### ISSUE TITLE
document.body.clear() fails with exceptions on Word Online Script Lab

### ISSUE THREAD

**Issue by kenual** [OfficeDev/office-js#1]
Script Lab fails to clear document body on Word Online --

Script Lab public gist link

https://gist.github.com/kenual/31548c30cfb12004177af89d44effbe0

The same script works fine inside Script Lab on Word 365 Win32 Version 1706

## Expected Behavior

After base64 file is inserted, context.document.body.clear() should succeed on Word Online just like Word on Windows.

## Current Behavior

Script Lab shows Office JS exceptions running on Word Online

context.document.body.clear() should work on Word Online like it does on Word.

## Steps to Reproduce, or Live Example

* Link to live example: ______

Open Script Lab on Word Online
Open Basic API call (Javascript) sample
Copy github public gist 

https://gist.github.com/kenual/31548c30cfb12004177af89d44effbe0

and paste into Script Lab Script

Click Run button to execute the Word JS block

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

Our Add-in's primary users are on Word Online. This bug is causing our Add-in not able to update the document with updated file content.  The same API call and functionality works fine on Word.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Version 1706
* Operating System: Windows
* Browser (if using Office Online): Chrome

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by JuaneloJuanelo** [comment]
something with the content of this document is what makes it fail.  we are investigating the issue. sorry  for the insane delay!

**Comment by weshi** [comment]
The content of the inserted base64 stream has a field, which is not supported in Word Online. Therefore the inserted content control becomes an unsupported content control. This is expected. 

But we should allow the body to be cleared. We are doing investigation to figure out the root cause.

**Comment by weshi** [comment]
Have narrowed down the steps to reproduce this issue. It only happens when the document body has only one single paragraph which contains the unsupported features such as field and/or unsupported content controls. This is a bug, and we are working on a fix.

However, the above script actually fails at the step when you try to insert content control to the range which is the inserted base64 stream that contains a field. It fails because field is not supported in Word Online, and therefore we disallow insert content control on the range.

**Comment by JuaneloJuanelo** [comment]
team is working on a fix, been tracked with 2452427 internally.

**Comment by didu9898** [comment]
I had the similar trouble. The following code worked for me:
`Word.run(async (context) => {
    let range = context.document.getSelection();
    let pageRange = range.parentBody.getRange();
    pageRange.delete();
    await context.sync();
  })`

**Comment by hnyrxs2** [comment]
i think this should be re-opened, faced the same issue. not only on the body but also for content controls clear api. it throws error Kickout error code and several other console error and a warning banner. please see screenshot below
 
<img width="1911" height="1033" alt="Image" src="https://github.com/user-attachments/assets/56f180bb-959e-4717-9d6f-e74e7f764930" />
