### ISSUE TITLE
TableRowCollection.add is clearing custom sort of the table after a clearRows

### ISSUE THREAD

**Issue by chanhohang** [OfficeDev/office-js#1000]
Custom Sort is regarding the Multi column sorting. i.e. sort by Column A ascending then Column B Descending.

This issue is found when I am implementing workaround of clearing table data when there is a filter applied.
https://github.com/OfficeDev/office-js/issues/994

## Expected Behavior
table.clearFilters() should keep custom sort of the Table, 

## Current Behavior
table.clearFilters() is clearing Column Filter and Columns Custom Sort as well.

## Steps to Reproduce, or Live Example

Please reuse the gist from issue https://github.com/OfficeDev/office-js/issues/994
Place Custom Sort to any Table and will see all custom sort is removed on table.clearFilters() is called.

## Context

My original intention is to find a way to clean up rows in a table with filter.

## Your Environment

Office 365 pro plus with Excel API 1.10 running on Edge.

## Useful logs
NA

**Comment by lumine2008** [comment]
Thanks @chanhohang , it would be awesome if you could also share the gist therefore we can locate the issue. thanks

**Comment by lumine2008** [comment]
We have tried in both Win32 and Excel Online, however the custom sort is still on after `table.clearFilters()` , could you please share the gist to us? thanks

![image](https://user-images.githubusercontent.com/26398035/75090925-ccf6a300-55a2-11ea-8ea3-f4e30ffe8d85.png)

**Comment by chanhohang** [comment]
@lumine2008 you are right. i spend more time to reproduce the problem.
it's actually clear when tableRowsCollection.add is called.

Please find the gist for your info.
https://gist.github.com/chanhohang/a3a8e8b683040e3453a555804a7d2a5b

The Custom Sort filter is still there until the rows.add(xxx) is called.

I update the description to give it a more meaning title as well.

**Comment by lumine2008** [comment]
Thanks @chanhohang , now we can repro this issue, based on our investigation, we found this only happens when the table has 0 rows and then call table.rows.add() which will trigger a “(Forced) Insert Row" operation.: BUG 3991007 was created. but there is workaround that can avoid this issue. when the table has 0 rows, we can edit the row directly to achieve the same goal with table.rows.add. 


```
table.rows.load("count");
await context.sync();

if (table.rows.count == 0)
{
table.getRange().getLastRow().values = [["Sample", "Values", "For"]];
}
else
{
table.rows.add(null, [["Sample", "Values", "For"]]);
}


```

**Comment by chanhohang** [comment]
@lumine2008 thank you very much for the workaround code snippet. it works for us.

**Comment by chanhohang** [comment]
@lumine2008 
the workaround suggested is not working anymore for Excel API 1.11 recently upgrade. can you kindly check?

There is an internal error thrown from the API without much information.

**Comment by lumine2008** [comment]
Hi @chanhohang,  We had a try, but couldn’t repro the internal error issue in both win32 and online. Could you please share the repro gist?  what is the error message? and excel version？
