### ISSUE TITLE
Office Addin Angular With Search the Word by HTML, after using getHtml() function or, by default API support for this

### ISSUE THREAD

**Issue by SibeeshVenu** [OfficeDev/office-js#1002]
I am developing an office word addin using Angular and I was successful in creating the same. I am getting an HTML with some classes assigned with some unique identifier to the DIVs and SPANs, from my API.

For Example:

`<span class="tip tip-5d4949a499b39510a0ea3676" id="tip-66b92187-d901-4366-99f4-417f20de60a1">nun</span>`

Now I loaded this newly given HTML to the word as follows after clearing the content first.

Clear the HTML:

```
clearContentsOfWord() {
    Word.run(function (context) {
      var body = context.document.body;
      body.clear();
      return context.sync().then(function () {
        console.log('Cleared the body contents.');
      });
    })
      .catch(function (error) {
        console.log("Error: " + JSON.stringify(error));
        if (error instanceof OfficeExtension.Error) {
          console.log("Debug info: " + JSON.stringify(error.debugInfo));
        }
      });
  }
```
Assign the new HTML:

```
setNewContentsInWord(html: string) {
    Word.run(function (context) {
      var body = context.document.body;
      body.insertHtml(html, Word.InsertLocation.start);
      return context.sync().then(function () {
        console.log('HTML added to the beginning of the document body.');
      });
    })
      .catch(function (error) {
        console.log('Error: ' + JSON.stringify(error));
        if (error instanceof OfficeExtension.Error) {
          console.log('Debug info: ' + JSON.stringify(error.debugInfo));
        }
      });
  }
```
Now I have a search function implemented as follows. The basic idea is to find the item and highlight the same.

```
assignColorToTheWord(color: string, search: string) {
    if (search) {
      Word.run((context) => {
        const searchResults = context.document.body.search(search);
        context.load(searchResults, 'font');
        return context.sync().then(function () {
          for (var i = 0; i < searchResults.items.length; i++) {
            searchResults.items[i].font.highlightColor = color;
          }
          return context.sync();
        });
      })
        .catch(function (error) {
          console.log('Error: ' + JSON.stringify(error));
          if (error instanceof OfficeExtension.Error) {
            console.log('Debug info: ' + JSON.stringify(error.debugInfo));
          }
        });
    }
  }
```
The problem with this approach is that, I don't get results if I search with the full HTML or with the identifier class `<span class="tip tip-5d4949a499b39510a0ea3676" id="tip-66b92187-d901-4366-99f4-417f20de60a1">nun</span>`, but if search with the text nun, it gives result.

There will be many such words (nun) in the word document, I needed to make sure that I highlight the correct one. I also knew that the search API has a limit in characters to be searched, how can I overcome this?

How can I do that? Have you ever done something similar? I have also asked this question in [StackOverflow, you can find it here](https://stackoverflow.com/questions/60297220/office-addin-angular-with-search-the-word-by-html-after-using-gethtml-functio).

**Comment by JuaneloJuanelo** [comment]
Yes the search API is not designed to search for the inserted HTML, but is designed to work on the actual text of the document. So if you have inserted  multiple "nun" the search operation will return you a collection of ranges with that text,  The question here is: how do you know which is the correct NUN? are you interested on searching only on the content you inserted?

Yes the search API is limited to 255 characters. but you can overcome that product limitation by following this https://stackoverflow.com/questions/50911606/body-search-issue-in-word-desktop/51159442#51159442

**Comment by SibeeshVenu** [comment]
Thanks. With the current approach, there is no way that I can find the correct "nun", that is the reason why I introduced the HTML with unique identifiers so that I can find the correct one and highlight it.

`<span class="tip tip-5d4949a499b39510a0ea3676" id="tip-66b92187-d901-4366-99f4-417f20de60a1">nun</span>`

So if I can search it with the `id="tip-66b92187-d901-4366-99f4-417f20de60a1"` my problem will be fixed.

**Comment by JuaneloJuanelo** [comment]
have you tried wrapping your range with a content control (invisible) that way you can get to it by ID of the content control.

**Comment by SibeeshVenu** [comment]
Thanks. No, I have not tried that. So are you suggesting that I should have `content control` for each `nun`? It would be a great help if you can share any related documents.

**Comment by JuaneloJuanelo** [comment]
yes, when you insert your html wrap it with a content control, add a tag to identify it.

the code is something like this: (i ap providing 2 methods one to insert and the other to get the placeholder.

you can restore this snippet in scriptlab if you want to see the sample running. https://gist.github.com/JuaneloJuanelo/629615349863fcb22adc9ab758699ba2  

```
async function create() {
  await Word.run(async (context) => {
  var cc = context.document.getSelection().insertHtml("<b>Whatever HTML</b>","replace").insertContentControl();
  cc.tag = "somethingToRemember";
  cc.appearance = Word.ContentControlAppearance.hidden
    await context.sync();
  });
}

async function navigate() {
  await Word.run(async (context) => {
    var mycc = context.document.contentControls.getByTag("somethingToRemember").getFirst();
    mycc.select();
    await context.sync();
  });
}
```

**Comment by SibeeshVenu** [comment]
Thanks a lot for the detailed explanation. I will try that and share my output here.
