### ISSUE TITLE
Outlook for Mac, Office.context.mailbox.item.to.setAsync crashes Outlook

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1003]
In an Outlook add-in for compose mode, we are using the setAsync and addAsync methods of the Office.Recipients interface to add or update email recipients.

## Expected Behavior
The setAsync and addAsync methods shall work correctly.

## Current Behavior
The setAsync and addAsync methods crash Outlook for Mac when the displayName property of the EmailUser object is set to an empty string.

## Steps to Reproduce, or Live Example
Please see the test code below:
`Office.context.mailbox.item.to.setAsync([ { displayName: '', emailAddress: 'example@domain.com'} ], (result: Office.AsyncResult<void>) => {});`

* Additional details:
  1. Only Outlook for Mac is affected. Everything works fine in Outlook Online and Outlook 2016 & 2019.

## Your Environment
* Platform: Mac
* Host: Outlook for Mac
* Office version number: 16.33 (20011301)
* Operating System: ______
* Browser (if using Office Online): ______

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding setAsync(). It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: Office:3973990

**Comment by exextoc** [comment]
This issue is fixed.
