### ISSUE TITLE
Outlook for Mac, shared mailbox, Office JS API does not work

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1004]
In an Outlook add-in for compose mode, we are using the Office JS API to fill in email fields. The "This browser does not support the requested API" error occurs on every OfficeJS call if a new email is created by using a shared mailbox account/from field.

## Expected Behavior
Office JS methods should work.

## Current Behavior
The "This browser does not support the requested API" error occurs.

## Steps to Reproduce, or Live Example
Add a shared mailbox:
1) Outlook menu -> File -> Open -> Other User’s Folder
2) Find and open a shared mailbox

Steps for reproduce:
1) Create a new email in Outlook for Mac
2) In the From field, select the shared mailbox
3) Open an add-in's pane and try to call any API method, e.g.:
`Office.context.mailbox.item.body.getTypeAsync({}, async (result: Office.AsyncResult<Office.CoercionType>) => {
  if (result.status !== Office.AsyncResultStatus.Succeeded) {
    console.log(result.error.message); // "This browser does not support the requested API."
  }
});`

* Additional details:
  1. We tested the same thing in Outlook for Mac 16.31 (19111002) and everything works fine in this version.

## Your Environment
* Platform: Mac
* Host: Outlook for Mac
* Office version number: 16.34 (20020900)
* Operating System: ______
* Browser (if using Office Online): ______

**Comment by exextoc** [comment]
We are able to repro the issue. Thanks for reporting it. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
We have fixed the bug and the fix would be available in the latest Insider Fast builds coming next week. Depending on the release channel a customer is on, getting an updated build can take anywhere from 4-8 weeks.

**Comment by gena7gena** [comment]
Observing very similar issue with the same error in Outlook for Mac 16.41.

Steps:
1) In Outlook for Mac open calendar, 
2) Create an event for shared calendar, close the event
3) Open it again for editing, open the plugin
4) with code inside of plugin, similar to the code below, you can see the error "This browser does not support the requested API"

```
Office.initialize = () => {
    setInterval(() => {
        Office.context.mailbox.item.body.getAsync(Office.CoercionType.Html, ({ status, value, error }) => {
            if (error) {
                console.log(error.message);
            }
        });
    }, 1000);
};
```
Notes:
1) Plugin executes code successfully if event was not created before and opened afresh
2) Sometimes first calls of `Office.context.mailbox.item.body.getAsync` executes successfully, but after several seconds they start returning the error.

Outlook for Mac 16.41
maxOS Catalina  10.15.5

**Comment by DmitryKostochko** [comment]
@rinfex-holfer, this 1004 issue is closed, please consider creating a new bug report. Hope this will speed up the reaction from Microsoft's side.

**Comment by exextoc** [comment]
@rinfex-holfer We have fixed this bug for event on shared calendar recently. Depending on the release channel a customer is on, getting an updated build can take anywhere from 4-8 weeks.

**Comment by gena7gena** [comment]
@exextoc thanks, nice to hear! In what version of Outlook on Mac we can expect the fix? If it is possible to say.

**Comment by exextoc** [comment]
It should be available in next insiders build. Check more about insiders build [here](https://support.microsoft.com/en-us/office/outlook-for-mac-release-notes-for-insider-fast-builds-d6347358-5613-433e-a49e-a9a0e8e0462a?ui=en-us&rs=en-us&ad=us). Please confirm once you receive the fix.
