### ISSUE TITLE
window.navigator.msSaveOrOpenBlob is undefined in Office Add-in WebView Edge browser

### ISSUE THREAD

**Issue by chiragvidani** [OfficeDev/office-js#1006]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Context
As per the requirement of our application, we invoke in-house API to get .pdf base64 file string.

And this .pdf base64 string will be passed to code that allows an option to download file from Office Add-in to end-user, Edge WebView is now loading Office Add-in as our Windows and Office is updated to latest one.

Code snippet is as follows:
`var pdfAsDataUri = "data:application/pdf;base64," + base64FileString;`
`if (window.navigator.msSaveOrOpenBlob) {`
`  // Create the Blob URL:`
`  var buffer = convertDataURIToBinary(pdfAsDataUri);`
`  var blob = new Blob([buffer], {`
`            type: 'application/pdf'`
`  });`
`  window.navigator.msSaveOrOpenBlob(blob, "download.pdf");`
`} else {`
`  window.open(pdfAsDataUri);`
`}`

In above code snippet `window.navigator.msSaveOrOpenBlob` is undefined, hence we are unable to serve purpose of .pdf base64 file download option to end-user.

As `window.navigator.msSaveOrOpenBlob` is undefined, `else` part is getting executed which throws `SEC7134` error with an exception as `Access is denied`.

And we are in blocker state for end-users who have updated their Windows and Office versions.

Also, this application was working fine, previous to updating Windows and Office versions, IE WebView was serving the purpose.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Office 365 16.0.11929.20586 64-bit version
* Operating System: Windows 10 1909 version

**Comment by chiragvidani** [comment]
Few pointers which can help you to reproduce this issue.

We have created a Demo website, which is working in most of the browsers and but not as a Word Add-in on a machine with updated Win10 and Office365 with Edge WebView.

Demo website URL: [https://cvaddindemo.azurewebsites.net](https://cvaddindemo.azurewebsites.net/)

Manifest file compressed as a zip, pointing to the above demo website, which can help to reproduce test scenarios on the target machine.
[cv_addin_demo.zip](https://github.com/OfficeDev/office-js/files/4367793/cv_addin_demo.zip)


Also attaching artifacts gif file created by capturing test scenarios on both type of environments.

1. Machine having IE WebView (Artifact GIF file: Word_Addin_IEWebView.gif)
    -  Result: Working fine.
    - OS: Win10 Version 1703 (OS Build 15063.540)
    - Office: Office365 16.0.11929.20586 64-bit
![Word_Addin_IEWebView](https://user-images.githubusercontent.com/2871708/75259264-c029b780-580d-11ea-9560-5d88cf70f891.gif)

2. Machine having Edge WebView (Artifact GIF file: Word_Addin_EdgeWebView.gif)
   - Result: Breaking here.
    - OS: Win10 Version 1909 (OS Build 18363.657)
    - Office: Office365 16.0.11929.20586 64-bit


![Word_Addin_EdgeWebView](https://user-images.githubusercontent.com/2871708/75259270-c1f37b00-580d-11ea-8836-88f335039dcd.gif)

**Comment by chiragvidani** [comment]
@JuaneloJuanelo @davidchesnut  Please help us with any update on this issue.

**Comment by jagibe** [comment]
I have the same issue in an Excel addin!
Windows version 1909
Office version 16.0.12527.20260

**Comment by Kashishmsft** [comment]
Please find the workaround here - https://gist.github.com/Kashishmsft/ea2059a3f73ef02e437abca031e29c8c

**Comment by plamenbotev** [comment]
We have the same issue in Outlook addin.

**Comment by Kashishmsft** [comment]
> We have the same issue in Outlook addin.

For outlook, it's logged here - https://github.com/OfficeDev/office-js/issues/503 
You could follow up there for precise tracking and appropriate response I believe.

**Comment by JuaneloJuanelo** [comment]
this is not an issue in Word but in the Edge Web View.

**Comment by chiragvidani** [comment]
@smaremanda: Please help us with any update for this bug?

**Comment by Kashishmsft** [comment]
> @smaremanda: Please help us with any update for this bug?

Below document would help you for this issue

https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins#get-errors-trying-to-download-a-pdf-file

**Comment by chiragvidani** [comment]
> > @smaremanda: Please help us with any update for this bug?
> 
> Below document would help you for this issue
> 
> https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins#get-errors-trying-to-download-a-pdf-file

@Kashishmsft Thank you for an alternative approach. But it would be great if we are able to get the solution to an actual problem.
