### ISSUE TITLE
Double-clicking from Ribbon to load a Task pane breaks functionality, which prevents Task pane from showing next time

### ISSUE THREAD

**Issue by Fedarcher** [OfficeDev/office-js#1007]
## Expected Behavior

One instance of the Task pane should be opened.

## Current Behavior

Two panes show up.

## Steps to Reproduce

Open any task pane in Excel online by double-clicking on the Ribbon button.

## Context

One of the panels may not work at all giving the Add-in error.
After closing the panes, I can not show the Task pane again. Only reloading the web page allows fixing the issue and open the Task pane again.

I think that many users have a bad habit of double-clicking buttons. 
Therefore, this problem will cause frustration for the first time the add-in is launched.

## Your Environment

* Platform: Office Online
* Host: Excel
* Office version number: Office 365 16.0.12620.35052
* Operating System: Win 10
* Browser: Chrome, Edge

## Useful logs

**The console may contain this error:**

Access to XMLHttpRequest at
'https://euc-excel.officeapps.live.com/x/AppSettingsHandler.ashx?app=Excel'
from origin 'https://adxteam-my.sharepoint.com' has been blocked by
CORS policy: No 'Access-Control-Allow-Origin' header is present on the
requested resource. excel-boot.min.js:3 GET
https://euc-excel.officeapps.live.com/x/AppSettingsHandler.ashx?app=Excel
net::ERR_FAILED

**See images:**

[Two panes](https://i.stack.imgur.com/vle0R.png)
[Sometimes one of the panels may not work at all](https://i.stack.imgur.com/EUwdX.png)

**Also the problem is published on:**

[UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/39787489-fix-the-issue-when-two-panes-shows-up-after-double)
[Stackoverflow](https://stackoverflow.com/questions/60373734/double-clicking-from-ribbon-to-load-a-taskpane-breaks-functionality-which-preve)

**Comment by lumine2008** [comment]
Hi, @Fedarcher, it seems that i cannot repro this issue in my endsuccessfully, would you mind to share the gist? you could use script lab and upload your gist.
![image](https://user-images.githubusercontent.com/26398035/75354095-65648e80-58e7-11ea-8236-f43ed7d8123c.png)

**Comment by lumine2008** [comment]
If you still observe this issue, please reopen it, thanks
