### ISSUE TITLE
Outlook desktop: addFileAttachmentFromBase64Async throws code: 5001, message: "An internal error has occurred." in pinned add-in

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1008]
In an Outlook add-in for compose mode, we are using the addFileAttachmentFromBase64Async method to add attachments. In Outlook desktop, the "Internal Error" occurs if the add-in's pane is pinned.

## Expected Behavior
The error should not occur.

## Current Behavior
Error:
code: 5001
message: "An internal error has occurred."
name: "Internal Error"

## Steps to Reproduce, or Live Example
1. Create a new email in Outlook desktop.
2. Open the add-in’s pane and pin it.
3. Close the created email.
4. Select any email in the Outlook Inbox
5. Click the Reply or Forward button. The add-in’s pane opens automatically.
6. Execute the following code:
`const options: Office.AsyncContextOptions & { isInline: boolean } = { isInline: false };
Office.context.mailbox.item.addFileAttachmentFromBase64Async('MQ==', 'test.txt', options, (result: Office.AsyncResult<string>) => {
   console.log(result);
});`

* Additional details:
  1. The event handler for the ItemChanged event is registered.
  2. Other API methods work correctly.

## Your Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: Microsoft Outlook for Office 365 MSO (16.0.12430.20112) 32-bit
* Operating System: Windows 10 x64
* Browser (if using Office Online): ______

**Comment by exextoc** [comment]
I followed your steps but cannot repro this issue.  addFileAttachmentFromBase64Async works fine in a pinned addin.  Could you include the ItemChanged snippet and the APIs that you tried?  In your repro, does the API also fail in a new compose pinned addin (instead of reply/forward)?

**Comment by DmitryKostochko** [comment]
> Could you include the ItemChanged snippet and the APIs that you tried?

I have attached a small code sample, hope it will be helpful.
[test.zip](https://github.com/OfficeDev/office-js/files/4254642/test.zip)

> In your repro, does the API also fail in a new compose pinned addin (instead of reply/forward)?

The addFileAttachmentFromBase64Async method works fine in this case, i.e. in a newly opened Outlook Inspector window. I think I described the repro steps incorrectly, please try these ones:
1. Select an email in Outlook Inbox, click Reply and enter some text in the email body so that a draft is created.
2. Open the add-in's pane.
3. Pin the pane.
4. Select another email in Outlook Inbox (change the selection so that the add-in's pane becomes hidden).
5. Select the draft email from step 1 (change the selection so that the add-in's pane becomes visible).
6. Execute the test code.

**Comment by exextoc** [comment]
I can repro with the updated steps. 
Thanks for reporting this issue regarding addFileAttachmentFromBase64Async  issues. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 16.0.12723.10000 or later. Depending on the release channel a customer is on, getting an updated build can take anywhere from 4-8 weeks.

**Comment by lindalu-MSFT** [comment]
This can be closed because the issue is fixed.
