### ISSUE TITLE
Shared MailBox, OfficeJS saveAsync() and other OfficeJS API not working

### ISSUE THREAD

**Issue by naemcivic** [OfficeDev/office-js#1009]
On our Outlook add-in for compose mode, we are using the Office JS API to save the email draft by calling ```Office.context.mailbox.item.saveAsync()```

## Expected Behavior

Office JS methods should work.

## Current Behavior

code: 5009 
message: “This browser does not support the requested API.” 
Name: “API Not Supported” 
status: “failed”

## Steps to Reproduce, or Live Example

Add a shared mailbox:

1. Find and Open a shared mailbox

Steps to reproduce:

1. Create a new email in Outlook for Mac
2. In the From field, select the shared mailbox
3. Open and add-in's pane and try to call
Office.context.mailbox.item.saveAsync()
console log the result and returns the following:
  - code: 5009 
  - message: “This browser does not support the requested API.” 
  - Name: “API Not Supported” 
  - status: “failed”

* Additional details:

This use to work in older version of Mac Outlook prior to the described Mac Outlook version

## Your Environment

* Platform: Mac
* Host: Outlook for Mac
* Office version number: 16.34 (20020900)
* Operating System: ______
* Browser (if using Office Online): ______

**Comment by exextoc** [comment]
We are able to repro the issue. Thanks for reporting it. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by lindalu-MSFT** [comment]
Hey @exextoc There are several issues you've resolved "Added to Backlog". Do you want me to close these issues or leave them open for customers to see what we have in the backlog?

**Comment by exextoc** [comment]
@lindalu-MSFT We want issue with "Added to Backlog" to be open for customers to see what we have in the backlog. Thanks for reopening.

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in upcoming builds. Depending on the release channel a customer is on, getting an updated build can take anywhere from 4-8 weeks

**Comment by ZainW** [comment]
When you do know could you please give us a version number, just so we can communicate definitively with customers and our support team!

Appreciate it

**Comment by exextoc** [comment]
The fix will be out soon with scheduled monthly build, which isn't out yet.
