### ISSUE TITLE
Excel: Names collection of worksheet object includes workbook-level names

### ISSUE THREAD

**Issue by jkpieterse** [OfficeDev/office-js#1011]
## Expected Behavior

The names collection of the workbook object includes all names, including all worksheet-scoped names. The names collection of the worksheet only includes names scoped to the worksheet
## Current Behavior

The names collection of the workbook object includes only workbook-scoped names, EXCLUDING all worksheet-scoped names. The names collection of the worksheet includes names scoped to the worksheet AND ALL WORKBOOK-LEVEL NAMES.

## Steps to Reproduce, or Live Example

See this file (script included on Script sheet):
https://jkpadsdev-my.sharepoint.com/:x:/g/personal/jkpieterse_jkpadsdev_onmicrosoft_com/ETliu0r-4-1HrDmpDp330pMBB1tdAkBWaDOo8E6rC0skcQ?e=Et8l9b

* Additional details:
N.A.

## Context

Trying to read either all range names without having to traverse through all worksheets to get their names.
## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: build 16.0.12624.35051
* Operating System: Windows 10
* Browser (if using Office Online): Edge

## Useful logs

N.A.

**Comment by lumine2008** [comment]
Thanks @jkpieterse , i think this is the same issue in [stackoverflow](https://stackoverflow.com/questions/60395802/problem-with-names-collection-of-worksheet-object),  i saw your quesiotn in stackoverflow yesterday, i didnt reply to you is because that i could not repro it in my side, it's great that you share the workbook, so let me try to repro and get back to 
 you soon.

**Comment by jkpieterse** [comment]
Hi Raymond,

Yes it is the same issue indeed.

Regards,

Jan Karel Pieterse
JKP Application Development Services
The Netherlands

**Comment by lumine2008** [comment]
Thanks @jkpieterse , We repro'ed this issue, and a bug(#3983983) was created to track this issue. team is investigating on this issue.

**Comment by lumine2008** [comment]
Thanks for your patient, it seems you have talked 2 issues:

- The names collection of the workbook object includes only workbook-scoped names, EXCLUDING all worksheet-scoped names.
- The names collection of the worksheet includes names scoped to the worksheet AND ALL WORKBOOK-LEVEL NAMES.

For 2#, I repro'ed this issue, and a bug(#3983983) was created to track this issue. Team is investigating on this issue.

For the 1#, our design was to separate workbook and worksheets, but we will revisit the design, we will let you know soon

**Comment by jkpieterse** [comment]
Hi Raymond,

 

I can live with small differences. In the COM OM, it has always been the case that from the Workbook object you would access *all* names, including the local ones. If that changes, so be it though I don’t agree with the change.

 

Regards,

 

Jan Karel Pieterse

JKP Application Development Services

The Netherlands

Chamber of Commerce # 12052177

https://www.jkp-ads.com

Phone: +31 495 750546

Mobile: +31 648 628252

Co-founder of https://excelexperts.nl

**Comment by lumine2008** [comment]
This issue was fixed, kindly verify. thanks

**Comment by jkpieterse** [comment]
I have tested the script and it now behaves as expected: The Workbook.Names collection only shows the global, workbook-level names, the Worksheets.Item[i].Names collection only shows the names local to the worksheet in question.
Bug fixed.
