### ISSUE TITLE
Excel online js - context.sync() GeneralException

### ISSUE THREAD

**Issue by dkornat** [OfficeDev/office-js#1012]
Hi,
I'm preparing simple add-in to import CSV file to Excel Online.
First I upload a file in add in task pane and then I parse csv file to array by Papa parse library:

`async function retrieveDataFromCsv() {
  return new Promise<string[][]>((resolve, reject) => {
    let input = document.querySelector("#CsvImport");
    let file = input.files[0];

    if (file) {
      let fr: FileReader = new FileReader();
      fr.onload = function(fileProp) {
        let content = fileProp.target.result;
        let retrievedCsv = Papa.parse(content, { delimiter: ";", newline: "\n" });
        resolve(retrievedCsv.data);
      };
      fr.readAsText(file);
    }
  });
}
`

After that i try to import data into worksheet - unfortunately when there is a lot of data, excel api throws internal error api which is probably related with too big payload ( I have found that the limit is 5MB).

Regarding to above error I have tried to seperate data and splits it into batches. Unfortunately even If i try to import first 500 rows, excel api throws an error like below:

![image](https://user-images.githubusercontent.com/47481868/75344200-68855d80-589a-11ea-96b8-6be62be7eaae.png)

Which means: "Internal error occured".

My code looks like below:

`$("#run").click(() => tryCatch(run));

async function run() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    let content = await retrieveDataFromCsv();
    let noOfColumns = content[0].length;
    let batchSize = 100;

    for (let i = 0; i <= 500; i += batchSize) {
      let addressRange = _getAddressRange(i, batchSize, noOfColumns);
      let range = sheet.getRange(addressRange);
      range.values = content.slice(i, (i + 1) * batchSize);
      range.untrack();
    }
    await context.sync();   
  });
}

function _getAddressRange(iteration: number, batchSize: number, noOfColumn: number): string {
  let startColumn = "A";
  let endColumn = String.fromCharCode(96 + noOfColumn);
  let startRange = (iteration + 1).toString();
  let endRange = (iteration + batchSize).toString();
  return startColumn + startRange + ":" + endColumn + endRange;
}`

If I place await context.sync() into loop it imports first 100 rows, then on context.sync() execution throws an error:

![image](https://user-images.githubusercontent.com/47481868/75344631-522bd180-589b-11ea-88b7-963b8cf05f1a.png)

Which means: 
"The argument is missing or invalid or has an incorrect format."

## Expected Behavior

Getting context.sync() works as expected or getting more detailed error description.

## Current Behavior

I'm getting error when I use range.untrack() method or context.sync() inside loop with a lot of data.

## Steps to Reproduce, or Live Example

Retrieving in JS some big csv file, then try to import it into range.

## Context

I can't import any data to Excel Online.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Excel Online Compilation: 16.0.12624.31876 
* Operating System: Windows 10
* Browser (if using Office Online): Google Chrome v. 79.0.3945.130

## Useful logs

![image](https://user-images.githubusercontent.com/47481868/75344200-68855d80-589a-11ea-96b8-6be62be7eaae.png)

![image](https://user-images.githubusercontent.com/47481868/75344631-522bd180-589b-11ea-88b7-963b8cf05f1a.png)

**Comment by lumine2008** [comment]
Thanks @dkornat, our team has started this investigation, however, based on script that you share in this post, we are not be able to repro this issue, so Could you please share a gist to us for repro? Thanks.
![image](https://user-images.githubusercontent.com/26398035/75407349-bad38680-594d-11ea-897a-b849af923bd0.png)

**Comment by lumine2008** [comment]
it would be great if you could share more information including: How many columns are there? The column is more than 26 or not?
could you please try to log what is addressRange and “content.slice(i, (i + 1) * batchSize)” which is used to set range value. Check whether they are valid input.
```
  let addressRange = _getAddressRange(i, batchSize, noOfColumns);
  let range = sheet.getRange(addressRange);
  range.values = content.slice(i, (i + 1) * batchSize);
  range.untrack();
```
 
so, it would be great if you could share us:
1. gist
2. sample CSV file

Thanks.

**Comment by soorajhealthplotter** [comment]
https://github.com/OfficeDev/office-js/issues/47#issuecomment-596933126

**Comment by soorajhealthplotter** [comment]
I am also having the same bug

My Code is 

Excel.run((context) ->
  sheet = context.workbook.worksheets.getItem(s_name)
  response_data = {"A1"=>"1000","A2"=>"1001","B1"=>"1000","B2"=>"1001","C1"=>"1000","C2"=>"1001"} # similary 54000+ records
  angular.forEach response_data, (key, value) -> 
    range = sheet.getRange(key)
    range.values = [[ value ]]
  context.sync().then ->
    console.log("Data synchronized")
    return
).catch (error) ->
  console.log 'Error: ' + error

My Excel version is

![excel_version](https://user-images.githubusercontent.com/12229181/76283553-e72dc200-62c0-11ea-8e98-7e469f51a1ae.png)

I am having issue is Excel Online

**Comment by lumine2008** [comment]
Hi @soorajhealthplotter, would you please share a bit more information for us to repro?
it would be great if you could share us the gist, thanks a lot.

**Comment by soorajhealthplotter** [comment]
https://github.com/OfficeDev/office-js/issues/1046#issuecomment-599485293

Hi i have created issue(1046) and bug 4025494 has been generated to track issue

**Comment by sachindra-nath-dubey** [comment]
I'm facing the same issue in PPT.
