### ISSUE TITLE
[Outlook] All Add-in disabled in shared calendar on outlook

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1013]
We are on o365 using outlook windows 10 version 1901 with outlook version 1908 (16.0.12130.20272).
When we try to use add-in in a shared calendar all add-in are disabled.(the owner delegated editor authority).
Not every PC got this problem but I wonder why this happened? And how to fix it.

## Expected Behavior
add-in is available in shared calendar.

## Current Behavior

All add-ins are disabled in shared calendar.

## Steps to Reproduce, or Live Example
Open a shared calendar and open a new event. Then trying open an add-in in this event.
Will find add-in are all disabled.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.12130.20272
* Operating System: windows 10 1803
* Browser (if using Office Online): ______

If this is an known issue please give me a link.
If anything else info you need please let me know, Thanks.

**Comment by exextoc** [comment]
Are the addin manifests updated to include SupportsSharedFolders?
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/supportssharedfolders
Could you also include screenshots of the cases when the addins are disabled and when they are not and the version number screenshot?

The SupportsSharedFolders feature was enabled for some users depending on the office channel in Outlook version 1908.  If the addins include the SupportsSharedFolders element, users without the feature, the addins are disabled.

**Comment by SWei1234** [comment]
Hi @exextoc 
Yes, the manifest has already include 'SupportsSharedFolders' and set it to true.
When they create a meeting on a shared calendar the add-in is disabled.
![image](https://user-images.githubusercontent.com/15980696/75639189-a0a9e900-5c6a-11ea-8ebf-7cd4f0fd265d.png)
When they  create a meeting on their own calendar the add-in is enabled.
And now we meet this problem both on windows 1901 and 1908.
Any idea?

**Comment by exextoc** [comment]
The main reasons that this can happen is that the Exchange Server Version does not support SupportsSharedFolders. Mainly On Prem Exchange Servers don't support it. Also older versions of the desktop client, will also show add-ins disabled on shared items. 

At this point, there must be some difference between the PCs that are working and the PCs that are not working. So any difference between the two will help figure it out. Namely: 

- Exchange Version
- Outlook Version
- Are they the same account?

From asking around this Screenshot either looks like an older desktop version or Exchange On Prem.

**Comment by SWei1234** [comment]
> The main reasons that this can happen is that the Exchange Server Version does not support SupportsSharedFolders. Mainly On Prem Exchange Servers don't support it. Also older versions of the desktop client, will also show add-ins disabled on shared items.
> 
> At this point, there must be some difference between the PCs that are working and the PCs that are not working. So any difference between the two will help figure it out. Namely:
> 
> * Exchange Version
> * Outlook Version
> * Are they the same account?
> 
> From asking around this Screenshot either looks like an older desktop version or Exchange On Prem.

Really appreciate your reply.
Now we got this problem on 16.0.12130.20272(Outlook Version). 
And using account A schedule a meeting on account B shared calendar.(Both A and B can use add-in on their own calendar)
I'm checking with our customer about the exchange version.
And I wondering if we can get a list about which version will support use add-in on a shared calendar which will not support?

**Comment by exextoc** [comment]
Outlook Client Version should be: 16.0.12026 or later. So if you AND the people having this issue are beyond that number, then it is likely not the issue.

Exchange Version is basically any On Prem Exchange Server is NOT supported. So the only exchange versions supported are 15.20.* 

15.00, 15.01, 15.02 Are NOT supported.

**Comment by SWei1234** [comment]
@exextoc 
Thanks for your support.

**Comment by exextoc** [comment]
Closed Bug 1396548<https://o365exchange.visualstudio.com/DefaultCollection/O365%20Core/_workitems/edit/1396548>
________________________________

**Comment by SWei1234** [comment]
@exextoc  Is there any other conditions that will cause all add-in on shared calendar greyed out?

The problems are all happening on windows version later than 1909 and on Office 365 online not in on-prem environment.  And Outlook version is 2002 or later. 

And  this problem only happening on windows Outlook client shared calendar. Browsers and Mac outlook client don't have this problem.

Or is there any wiki about all key conditions that is necessary for using add-in on shared calendar.

If any details need please reply me, Thanks

**Comment by exextoc** [comment]
As mentioned above, the only conditions this is possible is if the client is on an older build number than when sharedFolders were supported or exchange is an onPrem account. It seems like both don't seem to be the issue for you. Could you share your Outlook specific build number along with channel details(this is easily available from File->Office Account and looking at About Outlook's description) and the exchange build number where you're facing the issue. The calendar shared is of a specific user rather than a group calendar? Does this repro for mail items when a folder is shared rather than calendars? What add-ins are they wanting to use that don't work? Assuming the outlook build number and exchange version numbers are in sync with supporting sharedFolders, addins that don't have sharedFolders tag in the manifest shouldn't be showing up for shared items.

**Comment by SWei1234** [comment]
@exextoc 
I confirm they are not use on Prem environment. 
Their outlook client version is 16.0.12527.20612 , 16.0.12527.20720 on windows.
They are all using office 365 account. 
The calendar shared is a specific user's calendar.
We reproduce this on calendar because our add-in need run on a event or appointment.
All add-in are grayed out not only one meeting add-in have this problem. The same as the picture I attached in above reply.
Windows version is 1909.
Need any other details?
For example, user A on Mac 2002 make his delegate access to user B who is using outlook client on windows outlook client 1908. Will have this problem.
By the way, they are using Semi-Annual Enterprise channel 1908(11929.20838) . Does this version support this?

**Comment by JuaneloJuanelo** [comment]
The Semi-Annual Enterprise channel 1908(11929.20838) does not support 1.8, hence it does not support Shared Folders/Delegates.  More info below.

•	The shared folders feature was released as part of 1.8 requirement set.  As per[ this page](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets), the 1.8 requirement set is available in builds 12130.20272+. 
•	It was released for the **monthly channels** ~ November 2019.
•	The s**emi Annual channel** was forked in January 2020 (btw this is now in preview so you can actually try it), and will be released during July. For your reference that’s builds 16.0.12527.xxxx.

btw in your original question you mention build 16.0.12130.20272. was the problematic build 1908(11929.20838)?

**Comment by SWei1234** [comment]
@JuaneloJuanelo 
Yes, recently we have a lot of users met this problem. 
Include using semi annual and other version. And we didn't have a clear standard about whether this feature(add-in on shared calendar) will be supported.

**Comment by JuaneloJuanelo** [comment]
@SWei1234 great, on the page that I referred we post all this content. let me know if we can improve it anyhow to make more clear our support matrix. Will close this issue for now.

**Comment by SWei1234** [comment]
@exextoc 
Can this version support this feature?Outlook 2016 (16.0.5017.1000) MSO (16.0.5017.1000) 32-bit
 I think this is outlook 2016 so it just support to 1.4 set?
Thanks

**Comment by exextoc** [comment]
No that build (16.0.5017.1000) does not support this feature.
