### ISSUE TITLE
Office.context.ui.messageParent is not sending message to parent (task-pane)

### ISSUE THREAD

**Issue by ravitejagGitHub** [OfficeDev/office-js#1014]
I have opened dialog box using office dialog box API from excel-taskpane  but sometimes i'm getting below js error in console while opening the popup/dialog-box after that Office.context.ui.messageParent is not sending response to parent.

excel-web-16.00.js:24 Uncaught Function ContextActivationManager_getAppContextAsync call failed. ErrorCode is -3, exception: [object Object]
![image](https://user-images.githubusercontent.com/20149862/75365870-d86c0600-58e3-11ea-8b91-cb7e32a11dee.png)

**Code:**

Office.context.ui.displayDialogAsync(options.url,
				{
					height: options.height,
					width: options.width,
					displayInIframe: options.displayInIframe,
					promptBeforeOpen: options.promptBeforeOpen
				},
				(asyncResult: Office.AsyncResult<Office.Dialog>): void => {
					console.log('Dialog open call back ');
					console.log(asyncResult);
					if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
						this.dialog = asyncResult.value;
						this.dialog.addEventHandler(Office.EventType.DialogMessageReceived, this.processMessage);
					}
				}
			);

**dialog-box :**
**html:**
<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js" type="text/javascript"></script>
<link href="styles.css" rel="stylesheet"></head>

<body class="dialog">
    <main class="dialog__title">
        <span>You updated the formula, do you want to save the changes?</span>
    </main>
    <footer class="dialog__actions">
        <coral-button class="dialog__actions__btn" id="saveBtn">Save</coral-button>
        <coral-button class="dialog__actions__btn dialog__actions__btn--background-color-black" id="cancelBtn">Cancel</coral-button>
    </footer>
<script type="text/javascript" src="script.js"></script></body>

</html>

**script.js**
import { fromEvent } from 'rxjs';
import { ConfirmMessage } from '../services/confirm-dialog/confirm-dialog.service';

Office.initialize = (): void => { };

Office.onReady(() => {
	console.log("Office JS is Ready.............");

	console.log('Bindig button events');
	const saveBtn$ = fromEvent(document.getElementById('saveBtn'), 'click');
	const cancelBtn$ = fromEvent(document.getElementById('cancelBtn'), 'click');

	saveBtn$.subscribe(() => {
		console.log("Save Button!!");
		Office.context.ui.messageParent(ConfirmMessage.Yes)
	});
	cancelBtn$.subscribe(() => {
		console.log("Cancel Button!!");
		Office.context.ui.messageParent(ConfirmMessage.No)
		
	});
});

## Expected Behavior
Office.context.ui.messageParent should work always without any js errors.

## Current Behavior
Office.context.ui.messageParent is not sending response to parent
I'm getting above js error while opening dialog-box and it's happening intermittently.

**Comment by lumine2008** [comment]
@lindalu-MSFT , this is UX related issue, let me reassign to correct owner Lillian

**Comment by AnuragMohta** [comment]
@MSFT team , wondering if there was any update on this issue, as i am facing it in my Excel Add-in as well. Thanks !

**Comment by lindalu-MSFT** [comment]
I believe @lliu113 Lillian was investigating this issue.

**Comment by jordan21398** [comment]
Hi I'm having this same issue where Office.context.ui.messageParent does not work in our Excel Add-in when we are using shared runtime but it works without shared runtime. Has anyone found a resolution?

**Comment by ASamSam** [comment]
seems i found a working case for me:
when i'm trying to call a dialog inside 
`await Excel.run({ delayForCellEdit: true }, async function (context) {`
it fails with exactly same message (even with 'await'). 
but if i call it outside outside of 'run context' - it works stable.

Even more, seems it fails when excel have something to do (?context.sync()).

**Comment by lliu113** [comment]
@ravitejagGitHub - thanks for reporting this issue, and apologies for the belated response to this. We did some investigation and it appears to be an async execution issue in Excel. Are you able to provide the manifest for your add-in so we can repro this on our end? 

@jordan21398 - sorry you're hitting this, are you able to open another github issue so we can track it appropriately? Don't want it to get lost in this thread. Thanks!

**Comment by AbhishekGupta100** [comment]
Hi, are there any developments on this? I'm having a similar issue where Office.context.ui.messageParent sometimes does not work in our Excel Add-in and usually works after closing the dialog box and trying again? It seems either that after some actions all Office functions stop work in the dialog box.

**Comment by lliu113** [comment]
@AbhishekGupta100 - appreciate the check-in. Unfortunately we aren't able to debug further without a manifest which repros this. If you're hitting the same error, feel free to attach your manifest and we can take a look. Thanks!

**Comment by babarmashkoor** [comment]
Hi I'm having this same issue where Office.context.ui.messageParent does not work in our Excel Add-in when we are using shared runtime but it works without shared runtime. Has anyone found a resolution?
