### ISSUE TITLE
All Outlook add-ins are failing to load

### ISSUE THREAD

**Issue by esegcy** [OfficeDev/office-js#1016]
Starting an hour ago, all add-ins (including the built-in "Insights") don't work.
The Outlook add-in loader spins for a while and then shows error:
```something went wrong and we couldn't start this add-in. Please try again later or contact your system administrator.```

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop + Mac + Office online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2016 (win) + 16.28 (mac)
* Operating System: Win10 + macos 10.14.6
* Browser (if using Office Online): Chrome

**Comment by exextoc** [comment]
Do you see any console errors or network errors? Is the issue consistent?

**Comment by esegcy** [comment]
I expected the problem to be detected from your logs. I don't have anything to contribute now because it doesn't reproduce anymore so closing this ticket.

**Comment by elthombre** [comment]
nobody has any ideas why this was happening?
