### ISSUE TITLE
Possibility of removing the loading screen

### ISSUE THREAD

**Issue by erharvey** [OfficeDev/office-js#1020]
Hello,

It is possible to remove the "loading" placeholder when calling the context.sync method? (See below)

We have a plugin that loads data in batch (Basically ajax call, render data in table). Since the process can be potentially long, the user has the option to cancel the loading process within the plugin taskpane using a uifabric button. During the process, a uifabric shows a spinner to indicate the loading process.

The constant "loading" placeholder flickering is somewhat inefficient most of time because it blocks the taskpane.

Thanks

![image](https://user-images.githubusercontent.com/17800696/75575026-5b4ca800-5a2d-11ea-8952-ce4d689adb1f.png)

**Comment by lindalu-MSFT** [comment]
Hi @erharvey! Thanks for reaching out to us. However, in order for us to investigate, we need more info. Can you provide us with your environment, including what product you're experiencing this in? Ideally, can you create a video of the steps to repro and upload it here or provide detailed steps to repro? Once we have more info, I'll be able to assign this to the product eng team. THANKS
