### ISSUE TITLE
Outlook: Office.context.mailbox.item.displayReplyAllForm doesn't start callback

### ISSUE THREAD

**Issue by masa-fleet** [OfficeDev/office-js#1022]
`Office.context.mailbox.item.displayReplyAllForm` doesn't start callback. We don't update our code, but this function doesn't start call back after we update Outlook through Microsoft Update (not sure but probably it may affect).

## Expected Behavior
`Office.context.mailbox.item.displayReplyAllForm` invoke callback function as written in [document](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-1.5#displayreplyallform-formdata--callback-).

## Current Behavior
`Office.context.mailbox.item.displayReplyAllForm` create reply all form and inject html body expectedly, but it doesn't invoke callback.
I investigated through displaying error. I can see 'Start' but can't see 'CallBack' in browser debugger view with following code.
```Typescript
console.log('Start')
Office.context.mailbox.item.displayReplyAllForm({
                htmlBody: 'Insert html body'
                // eslint-disable-next-line @typescript-eslint/no-explicit-any
                callback: (asyncResult: Office.AsyncResult<any>) => {
                    console.log('Callback')
                }
            })
```

## Steps to Reproduce, or Live Example
1. Create sample app using `Office.context.mailbox.item.displayReplyAllForm`. You may call this method from button.
2. Launch app on Outlook for Mac.
3. Call this method by clicking button. => Call back is not invoked.

In 1 ~ 2 weeks ago, my colleague repro this issue, but I didn't have issue in my environment even if we have same OS version and Outlook version. But I can repro today, so I'm not sure about correct repro step and root cause.

If you want to see the problem, I can make time to have Teams call (screen sharing) with product team or I can send captured video if product team share me email address.

## Context
We want to communicate with server side after user see reply email form. If this callback is not invoked, we can't post necessary data to server side, as a result following process stops.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac (Catalina 10.15.3 (19D76))
* Host [Excel, Word, PowerPoint, etc.]: Outlook for Mac Version 16.34 (20020900) with Office 365 Subscription
* Office version number: Version 16.34 (20020900) 
* Operating System: Mac OS X Catalina 10.15.3 (19D76)
* Browser (if using Office Online): I've not tested in Office Online. 

## Useful logs
No log and screen shot, because callback is not invoked and can't write log.

**Comment by eugeneogongo** [comment]
Hello, I have been facing this issue when trying to invoking `Office.context.mailbox.displayNewMessageForm`

My Environment is:

- Mac (Catalina 10.15.3 (19D76))
- Outlook for Mac Version 16.34 (20020900) with Office 365 Subscription
- Office version number: Version 16.34 (20020900)
- Operating System: Mac OS X Catalina 10.15.3 (19D76)

NB: `Office.context.mailbox.displayNewMessageForm` works on Windows Outlook 365 Desktop version and on browser(Safari,outlook and Chrome)

**Comment by exextoc** [comment]
We are able to repro the issue. Thanks for reporting it. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Until this issue is fixed, the following workaround may work for you: 

Update 3/13 - 
(sorry I earlier had a workaround here) - This workaround is not supported and should not be used. We will update this thread when the bug has been fixed.

**Comment by exextoc** [comment]
Internal tracking ids: Office:4016849 and OutlookWeb:79527

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in latest build.
