### ISSUE TITLE
Shared JavaScript runtime

### ISSUE THREAD

**Issue by leybal** [OfficeDev/office-js#1023]
Hi guys! Do you have plans to move the [Shared JS runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview) from preview to a stable version? Do you have any updates regarding this functionality? We plan to use it in our add-in and it will be great to understand runtime future. Thanks in advance!

**Comment by lindalu-MSFT** [comment]
@nokafor Are you the correct PM for office.js runtime? If so, can you answer this q? If not, can you please reassign? THANKS, lindalu

**Comment by jeremy-msft** [comment]
Hi @leybal, thanks for your interest in this feature!  We don't have any release dates to share today, but we're excited to hear your feedback from the preview, which is available for Office Insiders across Windows, Mac, and Web.
