### ISSUE TITLE
"something went wrong and we couldn't start this add-in" on Excel Online

### ISSUE THREAD

**Issue by lukchen** [OfficeDev/office-js#1024]
When I upload my manifest and open the addin in Excel Online, it shows "something went wrong and we couldn't start this add-in, Pls try again later or contact your system admin"

![image](https://user-images.githubusercontent.com/26646767/75718953-dddd9d80-5ca1-11ea-841e-3e0542a51fe8.png)

This is my manifest, very simple, url is pointing to google:

<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="TaskPaneApp">
  
  <Id>c6890c26-5bbb-40ed-a321-37f07909a2f0</Id>
  <Version>1.0</Version>
  <ProviderName>Contoso, Ltd</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Northwind Traders Excel" />
  <Description DefaultValue="Search Northwind Traders data from Excel"/>
  <SupportUrl DefaultValue="https://www.google.com/" />
  <AppDomains>
    <AppDomain>https://www.google.com/</AppDomain>
  </AppDomains>
  <DefaultSettings>
    <SourceLocation DefaultValue="https://www.google.com/" />
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>
</OfficeApp>

**Comment by lukchen** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="TaskPaneApp">
  
  <Id>c6890c26-5bbb-40ed-a321-37f07909a2f0</Id>
  <Version>1.0</Version>
  <ProviderName>Contoso, Ltd</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Northwind Traders Excel" />
  <Description DefaultValue="Search Northwind Traders data from Excel"/>
  <SupportUrl DefaultValue="https://www.google.com/" />
  <AppDomains>
    <AppDomain>https://www.google.com/</AppDomain>
  </AppDomains>
  <DefaultSettings>
    <SourceLocation DefaultValue="https://www.google.com/" />
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>
</OfficeApp>

**Comment by lukchen** [comment]
![image](https://user-images.githubusercontent.com/26646767/75719055-0d8ca580-5ca2-11ea-9900-0f955adac6d5.png)

**Comment by lukchen** [comment]
![image](https://user-images.githubusercontent.com/26646767/75719982-bb4c8400-5ca3-11ea-9f8c-184971594688.png)

**Comment by lukchen** [comment]
I've changed the GUID already

**Comment by MandytMSFT** [comment]
@lukchen how do you generate this manifest? did you publish your add-in ?

**Comment by lindalu-MSFT** [comment]
No author feedback, closing issue. Feel free to reopen if needed!
