### ISSUE TITLE
InvalidArgument Error when write data to a range object in Excel Add-in

### ISSUE THREAD

**Issue by brownlzw1997** [OfficeDev/office-js#1025]
Received a InvalidArgument error with message "The number of rows or columns in the input array doesn't match the size or dimensions of the range." when set the value of an Excel range object. 

Help we needed:
Is there something we do wrong in the code?
How to debug this more effectively?
Is there any way for us to add more detailed logging?

## Expected Behavior
No error

## Current Behavior
The error message we received in logging:
```
  {
  "name": "RichApi.Error",
  "code": "InvalidArgument",
  "traceMessages": [
   
  ],
  "innerError": null,
  "debugInfo": {
    "code": "InvalidArgument",
    "message": "The number of rows or columns in the input array doesn't match the size or dimensions of the range.",
    "errorLocation": "Range.values",
    "statement": "range.values=...;",
    "surroundingStatements": [
      "var workbook=context.workbook;",
      "var worksheets=workbook.worksheets;",
      "var worksheet=worksheets.getItem(...);",
      "var range=worksheet.getRange(...);",
      "// Instantiate {range}",
      "// >>>>>",
      "range.values=...;",
      "// <<<<<",
      "range.load(["rowCount","columnCount"]);"
    ],
    "fullStatements": [
      "Please enable config.extendedErrorLogging to see full statements."
    ]
  }
}
```

## Steps to Reproduce, or Live Example
========Code Snippet=========
 ```
  funciton writeSliceToWorksheet(
    worksheet: string,
    sheetStartingRow: number,
    slice: Array<Array<string>>,
  ): Promise<boolean> {
    const rows = slice.length;
    const columns = slice[0].length;
    const range = [
      0,
      sheetStartingRow,
      columns - 1,
      sheetStartingRow + rows - 1,
    ];
 
    return writeToWorksheet(worksheet, range, slice);
  }
 
  function checkDataAndRangeConsistency(
    range: [number, number, number, number],
    data: Array<Array<any>>,
  ): boolean {
    const cols = range[2] - range[0] + 1;
    const rows = range[3] - range[1] + 1;
    if (rows !== data.length || cols !== data[0].length) {
      throw new Error('data and range dimension are inconsistent');
    }
 
    return true;
  }
 
 
  /**
   * Convert a rectangle area in 2d coordinate system,
   * to an Excel worksheet range using A1 notation
   * like [0, 0, 2, 4] => 'A1:C5'
   */
  function getA1Notation(range: [number, number, number, number]): string {
    if (!(range[0] <= range[2] && range[1] <= range[3])) {
      throw new Error('coordinates should start from top-left to right-bottom');
    }
    return (
      getAlphabetIndex(range[0]) +
      (range[1] + 1) +
      ':' +
      getAlphabetIndex(range[2]) +
      (range[3] + 1)
    );
  },
 
  // convert 0 -> A, 25 -> Z, 26 -> AA
  getAlphabetIndex(index: number): string {
    if(index < 0) { throw new Error('index may not be a negative number.'); }
    let columnName = '';
    let localIndex = index;
    while (localIndex >= 0) {
      columnName = String.fromCharCode(65 + (localIndex % 26)) + columnName;
      localIndex = Math.floor(localIndex / 26);
      localIndex--;
    }
    return columnName;
  },
 
  async function writeToWorksheet(
    sheetName: string,
    range: [number, number, number, number],
    data: Array<Array<any>>,
  ): Promise<boolean> {
    checkDataAndRangeConsistency(range, data);
 
    return FBOffice.Excel.run(ctx => {
      const excelRange = ctx.workbook.worksheets
        .getItem(sheetName)
        .getRange(getA1Notation(range));
      excelRange.values = data;
      // Range get from context is not synced with the actual value, we need to
      // call load to read the property of it.
      // Details here: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-core-concepts#load
      excelRange.load('rowCount, columnCount');
 
      return ctx.sync().then(() => {
        const firstRow = data[0];
        // Log the range and data if the x or y dimension doesn't match
        if (
          excelRange.rowCount !== data.length ||
          (firstRow != null && excelRange.columnCount === firstRow.length)
        ) {
          console.log('data:', data);
          console.log('Range:', range);
        }
        return true;
      });
}
 ```
========Code Snippet=========

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: >90% on Windows Excel , a few in Mac
* Host [Excel, Word, PowerPoint, etc.]:  Excel
* Office version number: 16.00 / 16.01
* Operating System: 
* Browser (if using Office Online): N/A

**Comment by lumine2008** [comment]
Thanks @brownlzw1997 , we have your sample code but it seems that we are not be able to repro this issue. 
https://gist.github.com/cjx0109/9628cbe9f553b1bca93bd2920f2aee9c

Would you please check the gist and see what are the issues? kindly modify this gist as needed to make this bug be able to repro. thanks

**Comment by renqi2018** [comment]
As @lumine2008 said, your code works well with the input like: writeSliceToWorksheet("Sheet1", 7, [[1,5,5],[12,6,7]]). May we know what input you used when getting the error?

For your other questions:
1. from the error messange, the problem is around
     const excelRange = ctx.workbook.worksheets
       .getItem(sheetName)
       .getRange(getA1Notation(range));
     excelRange.values = data;
If you can use console.log to print the range address "getA1Notation(range)" and "data", that will help to diagnostic the issue.

How to check the log printed by console.log? (forgive me if you already know this)
That is exactly same as the console.log browser supported. You can use browser debugger/Inspector to check the console log.
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-in-office-online
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac

2. A convenient way is to use "Script Lab" add-in (open Excel/Word/Powerpoin -> insert -> addin-in -> store -> search "Script" -> select "Script Lab" and add), it is a playground for you to test code snippet like your code above. "Script Lab" will show the console log inside the task pane, no need to inspect using browser tool. 

Thank you for your feedback, we strive to improve the developer experience. If there is any confusion during your development, that means there is something we can improve.

**Comment by brownlzw1997** [comment]
@lumine2008, @renqi2018 This days I collect more loggings but unfortunately it doesn't give any clues. I also tried to use the sample data from logging in Script Lab to repro the error but no luck.

To moving forward, I am considering 2 things:
1. Since I cannot repro the error, it may be a random failure. I plan to add a re-try mechanism to the write to sheet method. Do you guys know what is the best practice to adding re-try?
2. From the error message, it says "Please enable config.extendedErrorLogging to see full statements.". Is this a flag that I need to add? If so, can I add it to only a small percentage of people so that it won't influence performance that much. Also, when do I need to add the flag?  Should I add it before running any of the office method, or I can add it just before the method I am interested in (in this case, write sheet) and it will only apply to the that method?

Thanks in advance for any help

**Comment by jingch0109** [comment]
@brownlzw1997 
I am just wondering whether there is a possibility that the column counts of first row is different with other rows.

**Comment by brownlzw1997** [comment]
@jingch0109, we also have logging on that but we haven't find any case where the column counts don't match. @lumine2008, @renqi2018, can you guys offer some help on my questions above?

**Comment by renqi2018** [comment]
@brownlzw1997, my answers for your 2 questions as below.
1. In general, InvalidArgument is not a transient error that can be mitigated using retry. 
2. When set OfficeExtension.config.extendedErrorLogging to true, you can get parameter of range set value API. But setting this property to true will negatively impact performance and will log all statements in the batch request, including any statements 
that may contain potentially-sensitive data.
**It is recommended that you only set this property to true during debugging and that you never log the value of error.debugInfo.fullStatements to an external database or analytics service.**

The log will look like:
"fullStatements": [
            "var workbook=context.workbook;",
            "var worksheets=workbook.worksheets;",
            "var worksheet=worksheets.getItem(\"Sheet1\");",
            "var range=worksheet.getRange(\"A8:C9\");",
            "// Instantiate {range}",
            "range.values=[[1,5,5],[12,6]];",
            "range.load([\"rowCount\",\"columnCount\"]);"
        ]
Thanks.

**Comment by lumine2008** [comment]
Clean up, please reopen this issue, if you still observe this issue.
