### ISSUE TITLE
Outlook Add-in can't work on Android 9 and Android 10

### ISSUE THREAD

**Issue by hdkdinh** [OfficeDev/office-js#1027]
I am developing Outlook add-in using add-in command to execute a function.
The test version of the add-in will open dialog then user can choose to click OK or cancel then another dialog will appear and user can click OK to complete the action.
The add-in works well on iOS and web, but not on Android

**Expected Behavior**
I expected the add-in can work on web, iOS, Android

1. The add-in will show notification " is working on your request"
2. The add-in then show notification "step 1"
3. The add-in then open a dialog allow user to click button to send message back to parent and the dialog is closed
4. The notification show "step 2"
5. The dialog will appear and allow user to click button to send message back to parent and the dialog is closed
6. Action complete

**Current Behavior**
The add-in works very well on web and iOS. But when it comes to Android, the problem appears:

Sometimes the add-in stops working, the only notification message appears is " is working on your request" and it spinning forever.
Sometimes the add-in successfully opens the dialog but I click many times to the button on the dialog and nothing happened, no error showing up, it just stays there. Need to press X to close the dialog.
Sometimes the add-in can stop at any step.
Sometimes the add-in does successfully the expected steps.

**Steps to Reproduce, or Live Example**
Link to live example: ______
https://github.com/ntranvinh/AndroidOutlookAddinSample

**Your Environment**
Platform [PC desktop, Mac, iOS, Office Online]: Android
Host [Excel, Word, PowerPoint, etc.]: Outlook
Office version number: the latest version of Outlook for Android on 2020-04-02
Operating System: Android version 9 and Android version 10

**Comment by exextoc** [comment]
We are able to repro the issue. Thanks for reporting it. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by hdkdinh** [comment]
@exextoc Could you arrange and give us a time to fix it. Because there are a lot of user use android device. Thanks!

**Comment by exextoc** [comment]
We unfortunately have no timelines to share at this point. It has been put on our backlog.

**Comment by hdkdinh** [comment]
@exextoc Please help us arrange the time to fix it. Because a lot of user need to use add-in on Android device. Thanks!

**Comment by exextoc** [comment]
Reactivating original on call bug BUG 1404234<https://o365exchange.visualstudio.com/DefaultCollection/O365%20Core/_workitems/edit/1404234> to respond to OP.
________________________________

**Comment by exextoc** [comment]
We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: Office:3941546

**Comment by hdkdinh** [comment]
> Internal tracking id: Office:3941546

Hi @exextoc , how about this issue? Do you have any update for this bug?

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in upcoming builds. Depending on the release channel a customer is on, getting an updated build can take anywhere from 4-8 weeks

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 4.2102.0 or later
