### ISSUE TITLE
[Outlook] Office.context.mailbox.displayNewMessageForm doesn't show form correctly

### ISSUE THREAD

**Issue by zfdongzhi** [OfficeDev/office-js#1028]
Sometimes when I call the Office.context.mailbox.displayNewMessageForm API, the compose new email form is not right. The code calling API is like:
if (!!Office.context.requirements.isSetSupported && Office.context.requirements.isSetSupported("Mailbox", 1.6)) {
    Office.context.mailbox.displayNewMessageForm({
        toRecipients: ["user1@microsoft.com", "user2@microsoft.com"],
        subject: "Test subject",
        htmlBody: "Test body"
    });
}

When run this Outlook App Add-in, it's all right, it shows a new email with the to recipients, body and subject. But in [Outlook web service](https://outlook.office.com/mail/)'s add-in, sometimes in the new email, to recipients, subject and body are all empty. I checked the console logs and network logs, no explicit errors or warnings.

The same issue when I was calling:
Office.context.mailbox.displayNewAppointmentForm({
                requiredAttendees: [],
                optionalAttendees: ["user1@microsoft.com", "user2@microsoft.com"],
                start: startTime,
                end: endTime,
                location: "",
                resources: [],
                subject: "Test subject",
                body: "Test body"
            });

There is a new meeting form, but sometimes the attendees, subject and body are all empty.
It's a transient issue, sometimes it woks fine, sometimes not.
Appreciate any suggestions about how to fix it.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Laptop
* Host [Excel, Word, PowerPoint, etc.]: Outlook Web Service
* Operating System: Windows 10
* Browser (if using Office Online): Edge and Chrome

**Comment by exextoc** [comment]
We are not able to reproduce the same. It would be great if you share the test account.

**Comment by exextoc** [comment]
Do you have outlook.com account or enterprise account?

**Comment by exextoc** [comment]
Already bug is opened for it:

Bug 1404243<https://o365exchange.visualstudio.com/O365%20Core/_workitems/edit/1404243>: New GitHub Issue [OfficeDev/office-js]: [Outlook] Office.context.mailbox.displayNewMessageForm doesn't show form correctly
________________________________
