### ISSUE TITLE
[Excel Addin] Custom ribbon is not working at first click and it is requiring to click twice.

### ISSUE THREAD

**Issue by MhooTanapatAT** [OfficeDev/office-js#1029]
After upload custom ribbon manifest to excel, the ribbon won't work at first click. Is there any solution for this issue?
## Article URL
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/add-in-manifests.md

## Issue
Excel custom ribbon have to click twice to make it work. I have investigated and, found that on the first click, the ribbon will load function file that provided on manifest. and have to click again to execute functions.  Is there anyway to make the ribbon load function file when loaded manifest.

**Comment by mscharlock** [comment]
Hi @lindalu-MSFT, transferring this to office-js as requested as this is the place where we will most likely get an answer to this question. @RuoyingLiang can you weigh in on how to help here? Thank you!

**Comment by topkoong** [comment]
This happened to me as well. While I was debugging and monitoring the network tab from the browser, I found that if office.js is cached, it will immediately download prefetch-cached excel-web-16.0.js, and execute some functions prior to downloading custom-ribbon.html. 

The behaviour is Excel only downloads the html file representing that ribbon once user clicks on the ribbon for the first time, and nothing happens.

As a result, this prevents the script inside ribbon.html from executing, and user has to click on the ribbon again to invoke the function. 

I was wondering if you guys could check this out and keep us posted!

Thank you for your time and consideration!

**Comment by mscharlock** [comment]
Yep, we will have someone check it out and get back to you - @RuoyingLiang will be on point to respond when we get an answer! Thanks :)

**Comment by keyur32** [comment]
@topkoong, @MhooTanapatAT - to help facilitate this what version of Excel are you seeing this on?  Is this on desktop or Excel Online?  What does the add-in command do? Is it the show taskpane action or are you calling code via the functionfile?

thanks

**Comment by aluke1** [comment]
I am also having this issue. 

This exact problem occurs for excel on mac, Version 16.59. 

The addin command opens the taskpane to display the login HTML.

I am opening the taskpane via the ExecuteFunction using code in the functionfile.

When I first load the AddIn it takes two clicks to get the taskpane to open.

**Comment by shaun-pendrigh** [comment]
I am experiencing the same issue with my Excel Add-In. I am running a shared runtime and have a taskpane as well as some other command buttons. If I open the taskpane first, then everything works as expected. However if I click one of the command buttons first, that only seems to trigger initializing the Add-In. The command action does not run. If I click a second time then the command action executes.

It is very confusing for the Add-In users if they sometimes need to click the toolbar button twice before anything happens. Please can you confirm if this is a bug or if I am missing something about how this is supposed to operate. Thanks
