### ISSUE TITLE
Not a real useful feature

### ISSUE THREAD

**Issue by thoffmann-fms** [OfficeDev/office-js#1030]
Given that the SaveAsync method doesn't really "save" the data and it gets reset to default (see "Important" note at the top of the page) means this API method is not dependable enough to actually use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 48ebc3bd-026b-1f53-9759-d08f528b1a5b
* Version Independent ID: a5b370a0-ec65-7e19-4748-20d3235eacda
* Content: [Office.RoamingSettings interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.roamingsettings?view=outlook-js-preview)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.roamingsettings.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.roamingsettings.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@timothyhoffmann Thanks for raising this issue. I've transferred to the office-js repo where the product team can take a look.

Thanks.

**Comment by exextoc** [comment]
Yes, this is a known issue with refreshing the add-in or loading a separate page. However, most add-ins don't need to do a refresh or load the page, meaning they can take advantage of roaming settings. 

Filing a uservoice for a more robust roaming settings feature, would help us know how to prioritize this against our backlog: 
https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins
