### ISSUE TITLE
RibbonApi Examples

### ISSUE THREAD

**Issue by bdentino** [OfficeDev/office-js#1032]
Can you please add examples of how to use this API? According to [this page](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/ribbon-api-requirement-sets.md), it should be available in Office on the web as of Feb 2020. I am able to get a ribbon handle using 

`const ribbon = await OfficeRuntime.ui.getRibbon()` 

But when I call 

```
ribbon.requestUpdate({ 
  tabs: [{ 
    id: "<MyCustomTab>", 
    visible: false, 
    controls: [{ id: "<ButtonOnMyTab>", enabled: false }] 
  }] 
})
```

nothing seems to happen. I can't tell if I'm doing something wrong or if this API is not quite ready yet. Clarification would be appreciated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa4d019a-7970-7be3-1276-483ec11489fd
* Version Independent ID: 55483b7d-c756-71d8-69e3-194891f6932e
* Content: [Ribbon API requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/ribbon-api-requirement-sets)
* Content Source: [docs/reference/requirement-sets/ribbon-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/ribbon-api-requirement-sets.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Transferred to the office-js issue, because it's seems to be more an API bug than a documentation issue.

**Comment by Rick-Kirkham** [comment]
@bdentino 
See this article for how to use the new APIs: [Enable and Disable Add-in Commands](https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands). 

You'll see there that it only works on the web when the user is using the single-line ribbon. 

Also, the `visibility` property is not supported yet. It was documented and added to Intellisense by mistake.  (We hope to have that fixed today.) Please remove that from your code. 

Also, the page about the RibbonApi Requirement Set was also published by mistake (and is now gone). The new APIs are not yet assigned to a requirement set.
