### ISSUE TITLE
Office.context.ui undefined in dialog

### ISSUE THREAD

**Issue by jak-hammond** [OfficeDev/office-js#1034]
I have a dialog that is displayed via `displayDialogAsync` which redirects the user off to an authentication server. Once they have authenticated, they are redirected back to the app where some processing is done before trying to call `Office.context.ui.messageParent()` is used to communicate the auth result back to the parent app and close the dialog but this fails as `Office.context` is an empty object so `ui` is undefined.

## Expected Behavior
Office.context.ui should be initalized correctly inside a dialog.

## Current Behavior
When the app is loaded, we are seeing warnings of `Warning: Office.js is loaded outside of Office client` but the `Office.onReady(() => callback);` is still run which from my understanding shouldn't happen if the previously mentioned warning is displayed. Now when the main Vue code runs it fails as the ui property is undefined.

## Context
This is preventing us from completing an authentication flow using the dialog API.
If it makes any difference, I am using the `https://appsforoffice.microsoft.com/lib/beta/hosted/office.js` CDN to test out some preview APIs that we are developing against.

All the relevant domains we are using are listed inside the AppDomain portion of the mainfest.xml as well.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.36 (20030502)
* Operating System: Catalina
* Browser (if using Office Online): -

**Comment by jak-hammond** [comment]
Additional info I forgot initially:
- We are calling a local `/authprovider` route that then does a redirect back off to the authentication provider. So all initial loads of the dialog are still under our domain
- I seem to recall a while back there was some 'host info' in the query string of the dialog but when I do a redirect, that does not travel with it, although I cannot remember if it ever did.....is this needed to help initialize the dialog on the callback?
- In the screenshot below as well, `this._hostInfo` has `isDialog` set as false when the page is loaded in a dialog which seems wrong to me

This seems to be the line within Office.js that is causing it...again, not sure if it helps at all 
![image](https://user-images.githubusercontent.com/664193/76237637-7f2a9d80-6226-11ea-9ce6-1eddb095d4bf.png)

**Comment by exextoc** [comment]
Can you please provide manifest so that we can reproduce this issue inhouse?

**Comment by jak-hammond** [comment]
I have done some more debugging and I think I have found the root cause of the issue and it is independent of the manifest.

When the dialog loads, it does a GET request to /auth which is a controller route on the .NET MVC backend. This route returns a redirect to the IDP and when the user completes the process and is returned back to the dialog on /authcallback the issue presents itself.

If however, I change it so the dialog first loads /auth and then once the page has fully loaded, some JavaScript inside the page does the redirect to /auth, then when the user comes back, it works as intended and the app runs. 

Checking the two dialogs, the only difference I can see is that the second approach adds `HostInfo` to the SessionStorage of the dialog whilst the first approach with the server-side redirect has nothing in the SessionStorage.....I assume this is loaded via Office.js to figure out the 'state' of the dialog and to reinit the framework?

**Comment by exextoc** [comment]
Thanks @jak-hammond. Your root-cause analysis seems right. This part about HostInfo value is documented here under "Important" note: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins

Let us know if there is anything we can do in this issue or we can close it. Thanks!

**Comment by jak-hammond** [comment]
So a question I do have is that previously, we were making use of locally served Office.js files via the NPM package, then as we got ready to move to production we switched out for the CDN version which is when the issue presented itself. The functionality of the add-in did not change between that switch so it seems to have been working before in its current setup.

Could you just confirm for me how the host info is reasoned? Does the framework first try and read the value from session storage and then if it cannot find it there, will it try and read the value from the query string or is that value used just to populate session storage?

Thanks! :)

**Comment by exextoc** [comment]
Yes, you are correct. The framework first tries to read the value from the session storage, if it can't find there it fetches from the server and store it to the session storage, then tries to read value from the session.

**Comment by exextoc** [comment]
Can you share link to locally served office.js file so that we can compare with CDN version of it?

**Comment by jak-hammond** [comment]
Of course, I will upload it here tomorrow. It was quite old, I think originally I got the version last August or September, then when I updated, it would have been whatever was current on the CDN.
