### ISSUE TITLE
Microsoft Outlook 2013 meet crash when starting

### ISSUE THREAD

**Issue by hdkdinh** [OfficeDev/office-js#1035]
I am developing Outlook add-in using add-in execute a function.
I implement TLS 1.2 for add-in by:
**ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;**
After that, I build .exe file and install into outlook. It works ok on outlook 2016, outlook 365 but meet crash on outlook 2013 when starting.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Microsoft Outlook 2013
* Office version number: 15.0.4569.1506
* Operating System: Windows 7
* .Net Framework: 4.0 and 4.5

**Comment by exextoc** [comment]
This appears to be a question about COM add-ins. This backlog is for OfficeJS based add-ins. Closing as off topic.
