### ISSUE TITLE
EdgeManager.dll Crashes

### ISSUE THREAD

**Issue by redcirkle** [OfficeDev/office-js#1036]
We are developing an Excel add-in using Office.js. In our taskpane, we are using MSAL to authenticate users before continuing the workflow. We are experiencing an intermittent crash in EdgeManager.dll after login. The exception code is 0xc0000005 (part of the application error log is listed below). We can replicate this issue across multiple developer machines. We can somewhat resolve this issue by clearing network and storage caches/cookies through Microsoft Edge DevTools, but it only "fixes" the issue temporarily. It's not a complete, long-term fix (nor a reasonable solution for our add-in consumers). Please let us know how we can resolve this issue, as it's blocking our production release. Thank you for your time and help!

```
Log Name:      Application
Source:        Application Error
Date:          3/9/2020 9:22:46 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      <REMOVED_DUE_TO_PRIVACY>
Description:
Faulting application name: EXCEL.EXE, version: 16.0.12527.20242, time stamp: 0x5e5a7849
Faulting module name: EdgeManager.dll, version: 11.0.18362.657, time stamp: 0x298ae057
Exception code: 0xc0000005
Fault offset: 0x0000000000001a0e
Faulting process id: 0x2f98
Faulting application start time: 0x01d5f62ecc14ae30
Faulting application path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
Faulting module path: C:\Windows\System32\EdgeManager.dll
Report Id: ae02823b-496e-4cdd-a5b9-b8fec1265c3b
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-03-09T16:22:46.375929800Z" />
    <EventRecordID>9202</EventRecordID>
    <Channel>Application</Channel>
    <Computer><REMOVED_DUE_TO_PRIVACY></Computer>
    <Security />
  </System>
  <EventData>
    <Data>EXCEL.EXE</Data>
    <Data>16.0.12527.20242</Data>
    <Data>5e5a7849</Data>
    <Data>EdgeManager.dll</Data>
    <Data>11.0.18362.657</Data>
    <Data>298ae057</Data>
    <Data>c0000005</Data>
    <Data>0000000000001a0e</Data>
    <Data>2f98</Data>
    <Data>01d5f62ecc14ae30</Data>
    <Data>C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE</Data>
    <Data>C:\Windows\System32\EdgeManager.dll</Data>
    <Data>ae02823b-496e-4cdd-a5b9-b8fec1265c3b</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

Note: I think it might be related to the [Edge WebView Outlook Crashes issue](https://github.com/OfficeDev/office-js/issues/982) that someone else raised a few days ago, but I'm not 100% sure.

**Comment by AlexJerabek** [comment]
@redcirkle, Thank you for reporting this issue.

@sumurthy, could you please investigate?

**Comment by sumurthy** [comment]
@smaremanda  - could you please take a look at this issue and pass it to the right person?

**Comment by Borgquite** [comment]
Fixed for me in the latest Current Channel release (2006 Build 13001.20384)

https://docs.microsoft.com/en-us/officeupdates/current-channel#version-2006-july-14

'Addressed a crash issue with the office host in windows, when an add-in is activated while the registry TabProcGrowth value is REG_SZ type.'

**Comment by smaremanda** [comment]
Thanks for the update.
