### ISSUE TITLE
settings.saveAsync() and manifest version

### ISSUE THREAD

**Issue by giulianozor** [OfficeDev/office-js#1037]
Hello,
I'm using Office.context.document.settings.saveAsync() to save the changes of Office.AutoShowTaskpaneWithDocument in a word document.

I updated my manifest version from 1.0.1.0 to 1.0.2.0 and added the relevant xml configuration.
```
                  <Action xsi:type="ShowTaskpane">
                    <TaskpaneId>Office.AutoShowTaskpaneWithDocument</TaskpaneId>
                    <SourceLocation resid="Contoso.Taskpane.Url" />
                  </Action>
```
Everything seems to work fine if I only use manifest 1.0.2.0

But if I 
* enable the autoshow on version 1.0.1.0
* remove the manifest and sideload 1.0.2.0
I get an error as the add in is no longer available (that's expected). 
So I 
* open the doc and add in (that should be 1.0.2.0 as it is the only version installed)
* disable the setting/save/close/reopen the file 
it seems fine. However if I  enable the AutoShow I get the same error. 

After inspecting the webextensions I can see that the version referencesd is still 1.0.1.0

```
./word/webextensions/webextension1.xml:<we:webextension xmlns:we="http://schemas.microsoft.com/office/webextensions/webextension/2010/11" id="{AE91F051-XXXXX-XXXX-XXXXX-XXXXXXX}"><we:reference id="68c48e4b-c6a7-463f-a86e-c12f6223cf18" version="1.0.1.0" store="developer" storeType="Registry"/><we:alternateReferences/><we:properties><we:property name="Office.AutoShowTaskpaneWithDocument" value="true"/></we:properties><we:bindings/><we:snapshot xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"/></we:webextension>
```

Can this be a bug or am I missing something ?

Settings code is 
```

            if (!this.autoLoadStatus) {
                Office.context.document.settings.set(
                    'Office.AutoShowTaskpaneWithDocument'
                    !this.autoLoadStatus
                );
            } else {
                Office.context.document.settings.remove( 'Office.AutoShowTaskpaneWithDocument' );
            }
    }
```

Testing on MacOs 10.15.3, Word 16.35.20030802/Office365, office toolbox 6.13.4
, officejs from https://appsforoffice.microsoft.com/lib/1/hosted/office.js
Manifest uses 
```
<OfficeApp
  xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
  xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides"
  xsi:type="TaskPaneApp">
```
Thanks

**Comment by AlexJerabek** [comment]
Thanks for reporting this @giulianozor. 

Assigning @nokafor to investigate.

**Comment by giulianozor** [comment]
happy birthday, I suppose... Any news ?

**Comment by AlexJerabek** [comment]
Hi @giulianozor,

I'm sorry this issue went under the radar. Let me tag @keyur32 and @smaremanda to try and help.

**Comment by giulianozor** [comment]
@AlexJerabek I suppose this will not be fixed... is this project still maintained ?

**Comment by AbidRahman-MSFT** [comment]
Hey @giulianozor,

A few questions to help understand the issue:
1. You have two different manifest files, one is v1.0.1.0 and one is v1.0.2.0.
2. The 'AutoShowTaskpaneWithDocument' feature was added as part of v1.0.2.0
3. Are you sideloading both of these manifests in your steps?
4. When you remove v1.0.1.0 and sideload v1.0.2.0, then re-open the file, are you finding that the add-in installed is still 1.0.1.0? 

Thanks,
Abid

**Comment by giulianozor** [comment]
@AbidRahman-MSFT 
Hello,
1. yes
2. yes
3. yes
4. IIRC it was 1.0.2.0, but it was 2 years ago and I might be wrong. I am sure I cleaned the cached add-ons after removing 1.0.1.0

I can't check if this is still an issue as I moved to different tasks
