### ISSUE TITLE
Can't upload manifest.xml file for local testing in IE11

### ISSUE THREAD

**Issue by dzwillia** [OfficeDev/office-js#1038]
## Expected Behavior
I expect to open the Office Add-ins dialog and have it show the list of installed add-ins in the "My Add-ins" area and then to be able to click "Manage My Add-ins => Upload My Add-in" and upload my manifest.xml file and have the local version of my add-in available for testing.

## Current Behavior
The Office Add-ins dialog shows a spinner for a long time and then displays an error message "The catalog didn't respond in time, please try again later." and I am unable to install my local add-in for testing.

## Steps to Reproduce, or Live Example
1. Open up Internet Explorer 11
2. Go to office.com and log in
3. Click on Excel and create a new sheet
4. Go to the "Insert" tab above the ribbon
5. Click on "Office Add-ins"

The dialog hangs there and just shows a spinner for a long time and eventually shows the message "The catalog didn't respond in time, please try again later."

## Context
My add-in submission was denied because it did not pass compatibility tests for IE11. So, I'm trying to test my add-in on IE11, but I can't even get to the point where I can install it for testing because of this issue.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.12704.35050
* Operating System: Windows 10
* Browser (if using Office Online): Internet Explorer 11 (Version 11.657.18362.0)

#### Message that our add-in submission had failed
![Clipboard - March 11, 2020 1_15 PM](https://user-images.githubusercontent.com/1385356/76445654-23822080-639c-11ea-92df-2a72b3de8700.png)

#### IE Version
![Clipboard - March 11, 2020 12_52 PM](https://user-images.githubusercontent.com/1385356/76445677-2d0b8880-639c-11ea-9cf1-401a8da2b5fa.png)

#### Excel Online Version
![Clipboard - March 11, 2020 1_17 PM](https://user-images.githubusercontent.com/1385356/76445850-74921480-639c-11ea-8515-6d18ea5b3257.png)

#### This is the add-in dialog showing a spinner for about a minute and then an error message
![Clipboard - March 11, 2020 12_51 PM](https://user-images.githubusercontent.com/1385356/76445664-27ae3e00-639c-11ea-9261-87bfb0b55a95.png)

![Clipboard - March 11, 2020 12_52 PM - 2](https://user-images.githubusercontent.com/1385356/76445768-51676500-639c-11ea-8719-dfb4bbff0658.png)

#### This is what I was able to see in the dev tools
![Clipboard - March 11, 2020 12_59 PM](https://user-images.githubusercontent.com/1385356/76445818-680dbc00-639c-11ea-8fc5-98e37bfdaf3f.png)

![Clipboard - March 11, 2020 12_59 PM - 2](https://user-images.githubusercontent.com/1385356/76445830-6f34ca00-639c-11ea-89af-85d81f7b6bdf.png)

**Comment by AlexJerabek** [comment]
I'm sorry to hear you're having trouble with IE11, @dzwillia. 

@TCourtneyOwen, could you please investigate this issue?

**Comment by ElizabethSamuel-MSFT** [comment]
@millerds Can you take a look?

**Comment by millerds** [comment]
The test environment says it's Windows 10 which doesn't support IE11 anymore.  Windows 7 is also past it's supportability date.  I don't think this issue applies anymore.
