### ISSUE TITLE
Outlook Online, Safari, setSelectedDataAsync produces incorrect formatting

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1039]
In an Outlook add-in for compose mode, we use the Office JS API to fill in email fields.  The setSelectedDataAsync method inserts HTML with incorrect markup.

## Expected Behavior
The setSelectedDataAsync method should work as expected.

## Current Behavior
The setSelectedDataAsync method ignores markup in Safari.

## Steps to Reproduce, or Live Example
Create a new email in Outlook Online using the Safari browser and execute the following code:
`const data = '<strong>bold</strong> normal text';
Office.context.mailbox.item.body.setSelectedDataAsync(data, { coercionType: Office.CoercionType.Html }, (asyncResult) => {});`

Result: all the inserted text is bold.
Expected: only the 'bold' text should be bold.

* Additional details:
  1. Everything works as expected on Outlook for Mac 16.35 (20030802) and Outlook Online in Chrome

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Mac OS Catalina 10.15.3 (19D76)
* Browser (if using Office Online): Safari Version 13.0.5 (15608.5.11)

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue @DmitryKostochko. 

Assigning to @exextoc for investigation.

**Comment by exextoc** [comment]
Thanks for the reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
@DmitryKostochko Could you please confirm if you are still facing this issue?

**Comment by DmitryKostochko** [comment]
I have just retested the code and cannot reproduce the issue. The bug seems to be fixed, thank you!

**Comment by exextoc** [comment]
Thanks for the confirmation. We are closing this issue.
