### ISSUE TITLE
Encoding issue with getHtml()

### ISSUE THREAD

**Issue by leoseccia** [OfficeDev/office-js#104]
getHtml() does not return a string encoded using the correct encoding. It looks like the API is treating UTF-8 Bytes as Windows-1252 or ISO-8859-1 

## Expected Behavior
When calling getHtml() I expect that the API returns the html in the correct format, showing the correct characters. 

## Current Behavior
getHtml() treat UTF-8 bytes as Windows-1252 or ISO-8859-1. This result in the Html rapresentation of the document not to be correct. 

## Steps to Reproduce, or Live Example

Use the following code to retrieve Html from a doc
```
  Word.run(function (context) {

        // Queue a command to get the current selection and then
        // create a proxy range object with the results.
        var range = context.document.body;

        var bodyHTML = range.getHtml();
        // variable for keeping the search results for the longest word.
        var searchResults;

        // Queue a command to load the range selection result.
        context.load(range, 'text');

        // Synchronize the document state by executing the queued commands
        // and return a promise to indicate task completion.
        return context.sync()
            .then(function () {
               let html = bodyHTML.value; 
            });
    })
    .catch(errorHandler);
```

run the following code on a document which contains non Windows-1252 or ISO-8859-1 such as '…' or '“' or '€'

## Context
This is a very severe issue as it prevents us from analyzing the document correctly.

## Your Environment

* Platform: PC desktop
* Host: Word
* Office version number: 2016
* Operating System: Win7

## Useful logs
Please refer to my StackOverflow question here for screenshots and a more eloquent description of the issue: https://stackoverflow.com/questions/50021957/encoding-issue-with-gethtml-in-officejs

**Comment by leoseccia** [comment]
In case someone stumbles across this, while experiencing the same issue... I have just added a workaround to my question in StackOverflow: https://stackoverflow.com/questions/50021957/encoding-issue-with-gethtml-in-officejs

**Comment by JuaneloJuanelo** [comment]
I was not able to repro this issue. Actually use script lab to run this snippet. this snippet is sending the HTML of the body into a div in the Add--in taskpane.
Add the Euro or other UTF-8 chars and you will see they are rendered correctly in the taskpane. 

if you don't see this result, please reopen and also provide a document and build numbers where the issue is happening. 

it returns the encoding in windows-1252

please import this script into scriptlab  (if never used before check this http://aka.ms/scriptlab )
https://gist.github.com/JuaneloJuanelo/9fafa4c08de759bce97009b592ffce9c



<meta http-equiv=Content-Type content="text/html; charset=windows-1252">
--

**Comment by leoseccia** [comment]
@JuaneloJuanelo - This issue is still present when running my document with your code... See screenshot and attached doc.
![error in scriptlab](https://user-images.githubusercontent.com/2159624/39349672-b171a51a-49f3-11e8-9371-3fe9668500d8.png)
[simple doc to show encoding issue.docx](https://github.com/OfficeDev/office-js/files/1954146/simple.doc.to.show.encoding.issue.docx)

**Comment by leoseccia** [comment]
@JuaneloJuanelo - I cannot reopen an issue, closed by someone else... Can you reopen it please?

**Comment by leoseccia** [comment]
I do not experience this issue when using Word Online via Chrome or IE11. So it is just a desktop issue.

**Comment by JuaneloJuanelo** [comment]
thanks for adding the file, we'll investigate in more detail.

**Comment by leoseccia** [comment]
@JuaneloJuanelo - also related but different:
- getHtml() returns completely different values between Word Online and Word Desktop. This poses potential issues when developing an addin that needs to run universally, across platforms. It kind of goes against the high-level Office App concept. An example is how bold is converted ie. Word desktop uses `<b>` while Word Online uses `font-weight: bold;` as an inline style.
- getHtml() in Word Online returns html with correct UTF-8 values, however it does not contain `<meta charset="UTF-8" />`. This means that when you save and display the document in the browser the UTF8 characters do not display correctly. Adding the meta tag, solves the issue. 

Do you want me to log both of these as separate issues?

**Comment by KevinOrfas** [comment]
Where are you supposed to add the `meta`?
