### ISSUE TITLE
Class constructor parameters not valid inside method

### ISSUE THREAD

**Issue by pnchakravarthula** [OfficeDev/office-js#1041]
Hi,

Trying to create an custom function in Excel and running own custom function inline to implementation done here https://tsmatz.wordpress.com/2017/12/01/excel-addin-custom-function/ 

But instead of straight function in myfunc.js we have a class as below:

class Rectangle {
    constructor(height, width) {
        this.height = height;
        this.width = width;
    }
    // Method
    calcArea() {
        return (this.height * this.width);
    }
}

Problem: When we are trying to instantiate object of class and pass in parameters to constructor as below  const square = new Rectangle(10, 100);  and associating the function as CustomFunctions.associate("TEST", square.calcArea);. We getting value as #VALUE in Excel
After some digging in we found that the parameters passed in to constructor are not available for method calcArea. 
This above code works fine as standalone JS, but not when used here.
Can someone help here as in what is that we are doing wrong.

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue @pnchakravarthula. 

Assigning to @RuoyingLiang for investigation.

**Comment by RuoyingLiang** [comment]
Created item 4027627 to track this ask.
