### ISSUE TITLE
While inserting a Word document having multilevel bulleted text in another document using Office JS API "insertfilefrombase64" loses last bullet and text gets aligned to the margin

### ISSUE THREAD

**Issue by Kashishmsft** [OfficeDev/office-js#1042]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

While inserting a Word document having multilevel bulleted text in another document using Office JS API "insertfilefrombase64" loses last bullet and text gets aligned to the margin.

## Expected Behavior
The bullet in the Word document should have been intact i.e. should be in same format before base64 conversion.

## Current Behavior
While inserting a Word document having multilevel bulleted text in another document using Office JS API "insertfilefrombase64" loses last bullet and text gets aligned to the margin.

The Word document with multilevel bulleted text when created in a Office 2016 MSI environment, the bullet remains intact.
But When document created in Office 365 environment, the bullet is lost.

## Steps to Reproduce, or Live Example

1. Open Microsoft Word - Office 365/Office 2016. 
2. Load the ScriptLab Add-in.
3. Import gist from- https://gist.github.com/Kashishmsft/64e9002935a2c7358d4f756119de27ea  
4. Convert attached document (O365.docx) to base64 and copy it to the loaded code in Scriptlab Add-in.
5. Run the ScriptLab Add-in.
6. Click on custom task pane button "LoadFile".
7. You would see the bullet lost in the inserted text.
8. Observe that in original document (O365.docx), the bullets are saved as intact.
9. When the same steps as above are performed with base64 copied from a document O2016.docx, the bullets remain intact.
10. The issue occurs whether you insert the document in Word having Office 2016 MSI or Office 365 i.e. both.

## Context

The format of the text gets distorted as customer's product does a lot of document automation, basically breaks the well formatted document if Office JS is used.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Windows 10 OS version 1909.
* Host [Excel, Word, PowerPoint, etc.]: Microsoft Word
* Office version number: 16.0.11929.20618 64-bit
* Operating System: Windows 10 OS
* Browser (if using Office Online): NA

## Useful logs

 
![image](https://user-images.githubusercontent.com/35471218/76583791-37469780-6500-11ea-95c5-9db15a69f1b8.png)
[base64conversion_O365.txt](https://github.com/OfficeDev/office-js/files/4327525/base64conversion_O365.txt)
[base64conversion_O2016.txt](https://github.com/OfficeDev/office-js/files/4327526/base64conversion_O2016.txt)
[O365.docx](https://github.com/OfficeDev/office-js/files/4327527/O365.docx)
[O2016.docx](https://github.com/OfficeDev/office-js/files/4327528/O2016.docx)

**Comment by AlexJerabek** [comment]
Thanks for reporting this @Kashishmsft. 

Assigning to @JuaneloJuanelo for investigation.

**Comment by Kashishmsft** [comment]
Hello @AlexJerabek @JuaneloJuanelo - Any updates for me please ?

**Comment by JuaneloJuanelo** [comment]
its a bug been tracked internally with 4130033

**Comment by Kashishmsft** [comment]
> its a bug been tracked internally with 4130033

Thanks @JuaneloJuanelo . Would look forward to it then.

**Comment by hjkim-MSFT** [comment]
This doesn't repro locally. Back to you Juan.

**Comment by acrow59** [comment]
Hello @JuaneloJuanelo . Could we get an update on this issue? We are still experiencing the same problem when inserting files containing bulleted lists via base64 insert.

Additionally, numbered and lettered lists are fully inserted, but inserting multiple files with numbers or lettered lists will continue the list rather than starting a new one within the file's content control. For example, if File 1 has a list of "a. b. c." and File 2 also has a list of "a. b. c." and I insert both files, it will show in the document as "a. b. c. d. e. f." instead of "a. b. c. a. b. c.". This is the case even if the two lists are separated by other text in between the two lists. If needed, I can create a separate issue for this behavior.

**Comment by SirDavenport** [comment]
> Hello @JuaneloJuanelo . Could we get an update on this issue? We are still experiencing the same problem when inserting files containing bulleted lists via base64 insert.
> 
> Additionally, numbered and lettered lists are fully inserted, but inserting multiple files with numbers or lettered lists will continue the list rather than starting a new one within the file's content control. For example, if File 1 has a list of "a. b. c." and File 2 also has a list of "a. b. c." and I insert both files, it will show in the document as "a. b. c. d. e. f." instead of "a. b. c. a. b. c.". This is the case even if the two lists are separated by other text in between the two lists. If needed, I can create a separate issue for this behavior.

@acrow59 Howdy, did you ever figure out a solution for this list issue?
