### ISSUE TITLE
Custom function using Angular framework

### ISSUE THREAD

**Issue by shyambhiogade** [OfficeDev/office-js#1044]
Is creating custom function with Angular framework supported? i could not load addin for custom function created using angular framework in excel desktop, it somehow works in excel online.

**Comment by shyambhiogade** [comment]
@AlexJerabek can you please reply

**Comment by keyur32** [comment]
Hi there, yes, you can create functions independent of any front end framework.  Do you have specific information as to how you're planning to use Angular with the function? Do you have some repro steps to help us debug?

**Comment by shyambhiogade** [comment]
@keyur32 I have an angular based taskpane add, I am trying to create the custom function which uses most of the services from taskpane based addin, Please find the attached sample app, 
also 
1. angular application generates multiple javascript files, how to include that for custom function. 
2. if I just want to use HttpClient service from angular to query external data, how do i do that. 
3. can I format cells in excel to have a different background color or making text bold, in a custom function, is it supported looks like from documentation it's not, please confirm
4. what is the best way to make use of most of the services and classes we have created in task pane based addin.

[CFTestApp.zip](https://github.com/OfficeDev/office-js/files/4345872/CFTestApp.zip)

**Comment by keyur32** [comment]
Ah, in that case, we'd recommend using a shared runtime. This feature is in preview:

https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview

You can see a video of this in action from our March community call: https://developer.microsoft.com/en-us/office/blogs/office-add-ins-community-call-march-11-2020/ 

We'd love for you to try it and give feedback.  '

Also, the next Office Add-ins community call is on Wednesday, April 8, 2020 at 8:00AM PST. You can download the calendar invite at https://aka.ms/officeaddinscommunitycall.

thanks! closing for now, please reactivate if this doesn't solve your needs :)

**Comment by rahulaggarwalfl** [comment]
Is the shared runtime available for Word addins too? If not when can we expect it to become available.
