### ISSUE TITLE
context.sync hangs when writing data to excel

### ISSUE THREAD

**Issue by soorajhealthplotter** [OfficeDev/office-js#1046]
## Expected Behavior

I have got 54000 records fetched from the database and i insert into excel file using excel add in. It should write data to the excel file. 

## Current Behavior

While writing 54000 records fetched from the database and i tried to insert into excel file using add in. While writing data to the excel file it gets hangs up in context.sync in office 365 desktop version and throws out **ExecuteRichApiRequest** error in office online version.

In Office 365 Destop version it hangs up
In Office Online it throws a error: ExecuteRichApiRequest

## Code used

   Excel.run((context) ->
     sheet = context.workbook.worksheets.getItem(sheet_name)
     response_data = {"A1"=>"1000","A2"=>"1001","B1"=>"1000","B2"=>"1001","C1"=>"1000","C2"=>"1001"} # similary 54000+ records
    angular.forEach response_data, (key, value) -> 
      range = sheet.getRange(key)
      range.values = [[ value ]]
    context.sync().then ->
      console.log("Data synchronized")
      return
  ).catch (error) ->
    console.log 'Error: ' + error

## Your Environment

* Platform : Office Online and Office 365 Destop
* Host : Excel
* Operating System: Windows 10
* Browser (if using Office Online): Chrome

**Comment by lumine2008** [comment]
Thanks for your post. we can repro this issue, a bug4025494 was created to track this issue. 
there is a workaround that you could have a try. instead of calling range.values for 54000 times, you could use an array and assign it to range.values one time, then you can avoid this issue. here is the sample code you could have a try

```

        try 
        {
          var array = []
          for(var i = 0; i < 54000; i++)
          {
            array.push([1001]);
          }
          range.values = array;
          await context.sync();
        }
```
we also create a gist for you to verify this workaround
https://gist.github.com/lumine2008/31192a78134ea6b96fba0ff582321700

**Comment by soorajhealthplotter** [comment]
response_data = {"A1"=>"1000","A2"=>"1001","B1"=>"1000","B2"=>"1001"} # similarly 54000+ records
angular.forEach response_data, (key, value) ->
      range = sheet.getRange(key)
      range.values = [[ value ]]
context.sync()


This is the code i am using to insert data. For each column there is a specific value.For 54000+ column there is different value.how cal i get range for each column in array and assign data specific to column

**Comment by soorajhealthplotter** [comment]
I can see that the range you have selected

var range = sheet.getRange("A1:A54000")

In my case range may or may not be aligned.For example.
I have data for A1 but not for A2.Again i will have data for A3 and not for A4
i have no data for B1 but have data for B2 .Again no data for B3 and have data for B4 
Similarly upto A4463 to L4463

**Comment by lumine2008** [comment]
i think you could still use array, for the cell with no data, you could keep it blank, here is a sample for assigning range.values


```
    const data = [
      ["Product", "Qty", "Unit Price", "Total Price"],
      [, 2, 7.5, "=C3 * D3"],
      ["Coffee", , , "=C4 * D4"],
      ["Chocolate", 5, 9.56, "=C5 * D5"]
    ];

    range.values = data;
```

it shows like this below
![image](https://user-images.githubusercontent.com/26398035/76757836-5c1e6180-67c3-11ea-9743-a1366430fb38.png)

**Comment by soorajhealthplotter** [comment]
![Screenshot from 2020-03-16 18-03-23](https://user-images.githubusercontent.com/12229181/76758912-a6e2ae00-67b0-11ea-8a7e-74142d129a32.png)

Consider this case Year 2014,Year 2016 etc are information as text.they do not come from database.only the values like 1,2 3 ,4 5 etc comes from the database.if i set cell with not data to empty this informative text will be lost

**Comment by lumine2008** [comment]
Got it, based on our investigation the bug is coming from the `range.values` is calling for a lot of times within` context.sync()`. We are doing this investigation.  meanwhile, I think you could try to separate into 5 ranges in your scenario, therefore only 5 times of calling `range.values `

**Comment by soorajhealthplotter** [comment]
Any update on this..
As a workaround instead of calling range.values for 54000 times, initially i read all data from excel into an array. Then i fetched the data from database and updated the values coming from database to this array and written back to excel..Now the issue is avoided.

**Comment by lumine2008** [comment]
A bug (4025494) was created to track this issue. so far, I would suggest using this workaround to avoid calling range.values for 54000 times.

**Comment by lindalu-MSFT** [comment]
Has workaround, closing issue.
