### ISSUE TITLE
Office.context.mailbox.item.internetMessageId is empty for meetings/appointments

### ISSUE THREAD

**Issue by bx-anil** [OfficeDev/office-js#1047]
Missing message ID on Appointments/Meetings

## Expected Behavior
Office.context.mailbox.item.internetMessageId should have a value for meetings that are on Outlook Calendar. 

## Current Behavior
Office.context.mailbox.item.internetMessageId is null 
The message ID for the meeting should be populated for on Office.context.mailbox.item.internetMessageId.

* Additional details:
  1. Create a add-in and side load it. Have a call back Office onReady
  2. In the callback do console.log on Office.context.mailbox.item.internetMessageId
  3. Open an existing meeting on Outlook and open the add-in.

## Context
We are working on an add-in that needs to access the same meeting record for all the participants on the meeting. Office.context.mailbox.item.internetMessageId seems to have only one value for all emails and we are expecting same behavior on meetings

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Windows 10, Office online 
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 1912
* Operating System: Windows 10 v1809
* Browser (if using Office Online): Chrome.

**Comment by keyur32** [comment]
@JuaneloJuanelo  - can you comment on if above is supported or if we need to log a feature request on UserVoice please?

**Comment by bx-anil** [comment]
If this is not supported, can you please suggest a workaround.

**Comment by bx-anil** [comment]
Any update on this please.

**Comment by exextoc** [comment]
Currently the feature to get internetMessageId for calendar event via office js api is not available. internetMessageId api is only supported for Message Read (doc-https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-1.8#internetmessageid) We track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered, when we go through our planning process.

**Comment by bx-anil** [comment]
Do you suggest any workaround.  I understand that there is a unique id exists. There is global appointment id on the VB object model. https://docs.microsoft.com/en-us/office/vba/api/outlook.appointmentitem.globalappointmentid
Hence checking for a workaround.

**Comment by exextoc** [comment]
yes it was available in vba add-ins but currently there is no workaround.

**Comment by JuaneloJuanelo** [comment]
@bx-anil  so basically this is a feature request, we track those in uservoice.. Can you please open/upvote an idea https://officespdev.uservoice.com/

closing this issue

**Comment by JuaneloJuanelo** [comment]
closing this , as this is not an issue currently in the platform.
