### ISSUE TITLE
Does changing Add-in manifest.xml <Version> auto-update Custom Add-in's installed via URL?

### ISSUE THREAD

**Issue by mrbfrank** [OfficeDev/office-js#1048]
Regarding the section on Version here: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/manifests#version

Does changing Add-in manifest.xml &lt;Version&gt; auto-update Custom Add-in's that were manually installed via URL? This would be great for keeping QA engineers up to date during development & testing. The documentation could use some clarity on that as it's specifically what I'm trying to find an answer for, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 11323a5a-fd84-f259-9079-62732c695ed8
* Version Independent ID: 569f6274-2c83-e200-fc5a-9642193cb76c
* Content: [Outlook add-in manifests - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/manifests#feedback)
* Content Source: [docs/outlook/manifests.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/manifests.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by keyur32** [comment]
Hi @mrbfrank, can you share how you're deploying this to users?  

- If via the store, updating the version would prompt users to upgrade their add-in. When trusted they would get it.   
- If the add-in is centrally deployed via a file upload or url, I think an admin will need to re-push this out.

**Comment by mrbfrank** [comment]
Hi @keyur32 yes I am developing an add-in for internal use @ my company, so it will not be installed via the store. We will have our network admins push it to users on launch, & I was hoping to simply re-deploy with a version bump in the manifest & have our users automatically receive updates. It sounds like our admins will need to push each release. Please consider allowing Custom add-ins & Admin-managed add-ins deployed in an enterprise environment to auto-update, thank you.

**Comment by keyur32** [comment]
Thanks! Have you looked at Centralized Deployment? This supports exactly that scenario: https://docs.microsoft.com/en-us/office/dev/add-ins/publish/centralized-deployment

Your admins will only need to push the release of the manifest when the manifest itself changes. If you are mostly changing the taskpane or html/js, you will not need to re-deploy through centralized deployment.   If you're prefer a better approach, can you log a feature request on our uservoice channel?  https://officespdev.uservoice.com?

Hope that helps. Marking this as closed but feel free to reactivate if necessary.

**Comment by matthe68gps** [comment]
@keyur32 You mentioned "[Centralized Deployment] supports exactly that scenario". From his request, I am understanding this to mean that when you use Office 365 to do centralized deployment of an office addin to members of an organization- if you upload the manifest by url, everytime you update the manifest and the version number it should automatically update the addin throughout the organization? This is exactly the functionality that we are looking for but when we update the addin and version number nothing seems to change. 

Can you explain what you meant when you said, "This supports exactly that scenario?" If updating the manifest and the version number is supposed to update the addin, how soon should I expect to see those changes in the deployed addin?
