### ISSUE TITLE
OfficeJS based add-ins: Microsoft Outlook 2013 meet crash when strarting

### ISSUE THREAD

**Issue by hdkdinh** [OfficeDev/office-js#1049]
I am developing Outlook add-in using add-in execute a function.
I implement TLS 1.2 for add-in by:
ServicePointManager.SecurityProtocol = (SecurityProtocolType)3072;
After that, I build .exe file and install into outlook. It works ok on outlook 2016, outlook 365 but meet crash on outlook 2013 when starting.

**Your Environment**

- Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
- Host [Excel, Word, PowerPoint, etc.]: Microsoft Outlook 2013
- Office version number: 15.0.4569.1506
- Operating System: Windows 7
- .Net Framework: 4.0 and 4.5

**Comment by exextoc** [comment]
What Exe are you referring to? Office.js add-ins are traditionally just web pages.

**Comment by keyur32** [comment]
Hi @hdkdinh, can you specify your repro steps to produce the crash? Are you using the Yoeman Generator to build your add-in?  Does this happen with all add-ins (i.e from the store) or just the one your are developing on?

thanks!
