### ISSUE TITLE
Weird cross-process and cross-platform behaviour

### ISSUE THREAD

**Issue by leoseccia** [OfficeDev/office-js#105]
This is very strange: https://www.screencast.com/t/y5QSucSj

In this video, at the top I have Chrome (Version 65.0.3325.181 (Official Build) (64-bit)) and at the bottom I have Word 2016 desktop.

In fiddler, I can see a POST to https://word-edit.officeapps.live.com/we/OneNote.ashx which might be causing this behaviour...

I doubt it is a local issue as I am just dishing out the html+CSS+js files, statically from my web server and Chrome does not even use the same rendering engine to Word (which I assume uses IE11/Edge/Trident) 

Either way, it is weird. Is it by design? If it is, how do I disable it?

**Comment by JuaneloJuanelo** [comment]
I  was not able to repro this issue using a similar add-in from the store, (eg. please try Pickit), maybe this is something associated with your environment/add-in logic.
Closing issue unless solid repro is provided.
