### ISSUE TITLE
Outlook Web Access (OWA) fails to load add-ins for calendar items

### ISSUE THREAD

**Issue by bx-anil** [OfficeDev/office-js#1050]
OWA fails to load add-ins. The callback for onReady is never executed for Meetings/Appointments

## Expected Behavior
The call back for onReady should be executed.  Please note that this was working earlier and broke only recently ( ~ a week ago)

## Current Behavior
onReady callback is never executed. Console log has a null reference exception. (Attached is the log) 

* Additional details:
  1. Side load a test Outlook add-in with an "onReady" callback
  2. Console.log should below exception. 
![image](https://user-images.githubusercontent.com/52792802/76863138-75f88c80-6835-11ea-84bb-713ca1154c45.png)

## Context
The add-in never loads on OWA for meetings

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Windows 10, Office Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Semi annual channel
* Operating System: Windows 10
* Browser (if using Office Online): Chrome v79

## Useful logs

- [ x] Console errors
- [ x] Screenshots
![image](https://user-images.githubusercontent.com/52792802/76863349-bf48dc00-6835-11ea-9ed8-57aa6ec79437.png)

`recurrenceAdapter.ts:13 Uncaught (in promise) TypeError: Cannot read property 'Recurrence' of null
    at recurrenceAdapter.ts:13
    at VM148:405
    at Object.next (VM148:405)
    at VM148:405
    at new Promise (<anonymous>)
    at l (VM148:405)
    at Object.q [as getRecurrence] (recurrenceAdapter.ts:11)
    at getInitialAppointmentReadData.ts:52
    at VM148:405
    at Object.next (VM148:405)
(anonymous) @ recurrenceAdapter.ts:13
(anonymous) @ VM148:405
(anonymous) @ VM148:405
(anonymous) @ VM148:405
l @ VM148:405
q @ recurrenceAdapter.ts:11
(anonymous) @ getInitialAppointmentReadData.ts:52
(anonymous) @ VM148:405
(anonymous) @ VM148:405
(anonymous) @ VM148:405
l @ VM148:405
Tt @ getInitialAppointmentReadData.ts:23
(anonymous) @ TimeTypeEnum.ts:1
(anonymous) @ VM148:405
(anonymous) @ VM148:405
(anonymous) @ VM148:405
l @ VM148:405
Ft @ getInitialData.ts:25
(anonymous) @ owa.Addins.js:1
(anonymous) @ VM148:405
(anonymous) @ VM148:405
(anonymous) @ VM148:405
l @ VM148:405
(anonymous) @ getInitialDataApiMethod.ts:19
cn @ executeApiMethod.ts:74
(anonymous) @ EndpointRegistrator.ts:169
invoke @ osfruntime.js:2003
A @ osfruntime.js:1565
M @ osfruntime.js:1691
Promise.then (async)
s @ VM148:405
(anonymous) @ VM148:405
l @ VM148:405
(anonymous) @ getInitialDataApiMethod.ts:19
cn @ executeApiMethod.ts:74
(anonymous) @ EndpointRegistrator.ts:169
invoke @ osfruntime.js:2003
A @ osfruntime.js:1565
M @ osfruntime.js:1691
`

**Comment by fadamsen** [comment]
We're also seeing this issue across multiple add-ins in production, but only for Outlook on the web.

```
 TypeError: Object(...)(...).event is null in recurrenceAdapter.ts:12:18
```

**Comment by CTMinseok** [comment]
We are seeing the same issue on OWA only.

**Comment by bconners1005** [comment]
We also have a plug-in that is failing to load with the above issue.  The event does not occur on all users either.  My user is able to use the plug-in with no errors, but another user with the same access level on the system gets the 
`TypeError: Object(...)(...).event is null in recurrenceAdapter.ts:12:18`
error.  

So recap: Users of same/varying levels are running into the issue. 
 My user level works but another account on the same machine on the same plug-in instance received the above error.

**Comment by exextoc** [comment]
Thanks for reporting this issue. This issue has already been addressed and fixed by the team. Changes will be live by the end of the week.

**Comment by bx-anil** [comment]
Thanks. Is there a preview version that we can check on ?

**Comment by exextoc** [comment]
2020031603 contains the fix. Fix is already 30% deployed.

**Comment by exextoc** [comment]
Fix is 100% rolled out. Please confirm that you are not seeing this issue anymore.

**Comment by bx-anil** [comment]
Confirming that the issue is fixed.
