### ISSUE TITLE
recurrenceAdapter.ts:13 Uncaught (in promise) TypeError: Cannot read property 'Recurrence' of null

### ISSUE THREAD

**Issue by asith-w** [OfficeDev/office-js#1051]
When outlook add-in loading in OWA "recurrenceAdapter.ts:13 Uncaught (in promise) TypeError: Cannot read property 'Recurrence' of null" error can be seen in console. and add-in stops working
## Expected Behavior

add-in should work without issue
## Current Behavior

add-in does not work  
## Your Environment

 
* Operating System: windows
* Browser (if using Office Online): Chrome 

## Useful logs

- [ ] Console errors
```
 Uncaught (in promise) TypeError: Cannot read property 'Recurrence' of null
    at recurrenceAdapter.ts:13
    at VM144:405
    at Object.next (VM144:405)
    at VM144:405
    at new Promise (<anonymous>)
    at l (VM144:405)
    at Object.q [as getRecurrence] (recurrenceAdapter.ts:11)
    at getInitialAppointmentReadData.ts:52
    at VM144:405
    at Object.next (VM144:405)
```
![image](https://user-images.githubusercontent.com/5784846/76934750-bb8c8680-6915-11ea-8a3d-826e38bc8010.png)

**Comment by exextoc** [comment]
Thanks for reporting this issue. This issue has already been fixed and changes will be live by the end of the week.

**Comment by exextoc** [comment]
Fix is 100% rolled out. Please confirm that you are not seeing this issue anymore.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
