### ISSUE TITLE
[oneNote]Can't install add-in to oneNote

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1053]
Is there any way we can install add-in to oneNote? My version is [Version 16001.12624.20042.0]. 
And I finished coding follow microsoft's doc. But I didn't find a way to add my add-in to oneNote.

So...my question is, is there any limit on adding add-in to oneNote? For example, version or account 
authority? 
I can add add-in to outlook ,powerpoint or word. But just not find a way in oneNote.
![image](https://user-images.githubusercontent.com/15980696/77024254-061b0b00-69c9-11ea-9304-7c806b245576.png)

Actually I searched this problem on google found other developer add this under 'File' drop-doen menu. But I can't see it in my version. So... if this is the problem of version which version can I use?
Current oneNote was installed when I install office suit on office.com.

## Expected Behavior

Can add add-in to oneNote.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: oneNote
* Office version number: 16001.12624.20042.0
* Operating System: win 10 1909 18363.719
* Browser (if using Office Online): NA

**Comment by exextoc** [comment]
In [OneNote on the web](https://www.onenote.com/notebooks) choose Insert > Office Add-ins to open the Office Add-ins dialog.

**Comment by SWei1234** [comment]
> In [OneNote on the web](https://www.onenote.com/notebooks) choose Insert > Office Add-ins to open the Office Add-ins dialog.
@exextoc There is no this option under 'Insert'.
![image](https://user-images.githubusercontent.com/15980696/77039255-81dc7e00-69f0-11ea-84ec-0af113dc5b34.png)
I'm using a office 365 account. Will this effect?

**Comment by exextoc** [comment]
Can you please confirm is it a web app or desktop app?

**Comment by SWei1234** [comment]
@exextoc I found it here. Is this mean it's a desktop app? Or use other methods to determine? 
![image](https://user-images.githubusercontent.com/15980696/77039790-a2590800-69f1-11ea-8aa2-a30f937e4a75.png)
And I download a oneNote 2016,still can't add add-in, like:
![image](https://user-images.githubusercontent.com/15980696/77045532-55c6fa00-69fc-11ea-8a4f-1ba4458420e5.png)
 I have the authority to add add-in to outlook or word, need I buy another authority to develop add-in on oneNote?

**Comment by SWei1234** [comment]
@exextoc I download a oneNote 2016 and now I can see the add-in option.
At last I wonder how can we distinguish the oneNote is desktop or a web app?
Or my first install is a desktop version. Just not support add add-in?

**Comment by keyur32** [comment]
Hi there, thank you for the report. Currently add-ins in OneNote do not work on desktop. They are only avaialble in OneNote for Web. For information, you can follow the [OneNote Quickstart](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart). 

I would also suggest you vote for OneNote desktop support on our user voice site:  officespdev.uservoice.com

thanks!

**Comment by SWei1234** [comment]
Hi @keyur32 Thanks for your reply.
Last question, I success upload add-in to web oneNote. But problem is I cannot found it on web oneNote so that I can't delete this add-in.
looks like:
![image](https://user-images.githubusercontent.com/15980696/77271938-ef3b2800-6cea-11ea-9f0d-165143b7ca8a.png)
![image](https://user-images.githubusercontent.com/15980696/77271983-0a0d9c80-6ceb-11ea-9f54-ae77454f448c.png)
I added my add-in, but can't find it in store???
