### ISSUE TITLE
Safari, Exchange 2016 on-premise, OWA add-in does not load

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1057]
Outlook add-ins do not work in OWA with Exchange on-premise.

## Current Behavior
Empty add-in's pane is opened.

## Steps to Reproduce, or Live Example
You can start any add-in for compose mode. The add-in's pane opens, but it is empty. The following error can be found in the console:

[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (owa.clientnext.frepanel.js.map;, line 0)
[Error] SyntaxError: Unexpected token '<'
(anonymous function) (logon.aspx:1)

## Your Environment
* Platform: Office Online
* Host: OWA (Exchange 2016 (15.1 build 1913.5))
* Office version number: ______
* Operating System: macOS Catalina Version 10.15.3
* Browser: Safari Version 13.0.5 (15608.5.11)
* Exchange 2016 (15.1 build 1913.5)

**Comment by exextoc** [comment]
Are you facing this issue only on OWA on mac browser? Or is it reproing in OWA on Windows also? Console log shared by you looks incomplete. Can you share complete console error log?

**Comment by DmitryKostochko** [comment]
The issue is reproducible only on OWA in the Safari browser. Please see the complete log attached.
[log.txt](https://github.com/OfficeDev/office-js/files/4375697/log.txt)

**Comment by exextoc** [comment]
We are able to repro this bug. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: OutlookWeb:82206

**Comment by penpaapp** [comment]
Did this ever get fixed? This looks to relate to an issue we're having

**Comment by exextoc** [comment]
@askariblue ,

This issue was no longer reproducible. We suspect this was an issue with Safari which has since been fixed. Are you still able to see this issue?
