### ISSUE TITLE
js freezes when using officeRuntime.storage functions

### ISSUE THREAD

**Issue by benj-spectory** [OfficeDev/office-js#1058]
Hi,
office 365 version 2002 (installed on the computer - not on the browser), - win 10  

i have a weird bug.
i have a select, and a button elements in the HTML page.
when i press the button i'm using the getItems([...]) function -&gt; this works
when i change the select to a different option (even if i change it back to the first option) and i press the button and using the  getItems([...]) function -&gt; the js freezes. no error, no catch, nothing

the weirdest part is that the same code is working on the office 365 browser version. 

html:
```
<body class="ms-font-m ms-welcome ms-Fabric">
	<select id="cars">
		<option value="volvo">Volvo</option>
		<option value="saab">Saab</option>
		<option value="mercedes">Mercedes</option>
		<option value="audi">Audi</option>
	</select>
	<button class="click">click me</button>
	<div id="log"></div>
</body>
```
javascript:
```
Office.initialize = () => {
    (<HTMLDivElement>document.getElementsByClassName("click")[0]).onclick = getItems;
    OfficeRuntime.storage.setItems({ "a": "aaa", "b": "bbbb" });

};

async function getItems() {
    try {
        const x = await OfficeRuntime.storage.getItems(["a", "b"]);
        document.getElementById('log').innerHTML = "elements: " + JSON.stringify(x);
    } catch (error) {
        document.getElementById('log').innerHTML = "error: " + error;
    }
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eee3f1a5-71e4-c875-35a9-e826afe94ac3
* Version Independent ID: 7a691d06-b135-c724-db66-25af1341d7a1
* Content: [OfficeRuntime.Storage interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office-runtime/officeruntime.storage?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office-runtime/officeruntime.storage.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office-runtime/officeruntime.storage.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lindalu-MSFT** [comment]
Are we supporting Office 2002? I'm not sure who to assign this to!

**Comment by ElizabethSamuel-MSFT** [comment]
@RuoyingLiang This seems related to custom functions. Can you take a look?

Thanks.
