### ISSUE TITLE
Publishing Word add-in

### ISSUE THREAD

**Issue by schostac** [OfficeDev/office-js#1060]
Can I publish add-ins in AppStore if I create a developer account as an individual? I've created one but there is not such option.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2677af5b-e9b8-f962-25ce-8aa285977c90
* Version Independent ID: c31c7ed9-0a0a-7a65-0d1b-70d6a8b33994
* Content: [Deploy and publish Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish#feedback)
* Content Source: [docs/publish/publish.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/publish.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@schostac Thanks for your question.

@weshi Can you take a look?

Thanks.

**Comment by weshi** [comment]
@schostac Yes, you can. You can go to the [Partner Center](https://partner.microsoft.com/), select Dashboard, and then you will find the option to create new apps.
