### ISSUE TITLE
[Outlook add-in] All add-in can't refresh page

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1061]
For windows 1909 18363.720 with outlook 2019.
All add-in can't use location.reload() or refresh the page with F5.
And can't show right click menu on any add-in.
 I tried some PC with 1909 and almost all have same problem.

All above works fine on lower windows version which use IE core.
Is Microsoft change a new way refresh pages on add-in?Please let me know.
Thanks

## Expected Behavior

 location.reload() can reload the page.

## Current Behavior

Try use  location.reload() , F5 and  right click menu refresh add-in page.

## Steps to Reproduce, or Live Example
Just try use  location.reload() , F5 and  right click menu refresh add-in page.
You can reproduce this problem.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook 2019
* Office version number: 2002
* Operating System: Windwos 1909 
* Browser (if using Office Online):  NA

**Comment by exextoc** [comment]
Are you trying to programmatically refresh the add-in page? for edge, try using ctrl+F5, that should refresh the page for you

**Comment by SWei1234** [comment]
Hi @exextoc Thanks for your reply.
Yes, I tried that. But still not work. This problem happened on windows outlook client only.
For browser and mac refresh is work.
Actually I don't care about right click not work or can't refresh by 'F5'/'ctrl+F5'.
The real problem is function location.reload() not work on outlook add-in.
This will cause ,for example: some reset function which call location.reload() not work.

**Comment by SWei1234** [comment]
@exextoc Any update? Or this is confirmed not a problem?

**Comment by exextoc** [comment]
@SWei1234 you mentioned that location.reload() is not working because you have a function that you expect to be called once the reload is successful? If that is accurate, do you see any errors in the debug console when you debug your add-in?

**Comment by SWei1234** [comment]
Hi @exextoc I didn't see anything show on devTool when I call location.reload(). 
Anything else need I provide?  Or a recording?

**Comment by exextoc** [comment]
@SWei1234, if you have a recording, that will be helpful. You can also add a console.log() call inside the Office.initialize function and check to see if anything got logged to the console after calling location.reload().

**Comment by SWei1234** [comment]
Hi @exextoc 
Sorry for reply recording so late:
Recording:
https://success.zoom.us/rec/share/_8d2f4zR2SBITYXB9BzTXYEcGJ75X6a80yMd__UEyE3mbwJ-c7jg9Pn0Llrc9gU0
Access Password: 3a!4.p7Z

By the way, location.reload() is also not work.  This problem can be reproduce on all add-in include 'View Templates'
Please reopen this issue, Thanks

**Comment by exextoc** [comment]
We are unable to repro this issue. When you press F5 to refresh, make sure the focus is on the add-in. 

Does this issue repro with a store add-in? Instructions for how to get an Outlook add-in form the store can be found [here](https://support.office.com/en-us/article/get-an-office-add-in-for-outlook-1ee261f9-49bf-4ba6-b3e2-2ba7bcab64c8).

**Comment by SWei1234** [comment]
Yes, I can reproduce this on store add-in, include Webex, emoji or zoom . 
If you can't reproduce this problem can we have a trouble shooting meeting on teams or zoom?

**Comment by exextoc** [comment]
For the location.reload() issue, have you tried adding a console.log() inside the Office.initialize function? This will help you see if the add-in did actually reload or not. 
Would you be able to provide a recording or test account that reproes the issue with location.reload()?

**Comment by SWei1234** [comment]
Sure, I will paste it here later. Thanks for your support
