### ISSUE TITLE
[Outlook add-in] Can add-in in Meeting or appointment can get 'save' and 'close' event?

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1062]
>>> PLEASE USE USER VOICE FOR FEATURE REQUESTS <<<
 Can add-in in Meeting or appointment can get 'save' and 'close' event?

Post feature requests at https://officespdev.uservoice.com/

 Can add-in in Meeting or appointment can get notification when user click 'save' or ’Close‘?

**Comment by exextoc** [comment]
Currently the feature to get save and close event in meeting/appointment is not supported for add-in via office js apis. We track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered, when we go through our planning process.

**Comment by ElizabethSamuel-MSFT** [comment]
@SWei1234 As suggested, please add a request for this feature on User Voice. I'll close this now but if you have any further questions or comments, let us know.

Thanks.
