### ISSUE TITLE
Outlook add-in: Calling saveAsync on CustomProperties results in Undefined AsyncResult

### ISSUE THREAD

**Issue by Broomish** [OfficeDev/office-js#1064]
I have only seen this issue on the Outlook Web App on Exchange 2016 and Exchange 2019. OWA on Exchange 2013 and Office 365 works as expected.

In our Outlook Add-In, we are making use of custom properties. We add a property and call `saveAsync`: https://docs.microsoft.com/en-us/javascript/api/outlook/office.customproperties?view=outlook-js-preview#saveasync-callback--asynccontext- , passing a `callback`

This callback should be called with a `Office.AsyncResult` but instead it is getting "Undefined".

## Expected Behavior
The `callback` function being passed into `saveAsync` should get called with a `Office.AsyncResult`

## Current Behavior
The `callback` **is** getting called but the passed `Office.AsyncResult` is Undefined

## Steps to Reproduce, or Live Example
I can reproduce using the code example on https://docs.microsoft.com/en-us/javascript/api/outlook/office.customproperties?view=outlook-js-preview:

```js
(function () {
    'use strict';

    Office.initialize = function () {
        // Checks for the DOM to load using the jQuery ready function.
        $(document).ready(function () {
            // After the DOM is loaded, add-in-specific code can run.
            var item = Office.context.mailbox.item;
            item.loadCustomPropertiesAsync(customPropsCallback);
        });
    };

    function customPropsCallback(asyncResult) {
        var customProps = asyncResult.value;
        var myProp = customProps.get("myProp");
        console.log("myProp: " + myProp); // First run on current item will return `undefined`.

        // Set myProp custom property.
        customProps.set("myProp", "value");
        customProps.saveAsync(saveCallback);
    }

    function saveCallback(asyncResult) {
        if (asyncResult.status === Office.AsyncResultStatus.Failed) {
            console.error(asyncResult.error.message);
        }
        else {
            console.log("save successful");
        }
    }

})();
```
I serve that from a file called `addin.js` and this is the error in the chrome console logs:
![Screenshot from 2020-03-26 13-29-35](https://user-images.githubusercontent.com/11697734/77652268-e2763880-6f65-11ea-8022-b30290728000.png)

So the `asyncResult` being passed into the `saveCallback` is undefined.

Also, this might be interesting: If I run the add-in a second time, this is the console output:
![Screenshot from 2020-03-26 13-31-44](https://user-images.githubusercontent.com/11697734/77652566-557faf00-6f66-11ea-9dac-e68975c93b70.png)

So notice the property has actually been set. I think this means the custom property is getting successfully saved. It's just that the passed in  `asyncResult` is Undefined.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Outlook Web App (OWA) on Exchange Server 2016 and 2019
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: I updated the Exchange 2019 server I am testing with to CU5
* Operating System: Seen on MacOS Mojave 10.14.8, Ubuntu 18.04.4, Windows 10 Pro 1909
* Browser (if using Office Online): Chrome / Firefox on Mac & Ubuntu, Edge on Windows

**Comment by onestep** [comment]
I can confirm this issue is reproducible with both Exchange 2016 and 2019.

**Comment by andmaz** [comment]
I have the same problem

**Comment by sergez** [comment]
Have the same issue

**Comment by ElizabethSamuel-MSFT** [comment]
Thanks for raising this issue. Assigned to feature team to take a look.

**Comment by exextoc** [comment]
We are able to repro this bug. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: OutlookWeb:81772

**Comment by krisrm** [comment]
Is there an ETA on a fix for this one? I have this issue in Outlook 2016 and OWA with Exchange 2016.

**Comment by agelenava** [comment]
just faced the same issue on Exchange 2016 OWA. Do you plan to fix it?

**Comment by dmbilous** [comment]
Same story with Exchange 2016.

**Comment by exextoc** [comment]
Tracked by 1429370
________________________________

**Comment by exextoc** [comment]
We have already fixed this issue and its 100% live.
