### ISSUE TITLE
Issue with add-in when hosted on https

### ISSUE THREAD

**Issue by BlackStef** [OfficeDev/office-js#1065]
I'm having a similar issue but that one is closed : https://github.com/OfficeDev/office-js/issues/631

I get some RichApi.Error : AccessDenied when I try to extract data from my workbook with my add-in. 

The add-in is working well in debug or hosted without https. I have the ReadWriteDocument enabled in my manifest. 

Environment :
Windows 10
Office 365 Pro plus, Excel 1902
Office-js  : 1.0.31

Unfortunately I can't share some screen because It's on my professionnal laptop and all is restricted due to my company policy. 

Don't hesitate if you need extra informations. 
Thank you in advance for your help !

**Comment by lumine2008** [comment]
Thanks @BlackStef  for your report, however, based on limited information in this post, we are not able to repro this issue, so Could you please share a gist to us for repro? Thanks.

![image](https://user-images.githubusercontent.com/26398035/77751677-197d4480-7061-11ea-85bb-a4167c9e5af6.png)
