### ISSUE TITLE
[Excel] Custom function can't render dynamic array on Windows install version

### ISSUE THREAD

**Issue by nkrtarm** [OfficeDev/office-js#1066]
I have an issue on custom function trying to render dynamic array in Excel Windows install version. It's working fines on web version and Mac install version but not on Windows. The formula has been changed by appending `@` at the front `=@FORMULA.NAME(...)` and the data was rendered into single cell. Moreover, If users have built the formula from the other version, It will not works on windows install version. Instead, They're getting the popup message say `You can't change part of an array`.

## Expected Behavior
Dynamic array should works on Excel Windows install version.

## Current Behavior
- Only first top-left field of dynamic array has been rendered.
- Dynamic array that rendered from other version will not works on Windows install version.

## Your Environment
* Platform: PC desktop
* Host: Excel
* Office version number: 2002 (Build 12527.20278)
* Operating System: Windows 10

<img width="520" alt="Screen Shot 2563-03-25 at 14 40 29" src="https://user-images.githubusercontent.com/7779734/77683638-43842780-6fcb-11ea-965e-52dde358d1e6.png">
<img width="567" alt="Screen Shot 2563-03-25 at 14 40 07" src="https://user-images.githubusercontent.com/7779734/77683648-4848db80-6fcb-11ea-9501-024489e5db9f.png">

**Comment by RuoyingLiang** [comment]
@nkramer The feature is in production but doesn't have 100% flight on. You may not in the part which flight is on. Could you restart Excel or wait several more build and try again? Thanks for your patient!

**Comment by ElizabethSamuel-MSFT** [comment]
@nkramer Closing this for now while the feature rolls out.

Do let us know if the feature is still unavailable even after the rollout completes, or if you're facing any other issues.

Thanks.
