### ISSUE TITLE
Custom function script in XML file was loaded differently on windows install version

### ISSUE THREAD

**Issue by nkrtarm** [OfficeDev/office-js#1067]
Please check on the manifest via https://www.nkrtarm.com/cf/manifest.xml
Formula:   =TEST.TEST()

As you can see from the manifest above, I have a script file name "**in-js.js**" inside **xml** `<Script>` containing custum-function function to print a string `Hello, from Functions.Script.Url`.

And also html file of custom-function in `<Page>` containing html that have another script inside named "**in-html.js**". It's printing `Hi, I\'m loaded from HTML`

My purpose is to observe the excel's behaviour about how its executed their script between "**in-js.js**" and "**in-html.js**". The result is all excel versions (Mac install version, Chrome, Edge, Safari) are using "**in-js.js**" -- while **Windows install version** using "**in-html.js**".

## Expected Behavior
Windows install version should execute the script from html "**in-html.js**" -- just like other

## Current Behavior
Windows install version ignore html file in Page tag.

## Steps to Reproduce, or Live Example
Please see the manifest above.

## How has this issue affected you?
Based on my company flow, We have two domains - public and private

**Public Domain** should not containing any sensitive information at all. We're planning to stored a simple function to print string say 'please, sign in'. while looping check for the user credential on local/runtime storage and redirect them to the **private domain** when they're logged in.

**Private Domain** contains a real script file that included with all business logic and request endpoint inside retrieving all information and display to user.

We've tested on all all excel version, the concept above is working perfect **except for Windows install version** that download the script file and cache them locally. So, it's break our concept to **load the script files dynamically**.

## Tested on Windows 10 Excel install version
<img width="520" alt="Screen Shot 2563-03-25 at 14 40 29" src="https://user-images.githubusercontent.com/7779734/77692084-92848980-6fd8-11ea-87f1-35be0c822b0f.png">

**Comment by ElizabethSamuel-MSFT** [comment]
@nkrtarm Thanks for raising this issue.

@RuoyingLiang Can you take a look?

Thanks.

**Comment by RuoyingLiang** [comment]
Sorry I miss this thread. On windows, the js runtime is used instead of webview, that's why the behavior is different than Mac/Online. Could you try shared runtime for your scenario? [https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview](url)

**Comment by nkrtarm** [comment]
Sorry for late reply. The above shared js runtime will perfectly solve our issue and make it a lot easier to work with custom-function. Unfortunately, It's still in preview and we need to release our add-in soon. Anyway, Do you have any idea how this will be rolled out to production? we would like to keep track of it and hope we will hear a good news soon.

**Comment by RuoyingLiang** [comment]
Glad to know it's resolved with shared runtime. The feature is already released.
