### ISSUE TITLE
Can't change data format that rendered from custom function

### ISSUE THREAD

**Issue by nkrtarm** [OfficeDev/office-js#1068]
Data formatting in cell not have any affect to the data that have been rendered by custom function.

## Expected Behavior
Data formatting in cell should be applied to the data that have been rendered by custom function.

## Step to reproduce
Please check on the video via https://www.nkrtarm.com/cf/assets/215.mp4

**Comment by RuoyingLiang** [comment]
@nkrtarm Thanks for reporting. We are trying to repro this issue but couldn't repro in our environment. My Office Build number is 12624.20296. Could you help to let us know your build number? 
According to the video, seems the issue occurs in Windows Excel (please let me know if I'm wrong). Could you also try in Excel Online to see if you still encounter this issue? 
In your scenario, are you return the value from custom function directly? or you are doing some extra steps after custom function execution ( for example, change format using API)?

**Comment by nkrtarm** [comment]
@RuoyingLiang , Thank you for your prompt response. It's a Windows Chrome on the video, we also ran a test on Mac Chrome, Mac Safari, Mac install version, Windows Edge. The values have been returned directly from custom function.

Could you please help check on this manifest https://www.nkrtarm.com/cf/215/manifest.xml

Formula:   =TEST.TEST()

---
I have rechecked with the manifest above, looks like we are able to change the data format of number **if its value type is number** but **still not works with date/time format**.

**Comment by RuoyingLiang** [comment]
Thanks @nkrtarm. Seems this issue exists in dynamic array. We will investigate with feature team and back to this thread once we have update.

**Comment by RuoyingLiang** [comment]
Thanks @nkrtarm. We looked into this issue. As custom function's return value is string, Excel cannot convert string to data/time format. ( you can try to input a data/time string to a cell which format is Text, then convert the format. The format cannot be converted.)

We have a backlog work item for custom function return formatted data. That should address your requirement. Sorry for the inconvenient. Meanwhile, it will be great if you can help to raise the request in UserVoice [https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/filters/top?category_id=163563](url) to help us prioritize the feature.

**Comment by nkrtarm** [comment]
@RuoyingLiang, Thank you so much for your help. I have raised the request at UserVoice https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/40034089-fix-an-issue-on-excel-custom-function-about-data-f

Hope the issue gets resolved soon. Thanks again.

**Comment by RuoyingLiang** [comment]
Use UserVoice to track new request.

**Comment by jordandev** [comment]
is this still coming
