### ISSUE TITLE
Can;t show task pane of excel add-in tutorial

### ISSUE THREAD

**Issue by tuantruongminh** [OfficeDev/office-js#107]
Hi there

I am learning Office add-n and have just been practicing to make a button in excel. I can't show the new button in the excel ribbon even copy and run the complete add-in project from GitHub. Can anyone help?

Best regards

Tuan

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by Rick-Kirkham** [comment]
@tuantruongminh 
The issues for this repo are intended for reported suspected bugs with the Office JavaScript library. For problems with the Excel tutorial, please ask this question in the issues for the tutorial's repo: [Excel-Add-in-Tutorial](https://github.com/OfficeDev/Excel-Add-in-Tutorial)
