### ISSUE TITLE
Invalid Reference during error result of getInternetHeadersAsync.

### ISSUE THREAD

**Issue by gamblecd** [OfficeDev/office-js#1070]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

While calling getAllInternetHeadersAsync during viewing an email from an on-premise environment, we dont receive an error in the callback, but rather the equivalent of an NullPointerException in console.

`"outlook-web-16.01.js:19 Uncaught TypeError: Cannot read property 'OoeOperationNotSupported' of undefined at outlook-web-16.01.js:19 at Object.a [as callback] (outlook-web-16.01.js:19) at J (outlook-web-16.01.js:19)"
`
## Expected Behavior
IN On premise environments this call is not expected to work, so we should receive a failure in the callback that is passed in.

## Current Behavior
The above error occurs, 
it looks like the call to return the error code is referencing: [minified].DDA.ErrorCodes.OoeOperationNotSupported.
where DDA does not have a member called error codes.

I think the intention is that it should be calling [minified].DDA.**ErrorCodeManager**.errorCodes.ooeOoeOperationNotSupported. As that appears to be a valid object when stopped at that line in the code.

## Steps to Reproduce, or Live Example
Log into an On-Premise account.
Open an email.
Open dev tools.
Enable Break on all exceptions.
call OfficeJs 1.8 context.mailbox.item.getAllInternetHeadersAsync
The debugger will stop at the invalid line.

## Context
We handle errors from the callback, since this issue isn't allowing the callback to be called, it is interfering with how we handle errors.
Also we have a try catch wrapping the OfficeJS call as well, but that doesn't seem to be catching the issue. Resulting in logic to not be finished.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Outlook Web App
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: O365 - current version, JS API 1.8
* Operating System: OSX Catalina
* Browser (if using Office Online): Chrome

## Useful logs

Relavent Console Log:
```
outlook-web-16.01.js:formatted:9326 Uncaught TypeError: Cannot read property 'OoeOperationNotSupported' of undefined
    at outlook-web-16.01.js:formatted:9326
    at Object.a [as callback] (outlook-web-16.01.js:formatted:9356)
    at J (outlook-web-16.01.js:formatted:4545)
```

**Comment by ElizabethSamuel-MSFT** [comment]
@gamblecd Thanks for raising this issue.

@exextoc Can you take a look?

Thanks.

**Comment by exextoc** [comment]
We are able to repro this bug. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: OutlookWeb:81771
