### ISSUE TITLE
Manifest file including multiple extension points doesn't work

### ISSUE THREAD

**Issue by masa-fleet** [OfficeDev/office-js#1072]
## Summary
We are creating Outlook add-in which has "Add-in commands" and "Contextual add-ins" extension points. Even if installation succeeded, Outlook doesn't show Add-in commands and doesn't detect context (RegularExpressionMatch).

## Expected Behavior
- Outlook shows Add-in commands as "Add-in commands".
- Some of email texts are colored blue and underlined if it is matched regular expression as "Contextual add-ins".

## Current Behavior
"Add-in commands" and "Contextual add-ins" doesn't work.
- Outlook doesn't show Add-in commands
- Any email texts are not colored blue and underlined.
- Even if installation succeeded, I can't see the add-in in the [My add-ins] view.

### Preparation
Please download following files for your test. First 2 files works expectedly.
- Simple "Add-in Commands" add-in manifest file (https://contextaddinmasota.blob.core.windows.net/share/simple-manifest.xml)
-  Simple "Contextual add-ins" manifest file (https://contextaddinmasota.blob.core.windows.net/share/contoso-order-number-manifest.xml)
- Manifest file including "Add-in Commands" and "Contextual add-ins" (https://contextaddinmasota.blob.core.windows.net/share/simple-2extensions.xml).

**All manifest files have been validated** by [validation tool](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#validate-your-manifest-with-office-addin-manifest).

### Steps
Because this is manifest problem, I can't provide live example. So, let me share repro steps.
1. Launch Outlook (I'm using Outlook for Mac)
2. Click [Get Add-ins] button in the [Home] tab. -> Open [Office Add-ins] window.
3. Click [My add-ins] menu. You can see [Custom add-ins] in bottom.
4. Click [+ Add a custom add-in] button, then click [Add from file].
5. Select downloaded Manifest file (simple-2extensions.xml) and install it.

Outlook sometimes take longer time and fail installation. If you see this error, please install other manifest file and uninstall the add-in, then please retry installation with `simple-2extensions.xml`.

6. You can see "SampleAddin" as the Custom add-ins.
7. Close [Office Add-ins] window.
You can't see both "Add-in commands" and "Contextual add-ins". If you open [Office Add-ins] window, you can't see installed add-in as custom add-in.

## Context
We are creating add-in with backend. User-A can create item on task pane (Add-in commands), then Outlook add-in send it to back-end. Other users vote in the item by other application. When all users complete vote, back-end app will send email to User-A. User-A need to see item detail page to check result.
Because we want to improve UX, we want let User-A open item detail page by clicking email text (contextual add-in). It can reduce 3 steps, so we really want to use both contextual add-in and Add-in commands.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.35 (20030802)
* Operating System: Mac OS Catalina (Version 10.15.3)
* Browser (if using Office Online): NA

## Useful logs
When I use validation tool for all manifest files I saw following messages
```
masayukis-MacBook-Pro:SecretaryExtension masa$ npx office-addin-manifest validate simple-2extensions.xml 
npx: installed 32 in 2.13s
The manifest is valid.

Based on the requirements specified in your manifest, your add-in can run on the following platforms; your add-in will be tested on these platforms when you submit it to the Office Store:
  - Outlook 2013 or later
  - Outlook 2016 or later
  - Outlook 2016 for Mac
  - Outlook on the Web
Important: This analysis is based on the requirements specified in your manifest and does not account for any runtime JavaScript calls within your add-in. For information about which API sets and features are supported on each platform, see Office Add-in host and platform availability. (https://docs.microsoft.com/office/dev/add-ins/overview/office-add-in-availability).
```

**Comment by ElizabethSamuel-MSFT** [comment]
@NT-D Thanks for raising this issue.

@exextoc Can you take a look?

Thanks.

**Comment by exextoc** [comment]
There is a problem with the manifest as it contains duplicate Resource Ids in both VO 1.0 and VO 1.1. Duplicate resource Ids are groupLabel and customTabLabel, once you remove these it should start working.

**Comment by masa-fleet** [comment]
@ElizabethSamuel-MSFT , @exextoc 
Thank you for your quick comment. I removed the duplicate resource Ids and finally it works. Sorry for consuming your time by easy mistake...

Btw, I'm happy if you update manifest validation tool to detect duplicate setting.

**Comment by ElizabethSamuel-MSFT** [comment]
@NT-D Glad to hear that helped.

Regarding your feedback about the manifest validation tool, we encourage to take a moment to make this suggestion in a new issue on the [toolbox repo](https://github.com/OfficeDev/office-toolbox/issues).

Thanks.

**Comment by exextoc** [comment]
I created this toolbox repo issue:
https://github.com/OfficeDev/office-toolbox/issues/41

**Comment by masa-fleet** [comment]
Thank you very much for your support!
