### ISSUE TITLE
Outlook Add-in is not loading in chrome as well as in office 365 account in Edge and IE

### ISSUE THREAD

**Issue by shahshyam** [OfficeDev/office-js#1073]
I am getting following message when try to open in chrome and Edge
**Something went wrong and we couldn't start this add-in. Please try again later or contact your system administrator.**

![image](https://user-images.githubusercontent.com/4408930/77813614-0c4c6e00-70d2-11ea-9383-ffc189a7e72f.png)

Technology used node.js and ejs template  page is hosted in heroku.
[Portlr.zip](https://github.com/OfficeDev/office-js/files/4396558/Portlr.zip)

I have upload manifest.xml file in zip folder

**Comment by exextoc** [comment]
We are able to repro this bug. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Hey @shahshyam ,

We looked into your add-in. It seems that the officeJS library files are not being loaded for your add-in. Please do include the scripts in your page to use the OfficeJS APIs and avoid this error.

**Comment by proloopdev** [comment]
Hello, Same 
[server.zip](https://github.com/OfficeDev/office-js/files/4509452/server.zip)
thing is loading from outlook Desktop. I used node.js and ejs template. I am attaching code here

**Comment by shahshyam** [comment]
Please check above source Code

**Comment by shahshyam** [comment]
> Hey @shahshyam ,
> 
> We looked into your add-in. It seems that the officeJS library files are not being loaded for your add-in. Please do include the scripts in your page to use the OfficeJS APIs and avoid this error.

first page is login page which does not need to login office.js .

**Comment by elthombre** [comment]
can someone offer insight into what needed to be changed in the manifest or routes (i.e. what was causing this error?)

**Comment by exextoc** [comment]
@elthombre this issue was closed many months ago. If you have a related issue, please open a new one.
