### ISSUE TITLE
ExtensionPoint can't contain RequestedWidth and RequestedHeight elements

### ISSUE THREAD

**Issue by masa-fleet** [OfficeDev/office-js#1074]
Even if the document describes `ExtensionPoint` element can contain `RequestedHeight` element, we can't add it. We also can't add `RequestedWidth`, either. You can refer validation tool error log on the bottom of this page

[Referred document](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/requestedheight)

## Expected Behavior
- We can add both `RequestedHeight` and `RequestedWidth` as child elements of `ExtensionPoint`
- Validation tool doesn't show error

## Current Behavior
- If we add both `RequestedHeight` and `RequestedWidth`, we can't install this manifest
- Validation tool shows error (please refer `Useful logs` section)

## Steps to Reproduce, or Live Example
1. Download [this manifest file](https://contextaddinmasota.blob.core.windows.net/share2/contoso-order-number-manifest.xml)
1. Launch Outlook (I'm using Outlook for Mac)
1. Click [Get Add-ins] button in the [Home] tab. -> Open [Office Add-ins] window.
1. Click [My add-ins] menu. You can see [Custom add-ins] in bottom.
1. Click [+ Add a custom add-in] button, then click [Add from file].
1. Select downloaded Manifest file (contoso-order-number-manifest.xml) and install it.

## Context
For better UX, we want to arrange contextual add-in height and width. Our add-in need higher height than that of default one.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.35 (20030802)
* Operating System: Mac OS Catalina (Version 10.15.3)
* Browser (if using Office Online): NA

## Useful logs
validation tools shows following error message
```
Masayukis-MacBook-Pro:Outlook-Add-In-Contextual-Regex masa$ npx office-addin-manifest validate contoso-order-number-manifest.xml 
npx: installed 32 in 2.722s
The manifest is not valid.

Error # 1: 
XML Schema Violation: Your manifest does not adhere to the current set of XML schema definitions for Office Add-in manifests. (link: https://aka.ms/add-in-manifest-schema-violation)
  - Details: The element 'ExtensionPoint' in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1' has invalid child element 'RequestedHeight' in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1'. List of possible elements expected: 'Rule'
 in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1'.
  - Line: 75
  - Column: 16
```

**Comment by exextoc** [comment]
ExtensionPoint can contain RequestedHeight but not RequestedWidth, Try removing RequestedWidth from your manifest, it should work.

**Comment by masa-fleet** [comment]
@exextoc Thank you for your comment. Although I removed `RequestedWidth`, I still get following error from validation tool. Also can't install add-in to Outlook.

From the error message, I think `ExtensionPoint` doesn't support to contain `RequestedHeight`. Would you please double check in your environment ?
```
Masayukis-MacBook-Pro:Downloads masa$ npx office-addin-manifest validate contoso-order-number-manifest.xml
npx: installed 32 in 4.097s
The manifest is not valid.

Error # 1: 
XML Schema Violation: Your manifest does not adhere to the current set of XML schema definitions for Office Add-in manifests. (link: https://aka.ms/add-in-manifest-schema-violation)
  - Details: The element 'ExtensionPoint' in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1' has invalid child element 'RequestedHeight' in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1'. List of possible elements expected: 'Rule' in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1'.
  - Line: 75
  - Column: 16

```

**Comment by exextoc** [comment]
I used the same manifest which you have shared, removed the <RequestedWidth.../> tag and it works fine for me in both Outlook web and Outlook Desktop, Can you share your updated manifest which you are trying.

**Comment by masa-fleet** [comment]
Sure. Would you please try this manifest ?
https://contextaddinmasota.blob.core.windows.net/share3/contoso-order-number-manifest.xml

**Comment by exextoc** [comment]
So there is another issue this with manifest. The elements under ExtensionPoint have to be in a particular order. RequestedHeight tag should come after label tag and before SourceLocation tag.

**Comment by masa-fleet** [comment]
Thank you. It works.

Let me provide feedback. This is undocumented information, so no developers can understand this particular order. So, how about to do following actions to resolve future problem ?
1. Provide this information in the [document](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/requestedheight).
2. Update validation tool to show correct order ?

This is depends on your decision, but other developers may avoid same problem in the future.

**Comment by ElizabethSamuel-MSFT** [comment]
Related PR: https://github.com/OfficeDev/office-js-docs-pr/pull/1732
