### ISSUE TITLE
Change Icons in Custom Add-in in Outlook

### ISSUE THREAD

**Issue by shr9227** [OfficeDev/office-js#1076]
Hi All,

I've been ask to create custom Add-in in Outlook that when the icon is clicked - a website opens.

I follow the Build your first Outlook add-in and quickly got the functionality I wanted.

But when I tried to change the OOTB icons: 
![icon-32](https://user-images.githubusercontent.com/62870871/77881247-384d2800-7267-11ea-818a-a8c135cd3a8c.png) - This doesn't work and I get Default icon: ![IconOOTB](https://user-images.githubusercontent.com/62870871/77881257-426f2680-7267-11ea-88da-f99666ed0014.PNG)

I tried to rename the new image to the same name as the old ones - didn't work

Tried to insert images from the internet - didn't work

Tried to re-build the project with no luck - didn't work

Another thing, may be it's the problem - all the hyperlinks are "https://localhost:3000/......"

Can anyone help me with this? :)

Thanks,

**Comment by exextoc** [comment]
To change the icons you need to change the URL's in the manifest, Did you try that? All the hyperlinks coming with localhost should not be a problem as the add-in is locally hosted.

**Comment by shr9227** [comment]
Hi @exextoc ,
Yes I tried that but no luck. I created new icons in the same dimensions that the old one was and put them in the asset folder
The strange thing is when I change the URL's in the manifest I get the default icon: ![icon-32](https://user-images.githubusercontent.com/62870871/77881257-426f2680-7267-11ea-88da-f99666ed0014.PNG)
And when I replace the old icon with the new ones but keeping the same name of the icons I still get the  ![icon-32](https://user-images.githubusercontent.com/62870871/77989561-cd175a80-7327-11ea-876f-525275ba6e92.png) logo

**Comment by exextoc** [comment]
Share the link from where you created this add-in and also if possible what changes you are trying to make.

**Comment by shr9227** [comment]
Sorry I forgot to add the link: https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator

In the manifest file tring to change the icons:
<bt:Image id="Icon.16x16" DefaultValue="https://localhost:3000/assets**/powerapps-logo-16.png**"/>
<bt:Image id="Icon.32x32" DefaultValue="https://localhost:3000/assets/**powerapps-logo-32.png**"/>
<bt:Image id="Icon.80x80" DefaultValue="https://localhost:3000/assets**/powerapps-logo-80.png**"/>

**Comment by exextoc** [comment]
Looks like you are looking to change the default icon which you can change by changing the URL in tag <IconUrl .../>. I tried changing the URL's works fine for me.

**Comment by shr9227** [comment]
Itried there too, with no success :/
May be I need to do more the the command npm "run dev-server"?

**Comment by exextoc** [comment]
I don't think that should be a problem, instead of trying icon in different sizes, I just took one icon, put it in assets folder, change the manifest file with the new name. And that actually works.

**Comment by shr9227** [comment]
It worked! As you said - I just took one icon and then it worked...
Thanks :)

**Comment by Muneeraaaaa** [comment]
I have the same problem, and I added the icon to the asset file but it doesn't work. please help me what do I have to do.

**Comment by Muneeraaaaa** [comment]
please answer ASAP because we have a graduation project on this tomorrow
