### ISSUE TITLE
Office-JS Excel Desktop version Port Runtime Issue

### ISSUE THREAD

**Issue by Murugananths** [OfficeDev/office-js#1077]
Excel add-in Desktop version could not sideloaded Excel with below command through npm.
npm run start:desktop

## Expected Behavior
-------------------------
When trying to run below command the localhost should run and at the same time Excel should open while running the localhost server.
NPM Command : npm run watch followed  by npm run start:desktop.

## Current Behavior
----------------------

It was working initially but suddenly when doing the above said steps we are getting below issues.
**ISSUE:**
Debugging is being started...
App type: desktop
Enabled debugging for add-in 5dec6b5d-5796-4a45-9678-9359681a48a0. Debug method: 0
Starting the dev server... (webpack-dev-server --mode development)
ApplicationInsights:CorrelationIdManager [
  Error: connect ECONNREFUSED xx.xx.xx.xxx:xxx
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: 'xx.xx.xx.xxx',
    port: xxx
  }
]
Unable to start the dev server. Error: The dev server is not running on port 3000.
Sideloading the Office Add-in...
Debugging started.
events.js:187
## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by akrantz** [comment]
To use a different port for webpack-dev-server, in package.json change the value in the config.

"config": {
  "dev-server-port": 3000
}

**Comment by Murugananths** [comment]
Already i tried with the port 5003 and 8080....but the same issue getting..

**Comment by Murugananths** [comment]
Hi,
Any other findings required ?
