### ISSUE TITLE
When DisplayName string for Excel add-in is too long horizontal scroll bar appears, close button is moved and not interactable

### ISSUE THREAD

**Issue by Domen122** [OfficeDev/office-js#1078]
## Expected Behavior
Longer strings are wrapped in ellipsis and close button is working correctly

## Current Behavior
When we have long Addin name it isn't wrapped in any way which results in horizontal scroll bar. Also due to this addin close button is moved below the string and becomes not interactable

## Steps to Reproduce, or Live Example
1. Create manifest for addin with long <DisplayName/>
2. Add the addin to Excel ribbon
3. Click on the addin to open it
4. Notice the scrollbar
5. Try to close the addin by clicking on the "x" button

## Context
Allowing end-user to customize the manifest may lead to situation like this when he is unable to close the addin because the button is not interactable

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office 365 Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Online version 
* Operating System: Mac OS Catalina 10.15.3
* Browser (if using Office Online): Chrome

## Useful logs
![TooLongName](https://user-images.githubusercontent.com/24210935/78161727-32fa0400-7446-11ea-9109-117ef0aa5dbc.gif)

**Comment by ElizabethSamuel-MSFT** [comment]
@Domen122 Sorry that you hit this issue and thanks for reporting it.

@lumine2008 Can you take a look?

Thanks.

**Comment by lumine2008** [comment]
Thanks @ElizabethSamuel-MSFT , I think this should be UI areas, So let's assign to Lillian @lliu113

**Comment by lliu113** [comment]
@Domen122  - thanks for reporting this, sorry for the very belated response. I'm unable to repro this on my end - the long title introduces the horizontal scroll but the "x"/close button still works. Can you confirm whether you're still seeing this issue? 

Thanks!
