### ISSUE TITLE
getSharedPropertiesAsync encounters a 404 Bad Request

### ISSUE THREAD

**Issue by stejura-sfdc** [OfficeDev/office-js#1079]
While calling `Office.context.mailbox.item.getSharedPropertiesAsync` on a shared item, there's a 404 Bad Request error logged in the console. However, the shared properties data is retrieved successfully. 

## Expected Behavior
The `getSharedPropertiesAsync` call should not log a 404 Bad Request

## Current Behavior
The `getSharedPropertiesAsync` call logs a 404 Bad Request

## Steps to Reproduce, or Live Example
- Login to an OWA account
- Navigate to a shared mailbox (delegate mailbox) email
 - Open dev tools
- Execute `Office.context.mailbox.item.getSharedPropertiesAsync((props) => { console.log(props); });`

## Context
We're trying to retrieve shared property details on a shared mailbox (delegate mailbox) email. The shared properties are retrieved successfully, but there's an un-related 404 that is logged every time `getSharedPropertiesAsync` is executed.  

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: OfficeOnline (Outlook Web App)
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.10908.10000 (Office JS 1.8)
* Operating System: Mac OS X
* Browser (if using Office Online): Google Chrome 

## Useful logs

- [X] Console errors
[GetSharedPropertiesAsync (1).log](https://github.com/OfficeDev/office-js/files/4417984/GetSharedPropertiesAsync.1.log)

```
VM6:1 GET https://outlook.office.com/autodiscover/autodiscover.json/v1.0/mailappinfo@sfdcmsft.com?Protocol=REST 404
(anonymous) @ VM6:1
(anonymous) @ getSharedPropertiesApiMethod.ts:34
(anonymous) @ getAutoDiscoverRestUrl.ts:12
(anonymous) @ VM11:405
(anonymous) @ VM11:405
(anonymous) @ VM11:405
l @ VM11:405
(anonymous) @ getSharedPropertiesApiMethod.ts:26
cn @ executeApiMethod.ts:74
(anonymous) @ EndpointRegistrator.ts:169
invoke @ osfruntime.js:2003
A @ osfruntime.js:1565
I @ osfruntime.js:1556
setInterval (async)
M @ osfruntime.js:1693
sse-hooks.js:1 Got shared properies OSF.DDA.AsyncResult {value: {…}, status: "succeeded"}
VM6:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=AWT-Web-JS-1.8.5&x-apikey=a387cfcf60114a43a7699f9fbb49289e-9bceb9fe-1c06-460f-96c5-6a0b247358bc-7238&client-time-epoch-millis=1584635606980&time-delta-to-apply-millis=-18101 403 (All records were throttled.)
(anonymous) @ VM6:1
sendPOST @ vendors~aria-webjs-sdk_4b9dd84a1de46dedeffb.js:1
e._sendRequest @ vendors~aria-webjs-sdk_4b9dd84a1de46dedeffb.js:1
e.sendQueuedRequests @ vendors~aria-webjs-sdk_4b9dd84a1de46dedeffb.js:1
e.sendEventsForPriorityAndAbove @ vendors~aria-webjs-sdk_4b9dd84a1de46dedeffb.js:1
e._batchAndSendEvents @ vendors~aria-webjs-sdk_4b9dd84a1de46dedeffb.js:1
(anonymous) @ vendors~aria-webjs-sdk_4b9dd84a1de46dedeffb.js:1
setTimeout (async)
e.scheduleTimer @ vendors~aria-webjs-sdk_4b9dd84a1de46dedeffb.js:1
e.sendEvent @ vendors~aria-webjs-sdk_4b9dd84a1de46dedeffb.js:1
e._sendEvent @ vendors~aria-webjs-sdk_4b9dd84a1de46dedeffb.js:1
e._logEvent @ vendors~aria-webjs-sdk_4b9dd84a1de46dedeffb.js:1
e.logEvent @ vendors~aria-webjs-sdk_4b9dd84a1de46dedeffb.js:1
(anonymous) @ vendors~aria-webjs-sdk_4b9dd84a1de46dedeffb.js:1
e.flush @ vendors~aria-webjs-sdk_4b9dd84a1de46dedeffb.js:1
(anonymous) @ vendors~aria-webjs-sdk_4b9dd84a1de46dedeffb.js:1
```
- [X] Screenshots
![image (3)](https://user-images.githubusercontent.com/53920805/78193484-844ac900-742f-11ea-9866-0c35bf8f6c68.png)

**Comment by exextoc** [comment]
We are not able to repro the issue at our end. Is the issue consistent for you?

**Comment by stejura-sfdc** [comment]
@exextoc Yes, I can consistently reproduce the issue. FWIW, I can only see this on a shared mailbox (delegate mailbox) email

**Comment by exextoc** [comment]
> @exextoc Yes, I can consistently reproduce the issue. FWIW, I can only see this on a shared mailbox (delegate mailbox) email

Since we cannot repro this issue at our end still - will it be possible for you to provide us with a test account so that we may try there?

**Comment by stejura-sfdc** [comment]
@exextoc Yes, I can send you details for a test account. What's a good way for me to share the credentials?

**Comment by exextoc** [comment]
Hey @stejura-sfdc , sorry for the delay. Could you please share your test account details at AdeleV@M365x834167.OnMicrosoft.com ?

**Comment by exextoc** [comment]
> Hey @stejura-sfdc , sorry for the delay. Could you please share your test account details at [AdeleV@M365x834167.OnMicrosoft.com](mailto:AdeleV@M365x834167.OnMicrosoft.com) ?

**Comment by exextoc** [comment]
Hey @stejura-sfdc , Are you still facing the issue? Could you please share your test account details at AdeleV@M365x834167.OnMicrosoft.com ?
