### ISSUE TITLE
Sheet Unprotect/Protect - race condition/performance issues during Co-Authoring scenario

### ISSUE THREAD

**Issue by rameshbc** [OfficeDev/office-js#108]
We have an excel file with multiple protected sheets in the office365 environment.  In the sheet tables, most of the column cells are locked to avoid user editing the values. (formula, cell value, format).  Few columns where the cells are unlocked, the user can enter/change the values which in turn update the protected cell values. 

We are using OfficeJs API to insert new rows and/or change the values of the locked cells. We are using the following steps

1.  Unprotect the sheet.
2.  Adding rows or updating the cell values.
3.  Protect the sheet.

## Expected Behavior
Unprotect / Protect should not slow down the performance.

## Current Behavior
1.  On a Co-Authoring scenario, the unprotect and protect calls are failing when multiple user sessions perform the same operation due to the race condition.
2.  Performance of these Unprotect, protect and updating values API calls are very slow in any multi-user collaboration scenario.

## Steps to Reproduce, or Live Example

- Create an Excel sheet which should be protected.
- Create a table AccountAnalysis table inside the sheet with columns and( unlock the cells from columns E2:J500 and O2:O500)

```
$("#apply-mapping").click(applyMapping);

var sheetName = 'Sheet1'
var tableName = 'Table1'
var startRow =  2;
var lockExclusionRange=  ['E2:J500', 'O2:O500'];
var startColumn = 'A';

var tableRecords;
var tableRecordsModified;

async function applyMapping() {
    console.log('Apply mapping started!');

    // get table rows from AA
    await getTableRows(sheetName, tableName);
    console.log(tableRecords.length);

    // unprotect the sheet
    toggleSheetProtection(false, sheetName, tableName, startRow, lockExclusionRange);

    // Add some random rows
    await AddRandomRows(sheetName, tableName);

    //protect the sheet back.
    await toggleSheetProtection(true,sheetName, tableName, startRow, lockExclusionRange);
}

// Getting table rows
async function getTableRows(sheetName, tableName) {
    let rows = [];
    let table;
    await Excel.run(async(ctx) =>{
        table = ctx.workbook.tables.getItem(tableName).rows.load(['index','values']);
        await ctx.sync();
        
        if (table !== null && table.items !== null) {
            for (let i = 0; i < table.items.length; i++) {
              let row = {
                id: i,
                values: table.items[i].values
              };
              rows.push(row);
            }
        }
  
        tableRecords = rows;
       });
}

// sheet protection 
async function toggleSheetProtection(isToProtect, sheetName, tableName, startRow, lockExclusionRange) {
    let sheet;
    let table;
    await Excel.run(async(ctx) =>{
        sheet = ctx.workbook.worksheets.getItem(sheetName);
        table = ctx.workbook.tables.getItem(tableName)
        table.rows.load('count');
        sheet.protection.load();

        await ctx.sync();

       console.log(`toggleSheetProtection() tableName:${tableName} isToProtect:${isToProtect} sheet.protection.protected:${sheet.protection.protected}`);

        if (isToProtect && !sheet.protection.protected) {
            let extendedLockExclusionRange = [];

            if (lockExclusionRange) {
              for (let exclusionRangeValue of lockExclusionRange) {
                extendedLockExclusionRange.push(`${exclusionRangeValue}${startRow + table.rows.count}`);
              }
            }
            for (let extendedExclusionRangeValue of extendedLockExclusionRange) {
              sheet.getRange(extendedExclusionRangeValue).format.protection.locked = false;
            }
            sheet.protection.protect(this.excelConfig.protectionOptions);
          } else if (!isToProtect && sheet.protection.protected) {
            sheet.protection.unprotect();
          }

          await ctx.sync();
    });
}

async function AddRandomRows(sheetName, tableName){
    // Get top 10 rows and insert append with different random id for testing
    let newRows = [];

    console.log(tableRecords.length);

    for(let i=0; i< tableRecords.length;i++)
    {
       if (i<10) {
           newRows.push(tableRecords[i].values[0]);
        }
        else{
            break;
        }
    }
    //Append the rows to excel table.
    await Excel.run(async(ctx) =>{
        let tableRows = ctx.workbook.tables.getItem(tableName).rows;
         tableRows.add(null, newRows);
    });
}
```

## Context
It is impacting the performance of the application and user experience is very poor. OfficeJs provides API for Unprotection and Protection, Add/update rows separately and we are combining them to handle our scenario. Looking forward to having an API to handle this scenario ( combining all these operations with one API call) specifically for handling locked cells while updating it.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Office online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows 10
* Browser (if using Office Online): IE/Chrome

**Comment by JuaneloJuanelo** [comment]
@rameshbc  thanks for raising this issue. 
In order to be more effective helping you, we need a sample workbook for this. Can you please share a Workbook (free of PII of course) and also a script lab sample to repro this issue?

that will help us big time when investigating. 

thanks!

**Comment by JuaneloJuanelo** [comment]
@tutieu to follow up.

**Comment by lumine2008** [comment]
Hello @rameshbc, would you please share us your workbook for us to repro this issue? thanks

**Comment by betheman** [comment]
Is there any way to password encrypt an excel using office js.

**Comment by lumine2008** [comment]
Sorry @betheman , we don't provide password encrypt at API level due to encrypt workbook cannot be opened in excel online.

**Comment by betheman** [comment]
@lumine2008 is there any way we can protect **excel data** using office js.I just need only for desktop version.

**Comment by lumine2008** [comment]
You could use sheet.protection.protect to protect the sheet

**Comment by betheman** [comment]
Hi,

I already know this but the main issue is with the security of data. The
client does not want excel to open even in read-only mode.

**Comment by lumine2008** [comment]
thanks, therefore i am closing this issue, please open a new issue or feature ask accordingly
