### ISSUE TITLE
Error in Outlook Add-in after deploying to office 365 add-ins

### ISSUE THREAD

**Issue by shr9227** [OfficeDev/office-js#1080]
Hi all,

I have question about how to deploy simple add-in I created, that is a button that open web site

I built it with Sideloading and it work perfectly with my Outlook, now I need to publish it to all of my organization.

So I built VS project and connected it to Azure Web App and publish the solution, changed all the URL's to the Azure site and checked that the files are accessible anonymously. with this article: https://docs.microsoft.com/en-us/office/dev/add-ins/publish/host-an-office-add-in-on-microsoft-azure

I upload the manifest to Office 365, after couple of hours I saw the button on my Outlook but when I click on it I get an error:

![AddinError](https://user-images.githubusercontent.com/62870871/78243173-f54fb680-74eb-11ea-85f7-c2548de2f940.PNG)

"We're sorry, we couldn't access {0}. Make sure you have a network connection. If the problem continues, please try again late.

Can anyone help me with this case?

Thanks :)

**Comment by exextoc** [comment]
Can you share your manifest so that we can test it at our end.

**Comment by shr9227** [comment]
sure :)
[https://icl-outlook-addin.azurewebsites.net/OutlookWebAddIn1.xml](url)

I placed it also in Azure Web App

Thanks,

**Comment by shr9227** [comment]
I think I found the problem, I will check again and tell you what was wrong :)

**Comment by shr9227** [comment]
Hi All,
Sorry for delay answer, my problem was that I have broken link to the html command.
Now the solution work perfectly on the Outlook web (open Link to another web page) but not on the Outlook desktop(in the desktop is just saying:
_"{Solution Name} is working on your {Button Name} request"_
![OutlookAddinError](https://user-images.githubusercontent.com/62870871/78467670-a25a4700-7717-11ea-972a-c323d2713c15.PNG)

Here is the Manifest:
[Manifest.xml.txt](https://github.com/OfficeDev/office-js/files/4433184/Manifest.xml.txt)
Command.html:
https://sahartest2.azurewebsites.net/command/commands.html
Command.js:
https://sahartest2.azurewebsites.net/command/commands.js


Thanks,

**Comment by shr9227** [comment]
Hii,
I fount the answer to the problem:
OOTB in the command JS was this code on the beginning:
`Office.onReady(() => {
 // If needed, Office.js is ready to be called
});`
When I dig to IE console I found error that IE11 doesn't know the syntax, so I changed it to this:
`Office.onReady(function(){
  // If needed, Office.js is ready to be called
});`

and it worked :)
