### ISSUE TITLE
[Outlook] Office.context.mailbox.item.body.prependAsync() prepends multiline text in reverse order (OWA)

### ISSUE THREAD

**Issue by amegan** [OfficeDev/office-js#1082]
When I call `prependAsync()` API with the following ways, the inserted text appears in reverse order in the message body.  

```
Office.context.mailbox.item.body.prependAsync(
  "line 1<br/>line 2<br/>line 3", 
  {coercionType: Office.CoercionType.Html});
```

```
Office.context.mailbox.item.body.prependAsync(
  "<HTML><BODY>line 1<br/>line 2<br/>line 3<br/></BODY></HTML>", 
  {coercionType: Office.CoercionType.Html});
```

## Expected Behavior
The text should be inserted as 

line 1
line 2
line 3

## Current Behavior
The text is inserted as

line 3
line 2
line 1

in the message body.  I see this behavior only on OWA. 

## Steps to Reproduce, or Live Example
* Link to live example:  https://prlbg.csb.app/manifest.xml

Install debug add-in from above manifest then click the "Run" button to evaluate the script.
Or just run above `prependAsync()` code in dev console of any Office.js plugin context.

## Context
We provide the functionality to insert snippet HTML from the plugin using prependAsync() API. This feature works most of the times but we see this issue with certain HTML like above.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]:  Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number:  
* Operating System: Mac OS v10.15 / Windows 10
* Browser (if using Office Online): Chrome v80, IE11 11.1098.17763.0, Edge 44.17763.831.0, Firefox 74.

## Useful logs

![image](https://user-images.githubusercontent.com/90184/78194961-5d8e9180-7433-11ea-9714-19cc7f82256b.png)l‘«

**Comment by exextoc** [comment]
We are able to repro this bug. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by v-danmun** [comment]
Hello team, I'm from MS Dynamics CRM support. I have a customer having this exact issue. Is there any ETA for the resolution on this case that I can provide the customer?

**Comment by exextoc** [comment]
Thank you for your patience.  We have fixed the bug and the fix should be available soon.

**Comment by amegan** [comment]
I verified the fix is available to my testing account.  Thanks for the help.
