### ISSUE TITLE
Office.context.mailbox.item.addFileAttachmentAsync fails to attach files by URI in Outlook 2013 (Outlook 2016/2019/O365 fine)

### ISSUE THREAD

**Issue by CameronDwyer** [OfficeDev/office-js#1085]
## Expected Behavior
After obtaining the download URL of a SharePoint file from the Graph API https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0 (using the @microsoft.graph.downloadUrl property of the DriveItem), I expect to be able to use that URL to attach the file to a new email message being compose by using Office.context.mailbox.item.addFileAttachmentAsync in Outlook 2013 Windows Desktop.

Example format of the download URL returned by the call to Graph API:
![image](https://user-images.githubusercontent.com/16345690/78657630-676d3480-790c-11ea-8d3f-d053054aba52.png)

## Current Behavior
The above technique works for Outlook 2016/2019/O365/OWA but fails in Outlook 2013 without providing an error.

## Steps to Reproduce, or Live Example
Make a call to the Graph API to get the downloadUrl property of a DriveItem

Make a call from an Outlook 2013 add-in using Office.context.mailbox.item.addFileAttachmentAsync and the downloadUrl (it fails to attach the file)

Make the same call from an Outlook 2016/2019/O365/OWA host (it attaches the file as expected)

## Context
This is preventing us being able to attach files from SharePoint/OneDrive to email in Outlook 2013 Desktop. I am aware of the alternate method addFileAttachmentFromBase64 but this isn't available in Outlook 2013 as it was introduced in requirement set 1.8. Having the bug fixed for addFileAttachmentAsync would be my preference over making addFileAttachmentFromBase64 available for Outlook 2013. In all other hosts where we had both approaches available we chose addFileAttachmentAsync as it was much more suited to the requirement.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook 2013
* Office version number: 15.0.5172.1000
* Operating System: Problem occurs on both Windows 8.1 & Windows 10
* Browser (if using Office Online): N/A

### Outlook Desktop O365 (where the addFileAttachmentAsync is working)
Here's what the traffic looks like in Fiddler when the Outlook add-in calls addFileAttachmentAsync  in Outlook Desktop O365 (that does not have the problem).

1. Add-in makes call to Graph API to get the download URL (this comes back successfully)
![image](https://user-images.githubusercontent.com/16345690/78657936-d3e83380-790c-11ea-9c3a-bc6851d1f703.png)

2. Add-in calls addFileAttachmentAsync passing the downloadFile URL > then Outlook makes the CORS OPTIONS request.
![image](https://user-images.githubusercontent.com/16345690/78658178-2de8f900-790d-11ea-8dda-d759efa32e72.png)

3. Outlook then makes the call to GET the file and the attachment appears on the email as expected
![image](https://user-images.githubusercontent.com/16345690/78658217-3c371500-790d-11ea-9a5f-004908f4c3f8.png)

### Outlook Desktop 2013 (where the addFileAttachmentAsync is failing)
1. Add-in makes call to Graph API to get the download URL (this comes back successfully)
![image](https://user-images.githubusercontent.com/16345690/78658285-55d85c80-790d-11ea-8ef1-82d07721c240.png)

2. Add-in calls addFileAttachmentAsync passing the downloadFile URL > then Outlook makes the CORS OPTIONS request. This request fails with status code 401 (where the successful scenario above responded with a 405) and no further attempt is made by Outlook 2013 to request the file and the attachment process fails.
![image](https://user-images.githubusercontent.com/16345690/78658346-68eb2c80-790d-11ea-8108-c3ec9bff8fd6.png)

### Troubleshooting the cause
The issue seems to be in the CORS request generated by Outlook 2013 that results in the 401 response. I can use Fiddler to intercept the 401 response and modify it to have a status of 405 (same as what happens in Outlook Desktop 365).
![image](https://user-images.githubusercontent.com/16345690/78658603-b23b7c00-790d-11ea-8ed6-bfaeb9a40273.png)

When I do this and pass the response back to Outlook 2013 it continues to make the call to download the file and attaches the file as expected.
![image](https://user-images.githubusercontent.com/16345690/78658634-bff10180-790d-11ea-8e14-d01f3e1399a5.png)

![image](https://user-images.githubusercontent.com/16345690/78658646-c54e4c00-790d-11ea-84c7-d610bc5a9065.png)

**Comment by exextoc** [comment]
Thank you for the detailed post and taking the time to provide thorough logs. The API Office.context.mailbox.item.addFileAttachmentAsync is only intended to work with anonymous URLs. Additionally, Outlook 2013 is currently in extended support and is only fixed for security issues, so any non-security fixes will not be patched to Outlook 2013.

**Comment by CameronDwyer** [comment]
I understand your position on Outlook 2013 and not changing its behaviour. Clarification on those OneDrive URLs - I would consider them be anonymous access. The access key is a URL parameter so the calling code (Outlook host) doesn't need to do anything from an authorisation point of view other than request the given URL (the URL can be used in an InPrivate window for example). Can you confirm that this is a supported scenario?
