### ISSUE TITLE
[Excel] Border formatting issue using CellPropertiesLoadOptions / setCellProperties 

### ISSUE THREAD

**Issue by FelipeCostaGualberto** [OfficeDev/office-js#1087]
I'm trying to copy the borders format from a range and paste to another range using `Excel.CellPropertiesLoadOptions` to load properties and then `Range.setCellProperties` to set the properties, but the border formatting is being set incorrectly.
I don't know if the issue is being caused when _loading_ the properties or when _setting_ them.

## Expected Behavior
I expected the borders formatting in the destination range to be pasted identical as it is in the source range.

## Current Behavior
Part of borders' formatting are copied, but a lot of undesired diagonals black borders are also set.

## Steps to Reproduce, or Live Example
Refer to this ScriptLab code. Just paste it and it is possible to observe the behavior:

	(async function run() {
	  await Excel.run(async (context) => {
		const sheet = context.workbook.worksheets.getActiveWorksheet();
		const sourceRange = sheet.getRange("B1:C2");
		let options: Excel.CellPropertiesLoadOptions = {
		  format: {
			borders: {
			  weight: true,
			  tintAndShade: true,
			  color: true
			}
		  }
		};
		var sourceProperties = sourceRange.getCellProperties(options);

		await context.sync();

		let destinationRange = sourceRange.getOffsetRange(10, 0);
		destinationRange.setCellProperties(sourceProperties.value);

		await context.sync();
	  });
	}());

## Context
I want to store formulas and formatting in a database by reading the entire worksheet formatting (small worksheets), persist, and load later to the user.

## Your Environment
* Platform: PC desktop
* Host: Excel
* Office version number: Office 365 version 2004
* Operating System: Windows

## Useful logs
I got no errors.
![border](https://user-images.githubusercontent.com/12619088/78746194-96030380-793c-11ea-9989-533222ff2fee.png)

**Comment by MandytMSFT** [comment]
I can repro this issue from my side, BUG 4080917 is fired for internal track

**Comment by lumine2008** [comment]
Thanks @FelipeCostaGualberto for reporting this issue, our team has started the investigation. we will let you know once we have progress on this issue.

**Comment by lumine2008** [comment]
We are still in the investigation, meanwhile, there is a workaround for you to unblock your scenario, you could use `range.copyFrom() `API, here is the sample code:

```
async function run() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    const sourceRange = sheet.getRange("B2:C3");
    const destRange = sheet.getRange("E2:F3");
 
    destRange.copyFrom(sourceRange, Excel.RangeCopyType.formats);
    
    await context.sync();
 
  });
}
```

**Comment by ghost** [comment]
hi 
do you have a solution for the above problem ?
I am expriencing a similar problem when trying to copy paste manually from a table that has been filled by code written in officejs , and the borders are not copied ,only the data...
i would appreciate if you could join here apiece of code that configure the table while being created by the code to include 'all borders' so when copying from it, the borders would be also copied
many thanks!
