### ISSUE TITLE
Outlook contextual addin doesnt show for non breaking spaces in mac

### ISSUE THREAD

**Issue by jive-tamaskuzdi** [OfficeDev/office-js#1088]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I have an outlook contextual addin activating for regex results. The results can contain spaces, but it breaks when it contains a non breaking space. 

## Expected Behavior
I expect the regex result to be highlighted and the contextual addin to be activated when i click the highlighted text.

## Current Behavior
- Outlook mac application: text is highlighted but addin does not activate when i click on it

## Steps to Reproduce, or Live Example
Addin code to activate the extension with:
```
 <ExtensionPoint xsi:type="DetectedEntity">
              <Label resid="contextLabel" />
              <SourceLocation resid="detectedPhoneNumbersUrl" />
              <Rule xsi:type="RuleCollection" Mode="And">
                <Rule xsi:type="RuleCollection" Mode="Or">
                  <Rule xsi:type="ItemIs" ItemType="Message" />
                  <Rule xsi:type="ItemIs" ItemType="Appointment" />
                </Rule>
                <Rule xsi:type="ItemHasRegularExpressionMatch" RegExName="MyResult" RegExValue="some\stext" PropertyName="BodyAsPlaintext"/>
              </Rule>
            </ExtensionPoint>
```

I have copied the text from a page that contains `some&nbsp;text` in html into a mail, result in copiable format:
some text 

## Context
It prevents making an outlook addin that highlights phonenumbers in signatures containing non-breaking-space.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: ___Mac___
* Host [Excel, Word, PowerPoint, etc.]: ___Outlook___
* Office version number: ___16.35 (20030802)___
* Operating System: ____OSX Catalina__
* Browser (if using Office Online): ______

**Comment by exextoc** [comment]
Hello, we cannot repro this issue. Will it be possible for you to share the manifest for this?

**Comment by jive-tamaskuzdi** [comment]
@exextoc while i prepare a repo, i can tell that it only happens on mac with the Outlook app

**Comment by jive-tamaskuzdi** [comment]
@exextoc please find a reproduction code here with explanation in readme:
https://github.com/jive-tamaskuzdi/outlook-nbsp-repro

**Comment by exextoc** [comment]
Hey @jive-tamaskuzdi ,

Thanks for the precise reproduction steps. We are able to reproduce this issue, and we have put it on our backlog. Unfortunately we have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: Office:4103449
