### ISSUE TITLE
Handler not called: Office.context.mailbox.item.addHandlerAsync(Office.EventType.RecipientsChanged

### ISSUE THREAD

**Issue by KyNorthstar** [OfficeDev/office-js#1092]
## Expected Behavior
The handler which is passed to the `addHandlerAsync` function when the event type is `Office.EventType.RecipientsChanged` should be called.

## Current Behavior
The handler is not called when the recipients change

## Steps to Reproduce, or Live Example

With the following snippet:

```typescript
Office.onReady(() => {
    const email = Office.context.mailbox.item
    email.body.prependAsync(` ${Office.context.requirements.isSetSupported('Mailbox', '1.7')} `)

    email.body.prependAsync(` ${email.addHandlerAsync} `)
    email.addHandlerAsync(Office.EventType.RecipientsChanged, function () {
        email.body.prependAsync(` RecipientsChanged: ${arguments} `)
    })
})
```

When the add-in loads, the following is prepended to the email body:

>  function (){var c=OSF._OfficeAppFactory.getHostFacade()[OSF.DDA.DispIdHost.Methods.AddEventHandler];c(arguments,b,a,e)}  true 

but after recipients are changed in the "To", "Cc", and "Bcc" fields, the body is not modified.

## Context

In order for our add-in to function correctly, it needs to be notified when the recipients list changes.

The documentation says that [this feature requires API 1.7](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item#events), and that [Outlook for Mac in Office 365 supports API 1.7](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#outlook-client-support):
![image](https://user-images.githubusercontent.com/10189808/78834909-87543500-79ac-11ea-94b9-23a536b5b465.png)
![image](https://user-images.githubusercontent.com/10189808/78834043-2a0bb400-79ab-11ea-81c4-2d1c0833ef5c.png)

## Your Environment

* Platform: Mac
* Host: Outlook
* Office version number: 16.35 (20030802)
* Operating System: macOS 10.15.4

![image](https://user-images.githubusercontent.com/10189808/78835297-29741d00-79ad-11ea-9b74-51fed6373f97.png)

**Comment by exextoc** [comment]
Hello, we cannot repro this issue. Will it be possible for you to share the manifest for this addin?

**Comment by KyNorthstar** [comment]
@exextoc No problem! It's mostly unmodified from the one Yeoman generated:

[manifest.xml](https://github.com/OfficeDev/office-js/files/4469927/manifest.xml.zip)

**Comment by exextoc** [comment]
Hey @BenLeggiero ,

RecipientsChanged event is valid for Message Compose and Appointment Compose scenarios, while the manifest you have shared only uses MessageRead. Did you mean to use it on a compose surface?
