### ISSUE TITLE
context.document.getSelection() can't get Chinese characters

### ISSUE THREAD

**Issue by pinetreeps** [OfficeDev/office-js#1093]
I am do it in macOS
when I use sample by Script Lab
context.document.getSelection() can't get Chinese characters

[在此处输入反馈]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bd71647a-75de-038e-536a-7e56dd48ef3c
* Version Independent ID: a8bc56eb-0948-1ae0-0654-6b751ee9435f
* Content: [Word.Document class - Office Add-ins](https://docs.microsoft.com/zh-cn/javascript/api/word/word.document?view=word-js-preview#getselection--)
* Content Source: [docs/docs-ref-autogen/word/word/word.document.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.document.yml)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by MandytMSFT** [comment]
I tried this API works well on Word web and desktop. Transfer to the right owner who owns Word MAC

**Comment by lliu113** [comment]
@pinetreeps - thanks for your question! We're investigating this internally, will update when we know more. 

Internal bug code: 4084575

**Comment by pinetreeps** [comment]
> @pinetreeps - thanks for your question! We're investigating this internally, will update when we know more.
> 
> Internal bug code: 4084575

I tried it on win10 ,it's works well.

**Comment by nicheungMSFT** [comment]
@pinetreeps Hello, could you please clarify more on the steps you took to get this error on Mac?

**Comment by pinetreeps** [comment]
> @pinetreeps Hello, could you please clarify more on the steps you took to get this error on Mac?
it's my step1
![image](https://user-images.githubusercontent.com/30180070/79553308-de55ba80-80ce-11ea-8669-5da9436e534d.png)

it's my step2
![image](https://user-images.githubusercontent.com/30180070/79553433-0fce8600-80cf-11ea-8ac7-97c12a771db7.png)

it's my step3
![image](https://user-images.githubusercontent.com/30180070/79553627-591ed580-80cf-11ea-83a7-4f0fdacb946d.png)
I can't see any thing in the console window, I need copy to Sublime.

it's my copy text:
![image](https://user-images.githubusercontent.com/30180070/79553984-f417af80-80cf-11ea-983f-b182067ecf16.png)

Great, I can see it today, Did you upgrade?
But to be honest, it is indeed sometimes invisible, and can't see it in console windows

**Comment by lliu113** [comment]
@pinetreeps - this is marked as resolved internally, so I'm going to go ahead and close this issue. Please reactivate if you have any additional questions, thanks!
