### ISSUE TITLE
insertText not working for Word add-in on Mac desktop

### ISSUE THREAD

**Issue by pb-jeff-oneill** [OfficeDev/office-js#1094]
This bug report is based off this [SO post](https://stackoverflow.com/questions/60995349/replace-text-of-current-paragraph-in-ms-word-office-js-add-in).

The goal is to get the text of the current paragraph of a Word doc, look for an instance of the word "foo" and replace it with the word "bar".   Here is the code:

```
Office.onReady().then(function() {
  $(document).ready(function () {
      Office.context.document.addHandlerAsync(
        'documentSelectionChanged',
        updateText);
  });
});

function updateText() {
  var range, foo_range, par;
  Word.run(function (context) {
    range = context.document.getSelection();
    range.paragraphs.load('items');
    return context.sync()
    .then(function() {
      par = range.paragraphs.items[0];
      console.log(par.text); // THIS WORKS!
      foo_range = par.search('foo');
      foo_range.load('items');
    })
    .then(context.sync)
    .then(function() {
      console.log(foo_range.items[0].text); // THIS WORKS!
      foo_range.items[0].insertText('bar', 'Replace');
      return context.sync();
    });
  });
}
```

On my Mac with Office 365, everything is working except `insertText`.  The text of the Word document does not change.  There are no errors.

Rick Kirkham stated that code did work for him for Office 365 on Windows.

**Comment by weshi** [comment]
@pb-jeff-oneill I tried your code above on my Word for Mac, and it works as expected. When I enter foo, it's replaced with bar.

Could you share the version/build information of your Word for Mac ? (menu item: Word -> About Microsoft Word).

The version I tried is: 
<img width=300 src="https://user-images.githubusercontent.com/11494417/79236339-68b7d780-7e9f-11ea-9b3a-5fba13e7b694.png"/>

**Comment by pb-jeff-oneill** [comment]
I've got a more recent version:

<img width="209" alt="Screen Shot 2020-04-14 at 11 34 54 AM" src="https://user-images.githubusercontent.com/55557751/79243716-01b90500-7e44-11ea-8079-9b0559c2b092.png">

I just tried again and it still isn't working.

**Comment by weshi** [comment]
Could you try to use Script Lab from the Office Store, and Import below code from gist and try again?

https://gist.github.com/weshi/7f7e1c177dacf92a500dc629491fc206

<img width="300" src="https://user-images.githubusercontent.com/11494417/79289244-579cb400-7efb-11ea-9b7b-75b6cb9647fd.png">

<img width="300" src="https://user-images.githubusercontent.com/11494417/79289360-9c284f80-7efb-11ea-87ef-da3de817afb8.png">

**Comment by pb-jeff-oneill** [comment]
That does work!  Thank you for providing that.

However, that snippet uses async/await which is not supported by IE11 ([caniuse](https://caniuse.com/#search=async)) and some Word versions are still running add-ins using IE11.

Is it possible to get this working without async/await?

**Comment by weshi** [comment]
I figured out that the root cause is because of the following code:

Office.onReady().then(function() {
  $(document).ready(function () {
      Office.context.document.addHandlerAsync(
        'documentSelectionChanged',
        updateText);
  });
});


Change it to below:

Office.onReady().then(function() {
//  $(document).ready(function () {
      Office.context.document.addHandlerAsync(
        'documentSelectionChanged',
        updateText);
//  });
});

(Remove the commented line.)

Please try and see if it works.

**Comment by pb-jeff-oneill** [comment]
I made that change to my code but it didn't fix the problem.  Same as before.  I'm not sure if I missed it before, but now `insertText ` causes this error in the console:

![Screen Shot 2020-04-16 at 5 38 44 PM](https://user-images.githubusercontent.com/55557751/79509336-50fc6280-8009-11ea-8f1d-0c880615efcb.png)

I created a new Gist that puts my `updateText` function into the Gist you previously provided.  I also removed all the async/awaits to make it closer to my code:
https://gist.github.com/pb-jeff-oneill/e37863b154ec199483080eaa6bf65855

This Gist **does** work.  I don't understand why my Gist works but my code outside of Script Lab doesn't work.

Here is my complete Javascript that is not working:
```
Office.onReady().then(function() {
  Office.context.document.addHandlerAsync(
    'documentSelectionChanged',
    updateText);
});

function updateText() {
  var range, foo_range, par;
  Word.run(function (context) {
    range = context.document.getSelection();
    range.paragraphs.load('items');
    return context.sync()
    .then(function () {
      par = range.paragraphs.items[0];
      console.log(par.text);
      foo_range = par.search('foo');
      foo_range.load('items');
      console.log('1');
    })
    .then(context.sync)
    .then(function () {
      console.log('2a');
      console.log(foo_range);
      console.log(foo_range.items.length);
      if (foo_range.items.length) {
        console.log(foo_range.items[0].text);
        foo_range.items[0].insertText('bar', 'Replace');
      }
      console.log('2b');
      return context.sync();
    });
  })
}
```

**Comment by weshi** [comment]
Could you try the following code and let me know what's the output in the console?

```
function updateText() {
  Word.run(function (context) {
      console.log("Started")
      var range = context.document.getSelection();
      range.paragraphs.load("items");
      return context.sync().then(function () {
          console.log("First Sync done.");
          var par = range.paragraphs.items[0];
          console.log(par.text);
          var foo_range = par.search('foo');
          foo_range.load('items');
          return context.sync().then(function () {
              console.log("Second sync done.");
              console.log(foo_range.items[0].text);
              foo_range.items[0].insertText('bar', 'Replace');
              return context.sync().then(function () {
                  console.log("Third sync done.");
                  console.log("Replaced foo with bar");
              });
          });
      });
  }).catch(function (error) {
      console.log(JSON.stringify(error));
  })
}
```

**Comment by pb-jeff-oneill** [comment]
Here is the console log showing the error.  The screenshot shows the events after typing "fo" and also after "foo".

![Screen Shot 2020-04-17 at 9 51 35 AM](https://user-images.githubusercontent.com/55557751/79576312-0f16ff00-8091-11ea-8ecb-f6e2dbd0dd52.png)

**Comment by weshi** [comment]
One last try please. Please add a return keyword before the Word.run. If this still does not work, could you please try other API instead of insertText, and let's see if this is something specific to insertText or just the way that you call Word.run without return it. 

I can hold a Teams meeting with you to discuss more if needed. Please suggest a time that works for you.

```
function updateText() {
  return Word.run(function (context) {
      console.log("Started")
      var range = context.document.getSelection();
      range.paragraphs.load("items");
      return context.sync().then(function () {
          console.log("First Sync done.");
          var par = range.paragraphs.items[0];
          console.log(par.text);
          var foo_range = par.search('foo');
          foo_range.load('items');
          return context.sync().then(function () {
              console.log("Second sync done.");
              console.log(foo_range.items[0].text);
              foo_range.items[0].insertText('bar', 'Replace');
              return context.sync().then(function () {
                  console.log("Third sync done.");
                  console.log("Replaced foo with bar");
              });
          });
      });
  }).catch(function (error) {
      console.log(JSON.stringify(error));
  })
}
```

**Comment by pb-jeff-oneill** [comment]
Still doesn't work.  I tried a few things but nothing worked: removing 'Replace', using  `Word.InsertLocation.end` instead of 'Replace', `insertParagraph` instead of `insertText`.

How about 9am New York time on Monday for a meeting?

**Comment by weshi** [comment]
If other API does not work either, then this seems not specific to insertText. If you directly call any of these APIs, does it work?

At the meantime, since it works in Script Lab but not in this add-in, can I try your add-in directly? (you can share me the manifest.xml file if possible). 

I will setup a meeting at 9AM your time to discuss more. I didn't find your contact information in your profile. Please send me your contact email to weshi@microsoft.com and I'll send out the invitation. Thanks.

**Comment by weshi** [comment]
I updated my Word to the latest, and tried again. Still cannot reproduce it. 

<img width="300" src="https://user-images.githubusercontent.com/11494417/79593543-3364f100-810e-11ea-879d-c74cbf52afcb.png" />


<img width="300" src="https://user-images.githubusercontent.com/11494417/79593170-a5890600-810d-11ea-8681-2b6ca925a3e5.png" />

**Comment by weshi** [comment]
After our offline follow-up, the root cause has been identified, and it was because the add-in has Read only permission, therefore the call to write APIs failed.

The fix is to update the manifest file, and change below line:
```
<Permissions>ReadAllDocument</Permissions>
```
to this:
```
<Permissions>ReadWriteDocument</Permissions>
```

And then the add-in can work as expected.

However, It's worth checking the code to make sure all error conditions are handled so that it can catch and show the right errors:

In my test, it does show the expected error message if the permission is not sufficient:
{"name":"RichApi.Error","code":"AccessDenied","traceMessages":[],"innerError":null,"debugInfo":{"code":"AccessDenied","message":"You don't have sufficient permissions for this action."}}

I'm glad that the add-in can now call the APIs as expected. Any further question, please feel free to contact me.

**Comment by pb-jeff-oneill** [comment]
Thanks for the help.  Much appreciated!

**Comment by mynameismon** [comment]
Funnily, I am encountering this exact issue on Word 2019 (Windows). Word Version: 
```Microsoft® Word 2019 MSO (Version 2111 Build 16.0.14609.20000) 64-bit ```

The code can be found here: https://gist.github.com/mynameismon/ef7ec86842c7eb2f3290c9af3d09132d

To reproduce:
- Create a word document with two separate content controls
- Add some words in one, and leave the other one empty
- Select the empty CC and click the first button ("Get Content Control for Word Count")
- Select the other CC (with words), and click the second button
-  Click "Update Word Count"

Everything works fine until the insertion of text.
