### ISSUE TITLE
Office Addin - Unable to fetch document GUID or any other unique DriveItem property from Office.context 

### ISSUE THREAD

**Issue by nat-ser** [OfficeDev/office-js#1098]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

An Office Add-in is opened in a parent document with the full web url like `https://mydomain.xyz/:w:/r/personal/personal_com/_layouts/15/Doc.aspx?sourcedoc={GUID}&file=AddinTest.docx&action=default&mobileredirect=true`

In the context of the Add-in iframe,  I am unable to fetch any type of unique identifier for the parent document. `Office.context.document.url` returns only a partial url like `https://mydomain.xyz/personal/personal_com/Documents/AddinTest.docx` and the solutions that [this](https://stackoverflow.com/questions/42847480/how-to-get-the-sharepoint-o365-document-id-from-an-office-add-in) post suggests do not work. 

Please see https://github.com/OfficeDev/office-js/issues/831 as well.

## Expected Behavior
There is some prescribed Document API interface to get the GUID of the document that the add in is currently open in, context currently offers no such API

## Current Behavior/ Steps to Reproduce, or Live Example
![Screen Shot 2020-04-13 at 15 03 38](https://user-images.githubusercontent.com/8990017/79151561-a8e06280-7d98-11ea-91e7-085768cbede4.png)

None of these worked:

- JSON.parse(window.name) 
- Office.context.document.url
- Passing GUID into the addin manifest
- `getFilePropertiesAsync` 

Is there a way for me to identify the parent document from within the Addin iframe?

**Comment by MandytMSFT** [comment]
@nat-ser  Currently we don't have API can fetch document ID. Can i know why you need fetch this ID ?

**Comment by nat-ser** [comment]
Thanks for looking into this @MandytMSFT 

The core functionality of our Addin is to display info about a particular piece of content in our web app that is tied to a document in Office 365.
 
For ex:  A user uses the file picker SDK embedded in our app to link documentA to the chosen sharepoint file FileB. Within the addin, we want to show a preview of that documentA when the user opens FileB in Office 365.

We need some GUID that's accessible on the Sharepoint document. It is the only way to associate a Microsoft Office 365 document with an object in our db.

**Comment by dgrayling** [comment]
We also have a use case for this property.

We want to provide links to our users to documents associated with their group. Download links are not suitable because we expect our users to collaborate within their group and passing static documents around does not meet thier needs.

So we want either this sourceDoc id (As seems to be provided in the VB api https://docs.microsoft.com/en-us/office/vba/api/access.objectframe.sourcedoc)  so that we can construct that url for them...

or the actual web link of the document itself.

**Comment by soodvaibhav** [comment]
@nat-ser Did you find any solution to this? Our use case very similar to what you described?
