### ISSUE TITLE
Cannot deploy OWA add-in in the admin portal as file or URL

### ISSUE THREAD

**Issue by sarea** [OfficeDev/office-js#1099]
Hi there,
[This issue](https://github.com/OfficeDev/office-js/issues/853) is fixed but when I try to deploy the add-in (v1.8) from the admin portal as file or URL, I got this error:
```
No Supported Office Products. There are no platforms which fulfil the requirements specified in the manifest. The most common reasons for this failure are issues in the Requirements section. Please review the manifest and try again.
Correlation ID: cf770ed5-41a6-418a-8043-a92b22f69845
```
That error did not occur when deploying the same manifest with v1.7 or less

This issue is occurring only when deploying the add-in through the admin portal, not when adding a new add-in as a user.
Thanks

**Comment by exextoc** [comment]
The fix for this issue is complete and is currently rolling out. Once the update rolls out, you will can re-submit your add-in via the Partner Center and the update will take effect on your add-in.
