### ISSUE TITLE
“AccessDenied” error on WorksheetCollection.onActivated event on Excel 2019 Desktop

### ISSUE THREAD

**Issue by lumine2008** [OfficeDev/office-js#1103]
My customer uses "WorksheetCollection.onActivated" event to update the information when the user changes the worksheet. my customer found that on some versions of the office while trying to set this event, the add-in is getting error "AccessDenied".

```
async function registerOnActivateHandler() {
  await Excel.run(async (context) => {
    let sheets = context.workbook.worksheets;
    sheets.onActivated.add(onActivate);

    await context.sync();
    console.log("A handler has been registered for the OnActivate event.");
  });
}

```
The code works fine on Excel Online and Mac, my customer does see the "Access Denied" issue on Excel 2019 Desktop version 16.0.10356.2006

The interesting thing is: onAdded/onDeactivated event works fine on Excel 2019 desktop

Error screenshot:
![image](https://user-images.githubusercontent.com/26398035/79293488-79e7ff00-7f06-11ea-9f0b-22e10ff0a7da.png)

**Comment by weshi** [comment]
The fix is in rolling out stage.

**Comment by lumine2008** [comment]
Closing this bug, please re-open if you still repro this issue
