### ISSUE TITLE
Outlook Online, all browsers, setSelectedDataAsync produces incorrect formatting

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1104]
In an Outlook add-in for compose mode, we use the Office JS API to fill in email fields. The setSelectedDataAsync method inserts HTML with incorrect markup.

## Expected Behavior
The setSelectedDataAsync method should work as expected.

## Current Behavior
The setSelectedDataAsync method ignores markup and produces "stairs".

## Steps to Reproduce, or Live Example
Create a new email in Outlook Online using, for example, the Chrome or Edge browser and execute the code below. NOTE, the newly created email shall be completely empty, if you use signature, please turn it off.

`const data = '<p>List 1:</p>' +`
`'<ul>' +`
`'  <li>A</li>' +`
`'</ul>' +`
`'<p>List 2:</p>' +`
`'<ol>' +`
`'  <li>B</li>' +`
`'</ol>' +`
`'<p>Indented 1:</p>' +`
`'<p style="margin-left:30px;">This text is intended</p>' +`
`'<p>Indented 2:</p>' +`
`'<p style="margin-left:30px;">This text is also intended</p>';`
`Office.context.mailbox.item.body.setSelectedDataAsync(data, { coercionType: Office.CoercionType.Html }, (asyncResult) => { });`

I have attached 2 screenshots with the results, the first one is from Chrome, the other from Edge.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows 10, Mac OS Catalina
* Browser (if using Office Online): Chrome Version 81.0.4044.92 (Official Build) (64-bit) and Microsoft Edge 44.18362.449.0 on Windows, Safari Version 13.0.5 (15608.5.11) on Mac

## Useful logs
- [ ] Screenshots
![ol-online-chrome](https://user-images.githubusercontent.com/28924916/79453054-cbb98380-7ff1-11ea-887b-67015a40450b.png)
![ol-online-edge](https://user-images.githubusercontent.com/28924916/79453081-d3792800-7ff1-11ea-842e-363f7c6e10da.png)

**Comment by exextoc** [comment]
Hello, thanks for reporting this issue. We could repro this and added this issue to our backlog. We, unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
@DmitryKostochko  Could you please confirm if you are still facing this issue?

**Comment by DmitryKostochko** [comment]
I have just tested the code with Edge, Chrome and IE, but couldn't reproduce the issue. The bug seems to be fixed, thank you!

**Comment by exextoc** [comment]
@DmitryKostochko  Thanks for confirming.
