### ISSUE TITLE
Problems with using the microsoft graph document preview functionality from outlook addin

### ISSUE THREAD

**Issue by sjkp** [OfficeDev/office-js#1105]
We are building an outlook addin that uses the MS graph API. We are trying to use the drive item preview endpoint (https://docs.microsoft.com/en-us/onedrive/developer/rest-api/api/driveitem_preview?view=odsp-graph-online) But it fails, specifically when used in the addin pane. We have already posted the issues on 
https://github.com/OneDrive/onedrive-api-docs/issues/1232 

But since it is not getting any attention, I will cross post it here, as I'm not sure which team should be responsible for a fix (both teams can fix it as far as I can tell).

**Comment by exextoc** [comment]
Hey @sjkp,

As I see that the onedrive team has already acknowledged this issue, can we close it on this thread?
