### ISSUE TITLE
how to publish microsoft word add-ins on my local system

### ISSUE THREAD

**Issue by Bradrajkumar** [OfficeDev/office-js#1106]
hi all,

i have created an add-ins to add in my word desktop application and i want it to be published locally.
is there any way which i can achieve the same. whenever i open my word document my add-ins will be abailable.
is it mandatory to publish my application on O365 add-ins section ??

please provide me the detailed information regarding this.

**Comment by mscharlock** [comment]
Transferring this issue to the office-js repo.

**Comment by danielgwilson** [comment]
Perhaps this is what you're looking for?

https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins

You can sideload an Add-in which will allow it to be used locally for any document. Other users won't be able to see or use your add-in.

**Comment by Bradrajkumar** [comment]
suppose i am achieving this using sideload process, if i am working in an organization and want that addin to be available on every system locally. if this is possible then in how many ways i can achieve the same.

**Comment by danielgwilson** [comment]
Ah—you're probably looking for [this](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish-task-pane-and-content-add-ins-to-an-add-in-catalog) then; you can deploy your manifest to a SharePoint catalog and allow users within your organization to insert the Add-in.

Alternatively, you can also use [centralized deployment](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/centralized-deployment)—this approach is a bit more robust, but also more regulated. It requires a few more hoops, but end users can have the Add-in installed automatically without having to add it to each app themselves.

**Comment by Bradrajkumar** [comment]
Hi @danielgwilson,
I'm unable to find my add-in after i share it to self refering [this](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins), The shared section is available in the add-in section but not the manifest file which i shared, after going through the requirements i'm using a organizational 0365 account (proplus), yet facing this issue, please help me for the same. ![add-in](https://user-images.githubusercontent.com/34365788/79893788-2ef84b00-8422-11ea-8e29-4a91770821fc.png)
