### ISSUE TITLE
drag and copy not firing table.onChanged event in latest excel version 2002

### ISSUE THREAD

**Issue by leonidasthelab** [OfficeDev/office-js#1110]
## Expected Behavior
In Excel version 2002, When dragging a cell vertically down to copy across a range of cells below, regardless of if there is filtering on the columns present and hidden rows due to the filtering, the data changed event for the table gets fired and we can capture the event with an event handler. Copying by dragging works with column filtering.

## Current Behavior
In Excel Version 2002, if there is column filtering present and hidden rows due to the filtering, when dragging a cell vertically down to copy across a range of cells below, the data changed event for the table DOES NOT get fired and we are unable to capture the event with an event handler, but when dragging from left to right the data changed event is fired and captured. We need to be able to capture the data changed event in order to do custom validation on the values that were changed etc. regardless of whether the user has filtered data.

This unexpected behavior is seen in Excel version 2002. 

Works fine in 1908 which leads us to think it is a bug.

## Steps to Reproduce, or Live Example
Get Excel version 2002. In add in, after doing the basics of creating a table, adding data changed handlers, and seeing content on the sheet, you need to manually filter on a column first (filter the data in such a way that there are hidden rows in between). Modify a value and then drag that value down to copy to below cells. See that the event handler does not fire on vertical drag and copy, but event handler fires on horizontal drag and copy. It seems that if you do a vertical drag to copy values to cells below, when there is filtering and hidden rows in between, the data changed event does not fire. This is inconsistent behavior and only seen on version 2002. We do not see this issue in version 1908.

## Context

This issue in version 2002 is inconsistent with behavior in version 1908. We have offered this vertical drag and copy functionality to users who have 1908 and this behavior needs to be there when they upgrade to version 2002.

Please provide a solution so that behaviors are consistent and backward compatible across versions.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel Add in (based on IE)
* Office version number: 2002
* Operating System: Win 10
* Browser (if using Office Online):

**Comment by lumine2008** [comment]
Hi @leonidasthelab, thanks for your report for this issue. I have tested this event on following versions:
- version 2004 (build 12730.20150), 
- version 2005 
- version 2003

This issue is not repro on above versions. 
Therefore, here are some thing we could do:
1) Would you please share me your gist as well?therefore I can have a try in my side. 
2) Would you please try my gist and see if you can repro in your side? 
https://gist.github.com/lumine2008/82cbc5463fb5fa9a6431cb5ebd529ac0

**Comment by lumine2008** [comment]
Could you please share us the screenshot of your excel version? like this? we would like to see if we can get the exactly same version to validate in our side

![image](https://user-images.githubusercontent.com/26398035/79852220-f7c17400-83f8-11ea-8e48-763559dc1cd8.png)

**Comment by leonidasthelab** [comment]
Hi @lumine2008, i realized i left out a key detail, I will update the problem description. 

After doing the basics of creating a table, adding data changed handlers, and seeing content on the sheet, you need to manually filter on a column first (filter the data in such a way that there are hidden rows in between) before you do a vertical drag to copy over the values. It seems that if you do a vertical drag to copy values to cells below, when there is filtering and hidden rows in between, the data changed event does not fire. We have seen this behavior in both 2002 and 2003 versions. Please try this test case out. Below screen shot of Excel version.

![excelbuild](https://user-images.githubusercontent.com/12532186/79908307-dd26d500-83cf-11ea-8a3f-fc13afa0f2dc.PNG)

**Comment by lumine2008** [comment]
I just tried your tips, but no luck, could you please try my gist in your end, and see if you can repro in your side?
https://gist.github.com/lumine2008/82cbc5463fb5fa9a6431cb5ebd529ac0

**Comment by leonidasthelab** [comment]
@lumine2008 

I created a new Excel AddIn project in Visual Studio 2017, and modified the .js to try and replicate your gist and see if the issue is still there. I am doing very basic things:

1) Create tables with some data, as you have done, sales and return
2) Add table changed handler to the tables

In Excel version 2002, I am still able to reproduce the issue. I manually filter the data so that there are hidden rows in between (**this part is KEY**), I update the first cell and see that this fires the data changed handler, but when I drag this value down to copy to cells below, the data changed handler does not fire even though I can see that the values in the cells have changed.

Please try it out again with the same Excel version and build. I have attached an image showing how I filtered the data. See that I filtered the column Qtr1 on the values (5000, 12000, 225) and that rows 2,4, and 6 are shown, while rows 3 and 5 are hidden. Change 5000 to any number, hover on the lower right corner of that cell until the plus sign appears and then drag that number down to row 6. We are seeing that although the values of rows 4 and 6 are updated to that of row 2, the data changed event handler does not fire.

![sample](https://user-images.githubusercontent.com/12532186/80145067-7129a580-8564-11ea-9f08-e96fee321580.PNG)

The code is very simple, see the basic gist containing the html and .js files: https://gist.github.com/leonidasthelab/fd72d5f295d006b42c576c6d43ed62be

Appreciate you taking the time to help!

**Comment by lumine2008** [comment]
Thanks @leonidasthelab , we can now repro this issue now, bug 4120787 was created to track this issue. we will let you know once this bug was fixed. thanks for your support.

**Comment by leonidasthelab** [comment]
@lumine2008 great!! Do you have a estimated time frame for the bug fix that you can provide? We are looking to roll up the upgrade to version 2002+ and would be awesome if this is functional. Thanks!

**Comment by lumine2008** [comment]
Thanks @leonidasthelab , We are still working on an investigation on the root cause, we will let you know once we know more about the time frame. thanks for your support

**Comment by leonidasthelab** [comment]
@lumine2008 any updates for us? Thanks!

**Comment by leonidasthelab** [comment]
@lumine2008 @MandytMSFT @jeremy-msft any updates for us? Thanks!

**Comment by lumine2008** [comment]
Thanks @leonidasthelab , this issue was resolved and it is rolling out. if you are on the monthly channel (version 2009 build 13221.20038), you can verify the fix.
