### ISSUE TITLE
Office.js is loaded outside of Excel when the html page in an iframe

### ISSUE THREAD

**Issue by lukchen** [OfficeDev/office-js#1112]
First I found the Excel object is undefined, then I debugged 'o15apptofilemappingtable.js' and found the window.external.GetContext is undefined, which means the office.js is loaded outside Excel at all.

## Expected Behavior

Office.js should be loaded in Excel.

## Current Behavior
"Warning: Office.js is loaded outside of Office client" and "Excel" is undefined

## Steps to Reproduce, or Live Example
1. specify manifext.xml and open excel
2. open my taskpane, Excel is undefined

live url: http://elichen.matlabonlineserver-b.mwcloudtest.com/

you can login using username: excel   password: matlab

## Your Environment
* PC
* Excel
* Office version 16
* Win10

## Useful logs
I put log at o15apptofilemappingtable.js and found the window.external.GetContext is undefined:

`if (window.external && typeof window.external.GetContext !=='undefined') {
				context=OSF.DDA._OsfControlContext=window.external.GetContext();
			} else {
				initializeAsBrowser();
				return;
			}`

![image](https://user-images.githubusercontent.com/26646767/79936602-de82ec80-8425-11ea-83a6-3af8d9c7a35e.png)

I posted on stackoverflow:  https://stackoverflow.com/questions/61356400/office-js-is-loaded-outside-even-inside-excel-application

**Comment by lumine2008** [comment]
Thanks @lukchen , I have replied in StackOverflow, looks like that CDN reference is incorrect. could you please refers to 

`<script src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js" type="text/javascript"></script>`

**Comment by lukchen** [comment]
> Thanks @lukchen , I have replied in StackOverflow, looks like that CDN reference is incorrect. could you please refers to
> 
> `<script src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js" type="text/javascript"></script>`

Hi,

I changed to refer that CDN script but still having same issue

**Comment by lumine2008** [comment]
Here is my validation result 
![image](https://user-images.githubusercontent.com/26398035/79993386-48af9600-84e7-11ea-9e5b-2104ffe1ab37.png)

Here is my code: 
```

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js" type="text/javascript"></script>    </head>
    <body>
    
    <p id="output">hello</p>
    
    </body>
        <script type="text/javascript">
            Office.onReady(info => {
                if (info.host === Office.HostType.Excel) {
                    document.getElementById("output").innerHTML = "I am in Excel";
                } else {
                    document.getElementById("output").innerHTML = "out of excel";
                }
            });
        </script>
    </html>
```
Would you please try it in your side?

**Comment by lukchen** [comment]
> Here is my validation result
> ![image](https://user-images.githubusercontent.com/26398035/79993386-48af9600-84e7-11ea-9e5b-2104ffe1ab37.png)
> 
> Here is my code:
> 
> ```
> 
> <!DOCTYPE html>
> <html>
> <head>
>     <meta charset="UTF-8" />
>     <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
>     <meta name="viewport" content="width=device-width, initial-scale=1">
>     <!DOCTYPE html>
>     <html>
>     <head>
>         <meta charset="UTF-8" />
>         <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
>         <meta name="viewport" content="width=device-width, initial-scale=1">
>         <script src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js" type="text/javascript"></script>    </head>
>     <body>
>     
>     <p id="output">hello</p>
>     
>     </body>
>         <script type="text/javascript">
>             Office.onReady(info => {
>                 if (info.host === Office.HostType.Excel) {
>                     document.getElementById("output").innerHTML = "I am in Excel";
>                 } else {
>                     document.getElementById("output").innerHTML = "out of excel";
>                 }
>             });
>         </script>
>     </html>
> ```
> 
> Would you please try it in your side?

tried, still same issue:

**Comment by lukchen** [comment]
![image](https://user-images.githubusercontent.com/26646767/79994438-f8531c80-8483-11ea-9469-51e826a06b20.png)

**Comment by lukchen** [comment]
Are you testing with my web page link? If you do you might can see same issue

**Comment by lukchen** [comment]
Could it relates to iframe?

![image](https://user-images.githubusercontent.com/26646767/80000972-d5c50180-848b-11ea-9592-034cfb71da4d.png)

**Comment by lukchen** [comment]
I tested my page as static content on a node server and it works perfect. So my guess is the html and officejs library are all fine, the problem is how I host this page. And this iframe blocked officjs to get Excel enviornment context. What do you think?

**Comment by lukchen** [comment]
![image](https://user-images.githubusercontent.com/26646767/80013515-ffd2ef80-849c-11ea-8a4b-159d4e406ded.png)

Ok i think I can confirm this...
I put the iframe and test it on node server again, it's out of Excel again.
**So is the iframe stuff a known limitation or bug?**

**Comment by lukchen** [comment]
@lumine2008 Hi, can you confirm is this a bug or known issue?
