### ISSUE TITLE
Formulas for range not working correctly

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#1113]
I'm working on a complex add-in for a very specific set of requirements, and unfortunately I can't share much of the code. A lot of things happen before and after the point where the add-in inserts these formulas, so it's very possible that the cause of this error is not the formulas themselves. Either way, any help with this issue is greatly appreciated. I originally posted this question to Stackoverflow [here](https://stackoverflow.com/questions/61325990/formulas-for-range-not-applying-correctly).

I'm trying to hyperlink two rows, so that clicking on any cell on one leads you to the other and vice versa. As a test, I'm first trying to insert links between rows 11 and 100 with a completely hardcoded formula to avoid issues with variables. Here's what I'm trying to do:

```
let row10 = full_range.getRow(10)
    let formulas = new Array( 18 ).fill('=HYPERLINK("[Grouping test file.xlsx]\'WEKA 18 rec2\'!A100"; "test test test")')
    row10.formulas = [ formulas ]
```

Where full_range is the result of `worksheet.getUsedRange()`, 18 is the amount of columns on the sheet, and the filename sheet name and addresses are hardcoded. I have tried some variations of the Hyperlink formula but haven't had much success. 

## Expected Behavior
Each cell would have a hyperlink to cell B of the target row.

## Current Behavior
The add-in crashes and restarts. In cells A and B of the source row, the value has been replaced with the formula. When inspecting these cells, Excel recognizes them as hyperlinks, since it displays the formula on a tooltip below the cell, highlighting the different parts of the formula as I move the cursor.

![hyperlink_issue](https://user-images.githubusercontent.com/64004654/79976685-53453d80-849d-11ea-8ef7-4c063f6bd559.png)

Copying and pasting the content of these cells to another does create a hyperlink. 

## Steps to Reproduce, or Live Example
* Additional details:
 Like I said before, I can't share much of the code. However, I'll try to explain what it does:

First, it looks through each row and decides if it should stay in the sheet or not, as well as identifying rows that need to be linked. After this, the whole content of the sheet is deleted and replaced with the filtered rows and corresponding numberFormats. Context syncs so it can work with updated row indices, then does the hyperlinking (in the case of this example, only from row 11 to row 100). Another context.sync then the following code executes:

`    const col_A = sheet_range.getColumn(0)
    const col_B = sheet_range.getColumn(1)

    col_A.format.columnWidth = 5
    col_B.format.columnWidth = 400

    sheet.showGridlines = false
    sheet_range.format.autofitRows()
`
This portion of the code doesn't get to run though, as the add-in crashes and reloads during the previous sync (I think).

## Context
I'm writing this add-in for my employer. The input and output are very specific, but the gist of it is, removing unnecessary rows and applying some formatting (colors, etc). 

## Your Environment
I'm working on Win10 with WSL for all command line-related functions, and VSCode as the text editor. I'm working with OfficeJS CDN, Office version is 2003 (Build 12624.20466), no Office online support.

**Comment by lumine2008** [comment]
Thanks @mariana-tuma for your post,
we would like to learn about the crash, it seems we are not be able to repro in our side. would you please share a bit more information? gist in scriptlab would be super helpful
 ![image](https://user-images.githubusercontent.com/26398035/80091821-52430780-8594-11ea-9e66-7c883cb3dd64.png)

**Comment by ghost** [comment]
I'll try to reproduce it and and share the gist then.
