### ISSUE TITLE
Application Crashed on Loading

### ISSUE THREAD

**Issue by razor1299** [OfficeDev/office-js#1115]
Using office-js Excel API, Excel crashes and restarts when i loading excel with my Add- in

## Expected Behavior
![image](https://user-images.githubusercontent.com/64157718/80017292-61498d00-84a2-11ea-80e0-6b5bb3e1591c.png)

## Current Behavior
Random error when i open my Excel Add- in. 

## Useful logs
No more log or error Dom
![image](https://user-images.githubusercontent.com/64157718/80029775-3f0d3a80-84b5-11ea-9046-eb6187fae1b5.png)

**Comment by jeremy-msft** [comment]
Based on the log information provided, this appears to be a question about COM/VSTO add-ins rather than Office.js based add-ins.
