### ISSUE TITLE
Are there APIs available now to read/write custom properties inPowerPoint online using Office.js

### ISSUE THREAD

**Issue by ukalhapu** [OfficeDev/office-js#1117]
Are there APIs available now to read/write custom properties in PowerPoint online using Office.js ?

## Expected Behavior
We want to read/write custom properties in PowerPoint online.
Our Add-in highly depends on custom properties. Currently it support Word & Excel online only.
We want to support PowerPoint as early as possible .
Do you suggest alternative ?

**Comment by jeremy-msft** [comment]
This is not possible today. We track Office Add-in feature requests on our  [UserVoice page](https://officespdev.uservoice.com/). 

It looks like the feature you want has been requested by others already. Please upvote the [existing request](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/39001942-allow-powerpoint-add-in-to-read-custom-properties). Feature requests on UserVoice are considered when we go through our planning process. 

Thanks, 
Office Platform team
