### ISSUE TITLE
iOS Outlook Add-in not respecting Set-Cookies header for external sites in Dialog

### ISSUE THREAD

**Issue by westconference** [OfficeDev/office-js#1123]
Outlook Web Add-in in iOS Outlook app does not seem to set cookies for external pages opened in Dialogs that use the Set-Cookie header.

## Expected Behavior
External page that Add-in Dialog navigates to should be able to set cookies based on the Set-Cookie header and later retrieve those set cookies if redirected to another page on that same external domain.

## Current Behavior
Works as expected on desktop but not on iOS. Cookie does not appear to have been set by the header.

## Steps to Reproduce, or Live Example
(Below steps use placeholder URLs, I do not have a live example I can expose).
1. Launch dialog from add-in (dialog URL should be same domain as add-in).
2. Have dialog page redirect to an external site that passes back a Set-Cookie header on load.
3. That external page should redirect to another page on its external domain and try to access the cookie that should have been set.
4. Should see that on iOS the cookie will not have been set.

Add-in code should just be calling Office.context.ui.displayDialogAsync, then in the dialog redirecting to the non-add-in domain. That external domain should passes back Set-Cookie header, redirect to another page on same domain and try to read the cookie that should have been set.

## Context
I've an Outlook web add-in that uses the Office.js Dialog API to open a dialog that navigates to an external (i.e. not on my add-in domain) authentication landing page. When that page is loaded in the dialog it passes back a Set-Cookie header with a return URL value set to a page in my add-in, then redirects to a different external site to perform SAML authentication (whoever the user has configured as their SAML provider). When login completes the user is navigated to a completion page on the authentication landing domain, which is then expected to read the cookie that was initially set and redirect back to the add-in using the URL in the cookie.

This works fine on desktop platforms however when using the add-in through the Outlook IOS app I'm seeing that the Set-Cookies header does not seem to work as when the flow reaches the completion page there are no cookies present.

I cannot modify the behaviour of pages outside of my add-in.

The page I redirect to has X-Frame-Options set to sameorigin so I cannot load it in a hidden iFrame outside of the dialog.

This flow works on desktop Safari, Chrome, IE, Windows Outlook client, Mac Outlook client and was previously seen to work on iOS back in September 2019 indicating a change on the platform itself.

On the iOS device under Safari settings 'Prevent Cross-Site Tracking' and 'Block All Cookies' settings are both off.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: iOS 12.4.1.
* Host [Excel, Word, PowerPoint, etc.]: Outlook App 4.34.1
* Office version number: O365 Account, latest Outlook App.
* Operating System: iOS
* Browser (if using Office Online): N/A

## Useful logs

**Example Header not being respected on iOS**
```
Set-Cookie: ReturnURL=https://my-addin.com/finalize;Version=1;Path=/auth;Domain=auth-helper;Max-Age=86400;HttpOnly;Secure;SameSite=None
```

**Comment by exextoc** [comment]
We are following the same bug [here](https://ift.tt/35eqftJ) . If you have any questions you can add in comments on the mentioned post. Please let us know if it's not same issue.

**Comment by exextoc** [comment]
iOS upgrade fixes the issue.
Answer for the same question from different [forum](https://stackoverflow.com/a/61746995/7823505):
_"The iOS device was upgraded from OS 12.4.1 to 13.4.1 and this problem no longer occurs. So we're going to have to recommend users upgrade iOS as we haven't found any other way around this."_
