### ISSUE TITLE
Telemetry service not found causes add-in to not load on Excel for the web

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/office-js#1125]
After opening https://localhost:3000/ in Edge I get
![image](https://user-images.githubusercontent.com/25219229/80363781-01c5f580-8885-11ea-9930-3aef2a8b1b72.png)
After opening https://localhost:3000/taskpane.html in Edge I get the same
![image](https://user-images.githubusercontent.com/25219229/80364040-7e58d400-8885-11ea-8405-1ea44d4477c4.png)
After opening in Excel everything works
![image](https://user-images.githubusercontent.com/25219229/80364174-b9f39e00-8885-11ea-8a1e-5f453da262da.png)

Tried:
1. Installing certificate
![image](https://user-images.githubusercontent.com/25219229/80366389-7bf87900-8889-11ea-87d6-2fa655d13c2b.png)
2. Disabling AdBlock extension (only pausig AdBlock is not sufficient!)
![image](https://user-images.githubusercontent.com/25219229/80364687-9f6df480-8886-11ea-8a08-97dec7614a39.png)
3. Different example https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial but is not loading the body
![image](https://user-images.githubusercontent.com/25219229/80365338-b2cd8f80-8887-11ea-950c-886f80687782.png)

Could it be my excel version?
![image](https://user-images.githubusercontent.com/25219229/80365698-5028c380-8888-11ea-8836-5df67fc74807.png)

Not sure what I can try more. Followed the guide a couple of times now and keep getting the same result.

_Originally posted by @Rednas83 in https://github.com/OfficeDev/office-js-docs-pr/issues/720#issuecomment-619917740_

**Comment by Rick-Kirkham** [comment]
@AlexJerabek That telemetry service is only available to 1st party developers, that is, add-ins made by Microsoft itself. It should not affect the add-in and I believe it can be safely ignored. 

@Rednas83 You say that it only works in the task pane, not in the browser. This is normal. An add-in cannot work in a separate browser window. It needs the context of Office to initialize. In general, you should not be trying to open the add-in in a browser window.

**Comment by Rednas83** [comment]
@Rick-Kirkham Thanks for clearing it up. Looking at the guide this was not so clear at all.
![image](https://user-images.githubusercontent.com/25219229/80530222-fa900c00-8998-11ea-9c21-317deb1eb45f.png)
I posted some questions regarding the API on stackoverflow. Could you perhaps have a look?
https://stackoverflow.com/questions/61095118/is-excel-javascript-api-only-for-creating-add-ins

What I don't understand is why you would limit the API to be used in Excel only?

**Comment by Rednas83** [comment]
@Rick-Kirkham 
Is there a milestone when the telemetry service will be available for third party users?
Or will it be restricted to microsoft users only?

**Comment by Rick-Kirkham** [comment]
@Rednas83 I didn't see your Stack issue until just now because it wasn't tagged with `office-js`. That's the tag that I filter on. I'll take a look.

I don't think that that telemetry system is ever going to be available to 3rd party developers. I believe there are other telemetry services available for web apps that you can use. I think Azure has one.
