### ISSUE TITLE
outlook android mobile: loadCustomPropertiesAsync error

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#1129]
when i use [Outlook mobile add-in for an online-meeting provider](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting) guide to debug my add-in, i found the Office.context.mailbox.item.loadCustomPropertiesAsync api always failed.
even with your implement demo guide on this document:
this is my demo code:
```js
const newBody = '<br>' +
    '<a href="https://contoso.com/meeting?id=123456789" target="_blank">Join Contoso meeting</a>' +
    '<br><br>' +
    'Phone Dial-in: +1(123)456-7890' +
    '<br><br>' +
    'Meeting ID: 123 456 789' +
    '<br><br>' +
    'Want to test your video connection?' +
    '<br><br>' +
    '<a href="https://contoso.com/testmeeting" target="_blank">Join test meeting</a>' +
    '<br><br>';

var mailboxItem;

Office.onReady(function () {
    Office.context.mailbox.item.loadCustomPropertiesAsync((result) => {
        console.log("--mobile debug loadCustomPropertiesAsync: " + JSON.stringify(result));
    });
    mailboxItem = Office.context.mailbox.item;
    }
);

function updateBody(event, existingBody) {
  // Append new body to the existing body.
  mailboxItem.body.setAsync(existingBody + newBody,
      { asyncContext: event, coercionType: "html" },
      function (setBodyResult) {
          if (setBodyResult.status === Office.AsyncResultStatus.Succeeded) {
              setBodyResult.asyncContext.completed({ allowEvent: true });
          } else {
              console.error("Failed to set HTML body.");
              setBodyResult.asyncContext.completed({ allowEvent: false });
          }
      }
  );
}

function oneclickPrepareMeeting(event) {
    // Get HTML body from the client.
    mailboxItem.body.getAsync("html",
        { asyncContext: event },
        function (getBodyResult) {
            if (getBodyResult.status === Office.AsyncResultStatus.Succeeded) {
                updateBody(getBodyResult.asyncContext, getBodyResult.value);
            } else {
                console.error("Failed to get HTML body.");
                getBodyResult.asyncContext.completed({ allowEvent: false });
            }
        }
    );
}
```
and please notice this log:
**Office.context.mailbox.item.loadCustomPropertiesAsync((result) => {
        console.log("--mobile debug loadCustomPropertiesAsync: " + JSON.stringify(result));
    });**

it's output result:
```
{"status":"failed","error":{"name":"GenericResponseError","message":"An internal error has occurred.","code":9020}}
```
this will cause my add-in can't save Custom Properties(such as: meeting number) on the meeting event.

**Comment by hello-chenchen** [comment]
it seams have been fixed on outlook android version:4.1.73(200271) dogfood

**Comment by hello-chenchen** [comment]
have confirmed that it has been fixed on 4.1.73(200271) dogfood

**Comment by hello-chenchen** [comment]
due to another problem:https://github.com/OfficeDev/office-js/issues/1126, when i edit this meeting event, and click online-meeting button which status isn't right. It can't get corrent custom properties, only can get this result:(which i saved value have lost, but this is only happened on android. But other platform such as:OfficeOnline is fine.)
```
{"value":{"rawData":{}},"status":"succeeded"}
```

**Comment by hello-chenchen** [comment]
i think after fix https://github.com/OfficeDev/office-js/issues/1126, this problem will be no longer as a problem.

**Comment by mscharlock** [comment]
@hello-chenchen - Thanks for letting us know! I am going to close this issue as it sounds like this issue is resolved. If it's not and I've misunderstood, just let me know with a comment on this thread.
