### ISSUE TITLE
Outlook Online, addFileAttachmentAsync never completes

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1130]
In an Outlook add-in for compose mode, we use the Office JS API to fill in email fields. The addFileAttachmentAsync method never completes after refreshing the Outlook Online web page.

## Expected Behavior
The addFileAttachmentAsync method should complete with the succeeded or failed status.

## Current Behavior
The addFileAttachmentAsync method never completes. I waited for 30 minutes and got nothing.

## Steps to Reproduce, or Live Example
* Sign in to Outlook Online using, for example, the Chrome or Edge browser.
* Refresh the page, press Ctrl + F5.
* Create a new email and execute the code below.
`const options: Office.AsyncContextOptions & { isInline: boolean } = { isInline: false };`
`Office.context.mailbox.item.addFileAttachmentAsync('https://www.w3.org/TR/PNG/iso_8859-1.txt', 'iso_8859-1.txt', options,`
`  (result: Office.AsyncResult<string>) => {`
`    if (result.status === Office.AsyncResultStatus.Succeeded) {`
`      console.log('Succeeded');`
`    } else {`
`      console.log('Failed', result.error);`
`    }`
`  });`

* Additional details:
  1. Quite rarely the issue is not reproducible for the first time, please press Ctrl+F5 and try again.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows 10
* Browser (if using Office Online): Microsoft Edge 44.18362.449.0, Chrome 81.0.4044.122

**Comment by exextoc** [comment]
@DmitryKostochko we are unable to repro this at our end with the code snapshot shared by you. Can you try this sample code and see if this also fails:
/* Add file attachment */
var attachmentURL = "http://i.imgur.com/sRgTlGR.jpg";
Office.context.mailbox.item.addFileAttachmentAsync(attachmentURL, "squirrel.png",
 function callback(asyncResult) {
  if (asyncResult.status == "failed") {
   console.log("Action failed with error: " + asyncResult.error.message);
  } else {
   console.log("Attachment added with identifier:" + asyncResult.value);
  }
 }
);

**Comment by DmitryKostochko** [comment]
Thank you for a quick turnaround.
Yes, I can reproduce the issue with your code as well. I have made 5 attempts in each browser, Edge and Chrome. The 4th test in Edge and 2nd in Chrome were successful, all other failed.
Note, please refresh the Outlook Online page (Ctrl+F5) before clicking New Message!

**Comment by exextoc** [comment]
@DmitryKostochko Yes, I tried after refresh only. Are you executing the code in Office.initialize function? Can you try executing the code through developer window console after 1 minute or so. Just to confirm that the Office.context is initialized completely. You can right click on Add-in --> inspect --> console--> Execute the code mentioned above.

**Comment by DmitryKostochko** [comment]
>> Are you executing the code in Office.initialize function?

I don't execute the code in the Office.initialize function.

>> Can you try executing the code through developer window console after 1 minute or so.

Please have a look at the screenshot attached. In the console, I have highlighted the console.log() line from our Office.initialize function.
![Untitled](https://user-images.githubusercontent.com/28924916/80730310-18cd4780-8b12-11ea-9d03-35c17eec7cff.png)

Also, you can see how it looks like on our side - no attachment, no callback.

**Comment by DmitryKostochko** [comment]
Additional info: if I wait for > 2 min after opening my pane, the code seems to start working. Why are such huge delays required? As you can see from my screenshot, the Office.initialize and even Office.onReady functions are executed at add-in startup successfully.

**Comment by exextoc** [comment]
@DmitryKostochko  In the screenshot shared, the attached image is being shown as loading. Does the attachment complete at some point? Also, does this issue occur only when executing the code in Developer Window console or within Add-in code as well?

**Comment by DmitryKostochko** [comment]
>> In the screenshot shared, the attached image is being shown as loading. Does the attachment complete at some point?

As I mentioned earlier, it never completes.

>> Also, does this issue occur only when executing the code in Developer Window console or within Add-in code as well?

The issue occurs in both cases, when executing the code in console and when executing the code in the add-in with a button click.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding addFileAttachmentAsync API. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
Internal tracking id: OutlookWeb:84990

**Comment by ralphtheninja** [comment]
Any progress made on this yet? I'm also having problems with `Office.context.mailbox.item.addFileAttachmentAsync()`, however I get an internal error with code 5001. The `failed to attach file` is my `console.log()`, the rest is `console.log(result.error)` where `result` is the `AsyncResult` object.

NOTE that this is only on Mac desktop. It works just fine on Windows.

![image](https://user-images.githubusercontent.com/308049/119580162-2fe77300-bdc0-11eb-9950-57d402971e6e.png)

**Comment by ArjunSureshKumar92** [comment]
@exextoc  Having the exact same issue as [DmitryKostochko](https://github.com/DmitryKostochko). 

![image](https://user-images.githubusercontent.com/35875176/179281848-76fd546c-5514-4c46-a634-370417371f03.png)


The attachment uploads within seconds in outlook desktop. Never completes in OWA. There is no error.

Code 
function func1() {
    Office.context.mailbox.item.addFileAttachmentAsync(
        "<uri to png image>",
        "xyz.png",
        { asyncContext: null, isInline: false },
        function (asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Failed) {
                console.log("Failed to attach!!");
            } else {
                const attachmentID = asyncResult.value;
                console.log('ID of added attachment: ' + attachmentID);
            }
        });
}
