### ISSUE TITLE
notificationMessages.replaceAsync sometimes takes around 30 seconds to complete

### ISSUE THREAD

**Issue by dmitry-semenov** [OfficeDev/office-js#1131]
## Expected Behavior
`Office.context.mailbox.item.notificationMessages.replaceAsync` takes reasonable time to complete

## Current Behavior
`Office.context.mailbox.item.notificationMessages.replaceAsync` in rare cases can return it's callback after around 30 seconds. We're tracking the duration of functions that we call during the add-in command execution and reporting them when total execution time gets over 60 seconds. We found that changing the progress message is blocking our customers for this delay and we want to get it resolved.

## Steps to Reproduce, or Live Example
  1. Run `Office.context.mailbox.item.notificationMessages.replaceAsync` one by one and measure how long does it take to return a callback
We were not able to repro on our side, only a subset of customers reporting that as an issue.

## Context
We're showing progress messages for the add-in command that sends an email, to make troubleshooting of the whole process easier we're waiting for a callback from  `Office.context.mailbox.item.notificationMessages.replaceAsync`  before moving to the next step of the email processing.

## Your Environment
We got this from the bug reports for one of the affected user's account

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.11328.20480
* Operating System: Windows 10
* Browser (if using Office Online): IE 11.0.0

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by mscharlock** [comment]
@exextoc - Do you mind having a look at this issue? Thanks!

**Comment by kfmpchan** [comment]
We cannot reproduce this delay either. From your data, does the API succeed after the delay? One thing to note is that a modal dialog that is opened in Outlook (not necessarily related to addin) can block add-in APIs from executing.

**Comment by exextoc** [comment]
We cannot reproduce this delay either. From your data, does the API succeed after the delay? One thing to note is that a modal dialog that is opened in Outlook (not necessarily related to addin) can block add-in APIs from executing (until the dialog is closed). Could this explain your observation?

**Comment by dmitry-semenov** [comment]
> From your data, does the API succeed after the delay? 

Yes, it gets unstuck after some period of time. 
> One thing to note is that a modal dialog that is opened in Outlook (not necessarily related to addin) can block add-in APIs from executing (until the dialog is closed). Could this explain your observation?

This is possible. I checked few more cases and found breadcrumb examples where users experienced delays for 0, 10, and 29 seconds to get `replaceAsync` callback called for the same command execution. I suspect if a user continues working with the email client while email processing is in progress, something can trigger unrelated dialogs.

**Comment by exextoc** [comment]
Please let us know if there are more we can clarify with this issue.

**Comment by dmitry-semenov** [comment]
I'll re-open in case if I'll be able to get more information about the issue, thanks.
