### ISSUE TITLE
Question about Delivery date of  Version 2002 (Build 12527.20278) for Semi-Annual users

### ISSUE THREAD

**Issue by aburtsev1** [OfficeDev/office-js#1132]
Hello. 
Issue https://github.com/OfficeDev/office-js/issues/954 was fixed for Semi-Annual Targeted licenses but our Customers using the Semi-Annual version in most cases. Please clarify when we can expect Version 2002 (Build 12527.20278)  for Semi-Annual license type?  If there is any precise delivery date we can count on?

**Comment by sohailzafar** [comment]
Hi the release is available in the insiders channel. Will be available in Prod in July

**Comment by mscharlock** [comment]
@aburtsev1 - Does this answer your question? I don't think we can give an exact date of the release to production besides the month. I'm going to close this issue for now, but if you have additional questions, go ahead and comment on this thread and I will reopen it.

**Comment by aburtsev1** [comment]
@sohailzafar  @mscharlock  Thank you. Yes, we are waiting for it.
