### ISSUE TITLE
Outlook for Mac, addFileAttachmentAsync fails with Internal Error

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1133]
In an Outlook add-in for compose mode, we use the Office JS API to fill in email fields. The addFileAttachmentAsync method fails with Internal Error on Outlook for Mac.

## Expected Behavior
The addFileAttachmentAsync method should work correctly.

## Current Behavior
The addFileAttachmentAsync method fails with Internal Error.

## Steps to Reproduce, or Live Example
Create a new email in Outlook for Mac, execute the following code:

const url = 'https://www.swift.com/file/43346/download?token=Z4ELVyxz';
const name = 'bicdir2018_sample.txt';
const options: Office.AsyncContextOptions & { isInline: boolean } = {
isInline: false
};
Office.context.mailbox.item.addFileAttachmentAsync(
url,
name,
options,
(result: Office.AsyncResult<string>) => {
if (result.status === Office.AsyncResultStatus.Succeeded) {
console.log('Succeeded');
} else {
console.log(result.error); // {"name":"Internal Error","message":"An internal error has occurred.","code":5001}
}
});

* Additional details:
  1. The link to the TXT file is taken from the following page:
https://www.swift.com/taxonomy/term/15986
  2. It seems only Outlook for Mac is affected.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook for Mac
* Office version number: Microsoft Outlook for Mac Version 16.36.1 (20041900)
* Operating System: macOS Catalina 10.15.3
* Browser (if using Office Online): ______

**Comment by exextoc** [comment]
@DmitryKostochko We are able to repro the bug with the mentioned url.Thanks for reporting this issue. It has been put on our backlog. 
Does it repro with any other URL ?

**Comment by DmitryKostochko** [comment]
>> It has been put on our backlog.

Do you have any timeline for fixing this bug?

>> Does it repro with any other URL ?

The issue is easily reproducible with a link that redirects to a TXT file. It seems everything works fine with redirect links to Office documents, archives and images (png, jpg, etc.). I did not test binaries, sorry.

**Comment by exextoc** [comment]
Thank you for providing more details on the issue. Unfortunately, we have no timelines to share at this point.

**Comment by exextoc** [comment]
@DmitryKostochko We have fixed the bug and the fix should be available in latest builds.
