### ISSUE TITLE
Validated Excel addin manifest works in Excel locally but not in excel online

### ISSUE THREAD

**Issue by kMutagene** [OfficeDev/office-js#1135]
Link to [SO post](https://stackoverflow.com/questions/61519089/validated-excel-addin-manifest-works-in-excel-locally-but-not-in-excel-online?noredirect=1#comment108842563_61519089)
A manifest file that is valid by `office-addin-manifest validate` and works locally on my machine with excel does not work in Excel online. **It did work a few days ago** 

My addin is a webpage hosted on https://localhost:3000 and i have installed the office dev certs.

## Expected Behavior
Addin can sideload on Excel online just as on my machine

## Current Behavior

Excel online throws an error that says that the manifest is invalid

![image](https://user-images.githubusercontent.com/21338071/80788337-1b1eb880-8b89-11ea-8b50-ffbcf031f849.png)

## Steps to Reproduce, or Live Example

Start any type of webapp on https://localhost:3000 and use the manifest from the following gist:
https://gist.github.com/kMutagene/89e9e36a1462af5bb1a2b454453bc5a8

Additionally, here is the app i am working on in the context of this manifest : https://github.com/CSBiology/CSBAnnotatorAddIn

## Context
I mainly want to test the add in in excel online because none of the other suggested ways to get debugging info from the page itself didn't work for me, but i get the debug output from the page when i use the addin in excel online and press F12.

## Your Environment

* Platform: PC desktop, Office Online
* Host: Excel
* Office version number: 16.0.12624.20424
* Operating System: Windows 10 Pro 10.0.18363
* Browser (if using Office Online):
    I have the same error on all the browsers i have installed:
    - Chrome : 81.0.4044.129 (Official Build) (64-bit) (cohort: Stable)
    - Edge chromium preview: 83.0.478.18 (Official build) beta (64-bit)
    - Edge: 44.18362.449.0

## Useful logs
Validate output is included in the gist.

**Comment by kMutagene** [comment]
As a user in the SO post pointed out, there is the following tag in my manifest file:
`<FunctionFile resid="Commands.Url"/>`
While a resource with the id "Commands.Url" does not exist. I would however expect that to be catched by both Excel on my computer and `office-addin-manifest`.

**Comment by mscharlock** [comment]
@lumine2008 - Do you mind having a look at this issue? Thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@kMutagene If this is still an issue for you, do comment and we can reopen. You can also create a new issue.

Thanks.
