### ISSUE TITLE
Dialog-API for Office Add-in not sending back message

### ISSUE THREAD

**Issue by Gaurav1327** [OfficeDev/office-js#1137]
I have been developing an outlook plugin on production level but I am continuously facing issues for adding authentication. The Dialog API has been working if displayInFrame parameter is set to true. But when this parameter is not set to true, the dialog box opens but messageParent function is not working . Tried solving this issue for many days but problem is still persisting. Please somebody help me out.

I have been using Outlook.com for this and chrome browser. Checked out with all POPUP settings also. 
 @office-js @outlook-web-addins
@o365devx @exextoc

**Comment by exextoc** [comment]
@Gaurav1327 Can you confirm if the issue is same  as mentioned https://ift.tt/2YALRiH ? If so, you can track the same for further responses.
