### ISSUE TITLE
Firebase authentication using FirebaseUI is not working on an MS Word Addin. The same lines of code work fine if opened in a browser(Chrome). 

### ISSUE THREAD

**Issue by pulkitm404** [OfficeDev/office-js#1138]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am using the code provided in [https://firebase.google.com/docs/auth/web/firebaseui](url).
I would like to repeat that the same lines of code work fine if opened in a browser, but it fails to load in the addin.
I have added a screenshot of the  same taskpane.html file, left side is opened in a browser and the right side is in the addin window.

![Annotation 2020-05-02 152219](https://user-images.githubusercontent.com/47185451/80860928-cbbfb180-8c88-11ea-81bc-e582476f75de.jpg)

**Comment by mscharlock** [comment]
@weshi - Do you mind having a look at this, or tagging someone else you think might be able best able to answer this question? Thanks!
