### ISSUE TITLE
makeEwsRequestAsync does not work with online exchange servers windows or mac.

### ISSUE THREAD

**Issue by rjpruitt16** [OfficeDev/office-js#1139]
Calling makeEwsRequestAsync gives an access restricted error. Even if you connect to the online exchange server and give the entire orginization ews privledges, it will not work. When you call makeEwsRequestAsync, you should see the appropriate action completed. I have tried on both mac os and windows.

https://stackoverflow.com/questions/61298569/ews-request-return-access-restriction-error

```
{
  code: 9017,
  message: "Internal protocol error: '-2147467259'.",
  name: "AccessRestricted",
}

function getCreateFolderXMLRequest(request) {
  /*
  example request parameter
  <t:Folder>
    <t:DisplayName>Folder1</t:DisplayName>
  </t:Folder>
  <t:Folder>
    <t:DisplayName>Folder2</t:DisplayName>
  </t:Folder>
  */

  var completeRequest =
    '<?xml version="1.0" encoding="utf-8"?>' +
    '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/ "' +
    '               xmlns:t="https://schemas.microsoft.com/exchange/services/2006/types">' +
    "      <soap:Body>" +
    '          <CreateFolder xmlns="https://schemas.microsoft.com/exchange/services/2006/messages">' +
    "              <ParentFolderId>" +
    '                  <t:DistinguishedFolderId Id="msgfolderroot"/>' +
    "              </ParentFolderId>" +
    "              <Folders>" +
    request +
    "              </Folders>" +
    "          </CreateFolder>" +
    "      </soap:Body>" +
    "</soap:Envelope>";

  return completeRequest;
}

export default function createFolders(listOfFolders, callback) {
  const folderHeader = "<t:Folder> <t:DisplayName>";
  const folderFooter = "</t:DisplayName> </t:Folder>";
  var xmlFolders = [];
  for (var folderName of listOfFolders) {
    xmlFolders.push(folderHeader + folderName + folderFooter);
  }

  const folderXMLRequest = getCreateFolderXMLRequest(xmlFolders.join(" "));

  Office.context.mailbox.makeEwsRequestAsync(folderXMLRequest, callback);
}

```
login to the online exchange server to verify ews is enabled.
set-orginizationconfig ewsenabled true

**Comment by mscharlock** [comment]
@exextoc - Can you have a look at this issue? Thanks!

**Comment by kfmpchan** [comment]
@rjpruitt16 
makeEwsRequestAsync should work by default on Exchange online. Here are a few things to check:
1. Have you tried that your particular EWS request work from a EWS client outside of addins?

2. Have you also tried to see if your addin works in OWA?
For all platforms, in addition to the error returned to the addin, could you check if the EWS request is made to the server and if there is an error response returned? In OWA, the request should be made to <exchange online domain>/owa/service.svc?action=ExecuteEwsProxy. For Windows/Mac, the request should be made to <exchange online domain>EWS/Exchange.asmx. The reason I ask is that I want to confirm if the request was made to the Exchange.

3. To confirm if other EWS calls are working, here's another one you can try that sends a message to yourself.
var request = '<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">'+
	'  <soap:Header><t:RequestServerVersion Version="Exchange2010" /></soap:Header>'+
	'  <soap:Body>'+
	'    <m:CreateItem MessageDisposition="SendAndSaveCopy">'+
	'      <m:SavedItemFolderId><t:DistinguishedFolderId Id="sentitems" /></m:SavedItemFolderId>'+
	'      <m:Items>'+
	'        <t:Message>'+
	'          <t:Subject>Hello, Outlook!</t:Subject>'+
	'          <t:Body BodyType="HTML">This message was sent from &quot;Agave APIs&quot; app&apos;s &lt;font color=green&gt;&lt;b&gt;Make EWS calls&lt;/b&gt;&lt;/font&gt; tutorial used from ' + Office.context.mailbox.diagnostics.hostName + ', version ' + Office.context.mailbox.diagnostics.hostVersion + '!</t:Body>'+
	'          <t:ToRecipients>'+
	'            <t:Mailbox><t:EmailAddress>' + Office.context.mailbox.userProfile.emailAddress + '</t:EmailAddress></t:Mailbox>'+
	'          </t:ToRecipients>'+
	'        </t:Message>'+
	'      </m:Items>'+
	'    </m:CreateItem>'+
	'  </soap:Body>'+
	'</soap:Envelope>';

Office.context.mailbox.makeEwsRequestAsync(request, function (asyncResult) {
    console.log(JSON.stringify(asyncResult));
});

**Comment by exextoc** [comment]
@rjpruitt16
makeEwsRequestAsync should work by default on Exchange online. Here are a few things to check:
1. Have you tried that your particular EWS request work from a EWS client outside of addins?

2. Have you also tried to see if your addin works in OWA?
For all platforms, in addition to the error returned to the addin, could you check if the EWS request is made to the server and if there is an error response returned? In OWA, the request should be made to /owa/service.svc?action=ExecuteEwsProxy. For Windows/Mac, the request should be made to EWS/Exchange.asmx. The reason I ask is that I want to confirm if the request was made to the Exchange.

3. To confirm if other EWS calls are working, here's another one you can try that sends a message to yourself.
var request = '<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">'+
' soap:Header<t:RequestServerVersion Version="Exchange2010" /></soap:Header>'+
' soap:Body'+
' <m:CreateItem MessageDisposition="SendAndSaveCopy">'+
' <m:SavedItemFolderId><t:DistinguishedFolderId Id="sentitems" /></m:SavedItemFolderId>'+
' <m:Items>'+
' <t:Message>'+
' <t:Subject>Hello, Outlook!</t:Subject>'+
' <t:Body BodyType="HTML">This message was sent from "Agave APIs" app's <font color=green><b>Make EWS calls</b></font> tutorial used from ' + Office.context.mailbox.diagnostics.hostName + ', version ' + Office.context.mailbox.diagnostics.hostVersion + '!</t:Body>'+
' <t:ToRecipients>'+
' <t:Mailbox><t:EmailAddress>' + Office.context.mailbox.userProfile.emailAddress + '</t:EmailAddress></t:Mailbox>'+
' </t:ToRecipients>'+
' </t:Message>'+
' </m:Items>'+
' </m:CreateItem>'+
' </soap:Body>'+
'</soap:Envelope>';
Office.context.mailbox.makeEwsRequestAsync(request, function (asyncResult) {
console.log(JSON.stringify(asyncResult));
});

**Comment by rjpruitt16** [comment]
I am going through final, so I don’t have time verify this. I decided to you restasync function instead. I will look at it after school is done next week

**Comment by hthjthtrh** [comment]
I'd like to continue along this issue. I can confirm that I can create and send emails through the CreateItem EWS request, but for what I'm trying to do in my add-in, which is to get an item, and then its attachments, it's returning me the same error code as rjpruitt16 had.
