### ISSUE TITLE
OneNote is undefined

### ISSUE THREAD

**Issue by Roei-Bracha** [OfficeDev/office-js#1142]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/onenote-quickstart

## Issue
I tried to run the code from the demo but I got  the following error in console:
`Error: TypeError: Cannot read property 'run' of undefined`
 I tried to console log OneNote and it returned undefined

I used Mac and OneNote online in chrome
used the newest versions of yo and office generator

**Comment by mscharlock** [comment]
@keyur32 - Do you happen to have an idea who would know the answer to this? I'm trying to route this appropriately :) Thanks!

**Comment by lindalu-MSFT** [comment]
Hi @nokafor! Can you help us with this issue? We need to know which PM to assign it to. Thanks in advance for your insight.

**Comment by lindalu-MSFT** [comment]
@PrashSMSFT Hi, can you assist with this issue or assign it to someone on the OneNote area crew to help? Thanks much

**Comment by ElizabethSamuel-MSFT** [comment]
@lindalu-MSFT Can you help get this transferred to https://github.com/OneNoteDev/OneNoteApi?

Or @Roei-Bracha Can you open a new issue in the https://github.com/OneNoteDev/OneNoteApi repo and reference this issue?

The issue should then get more traction with the OneNote API team.

Thanks.

**Comment by lindalu-MSFT** [comment]
@ElizabethSamuel-MSFT That repo is in a different (non-OfficeDev) org. I don't have the required permissions to transfer this issue to that repo.

**Comment by Roei-Bracha** [comment]
https://github.com/OneNoteDev/OneNoteApi/issues/40
created a new Issue as you requested

as I wrote over there I am no longer have a macbook to check it but hope it will help @lindalu-MSFT @ElizabethSamuel-MSFT

**Comment by ElizabethSamuel-MSFT** [comment]
@Roei-Bracha Thanks for copying this issue. Please check there for updates going forward.

Closing this issue now.
