### ISSUE TITLE
Word insertHtml table in a content control inserts a newline

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#1144]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When inserting a table element with insertHtml method into a content control, a newline is inserted before the table element.

When we do the same into the document body, the newline is not inserted.

## Expected Behavior
When inserting a table into a content control, it should **not** insert a newline before the table element.

## Current Behavior
When inserting a table into a content control, it inserts a new line before the table element.

![image](https://user-images.githubusercontent.com/6338132/81043703-0e64d200-8eb3-11ea-990e-1b297492669c.png)

## Steps to Reproduce, or Live Example
**When using content controls**
Insert an empty content control into a blank word document and run following command:
```
await Word.run(async (context) => {
        const htmlTable = "<table><tr><td>Cell Content</td></tr></table>";
	const ccs = context.document.contentControls;
	ccs.load();

	await context.sync();
	ccs.items[0].clear();
	ccs.items[0].insertHtml(htmlTable , "Replace");

	await context.sync();
});
```
**Without content controls**
When inserting into document body there is no newline in front of the table element:
```
await Word.run(async (context) => {
	const htmlTable = "<table><tr><td>Cell Content</td></tr></table>";
	context.document.body.insertHtml(htmlTable, "Replace");
	await context.sync();
});

```
![image](https://user-images.githubusercontent.com/6338132/81044327-723bca80-8eb4-11ea-940f-3e53e46cd63e.png)

When inserting table into current selection there is no newline in front of the table element:

```
await Word.run(async (context) => {
	const htmlTable = "<table><tr><td>Cell Content</td></tr></table>";
	context.document.getSelection().insertHtml(htmlTable, "Replace");
	await context.sync();
});
```
![image](https://user-images.githubusercontent.com/6338132/81044335-75cf5180-8eb4-11ea-81b5-e01c1ca92fe2.png)

## Context
We have an office addin that can be used to design templates. Html table elements are often used to layout these templates. Sometimes we have these unwished line breaks which is not so cool for the user.

## Your Environment
* Platform: PC
* Host: Word
* Office version number: 2004 (Build 12730.20236)
* Operating System: Windows

**Comment by mscharlock** [comment]
@weshi Do you mind taking a look at this? Thanks!

**Comment by MartinSSeifert** [comment]
@weshi did you have a chance to look at this?

**Comment by xiruatms** [comment]
Thanks for reporting this.

According to the investigation, this is a by-design behavior, and also consistent with the current behavior when you tried to insert a table to a content control with UI operation: a newline was added before the table.

**Comment by barisbikmaz** [comment]
@xiruatms I don't think that this should behave like the UI insertion. I can image that the UI does this because it is nearly impossible to enter sth manually before and after the table if there would be no space before the table in that content control.

But with code I have control if I want to have a paragraph before and after the table and can decide if I wanna do that.
 cc @MartinSSeifert @AbidRahman-MSFT

**Comment by oldrich-s** [comment]
Is there any work-around for this behaviour? Something like detecting it and removing it or similar?

So far I came to the following, which is not ideal but works.

```
control.paragraphs.load('items')
await o.context.sync()

const items = control.paragraphs.items
if (items.length < 3) return

if (!items[0].text) items[0].delete()

const last = items[items.length - 1]
if (!last.text) {
  last.spaceAfter = 0
  last.lineSpacing = 0.72
}
```

**Comment by barisbikmaz** [comment]
FYI: We can't use this workaround because we don't generate the html. 
Our addin accepts html and inserts it into the document. The customer generates the html.
