### ISSUE TITLE
window.open method does not provide the expected result

### ISSUE THREAD

**Issue by Cata-ExF** [OfficeDev/office-js#1145]
I am using the following method to download a file:
window.open(location.origin + res, '_blank');

## Expected Behavior

A file download should be provided.

## Current Behavior

All I receive is a blank screen, as in the image attached. The same method works in excel online, I do receive the download using the same button.
tried it in 3 other computers, same issue.

![blank screen received](https://user-images.githubusercontent.com/64840748/81061287-bc38a680-8edc-11ea-82cc-a34cde89e7aa.png)

## Steps to Reproduce, or Live Example

* Link to live example: ______
[ExFormOfficeAddInExcelUI.zip](https://github.com/OfficeDev/office-js/files/4580402/ExFormOfficeAddInExcelUI.zip)
the behaviour can be reproduced by using the xml manifest attached. Once you deploy the addin, you can login with;
email: admin@gmail.com
pass: admin
Account: aspire
Once logged in, press the Sets of Forms link, a demo treeview will load. Select any orange set with a double click, now you should be able to view and click on the Download button.

* Additional details:
  1. ______
  2. ______
  3. ______
code used:

`function DownloadExcelTemplate() {
        $('#btnDownloadExcel').hide();
        $('#btnDownloadingExcel').show();
        $.ajax({
            type: 'get',
            cache: false,
            url: '/api/Template/DownloadExcelTemplate',
            data: {
                templateId: templateId,
                userId: parseInt(localStorage.getItem("UserID"))
            },
            contentType: 'application/json;charset=utf-8'
        }).done(function (res) {
            if (res !== null && res !== "") {
                setTimeout(function () {
                    window.open(location.origin + res, '_blank');
                }, 250);
            } else {
                app.showNotification('Error', 'File not found.');
            }
            $('#btnDownloadExcel').show();
            $('#btnDownloadingExcel').hide();

        }).fail(function (status) {
            app.showNotification('Error', 'File not found.');
        });
    }`

## Context

This excel download is the template that will be used by users to send data to that set of forms.
After they fill it with data, they should press the Send Data button, they will receive a .zip archive for download. This download is also not working, same blank screen shows up, ONLY in desktop, works in excel online.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.12730.20188
* Operating System: Win 10 64 bit
* Browser (if using Office Online): Firefox (tried opera and chrome as well)

## Useful logs

- [ ] Console errors
- [x] Screenshots
![blank screen received](https://user-images.githubusercontent.com/64840748/81062185-361d5f80-8ede-11ea-9321-be8555357472.png)
- [ ] Test file (if only happens on a particular file)

**Comment by mscharlock** [comment]
@lumine2008 Do you mind having a look at this issue? Thanks!

**Comment by lumine2008** [comment]
@lliu113 , Looks like this is UX scope, will you be the right person to take care of this issue?

**Comment by lukchen** [comment]
I'm meeting the same issue in Desktop Excel. What is the standard way to download file in Excel AddIn?

**Comment by lukchen** [comment]
based on my observation, if use window.open("http://xxx/xxx.pdf"), system browser will be opened and file gets downloaded; while window.open("https://xxx/xxx.pdf") will open a dialog inside Excel and cant get file downloaded. Is this http vs https difference the problem?

**Comment by Cata-ExF** [comment]
Hi @lukchen ,
Thanks for your observations, very useful.
In an addin, we are supposed to use only https, is that correct?
I was expecting https to work, and http to fail, seams logical, but apparently there is no visible logic.
Still curious to see a reasonable explanation of this behavior, but I'll accept a solution without asking embarrassing questions like "Why?!" :)
Thanks again for your thoughts
Cheers,
Catalin

**Comment by lukchen** [comment]
@Cata-ExF  Yes we are supposed to use only https. I've looked at this example https://github.com/OfficeDev/office-js/issues/712
Is "Office.context.ui.openBrowserWindow" a valid API and a workaround can address this issue?

**Comment by Cata-ExF** [comment]
Hi @lukchen ,
Office.context.ui.openBrowserWindow does work.
Is there a way to download AND open the downloaded file?
Thank you

**Comment by lukchen** [comment]
@Cata-ExF Hi, you said it does work, how? What I meant was can this function open the system browser and download the file

**Comment by Cata-ExF** [comment]
@lukchen : Instead of window.open(url), I used:
Office.context.ui.openBrowserWindow(url)
A new tab open in default browser and the download dialog was displayed.

**Comment by lukchen** [comment]
@Cata-ExF Great! I'll try it as well. So why is the question "Is there a way to download AND open the downloaded file?" still need anwser?

**Comment by Cata-ExF** [comment]
My guess is that Office.context.ui.openBrowserWindow is nothing else but a workaround.
Is there an official way to download a file and OPEN the downloaded file (not just download) ?

**Comment by lukchen** [comment]
@Cata-ExF I see. I think we need this anwser from Devs

**Comment by libjosep** [comment]
Hi..I am getting an error _Property 'openBrowserWindow' does not exist on type 'UI'. What am I doing wrong?

**Comment by sanjaygovindan** [comment]
@Libinjoseph  - Also experiencing the same thing. 
Trying to find documentation for this function but can't seem to locate any reference.  

Only thing I can find is this: 
https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins#get-errors-trying-to-download-a-pdf-file

**Comment by mausinc** [comment]
@Libinjoseph @sanjaygovindan  did you find a way to solve this problem?

**Comment by jpalo** [comment]
Any tips how to use openBrowserWindow? It is not defined in `https://appsforoffice.microsoft.com/lib/1/hosted/office.js` nor in `https://appsforoffice.microsoft.com/lib/beta/hosted/office.js`.

**Comment by safiness** [comment]
@jpalo  - nope, but if it's outside the whitelisted domain in your manifest it should open in a new window outside excel. 

For now, just living in dialogs.

**Comment by jpalo** [comment]
Turns out openBrowserWindow didn't work if I used it in Typescript file. Not sure why, probably related to webpack. After switching to vanilla Javascript, I was able to open new browser window just fine (via ribbon button command).

**Comment by safiness** [comment]
Thanks - Great!

**Comment by lliu113** [comment]
@Cata-ExF - unfortunately there is no official way to download + open the doc. The recommended approach is to use Office.context.ui.openBrowserWindow(URL) (as you are currently using), get your file and use the browser to download.

 Appreciate the great discussion in the thread, as well as the proposed workarounds! 

I'll go ahead and close this, please feel free to reactivate if you have any additional questions/feedback.
