### ISSUE TITLE
openAsyncdialog display shows different title in different platforms.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#1147]
We are using open asyncdialog to display some html message to our end users, for our outlook addon. The title of the dialog shown is different for different outlook/browser clients..

## Expected Behavior
All of the platforms should display the same title.

## Current Behavior
Browser based asyncdialogs show the same title, using the "Display Name" declared in the manifest. In the samples below, the name of the addon declared in the manifest is "Best AddOn Ever".

1. For Chrome/FireFox/Safari/Edge, the dialog box's title is the same as the addon display name "Best AddOn Ever",  we have the following:
 
![Chrome-OutlookOWA-cutoff](https://user-images.githubusercontent.com/3444844/81147386-c9bd6180-8fac-11ea-89ed-3a569b135898.png)

2. For Windows-Outlook, the dialog box's title is the same as the addon display name "Best AddOn Ever" plust the full url of the html file behind the dialog. This is what i see :

![OutlookWindows-Prompt-Cutoff](https://user-images.githubusercontent.com/3444844/81147412-d6da5080-8fac-11ea-8e17-f21350532f9a.png)

3. For MAC OS-Outlook we see "Office Add-Ins" plus the domain of the addon. We have this :

<img width="842" alt="Outlook-MACClient" src="https://user-images.githubusercontent.com/3444844/81147445-e8bbf380-8fac-11ea-87ec-2a8dcaa44f31.PNG">

## Steps to Reproduce, or Live Example
To reproduce this issue, just make a very simple addon that can uses the "Office.context.ui.displayDialogAsync" API. Run the said dialog in different platforms and browsers.

## Context
This issue is causing confusion for our addon users because of the different User experience for different platforms. I am in the opinion that the best title is still the name of the addon. Or anything, just make the user experience uniform.

## Your Environment
Please see the images. For OWA, chrome, safari, firefox and edge. For MAC and Windows Outlook standalone clients.

## Useful logs
none needed

**Comment by glr0221** [comment]
Thank you in advance to all of you guys in microsoft.

**Comment by exextoc** [comment]
@glr0221 We do observe this behaviour in OWA and Windows. For Mac, Can u share following details?
- Version
- What exactly did you mean by <DOMAIN_OF_ADDON> . Is it AppDomain mentioned in manifest?

**Comment by glr0221** [comment]
@exextoc 

First off thanks for the speedy response. I am really impressed and happy with your readiness to help. 

Now for the version I have this : 16.35 (20030802)
For the Domain of addon : assuming the source url is http://www.xxx.yyy.zzz//aaabbbbcccddd.htm
then domain of addon is "www.xxx.yyy.zzz". 

Does that make sense? thanks!!

**Comment by exextoc** [comment]
Thanks for reporting this issue. After careful consideration, our team has decided to not fix this issue. The title here has the url/domain for security reasons. 
On OWA, with `displayInIframe:false` user will see the url/domain.

**Comment by glr0221** [comment]
Thank you @exextoc! I will inform our clients of your decision then.
