### ISSUE TITLE
Unstable behaviour of onDataChanged

### ISSUE THREAD

**Issue by thiago-vivas** [OfficeDev/office-js#1149]
## Expected Behavior
Event-triggered after editing a cell

## Current Behavior
1. Event-triggered on Selection Changed of a cell that has a dropdownlist
2. Event-triggered on Selection Changed of a cell after clicking on a cell with dropdownlist. If you click beside a cell that has the onDataChanged binding the event triggers as well.

`function run() {
  return Excel.run(async function(ctx) {

    const sheet = ctx.workbook.worksheets.getActiveWorksheet();

    var wholerange1 = sheet.getRange("A4");
    var wholerange2 = sheet.getRange("A6");

    wholerange1.dataValidation.rule = {
      list: {
        inCellDropDown: true,
        source: "ab, cd, ef, gh"
      }
    };

    var binding1 = ctx.workbook.bindings.add(wholerange1, "Range", "one");
    var binding2 = ctx.workbook.bindings.add(wholerange2, "Range", "two");
    
    binding1.onSelectionChanged.add(testar);
    binding2.onDataChanged.add(testa2r);
    
    await ctx.sync();
  });
}
function testar(args){
console.log(args);
}
function testa2r(args) {
  console.log(args);
}
`

## Steps to Reproduce, or Live Example
0. Run the code above with Script Lab
1. Edit the A6 cell (expected behavior)
2.1 Click in the A4 cell
2.2 Click in the A6 cell
3.1 Click in the A4 cell
3.2 Click in any cell around A6 cell

**Comment by MandytMSFT** [comment]
I can repro this bug and filed BUG 4142347 for internal track

**Comment by lumine2008** [comment]
This issue was fixed, please verify, thanks
