### ISSUE TITLE
completing OnSend seems borked since May update: it May not send and close add-in on certain platforms/browsers

### ISSUE THREAD

**Issue by michahell** [OfficeDev/office-js#115]
## Expected Behavior
OnSend actually sends the email and closes add-in. 

## Current Behavior

nothing.

## Steps to Reproduce, or Live Example

- can not provide a live example.

- can not create script lab as this relates to Outlook, not Word Excel Powerpoint etc.

* Additional details:
  1. compose a message (recipient, subject, body)
  2. press send with having an OnSend function triggering
  3. make the OnSend function complete with {allowEvent : true }
  4. should fail ?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook Web App
* Office version number:  N.A.
* Operating System: Mac OSX 10.12.6

* Browser (if using Office Online): 
OSX/Chrome: **fails**
OSX/Firefox: succeeds
WIN/Firefox: **fails**
OSX/Safari: **fails**

## Useful logs

- [ ] Console errors
none
- [ ] Screenshots
I could make a screenshot but it would show nothing. just a `console.log()` statement júst before calling `this.onSendEvent.completed({ allowEvent: true }); // sends + closes OWA draft`.
- [ ] Test file (if only happens on a particular file)

**Comment by mamousch** [comment]
@michahell I'm investigating this, but need more information in order to repro, since the latest builds still work correctly with my demo add-ins.  Would you be able to send me your add-in or a simplified version of it, and any more info you think I might need to repro this?

**Comment by michahell** [comment]
@mamousch I'm sorry I never closed this, as it seems, this behaviour was caused by having a dialog open and *not* `.close()` ing such dialog *before* completing onSend, with or without the `allowEvent` parameter.

Unfortunately I can not share our add-in but adding / removing a `.close()` statement *before* `onSendEvent.completed({ allowEvent: true })` 
should be able to deterministically reproduce the bug after the May update.

**Comment by mamousch** [comment]
@michahell Thank you for the clarification!
