### ISSUE TITLE
Outlook Desktop, Outlook for Mac: setSelectedDataAsync incorrect size for base64 images

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1150]
In an Outlook add-in for compose mode, we use the Office JS API to fill in email fields. The setSelectedDataAsync method inserts base64 images and ignores the width and height attributes.

## Expected Behavior
The setSelectedDataAsync method shall work correctly as it does in Outlook Online.

## Current Behavior
The width and height attributes are ignored.

## Steps to Reproduce, or Live Example
Create a new email in Outlook Desktop or Outlook for Mac and execute the following code:

`// variant #1`
`Office.context.mailbox.item.setSelectedDataAsync(`
`  '<img width="50" height="50" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAIAAAAiOjnJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAGdYAABnWARjRyu0AAACLSURBVHhe7cEBAQAAAIIg/69uSEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAByoAdWXAAGkmvtwAAAAAElFTkSuQmCC" />',`
`  { coercionType: Office.CoercionType.Html },`
`  (result) => { }`
`);`

One more variant of the code that shall insert a 50*50 pixels image:

`// variant #2`
`Office.context.mailbox.item.setSelectedDataAsync(`
`  '<div style="width: 50px; height: 50px;">' +`
`  '  <img style="width: 100%; height: 100%" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAMgAAADICAIAAAAiOjnJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAGdYAABnWARjRyu0AAACLSURBVHhe7cEBAQAAAIIg/69uSEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAByoAdWXAAGkmvtwAAAAAElFTkSuQmCC" />' +`
`  '</div>',`
`  { coercionType: Office.CoercionType.Html },`
`  (result) => { }`
`);`

* Additional details:
  1. Everything works fine in Outlook Online.

## Your Environment
* Platform: PC desktop and Mac
* Host: Outlook and Outlook for Mac
* Office version number: Outlook version 2004 (build 12730.20250) and Outlook for Mac Version 16.36.1 (20041900)
* Operating System: Windows 10 1909 and macOS Catalina Version 10.15.3
* Browser (if using Office Online): ______

**Comment by mscharlock** [comment]
@exextoc Do you mind having a look at this issue? Thank you!

**Comment by exextoc** [comment]
Yes, I can reproduce the issue. I am investigating.
At the same time, have you considered using inline attachment? https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-1.8#method-details or  https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-1.8#addfileattachmentfrombase64async-base64file--attachmentname--options--callback- with isInline and setting the html to reference the image?

**Comment by DmitryKostochko** [comment]
>> At the same time, have you considered using inline attachment?

Inline attachments work well except one case, I will create a new issue about it later. But the addFileAttachmentFromBase64Async method exists in API Set >= 1.8 and we shall support older sets.

**Comment by exextoc** [comment]
The build number for the Desktop fix: 16.0.12918.10000.
For Mac, we have fixed the bug and the fix should be available. Depending on the release channel a customer is on, getting an updated build can take anywhere from 4-8 weeks, so we suggest you update to the latest build.
