### ISSUE TITLE
Outlook REST API, call to api/v2.0/me/messages/{message-id} fails with the ErrorInvalidMailboxItemId error code

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1152]
In an Outlook add-in for compose mode, we use the REST API to access the contents of emails that reside in the primary user's mailbox or other users' mailboxes. The call to api/v2.0/me/messages/{message-id} stopped working for other users' mailboxes, the "Item Id doesn't belong to the current mailbox." error occurs.

## Expected Behavior
The REST API call shall work as it did before.

## Current Behavior
The following error occurs:
error: {code: "ErrorInvalidMailboxItemId", message: "Item Id doesn't belong to the current mailbox."}

## Steps to Reproduce, or Live Example
As you understand, I cannot provide a working code sample.

Steps:
* User A gives permissions for an Outlook folder (and all parent folders including mailbox) to User B.
* User A obtains the ItemId of a message in the shared folder and passes it to User B.
* User B obtains the restUrl (Office.context.mailbox.restUrl) and rest token and tries to get the shared email via the REST API:

Office.context.mailbox.getCallbackTokenAsync({ isRest: true }, async (result: Office.AsyncResult<any>) => {
        if (result.status === Office.AsyncResultStatus.Succeeded) {
          // make REST request here to get the message using the token and message id
        }
});

* The following error occurs:
error: {code: "ErrorInvalidMailboxItemId", message: "Item Id doesn't belong to the current mailbox."}

## Context
The described scenario is implemented in our add-in and the code worked until something has changed in the REST API recently.

## Your Environment
* Platform: PC desktop, Mac, Office Online
* Host: Outlook
* Office version number: Any that supports REST API, i.e. set >= 1.5
* Operating System: Windows, Mac
* Browser (if using Office Online): Edge, Chrome, IE, Firefox, Safari

**Comment by mscharlock** [comment]
@exextoc Do you mind checking into this? Thanks!

**Comment by exextoc** [comment]
From your comment on Post https://github.com/OfficeDev/office-js/issues/1146 , this is what we understand. Can you confirm these?
- The rest call is being made in Compose Mode and you are accessing a Read Item in delegator's mailbox.
- SupportsSharedFolder is not used and 1.8 APIs are not supported.

And, Could you clarify the point "User A obtains the ItemId of a message in the shared folder and passes it to User B"? How is this being achieved here?

**Comment by DmitryKostochko** [comment]
Sorry for not being clear enough in my description.

>> The rest call is being made in Compose Mode and you are accessing a Read Item in delegator's mailbox.

Yes, correct.

>> SupportsSharedFolder is not used and 1.8 APIs are not supported.

Yes, correct. We have a lot of clients with API < 1.8.

>> And, Could you clarify the point "User A obtains the ItemId of a message in the shared folder and passes it to User B"? How is this being achieved here?

Both User A and User B have our add-in installed and can "share" their Outlook folders between each other by using the add-in's feature. In other words, User B can see all ItemId's that User A has provided to him and can get the email contents via the REST API. Did I answer your question?

**Comment by exextoc** [comment]
The error you are observing is because of the change mentioned in  https://developer.microsoft.com/en-us/office/blogs/accessing-outlook-items-in-a-users-archived-shared-or-delegated-mailboxes-using-microsoft-graph/
Accessing  delegator's mailbox items using api/v2.0/me/messages/{message-id}  is no longer supported.

**Comment by DmitryKostochko** [comment]
Thank you for the details.

I have just tried to access another user's items by using the api/v2.0/users/{user-id}/messages/{message-id} endpoint and got the following error:
HTTP403: FORBIDDEN - The server understood the request, but is refusing to fulfill it.

Where {user_id} is a valid SMTP address and {message-id} is a valid itemId.

@exextoc, please let me know what REST API endpoint I can use to get access to delegator's mailbox items. Note, SupportsSharedFolder is not used and 1.8 APIs are not supported.

**Comment by exextoc** [comment]
Given,
- The [limitation](https://developer.microsoft.com/en-us/office/blogs/accessing-outlook-items-in-a-users-archived-shared-or-delegated-mailboxes-using-microsoft-graph/) introduced to Graph API.
- Recommendation from add-ins perspective to use [SupportsSharedFolder](https://docs.microsoft.com/en-gb/office/dev/add-ins/outlook/delegate-access)

Using [getSharedPropertiesAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.sharedproperties?view=outlook-js-preview) is the solution here.

But in your case, you are accessing a mail item, which is different from the current mail item, your add-in is running on, we have no proper way of supporting this scenario.

We recommend you to create or upvote a [User-voice item](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins), this will give us visibility of the commonality of it and will help with our prioritisation. If we end up working on this issue we will re-activate as needed.

**Comment by DmitryKostochko** [comment]
I have added the SupportsSharedFolder element to our manifest and the following REST API call has started to work:
api/v2.0/users/{user-id}/messages/{message-id}

@exectoc, could you please confirm that this is a valid and supported way in our scenario? Thank you.
