### ISSUE TITLE
Webkit(macOS, Safari) based Excel freezes while removing big tables/ranges

### ISSUE THREAD

**Issue by pfilipp** [OfficeDev/office-js#1153]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior

Excel for Mac and Office Online(Excel) in Safari is responsive while removing big tables and ranges.

## Current Behavior

Currently when using officejs API method .delete(), on either table or range, causes Excel for mac or Safari browser to freeze. 
macOS shows "spinning wheel of death" for few seconds and the UI is completely unresponsive.

The issue was also checked on Google Chrome (both macOS and Windows), IE and Excel Desktop for Windows and it is **not** present.

## Steps to Reproduce, or Live Example

Link to gist with snipped to present issue: https://gist.github.com/pfilipp/38967c9c8bacf7c15d5d3034e49e6495

Please use attached Excel file with 100k rows. [test_book_2.xlsx](https://github.com/OfficeDev/office-js/files/4592435/test_book_2.xlsx)
Or generate your own data structure that is 100k+ rows big. It needs to be a table due to snippet implementation.

Steps to reproduce:
1. Open attached xlsx file in Office Online on Safari or Excel for Mac
2. Load snippet with ScriptLab
3. Click Delete table
4. Observe freezes

## Context

I need a reliable and non blocking way of removing big data structures in Excel across all clients due to project I am working on.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac and Office Online(Safari)
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.36 (20041300)
* Operating System: macOS 10.15.4
* Browser (if using Office Online): Safari 13.1 (15609.1.20.111.8)

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lumine2008** [comment]
Thanks, a bug 4145133 was created to track this issue, Team is working on the investigation.

**Comment by lumine2008** [comment]
it seems it is not an Excel JS API related issue, so let me loop shaofeng.

**Comment by donlvMSFT** [comment]
This issue seems already been fixed due to bug status, please help verify. I'd like to resolve this thread, thanks for discussion!
