### ISSUE TITLE
mailbox.item.body.getAsync affects clipboard functionality on Outlook for Mac

### ISSUE THREAD

**Issue by bchenhs** [OfficeDev/office-js#1154]
On Outlook for Mac, if the user copies any content (e.g. a single word) within a second after a `mailbox.item.body.getAsync` call, the clipboard contains the entire email body. This only occurs on Outlook for Mac, not OWA.

It appears that `mailbox.item.body.getAsync` temporarily selects the entire email body to get the content on the Mac platform.

## Expected Behavior
`mailbox.item.body.getAsync` should not affect clipboard functionality.

## Current Behavior
`mailbox.item.body.getAsync` call affects clipboard functionality for a period of time.

## Steps to Reproduce, or Live Example
- On Outlook for Mac, open a compose message and add-in.
- Enter random contents in the email body.
- Highlight a single word from the email body.
- Make a `Office.context.mailbox.item.body.getAsync` call
- Within a second, copy the highlighted word (either Ctrl-C or menu copy)
- Paste into any external editor (or the subject input)
- The entire email body, instead of the highlighted word, is pasted.

* Note: It is easy to reproduce by making `mailbox.item.body.getAsync` call every second in a test add-in.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook

**Comment by mscharlock** [comment]
Hi @exextoc - Would you mind checking on this? Thanks!

**Comment by exextoc** [comment]
Could you please clarify the point "Within a second, copy the highlighted word (either Ctrl-C or menu copy)"? Are you selecting the text again to copy or using Edit->Copy with the selection made before Office.context.mailbox.item.body.getAsync call ?

**Comment by bchenhs** [comment]
@exextoc As long as the copy operation happens within a ~1s timeframe after a call to `Office.context.mailbox.item.body.getAsync`, the clipboard always contains the entire body regardless of selection.

**Comment by exextoc** [comment]
We are unable to hit this scenario in our environment.
Can you confirm whether you are using code similar to below snippet?

    function getBody() {
      Office.context.mailbox.item.body.getAsync("html", function (asyncResult) {  
        console.log(asyncResult);
      });
    }
    setInterval(getBody, 1000);

Is it possible to share your add-in with us?
Also can you check whether body view (not add-in) is focussed when copying?

**Comment by bchenhs** [comment]
Hi @exextoc I created a dummy add-in that contained only the code you outlined, and was able to reproduce it.

- This only occurs on Outlook for Mac (on both the regular and Insider channels).
- And
> Paste into any external editor (or the subject input)

When pasting back into the email compose body, it works correctly.

**Comment by exextoc** [comment]
Can you please specify the OS version and the Mac outlook client version. And it'll be easy for us to debug if you can provide an a stripped down version of add-in.

**Comment by bchenhs** [comment]
Hi @exextoc, we've seen this issue on:
- macOS Catalina (10.15.3) with Office for Mac 16.36 (20041300)
- macOS Mojave (10.14.1) with Office for Mac 16.38 (20051207)

We can reproduce this with a Taskpane add-in that only contains the above code snippet. The issue occurs as long as the taskpane is open (no HTML contents on it at all) and running the `get` call.

**Comment by bchenhs** [comment]
Our manifest looks like:

> <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Requirements>
        <bt:Sets DefaultMinVersion="1.5">
          <bt:Set Name="Mailbox"/>
        </bt:Sets>
      </Requirements>...

> 
        </ExtensionPoint><ExtensionPoint xsi:type="MessageComposeCommandSurface">
              <OfficeTab id="messageComposeTab">
                <Group id="messageComposeTab.mainGroup">
                  <Label resid="AppLabel"/>
                  <Control xsi:type="Button" id="openSidebarReadButton">
                    <Label resid="openSidebarLabel"/>
                    <Supertip>
                      <Title resid="openSidebarSupertipTitle"/>
                      <Description resid="openSidebarSupertipDesc"/>
                    </Supertip>
                    <Icon>
                      <bt:Image size="16" resid="logo-16"/>
                      <bt:Image size="32" resid="logo-32"/>
                      <bt:Image size="80" resid="logo-80"/>
                    </Icon>
                    <Action xsi:type="ShowTaskpane">
                      <SourceLocation resid="taskPaneComposeModeURL"/>
                      <SupportsPinning>true</SupportsPinning>
                    </Action>
                  </Control>
                </Group>
              </OfficeTab>
            </ExtensionPoint>

**Comment by exextoc** [comment]
We are still unable to reproduce this issue. We are wondering if we are doing something wrong in our repro steps. Is it possible for you to record a video of your repro steps which shows this problem? Can you please share such video with us?

**Comment by bchenhs** [comment]
@exextoc Here is the video, demonstrating the issue using the script lab, running the code snippet above:

![clipboard_issue](https://user-images.githubusercontent.com/39492089/84784610-8812d400-afb8-11ea-8de7-fff828952fcf.gif)

**Comment by exextoc** [comment]
Thanks for reporting this issue and sharing the repro video. We are able to repro the issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.
