### ISSUE TITLE
How to accept permission request for all user in Microsoft office 365

### ISSUE THREAD

**Issue by hdkdinh** [OfficeDev/office-js#1155]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

>>> **How to accept permission request for new user in Microsoft office 365** <<<

We used Outlook 365 add-in. After global admin deploy our add-in, global admin check"Consent on behalf of your organization" to accept permission for their organization (please see attached image).

![Capture](https://user-images.githubusercontent.com/52642696/81391804-e6da6780-9147-11ea-994a-a8b6a70eb3a5.PNG)
![show permission - Copy](https://user-images.githubusercontent.com/52642696/81391780-daeea580-9147-11ea-8e46-a27c7fb2cd1f.png)

But users is created after global admin accept permission need to accept again permission request.
Please give us the way how to we accept permission request for all user. User is created after global accept permission don't need to accept again.

**Comment by exextoc** [comment]
Thanks for creating this issue. We are looking into it and we will back on this as soon as possible.

**Comment by psignoret** [comment]
When a tenant administrator grants tenant-wide admin consent, they are authorizing the app on behalf of all current _and future_ users in the organization (in the case of delegated permissions). When the app is requesting app-only permissions, the tenant admin is authorizing direct access to the data (i.e. the app is accessing the data on its own behalf, not on behalf of a user).

In both cases, once the app has been granted tenant-wide admin consent through the experience you show, users (both existing and new) should not be seeing any addition consent prompts.

**Comment by exextoc** [comment]
When an application has been granted tenant-wide admin consent, all users will be able to sign in to the app unless it has been configured to require user assignment. To restrict which users can sign in to an application, require user assignment and then assign users or groups to the application. Hence if require user assignment is not configured all current users and future users would get the admin consent. For more information, Prerequisites section in - https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent

**Comment by hdkdinh** [comment]
We added permission and granted tenant-wide admin consent by application administrator from App Registrations on Azure portal. But future user still need accept again permission request. Do global admin (in client side) need to add permission and granted tenant-wide admin consent by themselves?
