### ISSUE TITLE
Shared JS runtime availability and plans

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#1156]
Dear guys,

This is a question, but not a usage question, rather, a product one - which is why I am posting it here. If it's not the right place, please direct me before closing! 🙏 

I am currently working on an Excel add-in that desperately needs the presence of IndexedDB storage APIs in Excel custom functions (I need to cache quite a bit of data for smooth calculation experience). 

AFAIU it is currently not possible inside the custom functions' runtime.

I encountered this: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview

Since the life of my product depends on this, I wanted to understand: 

- Will the shared runtime feature come inside a new office.js library version, so it would be a seamless update that we can perform on our side (so it will appear even in today's Excel versions without a client-side update)?
- Or will it require **the customers** to update to bleeding-edge Excel versions across the platform board?
- What are your plans on general availability of this feature, maybe approximately? My product is a new one, so it will be some time before we release. I understand there can be no commitment, but if this is already established, would be nice to know.
- Is full platform support planned - Web, Windows, Mac, iPad?

Please redirect my question to the product team if needed... I can be contacted at pkabir.work@gmail.com .

**Comment by jeremy-msft** [comment]
Hi @wh1t3cAt1k, we're glad you're interested in the shared runtime functionality.  This is a client-side feature so users will need to be on the latest versions of Excel.  We don't have any news to share about GA or platform availability today, but we encourage you to join our [monthly community calls](https://aka.ms/officeaddinscommunitycall) for the latest updates -- the next one will be this Wednesday at 8:00AM PST.
