### ISSUE TITLE
Any plan to make getAccessTokenAsync(options, callback) production ready

### ISSUE THREAD

**Issue by kishor1910** [OfficeDev/office-js#1159]
Hi, I wanted to use getAccessTokenAsync for my outlook addIn development,  but it is in preview mode now. Can I use this API in production or do you guys have any plan to move it to use in production?
Please share if you have any other workaround for the same API.

Thanks.

**Comment by mattgeim** [comment]
We suggest not using preview APIs in production as breaking changes can be introduced. Unfortunately there is no specific timeline to share around the general availability of the SSO API, but we are actively working towards that in the near future. Add-ins that implement SSO should still implement a backup method, like the Dialog API, in case SSO encounters an issue like an unsupported client.  Additional details on how to do so are available here:  https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/implement-sso-in-outlook-add-in

Please feel free to re-open the issue or create a new one if there is feedback on the API or issues you are running in to using it so we can help address them.
