### ISSUE TITLE
Clarifications about availalbility

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#1160]
I am currently working on an Excel add-in that desperately needs the presence of IndexedDB storage APIs in Excel custom functions (I need to cache quite a bit of data for smooth calculation experience). 

AFAIU it is currently not possible inside the custom functions' runtime.

I encountered this: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview

Since the life of my product depends on this, I wanted to understand: 

- Will the shared runtime feature come inside a new office.js library version, so it would be a seamless update that we can perform on our side (so it will appear even in today's Excel versions without a client-side update)?
- Or will it require **the customers** to update to bleeding-edge Excel versions across the platform board?
- What are your plans on general availability of this feature, maybe approximately? My product is a new one, so it will be some time before we release. I understand there can be no commitment, but if this is already established, would be nice to know.
- Is full platform support planned - Web, Windows, Mac, iPad?

Please redirect my question to the product team if needed... I can be contacted at pkabir.work@gmail.com .
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc89eff2-1c69-c80f-2cfb-43746309f2b7
* Version Independent ID: af86e11c-93ec-c0d9-bccd-cdd993fce37c
* Content: [Run your add-in code in a shared JavaScript runtime (preview) - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview)
* Content Source: [docs/excel/custom-functions-shared-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-shared-overview.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by keyur32** [comment]
Hi @wh1t3cAt1k , we suggest you join our community call this week as we'll have an invite then.

See here for a calendar invite for Wednesday May 13, 8am PDT:  https://aka.ms/officeaddinscommunitycall

**Comment by wh1t3cAt1k** [comment]
This is already available as I learned from MSBuild.
