### ISSUE TITLE
run mailbox.item.getSharedPropertiesAsync success but always with a http404 request?

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1161]
I have using 'mailbox.item.getSharedPropertiesAsync' function to get calendar owner. Like:
`if (!Office.context.mailbox.item.getSharedPropertiesAsync) {
                    zopLog("not running in a shared folder.");
                    resolve(null);
                } else {
                    Office.context.mailbox.item.getSharedPropertiesAsync( function(result) {
                        if(result.status == "succeeded"){
                            resolve(result);
                        } else {
                            resolve(null);
                        }
                    });
                }`
And actually it return me a useful json about this shared calendar owner. 
But every time I call this function, it will show an error on network tag like:
xxx.xxx@xxx.com?Protocol=REST     http 404

By the way, this function might take some time to return a result. I am not sure if this is caused by the 404 request.

So my question is: Is it possible remove this request when I call 'getSharedPropertiesAsync' not in a REST way? 

## Expected Behavior
call 'getSharedPropertiesAsync' but not call 404 request.

## Steps to Reproduce, or Live Example
just need call this on js.like:
`if (!Office.context.mailbox.item.getSharedPropertiesAsync) {
                    zopLog("not running in a shared folder.");
                    resolve(null);
                } else {
                    Office.context.mailbox.item.getSharedPropertiesAsync( function(result) {
                        if(result.status == "succeeded"){
                            resolve(result);
                        } else {
                            resolve(null);
                        }
                    });
                }`

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: outlook
* Office version number: o365 online
* Operating System: windows 10
* Browser (if using Office Online): Chrome/Firefox

**Comment by exextoc** [comment]
getSharedPropertiesAsync should return to you the properties of the shared item.  Are you not getting those values back from the function? 

Can you provide some clarifications on your comment: 

> But every time I call this function, it will show an error on network tag like:
xxx.xxx@xxx.com?Protocol=REST http 404

What does "it will show an error" mean? Where are you getting that error? In the Async Result? what is a "network tag" ? 

What platform are you on and version? Are you using Outlook Web Access or Windows Rich Client? (the tags that you provided both list PC Desktop and Chrome/Firefox)

**Comment by SWei1234** [comment]
@exextoc 
Thanks for your reply. I'm sorry I did n' t describe the problem clearly.

1. getSharedPropertiesAsync should return to you the properties of the shared item. Are you not getting those values back from the function?
No, I get the properties of the shared item successfully.

2. Can you provide some clarifications on your comment:
But every time I call this function, it will show an error on network tag like:
xxx.xxx@xxx.com?Protocol=REST http 404

What does "it will show an error" mean? Where are you getting that error? In the Async Result? what is a "network tag" ?
I open chrome's devtool and get error like:
![image](https://user-images.githubusercontent.com/15980696/81661876-59f91c00-946f-11ea-8142-08c65f762bf7.png)

3.What platform are you on and version? Are you using Outlook Web Access or Windows Rich Client? (the tags that you provided both list PC Desktop and Chrome/Firefox)
I'm using windows 10  Outlook Web Access on chrome.

Thanks

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding network failure when calling getSharedPropertiesAsync API. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
Closing this, we will track this with https://github.com/OfficeDev/office-js/issues/1240
