### ISSUE TITLE
Preview status and will anything change with the new SaaS monetization model?

### ISSUE THREAD

**Issue by jimbarrett33** [OfficeDev/office-js#1164]
This has been in preview for a while and since then there is a new SaaS monetization model for selling apps via App Source. This document indicates "In addition, add-ins that use SSO are not accepted in AppSource." Will this still be the case under the new SaaS monetization model? Forcing the user to sign-in again inside the add-in is not the best user experience. Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb06c24b-9d11-9cc5-2e98-561601452638
* Version Independent ID: abda21d9-6e80-8319-c56f-004658014e3c
* Content: [Enable single sign-on for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)
* Content Source: [docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/sso-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mattgeim** [comment]
Unfortunately we don't have a timeline to share for general availability of the SSO APIs, but we are actively working to accomplish this in the near future.  If you have any specific issues with API please feel free to re-open this issue or start a new one so we can address them.
