### ISSUE TITLE
Something went wrong and we couldn't start this add-in

### ISSUE THREAD

**Issue by lukchen** [OfficeDev/office-js#1165]
Cant load addin in Excel Online's TaskPane when it loads fine in local Excel

## Expected Behavior

AddIn should work in TaskPane of Excel Online

## Current Behavior

First few seconds, there is a green spinner on top of AddIn page:
![image](https://user-images.githubusercontent.com/26646767/81760546-7f991c00-9495-11ea-8339-9d740a415a14.png)
Few seconds later I got this:
![image](https://user-images.githubusercontent.com/26646767/81760590-9b9cbd80-9495-11ea-842b-b196032602f9.png)

Windows 10, Excel Online, Chrome

**Comment by lukchen** [comment]
After I click RETRY, I got this:
![image](https://user-images.githubusercontent.com/26646767/81760676-e0285900-9495-11ea-8b4b-7db3a637688f.png)

**Comment by lumine2008** [comment]
Could you please share a bit more about the repro steps? We would like to repro in our side to locate the issue.

could you try to use open developer tool (F12) of the browser, see if there will be an error message in the console.

**Comment by lukchen** [comment]
> Could you please share a bit more about the repro steps? We would like to repro in our side to locate the issue.
> 
> could you try to use open developer tool (F12) of the browser, see if there will be an error message in the console.

This is the server link: https://elimwcloudtest.com/signin/

**Comment by lukchen** [comment]
I found out the problem
