### ISSUE TITLE
Can't set Excel.ChartBorder.lineStyle to "None"

### ISSUE THREAD

**Issue by wwy94621** [OfficeDev/office-js#1166]
Want to hide the border of a chart, but it doesn't working
## Expected Behavior

I'm working on a fucntion to hide a chart's border.
## Current Behavior

When I set the border's lineStyle to "None", office.js will through a exception. I trid other option like "Dash", "Dot", all of them is fine.
## Steps to Reproduce, or Live Example

* Additional details:
  1.open the Script Lab
  2.find the "Title format" sample
  3. change the code as below:
async function changeTitleFormat() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getItem("Sample");
    const title = sheet.charts.getItemAt(0).title;
    title.format.fill.setSolidColor("SkyBlue");
    title.format.border.lineStyle = "None";//change from Dash to None

    await context.sync();
  });
}
4.run it
5.click "add sample data"
6.click "Change title format", you'll get the error message as below:

![error](https://user-images.githubusercontent.com/15881207/81792268-6bf3c100-953a-11ea-832d-204d2125081b.PNG)

**Comment by lumine2008** [comment]
Thanks, i can repro this issue, let me follow up with the team, a bug(4157294) just created for tracking this issue

**Comment by lumine2008** [comment]
Hi @wwy94621 , i would like to share an update: This issue has been fixed in build 16.0.13015.10000, would you please verify it, thanks.

**Comment by wwy94621** [comment]
> Hi @wwy94621 , i would like to share an update: This issue has been fixed in build 16.0.13015.10000, would you please verify it, thanks.

My office 365 can only update to 16.0.12827.20200, will check it once I upgrade to 16.0.13015.10000
Many thanks

**Comment by lumine2008** [comment]
This bug was fixed, kindly verify

**Comment by wwy94621** [comment]
got it, thanks!
