### ISSUE TITLE
sheet.getRanges requires localized address instead of language neutral

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js#1167]
The calls should be unified across whole API and it should not require localizing its parts.

## Expected Behavior

It should be possible to call getRanges method with language neutral address, i.e. in case of multiple areas the call should look like this:
` let range = sheet.getRanges("B7:C7,G10");` 
The reason is that it is not possible to work correctly on various environments + other calls to office.js API return the range addresses using language neutral separator.

## Current Behavior

Currently this method must be called using locale specific argument/list separator, e.g. with Czech or German settings the call looks like this
` let range = sheet.getRanges("B7:C7;G10");` 
## Steps to Reproduce, or Live Example

Use the gist:
https://gist.github.com/4tti/5c91dace4723e6f1b7c46878dc79ea72
When working with non standard environment (e.g. German) 'Working' button will work fine, but 'NotWorking' button will log error.
In standard environment it will be vice versa (and expected).

## Your Environment

Windows, Desktop Excel (Microsoft 365), Version 2004 (build 12730.20250)

**Comment by lumine2008** [comment]
Thanks @4tti , I can repro this issue. A bug (4160381) is created to track this issue

**Comment by erharvey** [comment]
Hello,

Is there a workaround for this? I.E a way to get the list separator in order to feed the "join" below?
(The same way we can get decimalseparator from cultureInfo?)


        var rowsAreaAddress = ranges.map(function (range) { return range.address }).join(",");
        var rowsArea = sheet.getRanges(rowsAreaAddress);


        //Reapply column formatting
        renderColumnsFormatting(entitiesTable, viewModel, rowsArea);

        //Reapply row formatting
        renderRowsFormatting(entitiesTable, updatedEntities);

**Comment by 4tti** [comment]
Hello.
It can but the issue is that other API calls retrieve it in language neutral format, i.e. you will get address of selected range like 'A1:A5,B3' but getRanges will throw error if you try this.
That said, you would need to have proper parser + it means some performance overhead.

**Comment by erharvey** [comment]
Hi 4tti,

Yes I have the exact same issue as you since I have to consider more than just the English language.

For the moment, I am using the following code get the system **listSeparator** and feed the above code in order to use getRanges. (There is no way to get it directly as far as I know of?)

   var rowsAreaAddress = ranges.map(function (range) { return range.address }).join(**listSeparator**);

    var listSeparator = ",";
    Excel.run({ delayForCellEdit: true }, function (ctx) {
                var sheet = ctx.workbook.worksheets.getActiveWorksheet();
                sheet.getRanges("A1,B1");
                return ctx.sync();
            }).catch(function (error) {
                listSeparator = ";";
            });

Hopefully, there is a better temporary solution than this until the bug is fixed. Please advise.

**Comment by lumine2008** [comment]
We enhanced getRanges API, would you please validate? thanks.

**Comment by 4tti** [comment]
Confirmed it is working.
Thanks @lumine2008, good job!
