### ISSUE TITLE
Office.context.mailbox.item is undefined in Outlook Online

### ISSUE THREAD

**Issue by mpk** [OfficeDev/office-js#1168]
## Expected Behavior
`Office.context.mailbox.item` should contain selected email data

## Current Behavior
`Office.context.mailbox.item` is undefined

## Steps to Reproduce
- Select an email, open an add-in
- Close the add-in, go to next email, open the add-in again

## Context
I develop an add-in for Outlook that connects email data with a CRM. During this week, an error starts to occur while opening the add-in in some email accounts (I was able to reproduce it in two of three tested Outlook accounts).

It seems that Outlook telemetry throws an error during its initialization (see the first screenshot), which in turn causes error 9020 to be returned to my add-in (second screenshot). The telemetry error is always present if `Office.context.mailbox.item` is undefined.

I have not done any changes to the add-in for some time, so I think this might be caused by a recent Outlook Online update.

## Your Environment
* Platform: Office Online
* Host: Outlook
* Office version number: 16.0.10908.10000
* Operating System: Windows 10
* Browser: Chrome 81.0.4044.138

## Useful logs

![Annotation 2020-05-15 144148](https://user-images.githubusercontent.com/2478254/82051758-c451cc80-96ba-11ea-9931-6d6df1dc3e42.png)

![Annotation 2020-05-15 144333](https://user-images.githubusercontent.com/2478254/82051760-c6b42680-96ba-11ea-95ba-5dd5b1f5aaed.png)

**Comment by fkranenburg** [comment]
See issue #1134. We see the same issues with our crm add-in.

**Comment by mpk** [comment]
@AbidRahman-MSFT Are you sure this is a duplicate? The issue #1134 describes problems while add-in is pinned (I don't use it) and also throws different JS error.

**Comment by AbidRahman-MSFT** [comment]
Reopening. @exextoc , can you provide more information on if this is a duplicate issue of #1134 ?

**Comment by exextoc** [comment]
Not able to reproduce the bug. 
- Is the bug consistent for you ? Does it reproduce every-time you perform the specified repro steps ?
- Is the bug across browsers or Just chrome ?
- Have you been seeing the error for a specific add-in or happens for any given add-in ?

**Comment by mpk** [comment]
@exextoc 
- Yes, I can reproduce this bug consistently, but only on some email accounts (one is working fine, one has this problem). However, this week the error message is slightly different (`'isAddinPinned' of undefined` instead of `'mode' of undefined`), as you can see in the screenshot.
- Bug is present at least in Chrome and Firefox (both browsers without any extensions)
- All add-ins that access `Office.context.mailbox.item` triggers this error. For example, Microsoft's own OneNote add-in has the same problem (see screenshot).

![image](https://user-images.githubusercontent.com/2478254/82448101-93520d00-9aa9-11ea-8111-6762513598b7.png)

**Comment by exextoc** [comment]
We aren't able to reproduce the issue. Can you please provide a test account where the same is reproducible ?

**Comment by mpk** [comment]
I'm also unable to reproduce this issue anymore.

**Comment by ghost** [comment]
@exextoc  I have the same issue `Office.context.mailbox.item is undefined`. 

The demo: https://d.pr/v/AD4WUG

I've newly created accout with three drafts inside it. When I switch between drafts and open a plugin  on every draft I see the above error after some time

In order to reproduce you can use this test account:
demo00x@outlook.com
1234567890QWErty

**Comment by ndvbd** [comment]
Same issue here
