### ISSUE TITLE
OneDrive shared link is invisible in OWA

### ISSUE THREAD

**Issue by markb-trustifi** [OfficeDev/office-js#1171]
When sending email with OneDrive shared link from OWA in browser to other outlook account and opening it in OWA the shared link becomes invisible because of the internal style:
`<style type="text/css">#OwaReferenceAttachments{display:none}</style>`

The shared link is still visible when opening email in Outlook desktop client or when sending it from Outlook desktop client.

## Expected Behavior
See OneDrive shared link.

## Current Behavior
OneDrive shared link is invisible.

## Steps to Reproduce, or Live Example
- open OWA in browser
- attach file from OneDrive as a shared link
- send email to other Outlook account
- open email in OWA in browser - **the link is absent**
- open email in Desktop Client - **the link exists**

## Your Environment
* Platform: MAC+OWA
* Office version number: 365
* Operating System: MAC 10.14.6
* Browser (if using Office Online): Chrome 81

**Comment by exextoc** [comment]
Can you please share a screenshot of the issue and the way you are trying to share the link ?

**Comment by markb-trustifi** [comment]
- Login to Outlook account in browser
- Compose new email
- Attach 
- Browse cloud locations
- Select document from OneDrive
- Share as OneDrive link

**Comment by exextoc** [comment]
@markb-trustifi We are not able to reproduce the issue on our end, it would be really helpful, if you can share recording/screenshot.

**Comment by markb-trustifi** [comment]
> @markb-trustifi We are not able to reproduce the issue on our end, it would be really helpful, if you can share recording/screenshot.

Yes, sure. I'll send the recorded video. Just give me your private email.

P.S. I updated the issue. The problem occurs when the email is created in OWA and opened in OWA.

**Comment by exextoc** [comment]
Please send it to meganb@m365x443023.onmicrosoft.com.

**Comment by markb-trustifi** [comment]
I cannot reproduce it now.
