### ISSUE TITLE
Setting message headers throws an error

### ISSUE THREAD

**Issue by Warsame-Egal** [OfficeDev/office-js#1172]
## Expected Behavior
X Headers Message headers should be set without errors in pop out window.

## Current Behavior
Trying to set message headers throws an error

## Steps to Reproduce, or Live Example
Opening a new window
-	Create a new email
-	Click on open a new window icon on the top right of the composed email
![pop](https://user-images.githubusercontent.com/8644484/82369049-6be53c80-99e4-11ea-8fdd-26c4ccaedbb6.PNG)
-	Launch addin
-	Try to set message headers in compose mode (message edit)
-	Error is thrown: (The Exchange server returned an error. Please look at the diagnostics object for more information.","code":9042)
-	Same scenario works if message is not opened in pop-out dialog.

## Context
X Headers are set using the following, these are examples from the Microsoft docs: 
[The X Headers are set using the following, these are examples from the Microsoft docs: ](url)

    `<script>
            Office.onReady(function () {
                console.log(Office.context.mailbox.diagnostics.hostName);
                setCustomHeaders();
            });

        function setCustomHeaders() {
            Office.context.mailbox.item.internetHeaders.setAsync(
                { "x-preferred-fruit": "orange", "x-preferred-vegetable": "broccoli", "x-best-vegetable": "spinach" },
                setCallback
            );
        }

        function setCallback(asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
                console.log("Successfully set headers");
            } else {
                console.log("Error setting headers: " + JSON.stringify(asyncResult.error));
            }
        }

        setCustomHeaders();

    </script>
`

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Windows
* Browser (if using Office Online): Microsoft Edge, google chrome

console log errors:
![try](https://user-images.githubusercontent.com/8644484/82369483-15c4c900-99e5-11ea-9001-14e0506e84e7.PNG)

asyncResult Object:
![asy](https://user-images.githubusercontent.com/8644484/82370075-f67a6b80-99e5-11ea-9999-56a69ac7a6b0.PNG)

error Object:
![er2](https://user-images.githubusercontent.com/8644484/82369532-2a08c600-99e5-11ea-9313-b8ddbb0257f1.PNG)

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
We have fixed this issue and it will be rolled out 100% by end of this week.

**Comment by nikhileshcs** [comment]
@exextoc Facing few more issues 

**Environment**
Platform : Mac
Host : Outlook Desktop Version

Current Outlook Version in use:
![Screenshot 2020-06-25 at 9 52 27 PM](https://user-images.githubusercontent.com/14127053/85758728-35f74e80-b72e-11ea-9cec-7fb28487d2fe.png)

Permission Set: `<Permissions>ReadWriteMailbox</Permissions>`

```
Office.context.mailbox.item.internetHeaders.setAsync({
                'x-cmessage-id': 'value1@xxxxw.cv'
            }, (result) => {
                debugger;
            });
```
callback is receiving error: **Internal Error with code as 5001**

<img width="510" alt="Screenshot 2020-06-25 at 9 49 09 PM" src="https://user-images.githubusercontent.com/14127053/85758307-d26d2100-b72d-11ea-824c-f87afcbf5578.png">

It is working fine in the Online version on chrome browser
![Screenshot 2020-06-25 at 10 51 21 PM](https://user-images.githubusercontent.com/14127053/85768331-88d50400-b736-11ea-9532-4906aa654149.png)


Any particular steps we need to follow to debug this further or Is it a Bug?

**Comment by nikhileshcs** [comment]
@lindalu-MSFT Any reason for closing this issue? Do i need to open a new issue? 

I see the above error mentioned by me is valid and it is reproducible easily in Mac Systems Outlook Desktop Version.

**Comment by nikhileshcs** [comment]
I've raised a new issue for this. Thank you

[Error while setting Internet Headers on ComposeItem - Outlook #1242](https://github.com/OfficeDev/office-js/issues/1242)

**Comment by lindalu-MSFT** [comment]
@nikhileshcs This was closed because the outlook engineering team tagged as FIXED. They noted that it will take a week to roll out the fix.

**Comment by nikhileshcs** [comment]
@lindalu-MSFT @exextoc The issue mentioned by me and the earlier reported are different. Can you please ask outlook engineering team to look into this?
