### ISSUE TITLE
Word bindings become intermittently unreachable using Office.context.document.bindings.getByIdAsync

### ISSUE THREAD

**Issue by amelehy** [OfficeDev/office-js#1173]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When creating a binding from the user's current selection in a document, setting a value for that binding, and then attempting to retrieve the value for that same binding, we see intermittent "disappearance" of that binding and Office JS throws a `General Exception` error. 

We've seen this behavior in other minor versions of Word in the past (1-2 years ago), but it has seemed to show up less frequently as of late (assuming because of updates to Office JS). This issue is now happening again and we've isolated it to O365 Word within Citrix Workspace (more info below).

## Expected Behavior

We expect that after creating a binding from the user's current cursor selection:
```javascript
Office.context.document.bindings.addFromSelectionAsync(Office.BindingType.Text, {id: <ID>}, callback);
```
And after setting a value for that binding:
```javascript
const getBindingForId = (id) => {
    let officeBindings = Office.context.document.bindings;
    return new Promise((resolve) => {
      officeBindings.getByIdAsync(id, resolve);
    }).catch(e => console.error(e));
}
const binding = await getBindingForId(bindingId);
binding.value.setDataAsync( value, { coercionType: 'text' }, callback);
```
That we should then reliably be able to retrieve the value of that binding using:
```javascript
Office.context.document.bindings.getByIdAsync(id, callback)
```

## Current Behavior

Our add-in inserts a binding at the user's current selection, sets a value for that binding, and then attempts to retrieve the value of that binding. We're seeing that after inserting a binding, this binding becomes unreachable via the ID that is specified on creation and Office JS returns: 
```javascript
An internal error has occurred. {"status":"failed","error":{"name":"Internal Error","message":"An internal error has occurred.","code":5001}}
```
Creating a binding, setting it's value, and then attempting to retrieve the bindings' value causes Office JS to throw an error:
```javascript
GeneralException: An internal error has occurred.
```

## Steps to Reproduce, or Live Example

1. Must be within the Word version and environment mentioned below 
2. Enter some text in the Word document
3. Select that text with your cursor
4. Set up a dummy button to run the following code:
```javascript
// Create the binding
const ID = "3d2d1732-8784-4819-a365-ca062e4954c6";
const addBindingFromSelection = (type) => {
    return new Promise((resolve) => {
        Office.context.document.bindings.addFromSelectionAsync(type, {
            id: ID
        }, resolve);
    }).catch(e => console.error(e));
}
const asyncResultCreateBinding = await addBindingFromSelection(
    Office.BindingType.Text
);
// Creating a binding from the current selection failed
if (asyncResultCreateBinding.status !== 'succeeded') console.error(asyncResultCreateBinding);


// Set the binding's value
const getBindingForId = (id) => {
    let officeBindings = Office.context.document.bindings;
    return new Promise((resolve) => {
      officeBindings.getByIdAsync(id, resolve);
    }).catch(e => console.error(e));
}
const binding = await getBindingForId(ID);
binding.value.setDataAsync( "test", { coercionType: 'text' }, (r) => console.log("done"));


// Retrieve the binding's value
const binding = await this.getBindingForId(ID);
if (!binding.value) console.error(`Failed to find binding with bindingId ${bindingId}.`)
```
## Context

One of our customers is currently running O365 Word within Citrix Workspace (more details below) and is running our Add-in within that instance of Word. What we/they are seeing is unpredictable "disappearances" of bindings within a document (i.e. they become programmatically unreachable).

FWIW we've seen this behavior in other minor versions of Word in the past (1-2 years ago), but it has seemed to show up less frequently since (assuming because of updates to Office JS). 

Is it possible that additional add-ins that this customer has running are interfering with our add-in's functionality and/or Office JS?

## Your Environment

* Platform: PC desktop
* Host: Word
* Office version number: Microsoft Word for Office 365 MSO (16.0.11929.20762) 32-bit
* Operating System: Windows 10
* Citrix Workspace: Version: 20.02.0.5 (2002)
* Citrix Viewer: Version: 20.02.0.5 (2002)

## Useful logs

<img width="816" alt="Screen Shot 2020-05-19 at 6 54 35 PM" src="https://user-images.githubusercontent.com/3266420/82396222-38190f80-9a02-11ea-90f6-b440d6f4e88d.png">
<img width="989" alt="Screen Shot 2020-05-19 at 6 52 56 PM" src="https://user-images.githubusercontent.com/3266420/82396227-3a7b6980-9a02-11ea-914a-770b20d6abf7.png">
<img width="770" alt="Screen Shot 2020-05-19 at 6 52 12 PM" src="https://user-images.githubusercontent.com/3266420/82396229-3a7b6980-9a02-11ea-9073-c8d77d0cdf9b.png">

**Comment by amelehy** [comment]
Hi @weshi, saw that you were assigned to this issue, thanks a ton for looking into it. Any progress on your end?

**Comment by hjkim-MSFT** [comment]
Hi @amelehy, 

Thanks for reporting the issue. Would you please elaborate a little more on Citrix Workspace? We Microsoft couldn't repro the problem you mentioned as of Build 12527.20612 - Insiders release.

Thank you.

**Comment by amelehy** [comment]
Apologies for the delay @hjkim71. I've gathered some more details about the environment. The client is using a "Cloud Desktop" service called ProZone via this IT firm: https://www.procirrus.com/

When launching Word from within ProZone, Citrix viewer is launched (details in the attached screenshot). Are there other specific details that would be helpful to know?
<img width="312" alt="Screen Shot 2020-06-23 at 8 55 42 PM" src="https://user-images.githubusercontent.com/3266420/85498373-6acf9e00-b594-11ea-898d-3bd71b25a889.png">
