### ISSUE TITLE
[Content Addin] getFilePropertiesAsync call succeeds but empty path is returned for Excel Online

### ISSUE THREAD

**Issue by sajsarka** [OfficeDev/office-js#1176]
## Expected Behavior

getFilePropertiesAsync should return valid path of file when succeeded.

## Current Behavior

Call succeeds but empty path is returned.

## Steps to Reproduce, or Live Example

Not able to repro. But we are seeing such failures in our telemetry.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.12918.35052

## Useful logs

**Comment by lumine2008** [comment]
@sajsarka , would you please share a bit more information? we would like to locate the issue if there is no reproducible in our side.

**Comment by sajsarka** [comment]
@lumine2008 When we try to debug or try to do a local repro, not seeing this issue. But in our telemetry we are seeing such failures for 0.2% of our sessions.
Is it possible to check for logs for this API?

**Comment by MandytMSFT** [comment]
@sajsarka could you provide us the sessionID that encounter the issue, then we can have a try to see if any clues in logs.
