### ISSUE TITLE
PowerPoint.createPresentation(base64) not working on PowerPoint iPad

### ISSUE THREAD

**Issue by qqytqqyt** [OfficeDev/office-js#1177]
## Expected Behavior

If we execute "PowerPoint.createPresentation(base64)", we should be able to open the PowerPoint from the given base64 on PowerPoint iPad.

## Current Behavior

There was an issue #432 where PowerPoint.createPresentation(base64) did not work on PowerPoint online which has been fixed. Now with Office desktop, Office Online, Office Mac, executing this line would open a new PowerPoint application window from the base64 file.

However, this issue appeared to still happen on PowerPoint iPad that nothing happened after executing the line.

## Steps to Reproduce, or Live Example

PowerPoint.createPresentation('UEsDBBQABgAIAAAAIQDfzBj1r.......');

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: iOS
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: 2.37

**Comment by MandytMSFT** [comment]
@qqytqqyt thanks for reporting. I can repro and BUG 4178204 is opened to track internally

**Comment by robertmuehsig** [comment]
Any updates on this? We are seeing the same issue - works fine on Windows, Web & mac :/

**Comment by julio177** [comment]
Checking on this, are you still seeing this issue? @qqytqqyt

**Comment by AbidRahman-MSFT** [comment]
Closing the issue as stale. Please re-open if the issue persists. Thanks.

**Comment by SkopinGroup** [comment]
We still have this issue on the iPad, version 2.74 (23060901).
