### ISSUE TITLE
Insert Html <pre> element does not work in OfficeOnline .

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#1178]
When inserting some Preformatted text like this:
<pre>
  L          TE
    A       A
      C    V
       R A
       DOU
       LOU
      REUSE
      QUE TU
      PORTES
    ET QUI T'
    ORNE O CI
     VILISÉ
    OTE-  TU VEUX
     LA    BIEN
    SI      RESPI
            RER       - Apollinaire
</pre>

## Expected Behavior
In OfficeOnline, it should insert correctly.

## Current Behavior
Works well with
- Word app on Windows, Macos, Ios
![1 1](https://user-images.githubusercontent.com/13063615/82631914-f1553080-9c20-11ea-80d3-40e921ee821b.PNG)
![1 2](https://user-images.githubusercontent.com/13063615/82631917-f3b78a80-9c20-11ea-981d-143f9b19faa3.PNG)

- Not work with WordOnline
 
![1 4](https://user-images.githubusercontent.com/13063615/82631879-da164300-9c20-11ea-8e6f-07c58b52fdd9.PNG)

## Steps to Reproduce, or Live Example
Scriptlab: [https://gist.github.com/jasonhieu1905/8fc253867df274573b29cc5f096eae52](https://gist.github.com/jasonhieu1905/8fc253867df274573b29cc5f096eae52)

## Your Environment

* Platform: Office Online
* Host : Word
* Operating System: Windows, Mac
* Browser (if using Office Online): Chrome

## Useful logs
No errors in console log.

**Comment by MandytMSFT** [comment]
@jasonhieu1905  thanks for reporting. I just tried copy/paste the paragraph with  pre on word online directly, it also can not show correctly as well. so that's an issue of word online and expected behavior for API. Pls contact word online team by feedback to report this issue. 

![image](https://user-images.githubusercontent.com/52641972/82868719-b3794480-9f5f-11ea-86b9-5916c7a8d1f7.png)

**Comment by weshi** [comment]
This is a known limitation in Word on the Web that the pre format is not honored. Even when you copy/paste it from the UI, the same behavior is observed.

**Comment by JuaneloJuanelo** [comment]
@jasonhieu1905  we recommend to add this as a feature request in our [uservoice ](https://officespdev.uservoice.com/)channel, for the time being, we can track it there. thanks.
