### ISSUE TITLE
Access Office.context.document.settings on server

### ISSUE THREAD

**Issue by engage-deepakagarwal** [OfficeDev/office-js#1179]
Hi,
I am using office.js and saving some settings as key-value pairs described in your article using Office.context.document.settings API. 
Now, the complete fileBytes are transferred to the server and I need to read this settings in C# .net to take further actions. However, I am not able to find those custom settings. I am using WordprocessingDocument class of  DocumentFormat.OpenXml.Packaging to read it on server side. 

What am I missing here? Can you give me a short working example on how to do accomplish this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b683480b-a4fe-97ba-64f9-45ecfe829bf4
* Version Independent ID: a0993174-18dd-9594-9c3c-102d078e2217
* Content: [Persisting add-in state and settings - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings#feedback)
* Content Source: [docs/develop/persisting-add-in-state-and-settings.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/persisting-add-in-state-and-settings.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by MandytMSFT** [comment]
@deeagar  Could you provide more information to help us triage the issue on below questions? 

Which host is your addin targeting on? Word/Excel/outlook or others ?

Which platform ? Desktop / Online/Mac/iOS ?
