### ISSUE TITLE
Is there any support for running the back-end locally?

### ISSUE THREAD

**Issue by rgwood** [OfficeDev/office-js#1180]
This document discusses calling a .NET back-end hosted on Azure. Do you provide any support for shipping a _local_ .NET back-end with an Office add-in?

We need to keep data on the user's machine for confidentiality reasons, we can't send user data to a cloud back-end for processing. My understanding is that Office Add-ins do not provide any support for deploying local back-ends, so we'd need to handle deployment+updating of the back-end separately from the Office add-in. Is that correct?

This is currently blocking us from migrating away from VSTO.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e750012-89a3-3471-06e8-e1410d10568c
* Version Independent ID: 560869f0-c785-56ac-cb4e-94f14d350f2c
* Content: [Tutorial: Share code between both a VSTO Add-in and an Office add-in by using a shared code library - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/migrate-vsto-to-office-add-in-shared-code-library-tutorial#feedback)
* Content Source: [docs/tutorials/migrate-vsto-to-office-add-in-shared-code-library-tutorial.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/migrate-vsto-to-office-add-in-shared-code-library-tutorial.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by mscharlock** [comment]
@sumurthy & @smaremanda - can you look at this question above?

**Comment by stephenegriffin** [comment]
@rgwood There's no need to send any data back to your server if you don't want to. For an example, see [MHA](https://github.com/stephenegriffin/MHA). All processing is local to the client,

**Comment by ElizabethSamuel-MSFT** [comment]
Removing mscharlock. @slabereemsft Any update on this? Thanks.

**Comment by rgwood** [comment]
FWIW I'm happy to close this. I've long since given up on "modern" Office integration; the developer experience for building Office Add-ins is a nightmare and I literally quit a job to get away from it. I would recommend that anyone reading this for professional reasons run far, far away.
