### ISSUE TITLE
Development in linux environments

### ISSUE THREAD

**Issue by hmartiins** [OfficeDev/office-js#1181]
## Current Behavior

When I follow the tutorial at https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator, in Create your first Word task pane add-in, when I arrive at the step of running npm run start: web it returns the following error:

> office-addin-taskpane-js@0.0.1 start: web / home / henrique / Desktop / wordFormatter / wordFormatter
> office-addin-debugging start manifest.xml web

Debugging is being started ...
App type: web
Unable to start the dev server. office-addin-dev-certs: Platform not supported: linux
Debugging started.

Saying that the platform is not supported for linux. I am using version 20.04 of Ubuntu, I would like to know if it is possible to develop for it, or will I have to use a windows virtual machine to be able to carry out the development?

## Steps to Reproduce, or Live Example

* Additional details:
  1. follow the tutorial from https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/word-tutorial
  2. Be in linux environment
  3. Run npm run start: web

## Context
This problem affected me because my main development environment is linux. If I have to change OS to be able to use this tool, it will delay the development of my project, because besides having to configure a VM with windows, or perform a dual boot with windows, I will have to configure my entire development environment again

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop. office online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: Ubuntu 20.04
* Browser (if using Office Online): Google Chrome

**Comment by ElizabethSamuel-MSFT** [comment]
@hmartiins Thanks for asking about this.

@slabereemsft @mattgeim This seems like a DevX situation. Can you take a look?

Thanks.

**Comment by TCourtneyOwen** [comment]
@hmartiins @slabereemsft @ElizabethSamuel-MSFT @mattgeim 

We don’t support Linux for most DevX operations. If we do opt to start supporting Linux more broadly, we could add support for office-addin-dev-certs, but I don’t envision that happening in the near future. 

If you look at the way we generate dev-certificates [here,](https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/office-add,in-dev-certs/src/generate.ts) we use the mkcert package, which you can use yourself to create certificates and then presumably use our install code [here](https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/office-addin-dev-certs/src/install.ts) to install the certs.  

-Courtney
