### ISSUE TITLE
Excel crashes when user enters edit cell mode during table operations "context.sync"

### ISSUE THREAD

**Issue by erharvey** [OfficeDev/office-js#1183]
Excel crashes (not responding) when a user goes in edit cell mode during long running processes such as multiple table creation with formatting.

The issue seems to occur if the user goes in edit cell mode of an Excel.Run process with app.preventScreen update set to true. It would seems as if the screen doesn't become active again since it fails before doing so.

## Expected Behavior

Excel should never crash due to a user interfering with long running processes (~ 8sec). Ideally, the user wouldn't be able to enter the edit cell mode at all such as one can do using VBA by disabling interactivity. If not, Excel should at least throw the "cell edit mode exception" instead of crashing.

## Current Behavior

Excel crashes/deadlocks  and becomes "not responding"
![image](https://user-images.githubusercontent.com/17800696/82850897-13bea680-9ecc-11ea-824d-1e80fb766342.png)

## Steps to Reproduce, or Live Example

1- In a loop with 8 iteration
2- Set prevent screen update to true
2- Create a table with 120 columns with values "aaaa"
3 - Iterate each column to change the formatting to 0.000 (not the whole table in a batch, in my case the formatting is not the same for each column)
4- Delete the table
5- sync

During the creation of the 8 tables, spam edit cell.

## Context
Our plugin contains a refresh button that reload data from a backend database on each table currently in the excel worksheets. The ideal scenario would be that the user wouldn't be able to interact with the sheet. ( Without using "protection selection mode" since this mode doesn't allow the creation of tables)

## Your Environment

Windows 10
build 2004 (Excel on-prem)

**Comment by lumine2008** [comment]
Thanks @erharvey for reporting this issue to us, 
it would be super helpful that you could provide a script lab gist. therefore we can have a local repro to locate the issue. 
here is a screenshot how to share a gist in scriptlab. thanks in advance.
![image](https://user-images.githubusercontent.com/26398035/82920775-4dfe7580-9faa-11ea-98f2-7a76f0bfac49.png)
