### ISSUE TITLE
[Outlook ] on chrome Outlook online Office.CustomProperties not work on shared calendar

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1185]
I run Office.CustomProperties on a shared calendar(outlook online). 
But actually this function not work at all.

PS: I remember this function is working several month ago. Is there any update about this?

## Expected Behavior
Office.CustomProperties works on shared calendar.

## Current Behavior
saveAsync is done but just can't read any thing from properties.

## Steps to Reproduce, or Live Example
open add-in, then use:
Office.context.mailbox.item.loadCustomPropertiesAsync(function (result){
                    result.value.set("test",{"test":"success"});
                    result.value.saveAsync(function () {
                    console.log("done");
                });
                });
save some data, and after this use:
Office.context.mailbox.item.loadCustomPropertiesAsync(function (result){
                    console.log(result);
                });
to read data. But got nothing

## Context

Our add-in can't work normal on shared calendar.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online  
(I only test this on browser but other platform might have same problem.I will reply the result later)
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows 10
* Browser (if using Office Online): Chrome/ EDGE

**Comment by exextoc** [comment]
Are you using outlook.com account or Office365 Enterprise account?

**Comment by exextoc** [comment]
We are not able to reproduce this with the given code. 

1. What permission did you use when sharing calendar with delegate? When sharing calendar we get options like: "Can view all details", "Can view titles and locations", "Can view all details", etc.

2. When you say, CustomProperties does not work - do you mean you get API callback, it result is empty? Is asyncResult error code "success"? Can you please share with us output of "asyncResult" from this call?

**Comment by SWei1234** [comment]
> Are you using outlook.com account or Office365 Enterprise account?

Yes

**Comment by SWei1234** [comment]
> We are not able to reproduce this with the given code.
> 
> 1. What permission did you use when sharing calendar with delegate? When sharing calendar we get options like: "Can view all details", "Can view titles and locations", "Can view all details", etc.
> 2. When you say, CustomProperties does not work - do you mean you get API callback, it result is empty? Is asyncResult error code "success"? Can you please share with us output of "asyncResult" from this call?

Sure, I will record this and paste here later. If necessary we can have a meeting.

**Comment by SWei1234** [comment]
@exextoc Here is the problem recording. And this is easy to reproduce. Please try this.
[trouble_shooting_recording.zip](https://github.com/OfficeDev/office-js/files/4714295/trouble_shooting_recording.zip)

**Comment by SWei1234** [comment]
@exextoc Just want to confirm is there any update?

**Comment by SWei1234** [comment]
@exextoc This problem only happened on Chrome online Outlook. 
For windows: 83.0.4103.61 (64 bit)
For Mac: Version 83.0.4103.61 (64 bit)
Can you help us confirm why chrome will have this issue on outlook online?

**Comment by exextoc** [comment]
So this problem you are facing with Desktop versions as well? I tried in edge multiple times, I was not able to repro. I will try with chrome and keep you updated.

UPD: I tried with chrome(Version 83.0.4103.97) as well and was not able to repro this issue. Can you please share some test account?

**Comment by SWei1234** [comment]
Now I know how to reproduce this problem : 
 If I add this shared calendar under 'My calendars' ,  customer properties can be get correctly.
But if add shared calendar to 'People's calendars' ,  customer properties is just empty. 
This problem only happening on browser, Outlook client desktop is working fine. 
 (I tried chrome version 83.0.4103.97 but still the same phenomenon).
I just tried call loadCustomPropertiesAsync on dev-Tool. But if  still can't reproduce this problem I can share my screen on a trouble shooting meeting with zoom or teams.
Thanks

**Comment by exextoc** [comment]
@SWei1234 Can you try below snippet and share the result with us? We are trying to verify whether the set function even succeeded.

    Office.context.mailbox.item.loadCustomPropertiesAsync(function (result){
      result.value.set("test",{"test":"success"});
      result.value.saveAsync(function (result) {
         console.log(result);
      });
    });

**Comment by SWei1234** [comment]
@exextoc 
Sure, 
![Untitled](https://user-images.githubusercontent.com/15980696/84363779-c8adce80-ac01-11ea-8522-dd4e35a96fda.png)

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding custom properties issues. It has been put on our backlog. We unfortunately have no timelines to share at this point.
