### ISSUE TITLE
Unable to control/adjust window size when multiple widows are opened in task pane

### ISSUE THREAD

**Issue by rvskrishnaprasad** [OfficeDev/office-js#1186]
## Expected Behavior
Able to control/adjust window height depending on the need when multiple windows are opened in the task pane.

## Current Behavior
Window height is getting increased automatically when multiple windows are opened in task pane, we are unable to adjust the window height as it is read-only, due to which controls at bottom (footer part) are not displaying for the user.

<img width="959" alt="Issue" src="https://user-images.githubusercontent.com/65659523/82907678-8ab77600-9f84-11ea-8779-729785ec9012.png">

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lliu113** [comment]
@rvskrishnaprasad  - sorry for the delay. Is the issue here that adding an additional taskpane adds a footer to the taskpane box? Are you able to share a screenshot which shows the footer? I'm unable to repro it on my side. 

Thanks!

**Comment by lliu113** [comment]
@rvskrishnaprasad - I'm going to go ahead and close the issue for now. If this is still an issue, please reactivate with the extra information if possible, thank you!
