### ISSUE TITLE
Show and hide the task pane - Visual Studio Web AddIn

### ISSUE THREAD

**Issue by jnSWPC** [OfficeDev/office-js#1187]
**Problem:** - Test show/hide taskpane feature available as part of office preview api - https://docs.microsoft.com/en-us/office/dev/add-ins/excel/show-hide-add-in from Visual Studio Excel WebAdd-In project

**Help Needed** - Sample Visual Studio project referencing office preview api to show/ hide taskpane.

**Details:** 

1. Created a Excel Web AddIn in Visual Studio 2017. Referenced the https://appsforoffice.microsoft.com/lib/beta/hosted/office.js

Version of Office installed is 
![image](https://user-images.githubusercontent.com/22331494/82939669-48c50a80-9f59-11ea-843c-dd532d9c1c47.png)

2. Updated Manifest XML to include :   
  
![image](https://user-images.githubusercontent.com/22331494/82939264-bb81b600-9f58-11ea-98c7-120d832c70e4.png)

    Added 2 buttons to show and hide task pane with associated ExecuteFunction tag

3. Added implementation for the functions in function.js
![image](https://user-images.githubusercontent.com/22331494/82939108-73629380-9f58-11ea-9155-9e02aaddbbec.png)

4. See the above error.

**Comment by yihuax-msft** [comment]
@jnSWPC, Do you still have this issue? Thanks.

**Comment by AbidRahman-MSFT** [comment]
Closing the issue as stale. Please re-open if you continue to face these issues. Thanks.
