### ISSUE TITLE
HELP! remove - Build your first Word task pane add-in

### ISSUE THREAD

**Issue by Kindyr** [OfficeDev/office-js#1188]
I used https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=visualstudio to create my first add-in.  Now, I can't seem to make it stop.  Every time I open up a Word Doc, I have "This text was added by using code.This text was added by using code.This text was added by using code." across the page.  

The add-in is not on my add-in list in the Developer tab.  Microsoft's only answer was to completely uninstall Office and reinstall.  That seems kind of burn the whole house down to me.  Does anyone have any suggestions on how to stop this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 77e380a7-6e2e-ada8-d297-3fd5018a1958
* Version Independent ID: f23490e8-6eeb-f2d5-6c94-69e3c9ed83f4
* Content: [Build your first Word task pane add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=visualstudio)
* Content Source: [docs/quickstarts/word-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/quickstarts/word-quickstart.md)
* Product: **word**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by sumurthy** [comment]
I don't know knowledge of how this works. I'm checking with the team on who can address this.

**Comment by sumurthy** [comment]
@Kindyr, after talking to the experts, it looks like the best approach here is to remove the registry key (Assuming this is on Windows OS). The registry key to look at is HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\WEF\developer and there will be sub keys for each add-in. Please try deleting the sub-key and see if this resolves the issue.

**Comment by Kindyr** [comment]
After a long time working on this, we found out that the problem was the lines were saved to the Word Normal Template.  So every time the template was used, the lines were activated.

**Comment by JaieParker** [comment]
Hey All,
I hope this helps someone else too as I had this issue and found that I had the vsto file was still locked into word and I could not get rid of it by restarting the computer
As per below image it seems that the file was being loaded directly from the folder via "file://..Users/........./WordAddIn1.vsto"
[WordIssue1.pdf](https://github.com/OfficeDev/office-js/files/8367440/WordIssue1.pdf)
Deleting the file "file://..Users/........./WordAddIn1.vsto" caused the following error on next word load
[WordIssue2.pdf](https://github.com/OfficeDev/office-js/files/8367470/WordIssue2.pdf)
However future word loads after this do not show any errors and the text "This text was added by using code" is no longer added when I save.
Cheers
Jaie
