### ISSUE TITLE
Wrong Office.context.mailbox.item in Reading Pane mode

### ISSUE THREAD

**Issue by sagarpilkhwal** [OfficeDev/office-js#1189]
If I enable reading pane with "Show on the right" mode and select any email and then open up the MHA add-in (Message Header Analyzer) the 1st email I open up shows up correctly, but when I select another email and again open MHA add-in (Message Header Analyzer), I get the same details of the 1st email I opened up. This continues to happen when I select any other email unless I go to the "Other" email tab from the "Focused" email tab and same issue keeps happening to the "Other" emails tab. 

But this behavior is not observed if I disable the "Reading pane" mode.

P.S: I'm just using MHA add-in as a reference point, my own add-in is behaving the same way.

## Expected Behavior
Upon selecting a new email when "Reading pane" mode is enabled, new email details should be available in _Office.context.mailbox.item_.

## Current Behavior
After selecting first email after the mail box loads up, _Office.context.mailbox.item_ keeps returning the same object of the 1st email we selected after selecting any other email from the email list.

## Your Environment
* Platform : PC desktop 
* Host : Outlook
* Office version number: ______
* Operating System: Windows 10, windows 8.1
* Browser : Edge, Firefox, Chrome
* Reproducible on Outlook.com as well

![Outlook_Web_Reading_Pane](https://user-images.githubusercontent.com/20281013/83107060-14faf980-a0ad-11ea-84cc-22ead04ac496.png)

**Comment by wilcotroost** [comment]
This seems to be the same problem as the one in https://github.com/OfficeDev/office-js/issues/1134

**Comment by exextoc** [comment]
We have added this to our backlog. Unfortunately, we have no timelines to share at this point.

**Comment by exextoc** [comment]
We have fixed this issue and it will take ~1 week for 100% rollout.

**Comment by sagarpilkhwal** [comment]
[#1134](https://github.com/OfficeDev/office-js/issues/1134) seems to be fixed for the reporter of the issue but I still haven't received the update, I will close this ticket once I receive the update and confirm its fixed for me.

**Comment by exextoc** [comment]
@sagarpilkhwal Has the issue been resolved for you? If not, then it's a different issue than the one described in #1134 because the fix for that issue has rolled-out.

**Comment by sagarpilkhwal** [comment]
@exextoc  Yes , I can confirm that this issue is resolved. Thank you...
