### ISSUE TITLE
Exception when inserting a specific document wrapped by a content control in Office Online

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#119]
## Expected Behavior
I have a document with a title and a text. This document should be inserted into a new document wrapped with a content control using the insertFileFromBase64 method.

## Current Behavior
The document is inserted but:

1. An error occurs after insertion 
2. The content control only wraps the title and not the whole inserted file

## Steps to Reproduce, or Live Example
I have an example here with a working file and a broken file. Both are using the same method.

Use this gist repo [Script Lab](https://gist.github.com/barisbikmaz/7b65ade29ef4051ae633a7eb9aa12bbf) and observe the error when trying to insert the broken file.

## Your Environment
* Platform: Office Online
* Host : Word
* Browser (if using Office Online): Chrome

**Comment by JuaneloJuanelo** [comment]
@barisbikmaz we need a bit more detail on this to investigate properly.

questions:

1.  do you have a summary of whats different between those documents?
2. can you describe how you created the working and non-working documents?

one theory we have is that you are using a few attributes that are not supported in Word Online, and having an understanding of how the docs where generated will help a lot to understand this issue.
in the meantime i will mark it as "requires more info"

**Comment by JuaneloJuanelo** [comment]
after further investigation we discovered 2 bugs associated with this issue:

1. 2318752 -  using range.insertFileFromBase64(..).insertContentControl() does not include the entire file  (this is a potential workaround who is also failing) 
2. 2318756 - creating a CC and then inserting a file using cc.insertFileFromBase64(..) incorrectly applies style to CC 

in the process of getting fixed.

**Comment by JuaneloJuanelo** [comment]
used gist to validate this is now working in online. 
https://gist.github.com/JuaneloJuanelo/5cc13aa2163017ae7f094c22cd04907a
