### ISSUE TITLE
Word: Issue with getFileAsync when getting two files

### ISSUE THREAD

**Issue by dula85** [OfficeDev/office-js#1191]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
Thank you for your understanding and continued feedback.

In my code I am getting word file twice as compressed and pdf file type.

## Expected Behavior
To see file size of both compressed and pdf file in console log.

## Current Behavior
It is getting file of type compressed but not pdf file and I couldn't find any error logs. Word desktop is working fine with this code and word online is not working.

## Steps to Reproduce, or Live Example
[ScriptLab](https://gist.github.com/dula85/e2c5c7466a464e49c4c7e11abd85ac34)

## Context
I need to get the file size of the word file(that is the reason I am getting compressed file type) but I want the pdf type file to send to back end.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word(2016)
* Operating System: Windows 10
* Browser (if using Office Online): Chrome

## Useful logs
I have added  console.log in the script lab project and that will help to debug.

**Comment by MandytMSFT** [comment]
@dula85   could you try https://gist.github.com/MandytMSFT/cf2003237fc288c7dc065cb039aea4be 

i adjusted the closeAysnc call to success/fail callback of GetFileAsync, then it works for me

**Comment by dula85** [comment]
@MandytMSFT  https://gist.github.com/MandytMSFT/cf2003237fc288c7dc065cb039aea4be is working for the word files which got one slice. If you use little bit large file, some how it is stopping inside the getSliceAsync. Bellow is the logs I got when I run this for a file which got more than one slice.

Reading compressed type file.

inside the promise getFile for file type: compressed

inside the getFileAsync for file type: compressedResult: succeeded

slice count: "1" for file type: "compressed".

slice index: "0" for file type: "compressed".

inside the getSliceAsync for file type: compressedResult: succeeded

End file type: compressedfile size: 39902

size of compressed type file: "39902".

Reading pdf type file.

inside the promise getFile for file type: pdf

inside the getFileAsync for file type: pdfResult: succeeded

slice count: "2" for file type: "pdf".

slice index: "0" for file type: "pdf".

inside the getSliceAsync for file type: pdfResult: succeeded

slice index: "1" for file type: "pdf".

**Comment by MandytMSFT** [comment]
@dula85 Did you happen to take a look at our sample code [here](https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=word-js-preview#getfileasync-filetype--options--callback- ) about how to use GetFileAsync and getSliceAsync

BTW, I tried documents with more the 2 slices, both compressed and Pdf will fail. So it should not be issue when getting 2 files but about the code you wrote.

**Comment by dula85** [comment]
@MandytMSFT  Will you able to share the output when you are trying for a file which has more than one slice?

I have followed [example in here](https://docs.microsoft.com/en-us/javascript/api/office/office.file?view=word-js-preview#getsliceasync-sliceindex--callback-)

Also in this script lab https://gist.github.com/dula85/e2c5c7466a464e49c4c7e11abd85ac34, if you comment getting compressed file or Pdf file(only get one file) it works. But it is not working for getting two documents.
Output for getting one file:
Reading pdf type file.

inside the promise getFile for file type: pdf

inside the getFileAsync for file type: pdfResult: succeeded

slice count: "2" for file type: "pdf".

slice index: "0" for file type: "pdf".

inside the getSliceAsync for file type: pdfResult: succeeded

slice index: "1" for file type: "pdf".

inside the getSliceAsync for file type: pdfResult: succeeded

End file type: pdffile size: 164794

size of pdf type file: "164794".
