### ISSUE TITLE
Outlook desktop: Elevated permission is required to call the method 'body.getTypeAsync' in pinned add-in

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1192]
In an Outlook add-in for compose mode, we are using the body.getTypeAsync method. In Outlook desktop, the "Elevated permission is required to call the method" exception occurs if the add-in's pane is pinned.

## Expected Behavior
The exception should not occur.

## Steps to Reproduce, or Live Example
1. Select a received email in the Outlook Inbox.
2. Click the Reply or Forward button. Open the add-in’s pane and pin it.
3. Select another received email in the Outlook Inbox.
4. Click the Reply or Forward button. The add-in’s pane opens automatically.
5. Execute the following code:
`try {`
`  Office.context.mailbox.item.body.getTypeAsync({ }, (result: Office.AsyncResult<Office.CoercionType>) => {`
`    console.log('result', result);`
`  });`
`} catch (ex) {`
`  console.log('exception', ex);`
`}`

* Additional details:
  1. The same exception occurs for the getAsync method.

## Your Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: Version 2005 (build 12827.20210)
* Operating System: Windows 10
* Browser (if using Office Online): ______

**Comment by exextoc** [comment]
Thank you for reporting this issue. I'm able to reproduce it as well.

We'll need to investigate it further to understand its root cause and resolution.

Internal tracking id (helps to provide an update later) is office:4196963.

**Comment by exextoc** [comment]
We have fixed the bug you reported, and the fix should be available now. You may need to restart Outlook to pick up the fix if you are still seeing the issue.
