### ISSUE TITLE
[Outlook ] Office.context.mailbox.userProfile.timeZone get wrong timezone on Mac

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1194]
This problem only happening on Mac outlook client. Problem is: 'Office.context.mailbox.userProfile.timeZone' get the timezone of system not outlook client.
But mapi on C++ can get outlook timezone and js api 'Office.context.mailbox.userProfile.timeZone' get outlook timezone on windows too.

## Expected Behavior
'Office.context.mailbox.userProfile.timeZone' get timezone from Mac outlook preferences not system timezone.

## Current Behavior

On Mac set Time Zone to for example Wellington - New Zealand. And set Mac Outlook client default time zone to 'UTC+14:00 Kiritimati Island'. 
Then try use 'Office.context.mailbox.userProfile.timeZone' get time zone on add-in. 

Let 'Office.context.mailbox.userProfile.timeZone' get Outlook client timezone on Mac just like on windows.

## Steps to Reproduce, or Live Example
On Mac set Time Zone to for example Wellington - New Zealand. And set Mac Outlook client default time zone to 'UTC+14:00 Kiritimati Island'. 
Then try use 'Office.context.mailbox.userProfile.timeZone' get time zone on add-in. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac 10.15.5
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.35 (20030802)
* Operating System: Mac
* Browser (if using Office Online): ______

**Comment by exextoc** [comment]
Thanks for reporting this issue, we were able to repro this. It has been put on our backlog. Unfortunately, we have no timelines to share at this point.

**Comment by SWei1234** [comment]
Cool, any update please reply here ,Thanks

**Comment by exextoc** [comment]
@SWei1234 Can you share with us a screenshot of the window, where you set client default time zone?
Did you mean the default time zone for new events?

**Comment by SWei1234** [comment]
The left one is system Preferences and this setting is actually effective. 
The right one is Outlook Preferences which not effective.
![Untitled](https://user-images.githubusercontent.com/15980696/84362200-72d82700-abff-11ea-858c-0712c20f5e22.png)
yes, I mean the default time zone for new events.

**Comment by exextoc** [comment]
On further analysis it was found that Client timezone is only returned in case of Outlook on Web, On all other platforms the System timezone is returned. We shall be updating our documentation to make it clear.
