### ISSUE TITLE
Outlook Web taskpanel header does not change to dark mode when client set to dark mode

### ISSUE THREAD

**Issue by sirtwist** [OfficeDev/office-js#1195]
In Outlook Web the header area of the task pane does not change to dark mode when you set outlook to dark mode:

![image](https://user-images.githubusercontent.com/3112462/83475720-8c85ab80-a454-11ea-9d69-1aa34d88492a.png)

This is in contrast to what the Outlook desktop client does in dark mode:

![image](https://user-images.githubusercontent.com/3112462/83475749-9a3b3100-a454-11ea-83f3-20f97b8e2724.png)

## Expected Behavior
I know that there is not currently a way to detect when the web client is in dark mode, but I want to include a dark mode toggle in my add-in so the task pane isn't blindingly white when the user selects dark mode in Outlook. I have done this in my add-in and it works great for the content that I add and it looks good in the full Outlook client for Windows. But on the web, not so much.

My expectation would be that the header of the task pane that is automatically generated by Outlook should switch to dark mode along with the client, since it appears that I have no control over that UI.

Juan Balmori requested I add this issue: https://twitter.com/juaneloBalmori/status/1267627556762599425?s=20

**Comment by exextoc** [comment]
Can you please share the manifest file? I am unable to repro this issue. Are you using  [Office.context.officeTheme](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/preview-requirement-set/office.context#officetheme-officetheme) to extract the theme of the outlook?

**Comment by sirtwist** [comment]
I'm not using Office.context.officeTheme since it's only in preview at this time and only supports Outlook for Windows (O365) anyway. 

I've attached the manifest as requested, but not sure why the manifest would have anything to do with it. From what I can see every single task pane add-in opens with a white header in Outlook Web just like my example above.

[manifest-dev.zip](https://github.com/OfficeDev/office-js/files/4739339/manifest-dev.zip)

**Comment by sirtwist** [comment]
Just for clarity, my add-in has its own settings where I give the user the ability to set dark mode for the add-in since there's no way to get the current theme in a consistent manner for all outlook clients with a production API. So, if the user chooses to use "light" mode the add-in task pane looks fine and if you have Outlook in light mode as well, everything will match. If, however, you set Outlook to dark mode, and my add-in to dark mode, the user is left with a large block of white in the upper right corner (the add-in header). This is in contrast to how things look in the desktop client, which changes the header to a dark mode as well when the client is in dark mode.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding add-in title bar not handling dark mode. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
@sirtwist Manifest which you shared has localhost url. Can you share manifest for deployed version? Or striped down version of addin with dark mode toggle logic only?

**Comment by exextoc** [comment]
Internal tracking id: OutlookWeb:86708
