### ISSUE TITLE
Different Error Messages on Office Online and Office PC when an item is not found

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#120]
## Expected Behavior
We are searching the parent content control of the current selection. It can be that the selection does not have a parent content control. In such case an ItemNotFound exception is thrown.

## Current Behavior
Office Online throws a GeneralException instead of an ItemNotFound exception.

## Steps to Reproduce, or Live Example
Open this [gist repo](https://gist.github.com/barisbikmaz/769ebc9b2830675219e071482d12c4f4) on Office Online and PC and observe the different behaviours.

## Context
In Office Online I cannot differentiate between if the parent content control was not found or another exception has occured.

## Your Environment

* Platform : Office Online
* Host : Word
* Browser : Chrome

**Comment by XiangGaoMSFT** [comment]
Thanks for reporting it. This is a known issue and the fix has been checked-in, but we still need sometime to deploy it.
Will let you know once it reaches production environment.

**Comment by XiangGaoMSFT** [comment]
Hi Baris, the fix has been deployed to PROD.
I'm closing it and please free feel to reopen it if you still hit this issue.
