### ISSUE TITLE
addFileAttachmentFromBase64Async with isInline option doesn't work

### ISSUE THREAD

**Issue by bjornbacklund** [OfficeDev/office-js#1200]
The Office.context.mailbox.item.addFileAttachmentFromBase64Async API call with the "isInline=true" option inserts an empty image (of correct size but no data). Works well is isInline=false.

Steps to reproduce.
1. Launch https://outlook.office.com/
2. Open new message window
3. Go to Get Add-ins
4. Go to My add-ins
5. Click "Add a custom add-in:"
6. Enter "https://www.backlund.org/Manifests/LoveGifsForMSOutlook_Manifest_Release.xml"
7. In the sidebar that opens, use the two "red" "DEBUG" options. One will insert (correctly) an image attachment. The other option will insert the same image but "inline" and you end up with an empty image box.

**Comment by exextoc** [comment]
We can reproduce the issue. Thanks for reporting this issue regarding addFileAttachmentFromBase64Async issues. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by bchenhs** [comment]
Hi, this issue affects both file attachment APIs: `addItemAttachmentAsync` and `addFileAttachmentFromBase64Async`. Is there a rough estimate on when we can expect the fix? Thanks.

**Comment by exextoc** [comment]
@bchenhs With addFileAttachmentFromBase64Async and isInline = true, we need to use any set body related APIs to insert the image inline. addFileAttachmentFromBase64Async() API itself does not insert the image inline (inline=true). 

For example: You can use setAsync() and mention your image with "cid" syntax as below to insert the image inline.

		Office.context.mailbox.item.body.setAsync(
			"<p>Here's a gif image!</p><img src='cid:gifImageNameToInsert.gif'>",
			{
				"coercionType": "html"
			},
			function (asyncResult) {
                                        
	                }
                );

Note: gifImageNameToInsert.gif should be same name used addFileAttachmentFromBase64Async API.

Can you please confirm if you are using setAsync() or any other set body related APIs to insert your image inline?

**Comment by bchenhs** [comment]
Hi @exextoc Thanks for the snippet. Yes, the inline image appears after calling the setAsync. I apologize for the derail.

**Comment by bjornbacklund** [comment]
Works like a charm now. Thanks. 

---bjorn

**Comment by exextoc** [comment]
Thanks for confirming @bchenhs.

You had also mentioned about 'addItemAttachmentAsync' API. Is that working fine now? Note that "isInline" is not an option for this API. So, trying to understand what was the problem/error with this API usage.

**Comment by exextoc** [comment]
Closing this issue as main query is resolved. Please reopen if there is anything pending.
