### ISSUE TITLE
Outlook Consume Graph API Login Frequency

### ISSUE THREAD

**Issue by nfgallimore** [OfficeDev/office-js#1201]
**Question**

I am investigating how to convert an existing outlook add-in to authenticate to one of our APIs via AAD. The way the add-in works, it would severely limit the user experience if they were constantly  prompted with a dialog. If I were to base my solution off this sample project, how often could we expect the user to have to interact with a dialog or login?

**Comment by exextoc** [comment]
@mscharlock Can you explain the scenario which you are blocked on? From your other forum post, we could gather that there is some problem with callback. If you can provide proper repro steps, it will be helpful for investigation,

**Comment by mscharlock** [comment]
@exextoc tagging @saberone for further explanation

**Comment by lindalu-MSFT** [comment]
This issue is fixed by MSAL team. [See this PR](https://github.com/AzureAD/microsoft-authentication-library-for-js/pull/1667). WIth this latest release, the user should be unblocked. – Per Stack, Answered by Outlook Add-ins Team - MSFT Jun 15 at 9:19
