### ISSUE TITLE
Office.context.ui.messageParent not working on outlook web

### ISSUE THREAD

**Issue by AnvarNazar** [OfficeDev/office-js#1204]
## Expected Behavior
When the Office.context.ui.messageParent(message); called the message should reach on the callback in the hosted page.

## Current Behavior
Nothing happens. No warnings or error messages. The callback function on the hosted page is not invoked at all

## Additional details:
**The function creating the dialog on the hosted page**
```
  startDialog() {
    try {
      Office.context.ui.displayDialogAsync(
        `${window.location.origin}/dialog`,
        {
          height: 60,
          width: 80,
          displayInIframe: false,
        },
        function (asyncResult) {
          console.info("Dialog window opened for authentication");
          console.info(asyncResult);
          asyncResult.value.addEventHandler(
            Office.EventType.DialogMessageReceived,
            (message) => {
              console.info(message);
              console.info("MESSAGE received from dialog");
              asyncResult.value.close();
              this.router.navigate(["/sucessScreen"]);
              this.userExist = true;
              localStorage.setItem("auth", JSON.stringify(this.userExist));
            }
          );
        }
      );
    } catch (error) {
      console.error("Error setting up dialog");
      console.error(error);
    }
  }
```
**The dialog window source**

```
<!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Sustainable Meeting Activated Successfully</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://appsforoffice.microsoft.com/lib/beta/hosted/office.debug.js"></script>
        <script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
        <link
          rel="stylesheet"
          href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.min.css"
        />
        <link
          rel="stylesheet"
          href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/css/fabric.components.min.css"
        />
        <script src="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.4.0/js/fabric.min.js"></script>
      </head>
      <body>
        <script>
          (function () {
            console.info("Test Dialog");
            Office.initialize = (reason) => {
              $(document).ready(function () {
                Office.context.ui.messageParent(true);
              });
            };
          })();
        </script>
      </body>
    </html>
```
## Context
I am trying to send a message to the hosted page from the dialog window that the operation is successful. The add in written in typescript and the dialog page is plain html and javascript.

## Your Environment
* Platform : Office Online
* Host : Outlook
* Office version number: Outlook Web 16
* Operating System: Gnu/Linux
* Browser (if using Office Online): Firefox 76.0.1, Chromium 83.0.4103.61

## Useful logs
No error. It seems that only `Office.context.ui.messageParent` function is not working

**Comment by exextoc** [comment]
We cannot reproduce the issue. Is this the same issue reported on [stackoverflow](https://stackoverflow.com/questions/62244143/error-in-outlook-addin-dialog-typeerror-cant-redefine-non-configurable-proper/62275116#62275116)?

**Comment by AnvarNazar** [comment]
> We cannot reproduce the issue. Is this the same issue reported on [stackoverflow](https://stackoverflow.com/questions/62244143/error-in-outlook-addin-dialog-typeerror-cant-redefine-non-configurable-proper/62275116#62275116)?

No. I actually found the issue. The `<AppDomain>` in plugin manifest didn't match the domain of the addin. It's working when I set the correct domain on the manifest.
