### ISSUE TITLE
Outlook Online, addFileAttachmentAsync, exception in AttachmentIconViewBase

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1205]
In an Outlook add-in for compose mode, we use the Office JS API to fill in email fields and add attachments. The addFileAttachmentAsync method throws the “Cannot read property 'Id' of null” exception.

## Expected Behavior
The addFileAttachmentAsync method should work correctly.

## Steps to Reproduce, or Live Example
Create a new email in Outlook Online and execute the following code:

    const url = 'https://cdn.ablebits.com/_img/d-19/logo/ablebits-logo-desktop.svg';
    const options: Office.AsyncContextOptions & { isInline: boolean } = { isInline: true };
    try {
      Office.context.mailbox.item.addFileAttachmentAsync(url, 'test.svg', options, (result: Office.AsyncResult<string>) => {
        if (result.status === Office.AsyncResultStatus.Succeeded) {
          console.log('# success', result);
        } else {
          console.log('# error', result);
          console.log(result.error);
        }
      });
    } catch (ex) {
      console.log('# exception', ex);
    }

Note, the callback is not executed, but there is an error in the console.

* Additional details:
  1. Both platforms, Windows and Mac, are affected.

## Your Environment
* Platform: Outlook Online
* Host: Outlook
* Office version number: 
* Operating System: Windows and Mac
* Browser (if using Office Online): Chrome 83.0.4103.97 on Windows and Chrome 83.0.4103.61 on Mac

## Useful logs
- [*] Console errors
Uncaught (in promise) TypeError: Cannot read property 'Id' of null
at owa.MailCompose.js:1
at owa.MailCompose.js:1
at AttachmentIconViewBase.tsx:32

**Comment by exextoc** [comment]
The supported image file types for inline attachments are .png, .gif, .bmp, .dib, .jpg, .jpe, .jfif, and .jpeg.
You can add .svg types as non-inline attachments use  `{ isInline: false }`

Outlook online does not know how to render other file types inline, so this is expected behavior.

**Comment by DmitryKostochko** [comment]
@exextoc, sorry, I cannot understand your answer. Do you think that this unhandled exception is really expected behavior? I would rather get a callback with the status set to AsyncResultStatus.Failed. Please consider this once again.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding addFileAttachmentAsync callback issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by DmitryKostochko** [comment]
@exextoc, thank you! Please re-open this issue.
