### ISSUE TITLE
insertHtml inserts additional whitespace before content

### ISSUE THREAD

**Issue by josip-rc** [OfficeDev/office-js#1206]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior

When using `insertHtml(newContent, 'Replace')` new content should replace old content in the same way on all Word platforms (Windows, Mac, Online).

## Current Behavior

Calling `insertHtml(newContent, 'Replace')` on Word Online adds extra whitespace before the content.

## Steps to Reproduce, or Live Example

* Link to live example: https://gist.github.com/josip-rc/427b6946fc796268811783963a79742c

Click setup to setup document, and run to reproduce the behaviour.
Note that extra whitespace is inserted in Word Online.

## Context

Our logic requires us to replace hyperlink ranges with other content. This replace works correctly in Word on Windows and Mac but on Word Online extra whitespace is added before
the newly inserted content.

On text:
```
Video provides
         ^^^^^^ where vides is linked
```

Running code:
```
context.document.body
      .getRange()
      .getHyperlinkRanges()
      .getFirst()
      .insertHtml("Test", "Replace");
```

results in:
```
Video pro Test
```
on Word online

and 
```
Video proTest
```
on Word on Windows, Mac

## Your Environment
* Platform: Office Online
* Host: Word
* Office version number: Word Online
* Operating System: MacOS Mojave
* Browser: Chrome 83.0.4103.61

**Comment by MandytMSFT** [comment]
@josip-rc thanks for the reporting, i can repro this issue. BUG 4217372 is opened for internal track.
