### ISSUE TITLE
OfficeRuntime and other SDK components are undefined in Chrome incognito

### ISSUE THREAD

**Issue by bdentino** [OfficeDev/office-js#1207]
When testing an add-in within incognito mode in Chrome, I have noticed that some SDK components are not available globally or on the window. Accessing `OfficeRuntime` throws an "OfficeRuntime is not defined" error. `Excel` is undefined, as is `Office.addin`.

## Expected Behavior
OfficeRuntime, Excel, and Office.addin components should be defined by the time Office.onReady(...) callback is called.

## Current Behavior

On load I see an error in the console about trying to access sessionStorage without permission. The culprit seems to be a function in `excel-web-16.00.debug.js`:

```js
         function loadWebAuthForReplyPage() {
		if (typeof (window)==="undefined" || !window.sessionStorage) {
			return;
		}
		var webAuthRedirectUrls=sessionStorage.getItem(WebAuthReplyUrlsStorageKey);
		if (webAuthRedirectUrls !==null && webAuthRedirectUrls.indexOf(window.location.origin+window.location.pathname) !==-1) {
			load();
		}
	}
```

I tested with a patched version, and wrapping the `window.sessionStorage` expression in a try/catch block and returning on error seems to resolve the issue and all SDK components are defined by the time my Office.onReady(...) callback is run.

## Steps to Reproduce, or Live Example
I think you should be able to reproduce this just by running the ScriptLab add-in itself in Chrome Incognito Mode.

## Context

I understand that the OfficeRuntime.storage API may not be fully functional if access to sessionStorage is restricted, but because of all these missing components any other functionality in our add-in that should be able to work without relying on sessionStorage is effectively neutered and can't run at all in Incogito mode.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.00
* Operating System: Mac
* Browser (if using Office Online): Chrome Version 83.0.4103.97 (Official Build) (64-bit) (Incognito)

## Useful logs

![image](https://user-images.githubusercontent.com/3820523/84081127-019c3800-a9a3-11ea-93b4-c8a49f6cfb2b.png)

**Comment by bdentino** [comment]
This appears to be related to a new setting in Chrome that blocks 3rd-party cookies in Incognito - so you will need Chrome v83+ to reproduce.

https://venturebeat.com/2020/05/19/google-chrome-83/#:~:text=Third%2Dparty%20cookies%20blocked%20in%20Incognito,-In%20Incognito%20mode&text=Starting%20with%20Chrome%2083%2C%20the,icon%20in%20the%20address%20bar

**Comment by jeremy-msft** [comment]
Hi @bdentino, thanks for your feedback.  We recently resolved this issue and the fix was released to production yesterday.  Please try again and let us know if you still see the problem.

**Comment by lindalu-MSFT** [comment]
Closing, fixed!
