### ISSUE TITLE
Help needed with reading the text of indented OneNote paragraphs using Office.js

### ISSUE THREAD

**Issue by 1001QAdotNET** [OfficeDev/office-js#1209]
Hi 

I am trying to read the text of a OneNote page that contains indented paragraphs and I can't figure out how to do it
Please if you have an example I would like to see it
Here is my StackOverflow question and my attempts to solve the problem
https://stackoverflow.com/questions/62272535/how-do-i-read-onenote-indented-paragraphs-using-onenote-javascript-apis

Any help would be much appreciated
Thank you
1K1

**Comment by peronald** [comment]
Thanks for your question. We monitor StackOverflow for programming questions while this forum is for issues with our product or documentation. You should be getting a response from us on your StackOverflow question shortly.

**Comment by 1001QAdotNET** [comment]
OK so you guys closed this 15 days ago, My question has been sitting on StackOverflow for much longer than that. Any chance this could be looked at ?
