### ISSUE TITLE
Excel Chart onActivate and onDeactivate fire repeatedly when chart is selected

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js#121]
## Expected Behavior
Selecting a chart will fire the onActivated event once and not fire the onDeactivated event.

## Current Behavior
When the chart is selected, the onActivated fires from 5 to 10 times in a row, with onDeactivated firing in between each firing of onActivated.

## Steps to Reproduce, or Live Example
Import the following gist into Script Lab to reproduce. Just follow the instructions in the task pane.
* Link to live example: https://gist.github.com/Rick-Kirkham/7263a80bec5df56a9d8722eea020a3a5

## Context
Creating a snippet for these events is blocked.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1806 10203.20002
* Operating System: Windows
* Browser (if using Office Online): ______

**Comment by JuaneloJuanelo** [comment]
you are not registering to the deactivated event, your code i think has a bug.

**Comment by Rick-Kirkham** [comment]
Good catch. I fixed that and the other bug is fixed, but the symptoms of this one are still happening.

**Comment by JuaneloJuanelo** [comment]
@Rick-Kirkham  can you please confirm this issue happens when AIP add-in is active?

**Comment by Rick-Kirkham** [comment]
Yes. I can confirm.

**Comment by Rick-Kirkham** [comment]
Also affects ChartCollection.onActivated. Snippet: https://gist.github.com/Rick-Kirkham/9cac16a552daf5070fc1cfb46bed415c

**Comment by Rick-Kirkham** [comment]
This bug was fixed some months ago.
