### ISSUE TITLE
ScriptLab Excel add-in causes Excel and WWAHost.exe application errors

### ISSUE THREAD

**Issue by AndreRSA** [OfficeDev/office-js#1210]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I installed the ScriptLab add-in and the tab appears in the Excel ribbon but when I select any of the functions Excel closes and several error log entries are created. The first is an application error entry (1000) with the following content:
Faulting application name: wwahost.exe, version: 10.0.19041.1, time stamp: 0x484cb762
Faulting module name: KERNELBASE.dll, version: 10.0.19041.207, time stamp: 0x746c1866
Exception code: 0xc0000409
Fault offset: 0x000000000010b37c
Faulting process id: 0x2140
Faulting application start time: 0x01d63e4a6dd4b061
Faulting application path: C:\Windows\System32\wwahost.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 572aaded-81e8-42ba-89da-5a7277de68d2
Faulting package full name: Microsoft.Win32WebViewHost_10.0.19041.1_neutral_neutral_cw5n1h2txyewy
Faulting package-relative application ID: DPI.PerMonitorAware

A second application error entry is logged :
Faulting application name: EXCEL.EXE, version: 16.0.12827.20268, time stamp: 0x5ed0d679
Faulting module name: KERNELBASE.dll, version: 10.0.19041.207, time stamp: 0x746c1866
Exception code: 0xc0000409
Fault offset: 0x000000000010b37c
Faulting process id: 0x3554
Faulting application start time: 0x01d63e4a38fafc7d
Faulting application path: C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 0576eb2c-8a99-4a8f-a97c-5e8f80f765f8
Faulting package full name:
Faulting package-relative application ID:

Each of the error entries are followed by Windows Error Reporting entries.

My environment is: OS : Windows 10 Home Version 2004 build 19041.264 Office: version 2005 Build 12827.20268 Click-to-Run Edge Version: Version 83.0.478.45 (Official build) (64-bit) Edge Beta: Version 84.0.522.15 (Official build) beta (64-bit)

I have re-installed Edge and Edge Beta, fixed Office installation, ran sfc /scannow with no errors.
Testing the same process with another PC worked fine.

**Comment by lumine2008** [comment]
@smaremanda , I saw @AndreRSA asked a question in StackOverflow,  it looks to me like a webview control issue from the error. So I suggest @AndreRSA report this issue in github. could you please view and see if this is webview control area? thanks

**Comment by AndreRSA** [comment]
> @smaremanda , I saw @AndreRSA asked a question in StackOverflow, it looks to me like a webview control issue, as the error is gone after reinstalled the edge. So I suggest @AndreRSA report this issue in github. could you please view and see if this is webview control area? thanks

Just a correction - re-installing Edge did not fix the error.  The working test of the add-in and worksheet was on another PC.

**Comment by AltitudeApps** [comment]
I am experiencing a similar, but not identical, problem.

https://github.com/OfficeDev/script-lab/issues/831

Also:  I'm not sure how this topic can be considered a programming question, since the user hasn't presented any code.
