### ISSUE TITLE
OneNote - image.description setter doesn't work

### ISSUE THREAD

**Issue by pvasek** [OfficeDev/office-js#1212]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

If you set `image.description` this description is not saved.

## Expected Behavior
The description is saved on the server. After reloading it can be read. That means:
- it's displayed in "Alt text..."
- it's returned if you read `image.description`

## Current Behavior
The description stays empty.

## Steps to Reproduce, or Live Example

Open a OneNote page, select an image and run this function:

```typescript
OneNote.run(async ctx => {
      const par = ctx.application.getActiveParagraph();
      const des = "test description " + Date();
      par.image.description = des;
      await ctx.sync();
      console.log("description assigned: ", par.image.description);
    });
```

Reading works fine. If I assign the "Alt text..." I got this description back.

## Context

I am trying to insert image including a description. I can insert the image but I am not able to assign the description. 

## Your Environment
Mac, Chrome 84, Office Online, OneNote

**Comment by lindalu-MSFT** [comment]
@JuaneloJuanelo Hi, is OneNote your area? If not, do you know the correct PM to assign?

**Comment by ElizabethSamuel-MSFT** [comment]
@pvasek Thanks for raising this issue. I'm reaching out to OneNote folks internally and will provide an update as soon as possible.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@pvasek The team has confirmed this is still reproing and they're investigating next steps. We'll comment as we get updates.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@lindalu-MSFT Can you help get this transferred to https://github.com/OneNoteDev/OneNoteApi?

Or @pvasek Can you open a new issue in the https://github.com/OneNoteDev/OneNoteApi repo and reference this issue?

The issue should then get more traction with the OneNote API team.

Thanks.

**Comment by lindalu-MSFT** [comment]
@ElizabethSamuel-MSFT That repo is in a different (non-OfficeDev) org. I don't have the required permissions to transfer this issue to that repo.

**Comment by lindalu-MSFT** [comment]
@ElizabethSamuel-MSFT That repo is in a different (non-OfficeDev) org. I don't have the required permissions to transfer this issue to that repo.
