### ISSUE TITLE
License points to broken link

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/office-js#1213]
The license file points to https://msdn.microsoft.com/en-US/cc300389, which is a broken link.

Please update whatever needs to be updated so that we can obtain all the licences related to this project. Without this our legal department will not allow us to use this library.

**Comment by JuaneloJuanelo** [comment]
Can you please add more details on where is the license you are describing or what page has that broken link? otherwise will be tough to fix.

**Comment by dmitriyyepishin** [comment]
The license file is here: https://github.com/OfficeDev/office-js/blob/release/LICENSE

**Comment by lindalu-MSFT** [comment]
@dmitriyyepishin Where did you find this broken link?

**Comment by dmitriyyepishin** [comment]
@lindalu-MSFT Here's how to see the broken link:

1. Open license file in this repository: https://github.com/OfficeDev/office-js/blob/release/LICENSE
2. The license file refers to this link: https://msdn.microsoft.com/en-US/cc300389. This link is broken.

**Comment by dmitriyyepishin** [comment]
This has been fixed.
