### ISSUE TITLE
[Word Online] Range tracking doesn't work / inconsistent with Office 365 Word

### ISSUE THREAD

**Issue by nopepper** [OfficeDev/office-js#1215]
A tracked range used to be robust to changes around it until a few days ago. The behavior is only bugged in the online version of Word.

Example:
- Have a sentence, e. g. "The house is green"
- Find the ranges for the words "The" (r1) and "green" (r2) and track them
- Set r1 to "[The]"
- Set r2 to "[green]"

## Expected Behavior
Word document should be: "[The] house is [green]"

## Current Behavior
Word document outputs: "[The] house i[green]en"
It seems that the character range for "green" has stayed the same, so by replacing "The" with "[The]" and adding two characters, the range gets shifted to the wrong position.

## Steps to Reproduce, or Live Example
* Link to live example: https://gist.github.com/nopepper/1479c1faa46649f459b1398c737ee872

## Context
Our company provides a grammar checker add-on for Word. Therefore, we rely heavily on tracked ranges to keep our text suggestions bound to the correct words in the document even after changes by the user. 

## Your Environment
* Platform: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: n/a
* Operating System: Windows 10
* Browser (if using Office Online): Chrome, Edge

## Useful logs
No special errors, at least in the console.

**Comment by jipyua** [comment]
hi,

Due to some limitation on word online, sometimes this issue will happen. But if you changed your code to InsertText in the same batch, then it will be working. And actually for better performance, there is no need to put them into separate batch. so please change to the following and have a try:
 var par = context.document.body.paragraphs.getFirst();
      par.load();
      var r1 = par
        .search("The")
        .load("items")
        .getFirst();
      var r2 = par
        .search("green")
        .load("items")
        .getFirst()
        .load();
      r1.insertText("[The]", "Replace");
      r2.insertText("[green]", "Replace");
      return context.sync().then(function() {       
        console.log(r2.text); // Still says "properly."
      });
    });

**Comment by nopepper** [comment]
Hi @jipyua, thank you for your quick answer. You're right, in this example it wouldn't be necessary to have two batches. However, our system requires that the Range objects stay tracked beyond one particular batch. As I understand it, that's the purpose of the track() function.
I'd be grateful for a workaround or fix that doesn't require batching all actions together.

**Comment by JuaneloJuanelo** [comment]
Here is an example of how you successfully track ranges.  This code is actually doing a search, it actually keeps the ranges in an array for later use. Hope it helps.
https://gist.github.com/JuaneloJuanelo/a8b62c1f1dc31703c7960f661b9e8b18

**Comment by nopepper** [comment]
Hello @JuaneloJuanelo and thank you for the reply. I've tested your snippet and posted the video results below. Unfortunately the same problem persists, as changing the length of the document will offset the (supposedly tracked) ranges and apply the bold formatting to the wrong part of the text. Again, the problem only applies to Word Online, the local Office 365 Word for Windows works as expected.
Since this behavior is inconsistent across Word versions, and possibly a legitimate bug, maybe it would be a good idea to reopen the issue.

[Range tracking issue.zip](https://github.com/OfficeDev/office-js/files/4785999/Range.tracking.issue.zip)
