### ISSUE TITLE
Cannot insert contentControl on w:t with xml:space=\"preserve\"

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/office-js#1216]
When text sits inside `<w:t>` with `xml:space=\"preserve\"` inserting contentcontrol on corresponding range fails. If a parent has `xml:space=\"preserve\"` no problem. 

Below is the extracted OOXML body

```XML
<w:body>
					<w:p w:rsidR=\"003926EC\" w:rsidRDefault=\"003926EC\" w:rsidP=\"59EE9F45\">
						<w:pPr>
							<w:spacing w:line=\"276\" w:lineRule=\"auto\" />
						</w:pPr>
						<w:bookmarkStart w:id=\"0\" w:name=\"_Toc36386118\" />
						<w:bookmarkStart w:id=\"1\" w:name=\"_Toc36386158\" />
						<w:bookmarkStart w:id=\"2\" w:name=\"_Toc36386171\" />
						<w:bookmarkEnd w:id=\"0\" />
						<w:bookmarkEnd w:id=\"1\" />
						<w:bookmarkEnd w:id=\"2\" />
						<w:r>
							<w:t>RPL § 232, stk. 3 </w:t>
						</w:r>
					</w:p>
					<w:p w:rsidR=\"00000000\" w:rsidRDefault=\"003926EC\">
						<w:r>
							<w:t xml:space=\"preserve\">RPL § 232, stk. 3 

</w:t>
						</w:r>
					</w:p>
					<w:sectPr w:rsidR=\"00000000\">
						<w:pgSz w:w=\"12240\" w:h=\"15840\" />
						<w:pgMar w:top=\"1440\" w:right=\"1440\" w:bottom=\"1440\" w:left=\"1440\" w:header=\"708\" w:footer=\"708\" w:gutter=\"0\" />
						<w:cols w:space=\"708\" />
					</w:sectPr>
				</w:body>
```
Document is here [UknownBug.docx](https://github.com/OfficeDev/office-js-docs-pr/files/4758433/UknownBug.docx)

I do not know how to generate that particular form of OOXML. I have not manipulated the OOXML directly. I have only been using the API. 

To reproduce:
1) search for `RPL § 232, stk. 3 `
2) for every range -> range.insertContentControl()
3) first range is ok second one fails

Error 
{"code":"GeneralException","message":"Der opstod en fejl. Se OfficeExtension.Error.debugInfo for yderligere oplysninger. ","errorLocation":"Range.insertContentControl","statement":"var insertContentControl=v.insertContentControl();","surroundingStatements":["var v=context.root._getObjectByReferenceId(\"{45828e50-b0ea-4205-9bf4-7b13e60cf2dd}{184}\") /* originally intersectWithOrNullObject(...) */;","// >>>>>","var insertContentControl=v.insertContentControl();","// <<<<<","// Instantiate {insertContentControl}","insertContentControl.removeWhenEdited=...;","insertContentControl.appearance=...;","insertContentControl.tag=...;","insertContentControl.title=...;","..."],"fullStatements":["var v=context.root._getObjectByReferenceId(\"{45828e50-b0ea-4205-9bf4-7b13e60cf2dd}{184}\") /* originally intersectWithOrNullObject(v1) */;","var insertContentControl=v.insertContentControl();","// Instantiate {insertContentControl}","insertContentControl.removeWhenEdited=true;","insertContentControl.appearance=\"Hidden\";","insertContentControl.tag=\"__onlawlink__\";","insertContentControl.title=\"{\\\"contents\\\":{},\\\"displayTitle\\\":\\\"\\\",\\\"paragraphs\\\":[],\\\"uid\\\":\\\"LBK nr 938 af 10/09/2019\\\",\\\"url\\\":\\\"https://onlaw.dk/lovbekendtgørelse/lbk-nr-938-af-10-09-2019\\\"}\";","v.hyperlink=\"https://onlaw.dk/lovbekendtgørelse/lbk-nr-938-af-10-09-2019\";"]}

**Comment by JuaneloJuanelo** [comment]
I cannot repro this behavior. 

i am using this code with the document you referenced. that document, btw only has one instance of  RPL § 232, stk. 3 (so it only find one range) 
```
async function basicSearch() {
  await Word.run(async (context) => {
    let results = context.document.body.search("RPL § 232, stk. 3");
    results.load("length");

    await context.sync();

    // Let's traverse the search results... and highlight...
    for (let i = 0; i < results.items.length; i++) {
      results.items[i].insertContentControl();
    }

    await context.sync();
    console.log("Good!");
  });
}

```

if you can still repro, please send a document with several instances, and also will be great if you can include the code you are using so we can investigate properly. 
Also please indicate in what platforms and what build you are observing this.
Thanks!
