### ISSUE TITLE
OneNote API: How do I change the indentation of a paragraph and its children?

### ISSUE THREAD

**Issue by 1001QAdotNET** [OfficeDev/office-js#1217]
HI 
My question was posted yesterday on Stackoverflow as advised here. Here is the link
https://stackoverflow.com/questions/62348684/onenote-office-js-apis-updating-the-text-of-a-paragraph-and-indenting-it-as-nee

To give you a quick overview, I am trying to change the indentation of a paragraph and its children and I can't figure out what I should do for that. The OneNote Javascritp APIs don't seem to have a paragraph method for that. I have tried to add the respective paragraph as a child (listed in items) of the next upstream paragraph that is just above the element I am trying indent. Please see Stackoverflow for details 
Could you please help with some examples (maybe add them to your API docs or point to where I should read about this? I am not sure if there is a method for this or one should combine existing objects and their methods to achieve this

thank you
1k1

**Comment by lindalu-MSFT** [comment]
Hi @1001QAdotNET, I verified with the OneNote PM that on OneNote or any other Office canvas, you cannot modify the page indentation with office.js currently. You can always suggest this feature at [UserVoice](https://officespdev.uservoice.com/)!
