### ISSUE TITLE
Outlook add-in doesn't work in group boxes

### ISSUE THREAD

**Issue by modestfake** [OfficeDev/office-js#1218]
I've noticed that none of Outlook add-ins work in Outlook group boxes. I tested a few add-ins (Jira Cloud for Outlook, Slack for Outlook, Trello.

## Expected Behavior
Outlook add-ins work the same as they do in a regular inbox.

## Current Behavior
If I open a group box, Outlook add-ins don't show up.
Outlook WEB
![image](https://user-images.githubusercontent.com/16977959/84681361-acc96600-af3c-11ea-9bb1-9d43ee753e05.png)
Outlook for Mac
![image](https://user-images.githubusercontent.com/16977959/84681473-d6828d00-af3c-11ea-8125-9a1e69e18384.png)

## Steps to Reproduce, or Live Example
1. Install any Outlook add-in. For example, [Jira Cloud for Outlook](https://appsource.microsoft.com/en-us/product/office/WA200000056).
2. Open any email in inbox, confirm that you see add-in in a ribbon (or menu, depending on platform).
3. [Create group box following this guide](https://support.office.com/en-us/article/create-a-group-in-outlook-04d0c9cf-6864-423c-a380-4fa858f27102#ID0EACAAA=Web).
4. Send email to this group box, open it and check if you see add-in there.

## Context
It would be great if add-ins work in group boxes.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac, Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Mac
* Browser (if using Office Online): Chrome

**Comment by JuaneloJuanelo** [comment]
That's right, Add-ins are not supported in groups. Please create/upvote issue https://officespdev.uservoice.com/ and share more details on your scenario.
