### ISSUE TITLE
Provide timeline for switching to Chromium Edge in Windows Desktop Outlook

### ISSUE THREAD

**Issue by ArashMotamedi** [OfficeDev/office-js#1219]
[Enter feedback here]
What's the timeline for switching to Chromium Edge in Outlook Desktop for Windows for Taskpane addins?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Oleg-O** [comment]
I believe we've switched already...
