### ISSUE TITLE
CustomFunctions.StreamingInvocation setResult() cannot set the result for a dynamic array

### ISSUE THREAD

**Issue by topkoong** [OfficeDev/office-js#1220]
CustomFunctions.StreamingInvocation setResult() cannot set the result for a dynamic array.

## Expected Behavior

CustomFunctions.StreamingInvocation setResult() should set the result for a dynamic array and display it once a second.
## Current Behavior

It returns #VALUE error which indicates an error in the functions' script file.

## Steps to Reproduce, or Live Example

```typescript
/**
 * Increments a value once a second.
 * @customfunction
 * @param incrementBy Amount to increment
 * @param {CustomFunctions.StreamingInvocation<any[][]>} invocation
 */
export function test(incrementBy: number, invocation: CustomFunctions.StreamingInvocation<any[][]>): void {
  let result = [0, 0, 0, 0];
  const timer = setInterval(() => {
    result = result.map(r => r + incrementBy);
    console.log('result: ', [result]);
    invocation.setResult([result]);
  }, 1000);

  invocation.onCanceled = (): void => {
    clearInterval(timer);
  };
}
```

```typescript
/**
 * Increments a value.
 * @customfunction testArr
 * @param {CustomFunctions.StreamingInvocation<any[][]>} invocation
 */
export function testArray(invocation: CustomFunctions.StreamingInvocation<any[][]>): void {
  invocation.setResult([[1,2,3,4]]);
}
```

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: OSX
* Browser (if using Office Online): Chrome Version 83.0.4103.97 (Official Build) (64-bit)

**Comment by xiaochunms** [comment]
#VALUE error means wrong data type.  You can change the function definition as follows to have a try.

> testArray(invocation: CustomFunctions.StreamingInvocation<**any[][]**>

**Comment by topkoong** [comment]
@xiaochunms Thank you for the reply. I've tried that. Still, it shows #VALUE error.

```Typescript
/**
 * Increments a value.
 * @customfunction testArr
 * @param invocation
 */
export function testArray(invocation: CustomFunctions.StreamingInvocation<any[][]>): void {
  invocation.setResult([[1,2,3,4]]);
}
```

**Comment by xiaochunms** [comment]
Suppose you are using scriptlab. Following code snippet works for me. The difference is that no "export" before function in codes below.

```
/**
 * Increments a value.
 * @customfunction testArr
 * @param {CustomFunctions.StreamingInvocation<any[][]>} invocation
 */
function testArray(invocation: CustomFunctions.StreamingInvocation<any[][]>): void {
  invocation.setResult([[1, 2, 3, 4]]);
}
```

**Comment by topkoong** [comment]
Well, I've slightly modified a function from a sample code generated by Yeoman [https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows), and when I compiled it, I've got the following error message: **Invalid type: CustomFunctions.StreamingInvocation**. I think this happens because of JSDoc tags, used to provide extra information about the custom function, which are then used at build time to create the JSON metadata file.

**Comment by itoxable** [comment]
Hello,
I'm experiencing the same problem, it works on Excel online, but not on the desktop. 
Is there any working examples?

Thanks

**Comment by topkoong** [comment]
Any update on this?

**Comment by xiaochunms** [comment]
The error message used to indicate some errors in the code. I may suggest to using [Scriptlab](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab) and applying the code I shared to have a try then.

**Comment by topkoong** [comment]
@xiaochunms I've used a sample code generated by Yeoman https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows and only modified this function. I would greatly appreciated if you could provide a repo/code sandbox for this.

**Comment by thatusernamenotavailable** [comment]
The following works on Excel online but it only shows "larry" in Office 365 for Windows:

```
/**
 * Returns the names of people
 * @customfunction mynames
 * @param invocation Custom function handler
 */
function mynames(invocation: CustomFunctions.StreamingInvocation<string[][]>): void{
  const timer = setInterval(() => {
    var row1 = ["larry", "moe", "curly"];
    var row2 = ["scoopy", "velma", "shaggy"];
    var rows = [row1, row2];

    invocation.setResult(rows);
  }, 5*1000); // every 5 seconds

  invocation.onCanceled = () => {
    clearInterval(timer);
  };
}
```


I've tried with and without `export` with the same effect. Doesn't seem to be any documentation anywhere on why this doesn't work.

**Comment by thatusernamenotavailable** [comment]
The examples posted [in the docs](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-dynamic-arrays) work on online Excel but not in Excel 356 for Windows (same issue...just returns the first value):

```
/**
 * Get text values that spill down.
 * @customfunction
 * @returns {string[][]} A dynamic array with multiple results.
 */
function spillDown() {
  return [['first'], ['second'], ['third']];
}

/**
 * Get text values that spill to the right.
 * @customfunction
 * @returns {string[][]} A dynamic array with multiple results.
 */
function spillRight() {
  return [['first', 'second', 'third']];
}

/**
 * Get text values that spill both right and down.
 * @customfunction
 * @returns {string[][]} A dynamic array with multiple results.
 */
function spillRectangle() {
  return [
    ['apples', 1, 'pounds'],
    ['oranges', 3, 'pounds'],
    ['pears', 5, 'crates']
  ];
}
```

**Comment by thatusernamenotavailable** [comment]
I imagine it's also broke in Mac version as well.

**Comment by topkoong** [comment]
Any update on this matter?

**Comment by topkoong** [comment]
Any update on this? @xiaochunms

**Comment by keyur32** [comment]
Hi there, @thatusernamenotavailable , per the examples above, did you need to add the '@streaming' tag? THat would register it as a streaming function on the desktop as well as online: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json-autogeneration

This works for me:
-------------------------------------
name: StreamingGitHubIssue1120
description: Create a new snippet from a blank template.
host: EXCEL
api_set: {}
script:
  content: >-
    /**
     * Returns the names of people
     * @customfunction mynames
     * @streaming
     * @param invocation Custom function handler
     */
    function mynames(invocation:
    CustomFunctions.StreamingInvocation<string[][]>): void {
      const timer = setInterval(() => {
        var row1 = ["larry", "moe", "curly"];
        var row2 = ["scoopy", "velma", "shaggy"];
        var rows = [row1, row2];

        invocation.setResult(rows);
      }, 1 * 1000); // every 5 seconds

      invocation.onCanceled = () => {
        clearInterval(timer);
      };
    }
  language: typescript
libraries: |
  https://appsforoffice.microsoft.com/lib/1/hosted/office.js
  @types/office-js

  office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
  office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

  core-js@2.4.1/client/core.min.js
  @types/core-js

  jquery@3.1.1
  @types/jquery@3.3.1

**Comment by keyur32** [comment]
Also, if it is working on Online, but not on desktop, you may be in a build of windows that doesn't suppport dynamic arrays. Easier way to check it type in the =MUNIT(3) into the cell and see if it spills into a 3x3 range.

**Comment by sdbarrington** [comment]
did anyone ever get this working? IF so could you please share a working example, I've tried everything but can't get something like this to actually work:
`var row1 = ["larry", "moe", "curly"];
    var row2 = ["scoopy", "velma", "shaggy"];
    var rows = [row1, row2];

    invocation.setResult(rows);`

**Comment by georgechr** [comment]
Hello,

Will this ever get fixed?

It's a bug for all intends and purposes.

**Comment by AlexandraKim** [comment]
Still not working( Does anybody know a workaround?

**Comment by FelipeCostaGualberto** [comment]
This is working as expected for me in Excel for Windows Desktop. I don't know if it was fixed, today was the first day I tried to use.
The way you should register the function must be specifically this way:

```
{
  // ... id, name, description and parameters ...
  "result": {
    "type": "number",
    "dimensionality": "matrix",
    "description": "Another description."
  },
  "options": {
    "stream": true
  }
}

```
