### ISSUE TITLE
Office.CustomProperties.saveAsync return succeed but custom property not saved to Event Item for Shared Calendars in OWA

### ISSUE THREAD

**Issue by GeoffreyYue1** [OfficeDev/office-js#1224]
In out Outlook Add-in we are using Office.CustomProperties.saveAsync to save the custom properties, the function works fine in Outlook, my own calendar in OWA, but in the shared calendar of OWA, the API result succeed but didn't save the customer property to the meeting item.

## Expected Behavior
In OWA shared calendar meeting items,  Office.CustomProperties.saveAsync could save the meeting items successfully.

## Current Behavior
In OWA shared calendar meeting items,  when we call Office.CustomProperties.saveAsync, API return succeed, but custom property didn't save to the meeting Item.

## Steps to Reproduce, or Live Example
	function btnSetPropertyClick() {
	
	       
	        var item = Office.context.mailbox.item;
	
	        item.loadCustomPropertiesAsync(customPropsCallback);
	       
	    }
	
	    function customPropsCallback(asyncResult) {
	        var customProps = asyncResult.value;
	        var myProp = customProps.get("myProps");
	        console.log("myProp: " + myProp); // First run on current item will return `undefined`.
	
	        // Set myProp custom property.
	        customProps.set("myProps", "this is my test property value [Case #:20132451] - O365 addin client setcustomproperty failed even the api return success");
	        customProps.saveAsync(saveCallback);
	    }
	
	    function saveCallback(asyncResult) {
	        if (asyncResult.status === Office.AsyncResultStatus.Failed) {
	            console.error(asyncResult.error.message);
	        }
	        else {
	
	
	            Office.context.mailbox.item.saveAsync(function (result) {
	            
	                console.log("Meeting Item Save Succeed");
	            });
    
	        }
    }

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Desktop
* Host [Excel, Word, PowerPoint, etc.]: OWA of O365
* Office version number: ______
* Operating System: Win10
* Browser (if using Office Online): Edge

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
@GeoffreyYue1 we aren't able to reproduce the issue. Can you tell us how you're checking whether the custom properties have been saved on the item? Are you checking using the add-in or on Exchange? Can you show us a code snippet of the REST call you're making?

**Comment by GeoffreyYue1** [comment]
As you can see from the description, we have the repro code below
When we run it in O365 OWA, there is no issue on the current user's Calendar, but in Shared Calendar, there is no value when I get the saved property.

```
function btnSetPropertyClick() {
        var item = Office.context.mailbox.item;
        item.loadCustomPropertiesAsync(customPropsCallback);  
    }

    function customPropsCallback(asyncResult) {
        var customProps = asyncResult.value;
        var myProp = customProps.get("myProps");
        console.log("myProp: " + myProp); // First run on current item will return `undefined`.

        // Set myProp custom property.
        customProps.set("myProps", "this is my test property value [Case #:20132451] - O365 addin client setcustomproperty failed even the api return success");
        customProps.saveAsync(saveCallback);
    }

    function saveCallback(asyncResult) {
        if (asyncResult.status === Office.AsyncResultStatus.Failed) {
            console.error(asyncResult.error.message);
        }
        else {


            Office.context.mailbox.item.saveAsync(function (result) {
            
                console.log("Meeting Item Save Succeed");
            });

        }
}
```
When we run the repro code twice in the current user‘s Calendar, Console log output is:

```
myProp: undefined

Meeting Item Save Succeed

myProp: this is my test property value [Case #:20132451] - O365 addin client setcustomproperty failed even the api return success

Meeting Item Save Succeed
```

When we run the repro code twice in the shared calendar, Console log output is:

```
myProp: undefined

Meeting Item Save Succeed

myProp: **undefined**

Meeting Item Save Succeed

```

**Comment by exextoc** [comment]
@GeoffreyYue1 As per discussions with you offline, we are tracking this bug in our backlog.

**Comment by exextoc** [comment]
Internal tracking id: OutlookWeb:87207

**Comment by SteveJerbs** [comment]
@exextoc I know this question may be slightly unrelated to the reported issue but the code above provides an easy context to ask it.  Is it required to call `item.saveAsync()` within the callback passed to the `customProps.saveAsync()` method?  This implementation is working for me however it means I will need to clean up a message in the drafts folder if the user decides not to send the message.   Any input is appreciated!

**Comment by exextoc** [comment]
@SteveJerbs To answer your question, it is not mandatory to call item.saveAsync() within the callback passed to customProps.saveAsync().  The code within the callback to customProps.saveAsync() depends on the functionality of your add-in.  Please refer to the documentation [here](https://learn.microsoft.com/en-us/javascript/api/outlook/office.customproperties?view=outlook-js-preview#outlook-office-customproperties-saveasync-member(1)) to know more about Custom Properties.  We recommend you to start a new thread if you have more questions.
