### ISSUE TITLE
Wait until previous call completes at certain limit

### ISSUE THREAD

**Issue by mdunn416** [OfficeDev/office-js#1225]
## Expected Behavior

I am trying to iterate through a list of words, search the document for each word, once I find it, assign a bookmark to that word. 

## Current Behavior

My code seems to work, but when the lists gets large I am getting an error. 
[Error] Unhandled Promise Rejection: RichApi.Error: Wait until the previous call completes.
	dispatchException (polyfill.js:12173)
	invoke (polyfill.js:11894)
	asyncGeneratorStep (taskpane.js:9794:104)
	_throw (taskpane.js:9796:310)
	promiseReactionJob

## Steps to Reproduce, or Live Example

* Link to live example: ______

`async function createBookmark(phrase, dict){

  await Word.run( async (context) =>
{
  let x = context.document.body.search(phrase, {matchCase: true}).getFirst();
  await context.sync();      
      x.insertBookmark(`${dict[phrase].bookmarkterm}`);
      await context.sync();

    
});

}`

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

**Comment by Rick-Kirkham** [comment]
You say that you are iterating through the words, but the code you've provided doesn't have any loops. Could you please clarify?

Also, it looks like your code only inserts a bookmark to the _first_ instance of each term. Is that your intention? 

Finally, please take a look at this article: [Avoid using context.sync in a loop](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/correlated-objects-pattern). In particular, note this "Just as the commands in a synchronization batch job are queued, the batch jobs themselves are queued in Office, but Office supports no more than 50 batch jobs in the queue. Any more triggers errors.".

**Comment by mdunn416** [comment]
I have read the link on Avoiding using context.sync inside a loop. An issue I seem to be having is passing a large number of items (in the dict argument) to search. (ie. Search for all instances dict = {'word1', 'word2', 'word3',.....} of a large list of words inside a document). 

The code works on smaller lists (<20 items to search) but seems to fails when the list gets large (300+). When I say fail, I mean the second for loop does not seem to ever get executed.


```
async function linktoBookmark2(dict){
  Word.run(async (context) => {

    //const allSearchResults = {};
    let allSearchResults = {};
    let keys = Object.keys(dict);
    for (let i = 0; i < keys.length; i++) {
      let options = Word.SearchOptions.newObject(context);
      options.matchCase = true;
      let currentKey = keys[i]
      
      let searchResults = context.document.body.search(dict[currentKey].searchterm, options);
      searchResults.load('items');
      allSearchResults[currentKey] = {search: searchResults}
    }
    
    await context.sync()
    console.log(allSearchResults);
    let keysdicttmp = Object.keys(allSearchResults);
    console.log(keysdicttmp)
    
    for (let i = 0; i < keysdicttmp.length; i++) {
      let currentKey = keysdicttmp[i];
      let total_range = allSearchResults[currentKey].search;
      
      let range_len = total_range.items.length;
      let book = dict[currentKey].bookmarkterm
      console.log(book);
      for(let x = 0; x<range_len; x++){
        total_range.items[x].hyperlink = '#'+book;
        
      }
    }

    await context.sync();
});
}
```

**Comment by Rick-Kirkham** [comment]
Thanks. Can you reproduce this problem in the Script Lab tool? If so, can you export a gist of the sample that I can use to try and reproduce?

**Comment by mdunn416** [comment]
Hi here is a gist sample of the complete code. As I mentioned this works fine on smaller docs, but when I try and search large documents for all instances of many words (300+) I run into some kind of issue.

 [https://gist.github.com/mdunn416/88fdef8499265e2ff46190347c7ae1ac](url)

Thanks

**Comment by Rick-Kirkham** [comment]
I've tried with up to 422 words and I've got no errors. I don't see anything visual change in the document, even with very small numbers of words. What should I see if it succeeds?
