### ISSUE TITLE
FilterCriteria objects with invalid null properties

### ISSUE THREAD

**Issue by tjcrowder** [OfficeDev/office-js#1226]
## Expected Behavior

Being able to use the [`FilterCriteria`](https://docs.microsoft.com/en-us/javascript/api/excel/excel.filtercriteria?view=excel-js-preview) objects we receive from autofilter:

```js
let saveCriteria = autoFilter.criteria.slice();
```

...to (re)apply those criteria later via `apply`:

```js
sheet.autoFilter.apply(appropriateRange, index, saveCriteria[index]);
```

## Current Behavior

The objects from the `criteria` array have properties with the value `null`, but the TypeScript type information says they shouldn't be able to be `null` (they can be `undefined`, but not `null`) and when you try to use them with `apply`, it throws the following error:

> RichApi.Error: The argument is invalid or missing or has an incorrect format.

As a result, you can't use the `FilterCriteria` object you got to (re)apply filtering criteria.

At the moment I'm working around it by removing those properties:

```js
const entry = Object.fromEntries(
    Object.entries(saveCriteria[index]).filter(([name, value]) => value !== null)
);
sheet.autoFilter.apply(dataRange, index, entry);
```

## Steps to Reproduce, or Live Example

As above.

## Context

This issue cost us a couple of hours of trial and error figuring out why the API wasn't working correctly, creating the workaround, and reporting the issue, but ongoing impact is minimal. But obviously it would be better if we don't have to massage the objects like that.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online (but presumably would affect desktop Excel as well)
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Office 365 build 16.0.13014.35904
* Operating System: Windows
* Browser (if using Office Online): Chrome

## Useful logs

N/A

**Comment by lindalu-MSFT** [comment]
HI PM team @sohailzafar @weshi Here's a bug in W/X/P etc. and I'm not sure who to assign to look into this. Please advise!

**Comment by lumine2008** [comment]
We can repro this issue, a bug (4262773) is created

**Comment by tjcrowder** [comment]
I was wrong about the impact of this: It's a big problem holding up our progress rolling out our add-in, because I cannot save and restore filtering settings when there's more than one filter.

If I do a text filter ("begins with" "tjc") and a value filter (TRUE), the `criteria` array has four objects, which look like this:

```js
[
    {
        "@odata.type": "Microsoft.ExcelServices.FilterCriteria",
        "color": null,
        "criterion1": null,
        "criterion2": null,
        "filterOn": "BottomItems",
        "subField": null,
        "dynamicCriteria": "Unknown",
        "icon": null,
        "operator": "And",
        "values": null
    },
    {
        "@odata.type": "Microsoft.ExcelServices.FilterCriteria",
        "color": null,
        "criterion1": "=tjc*",
        "criterion2": null,
        "filterOn": "Custom",
        "subField": null,
        "dynamicCriteria": "Unknown",
        "icon": null,
        "operator": "Or",
        "values": null
    },
    {
        "@odata.type": "Microsoft.ExcelServices.FilterCriteria",
        "color": null,
        "criterion1": null,
        "criterion2": null,
        "filterOn": "BottomItems",
        "subField": null,
        "dynamicCriteria": "Unknown",
        "icon": null,
        "operator": "And",
        "values": null
    },
    {
        "@odata.type": "Microsoft.ExcelServices.FilterCriteria",
        "color": null,
        "criterion1": "=TRUE",
        "criterion2": null,
        "filterOn": "Custom",
        "subField": null,
        "dynamicCriteria": "Unknown",
        "icon": null,
        "operator": "Or",
        "values": null
    }
]
```
Removing those invalid `null` properties and putting those objects back results in the uninformative:

> `RichApi.Error: The argument is invalid or missing or has an incorrect format.`

I can get two of them (the second and fourth) to go back to the API if I remove the properties with `null` and remove the `dynamicCriteria` property, but I can't get it to accept the other two (the first and third). I can't find any combination that lets me put in a filter within no `criterion1` or `criterion2`. I've tried `""` and `undefined` with no success.

Any advice on how to successfully save and restore filters in the face of this bug would be **hugely** welcome. :-) Thanks in advance!

**Comment by lindalu-MSFT** [comment]
@lumine2008 Hi, do we have a workaround for this customer until the bug gets resolved?

**Comment by tjcrowder** [comment]
@lumine2008 - Any progress? I need to give an update on this soon... Thanks. :-)

**Comment by gingerjia** [comment]
@tjcrowder can you try to call sheet.autoFilter.clearCriteria() to restore the first and third filter when you found both criterion1 and criterion2 are null in the filter?

**Comment by tjcrowder** [comment]
@gingerjia  - I'm afraid I don't understand. Why would [`clearCriteria`](https://docs.microsoft.com/en-us/javascript/api/excel/excel.autofilter?view=excel-js-preview#clearcriteria--) **restore** anything?

**Comment by gingerjia** [comment]
Hi @tjcrowder ,  let me try to understand your question and clarify my suggestion.
1. First you get the four criterias object and stored them in saveCriteria array
let saveCriteria = sheet.autoFilter.criteria.slice();
In the four criterias, the second and fourth are with criterion1 value, the first and third are empty criteria in fact.

2. Someone else modified your data criteria by UI or some other ways, and you want to re-apply the above four criterias
You can call sheet.autoFilter.clearCriteria() first, then your data will go back to the state with criterion1 and criterion2 both are null, just same as above the first and third criteria object.
Then you apply the second and fourth criterions.
Now all criterias are restored.

If anything I misunderstand, please let me know. Thanks.

**Comment by tjcrowder** [comment]
@gingerjia - Thanks. It's not that someone *else* changes the filter. My code updates the data being filtered, and so has to save and then turn off the filters (`clearCriteria`), update the data, and then re-apply the filters.

Please see [this comment](https://github.com/OfficeDev/office-js/issues/1226#issuecomment-697553705); I've previously tried reapplying only the second and fourth entries (with and without `null`s removed), and it just doesn't work.

To replicate the situation:

1. Have multiple columns with data in them.
2. In the UI, apply at least two autofilters (for instance, a date range on one column and text prefix on another)
3. In code, save those filters, use `clearCriteria` to clear the existing criterial, update the data, then try to reapply the filters.

Microsoft have acknowledged there's a bug here. I'd love to find a successful workaround, but all of my efforts so far have failed with either A) Variations on the uninformative *"The argument is invalid or missing or has an incorrect format."* error, or B) Just not filtering the data correctly.

Thanks again for trying to help.

**Comment by gingerjia** [comment]
@tjcrowder , thanks very much for your detail scenarios info. I'm also an engineer from Microsoft, haha.
Here I shared my work gist for your reference: [https://gist.github.com/gingerjia/65ac444476035c03032f74914deb1613](url)
This is my test data:
![image](https://user-images.githubusercontent.com/62282034/96076546-29b31f00-0ee0-11eb-9322-6426c85391a9.png)
Steps:
1. Click Apply Filter;
2. Click reApplyFilter-> it will store filter first, update D4 cell's value, apply the original filter again.
This should be the same scenario as your described. Hope it works for you!

**Comment by lumine2008** [comment]
Please re-activate if you still have question regarding to our workaround
