### ISSUE TITLE
Access Denied - PivotTable Add

### ISSUE THREAD

**Issue by sanjaygovindan** [OfficeDev/office-js#1227]
## Expected Behavior
Expect a pivot table to be created. This code was working prior to the new release of office js.

## Current Behavior
Currently receiving an error - AccessDenied: You cannot perform the requested operation

## Steps to Reproduce, or Live Example
Via the api:

1. Create new worksheet
2. Set new worksheet to active
3. Get active worksheet object from workbook object and set to new variable
4. Add pivot via active worksheet variable

## Your Environment

Windows 10
Excel Web Add In (Office Version:2005, 12827.20268 )

## Useful logs
![image](https://user-images.githubusercontent.com/19772737/85101645-31bac500-b246-11ea-945b-6545ca9af158.png)

**Comment by code9** [comment]
Had the same issue using 
https://appsforoffice.microsoft.com/lib/1/hosted/office.js

switched to a version at:
https://unpkg.com/@microsoft/office-js/  (ver 1.1.38) and all appears fine. 

Found in a similar issue here
https://github.com/OfficeDev/office-js/issues/421

**Comment by lindalu-MSFT** [comment]
@lumine2008 @tutieu Apparently, the new office-js breaks his code. Please advise! Thanks,

**Comment by vivagonna** [comment]
+1 the same issue.

**Comment by lumine2008** [comment]
@code9 , @vivagonna , I have tried on my Desktop/Mac and Excel online, it seems not repro, would you please share your sample code to us? thanks.

**Comment by vivagonna** [comment]
@lumine2008 I am using the example code in this doc to create a pivot table https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-pivottables. @code9 is right, this issue happens with the version on official CDN https://appsforoffice.microsoft.com/lib/1/hosted/office.js , switching to older version mitigate this issue.

**Comment by sanjaygovindan** [comment]
Hi just confirming, had the same experience as  @vivagonna  & @code9, in both problem and workaround. 

New office update came through last night. Version 2005. Build 12827.20336 Click-to-run. Cleared add in cache, and away we go!

It now looks like I am able to use the Add pivot function again, although slight bug with this as it doesn't allow me to use a table class as the source.


```
let table = ctx.workbook.tables.getItem(dataTableId);
let tableDataRange = table.getRange();
tableDataRange.load('address');
await ctx.sync();
		
activeSheet.pivotTables.add(sheetName, table, rangeToPlacePivot);
await ctx.sync();
```
	



Get the classic Invalid Argument error, explaining that the table variable isn't what it expected. 
This code works when replacing table for a range object, so just wondering if the API docs are up to date? / Am I missing something here?

**Comment by lumine2008** [comment]
Hi @sanjaygovindan, may i know if this issue can still repro in latest version? thanks

**Comment by lumine2008** [comment]
I am going to close this issue, please reopen if you still observe this issue. thanks.
