### ISSUE TITLE
Unable to get token

### ISSUE THREAD

**Issue by sandeep007bonds** [OfficeDev/office-js#1229]
Hi,
I have done all the steps but unable to get token.
I am developing Excel add in, I got the login popup only after login a got error "missing grant for this add-in : pre authorization missing "

![image](https://user-images.githubusercontent.com/48192725/85129431-b9a5cc80-b250-11ea-9ab6-3c5583f400d1.png)

Below is the API permission screenshot

![image](https://user-images.githubusercontent.com/48192725/85129034-12289a00-b250-11ea-8f55-c28443340d4c.png)

Addin manifest file

![image](https://user-images.githubusercontent.com/48192725/85129131-3ab09400-b250-11ea-852e-88c2b3f13afb.png)

please let me what I am missing here.

**Comment by sandeep007bonds** [comment]
> I'm going to move this to the office-js repo, so the bot will stop closing it.

Thanks

**Comment by Rick-Kirkham** [comment]
Why do you have 5 preauthorized GUIDs instead of 4? Where did the GUID that begins df83... come from?

**Comment by sandeep007bonds** [comment]
> Why do you have 5 preauthorized GUIDs instead of 4? Where did the GUID that begins df83... come from?

Earlier it was only 4 that mentioned in doc..but when nothing was working and I thought I am missing something so I added the client I'd of register app to test. But nothing work for me

**Comment by Rick-Kirkham** [comment]
Remove that extra preauthorization with the client ID. You don't need to preauthorize your add-in to itself. It's misleading and might cause problems.

But then add a new preauthorization for this GUID: 08e18876-6177-487e-b8b5-cf950c1e598c 
See if that fixes it.

**Comment by sandeep007bonds** [comment]
Remove the client Id and added the GUID: 08e18876-6177-487e-b8b5-cf950c1e598c as per your suggestion, but getting the same error. I want to know what this new guid is all about where it came from.

Please let me know if you want anything from my side. 

![image](https://user-images.githubusercontent.com/48192725/85194304-f0c8bc00-b2ea-11ea-88a7-66b1c20c6c29.png)

**Comment by Rick-Kirkham** [comment]
I believe that the new GUID is meant to replace two or more of the original 4, so that preauthorization can be done faster, but I wasn't sure if it had been rolled out yet and it was the weekend, so I thought I'd have you try it. Looks like it did not help, so you can just remove it again.

**Comment by Rick-Kirkham** [comment]
@jargil Can you help this customer? He seems to be preauthorized, but he's getting an error that says he is not.

**Comment by sandeep007bonds** [comment]
@jargil  Please update..

**Comment by jargil** [comment]
@sandeep007bonds - for your screenshot for the "Expose a API" section, could you please show how the top part with the id uri and the scope look like?
Could you also confirm what Office client and what version of Office you're using?

**Comment by sandeep007bonds** [comment]
Hi @jargil,

Please find the attached screenshot.

I am using office 2016.

![image](https://user-images.githubusercontent.com/48192725/85519251-d3635d00-b61e-11ea-924c-e7c24aeec477.png)

**Comment by jargil** [comment]
@sandeep007bonds - the scopes uri is cut in the screenshot, what's the full string?
Could you also be specific about what Office version?  See this: https://support.microsoft.com/en-us/office/about-office-what-version-of-office-am-i-using-932788b8-a3ce-44bf-bb09-e334518b8b19

**Comment by sandeep007bonds** [comment]
@jargil Please find the screenshot for office version and scope uri.

![image](https://user-images.githubusercontent.com/48192725/85621173-77322480-b682-11ea-8c13-2b8c69796d05.png)


![image](https://user-images.githubusercontent.com/48192725/85620998-36d2a680-b682-11ea-8a78-e710a8ba817e.png)

**Comment by jargil** [comment]
@sandeep007bonds - thanks. The scope looks good. The second screenshot unfortunately missed the version details which should be right below the Updates, could you please paste that part?

Next set questions would be:
- How are you deploying this add-in to this machine?
- Could you please also share the full code snippet that calls the getAccessTokenAsync API? I'm interested in seeing what parameter you pass for the AuthOptions.
- Did you grant permissions to your add-in to access your user's identity?

**Comment by sandeep007bonds** [comment]
@jargil Please find the attached complete screenshot

![image](https://user-images.githubusercontent.com/48192725/85772146-31389780-b73a-11ea-9b40-6fc6979de2c0.png)

And answers to your questions are: 

1. Add in is under development so we are using localhost..

2. I am using below code..
`async function getToken() {
    var returnObject;
    Office.context.auth.getAccessTokenAsync(function (result) {
        debugger;
        if (result.status === "succeeded") {
            var token = result.value;
            returnObject = token;
        } else {
            console.log("Error obtaining token", result.error);
        }
    });
    return returnObject;
}
`

3. I am not aware of this, how can we grant permission to addin to using identity, but in addin manifest I have added below code as per online document.

`<WebApplicationInfo>
      <Id>df83f308-8a7c-4d1c-aa75-fa482ad1aefa</Id>
      <Resource>api://localhost:44355/df83f308-8a7c-4d1c-aa75-fa482ad1aefa</Resource>
      <Scopes>
        <Scope>Files.Read.All</Scope>
        <Scope>offline_access</Scope>
        <Scope>openid</Scope>
        <Scope>profile</Scope>
      </Scopes>
    </WebApplicationInfo>`

**Comment by sandeep007bonds** [comment]
@jargil FYI I am able to see the authentication popup where I can put username and password after that I get the error.

**Comment by jargil** [comment]
@sandeep007bonds - thanks for the responses!
For 1 above, I was asking about how you're deploying your add-in to Office, e.g. are you sideloading? How? Are you Centrally Deploying?

For the API call, could you try calling with these AuthOptions and let me know what you see?
{ allowConsentPrompt: true, allowSignInPrompt: true }
The first one, allowConsentPrompt should make Office show a dialog where you should see some information about granting your add-in access to your user's identity. With the information I have, I think this is what is missing.

https://docs.microsoft.com/en-us/javascript/api/office-runtime/officeruntime.authoptions?view=excel-js-preview

**Comment by sandeep007bonds** [comment]
@jargil I am using sideloading..and I have tried auth options too.. was getting the same error. I am trying this again and update you in few minutes.

**Comment by sandeep007bonds** [comment]
@jargil thanks for your help, now its working after adding this 2 auth options.

I was referring [https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet](url)

where { allowSignInPrompt: true, forMSGraphAccess: true } are mentioned not the "allowConsentPrompt: true" tha was confusion. 

But thanks alot for your help.

**Comment by jargil** [comment]
Thanks for the update, @sandeep007bonds 

That's useful feedback for our samples.
