### ISSUE TITLE
Some inline styling in markup passed to insertHtml() gets ignored

### ISSUE THREAD

**Issue by dinkom** [OfficeDev/office-js#123]
Some of the inline CSS rules in markup passed to `insertHtml()` get ignored (like `padding-left` and `text-indent`), while some works OK (`color`, `font-weight`).

## Expected Behavior
All styling should work as expected.

## Current Behavior
`padding-left` and `text-indent` are ignored when passed to `insertHtml()` as a part of the markup.

## Steps to Reproduce, or Live Example
Code for ScriptLab can be found here: https://stackoverflow.com/questions/50172647/office-js-format-html-in-a-contentcontrol-with-inline-css/50178798

Example of how it should look like is here: http://cssdeck.com/labs/ocplq2la

## Context
I am working on an add in for inserting references and bibliographies inside documents. Some citation styles require a hanging indent, which does not work unless this is fixed.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.12 (180410)
* Operating System: macOS High Sierra

**Comment by BilalAlam173** [comment]
any follow up on this one? this is a very critical issue, only handful of styles are working. This should be resolved asap

**Comment by JuaneloJuanelo** [comment]
sorry about the amazing delay on this, is this issue still current?

**Comment by dinkom** [comment]
> sorry about the amazing delay on this, is this issue still current?

I'm not sure; I'm no longer involved in that project.

**Comment by hjkim-MSFT** [comment]
A workaround is appending <br> tag to the html input.
