### ISSUE TITLE
Office.context.mailbox.item is undefined in ItemChanged after selecting an appointment

### ISSUE THREAD

**Issue by oyvindo** [OfficeDev/office-js#1230]
Platform: Windows 10 Enterprise, v1903
OWA and Outlook 365 ProPlus
(https://appsforoffice.microsoft.com/lib/beta/hosted/office.js)

Description:
I'we noticed that appointment messages delays initialization of Office.context.mailbox.item in the itemChangeHandler if args.initialData is not accessed:

```
const handleItemChanged = args => {
  console.log('item pre access initialData', Office.context.mailbox.item);
  const isEmail = args.initialData.itemType === 1;
  console.log('item post access initialData', Office.context.mailbox.item);
  if (isEmail) {
    console.log('It is an e-mail');
  } else {
    console.log('It is NOT an e-mail');
  }
};

```
In our case, we only handle regular e-mails. 
Scenario is:

1. Select a regular e-mail => Office.context.mailbox.item has value in the first and second console.log
2. Select an appointment message => Office.context.mailbox.item is null in the first console.log but  has value in the second
For some reason the second console.log comes two times (I cannot figure out why)
3. Select a regular e-mail => Office.context.mailbox.item is still null in the first console.log but in the seccond, it has got value and initialData.itemType is 1.
The second console.log comes two times
4. Select an appointment message.
The second console.log comes only once

My point is that if you only rely on Office.context.mailbox.item in the eventhandler, item won't have a value while selecting, if you just selected an appointment. Unless you access initialData first.

Office.context.mailbox.item has a value, item.message is always "message" which may make sense while itemClass i different. Still, I would find it more likely to have Office.context.mailbox.item.itemType aligned with the enum value in initialData.itemType.

_Originally posted by @oyvindo in https://github.com/OfficeDev/office-js/issues/1134#issuecomment-642524712_

**Comment by exextoc** [comment]
@oyvindo we are unable to reproduce this on OWA. Is it possible to share a video / screenshots of what exactly you're doing to reproduce the problem (for each step)? What do you mean by "appointment message" - do you mean a meeting request?
