### ISSUE TITLE
Word: binding.getDataAsync is not a function in Word on the web

### ISSUE THREAD

**Issue by algomaster99** [OfficeDev/office-js#1233]
## Expected Behavior
I should have been able to successfully get the data associated with the binding according to [this API](https://docs.microsoft.com/en-us/javascript/api/office/office.binding?view=word-js-preview#getdataasync-options--callback-).

## Current Behavior
A `TypeError` is thrown which says "`binding.getDataAsync` is not a function on web version of Word"

## Steps to Reproduce, or Live Example
Try using `binding.getDataAsync` on the web version of MS Word.

**Live Example**

https://gist.github.com/algomaster99/9fa0f3ff7af7ae4b62ff13fc02927e00

1. Inserts a text "Aman Sharma" in a paragraph and wraps it in a content control.
2. Attaches an event listener (`Office.EventType.BindingDataChanged`).
3. Whenever the data is changed, `handler` is executed which has this piece of code responsible for the error.
```js
binding.getDataAsync(result => {
    console.log(result.value)
  })
```

## Context
It works perfectly on the desktop version of MS Word but I am getting this error in the web version.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number:
* Operating System: Windows 10
* Browser (if using Office Online): Edge (Version 83.0.478.54)
* API version: https://appsforoffice.microsoft.com/lib/beta/hosted/office.js

## Useful logs

- [x] Console errors: `Uncaught TypeError: binding.getDataAsync is not a function`
- [x] Screenshots:
<img width="960" alt="word-web" src="https://user-images.githubusercontent.com/35191225/85368944-cd4f7c80-b549-11ea-90e3-a1f4344dda7f.PNG">

- [ ] Test file (if only happens on a particular file)

**Comment by lindalu-MSFT** [comment]
@algomaster99 Thanks for reporting this! I've assigned this to the Word feature team to help triage.

**Comment by MandytMSFT** [comment]
@algomaster99  The issue can't repro on my side, could you help try again ? Whenever i change the text, the handler can execute successfully. Our CDN has some known issue these days, that may be related. We just rolled out a new version today  

![image](https://user-images.githubusercontent.com/52641972/85528845-03225d00-b63f-11ea-9dde-75a3557d9fa8.png)

**Comment by algomaster99** [comment]
@MandytMSFT I tried on `ScriptLab` only. Can you please share the CDN link with me?
I was currently using the [preview version](https://appsforoffice.microsoft.com/lib/beta/hosted/office.js).

Can you instead open the browser developer tool? The error is being logged there.
![error](https://user-images.githubusercontent.com/35191225/85554039-269ad700-b642-11ea-8f95-5c6d0d85059c.PNG)

What actually needed to be logged is the data of the binding. `MyBnding` is the `id` of the Binding.

**Comment by algomaster99** [comment]
@MandytMSFT Hi! Were you able to reproduce the bug? Please help me out :)

**Comment by MandytMSFT** [comment]
@algomaster99  sorry for the late response. I can repro with your gist , and i did a rough investigation, seems the event arg returned by BindingDataChanged event is different between word online and desktop. You can simply output the binding in handler to look details. And getDataAsync is missed on online.  I opened a BUG 4267228 for product team to address

**Comment by algomaster99** [comment]
@MandytMSFT thanks for the response! Is there any other to get the value of a binding?

**Comment by MandytMSFT** [comment]
getDataAsync is the right way, could you help try below code to get the binding object by getByIdAsync before calling getDataAsync ? It works at my side.

async function handler(event) {
  const { binding } = event;
  Office.context.document.bindings.getByIdAsync(binding.id, function (asyncResult) {
    asyncResult.value.getDataAsync((result) => {
      if (result.status === Office.AsyncResultStatus.Failed) {
        console.log(result);
      } else {
        console.log(result.value);
      }
    });
  });
}

**Comment by algomaster99** [comment]
@MandytMSFT yeah, this snippet worked. But I think it is a little redundant since we already have a reference to the `binding`. We shouldn't need to get it again using `Office.context.document.bindings.getByIdAsync`. I hope "BUG 4267228" is fixed soon :sweat_smile: Thanks for helping out though :)
