### ISSUE TITLE
Outlook: loadCustomPropertiesAsync can't get property saved by mapi

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1234]
Why loadCustomPropertiesAsync  can only get empty if the property saved by graph api but graph api can get property saved by 'customProps.set' ?
Just wondering they all saved info to property but can't read each other.
It's by design?

## Expected Behavior
both graph api and office api can read properties no matter which api saved them.

## Current Behavior
We register an app and use it's id on graph api save and read properties.
At the same time we also use office api save and read properties.
But it's really interesting that graph api can read properties saved by 'customProps.set' but the other way around doesn't work.

## Steps to Reproduce, or Live Example
Try save something to property by graph api and then try use loadCustomPropertiesAsync  read them.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ALL
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16,19 and online
* Operating System: Windows and Mac
* Browser (if using Office Online): Chrome

**Comment by exextoc** [comment]
@SWei1234 Could you explain how you're setting custom properties using graph API? Could you post a code snippet?

**Comment by SWei1234** [comment]
@exextoc  Sorry for misleading. The property is saved by mapi. And can be successfully read by graph api. 
But loadCustomPropertiesAsync  can only read empty result.
If necessary I can provide mapi save code.

**Comment by exextoc** [comment]
Hey @SWei1234 ,

Sure, can you go ahead and provide us the Mapi save code that you're using? This will help us look into this issue better.

**Comment by SWei1234** [comment]
Hi @exextoc 
    Here is how mapi save properties:
    `HRESULT hr = S_OK;
     if(!m_spAppt)
			break;
		CComPtr<IMessage> spMsg;
		hr = m_spAppt->get_MAPIOBJECT( (IUnknown**) &spMsg);
		if( (spMsg == NULL) || FAILED(hr) )
		{
			break;
		}

		MAPINAMEID PropName;
		PropName.lpguid				= (LPGUID) &PS_PUBLIC_STRINGS;
		PropName.ulKind				= MNID_STRING;
		PropName.Kind.lpwstrName	= bstrName;

		LPMAPINAMEID lpPropName		= &PropName;

		LPSPropTagArray lpPropTag;
		hr = spMsg->GetIDsFromNames(1, &lpPropName, MAPI_CREATE, &lpPropTag);
		//... 
        //Exception handler
        //...

		ULONG ulPropTag = PROP_TAG(PT_UNICODE, PROP_ID(lpPropTag->aulPropTag[0]));
		CComPtr<IStream> spStream;
		hr = spMsg->OpenProperty(ulPropTag,
			&IID_IStream,
			STGM_READWRITE | STGM_DIRECT,
			MAPI_CREATE | MAPI_MODIFY,
			(IUnknown**) &spStream);

		if( (spStream == NULL) || FAILED(hr) )
		{
			break;
		}

		ULONG cbWritten;
		hr = spStream->Write(bstrValue, ::SysStringByteLen(bstrValue), &cbWritten);
		if(FAILED(hr))
		{
			break;
		}

		hr = spStream->Commit(0);
		if(FAILED(hr))
		{
			break;
		}
`
Any idea?

**Comment by exextoc** [comment]
Does loadCustomPropertiesAsync API fails on Outlook Online (OWA) only or does it fail on Outlook Desktop clients Win32/Mac as well?

**Comment by SWei1234** [comment]
I have tried on both windows and Mac outlook and online , this api actually not response failed but just get empty result.
But the graph api on COM can get the correct data on the same event.

**Comment by exextoc** [comment]
@SWei1234 can you also share the loadCustomPropertiesAsync code snippet which you are using to get the custom properties via Add-in?
Can you run this test code to set and get custom properties via Add-in APIs and see if returns custom property value on get.

**// Set and save custom property** 
Office.context.mailbox.item.loadCustomPropertiesAsync(
 function customPropsCallback(asyncResult) {
  if (asyncResult.status == "failed") {
   console.log("Failed to load custom property");
  }
  else {
   var customProps = asyncResult.value;
   customProps.set("myProp", "value");
   customProps.saveAsync(
    function (asyncResult) {
     if (asyncResult.status == "failed") {
      console.log("Failed to save custom property");
     }
     else {
      console.log("Saved custom property");
     }
    }
   );
  }
 }
);


**// Get custom property**
Office.context.mailbox.item.loadCustomPropertiesAsync(
 function customPropsCallback(asyncResult) {
  if (asyncResult.status == "failed") {
   console.log("Failed to load custom property");
  }
  else {
   var customProps = asyncResult.value;
   var myProp = customProps.get("myProp");
   console.log(myProp);
  }
 }
);

**Comment by SWei1234** [comment]
Hi @exextoc 
My loadCustomPropertiesAsync  code is same as you write above. 
In your way , I can save and read property. 
But only read empty result on property saved by mapi.

**Comment by exextoc** [comment]
@SWei1234 Can you download this MAPI exe from [here](https://github.com/stephenegriffin/mfcmapi/releases/tag/17.0.17099.01 ) and try to set custom property using Property -->Additional Property -->Add and check in your Add-in. It seems to work fine on our side. 
Can you share your Add-in so that we can try to repro it at our end?

**Comment by SWei1234** [comment]
@exextoc I can provide you our reading part code but I can't provide you all the project. And other codes think is unnecessary for this question.
I want to read the properties from zoom plugin. Can you try read the properties from zoom plugin?

**Comment by stephenegriffin** [comment]
This is all by design. The CustomProperties interface provides access to a bag of properties specific to the add-in using it. These properties are not stored as individual MAPI properties, but rather as a blob on a single MAPI property (you can find this property with some digging in MFCMAPI). The CustomProperties interface does NOT provide generic access to any MAPI property. That's not part of the design and likely never will be.

If your goal is to access generic MAPI properties from your add-in you will need to use EWS or Graph.

**Comment by SWei1234** [comment]
Thank you so much @stephenegriffin @exextoc
