### ISSUE TITLE
Outlook on Mac: Removing any recipient in on-send hook breaks recipient change event handler in parent task pane

### ISSUE THREAD

**Issue by jak-hammond** [OfficeDev/office-js#1236]
We have some code that is invoked when the user sends the message. This displays a prompt to the user allowing them to confirm some details and add/remove any recipients as well. We have found an issue where, if they remove all the recipients and then decide to cancel the send, the associate event in the task pane no longer fires.

## Expected Behavior
If all recipients are removed from within the context of the on-send code, the event handler in the associated task pane should still fire.

## Current Behavior
All recipients are removed and then if the on send event is cancelled and the user adds more recipients to the message in main compose window, the recipient change handler is not fired.

## Steps to Reproduce, or Live Example
https://github.com/jak-hammond/office-js-on-send

* Additional details:
  1. Open side panel
  2. Click Run button once (multiple times will register multiple handlers)
  3. Open console
  4. Add some recipients to the message (console events logged)
  5. Send the message
  6. All recipients will be removed and send event will be cancelled
  7. Add another recipient to the message (console will log nothing)

## Context
We are providing some functionality to the user both during compose and on send of their message. With this event breaking if all recipients are removed on send then the add-in has to be closed and re-opened which is a poor user experience.

Windows Outlook and Office Online (tested under Chrome) seem unaffected by the issue and work as intended.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.39 (20060705)
* Operating System: 10.15.5
* Browser (if using Office Online): -

**Comment by jak-hammond** [comment]
A clarification here, it seems that the recipient change notifications are removed when **ANY** recipient is removed from the list, not just removing all of them, I did some more testing and confirmed it is more common than the edge case when all users were removed.

**Comment by jak-hammond** [comment]
@lindalu-MSFT going from my previous comment, seeing as you updated the title, after some more testing, it isn't just removing all recipients, but the issue seems to be present when removing any recipient whilst the on-send hook is active causes the event handler to be removed/made inoperable.

**Comment by exextoc** [comment]
Hi @jak-hammond, we are able to reproduce this issue on Mac. Thanks for reporting this bug. We have added it to our backlog and will work towards fixing it. We'll update this thread when it is fixed, but unfortunately do not have any timelines to share at this point.

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 16.40 (20070801) or later. Depending on the release channel a customer is on, getting an updated build can take anywhere from 4-8 weeks.

**Comment by jak-hammond** [comment]
I've tested it on the original repro app I submitted and can confirm this issue appears to be fixed, thanks again 👍

**Comment by exextoc** [comment]
Thanks @jak-hammond for confirming.
