### ISSUE TITLE
Disabling/Enabling Commands add-in for button or menu item in Office 365 Online (Excel) is not working as expected. (Preview)

### ISSUE THREAD

**Issue by topkoong** [OfficeDev/office-js#1238]
I have used the preview version of the Office JavaScript API library from the Office.js CDN. https://appsforoffice.microsoft.com/lib/beta/hosted/office.js in the index.html and created <Runtimes> element as the first child under the <Host> element in the VersionOverrides section where it has <Runtime resid="Contoso.SharedRuntime.Url" lifetime="long" /> as a child element of <Runtimes> element.

Also, I have set the resid attribute of the Action.SourceLocation element to exactly the same string as I used for the resid of the <Runtime> element in step 1; for example, Contoso.SharedRuntime.Url. The element looks like this: <SourceLocation resid="Contoso.SharedRuntime.Url"/>.

In addition, I have customized button or menu item to be disabled when the Office application launches by specifying this in the manifest. Just add an Enabled element (with the value false) immediately below (not inside) the Action element in the declaration of the control like so:  

<Control ... id="MyButton">
                  ...
                  <Action ...>
                  <Enabled>false</Enabled>

Unfortunately, the button or menu item is unable to be disabled. I was wondering if you guys could help me out or provide an example/repo of this.

Thank you for your time.

Sample Code: https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario
Environment: Chrome Browser
Product: Office 365 Online

**Comment by topkoong** [comment]
I have also tried sample code from the following repo: https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario, but the buttons and menu items are still enabled.

**Comment by pkkj** [comment]
Hi @topkoong , would you like to provide more information about the environment (like platform, Excel's checkpoint, etc). Thanks.

**Comment by topkoong** [comment]
@pkkj When I tried the sample code from the following repo: https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario from Office 365 Insider Fast Version for Mac (‎Microsoft Excel on the Mac), disabling menu items on page load works perfectly fine. However, when I did the same thing on Office 365 Online through Chrome browser, it doesn't work.

I was wondering if you could help me out 
Thank you for your time.

**Comment by JackyChen200304** [comment]
@topkoong , thanks for helping previewing our feature and provide us the feedback. I assume you are using O365 Online production environment which Single-line ribbon is not enabled yet.

There are several depends for Add-in Commands enable/disable feature, please checkout the preview technical documentation for more detail information about the requirements [https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands](https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands).

As mentioned, Add-in Commands enable/disable API only support new Single-line Ribbon for Office Online and it is also under preview not releasing to production yet.

**Comment by topkoong** [comment]
@JackyChen200304  Thank you for the reply. I'm not sure if I understand single-line ribbon correctly. Apart from UI, what's the difference between single-line ribbon and the traditional UI? I was wondering if you could elaborate more on this. 

Also, I have checked the sample code from Microsoft, and looks like it uses the preview version of the Office JavaScript API library from the Office.js CDN in index.html. Still, there's no Single-line ribbon enabled when using O365 Online with the preview CDN even though it's a beta version.

Thank you once again for your time and consideration.

**Comment by lumine2008** [comment]
Hi @lindalu-MSFT, Thanks for assignment, I think this is UX related issue, therefore you may @ UX team. 
@lliu113, I believe this is in your area, would you please take care of it? thanks.

**Comment by topkoong** [comment]
Any update on this matter?

**Comment by lliu113** [comment]
@topkoong - this feature is no longer in preview, are you still hitting this issue with enable/disable? Looping in @sohailzafar

To answer your previous question, single line ribbon looks like this:
![SLR](https://user-images.githubusercontent.com/6591834/119404898-55c42900-bc95-11eb-8528-244b81f007c0.JPG)

Traditional ribbon looks like this:
![MLR](https://user-images.githubusercontent.com/6591834/119404910-59f04680-bc95-11eb-8a1f-6188a7f2d707.JPG)

**Comment by ElizabethSamuel-MSFT** [comment]
@preethikakiru Can you take a look and reassign as needed? Thanks.

**Comment by KishanVaishnani** [comment]
Hello, @lliu113 @ElizabethSamuel-MSFT Is this feature now available in preview?

**Comment by ElizabethSamuel-MSFT** [comment]
@KishanVaishnani Thanks for asking.

@trigurl Can you investigate and respond to this?

Thanks.

**Comment by davidchesnut** [comment]
Hi @KishanVaishnani yes this feature is released in the [Ribbon API requirement set](https://learn.microsoft.com/javascript/api/requirement-sets/common/ribbon-api-requirement-sets). 

@topkoong sorry this thread has gone on so long. It seems like this issue got fixed by the time of release. But can you please let me know if you are still seeing any issues with command enable/disable? Thanks!
