### ISSUE TITLE
Sideloading Issue with OfficeJS Outlook Add-in on iOS

### ISSUE THREAD

**Issue by TheSamsterZA** [OfficeDev/office-js#124]
## Expected Behavior

[According to the documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability#outlook), requirement set **Mailbox 1.5** is supported on Office for iOS. I expect that, [by adding mobile support on the manifest](https://docs.microsoft.com/en-us/outlook/add-ins/add-mobile-support), I can sideload my add-in and have it appear on my iOS device.

## Current Behavior

My add-in does not appear on my iOS device (an iPhone 6s with iOS 11.0.3 installed). If I downgrade to requirement set **Mailbox 1.4**, then the sideloaded add-in appears, but I do not want to do this.

## Steps to Reproduce, or Live Example

* Link to live example: https://stackoverflow.com/questions/49789438/sideloading-issue-with-officejs-outlook-add-in-on-ios

* Additional details:
I want to target **only the following platforms**:
  1. Outlook 2016 or later
  2. Outlook on the Web
  3. Outlook 2016 for Mac
  4. Outlook for iOS
  5. Outlook for Android

## Context

I currently have a few add-ins using requirement set Mailbox 1.5 up on the Office Store. I have been waiting for Office for iOS and Office for Android to support Mailbox 1.5, so that all I would need to do is to [add mobile support on the manifest](https://docs.microsoft.com/en-us/outlook/add-ins/add-mobile-support), and then I could test my add-in on these new platforms.

However, doing this has proven incredibly difficult and I have been trying to get some help from Microsoft regarding this issue for close to a whole month now. So far, I have tried contacting Microsoft via:

- [StackOverflow](https://stackoverflow.com/questions/49789438/sideloading-issue-with-officejs-outlook-add-in-on-ios)
- Github (this issue and [one on the Docs repo](https://github.com/OfficeDev/office-js-docs/issues/1415))
- Microsoft Support online
- The Support option on the Outlook for iOS app

## Your Environment

* Platform: iOS
* Host: Outlook
* Office version number: 2.76.0
* Operating System: iOS 11.0.3 on an iPhone 6s
* Browser (if using Office Online): N/A

## Useful logs

None. I get nothing. The add-in simply does not appear on my iOS device.

**Comment by TheSamsterZA** [comment]
It is worth noting that my side-loaded add-in appears on Outlook for Android, and I am able to test as I expected. So this is definitely an issue specifically on the iOS side.

**Comment by mlafleur** [comment]
Given that your experience is different than the documentation, your post in [office-js-docs](https://github.com/OfficeDev/office-js-docs/issues/1415) certainly makes sense. 

That said, posting the same issue in multiple locations is likely to create confusion.  I suggest keeping everything in a single place. Given that this is most likely a documentation error, I'll cross-link back and close this one.

**Comment by TheSamsterZA** [comment]
@mlafleur My apologies about cross-posting the issue; I hope you appreciate the confusion I have been experiencing with this. I was not sure whether it was an Office for iOS app problem, or a documentation error.

Given that the documentation was updated in two places back in February/March 2018, I would expect that the client platform (Office for iOS) had pushed out an app update before then. It appears that this might have been working before; see https://github.com/OfficeDev/office-js-docs/issues/1301#issue-293182064.

**Please double-check with the Office for iOS client team about Mailbox 1.5 support.**

For reference, the two places that the documentation was updated are:

1. [Add req set 1.5 support to Outlook for iPhone](https://github.com/OfficeDev/office-js-docs/commit/42d3a02f1a5ff43e2ac8f8110260d88b24b0b2ec#diff-4b8066da9eb5724afeeb500551c29b16) - also references aforementioned https://github.com/OfficeDev/office-js-docs/issues/1301.
**Published doc:** [Understanding Outlook API requirement sets](https://dev.office.com/reference/add-ins/outlook/tutorial-api-requirement-sets?product=outlook&version=v1.5).
2. [Add Outlook for iOS support for req set 1.5](https://github.com/OfficeDev/office-js-docs-pr/commit/2e8605852bea817c8b4a138e43827c8b0d59445a#diff-f950220bc173ee2422366001e5703dc2).
**Published doc:** [Office Add-in host and platform availability#outlook](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability#outlook).

**Comment by TheSamsterZA** [comment]
As of 4 July 2018, `Outlook for iOS 2.83.0` now correctly side-loads my add-in for testing.
