### ISSUE TITLE
Excel: Download in Chrome triggered from excel does not work

### ISSUE THREAD

**Issue by intellectyxArria** [OfficeDev/office-js#1241]
## Issue
Hello every one I just found out that chrome has depreciated download triggered from iframes or sandbox. because of this any download's I trigger does not work as expected inside excel add-in ( Only in chrome ). I found this issue while developing an excel add-in, but it is possible to occur in other MS applications as well ( like powerbi ).

`window.open('*url to my file*', 'Download');`

## Expected Behavior
It should redirect to chrome and download automatically

## Current Behavior
It redirects to chrome but the download starts only after refresh

## Reference Links
Chrome doc- https://developers.google.com/web/updates/2020/04/chrome-83-deps-rems
Question I have raised in stackoverflow - https://stackoverflow.com/questions/62531152/download-in-chrome-triggered-from-excel-does-not-work

##Possible fix
 I think that adding the property 'allow-downloads' to the iframes inside which add-in's are rendered. Please refere the image.

##Reference Image

![iFramereference](https://user-images.githubusercontent.com/33822260/85669688-b8a3ed80-b6dd-11ea-9cfc-a0b80bf0ebfd.jpg)

**Comment by lumine2008** [comment]
It looks like UX related issue, so let me re-direct to @lliu113

**Comment by intellectyxArria** [comment]
Hello team the issue seems to be fixed now. Thanks for the effort
