### ISSUE TITLE
Error while setting Internet Headers on ComposeItem - Outlook

### ISSUE THREAD

**Issue by nikhileshcs** [OfficeDev/office-js#1242]
## Expected Behavior
Internet headers should be set without errors in MacOS Outlook Desktop Version

## Current Behavior
Trying to set the Internet Header is throwing Internal Error with code: 5001

## Steps to Reproduce, or Live Example

* Open a New Email Compose Window
* Try to set a Internet Header from any Add-in
* Additional details:
  1. This issue is reproducible in the MacOS Outlook Desktop Version
  2. Working fine with the Online version of Outlook
  3. Permission Set: `<Permissions>ReadWriteMailbox</Permissions>`

## Context
X Headers are set using the following, these are examples from the Microsoft docs:
```
<script>
        Office.onReady(function () {
            console.log(Office.context.mailbox.diagnostics.hostName);
            setCustomHeaders();
        });

    function setCustomHeaders() {
        Office.context.mailbox.item.internetHeaders.setAsync(
            { "x-preferred-fruit": "orange", "x-preferred-vegetable": "broccoli", "x-best-vegetable": "spinach" },
            setCallback
        );
    }

    function setCallback(asyncResult) {
        if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
            console.log("Successfully set headers");
        } else {
            console.log("Error setting headers: " + JSON.stringify(asyncResult.error));
        }
    }

    setCustomHeaders();

</script>
```

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.38.20061401
* Operating System: macOS Catalina Version 10.15.5 
* Browser (if using Office Online): NA

## Useful logs
- [ ] Console errors
- [x] Screenshots

Issue when tried to set the header using the above code: 
<img width="510" alt="Screenshot 2020-06-25 at 9 49 09 PM" src="https://user-images.githubusercontent.com/14127053/85783373-e2442f80-b744-11ea-9035-ff03bb5ff1e6.png">

Working fine in the Outlook Desktop Version:
![Screenshot 2020-06-25 at 10 51 21 PM](https://user-images.githubusercontent.com/14127053/85783520-056edf00-b745-11ea-9f45-f50203dfb740.png)

**Comment by lindalu-MSFT** [comment]
@nikhileshcs Per previous [issue 1172](https://github.com/OfficeDev/office-js/issues/1172), this has been fixed and will be 100% rolled out to prod.

**Comment by nikhileshcs** [comment]
@lindalu-MSFT @exextoc The issue mentioned by me and the earlier reported are different. Can you please ask outlook engineering team to look into this?

**Comment by exextoc** [comment]
Hey @nikhileshcs ,

Sorry for the late response. However, I am unable to reproduce your issue on the build you mentioned, even from the code snippet that you have shared. is it possible for you to share the manifest of your add-in and a working endpoint where you are facing this issue so that we can look into it?
