### ISSUE TITLE
Outlook add-in to Graph API

### ISSUE THREAD

**Issue by bx-anil** [OfficeDev/office-js#1243]
We plan to use Graph API from Outlook add-in with scopes limited to calendar api (shared calendars) . How best to deal with auth. 
 I have seen the documentation and there seems to multiple options. Can you suggest a best way with least user inputs. 

Tag your question with office-js or outlook-web-addins

**Comment by exextoc** [comment]
By least user inputs, I assume you want to minimize prompts for auth. If your addin is also meant to work with shared calendar, following https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access should do what you want. If this does not seem to fit your scenario, could you expand and perhaps go into the operations you are planning to do with the Graph API?

I also notice that you posted https://github.com/OfficeDev/office-js/issues/1193.  Are the questions related in some way?

**Comment by bx-anil** [comment]
Thanks for the prompt response.
Yes. We are exploring if Graph API will be good enough to cover the short comings because of the issue #1193 . Any by user inputs I mean, no consent page/login page when connecting to graph API . Please let me know if you have any suggestions

**Comment by exextoc** [comment]
An alternative is to use https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins. Note that it is still in preview. If you are using central deployment, the admin consent is granted and user should not see consent page. You will also have to create a AAD app with the calendar share graph scope (and other scopes if any) that you need for the graph API

I am also adding a note on  #[1193 ](https://github.com/OfficeDev/office-js/issues/1193), that fits into that post more.
