### ISSUE TITLE
Outlook: Desktop Version is using different internetMessageId after the mail is composed and sent

### ISSUE THREAD

**Issue by nikhileshcs** [OfficeDev/office-js#1244]
## Expected Behavior
InternetMessageId should be same after sending the email in the Outlook Desktop Version in MacOS.

## Current Behavior
Currently the InternetMessageId is changed after the mail is sent in Outlook Desktop Version.

## Steps to Reproduce, or Live Example
1. Setup sample Add in in MacOS Desktop Outlook Edition. Execute the following code 

```

Office.context.mailbox.item.saveAsync((result) => {
    if (result.status === Office.AsyncResultStatus.Succeeded) {
        let itemId = Office.context.mailbox.convertToRestId(result.value, 'v2.0');
        Office.context.mailbox.getCallbackTokenAsync({isRest: true}, (accessTokenResponse) => {
            if (accessTokenResponse.status === Office.AsyncResultStatus.Succeeded) {
                let accessToken = accessTokenResponse.value;
                let xhr = new XMLHttpRequest();
                xhr.setRequestHeader('Authorization', `Bearer ${accessToken}`);
                xhr.open('GET', `${Office.context.mailbox.restUrl}/v2.0/me/messages/${itemId}?$select=Sender,Subject,InternetMessageId,SentDateTime,ReceivedDateTime,IsDraft`);
                xhr.onload = function (evt) {
                    console.log(xhr.responseText); // check the internetMessageId from here
                };
                xhr.send();
            } else {
                // Handle the error.
            }
        })

    }
})
```

2. Now compose the mail and send it. 

3. Open the receiving end mail box 

4. Check the internetMessageId from the Mail details, it is a mismatch.

* Additional details:
  1. The above is working fine in Outlook online version (tested on chrome)
  2. Also if we try to set the custom internet message headers in MacOS Desktop version, it is failing with internal server error [Reference to that issue](https://github.com/OfficeDev/office-js/issues/1242)
  3. The behaviour is very much inconsistent from Desktop version to Online version. 

I'm currently using Microsoft 365 subscription, so i have access to all high level API set.

## Context
Context behind retrieving the InternetMessageId before sending the email is, we are trying to save some context against a email with internetMessageId as identifier, so when the email is received via Bcc approach, we can log it properly against a previously saved entity. 

We started the development using the Online version, however once we started testing on Desktop Version, things started breaking and we are BLOCKED by this. 

We also looked other alternative approaches like setting InternetMessageHeader and retrieving later in Server once the mail is received, but even it has so many limitations like 
  1. Unable to read the InternetMessageHeader from the MessageRead mode in UI(when we try to know the status by custom message header)
  2. Setting the InternetMessageHeader itself is not working in Desktop Edition with Internal Error 5001

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.38.20061401
* Operating System: MacOS Catalina
* Browser (if using Office Online): NA

## Useful logs
- [ ] Console errors
Nothing is failing, it is the data-mismatch. (This is much dangerous than console errors)

**Comment by exextoc** [comment]
Hey @nikhileshcs ,

Sorry for the late response, but unfortunately, we are unable to reproduce this issue. When we execute the code that you have provided, the internetMessageId in the response text is the same as that is later in the sent email. The only difference is that the internet message Id in case 1 is enclosed within angular brackets. Are you seeing a completely different identifier altogether? Can you share how the IDs look in both the scenarios? (or a dump of the API call response text would also be helpful) Can you confirm that you see this issue on an add-in which is just executing this code (in compose mode) and nothing else?

**Comment by BelikovSergey** [comment]
This is easily reproduced on Windows desktop Outlook from Office 365 when it is working in Online mode. Maybe something broken at Exchange end? Since AFAIK internet-message-id generated and set by it.
