### ISSUE TITLE
Word: Published Add-Ins not Showing on Word Online Using Edge Chromium if Profile Sync is Turned On

### ISSUE THREAD

**Issue by aldvintumbelaka** [OfficeDev/office-js#1245]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I'm having issue when with Word Online in Edge Chromium.
It works fine with local manifest, but once it gets deployed in the Office 365, I can't see the Add Ins.
What I notice is, I can only see the add-ins if sync profile is turned off.
But when sync profile is turned on (using same user credential), I cannot see the add ins.
![image](https://user-images.githubusercontent.com/33532350/85484099-5620f380-b5f0-11ea-9ac4-dc0f39229e48.png)

I've checked the add ins under admin managed and my organizations but it's also empty.
![image](https://user-images.githubusercontent.com/33532350/85484147-7486ef00-b5f0-11ea-8562-6ee0394f8b28.png)
![image](https://user-images.githubusercontent.com/33532350/85484163-7cdf2a00-b5f0-11ea-9cf2-aa9ace8fd30b.png)

Here is what I can see if I'm using same credential but in a different profile where sync is not turned on.
![image](https://user-images.githubusercontent.com/33532350/85484346-da737680-b5f0-11ea-8e36-1c8c801a0e77.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2677af5b-e9b8-f962-25ce-8aa285977c90
* Version Independent ID: c31c7ed9-0a0a-7a65-0d1b-70d6a8b33994
* Content: [Deploy and publish Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish)
* Content Source: [docs/publish/publish.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/publish.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by donlvMSFT** [comment]
Already have internal bug tracking this issue [Bug 4291393](https://office.visualstudio.com/OC/_workitems/edit/4291393) and feature team is working on it. Will update later here.

**Comment by phtai** [comment]
@aldvintumbelaka @xtianfelix Thanks for reporting the issue. I tried to repro the issue but failed.

Do you have multiple work accounts logged in after profile sync is turned on? To verify that you can go to https://www.office.com/login?es=Click and check if it shows a "Pick an account" interface with multiple options.

If you do, this is a known issue and we are already working to fix it. Otherwise, we will need more details to find out the root cause of the problem.

**Comment by NickDarvey** [comment]
Are there any updates on this issue?

I have some additional details which might help others: it appears to be affected by new deployments of our add-in. Notably not where we're changing the manifest, but _changing our application code_ (such that our `taskpane.html` pointed to a new `taskpane.<hash>.js`).

If you get the add-in to appear once in a private/incognito browser session (i.e. ensure only one account signed in), it will subsequently appear in other sessions even if you have multiple accounts signed in. If you make a _change to application code_ it will disappear. If you go back into a private/incognito browser session with only one account signed in, it will reappear and subsequently appear in other sessions with multiple accounts signed in again.

**Comment by JensMadsen** [comment]
@aldvintumbelaka You write: "What I notice is, I can only see the add-ins if sync profile is turned off." Where do you set "sync profile"?
