### ISSUE TITLE
Word: Office.context.ui.displayDialogAsync callback's Dialog is an empty object on Mac using Latest Version

### ISSUE THREAD

**Issue by rkw6086** [OfficeDev/office-js#1246]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Noticed today while testing out my plug-in on Mac using the latest version of Microsoft Word Version 16.38 (20061401), that when I try to hook up addEventHandler from the asyncResult variable in the callback of displayDialogAsync, it's an empty object, {}. Because of this, the addEventHandler function doesn't exist, and it's breaking the flow for our dialogs in Microsoft Word. This was working about 2 weeks ago, now it's not, and it appears to only be on the Mac version of Word.

## Expected Behavior
I expect when I get the callback that asyncResult.value would be the reference to the dialog so I can call addEventHandler and receive events from the dialog when it sends a message back to parent.

## Current Behavior
asyncResult is an empty object, thus no addEventHandler method available.

## Steps to Reproduce, or Live Example
I don't have a live example, but if you set up a dialog and call displayDialogAsync, the callback's asyncResult will be set to "success", but the value will be an empty object. This should be an instance of the dialog.

## Context
This issue is currently breaking my plugin, and we enter beta testing for it next week! 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.38 (20061401)
* Operating System: MacOS Catalina 10.15.5

**Comment by rkw6086** [comment]
@weshi @lindalu-MSFT 

Any updates on what's going on with this?

**Comment by weshi** [comment]
@hjkim71 could you take a look as this is for Mac only?

**Comment by rkw6086** [comment]
Any help on this is great. Thanks @weshi!

**Comment by rkw6086** [comment]
@hjkim71 Any updates on this?
