### ISSUE TITLE
Outlook: Onsend addins not invoked in multiple scenarios

### ISSUE THREAD

**Issue by Premsagar-lab** [OfficeDev/office-js#1247]
Following are cases where onsend addin is not invoked. 
a.	Responding a Meeting with Accept or Tentative or Decline option.
b.	Responding a Meeting through RSVP option in OWA
c.	Forwarding a Meeting through Calendar Pane
d.	Content of Word document is selected and shared as HTML document through Mail. (Option to share in MSWord – File -> Share-> Send as HTML)
e.     OWA meeting invite does not get monitored when created inline in calendar pane.

## Expected Behavior

Onsend addin must be invoked in all the above cases when any mail or meeting is sent.

## Current Behavior

Mail is sent without onsend activation. 

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]:  __Mac__
* Host [Excel, Word, PowerPoint, etc.]: __Outlook__
* Office version number: __16.33__
* Operating System: __macOS 10.14.6__
* Browser (if using Office Online): __Chrome and Safari__

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lindalu-MSFT** [comment]
Hi @Premsagar-lab In order for us to triage this issue, we need more repro steps and additional details. Do you have any of the useful log files?

**Comment by exextoc** [comment]
Hey @Premsagar-lab ,

Scenarios (a) and (b) are known scenarios that we do not support OnSend add-in execution on currently.
Scenario (c) is something we might have to reconsider, thank you for reporting this issue. Scenario (d) is a little unclear to me, which Word client (Desktop/Mac/web) are you using and which app are you using to send the final email? OnSend add-ins are not supposed to run outside of the context of Outlook.

Can you tell us what your use case is so that we can understand your situation better?

**Comment by Premsagar-lab** [comment]
## Scenario D:
Onsend addin is not invoked when HTML content is shared by MS Word application on mac through Micorsoft Outlook for mac.

### Setup Details:
Machine - MacOs 10.14
Application - Microsoft Word for mac
Email Application - Microsoft Outlook for mac
  

Here Outlook Addin is not available to execute. 

### Steps to Reproduce:
1. Open macOS Mail Preference - General - Select Default Email Reader as 'Microsoft Outlook' 
2. In the Accounts Tab - configure the O365 email account
3. Open the MS Word application on mac and Create the Word file with some text contents
Goto Menu File - Share - Send HTML
![Screen Shot 2020-06-30 at 4 43 56 PM](https://user-images.githubusercontent.com/67500503/86207786-e204c380-bb8c-11ea-9045-bf67b39057ca.png)

It will create new MS Outlook mail with contents of Word file above in HTML format
4. Click on Send button
![Screen Shot 2020-06-30 at 4 45 16 PM](https://user-images.githubusercontent.com/67500503/86207817-f052df80-bb8c-11ea-9865-c7693076d7bf.png)

### Current behaviour :
Onsend addin is not loaded in compose window when user sends email.

### Expected Result :
Onsend addin should be available and invoked when user sends email.

## Scenario E) OWA meeting invite does not get monitored when created inline in calendar pane.
This is new issue we observed so adding it to this issue.

### Steps to reproduce:
1.       Open the OWA in Safari
2.       Go to Calendar Pane
3.       Select any future date
4.       just single click on it
5.       it will open the compose meeting pane with limited options at attachment.
<img width="1540" alt="Inline_Event_invite" src="https://user-images.githubusercontent.com/67500503/86208380-12009680-bb8e-11ea-9bc2-5ccf4588de9a.png">

6.       Click on Send button 

### Expected behaviour:
Onsend addin should be activated

### Current behaviour:
Onsend addin is not invoked.

**Comment by exextoc** [comment]
Hey @Premsagar-lab ,

Sorry for the late response. I can see this issue happen as you have mentioned across OWA and Mac. Thank you for reporting the issue, we have moved it to our backlog and we will fix it. However, we have no timelines to share at this point.

**Comment by exextoc** [comment]
Hey @Premsagar-lab ,

Can you confirm that the OnSend policy is enabled for the account in which you're seeing behaviour (e)?
You can read about the OnSend policy here: [Install Outlook add-ins that use On-Send](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=classic#install-outlook-add-ins-that-use-on-send)

If this policy is enabled, it shouldn't display the inline compose for Calendar at all.

**Comment by Premsagar-lab** [comment]
> Hey @Premsagar-lab ,
> 
> Can you confirm that the OnSend policy is enabled for the account in which you're seeing behaviour (e)?
> You can read about the OnSend policy here: [Install Outlook add-ins that use On-Send](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=classic#install-outlook-add-ins-that-use-on-send)
> 
> If this policy is enabled, it shouldn't display the inline compose for Calendar at all.

Yes, onsend policy is enabled for the account in which we are seeing this behaviour.

**Comment by exextoc** [comment]
> Yes, onsend policy is enabled for the account in which we are seeing this behaviour.

This is strange. Can you confirm that when the OnSend add-in does work (in a normal mail/ calendar compose scenario) do you see all other email/calendar edit fields being disabled while the add-in is running?

**Comment by Premsagar-lab** [comment]
> > Yes, onsend policy is enabled for the account in which we are seeing this behaviour.
> 
> This is strange. Can you confirm that when the OnSend add-in does work (in a normal mail/ calendar compose scenario) do you see all other email/calendar edit fields being disabled while the add-in is running?

No. Fields are not disabled while the addin is running. We can edit the fields till the addin is in progress.

**Comment by exextoc** [comment]
Hey,


 

There's a chance that the OnSend policy isn't enabled if you're seeing this behaviour. Could you please confirm that the policy is enabled?

For this you need to run the command-let: 

```powershell
Get-CASMailbox <admin-account-email>| fl
```

(You will need Exchange admin account credentials for this)

Look out for the field:

```
OwaMailboxPolicy : OWAOnSendAddinAllUserPolicy
```
If that field doesn't exist, the policy is probably not enabled. You can read about the Get-CASMailbox command-let here: [Get-CASMailbox Commandlet](https://docs.microsoft.com/en-us/powershell/module/exchange/get-casmailbox?view=exchange-ps)

**Comment by Premsagar-lab** [comment]
Hey exextoc,

Thanks for reply, We will check with this cmdlet. For the same user mailbox it's working when a message is drafted, replied or forwarded from inbox folder. The issue is only observed for meetings. Is there any different onsend policy for meetings?

**Comment by exextoc** [comment]
Hi @Premsagar-lab , we currently do not support the scenarios you've mentioned (a, b, c and d) and are evaluating the changes required to handle these scenarios. We will continue to investigate and work on them, Thank you for reporting the issue. Unfortunately, we do not have timelines to share at this point. 

To answer your other question no, there shouldn't be a different policy for meetings.

**Comment by exextoc** [comment]
Internal tracking id: O365:1558017

**Comment by Premsagar-lab** [comment]
Hi @exextoc, Any update on these issue?

**Comment by exextoc** [comment]
@Premsagar-lab This has been added to our backlog. Unfortunately, we do not have timelines to share at this point for fix to be available.
