### ISSUE TITLE
Outlook: Office.context.mailbox.item.body.getAsync() does not provide email body correctly in text format. In html format it returns differently on OWA and Client.

### ISSUE THREAD

**Issue by Premsagar-lab** [OfficeDev/office-js#1248]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Body is retrieved using or written office JS Api 
Office.context.mailbox.item.body.getAsync(coercionType, options, callback)
Coercion type can be either text or html. 
When User edits email in HTML format but body is retrieved as text. The retrieved body does not have proper whitespacing  (newline)between texts. If the body is retrieved in html format then also the output of the API is different in OWA and Outlook application for mac

## Expected Behavior

The text should be received as the user has typed in mail box compose window.

## Steps to Reproduce, or Live Example

Suppose the user has typed following message in compose window:
This is message
Sensitive Keyword
This is message

**Case A) CoercionType = text**
If the body is retrieved in "text" format the expected body should be:
__This is message\nSensitive Keyword\nThis is message__

But body received through office API:
__This is messageSensitive KeywordThis is message__

**Case B) CoercionType = html**
We receive different html text in OWA and in Outlook client for mac.

Text returned on OWA:
\<div style=\"font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);\"\>This is message.\</div\>
\<div style=\"font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);\"\> Sensitive Keyword \</div\>
\<div style=\"font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);\"\>
\<span style=\"caret-color: rgb(0, 0, 0); font-family: Calibri, Arial, Helvetica, sans-serif; background-color: rgb(255, 255, 255); display: inline !important\"\>This is message.\</span\>\<br\>\</div\>"

Text returned on Outlook Client:
\<div style=\"font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);\">This is message.\</div\>\r\n
\<div style=\"font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);\"> Sensitive Keyword \</div>\r\n
\<div style=\"font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);\">\r\n
\<span style=\"caret-color: rgb(0, 0, 0); font-family: Calibri, Arial, Helvetica, sans-serif; background-color: rgb(255, 255, 255); display: inline !important\"\>This is message\</span\>\<br\>\</div\>"
 
So we get whitespaces on client but we dont get on OWA.

## Context

Due to this we are not able to understand content of the message properly.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: __Mac and Online__
* Host [Excel, Word, PowerPoint, etc.]: __Outlook__
* Office version number: __16.33__
* Operating System: __10.14.6__
* Browser (if using Office Online): __Safari__

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
Hey @Premsagar-lab ,

Sorry for the late response. Thank you for reporting the issue. We can see the issue across OWA and Mac as you have described. We have put this in our backlog and are going to fix it. Unfortunately, we have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: OutlookWeb:89150

**Comment by andmaz** [comment]
@exextoc, it there any possibility to get this issue fixed soon?

**Comment by fergy-hs** [comment]
Any updates on this? This is becoming a big issue for my company.

**Comment by unicornflax** [comment]
This issue is not fixed. It’s very annoying. Can it be this hard to get the raw text with proper line breaks?

**Comment by Premsagar-lab** [comment]
@exextoc is it fixed in the recent versions?
