### ISSUE TITLE
Outlook: Onsend addin is not invoked for mails sent with Do not forward option

### ISSUE THREAD

**Issue by Premsagar-lab** [OfficeDev/office-js#1251]
## Expected Behavior

Onsend Addin should be invoked for Do not forward mails

## Steps to Reproduce, or Live Example

1. Configure certificates for encryption.
2. Open a new mail window and draft a mail.
3. Go to Draft->Encrypt and select Do Not Forward option.

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ___Mac___
* Host [Excel, Word, PowerPoint, etc.]: __Outlook____
* Office version number: _16.33_____
* Operating System: _10.14.6_____
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
This is currently intended behavior. No add-ins run (onsend / taskpane / executefunction etc.) when DRM is enabled on an email for security reasons.

**Comment by lindalu-MSFT** [comment]
Because this is **resolution: by design**, closing this issue.
