### ISSUE TITLE
Outlook: Office JS API to retrieve mail body does not return entire email thread when mail is replied in OWA

### ISSUE THREAD

**Issue by Premsagar-lab** [OfficeDev/office-js#1252]
OWA has option to reply or reply to messages in email reading window. 
When we reply or reply all using this option, the mail thread is not loaded in compose window till ellipsis option is selected by user. 
If the user edits the email and new content is added with ellipsis not selected then getAsync api for body only returns new content. Previous email body are not returned. 

## Expected Behavior

API should return entire email thread which will be sent irrespective of ellipsis is selected or not.

## Current Behavior
Only recent content of mail body is returned through Outlook Office JS API of getting body.

## Steps to Reproduce, or Live Example
1. Open mailbox in OWA and draft a new email. Sent the Email. (This step is optional and can move to step 2 if already mails available in inbox).
<img width="1455" alt="NewEmail" src="https://user-images.githubusercontent.com/67500503/86448824-f08ddf00-bd34-11ea-9a1d-1ceeed44b540.png">

2. Reply to the email received. Do not select ellipsis. This will not load entire email body in compose window.
<img width="1450" alt="ReplyEmailWithoutLoadingEmailThread" src="https://user-images.githubusercontent.com/67500503/86449017-2fbc3000-bd35-11ea-84b3-1c0ad6bb7b79.png">

3. Send email. Email is sent with entire email thread.
<img width="956" alt="EmailSent" src="https://user-images.githubusercontent.com/67500503/86450705-92163000-bd37-11ea-8cc0-82018a1483b0.png">

## Context

We are not able to check content of entire email being sent.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: __Online____
* Host [Excel, Word, PowerPoint, etc.]: ___Outlook___
* Browser (if using Office Online): _Safari_____

**Comment by Premsagar-lab** [comment]
I have edited the issue to provide screenshots within it.

**Comment by exextoc** [comment]
We are able to reproduce this issue on OWA. Thank you for reporting this issue. It has been put into our backlog and is under investigation. Unfortunately, we don't have timelines to share at this point.
