### ISSUE TITLE
Outlook OWA pinned task pane does not navigate to correct url based on mode

### ISSUE THREAD

**Issue by d-franklin** [OfficeDev/office-js#1253]
When replying to an email in OWA, the pinned task pane loads the "edit mode" url, but when clicking the discard button the url does not change back to the "read mode" url. This only occurs when replying to an email, if creating a new email, it functions as expected.

## Expected Behavior
The url should change to reflect what action the user is currently taking, edit or read, as it does on the desktop version.

## Current Behavior
![page-reload-example](https://user-images.githubusercontent.com/12947514/86107037-2c475100-ba76-11ea-855b-edec0afa05cc.gif)

## Steps to Reproduce, or Live Example
1. Create empty project with a different url for MessageReadCommandSurface and MessageComposeCommandSurface in the manifest.
2. Load OWA and pin the task pane (for both modes).
3. Select email to read, click reply, then click discard.

## Context
I need the url to reflect the current mode since the add-in will allow different actions for users depending on whether the mode is read or compose.

For example; the ability to insert attachments if the user is in compose mode vs extracting any attachments in read mode.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft 365 E5 Developer
* Operating System: Windows 10
* Browser (if using Office Online): Chromium based

**Comment by exextoc** [comment]
Hey @d-franklin ,

The add-in ideally should only be pinned for one mode, and from switching away from Compose, the add-in should close. That being said, I understand the issue here since the add-in is not being refreshed on closing the reply mode. We have added this to our backlog and we will fix it, however we have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: OutlookWeb:89151

**Comment by exextoc** [comment]
@d-franklin We are not able to repro this issue any more. Can you please check at your end and confirm?

**Comment by d-franklin** [comment]
> @d-franklin We are not able to repro this issue any more. Can you please check at your end and confirm?

Confirmed working as expected.
