### ISSUE TITLE
Excel Custom Functions: API Calls Timing Out After 60 Seconds [DUPLICATE]

### ISSUE THREAD

**Issue by pbl2108** [OfficeDev/office-js#1254]
Hi office-js Team and Contributors,

I apologize in advance for creating a duplicate bug report that already described here https://github.com/OfficeDev/office-js/issues/1184.

It is a show stopper for our Excel custom function production application. We have reported this issue twice, the first time on Jan 13, 2020 (https://github.com/OfficeDev/office-js/issues/934 and https://github.com/OfficeDev/office-js/issues/1184) and none of the workaround suggested work for us. Could you please increase the priority of this bug and provide a solution to us?

The issue is, the excel custom functions created as part of Add-In seem to have 60 seconds request limit on API call. When API call takes more than 60 seconds, it return "Network Request Failed" error. We are experiencing this 60 seconds request time limit in our current production Excel Add-In. Please refer to the full thread for description of the issue https://github.com/OfficeDev/office-js/issues/1184.

Thanks,
Petre

**Comment by lindalu-MSFT** [comment]
Hi all @keyur32 @sumurthy @lumine2008 @tutieu Can we escalate this? The customer has already opened two issues previously, none of the suggested workarounds work and he is blocked. Thanks in advance.

**Comment by pbl2108** [comment]
@lindalu-MSFT thanks for escalating this. Please keep us posted on any updates.

**Comment by dho-caissa** [comment]
@lindalu-MSFT is there any update to the issue? Any recommendation? thanks again

**Comment by pbl2108** [comment]
Hi @lindalu-MSFT could you please provide an update on this? We have reported this issue in January 2020 and we have not received any kind of explanation as to what's the cause of the 60 second timeout limit on the HTTP requests made by Excel custom functions. We have clients facing issues with this. Any solution to avoid this will be much appreciated.
Thanks,
Petre

**Comment by lindalu-MSFT** [comment]
Hi, the assignees can provide the update. I'm just the triage person!

**Comment by pbl2108** [comment]
Thanks @lindalu-MSFT . Can someone else please provide an update or explanation on the cause for this issue?

**Comment by pbl2108** [comment]
Hi @RuoyingLiang and @shaofengzhu, are there any updates on this? Thanks, Petre

**Comment by zlatko-michailov** [comment]
I responded in issue #1184. Let's continue there.

**Comment by keyur32** [comment]
Cleaning up, as this was a duplicate.
