### ISSUE TITLE
Outlook onsend addin is not invoked on Meeting cancellation

### ISSUE THREAD

**Issue by Premsagar-lab** [OfficeDev/office-js#1256]
Onsend addin not invoked while sending meeting cancellation.

## Expected Behavior

Onsend addin should be invoked on meeting cancellation.

## Current Behavior

Onsend addin is not invoked on meeting cancellation.

## Steps to Reproduce, or Live Example
1. Set and send a meeting invite to some outlook member.
![CreateMeeting](https://user-images.githubusercontent.com/67500503/86451991-46fd1c80-bd39-11ea-81a6-fb6ad8188597.png)

2. Now open the same meeting from calendar and add some text or attach some file to it and select "Cancel"
Don't see the addin being invoked and the meeting cancellation is sent.
![CancelMeeting](https://user-images.githubusercontent.com/67500503/86452010-4e242a80-bd39-11ea-84a8-58a5afb726eb.png)

## Context
We don't get the email data for verification.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: _Mac, Online_____
* Host [Excel, Word, PowerPoint, etc.]: __Outlook____
* Office version number: __16.33____
* Browser (if using Office Online): __Safari____

**Comment by exextoc** [comment]
Hi @Premsagar-lab , we currently do not support the scenario you've mentioned (meeting cancallation) for OnSend add-ins. We are evaluating the changes required to handle this scenario, along with the other GitHub issue you've created (#1247 ). We will continue to investigate and work on them. Unfortunately, we do not have timelines to share at this point.
