### ISSUE TITLE
Error message on Outlook Client does not give exact information about network issue when Onsend AddIn JS is not accessible

### ISSUE THREAD

**Issue by Premsagar-lab** [OfficeDev/office-js#1257]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

There are scenarios in which Onsend Addin JS may not be accessible to Outlook Client while sending emails.
In that case, Outlook for mac gives generic message that there is problem with Onsend addin. But the OWA gives more meaningful messages in such cases.

## Expected Behavior

Message should point towards cause like network issue or addin JS itself is not proper.

## Current Behavior
Different messages are shown in Outlook for mac and on OWA for same issue.
In case of OWA , in Javascript Console we get more exact message as 'We are sorry, we couldn't access Broadcom Symantec Addin , Make sure you have network Connection. If the Problem continues , Please try again later'

## Steps to Reproduce, or Live Example
1.  Setup a Proxy Server on the machine where Outlook for mac is installed. 
2.  Make sure that all Internet traffic is through Proxy
3.  On Proxy server server add the static website in blacklisting sites ie. block the public website
4.  Open Outlook Client and send sensitive mail from it
5.  Here we get the message on Outlook client saying 'Outlook Can't send this message because there is problem with the Broadcom Symantec Addin' 
6.  Here actual problem is that the static website is not accessible and hence network connection problem.
![OutlookClient_Message](https://user-images.githubusercontent.com/67500503/86456075-2afc7980-bd3f-11ea-942f-6c3f1379fb86.png)

7.  Try the similar steps on OWA  and check the message shown to user.
![OWA_JavascriptConsole_Message](https://user-images.githubusercontent.com/67500503/86455864-dc4edf80-bd3e-11ea-8ed4-4ef5444ddea1.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: _Mac, Online_____
* Host [Excel, Word, PowerPoint, etc.]: _Outlook_____
* Browser (if using Office Online): __Safari____

**Comment by exextoc** [comment]
Thank you for reporting this issue. We have put this issue in our backlog. However, we have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: Office:4270004
