### ISSUE TITLE
Outlook Onsend addin is not invoked if the email is updated in Outbox.

### ISSUE THREAD

**Issue by Premsagar-lab** [OfficeDev/office-js#1258]
Suppose mail is stuck in outbox due to any network issue then User can edit the email and resent it to Outbox till the mail is actually sent. For these edits from Outbox folder, Onsend addin is not invoked.

### Expected Behavior
Onsend addin shall be invoked when mail is edited or drafted from any folder including Outbox.

### Current Behavior
Onsend addin is not invoked when email is edited.

## Steps to Reproduce, or Live Example
1. Proxy is configured on the Machine so that all Internet traffic goes via Proxy server
2. Stop the Proxy service on that server
3. Draft a email and send it. Onsend addin is activated. Mail is sent but it stucks in Outbox due to network.
4. Open the mail from outbox 
5. Add sensitive content in it and Save. Onsend addin is not invoked.
6. Start the Proxy service so that network connection is restored. Mail is sent from Outbox with edited contents.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: __Mac____
* Host [Excel, Word, PowerPoint, etc.]: _Outlook_____
* Office version number: __16.33____

**Comment by exextoc** [comment]
Thank you for reporting this issue. We do not support this OnSend scenario at the moment. We are evaluating all the OnSend scenarios you've mentioned, along with issues #1247 and #1256 . We unfortunately don't have any timelines to share at this point.
