### ISSUE TITLE
Excel: Configuring the manifest to use shared runtime breaks custom functions with #N/A error on both Windows and Mac desktops

### ISSUE THREAD

**Issue by cghaddar** [OfficeDev/office-js#1259]
I followed the instruction given here
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime
This broke the CONTOSO  custom functions tutorial. After the change =CONTOSO.ADD(1,1)  return #N/A error with the message 'A value is not available to the formula or function.'
The CONTOSO tutorial was working just fine prior to switching to shared runtime

Update* I also tried the exact steps on a Mac pro  with Catalina os and latest Office 365  and getting same #N/A errors after switching to shared runtime.

## Expected Behavior

Custom functions should continue to work with shared runtime as promised.

## Current Behavior

I get #N/A error and the following error in the log
7/3/2020 16:26:09	Verbose	CustomFunctions	[Execution] [Async] [Begin] Function=CONTOSO.ADD, Workbook=Excel add-in fe56a26b-fb5a-4969-ac60-5b6477c845c0.xlsx		
7/3/2020 16:26:10	Unexpected	CustomFunctions	[Execution] [Async] [End] [Failure] Function=ADD, Workbook=Excel add-in fe56a26b-fb5a-4969-ac60-5b6477c845c0.xlsx		

## Steps to Reproduce, or Live Example

* Link to live example: ______
simply follow the steps given at
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime
on Windows desktop
The attached zip file includes test files
[CustomFUnctionsTest.zip](https://github.com/OfficeDev/office-js/files/4874963/CustomFUnctionsTest.zip)

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

Blocking

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]:  both PC desktop and Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number:  2006 build 13001.20266  (365)
* Operating System: Microsoft Windows 10 Enterprise; (Catalina on Mac)
[OfficeAddins.log.txt](https://github.com/OfficeDev/office-js/files/4871619/OfficeAddins.log.txt)

* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by weshi** [comment]
Have you added your function.js to your taskpane.html?

**Comment by cghaddar** [comment]
This is not specified in MS docs but I tried adding functions.js to my taskpane.html as you suggested
<script type="text/javascript" src="../functions/functions.js"></script>
Rebuild and tested but it made no difference. Same #N/A error.

**Comment by bmgomg** [comment]
I made it work by tweaking the manifest and replacing this:

<bt:Url id="ContosoAddin.Url" DefaultValue="https://localhost:3000/dist/taskpane.html"/>

with this:

<bt:Url id="ContosoAddin.Url" DefaultValue="https://localhost:3000/dist/functions.html"/>

**Comment by cghaddar** [comment]
The tweak you made does indeed eliminate the #N/A error, however the custom functions do not seem to be running in a shared runtime environment after the tweak.  If I attempt to call Excel APIs from any custom function it will throw "Excel is undefined". For example, if you try the example described here
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function

/**
 * @customfunction
 * @param address range's address
 **/
async function getRangeValue (address) {
 var context = new Excel.RequestContext();
 var range = context.workbook.worksheets.getActiveWorksheet().getRange(address);
 range.load();
 await context.sync();
 return range.values[0][0];
}

It does not work and will throw  "Excel is undefined".  This indicates the custom functions are still running in the custom functions runtime  where Excel is undefined.  
If you know of a way to make this work please advise as this is blocking. Thanks much!

**Comment by bmgomg** [comment]
The tweak (a hack, really) only allowed me to work around the "#N/A" problem. I can call my custom functions now and use full CORS, which was my only goal. I don't pretend that I found a real solution, and I'm not trying to use any Excel APIs, sorry.

**Comment by uangyydev** [comment]
Mybe you can add the following code in the \<head\> section in taskpane.html file to add your function.js to your taskpane.html, and rebuild the project.
```
<script src="functions.js"></script>
```
instead of
```
<script type="text/javascript" src="../functions/functions.js"></script>
```

It works to me.

> This is not specified in MS docs but I tried adding functions.js to my taskpane.html as you suggested
> 
> <script type="text/javascript" src="../functions/functions.js"></script>
> Rebuild and tested but it made no difference. Same #N/A error.

**Comment by cghaddar** [comment]
I undid elterman tweak and added <script src="functions.js"></script> to the taskpane.html. This  made it work finally!.  Thank you much uangyydev for pointing this out. This modification is required but has been left out in the MS docs article. 
I will leave this issue open for someone at MS to take notice and update the docs.

**Comment by cghaddar** [comment]
The documentation has been updated.
