### ISSUE TITLE
Recipe for circumventing sandbox error on localhost

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js#126]
`Error while parsing the 'sandbox' attribute: 'ms-allow-popups' is an invalid sandbox flag.`

I'm seeing that error each time I try to debug an add-in locally on latest Chrome. It prevents me from seeing the authentication dialogue see examples at https://github.com/OfficeDev/office-js-helpers#authentication-1

Already googled but found no answers. Any clues very welcome.

**Comment by mlafleur** [comment]
This is just a warning that Chrome doesn't support/know what to do with `ms-allow-popups`. It can safely be ignored (which for the record is what Chrome does as well, it simply ignores that flag).

**Comment by binarykitchen** [comment]
Mmmhhhh ... and are you adding vendor tags for that as well for Chrome? So that it won't complain?

The thing is that I do not see an authentication popup at all here and makes me believe there is a problem.

**Comment by mlafleur** [comment]
This isn't a problem. All browsers ignore attributes that it doesn't recognize. Chrome is just particularly aggressive about surfacing warnings.  

This is why you'll often see CSS that looks like this:

```
-moz-animation: spin 2s infinite linear;
-o-animation: spin 2s infinite linear;
-webkit-animation: spin 2s infinite linear;
animation: spin 2s infinite linear;
```

**Comment by binarykitchen** [comment]
Alright, false alarm then. Thx
