### ISSUE TITLE
Outlook Office 365 for web creates additional add-ins instances and loads them together (Chrome, Safari)

### ISSUE THREAD

**Issue by max-yushchuk** [OfficeDev/office-js#1261]
## Expected Behavior
It shouldn't load all add-ins, opened before. It has worked normally previously.

## Current Behavior
Open and close add-in on different email items.
When a user opens new item he/she will see that all items, opened previously are loaded as well.

## Steps to Reproduce, or Live Example
1. Create add-in from scratch.
2. Add, for example, console.log('INIT') in Office.onReady callback.
3. Sideload add-in.
4. Open and close add-in on several email items. For example 5 items.
5. Open any item again and see console output: 6 or more "INIT" words were shown. (expected 1 "INIT")

Example video in attachment
[Screen Recording 2020-07-06 at 14.57.53.zip](https://github.com/OfficeDev/office-js/files/4878721/Screen.Recording.2020-07-06.at.14.57.53.zip)

## Context
It's critical issue. And it doesn't allow us to use Outlook Add-in.

## Your Environment

* Platform: Mac, PC desktop
* Host: Outlook
* Office version number: Office 365 for web
* Operating System: Mac OS, Windows 10
* Browser (if using Office Online): Chrome, Safari

## Useful logs
Taskpane.js code:
```
/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
 * See LICENSE in the project root for license information.
 */

/* global document, Office */

Office.onReady(info => {
  console.log("INIT");
  if (info.host === Office.HostType.Outlook) {
    document.getElementById("sideload-msg").style.display = "none";
    document.getElementById("app-body").style.display = "flex";
    document.getElementById("run").onclick = run;
  }
  Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, e => {
    console.log("Item Changed", e);
  });
});

export async function run() {
  /**
   * Insert your Outlook code here
   */
}
```

**Comment by exextoc** [comment]
Hi, we are unable to reproduce this issue on OWA. From your video, is it possible there are no redundant initialize calls, but all the "INIT" messages are being printed together after you open the console? Could you record a video by keeping the console open, and doing the same actions as your original video?

**Comment by max-yushchuk** [comment]
Hi, no it's not possible. I've cleaned the console after opening. You can see it on video. This issue existed till yesterday and suddenly disappeared. I suppose, it was something on Microsoft side. It didn't work only for two days.
So I'll close this issue. It doesn't exist now.
