### ISSUE TITLE
Outlook Addin Javascript timeouts in 60 second instead of 5 min.

### ISSUE THREAD

**Issue by Premsagar-lab** [OfficeDev/office-js#1262]
Addin Javascript helps to retrieve the contents of attachment which can be as large as around 30 mb. We have to upload this data to our server where we process contents of attachments. This http Post request in addin Javascript  sometimes take more then 60 seconds to complete. But this request is timedout on Outlook Client. 
The same request works properly in OWA in safari and Chrome.

https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1408259-timeoutintervalforrequest

The reason for this Outlook Client uses webkit to load addin html page which has default timeout configuration of 60 seconds.
On OWA safari handles it properly

## Expected Behavior

The request should not timeout in 60 seconds. It can timeout with addin if required.

## Current Behavior

Request timed out in 60 seconds.

## Steps to Reproduce, or Live Example
1. Create a outlook addin which does http post request to a webservice.
2. Send email which invokes addin.
3. Webservice should take more then 60 seconds for its processing which is possible on slow networks.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: __Mac____
* Host [Excel, Word, PowerPoint, etc.]: __Outlook____
* Office version number: _16.33_____
* Browser (if using Office Online): __Safari____

**Comment by exextoc** [comment]
Hi, thanks for reporting this issue. We are able to reproduce this on Outlook Mac. We have added it to our backlog, but unfortunately do not have timelines to share at this point.

As a temporary workaround, we suggest breaking the POST request into smaller ones so they don't timeout.

**Comment by codexeon** [comment]
You can set timeout on XMLHttpRequest to increase the limit beyond 1 minute. 
var xhr = new XMLHttpRequest();
xhr.open('POST', "https://localhost:3000/testpost", true);
xhr.timeout = 80000; // time in milliseconds
xhr.onload = function () {
console.log(this.response);
};
xhr.ontimeout = function (e) {
  console.error("timeout");
};
xhr.send(null);
