### ISSUE TITLE
Outlook: Desktop "a problem occurred while trying to reach this addin" on network error in dialog

### ISSUE THREAD

**Issue by cbishop-fv** [OfficeDev/office-js#1268]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior

The dialog should remain open and render the page in the same way the web app does.

## Current Behavior

When using a dialog modal to auth with AWS cognito and amplify.js, the user enters an incorrect username password combo AWS responds with a 401 network error. 

The desktop version detects a 401 network error for fail user login attempts and closes.
![Capture](https://user-images.githubusercontent.com/56599161/86830599-1d9f0200-c053-11ea-8c81-e11197b2c96e.PNG)

The web app stays open and renders the page as expected
![image](https://user-images.githubusercontent.com/56599161/114428280-38218100-9b79-11eb-8cea-07df395a7065.png)

## Steps to Reproduce, or Live Example

Unable to find live examples.

Using https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins this auth flow with async dialog
Using AWS Cognito hosted login and amplify.js
Open dialog show user login
Failed login returns 401 network error
App crashes

## Additional details
We have seen other cases where the app detects a network error on desktop and has the same behavior unrelated to AWS / cognito.

## Context
How has this issue affected you? App is crashing on users 
What are you trying to accomplish? Give users feedback they entered incorrect un/password combo

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Windows Desktop 16.0.12827.20328
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.12827.20328
* Operating System: Windows 10 Pro
* Browser (if using Office Online): n/a - works on chrome as expected

## Useful logs

- [x] Screenshots

**Comment by exextoc** [comment]
@cbishop-fv when the user enters an incorrect username/password, does the page attempt to navigate, resulting in the 401 error?

**Comment by cbishop-fv** [comment]
> @cbishop-fv when the user enters an incorrect username/password, does the page attempt to navigate, resulting in the 401 error?

Correct, The login form posts to itself and in the case of bad UN/PW combo returns a 401 unauthorized. The AWS cognito hosted login page sees this and normally just presents an error message to the user as seen in the 2nd image above. This works fine for outlook addins on the web but not the desktop outlook client.

**Comment by exextoc** [comment]
In the desktop client, if the initial page of the add-in returns a 401 response, the 401 is handled and the add-in error is displayed in the displayDialog. 

I noticed in the repro steps that you mention that the app crashes. Does the entire add-in show an error or just the displayDialog?

**Comment by cbishop-fv** [comment]
Hi, for clarification the app opens a dialog for auth. When the 401 happens the taskpane sidebar app is unchanged, still displays our page / app where it was when the auth dialog modal opens. When the 401 occurs the dialog modal is what shows the yellow "ADD-In ERROR" message seen in the OP. So to answer just the displayDialog shows the error.

**Comment by exextoc** [comment]
The add-in error you are seeing is by design. The win32 client handles 401 responses and will display this error in the displayDialog (the taskpane will remain unchanged). 

A possible workaround is to set the sourceLocation to a page that does not require authentication, and then perform the login from that page. This way if there is a 401 response, the navigation will occur to a page that does not require authentication.

**Comment by cbishop-fv** [comment]
🤔 hmmm I am not sure I follow. I am not sure what " then perform the login from that page " would look like, especially using a AWS cognito hosted login. We already start the user on a sourcelocation that is a local unauthenticated page since we can't start them on AWS cognito. From there we redirect them to a cognito hosted login and thats where the 401 can occur. I think to handle the way you have suggested we would have to have a 2nd popup from the dialog modal or something? That doesn't seem like a good user experience. The dialog is already more than desired. 

Why is the behavior handled differently on the web client? Web works as expected.

**Comment by rajesh2011** [comment]
We are seeing similar behavior. Desktop add-in shows error while authenticating but in OWA browser there is no such error.
Is the fix being worked on? Any ETA?

**Comment by Zamolxe00** [comment]
@exextoc Would this still happen with the new Chromium webview?

**Comment by cbishop-fv** [comment]
This is still a problem for us. Any update? 401 Unauthorized is a valid response from an auth request. This is from amazon AWS cognito hosted login. The outlook web client handles this request as expected.

**Comment by cbishop-fv** [comment]
On further digging on web I am seeing Cognito does a 302 POST and then a 401 GET for 1 auth request. Maybe the extra hop is causing outlook desktop to crash? 

![image](https://user-images.githubusercontent.com/56599161/114428118-0a3c3c80-9b79-11eb-9996-09012faf4fdf.png)

**Comment by zunquan** [comment]
@cbishop-fv, can we get your addin to reproduce your issue?

**Comment by cbishop-fv** [comment]
> @cbishop-fv, can we get your addin to reproduce your issue?

We are using a custom auth flow for this now to avoid this error. We would be unable to reproduce this in our app at this time. 

We were using the add in documented flow of using the dialog to open a window and the basic aws hosted Cognito.

**Comment by hdwatts** [comment]
@croicu @zunquan Any update on this? Our clients are experiencing it while authenticating with Okta. The 401 status is being returned and it is then followed up with a successful connection (screenshot from a successful login via Chromium Edge).

![image](https://user-images.githubusercontent.com/16158417/144080957-9e67080f-428e-45b7-92ee-6cbf040215ca.png)

**Comment by hdwatts** [comment]
@exextoc Would like to get your attention to the above

**Comment by hdwatts** [comment]
@exextoc We are experiencing a 404 in a client's Okta SSO request chain which is triggering this issue. Is there a way we can access the problematic URL when a 12002 event error occurs so we can gain any insights into where things are going wrong?

**Comment by cbishop-fv** [comment]
> @exextoc We are experiencing a 404 in a client's Okta SSO request chain which is triggering this issue. Is there a way we can access the problematic URL when a 12002 event error occurs so we can gain any insights into where things are going wrong?

We had to debug these issues in Chrome OWA since it doesn't crash in the same way desktop does and then you are able to look at the network request and console.

**Comment by jtrueblood-anaqua** [comment]
We are running into this issue as well using a SAML provider for SSO. The flow for SAML first returns a 401 for unauthorized users. The Office JS Dialog window does not like this.

![image](https://user-images.githubusercontent.com/36737370/153302456-22f281ff-eff0-4fc0-be2b-46fb90945d2b.png)

**Comment by jtrueblood-anaqua** [comment]
Any update on this? This seems to be a pretty standard authentication flow:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate

**Comment by rvab** [comment]
> jtrueblood-anaqua

Did you find any workaround for this? I'm too facing the same issue with SAML SSO.

**Comment by rvab** [comment]
@jtrueblood-anaqua 

Did you find any workaround for this? I'm too facing the same issue with SAML SSO.

**Comment by cbishop-fv** [comment]
> @jtrueblood-anaqua
> 
> Did you find any workaround for this? I'm too facing the same issue with SAML SSO.

We had to build our own auth page using the cognito UI libs and hook to work around it. pain :(
