### ISSUE TITLE
How can I debug in native Outlook?

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js#127]
When writing JS code and installing the add-in X I can see it behaves differently among web and native interfaces.

On web interfaces I can debug in dev tools fine. But how can I debug i.E. add-in behaviour, the JS execution, on native Outlook?

If seems it doesn't run when I single click on the add-in icon but only when I double click on which which is kinda weird. Hence keen to debug this.

**Comment by exextoc** [comment]
For debugging add-in running in native Outlook, have you tried using Visual studio https://docs.microsoft.com/en-us/office/dev/add-ins/testing/attach-debugger-from-task-pane or Windows 10 F12 dev tools https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10 ? For the click behavior, we have not heard what you reported. If you are seeing single click vs double click difference for the add-in icon on the ribbon and that happens before any of the html / js executes, please tell us more or extract a simple manifest /add-in for us to repro.

**Comment by binarykitchen** [comment]
Well I am running on MacOS. Would that F12 dev tool work there too?

About the weird single + double click behavior, I can show you the code but it's written in ClojureScript. Would you understand it?

**Comment by mlafleur** [comment]
There is an article in the documentation that covers this: [Debug Office Add-ins on iPad and Mac](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac)

**Comment by binarykitchen** [comment]
thanks for the link!

**Comment by binarykitchen** [comment]
hmmm,  unfortunately nothing on that article works. there is no "inspect element" context menu entry in outlook for mac

**Comment by mlafleur** [comment]
You want to use Vorlon.JS, not the Safari web inspector.

**Comment by binarykitchen** [comment]
That was not clear on this article. And is Vorlon.JS able to debug sessions from native Outlook for Mac OS? Is there a YouTube video for that?

**Comment by JuaneloJuanelo** [comment]
@Rick-Kirkham  can we please document more details on how to debug? thanks!

**Comment by Rick-Kirkham** [comment]
@ElizabethSamuel-MSFT Can you answer binarykitchen's question and add it to the article mlafleur linked to as needed?

**Comment by rvanlaak** [comment]
> Currently the only supported debugger tool is Visual Studio 2015 with Update 3 or later. If you don't have Visual Studio installed, selecting the Attach Debugger option doesn’t result in any action.

https://docs.microsoft.com/en-us/office/dev/add-ins/testing/attach-debugger-from-task-pane

The standalone F12 tool executable is a nice start. As it allows to hook into the addin iexplorer process after Word opened it, and allows adding the debugger as described in above tutorial. This does not allow linking to sourcemaps though, so placing breakpoints is a struggle. An IDE could also do what F12 tools does?

Could more information be added on a possible remote debug TCP port that's exposed, and on how an external tool could hook into that iexplorer process? Preferably how it would work for Visual Studio Code and WebStorm.
