### ISSUE TITLE
In Contextual office addins in Outlook specific word not gets highlighted properly

### ISSUE THREAD

**Issue by avgode** [OfficeDev/office-js#1271]
This is not dupe of #1266. I have created this as #1265 closed saying dupe of #1266. But both are different issues.
**Here we saying word getting highlited wrongly**. And in **#1266 we saying word not getting highlighted on forwarded and replied emails on Outlook on Web**.
## Expected Behavior

When using contextual addins in Outlook, I wanted to highlight few words like ill, holiday, leave and wrote regex as **\b(\r\n|\r|\n)|(leave|holiday|vacation|sick|ill|sickness|poorly|absent|absence)|(\r\n|\r|\n)\b**

So if  the message contains below text...
**Hi I'm still on holiday.**

It should only highlight **Holiday**
## Current Behavior

When using contextual addins in Outlook, using regex as **\b(\r\n|\r|\n)|(leave|holiday|vacation|sick|ill|sickness|poorly|absent|absence)|(\r\n|\r|\n)\b** it highlights **ill** word in st**ill** and **holiday** in **holiday**ing which is not expected. I have tried various ways but result is same and I think regex written by me is straight forward and its working on online third-party regex tools.

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook, Outlook on Web
* Office version number: ______
* Operating System: Windows 10
* Browser (if using Office Online): Chrome, Chromium

## Useful logs

- [ ] Console errors
- [ ] Screenshots
![image](https://user-images.githubusercontent.com/15957229/86805404-c3606a00-c06f-11ea-8ada-0113aef204ab.png)

- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
Hi @avgode , we think your regex should be:

\b((\r\n|\r|\n)|(leave|holiday|vacation|sick|ill|sickness|poorly|absent|absence)|(\r\n|\r|\n))\b

With the added **()**. You can test your given regex with https://regex101.com/, for example, which highlights "ill" in "still", and "holiday" in "holidaying".

Please let us know if this fixed your issue.

**Comment by avgode** [comment]
> Hi @avgode , we think your regex should be:
> 
> \b((\r\n|\r|\n)|(leave|holiday|vacation|sick|ill|sickness|poorly|absent|absence)|(\r\n|\r|\n))\b
> 
> With the added **()**. You can test your given regex with https://regex101.com/, for example, which highlights "ill" in "still", and "holiday" in "holidaying".
> 
> Please let us know if this fixed your issue.
Hi @exextoc 
It not resolved my issue. It looks you misunderstood my issue. My issue is **ill** gets highlighted in **still** word, which I don't want. **I want ill should get highlighted on individual word like ill, ILL, Ill but not in Still , till**
Also my regex works fine in https://regex101.com/ but not working in Contextual addins.
I hope you got what my real issue is.

**Comment by exextoc** [comment]
Using your regex, the word **ill** _does_ get highlighted in the string: "holidaying instill". Can you try the same on http://regex101.com/?

Using the regex we've given, however, only highlights individual words "ill", "holiday", etc. Can you test this out?

**Comment by avgode** [comment]
> Using your regex, the word **ill** _does_ get highlighted in the string: "holidaying instill". Can you try the same on http://regex101.com/?
> 
> Using the regex we've given, however, only highlights individual words "ill", "holiday", etc. Can you test this out?

Hi @exextoc 
Thanks for the help.
In  http://regex101.com/ I have checked my regex and there **ill** gets highlighted in **still**. And after your regex it is not highlighting. So your regex does work on http://regex101.com/
But same regex given by you with extra **()** not working in Contextual Addins (both on web and on desktop outlook).

**Comment by avgode** [comment]
Even regex **\b(leave|holiday|vacation|sick|ill|sickness|poorly|absent|absence)\b** is working in http://regex101.com/ but not working on Outlook on web and on Outlook native app and also with that there is another issue that words not getting highlighted in new lines, so I have added **(\r\n|\r|\n)** at start and at end, which solved the new line issue.
So there is some different interpretation of regex in Contextual addins with Office API

**Comment by exextoc** [comment]
@avgode Yes, you're right. The \b doesn't seem to be respected by Outlook, on any platform (Web / Mac / Windows). Thank you for reporting this issue. We have added it to our backlog to fix, unfortunately we don't have any timelines to share at this point.
