### ISSUE TITLE
Excel: Unable to run OfficeJs under iframe. Uncaught Sys.ArgumentNullException: Sys.ArgumentNullException: Value cannot be null. Parameter name: conversationId

### ISSUE THREAD

**Issue by kullachoke-bosuwan-rft** [OfficeDev/office-js#1273]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
Taskpane app should be able to host another app that required OfficeJs Api within iframe.

## Current Behavior
If taskpane hosted another app that required OfficeJS script within iframe, we'll got an error (see an image attached below) from an app in iframe which blocked officejs from initialize

## Steps to Reproduce
  1. Open an taskpane app, run `Office.onReady`
  2. in html file, add <iframe src=...> that open another app that also have officejs script then run `Office.onReady`
  3. error `Uncaught Sys.ArgumentNullException: Sys.ArgumentNullException: Value cannot be null. Parameter name: conversationId`
 4. Officejs not working on another app inside iframe.

## Your Environment
* Platform: Office Online
* Host: Excel
* Office version number: All
* Operating System: All
* Browser (if using Office Online): All

## Useful logs

![Screen Shot 2563-07-10 at 14 46 07](https://user-images.githubusercontent.com/64405659/87130641-6e199800-c2bd-11ea-8708-7f7f94ce546c.png)

**Comment by lumine2008** [comment]
Hi @kullachoke-bosuwan-rft , would you please share some more information to us? may i know the reason that you need to run in iframe? thanks

**Comment by lumine2008** [comment]
@shaofengzhu , it seems this issue owned by your team. so let me assign to you

**Comment by SorinMiron** [comment]
Any news about this issue? I'm struggling rn with that
