### ISSUE TITLE
Excel: error shown in console after executed `Office.context.ui.messageParent`

### ISSUE THREAD

**Issue by kullachoke-bosuwan-rft** [OfficeDev/office-js#1274]
There is an error message shown in console every times that we executed function `Office.context.ui.messageParent` from dialog.

The error has no effect on our app workflow, add-ins are working fine but it would be great if you can get rid of this error message.

## Expected Behavior
No error in console after executed function Office.context.ui.messageParent

## Steps to Reproduce, or Live Example
  1. add multiple domains in manifest file under tag `AppDomains`
`<AppDomains><AppDomain>https://domain1.com</AppDomain><AppDomain>https://domain2.com</AppDomain><AppDomain>https://domain3.com</AppDomain>.....</AppDomains>`
  2. ribbon file hosted in domain1
  3. add a ribbon button that will open dialog on click (dialog also hosted in domain1)
  3. run Office.context.ui.messageParent from dialog.html to send data back to parent.
  4. check on dev console.
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://domain2') does not match the recipient window's origin ('https://domain1').`
`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://domain3') does not match the recipient window's origin ('https://domain1').`
.. and so on. The number of error message is depending on number of domain that you've added in manifest.

## Your Environment

* Platform: Office Online
* Host: Excel
* Office version number: All
* Operating System: All
* Browser (if using Office Online): Chrome

## Useful logs
![edited](https://user-images.githubusercontent.com/64405659/87137056-817d3100-c2c6-11ea-959c-c99810e2906e.png)
![edited2](https://user-images.githubusercontent.com/64405659/87137062-84782180-c2c6-11ea-8b4b-d70786ff41dd.png)

**Comment by lliu113** [comment]
@kullachokebosuwan-refinitiv - thanks for reporting this! Just to clarify, it sounds like the add-in is working as expected but the error message is annoying? What domain is your taskpane in when messageParent() is called?

Some background: we historically had a more restricted messaging model, where it will only work when the taskpane and dialog are on the SAME domain. This was relaxed to allow messaging between any trusted domain. My hunch is that this error was from the previous restrictions, which was never cleaned up when it was relaxed.

Will forward this onto the engineering team - thanks!

**Comment by lindalu-MSFT** [comment]
@kullachokebosuwan-refinitiv Our Eng just reported they could repro this. That's good news! It's under investigation, will let you know when a fix is available. No time expectation yet.

**Comment by kullachoke-bosuwan-rft** [comment]
Hi, @lindalu-MSFT @lliu113 

Sorry for the late response. I'm glad to hear that -- Thank you very much.

**Comment by lliu113** [comment]
@kullachoke-bosuwan-rft - late response but wanted to update that this is in our backlog, internal bug: 5088512

**Comment by donlvMSFT** [comment]
Based on the bug status, this issue should already been fixed in new APIs, please help verify. I'd like to close this thread then.
