### ISSUE TITLE
Visio: PageView.getPosition returns two times X, i.e. (x,x) instead of (x, y)

### ISSUE THREAD

**Issue by nbelyh** [OfficeDev/office-js#1275]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

The issue is about Visio API, function `PageView.getPosition` that is supposed to return page position (X, Y)
https://docs.microsoft.com/en-us/javascript/api/visio/visio.pageview?view=visio-js-1.1#getposition--

## Expected Behavior
The function is supposed to return page position, according to the documentation:
`Returns the position object that specifies the position of the page in the view`

## Current Behavior
The function returns doubled X coordinate, like (X, X) instead of (X, Y)
Y coordinate is not returned.

**Comment by lindalu-MSFT** [comment]
HI @nbelyh Same thing with this issue. It is being tracked internally in our backlog. Thanks much for reporting!
