### ISSUE TITLE
Outlook Add-in not showing on web version menu with sideload

### ISSUE THREAD

**Issue by Umair-Munir** [OfficeDev/office-js#1279]
Hi,

I am developing outlook add-in on Mac and using visual code. I am following [https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator](this) tutorial to create Taskpane App using Yeoman generator. I am able to build and run dev-server. I uploaded the manifest file on the web version of outlook to run and test the add-in. Everything works fine to this point and my add-in is showing up in custom-add-ins section as you can see in the image 
![Screen Shot 2020-07-14 at 1 54 02 AM](https://user-images.githubusercontent.com/8552862/87365012-5ff5a100-c575-11ea-9d6c-5346fc9ff762.png)

But the add-in is not showing up in the menu section as in the image

![Screen Shot 2020-07-14 at 1 54 45 AM](https://user-images.githubusercontent.com/8552862/87365059-887d9b00-c575-11ea-9d26-0ee85f22c25c.png)

I have tried creating the task pane app and also tested with React and simple javascript. But it's not working for me. Currently, I am on a free plan with 5GB storage and only access to online apps. 

Does it require to upgrade office membership for the development? or Am I missing something?

**Comment by exextoc** [comment]
@Umair-Munir  Please check these docs to see if you missed anything [Build your first Outlook add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart) and [Outlook add-in tutorial](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial) .

- Is it possible for you to share the manifest file of your Add-in?
- Looks like you are trying to use to Add-in in message compose scenario does your manifest file has ExtensionPoint MessageComposeCommandSurface ?

For more information on extension points in manifest check the [doc](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extensionpoint) .

**Comment by Umair-Munir** [comment]
@exextoc yes, my manifest file contains the ExtensionPoint attribute. I used the Yeoman generator to generate a Task pane plugin. From the tutorial, it should display the Task pane tab. This is the [manifest](https://github.com/OfficeDev/office-js/files/4917278/manifest.xml.zip) file of the Task pane plugin

**Comment by exextoc** [comment]
@Umair-Munir as your manifest file contains only MessageReadCommandSurface ExtensionPoint, it will be visible in message read scenario. If you want it to be shown when user is composing a mail you should add MessageComposeCommandSurface ExtensionPoint as well.  Same applies for event surfaces AppointmentOrganizerCommandSurface and AppointmentAttendeeCommandSurface.

**Comment by Umair-Munir** [comment]
@exextoc yes, that makes sense. Thank you for the response
