### ISSUE TITLE
Internet Message header with spaces in value cause failure on Windows

### ISSUE THREAD

**Issue by jak-hammond** [OfficeDev/office-js#1280]
When attempting to set an internet message header that contains a space in the value, both quoted and un-quoted, the call fails with an error code of 2006 saying that the given object was of an invalid format.

## Expected Behavior
The header should be set without issue.

## Current Behavior
When run on Windows, values that contain a space will cause a failure when calling `setAsync` on an item that is currently being composed.

## Steps to Reproduce, or Live Example
https://gist.github.com/jak-hammond/ec61adb4333941d9e3387a999ef7bd02

## Context
We set message headers based on some externally loaded which we have no control over the format of some of the values that are returned to us in. Some cases, these values may contain spaces which will then end up being set in the message headers of the current item.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC 
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2006 (Build 13001.20266 Click-to-Run)
* Operating System: Windows 10

## Useful logs
![image](https://user-images.githubusercontent.com/664193/87413073-bbe61700-c5c1-11ea-91e6-831a7c551390.png)

![image](https://user-images.githubusercontent.com/664193/87412667-34000d00-c5c1-11ea-82f6-7d1f6d3b9093.png)

**Comment by lindalu-MSFT** [comment]
@jak-hammond Thanks for providing all the relevant info in this issue! I've assigned to the Outlook team to triage.

**Comment by exextoc** [comment]
Thank you for providing the Gist repro and screenshots. I was able to reproduce the issue as well on the same version of Outlook. Our team tested OWA and Mac as well and the issue only occurred on Windows.

This issue has been added to our backlog for triage.

Internal tracking # (helps to provide an update later): Office:4301643

**Comment by exextoc** [comment]
This should be fixed in Win32 Office Build: 16.0.13127.10000.
