### ISSUE TITLE
[Excel] An error thrown in console on all Angular app

### ISSUE THREAD

**Issue by kullachoke-bosuwan-rft** [OfficeDev/office-js#1282]
All of Angular app has an error thrown in dev console, please check gif image or video file attached. It happens almost every time and only when included officejs script. An error has no effect with an app but it would be great if you can fix it.

App in video has been generated from scratch by using ng generate <app>, There is nothing in the project, only included officejs script.

## Expected Behavior
No error in dev console.

![Screen Recording 2563-07-16 at 12 58 59](https://user-images.githubusercontent.com/64405659/87635897-01454880-c76a-11ea-8f06-1b41cdbab3ad.gif)
[Screen Recording 2563-07-16 at 12.58.59.zip](https://github.com/OfficeDev/office-js/files/4929726/Screen.Recording.2563-07-16.at.12.58.59.zip)

**Comment by lindalu-MSFT** [comment]
@kullachokebosuwan-refinitiv Hi, sorry for the delayed response! We're a bit short on resources this week due to vacations. I assigned this to the correct team to investigate. Thanks, linda

**Comment by kullachoke-bosuwan-rft** [comment]
@lindalu-MSFT 
Thank you for looking into this. I hope we can find a solution soon.

**Comment by donlvMSFT** [comment]
@kullachokebosuwan-refinitiv , thanks for raising this issue, but we couldn't reproduce from our side. 
Could you share some detail steps to reproduce? It could be great helpful if there's any gist script or git project. 
Thanks in advance.

**Comment by kullachoke-bosuwan-rft** [comment]
@donlvMSFT , I've rechecked it today and can't reproduce an issue anymore. I'm waiting for our QA to verify this before close a ticket. Thanks a lot.

**Comment by kullachoke-bosuwan-rft** [comment]
I'll close a ticket as QA has confirmed that the issue couldn't reproduce anymore.

Thank you for your support.
