### ISSUE TITLE
OAuth 2.0 code flow - requested permissions are displayed incorrectly for free (outlook.com) accounts

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1288]
In an Outlook add-in for compose mode, we use Microsoft Graph to get access to OneDrive on behalf of a user. The following Microsoft Graph permissions are used in the scope query parameter:
'openid',
'profile',
'user.read',
'files.read.all',
'sites.read.all',

There is a difference in the "Ask to consent to the required permissions" steps for Office365 and Outlook.com accounts. I have attached 2 screenshots, please pay attention to "Have full access" in case of the outlook.com account.

![office365account](https://user-images.githubusercontent.com/28924916/87948290-2fe65a80-caad-11ea-9a0a-a442787ab2f4.png)
![outlookcomaccount](https://user-images.githubusercontent.com/28924916/87948311-34127800-caad-11ea-895e-b3c73a9f030e.png)

## Expected Behavior
Read access permission shall be shown for a user.

## Current Behavior
Full access permission is requested.

## Steps to Reproduce, or Live Example
You can use Graph Explorer:
https://developer.microsoft.com/en-us/graph/graph-explorer

Sign-in with an outlook.com account, go to OneDrive sample queries, choose the "all the items in my drive" query, switch to Modify Permissions and click the Consent button for Files.Read.All permission.

## Your Environment
* Platform: Office Online
* Host: Outlook
* Office version number:
* Operating System: Windows 10
* Browser (if using Office Online): Chrome, Edge

**Comment by DmitryKostochko** [comment]
Any news about the issue?

**Comment by exextoc** [comment]
We can reproduce the issue mentioned.
We are working on a fix and we will notify you once the fix is deployed.

**Comment by JeremyKelley** [comment]
Just to clarify the issue, thankfully this is a cosmetic issue where the strings in the dialog are incorrect, the actual permission being requested and granted is still Read Only.  String changes have been submitted but are not yet live.

**Comment by DmitryKostochko** [comment]
Thank you very much! Please let me know when it can be tested.

**Comment by Oleg-O** [comment]
I assume this has been resolved by now. Otherwise, please re-open.
