### ISSUE TITLE
Office.SharedProperties delegatePermissions contains int value not defined in Office.MailboxEnums.DelegatePermissions

### ISSUE THREAD

**Issue by jlevenssfdc** [OfficeDev/office-js#1293]
I've not looked at all of the users, but of the two that I've looked at the delegatePermissions value returned getSharedPropertiesAsync has a value not defined in the enum Office.MailboxEnums.DelegatePermissions.  I'm seeing values like 63 and 49. 

We're unable to use this property if we can't lookup/translate the value in the enum.

## Expected Behavior
The value of delegatePermissions is always defined in the enum Office.MailboxEnums.DelegatePermissions

## Current Behavior
The value of delegatePermissions is not always defined in the enum Office.MailboxEnums.DelegatePermissions

## Steps to Reproduce, or Live Example
I'm assuming this is specific to the user's I'm looking at, @exextoc You should still have a login to our exchange instance from a previous issue, please let me know if there's any issue with that.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: All
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 365
* Operating System: Any
* Browser (if using Office on the web): Chrome

**Comment by exextoc** [comment]
[Office.MailboxEnums.DelegatePermissions](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailboxenums.delegatepermissions?view=outlook-js-preview) is a bitmask that represents a delegate's permissions on a shared folder. For example, when you receive 63 as the value for delegatePermissions, which is represented as 111111 in binary, this means that the permissions DeleteAll, DeleteOwn, EditAll, EditOwn, Read, and Write are granted to the delegate.
