### ISSUE TITLE
how to allow single sign on login using office 365 from office desktop addin 

### ISSUE THREAD

**Issue by shyambhiogade** [OfficeDev/office-js#1297]
we have an office excel addin developed using office.js. to be able to use our addin - the user needs to have user id and password to log in. We provide the single sign-on option with office 365 along with other sign-in option. 

![image](https://user-images.githubusercontent.com/10468130/88463087-0b033600-ce65-11ea-912c-83feb9ff6952.png)

As I understand any domain accessed from the office addin should be listed on the app domain in the manifest file else it launches the browser window if addin is used from office desktop version. Single sign-on option with office 365, launches the organization sign-in page, with the following dialog,

![image](https://user-images.githubusercontent.com/10468130/88462934-fa05f500-ce63-11ea-94ef-f9b2f68d5b27.png)

then redirect me to the corporate login page, in my case its https://sso.aveva.com, i have added these entries in the manifest file and addin works well for my organization. **How do i make it work for customers who could be having sign-in URL specific to their organization?**

**Comment by shyambhiogade** [comment]
@weshi @lindalu-MSFT @Rick-Kirkham can you please help

**Comment by lindalu-MSFT** [comment]
@RuoyingLiang Can you please help us triage this matter?

**Comment by shyambhiogade** [comment]
hi @lindalu-MSFT its not related to custom functions

**Comment by shyambhiogade** [comment]
@lindalu-MSFT can you please get someone help me in for this issue, is blocking our production release, there must be something you guys would have already thought about this scenario, it might be a matter of just searching in your internal database about this kind of issue.

**Comment by keyur32** [comment]
Hey @shyambhiogade, thank you for the report.  I have a few questions so we can route this over to our Identity team:
Can you clarify, what you mean by "How do i make it work for customers who could be having sign-in URL specific to their organization?"
- Are these sign-in URLs on the same domain i.e. customer1.aveva.com, customer2.aveva.com?  
- Is your identity integrated with Azure AD, and are they looking to sign in with their tenant?  (trying to understand what is meant by single sign on here).  thanks!

**Comment by shyambhiogade** [comment]
@keyur32 we have a web application https://online.wonderware.com/ you can take a look at it, to be able to sign in to this you need to have userid and password, user can also use their organization login id to get the access to the portal like I can send an invitation on your  microsoft id and you can login to the portal by sigining in to your office 365 account, you dont need to create the separate password.

same goes for office addin, it actually uses the same interface as our web application to sign in.

sign in url will not be same domain. 
single sign on here mean, you can use your organization sign on to log in to our platform.

**Comment by shyambhiogade** [comment]
@keyur32 let me know if we can talk about this issue on the Microsoft team or if you need any more details. @lindalu-MSFT can someone please look into this urgently, if needed I can raise the priority support request. we are partners with Microsoft.

**Comment by shyambhiogade** [comment]
@lindalu-MSFT can someone please help..its pushing my product release date. There is not good help available on office addins.

**Comment by shyambhiogade** [comment]
@lindalu-MSFT @keyur32 any update on this issue.

**Comment by lindalu-MSFT** [comment]
Hi, I just assigned this to our dev writer for authentication @Rick-Kirkham  and a couple people on the Excel team. @keyur32 @lumine2008  Can someone help this customer please? Or tell me who is the right person who can help him sort out this issue? He has an app he's trying to ship!

**Comment by shyambhiogade** [comment]
@keyur32 @Rick-Kirkham @lindalu-MSFT @lumine2008 I am still waiting for the help.

**Comment by shyambhiogade** [comment]
help please

**Comment by shyambhiogade** [comment]
@keyur32 @Rick-Kirkham @lindalu-MSFT @lumine2008, please help

**Comment by keyur32** [comment]
Hi there,

- If you want single sign on to get the user token without having to ask the user to sign in again, we just had the single sign on feature ship: https://developer.microsoft.com/en-us/microsoft-365/blogs/announcing-general-availability-of-single-sign-on-sso-for-office-add-ins/

- If you have multiple tenants or different domains, we suggest following an approach where each deployment has a different manifest with it's own set of specified app domain URLs. The App Domain URLs list requires all domains to be listed. With these instead of submitting the add-in into the store, you will need

Hope that helps.

**Comment by shyambhiogade** [comment]
@keyur32 looks like my question is not understood correctly. your second point is somewhat related to what i am asking for but does not answer. let me try to explain it again, also do read my question again and the comment i gave after that.

following is the image of manifest file of my addin, My addin after loading in the excel shows web interface to allow enterprise user to login. to login user can use their corporate email id which is integrated with office365, some customer may be redirected to specific company specfic url to login to office 365, like for aveva its sso.aveva.com and then it allows to login to office 365, as you can see in following manifest file image, i have added that url. so that when i am using my addin in desktop version of excel it does not launch the browser window.

![image](https://user-images.githubusercontent.com/10468130/89751382-a7901f80-da84-11ea-9e57-6b018dd18633.png)

similarly, the customer may have similar url specific to their corporation to sign in to office365 and then in our application. 

is there any wide char I can add-in the manifest file so that any URL can be accessed from office addin

@weshi please see if you could help, we had team call with you in the march to fix some other issue 
@keyur32 let me know if we can meet on team. its been 15 days but still looks like my question is not understood..

**Comment by shyambhiogade** [comment]
any update please

**Comment by shyambhiogade** [comment]
any update please

**Comment by keyur32** [comment]
Hi @shyambhiogade, we'll work with @weshi  and reach out to you directly.  Unfortunately, the app domain URLs need to be an exact match. That's why we suggest creating seperate manifest per customer and have them use centralized deployment to deploy their add-in.

**Comment by shyambhiogade** [comment]
@keyur32 that will not be feasible as there could be lot of customer and we want to have one place that is office store to get them the office addin, i do not see this issue in web version of excel. any workaround on this.

**Comment by extremeandy** [comment]
We are also facing this issue. We're rolling out to hundreds of clients, who may have different company portals they're required to sign into, and it's not really feasible to hand-craft a manifest file for each and every client.

**Comment by keyur32** [comment]
Hi sorry for the delay on this, but unfortunately we don't have a good story for allowing wild card support in our sub domains list. It is still something the team is checking on but we don't have an ETA the moment. I have tagged this to indicate it is a product feature request for tracking purposes.

**Comment by lindalu-MSFT** [comment]
If you're still interested in adding this feature, please go to our new [Ideas forum](https://aka.ms/m365dev-suggestions) and click **Submit an Idea**. If there's enough interest (votes), we will follow up with you there and add it to our feature request backlog. Please add link to the suggestion in the comments for tracking. Thanks, lindalu
