### ISSUE TITLE
content controls are not deleted when track changes is turned on

### ISSUE THREAD

**Issue by kamilmach** [OfficeDev/office-js#1299]
## Expected Behavior

Content Controls should be deleted.

## Current Behavior

After creating new content control - turning on 'track changes' and putting a comment on content control causes this content control to be 'undeletable'
## Steps to Reproduce, or Live Example

* Repro steps:
  1. create new content control by running this gist : https://gist.github.com/kamilmach/8178ff3f857174c881104bc24e6a68a1
  2. turn on 'Track changes'
  3. leave a comment on content control
  4. delete content control and get document ooxml by running this gist :
https://gist.github.com/kamilmach/982b54f1816ab5e8667e80ff98ac6be5
  5. observe thet in copied ooxml there is still data for deleted content control. 
  6. run above gist once again and observe the content control is still being detected inside the document

## Context

Mentioned issue is currently affecting our users. Some parts of our application are expecting content control to be deleted and when it's not it's causing breaking side effects
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:  Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.39
* Operating System: macOS 10.14.6

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by serjant** [comment]
I had reported about this two years ago, and they have just closed the ticket after a year of the investigation.

**Comment by AbidRahman-MSFT** [comment]
We are internally tracking this bug with: 4650379.

**Comment by AbidRahman-MSFT** [comment]
Hey everyone, after investigation, this behavior is by-design. If trackchanges mode is on, content controls that are deleted must be displayed in the Ooxml of the document. If the content control is no longer represented in the Ooxml, there is no way for the application to restore the changes.

You can see the Ooxml file has several w:customXmlDelRangeStart - w:customXmlDelRangeEnd pairs, while a file with no track changes on does not have them. Each pair marks a range within a change. A change has multiple pairs for multiple places, and the document can have multiple changes which are differentiated with the time. Developers are able to use these elements to determine which content controls have been deleted during track changes mode.

E.g. note the ```customXmlDelRangeStart``` and ```customXmlDelRangeEnd``` tags.
```
<customXmlDelRangeStart w:id="0" w:author="Abid Rahman" w:date="2020-12-17T10:03:00Z" />
<sdt>
    <sdtPr>
        <id w:val="-650451726" />
        <placeholder>
            <docPart w:val="C7312EC74CA845ABA031FA1AF0333EE8" />
        </placeholder>
    </sdtPr>
    <sdtContent>
        <customXmlDelRangeEnd w:id="0" />
        <p w:rsidR="008711D4" w:rsidRDefault="008711D4" />
        <customXmlDelRangeStart w:id="1" w:author="Abid Rahman" w:date="2020-12-17T10:03:00Z" />
    </sdtContent>
</sdt>
<customXmlDelRangeEnd w:id="1" />
```
