### ISSUE TITLE
Lots of noise in console

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js#130]
When I want to test my add-in on outlook.office.com I am seeing lots of noise in the dev console, having an impact on my developer productivity.

![screen shot 2018-05-15 at 10 38 26](https://user-images.githubusercontent.com/177641/40027030-1f14172e-582c-11e8-9465-6f0e635bc1cb.png)

Why are you sending cookies with more than 4096 characters?

**Comment by binarykitchen** [comment]
Also too many POST errors for Telmetry:

![screen shot 2018-05-15 at 10 39 13](https://user-images.githubusercontent.com/177641/40027053-3cc5d438-582c-11e8-9b22-eb78e8f10d83.png)

**Comment by exextoc** [comment]
These are notifications from OWA, I do not believe there is a way to silence them. Depending on your console debugger, can you filter the console so that you only get messages from your code?

**Comment by binarykitchen** [comment]
Yes I can filter some but then, I won't see any outputs from my code of the same level I have filtered out. Not a good solution. I still would reduce all the above noise for a starter.

**Comment by schmkr** [comment]
Not sure about other browsers, but at least with Chrome you can select the context for which you want to see the console (“top” in your screenshot), if you select the frame context in which your addin is running, it already becomes a lot more quiet.
And you can also filter some sources (so not based on a level, but based on the is file that generated the log line). Using that also silences the console a lot!

**Comment by binarykitchen** [comment]
Yeah, with those filters I can reduce some noise.
