### ISSUE TITLE
`displayNewAppointmentForm` function is not setting html content correctly in macOs.

### ISSUE THREAD

**Issue by hmistry-lz** [OfficeDev/office-js#1300]
`displayNewAppointmentForm` function is not able to set HTML content in Outlook Mac.
the same function works fine in Office365.
I want to display HTML content in the appointment Body but it shows me HTML tag in a plain string.
![image](https://user-images.githubusercontent.com/53185673/88589037-236a8080-d01e-11ea-8e96-49c2fb302c81.png)

## Expected Behavior
It should set HTML content in the appointment just like it does in the browser.

![image](https://user-images.githubusercontent.com/53185673/88589150-4eed6b00-d01e-11ea-9d27-8c8375e5ebd5.png)

## Current Behavior
It is displaying HTML in plain string while calling `displayNewAppointmentForm`

## Steps to Reproduce, or Live Example
Please use following function in outlook mac desktop client to reproduce it.

```
Office.context.mailbox.displayNewAppointmentForm({
      body: '<div><b>This should be displayed in HTML</b></div>',
      location: 'Austin, TX',
      subject: 'Subject'
});
```

## Context
it is creating different experiences for our outlook plugin in different platforms.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac, Windows
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.39
* Operating System: Catalina 10.15.5
* Browser (if using Office on the web): N/A

## Useful logs
It is not creating any error.

**Comment by exextoc** [comment]
Thank you for reporting this issue. This has been put in our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: Office:4332228,4340528

**Comment by Oleg-O** [comment]
For Windows (Office:4340528), this has been fixed around February 2022 and integrated in build 16.0.15002.10000.
For Mac (Office:4332228), it's still in backlog.

**Comment by exextoc** [comment]
For Mac (Office:4332228), this has been fixed around August 2020 and integrated in build 16.42 (20101102).
