### ISSUE TITLE
[Word] getSelection().parentContentControl not working on plaintext content controls

### ISSUE THREAD

**Issue by remar27** [OfficeDev/office-js#1302]
## Expected Behavior
Running context.document.getSelection().parentContentControl should return Word.ContentControl object or throw exception if parentContentControl not found. [See the documentation](https://docs.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview#parentcontentcontrol).

## Current Behavior
- Running the code with the cursor inside Rich Text content control - ok.
- Running the code with the cursor inside Plain Text content control - exception (code=ItemNotFound).

Doesn't matter if selected range is empty ir not (context.document.getSelection().isEmpty).

## Steps to Reproduce, or Live Example
Link to live example: [Script Lab](https://gist.github.com/remar27/79b7ddc51368f49d90d24c5b37f50461).

To reproduce:
1. Insert plain text content control
2. Insert rich text content control
3. Place the cursor inside plain text content control and run the code example. Error will be thrown.
4. Place the cursor inside rich text content control and run the code example. Ok.

## Context
I'm trying to get ContentControl value on cursor position then obtain ContentControl OOXML value parentContentControl.getOoxml() and send to server-side for further data processing.

The document may have multiple content controls, some of them are Plain Text type. Visually there are no difference between Plain Text and Rich Text controls. Just you can't have advanced formatting or nested content controls inside plain text content control. I think the behavior of parentContentControl should be the same on both content control types.

## Your Environment

Office for Windows (desktop):
- Office 365 Pro Plus (Version 2006, Build 13001.20384, Current Channel)
- Office Professional Plus 2016 (Version 2002, Build 12527.20278)

OS:
- Windows 10 1909, Windows Server 2019, Windows Server 2012.

Issue is the same in all tested versions and environments.

## Useful logs

`[ERROR]: Error:
{
    "description": "ItemNotFound",
    "message": "ItemNotFound",
    "name": "RichApi.Error",
    "code": "ItemNotFound",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "ItemNotFound",
        "message": "ItemNotFound",
        "errorLocation": "Range.parentContentControl",
        "statement": "var parentContentControl = v.parentContentControl;",
        "surroundingStatements": [
            "var v = context.root._getObjectByReferenceId(\"r!00000010\");",
            "// >>>>>",
            "var parentContentControl = v.parentContentControl;",
            "// <<<<<",
            "// Instantiate {parentContentControl}",
            "parentContentControl.load();"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "stack": "ItemNotFound: ItemNotFound\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:26:289636)\n   at o (https://script-lab-runner.azureedge.net/static/js/1.0f9cfae3.chunk.js:1:2779072)\n   at Anonymous function (https://script-lab-runner.azureedge.net/static/js/1.0f9cfae3.chunk.js:1:2779219)\n   at u (https://script-lab-runner.azureedge.net/static/js/1.0f9cfae3.chunk.js:1:314565)"
}`

**Comment by shishiradas** [comment]
Facing the same issue

**Comment by AbidRahman-MSFT** [comment]
Hey @remar27 and @shishiradas, 

Thanks for reporting the issue and apologies for the delay in response.
We currently do not support plain text content controls for any API functionality. Only rich text content controls are supported right now. We do have plain text content control support in our backlog but currently it is not a prioritized feature so there is no ETA i can provide.

Thanks,
Abid
