### ISSUE TITLE
[Outlook ] getSharedPropertiesAsync not supported on Mac 

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1304]
getSharedPropertiesAsync  not supported on Mac yet.
Is there any plan this feature will be done?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac

**Comment by SWei1234** [comment]
@exextoc 
I have inner update Mac outlook client to version 16.41(20072901) .
Is this version should support this feature.
Tested on this version , support 1.8 set ,but not support Office.context.mailbox.item.getSharedPropertiesAsync

**Comment by exextoc** [comment]
We support Office.context.mailbox.item.getSharedPropertiesAsync from Version 16.41 (20072700) (Insider ring).
You'll have to be on Insiders Fast ring, to have the same.

**Comment by SWei1234** [comment]
Hi @exextoc 
I have already updated to a version later than 16.41 (20072700), will it support this ?

**Comment by lindalu-MSFT** [comment]
@SWei1234 are you on the Insider Ring version? @exextoc How does he get insider ring version? (Sorry, I don't know either!)

**Comment by SWei1234** [comment]
Hi @exextoc @lindalu-MSFT 
I'm not in version 16.41 (20072700).  Is there a way for us to get that version? 
Thanks

**Comment by exextoc** [comment]
You can visit [here](https://insider.office.com/en-us/releasenotes/mac/fast) for more info.

**Comment by SWei1234** [comment]
@exextoc 
It's seems 16.41(20072901)  is same with 16.41 (20072700). And I have both tried run 'Office.context.mailbox.item.getSharedPropertiesAsync' on console. It's return undefined.
And I tried update to the latest insider fast version 16.41(20080203) then run 'Office.context.mailbox.item.getSharedPropertiesAsync' again. Still get undefined.
I'm using both 1.1 version and beta version office.js.

Are there any problems with the above operations?

Thanks

**Comment by exextoc** [comment]
There can be many reasons why the same isn't working for you 

- Make sure you're using API set 1.8 

- The API is only available on shared items, trying to use it on non shared item won't work. Please visit [here](https://docs.microsoft.com/en-us/javascript/api/outlook/office.sharedproperties?view=outlook-js-preview) for more insights. 

- Does it throw any error when you use the API (given the above two conditions are met) ?

**Comment by SWei1234** [comment]
Hi @exextoc 
I have already make sure the set 1.8 is supported.
And I do all operation on a shared calendar. And this is working on windows.
When I trying to call  'Office.context.mailbox.item.getSharedPropertiesAsync' only return 'undefined'

**Comment by exextoc** [comment]
Can you please share the exact repro steps, so that we can try it out and see if it repros for us or not ?

**Comment by SWei1234** [comment]
Sure. 
Mac OS version:10.15.6
Outlook version: 16.41 (20080203) 
outlook debug is on
1. use preview office.js 
https://appsforoffice.microsoft.com/lib/beta/hosted/office.js
2. Open a new meeting on shared calendar and then open add-in (we also called getSharedPropertiesAsync in add-in)
3. Then open devTool and input 'Office.context.mailbox.item.getSharedPropertiesAsync' on console.

**Comment by SWei1234** [comment]
@exextoc 
We have tried the steps from Microsoft suggestion:
Add shared calendar to 'Open these additional mailboxes' .
Now Office.context.mailbox.item.getSharedPropertiesAsync is not undefined any more.
But return 
name: "API Not Supported", Message：“This browser does not support the requested API”  code:5009 
(manifest permission: ReadWriteItem , delegate permission is editor , both tried beta and Ver 1.1 office.js)
Mac OS: 10.15.6 Outlook: 16.41(20080203) 
Any idea?

**Comment by exextoc** [comment]
Apologies for this delay. We are actively working on this and will be able to provide update soon on this.

**Comment by SWei1234** [comment]
@exextoc 
It's okay. Really appreciate your support. : )

**Comment by exextoc** [comment]
Marked an already opened bug as active for this issue

Bug 1610666<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fo365exchange.visualstudio.com%2F959adb23-f323-4d52-8203-ff34e5cbeefa%2F_workitems%2Fedit%2F1610666&data=04%7C01%7Canoberoi%40microsoft.com%7C02f1e6d60bbe446a540508d837cca1e4%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637320699322883371%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=S2Lw1rgLPlldVPd5SDYri3LKNkAb8QraCTZJRIBLhjg%3D&reserved=0>: [OfficeDev/office-js] [Outlook ] getSharedPropertiesAsync not supported on Mac (#1304)

Best,
Ankush
________________________________

**Comment by exextoc** [comment]
@SWei1234  Fix is in prod now for builds 16.40.810.0 and above. Please check and confirm.

**Comment by SWei1234** [comment]
Hi @exextoc 
I have tried this on Mac latest prod version 16.40 (20081000) and insider fast latest version 16.41 (20082600) . 
In prod version not support api getSharedPropertiesAsync. 
In insider fast version it show error that api not supported...
Any idea?
By the way, I test all above on Mac outlook client. The version format not like 16.40.810.0 . Any difference or misunderstanding?
Thanks

**Comment by exextoc** [comment]
Can you upgrade it to Insiders Fast 16.41(20083005) and try again? Also are you on New Outlook UI or classic Outlook UI in insider fast? This will be available on Classic Outlook UI. To check classic vs New UI you can check here on top bar-
![MicrosoftTeams-image](https://user-images.githubusercontent.com/28549921/91838944-e708f080-ec6b-11ea-90d1-e3cf2260f8fb.png)


16.40.810.0 is the format which we use internally and is same as 16.40(20081000).

Can you also share code snippet which you are trying?

**Comment by SWei1234** [comment]
Hi @exextoc 
I have tried this on 16.41(20083005) and 'New Outlook' keep off. 
Now it report "API Not Supported"...
Any other thing I need to check? Or this is not released yet? Because I found other feature Microsoft promise will release yesterday not work too.
Any idea?

**Comment by exextoc** [comment]
@SWei1234 Can you please share your email id here- admin@a830edad9050849405E20081103.onmicrosoft.com so that we can schedule meeting with you?

**Comment by SWei1234** [comment]
Hi @exextoc 
Just as meeting showed just zoom add-in can't use this api , can you please help find out the reason?
what configuration need to be done?
Thanks

**Comment by SWei1234** [comment]
It works when we set <Permissions> to ReadWriteMailbox in manifest xml file.
