### ISSUE TITLE
[Outlook] ribbon "Start" not working with Exchange 2016 on-premises and Office 365

### ISSUE THREAD

**Issue by m24cl6000** [OfficeDev/office-js#1306]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I developped an add-in for Outlook. The add-in is shown in Ribbons Start, Message (for read) and Ribbon message (in compose). It works perfect for Office.com accounts, with all Clients, web-Clients and so on.

if i use Exchange 2016 account on local Exchange, only the Office 365 (build 16.0.13001.20448 64 bit 365 MSO) with Outlook Version 2006 build 13001.20498 click-and-run) behave strange.

read:
Ribbon start: button is shown, when clicked no Action happens
Ribbon Message: okay
compose:
Ribbon message: no Icon !

Local Exchange 2016 account with Office 2013, Exchange2016/owa is okay and wotks fine.

## Expected Behavior

for Read: when clicked open Taskpane, for compose: Show the button and open Taskpane
## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by m24cl6000** [comment]
Although the <local>/owa is running correctly i found 3 warnings in console.log.
SRV3 = <local Exchange 2016  Server>
SRV3 has CU17 (15.1.2044.4 installed)

HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
(Fetch)GET - https://srv3/owa/prem/15.1.2044.4/resources/locale/de/owa-calendar-strings.json

HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
(Fetch)GET - https://srv3/owa/prem/15.1.2044.4/resources/locale/de/owa-groups-strings.json

HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
(Fetch)GET - https://srv3/owa/prem/15.1.2044.4/resources/locale/de/owa-extensibility-strings.json

the Directory "locale" is missing in 
C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\Owa\prem\15.1.2044.4\resources


Maybe that causes the Problem with Office 365 ?

regards Moritz

**Comment by exextoc** [comment]
Can you clarify what you mean by "Ribbon start". Maybe some screenshots can help.

For message compose, make sure that you specify the extension point [MessageComposeCommandSurface](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extensionpoint#messagecomposecommandsurface) in your manifest. If possible, can you please share your manifest?

**Comment by m24cl6000** [comment]
Ribbon "Start" is the first ribbon activ when you start outlook.
Your message is enabled but not double-clicked!
Add-in Name gpg4web. The button is visible, **but now action comes up** if you click.

![ribbon](https://user-images.githubusercontent.com/49696572/89077364-4f6d6500-d382-11ea-9710-2cfe9191814f.png)

When you double-click, in the next window you got ribbon "Message (german=Nachricht).
Here everything works fine. If you click the add-in, TaskPane will open and add-in starts

![ribbon2](https://user-images.githubusercontent.com/49696572/89077809-5ba5f200-d383-11ea-8338-64221b9eab83.png)

In compose the button is missing

![ribbon3](https://user-images.githubusercontent.com/49696572/89078117-05857e80-d384-11ea-9d0c-943a08b47d74.PNG)

Problem exists only in office 365 and exchange 2016 on-premises.

For example here the compose-window from /localexchange/owa.  SRV3 is the local exchange 2016.
Everything is  okay and working. Same server, same account.

![ribbon4](https://user-images.githubusercontent.com/49696572/89079539-0370ef00-d387-11ea-8b35-ca64e1a79406.PNG)


I added a print-out from the manifest. SRV2 is the local IIS hosting the add-in.

[manifest.pdf](https://github.com/OfficeDev/office-js/files/5009110/manifest.pdf)

**Comment by exextoc** [comment]
In your Compose Email Screenshot. The "From / Von" Field is blank. Is this email actually being sent from an Exchange Account? Or from another account that you added to your profile? Add-ins are only available per Exchange Account. So if you switch to another account that you added, then your add-in won't appear, unless you also install the add-in on that account.  

On the same line of thinking, when you REPLY to an email where you add-in was installed, does the add-in appear?

**Comment by m24cl6000** [comment]
Okay,
first point for you ;-) The button comes up when i changed the from to an Exchange account. But sorry - no action happens when i click, Same problem as in ribbon "start".

When i reply to an message the ribbon shows the add-In, after clicking the result is: Task-Pane opens, showing wrong context, add-in is not running (checked with devTools).

![ribbon5](https://user-images.githubusercontent.com/49696572/89081203-2ac9bb00-d38b-11ea-975e-9fd46a10b68d.png)

**Comment by m24cl6000** [comment]
More news.

Changing default settings change behaviour too. I switched default account setting in Outlook options to Exchange-Server.
Result is: add-in shows up in compose and works okay !

So changing default gives different behaviour as switching "from".

![ribbon6](https://user-images.githubusercontent.com/49696572/89081914-cc9dd780-d38c-11ea-8f68-4c6f2ba4ea01.png)
png shows values before switch !!

**Comment by exextoc** [comment]
Add-ins only work in Exchange accounts. 

In read mode ("ribbon start") is there any error dialog when you click on the ribbon button and the taskpane does not open? Do other add-ins behave the same way? Instructions for installing other add-ins are [here](https://support.microsoft.com/de-de/office/installieren-von-office-add-ins-in-ihrem-postfach-65e243f5-cdac-4987-8185-97069a6058cb?ui=de-de&rs=de-de&ad=de).

**Comment by m24cl6000** [comment]
Sorry for late answer, it was more than 30 minutes past midnight  when your last message arrives ;-)

I tried a new profile with only one Exchange account on my Office 365 .  **Everything is okay !!**

Okay. I went to my local Desktop with Office 2013. It is an profile with single Exchange account :-(

Next step - I added the same Pop/imap account to that profile. Outlook 2013 can handle that combination - profile with Pop/imap and Exchange - correct. All Ribbons function correct! (compose only when send-from=Exchange).

So there is stil a difference in Office 2013 and Office 365.

**Comment by exextoc** [comment]
Thank you for reporting this issue. This has been put in our backlog. We unfortunately have no timelines to share at this point.
Internal tracking id: Office:4348489

**Comment by m24cl6000** [comment]
Hi,
thx for your answers. Your notes where very helpfull for me. Should I close the issue or it stays open until the Backlog is cleared?

**Comment by exextoc** [comment]
Thanks. Please leave this open.
