### ISSUE TITLE
Outlook Online Pinned Taskpane reloading on item change

### ISSUE THREAD

**Issue by as-aaron** [OfficeDev/office-js#1308]
Pinned taskpane add-in's disappear and reanimate in from the side / reload whenever you change item inside of a folder.

## Expected Behavior

Pinned taskpane add-in's should stay open and not reload when changing item

## Current Behavior

Pinned taskpane add-in's disappear and reanimate in from the side / reload whenever you change item

## Steps to Reproduce, or Live Example

Open any pinnable taskpane add-in, pin it and then select a different item. You should see the add-in disappear and reanimate in / reload.

## Context

This causes a significantly poor experience for users as they have to wait for the add-in to be reloaded every time it updates with details from the newly selected item.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: OWA
* Operating System: Windows 10
* Browser (if using Office on the web): Reproduced in Chrome, Firefox, New Edge

**Comment by exextoc** [comment]
We are aware of this issue and have already pushed a fix. The changes will by live by end of the week, 
Please try again on Monday.

**Comment by exextoc** [comment]
@as-aaron Can you please check this is fixed for you now? Thanks.

**Comment by as-aaron** [comment]
Appears fixed for me 👍 Thanks

**Comment by exextoc** [comment]
Thanks @as-aaron for confirming. We are closing this issue now.
