### ISSUE TITLE
Outlook web TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by jurisjansons** [OfficeDev/office-js#1309]
I see that there has been some delivery of new version of offise.js? Based on [This](https://github.com/OfficeDev/office-js/issues/1285#issuecomment-668504229) comment.

I'm currently having problems with DialogAPI from what I can tell.

## Expected Behavior
Outlook add-in opens

## Current Behavior
Outlook add-in gets stuck after authorization with DialogAPI

## Steps to Reproduce, or Live Example
Try msal authorization with DialogAPI

## Context
Users can't use outlook add-in in web any browser. Fails after authorization. Erverything workend a while ago (can't tell exactly when, maybe yesterday). Haven't change any code on my end since last time worked.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook web
* Office version number: unrelated
* Operating System: Widnows 10, macOS Catalina
* Browser (if using Office on the web): Edge, Internet Explorer, Chrome, Firefox, Safari

## Useful logs
`outlook-web-16.01.js:19 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://login.windows.net') does not match the recipient window's origin ('---').`

`Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://login.microsoftonline.com') does not match the recipient window's origin ('---').`

`Uncaught TypeError: Cannot read property 'replace' of undefined
    at T (outlook-web-16.01.js:19)
    at R (outlook-web-16.01.js:19)
    at outlook-web-16.01.js:19
    at Object.a [as callback] (outlook-web-16.01.js:19)
    at L (outlook-web-16.01.js:19)`

**Comment by exextoc** [comment]
We are able to reproduce this issue on our side. Thanks for reporting this issue regarding DisplayDialog API. 
We are actively working on this issue as it is high priority. We unfortunately have no timelines to share at this point

**Comment by abdulkareemnalband** [comment]
Investigated further:
It fails here https://appsforoffice.microsoft.com/lib/1/hosted/outlook-web-16.01.debug.js at line number `9414`

`addErrorMessage(9051, "SessionObjectMaxLengthExceeded", getString("l_SessionDataObjectMaxLengthExceeded_Text").replace("{0}", sessionDataLengthLimit));`

While calling `addErrorMessage` for error `9051 : SessionObjectMaxLengthExceeded` 
`getString("l_SessionDataObjectMaxLengthExceeded_Text")` is returning `undefined` so and we cannot call `replace` on undefined.

**Comment by exextoc** [comment]
We have pushed our changes to production.
It may take at max 24 hours for the changes to get reflected (cache may have older copies) .
