### ISSUE TITLE
Office.context.auth.getAccessTokenAsync returns error 5009 in Office Online

### ISSUE THREAD

**Issue by vskh** [OfficeDev/office-js#131]
`Office.context.auth.getAccessTokenAsync()` (part of Identity API) currently does not seem to work in Office Online despite [claiming to do so](https://dev.office.com/reference/add-ins/requirement-sets/identity-api-requirement-sets).

## Expected Behavior
The following code should log an access token when add-in is opened in Office Online.

```
Office.initialize = reason => {
    Office.context.auth.getAccessTokenAsync({ forceConsent: true }, result => {
        if (result.status === Office.AsyncResultStatus.Succeeded) {
            console.log("Token: " + result.value);
        } else {
            console.error(result.error);
        }
    });
};
```
The code above works when add-in is launched in Office 2016 for Windows by providing a consent window and returning a successful result with the token after user approval.

## Current Behavior
Currently, in Office Online (tried in Word & Excel) the same add-in receives an error result:
`Object { name: "API Not Supported", message: "This browser does not support the requested API.", code: 5009 }`

## Context
I've been trying to use Identity API to retrieve user's profile from within the add-in.

## Your Environment
* Platform: PC Desktop - Windows 10, Office365 (works); Office Online (does not work)
* Host: tried in Word and Excel with same results
* Office version number: 16
* Operating System: Windows, Linux
* Browser (if using Office Online): the issue is reproducible in Firefox (60.0, 64 bit) and in Chrome (Chromium 66.0.3359.139)

## Useful logs
- [x] Console errors
```
{…}
​code: 5009
​message: "This browser does not support the requested API."
​name: "API Not Supported"
​__proto__: Object { … }

Office.initialize/<
app.js:22446:13
OSF.DDA.issueAsyncResult
https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:21:60475
onComplete
https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:21:72199
OSF.DDA.WAC.Delegate.executeAsync/<
https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:21:112138
lt
https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:21:101409
```

**Comment by dorisgega** [comment]
Currently we only support SSO for sharepoint production environment in Office Online. For onedirve.com and outlook.com, SSO will come later (https://dev.office.com/reference/add-ins/requirement-sets/identity-api-requirement-sets). We don't support SSO for ppe environment, so you can not try it in msft.spoppe.com. Which environment are your using ?

**Comment by vskh** [comment]
I am opening https://office.live.com/start/Word.aspx?auth=1. Is it considered OneDrive.com or Office Online? The table on a page you've provided is rather confusing.

**Comment by vskh** [comment]
After experimenting a bit I think I understood: if I log in with liveid that seems to use OneDrive as a storage and add-in does not work (this is what table refers to as OneDrive.com). If I log in with orgid, it uses sharepoint as a storage and add-in does work (this is what you referred to as sharepoint environment of Office Online).

Is there a roadmap for the rest of scenarios (OneDrive/liveid)?

**Comment by dorisgega** [comment]
Currently we don't have an accurate timeline for it. Hopefully we will enable it for Onedrive by the end of July.

**Comment by vskh** [comment]
Thanks, looking forward to it.
