### ISSUE TITLE
undefined returned by o("l_SessionDataObjectMaxLengthExceeded_Text") which then fails a .replace method call

### ISSUE THREAD

**Issue by cdmdotnet** [OfficeDev/office-js#1313]
Using your library returns an error on loading the add-on. There is no stack trace leading back to my code
```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at T (outlook-web-16.01.js:formatted:9475)
    at R (outlook-web-16.01.js:formatted:9735)
    at outlook-web-16.01.js:formatted:9714
    at Object.a [as callback] (outlook-web-16.01.js:formatted:9752)
    at L (outlook-web-16.01.js:formatted:4791)
```
Walking the stack the data is
```
T(9046);
R(undefined, 1, 9046, undefined, undefined);
L( t: "{"_messageType":1,"_actionName":"ExecuteMethod","_conversationId":"-1402858b_-7b6ba98a_1596586498558","_correlationId":13,"_origin":"https://outlook.live.com","_data":{"error":1,"errorCode":9046},"_errorCode":0,"_responseType":0,"_serializerVersion":1}" )
```

## Expected Behavior

There is no error.

## Current Behavior

`o("l_SessionDataObjectMaxLengthExceeded_Text")` returns `undefined` so when YOU call `o("l_SessionDataObjectMaxLengthExceeded_Text").replace("{0}", 5e4)` YOU produce YOUR own error
The full line is 
`S(9051, "SessionObjectMaxLengthExceeded", o("l_SessionDataObjectMaxLengthExceeded_Text").replace("{0}", 5e4))`
It's all minified so I have no idea what or why this is

## Steps to Reproduce, or Live Example

open an extension

* Additional details:
open an extension
## Context

open an extension

## Your Environment

* Platform Outlook.com
* Host Outlook.com
* Office version number:  Outlook.com
* Operating System:  Windows 10
* Browser (if using Office Online): Chrome

## Useful logs

Uncaught TypeError: Cannot read property 'replace' of undefined
    at T (outlook-web-16.01.js:formatted:9475)
    at R (outlook-web-16.01.js:formatted:9735)
    at outlook-web-16.01.js:formatted:9714
    at Object.a [as callback] (outlook-web-16.01.js:formatted:9752)
    at L (outlook-web-16.01.js:formatted:4791)

**Comment by cdmdotnet** [comment]
I've track this down to making a call to `Office.context.mailbox.item.getItemIdAsync` results in the library crashing out.
```
			Office.context.mailbox.item.getItemIdAsync(function (asyncResult) {
				// never makes it here.
				if (asyncResult.status == Office.AsyncResultStatus.Succeeded) {
					// good
				} else {
					// bad
				}
			});
```

**Comment by exextoc** [comment]
We are able to reproduce this issue on our side. Thanks for reporting this issue regarding DisplayDialog API.
We are actively working on this issue as it is high priority. We unfortunately have no timelines to share at this point

**Comment by bx-anil** [comment]
We are affected by this as well.

**Comment by abdulkareemnalband** [comment]
duplicate of #1309

**Comment by exextoc** [comment]
We have pushed our changes to production.
It may take at max 24 hours for the changes to get reflected (cache may have older copies) .

**Comment by cdmdotnet** [comment]
Appears to be working now... would be great if there were clear instructions on how to use a set version of the scripts to avoid these types of issues being inflicted on developers again... but I've raised that in a separate ticket https://github.com/OfficeDev/office-js/issues/1319
