### ISSUE TITLE
Excel: Got 500 error when using online Excel with our private addin

### ISSUE THREAD

**Issue by Lilyliu123** [OfficeDev/office-js#1314]
Got following error when running our private addin using Excel on the web. Works fine with desktop excel application.
___API Error: GeneralException, An internal error has occurred., undefined___

## Context
Our addin basically import the contents from a json file to the excel spreadsheets.
This issue happened when one of the json object has too many sub-objects. I tried to delete some sub-objects, then the issue disappeared.
Our json structure is like following. When I have too many objects under 'Rows' the issue will happen.

	{
          "Loader_Settings": {
		"Rows": 
              [
			{
				"Section_Name": "PO Header",
				"Implemented": true,
				"One_To_One": false
			},
			{
				"Section_Name": "PO Line",
				"Implemented": true,
				"One_To_One": false
			}
		],
		"Name": "Loader Settings"
	}
}
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___Office on the web___
* Host [Excel, Word, PowerPoint, etc.]: __Excel__
* Browser (if using Office on the web): __Edge, Chrome__

## Useful logs

- [ ] Console errors
POST https://auc-excel.officeapps.live.com/x/_vti_bin/EwaInternalWebService.json/ExecuteRichApiRequest?waccluster=AU3 500
RichApi.Error: An internal error has occurred.
    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:293852)
    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:353265)
    at https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:351686

**Comment by lindalu-MSFT** [comment]
Hi, sorry for the delayed response! We're a bit short on resources this week due to vacations. I assigned this to the Excel engineerign team to investigate. Thanks, linda

**Comment by lumine2008** [comment]
It looks to me like your add-in is hitting the [payload size limit](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/common-coding-issues#excel-data-transfer-limits), would you please try to make the json object smaller and try it again?

**Comment by Lilyliu123** [comment]
> It looks to me like your add-in is hitting the [payload size limit](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/common-coding-issues#excel-data-transfer-limits), would you please try to make the json object smaller and try it again?

I did try that, making the json object smaller, and it did work. No issue with the smaller json object.

**Comment by lumine2008** [comment]
This is great, thanks Lily for your confirmation

**Comment by Lilyliu123** [comment]
> This is great, thanks Lily for your confirmation
Thanks Raymond @lumine2008. 
Is this still something you will fix or I should read the [payload size limit](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/common-coding-issues#excel-data-transfer-limits)  and make the changes to my code?

**Comment by lumine2008** [comment]
> > This is great, thanks Lily for your confirmation
> > Thanks Raymond @lumine2008.
> > Is this still something you will fix or I should read the [payload size limit](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/common-coding-issues#excel-data-transfer-limits)  and make the changes to my code?

The payload size limit is the limitation that set by Excel online, we could not make it unlimited, but we are thinking about to provide a more meaningful error code when hitting payload size limit. So yes, you would need to change your code.

**Comment by Lilyliu123** [comment]
@lumine2008 Thanks Raymond. 
I have changed my code following the instructions on the page [payload size limit](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/common-coding-issues#excel-data-transfer-limits) you provided. It worked.

**Comment by Lilyliu123** [comment]
Closed the issue as the issue got fixed with the solution for payload size limit.
