### ISSUE TITLE
Excel: Office App stops registering events when migrated to windows 10 1909 and Office 2002

### ISSUE THREAD

**Issue by nsakar** [OfficeDev/office-js#1315]
## Expected Behavior

Our office app which loads and edits excel tables is not raising events registered events like onSelectedDataChanged event on excel table. It works correctly on windows 1809 and office 2002. We are about to launch the apps in production

## Current Behavior
None of the table changed events are being raised

## Steps to Reproduce, or Live Example
Create an angular 2 based web app and create a web page that loads a table with some data and registers events on the table.
Now edit the data.
Expectation is events will be raised and control returned to the handlers

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop]: ______
* Host [Excel.]: ______
* Office version number: _2002_____
* Operating System: ____windows 10 1909__
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by a114383** [comment]
Platform: PC Desktop
Host: Excel
Office version number: 
Office 365
![image](https://user-images.githubusercontent.com/32073052/90057099-e8b74800-dcad-11ea-9703-cba4aa5ba7f9.png)
Operating System: Windows 10 1909


Our company recently upgraded a few machines to 1909 and have seen the addins loading forever:

![image](https://user-images.githubusercontent.com/32073052/90056825-7e060c80-dcad-11ea-9e7a-3efce4c43deb.png)
