### ISSUE TITLE
Excel: Couldn't initialize an angular application inside Office.onReady() / Office.initialize in slow network

### ISSUE THREAD

**Issue by intellectyxArria** [OfficeDev/office-js#1317]
We have completed development of an Excel addin using the officejs API's. During the process of deploying it to App source we got a feedback that the addin shows blank screen when there is a slower internet connection. When we tried to debug it we got the following error ( when 3G Slow option is set in chrome ).

Uncaught Error: Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.

But the same addin works fine when the internet speed is decent. Below is the piece of code that we have used to bootstrap the angular application.

Office.onReady().then(function() {
  platformBrowserDynamic().bootstrapModule(AppModule).catch(err => console.error(err));
});
We are still not sure what went wrong but when we comment the single line inside the Office.onReady function and add consoles. It dosen't throw any error's ( I know this is irrelavent but still an observation which we made ). It would be great if someone could help us. Thanks in advance.

**Comment by sarea** [comment]
Got this error before, really annoying how this API works, in the documentation [example](https://github.com/OfficeDev/Word-Add-in-Angular2-StyleChecker/blob/master/app/main.ts#L21) they still use the old way.
However, we do use both `initialize` and `onReady` but we check Office first:
```
if (Office !== undefined) {
  // see: https://github.com/OfficeDev/office-js/issues/246#issuecomment-437260860
  Office.initialize = function () {
    // Does not throw. ever. see: https://github.com/OfficeDev/office-js/issues/246#issuecomment-438342679
    Office.onReady()
      .then((info: { host: Office.HostType; platform: Office.PlatformType }) => {
        return bootStrapAngular();
      })
      .catch(reason => {
        console.warn('Angular not bootstrapped. reason: \n');
        console.log(reason);
      });
  };
} else {
  console.log('Bootstrapping Angular, without OfficeJS');
  bootStrapAngular();
}
```
Another tip to get zone.js is to have it once you bootstrap the app:
```
function bootStrapAngular() {
  const compilerBootstrapOptions: CompilerOptions & BootstrapOptions = {
    preserveWhitespaces: false,
    ngZone: 'zone.js',
  };

  return platformBrowserDynamic()
    .bootstrapModule(AppModule, compilerBootstrapOptions)
    .catch(error => {
      console.log('Error bootstrapping OWA angular app: ', error);
    });
}
``` 
where `compilerBootstrapOptions` is something you can get from here
```
import { BootstrapOptions } from '@angular/core/esm2015/src/application_ref';
```

**Comment by intellectyxArria** [comment]
Thanks alot for the suggestion @sarea. We still get the same error message in slow network

**Comment by intellectyxArria** [comment]
I tried creating a new application following the steps mentioned in https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-angular. The new application also has the same issue . I did this because I thought the size of the application might be the problem. It seems that this is related to the office.intialize and office.onReady methods

**Comment by alison-mk** [comment]
Hi @intellectyxArria, thank you for submitting this network speed issue! I've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by intellectyxArria** [comment]
Hello @alison-mk some of my co-workers  found out that the application size had significant impact on loading the extension inside excel after adding the following line of code in build script we were able to fix this.

`ng build --base-href=/excel/ --prod=true --aot=true --buildOptimizer=true --extractCss=true --extractLicenses=true --optimization=true --output-hashing=all --sourceMap=true`

This piece of code optimizes the application size. Hope this helps other people facing the same issue. 

Thanks & Regards,

**Comment by alison-mk** [comment]
Closing this issue as it is resolved. Thank you for sharing your solution!

**Comment by ic3guy** [comment]
I just want to add that I'm using Angular 11 for an Excel Office.js Add-In and I'm getting the same error on slow connections.

The solution above written by @intellectyxArria is most likely correct. That the bundle size is too big. This really shouldn't be a problem Microsoft... 

I do not like one liners so here is a little bit of an explanation of the options.

--prod specifies using the "production" configuration. Without seeing @intellectyxArria angular.json, there could be settings that modify how the build is being done. Let's assume it is the defaults generated by ng new.

Here they are:

    "optimization": true,
    "outputHashing": "all",
    "sourceMap": false,
    "namedChunks": false,
    "extractLicenses": true,
    "vendorChunk": false,
    "buildOptimizer": true,
    "budgets": [
    {
        "type": "initial",
        "maximumWarning": "2mb",
        "maximumError": "5mb"
    },
    {
        "type": "anyComponentStyle",
        "maximumWarning": "6kb",
        "maximumError": "10kb"
    }

If we assume the default, then --optimization=true, --extractLicenses=true, --output-hasing=all are not required.

In Angular 11, AOT is on by default. See  "aot": true in the build architect settings of angular.json so --aot=true is not required either.

--extractCss has been deprecated and it defaults to true

--sourceMap=true will make your bundle size LARGER not SMALLER

In Angular 11 then all you need to minimize the bundle size is `ng build --prod` which is shorthand for `ng build --configuration=production`

It would be nice if we could get some info about what the max bundle size should be then we could edit the maximumWarning/maximumError to match that..

**Comment by alison-mk** [comment]
Thanks for contributing, @ic3guy. 

@lumine2008 Can you take a look at the most recent comment on this issue, and provide information about the max bundle size?
