### ISSUE TITLE
Excel: Custom Document Properties not persisted in Excel Online

### ISSUE THREAD

**Issue by thulium3** [OfficeDev/office-js#1318]
I am using Excel Online Version 16.0.13129.31875.
I am adding document properties to my document and later read them again.

Following pattern was observed:
When working locally in Excel on Mac I can set properties, close document, reopen it and read them again.
Also adding properties in local Excel and reading them later in Excel Online does work.

But when I add the properties in Excel Online I can only read them as long as my session is active. When I close the file or reopen it the properties are gone. Also I cannot add properties in Excel Online and close the file and read them later in local Excel.

In the API reference these settings are also flagged as read-only: https://docs.microsoft.com/en-us/javascript/api/excel/excel.documentproperties?view=excel-js-preview#custom

It seems like read-only is not valid for local Excel app. Would be great if you could remove the read-only flag and let it behave the same locally and Online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6b16473-fffd-9ebf-ee91-2f0012a496ee
* Version Independent ID: 3f147de9-0138-9104-f462-c6f4097b1167
* Content: [Work with workbooks using the Excel JavaScript API - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-workbooks#add-custom-xml-data-to-the-workbook)
* Content Source: [docs/excel/excel-add-ins-workbooks.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-workbooks.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lumine2008** [comment]
Thanks @thulium3 for reporting this issue to us, it looks like a bug, I created a bug(4367885) to track this issue. 
However, we tried online PROD and find 100% repro when has worksheet protected, however, it is not repro a non-protection sheet in the workbook.
would you please share with us a) your sample workbook and b) your repro script. we would like to validate our side. thanks

**Comment by thulium3** [comment]
Hi @lumine2008 
unfortunately I cannot share the workbook and code as it is internal stuff from my work. 
I used a code snippet from help pages to set the custom properties. Now I changed it to use field 'subject' instead. This works fine Online and also on local Excel:
`await Excel.run(async context => {
      let docProperties = context.workbook.properties;
      docProperties.subject = JSON.stringify(myJSON);
      await context.sync();
    })`

**Comment by lumine2008** [comment]
This issue was fix, would you please verify? thanks

**Comment by thulium3** [comment]
our code has changed since then, do not use document properties anymore. But I keep in mind that this should work now. 

Thanks
Mark
