### ISSUE TITLE
CDN versions

### ISSUE THREAD

**Issue by cdmdotnet** [OfficeDev/office-js#1319]
Are the hosted files versioned and thus selectable?

I ask as part of any good software practice is to know what you have QA'ed and deployed.

If a remotely hosted core file to an developers application, in my case  `//appsforoffice.microsoft.com/lib/1/hosted/office.js` is a core file, and and new deployment, which is out of my control, it would appear to fundamentally change core parts of said developers application without being tested.

I ask as I and several other developers have this exact problem today. A deployed changed in the core libraries has introduced a bug without a deployment on our part. See https://github.com/OfficeDev/office-js/issues/1309 and https://github.com/OfficeDev/office-js/issues/1313. 

So, to my question, are there version (in the same way JQuery is versioned see //ajax.aspnetcdn.com/ajax/jQuery/jquery-1.9.1.min.js) so developers can have confidence in the stability of the SDKs and libraries we're using from AppSource?
I've read the **Best practices** at https://github.com/OfficeDev/office-js and we're not allowed to package our own version - which I fully understand for security reasons, but the statement 

```Add-ins that are published to AppSource must use the Office.js CDN. ```

Means we need versioned releases otherwise our submissions get rejected when our AddOns fail because of a flaw introduced by the Office development team and not the developer.

And while I've read `Accessing the NPM files via a CDN`, the instructions on versioned usage refer to https://unpkg.com which isn't made clear if that meets the requirements of `must use the Office.js CDN` and is noted as `provides best-effort (no uptime guarantees)` so it doesn't seem like it.

So... Are the hosted files versioned and thus selectable on the Office.js CDN?

**Comment by alison-mk** [comment]
Hi @cdmdotnet, thank you for using Office.js. I don't have an answer to this question, but I'd really like to get one for you, so I'll loop in a couple other team members. @nokafor, @lliu113, or @AbidRahman-MSFT, can you help answer this question about the Office.js CDN versioning process? 

Thanks!
Alison

**Comment by sumurthy** [comment]
Office.js CDN doesn't offer versions. The APIs are expected to work on all future Office versions. Unless communicated explicitly via docs, IntelliSence, etc. ahead of time, the API behavior doesn't change. Yes, sometimes we do see bugs in the library, which we act on as soon as we discover. For testing purpose, one can always use http://appsforoffice.microsoft.com/lib/beta/hosted/office.js version to get a view of upcoming changes.
The store policy is to require official CDN version. If you are distributing via. centralized deployment, you could use the NPM version.

**Comment by ElizabethSamuel-MSFT** [comment]
@cdmdotnet Seems like this was answered so I'll close this. Do create a new issue or comment on this issue and we'll reactivate.

Thanks.
