### ISSUE TITLE
[Outlook] Office.context.mailbox.item.body.getAsync get html exception

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1321]
When I input some content use ‘automatically generate serial number’. 
Then use 'Office.context.mailbox.item.body.getAsync' trying get html body. 
The index number will disappear.
![image](https://user-images.githubusercontent.com/15980696/89645162-d32bd200-d8eb-11ea-8918-a12b09f63e85.png)
And this problem only happen on Mac outlook client.

## Expected Behavior
index number should be reserve.

## Current Behavior
only saved content without index number

## Steps to Reproduce, or Live Example
1. in put some wording like:
 1. testtest
 2. testtest22
 3. 
 The index number should be automatically generated.

2. Use 'Office.context.mailbox.item.body.getAsync' trying get html body. 
3. set the 'html' body back to meeting body again

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.41 (20080203)
* Operating System: Mac
* Browser (if using Office on the web): ______

**Comment by alison-mk** [comment]
Hi @SWei1234, thank you for submitting this issue! I've assigned it to the Mac Outlook engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by SWei1234** [comment]
@alison-mk 
Thanks, really appreciate it. 
And I met another problem but seems is the same root cause :
When I set a table with html format to body. An extra table html code will be generated. 
If necessary i can provide code and recording. If possible have an online meeting will be perfect!
Thanks

**Comment by SWei1234** [comment]
Hi @alison-mk 
Just want to confirm, any update?
Thanks

**Comment by alison-mk** [comment]
Hi @SWei1234, I'm sorry for the delay! @macOutlookExtensibility or @AnjanaValsan, can you take a look at this issue and help provide our customer with an answer? Thanks!

**Comment by SWei1234** [comment]
Hi @macOutlookExtensibility and @AnjanaValsan
Do you need any information or replicate steps?
Thanks

**Comment by AnjanaValsan** [comment]
@exextoc for follow up

**Comment by exextoc** [comment]
To reproduce this issue from our side we will need the Code Snippet which is causing this issue,Please share Code Snippet with us.

**Comment by SWei1234** [comment]
Hi @exextoc 
There is no need to write some code, Only need some steps then call 'Office.context.mailbox.item.body.getAsync' . And there is another problem on this believe is the same root cause.
I will record steps and show you. 
And if we can have a meeting will be faster and easier.
Thanks

**Comment by exextoc** [comment]
Recording for the repro will be helpful for investigation. Please share that.

**Comment by exextoc** [comment]
Thanks for Reporting this issue.It has been put on our backlog.We unfortunately have no timeline to share at this point

**Comment by SWei1234** [comment]
Hi @exextoc 
    We have another exception phenomenon about this api. 
    After we save an html in body and update it. Another will be generated there above the table. I have mentioned this in last shooting meeting on teams. 
   Can you please fix this when you have ETA?

    Thanks
