### ISSUE TITLE
Word: range.select() doesn't work in office.js Add-in with Word 2016

### ISSUE THREAD

**Issue by josiasmueller** [OfficeDev/office-js#1323]
I have an issue with my Word-office.js-Add-in, implemented with Vue.js.

When I call range.select() in my Win10 & Word 2016 setup the selection isn't changed. As far as I can tell nothing happens, not even an error is thrown. According to the documentation that function is in API set WordApi 1.1 so should be a supported function for Word 2016, right?

My word version: 16.0.4266.1001. This can be reproduced using the code in the example given here: https://docs.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview#select-selectionmode-

This code works like a charm with Office 2019 and on the web (even in ie11). Could it be that range.select() is WordApi 1.3 anyways? If that's the case, any idea how I could select a specific part of the word document using WordApi 1.1 functionality otherwise?

## Expected Behavior
When calling range.select() the range get's selected in the Word 2016 client.

## Current Behavior
No selection change.

## Steps to Reproduce, or Live Example
Implement the snipped provided below and test it in a Word 2016 client.
https://docs.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview#select-selectionmode-

## Context
I'm trying to select a certain text passage so the user knows what text passage is referred to in the add-in.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Word 2016, 16.0.4266.1001
* Operating System: Win10

**Comment by alison-mk** [comment]
Hi @josiasmueller, thank you for submitting this issue! I've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by genderapp** [comment]
@weshi If we can provide more information, please let us know.

This issue is very important for us.

**Comment by josiasmueller** [comment]
Did you manage to reproduce the issue?

**Comment by genderapp** [comment]
@alison-mk Could you maybe stress this issue again with @weshi? As mentioned. This ticket  is very important for us as Microsoft MPN Partner.

**Comment by alison-mk** [comment]
Hi @genderapp and @josiasmueller, I'm sorry for the delay here! I'll reach out internally to @weshi and @JuaneloJuanelo to see if I can help get you an answer.

**Comment by JuaneloJuanelo** [comment]
That method should absolutely work on that build. @genderapp  what are you doing before selecting the range? how are you getting the range you want to scroll to? just to clarify are you using this snippet?
```

Word.run(function (context) {

    // Queue a command to get the current selection and then
    // create a proxy range object with the results.
    var range = context.document.getSelection();

    // Queue a command to insert HTML in to the beginning of the range.
    range.insertHtml('<strong>This is text inserted with range.insertHtml()</strong>', Word.InsertLocation.start);

    // Queue a command to select the HTML that was inserted.
    range.select();

    // Synchronize the document state by executing the queued commands,
    // and return a promise to indicate task completion.
    return context.sync().then(function () {
        console.log('Selected the range.');
    });
})
.catch(function (error) {
    console.log('Error: ' + JSON.stringify(error));
    if (error instanceof OfficeExtension.Error) {
        console.log('Debug info: ' + JSON.stringify(error.debugInfo));
    }
});
```

is the html inserted?

also what happens when you call

a.  console.log(Office.context.requirements.isSetSupported("WordApi",1.1));
b.  console.log(Office.context.requirements.isSetSupported("WordApi",1.2));

**Comment by JuaneloJuanelo** [comment]
adding @hjkim71  as he actually owns Desktop.

**Comment by josiasmueller** [comment]
@JuaneloJuanelo Yes, that's the snippet. 

a. console.log(Office.context.requirements.isSetSupported("WordApi",1.1));
b. console.log(Office.context.requirements.isSetSupported("WordApi",1.2)); 
return both 'true'.

I now found a workaround that works with my Word 2016 build, maybe you want to update the documentation?

```

Word.run(function (context) {

    // Queue a command to get the current selection and then
    // create a proxy range object with the results.
    var range = context.document.getSelection();

    // Queue a command to insert HTML in to the beginning of the range.
    range.insertHtml('<strong>This is text inserted with range.insertHtml()</strong>', Word.InsertLocation.start);

    // Synchronize the document state by executing the queued commands,
    // and return a promise to indicate task completion.
    return context.sync().then(function () {
        // Queue a command to select the HTML that was inserted.
        range.select();
        console.log('Selected the range.');
    });
})
.catch(function (error) {
    console.log('Error: ' + JSON.stringify(error));
    if (error instanceof OfficeExtension.Error) {
        console.log('Debug info: ' + JSON.stringify(error.debugInfo));
    }
});
```

For me, you can close this issue.
Thanks for your time.
