### ISSUE TITLE
[Outlook] Can't set start/end time of recurring meeting

### ISSUE THREAD

**Issue by jurisjansons** [OfficeDev/office-js#1327]
For normal events everything works fine, when creating recurring meeting `start.setAsync()` and `end.setAsync()` fails.

## Expected Behavior
Time is set for recurring meeting

## Current Behavior
Internal Error

## Steps to Reproduce, or Live Example
Open new meeting,
Create any recurrence pattern,
Use `Office.context.mailbox.item.start.setAsync()` or `Office.context.mailbox.item.end.setAsync()`
Result to callback will be with `5001` error 

## Context
I am trying to change end time of meeting, but it doesnt work for meeting with recurrence. Same code works fine in Outlook Web, even for recurring meetings.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 1910 (Build 12130.20272)
* Operating System: Windows

## Useful logs
`
{
   error: {
      code: 5001,
      message: "An internal error has occurred.",
      name: "Internal Error",
   },
   status: "failed",
   value: undefined
}
`

**Comment by exextoc** [comment]
This is by deisgn in win32. You'll need to use the recurrence office js [recurrence](https://docs.microsoft.com/en-us/javascript/api/outlook/office.recurrence?view=outlook-js-1.8) API to be able to make changes to the recurring meeting.

**Comment by jurisjansons** [comment]
Do I need to change times using `Office.context.mailbox.item.recurrence.setAsync()` ? I see that there is property `seriesTime` in documentation and my IntelliSense is giving me this property with all its methods, but when I try to access it `Office.context.mailbox.item.recurrence.seriesTime` is `undefined`. I have set API Mailbox 1.8 in my manfiest.

This line: `Office.context.mailbox.item.recurrence.seriesTime.setDuration(60);`
Throws this error: `Unable to get property 'setDuration' of undefined or null reference`

**Comment by exextoc** [comment]
That is correct. You'll first need to do a getAsync on the item.recurrence to get the recurrence Object, then you can access the seriesTime object from the recurrence, set it's duration/startTime/etc and the do a recurrence.setAsync to reflect the changes. As an example, the following sample will get the recurrence and change the duration of the recurring meeting to 2 hours.

Office.context.mailbox.item.recurrence.getAsync(callback);

function callback(asyncResult) { 
   var recurrencePattern = asyncResult.value; 
   recurrencePattern.seriesTime.setDuration(120); 
   Office.context.mailbox.item.recurrence.setAsync(recurrencePattern, (asyncResult) => { 
      if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) { 
          showMessage("failed"); 
  	      return; 
	  } 
	  showMessage("success"); 
   }); 
}

**Comment by jurisjansons** [comment]
Thank you for your time. This worked!
