### ISSUE TITLE
Excel: binding.addRowsAsync(...) not working as expected

### ISSUE THREAD

**Issue by pelis** [OfficeDev/office-js#133]
There seems to be a bug when trying to add rows to a table under the following condition:
- Table has rows
- The table that the binding refers to is on a sheet that is not active (for example 'sheet 1')
- active sheet, for exemple, is 'myActiveSheet'
- the following code returns success, however, rows are NOT appended:
         binding.addRowsAsync(rowsToAppend, function (result) {
         if (result.status === Office.AsyncResultStatus.Succeeded) {// this is true, however, no rows added} 

The code works when the sheet containing the table is active ('sheet 1' in this example)

Environment
- Task-Pane App, clicking a button to execute above described code
- Excel 2016 64 Bit, Version 1804, Build 9226.2126
- Office.js - not sure how to find out the exact release, however, Office.context.requirements.isSetSupported() tells me 1.6 is supported.

**Comment by pelis** [comment]
I have done a little more testing...
It seems that there are more problems when manipulating table data and formats when the table binding is not in the currently active sheet, such as:
- showTotals formatting is not working properly
- when total Row is displayed, the table gets corrupted

**Comment by JuaneloJuanelo** [comment]
there are 2 issues reported here: 

1. First issue is a non repro. i can add items to the binding on non-active sheets. 
2. Second issue **does** repro and its a bug: if a total row exists get corrupted upon insertion. 

There is an alternative you can try, if you use the Excel specific JS API (aka excel.js)  you can do this and it will work on active and non-active sheets.


var appendRows = [["4"], ["20"]];

async function AppendRows() {
    await Excel.run(async (context) => {
        context.workbook.bindings.getItem("BindingID").getTable().rows.add(null, appendRows);
        await context.sync();
    });
}

please find a [script lab ](http://aka.ms/scriptlab)snippet [here](https://gist.github.com/JuaneloJuanelo/f5310849d38f519516491d6f51990633). 

btw  there a reason why you are not using the Excel specific API? i strongly recommend you to move to it.

**Comment by JuaneloJuanelo** [comment]
bug is tracked with
2463266

**Comment by pelis** [comment]
Thanks for your reply...
I am using the Excel Rich API - however, have not yet migrated everything.
In some cases I have to stick with the old one: I am using evnts (Cell data change events), it seems that events are not yet part of the Rich API?
Cheers - Peter

**Comment by JuaneloJuanelo** [comment]
@pelis  absolutely we have the events on the Excel specific API! check out our docs please! many events were shipped as part of our 1.7 release!

**Comment by pelis** [comment]
Thanks Juanelo,
I have briefly looked at the events - as you have mentioned, seems to be brand new.
Fortunately the new API gets more and more complete and thus usable.

Since your response is the first response that I receive which is really helpful I am adding a pointer to another issue that sits there for 2 years, just in case you are interested... :-)

https://social.technet.microsoft.com/Forums/office/en-US/b0e027d9-ca29-4d2b-9007-01d59dd2ca2e/this-addin-is-no-longer-available-from-the-following-server-?forum=Office2016ITPro.

Thanks again - really helpful

**Comment by JuaneloJuanelo** [comment]
Provided workaround and also we have a bug tracking this issue.
