### ISSUE TITLE
[Outlook] Can't save properties in some shared calendar group

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1333]
When we tried save some data to properties in calendar under  'People's calendars' .
Save properties will never be success.
Is this by design? 
We tried save properties in calendar owner's calendar, it works fine.And this only happened on browser.[office online]

## Expected Behavior
Can save properties success or it's by design.

## Current Behavior
Can't save any data to property.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: outlook
* Office version number: online
* Operating System: Windows
* Browser (if using Office on the web): Chrome

Any idea?

**Comment by exextoc** [comment]
Are you trying to save any custom property? Do you have permission to do so? We are trying to understand the exact scenario in order to repro the issue if you can share manifest or code-snippet, it will be helpful.

**Comment by SWei1234** [comment]
Hi @exextoc 
Are you trying to save any custom property? --- Yes
Do you have permission to do so? --- Yes, We set both read and write permission in manifest file, like below:
![image](https://user-images.githubusercontent.com/15980696/90730707-21cd6900-e2fb-11ea-9700-1a1af07f0b84.png)
And I think the pic below will be helpful:
![image](https://user-images.githubusercontent.com/15980696/90730840-61945080-e2fb-11ea-85ad-19b24611f2c6.png)

**Comment by exextoc** [comment]
Can you please share the manifest file for the repro purpose?

**Comment by SWei1234** [comment]
@exextoc 
You can get the manifest from zoom in store.

**Comment by SWei1234** [comment]
@exextoc 
Why you need the whole manifest file? I can show any tag you want to know in that file or send it to your email. 
But share the manifest in public, I don't think this is a good idea.
You can try below steps if you can't replicate this problem:
1. open a new meeting,then use add-in and save properties
2. click 'save' button save meetin.
3. open saved meeting in step 2, and try read properties.

**Comment by exextoc** [comment]
@SWei1234 We are unable to reproduce the issue locally, it will be helpful if you can share a screen recording or screenshots explaining the flow. 
We understand that you may not be able to share the manifest here, but is it possible to share a stripped-down version of the add-in which we can use for reproducing the issue?

**Comment by SWei1234** [comment]
Hi @exextoc 
Sure, you can use zoom add-in to reproduce this problem, it will save properties after schedule a meeting.
And I'll attach recording later.
Thanks for understanding.

**Comment by SWei1234** [comment]
@exextoc 
Here is my recording:
https://success.zoom.us/rec/share/1McoDpXKxExLHM_N53rVQZEHEcfBT6a81yMX-PVbzUh0NrJJ7HiVOjJKxxPAYuPB Passcode: 1@!MSv5N 
Related test code:
//write something
Office.context.mailbox.item.loadCustomPropertiesAsync(function (result){
                    result.value.set("test","success");
                    result.value.saveAsync(function () {
                    return true;
                });
                });

//read something
Office.context.mailbox.item.loadCustomPropertiesAsync(function (result){
                    console.log(result.value);
                });
If you still can't reproduce this problem , can we have a trouble shooting meeting?
Thanks

**Comment by exextoc** [comment]
@SWei1234 Thanks for sharing the recording, we will try to reproduce the issue.
If we cannot reproduce the issue, we will schedule a meeting.

**Comment by exextoc** [comment]
@SWei1234 We saw the repro and still not able to repro the same at our end. Can you share OWA build version in which this was reproducible?

**Comment by SWei1234** [comment]
@exextoc 
Sure, but I'm using Office 365 online not in an on Prem environment...
I have send you my email or maybe we can talk this on a trouble shooting meeting? 
I think this will be faster.
Thanks

**Comment by exextoc** [comment]
@SWei1234 Have you emailed it here- admin@a830edad9050849405E20081103.onmicrosoft.com? We haven't received your emailId.

**Comment by SWei1234** [comment]
@exextoc Yes, I have send both User2@ContosoEventAddin.onmicrosoft.com and admin@a830edad9050849405E20081103.onmicrosoft.com now.
Please check the email later.

**Comment by exextoc** [comment]
Thank you @SWei1234. We have received the email now. We will set up meeting with you.
