### ISSUE TITLE
OfficeJS Excel SouceLocation behind auth proxy loading forever after upgrading to Windows 1909

### ISSUE THREAD

**Issue by a114383** [OfficeDev/office-js#1334]
I have an application hosted on a cloud provider which sits behind a reverse proxy (also hosted on the cloud provider) responsible for organizational ADFS.

After adding it to our trust center we've used a `ContentApp` type OfficeJS Excel plugin without problem:
```
<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp
          xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
          xsi:type="ContentApp">
  <Id>XXXXX</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>App</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="App Content" />
  <Description DefaultValue="App Description"/>
  <Host Name="Workbook" />
  <DefaultSettings>
    <SourceLocation DefaultValue="https://app.com" />
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>
</OfficeApp>
```

After upgrading to Windows 1909 we've noticed some users experiencing the addins loading forever:
![image](https://user-images.githubusercontent.com/32073052/90567802-bbb8d880-e178-11ea-9d64-ea588ea6dd51.png)

## Expected Behavior
The content app pane to display the expected HTML page.

## Current Behavior
See above

## Steps to Reproduce, or Live Example
I'm not sure this is possible due to the organizational design we have in place.  I'll gladly take any ideas on how to help re-produce this.

## Context
This renders a button which uses iframes to authenticate to the above mentioned service for retrieving API responses.  VBA doesn't seem to follow the redirects necessary for authentication.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1909
* Operating System: Windows
* Browser (if using Office on the web): Default IE

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lumine2008** [comment]
@nkkinariwala , this issue doesnt look like in Excel JS API scope, it seems related to manifest and webview. would you please help reassign it?

**Comment by a114383** [comment]
Thanks turns out the redirect to ADFS which to an internal url needed to be added to the `<AppDomains>` element.  Still unclear why this wasn't needed before 1909 but regardless the problem seems to be solved.
