### ISSUE TITLE
Full CORS not working for custom functions in shared runtime

### ISSUE THREAD

**Issue by georgechr** [OfficeDev/office-js#1335]
We have a custom functions add-in which makes API requests. The request is made to a same-domain URL and is always re-directed  (based on IP) to a sub-domain URL (e.g. request is made to api.mydomain.com and then redirected to api-a.mydomain.com).

The request carries some basic headers: authorization: bearer..., content-type: application/json and accept: application/json.
This didn't use to work as custom functions' runtime didn't support full CORS but then the shared JS runtime feature was released which was supposed to address this issue: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime

I'm following all the steps from the above link but I am still getting the same error:
"Url was redirected. The request does not meet conditions for security policy of SOP (same-origin policy) or simple CORS (cross-origin resource sharing)."

Other apps connecting to the API are redirected just fine.

## Expected Behavior
The request is redirected or at least we get a redirect status to allow us to follow the redirect.

## Current Behavior
CORS error

**Comment by RuoyingLiang** [comment]
Could you try to add  Access-Control-Allow-Origin  to response header to enable Cors and let us know if it can solve the problem?

**Comment by georgechr** [comment]
This is happening in development mode where I have a local webback dev server with a dev proxy. It should just redirect.

**Comment by georgechr** [comment]
@RuoyingLiang in addition to my comment above it would be worth mentioning that there is code accessing the API inside the taskpane and that gets redirected just fine. And the Runtime element inside manifest.xml is referencing the same resource ID for both taskpane and functions.

Is there something I am missing here?

**Comment by georgechr** [comment]
Hello,

Is there an update on this? It's hindering further development of an enterprise add-in we would like to roll out.

Thanks

**Comment by georgechr** [comment]
Hello @RuoyingLiang 

Is there a workaround for this? We've had this issue for a long time now and it's impeding releasing enterprise applications to our clients.

Thanks

**Comment by grangeryy** [comment]
dup with 1383: https://github.com/OfficeDev/office-js/issues/1383
