### ISSUE TITLE
displayDialogAsync dialog not returning response in Shared runtime with ExecuteAction Function

### ISSUE THREAD

**Issue by Murugananths** [OfficeDev/office-js#1336]
## Expected Behavior

We are using displayDialogAsync dialog for Login authentication in Excel add-in using OfficeJS and below are the expectations.

1) We are using displayDialogAsync dialog box in shared runtime (to achieve enable/disable of ribbon commands) with ExecuteFunction Action from manifest file.

2) As a user if clicks Login ribbon command in Excel, dialog is getting opened with our on-premise url constructed with required redirect url so that it can return successful response token on redirect url.

3) As a user once entered credentials and submit in dialog then it should generate with token and return to  redirect url (i.e /taskpane.html?id_token="*****" )

## Current Behavior

1) As a user once entered credentials and submit in dialog then it is generated with token in query string of dialog box with redirect url (i.e /taskpane.html?id_token="*****" ) but not returning to redirect url (taskpane.html) and the page is idle.

2) The same behavior was working when it was having non-shared runtime with ShowTaskPane Action in Manifest.

## Steps to Reproduce, or Live Example

* Link to live example: https://github.com/Murugananths/displayDialogAsync

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by Murugananths** [comment]
Hi team, 

Have you had a chance look at this issue?

**Comment by lumine2008** [comment]
it seems related to UX areas. as I am responsible for Excel Rich API, so Looping @lliu113 who is responsible for UX Dialog. @lliu113 , Would you please take care of this issue or redirect to right person? thanks

**Comment by Murugananths** [comment]
Hi team, 

Can you please forward it to Heidi Munson who is already looking into this in separate mail chain....

**Comment by Murugananths** [comment]
Hi team, 
Are you able to reproduce the issue?

**Comment by lliu113** [comment]
@Murugananths - apologies for the very late response to this. Is this issue still reproing? Are you seeing this on both desktop and online? 

Just so I understand, the dialog was correctly passing the token and redirectly correctly using the legacy runtime but this is not working with the shared runtime?

**Comment by lliu113** [comment]
@Murugananths - I'm going to go ahead and close this issue for now. Please reactivate if you're still having problems or if you have any additional questions. Thanks!
