### ISSUE TITLE
Core Properties open xml package part is missing

### ISSUE THREAD

**Issue by serjant** [OfficeDev/office-js#1337]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am setting the body as OOXML, then extract the content using **context.document.body.getOoxml()**  and it turns out that the coreProperties contains dummy data instead of my actual real data. 
## Expected Behavior
The core properties open xml package part should persist during document editing and can be retrieved inside the raw OOXML value or via 
```js
Office.context.document.customXmlParts("http://schemas.openxmlformats.org/package/2006/metadata/core-properties")
```

## Steps to Reproduce, or Live Example

1. Add relation of core.xml which will contain the core properties definitions

```xml
<pkg:part pkg:contentType='application/vnd.openxmlformats-package.relationships+xml'
            pkg:name='/_rels/.rels'>
    <pkg:xmlData>
      <Relationships xmlns='http://schemas.openxmlformats.org/package/2006/relationships'>
        <Relationship Id='rId3'
                      Target='docProps/app.xml'
                      Type='http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties'/>
        <Relationship Id='rId2'
                      Target='docProps/core.xml'
                      Type='http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties'/>
        <Relationship Id='rId1'
                      Target='word/document.xml'
                 Type='http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument'/>
      </Relationships>
    </pkg:xmlData>
  </pkg:part>
```

2. Inside the OOXML package set the predefined core properties in the core properties open xml package part:

```xml
<pkg:part pkg:contentType='application/vnd.openxmlformats-package.core-properties+xml'
          pkg:name='/docProps/core.xml'>
    <pkg:xmlData>
        <cp:coreProperties
                xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"
                xmlns:dc="http://purl.org/dc/elements/1.1/"
                xmlns:dcterms="http://purl.org/dc/terms/"
                xmlns:dcmitype="http://purl.org/dc/dcmitype/"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <dc:title>Core Document Properties</dc:title>
            <dc:subject>Core document properties</dc:subject>
            <dc:creator>David Baum</dc:creator>
            <cp:keywords>word; open xml; dublin core; microsoft office</cp:keywords>
            <dc:description>
                Core Document Properties Description
            </dc:description>
            <cp:lastModifiedBy>David Baum</cp:lastModifiedBy>
            <cp:revision>2</cp:revision>
            <dcterms:created xsi:type="dcterms:W3CDTF">2018-10-06T06:03:36Z</dcterms:created>
            <dcterms:modified xsi:type="dcterms:W3CDTF">2018-10-15T06:09:18Z</dcterms:modified>
            <cp:category>analysis</cp:category>
        </cp:coreProperties>
    </pkg:xmlData>
</pkg:part>
```

3. Construct the OOXML ([the file example](https://github.com/OfficeDev/office-js/files/2553626/ooxml.txt), initialize the Office in the add-in, and set the content:

```js
Word.run(async (context) => {
    let body = context.document.body;
    body.clear();
    body.insertOoxml(OOXML_VALUE, Word.InsertLocation.replace);
    await context.sync();
});
```

4. Try to load the OOXML back and print the raw value in the console:

```js
let documentBody = context.document.body;
let ooxml = documentBody.getOoxml();
await context.sync();
```

Examine the output - it does not contain the package part of type application/vnd.openxmlformats-package.core-properties+xml

5. Try to load the package part using the another API method Office.context.document.customXmlParts.getByNamespaceAsync("http://schemas.openxmlformats.org/package/2006/metadata/core-properties",  <Callback>) and output the subject node value from the core properties part:

```js
let xmlParts = Office.context.document.customXmlParts;
xmlParts.getByNamespaceAsync("http://schemas.openxmlformats.org/package/2006/metadata/core-properties", function (eventArgs) {
        let xmlParts = eventArgs.value;
      
        if(xmlParts.length > 0) {
            xmlParts[0].getNodesAsync('*/*', function (nodeResults) {
                for (let i = 0; i < nodeResults.value.length; i++) {
                    let node = nodeResults.value[i];
                    if(node.baseName == 'subject') {
                        console.log(node.nodeType + " " + node);

                        node.getTextAsync({asyncContext: "StateNormal"}, function (getTextAsyncResult) {
                            console.log("Text of the subject element = " + getTextAsyncResult.value);
                        });
                        break;
                    }
                }
            });
        }
    }
)
```

It turns out that nor the subject value is set neither the value is equal to one from the initial OOXML. The same thing with author and dates tag values. Why should Office JS API set its own data which does not make any sense?
 
## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]:  iMac Pro (2017)
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.41 (20072901)
* Operating System: MacOS Catalina 10.15.5

**Comment by serjant** [comment]
That is it? Well done. Well, as usually you suck by closing the tickets without any interaction.

**Comment by wangyun-microsoft** [comment]
Hi @serjant , 

Our Bot closed this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. 

I do understand your frustration here. Is this issue still a problem for you?
