### ISSUE TITLE
could outlook add-in support login to browser and then launch back to outlook add-in(which will callback some message from browser)

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#1338]
as we know, office build-in browser has some limitation for example: security.

when we call **Office.context.ui.displayDialogAsync**, we will open a new tab in build-in browser. but there are some limitation for this dialog. 

I have a login sso case for explain the limitation:
right now, when the add-in want to login to sso, we need call **Office.context.ui.displayDialogAsync**, and then location.href to sso page(for example: azure ad). when we use is build-in browser to login to sso, it may meet some problem for conditional access policy requirement. and the sso login failed.(which is worked fine, in native browser: for example: chrome or IE).

if the outlook add-in support communicate with native browser(for example: chrome), our add-in just need open the sso login link from outlook add-in to chrome. after we login in at chrome, and then launch back to outlook add-in, and contain the callback message(for example: login token), our add-in can login success.

As i have researched, when we try to use gmail to login to outlook client, the outlook client will open a new build-in browser, and then navigation to chrome, after login from chrome it will launch back to outlook(which i notice the launch back link is like: `com.microsoft.office.outlook:/mac/google/oauth2redirect?state=A4D4asdf-4534xxxxxx7DBE2767&code=4/asdfasdxzxzz-9Ro&scope=email%20profile%20https://www.googleapis.com/auth/userinfo.profile%20https://www.googleapis.com/auth/userinfo.email%20https://mail.google.com/%20https://www.googleapis.com/auth/calendar%20https://www.googleapis.com/auth/contacts%20https://www.googleapis.com/auth/drive%20https://www.googleapis.com/auth/user.emails.read%20openid&authuser=1&hd=zasds.com&prompt=consent
`) and login to gmail at outlook client success.

Since the Outlook client supports gmail's interworking login mechanism with the native browser, does it have the same support for Add-in?

I think this is a very good and necessary feature support!

**Comment by exextoc** [comment]
We have documentation for enabling single sign-on for add-ins (link below). Please take a look:
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins

**Comment by hello-chenchen** [comment]
hi @exextoc , thanks for the reply.
yeah, the oauth2.0 is a perfect solution to sync sso login token.  but i still want to know is it possible for support login to native browser and then launch back to outlook add-in? cause i think the second method is more flexibility and wider applicability.
thanks

**Comment by exextoc** [comment]
Currently, this behavior is not supported. Please add a feature request on our [UserVoice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Feature requests are considered when we go through our planning process.

**Comment by hello-chenchen** [comment]
hi @exextoc , for the single sign-on for add-ins, i have one question here.
from the document [Enable single sign-on for Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins), it seams that if the user want to use this feature. he or his IT admin must have an azure account and mush Register an application which is provide the access_token for the add-in by getAccessToken, right?

**Comment by hello-chenchen** [comment]
and this manifest must be customized by their it admin, and must contains below in the manifest.xml?
```
<WebApplicationInfo>
  <Id>$application_GUID here$</Id>
  <Resource>api://localhost:44355/$application_GUID here$</Resource>
  <Scopes>
      <Scope>Files.Read.All</Scope>
      <Scope>profile</Scope>
  </Scopes>
</WebApplicationInfo>
```

**Comment by exextoc** [comment]
That is correct. You'd need to sign in with admin credentials to your Microsoft 365 tenancy to [register the application](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/register-sso-add-in-aad-v2).
