### ISSUE TITLE
Is there an ETA for when `getAccessToken` will be out of preview?

### ISSUE THREAD

**Issue by tjcrowder** [OfficeDev/office-js#1339]
Is there an ETA for when `getAccessToken` will be out of preview and available on the semi-annual update channel? (For Office365 on Windows and on the web.) Our IT department won't allow the preview channel or monthly updates.

Our understanding is that right now you have to:

* be on the Preview channel
* have Office v1809 or higher
* have Windows 10 v1903 or higher

The last two aren't an issue; the first is a blocker.

We've tried to figure it out from [this][1] and [this][2], but there doesn't seem to be any ETA.

Thanks!

[1]: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/identity-api-requirement-sets
[2]: https://docs.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date

**Comment by Rick-Kirkham** [comment]
It released a couple of weeks ago, its out of preview. See this announcement post (and the link in it to the requirement set article): 
[Announcing General Availability of Single Sign-On (SSO) for Office Add-ins](https://developer.microsoft.com/en-us/graph/blogs/announcing-general-availability-of-single-sign-on-sso-for-office-add-ins/)

I'll close this, but if you still have questions you can still ask them here.

**Comment by tjcrowder** [comment]
@Rick-Kirkham - That's great! When will 2008 make the semi-annual channel? [This](https://docs.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date) made it seem like 2008 would be some time before reaching that stage...? It says the semi-annual channel just recently reached 2002 (August 11th). (It also lists "Monthly Enterprise Channel" twice, 2005 and 2006, respectively.)

**Comment by tjcrowder** [comment]
@Rick-Kirkham - Hi -- Just checking back on the above. Thanks.

**Comment by tjcrowder** [comment]
@Rick-Kirkham  - Hi -- Just checking back again, management is really keen to get an answer to this question. I've suggested they raise it through our premier support or whatever that's called, but if you can shed any light as a subject matter expert, that would be really useful. Thanks!
