### ISSUE TITLE
Table.showHeaders=false crashes Excel

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js#134]
See this SO issue for details: https://stackoverflow.com/questions/50342241/office-js-the-excel-will-exited-by-using-showheaders

## Expected Behavior
The header text should be blanked out and Excel should not crash.

## Current Behavior
Excel crashes (and relaunches immediately). 

## Steps to Reproduce, or Live Example
Just use the customer's code in the SO question.

## Context
N/A

## Your Environment
See the SO issue.

**Comment by tong-1324** [comment]
I have turned off the flight for the change that caused this issue. If you restart your excel, the issue should be fixed.

**Comment by nimro** [comment]
I'm seeing this issue today for any users who have updated to Excel 1808 Build 10730.20102

Any table where "showHeaders = false" is set will fully crash Excel.
