### ISSUE TITLE
Word Online: createDocument(base64File) fails with 3rd-party WOPI hosts

### ISSUE THREAD

**Issue by yuoooz** [OfficeDev/office-js#1340]
Dear OfficeJs dev team,
CreateDocument API is not working with 3rd-party WOPI Hosts. Calling this API results in redirect to Outage.html with reported 'Not Implemented' status code. Looks like no calls to storage are being made from Office services. The issue has been described at https://stackoverflow.com/q/63029379/795861, but no answers so far.

## Expected Behavior
A new document is created. A user is prompted to open it.

## Current Behavior
Nothing happens on UI. There are error logs in console.

## Steps to Reproduce, or Live Example

[Script Lab gist] https://gist.github.com/yuoooz/a82add33f20b4235cabeede5955fd2c9
Click Create button and then Ok.

* Additional details:
    1. This API fails with DropBox, NetDocuments in Word Online, but works as expected in desktop version.
    2. This API works fine with SharePoint & One Drive.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.13220.41000
* Browser (if using Office on the web): All browsers

## Useful logs
  ![Image](https://i.stack.imgur.com/4F23E.png)

**Comment by donlvMSFT** [comment]
Hi yuoooz, thanks for reaching us.

Word online doesn’t support create new document on third party host from UI, so does the API. 
For online, CreateDocument API only support OneDrive & SharePoint, not other third party host.

**Comment by yuoooz** [comment]
Hi @donlvMSFT. Thank you very much for your response.

Are there any ETA or at least plans for this to be implemented?

**Comment by donlvMSFT** [comment]
No plan for now, the feature should first supported on UI, then API. If it's important to you, one suggestion is to put a request on UserVoice to ask the supportive on UI.
