### ISSUE TITLE
Word Online: insertOoxml and insertFileFromBase64 fail with 3rd-party WOPI hosts

### ISSUE THREAD

**Issue by yuoooz** [OfficeDev/office-js#1341]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Dear OfficeJS dev team,
 
Replacing the whole document content through insertOoxml or insertFileFromBase64 with location set to Replace does not work with 3rd-party WOPI hosts such as DropBox, NetDocuments. The issue has been described at https://stackoverflow.com/q/63031020/795861

## Expected Behavior
The content on the document is replaced.

## Current Behavior
Nothing happens on UI. There are error logs in console.

## Steps to Reproduce, or Live Example
[Script Lab gist](https://gist.github.com/yuoooz/a82add33f20b4235cabeede5955fd2c9)
Click Insert button.

* Additional details:
This API fails with DropBox, NetDocuments in Word Online, but works as expected in desktop version.
This API works fine with SharePoint & One Drive.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.13220.41000
* Browser (if using Office on the web): All browsers

## Useful logs

- [ ] Screenshots
![Image](https://i.stack.imgur.com/wS8FI.png)

**Comment by yuoooz** [comment]
Hi @donlvMSFT ,
I've figured out that WOPI hosts are able to handle these requests. It appears that Word Online is not able to automatically reflect changes, but still able to present them after refreshing the page or reopening the document. Tested with Drop Box, NetDocuments and HighQ. 
Hope that helps to investigate the issue.

**Comment by donlvMSFT** [comment]
Hi @yuoooz , after we investigate, this is a behavior existing for a long time, supporting WOPI would be a new feature for these 2 APIs, and we don't have priority take this in current stage.

If it's important to you, I'd suggest that you could submit your request on [User Voice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?category_id=163563), and up-vote your request. 

Thanks.
