### ISSUE TITLE
Does single sign on SSO work with Azure Devops Git Rest API?

### ISSUE THREAD

**Issue by Lilyliu123** [OfficeDev/office-js#1342]
I am using OfficeRuntime.auth.getAccessToken({ allowSignInPrompt: true }) for the single sign on. It worked well and I can get my user profile data returned.

However when I used the returned token to try to access the  [Azure Devops  Git Rest API](https://docs.microsoft.com/en-us/rest/api/azure/devops/git/?view=azure-devops-rest-6.0) the token didn't work.

Does single sign on SSO work with Azure Devops Git Rest API?

**Comment by sumurthy** [comment]
The token is only valid for Microsoft Graph based APIs. The Azure Devops APIs are available under Azure REST and hence not a supported service for single sign on.
