### ISSUE TITLE
Addins Not Working in Outlook-Android for several locales/language settings.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#1343]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

AddIns not loading for 5 specific locales in Outlook Android.

## Expected Behavior

Addins must be successfully loaded in all locales/language settings.

## Current Behavior

Addins are not loading if you set Outlook-Android locale to any of the following : 
العربية
বাংলা-BD
বাংলা-BA
فارسی
मराठी (भारत)

## Steps to Reproduce, or Live Example
1. Install Slack, Evernote or any Addon That can run on mobile.
2. From your Android outlook, select and set any of the 5 locales mentioned above as default language.
3. Open an email and access your installed addin.
EXPECTED : AddIn Loads successfully.
ACTUAL : AddIn Loading fails.

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
@glr0221 Can you share a screenshot of the issue?
Is this Android specific? or do you see this in other clients (Desktop/Online)?

Also [localization](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/localization) is completely owned by the add-in developer, meaning if developer does not provide localization for a particular language we show the default values.

**Comment by glr0221** [comment]
@exextoc thanks for the quick response. I will try and upload a video for you tomorrow. It's not really the values or text shown. The addins don't load at all. I tested with Slack, Evernote and our own add-in as well.

**Comment by glr0221** [comment]
@exextoc sorry for the delay, here is a link of the video I made for this issue : 

https://youtu.be/dtZqx6R5t-8

Please tell me if the video does not load on your end, and I will find some other way to share.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding add-in not working in some locales. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by glr0221** [comment]
@exextoc Thank you also for taking a look at this issue. There is no rush for the fix. I just dropped by to inform you about it.  Thank you again.
