### ISSUE TITLE
Excel.NamedItemCollection.add causes an internal error on sync.

### ISSUE THREAD

**Issue by chucklay** [OfficeDev/office-js#1345]
I currently have an add-in that loads some data and performs some general ease-of-use steps once the data is loaded
## Expected Behavior
```context.workbook.names.add(string, Excel.Range)``` should create a new named range when ```context.sync()``` is called.

## Current Behavior
Attempting to call
```context.workbook.names.add("AnyNameHere", range);``` (or the equivalent method on a worksheet's NamedItemCollection) results in the following RichAPI error the next time context.sync() is called:

```
RichApi.Error: There was an internal error while processing the request.
    at new n (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:293852)
    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:353530)
    at https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:351686
```

## Steps to Reproduce, or Live Example

* Link to live example: https://gist.github.com/chucklay/fe9a2ade1cca3e7ef0fe253dc793003f

* Additional details:
This happens in my add-in after pulling in data from a remote source and running some common convenience methods.
```
            // Common convenience methods
            // Freeze column headers
            sheet.freezePanes.freezeRows();
            // Auto-resize columns
            range.format.autofitColumns();
            // Enable filters
            sheet.autoFilter.apply(range);
            // Create/update named range
            ctx.workbook.names.add(worksheetName + " ALL", range);  // <- This is the problem. Removing this line results in ctx.sync() executing without error
            return ctx.sync(); 
```

## Context
Attempting to use this for ease-of-use when working with pivot tables at another point in the add-in.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop (16.0.13029.20342), Office on the web (16.0.13219.35051)
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.13029.20342/16.0.13219.35051
* Operating System: Windows 10 version 1909
* Browser (if using Office on the web): Edge 84.0.522.63

## Useful logs

- [ ] Console errors:
```
RichApi.Error: There was an internal error while processing the request.
    at new n (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:293852)
    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:353530)
    at https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:351686
```

**Comment by lumine2008** [comment]
Thanks for your post, I can repro it with your gist, a bug(4409514#) was logged for tracking this issue. Team is working on investigation on it.

**Comment by lumine2008** [comment]
Hi @chucklay , it seems that you added space in names "name test" for the named item. which is not a valid naming pattern. this operation will be failed if you do it via UI. therefore you can remove the space in the name. thanks.

**Comment by chucklay** [comment]
Yep, that was it. Thanks! Wasn't aware of that caveat. If possible, it might be worth making that error message a bit more descriptive. As it stands there's not much to go off of.
