### ISSUE TITLE
Office.context.mailbox.userprofile doesnt work correct with shared mailboxes

### ISSUE THREAD

**Issue by isawek** [OfficeDev/office-js#1348]
## Expected Behavior

i use Office.context.mailbox.userProfile.emailAddress to get the information and need to get the email adress of the shared mailbox.

## Current Behavior

in outlook web everything works fine but in the client i always get my userprofile instead of the profile of the current [mailbox.]

## Steps to Reproduce, or Live Example

* Additional details:
  1. just try to get the Office.context.mailbox.userProfile.emailAddress from a shared mailbox in the client application

## Context

I use the office-js with shared mailboxes and need to get the current mailbox email adress.
probably it is a bug inside the client application cause if i add a mailbox and right click it and click on **Data File Properties** (at the bottom of the context menu) and after that click on **Advanced...**. i see my email adress instead of the mailbox adress.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows
* Host [Excel, Word, PowerPoint, etc.]: Outlook Client
* Office version number: 2008 (Build 13127.20208 Click-to-Run) Current Channel (Preview)
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome

**Comment by exextoc** [comment]
Office.context.mailbox.userProfile.emailAddress is supposed to give you the current mailbox's email address, this looks like an issue in Outlook Online not Outlook Windows.
Please share a screenshot from Outlook Online (highlighting how you are accessing shared mailbox).

For your use case, you can use [Office.context.mailbox.item.getSharedPropertiesAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-1.8#getsharedpropertiesasync-options--callback-) to fetch owner email address.

**Comment by isawek** [comment]
No i think the error is inside Outlook Windows. In Outlook Online it works fine. I will do some screenshots and send them to you

**Comment by isawek** [comment]
Online i do the following steps to get to the mailbox (works fine getting the right mailbox with office js)
1. click on my profile
2. click OwaOpenTargetMailboxLink
3. enter mailbox
4. click "open" button
![Online](https://i.ibb.co/CtG6gTj/Online.png)

in Outlook Windows it doesn't work and with office js i always get my mailbox instead of the shared mailbox. Probably it is connectet with the following behavior.

1. right click on shared mailbox
2. click on Data File Properties...
3. click on Advanced.
4. under Mailbox it shows my adress instead of the adress of the mailbox
![Offline1](https://i.ibb.co/3SJWTs4/Offline.png)
![Offline2](https://i.ibb.co/KFxDQrq/Offline2.png)

**Comment by isawek** [comment]
> For your use case, you can use [Office.context.mailbox.item.getSharedPropertiesAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-1.8#getsharedpropertiesasync-options--callback-) to fetch owner email address.

could you please give me the exact property name to ask for? And does the property always give me the mailbox adress? cause i use this add in with sended and received emails and "owner" sounds like it could always be the sender.

**Comment by exextoc** [comment]
[owner](https://docs.microsoft.com/en-us/javascript/api/outlook/office.sharedproperties?view=outlook-js-1.8#owner) property represents the user, whose mailbox the item belongs to. (not the sender)
