### ISSUE TITLE
Outlook: Office.context.mailbox.item.isAllDayEvent is undefined (always)

### ISSUE THREAD

**Issue by yosefsun** [OfficeDev/office-js#1349]
## Expected Behavior
Office.context.mailbox.item.isAllDayEvent should return either a boolean or a IsAllDayEvent object

## Current Behavior
Always retuning undefined

## Steps to Reproduce, or Live Example
open an event
open the add-in sidepane
console.log the Office.context.mailbox.item.isAllDayEvent object

## Your Environment

* Platform : Mac OS Catalina 10.15.6
* Browser : Chrome V 84.0.4147.135 (Official Build) (64-bit)
* office.js versioin : 1.1 (https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js  )

**Comment by exextoc** [comment]
@yosefsun Can you provide us with the requested information under the **Your Environment** section?
`isAllDayEvent` is currently in preview and is available on Outlook on Windows connected to a Microsoft 365 Subscription.
Documentation here: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview

**Comment by yosefsun** [comment]
@exextoc updated

**Comment by exextoc** [comment]
This is an expected behavior because this API is not implemented in Outlook web or Mac Outlook. You can, however, try this API on Outlook on Windows.
