### ISSUE TITLE
Office.context.mailbox.getCallbackTokenAsync never fires callback

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js#135]
In my app the callback of that code is never fired:

```js
Office.context.mailbox.getCallbackTokenAsync({isRest: true}, function(result) {
  console.log('never arrives here, why?')
})
```

I do not see any errors in the console when testing locally. Just nothing. While debugging deep in your code, it seems that after `postMessage` nothing happens.

What could this be? Possible reasons? The parent frame, which is outlook.office.com, seems to be receiving the message from localhost but isn't responding.

Thanks for any clues

**Comment by exextoc** [comment]
Can you share the client that you are using? It seems to be OWA (which browser version) Do you also know if you are on OWA or on OWA Beta? That said I tried reproing and was always able to get the callback, on either OWA or OWA Beta, the callback was called. Is the account on Office 365? Do you see the postMessage failing?

**Comment by binarykitchen** [comment]
Client? Latest Chrome. Using https://outlook.office.com/owa and my account is admin@testingnz.onmicrosoft.com

Serving my files from `https://localhost:3443`.  The function file which contains code to be run upon press of a button is `https://localhost:3443/index.html`

Configured app domains are:

```
  <AppDomains>
    <AppDomain>https://localhost:3443</AppDomain>
    <AppDomain>https://login.windows.net</AppDomain>
    <AppDomain>https://login.microsoftonline.com</AppDomain>
  </AppDomains>
```

Again, the callback in Office.context.mailbox.getCallbackTokenAsync never gets fired and no errors are seen in the console.

**Comment by timwan10** [comment]
Was this resolved along with the issue here: https://github.com/OfficeDev/office-js/issues/132 ?

**Comment by exextoc** [comment]
Was this resolved with the ExecuteFunction changes you made here: https://github.com/OfficeDev/office-js/issues/132 ?

**Comment by binarykitchen** [comment]
yes and i wish a warning was printed. that would have saved me lots of time.
