### ISSUE TITLE
Outlook: on-send handler occasionally fails to prependAsync with addRange(): The given range isn't in document.

### ISSUE THREAD

**Issue by roysjosh** [OfficeDev/office-js#1350]
An add-in implementing the on-send handler experiences occasional prependAsync failures. In general it succeeds but there are seemingly random failures. I'm not sure what is different to cause the failures.

## Expected Behavior
The prependAsync call should consistently prepend our header or return an error.

## Current Behavior
Certain unknown circumstances seem to cause prependAsync to fail to add our header.

## Steps to Reproduce, or Live Example
```javascript
export function prependValue(item, ...args): Promise<void> {
  return new Promise((resolve, reject) => {
    // set up common callback
    let cb = (result: Office.AsyncResult<void>) => {
      if (result.status === Office.AsyncResultStatus.Succeeded) {
        resolve();
      } else {
        console.log('PREPEND VALUE ERROR');
        console.log(result);
        reject(result.error);
      }
    };
    // call appropriate method
    item.prependAsync(...args, cb);
  });
}

export async function onSendHandler(event) {
  // ... redacted ...
  let email = Office.context.mailbox.item as Office.MessageCompose;
  // ... redacted ...
  try {
    await prependValue(email.body, someHtml, { coercionType: Office.CoercionType.Html });
    event.completed({ allowEvent: true });
  } catch (e) {
    console.log('ERROR');
    console.log(e);
    event.completed({ allowEvent: false });
  }
}
```
* Additional details:
  1. an error is NOT thrown (prependAsync returns Succeeded???) when the html header fails to prepend
  2. an error IS printed out
    addRange(): The given range isn't in document.

## Context
Our product will frequently send emails to users who do not have the add-in installed. They will not know about our product or its features without our header.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: This has been seen on Mac & Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook for Mac 16.40 (20081000)
* Operating System: MacOS 10.15.5
* Browser (if using Office on the web): Chrome 84.0.4147.135

## Useful logs
```
addRange(): The given range isn't in document.
t.selectRange	@	selectRange.ts:70
t.focus	@	owa.41.js:1
e.focus	@	Editor.ts:617
(anonymous)	@	prependContentToEditor.ts:26
(anonymous)	@	operateContent.ts:117
u	@	index.ts:1
m	@	createTempHtmlEditor.ts:8
(anonymous)	@	prependContentToEditor.ts:23
Promise.then (async)		
o	@	prependContentToEditor.ts:21
(anonymous)	@	SubjectAdapter.ts:11
(anonymous)	@	setDataAsyncApiMethodBase.ts:66
(anonymous)	@	VM12 inbox:344
(anonymous)	@	VM12 inbox:344
a	@	VM12 inbox:344
Promise.then (async)		
s	@	VM12 inbox:344
(anonymous)	@	VM12 inbox:344
l	@	VM12 inbox:344
oe	@	owa.MailBoot~Addins~…s-marketplace.js:12
(anonymous)	@	bodyPrependAsyncApiMethod.ts:28
(anonymous)	@	VM12 inbox:344
(anonymous)	@	VM12 inbox:344
(anonymous)	@	VM12 inbox:344
l	@	VM12 inbox:344
(anonymous)	@	owa.MailBoot~Addins~…s-marketplace.js:12
hn	@	executeApiMethod.ts:82
(anonymous)	@	EndpointRegistrator.ts:41
invoke	@	osfruntime.js:2246
T	@	osfruntime.js:1710
x	@	osfruntime.js:1701
setInterval (async)		
U	@	osfruntime.js:1890
```

**Comment by exextoc** [comment]
@roysjosh Please share the console logs from Mac as well, this will help us investigate the issue.
Useful link: [Debugging with Safari Web Inspector on a Mac](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac#debugging-with-safari-web-inspector-on-a-mac)

**Comment by exextoc** [comment]
@roysjosh We are not able to repro this on Mac client and OWA. Please share repro video and build version with us so that we can investigate further.
