### ISSUE TITLE
The ContextMenuCell option doesn't show up for cells that are part of a table. Is this by design or a bug?

### ISSUE THREAD

**Issue by nikhilism15** [OfficeDev/office-js#1353]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

The `ContextMenuCell` option, if used, shows custom menu options for normal cells but if the cell is part of a table, it doesn't show up. Is this by design or a bug? If it's by design, how do I make the menu show up for a table cell? My add-in works exclusively on tables so this is very important.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46c4dafc-01a5-84c3-9cc0-dbc862a6c162
* Version Independent ID: 9d280f3c-be20-bd7f-0cee-bf39cb17e504
* Content: [OfficeMenu element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officemenu)
* Content Source: [docs/reference/manifest/officemenu.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/officemenu.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
@smaremanda, can you investigate here?

**Comment by nikhilism15** [comment]
Hi, may I know when this issue will be potentially fixed in the library?

**Comment by ElizabethSamuel-MSFT** [comment]
@erayc-msft Can you take a look?

Thanks.
