### ISSUE TITLE
Office.context.mailbox.item is undefined

### ISSUE THREAD

**Issue by ydock1** [OfficeDev/office-js#1355]
## Expected Behavior
 Office.context.mailbox.item should bring data

## Current Behavior
 Office.context.mailbox.item is undefined

## Steps to Reproduce, or Live Example
```
function (response) {
                        $rootScope.isLogged = true;
                        $scope.$close();

                        if (!loginOutlookService.isEvent(Office.context.mailbox)) {
                            var toMails = "";
                            for (var i = 0; i < Office.context.mailbox.item.to.length; i++) {
                                toMails += Office.context.mailbox.item.to[i].emailAddress + ";";
                            }
                            var CCMails = "";
                            for (i = 0; i < Office.context.mailbox.item.cc.length; i++) {
                                CCMails += Office.context.mailbox.item.cc[i].emailAddress + ";";
                            }
                            alreadyMatterAttachedByOtherUserTransparentService.isAlreadyMatterAttachedByOtherUser(Office.context.mailbox.item.internetMessageId, Office.context.mailbox.item.subject, Office.context.mailbox.item.dateTimeCreated.toUTCString(), Office.context.mailbox.item.from.emailAddress, toMails, CCMails).then(function (response) {
                                if (response.data.alreadyAttached) {
                                    $rootScope.myModalAlreadyMatterAttachedByOtherUser = $uibModal.open({ templateUrl: 'AlreadyMatterAttachedByOtherUser.html', controller: 'AlreadyMatterAttachedByOtherUserTransparentController', backdrop: 'static' });
                                }
                            });
                            Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, function (eventArgs) {
                                var toMails = "";
                                for (var i = 0; i < Office.context.mailbox.item.to.length; i++) {
                                    toMails += Office.context.mailbox.item.to[i].emailAddress + ";";
                                }
                                var CCMails = "";
                                for (i = 0; i < Office.context.mailbox.item.cc.length; i++) {
                                    CCMails += Office.context.mailbox.item.cc[i].emailAddress + ";";
                                }

                                alreadyMatterAttachedByOtherUserTransparentService.isAlreadyMatterAttachedByOtherUser(Office.context.mailbox.item.internetMessageId, Office.context.mailbox.item.subject, Office.context.mailbox.item.dateTimeCreated.toUTCString(), Office.context.mailbox.item.from.emailAddress, toMails, CCMails).then(function (response) {
                                    if (response.data.alreadyAttached) {
                                        $rootScope.myModalAlreadyMatterAttachedByOtherUser = $uibModal.open({ templateUrl: 'AlreadyMatterAttachedByOtherUser.html', controller: 'AlreadyMatterAttachedByOtherUserTransparentController', backdrop: 'static' });
                                    }
                                });
                                $rootScope.shouldRefresh = true;
                            });
                        }
                    }
```

* Additional details:
(The Email must have 1 attachment)
1- Open a mail in a new window
2- Only happens if you preview the attachment first and then load the addin(i´ve tried with doc and pdf and i got the same result)
3- Load the addin and retrieve the data of the mail 
4- The data now is undefined

## Context
We are importing emails to our software and without the email data we cant.
This only happens if you open the email in a new window and  you preview the attachment first. If you don´t open the preview it brings the data in the "item" field correctly.

Video 

https://vimeo.com/453268614

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop, OWA and office365
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ___
* Operating System: Win 10
* Browser (if using Office on the web): Edge insider, Chrome

## Useful logs

- [X ] Console errors

`TypeError: Cannot read property 'itemType' of undefined
    at Object.factory.isEvent (OutlookRelatedMatters.js:1464)
    at OutlookRelatedMatters.js:994
    at processQueue (angular.js:14569)
    at angular.js:14585
    at Scope.$eval (angular.js:15848)
    at Scope.$digest (angular.js:15659)
    at Scope.$apply (angular.js:15953)
    at done (angular.js:10366)
    at completeRequest (angular.js:10538)
    at XMLHttpRequest.requestLoaded (angular.js:10479)`

- [ X] Screenshots
![Office](https://user-images.githubusercontent.com/23103235/91718319-6aa2de80-eb93-11ea-8224-8d9e8c1ec710.PNG)

**Comment by exextoc** [comment]
@ydock1 Can you please share repro video? We are not able to see repro video here- https://vimeo.com/453268614.

**Comment by ydock1** [comment]
> @ydock1 Can you please share repro video? We are not able to see repro video here- https://vimeo.com/453268614.

Hello, now  the link is working,

**Comment by exextoc** [comment]
We are able to reproduce this from our side. Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
Hey @ydock1 ,

This issue has now been fixed. Please do have a look from your side and confirm the same. Please reactivate this thread again if you still see the issue.

**Comment by oleksandr-slys** [comment]
Hi @exextoc!
1 - what was the problem? 
2 - how to troubleshoot such the problems? 
I have the similar problems but the conditions are different. In on of my mailboxex `mailbox.item` returns `undefined` for all emails, but other mailboxes works just fine.
Can I check some permissions or settings in mailbox to find out why `mailbox.item` is undefined?

**Comment by ydock1** [comment]
> Hey @ydock1 ,
> 
> This issue has now been fixed. Please do have a look from your side and confirm the same. Please reactivate this thread again if you still see the issue.

Hello, the issue is resolved. Thank you!

**Comment by exextoc** [comment]
@oleksandr-slys As you have mentioned in your case conditions are different. Can you create a separate post with all the details about your environment and repro steps?

**Comment by ndvbd** [comment]
Same issue here :(
