### ISSUE TITLE
Load `arrayValues` for some named ranges causes Excel to crash

### ISSUE THREAD

**Issue by jwhite-venacorp** [OfficeDev/office-js#1357]
When named ranges' formulas have functions or multiple ranges, such as:

```
=Sheet1!$B$3,Sheet1!$B$6
```
or
```
=OFFSET(Sheet1!$B$2:$B$7,1,0,ROWS(Sheet1!$B$2:$B$7)-1,1)
```

calling `context.workbook.names.load('items/arrayValues')` causes an Excel application error. This causes Excel to close and restart.

## Expected Behavior
Ideally, I expect the `arrayValues` to be loaded for all the named ranges. At the very least, Excel should not crash.

## Current Behavior
Excel crashes. Here's what is logged in the application event viewer (on Windows):
```
Faulting application name: EXCEL.EXE, version: 16.0.13001.20520, time stamp: 0x5f2454b8
Faulting module name: mso20win32client.dll, version: 0.0.0.0, time stamp: 0x5f20fe45
Exception code: 0x0152139a
Fault offset: 0x000000000020e37d
Faulting process id: 0x11ec
Faulting application start time: 0x01d6804d866c99c0
Faulting application path: C:\Program Files\Microsoft Office\Root\Office16\EXCEL.EXE
Faulting module path: C:\Program Files\Common Files\Microsoft Shared\Office16\mso20win32client.dll
Report Id: b7438f24-847a-4b6c-a10f-70c0def955cc
Faulting package full name: 
Faulting package-relative application ID: 
```

## Steps to Reproduce, or Live Example

* Link to live example: https://gist.github.com/jwhite-venacorp/11a9534ca6b785bd6c653d3ed7ed342d

Either of the "Create with function" or "Create with delimited" buttons will set up the document, and the "Load test" button exemplifies the issue.

## Context
We need to load most (if not all) of the named ranges and their values.

## Your Environment 
* Platform: Windows Desktop
* Host: Excel
* Office version number: Version 2006 (Build 13001.20520 Click-to-Run)
* Operating System: Windows 10, version 2004

## Useful logs
[EventViewer details.txt](https://github.com/OfficeDev/office-js/files/5157307/EventViewer.details.txt)

**Comment by sharonplatkin** [comment]
Reproduced this and current behaviour is persisting on my machine as well.

**Environment**
Platform: Mac Desktop
Host: Excel
Office version number: Version 16.40 (20081000)
Operating System: macOS Catalina Version 10.15.5

**Comment by lumine2008** [comment]
Thanks @platkis , we can repro this issue in our side, and a bug 4434362 was logged to track this issue.

**Comment by lumine2008** [comment]
This issue was fixed, please verify, thanks
