### ISSUE TITLE
Outlook/Word Windows 10 Getting Body Text Briefly Hangs Document On Certain Devices

### ISSUE THREAD

**Issue by rogueunix** [OfficeDev/office-js#1360]
Currently, our add-in has logic in both Outlook and Word to poll the Word document for current body text or the Outlook mailbox item body text every 5 seconds and perform processing on it. In almost every environment I've tested (Mac, Web, and most Windows 10 environments), the documents are polled with no interrupt to the document, but on these specific organization managed, Windows 10, Surface Pro tablets, the document will hang as I'm typing and random keystrokes will not be entered in the document.

For Outlook, I'm using this code block to get body text:
```
window.Office.context.mailbox.item.body.getAsync(window.Office.CoercionType.Text, {}, (asyncResult) => {
  this.doSomethingWithText(asyncResult.value)
})
```

For Word, I'm using this code block to get body text:
```
window.Word.run((context) => {
  let documentBody = context.document.body
  context.load(documentBody)
  return context.sync().then(() => {
    this.doSomethingWithText(documentBody.text)
  })
})
```

**Note**: The problem is less frequent, but still occurs if I change the setInterval from 5 seconds to say 30 seconds.

## Expected Behavior
I expect for the document to not hang when getting the document text in every environment and all keystrokes to register appropriately. 

## Current Behavior
On these specific organization managed, Windows 10, Surface Pro tablets, the document will hang as I'm typing and random keystrokes will not be entered in the document.

## Steps to Reproduce, or Live Example
You should be able to reproduce the issue by installing the [Huna Add-In](https://appsource.microsoft.com/en-us/product/office/WA200001943) in Word on Windows 10.

But, if not, a simple application with a setInterval that calls a function with one of the above code blocks should trigger it.

## Context
Trying to prevent any Huna users from having to experience this issue while they're working, especially since it may not be apparent to a lot of users where this problem is coming from, and, in the worst case, if they do understand they may remove the add-in over the issue.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Word / Outlook
* Office version number: Version 2007 (Build 13029.20460)
* Operating System: Windows 10 Enterprise Version 2004 (Build 19041.388)

**Comment by oberoiankush** [comment]
The getBody API in Outlook was not designed to be used with polling. This is expected when polling the body. As you pointed out, reducing the polling interval circumvents this issue however not completely. What is the scenario you're trying to achieve that requires you to poll the body of the message in Outlook?

**Comment by rogueunix** [comment]
After each poll, the previous body and current body are compared. Words that were removed are removed from our list of search results, and words that were added are searched in our backend for results and displayed accordingly. This accomplishes 2 things: our results appear in, somewhat, real time as the user doesn't have to interact with the Add-In to search, and these results now appear in the order they were typed, not just the order of the document.

**Comment by exextoc** [comment]
Thanks for clarifying the use case. Unfortunately as mentioned, the getBody API was not designed to be polled. What you might be looking for is a GetBodyChangedEvent that can help you make your server calls when the body changes and the event is triggered to the add-in, however this feature is currently not a part of the product. We track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins ). Please add your request there. Feature requests on user-voice are considered, when we go through our planning process.

**Comment by rogueunix** [comment]
That definitely makes sense, thanks for the response.

My final question would be, do you have ideas as to why this interrupt only occurs on some devices, but not others? (as outlined above)

**Comment by exextoc** [comment]
Each client has it's own native implementation of the API which depends on the native implementation of the client itself. For Desktop, as an example, the getBody call results in a save which is what causes the interrupt as the save happens on the main thread.

**Comment by rogueunix** [comment]
I understand there's different implementations across platforms and web/desktop, but the interruption issue I've been describing only appears on a small number of Windows 10 devices using the desktop variant of Word/Outlook, and behaves normal, without interruption, on most Windows 10 devices with the desktop variant. I've checked to make sure Office and Edge versions match between devices, and system specs are more or less the same.

**Comment by exextoc** [comment]
There are many different factors that could cause body.getAsync to hang. Possible factors include the content of the e-mail (if the e-mail is large/contains images) or any core OS processes that are running when the API is called.  

The body.getAsync API was not designed to be polled, and a getBodyChangedEvent should resolve this issue in the future.

**Comment by jedmonsanto** [comment]
@exextoc what if the mail is large, i have been experiencing this problem since last month, what's the solution/workaround?
