### ISSUE TITLE
[Outlook] Show URL different on Windows Outlook client and other platform

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1361]
I met a very interesting problem. 
When I set an URL to the meeting body. Using 
`var options = {coercionType: Office.CoercionType.Html};
Office.context.mailbox.item.body.setAsync(htmlBody,  options, function (result) {
    //xxxxx
});`
It shows different on Windows Outlook client and other platform like browsers or Mac Outlook client.

On Windows Outlook client it shows an hyper link
On browsers or Mac outlook client only shows an link text which can't be clicked directly

I have checked all platform body type is HTML. 
## Expected Behavior
If possible I hope all platform can show as Hyper link.

## Current Behavior
On Windows Outlook client it shows an hyper link
On browsers or Mac outlook client only shows an link text which can't be clicked directly

## Steps to Reproduce, or Live Example
Use api:
`var options = {coercionType: Office.CoercionType.Html};
Office.context.mailbox.item.body.setAsync(htmlBody,  options, function (result) {
    //xxxxx
});`
set URL to meeting.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ALL
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: latest
* Operating System: Mac and Windows
* Browser (if using Office on the web): Chrome, EDGE, FireFox and Safari

Any idea?

**Comment by exextoc** [comment]
We are not able to repro this on our side.Could you please share a code snippet  with which we can try to reproduce ?

**Comment by SWei1234** [comment]
Hi @exextoc 
Please consult:
Recording:
https://success.zoom.us/rec/share/mtUUL9SZMY0mJkahmcnI8POidJzpNopnMujbfP5veBsIGYXJfaLyoy5LZy3rbV6-.4ULjyOr_vqo2owHd
 
Access Passcode: nA3uVT#w


Code:
//read custom properties
Office.context.mailbox.item.loadCustomPropertiesAsync(function (result){
                    console.log(result.value);
                });

//save custom properties
Office.context.mailbox.item.loadCustomPropertiesAsync(function (result){
                    var customProps = result.value;
	    customProps.set("test","test");
customProps.saveAsync(function () {
                    return true;
                });
                });

**Comment by exextoc** [comment]
Code snippet  and Video which is shared and issue description do not match. Can you please share Code snippet for the issue which is mentioned in the description of this bug? Also the repro video and snippet which you shared earlier matches with the issue description of this bug- https://github.com/OfficeDev/office-js/issues/1333. You have added same comment there as well.

**Comment by SWei1234** [comment]
Hi @exextoc 
Sorry for wrong recording link. Already updated the link in above comment.

**Comment by exextoc** [comment]
Thanks for reporting this issue. We have been able to reproduce this. We have added this bug in our backlog but unfortunately we don't have timelines to share at this point.

However as a workaround, you can add HTML anchor tags (a href) in the html content to create the link.
