### ISSUE TITLE
Empty ewsUrl in Outlook for Mac when using Gmail account

### ISSUE THREAD

**Issue by modestfake** [OfficeDev/office-js#1362]
I've connected my Gmail account to Outlook for Mac and tried to get `window.Office.context.mailbox.ewsUrl`, it returns an empty string `''`. I tried to log into my Gmail account using OWA and there it works, it returns `https://outlook.office365.com/EWS/Exchange.asmx`.

## Expected Behavior
Outlook for Mac to be consistent with OWA and return `ewsUrl` when accessing `window.Office.context.mailbox.ewsUrl`.

## Current Behavior
`window.Office.context.mailbox.ewsUrl` is an empty string `''` in Outlook for Mac when using Gmail account.

## Steps to Reproduce, or Live Example
1. Add your Gmail account to Outlook for Mac, run add-in in taskpane. Check `window.Office.context.mailbox.ewsUrl`. It will be an empty string `''`.
1. Add your Gmail account to OWA (outlook.live.com), run add-in in a taskpane. Check `window.Office.context.mailbox.ewsUrl`. It should be something like `https://outlook.office365.com/EWS/Exchange.asmx`.

## Context
We can't access attachments via EWS API, since there's no `ewsUrl`.

## Your Environment
* Platform: Mac
* Host: Outlook
* Office version number: Outlook for Mac, version 16.40 (20081201)
* Operating System: macOS Catalina 10.15.6
* Browser: Chrome 85.0.4183.83 (it works in this browser in OWA)

**Comment by exextoc** [comment]
Thanks for reporting this issue.It has been put on backlog.We unfortunately have no timeline to share at this point.

**Comment by lliu113** [comment]
@modestfake  - As the request has been added to our backlog, I'll close the issue. Please reopen if you have any further questions, we'll be happy to help. Thanks!

**Comment by exextoc** [comment]
Currently this item is in backlog but as a workaround please sign up on Insiders rings (https://insider.office.com/en-us/join/mac) and use the New Outlook for Mac (https://support.microsoft.com/en-us/office/the-new-outlook-for-mac-6283be54-e74d-434e-babb-b70cefc77439) for immediate access. The New Outlook for Mac will also be available in production around mid October.
