### ISSUE TITLE
getCallbackTokenAsync doesn't work when getting EWS token on Outlook for Mac (Gmail account)

### ISSUE THREAD

**Issue by modestfake** [OfficeDev/office-js#1363]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I have Gmail account in my Outlook for Mac. I'm trying to get EWS token for this account using this code:
```javascript
async getEwsCallbackToken() {
  return new Promise((resolve, reject) => {
    window.Office.context.mailbox.getCallbackTokenAsync({ isRest: false }, (result) => {
      if (result.status === 'succeeded') {
        resolve(result.value)
      } else {
        reject(
          Object.assign(new Error('Error retrieving EWS callback token'), {
            code: 'FAILED_TO_GET_CB_TOKEN',
            details: result.error,
          }),
        )
      }
    })
  })
}
```

But it fails with this error:
```json
{
  "result": {
    "status": "failed",
    "error": {
      "name": "AccessRestricted",
      "message": "Internal protocol error: '-2147467259'.",
      "code": 9017
    },
    "diagnostics": {
      "InvokeCodeResult": -2147467259
    }
  }
}
```
I tried to do the same thing with Gmail account in OWA and it worked there.

## Expected Behavior
Outlook for Mac to be consistent with OWA and return EWS callback token when requested.

## Current Behavior
`window.Office.context.mailbox.getCallbackTokenAsync({ isRest: false }, cb)` fails in Outlook for Mac with Gmail account.

## Steps to Reproduce, or Live Example
1. Add your Gmail account to Outlook for Mac, run add-in in taskpane. Retrieve EWS callback token using `window.Office.context.mailbox.getCallbackTokenAsync({ isRest: false }, cb)`. It will fail (see error above).
2. Add your Gmail account to OWA (outlook.live.com), run add-in in a taskpane. Retrieve EWS callback token using `window.Office.context.mailbox.getCallbackTokenAsync({ isRest: false }, cb)`. It will return EWS callback token.

## Context
We can't access attachments via EWS API since we can't get EWS token.

## Your Environment

* Platform: Mac
* Host: Outlook
* Office version number: Outlook for Mac, version 16.40 (20081201)
* Operating System: macOS Catalina 10.15.6
* Browser: Chrome 85.0.4183.83 (it works in this browser in OWA)

**Comment by modestfake** [comment]
Related issue #1362

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding getCallbackTokenAsync. It has been put on our backlog. We, unfortunately, have no timelines to share at this point

**Comment by exextoc** [comment]
This behaviour in MAC is as per Design .You cannot use Exchange Web Services (EWS) to access items in the Gmail mailbox. This means that you cannot use makeEwsRequestAsync or use an EWS callback token from getCallbackTokenAsync to make EWS calls directly. Instead, you can get the same type of access to the items in the mailbox by using the Outlook REST APIs.Please follow this documentation for more information:-https://docs.microsoft.com/en-us/archive/blogs/exchangedev/announcing-add-in-support-for-gmail-accounts-in-mac-outlook
For OWA:-We will evaluate the right behaviour and make changes

**Comment by ElizabethSamuel-MSFT** [comment]
What is the current status of the OWA investigation? Thx.

**Comment by exextoc** [comment]
This issue for OWA is in our backlog. We unfortunately don't have timelines to share at this point.

**Comment by yuwu9145** [comment]
> This behaviour in MAC is as per Design .You cannot use Exchange Web Services (EWS) to access items in the Gmail mailbox. This means that you cannot use makeEwsRequestAsync or use an EWS callback token from getCallbackTokenAsync to make EWS calls directly. Instead, you can get the same type of access to the items in the mailbox by using the Outlook REST APIs.Please follow this documentation for more information:-https://docs.microsoft.com/en-us/archive/blogs/exchangedev/announcing-add-in-support-for-gmail-accounts-in-mac-outlook
> For OWA:-We will evaluate the right behaviour and make changes

However, I think the primary issue for Gmail account is `getCallbackTokenAsync` does not return the token rather than cannot use the token being returned by it? Same error happened to one of our clients as well.
