### ISSUE TITLE
Outlook Desktop, Outlook for Mac, setSelectedDataAsync produces incorrect formatting for bulleted and numbered lists

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1364]
In an Outlook add-in for compose mode, we use the Office JS API to fill in email fields. The setSelectedDataAsync method inserts HTML with incorrect markup.

## Expected Behavior
The setSelectedDataAsync method should work as expected.

## Current Behavior
The setSelectedDataAsync method ignores markup and produces a list with no bullets/numbers and with an extra empty line in between.

## Steps to Reproduce, or Live Example
Create a new email in Outlook Desktop or Outlook for Mac and execute the code below.

`    Office.context.mailbox.item.setSelectedDataAsync(`
`      '<ul style="margin-left:0cm;">' +`
`      '  <li><span>Line 1</span></li>' +`
`      '  <li><span>Line 2</span></li>' +`
`      '  <li><span>Line 3</span></li>' +`
`      '</ul>',`
`      { coercionType: Office.CoercionType.Html },`
`      (result) => { }`
`    );`

* Additional details:
  1. Everything seems to work fine in Outlook Online.

## Your Environment
* Platform: PC desktop, Mac
* Host: Outlook
* Office version number: Microsoft Outlook Version 2008 (build 13127.20296), Microsoft Outlook for Mac Version 16.40 (20081201)
* Operating System: Windows 10 version 2004, macOS Catalina Version 10.15.6
* Browser (if using Office on the web): ______

## Useful logs
![image](https://user-images.githubusercontent.com/28924916/92001679-a4b4e180-ed47-11ea-9de2-572c52f01ceb.png)

**Comment by oberoiankush** [comment]
We are unable to reproduce the issue on Outlook Desktop. Is there an additional step between opening the new email and calling into the API? Does this only happen with the formatted content being a list or all sorts of HTML content, like say inserting a bold/Italix text?

**Comment by exextoc** [comment]
We are unable to reproduce the issue on Outlook Desktop. Is there an additional step between opening the new email and calling into the API? Does this only happen with the formatted content being a list or all sorts of HTML content, like say inserting a bold/Italix text?

**Comment by DmitryKostochko** [comment]
>> Is there an additional step between opening the new email and calling into the API?

There are no additional steps - place the cursor anywhere in a message body and execute the code. May it be that you have modified the HTML I provided? If you remove style="margin-left:0cm;" then it starts working, bullets are shown but an extra line is still added. Have you tried this on Outlook for Mac? Maybe you have a different version of Outlook Desktop?

>> Does this only happen with the formatted content being a list or all sorts of HTML content, like say inserting a bold/Italix text?

We noticed this issue only with lists and with style="margin-left:0cm;".

**Comment by DmitryKostochko** [comment]
@exextoc, sorry for bothering you but did you reproduce the issue?

**Comment by exextoc** [comment]
> @exextoc, sorry for bothering you but did you reproduce the issue?

We are still unable to repro this issue fully. However we notice that the last line is not coming in as a list. 

Also can you please update your mac outlook version to the latest one and try this once?

![image](https://user-images.githubusercontent.com/28549921/92562711-08816200-f294-11ea-8fd2-5d73f99b402f.png)

**Comment by DmitryKostochko** [comment]
@exextoc, we have just re-tested the issue on the following configurations:

Microsoft Outlook for Mac Version 16.40 (20081000)
Microsoft Outlook for Mac Version 16.40 (20081201)
Microsoft Outlook Version 2008 (build 13127.20378)

It is reproduced on all 3 configurations, please see a screenshot from Outlook for Mac below:
<img width="311" alt="Screen Shot 2020-09-09 at 10 00 09" src="https://user-images.githubusercontent.com/28924916/92575117-9fe4b600-f290-11ea-9ee9-ce689852c484.png">

Do you need any additional information? Please let me know.

**Comment by exextoc** [comment]
> @exextoc, we have just re-tested the issue on the following configurations:
> 
> Microsoft Outlook for Mac Version 16.40 (20081000)
> Microsoft Outlook for Mac Version 16.40 (20081201)
> Microsoft Outlook Version 2008 (build 13127.20378)
> 
> It is reproduced on all 3 configurations, please see a screenshot from Outlook for Mac below:
> <img alt="Screen Shot 2020-09-09 at 10 00 09" width="311" src="https://user-images.githubusercontent.com/28924916/92575117-9fe4b600-f290-11ea-9ee9-ce689852c484.png">
> 
> Do you need any additional information? Please let me know.

Will it be possible to update the MAC Outlook to the most recent version and then check? We tested at 16.42

**Comment by DmitryKostochko** [comment]
>> Will it be possible to update the MAC Outlook to the most recent version and then check? We tested at 16.42

We don't have access to update 16.42, Office on our Macs does not show a notification about available updates. Moreover, on the page below, update 16.42 is not mentioned either:
https://docs.microsoft.com/en-us/officeupdates/update-history-office-for-mac

Where can we get 16.42? And what about Outlook Desktop on Windows?

**Comment by exextoc** [comment]
Hey @DmitryKostochko ,

Thank you for reporting this issue about Ordered lists in setBody. We can see this issue across both Outlook for Windows and Mac and have added it to our backlog. Unfortunately, we have no timelines to share at this point.

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 16.41 for Mac and build 13231 for Windows or later. Depending on the release channel a customer is on, getting an updated build can take anywhere from 4-8 weeks.
