### ISSUE TITLE
Shared runtime questions

### ISSUE THREAD

**Issue by erharvey** [OfficeDev/office-js#1368]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hello,

I have 2 questions regarding the shared runtime for the excel host.

1)
 I am following this  link to create a custom function used the share runtime:
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime

Unfortunately, I cannot add the "runtimes" element inside the host override tag since it gives me an invalid manifest. Looking at the schema itself ("TaskPaneAppVersionOverridesV1_0.xsd") installed with Visual studio, I do not see any references to the runtime tag. I tried using visual studio 2019 community edition and enterprise (version 16.7.2). 

Where can I get the most recent xsd with visual studio? Am I missing an update or something? ( I can see that the runtime element is indeed available based on the docs https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-owemxml/82e93ec5-de22-42a8-86e3-353c8336aa400)

<VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
  <Hosts>
    <Host xsi:type="Workbook">
    <Runtimes>
      <Runtime resid="ContosoAddin.Url" lifetime="long" />
    </Runtimes>

(

2) 
Is this feature still in preview? I do not see the preview flag anywhere beside the following page:
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/runtime

Thanks

**Comment by AlexJerabek** [comment]
Thanks for the questions @erharvey.

@jeremy-msft or @shaofengzhu, could you help out here?

**Comment by jeremy-msft** [comment]
Hi @erharvey, as we [announced](https://developer.microsoft.com/en-us/microsoft-365/blogs/power-up-with-office-add-ins-build-2020/) at Build 2020, shared runtime is now generally available.  I'm adding @nokafor for your question about the Visual Studio 2019 developer experience.

**Comment by ElizabethSamuel-MSFT** [comment]
@mattgeim Following up on VS 2019 dev experience. Thx.
