### ISSUE TITLE
How to insert Task( or Resource) to project by js api?

### ISSUE THREAD

**Issue by aninfeel** [OfficeDev/office-js#1369]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I have a requirement which is loading tasks from a internal server and then insert all the tasks into ms project. But I cannot find a way to do that by invoking the office add-in api. I have try follow stupid methods but fail:
1、invoke setResourceFieldAsync passing a empty task id。
2、invoke getResourceByIndexAsync passing a empty row index, hoping it return a task id。

**Comment by AlexJerabek** [comment]
Thanks for the questions @aninfeel. I'm sorry you're having issues with the Project APIs.

@JuaneloJuanelo, can you help answer this question?

**Comment by ElizabethSamuel-MSFT** [comment]
@JuaneloJuanelo Any guidance here? Thanks.

**Comment by nnyegaard** [comment]
Hey @aninfeel, there are some documentation around that [here ](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/project-quickstart) if you want more I can provide you with some sample code

**Comment by aninfeel** [comment]
> Hey @aninfeel, there are some documentation around that [here ](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/project-quickstart) if you want more I can provide you with some sample code

Thanks. But I have switched to VSTO for several months.

**Comment by nnyegaard** [comment]
@aninfeel Yeah it feels that is the only option for Project development

**Comment by JBoman32768** [comment]
There is actually an undocumented function that creates tasks in MS Project Desktop.  Seems to work well.

```
Office.context.document.createTaskAsync(callback)
```

**Comment by ElizabethSamuel-MSFT** [comment]
That function is actually documented at https://docs.microsoft.com/javascript/api/office/office.document?view=common-js-preview#office-office-document-getselectedtaskasync-member(1). The [Office.Document object](https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=common-js-preview#methods) has this and other methods that can be used with Project.

**Comment by JBoman32768** [comment]
Ah okay - I missed that.  They should probably consider adding it to the TypeScript @types/office-js package as the TypeScript compiler will actively tell you it doesn't exist.

**Comment by ElizabethSamuel-MSFT** [comment]
@JBoman32768 Actually, it's in the [DefinitelyTyped .d.ts file](https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/office-js/index.d.ts) for the office-js type.

However, I'm not sure about the config for Project on Windows so it's possible the local cache is outdated or something like that.
