### ISSUE TITLE
Context.document.contentControls.getByTag('MyTag') no longer finds nested controls

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js#137]
## Expected Behavior
Details are in this SO question: https://stackoverflow.com/questions/50374193/unable-to-delete-nested-content-controls-in-word-with-office-js

In build 1708, Context.document.contentControls.getByTag('MyTag')  would return all controls with the specified tag, even if they were nested inside another tag. 

## Current Behavior
As of build 1806 1806 10214.20000, controls that are nested in other controls are not returned.

## Steps to Reproduce, or Live Example
1. Create a content control with tag "Outer".
2. Create a content control inside the first one and tag it "Inner".
3. Use the customer's code in the SO question to reproduce. The "Inner" tagged content control is not found.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 1806 1806 10214.20000
* Operating System: Win 10
* Browser (if using Office Online): ______

**Comment by JuaneloJuanelo** [comment]
This issue is non repro in the current builds.

**Comment by Rick-Kirkham** [comment]
@JuaneloJuanelo  I can reproduce on a more recent build: 1806 10215.20003

**Comment by Rick-Kirkham** [comment]
To repro use this gist: https://gist.github.com/Rick-Kirkham/fb2cce670dec338486464a4ddb2702f1
Be sure you have a content control tagged "Outer" and a second content control inside the first one that is tagged "Inner".

**Comment by ElizabethSamuel-MSFT** [comment]
@Rick-Kirkham Can you still repro this? Thanks.

**Comment by Rick-Kirkham** [comment]
@ElizabethSamuel-MSFT No. This doesn't reproduce anymore.
