### ISSUE TITLE
[Outlook ] mobile add-in can not be installed on Exchange 2016

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1370]
When we trying install add-in on mobile end with Exchange 2016. Add-in can not install success.
Any idea?

## Expected Behavior
Add-in can install successful on mobile end with Exchange 2016.

## Current Behavior
Can't see add-in on mobile outlook end.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Android
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 
* Operating System: Android
* Browser (if using Office on the web):

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue @SWei1234. 

@exextoc, can you please investigate?

**Comment by SWei1234** [comment]
Hi @AlexJerabek  and @exextoc 
Thanks for your support. 
Our work around is:
Exchange update to build 15.01.1870.000.
Problem fixed.
Will close this ticket.
