### ISSUE TITLE
[Excel] Office.context.ui.displayDialogAsync method does not work in IE 11 

### ISSUE THREAD

**Issue by bendhayer** [OfficeDev/office-js#1372]
In an Excel add-in, we call displayDialogAsync. In IE, the method does nothing, the dialog window does not show up, the callback is not executed. 

## Expected Behavior
Dialog popup should open.

## Current Behavior
Nothing happens, the dialog window does not show up, the callback is not executed. There is an error in the console: Unable to get property 'length' of undefined or null reference".

## Steps to Reproduce, or Live Example
Just try to use this snippet in an Excel add-in use Excel online in Internet Explorer 11.

```javascript
export function openDialog(): void {
  Office.context.ui.displayDialogAsync(
    'https://docs.microsoft.com/en-us/office/dev/add-ins/reference/javascript-api-for-office',
    { height: 60, width: 40, promptBeforeOpen: false },
    (asyncResult: Office.AsyncResult<Office.Dialog>): void => {
      console.log(asyncResult);
    },
  );
}
```

It's also possible to reproduce it using the Script Lab add-in by following these steps:
1. Start the Script Lab add-in using the "Code" button in the ribbon
2. Click on the "+" icon
3. Click on the icon to edit the code in an other window

**Note:** It seems that the function might work for some user while crashing for the rest. I've had it crashed for 2 users and work for 1 using the same computer and IE 11. I'm not able to see any differences apart from the user account I was using. The add-in work perfectly in all other browser for all users.

## Context
The modal that can't be open is the login modal. This means that our users can't use our add-in while this bug exist.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.13229.35900
* Operating System: Windows 10 Pro 19041.450
* Browser (if using Office on the web): Internet Explorer 11 (11.450.19041.0)

### Our logs

- description: "Unable to get property 'length' of undefined or null reference"
- message: "Unable to get property 'length' of undefined or null reference"
- name: "TypeError"
- number: -2146823281
- stack: 
  >  
  > TypeError: Unable to get property 'length' of undefined or null reference
  > at m (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:106821)
  > at isTargetSubdomainOfSourceLocation (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:112285)
  > at OSF.DDA.WAC.Delegate.openDialog (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:275008)
  > at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:81075)
  > at value (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:251631)
  > 

### Script Lab's logs
```json
Error:
{
    "message": "Unable to get property 'length' of undefined or null reference",
    "description": "Unable to get property 'length' of undefined or null reference",
    "number": -2146823281,
    "stack": "TypeError: Unable to get property 'length' of undefined or null reference\n   at m (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:106821)\n   at isTargetSubdomainOfSourceLocation (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:112285)\n   at OSF.DDA.WAC.Delegate.openDialog (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:275008)\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:81075)\n   at value (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:251631)\n   at t.openPopoutCodeEditor (https://script-lab.azureedge.net/static/js/main.b6aa29e2.chunk.js:1:198405)\n   at Anonymous function (https://script-lab.azureedge.net/static/js/main.b6aa29e2.chunk.js:1:187741)\n   at x (https://script-lab.azureedge.net/static/js/2.17501470.chunk.js:1:3046376)\n   at Anonymous function (https://script-lab.azureedge.net/static/js/2.17501470.chunk.js:1:3046185)\n   at e[t] (https://script-lab.azureedge.net/static/js/2.17501470.chunk.js:1:3046570)",
    "sagaStack": "at Ql \n at Ql \n at l \n at Fl \n TypeError: Unable to get property 'length' of undefined or null reference\n   at m (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:106821)\n   at isTargetSubdomainOfSourceLocation (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:112285)\n   at OSF.DDA.WAC.Delegate.openDialog (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:275008)\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:81075)\n   at value (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:26:251631)\n   at t.openPopoutCodeEditor (https://script-lab.azureedge.net/static/js/main.b6aa29e2.chunk.js:1:198405)\n   at Anonymous function (https://script-lab.azureedge.net/static/js/main.b6aa29e2.chunk.js:1:187741)\n   at x (https://script-lab.azureedge.net/static/js/2.17501470.chunk.js:1:3046376)\n   at Anonymous function (https://script-lab.azureedge.net/static/js/2.17501470.chunk.js:1:3046185)\n   at e[t] (https://script-lab.azureedge.net/static/js/2.17501470.chunk.js:1:3046570)"
}
```

**Comment by AlexJerabek** [comment]
Thanks for reporting this @bendhayer. 

@lliu113, could you please investigate this?

**Comment by ElizabethSamuel-MSFT** [comment]
@lliu113 Any update on this? Thx.

**Comment by v-pidoplichko** [comment]
@lliu113 we're facing the same issue, do you have any updates or any workaround?

**Comment by lliu113** [comment]
@bendhayer @v-pidoplichko - sorry for the late response, thanks for your patience on this. I tried reproing this on IE 11 in Excel Online and the dialog is launching correctly. I used the snippet provided by @bendhayer. 

Can you confirm whether this is still reproing?

**Comment by lliu113** [comment]
@bendhayer, @v-pidoplichko - I'm going to go ahead and close this issue, hoping this is no longer reproing. Please reactivate if this is still a problem and we will look into this. 
Thanks!
