### ISSUE TITLE
OneNote: Fetching contents of non-active page

### ISSUE THREAD

**Issue by msiemens** [OfficeDev/office-js#1373]
## Expected Behavior

Using the OneNote API to fetch the page contents of a non-active page should succeed.

## Current Behavior

An error is thrown:

```
RichApi.Error: Accessing page contents of inactive page is not allowed
```

Either this error should not happen _or_ – if intended – this should be documented in the OneNote API documentation.

## Steps to Reproduce

```
const section = context.application.getActiveSection();
section.pages.load();
await context.sync();

const page = section.pages.getItem(5); // In this example the page with index 5 is NOT active
page.contents.load();
await context.sync();

page.contents.load();
```

## Your Environment

* Platform: Office on the web Add-In using the [Yo Office generator](https://github.com/OfficeDev/generator-office)

**Comment by AlexJerabek** [comment]
Thanks for reporting this @msiemens. 

@JuaneloJuanelo, could you please help investigate this OneNote issue or find the right owner?

**Comment by ElizabethSamuel-MSFT** [comment]
@msiemens The OneNote page does need to be active for fetching page content to succeed - see https://docs.microsoft.com/office/dev/add-ins/onenote/onenote-add-ins-page-content#accessing-page-contents.

If you would like to see support added for getting the content of non-active OneNote pages, please upvote or request a feature on [UserVoice](https://officespdev.uservoice.com/).

Thanks.
