### ISSUE TITLE
Office.EventType.DialogMessageReceived is not working in Outlook 2019 (but OWA is OK)

### ISSUE THREAD

**Issue by fisherwei** [OfficeDev/office-js#1375]
taskpane.html open a new dialog preview.html by click a button,
preview.html has two button: cancel and apply, both of them will send `"dialogClosed"` by `Office.context.ui.messageParent` to host page,
it is work fine in OWA(chrome), but in outlook 2019, close action does not any response.

## Expected Behavior
close dialog window

## Current Behavior
no response in outlook 2019

## Steps to Reproduce, or Live Example
open dialog by
```
      function preview(index) {
        var Office = window.Office;
        var host = window.location.href
          .split("/")
          .slice(0, 3)
          .join("/");
        var dialog;
        Office.context.ui.displayDialogAsync(
          host + "/preview.html?index=" + index,
          { height: 48, width: 64, displayInIframe: true },
          function(asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Failed) {
              console.log((asyncResult.error.code = ": " + asyncResult.error.message));
            } else {
              dialog = asyncResult.value;
              dialog.addEventHandler(Office.EventType.DialogMessageReceived, function(arg) {
                var messageFromDialog = JSON.parse(arg.message);
                if (messageFromDialog.messageType === "dialogClosed") {
                  dialog.close();
                  if (messageFromDialog.index >= 0) {
                    console.log(messageFromDialog.index);
                  }
                }
              });
            }
          }
        );
      }
```
close dialog by:
```
      function closeButtonClick(status) {
        var Office = window.Office;
        var messageObject = { messageType: "dialogClosed", index: status ? index : -1 };
        var jsonMessage = JSON.stringify(messageObject);
        Office.context.ui.messageParent(jsonMessage);
      }
```

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: pc
* Host [Excel, Word, PowerPoint, etc.]: 
* Office version number: outlook 2019 version 1808 build 10366.20016, Exchange 2016 CU12 OWA
* Operating System: windows 10 1909
* Browser (if using Office on the web): chrome

**Comment by AlexJerabek** [comment]
Thanks for reporting this @fisherwei. 

@lliu113, could you please help investigate this dialog issue?

**Comment by fisherwei** [comment]
additional info:
office js is
<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>

**Comment by fisherwei** [comment]
i have resolved this issue, it is not a bug in office-js,
cause just is outlook 2019 used IE11, something js feature cannot work fine.
