### ISSUE TITLE
unable to call a function once all the data has been retrieved and call a python API inside outlook add-in

### ISSUE THREAD

**Issue by LovikaJain** [OfficeDev/office-js#1379]
I am trying to get the subject, email Ids, and pass them in a function once the values are retrieved. How do I check if the values have been already picked? Once that is done I am trying to call a python API inside outlook add-in. I tried using ajax and XMLHttpRequest but unable to trigger the API from outlook add-in.

The code is mentioned below used for calling the API:

`function sendEmail(recipients, cc, bcc, sub, start, end) {
  var xhr = new XMLHttpRequest();
  write("<br/>Inside Send Email<br/>");
  var payload_data = JSON.stringify({
    "torecipients": recipients,
    "ccrecipients": cc,
    "bccrecipients": bcc,
    "subject" : sub,
    "startTime" : start,
    "endTime" : end
  });

  write("<br/> payload_data:" + payload_data + "<br/>")
  
  $.ajax({
    url: 'https://127.0.0.1:5895/meeting',
    data : payload_data,
    type : 'POST',
    error: function(xhr, status, error) {
      write("Error" + error);
    }
  }).done(function(dataa) {
    write("Data:" + data);
  })`

**Comment by AlexJerabek** [comment]
Thanks for reporting this @LovikaJain. 

@keyur32, is this something you can investigate?

**Comment by AlexJerabek** [comment]
Reassigning to @exextoc.

**Comment by exextoc** [comment]
Hello @LovikaJain Can you please mention on which platform are you trying this? Is this Win32, Mac, Outlook on the Web or mobile?

**Comment by LovikaJain** [comment]
I am trying on outlook on the web

**Comment by exextoc** [comment]
Hey @LovikaJain ,

Can you please share the logs on the console or debugger (in the browser inspector) after the add-in runs? That can help us debug what might be going wrong.
