### ISSUE TITLE
displayDialogAsync Crash after last Word Update (Beta, Build 13304.200000)

### ISSUE THREAD

**Issue by MarcEichenberger** [OfficeDev/office-js#1380]
Since Office update yesterday, displayDialogAsync crashes after OAuth-Login redirect.

## Steps to Reproduce, or Live Example
Office.context.ui.displayDialogAsync with oauth-url
Login
OAuth-Login-Redirect crashes "displayDialogAsync-Window"

## Your Environment

* Platform PC desktop
* Host: Word
* Office version number: Build 13304.200000 Beta
* Operating System: Windows

![image](https://user-images.githubusercontent.com/31311384/92716968-cf162880-f35f-11ea-9070-99ba29546ae0.png)

No LOG available.

**Comment by AlexJerabek** [comment]
Thanks for reporting this @MarcEichenberger. 

@lliu113, can you please investigate this Dialog issue?

**Comment by MarcEichenberger** [comment]
Update: Same problem occours if we do the oauth - login in the pane. After Login, http-redirect crashes the pane:

![image](https://user-images.githubusercontent.com/31311384/92890434-68ecdc80-f417-11ea-95f8-720a87712597.png)

In the browser (Word Online) everything works as expected.

**Comment by MarcEichenberger** [comment]
Update: It looks like the "POST" - Request at login already crashes the browser. The POST-Request (Login-Button click) arrives (localhost), but the browser is already crashed.

**Comment by MarcEichenberger** [comment]
The bug is partly on our site. When I press "Enter" to login, 2 POST requests are sent. The first one is "canceled", which causes the browser to crash. If only 1 POST is sent, everything works.

**Comment by ElizabethSamuel-MSFT** [comment]
> The bug is partly on our site. When I press "Enter" to login, 2 POST requests are sent. The first one is "canceled", which causes the browser to crash. If only 1 POST is sent, everything works.

@MarcEichenberger It seems like you were able to resolve this issue? Thx.

**Comment by MarcEichenberger** [comment]
@ElizabethSamuel-MSFT : Yes, i will close the issue. Thx.
