### ISSUE TITLE
Excel. Custom functions do not support full CORS when running in a shared JavaScript runtime. Throws Network request failed

### ISSUE THREAD

**Issue by cghaddar** [OfficeDev/office-js#1383]
I configured my Excel add-in to use a shared JavaScript runtime as described here 
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime

I am able to call the Office.js API but if I try to make a POST request from a custom function it throws Network request failed.
It only works with same origin or  a simple GET.  This contradicts the claim: Your custom functions will have full CORS support stated here
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview

## Expected Behavior

POST request should work with full CORS

## Current Behavior

fails to complete a POST with either fetch or XMLHttpRequest.   throws Network request failed

## Steps to Reproduce, or Live Example

* Link to live example: ______

Use the following  code examples in a custom function (verified to work when invoked outside custom functions)  
//USING FETCH  always throws Network request failed
fetch('https://mysite.com', {
    method: 'POST', 
    headers: {
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(data)
  })
  .then(response => response.json())
  .then(data => {
    console.log('Success:', data);
  })
  .catch((error) => {
    console.error('Error:', error);
    throw error;
  });

or this alternative code.  xhttp.status comes back always 0
let xhttp = new XMLHttpRequest();
  return new Promise(function (resolve, reject) {
    xhttp.open('POST', 'https://mysite.com', true);
    xhttp.setRequestHeader('Content-Type', 'application/json');
    xhttp.send(JSON.stringify(data));
    xhttp.onreadystatechange = function () {
      if (xhttp.readyState !== 4) return;
      if (xhttp.status == 200) {
        resolve(JSON.parse(xhttp.responseText).result);
      } else {
        reject({
          status: xhttp.status,
          statusText: xhttp.statusText
        });
      }
    };
  }); 

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

Tested this on Windows 10  Version	10.0.18363 Build 18363. with OFFICE 365 VERSION 2007 build 13029.20344

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Another issue I am having to be filed separately is that console.log does not seem to work in shared run time. I have enabled logging but non of my custom logs are showing in the generated log file.

**Comment by ElizabethSamuel-MSFT** [comment]
@RuoyingLiang Can you take a look at this custom functions issue? Thx.

**Comment by cghaddar** [comment]
Attempts to do a cross-origin post in shared run time are failing with either Network request failed or status 0 (depending on the method used). I am not even able to post to https://login.microsoftonline.com get access token for SSO on  the client side. I added the following to the manifest file (back slash added just to show tag in this post)

\<AppDomains>
   \<AppDomain>https://login.microsoftonline.com/<\AppDomain>
\</AppDomains>

//but had no effect.  The only successful work around for now is to do any cross-origin posts on the server side.   Looks like there are multiple reports about this same issue .

**Comment by suresh-anumolu** [comment]
Hi, Do you have any update on this issue? We are still facing the issues with CORS, same works on excel -web .

Thanks
Suresh

**Comment by suresh-anumolu** [comment]
Hi, do you have any update on this issue? I am facing same issue on my end.. any help on this would be appreciated.

**Comment by CristovaoTorres** [comment]
I am facing same issue on my end. Any news?

**Comment by AlexJerabek** [comment]
Adding @grangeryy to help investigate.

**Comment by CristovaoTorres** [comment]
Any news?

**Comment by grangeryy** [comment]
Adding @jeremy-msft to help.

**Comment by jeremy-msft** [comment]
Thanks for reporting this issue.  We're currently investigating and will let you know once we have more information.

**Comment by jeremy-msft** [comment]
@suresh-anumolu, @CristovaoTorres -- we were unable to repro this problem.  Full CORS is working fine on our end.   Can you please reverify that you have configured shared runtime correctly?  A simple test would be to ensure you can share a variable between a custom function and task pane.  If that's working, would you be able to share a sample manifest that repros this issue?

**Comment by grangeryy** [comment]
Close this with no repro. Please feel free to reopen it once the issue happens again. Thx!

**Comment by Zegoverno** [comment]
anyone could get around this problem? I am facing it too
