### ISSUE TITLE
[Outlook ] custom properties disappeared on Mac shared calendar

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1385]
This a problem happening recently. I have met this problem on both 'production' version and 'Inside fast' version.
Production version is 16.40(20081000)
Insider fast version is 16.41 (20083005)
related api :
Office.context.mailbox.item.loadCustomPropertiesAsync

## Expected Behavior
Add-in can save custom properties successfully on Mac Outlook client.

## Current Behavior
The properties will disappear after about one minutes. And this problem only happened on Mac Outlook shared calendar.

## Steps to Reproduce, or Live Example
1. open an add-in then save some thing to custom properties.
2.Save or send this ,open it after one or two minutes. The twice or third time open. The properties will disappear.

I have already make sure the delegate permission is enough.

## Context
The meeting we scheduled by add-in can not be edit any more. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.41 (20083005)
* Operating System: 15.5
* Browser (if using Office on the web): ______

This problem have a big effect on add-in . Any request please let me know.
Thanks

**Comment by exextoc** [comment]
Hey @SWei1234 ,

Unfortunately, we are unable to reproduce this issue.

To be clear about the repro steps:
1. We open a new appointment on a Shared Calendar in Outlook for Mac Client.
2. In the Appointment compose, we launch an add-in which sets and saves Custom Properties (using saveAsync) to the appointment.
3. We save/send the appointment.
4. We reopen the appointment and check for custom properties for the add-in after a certain amount of time.

If I understand these steps correctly, I am unfortunately unable to see this issue. Is this happening for any randomly generated custom properties (can you once try this in the setup where you see this issue?) or is there a specific property you're seeing this issue with? If you could share a code snippet where you see this happen, that would be helpful.

**Comment by SWei1234** [comment]
Hi @exextoc 
Sorry for reply delay. 
This is happened on some user's PC but it works fine on other users.  Just want to know is there any thing we can try to solve this?
Or any idea about this?
Thanks

**Comment by exextoc** [comment]
Unfortunately, we cannot reproduce this and don't have enough information to investigate it further.

1. Can you confirm the repro steps in our previous response?
2. Are you seeing this bug in "New Outlook" or the old one?

**Comment by SWei1234** [comment]
Hi @exextoc 
Your steps  is exactly what we met. 
We seeing this bug on the old one.
Thanks

**Comment by exextoc** [comment]
@SWei1234 we are trying to understand this issue better. Is this happening for specific accounts across devices (the same account installed on multiple devices reproduces the same bug)? Or is it happening on particular devices irrespective of accounts (bug reproduces for multiple accounts on the same device)?

**Comment by SWei1234** [comment]
Hi @exextoc 
This seems happened on particular  devices and only happened on Mac Outlook client.
Sorry for reply late.
Thanks

**Comment by exextoc** [comment]
@SWei1234 When this issue repros can you check if you are able to get the custom properties for same meeting/appointment from Outlook on Web? This will help us ensure whether custom properties are set properly.

**Comment by SWei1234** [comment]
@exextoc Sure, I will update here as soon as I got the result. Thanks for your support.

**Comment by SWei1234** [comment]
Will update here result. Please don't close this ticket.
