### ISSUE TITLE
Ribbon Api  throw ApiNotAvailabe

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#1386]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior

ribbon button can disable or enable

## Current Behavior

https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands
we use this ,but it throw ApiNotAvailabe
we use Office.context.requirements.isSetSupported('RibbonApi', '1.1')  it return true

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: _____pc desktop_
* Host [Excel, Word, PowerPoint, etc.]: ___excel__365_
* Office version number: _version 2008, build 13127_____
* Operating System: __windows____
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by pkkj** [comment]
Hi @dinglicoding, Ribbon API requires shared runtime defined in the manifest. Would you like to check out the "Shared runtime required" section in the "Enable and Disable Add-in Commands" document? It has detail info for shared runtime. Thanks.

**Comment by dinglicoding** [comment]
Hi @pkkj,  I have add <Runtime resid="Contoso.SharedRuntime.Url" lifetime="long" /> , but it still throw ApiNotAvailabe . Can you provide a demo of this manifest. thank you

**Comment by ElizabethSamuel-MSFT** [comment]
@preethikakiru Can you take a look and reassign as needed? Thanks.
