### ISSUE TITLE
External requests blocked due to Content Security Policy issue

### ISSUE THREAD

**Issue by SanketDG** [OfficeDev/office-js#1388]
We are developing Outlook Web Addin. 

To achieve our desired functionality, we are making HTTP Requests to our backend servers from our addin.

This works fine when using the `MessageReadCommandSurface` `ExtensionPoint` where we are showing  a taskpane.

However, when we try to use `MessageComposeCommandSurface`, and we use the following manifest snippet inside it:

```xml
<Action xsi:type="ExecuteFunction">
   <FunctionName>functionName</FunctionName>
</Action>
```

This `functionName` is actually defined in a `js` file, which is called from the HTML file (this is defined as a `FunctionFile` in the manifest)

Here, again, we are making HTTP request to our backend server

Now, we are facing the following error in the browser console:

```
[Report Only] Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'nonce-I193+SQXP9Xe6RXcQym8Mw==' *.res.office.com *.res.office365.com *.cdn.office.net *.cdn.partner.outlook.cn owassets.azureedge.net *.blob.core.windows.net outlookdev.azureedge.net wss://*.delve.office.com:443 shellprod.msocdn.com amcdn.msauth.net amcdn.msftauth.net *.bing.com *.skype.com *.skypeassets.com *.delve.office.com *.cdn.office.net *.cdn.partner.outlook.cn static.teams.microsoft.com *.arkoselabs.com fabriciss.azureedge.net *.googleapis.com teams.microsoft.com 'report-sample' 'self' 'unsafe-inline' 'unsafe-eval' *.yammer.com". Note that 'unsafe-inline' is ignored if either a hash or nonce value is present in the source list.
```

We have inspected the console and we have found out that the first request to our backend server is being blocked to our server because of some CSP condition.

## Expected Behavior
The browser would not be prevented from making HTTP requests to our backend server.

## Current Behavior
The HTTP requests are blocked to our backend server.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
- Host [Excel, Word, PowerPoint, etc.]: Outlook
- Office version number: Microsoft Outlook for Office 365 MSO (16.0.12527.20260) 64-bit
- Operating System: Window 10
* Browser (if using Office on the web): Mozilla Firefox 80.0 | Chrome Version 84.0.4147.105 (Official Build) (64-bit)

## Useful logs

- [ ] Console errors
- [x] Screenshots

<img width="1440" alt="csp-browser-console" src="https://user-images.githubusercontent.com/8980971/93220696-7c3ad780-f78a-11ea-91e2-4fe6f3ced70e.png">

<img width="834" alt="csp-compose-pane" src="https://user-images.githubusercontent.com/8980971/93220721-8361e580-f78a-11ea-98f7-965ae9d1840f.png">

- [x] Test file (if only happens on a particular file)

CC @mihirsn @ankitsurkar @shubhashishtiwari

**Comment by exextoc** [comment]
Hey @SanketDG,

Can you share a small code snippet of the API that you're trying to run? An even more helpful way would be to share the manifest of your add-in so that we can see what the problem is.

**Comment by SanketDG** [comment]
We have since realized that this issue was happening for entirely some other reason.

Closing.

**Comment by CNANDAN** [comment]
@SanketDG Same here, My extension point is **AppointmentOrganizerCommandSurface** it works perfectly in local but when I try to access it through apache getting an error saying **Refused to run javascript URL**.

Attached an image for reference, any help would be appreciated.

![image](https://user-images.githubusercontent.com/38749220/122370391-a66d3000-cf7c-11eb-9ba3-00ef67b89b76.png)
