### ISSUE TITLE
Word: IsSetSupported("PdfFile") not reliable on iPad

### ISSUE THREAD

**Issue by cattermo** [OfficeDev/office-js#1391]
I have a problem with `isSetSupported("PdfFile")` returning true on Word on iPad. The documentation says clearly that it is not supported https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=word-js-preview. 

## Expected Behavior
isSetSupported("PdfFile") should return false on hosts that does not support getting the file as PDF.

## Current Behavior
`isSetSupported("PdfFile")` returns true for Word on iPad but when trying to use getFileAsync("pdf",...) one gets Internal error

## Context
I wanted to get the file as Pdf when possible but since `isSetSupported("PdfFile")` is not reliable I will have to get it as "Compressed" always instead.

I have not tried this on all supported iPad apps but please check all when you do fix it.

**Comment by AbidRahman-MSFT** [comment]
Hey @cattermo - thank you for reporting this issue and apologies for the delay in response. 

@sumurthy and @AlexJerabek - there looks to be a conflict in terms of the supported file types for Word on iPad for the getFilesAsync API call.

PDF files ARE supported for Word on iPad in the following Requirement Set documentation for PDFs: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/office-add-in-requirement-sets#pdffile 

PDF files ARE NOT supported for Word on iPad in the following API documentation for getFileAsync:
https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=word-js-preview#getFileAsync_fileType__options__callback_ 

Here's the relevant chart from the above webpage:
![image](https://user-images.githubusercontent.com/53581099/115291820-0d4fa380-a10a-11eb-8976-db0d1226942e.png)

Which one is the correct documentation?

**Comment by AlexJerabek** [comment]
@AbidRahman-MSFT, Thanks for

**Comment by AlexJerabek** [comment]
(Sorry for the accidental close. Blame the cat on my keyboard.)

According to the [requirement set source of truth](https://github.com/OfficeDev/Office-Js-Requirement-Sets/blob/master/mapping/requirements_officejs.json), the `PdfFile` requirement set is supported by Word on iPad. However, @cattermo, you're seeing errors when trying to actually use `getFileAsync`, correct?

**Comment by cattermo** [comment]
> (Sorry for the accidental close. Blame the cat on my keyboard.)
> 
> According to the [requirement set source of truth](https://github.com/OfficeDev/Office-Js-Requirement-Sets/blob/master/mapping/requirements_officejs.json), the `PdfFile` requirement set is supported by Word on iPad. However, @cattermo, you're seeing errors when trying to actually use `getFileAsync`, correct?

Correct. I got an error without any detailed message so I gave up after that. This was in September last year and I haven't tried it since.

**Comment by AlexJerabek** [comment]
Thank you @cattermo. @AbidRahman-MSFT, are you able to repro the behavior of `getFileAsync` on iPad?

**Comment by AlexJerabek** [comment]
Just to update the thread, it looks like PDFs are not supported for Word on iPad. We are working on changing the return for `isSetSupported("PdfFile")` to reflect that. We are also updating the documentation accordingly in https://github.com/OfficeDev/office-js-docs-pr/pull/2647.

**Comment by AlexJerabek** [comment]
Closing because the documentation updates have been made.
