### ISSUE TITLE
ItemId on shared calendar item is empty

### ISSUE THREAD

**Issue by bx-anil** [OfficeDev/office-js#1394]
ItemId on Shared Calendar is not available when the shared calendar is from a mailbox in a different region

## Expected Behavior
ItemId on shared calendar item should be available if the calendar was shared with delegate/edit permissions even if the mailboxes are on different region.

## Current Behavior
There is no ItemId on shared calendar item when the shared mailbox is in a different region

## Steps to Reproduce, or Live Example
1. On Multi-Geo setup of Office 365, share a calendar to a user on different region
2. e.g. When a user with mailbox in APAC that shares calendar with a user who's mailbox is NAM with delegate/write access.
3. Open the APAC user shared calendar item from NAM user's Outlook desktop. 
4. Outlook.context.mail.item.itemId is undefined.

![image](https://user-images.githubusercontent.com/52792802/93629333-1d59a600-f9b6-11ea-87d5-3c012de5d0e9.png)

![image](https://user-images.githubusercontent.com/52792802/93629347-22b6f080-f9b6-11ea-86bf-2aad46a40b66.png)

payload json: 
[0,[[1,1],"{\"hostVersion\":\"16.0.12325.20298\", \"itemType\":5, \"permissionLevel\":2, \"userEmailAddress\":\"Anil.Srikantham@Blackstone.com\", \"userDisplayName\":\"<REDACTED>\", \"userProfileType\":\"office365\", \"conversationId\":null, \"userTimeZone\":\"Eastern Standard Time\", \"ewsUrl\":\"https://outlook.office365.com/EWS/Exchange.asmx\", \"restUrl\":\"https://outlook.office.com/api\", \"isFromSharedFolder\":true, \"shouldRunNewCodeForFlags\":1, \"seriesId\":\"<REDACTED>\", \"itemNumber\":39}"]]

Let me know if you need additional details.

**Comment by exextoc** [comment]
@bx-anil On which Outlook platform(s) do you see this behavior (i.e. Outlook on Windows, Outlook on Mac, or OWA)?

Also, which version of Outlook is the user using?

**Comment by bx-anil** [comment]
Sorry, I missed that information. This is on Outlook Desktop v1912, v2002 and v2007 on Windows 10 v1809 and v1909. Also on OWA (Chrome v84) we cannot open the shared calendar meeting item. Double clicking on the item doesn't work.

**Comment by exextoc** [comment]
Here's something to check on Outlook Desktop on Windows. If the owner of the shared calendar created the meeting, the add-in with open in **organizer** mode and the item id will be returned by [saveAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.appointmentcompose?view=outlook-js-1.8&preserve-view=true#saveasync-options--callback-). If the calendar's owner is an **attendee** of the meeting, only then will Outlook.context.mail.item.itemId be defined.

**Comment by bx-anil** [comment]
The meeting was not opened as an organizer but as an attendee. The nuances of organizer and attendee mode are already taken care of and everything works on regular calendar and if the shared calendar is from the same region.

**Comment by exextoc** [comment]
Thank you for reporting this issue. This has been put in our backlog. We unfortunately have no timelines to share at this point.
Internal tracking id: Office:4501807

**Comment by exextoc** [comment]
We are not able to reproduce the same on OWA. Do you see any error on console when you perform the above ?

**Comment by bx-anil** [comment]
Here is the exception on OWA: 
Uncaught (in promise) Error: [fetchFullCalendarEvent] Action source:DeeplinkShowReadingPane_Deeplink with error: [getCalendarEventService] request failed. Message: The specified object was not found in the store., Can't connect to the mailbox of user Mailbox database guid: 161c3ef3-335a-40ea-a05c-7b10e178b691 because the ExchangePrincipal object contains outdated information. The mailbox may have been moved recently., ResponseCode: ErrorItemNotFound, ResponseClass: Error
    at fetchFullCalendarEvent.ts:501
    at VM1567 AAMkAGE0MGU0YWY4LTlhNWItNDg4MS1iNGI4LTdhZGQ3NzUwNDNkZgFRAAgI2G%2FUGApAAEYAAAAAQ9JtW26jTUevHHNtPKhbqwcALEj%2FZFp9xk2opv7MToMZ%2FwAAAC%2F2uQAAAJGOX9MCIkuXIQZyTQIPRAEVRLwMKAAAEA%3D%3D:347
    at Object.next (VM1567 AAMkAGE0MGU0YWY4LTlhNWItNDg4MS1iNGI4LTdhZGQ3NzUwNDNkZgFRAAgI2G%2FUGApAAEYAAAAAQ9JtW26jTUevHHNtPKhbqwcALEj%2FZFp9xk2opv7MToMZ%2FwAAAC%2F2uQAAAJGOX9MCIkuXIQZyTQIPRAEVRLwMKAAAEA%3D%3D:347)
    at a (VM1567 AAMkAGE0MGU0YWY4LTlhNWItNDg4MS1iNGI4LTdhZGQ3NzUwNDNkZgFRAAgI2G%2FUGApAAEYAAAAAQ9JtW26jTUevHHNtPKhbqwcALEj%2FZFp9xk2opv7MToMZ%2FwAAAC%2F2uQAAAJGOX9MCIkuXIQZyTQIPRAEVRLwMKAAAEA%3D%3D:347)
    at actionWrappers.js:27
    at action.js:22
    at i (legacyApplyMiddleware.js:27)
    at t.promiseMiddleware (App.css?006e:7)
    at t.stitch (stitch.js:6)
    at y (DatapointMiddleware.ts:180)

**Comment by exextoc** [comment]
We are still not able to repro the issue on OWA. Could  you please provide us with Test Accounts with which we can repro the issue from our side?

**Comment by bx-anil** [comment]
I'm assuming the exception stack wasn't helpful.

**Comment by bx-anil** [comment]
Please ignore the OWA issue. We don't see the issue on OWA anymore. 
But on Outlook desktop its still an issue.

**Comment by exextoc** [comment]
We have fixed the bug for Outlook Desktop and the fix should be available in build 16.0.13423.10000 or later. When an updated build is available depends on the release channel a customer is on.
