### ISSUE TITLE
Runtime logging from custom functions  in shared runtime with console.log() does not work

### ISSUE THREAD

**Issue by cghaddar** [OfficeDev/office-js#1396]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I followed the instructions to enable runtime logging given here using both npx and registry RuntimeLogging key
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging

The custom functions are running in shared runtime environment. The log file gets created but non of the console.log() messages from custom functions are ever written to the output log.

## Steps to Reproduce, or Live Example

* Link to live example: ______

Use the example add-n given here
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime
Throw in console.log("this a test log") in any of the custom functions. Nothing shows in output log 

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______PC desktop
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______2007 build 13029.20344
* Operating System: ______Windows 10 Version 10.0.18363 Build 18363
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by xiaochunms** [comment]
@cghaddar in shared runtime case, the log will go to console of browser debugging tools instead of Runtime logging.

**Comment by ElizabethSamuel-MSFT** [comment]
@grangeryy Any update here? Thx.

**Comment by cghaddar** [comment]
@xiaochunms  I start excel with the add-in loaded, (64bit) then I launch  C:\Windows\SysWOW64\F12\IEChooser.exe. However, it displays an empty pane with no targets to debug or any setting to adjust.

**Comment by AlexPhilippov** [comment]
@xiaochunms, we faced the same issue. IEChooser.exe displays log messages in our case but there is a catch. It's not displaying log messages that were posted before IEChooser was loaded. So now there is basically no opportunity to get debug information for custom functions loading for Excel desktop.

**Comment by grangeryy** [comment]
@jeremy-msft  not sure if you know more about this.

**Comment by jeremy-msft** [comment]
Adding @madhavagrawal17 per related issue #1568
