### ISSUE TITLE
Android Outlook Add-in not support security verify with Android Intune App

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#1397]
When user open the security verify with Intune App, they can't login in though Outlook Add-in.
it seams that the two app can’t communicate with each other.

here is a step for reproduce this problem:
[Fail Step.docx](https://github.com/OfficeDev/office-js/files/5253340/Fail.Step.docx)

and here is the configure for the CA Policies:
[CA Policies Configure.docx](https://github.com/OfficeDev/office-js/files/5253342/CA.Policies.Configure.docx)

**Comment by exextoc** [comment]
Hi @hello-chenchen , we are unable to reproduce this on our end. Is it possible for us to get a test account where this bug is reproduced? If so, can you email account details to admin@a830edad9050849405E20081103.onmicrosoft.com?

**Comment by hello-chenchen** [comment]
hi @exextoc it seams our customer have try working with microsoft relate teams already. so will close this issue, thanks.
