### ISSUE TITLE
Unable to Pin the TaskPane

### ISSUE THREAD

**Issue by inderjitkr** [OfficeDev/office-js#1398]
I want to Pin my Outlook Add-Ins to maintain the Persistency and Consistency while it is being used.

I want to pin my Task pane so that while navigating to others mail it should remain open.

I got some support code to Pin the task pane from Microsoft Doc but not working.
I used <SupportsPinning> tag as option 'true'. It supposed to Work as per Microsoft but showing Version Overrides issue.

LINK - https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/pinnable-taskpane

Environment
 Platform - Visual CSharp and JQuery
 Host - Microsoft Outlook Exchange
<img width="337" alt="OutlookError" src="https://user-images.githubusercontent.com/42667183/93766187-aaf5f980-fc33-11ea-8a14-b28b08da0143.png">

 Operating System - Windows 10
 Office version number: Microsoft 365 outlook web version
 Browser Google Chrome

## Useful logs
This app can't be installed. The manifest file doesn't conform to the schema definition. The element 'Action' in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides' has invalid child element 'SupportsPinning' in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides'...

**Comment by exextoc** [comment]
Hi @inderjitkr , are you sure you're adding the SupportsPinning tag under Version Overrides 1.1, and not 1.0? Can you give a link / copy of your manifest so we can take a look at it?

**Comment by inderjitkr** [comment]
Hi, I tried adding both places under 1.0 and 1.1 version overrides but
it didn't worked and showing error. I want to add pin in the outlook
Add-Ins. Please help me.

PFA...

Thanks and Regards
InderJit Kumar

<?xml version="1.0" encoding="UTF-8"?>

<OfficeApp 
          xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" 
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" 
          xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0"            
          xsi:type="MailApp">

  

  
  <Id>0de0b3c9-4db3-4d9f-ae83-3de6d93423be</Id>

  
  <Version>1.0.0.0</Version>
  <ProviderName>OutlookCRM</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  
  <DisplayName DefaultValue="OutlookCRM" />
  <Description DefaultValue="OutlookCRM"/>
  

  <SupportUrl DefaultValue="http://www.contoso.com" />
  
  <AppDomains>
    <AppDomain>AppDomain1</AppDomain>
    <AppDomain>AppDomain2</AppDomain>
    <AppDomain>AppDomain3</AppDomain>
  </AppDomains>
  
  
  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.1" />
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:44307/MessageRead.html"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteItem</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>

  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Requirements>
      <bt:Sets DefaultMinVersion="1.3">
        <bt:Set Name="Mailbox" />
      </bt:Sets>
    </Requirements>
    <Hosts>
      <Host xsi:type="MailHost">

        <DesktopFormFactor>
          
          <FunctionFile resid="functionFile" />

          
          <ExtensionPoint xsi:type="MessageReadCommandSurface">
            
            <OfficeTab id="TabDefault">
              
              <Group id="msgReadGroup">
                <Label resid="groupLabel" />
                
                <Control xsi:type="Button" id="msgReadOpenPaneButton">
                  <Label resid="paneReadButtonLabel" />
                  <Supertip>
                    <Title resid="paneReadSuperTipTitle" />
                    <Description resid="paneReadSuperTipDescription" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="icon16" />
                    <bt:Image size="32" resid="icon32" />
                    <bt:Image size="80" resid="icon80" />
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="messageReadTaskPaneUrl" />
                    <SupportsPinning>true</SupportsPinning>
                  </Action>
                </Control>
                
              </Group>
            </OfficeTab>
          </ExtensionPoint>
          
        </DesktopFormFactor>
      </Host>
    </Hosts>

    <Resources>
      <bt:Images>
        <bt:Image id="icon16" DefaultValue="https://localhost:44307/Images/icon16.png"/>
        <bt:Image id="icon32" DefaultValue="https://localhost:44307/Images/icon32.png"/>
        <bt:Image id="icon80" DefaultValue="https://localhost:44307/Images/icon80.png"/>
      </bt:Images>
      <bt:Urls>
        <bt:Url id="functionFile" DefaultValue="https://localhost:44307/Functions/FunctionFile.html"/>
        <bt:Url id="messageReadTaskPaneUrl" DefaultValue="https://localhost:44307/MessageRead.html"/>
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="groupLabel" DefaultValue="My Add-in Group"/>
        <bt:String id="customTabLabel"  DefaultValue="My Add-in Tab"/>
        <bt:String id="paneReadButtonLabel" DefaultValue="Display all properties"/>
        <bt:String id="paneReadSuperTipTitle" DefaultValue="Get all properties"/>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="paneReadSuperTipDescription" DefaultValue="Opens a pane displaying all available properties. This is an example of a button that opens a task pane."/>
      </bt:LongStrings>
    </Resources>
 
  </VersionOverrides>
  
  
  
   <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1"> 
     <Action xsi:type="ShowTaskpane">
        <SourceLocation resid="messageReadTaskPaneUrl" />
        <SupportsPinning>true</SupportsPinning>
       </Action>
   </VersionOverrides>

  

</OfficeApp>

**Comment by exextoc** [comment]
@inderjitkr The "Action" element cannot occur directly as a child to the VersionOverrides element. It should be under "Group" or "Menu". In your manifest, you should copy the entire part under "VersionOverrides1_0" into "VersionOverrides1_1", and make further changes (adding the SupportsPinning tag), instead of just adding parts that you want to override.

When VersionOverrides1_1 is supported by the client, it will completely ignore the VersionOverrides1_0 element.

Also, you should probably remove "SupportsPinning" from 1_0 as that will give a validation error.

Here is a useful resource: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering#task-pane-add-in-element-ordering-within-versionoverrides

**Comment by aashutoshrathi** [comment]
This helped me -> https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/versionoverrides#implementing-multiple-versions

Basically, this allows me to use both the Version

**Comment by inderjitkr** [comment]
Thanks for the reply. I got it and implemented it.

Thanks and Regards
Inderjit Kumar
8984555390

**Comment by Montago** [comment]
> Thanks for the reply. I got it and implemented it.

Hi 

I'm struggling with Outlook 365 and Pinning my Add-In ... 

Would you care to share the Manifest so i can see what you did right and what I did wrong ? 

I can't make the pinning icon show :(
