### ISSUE TITLE
Does the token from getCallbackTokenAsync also work for the Microsoft Graph API?

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js#140]
I'm experiencing 401 Authorisation errors when I pass on the token I retrieved from `Office.context.mailbox.getCallbackTokenAsync()`

Looking at your documentation it says it's for REST and Microsoft Exchange. So that doesn't say it's a token for Microsoft Graph API as well. Can you confirm here and probably improve documentation on this?

Thanks

**Comment by exextoc** [comment]
The callback token does not work with Microsoft graph and we do not have plans to do so in near future. Please use AAD authenticated access token for Microsoft graph access. Callback token is intended to work for on-prem exchange configurations and it is only intended to give access to mailbox content while Microsoft graph has additional APIs as well which are some of the reasons it is not supported for Microsoft Graph.

**Comment by mlafleur** [comment]
Given that the Outlook REST API and Microsoft Graph are often used interchangeably elsewhere in the documentation, I can see how this might not be immediately clear to developers. 

Should this be noted in the [Use the Outlook REST APIs from an Outlook add-in](https://docs.microsoft.com/en-us/outlook/add-ins/use-rest-api)?

**Comment by Zlatkovsky** [comment]
Adding @Rick-Kirkham from documentation team, to handle the documentation side of things

**Comment by elegault** [comment]
@mlafleur is correct - I also have fallen into this assumption, and I wish I would have seen this issue last week as it could have saved me several days of banging my head against the desk. :-|

**Comment by ElizabethSamuel-MSFT** [comment]
The update should be published next week. Please reopen if more clarification is needed. Thanks.

**Comment by ghost** [comment]
i am not getting the Access Token in my outlook addin. i am using office 365 account and outlook web.what would be the issue? could anyone please help

**Comment by ghost** [comment]
just want to give more information on issue, when i save the calendar event and open, i am getting the access token. is this the expected behavior? Won't i be able to get the token while composing as new? my add-in is for fetching the data before saving/send the appointment. please help

**Comment by ElizabethSamuel-MSFT** [comment]
@Francis-B: Thank you for raising this issue. However, could you create a new issue as this one is already closed?

**Comment by td-gonzales** [comment]
This is still very confusing and I just ran into it. If I'm not supposed to use `Office.context.mailbox.getCallbackTokenAsync` to get a token to use with the Graph API what should I use?

**Comment by td-gonzales** [comment]
> The update should be published next week. Please reopen if more clarification is needed. Thanks.

Where was this published?

**Comment by ElizabethSamuel-MSFT** [comment]
> > The update should be published next week. Please reopen if more clarification is needed. Thanks.
> 
> Where was this published?

@td-gonzales Thanks for asking. Looks like we lost this update at some point so we'll get that resolved. However, can you take a look at the referenced articles [Outlook REST API via Microsoft Graph](https://docs.microsoft.com/outlook/rest/#outlook-rest-api-via-microsoft-graph) and [Compare Microsoft Graph and Outlook REST API endpoints](https://docs.microsoft.com/outlook/rest/compare-graph) and see if that helps?

Thanks.

**Comment by td-gonzales** [comment]
> > > The update should be published next week. Please reopen if more clarification is needed. Thanks.
> > 
> > 
> > Where was this published?
> 
> @td-gonzales Thanks for asking. Looks like we lost this update at some point so we'll get that resolved. However, can you take a look at the referenced articles [Outlook REST API via Microsoft Graph](https://docs.microsoft.com/outlook/rest/#outlook-rest-api-via-microsoft-graph) and [Compare Microsoft Graph and Outlook REST API endpoints](https://docs.microsoft.com/outlook/rest/compare-graph) and see if that helps?
> 
> Thanks.

So I can use the [explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) to get my access token then hard code it to send an email from my outlook add-in. What should I use in the office-js lib to get that token dynamically?
