### ISSUE TITLE
Impossible to insert a string in a cell from the Dialog Box in Desktop Excel 365 (Windows)

### ISSUE THREAD

**Issue by leybal** [OfficeDev/office-js#1403]
We took the excel-shared-runtime-scenario sample ([link](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario)) as a base and added the ability to open a dialog box from a ribbon. A user should be able to insert a string into a cell when clicking on the "Insert from Dialog" button in the dialog box. This script works fine on Mac, Office on the web, but does not work on Windows.

## Expected Behavior

A string should be inserted into a cell after a user clicks the "Insert from dialog" button in the dialog-box.

## Current Behavior

After opening the dialog box from the Ribbon and clicking the "Insert from dialog" button, the string is not inserted into a cell (it may be inserted once with a delay, but it stops working after it). For details, please, see an attached [video](https://drive.google.com/file/d/1WySvyPNqxFYrjg-Ewv_DtwcAKc0zFJv8/view?usp=sharing).

## Steps to Reproduce, or Live Example

* Link to code: [link](https://github.com/TheSorbex/PnP-OfficeAddins/commit/4f7b26ceb965fdc4b826b4c9e3a68d917d75cbb6)

* Additional details:
  1. In commands.ts we have added the openDialogueModal function, which opens a page in a dialog-box using displayDialogAsync.
  2. When a user clicks on the button in the dialog box, we pass the data using messageParent 
  3. We receive data in commands.ts using dialog.addEventHandler (Office.EventType.DialogMessageReceived, processMessage). Inside the processMessage function we process data and insert a string into the cell. As a result, a string is not inserted into the cell with an open dialog-box.

## Context

We create add-in based on shared js runtime. Our users should be able to open a dialog box from the ribbon and insert a string into a cell without closing the dialog box.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Excel for Microsoft 365 MSO (16.0.13127.20402) 64-bit
* Operating System: Windows 10 1909

## Useful logs

- A video on which the same script works on a Mac is attached [link](https://drive.google.com/file/d/16llygo6rkYncXmK6Oia3xGK3RstfFhKU/view?usp=sharing).
- Previously, this bug was discussed on the [stackoverflow](https://stackoverflow.com/questions/63938325/impossible-to-insert-a-string-in-a-cell-from-the-dialog-box-in-desktop-excel-365).

**Comment by smaremanda** [comment]
hi @leybal - This is by design. The dialog is meant for authentication purposes and not as a surface for executing apis. what is the reason why you couldnt execute this api from the taskpane?

**Comment by leybal** [comment]
@smaremanda thanks for the answer. According to business requirements, our users should be able to open a dialog box from a ribbon and insert a string into a cell. With the publishing of shared js runtime, we can modify the value in the cell when clicking on the button on the ribbon (as shown in the excel-shared-runtime-scenario example). In our case, we get a string from the dialog and handle inserting a string in the dialog.addEventHandler method.
@lliu113 please take a look at the following scenario. The fact that on Excel for Windows we cannot insert a string into a cell from the dialog box looks like a bug, because in Office on the web and Excel for Mac this script works fine. In practice, we can modify the cell inside the dialog.addEventHandler method, but not on all platforms.
1. What is considered as a bug? That we cannot insert a string on Excel fro Windows or the ability to modify a cell on Excel Online and Excel for Mac?
2. In the future, do you plan to allow us modifying of a cell from the dialog box? Or eliminate this feature entirely on all platforms?

Note: we think that dialog boxes have much more potential. The dialog box has more functionality due to the fact that we can place more visible content than in the task pane. It will be convenient for users to use dialog boxes to change data in the workbook, because they do not have strict restrictions on the width of the content.
By limiting the ability to edit cells from a dialog-box (from dialog.addEventHandler method), we limit the ability to build a high-quality and easy-to-use add-in.

**Comment by leybal** [comment]
@smaremanda @lliu113 Could you please provide us the updates regarding this question? It blocks our work.

**Comment by lliu113** [comment]
@leybal thanks for reporting this issue, and sorry for the delayed response! 

As Sudheer mentioned, the block on API calls is by design. For a bit of context, the current dialog box has a locked-down API surface for security reasons as it needs to redirect to untrusted domains for auth. We're investigating a new type of dialog box that will be allowed to call office.js APIs, but there is no current ETA for this. 

The fact that your code works on Mac/Online appears to be a bug. The dialog box should not be able to execute any API calls besides the messaging APIs back to its parent runtime. With a shared runtime, our recommended approach is to utilize the messaging APIs to notify your runtime of the action the dialog would like to perform. That way, instead of your dialog executing the API, it would instead instruct the runtime to do so instead. We support both a [messageChid() ](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#pass-information-to-the-dialog-box)and [messageParent() API](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#send-information-from-the-dialog-box-to-the-host-page) which should make this communication easier.
 
Does this alternative work for your scenario?

**Comment by leybal** [comment]
@lliu113 thanks for the answer. It looks like we have a misunderstanding. We did exactly the same as what you have described. 

In dialog-box, we **did not execute** any Office JS API calls besides the messaging APIs back to its parent runtime. We **used only messageParent API** to pass the string to the host page (in our case It's a Ribbon).  And already the host page is engaged in inserting the string into the cell. Link to code: [link](https://github.com/TheSorbex/PnP-OfficeAddins/commit/4f7b26ceb965fdc4b826b4c9e3a68d917d75cbb6).

This script works fine in Office on the web and Excel for Mac but doesn't work correctly on Excel for Windows (looks like a bug, please look at the [video](https://drive.google.com/file/d/1WySvyPNqxFYrjg-Ewv_DtwcAKc0zFJv8/view?usp=sharing)). Could you look at the [code](https://github.com/TheSorbex/PnP-OfficeAddins/commit/4f7b26ceb965fdc4b826b4c9e3a68d917d75cbb6) and reproduce this scenario on Excel for Windows?

We will be very grateful for your attention to this problem.

**Comment by lliu113** [comment]
@leybal - thank you for providing the sample! Unfortunately I was unable to repro it on desktop, there is no delay when inserting and it inserted each time. Can you verify whether you're still seeing this issue?
