### ISSUE TITLE
Excel:Is there a storage larger than localstorage

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#1404]
We Use localstorage,It only supports 5M data。

Is there a storage larger than localstorage？ thanks

**Comment by lumine2008** [comment]
may I know your scenario of using local storage? which API are you using? 
if you want to the large storage, maybe you could consider worksheet custom property?

**Comment by lumine2008** [comment]
Clean up issue, please re-open if you still have some questions, thanks
