### ISSUE TITLE
[Outlook ] Discard recurring meeting issue 

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1405]
When we scheduling a recurring meeting and then discard this meeting. 
It will show me an error :  Uncaught (in promise) TypeError: Cannot read property 'IsMeeting' of null
And this meeting was saved even I don't want to save it ...

## Expected Behavior
Recurring meeting will not be saved and with no error

## Current Behavior
Show me an error and saved the discard meeting.

## Steps to Reproduce, or Live Example
Recording:
https://success.zoom.us/rec/share/gtQEszcTdqsgSDr5bzNApoBxj0VGJZCeSCXi_qOtLygOMOb73CscDHQEw8pZ_XAM.R6XoXgkF4pfF0XCv

Access Passcode: diMHH#R0
![image](https://user-images.githubusercontent.com/15980696/94137261-bc8c0b00-fe98-11ea-95f6-4d2fd75aa189.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: online
* Operating System: Windows
* Browser (if using Office on the web): Chrome

reference link: https://github.com/OfficeDev/office-js/issues/1312

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in the latest build.
[Outlook Add-ins Engineering Team]

**Comment by SWei1234** [comment]
Hi @exextoc 
Thanks, I will check it and change the ticket status.

**Comment by SWei1234** [comment]
@exextoc  The issue is fixed! Thanks
