### ISSUE TITLE
getStartupBehavior throws NotImplemented error in Chrome

### ISSUE THREAD

**Issue by bdentino** [OfficeDev/office-js#1407]
Attempting to call getStartupBehavior crashes the add-in in Chrome.

## Expected Behavior

Nothing I could find in the docs indicates that this API is not available on certain platforms, so I would expect that it should behave as other platforms and return the startup behavior of the document.

## Current Behavior

Attempting to call getStartupBehavior crashes the add-in in Chrome with a NotImplemented error. The docs [here](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/run-code-on-document-open?view=word-js-preview) don't mention anything about this feature being unsupported in certain environments, so it's not clear if this is a bug or intentionally not implemented.

## Steps to Reproduce, or Live Example

* Link to live example: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/run-code-on-document-open?view=word-js-preview

* Additional details:
Click the run button in Office online in Chrome, and check the console logs.

## Context

I want to check/set add-in startup behavior on the web document so that add-in code will run when the document is opened.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web 
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.13322.37952
* Operating System: Mac OS X
* Browser (if using Office on the web): Chrome Version 85.0.4183.121 (Official Build) (64-bit)

## Useful logs

<img width="394" alt="Screen Shot 2020-09-24 at 1 03 17 PM" src="https://user-images.githubusercontent.com/3820523/94182255-55556300-fe66-11ea-8e64-eea250c348ec.png">

**Comment by JinghuiMS** [comment]
@ElizabethSamuel-MSFT 
Do you configure your Office Add-in to use a shared runtime? this step is required. See the first highlight area in below link for details. https://docs.microsoft.com/en-us/office/dev/add-ins/excel/run-code-on-document-open?view=word-js-preview 
If you did it, could you provide more infomation about your addin manifest? Because in too many cases, the error of your screenshot will appear. We can not figure out the specific issue with current msg.

**Comment by ElizabethSamuel-MSFT** [comment]
> @ElizabethSamuel-MSFT
> Do you configure your Office Add-in to use a shared runtime? this step is required. See the first highlight area in below link for details. https://docs.microsoft.com/en-us/office/dev/add-ins/excel/run-code-on-document-open?view=word-js-preview
> If you did it, could you provide more infomation about your addin manifest? Because in too many cases, the error of your screenshot will appear. We can not figure out the specific issue with current msg.

@bdentino I think this comment is meant for you. Can you respond to JinguiMS' questions? Thx.

**Comment by bdentino** [comment]
Sure, thanks for the notification.

We do have our add-in configured to use a shared runtime. Note that everything works as expected on desktop platforms. This is the basic structure of our manifest, with urls & strings redacted.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="TaskPaneApp">
  <Id>...</Id>
  <Version>...</Version>
  <ProviderName>...</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="..."/>
  <Description DefaultValue="..."/>
  <IconUrl DefaultValue="..."/>
  <HighResolutionIconUrl DefaultValue="..."/>
  <SupportUrl DefaultValue="..."/>
  <AppDomains>
    <AppDomain>...</AppDomain>
    <AppDomain>...</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Workbook"/>
  </Hosts>
  <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="CustomFunctionsRuntime" MinVersion="1.1"/>
      <Set Name="DialogApi" MinVersion="1.1"/>
    </Sets>
  </Requirements>
  <DefaultSettings>
    <SourceLocation DefaultValue="..."/>
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>
  <VersionOverrides xmlns="..." xsi:type="...">
    <Hosts>
      <Host xsi:type="Workbook">
        <Runtimes>
          <Runtime resid="Taskpane.Url" lifetime="long" />
        </Runtimes>
        <AllFormFactors>
          <ExtensionPoint xsi:type="CustomFunctions">
            <Script>
              <SourceLocation resid="Functions.Script.Url"/>
            </Script>
            <Page>
              <SourceLocation resid="Taskpane.Url"/>
            </Page>
            <Metadata>
              <SourceLocation resid="Functions.Metadata.Url"/>
            </Metadata>
          </ExtensionPoint>
        </AllFormFactors>
        <DesktopFormFactor>
          <GetStarted>
            <Title resid="GetStarted.Title"/>
            <Description resid="GetStarted.Description"/>
            <LearnMoreUrl resid="GetStarted.LearnMoreUrl"/>
          </GetStarted>
          <ExtensionPoint xsi:type="PrimaryCommandSurface">
            <OfficeTab id="TabHome">
              <Group id="CommandsGroup">
                <Label resid="CommandsGroup.Label"/>
                <Icon>
                  <bt:Image size="16" resid="Icon.16x16"/>
                  <bt:Image size="32" resid="Icon.32x32"/>
                  <bt:Image size="80" resid="Icon.80x80"/>
                </Icon>
                <Control xsi:type="Button" id="TaskpaneButton">
                  <Label resid="TaskpaneButton.Label"/>
                  <Supertip>
                    <Title resid="TaskpaneButton.Label"/>
                    <Description resid="TaskpaneButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="Taskpane.Url"/>
                  </Action>
                </Control>
              </Group>
            </OfficeTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>
    <Resources>
      <bt:Images>
        <bt:Image id="Icon.16x16" DefaultValue="..."/>
        <bt:Image id="Icon.32x32" DefaultValue="..."/>
        <bt:Image id="Icon.80x80" DefaultValue="..."/>
      </bt:Images>
      <bt:Urls>
        <bt:Url id="GetStarted.LearnMoreUrl" DefaultValue="..."/>
        <bt:Url id="Taskpane.Url" DefaultValue="..."/>
        <bt:Url id="Functions.Script.Url" DefaultValue="..."/>
        <bt:Url id="Functions.Metadata.Url" DefaultValue="..."/>
        <bt:Url id="Functions.Page.Url" DefaultValue="..."/>
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="GetStarted.Title" DefaultValue="..."/>
        <bt:String id="CommandsGroup.Label" DefaultValue="..."/>
        <bt:String id="TaskpaneButton.Label" DefaultValue="..."/>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="GetStarted.Description" DefaultValue="..."/>
        <bt:String id="TaskpaneButton.Tooltip" DefaultValue="..."/>
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>
```

**Comment by JinghuiMS** [comment]
Involve our PM @lumine2008 for more ideas.

**Comment by lumine2008** [comment]
Thanks @bdentino  for reporting this issue, a bug (4552017) was created and engineering team has been worked on the fix, it will be rolled out soon.

**Comment by lumine2008** [comment]
Update:
This issue was resolved, please verify, thanks.
