### ISSUE TITLE
Share Runtime Performance in IE

### ISSUE THREAD

**Issue by chanhohang** [OfficeDev/office-js#1408]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi,

We are adding support of shared runtime to our Excel Add-in and find the performance of IE is much slower than Edge. (Our data update operations take 2-3 times longer in Shared Runtime IE than in Edge)

Is there any plan to support Shared Runtime in Edge in the coming release?

Regards,
Roy

**Comment by lumine2008** [comment]
@smaremanda , it seems to me that this issue is in your scope. would you please take care of it?

**Comment by lindalu-MSFT** [comment]
@smaremanda Somehow this didn't get assigned so it's been overlooked. Can you answer this? The question is if there are any plans to support Shared Runtime in Edge in the coming release. Thanks, linda

**Comment by ElizabethSamuel-MSFT** [comment]
@madhavagrawal17 Can you take a look?

Thanks.
