### ISSUE TITLE
[Firefox] Add-In Dialog is closing when clicked

### ISSUE THREAD

**Issue by helmarluiz** [OfficeDev/office-js#1409]
Hi, 

I'm developing a Click to Call Add-In, using Contextual-Regex which finds phones in the email body, creating a click link with "tel" protocol (`<a href="tel:+353888888888"> </a>`). Clicking on the link it opens the Add-In Dialog (which is managed by Outlook) with a text field and a button, which the user can edit the number and them click on to open the local software for calls.

The Add-In It's working fine for Outlook Desktop and all the browsers except Firefox, In Firefox when clicking inside the Dialog it closes immediately and doesn't trigger any click events within the Dialog content.

I did a test also using the sample code available here in the repository and the same behavior occurs, so the issue is in Outlook. Is anyone experiencing the same problem? Would there be any other way  to implement a similar Add-In without using Contextual-Regex with Dialog?

### Firefox 
![](https://media.giphy.com/media/JY23b68QKu5wMsreol/source.gif)

### Chrome and other browsers
![](https://media.giphy.com/media/7VSU7UxVxtsy6B2iUM/source.gif)

**Comment by exextoc** [comment]
@helmarjunior We are unable to repro this issue on our side. 
1. Is it possible to share sample add-in so that we can repro this issue on our side?
2. Does Add-in dialog closes on clicking anywhere in the dialog or just on clicking the text field ?
3. Can you try this [sample contextual add-in](https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex) once and check if you face same issue?

**Comment by helmarluiz** [comment]
@exextoc I created a new Microsoft 365 account to reproduce the issue:

1. It's happening even using the [sample contextual add-in](https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex) code.
2. It closes on clicking anywhere in the dialog, except in the dialog title.
3. I just tried to use the [sample contextual add-in](https://github.com/OfficeDev/Outlook-Add-In-Contextual-Regex) code with a new Microsoft 365 account and I got the same issue, take a look at the videos bellow.

### Firefox 81.0
![](https://media.giphy.com/media/wQirXfJPaXoF7L7oCL/source.gif)

### Chrome and other browsers
![](https://media.giphy.com/media/TOySftztj4lqODKFpD/source.gif)

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding Add-In Dialog. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.
