### ISSUE TITLE
Does the REST API support forwarding at all?

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js#141]
Tried to forward an email with REST API like that:

https://outlook.office365.com/api/v2.0/me/messages/AQMkAGQyZTBkZjQ1LWQ3M2QtNDk2MS04MWI4LTJhNWY1MGRmYzkyNwBGAAADT2XgZSCi_kySETGqKpnYRgcAD-iVVa-h0kS4omDA7LUynAAAAgEMAAAAD-iVVa-h0kS4omDA7LUynAAAAgVOAAAA/forward

But it comes back with a 403 ErrorAccessDenied saying "The api you are trying to access does not support item scoped OAuth."

Using this token here

```js
Office.context.mailbox.getCallbackTokenAsync()
```

And have this permission and those rules in the manifest

```xml
  <Permissions>ReadWriteMailbox</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit" />
  </Rule>
```

Any clues?

**Comment by mlafleur** [comment]
You need to pass `isRest: true` in order to get back the proper token:

``` js
Office.context.mailbox.getCallbackTokenAsync({ isRest: true }, function(result) {
  if (result.status === "succeeded") {
    var accessToken = result.value;

    // Get the item's REST ID
    var itemId = getItemRestId();

    // Get the URL
    var getMessageUrl = Office.context.mailbox.restUrl + '/v2.0/me/messages/' + itemId + '/forward';

    // ....
  }
});

```

**Comment by binarykitchen** [comment]
yessss, that was it! thanks heaps - just wish the error message is a bit more clear
