### ISSUE TITLE
Excel Shared JavaScript runtime does not work with Solver or Analysis ToolPak in Mac OS

### ISSUE THREAD

**Issue by marami52** [OfficeDev/office-js#1410]
## Expected Behavior
I expect to have an Excel JavaScript add-in to work without any conflict with other Excel add-ins such as Solver or Analysis ToolPak on Mac OS.

## Current Behavior
When I install an Excel Add-in which uses Shared JavaScript runtime, it stops working when I activate Solver or Analysis ToolPak in my Mac OS. This issue does not happen on Windows (we tested on WIndows 10).

## Steps to Reproduce, or Live Example
You should follow these steps in Mac OS. Please see the environment details below:

1. Use the excel-shared-runtime-scenario Add-in with Shared runtime example from Microsoft official OfficeDev repo here:

https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario

2. Follow the instructions provided in the repo to run the add-in. However, **do not** run the add-in by `npm run sideload`
Instead follow the instruction here: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac to test the add-in. In fact, you need to copy the manifest file (_manifest.xml_) from above mentioned repo into `/Users/<username>/Library/Containers/com.microsoft.Excel/Data/Documents/wef` folder.

3. Now, open a new Excel file and add Contoso Data add-in by following: 
Insert > Add-ins > My Add-ins (drop-down menu), and then choose the add-in.

4. After step 3, **Contoso Data** tab should show in Excel. In an empty Cell, run: 
`= CONTOSOSHARE.ADD(1,2)` which shows 3.

5. Now, go to Tools > Excel Add-ins... and select the checkbox for Solver and/or Analysis ToolPak.

6. Close Excel file and **quit** Excel as well.

7. Open a new Excel file and repeat step 3.

8. Again, in an empty cell run:

`= CONTOSOSHARE.ADD(1,2)`

This time it shows ?NAME which shows that the add-in does not work anymore. Of course, if you deactivate  Solver and Analysis ToolPak and start from step 3, everything goes back to normal.

9. What is interesting is that if when Solver and Analytics ToolPak are deactivated and you run successfully `CONTOSOSHARE.ADD` function, and save your workbook. Next time, when you open your workbook, even when the Solver or ToolPak are activated, the add-in works as expected.

## Context
We are developing an Excel Add-in which uses Shared JavaScript runtime. Using Shared runtime is important for us as we need full CORS functionalities. WIth this issue, our users on Mac OS  cannot use our add-in and Solver for instance, at the same time unless follow the workaround in step 9 above.

## Your Environment
1. MAC OS Catalina 10.15.6
2. Excel with 365 Subscription version 16.41

This issue does not happen on Windows 10.

## Useful logs
We activated runtime logging and noticed that when Solver is activated, the system reports registration of  CONTOSOSHARE.ADD function with a workbook called `Solver.xlam` which does not look relevant to this process (we do not have any workbook with this name in our file). We do not see this process when the add-in works properly:

```
9/27/20 6:09:43 PM	Verbose	CustomFunctions	[Registration] [Begin] Function=CONTOSOSHARE.ADD, Workbook=Solver.xlam		
9/27/20 6:09:43 PM	Medium	CustomFunctions	[Registration] [End] [Success] Function=CONTOSOSHARE.ADD, Workbook=Solver.xlam
```

**Comment by keyur32** [comment]
Needs investigation, but repro seems odd as the enabling of Solver/ATP built in add-ins should not affect Custom Function registration.

**Comment by grangeryy** [comment]
@marami52 does this still repro for you?

**Comment by marami52** [comment]
no. I close the issue. Thank you.
