### ISSUE TITLE
Office.context.mailbox.item does not return recipient email address on copy-paste 

### ISSUE THREAD

**Issue by tido-ms** [OfficeDev/office-js#1411]
When copy and paste pre-existing recipients, Office.context.mailbox.item returns recipients without email addresses. This library is used in a outlook add-in, as the recipient email address is not returned, the add-in prompts an error. 

## Expected Behavior
When copy and paste pre-existing recipients, Office.context.mailbox.item returns valid recipient email addresses. 

## Current Behavior
When copy and paste pre-existing recipients, Office.context.mailbox.item returns recipients without email addresses.
![image](https://user-images.githubusercontent.com/71897774/94439075-c8a3f100-0154-11eb-8dc3-4188a339dc9d.png)

## Steps to Reproduce, or Live Example
Repro  steps: 
 
1.	Opens FindTime in outlook desktop 
2.	Adding users to email compose
![image](https://user-images.githubusercontent.com/71897774/94439498-5a136300-0155-11eb-84c2-74c0f363b7b0.png)

3.	Cut “Cal Substrate Test 1” from Cc and paste to To field -> Warning shows up
![image](https://user-images.githubusercontent.com/71897774/94439515-60094400-0155-11eb-97fa-6c0a946e2e36.png)

* Additional details:
Same behavior exists in **AC Calendar View** add-in 

## Context
There are approximately 700 api call failures due to this error. 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop (only)
* Host [Excel, Word, PowerPoint, etc.]: NA
* Operating System: PC

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding recipients API. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 4516844

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 16.0.13408 or later. When an updated build is available depends on the release channel a customer is on.

[Outlook Add-ins Engineering Team]

**Comment by tido-ms** [comment]
Great, thanks for the quick fix.
