### ISSUE TITLE
Attachment API with blocked attachments

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#1412]
I have a question about Attachment API specification when attaching a file that is [blocked by Outlook](https://support.microsoft.com/en-us/office/blocked-attachments-in-outlook-434752e1-02d3-4e90-9124-8b81e49a8519).

The behavior differs as described below.
What is the expected behavior?

**Windows Outlook:**
You can retrieve content with `getAttachmentContentAsync()` API after attaching a file with the EXE extension.
Then, if you try to save the email, the warning screen appears as shown below.

![unsafe_dialog](https://user-images.githubusercontent.com/58804032/94408047-3d0b7e00-01af-11eb-9326-183159dc2220.png)

After you accept and save it, if you get a list of attachments using the `getAttachmentsAsync()` API, it is not in the list.

![blocked_windows](https://user-images.githubusercontent.com/58804032/94408141-5ad8e300-01af-11eb-8e9e-fe0d92c5963e.png)

**OWA (Outlook on the web):**
If you attach a file with the EXE extension, it will look like the following screen.

![blocked_owa](https://user-images.githubusercontent.com/58804032/94408254-7d6afc00-01af-11eb-9f09-de0183338019.png)

If you get a list of attachments using the `getAttachmentsAsync()` API, it is included in the list.
In addition, executing the `getAttachmentContentAsync()` API to retrieve the content will succeed, but the `base64` value will contain an empty or unknown value starting with "_initial-scale=1.0,user-scalable=0"/><metaname=_".

Note: I have only tested with Windows Outlook and OWA.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 03b32859-121b-cab9-78b9-923fd57628be
* Version Independent ID: c7ac8b7f-0b2a-9389-8d12-8aa0c87817ac
* Content: [Add and remove attachments in an Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form)
* Content Source: [docs/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
I would like to look at the difference in 2 angles:
1. When does Outlook / OWA decides that an attachment is blocked? As you noted, OWA considers an attachment is blocked right away, and Outlook does so after saving. This is a difference in how each client recognizes blocked attachment and it is outside the scope of the Outlook addins API.

2. What is the API behavior for blocked attachments?
Outlook does not return blocked attachments via getAttachmentsAsync, but OWA does. getAttachmentContentAsync for OWA, however would return empty value for a blocked attachment. We can repro this issue and we are investigating.

Do you have scenario or requirement for your addin to expect these APIs to behave in a certain way?

**Comment by clavx** [comment]
Thank you for your response.

Our add-in uses the On-Send feature to inspect attachments and remove unwanted attachments.
With the current behavior of Windows Outlook, it is not possible to retrieve whether or not an attachment exists, and the removal process cannot be carried out. Therefore, the mail is sent with unnecessary attachments, and there is an issue  that uninspected attachments can be obtained depending on the destination.

To remove attachments, the `getAttachmentsAsync()` API should be able to retrieve the list of attachments.
We don't need to get the contents of the attachment, but we would be happy if there is a method to know that it is a blocked file.

**Comment by exextoc** [comment]
Thanks for giving your feedback. We have opened a backlog bug for the owning team to take a look at the difference. In general, we strive to make the api behave the same across different clients, however, the clients can sometimes implement specific features in different ways that require our API to also behave differently. I am not sure what bucket this falls into at this time. 

Internal Tracking Id: 4531060

**Comment by exextoc** [comment]
In the meantime you may want to see this article, in configuring Exchange to block outgoing mails with attachments that have certain extensions: 

https://support.microsoft.com/en-us/help/2795329/how-to-block-a-message-from-being-sent-or-received-based-on-the-file-n

Would that combined with your solution meet your needs?

**Comment by clavx** [comment]
I forgot that we can use transport rules to block outgoing mail.
There is no problem in our scenario.
Thank you for the helpful link.

**Comment by clavx** [comment]
I think it is a bug to return empty value in OWA.
I don't know what the final behavior will be, but if the behavior changes, I would be happy to share it here.
