### ISSUE TITLE
[Outlook Add-in] Fetch in UI-Less doesn’t work

### ISSUE THREAD

**Issue by ghivert** [OfficeDev/office-js#1413]
## Expected Behavior

Hi, I’m using an Add-in Outlook and I’m using a fetch in a UI-less function. It’s fine and perfectly working on Outlook for Web, but not on Outlook for Mac or Outlook for Windows.

Here’s a snippet : 

```javascript
  const result = await fetch(`${getBackendUrl()}/graphql`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      EXTERNALAUTHENTICATIONTOKEN: Office.context.roamingSettings.get(
        'api-token'
      ),
    },
    mode: 'cors',
    body: JSON.stringify({ blablabla }),
  })
```

## Current Behavior
I got this error on desktop:

![image](https://user-images.githubusercontent.com/7314118/94567287-9507ba80-026b-11eb-8d39-098c71e05ca3.png)

## Steps to Reproduce, or Live Example
Creates an Outlook Office Add-in, write a UI-less function, write a fetch.

## Context
I try to create an appointment on my server during a meeting creation in calendar.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac, Windows, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.41
* Operating System: macOS 10.15.6
* Browser (if using Office on the web): Chrome & Edge

**Comment by exextoc** [comment]
I have just tried a fetch request in UI-less and that is working correctly in Desktop Outlook for Windows. There should not be anything specific with ui-less that prevents fetch. A few things to check: 
- have you tried the fetch request from a task pane?
- Could you check if the server response is expected?

Another note: for Office in Windows, older versions of office uses an IE based web control for addins, and fetch is not supported in IE. See https://developer.microsoft.com/en-us/office/blogs/microsoft-edge-webview-for-office-add-ins/ on the Windows and Office versions that have Edge webview

**Comment by ghivert** [comment]
Thanks, the bug was indeed due to body.getAsync, giving a different output on web and desktop. (One give a fragment of HTML, the other one giving an entire HTML page.)
