### ISSUE TITLE
Sideload fails: "ADD-IN ERROR: This add-in is no longer available."

### ISSUE THREAD

**Issue by chucklay** [OfficeDev/office-js#1414]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Not sure if this is a bug with office-js or excel itself, but my Excel installation seems to be stuck, not letting me sideload my add-in. Attempting to `npm run start` an add-in causes this error message in the task pane: 
![image](https://user-images.githubusercontent.com/8353090/94581010-9378cb00-0248-11eb-853c-78e9ca92248a.png)

## Expected Behavior

`npm run start` should sideload an add-in, unless there are other problems preventing this from happening. If something is preventing this add-in from loading, the error message should provide better feedback.

## Current Behavior

`npm run start` successfully launches the debug server, which builds the add-in successfully, and launches excel. However, even before the debug server finishes building the add-in, excel displays the message in the screenshot above. I'm able to sideload this add-in to Excel online without issue (in both edge and ie11). 

## Steps to Reproduce, or Live Example

This is my manifest (which passes validation): https://gist.github.com/chucklay/5276628e8f08f6d10c2b99762fcdd649
There were no changes to this manifest (or the add-in in general) between when sideloading this add-in worked and now.

* Additional details:
I've tried rebooting, clearing the office cache, and even reinstalling office. No luck on any of them. The error message seems to be very outdated, so I have no idea where to even start looking.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2008 (Build 13127.20408)
* Operating System: Windows 10 (10.0.18363 Build 18363)

## Useful logs

I cannot find any logs that suggest where the issue might be. I'm open to suggestions.

**Comment by chucklay** [comment]
Sorry to beg for help again, but this is a complete blocker, and nothing I've turned up has helped. I've tried loading this on another computer, with the same result. Even rolling back to a previous version of the manifest (And add-in in general) that I know worked hasn't helped.

**Comment by chucklay** [comment]
Aaand as soon as I leave that comment, I found the issue. While the add-in's HighResoutionIcon has to be 64x64, if the high resolution icon for your buttons is anything other than 80x80, you get this error. I'd like to change this issue to a request to have the manifest validator catch that, since your add-in will not work if you don't have it right.

**Comment by TCourtneyOwen** [comment]
Sorry to hear you are having problems.  A  few questions for you:

- Did you create this project with Yo Office?
- When you run "npm start"does the dev-server start?
- If it does indeed start, are you able to browse to https://localhost:3000/taskpane.html?  If you aren't then that would be a problem and probably indicates the dev-server certs aren't installed

-Courtney

**Comment by TCourtneyOwen** [comment]
So in reading through this thread is the real issue the size of the icon?

**Comment by chucklay** [comment]
Yes, the icon size of my taskpane buttons was the problem. I had them set to 64x64. (I had done a find/replace to switch 80x80->64x64 after my HighResolutionIcon was incorrectly set to 80x80). However, it appears that Excel cached the old button icon, so this issue didn't pop up until much later.

What was really confusing is that this doesn't prevent the add-in from sideloading into excel online. That combined with manifest validation not catching this made the problem really hard to track down.

**Comment by TCourtneyOwen** [comment]
So essentially manifest validation fails when the icon size is set to 64x64?  If this is the case I can see about asking that we don't fail manifest validation for this, but this will not be a quick fix, as I believe this is owned by our team in Ireland.

-Courtney

**Comment by chucklay** [comment]
Actually it's the opposite problem - If the icons are the wrong size, `npm run validate` claims that the manifest IS valid, and the add-in will load in Excel online. However, using `npm run start` to run on desktop will cause it to not load with the error message/description in my original post.

**Comment by TCourtneyOwen** [comment]
Interestingly, I changed my manifest to use 64x64 icons and was able to start my add-in project successfully in Desktop.  I am using a Excel taskpane project I created via Yo Office

**Comment by chucklay** [comment]
Hmm, strange. Just to clarify, the incorrectly sized icons were for my ribbon buttons. Maybe it had something to do with them being on a custom tab? This is the problem section in question, and this version of my manifest does demonstrate the problem: https://gist.github.com/chucklay/4f8d1da6a5b15234b194552a2a1f0211#file-manifest-xml-L61-L105

Based on the feedback I got when I submitted this add-in (I hadn't hit this problem yet, I assume due to caching), I think the testers ran into this problem too.

**Comment by awasser-omnispear** [comment]
I'd like to pile on my experience as well.
I am encountering the same issue, but with the Yo Office result directly without any change to the manifest or any of the code.
* Excel Enterprise version: 2011 (Build 13426.20332 Click-to-Run)
* Windows 10 Pro Version 10.0.19041 Build 19041

I've tried a number of templates in yo office, and even cloning the Custom Functions template directly from github.  All have the same yellow dialog as OP's screenshot.

**Comment by danlg** [comment]
@chucklay thanks for your post. I am facing the same issue but using in manifest.xml a HighResolutionIcon to 80x80 didn't solve it. I am on Mac BigSur OS.
Actually the error is slightly different. I have tried to clear the cache because I wanted to change the default icon but now it cannot reload an addin.
![image](https://user-images.githubusercontent.com/12525045/150702268-22409fc8-987b-47c7-8988-2b6930aaf2c1.png)
![image](https://user-images.githubusercontent.com/12525045/150702318-7eb8187b-561c-4113-a953-5d909ea05d9e.png)
