### ISSUE TITLE
Outlook for Mac, Office JS API does not work after switching accounts in From field

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1417]
In an Outlook add-in for compose mode, we are using the Office JS API to fill in email fields. OfficeJS methods throw the "The selected item has been changed" error in a new email window after changing an email account in the From field.

## Expected Behavior
Office JS methods should work.

## Current Behavior
The following error occurs:
"error":{"name":"APICallFailedDueToItemChange","message":"The selected item has been changed.","code":9030}

## Steps to Reproduce, or Live Example
Steps for reproduce:
1. Create a new email in Outlook for Mac
2. Open an add-in's pane and pin it.
3. Execute the code below.
4. Choose another email account in the From field.
5. Open the add-in's pane, pin it and execute the code below.
6. Switch the From field back to the first email account.
7. The add-in's pane is opened automatically because it is pinned.
8. Execute the code below and you will see the error.

Code sample:
`Office.context.mailbox.item.body.getTypeAsync({ }, (result: Office.AsyncResult<Office.CoercionType>) => {`
`  console.log(result);`
`});`

* Additional details:
  1. The itemChanged event is handled in our code.

## Your Environment
* Platform: Mac
* Host: Outlook for Mac
* Office version number: 16.41 (20091302)
* Operating System: macOS Catalina Version 10.15.6
* Browser (if using Office on the web):

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding pinned add-ins. It has been put on our backlog. We unfortunately have no timelines to share at this point.
However the [New Outlook for Mac](https://support.microsoft.com/en-gb/office/the-new-outlook-for-mac-6283be54-e74d-434e-babb-b70cefc77439?ui=en-us&rs=en-gb&ad=gb) doesn't have this issue, which is currently available in our Insiders program. You can get access to it by signing up for the Insiders program [here](https://insider.office.com/en-us/join/mac).
Internal tracking id: Office: 1709532

**Comment by exextoc** [comment]
The issue is not there in New Outlook for Mac which is in production now. If you see the problem there, you can reopen the issue.
