### ISSUE TITLE
Blazor as a Office addin?

### ISSUE THREAD

**Issue by sturlath** [OfficeDev/office-js#1418]
I asked [this question at the aspnetcore repo](https://github.com/dotnet/aspnetcore/discussions/26419) and will repeat it here.

There is an [article from Nov 2019](https://developer.microsoft.com/en-us/office/blogs/office-add-ins-community-call-november-13-2019/) that says

>Will Blazor be supported for Office Add-ins?

>No, it will be a React Office.js add-in. We don’t have any plans to support Blazor yet.

**Is this still the case?** Any work being done on offering it?

I find it really strange if this programming model (C#) will not be available someday. Any and all information appreciated.

p.s
I first added the question to [StackOverflow](https://stackoverflow.com/questions/64138534/blazor-as-a-office-add-in) so a lot of questions around by me.. sorry about that..

**Comment by ElizabethSamuel-MSFT** [comment]
@sturlath Thanks for asking about this.

@mattgeim Someone has also asked about Blazor on the docs repo: https://github.com/OfficeDev/office-js-docs-pr/issues/1711.

Thanks.

**Comment by sturlath** [comment]
Thanks @ElizabethSamuel-MSFT but I see the first issue (that I missed sorry) has not been answered. I added comments to it and will in turn close this one and have the other one as the main driver for my question.

**Comment by robertmclaws** [comment]
Anything new on this? It's been over a year and more apps are moving to Blazor. We're upgrading our app and would like our Add-in to support Blazor too.

Thanks!

**Comment by StevenDeRoover** [comment]
Following ...

**Comment by AkshayKumarGadiya** [comment]
Yes, Both WASM & SSR support office Add-ins.
https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/blazor-add-in/outlook-blazor-add-in
