### ISSUE TITLE
Outlook Online, IE and old Edge, the displayDialogAsync method opens a popup window behind the main browser window

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1419]
In an Outlook add-in for compose mode, we are using the Office.context.ui.displayDialogAsync method to display a dialog to a user. In Internet Explorer and old Microsoft Edge (not Chromium) the opened dialog window is not visible because it is opened behind the main browser window.

## Expected Behavior
The displayDialogAsync method shall open the dialog window and bring it to the front.

## Current Behavior
The dialog window is opened behind the main browser window.

## Steps to Reproduce, or Live Example
Sign in to Outlook Online using Internet Explorer or Microsoft Edge, create a new email and execute the following code:
`const url = location.origin;`
`Office.context.ui.displayDialogAsync(url, { width: 30, height: 30 }, (result) => {`
`  console.log(result);`
`});`

## Your Environment
* Platform: Office on the web
* Host: Outlook Online
* Office version number: 
* Operating System: Windows 10
* Browser (if using Office on the web): Internet Explorer 11.1082.18362.0 and Microsoft Edge 44.19041.423.0

**Comment by exextoc** [comment]
We are unable to repro the issue on our side with the code snippet shared by you. Can you try setting [displayInIframe]( https://docs.microsoft.com/en-us/javascript/api/office/office.dialogoptions?view=word-js-preview#displayiniframe) option to true and check if you still see the issue?
You can try sample code 
var dialogOptions = { height:80, width:50, displayInIframe: true,};
Office.context.ui.displayDialogAsync(url, dialogOptions, displayDialogCallback);
function displayDialogCallback(asyncResult){
      console.log(asyncResult.status);
}

**Comment by DmitryKostochko** [comment]
@exextoc, unfortunately we cannot use displayInIframe: true. We need a new pop-up window with authentication pages.

It is a bit strange that you cannot reproduce the issue. On our side, I can see the new pop-up window for about half a second, and then it gets hidden behind the main browser window.  What else can we try to check?

**Comment by exextoc** [comment]
@DmitryKostochko Does this happen on multiple systems or is it on a specific system ? 
Can you confirm if you are repro the issue with sample code share above with displayInIframe: false? If Not, can you share sample add-in with which we can repro this issue at our end.

**Comment by DmitryKostochko** [comment]
>> Does this happen on multiple systems or is it on a specific system ?

It happens on different systems. For example, I have just re-tested IE on my virtual machine with the following configuration:
- Windows 10 Version 1909 (build 18363.1082)
- Internet Explorer 11.1082.18362.0
- Code: Office.context.ui.displayDialogAsync(url, { width: 30, height: 30, displayInIframe: false }, (result) => { 

>> Can you confirm if you are repro the issue with sample code share above with displayInIframe: false?

I have just reproduced the issue again, please see the details above. What other information do you need from our side?

**Comment by exextoc** [comment]
@DmitryKostochko We are unable to reproduce this issue on our end with the information you provided. Could you please share a sample add-in with us in order to reproduce the bug?

**Comment by DmitryKostochko** [comment]
@exextoc, no problem, you can install the test add-in using the following manifest:
https://online-addins.ablebits.com/testaddin/manifest.xml

I have also attached its sources and manifest:
[test-add-in.zip](https://github.com/OfficeDev/office-js/files/5332891/test-add-in.zip)

**Comment by exextoc** [comment]
@DmitryKostochko We are unable to reproduce this issue on our end. Could you please provide us a test account so that we can investigate this issue?

**Comment by DmitryKostochko** [comment]
@exextoc, I have just created a test account on outlook.com and reproduced the issue. How can I pass the email address and password to you?

**Comment by exextoc** [comment]
@DmitryKostochko Could you please share the test account credentials with us at admin@a830edad9050849405E20081103.onmicrosoft.com

**Comment by DmitryKostochko** [comment]
@exextoc, thank you, I have just sent the credentials.

**Comment by exextoc** [comment]
@DmitryKostochko we could not reproduce the issue with the test account provided by you using Internet Explorer on Windows 10. Could you please try updating your Internet Explorer to the latest version? Also, could you please try reproducing this issue on a different system than you mentioned earlier?

**Comment by DmitryKostochko** [comment]
>> Could you please try updating your Internet Explorer to the latest version?

I don't  have any updates for Internet Explorer in Windows Update.

>> Also, could you please try reproducing this issue on a different system than you mentioned earlier?

Here are 2 other configurations where the issue is reproducible:

Windows 1809 (build 17763.1397)
- Internet Explorer 11.1397.17763.0
- Microsoft Edge 44.17763.831.0, Microsoft EdgeHTML 18.17763

Windows 2004 (build 19041.450)
- Internet Explorer 11.450.19041.0
- Edge 44.19041.423.0, Microsoft EdgeHTML 18.19041

**Comment by exextoc** [comment]
We are not able to reproduce the issue from our end, please update the browsers to the latest version and try again.

**Comment by exextoc** [comment]
Moreover can you please share a repo video for our reference ?

**Comment by DmitryKostochko** [comment]
>> We are not able to reproduce the issue from our end, please update the browsers to the latest version and try again.

As I mentioned earlier, IE is up to date.

>> Moreover can you please share a repo video for our reference ?

Of course, please see it attached.

[IE-video.zip](https://github.com/OfficeDev/office-js/files/5384805/IE-video.zip)

**Comment by exextoc** [comment]
@DmitryKostochko  Thanks for sharing the video. We are able to repro this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
This issue is with specific browser IE, as a workaround you can try using Edge or other supported browsers.
