### ISSUE TITLE
[Excel] Handling Default Event for Modal Closing

### ISSUE THREAD

**Issue by TheSorbex** [OfficeDev/office-js#1420]
Need an ability to handle the default closing of the Modal when a user clicks on a cross-icon. We have the ability to close modal using `messageParent` and `dialog.close()` but it’s shared only on custom buttons, cross-icon can’t be handled by it now.

Adding of this feature will allow us to run some logic on closing modal, not depending on a way how it was closing. It would be great if you extend `Dialog` with some method `onClose`. It would be called every time, when a user closes the modal.

Example case - [Trying to control modal closing](https://drive.google.com/file/d/14gf7MoVxuerg8xktGhd4grTs0-I6HOcW/view)

**Comment by lumine2008** [comment]
Hi @lliu113 , this looks to me like an UX request. would you please help confirm? thanks

**Comment by lindalu-MSFT** [comment]
If you're still interested in adding this feature, please go to our new [Ideas forum](https://aka.ms/m365dev-suggestions) and click **Submit an Idea**. If there's enough interest (votes), we will follow up with you there and add it to our feature request backlog. Please add link to the suggestion in the comments for tracking. Thanks, lindalu
