### ISSUE TITLE
Cookies do not persist on Excel for MAC  

### ISSUE THREAD

**Issue by vikasm1720** [OfficeDev/office-js#1422]
I have Excel add-in which uses shared runtime and UI less custom function. I am using dialog API for authentication. When a user closes a workbook and opens a new one or reopens a saved workbook, cookies do not persist and user needs to re-login. I am facing this issue only on Excel for MAC platform. it is working as expected on windows and online.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41545a25-b635-de53-a4aa-36ab4108f817
* Version Independent ID: d7ce1841-184d-38f1-b81b-96d5ef887538
* Content: [Authentication for UI-less custom functions - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-authentication)
* Content Source: [docs/excel/custom-functions-authentication.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-authentication.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@vikasm1720 Thanks for raising this issue. I'll transfer this issue to the office-js repo for the product team to take a look.

Thanks.

**Comment by jeremy-msft** [comment]
Hi @vikasm1720, thanks for reporting this issue.  Could you please provide us with a small sample repro of the issue you're seeing (e.g.  storing/reading the cookies with test data instead of going through your full auth flow)?  Also, please let us know what version of Mac OS and Office you are running.

**Comment by keyur32** [comment]
hi @vikasm1720, checking back to see if you had have a chance to add a sample repro of above so we can help investigate?
