### ISSUE TITLE
getSharedPropertiesAsync() on Mac Outlook returns false delegatePermissions information

### ISSUE THREAD

**Issue by naemcivic** [OfficeDev/office-js#1423]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

On Outlook Mac we are getting a 0 return value for `delegatePermissions` on a mailbox that has delegatePermission setup for a shared mailbox when calling `Office.context.mailbox.item.getSharedPropertiesAsync()` function.

Below is the the code example from the docs https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#getsharedpropertiesasync-options--callback- 
which I have followed and used in my code.

  
```javascript
if (!Office.context.mailbox.item.getSharedPropertiesAsync) {
  console.error("Try this sample on a message from a shared folder.");
  return;
}

Office.context.mailbox.getCallbackTokenAsync({ isRest: true }, function(result) {
  if (result.status === Office.AsyncResultStatus.Succeeded && result.value !== "") {
    Office.context.mailbox.item.getSharedPropertiesAsync(
      {
        // Pass auth token along.
        asyncContext: result.value
      },
      function(result2) {
        let sharedProperties = result2.value;
        let delegatePermissions = sharedProperties.delegatePermissions;

        // Determine if user can do the expected operation, e.g., do they have Write permission?
        if ((delegatePermissions & Office.MailboxEnums.DelegatePermissions.Read) != 0) {
          var ewsId = Office.context.mailbox.item.itemId;
          var restId = Office.context.mailbox.convertToRestId(ewsId, Office.MailboxEnums.RestVersion.v2_0);
          let rest_url =
            sharedProperties.targetRestUrl + "/v2.0/users/" + sharedProperties.targetMailbox + "/messages/" + restId;

          $.ajax({
            url: rest_url,
            dataType: "json",
            headers: { Authorization: "Bearer " + result2.asyncContext }
          })
            .done(function(response) {
              console.log(response);
            })
            .fail(function(error) {
              console.error(error);
            });
        }
      }
    );
  }
});

``` 

## Expected Behavior

It should return `delegatePermissions` value of 1 on a mailbox that has delegated permission on the shared mailbox 

## Current Behavior

Returns 0 on delegatePermissions

## Steps to Reproduce, or Live Example

Add a shared mailbox:

1. Find and Open a shared mailbox

Steps to reproduce:

1. Create a new email in Outlook for Mac
2. In the From field, select the shared mailbox
3. Open and add-in's pane and try to call `Office.context.mailbox.item.getSharedPropertiesAsync()`
4. Returns the wrong delegatePermissions value of 0 on a mailbox with delegation setup on a shared mailbox
 

* Additional details:

This is a blocker for us to try out the `getSharedPropertiesAsync()` fully.
Please see: https://github.com/OfficeDev/office-js/issues/1116#issuecomment-661864941

## Your Environment

* Platform: Mac
* Host: Outlook for Mac
* Office version number: 16.42 (20092705)
* Operating System: MacOS Catalina 10.15.16
* Browser (if using Office Online): N/A

**Comment by exextoc** [comment]
Thanks for reporting this issue . It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by naemcivic** [comment]
@exextoc 
Are there any updates on this as we are relying on this to work on our issue. thank you
