### ISSUE TITLE
Font Size Issue (12 pt font) With setDataAsync In A Word Add-in

### ISSUE THREAD

**Issue by gkarmelich** [OfficeDev/office-js#1424]
In a Word add-in, we are using the setDataAsync method to insert HTML into the document body. In this HTML, we have various font sizes that mimic most of the font sizes offered by Word. The setDataAsync method does not allow inserting HTML with the font size 12pt, however, all other font sizes work as expected.

## Expected Behavior

The setDataAsync method should insert font size 12pt.

## Current Behavior

When trying to insert font size 12pt, the setDataAsync method instead inserts 11pt font (the document default style). As mentioned, all other font sizes work as expected.

## Steps to Reproduce, or Live Example

* Example code below
```
Office.Binding.value.setDataAsync(`<div style="font-size: 12pt">hello world</div>`, {
        coercionType: Office.CoercionType.Html
      }, (asyncResult) => { });
```
The resulting text is of 11pt font (the default font size in the document). See the screenshot below.

## Your Environment

* Platform: PC (but issue persists on Mac as well)
* Host: Word
* Office version number: 2002 (Build 12527.21104)
* Operating System: Windows

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

<img width="508" alt="example-img" src="https://user-images.githubusercontent.com/32963798/94933632-f24d7700-04ca-11eb-8110-a3db12347bd5.PNG">

**Comment by lfglopes** [comment]
Two years after this issue was first filed and I'm having a similar issue... All sizes work except 12pt.

**Comment by jipyua** [comment]
hi @gkarmelich @lfglopes , for this issue reproted, I tried the following code on latest M365 version Office [16.0.17531.20152] and this doesn't reproduce anymore. This should have been fixed and feel free to have a try on the latest Office build.

function addBinding() {
  Office.context.document.bindings.addFromSelectionAsync(Office.BindingType.Text, { id: "mybinding" }, function(
    asyncResult
  ) {
    if (asyncResult.status == Office.AsyncResultStatus.Failed) {
      console.log("Action failed. Error: " + asyncResult.error.message);
    } else {
      console.log("Added new binding with type: " + asyncResult.value.type + " and id: " + asyncResult.value.id);
    }
  });
}

function setData() {
  Office.context.document.bindings.getByIdAsync("mybinding", function(asyncResult) {
    if (asyncResult.status == Office.AsyncResultStatus.Failed) {
      console.log("Action failed. Error: " + asyncResult.error.message);
    } else {
      console.log(asyncResult.value.id + "got Id");
      var binding = asyncResult.value;
      binding.setDataAsync(`<div style="font-size: 12pt">hello world</div>`, { coercionType: "html" }, function(
        asyncResult
      ) {
        if (asyncResult.status == Office.AsyncResultStatus.Failed) {
          console.log("Error: " + asyncResult.error.message);
        }
      });
    }
  });
}
