### ISSUE TITLE
Loading of the bing map when clicking on the Address

### ISSUE THREAD

**Issue by inderjitkr** [OfficeDev/office-js#1425]
I have appended the code for regular expression. when hovering on the address then the dialogue box is appearing. Can you please guide me how to activate the Bing map? 

The map is not getting loaded with the map images.

## Issue
Console Error : 
Cannot read property 'getSelectedEntities' of undefined at NLG.SuggestedAddresses.SuggestedAddressesExtension._getSelectedAddresses$p$1

Issue is of loading the map when clicking on the link of add
[MapLoading.docx](https://github.com/OfficeDev/office-js-docs-pr/files/5326340/MapLoading.docx)
ress

**Comment by Rick-Kirkham** [comment]
Please show the code context where you call `getSelectedEntities`.

**Comment by inderjitkr** [comment]
Hi Rick, This is the code I used -


            <ExtensionPoint xsi:type="DetectedEntity">
              <Label resid="contextLabel" />
              
              
              <SourceLocation resid="detectedEntityURL" />
              <Rule xsi:type="RuleCollection" Mode="And">
                <Rule xsi:type="ItemIs" ItemType="Message" />
                <Rule xsi:type="ItemHasKnownEntity" EntityType="Address" />
              </Rule>
            </ExtensionPoint>

> https://github.com/OfficeDev/office-js/issues/1425#issuecomment-703973274

**Comment by inderjitkr** [comment]
> Please show the code context where you call `getSelectedEntities`.

I didn't used this Rick. Instead I used this - 
 var item = Office.context.mailbox.item;
 var addresses = item.getEntitiesByType(Office.MailboxEnums.EntityType.Address);

**Comment by exextoc** [comment]
@inderjitkr We are not able to reproduce the issue with the above code snippet. Could you please share a sample add-in with us for reproducing it?

**Comment by inderjitkr** [comment]
Sorry for the delay due to some technical problem. I will provide the code.
[OutlookTry.zip](https://github.com/OfficeDev/office-js/files/5369859/OutlookTry.zip)

**Comment by inderjitkr** [comment]
can you please help me in the above problem?

**Comment by exextoc** [comment]
The addin provided by you doesn't load because it has unresolved references.
