### ISSUE TITLE
#REF! error when copying formula between workbook if EquivalentAddin is set in manifest

### ISSUE THREAD

**Issue by thitiphanjen** [OfficeDev/office-js#1426]
Got #REF! error when copying formula between workbook if EquivalentAddin is set in manifest file.

## Expected Behavior

Formula should be copied correctly.

## Current Behavior

Got #REF! error when copying formula between workbook if EquivalentAddin is set in manifest file.
![image](https://user-images.githubusercontent.com/21177487/95292058-f565b000-089a-11eb-8b66-8b9308f9d181.png)
![image](https://user-images.githubusercontent.com/21177487/95292659-1da1de80-089c-11eb-879a-cbddc78bdad2.png)

## Steps to Reproduce, or Live Example

1. Upload manifest with EquivalentAddin tag.
2. Add formula from the manifest to any cell.
3. Copy that cell to another workbook.

**Comment by grangeryy** [comment]
It is a known issue. The root cause is, copy and paste doesn't support this scenario yet. We'll track this request in our backlog and prioritize with other items together. You may try to retype the content in the destination workbook as a work around.
