### ISSUE TITLE
getSelection on table rows problem with Word API

### ISSUE THREAD

**Issue by stankonikolic** [OfficeDev/office-js#1428]
If user selects more than one row in the table (but not entire table), getSelection() function is returning corrupted result.
If I call getOoxml() (or getHtml()) function, the result is showing only the last row selected.
There is no way to implement even sample use case based on this selection, e.g. to change style of selected rows. 

## Expected Behavior

Resulting OOXML or HTML structure should contain all selected rows and cells.

## Current Behavior

Resulting OOXML or HTML structure contains only cells from the last selected row .

## Steps to Reproduce, or Live Example

1. Create new Word document
2. Insert empty table with several rows and columns
3. Populate table with distinct values

a | b | c
------------ | ------------- | -------------
d | e | f
g | h | i

4. Write the following script in ScriptLab:
```javascript
await Word.run(async (context) => {
    const selection = context.document.getSelection();
    selection.load();
    await context.sync();
    if (!selection.isEmpty) {
      const xml = selection.getOoxml();
      await context.sync();
      console.log(xml.value);
    } else {
      console.log("none");
    }
  });
```
5. Select at least 2 rows, but not entire table
example:

a | b | c
------------ | ------------- | -------------
d | e | f

6. Run the script

The result only contains cells with d, e, f.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Build 13231.20262 Click-to-Run
* Operating System: Windows 10 Enterprise 64

**Comment by AbidRahman-MSFT** [comment]
Thank you for reporting the issue. We were able to repro the issue and a fix has been made. The fix will be available on Word version greater than or equal to: 13523.10000.
