### ISSUE TITLE
Outlook Desktop, addFileAttachmentAsync with { isInline: true } adds inline attachment as usual/visible attachment

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1429]
In an Outlook add-in for compose mode, we are using the Office.context.mailbox.item.addFileAttachmentAsync method to add attachments including inline ones. If an email already contains a manually added attachment, addFileAttachmentAsync with { isInline: true } adds an inline attachment as a usual/visible attachment.

## Expected Behavior
When { isInline: true } the added attachment shall be hidden.

## Current Behavior
The added attachment is visible.

## Steps to Reproduce, or Live Example
1. Create a new email in Outlook.
2. Attach an Excel workbook to the email.
3. Open the add-in’s pane and execute the following code:

`Office.context.mailbox.item.addFileAttachmentAsync('http://i.imgur.com/WJXklif.png', 'cute_bird.png', { isInline: true },`
`  function () {`
`    Office.context.mailbox.item.body.setSelectedDataAsync(`
`      '<p>Here\'s a cute bird!</p><img src=\'cid:cute_bird.png\'>', { coercionType: Office.CoercionType.Html },`
`      function () { });`
`  });`

## Your Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: Outlook version 2009 (build 13231.20360)
* Operating System: Windows 10
* Browser (if using Office on the web): ______

## Useful logs
![untitled](https://user-images.githubusercontent.com/28924916/95457588-c8d49580-0979-11eb-95e1-8f075034aef2.PNG)

**Comment by exextoc** [comment]
Thank you for the detailed repro steps. I am able to repro this, and will open a bug on the backlog for the product team to look at. 

I did notice some workarounds that may be useful in the meantime. 

1) Using body.setAsync() avoids the problem. (though I understand that setAsync and setSelectedDataAsync() serve different purposes) 

2) If you save the item. (either through item.saveAsync() or manually clicking the save icon) then the problem will be fixed. 

3) Sending the mail fixes the issue. (the recipients will not see the image in the attachment well) 


Internal Tracking Id: 4540742

**Comment by DmitryKostochko** [comment]
1) The body.setAsync method does not suit us, sorry.
2) I also noticed that saving manually fixes the issue. But I have tried item.saveAsync() and this did not help for some reason...
3) I can confirm this, a recipient does not see the inline image in the attachments list.

Nevertheless, thank you very much for looking for workarounds. Do you have any timeline for fixing this issue?

**Comment by exextoc** [comment]
Sorry I don't have any timelines to share at this point.

**Comment by Techno11** [comment]
I'm experiencing the exact opposite in #1903 ... My 'inline' image doesn't show at all.  However, it could be a difference between `addFileAttachmentAsync` and `addFileAttachmentFromBase64Async`
