### ISSUE TITLE
[Outlook ] Exchange can not deploy add-in to Mac Outlook user

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1430]
Exchange can not deploy add-in to Mac Outlook user. 
Exchange version: Version 15.1 ‎(Build 1913.5)‎
Mac outlook version: 16.41 (20083005)

We can see deployed add-in on Windows web or Outlook application normally. But just can't see them on Mac outlook.

## Expected Behavior
Can see deployed add-in on Mac outlook.

## Current Behavior
1. login Exchange ecp with admin account
2. deploy an add-in to all (choose file)
3. wait one day for synchronization
4. Check with a user account on both Windows and Mac

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.41 (20083005)
* Operating System: Mac OS
* Browser (if using Office on the web): NA

Is this normal? Or are there any additional steps to be taken?

**Comment by exextoc** [comment]
- Can you please confirm if you're using New Mac UI or Old Mac UI ?
- Can you please share the Manifest file to "admin@a830edad9050849405E20081103.onmicrosoft.com" if possible, we'll try to reproduce the same from our end ?

**Comment by SWei1234** [comment]
Hi @exextoc 
 Sorry for reply late. I have send manifest xml to your mailbox. Please check it and reopen this ticket.
Thanks

**Comment by SWei1234** [comment]
Hi @exextoc 
I think this problem can be easy replicate.
Can I have any update ?
Thanks

**Comment by exextoc** [comment]
Can you please share the manifest file again and share the location for the file.

**Comment by SWei1234** [comment]
Hi @exextoc 
Can I still send the manifest to "admin@a830edad9050849405E20081103.onmicrosoft.com" ? 
Or other mail box?
Thanks

**Comment by exextoc** [comment]
@SWei1234  Please share the manifest to the new mailbox admin@M365x010952.onmicrosoft.com. You can also share the URL to a stripped-down version of the manifest with which we can repro the bug.

**Comment by exextoc** [comment]
Thanks for sending the manifest. We are working on reproducing the issue on our side.

**Comment by exextoc** [comment]
@SWei1234  We are not able to repro this issue on our side. Do you have a Test account that you can share with us to analyze the issue?

**Comment by exextoc** [comment]
@SWei1234 

1. If possible, can you please share test account so that we can repro with that account? We are not able to repro with given manifest file.
2. Can you please confirm if you're using New Mac UI or Old Mac UI ? It is possible that add-ins are not pinned on ribbon but are available in some overflow menu in UI?
3. Is it possible to capture network trace when "Outlook Mac" start fresh? Please share such network trace with us.
