### ISSUE TITLE
Office.OfficeTheme interface not supported in Office 365

### ISSUE THREAD

**Issue by harit-m-kumar** [OfficeDev/office-js#1431]
I have been trying to **get the background theme , colour using API's in Excel 365**.

https://docs.microsoft.com/en-us/javascript/api/office/office.officetheme?view=word-js-preview

But the Office.OfficeTheme API is not present in Excel 365. And the given link says that it is supported only in Office 365

https://www.eliostruyf.com/using-office-theme-colors-add/

Is there any way to **get the Office theme and colour in Office 365**. Or are there any alternate approaches for it?

**Comment by MandytMSFT** [comment]
@harit-m-kumar I'd like to confirm why you say "Office.OfficeTheme API is not present in Excel 365" ?  The document say this API is only supported in Office on Windows. That means this API can be used on Excel desktop, but excel on web/Mac/iOS can't. I tried it work on Excel desktop, Does this meet your requirement ?

**Comment by harit-m-kumar** [comment]
Hi,
I would like to add a clarification.
Office.OfficeTheme has no field called "bodyBackgroundColor" as shown in the first link posted.

Sorry for the miscommunication.

My actual requirement is that I should be able to get the theme color for the specific office application(green for excel, blue for word), using "Office.officeTheme.bodyBackGroundColor" or any similar API.

**Comment by MandytMSFT** [comment]
@harit-m-kumar Office.OfficeTheme do have field called bodyBackgroundColor. I tried this gist: https://gist.github.com/MandytMSFT/2f8a2116b7c74bf2a518a9db059e3c54 on Excel Desktop , it returned 
#e6e6e6 for bodyBackgroundColor.

But looks like it's not green color that you expected, is this your point ?

**Comment by harit-m-kumar** [comment]
This code works in the Desktop version, but not in the onlone version.
In the online version, it says that the key "OfficeTheme" does not exist within Office.OfficeTheme
![OfficeColorInExcel](https://user-images.githubusercontent.com/58638877/99788226-ce132b80-2b46-11eb-8274-ebc6b5cc7991.PNG)

**Comment by harit-m-kumar** [comment]
The above code fragment works fine for Office desktop version, but not for Office online. It says that Office.context does'nt have a theme called OfficeTheme.

**Comment by MandytMSFT** [comment]
@harit-m-kumar Yes, as mentioned in our official document (https://docs.microsoft.com/en-us/javascript/api/office/office.officetheme?view=word-js-preview), office.theme is only supported on Excel Desktop and not on Office online. 

We track Office Add-in feature requests on our [UserVoice page](https://officespdev.uservoice.com/) Please add your request there. Feature requests on user-voice are considered when we go through our planning process.

**Comment by lumine2008** [comment]
as this is a new feature request, so let me close this issue, and track in uservoice. thanks

**Comment by rkkp1023** [comment]
The documentation states that `Office.context.officeTheme` is supported in Excel Web, but when we attempt to access it, we receive an `undefined` value.

Referencing doc: https://learn.microsoft.com/en-us/javascript/api/office/office.officetheme?view=excel-js-preview

opened issue: https://github.com/OfficeDev/office-js/issues/6134#issuecomment-3316575289

**Comment by RuizhiSunMS** [comment]
@rkkp1023 I will reach out to the owning fc. Will update here if got the answer.
Thx.
