### ISSUE TITLE
Some Users unable to access Admin Managed Add-In section

### ISSUE THREAD

**Issue by meladm** [OfficeDev/office-js#1432]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We have a few users that are missing the add-ins (in detail we use the officeatwork add-ins) we deploy using centralized deployment. When they want to check the admin managed section (Word 365 on Windows, latest version) they get a login screen with some random characters already filled in. It does not accept the users Microsoft 365 credentials.

## Expected Behavior
Deployed Add-Ins load automatically for signed in Users or Users can at least see them when they access the admin managed section.

## Current Behavior
They get a login screen with some random characters already filled in. It does not accept the users Microsoft 365 credentials. 

## Steps to Reproduce, or Live Example
I am unable to reproduce the issue on another Machine. It seems to be something User Profile related. 
We already tried the following without success:
- Signed out and in in Office
- Deleted all Office related Credentials in "Windows Credentials"
- Online repair of Office
- Reset Internet Explorer (and checked Safe mode etc.)

## Context
Some Users are unable to use the add-ins and cannot get them back. For most other Users it seems to work (or they did not contact the IT dept.)
Maybe this issue is related to the fact, that we had to re-depoly these Add-Ins as officeatwork asked us to do so because of some changes on their side. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: HP Laptop 
* Host [Excel, Word, PowerPoint, etc.]: Word (also happens in the other Applications)
* Office version number: 2009 (click-to-run)
* Operating System: Windows 10
* Browser (if using Office on the web): -
* We use Exchange Online

## Useful logs
Here is an Image of the Window that comes up: 
![admin_managed](https://user-images.githubusercontent.com/72734263/95729582-60d5c600-0c7d-11eb-91c7-0c49e527812d.jpg)

**Comment by MartinSSeifert** [comment]
@JuaneloJuanelo, this seems to me, to most likely be the same behavior you witnessed during our last meeting!

**Comment by JuaneloJuanelo** [comment]
@meladm thanks for reporting this. We actually need more details to investigate this isssue.
As @MartinSSeifert  suggests, we experienced a similar behavior, what  I noticed back then is that the user who was logged-in in the device was using a Microsoft Account (i.e. @outlook.com account) and they trying to get Add-ins deployed in the organization, and for that an Organizational Account is needed. Right @MartinSSeifert ? 

is this the same case for you?

can you describe the accounts used to log in in the machine? 

also please add the build details, in what builds are you experiencing this?

**Comment by meladm** [comment]
@JuaneloJuanelo thanks for your reply. The user ist logged-in in the device with an organizational account (AAD, Company owned and Intune managed device). So the case seems not to be the same.

Currently the user is on build 13231.20262 and I've asked her to check for updates and try again. She will let me know tonight.

**Comment by JuaneloJuanelo** [comment]
@meladm  thanks! I am assuming in the same Organization where the add-in was deployed, right?

**Comment by meladm** [comment]
@JuaneloJuanelo  correct, everything is inside the same Org. I just got her reply: 2010 Build 13328.20292 and the issue still exists.

**Comment by MartinSSeifert** [comment]
@JuaneloJuanelo has there been any progress made on this case? Do you have any updates you could share?

**Comment by meladm** [comment]
I came across a similar issue: https://answers.microsoft.com/en-us/msoffice/forum/all/office-add-ins-disappearing-due-to-multiple-office/f92ad961-7389-42e1-8a50-94f3344905a1
