### ISSUE TITLE
Outlook Add in pinning does not work in Shared folders - Outlook Office Webmail - SupportsPinning and SupportsSharedFolders

### ISSUE THREAD

**Issue by davyarris** [OfficeDev/office-js#1433]
## Summary
We have implemented an Outlook Add in that uses the SupportsPinning option from Req Set 1.5 and the SupportsSharedFolders option from Req Set 1.8. Both options are working fine in Windows Outlook Native client but malfunction in Outlook Office Webmail - https://outlook.office.com/mail/login.html (tested in latest Chrome, IE and Edge).

## Steps to Reproduce, or Live Example
These are the steps:

1. Open Shared Inbox in Outlook 365 Webmail - https://outlook.office.com/mail/login.html
2. Select email
3. Open Add-in
4. Pin Add-in
5. Select another email

## Expected Behavior
Add-in window remains open

## Current Behavior
Add-in window closes

The other strange thing is that if you then select another message, the add-in remains closed BUT if you select an email that you previously opened the add-in on, in the shared inbox, the add-in reopens.

No ItemChanged event is recorded.

## Context
This is a problem as we are attempting to support both Shared Folders and Pinning. It's working perfectly in Native.

## Your Environment
* Platform: Windows 10
* Host: Outlook Office Web - IE 11, Chrome Version 85.0.4183.121 (Official Build) (64-bit), Edge Version 85.0.564.70 (Official build) (64-bit)
* Office version number: 365 Office Version 2008 13127.20408

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

**Comment by davyarris** [comment]
Thanks for letting us know @exextoc . Given that it's working fine in Native Shared folders and web standard folders makes me think that it's pretty close.

**Comment by exextoc** [comment]
Closing issue for now since this is now in our backlog. Thanks!
