### ISSUE TITLE
New UI in Outlook for Mac. conversationId property isn't null when user creating new message

### ISSUE THREAD

**Issue by lavrynenko-devpro** [OfficeDev/office-js#1434]
On the old outlook UI when adding a template from an add-in, a subject was added after checking the conversationId. It was `null` when new message was created, and there was id of conversation when replied on message.
```
  if (!this.item.conversationId) {
      this.setSubject(subject)
    }
```
Now conversationId property has value even when new message created, so subject do not change.

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

**Comment by dmitry-semenov** [comment]
@exextoc can you suggest a workaround that can be used to determine new email thread?

**Comment by exextoc** [comment]
Unfortunately there isn't any way currently in the New Mac UI. 
For OWA/win32 clients you can use [getComposeType](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#getcomposetypeasync-options--callback-) .

**Comment by dmitry-semenov** [comment]
@exextoc sorry for bumping this, just want to understand is the issue closed due to being fixed in the latest builds or not?

**Comment by exextoc** [comment]
As mentioned, unfortunately we do not have any workarounds in new Mac UI. However you can use it for other clients like OWA and Win32. Also this issue has been added to our backlog. But we do not have any timelines to share at this point.

**Comment by exextoc** [comment]
@dmitry-semenov Please try out the [Autorun add-ins ](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch) with OnNewMessageCompose and OnNewAppointmentCompose events. We believe this will serve your purpose.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
