### ISSUE TITLE
on send addin is not invoked with new outlook feature of outlook vesion 16.42

### ISSUE THREAD

**Issue by dlpsysqa** [OfficeDev/office-js#1435]
on send addin is not invoked when outlook is used in "New outlook" feature for the version 16.42.

**Comment by wamaina** [comment]
@dlpsysqa could you please provide the steps to reproduce this issue or a Live sample?

**Comment by dlpsysqa** [comment]
steps to reproduce
1. on mac update the outlook to version 16.42
2. run the outlook in "New outlook" mode. this is new outlook with UI changes which MS has released
3. sideload the attached manifest file that is the on send  addin
4. compose a mail and click on send button. this doesnt trigger the addin loaded in step 3
attached is the manifest file change the file extension to xml
[manifest.txt](https://github.com/OfficeDev/office-js/files/5381882/manifest.txt)

**Comment by westconference** [comment]
@dlpsysqa New Outlook for Mac UI doesn't support on-send yet according to their docs.

> Outlook add-ins are now supported in the new Mac UI, up to requirement set 1.7. However, the following requirement sets and features are NOT supported yet.
> * API requirement set 1.8
> * Contextual add-ins
> * On-send
> * Shared folder support
> * saveAsync when composing a meeting

https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/compare-outlook-add-in-support-in-outlook-for-mac#new-outlook-on-mac-preview

**Comment by dlpsysqa** [comment]
@westconference  does  on send addin is not supported only on preview builds or it applies to release version of 16.42 also?.

from 16.42 new outlook feature is available in production builds.

below documentation for the production builds doesn't mention any limitation about on send addin.
https://support.microsoft.com/en-us/office/the-new-outlook-for-mac-6283be54-e74d-434e-babb-b70cefc77439

**Comment by exextoc** [comment]
Currently the feature on-send, you requested, is not a part of the product New Mac UI. 
We track Outlook add-in feature requests on our user-voice page. Please add your request there. Feature requests on user-voice are considered, when we go through our planning process.

**Comment by Premsagar-lab** [comment]
Hi @exextoc, is it possible to share the link of user-voice page?

**Comment by exextoc** [comment]
Please find [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins) here.

**Comment by JuaneloJuanelo** [comment]
a few clarifications on this issue.

1. Thanks for trying the new Mac UI, but at the time of this writing is still considered  preview and not considered released.
2. While the OnSend Feature (shipped as part of Mailbox 1.8) is not yet supported in the new Mac UI, the team is actively working on it and looking forward to release it in the short term. So there is no need to add this to user-voice.
3. it is possible for an organization admin to block the rollout of the new Outlook UI by Using the EnableNewOutlook Preference Key. PLease see [this article](https://docs.microsoft.com/en-us/deployoffice/mac/preferences-outlook) (scroll all the way down) for more details.
