### ISSUE TITLE
WebView2 Task Pane displays error during HTTP Authentication

### ISSUE THREAD

**Issue by westconference** [OfficeDev/office-js#1436]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

On an environment configured to use Edge WebView2 on Outlook Beta channel, the Outlook task pane displays an error when it encounters a HTTP Authentication 401 challenge, 'Add-in Error: This add-in could not be started'. The task pane shows the login prompt correctly and can proceed with login however the error banner remains unless dismissed.

## Expected Behavior
The described error banner should not appear and should be able to proceed with login using HTTP Authentication. This is how the task pane functioned with IE11 and Edge WebView1 as the browser in previous Outlook versions.

## Current Behavior
Error banner displayed in task pane when navigating to perform HTTP Authentication. Appears when the 401 challenge is issued.

## Steps to Reproduce, or Live Example
Only occurring on Beta Channel Outlook configured to use Edge WebView2 as described in documentation [here](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins).
Create a manifest that opens a task pane to a site that uses HTTP Authentication.
* The site may consist of an initial landing page and then a button to perform the authentication.
Observe that attempting to perform HTTP authentication causes an error banner to be displayed in task pane at the same time the login credentials prompt appears.
Example manifest using a public site attached.
* [challenge_auth_site.txt](https://github.com/OfficeDev/office-js/files/5379722/challenge_auth_site.txt)
** Change extension to xml.
** Scroll down site and click the 'protected page' link. Should be prompted for credentials and see error banner.

## Context
Our add-in opens a task pane to a landing screen where user enters their username and then clicks authenticate which begins the HTTP Authentication process. This error banner will confuse them and make it appear the add-in is broken if they upgrade their Outlook.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook 365
* Office version number: Version 2011, 16.0.13408.20000 64-bit (Beta channel)
* Operating System: Windows 10 Pro 2004 (all updates installed as of 2020-10-14)

## Useful logs
![task pane error banner](https://user-images.githubusercontent.com/64404605/96021235-10aa5f80-0e47-11eb-983a-d4b0860a6728.png)

![task_pane_error_401](https://user-images.githubusercontent.com/64404605/96021347-2f105b00-0e47-11eb-9f59-705d90b89c36.gif)

**Comment by westconference** [comment]
@smaremanda hi, has there been any progress on this? Were you able to reproduce it internally?

**Comment by smaremanda** [comment]
@westconference - thanks for bringing this up during the community call this am. We're working on this issue along with the Edge team. I can confirm that we are able to repro this internally. Will keep you updated on the progress.

**Comment by westconference** [comment]
@smaremanda this is still occurring, any updates? Getting worried as the documentation says WebView2 is going to be rolling out at the end of March.

**Comment by zunquan** [comment]
@westconference. this is a known issue in WebView2. We are waiting for a fix from WebView2. In the meantime, we have a mitigation for the 1st time when this happens during an addin's activation. Basically, when an user activates your addin, he\she will see the login prompt WITHOUT the error banner. But if he\she inputs wrong creds and triggers the login prompt again, the error banner will show. The mitigation is in build 16.0.13525.10000 and later.

**Comment by gitchristopher** [comment]
Has there been any development on this?
I am creating an add-in that is suffering from this error when a user logs in.
