### ISSUE TITLE
 Dialog window does not support add-in for the new Outlook for Mac

### ISSUE THREAD

**Issue by Petryxasport** [OfficeDev/office-js#1438]
Our clients are using new Outlook design 16.42 (20101102)
Our Add-in uses functions: reply/replyAll/forward they open Dialog window(pop-up) and this window does not support add-ins.
This is really critical issue, because our clients use pinned panel of add-ins to complete their workflow.
Could you please clarify when can we use the add-in inside Dialog window for european region?

**Comment by exextoc** [comment]
Currently the feature add-ins inside pop-up window, you requested, is not a part of the product New Mac UI. We track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered, when we go through our planning process.

**Comment by Petryxasport** [comment]
@exextoc It' s quet strange to have a new Design without supporting previous functionalities. :( Can you suggest any workaround for our product? Perpheps we can do "reply/replyAll" into current window without oppening via pop-up or something.

**Comment by exextoc** [comment]
Yes "reply/replyAll" in the current window will work.
