### ISSUE TITLE
"Outlook for web" is not able to send attachments with API call "addFileAttachmentFromBase64Async"

### ISSUE THREAD

**Issue by AdielAhmad** [OfficeDev/office-js#1439]
## Expected Behavior

I am expecting to receive attachments added from an Outlook-Addin inside "Outlook for web".
## Current Behavior

It seems like "Outlook for web" is not able to add Image-Files as attachments correctly when adding them from my Outlook-Addin (they are visually available while writing the mail, but dont appear in the sent mail) , this behaviour only applies to "Outlook for web", the Addin-Workflow works as intended inside the Desktop-Application.

## Steps to Reproduce, or Live Example

* Link to live example: [https://streamable.com/d1ckl3](https://streamable.com/d1ckl3)

## Context

I am adding the attachments (PNG, JPEG, DOC) with the API call `addFileAttachmentFromBase64Async` from the Outlook-API and sending the Mail to myself, but only the .doc-File appears.

## Your Environment

* Platform: PC desktop
* Host: Outlook for web
* Operating System: Windows 10
* Browser: Firefox, IE11

**Comment by exextoc** [comment]
We are able to reproduce this from our side. Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by AdielAhmad** [comment]
Hi @exextoc is there any new information, regarding this topic?

**Comment by exextoc** [comment]
Hi @AdielAhmad this issue is still in our backlog. We do not have an update yet, but we will update this thread once we do.
