### ISSUE TITLE
Unable to set cookie

### ISSUE THREAD

**Issue by whowhatwhen** [OfficeDev/office-js#1443]

**Comment by jeremy-msft** [comment]
Hi @whowhatwhen, this is a [limitation](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-authentication) of the UI-less custom functions runtime.  We recommend you use a [shared runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/configure-your-add-in-to-use-a-shared-runtime) if you require browser cookie support for your custom functions.
