### ISSUE TITLE
Office add-in is not rendering properly in safari browser version 11.1.2.

### ISSUE THREAD

**Issue by rai1109** [OfficeDev/office-js#1444]
In Safari browser v11.1.2, the Installed add-in is not rendering properly. The add-in reserved space is not completely utilized. which means, It has height issue.
## Expected Behavior
When you install add-in from office store it should cover over all right panel of the excel. Find attached image for more info.

![Screenshot (61)](https://user-images.githubusercontent.com/53037339/96263653-dd9bd380-0fe0-11eb-8feb-6962667c718d.png)
![Screenshot (60)](https://user-images.githubusercontent.com/53037339/96263659-df659700-0fe0-11eb-9e62-1526dd73e4dd.png)

## Current Behavior
As you can see add-in  in right panel it is taking only 40%  of total height, rest it is showing blank. 

![Screen Shot 2020-10-13 at 12 49 29 PM](https://user-images.githubusercontent.com/53037339/96246117-d1eee380-0fc5-11eb-9401-48685185b830.png)
![Screen Shot 2020-10-13 at 12 16 21 PM](https://user-images.githubusercontent.com/53037339/96246127-d4513d80-0fc5-11eb-859a-4d01c5c62142.png)

## Steps to Reproduce, or Live Example
Open online excel in your safari browser (v11.1.2) and try to open any add-in and thus the scenario got reproduce.

## Your Environment

- Platform : Laptop
- Operating System: MAC OS, X
- OS - Version: 10.11.6
- Browser : Safari-version- 11.1.2

**Comment by jeremy-msft** [comment]
@rai1109, thanks for reporting this; we've identified the problem and were able to fix the issue.  Please let us know if the problem is still not resolved for you.
