### ISSUE TITLE
Outlook for Mac: Office.context.mailbox.item.body.getTypeAsync returns "An internal error has occurred" after several (3-5) calls

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1445]
In an Outlook add-in for compose mode, we are using Office.js methods to fill in email fields. The getTypeAsync method stops working after a few executions in case of Outlook for Mac.

## Expected Behavior
The method should work.

## Current Behavior
The getTypeAsync method stops working after 3-5 executions.

## Steps to Reproduce, or Live Example
I have created a test add-in, you can install it using the link to manifest below.

Steps:
- Create a new email in Outlook for Mac
- Start the add-in
- Click the "Test getTypeAync" button several times
- Observe the results added to the text area below the button

In out tests, we've noticed that 3 clicks work, and then the "An internal error has occurred" error occurs on all subsequent attempts.

Code:
`var attempt = 0;`
`function getTypeAsyncTest() {`
`  attempt += 1;`
`  Office.context.mailbox.item.body.getTypeAsync({}, (asyncResult) => {`
`    if (asyncResult.error) {`
`      document.getElementById("logger").value += '### Error getTypeAsync ' + attempt.toString() + ': ' + asyncResult.error.message + '\r\n';`
`    } else {`
`      Office.context.mailbox.item.body.setSelectedDataAsync('#test' + attempt.toString(), { coercionType: asyncResult.value }, (asyncResult1) => {`
`        if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {`
`          document.getElementById("logger").value += '### Succeeded setSelectedDataAsync ' + attempt.toString() + '\r\n';`
`        } else {`
`          document.getElementById("logger").value += '### Error setSelectedDataAsync ' + attempt.toString() + ': ' + asyncResult.error.message + '\r\n';`
`        }`
`      });`
`    }`
`  });`
`}`

* Link to live example: https://online-addins.ablebits.com/testaddin/manifest.xml

I have also attached the source code:
[index.zip](https://github.com/OfficeDev/office-js/files/5408868/index.zip)

## Your Environment
* Platform: Mac
* Host: Outlook for Mac
* Office version number: 16.42 (20101102)
* Operating System: Catalina 10.15.7
* Browser (if using Office on the web):

**Comment by exextoc** [comment]
We are able to reproduce this from our side. Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by gena7gena** [comment]
Hi!

Also both `getAsync` and `setAsync` stop working after first use, for `Office.context.mailbox.item.body`, `Office.context.mailbox.item.location` and other fields. Error is 5001 ('Internal error occurs') again.

Looks like the same issue.

Environment is exactly the same as described in original post.

**Comment by exextoc** [comment]
Have updated the backlog issue with additional detail.

**Comment by exextoc** [comment]
@DmitryKostochko @rinfex-holfer  Could you please confirm if are you still facing this issue in latest versions of Mac Outlook?

**Comment by DmitryKostochko** [comment]
@exextoc, I have just tested the issue with Outlook for Mac version 16.44 (20121301) and it is not fixed, sorry.
