### ISSUE TITLE
Excel crashes while loading a named item which contains custom function that has @requiresAddress attached.

### ISSUE THREAD

**Issue by Shubhajit01** [OfficeDev/office-js#1446]
We have an add-in that contains a custom function.
That function has the  **@requiresAddress** tag.
It works perfectly fine when used in any cell.

Now, I have a named item with that function as the value/formula.
Whenever I try to load the items for ```context.workbook.names```, excel crashes and reloads.
Even just loading that particular named item, the same issue occurs.

## Expected Behavior
Excel should be able to load the name and the formula used.
And, maybe return some kind of error code for the value and type. For example: '#CALC!'.
Also, Excel shouldn't crash.

## Current Behavior
On loading the named items, excel is crashing and showing an message.
On clicking the ok button, screen refreshes.

## Steps to Reproduce, or Live Example
* Link to live example: 
 1. Custom Function Gist: https://gist.github.com/Shubhajit01/d8b3410f311692da7dfdd7bd93c07df5
 2. Sample Named Item Code Gist: https://gist.github.com/Shubhajit01/badccc9c7f410d268ffaa13f20dbdb16

The custom function gist url contains two function.
The one which doesn't uses **@requiresAddress** works fine with the named item but the other one fails.

* Steps to reproduce:
  * Create a new workbook.
  * Use the custom function gist to register the custom functions.
  * Use the Sample Named Item Code Gist and click on the buttons in the following orders:
    * Set Named Item [This will insert the named items]
    * Get & Load Named Item Without Address [This will successfully fetch the named Item]
    * Get & Load Named Item With Address [This will fail to get the data and throw error]
    * Get & Load All Named Items [This will fail to get all the items]

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Browser (if using Office on the web): Google Chrome

## Useful logs

- Error In Chrome Console

![Chrome_Console_Error](https://user-images.githubusercontent.com/43203087/96590388-94f75980-1303-11eb-8bba-3fedb1cf223b.png)
- Error Message In Excel Sheet

![Excel Sheet](https://user-images.githubusercontent.com/43203087/96590408-9c1e6780-1303-11eb-8355-2e27d58fc88f.png)

**Comment by grangeryy** [comment]
@Shubhajit01 We can reproduce it and create a bug (BUG 4576906) for it.

**Comment by grangeryy** [comment]
Hi @Shubhajit01, this bug was fixed. Please have a try and let me know whether it works. Thx!
