### ISSUE TITLE
Word Online: bugs when inserting OOXML containing OMML equations in a document

### ISSUE THREAD

**Issue by mathtypeengineering** [OfficeDev/office-js#1448]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Inserting OMML equations using OOXML in Word documents works just fine in Word Desktop and Word for iPad but results in several bugs and crashes that make it unusable when done in Word Online.

## Expected Behavior

Insertion of OMML equations using OOXML in Word Online works.

## Current Behavior

Here are the main issues we've found:

  * When inserting an equation by itself in a paragraph everything looks OK.
  * Inserting a second equation in the same paragraph will insert it offset by as many positions as equations before the caret. If this would make the caret go out of bounds for the current paragraph this will throw a "General exception: unknown" error.
  * Sometimes the inserted equations are visible by the user but aren't stored in the document, usually after an error happens. Reopening the document or refreshing the page will make these equations disappear, even though Word Online shows that the document has been saved.

![office1](https://user-images.githubusercontent.com/73217484/96696553-2eb61980-138b-11eb-9bed-17e9f7510942.gif)

![office2](https://user-images.githubusercontent.com/73217484/96696562-31b10a00-138b-11eb-9a56-bd7eaaed1dfc.gif)

Some other issues that we've found while toying around:

  * Inserting a new equation sometimes makes the previously inserted equations in the document disappear completely or turn into `OBJ` markers.
  * Retrieving the OOXML of the equations sometimes throws an `ooxmlIsMalformated` exception. Can be reproduced by inserting an equation via the Script Lab sample in a new paragraph by itself, selecting it and pressing "Get OOXML".
  * Word Online crashing completely, needing a page refresh. **Thankfully this hasn't happened in a while.**

## Steps to Reproduce, or Live Example

* **Link to Script Lab gist**: https://gist.github.com/mathtypeengineering/3b2eff0c201cadb3768fd6fdaced23a8

## Your Environment

* **Platform**: Office on the web
* **Host**: Word
* **Office version number**: 16.0.13416.41000 (although the issues were found 2+ years ago)
* **Operating System**: Windows, Linux
* **Browser**: Firefox, Chrome, Edge

## Useful logs

* **Link to Imgur album showcasing some of the issues**: https://imgur.com/a/8EHDc

**Comment by MandytMSFT** [comment]
Thanks for reporting. BUG 4580433 has opened for internal track
