### ISSUE TITLE
Range.getDirectPrecedents issue when equivalent XLL are specified

### ISSUE THREAD

**Issue by sshukurov** [OfficeDev/office-js#1449]
We are developing an Excel JS addin which makes use of custom functions, and we also have equivalent XLL specified in our manifest for compatibility with our legacy COM addin. We welcome Office JS team's efforts on constantly bringing new functionality to us, one of the latest of which is `Range.getDirectPrecedents` api.

Invoking the api mentioned on a cell which contains one of our custom functions and a further `context.sync()` is throwing an "internal error" with no meaningful description. We spent a while trying to figure out the error cause, and we finally managed to find out that we don't get any error if we remove `EquivalentAddins` tag from our manifest.

## Expected Behavior
No error, direct precedents returned.

## Current Behavior
We are getting **RichApi.Error: An internal error has occurred.**
![image](https://user-images.githubusercontent.com/36232686/96715082-87ea7100-13bc-11eb-806d-8189aeb521bb.png)

Any further manipulation within workbook leads to the error modal being displayed:
![image](https://user-images.githubusercontent.com/36232686/96715266-c08a4a80-13bc-11eb-9f42-40288b968b84.png)

## Steps to Reproduce, or Live Example
Minimal repro: https://github.com/sshukurov/getDirectPrecedentsIssue

1. Build and run the repro on Excel on the web instance.
2. Insert numbers to a couple of cells.
3. Insert a formula on a third cell referencing the cells with numbers: `=ADD(FirstCell, SecondCell)` (note the `CONTOSO` prefix is not needed because XLL equivalence is specified in the manifest).
4. Select the cell with the formula, click 'Run' on the addin's side panel.

## Your Environment
* Platform: Office on the web
* Host: Excel
* Operating System: Windows 10 Pro Version 2004 OS build 19041.572
* Browser: Google Chrome Version 86.0.4240.111 (Official Build) (64-bit)

**Comment by lumine2008** [comment]
Thanks @sshukurov for reporting this issue, we can repro this issue, a bug(4580782) is created to track this issue.

**Comment by wh1t3cAt1k** [comment]
Hey guys, also encountering this issue, any update so far? @lumine2008

**Comment by lumine2008** [comment]
Thanks @wh1t3cAt1k for your ask, the issue was fixed, it is rolling out stage, but not yet deployed to production.

**Comment by sshukurov** [comment]
@lumine2008, has the fix reached the production yet?

**Comment by lumine2008** [comment]
this issue was fixed, please validate, thanks

**Comment by sshukurov** [comment]
I confirm the issue no longer reproduces. Thank you very much!
