### ISSUE TITLE
Easiest way to move a message to junk folder via REST API?

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js#145]
Looking at the [Outlook Mail REST API reference](https://msdn.microsoft.com/en-nz/office/office365/api/mail-rest-operations), there is no simple way to move a message to the Junk folder.

It seems that the `DestinationId` can't be `JunkEmail` . It's not listed here: 

> The destination folder ID, or the Inbox, Drafts, SentItems, or DeletedItems well-known folder name.

Plus there is no API yet for flagging.

Any suggestions?

**Comment by mlafleur** [comment]
The [documentation ](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/message_move )simply fails to list all of the known-folders.  I was able to send a message to Junk using this:

``` json
{
  "destinationId": "JunkEmail"
}
```

I've reported this as an issue with the documentation in the MIcrosoft Graph documentation repo: https://github.com/microsoftgraph/microsoft-graph-docs-contrib/issues/7842

**Comment by binarykitchen** [comment]
Ah, that wasn't very clear in the documentation. And what happens if the known-folder "JunkEmail" doesn't exist while moving? Will it be automatically created?
