### ISSUE TITLE
Outlook Desktop: WWAHost.exe and Win32WebViewHost.exe hang after closing Outlook

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1450]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We are developing an Outlook add-in for compose mode. Recently, we've noticed hanging WWAHost.exe and Win32WebViewHost.exe processes in the Task Manager.

## Steps to Reproduce, or Live Example
1) Start Outlook.
2) Create a new email.
3) Open an add-in's pane.
4) Return back to the main Outlook window and close it.
5) The new email window is closed automatically.
6) Check the WWAHost.exe and Win32WebViewHost.exe processes in the Task Manager.

* Additional details:
1) The issue does not occur if you close the new email window first.
2) As far as I can see, the issue can be reproduced with any add-in for compose mode.

## Your Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: Version 2010 (Build 13328.20210)
* Operating System: Windows 10 Version 2004 (build 19041.572)
* Browser (if using Office on the web):

**Comment by exextoc** [comment]
Thanks for reporting this issue. I'm able to reproduce it with your repro steps.

I've added this issue to our backlog for further investigation (internal tracking id Office:4584153).

**Comment by exextoc** [comment]
Updated internal tracking id (Microsoft: 30684890)

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Is there a different assignee needed for this issue?
