### ISSUE TITLE
Outlook Online + IE11: Unable to move to another site in a pop-up window created by displayDialogAsync method

### ISSUE THREAD

**Issue by shumach5** [OfficeDev/office-js#1453]
In outlook online + IE11, when our Office outlook add-in opens a pop-up window, the add-in tries to redirect users to another site such as `https://login.microsoftonline.com` for authentication by setting the value to `window.location.href`. This approach works on Chrome, but not working with outlook online + IE11. The popup window is created by `Office.context.ui.displayDialogAsync` method.

## Expected Behavior
When users click the link inside a pop up window in IE11 + outlook online, the page should be redirected to the new site.

## Current Behavior
Even though user clicks the link in the pop up window, the pop up window does not change.  (It keeps displaying the same page)

## Steps to Reproduce, or Live Example
1. Create a pop up window by calling `Office.context.ui.displayDialogAsync` method like followings.
```
const dialogScaleInDeviceWindow = 60 //Show dialog 60% of device window
export const ShowAuthDialog = (mode: dialogMode, exToken: string | undefined): void => {
    Office.context.ui.displayDialogAsync(
        'https://<test.com>/signupcontainer',
        {
            height: dialogScaleInDeviceWindow,
            width: dialogScaleInDeviceWindow,
            promptBeforeOpen: true,
            asyncContext: { location: true }
        },
        (asyncResult: Office.AsyncResult<Office.Dialog>) => {
            // This callback is triggered when Pop-up window open
        }
    )
}
```
2. In a pop up window, make the following html appear 
```
//Javascript (we use react)
  <div className="SignUpContainer">
                <div className="Secretary">Secretary</div>
                <div className="SignUpMessage"> Please Sign-up with your Microsoft account </div>
                <img
                    src={<any logo>}
                    alt="logo"
                    width="200"
                    height="40"
                    onClick={() => startAuthorization(dispatch, email)}
                />
            </div>

const startAuthorization = (email?: string): void => {
    const urlElements: string[] = [
        `https://login.microsoftonline.com/common/oauth2/v2.0/authorize?`,
        `client_id=${clientId}`,
        `&response_type=code`,
        `&redirect_uri=${createEncodedRedirectUrl()}`,
        `&response_mode=query`,
        `&scope=${createEncodedScopeString()}`
    ]
    if (email) urlElements.push(`&login_hint=${email}`)

    window.location.href = urlElements.join('')
}
``` 

* Additional details:
  1. I tried changing the value of `window.location.href` from IE11 console on developers tool such as `window.location.href = "https://google.com", but it was not changed.

2. I also saw the following article and tried them, but none of them worked.
https://stackoverflow.com/questions/28872598/window-location-href-not-working-in-ie-11

3. In a pop up window created by ``Office.context.ui.displayDialogAsync` method, even a very simple <a href="https://google.com"></a>  does not work. 

4. I've added the urls at manifest.xml like this, but it did not solve the problem. (I've added the google just for the test)

```
<AppDomains>
    <AppDomain>https://localhost:3000</AppDomain>
    <AppDomain>https://www.google.com</AppDomain>
  </AppDomains>
```

## Your Environment
* Windows 10 Build 2004
* IE 11: 11.572.19041.0

**Comment by shumach5** [comment]
Because of this bug, we cannot pass our app store review... so I'd highly appreciate if you take a look at this issue soon.

**Comment by exextoc** [comment]
@shumach5  We are not able to repro this issue. Do you see any errors in the console on attempting to redirect? 
Could you please share a stripped down version of the manifest/add-in with which issue can be reproed?

**Comment by shumach5** [comment]
@exextoc Sorry for the late reply. Actually once we added the url into `Trusted Zone` in IE11, it worked! So I am gonna close this issue. Thank you for your support!
