### ISSUE TITLE
Mobile does not support add-ins in compose mode

### ISSUE THREAD

**Issue by d-franklin** [OfficeDev/office-js#1455]
Unlike desktop or web version of add-ins, mobile does not support the ability to be accessed when in compose mode for mobile.

## Expected Behavior
It is expected that there is parity between version so the user experience is uniform. Being unable to offer this to end users, especially when mobile first has been accepted practice for several years, puts developers, end users and even Microsoft at a disadvantage compared to alternative solutions.

## Current Behavior
Add-ins are unable to run in compose mode for mobile.

## Context
I am aware there is a request on [uservoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/35738695-support-compose-addin-on-mobile) which is the 3rd requested feature for outlook add-ins, 2 years old and unfortunately has been ignored by MS.

I am hoping that a github issue might gain some traction for this issue.

While some would consider this a feature request, I personally don't see having parity between platforms as a feature, instead I see not having parity as a bug.

The reason being that the inability to offer end users a universal experience across platforms leaves the user with a broken, confusing and frustrating experience.

**Comment by exextoc** [comment]
Add-in support on mobile compose is under review and we are working on defining the right UX experience for mobile users. Unfortunately we do not have a timeline that we can share publicly.

**Comment by ajays-msft** [comment]
We track Outlook add-in feature requests on our[Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
