### ISSUE TITLE
[Outlook] Item.body.getTypeAsync not work when edit an exist meeting on shared calendar (Mac)

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1457]
We get a problem when we try insert something to meeting body on an exist meeting in shared calendar.
Looks like when I try call 'Office.content.mailbox.item.body.getTypeAsync' will return failed.
The delegate permission role is editor.
  'Office.content.mailbox.item.body.getTypeAsync' can run normally on a new meeting or my own calendar.

## Expected Behavior
  'Office.content.mailbox.item.body.getTypeAsync' can run  on an exist meeting in shared calendar.

## Current Behavior
 When trying run run  on an exist meeting in shared calendar. 'Office.content.mailbox.item.body.getTypeAsync' return status 'failed' ,value: undefined

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.42 (20101102)
* Operating System: Mac
* Browser (if using Office on the web): ______

## Useful logs
![image](https://user-images.githubusercontent.com/15980696/96947293-5f29bf00-1515-11eb-81c0-a4ea03014b00.png)

**Comment by exextoc** [comment]
@SWei1234
Could you please share the repro steps? We would like to understand if any APIs are called prior to the Office.content.mailbox.item.body.getTypeAsync call to update the body.
Also, Please share the error response that is being returned.
