### ISSUE TITLE
Not able to insert document variables using word.Word.Body.insertOoxml

### ISSUE THREAD

**Issue by arshadshibli** [OfficeDev/office-js#1458]
I am trying to insert document variables to a word document by editing the office open xml. But could not find the <w:docVars> element after inserting the corresponding OOXML using  word.Word.Body.insertOoxml function

## Expected Behavior
xml element <w:docVars> should be there as a child node to <w:settings> element

## Current Behavior
No <w:docVars> element present as a child to <w:settings> element

## Steps to Reproduce, or Live Example
https://gist.github.com/arshadshibli/f8bb2ea2badc80914c2c536b1eff8115

## Context
The steps followed in the attched script lab code 

1. Retrieving the OOXML of the word document using word.Word.Body.getOoxml function
2. Editing the retrieved OOXML to include the following xml element as a child node to <w:settings>
` <w:docVars>
                    <w:docVar w:name="SV_COMMENTS_LIST_A3F0ABAB-D387-4CB1-A59F-9459101C3EB1" w:val="&amp;lt;compressed size=&amp;quot;102&amp;quot;&amp;gt;eJwdiksKgDAQxXIlbf10WaziRgVb3Hr/WxhkmCEv8yoPLwsXh7Ny0qiaxs5tzpT/XxiIpiDN+kDyRm1mkwujreAmbacP9DYnuecD5lYNIQ==&amp;lt;/compressed&amp;gt;_x000d__x000a_" />
                    <w:docVar w:name="SV_COMMENTS_THREAD_621501438D4D42FAAF3A9308AE37388D" w:val="&amp;lt;compressed size=&amp;quot;1620&amp;quot;&amp;gt;eJytVV1vElEQPc8m/ocNz1Z3t7RQRBJsIfGhaqz6tAmh+wFEYJFdYhPa/+6Zs5cFrEaj5mbvnTufZ+bOQBclplgjxRgJPMy4v0ID5wgR4Aw+9yZO0cYVT/tCDNHnGpLbxwV3n9I+BqRa0jTdBn2luKP3Ue3zHeOMEWNOyXPcYMHbmhqfqZHiG3kDvMcHXFI2kG2KJQpKc54N9NCldU67hSTlAd4tkQyJ+lwIm1wnRG5IQ1JN8gPxLki9Jv+EKH3erqhxSR3LqM18W3gQ9jE2qkxOhOb/R97oUXYpVsQ14i1FJt255JZvzltC2mq8oMVS/kpSlklBakxqJT8Bcb0golC7r88jto6y6IjjEe21fMxpWSjOglESesxUzeSvfOVE+6W29h9xR7/BHBzFCRkhYI076iCPb3t90BeHb2tVG8vj/+i9e3LvuQJFi113ly4DQ752/RirhyzaM5075C0hryoU/FG1/9Xvz2p86LPq/tLVrsd+jzQ7Gf1ERFXVck/FfJkJZSHrGJK/Icc0p7RZuE4uqBO5fs2oZT4zvUfJdUtUFcfXHtPW5rWgfqlsPta94OGtJtjj9Obyv8RLTlJlH/7C/obUhPop6U94I4vKxqZ8rjmrcER6w0RIJqKte+xm0g1vPq13Wpbz2ZHmjrPTru4WL3K1n6o2M0cl1KyolTAnouz1bXYjTfbaySLyrHNXxLCVzLKfaCZOuSz3grd2XYtYNfVqKsLXutY2j9s6gmHw6DklnakeVW1jcirsM9mv3VlQWp237tVmtf9dLg94iif13uXE7ruqS8uNcj/8lS2o05PmMb/nrPf/Hz15/Q5O7AR+&amp;lt;/compressed&amp;gt;_x000d__x000a_" />
                    <w:docVar w:name="SV_HIDDEN_GRID_QUERY_LIST_4F35BF76-6C0D-4D9B-82B2-816C12CF3733" w:val="&amp;lt;compressed size=&amp;quot;84&amp;quot;&amp;gt;eJwdijEKgDAQBOdDgSiSw/I0vsMqpWBh4+8dZIubud3Bxc3Dy8lCmM5EpZEUdqnLxa7JISUHm9/inV2s/6JqqYf+Ae3nCpA=&amp;lt;/compressed&amp;gt;_x000d__x000a_" />
                    <w:docVar w:name="SV_QUERY_LIST_4F35BF76-6C0D-4D9B-82B2-816C12CF3733" w:val="&amp;lt;compressed size=&amp;quot;84&amp;quot;&amp;gt;eJwdijEKgDAQBOdDgSiSw/I0vsMqpWBh4+8dZIubud3Bxc3Dy8lCmM5EpZEUdqnLxa7JISUHm9/inV2s/6JqqYf+Ae3nCpA=&amp;lt;/compressed&amp;gt;_x000d__x000a_" />
                </w:docVars>`
3. Inserting edited OOXML to the word document using word.Word.Body.insertOoxml function
4. On retrieving the OOXML again could not find <w:docVars> element as a child to <w:settings>

##  Environment
* Platform - Office on the web
* Host - Word_
* Office version number:
* Operating System: Windows
* Browser (if using Office on the web): Chrome

**Comment by MandytMSFT** [comment]
@arshadshibli currently <w:docVars> is not supported by insertOOXml. If you want to store these data, you can try custom XML APIs, here is the related doc: https://docs.microsoft.com/en-us/javascript/api/word/word.customxmlpart?view=word-js-preview
