### ISSUE TITLE
Reading content controls fails on Office Online when header has more then one content control

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#146]
## Expected Behavior
I want to list all the content controls in the document.

## Current Behavior
I get a "**GeneralException: Cannot read property 'z9' of null**" exception when I try to list all content controls in the document.

## Steps to Reproduce, or Live Example
1. Create two rich content controls in the header of an empty document
2. Open the document on Office Online
3. Try to list all content controls with the following code (You can paste the code into the run function in Script Lab)
4. Observe the error
```
await Word.run(async (ctx) => {
  const contentControls = ctx.document.contentControls;
  ctx.load(contentControls);
  await ctx.sync();
});
```

## Context
I want to list all content controls in the document.

## Your Environment
* Platform: Office Online
* Host: Word
* Operating System: Win 10 64 Bit
* Browser: Chrome

**Comment by XiangGaoMSFT** [comment]
Hi Baris, I can't repro it. Could you provide a sample doc?

**Comment by JuaneloJuanelo** [comment]
@xianggaomsft  please try it in CHROME, it repros there. we are tracking with bug 2353331

**Comment by barisbikmaz** [comment]
Does not happend anymore. Closing.
