### ISSUE TITLE
[Outlook] loadCustomPropertiesAsync can't access custom property on Mac outlook application(error code:9020)

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1460]
When we open outlook application on Mac . The first 10 ~ 20 minutes we can't access to custom property. 
report error code 9020 .
But after this, we can access custom property normally.
Is this an known issue? Any idea?

## Expected Behavior
User can access to custom property soon after open outlook application on Mac.

## Current Behavior
When we open outlook application on Mac . The first 10 ~ 20 minutes we can't access to custom property. 
report error code 9020 .

* Additional details:
  1. NA

## Context
We can't schedule meeting with add-in because can't save or read data on custom property.
This bug might effect 10K+ users...

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number:  16.41 
* Operating System:  Catalina 10.15.7
* Browser (if using Office on the web): ______
By the way we are using on prem environment with outlook 2016+.

Looks similar with https://github.com/OfficeDev/office-js/issues/1129

**Comment by exextoc** [comment]
@SWei1234 Could you please provide following information?

1. Are you facing this issue in Classic Mac Outlook or New Mac Outlook UI?
2. Does the issue occur consistently?
3. Please share the steps to repro the issue.

**Comment by SWei1234** [comment]
Hi @exextoc 

1. Are you facing this issue in Classic Mac Outlook or New Mac Outlook UI?
In classic Mac Outlook.
2. Does the issue occur consistently?
Yes, I tried clean cache and checked the delegate permission , but this issue occur consistently.
3. Please share the steps to repro the issue.
Pre condition: Quit Outlook Application, then reopen it.  
1) open a new meeting on a shared calendar. (in delegate permission, only set current user as an editor , set default as reader)
2) open add-in, schedule a meeting and write somge thing to custom property. 
3) open dev-tool , try use 'Office.context.mailbox.item.loadCustomPropertiesAsync' to read property
Result: You will encounter this problem within 10-20 minutes after opening. After a while, you can access it normally.
Thanks

**Comment by exextoc** [comment]
@SWei1234 Can you confirm if this is occurring on updating an existing meeting or in a new meeting window. Is it possible for you check if the custom property being set in Mac can be read from other Platforms like Windows or OWA?

**Comment by SWei1234** [comment]
Hi @exextoc 
Sorry for reply late. Please reopen this issue.
We are confirming this with customer now. Will response soon.
According to can access custom property after 20 minutes believe the custom properties write is succeed.
Thanks

**Comment by SWei1234** [comment]
Hi @exextoc 
Please help reopen this issue.

**Comment by exextoc** [comment]
Per new response by OP, reactivated github and Bug 1749805<https://o365exchange.visualstudio.com/DefaultCollection/O365%20Core/_workitems/edit/1749805>: New GitHub Issue [OfficeDev/office-js]: [Outlook] loadCustomPropertiesAsync can't access custom property on Mac outlook application(9020)

[MS Logo]       Philip Chan
pchan@microsoft.com
________________________________

**Comment by exextoc** [comment]
@SWei1234 Please confirm with customer whether customProperty write is successful.
Meanwhile, we will investigate why first few minutes after Outlook boot, behaves differently.

**Comment by SWei1234** [comment]
Hi @exextoc 
Sure, I 'm waiting customer's response.
But I think writing should be successful. Because even if you need to wait for some time, you can still read the custom properties successfully in the end.

**Comment by exextoc** [comment]
@SWei1234 So far we don't have a repro with the steps mentioned. Could you please provide more clarity with the steps?
1 -> Is the Custom Property being read immediately after the setCustomProperty in a new meeting or is the meeting invite being sent and then Custom Property is being read after a while or an Outlook restart.
2 -> In step 3 mentioned, is loadCustomProperty being done by the delegate in the shared calendar or is the call being made in delegator Account?

**Comment by SWei1234** [comment]
Hi @exextoc 
1 -> Is the Custom Property being read immediately after the setCustomProperty in a new meeting or is the meeting invite being sent and then Custom Property is being read after a while or an Outlook restart.
A: The Custom Property can be read after an Outlook restart serval minutes. Looks like only related with Outlook restart...

2 -> In step 3 mentioned, is loadCustomProperty being done by the delegate in the shared calendar or is the call being made in delegator Account?
A: on a shared calendar
Thanks

**Comment by exextoc** [comment]
Hey @SWei1234 ,

We are investigating this issue and would really appreciate your patience. We will keep you posted.

**Comment by exextoc** [comment]
Hi @SWei1234 you have mentioned your environment as on-prem. Add-ins for shared folders / calendars aren't available yet for on-prem accounts, on Outlook Mac. We are in the middle of an ongoing investigation about whether we can add shared folder support for them. Unfortunately, we don't have timelines to share at this point.

You should not be seeing add-ins on shared calendars at all, for on-prem accounts. We have tested on Outlook 16.41 (as mentioned in your post) and we don't see add-ins on the shared calendar. This is expected at this point.

Is it possible for you to share a test account which we can use to reproduce the problem? You can email its details to admin@a830edad9050849405E20081103.onmicrosoft.com.
