### ISSUE TITLE
CustomXmlNode.setTextAsync() fails on node with no text set, error 6100

### ISSUE THREAD

**Issue by ralphtheninja** [OfficeDev/office-js#1461]
## Expected Behavior

Setting the text on an empty node should work.

## Current Behavior

If a node has no text set, it errors with 6100.

However, if the node already has a value set (if you do this manually by editing the custom property under `Info` in office desktop) then `node.setTextAsync()` works as expected.

Another observation I made was that if the property has a value set already and if you try to set it to empty string, then office shows the property as invalid on the Info page when inspecting the property.

## Steps to Reproduce, or Live Example

Just try to set a text on a custom property that has an empty value.

```js
node.setTextAsync('foo', (result) => {
  // result.error always returns error 6100 if the text node is empty
})
```

## Context

I'm trying to set custom xml properties, e.g. "Document Information" etc before saving the document to SharePoint so it can index the document on that particular property (content types and fields in SharePoint).

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.13231.20250
* Operating System: Windows 10
* Browser (if using Office on the web):

**Comment by hjkim-MSFT** [comment]
We tried to repro this issue but we couldn't.

Here is what we did:
Create a custom XML part as  `<A xmlns="http://ab.org"><B/></A> (or as <A xmlns="http://ab.org"><B></B></A>)`. Note that "B" has no text.
In VBA, add this new Custom XML part: activedocument.CustomXMLParts.Add("the xml here") It is the fourth part in the document.
In VBA, get this new part's ID:  ?activedocument.CustomXMLParts(4).Id (I got C39D655B-8EAC-4A1F-8F37-F9FBE30E75D6}).
In Script Lab, HTML is:
```
<div>
 <button id="set" class="ms-Button">
        <span class="ms-Button-label">Set node text</span>
    </button>
</div>
```
In Script Lab, javascript is:

```
$("#set").click(() => tryCatch(setXmlNodeText));

function setXmlNodeText() {
  Office.context.document.customXmlParts.getByIdAsync("{C39D655B-8EAC-4A1F-8F37-F9FBE30E75D6}", function(result) {
    var xmlPart = result.value;
    xmlPart.getNodesAsync("*/*", function(nodeResults) {
      for (var i = 0; i < nodeResults.value.length; i++) {
        var node = nodeResults.value[i];
        node.setTextAsync("Hello");
      }
    });
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    OfficeHelpers.UI.notify(error);
    OfficeHelpers.Utilities.log(error);
  }
}

```
And the issue does not repro. By running the javascript above, we can set node B's text successfully to:
```
<A xmlns="http://ab.org">
    <B>Hello</B>
</A>
```

**Comment by ralphtheninja** [comment]
The empty xml nodes that I'm trying to set look like `<B xmlns="757d984d-6dab-4bc2-83cc-8319df82947b" xsi:nil="true"/>`. I'm not sure if it's the `xsi:nil="true"` part that cause the problem. I got around this issue by setting the complete xml instead of manipulating single nodes at a time.
