### ISSUE TITLE
Custom functions doesn't recalculate on Formulas -> Calculate Now

### ISSUE THREAD

**Issue by AlexPhilippov** [OfficeDev/office-js#1462]
Executing Formulas -> Calculate Now (F9) doesn't recalculate custom functions.

## Expected Behavior
Formulas -> Calculate Now (F9) triggers the recalculation of both built-in and custom functions.

## Current Behavior
Custom functions get recalculated on cell editing, removing cells from the sheet, but not on Calculate Now.
Meanwhile, build-in functions like RAND() get recalculated on each Calculate Now.

## Steps to Reproduce, or Live Example
Custom functions repo based on general custom functions example: https://github.com/AlexPhilippov/Excel-Custom-Functions.
The one difference from general repository - function currentTime marked with @customfunction to change results on each recalculation.
0. Build repo, run custom functions on Excel Online/Destktop
1. Add formulas to two sheet cells:
=RAND()
=CONTOSO.CURRENTTIME()
2. Execute Formulas -> Calculate Now (F9)
RAND result is changed, CURRENTTIME returns the same time.

## Context
In the real world add-in, we have a custom function that requests data via API and that data can change over time. Sheet can contain multiple formulas using that custom function.
We need to have a way to get the latest data for all custom functions.
Deleting cells on the sheet causes all formulas to recalculate. It's not clear why the request for recalculation doesn't.

## Your Environment
* Platform: PC desktop/Office on the web
* Host: Excel
* Office version number: Version 2009 (Build 13231.20390 Click-to-run)/latst available for Excel Online
* Operating System: Windows 10 Pro
* Browser (if using Office on the web): Google Chrome 86.0.4240.111

**Comment by xiaochunms** [comment]
In Custom Functions case, instead to use Calculate Now (F9), ctrl-alt-shift-F9 or ctrl-alt-F9 is recommended for recalc.

**Comment by keyur32** [comment]
Hi, it appears you're missing the "@volatile" tag on your functions. This will allow your functions to be treated like volatile files like Rand() in Excel.

https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-volatile\

thanks

**Comment by jordandev** [comment]
Why can't a @stream function also be @volatile? Otherwise @stream functions do not recalculate on 'Calculate Now'

**Comment by ramon-villain** [comment]
@keyur32 we are facing the same issue as @jordandev when we try to use `@volatile` with `StreamingInvocation`, do you have any suggestions?

cc: @lindalu-MSFT @ElizabethSamuel-MSFT
