### ISSUE TITLE
[Excel] unfreeze() throws an exception when trying to unfreeze panes on hidden sheets

### ISSUE THREAD

**Issue by leticiabecker** [OfficeDev/office-js#1463]
`sheet.freezePanes.unfreeze()` throws an exception when trying to unfreeze panes on a hidden sheet from the Excel add-in

## Expected Behavior
`unfreeze()` should be able to unfreeze all sheets, including the hidden ones.
https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheetfreezepanes?view=excel-js-preview#unfreeze--

## Current Behavior
If a workbook has a visible sheet with a frozen pane, calling `unfreeze()` will successfully unfreeze the pane for that sheet. 
However, if there is a hidden sheet with a frozen pane, calling `unfreeze()` on that sheet will not unfreeze the pane, but return an exception.

## Steps to Reproduce, or Live Example
* Link to Script Lab Gist: https://gist.github.com/leticiabecker/8305e861485d5a9d20d22a936e0af612

Additional details for the Script Lab Gist:

**1. Setup button:**
- Create "Sample" sheet
- Freeze "Sample" sheet panes
- Hide "Sample" sheet

**2. Test button**
- Try to unfreeze panes from the hidden "Sample" sheet

## Context
Our add-in has a button that allows our users to hide/unhide columns and rows from all the sheets on a workbook, unfreezing/freezing any columns/rows during this process. They should be able to apply all these changes (hiding, unhiding, freezing, unfreezing) to all the workbook sheets (including the hidden ones) at once with one single click.

## Your Environment
* Platform: PC desktop, Mac desktop, Office on the web
* Host: Excel
* Office version number: 16.42
* Operating System: Windows / Mac
* Browser (if using Office on the web): Google Chrome

## Useful logs
![image](https://user-images.githubusercontent.com/23156388/97227120-69fd8180-17ab-11eb-8121-2e0b8c354fdf.png)

**Comment by jwhite-venacorp** [comment]
I can confirm this fails on Windows with Excel version 16.0.13127.20620 (64-bit).

**Comment by MandytMSFT** [comment]
Open an internal BUG 4599725 to track

**Comment by lumine2008** [comment]
Thanks @leticiabecker  for reporting this issue, @MandytMSFT  from our team has repro this issue and bug was created to track this issue, we will keep you update once we have progress on this issue.

**Comment by lumine2008** [comment]
Hi @leticiabecker , would you please share a bit more on your scenario, we would like to learn more about the reason that need to freeze/unfreeze the hidden worksheets.

**Comment by leticiabecker** [comment]
Hi @lumine2008, thanks for replying. 

Most of our users' templates have worksheets with frozen rows and columns, but some of those worksheets might be hidden at times. 
Our Excel Add-in has 2 buttons: `Deactivate Flags`* and `Activate Flags`*.

- `Deactivate Flags` basically allows users to change all their template worksheets to a "raw" state, unfreezing panes, showing hidden columns and rows, among other actions, which make it easier for them to customize the template.
- `Activate Flags`, on the other hand, will freeze panes and hide columns and rows back again.

At the moment, as a workaround, we are wrapping the freeze/unfreeze calls in a `try/catch` so even if they fail, the rest of the code still runs. 
However, the problem is that our users would have to perform extra work, manually freezing/unfreezing those sheets’ panes in these cases, which they would expect to be handled by the `Deactivate Flags` button click.

_\* "Flags" are tags (such as #freezerow, #freezecolumn, #unfreezerow, #unfreezecolumn, etc.) which users can add directly to cells, setting the coordinates of columns/rows to be frozen/unfrozen._ 

I hope it helps you understand the context a bit better. Please let me know if anything is not clear or you have any more questions.

**Comment by lumine2008** [comment]
Thanks, @leticiabecker for your reply, we are still having an internal discussion about whether we should support freeze and unfreeze when the worksheet is invisible. as there will be potential bugs and issues if we support, therefore we have a workaround solution for your scenario, you could register the freeze/unfreeze operation to onActivated event, and implement freeze/unfreeze when the target sheet is activated.

**Comment by lumine2008** [comment]
This bug 4599725 was fixed, please verify
