### ISSUE TITLE
Custom function works well in Online excel and doesn't work in Desktop Excel

### ISSUE THREAD

**Issue by ivanosipov95** [OfficeDev/office-js#1464]
Add-in works well in Excel Online. On the desktop version, I always get #N/A error. I use shared environment

## Expected Behavior

If the custom function works correctly in Online Excel it should work well in Desktop Excel. Or I missed some differences in configuration?

## Current Behavior

The custom function doesn't work in Desktop but works in Online Excel

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

Our add-in is an Enterprise solution. We would like to run it on Desktop and Online as well

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft 365 MSO (16.0.13127.20620) 64-bit
* Operating System: Windows 10 Pro 10.0.19041 Build 19041
* Browser (if using Office on the web): Chrome

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by ivanosipov95** [comment]
@keyur32 Hi, any ideas?

**Comment by keyur32** [comment]
Hey, can you provide more information please.
a) are you using the shared runtime for your custom function?
b) can you verify the associate command is set to register your metadata?
c) Can you enable runtime logging on windows desktop?
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-troubleshooting#enable-runtime-logging
d) Are you able to call your function successfully, if possible via scriptlab?

thanks and assigning to @grangeryy as our custom functions expert :)

**Comment by grangeryy** [comment]
@ivanosipov95 does this issue still repro for you?

**Comment by grangeryy** [comment]
Close this without repro. Please feel free to reopen it once the issue shows up again. Thx!
