### ISSUE TITLE
Addin disappeared. Get addins redirects to web 

### ISSUE THREAD

**Issue by GMolini** [OfficeDev/office-js#1465]
I have this issue: https://github.com/OfficeDev/outlook-dev-docs/issues/514 but cant comment since it has been closed. I had sideloaded my addin correctly and was trying some things when I accidentally closed outlook. Now, after opening again, the addin is not loaded and whenever i click on the get addins button it opens a tab in the browser and redirects me to: https://appsource.microsoft.com/en-us/marketplace/apps?product=office%3boutlook&page=1&src=office
instead of opening the dialog inside outlook.

Curiously, if i go to file -> Info -> Manage addins, it opens https://outlook.office365.com/mail/inbox and there I can see my addin under the "My addins" tab. 

Whats going on? Why has it stopped showing my addin? Ive tried rebooting and it still doesnt work.

**Comment by exextoc** [comment]
What client are you using (win32, mac, OWA) and what is the build of Outlook? What OS and version number are you using?

**Comment by GMolini** [comment]
Os: Windows 10 Education
Version: 1909 OS Build 18363.1139
Outlook: Version2009 (Build 13231.20390 Click-to_run)

It has actually started working again, without me doing anything. But it would be great to know what causes the problem in case it happens again, and what could be the solution.

**Comment by GMolini** [comment]
And it has happened again.

**Comment by GMolini** [comment]
Some more info. As I said, addin comes and goes. But at some point when I clicked to in the addin button, the following message appeared:

![image](https://user-images.githubusercontent.com/1327783/97739112-990e3e80-1a9c-11eb-85ed-e15d8e9d89d4.png)

Which is weird, because its been working fine, its a self signed certificate that i did following the tutorial. After that message appears, if I close Outlook and open it again, the addin has disappeared and get addins redirects to the web.

**Comment by exextoc** [comment]
Do you have [Fiddler ](https://www.telerik.com/fiddler)(or any other network tracing tool) open when you are using your sideloaded add-in? Something that might help debug this intermittent issues is to have Fiddler open when Outlook is booted. This will help see if any calls are failing that might prevent add-ins from showing. Do you see any calls to Exchange that fail in Fiddler once Outlook is booted?

When you notice your sideloaded add-in is missing, are all add-ins missing or only your add-in is missing?

**Comment by ArjunSureshKumar92** [comment]
Facing similar issue where the addin randomly is missing after a restart. No way of getting it back, and after a few days randomly is there again.

**Comment by exextoc** [comment]
@ArjunSureshKumar92 - As the original issue has been closed, may we recommend to please open a separate issue with what you're trying to achieve/issues you are facing. This way we can have an active involvement on the new post and make sure that appropriate help is provided. It may also help others who are facing a similar issue.
