### ISSUE TITLE
[invalid] Office.context.mailbox.item.getAttachmentsAsync only works in Compose mode

### ISSUE THREAD

**Issue by ig-jb** [OfficeDev/office-js#1466]
The documentation at https://docs.microsoft.com/en-us/javascript/api/outlook/office.attachmentcontent?view=outlook-js-preview indicates that Office.context.mailbox.item.getAttachmentsAsync should work in either Compose or Read mode. However, it only works in Compose mode

## Expected Behavior
Office.context.mailbox.item.getAttachmentsAsync and result.asyncContext.currentItem.getAttachmentContentAsync work in Read and Compose mode

## Current Behavior
Office.context.mailbox.item.getAttachmentsAsync and result.asyncContext.currentItem.getAttachmentContentAsync only work in Compose mode

## Steps to Reproduce, or Live Example
ScriptLab - Standard "Get attachment content" sample
  1. View an email which has an attachment. Run the script lab sample
  2. Compose an email and add an attachment. Run the script lab sample

The feature will only work when composing

## Context
We would like to provide users the ability to upload attachments to our web application. This feature only being available in compose mode limits this significantly. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Web - latest
* Operating System: Windows
* Browser (if using Office on the web): Chrome, edgev2

## Useful logs
0: "Uncaught TypeError: item.getAttachmentsAsync is not a function"
1: "https://script-lab-runner.azureedge.net/"
2: 6
3: 10
4: TypeError

**Comment by exextoc** [comment]
Office.context.mailbox.item.getAttachmentsAsync is a Compose mode API.
For Read mode, we have Office.context.mailbox.item.attachments API.  You can find the details here https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-preview&preserve-view=true#property-details
The result of this API can be used by  Office.context.mailbox.item.getAttachmentContentAsync  to retrieve the content in Message Read and Appointment Attendee modes.

**Comment by ig-jb** [comment]
@exextoc Unless I'm missing something Office.context.mailbox.item.attachments doesn't provide access to the attachment content (method getAttachmentContentAsync doesn't exist on the object), while Office.AttachmentContent is described in the documentation as being for either Compose or Read? 

Do you perhaps have a working example of this for an item in read mode?

**Comment by ig-jb** [comment]
Got it -- I had missed something. Thanks @exextoc 

Example based on the script lab compose example for anyone else who comes across this later:
```
$("#run").click(run);

function run() {
  var item = Office.context.mailbox.item;
  var options = { asyncContext: { currentItem: item } };

  Office.context.mailbox.item.attachments.forEach(callback);
  function callback(result) {
    console.log(result);
    Office.context.mailbox.item.getAttachmentContentAsync(result.id, {} , handleAttachmentsCallback);
  }

  function handleAttachmentsCallback(result) {
    // Parse string to be a url, an .eml file, a base64-encoded string, or an .icalendar file.
    switch (result.value.format) {
      case Office.MailboxEnums.AttachmentContentFormat.Base64:
        // Handle file attachment.
        console.log(result.value.content);
        break;
      case Office.MailboxEnums.AttachmentContentFormat.Eml:
        // Handle email item attachment.
        console.log("Attachment is a message.");
        break;
      case Office.MailboxEnums.AttachmentContentFormat.ICalendar:
        // Handle .icalender attachment.
        console.log("Attachment is a calendar item.");
        break;
      case Office.MailboxEnums.AttachmentContentFormat.Url:
        console.log(result.value);
        // Handle cloud attachment.
        console.log("Attachment is a cloud attachment.");
        break;
      default:
      // Handle attachment formats that are not supported.
    }
  }
}
```
