### ISSUE TITLE
ContentControl.insertFileFromBase64 resets content control properties

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#1467]
When I create a content control with some properties and upload this document to Word Online and then change the properties there and insert a document with insertFileFromBase64 then the content control properties are resetted.

## Expected Behavior
The method insertFileFromBase64 should not reset content control properties.

## Current Behavior
The method insertFileFromBase64 resets content control properties like title and tag.

## Steps to Reproduce, or Live Example
[Gist Example](https://gist.github.com/barisbikmaz/45e129180a57aaa035eb577893745c45)
1. Create a blank document in Word on Windows
2. Insert a richtext content control  into the blank document
3. Add a content control title and tag 
4. Upload document to OneDrive
5. Open document in Word Online
6. Run the gist sample in Script Lab
7. Click "Print the Content Control Properties" and see current title and tag on console
8. Click "Update" to update the content control title and tag
9. Click "Print the Content Control Properties" and see new title and tag on console
10. Click "Insert" to insert a docx into the Content Control
11. Click "Print the Content Control Properties" and observe that the properties are resetted.

## Context
We have an addin which reads configurations from the content control tag.
When we insert some content into the content control by using insertFileFromBase64 the tag information is lost.

## Your Environment
* Platform: Office on the web
* Host: Word
* Office version number: Version 2010 (Build 13328.20292)
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome

**Comment by MandytMSFT** [comment]
I can repro this issue,  BUG 4603048 is opened for internal track

**Comment by jipyua** [comment]
After validation on latest word online build 16.0.17619.41005, this issue doesn't repro anymore and should have been fixed. Close this issue as fixed and please feel free to try the latest behavior.
