### ISSUE TITLE
Problem with rendering page when using window.open in Outlook for Windows

### ISSUE THREAD

**Issue by modestfake** [OfficeDev/office-js#1468]
Let me know if this is the wrong place to raise such issues.

We render sidebar and inside a sidebar we do this
```javascript
window.open('/example', 'width=500,height=900,...')
```

If the server returns 409 HTTP status code for `/example`, Outlook shows this error, even if the response is a valid HTML.
![image](https://user-images.githubusercontent.com/16977959/97632252-efe32c00-1a3a-11eb-97da-18b86d986198.png)

It actually works in OWA and Outlook for Mac, it renders HTML if the status code of the response is 409. The same thing for the sidebar itself. The sidebar is not rendered if the status code is 4xx.

## Expected Behavior
Render HTML in the sidebar or in a new window, even if the HTTP status code is 409.

## Current Behavior
Outlook renders the following error when the server responds 409, even with valid HTML:
```
ADD-IN ERROR
A problem occurred while trying to reach this add-in.
```

## Steps to Reproduce, or Live Example
1. Add taskpane to manifest file, for example with URL `/sidebar`.
2. Set up the server to respond with valid HTML but set status code to 409.
3. Try to open the sidebar. It will show the error instead of rendering the HTML.

## Context
We show the OAuth dialog for our users and sometimes the server responds with 409 and valid HTML. Instead of showing the error page from the OAuth provider, it shows that it can't reach the add-in. The user thinks that it's our add-in is broken.

## Your Environment
I can only reproduce this on
* Platform: PC
* Host: Outlook
* Office version number: 13426.20004 (Beta channel, but our customers on a stable build and see the same issue)
* Operating System: Windows

**Comment by exextoc** [comment]
The behavior you are seeing is by-design in Outlook win-32 when using Edge Webview as the underlying browser. 4xx responses are handled by the Webview, and this error is displayed.

The new Edge WebView2 will popup a browser and display whatever error/content the browser shows. There are instructions to begin testing with Webview 2 [here](https://developer.microsoft.com/en-us/office/blogs/announcing-webview2-for-office-add-ins-platform/).

**Comment by modestfake** [comment]
So, it's not a bug but it will work as we expect soon. Is there any ETA when this will be GA (not on the Insider program but for all customers)?
And also, this issue can be closed. Thank you!

**Comment by exextoc** [comment]
We unfortunately don't have an ETA yet we can commit to but are trying hard to get this out.
