### ISSUE TITLE
OfficeJS add-ins are flickered after updating content-control bound to a repeating table

### ISSUE THREAD

**Issue by namnn96** [OfficeDev/office-js#1469]
If the document opened in Word contains a content-control bound to a repeating table, after updating that content-control's value, all OfficeJS add-ins are flickered.

## Expected Behavior

Regardless of whether a content-control is bound to singular value or repeating table, updating fields in Word document should not flicker OfficeJS add-ins.

## Current Behavior

All OfficeJS add-ins are flickered after Word updates a repeating table content-control.

The flickering does not happen if content-control is bound to a singular value, and occurs on add/update/delete row in a repeating table. The more items the table holds, the worse flickering issue becomes.

Not only is dev (and/or deployed) add-in flickered, live third-party add-in is also flickered.

The flickering issue also happens when toggling Design Mode under Developer tab.

### Scenario 1: Toggle Design Mode under Developer tab
* Open a document with repeating table content-control (by default table should contain some rows)
* Open and Run a pre-defined Script Lab add-in
* Toggle Design Mode under Developer tab
* Notice the flickering on Script Lab add-in
### Scenario 2: Update content-controls' data
* Open a new Word document, insert a content-control as repeating table (data bound to CustomXmlParts)
* Insert some other singular content-controls
* Launch an OfficeJS add-in, which contains a list and some form inputs. On update, write to CustomXmlParts and trigger document fields update
* Also launch a third-party OfficeJS add-in from store
* Add/edit/remove items to/from the list, notice the flickering on all OfficeJS add-ins
* Update a singular input, notice there is no flickering

## Context

We have quite a large number of documents using repeating tables and OfficeJS add-ins that contain mutating lists of items. The flickering affects the user experience significantly.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
### Test 1
* Office version number: Word 2010 (Build 13328.20292 Click-to-Run)
* Operating System: Windows 10 Version 1809 (build 17763.737)
* Office Add-in Browser: IE11
### Test 2
* Office version number: Word 2010 (Build 13328.20292 Click-to-Run)
* Operating System: Windows 10 Version 2004 (build 19041.572)
* Office Add-in Browser: Edge with original WebView
### Test 3
* Office version number: Word 2011 (Build 13426.20004 Click-to-Run)
* Operating System: Windows 10 Version 20H2 (build 19042.610)
* Office Add-in Browser: Edge with WebView2

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [x] Test file (if only happens on a particular file)
### Scenario 1: Toggle Design Mode under Developer tab
![Mfo1uxCZ8r](https://user-images.githubusercontent.com/8945395/97824865-37a2d580-1d11-11eb-89ef-c8793bee1468.gif)
### Scenario 2: Update content-controls' data
![e033L0YvHN](https://user-images.githubusercontent.com/8945395/97819934-cf97c380-1cff-11eb-9462-dd3a57952f9e.gif)
### Document
[Issue 1469 - Test document.docx](https://github.com/OfficeDev/office-js/files/5472498/Issue.1469.-.Test.document.docx)

**Comment by namnn96** [comment]
Hi @hjkim-MSFT and @JiayuanLiMSFT,

Do you have any updates on this issue?

**Comment by zhaoliu-MSFT** [comment]
Hi @namnn96 ,

I'm trying to find out the cause of the issue. I can repro the Scenario #1, but I cannot repro the Scenario #2. What I have tried is to update the part XML with the function setXmlAsync in the interface Office.CustomXmlNode.

The steps that I have taken:
1) Open the document "Issue 1469 - Test document.docx" that is attached in the post
2) Open Script Lab and create a new project from Samples > Basic API call (TypeScript)
3) Paste the code in the attachment
4) Click run and click the button
5) Observe that the table is updated with a random number of rows, but I don't see flashes

[scriptlab setxmlasync.txt](https://github.com/OfficeDev/office-js/files/5638434/scriptlab.setxmlasync.txt)

**Comment by namnn96** [comment]
Hi @zhaoliu-MSFT,

From our end, we have a com-addin sitting behind to handle updating content-controls.

For scenario 2, there was an issue where table bindings not always updated properly, so on every call to update table content-controls, we worked around by toggling the design mode twice to make sure data is bound properly, which leads us to the same with scenario 1.

Is there a way to toggle the design mode without flashing the add-in?

**Comment by namnn96** [comment]
Hi @hjkim-MSFT,

I noticed you marked the ticket as fixed. Could you please elaborate on:
- Minimum version of Windows/Office
- What solution has been done? Is it to fix the flickering when toggle the design mode?

**Comment by zhaoliu-MSFT** [comment]
Hi @namnn96,

The fix should be available on Build 13610. It happens to be a simple fix in the code so the fix was justified quickly.

The flickering is caused by the WM_SETREDRAW message that can be seen with the Spy++ tool in one of the HWNDs. The fix will prevent the WM_SETREDRAW message if the add-in taskpanes are present, which should fix cases including the design mode and changing view mode in Word.
