### ISSUE TITLE
callback in Office.context.ui.displayDialogAsync() not excuted

### ISSUE THREAD

**Issue by whj768702** [OfficeDev/office-js#147]
## Expected Behavior

yesterday I update word to the newest version. (16.13[180513]), something goes wrong. when i open a dialog window，click close button，Office.context.ui.displayDialogAsync() do not execute callback, so no change to excute dialog.close of callback 。when i open the dialog for the second time, it does not appear。the code of asyncResult is 12007。
forgive my poor English。

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac 10.13.4 
* Host [Excel, Word, PowerPoint, etc.]: Word 16.13[180513]
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by LanceEa** [comment]
I'm seeing the same error where the first time I load the add-in it works fine. I close the dialog box either via the "X" or via the messageParent/dialog.close() pattern and try to re-open dialog box and it fails.

There is a discussion in Stackoverflow on this same issue that only talks about word but it seems to be just the Mac versions of Office that are causing this issue.
https://stackoverflow.com/questions/50485448/office-js-dialog-api-16-13-word-doesnt-open-dialog-next-time

> Note - I'm on insider release channel and this only started happening about 1-2 weeks ago. I have tried switching from beta/production CDN for Office-js as well but that doesn't seem to help.

Results from testing in different Excel Versions:
- Excel on Windows (16.0.9020.2003) 32bit => Works correctly
- Excel Online (16.0.9423.5058) => Works correctly
- Excel for Mac (16.14 - 180520) => does NOT work.


```typescript
 Office.context.ui.displayDialogAsync(url, options, (displayDialogResult: Office.AsyncResult) => {
        console.log(displayDialogResult);
        this._dialog = displayDialogResult.value;
        this._dialog.addEventHandler(Office.EventType.DialogMessageReceived, result => {
          const message = JSON.parse(result.message);
          switch (message.messageType) {
            case 'dialogClosed':
              console.log('received dialogClosed command!');
              this._dialog.close();
              this._dialog = null;
              console.log(this._dialog);
              return;
            case 'dispatch':
              this.store.dispatch(message.action);
              return this.selectQuery(message.queryHeader);
          }
        });

        this._dialog.addEventHandler(Office.EventType.DialogEventReceived, test => console.log(test));
```

 Here is a console output snippet of what happens:

<img width="996" alt="screen shot 2018-05-24 at 8 21 22 pm" src="https://user-images.githubusercontent.com/8103374/40521459-65261548-5f91-11e8-9dbd-2caac0aab5ba.png">

I tried explicitly setting my reference to dialog to null/undefined but that doesn't seem to release it. I have also tried adding the `DialogEventReceived` but it doesn't seem to be getting fired which might be the issue.

@Zlatkovsky @sumurthy @mlafleur  - is this a known issue? Let me know if you need me to provide more information.

**Comment by whj768702** [comment]
@LanceEa the lateset version has fixed this bug.  >16.14

**Comment by LanceEa** [comment]
@whj768702 - Thanks, yes I updated to the last build earlier this week and it seems to be working correctly now.
