### ISSUE TITLE
Memory leak issue in Outlook Add-ins when app is pinned and opened in multiple new windows

### ISSUE THREAD

**Issue by swasti1994** [OfficeDev/office-js#1471]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

##  Expected Behavior
The add-in should not cause an abrupt increase in memory utilization and should not cause Outlook to crash.

## Current Behavior
On following the steps below, the add-in becomes unresponsive and eventually crashes Outlook. 
**Please note that this issue is reproducible even after the recent [August 2020 IE Patch](https://support.microsoft.com/en-us/help/4566116)**. 

## Steps to Reproduce
* Open Outlook and select any mail
* Open any add-in and pin it (reproducible with Script Labs for Outlook add-in)
* Now double click outlook mails to open them in separate windows
* Since the add-in is pinned, it tries to auto load in all of them
* Load up to 10 mails in a similar fashion in quick succession
* There should be a spike in the memory utilization
* At memory usage higher than 250MB, Outlook starts to slow down, the add-ins stop responding and eventually causes Outlook to crash. We have observed a memory utilization of ~600MB at the time of crash

## Context
* This issue has affected multiple customers. The fact that this makes Outlook unstable is discouraging the use of our add-in. 

## Your Environment
* Platform: PC Desktop
* Host: MS Outlook
* Office version number: Outlook 16.0.13127.20408, Outlook 16.0.13328.20262
* Operating System: Windows 10 (OS Build 10.0.19041.488)
* Browser: Not Applicable

## Outlook Version
![WhatsApp Image 2020-11-03 at 10 31 52](https://user-images.githubusercontent.com/40160613/97959369-3c30c200-1dd5-11eb-84ca-0a9dff44f7e9.jpeg)

## Windows Version
![WhatsApp Image 2020-11-03 at 10 33 38](https://user-images.githubusercontent.com/40160613/97959376-3f2bb280-1dd5-11eb-91ad-47c4d83ea17a.jpeg)

**Comment by JuaneloJuanelo** [comment]
This is an issue with the web view engine.

**Comment by dkuklis** [comment]
@JuaneloJuanelo Hello - Is there a target date for resolving this issue that you know of? (I believe you work for Microsoft).  I am working with a salesforce customer who is still having this issue but MS is saying it's been fixed (and it's not - at least for them).

**Comment by Byron-Mo** [comment]
Hi, we'd like to confirm if this is related to the webview memory leak issue filed here. The user is encountering excessive slowness when using an Outlook Addin on Outlook Desktop. This is their memory usage - Desktop App Web Viewer is taking up 2.4gb of memory

![renditionDownload1](https://user-images.githubusercontent.com/14811552/116845953-22154800-ab9c-11eb-8dd3-2e41ded63366.jpeg)

**Comment by ElizabethSamuel-MSFT** [comment]
@croicu Can you take a look?

Thanks.
