### ISSUE TITLE
Memory leak issue in Outlook Add-ins when app is pinned, and a user scrolls through the outlook messages

### ISSUE THREAD

**Issue by swasti1994** [OfficeDev/office-js#1472]
##  Expected Behavior
The add-in should not cause an abrupt increase in memory utilization and should not cause Outlook to crash.

## Current Behavior
On following the steps below, the add-in becomes unresponsive and eventually crashes Outlook.
**Please note that this issue is reproducible even after the recent [August 2020 IE Patch](https://support.microsoft.com/en-us/help/4566116)**. 

## Steps to Reproduce
* Open any add-in and pin it
* Use the down arrow key of your keyboard and scroll through outlook messages
* After about 5-7 mins of scrolling, Outlook stops responding
* Task manager shows multiple instances of Desktop App Web Viewer running (usually 4-8 in number)
* Memory utilization crosses **400MB** and CPU usage is also > **80%**

## Context
* This issue has affected multiple customers. The fact that this makes Outlook unstable is discouraging the use of our add-in. 

## Your Environment
* Platform: PC Desktop
* Host: MS Outlook
* Office version number: Outlook 16.0.13127.20408, Outlook 16.0.13328.20262
* Operating System: Windows 10 (OS Build 10.0.19041.488)
* Browser: Not Applicable

**Comment by JuaneloJuanelo** [comment]
@swasti1994 can you please help us describe the issue in more detail? It sounds a bit edgy that the user is continuously scrolling for 7 minutes through the email. Is that the condition you are observing? 
A video could be really helpful.

**Comment by swasti1994** [comment]
@JuaneloJuanelo We are working to get a video of the scenario to help with the investigation. We will share the same with you offline by Monday. Thanks !

**Comment by Byron-Mo** [comment]
Hi, we have a customer case that is experiencing this exact same issue. Customer's Outlook & Windows config are:

Outlook is on 13127.21064 and Windows is on 18363.1316

We are following up and asking if upgrading to use WebView2 would be a reasonable solution. In the meantime, would it be possible to reopen this ticket? Thanks

**Comment by exextoc** [comment]
@Byron-Mo We meant to close this issue as a duplicate of #1471 

Could you please add any information you have to that issue? Thanks!
