### ISSUE TITLE
Word is aborted when loading a global template (*.dotm)

### ISSUE THREAD

**Issue by friedlaenderhans** [OfficeDev/office-js#1473]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

A macro package (*.dotm) which is loaded as a global template by a Com-AddIn causes Word to crash. Yesterday (2020-11-02) the problem was restricted to Word 2016 versions, today (2020-11-03) we receive messages indicating that also Word 2019 is concerned.
## Expected Behavior
Word starts normally. When opening a document the AddIn is loaded as a Ribbon.
## Current Behavior
Word crashes directly without any error message.
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop, Windows 10 (multiple versions and builds)
* Host [Excel, Word, PowerPoint, etc.]: MS Word multiple versions and distribution channels

**Comment by friedlaenderhans** [comment]
Additional information: it seems that the problem is restricted to Click-to-run-installations. Best regards, Hans

**Comment by Kaidali** [comment]
Sorry but a question is: does all com add-in will make work crash? or a specific one? Thanks. 
Since I tried it, but seems loaded correctly.

**Comment by friedlaenderhans** [comment]
Kaidali wrote:
> Sorry but a question is: does all com add-in will make work crash? or a specific one? Thanks.
> Since I tried it, but seems loaded correctly.

No, the COM-AddIn itself is loaded correctly and works as expected. When I deactivate it and try to load the dotm-macro package manually Word crashes anyway, so the COM-AddIn is not the problem.

So far we managed to see that another dotm-macro package we develop and sell loads ad first, but causes Word to terminate when some of its functions are called. We fear that maybe one of the libraries we are using is the cause of the issues but we have not yet identified which of the following:

- Visual Basic for Applications
- Microsoft Word 16.0 Object Library
- OLE Automation
- Microsoft Office 16.0 Object Library
- Microsoft Forms 2.0 Object Library
- Microsoft Office 16.0 Access database Engine Object Library
- HHCtrl 4.0 Type Library
- Microsoft Scripting Runtime
- Microsoft Windows Common Controls 6.0 (SP6)
- Microsoft Internet Controls
- Microsoft Windows Image Acquisition Library v2.0

Best regards, Hans

**Comment by Kaidali** [comment]
Thanks for the info, Hans. 
We haven't heard a similar crash so far, and it's hard to get a clue with those info. 
Can you please provide some more details like, which of your calls actually terminate word? Or crash call stack. Thanks. 

Regards, Flora

**Comment by friedlaenderhans** [comment]
Hello,
it turned out that the "Microsoft Office 16.0 Access database Engine Object Library" which has been updated by Microsoft aorund Nov. 2 caused the error. In our dotm we used common database questions on MDB-files ("table exists" and field exists") in "for each"-loops. After changing that method into something else (sorry, our developer told me, it was something using an index, if necessary I can ask for details!) everything works smoothly.

Best regards, Hans

**Comment by Kaidali** [comment]
Not sure what version/build of Office you're working on, but probably you're still in Office2010?
if so, then we recently fixed an issue about EnumVariantInterceptor::Next, and a new deployment of the library is currently planed on Nov 17, then this issue would get a fix. Thanks. 

Regards,
Flora

**Comment by friedlaenderhans** [comment]
Flora wrote: 
> Not sure what version/build of Office you're working on, but probably you're still in Office2010?
> if so, then we recently fixed an issue about EnumVariantInterceptor::Next, and a new deployment of the library is currently planed on Nov 17, then this issue would get a fix. Thanks.

Hello,
sorry for not having answered for a couple of weeks.

We had the problem with a variety of current versions of MS Office. Our VBA/.NET-code was doing some "for each" loops on "Recordset.Fields" which produced the abortion of Word. Our developer replaced that whith "for i to Count-1", now evereything is running smooth again.

Best regards, may everybody stay well and safe!

Hans
