### ISSUE TITLE
Safari ITP and Taskpane -> Dialog LocalStorage

### ISSUE THREAD

**Issue by jak-hammond** [OfficeDev/office-js#1474]
With the latest release of Intelligent Tracking Prevention in Safari, the ability to use local storage to communicate between taskpanes and dialogs has become non-functional. 

This is tied to the hosting model of Office.js add-ins. When running in OWA, the top-level domain is https://outlook.office.com, or some variation, the add-in is then hosted on some other domain and embedded in the iFrame, this results in the local storage being sandboxed to this particular combination. When the dialog is opened, the TLD is that of the dialog, http://my.dialog.com, for instance, this results in a new sandbox for the local storage and as a result, it cannot be relied upon for communication between the taskpane and dialog.

A workaround is to disable the tracking prevention functionality inside Safari, but understandably, this will most likely come up against considerable user resistance/complaints.

## Expected Behavior
This is tricky to quantify as the current behavior is technically by design, but either the iFrame that embeds Office.js apps should support the required attribute to allow apps to request permissions, or Office.js itself should provide some mechanism through which apps can request permission.

## Current Behavior
Taskpane and dialog local storage instances are sandboxed and not accessible to one another.

## Steps to Reproduce, or Live Example
https://github.com/jak-hammond/office-js-safari-itp

Additional details:
  1. Install sample manifest
  2. Click the Run button
  3. Value in taskpane will update
  4. Dialog will be displayed with explanation of issue and empty local storage value at the bottom
  5. Inspect the taskpane and its local storage and you will see a value for 'jh-test'
  6. Inspect the dialog and its local storage and you will see the value is not present

Alternatively:
  1. Open the taskpane, click run
  2. Dismiss the dialog
  3. Send the message
  4. Second dialog will be displayed
  5. Behavior is as before, values from local storage are not persisted

## Context
Our app utilizes local storage heavily with a Vue application to persist client state between the taskpane and any dialog that we might spawn, at the moment this functionality does not work and dialogs act like a fresh instance of the app, asking the user to authenticate all over again. We also utilize this functionality when sending a message to, again, share state between the message send processing code and dialogs we display.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: macOS Catalina Version 10.15.7
* Browser (if using Office on the web): Safari 14.0.15610.1.28.1.9

## Useful logs
![image](https://user-images.githubusercontent.com/664193/98020561-13232800-1dfb-11eb-8002-b6e5fca14a4c.png)

**Comment by jak-hammond** [comment]
I also think it is quite important to call this specific behavior out here; https://docs.microsoft.com/en-us/office/dev/add-ins/develop/parent-to-dialog where you state that local storage is a method through which add-ins can communicate to their dialogs, without the user disabling the Privacy functionality in Safari, this is not possible.

**Comment by exextoc** [comment]
Thanks for reporting the issue. We are able to reproduce it. We have created a backlog item for further investigation and research on the above. We don't have any timelines as of now.

**Comment by yumao5** [comment]
is there any update about this ticket? @exextoc

**Comment by exextoc** [comment]
@yumao5  Investigation is still in our backlog. Unfortunately, we have no timelines to share at this point.

**Comment by exextoc** [comment]
Currently the feature you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
