### ISSUE TITLE
Licencing Issue with officeatwork add-ins in Office 2016

### ISSUE THREAD

**Issue by FlorinBuffet** [OfficeDev/office-js#1475]
## Expected Behavior
The expected behaviour is exactly the same as it is with Word 365. The Add-In is expected to do its job and open.

## Current Behavior
Instead we see a Licencing Issue.
![licencingissue](https://user-images.githubusercontent.com/73933252/98087548-8cb12980-1e80-11eb-8d36-e89b692f30a2.jpg)

## Steps to Reproduce, or Live Example
In our Citrix envirement it is often the case when we try to load the Add-Ins to Office 2016.
The way we can sometimes solve this is by deleting all Add-Ins, Load the officeatwork nes again and the login again inside the add-in.

## Context
We can't use the feature promised to work by officeatwork in Office 2016.

## Your Environment
Citrix Enviroment with Windows Server 2012 R2
Word 2016 64-Bit (16.0.5071.1000) MSO (16.0.5056.1000)

**Comment by MandytMSFT** [comment]
@FlorinBuffet can you reach officeatwork first to solve your problem ?

**Comment by MartinSSeifert** [comment]
@MandytMSFT we can assure you that the Add-in is published properly (via AppSource, checked by Microsoft). Other customers have no issues at all! Can you please investigate why the 'web view' is showing this MICROSOFT generated message about licensing - this is NOT an officeatwork message! So we can not solve this - only Microsoft can!

**Comment by MandytMSFT** [comment]
@MartinSSeifert Aha, Thanks for the info to help me understand your role.  

Could you pls share a high quality screenshot or share the message shown on error page ? i can't see clearly what the screenshot saying. Then I can redirect to right team for help.

**Comment by MartinSSeifert** [comment]
@FlorinBuffet can you please send Mandy a higher resolution image as she requested in her message to me - thx. cc: @MandytMSFT

**Comment by FlorinBuffet** [comment]
Hi @MandytMSFT 
Please find attached the Screenshot. Can you please reassign yourself the case?
![10-12-_2020_12-46-42](https://user-images.githubusercontent.com/73933252/101768657-26a26c80-3ae6-11eb-832f-d30252e593eb.png)

@MartinSSeifert Many thanks for your participation.

Best Regards
Florin

**Comment by MandytMSFT** [comment]
@FlorinBuffet thanks for the details. I have assigned to right people to help figure out cause.

**Comment by AbidRahman-MSFT** [comment]
Hey @FlorinBuffet - thanks for reporting this issue. We are aware of this and are currently investigating. A few clarifying questions:

1. Are you able to consistently reproduce this issue? Does the error show up every single time you install and open the officeatwork add-in? 
2. Have you seen this error happen for other add-ins as well?
3. Any other information that can help us reproduce this error would be very helpful.

Thanks,
Abid

**Comment by AbidRahman-MSFT** [comment]
This issue has been fixed! Please re-open the issue if you continue to see related problems with a similar error message. 

Thanks for the patience. :)
