### ISSUE TITLE
Outlook Online Reporting Incorrect Dialog API Support

### ISSUE THREAD

**Issue by jak-hammond** [OfficeDev/office-js#1476]
We are looking at adding support for the new messageChild() function inside the DialogAPI, but we need to ensure that we only 
use this functionality on clients where it is supported. We are using the Office.context.requirements.isSetSupported() function to figure out if the client supports the necessary 1.9 Mailbox and 1.2 DialogAPI sets but when this is run on Outlook Online, the DialogAPI check is returning false, even though, when we spawn a dialog, we can see the messageChild() function is present on the object.

This also goes against the documentation about the 1.2 set which says it has been available in Office Online since June 2020; https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/dialog-api-requirement-sets

## Expected Behavior
Outlook Online will return true if DialogAPI 1.2 is supported.

## Current Behavior
Outlook Online is returning false when asking if DialogAPI 1.2 is supported.

## Steps to Reproduce, or Live Example
* Link to live example: https://gist.github.com/jak-hammond/0e47d167fcff1376b1d2f1dd732eb9e8

* Additional details:
  1. Run the add in on Office
  2. Click the Run button
  3. Inspect the reported values for the various requirement sets support

## Context
We need to use this method to convey information from the parent app, both taskpane and on-send code, over to dialogs that we spawn, this is also the suggested workaround for another issue we have previously reported; #1399 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: N/A
* Browser (if using Office on the web): Chrome

## Useful logs
Dialog API reported from Outlook on Mac:
![DialogAPI_Mac](https://user-images.githubusercontent.com/664193/98104745-c9841d00-1e8e-11eb-9658-221ebba0a230.png)

Dialog API reported from Outlook on Windows:
![DialogAPI_Windows](https://user-images.githubusercontent.com/664193/98104751-cb4de080-1e8e-11eb-8c16-1efaf2b30d49.png)

Dialog API reported from Outlook Online (https://outlook.office.com)
![DialogAPI_OWA](https://user-images.githubusercontent.com/664193/98104755-cdb03a80-1e8e-11eb-8e74-15fe7e4cefea.png)

Log of the dialog variable after it has been displayed showing the `messageChild()` function is present and as such, 1.2 is supported:
![DialogVariable](https://user-images.githubusercontent.com/664193/98104761-cee16780-1e8e-11eb-9648-ef7e279b41dd.png)

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.
For work around please use 
`Office.context.requirements.isSetSupported('Mailbox', '1.9')
`
It too has the same changes.

**Comment by jak-hammond** [comment]
Ah, okay, this was actually a question I had asked elsewhere but got no answer, does Dialog API 1.2 have a dependency on Requirement Set 1.9? I ask as according to the issue I have logged #1479 here about Mac support and the documents say that Mac doesn't currently support Requirement Set 1.9 yet, but it does (or should) support Dialog API 1.2......so I am trying to understand if the Dialog API is independent of the Mailbox API or not.

**Comment by exextoc** [comment]
Two Way Dialog Api functionality was released along with Mailbox 1.9 Api set. So while it doesn't really have any direct dependency; but you won't get this new DialogApi support in previous Mailbox Api set i.e 1.8 and below.

**Comment by jak-hammond** [comment]
So if the Mac Outlook doesn't currently support 1.9, but does support Dialog API 1.2, is this an error in the documentation or something else?

**Comment by exextoc** [comment]
> So if the Mac Outlook doesn't currently support 1.9, but does support Dialog API 1.2, is this an error in the documentation or something else?

Hello, @jak-hammond - For OWA can you please check whether DialogApi 1.2 is behaving ideally or not? The fix has been made and is in process of being rolled out.

For Mac scenarios, we will communicate in the other github thread (https://github.com/OfficeDev/office-js/issues/1479)

**Comment by jak-hammond** [comment]
Hi @exextoc, I have taken a quick look on Office Online and can confirm that the Dialog API is now being correctly supported, thanks for getting this fixed :)

![image](https://user-images.githubusercontent.com/664193/100210416-df6f8580-2f02-11eb-91ec-2202d68a217a.png)

**Comment by exextoc** [comment]
Thanks for confirming.
