### ISSUE TITLE
Outlook Online: empty space (50px) under the add-in pane in a separate window

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1477]
## Steps to Reproduce, or Live Example
* Create a new email in Outlook Online by using for example the Chrome browser.
* Click the "Open in new window" button.
* Start any add-in for compose mode.
* Notice that the add-in's pane does not take all space.

## Your Environment
* Platform: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 
* Operating System: Windows 10
* Browser: Chrome version 86.0.4240.111

## Useful logs
- [ x ] Screenshots
![ol-online-new-window](https://user-images.githubusercontent.com/28924916/98130836-be031700-1ecb-11eb-9c09-58ac89a0e91c.png)

**Comment by jak-hammond** [comment]
I have also seen this, seems very intermittent, some times it will resolve itself from a simple open and close and other times it will stick around for a while.

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

**Comment by exextoc** [comment]
We are currently unable to reproduce this issue on our end. Are you still able to reproduce it?

**Comment by DmitryKostochko** [comment]
I have just re-tested and cannot reproduce the issue.

**Comment by ajays-msft** [comment]
This issue has been fixed. Thank you for raising the issue and helping us make the product better.
