### ISSUE TITLE
Office.EventType.DialogParentMessageReceived triggered twice in Outlook Online

### ISSUE THREAD

**Issue by jak-hammond** [OfficeDev/office-js#1478]
When implementing the `messageChild()` functionality for the dialog API, it requires the registration of an event handler for the `Office.EventType.DialogParentMessageReceived` event. When run on OWA/Outlook Online, the handler is triggered twice whilst the same code when running on Outlook for Windows is only triggered once.

## Expected Behavior
Event will only be fired once.

## Current Behavior
Event is currently fired twice.

## Steps to Reproduce, or Live Example
https://github.com/jak-hammond/office-js-safari-itp/tree/dialog-message-child
Checkout and ensure that you are on the `dialog-message-child` branch, the master branch is currently being used to repro the issue reported in #1474 

* Additional details:
  1. Open the add-in
  2. Click open dialog
  3. Click message dialog
* Alternatively:
  1. Compose a message
  2. Send the message
  3. Send processing will occur and dialog will be displayed
  4. After a few seconds, the message event will fire automatically

## Context
The handler being run twice could result in multiple expensive operations being carried out, HTTP requests for instance, or data being duplicated both of which can result in a poor user experience or application performance/functionality issues.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Windows and macOS
* Browser (if using Office on the web): Chrome, Chromium Edge and Safari all demonstrate the issue

## Useful logs
![DoubleEvent](https://user-images.githubusercontent.com/664193/98144342-35cc4400-1ec2-11eb-87aa-ee2b94c06891.png)

**Comment by exextoc** [comment]
Thanks for reposting this issue, The fix has already been made and is in roll-out phase. 
Please wait while the fix reaches you.

**Comment by jak-hammond** [comment]
Is there an ETA on when it will reach production?

**Comment by exextoc** [comment]
Please expect the changes to reach by End Of Next Week.

**Comment by jak-hammond** [comment]
Thanks, I will check the reproduction again on Friday 13th or Monday 16th and if fixed will close off the ticket.

**Comment by jak-hammond** [comment]
@exextoc I have checked on https://outlook.office.com and the issue is still present.

**Comment by exextoc** [comment]
Sorry, it was a mistake from our side. Fix is rolling out. We will let you know once fix is available to users.

**Comment by exextoc** [comment]
The fix has been made available to 100% users.
