### ISSUE TITLE
Office.context.ui.addHandlerAsync is not a function

### ISSUE THREAD

**Issue by jak-hammond** [OfficeDev/office-js#1479]
According to the [documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/dialog-api-requirement-sets) on the Dialog API, and the response from the `isSetSupported()` method, Outlook for Mac should support the 1.2 set of this API however, when trying to wire up an event handler for the appropriate event, the error `Office.context.ui.addHandlerAsync is not a function` is thrown in the console.

## Expected Behavior
The event handler function will be available to register the handler necessary to implement the `messageChild()` functionality.

## Current Behavior
The error of `Office.context.ui.addHandlerAsync is not a function` is thrown in the console and the event is not registered, as a result the functionality provided by the new `messageChild()` function is not available.

## Steps to Reproduce, or Live Example
https://github.com/jak-hammond/office-js-safari-itp/tree/dialog-message-child
Checkout and ensure that you are on the `dialog-message-child` branch, the master branch is currently being used to repro the issue reported in #1474 

* Additional details:
  1. Open the add-in
  2. Click open dialog
  3. Inspect the console of the opened dialog to see the message

## Context
Due to the issues #1474 and #1399 we are looking at ways we can work around using officially supported methods, the ability to message a dialog from the parent code works in our testing but it now fails to run on Mac making the solution non-workable as we need to be confident it will run on all 3 platforms before we can implement this as a proper fix for the 2 issues our users are seeing.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 16.44 (20110103)
* Operating System: macOS 10.15.7
* Browser (if using Office on the web): N/A

## Useful logs
![addHandlerAsync](https://user-images.githubusercontent.com/664193/98150821-24396b00-1ec7-11eb-9d76-1770b9570c27.png)

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

**Comment by jak-hammond** [comment]
So the `messageChild` functionality in the 1.2 Dialog API will not be available until this is fixed?

**Comment by exextoc** [comment]
There are some alternative ways for parent-to-dialog-box messaging suggested here- https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#conditional-messaging-from-parent-page-to-dialog-box. Can you please try those?

**Comment by jak-hammond** [comment]
Thank, I've seen that piece of documentation, however, due to #1474 and #1399 I am trying to find a solution that will work for all platforms, which is proving difficult given these 3 issues combined. This `messageChild()` functionality seems to solve everything, from our testing, hence our eagerness to get this issue fixed so we can implement it, if it could be bumped up in some priority, that would be hugely appreciated.

**Comment by exextoc** [comment]
We have fixed this issue and fix should be available with latest build.

**Comment by jak-hammond** [comment]
@exextoc Can I get a build number that this is fixed in please, I updated my Outlook this morning to the version shown below and the issue is still present.

![image](https://user-images.githubusercontent.com/664193/100209803-36288f80-2f02-11eb-8888-50e13cbd64e3.png)

**Comment by exextoc** [comment]
Apologies. It is a mistake from our end. Fix is not yet available fully world-wide. We will update you once fix is available in December sometime. Thanks for your patience.

**Comment by exextoc** [comment]
Hi @jak-hammond the fix has been rolled out and we have verified it with the add-in and repro steps given by you. We cannot see the console error any more. Please confirm from your end.

**Comment by jak-hammond** [comment]
Sorry for such the long delay, I've just tested the steps using the sample application that I created before and can confirm that this is fixed and is now working as intended 👍
