### ISSUE TITLE
Missing rest Url property in the mailbox context object in New Outlook for Mac

### ISSUE THREAD

**Issue by nchakravarthi** [OfficeDev/office-js#1480]
Office.context.mailbox.restUrl property is missing, the value of the property is ""

## Expected Behavior
Ideally, **_Office.context.mailbox.restUrl_** property should fetch the restUrl of the mailbox.

## Current Behavior
The value of the **_Office.context.mailbox.restUrl_** property is empty string in the [New Outlook for Mac](https://w2.outlook.com/outlookmac/)

## Steps to Reproduce, or Live Example
It is happening in a normal scenario. Just check for Office.context.mailbox.restUrl 

## Context
We need restUrl property value to fetch the mailbox message content with messageId. 

e.g: ${restUrl}/v2.0/me/messages/${messageId}

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Microsoft Outlook on Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.42 (20101102)
* Operating System: Mac OS
* Browser (if using Office on the web): NA

## Useful logs
Please check the recording of the same 
https://1drv.ms/v/s!Ai-W12b0Y7A3jptZu-tWWEezkGW9Ig?e=xto9Hm

**Comment by exextoc** [comment]
@gs-nchakravarthi This issue is already fixed, and it will be rolled out in next monthly build release. This fix is currently in Insider Fast build, if you are in Insider fast and still seeing this issue then you can try removing outlook.com account and adding it again.

**Comment by nchakravarthi** [comment]
@exextoc I have verified the same in Insider build and it is working fine. However, I was able to only access the restUrl after I reconfigured the account. 

Does everyone using the newer version in the upcoming build needs to do that? 

If yes, that would be a bad user experience asking users to reconfigure their accounts in Outlook

**Comment by nchakravarthi** [comment]
@exextoc Can you answer the above question?

**Comment by exextoc** [comment]
@gs-nchakravarthi Having to reconfigure account to access restUrl is a bug at our end and the team is currently working on fixing this. We unfortunately have no timelines to share at this point.

**Comment by nchakravarthi** [comment]
@exextoc Is there any update on this issue? 

Currently, we are asking our customers to stop using the _New Outlook for Mac_ due to this issue. 

This is a critical bug in terms of the functionality, it is blocking majority of the APIs

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in latest build.
