### ISSUE TITLE
Outlook Online: Supertip's Title is added to button's label in ... menu

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1481]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We are developing an Outlook add-in for compose mode. Recently we have noticed that the Supertip->Title value from the manifest is added to the add-in's button label in the 3 dots (...) menu.

## Expected Behavior
The Title of Supertip shall not be added, its value may contain quite a long string and this may mangle the ... menu.

## Current Behavior
The Title of Supertip is added to the button's Label.

## Steps to Reproduce, or Live Example
1) Install any add-in for compose mode, e.g. https://online-addins.ablebits.com/testaddin/manifest.xml
2) Go to Settings -> Mail -> Customize actions, check the add-in in the Toolbar section and click Save (please see the screenshot attached).
3) Create a new email and click the ellipsis (...) button.
4) As you can see, the supertip's value is shown (please see the screenshot attached).

* Link to live example: https://online-addins.ablebits.com/testaddin/manifest.xml

* Additional details:
  1. The issue is reproducible for both Microsoft 365 and Outlook.com accounts.

## Your Environment
* Platform: Office on the web
* Host: Outlook Online
* Office version number: 
* Operating System: Windows 10, Catalina 10.15.7
* Browser (if using Office on the web): Chrome 86.0.4240.183, any other browser

## Useful logs
- [ x ] Screenshots
![ol-online-settings](https://user-images.githubusercontent.com/28924916/98230865-b6477f00-1f6c-11eb-896d-1f3587fac7cd.png)
![ol-online-3dots-menu](https://user-images.githubusercontent.com/28924916/98230888-be9fba00-1f6c-11eb-8791-468ce2dca300.png)

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by DmitryKostochko** [comment]
Sorry for bothering you, but do you have any news about this issue?

**Comment by exextoc** [comment]
We are currently not able to reproduce this issue in flyout and old "..." UX. Is the issue still reproducible on your end?

**Comment by DmitryKostochko** [comment]
The issue is still reproducible, please see the screenshot below.
![image](https://user-images.githubusercontent.com/28924916/160231800-5e1de5ea-cb05-424a-9007-d7053c63a83e.png)

**Comment by exextoc** [comment]
We are still unable to repro the issue at our end. Can you please configure the add-ins, repro the issue and share the credentials to "OutlookAddins@M365x693897.onmicrosoft.com" so that we can debug better?

**Comment by DmitryKostochko** [comment]
Here is the manifest file of our test add-in:
https://online-addins.ablebits.com/testaddin/manifest.xml

1. Sign-in into an outlook.com account and install the add-in.
2. Go to Settings -> View all Outlook settings -> Mail -> Customize actions, turn on the Test Addin in the Toolbar section, click Save:
![image](https://user-images.githubusercontent.com/28924916/160419113-d1e1ef03-69e0-41b8-810b-d5523bc986de.png)

4. In outlook.com, click the New message button and then ...
5. Note, the Title of the Supertip from the manifest file is shown in the ... menu:
![image](https://user-images.githubusercontent.com/28924916/160420050-f034ba8c-0c39-42ad-93f9-77f5a343f6de.png)

Please let me know if you need any additional information.

**Comment by exextoc** [comment]
@DmitryKostochko  Thanks for the details regarding the issue. We are able to repro it now, and it has been put on our backlog. We, unfortunately, have no timelines to share at this point.
Internal tracking id: Eg: Outlook Web: 149641

**Comment by DmitryKostochko** [comment]
@exextoc, do you have any news about this issue? We still see it on iPad in Safari.
