### ISSUE TITLE
addFromBase64 - Preview API - Does not copy sheets from xlsm files

### ISSUE THREAD

**Issue by jnSWPC** [OfficeDev/office-js#1482]
## Expected Behavior
Select xlsm file and then  copy worksheet to a target excel document. The sheet gets copied.

## Current Behavior
The api copies sheets when the source workbook is xlsx type but seems to error out during addFromBase64 statement when the source excel document is xlsm. type  Wanted to check if xlsm files are supposed to be supported?

## Steps to Reproduce, or Live Example

* Link to live example: ______

Sample code

var myFile : any = document.getElementById("files");
            var reader = new FileReader();
            reader.readAsDataURL(myFile.files[0]);
            reader.onload = (event) => {
                 Excel.run( function (context) {
                    // strip off the metadata before the base64-encoded string
                    var startIndex = reader.result.toString().indexOf("base64,");
                    var workbookContents = reader.result.toString().substr(startIndex + 7);

                    var sheets = context.workbook.worksheets;
                    sheets.addFromBase64(
                        workbookContents,
                        [workSheetName], // get all the worksheets
                        Excel.WorksheetPositionType.after, // insert them after the worksheet specified by the next parameter
                        sheets.getActiveWorksheet() // insert them after the active worksheet
                     );     

                     const sheet = context.workbook.worksheets.getItem(workSheetName);
                     sheet.visibility = Excel.SheetVisibility.visible;
                     sheet.activate();
  
                    return context.sync();
                 }).catch(function (error) {

                     //Need to create logger 
                     console.log("Error: " + error);
                     if (error instanceof OfficeExtension.Error) {
                         console.log("Debug info: " + JSON.stringify(error.debugInfo));
                     }

                 });

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______PC desktop
* Host [Excel, Word, PowerPoint, etc.]: ______Excel
* Office version number: ______
   ![image](https://user-images.githubusercontent.com/22331494/98250816-8e8cf280-1f3d-11eb-9435-1e7cb9236d67.png)

* Operating System: ______Windows
* Browser (if using Office Online): ______IE 11

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lumine2008** [comment]
Thanks @jnSWPC for your question. addFromBase64 support xlsx and xltx file types.  we don't support vba macro file type. so I would suggest that you could convert xlxm to xlsx. thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@jnSWPC We'll close this issue now but if you need further help with this, let us know so we can reopen this issue or you can create a new one.

Thanks.
