### ISSUE TITLE
Outlook Desktop: addFileAttachmentAsync adds an attachment (fake?) to the attachments list after unsuccessful call

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1483]
In an Outlook add-in for compose mode, we are using the addFileAttachmentAsync function to add attachments. In desktop Outlook, an attachment is added to the attachments list even if a call failed, i.e. result.status === "failed".

## Expected Behavior
An attachment shall not be added to the list of attachments in this case.

## Current Behavior
The attachment is added, please see the screenshot below.

## Steps to Reproduce, or Live Example
1) Create a new email in desktop Outlook.
2) Start an add-in and execute the following code:
`    function addFileAttachmentAsyncTest() {`
`      Office.context.mailbox.item.addFileAttachmentAsync('https://microsoft.com/xyz.zip', 'xyz.zip', { },`
`        function (result) {`
`          console.log(result);`
`        });`
`    }`
3) Note, I specially provide the URL to a non-existing zip file to get an error.
4) As you can see, the new attachment is added.

* Additional details:
  1. The issue exists only in Outlook Desktop on Windows. Outlook Online and Outlook for Mac work correctly.

## Your Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: Version 2010 (build 13328.20340)
* Operating System: Windows 10 version 2004
* Browser:

## Useful logs
- [ x ] Screenshots
![ol-desktop-attachment](https://user-images.githubusercontent.com/28924916/98261657-bc9e2100-1f95-11eb-81a1-d0908de340ed.png)

**Comment by exextoc** [comment]
Thanks for reporting this issue. The described behavior is consistent with how Outlook Desktop in Windows behaves if a user directly adds a non-existing file URL attachment. Please try it. To avoid this condition, we recommend you to validate the URL and check if the file exists before calling addFileAttachmentAsync.

**Comment by DmitryKostochko** [comment]
@exextoc, thank you, but there is one difference between adding a fake attachment manually and by using addFileAttachmentAsync. In case of addFileAttachmentAsync, the attachment is added and the "Download failed" label appears. When added manually, the attachment is also added but there is no "Download failed".

In general, I don't quite understand why addFileAttachmentAsync behaves differently in Outlook Desktop in comparison with all other platforms. As I mentioned above, Outlook Online and Outlook for Mac handle this scenario correctly. In Outlook Desktop, we do get the "Internal error" error from the addFileAttachmentAsync function but an attachment is still added. To me, this behavior is weird and inconsistent, sorry.

Is this specificity documented anywhere? Please let me know.

**Comment by DmitryKostochko** [comment]
@exextoc, sorry for bothering you but do you have any news regarding this issue?

**Comment by exextoc** [comment]
For the first point, I'm not observing what you see. If I add a fake url (say https://i.imgur.com/WJXkliccccf.png) via Attach File -> Browse This PC. And then paste that URL in, I get a "Download failed" in the UI. 

There are some issues where the client teams have implemented features differently across platforms (Windows, Mac, Web). We strive to make the APIs consistent across all clients, but there are cases where the core feature is implemented differently across those platforms which results in differences like this.

**Comment by DmitryKostochko** [comment]
> For the first point, I'm not observing what you see. If I add a fake url (say https://i.imgur.com/WJXkliccccf.png) via Attach File -> Browse This PC. And then paste that URL in, I get a "Download failed" in the UI.

Yes, you are right, now I see the same behavior, I guess it was changed in the latest Outlook update (I have version 2011 now), thank you.

> There are some issues where the client teams have implemented features differently across platforms (Windows, Mac, Web). We strive to make the APIs consistent across all clients, but there are cases where the core feature is implemented differently across those platforms which results in differences like this.

I fully understand you and am trying to help in finding and removing these differences. In my opinion, if the API function cannot perform its action (add an attachment in our case) and returns 'failed', then the attachment shall not be added.

**Comment by exextoc** [comment]
Thanks for the feedback @DmitryKostochko .
We will pass this feedback onto the client/product team as we strive for a more consistent experience across all Outlook clients.
