### ISSUE TITLE
After adding new permission to manifest Outlook keeps prompting to upgrade

### ISSUE THREAD

**Issue by modestfake** [OfficeDev/office-js#1485]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Recently we've changed the permission of Outlook add-in from `ReadWriteItem` to `ReadWriteMailbox`. According to [this page](https://docs.microsoft.com/en-us/office/dev/store/appsource-submission-faq#what-happens-when-i-update-my-add-in-to-a-new-version-in-microsoft-appsource), the user must consent to the new permission level:
> When an existing customer launches the updated add-in for the first time, a notification appears either in the task pane or the body of the document that prompts the user to update their add-in. When the user chooses Update, the latest version of the add-in launches.

> If the updated version includes new permissions, the user must consent to them.

When the new version of manifest was accepted and published, we've noticed that Outlook keeps prompting to upgrade the add-in. I've reproduced several scenarios on Outlook for Windows, Outlook for Mac, and OWA.

* Sometimes, when I open the add-in's sidebar, it shows the message with the "Update" button (or "Upgrade", sorry, don't remember). When I click it, it opens the add-ins store with the add-in highlighted. But nothing happens. I close this popup and the add-in works now until I close the sidebar and open it again. Then it prompts me to update again.
* Another scenario is that when I click the "Update" button and then close the popup from the add-ins store, the message about upgrading is still there.
* The customer reported this case. When they open contextual add-in, they see a prompt, click "Update", close the popup, and then when they open the contextual add-in again, they see this message:
![image](https://user-images.githubusercontent.com/16977959/98302461-179b3c80-1fc5-11eb-8a3d-ea24021eb863.png)
They close the add-in, open it again but they are stuck with this message.

## Expected Behavior
Once the user clicks the "Update" button, the add-in is updated to the latest version and never asks to update again.

## Current Behavior
The add-in keeps prompting to update the add-in, even if the user has done this.

## Steps to Reproduce, or Live Example
Not sure how to reproduce it, as you need to have an actual listing in AppSource with `ReadWriteItem` permission and then upgrade it to `ReadWriteMailbox`. Maybe you can do this on staging environment.

## Context
Because of this issue, a lot of our customers can't use the add-in at all. For most users, it's annoying, since it requires them to update the add-in each time they open the sidebar or contextual add-in. Also, our MAU has dropped a bit because of this issue.

As a workaround, we suggest our customers uninstall the add-in and then install it again, so the latest version is installed. But not all of our customers reach out to us, so we can't communicate with all of them.

## Your Environment
* Platform: PC desktop, Mac, OWA
* Host: Outlook
* Office version number: different
* Operating System: macOS, PC
* Browser: Chrome

**Comment by MartinSSeifert** [comment]
We also see similar behaviors (Update message) when we update our manifest file and re-submit those changes to the office store. Once that gets approved, many of our customers get yellow update messages. We believe that for centralized deployed add-ins, users should not ever get an update message. You can help upvote this matter in UserVoice here: https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/41274478

**Comment by exextoc** [comment]
Hi,

Could you please share Fiddler trace for this issue to addin-help@outlook.com.
This is required to debug this issue from our end.

Here are the steps

1.	Install Fiddler.(https://www.telerik.com/fiddler)
2.	Close ALL applications. 
4.	Launch fiddler: 
•	Go to: Tools -> Options… -> HTTPS
•	Enable "Decrypt HTTPS traffic" 
5.	Launch Outlook Desktop Client: 
•	Run the flow which has issue.Here update addin flow.Cover entire flow including clicking of update button
        then going to store then relaunch addin and when you again see the same update message
6.	Save Fiddler trace: Go to File -> Save -> All Sessions. 
7.	Share the Fiddler trace file (*.saz) as attachment over email.

**Comment by modestfake** [comment]
@exextoc unfortunately I have already reinstalled the add-in and have the latest version installed. Is there a way to install the previous version from AppSource, so I could reproduce the issue? I don't have any accounts with the older version.

**Comment by modestfake** [comment]
@exextoc we've been able to find an account where we still have the previous version installed and reproduced the behavior on Outlook for Mac and OWA. I've sent you an email.
