### ISSUE TITLE
getTypeAsync needs to support read mode

### ISSUE THREAD

**Issue by vault79** [OfficeDev/office-js#1490]
Need a method to identity CoercionType (Text/Html) in read mode, but getTypeAsync doesn't support read mode.
A developer want to create reply form by [displayReplyAllForm](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-1.5&preserve-view=true#displayreplyallform-formdata-). displayReplyAllForm supports to set Text or HTML format data in read mode. But, Office.js doesn't have method to identity CoercionType in read mode now, so it's hard for developers to decide which format to insert via displayReplyAllForm. It can make Bad UX (non well formatted email) to end users.

## Expected Behavior
getTypeAsync returns CoercionType in read mode. Or Office.js has another method to get CoercionType in read mode.

## Current Behavior
getTypeAsync doesn't support read mode even though a developer need to know CoercionType when he/she uses displayReplyAllForm.

## Steps to Reproduce, or Live Example
Use `getTypeAsync` in read mode, then you get exception.

## Context
This issue blocks me to create correct format reply email via displayReplyAllForm. Currently, I need to hard code HTML or Text format body via displayReplyAllForm , because I can't identify end user's email format. It can show non-well formatted email to end users.

I want to show well formatted email by identifying user's email format. For example, I want to Insert HTML format email when a user uses HTML format. 

I don't persist getTypeAsync method. I can accept any way to know CoercionType in read mode. 

## Your Environment
It happens in any platform, but let me write my own dev platform here.
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.42
* Operating System: macOS Catalina 10.15.7
* Browser (if using Office on the web): Microsoft Edge 86.0.622.58

## Useful logs
No logs
- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
Currently getTypeAsync API is not supported in Message read mode. We track Outlook add-in feature requests on our  [user-voice](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins ) page. Please add your request there. Feature requests on user-voice are considered when we go through our planning process.
