### ISSUE TITLE
Enable outlook addin for multiple mail selection

### ISSUE THREAD

**Issue by Namrata99sah** [OfficeDev/office-js#1491]
Hi,
How to activate the addin when multiple emails are selected. I tried the ItemHasRegularExpressionMatch for any generic filter so that the addin button is enabled for all but it's not working.

**Comment by JuaneloJuanelo** [comment]
This is actually a known gap in the platform, please upvote this user request to influence our backlog
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/11080962-allow-outlook-add-in-commands-to-be-used-on-select

**Comment by fr-pagesurfer** [comment]
Looks like the UserVoice link stopped working as Microsoft seems to be moving away from that service. Is there another way to vote for this feature?

**Comment by atomroflman** [comment]
Any updates on this?

**Comment by jtrueblood-anaqua** [comment]
This is a pretty big gap for us as well. The functionality is available in VSTO, but completely missing from web-based add-ins.

**Comment by alexmaris** [comment]
@JuaneloJuanelo - the uservoice site linked above is no longer working. What's a good medium for us to vote on this currently missing functionality?
