### ISSUE TITLE
Office.context.host is unavailable in one-time purchase Outlook 2016

### ISSUE THREAD

**Issue by ig-jb** [OfficeDev/office-js#1492]
One-time purchase Outlook 2016 is documented to support requirement sets up to 1.4 (or at least 1.3 depending on patch version).

Office.context.host is documented as being in requirement set 1.1.

https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.1/office.context

## Expected Behavior
I would expect Office.context.host to equal Office.HostType.Outlook

## Current Behavior
Office.context.host is undefined and does not equal Office.HostType.Outlook.

The only members of Office.context available in Outlook 2016 are:
[contentLanguage","displayLanguage","touchEnabled","commerceAllowed","license","ui","mailbox","requirements","roamingSettings]

## Steps to Reproduce, or Live Example
Script lab example:

$("#run").click(run);

function run() {
  switch(Office.context.host){
    case Office.HostType.Outlook:
      console.log("Success");
      break;
    default:
      throw new Error("Test failed");
  }
}

## Context
I am implementing functionality that needs to differ slightly depending on which Office host is in use. Instead of using the correct mechanism to determine this (Office.context.host) I will need to use the presence or lack of Office.context.mailbox instead to determine if we are in Outlook 2016. 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web (working), Office 2016 Pro-Plus (not working)
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.5056.1000
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome

## Useful logs
Outlook 2016:
![image](https://user-images.githubusercontent.com/73241590/98536873-632d3f00-2280-11eb-8ed4-ba06426d9ff8.png)

Outlook online:
![image](https://user-images.githubusercontent.com/73241590/98536959-7d671d00-2280-11eb-99f8-32065db4499f.png)

**Comment by exextoc** [comment]
Are you able to reproduce this issue in another Office Application? For example in Excel or Word.
Can you please provide your [Exchange version number? ](https://docs.microsoft.com/en-us/exchange/new-features/build-numbers-and-release-dates?view=exchserver-2019)

**Comment by ig-jb** [comment]
@exextoc I've tried this in Word 2016 and although Script Lab refuses to run (states too old) - I was able to load an addin to output the available keys in Office.context which returned `["contentLanguage","displayLanguage","touchEnabled","commerceAllowed","host","platform","isDialog","diagnostics","license","ui","auth","document","officeTheme","requirements"]` ; correctly containing "host" with a value of "Word"

We are using Office 365, I'm not sure where we could find the exchange version there?

**Comment by exextoc** [comment]
Thanks for bringing this to our attention. We don't support Office.context.host for Outlook 2016 MSI, and we will fix the documentation. You can you try using [Office.context.mailbox.diagnostics](https://docs.microsoft.com/en-us/javascript/api/outlook/office.diagnostics?view=outlook-js-1.7) which has hostName.

**Comment by ig-jb** [comment]
Thanks @exextoc, I'll use the workaround for 2016.
