### ISSUE TITLE
Inserting svg from office web on windows fails

### ISSUE THREAD

**Issue by abdul-kurtosys** [OfficeDev/office-js#1493]
Attempt to insert an svg using Office.context.document.setSelectedDataAsync fails inside word, on the web (office365), on windows 7 and 10. All tested browsers fail (chrome, edge, internet explorer)

## Expected Behavior
Svg should be inserted like on other platforms.

It currently works on windows desktop, mac desktop, and mac web. It does not work for any browser on windows 7/10

## Current Behavior
An error is returned when calling Office.context.document.setSelectedDataAsync

## Steps to Reproduce, or Live Example

* Link to live example: [Gist Example](https://gist.github.com/abdul-kurtosys/ad277326b7decfc5ce1fea1265447215)

* Additional details:

## Context

We are busy with the testing phase our add-in getting ready to publish it to app source. The functionality is critical to the functioning of our add-in. We insert SVGs into documents that later get substituted as part of functionality we provide to our customers. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: word
* Office version number: web
* Operating System: Windows 7 and windows 10
* Browser (if using Office on the web): Chrome 86.0.4240.11, Internet Explorer 11.572.19041.0, Edge 86.00.622.63

## Useful logs

- [x] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

The stringified result of the setSelectedDataAsync call:

{
  "status": "failed",
  "error": {
    "name": "Unsupported Enumeration",
    "message": "The enumeration isn't supported in the current host application.",
    "code": 5007
  }
}

![ie](https://user-images.githubusercontent.com/55397893/98544867-47846180-229d-11eb-9f57-d8ec904acf44.png)
![edge](https://user-images.githubusercontent.com/55397893/98544883-4bb07f00-229d-11eb-83f8-3f75584156b3.png)
![chrome](https://user-images.githubusercontent.com/55397893/98544886-4ce1ac00-229d-11eb-8286-e40d264848d9.png)

**Comment by MartinSSeifert** [comment]
+1 on the ask for supporting SVG via Office.context.document.setSelectedDataAsync

**Comment by MandytMSFT** [comment]
Currently the feature you requested is not supported due to security reason. We track Office Add-in feature requests on our [UserVoice page](https://officespdev.uservoice.com/) Please add your request there. Feature requests on user-voice are considered when we go through our planning process.
