### ISSUE TITLE
[Excel] Issue using RangeArea.copyFrom to copy values from one RangeArea to another RangeArea

### ISSUE THREAD

**Issue by AbhishekGupta100** [OfficeDev/office-js#1494]
I'm trying to copy values from multiple ranges and paste to another set of ranges of the same size using ```RangeArea.copyFrom```, but I am getting General Exception Error. 

## Expected Behavior
I expect to be able to copy-paste values from one RangeArea to another using ```RangeArea.copyFrom```. 

## Current Behavior
I am getting a General Exception Error when I am trying to run the function.

## Steps to Reproduce, or Live Example
```
async function loadValues() {
        await Excel.run(async function main(context) {
            let sheet = context.workbook.worksheets.getActiveWorksheet();
            var rng = sheet.getRanges("A1:A5,C1:C5");
            rng.copyFrom("E1:E5,G1:G5",Excel.RangeCopyType.values);
            await context.sync();
        }).catch(errorHandler)
    }
```

## Context
I am trying to paste values in multiple ranges at the same time using RangeArea to reduce the number of ```context.sync```. I am unable to do so as I am not able to keep the source in ```RangeArea.copyFrom``` as a RangeArea.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Office 365
* Operating System: Windows
* Browser (if using Office on the web): Google Chrome

## Useful logs

Console errors :  Error: GeneralException: There was an internal error while processing the request.

**Comment by lumine2008** [comment]
Thanks, @AbhishekGupta100 for your post, as our design principle is to align with UI, 
if the discontinuous range is in the same column or row, we will support, but due to both Win32/Mac and Excel Online doesn't support copy discontinuous range to another discontinues range from UI action, therefore, this action is not supported via API as well. Thanks for your support

**Comment by ElizabethSamuel-MSFT** [comment]
@AbhishekGupta100 Thanks for asking about this. Based on @lumine2008's response, I'll close this issue now. However, if you have further questions, you can let us know so we can reopen this issue or you can create a new one.

Thanks.
