### ISSUE TITLE
Outlook-OWA not displaying email properly when email headers are sent.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#1495]
As the title states, there is a case where OWA fails to properly display the email if some email headers are in the content of the email. Outlook clients display the headers correctly though.

I don't think this is the right forum, but took a chance at filing the ticket anyway since I have had pleasant experiences with this group. And I am hoping this will be re-routed to the right team. Thank you in advance your kindness and understanding of my decision to post here.

## Expected Behavior

This is how Outlook displays the email. And the right way to display it : 
[Correct Email Display](https://imgur.com/a/v2My2J9)

## Current Behavior

This is how it is displayed in Outlook-via-browser : 
[Reply and Forward Incorrectly Shown](https://imgur.com/HkbzRp2)

## Steps to Reproduce, or Live Example

* Link to live example:  NONE
1. Use MAC or WINDOWS Outlook client.
2. Send the following email as **PLAIN TEXT** : 
```
Received: from SG2PR01MA4000.apcprd01.prod.exchangelabs.com
(2603:1096:4:83::23) by SG2PR01MB2507.apcprd01.prod.exchangelabs.com
(2603:1096:4:51::20) with Microsoft SMTP Server (version=TLS1_2,
cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.3499.29; Wed, 4 Nov
2020 04:59:09 +0000
Received: from SG2PR01MA4000.apcprd01.prod.exchangelabs.com
([fe80::d06e:7395:ebbc:8f61]) by SG2PR01MA4000.apcprd01.prod.exchangelabs.com
([fe80::d06e:7395:ebbc:8f61%3]) with mapi id 15.20.3499.032; Wed, 4 Nov 2020
04:59:09 +0000
From: John Doe 
To: John Doe 
Subject: Fw: this is a test message over 1mb
Thread-Topic: this is a test message over 1mb
Thread-Index: AQHWq7Nt16K6R+9SG0K6zdW0c3Tsxam3dvzT
Date: Wed, 4 Nov 2020 04:59:09 +0000
```
3. Once email is sent, view the email in Outlook-via-Browser.

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

I am sending some data for header analysis to some of my clients and colleagues. And this gets in the way.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
Just affects OWA.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
None really.

**Comment by glr0221** [comment]
@ElizabethSamuel-MSFT any chance somebody can take a look at this? Not really super important. But might be something to look at thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@glr0221 Thanks for raising this issue and pinging us about it. We'll take a look and direct where appropriate.

**Comment by exextoc** [comment]
This is not an add-in specific issue.
We will route this issue to Outlook team internally.

**Comment by glr0221** [comment]
Thank you @exextoc @ElizabethSamuel-MSFT. If this is properly routed, we can close this ticket then, Thank you again.

**Comment by ElizabethSamuel-MSFT** [comment]
Thanks for raising this issue, @glr0221. We'll close this issue now but if you have any further questions here, let us know so we can reopen it, or you can create a new issue.

Thanks.
