### ISSUE TITLE
(Word Online) Issue with Updating Content Control when removeWhenEdited set back to true from false.

### ISSUE THREAD

**Issue by hxltinh** [OfficeDev/office-js#1497]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior

update content control without removing the content control

## Current Behavior

the content control is removed when updated.
Happens on word Online, it should work fine on Word Native  

## Steps to Reproduce, or Live Example

1. Create a content control on Word with removeWhenEdited property is true.
2. Open ScriptLab
3. Set content control removeWhenEdited to false.
4. Update content control content.
5. Set content control removeWhenEdited back to true.
* Link to live example: [link](https://gist.github.com/hxltinh/e37b54c9594bde2daf98be76f3f90bcc)

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

Our target is updating the content control content without removing the content control when  removeWhenEdited is set. By set removeWhenEdited property to false temporary, and revert it back to before when CC updating is done. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): Chrome, Safari, Firefox, Edge

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by MandytMSFT** [comment]
@hxltinh Thanks for reporting! This should be an issue, I logged  BUG 4635116 for internal track.
