### ISSUE TITLE
Office.js Excel Add-in manifest update does not update command/ribbon

### ISSUE THREAD

**Issue by osvath58** [OfficeDev/office-js#1498]
We have developed an Office Add-in for Excel, when an updated manifest is uploaded, the next time Excel is opened, the add-in should be updated. 

The code for the panel is updated as expected, as well as the changes to the ribbon/commands. This holds true for the add-in panel, nut the command ribbon is not showing the latest changes for all users. Some see it right away, but others have to go into **_Admin Managed_** and do a **_Refresh_** to get the latest, or clear the cache in **_%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\_**.

**Comment by exextoc** [comment]
Hi osvath58, 

There is a cache implemented on the server side which could be preventing the Addins from refreshing immediately.
Cache expires after 24 hrs for Excel.
Can you please confirm how much time after deployment have we tried checking Excel?

**Comment by keyur32** [comment]
Hi @osvath58,  I think we've followed up with you offline about the 24 hour cache for centrally deployed add-ins. I'm closing this for now but please feel free to up re-open.
