### ISSUE TITLE
Request: Please provide a method to get the selected Timezone's offset in calendar.

### ISSUE THREAD

**Issue by thinksysprem** [OfficeDev/office-js#15]
Summary: I want to get the selected timezone's offset from UTC of the calendar event.

![image](https://user-images.githubusercontent.com/18140689/31424470-15db7020-ae78-11e7-8b8f-e3d44388b640.png)

Here I want to get the Pacific Time Zone's offset but I only get the offset of the timezone I am already in. 
(IST)
Expectation: Office.context.mailbox.item should have a method that gives me the selected timezone or rather preferably the timezone's offset of the calendar event.

Current Behavior:
Office.context.mailbox.item._data$p$0._data$p$0.timeZoneOffsets is an array containing only the timezone offsets of the timezone the user is currently in (In which he/she is creating the event in calendar.)

Change from Current Behavior:
Is it possible to provide the selected time zone's offset in some or any other preferred way?

  1. Login into your outlook web application using valid account credentials. 
  2. Assuming you see the mail's inbox directly (navigate to the mailbox if not) after logging in, Click the calendar icon at the bottom for creating a new Calendar event.

Unable to get the selected timezone's offset from the Outlook api.

Context:
Our Add-in has email contacts that are in different timezone than that of the selected timezone, So timezone offset is required to set the appointment time correctly in the Add-in's contact page (although it is already handled for the outlook contact in outlook email, but need the offset to adjust the time in the Add-in's contact page.)

Environment:
Platform: PC 
Host: Outlook web.
office-js version: v1.1
Operating System: Windows 7
Browser (if using Office Online): No, Chrome v61

**Comment by lucianorabu** [comment]
+1

**Comment by tuanjinn** [comment]
Microsoft, any update on this?
@thinksysprem I think you must create an user voice for this

**Comment by JuaneloJuanelo** [comment]
this is not a place for new feature requests. please add it in uservoice
https://officespdev.uservoice.com/

**Comment by abdulkareemnalband** [comment]
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/38501812-provide-api-to-get-event-start-end-time-zone-usin
