### ISSUE TITLE
Issue with PromiseConstructor in d.ts?

### ISSUE THREAD

**Issue by Zlatkovsky** [OfficeDev/office-js#150]
Per https://github.com/OfficeDev/office-js/issues/48#issuecomment-390313853:

> Quick remark here about the latest definitely typed package (under @ types/office-js). My web project is currently setuped to target ES5. When I try to use the definitely typed under @ types/office-js, I get an error about PromiseConstructor. I switched my project's typescript build target to ES6 and it seems to work. Isn't it a bit odd that you use a ES6 feature (PromiseConstructor) from lib.es6.d.ts for Office Add-In which doesn't support ES6 since it runs under IE11. The solution we found now is to target ES5 but specify lib ES6 so our project can build (the problem with that is that we can write/compile ES6 features like async, promise, etc but they will not work on runtime).

**Comment by eblancperso** [comment]
Can't you use IPromise interface like you used to in a previous version (1.1.6) ?

**Comment by Zlatkovsky** [comment]
I have investigated the issue.

In general, even with "es5", if your **lib** options in the tsconfig.json specified "es2015.promise", you wouldn't have seen this -- which is why I hadn't seen it, either.

However, it's a fair point that it should work even in the default configuration.  Pull request https://github.com/DefinitelyTyped/DefinitelyTyped/pull/26069 addresses this.
