### ISSUE TITLE
context.sync is throwing error in windows 10 build 1909 but not in 1803

### ISSUE THREAD

**Issue by SuprajitGhosh** [OfficeDev/office-js#1501]
We have been creating an office add-in for excel for our client. In Dev environment we have office 365(Microsoft Excel for Microsoft 365 MSO(16.0.13231.20250) 64-bit) and windows version 1803 (OS Build 17134. 1488). The custom tab we have created contains various buttons to perform read write operation on the excel. This is not working On one of the staging system. The only difference is that the windows version is 1909(OS Build 18363, 1016). 
when ever we are loading a taskpane after hitting a ribbon button it is suppose to check if the workbook contains specific worksheet name(If not then display message in dialog). To do that the context.sync() we put over there is throwing following error message. 

code	"AccessDenied"
data	undefined
debugInfo	{...}
description	"You cannot perform the requested operation."
httpStatusCode	403
innerError	null
message	"You cannot perform the requested operation."
name	"RichApi.Error"
stack	"AccessDenied: You cannot perform the requested operation.\n at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:26:292784)"

error.debugInfo.fullStatements.message	"You cannot perform the requested operation."
error.debugInfo.fullStatements.statement	"var worksheets = workbook.worksheets;"

Could you please help us on identifying the issue .....
Thanks in advance.

**Comment by MandytMSFT** [comment]
@SuprajitGhosh Thanks for your reporting. Is that possible to share your test code with a scriptlab gist to help us repro?  or did you simply try workbook.worksheets API with scriptlab to see whether the API call itself works or not ?   And what's the Excel Version on the bad environment?

**Comment by SuprajitGhosh** [comment]
Hi @MandytMSFT. Thank you very much for replying.
We have been using Visual Studio 2019 to create the add in. The excel version of the bad environment is version 2009(Build 13231.20262 Click to run).
The issue is occurring for the app we developed. Have not yet created a separate sample code to check if it is happening for that too as this is a staging system and installing VS in this environment or deploying another manifest would require special permission. I will update on this when we can create a sample code to recreate the issue.

**Comment by MandytMSFT** [comment]
@SuprajitGhosh Is this issue resolved for you? 

As for creating a sample code, you don't need install VS and deploy manifest, you can just use ScriptLab to try your API code. This can help identify whether the cause is from API call or related to Addin config or something else.

Here is how to use scriptLab: https://docs.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab
