### ISSUE TITLE
Duplicate Draft Events being Created in Outlook Web Access (OWA) after loading Add-in in New Event create window

### ISSUE THREAD

**Issue by Byron-Mo** [OfficeDev/office-js#1505]
## Update
This issue is also occurring on both Windows Outlook Desktop and Outlook for Mac. In these instances, after item.saveAsync is called, a draft of the event is saved even though the user chose to discard the event

![image](https://user-images.githubusercontent.com/14811552/110045919-4a99d680-7d00-11eb-9ad2-c11882aabf34.png)

## Expected Behavior

When the user creates a new event in Outlook Web Access and loads an Addin that calls item.saveAsync just after entering the subject, one draft of the event should be created in Outlook

## Current Behavior

When the user creates a new event in Outlook Web Access and loads an Addin that calls item.saveAsync just after entering the subject, duplicate draft events created in Outlook. This happens only in Outlook Web Access (OWA) and no issue with Outlook desktop clients.

## Steps to Reproduce, or Live Example

1. Login to Office365 OWA in any browser (Ex: Chrome)
2. Switch to Calendar
3. Create a new event
4. Enter any text in the 'Subject' field
5. Immediately load add-in that calls item.saveAsync
6. Close event without save/send
7. Duplicate events appear on the Calendar view

![rtaImage (1)](https://user-images.githubusercontent.com/14811552/99325948-2affa080-282c-11eb-964f-8b41132845b8.jpeg)

## Context

- This can be reproduced in any Office365 Outlook Web Access (OWA) and in any browser.
- No issue with desktop clients
- The issue occurs intermittently but very frequent

## Your Environment

* Browser (if using Office on the web): any browser

**Comment by exextoc** [comment]
Thank you for reporting this issue. It can be repro-ed and we have added this to our backlog. Unfortunately we don't have any timelines to share at the moment. 

As a workaround, you can try refreshing this page and this duplicate draft should disappear.

**Comment by wsywq** [comment]
Hi @exextoc  , i also met this issue. It's a quite confused for me. Hope you can fix it soon! Some of our customers also met this issue. I think it has a big impact on many people.

**Comment by JuaneloJuanelo** [comment]
tracking with bug 1784176
