### ISSUE TITLE
Unable to add attendees in new Outlook (Mac) if field is focussed

### ISSUE THREAD

**Issue by jameshoward** [OfficeDev/office-js#1506]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior

The following code, triggered as an add-in command, should add `test@example.com` to the required attendees field:

```
Office.context.mailbox.item.requiredAttendees.addAsync(['test@example.com'], addResult => {
  console.log(addResult);
  event.completed();
});
```

## Current Behavior

The code above works if the focus is elsewhere on the compose event form but the attendee is not added if the 'Add required attendees' field has focus. Regardless, the result is always `{"status": "succeeded" }`.

## Steps to Reproduce, or Live Example

* Link to live example: https://gist.github.com/jameshoward/2f89916389d89b833c3b7e3ee2fb470f

1. Create a new event
2. Focus into the 'Add required attendees field'
3. Run the ScriptLab code (Gist above) from the add-in menu (ScriptLab > Run)
4. Note that the attendee is not added
5. Focus into any other field or the body
6. Re-run the SciptLab code, again from the add-in menu (ScriptLab > Run)
7. Note that the attendee is added

## Context

Our add-in adds a required attendee to meetings but if the user has already started adding attendees and has focussed on the field, the functionality stops working.

## Your Environment

* Platform: Mac
* Host: Outlook (in 'New Outlook' mode only, it works fine in the old version)
* Outlook version number: 16.43 (20110804)
* Operating System: macOS Mojave (10.14.6)

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point
