### ISSUE TITLE
Outlook Add-in: Office.loadCustomPropertiesAsync cannot get the custom property of a exception meeting

### ISSUE THREAD

**Issue by wsywq** [OfficeDev/office-js#1508]
In my Outlook Add-in, i try to call Office.js API to save some information for a meeting. According to MSFT docs, i use Office.loadCustomPropertiesAsync to do it. Add-in calls this interface to get the custom property(cecp-clientId) of a exception meeting. 
## Expected Behavior

My expect result is that Add-in can get the custom property of this exception.

## Current Behavior

But actually, it returns null. Also, it works well when i open an occurrence or the whole series meeting.
## Steps to Reproduce, or Live Example

* Steps to reproduce:
1. Create a series meeting and use Add-in to set a custom property.
2. Invite some attendees and send it.
3. Change one instance into exception and open it.
4. Open Add-in to get the custom property which i saved before.

## Context

When the customers open a exception meeting, our Add-in cannot recognize this meeting so that our customers cannot do some change through Add-in.
This issue only occurs in the latest Outlook version(after Monthly channel 2005);
Aslo, i have created a stackoverflow [issue](https://stackoverflow.com/questions/64885883/office-365-win-add-in-cannot-get-the-custom-property-of-a-exception-meeting-thr)
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Monthly channel 2008(Build 13127.20638)
* Operating System: Win 10 
* Browser (if using Office on the web): NO

## Useful logs

Sample code
```
Office.context.mailbox.item.loadCustomPropertiesAsync(function(asyncResult){
  var customProps = asyncResult.value;
  console.log('property = '+JSON.stringify(customProps));

  var myProp = customProps.get("myProp");
  customProps.set("otherProp", "value");

  customProps.saveAsync(function(result){
     console.log('save result'+JSON.stringify(result));
  });
});
```

**Comment by exextoc** [comment]
There are developers that expect properties from the master series to NOT propagate to exceptions, and developers like you that expect them to be there, so we are investigating many possible solutions

**Comment by wsywq** [comment]
Thanks. We only want to get the cecp value for Add-in not all properties.

**Comment by exextoc** [comment]
Yes, that's what we are referring to. Some developers want the cecp values of an add-in to propagate from the master series to exceptions. Others do not desire such behavior. So we are currently investigating how to approach these scenarios.

**Comment by JuaneloJuanelo** [comment]
there is a workaround for this issue:
	Exception (from series) meeting is created
	Gets a webhook with series ID of the parent series
	Retrieves custom property of the series ID
	Then set property  it on the exception meeting
