### ISSUE TITLE
displayDialogAsync not working every time, works sometimes, hooked to on-send event in an outlook web add-in

### ISSUE THREAD

**Issue by 2bigO** [OfficeDev/office-js#1509]
## Expected Behavior
`displayDialogAsync` should show the dialog every time.

## Current Behavior
The dialog is not shown in about 1 out of 3 times, this happens when my users click send (the dialog is hooked to `ItemSend` event) in long email threads. It gets stuck in `[add-in] is working on your request`.

It's very important for my use case that the dialog is shown evry time consistently.

## Steps to Reproduce, or Live Example
* Link to live example: install the add-in from URL with https://stage.stanintelligence.com/manifest-alternatives/manifest-stage.xml

Since the above link is my production env, as a temporary workaround, I currently have a timeout of 1 seconds that performs `{ allowEvent: true }` if the dialog is not confirmed shown:

```js
setTimeout(() => {
  if (localStorage.getItem('onSendActive')) {
    localStorage.removeItem('onSendActive');
  } else {
    dialog && dialog.close();
    asyncResult.asyncContext.completed({ allowEvent: true });
  }
}, 1000);
```

In modals code:

```js

useEffect(() => {
  localStorage.setItem('onSendActive', 'true');
...
```

However, I don't have this code in my localhost dev env and can confirm it gets stuck forever.

## Context
Here's the code that invokes the dialog:

```js
// The add-in command functions need to be available in global scope
window.checkTemplateIsUsed = event => {
  Office.context.ui.displayDialogAsync(
    `${window.location.origin}/modals/onsend`,
    // window.location.origin so it works on both localhost and production
    {
      asyncContext: event,
      displayInIframe: true,
      height: 80,
      width: 70,
    },
    asyncResult => {
      const dialog = asyncResult.value;
      // Pass item body to dialog by localStorage
      Office.context.mailbox.item.body.getAsync(
        Office.CoercionType.Html,
        asyncResult => {
          localStorage.setItem(
            'paragraphs',
            JSON.stringify(getParagraphs(asyncResult.value))
          );
        }
      );

      dialog.addEventHandler(
        Office.EventType.DialogMessageReceived,
        () => {
          // Our logic is handled within the component,
          // on clicking either button, we send a "sussess" message,
          // nothing to do here but closing the dialog and allowing the item to be sent
          dialog.close();
          asyncResult.asyncContext.completed({ allowEvent: true });
        }
      );

      // If user closes the dialog with top-right X, prevent send
      dialog.addEventHandler(Office.EventType.DialogEventReceived, args => {
        asyncResult.asyncContext.completed({ allowEvent: false });
      });
    }
  );
};
```

Here's how it's hooked to on-send:

```xml
<ExtensionPoint xsi:type="Events">
  <Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="checkTemplateIsUsed" />
</ExtensionPoint>
```

App domains:

```xml
<AppDomains>
  <AppDomain>https://stage.stanintelligence.com</AppDomain>
  <AppDomain>https://localhost:3000</AppDomain>
</AppDomains>
```

Complete manifest:
https://stage.stanintelligence.com/manifest-alternatives/manifest-stage.xml

I've found that the times that dialog is shown, it is rendered in the DOM properly (note the search for `ms-modal` within the rendered DOM yields 4 results):

![Screenshot (6)](https://user-images.githubusercontent.com/1758649/99501678-16b1c580-294a-11eb-91e7-aa34e998a35c.png)

But the times it doesn't work, the dialog is not even rendered (only the "commands" page which executes `displayDialogAsync` is rendered, search for `ms-modal` yields only 2 results):

![Screenshot (5)](https://user-images.githubusercontent.com/1758649/99501699-1d403d00-294a-11eb-89bf-043f6c7344ed.png)

The only other correlation that I've found is that the taskpane (a different part of my add-in), although pinned, won't show either in the times that `displayDialogAsync` gets stuck.

## Your Environment

* Platform: Same behavior on localhost dev env (Windows) and production (Ubuntu 20.04) 
* Host: Outlook Web
* Browser: same behaviour on Edge and Chrome

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding displayDialogAsync. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
We are currently unable to reproduce this issue on our end. Are you still able to reproduce it?
