### ISSUE TITLE
Cannot get Delegates Folder Username/Folder owner name

### ISSUE THREAD

**Issue by Kronenberg** [OfficeDev/office-js#1513]
Good day, i am trying to get some information about shared folder information.

_User A_ delegates permissions to _user B_ account and now _user B_ see his inbox folder and subfolder. 
_User B_ is trying to use Office.context / Office.context.mailbox / Office.context.mailbox.item API, 
but do not see ant differences between his own mailbox and shared mailbox. He see his username and email under initial data and nothing about real owner of this folder which is _User A_ in this case. You can check screenshot below.

## Expected Behavior
User A should get some differences from between his own mailbox and shared user mailbox using  
Office.context / Office.context.mailbox / Office.context.mailbox.item. Because from now, user A do not see differences between user A and user B mailbox API.

## Current Behavior
User B is trying to get some data about user B shared folder using Offce.context and Office.mailbox but do not see any differences. From data perspective it looks the same and user B see his name and email under shared account folder. 

* Additional details:
1. Delegate permission of your folder to another outlook user
2. How this user should know that this folder is belongs to use from API perspective? 

## Context

My feature requires this specific data. 

Example: 
FE -> I want to show folder owner in my outlook-addin UI. 
BE -> I want to save usernames of every person who delegates me permissions of theirs folders
and i am assume its should be simple, because i see it in UI

## Your Environment
It's the same though all platform.

## Useful logs & Screenshots 
![Office-api-example](https://user-images.githubusercontent.com/13053374/99895561-851bbe00-2c91-11eb-8c48-a6503a7e900b.jpg)

**Comment by exextoc** [comment]
You should be able to use the shared properties to get information on whether or not the item is in a shared folder (as well as the owner) (getSharedPropertiesAsync)

https://docs.microsoft.com/en-us/javascript/api/outlook/office.sharedproperties?view=outlook-js-preview#owner

https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access
