### ISSUE TITLE
Placeholder text appears on clearing content control

### ISSUE THREAD

**Issue by ssoni2074** [OfficeDev/office-js#1515]
On clearing content control placeholder text **Click here to enter text** appears in content control even if I have custom placeholder text on browser.
*Setting placeholder text through word api on browser is not supported
pfa.
## Expected Behavior
Custom placeholder text should appear

## Current Behavior
default placeholder text **Click here to enter text** appears

## Steps to Reproduce
clear text inside content control placeholder text will appear 

## Context
I want to insert empty content control for some operation and then insert text inside it if needed ,but if content control is left empty it shows wrong text (i.e. placeholder text)

## Your Environment
Occurring definitely on browser on windows and mac ,seems to be solved on desktop.

[placeholder text issue.zip](https://github.com/OfficeDev/office-js/files/5581311/placeholder.text.issue.zip)

![image](https://user-images.githubusercontent.com/66596870/99933363-d9ea3200-2d80-11eb-9c28-b8e2f635542c.png)

**Comment by MandytMSFT** [comment]
@ssoni2074  thanks for reporting. BUG 4675869 is opened for internal track

**Comment by ElizabethSamuel-MSFT** [comment]
@MandytMSFT / @AlexJerabek Can you confirm if this is fixed now?

Thanks.

**Comment by AlexJerabek** [comment]
@ElizabethSamuel-MSFT I've updated the documentation to describe the Word on the web support: https://github.com/OfficeDev/office-js-docs-reference/pull/852. I'll close the issue, but please reopen if there's more to say on the matter.
