### ISSUE TITLE
issue with Word.InsertLocation.replace

### ISSUE THREAD

**Issue by ssoni2074** [OfficeDev/office-js#1516]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Word.InsertLocation.replace is behaving same as Word.InsertLocation.start.
I am tring to replace text inside content control with `contenControl.insertText('new text',Word.InsertLocation.replace)`
but as you can see in attached video it is behaving like `contenControl.insertText('new text',Word.InsertLocation.start)`
we are facing this issue from last 10-14 days.
Same behavior is seen on other team members

```

$("#run").click(() => tryCatch(run));

async function run() {
  await Word.run(async (context) => {
    let contentControls = context.document.body.contentControls;
    context.load(contentControls);

    await context.sync();

    contentControls.items.forEach(item => {
      item.insertText("new text", Word.InsertLocation.replace);
    })

    await context.sync();
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}

```

## Expected Behavior
It should replace text inside content control

## Current Behavior
Api is adding replace text to the start of text inside content control

## Steps to Reproduce, or Live Example
add some text in content control and use word api to replace text inside it 

## Context
It breaks functionality

## Your Environment
reproducible on all environments except desktop
[replace_issue.zip](https://github.com/OfficeDev/office-js/files/5581427/replace_issue.zip)

**Comment by MandytMSFT** [comment]
@ssoni2074 I tried on Word online, It works fine to me as shown video below. Can I know your word version?
![ezgif com-gif-maker](https://user-images.githubusercontent.com/52641972/101756743-4dc26380-3b11-11eb-970d-1d4d561b7f14.gif)

**Comment by ssoni2074** [comment]
@MandytMSFT please find attached picture.I would like to inform that all our team members are having same build number but some are facing this issue and some are not facing this issue ( our team members are in INDIA, AUSTRALIA, AMERICA mostly are facing this issue but some are not) 
![image](https://user-images.githubusercontent.com/66596870/102069042-3d68fc00-3e23-11eb-9470-a931d69cd496.png)

**Comment by MandytMSFT** [comment]
@ssoni2074 Thanks for the update. Could you share a sessionID which can repro the issue to me for further dialogistic?

**Comment by ssoni2074** [comment]
@MandytMSFT 36c5a5ba-35ff-4d16-b53c-bc5f94aee914

**Comment by ssoni2074** [comment]
Hi @MandytMSFT any update on this ?

**Comment by MandytMSFT** [comment]
@ssoni2074  Sorry for delay update here. 

Based on your previous info that not all people were facing this issue, I suspect it was related to some flight. But I applied all the flight in your given session manually, unfortunately I still can't repro.  I will keep looking and update here if i have new finding.

**Comment by ssoni2074** [comment]
@MandytMSFT can you use this session id a8291d3f-7604-4519-b67e-b957acab1820

**Comment by MandytMSFT** [comment]
@ssoni2074 Applying flights in session above still not repro the issue. But looking at the log behind, there are some errors related to bad paragraph. Is there any special thing in your word document? If possible, could you share your workbook to us for reproduce ?

**Comment by ssoni2074** [comment]
seems to be resolved!!!

**Comment by ssoni2074** [comment]
Hi, we are again facing this issue with ` item.insertText("new text", Word.InsertLocation.replace);` and ` item.insertHtml("new text", Word.InsertLocation.replace);`
session id c1ffebb7-ddac-4190-b0b6-f71f4db1a34f
build 16.0.13916.41002
