### ISSUE TITLE
How to know changes to office api

### ISSUE THREAD

**Issue by ssoni2074** [OfficeDev/office-js#1517]
How can I get noticed that certain part of API is added from beta to hosted API? or some new feature is added like recently resizing taskpane on browser was added but I don't think there is any post or something about this. 
Is there a blog or something which posts announcements ?

Also there is two hosted CDN with version 1 and1.1 what is the difference
https://appsforoffice.microsoft.com/lib/1/hosted/office.js
https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js

**Comment by massonj** [comment]
There are a few ways that you can keep up with changes happening in Office add-ins and APIs
1) We have a blog here where we discuss larger features and announcements - https://developer.microsoft.com/en-us/microsoft-365/blogs/technology/office-add-ins/
2) We also host a monthly community call where we share information on what the team is working on - https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins-community-call
3) https://appsforoffice.microsoft.com/lib/1/hosted/office.js is the correct path to reference office.js with (see https://docs.microsoft.com/en-us/office/dev/add-ins/develop/referencing-the-javascript-api-for-office-library-from-its-cdn)
Hope this helps
