### ISSUE TITLE
EventType.DialogMessageReceived not working in Word Online

### ISSUE THREAD

**Issue by chintan-avnio** [OfficeDev/office-js#1518]
## Expected Behavior

Dialog close after sign in

## Current Behavior

It was working till last week suddenly stoped working online word app though it continues to work with excel. I don't know why this is happening is the online word app has been updated? 
![image](https://user-images.githubusercontent.com/72140171/99975862-bc40bb00-2dc8-11eb-9394-96873829b7c0.png)

**Comment by TobiasWolters** [comment]
We have also seen this issue. The event handler for `Office.EventType.DialogMessageReceived` simply doesn't get triggered in Word Online.
Note that it works perfectly in all offline Office applications, and it works in PowerPoint Online and Excel Online.

This is quite critical and should be fixed ASAP.

**Comment by chintan-avnio** [comment]
@sumurthy  Can you please check this issue! Or you can tag a responsible person to check this. Thanks!

**Comment by lliu113** [comment]
@chintan-avnio thanks for reporting this! We tried reproing this on our end and we weren't successful - the dialog closed successfully. Would you be able to provide more detailed repro steps? If you have any code snippets/manifest you can share that would also be helpful. 

Thanks!

**Comment by chintan-avnio** [comment]
> @chintan-avnio thanks for reporting this! We tried reproing this on our end and we weren't successful - the dialog closed successfully. Would you be able to provide more detailed repro steps? If you have any code snippets/manifest you can share that would also be helpful.
> 
> Thanks!

Step1: Open Word Online.
Step2: Search for Grammerly Addin in store.
Step3: Sign in with your Account.
Step4: Check with Word Client and Word Online.
(Online word will not close Dialog after successful sign-in)

If still doesn't getting the issue! 

Please write in here will create a sample code for dialog close issue

**Comment by TobiasWolters** [comment]
> @chintan-avnio thanks for reporting this! We tried reproing this on our end and we weren't successful - the dialog closed successfully. Would you be able to provide more detailed repro steps? If you have any code snippets/manifest you can share that would also be helpful.
> 
> Thanks!

We also still experience the issue.

**Comment by chintan-avnio** [comment]
@TobiasNissen is this fixed in your app?

It started working for 2days!

**Comment by TobiasWolters** [comment]
> @TobiasNissen is this fixed in your app?
> 
> It started working for 2days!

Yes, it also works for me again. Feel free to close this issue.
