### ISSUE TITLE
SSO in Excel not working (Unsafe Javascript attempt and error 13007)

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#1519]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi,

I try to enable SSO in an Excel add-in. 
So I followed 'Create an ASP.NET Office Add-in that uses single sign-on' guidelines. But I keep getting an errormessage when I call 'OfficeRuntime.auth.getAccessToken':
![afbeelding](https://user-images.githubusercontent.com/46490607/99974973-ecc12e80-2da1-11eb-804f-e996c8c17c6b.png)

As far as I understand, this is because a login-page might be loaded within the taskpane. And because that is a restricted sandbox this message occurs.

So I tried the same thing in a dialog window. But calling 'OfficeRuntime.auth.getAccessToken' did not do anything at all:

  async function getAccessToken() {
    try {
      console.log("Starting");

      let bootstrapToken = await OfficeRuntime.auth.getAccessToken({
        allowSignInPrompt: true,
        allowConsentPrompt: true,
        forMSGraphAccess: true
      });

      console.log("Done");

      return bootstrapToken;
    }
    catch (exception) {
      console.log("error");
      console.log(JSON.stringify(exception));
    }
  }

this resulted in the console:
Starting
*and nothing more (no 'error', no 'Done'...)*

It would help tremendous to know what I do wrong or have to do to resolve this problemen!
Many thanks

Best regards
Lou Driehuis

## Expected Behavior
I would like to know how to make SSO work in Excel

## Steps to Reproduce, or Live Example
Follow: 'Office-Add-in-ASPNET-SSO' example!

## Context
Currently I'm not able to use SSO due to an error as mentioned above.
This code continues in the catch (exception.code = 13007):

    async function getDataWithToken() {
        try {

            // Get the bootstrap token and send it to the server to exchange
            // for an access token to Microsoft Graph and then get the data
            // from Microsoft Graph.

            let bootstrapToken = await OfficeRuntime.auth.getAccessToken({
                allowSignInPrompt: true,
                allowConsentPrompt: true,
                forMSGraphAccess: true
            });

            getData("/api/values", bootstrapToken);

        }
        catch (exception) {
            if (exception.code) {
                handleClientSideErrors(exception);
            }
            else {
                showResult(["EXCEPTION: " + JSON.stringify(exception)]);
            }
        }
    }

## Your Environment

* Platform Office on the web]
* Host Excel
* Office version number: 16.0.13517.35052
* Operating System: Windows 10
* Browser (if using Office on the web): Edge Version 87.0.664.41 (Official build) (64-bit)

**Comment by raflyalk** [comment]
Hi @ALDriehuis, I'm also having the same problem as you. I'm following the [Create a Node.js Office Add-in that uses single sign-on](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs) guidelines. Have you got any solutions to this problem?

**Comment by ghost** [comment]
unfortunately...I did not get it to work.
But I am using a workaround now: I don't get the access-token within the office-add-in. What I do currently:
* Present the user a login button
* when the button is pressed, I open a dialog (on the clientside) with displayDialogAsync with an API call to it's login method
* There I login to Azure with a return call the a API methode 'Authorize'
* This 'Authorize' methode returns a view 
* In this 'Authorize' view I use messageParent to sent the token back to the parent

Hope this helps a little.

I know that I anony the user with a second login, but I do not see another alternative. But an advantage of this solution is that I have full controle of the Azure login.

Lou

**Comment by vouyoung-alloy** [comment]
Aso having the same issue....  Seems like this was never solved after all this time

**Comment by glr0221** [comment]
This did not work for me either.
