### ISSUE TITLE
Can not reload header and footer in MS Word using officejs api in second time

### ISSUE THREAD

**Issue by ceyx-azureus** [OfficeDev/office-js#152]
I use this method to load templates for document:

``` javascript
public someGetMethod(templateId: string): ng.IPromise<any> {
return this.Service.getXml(templateId).then((myBodyXML: string) => {
    return Word.run((...args) => {
        const context = args[0];
        const body = context.document.body;
        body.insertOoxml(myBodyXML, Word.InsertLocation.replace);
        return context.sync();
    }).catch((error: Error) => {
        console.error("Error: " + JSON.stringify(error));
    });
});
}
```
It works fine the first time. The document body is filled with data, and the header and footer as well (body does not contain headers/footers if we take a look into documentation, but in xml from BE contains all document).

## Expected Behavior

So, I simply expect that `header.clear()` fully cleans header and let fill it with new data.

## Current Behavior

After load new template header and footer does not reload. So I use something like I tried below:

``` javascript
public loadSomeXML(templateId: string): ng.IPromise<any> {
return this.SomeService.getXml(templateId).then((myBodyXML: string) => {
    return Word.run((...args) => {
    const context = args[0];
    const sections = context.document.sections;
    context.load(sections, "body/style");

    return context.sync().then(() => {
        const header = sections.items[0].getHeader("primary");
        const footer = sections.items[0].getFooter("primary");
        header.clear();
        footer.clear();
        return context.sync().then(() => {
        const body = context.document.body;
        body.insertOoxml(myBodyXML, Word.InsertLocation.replace);
        return context.sync();
        });
    });
    }).catch((error: Error) => {
    console.error("Error: " + JSON.stringify(error));
    });
});
}
``` 
and they had cleaned visually but not at all. Next template can not fills them, only body was changed. _If I manually double clicked in header, then made combination ctrl+A -> delete, after it new template can fills them. So, as I understood, `header.clear()` can not actually clean by 100%.
Also I have created issue on [stackoverflow](https://stackoverflow.com/questions/50461348/how-to-reload-header-and-footer-in-ms-word-using-officejs-api).

## Context
It blocks development.

## Your Environment
I use [Office.js v1](https://appsforoffice.microsoft.com/lib/1/hosted/Office.js), and it is completely the same as [Office.js v1.1](https://appsforoffice.microsoft.com/lib/1.1/hosted/Office.js)
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2016
* Operating System: Windows 10 Enterprise x64
* Browser (if using Office Online): -

**Comment by JuaneloJuanelo** [comment]
@AntonMedviediev  can you please indicate more precisely what office version you are using?  Go to file->account and you will see the Version and build (something like Version 1806 Build xxxx.xxxx) thanks!

**Comment by ceyx-azureus** [comment]
Microsoft Word 2016 MSO (16.0.4639.1000) 32 bit

**Comment by JuaneloJuanelo** [comment]
please c[heck my answer in stack,](https://stackoverflow.com/questions/50461348/how-to-reload-header-and-footer-in-ms-word-using-officejs-api/50596622#50596622) I  think this is not a bug, but more like you need to try a different approach to solve your scenario.

**Comment by ceyx-azureus** [comment]
Thank you for answer one more time:).
I wrote to stackoverflow a couple of minutes ago.
I think I can attach xml example of the document from BE tomorrow, if it can helps.

**Comment by JuaneloJuanelo** [comment]
@AntonMedviediev  also can you please clarify what you mean by "BE"

**Comment by ceyx-azureus** [comment]
Sorry for so long delay, I mean back-end.

**Comment by JuaneloJuanelo** [comment]
if something needs to be added to the header it needs to be done using the header/footer body. body.insertOoXML do not replace existing headers. *by design*
