### ISSUE TITLE
mailbox.item.itemId on Android return id in different format

### ISSUE THREAD

**Issue by rosergeev** [OfficeDev/office-js#1520]
There is a difference in format in returned value of itemId of the mail item between Android and desktop(windows) platform 

## Expected Behavior
itemId of the same mail item should be the same

## Current Behavior
On desktop browser itemId property return value in following format:
AAMkADYyOWViNTEzLTNkMmItNDBiMC05NDcyLThmZTBiN2FjMjI2NQBGAAAAAADwmiZ0cOqgTb7+Fs7DzKlyBwC6KBvAkVoERJgOYFuMJLI7AAAAAAEMAAC6KBvAkVoERJgOYFuMJLI7AAENeLqQAAA=
And this value allow me to find mail item on backend via ews request.

But on Android device the format completely differs:
AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0AuigbwJFaBESYDmBbjCSyOwABDXw5lAAA
This value doesn't allow identify mail item on backend.

## Steps to Reproduce, or Live Example
https://github.com/rosergeev/GetItemId

## Your Environment
* Platform: Office on the web, Outook app on Android version 4.2044.3(42044817)
* Host: Outlook
* Office version number: O365
* Operating System: Windows 10, Version 1903 (OS Build 18362.592)
* Browser: Google Chrome Version 86.0.4240.198

This is how it looks  in browser:
![web](https://user-images.githubusercontent.com/12766193/100128278-245ad400-2e91-11eb-970d-486794126b1e.png)

And how on Android:
![Android_crop](https://user-images.githubusercontent.com/12766193/100128611-86b3d480-2e91-11eb-80ca-2be3c14dc6bd.jpg)

**Comment by exextoc** [comment]
This is expected.

1. itemId returned from Mobile is "REST-formatted ID". This is mentioned here in documentation: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api#get-the-item-id . We will improve our documentation so that this information is easily available to developers.

2. To convert this "REST Formatted ID" to "EwsId", you can use converToEwsId() API. Documentation: https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-1.5&preserve-view=true#convertToEwsId_itemId__restVersion_

**Comment by rosergeev** [comment]
I had already tried this approach, but ended up with the same result.

**Web Office:**
![web](https://user-images.githubusercontent.com/12766193/100317009-a1d72f00-2fcc-11eb-9c07-4351b217998f.png)

**Android:**
![photo_2020-11-26_09-46-30](https://user-images.githubusercontent.com/12766193/100317037-ae5b8780-2fcc-11eb-90fe-9c31b7745679.jpg)

![photo_2020-11-26_09-47-03](https://user-images.githubusercontent.com/12766193/100317043-b3203b80-2fcc-11eb-9b86-03bf02ee115a.jpg)

The only difference I can see is conversion method just escapes '-', but really doesn't convert anything

**Comment by rosergeev** [comment]
https://github.com/OfficeDev/office-js/blob/9f2b5db05d97c5060af3b43dd9b915da86728ccf/dist/outlook-15.04.debug.js#L520-L526

**Comment by rosergeev** [comment]
@exextoc, your suggestion to use convertToEwsId is not suitable for Android due to API restrictions:
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/add-mobile-support#unsupported-apis

**Comment by rosergeev** [comment]
@exextoc , have you had a chance to take a look?

**Comment by exextoc** [comment]
Hey @rosergeev ,

On Outlook Mobile the ID returned is an immutable ID instead of EWS ID. Please use the following to handle this case 

Possible solutions that can be implemented at add-ins side
Option1: Use REST API instead of EWS as immutable ID is accepted by REST APIs.
Option 2: Use the following REST API to convert the immutable id to EWS ID,

REST API : https://docs.microsoft.com/en-us/graph/api/user-translateexchangeids?view=graph-rest-beta
Sample API request format

POST https://graph.microsoft.com/beta/me/translateExchangeIds
Content-Type: application/json
Input:
```
{
  "inputIds" : [
    "{rest-formatted-id-1}"
  ],
 "sourceIdType": "restImmutableEntryId",
  "targetIdType": "ewsId"
}
```

**Comment by rosergeev** [comment]
Hey, @exextoc,
Thank you for your reply. 

### Option 1:
 It's not suitable for our project(it's not a jedi way) due to we would replicate backend code that work with ews ids on client side.

### Option 2; I stuck with this approach. 

- My first try:

![invalid_parameter](https://user-images.githubusercontent.com/12766193/103295379-d93e5e80-4a04-11eb-8193-ff6ef67f3818.png)

I think this is a documentation issue and maybe we can say hello json.net and bye newtonsoft.json as well due to the only way to get to know what's wrong was to request with an empty json object:

![missing_params](https://user-images.githubusercontent.com/12766193/103295513-31756080-4a05-11eb-9bd8-aa25bdceb303.png)

But [here in example](https://docs.microsoft.com/en-us/graph/api/user-translateexchangeids?view=graph-rest-beta&tabs=http#example) and in your excerpt all parameters begin with lower case.
- My second try:
I capitalized parameter names and got this:

![access_denied](https://user-images.githubusercontent.com/12766193/103296090-659d5100-4a06-11eb-83b9-7b27dd49f7f8.png)

- Then I thought that maybe endpoint is incorrect and try this one:

![access_denied_v2 0](https://user-images.githubusercontent.com/12766193/103296151-8bc2f100-4a06-11eb-8a15-05578a754591.png)

as with /v2.0/ I was able successfully to get message using the following url:
`var getMessageUrl = restUrl + '/v2.0/me/messages/' + itemId;` 

After that I tried to use url that you provided in your answer:
[](https://graph.microsoft.com/beta/me/translateExchangeIds)

![invalid_token](https://user-images.githubusercontent.com/12766193/103296408-173c8200-4a07-11eb-987e-dd73c1ad3179.png)
Graph API answered me that token is invalid. 
So now I get lost and don't understand what's wrong with my token that I got with help of [getCallbackTokenAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-preview&preserve-view=true#getCallbackTokenAsync_options__callback_) or maybe I'm using wrong endpoint to ask for translating ids.
[Here](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api) it's written that it should be enough to have callbackToken to make REST calls. It's not clear why I'm getting access denied in this case.

**Comment by rosergeev** [comment]
Moreover, I changed permissions in manifest file from ReadWriteItem to ReadWriteMailbox, but this didn't help as well

**Comment by exextoc** [comment]
The add-in callback token doesn't have enough permission scope to use the translateExchangeIds API. translateExchangeIds requires User.Read.All, User.ReadWrite.All permission but the add-in token only has Mail.ReadWrite permission.Right now the only option is to use a REST API on Android.

**Comment by rosergeev** [comment]
So I ended up with requesting entryId via Graph API and then converting it to ews format at back end. In any case, @exextoc thank you for your support!
