### ISSUE TITLE
Outlook Error Code 5010 is not documented

### ISSUE THREAD

**Issue by masem1899** [OfficeDev/office-js#1522]
When using Office.context.mailbox.item.removeAttachmentAsync the following error occurs, but isn't documented:
code: 5010
name: Interner Fehler
message: Ein interner Fehler ist aufgetreten.

Documentation Link:
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/javascript-api-for-office-error-codes

**Comment by ElizabethSamuel-MSFT** [comment]
Reclosing

**Comment by JuaneloJuanelo** [comment]
@sempre76  Hello! hey we have a  hypothesis that this is due to the length  of the attachment ID, is it possible that you can confirm that?  would be really useful to make sure if our fix will help you.
