### ISSUE TITLE
Not able to detect the difference between the deleted content control and remaining normal content control having text when the Track changes are ON using OfficeJS API in Word add-in.

### ISSUE THREAD

**Issue by c-suraj** [OfficeDev/office-js#1524]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Description: 
As per the requirement of our application, we are tagging/adding the same text/paragraph multiple times on the document using word add-in tagging functionality. When we tag/add the text/paragraph has the content controls applied and to do this we use the insertContentControl() API of the OfficeJS.  Now when we turn ON the track changes and do the lock tracking with the All Markup option selected and then we remove the tagged/added text/paragraph that time the text/paragraph gets strikeout with the content control but in the add-in, we are not able to detect the difference between the deleted content control and the remaining normal content control having text/paragraph when the Track changes are ON.

Expectation:
We need a mechanism to differentiate between the deleted content control and the remaining normal content control having text/paragraph when the Track changes are ON using OfficeJS API’s.

**Comment by MandytMSFT** [comment]
@c-suraj  thanks for reaching us. Unfortunately, currently we have no way to detect this. We track Office Add-in feature requests on our [UserVoice page](https://officespdev.uservoice.com/) Please add your request there. Feature requests on user-voice are considered when we go through our planning process.

**Comment by c-suraj** [comment]
Thanks for the reply @MandytMSFT .

I already raise feature request on UserVoice page. Below is the UserVoice link for this issue:
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/42053035-not-able-to-detect-the-difference-between-the-dele
