### ISSUE TITLE
window.open from add-in in Windows Outlook using WebView1 returns null window

### ISSUE THREAD

**Issue by westconference** [OfficeDev/office-js#1525]
Calling window.open from an add-in on versions of Windows Outlook that use WebView1 (old Edge, specifically Office for 365 16.0.13328.20350) is seen to return null rather than a reference to the newly opened window. The new window is opened however no reference is returned to it. Further the new window will have window.opener set to undefined and its window.parent will refer to itself, effectively meaning it is not possible to communicate between the two windows.

This does not happen if window.open is invoked from JavaScript console of a browser. Just seeing it occur from within the add-in JavaScript context in this WebView1 Windows Outlook. Does not occur on Outlook Mac, in OWA or on Outlook using WebView2.

e.g.
```
var openedWindow = window.open('/samplePage', '_blank');
```
* openedWindow will be null rather than a reference to the window that was opened.

I've checked for various pop-up settings etc that might be blocking this but haven't got any to work. Tried putting all involved sites into Trusted Sites or Internet Sites with Protected mode On or Off but no difference.

## Expected Behavior
window.open should return reference to window that was created when called from inside the add-in.

## Current Behavior
window.open returns null when called from inside the add-in on Outlookfor 365 using WebView1.

## Steps to Reproduce, or Live Example
- Create a simple ExecuteFunction add-in that on launch opens a window using window.open.
- Add-in should store the result of window.open so it can then be examined.
-- Examine either using a script debugger to attach to the code at this point or write a message to the Outlook status bar indicating if window.open result was null or not.

## Context
I want to be able to open a window that i can post messages to from my add-in to give a Windows Outlook desktop user some detailed information about what the UI-less add-in is doing. The approach was to open a window and then pass text to it using postMessage on the returned window reference from opening it which works on some instances of Outlook e.g. WebView2, Outlook for Mac, but is not working with WebView1.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop Windows Outlook
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.13328.20350 (64-bit) Outlook for 365
* Operating System: Windows

**Comment by westconference** [comment]
Further odd behaviour is that after the window is opened if I then try to use the displayDialogAsync method of office-js back on the caller I'm seeing an odd (looks like an overflow error code) Internal Error returned in the displayDialogAsync result.

```
{
"status":"failed",
"error":{
  "name":"Internal Error",
  "message":"An internal error has occurred.",
  "code": -2147467259
}
}
```

**Comment by exextoc** [comment]
window.open will behave differently due to the underlying engine. (https://github.com/OfficeDev/office-js/issues/1468) 

either openBrowserWindow (if the window should be opened in the default browser), or displayDialogAsync (for two way communication) should be used. 

DisplayDialogAsync can only be called from the original taskpane or uiless add-in.

**Comment by westconference** [comment]
@exextoc  'openBrowserWindow' doesn't return the opened window so I wouldn't be able to send data to it from the parent - [spec](https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=powerpoint-js-preview#openBrowserWindow_url_).

'displayDialogAsync' only supports two way communication with requirement set 1.9 right (via messageParent and messageChild)? That limits its usage to O365 OWA and latest Windows Outlook for O365 desktop client but since that's the only client this is occurring on that might work. I'll give it a try thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@westconference I'll close this issue now. However, if you still have questions about this, let us know so we can reopen this issue, or you can create a new one.

Thanks.

**Comment by mmcalynnproof** [comment]
Finally got around to trying this. Neither suggestion works for my case but might for others so documenting here.

As I thought openBrowserWindow opens a window with no ability to receive messages from the original opener so is not suitable here.

'displayDialogAsync' and 'messageChild' does actually open a new window that can receive messages from the parent. However it also means no other dialogs can be opened (error is thrown on trying to do so) which is not useful for my add-in as I was opening a window to display log messages and then having the add-in use a dialog for user interaction.

**Comment by westconference** [comment]
Finally got around to trying this. Neither suggestion works for my case but might for others so documenting here.

As I thought openBrowserWindow opens a window with no ability to receive messages from the original opener so is not suitable here.

'displayDialogAsync' and 'messageChild' does actually open a new window that can receive messages from the parent. However it also means no other dialogs can be opened (error is thrown on trying to do so) which is not useful for my add-in as I was opening a window to display log messages and then having the add-in use a dialog for user interaction.

**Comment by exextoc** [comment]
Thanks for documenting this here.
If we can be of further assistance, don't hesitate to open a new issue.
