### ISSUE TITLE
Dynamics 365 App for Outlook - appears in OWA but not Desktop for a single user

### ISSUE THREAD

**Issue by GPetrites** [OfficeDev/office-js#1526]
Dynamics App for Outlook has been deployed to users.  Most users can see the Dynamics ribbon/menu options in both Outlook Web App and Outlook Desktop client.  We have one user who is able to see and interact Dynamics in Outlook Web Access, but NOT in Outlook Desktop.

We've verified that the app manifest is getting downloaded to the user's machine by looking under:
 
%localappdata%\Microsoft\Office\16.0\Wef

We've tried deleting this folder and restarting Outlook.  The newly recreated folder contains the Dynamics app manifest.

In Outlook Desktop, we've looked for signs of the add-in getting loaded by opening up "Customize the ribbon" and looking at "All Commands". On desktops which have the add-in loading successfully, we see a command "Dynamics 365".  For the user encountering the issue, we do NOT see "Dynamics 365" under All Commands.

The user is running Outlook build 13328.20356, the same as other users not encountering the problem.

**Comment by exextoc** [comment]
Has the user turned off connected experiences in Outlook?

 https://developer.microsoft.com/en-us/microsoft-365/blogs/outlook-add-ins-and-optional-connected-experiences/

Do other Add-ins work for the user? Can the user open the Add-in Store?

**Comment by GPetrites** [comment]
Perfect!  The user had connected services disabled for some reason.  Enabling it immediately resolved the issue.

Thanks for the quick response. (The three days was over a holiday weekend so it was actually much quicker than it may appear...or that I expected.)

**Comment by ronnyholtmaat** [comment]
Hi,

The 'Optional Connected Experiences' is mentioned in the (Dutch Government) DPIA (following the GDPR requirements) on Office 365 E3, Teams, OneDrive, SharePoint & AzureAD from 16 February 2022. 

Please see: https://www.rijksoverheid.nl/documenten/publicaties/2022/02/21/public-dpia-teams-onedrive-sharepoint-and-azure-ad

Direct link to DPIA PDF: https://open.overheid.nl/documenten/ronl-06f045ed745d9540ec4262a6079e8e73ad262a43/pdf

Disabling the 'Optional Connected Experiences' is advised in DPIA. This to mitigate privacy risk from 'high' to 'low'. 
'Optional Connected Experiences' uses the (general?) Privacy statements https://privacy.microsoft.com/nl-NL/privacystatement
Microsoft acts as a data controller / (gegevensbeheerder) on data from 'Optional Connected Experiences' (in stead of processor/verwerker)

Q1 Does anyone know how we can implement the "Dynamics 365 App for Outlook" while also beeing complaint to GDPR (or the Dutch implementation of this, AVG/UAVG)

Q2 Anything in the Pipeline/Backlog on this? There are other apps in the AppSource App store that can function without the 'Optional Connected Experiences', right? 

https://appsource.microsoft.com/en-us/product/dynamics-365/mscrm.fa50aa98-e8bb-4757-83ce-6d607959b985?tab=overview

Would love to hear.
