### ISSUE TITLE
Outlook always resets the cursor position after handling a drag&drop email attachment.

### ISSUE THREAD

**Issue by blesliecan** [OfficeDev/office-js#1528]
We have an Outlook Add-in that can handle attachments by uploading them to a secure storage location and inserting a Url into the body of the email that can be used to access the file.

Our problem is that when the user adds attachments using drag and drop the cursor is being reset so that it is just before the inserted Url rather than after it.
## Expected Behavior

I expect that the insert cursor will be where I placed it just after the inserted Url as shown in this screen shot taken after an attachment was added with the "Attach File" button:

![After-button-attachment](https://user-images.githubusercontent.com/22990021/100686626-8ef98d00-3333-11eb-90f5-f96a32a90529.PNG)

## Current Behavior

The cursor is being reset so that it is just before the inserted Url rather than after it as shown in this screen shot taken after an attachment was added by dragging it into the email:
![After-DragAndDrop-attachment](https://user-images.githubusercontent.com/22990021/100686828-f8799b80-3333-11eb-9a16-0982a1a4c383.PNG)

## Steps to Reproduce, or Live Example

Here is the code to create a simple Add-in to reproduce this problem:
[ThisAddIn.zip](https://github.com/OfficeDev/office-js/files/5619794/ThisAddIn.zip)

## Context

This results in frustrated users because they always have to manually reposition the text insert location after dragging an attachment into their email.

## Your Environment

* Platform :PC desktop
* Host : Outlook Version 2010 (Build 13228.20408)
* Operating System: win10

**Comment by exextoc** [comment]
We are able to repro a similar issue with regular text in the body of a message without using the add-in. @blesliecan when dragging and dropping an image / text file into the email, there appears to be a drag cursor which indicates the location of the cursor after the image/text is attached. Screenshot below to clarify this. Is that what you are experiencing?

![image](https://user-images.githubusercontent.com/28549921/101225218-bd35e000-3645-11eb-88b8-bf7a2e645127.png)

**Comment by blesliecan** [comment]
It may be related but the problem is that the add-in is unable to set the cursor position to the end of the inserted link

**Comment by exextoc** [comment]
I missed the link to your add-in zip file. It appears you are building a [VSTO add-in for Outlook](https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-creating-your-first-vsto-add-in-for-outlook?view=vs-2019), instead of a [web add-in for Outlook](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-add-ins-overview). Ignore my previous comment then. I will pass this issue onto the Outlook Desktop product team.

**Comment by blesliecan** [comment]
What is the next step here? Should I have reported this bug somewhere else?

Will I get feedback here from the Outlook Desktop product team or is there a tracking number or something that I can use to keep track of this?

**Comment by exextoc** [comment]
We have forwarded this bug along to the Outlook Desktop product team. It is being tracked with bug id 4715226.

The guidance for reporting feedback to the Outlook Desktop product team is to use the Help->Contact Support, Help->Feedback, or Help->Suggest a Feature buttons in the Outlook ribbon as appropriate to your situation. Issues entered through these avenues will contain logging information and be sent to the Outlook Desktop product team.

You can also use [Outlook User Voice for Windows Desktop Outlook](https://outlook.uservoice.com/forums/322590-outlook-2016-for-windows) to post feature suggestions for Outlook desktop.

**Comment by blesliecan** [comment]
Is there anyway I can see what the status of bug id 4715226 is?
