### ISSUE TITLE
insertooxml does not work on document with page number from word desktop.

### ISSUE THREAD

**Issue by ekowpo** [OfficeDev/office-js#1529]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Word desktop page number is within a content control. but not the same for word online. When a document has page number added from word desktop. word online removes the page number leaving behind the an empty content control even if you use the remove page number button. This content control can not be deleted. 

Also if you try to update the ooxml its would not allow you. with error name: "RichApi.Error", code: "NotAllowed".

## Expected Behavior
Should update since nothing has changes. Page number on word online updates

## Current Behavior
Fails to update the document although we are updating with the same ooxml.

## Steps to Reproduce, or Live Example

1. - Create a document in word desktop. 
2. - Add a page number,
3. - upload the document to office365.
4. - Get the ooxml from the document.
5. - Update the document with the same ooxml

.
https://gist.github.com/ekowpo/f27110afb810f8b081c6c8f6072b8d91

![image](https://user-images.githubusercontent.com/15113067/100765275-51dddb00-33c5-11eb-8263-1bf8e7721703.png)

## Context
I require compatibility with word desktop and word online. bookmarks are not present on online word.
As a result open xml manipulation is the only way to go. Currently this is blocking that.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______Office on the web
* Host [Excel, Word, PowerPoint, etc.]: ______Word_
* Browser (if using Office on the web): ______Chrome

## Useful logs

- [ERROR]: Error:
{
    "stack": "RichApi.Error: The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information.\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:26:300393)\n    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:26:361435)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:26:359540",
    "message": "The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information.",
    "name": "RichApi.Error",
    "code": "NotAllowed",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "NotAllowed",
        "message": "The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information.",
        "errorLocation": "Body.insertOoxml",
        "statement": "var insertOoxml = v.insertOoxml(...);",
        "surroundingStatements": [
            "var v = context.root._getObjectByReferenceId(\"{92808cfb-fdc6-45a6-b448-3760e087e2a3}{235}\");",
            "// >>>>>",
            "var insertOoxml = v.insertOoxml(...);",
            "// <<<<<",
            "// Instantiate {insertOoxml}"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}

**Comment by MandytMSFT** [comment]
@ekowpo Unfortunately, the content control wrapped with page number is not supported by word online, the API call just returned with correct error. 

Ypu can submit your request to word online by clicking [Give Feedback to Microsoft]->[I have a suggestion] shown in screenshot below 

![image](https://user-images.githubusercontent.com/52641972/101325094-27e55680-38a6-11eb-8f3b-2e6346b338ef.png)

**Comment by ekowpo** [comment]
Thanks, @MandytMSFT. Could you send me the link to the suggestion. Also, the problem transcends beyond page numbers to custom headers, document properties in the header/footer.

**Comment by MandytMSFT** [comment]
@ekowpo  you can find the link by opening any of your word document in browser :)
