### ISSUE TITLE
Functionality to disable UI controls

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js#153]
Looks like functionality is missing to disable/enable UI controls. For example disable a "Spam" button when you are already in the Junk folder.

**Comment by JuaneloJuanelo** [comment]
this is a known issue and currently in our backlog. No ETAs. There is an active uservoice request, please upvote it!
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/6509264-client-side-ribbon-manipulation
