### ISSUE TITLE
Edge DevTools Preview Crashes on connect

### ISSUE THREAD

**Issue by roebuk** [OfficeDev/office-js#1530]
Everytime edge devtools preview connects to my outlook add-in it crashes within a second of opening if the JavaScript code contains a syntax error.

## Expected Behavior
The devtools should connect and remain open to inspect the error.

## Current Behavior
Everytime edge devtools preview connects to my outlook add-in it crashes within a second of opening.

## Steps to Reproduce, or Live Example
* Additional details:
  1. Open DevTools Preview
  2. Connect to running App with a JS syntax error
  3. Instantly closes.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop 
* Host [Excel, Word, PowerPoint, etc.]: Outlook Add-in
* Office version number: 16.0.13328.20408
* Operating System: Windows 10
* Browser (if using Office on the web): N/A

## Useful logs

```
Faulting application name: wwahost.exe, version: 10.0.19041.488, time stamp: 0x64bdb2d5
Faulting module name: WebRuntime.Diagnostics.dll, version: 1.0.0.0, time stamp: 0x5dcdeec1
Exception code: 0xc0000420
Fault offset: 0x0000000000022fcc
Faulting process ID: 0x40ac
Faulting application start time: 0x01d6c804af69c8c3
Faulting application path: C:\Windows\system32\wwahost.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.MicrosoftEdgeDevToolsPreview_19.1118.2.0_x64__8wekyb3d8bbwe\WebRuntime.Diagnostics.dll
Report ID: 260a2353-17e7-49f1-b436-593231981103
Faulting package full name: Microsoft.MicrosoftEdgeDevToolsPreview_19.1118.2.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

**Comment by exextoc** [comment]
What is your Office/Outlook version number?

**Comment by roebuk** [comment]
The Outlook version number is 16.0.13328.20408 and it's the 64 Bit version. I've also updated the original post with the version number.

**Comment by roebuk** [comment]
I believe the devtools may also be instantly closing even when an error isn't present.

**Comment by exextoc** [comment]
We are unable to reproduce this issue in-house. What is your Windows version number? And also, what type of JavaScript syntax error do you have in your add-in? Can you share a code snippet? We tried with some gibberish text in our JavaScript file and we could not reproduce this issue.
