### ISSUE TITLE
Office.context.ui.displayDialogAsync popup window size can be fixed by px

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1531]
When using Office.context.ui.displayDialogAsync to create a popup window, the size is fixed by percentage. But this will cause a problem as add-in is defined a cross platform application, it will running at different size screen device. As a result it will looks bad on some device. 
Can we provide a switch trigger on this api so that developer can fix window size by px?

**Comment by Rick-Kirkham** [comment]
The old Office Helpers repo had a technique for adding more flexibility to the dialog size. Maybe you could copy some of that code: [office-js-helpers dialog.ts](https://github.com/OfficeDev/office-js-helpers/blob/a54a6d70ea9295d4a1d8f9c4372758175b1a552c/src/helpers/dialog.ts)

**Comment by SWei1234** [comment]
Hi @Rick-Kirkham 
Thank you so much. 
I have simulate this way set height/width to (screen height/width) x 50% .
