### ISSUE TITLE
Page.getRestApiId() returns empty string not the id.

### ISSUE THREAD

**Issue by ulonsjo** [OfficeDev/office-js#1532]
Page.getRestApiId() always returns empty string.

## Expected Behavior
Return of Id used by Microsoft Graph

## Current Behavior
Always returns empty string, instead of the id.

## Steps to Reproduce, or Live Example

From the oneline documentation https://docs.microsoft.com/en-us/javascript/api/onenote/onenote.page?view=onenote-js-1.1#getRestApiId__,
OneNote.run(function(ctx){
    // Get the current page.        
    var page = ctx.application.getActivePage();
    var restApiId = page.getRestApiId();

    return ctx.sync().
        then(function(){
            console.log("The REST API ID is " + restApiId.value);
            // Note that the REST API ID isn't all you need to interact with the OneNote REST API.
            // This is only required for SharePoint notebooks. baseUrl will be null for OneDrive notebooks.
            // For SharePoint notebooks, the notebook baseUrl should be used to talk to the OneNote REST API
            // according to the OneNote Development Blog.
            // https://blogs.msdn.microsoft.com/onenotedev/2015/06/11/and-sharepoint-makes-three/
        });
});

## Context

I am unable to build the solution I want as it requires the Microsoft Graph Id to do anything. The Onenote file is stored on Onedrive personal..

## Your Environment

Onenote online with a new Visual Studio office add-in template and copied the sample from the documentation.

**Comment by lindalu-MSFT** [comment]
@ElizabethSamuel-MSFT , have we sorted out who the OneNote SME is? This should be assigned to someone to get the attention it deserves. Thanks, lindalu

**Comment by ElizabethSamuel-MSFT** [comment]
@lindalu-MSFT As far as I know, the SMEs are known but we don't have any GitHub IDs for them. I've emailed them about the issue but I may need to follow up once folks are back from the holiday break.

**Comment by lindalu-MSFT** [comment]
@ulonsjo Sorry this has taken us so long to track down someone to help with this issue. Have you resolved the issue yourself or should I leave this issue open? Maybe we can find someone on the graph side to help.

**Comment by ElizabethSamuel-MSFT** [comment]
Followed up with product team. Hope to have a response soon.

**Comment by ulonsjo** [comment]
Great that this issue gets some attention.

**Comment by ElizabethSamuel-MSFT** [comment]
OneNote bug ID 4632802. @ulonsjo I can't transfer this issue to the [OneNoteApi repo](https://github.com/OneNoteDev/OneNoteApi). If you want, you can create an issue there and link to this one.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@ulonsjo Thanks for doing so. Please track updates there and we'll go ahead and close this issue.

Thanks.
