### ISSUE TITLE
Outlook Clients Do Not Follow Manifest Locale-based values.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#1534]
Outlook clients, unlike OWA, does not display the right locale-based text values.

## Expected Behavior

Outlook clients must display the right locale-based text.

## Current Behavior

The current behavior is that Outlook clients do not display the locale-based text.
Instead it displays the default value.

## Steps to Reproduce, or Live Example

1. Download and install the evernote addin. This evernote addin has a [French ("fr") value](https://imgur.com/a/2LG6aNB) for the tool tip text.
2. Once downloaded, hover over the addin name on your addin list and see the French tooltip text. Like in [this image](https://imgur.com/a/qdK85qP).
3. Now open your Outlook client and set the default language to French. 
4. Once the client is in French, hover over the Evernote Addin Button. 
5. The tooltip text for the addin displays the "default" value and not the French value. This bug is shown [here](https://imgur.com/a/jITkR5t).

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2011 (More details [here](https://imgur.com/a/6AbuJnG).) 
* Operating System: Windows 10
* Browser (if using Office on the web): _____

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by glr0221** [comment]
@ElizabethSamuel-MSFT Thank you for understanding that I had to tag you on this one. But I hope this ticket gets some attention too. Thank you again.

**Comment by ElizabethSamuel-MSFT** [comment]
@glr0221 Sure, no problem. Assigning to the team to take a look.

Thanks.

**Comment by exextoc** [comment]
According to our documentation, the string overrides must specify the locale using the BCP 47 language tag format. So for French (from France), it should be **"fr-fr"**, not "fr". So that's most-likely why the override strings are not being displayed for EverNote. Here's a link to our documentation : https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/override

If you try another add-in, such as [Translator for Outlook](https://appsource.microsoft.com/en-us/product/office/WA104380627?tab=Reviews), the override strings are respected because the locale is specified in the correct format.

**Comment by glr0221** [comment]
@exextoc @ElizabethSamuel-MSFT  Thank you both for always taking time to answer my questions. I understand and will take a look at the manifest once I get to my MS machine later. The only other thing though, is that this behavior is not the same as the javascript addins. Would it be possible for the outlook-client team to take a look into the possibility of making the experience the same as the browser? Thank you and I hope that makes sense.

**Comment by exextoc** [comment]
[Localization for Office add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/localization#control-localization-from-the-manifest) has a more complete description of the localization guidance and limitations:

> If you need to localize for more than one area within a language family, such as de-de and de-at, we recommend that you use separate Override elements for each area. Using just the language name alone, in this case, de, is not supported across all combinations of Office client applications and platforms.

If you would like to suggest more consistent support, this would impact more clients than just Outlook. Please consider leaving some feedback on [UserVoice here](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?category_id=169836). Thanks!

**Comment by glr0221** [comment]
@exextoc @ElizabethSamuel-MSFT 

Sorry for the late response. I have been very busy these past few days. Thank you for the very clear response @exextoc. I am now following the BCP-47 syntax for the locale-codes. I based it on the Translator for Outlook manifest.

As for the request on consistent support, yes I will file this in the user voice later.

Thank you always for all your support and prompt responses. You have been very helpful to us. Thank you.
