### ISSUE TITLE
Charts related functions issues on iPad (in particular, markerStyle)

### ISSUE THREAD

**Issue by alexuaua** [OfficeDev/office-js#1538]
I've issues with some charts related API methods on iPad (markers and axes related).
In this report I have included code on one of them, but I'm not sure if this a good idea to create an issue for each of them (please let me know). This is an API related issue, because Excel on iPad supports rendering different markers.

## Expected Behavior
Change marker style for line series, similarly to Excel for Mac, Windows and online version. Attached screenshot shows result of code execution on Excel for Mac.

On iPad Excel 2.43 (20110606) Office.context.requirements.isSetSupported('ExcelApi','1.7) returns true (as well as it supports API 1.9) and thus markerStyle should be available for chart series. 

https://docs.microsoft.com/en-us/javascript/api/excel/excel.chartseries?view=excel-js-1.7#markerStyle
<img width="768" alt="Screen Shot 2020-12-07 at 03 22 03" src="https://user-images.githubusercontent.com/8337308/101299597-bdc6a600-3800-11eb-983c-5addfc6f2af5.png">

## Current Behavior
Setting markerStyle for lines or scatter lines causes an exception on iPad.

## Steps to Reproduce, or Live Example

This code executed on iPad crashes with "This operation is not permitted for the current object" error.
https://gist.github.com/alexuaua/2bc1ab472595eea3bb5f8def0f964fc3

## Context
Cannot change series markers (where applicable - lines, scatter lines).
 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: iOS (iPad)
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2.43 (20110606)
* Operating System: iOS 14.2 or 14.0

## Useful logs

`
{"name":"RichApi.Error","code":"InvalidOperation","traceMessages":[],"innerError":null,"debugInfo":{"code":"InvalidOperation","message":"This   operation is not permitted for the current   object.","errorLocation":"ChartSeries.markerStyle","statement":"itemAt.markerStyle   = ...;","surroundingStatements":["...","var   worksheet = worksheets.getItem(...) /* originally getActiveWorksheet()   */;","var charts = worksheet.charts;","var chart =   charts.getItem(...) /* originally getItemAt(...) */;","var series =   chart.series;","var itemAt = series.getItemAt(...);","//   >>>>>","itemAt.markerStyle = ...;","//   <<<<<"],"fullStatements":["var workbook =   context.workbook;","var worksheets =   workbook.worksheets;","var worksheet =   worksheets.getItem(\"{B24E8244-6101-944A-BCF2-EA4B2CFFDD8F}\") /*   originally getActiveWorksheet() */;","var charts =   worksheet.charts;","var chart =   charts.getItem(\"{F9DB7979-68FB-C245-BFA2-8D172C63B4D1}\") /*   originally getItemAt(0) */;","var series =   chart.series;","var itemAt =   series.getItemAt(0);","itemAt.markerStyle =   \"Plus\";"]},"httpStatusCode":400}
`

--

**Comment by MandytMSFT** [comment]
@alexuaua Thanks for reporting. We can repro the issue and Bug 4708364 is created for internal track. We unfortunately have no timelines to share at this point.

**Comment by alexuaua** [comment]
@MandytMSFT Thank you. Could you please advise me if I should open another issue: when I use markers/line formatting related API for charts (marker size/line style) with latest Excel on iPad _and_ more than one chart, only the first chart is displayed and no exception goes to catch{}. I can prepare a demo script based on my code, just wanted if it is ok to report as another issue.

**Comment by MandytMSFT** [comment]
@alexuaua It's better to share a gist to me first to understand your operation before I can give you a confirmed answer :). You also can try the same API calls on other platforms like excel desktop/Excel Online, if they are behaved differently from iOS, then you can report to us. Ideally, API behavior is consistent among different platforms.

**Comment by MiaofeiWang** [comment]
Hi @alexuaua This issue has been fixed after version 2.46.21020800. Could you please update your Office and try again?

**Comment by alexuaua** [comment]
@MiaofeiWang  Yes, thank you for letting me know. There are still other issues with axes, but this issue is resolved with v2.46. Thanks!
