### ISSUE TITLE
Visio: the viewer breaks periodically on loading

### ISSUE THREAD

**Issue by nbelyh** [OfficeDev/office-js#1539]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When you embed Visio drawing into a page (a simple built-in example is File Viewer stock SharePoint web part), loading file can stop unexpectedly, and part of the diagram is not loaded. Especially the case with multi-page diagrams.  Also this affects Visio API quite heavily (API actions are not executed because script execution stops earlier because of the error).

The error does not happen all the time, but periodically. See the logs below for the reason.

## Expected Behavior

There is no error on loading the page viewer.
The javascript cleanup code mentioned executes successfully and the widget always load the diagram, no error in the console.

## Current Behavior

The widget stops loading diagram more or less randomly, especailly in case of Visio API usage.

## Steps to Reproduce, or Live Example

Add a "File Viewer" web part. Select Visio diagram into that part (the more complex the more probability to get the error) because it can be loaded in multiple load operations. Open the browse console and observe. Make sure cache is disabled (in DEV tools). Try switching pages or refreshing the pag, this error should pop up.

## Context

I am using Visio API to display Visio diagrams in SharePoint pages (this is not required to reproduce, but just shows the problem immediately)

### Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: SharePoint
* Host [Excel, Word, PowerPoint, etc.]: SharePoint Online
* Office version number: -
* Operating System: -
* Browser (if using Office on the web): Chrome 82

## Useful logs (**visio.boot.js**)

The reason seems to be:
https://c1-visio-15.cdn.office.net/v/s/App_Scripts/visio.boot.js

![image](https://user-images.githubusercontent.com/528366/101396925-49f1cf80-38cc-11eb-9c1b-d83f5531008c.png)

The place where the error happens (please notice how "this" is used):

```js
i.prototype.hideAndRemoveBootContainer = function() {
  this.Ws.style.display = "none", /// <<<<<<< here it throws exception and stops , because "this." is window!!
  this.ws = !1
}
,
i.prototype.switchToWopiApp = function(i) {
  var t = this;
  .......
  this.As && this.As.showApplicationFrame(),
  window.setTimeout(this.hideAndRemoveBootContainer, 0)), // << should not pass functions like this
````

**Comment by mattgeim** [comment]
@prateek9us can you take a look at this please?

**Comment by prateek9us** [comment]
@nbelyh can you please share a screenshot or an error that you see?

**Comment by nbelyh** [comment]
@prateek9us @mattlind 

Some screenshots (the error varies):

freezes forever:
![image](https://user-images.githubusercontent.com/528366/102328645-9c478600-3f87-11eb-9385-b22ac2462623.png)

or gives this:
![image](https://user-images.githubusercontent.com/528366/102328275-23e0c500-3f87-11eb-8f90-29554186ed68.png)

Please check the JavaScript file above - the error looks pretty much straightforward I guess... Incorrectly passing function that makes use of "this" stops script execution at random time, and leads to the rest of the errors. Example of this error:
```js
X.prototype.foo = function() {
}

X.prototype.baz = function() {
  this.foo()   // <<<<< "this.foo is not a function"
}

X.prototype.bar = function() {
  window.setTimeout(this.baz, 0);   // <<< the problem
}

var x = new X()
x.bar();
```

In JavaScript, you have to use something like "bind" to handle "this" properly:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind

Means, the fixed code for this example could probably be:
```js
X.prototype.bar = function() {
  var b = this.baz.bind(this);
  window.setTimeout(b, 0);   // <<< fixed
}
```
And In this particular case:
```js
window.setTimeout(this.hideAndRemoveBootContainer.bind(this), 0)
```
Changing it like that should fix the issue.

**Comment by lindalu-MSFT** [comment]
@prateek9us Is there an update on this? Are you the Visio PM? We have a couple other Visio issues in this repo that haven't had any recent activity.

**Comment by nbelyh** [comment]
From my side, the issue seems to be still there.

**Comment by nbelyh** [comment]
The issue still exists after 2 years

**Comment by lindalu-MSFT** [comment]
@prateek9us @ElizabethSamuel-MSFT Hi, do we know who the Visio PM is who can help? @nbelyh We currently don't have a lot of engineering resources for Visio, but like you pointed out, this perhaps is a not-so-hard fix?
