### ISSUE TITLE
Mouse hover on any of text or button is not working on Custom Excel Add-in

### ISSUE THREAD

**Issue by rupesh-malpani-rfh** [OfficeDev/office-js#154]
I have created one fabric component and converted into excel add in. My UI is properly visible on browser with hover effect. Same UI is also properly visible on Excel add in also except the hover thing. 
In Simple words hovering on component is not working, i have to hover it on another place in view port to see the hover effect. The behavior is very strange. Also i have to click on button to see the color change (it should work on hover and not on click). I am attaching few snap shot. Please find those. I hope you will get my concern.

Please help me out here.

**Comment by JuaneloJuanelo** [comment]
@rupesh-malpani-rfh  we need way more detail to try to help you.  please fill up all the template and add as much info as possible and if you can provide a sample snippet with script lab will or your manifest so we can repro your issue will be valuable. For now i am closing this issue until details are added.
thansk!

**Comment by rupesh-malpani-rfh** [comment]
In my manifest file, I have just added my localhost path, so that I  can see my web page inside Excel 2016 as an Office add-in. To convert it into office add in, I am using `office.js`.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Created:ce44715c-8c4e-446b-879c-ea9ebe0f09c8-->
<OfficeApp
          xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
          xsi:type="ContentApp">

  <!-- Begin Basic Settings: Add-in metadata, used for all versions of Office unless override provided. -->

  <!-- IMPORTANT! Id must be unique for your add-in, if you reuse this manifest ensure that you change this id to a new GUID. -->
  <Id>Some dummy ID here for add in</Id>

  <!--Version. Updates from the store only get triggered if there is a version change. -->
  <Version>1.0.0.0</Version>
  <ProviderName>[Provider name]</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <!-- The display name of your add-in. Used on the store and various places of the Office UI such as the add-ins dialog. -->
  <DisplayName DefaultValue="ExcelWebAddIn1" />
  <Description DefaultValue="ExcelWebAddIn1"/>
  <!-- Icon for your add-in. Used on installation screens and the add-ins dialog. -->
  <IconUrl DefaultValue="~remoteAppUrl/Images/Button32x32.png" />

  <SupportUrl DefaultValue="http://www.contoso.com" />
  <!-- Domains that will be allowed when navigating. For example, if you use ShowTaskpane and then have an href link, navigation will only be allowed if the domain is on this list. -->
  <AppDomains>
    <AppDomain>AppDomain1</AppDomain>
    <AppDomain>AppDomain2</AppDomain>
    <AppDomain>AppDomain3</AppDomain>
  </AppDomains>
  <!--End Basic Settings. -->

  <Hosts>
    <Host Name="Workbook" />
  </Hosts>
  <DefaultSettings>
    <SourceLocation DefaultValue="localhost path" />
    <RequestedWidth>852</RequestedWidth>
    <RequestedHeight>541</RequestedHeight>
  </DefaultSettings>

  <Permissions>ReadWriteDocument</Permissions>

</OfficeApp>
```

Now I have created a web page (localhost path) with one simple button(`type="button"`). I want to change the background-color of the button when I mouse hover over it. I added the CSS and its working fine on the browser. When I run the same page in Excel 2016, the hover effect is not working. It is a simple HTML/CSS file and nothing great in that. Just to make it as office add-in we are using `office.js`.

Steps:-

Attached is a web page with Edit Diagram as a button on the top right corner. 
When I mouse hover over it, background-color is not changing. I have to click on this button to see the changed BG color. Please find attached snapshot of the web page that runs in the browser and that runs in Excel as an add in. Simply Office add-ins are not able to recognize the hover thing in my case.

Because of some limitation, I won't be able to send my code. Sorry for that.
