### ISSUE TITLE
Excel Woorksheet.onSingleClick is not reliable

### ISSUE THREAD

**Issue by hunef39** [OfficeDev/office-js#1540]
## Expected Behavior
I would expect the onSingleClick event to be fired consistently when I click on a single cell.
_Further more, I would expect the event to be fired when the mouse click is pressed and released in the same cell (no multi-select)_
## Current Behavior
When the mouse button is pressed on a single cell, even the slightest movement of the pointer within the cell boundaries will prevent the onSingleClick event to be fired. **A slight movement of the mouse pointer between pressing and releasing the mouse button is a fairly common scenario especially when the user is making quick movements or using a touch device like the laptop pad.**

## Steps to Reproduce, or Live Example
In this small snippet you can reproduce the scenario I described above. You will see that if you move the pointer between pressing and releasing while staying within the same cell (no multi-select), no event is logged in the console.
[https://gist.github.com/hunef39/0b5f93a36465f523f90c97bcad1eb802](url)

## Context
Our app relies heavily on worksheet events to allow the user to interact directly with the worksheet. And the user experience is severely impacted when an action (clicking) doesn't get the expected reaction (event callback)

## Your Environment
Tested on:
Desktop Excel Windows 10
Office online in Mozilla Firefox and Google Chrome.

**Comment by MandytMSFT** [comment]
@hunef39 thanks for reaching us. Currently it's a by-design behavior that single click is not triggered if you moved mouse pointer before releasing. Our API relied on OS to decide if it's a left click event. 

We track Office Add-in feature requests on our [UserVoice page](https://officespdev.uservoice.com/) Please add your request there. Feature requests on user-voice are considered when we go through our planning process.
