### ISSUE TITLE
setSelectedDataAsync with Html coercion does not work on Outlook on Big Sur

### ISSUE THREAD

**Issue by fusiled** [OfficeDev/office-js#1541]
Trying to add text or HTML to a mail body with `Office.context.mailbox.item.body.setSelectedDataAsync` function does not work reporting that a generic internal error occurred in Outlook for Mac on Big Sur after a non-deterministic number of insertions.

## Expected Behavior
The content should be inserted in the body without any issue.

## Current Behavior
Calling `setSelectedDataAsync` multiple times with Html coercion rises an internal error after a non-determistic number of calls of such a function. After this event happens, the next calls of `setSelectedDataAsync` results into the generic internal error too. The content is not inserted in the body.

## Steps to Reproduce, or Live Example

1. Clone `https://github.com/fusiled/outlook-addin-setselecteddatasync-test-bug`
2. Install the dependencies with npm: `npm install`
3. Run the dev server: `npm run dev-server`
4. Import the local manifest of the add-in
5. Compose a new message on outlook
6. Sideload the installed addin (more specifically `Contoso Taks Pane Add-in -> Show Taskpane`)
7. Click the `Run` button at the bottom of the sidepane multiple times until the text is not added anymore to the body
8. At some point, the content is not going to be added anymore to the body 

## Context
Just adding Html content to the mail body. Also adding text with Html coercion generates the same issue. The following snippet causes the issue:

```
const variabile = renderToStaticMarkup(<span>123456</span>);
Office.context.mailbox.item.body.setSelectedDataAsync(variabile,
        {coercionType: Office.CoercionType.Html},
        (asyncResult) => {
            if (asyncResult.status == Office.AsyncResultStatus.Failed) {
                console.log("Error during insertion", asyncResult.error.message);
            }}
);
```

## Your Environment

- Outlook on Mac Version 16.45 (20120702)
- MacOS Big Sur Version 11.0.1

Tested on two different MacBooks.

## Useful logs
Not anything special. Just run an example on Mac Big Sur and the issue should happen.

**Comment by fusiled** [comment]
Related to [this](https://github.com/OfficeDev/office-js/issues/1499#issuecomment-735510209)?

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding setSelectedDataAsync(). It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
1. We tried to reproduce this with latest Outlook Mac build and we were not able to repro this now. Can you please check if this problem is still reproducible for you with latest build?
2. If it is reproducible, please share your Outlook Mac build number.
