### ISSUE TITLE
setStartupBehavior(Office.StartupBehavior.load) results in the ADD-IN ERROR when opening saved workbook

### ISSUE THREAD

**Issue by leybal** [OfficeDev/office-js#1542]
Hello. We launched the [excel-shared-runtime-scenario](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario) add-in locally. Then made sideload of this add-in in google chrome and clicked the Load on doc open button on ribbon. After that we saved a copy of the document to the computer. An ADD-IN ERROR message occurred when we opening the workbook. Please take a look at [video](https://drive.google.com/file/d/1SR173wUgBie4cEPnCgv9PGnHUi3jhIjb/view?usp=sharing).
Then we pressed the No load behavior button. Saved a copy of the document to our computer again. No error message occurred after opening the workbook. Video is [here](https://drive.google.com/file/d/1eNAV_kTNbOT-Kk-CeF3DMEDT1kUmyHYG/view?usp=sharing).
It looks like Office.addin.setStartupBehavior(Office.StartupBehavior.load) is causing this error to appear.

## Expected Behavior
Office.addin.setStartupBehavior(Office.StartupBehavior.load) will not result in to the ADD-IN ERROR appear when opening the workbook.

## Current Behavior
The ADD-IN ERROR appear when we opening the workbook with Office.addin.setStartupBehavior(Office.StartupBehavior.load).

## Steps to Reproduce, or Live Example

1. Download [excel-shared-runtime-scenario](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario) add-in and run it locally. Make sideload in google chrome.
2. Press "Load on doc open" button
3. Save a Copy of the workbook on PC.
4. Open saved workbook in excel for windows.
5. The ADD-IN ERROR should appear.

## Context
We trying to run scripts after opening a workbook, but we get an error.

## Your Environment
* Platform: PC desktop
* Host: Excel
* Office version number: Version 2011 (Build 13426.20308)
* Operating System: Windows 10 Pro (Same behavior on MAC)
* Browser : Google Chrome 87.0.4280.88

**Comment by jeremy-msft** [comment]
Hi @leybal, we weren't able to reproduce this issue.  Could you please try running the steps again and sharing the session ID with us?  You can find the Session ID under File -> About.

**Comment by leybal** [comment]
Thanks for the answer.
Here is the session ID for case when we have the add-in error: 14e9536e-2038-4bc4-914d-c85a266b831b. Also please take a look at [video](https://drive.google.com/file/d/1hpFqkKgp_czKzTHIngSUz3N5V76cN1CF/view?usp=sharing).
In this case we set Office.addin.setStartupBehavior(Office.StartupBehavior.load).

The session ID when here is no error: b6d69612-cce2-4796-ba4d-1ee362ecb861. [Link](https://drive.google.com/file/d/1Aw87UfsCe8FuVu1-RbDQgB40DFMwD5o_/view?usp=sharing) to video.
We set Office.addin.setStartupBehavior(Office.StartupBehavior.none);

**Comment by davidchesnut** [comment]
Hi @leybal,

Just a quick update: I submitted a [PR to the sample](https://github.com/OfficeDev/PnP-OfficeAddins/pull/106) which fixes the RichApi.Error you were seeing logged to the debug console. That was a bug in the sample unrelated to the add-in error, but good to fix.

I also reproduced the problem by following your video (which was super helpful!). Now that we can repro the add-in error, the team is looking into the cause.

Thanks,
David

**Comment by leybal** [comment]
Hi @danielgwilson,
Are there any updates regarding this issue?

**Comment by davidchesnut** [comment]
Hi @leybal,

Okay, so I have some updates from the team here. Currently setStartupBehavior is not configured to support startup when the add-in is sideloaded during development. When going from web to desktop like in your video, it will fail to work. However, it will work if the add-in is deployed to the store, or through central deployment. So when deployed this won't be an issue. This is just a behavior you see during development and sideloading.

Hope this helps. Please let us know if there are any other issues with this scenario.

Thanks!
David

**Comment by leybal** [comment]
@davidchesnut thanks for the answer.
I have additional questions. It looks like setStartupBehavior does not give us the ability to do autorun the add-in. The following steps need to be taken:
1. a user have to interact with the add-in,
2. we set Office.StartupBehavior.load,
3. this setting will be saved in the workbook,
4.  and only when the workbook is reopened, the add-in will run automatically.

Do the same steps need to be taken when a user works with add-in from the store? How does Excel save the StartupBehavior configuration to the workbook (there is a binding to the add-in id)?
How can we run our add-in automatically when a user creating a new workbook?

**Comment by lindalu-MSFT** [comment]
Related to https://github.com/OfficeDev/office-js/issues/1567.

**Comment by davidchesnut** [comment]
Hi @leybal,

Yes the same steps would be taken with the add-in from the store. 

You can view the settings by exploring the XML when you save the file. For example, if you save a file named test.xlsx, change the file extension to test.zip. Then you can use File Explorer to browse into the XML sections of the document. The settings are saved in the **webextensions** folder of the XML. If you save a file a file with the setup behavior set to load, you will see an entry similar to the following in the webextension1.xml file.

```xml
<we:backgroundApp state="1" runtimeId="ContosoAddin.Url"/>
```

You can use the [Open XML SDK](https://docs.microsoft.com/office/open-xml/open-xml-sdk) to modify the XML. You can also do interesting things such as [automatically show the task pane](https://docs.microsoft.com/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document). 

Hope this helps,
David

**Comment by ilex-sgangwani** [comment]
This is a two year old issue but hasn't been fixed yet. Still seeing add-in error when we have setStartupBehavior set to Office.StartupBehavior.load to support calculating formulas when user opens the workbook. But then the developers cant debug issues on sheets from the users as they keep getting the error mentioned in this thread. How do we get this fixed, without having to change XML for each file we have to debug?
