### ISSUE TITLE
ADD-IN ERROR Sorry, we had to restart because this add-in wasn't responding.

### ISSUE THREAD

**Issue by sarala-bhalerao** [OfficeDev/office-js#1543]
## Current Behavior
After add-in load in word some time it shows Add-in error 

* Additional details:
  1. Office.initialize() is added in setInterval() because we are loading same angular application in C# add-in 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Microsoft 365 MSO (16.013426.20330)
* Operating System: Windows 10

The console/dev tools shows no error logged at all and then the add-in proceeds to restart and run just fine. Is there any reason why add-ins fail to load on occasion without specific errors

## Useful logs
- [ ] Screenshots
![add-in err (2)](https://user-images.githubusercontent.com/71916499/101630455-e50fb400-3a48-11eb-9490-2403dd1356be.png)

**Comment by LouMM** [comment]
@mattgeim This looks like an API issue. Is the customer using our templates? Can  @shaofengzhu or someone take a look?

**Comment by sarala-bhalerao** [comment]
Thank you for your feedback!
