### ISSUE TITLE
Iframe Dialog box height and width implementation is broken 

### ISSUE THREAD

**Issue by Khivar** [OfficeDev/office-js#1544]
When opening a Dialog box with Office.context.ui.displayDialogAsync and displayInIframe set to true in the options object, the implementation of the height and width options parameters (which are defined as a % of the page) is broken. 

## Expected Behavior
The Dialog box itself should be the size defined by the width / height parameters.

## Current Behavior
In Outlook Web, the Dialog box is implemented as a modal with a title bar including a close button in position absolute and then below there are nested divs which contain a div wrapping the iframe (containing the url passed to the Dialog). The height and width provided in the options object are applied to this wrapping div as vh and vw. So if you set height and width to 100 for example, the wrapping div will have this style :
 
`style="height: 100vh; width: 100vw; overflow: hidden;"`

I guess you can see what's wrong here. It is not the Dialog modal itself that has 100vw and 100vh but just a part inside the modal. So the wrapping div has 100vw but the wrapping div itself is inside another div with a padding right / left / bottom of 24px (or 16px in mobile) so you guessed it, it overflows and there is an horizontal scrollbar. Same thing with the height, the title bar height + 100vh of the wrapping div + 24px padding bottom, so the wrapping div overflows vertically and there is a vertical scrollbar, and that's not even taking into account the fact that the modal itself is not taking the full height for some unknown reason.

Moreover the CSS for mobile is even more broken, between 320 and 480px the whole Dialog modal width is set to a fixed width of 288px, why ? In mobile mode the natural thing to do would be for the Dialog modal to take the whole screen, not reducing its size.

## Steps to Reproduce, or Live Example
1. Office.context.ui.displayDialogAsync('https://myDomain/myDialog.html', {height: 100, width: 100, displayInIframe: true});

## Your Environment
* Browser : All

## Useful logs
Height and width set to 100 :
![Dialog-top](https://user-images.githubusercontent.com/31745738/101762413-b68fe880-3add-11eb-9e26-ffc96cc32b15.png)

Scrolled down to show the horizontal scrollbar :
![Dialog-bottom](https://user-images.githubusercontent.com/31745738/101762426-ba236f80-3add-11eb-8461-6e2a0b93aa51.png)

Mobile :
![Dialog-mobile](https://user-images.githubusercontent.com/31745738/101762435-bd1e6000-3add-11eb-9ce9-eff2dd9f1917.png)

**Comment by exextoc** [comment]
Hello, we are unable to reproduce this issue.  Can you share the manifest of the addin which you're trying this from?

**Comment by nicolasmendonca** [comment]
Hi Team! I wanted to re-open this ticket since I'm also experiencing the same issue in Iframe mode.
Here's the style rule that is taking up the entire screen. Disabling it produces the desired result, and it begins to use the given parameters for width and height:


![Screenshot 2022-09-27 at 09 59 51](https://user-images.githubusercontent.com/22284473/192533556-6d2dc2bb-27a2-4e52-aef3-8a9df536d003.png)
