### ISSUE TITLE
A problem occurred while trying to access this add-in.

### ISSUE THREAD

**Issue by alaeMellon** [OfficeDev/office-js#1549]
Hello,

since I installed the Microsoft Edge DevTools (Preview) last night I can't access my add-in in Outlook. I get the following error message: "A problem occurred while trying to access this add-in.".

However, it works fine in Outlook Web. And also on my old laptop the add-in still works.

Does anyone else have any ideas perhaps? (On my old laptop it works fine in Outlook. I have already uninstalled and reinstalled Outlook).

Many greetings , Ines

**Comment by exextoc** [comment]
What is your build and version of Outlook?

Does the add-in load when Edge DevTools is closed or uninstalled? Do you have a screenshot of the error?
