### ISSUE TITLE
[Outlook] Installing add-in thru URL fails but works fine when I use the downloaded xml

### ISSUE THREAD

**Issue by bx-anil** [OfficeDev/office-js#1550]
When I use the option to install the add-in via the url it throws an error. But when I down the manifest.xml  and tried to install it works fine.
The add-in for Outlook and not part of the store. It is a managed/centrally deployed add-in. 

manifest url: https://<domain>/manfiest or https://<domain>/manfiest.xml

Exception when using the URL:
{"anonUID":"","BillingRegion":"US","Browser":"Chrome87","CID":"","HexPUID":"","SourceClient":"WAC_Outlook","OfficeVersion":"16.2130.0.9999","ContentCulture":"en-US","CorrelationID":"c61657ed-c7d0-4de6-b730-b9a042610e0a","Domain":"store.office.com","GateHashes":"282052946,1039894021,86226609","GeographicRegion":"US","OperatingSystem":"WindowsNT10Dot0","ReferralUrl":"","ServiceScope":"OutlookStoreService","StateScope":"OutlookStore","UICulture":"en-US","UserAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36","User_HashID":"2_holX5056EbkwZqVy6xc6SqULAnrUlIyzKSTh8g65bkI=","VerboseEnabled":"False","OmexSession":"7d09f819-8f9d-4ea8-87c4-51c3e5642415","NecessaryServiceDataEventTypes":["ONREADY","ONCLICK","INCLIENTADDINSTATECHANGE","PERFORMANCE","TIMEMETRIC"],"PageUrl":"https://store.office.com/gyro/client?client=WAC_Outlook&cv=16.2130.0.9999&ui=en-US&rs=en-US&timestamp=1607977266370&ep=ma&exchver=15.20.3654.25&privateenabled=true&cb=x&ClientSessionId=8e1bbbb3-ac69-ec2f-db10-26ac456ea7b7&userPuid=0&gates=Marketplace.Outlook.Pin.Addin.Options,Marketplace.Outlook.Pin.Addin.Calendar.Options#/?Category=MyAddIns&OrderBy=None%20Desc","BTS":"2020-12-14T20:36:57.577Z","EventType":"Error message from Exchange service An internal server error occurred. The operation failed., No such host is known"}

The manifest validation seems to be fine:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/52792802/102134140-25de4300-3e24-11eb-8e58-72499e3ca8e4.png)

**Comment by exextoc** [comment]
Hi bx-anil, Can you please share the exact command used, it would help us in debugging this further? Looks like Exchange is not able to reach the host passed.

**Comment by bx-anil** [comment]
Yes the add-in host is unreachable from the Exchange server

**Comment by jfoclpf** [comment]
> Yes the add-in host is unreachable from the Exchange server

How to make it reachable? I have the same issue. I can't upload manifest.xml via URL

**Comment by mihitha** [comment]
Same thing happened to me and found the issue was that the server which hosted manifest file only supports TLS 1.3. I managed to enable TLS 1.2 in the server and the problem went away. Hope this will help someone.
