### ISSUE TITLE
Microsoft Publish Failure for Outlook Addin

### ISSUE THREAD

**Issue by neso613** [OfficeDev/office-js#1551]
Hi
I have developed an Outlook for Windows Add-in using Office.js. 
The add-in has functionality ​to assist users in scheduling and  starting a meeting in Microsoft Outlook quickly. Add-in has settings UI so that user can save its room/pin/username for meeting. There is a custom tab which opens new appointment window with pre-populated text.
I have submitted it on Microsoft Store for publish. But It fails on Microsoft Validation. They has reported the reason of failure:
**"Your offer demostrate insufficient interaction with our service in Message Read mode. Please consider adding functionality which either reads information from or writes information to the Office Client."**

Please help me to understand and solve this issue. Looking forward for response in this regard. Thanks!

**Comment by exextoc** [comment]
Can you please tell the process which you've followed to publish the addin? Also can you please share the manifest of the same?

**Comment by kanaksony** [comment]
Hey @exextoc We have published the app via Microsoft  Partner Center - Appsource Dashboard. And this is the [URL](https://mop.infocus.net:3000/infocus-conx-outlook-addin.xml) for Manifest.

![image](https://user-images.githubusercontent.com/6097596/103169091-e1f53000-485e-11eb-9adb-438dc2bee30c.png)
Edit: Attaching screenshot of error.

**Comment by neso613** [comment]
looking forward for solution.

**Comment by exextoc** [comment]
Hi @nehasoni3 @kanaksony ,  please open a Customer Support ticket here for marketplace publisher support:

https://aka.ms/marketplacepublishersupport
Browse topics Category: Commercial Marketplace
Topic: Certification issue
Next step: Office Add-in
