### ISSUE TITLE
Error message spills out of its container

### ISSUE THREAD

**Issue by roebuk** [OfficeDev/office-js#1552]
When adding an invalid XML file the text spills out of the container.

![image](https://user-images.githubusercontent.com/474377/102205302-eadf1c80-3ec2-11eb-891e-81b7669e1534.png)

It's also difficult to read, perhaps some better formatting of the error message wouldn't go a miss.

**Comment by lindalu-MSFT** [comment]
@roebuk Hi, can you please let us know which Office client you are working in (assuming Outlook??) and your configuration? Please refer to the issues template for the fields we need to triage your issue. Thanks in advance!

**Comment by roebuk** [comment]
1. Create an manifest.xml file that's invalid
  2. Attempt to add the add-in
  3. The error message appears as it does in the screenshot above.

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2011 Build 13426.20332
* Operating System: Windows 10
* Browser (if using Office on the web): N/A

**Comment by lindalu-MSFT** [comment]
Thanks! I'll reassign to the Outlook engineers. We're a bit backlogged due to the holidays but you should hear back soon.

**Comment by exextoc** [comment]
Internal Tracking: 4775568

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding the error UX. It has been put on our backlog. We unfortunately have no timelines to share at this point.
Internal tracking id: Office # 4763022

**Comment by Oleg-O** [comment]
This appears to have been fixed and verified around June 2022.
