### ISSUE TITLE
range.numberFormat does not work properly in German Regional Setting

### ISSUE THREAD

**Issue by GeorgeHung** [OfficeDev/office-js#1553]
After setting Mac's regional setting to Germany, range.numberFormat does not apply the number format correctly

## Expected Behavior
The number format passed to range.numberFormat api should be applied.

## Current Behavior
After setting Mac's regional setting to German, range.numberFormat does not apply the number format correctly

## Steps to Reproduce, or Live Example
1.  In Mac, go to System Preferences->Language & Region, and change Region to Germany.
2. Restart Mac.
3. Open Excel, and then load ScriptLab.
4. Import sample at https://gist.github.com/GeorgeHung/9d2fbc0458d3657d161f42ba0d155548 to ScriptLab
5. Open the Run Panel in Script Lab
6. Click on "Add Sample Data"
7.  Click on "Set Number Format"
8. Check the number format on cell D3, it is "###,##000".  However, in the sample code, the number format passed to range.numberFormat is "###.##0,00"

* Link to live example: https://gist.github.com/GeorgeHung/9d2fbc0458d3657d161f42ba0d155548

## Context
We try to use numberFormat to change cells' number format.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.45(20121303)
* Operating System: Big Sur
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by MandytMSFT** [comment]
@GeorgeHung  Thanks for reaching us. I think the difference is the decimal separator given Germany is using different decimal separator as other locale like en-us. I can get the same display on Windows by changing region to Germany. Application.useSystemSeparators return true in this case. 

Could you try this workaround to see if it works for you ? Setting workbook don't use system separator by **File->Options->Advanced-> Uncheck “Use system separators”**. 

Unfortunately we didn't have API to change this setting till now.

**Comment by GeorgeHung** [comment]
Mandy

Thanks for your response.  However, I am using Mac, and I couldn’t find Options under the File in Office for Mac.

Regards,
George

**Comment by MandytMSFT** [comment]
@GeorgeHung My fault, i thought the settings on Mac is similar as Win32. Then how about changing the system separator on Mac by: **System Preferences ->Language and Region->Advanced**. Change the Group separator from full stop (.) to a comma (,) and Decimal separator from a comma (,) to a full stop (.) as screenshot below. 

![MicrosoftTeams-image](https://user-images.githubusercontent.com/52641972/102572648-9e484b00-4127-11eb-98c2-305ca50a5e86.png)

**Comment by 4tti** [comment]
@MandytMSFT this is not solution of the issue nor viable workaround, we cannot ask every single user to change their preferences. The issue is that the range.numberFormat should be locale neutral, i.e. developer should always pass the format in language neutral format and it should then format the cell correctly using appropriate group/decimal separators, e.g. if I pass '###,##0.00' it should format number 12345.67 as "12,345.67" in US and "12 345,67" in German settings.

**Comment by GeorgeHung** [comment]
Mandy

If I apply the number format manually, it actually works without changing the settings.  You can try by right click on the cells and to go Format Cells->Number Tab->Select Custom from category.  After you apply custom format "###.##0,00", the number is formatted as expected.

Regards,
George

**Comment by MandytMSFT** [comment]
@GeorgeHung @4tti Maybe I have some misunderstanding on the issue before. To clarify, You want C3 show as 7,50 instead of 7,5000, correct ?  Then I think range.numberformatLocal is the right API, could you have a try ? and let me know if the issue is not resolved

**Comment by GeorgeHung** [comment]
Switch from numberFormat to numberFormatLocal does fix the issue.  However, for Excel online, the problem still exist with numberFormatLocal.
