### ISSUE TITLE
Office.context.document.getTaskByIndexAsync work?

### ISSUE THREAD

**Issue by puentesdiaz** [OfficeDev/office-js#1554]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi i am try use **Office.context.document.getTaskByIndexAsync** in my code, i'm develop a ADDIN for Project Desktop
i know how many rows or task i have inm y Project File
So i want get an array with GUIDs of all TASKs

i have this code: (ie. i want get the TASK with index **3**

Office.context.document.getTaskByIndexAsync(3,   
&nbsp;&nbsp;function (resultTask) { 
&nbsp;&nbsp;&nbsp;&nbsp;if (resultTask.status === Office.AsyncResultStatus.Succeeded) { 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this.setState({ idDocuMongo: resultTask.value }); 
&nbsp;&nbsp;&nbsp;&nbsp;} else { 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;this.setState({ idDocuMongo: resultTask.error }); 
&nbsp;&nbsp;&nbsp;&nbsp;} 
&nbsp;&nbsp;} 
);

but i don't get anything, ie. it apper that dont get inside into **getTaskByIndexAsync** function, at all

#office-js #addins #project

**Comment by nnyegaard** [comment]
@puentesdiaz I have gotten the number of tasks and then iterated through. 

A small example:

```
async function ButtonClick() {
    const numberOfTasks = await GetMaxTaskIndex();

    for (let index = 0; index < numberOfTasks; index++) {
     const taskId = await GetTaskIdByIndex(index);
     const taskInfo = await GetTaskInfo(taskId, Office.ProjectTaskFields.Name);
    }
}

  function GetMaxTaskIndex(): Promise<number> {
    return new Promise((resolve, reject) => {
      Office.context.document.getMaxTaskIndexAsync((data) => {
        if (data.status === Office.AsyncResultStatus.Failed) reject(data.error);
        resolve(data.value);
      });
    });
  }

  function GetTaskIdByIndex(index: number): Promise<string> {
    return new Promise((resolve, reject) => {
      Office.context.document.getTaskByIndexAsync(index, (data) => {
        if (data.status === Office.AsyncResultStatus.Failed) reject(data.error);
        resolve(data.value);
      });
    });
  }

  function GetTaskInfo(taskId: string, fieldName: Office.ProjectTaskFields): Promise<any> {
    return new Promise((resolve, reject) => {
      Office.context.document.getTaskFieldAsync(taskId, fieldName, (data) => {
        if (data.status === Office.AsyncResultStatus.Failed) return reject(data.error);
        resolve(data.value);
      });
    });
  }
```

I also turned the callback functions into promises so I could use async/await
