### ISSUE TITLE
[Word] Unable to delete text in content control (on word online)

### ISSUE THREAD

**Issue by ssoni2074** [OfficeDev/office-js#1555]
Sometimes in some content control (not all ) I can add text but deletion is not allowed .
For more clarity on problem ,procedure and properties of content control please look at video attached .
Video shows onscreen keyboard and keystrokes .
You can also see properties of content control in chrome debug panel/section on right .

## Expected Behavior
Insertion and deletion of text should be allowed

## Current Behavior
I am able to add some new characters inside content control but unable to delete text/characters.

## Steps to Reproduce, or Live Example
Please find attached video

## Context
It blocks from editing document.

## Your Environment
Word online 

## Useful logs

[content control.zip](https://github.com/OfficeDev/office-js/files/5709773/content.control.zip)

**Comment by MandytMSFT** [comment]
@ssoni2074 Thanks for reaching us. I can't repro on my side. Could you share your sample doc to us ? and what's your build version of word online ?

**Comment by ssoni2074** [comment]
@MandytMSFT **session id** 36c5a5ba-35ff-4d16-b53c-bc5f94aee914
**build version** 16.0.13610.41006

there are multiple content controls in this file you can try adding and deleting data from these content control .This issue is reproducible on web only .
[Entire Agreement.docx](https://github.com/OfficeDev/office-js/files/5722817/Entire.Agreement.docx)

**Comment by MandytMSFT** [comment]
@ssoni2074  thanks for the quick reply. We can repro and our team is working on the investigation.

**Comment by MandytMSFT** [comment]
@ssoni2074  The fix for this issue has been reached on word online. Could you help confirm if it's resolve from your sides. I tried on 16.0.13713.41009, looks good to me.

**Comment by AbidRahman-MSFT** [comment]
Closing the issue for now, please re-open if the issue still persists.
