### ISSUE TITLE
[Outlook] Custom property disappeared after serval minutes on delegate calendar

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1557]
Custom property disappeared after serval minutes on delegate calendar.
1. delegate permission is full calendar, Tasks are both Editor
2. This problem only happened on Mac Outlook (16.44  20121301)

## Expected Behavior
Custom property will not disappear until I delete them.

## Current Behavior
Custom property will disappeared after saving about 30 minutes on shared calendar

## Steps to Reproduce, or Live Example
1. Open an delegated calendar on Mac Outlook
2. try use 'Office.context.mailbox.item.loadCustomPropertiesAsync' save some value to custom property
3. send this meeting event.
4. in first serval minutes(about 5~15 minutes) can read custom property normally. 
5. wait 30 minutes, then try read the custom property.
6. Only read '{}' and status 'success'

## Context
User can't edit these meeting after scheduled...

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.44 20121301
* Operating System: Mac
* Browser (if using Office on the web): NA

## Useful logs
Some times might get error on Sync error : 'A message could not be sent' and 'An unknown error has occurred in Outlook'
Permission set like:
![image](https://user-images.githubusercontent.com/15980696/102567651-e877ff00-411c-11eb-9442-7cac613493e9.png)

**Comment by exextoc** [comment]
@SWei1234, 
Thanks for reporting this issue regarding custom properties on delegate calendar. It has been put on our backlog. We unfortunately have no timelines to share at this point.
Internal tracking id: Office 1838683

**Comment by SWei1234** [comment]
Hi @exextoc 
If have any update or anything need my help, please update here. Thanks

**Comment by exextoc** [comment]
This is in our backlog. Unfortunately, we still have no timelines to share at this point.

**Comment by peacewater-vm** [comment]
Hi @exextoc,
The same issue was reproduced in OWA (Chrome, Mozilla, and Edge browsers) and in Desktop Outlook O365 (16.0.14228.20204).
The user has full rights on a delegated calendar (delegatePermission: 63) but can not save customProperties tho' in Read mode - Office sends "status: succeeded" after saving custom props however it is not saved actually (loadCustomPropertiesAsync shows that rawData is empty after all).

Please advise if there are any updates on the timelines for this case resolution.

**Comment by exextoc** [comment]
@vitaliimyrvoda , Thanks for your patience. We are unable to reproduce the issue at our end.

Can you please verify if it's still happening to you? If so, we would like to collect the logs to understand the issue more. 
Follow these steps to get us the incident ID: 

1. Repro the issue 
2. Click on the Help tab from Outlook Menu 
3. Click on collect Diagnostics 
4. This will generate an Incident ID, share that with us.

It will be helpful if you can send a short video of the same to OutlookAddins@M365x693897.onmicrosoft.com.

**Comment by SWei1234** [comment]
@exextoc 
Just wonder if this problem have any update.

**Comment by exextoc** [comment]
We are unable to reproduce this issue at our end, in order to fix the issue, could you please collect the logs and send them to us. Follow these steps to get us the incident ID:

Repro the issue
Click on the Help tab from Outlook Menu
Click on collect Diagnostics
This will generate an Incident ID, share that with us.

It will be helpful if you can send a short video of the same to OutlookAddins@M365x693897.onmicrosoft.com.
