### ISSUE TITLE
MS login window comes up in browser, not needed, only in Outlook Client Application

### ISSUE THREAD

**Issue by LidiaEmma** [OfficeDev/office-js#1558]
I have an outlook add-in and, when it's loaded it should read the token via the MSAL library (updated at version 1.4.4.) and in case it's not found load a sign-in button, and after click an authentication form appears in outlook app. 
It's happening , but at the load of add-in (so not at click of button) another thing not needed is happening: a browser with the authentication page comes out. 

In outlook web it's not happening; only in client app Outlook version 2008, build 13127.20638, on Windows 10. 

Any hint about will be appreciated. 
Thank you so much!

**Comment by exextoc** [comment]
Unfortunately we don't have enough experience with the MSAL library to comment on the former part of your request. From the sounds of it, it looks like it's specific to the add-in you're creating - how/where you're initializing the library or on how the library behaves if the user isn't authenticated. As for the latter part of the issue, where a browser opens up instead, is the URL of the page where authentication happens in the same domain as the URLs from the manifest? Are you using the displayDialog API by any chance to show the login page? Another thing you could try is using our [SSO API](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins) to authenticate users if that helps.
