### ISSUE TITLE
Error 5001 with multiple event handlers on Office.EventType.ItemChanged in Outlook

### ISSUE THREAD

**Issue by visual4** [OfficeDev/office-js#156]
## Expected Behavior
in the documentation for addHandlerAsync it is stated, that as long as the handler names differ, you can add as many handlers as you want.

```
function myhandler(test){
    console.log('first');    
}
function my2handler(test){
    console.log('second');
}
function myCallback (res) {
    console.log(res);
}
Office.initialize = reason => {
        launch();
        Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, myhandler, [], myCallback);
        Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, my2handler, [], myCallback);
    };
```
## Current Behavior
the first handler is ok and works like expected.
for the second Handler the callback function outputs 
```
OSF.DDA.AsyncResult {value: undefined, status: "failed", error: OSF.DDA.Error}
    error: OSF.DDA.Error
        code: 5001
        message: "Ein interner Fehler ist aufgetreten."
        name: "Interner Fehler"
    status: "failed"
    value: undefined
```
## Context
I was actually trying to create a rxjs observable from this event with Rx.observable.fromEventPattern. Unfortunately with every subscription a new event gets added for every subscription. I will now try to use the share operator.

## Environment
this happens in Office365 Online in Chrome and Firefox on Windows. Outlook Client not tested due to missing console.

**Comment by visual4** [comment]
In Outlook Client Version 1805 Build 9330.2087 on Win 10, multiple handlers work like expected.

**Comment by exextoc** [comment]
That sounds good. Should we consider this as resolved then?

**Comment by visual4** [comment]
sorry for the delay,
no, in Web client the handler does not work like expected, only in Outlook for Windows it does.
Cheers,
Björn

**Comment by exextoc** [comment]
We are in the progress of looking into this. From initial investigations the timing of adding the handlers on the web client seems to matter. Until we make further progress, it looks like the workaround will have to be to only add one handler, and let that handler call the other handles that you wish to call.
