### ISSUE TITLE
Excel add ins manifest<OfficeMenu id="ContextMenuCell">unable to run

### ISSUE THREAD

**Issue by gerrychong** [OfficeDev/office-js#1560]
An error occurred when I tried to use this manifest item
[https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extensionpoint](url)

## Expected Behavior
ContextMenuCell - Displays the item on the context menu when the user opens the context menu (right-clicks) on a cell on the spreadsheet

## Current Behavior
Unable to run while creating ContextMenuCell

## Steps to Reproduce, or Live Example
yo office ->Office add-in  Task pane project using React framework->TypeScript->Excel->(Insert ExtensionPoint creating OfficeMenu)
`<ExtensionPoint xsi:type="ContextMenu">
            <OfficeMenu id="ContextMenuCell">
              <Control xsi:type="Menu" id="myMenuID">
                <Label resid="residLabel3" />
                <Supertip>
                  <Title resid="residLabel" />
                  <Description resid="residToolTip" />
                </Supertip>
                <Icon>
                  <bt:Image size="16" resid="Icon.16x16" />
                  <bt:Image size="32" resid="Icon.32x32" />
                  <bt:Image size="80" resid="Icon.80x80" />
                </Icon>
                <Items>
                  <Item id="myMenuItemID">
                    <Label resid="residLabel3"/>
                    <Supertip>
                      <Title resid="residLabel" />
                      <Description resid="residToolTip" />
                    </Supertip>
                    <Icon>
                      <bt:Image size="16" resid="Icon.16x16" />
                      <bt:Image size="32" resid="Icon.32x32" />
                      <bt:Image size="80" resid="Icon.80x80" />
                    </Icon>
                    <Action xsi:type="ShowTaskpane">
                      <SourceLocation resid="Taskpane.Url"/>
                    </Action>
                  </Item>
                </Items>
              </Control>
            </OfficeMenu>
          </ExtensionPoint>`
VS CODE :npm start
Error:This add-in is no longer available:add-ins inserted during development are only available during debugging from Visual Studio. Please open your project in Visual Studio and re-run your application, or deploy your add-in into a valid catalog and re-insert.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version2012(build 13530.20144 Click-to-Run)
* Operating System: win10 
* Browser (if using Office on the web): Chrome

Manifest.xml

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="TaskPaneApp">
  <Id>a15c158f-cc98-473c-bc5a-e47cc92e9434</Id>
  <Version>3.0.0</Version>
  <ProviderName>WA</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="odemo2"/>
  <Description DefaultValue="A cost to get started."/>
  <IconUrl DefaultValue="https://localhost:3000/assets/icon-32.png"/>
  <HighResolutionIconUrl DefaultValue="https://localhost:3000/assets/icon-64.png"/>
  <SupportUrl DefaultValue="https://www.contoso.com/help"/>
  <AppDomains>
    <AppDomain>https://www.baidu.com</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Workbook"/>
  </Hosts>
  <DefaultSettings>
    <SourceLocation DefaultValue="https://localhost:3000/taskpane.html"/>
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Hosts>
      <Host xsi:type="Workbook">
        <DesktopFormFactor>
          <GetStarted>
            <Title resid="GetStarted.Title"/>
            <Description resid="GetStarted.Description"/>
            <LearnMoreUrl resid="GetStarted.LearnMoreUrl"/>
          </GetStarted>
          <FunctionFile resid="Commands.Url"/>
          <ExtensionPoint xsi:type="PrimaryCommandSurface">
            <OfficeTab id="TabHome">
              <Group id="CommandsGroup">
                <Label resid="CommandsGroup.Label"/>
                <Icon>
                  <bt:Image size="16" resid="Icon.16x16"/>
                  <bt:Image size="32" resid="Icon.32x32"/>
                  <bt:Image size="80" resid="Icon.80x80"/>
                </Icon>
                <Control xsi:type="Button" id="TaskpaneButton">
                  <Label resid="TaskpaneButton.Label"/>
                  <Supertip>
                    <Title resid="TaskpaneButton.Label"/>
                    <Description resid="TaskpaneButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <TaskpaneId>ButtonId1</TaskpaneId>
                    <SourceLocation resid="Taskpane.Url"/>
                  </Action>
                </Control>
                <Control xsi:type="Button" id="TaskpaneButto1">
                  <Label resid="TaskpaneButton.Label1"/>
                  <Supertip>
                    <Title resid="TaskpaneButton.Label2"/>
                    <Description resid="TaskpaneButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <TaskpaneId>ButtonId2</TaskpaneId>
                    <SourceLocation resid="Taskpane.Url"/>
                  </Action>
                </Control>
              </Group>
            </OfficeTab>
          </ExtensionPoint>
          <ExtensionPoint xsi:type="ContextMenu">
            <OfficeMenu id="ContextMenuCell">
              <Control xsi:type="Menu" id="myMenuID">
                <Label resid="residLabel3" />
                <Supertip>
                  <Title resid="residLabel" />
                  <Description resid="residToolTip" />
                </Supertip>
                <Icon>
                  <bt:Image size="16" resid="Icon.16x16" />
                  <bt:Image size="32" resid="Icon.32x32" />
                  <bt:Image size="80" resid="Icon.80x80" />
                </Icon>
                <Items>
                  <Item id="myMenuItemID">
                    <Label resid="residLabel3"/>
                    <Supertip>
                      <Title resid="residLabel" />
                      <Description resid="residToolTip" />
                    </Supertip>
                    <Icon>
                      <bt:Image size="16" resid="Icon.16x16" />
                      <bt:Image size="32" resid="Icon.32x32" />
                      <bt:Image size="80" resid="Icon.80x80" />
                    </Icon>
                    <Action xsi:type="ShowTaskpane">
                      <SourceLocation resid="Taskpane.Url"/>
                    </Action>
                  </Item>
                </Items>
              </Control>
            </OfficeMenu>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>
    <Resources>
      <bt:Images>
        <bt:Image id="Icon.16x16" DefaultValue="https://localhost:3000/assets/icon-16.png"/>
        <bt:Image id="Icon.32x32" DefaultValue="https://localhost:3000/assets/icon-32.png"/>
        <bt:Image id="Icon.80x80" DefaultValue="https://localhost:3000/assets/icon-80.png"/>
      </bt:Images>
      <bt:Urls>
        <bt:Url id="GetStarted.LearnMoreUrl" DefaultValue="https://go.microsoft.com/fwlink/?LinkId=276812"/>
        <bt:Url id="Commands.Url" DefaultValue="https://localhost:3000/commands.html"/>
        <bt:Url id="Taskpane.Url" DefaultValue="https://localhost:3000/taskpane.html"/>
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="GetStarted.Title" DefaultValue="请开始你的加载项!"/>
        <bt:String id="CommandsGroup.Label" DefaultValue="控制组"/>
        <bt:String id="TaskpaneButton.Label" DefaultValue="打开加载项"/>
        <bt:String id="TaskpaneButton.Label2" DefaultValue="打开加载项"/>
        <bt:String id="TaskpaneButton.Label1" DefaultValue="打开加载项"/>
        <bt:string id ="residLabel3" DefaultValue="标题3"/>
        <bt:string id ="residLabel" DefaultValue="标题"/>
        <bt:string id ="residLabel5" DefaultValue="标题5"/>
        <bt:string id ="residToolTip" DefaultValue="标题一tips"/>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="GetStarted.Description" DefaultValue="你的加载项已运行成功. 请单击'展开面板'开始你的项目."/>
        <bt:String id="TaskpaneButton.Tooltip" DefaultValue="单击显示面板"/>
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>
`

**Comment by lindalu-MSFT** [comment]
@lliu113 Lillian is this your area? Please let me know if I need to reassign! Thanks in advance, double EL

**Comment by lliu113** [comment]
@gerrychong - sorry for the late response to this! I took a look at your manifest, there seems to be nothing wrong with the context menu portion but the manifest itself has issues (e.g. schema violations). 

The manifest you used has since been deleted, my guess is that it was stale. Let me follow-up internally to see if there is a better add-in template for you to use. 

Thanks!
Lillian

**Comment by lliu113** [comment]
@gerrychong here is more info on the error you hit - https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-development-errors?view=excel-js-preview#getting-error-this-add-in-is-no-longer-available

**Comment by lliu113** [comment]
@gerrychong - I'm going to go ahead and close this issue for now. Please reactivate if you have any additional questions. Thanks!

**Comment by timmaffett** [comment]
In response to the issue I was having Angela from MS provided me with these working examples:

This one adds a parent menu with children to the cell context menu :

 <OfficeMenu id="ContextMenuCell">
                <Control xsi:type="Menu" id="myMenuID">
                  <Label resid="residLabel" />
                  <Supertip>
                      <Title resid="residLabel" />
                      <Description resid="residToolTip" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="icon1_16x16" />
                    <bt:Image size="32" resid="icon1_32x32" />
                    <bt:Image size="80" resid="icon1_80x80" />
                  </Icon>
                  <Items>
                    <Item id="myMenuItemID">
                      <Label resid="residLabel2"/>
                      <Supertip>
                        <Title resid="residLabel2" />
                        <Description resid="residToolTip" />
                      </Supertip>
                      <Icon>
                        <bt:Image size="16" resid="icon1_16x16" />
                        <bt:Image size="32" resid="icon1_32x32" />
                        <bt:Image size="80" resid="icon1_80x80" />
                      </Icon>
                      <Action xsi:type="ShowTaskpane">
                        <SourceLocation resid="Taskpane.Url" />
                      </Action>
                    </Item>
                  </Items>
                </Control>
            </OfficeMenu>
         </ExtensionPoint>
     <bt:Images>
        <bt:Image id="icon1_16x16" DefaultValue="https://wikipedia.firstpartyapps.oaspapps.com/wikipedia/images/wikipedia_32x32.png"></bt:Image>
        <bt:Image id="icon1_32x32" DefaultValue="https://wikipedia.firstpartyapps.oaspapps.com/wikipedia/images/wikipedia_32x32.png"></bt:Image>
        <bt:Image id="icon1_80x80" DefaultValue="https://wikipedia.firstpartyapps.oaspapps.com/wikipedia/images/wikipedia_32x32.png"></bt:Image>
      </bt:Images>
      <bt:ShortStrings>
        <bt:String id="residLabel" DefaultValue="Wikipedia Menu"></bt:String>
        <bt:String id="residLabel2" DefaultValue="Wikipedia Button"></bt:String>
      </bt:ShortStrings>

and a slight variation adds a single menu button (note that this one the control added is a 'button' and not a 'menu'.

<ExtensionPoint xsi:type="ContextMenu">
          <OfficeMenu id="ContextMenuCell">
            <Control xsi:type="Button" id="ContextMenuButton1">
              <Label resid="residLabel" />
              <Supertip>
                <Title resid="residLabel" />
                <Description resid="residToolTip" />
              </Supertip>
              <Icon>
                <bt:Image size="16" resid="icon1_32x32" />
                <bt:Image size="32" resid="icon1_32x32" />
                <bt:Image size="80" resid="icon1_32x32" />
              </Icon>
              <Action xsi:type="ShowTaskpane">
                        <SourceLocation resid="Taskpane.Url" />
               </Action>
            </Control>
          </OfficeMenu>
        </ExtensionPoint>



I had done the exact same thing as the second option and it had not worked, but it ended up that I was naming my resid's MenuLabel and MenuDescription,  when I changed the above to use these resid's it also stopped working.. weird.
But I wanted to put these working examples here for anyone that finds this issue is a search
