### ISSUE TITLE
[Excel] Excel.createWorkbook throws exception on ios

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#1562]
## Expected Behavior
Excel.createWorkbook(base64) should not throw

## Current Behavior
Excel.createWorkbook(base64) creates a workbook but also throws a "Not Implemented" exception on ios.

## Steps to Reproduce, or Live Example

* Additional details:
  1. Create a snippet with Excel.createWorkbook(base64).catch(displayError)
  2. Replace "base64" with the base64 representation of a workbook.
  2. Run snippet on ios
  3. Observer error

## Context
We want to create Excel Workbooks on iPad. This is working but we have to handle the error.

## Your Environment
* Platform: iOS
* Host: Excel

## Useful logs
![image](https://user-images.githubusercontent.com/6338132/102990707-1e035a80-4518-11eb-854d-eefa125eb855.png)

**Comment by MandytMSFT** [comment]
@barisbikmaz thanks for reaching us. I can repro this issue and BUG 4741547 is opened for internal track. We unfortunately have no timelines to share at this point.

**Comment by lumine2008** [comment]
This issue was fixed, please verify, thanks
