### ISSUE TITLE
[Excel] Non-error promise rejection when launching a dialog

### ISSUE THREAD

**Issue by christian513** [OfficeDev/office-js#1563]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi,

every time we launch a dialog from our add-in in PC desktop using the Office.context.ui.displayDialogAsync API we see this error in our application monitoring (sentry.io):

"Non-Error promise rejection captured with keys: code, message, name"

Promise rejected with {"name":"Permission Denied","message":"You don't have sufficient permissions for this action.","code":7000}}

## Expected Behavior
There should be no internal error when launching a dialog.

## Current Behavior
The dialog is launched as expected and works fine but there seem to be an internal error in Office.js when calling the above API.

## Steps to Reproduce, or Live Example
- Open a dialog

## Your Environment
* Platform [PC desktop]
* Host [Excel]
* Office version number:  2002 (12527.21416)

* Operating System:  Windows

**Comment by lliu113** [comment]
@christian513 thanks for reporting this! Just so I understand, this is not blocking your dialog from launching but it's throwing an internal error? What is your dialog doing?

**Comment by christian513** [comment]
@lliu113 you are right. The dialog is launched correctly but every time this error occurs. The error does not show up in the dialog but nevertheless it should not happen. The error is triggered when launching the dialog. So it does not depend on what the dialog is doing. Even if the dialog is a completely empty page without functionality the error occurs.

**Comment by lliu113** [comment]
@christian513 appreciate the clarification, I will follow-up internally. Thanks!

**Comment by lliu113** [comment]
Internal bug: 4803453
