### ISSUE TITLE
[Excel] Office add-in fails to load due to invalid cert authority even after installing dev certs

### ISSUE THREAD

**Issue by chucklay** [OfficeDev/office-js#1564]
Currently being experienced by @viperhodge11. On trying to insert our add-in in Excel online (in Edge), was unable to load the add-in, despite the CAs being installed.

We've attempted to uninstall/reinstall the certs via `npx office-addin-dev-certs uninstall` and `npx office-addin-dev-certs install` (restarting the dev server and edge between installs) multiple times, but haven't gotten anywhere.

`npx office-addin-dev-certs verify` never shows the certs as being installed, even right after running the install command.

In addition, even after running the install command, the first time we run `npm run start:web` the dev server prompts us to install the certs again.

## Expected Behavior

`npx office-addin-dev-certs install` should install any needed certificates for localhost

## Current Behavior

`npx office-addin-dev-certs install` claims to have installed the required certs, but localhost is unreachable without invalid certificate errors

## Steps to Reproduce, or Live Example

* Sadly N/A to our knowledge. This appears to only be impacting one developer.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop/Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows 10
* Browser (if using Office on the web): Edge

## Useful logs

```
viper@venge MINGW64 ~/src/plaidxl-service (andrew)
$ npx office-addin-dev-certs install
The developer certificates have been generated in C:\Users\viper\.office-addin-dev-certs
Installing CA certificate "Developer CA for Microsoft Office Add-ins"...
You now have trusted access to https://localhost.
Certificate: C:\Users\viper\.office-addin-dev-certs\localhost.crt
Key: C:\Users\viper\.office-addin-dev-certs\localhost.key
viper@venge MINGW64 ~/src/plaidxl-service (andrew)
$ npx office-addin-dev-certs verify
You need to install certificates for trusted access to https://localhost.
```

**Comment by keyur32** [comment]
Hey sorry for the delay on this one. Adding @TCourtneyOwen to see if he can help.  

Is localhost unreachable from your add-in or browser? or both?
