### ISSUE TITLE
Comments and Grouping are not loaded into excelusing addFromBase64

### ISSUE THREAD

**Issue by PavanaKatta** [OfficeDev/office-js#1565]
Hi Team,

We are using **addFromBase64** in Office 365. Comments and Grouping in not loading in the excel.

Could you please suggest any other way i can achieve this functionality.

Thanks team in advance!!..

Thanks,
Pavan

**Comment by PavanaKatta** [comment]
Disable cell functionality is also  missed.

**Comment by MandytMSFT** [comment]
@PavanaKatta  Thanks for reaching us. Can I know which platform (Excel desktop, online, mac or iOS) you are using AddFromBase64? I am asking this because Comments and Grouping has been supported on Excel Desktop. If you are on desktop, can I know your excel version ?

Besides, what do you mean by "Disable cell functionality is also missed" ?

**Comment by PavanaKatta** [comment]
> @PavanaKatta Thanks for reaching us. Can I know which platform (Excel desktop, online, mac or iOS) you are using AddFromBase64? I am asking this because Comments and Grouping has been supported on Excel Desktop. If you are on desktop, can I know your excel version ?
> 
> Besides, what do you mean by "Disable cell functionality is also missed" ?

-------------------------------------------------------------------
I am using Excel Online (Office 365). 

I am protecting sheet and enabling some cells. But, this is not working in excel online.

**Comment by MandytMSFT** [comment]
@PavanaKatta thanks for clarify. Then they are known limitation for this API on Excel Online. Could you help review if steps below is acceptable or not ? Besides, We track Office Add-in feature requests on our [UserVoice page](https://officespdev.uservoice.com/) You can add your request there if needed. Feature requests on user-voice are considered when we go through our planning process. 

1.	First remove the unsupported features in source workbook, such as comments, group shape.
2.	Call  AddFromBase64 API on online to import the source workbook.
3.	If you still needs the removed unsupported features in step 1, call comment/shape api to add them back to destination workbook.

**Comment by PavanaKatta** [comment]
> @PavanaKatta thanks for clarify. Then they are known limitation for this API on Excel Online. Could you help review if steps below is acceptable or not ? Besides, We track Office Add-in feature requests on our [UserVoice page](https://officespdev.uservoice.com/) You can add your request there if needed. Feature requests on user-voice are considered when we go through our planning process.
> 
> 1. First remove the unsupported features in source workbook, such as comments, group shape.
> 2. Call  AddFromBase64 API on online to import the source workbook.
> 3. If you still needs the removed unsupported features in step 1, call comment/shape api to add them back to destination workbook.

------------------------------

Thanks for the quick response.

Could you please help me the links on how to add comments and groups  back to opened excel which you have mentioned in the Step3.

**Comment by MandytMSFT** [comment]
@PavanaKatta  You can find comment/group related API on below page:
https://docs.microsoft.com/en-us/javascript/api/excel/excel.commentcollection?view=excel-js-preview#add_cellAddress__content__contentType_ 

https://docs.microsoft.com/en-us/javascript/api/excel/excel.shapecollection?view=excel-js-preview#addGroup_values_

**Comment by PavanaKatta** [comment]
I am protecting sheet and enabling some cells. But, this is not working in excel online. 

Is the above issue resolved.

**Comment by lumine2008** [comment]
insertWorksheetsFromBase64 is now in preview for Excel online, would you please verify this API?
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-preview-apis?view=excel-js-preview

**Comment by lumine2008** [comment]
I am going to close this issue due to we have a new API insertWorksheetsFromBase64, please validate and re-open if you still observe some other issues, thanks.

**Comment by PavanaKatta** [comment]
> I am going to close this issue due to we have a new API insertWorksheetsFromBase64, please validate and re-open if you still observe some other issues, thanks.

I am using insertWorksheetsFromBase64, but issue still exist.
