### ISSUE TITLE
When bookmarks API would be released officially?

### ISSUE THREAD

**Issue by katyapavlenko** [OfficeDev/office-js#1569]
Hi! 
My product depends on bookmarks API, so I am interested if there are any estimations when it would be released fully?

I see that now it's only supported in preview mode and only for windows
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/word-preview-apis#see-also

**Comment by AbidRahman-MSFT** [comment]
Hello Katya, 

Unfortunately there is no timeline for an official release for the bookmarks API (along with the rest of the Preview APIs for Word). It has been in our backlog for a while but we will not be able to get to it for at least this fiscal year. I apologize as I cannot give you a timeline. Please follow our blogs [developer blog](https://developer.microsoft.com/en-us/office/blogs/) as we will post an update once we are ready for official release.

Thanks,
Abid

**Comment by katyapavlenko** [comment]
thank you, @AbidRahman-MSFT
