### ISSUE TITLE
Font size getting changed when email is sent from Outlook app 

### ISSUE THREAD

**Issue by gs-achandrakamal** [OfficeDev/office-js#1574]
When sending normal text email from Outlook desktop app, the font sizes are being changed randomly when received.

## Expected Behavior

Font size for email content should remain consistent when received.

## Current Behavior

Font size is decreasing randomly in the received email
## Steps to Reproduce, or Live Example

* Additional details:
  1. Compose new mail from outlook app
  2. Add text content with some bullets or ordered lists
  3. Send email
  4. Received email is having content with non-uniform font sizes

<img width="543" alt="Received mail" src="https://user-images.githubusercontent.com/72736097/103740960-38602c80-501e-11eb-8250-5c924630ae4c.png">

## Context

Need to send email with consistent content

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Microsoft Outlook on Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook(Version 16.43)
* Office version number: 2020.11.5.18435
* Operating System: Mac OS
* Browser (if using Office on the web): NA

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
Hi @gs-achandrakamal , this doesn't seem to be an issue related to add-ins. Is the problem specifically with the body being set by add-ins?

**Comment by gs-achandrakamal** [comment]
> Hi @gs-achandrakamal , this doesn't seem to be an issue related to add-ins. Is the problem specifically with the body being set by add-ins?

It's not specific to add-in, it's happening in normal emails too. But as our add in sets the email's body ,this issue happens there also. It was reported by one of our customers using Outlook app.

**Comment by exextoc** [comment]
Thanks @gs-achandrakamal. Since this is not an add-in specific issue, it probably doesn't belong here. Can you file a bug report from within Outlook?

**Comment by gs-achandrakamal** [comment]
Okay, thank you. It will be really helpful if you provide any link for that Outlook repo or any other portal for reporting this bug.

**Comment by lindalu-MSFT** [comment]
Closing issue, not related to office-js.
