### ISSUE TITLE
OfficeJS : Context menus are not visible when right click on table

### ISSUE THREAD

**Issue by sarala-bhalerao** [OfficeDev/office-js#1576]
I am using OfficeJs to create word add-in. In that i have added context menus from manifest I can see the context menus on right click of document, content control but when I perform right click on table i'm not able to see the context menus. Why the context menus are not visible on right click on table? Please help if anyone know the solution.

## Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
Host [Excel, Word, PowerPoint, etc.]: Word
Office version number: Microsoft 365 MSO (16.013426.20330)
Operating System: Windows 10

**Comment by KelBowen** [comment]
@lliu113 - hoping you can help? Not sure if this is a how-to question or a bug.

**Comment by sarala-bhalerao** [comment]
Here are some screenshots:
1) when content control in document context menu is visible
![Context menu in doc (2)](https://user-images.githubusercontent.com/71916499/104146944-7d0b0f80-53f2-11eb-8555-351358c32b8b.png)

2) In table context menu is not visible.
![context menu in table (2)](https://user-images.githubusercontent.com/71916499/104146963-8a27fe80-53f2-11eb-9903-6349c19e01d1.png)

**Comment by lliu113** [comment]
@sarala-bhalerao thanks for reporting this! Unfortunately the context menu is only supported for basic text in the document, and not tables or other objects within Word. 

If you'd like to make a feature request for additional support, please submit a new idea to https://officespdev.uservoice.com/. 

Closing this issue, please reopen if you have any further questions. Thanks!

**Comment by sarala-bhalerao** [comment]
Can I get list of objects for which context menu is not supported and list of supported objects?

**Comment by mstransky** [comment]
Is there any reason not to enable it on all objects? I think its wonderful feature

**Comment by TeamviennaJeremy** [comment]
@lliu113 Is there a reason the context menus don't work on URLs? 
I think this is a huge show stopper for all users of office.js.

**Comment by lliu113** [comment]
@TeamviennaJeremy - great questions. This was more of a technical limitation than a design one. It is on our backlog to support other objects like tables, images etc. but we currently have no ETA. 

We have shifted feature requests to the [Microsoft Developer Platform](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). Please upvote this request to help us prioritize for the future - thanks!

**Comment by nicolasiscoding** [comment]
@lliu113 Hi! Has there been any updates on this?

**Comment by katerinaNewcodeAI** [comment]
Hi! I'm also struggling with this issue, and not only for tables. I have the same problem for headings and lists. My Word add-in Context Menu works perfectly fine only for standart text and invisible for tables, headings, lists in the Desktop version.
Does anybody know if the Microsoft solved this issue? Or maybe you can help me?
