### ISSUE TITLE
input type="file" not working on dev

### ISSUE THREAD

**Issue by lowefraser** [OfficeDev/office-js#1577]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

if you add an `<input type="file"/>` to the taskpane (or a dialogue) and deploy using the dev tools (npm start) then clicking on browse does not do anything.

However, if you deploy to prod then browse loads the file selection dialogue as expected.

I have tested this in both Excel and Powerpoint. For PowerPoint, following the instructions detailed here [https://docs.microsoft.com/en-us/office/dev/add-ins/powerpoint/insert-slides-into-presentation].

This is on Windows 10/Office Build 13530.20316.

**Comment by lowefraser** [comment]
Update: I believe this only applies to the workbook that opens automatically when you run `npm start`.

When using a blank workbook, going to 'Insert' > 'My Add-ins' drop down and selecting the developer add-in, the Browse... button does open the file dialogue.

**Comment by smaremanda** [comment]
@lowefraser - we are looking into this issue. In the meantime, have you tested this using the latest WebView2 control? If yes, please share any details.

**Comment by zliebersbach** [comment]
We are having a similar issue with our **production** add-in which uses the shared runtime, so is as of yet unsupported by WebView2 (as far as we know). The issue has appeared in release Excel for Windows v2102 (Current channel).

As you can see in the attached video, Excel completely crashes if you have the file picker open for more than a few seconds. The add-in reloads, but the entire UI becomes unresponsive. There are no errors in the JavaScript console nor in the Runtime Log. The exact code used is as follows:
```html
<input type="file">
```

Video: https://www.screencast.com/t/Zq47B7FSJfSd

**Comment by zliebersbach** [comment]
Have tested on macOS Catalina and Online and neither produce this error. Seems to be a regression in the IE WebView.

:crossed_fingers: we get WebView2 for shared runtimes soon...

**Comment by donlvMSFT** [comment]
Could you help verify whether this is still reproduced on WebView2?
