### ISSUE TITLE
CustomTab & Worksheet visibility dose not work in excel 64bit

### ISSUE THREAD

**Issue by hanzhangyu** [OfficeDev/office-js#158]
See this issue for details: https://stackoverflow.com/questions/50616329/office-js-customtab-worksheet-visibility-dose-not-work-in-excel-64bit
## Expected Behavior

The Excel 64bit show the `customTab` and hide the worksheet.

## Current Behavior

When I insert the addin the excel show the web panel only. and the worksheet were all showed.
But It\`s works well after I debug the addin by `visual studio 2017`.
After I debugged my addin in the `visual studio 2017`, Everything goes back to the beginning when I reinstall the Excel.

## Steps to Reproduce, or Live Example

Use the `manifest.xml` I provided in the `stackoverflow`.
Insert It into the shared folder in the Excel 64bit.

## Context

Test my addin in the Excel 64bit.

## Your Environment

* Platform: PC desktop
* Host: Excel
* Office version number:  (16.0.4266.1001)64bit
* Operating System: window 10 pro

**Comment by JuaneloJuanelo** [comment]
the referred build does not support Add-in commands. You need to upgrade to Office 365 builds.
