### ISSUE TITLE
Office.context.mailbox.item.getAttachmentContentAsync not work in IE11 

### ISSUE THREAD

**Issue by He-Dongwei-GitHub** [OfficeDev/office-js#1580]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
`Office.context.mailbox.item.getAttachmentContentAsync` should get the attachments successfullly in IE11

## Current Behavior
When I call `Office.context.mailbox.item.getAttachmentContentAsync` in IE11, I will always get an error, see the picture below:
![image](https://user-images.githubusercontent.com/67097551/103981091-0edd0780-51bc-11eb-9e81-6f64512653b6.png)

As I know, `URLSearchParams` is not supported in IE11. But it seems that some where of the calling stack of `Office.context.mailbox.item.getAttachmentContentAsync` used `URLSearchParams`, so we got this error.

## Steps to Reproduce, or Live Example
1. install add-in by manifest.xml
2. add attachment in send box
3. add recipients, subject, message in send box
4. open the dev tool
5. click send button in send box, wait a while you will see the error in dev tool; And the mail will send failled.

## Context
I want to get the attachment in the mail when send.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
* Operating System: Online
* Browser (if using Office on the web): IE 11

**Comment by exextoc** [comment]
Hi @He-Dongwei-GitHub we're able to reproduce this issue on IE11. Thank you for reporting this. We have put this item in our backlog. Unfortunately, we don't have timelines to share at this point.

**Comment by AdielAhmad** [comment]
Hi @exetoc, i am running into the same issue, would the validation policy for Office Add-Ins deny my submission in this case? 
It seems like this issue is only related to IE11, but older versions of the Desktop-Application are using IE11 aswell.

**Comment by Vaibhav-Mande** [comment]
Hi any update on this Issue ?

**Comment by zwang1225** [comment]
Please is there any update on this issue? My team is facing the same issues. @exextoc

**Comment by exextoc** [comment]
This is still in the backlog, we don't have a date to share yet, but we will you posted when we take this up.
