### ISSUE TITLE
Incorrect scrollbar behavior in Word Online using Safari

### ISSUE THREAD

**Issue by WillemSleegers** [OfficeDev/office-js#1581]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
The width and height of the taskpane should adapt to the content of the taskpane, only producing scrollbars if the content of the taskpane exceeds the width and height.

## Current Behavior
Scrollbars appear regardless of content, nor do the scrollbars seem correct.

<img width="501" alt="Screen Shot 2021-01-09 at 15 56 33" src="https://user-images.githubusercontent.com/4398042/104094789-54b8cf00-5293-11eb-9697-c85edc1c20ff.png">

## Steps to Reproduce, or Live Example
1. Open a document in Word Online in Safari (EDIT: or Firefox).
2. Launch the Script Lab example add-in
3. Observe scrollbars

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: -
* Operating System: macOS Big Sur 11.1
* Browser (if using Office on the web): Safari

EDIT: This is also an issue in Firefox.

**Comment by lliu113** [comment]
@WillemSleegers - thanks for reporting this! The horizontal scrollbar is indeed incorrect, will open a bug internally and get this fixed.

**Comment by WillemSleegers** [comment]
I think the vertical scrollbar is also incorrect; it seems to behave unusually when scrolling. When I scroll through the Samples section of the add-in, the scrollbar does not respond until I get to the bottom of the add-in.

And in Chrome I do not get the initial vertical scrollbar.

**Comment by lliu113** [comment]
@WillemSleegers - I think you might be right, thanks for testing this. Will amend our internal bug to include both scrollbars. This is in our backlog but no ETA yet. Will update when we ship a fix - thanks! 

Ref: Bug ID 4782012

**Comment by ElizabethSamuel-MSFT** [comment]
@preethikakiru Can you take a look and reassign as needed? Thanks.
