### ISSUE TITLE
Very general error when starting an Outlook add-in - "A device attached to the system is not functioning"

### ISSUE THREAD

**Issue by rodimius** [OfficeDev/office-js#1583]
## Expected Behavior
I'd expect my task pane add-in to start correctly and redirect me to a login page

## Current Behavior
I get a blank page on opening the add-in pane. On checking the console logs I get a generic error after some amount of my javascript code runs.
(All systems are localised as nl-NL).
![image](https://user-images.githubusercontent.com/8717/104191262-337fec00-5415-11eb-96a6-b909aa709a19.png)
The english translation of the error is: 
-2147024865 	ERROR_GEN_FAILURE 	A device attached to the system is not functioning

There are no error codes in the network tab, and the content of each request is what I expect it to be.

This doesn't occur on every user's device, but a significant number. I can't see anything relevant in event viewer.

The pages for the add-in load correctly in Internet Explorer on the same device. (the add-in is hosted on Internet Explorer in outlook on these desktops)

## Context
The add-in site is hosted on the same network as the client PCs, there are no connectivity issues and all certificates are trusted.
Having supported running this same add-in on multiple different networks this is my first time seeing this error, and I can find no mentions of it in this repository.
I realise this may not be directly related to this library, but any pointer of where else to report this/get more information would be very helpful.
Compatibility mode is disabled, and there is no enterprise site list in operation.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop (mixed citrix and full desktop, issue occurs on both)
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office 365 enterprise (awaiting a response for specific version number)
* Operating System: Windows 10

## Useful logs

- [x] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
Where is that error coming from? Are you getting that as a return error when you call an API function? 

Does this occur on the same machines with other add-ins that aren't yours? 

What build version of Outlook are you on? (i.e. 16.0.XXXX.YYYY). What build version of Windows 10 are you on? (1908, etc.)

Is Office.Initialize being called?

**Comment by rodimius** [comment]
clarification here:
Outlook version is actually Outlook 2019 MSO, build 16.0.10346.20002 32-bits
Windows version is Windows Server 2019 Datacenter 10.0.17763, which appears to map to build 1809
I'll double check what the situation is with other add-ins on the same machine.
We're using the Office.onReady callback to bootstrap our app, and I can see logging from there.

The error doesn't appear to come from any of our code directly, there's no stack trace in the error, and it's happening during the Angular bootstrap process. The last line of logging from our application is from a class being initialized, but before the constructor is called.
At that point nothing in the `Office` object has been called other than assigning the `onReady` callback.

**Comment by exextoc** [comment]
Unfortunately, there is no obvious place in our code that returns that error. (Unless you are calling a specific API and getting that back, then we could investigate further). Could this be a failure somewhere coming from Angular? Normally I'd say that maybe there is something in IE that isn't compatible in your code...but you say that it loads fine in OWA in IE? (or just that the pages load fine in IE?) Is there anything additional to that, that may not be IE compatible? 

If you move to a later version of Windows/Office it will start loading in Edge, and it would be interesting to know if the problem persists in Edge too. (https://developer.microsoft.com/en-us/office/blogs/microsoft-edge-webview-for-office-add-ins/) But that may not be possible, if you don't have those versions of Office/Windows. 

The other thing to do: In Internet Explorer, make sure to (Tools->Internet Options->Advanced), and make sure "Disable Script Debugging" is Unchecked. You can also Check "display a notification for every script error" to see if any errors are popping up. (You may need to reboot for these settings to take effect). After that, you can attach a debugger (Visual Studio) in script mode to iexplore.exe, and hopefully debug your add-in. If you want to trigger your loading code again, put focus into the pane and hit Ctrl-F5.

Hopefully some of those tips will reveal where the error is coming from?

**Comment by rodimius** [comment]
There is a good mix of systems on site, so I will check if any are using edge.
I will go away and double check those things. Thanks.

**Comment by rodimius** [comment]
This ended up being caused by folder redirection. Specifically using Ivanti UEM.
The integrity level of the IE low integrity cache was not set to Low as a side effect of the folder redirection.
The error was being thrown when writing to localStorage, which I confirmed in the console, which helped us track it down.

Thanks for your help.
