### ISSUE TITLE
AppDomains Not Working for Office (Word) Add-in in preventing domains from opening in new window on Mac

### ISSUE THREAD

**Issue by james-huang** [OfficeDev/office-js#1586]
## Expected Behavior
I have something like the following in my Word Add-in Manifest
```
<AppDomains>
    <AppDomain>https://google.com</AppDomain>
</AppDomains>
```

In the browser it opens in the taskpane. 
## Current Behavior
When navigating to google.com in my Word add-on on Mac it always opens in a new window. 
I believe it should open in the taskpane.

## Steps to Reproduce, or Live Example
1. Add a domain `https://google.com` to Manifest AppDomains
2. Set windows.location.href = "https://google.com"

## Context
I am trying to navigate to a third-party URL such as google.com within the extension taskpane. 

## Your Environment
* Platform: Mac
* Host: Word
* Office version number: Version 16.44 (20121301)
* Operating System: MacOS 10.14.6 
* Browser: Chrome

[1] https://stackoverflow.com/questions/65338612/appdomains-not-working-for-office-word-add-in-in-preventing-domains-from-openi

**Comment by james-huang** [comment]
Hi Microsoft, any updates on this?

**Comment by jargil** [comment]
@james-huang - AppDomains elements have to be an exact match. When you navigate to "https://google.com" they redirect you to "https://www.google.com". If you want to avoid the popup, you'll have to add "https://www.google.com" to your AppDomains list. Let me know if this answers your question.

**Comment by james-huang** [comment]
My post and repro ever mentions the "www" subdomain?

**Comment by jargil** [comment]
@james-huang - your example uses "https://google.com". Google automatically redirects you to "https://www.google.com". The redirection to "https://www.google.com" is what is causing the navigation to pop out of Word. If you want the navigation to stay within Word you'll need to add both "https://google.com" and "https://www.google.com" or just add the second one and navigate directly to "https://www.google.com".

**Comment by jargil** [comment]
I'll go ahead and close this issue. Let me know if the answer above helped answer your question.
