### ISSUE TITLE
Outlook Add-in support for on-premise exchange server

### ISSUE THREAD

**Issue by ShubhamJain-Outlook** [OfficeDev/office-js#1587]
In our add-in we will be using Outlook Rest API to create and fetch events from the user’s mailbox. It is working fine for us for the mailboxes hosted in cloud. But we also need to add support for On-Premise exchange servers and there is no specific documentation details for the same.
As per the link https://techcommunity.microsoft.com/t5/exchange-team-blog/on-premises-architectural-requirements-for-the-rest-api/ba-p/605609, we can use Outlook Rest APIs with exchange server but as mentioned on https://support.microsoft.com/en-in/help/4462988/rest-api-is-not-yet-supported-for-this-mailbox-error , Rest API are not supported if mailbox is not on cloud.
Outlook Rest API documentation https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/use-outlook-rest-api also not mentioning anything about On-Premise Exchange Server. So we are planning to Exchange Webservice as a fallback mechanism but when we are using ews-java-api along with callback token retrieved from Office.context.mailbox.getCallbackTokenAsync({ isRest: false } that also gives me error "The requested web method is unavailable to this caller or application."

@office-js @outlook-web-addins

**Comment by exextoc** [comment]
For the most part REST is NOT supported On-Prem. There are some hybrid deployments that do support Rest (https://docs.microsoft.com/en-us/graph/hybrid-rest-support) But new REST Apis/updates aren't given to these environments. There are certainly will always be On Prem servers, where REST is not available and you need to fall back to EWS. 

The EWS token can be used for GetItem and GetAttachments only. (https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-1.5&preserve-view=true#getcallbacktokenasync-options--callback-) 

If you require other EWS operations, the makeEWSRequestAsync api, can make more calls. These are made by the Outlook Client for you. But not every EWS operation is allowed via this API. 

Also make sure that your manifest has the appropriate permissions for the actions that you want to use (ReadItem, ReadWriteItem, ReadWriteMailbox)

**Comment by ShubhamJain-Outlook** [comment]
Is there any support for on-premise customers with MS Graph APIs

**Comment by exextoc** [comment]
I don't think there's MS Graph support for exclusive on-premise environment. However, there support for hybrid deployments. See this documentation : https://docs.microsoft.com/en-us/graph/hybrid-rest-support
