### ISSUE TITLE
Outlook Exchange Server Environment for Testing

### ISSUE THREAD

**Issue by ShubhamJain-Outlook** [OfficeDev/office-js#1588]
Hi Team,
Is there any exchange server environment managed by Microsoft where we can perform functional and performance testing on different versions of exchange server.

@office-js @outlook-web-addins

**Comment by exextoc** [comment]
What versions of exchange server are you looking to test on? Microsoft doesn't provide a way to test against On-Prem Exchange servers. For Office 365, you could look into: https://developer.microsoft.com/en-us/microsoft-365/dev-program

You could also create a consumer account on outlook.com to test outlook add-ins.
