### ISSUE TITLE
Insert slides in a PowerPoint presentation - Fails if the browser is IE with GeneralException

### ISSUE THREAD

**Issue by waliwa** [OfficeDev/office-js#1589]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When trying to insert slides using the following  tutorial:- https://docs.microsoft.com/en-us/office/dev/add-ins/powerpoint/insert-slides-into-presentation:-
context.presentation.insertSlidesFromBase64(chosenFileBase64);
If the browser is IE11 it fails with GeneralException

## Steps to Reproduce, or Live Example
Used the following: https://docs.microsoft.com/en-us/office/dev/add-ins/powerpoint/insert-slides-into-presentation:-

## Your Environment

* Platform [PC desktop, Windows 10
* Host [Excel, Word, PowerPoint, etc.]: Powerpoint - Office 365 
* Office version number:  16.0.12526.21294
* Operating System: 10
* Browser (THAT Office using): IE11 - 11.4046

Note works on Edge on other desktop etc.

**Comment by waliwa** [comment]
Hello,
can you please confirm that inserting slides is supported if the browser is IE11?
As mentioned we have no problem with Edge. IE11 is the browser that we also have to support.

thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@wangyun-microsoft Can you take a look and reassign as needed? Thanks.

**Comment by wangyun-microsoft** [comment]
insertSlidesFromBase64 does not require a specific web browser. The web browser support is controlled at Addin level. Please refer to the following link for supported browser for each OS and Office version. 

https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins
