### ISSUE TITLE
Outlook API: loadCustomPropertiesAsync does not return CustomProperties for shared mailboxes

### ISSUE THREAD

**Issue by splinter** [OfficeDev/office-js#159]
The loadCustomPropertiesAsync behaves inconsistently across Outlook clients.

## Expected Behavior
The [loadCustomPropertiesAsync](https://dev.office.com/reference/add-ins/outlook/1.3/Office.context.mailbox.item) should return a [CustomProperties](https://dev.office.com/reference/add-ins/outlook/1.3/CustomProperties) object across all Outlook clients when accessing a shared mailbox. The same method calls works on the Mac Desktop client.

## Current Behavior
The loadCustomPropertiesAsync returns an undefined object for Outlook web clients ( Office365 online and Live).

## Steps to Reproduce, or Live Example
This can be reproduced by calling loadCustomPropertiesAsync after loading the add-in in a web client for a shared mailbox

## Context
We have several clients who have expressed an interest in accessing our Outlook add-in for shared mailboxes.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Outlook Live (Online), Mac Outlook 2016
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Mac Outlook 2016 (16.12 - 180410)
* Operating System:  Mac High Sierra 
* Browser (if using Office Online): Firefox and Chrome

**Comment by exextoc** [comment]
Add-ins for shared mailboxes is currently not supported. This is a feature we are investigating actively for all clients.

**Comment by JuaneloJuanelo** [comment]
upvote in https://officespdev.uservoice.com/
