### ISSUE TITLE
[Excel] getMergedAreas returns only the top left cell of the merged areas

### ISSUE THREAD

**Issue by billcawley** [OfficeDev/office-js#1590]
The method ‘getMergedAreas’ when applied to a row in Excel either returns an undefined area (there are merged areas which intercept with the row, but none start on the row) or returns a series of single cells (e.g. if the merged area is T4:U5, only T4 is returned).

I had wished to fill every cell of a merged area with the value in the top left, but given that only the top left cell is returned, this is not possible.

The particular problem is that I wish to detect the headings that a user sees as being in a row, even when some cells are merged with the cells above

**Comment by rundongmsft** [comment]
Hi Billcawley, 

Thanks for your questions! I have a workaround that can help to get all the cells of mergedAreas:

``` javascript
let areas = range.getMergedAreas();
let detailedAreas = areas.areas; // areas.areas will give us a detailed areas array
detailedAreas.load();
await context.sync(); // Before read detailedAreas's value, we should load and context.sync
```
Can this workaround solve your problem?

**Comment by lumine2008** [comment]
@billcawley, does rundong's workaround work for you?

**Comment by billcawley** [comment]
Thank you for the workaround.     I found other methods to achieve my end, but it is useful to know that there might be a workaround.  However it does not seem to cover the case where the merged area does not start on the same row.  If the return is undefined, then it is not possible to ask for  properties.

**Comment by Jayshiv-IRIS** [comment]
@billcawley  can you please tell me which method you use?
For my work I also facing same issue .
I only get Top Left cell address of merging.
