### ISSUE TITLE
IOS and Android: client add-in not support prompt for cert selection when using adfs or azure ad intune to doing sso login

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#1592]
the same problem with this one, but it is not Mac outlook client, it is IOS outlook client. https://github.com/OfficeDev/office-js/issues/1347

for android, i have enrolled my android device, but it always show "to enroll your device, install the free Microsoft Intune Company Portal app. -> go to goole play"
![image](https://user-images.githubusercontent.com/1878089/106079055-7816c180-614f-11eb-95b3-9a1861b4d07a.png)

**Comment by hello-chenchen** [comment]
hi @exextoc any update here? we found android outlook also have the same problem here.
when i try to use azure ad (which open the intune device verify, it means need select cert selection on browser). when i use chrome directly, it works fine. and can prompt the certification select. but on android outlook app, it can't do that.
below screenshot is what chrome behavior:
![image](https://user-images.githubusercontent.com/1878089/105329560-3f855e00-5c0c-11eb-825d-b71583833786.png)

**Comment by hello-chenchen** [comment]
hi @lindalu-MSFT @exextoc any update here please?

**Comment by exextoc** [comment]
Bug 1922224<https://o365exchange.visualstudio.com/959adb23-f323-4d52-8203-ff34e5cbeefa/_workitems/edit/1922224>: [OfficeDev/office-js] IOS and Android Outlook: client add-in not support prompt for cert selection when using adfs or azure ad intune to doing sso login (#1592)


Created using VSTS Outlook add-in<https://www.owiki.ms/wiki/VSTS_Add-In_for_Outlook>

Thanks,
Sachin

**Comment by exextoc** [comment]
@hello-chenchen Thank you for reporting this issue. We have added this issue to our backlog and unfortunately have no timelines to share at this point.

**Comment by hello-chenchen** [comment]
thanks @exextoc

**Comment by hello-chenchen** [comment]
hi @exextoc , the same problem with Windows Outlook. it also not support prompt for cert selection.

**Comment by exextoc** [comment]
Can you check if this problem also repros on OWA? If it does not repro in OWA this would also be a Win32 issue, and in that case, please open a separate issue for Win32 so we can track it there as this thread is used to track the Android and iOS side of the problem.

**Comment by hello-chenchen** [comment]
Okay, thanks for the reply. I think that It's a win32 problem.By the same root cause.
I will re-create a new issue for win32.

**Comment by hello-chenchen** [comment]
@exextoc It was automatic closed. We need to re-open.But I don't know how to re-open it. Could you please help us to re-open it?

**Comment by hello-chenchen** [comment]
@exextoc this issue is not fixed, please re-open it.

**Comment by exextoc** [comment]
Hey @hello-chenchen,

We have re-opened this issue as you requested. We are investigating this issue and will keep you updated.

**Comment by exextoc** [comment]
Hey,

We have tracked this bug in our backlog and we are following up on the progress. Unfortunately we have no timelines to share at this point. We are closing this bug since it's moved to backlog.

**Comment by hello-chenchen** [comment]
hi @exextoc , is there any update for this problem?

**Comment by exextoc** [comment]
Unfortunately, this has not been picked up yet. But work is expected to start on it soon.

**Comment by hello-chenchen** [comment]
hi @exextoc , could you please share the Internal tracking id for us?

**Comment by hello-chenchen** [comment]
hi @exextoc , do you have any update for this. if not fixed, please reopen this issue.
