### ISSUE TITLE
[Excel] Context menu control icon defined in manifest does not show in Excel on the Web

### ISSUE THREAD

**Issue by sshukurov** [OfficeDev/office-js#1593]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
Context menu controls' icons must be visible on all supported platforms, including Excel on the Web.

## Current Behavior
Currently the icon gets displayed correctly in Excel for Windows:
![image](https://user-images.githubusercontent.com/36232686/104606283-62aa8d80-56a1-11eb-8280-b5d32343a2fb.png)

This is not the case with Excel on the Web:
![image](https://user-images.githubusercontent.com/36232686/104606396-879f0080-56a1-11eb-8928-4aa26ecc5eb7.png)

You might also notice control labels are repeated in the web version, which is not consistent with the built-in context menu controls as well as those in Excel for Windows.

## Steps to Reproduce, or Live Example
Just upload the manifest from the sample here: [https://github.com/OfficeDev/Office-Add-in-Commands-Samples/blob/master/Excel/Manifest/ExcelAddinWithCommandsOnDataTab.xml](https://github.com/OfficeDev/Office-Add-in-Commands-Samples/blob/master/Excel/Manifest/ExcelAddinWithCommandsOnDataTab.xml)

## My Environment
* Platform: PC desktop
* Host: Excel
* Excel for Windows version number: 2102 Build 13707.20008
* Excel on the web build number: 16.0.13711.31875
* Operating System: Windows 10 Pro Version 20H2 OS build 19042.685
* Browser (if using Office on the web): Google Chrome  87.0.4280.141 (Official Build) (64-bit)

**Comment by zoulou00** [comment]
Any update ? 
I have both problems (repeated labels and icons not loaded)
Thank you

**Comment by donquijotedelamancha** [comment]
This issue continues to reproduce for Excel on the Web. 
Is there any updates on this?

**Comment by ElizabethSamuel-MSFT** [comment]
@sshukurov @zoulou00 @donquijotedelamancha If this is still an issue, please comment and we can reopen. Or you can create a new issue. Thanks.

**Comment by sshukurov** [comment]
@ElizabethSamuel-MSFT not clear why this issue was closed, this is still reproducing for me. Can I ask you to share internal task number for ease of tracking?

**Comment by ElizabethSamuel-MSFT** [comment]
@sshukurov Thanks for letting us know. I'll reopen.

**Comment by ElizabethSamuel-MSFT** [comment]
@preethikakiru Can you take a look? Thanks.
