### ISSUE TITLE
How to hide developer window when performing ribbon or context menu action in OfficeJS Word

### ISSUE THREAD

**Issue by PriyaKatkade** [OfficeDev/office-js#1598]
Hello,

We are using OfficeJS Beta https://appsforoffice.microsoft.com/lib/beta/hosted/office.js to create Word Addin.
Our add-in contains Ribbon and Context menus (Add-in commands). We have created manifest.xml which supports this commands. Function file is there which handles execution for this add-in commands.

When we execute any add-in command(Ribbon button or context menu), it executes the operation as expected on Windows. But on MAC it opens developer window like below which show function file's body content(Function file body never is never displayed). Whenever we execute any add-in command, it show new developer window each time.

![image](https://user-images.githubusercontent.com/24935240/104700502-427add00-573a-11eb-9ede-98068ba3be77.png)

Platform Details-

**MAC Version -** macOS Big Sur 11.1
**Microsoft Word Version -** Microsoft Word 16.45 (21011103)

It will be great if anybody knows how to hide this developer window.

**Comment by pravin-mamdge** [comment]
To hide the Developer Window, run the following command in terminal - 
defaults write com.microsoft.Word OfficeWebAddinDeveloperExtras -bool false

**Comment by PriyaKatkade** [comment]
Thanks @pravin-mamdge.

Command works as expected.
