### ISSUE TITLE
[Outlook] Outlook add-in not enabled for shared mailbox in Windows Outlook 2016 client

### ISSUE THREAD

**Issue by splinter** [OfficeDev/office-js#160]
The add-in  throws an error saying that the add-in scenario is not supported when attempting to activate it for a shared mailbox.

## Expected Behavior
The add-in should be activated or the add-in button should be disabled. Are shared mailboxes supported by add-ins?  We have noticed contradicting behaviour:
- Mac Outlook 2016 - Works
- Outlook online - Activates but some API calls fail
- Windows Outlook 2016 - Add-in visible but does not activate

## Current Behavior
The add-in throws an error saying the add-in scenario is not supported.

## Steps to Reproduce, or Live Example
Load an Outlook add-in and attempt to access it from a shared mailbox

## Context
Our customers who wish to use shared mailboxes have an inconsistent user experience across devices

## Your Environment
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Mac Outlook 2016 (16.12 - 180410), Windows Outlook 2016 (1805)
* Operating System:  Mac High Sierra , Windows 10 
* Browser (if using Office Online): Firefox and Chrome

**Comment by exextoc** [comment]
This question has been answered here: https://github.com/OfficeDev/office-js/issues/159
