### ISSUE TITLE
Function saveAsync does not work after removing item

### ISSUE THREAD

**Issue by Petryxasport** [OfficeDev/office-js#1600]
**Issue:**
Function saveAsync does not work after removing Email and throw the error:
{
   "code": 9021,
   "message": "Connection error occurred while trying to save the item on the server.",
   "name": "SaveError"
}

**Steps to Reproduce**
1. Open add-in in compose mode 
2. call `saveAsync` - Email will be saved as draft item.
3. remove email
4. call again `saveAsync`
5. call fails with following error above

In order to remove item we are using the code below:
  ```
  var deleteRequest =
                        '<?xml version="1.0" encoding="utf-8"?>' +
                        '<soap:Envelope xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"' +
                        '               xmlns:xsd="https://www.w3.org/2001/XMLSchema"' +
                        '               xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"' +
                        '               xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">' +
                        '  <soap:Header>' +
                        '    <RequestServerVersion Version="Exchange2013" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" soap:mustUnderstand="0" />' +
                        '  </soap:Header>' +
                        '<soap:Body>' +
                        '<MoveItem xmlns="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">' +
                        '<ToFolderId>' +
                        '<t:DistinguishedFolderId Id="deleteditems"/>' +
                        '</ToFolderId>' +
                        '<ItemIds>' +
                        '<t:ItemId Id="' + data.MsgId + '" ChangeKey="' + changeKey + '"/>' +
                        '</ItemIds>' +
                        '</MoveItem>' +
                        '</soap:Body>' +
                        '</soap:Envelope>';
                    var mailbox = Office.context.mailbox;
                    mailbox.makeEwsRequestAsync(deleteRequest, deleteMessageCallback);
```

**Environment**
Platform :Office Desktop
Office version number: 365 MSO (16.0.13530.20132) 64-bit
Operating System: windows 10

**Comment by JuaneloJuanelo** [comment]
@Petryxasport  thanks for reporting this. Can you please clarify the scenario?  Why do you want to save an item after you delete it? Are you expecting a deleted item to be saved?  Probably this is by design.

**Comment by Petryxasport** [comment]
> @Petryxasport thanks for reporting this. Can you please clarify the scenario? Why do you want to save an item after you delete it? Are you expecting a deleted item to be saved? Probably this is by design.

Yes, our clients expect that we save Email again as new one. Scenario is:
1. Client click on the Reply
2. Then clients open add-in and use it. 
3. Then save Email with information using add-in in enother system. ((add-in calls SaveAsync to get Email id and recive stream from server side).
4. Then clients can send Email or close it. In case of closing we have to remove Email.

Outlook API does not provide an event to handle closing of Email and we have to remove each time Email to avoid collection of Email in Draft folder after clients' activities.
 As result sometimes clients save Email in other system via add-in  then our add-in remove email and then client would like to send again the same Email. Here we receive the issue. 
As hot fix we removed deleting part, but client annoying to have a lot of Emails in draft folder.

**Comment by exextoc** [comment]
Thank you for the clarification of your scenario. 

Currently, the feature of knowing if an e-mail is closed or sent, you requested, is not a part of the product. The saveAsync API was not designed for this scenario, and if there is no item, it is expected to fail. We track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered, when we go through our planning process.

**Comment by thao33** [comment]
@Petryxasport 
> Outlook API does not provide an event to handle closing of Email 

yes, but you can using `Office.context.ui.closeContainer()` instead. It's worked for me.
