### ISSUE TITLE
Office Version reported as 0.0.0.0

### ISSUE THREAD

**Issue by paulfrench** [OfficeDev/office-js#1602]
# Issue

Running online Excel using Addin in shared runtime.

I check the properties:

- Office.context.diagnostics.version
- Office.context.diagnostics.platform

..and they are reported as:

- 0.0.0.0
- OfficeOnline

 ## Expected Behavior

The actual online version of office.js should be reported and not 0.0.0.0

## Current Behavior
Office.context.diagnostics.version=0.0.0.0

## Steps to Reproduce, or Live Example

`
Office.onReady(() => {
  console.log(JSON.stringify(Office.context.diagnostics))
});
`
...outputs the following...
`
{"host":"Excel","version":"0.0.0.0","platform":"OfficeOnline"}
`
# Platform
**Browser Name**    Chrome
**Browser Version**  87.0.4280.141
**Office JS**    https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js

Where can I get the version from if not from here?

**Comment by JuaneloJuanelo** [comment]
You are checking for this parameter in Excel for the Web  who is always on latest version
