### ISSUE TITLE
Remove IE11 as default browser for desktop Excel in shared runtime

### ISSUE THREAD

**Issue by paulfrench** [OfficeDev/office-js#1603]
When can we expect IE11 to be removed as the default browser in desktop Excel when using the javascript shared runtime? It's a massive pain having to make your Addin work in IE11 since a lot of frameworks have dropped support for IE11 and polyfills do not exist for all the newer browser features e.g. new CSS stuff etc

**Comment by smaremanda** [comment]
@paulfrench I understand your feedback on IE11.
We are getting ready to rollout support for WebView2 over the next several weeks. This will likely start with the November fork of Office. For Office versions numbers and corresponding browser support you can see this page here: https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins
Please note that you will need the WebView2 runtime downloaded and deployed on the local machine for Office to be able to use WebView2.
Does that help?

**Comment by paulfrench** [comment]
@smaremanda that is good news.

Does this also help with Office Store submissions? Currently I cannot submit my Addin unless it works on all platforms and that currently means IE11 in desktop Excel as well as safari on Mac/IOS ?

It's crazy we are forced to support many platforms which we have no plans to support ourselves e.g. IOS

Basically my problem is I want to submit an Addin to the Office Store that will only be used in online Excel or desktop Excel (running on windows connected to an Office 365 subscription). It's a Addin that is used to provide further integration into our product for our customers (and so is free).

Removing IE11 is a big help since we can use the latest and greatest frameworks etc without the pain of trying to support IE11.

So I suppose the question is how will the criteria for Addin submission to the Office Store change when we have the ability to target WebView2 ?

**Comment by paulfrench** [comment]
Also looking at the link you supplied, point 3 is applicable to me...

`If your add-in includes the Runtimes element in the manifest, it uses Internet Explorer 11 regardless of the Windows or Microsoft 365 version. For more information, see Runtimes.`

Is this restriction going away since I do use a shared runtime?

**Comment by keyur32** [comment]
Hey @paulfrench, yes, if webview2 is available, we will use that for the shared runtime as well, instead of the IE11 runtime. Thanks!

**Comment by keyur32** [comment]
I'm going to mark this as closed but please do let us know if you have any issues with webview2 control or if you have any other questions.

**Comment by paulfrench** [comment]
> @paulfrench I understand your feedback on IE11.
> We are getting ready to rollout support for WebView2 over the next several weeks. This will likely start with the November fork of Office. For Office versions numbers and corresponding browser support you can see this page here: https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins
> Please note that you will need the WebView2 runtime downloaded and deployed on the local machine for Office to be able to use WebView2.
> Does that help?

When you say November, do you mean November 2021 coming or the November release of Office last year will be forked and so we will get WebView2 support in the next few weeks?

**Comment by keyur32** [comment]
November was when we forked the code and got the build ready.  It should be rolling out to customers on the current channel within the next few weeks! Thanks.  @smaremanda  can confirm once that build that has it has been rolled out :)

**Comment by schmitch** [comment]
@keyur32 will there be a time when WebView2 Runtime is bundled with Office365 or at least will get installed with it while running the installer or be distributed with windows.
It's such a pain to actually **force** people to use install the WebView2 runtime.

Or at least it would be a breeze to support store submissions where users **need** to install WebView2 to install the addin. i.e. make use of the Runtime element more...
