### ISSUE TITLE
Feature displayDialogAsync add an action parameter to the url which break google oauth flow

### ISSUE THREAD

**Issue by vddgil** [OfficeDev/office-js#1604]
## Expected Behavior
When opening a dialog for google oauth, displayDialogAsync shoudn't add any params to the given url

## Current Behavior
displayDialogAsync add a param "action=dialogOpen" which break google oauth flow
See screenshot: 

![Screenshot](https://d3dehtdmp2rwcw.cloudfront.net/ms_40099/1LI635HSHWxf3kq22xOymQ4La2GuJD/Office%2BAdd-ins%2B-%2Baccounts.google.com%2B2021-01-19%2B13-01-54.png?Expires=1611059400&Signature=cZDsq7jMO6TxFI-diGp2Cs1VknK8IRUXjIaT5vJ3~2HIoQSdTGdBal9nxKJdWctuNtn0d3Fc14m-PRIVuCeb3QoYoqQqqkkJaaGpsqJpnY8nLk6LRLuCyNELnm1nxL9ujuilgZUMq12lYx9jfcglljLCHH6TkCFWER2cUjr1QR26kDfPHbBYjSvPBxgMpZviKa2mmxsVYw0ssNdaReuaCijMN4BPbTD~OFutUOPFj~JMgqtbWyzGCuLST7I03fGCxPYbQVryfujD~XUMTSVYgKMWanrHioqEjFG0dcWwN9SS~32iN2k6VClwyg5JVTpRRpU6dHIDv66Nob2~u0ynVQ__&Key-Pair-Id=APKAJBCGYQYURKHBGCOA)

**Comment by lliu113** [comment]
@vddgil thanks for reporting this! Can you provide a little more info to help us repro - which app and browser are you seeing this on?

**Comment by vddgil** [comment]
@lliu113 Hello ! It's on outlook, i'm one macOS, thats pretty simple to reproduce, just open a dialog with displayDialogAsync and you will see that the method add an extra parameter "action=dialogOpen" in the url. Which is actually not a big deal, except for google oauth flow wich is very strict regarding url parameters (see screenshot).

There is an old issue on the following repo => https://github.com/OfficeDev/office-js-helpers/issues/83.
This is the same issue, as the lib use displayDialogAsync from office-js.

Thanks in advance !

**Comment by lliu113** [comment]
@vddgil appreciate the clarification - let me circle back internally and figure out what's happening.

**Comment by lliu113** [comment]
@vddgil our team is looking into this. While we investigate, is it possible for you to redirect to a page on your app domain first and then redirect to the google auth page? Doing so should hopefully unblock you in the meantime. 

https://docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api#authentication-flow-with-the-office-dialog-box
