### ISSUE TITLE
Body content style changed after inserting html from Outlook add-in on Mac

### ISSUE THREAD

**Issue by liwei118** [OfficeDev/office-js#1605]
## Expected Behavior
After inserting html to the top of mail body content from Outlook add-in on Mac, part of the beginning of original body content is not changed.

## Current Behavior

After inserting html to the top of mail body content from Outlook add-in on Mac, part of the beginning of original body content is wrapped with <span style="color:white"></span> tag.

## Steps to Reproduce, or Live Example

            Office.context.mailbox.item.body.setAsync(
              `
              <div style='margin-bottom:10.0pt;margin-top:5.0pt;'>
              
              <table cellspacing='0' cellpadding='0' style='border:solid #F4F4F4 1.0pt;padding:12pt;font-family: Segoe UI;'>
              <tbody>
                <tr>
                  <td width='69' valign='top'>
                  <img width='54' height='54' src="https://img.png" crossorigin="anonymous">
                  </td>
                  <td width='1897' valign='top' >
                  <p><b>Starbucks</b></p>
                  <p style='margin-top:8.0pt'>Hi! wei ordered coffee for you. If you want to change your coffee option or decline the coffee, click
                  <b><a href="https://1213#}">Here</a></b> before 8AM of meeting day.</p>
                  <p style='margin-top:15.0pt;'>Tips: You can also s.</p>
                  </td>
                </tr>
                </tbody>
              </table> 
              </div>
              `+ newDom.outerHTML , { coercionType: Office.CoercionType.Html }
            )
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: _____Mac_、Windows
* Host [Excel, Word, PowerPoint, etc.]: ______outlook
* Office version number: ____ Office2019 on Windows_  Office  16.46 on Mac 
* Operating System: ___Windows10    MacOS big sur ___
* Browser (if using Office on the web): ______

## Useful logs

![image](https://user-images.githubusercontent.com/42823739/105149219-45ad0900-5b3e-11eb-8b76-75d605997ae9.png)

**Comment by exextoc** [comment]
Is this issue happening on both Mac and Windows?In Mac is it happening on old UI or new UI?
I tried reproducing this issue on Mac but was not able to reproduce it .Can you please elaborate  the repro steps with sample code for both scenario?

**Comment by liwei118** [comment]
old UI  
repro steps:
https://21vms-my.sharepoint.cn/:v:/g/personal/v-rehong_21vms_partner_onmschina_cn/EVDwczSMO5NFpe5r42LRnmkBYo6eaIXjglC0Ss-_UFOC7w?e=STYzWr

**Comment by exextoc** [comment]
We tried to reproduce this issue with sample code shared above on Mac(Old UI) and windows but could not able to reproduce this issue .Can you please share the manifest which you are using to reproduce this issue?

**Comment by liwei118** [comment]
manifest：
 https://sbux-outlook.chinacloudsites.cn/manifest.prod.xml

**Comment by exextoc** [comment]
Manifest which you shared require QR Code to login .Can you please share the exact sample code in Add-in which you are running .I tried with sample code shared above but newDom was not defined in that sample code and we are not able to run it .

**Comment by liwei118** [comment]
You may scan the QR Code and click "link" button on the page it opens, then you should be able to test. It is just a demo, the login process will only store your email address and a randomly generated GUID. thanks.

**Comment by exextoc** [comment]
We are able to repro the issue. Thanks for reporting it. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
To help us repro in Outlook for Windows, could you provide the Outlook version number (I see Outlook 2019 is mentioned above, but without the full version number).

In addition, could you update the repro steps with what the value for `newDom` should be? Being able to reproduce the issue outside of your add-in will help us fix the issue. Thanks.

**Comment by liwei118** [comment]
verison:
<img width="372" alt="815b62c881ea4c4839d26ca6b48a5c1" src="https://user-images.githubusercontent.com/42823739/106223720-eecdc080-621c-11eb-95ba-a842ca748675.png">
![36204d42-1d4c-4c9b-b533-b84a62c04a9e](https://user-images.githubusercontent.com/42823739/106224883-0b6af800-621f-11eb-8636-49ba664fb7d6.jpg)

**Comment by exextoc** [comment]
For win-32 Outlook, we were unable to repro the bug you are seeing. Are you reproing this issue in Outlook win-32? If so, can you confirm the build of Outlook win-32 you are seeing this issue on? Are you seeing this on Version 2101, Build 16.0.13628.20274 as per your screenshot or on Outlook 2019?
