### ISSUE TITLE
[Outlook] [Onsend addin] Unable to read MIP Labels through get internet headers API in onsend addin

### ISSUE THREAD

**Issue by Premsagar-lab** [OfficeDev/office-js#1606]
We have use case of checking if the emails being sent have applied MIP Labels as configured. We tried to read using the Office.context.mailbox.item.internetHeaders.getAsync() method but it fails to provide the labels. We found that the MIP labels are applied on the email after invocation of Onsend addin hence addin cannot get that headers. 

## Expected Behavior

Labels should be applied before the onsend addin is invoked so that we can read internet headers on mail being sent.

## Current Behavior

Labels applied after onsend addin is invoked

## Steps to Reproduce, or Live Example

1. Configure MIP Labels for the emails.
2. Add the Onsend addin to check email which can read internet headers for composed email.
3. Compose a email with keywords and policy so that required Label can be applied.
4. Send the email.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __Mac____
* Host [Excel, Word, PowerPoint, etc.]: __Outlook____
* Office version number: __16.43____
* Operating System: ___Bigsur___
* Browser (if using Office on the web): ___Safari___

**Comment by exextoc** [comment]
One which Mac UI are you seeing this issue:-Old or New UI?

**Comment by Premsagar-lab** [comment]
@exextoc We are seeing this on Old UI. New UI does not support Onsend addin.

**Comment by exextoc** [comment]
@Premsagar-lab  Could you please help us understand more about the scenario here and why On-send Add-in needs access to internet headers?

**Comment by Premsagar-lab** [comment]
@exextoc We check the email contents when the email is being sent. If content has some sensitive content as per the policy of the enterprise then we have to apply the sensitive MIP tags as configured by enterprise. 

It is possible that the user had already selected a MIP label for the email. We wanted to retrieve the MIP label and check if its in accord with the configured policy. Also, if user has not applied then apply the MIP Label. 

Are there any direct api to read the MIP label in Onsend addin ? We didnt find any.
So we wanted to read those through internet headers api.

**Comment by exextoc** [comment]
internetHeaders.getAsync is intended to return the values of the custom headers you set using the setAsync method. So, the API is not designed to get the headers set using Sensitivity labeling in compose mode. 
Unfortunately, we don't have an API to read the MIP label in Compose mode.
Can the On-send Add-in add the label anyway(without checking if the user has already added it) before send and save? 
We are curious to know how is this scenario working for you on other platforms like Web and Windows?

**Comment by Premsagar-lab** [comment]
@exextoc We are adding the MIP label by setting the internet header "msip_labels" with value in the format "MSIP_Label_8cdfea29-c7dd-4d85-bd07-f0b0c7031a36_Enabled=true;
 MSIP_Label_8cdfea29-c7dd-4d85-bd07-f0b0c7031a36_SiteId=3973ce53-0d96-4385-b58b-68fda2fc4865;
 MSIP_Label_8cdfea29-c7dd-4d85-bd07-f0b0c7031a36_ActionId=87d0f5bb-0f22-4cde-85b3-0f49075f2a4c;
 MSIP_Label_8cdfea29-c7dd-4d85-bd07-f0b0c7031a36_Method=Privileged;
 MSIP_Label_8cdfea29-c7dd-4d85-bd07-f0b0c7031a36_ContentBits=0;
 MSIP_Label_8cdfea29-c7dd-4d85-bd07-f0b0c7031a36_Name=Confidential;
 MSIP_Label_8cdfea29-c7dd-4d85-bd07-f0b0c7031a36_SetDate=2021-02-04T09:40:30Z;" 

We use tenant id and client id to create the value of mip header.
Is this the correct way to apply the label or can we get this string from MIP SDK?

**Comment by exextoc** [comment]
Can you confirm if this suggestion works for you - the On-send Add-in add the label anyway (without checking if the user has already added it) before send and save.
You can use setAsync API for this

**Comment by Premsagar-lab** [comment]
@exextoc No.. it does not work in scenario when already label has been applied. Let say if "internal" was applied by the user and according to policy we wanted to apply "confidential". But it is not applied with setAsync.

**Comment by exextoc** [comment]
Currently the feature you requested is not available. We track Outlook add-in feature requests on our [ user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered when we go through our planning process

**Comment by Premsagar-lab** [comment]
hello @exextoc, we will be requesting on user-voice page. 
Can we send EWS request from Outlook Add-In to fetch the MIP Label for the mailbox item after saving the email? 
Or we can read the internet headers from ews?

**Comment by exextoc** [comment]
Closing this as we're communicating on the second question via this link

https://github.com/OfficeDev/office-js/issues/1673
