### ISSUE TITLE
mailbox.makeEwsRequestAsync get error on shared calendar

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1607]
I just trying use 'makeEwsRequestAsync' to get Extend properties.
Just wonder can this API running on a shared calendar. 
When I trying this api on a shared calendar (have Editor permission on 'Calendar' and 'Tasks') it report me 'Office extension have no permission to access any other mailboxes then the mailbox provided in the user context.'

## Expected Behavior
makeEwsRequestAsync can run on shared calendar.

## Current Behavior
get an error response says ''Office extension have no permission to access any other mailboxes then the mailbox provided in the user context.'

## Steps to Reproduce, or Live Example
* 1. save extend properties by COM.
2. trying call makeEwsRequestAsync getting extend properties on add-in.
3. get no valid response. Just an error...

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

I can't get Extend properties on shared calendar. But wonder if ews can't get Extend properties on shared calendar can GRAPH api do this?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ALL
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Mac 16.42 (20101102)
* Operating System: Mac Windows and web
* Browser (if using Office on the web): Chrome,IE

## Useful logs
response error:
`<?xml version=\"1.0\" encoding=\"utf-8\"?><s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"><s:Header><h:ServerVersionInfo MajorVersion=\"15\" MinorVersion=\"20\" MajorBuildNumber=\"3763\" MinorBuildNumber=\"15\" Version=\"V2018_01_08\" xmlns:h=\"http://schemas.microsoft.com/exchange/services/2006/types\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"/></s:Header><s:Body><m:GetItemResponse xmlns:m=\"http://schemas.microsoft.com/exchange/services/2006/messages\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:t=\"http://schemas.microsoft.com/exchange/services/2006/types\"><m:ResponseMessages><m:GetItemResponseMessage ResponseClass=\"Error\"><m:MessageText>Office extension have no permissions to access any other mailboxes then the mailbox provided in the user context.</m:MessageText><m:ResponseCode>ErrorAccessDenied</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:Items/></m:GetItemResponseMessage></m:ResponseMessages></m:GetItemResponse></s:Body></s:Envelope>`

**Comment by exextoc** [comment]
We does not support EWS in Delegate scenario .Follow this document for more information :-https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access.
REST API, however, works! We made server changes specifically for this.

**Comment by SWei1234** [comment]
Thanks for your reply. @exextoc 
Will try use other ways on shared calendar.
