### ISSUE TITLE
Undo operation with Office-js 

### ISSUE THREAD

**Issue by gerrychong** [OfficeDev/office-js#1608]
How do I undo an operation done by Office. Js to Excel?

**Comment by lumine2008** [comment]
Thanks for your post, unfortunately, office JS currently does not support undo. I would suggest that you could vote in the [uservoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/10754784-fix-the-issue-with-new-javascript-api-for-excel-a) 

meanwhile, would you please also share your scenario?

**Comment by gerrychong** [comment]
> Thanks for your post, unfortunately, office JS currently does not support undo. I would suggest that you could vote in the [uservoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/10754784-fix-the-issue-with-new-javascript-api-for-excel-a)
> 
> meanwhile, would you please also share your scenario?

In fact, everyday scenarios already have a lot of undo operations,It shouldn't be Office. JS to support it, it should be Excel to record it and then undo it....

**Comment by gerrychong** [comment]
> > Thanks for your post, unfortunately, office JS currently does not support undo. I would suggest that you could vote in the [uservoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/10754784-fix-the-issue-with-new-javascript-api-for-excel-a)
> > meanwhile, would you please also share your scenario?
> 
> In fact, everyday scenarios already have a lot of undo operations,It shouldn't be Office. JS to support it, it should be Excel to record it and then undo it....

I think that's a very important thing to do, rather than having users vote on it.

**Comment by lumine2008** [comment]
Thanks, the reaon that this workitem hasn't get the priority is that the cost is super high plus VBA currently don't support it. 

Can you please share us your scenario, we have an idea, but we would like to see if this could help in your scenario or not.

**Comment by stenly311** [comment]
The user's voice is no longer available (the hyperlink from above seems to be dead). 

I would like to see some way of driving history changes as Garry mentioned via the Office.js library.
Moreover, having the option to reset (delete) the history would be the one I would find very useful for my use case.

Is there any chance to add this as a new feature into the next release, please?

**Comment by 4tti** [comment]
Added https://feedbackportal.microsoft.com/feedback/idea/0f5caa5a-32e7-ec11-a81b-000d3a00c008
