### ISSUE TITLE
[OUTLOOK FOR MAC] getAttachmentContentAsync() returns '7000' error in "New Outlook" 16.45 for macOS Big Sur

### ISSUE THREAD

**Issue by HackerM00n** [OfficeDev/office-js#1610]
The getAttachmentContentAsync() method can't get the attachment value. This bug appears only in “New Outlook” for macOS Bug Sur. If I switch back to "Old Outlook" it disappears. It also doesn't appear in WEB / Win 10 Outlook.

## Expected Behavior

Attachment successfully loaded, base64 can be obtained from result.value.content.

## Current Behavior
Attachment not loaded:
**code:** 7000
**message:** "You don't have sufficient permissions for this action."
**name:** "Permission Denied"

## Steps to Reproduce
1. Switch to "New Outlook"
<img width="146" alt="image" src="https://user-images.githubusercontent.com/43299774/105627980-be63dc00-5e42-11eb-9d7d-5ebedbfdd7ce.png">
2. Paste code:

    const firstAttachment = Office.context.mailbox.item.attachments[0];

    Office.context.mailbox.item.getAttachmentContentAsync(
        firstAttachment.id,
        {},
        function(result) {
          console.log(result);
        }
    );

3. Select an email with at least one attachment.
4. Open add-in.
5. View console.

## Context

I use the getAttachmentContentAsync() method to get attachments by their ID after the user selects them.

Outlook REST API (https://outlook.office.com/api/v2.0/me/messages/{message_id}/attachments/{attachment_id}) isn't an option because it has limitation on 4 requests at one time. 

Of course, I can preload attachments using one request (https://outlook.office.com/api/v2.0/me/messages/{message_id}/attachments/), but that will significantly slow down the add-in.

## Your Environment

* Platform: MacBook Pro (13-inch, 2019, Four Thunderbolt 3 ports)
* Host: Outlook for Mac 16.45 (21011103)
* Office version number: 16.45
* Operating System: macOS Big Sur 11.1 (20C69)

## Useful logs

- [x] Screenshots
<img width="493" alt="image" src="https://user-images.githubusercontent.com/43299774/105628087-8741fa80-5e43-11eb-982e-4f1118e2cd36.png">

**Comment by exextoc** [comment]
getAttachmentContentAsync is part of 1.8 API which is currently not supported on new Outlook on Mac. Here is the link:
[https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/compare-outlook-add-in-support-in-outlook-for-mac#new-outlook-on-mac-preview](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/compare-outlook-add-in-support-in-outlook-for-mac#new-outlook-on-mac-preview)

**Comment by HackerM00n** [comment]
> getAttachmentContentAsync is part of 1.8 API which is currently not supported on new Outlook on Mac. Here is the link:
> https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/compare-outlook-add-in-support-in-outlook-for-mac#new-outlook-on-mac-preview

What method would you recommend to get attachments by their id without limiting the number of requests? 
Do you have an estimated date when API 1.8 will be supported in "New Outlook" for macOS?

**Comment by exextoc** [comment]
We are targeting Mar '21 for GA of 1.8 API, but you can sign up for Insiders to get an earlier build which we are expecting to release by end of Feb.

**Comment by margielovelet** [comment]
Hi, do we have any updates on this one? Our client is using Microsoft Outlook for Mac version 16.47 and the getAttachmentContentAsync is still not working as expected. Thank you.
