### ISSUE TITLE
[OUTLOOK FOR MAC] saveAsync() returns '5000' error in New Outlook on macOS Big Sur

### ISSUE THREAD

**Issue by jurisjansons** [OfficeDev/office-js#1611]
Using office.js method `Office.context.mailbox.item.saveAsync()` returns error in callback response. Same code works fine when switching off New Outlook toggle button.

## Expected Behavior
returns object with property value which contains id of the event

## Current Behavior
return object with error

## Steps to Reproduce, or Live Example

1. Create add-in which uses `Office.context.mailbox.item.saveAsync()` method.
2. Switch to "New Outlook"
2. Open new event
3. Save this event using add-in from step one
4. Callback will return error

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook for Mac
* Office version number: 16.45
* Operating System: macOS Big Sur 11.1

## Useful logs
`{"status":"failed","error":{"name":"Host Error","message":"The operation is not supported.","code":5000}}`

**Comment by exextoc** [comment]
Currently, saveAsync is not supported in New Outlook Mac in Event Compose. This document has information:
[https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/compare-outlook-add-in-support-in-outlook-for-mac#new-outlook-on-mac-preview](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/compare-outlook-add-in-support-in-outlook-for-mac#new-outlook-on-mac-preview)

**Comment by jurisjansons** [comment]
@exextoc is there a way to tell if user currently in "New Outlook Mac" or "Outlook Mac" to show some notification for them? And is "by design" the right tag for this? Are you guys planning implementing this feature and maybe can share road map?

**Comment by exextoc** [comment]
1)is there a way to tell if user currently in "New Outlook Mac" or "Outlook Mac" to show some notification for them? 
Could you please explain the requirement ? Did it means an API exposed to support this notification ?
2)And is "by design" the right tag for this? Are you guys planning implementing this feature and maybe can share road map?
We are tracking this work item internally and we will update this thread when we have updates.

**Comment by jurisjansons** [comment]
1) Is there a way to tell if user opens Add-In from "New Outlook Mac". I will handle notification, I just need a way to tell who is using "New Outlook Mac"
2) Hope for fast resolution. It's a critical feature for us

**Comment by exextoc** [comment]
@jurisjansons 

(1) We don't have any API to detect if it is "Old Outlook Mac" or "New Outlook Mac". But, we believe a better way for add-in is to check which API set is supported and make decisions based on that. Example:

if (Office.context.requirements.isSetSupported('Mailbox', '1.8')) {
   // API set 1.8 is supported
}
else {
   // API set 1.8 is NOT supported
}

Will this work for you?

(2) For saveAsync() not working in "New Outlook Mac": Will this workaround work for your use-case? https://docs.microsoft.com/en-US/outlook/troubleshoot/calendars/cannot-save-meeting-as-draft-in-outlook-for-mac

**Comment by jurisjansons** [comment]
Thank you for your help, will look what I can do with API set. As of workaround it will not work in our case. Hoping that this will be resolved soon. 
Good luck!
