### ISSUE TITLE
Outlook Online, IE, the setSelectedDataAsync() method does not work after cleaning an email body

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1612]
In an Outlook add-in for compose mode, we are using the Office.context.mailbox.item.body.setSelectedDataAsync method to insert HTML into a message body. In Internet Explorer, the method stops working if you clean the message body manually.

## Expected Behavior
The setSelectedDataAsync method shall work correctly.

## Current Behavior
The setSelectedDataAsync method does nothing after cleaning the message body. Though, it returns succeeded in the callback result.

## Steps to Reproduce, or Live Example
1) Sign in to Outlook Online using Internet Explorer, create a new email and execute the following code:

`Office.context.mailbox.item.body.setSelectedDataAsync(`
`  '<p>line 1</p><p>&nbsp;</p>',`
`  { coercionType : 'html' },`
`  function (result) { console.log(JSON.stringify(result)); }`
`);`

2) Select all the content in the message body by using mouse (mouse - it is important) and delete it by using Backspace or Delete key.

3) Execute the code above again – nothing was inserted into the message body but you will see {"value":null,"status":"succeeded"} in the console.

* Link to live example: 
You can try our sample add-in but I hope the code and steps above are clear enough:
https://online-addins.ablebits.com/testaddin/manifest.xml

* Additional details:
  1. It seems only IE is affected, we cannot reproduce the same issue in other browsers.

## Your Environment
* Platform: Office on the web
* Host: Outlook
* Office version number:
* Operating System: Windows 10 1909 (18363.1316) and Windows 10 20H2 (19042.746)
* Browser (if using Office on the web): Internet Explorer 1909 (18363.1316) and Internet Explorer 20H2 (19042.746)

BTW, what happened with the About window in IE - why OS version info is shown there?

**Comment by exextoc** [comment]
We are able to repro the issue. Thanks for reporting it. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Hey, 

We do not support IE anymore. Please switch to modern browsers like Edge and do get back to us if the issue persists.
