### ISSUE TITLE
Outlook Online, Safari, the getAccessToken method returns 13001 error code

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1613]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

In an Outlook add-in for compose mode, we are using the OfficeRuntime.auth.getAccessToken method to take advantage of the SSO capabilities. In Safari, the method returns the following error:
{"name":"No user is signed into Office.","message":"No user is signed into Office.","code":13001}

The issue is quite weird because I’m signed in to Outlook Online, I see my emails, I can reply/send/etc.

## Expected Behavior
The getAccessToken method should work as it does in other browsers.

## Current Behavior
The getAccessToken method returns 13001 error code in Safari

## Steps to Reproduce, or Live Example
Sign in to Outlook Online using Safari, create a new email and execute the following code:

`function` getAccessTokenTest() {`
`  OfficeRuntime.auth.getAccessToken({ allowConsentPrompt: true, allowSignInPrompt: true })`
`    .then(function (result) { console.log('OK', result); })`
`    .catch(function (err) { console.log('FAILED', err); })`
`}`

You will get the following error in console:
{"name":"No user is signed into Office.","message":"No user is signed into Office.","code":13001}

* Link to live example:
You can try our sample add-in, please see the "OfficeRuntime.auth.getAccessToken" button:
https://online-addins.ablebits.com/testaddin/manifest.xml

* Additional details:
  1. It seems it is the Safari-specific bug.

## Your Environment
* Platform: Office on the web
* Host: Outlook
* Office version number:
* Operating System: macOS Big Sur Version 11.1
* Browser (if using Office on the web): Safari Version 14.0.2 (16610.3.7.1.9)

**Comment by DmitryKostochko** [comment]
Do you have any news about the issue?

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding getAccessToken. It has been put on our backlog. We unfortunately have no timelines to share at this point
 
Internal tracking id: 106308

**Comment by stringbean** [comment]
We are also having the same issue with an add-in that we are developing. Attempting to call `OfficeRuntime.auth.getAccessToken` results in an error 13001 even if the user has just authenticated.

Disabling 'Prevent cross-site tracking' in the Safari preferences and restarting the browser does allow the request to work but this isn't a viable option for a public add-in.

**Comment by marwankhalili** [comment]
Same issue here. `OfficeRuntime.auth.getAccessToken` and `Office.context.auth.getAccessTokenAsync` both seem to rely on third party cookies, probably a cookie from `login.microsoftonline.com`. 

I haven't found a workaround yet that works with third party cookies disabled.

**Comment by victordas** [comment]
code: 13001

message: "No user is signed into Office."

name: "No user is signed into Office."

Still got the erron on Safari, and your AppSource teams blocks submission without Safari Support.
How to get my add-in published ?
