### ISSUE TITLE
Taskpage close automatically after long time inactive

### ISSUE THREAD

**Issue by kullachoke-bosuwan-rft** [OfficeDev/office-js#1614]
Hi, the issue has been raised by our QA team. The taskpane close itself after left inactive for 1-2 hours, or after pc wake from sleep mode. There are some errors in dev console, I've attached the screen shot below. I've tested and able to reproduce the issue. It happens on script lab add-ins too.

## Expected Behavior
Taskpane should not close itself without user action.

## Steps to Reproduce, or Live Example
1. Open script lab taskpane
2. Left it inactive for 1-2 hours

## Your Environment
* Platform: Office on the web
* Host: Excel
* Office version number: ______
* Operating System: OSX, Windows
* Browser (if using Office on the web): Tested on Chrome, Edge and IE11

## Useful logs
![Screen Shot 2564-01-26 at 12 22 28](https://user-images.githubusercontent.com/64405659/105806702-03b91280-5fd7-11eb-975f-9cdefbd0c801.png)
![Screen Shot 2564-01-25 at 16 35 05](https://user-images.githubusercontent.com/64405659/105806750-1df2f080-5fd7-11eb-9876-60d95dbad301.png)

**Comment by AbidRahman-MSFT** [comment]
Hey @kullachoke-bosuwan-rft , 

Thank you for bringing this to our attention, we are internally tracking this issue with #3995826. This feature is in our backlog, however, at the moment, I don't have a timeline I can share with you.

Thanks,
Abid

**Comment by kullachoke-bosuwan-rft** [comment]
@AbidRahman-MSFT 

Thank you for letting me know. It's alright, This is not a critical issue on our add-in. At least, we have a ticket for tracking issue.

Thanks.

**Comment by lliu113** [comment]
@kullachoke-bosuwan-rft  - +1, thanks for reporting this! As Abid mentioned, this is on our backlog. I'll go ahead and close this issue, please reactivate if you have any additional questions/concerns. 

Thanks!

**Comment by Henryz2023** [comment]
This issue is fixed. I will roll out to production a little later.
