### ISSUE TITLE
Outlook for Mac new UI hostVersion is incorrect

### ISSUE THREAD

**Issue by Byron-Mo** [OfficeDev/office-js#1616]
Outlook for Mac new UI's hostVersion returns the version of the Exchange Server instead of the version of the host application. This is not the case on Outlook for Mac old UI.

Documentation states (https://docs.microsoft.com/en-us/javascript/api/outlook/office.diagnostics?view=outlook-js-1.8#hostVersion):
`If the mail add-in is running in Outlook on a desktop or mobile client, the hostVersion property returns the version of the host application, Outlook. In Outlook on the web, the property returns the version of the Exchange Server`

Outlook for Mac new UI returns 16.0.124.1000
![image](https://user-images.githubusercontent.com/14811552/105921669-07a45f00-5fee-11eb-9c4d-d11e193deb35.png)

Outlook for Mac old UI returns 16.46 (21012403)
![image](https://user-images.githubusercontent.com/14811552/105921683-0d9a4000-5fee-11eb-8308-bf114e902519.png)

## Expected Behavior

Outlook for Mac new UI's hostVersion should return the host application version number

## Current Behavior

Outlook for Mac new UI's hostVersion returns the Exchange server version

## Context

We need to correctly detect the version of Outlook for Mac to add messaging for our customers

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook for Mac
* Office version number: 16.46
* Operating System: macOS Big Sur 11.1

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding the host version. It has been put on our backlog. We, unfortunately, have no timelines to share at this point 

Internal tracking id: Office: 2671822

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in next build. When an updated build is available depends on the release channel a customer is on.
