### ISSUE TITLE
How to apply text highlight color and Strikethrough of Paragraph in Word Addin using Angular 11

### ISSUE THREAD

**Issue by vinodifour** [OfficeDev/office-js#1617]
![forum2](https://user-images.githubusercontent.com/37571552/105987915-f2e6ca80-60c4-11eb-880f-df744e6b49e3.png)
As per show in the image ,I want to make text "Test1234" highlight and Strikethrough of Paragraph in Word Addin using Angular 11.
Here paragraph exists in the Content control. Here I am getting text and all other properties from word document using addin , but unable to apply background color and strikethrough.
- **Tested code :-**  I have checked with below code but not getting output, and in **paragraphAfterLast.text** , I'm getting "Test1234" text.
paragraphAfterLast.font.set({
                    highlightColor: "#fcc1ca",
                    strikeThrough: true
                    });

**Comment by AbidRahman-MSFT** [comment]
Thanks @vinodifour for posting the issue.

Thank you @yihuax for looking into the issue, @vinodifour, please try the following:

Suppose you want to set the highlight color and strike through of the paragraph where your cursor is in, you can run (I used Script Lab) the javascript below and it works correctly:

$("#run").click(() => tryCatch(run));

async function run() {
  await Word.run(async (context) => {
    var par = context.document.getSelection().paragraphs.getFirst();  // get the first paragraph in case multiple paragraphs are selected
    var ft = par.font;
    ft.highlightColor = "Yellow";
    ft.strikeThrough = true;
    await context.sync();
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    OfficeHelpers.UI.notify(error);
    OfficeHelpers.Utilities.log(error);
  }
}

Please let us know if the above works as expected for you.
