### ISSUE TITLE
Desktop App Web Viewer does not load and web add-ins do not load

### ISSUE THREAD

**Issue by splinter** [OfficeDev/office-js#1618]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We have an encountered a scenario where no web add-ins load on a user's machine. This is caused by the fact that the Desktop App Web Viewer process does not start up. 

## Expected Behavior
The web add-ins should load and be usable

## Current Behavior
The taskpane web add-in remains blank with an error message saying that the add-in could not be loaded.

## Steps to Reproduce, or Live Example
1. Install a web add-in
2. Open the web add-in

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]:  PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook 2016 16.0.13530.20368 64 bit
* Operating System: Windows 10 10.0.19042 Build 19042

**Comment by croicu** [comment]
Hi, can you try to run from an elevated command prompt:

powershell Add-AppxPackage -register -disable c:\windows\SystemApps\Microsoft.Win32WebViewHost_cw5n1h2txyewy\AppxManifest.xml

**Comment by splinter** [comment]
Hi @croicu ,

I just wanted to ask two questions:
1. This command needs to be executed after closing all Outlook instances?
2. What does this command do?

**Comment by croicu** [comment]
This command will reinstall the WebView control, I suspect the installation is corrupted on your machine. You should restart Outlook after you run the command.
