### ISSUE TITLE
getHtml() returns completely different values between Word Online and Word Desktop

### ISSUE THREAD

**Issue by leoseccia** [OfficeDev/office-js#162]
getHtml() returns completely different values between Word Online and Word Desktop. This poses potential issues when developing an addin that needs to run universally, across platforms. It kind of goes against the high-level Office App concept. An example is how bold is converted ie. Word desktop uses `<b>` while Word Online uses font-weight: bold; as an inline style.

## Expected Behavior
getHtml() returns the same html, no matter what platform it is invoked from.

## Current Behavior
getHtml() returns completely different values between Word Online and Word Desktop.

## Steps to Reproduce, or Live Example
Using Script Lab run the following snippet in both platforms (Word Desktop and Word Online) and compare the content returned:
```
name: 'Write Body as HTML in Body '
description: Executes a basic Word API call using TypeScript.
host: WORD
api_set: {}
script:
    content: |-
        $("#run").click(() => tryCatch(run));

        async function run() {
            // Gets the current selection and changes the font color to red.
            await Word.run(async (context) => {
                var myHTML = context.document.body.getHtml();
                await context.sync();
                document.getElementById("juan").innerHTML = myHTML.value;
                console.log(myHTML.value);

               // console.log(`The selected text was "${range.text}".`);
            });
        }

        /** Default helper for invoking an action and handling errors. */
        async function tryCatch(callback) {
            try {
                await callback();
            }
            catch (error) {
                OfficeHelpers.UI.notify(error);
                OfficeHelpers.Utilities.log(error);
            }
        }
    language: typescript
template:
    content: |-
        <p class="ms-font-m">Executes a simple code snippet. Make sure to select text before clicking "Run code".</p>
        <button id="run" class="ms-Button">
            <span class="ms-Button-label">Run code</span>
        </button>

        <div id="juan">
            
            </div>
    language: html
style:
    content: |-
        body {
            margin: 0;
            padding: 10px;
        }


        /* Button customization, including overwriting some Fabric defaults */

        .ms-Button, .ms-Button:focus {
            background: #2b579a;
            border: #2b579a;
        }

            .ms-Button > .ms-Button-label,
            .ms-Button:focus > .ms-Button-label,
            .ms-Button:hover > .ms-Button-label {
                color: white;
            }

            .ms-Button:hover, .ms-Button:active {
                background: #204072;
            }

            .ms-Button.is-disabled, .ms-Button:disabled {
                background-color: #f4f4f4;
                border-color: #f4f4f4;
            }

            .ms-Button.is-disabled .ms-Button-label,
            .ms-Button:disabled .ms-Button-label {
                color: #a6a6a6;
            }
    language: css
libraries: |
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
    https://appsforoffice.microsoft.com/lib/1/hosted/office.d.ts

    office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
    office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

    core-js@2.4.1/client/core.min.js
    @types/core-js

    @microsoft/office-js-helpers@0.7.4/dist/office.helpers.min.js
    @microsoft/office-js-helpers@0.7.4/dist/office.helpers.d.ts

    jquery@3.1.1
    @types/jquery

```

## Context
This poses potential issues when developing an addin that needs to run universally, across platforms. It kind of goes against the high-level Office App concept. 
The tool we are developing, analyses the content returned by getHtml(). Because of the way the html returned is completely different, the analysis often returns different results. This is a very critical issue because from our clients point of view, it diminishes credibility and confidence.

**Comment by leoseccia** [comment]
here is another example of where this is an issue on top of another issue: https://stackoverflow.com/questions/50816620/cross-references-anchors-and-links-from-a-document-in-word-using-the-javascript

**Comment by leoseccia** [comment]
this is also related: https://stackoverflow.com/questions/50021957/encoding-issue-with-gethtml-in-officejs

**Comment by serjant** [comment]
The same thing happens when you insert html with OL and UL tags and then when you retrieve the html using getHtml() method, it just replaces the OL/UL tags with P tags. I know that OOXML format represents lists as paragraphs using levels attributes and numbering.xml, but at least I would expect to have some attributes inside the P tag of the retrieved content which will point me the level of the list, the type of the list and start number of the list

**Comment by JuaneloJuanelo** [comment]
it was never our intent to retrieve the same HTML for all platforms. if you need 100% fidelity use the OOXML method instead.

**Comment by serjant** [comment]
@JuaneloJuanelo I understand - I have already written my own OOXML to HTML converter, but the problem when you retrieve the content using getHtml() and then you set the same content using insertHtml() - the content is completely broken. If you want to dig in, I can provide you with more details.

**Comment by leoseccia** [comment]
@JuaneloJuanelo in that case, it should be clearer in the documentation that different platforms returns different results. Also, are there other instances where the platforms behave differently? From the api consumer point of view, it would be very beneficial to have a list of where this occurs.

**Comment by JuaneloJuanelo** [comment]
@serjant insteresting. if you do getHtml and insertHtml on the same platform should work. Provide me a scenario when this is not the case.

@leoseccia  yes we will adjust that info for the HTML case. Again if you need 100% fidelity you should not be using HTML, but OOXML. the resulting HTML should be close to fidelity x-platforms.

**Comment by Rick-Kirkham** [comment]
@leoseccia 
I have updated the description of the getHtml method state that different HTML is returned on different platforms. Because we are currently in the process of moving to a new system of publishing API reference content, it may be a few weeks before the improved description is published.

**Comment by junaid042** [comment]
@Rick-Kirkham 
please fix this issues when I insertHtml in word desktop then it is working currently but not working same when I insertHtml in word online.
