### ISSUE TITLE
Cannot convert black icon to white icon while I'm using the dark theme

### ISSUE THREAD

**Issue by tanapone-kanongsri** [OfficeDev/office-js#1621]
## Expected Behavior

Convert black icon to white icon when using the dark theme
## Current Behavior

On windows installed version the sub-menu still using black icon 
## Steps to Reproduce, or Live Example

![icon-issue](https://user-images.githubusercontent.com/78138777/106110669-97c4de80-617d-11eb-8da4-7b6e2cbefd6d.jpg)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2002 (Build 12527.21330)
* Operating System: Windows 10 Enterprise
* Browser (if using Office on the web): -

**Comment by ElizabethSamuel-MSFT** [comment]
@tanapone-kanongsri If this is still an issue, please comment and we can reopen. Or you can create a new issue. Thanks.
