### ISSUE TITLE
When inserting content to appointment body, content does not show up immediately.

### ISSUE THREAD

**Issue by liwei118** [OfficeDev/office-js#1624]
It is kind of slow when inserting content to appointment body with Office.context.mailbox.item.body.setAsync(). Is this a known issue as I see there is a tip "Teams meeting details will be added after sending the invitation" in the Teams Add-In.

**Comment by exextoc** [comment]
@liwei118 
1.  Could you please the following information?
  -         Platform [PC desktop, Mac(Classic or New UI), iOS, Office on the web]: 
  -         Office version number: 
  -         Operating System: 
  -         Browser (if using Office on the web):
2. Please provide us the script with which you are inserting the text along with repro steps. Perhaps, a video recording would help us understand how slow the API is.

**Comment by liwei118** [comment]
Platform [PC desktop, Mac(Classic or New UI), iOS, Office on the web]:  Mac 

Office version number:  16.46 (21012005)

Operating System: Big Sur

Browser (if using Office on the web):

**Comment by exextoc** [comment]
@liwei118 Thanks for sharing information about the Platform. Could you please specify whether you are seeing this issue in Classic Mac UI or New Mac UI?
Also, Please answer the second question in the previous comment so that we can try to repro the issue locally.

**Comment by liwei118** [comment]
Classic Mac UI

**Comment by exextoc** [comment]
@liwei118  We are not able to reproduce this issue on our side. Could you please help us with repro steps?
