### ISSUE TITLE
Office.js causes build failure for Outlook 2016 Addin

### ISSUE THREAD

**Issue by blakezeisler** [OfficeDev/office-js#1627]
Office.js fails to load https://telemetryservice.firstpartyapps.oaspapps.com/telemetryservice/telemetryproxy.html the server responded with a status of 404. I do not need this for my app.

I am calling office.js from CDN in header of HTML, then initializing in main.ts file: 

`<script src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js" type="text/javascript"></script>`

```
  Office.initialize = function () {
    const platform = platformBrowserDynamic();
    platform.bootstrapModule(AppModule).catch(err => console.log(err));
  };
```
It is failing the build of my web app and therefore I can't deploy it as an Outlook 2016 Addin because the manifest file is pointing to my web app. This is currently preventing from creating an Addin for Outlook 2016 desktop using javascript/typescript.

## Expected Behavior
Office.js should load all files it references (in this case the telemetryservice) OR bypass failing service.

## Current Behavior
Web app build fails when office.js is loaded because it does not get a response from telemetry service.

## Steps to Reproduce, or Live Example
1. Generate an office addin using Yo office.
2. Select to generate an Angular app
3. Load office.js into header of index.html
4. Initialize office in main.ts with app boot strap
5. Attempt to perform build and observe build failure.

## Context
I am developing an Addin for Outlook 2016 desktop for a private company. I have generated app using yo office then loading office.js to try and call outlook methods, but office.js calls a telemetry service that fails to load and thus i am not able to build and deploy the app that the manefest points to. If I comment out office.js then i can build my app and the Addin can be loaded and viewed in the task pane.

## Your Environment

* Windows 10
* Outlook 2016 Desktop
* Chrome and Edge

## Useful logs
Failed to load resource: the server responded with a status of 404 ()  
   Request URL: https://telemetryservice.firstpartyapps.oaspapps.com/telemetryservice/telemetryproxy.html

**Comment by exextoc** [comment]
Are you loading Office.js inside of the Outlook application? Office.js will only work inside an Office application, which could be causing the error you are seeing. Are you seeing any other errors in the console while building?

**Comment by blakezeisler** [comment]
I am loading office in Outlook 2016 desktop. I found the build is successful, but since outlook 2016 only supports IE 11, some of the components of my web app don’t support polyfills that are back compatible to IE 11, so the taskpane comes up blank.

I ended up needing to move forward so I rolled into using JavaScript with fabric js components.
