### ISSUE TITLE
Start of 5 second initiation timer

### ISSUE THREAD

**Issue by parilla** [OfficeDev/office-js#1628]
For the statement _'Office applications require that add-ins initialize within 5 seconds of activation'_ I would like to know precisely when this time starts?

Reason being is our Add-in is hosted on a SiteMinder protected web server, and performs an authentication process which takes approx 3.5 seconds to execute. This process performs a series of HTTP 302 redirects to facilitate authentication.

Of interest is if the timer restarts post HTTP 302 redirect (5 seconds starts after the redirect is processed).

Also can this time be extended via configuration if 5 seconds is proves insufficient for SiteMinder authentication and page asset loading?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 657d2f02-ef94-316e-ad68-c4f027c3f396
* Version Independent ID: e4bba2e5-7c64-86ea-c2ec-ac75b4a446bd
* Content: [Outlook add-in APIs - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/apis?source=docs)
* Content Source: [docs/outlook/apis.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/apis.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lliu113** [comment]
@parilla  - can you link the doc where you got the 5 secs initialize from?

**Comment by AlexJerabek** [comment]
@lliu113 - In this doc: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/apis
In the blue "Important" section.

**Comment by parilla** [comment]
@lliu113 the doc link has been correctly identified by @AlexJerabek 

Please note the SiteMinder scenario I am describing will be quite common in large multinationals with significant IT investments.

**Comment by lliu113** [comment]
@AlexJerabek - thanks for linking the doc!
@parilla  - appreciate the confirmation. Will follow-up internally and get some clarification.

**Comment by lliu113** [comment]
@parilla - looks like this is an error in our documentation, we strongly recommend your add-in activates within 5 seconds but there is no error message. However, once activated we may display an error message if your add-in is unresponsive or if it exceeds an acceptable CPU usage. 

Hope that clears things up! We will be working to get this amended in the docs.

**Comment by parilla** [comment]
Thankyou @lliu113 

This may explain why I was unable to force an error message to occur via deliberately delaying the initialization with this code:

setTimeout(function(){ 
  /* Render application after Office initializes */
  Office.initialize = () => {
    isOfficeInitialized = true;
    render(App);
  };
}, 10000);  

Even after a 10 second delay the add-in still loaded without error.

If there are future issues does the 'AlertInterval' policy setting allow us to control the error message behavior?

**Comment by lliu113** [comment]
@parilla - we don't check this policy when showing the errors, so they can't be controlled with that setting. There's no restrictions in the code, so we shouldn't be showing initialization errors. If you encounter future issues please don't hesitate to open a new issue and we will follow-up. 

We will be updating the documentation to correctly reflect the state. Closing this issue - thanks for bringing this to our attention!
