### ISSUE TITLE
getHtml() in Word Online returns html with correct UTF-8 values, however it does not contain <meta charset="UTF-8" />

### ISSUE THREAD

**Issue by leoseccia** [OfficeDev/office-js#163]
getHtml() in Word Online returns html with correct UTF-8 values, however it does not contain <meta charset="UTF-8" />. This means that when you save and display the document in the browser the UTF8 characters do not display correctly. Adding the meta tag, solves the issue. 

This is directly related to https://github.com/OfficeDev/office-js/issues/104

**Comment by JuaneloJuanelo** [comment]
@weshi issue with Word Online...
