### ISSUE TITLE
Excel CustomFunctions not installing on web

### ISSUE THREAD

**Issue by nathanhammond** [OfficeDev/office-js#1630]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

The add-in that fails to work is entirely open source, built using `yo office` and the Office's [Excel-Custom-Functions template](https://github.com/OfficeDev/Excel-Custom-Functions).

The source (and, consequently) diff from the initial template is available here:
https://github.com/cantonese/cantonese-for-excel

Browsing of the compiled output is available here:
https://github.com/cantonese/cantonese-for-excel/tree/gh-pages

The add-in works perfectly in Excel for Mac. Based upon the Add-in Store review not flagging it, I also believe that it works on Excel for Windows (but I am unable to personally verify that).

## Expected Behavior

Successfully install an Excel Add-in's `CustomFunctions` on the web.

## Current Behavior

Excel for the Web will always throw an error when attempting to install this add-in. The error is "One or more add-ins failed to install or load custom functions." "Error installing functions." This error appears in all browsers.

<img width="1280" alt="Failure in Excel for the Web" src="https://user-images.githubusercontent.com/20542/106708190-5a7fa700-65ea-11eb-9d70-2afb252fc440.png">

Reviewing the network behavior, the call to load `functions.json` completes successfully but no further call is made to load either `functions.html` or `functions.js` as specified in the manifest.

Reviewing the console log there is nothing that appears to be related to the installation failure.

The manifest for the add-in is available for review here:
https://cantonese.github.io/cantonese-for-excel/dist/manifest.prod.xml

The calls I expect would be made to load the function runtime and load the JavaScript are these:
https://cantonese.github.io/cantonese-for-excel/dist/functions.html
https://cantonese.github.io/cantonese-for-excel/dist/functions.js

## Steps to Reproduce

0. Download this manifest file: https://cantonese.github.io/cantonese-for-excel/dist/manifest.prod.xml
1. Visit office.com, create a new Excel document.
2. In the Ribbon, select the "Insert" tab.
3. Click "Office Add-ins".
4. In the modal that appears, press "Upload My Add-in".
5. Upload the XML file downloaded in step zero.
6. Note the failure.

## Context

As a consequence of this, I've been prevented from distributing my add-in through the Add-in store, necessary as part of getting this distributed to the disparate teams working on a particular Cantonese language documentation project.

## Your Environment

This issue is reproducible in Excel for the Web in all web browsers.

**Comment by xiaochunms** [comment]
Please check the Version element in manifest.prod.xml, which is <Version>1.0.2</Version>, however the syntax expected is <Version>n .n .n .n</Version> as [manifest version](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/version) shows. You may can change it to <Version>1.0.0.2</Version> to have a try.

**Comment by nathanhammond** [comment]
It appears possible that this change may result in the add-in working. However, that this passes both submission validation and local validation is definitely a bug.

```sh
npm install -g office-addin-manifest
wget https://cantonese.github.io/cantonese-for-excel/dist/manifest.prod.xml
office-addin-manifest validate manifest.prod.xml && echo "It passes validation."
```

**Comment by nathanhammond** [comment]
Also worth noting, changing the version number being the solution strongly implies that Excel for Web and Excel for Mac are using different methods for identifying the version of an add-in. Those should likely be brought into parity.

**Comment by nathanhammond** [comment]
Note: I've just updated the published version to use a four digit version number. The validation passes with a three-digit version number.

**Comment by xiaochunms** [comment]
@nathanhammond good to know the add-in works with four digit version number. This is the first time I've seen an issue as such. There might be a hole in validation process. Thanks to raise the issue.
