### ISSUE TITLE
[Outlook] function "displayReplyAllForm" does not work properly

### ISSUE THREAD

**Issue by Petryxasport** [OfficeDev/office-js#1631]
**Issue:**
A wrong place of a Signature when use the function "displayReplyAllForm" on a MacOS system.

**Steps to Reproduce:**
1. Add Signature into Outlook
2. Open Add-in in Outlook
3. Call function: Office.context.mailbox.item.displayReplyAllForm({});
Result: As you can see below the signature is on the bottom.
![image](https://user-images.githubusercontent.com/17165899/106632494-dd731400-658e-11eb-9657-847fad858f26.png)

**Expected result:**
When we use the outlook button "Reply All" we can see correct result:
![image](https://user-images.githubusercontent.com/17165899/106632732-21feaf80-658f-11eb-97be-60da639f6ae1.png)

**Environment**
Platform :Office Desktop
Office version number: 365 MSO 64-bit
Operating System: MacOS

**Comment by exextoc** [comment]
@Petryxasport Are you seeing this issue in Classic Mac UI or New Mac UI?

**Comment by Petryxasport** [comment]
Issue is relevant only for Classic Mac UI

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding displayReplyAllForm. It has been put on our backlog. We, unfortunately, have no timelines to share at this point

**Comment by exextoc** [comment]
Thank you for sharing this issue. As a workaround, users can switch to the new Outlook for Mac experience which works as expected. We are not prioritizing this fix on classic Mac UI; please reopen the issue in case the workaround does not solve your scenario.

**Comment by Petryxasport** [comment]
We know, but unfortunately can not switch to the New UI because Dialog window does not support add-in for the new Mac UI. This issue described here:
https://github.com/OfficeDev/office-js/issues/1438

**Comment by exextoc** [comment]
Thanks for sharing this issue. We are presently working on it and will update once it is available in Insiders.

**Comment by exextoc** [comment]
@Petryxasport Add-ins support on pop out compose is now available on New UI for Insiders Beta users. You can update to latest version and use the New UI as workaround. For information on Office Insiders program check [here](https://insider.office.com/en-us/join/mac).
