### ISSUE TITLE
RecipientsChanged not fired when selecting recipients from address book on Outlook web

### ISSUE THREAD

**Issue by amiram** [OfficeDev/office-js#1634]
RecipientsChanged not fired when selecting recipients from address book on Outlook web

## Expected Behavior

RecipientsChanged is fired

## Current Behavior

RecipientsChanged not fired

## Steps to Reproduce, or Live Example

add a handler to RecipientsChanged
```
mailItem.addHandlerAsync(Office.EventType.RecipientsChanged, () => {
});
```

Add contacts from address book - event not fired.
Add contacts by typing in the To field - event fired.

## Your Environment

* Platform - Office on the web.
* Host - Outlook
* Operating System: Ubuntu
* Browser (if using Office on the web): Chrome 88

I didn't check it in installed version of Outlook.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding Recipient Changed Event. It has been put on our backlog. We unfortunately have no timelines to share at this point
