### ISSUE TITLE
Insert presentation with custom tag removed while inserting a presentation

### ISSUE THREAD

**Issue by mariselvanm** [OfficeDev/office-js#1635]
I was trying to insert a presentation using the below office js API. `data` contains base64 format of pptx. In each and every `chart.xml` file I was having some custom tags like `<author>, <uniqueId>`. Using the below code to insert a presentation. 

    await PowerPoint.run(async function(context) {
       context.presentation.insertSlidesFromBase64(data);
       await context.sync();
    });

 After inserting the PPTX if I extract the PPTx file and view the chart.xml file I can't find any custom tags. Those are removed by the library. How to resolve these issues?

**Comment by ononder** [comment]
I'm looking at this bug @mariselvanm, but I couldn't repro the issue when I add a tag to the chart shape. I wonder if the tags you mention is a different tag.

Can you share a sample pptx file which reproduces this behavior? It can be a very simple file, it could be shared as a gist or even in base64 format with a sample usage.
