### ISSUE TITLE
Reply/ReplyAll/Forward has to provide option to open in active window for the New Mac UI

### ISSUE THREAD

**Issue by Petryxasport** [OfficeDev/office-js#1636]
Current functions Reply/Reply All/Forward are opened Dialog pop-up instead of opening in an active window based on a new idea of New Mac UI.

Will be grate to have some additional Boolean parameter "Is Dialog" for _displayReplyAllFormAsync or displayReplyAllForm_ function to have an option stay in current window without opening via pop-up.

**Comment by exextoc** [comment]
@Petryxasport Currently the feature you requested is not available. We track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered when we go through our planning process.
