### ISSUE TITLE
Missing API for retrieving folder of Office.context.mailbox.item

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js#164]
Looking at your latest API in https://dev.office.com/reference/add-ins/outlook/preview/Office.context.mailbox.item it seems there is no way to find out the folder the currently selected message resides.

Think this is an important feature. Already searched on StackOverflow, Github and in your code base for answers but nah, no luck.

I don't want to retrieve a full folder list and compare their messages with the itemId to find this out. Way too complicated/long.

Any clues?

**Comment by exextoc** [comment]
The way to do this would be to get the item id of the current item, then use graph or EWS to look up the folder id.

**Comment by JuaneloJuanelo** [comment]
please add to https://officespdev.uservoice.com/ if solution is not suitable. thanks!

**Comment by hmuris** [comment]
On this link, we get only this message: This UserVoice instance is no longer available.
Feature is still missing as there is no way to find out if the message is incoming or outgoing message, by ONLY using office js.

**Comment by eugene-plutoflume** [comment]
Use https://aka.ms/M365dev-suggestions for posting your feature requests or suggestions instead.

**Comment by senden9** [comment]
Feature request link: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-property-or-function-for-retrieving-folder-of-office-context/idi-p/4124679
