### ISSUE TITLE
Custom XML part is not updated

### ISSUE THREAD

**Issue by NickDarvey** [OfficeDev/office-js#1643]
We're trying to append an item to a collection in a custom XML part. We can create the part with some initial content, however we cannot update it.

## Expected Behavior
We can create a custom XML part via `customXmlParts.addAsync` and then update it.

## Current Behavior
We cannot updated a custom XML part once created.

## Steps to Reproduce, or Live Example
* Link to live example: https://gist.github.com/NickDarvey/d245054dc6894690d3f28a6ac99036c0
 
1. Click run, observe that the customXmlPart has been created (via the `if` branch)
2. Click run, observe that the customXmlPart has _not_ been updated (via the `else` branch)

## Context
We want to be able to append items to a collection in a custom XML part as the document is edited.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Version 2101 (13628.20380) x64
* Operating System: Windows 10 Pro 1909 (18363.1379)

**Comment by NickDarvey** [comment]
This works if you alter `exampleContent2` from
```
<?xml version="1.0" standalone="no"?><c:Collection xmlns:c="' + namespace + '" xmlns="' + namespace + '"><c:Item>Test 1</c:Item><c:Item>Test2</c:Item></c:Collection>
```
to
```
<c:Collection xmlns:c="' + namespace + '" xmlns="' + namespace + '"><c:Item>Test 1</c:Item><c:Item>Test2</c:Item></c:Collection>
```

and update the `part.getNodesAsync` path during the update branch from `/` to `/*`.

It does seem like `setXmlAsync` ought to return an error if supplied with the former. I'll leave this open for consideration, but feel free to close it if `success` is considered correct behaviour.

**Comment by AbidRahman-MSFT** [comment]
Hey @NickDarvey, thanks for posting the issue.

It looks like you are attempting to update a single node of an XML with an entire XML snippet and hence were running into the error. I do agree that the error could be more useful to debug quicker, unfortunately, we won't be making any additional changes to the Common API set.

FYI:
If you are only targeting Word on Windows and Word on Mac for your add-in, I would highly suggest using the Preview APIs for Word instead of the Common API set to alter custom XML parts. For your example, you can achieve the same scenario as your sample with much fewer code:

```
    let doc = context.document;
    let xmlParts = doc.customXmlParts.getByNamespace(namespace);
    const numXmlParts = xmlParts.getCount();
    await context.sync();

    if (numXmlParts.value == 0) {
      doc.customXmlParts.add(exampleContent1);
      await context.sync();
    } else {
      console.log("amend existing part");
      let part = xmlParts.getOnlyItem();
      part.setXml(exampleContent2);
      await context.sync();

      const xmlPart = xmlParts.getOnlyItem();
      const updatedResult = xmlPart.getXml();
      await context.sync();
      console.log("updated results: ", updatedResult);
    }
```

**Comment by NickDarvey** [comment]
Thanks for the tip @AbidRahman-MSFT. That Preview API does look much more pleasant, but unfortunately we'll have to wait till it's more widely available.
