### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by OfficeAddins** [OfficeDev/office-js#1644]
<img src="https://bettersolutions.com/github/undefined/screenshot.png">

## Expected Behaviour
What is this error message ?

## Current Behaviour
When I press the button to display the task pane, I am seeing the following error message in the console window which I cannot remove or explain:

"Uncaught (in promise) TypeError: Cannot read property 'name' of undefined"
    at t (word-web-16.00.js:26)
    at word-web-16.00.js:26
    at Office.js:46
    at Array.forEach (<anonymous>)
    at d (Office.js:46)
    at Office.js:46

## Steps to Reproduce, or Live Example
Side load the TypeScript add-in into Word Online and press the Button to display the task pane.

The task pane is displayed but why is this error message appearing.

## Context
This error message might have always been there, not sure.
I have tried all the following URLs and the message is consist.
src="appsforoffice.microsoft.com/lib/beta/hosted/Office.js" 
src="appsforoffice.microsoft.com/lib/1/hosted/Office.js" 
src="appsforoffice.microsoft.com/lib/1.1/hosted/Office.js" 

## Your Environment
This appears in Word Online
Windows 10 64 bit and Office 64 bit
Browser - Microsoft Edge, Version 88.0.705.68 (Official build) (64-bit)

## Useful logs
The following repository contains the project (only 5 files):
https://github.com/OfficeAddins/undefined

**Comment by OfficeAddins** [comment]
Have you been able to look at this please

**Comment by keyur32** [comment]
Adding @AbidRahman-MSFT to help take a look at this issue.

**Comment by OfficeAddins** [comment]
Have you been able to look at this please

**Comment by yihuax-zz** [comment]
How to repro it? Where to find the TypeScript add-in?

**Comment by OfficeAddins** [comment]
Many Thanks.
The following repository contains the project (only 5 files):
https://github.com/OfficeAddins/undefined

**Comment by jayrathi** [comment]
Can you try using this using lowercase o when referencing the office.js url - 
src="appsforoffice.microsoft.com/lib/beta/hosted/**o**ffice.js"

**Comment by OfficeAddins** [comment]
Thank you so much Jay !!! Yes, the error message has disappeared !!

**Comment by gercobrandwijk** [comment]
@jayrathi Do you have any idea how this solves the problem/How this caused the problem?
