### ISSUE TITLE
Incorrect EWS URL used to attempt to obtain token when Exchange environment has both External and Internal EWS URLs set

### ISSUE THREAD

**Issue by GrumpyAL** [OfficeDev/office-js#1646]
## Expected Behavior
When using getCallbackTokenAsync from an Outlook on Windows client while external to the Exchange environment, the command is sent through the  external EWS URL (as seen in fiddler).  It is expected that the client/Office Add-ins framework would use the appropriate URL depending on the client's network status (External vs Internal access).

## Current Behavior
When using getCallbackTokenAsync from an Outlook on Windows client while external to the Exchange environment, the command is sent through the **internal** EWS URL (as seen through Fiddler) when the client is not on the internal network.  Other calls appear to go correctly to the **external** URL and the Office.context.mailbox.ewsUrl property returns the external URL as expected.

## Steps to Reproduce, or Live Example
This is difficult to reproduce.  I have seen this in a live production environment but have not been able to setup my lab correctly so far to attempt to reproduce. (Still working on this). 

* Additional details:
  1. Have an Exchange 2016 environment that has both internal and external access, specifically having separate FQDNs for the EWS internal and external URL in the virtual folder's configuration.
  2. Connect an Outlook on Windows client to this environment and attempt to get an EWS or REST token while using the external connection.

## Context
This issue prevents the client, when external, from obtaining a token when external as the client tires to reach the internal EWS URL.

## Your Environment

* Platform PC Desktop
* Host Outlook
* Office version number: Microsoft Outlook for Office 365 MSO (16.0.12527.21294) 32 bit \ Version 2002 Build 12527.21330 Click-to-Run)
* Operating System: Windows 10
* Browser (if using Office on the web): n/a

## Useful logs

![image](https://user-images.githubusercontent.com/28786762/108236244-ac5d1c80-7114-11eb-9eb9-7186d405e14f.png)

The Office Add-ins script in use for this client  is outlook-win32-16.02.js

**Comment by exextoc** [comment]
Which other calls appear to go to the external URL? Are those calls from the add-in or from the Outlook client itself?

**Comment by GrumpyAL** [comment]
So far I've only noticed that the token calls go to the incorrect internal URL whereas everything else go to the external as expected.  The one I'm not 100% sure of is an identity token call, that one is a bit harder to track.

The calls are coming from Outlook.exe and I can only see them in Fiddler.  They do not show up in the F12 Dev tools when attached to the frame (assuming because they aren't coming from the IE/Edge process running that frame).

If there are any specific function calls you'd like me to check, I'd be happy to do so.  I can just run them via the console while the add-in frame is still loaded in Outlook and monitor the Outlook process with Fiddler.

**Comment by exextoc** [comment]
Let me investigate the EWS calls from outlook.exe and get back to you.

**Comment by exextoc** [comment]
I expect requests that Outlook make to EWS (for addin tokens/ and other EWS calls) should be using the same endpoint. Here are few things to look into:

From addin:
- could you also print out the diagnostics object for this error. Info: https://docs.microsoft.com/en-us/javascript/api/office/office.asyncresult?view=excel-js-preview#diagnostics

For Outlook:
- there should be logic to fall back (external->internal) url. Having said that, the internal vs external detection sometimes require Outlook reboot. Could you see if there are such scenario in the repro where the user might have moved from internal -> external network, or vice versa?

In the fiddler:
- Addin APIs getCallbackToken call should trigger a EWS call to exchange.asmx, and the request payload XML should include GetClientAccessToken. getUserIdentity call is harder to see because the result is cached on the client, but the same GetClientAcessToken method is used. What responses are we seeing from EWS?
- Other EWS calls are made to exchange.asmx as well, could you confirm if calls made to exchange.asmx is using a different URLs compared to GetClientAccessToken?

**Comment by GrumpyAL** [comment]
Thanks!  I will look into this and get back to you.  Please note, I do not have direct access to this environment to repro so it may take me a few days to collect everything.  Thanks again!

**Comment by GrumpyAL** [comment]
@exextoc Quick question.  Is it expected that asyncresult.diagnostics property will contain information if the error is **not** HTTPRequestFailure or InternalServerError?  I have implemented the diagnostics property but I can't seem to fake the right error to get it to print out information.

In the case of using the wrong EWS URL here, we're getting DNS resolution failure so I'm not sure we'll see information in that property.  I'm happy to print it out anyway, but want to make sure I'm getting what you need and not looking at the wrong thing.  Thanks!

**Comment by exextoc** [comment]
The diagnostics property may not be present in all cases (depend on client version too), but should be there when the error message says that it is.  For coding/printing this, definitely check that the diagnostics property is present, and print JSON.stringify the property.

Thanks for the additional info on the EWS hitting DNS error. It will still be interesting to see if any EWS calls (specifically exchange.asmx) succeeds, and if there are attempts to retry.  EWS is used for other features in Outlook outside of addins (eg. setting OOF, getting mailtips). Knowing if those succeed will let us know if this is a general Outlook or config issue with EWS vs an addins issue (or just tokens).  When you are collecting fiddler, it will also be good to start collecting during Outlook launch as well to see if getting addins is affected (which also use EWS).

To be clear on terminologies, when we say EWS calls here, we are referring to call to exchange.asmx.  It's quite possible in fiddler that you see other calls to Exchange succeeding, and it is interesting to know that they are succeeding. It is also interesting to know if some EWS are succeeding.

**Comment by GrumpyAL** [comment]
@exextoc are there any Framework calls you want me to make that would have an underlying EWS call?  Right now I am using the token viewer demo app to troubleshoot this.  I have a modified version that won't pull the tokens until you ask for each one so we can make sure to only try for one token at a time (and prevent the ID token from getting cached before we're ready).

But before I setup a session to pull some of this information, just wanted to check if I should try any other calls that may have underlying EWS calls (e.g. makeEWSRequestAsync)

The last time I ran fiddler in this scenario I believe I do recall seeing some failed EWS/Exchange.asmx calls but they were followed by successes to the other URL.  Outlook appears to work normally aside from add-in tokens.  The tokens never seem to try to fallback.  However, I will setup some time to test again and try to get you more/better information. 

Thanks!

**Comment by exextoc** [comment]
You could try: 

makeEWSRequestAsync() 
getCallbackTokenAsync() (both isRest = true and false)
getUserIdentityTokenAsync()

makeEWSRequestAsync() should make an EWS Call every time. However, this does not have the diagnostics data object on return. 

The Token Calls DO have a diagnostics object returned on the latest builds of Outlook. 
The UserIdentity token is cached for some number of hours, so it will stop making EWS calls for this API until you reboot Outlook. 

Outside of add-ins, you can create a new mail and try to send the email to someone outside your org. This is supposed to display a mailtip that warns you that you are sending a mail outside your org. I would be interesting if mailtips *worked* and the outlook.js apis were failing, as they are supposed to be using the same EWS endpoint.

**Comment by GrumpyAL** [comment]
Hello,

We have done some additional testing.  To summarize, when on an External network, every aspect of Outlook and Office Add-ins appears to work fine with the exception of getCallbackTokenAsync() (REST or EWS).

To add some detail.  I modified the TokenViewer Sample App (available here https://github.com/OfficeDev/Outlook-Add-In-Token-Viewer) to have it only get a single token on demand (instead of trying to get all of them at once) and to print the diagnostic error on failure.  I also added a call to makeEWSRequestAsync() to get the id of the parent folder of the current mail item.

In the same "session" (By which I mean we opened the Add-in task pane and did not close it or change network status) we were able to successfully run the makeEWSRequestAsync() function but not get an EWS token:  

![image](https://user-images.githubusercontent.com/28786762/110946253-aa017300-830c-11eb-97de-8d2334b445b3.png)
(Rest tokens also failed in other tests).

Not pictured, the call to get an identity token was also successful.  We parsed the token and verified the nbf value to ensure that the token was not pulled from cache.

The only way we've been able to get EWS or REST tokens while external has been to modify the host file to point the internal URL to an external IP address.

Unfortunately, we were not able to do this testing with Fiddler running as it acting as a proxy and doing SSL inspection was causing other errors with the tests.  So these tests were done without Fiddler sitting in the middle.  Outlook was also opened while on the External network and we never connected to the internal network during the tests. 

We also tested the EWS operation mentioned regarding Mailtip and it was working as expected:

​​
![image](https://user-images.githubusercontent.com/28786762/110946279-b08fea80-830c-11eb-9a40-fa314592399e.png)


One other note, the Outlook client did receive an update from when I originally opened this ticket but that did not change the results.  It was on 2008 (Build 13127.21216 Click-To-Run) at the time of these tests.

Please let me know if you need additional information.  Thanks!

**Comment by exextoc** [comment]
Thank you for the information. We have identified this issue as a client bug. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: 4961334

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 16.0.13925.10000 or later. When an updated build is available depends on the release channel a customer is on.

**Comment by GrumpyAL** [comment]
Thank you!  We will test once the build is available.  Looks like we were running Semi-Annual Enterprise channel in our testing.

**Comment by atsopuronen** [comment]
This issue seems to still occur for our customer after updating to Semi-Annual Enterprise Channel version 2102 (build 13801.20864). At least the symptoms and workarounds are identical.

**NOTE:** While the build doesn't match with the "16.0.13925.10000 or later" mentioned above, the release notes for Semi-Annual Enterprise Channel version 2102 (build 13801.20808) (July 13, 2021) contain the fix:
> We fixed an issue that caused users to get connectivity errors when the internal and external EWS endpoints are different and the call to the internal endpoint fails.

Does anyone else continue having the issue with this Semi-Annual Enterprise version?

**Comment by exextoc** [comment]
The fix build of 16.0.13925.10000 is for the Monthly Release Channel.
For the Semi-Annual Release Channel, the fix build is 16.0.13801.20686 (ver. 2102), so your customer should have the fix.
We are going to re-validate the changes to understand what is going on.

**Comment by exextoc** [comment]
What symptoms are you seeing and what workarounds have you tried?

Could you add fiddler logs for when you see this issue repo?
