### ISSUE TITLE
[Outlook ] Custom property missing when update scheduled recurring meeting 

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1648]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I have scheduled an recurring meeting( write something in custom properties) and  then updated one event of the series. 
Problem is, when I open the updated single event the custom property can not be read.
But when I edit other single event or entire series, I can get saved properties. 
This problem can be easily replicated on WINDOWS outlook application.

## Expected Behavior
1. updated single event can still get saved custom properties.

## Current Behavior
1. Schedule a recurring meeting and write something to custom properties.
2. update one single event.
3. trying read saved custom properties on updated single event

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2101 13628.20380
* Operating System: windows 1909
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by SWei1234** [comment]
Hi @exextoc 
Just update the description:
I found that this problem also happened on shared calendar. 
But when I open the same event on Boss's calendar. I can access the properties fine.
But think this might be permission issue. Just need confirm this.
Thanks

**Comment by exextoc** [comment]
The problem with Custom Properties missing on the updated single event (a.k.a meeting exception) is a known issue that we have in our backlog. We unfortunately have no timelines to share at this point regarding this issue.
For the Shared Calendar scenario, are you observing this problem on a meeting exception as well?

**Comment by exextoc** [comment]
Can you also share how you are setting up the Shared Calendar Scenario (specific steps that you took to both setup (the delegator) the Shared Calendar and how you are accessing it from the delegate)

**Comment by SWei1234** [comment]
Hi @exextoc 
We setting up the delegate permission by default, like:
![image](https://user-images.githubusercontent.com/15980696/110061874-4246a780-7da3-11eb-93bc-c56bf677bf2f.png)

I add shared calendar steps:
Right click on my calendar-> choose open shared calendar-> open a shared calendar under group 'My calendars'.
Any idea?
Thanks

**Comment by exextoc** [comment]
Thanks for providing that info!
When you tried it on your Boss's calendar (or any Shared Calendar), did you see the same issue? And did the issue occur when you updated all events or a single event (meeting exception)?

**Comment by SWei1234** [comment]
Hi @exextoc 
Yes, When I tried this on a shared calendar this problem will happen include my boss's. 
And I can replicate this on my side and it's inevitable.
Thanks
,

**Comment by exextoc** [comment]
As previously mentioned, the problem with Custom Properties missing on the updated single event (a.k.a meeting exception) is a known issue that we have in our backlog. We unfortunately have no timelines to share at this point regarding this issue.

Similar to #1508, the recommended workaround for this issue is:
- Exception (from series) meeting is created
- Gets a webhook with series ID of the parent series
- Retrieves custom property of the series ID
- Then set property it on the exception meeting

Please try it and let us know.
