### ISSUE TITLE
Outlook 2016 Reporting Incorrect Dialog API/Mailbox Requirement Set Support

### ISSUE THREAD

**Issue by mmcalynnproof** [OfficeDev/office-js#1649]
Calling isSetSupported("DialogApi", 1.1) or isSetSupported("Mailbox, 1.4) in Outlook 2016 is reporting false, even though the Dialog API works in that environment as it supports Mailbox API 1.4.

## Expected Behavior
Office.context.requirements.isSetSupported("DialogApi", 1.1) and Office.context.requirements.isSetSupported("Mailbox", 1.4) should return true in Outlook 2016.

## Current Behavior
Office.context.requirements.isSetSupported("DialogApi", 1.1)  and Office.context.requirements.isSetSupported("Mailbox", 1.4) returns false in Outlook 2016.

## Steps to Reproduce, or Live Example
The example from https://github.com/OfficeDev/office-js/issues/1476 can be used here. Use it in an Outlook 2016 environment.
Additional details:
* Run the add-in in Outlook 2016
* Click the Run button
* Inspect the reported values for the various requirement sets support

## Context
Add-in is trying to check if we can show a prompt to the user and if not then we go a default path. In this case it is falling back to the default path when it could show the prompt instead.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Windows Outlook 2016 32-bit and 64-bit.
* Host [Excel, Word, PowerPoint, etc.]: Outlook 2016
* Office version number: Outlook 2016, 16.0.5113.1000
* Operating System: Windows

## Additional Information

I've checked that the osfclient-x-none updates are installed and they are, ([here](https://support.microsoft.com/help/4475580) and [here](https://support.microsoft.com/help/4464534)).

Note dialogs do work on the environment, just this check if they are supported is failing.

**Comment by exextoc** [comment]
I have been unable to reproduce this issue so far, Office.context.requirements.isSetSupported("DialogAPI", 1.1) and Office.context.requirements.isSetSupported("Mailbox", 1.4) both return true in my setup of Outlook 2016.

Could you help confirm the binary version for Outlook.exe and osf.dll to make sure? (right click, properties, details tab on the files that should be in the directory where office is installed)
In addition, could you tell us the full path of the office.js reference? (are you using https://appsforoffice.microsoft.com/lib/1/hosted/office.js?)
