### ISSUE TITLE
Promise from context.sync never resolves when inserting slides

### ISSUE THREAD

**Issue by dhilgarth** [OfficeDev/office-js#1650]
## Expected Behavior
After inserting a slide with `insertSlidesFromBase64` and then calling `context.sync()`, the promise returned by `sync` should eventually resolve, no matter how many times this routine is called.

## Current Behavior
The first time I call `context.sync()`, the promise resolves. In subsequent calls, the promise doesn't resolve, although the slide still gets added successfully.

## Steps to Reproduce, or Live Example
```
function insertSlide() {
    PowerPoint.run(context => { 
        context.presentation.insertSlidesFromBase64(base64, {formatting: PowerPoint.InsertSlideFormatting.useDestinationTheme});
        return context.sync().then(() => console.log('resolved')).catch(e => console.log('rejected', e));
    });
}

insertSlide();
setTimeout(insertSlide, 10000)
```

"resolved" will be printed to the console only once.

I also created a full add-in demonstrating the behavior. It can be found here:
https://github.com/dhilgarth/PowerPointIssueForeverPromise
Click on the Run link at the bottom of the task pane. It will insert the slide and change the text to Promise resolved.
Click on Run again. The text will stay at Sync started - Promise not resolved.

## Context
I want to perform additional steps after the slide has been inserted, specifically selecting it with `goToById(...Next, ...Index)`

## Your Environment
* Platform: Office on the web
* Host: PowerPoint
* Operating System: Windows 10 1909
* Browser: Chrome, Edge Chromium, Firefox

**Comment by barisbikmaz** [comment]
This issue is still happening. @ononder Do you have any plans to fix this ?

**Comment by ononder** [comment]
Hello @barisbikmaz, we will prioritize this issue and I'll get back to this thread with the updates. We are sorry for the inconvenience this is causing currently.

**Comment by ononder** [comment]
This should be fixed now. Let us know if that is not the case. Thanks for the feedback and report.
