### ISSUE TITLE
getSelectedDataAsync with SlideRange only returns first selected slide

### ISSUE THREAD

**Issue by dhilgarth** [OfficeDev/office-js#1651]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
Calling `Office.context.document.getSelectedDataAsync(Office.CoercionType.SlideRange` should return an array of all selected slides.  
And I am pretty sure it used to do that just a few days ago.

## Current Behavior
It returns only the first selected slide.

## Steps to Reproduce, or Live Example
Sample Add-in:
https://github.com/dhilgarth/PowerPointIssueIncorrectSelection

1. Select multiple slides with Ctrl + Click
2. Click on Run in Taskpane

## Context
I am trying to insert a slide after all of the currently selected ones.

## Your Environment
* Platform: Office on the web
* Host: PowerPoint
* Operating System: Windows 10 1909
* Browser: Chrome, Edge Chromium, Firefox

**Comment by lliu113** [comment]
@dhilgarth - sorry for the belated response to this, and thanks for reporting this issue! I'm able to repro this online, will open up a bug to track this internally. 

Bug tracking #:5160518

**Comment by zohaibr** [comment]
Hello - Following up on this issue. This has not been fixed yet.

**Comment by danbratton** [comment]
Hello, we're working on a PowerPoint add-in where this defect is severely impacting us. Is there an expected timeline to resolve? Please let me know if I can provide any information or help in any way.
