### ISSUE TITLE
goToById(Next, Index) in PowerPoint doesn't clear selection from previous slide

### ISSUE THREAD

**Issue by dhilgarth** [OfficeDev/office-js#1652]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
When navigating to a slide with `goToById(..., Index)` that new slide should be the only selected slide.

## Current Behavior
The slide to which is being navigated is added to the list of selected slides.

## Steps to Reproduce, or Live Example
1. Insert a second slide
2. Select first slide manually
3. Click on Run
4. Slides 1 and 2 are now selected

Sample Add-in:
https://github.com/dhilgarth/PowerPointIssueExtendedSelection

## Context
I want to navigate to the next slide.
The bigger picture is this:
1. I want to insert a new slide
2. After adding the new slide, I want to navigate to the inserted slide, so it is displayed in the content area and be the only selected slide
3. I want to insert another slide after the currently selected one, i.e. after the one I previously inserted and navigate to it.

This is currently impossible because of this bug and bugs #1650  and #1651 

## Your Environment
* Platform: Office on the web
* Host: PowerPoint
* Operating System: Windows 10 1909
* Browser: Chrome, Edge Chromium, Firefox

Video: https://cloud.sovarto.com/f/11f3ee09a1224de9a4cc/

**Comment by bcziommer-sovarto** [comment]
Any update on this?
It's still happening
