### ISSUE TITLE
Add a binding from a prompt and get selected range with Office.js API

### ISSUE THREAD

**Issue by Nassim33** [OfficeDev/office-js#1653]
I want to get the values of a range binding from a prompt. To implement this I follow the spec: [Add a binding from a prompt](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/bind-to-regions-in-a-document-or-spreadsheet#add-a-binding-from-a-prompt)
## Expected Behavior

When I call the method Office.select("bindings#myBinding").getDataAsync I expect to get the the values corresponding to the range binding.
## Current Behavior

The method Office.select("bindings#myBinding").getDataAsync work only if the range binding contains one cell.
## Steps to Reproduce, or Live Example

* Link to live example: https://gist.github.com/Nassim33/4131bf1e73ca92663481a6e828035eef#file-get-data-binding-from-a-prompt-excel-yaml

* Additional details:
For testing,
1 - click on "Set binding on data" button (to create a binding on the cells to get their values)
2 - click on "Get data" button (to get the values for the binding)
3 - the problem occured
![image](https://user-images.githubusercontent.com/12541080/108683455-e7cf6080-74f1-11eb-93dd-6ebb9efcc44d.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.13029.20342
* Operating System: Windows 10
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lumine2008** [comment]
Thanks @Nassim33 , i can repro this issue, a bug (4895051) is logged to track this issue.

**Comment by lumine2008** [comment]
Thanks @Nassim33 , Our team has done some investigation, we suggest that you could use our workbook.bindings API to add a binding to multiple cells.  
`const newBinding = context.workbook.bindings.add("A1:A100","Range","cc1c.onDataChangedBinding:"+"A1:A100");
`

PS. Common binding API (document.bindings) does not support add binding to multiple cells which is by design.

**Comment by techindia2010** [comment]
Excel.BindingCollection class donot have addFromPromptAsync method?! 

Is there any possibility in office.js, so that user can select range in excel as shown in picture (Prompt dialog box) by author?
