### ISSUE TITLE
xample functions return #N/Ain Web

### ISSUE THREAD

**Issue by CristovaoTorres** [OfficeDev/office-js#1657]
I'm having trouble with the custom function.

only on the web I always have the return # N / A

yesterday it worked perfectly

![image](https://user-images.githubusercontent.com/46796748/108741123-262a4700-7515-11eb-8a88-9dd36eacd443.png)

**Comment by efremsternbach** [comment]
I'm seeing similar problems when trying to troubleshoot access to our company add-in from office.com. The add-in functions correctly when using desktop excel on windows or mac. The taskpanes seem to be working but the customfunctions are not.

I see many warnings in the javascript console with the form

`Could not load content for https://c1h-excel-15.cdn.office.net/x/s/*.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

where I've put a * to indicate that there is additional stuff in the path.

When I try to view the urls in a browser I get 404 error. Either something is wrong on office.com or there is some new configuration they haven't mentioned. I've tested this on several browsers and systems.

**Comment by grangeryy** [comment]
Sorry for the issue. We've already identified the root cause and we are working on the fix. Will update with you the progress. Thx!

**Comment by grangeryy** [comment]
Hey @CristovaoTorres this issue is already mitigated. Please check if CF work on Web. Thx!

**Comment by CristovaoTorres** [comment]
> Hey @CristovaoTorres this issue is already mitigated. Please check if CF work on Web. Thx!

Hello.
It works for me. TKS ;)
