### ISSUE TITLE
npm run start:desktop shows add-in error

### ISSUE THREAD

**Issue by yiquanchaoren** [OfficeDev/office-js#1658]
I follow the link, do a test in my local excel
https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows

When I run the "npm run start:desktop" in command, the opened excel shows the error:

![image](https://user-images.githubusercontent.com/35981627/108795405-68a95d80-75c1-11eb-84e8-e148fb933b70.png)

my excel version:
![image](https://user-images.githubusercontent.com/35981627/108795523-a7d7ae80-75c1-11eb-87b8-639a633d8767.png)

I don't know why, please help me.

**Comment by yiquanchaoren** [comment]
Anybody? Is the document is wrong?

**Comment by AlexJerabek** [comment]
Hi @yiquanchaoren,

Let me tag @akrantz to help investigate.

Also, have you tried [clearing the cache](https://docs.microsoft.com/office/dev/add-ins/testing/clear-cache) before running `npm run start`? That might help get Office in a good state before sideloading the add-in.

**Comment by akrantz** [comment]
You can turn on runtime logging using `npx office-addin-dev-settings runtime-log --enable` and then open that file with VS Code. It will update as logging is written. 

Also make sure that the dev-server is running, either in VS Code using Terminal, Run Task, Dev Server, or outside using `npm run dev-server`.  For an add-in to run, it has to first load from the SourceLocation in the manifest, which by default is the dev server port `https://localhost:3000/"

**Comment by yiquanchaoren** [comment]
> Hi @yiquanchaoren,
> 
> Let me tag @akrantz to help investigate.
> 
> Also, have you tried [clearing the cache](https://docs.microsoft.com/office/dev/add-ins/testing/clear-cache) before running `npm run start`? That might help get Office in a good state before sideloading the add-in.

I tried, but not work. I strictly install the document step operation, which has no effect on the desktop excel.

**Comment by yiquanchaoren** [comment]
> You can turn on runtime logging using `npx office-addin-dev-settings runtime-log --enable` and then open that file with VS Code. It will update as logging is written.
> 
> Also make sure that the dev-server is running, either in VS Code using Terminal, Run Task, Dev Server, or outside using `npm run dev-server`. For an add-in to run, it has to first load from the SourceLocation in the manifest, which by default is the dev server port `https://localhost:3000/"

I met the error in the desktop excel, pure nodejs code, not using vs code.
 I strictly install the document step operation, which has no effect on the desktop excel.

**Comment by grangeryy** [comment]
Hey @yiquanchaoren, 

1. Does this issue also happen for you in Excel on the web? https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-online (npm run start:web)
2. You may have a try to see if it could help at least load the add-in successfully by: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins#sideload-your-add-in
