### ISSUE TITLE
Office PowerPoint 1.2 - Issue in method insertSlidesFromBase64

### ISSUE THREAD

**Issue by sahil1504001** [OfficeDev/office-js#1659]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Office PowerPoint 1.2 API - insertSlidesFromBase64 is failing for given base64 data

## Expected Behavior
The slide should be added to the PowerPoint opened.

Note:
1. The base64 is present inside a git gist:- https://gist.github.com/sahil1504001/fb38689ff8929656f6161f3efa1a48fa
2. The PowerPoint.createPresentation is working perfectly fine 

## Current Behavior
We're trying to use the insertSlidesFromBase64 method with mentioned base64 but it's failing at await context.sync() after failing it's not going even inside a catch or finally or on the next line for a try block.

**Actually, the issue is with the same base64 PowerPoint.createPresentation API is working and insertSlidesFromBase64 is failing.**

## Steps to Reproduce, or Live Example
https://gist.github.com/sahil1504001/fb38689ff8929656f6161f3efa1a48fa

## Context
I'm trying to insert a slide into a powerpoint with the mentioned base64.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: 1.2
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome

The same thing is working on Windows Installed Desktop Version [IDV] but **not working on online Excel on windows chrome**

## Useful logs
After some time of failing the API call, the PowerPoint is getting crashed.

![image](https://user-images.githubusercontent.com/79520782/108852079-286ecd00-760b-11eb-9e11-ff9a94fa302e.png)

**Comment by lliu113** [comment]
@sahil1504001 - thanks for reporting this! I've opened an internal bug to track: 4902245.
