### ISSUE TITLE
AppDomains not needed in Office add-in manifest for external domains?

### ISSUE THREAD

**Issue by stowellt** [OfficeDev/office-js#166]
I created a simple Office add-in with a manifest that has no `<AppDomains>` section. I then added the following link to the add-in .html file:

`<a href="https://www.tutorialrepublic.com">Test</a>`
When I load the add-in in either Office Online or desktop MS Word and click the link, the addin frame loads the html from www.tutorialrepublic.com.

I would have expected that this would be blocked according to the description here: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-1#specify-domains-you-want-to-open-in-the-add-in-window

Can anyone explain the discrepancy? I found I can also submit to a form and set window.location.href to external domains and they open in the addin iframe, not in a separate window as expected.

**Comment by Rick-Kirkham** [comment]
I'm consulting with the product team about this. I think the documentation is wrong. It should say that URLs with the http (as distinct from https) protocol have to be listed in AppDomains. But https domains do not need to be. (I think what the docs say was originally true but that changed at some point.) I'll report back on your StackOverflow issue when I get confirmation. Please add a comment to that SO issue if you haven't heard more in a week.
