### ISSUE TITLE
NotificationMessageAction contextData implementation not clear

### ISSUE THREAD

**Issue by AhmedJDev** [OfficeDev/office-js#1661]
Hi!

I have been able to get the notification action working and it opens a the task pane as requested. I want to pass data across and I see there is a property call contextData which I pass JSON data to. But it isn't actually clear on how to get that information because when the function is called it doesn't pass any data? Was wondering if there is any additional documentation on how it is actually used, I am pretty sure I Am getting it wrong. I know it is just a preview but would be fantastic if I can get this working as soon as possible! Thank you in advance!

Thanks,
Ahmed
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 742b29d6-6ac5-6c43-a684-b88af36eadca
* Version Independent ID: 4f13bc13-7665-fbb3-5cb8-276ef23342f9
* Content: [Office.NotificationMessageAction interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.notificationmessageaction?view=outlook-js-preview)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.notificationmessageaction.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.notificationmessageaction.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
We've provided an object called SessionData (currently in [preview](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/preview-requirement-set/outlook-requirement-set-preview#session-data)). You can access through Office.context.mailbox.item.sessionData.

Can you see if this works for your scenarios?

Thanks.
