### ISSUE TITLE
office.js use in IE11 seems to hang/can't use Office.onReady

### ISSUE THREAD

**Issue by kzkiser** [OfficeDev/office-js#1662]
## Summary
Internet Explorer does not seem to work with the office.js library.  We have a simple logon.html in place to allow a message to alert the user that IE 11 isn't supported.

## Context
This issue is in the context of an addin to Office 365 (primarily through office.com, but it can also be loaded via MS Excel Desktop version).  Once the manifest is uploaded with office 365, when you click to access the addin, the html file listed below is the first file to load.

## Expected Behavior
If the html file is opened via IE, then the javascript code displays a simple text message instead of proceeding onto the redirect.

## Current Behavior
See html section below for reference:
If the addin's logon page is accessed via a chrome/chromium based browser, then each of the console statements are hit before being redirected to the index.html file.  All works as expected.
However, if the same addin logon page is accessed via IE 11, even the first console message "reached:outside if statement" is not displayed.  
Futher efforts were tried.  If the Office.onReady is removed completely and just the redirect is included, then things can be processed normally.  So it appears that the office.js library is related to the issue.

## Steps to Reproduce, or Live Example
Here is the html file that is used in this context.
<html class="bg" lang="en-us" dir="ltr">
  <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
      <title>Office Addin</title>
  </head>
  <body>
    <script type="text/javascript">
        console.log("reached: outside if statement");
        if (window.Office){
            console.info("Setting up Office.onReady");
            console.log("reached: inside if statement");
            Office.onReady(function(info) {
              console.log("reached: Office.onReady is called");

              // Internet Explorer 6-11
              var isIE = false || !!document.documentMode;
              console.log(isIE);

              if (isIE)
                document.write("<H2>Your current configuration is not supported for Microsoft 365.</H2>")
              else {
                document.write("<p>Loading…</p>")
                if (info.host === Office.HostType.Excel) {
                  console.info("host = excel");
                }
                if (info.platform === Office.PlatformType.PC) {
                   //pc code goes here
                }
                console.info(`Office.js is now ready in ${info.host} on ${info.platform}`);
                window.location.href="../index.html";
              }
            });
        }
     </script>
  </body>
</html>

## Your Environment
Office.com MS Excel used, but can also be loaded from Desktop Excel
Windows 10 OS
Chrome browser - works
IE11 browser - does not

## Speculation/Further Question:
I have done some googling on the issue, and have come across a few discussions about potential timing issues in IE11 with the office.js library.  But I have been unable to find anything concrete describing what I am seeing.
Is this a ES5/ES6 issue?
Is there some way to use Office.onReady within IE11?

Please let me know if I can provide more details.  Thanks!

**Comment by sumurthy** [comment]
@kzkiser Could you please try this approach and see if it works?
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/initialize-add-in#initialize-with-officeinitialize

**Comment by kzkiser** [comment]
I tried the following html (see bottom), however even in a chrome browser, the initialize isn't called.  I could put a break point when I set the call back, but the contents never fired.  Checking the break point, the Office object seemed to already be populated, which makes me think the initialize has already happened.  We get it too late in the startup to work.

<html class="bg" lang="en-us" dir="ltr">
  <head>
      <meta charset="UTF-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
      <title>SAS Office Addin</title>
  </head>
  <body>
    <script type="text/javascript">
		Office.initialize = function () {
			var isIE = false || !!document.documentMode;
			console.log(isIE);


			if (isIE)
				document.write("<H2>Your current configuration is not supported for Microsoft 365.</H2>")
			else {
				document.write("<p>Loading…</p>")
				if (info.host === Office.HostType.Excel) {
					console.info("host = excel");
				}
				if (info.platform === Office.PlatformType.PC) {
				  // Make minor layout changes in the task pane.
				}
				window.location.href="../index.html";
		    }
		};
     </script>
  </body>
</html>

**Comment by sumurthy** [comment]
Thanks for the details. We'll look into this.

**Comment by kzkiser** [comment]
I believe I have found a way around this.  I believe this was developer error.  There was non-vanilla javascript in the original that was causing issues.  The timing issue that I was trying to recreate was a red herring.  Sorry for the confusion.
