### ISSUE TITLE
Cannot side load Excel Addin in desktop Excel

### ISSUE THREAD

**Issue by paulfrench** [OfficeDev/office-js#1663]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I've followed the instructions as exactly given at https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins

This did work for me about 3 months ago and the network share catalog was still setup. I deleted and added the new manifest and restarted desktop Excel. The new manifest did not appear and the old one had gone. I tried creating a new shared folder with my manifest and added that as a trusted catalog (and selected require in menu) but still it will not show up when I click "My Addins" and "Shared Folder"

## Expected Behavior
I should see my Addin in the Office Add-ins window

## Current Behavior
Side loading the same manifest file in the web version of Excel works fine.

## Steps to Reproduce, or Live Example
As given in link above except I don't get the expected result

## Your Environment

* Windows 10 Enterprise
* Host [Excel]
* Office version number: Microsoft 365 Apps for enterprise
* Excel Version 2012 (Build 13530.20528)

**Comment by paulfrench** [comment]
I created a new Yo office project and generated a default project holding the manifest only. This appears okay in the office addin list. So it does not like my manifest, yet this manifest loads fine in the web version. How do I find out what the issues are?

**Comment by paulfrench** [comment]
Okay, running npm run validate gives me some clues what it does not like about the manifest. I will fix the issues it highlights and see if that helps. Running npm run validate against the default manifest still gives 3 errors but it still loads okay so I will assume these are acceptable errors while developing against localhost

Error #1: 
Missing Support URL: The manifest support URL could not be found. (link: undefined)

Error #2: 
Localhost Manifest High Resolution Icon URL: The manifest high resolution Icon URL should not be localhost. (link: undefined)  - Details: https://localhost:3000/assets/icon-80.png

Error #3: 
Localhost Manifest Icon URL: The manifest icon URL should not be localhost. (link: undefined)
Details: https://localhost:3000/assets/icon-32.png

**Comment by paulfrench** [comment]
It now loads okay, apologies for raising issues. It did not like using svg instead of png in desktop Excel. I created png for the svg icons and all loaded okay. Is there any where you can see the errors why it can't load the manifest? Trial and error is a pain! Cheers

**Comment by mattgeim** [comment]
@paulfrench the various parts of the manifest are available in the documentation in more detail (example - [IconUrl](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/iconurl)),  we will  also investigate the ask around unsupported icons being reported back as part of the validator.

Thanks!
