### ISSUE TITLE
Excel AddIn - Desktop - Window.open (url) shows blank dialog box instead of a new window for pdf files in latest Excel versions

### ISSUE THREAD

**Issue by kayramu** [OfficeDev/office-js#1665]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior

 window.open(url) on Ribbon or Taskpane should open a new window opening pdf files (which is in a different domain). 
## Current Behavior

 window.open(url) is showing a blank dialog instead of a new window with a pdf file. This is only happening in the latest versions of Excel for example - 16.0.13628.20448 64-bit.
This is working fine on Excel version 16.0.12527.21594 32 bit.
## Steps to Reproduce, or Live Example

* Link to live example: ______
Attached sample Manifest file (pick only latest zip file please)

Reproduction steps:
1.	Launch add-in
2.	Click on Instruction Manual icon from the ribbon / Click on the Terms of Use link within the "New Return" click on the taskpane.
3.	Observe pop up dialog appears but no content is displayed.

The above issue only occurs in the latest versions of Excel. This is working fine on Excel version 16.0.12527.21594 32 bit.

[VATTool.zip](https://github.com/OfficeDev/office-js/files/6038199/VATTool.zip).

<img width="593" alt="Ribbon" src="https://user-images.githubusercontent.com/9076497/109051138-1d32a480-76d2-11eb-8226-e8589f08f691.png">

* Additional details:
  1. ______This works all fine on office online.
  2. ______
  3. ______

## Context

We have almost finished developing an Excel AddIn and is currently held by this issue by the Microsoft Certification team to publish to AppSource. This has caused so much pain going back and forth as we couldn't reproduce it.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___Windows ___
* Host [Excel, Word, PowerPoint, etc.]: __Excel____
* Office version number: __ Microsoft 365 on Windows Excel version 16.0.13628.20448 64-bit.____
* Operating System: __All____
* Browser (if using Office on the web): ___All browsers. _

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

I have attached Manifest file which you can use to test this issue.

Work Around:

We have the below AppDomains used in our manifest as we use these domains in our App and needs to open these files as hrefs etc.
<AppDomain>https://csgexternal.ey.com</AppDomain>
<AppDomain>https://vatefiling.ey.com</AppDomain>
<AppDomain>https://pub.ey.com</AppDomain>

By adding these domains in the Manifest, all the files in these domains are opening as dialogs instead of new windows and failing for only pdfs in the latest version. Even normal pages also look a bit odd in the dialog. This is because the domains listed in the Manifest are opened in IE and not the default browser. And this opens as a Dialog and not new window.
This issue only occurs in the latest Excel versions. Even changing default browsers will not make any impact.

Solution:
If we get rid of all these <AppDomain>s in the Manifest, when clicking on the links, they are opened in Default browsers in a new window without any issues. So there is something breaking here with the <AppDomain> listing and the latest versions of Excel.

**Comment by lliu113** [comment]
@kayramu - thanks for reporting this, I'm sorry this has caused so many issues with validation. 

We will take a look internally, will update when we know more.

**Comment by lliu113** [comment]
Updating with bug number: 4955355
