### ISSUE TITLE
Outlook for Mac, body.setAsync call during ItemSend event breaks inline images with a local source, in body and in signature

### ISSUE THREAD

**Issue by ngelsi** [OfficeDev/office-js#1666]
The Add-in subscribes to the ItemSend event in the XML using

```XML
<ExtensionPoint xsi:type="Events">
  <Event Type="ItemSend" FunctionExecution="asynchronous" FunctionName="sendEmail" />
</ExtensionPoint>
```

which then inside the sendEmail function call, retrieves the e-mail body using

```JS
Office.context.mailbox.item.body.getAsync(Office.CoercionType.Html, htmlCallback)
```

The URLs of links in the e-mail body are appended with additional query parameters, using regex searching and string replacing. Afterwards the changed body is set using

```JS
Office.context.mailbox.item.body.setAsync(processedHtml, { coercionType: Office.CoercionType.Html }, processedCallback)
```

The process completes without errors on all tested platforms (Outlook on the web, Windows Desktop, Outlook for Mac). However, on Outlook for Mac, if the e-mail contains inline images, or contains a signature with an inline image, which is located on the user's computer, the images are broken, and only the alt text of the images are displayed. This behavior is not present on the Outlook on the web, and Windows Desktop Outlook versions, there the inline images are still correctly being displayed.

## Expected Behavior
It is expected that the body.setAsync call during ItemSend event handling would not break inline images inside the e-mail on Outlook for Mac, as it is working fine on other platforms.

## Current Behavior
Currently on Outlook for Mac, during ItemSend event handling, if a body.setAsync call is made to change the body of the e-mail, any inline images, or inline images in a signature, which are located on the user's computer, are broken, and only their alt text is displayed. This behavior is not present on other platforms.

## Steps to Reproduce, or Live Example

* Additional details:
  0. Use Outlook for Mac version 16.44
  1. The Add-In should subscribe to the ItemSend event using the Events extension point.
  2. The e-mail being sent out should contain inline images, or a signature with an inline image, where the image is located on the user's computer.
  3. In the function which is called in the ItemSend event subscription, retrieve the body of the e-mail using body.getAsync, and then replace the body using body.setAsync.
  4. The sent out e-mail will not display the inline images, only their alt text.

## Context
We would like to enrich the links in the outgoing e-mail with additional query parameters. For this, we have to retrieve the complete body, do link processing using regex and string replacing, and then set back the changed body. This has been working fine for all platforms altogether.  However, during one of the internal tests, we experienced that on Outlook for Mac, the inline images are getting broken during the procedure. At this moment we do not have any workaround for this, so we would need to completely disable this feature in Outlook for Mac.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.44 (20121301)
* Operating System: MacOS

## Useful logs

- Console errors: There are no errors returned by the Office JS in any asynchronous calls.
- Screenshots
<img width="348" alt="2021-02-25 09_52_21-Outlook for Mac_ Enabling link processing removes the images from the e-mail for" src="https://user-images.githubusercontent.com/12906850/109128071-67a63680-774f-11eb-99a3-1944cc63813d.png">

**Comment by rklaui** [comment]
Problem also observed in Outlook for Mac version: 16.46 (21021202).

**Comment by exextoc** [comment]
Thanks for sharing the issue. We could reproduce this issue at our end. We have added this to our backlog but unfortunately we do not have any timelines to share for the same.

**Comment by exextoc** [comment]
Hey @ngelsi ,

Needed a quick check from you. Are you seeing this issue on the new Outlook for Mac UI or the Old Outlook for Mac UI?

**Comment by ngelsi** [comment]
@exextoc Currently we are testing on the old Mac UI. The new Mac UI has even more show stopping bugs so we are currently recommending the old Mac UI to the customers for the time being.

**Comment by exextoc** [comment]
@ngelsi Can you share details on what type of issues are you facing on new Mac UI ?

**Comment by ngelsi** [comment]
@exextoc General reliability issues. In some cases the asynchronous requests to get attributes (subject, recipient, body, etc.) of the e-mail fail with a failed async result stating an 'internal error'. In these cases, the whole process comes to a halt, and even if the call of the completed method on the Office js event object is executed, the processing doesnt end, and the '<add-in> is working on your request' message on top of the compose screen stays there indefinitely.

Example async result returned by the Office JS interface in these cases:

> {"name":"Internal Error","message":"An internal error has occurred.","code":5001}

As we could not make this reproducible and it seems to be happening in random cases and during random function calls, we did not open specific GitHub issues for them. Currently this is the only issue where we have a clear reproduction path.

**Comment by exextoc** [comment]
@ngelsi Could you please provide the APIs names which are not reliable. Also, I would like to inform you that the 1.8 API set is not supported in the new UI.

**Comment by ngelsi** [comment]
@exextoc 

Office JS API interface calls which the add-in is making, in order:

Office.context.mailbox.item.body.getTypeAsync
Office.context.mailbox.item.body.getAsync
Office.context.mailbox.item.to.getAsync
Office.context.mailbox.item.subject.getAsync
Office.context.mailbox.item.from.getAsync
Office.context.mailbox.item.loadCustomPropertiesAsync
customProperties.saveAsync
Office.context.mailbox.item.body.setAsync

As i mentioned eariler, we cant really determine at this moment an exact path to produce the aforementioned internal errors. We only have observations, such as the internal error usually happens after a fresh Outlook start during sending out the first e-mail, and the recipient retrieval fails most of the time.

The biggest problem we are facing so far is that seems that after an internal error, the event.completed() call seems to be no longer registered by the JS API, and the process never finishes, therefore completely preventing the e-mail being sent out, without us having a way to cancel the process or inform the user, since even notification display call seems to fail. As if the JavaScript engine just stops internally.

**Comment by exextoc** [comment]
These APIs work fine for us. 
Please share the screenshots/logs/trace as and when these errors occur. 
Furthermore, we can organize debugging sessions to address the issue.

**Comment by ngelsi** [comment]
For now, we have opted to mark the version of the add-in which uses the on-send feature as alpha, and we will create an add-in which will manually process the e-mail using a button click. When we will have more information or steps to reproduce the internal errors, we will open another issue here. Nonetheless we would like to use the on-send feature version as the definitive one in the near future.

On this note, i would like to re-route the topic of this conversation to the original issue, which is the inline image disappearance during on-send event on Outlook for Mac, since that has been properly identified as a bug.

**Comment by exextoc** [comment]
@ngelsi Apologies for missing update on this issue. 
As a workaround, users can switch to the [New Outlook for Mac](https://support.microsoft.com/en-gb/office/the-new-outlook-for-mac-6283be54-e74d-434e-babb-b70cefc77439?ui=en-us&rs=en-gb&ad=gb) experience which works as expected. We are not prioritizing this fix on classic Mac UI; please reopen the issue in case the workaround does not solve your scenario.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
