### ISSUE TITLE
outlook online Office.context.mailbox.item.body.setAsync bug

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#1667]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

question 1:

demo code
```
var setHtml = function (a) {
    return new Office.Promise(function (resolve) {
        Office.context.mailbox.item.body.setAsync( a,
            {coercionType: Office.CoercionType.Html}, (function (result) {
            console.log(result);
            }));
        });
};

var a = '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"https://protect-us.mimecast.com/s/jZL3CJ6PLGU269xgSVOhmJ\">\n<html xmlns=\"https://protect-us.mimecast.com/s/eHq3CKr6MKtYX7LZsv1L48\">\n<head>\n    <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n</head>\n<body style="height: 100% !important; width: 100% !important; background-color: #ffffff; margin: 0; padding: 0;">\n<img src=\"https://assets.codepen.io/3/kiwi.svg\" width=\"100\" height=\"50\" alt=\"BCGDV-ZOOM\" /\n</body>\n</html>';

setHtml(a);
```
got error result:
```
OSF.DDA.AsyncResult {value: undefined, status: "failed", error: OSF.DDA.Error}
error: OSF.DDA.Error
code: 5000
message: "The operation is not supported."
name: "Host Error"
__proto__: Object
status: "failed"
value: undefined
```
if change svg to jpg or png, it will work fine:
```
var a = '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"https://protect-us.mimecast.com/s/jZL3CJ6PLGU269xgSVOhmJ\">\n<html xmlns=\"https://protect-us.mimecast.com/s/eHq3CKr6MKtYX7LZsv1L48\">\n<head>\n    <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n</head>\n<body style="height: 100% !important; width: 100% !important; background-color: #ffffff; margin: 0; padding: 0;">\n<img src=\"https://www.paintshoppro.com/static/psp/images/pages/seo/ui-screenshot.jpg\" width=\"100\" height=\"50\" alt=\"BCGDV-ZOOM\" /\n</body>\n</html>';
```

question 2:
demo code
```
var setHtml = function (a) {
    return new Office.Promise(function (resolve) {
        Office.context.mailbox.item.body.setAsync( a,
            {coercionType: Office.CoercionType.Html}, (function (result) {
            console.log(result);
            }));
        });
};

var a = '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"https://protect-us.mimecast.com/s/jZL3CJ6PLGU269xgSVOhmJ\">\n<html xmlns=\"https://protect-us.mimecast.com/s/eHq3CKr6MKtYX7LZsv1L48\">\n<head>\n    <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n<style type="text/css">\nbody{height:100% !important; margin:0; padding:0; width:100% !important;}\n</style>\n</head>\n<body style="height: 100% !important; width: 100% !important; background-color: #ffffff; margin: 0; padding: 0;">\n<img src=\"https://www.paintshoppro.com/static/psp/images/pages/seo/ui-screenshot.jpg\" width=\"100\" height=\"50\" alt=\"BCGDV-ZOOM\" /\n</body>\n</html>';

setHtml(a);
```
the root cause code is:
```
<style type="text/css">\nbody{height:100% !important; margin:0; padding:0; width:100% !important;}\n</style>
```
the whole office page will crash.

![image](https://user-images.githubusercontent.com/1878089/109140954-1e2e0980-7798-11eb-8530-798172f0309b.png)

**Comment by exextoc** [comment]
Bug already created for this- Bug 1975767<https://o365exchange.visualstudio.com/959adb23-f323-4d52-8203-ff34e5cbeefa/_workitems/edit/1975767>: New GitHub Issue [OfficeDev/office-js]: outlook online Office.context.mailbox.item.body.setAsync bug

Thank you,
[MS Logo]       Neelu Agrawal
Software Engineer II
nagrawal@microsoft.com
________________________________

**Comment by exextoc** [comment]
> question 1:
> 
> demo code
> 
> ```
> var setHtml = function (a) {
>     return new Office.Promise(function (resolve) {
>         Office.context.mailbox.item.body.setAsync( a,
>             {coercionType: Office.CoercionType.Html}, (function (result) {
>             console.log(result);
>             }));
>         });
> };
> 
> var a = '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"https://protect-us.mimecast.com/s/jZL3CJ6PLGU269xgSVOhmJ\">\n<html xmlns=\"https://protect-us.mimecast.com/s/eHq3CKr6MKtYX7LZsv1L48\">\n<head>\n    <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n</head>\n<body style="height: 100% !important; width: 100% !important; background-color: #ffffff; margin: 0; padding: 0;">\n<img src=\"https://assets.codepen.io/3/kiwi.svg\" width=\"100\" height=\"50\" alt=\"BCGDV-ZOOM\" /\n</body>\n</html>';
> 
> setHtml(a);
> ```
> 
> got error result:
> 
> ```
> OSF.DDA.AsyncResult {value: undefined, status: "failed", error: OSF.DDA.Error}
> error: OSF.DDA.Error
> code: 5000
> message: "The operation is not supported."
> name: "Host Error"
> __proto__: Object
> status: "failed"
> value: undefined
> ```
> 
> if change svg to jpg or png, it will work fine:
> 
> ```
> var a = '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"https://protect-us.mimecast.com/s/jZL3CJ6PLGU269xgSVOhmJ\">\n<html xmlns=\"https://protect-us.mimecast.com/s/eHq3CKr6MKtYX7LZsv1L48\">\n<head>\n    <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n</head>\n<body style="height: 100% !important; width: 100% !important; background-color: #ffffff; margin: 0; padding: 0;">\n<img src=\"https://www.paintshoppro.com/static/psp/images/pages/seo/ui-screenshot.jpg\" width=\"100\" height=\"50\" alt=\"BCGDV-ZOOM\" /\n</body>\n</html>';
> ```
> 
> question 2:
> demo code
> 
> ```
> var setHtml = function (a) {
>     return new Office.Promise(function (resolve) {
>         Office.context.mailbox.item.body.setAsync( a,
>             {coercionType: Office.CoercionType.Html}, (function (result) {
>             console.log(result);
>             }));
>         });
> };
> 
> var a = '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"https://protect-us.mimecast.com/s/jZL3CJ6PLGU269xgSVOhmJ\">\n<html xmlns=\"https://protect-us.mimecast.com/s/eHq3CKr6MKtYX7LZsv1L48\">\n<head>\n    <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n<style type="text/css">\nbody{height:100% !important; margin:0; padding:0; width:100% !important;}\n</style>\n</head>\n<body style="height: 100% !important; width: 100% !important; background-color: #ffffff; margin: 0; padding: 0;">\n<img src=\"https://www.paintshoppro.com/static/psp/images/pages/seo/ui-screenshot.jpg\" width=\"100\" height=\"50\" alt=\"BCGDV-ZOOM\" /\n</body>\n</html>';
> 
> setHtml(a);
> ```
> 
> the root cause code is:
> 
> ```
> <style type="text/css">\nbody{height:100% !important; margin:0; padding:0; width:100% !important;}\n</style>
> ```
> 
> the whole office page will crash.
> 
> ![image](https://user-images.githubusercontent.com/1878089/109140954-1e2e0980-7798-11eb-8530-798172f0309b.png)

Inserting svg images in owa through the setAsync api is not permitted by design. Request you to go for other image formats like jpeg/png/gif etc.

**Comment by hello-chenchen** [comment]
@exextoc is there any official description for question 1? and what about question 2?

**Comment by exextoc** [comment]
> @exextoc is there any official description for question 1? and what about question 2?

Unfortunately we don't have any official documentation for question 1 at this moment. We will make sure that we update the official docs with this scenario.

As for question 2, is this applicable for a particular browser?

**Comment by hello-chenchen** [comment]
I haven't test all the browser, but i think the answer is it will happen for all browser. At least, it will happened on Chrome and new Microsoft Edge(chromium base) with my office365 E3 license. for every add-in, you can execute my demo code under your official add-in, such as OneNote on outlook online: https://outlook.office.com/calendar/view/week with a new event. it will happened for 100%.
```
var setHtml = function (a) {
    return new Office.Promise(function (resolve) {
        Office.context.mailbox.item.body.setAsync( a,
            {coercionType: Office.CoercionType.Html}, (function (result) {
            console.log(result);
            }));
        });
};

var a = '<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"https://protect-us.mimecast.com/s/jZL3CJ6PLGU269xgSVOhmJ\">\n<html xmlns=\"https://protect-us.mimecast.com/s/eHq3CKr6MKtYX7LZsv1L48\">\n<head>\n    <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\"/>\n<style type="text/css">\nbody{height:100% !important; margin:0; padding:0; width:100% !important;}\n</style>\n</head>\n<body style="height: 100% !important; width: 100% !important; background-color: #ffffff; margin: 0; padding: 0;">\n<img src=\"https://www.paintshoppro.com/static/psp/images/pages/seo/ui-screenshot.jpg\" width=\"100\" height=\"50\" alt=\"BCGDV-ZOOM\" /\n</body>\n</html>';

setHtml(a);
```
![image](https://user-images.githubusercontent.com/1878089/110597200-313ed180-81bb-11eb-9704-53e6335b8481.png)

![image](https://user-images.githubusercontent.com/1878089/110597599-b9bd7200-81bb-11eb-98fe-cc64bcc3e9f8.png)

**Comment by exextoc** [comment]
We tried using this code snippet and yes the OWA crashes. It has something to do with this styling.

`<style type="text/css">\nbody{height:100% !important; margin:0; padding:0; width:100% !important;}\n</style>
`

Right now we don't have a root cause for this. As a workaround either you can not use this <style> or use Outlook Win32 client (where this works fine). We will create a bug in our backlog however we don't have any timelines to share at this moment.

Also we will update our documentation about OWA not allowing svg images to be inserted by office-js apis.
