### ISSUE TITLE
PowerPoint insertSlidesFromBase64 method does not return in Office Online

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#1668]
## Expected Behavior
insertSlidesFromBase64 promise should resolve after inserting slides.

## Current Behavior
insertSlidesFromBase64 promise does not resolve after inserting slides. So we don't know if inserting is finished.

## Steps to Reproduce, or Live Example
You can  use the "Insert slides from other presentations" snippet in Script Lab and add a console.log after the sync method.

```
await PowerPoint.run(async function(context) {
    context.presentation.insertSlidesFromBase64(chosenFileBase64);
    console.log("Start Inserting");
    await context.sync();
    console.log("Finished Inserting"); // This line is not called
});
```
Observe that "Finished Inserting" is never called.

## Context
Our addin insert slides but we can't give the user feedback when the operation is finished.

## Your Environment
* Platform: Office on the web
* Host: PowerPoint
* Operating System: Windows
* Browser: Chrome 88.0.4324.190

**Comment by barisbikmaz** [comment]
Probably a duplicate of #1650

**Comment by ononder** [comment]
This should be fixed now. Thanks for the feedback and report.
