### ISSUE TITLE
Custom Function not working in Excel Desktop with array parameters

### ISSUE THREAD

**Issue by CristovaoTorres** [OfficeDev/office-js#1669]
My function doesn't work on the desktop, but it works on the Web return #VALOR!

I have a function called RESULTADO that receives any parameters
![image](https://user-images.githubusercontent.com/46796748/109185252-997ac580-776e-11eb-88ab-977016f1bb0e.png)

All other functions in my project work perfectly on the Desktop and WEB

Project is here:https://github.com/CristovaoTorres/CustoFunctionNorWorkingDesktop

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2101 (build 13628.20448
* Operating System: Windows 10 Home Single 18363.1379

**Comment by CristovaoTorres** [comment]
Do you have any news about the issue?

**Comment by CristovaoTorres** [comment]
Any news?

**Comment by AlexJerabek** [comment]
Hi @CristovaoTorres, 
I'll send a reminder to the feature crew to investigate this. In the meantime, can you please provide more information about the desktop behavior? When you say it doesn't work, what happens? Thanks!

**Comment by CristovaoTorres** [comment]
> Hi @CristovaoTorres,
> I'll send a reminder to the feature crew to investigate this. In the meantime, can you please provide more information about the desktop behavior? When you say it doesn't work, what happens? Thanks!

Hi.
My function doesn't work on the desktop, return #VALOR!

![image](https://user-images.githubusercontent.com/46796748/110206495-c1e47d00-7e5c-11eb-9581-77b840383e79.png)

**Comment by grangeryy** [comment]
We are investigating into this one and will update the finding later. Thx!

**Comment by CristovaoTorres** [comment]
@grangeryy 
Give preference to https://github.com/OfficeDev/office-js/issues/1700
