### ISSUE TITLE
WebView2 not being used in Outlook add-in despite requirements of table being satisfied

### ISSUE THREAD

**Issue by neville-jones** [OfficeDev/office-js#1670]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

This document does not seem to contain accurate information, based on our testing.

Our test environment is:
- Windows 10 Enterprise version 10.0.18363 (from System Information)
- Microsoft 365 Apps for enterprise Version 2101 (Build 13628.20448 Click-to-Run); Current Channel
- Edge WebView2 is installed from https://aka.ms/webview2installer (using Evergreen Bootstrapper); control panel listing "Microsoft Edge WebView2 Runtime" version 88.0.705.74 (same version as Edge)

This environment satisfies the last row of the table on the referenced page. 

If we start Outlook, create a new message and start our compose pane add-in, then use Sysinternals Process Explorer (https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) to determine what process the add-in is running under (using the bullseye cursor of the tool), the Process Explorer reports it as Win32WebViewHost.exe with details of 
`C:\Windows\SystemApps\Microsoft.Win32WebViewHost_cw5n1h2txyewy\Win32WebViewHost.exe`

If we right-mouse click in the pane of the add-in then no context menu is shown, which I believe is expected for WebView (EdgeHTML based) but not for WebView2 where a context menu should appear.

We have also repeated this with Current Preview channel and Beta channel versions of Outlook, without any difference. We have also uninstalled the WebView2 Runtime and repeated tests; the same process name is being used so it seems to confirm Win32WebViewHost = WebView (not WebView2). We have also repeated tests using the Microsoft created "My Templates" add-in and in all cases it is using the same Win32WebViewHost process.

If the documentation is accurate, then why is WebView2 not being used by our Outlook add-in?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
I am transferring the issue from docs to the office-js repo.

**Comment by ElizabethSamuel-MSFT** [comment]
@croicu Can you take a look?

Thanks.
