### ISSUE TITLE
Synchronization between instances of the Office Word JavaScript add-in

### ISSUE THREAD

**Issue by AlexanderSokolov1** [OfficeDev/office-js#1671]
Hi folk,

I'm working on JavaScript add-in for Office Word (Win10 and Mac) and store some shared data in `OfficeRuntime.storage` (open for suggestions about other global persistent storages). Add-in displays this data on taskpane. Currently, if a user changes this data though one instance, it won't affect other add-in instances (e.g. in other open documents) until the taskpane is reopened or the add-in re-reads the data manually.

I tried HTML5 storage but it pickups values only once when add-in initialized. The Storage Event didn't work in add-in at all.

Is there a way to notify active add-in instances about changes in storage? Or somehow sync them through global event of smth?

Thanks,
Alex.

**Comment by sumurthy** [comment]
There's no event-support for Word. The Office.storage APIs are also meant for Excel. 
You may want to check-out this document to see how to store shared information: https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/persisting-add-in-state-and-settings.md

For detecting changes, I think you'll have to poll periodically.

**Comment by sumurthy** [comment]
@davidchesnut - Is there any PnP to help for this scenario?

**Comment by AlexanderSokolov1** [comment]
@sumurthy, thanks for response. I have read this article but I need a **global** persistent storage, not only on the document level.

**Comment by davidchesnut** [comment]
@sumurthy, no, there is no PNP sample for this scenario.
@AlexanderSokolov1, it sounds like you are looking for real time communication between add-in instances (potential cross-platform, cross-process)? Would it make sense to look into real time communication libraries like [SignalR](https://dotnet.microsoft.com/apps/aspnet/signalr), or similar?  

Cheers,
David

**Comment by AlexanderSokolov1** [comment]
@davidchesnut, yes, I'm looking for solution which will help me to handle scenario when the storage changed through another add-in instance (e.g. from another document of the same Word process). Some kind of the [Storage](https://www.w3schools.com/jsref/event_storage_url.asp) event is exactly what I need.

In case of SignalR (or others) I will have to use some server installed on the client machine (or somewhere else) and I will lose time for transport between this server and add-in instances. Solution looks overhead to me.

I found an article about the [shared runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime#about-the-shared-javascript-runtime) for Excel and PowerPoint and it looks like something that might help me. Is the any plans to implement something similar for Word?
If not, maybe you have any plans to add the Storage event analog for the OfficeRuntime.storage?

**Comment by AbidRahman-MSFT** [comment]
Hey @AlexanderSokolov1, 

We do have plans on bringing shared runtime for Word within the next 6 months. Please keep an eye on the O365 Add-in [blogs](https://developer.microsoft.com/en-us/office/blogs/technology/add-ins/) for an update when it is ready for developers.

Thanks,
Abid

**Comment by AlexanderSokolov1** [comment]
@AbidRahman-MSFT, great, thank you!
