### ISSUE TITLE
[Excel] Instead of Dialog Title a GUID is shown

### ISSUE THREAD

**Issue by groh-f** [OfficeDev/office-js#1674]
Sometimes when you open a dialog the title is not set correct (Add-In name or "Message send by Add-In name)  instead a GUID is shown. 

## Expected Behavior
Add-In name should be shown within the title

## Steps to Reproduce, or Live Example
There is no certain event or behaviour which seems to cause this. Further it does not appear always. It can be fine for 5 times opening the same dialog and then fail for the next 2 times you open it

## Context
This can confuse User. It looks rather strange to suddenly see a GUID within the Dialog Title

## Your Environment
We experienced this behaviour in every Environment

## Useful logs

![Capture](https://user-images.githubusercontent.com/79715498/109333846-3bc6a600-7860-11eb-823e-66aa39eb5079.PNG)

**Comment by lliu113** [comment]
@groh-f - thanks for reporting this! Just to confirm, you're seeing this on Windows, Mac and Online? Is the GUID always the same?

**Comment by groh-f** [comment]
@lliu113 Yes we were able to see it in all the environments. As far as I can see It seems like that the GUID only changes when your session changes.

**Comment by groh-f** [comment]
@lliu113 I am sorry, I talked about it with my colleagues.  We are currently only able to reproduce it reliable within Windows Excel Desktop with IE 11.  It seems like it was never a issue on Mac

**Comment by lliu113** [comment]
@groh-f - thanks for the extra info! We are able to repro this internally and have opened up a bug to track. 
Bug ID: 5023697

No ETA right now to share, but will update if that changes.

**Comment by lliu113** [comment]
@groh-f - good news, we have checked in the fix. We were using a raw pointer which sometimes caused issues during thread switching but this has been addressed. I'm going to go ahead and close this issue, thanks!
