### ISSUE TITLE
Data validation in sheet 1 is copied to other rows in sheet 1 when new rows are added to the table in sheet 2.

### ISSUE THREAD

**Issue by harri-rajala-koivu-solutions** [OfficeDev/office-js#1675]
Data validation in sheet 1 is copied to other rows in sheet 1 when new rows are added to the table in sheet 2. See comments on the example code for more information.

## Expected Behavior
Excel should not copy data validation to other rows.

## Current Behavior
Data validation is copied to other rows.

## Steps to Reproduce, or Live Example
```typescript
        await Excel.run(async (context: Excel.RequestContext) => {
            // Create Test1 sheet (delete existing sheet)
            const sheet1Name = "Test1";
            let sheet1 = context.workbook.worksheets.getItemOrNullObject(sheet1Name);
            await context.sync();
            if (!sheet1.isNullObject) {
                sheet1.delete();
            }
            sheet1 = context.workbook.worksheets.add(sheet1Name);
            // Add 7 data rows 
            sheet1.getRange("A3:A9").values = [[10], [20], [30], [40], [50], [60], [70]];
            // Add decimal data validation only to A3
            sheet1.getRange("A3").dataValidation.rule = {
                decimal: {
                    formula1: 15,
                    operator: "LessThan",
                }
            }

            // Create Test2 sheet (delete existing sheet)
            const sheet2Name = "Test2";
            let sheet2 = context.workbook.worksheets.getItemOrNullObject(sheet2Name);
            await context.sync();
            if (!sheet2.isNullObject) {
                sheet2.delete();
            }
            sheet2 = context.workbook.worksheets.add(sheet2Name);
            // Create a table with header and one data row
            sheet2.getRange("A2:A3").values = [["Table"], ["aaa"]];
            sheet2.tables.add("A2:A3", true);

            // Add 3 additional rows to this table in sheet 2
            // This is the magic line. 
            // Every row you add to this table (in sheet 2) will copy data validation from A3 to A4, A5, etc. (in sheet 1).
            // If you comment out this line then data validation is only in A3.
            sheet2.getRange("A4:A6").values = [["bbb"], ["ccc"], ["ddd"]];

            // Print existing decimal data validation. 
            // Data validation should be only in row 3, but because of this bug it is also in rows 4, 5 and 6
            for (let row = 3; row <= 9; row++) {
                const dataValidation = sheet1.getRange("A" + row).dataValidation.load("rule");
                await context.sync();
                sheet1.getRange("B" + row).values = [[JSON.stringify(dataValidation.rule.decimal)]];
            }

            sheet1.activate();
        });
```

## Context
This is a critical bug. Our Excel Add-in does not work because of this bug.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2101 Build 13628.20448
* Operating System: Windows

**Comment by qinliuMSFT** [comment]
Thanks for reporting this issue. We could repro this issue on latest Excel version, and this is also could be repro on Excel UI. We will contact Excel team to follow up the fix.

**Comment by harri-rajala-koivu-solutions** [comment]
@qinliuMSFT @lumine2008 Do you have any estimate of when this is fixed?

**Comment by qinliuMSFT** [comment]
@harri-rajala-koivu-solutions , we have fixed the bug and the fix should be available in build 16.0.13908.20000 or later. Depending on the release channel a customer is on, getting an updated build can take anywhere from 4-8 weeks, or longer if they are on the Semi-Annual Enterprise Channel.

**Comment by harri-rajala-koivu-solutions** [comment]
@qinliuMSFT Ok. Thanks.
Can you tell which Excel versions have this bug?
Do you know if there is any workaround that we could tell our customers affected by this bug?

**Comment by harri-rajala-koivu-solutions** [comment]
@lumine2008 @qinliuMSFT Can you tell which Excel versions have this bug?

**Comment by lumine2008** [comment]
I think you may need to wait for a few more weeks, please check Excel build > 16.0.13908.20000 , thanks.

**Comment by qinliuMSFT** [comment]
Hi @harri-rajala-koivu-solutions , sorry for the delay reply. 
As the fix (in build 16.0.13908.20000) still need some time to get deployed, we turned off the previous change that caused this bug, to unblock you firstly. I've confirmed that this issue is no longer repro in current Semi-Annual Channel (16.0.13127.21348) and Monthly Channel (16.0.13801.20294). Please help ensure you could also not repro this issue.
To answer your question, The Excel versions between 16.0.13318.10000 and 16.0.13328.10000 have this bug.

**Comment by harri-rajala-koivu-solutions** [comment]
@qinliuMSFT @lumine2008 Thanks!! I can confirm that I could not repro this issue anymore with the Excel version 16.0.13801.20294.

**Comment by lumine2008** [comment]
let me close the issue
