### ISSUE TITLE
"Data > Refresh All" from Excel for Windows in co-authoring mode leads to error in Excel for the web

### ISSUE THREAD

**Issue by sshukurov** [OfficeDev/office-js#1676]
I am running into an issue which can be reproduced as follows:
1. Create a new workbook in `Excel for Windows`, save it in `OneDrive`.
2. Open the same workbook in `Excel for the web`.
3. Press `Data` > `Refresh All` button in `Excel for Windows`.
4. Edit contents of any cell in `Excel for the web` instance.

`Excel for the web` instance renders the following error:
![image](https://user-images.githubusercontent.com/36232686/109339312-4ba6b000-7889-11eb-8bf2-77f2e5b62e25.png)

## Your Environment
* Platform: PC desktop, Office on the web
* Host: Excel
* Office (desktop) version number: 2101 (build 13628.20448 Click-to-Run)
* Office (web) version number: Build 16.0.13822.31876
* Operating System: Windows 10 Pro 64-bit, Version 20H2, OS build 19042.804, Windows Feature Experience Pack 120.2212.551.0
* Browser (if using Office on the web): Google Chrome Version 88.0.4324.190 (Official Build) (64-bit)

**Comment by keyur32** [comment]
Hi @sshukurov,  thanks for your issue. As it is specific to the Excel for web product, and not our extensibility model, we ask that you please click the "Give Feedback" link as this will send in the appropriate logs.  We'll also send this issue over to the Excel team in case there is a known issue (And in which case, we will reply back here).  Thanks.
