### ISSUE TITLE
ReferenceError: 'OfficeRuntime' is undefined

### ISSUE THREAD

**Issue by malikirfan** [OfficeDev/office-js#1677]
I have created an Addin using "Yo Office" for Excel Custom Functions and then changed it to Shared Runtime as per documentation. Everything works at this time. Now when I am trying to set Token in storage OR Retrieve token from Storage, getting this exception. Here are my code snippet. 
`taskpane.js
--------------------------------
Office.initialize = () => {
  document.getElementById("sideload-msg").style.display = "none";
  document.getElementById("app-body").style.display = "flex";
  //document.getElementById("run").onclick = run;    
};
Office.onReady = () => {
    $(document).ready(async function () {
        ...........

        var resp = "Success";
        try {
            const key = await OfficeRuntime.storage.getItem("UserCredentials");
        } catch (err) {
            resp = "error: " + err;
        }
        $("#txtUserName").val(resp);
    });
};`

## Expected Behavior
Appearently txtUserName field should contains "Success" i.e. UserCredentials key should retrieve.

## Current Behavior
Getting exception in "txtUserName" field: 
error: ReferenceError: 'OfficeRuntime' is undefined

[ExcelAddin.zip](https://github.com/OfficeDev/office-js/files/6053938/ExcelAddin.zip)

**Comment by jeremy-msft** [comment]
@malikirfan, thanks for reporting this issue.  Can you please provide us with details about your environment?  Additionally, if using Office on the web, please confirm whether or not you are in Private/Incognito mode.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

**Comment by malikirfan** [comment]
Hi @jeremy-msft, Hope you are doing well. Here is the required detail:

I am on Windows 10 using Excel Desktop (version: Microsoft Excel for Microsoft 365 MSO (16.0.13127.21210) 64 bit) created add-in using Yeoman generator as mentioned in [this tutorial](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows) and then converted it to Shared Runtime as per [this tutorial](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime). Though I have VS 2019 Professional on my machine but Building and Running this addin via command prompt as per tutorial (I also tried to create project via VS 2019 but it doesn't have Custom Functions and I couldn't find any tutorial how to add Custom Functions libraries in VS created Project :(  so unfortunately bound to use Command Prompt) 
Please let me know if you need more detail?

**Comment by jeremy-msft** [comment]
Thanks, we'll investigate and get back to you if we need more details.

**Comment by jeremy-msft** [comment]
Hi @malikirfan, we took a closer look and it appears this is caused by the limitations of arrow function expressions.  Could you please try again using a traditional function expression (e.g. `Office.onReady = function () {};`)?

**Comment by keyur32** [comment]
hi @malikirfan  - were you able to check with Jeremy's recommendation?  Thanks

**Comment by malikirfan** [comment]
Sorry for late response. Yes it works with traditional function. Thank you @jeremy-msft
