### ISSUE TITLE
About the Chromium Edge rollout schedule

### ISSUE THREAD

**Issue by KazuyaHarashima4500** [OfficeDev/office-js#1678]
I would like to ask the specific schedule when office add-ins that meet the conditions for becoming Chromium Edge will be changed from EdgeHTML.

I asked MR.Yanagizawa of Microsoft Japan about the situation,but Even if the following conditions are met,there is no change of Chromium Edge.
So i didn't get a definite answer from MR.Yanagizawa.
About this situation ,Can you tell me about the schdule for completing to rollout of changing to Chromium Edge?

**Comment by neville-jones** [comment]
similar to #1670  ?

**Comment by KazuyaHarashima4500** [comment]
That's the fundamental thing I would like to ask.
On top of that, I would like to ask you about the specific schedule when that is.

**Comment by lindalu-MSFT** [comment]
Hi, we can't share a specific schedule here but you can join the Insiders program. Then you'll be able to not only get preview info, but more details regarding the roll-out. [Microsoft Insiders](https://insider.microsoft.com/)
