### ISSUE TITLE
OfficeRuntime.auth.getAccessToken() not support different tenant account

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#1679]
when i use OfficeRuntime.auth.getAccessToken() under my own azure account who have create an app registrations on azure portal. it can works fine.
```
OfficeRuntime.auth.getAccessToken().then((result) => {console.log(result)})
```
but when i install this manifest.xml to other tenant account user, there is an error message:
```
code: 13005
message: "Missing grant for this add-in."
name: "Preauthorization missing."
```
does this OfficeRuntime.auth.getAccessToken() support in different office tenant account. not only under the same azure account?

**Comment by hello-chenchen** [comment]
hi @exextoc do you know this one?

**Comment by exextoc** [comment]
You may need admin authorization in the tenant that you are installing the add-in: 

https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph

From that doc:  Office cannot prompt for consent to any Microsoft Graph scopes, not even User.Read.

So admin auth is needed.

**Comment by jargil** [comment]
Take a look at our documentation, there's guidance for errors that SSO can return to you, including 13005:
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins#:~:text=Office-Add-in-NodeJS-SSO%20Conditional%20access%20/%20Multifactor%20authentication%20errors%20In,when%20the%20user's%20Microsoft%20365%20tenancy%20does%20not.

**Comment by hello-chenchen** [comment]
hi @exextoc @jargil , thank you for your suggestion.
my question is about multi-tenant situation. I have success to use OfficeRuntime.auth.getAccessToken() api to get token, but it only work for the same tenant azure account, which create the oauth app [register the add-in with Azure AD v2.0 endpoint](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs#register-the-add-in-with-azure-ad-v20-endpoint) ,i switch to other tenant azure account(which is not create the oauth app), i can only get the error message. according to the link you provided, i still don't know how to set other tenant account to approve the auth in azure. do you know the step for how to approve the auth? or it just work for the same tenant account?
If this api is only work for the same tenant account who create the oauth app, not work for other who don't create oauth app, i think it same not so much useful for our add-ins.

**Comment by jargil** [comment]
The API works for multi-tenant. The document you linked to has some details for making sure your registration is multi-tenant.

You need to grant consent for the user in the other tenant. Look at notes at the top of the link about why/when this consent will be needed:
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/grant-admin-consent-to-an-add-in

**Comment by hello-chenchen** [comment]
hi @jargil , thank you for your suggestion.
but it seems not work for me. In fact, which i mean multi-tenant is means these multi-tenant is under different AAD with different azure admin account.
these is my two different tenant which is under different AAD with different azure admin account. does this api OfficeRuntime.auth.getAccessToken() support this situation?
this is my tenant for saasbee:
![image](https://user-images.githubusercontent.com/1878089/109836924-9eb0a680-7c7f-11eb-9d34-22c820bf4e86.png)
and this is other tenant:
![image](https://user-images.githubusercontent.com/1878089/109836990-aec88600-7c7f-11eb-9bfb-2d50fdeabe43.png)

i can only grant for my AAD: saasbee. and it only work for my saasbee. please look at this screenshot.
![image](https://user-images.githubusercontent.com/1878089/109835402-24cbed80-7c7e-11eb-8003-58e1df549b1f.png)

and i don't know how to grant it for other AAD: such as zoom video communications inc. in fact, i think my app should get the tenant zoom video communications inc's grant on their azure portal. but i don't know how to grant my app on the other AAD tenant. Is it possible to grant it in different azure admin account with different AAD?

i notice that there is a create a tenant button here? do you mean the multi-tenant are under the same AAD account?
![image](https://user-images.githubusercontent.com/1878089/109837235-ecc5aa00-7c7f-11eb-9037-315ee5f13ec1.png)

thank you so much.

**Comment by jargil** [comment]
Your multi-tenant scenario is supported. If I understand correctly the problem is that you don't have admin role in the second tenant and thus you're not able to grant profile consent. For testing with users in the second tenant you'll definitely need to be able to have the rights to grant admin consent. Given you have it working in one test tenant, I assume you have added all the correct permissions in your app registration, hence this problem is not about granting any consents/permissions in your app registration, but in the tenant where you want to access the user's profile. You can never access a user's profile via the getAccessToken API without the proper consent.

If your goal is simply to test multi-tenancy, my suggestion is to setup two test tenants where you have admin role and can provide all the consents. If you must test in the Zoom tenant, then my suggestion is to work with your tenant admin to find if they could grant the admin consent to your account/app.

**Comment by hello-chenchen** [comment]
hi @jargil , thank you so much for your help.
you are right my second tenant is not the admin role. I will find out it's admin account tomorrow(the second tenant is also a test tenant AAD). Could you please told me for how to grant admin consent for the first tenant saasbee if i have the second tenant zoom video communications inc's admin account.
from you provide this link: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/grant-admin-consent-to-an-add-in
in fact, on the second tenant i can't even see the app which is create by saasbee AAD. In my opinion, it really shouldn't be seen. Because they are completely unrelated 2 azure accounts. You can think that saasbee and zoom video communications inc are two completely unrelated azure accounts. They are equivalent to two different companies, and they have purchased separate accounts belonging to their companies in azure.

**Comment by jargil** [comment]
The consent is granted directly in the second tenant, not from the tenant where you made your app registration. Once you get the admin account for the second tenant, try deploying your add-in manifest by following this:
https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide#:~:text=Deploy%20an%20Office%20add-in%20using%20the%20admin%20center.,top%20of%20the%20page,%20and%20then%20select%20Next.

Deploying via Centralized Deployment will make your add-in available to the users you choose. This process will also detect that your add-in is configured for SSO by looking into your manifest. Assuming you've added all the right entries it'll ask you to consent for your organization, at this step you can grant all scopes, not just profile.

For which Office client you're developing this add-in?

**Comment by hello-chenchen** [comment]
hi @jargil ,thank you so much.
i am developing for outlook client's add-in.
from your reply, as the second tenant admin, i need to manual deploy my develop manifest on office365 admin center. like below right:(let me wait for 12 hour to get this add-in on my outlook client.)
![image](https://user-images.githubusercontent.com/1878089/109906785-18767d80-7cdc-11eb-94bf-b345595a089f.png)

as an tenant admin to deploy my develop manifest, this means, the consent is granted directly by the tenant admin right?

before deploy on admin center, i deploy the develop manifest on my normal user account, custom add-ins. like below, and when i call getAccessToken, it will get the "Missing grant for this add-in." error message.
![image](https://user-images.githubusercontent.com/1878089/109910779-e49f5600-7ce3-11eb-89f0-c63f2b4b31af.png)

**Comment by hello-chenchen** [comment]
hi @jargil , after install my develop manifest using admin account, i can get the token for getAccessToken api. But when i want to use this token to get access token by using https://login.microsoftonline.com/common/oauth2/v2.0/token/ and add client_id and client_secret, assertion, requested_token_use, grant_type and scope, it return the error message.
```
{
    "error": "invalid_grant",
    "error_description": "AADSTS65001: The user or administrator has not consented to use the application with ID '1f11705d-3b8e-4659-8e41-c7d7b890e310' named 'maiken-access-token-test'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 042e8d10-8342-409d-a9a4-ea0eb6fe1c00\r\nCorrelation ID: 84cf3ea6-3eea-4696-8940-5b39983d450e\r\nTimestamp: 2021-03-04 06:41:32Z",
    "error_codes": [
        65001
    ],
    "timestamp": "2021-03-04 06:41:32Z",
    "trace_id": "042e8d10-8342-409d-a9a4-ea0eb6fe1c00",
    "correlation_id": "84cf3ea6-3eea-4696-8940-5b39983d450e",
    "suberror": "consent_required"
}
```
does it need i to pop up a microsoft permission page, to let user consent for my app? do you have any suggestion here?
it's really appreciate for your help.

**Comment by hello-chenchen** [comment]
hi @jargil and @exextoc , thank you so much for your help. i have got the right grant method from this document: https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent#construct-the-url-for-granting-tenant-wide-admin-consent
use this url to grant for my app: https://login.microsoftonline.com/{tenant-id}/adminconsent?client_id={client-id}

**Comment by hello-chenchen** [comment]
hi @jargil , i can grant it by direct to https://login.microsoftonline.com/{tenant-id}/adminconsent?client_id={client-id}, but do you know have to revoke my grant?

**Comment by hello-chenchen** [comment]
@jargil there is no need, thanks, i can remove it on azure portal.
