### ISSUE TITLE
body.search Issue in word desktop

### ISSUE THREAD

**Issue by aplihs** [OfficeDev/office-js#168]
context.document.body.search(<TextMoreThan255Chars>) is throwing an InvalidArgument exception only in word 2016 desktop client when the text to search for is > 255 characters long. The same seems to be working in word online version.

## Expected Behavior
Should search for text >255 chars

## Current Behavior
InvalidArgument exception in word 2016 desktop client

## Steps to Reproduce, or Live Example
    var searchResults = context.document.body.search( <TextMoreThan255Chars>);
    context.load(searchResults);
    return context.sync().then(function () {
    });

**Comment by JuaneloJuanelo** [comment]
unfortunately this is a known issue and a limitation in Word for Windows. we might improve it in the future please upvote a request in our user voice channel. 
https://officespdev.uservoice.com/
thanks!
