### ISSUE TITLE
Word addin: context.document.body.getHtml().value brings back comments in Word Software but does not in Word online

### ISSUE THREAD

**Issue by ndvbd** [OfficeDev/office-js#1682]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Word addin: context.document.body.getHtml().value bring back comments in Word Software but does not in Word online.
This is a major difference in the api between the offline/online version. Can it be, or am I missing something? 
By the way, nothing about it is mentioned in the documentation

**Comment by AlexJerabek** [comment]
Hi @ndvbd, 
Thanks for reporting this difference in behavior between Word platforms.

@AbidRahman-MSFT, could you please investigate?

**Comment by AbidRahman-MSFT** [comment]
Hey @ndvbd , 

Thanks for reporting this issue. I can reproduce it on my machine, and you're right it is a bug. Comments was not a part of Word on Web when .getHtml() method was implemented and it looks like there may be some additional work we would need to do to ensure we include comments as part of the HTML in Word on Web. I've opened bug #4946935 to internally track this issue. 

I'm curious to know, is there a specific need for the HTML representation of the document? Are you just looking for a way to fetch the comments of the document? As a workaround, I suggest using .getOOxml() instead to see the comments.

Thanks,
Abid

**Comment by ndvbd** [comment]
1. So we agree that the getHtml() should be consistent. The best thing would be to add a parameter so the developer can choose whether to retrieve the comments or not.
2. What is exactly the difference between getHtml and getOOxml?
3. Regarding the 'specific need', well, the biggest API problem is that in order to highlight or replace a Range in the text, the only api you provide to generate a Range is using .search(). Now search is problematic, since let's say you want to replace the 5th substring of [the teacher], but while the server works the user adds another [the teacher] phrase in the text, you can't tell which of the ranges returned by .search() is the right one. Do you get what i am saying? So you guys need to provde a way to create range either by text [start,stop] position (that's the best) or like javascript createRange. until you have that, the only way to get the raw data and replace the data is by getHtml and set the whole html, which is not efficient.

**Comment by AbidRahman-MSFT** [comment]
Hey @ndvbd ,

1. That is not correct, html will not be consistent across the different endpoints and this is specified in our documentation, see below, that being said I do agree that comments should be returned in the html for Web, but you cannot use getHtml if you are looking for consistency:
![image](https://user-images.githubusercontent.com/53581099/110971813-2ea1c080-8310-11eb-89c0-55a251f16173.png)

2. GetOOxml returns the XML representation of the document. The XML representation of a single document **will** be the same across different endpoints and I suggest this is what you use if you are looking for consistency.

3. Thank you for that insight. We do have getRangeByPosition() API in our backlog and will keep you updated when/if we start to work on it. I suggest you post your feature request at [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/filters/top?category_id=163566) to allow the community to chime in and it will also help us prioritize this work down the road.

Thanks,
Abid

**Comment by ndvbd** [comment]
Thanks.

**Comment by ndvbd** [comment]
I see another issue now. 
The context.document.body.text returns the comments as well (which ruins the text). The comment appears as a special character in the text \x05
I believe comments should not appear there. Can you fix it please?

**Comment by AlexJerabek** [comment]
Reopening and pinging @AbidRahman-MSFT.

**Comment by RuoyingLiang** [comment]
Thanks for contacting us. Will look into it now.

**Comment by xiaoyuMS** [comment]
Hi @ndvbd
About the issue of get text, is it a behavior on Desktop? If yes, it is a feature on Desktop, not a bug.

**Comment by ndvbd** [comment]
One more thing to add/ask - Currently the context.document.body.text returns the Tracked Changes in a wierd way - as if they are part of the text itself. So if for example in tracked change I replace a word A with a different word B, the body.text will contain AB (concatenated).
This is unwanted. 
What should happen is that the body.text will return the most current version of the text, as if all tracked-changed were accepted. What do you think? What is currently found in the documentation?
In https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#text there is no mention of what is "text" when there are tracked changes in the document.

**Comment by ndvbd** [comment]
And another problem: While comments are being "injected" to the text as a single control character \x05, footnotes are being injected to text as a control character \x02. Is this documented somewhere?

**Comment by RuoyingLiang** [comment]
For "context.document.body.text return comments character":  This is an expected behavior. We are enable the same experience for many special characters also in Word Online. 
For track change behavior, this is a problem we are solving. Now we are adding APIs to get the correct content in Track change mode. Will announce the new APIs once it's done.  
For the documentation of the special characters, we should provide a document. will update the documentation and add it here.

**Comment by ndvbd** [comment]
@RuoyingLiang Thanks,
1. Please update us here when the documentation is updated.
2. What is the reason you want to 'inject' these special control characters in the plain-text version? After all, they say nothing besides "there is some comment here"...

**Comment by thechrisoshow** [comment]
If you want to remove comments from the HTML, I've used this function and it seems to work:
```
function removeComments(html: string): string {
  // remove spans with class MsoCommentReference
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, "text/html");
  const spans = doc.querySelectorAll("span.MsoCommentReference");
  spans.forEach((span) => {
    span.remove();
  });
  return doc.body.innerHTML;
}
