### ISSUE TITLE
Use MS office word built in ribbon elements from custom web-addin in office-js

### ISSUE THREAD

**Issue by arshadshibli** [OfficeDev/office-js#1689]
Is there any way I can control the built-in ribbon elements in MS office word web from a custom addin using office-js ? and is there a way to catch the word events from web-addin taskpane

For example
1. Is there any way to load the MS office word comments  ribbon by clicking a button from custom add-in
2. Is there a way to load custom addin taskpane on clicking a MS word comment ribbon item

office-js
word web-addin

**Comment by AlexJerabek** [comment]
Hi @arshadshibli, 

Thanks for the questions. I'll tag @AbidRahman-MSFT and @sohailzafar to help answer.

**Comment by AbidRahman-MSFT** [comment]
Hey @arshadshibli,

Thank you for the question. We currently don't have this capability in Word. 

We did recently introduce this capability for PPT on Web and the feature is in private preview. If you are interested in this feature for Word, please let us know by posting a feature request on [UserVoice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?category_id=163566).

**Comment by arshadshibli** [comment]
Thanks @AbidRahman-MSFT @AlexJerabek 

@AbidRahman-MSFT  Can you please share any reference of this capability for PPT , That would be helpful

**Comment by AbidRahman-MSFT** [comment]
Hey @arshadshibli - here are the preview docs around that feature for PPT: https://docs.microsoft.com/en-us/office/dev/add-ins/design/built-in-button-integration

**Comment by arshadshibli** [comment]
Thanks @AbidRahman-MSFT
