### ISSUE TITLE
Please update accordingly and CC with copy to soon5265@gmail.com

### ISSUE THREAD

**Issue by mikeowen85** [OfficeDev/office-js#169]
## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by mlafleur** [comment]
This looks like an issue created in error
