### ISSUE TITLE
Taskpane add-in is blocked although protected mode is enabled

### ISSUE THREAD

**Issue by christian-sap** [OfficeDev/office-js#1690]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Some of our customers are getting the following ADD-IN ERROR in the taskpane with a link to [this page]( https://docs.microsoft.com/en-US/office/troubleshoot/office-suite-issues/apps-for-office-not-start).

![image](https://user-images.githubusercontent.com/79985386/109928815-202b2780-7cc6-11eb-81b2-e994c2d57826.png)

They have enabled the "Protected Mode" in the "Restricted Sites" zone as suggested. But still the add-in is blocked. 

![image](https://user-images.githubusercontent.com/79985386/109929695-0b9b5f00-7cc7-11eb-9b48-b2c95b09f623.png)

Restarts of Excel did not help.

## Expected Behavior
Add-in should not be blocked if the protected mode is enabled in restricted sites zone.

## Current Behavior
Add-in is blocked.

## Steps to Reproduce, or Live Example
Just click the "Log on" ribbon button that starts the task pane.
The issue does only happen on some PCs. It may be related to some other IE settings.

## Context
Our add-in uses shared runtime on IE.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Semi-Annual Enterprise Channel | 2008 | 13127.21216
* Operating System: Windoes
* Browser (if using Office on the web): -

**Comment by keyur32** [comment]
Hi @christian-sap,  can you highlight what the customer sees in the File > Options > Trust Center > Trusted Add-in Catalogs?  I wonder if their is a group policy that was set for desktop specifically that prevents add-ins from starting, which would be the case if either of the below items were checked:

![image](https://user-images.githubusercontent.com/3476087/109992734-6aa9a580-7cc0-11eb-888f-a33919da48ae.png)

**Comment by christian-sap** [comment]
Hi @keyur32, we checked the settings and both are disabled. 
I tried enabling the settings on my local machine. Both settings block the add-in completely. So the ribbon bar of the add-in isn't shown at all. 
Our customers have a different behavior: they are able to see the add-in ribbon bar and click the ribbon button to open the task pane.
After that the task pane shows the above ADD-IN ERROR.

**Comment by keyur32** [comment]
I see. thanks. We're checking.

**Comment by lumine2008** [comment]
Hi @christian-sap , 

The owner team is looking into it, they would like to ask your help to do the following 2 things, thanks in advance. 

1)	Could you ask your customer to export these two keys and send them to us?
a.	Internet Zone: Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
b.	Restricted Sites Zone: Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
2)	Once they’ve exported those. Ask them to delete both keys and try again.

**Comment by keyur32** [comment]
Assigned to @lumine2008, so we can follow up offline to confirm if this has been fixed or is still an issue with the customer.

**Comment by christian-sap** [comment]
@lumine2008 I sent you the exported data from one of the affected customers.

**Comment by jargil** [comment]
@christian-sap - thanks for sending the exported registry keys. A few follow up questions:
* Any reason why Protected Mode is disabled for the Internet Zone? And could you ask them to enable it back and try?
* Did they try as suggested by deleting both registry keys?
* Could you also send over their exported keys under HKLM for 3 and 4 just like before? e.g. Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4

**Comment by christian-sap** [comment]
Hi @jargil , they temporarily enabled "Protected Mode" for the Internet Zone and this solves the issue. But this is no acceptable solution because of their corporate policy. [In your documentation](https://docs.microsoft.com/en-US/office/troubleshoot/office-suite-issues/apps-for-office-not-start) the "Protected Mode" should only be enabled for the Restricted Sites.
Deleting both registry keys will completely delete their security configuration. They could do that on a test machine but this can't be the solution for the issue.
I will ask them to send the mentioned exported keys too.

**Comment by christian-sap** [comment]
HI @jargil , I sent the exported registry keys internally via email.

**Comment by jargil** [comment]
Thanks, @christian-sap. I received the registry dumps, these all look fine. There's one final registry tree that I'd like to check and given the previous dumps, I'm guessing here's where Protected Mode is disabled:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4

I'm sorry about the back and forth with multiple dumps, I had hoped to find the culprit already.

**Comment by christian-sap** [comment]
Hi @jargil , I'm still waiting for our customers to provide the exported keys. Kind regards, Christian

**Comment by christian-sap** [comment]
Hi @jargil , one of our customers replied that the requested registry key does not exist (Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4) but only this here:
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
