### ISSUE TITLE
How to detect if a taskpane is pinned?

### ISSUE THREAD

**Issue by rickgoud** [OfficeDev/office-js#1691]
Hi,

Is there a way to detect whether a user has pinned the task pane in both compose and read mode?
And if there is no 'real' way, are there suggestions on how to detect this as good as possible?

Thanks!

Regards,
Rick

**Comment by AlexJerabek** [comment]
Hi @rickgoud, 

Thanks for the question. Let me tag @exextoc to help answer.

**Comment by exextoc** [comment]
This is currently not possible with the API. 

Unfortunately we are not aware of a viable workaround at this time. ItemChanged events will ONLY come if an Add-in is Pinned...but if the user never selects another item, then ItemChanged events will never come. If a user unpins an add-in afterward, you also won't know. (or if the user pins an item after "popping" out the item in an inspector). 

If your purpose is for Telemetry (i.e. how often are people pinning my add-in, listening to the Item Changed Event will probably be a good approximation) 

What are you trying to do with this information in general? 

Feature/API requests are currently considered via UserVoice:  
https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins

**Comment by rickgoud** [comment]
Hi,

Our functional requirement is: we want to give a tip to users to pin a taskpane if not done, because we see that for many users it is not clear that it can be pinned and how. But you only want to give a tip when the taskpane is not already pinned.
Any suggestions on how to realize this would be very much appreciated!

**Comment by exextoc** [comment]
There is no direct way to do this at this time. (so making a suggestion via UserVoice) is probably the best way to go. 

The only thing I can suggest is you could display the tip if you've never gotten an item changed event. If the user dismisses your warning, or you get an item changed event, you could store this in roamingSettings (https://docs.microsoft.com/en-us/javascript/api/outlook/office.roamingsettings?view=outlook-js-preview) Then stop displaying the message. If that value is et. 

This misses the case where a user pins the add-in but does not change an item before switching items.

**Comment by rickgoud** [comment]
Thanks @exextoc, I'll try it out and report some results here for community learnings!
