### ISSUE TITLE
getUserIdentityTokenAsync fails with Internal Protocol Error while switching between items with a pinned taskpane

### ISSUE THREAD

**Issue by gummybuns** [OfficeDev/office-js#1692]
When the taskpane is pinned, and the user switches quickly between different items. `getUserIdentityTokenAsync` returns an unexpected error. These seems to happen consistently for our users while we are initializing our app.
```
{
  "status":"failed",
  "error":{
    "name":"AccessRestricted",
    "message":"Internal protocol error: '-2147467259'.",
    "code":9017
  },
  "diagnostics":{
    "InvokeCodeResult":-2147467259
  }
}
```
## Expected Behavior
The system should not throw an error when the add-in calls `getUserIdentityTokenAsync` while the user is clicking through multiple items will the Taskpane is pinned.

## Current Behavior
It throws the error above

## Steps to Reproduce, or Live Example
Here is a demo application that produces the issue:

Run this application with the taskpane pinned for the Inbox Mode. Click a bunch of different items within the first three seconds (see video below)

```javascript
import * as React from 'react';
import { render as reactDOMRender } from 'react-dom';


const Content = () => {
  const [isDone, setIsDone] = React.useState(false);
  const [error, setError] = React.useState('');

  React.useEffect(() => {
    // add a 3 second delay to simulate the app loading
    // and to provide a clear example of the failure
    setTimeout(() => {
      try {
        Office.context.mailbox.getUserIdentityTokenAsync((res) => {
          if (res.status === Office.AsyncResultStatus.Succeeded) {
            setIsDone(true);
          } else {
            setError(JSON.stringify(res));
          }
        });
      } catch (e) {
        setError(e.toString());
      }
    }, 3000);
  });
    
  return (
    <div>
      {!isDone && <p>Loading...</p>}
      {isDone && <p>DONE!</p>}
      {error && <p>{error}</p>}
    </div>
  );
};  
    
const run = () => {
  Office.onReady(() => {
    const rootElement = document.getElementById('container');
    reactDOMRender(<Content />, rootElement);
  }); 

};

run();
```

## Context
Our Add-in has several steps during the initial process and if clicks on a bunch of items with the taskpane pinned our application fails to properly load because we cannot get a user identity token.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: I have seen this in PC Desktop and Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.48
* Operating System: Mac

### Example
![Kapture 2021-03-04 at 18 18 09](https://user-images.githubusercontent.com/47437711/110057769-06193580-7d16-11eb-9c93-31fe98be3c60.gif)

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue @gummybuns. 

@mattgeim, can you please investigate?

**Comment by exextoc** [comment]
From your sample code you do not appear to be registered for item change events. If you want to support pinning, you need to call addHandlerAsync() with the itemChanged event. 

I've created a short ScriptLab gist file with an example here: 
https://gist.github.com/exextoc/cdda502b27dbb69bfd98a9e5b12f4767

**Comment by gummybuns** [comment]
Ok it seems like you want me to move everything that is in `useEffect` to instead be within a `addHandlerAsync` for the itemChanged event. But then the app does not initialize until i pin the taskpane and make a change.

I would need the initialize logic to run in `useEffect` _and_ in the `addHandlerAsync` correct? That would still cause the unexpected error in getUserIdentityTokenAsync() when the initial one in `useEffect` gets called.

**Comment by exextoc** [comment]
Depending on your scenario, you can have `useEffect` in both initialize and the addHandlerAsync. 
A number of things could stop working if AddHandlerAsync / ItemChanged is not included with a pinnable taskpane, even though `getUserIdentityTokenAsync()` does not depend on the item. Calls to `getUserIdentityToken` should succeed once you include `addHandlerAsync()` no matter when they were called. (If you can create a scriptlab snippet to show when it doesn't, we can investigate further). 

It is worth noting that `getUserIdentityToken` doesn't need to be called on every item. You can call it once during initialization and then use that token until it expires.
