### ISSUE TITLE
OWA addin fails to report from Outlook for shared mailboxes

### ISSUE THREAD

**Issue by sharon8811** [OfficeDev/office-js#1694]
I have used the &lt;SupportsSharedFolders&gt;true&lt;/SupportsSharedFolders&gt; as mentioned in the docs,
It is letting me use the API over OWA but when I am using it from Outlook 365 for Windows (16.0.13801.20240 64bit) It does not let me, I am getting the following error:
`API not supported for shared folders.`
When I am using:
`const item = Office.context.mailbox.item`

## Expected Behavior
I should be able to use the API according to the docs (with the most updated version of Outlook).

## Current Behavior
It does not let me use it.

## Steps to Reproduce, or Live Example
`const item = Office.context.mailbox.item`

## Your Environment
Outlook 365 for Windows (16.0.13801.20240 64bit)
Windows 10 (19041.804 OS Build)

**Comment by exextoc** [comment]
To clarify the repro steps, are you only calling `Office.context.mailbox.item`? Are you calling another API on the item?

**Comment by sharon8811** [comment]
I have few lines of code:
`const item = Office.context.mailbox.item`
`const from = item.from`
`const recipientType = from.recipientType`
`const hostName = Office.context.mailbox.diagnostics.hostName`
and it fails when I ran it over Outlook 365

**Comment by sharon8811** [comment]
My code is using EWS as well, can it be supported for shared mailbox from OWA (using the browser) but not from Outlook?

**Comment by exextoc** [comment]
Can you share how you are setting up the shared mailbox (specific steps that you took to both setup (the delegator) the shared mailbox and how you are accessing it from the delegate).

**Comment by sharon8811** [comment]
This is the way that the shared mailbox is set:
![image](https://user-images.githubusercontent.com/18531500/110636220-ace95000-81b4-11eb-8c60-f02e2fcb10da.png)
![image](https://user-images.githubusercontent.com/18531500/110636603-1e290300-81b5-11eb-9c1b-a2ffb17f2138.png)
But I am not sure if it is relevant,
The mailbox is accessible when I use the same addon in the browser.

**Comment by exextoc** [comment]
Shared mailboxes are not supported at this time, we only support Shared Folders/Delegate scenarios. An overview of what is not supported can be found [here](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-add-ins-overview). And if you're interested in enabling Delegate Scenarios in an Outlook add-in, documentation can be found [here](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access). One thing to note is that in a delegate scenario, you can't use EWS with the tokens currently provided by office.js API.
