### ISSUE TITLE
Can I specify shortcut keys for Ribbon elements through manifest : 508 Issue

### ISSUE THREAD

**Issue by harit-m-kumar** [OfficeDev/office-js#1695]
I have been using a custom addin "data" for Office365 in Excel online, as shown. Related to the 508 compliance, It has been found that :

1.  On  pressing alt key, the 'Data' menu is assigned a default short cut 'A'. Is it possible to assign a custom shortcut for that?
2. The elements in the ribbon are assigned, default shortcuts like 'RA', 'K' etc. Is it possible to assign meaningful custom shortcuts for the ribbon elements?

It has been found that, the ribbon elements have become tabbable with arrow keys and NVDA reads it after a later release, but can we customise the shortcut keys assigned for the elements?

https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-addin-c
![1](https://user-images.githubusercontent.com/58638877/110294444-e3d52f80-8015-11eb-8ff0-a71ac56f4ca8.PNG)
![2](https://user-images.githubusercontent.com/58638877/110294468-eb94d400-8015-11eb-8ef5-e2ecca0aee68.PNG)

**Please let me know, if I find a solutions for issues 1 and 2 through the manifest or any other method in Excel 365 Online** ?

**Comment by AbidRahman-MSFT** [comment]
Hey @harit-m-kumar,

Thank you for your question. There is currently no way to set custom shortcut keys for Excel buttons in the ribbon. If you would like to see this feature, please suggest it over at [UserVoice](https://officespdev.uservoice.com/) for the community to help surface the need for this feature.

What you are seeing in the ribbon is known as [access keys](https://support.microsoft.com/en-us/topic/keyboard-shortcuts-in-excel-1798d9d5-842a-42b8-9c99-9b7213f0040f?ui=en-us&rs=en-us&ad=us#bkmk_access). They are slightly different than shortcuts in the way that we have no control of what access keys are assigned to the ribbon, they are done purely from an accessibility perspective. 

You can however create an add-in with your own custom ribbon tab and custom ribbon buttons - for which you can assign custom shortcut keys and can access each of these buttons with those custom shortcut keys. The shortcut key feature is currently in preview for Excel and you can learn more here: https://docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts

Please keep in mind that even with the custom keyboard shortcuts feature, this only allows you to set custom shortcuts to add-in related buttons/functions. So you still would not be able to set custom shortcuts to native Excel ribbon buttons that you have mentioned in your screenshots.

Thanks,
Abid

**Comment by harit-m-kumar** [comment]
Thanks for the response. But it says only about adding shortcuts for actions like opening taskpanes. I need to map it to individual buttons which comes under <Control> tag.
Please refer to the first comment. I need the shortcuts to be displayed on the button say 'SA' for sortAscending
Can you please specify what format the Json should be.?

**Comment by AbidRahman-MSFT** [comment]
@harit-m-kumar That's correct, as I mentioned, what you are seeing in the ribbon is known as access keys. They are slightly different than shortcuts in the way that we have no control of what access keys are assigned to the ribbon, they are done purely from an accessibility perspective. There's no way to change these access keys.

If you are adding **custom ribbon buttons to the ribbon through your add-in, you can set up shortcut keys that will invoke the same action as the ribbon button** but the shortcuts will not be displayed on the button like access keys do.

**Comment by ghost** [comment]
Hi @AbidRahman-MSFT, was this ever taken any further in [UserVoice](https://officespdev.uservoice.com/)? The link doesn't seem to exist anymore. Thanks in advance!
