### ISSUE TITLE
HTTP Redirect not working for shared custom runtime functions resources

### ISSUE THREAD

**Issue by georgechr** [OfficeDev/office-js#1696]
OK, this is a bit of a complicated one.

We updated our manifest and build process for custom function to use SharedRuntime as per: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime

We wanted to do this because our service(s) which serve the add-in JS, HTML, CSS files sits behind a proxy server which redirects users to closest one geographically.

When debugging this works perfectly fine now (it didn't use to work before). Our dev manifest points to localhost and we have a configured a dev proxy in webpack.config.js to forward data-fetching HTTP requests to our main URL and the request is successfully redirected as described above.

When deployed to production the add-in installs just fine and we can see the functions. BUT none of them work, not even the ones that don't make an HTTp request to return data. 

My suspicion is that the actual add-in web app files (functions.json, functions.js etc) need to be served directly otherwise the whatever context that functions are running in cannot follow the redirect to get to the function implementation. If the function implementation ITSELF makes an HTTP request then THAT will redirect just fine. 

Am I correct in the assumption above? If so, isn't this a bug then?

**Comment by keyur32** [comment]
@jeremy-msft  - can you take a look please?

**Comment by lindalu-MSFT** [comment]
Not sure if this has to do with deployment or browser. @jeremy-msft @keyur32 Can we find the right person to route this issue to?

**Comment by exextoc** [comment]
No action for quite some time. Closing the issue.
