### ISSUE TITLE
Developer Window Pop Up

### ISSUE THREAD

**Issue by taylorjtatro** [OfficeDev/office-js#1697]
## Article URL

https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/tutorials/excel-tutorial.md
## Issue

Hello!

 I have completed the Protect Worksheet section of the documentation. Whenever I use the newly created add-in I get a blank "Developer window - My Office Add-in" that pops up. The add-in works but I get this pop up every time. 

I have double checked all the code and cannot find what is prompting the launch of the window, also I am using a Mac. Any help would be greatly appreciated!

Hope this is the right place to post this question can't find answers anywhere else.

**Comment by taylorjtatro** [comment]
@AlexJerabek 

The issue does not stop progress but is a bit cumbersome. A new window pops up every time I press the button to protect and then unprotect. So if I’m testing I’ll end up with 3 or so window pop ups. Also it never appears when I use the task pane buttons.

I won’t have a chance until tonight but I will take it through all the paces you outlined above to see if I can help narrow it down!

Thanks again for taking the time!

**Comment by lliu113** [comment]
@taylorjtatro - thanks for reporting this! Just to confirm, you see the pop-up when you click on the "Toggle Worksheet Protection" button, but not the "Show As Taskpane" button? Does it launch a new window each time? 

I went through the tutorial and was also unable to repro, but let me circle back with the engineering team and see if I can get more info on what the developer window is.

**Comment by lliu113** [comment]
@taylorjtatro - looks like the developer window is part of the debug support for Mac and UI-less app commands. It enables hosting UI-less add-ins in a window so developers can right click to inspect and debug. 

You can disable this by setting the OfficeWebAddinDeveloperExtras flag to false. Instructions for how to do so are here -> https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac

Let me know if that turns off the window!

**Comment by lliu113** [comment]
@taylorjtatro - I'm going to go ahead and close this. Feel free to reactivate if you have any additional questions, thanks!
