### ISSUE TITLE
Excel Add-In with Dialog API stops execution until F12 is opened

### ISSUE THREAD

**Issue by nikhilism15** [OfficeDev/office-js#1699]
When an Excel is opened for the first time, if it has a dialog included (for example, login dialog), the code that has to execute after message is passed back to the taskpane doesn't execute until I open F12Chooser or IEChooser from C:\Windows\SysWOW64\F12 folder. Once I open it, it starts working fine even after closing it. I need an immediate solution for this as a production-deployed app is causing this issue for users with slightly out of date Windows OS systems.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by keyur32** [comment]
@lliu113  to help. thanks.

**Comment by nikhilism15** [comment]
Hello product team, can you please help me out in this matter at the earliest? Our product is deployed in production and its not working for windows users with version lower than 1903. It's urgent as all of our users are in that configuration and are unable to use our product due to that.

**Comment by nikhilism15** [comment]
I have to say I'm disappointed by the response time. Not even a message saying you'll look into it? I mentioned already that it's an issue in production created because office has to use IE11 everywhere even if windows 10 with edge is installed. I would appreciate a message explaining what's happening at least.

**Comment by lliu113** [comment]
@nikhilism15 - firstly, apologies for the very late response to this. I know how frustrating it is, and you're right to expect a prompt reply. 

Can you provide your version of office (File > Account) as well as your manifest to help us repro?

**Comment by nikhilism15** [comment]
Office version is 2102 (Build 13801.20294) Click to Run (Office 365)
Windows Version is 1809.
Manifest is as below (please note that I have replaced the domain URL with localhost for privacy reasons):
`
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
  xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="TaskPaneApp">
  <Id>959f27df-aa85-4646-a7d9-46bddf900002</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Data Migration Resources</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Enrich Web Add-In"/>
  <Description DefaultValue="A template to get started."/>
  <IconUrl DefaultValue="https://localhost:3000/assets/img/Concento_Icon.png"/>
  <HighResolutionIconUrl DefaultValue="https://localhost:3000/assets/img/Concento_Icon.png"/>
  <SupportUrl DefaultValue="https://support.datamigrationresources.com/portal/en/kb/concento-enrich"/>
  <AppDomains>
    <AppDomain>localhost</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Workbook"/>
  </Hosts>
  
  <Requirements>
    <Sets DefaultMinVersion="1.9">
      <Set Name="ExcelApi" MinVersion="1.9"/>
    </Sets>
  </Requirements>
  <DefaultSettings>
    <SourceLocation DefaultValue="https://localhost:3000/taskpane.html"/>
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Hosts>
      <Host xsi:type="Workbook">
        <DesktopFormFactor>
          <GetStarted>
            <Title resid="GetStarted.Title"/>
            <Description resid="Enrich.Tooltip"/>
            <LearnMoreUrl resid="GetStarted.LearnMoreUrl"/>
          </GetStarted>
          <FunctionFile resid="Commands.Url"/>
          <ExtensionPoint xsi:type="PrimaryCommandSurface">
            <CustomTab id="EnrichTab">
              <Group id="Enrich.CommandsGroup">
                <Label resid="Enrich.Group"/>
                <Icon>
                  <bt:Image size="16" resid="Concento"/>
                  <bt:Image size="32" resid="Concento"/>
                  <bt:Image size="80" resid="Concento"/>
                </Icon>
                <Control xsi:type="Button" id="EnrichTab.Button1">
                  <Label resid="Enrich.Title"/>
                  <Supertip>
                    <Title resid="Enrich.Title"/>
                    <Description resid="Enrich.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Concento"/>
                    <bt:Image size="32" resid="Concento"/>
                    <bt:Image size="80" resid="Concento"/>
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <TaskpaneId>ButtonId1</TaskpaneId>
                    <SourceLocation resid="Taskpane.Url"/>
                  </Action>
                </Control>
              </Group>
              <Group id="Enrich.EnrichmentGroup">
                <Label resid="Enrich.EnrichmentGroup"/>
                <Icon>
                  <bt:Image size="16" resid="Concento"/>
                  <bt:Image size="32" resid="Concento"/>
                  <bt:Image size="80" resid="Concento"/>
                </Icon>
                <Control xsi:type="Button" id="EnrichTab.Button3">
                  <Label resid="Enrich.SetupLabel" />
                  <Supertip>
                    <Title resid="Enrich.SetupLabel"/>
                    <Description resid="Enrich.SetupDescription"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="setup"/>
                    <bt:Image size="32" resid="setup"/>
                    <bt:Image size="80" resid="setup"/>
                  </Icon>
                  <Action xsi:type="ExecuteFunction">
                    <FunctionName>loadEnrichTemplateDialog</FunctionName>
                  </Action>
                </Control>
                <Control xsi:type="Button" id="EnrichTab.ButtonSave">
                  <Label resid="Enrich.SaveLabel" />
                  <Supertip>
                    <Title resid="Enrich.SaveLabel"/>
                    <Description resid="Enrich.SaveDescription"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="save_16x16"/>
                    <bt:Image size="32" resid="save_24x24"/>
                    <bt:Image size="80" resid="save_32x32"/>
                  </Icon>
                  <Action xsi:type="ExecuteFunction">
                    <FunctionName>saveData</FunctionName>
                  </Action>
                </Control>
                <Control xsi:type="Button" id="EnrichTab.AddNewRow">
                  <Label resid="Enrich.AddNewRow" />
                  <Supertip>
                    <Title resid="Enrich.AddNewRow"/>
                    <Description resid="Enrich.AddNewRowDesc"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="table_row_add_16x16"/>
                    <bt:Image size="32" resid="table_row_add_24x24"/>
                    <bt:Image size="80" resid="table_row_add_32x32"/>
                  </Icon>
                  <Action xsi:type="ExecuteFunction">
                    <FunctionName>addNewRow</FunctionName>
                  </Action>
                </Control>
                <Control xsi:type="Button" id="EnrichTab.DeleteRow">
                  <Label resid="Enrich.DeleteRow" />
                  <Supertip>
                    <Title resid="Enrich.DeleteRow"/>
                    <Description resid="Enrich.DeleteRowDesc"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="table_row_delete_16x16"/>
                    <bt:Image size="32" resid="table_row_delete_24x24"/>
                    <bt:Image size="80" resid="table_row_delete_32x32"/>
                  </Icon>
                  <Action xsi:type="ExecuteFunction">
                    <FunctionName>deleteRow</FunctionName>
                  </Action>
                </Control>
                <Control xsi:type="Button" id="EnrichTab.ButtonLockRecords">
                  <Label resid="Enrich.LockRecordsLabel" />
                  <Supertip>
                    <Title resid="Enrich.LockRecordsLabel"/>
                    <Description resid="Enrich.LockRecordsDescription"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="lock_16x16"/>
                    <bt:Image size="32" resid="lock_24x24"/>
                    <bt:Image size="80" resid="lock_32x32"/>
                  </Icon>
                  <Action xsi:type="ExecuteFunction">
                    <FunctionName>lockAllRecords</FunctionName>
                  </Action>
                </Control>
                <Control xsi:type="Button" id="EnrichTab.ButtonUnlockRecords">
                  <Label resid="Enrich.UnlockRecordsLabel" />
                  <Supertip>
                    <Title resid="Enrich.UnlockRecordsLabel"/>
                    <Description resid="Enrich.UnlockRecordsDescription"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="unlock_16x16"/>
                    <bt:Image size="32" resid="unlock_24x24"/>
                    <bt:Image size="80" resid="unlock_32x32"/>
                  </Icon>
                  <Action xsi:type="ExecuteFunction">
                    <FunctionName>unlockRecords</FunctionName>
                  </Action>
                </Control>
              </Group>
              <Label resid="Enrich.TabLabel" />
            </CustomTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>
    <Resources>
      <bt:Images>
        <bt:Image id="Concento" DefaultValue="https://localhost:3000/assets/img/Concento_Icon.png" />
        <bt:Image id="setup" DefaultValue="https://localhost:3000/assets/img/setup.png" />
        <bt:Image id="save_16x16" DefaultValue="https://localhost:3000/assets/img/save-16.png" />
        <bt:Image id="save_24x24" DefaultValue="https://localhost:3000/assets/img/save-24.png" />
        <bt:Image id="save_32x32" DefaultValue="https://localhost:3000/assets/img/save-32.png" />
        <bt:Image id="reload_16x16" DefaultValue="https://localhost:3000/assets/img/reload-16.png" />
        <bt:Image id="reload_24x24" DefaultValue="https://localhost:3000/assets/img/reload-24.png" />
        <bt:Image id="reload_32x32" DefaultValue="https://localhost:3000/assets/img/reload-32.png" />
        <bt:Image id="lock_16x16" DefaultValue="https://localhost:3000/assets/img/icons8-lock-16.png" />
        <bt:Image id="lock_24x24" DefaultValue="https://localhost:3000/assets/img/icons8-lock-24.png" />
        <bt:Image id="lock_32x32" DefaultValue="https://localhost:3000/assets/img/icons8-lock-32.png" />
        <bt:Image id="unlock_16x16" DefaultValue="https://localhost:3000/assets/img/icons8-padlock-16.png" />
        <bt:Image id="unlock_24x24" DefaultValue="https://localhost:3000/assets/img/icons8-padlock-24.png" />
        <bt:Image id="unlock_32x32" DefaultValue="https://localhost:3000/assets/img/icons8-padlock-32.png" />
        <bt:Image id="table_row_add_16x16" DefaultValue="https://localhost:3000/assets/img/table_row_add-16.png" />
        <bt:Image id="table_row_add_24x24" DefaultValue="https://localhost:3000/assets/img/table_row_add-24.png" />
        <bt:Image id="table_row_add_32x32" DefaultValue="https://localhost:3000/assets/img/table_row_add-32.png" />
        <bt:Image id="table_row_delete_16x16" DefaultValue="https://localhost:3000/assets/img/table_row_delete-16.png" />
        <bt:Image id="table_row_delete_24x24" DefaultValue="https://localhost:3000/assets/img/table_row_delete-24.png" />
        <bt:Image id="table_row_delete_32x32" DefaultValue="https://localhost:3000/assets/img/table_row_delete-32.png" />
      </bt:Images>
      <bt:Urls>
        <bt:Url id="Commands.Url" DefaultValue="https://localhost:3000/commands.html"/>
        <bt:Url id="Taskpane.Url" DefaultValue="https://localhost:3000/taskpane.html"/>
        <bt:Url id="Enrich.LearnMoreUrl" DefaultValue="https://support.dmroffice.com/ConcentoSuite/3_2/Enrich/index.htm?context=30"></bt:Url>
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="GetStarted.Title" DefaultValue="Enrich has loaded successfully!"/>
        <bt:String id="CommandsGroup.Label" DefaultValue="Commands Group"/>
        <bt:String id="Enrich.Title" DefaultValue="Enrich" />
        <bt:String id="Enrich.Description" DefaultValue="Enrich" />
        <bt:String id="Enrich.Group" DefaultValue="DMR Tools"/>
        <bt:String id="Enrich.EnrichmentGroup" DefaultValue="Enrichment"/>
        <bt:String id="Enrich.TabLabel" DefaultValue="Enrich_NPM" />
        <bt:String id="Enrich.SetupLabel" DefaultValue="Select Template"/>
        <bt:String id="Enrich.SaveLabel" DefaultValue="Save"/>
        <bt:String id="Enrich.ReloadLabel" DefaultValue="Reload"/>
        <bt:String id="Enrich.LockRecordsLabel" DefaultValue="Lock"/>
        <bt:String id="Enrich.UnlockRecordsLabel" DefaultValue="Unlock"/>
        <bt:String id="Enrich.Actions" DefaultValue="Enrich Context Menu Actions"/>
        <bt:String id="Enrich.AddNewRow" DefaultValue="Add Row"/>
        <bt:String id="Enrich.DeleteRow" DefaultValue="Delete Row"/>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="GetStarted.Description" DefaultValue="Your sample add-in loaded succesfully. Go to the HOME tab and click the 'Show Taskpane' button to get started."/>
        <bt:String id="Enrich.Tooltip" DefaultValue="Click to Open Enrich Add-in Taskpane"/>
        <bt:String id="Enrich.GetDataDescription" DefaultValue="Click here to Get Data" />
        <bt:String id="Enrich.SetupDescription" DefaultValue="Click here to select Enrich Template" />
        <bt:String id="Enrich.SaveDescription" DefaultValue="Click here to save changes to Enrich database" />
        <bt:String id="Enrich.ReloadDescription" DefaultValue="Click here to reload changes from Enrich database" />
        <bt:String id="Enrich.LockRecordsDescription" DefaultValue="Click here to lock records in the Enrich Table" />
        <bt:String id="Enrich.UnlockRecordsDescription" DefaultValue="Click here to unlock records in the Enrich Table" />
        <bt:String id="Enrich.ActionsDescription" DefaultValue="Context menu actions for Enrich Templates. Only works on Enrich Templates" />
        <bt:String id="Enrich.AddNewRowDesc" DefaultValue="Click here to add a new row to the Enrich Table. Only works on Enrich Templates" />
        <bt:String id="Enrich.DeleteRowDesc" DefaultValue="Click here to delete a row from the Enrich Table. Only works on Enrich Templates" />
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>
`

**Comment by nikhilism15** [comment]
@lliu113 can you please help me out on this? Clients are after us as to why its not working in production. I hope you understand the urgency of this issue.

**Comment by nikhilism15** [comment]
@lindalu-MSFT I need help resolving this please. I need to find out if it's an issue with Microsoft or at my end. The same code runs perfectly on an up-to-date windows machine but not in a Windows Server 2019 or even a slightly out of date windows machines. This will cause issues as a bunch of our clients are not on the latest windows OS yet. I have been waiting for some sort of a response from MSFT for almost a month now.

**Comment by massonj** [comment]
@nikhilism15 - unfortunately, your manifest didn't really come through in the comment above - we only got a small fragment of it, so if you could try to re-attach that would be great. A few other questions which would help narrow things down:

1. Can you provide a little more information about what happens when the dialog completes - is the taskpane frozen, or responsive? 
2. Are you using the [shared runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime) ?
3. Are you using a client framework like React in your taskpane? if so which one?

We don't have enough information to say for sure that this will help, but we have seen occasional instances where the web control we use for rendering the task pane can temporarily stop processing callback messages, until some other event nudges it into resuming. If that's what's happening in your case, one workaround we have seen be effective is to have some code at the beginning of the function registered to receive messages back from the dialog which changes the DOM in some way (i.e. perhaps there is a hidden element somewhere and you can change the content of it), which seems to be enough to prevent things from stalling out.

thanks

**Comment by nikhilism15** [comment]
@massonj - Here are my answers:
1. The taskpane is not frozen or unresponsive. The functionality is that the user enteres some details in the dialog, and I keep the taskpane open until I load data in the sheet (and a hidden sheet I use for dropdowns) and then close the dialog. What happens is that the data doesn't load and the dialog stays open (for 5 minutes if I keep it open). As soon as I open F12Chooser.exe and select the taskpane, the data loads and dialog closes fine. From that point onwards, everything works perfectly as if nothing happened. It's only the first time that it happens, until the next time they load the add-in again.
2. No, I am not using shared runtime. As I already mentioned above, this happens in machines with out of date Windows or Office systems because it by default uses IE11 as the browser to run the add-in, and not Edge. With Edge, I don't have any issues with the add-in functionality, which is why we pushed it to clients in the first place. Now some clients have out of date Windows installed and it doesn't work for them as soon as they open Excel.
3. I am using React on my taskpane but most of my functional code is on the commands FunctionFile code.
`<FunctionFile resid="Commands.Url"/>`

How do I set that up? What kind of DOM changes? Can you give an example please? 

Thank you so much for responding, I was going crazy here.

**Comment by nikhilism15** [comment]
@massonj Actually there has been a breakthrough, sort of. I let the program run, and what should take a couple of seconds in a normal up-to-date windows machine takes forever in a Windows Server (unless F12 is opened). If F12 is opened, it immediately speeds up and runs at the normal pace. Very peculiar behavior.

**Comment by massonj** [comment]
When I said to have some code which changes the dom, one thing you could do is
1. add an element in your taskpane HTML like this 
`<div id="myHiddenDiv" style="display: none;"></div>`
2. add code at the top of the function handeling callbacks from the dialog like this:
 `document.getElementById("myHiddenDiv").innerHTML = "Anything";`

**Comment by massonj** [comment]
I'm going to assume this is closed at this point - feel free to reopen if that's not the case
