### ISSUE TITLE
Addin not working in desktop with Share data and events between Excel custom functions and the task pane

### ISSUE THREAD

**Issue by CristovaoTorres** [OfficeDev/office-js#1700]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
Add-in not working in desktop with Share data and events between Excel custom functions and the task pane.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2102 (Build 13801.20266)
* Operating System: Windows Server 2016 Datacenter
* Browser (if using Office Online): Working Ok

## Useful logs
- [ ] Screenshots
![image](https://user-images.githubusercontent.com/46796748/110514134-c1124c00-80e5-11eb-982a-e1e14581b52d.png)

Project Code: https://github.com/CristovaoTorres/ExcelCustomFunction_Shared_avaScriptRuntime

**Comment by xiaochunms** [comment]
@CristovaoTorres sorry for the issue. Is it possible to share the manifest file that I can take further debugging?

**Comment by CristovaoTorres** [comment]
@xiaochunms  ok,
Here you go
https://github.com/CristovaoTorres/ExcelCustomFunction_Shared_avaScriptRuntime

**Comment by xiaochunms** [comment]
@CristovaoTorres I just noticed that you already pasted the link of the code in the initial thread. Sorry for missing it and thanks to share it again. BTW, looks like the resources is inaccessible, for example I cannot reach "http://YaraOp2b:8002/dist/functions.js" from my side. Is the website accessible? The Add-in installation will fail if related resources is inaccessible.

**Comment by CristovaoTorres** [comment]
@xiaochunms  the manifest file were updated.
http://YaraOp2b:8002/dist/functions.js -> https://main.dvntzptumz7ya.amplifyapp.com/dist/functions.js

**Comment by CristovaoTorres** [comment]
Any news?

**Comment by xiaochunms** [comment]
@CristovaoTorres sorry for the late response as I am busy working on other things recently. I compiled your project and executed "npm start" to launch excel, the add-in can be installed successfully at my side. However I noticed the add-in name is AddinJavaScript, which is different from the one (Vcm1xExcel) you were installed. I am not sure if they are the same one.

![image](https://user-images.githubusercontent.com/1261601/111727664-2d94f580-8820-11eb-8114-c2bc7f63a84d.png)

You may notice there is #VALUE! returned in above screenshot, it is the return value of function call "=CONTOSO.VERSAO()". And it indicates a successful call of the function but return value of the function is not correct.

My Excel version:
![image](https://user-images.githubusercontent.com/1261601/111728320-7b5e2d80-8821-11eb-9b6d-4b608336ceea.png)

**Comment by CristovaoTorres** [comment]
Working perfectly
TKS
