### ISSUE TITLE
Is linkedDataTypes api working?

### ISSUE THREAD

**Issue by puripats** [OfficeDev/office-js#1701]
[Enter feedback here]
Deat Support Team,

I run this on Excel web with beta setup in the guide.
I try to learn linkDataTypes api. I try to use simple code for example, I run

Excel.run(function (context) {
var linkedCount = context.workbook.linkedDataTypes
linkedCount.getCount()
}
return context.sync().then(function(){
console.log(linkedCount)
  });
})

After that the result showed.
Uncaught (in promise) RichApi.Error: This operation is not implemented.

So I think maybe i do wrong in the code so I'm try other function for example,

Excel.run(function (context) {
 var taskCount = context.workbook.tasks;
 taskCount.getCount();
}
return context.sync().then(function(){
    console.log(taskCount)
  });
})

the result showed.
r {m_contextBase: n, m_objectPath: t, m_context: n, m_isNull: false}
That means it is working.

So the question is "Is linkedDataTypes api working?" or I am doing something wrong here?

Best regards.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ee2d4bf5-85ab-7f5e-0112-25b4c41f5db0
* Version Independent ID: ebd8e0f7-9ff4-b0f0-e4eb-36453d68d937
* Content: [Excel JavaScript preview APIs - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-preview-apis)
* Content Source: [docs/reference/requirement-sets/excel-preview-apis.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/excel-preview-apis.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@puripats Thanks for letting us know. I'll transfer to the office-js repo so the product team can take a look.

Thanks.

**Comment by JinghuiMS** [comment]
Thanks for reaching us. The LinkedDataTypes api is not ready yet, it is likely to be released in ExcelAPI1.14. You can follow our release information.

**Comment by puripats** [comment]
> Thanks for reaching us. The LinkedDataTypes api is not ready yet, it is likely to be released in ExcelAPI1.14. You can follow our release information.

Many thanks JinghuiMS
