### ISSUE TITLE
Addins not working when using Remote Desktop to remote into Outlook Desktop on Windows

### ISSUE THREAD

**Issue by Byron-Mo** [OfficeDev/office-js#1702]
After upgrading Windows, when users use Remote Desktop to remote into their Windows machine from their personal Macbook or Linux, Addins on Outlook Desktop are not loading properly. 

## Expected Behavior

Addins should load and sign in properly on Windows 2004 or 2009

## Current Behavior

Addins such as Evernote and Salesforce Outlook Integration do not load:

Evernote
 
![image](https://user-images.githubusercontent.com/14811552/110544411-878b1200-80e0-11eb-95b0-db2c413ba5c7.png)

Salesforce
![image](https://user-images.githubusercontent.com/14811552/110544430-8f4ab680-80e0-11eb-8d8b-4c7efcacaea0.png)

## Steps to Reproduce, or Live Example

1. Open Mac Machine
2. Use Microsoft Remote Desktop, or Apple Remote Desktop and a third-party remote desktop software called Jump Desktop, to access the remote machine
3. Open Outlook application
4. Click on any email
5. The side panel just spins, trying to connect, and eventually reports the following error: ''The app can take some time to load. You can wait, try closing the app and opening it again , or clear your settings and log in again.''

## Additional details & Environment
Issue is observed when remoting in from either Macbook or Linux. Remote desktop from a Windows machine to another Windows machine works. 

Remote Desktop, Apple Remote Desktop, or a third-party remote desktop, Jump Desktop all observe the same issue.

This problem only occurs in the Desktop version of Outlook

OWA works fine in the following browsers:
- IE
- Chrome
- Edge Chromium Version

**Windows and Office Versioning for affected users:**
Windows 10 build 19041 (2004)
Office 16.0.13328.2040
Edge Chromium Version 87.0.664.60 64-Bit

Windows 10 build 19042 (2009)
Office 16.0.13426.2027

Windows 10 build 19042 (2009)
Downgraded to build 18363, since this began, and now it's working
Office 16.0.13328.2040

**Windows and Office Versioning in place for users not having a problem:**
Windows 10 build 18362 (1903)
Office 16.0.13328.2025

Windows 10 build 18362 (1903)
Office 16.0.13328.2035

Windows 10 build 18363 (1909)
Office 16.0.13328.2035

Windows 10 build 18363 (1909)
Office 16.0.13328.2035

**Comment by exextoc** [comment]
Are you able to load add-ins on other Office applications such as Excel?

**Comment by jcl-nfs** [comment]
> 
> 
> Are you able to load add-ins on other Office applications such as Excel?

Hi, I'm one of end-users that was involved with the discovery of this issue.  If you can you recommend a benign excel add-in to test, I'd be happy to do so.

**Comment by exextoc** [comment]
Feel free to try any add-in. For example you can try the [Script Lab](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab) add-in.

**Comment by jcl-nfs** [comment]
Hi, same behavior as presented.  On the RDP Mac session, the rolling dots at the bottom repeat over and over.

**Comment by exextoc** [comment]
Are you able to load add-ins on the same Windows machine when not remoting?

**Comment by jcl-nfs** [comment]
Yes.  Here are the three cases:
  Local windows work fine.  
  PC->rdp->PC works fine.  
  Mac->rdp->PC does not.
The windows version presented in original submission is key to this.  Anything prior to 19041, and the Mac->rdp->PC works.  Anything 19041 and after, and it fails/hangs/blanks.

**Comment by jargil** [comment]
I tried reproducing this by connecting from Mac to Windows/PC and I could not see this problem, using multiple Office builds as well as the latest Windows build.

@Byron-Mo, @jcl-nfs:
Could you please try and report the following?
* Remote from Mac to Windows,
* Try starting an add-in and confirm it is blank, or hang, etc.
* Reconnect to the Windows PC locally and confirm if the add-in is still blank or if it shows its UI as expected.

Could you please confirm which Runtime your PC is using by doing this locally or using Windows to Windows?
* Start Excel,
* Start Script Lab (or any other add-in),
* Click anywhere in Script Lab and you should see a button with a < on the top right of the pane,
* Click the button and a context menu will appear,
* Click Security Info,
* Confirm the value for "Runtime".

![image](https://user-images.githubusercontent.com/10125816/111193351-4fb81a80-8577-11eb-9342-68246705c1ae.png)

**Comment by jcl-nfs** [comment]
Hi:
First test:
1. MAC RDP to Windows
2. Opened both outlook and excel, enabled plugins, observed their broken state (circling / blank) **
3. Left the RDP session active
4. Accessed Windows computer locally about 1 hour later (drove to work)
5. Logged into machine, which took over RDP session, and the sidebars remained stuck
6. Upon refreshing sidebars, issue went away ++

I took videos of what's going on and put into my o365 onedrive, however, seems like the option to "anyone with link" is disabled.  If necessary, I can look into other ways of sharing, but hopefully the above description is enough.

Second test:
I forgot to do this locally, but I did windows->windows rdp, and runtime is "Microsoft Edge Legacy"

**Comment by jargil** [comment]
Thank you, @jcl-nfs.

I tried to repro again by using the same Microsoft Edge Legacy runtime, connecting from Mac to PC and could not reproduce.

Given you're seeing it with the Microsoft Edge Legacy runtime, if possible, could you try the new Edge runtime? If you are able to update to Office 16.0.13530.20424 or newer and install the WebView2 runtime, you'll be able to have your add-ins running in the newer Edge control (Chromium based) and hopefully this problem will go away.

Relevant links:
* This one shows which runtime Office uses depending on OS/Office build combinations: https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins
* Microsoft Edge WebView2 runtime installer: https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by jcl-nfs** [comment]
Hi:  the office applications are on latest version, however, none of the systems have webview2.  After installing, the issue has been resolved.  Thank you.  I realize this is a tech support issue on a development board, but thank you anyway.  We ragged our brains on this for months trying to make it work.

**Comment by jargil** [comment]
Thanks for confirming this works fine after installing WebView2. I'll go ahead and close.

**Comment by jcl-nfs** [comment]
@Byron-Mo I tried updating the case in SF without luck, if you're able to add that, great.

**Comment by Byron-Mo** [comment]
Excellent, @jcl-nfs . I'll work with our support team to get the case updated with the resolution. Thank you!
