### ISSUE TITLE
Asian language ribbon strings aren't displayed in one line on Excel desktop client

### ISSUE THREAD

**Issue by masayukiiizuka** [OfficeDev/office-js#1703]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Asian language ribbon strings aren't displayed in one line on Excel desktop client even though the width is enough. 

## Expected Behavior

Asian language ribbon strings are displayed properly on Excel desktop client.

## Current Behavior

Currently ribbon strings are displayed vertically or improperly on Excel desktop client.
I tried to control word wrap by adding CR+LF or &amp;#13; , but I could not control word wrap of ribbon string.

Here is snippet of my manifest.
..
<bt:Override Locale="ja-jp" Value="ホーム" />
...
<bt:Override Locale="ja-jp" Value="詳細" />
...
<bt:Override Locale="ja-jp" Value="ヘルプ" />
![ribbon_ja](https://user-images.githubusercontent.com/79878721/110554693-a5a74f80-817e-11eb-99b1-f42ccecf24a8.png)

This problem occurs on Excel desktop client. Problem isn't reproduced on Excel web client.

**Comment by keyur32** [comment]
Assigning to @sohailzafar  to investigate.

**Comment by ElizabethSamuel-MSFT** [comment]
@masayukiiizuka Is this still reproing for you?

@preethikakiru Can you take a look?

Thanks.

**Comment by masayukiiizuka** [comment]
@ElizabethSamuel-MSFT problem still occur. Please look into this problem.

**Comment by ElizabethSamuel-MSFT** [comment]
@masayukiiizuka Thanks for letting us know.
