### ISSUE TITLE
In Safari, I get nothing from `Office.context.ui.messageParent`

### ISSUE THREAD

**Issue by alexhrytsak** [OfficeDev/office-js#1705]
In Safari, I get nothing from `Office.context.ui.messageParent`
## Expected Behavior

I do receive a message from `Office.context.ui.messageParent`
## Current Behavior

I do not receive a message from `Office.context.ui.messageParent`
## Steps to Reproduce, or Live Example

I using this is[ example ](https://github.com/OfficeDev/Office-Add-in-Dialog-API-Simple-Example/blob/master/SimpleDialogSampleWeb/DialogHelper.js)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: OfficeWeb
* Operating System:  MacOS 11.1 (20C69)
* Browser (if using Office on the web): Safari 14.0.2 (16610.3.7.1.9)

**Comment by keyur32** [comment]
Assigning to @lliu113 to investigate, as this is related to the Dialog API (on Word Web)

**Comment by lliu113** [comment]
@alexhrytsak - sorry for the belated response to this. What domain are you sending the message from in the dialog, is it the same as your taskpane?

**Comment by lliu113** [comment]
@alexeystrakh - I'm going to close this issue for now, please reactivate if you're still experiencing this issue. if you can provide more information on your dialog domain, as well as whether you're seeing any errors that will help us debug. Thanks!
