### ISSUE TITLE
Outlook appendOnSendAsync method seems to have a size limit on the data attribute.

### ISSUE THREAD

**Issue by vddgil** [OfficeDev/office-js#1707]
appendOnSendAsync method in Outlook seems to have a size limit on the data attribute.

## Expected Behavior
Should append the text on send whatever is the size of it.

## Current Behavior
When adding an HTML Signature (9438 characters) I get the following error:
Sys.ArgumentOutOfRangeException: Sys.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: data
Actual value was 9438.

## Steps to Reproduce, or Live Example
Just try the method with a big text

## Context
I want to automatically add a signature when sending an email

## Your Environment
* Platform : Max
* Host : Outlook
* Office version number: 16.46
* Operating System: OSX 11.2.2

**Comment by exextoc** [comment]
Just to confirm, is this issue faced on Outlook MAC client or Outlook On The Web in Mac OS?

**Comment by vddgil** [comment]
Hello,

On Outlook mac client.

**Comment by exextoc** [comment]
Hey @vddgil ,

`appendOnSendAsync` is implemented only on Outlook for Web and Outlook for Windows as a part of the API set 1.9. API set 1.9 is not yet shipped for Outlook for Mac. You can find the specifications for which API set is supported across which client [here](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#outlook-client-support).

**Comment by vddgil** [comment]
Hello @exextoc,

You are right, but it was not working on windows either.
But found in the docs that that there is a 5000 character limit, for those who are wondering ;)
