### ISSUE TITLE
Edge destroys session cookie on pane closing.

### ISSUE THREAD

**Issue by DiliTrustApplicant** [OfficeDev/office-js#1708]
Currently we use session cookies to allow authentication for our addin. We are starting to have users complain that they have to login every time because of the pane closing.  We're assuming this is edge behavior.

We've looked at perhaps storing the cookie in local storage but does that not leave the cookie vulnerable to cookie stealing if we turn off httponly?  How do we handle authentication securely when the pane is closing using cookies?  

Cookies as security will become obsolete with this behavior as more people upgrade, and what's worse is because it's a single manifest file you cannot utilize things such as SSO because a single manifest file cannot contain all users information.

**Comment by keyur32** [comment]
Hi thanks for the report. Assigning to @smaremanda  to look at the edge cookie issue.  

We would generally recommend using OAuth, which will allow you to take advantage of SSO as you mention.

**Comment by DiliTrustApplicant** [comment]
> Hi thanks for the report. Assigning to @smaremanda to look at the edge cookie issue.
> 
> We would generally recommend using OAuth, which will allow you to take advantage of SSO as you mention.

They still have to put in their username every single time...

Or how else can 1 manifest know 100 different users...

**Comment by ElizabethSamuel-MSFT** [comment]
@croicu Can you take a look?

Thanks.

**Comment by Dengshan2018** [comment]
Session cookie is gone if add-in instance is closed. Please follow the document from https://learn.microsoft.com/en-us/office/dev/add-ins/develop/overview-authn-authz.
