### ISSUE TITLE
How to move cursor on word document with office js api 

### ISSUE THREAD

**Issue by ssoni2074** [OfficeDev/office-js#1709]
How can I move blinking cursor by few character left/ right in js addin ? For VSTO addin we were simply doing **range +/- 1** .
Even doing range.clear() or range.delete() doesn't show blinking cursor.
## Expected Behavior
range.clear() or range.delete() should show a cursor where we can start typing directly without clicking on the document

## Current Behavior
currently after range.clear() range is deleted and we get (sort of ) a white space in selection and on range.delete() range is deleted and we can't see cursor  in both the cases we still need to click on the document to enter text on document otherwise there won't be any text on document

## Steps to Reproduce, or Live Example
select any text on document run range.clear() or range.delete() you will be able to be what I mentioned above

## Context
I can't move cursor left or right from addin 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: **Office on the web**
* Host [Excel, Word, PowerPoint, etc.]: **Word**
* Operating System: **Windows**
* Browser (if using Office on the web): Tried on all

**Comment by keyur32** [comment]
@AbidRahman-MSFT  to take a look. thanks.

**Comment by AbidRahman-MSFT** [comment]
Hey @ssoni2074,

Thanks for posting the question. You are correct, there is no way to achieve this behavior using Office JS. 

I would suggest posting a feature request on [UserVoice[(https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/filters/top?category_id=163566) as that helps us and the community keep track of future investments.

I would also recommend posting a similar query on StackOverflow to see if there's any way to achieve a similar scenario - for eg. there's no way to actually move the cursor, but if you are looking for ways to draw the user's attention to certain parts of the canvas, you can use APIs like [range.select()](https://docs.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview#select_selectionMode_) to navigate the user to a certain part of the document.
