### ISSUE TITLE
Function to close window after completion

### ISSUE THREAD

**Issue by binarykitchen** [OfficeDev/office-js#171]
There is no functionality to close the window when an add-in has completed the event.

When you double click on a message in Outlook Online, it opens in its own window. Then whenever you do an action and perform it, it closes.

But not when you run an add-in event. Probably this is by design. But we really need to close it in our case. Configurable in the manifest or is that a missing function in office-js?

**Comment by exextoc** [comment]
Hi,

we do have the item.close() API. Is that what you're looking for? What's the scenario in your case?

**Comment by binarykitchen** [comment]
Nope, this function seems missing.

`Office.context.mailbox.item` doesn't have a close function. And it's not documented in  your API docs either.

My scenario is just to close the window after pressing an add-in button.

**Comment by exextoc** [comment]
You are correct in that we do not have a close function for read mode. It only exists for compose.

Having an item.close() API for a read item is not a common request from developers so it is not high on our priority list. We suggest you submit this feature request to our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins) as it allows us to prioritize features when we go through our planning process.

**Comment by JuaneloJuanelo** [comment]
this is a feature request, hence closing this item.
