### ISSUE TITLE
excel-win32-16.01.js:2 Ressource not found when we deployed from Admin center

### ISSUE THREAD

**Issue by Krishna-de** [OfficeDev/office-js#1710]
Created excel addin with babel and webpack config for IE11 engine.

We referenced "Office.js"  in html     **"<script src="/assets/office-js/office.js"></script>"**
Excel office add in works fine if we reference from assets in Debugging.

Now we published it in admin center, office js intialized fine but unfortunately console shows **"excel-win32-16.01.js"** not found. Excel sheet functions does not work.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/25722294/110940683-93244600-8337-11eb-8240-aa4d6a8c91d4.png)

Could you guys give some pointers to solve this issue?

**Comment by nikhilism15** [comment]
Hey Krishna, I faced a similar issue, solved it by downloading this [file](https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js) and placing it in my assets folder along with office.js.

**Comment by Krishna-de** [comment]
> Hey Krishna, I faced a similar issue, solved it by downloading this [file](https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js) and placing it in my assets folder along with office.js.

Hey Nikhil,

I also exported office.js and excel-win32-16.01.js both files to assets , I still got the error. Could you please give me some sample example? Thank you again for the reply.
You are from Hyderbad. I used to live there for couple of years

**Comment by nikhilism15** [comment]
Hey Krishna, I cannot read German but can you please explain the error in English? It doesn't look like the win32 file is not found, it looks like there is some error within? Can you please clarify?

**Comment by lumine2008** [comment]
@Krishna-de, do you observe this issue before you publish to admin center? if no, it looks like a deployment issue.

**Comment by Krishna-de** [comment]
> Hey Krishna, I cannot read German but can you please explain the error in English? It doesn't look like the win32 file is not found, it looks like there is some error within? Can you please clarify?

Thanks Nikhil, we figure it out
