### ISSUE TITLE
Excel streaming custom function starts twice after loading spreadsheet (non-shared runtime)

### ISSUE THREAD

**Issue by logicaloud** [OfficeDev/office-js#1714]
After creating a spreadsheet containing a streaming custom function, saving it, then reloading it later, it shows that a streaming custom function starts twice.

## Expected Behavior
The custom function should only start once after loading the spreadsheet.

## Current Behavior
The custom function starts twice.

## Steps to Reproduce, or Live Example
To reproduce the issue for Excel Desktop:

Create a folder and run `yo office --projectType excel-functions --name 'TestAddin' --host excel --js`

Change to folder TestAddIn and run `npm run build`, then `npm start`

Allow some time for the plugin to compile and Excel to start, then select a spreadsheet cell and type `=CONTOSO.INCREMENT(1)` into the Excel formula bar. Press Enter.

You should now see the cell showing incrementing values.

Save the spreadsheet and close Excel.

Re-open the spreadsheet.

Over time, the cell shows:

#BUSY
1
2
3
#BUSY
1
2
3
4
...

## Context
The customer experience is somewhat jarring when continuity is lost. A streaming custom function that communicates with backend servers incurs additional processing or initialization cost depending on the backend functionality performed. 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft 365 v16.0.13801.20288 64-bit
* Operating System: Windows 10 v1909
* Browser (if using Office on the web): n/a

**Comment by qinliuMSFT** [comment]
Thanks for reporting this issue. We could repro it and created bug 4900383 to follow up.

**Comment by igor-ribeiiro** [comment]
I will be looking at this issue today, thanks for reporting it.

**Comment by grangeryy** [comment]
Hey @igor-ribeiiro, do you have any update on this?

**Comment by igor-ribeiiro** [comment]
Sorry for no updates, I will be looping with the Custom Functions team as they will be in a better position to solve this issue.

**Comment by grangeryy** [comment]
@logicaloud, we did some investigation and here is the finding:
1.	The issue only happens with the add-in generated by Yo office tool in Windows, 
2.	The issue will not seen with add-ins in Office store,
3.	Following steps can mitigate the issue,
1)	Launch Registry Editor,
2)	Go to "HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\WEF\Developer",
3)	Look for the key whose name is the ID in manifest file (for example, <Id> 44a0a681-c6ed-4c2f-ad13-ca8f08934eb2</Id>), 
4)	Change “UserDirectDebugger” value from “1” to “0“ 

Pls let me know if the above can resolve the issue?

**Comment by logicaloud** [comment]
@grangeryy Thank you for looking into this. I can confirm that the function does not start twice when loading the spreadsheet without the debugger. 

What first led me to this issue was an Admin-deployed Add-In that appeared to perform differently at the time when the spreadsheet was first created vs the time when it was loaded in an existing spreadsheet. The "loaded" behavior seemed consistent with starting twice or running two functions concurrently. The yo-generated example was an attempt to re-produce the issue in its simplest form. I cannot tell at the moment if the original issue is related, so I suggest to close this one. 

With the new knowledge, I'll investigate the other Add-In behavior and should the odd behavior persist then I'll open another issue with hopefully more details.

**Comment by grangeryy** [comment]
Thank you @logicaloud for the additional information! Then I'll close this one, and pls feel free to open a new one if you encounter the other issue like mentioned above:)
