### ISSUE TITLE
Profile menu hidden behind task pane making it unusable

### ISSUE THREAD

**Issue by rickgoud** [OfficeDev/office-js#1715]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

With a Taskpane open, clicking on the profile menu, the profile menu falls behind the task bar. This makes it impossible to use the profile menu without closing the task pane. Certainly with pinnable task pane, this is unworkable, because users can not switch profiles anymore. See image. Hopefully this is something easy fixable, maybe even in OWA CSS?

![image](https://user-images.githubusercontent.com/13066218/111024577-cfab7c80-83df-11eb-8861-d0c4dc7d187a.png)

**Comment by keyur32** [comment]
@JuaneloJuanelo for the feedback to take a look.

**Comment by lindalu-MSFT** [comment]
@JuaneloJuanelo Is this something we can create a bug for and put on the backlog? Or is this not actionable/won't fix?
