### ISSUE TITLE
[Outlook] Office.context.mailbox.item.seriesId value show null when edit one event of recurring meeting

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1716]
We use seriesId to distinguish between a single event of recurring meeting and the whole series. But recently it has been found that this value is sometimes incorrect.
This problem only happened on Mac Outlook. Windows outlook and web works fine.

Note: But some times this seriesId will work after a few hours.

## Expected Behavior
When edit single event of series ,series Id will show a value. not null or undefined
When edit entire series, series Id will show null.

## Current Behavior
Not matter I edit single event or entire series on Mac outlook calendar. Series ID sometimes always show null. And 
it's a high probability, and it's inevitable on some Macs.
For example Mac Outlook version： 16.46 （21021202）

## Steps to Reproduce, or Live Example
You can try,
1. schedule a recurring meeting with zoom add-in.
2. save and open a single event again
3. try get seriesId from dev tool.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.46 （21021202）
* Operating System: Mac OS
* Browser (if using Office on the web): ______

**Comment by exextoc** [comment]
Hey @SWei1234 ,

Are you seeing this issue in the New Outlook UI or the Old UI? Since this is an intermittent issue, it might take some time to narrow things down. Can you see if this issue exists in the [latest build of Outlook](https://docs.microsoft.com/en-us/officeupdates/update-history-office-for-mac) as well?

**Comment by SWei1234** [comment]
Hi @exextoc 
We met this problem on Old UI. 
I will try update Outlook to latest version and see if this problem still exist.
Thanks for you reply.
