### ISSUE TITLE
Add-In settings lost after Office Update

### ISSUE THREAD

**Issue by ndreisg** [OfficeDev/office-js#1717]
Recently we are getting many customer reports that all settings in the Add-In suddenly disappeared after they updated Office.

In our Excel Add-In we use the browsers localStorage to save some settings, please note that these settings should be saved independent of the document, so the `Office.Settings` API can't be used in this case.

[This document](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings) suggests to "Use techniques provided by the underlying browser control: browser cookies, or HTML5 web storage (localStorage or sessionStorage)."

According to [this document](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) Office is using Internet Explorer if Windows 10 version < 1903 or Microsoft 365 ver. < 16.0.11629. If Windows 10 version >= 1903 and Microsoft 365 ver. >= 16.0.11629 the Edge WebView will be used instead.

This is causing an issue, for example:
- A user has Windows 10 >= 1903 and Microsoft 365 ver. < 16.0.11629 
- He installs an Add-In and changes some settings (which are saved to localStorage of Internet Explorer)
- He then updates his Office to a version >= 16.0.11629
- Office will now use the Edge WebView instead of the IE browser control
- Settings saved in localStorage of IE will not be available to the Add-In any longer

## Expected Behavior
There should be some kind of global Settings API which allows to save settings on a global scope instead of document scope.

## Current Behavior
Currently there is no API to save settings on a global scope, when using "techniques provided by the underlying browser control" the settings will be lost upon update of this underlying browser control.

## Your Environment
* Platform: PC
* Host: Excel (probably affects all hosts)
* Office version number: multiple (see above)
* Operating System: Windows 10

**Comment by smaremanda** [comment]
@ndreisg - thanks for connecting with us. The issue you outline is expecting as the localstorage is not shared between browser controls.
Couple of questions:
Can you please let me know why you cant use Office.Settings API to store these settings?
Localstorage in general cannot be considered a permanent storage. so you'll need to plan for cases where the user somehow clears this storage. What exactly are you storing here?

**Comment by ndreisg** [comment]
> Can you please let me know why you cant use Office.Settings API to store these settings?

Because these settings should persist when the user opens the Add-In in another document.

> Localstorage in general cannot be considered a permanent storage. so you'll need to plan for cases where the user somehow clears this storage.

That's exactly the point: The office-js API currently doesn't offer any way to do this. The suggested way to save settings in a global scope is "techniques provided by the underlying browser control" as you can see in the first link I posted. All these techniques have the same issue.

What exactly would you suggest to do to plan for these cases?

> What exactly are you storing here?

Settings which should persist when the user opens the Add-In in another document :)

**Comment by ndreisg** [comment]
Any news about this issue?

Also another question: When WebView2 is used where will the user data folder be located?

Since the new WebView2 is used to display Add-Ins this issue is now appearing much more frequently (not only when updating Office).
I got reports from customers that settings are lost every weekend.
I guess Office sets the user data folder for the WebView2 to some kind of temp location which is periodically deleted by Windows.

**Comment by Dengshan2018** [comment]
@ndreisg webview2 user data folder for Office is under user app data folder. OS will not delete them.

**Comment by ndreisg** [comment]
Thanks for the answer. Do you also have any news about the original issue? Will there be some kind of global Settings API in the future?

**Comment by Dengshan2018** [comment]
Sorry, @ndreisg, I didn't hear any plan for Global Setting API.

**Comment by Dengshan2018** [comment]
No plan for Global Setting API. Close as Won't Fix.
