### ISSUE TITLE
onDataChanged bindings for a cell returns RichApi.Error

### ISSUE THREAD

**Issue by popecode** [OfficeDev/office-js#1719]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior

When trying to observe excel cell changes we are getting an error back in the api 

## Current Behavior

We want to receive real-time event data information

## Steps to Reproduce, or Live Example
We're getting a `RichApi.Error` with an internal error of 500 - internal server error.

This same type of code worked before in a previous iteration of the add-in (was using vanilla javascript).  We're currently using react + typescript, but don't think that should really be an issue.

I've limited it down to the following, which should hopefully help you out a bit. Please let me know if there's anything further I can do.

Thank you!
Ben

Error Object
```
{
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "There was an internal error while processing the request.",
        "errorLocation": "Workbook.bindings",
        "statement": "var bindings = workbook.bindings;",
        "surroundingStatements": [
            "var workbook = context.workbook;",
            "// >>>>>",
            "var bindings = workbook.bindings;",
            "// <<<<<",
            "var add = bindings.add(...);",
            "context.trace();"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}
```

Network tab
```
RichApi.Error: There was an internal error while processing the request.
    at new n (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:301571)
    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:363144)
    at https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:26:361249
```

Suspect code
```
await Excel.run(async (context) => {
    const cellBinding = context.workbook.bindings.add(cellAddress, "Range", (Math.random()*10000000000).toString());
    cellBinding.onDataChanged.add(this.onBindingDataChanged);
    await context.sync();
});
```

## Context

Cannot get change value updates in Excel

This code doesn't ever get called, but here for the reference:
https://gist.github.com/popecode/93b5337719c9a12aee787fa9d7e652f3

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______ Mac and Windows
* Host [Excel, Word, PowerPoint, etc.]: ______ Excel
* Office version number: ______ 
* Operating System: ______ Win 10 / Big Sur
* Browser (if using Office on the web): ______ Google Chrome

## Useful logs
As above

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by keyur32** [comment]
assigned to @lumine2008  to investigate, per offline thread.

**Comment by xuxife** [comment]
Hi @popecode, would you please provide "ServerCorrelationId" or "SessionId" of your repro document if you're using Office web?
If you're using desktop Excel, you can send a "feedback to MS" to help us identify the problem session.

**Comment by popecode** [comment]
Hi team.

```
{
    "27c9dd6b_42ef331e_1615910255006CachedSessionSettings": "{}",
    "_xdm_0_https://xero365-my.sharepoint.com/personal/ben_gemperline_xero_com/Documents/Book 17.xlsx_{010B9440-F7FE-4FE3-A8AA-3B609FD5AAFF}5884cf00_3a2ec096_1615910255006serializerVersion": "1",
    "_xdm_0_https://xero365-my.sharepoint.com/personal/ben_gemperline_xero_com/Documents/Book 17.xlsx_{f86ef712-7142-4dd3-b3a5-6b5a2fdc000c}23c2c7cd_3538963_1615910345567xdmInfo": "1ea5ec98_3dd008d0_1615910345567|{f86ef712-7142-4dd3-b3a5-6b5a2fdc000c}|https://excel.officeapps.live.com",
    "_xdm_0_https://xero365-my.sharepoint.com/personal/ben_gemperline_xero_com/Documents/Book 17.xlsx_{f86ef712-7142-4dd3-b3a5-6b5a2fdc000c}23c2c7cd_3538963_1615910345567serializerVersion": "1",
    "_xdm_0_https://xero365-my.sharepoint.com/personal/ben_gemperline_xero_com/Documents/Book 17.xlsx_{010B9440-F7FE-4FE3-A8AA-3B609FD5AAFF}5884cf00_3a2ec096_1615910255006xdmInfo": "27c9dd6b_42ef331e_1615910255006|{010B9440-F7FE-4FE3-A8AA-3B609FD5AAFF}|https://excel.officeapps.live.com",
    "1ea5ec98_3dd008d0_1615910345567CachedSessionSettings": "{\"customFunctionAddinId\":\"2|31186516-aa8f-4e22-8294-6e4a622646b1|1.0.0.0|15|developer|||\"}",
    "hostInfoValue": "Excel|Web|16.00|en-US|a4d0a426-98af-4004-8d55-be6fd16cf7c3|||2"
}
```

```
{
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "There was an internal error while processing the request.",
        "errorLocation": "Workbook.bindings",
        "statement": "var bindings = workbook.bindings;",
        "surroundingStatements": [
            "var workbook = context.workbook;",
            "// >>>>>",
            "var bindings = workbook.bindings;",
            "// <<<<<",
            "var add = bindings.add(...);",
            "context.trace();"
        ],
        "fullStatements": [
            "var workbook = context.workbook;",
            "var bindings = workbook.bindings;",
            "var add = bindings.add(\"Sheet1!D4\", \"Range\", \"4233528862.5621147\");",
            "context.trace();"
        ]
    },
    "httpStatusCode": 500
}
```

and document link: 
https://xero365-my.sharepoint.com/:x:/r/personal/ben_gemperline_xero_com/_layouts/15/Doc.aspx?sourcedoc=%7B1BFE39E4-3637-4C90-A4C8-933CB965D8C5%7D&file=Book%2017.xlsx&action=editnew&mobileredirect=true&wdNewAndOpenCt=1615910176443&ct=1615910176443&wdPreviousSession=c252a919-4b52-4144-afd7-18773f3358a7&wdOrigin=OFFICECOM-WEB.START.NEW


Does this help?

**Comment by popecode** [comment]
It should also be noted that we are getting an error even if we do: 

```
 const wbindings = context.workbook.bindings.load("items");
 await context.sync();
```

**Comment by xuxife** [comment]
Thank you, this helps a lot. We cannot access your file since it's under your domain.
We've gone through that session's log, it looks like your Addin instance has some problem, is it a Taskpane Addin? 
Can you repro this issue from other workbooks or after creating a new Addin instance?
Do you also encounter this error even running this code in ScriptLab?

**Comment by popecode** [comment]
It is a Taskpane addin that was created by the yo generator. It uses React, Redux, and TypeScript.
We can reproduce the issue with other workbooks.
We have not had the issue running it in Script lab so we do believe that there is an issue in the addin. We are looking for support on isolating the issues as we could be missing implicit requirements. 

One thing that we think might be causing the problem is that we are calling it from a static instance, but we are not how this would affect calls to the API.

Thanks,

**Comment by popecode** [comment]
Update:

it fails when we call it from within the context of the custom functions in a shared context.
it works when we call it from within our react components.

**Comment by xuxife** [comment]
Can you provide a sample Addin? I've tried yo-generating an Addin followed your description but cannot repro this error.
A file or sample Addin that can repro the problem will help us a lot! Thank you!

**Comment by popecode** [comment]
Hi it seems to be an issue when you're calling Excel.run() from within a custom function invocation within a shared runtime environment.  That's what I found out and is the most accurate way to reproduce. I'm not sure I can provide an example as it is commercially sensitive. But if can ask if you think it's necessary

**Comment by xuxife** [comment]
Did you mean [Call Excel JavaScript APIs from a custom function](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function) within a shared runtime add-in like ([Configure your Office Add-in to use a shared JavaScript runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime))?
I've created an internal bug 4966075 for tracking this problem.

**Comment by popecode** [comment]
That's correct. Thank you.

**Comment by popecode** [comment]
A code example can be found [here](https://gist.github.com/popecode/b52a6181b0f675a0af1598e2dcfed37a)

**Comment by gingerjia** [comment]
hi @popecode, the file you shared to us above cannot be accessed due to permission. Can you help to create a new workbook and try to repro the issue? This won't include any commercially information. And if can repro, could you help to share the workbook to us also? The workbook can help us to populate issue much quickly. Thanks very much!

**Comment by popecode** [comment]
Hi I have changed the permissions on that file.

**Comment by advisoray** [comment]
We'll generate a new workbook, install our add-in, trigger the error, and invite you. Is there anything particular we should do to invite? Any specific account or sharing setting?

**Comment by gingerjia** [comment]
@popecode @advisoray , thanks! After you trigger the error, please download the file as a copy, and attached file to your reply comment box directly:
![image](https://user-images.githubusercontent.com/62282034/112244082-a7e2d100-8c89-11eb-8938-214a99f9a267.png)
Then I can get the file for further check. Thanks again!

**Comment by advisoray** [comment]
[Book 27.xlsx](https://github.com/OfficeDev/office-js/files/6199030/Book.27.xlsx)

Here's a copy of the file from onedrive demonstrating the internal error.

**Comment by gingerjia** [comment]
As we discussed offline, currently we have some limitations for calling APIs in CF:
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function

Include worksheet.onChanged event option, another option for your reference is that create one Add-in for custom functions, and create another Add-in for calling APIs update data.

Thanks!
