### ISSUE TITLE
Word.Range.insertParagraph() throws exception after using Word.Range.delete()

### ISSUE THREAD

**Issue by triandco** [OfficeDev/office-js#1720]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Summary
We were trying to create an reference Add-in to replace user's highlighted text with a paragraph with the same fontFamily/size/color as user's highlighted text. 

We tried the Word.Range.delete() to clear out the user input before inserting a new paragraph using Word.Range.insertParagraph() with the link. This works the first time, but subsequently failed with a GeneralException when we try to perform the same process with some text on the newly inserted paragraph. Please see the gif and checkout the gist for more details.

![ffs2](https://user-images.githubusercontent.com/61586052/111269956-5af86c80-8683-11eb-9ee7-a169ce8ed236.gif)

## Steps to Reproduce and Live Example
1. Checkout the (gist)[https://gist.github.com/triandco/eff7be9a6e065225e5e6ef81ae34b392] and run it in Script Lab for Word: -  *in this example, we replace user input with an empty string and log the font name on console*
2. In Word, enter a piece of text and highlight it
3. Press Run button in taskpane
4. Click on the newline and enter some text
5. Highlight the newly inserted text
6. Press the Run button again

## Expected Behavior
Current text is replaced with a new text, console logs the font of the new paragraph

## Current Behavior
A _GeneralException_ was raised for the method Word.Range.insertParagraph

## Environment
* Platform : PC desktop
* Host: Word
* Office version number: Version 2102(Build 13801.20294 Click to Run)
* Operating System: Windows

## Exception Log
```json
{"name":"RichApi.Error","code":"GeneralException","traceMessages":[],"innerError":null,"debugInfo":{"code":"GeneralException","message":"GeneralException","errorLocation":"Range.insertParagraph","statement":"var insertParagraph = selection.insertParagraph(...);","surroundingStatements":["...","var body = root.body;","// Instantiate {body}","var selection = root.getSelection();","// Instantiate {selection}","selection.delete();","// >>>>>","var insertParagraph = selection.insertParagraph(...);","// <<<<<","// Instantiate {insertParagraph}","var range = insertParagraph.getRange();","// Instantiate {range}"],"fullStatements":["Please enable config.extendedErrorLogging to see full statements."]},"httpStatusCode":500}
```

**Comment by smaremanda** [comment]
@hjkim-MSFT - could you please take a look at this one?

**Comment by grangeryy** [comment]
@triandco are you still having issue with this API, as this item seems to have been silent for a while. THX!

**Comment by triandco** [comment]
@grangeryy, I have been able to replicate this issue using the provided example and verified that this is still a problem.

The issue remain unresolved. Please help.

Much appreciated,

Tri
