### ISSUE TITLE
item.categories.addAsync gives an error "The operation is not supported" in compose mode

### ISSUE THREAD

**Issue by EugeneLazutin** [OfficeDev/office-js#1721]
Office 365 online throws an error in compose mode although according to the [documentation](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mastercategories?view=outlook-js-preview#addAsync_categories__options__callback_) it should work;

![image](https://user-images.githubusercontent.com/12011141/111293185-0bea1180-865a-11eb-87cf-3f8137c97784.png)

**Comment by exextoc** [comment]
Hey @EugeneLazutin ,

While Categories API for adding categories to item is supported in Read Mode for both Outlook for Windows and Outlook for Web, the support in Compose Mode today is only limited to Outlook for Web. The documentation that you shared shows addAsync only for MasterCategories which is supported across platforms. You can request for using addAsync on item categories on our [uservoice page](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/filters/top?category_id=131778). We go through our uservoice page while going through our planning process.

**Comment by EugeneLazutin** [comment]
Yes, I messed up with master categories. But documentation for [categories.addAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.categories?view=outlook-js-preview#addAsync_categories__options__callback_) also says it should work in Compose mode.
In the example above I do use Outlook for Web in chrome browser (correct if I'm wrong and Outlook for Web is something different).

**Comment by exextoc** [comment]
Hey @EugeneLazutin ,

I see the documentation does not accurately reflect the behaviour of the API and we're working to get it corrected. Thanks for pointing it out. Outlook on Web as of today does not support `item.categories.addAsync` for Compose mode in Outlook for Web (The one you used in the example above)
