### ISSUE TITLE
Excel: numbers formatted wrong when creating a table whith european formats and target hosts

### ISSUE THREAD

**Issue by ndeeH** [OfficeDev/office-js#1724]
## Expected Behavior
Formatted values must be inserted in correct regional format (settings of host system).

## Current Behavior
On some client computers the values get wrong decimal and thousand separators:
#### **"123.456"** will become **"123,456"** 

All versions OS, office version and all region settings are the same.

Seems the API will interpret the values on some clients as american formatted values🤔
The thousands and decimal separator get changed.

## Steps to Reproduce, or Live Example
You can use my Gist to try this behavior in Script Lab:
https://gist.github.com/ndeeH/e8b4e40a850b6ae48d6867c39bbbbbb6

```
var myTable = new Office.TableData();
    myTable.rows = [
      ["European", "'123.456.789,00", "123.456.789,00"],
      ["American", "'123,456,789.00", "123,456,789.00"],
      ["European", "'123.456", "123.456"],
      ["American", "'123,456", "123,456"],
      ["European", "'123.456 €", "123.456 €"],
      ["American", "'$123,456", "$123,456"],
      ["European", "'123,456 €", "123,456 €"],
      ["American", "'$123.456", "$123.456"]
    ];

    var style = {
      coercionType: Office.CoercionType.Table,
      tableOptions: {
        style: "none2",
        headerRow: false,
        firstColumn: false,
        filterButton: false,
        totalRow: false,
        lastColumn: false,
        bandedRows: false,
        bandedColumns: false
      },
      cellFormat: []
    };

   Office.context.document.setSelectedDataAsync(myTable, style, ..);

```
Here a table is created with American and European formatted values:

We see on some computers (same OS, same office version) the numbers are misinterpreted:
**"123.456"** will become **"123,456"** 
In Europe the comma is the decimal separator and the value is factor 1000 wrong!

On other computers the values are inserted correctly in same format we pass it 
(same OS, same office version - all region / language settings completely same).

## Your Environment
* Platform PC desktop
* Host:  Excel
* Office version number: 16.0.13801.20240
* Operating System: Windows 10 20H2

**Comment by smaremanda** [comment]
@lumine2008 @tutieu Tuan/Raymond - could you please take a look at this issue and redirect?

**Comment by xuxife** [comment]
Hi @ndeeH , you can use "range.formulasLocal" to make the local number format work. 

https://gist.github.com/xuxife/13fe46fbf4f44143e7e77c4cd40415bf
```    
sheet.getRange("A2:C5").formulasLocal = [
      ["European", "'123.456,00", "123.456,00"],
      ["American", "'123,456.00", "123,456.00"],
      ["European", "'123.456,00 €", "123.456,00 €"],
      ["American", "'$123,456.00", "$123,456.00"]
    ];
```

**Comment by ndeeH** [comment]
@xuxife Thank you for your tipp. 

Our productive Add In does use the "old" way to insert a table via **setSelectedDataAsync()** - see Gist:
https://gist.github.com/ndeeH/e8b4e40a850b6ae48d6867c39bbbbbb6

**_Is it possible to force local format or formulasLocal this way?_**

We see at the same company (all computers use same os, same office version) 
- on some computers the value formats inserted correctly 
- on some computers the values are misinterpreted e.g. **"123.456"** will change to **"123,456"**! 😫
We do not see any difference in language or reginal settings. All set according to target number format.

_We need a solution for this - a very big ice cream company is getting wrong numbers...._ 😲

@lumine2008 @tutieu

**Comment by ndeeH** [comment]
Changed the issues description to our current real life problem with the officejs API in our productive Add In
Please restart triage if necessary!

**Comment by xuxife** [comment]
Sorry, we don't have a feature like "force German format" currently. 
**setSelectedDataAsync** is supposed to work with local number format setting. 
Number format has a separate setting both in Windows and Excel:

For Win, Control Panel - Clock and Region - Change date, time, or number formats - Additional settings...
![image](https://user-images.githubusercontent.com/28257575/111592211-71c5cd00-8803-11eb-966d-99d22d785fc2.png)

For Excel, which is recommended because it could override system's setting
File - Options - Advanced - Use system separators
![image](https://user-images.githubusercontent.com/28257575/111592378-ac2f6a00-8803-11eb-8c31-bff0220cbf5c.png)

Please try unselect "Use system separators" and specific "Decimal"/"Thousands" separator as your will.

**Comment by ndeeH** [comment]
Hi @xuxife ,
we double checked those settings and it seems that your statement is not valid for some office versions:
> setSelectedDataAsync is supposed to work with local number format setting.

Some office versions do not use the given local number format and change the values.
I will send you the version number as soon as I get it from the customer.
Is it possible that you look if there have been changes in that region?
TIA, Andi

**Comment by xuxife** [comment]
Try to input the number from UI to check if the locale number format setting works.
If setSelectedDataAsync didn't behave like UI in some version, it should be a bug.

**Comment by ndeeH** [comment]
Hi @xuxife ,
we just tried to input numbers from UI in local number format - all ok there.

There was definitely a **bug** in version: **MSO 16.0.13801.20240 32-Bit**
With this version our customers get the wrong formatted local numbers.

Our customers with a higher office version do not face this problem.
It is a pity that office says "you have the latest version" when they want to upgrade :(

Bye, Andi

**Comment by lumine2008** [comment]
It look to me this issue can be resolved by upgrade Office, but it seems your customer meet an upgrade issue, do your customer have MSFT support engineer? it would be great to approach from other channel. thanks

**Comment by ndeeH** [comment]
@lumine2008 @xuxife 
No - the customer does not have MSFT support engineers - they are contacting me because the add in does not work like expected.
It is hard to tell them that MS has a bug in some version and that this is fixed in a newer version of office -
BUT they have no chance to update because office tells them they have the newest version. 😒

Any chance/tipp to force the update to the newer version?
TIA, Andi

**Comment by ndeeH** [comment]
Any idea how to force an excel to update to the newest version?

**Comment by ndeeH** [comment]
Hi there,
today we had a support meeting with our customer and tried it again in Excel Version:
**MSO 16.0.13901.20148 32-Bit**
![image](https://user-images.githubusercontent.com/11518242/114417978-5e174780-9bb2-11eb-86db-d90c12d5cf80.png)

@xuxife 
We tried the following:
-  inserted local formatted value by keyboard: **123.456,00** (this format is set in region and excel settings):  
result: when clicking in this cell we see the correct value **123456,00** 
- inserted same local formatted value **123.456,00** via _setSelectedDataAsync()_ (see my [Gist ](https://gist.github.com/ndeeH/11d07f35632c5efabd9de3aa57a1657f) for ScriptLab) :
not recognized as number (text)
- we also inserted a value via _setSelectedDataAsync()_  formatted as **123,456.00** (us format)
the value was inserted / transformed as correct german formatted value **123.456,00** 🤔

The confusing thing is that we have an office installation with completely same version (64 bit)
where all these things work as expected. 
Excel installation at customer still says - the have the latest update.

Thank you, Andi

**Comment by xuxife** [comment]
Hello Andi,
I appreciate all information you provided. I've tried it on latest 32bit Excel, the problem does not appear.
The best solution is that the customer upgrade the Office installation.

For the Office upgrade issue, the customer could send a frown face :( in "Feedback to Microsoft" with keyword "cannot upgrade Office" and attached information (maybe this issue link).

Thanks

**Comment by xuxife** [comment]
There is another method worth to try: 
Switch to another channel, check updates then switch back and check again.

You can change channel in **Files-Account-Office Insider-Change Channel**
![image](https://user-images.githubusercontent.com/28257575/114656851-6641c500-9d21-11eb-94ed-13647b34ab17.png)

**Comment by ndeeH** [comment]
Thank you @xuxife for your tipps! 👌
_Where may I switch the Insider Channel?_
![image](https://user-images.githubusercontent.com/11518242/114661123-c111f700-9cf6-11eb-8960-8390d3e75e34.png)

**Comment by xuxife** [comment]
According to https://insider.office.com/en-us/join/windows, Office Insider for enterprise is managed by admin.

**Comment by ndeeH** [comment]
Hi there,
at last we had exact the same version numbers of office and one installation worked - the other did not insert the local formatted numbers correct.
**Finally the customer uninstalled office and re-installed the latest 64bit version of office.
Now inserting local formatted values by the add in works like expected.**
Thank you, Andi
