### ISSUE TITLE
[Outlook] getAttachmentContentAsync fails when contentType=text/xml

### ISSUE THREAD

**Issue by jlevenssfdc** [OfficeDev/office-js#1725]
getAttachmentContentAsync fails when contentType=text/xml

## Expected Behavior
Should be able to get the attachment content

## Current Behavior
Unable to get the attachment content and an unhandled rejection is thrown

## Steps to Reproduce, or Live Example
- Send an email with an xml attachment
- Find email in sent items
- run this: 
`Office.context.mailbox.item.attachments.map((attachment) => { console.log(attachment); Office.context.mailbox.item.getAttachmentContentAsync(attachment.id, console.log) })`

## Context
Trying to get attachment content using getAttachmentContentAsync so we don't have to manually use EWS

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: OWA/EXO
* Host [Excel, Word, PowerPoint, etc.]: OWA/EXO
* Office version number: OWA/EXO
* Operating System: Ubuntu
* Browser (if using Office on the web): Chromium

## Useful logs
```
VM8:345 Uncaught (in promise) o {message: "Invalid token specified", filename: "", lineno: 0, colno: 0}message: "**Invalid token specified**"colno: 0filename: ""lineno: 0__proto__: InvalidTokenError
    at Object.1220 (https://outlook-1.cdn.office.net/owamail/20210308001.08/srienabled/scripts/owa.AddinsCommon.js:1:307)
    at u (https://outlook.office.com/mail/:330:160686)
    at Module.4153 (https://outlook-1.cdn.office.net/owamail/20210308001.08/srienabled/scripts/owa.AddinsCommon.js:1:8145)
    at u (https://outlook.office.com/mail/:330:160686)name: "InvalidTokenError"stack: "InvalidTokenError↵    at Object.1220 (https://outlook-1.cdn.office.net/owamail/20210308001.08/srienabled/scripts/owa.AddinsCommon.js:1:307)↵    at u (https://outlook.office.com/mail/:330:160686)↵    at Module.4153 (https://outlook-1.cdn.office.net/owamail/20210308001.08/srienabled/scripts/owa.AddinsCommon.js:1:8145)↵    at u (https://outlook.office.com/mail/:330:160686)"__proto__: Object
s @ VM8:345
Promise.then (async)
l @ VM8:345
(anonymous) @ VM8:345
l @ VM8:345
(anonymous) @ owa.MailBoot~Addins~addins-marketplace.js:12
yn @ owa.MailBoot~Addins~addins-marketplace.js:12
(anonymous) @ owa.MailBoot~Addins~addins-marketplace.js:12
invoke @ owa.MailBoot~Addins~addins-marketplace.js:12
T @ owa.MailBoot~Addins~addins-marketplace.js:12
U @ owa.MailBoot~Addins~addins-marketplace.js:12
```

**Comment by exextoc** [comment]
Hey, unfortunately, we are not able to reproduce this issue at our end on a Machine running Mac OS running Chrome. Can you please verify if your issue is reproducible on a Windows PC or Mac running any of the standard browsers? 

We are able to see the xls attachment successfully be fetched using the code you shared:

<img width="448" alt="Screenshot 2021-03-18 at 1 18 21 PM" src="https://user-images.githubusercontent.com/28549921/111590991-d3c70800-87ec-11eb-8435-ff1b2ccd7ec5.png">

**Comment by exextoc** [comment]
Hey,

Unfortunately, we are unable to reproduce the issue with the code you shared on Outlook for Web on MacOS. Can you please confirm if this issue is specific to Ubuntu running Chromium or do you see this issue on Browsers running in a Windows PC or a Mac as well? Is there any administrator policies blocking XML attachments for you? (this will prevent you from downloading an XML attachment by clicking on it as well)

We are able to run your code successfully Chrome running on Mac OS:
<img width="437" alt="Screenshot 2021-03-18 at 1 27 08 PM" src="https://user-images.githubusercontent.com/28549921/111591841-fb6aa000-87ed-11eb-8b4f-2b2b9a3fcc8f.png">

**Comment by jlevenssfdc** [comment]
No one has explicitly set any download rules that I know of, how/where would that be confirmed?  I just tested in Firefox on Ubuntu, Edge Chromium on Windows, Safari/Chrome on Mac with the same result.  Are you using a different version of OfficeJS maybe?  I notice yours has a _.debug.js_ suffix, where mine, loaded from the cdn does not.

If you want, you might have an old email from me with a login to our instance, it's just a tester, if you want to try it there.  Alternatively, if you want to provide a cdn for the debug resource, I can try that.

**Comment by jlevenssfdc** [comment]
@lindalu-MSFT What additional feedback should I provide?  Thanks!

**Comment by exextoc** [comment]
Hey @jlevenssfdc ,

Can you share your Manifest for the Outlook add-in (or a test account credential, which would be even more helpful) where you can reproduce this issue, either here or at admin@M365x010952.onmicrosoft.com? We'll take a look.

**Comment by bconners1005** [comment]
I am actually having this issue as well, but can't tell if it is new or existing, issue.  It seems to be tied to when the method is called when trying to get content for a OneDrive attachment link using `item.getAttachmentContentAsync`. 

The error comes in as:

```
Uncaught (in promise) TypeError: Cannot read property 'model' of undefined
    at owa.MailBoot~Addins~addins-marketplace.js:12
    at VM13 AAQkADIzNDc1MTE2LWIyZmEtNDMyOS05NzVkLTMxMGJlNjExMzRjZgAQAN55ySoU4U9AnrMDwmCkm5U%3D:345
    at Object.next (VM13 AAQkADIzNDc1MTE2LWIyZmEtNDMyOS05NzVkLTMxMGJlNjExMzRjZgAQAN55ySoU4U9AnrMDwmCkm5U%3D:345)
    at VM13 AAQkADIzNDc1MTE2LWIyZmEtNDMyOS05NzVkLTMxMGJlNjExMzRjZgAQAN55ySoU4U9AnrMDwmCkm5U%3D:345
    at new Promise (<anonymous>)
    at l (VM13 AAQkADIzNDc1MTE2LWIyZmEtNDMyOS05NzVkLTMxMGJlNjExMzRjZgAQAN55ySoU4U9AnrMDwmCkm5U%3D:345)
    at owa.MailBoot~Addins~addins-marketplace.js:12
    at yn (owa.MailBoot~Addins~addins-marketplace.js:12)
    at owa.MailBoot~Addins~addins-marketplace.js:12
    at Microsoft.Office.Common.Invoker.invoke (owa.MailBoot~Addins~addins-marketplace.js:12)
```

It then does not finish processing.  Even the example code given for a return of CloudAttachment links seems to be skipped.

Hopefully this gives some context that might help?

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.

**Comment by bconners1005** [comment]
This issue is still occuring for me.

I am trying to make a system to get information related to a Cloud uploaded attachment is when it seems to happen.  

Is there a different method if I have the cloud link I should be processing to get the cloud attachment?

```
getAttachmentContentAsyncApiMethod.ts:41 Uncaught (in promise) TypeError: Cannot read property 'model' of undefined
    at getAttachmentContentAsyncApiMethod.ts:41
    at VM11325 WFk%3D:345
    at Object.next (VM11325 WFk%3D:345)
    at VM11325 WFk%3D:345
    at new Promise (<anonymous>)
    at u (VM11325 XaiWFk%3D:345)
    at owa.MailBoot~Addins~addins-marketplace.js:12
    at hn (executeApiMethod.ts:82)
    at EndpointRegistrator.ts:41
    at Microsoft.Office.Common.Invoker.invoke (osfruntime.js:22)
  | (anonymous) | @ | getAttachmentContentAsyncApiMethod.ts:41
-- | -- | -- | --
  | (anonymous) | @ | VM11325 …AmDBjjXaiWFk%3D:345
  | (anonymous) | @ | VM11325 …AmDBjjXaiWFk%3D:345
  | (anonymous) | @ | VM11325 …AmDBjjXaiWFk%3D:345
  | u | @ | VM11325 AAQkADIzNDc1…AmDBjjXaiWFk%3D:345
  | (anonymous) | @ | owa.MailBoot~Addins~…s-marketplace.js:12
  | hn | @ | executeApiMethod.ts:82
  | (anonymous) | @ | EndpointRegistrator.ts:41
  | invoke | @ | osfruntime.js:22
  | T | @ | osfruntime.js:22
  | U | @ | osfruntime.js:22
```
