### ISSUE TITLE
Search strings within 255 character limit throws errors

### ISSUE THREAD

**Issue by handofthecode** [OfficeDev/office-js#1726]
Search strings under the 255 character limit can throw errors if character escapes are used. It seems like 8 escaped characters is too many, and will throw an error. But using 7 can also cause issues if the search string is too close to the character limit of 255. 

**Example**
```
const searchOptions = {
  matchWildcards: true,
};

const text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor in, 18 U.S.C. § 924[(]c[)][(]1[)][(]A[)][(]i[)].";

context.document.body.search(text, searchOptions);
```

One of the escaped characters must be removed to prevent the error.

**Avoid the error:**
`c[)][(]1[)][(]A[)][(]i[)].`
OR
`Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor in, 18 U.S.C. § 924[(]c[)][(]1[)][(]A[)][(]i`

Here's another search string that throws an error. It has the same number of escapes but in this case, removing an escaped character is not enough, you have to remove some of the unescaped text as well to avoid the error:

**Throws an error:** 
`mi bibendum neque egestas congue quisqu[(]2016[)]; laoreet sit amet cursus sit amet dictum sit amet justo donec enim diam [(]2009[)]; diam maecenas sed enim ut sem viverra aliqu[(]2006[)]; augue neque gravida in fermentum et sollicit[(]9th Cir. 2016[)]`

**Avoid the error:**
`bendum neque egestas congue quisqu[(]2016[)]; laoreet sit amet cursus sit amet dictum sit amet justo donec enim diam [(]2009[)]; diam maecenas sed enim ut sem viverra aliqu[(]2006[)]; augue neque gravida in fermentum et sollicit[(]`

If this is a bug, can it be fixed soon? If this is a current limitation, it would be great to know the constraints.

Tested on MacOS Big Sur 11.2.1, Desktop Word (v16.46)

**Comment by AbidRahman-MSFT** [comment]
Hey @handofthecode, 

Thanks for reporting the issue.

This is a limitation of Word. Unfortunately, there's nothing we can do from an API perspective to change this behavior. You will notice that when using the Find and Replace UI for Word, you will get a similar error when using the search string provided. Therefore I am going to resolve this as By Design.

![image](https://user-images.githubusercontent.com/53581099/111837428-18b67180-88b5-11eb-9e8f-957f6aaa6acd.png)
