### ISSUE TITLE
[SSO] With Restricted permissions, SSO is not working

### ISSUE THREAD

**Issue by gaurav2493** [OfficeDev/office-js#1727]
With permissions set to **Restricted**, SSO fails to work

## Expected Behavior
As per the [documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/understanding-outlook-add-in-permissions), the permissions are only applied on the **document**, so SSO should work if permission is set to **Restricted**.
On setting the permission to **Read** or **ReadWrite,** it is working

## Current Behavior
SSO authentication failes with the following error
```
{
  "name": "Permission Denied",
  "message": "You don't have sufficient permissions for this action.",
  "code": 7000
}
```

## Steps to Reproduce

  1. Create an excel addin ([example here](https://github.com/officedev/generator-office))
  2. Register an addin App in azure portal as [mentioned here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/register-sso-add-in-aad-v2) with scopes openid and profile 
  3. Setup sso by updating the appId generated in _step 2_ in the project from _step 1_. [Refer this link](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)
  4. In the click method, log the SSO succes/failure messages
  ```
try {
      OfficeRuntime.auth.getAccessToken({allowConsentPrompt: true}).then(token => {
        console.log(`success. token ====> ${token}`);
      }).catch( err => {
        console.log(`error ===> ${JSON.stringify(err)}`);
      });
    } catch (exception) {
      console.log(`Failed to get token. Error: ${JSON.stringify(exception)}`);
    }
```
Here SSO will work, when the addin is run.(npm start)
  5. Now change <Permissions>ReadWriteDocument</Permissions> to <Permissions>Restricted</Permissions>
and the SSO will fail wuth an error in console

{"name":"Permission Denied","message":"You don't have sufficient permissions for this action.","code":7000}

## Context
- We want our addin to have minimum possible permissions. 
- Authentication is must but we do not want the addin to have access to the document. 
- We are able to log in user using the popup authentication method, but it causes inconvenience to the user.

## Your Environment

* Platform :MacOs
* Host:Excel
* Office version number: 16.6
* Operating System: Mac Os 11.2.3 (20D91)

**Comment by lindalu-MSFT** [comment]
@JuaneloJuanelo @mattgeim Hi Juan, Hi Matt... as this is related to SSO, I am reassigning to you to triage. Thanks for your help! linda

**Comment by vivekchauhan** [comment]
@lindalu-MSFT @JuaneloJuanelo It will be great if we can get any update about the status of this issue as when we are using the most secure way prescribed by MSFT, the SSO is not working.

**Comment by mattgeim** [comment]
@vivekchauhan the SSO API requires ReadDocument permission to work - the Word/Excel/PowerPoint related permissions documentation can be found [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins).  In Outlook(the permissions documentation you linked to) the SSO API also does not work under Restricted as it contains user information when the token is returned.

Feel free to re-open if this didn't answer your question - thanks!
