### ISSUE TITLE
Can't copy formula if parameter using concatenating

### ISSUE THREAD

**Issue by leybal** [OfficeDev/office-js#1728]
Hi
Our team work with custom formulas in online Excel. We notice an error when we trying copy whole spill formula. A formula's paramenter we crete via concatenating cell value with custom name from very hidden sheet and string. It's looks like this =FORMULA(cellName_FromVeriHiddenSheet & "string"). We can copy formula selecting first cell. But an error occurs when we select the entire range of the formula and try to copy it ([screenshot](https://drive.google.com/file/d/1ugkInPux_clAx8eQe9qBM9yFqODMGvOQ/view?usp=sharing)).

## Expected Behavior

Select the entire range of formula, copy and paste the formula. 

## Current Behavior

An error occurs when we select the entire range of the formula and try to copy it.

## Steps to Reproduce, or Live Example

1. Open desktop Excel. Create sheet and set custom cell name, like cellName_FromVeriHiddenSheet.
2. Make the sheet very hidden and save the workbook on onedrive.
3. Create custom function, that accept string parameter and return matrix. For example =FORMULA(cellName_FromVeriHiddenSheet & "string").
4. Select first and second cell of formula and copy it using combination Ctrl+C.

## Context

Users of your add-in cannot copy spill formulas. 

## Your Environment

* Platform: Office on the web
* Host: Excel
* Office version number: 16.0.13914.37952
* Operating System: Windows 10
* Browser (if using Office on the web): Google Chrome

## Useful logs
Session ID: 30ba50b5-ed55-4bf5-a7f8-7424863a87c8

**Comment by qinliuMSFT** [comment]
Hi @leybal , thanks for reporting this issue. To make myself more clearly, could you please answer the following questions:
1. Does it also repro in Desktop Excel?
2. Does it also repro if the formula's parameter from visible sheet or hidden sheet? or this issue only repro when formula's parameter from very hidden sheet?
3. I written a sample custom functions/formula like below, is it correct? if not, could you please give us a sample snippet?
        Function:
            _function customSum(x: string): string[][] {
                return [[x], [x]];
            }_
        Formula:
            _=SCRIPTLAB.BASICCUSTOMFUNCTION1.CUSTOMSUM(CustomCellName&"0")_
4. Could you please give us a screenshot or gif for repro step 4? I could check if my repro step is correct.

**Comment by leybal** [comment]
@qinliuMSFT thanks for the questions. It seems that the problem arises when we refer to a cell with sheet name such as Sheet1!A1. Sometimes we fail to copy the formula. But if only a cell is specified in the formula parameters, without a sheet name (like A1), there is no problem. Also Its repro for regular Excel functions like this =IF(Sheet1!A1 <> "", MUNIT(3), "").
We made [the video](https://drive.google.com/file/d/1VVWoVBM22uK6xZK277PMR7_WA9lvzOKN/view?usp=sharing) for you and can add the following details:

1. No, we notice this behavior only for Excel Online
2. It's also reproduce if the formula's parameter from any sheet.
3. Function:
 * @customfunction
 * @param {string} x
 * @param {string} y
 * @returns The spill.
 */
function customSum(x: string, y: string): string[][] {
  return [[x], [x], [y], [y]];
}
Formula:
=SCRIPTLAB.BASICCUSTOMFUNCTION4.CUSTOMSUM(Sheet1!A1, A2)

Session ID: dfaf560e-9636-492d-ba4e-cea54b0af21c

**Comment by grangeryy** [comment]
From the repro video, this issue also happens to regular Excel functions like IF. @lumine2008 do you know about this?

**Comment by lumine2008** [comment]
It looks like there is no API called for reproing this issue? if yes, it seems this is not a office.js related issue.

**Comment by lumine2008** [comment]
I am going to close this isuse due to this issue is not related to Office JS. thanks.

**Comment by leybal** [comment]
@lumine2008 thanks for the answer. How we can track the progress of this bug?
Should we report this issue on another site?
