### ISSUE TITLE
Incorrect value returned by `Office.context.displayLanguage`

### ISSUE THREAD

**Issue by yanli0303** [OfficeDev/office-js#1731]
On macOS 11.2.2 (Big Sur), Outlook Desktop application, the `Office.context.displayLanguage` returns incorrect value.

## Expected Behavior

`Office.context.displayLanguage` should returns `zh-CN` when the macOS language is set to `zh-CN`.

## Current Behavior

`Office.context.displayLanguage` returns `en-US` when the macOS language is set to `zh-CN`.

## Steps to Reproduce, or Live Example

- Set macOS v11.2.2 language to en-US (English, United States).
- Launch Outlook Desktop application, call out task pane of an add-in.
- Inspect the add-in (call out the developer tools of the add-in webview):
  - `navigator.language` returns `en-us` which is expected.
  - `Office.context.contentLanguage` returns `en-US` which is expected.
  - `Office.context.displayLanguage` returns `en-US` which is expected.
- Quit Outlook.
- Open system preferences, change OS language to zh-CN (Chinese, China mainland).
- Quit system preferences (no need to restart the OS, I can still reproduce this issue by restarting the OS).
- Launch Outlook Desktop application, call out task pane of an add-in.
  - The Outlook Desktop UI now displays in Chinese.
  - My add-in still displays in English.
- Inspect the add-in (call out the developer tools of the add-in webview):
  - `navigator.language` returns `zh-cn` which is expected.
  - `Office.context.contentLanguage` returns `zh-CN` which is **NOT** expected.
  - `Office.context.displayLanguage` returns `en-US` which is **NOT** expected.

See https://user-images.githubusercontent.com/3038713/111548744-877aba00-8751-11eb-841e-5d926d21430e.mp4

Outlook add-in manifest for testing: https://gist.github.com/yanli0303/9a66448506a4bdf463a961b63523ca43
Source code of above Outlook add-in: https://codesandbox.io/s/officecontextdisplaylanguage-56xr8

## Context

I wanted to localize my add-in with the [`Office.context.displayLanguage`](https://docs.microsoft.com/en-us/javascript/api/office/office.context?view=excel-js-preview#displayLanguage).

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac Book Pro, Outlook Desktop Application
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook v16.48 (21031404)
* Operating System: macOS v11.2.2 Big Sur
* Browser (if using Office on the web): N/A.

**Comment by Rick-Kirkham** [comment]
The Mac OS language is not what determines these values. They are determined by the Office language settings in  File > Options > Language in the Office host application. See this documentation page: [Office.context](https://docs.microsoft.com/en-us/javascript/api/office/office.context?view=common-js#displayLanguage)

**Comment by yanli0303** [comment]
> The Mac OS language is not what determines these values. They are determined by the Office language settings in File > Options > Language in the Office host application. See this documentation page: [Office.context](https://docs.microsoft.com/en-us/javascript/api/office/office.context?view=common-js#displayLanguage)

@Rick-Kirkham 

- On macOS Outlook Desktop Application, File > Options > Language isn't available (I can't find any settings in the Preferences that are related to language).
- I can't reproduce this issue on newer macOS with Big Sur v11.2.3 and older macOS with Mojave v10.14.2. **Per my testing, the Mac OS language is indeed what determines the value of `Office.context.displayLanguage`.**
- I can also confirm that the Office 365 account language setting doesn't affect `Office.context.displayLanguage` on macOS.
- Your explanation can't explain why both `Office.context.displayLanguage` and `Office.context.contentLanguage` changed to incorrect values after I changed my macOS language.

**Comment by exextoc** [comment]
Hey @yanli0303 ,

Are you seeing this issue in the New Outlook for Mac, or the Old Outlook for Mac?

**Comment by yanli0303** [comment]
> Hey @yanli0303 ,
> 
> Are you seeing this issue in the New Outlook for Mac, or the Old Outlook for Mac?

I can reproduce this issue with both new and old of Outlook for Mac desktop applications.

<img width="1416" alt="Screen Shot 2021-03-23 at 10 04 15" src="https://user-images.githubusercontent.com/3038713/112159286-60900e00-8bbf-11eb-8cd9-3a4766407e22.png">

**Comment by exextoc** [comment]
Thanks for sharing the issue. We could reproduce this issue at our end.
We have added this to our backlog but unfortunately 
we do not have any timelines to share for the same.

**Comment by exextoc** [comment]
@yanli0303 We tried to repro on some other macOS versions also but could not repro this. Can you please confirm that it only repros on 11.2.2 for you?

**Comment by exextoc** [comment]
@yanli0303 We tried to repro on some other macOS versions also but could not repro this. Can you please confirm that it only repros on 11.2.2 for you?

**Comment by yanli0303** [comment]
> @yanli0303 We tried to repro on some other macOS versions also but could not repro this. Can you please confirm that it only repros on 11.2.2 for you?

I was not able to reproduce this issue in any other version.

**Comment by GrumpyAL** [comment]
I'm seeing something similar to this with other locale codes for MacOS and iOS.  I'm not sure if related to this or if you'd prefer or I open a new bug (or if it's working as intended).

However, on both Mac or iOS if locale is set to es-ES (or any es-XX locale) Office.context.displayLanguage will always return es-US.  This is also true for en-GB (it will return en-US).  Works as expected on OWA and Android.

**Comment by exextoc** [comment]
@GrumpyAL, I tried on Mac with es-ES and display language is returned as es-ES. You can open a new bug with the details if you are still facing the problem.

**Comment by GrumpyAL** [comment]
https://user-images.githubusercontent.com/28786762/155554997-a7361aec-3da7-4fd6-ae4b-e153a27c88c1.mp4

This shows us changing to es-MX and getting es-US but this happens for multiple Spanish locales that we tried (Panama, Colombia, Spain, and Mexico)
