### ISSUE TITLE
Outlook: forMSGraphAccess not work for OfficeRuntime.auth.getAccessToken api

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#1732]
when i execute this demo code in Outlook add-in:
```
OfficeRuntime.auth.getAccessToken({forMSGraphAccess: true}).then( function(result) {console.log(result);});
```
i can get jwt token success.
But in fact, my app was not granted by admin.
when i try to use this jwt token to get access_token, by call this api:
```
https://login.microsoftonline.com/common/oauth2/v2.0/token/
client_id: my app's client id
client_secret: my app's client secret
assertion: the jwt token from OfficeRuntime.auth.getAccessToken({forMSGraphAccess: true})
requested_token_use: on_behalf_of
grant_type: urn:ietf:params:oauth:grant-type:jwt-bearer
scope: User.Read
```
i get an error for not granted.
```
{
    "error": "invalid_grant",
    "error_description": "AADSTS65001: The user or administrator has not consented to use the application with ID 'ab71e945-f7b8-4d5e-84ce-f631e9ea7e52' named 'maiken-test111'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 23effd36-b8da-4a49-8589-e15f0660a100\r\nCorrelation ID: 5caece2f-b847-4c70-be5b-d5ef101abc5b\r\nTimestamp: 2021-03-17 13:07:59Z",
    "error_codes": [
        65001
    ],
    "timestamp": "2021-03-17 13:07:59Z",
    "trace_id": "23effd36-b8da-4a49-8589-e15f0660a100",
    "correlation_id": "5caece2f-b847-4c70-be5b-d5ef101abc5b",
    "suberror": "consent_required"
}
```

**Comment by exextoc** [comment]
Hey @hello-chenchen ,

Can you please tell us which Outlook platform (Windows/Mac/Web) you're seeing this issue in and what is the build number you're on?

**Comment by hello-chenchen** [comment]
hi @exextoc , it happened on Web. Not sure if it works for Mac And Windows. My problem has been solved i think. Cause when i re-create an App on Azure On Admin Account A(In tenant A). And only request User.Read permissions(No Need Admin consent). Then I use Admin Account B(In tenant B), to assign this App to B tenant, By Deploy My Add-in Manifest on Admin Center. It Don't Need Admin grant, can get access token by call: 
```
https://login.microsoftonline.com/common/oauth2/v2.0/token/
client_id: my app's client id
client_secret: my app's client secret
assertion: the jwt token from OfficeRuntime.auth.getAccessToken({forMSGraphAccess: true})
requested_token_use: on_behalf_of
grant_type: urn:ietf:params:oauth:grant-type:jwt-bearer
scope: User.Read
```
It can get access token, no need Admin grant.
I don't know if in the past, i do some mistake for this step, cause i don't know well for some steps and tips for getaccesstoken api. Maybe i need more research for this behavior. Will close this first.
