### ISSUE TITLE
Event based feature working on outlook.com but not outlook windows

### ISSUE THREAD

**Issue by vddgil** [OfficeDev/office-js#1733]
I'm trying to implement an event-based feature to automatically insert a signature.
It's working on outlook web but not on outlook windows (Same office 365 account)

## Expected Behavior
It should work on outlook windows

## Current Behavior
It's not working on outlook windows

## Your Environment
* Platform : PC
* Host :Outlook
* Office version number: Outlook 16.0.13801.20240
* Operating System: Windows 1°
* Browser (if using Office on the web): Chrome

## command.js file
Find there my command.js file https://gist.github.com/vddgil/3d37f1dcaeb355396fd4c18cfc755620

**Comment by exextoc** [comment]
Could you describe your scenario you are trying to achieve?

Are you seeing any errors in the console? What behavior are you seeing (ie signature API not called at all, signature API called but not adding any data, callback not reached, API adding incorrect data)?
