### ISSUE TITLE
Teams meeting feature does not save in OWA if outlook Add-in App save custom property(extended property) using office.js

### ISSUE THREAD

**Issue by anuragjaiswal18** [OfficeDev/office-js#1736]
Hi,
Teams meeting feature does not save in appointment in OWA if outlook Add-in App save custom property(extended property) using Office.js , but if custom properties are saved using Office.js and later add Teams meeting  in appointment , it works and save Teams meeting data.
This works fine in case of native Outlook client.

## Expected Behavior
Teams meeting option should be saved if user has selected in meeting. It should not be affected by Office.js save custom property(extended property).

## Current Behavior
Create a new meeting in OWA and add Teams meeting feature in meeting. Now use outlook Add-in App to save custom property(extended property) using Office.js. This add-in will add resource location. Add subject and attendee and save meeting. Now open this meeting again , it will not show previously added Team meeting option. 
But if custom properties are saved using Office.js and later add Team meeting  in appointment , it works and save Teams meeting data.
This works fine in case of native Outlook client for all case.

Repro steps below: 
1) Open new appointment in OWA. 
2) Enable Teams meeting option in meeting.
3) Use Outlook add-in app to save custom properties ( extended properties) using office.js
4) Add other details in meeting and save it.
5) Now open this meeting again to view. It will not show previously added Teams meeting (Teams meeting slider is seen as off) . 
![Capture](https://user-images.githubusercontent.com/31452110/111764258-09412380-88c9-11eb-8012-89923faf0c4a.PNG)
![Capture2](https://user-images.githubusercontent.com/31452110/111764859-aef49280-88c9-11eb-88cb-1cdae432d756.PNG)
![Capture3](https://user-images.githubusercontent.com/31452110/111766511-a2713980-88cb-11eb-9232-944774cc0496.PNG)

## Your Environment
Office 365 OWA + Offic.js

**Comment by exextoc** [comment]
Hey @anuragjaiswal18 ,

Thank you for reporting this issue,. We are able to reproduce this issue and have added it to our backlog. However, we have no timelines to share at this point.

**Comment by exextoc** [comment]
Hello @anuragjaiswal18, 

Can you please try this again on your end and let us know if the issue still persists?

**Comment by anuragjaiswal18** [comment]
Hello @exextoc ,
This issue is still replicating in OWA.

**Comment by exextoc** [comment]
> Hello @exextoc ,
> This issue is still replicating in OWA.

Can you please upload a video of the repro steps and mention the version of OWA which you're using?

**Comment by anuragjaiswal18** [comment]
thanks @exextoc  for your response.
I verified again in OWA today. Its working now as expected. We will do some more testing around it and will let you know.

**Comment by anuragjaiswal18** [comment]
Its working now 👍 . Thank you so much .

**Comment by ElizabethSamuel-MSFT** [comment]
This has been verified as fixed so closing.
