### ISSUE TITLE
Outlook REST API call ends with 403 response code when auth with callback token from OfficeJs on Android

### ISSUE THREAD

**Issue by agelenava** [OfficeDev/office-js#1737]
## Expected Behavior
Callback Token works fine as it was before.

## Current Behavior
On modern versions of Microsoft Outlook on Android, the callback token is invalid and REST API request ends with 403 if using the token to auth.

## Steps to Reproduce, or Live Example
- use o365 account;
- on Android with MS Outlook version 4.2108.3 (32108814) or 4.2109.2 (32109815) сall OfficeJs `getCallbackTokenAsync`, handle callback with the token;
- Make REST API call `https://outlook.office365.com:443/api/v2.0/me/messages/[your ItemId]`  with the token;

## Context
Can't use a callback token to download an item on our backend.

## Your Environment
Android (9 and 10) with Microsoft Outlook version 4.2108.3 (42108814) or 4.2109.2 (32109815)

## Useful logs
with version 4.2108.3 (32108814) it works fine.

Here are headers in 403 response
> X-CalculatedFETarget: SJ0PR05CU007.internal.outlook.com
> X-BackEndHttpStatus: 403;403
> X-FEProxyInfo: SJ0PR05CA0185.NAMPRD05.PROD.OUTLOOK.COM
> X-CalculatedBETarget: BYAPR01MB5208.prod.exchangelabs.com
> X-RUM-Validated: 1
> X-BeSku: WCS5
> x-ms-appId: ddb00a58-4ace-4bbd-880b-ce841b0ae55d
> Rate-Limit-Limit: 10000
> Rate-Limit-Remaining: 10000
> Rate-Limit-Reset: 2021-03-18T15:11:33.140Z
> x-ms-diagnostics: 2000008;reason="The callback token's protocol claim value '{0}' doesn't match the current requested protocol.";error_category="invalid_grant"
> OData-Version: 4.0
> X-DiagInfo: BYAPR01MB5208
> X-BEServer: BYAPR01MB5208
> X-Proxy-RoutingCorrectness: 1
> X-Proxy-BackendServerStatus: 403
> X-FEServer: SJ0PR05CA0185;SA0PR11CA0029
> Cache-Control: private
> Date: Thu, 18 Mar 2021 15:11:32 GMT
> Server: Microsoft-IIS/10.0
> WWW-Authenticate: Bearer client_id="00000002-0000-0ff1-ce00-000000000000", trusted_issuers="00000001-0000-0000-c000-000000000000@*", token_types="app_asserted_user_v1 service_asserted_app_v1", error="invalid_token"
> X-AspNet-Version: 4.0.30319
> X-Powered-By: ASP.NET

**Comment by ElizabethSamuel-MSFT** [comment]
@agelenava Thanks for raising this issue.

@exextoc Can Android folks take a look?

Thanks.

**Comment by agelenava** [comment]
I found a difference, the broken callback token has `"scope":"AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0Aabol7TmVQkmDNhnSdkE8jAAAiPSJTAAA"` in `appctx`, whereas working token has `"scope":"ParentItemId:AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0Aabol7TmVQkmDNhnSdkE8jAAAiPSJTAAA"`. Maybe it's a key to find out the root cause. Maybe this `ParentItemId:` is important to authorize REST API cal but I'm not complete sure for now.

**Comment by exextoc** [comment]
@agelenava can you share following details:
1.  Is it possible for you to share code snippet for the call you are making to getCallbackTokenAsync and the REST API call? 
2. How are you getting the REST endpoint "https://outlook.office365.com:443/api/v2.0/"? Are you using Office.context.mailbox.restUrl?
3. Can you try to decode both tokens(working/broken) on [https://jwt.io/](https://jwt.io/) and see if there is any difference?

**Comment by agelenava** [comment]
Sorry for delay,
1. Here is my code for getCallbackTokenAsync 

> Office.context.mailbox.getCallbackTokenAsync(asyncResult => { 
> if (asyncResult && asyncResult.status === Office.AsyncResultStatus.Succeeded) {
>    console.log(asyncResult.value);
> }
> } );

Yes, I know it is hard to get results from console log on Andorid but I can't provide the whole code we use and I think it is not necessary here.
Next we send callbackToken to our back-end.

Here is a code snipet to make REST API call  (c# code)

> const string V2_API_URL = "https://outlook.office365.com/api/v2.0/";
> var _client = new GraphServiceClient(
>                V2_API_URL,
>                new DelegateAuthenticationProvider(requestMessage =>
>                {
>                    requestMessage.Headers.Authorization = new OAuthAuthenticationHeader(callbackToken);
>                    return Task.CompletedTask;
>                }),
>                new HttpProvider(new RestGraphSerializer())
>            );
> _message = await _client.Me.Messages[_id].Request().GetAsync().ConfigureAwait(false);

2. We just hardcode it for now.
3. Tokens payload are
for broken token 

> {
>   "nameid": "ddb00a58-4ace-4bbd-880b-ce841b0ae55d@848c5ff4-6a22-405e-a845-732e98511fdd",
>   "ver": "Exchange.Callback.V1",
>   "appctxsender": "https://my-host-for.addin.something/main.html?parameter=some@848c5ff4-6a22-405e-a845-732e98511fdd",
>   "issring": "WW",
>   "appctx": "{\"oid\":\"dc3f8f9a-c0f8-4243-9a8c-ccf89099cd2b\",\"smtp\":\"my.user@email.test\",\"upn\":\"my.user@email.test\",\"scope\":\"AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0Aabol7TmVQkmDNhnSdkE8jAAAiPSJTAAA\"}",
>   "nbf": 1616074356,
>   "exp": 1616074656,
>   "iss": "00000002-0000-0ff1-ce00-000000000000@848c5ff4-6a22-405e-a845-732e98511fdd",
>   "aud": "00000002-0000-0ff1-ce00-000000000000/outlook.office365.com@848c5ff4-6a22-405e-a845-732e98511fdd",
>   "happ": "OutlookService"
> }

here is one for working

> {
>   "nameid": "ddb00a58-4ace-4bbd-880b-ce841b0ae55d@848c5ff4-6a22-405e-a845-732e98511fdd",
>   "ver": "Exchange.Callback.V1",
>   "appctxsender": "https://my-host-for.addin.something/main.html?parameter=some@848c5ff4-6a22-405e-a845-732e98511fdd",
>   "issring": "WW",
>   "appctx": "{\"oid\":\"dc3f8f9a-c0f8-4243-9a8c-ccf89099cd2b\",\"smtp\":\"my.user@email.test\",\"upn\":\"my.user@email.test\",\"scope\":\"ParentItemId:AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0Aabol7TmVQkmDNhnSdkE8jAAAiPSJTAAA\"}",
>   "nbf": 1616077603,
>   "exp": 1616077903,
>   "iss": "00000002-0000-0ff1-ce00-000000000000@848c5ff4-6a22-405e-a845-732e98511fdd",
>   "aud": "00000002-0000-0ff1-ce00-000000000000/outlook.office365.com@848c5ff4-6a22-405e-a845-732e98511fdd",
>   "happ": "API"
> }

**Comment by agelenava** [comment]
@exextoc is it enough or do you want something more?

**Comment by exextoc** [comment]
Outlook rest API has been deprecated and is not being supported
https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/use-outlook-rest-api

Migrate existing apps to use [Microsoft Graph](https://docs.microsoft.com/en-us/graph/overview-major-services). See a [comparison](https://docs.microsoft.com/en-us/outlook/rest/compare-graph) to start your migration.

**Comment by agelenava** [comment]
Ok, I know it has been deprecated and we did a plan for migration to the Graph, BUT for now, it looks like not Graph issue because it worked recently well and if you examine callback token payload you can find the difference between working token and broken one in `appctx`
in broken it is `"scope":"AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0Aabol7TmVQkmDNhnSdkE8jAAAiPSJTAAA"` 
in working it is `"scope":"ParentItemId:AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0Aabol7TmVQkmDNhnSdkE8jAAAiPSJTAAA"` 
So for me, it looks like there were some changes inside callback token generation on Android. 

Is it expected changes? Why iOS token generation didn't change yet?

In case it is expected changes then we have to migrate to Graph ASAP I think

**Comment by exextoc** [comment]
@agelenava This appears to be a bug in Android. Thanks for reporting this issue regarding getCallbackTokenAsync. It has been put on our backlog. We, unfortunately, have no timelines to share at this point. We will update this thread once the fix is available.
Regarding REST API, the target deprecation is Nov 2022. Timelines and further details are available [here](https://techcommunity.microsoft.com/t5/exchange-team-blog/outlook-rest-api-beta-and-outlook-rest-api-v2-0-deprecation/ba-p/1898162). 

Internal tracking id: Office: 2022940

**Comment by agelenava** [comment]
Thank you! We'll wait for an update :-) 
And we're doing our migration to the Graph in the background.
