### ISSUE TITLE
From Excel Office.js Add In, Desktop App Web Viewer will not retrieve saved credentials

### ISSUE THREAD

**Issue by ic3guy** [OfficeDev/office-js#1738]
My add-in makes an iframe call to another server, which causes a windows security box to appear and ask for credentials. I enter the credentials (I can see they are saved in credential manager) and the call succeeds. If I restart the add-in, the windows security box pops up again for my credentials.

## Expected Behavior

Desktop App Web Viewer should have access to saved Credentials.

## Current Behavior

Desktop App Web Viewer requires entering credentials every time add-in loads.

## Context

It is annoying for developers to have to enter their credentials each time they reload.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel 
* Office version number: Office 365 - Version 1908
* Operating System: Windows 10 - 20H2
* Edge is used to render (Desktop App Web Viewer)
* This is an Angular 11 application

**Comment by ElizabethSamuel-MSFT** [comment]
@ic3guy Thanks for raising this issue.

@smaremanda Can you take a look or assign to an appropriate person to investigate?

Thanks.

**Comment by ic3guy** [comment]
If I load the add-in in Edge (outside of Excel) the iframe load picks up the saved credentials just fine.

**Comment by ic3guy** [comment]
The other issue is why is this credential even popping up? The server respondes with an WWW-Authenticate: NTLM so the credentials should be picked up.

**Comment by ic3guy** [comment]
I figured this out by using fiddler to first confirm that NTLM was being correctly requested but not automatically triggering IWA (Integrated Windows Authentication)
- It was working in Edge outside of Excel because that's Chromium Edge but my version of Excel is using WebView (Legacy Edge) to render the add-in
- I had to add the CNAME (which matches the URL that I was requesting) to the IE Internet Properties -> Security -> Local Intranet -> Sites
- The red herring was that the windows auth box was referencing the server name and I tried adding that to the internet properties at first, which didn't work.

I want to add that I don't need any saved credentials, IWA works as expected.

**Comment by rosergeev** [comment]
Hi, @ic3guy 
We've experienced the same issue, can you give me a hint or example what exactly I have to add to internet props instead of server name?

**Comment by ic3guy** [comment]
@rosergeev I used the cname for the auth machine. The cname that is requested by the front end.
