### ISSUE TITLE
Outlook 365 bug? sent-item message details shows nothing

### ISSUE THREAD

**Issue by michahell** [OfficeDev/office-js#174]
I think this is a bug, or otherwise very confusing.
If you right-click a message in your `sent-items` folder:

![screen shot 2018-06-25 at 10 58 07](https://user-images.githubusercontent.com/225784/41841195-f4baa93c-7867-11e8-9295-b58ba2a084d6.png)

then open `message details`, you get an empty dialog without any info:

![screen shot 2018-06-25 at 10 56 42](https://user-images.githubusercontent.com/225784/41841099-aec6f2fa-7867-11e8-94f2-4409a56d1506.png)

It is unclear whether this is intended: 
- that we should actually be able to also see things like set headers and other outbound mail info, or
- that this info indeed is not available for sent-items. 

In that last case, multiple UX pattern exists to inform the user of unavailability, by:
- removing the item entirely (confusing)
- graying out the option (less confusing)
- putting text in the dialog stating unavailability (might be best here)

**Comment by JuaneloJuanelo** [comment]
unfortunately this is not an issue associated with Office Extensibility.
