### ISSUE TITLE
Can't insert new slide from Ribbon after inserting Slide via insertSlidesFromBase64

### ISSUE THREAD

**Issue by dhilgarth** [OfficeDev/office-js#1740]
## Expected Behavior
After inserting a slide with `insertSlidesFromBase64` the 'New Slide' button in the Ribbon bar continues to work as expected.

## Current Behavior
The button works before but not longer after calling `insertSlidesFromBase64`. Clicking it will have no effect at all.

## Steps to Reproduce, or Live Example
I created a full add-in demonstrating the behavior. It can be found here:
https://github.com/dhilgarth/PowerPointIssueForeverPromise
1. Click on the New Slide button. A window is shown. Choose a slide and insert it
2. Click on the Run link at the bottom of the task pane. It will insert a slide.
3. Click on the New Slide button again. Nothing happens

## Your Environment
* Platform: Office on the web
* Host: PowerPoint
* Operating System: Windows 10 1909
* Browser: Chrome, Edge Chromium, Firefox

## Demonstration
Video: https://cloud.sovarto.com/f/8aaf61dde0d74e78a140/

**Comment by ElizabethSamuel-MSFT** [comment]
@dhilgarth Thanks for letting us know about this.

@sohailzafar Can you take a look or assign to someone else to investigate?

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@dhilgarth Is this still an issue?

@wangyun-microsoft Can you take a look?

Thanks.
