### ISSUE TITLE
Inserting an image into selected placeholder behaves weird in PowerPoint

### ISSUE THREAD

**Issue by dhilgarth** [OfficeDev/office-js#1743]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
When I select a placeholder and insert an image via `setSelectedDataAsync`, it should always insert the picture into the selected placeholder and scale it to match that placeholder. It should not affect any other placeholders.

## Current Behavior
On a slide with two placeholders, if I select any placeholder and then insert an image, the image gets inserted at the center of the selected placeholder, but it is very small and BOTH placeholders disappear.
If I don't select any element, the image gets inserted in the first placeholder in the correct size -> That's expected.
Yesterday, it worked correctly when selecting the left placeholder but didn't when selecting the right. Today, it behaves incorrectly no matter what placeholder I select.

## Steps to Reproduce, or Live Example
Sample add-in: https://github.com/dhilgarth/PowerPointIssueWeirdInsertImageBehavior
1. Insert new slide with two placeholders
2. Click Run in taskpane -> Image is inserted in left placeholder in correct size, right placeholder is still there -> Expected behavior
3. Insert another new slide with two placeholders
5. Select left placeholder
6. Click Run in taskpane -> Image is inserted in right placeholder. But it is very small and the left placeholder suddenly is gone as well -> Bug

## Context
We want to have a consistent user experience when inserting images via our taskpane addin. Right now, we get bug reports.

## Your Environment
* Platform: Office on the web
* Host: PowerPoint
* Operating System: Windows 10 1909
* Browser: Chrome, Edge Chromium, Firefox

## Demonstration
Video: https://cloud.sovarto.com/f/48f7c60381d9400caa50/

**Comment by ElizabethSamuel-MSFT** [comment]
@dhilgarth Thanks for raising this issue.

@sohailzafar Can you take a look or assign to an appropriate person to investigate?

Thanks.

**Comment by mbice** [comment]
@sohailzafar Any updates on this? We are experiencing the same issue. Works fine in desktop app, but has the above described behavior in PowerPoint web.

**Comment by mbice** [comment]
Hi,

This has become a blocking issue for us rolling out our PowerPoint addin because we can't have a consistent photo insertion experience across desktop/web. Desktop seems fine, no issues. PowerPoint web still has the issue described above, which makes photo insertion with placeholders kind of useless.

Any way to get an update on whether this is acknowledged and if a fix is possible? Or a potential workaround?

cc @sohailzafar @ElizabethSamuel-MSFT 

Thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@mbice: @sohailzafar no longer works in this space. Assigning to @wangyun-microsoft to take a look.

Thanks.

**Comment by wangyun-microsoft** [comment]
Adding Onur. 

Onur, can you look at this and provide some insights?

Thanks.

**Comment by mbice** [comment]
@ononder any insight on what might be happening with this one?

Thanks!
