### ISSUE TITLE
Inserting image via setSelectedDataSync

### ISSUE THREAD

**Issue by dhilgarth** [OfficeDev/office-js#1744]
## Expected Behavior
The Undo and Redo buttons behave consistently.

## Current Behavior
Inserting an image doesn't add its own Undo entry but it does hijack existing ones

## Steps to Reproduce, or Live Example
Sample add-in: https://github.com/dhilgarth/PowerPointIssueWeirdInsertImageBehavior

1. Click on Run in the taskpane
2. Image is inserted but Undo button is disabled
3. Insert Shape -> Undo button gets enabled and is functional
4. Add new slide with placeholder
5. Click on Run
6. Image is inserted, Undo button is still enabled
7. Click Undo: Image insertion is undone
8. Click Undo until the button becomes disabled -> The button gets disabled one step too early. It's no longer possible to undo the insertion of the Shape from step 2 -> Inserting an image doesn't add its own Undo entry but it does hijack existing ones

## Context
We want to allow our users to undo the actions performed by our taskpane addin in a consistent manner.

## Your Environment
* Platform: Office on the web
* Host: PowerPoint
* Operating System: Windows 10 1909
* Browser: Chrome, Edge Chromium, Firefox

## Demonstration
Video: https://cloud.sovarto.com/f/38ed5f62ed694479b207/

**Comment by ElizabethSamuel-MSFT** [comment]
@dhilgarth Thanks for letting us know about this issue.

@sohailzafar Can you take a look or assign to an appropriate person to investigate?

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@dhilgarth Is this still an issue for you?

@wangyun-microsoft Can you take a look?

Thanks.
