### ISSUE TITLE
Word online when trying to create/open new document from base64 string i get an error

### ISSUE THREAD

**Issue by MantautasG** [OfficeDev/office-js#1745]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hey, I have an add-in, in my case I get a base64 document string and want to create/open new document in online word.
My code is:
```
function openWordDocument(templateFile: string, dataPresentationTemplateNr: Number): void {
	Word.run(context => {
        debugger;
		var doc = context.application.createDocument(templateFile);
        context.load(doc);

		context.sync()
			.then(() => {
				doc.properties.customProperties.add("DataPresentationTemplateNr", dataPresentationTemplateNr);
				doc.open();
				context.sync();
			});
		return context.sync();
	}).catch(errorHandler);
}
```
when this function executes I get this error code in console: 
`Uncaught (in promise) RichApi.Error: The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information. at new n (https://appsforoffice.microsoft.com/lib/beta/hosted/word-web-16.00.js:26:301595) at n.o.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/beta/hosted/word-web-16.00.js:26:363168) at https://appsforoffice.microsoft.com/lib/beta/hosted/word-web-16.00.js:26:361273`

## Expected Behavior
I expect online word to open newly created document.

## Current Behavior
When document is being created online word prompts a message about document being saved to OneDrive:
![image](https://user-images.githubusercontent.com/28557416/112104653-24a37b80-8bb4-11eb-87cc-53599e4f53c6.png)
which it does, document is successfully saved. In my understanding the issue happens when online word tries to open the document.

## Steps to Reproduce, or Live Example

* Link to live example: for now can't provide live example, steps to reproduce are covered in video below.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: windows 10 17134.1902
* Browser (if using Office on the web): chrome

## Useful logs

- [Uncaught (in promise) RichApi.Error: The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information. at new n (https://appsforoffice.microsoft.com/lib/beta/hosted/word-web-16.00.js:26:301595) at n.o.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/beta/hosted/word-web-16.00.js:26:363168) at https://appsforoffice.microsoft.com/lib/beta/hosted/word-web-16.00.js:26:361273 ] Console errors

## Demonstration
Video: https://bssitlt-my.sharepoint.com/:v:/g/personal/mantautas_gimbutis_bssitlt_onmicrosoft_com/EZ3gpKmSWxBOvr8ZUBin88oBMWVXdDRQijjuoqOFwycJKg?e=MgLvxm

**Comment by RuoyingLiang** [comment]
@MantautasG Thanks for reaching us. The problem here is the generated document doesn't support to set property in Word WAC. Because in browser a word session cannot edit another word document, the add-in cannot set the value to the new doc. So in your code, if you didn't set the property, the document can open as you expected. 

If you need to set the property in the new opened doc, you can add that to the Base64 string( the template file). Then the new created doc will have the property set already.

**Comment by MantautasG** [comment]
@RuoyingLiang  Thank your for your answer. If I understand correctly my function in this case should look like this : 
```
function openWordDocument(templateFile: string, dataPresentationTemplateNr: Number): void {
	Word.run(context => {
        debugger;
		var doc = context.application.createDocument(templateFile);
        context.load(doc);

		context.sync()
			.then(() => {
				doc.open();
				context.sync();
			});
		return context.sync();
	}).catch(errorHandler);
```
The problem is that i still get the same error as mentioned earlier.
