### ISSUE TITLE
Remove attachments from previously drafted email fails

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#1746]
Unable to remove attachments from an email that during the "on send" handling (add-in) if that email was previously saved as a draft and attachments added prior to saving. I believe this may be considered that the "session" has ended, but this isn't exactly clear.

When attempting to remove the attachments, I see the following error:
```
The following attachments couldn't be deleted: [filename]. Please try again later.
```

## Expected Behavior
The ability to remove attachments from a message that was previously saved as a draft and later sent.

## Current Behavior
Error received when attempting to remove the attachments that were previously added to the draft (and sent at a later time).

## Steps to Reproduce, or Live Example
Here is some example code (quickly wrote this up for testing purposes). The steps to get into the state where the error is seen is as follows:

```
mailboxItem.getAttachmentsAsync({ asyncContext: null }, attachmentAsyncResult => {
        if (attachmentAsyncResult.status === Office.AsyncResultStatus.Succeeded) {
            if (attachmentAsyncResult.value.length === 0) {
                console.log('>>> No attachments...');
            } else {
                console.log('>>> Found attachments: ', attachmentAsyncResult.value);

                attachmentAsyncResult.value.forEach((item, index, array) => {
                    try {
                        Office.context.mailbox.item.getAttachmentContentAsync(item.id, { asyncContext: null }, (getAttachmentContentResult) => {
                            console.log('>>> Get attachment result: ', getAttachmentContentResult);
                        });

                        Office.context.mailbox.item.removeAttachmentAsync(item.id, { asyncContext: null }, removedAsyncValue => {
                            if (removedAsyncValue.status === Office.AsyncResultStatus.Succeeded) {
                                console.log('>>> Removed attachment: ', item.id);
                            } else {
                                console.log('>>> Error removing attachment: ', item.id, removedAsyncValue);
                            }
                        });
                    } catch (e) {
                        console.log(e);
                    }
                });

                setTimeout(() => {
                    messageSendingEvent.completed({ allowEvent: false });
                }, 60000);
            }
        } else {
            console.log('>>> Error retrieving attachments for item');
        }
    });
```

1. Compose a new email and open the add-in (doesn't do anything with attachments during compose).
2. Attach a file or two (doesn't appear to matter what type).
3. Save as draft.
4. Navigate to a different mailbox item and ensure your compose add-in pane has closed.
5. Navigate back to the draft and open your add-in.
6. At this point, you could try to click the "x" to delete the attachment. This results in an error for me as well. Or you can click send and let your "on send" function be triggered that attempts to remove the attachments (see example snippet above).

## Context
We want to remove all attachments from an email before it is sent and attach our own encrypted attachments. This works fine if the user does not save it as a draft and return, but fails with drafts that had the attachments added previously.

I verified that the attachment ids when the are added to the composed message match that of what is retrieved later from the draft during the "on send" add-in function. Yet, I receive the error that it is an Invalid Id for every attachment.

## Your Environment
Outlook.com

## Useful logs
In the network tab of dev tools in Chrome, I saw the following:
```
{
    "Header": {
        "ServerVersionInfo": {
            "MajorVersion": 15,
            "MinorVersion": 20,
            "MajorBuildNumber": 3955,
            "MinorBuildNumber": 27,
            "Version": "V2018_01_08"
        }
    },
    "Body": {
        "__type": "DeleteAttachmentResponse:#Exchange",
        "ResponseMessages": {
            "Items": [
                {
                    "__type": "DeleteAttachmentResponseMessage:#Exchange",
                    "RootItemId": null,
                    "MessageText": "The specified attachment Id is invalid.",
                    "ResponseCode": "ErrorInvalidAttachmentId",
                    "ResponseClass": "Error"
                }
            ]
        }
    }
}
```

**Comment by cody-lettau** [comment]
So I may have found what leads to this issue occurring.

When we are adding a notificationMessage to the message during compose, we see this error. Yet, when I do not add the notificationMessage to the email during compose (using ```Office.context.mailbox.item.notificationMessages.addAsync(...)```), we do not run into the issue removing attachments.

Why would this be?

**Comment by cody-lettau** [comment]
And further debugging has found that it likely has to do with the notificationMessage not having a unique id across different drafts.

**Comment by cody-lettau** [comment]
Can probably close this out, but the documentation should be a bit more descriptive around notification messages and the need for unique ids.

**Comment by ElizabethSamuel-MSFT** [comment]
@cody-lettau Thanks for letting us know about this issue and providing details.

@exextoc Can you take a look?

If the docs need to be clarified, let me know.

Thanks.

**Comment by exextoc** [comment]
@cody-lettau Ideally notification messages should not affect the attachments. You also mentioned that you are not able to remove the attachment via UI(by clicking on x). Is this problem also solved when you change notification message ID?
Can you share the notification message code snippet ?

**Comment by cody-lettau** [comment]
@exextoc it did appear to fix the issue with even clicking the "x" to delete the attachment from what I saw. So I have a toggle button to enable/disable security. Turning that on/off would add/remove the notification message. Then it appeared to cause issues when saved as a draft and opened later and sent. But it could have caused issues even without the draft...but I didn't do any testing around that flow.

Here's an example of what I was doing in terms of the notification messages that was causing the issue:
```
if (!enabled) {
    Office.context.mailbox.item.notificationMessages.removeAsync(`IsSecured`);
    return;
}

Office.context.mailbox.item.notificationMessages.addAsync(`IsSecured`, {
    type: "informationalMessage",
    message: "This Message is secured",
    icon: "icon1",
    persistent: true
});
```

What I did to fix this was add in a unique key (per inbox message -- using the item id):
```
if (!enabled) {
    Office.context.mailbox.item.notificationMessages.removeAsync(`${mailboxItemId.substr(mailboxItemId.length - 16)}-IsSecured`);
    return;
}

Office.context.mailbox.item.notificationMessages.addAsync(`${mailboxItemId.substr(mailboxItemId.length - 16)}-IsSecured`, {
    type: "informationalMessage",
    message: "This Message is secured",
    icon: "icon1",
    persistent: true
});
```

**Comment by exextoc** [comment]
@cody-lettau Could you please provide us a sample add-in where we could reproduce this issue? You can mail us at admin@M365x010952.onmicrosoft.com

**Comment by cody-lettau** [comment]
@exextoc I will try to find some time here this week to create an example and send it over.

Edit: The yeoman generator isn't working for a compose add-in. Can you send me an example compose add-in (javascript) that I can modify? Otherwise, it may take me a bit longer as I'm pretty swamped working towards a release.

I think we just need to have a toggle that adds/removes the notification message. With it enabled (message added), save the draft with attachments. Then switch the inbox item and come back to the draft.

**Comment by exextoc** [comment]
@cody-lettau We are not able to reproduce the issue with the steps you mentioned.

Please find time to write a simple add-in which shows the issue. 
You can find the instructions here : https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart

A sample can be found here : https://github.com/OfficeDev/Office-Add-in-Commands-Samples/tree/master/Simple

**Comment by cody-lettau** [comment]
We can go ahead and close this as I won't have time to create an example for some time. Thanks for taking a look into it and I apologize that I haven't had time to provide a better example.

**Comment by ricardoleonhart** [comment]
> if (!enabled) {
>     Office.context.mailbox.item.notificationMessages.removeAsync(`${mailboxItemId.substr(mailboxItemId.length - 16)}-IsSecured`);
>     return;
> }```

Hi @cody-lettau , may I know how did you determine that the last 16 characters will be a unique key? I can't find any reference.
