### ISSUE TITLE
Same TaskpaneId for different actions does not work on Office for Mac 16.14.1

### ISSUE THREAD

**Issue by dgrudenic** [OfficeDev/office-js#175]
Use of same TaskpaneId for different actions that share the same pane does not work on Office for Mac 16.14.1 (180613).

Here is a snippet of current Manifest:

                <Control xsi:type="Button" id="Team.OpenCommand">
                  <Label resid="Team.OpenCommand.Label" />
                  <Supertip>
                    <Title resid="Team.OpenCommand.TipTitle" />
                    <Description resid="Team.OpenSupertip.Desc" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Team.Icon.Open.16" />
                    <bt:Image size="32" resid="Team.Icon.Open.32" />
                    <bt:Image size="80" resid="Team.Icon.Open.80" />
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <TaskpaneId>Taskpane1</TaskpaneId>
                    <SourceLocation resid="Team.Open.Url" />
                  </Action>
                </Control>
                <Control xsi:type="Button" id="Team.SaveCommand">
                  <Label resid="Team.SaveCommand.Label" />
                  <Supertip>
                    <Title resid="Team.SaveCommand.TipTitle" />
                    <Description resid="Team.SaveSupertip.Desc" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Team.Icon.Save.16" />
                    <bt:Image size="32" resid="Team.Icon.Save.32" />
                    <bt:Image size="80" resid="Team.Icon.Save.80" />
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <TaskpaneId>Taskpane1</TaskpaneId>            
                    <SourceLocation resid="Team.Save.Url" />
                  </Action>
                </Control>

While on Windows version of Office same manifest will work and load different url in same taskpane  on Mac you need to close taskpane and then click the button to load different url.

Environment

* Platform: Mac
* Host Excel, Word, PowerPoint
* Office version number: 16.14.1
* Operating System: High Sierra 10.13.5

**Comment by codexeon** [comment]
This will be fixed in the August Office update

**Comment by dgrudenic** [comment]
Nice. Much appreciated.

**Comment by ElizabethSamuel-MSFT** [comment]
@Zlatkovsky Can you provide current status on this? Thanks.
