### ISSUE TITLE
Word Add-In Quick Start: Add-in Not Loading in Ribbon

### ISSUE THREAD

**Issue by jambrogne** [OfficeDev/office-js#1750]
I'm trying out the "Build your first Word task pane add-in" tutorial, using the Word 2016 / Yeoman generator method. Here is the tutorial link:
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator

Issue: I can't get the Add-in to display in my Word Ribbon.

Details: At step 2 of the "Try it out" section, I enter the command "npm start", and then a new Word doc opens, and the bottom of the pane indicates that the "Add-ins loaded successfully". At this point, I click "Show Taskpane" in the Ribbon. When I do this, I'm supposed to see the Add-in. But instead, I get the following message:

ADD-IN ERROR
Sorry, we can't load the add-in. Please make sure you have network and/or Internet connectivity. Click "Retry" once you're back online.

I'm unsure what this means since my internet connection seems fine. FYI, this is my first time submitting a GitHub issue. Apologies if it's breaking any conventions.

##My Environment
* Platform: PC
* Host: Word
* Office version number: Microsoft 365, version 2102 (Build 13801.20360)
* Operating System: Windows 10 Home, Build 19041.867

**Comment by ElizabethSamuel-MSFT** [comment]
@jambrogne Thanks for asking about this.

@hjkim-MSFT Can you take a look, or assign to an appropriate person to investigate?

Thanks.

**Comment by jambrogne** [comment]
@ElizabethSamuel-MSFT Hi again - I hope you're all safe and healthy. Any ETA on this?

**Comment by jambrogne** [comment]
@hjkim-MSFT @ElizabethSamuel-MSFT I think I've fixed this issue. I needed to install certificates and then manually run the dev server as described here: https://github.com/OfficeDev/generator-office/issues/470
