### ISSUE TITLE
Feature request: Word Field API

### ISSUE THREAD

**Issue by adomasven** [OfficeDev/office-js#1751]
Since UserVoice is no longer supported I'll move this request here. There has been a long standing request since at least 2016 on UserVoice to add field functions to the Word JS API. I am a developer at Zotero, one of the biggest reference managers, and our citation integration with Word relies on fields. Other reference managers such as Endnote and Mendeley also rely on fields for their current desktop Word integrations. Content Controls are no good for citation integration for two reasons:

1. We need backwards compatibility for our existing customers who have written their documents with Desktop versions of Word over the last 15 years. They cannot move to Word Online (or Word for iOS) with their existing documents without Zotero support and we cannot provide such support without field APIs.
2. Even if we implemented an incompatible version of citing using Content Controls they have undesirable attributes such as standing out from the text and being natively editable by users, something, which users shouldn't (easily) do with field codes reference managers put under their citations.

Quality reference managing and citing is absolutely mandatory for any serious academic writing which is a good enough reason alone to consider adding field APIs although I am sure there are many other use cases that plugin developers have for the feature beyond citing support.

**Comment by ElizabethSamuel-MSFT** [comment]
@adomasven Thanks for recording your request here.

@AbidRahman-MSFT Can you take a look and verify if this is already on the feature backlog?

Thanks.

**Comment by AbidRahman-MSFT** [comment]
Hey @adomasven,

Thank you for the context around the needs for a Fields API. I agree that it is an important feature for citation managers and we do have it prioritized in our backlog accordingly. Unfortunately, we haven't had any new Word-specific investments over the last several years but I'm confident this will change in the next 6 months. We will let you know as soon as we have an update regarding Fields API. 

In the meantime, I would love to have a longer conversation with you and the team at Zotero regarding Office Add-ins and the main blockers and issues you are facing in moving your core features from the existing COM add-ins to an Office Add-in (other than of course the Fields API).

If you are interested, please fill out the following form (and please include your email): [Word Extensibility Survey](https://aka.ms/WordExtensibilitySurvey) and I will reach out to learn more.

Thanks,
Abid

**Comment by lindalu-MSFT** [comment]
If you're still interested in adding this feature, please go to our new [Ideas forum](https://aka.ms/m365dev-suggestions) and click **Submit an Idea**. If there's enough interest (votes), we will follow up with you there and add it to our feature request backlog. Please add link to the suggestion in the comments for tracking. Thanks, lindalu

**Comment by adomasven** [comment]
Voted on an [existing idea](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/adding-field-codes-for-word-using-word-javascript-api/idc-p/2376739#M93). If you've come here looking for the feature, make sure you vote on it there.

**Comment by lindalu-MSFT** [comment]
Thanks for cross posting here @adomasven, it really helps us drive people to the feature request. We don't want to track the same request in two places! We appreciate you taking the time.

**Comment by rsoeldner** [comment]
Any update on this topic?

**Comment by mayagit** [comment]
Hey everyone, we are starting to look into this area. Could you please go ahead and fill in this survey to help us understand and prioritize requirements: https://aka.ms/WordAPI ?
Thanks!

**Comment by follhim** [comment]
HI! Zotero user, requesting attention be placed on this issue!
