### ISSUE TITLE
Outlook Item is undefined when on a certain mailbox

### ISSUE THREAD

**Issue by zaker** [OfficeDev/office-js#1752]
Our add-in works on any other mailbox and in for all in owa. 
But on a certain shared (office365)mailbox for the desktop the items cannot be loaded.
The settings for this is the same as others that

## Expected Behavior

Item values should be readable, like any other item in the other inboxes

## Current Behavior

Item doesn't load,  and initialize method doesn't let it self be overridden

windows.Office.initialize = (e )=> console.log(e);

## Steps to Reproduce, or Live Example

Can only be reproduced in internal environment. 

      window.Office.context.mailbox.addHandlerAsync(
        window.Office.EventType.ItemChanged, (e) => console.log(e.initialData.itemType) // == 0
      );

## Context

Read mails to archive metadata on them

## Your Environment

* PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.13
* Operating System: Win 10
* Browser (if using Office on the web): NA

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] ![image (1)](https://user-images.githubusercontent.com/313043/112624361-d7cad980-8e2d-11eb-9405-3c95291731d3.png)

- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
Could you share a bit more details on what's working and what's not? Does your add-in work on your own mailbox but not on sharedMailboxes? Does the manifest support shared Folders feature - There needs to be a manifest change to enable this. You mention that the item doesn't load - Is it that the Office.context.mailbox.item is undefined? Sharing details of repro steps/video of the repro would be helpful too. Could you also share the full Outlook build version number where you're seeing this issue?

**Comment by zaker** [comment]
It works on both me inbox, and other users inboxes. 
Usually it works on all shared inboxes, but we have encountered one shared inbox that it doesn't work on.  
This shared mailbox does work fine in OWA, but not on desktop.
Office version : 16.0.13.127.21336

The manifest has support shared folders set to true. 

The app loads , so Office.initialize get's triggered. 
The item doesn't seem to load as Office.context.mailbox.item is undefined under office .onReady callback
When we select different items' Office.EventType.ItemChanged is triggered. but we get uncomplete data in event arguments.
e.initialData.itemType == 0, but e.initialData.itemClass == 'IPM.Note' .
 Office.context.mailbox.item remains undefined

We do not suspect this is a office.js issue, but rather a setup for this inbox, but we're really not sure how this inbox is different as the settings are all the same as other inboxes. 

We're looking for insights into what we should try.

**Comment by exextoc** [comment]
For the shared inbox that's not working, could you elaborate on how it was set up? Was it a user that shared the folder with another user? Or was it an admin created folder giving access to specific users in the org?  
Even though add-ins work on sharedMailboxes (known issue) this is not a scenario we officially support and have a backlog work item to address this feature work. We unfortunately cannot share timelines of when this will be enabled. That said, could you share the differences in setup for these sharedMailboxes for the one's that work vs the one that doesn't in terms of admin setup or how the user added these sharedMailboxes to their account?

**Comment by zaker** [comment]
The shared mailbox was set up by an administrator, and then the users where given access. Neither we(Developers, Operations) or them(Administrators) can't find any differences, between this and others that work. We have seen that it was created with two different exchange licenses, but havev since removed the "old" one.  But that did not help the situation. 

Thanks for the information about sharedMailboxes not being fully supported, I'll bring it forward to the team. We'll have to manage the expectations for the users, and see how we'll get around this issue.

**Comment by exextoc** [comment]
The shared Mailbox that's in question, are all users who were given access to it facing this issue or only a specific set of users? Also, could you share the steps on how this sharedMailbox was added by the users facing this issue to their outlook profile?

**Comment by zaker** [comment]
Every user that's using the mailbox has this issue. We're currently in the process of creating a new shared mailbox with the same users and permissions to see if it resolves the issue, or if we have a way to reproduce it.

**Comment by exextoc** [comment]
@zaker - Thanks for following up on the issue. Here are a few articles that may possibly explain why this mailbox is hitting the issue specifically. Could you check if the setup in outlook profiles were done correctly based on how the mailbox was setup. The articles also have steps on resolving known issues with permission sets if setup the wrong way.

https://techcommunity.microsoft.com/t5/outlook-global-customer-service/conflicting-permission-sets-when-working-with-shared-or/ba-p/388842

https://docs.microsoft.com/en-US/outlook/troubleshoot/profiles-and-accounts/issues-that-occur-when-adding-multiple-exchange-accounts

Let us know if this resolves the issue for you.

**Comment by zaker** [comment]
As it turns out, buisness operations has set this email address as hidden for lookup (msExchHideFromAddressLists == TRUE), and this seems to cause the error in outlook desktop. 
The addin on top of office.js still works in OWA though. 

The case for why they want it like that is as follows.
Nobody should send an email directly to this inbox, all items gets transferred over if a user with access categorizes an email with a tag that has some logic to it that copies the email over.
