### ISSUE TITLE
Malformatted hyperlink in Office Online

### ISSUE THREAD

**Issue by dhoelzl** [OfficeDev/office-js#1753]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When opening the attached document in Office Online (Build 16.0.13925.41023) and hovering over the hyperlink (the document contains one single hyperlink), the following URL is displayed (incorrect):

`https://example.com/path" \l "samplehash" \`

Following the link (Ctrl+click) will open the link in it's malformatted representation.

When opening the same document in native Word (Windows, Word 2016 (16.0.5110.1000) MSO (16.0.5134.1000) 64-bit), the following URL is displayed (correct), and (Ctrl+click) will also open it correctly:

`https://example.com/path#samplehash`

Problematic document:
[LinkInvalidSyntax.docx](https://github.com/OfficeDev/office-js/files/6211837/LinkInvalidSyntax.docx)

**Comment by ElizabethSamuel-MSFT** [comment]
@dhoelzl Thanks for raising this issue. However, it seems to be unrelated to Office Add-ins. As such, we're tagging this is external and will close. If that's a misunderstanding, do respond with office-js details so we can reopen and investigate.

@AbidRahman-MSFT Can you see if we can raise issue with Word product team?

Thanks.

**Comment by dhoelzl** [comment]
Hello!

Thank you for looking at this.

I posted this here because I detected the problem while using the hyperlink range API:

```
Word.run(async (context) => {
  const hyperlinkranges = context.document.body.getRange("Content").getHyperlinkRanges();
  hyperlinkranges.load("hyperlink");
  await context.sync();
  for (const hyperlinkrange of hyperlinkranges.items) {
    console.log(hyperlinkrange.hyperlink);
  }
});
```

This delivers the hyperlinks in the malformatted representation when executed in the context of an OfficeJS-Add-In in Office for the web in the problematic document. When running it in a native Office application it seems to work properly.

Are there any further steps for me for this bug report?

Regards,
Dominik

**Comment by ElizabethSamuel-MSFT** [comment]
@dhoelzl Thanks for providing this additional information.

@qinliuMSFT Can you take a look?

Thanks.

**Comment by qinliuMSFT** [comment]
Hi @dhoelzl , thanks for reporting this issue. 
From the document.xml, the hyperlink is saved the same as what displayed in web as following:
<w:instrText xml:space="preserve"> HYPERLINK "https://example.com/path" \l "samplehash" \h </w:instrText> 
I'm not sure why Word desktop show it as https://example.com/path#samplehash. 

Could I know how you create this hyperlink? Do you use Hyperlink range API to set or using native UI?

**Comment by dhoelzl** [comment]
Thank you!

It was inserted into the document via the `Range.insertHtml` API in a taskpane in Word for Mac (Version 16.45 (21011103)).

Inserted HTML:

`<html><head></head><body><a href='https://example.com/path#samplehash' title='Link'>Link</a></body></html>`

Even if the insertion may have caused the problem, there may exist documents with that formatting which need to be read as expected (as Word desktop does).

**Comment by qinliuMSFT** [comment]
Hi @dhoelzl ，I added hyperlink by using the following snippet on Mac(Version 16.47(21031401)), but could not repro this issue. 
```js
  await Word.run(async (context) => {
      const str = "<html><head></head><body><a href='https://example.com/path#samplehash' title='Link'>Link</a></body></html>";
   
      var mySelection = context.document.getSelection();
      mySelection.insertHtml(str, "Before");
   
      await context.sync();
      
      const hyperlinkranges = context.document.body.getRange("Content").getHyperlinkRanges();
      hyperlinkranges.load("hyperlink");
      await context.sync();
      for (const hyperlinkrange of hyperlinkranges.items) {
        console.log(hyperlinkrange.hyperlink);
      }
    });
 ```
Could you please help double check? If possible, could you please give us your sample snippet or repro video?

**Comment by dhoelzl** [comment]
You need to insert the link in Word for Mac, save the document, re-open it in Office Online and then read the link separately.
In Word for Mac itself the link can always be read correctly.
I am looking forward to create a repro viedo.

**Comment by dhoelzl** [comment]
Hello!

I could narrow the cause of the problem to be somewhere in the link text itself. Previously I stripped the text for demo purposes, but unfortunately with that it did not cause the problem.

When the following script is used in Word for Mac, the link is inserted malformatted.
When changing the link text from "Link1 Sampl" ("typos" are intended) to "Link", the problem does not occur any more.

Repro video:



https://user-images.githubusercontent.com/25737508/113402976-33edaa80-93a6-11eb-974a-b2a503c6a9c9.mp4



```
<!DOCTYPE html>
<html>
<body>
<script type='text/javascript'>
const script = document.createElement("script");
script.src = "https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js";
script.onload = () => {
  Office.onReady(async () => {
      await Word.run(async (context) => {
      const str = "<html><head></head><body><a href='https://example.com#samplehash' title='Link'>Link1 Sampl</a></body></html>";
   
      var mySelection = context.document.getSelection();
      mySelection = mySelection.insertHtml(str,  Word.InsertLocation.replace);
      mySelection.select(Word.SelectionMode.end);
   
      await context.sync();
      
      const hyperlinkranges = context.document.body.getRange("Content").getHyperlinkRanges();
      hyperlinkranges.load("hyperlink");
      await context.sync();
      for (const hyperlinkrange of hyperlinkranges.items) {
        console.log(hyperlinkrange.hyperlink);
      }
    });
  });
};
document.head.appendChild(script);
</script>
</body>
</html>
```

**Comment by qinliuMSFT** [comment]
Thanks for the confirmation. 
@AbidRahman-MSFT , could you please find someone to look at this issue? Customer use Range.insertHtml to insert a hyperlink, but the link is inserted and saved malformatted when the snippet running in Word on Mac, which caused the link is malformatted representation on web.
