### ISSUE TITLE
Excel.RangeFormat.autofitColumns doesn't account for custom number format coupled with bold font

### ISSUE THREAD

**Issue by sshukurov** [OfficeDev/office-js#1754]
Custom number format we use in our project for financial amounts is: `_(* #,##0.00_);_(* (#,##0.00);_(* ""-""??_);_(@_)`

When we assign this number format to a cell, set the font to bold, and then invoke `autofitColumns`, we see the following picture:
![image](https://user-images.githubusercontent.com/36232686/112640876-9a813e80-8e63-11eb-9214-b4318ea45e4a.png)

## Minimal repro
https://github.com/sshukurov/autofitColumnsIssue

The issue reproduces in Excel on the web, doesn't reproduce in Excel desktop.

## Environment
* Platform: Office on the web
* Host: Excel
* Office version number: Build 16.0.13921.31876
* Operating System: Windows 10 Pro 64-bit 20H2 OS build 19042.867
* Browser: Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by ElizabethSamuel-MSFT** [comment]
@sshukurov Thanks for raising this issue.

@lumine2008 Can you take a look, or assign to an appropriate person to investigate?

Thanks.

**Comment by lumine2008** [comment]
Thanks, Bug 4987934 is created to track this issue.

**Comment by donlvMSFT** [comment]
This issue already been fixed based on bug status, please help verify.
I'd like to close this thread, thanks for discussion!
