### ISSUE TITLE
insertText: Weird behavior when inserting vertical tabulation ("\v")

### ISSUE THREAD

**Issue by dhoelzl** [OfficeDev/office-js#1755]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Inserting text into a Word document via `Range.insertText` does not work properly when inserting vertical tabulator characters ("Shift-Enter" line breaks).

## Expected Behavior
insertText should insert all characters as expected and should not generate a second weird undo operation.

## Current Behavior

Enable displaying line break characters in the document to see the problems. The output here is formatted as displayed in Word with this option enabled.

### Test case 1:

```
await Word.run(async (context) => {
   var sourceRange = context.document.getSelection();
   sourceRange.insertText("Test\vLine\vBreak", 'Replace');
   await context.sync();
});
```

This inserts

`Test♂Line♂Break`

into the document (note the wrong characters). When pressing "Ctrl+Z" the first time, the text changes to the expected output

```
Test↵
Line↵
Break 
```

Pressing it a second time will revert the insertion.

### Test case 2:

```
await Word.run(async (context) => {
   var sourceRange = context.document.getSelection();
   sourceRange.insertText("Test\vLine\vBreak\nTest", 'Replace');
   await context.sync();
});
```
This inserts

```
Test♂Line♂Break¶

Test
```
into the document (note the wrong characters). When pressing "Ctrl+Z" the first time, the text changes to the expected output

```
Test↵
Line↵
Break¶

Test
```

Pressing it a second time will revert the insertion.

### Test case 3:

```
await Word.run(async (context) => {
   var sourceRange = context.document.getSelection();
   sourceRange.insertText("Test\nTest\vLine\vBreak\nTest", 'Replace');
   await context.sync();
});
```

this inserts

```
Test¶

Test\vLine\vBreak¶

Test
```

into the document (note the double-escaped characters). When pressing "Ctrl+Z" the first time, nothing happens. The expected output (↵ instead of \v) is not revealed. Pressing it a second time reverts the insertion.

### Test case 4:

```
await Word.run(async (context) => {
   var sourceRange = context.document.getSelection();
   sourceRange.insertText("Test\nLine\nBreak", 'Replace');
   await context.sync();
});
```

this inserts

```
Test¶

Line¶

Break¶
```

as expected into the document. Pressing "Ctrl+Z" does nothing the first time, and will undo the operation as expected the second time.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.13926.41000
* Operating System: Windows
* Browser (if using Office on the web): Google Chrome 89.0.4389.82 (Official build) (64-Bit)

**Comment by ElizabethSamuel-MSFT** [comment]
@dhoelzl Thanks for letting us know about this and providing details.

@hjkim-MSFT Can you take a look, or assign to an appropriate person to investigate?

Thanks.

**Comment by dhoelzl** [comment]
I have re-tested this on office.com (Version 16.0.17514.41008), looks better now, but test case 3 still does not work, it still behaves like before.

Thank you and regards,
Dominik

**Comment by gergzk** [comment]
@dhoelzl - thanks for retesting. Can you open a new issue with the still-failing case in it? We're working through a new process to get better issue routing to the dev teams.

**Comment by dhoelzl** [comment]
Follow-up issue was created: https://github.com/OfficeDev/office-js/issues/4275
