### ISSUE TITLE
Outlook Add-In built using Angular showing blank taskpane on Windows Outlook App pre 1903 build

### ISSUE THREAD

**Issue by sarthak625** [OfficeDev/office-js#1757]
We are developing an Outlook add-in using angular. The add-in works on IE11, Edge, Chrome and Safari, but on Windows Outlook desktop app versions (< 1903) which use IE11, it shows an empty taskpane. 
Following workarounds I have tried and still the issue persists, so would like to know if it is a compatibility issue. Attaching the code below this:

1. Ensured that the document mode is set to edge using the meta tag as per this link: https://stackoverflow.com/questions/52295729/office-outlook-web-addin-does-not-work-on-office-client-2016
<meta http-equiv="X-UA-Compatible" content="IE=edge"/> 

2. Ensured that all unsupported features by IE are included in the pollyfills.
Here is my pollyfills file:

`/***************************************************************************************************
 * BROWSER POLYFILLS
 */

/** IE10 and IE11 requires the following for NgClass support on SVG elements */
import 'classlist.js'; // Run `npm install --save classlist.js`.
import 'intersection-observer';
import 'core-js/es6/symbol';
import 'core-js/es6/object';
import 'core-js/es6/function';
import 'core-js/es6/parse-int';
import 'core-js/es6/parse-float';
import 'core-js/es6/number';
import 'core-js/es6/math';
import 'core-js/es6/string';
import 'core-js/es6/date';
import 'core-js/es6/array';
import 'core-js/es6/regexp';
import 'core-js/es6/map';
import 'core-js/es6/weak-map';
import 'core-js/es6/set';
import 'core-js/es7/array';

import 'core-js/es6/reflect';
import 'core-js/es7/reflect'`

Please help with the same.

**Comment by sarthak625** [comment]
Hi,

Some more information that would help with debugging.

We are using dynamic loading in Angular. So office.js is loaded only on the route where it is required. We have enabled this through the following code:

> OUTLOOK_URL = 'https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js';
> loadScript(url): HTMLScriptElement {​​​​​​​
>    const node = document.createElement('script');
>    node.src = url;
>    node.type = 'text/javascript';
>    node.async = false;
>    node.charset = 'utf-8';
>    document.getElementsByTagName('head')[0].appendChild(node);
>    return node;
> }​​​​​​​


and initialization is done this way

> ngOnInit(): void {​​​​​​​
>    this.loadScript(this.OUTLOOK_URL).onload = () => {​​​​​​​
>      Office.onReady().then(() => {​​​​​​​
>            this.onOfficeReady();  // Further logic after office.js loads
>      }​​​​​​​);
>    }​​​​​​​;
>  }​​​​​​​


Here is a link to a sample project which does the same: https://github.com/sarthak625/outlook-sample


I discovered that on removing this logic allows the add-in to load on the Outlook App with build target set to es5. It doesn't resolves any errors however so the experience is still poor. However, we cant allow the office js script to be loaded on the root level and the build target be es5 and instead office.js has to be dynamically loaded when the add-in route is called. 

Here is a link to sideload this sample project as an add-in: https://jiomeetstage.jiomeet.com/outlookHelloManifest/manifest.xml

**Comment by sarthak625** [comment]
Hi,

Some more information i collected.

On putting the Office.js url on the root html page of angular like this,
`<script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js" type="text/javascript">`

The add-in loads up this way, but the Office.js seems to change the default URL strategy of angular from PathLocationStrategy to HashLocationStrategy. We confirmed this by checking the routes and a hash parameter is added infront of the url.
I enabled HashLocationStrategy in app.module.ts as suggested [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-ins-with-angular2)

**Impact**:
The HashLocationStrategy affects other aspects of our application as it changes routes to start with Hash which causes some APIs and other components to fail.

**Comment by sarthak625** [comment]
Hi,

As suggested i tried changing the code to es5 syntax like this:

```
ngOnInit() {

        var thisObj = this;

        this.loadScript(this.OUTLOOK_URL).onload = function(){

            thisObj.initializeOutlook();

        };

    }

initializeOutlook() {

      var thisObj = this;

      Office.onReady().then(function(){

          thisObj.onOfficeReady();

      });
}

```
This did not change anything however. Angular already does differential loading and transpiles the es6 code to es5 code for older browsers.

**Comment by sarthak625** [comment]
Hi,

As suggested we have tried the following fixes:

1. Remove async from loadScript function
2. Disabled differential loading and changed the transpiler to es5 to avoid any arrow function issues.
3. Added a logger div on the root element to get the logs on the main window itself.

I have also added the manifest.xml in the sample project which can be found [here](https://github.com/sarthak625/outlook-sample)

**Comment by sarthak625** [comment]
The issue seems to be the dynamic loading of office.js file. It works fine in browsers but in the Outlook App (IE versions) it causes issues because the Outlook App requires additional JS files to load the add-in. Furthermore it seems that those js files are loaded on the basis of the script tag with office.js in the head section. We will try static office.js loading and see if that works.

**Comment by shaofengzhu** [comment]
Would you please add
<script type="text/javascript">window.history.replaceState=null;window.history.pushState=null;</script>
to your index.html page?

window.history won't work in richclients using IE11 browser control. Angular framework will try to use window.history API when the API is defined, but those API will not work. Please add the above code in the index page to disable the history API. We tested your addin and it works after we added the above code to the index.html.
