### ISSUE TITLE
Outlook Office.context.auth.getAccessTokenAsync And OfficeRuntime.auth.getAccessToken Not Work for Intune Device Verify

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#1758]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

when Enable Intune Device Verify on Azure By Create a new Conditional Access Policy.
The Api: Outlook Office.context.auth.getAccessTokenAsync And OfficeRuntime.auth.getAccessToken Not Work.
My Azure new Conditional Access Policy such like below:
Please Notice:
Zoom(maiken test) is my add-in App which is deployed on Office Admin Center Add-ins.
Zoom-add-in-auto-sso is my getAccessToken's App which is create by follow this document. https://docs.microsoft.com/en-us/office/dev/add-ins/develop/register-sso-add-in-aad-v2.
Two App Selected:
![image](https://user-images.githubusercontent.com/1878089/112722230-359d1580-8f43-11eb-8ce0-fd9afa592b93.png)
Grant Access Controls:
![image](https://user-images.githubusercontent.com/1878089/112722245-46e62200-8f43-11eb-87eb-9695c3e94fe1.png)

the web return error code is:
13006: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins#13006
Windows Outlook error code is:
13005: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins#13005

But i think this error code and solution is useless, cause i solved these error in the last weeks, but the solution is not work for this problem. and i can confirm that this error is caused by the intune device verify.

**Comment by hello-chenchen** [comment]
hi @mattgeim @exextoc @lindalu-MSFT  is there anything can update?

**Comment by exextoc** [comment]
@hello-chenchen Could you please provide us a sample add-in so that we could reproduce this issue on our end. You can mail us at admin@M365x010952.onmicrosoft.com.

**Comment by mattgeim** [comment]
@hello-chenchen a couple of questions:

- are you passing allowConsentPrompt:true as part of the options for getAccessToken?
- Can you share a fiddler trace with us from when this isn't working?

**Comment by hello-chenchen** [comment]
hi @mattgeim thanks for update. My test code is:
```
Office.context.auth.getAccessTokenAsync({allowConsentPrompt: true}, function(result) {     if (result.status === "succeeded") {         console.log(result.value)     } else {         console.log("Error obtaining token", result.error);     } });
```
test platform is new edge browser.
below is the http trace.
[outlook.office.com.har.zip](https://github.com/OfficeDev/office-js/files/6302104/outlook.office.com.har.zip)

**Comment by hello-chenchen** [comment]
in win 10 outlook client:(which is based on webview2)
after execute this code:
```
Office.context.auth.getAccessTokenAsync({allowConsentPrompt: true}, function(result) {     if (result.status === "succeeded") {         console.log(result.value)     } else {         console.log("Error obtaining token", result.error);     } });
```
it shows this popup error dialog:
![image](https://user-images.githubusercontent.com/1878089/114519494-0bea2b00-9c73-11eb-8b94-16a3813ace91.png)
My device has enrolled.
![image](https://user-images.githubusercontent.com/1878089/114519567-1e646480-9c73-11eb-8dd3-517e435c0bb8.png)
![image](https://user-images.githubusercontent.com/1878089/114519547-199fb080-9c73-11eb-8f4c-6a5538a0f2a9.png)

**Comment by hello-chenchen** [comment]
sorry i can't catch fiddler trace for outlook client. when i open fiddler, the test code can't popup dialog , and throw error message:
```
code: 13007
message: "An unexpected error occurred on the server."
name: "Error occurred in the authentication provider."
```
i think maybe it was the intune certificate verify. fiddler error: the server requests a client certificate please save a client certificate using the filename
