### ISSUE TITLE
Excel Ribbon defined in sideloaded manifest doesn't appear in Excel for iPad

### ISSUE THREAD

**Issue by botalla** [OfficeDev/office-js#176]
## Expected Behavior
We have created an addin which add a new Ribbon in Excel with 2 groups, 3 buttons and 3 associated JS functions which interact with the spreadsheet.
It works well on Excel Online and Excel Desktop.
I'm trying to get the same on Excel iPad

## Current Behavior
I'm using the sideloading method (https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac): the sideload work (I see my add-in) but I don't see my new Ribbon

## Steps to Reproduce, or Live Example
1. sideload the manifest (using this https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac): => here is my manifest : https://drive.google.com/file/d/11OBaXVaCTMoudzVorXpl6_FQLvK5N2uD/view?usp=sharing
2. start Excel

## Context
See above

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: iOS
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: latest version from the applestore (on the 26th of June 2018)
* Operating System: iOS 11.3
* Browser (if using Office Online): N/A

## Useful logs
 N/A

**Comment by botalla** [comment]
here is my manifest

**Comment by botalla** [comment]
Here is my manifest (renamed with a .txt extension for attach purpose)
[rimes2.xml.txt](https://github.com/OfficeDev/office-js/files/2136680/rimes2.xml.txt)

**Comment by JuaneloJuanelo** [comment]
yes, add-in commands are not yet supported in iOS, that's why you cannot see it.  please upvote this request in our uservoice channel.
https://officespdev.uservoice.com/
