### ISSUE TITLE
ContentControl.insertHTML gets progressively slower

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#1761]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior

The ContentControl Operations and Word Online don't slow down.

## Current Behavior

In Word Online editing a previously loaded ContentControl via the insertHTML Method, leads to really bad loading times which get progressively slower depending on the number of ContentControls and insertions performed. It can take up to several minutes to perform context.sync() for the insertHTML-Method. 
This Problem only exists in Word Online.  

## Steps to Reproduce, or Live Example

I've created a ScriptLab Sample to recreate the issue. 
After pressing the load button, press the InsertHTML Button after it appears. Each time you press it the time it takes to insert the HTML gets worse.
* Link to live example: https://gist.github.com/tillkaemmerer/6064d759dd1dbfd310378f9097d8fcdb

## Context

I have a prebuilt document with several ContentControls which can be filled in via a Taskpane Add In. This Add In should support ralatively live updates into the document while the user is typing.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.13924.41001
* Operating System: Win10 Pro x64
* Browser (if using Office on the web): Edge, Firefox

## Useful logs

Unfortunately there is no Console-Errors.

**Comment by Rick-Kirkham** [comment]
@AbidRahman-MSFT  Ruoying is on leave. Can you take a look at this or find someone who can help? (I can reproduce this. The slow down happens for me about the 10th time I press the button. If I press 1 or 2 more times, the browser becomes unresponsive. Also, if I save the doc and reopen it, the browser locks up if I press the button even one time.)

**Comment by RuoyingLiang** [comment]
Created bug 4990481 to track this issue. Will look into it.
