### ISSUE TITLE
insertText: inconsistent formatting behavior

### ISSUE THREAD

**Issue by dhoelzl** [OfficeDev/office-js#1762]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

insertText with "Replace" produces incorrect / unexpected formatting when replacing a hyperlink range (or probably other ranges) with text when executed in Office for the Web. It looks like the formatting of the preceding content spreads into the replaced text and some content beyond, and if there is no preceding text in a line where the link starts, the formatting of the link is used. additionally, if two different links are directly side by side without any text between, and only the second link will be replaced, the first link will expand over the replaced text after the replacement.

## Expected Behavior
insertText with "Replace" should always use the formatting of the hyperlink range (probably the formatting of the beginning of it, or at least the default formatting in the document, I don't know whats technically really correct here) and it should not destroy the formatting of following areas in the document.

## Current Behavior
See description above.

## Steps to Reproduce, or Live Example

* Open the following document in either Office for the Web or Word for macOS.
[InsertTextReplaceLinkFormatting.docx](https://github.com/OfficeDev/office-js/files/6222497/InsertTextReplaceLinkFormatting.docx)

* Execute the following script in the context of an OfficeJS task pane. The script will log all hyperlinks in the document to console and replace all with the text "Replaced".

```
Word.run(async (context) => {
  const hyperlinkranges = context.document.body.getRange("Content").getHyperlinkRanges();
  hyperlinkranges.load("hyperlink");
  await context.sync();
  for (const hyperlinkrange of hyperlinkranges.items) {
    console.log(hyperlinkrange.hyperlink);
    hyperlinkrange.insertText("Replaced", "Replace");
  }
  await context.sync();
});
```

In Office for the Web unexpectedly the whole first line turns red.

**Before**: 
<img width="165" alt="WebBefore" src="https://user-images.githubusercontent.com/25737508/112853899-9ba5ac00-90ad-11eb-836a-de95d948c1d6.PNG">

**After**: 
<img width="144" alt="WebAfter" src="https://user-images.githubusercontent.com/25737508/112853917-9ea09c80-90ad-11eb-8eea-bacbf24863dd.PNG">

In Word on macOS the replaced text turns black, but not italic and purple.

**Before**: 
<img width="181" alt="macOSBefore" src="https://user-images.githubusercontent.com/25737508/112853934-a2342380-90ad-11eb-84d0-da2fa56c0755.PNG">

**Ater**: 
<img width="162" alt="macOSAfter" src="https://user-images.githubusercontent.com/25737508/112853951-a6f8d780-90ad-11eb-8358-d50409fb85b7.PNG">

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.13929.41000 (), session id: a0b725c4-218a-4e26-a809-68e231839b80
* Operating System: macOS 11.0.1 (native Word), Windows 10 (Browser)
* Browser (if using Office on the web): Google Chrome Version 89.0.4389.82 (Official build) (64-Bit)

**Comment by Rick-Kirkham** [comment]
@AbidRahman-MSFT Ruoying is on leave. Can you take a look at this or find someone who can help?

**Comment by RuoyingLiang** [comment]
Thanks for reporting the issue. Opened bug 5008299 to track internally.

**Comment by dhoelzl** [comment]
I have re-tested this on office.com (Version 16.0.17514.41008) and it looks better now, but it still behaves different than on macOS, now the first replaced text is red and the second purple and italic instead of black without any other formatting as I would expect it.

![image](https://github.com/OfficeDev/office-js/assets/25737508/742435e0-b518-4683-a738-2b1731c0f66d)

Thank you and regards,
Dominik

**Comment by gergzk** [comment]
@dhoelzl - thanks for retesting. Can you open a new issue scoped to the current behavior/platform? We're working through a new process to get better issue routing to the dev teams.
