### ISSUE TITLE
Office.context.mailbox.item.attachments contentType returns unexpected values

### ISSUE THREAD

**Issue by alexgomez97** [OfficeDev/office-js#1763]
## Expected Behavior

When using the Office JS Mailbox API I expect the returned contentType for Attachments in the AttachmentDetails object to use the standard IANA Mime Types

## Current Behavior

The contentType is not standardized. When I get the attachmentDetails on an email with various attachments in Outlook Desktop (using Mailbox API 1.9) I get contentTypes such as application/x-pdf for pdf and application/octect-stream for csv files

## Steps to Reproduce, or Live Example

Get the attachmentDetails (Office.context.mailbox.item.attachments) on an email with different types of attachments, specifically csv files return the wrong contentType consistently, including Office on the web and Office Desktop

## Context

We would like to use the contentType of the attachment when sending the attachment to our platform. When the MIME Type is unexpected, then the file is saved as with a non-standard mime type resulting in the file not appearing as expected.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop (Version 2102 Build 13801.20360) , Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office 365 (16.0.13801.20288)
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome

## Useful logs

- [ ] Console errors
- [ ] Screenshots
![image](https://user-images.githubusercontent.com/25066493/112877714-f2928d80-907b-11eb-8d30-036adccbfbeb.png)

**Comment by exextoc** [comment]
The contentType value is a direct lookup of the suffix for the name of the attachment. For example, in your screenshot it would look up ".csv" and always return "application/octet-stream". This mapping is not actively maintained and contentType might become outdated. If you have a requirement to have specific types, it would be better for you to grab the the suffix of the name and have your own processing on it.

**Comment by alexgomez97** [comment]
Thank you! That’s what we will do.
