### ISSUE TITLE
Bug: word addin (Edgium) single qoutes are not escaped in context.GetDocUrl function

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/office-js#1764]
single  quotes are not escaped in word addin, when new chromium based edge rendering engine is used
It works fine in old edge engine

## Expected Behavior
generated code should look like this
```js
context.GetDocUrl = function () { return 'https://figg.sharepoint.com/sites/AbdulKareemTestTeam/Shared Documents/General/Meetings/2021-03-28 - Channel meeting sync test/a\'b.docx'; };
```

## Current Behavior

Generated code looks like this
```js
context.GetDocUrl = function () { return 'https://figg.sharepoint.com/sites/AbdulKareemTestTeam/Shared Documents/General/Meetings/2021-03-28 - Channel meeting sync test/a'b.docx'; };
```
single quotes should be escaped properly

* Additional details:
  1. Create a word document in sharepoint , where name of document contains single qoute
  2. Open that document in window 10 word application
  3. Try to open any office.js addin

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2102 build 13801.20360
* Operating System:  Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎01-‎11-‎2020
OS build	19042.867
Serial number	PF26MYEJ
Experience	Windows Feature Experience Pack 120.2212.551.0

## Useful logs

- [ X] Console errors
   ```
   Uncaught SyntaxError: Unexpected identifier
   ```
- [ X] Test file (if only happens on a particular 
[a'b.docx](https://github.com/OfficeDev/office-js/files/6226999/a.b.docx)

**Comment by Rick-Kirkham** [comment]
@croicu Please take a look.

**Comment by Dengshan2018** [comment]
It seems the regression.

**Comment by pbl2108** [comment]
Hi @Rick-Kirkham and @croicu,

We are experiencing the same problem in Excel. Can you please provide an update of when do you expect to fix this? We have real clients having issues with this.

It is a frustrating issue. 

Best,
Petre

**Comment by cidev5** [comment]
I understand this is resolved in the beta channel. Is that the case? When can we expect this fix to be released more broadly?

We are currently instructing users to uninstall the WebView2 runtime.

Not ideal to say the least.

**Comment by Dengshan2018** [comment]
The fix will be in monthly channel very soon.
