### ISSUE TITLE
The add-in is failing to load while inserting - Meeting information in Compose Mode

### ISSUE THREAD

**Issue by kanaksony** [OfficeDev/office-js#1765]
The manifest includes the MessageComposeCommandSurface extension point in the VersionOverrides node but the add-in does not function in compose mode of an email. 

## Expected Behavior
The add-in should insert the meeting information in Compose Mode in Mailbox.

## Current Behavior
The add-in keeps loading and fails to insert meeting information in Compose Mode in Mailbox. 

## Steps to Reproduce, or Live Example

1. Launch the add-in
2. Configure settings
3. Attempt to input meeting info
4. Notice the issue
5. Video attached for reference: compose.mp4

* Link to live example (Add-in Manifest link to test the bug) :  https://mop.infocus.net:3000/infocus-conx-outlook-addin.xml

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop / Office on the web 
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Any
* Operating System: Windows / Mac
* Browser (if using Office on the web): Google Chrome

## Useful logs

- [ ] Console errors
- [ ] Screenshots
![Capture](https://user-images.githubusercontent.com/6097596/113018988-bf94ea80-919e-11eb-93c0-9e3fb4f9240c.PNG)

- [ ] Video attached 
https://user-images.githubusercontent.com/6097596/113018556-4dbca100-919e-11eb-8d02-e3cea9b878fe.mp4

**Comment by exextoc** [comment]
Can you provide more clarification on which specific platforms are failing? Is it Outlook on Win32 Desktop, Mac Desktop, Outlook on the web, or all of them?

**Comment by kanaksony** [comment]
It is Outlook on Win32 Desktop, Mac Desktop and Outlook on the web.

**Comment by exextoc** [comment]
Could you share the codesnippet that backs the schedule meeting button on your addin. We're interested in looking at the APIs you're calling into when the button gets clicked? What is the expected behavior for when the button works - Is the body of the message updated? Also, can you make sure you're calling event.completed at the end of the function.

**Comment by neso613** [comment]
> Could you share the codesnippet that backs the schedule meeting button on your addin. We're interested in looking at the APIs you're calling into when the button gets clicked? What is the expected behavior for when the button works - Is the body of the message updated? Also, can you make sure you're calling event.completed at the end of the function.

Hi @exextoc ,I am working with @kanaksony on this same issue. 
Code snippet :
`function ScheduleMeeting(event, settings) {
  var start = new Date();
  var end = new Date();
  end.setHours(start.getHours() + 1);
  Office.context.mailbox.displayNewAppointmentForm(
      {
        start: start,
        end: end,
        location: 'location',
        subject: 'SUBJECT',
        body: 'meetingInviteText'
      });
  event.completed();
}`

**Comment by neso613** [comment]
> > Could you share the codesnippet that backs the schedule meeting button on your addin. We're interested in looking at the APIs you're calling into when the button gets clicked? What is the expected behavior for when the button works - Is the body of the message updated? Also, can you make sure you're calling event.completed at the end of the function.
> 
> Hi @exextoc ,I am working with @kanaksony on this same issue.
> Code snippet :
> `function ScheduleMeeting(event, settings) { var start = new Date(); var end = new Date(); end.setHours(start.getHours() + 1); Office.context.mailbox.displayNewAppointmentForm( { start: start, end: end, location: 'location', subject: 'SUBJECT', body: 'meetingInviteText' }); event.completed(); }`

**Comment by exextoc** [comment]
Office.context.mailbox.displayNewAppointmentForm is only supported in Read mode and not Compose mode. See documentation [here](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-1.5&preserve-view=true#displayNewAppointmentForm_parameters_).
Here are some alternative APIs that could potentially help with your use case:
Setting the start and end: [setAsync(dateTime, options, callback)](https://docs.microsoft.com/en-us/javascript/api/outlook/office.time?view=outlook-js-preview) 
Setting the location: [setAsync(location, options, callback)](https://docs.microsoft.com/en-us/javascript/api/outlook/office.location?view=outlook-js-preview#setAsync_location__options__callback_)
Setting the [Subject](https://docs.microsoft.com/en-us/javascript/api/outlook/office.appointmentcompose?view=outlook-js-preview#subject)
Setting the [Body](https://docs.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-preview#setAsync_data__options__callback_)

**Comment by neso613** [comment]
> Office.context.mailbox.displayNewAppointmentForm is only supported in Read mode and not Compose mode. See documentation [here](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-1.5&preserve-view=true#displayNewAppointmentForm_parameters_).
> Here are some alternative APIs that could potentially help with your use case:
> Setting the start and end: [setAsync(dateTime, options, callback)](https://docs.microsoft.com/en-us/javascript/api/outlook/office.time?view=outlook-js-preview)
> Setting the location: [setAsync(location, options, callback)](https://docs.microsoft.com/en-us/javascript/api/outlook/office.location?view=outlook-js-preview#setAsync_location__options__callback_)
> Setting the [Subject](https://docs.microsoft.com/en-us/javascript/api/outlook/office.appointmentcompose?view=outlook-js-preview#subject)
> Setting the [Body](https://docs.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-preview#setAsync_data__options__callback_)

previously, we was working with Read mode but we got validation fail there also.

**Comment by neso613** [comment]
also, addin should create new appointment on custom button click and values should be set dynamically. Thats why this above function used

**Comment by exextoc** [comment]
Can you please mention the validation errors that you are facing while you are executing "displayNewAppointmentForm" function?

**Comment by neso613** [comment]
> Can you please mention the validation errors that you are facing while you are executing "displayNewAppointmentForm" function?
I have submitted this add-in with ReadMode and it was validated bdefore. But this time, with same manifest.xml, I am getting this validation fail message.

![image_2020_12_11T12_18_57_673Z-1](https://user-images.githubusercontent.com/31642462/114528707-dfc8ad00-9c66-11eb-88cb-afc1efcd191b.png)

**Comment by exextoc** [comment]
Could you clarify question here, is the issue:
1 The add-in or an API is not behaving as you expected and you can repro the issue in your environment. You are looking to understand addin or API behavior.
Or
2 Your addin is behaving as you expect, and you would like clarification on the cert results

For 1 - please provide information on the scenario, API you are calling, the behavior you expect and what you are seeing. I have tried your code snippet and the appointment form displays when used in read mode. It is possible that we are not getting full picture here.

For 2 - Please raise a ticket at https://aka.ms/marketplacepublishersupport ; as is advised in there rejection report. We can’t talk on a public forum about individual offer results.
