### ISSUE TITLE
Addin is not distributed

### ISSUE THREAD

**Issue by ITIVITYAG** [OfficeDev/office-js#1766]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
We want to roll out addins for Office products, but they are not distributed to all users.
For all new accounts they are distributed correctly and for old users they are not distributed for most of them.

## Current Behavior
The add-ins are not displayed in Word or other Office programs.

## Steps to Reproduce, or Live Example
1. add-ins are added in the portal
2. a group is assigned to the add-ins
3. for some users the add-in is displayed in Office for others not.

## Context
The users cannot use the addins. 
However, the problem exists only for some addins, for example wikipedia works for all users

## Your Environment
- Windows Server 2012 R2
- Chrome
- Office 365 Apps

## Useful logs

![image](https://user-images.githubusercontent.com/81641848/113027255-28259c80-918a-11eb-8f9a-83cff39cdfbf.png)

**Comment by Rick-Kirkham** [comment]
Bhavin Kapoor, Can you please take a look at this problem?

**Comment by bhavinkap** [comment]
Translating the message from the screen shot: "There are currently no add-ins available"

Hi @ITIVITYAG, 

Can you please help to share some more details:

1> You have mentioned that Wikipedia works for all users, however from the screen shot shared we do not see the Wikipedia Add-in installed for this user. 

So does this user never receive any Add-ins or is it a problem with a specific Add-in Only ? And what add-in are you trying to install

2> It is mentioned that the Add-in is assigned to a Group. 
Centralized Deployment Only Supports users in top-level groups or groups without parent groups, but not users in nested groups or groups that have parent groups. 

Can you please check if the affected user is a part of nested group as that may explain the reported behavior.
More details in the below developer documentation:
https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide#user-and-group-assignments

**Comment by ITIVITYAG** [comment]
Hi Bhavinkap

**1> You have mentioned that Wikipedia works for all users, however from the screen shot shared we do not see the Wikipedia Add-in installed for this user.**
This is because I have deleted the add-in again

**2> It is mentioned that the Add-in is assigned to a Group.
Centralized Deployment Only Supports users in top-level groups or groups without parent groups, but not users in nested groups or groups that have parent groups**
I am aware of that, the users are in the group which is directly assigned to the add-in. For newly created users this also works without problems


next I will run the powershellscript and check if I see any errors there.

**Comment by bhavinkap** [comment]
Thanks for these details. Please keep us posted on the results. 

Query - For the impacted user was the issue observed on:
1> Word Desktop App Only
2> Web App (Online Word) Only
3> Across both the Word Desktop App and Web App

Also, If you could share the details of the Add-in that you are trying to install then it would be useful for us to try and repro.
