### ISSUE TITLE
ContentController missing inputs or not saving after refreshing page

### ISSUE THREAD

**Issue by leonliang-apprentice** [OfficeDev/office-js#1769]
Inputs in the ContentController are not being saved or not returned fully after refreshing document.

## Expected Behavior
I have a console log on when Word loads:

```
    Office.onReady()
      .then(() => {
        console.log('document loaded');
        Word.run(async (context) => {
          context.document.contentControls.load();
          await context.sync().catch(err => {
            console.log(err)
          })
          console.log(context.document.contentControls.items.map(cc => console.log(cc.id, cc.text)))
        })
      });
```

Which is returning the following when i'm in the same session aka just reloading the plugin but not the page.
![image](https://user-images.githubusercontent.com/76965896/113227513-b4e26000-9247-11eb-82bc-9390d7fe04e3.png)

## Current Behavior
After reloading the page, we are seeing no inputs under contentControls
![image](https://user-images.githubusercontent.com/76965896/113227829-6d100880-9248-11eb-91bd-665d4daa0680.png)

## Steps to Reproduce, or Live Example
This is how we are trying to write/create these contentControls
```
Word.run(async (context) => {
        const range = context.document.getSelection();
        if (range) {
          range.insertText('Enter Step Instructions', Word.InsertLocation.replace);
          range.insertContentControl();
          range.select(Word.SelectionMode.select);
          await context.sync().catch(console.error);
          resolve();
        }
        resolve(null);
      })
        .catch((error) => {
          console.log('Error: ' + JSON.stringify(error));
          if (error instanceof OfficeExtension.Error) {
            console.log('Debug info: ' + JSON.stringify(error.debugInfo));
          }
          reject(error);
        });
```

## Context

Seems to be some sort of regression, started happening past 2 days, there's been no known code change from our end for over a month.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Browser (if using Office on the web): Chrome

## Useful logs

- [ x ] Console errors
- [ x ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by JinghuiMS** [comment]
Thanks for reaching us. It's definitedly not right to have this error. And what's your word version? If you can provide a repro video, it will be helpful for us to repro the issue, because I can't repro it in my machine. Could you check the video in the attachment? Is there something wrong with the operation that makes it impossible to reproduce? 

https://user-images.githubusercontent.com/56814588/113378088-b4150f80-93a8-11eb-9bac-eeb725af40b9.mp4

**Notes: open powerpoint client, click insert tab, click "screen recording". we can easily record the screen.**

**Comment by leonliang-apprentice** [comment]
I can't repro from script lab, but we have our own add-in locally hosted that we are running. 
I have a slight suspicion that perhaps Word is not able to write the contentControls back to the source word doc. Currently we are grabbing the word doc from a cloud storage provider with a signedURL such as AWS S3 or Azure Blob Storage.

How does Word write back to the original doc and how do we know if it correctly saved?

**Comment by JinghuiMS** [comment]
Sorry, I still can't repro this issue after I build one personal addin. Could you share your document and your own add-in for repro this issue? 
If you edit in word online, it will trigger save operation, this operation will save your edited content. You can save your docx into local machine, then you can follow the attached video to check whether your changes have been saved into document.

https://user-images.githubusercontent.com/56814588/113694920-e6a16e00-9702-11eb-8c32-d8163ec7875b.mp4
