### ISSUE TITLE
Powerpoint add-in: Get the subtitiles of the selected slides 

### ISSUE THREAD

**Issue by Sam2243** [OfficeDev/office-js#177]
Hi,

I am making an add-in for powerpoint and one of the use case is a user selects a slide or multiple slides and I want to extract the text of the selected slides. I am using the following code but I just get the title, id and index information of the slide and not the subtitles. Can anyone please help me? :) here's the code

```
 Office.context.document.getSelectedDataAsync(Office.CoercionType.SlideRange, function (asyncResult) {
            if (asyncResult.status == "failed") {
                console.log("Action failed with error: " + asyncResult.error.message);
            }
            else {
                console.log(asyncResult.value.slides[0]); // This just returns an object with information (id, index and title)
            } 
        });
```

**Comment by JuaneloJuanelo** [comment]
this is not supported in the API please open a case in our user voice channel. https://officespdev.uservoice.com/
