### ISSUE TITLE
sheets.addFromBase64 not navigating to the inserted sheets in excel online

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#1770]
## Expected Behavior
using api sheets.addFromBase64 to insert sheets should navigate to the new sheets in excel online

## Current Behavior
It can insert successfully but not auto navigating like office excel app.

## Steps to Reproduce, or Live Example
https://gist.github.com/jasonhieu1905/6a6ee77293642fad418677dca3ff5a5c

Excel Online (**have to click the sheets**)
![9nz5RdoZDe](https://user-images.githubusercontent.com/13063615/113243884-0f2e0000-92de-11eb-9fc8-7ec879ca4188.gif)

Excel app (**auto navigate to the sheet**)
![rULtH4s1bd](https://user-images.githubusercontent.com/13063615/113244003-587e4f80-92de-11eb-8ba0-5bfe9f21c815.gif)

## Context
- Excel app can navigate to the new sheets

## Your Environment

* Platform [ iOS, Office on the web]: ______
* Host [Excel]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): chrome

**Comment by lumine2008** [comment]
Thanks @jasonhieu1905 , Team is looking into this issue, a bug 4998492 is created to track this issue. 

Meanwhile, I would suggest that you could use a worksheet.activate() API as a workaround, thanks.

**Comment by lumine2008** [comment]
@jasonhieu1905 , i have a question, as some of the customer may not want to activate the newly inserted worksheet, and some customer want to activate the worksheet, do you think it's better not activate for Windows Excel and Excel online?

**Comment by jasonhieu1905** [comment]
@lumine2008 : thanks for the reply. I can confirm the **worksheet.activate() API** works. In my opinion, the **addFromBase64**  should not change the behaviors of the office app (no matter native or online), so I prefer to not activate the new worksheet. but the api should offer the user to choose :)

**Comment by lumine2008** [comment]
Thanks @jasonhieu1905

**Comment by donlvMSFT** [comment]
This issue already been fixed based on the bug status, please help verify. 
I'd like to close this thread, thanks for the discussion.
