### ISSUE TITLE
[Word] issue with range.insertContentControl()

### ISSUE THREAD

**Issue by shubhamsoni2074** [OfficeDev/office-js#1771]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am inserting html to document and then trying to wrap it in content control. like
`const range: Word.Range = selection.insertHtml(html, Word.InsertLocation.start);
range.insertContentControl();`
This works fine if line is completely empty ,but fails if something is written in the line please look at attached video (my text is having new line character after first word ).
but if I do `selection.insertContentControl().insertHtml(html, Word.InsertLocation.start)` if inserts content control in next line 

## Expected Behavior
a content control should wrap all text ,irrespective of any text already present and it should not move to new line ( if I do `selection.insertContentControl().insertHtml(html, Word.InsertLocation.start)`)

## Current Behavior
content control is inserted around first word only (my text has some new line character please look at html snippet) if some text is present in that line

## Steps to Reproduce, or Live Example
pfa

## Code snippet
`$("#run").click(() => tryCatch(run));

async function run() {
  await Word.run(async (ctx) => {
    const selection = ctx.document.getSelection();
    const html = `<html><head><meta http-equiv="Content-Type" content="text / html; charset = utf - 8" /><meta http-equiv="Content - Style - Type" content="text / css" /><meta name="generator" content="Aspose.Words for Java 21.2.0" /><title></title></head><body style="line - height: 108 %; font - family: Calibri; font - size: 11pt"><div><p style="margin - top: 0pt; margin - bottom: 8pt"><span>Version 1</span></p><p style="margin - top: 0pt; margin - bottom: 8pt"><span>The Customer may appoint a certified accountant to inspect and audit all records relating to the sale of goods and grants of licences, calculation of invoices, and the books and accounts of the Supplier at the Customer's expense at all reasonable times and on reasonable notice.</span></p></div></body></html>`;
    const range: Word.Range = selection.insertHtml(html, Word.InsertLocation.start);
    range.select();
    ctx.load(range, "text");
    ctx.load(selection, "text");
    await ctx.sync();
    console.log(range.text);
    console.log(selection.text);
    const parentContentControl = range.insertContentControl();

    await ctx.sync();
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}`

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Tested on web not sure about desktop
* Host [Excel, Word, PowerPoint, etc.]: WORD
* Session ID 1fc84dbc-3558-4e9c-b62e-d68d556fa42e
* Build 16.0.13929.41002
* Browser (if using Office on the web): ALL

## Useful logs

https://user-images.githubusercontent.com/81732332/113257982-f840db00-92e8-11eb-8175-c18421ba6277.mp4

**Comment by JinghuiMS** [comment]
Thanks for reaching us. It should be a issue. Bug 5008818 has been opened for internal track.

**Comment by wyh** [comment]
Is this bug resolved or still open?

**Comment by RuoyingLiang** [comment]
The bug is still open. We will update the thread once there is update. Thanks!

**Comment by yusufsamsum** [comment]
Is the bug resolved? Also, is there anyone who come up with a work around or a solution for that bug? Thank you.

**Comment by andreijitaru-gep** [comment]
Hello! Did you find any work-around for this?

**Comment by xiruatms** [comment]
Thanks for reporting this issue.

This is an expected behavior according to current design.

There're 2 supported content control on Word WAC: 

1. Inline contentcontrol: 

     All of the parts of this contentcontrol are in the same paragraph, there's no new line or new paragraph in this contentcontrol.

2. Block contentcontrol:

     There could be multiple paragraphs in the same contentcontrol. But for each paragraph inside the contentcontrol, the whole paragraph should be in this contentcontrol.

In your case:
If your selection was in the middle of a paragraph, and you wanted to insert a contentcontrol, it would be considered as an inline contentcontrol, there should be no new paragraph inside contentcontrol. 

If your selection is start from a newline, and you wanted to insert a contentcontrol with multiple paragraphs, it would be considered as an block contentcontrol, all of the contents you tried to insert will be in the same contentcontrol.

Please let me know if I made this clear.

**Comment by AndreiJitaru** [comment]
Hi @xiruatms! Correct me if I'm wrong but wasn't this possible until recently? Having a block content control start from the middle of a paragraph, I mean. I remember seeing this very behaviour on an officeJs project some time go. Was the design recently changed? It's just my curiosity. Thanks!
