### ISSUE TITLE
Custom functions returns #NAME? or #N/A if a user unhide workbook. RichApi.Error The JavaScript API request failed because the workbook was hidden

### ISSUE THREAD

**Issue by leybal** [OfficeDev/office-js#1773]
Hi. We are using sentry in our add-in for Excel and notice such error "RichApi.Error The JavaScript API request failed because the workbook was hidden. Please unhide the workbook and try again". This messages received from both Mac and Windows users. We reproduce this error using the [excel-shared-runtime-scenario](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario) example and recorded videos. Also we specified equivalent XLL in the manifest using [documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/make-custom-functions-compatible-with-xll-udf). Please take a look at the [video for Mac](https://drive.google.com/file/d/1_6i5yr-2izB0UB1JCTnQpAO6jcEUK7A0/view?usp=sharing) and [for Windows](https://drive.google.com/file/d/1y9ZwoL83nEWETy05riLOxzEC0DK2dLGL/view?usp=sharing).
Let's say a user runs a custom formula, saves the workbook, and hides it. The next time a user opens the workbook, the formulas do not work. Custom formulas error on Mac and Windows is different. 
This is reproduce locally, in production and even in script lab. 

## Expected Behavior
If a user unhide the workbook, the custom functions and the Excel JS API works correctly.

## Current Behavior
A user can't work with custom functions if he hide the workbook, save it and unhide again.
Probably we recive error "RichApi.Error The JavaScript API request failed because the workbook was hidden" becouse we set StartupBehavior.load and Excel can't handle StartupBehavior property for the workbook.

## Steps to Reproduce, or Live Example
1. Download excel-shared-runtime-scenario example and specified equivalent XLL in the manifest
2. Open the workbook and run =ADD() function
3. Save the workbook and hide it
4. Close Excel
5. Open Excel and unhide the workbook.
6. Run =ADD() function.
7.  The error #NAME? should be shown for Windows and #N/A for Mac.

## Context
Our users actively use the functionality to hide the workbook. But they have difficulty running our custom functions, which is the core of our add-in.

## Your Environment

* Platform: Mac, PC
* Host: Excel
* Office version number: 2102 (Build 13801.20360), 16.47.1
* Operating System: Windows 10, mac OS Big Sur

**Comment by grangeryy** [comment]
Thanks for reporting the issue. We'll take a look and update the progress later.

**Comment by grangeryy** [comment]
We've created bug 5011901 to track this.

**Comment by grangeryy** [comment]
@leybal after investigation, we found the reason.
1. Hide the workbook and close Excel.
2. Reopen the Excel and unhide the workbook -> in this step, Custom Function(CF) is processing **before** "unhide" action, so for hidden workbook, CF couldn't find the information it needs. 

One simple workaround is, you can try install the add-in after unhide the workbook.

To support the expected behavior is a requirement for us. For the scenario you mentioned, may I understand more from customers' perspective why they need to hide the workbook and unhide later?

**Comment by leybal** [comment]
@grangeryy thank you for the investigation. We get the RichApi.Error on a regular basis. We do not have a description of a specific scenario when a user hides and unhides the workbook. This is the standard Excel feature and users can use it however they like.
It looks like any js add-in will not work if a user hides and unhides the workbook. An add-in reinstallation is not the best workaround.

**Comment by grangeryy** [comment]
@leybal Agree with you on the point it is not the best workaround. Hide/Unhide workbook is still a Excel feature gap for Excel Online. I'll connect with the feature team to raise your issue. You may also try to give feedback directly through the status bar at the right bottom in Excel Online here:
![image](https://user-images.githubusercontent.com/50093161/114666994-82e5f900-9d31-11eb-9931-2c719187fa86.png)

**Comment by grangeryy** [comment]
I'll also created a item in backlog to support Custom Function for hidden workbook and prioritize with all other requirements together. Thx!

**Comment by grangeryy** [comment]
Feature request No.: 5026704

**Comment by leybal** [comment]
We have sent feedback via Excel online referring to this issue. We will be grateful for any updates.
