### ISSUE TITLE
Dialogs no longer function with Excel build 13926.20000 (Version 2104)

### ISSUE THREAD

**Issue by EdwinStraver** [OfficeDev/office-js#1774]
After updating to the the latest Excel beta version, all dialogs displayed by javascript addins are now just white, and do not function.

**Comment by Rick-Kirkham** [comment]
I've assigned this to @lliu113 .

@EdwinStraver In the meantime, can you reproduce this in Script Lab? If so, can you reproduce it in Script Lab on Word or PowerPoint?

**Comment by Rick-Kirkham** [comment]
@EdwinStraver Ignore my previous comment. This has been determined to be a bug in that build.  The fix should be pushed out within 24 hours. Please restart Excel at that time and it should be fixed. 

Please let us know whether it is fixed or not.

**Comment by EdwinStraver** [comment]
Will do, thx!

**Comment by EdwinStraver** [comment]
@Rick-Kirkham This issue is fixed.
