### ISSUE TITLE
Unclear error when opening Outlook add-in "A problem occurred while trying to reach this add-in"

### ISSUE THREAD

**Issue by skaramchandani11** [OfficeDev/office-js#1775]
We (Groove) have an Outlook add-in. For one of our customers, all of their users are running into an unclear error when clicking the button in our add-in that is supposed to show a MSFT auth screen, only when trying from the Outlook Desktop Client. The error is in the screenshot below:

![image](https://user-images.githubusercontent.com/35939675/113345728-b499a180-92e7-11eb-9e54-4e9fff73dcdf.png)

## Expected Behavior

We expect that when they click the Sign in button in our add-in, a window for MSFT auth to our app shows up.

## Current Behavior

What is happening now is that the error message pops up, and clicking "Retry" does not do anything

## Context

One of our new large customers is unable to onboard their team to our add-in/platform until this is resolved. This is currently holding up the deployment. This issue is specifically happening on their Outlook Desktop environment, they are able to sign in to our add-in just fine on Outlook web, so maybe some internet settings on their end are blocking it.

We have tried the [recommended workarounds/solutions](https://answers.microsoft.com/en-us/outlook_com/forum/all/a-problem-occurred-while-trying-to-reach-this-add/1b644b37-3bc9-4264-8984-accd515f0de1) that I found online. Looks like many users run into this issue with different Outlook add-ins. These recommended solutions have not worked and we would like any guidance on getting around this. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Build Version is below:
![image](https://user-images.githubusercontent.com/35939675/113345950-09d5b300-92e8-11eb-81bb-deff18a48d9b.png)
* Operating System: Windows 10

**Comment by exextoc** [comment]
As you mentioned, this could be a network error. Can you verify whether the customer can reach the URL directly in a web browser?

It sounds like the error is occurring within a dialog? Are there any JavaScript errors occurring within the dialog? Can you tell whether `Office.initialize` is successfully defined and called within the dialog?

It would be helpful to know the version of Windows 10 the customer is using as well. [Depending on the version of Windows](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins), Outlook could be using either IE11 or Edge to render the add-in. If it's using IE11, I would check whether the issue also occurs in OWA running in IE11.

References:

- [Use the Office dialog API in Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins)
- [Authenticate and authorize with the Office dialog API](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api)
