### ISSUE TITLE
[Excel for Mac] Share runtime is not open an app in Taskpane.

### ISSUE THREAD

**Issue by kullachoke-bosuwan-rft** [OfficeDev/office-js#1778]
When enable feature shared-runtime, application is not showing in taskpane but got a black page as in image attached
<img width="995" alt="Screen Shot 2564-03-18 at 14 13 07" src="https://user-images.githubusercontent.com/64405659/113558617-2ba5a180-962a-11eb-980a-c0102d6d3d29.png">

## Expected Behavior
App running in taskpane

## Current Behavior
blank taskpane page

## Steps to Reproduce, or Live Example
Enable shared runtime in manifest then open it in Excel for Mac

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Excel 16.47.1 (21032301)
* Operating System: OSX Catalina 0.15.7 (19H524)
* Browser (if using Office on the web): -

**Comment by kullachoke-bosuwan-rft** [comment]
After doing some investigation, This only happens when we enable debug mode on Excel mac.
`Open debug mode: (Terminal) defaults write com.microsoft.Excel OfficeWebAddinDeveloperExtras -bool true`

The taskpane show as blank but it display in debug dialog instead. So, I just would like to confirm if it is expected behaviour or not. Is there any difference between running on dialog and taskpane?

**Comment by jeremy-msft** [comment]
Hi @kullachoke-bosuwan-rft, thanks for reporting this issue.  `OfficeWebAddinDeveloperExtras` is not supported for shared runtime  add-ins, and the property will be ignored when using shared runtime in a future update.
