### ISSUE TITLE
[Outlook] `setAsync` results in unpredictable undo behavior

### ISSUE THREAD

**Issue by david-davidson** [OfficeDev/office-js#1781]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi there!

My organization has an Outlook add-in that uses [Office.Body.setAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-preview#setAsync_data__options__callback_) to write content into Outlook emails. Users sometimes edit mails in Outlook directly and sometimes do so via the add-in, leaning on the `setAsync` functionality to keep Outlook up to date. That means that, as users occasionally undo changes in Outlook's editor, some of the changes originated directly from the user, and some from the add-in.

We've observed varying behavior across Outlook environments:
* Outlook web app: undo works fine (via command- or control-Z in the Outlook email body)
* Mac desktop client: undo of a change made via `setAsync` empties the body entirely
* Windows desktop client: undo of a change via `setAsync` has no effect

## Expected Behavior
Mac and desktop client behave like the web client: changes via undo (command- or control-Z) work regardless of whether the change came directly from the user, or from the add-in.

## Current Behavior
* Mac desktop client: undo empties the body entirely
* Windows desktop client: undo has no effect

## Steps to Reproduce, or Live Example
I [modified](https://github.com/david-davidson/setasync-bug-repro/commit/84548d98a2aa7f1503c3c985222a575bb7c68ae1) the "Git the Gist" sample add-in (original [here](https://github.com/jasonjoh/git-the-gist)) to use `setAsync` instead of `setSelectedDataAsync`. That provides a repro, but (if cloning and side-loading is a hassle) the same core repro—update the body with `setAsync`, fail to undo it—should work generically in any Outlook add-in that uses `setAsync`:
* Clone https://github.com/david-davidson/setasync-bug-repro and run `npm install` / `npm start`
* Follow the steps in the README (no changes from Microsoft's original text) to manage the local certificate and side-load the add-in
* Open a Compose window (new message or existing draft) in Mac or Windows desktop
* Write text (any text) in the mail body
* Use the add-in to insert a gist into the body with `setAsync`
* Focus the mail body, and attempt to undo the insertion with control-/command-Z
* Mac: compose window will empty; Windows: no undo will take place

## Context
The big-picture goal here is: make sure our add-in isn't contributing to a frustrating Outlook experience for users! In any scenario where a user edits their email (via the add-in), thinks better of it, and decides to undo, we want to do the thing they expect.

## Your Environment
* Platform: Mac and Windows desktop
* Host: Outlook
* Office version number: 16.47
* Operating System: Mac OSX Big Sur, 11.2.3
* Browser (if using Office on the web): Chrome 89.0.4389.114 (no error, behavior we'd like to emulate on desktop)

## Useful logs
Unfortunately, I'm unaware of any way to get at logs, since the undo behavior takes place "outside" the add-in, within Outlook itself.

Thank you so much!

**Comment by exextoc** [comment]
Thank you for reporting the bug. We have added this to our backlog. Currently we don't have any timeline to share.
