### ISSUE TITLE
Extract ReplyTo from email item

### ISSUE THREAD

**Issue by Zamolxe00** [OfficeDev/office-js#1783]
Hi, I've been trying to the the replyTo list from an outlook message but there does not seem to be a way to do that, at least no a documented one.

I am trying to create a feature for shared mailboxes, as for docs my assumption was that sender will hold the delegate address, but it seems to return the same address as from when email is from a shared mailbox.

How can this replyTo list get extracted using officejs?

**Comment by exextoc** [comment]
Hello @Zamolxe00 

You can fetch the list of to and cc using outlook add-ins.

`Office.context.mailbox.item.to` can be used to fetch the to list.
`Office.context.mailbox.item.cc` can be used to fetch the cc list.

Based on the values you can construct the "replyTo" list. 

Furthermore, you can visit this to learn more about creating add-ins : [Here](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart#:~:text=When%20prompted%2C%20provide%20the%20following,Choose%20a%20script%20type%3A%20Javascript)

**Comment by Zamolxe00** [comment]
I am not sure I understand how you construct replyTo based on to and cc. Cc is empty and to has the recipient, I need reply_to since from is the shared mailbox.

**Comment by exextoc** [comment]
Please answer a few questions to help us understand the scenario better. 

- What do you mean by "replyTo" list ? Please give us an example to understand better.
- Are you targeting any specific platform for the same ? (ex: windows client, outlook on web, mac client etc)
- What have you tried to achieve the same ? Did you try any add-in/add-in API to achieve the same ?

**Comment by Zamolxe00** [comment]
1. Please see the snippet below, I am referring to replyTo, this is extracted from graph explorer:
`"toRecipients": [
                {
                    "emailAddress": {
                        "name": "",
                        "address": ""
                    }
                }
            ],
            "ccRecipients": [],
            "bccRecipients": [],
            "replyTo": [
                {
                    "emailAddress": {
                        "name": "",
                        "address": ""
                    }`
2. Targeting all 3 specified platforms.
3. Yes, after reading documentation my understanding is that this would be solved by getting context.item.sender, but after some tests it does not seem

**Comment by exextoc** [comment]
So you are trying to fetch "replyTo" field of a message item, from graph API call. 
So what issue are you facing, with that ? 

Moreover, these is another way to fetch that. 
It can also be done using "Office.item" interface. 
The item namespace is used to access the currently selected message, meeting request, or appointment.
You can read more here : https://docs.microsoft.com/en-us/javascript/api/outlook/office.item?view=outlook-js-preview
Is there anything that you faced here, you can let us know ?

You can get the same value from here too.

`Office.context.mailbox.item.from.getAsync(callback);
function callback(asyncResult)
{
  showMessage(asyncResult.value.displayName + " " + asyncResult.value.emailAddress);
}`

**Comment by Zamolxe00** [comment]
Office.context.mailbox.item.from.getAsync(callback) this will retrieve from address, in this case the shared mailbox, ex: support@company.com. replyTo will hold the actual email of the user that sent the email will be in the replyTo. I do not use ghraph API to extract it, i want to use Office.item. 
The graph api response was just an example to make it clear what property I am talking about.

There is no Office.context.mailbox.item.replyTo, there is Office.context.mailbox.item.from and Office.context.mailbox.item.sender, but both return the same shared address in this case: support@company.com

Microsoft docs on this make you believe sender will hold the address of the user using the shared mailbox.

**Comment by exextoc** [comment]
Currently the feature of finding replyTo list using add-in APIs or Office.Item interface, is not a part of the product. 
We track Outlook add-in feature requests on our [user-voice page.](https://github.com/OfficeDev/office-js/issues) Please add your request here with the label “Type: product feature request”. Feature requests on user-voice are considered, when we go through our planning process.

**Comment by Zamolxe00** [comment]
Thanks for your help, I have created a feature request.
