### ISSUE TITLE
Outlook add-in manifest is not updated for existing users after successful updating on AppSource

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1785]
We have submitted an updated manifest file on 25 February, it was approved and published by the AppSource team. Since then, neither our test machines nor our users have got the updated manifest. How much time does the update process usually take? May it be that our update got lost somehow? Please let us know.

Just in case, here is our add-in:
https://appsource.microsoft.com/en/product/office/WA200000930

**Comment by exextoc** [comment]
Thank you for bringing it to our notice. 
We are getting in touch with the concerned team.

**Comment by exextoc** [comment]
Is this problem happening for any particular platform or is it across all platforms (Win32, Mac, Web)?

**Comment by DmitryKostochko** [comment]
All platforms are affected.

**Comment by exextoc** [comment]
Could you help with a few confirmation / questions to help us connect to the correct team: 
1. is the expected version of the addin 1.6.202.0? 
2. Is the issue only happening for updates?  That is - if a user does a new installation of the addin, do they get the updated version?
3. Were there permissions changes in the addin, was it also ReadWriteMailbox before the update?
4. For the users who did not get updates, was the installation by admin or by user or both?

**Comment by DmitryKostochko** [comment]
> is the expected version of the addin 1.6.202.0?

Yes, exactly.

> Is the issue only happening for updates? That is - if a user does a new installation of the addin, do they get the updated version?

Yes, the issue affects updates only. In new installations, we see the latest version of the manifest.

> Were there permissions changes in the addin, was it also ReadWriteMailbox before the update?

Permissions were not changed. We added a SSO section, probably this causes the issue?

> For the users who did not get updates, was the installation by admin or by user or both?

On all our test machines, there are user installations.

**Comment by exextoc** [comment]
Yes SSO section could be the potential issue. Can you confirm how these addins are deployed for the affected users ? Is it admin deployed or user deployed?

**Comment by DmitryKostochko** [comment]
> Can you confirm how these addins are deployed for the affected users ? Is it admin deployed or user deployed?

It is user deployed.

**Comment by exextoc** [comment]
No action for quite some time. Closing the issue.

**Comment by DmitryKostochko** [comment]
@exextoc, the issue is not resolved yet, please re-open the case.

**Comment by osvp-ai** [comment]
Did the issue get resolved? Currently experiencing the same problem.
