### ISSUE TITLE
Turning off event handlers doesnt seem to have an effect

### ISSUE THREAD

**Issue by EdwinStraver** [OfficeDev/office-js#1786]
In my JS addin for Excel, I create a onchange handler, like so:

Excel.run(function (ctx) {
        var wbk = ctx.workbook;
        var sh = wbk.worksheets.getActiveWorksheet();
        sh.onChanged.add(myChangeHandler);
...

This works perfectly fine, and when a change happens on the worksheet my function myChangeHandler is called,

But, when I turn off the event hander, using a function like:

function enableSolverEvents(enabled) {
    return Excel.run(function (context) {
        context.runtime.load("enableEvents");
        return context.sync()
            .then(function () {
                context.runtime.enableEvents = enabled;
            }).then(context.sync);
    });
}

and calling enableSolverEvents(false), 
I find that my function myChangeHandler is still being called.

I worked around the problem by checking the value of "context.runtime.enableEvents" inside my callback and just exiting when this is false, but it is rather bizarre to check for enableEvents flag inside my event callback handler.....

Edwin

**Comment by jipinshi** [comment]
@EdwinStraver , thanks for reporting the issue. May I know which platform did you meet the issue? Windows? Mac or Excel Online? I tried Windows and cannot repro with ScriptLab. Can you share one gist you repro the issue and let me know which platform do you use.

**Comment by EdwinStraver** [comment]
This is using desktop Excel, on Windows.  We experience this on multiple machines, with various versions of Excel

**Comment by jipinshi** [comment]
@EdwinStraver , May I know the version of Excel you used? I tried with the latest version and cannot repro.

**Comment by jipinshi** [comment]
This is my gist and seems changed from true to false can work fine to me. https://gist.github.com/jipinshi/0a57a49589862b8fd5f90900cacb43e9
@EdwinStraver

**Comment by EdwinStraver** [comment]
@jipinshi 
Thanks. I modified the code  a bit:
https://gist.github.com/EdwinStraver/6ae7293b835d6d270b9a46903f4ec259

When I press "run", and then click "write a1" nothing should happen in the log.
And with my latest version  (2105 , build 14002.20000) that is indeed the case.

But on another machine (2103 (build 13901.20230), when we press "write a1", the log displays the event.

**Comment by jipinshi** [comment]
@EdwinStraver , suggest to upgrade the version, since 16.0.13901.20230 is blocked to release in production. It is in preview status, marked as blocked to release in production.
