### ISSUE TITLE
Office.item interface extraction of replyTo list from email

### ISSUE THREAD

**Issue by Zamolxe00** [OfficeDev/office-js#1787]
I am referring to replyTo, this is extracted from graph explorer:
`"toRecipients": [ { "emailAddress": { "name": "", "address": "" } } ], "ccRecipients": [], "bccRecipients": [], "replyTo": [ { "emailAddress": { "name": "", "address": "" }`

There is no Office.context.mailbox.item.replyTo, there is Office.context.mailbox.item.from and Office.context.mailbox.item.sender.

Desired behaviour:
ReplyTo list shown in graph explorer on an email can be extracted using add-in API.

**Comment by lindalu-MSFT** [comment]
Hi @Zamolxe00 Can you please submit this idea to [our feature request forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) on Microsoft Tech Communities? You can label this with Microsoft Graph and/or Office Add-ins development.

**Comment by Zamolxe00** [comment]
@lindalu-MSFT I would rather not create a Microsoft account to do this. I was lead to believe that here is where features should be created.

**Comment by Zamolxe00** [comment]
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/office-item-interface-extraction-of-replyto-list-from-email/idi-p/2279902#M17

**Comment by Oleg-O** [comment]
Thanks for adding that to Tech Community page! Feature requests on Tech Community are considered, when we go through our planning process.
