### ISSUE TITLE
In OWA getSelectedDataAsync does not return body selection anymore

### ISSUE THREAD

**Issue by aduggleby** [OfficeDev/office-js#1788]
## Expected Behavior
When calling [getSelectedDataAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#getSelectedDataAsync_coercionType__options__callback_) while having body text selected (i.e. highlighted) it should return information about the highlighted text including the sourceProperty == "body". 

## Current Behavior
In OWA (outlook.office.com) regardless of whether I selected text in body or subject, the returned sourceProperty is always "subject". 
In Desktop Outlook the behaviour is correct as expected.

## Steps to Reproduce, or Live Example
* Link to live example: https://gist.github.com/aduggleby/2fe45e4e841db4249f44532f8c53be5c
* Highlight a part of the body, run the script and the text displayed is the sourceProperty of the result and will display "subject".

## Context
As far as I can see the behaviour here changed within the last month. Before that both OWA and Desktop Outlook were displaying the correct behaviour.

Current effect is that a part of our Add-In (MailMerge365) does not work.

## Your Environment

* Platform: Office on the web
* Host: Outlook
* Office version number: current
* Operating System: Win10 current
* Browser (if using Office on the web): reproduced in Edge, Chrome, Firefox

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding getSelectedDataAsync API. It has been put on our backlog. We, unfortunately, have no timelines to share at this point 
Internal tracking id: Office: 2065300
