### ISSUE TITLE
Issue with ribbon enablement API in Excel Online

### ISSUE THREAD

**Issue by Alex0cean** [OfficeDev/office-js#1792]
We recently noticed the following regression in the Ribbon Enablement of Excel using the Ribbon Enablement API. This immediately affects all our customers.

Summary:
All buttons within a Ribbon group are disabled. The API is used to enable one button in this group. By mistake all buttons in this group are disabled.
This error is reproducible in Excel Online in both Ribbon variants.

Video shows how this is reproduced comparing Desktop Excel on Windows with Excel Online.  (Desktop works as expected).
The attached zip contains the source code for this repro. It was used to create the video above.

https://user-images.githubusercontent.com/80747078/114564060-43a3a380-9c70-11eb-82dd-2d1a21ab6fe1.mp4

[ribbonEnablementRegression.zip](https://github.com/OfficeDev/office-js/files/6304223/ribbonEnablementRegression.zip)

**Comment by trigurl** [comment]
Thanks for attaching the repro.  Investigating.

**Comment by trigurl** [comment]
I've logged a bug and assigned it to our area expert.

**Comment by JackyChen200304** [comment]
@Alex0cean , thanks for your feedback, it is valuable to us. Seems you are still using the old beta version namespace for Ribbon JS API. After Ribbon API released out, it has been changed according to the feedbacks. Please use Office.ribbon.requestUpdate() to update the ribbon control status.
You may checkout the sample from https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands

**Comment by Alex0cean** [comment]
Hi Jacky,

we already use Office.ribbon.requestUpdate() in our current add-in code. Sorry, the example that we used to document was slightly older. But even if you replace it with the new call, the error stays the same. Please re-check it. 

Best,
Alex

**Comment by msgarycha** [comment]
@Alex0cean,

Sorry for the delay. We can confirm that there is a regression on our side. We are working on a fix. Meanwhile, please avoid disabling all buttons in a group to prevent hitting the problem as a temporary remedy.

Regards,
Gary

**Comment by Alex0cean** [comment]
Hi @msgarycha ,
do you have a rough ETA for the fix?  
Best,
Alex

**Comment by Alex0cean** [comment]
Hi I can confirm this bug is fixed now as of version 16.0.14216.
