### ISSUE TITLE
Desktop Excel JS Add-in displays browser download status in task pane

### ISSUE THREAD

**Issue by jhschmidt38** [OfficeDev/office-js#1793]
## Expected Behavior

When downloading a file using a Javascript add-in I would expect a message box or a save as dialog to appear in the center of the application window so the download status is clear to the user. Task panes are not meant to be the center of attention and users can easily miss the fact that their file was downloaded successfully. At the very least the current download status bar should be styled so the filename is not hidden.

## Current Behavior

Below is an example of the download status bar in the Analytic Solver task pane after a file is downloaded from a server. The blank bar at the bottom of the task pane does not display the downloaded filename.
![Download-status-bar-in-task-pane](https://user-images.githubusercontent.com/5251809/114581886-f0f8c600-9c34-11eb-8b6a-d15146078db5.png)

If the task pane is sized wider the downloaded filename is displayed.
![Wider-download-status-bar-in-task-pane](https://user-images.githubusercontent.com/5251809/114583151-26ea7a00-9c36-11eb-8b74-a4aeab72a383.png)

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2013 (Build 13901.20400 Click-to-Run)
* Operating System: Windows 10 Pro Version: 20H2 OS Build: 19042.867 Experience: Windows Feature Experience Pack 120.2212.551.0
* Browser (if using Office Online): N/A

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lindalu-MSFT** [comment]
Hi, can you please submit this suggestion to our new Feature Suggestion platform?
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

**Comment by keyur32** [comment]
Thanks, agree with @lindalu-MSFT  that we'd need to treat this as a seperate feature request, as today, we only have control of the taskpane.  If the file is an Excel workbook, then the recommendation would be to open it, or insert new sheets with that content using the upcoming AddFromBase64 APIs.

**Comment by jhschmidt38** [comment]
In this case it is downloading an html or zip file so it can't be opened in Excel. I submitted a new idea this morning on the Microsoft 365 Developer Platform as Linda suggested.

Thanks Keyur and Linda
