### ISSUE TITLE
Word.Range.insertText now moves the cursor

### ISSUE THREAD

**Issue by pb-jeff-oneill** [OfficeDev/office-js#1794]
I updated this to make the issue clearer on 2021-04-17.

---

Suppose I have this text in a Word doc:

    foo bar^

where the cursor is indicated by the `^` and I have a range `r` corresponding to the word `foo`.  Previously, if I did this:

      r.insertText('foofoo', 'Before');

then the Word document would then show this:

    foofoofoo bar^

Importantly, the cursor would stay after the word bar which what a user would expect.

As of today, the call to `insertText` causes the cursor to move and it looks like this:

    foofoof^oo bar

It appears that the cursor position somehow relates to character count.  Both before and after the `insertText`, there are 7 characters before the cursor.

This is very disruptive for users because all of a sudden the cursor is in a different location.  The user may be typing characters and expecting them to be after the word bar, but the characters suddenly appear in a different location.

I hope this can get fixed quickly.

**Comment by jipinshi** [comment]
@pb-jeff-oneill , what's the platform Win32/Mac/iOS/Word Online? and what's the build hit the issue?

**Comment by pb-jeff-oneill** [comment]
I am on Mac OS X 11.2.3 with Office 365 and Word 16.48.  It happens with both installed Word and browser Word (Chrome).

A customer has the same issue on Windows 10, but I don't have the other details.

It seems to be a Javascript bug that is affecting all platforms.

**Comment by sumurthy** [comment]
@pb-jeff-oneill Thanks for making the connection from Stackoverflow to this Github issue. Looking at the issue, this is likely not related to Office-js update but more on the application side. That is, the API interface has not changed and rather the API behavior may have changed causing this issue. I think the right fix would involve fixing the bug in the Office app, which I guess will be looked at by @yihuax

**Comment by pb-jeff-oneill** [comment]
Thank you @sumurthy for the feedback.  I can confirm that downgrading to Word 16.46 on Mac is a work around for this bug.

I will instruct my users that they need to turn off automatic updates of Office and downgrade Word to 16.46.

I'm looking forward to a quick fix of this bug.  Is there a better place to report this bug?

**Comment by yihuax-zz** [comment]
Looks it is a MAC-only issue. I couldn't repro it with the latest win32 code.

Thanks!
Yihua

**Comment by pb-jeff-oneill** [comment]
@yihuax, no the bug appears to be on all platforms.  

I have personally verified the bug on:

- Windows 10 with Word 16.0.13901.20366, and
- web Word

Please let me know how I can help you replicate.

**Comment by yihuax-zz** [comment]
Yes. I found that and made a fix last night.

Thanks for letting us know the issue. I'll submit the fix as soon as possible.

Thanks.
Yihua
________________________________

**Comment by pb-jeff-oneill** [comment]
@yihuax, amazing, thank you for the fast turn around!

Any idea when the fix will be in production?  It would be helpful to let our users know.

**Comment by yihuax-zz** [comment]
I have applied the fix to a sub-branch of our codebase. Once the sub-branch is merged to the main branch (probably by this weekend?), I will let you know the version number with the fix. Our guess is you may get it in production in late May.

Thanks again!
Yihua

**Comment by yihuax-zz** [comment]
The fix will be in build version 16.0.14022.10000.

Thanks!
Yihua

From: Yihua Xiong
Sent: Tuesday, April 20, 2021 2:02 PM
To: 'OfficeDev/office-js' ***@***.***>; OfficeDev/office-js ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/office-js] Word.Range.insertText now moves the cursor (#1794)

I have applied the fix to a sub-branch of our codebase. Once the sub-branch is merged to the main branch (probably by this weekend?), I will let you know the version number with the fix. Our guess is you may get it in production in late May.

Thanks again!
Yihua

**Comment by pb-jeff-oneill** [comment]
As of the May 11, 2021 Word update:

- The bug **is not fixed** on Windows 10 with Word 2104 (Build 13929.20372)
- The bug **is fixed** on Mac with Word 16.49 (21050901)

Getting closer at least...

**Comment by yihuax-zz** [comment]
@AbidRahman-MSFT ***@***.******@***.***>  Abid, The fix should be in devmain 14022. Word 2104 (Build 13929.20372) is earlier than devmain 14022, right?

**Comment by AbidRahman-MSFT** [comment]
That is correct, the bug has been fixed in Word version 2105. (Or any build greater than 14022.00000).

**Comment by pb-jeff-oneill** [comment]
Confirming that this is now fixed for Office 365 on Windows.

I don't have access to Office 2019 so I am not able to check that.

**Comment by yihuax-zz** [comment]
Good. Thanks!

**Comment by yihuax-zz** [comment]
Great! Thanks.
