### ISSUE TITLE
Side-loading behavior change makes the debugging harder

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js#1795]
## Expected Behavior

In the previous versions it was possible to have in shared folder add-in catalog multiple manifests referencing various versions of same add-in (with only difference in ID element in the manifest) and developer could just insert one addin at a time. To switch the only need was to clean cache/Wef folders.

## Current Behavior

All manifests in the shared folder are being loaded, as a consequence all of them - except the first loaded - throw errors due to custom functions. Also it is not under  control what will be loaded.
As a consequence we are forced to use workaround having single manifest per folder and rather switch add-in catalogs.

## Steps to Reproduce, or Live Example

1.	Downloaded manifest for ScriptLab: https://github.com/OfficeDev/script-lab/blob/master/manifests/script-lab-react-prod.xml
2.	Add it to local/shared folder 3 times with different name, each changing ID – last digit changed to 2,3,4 respectively.
3.	Inserted them manually
4.	Closed excel
5.	Then cleaned cache/remove WEF folders
6.	Open excel
7.	The addins will reappear.

https://user-images.githubusercontent.com/19533927/114698589-8ff9ec80-9d1f-11eb-8a64-01c3b03f6268.mp4

## Context

It is quite common to switch between versions while developing addin, i.e. it is much easier to switch the add-ins/versions while having single shared folder with multiple manifests and it is crucial to have under control what add-in is loaded, etc.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 
![image](https://user-images.githubusercontent.com/19533927/114698812-cd5e7a00-9d1f-11eb-9d3b-5d0a229eb058.png)
* Operating System: Windows 10
* WebView: 
![image](https://user-images.githubusercontent.com/19533927/114700774-3646f180-9d22-11eb-81d6-5dd348ed14f6.png)

**Comment by lindalu-MSFT** [comment]
@sumurthy Hi Sudhi, this is a Script Lab/Excel/Sideloading issue. Can you please help triage? I'm not sure who the correct PM to assign to is. Thanks in advance!

**Comment by sumurthy** [comment]
This is not likely anything to do with the Office JS library. Probably something to do with the platform. Will start with Sudheer and check.

**Comment by trigurl** [comment]
There's an email thread about this feedback with Heidi.

**Comment by lliu113** [comment]
@4tti - sorry you're hitting this issue! Is the expected behaviour that removal of the WEF folders in step (5) results in no add-ins appearing in step (7) unless manually reloaded again?

**Comment by 4tti** [comment]
Hello @lliu113,
until recently it was behaving just like that, i.e. we had to manually insert the addin. It would be useful to have option to drive this behavior because I can imagine cases when this autoloading is useful, however there are also cases when it is rather annoying. 😁

Update: to make it clear, it is required to have the old behavior also for other reasons, imagine you have multiple manifests for same addin but different tenant (like production and test tenants), with this new behavior you are forced to always switch add-in catalog which is more work than to clean cached stuff via script and insert addin.
Thank you.

**Comment by trigurl** [comment]
I might have a way to make it a bit easier for you to switch between versions while developing.  I'm trying to get some feedback from my peers first to get their thoughts.

**Comment by 4tti** [comment]
Thank you @trigurl!

**Comment by trigurl** [comment]
@4tti OK so I have a work around for you which you can use to "toggle" in between shared folders (aka fileshare). 

Steps:  Here's an example of how to set it up, in my example I have 2 manifest versions that I wish to switch back and forth. 
1) Create 2 shared folders, call it Version1 and Version2.  I have one manifest in folder Version1 and another in Version2.
2) Boot Excel, go to File | Options | Trust Center | Click Trust Center Settings | Click Trusted Add-in Catalogs
3) Take this time to review the Network shares under Trusted Catalogs Tab, remove the ones you don't want to use.  
4) Add the shared folder path to your Version1 by pasted into the Catalog Url and clicking "Add catalog". Do the same for Version2 folder.
5) After you've created new entries to Version1 and Version2 shared folder, select checkbox for Version1 under "Show in Menu"
6) Click OK to everything and shutdown Excel.
7) When you reboot Excel go to Insert tab | Add-ins dialog | Shared Folder tab, you should see the Version1 add-in.  If you click on it, it should install and thus you can work on the Version1 add-in.
8) Shut down Excel.
9) Now open the Registry Editor and navigate to HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\Wef\TrustedCatalogs
10) Right click on the "TrustedCatalogs" node in the left pane and click Export, then save the file as Version1.reg to your desktop
11) Boot Excel and repeat steps 7-10 but with Version2 shared folder, name that registry file Version2.reg

So you now have a way to toggle between Version1 and Version2 of your add-in. When you want to work on Version2, then double click on the Version2.reg file and it will point to that shared folder the next time you boot Excel.  Just remember, if you make any changes to the shared folder, be sure to update your registry file by exporting it again.

Can you give this a try?

**Comment by 4tti** [comment]
@trigurl I'll give it a check, basically I think this could work... I mean having script to change the addin catalog by changing registry key can work fine.
Curious question - this behavior change was intended then, right? May I know the reason? 
Thanks a lot!

**Comment by trigurl** [comment]
So there's some behavior changes because we've added some new features.  Moving forward, we rely on the WEF folder to be present and wish to encourage folks not to make modifications to it.

**Comment by 4tti** [comment]
@trigurl thanks. That is pretty important information. Can I ask more questions?:
- does it mean that 'clearing cache' as mentioned in the docs should avoid removing content of WEF?
- Does it apply also to mac versions?
see docs: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#clear-the-office-cache-on-windows

Thank you!

**Comment by trigurl** [comment]
So the document you referenced is for side-loading which is different from shared folders (aka fileshare).   Side-loading can be used by Outlook add-in developers test their add-in on Exchange.  Outlook will cache the add-in after it has downloaded it from Exchange and to be efficient, it may not check for a newer version until some time as past.  So an Outlook dev might delete the WEF folder to force their update add-in to get re-downloaded.

Over the past year, we've been trying to improve our features such that hopefully you don't need to "clear your cache" to get your add-ins back into a good state.  Without going into details (because I can't), we've added some logic to help repair, so if the WEF folder is missing (plus some other things we look for) we might detect it as being in a bad state.  
Deleting the WEF folder is not bad if you find your add-ins in a weird state.

**Comment by 4tti** [comment]
Thank you for all the clarifications! 
I am going to close this...

@lindalu-MSFT feel free to reopen if you'll find some of the info interesting for the docs to be updated (as I think there is valuable information).
