### ISSUE TITLE
getAttachmentsAsync returns an id in invalid format on Outlook for Mac

### ISSUE THREAD

**Issue by PlayPratz** [OfficeDev/office-js#1796]
`Office.context.mailbox.item.getAttachmentsAsync` on Outlook for Mac returns an array of attachments, but their `id` attribute is not in the expected format.

## Expected Behavior

`getAttachmentsAsync` must return `id` in the same format as on Outlook on the Web.
**Output from Outlook on the Web: (expected format)**
```json
[
    {
        "id": "AAMkADUxMTA0MGJiLTg0NzUtNDA4YS04Y2NkLTVmOGU3NGQ2ZGQxMgBGAAAAAABvWrqazJtFS691lpIgzheFBwBzbAJJB4WdQ7K4RHYXR2psAAAAAAEPAABzbAJJB4WdQ7K4RHYXR2psAAGu5txEAAABEgAQAP+bGWGS4XlCmTt94ZLeXT0=",
        "name": "FileActivityLogs 08.03.21.csv",
        "contentType": "application/vnd.ms-excel",
        "size": 252158,
        "attachmentType": "file",
        "isInline": false
    },
    {
        "id": "AAMkADUxMTA0MGJiLTg0NzUtNDA4YS04Y2NkLTVmOGU3NGQ2ZGQxMgBGAAAAAABvWrqazJtFS691lpIgzheFBwBzbAJJB4WdQ7K4RHYXR2psAAAAAAEPAABzbAJJB4WdQ7K4RHYXR2psAAGu5txEAAABEgAQAP9veuW9oQlKpAL+xr4PdSw=",
        "name": "Some File.docx",
        "contentType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "size": 11869,
        "attachmentType": "file",
        "isInline": false
    }
]
```

## Current Behavior

**Output from the Mac client:**
```json
[
        {
            "id": "1D51CC90-4D36-4D42-8972-12034FB6DB8E",
            "name": "FileActivityLogs 08.03.21.csv",
            "contentType": "application/vnd.ms-excel",
            "size": 252484,
            "attachmentType": "file",
            "isInline": false
        },
        {
            "id": "35D94F7F-9D9B-42EC-B3FC-3857804BF7B2",
            "name": "Some File.docx",
            "contentType": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            "size": 12231,
            "attachmentType": "file",
            "isInline": false
        }
]
```

## Steps to Reproduce, or Live Example

1. Compose a mail on Outlook for Mac.
2. Attach one or more files to that mail.
3. Run [this code block](https://gist.github.com/PlayPratz/c9bd2f1fc0a8aecc44127357e9de6290) in Script Lab.

## Context

The `id` that we get from Graph or Outlook on the Web does not match the one from the Mac client. As a result, it is impossible to map the `id` attribute from Graph to the Mac client.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.48 (21041102)
* Operating System: macOS Big Sur version 11.2.2

**Comment by exextoc** [comment]
@PlayPratz  This behavior is by design for Mac Outlook. In Compose mode, the attachment ID is valid only within the same session and isn't guaranteed to map to the same attachment across sessions. This is mentioned in the documentation  [here](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/add-and-remove-attachments-to-an-item-in-a-compose-form). The attachment ID returned by getAttachmentsAsync can be further used by APIs like removeAttachment and getAttachmentContentAsync.
For your use case, Can you try getting the attachment details directly using Graph API instead?

**Comment by PlayPratz** [comment]
@exextoc If that is the case, what is the recommended way of mapping attachments across platforms? For my add-in, I want to attach files on the client side, then perform operations on them (getContent, remove, etc.) on the server side using Graph API. As you mentioned, there is no unique identifier for a single attachment.

**Comment by exextoc** [comment]
@PlayPratz Unfortunately, there is no unique identifier across the platform in Compose mode. The Id returned by Add-in can only be used to call APIs on the client-side in the same session. Can you try getting the attachmentIDs using Graph API itself and then perform desired operations? Documentation on this is available [here](https://docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=http).

**Comment by PlayPratz** [comment]
@exextoc That's pretty unfortunate. Maybe you can take it up as a feature request?

**Comment by exextoc** [comment]
We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.

**Comment by PlayPratz** [comment]
Alright, will do.

**Comment by exextoc** [comment]
Thank you!
