### ISSUE TITLE
Word add-in is not using latest Edge WebView2 runtime instead it is still running on Microsoft Edge Legacy

### ISSUE THREAD

**Issue by rajha-conga** [OfficeDev/office-js#1799]
My system got windows 10 update after that as per below link I was expecting Word add-in to use latest Edge WebView2 runtime instead of Microsoft Edge Legacy, which is not the case.

[New Microsoft Edge to replace Microsoft Edge Legacy](https://techcommunity.microsoft.com/t5/microsoft-365-blog/new-microsoft-edge-to-replace-microsoft-edge-legacy-with-april-s/ba-p/2114224)

OS : Windows 10 Enterprise
Version : 2004
OS Build : 19041.928

Office version : Microsoft 365 MSO (16.0.13801.20288)
Channel : Semi-Annual Enterprise Channel

Edge Chromium Canary Channel installed

Microsoft Edge webview2 runtime : 89.0.774.76

Created simple word add-in using yo generator which is mentioned in this [video](https://www.youtube.com/watch?v=TLNWq6YC6nU)

Impact : After this update my actual application is not working on my local system.

**Comment by rajha-conga** [comment]
@sumurthy @AlexJerabek @arttarawork @mscharlock

**Comment by ic3guy** [comment]
If you are on the "Semi-Annual Enterprise Channel" and your versions are correct for Edge WebView2 (as mentioned in your post) you need to follow the instructions at https://developer.microsoft.com/en-us/microsoft-365/blogs/understanding-office-add-ins-runtime/

Specifically from that blog post:

> Note: Customers on the Semi-Annual Enterprise channel of Office can expect to receive version Version 2102 in July 2021. Admins at these customers will need to take an additional step to enable the use of WebView2. They must create the registry key HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\WEF\Win32WebView2 and set its value to dword:00000001.

**Comment by rajha-conga** [comment]
we can close this issue. now it is using webview2

**Comment by geekykant** [comment]
@rajha-conga Can you confirm if this is how the registry key should be created?
This isn't working for me.
 
<img width="693" alt="Screenshot 2022-03-18 at 4 09 20 PM" src="https://user-images.githubusercontent.com/27401142/158988369-d59d7919-7361-413c-a459-a5f6b17fb1c2.png">
