### ISSUE TITLE
5001, An internal error has occurred

### ISSUE THREAD

**Issue by markb-trustifi** [OfficeDev/office-js#18]
## Expected Behaviour
Update email address:
`Office.cast.item.toItemCompose(Office.context.mailbox.item).to.setAsync(recipients, callback);`

## Current Behaviour
Receive an error: 5001, An internal error has occurred

## Steps to Reproduce
It happens only when all these factors are combined together:
1) Windows 10 (Outlook for Mac is OK)
2) Outlook 365 desktop client (Outlook in browsers Chrome and **IE11** are OK)
3) Add-in is pinned (when it is not pinned - it is OK)
4) Mail is forwarded or replied (new compose mail - is OK)

## Your Environment
Platform: Outlook 365 desktop client
OS: Windows 10

**Comment by exextoc** [comment]
Thanks for reporting!
Could you please share which Desktop Outlook version you have?

**Comment by markb-trustifi** [comment]
Outlook 2016

**Comment by markb-trustifi** [comment]
It started working now
