### ISSUE TITLE
Port Office.addin API functions to Outlook JS addin

### ISSUE THREAD

**Issue by jwissocq** [OfficeDev/office-js#1802]
[Office.addin](https://docs.microsoft.com/en-us/javascript/api/office/office.addin?view=excel-js-preview) exists for now in Excel and Powerpoint JS addins.
It would definitely be interesting to port this functionality to Outlook JS addin as well.

## Expected Behavior
Office.addin is loaded in Outlook JS addin, so that the taskpane can be shown or hidden.

## Current Behavior
Right now, Office.addin namespace is not loaded in Outlook JS addin, leaving no choice but to inform the client of the result of a command via [Office.context.mailbox.item.notificationMessages.replaceAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.notificationmessages?view=outlook-js-preview#replaceAsync_key__JSONmessage__callback_) which is not visible enough.

## Context
The goal is to be able to open the taskpane from Typescript code while I am executing a command launched from the ribbon.
For instance, I want to show the taskpane while refreshing data, so I can show the process ongoing to the user in a dialog inside the taskpane.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: All
* Host : Outlook

**Comment by exextoc** [comment]
We track Outlook add-in feature requests on our Tech Community Page: aka.ms/M365dev-suggestions
Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by jwissocq** [comment]
Thanks @exextoc so I posted https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/port-office-addin-api-functions-to-outlook-js-addin/idi-p/2277783#M13

**Comment by ElizabethSamuel-MSFT** [comment]
@Deymoun Thanks for posting on Tech Community!

Closing this issue.
