### ISSUE TITLE
Office.context.mailbox.item.getAttachmentContentAsync fails for attachmentType="cloud"

### ISSUE THREAD

**Issue by moszti** [OfficeDev/office-js#1806]
The call to the Office.context.mailbox.item.getAttachmentContentAsync function fails if there is a 'cloud' attachment type among the mail attachments. 

## Expected Behavior
The function should return the attachment content

## Current Behavior
The function fails with the following error:
![image](https://user-images.githubusercontent.com/35491891/115238237-be136e00-a11d-11eb-89e1-fd923402df83.png)

 it fails on the line 41 in the file getAttachmentContentAsyncApiMethod:

![image](https://user-images.githubusercontent.com/35491891/115238342-dedbc380-a11d-11eb-9d25-673fce2be8ed.png)

## Steps to Reproduce, or Live Example
Use the following function to reproduce it inside Outlook:

  `if (Office.context.mailbox.item.attachments) {
    for ( let i = 0; i < Office.context.mailbox.item.attachments.length;i++ ) 
{
Office.context.mailbox.item.getAttachmentContentAsync(
          Office.context.mailbox.item.attachments[i].id,
          this.handleAttachmentsCallback
        );
    }
  }

  handleAttachmentsCallback(result) {
    // Parse string to be a url, an .eml file, a base64-encoded string, or an .icalendar file.
    switch (result.value.format) {
      case Office.MailboxEnums.AttachmentContentFormat.Base64:
        // Handle file attachment.
        console.log('File attachment found');
        break;
      case Office.MailboxEnums.AttachmentContentFormat.Eml:
        // Handle email item attachment.
        console.log('Email attachment found');
        break;
      case Office.MailboxEnums.AttachmentContentFormat.ICalendar:
        // Handle .icalender attachment.
        console.log('Calendar attachment found');
        break;
      case Office.MailboxEnums.AttachmentContentFormat.Url:
        // Handle cloud attachment.
        console.log('Cloud attachment found');
        break;
      default:
        // Handle attachment formats that are not supported.
        console.log('Not yet supported attachment format found');
    }
  }

`  

## Context
I tried to read the content of email attachments and have tried a lot of different types. The "cloud" attachment type is  a ReferenceAttachment type (ATTACH_BY_WEB_REF). I have seen a similar behavior in EWS when I tried to read attachments of type ATTACH_BY_WEB_REF. A detailed description to the issue can be found here: https://stackoverflow.com/questions/65806240/attachments-with-the-referenceattachment-type-attach-by-web-ref-from-o365-mai

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office online, Office.js, Task pane addin
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Browser (if using Office Online): Chrome

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding  Office.context.mailbox.item.getAttachmentContentAsync API. It has been put on our backlog. We, unfortunately, have no timelines to share at this point 

Internal tracking id: OutlookWeb:114469

**Comment by exextoc** [comment]
Hi @moszti, please let us know if you're still facing this issue. Will be closing this thread otherwise.

**Comment by moszti** [comment]
Hi, It was confirmed as  a bug. I don’t know if it was solved on your end? Was it?Thanks- AttilaOn 19 May 2023, at 07:38, Outlook Add-ins Team - MSFT ***@***.***> wrote:﻿
Hi @moszti, please let us know if you're still facing this issue. Will be closing this thread otherwise.

**Comment by exextoc** [comment]
Hi @moszti, 
This is expected behavior now as cloud attachments in OWA have recently been updated to "Friendlier Link Names". Please find the documentation [link](https://support.microsoft.com/en-us/office/friendlier-link-names-in-email-02040f47-bd56-4806-8311-fc913fed54c0#:~:text=On%20the%20Message%20tab%2c%20select%20Link%20%3e%20Insert%2cURL%20to%20the%20name%20of%20the%20inserted%20file.) for reference.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
