### ISSUE TITLE
Outlook Desktop, WebView2, date.toLocaleDateString() and date.toLocaleTimeString() methods ignore Windows regional settings and return date/time in English (United States) formats

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1807]
In an Outlook add-in for compose mode, we are using the toLocaleDateString() and toLocaleTimeString() methods. Previously, when IE or Edge Legacy web view controls were used, these methods returned correct strings taking into account the regional settings of Windows and Outlook. Now, with the WebView2 control (Edge Chromium), we always receive date and time units in the EN-US format.

## Expected Behavior
The toLocaleDateString() and toLocaleTimeString() methods shall work correctly.

## Current Behavior
The toLocaleDateString() and toLocaleTimeString() methods return date/time units in the English (United States) format.

## Steps to Reproduce, or Live Example
1) In Windows Regional settings, set the format other than English (United States), for example English (United Kingdom).
2) Start Outlook Desktop.
3) Open the add-in's pane and execute the following code:
`    const date = new Date(1999, 0, 9);`
`    console.log('Date:', date.toLocaleDateString());`
`    const time = new Date(1999, 0, 9, 15, 30, 0);`
`    console.log('Time:', time.toLocaleTimeString());`

In the debug console you will see:
Date: 1/9/1999
Time: 3:30:00 PM

While the expected results are:
Date: 09/01/1999
Time: 15:30

* Additional details:
  1. With the IE and Edge Legacy web view controls, both methods work correctly.

## Your Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: Version 2103 (Build 13901.20400)
* Operating System: Windows 10 20H2 (OS Build 19042.928)
* Browser (if using Office on the web):

**Comment by exextoc** [comment]
I can reproduce this issue and investigating.

**Comment by exextoc** [comment]
Initial investigations seems to reveal that this value was changed to installed language of **Office** that the user has. In order to help the owning team understand the consequences of this decision (and possible solutions), how does this affect your add-in?

**Comment by DmitryKostochko** [comment]
Thank you for the investigation.

> In order to help the owning team understand the consequences of this decision (and possible solutions), how does this affect your add-in?

All our controls with date and time values show data in a wrong format. It looks very strange to users - in the inbox, you see the correct / familiar date-time value in emails, but in the add-in's pane all data is in EN-US.

And from a developer's viewpoint, it looks like breaking changes.

**Comment by DmitryKostochko** [comment]
@exextoc, sorry for bothering you, but do you have any news about the issue?

**Comment by davyarris** [comment]
I too have this issue. If the locale is derived from the Installed Office version then this results in no way to change it. Which is definitely a problem for our users. I assumed the locale for the browser (being Edge in the case of native Add-in) would be used. Accessing outlook.com obviously results in the correct behaviour (i.e. using the locale from Settings > Languages of the browser).

**Comment by davyarris** [comment]
Further information related to this issue, I attempted to obtain the correct locale from within the Add-in (inside Native Outlook), so it was using an Edge viewer. My Windows locale is set to en-AU. My Edge Browser is set to en-AU and my Office Locale is set to en-AU.. This is the results:
![image](https://user-images.githubusercontent.com/59075773/117403410-7711df00-af4b-11eb-9c75-44727be73411.png)

**Comment by Dengshan2018** [comment]
Still under the discussion. There is no solution for the issue yet.

**Comment by andymozza** [comment]
Hi, any resolution or work around for this yet? Hitting the same issue.

**Comment by Dengshan2018** [comment]
No solution so far. There is a plan in webview2 which will respect OS regional setting. Will update the schedule once it's firmed.

**Comment by tcgpatrickk** [comment]
I'm suffering the same: 
Windows is set up Switzerland/german.
Office standard installation.
WebView2 in Outlook Desktop Add-In has as primary langange code de-DE (so Germany/german)

Messes up all amount presentations ...

**Comment by Dengshan2018** [comment]
There is a fix . Will update if the fix is in Current Channel.

**Comment by Dengshan2018** [comment]
The fix is in Current Channel Preview right now: https://learn.microsoft.com/en-us/officeupdates/update-history-current-channel-preview.

Please give a try @DmitryKostochko, @tcgpatrickk , @andymozza @davyarris .

**Comment by DmitryKostochko** [comment]
@Dengshan2018, we have just tested the issue against Outlook version 2307 (build 16610.20000) Beta Channel and I can confirm the issue is resolved, thank you.

**Comment by Dengshan2018** [comment]
Thanks @DmitryKostochko for the verification. and close the issue.
