### ISSUE TITLE
MessageCompose.setSelectedDataAsync always add the text to the subject in web version

### ISSUE THREAD

**Issue by amiram** [OfficeDev/office-js#1808]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When using MessageCompose.setSelectedDataAsync, text should be inserted to the subject or body, the last one that had focus. It is not working well and the text is always added to the subject. The bug exists in the web version. The Windows version is ok. Body.setSelectedDataAsync is working fine also in web.

## Expected Behavior

Text should be added to the last part that had focus, subject or body.

## Current Behavior
Text always added to the subject.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: web
* Operating System: Ubuntu
* Browser (if using Office on the web): Chrome

## Useful logs
No error is console.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding setSelectedDataAsync API. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.
Internal tracking id: Office:2078820
