### ISSUE TITLE
`mailbox.getCallbackTokenAsync({ isRest: false })` returns different token versions

### ISSUE THREAD

**Issue by Kronenberg** [OfficeDev/office-js#1810]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

General summary: I got different tokens based on platform in my case it is IOS

## Expected Behavior
On PC windows/MAC/Android i got this token structure using `mailbox.getCallbackTokenAsync({ isRest: false })`  method 

```
appctx: "{"oid":"c73b8759-34b2-4186-aa8c-04d149dcc77a","smtp":"example@test.com","upn":"michael@gmail.com","scope":"ParentItemId:AAMkADliYTYxYmU3LWZmZDItNDc1NS05ZDJlLTEzMTEzYTcxZjJiMgBGAAAAAACD1PGbVJwsSJGpKm1YY3txBwDkoikDDyNWQYOa6euTISfZAAAAAAEMAADkoikDDyNWQYOa6euTISfZAAJgUJpDAAA="}"
appctxsender: "https://localhost:3000/@c8b54cf8-ff8f-4033-8c1b-bf5aa3235094"
aud: "00000002-0000-0ff1-ce00-000000000000/outlook.office365.com@c8b54cf8-ff8f-4033-8c1b-bf5aa3235094"
exp: 1618819791
happ: "owa"
iss: "00000002-0000-0ff1-ce00-000000000000@c8b54cf8-ff8f-4033-8c1b-bf5aa3235094"
issring: "WW"
nameid: "35c7da4b-7af9-4e1a-ac4a-a2255a8f3e36@c8b54cf8-ff8f-4033-8c1b-bf5aa3235094"
nbf: 1618819491
ver: "Exchange.Callback.V1"
```

So i expect to get same token for iOS platform but it is different:
That what i got on IOS platform.

```
  {
    "oid": "fed15ab4-8b08-4016-89be-72c3eb2a1c57",
    "puid": "100320004A272AF6",
    "smtp": "blabla@gmail.com",
    "upn": "blabla@gmail.com",
    "clientappid": "e468b405-174d-41b5-88f6-3e230307b8a6",
    "ver": "Exchange.Callback.V2",
    "appid": "00000002-0000-0ff1-ce00-000000000000",
    "deploymentid": "https://outlook.office365.com/",
    "tid": "a1957378-6999-4558-ae0f-aa8377bd1577",
    "acr": "1",
    "appidacr": "0",
    "scp": "Mail.ReadWrite Mail.ReadWrite.Shared Mail.Send Calendars.ReadWrite Calendars.ReadWrite.Shared Contacts.ReadWrite",
    "nbf": 1618822312,
    "exp": 1618823212,
    "iss": "https://outlook.office365.com/",
    "aud": "https://outlook.office365.com",
    "happ": "API"
  }
```

* Additional details:
  When Calling `mailbox.getCallbackTokenAsync({ isRest: false })` expect to see new and same token each time as i have on Android/PCNative Outlook/Mac Native Outlook. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: IOS
* Host [Excel, Word, PowerPoint, etc.]: IOS Mobile 14.4.2
* Office version number: OS Mobile 14.4.2
* Operating System: iOS
* Browser (if using Office on the web): iOS Outlook 16.45.0.0 Mobile Safari UI/WKWebView 14.4.2

## Useful logs
Here is my manifest permissions 
```
<Permissions>ReadWriteMailbox</Permissions>
<SupportsSharedFolders>true</SupportsSharedFolders>
```
I want to to know if all this staff is expected if yes can you show docs for this, if not please provide some answer.
If you need any more details please let me know.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding mailbox.getCallbackTokenAsync API. It has been put on our backlog. We, unfortunately, have no timelines to share at this point 

Internal tracking id: Office: 2079353
