### ISSUE TITLE
Excel addin, parallel sessions - "can't merge changes" message appears, changes lost in both sessions

### ISSUE THREAD

**Issue by ASamSam** [OfficeDev/office-js#1813]
I have a document opened in two browser sessions (I think it even could be opened on two different PC).
addin is activated only in 1 session.
during addin javascript code execution several things appear: 
1. the message "Can't merge changes ... reload" 
2. click reload in the second session
3. the same message appears in the session with the addin activated
4. click reload - changes done by addin are lost
5. addin seems closed automatically, disappears

## Expected Behavior
no any messages appears because there are no changes to merge from the second session

## Current Behavior
seems, the issue depends on the size of data for synchronizing, yet I don`t think it breaks the 5Mb limit.
with a significant amount of data all sessions became impacted, hard to come back to working state

in the same time, with small amount of data everything works correctly.

## Steps to Reproduce, or Live Example
here is my gist:
https://gist.github.com/ASamSam/9ff904acdb4787eedd2abdbd3501b244
1. open the same document in two browser sessions
2. activate the addon in the first one
3. click 'add sheet' button :
4. it creates two new sheets with table on each one. each table is filled with 1000 lines x 3 columns with numbers from 1 to 1000.
5. during the execution the message "Can't merge changes
Error
We couldn't merge all the changes in this workbook. You may lose your latest changes, but you need to reload the workbook to continue.
Give Feedback" - > Reload 
appears in the second session (no changes are done in real!)
6. it is a parallel session, another user knows nothing about the first session, clicks 'reload'
7. the first session became interrupted with the same "Can't merge changes..." message
8. click 'reload' 
9. changes done by the script are missed
10. addin (scriptlab window) became closed automatically  

Note, that you can play with the amount of data stored to find the moment when everything works correctly
update: it fails even with 100 lines in tables

## Context
i`m trying to make addin allowing several users to work in parallel, such behavior is not controlled and impacts ever users who did not activate the addin

## Your Environment
windows 10, google chrome browser

## Useful logs
no any logs appear in this case

**Comment by ASamSam** [comment]
sorry if the script is not accurate, were trying to reproduce the issue fastly

**Comment by gingerjia** [comment]
@ASamSam , you are really a very good tester! :)
If you can share the WAC session Id to us also, that would be very helpful! Thanks!

**Comment by ASamSam** [comment]
@gingerjia , thanks, I have some experience :)
can you tell me what is the WAC session id and how I can get it?

**Comment by gingerjia** [comment]
Steps:
1. Please click F12 to open the devTool for Chrome
2. Take actions on taskpane to repro the issue 
3. You can see the requests at Network tab, then select one of the request to get the wac session Id. 
Here is a gif for detail reference:
![howtogetsessionId](https://user-images.githubusercontent.com/62282034/115537921-ea6dec80-a2cd-11eb-86ac-0e8565e42f27.gif)

**Comment by ASamSam** [comment]
@gingerjia , ok, here is it:
b39f5d61-aa0b-4fb2-a3b2-4241a6c23136
what is the lifecycle of this id? is it stable or regenerated often?

**Comment by gingerjia** [comment]
Thanks @ASamSam! I have created a bug 5050411 to track and will back to you when have progress!

**Comment by ASamSam** [comment]
Thank you,
did small experiment - seems issue does not appear when there are no 'add page' and 'add table' - then a huge amount of lines could be stored

**Comment by gingerjia** [comment]
@ASamSam sorry for late reply as we just back from international labor vacation.
It's good to hear that the issue was resolved by removing 'add page' and 'add table'. 
And another workaround to unblock you is to add 'await context.sync()' before adding the second workbook:
<img width="460" alt="Untitled" src="https://user-images.githubusercontent.com/62282034/117310238-a8d86680-aeb5-11eb-9c1f-5b29ff7326a0.png">

This is because our co-authoring logic has some assumption for the action order and cause the merge conflict. We have work item to track it and I will discuss with our PM to priority the work.
Hope the workaround above can unblock your issues first. Thanks!

**Comment by ASamSam** [comment]
> Hope the workaround above can unblock your issues first. Thanks!
Thank you very much, will keep it in mind
