### ISSUE TITLE
Excel Js Events onDeleted and onActivated cannot be added at the same time

### ISSUE THREAD

**Issue by KrisSodroski** [OfficeDev/office-js#1814]
When adding onDeleted and onActivated events to the context.workbook.worksheets property, OnDelete is never hit.  Instead, onActived is called when a sheet is deleted, and the event "type" is set to "WorksheetActivated."  Removing the onActivated event causes onDeleted to be hit correctly.  

## Expected Behavior
onDeleted and onActived should be able to live in harmony. 

## Current Behavior
onDeleted won't be called if onActivated event is added.  Instead, deleting causes onActivated to be hit with incorrect event type.

## Steps to Reproduce, or Live Example

Place the following code in an excel addin.  

```
export class ExcelTest
{

 constructor()
{
   AddEvents(); 
}
 async Test(event: any)
    {
        console.log(event);
    }

    async AddEvents()
    {
        await Excel.run(async context =>
        {
            context.runtime.load('enableEvents');
            context.runtime.enableEvents = true;


            context.workbook.worksheets.onDeleted.add(this.Test);

            context.workbook.worksheets.onActivated.add(this.Test);
        });
    }
}

```

Delete a worksheet.  Notice that the logged event has the incorrect event type, and event "WorksheetDeleted" is never logged to the console.

Then remove the onActivated event.  Rerun the same.  Notice that "WorksheetDeleted" event is now logged correctly.

## Context

We need to handle both Activated and Deleted events.  Now, we have to handle both delete and activated in the same method, and try and figure out if the event is actually a Deleted event, by scanning all the worksheets and matching them to an internal state that we have to track them. 

If onDeleted worked, we wouldn't have to scan the worksheets and try and figure out what happened.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: N/A
* Operating System: Windows
* Browser (if using Office on the web): Chrome

**Comment by jipinshi** [comment]
Just tried locally cannot repro, it works good.

name: Blank snippet (2)
description: Create a new snippet from a blank template.
host: EXCEL
api_set: {}
script:
  content: |
    $("#run").click(() => tryCatch(run));

    async function run() {
      await Excel.run(async (context) => {
        context.runtime.load('enableEvents');
        context.workbook.worksheets.onDeleted.add(this.Delete);

        context.workbook.worksheets.onActivated.add(this.Add);


        console.log("Your code goes here");

        await context.sync();
      });
    }

    async function Delete() {
      console.log("sheet is deleted");
    }
    async function Add() {
      console.log("sheet is added");
    }

    /** Default helper for invoking an action and handling errors. */
    async function tryCatch(callback) {
      try {
        await callback();
      } catch (error) {
        // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
        console.error(error);
      }
    }
  language: typescript
template:
  content: |
    <button id="run" class="ms-Button">
        <span class="ms-Button-label">Run</span>
    </button>
  language: html
style:
  content: |-
    section.samples {
        margin-top: 20px;
    }

    section.samples .ms-Button, section.setup .ms-Button {
        display: block;
        margin-bottom: 5px;
        margin-left: 20px;
        min-width: 80px;
    }
  language: css
libraries: |
  https://appsforoffice.microsoft.com/lib/1/hosted/office.js
  @types/office-js

  office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
  office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

  core-js@2.4.1/client/core.min.js
  @types/core-js

  jquery@3.1.1
  @types/jquery@3.3.1

**Comment by jipinshi** [comment]
@KrisSodroski , I tried with chrome and edge both cannot repro. Can you confirm?

**Comment by KrisSodroski** [comment]
@jipinshi , thanks for taking a look.  

Here is a project that demonstrates the issue: 

https://github.com/KrisSodroski/ExcelJsEventExample

On another note, without this [timeout](https://github.com/KrisSodroski/ExcelJsEventExample/blob/78823144c654408829d8ed6ad535c50eaadd2cd0/src/app/Pages/Addin/Addin.ts#L8), no events are added at all it seems, despite office being loaded.

**Comment by jipinshi** [comment]
@KrisSodroski, is it possible to repro the issue in ScriptLab? it will be more easier to debug. And for Office.onReady() will ensure the js is ready, you can refer  [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/initialize-add-in).

**Comment by jipinshi** [comment]
And one difference from my sample code with yours is that I add two different callbacks for OnDeleted and onActivated. Not sure whether it has impact. Better to have scriptlab to repro.

**Comment by KrisSodroski** [comment]
@jipinshi  thanks for taking a look. 

> And one difference from my sample code with yours is that I add two different callbacks for OnDeleted and onActivated. Not sure whether it has impact. Better to have scriptlab to repro.

Hate to ask, but can you verify on your end using the above repo.  It would take me a week or so to get this in Scriptlab for you.  

In the project, onActivated, and onAdded are hit, but not onDeleted.  Commenting out onActivated, then rerunning the test case, onDeleted is then hit.  Debug statements are placed already to clearly demonstrate the issue. 

>And for Office.onReady() will ensure the js is ready, you can refer here.

Since onAdded, and (even onActivated and onDeleted do get hit, just not when placed together) work, it doesn't sound like an Office.onReady() issue to me.   The service in the repo explicitly waits for onReady(), and its not like my addin isn't working.  Its just that onActivated and onDeleted events cannot be added at the same time, or else onDeleted is ignored completely.

Swapping when the onDeleted and onActivated events are added doesn't change the outcome.  But as soon as onActivated is commented out, onDeleted is then hit with the correct arguments.  This seems to rule out a timing issue, especially since onAdded is still added last in the pipeline, but it still executes as expected.

**Comment by jipinshi** [comment]
@KrisSodroski , I tried and found that these events can works good after disable all debugger. Here is screenshot:
![image](https://user-images.githubusercontent.com/44011941/115979599-69f30880-a5b9-11eb-9124-41bcdafc4142.png)
