### ISSUE TITLE
Office.com not showing purchased add-ins in Home ribbon

### ISSUE THREAD

**Issue by KeithBook** [OfficeDev/office-js#1816]
## Expected Behavior
<I expect to see purchased add-ins in the Home ribbon when I access Word via office.com.>
I expect to see purchased add-ins in the Home ribbon when I access Word, PowerPoint, and Excel via office.com. 
## Current Behavior
<Purchased add-ins do not appear when I log into Word via office.com.->

Purchased add-ins do not appear when I log into Word, PowerPoint, and Excel via office.com.
## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by jeremy-msft** [comment]
Please ensure the add-in has loaded successfully via **Insert > My Add-ins**.  Further details can be found in the help article [here](https://support.microsoft.com/en-us/topic/get-an-office-add-in-for-excel-d3df5854-0a4e-4169-9cc3-25177a288d3d).
