### ISSUE TITLE
Enable/Disable is not working as expected.

### ISSUE THREAD

**Issue by Storygu** [OfficeDev/office-js#1817]
I use Office from this URL "https://appsforoffice.microsoft.com/lib/1/hosted/office.js"
and I have created manifest with this structure 
`<Group id="id.Group">
    <Control xsi:type="Button" id="SignIn.Button">
       <Enabled>true</Enabled>
    </Control>
    <Control xsi:type="Button" id="SignOut.Button">
       <Enabled>false</Enabled>
    </Control>
</Group>`
As you see I have Control with different stage in the same group and When user already sign in, then I set Signin button to disable and SignOut button to enable.
And When I edit value in cell all button change to Enable stage.

This is only happening in the Web version. it works fine on the Install version.

## Expected Behavior

The button should not change stage.

## Current Behavior

The button has changed to enable stage.

## Steps to Reproduce, or Live Example

1. Create Groud and add 2 Control, one is enabled and the other is disabled.
2. Change stage to all button (enable->disable & disable->enable).
3. Edit a value in any cell. 

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

When User edit value in a cell, I see that all button in ribbon change to disable stage. I think this issue relates to this behavior

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: Windows and Mac
* Browser (if using Office on the web): Google Chrome

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by JackyChen200304** [comment]
@Storygu, thanks for your feedback, it is valuable to us. Without your JS script, it's hard for us to repro and identify the issue. I suspect you are using the beta version Ribbon JS API namespace, after Ribbon API released out, it has been changed according to feedbacks. Please use Office.ribbon.requestUpdate() to update the ribbon control status.
You may checkout the sample from https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands
