### ISSUE TITLE
Outlook Desktop, setSelectedDataAsync sets incorrect color for cell borders in a table

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1818]
In an Outlook add-in for compose mode, we use the setSelectedDataAsync method that inserts HTML with incorrect result, the color is not applied to all borders of a cell.

## Expected Behavior
All borders of a cell shall have the specified color.

## Current Behavior
Please see the screenshot below.

## Steps to Reproduce, or Live Example
Create a new email in Outlook Desktop and execute the following code:
`      Office.context.mailbox.item.body.setSelectedDataAsync(`
`        '<p>Table</p>' +`
`        '<table style="width: 100%; border-collapse: collapse; border-style: solid; border-color: black;" border="1px">' +`
`        '<tbody>' +`
`        '<tr>' +`
`        '<td style="width: 50.0%; border: 1px solid red;">border: 1px solid red</td>' +`
`        '<td style="width: 50.0%; border: 1px solid black;">text</td>' +`
`        '</tr>' +`
`        '<tr>' +`
`        '<td style="width: 50.0%; border: 1px solid black;">text</td>' +`
`        '<td style="width: 50.0%; border: 1px solid black;">text</td>' +`
`        '</tr>' +`
`        '</tbody>' +`
`        '</table>',`
`        { coercionType : 'html' },`
`        function (result) { console.log(JSON.stringify(result)); }`
`      );`

As you can see, the borders of the first cell are not red.

* Additional details:
  1. The issue occurs in Outlook Desktop only, Outlook Online and Outlook for Mac work correctly.

## Your Environment

* Platform: PC desktop
* Host: Outlook
* Office version number: Version 2103 (Build 13901.20400)
* Operating System: Windows 10 20H2 (OS Build 19042.928)
* Browser (if using Office on the web):

## Useful logs
- [x] Screenshots
![ssCellBorder](https://user-images.githubusercontent.com/28924916/115720834-164ca900-a386-11eb-9508-a30d03bc6594.png)

**Comment by exextoc** [comment]
HTML in Outlook is rendered via Word, which doesn’t always behave the same as Web based HTML renders. We have made the owning team aware of this report, but it is unknown if this will be addressed.

In the meantime, it is likely you should rework the HTML to workaround this issue. Which will also have the benefit of working with older versions of Outlook/Word even if the issue is addressed.

**Comment by DmitryKostochko** [comment]
Thank you. Please let me know when you have any news from the owning team.

**Comment by exextoc** [comment]
Thanks for reporting this issue. After careful consideration, the owning team has decided to not fix this issue in the short term. We recommend you to upvote or create a new [Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue we will re-activate as needed.
