### ISSUE TITLE
Fail to obtain draft on Outlook365 groups delegated email

### ISSUE THREAD

**Issue by naemcivic** [OfficeDev/office-js#1819]
When sending on behalf of a Outlook365 group's delegated email, the draft id from Office-js can not be used to lookup for the draft with the signed in user's on graph api.

## Expected Behavior
Draft should be placed in the user's folder which could be found when using graph api with the signed in user.

## Current Behavior
It gets placed in the group's draft folder, which is not accessible by the user on graph api.

## Steps to Reproduce, or Live Example
**Successful Case**

- Open OWA
- Change "From" address to office365group@yourdgroup.ca
- Observe the draft, it gets put inside the user's draft folder, which could be found with signed in user since it's placed in the user's draft folder

**Failed Case**

Open Outlook and navigate to Preferences -> Accounts -> Advanced -> Delegates -> "Open these additional mailboxes"
Add ie: office365group@domain.com as a delegate
Change the send from to the just added group
Observe the draft, it gets put inside the group's office365group@domain.com draft folder, the draft is inaccessible using graph's service with the signed in user since it is placed in the group's draft folder.

## Context
This will interrupt our flow for delegated email sending with Office365Groups, as there are no other way of obtaining the draft from graph api's groups resource.

## Your Environment

* Platform Mac 
* Host Outlook
* Office version number: 16.46(21021202)
* Operating System: MacOS

**Comment by exextoc** [comment]
@naemcivic 

1. Are you facing this issue in New Mac Outlook or Class Mac Outlook UI? 
2. Is the Add-in trying to access the drafts item from user's Account?
3. Could you please elaborate on the Add-in scenario that you are trying to achieve?

**Comment by naemcivic** [comment]
@exextoc 

> @naemcivic
> 
> 1. Are you facing this issue in New Mac Outlook or Class Mac Outlook UI?
I am currently experiencing this on the Classic UI
> 2. Is the Add-in trying to access the drafts item from user's Account?
getting the draft ID from `Office.context.mailbox.item.saveAsync()`
> 3. Could you please elaborate on the Add-in scenario that you are trying to achieve?
using the draft_id from step two to call graph v1 api with the signed in user and trying to retrieve the draft from the user's draft folder fails.

**Comment by exextoc** [comment]
The above mentioned scenario works fine for us in New Mac UI. Can you also please try on new UI and share the feedback?

**Comment by naemcivic** [comment]
> The above mentioned scenario works fine for us in New Mac UI. Can you also please try on new UI and share the feedback?

@exextoc 
I am unable to add an Office365group to the New UI, it can only be added and utilized via the old UI. Please share the steps on how to add such groups to the new UI.

**Comment by exextoc** [comment]
@naemcivic Can you please try these steps?

Open Outlook and navigate to Preferences -> Accounts -> Delegation and Sharing -> Shared With Me -> "Open these additional mailboxes". Add ie: office365group@domain.com as a delegate"

Also, please update your app to version 16.48 if possible.

**Comment by liamtim** [comment]
@exextoc I have an Office 365 group called office365group@domain.com added to my Outlook profile. When "New Outlook" is switched off, I can see this group on the left hand pane of Outlook, along with my other accounts.

When I switch on "New Outlook", the Office 365 group is no longer in the left hand pane, and I am unable to add it via delegates. 



https://user-images.githubusercontent.com/44294661/118011916-86fc3b00-b31e-11eb-9a94-6d8a93666910.mov

**Comment by naemcivic** [comment]
@exextoc 
Unfortunately I can not add the 365groups by the way you have suggested, however when I switch back to the old UI I am able to see the group.

**Comment by exextoc** [comment]
We are not able to repro this on our end in new UI. Can you provide us a test account in which the issue is still reproducible? Also, can you remove the account from the old UI first and then try to add it again in new UI?
