### ISSUE TITLE
MessageComposeCommandSurface spec does not put button on ribbon for pop-up mail composer in "New Outlook" mode. 

### ISSUE THREAD

**Issue by james-huang** [OfficeDev/office-js#1820]
MessageComposeCommandSurface spec does not put button on ribbon for pop-up mail composer in "New Outlook" mode. Outlook 365, MacOS. 

## Expected Behavior
Ribbon button to launch popup should show while composing messages.

## Current Behavior
Ribbon button to launch popup is missing in "New Outlook" mode. 

## Steps to Reproduce, or Live Example
- Launch MacOS Outlook 365
- Toggle to "New Outlook" mode. (top right corner)
- Click "New Message"
- Option to launch addin as part of the 3 dots at the top. 
- Click "Continue message in a separate window" 
- Missing option to launch addin. 

![image](https://user-images.githubusercontent.com/990325/115917590-587bf600-a42b-11eb-8308-d8c7261444c9.png)

## Context
We have had some users give feedback that our add-in is not available in their Outlook. 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: MacOS
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 365
* Operating System: Mojave 10.14.6
* Browser (if using Office on the web): N/A

## Useful logs
![image](https://user-images.githubusercontent.com/990325/115918104-f243a300-a42b-11eb-9dab-573a7fe41056.png)
![image](https://user-images.githubusercontent.com/990325/115918218-1c956080-a42c-11eb-95f7-034913e38a0f.png)

**Comment by mscharlock** [comment]
@exextoc can you have a look? Thanks!

**Comment by james-huang** [comment]
Hi Microsoft, any updates on this?
Was this reported to the right place?

**Comment by exextoc** [comment]
We are in the process of rolling out the New Outlook UI for full mail compose, and Add-ins will be available on it. You can test it in the latest [Insiders ](https://insider.office.com/en-us/join/mac)build. We expect the feature to be generally available by mid to end June.
