### ISSUE TITLE
getSharedPropertiesAsync is undefined in shared/delegate mailbox in Outlook Mac 16.49

### ISSUE THREAD

**Issue by Coianiz** [OfficeDev/office-js#1821]
I've noticed recently that the call to mailbox.item.getSharedPropertiesAsync() is undefined when in Outlook for Mac 16.48 and 16.49. The isApiSetSupported('Mailbox', '1.8') is returning true, the selected mailbox item is in a shared mailbox, but in my add-in and in the console only see the following:

![image](https://user-images.githubusercontent.com/60905116/116155716-d262f680-a72d-11eb-9902-18accea3d0f1.png)

We released an update to our add-in towards the end of January this year and during testing it worked fine. I believe that was Outlook 16.45 (20121303) but I can't confirm because app insights doesn't quite go back to the testing phase. That version number is from the week following the release, so it's likely what we tested on.

## Expected Behavior
When in the following scenario:
* Outlook on Mac
* 365 subscription
* Mail.Read context
* Shared or delegate mailbox context
* Not using new UI
* Api set 1.8 supported

the mailbox.item.getSharedPropertiesAsync() will return the shared properties, and not undefined.

## Current Behavior
See the screenshot above, but even when the api set should be supported and in a shared or delegate mailbox the getSharedPropertiesAsync call just returns undefined.
Here's another just to show the shared mailbox context:
![image](https://user-images.githubusercontent.com/60905116/116155740-dabb3180-a72d-11eb-9191-da24b8eb059d.png)

Here's the same user accessing the same shared mailbox from Safari OWA and the call succeeding:
![image](https://user-images.githubusercontent.com/60905116/116039194-c6375480-a6ad-11eb-82e7-53c383d3b9fa.png)

## Steps to Reproduce, or Live Example
* Sign in to Outlook for Mac with a user that has delegate or shared mailbox access
* Select a mail item from the delegate/shared mailbox
* Open an add-in pane and try to call Office.context.mailbox.item.getSharedPropertiesAsync()

## Context

We use the shared properties target email address to then get the graph user id for the conversion of the itemId to a REST ID, which is failing because the email address is undefined.
So at the moment, users on Mac aren't able to use our add-in with their shared mailboxes.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.48+
* Operating System: MacOS 10.15.7 (19H524)

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
Can you try the following code snippet
`Office.context.mailbox.item.getSharedPropertiesAsync((result) => showMessage(JSON.stringify(result))); `

**Comment by Coianiz** [comment]
The same result unfortunately:
![image](https://user-images.githubusercontent.com/60905116/116830371-ef477000-abec-11eb-9b17-d52c70399bde.png)

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding getSharedPropertiesAsync API. It has been put on our backlog. We unfortunately have no timelines to share at this point.
Internal tracking id: Office: 2088338

**Comment by exextoc** [comment]
Thank you for sharing this issue. As a workaround, users can switch to the New Outlook for Mac experience which works as expected. We are not prioritizing this fix on classic Mac UI; please reopen the issue in case the workaround does not solve your scenario.
