### ISSUE TITLE
How to get CID of inline attachment

### ISSUE THREAD

**Issue by nc-ewe** [OfficeDev/office-js#1823]
Hi,
We're developing Outlook add-in for archiving emails and we're facing problems with inline attachments as we don't have a way to match attachment file with it's place in email html body. We need CID for this. Is there any way to obtain that property? We're using Office.context.mailbox.item.attachments and getAttachmentContentAsync to get information about attachments but there is nothing about cid.

**Comment by exextoc** [comment]
@nc-ewe 
Can you try the `Office.context.mailbox.item.body.getAsync` API
Example below.

`/* ReadItem or ReadWriteItem or ReadWriteMailbox */
/* Get body content */
Office.context.mailbox.item.body.getAsync("html",
 function (asyncResult) {
  if (asyncResult.status == "failed") {
   console.log("Action failed with error: " + asyncResult.error.message);
  } else {
   console.log(asyncResult.value);
  }
 }
);`

**Comment by egloff** [comment]
I am facing the same issue:
For most mails I can use the 'attachmentDetail.name' property, as it mostly matches the cid (Content-ID).
But if for example the cid does not contain the file-extension or the cid is completely different from the filename of the attachment there is not way to do the matching between cid and the attachment or am I missing something?

**Comment by Calvin-Coomer** [comment]
Upvote i amfacing the exact same issue

**Comment by exextoc** [comment]
Hi @Calvin-Coomer 
From what I understand you are trying to map the attachment list you get from attachment API to the inline attachment present in body. As this issue is already closed, can you create a new issue with exact details of your scenario so that we can help you better?
