### ISSUE TITLE
OfficeGropus and OfficeControls

### ISSUE THREAD

**Issue by VSlobolinskyi** [OfficeDev/office-js#1825]
Could you please add support in manifest.xml for OfficeGroups and OfficeControls for PowerPoint on Windows? Currently those are only supported for PowerPoint on the Web.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 540ad65e-a396-ce57-34fa-00e490028f0d
* Version Independent ID: d7807a56-e4d6-aa64-0dd8-3af677b9849d
* Content: [Group element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/group)
* Content Source: [docs/reference/manifest/group.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/group.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
I will investigate.
