### ISSUE TITLE
How can I wrap several operation into single UndoRecord?

### ISSUE THREAD

**Issue by AlexanderSokolov1** [OfficeDev/office-js#1827]
Hi team,

I have a Word add-in that needs to do some manipulation on the document and be able to undo them with one click on the undo button. In the VSTO add-in version, I am using the [UndoRecord](https://docs.microsoft.com/en-us/office/vba/word/concepts/working-with-word/working-with-the-undorecord-object) class, but it looks like there are no analogues in office-js.

Is there any plans to implement some kind of the [UndoRecord](https://docs.microsoft.com/en-us/office/vba/word/concepts/working-with-word/working-with-the-undorecord-object) in office-js for Office Word?

Thanks,
Alex.

**Comment by nancy-wang** [comment]
Great question - I've tagged @AbidRahman-MSFT who works in this space. Thanks for asking @AlexanderSokolov1 !

**Comment by AbidRahman-MSFT** [comment]
Hey @AlexanderSokolov1,

Thanks for posting your issue. Currently, we don't have any plans to introduce this capability to Office Add-ins. I highly recommend posting this feature suggestion on the [M365 Developer Platform Forums](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform).

Thanks!!
