### ISSUE TITLE
CustomFunctions.StreamingInvocation setResult() performance issue

### ISSUE THREAD

**Issue by jasonclg** [OfficeDev/office-js#1828]
## Expected Behavior
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-web-reqs#make-a-streaming-function
I was testing streaming function ```increment``` with the tutorial above. 
The interval is set at 1000ms in the example code. In my test, it's set at 1ms with incrementBy 1. 
I expected the streaming function would update the result in the workbook at the interval close to 1ms.

## Current Behavior
It looks like the update interval was throttled to ~500ms in the test, much slower than expected.
Please investigate how ```CustomFunctions.StreamingInvocation setResult()``` method impact the overall performance.
 
## Steps to Reproduce, or Live Example
```ts
/**
 * @customfunction
 * @param incrementBy Amount to increment
 * @param invocation Custom function handler
 */
 export function increment(incrementBy: number, invocation: CustomFunctions.StreamingInvocation<number>): void {
  let result = 0;
  const timer = setInterval(() => {
    result += incrementBy;
    invocation.setResult(result);
  }, 1);

  invocation.onCanceled = () => {
    clearInterval(timer);
  };
}
```
* Additional details:
1. The project was generated following this [tutorial](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-create-custom-functions?tabs=excel-windows)
2. Modify the ```increment``` method in functions.ts with above code
3. Type ```=contoso.increment(1)``` to get the streaming update in the cell
## Your Environment
* Platform:  PC desktop
* Host: Excel
* Office version number: Microsoft 365 16.0.13801.20442
* Operating System: Windows 10

## Useful logs

- [x] Screenshots
![record](https://user-images.githubusercontent.com/2009930/116297079-c5ef9580-a74f-11eb-9e2a-d6ad44acc634.gif)

**Comment by grangeryy** [comment]
Hey @jasonclg could you share with us what scenarios users want to update streaming functions every 1ms?

**Comment by jordandev** [comment]
I agree here. Real time streaming market data quotes for me would be nice to have faster than 500ms (1 ms may be pushing it 😬)

For example, RTD functions show much faster refresh speeds with recent 365 improvements (I realize these are completely different technology). Just from the examples at https://techcommunity.microsoft.com/t5/excel-blog/excel-performance-improvements-now-take-seconds-running/ba-p/1615172
 
While I find it hard to imagine the actual usefulness of this, users want it faster and it demos well. We have clients using RTD functions from competitors that will find custom functions to just look slower for similar use cases. RTD has a throttle interval so it would be nice  if custom functions could go faster if wanted (yes it may be at the expense of some performance). A similar throttle setting would be nice to have if feasible?

**Comment by grangeryy** [comment]
Thx for the details! I think the ideal here is to make streaming Custom Functions refresh more frequently with faster calculation. Currently based on existing usage pattern, for most cases, 500ms can fulfil most of the scenarios. I've create a backlog for the new ask based on the information above: FEATURE 5067197

**Comment by jasonclg** [comment]
Hi @grangeryy 
I echo with the points shared by @jordandev; especially the example of the performace boost from RTD.
Please keep us posted on the progress of bringing the refresh improvement to custom function.

Thanks!

**Comment by jasonclg** [comment]
Hi,
Is this issue still being tracked?

**Comment by SiruiSun-MSFT** [comment]
Hi @jasonclg, sorry for the late response. Unfortunately, this feature is still in the backlog. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). If this feature still blocks your customers, please also add your request there. Feature requests are considered when we go through our planning process. It would be better if you could provide the scale of affected users, it will help us re-prioritize this feature. Thanks for your patience!

**Comment by jasonclg** [comment]
@SiruiSun-MSFT thanks for the reply, I submitted the idea [there](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/faster-update-rate-for-streaming-functions/idi-p/3849542).

**Comment by adrianwu8516** [comment]
Hi @jasonclg, thank you for submitting your feature request to our Idea Forum, we will keep track of the discussion and upvote on the [post](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/faster-update-rate-for-streaming-functions/idi-p/3849542) and prioritize them properly. Thank you for your valuable suggestion.
