### ISSUE TITLE
Office.context.document.getTaskFieldAsync returns wrong result for MileStone in Project

### ISSUE THREAD

**Issue by nnyegaard** [OfficeDev/office-js#1829]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

The data I get back on a task when using add-ins don't match the data in project (Or VSTO)

## Expected Behavior

`Office.context.document.getTaskFieldAsync()` should return true, when called with `Office.ProjectTaskFields.Milestone` on milestones.

## Current Behavior

`Office.context.document.getTaskFieldAsync()` returns false, when called with `Office.ProjectTaskFields.Milestone` on milestones.

## Steps to Reproduce, or Live Example

* Link to video: [Loom video](https://www.loom.com/share/660f8cc707db4e8ab55aac0b00cc7c1c)
* Create a new Plan in MS Project
* Create a new task
* Create a new milestone
* Call the method `Office.context.document.getTaskFieldAsync()` with `Office.ProjectTaskFields.Milestone` on the milestone
* Results are false

## Context

I want to read the plan in Project to sync the state with an external app.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Project 2019
* Office version number: Microsoft Project 2019 MSO (16.0.13127.21452)
* Operating System: Windows 10
* Browser (if using Office on the web): X

**Comment by mscharlock** [comment]
@BeReasonable based on this being related to Project, can you have a look? Thanks!

**Comment by nnyegaard** [comment]
Hey @mscharlock, do you have any updates? Atm we are going down the path of VSTO, but with the focus on .NET 5 from Microsoft, it feels like this approach is not that viable since we have to relay on the .NET Framework

**Comment by JBoman32768** [comment]
Have confirmed @nnyegaard result.

In addition to the Milestone field the "Active" and "Summary" fields also always return False.  Perhaps same root cause?

**Comment by JBoman32768** [comment]
"Not planned" isn't probably a good resolution for this one.  I logged this via Microsoft Support case #32728393 and the bug in Project was corrected 👍

**Comment by gergzk** [comment]
thanks @JBoman32768 !
