### ISSUE TITLE
Settings.SaveAsync() not persistent when used in PowerPoint Online

### ISSUE THREAD

**Issue by ndeeH** [OfficeDev/office-js#183]
We failed at store validation because the Settings API is not working as expected in PowerPoint Online.

- Create a new presentation with PowerPoint Online
- Add an Add In with use of Settings API to save a value

**Example:**
```
var mySetting = new Date().toString();
Office.context.document.settings.set("MySetting", mySetting);
Office.context.document.settings.saveAsync(function (asyncResult) {
    console.log('### Settings saved with status: ', asyncResult.status, asyncResult.error);
});
console.log("### Saved MySetting: " + mySetting);
```
- asyncResult.status says "succeeded"
- Save the document (done other changes in the slide to force auto-saving)
- Close document
- Trying to get the value when loading the document again:

```
Office.initialize = function (reason) {
    $(document).ready(function () {
        try {
            var mySetting = Office.context.document.settings.get("MySetting");
            console.log("### Loaded MySetting: " + mySetting);
...
```

**Console-Output**:
`### Loaded MySetting: null`

**The setting has NOT been saved with the document!**

_The Setting API seems to have a bug in this context (PowerPoint Online?)_

**Comment by ndeeH** [comment]
Please validate this issue and tell me if it is a bug. We have to know this for our store validation!
(You could have our manifest to try it out)

**Comment by JuaneloJuanelo** [comment]
quick question is this a content add-in or a task pane Add-in.  I am able to repro on content add-ins.

**Comment by weird-dreams** [comment]
It is a Content Add In for PowerPoint. 
I could send you my manifest via PM to see the failure in my context.

**Comment by ndeeH** [comment]
Yes! It is a content add in. Thanks for reproducing!  
Could you please tell me the internal VSO bug nr for the tester. TIA.

**Comment by JuaneloJuanelo** [comment]
this issue is now fixed !

**Comment by ndeeH** [comment]
We see great Improvements in PowerPoint Online - seems that actual many things concerning presentation mode and display of content add ins is revised. 👍 
We tested this issue and can confirm that it is fixed.
