### ISSUE TITLE
js excel addin charts.add method issue in Web Office (365)

### ISSUE THREAD

**Issue by kotanda** [OfficeDev/office-js#1830]
!
## Expected Behavior
charts based on a two-column range and created from excel UI  and by js API should be the same

## Current Behavior
charts based on a two-column range and created from excel UI and by js API have a different view - chart created by js API interprets source range in a wrong way - it uses it in kind an opposite way and swap column and row data

## Steps to Reproduce, or Live Example
repro steps for scriptLab 
1. open script lab and find "create charts" example 
2. press the "create table" button in the scriptLab menu
3. remove all columns from the table but the first two 
4. press the "create a line chart" button in the script lab menu 
5. then select the range of table (A1:B7) and add a chat by the classic way - insert -> linear diagram 
5.1 - also try to press "switch row/column" for one of the charts to see that they can be the same.

I know, my explanation of repro steps not really clear, so, please follow the link and see a short demonstration
* Link to live example: --[my demonstration](https://recordit.co/XPHxzm6Qqe)  --  https://recordit.co/XPHxzm6Qqe

https://stackoverflow.com/questions/67264258/js-excel-addin-charts-add-method-issue/67275779#67275779

## Context
it makes the charts not enough predictable, also I can not force users to switch column/row manually for each diagram

## Your Environment

* Platform: Office on the web
* Host: Excel
* Office version number: Office 365  // Excel build 16.0.14026.31875
* Operating System: Windows / Mac
* Browser (if using Office on the web): Edge/Chrome/Opera (not sure about the others, did not test)

## Useful logs
![chartsIssue](https://user-images.githubusercontent.com/7734704/116372585-36acb580-a815-11eb-860a-8628ae8454f1.PNG)
)

**Comment by jipinshi** [comment]
My edge and chrome(Version 90.0.4430.93 (Official Build) (32-bit)) are latest version, they both cannot repro. So may I know the version of your repro browser for chrome @kotanda

**Comment by kotanda** [comment]
hi, of course, here is mine ---
Win OS -- 
chrome -- Version 90.0.4430.93 (Official Build) (64-bit) // 
edge - Version 90.0.818.49 (Official build) (64-bit) // 
opera - 76.0.4017.94 (Win 10 64-bit) // firefox - 88.0 (64-bit) //
Mac OS -- 
safari - Version 14.0.3 (15610.4.3.1.7, 15610) //
chrome - Version 90.0.4430.93 (Official Build) (x86_64) //

---
p.s. I checked all cases these cases before sending this message

**Comment by kotanda** [comment]
> My edge and chrome(Version 90.0.4430.93 (Official Build) (32-bit)) are latest version, they both cannot repro. So may I know the version of your repro browser for chrome @kotanda

hi @jipinshi  , of course, here is mine ---
Win OS --
chrome -- Version 90.0.4430.93 (Official Build) (64-bit) //
edge - Version 90.0.818.49 (Official build) (64-bit) //
opera - 76.0.4017.94 (Win 10 64-bit) // 
firefox - 88.0 (64-bit) //
Mac OS --
safari - Version 14.0.3 (15610.4.3.1.7, 15610) //
chrome - Version 90.0.4430.93 (Official Build) (x86_64) //

p.s. I checked all these cases before sending this message

**Comment by lumine2008** [comment]
Thanks, a bug (5072600) was created to track this issue.

**Comment by MiaofeiWang** [comment]
@kotanda Thanks for reporting this. It is a known issue and we are actively fixing it (local fix ready). 
Before the fix ready for Production, can you try the workaround: selecting the range before adding chart? Sample code below:
` let dataRange = sheet.getRange("A1:E7");`
`dataRange.select();`
`let chart = sheet.charts.add("Line", dataRange, "Auto");`

**Comment by jipinshi** [comment]
Close the case now, if you have further requirement, please open a new one.
