### ISSUE TITLE
Name range value on a Mac Excel different from Windows Excel with R1C1 enabled

### ISSUE THREAD

**Issue by derek-vena** [OfficeDev/office-js#1831]
In our add-in, we want to check if the template is opened with R1C1 reference or A1 reference. We want to prevent the user from using our addin when R1C1 reference style is enabled. To achieve this, we have 2 possible solutions. When it's an empty template, we add a new name range and check the value of it where we would expect something like this (`Sheet1!$A$1` vs `Sheet1!R1C1`). Or if the template already comes with named items, we also check the value of the named item and expect a result similar to the previous example. Lately, we have noticed that on Mac Excel, the values always show up as `Sheet1!$A$1` whether we have R1C1 reference enabled or not. 

## Expected Behavior
When R1C1 reference style is enabled, we should be getting an R1C1 refence style value on Mac
When A1 reference style is enabled, we should be getting an A1 reference style value on Mac (this part is currently working)

## Current Behavior
When R1C1 reference is enabled on a Mac Excel, A1 style values are being returned

## Steps to Reproduce, or Live Example
this first example is when a template is empty
https://gist.github.com/derek-vena/6f4badfa0b80325416e6c5cb4e232e7c

this second example requires that the file has at least 1 name item present
https://gist.github.com/derek-vena/6861b80d1f3e6ddd341397e45640e599

## Context
Our add-in works best in A1 style reference and we want to show an error message when the template has R1C1 reference style enabled

## Your Environment
This issue only happens on Mac Excel at the moment, we know that this was a recent issue as our code was working as recently as a few weeks ago

**Comment by mscharlock** [comment]
@lumine2008 Do you mind having a look at this? Thanks!

**Comment by honxmsft** [comment]
Can you share more information about your Excel Mac build? You can find them in Excel > About Microsoft Excel.

**Comment by derek-vena** [comment]
@honxmsft 
![image](https://user-images.githubusercontent.com/83288408/117457384-2aacac00-af17-11eb-923b-d05ebfd17ca7.png)

**Comment by derek-vena** [comment]
@honxmsft 
![image](https://user-images.githubusercontent.com/83288408/117457564-5465d300-af17-11eb-9af2-781574e9829c.png)

**Comment by jipinshi** [comment]
5095340 was recorded to track the issue.

**Comment by lumine2008** [comment]
Thanks, @derek-vena , the team is doing the investigation, this issue is triggered because of our recent bug fix, we fix the behavior. 

Looks like you are using this to detect the R1C1 setting, so the correct approach is that we build this API for you. API work item (#5100669) is created. 

before we build this API, we would like to learn your feedback for the following questions:
- Is R1C1 a commonly used by your customer?
- What's the scenario that customer is using R1C1?
- What's the priority of this bug in your view?

**Comment by derek-vena** [comment]
@lumine2008 Thank you for the update

1. R1C1 not commonly used by our customer, but it is something that we want to prevent our user to have on when they are using our add-in. In the current behaviour of our add-in, when the R1C1 reference style is detected, we throw an error screen and force the user to update the reference style before they can continue.
2. Since this is a mac only issue, I would say that the priority is a medium

**Comment by lumine2008** [comment]
Here are priority definitions, would you please let us know which is the right one for you?

- P1 - Blocker
- P2 - Critical
- P3 - Major 
- P4 - Minor

**Comment by derek-vena** [comment]
This is a P4-Minor issue on our end

**Comment by derek-vena** [comment]
@lumine2008 I have just confirmed that this issue is now affecting Windows Excel as well, the code block I posted originally no longer works on Windows Excel now

**Comment by lumine2008** [comment]
@derek-vena , we fixed the issue, would you please validate, see if you can repro this issue? thanks

**Comment by derek-vena** [comment]
@lumine2008 we just tried the issue on both Mac and Windows with the latest available Excel version and was still able to reproduce the issue with the provided code block.

Here's the Mac version we tested on 
![image](https://user-images.githubusercontent.com/83288408/121455394-63a2cb00-c972-11eb-901a-31fc6a6a2302.png)

And here's the Windows version
![image](https://user-images.githubusercontent.com/83288408/121455469-82a15d00-c972-11eb-8f30-fb2dbafd67b8.png)

**Comment by derek-vena** [comment]
@lumine2008 can we gett an update on this?

**Comment by lumine2008** [comment]
the fix is on the way to rolling out, you may check the monthly channel in July.

**Comment by honxmsft** [comment]
I've tested on the version 2108 (Build 14326.20304) and the fix is there. Maybe we can verify it again.

**Comment by gingerjia** [comment]
Close it as the fix has been rolled out to PROD. 
Please let us if have any new issues. Thanks!
