### ISSUE TITLE
Outlook Desktop, MessageCompose.from.getAsync() returns incorrect data in case of shared mailbox

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1832]
In an Outlook add-in for compose mode, we use the from.getAsync() method to get the email address of the message sender. If you reply to an existing message located in a shared mailbox, the from.getAsync() method returns your primary email address instead of the email address of the shared mailbox.

## Expected Behavior
The from.getAsync() method shall return the email address of the shared mailbox. BTW, in Outlook for Mac it works fine.

## Current Behavior
The from.getAsync() method returns the user’s email address but not shared mailbox’s.

## Steps to Reproduce, or Live Example
1) Select any existing email in a shared mailbox and click Reply or Reply All.
2) Note, the correct data is shown in Outlook’s Form field, you can see the display name or email address of the shared mailbox there.
3) Open the add-in’s pane and execute the following code:
`    function getFrom() {`
`      // document.getElementById("output").value = '';`
`      Office.context.mailbox.item.from.getAsync((result) => {`
`        console.log(JSON.stringify(result));`
`        // document.getElementById("output").value += JSON.stringify(result) + '\r\n';`
`      });`
`    }`

As you can see, the user’s primary email address is returned.

 Additional details:
  1. The code above works correctly in Outlook for Mac.
 
## Your Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: Version 2103 (Build 13901.20462)
* Operating System: Windows 10 20H2
* Browser (if using Office on the web):

**Comment by mscharlock** [comment]
@exextoc do you mind having a look at this issue? Thank you!

**Comment by exextoc** [comment]
There appears to be a difference in behavior between Windows Outlook and Mac Outlook when it comes to items from Shared Folders. In Windows Outlook, whenever a user creates a new message or a reply, it resides in the primary mailbox that the Shared Folder was shared with. That is why the `from.getAsync` returns the email address of the primary mailbox. In other words, the new item is not in the Shared Folder.

If you place a draft email in the Shared Folder, you can retrieve the email address of the owner of the Shared Folder by calling `Office.context.mailbox.item.getSharedPropertiesAsync`. More information here : https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access

PS : We don't officially support Shared Mailboxes. We, however, support Shared Folders. I think your post is about Shared Folders. Please correct me if I'm wrong.

**Comment by DmitryKostochko** [comment]
Thank you for explaining the difference in behavior between Windows Outlook and Mac Outlook. 

However, the problem is when the user replies to an existing email in a shared folder in Windows Outlook, they see the correct data in Outlook's From field, but the Office JS API returns incorrect data. I believe the data the user sees and the data the from.getAsync method returns should be the same, otherwise a confusion is inevitable.

**Comment by exextoc** [comment]
When a new reply is created, that reply is created in the primary mailbox of whoever created that reply, not the shared folder. The `from.getAsync` API uses the primary mailbox, so that is why you are getting that user's information. The From field in Outlook reflects the owner of the shared folder, not whoever created the reply. I will open a documentation bug to clarify this in our documentation for the `from.getAsync `API.

**Comment by DmitryKostochko** [comment]
> When a new reply is created, that reply is created in the primary mailbox of whoever created that reply, not the shared folder. The from.getAsync API uses the primary mailbox, so that is why you are getting that user's information. The From field in Outlook reflects the owner of the shared folder, not whoever created the reply.

@exextoc, I hope you understand that if you do not correct this behavior, the from.getAsync will be absolutely useless in a case of a shared folder in Windows Outlook. After all, we have no other way to get the real sender in this case, right?

**Comment by exextoc** [comment]
This information has been passed to the appropriate product team and is currently being investigated. We will update the issue when we have more information.

**Comment by DmitryKostochko** [comment]
Thank you!

**Comment by exextoc** [comment]
@DmitryKostochko - We have fixed the bug and the fix should be available in build > 16.0.14128.10000 or later. When an updated build is available depends on the release channel a customer is on.

**Comment by DmitryKostochko** [comment]
Wow! Thank you! I will retest the issue and let you know.

**Comment by DmitryKostochko** [comment]
I have tested the issue with Outlook Version 2107 (Build 14204.20006) Insider, the bug is not reproducible, thank you! Nevertheless, I will retest the issue again, when Outlook Current Channel gets this update.
