### ISSUE TITLE
Office.context.auth undefined

### ISSUE THREAD

**Issue by puentesdiaz** [OfficeDev/office-js#1834]
We are develop a Project Addin with React Node (yeomen) on Windows 10 with Microsoft Project Professional 2019  (Version 2103 )( Build 13091.20462) 

We can use some object and functions like:
`  Office.context.requirements`
` Office.context.document.getTaskFieldAsync`
  
But . Office.context.auth is undefined

In our taskpane.html we use :

`    
    <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>`

When a client open his MsProject, need chosee a Profile to login with a credentials oof Active Directory ... No problem there...
So, when open a file a load our addin , web need get this domain/user (from Credentials of Active Directory

How do you recommends solve this challenge? is Office.context.auth our simplest path or you have some another ideas?

#office-addin

**Comment by mscharlock** [comment]
Hi @BeReasonable - do you mind having a look at this issue? Thank you!

**Comment by ElizabethSamuel-MSFT** [comment]
@puentesdiaz Are you still able to repro this?

Thanks.
