### ISSUE TITLE
Latest Excel/Edge update separates the localStorage for dialog and taskpane although they are from the same origin

### ISSUE THREAD

**Issue by nikhilism15** [OfficeDev/office-js#1835]
I have a working Excel Add-In in production and with the latest update of Excel the add-in suddenly breaks because the dialog's functionality depends on using the localStorage that has entries created from the taskpane.

There are only a few ways to communicate between dialogs and taskpanes - query string parameters (while opening the dialog), localStorage and sessionStorage. Separating the instances cripples the functionality and only enabled query string parameters. 

Please give us a bugfix of some sort, or give us a different option to communicate with the dialog. I don't understand why localStorage has to be separated between the dialog and the taskpane.

**Comment by mscharlock** [comment]
Hi @lumine2008, do you mind looking at this request? Thank you!

**Comment by AlexPhilippov** [comment]
I think we have a different issue but for similar reasons. After the engine was updated to WebKit, the behavior of displayDialogAsync has changed. Before the update, each new dialog has its own javascript environment, specifically, cookies weren't shared between calls. Now cookies are preserved and it requires changes in our auth flow. I didn't find any info in the documentation on that. It should be mentioned somewhere at least.

**Comment by nikhilism15** [comment]
Here are further details on it:

Excel version:

![Excel version](https://user-images.githubusercontent.com/11223765/116972865-4aef2780-acd9-11eb-8bc8-b0e569a32bfc.png)

Office 365 version:

![Office 365 version](https://user-images.githubusercontent.com/11223765/116972890-53dff900-acd9-11eb-8d79-c125d3042f05.png)

Dialog and taskpane are two different HTMLs in different folders in the same website but they do not share localstorage. I have screenshots of that too if you like to see it.

**Comment by nikhilism15** [comment]
https://github.com/OfficeDev/office-js/issues/1741#issuecomment-832363275

This comment is the fix for the issue. @Dengshan2018 thank you for fixing the issue.
