### ISSUE TITLE
Outlook on the web: Attachments can be added while the On-Send add-in is running

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#1836]
When the OnSendAddinsEnabled flag is True, clicking the Send button locks the screen, but allows you to add attachments at that time.

## Expected Behavior

Attachments cannot be added.

## Current Behavior

Attachments can be added.

## Steps to Reproduce, or Live Example

1. Click the Send button on the pop-out window
2. Add an attachment while the On-Send add-in is running

## Context

If you locked the screen by displaying a dialog, the issue did not occur.

I think it is useful to be able to lock without displaying a dialog.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 20210426004.07
* Operating System: Windows 10
* Browser (if using Office on the web): Edge 90.0.818.49

## Useful logs

``` ts
function action(event: Office.AddinCommands.Event) {
  const message: Office.NotificationMessageDetails = {
    type: Office.MailboxEnums.ItemNotificationMessageType.InformationalMessage,
    message: "Performed action.",
    icon: "Icon.80x80",
    persistent: false
  };

  let cnt = 0;

  // Show a notification message
  setInterval(() => {
    Office.context.mailbox.item.notificationMessages.replaceAsync("action", {
      ...message,
      message: ++cnt + " seconds elapsed."
    });
  }, 1000);

  // Be sure to indicate when the add-in command function is complete
  setTimeout(() => {
    event.completed({allowEvent:true});
  }, 1000 * 10);
}
```

https://user-images.githubusercontent.com/58804032/116663520-bdcd6b00-a986-11eb-9ec8-dbf9d925f7aa.mp4

**Comment by mscharlock** [comment]
@exextoc Hi there! Do you mind having a look at this? Thank you!

**Comment by exextoc** [comment]
Can you tell us if you are using any On Send add-in and if the add-in has any logic to block the send.

**Comment by clavx** [comment]
We have installed only one On-Send add-in.
The add-in passes a send event after 10 seconds, as shown in the code above.



> If you locked the screen by displaying a dialog, the issue did not occur.

This is done with the following code. It is based on the code generated by generator-office.

``` ts
let _dialog: Office.Dialog;

function action(event: Office.AddinCommands.Event) {
  Office.context.ui.displayDialogAsync(location.origin + "/dist/taskpane.html", {
    displayInIframe: true,
    width: 20,
    height: 40,
  }, (ret) => {
    _dialog = ret.value;
  });

  setTimeout(() => {
    _dialog.close();
    event.completed({allowEvent:true});
  }, 1000 * 10);
}
```

**Comment by exextoc** [comment]
@clavx Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.
Internal tracking id: 117708

**Comment by clavx** [comment]
I have checked the current status.
The issue seems to be unresolved.

If the current state is the expected behavior, please specify it in the document.

https://user-images.githubusercontent.com/58804032/140282127-21de3eb4-710c-46f7-b48f-58cc0812d478.mp4
