### ISSUE TITLE
Outlook on the web: Send Later feature error in using On-Send add-in

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#1837]
When the OnSendAddinsEnabled flag is True, sending the email from the "Send Later" feature after composing an email will result in an error.

## Expected Behavior

It can be sent without error.

## Current Behavior

Unable to send due to an error.
It is necessary to perform the send operation again from the pop-out window.

## Steps to Reproduce, or Live Example

1. Compose an email
2. Send the message using the Send Later feature

If the OnSendAddinsEnabled flag is True and the On-Send add-in is installed, it will automatically pop out.

If you use the Send Later feature from the pop-out window, this issue does not occur.

https://user-images.githubusercontent.com/58804032/116664217-b0fd4700-a987-11eb-94e2-565d137496c7.mp4

## Context

If you set the OnSendAddinsEnabled flag to True, you will be forced to go to the pop-out window and will have to perform the send operation twice.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 20210426004.07
* Operating System: Windows 10
* Browser (if using Office on the web): Edge 90.0.818.49

**Comment by mscharlock** [comment]
Hi @exextoc - do you mind having a look at this issue? Thank you!

**Comment by exextoc** [comment]
When you have on send add-ins installed, Send Later option should be disabled. However, I can see that it is enabled in your case. Are you facing this issue only for Send Later option or Send option also?

**Comment by clavx** [comment]
This issue occurs only with the "Send Later" option.

I understand that the Send Later feature allows you to specify the date and time to send, and the Undo send feature allows you to cancel while sending.

I have confirmed that the Undo send feature does not work in the pop-out window.

https://user-images.githubusercontent.com/58804032/117258289-51e27b00-ae3c-11eb-934b-91ce0e1bf530.mp4

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
@clavx We are no longer able to reproduce it. Are you still able to reproduce it and is this issue seen only in OWA or also seen in other platforms (Specifically Win32 Outlook or Mac)?

**Comment by clavx** [comment]
Thank you for letting me know.

This issue only affects OWA.

I have confirmed that this issue has been solved.
I have also confirmed that the **Undo send** function works when sending from the pop-out window.

Thank you.

**Comment by exextoc** [comment]
Thank you for the confirmation. Closing this issue.
