### ISSUE TITLE
Outlook on the web: Uploading does not proceed after the pop-out window opens

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#1838]
If you click the Send button while uploading an attachment, the upload will not proceed.

## Expected Behavior

Uploading proceeds.

## Current Behavior

Uploading does not proceed.

## Steps to Reproduce, or Live Example

1. Compose an email
2. Click the Send button while uploading an attachment

If the OnSendAddinsEnabled flag is True and the On-Send add-in is installed, it will automatically pop out.

https://user-images.githubusercontent.com/58804032/116664710-5b756a00-a988-11eb-81ea-9f219a2bffd2.mp4

## Context

It can be reproduced by opening the pop-out window by yourself, so I think it is a problem of OWA itself.

If the OnSendAddinsEnabled flag to true, you are more likely to encounter this issue because it forces you to go to the pop-out window.
If the OnSendAddinsEnabled flag is false, you will not encounter this issue unless you click the "Open in new window" button to open the pop-out window yourself.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 20210426004.07
* Operating System: Windows 10
* Browser (if using Office on the web): Edge 90.0.818.49

**Comment by mscharlock** [comment]
Hi @exextoc - do you mind having a look at this? Thanks!

**Comment by exextoc** [comment]
We are unable to reproduce this issue at our end. Could you please tell us more about your on send add-ins?
Does this happen only when you install any on send add-ins or does it happen even when just the flag OnSendAddinsEnabled is set to true without any on send add-ins installed?

**Comment by clavx** [comment]
The issue is that if you open the pop-out window during an upload, the upload will not progress and you will not be able to send.
And you will not be able to delete the attachment even if you perform the delete operation, but you will be able to send it in that state.

If the OnSendAddinsEnabled flag is True and any On-Send add-in is not installed, clicking the Send button will not automatically pop-out the window, so this will not occur. However, you can reproduce it by opening the window yourself.

https://user-images.githubusercontent.com/58804032/117425346-3ea1df00-af12-11eb-84b3-32ad788bd5ba.mp4

**Comment by exextoc** [comment]
Thanks @clavx for clarifying this again. It looks like this bug is reproducible even with just simple mail compose pop-out and no addin. Since, this is not extensibility (addin) related, we will ask OWA team to look into this internally.

**Comment by ajays-msft** [comment]
This issue has been fixed. Thank you for raising the issue and helping us make the product better.
