### ISSUE TITLE
PowerPoint Online: Preview Thumbnails do not update when add in uses iFrame

### ISSUE THREAD

**Issue by ndeeH** [OfficeDev/office-js#184]
Simply add the Microsoft Add In **WebViewer** in PowerPoint Online and press preview.
In the slide the Wikipedia site is shown - the preview thumbnail shows an emtpy add in:
![image](https://user-images.githubusercontent.com/11518242/42215649-67caad98-7ebf-11e8-8d10-52a48403e018.png)

**So Content Add Ins in PowerPoint Online that use iFrames are not be rendered properly in the thumbnails of the slides.** 
_Please could you double-check if this is a bug._

**Comment by ndeeH** [comment]
Please could you verify if this is a bug in PPT Online.

**Comment by JuaneloJuanelo** [comment]
unfortunately this is how ppt works as of now. we cant refresh.

**Comment by ndeeH** [comment]
unfortunately this was nagged by the store validation tester as a failure in our add-in
@JuaneloJuanelo

**Comment by ndeeH** [comment]
@JuaneloJuanelo Seems the developers are working on this.
In latest Chrome-Version we see a bitmap-overlay that seems to be used to proper update the thumbnails.

Unfortunately it does not work correct with most content add ins - see example screenshot;
![image](https://user-images.githubusercontent.com/11518242/45422689-404b7400-b691-11e8-8adc-d67723517407.png)

**Comment by ndeeH** [comment]
@JuaneloJuanelo 
Tested in all current browser versions.
Seems the content add ins now create bitmap overlays in the online version of powerpoint.
They are not proper placed when draging the content add in frame.

The thumbnails of the slides that are using content add ins with iFrames are not correct.
