### ISSUE TITLE
Text doesn't fit to rows when merged and shapes move when text is deleted.

### ISSUE THREAD

**Issue by timbeese** [OfficeDev/office-js#1840]
If you enter multi-line text with wrapText on, but it lives in a merged cell, the text doesn't wrap properly, and then when you clear the contents of that cell, any shapes in your document get shifted upwards.

This only happens in the Excel web client.  I was unable to reproduce this in the desktop client.  I have steps that reproduce the issue outside of our add-in using ScriptLab.

## Expected Behavior
I would expect the multi-line shape to wrap its text and increase the size of the row where it is located, and for the shape to remain where it was when the other cells are cleared.

## Current Behavior
The wrapped text only displays the bottom row, and when I clear the range, the shape moves in the worksheet.

## Steps to Reproduce, or Live Example
1. Open a new Excel document on the web, and choose Insert->Shapes->{I picked a square}

2. The shape got inserted in the middle of my screen, floating over H16:I21

3. Next, I select K15 and L15 and merge them across, then run the following code in ScriptLab to put content there.

`async function run() {
  await Excel.run(async (context) => {
    const range = context.workbook.getSelectedRange();
    range.values = [['Simple Sparkline in a list table', '']];
    range.format.font.name = "AvenirNext";
    range.format.font.size = 13.5;
    range.format.wrapText = true;
    range.getEntireRow().format.autofitRows();
  });
}
`

4. Here's what my document looks like at this point.  Notice that the rows didn't autofit, only the tail end of my text is visible.
![image](https://user-images.githubusercontent.com/16708768/116733455-1ec26680-a9ba-11eb-8aa5-6e03e8d04405.png)

5. I make sure that my K15:L15 merged range is still selected and then I run the following code in ScriptLab to clear the content that I put there.

`async function run() {
  await Excel.run(async (context) => {
    const range = context.workbook.getSelectedRange();
    range.clear(Excel.ClearApplyTo.all);
  });
}`

6. When I run this, my content goes away, but watch the shape, it gets moved up in the worksheet by about 5 rows.  It now sits from H11:I16
![image](https://user-images.githubusercontent.com/16708768/116733685-647f2f00-a9ba-11eb-9888-1d0c1e750623.png)

7. If I click on the shape, notice the focus rect still marks the correct location for the shape though:
![image](https://user-images.githubusercontent.com/16708768/116733844-98f2eb00-a9ba-11eb-9bd1-6f7fedfe0d53.png)

8. After this if I enter text in the document or click the shape to move it, it does snap back to the original location.

## Context
Our add-in creates tables, graphs, and titles in the worksheet based on reports that are generated by our add-in.  We noticed this issue when we inserted an element with a title that spanned multiple cells.  When we removed it from the worksheet, some of the images that we had inserted into the worksheet were affected.

## Your Environment
I only experience this issue with the Excel web client, and I'm running in Chrome (90.0.4430.93).  I'm on a Windows 10 PC

**Comment by mscharlock** [comment]
@lumine2008 Can you have a look at this issue? Thanks!

**Comment by jipinshi** [comment]
@timbeese, I can repro the issue, 5072600 was reported to track the issue.

**Comment by jipinshi** [comment]
For the merged cell autofit cannot work now, maybe you can do autofit for one cell first, and then merge two cells first to unblock first.

**Comment by timbeese** [comment]
We'll look into workarounds for the issue.  Thanks for the update.

**Comment by jipinshi** [comment]
For the other one shape moved issue, 5089360 is used to track the issue

**Comment by jipinshi** [comment]
@timbeese. I also found the shape issue is related to postion, if you move the shape align with the cell top line, then the issue won't repro, it can be unblocked by this, for the bug itself, we are investigating.

**Comment by jipinshi** [comment]
Close the issue, have used bug to track the issue itself, if have further question, please open new or active this one, thanks.

**Comment by keyur32** [comment]
re-opening this issue since bugs are active and marking fix pending.

**Comment by jipinshi** [comment]
@keyur32, the code to do the fix is ready locally, and is going through checkin process. I think it needs time to be released to the latest monthly build. Will let you know when it is done. As for workaround, I think you can put the shape a little higher the cell to unblock or try to not use the combined cells to do the autofit.

**Comment by lynneosmith** [comment]
@keyur32 @jipinshi Is there an update on the fix you mentioned above? Thanks!

**Comment by jipinshi** [comment]
@lynneosmith , can you verify whether it repros now? Currently suppose the bug has been fixed and I cannot repro it in production.

**Comment by lynneosmith** [comment]
@jipinshi The shape is no longer jumping, however the problem with the text that Tim describes is still there. I see it on the web client only. The text displays the ending part of the text string. On the desktop Excel client, the text correctly displays the beginning of the text string.

**Comment by gingerjia** [comment]
@lynneosmith, thanks for returning back and update the issue! 
I will look into the problem and update to the thread when have progress. Thanks!

**Comment by gingerjia** [comment]
@lynneosmith, after further investigation we found the issue has been there since O14, and API behavior is same as UI design. We cannot quickly fix it in short time as the code impact is big. 
Here we provide workaround to unblock your side work first:
https://gist.github.com/yuc014/fcb190de4032f710ae3094f1718d7a9f
If this doesn't work for you, please let us know. We will try to explore further to see if any other suitable solutions for you.
Thanks again for your patience and questions!

**Comment by lynneosmith** [comment]
Having to measure the text is not ideal. We realize there have been issues with wrapping, merged and autofit to cell height for a while, but what we would like is for Excel on the web to have the same behavior with the text in this situation that Excel desktop does. 
On Excel on the web:
- In a new worksheet, go to a cell and enter this text "This is a very long string of text that will wrap multiple times"
- In the ribbon,  Home->Alignment section choose to Wrap Text
- Select the cell containing the text and the cell next to in and in the ribbon, Home->Alignment section, choose to Merge Cells
- In the ribbon, Home->Cells->Format choose Auto Fit Row Height
- You will see that the only "times" shows in the merged cells when the height snaps back. That is the very end of the string of text.

On Excel Desktop:
- Follow the exact same steps as above
- You will see that the beginning of the string shows in the cell when the cell height snaps back.  "This is a very long" is what is displayed in the two merged cells.

We can accept the issues with merging and autofit as they have been around a while even though I wish the autofit worked correctly. However, what we would like for you to resolve is that on the web, after snapping the height back when autofitting a merged cells' height, it should display the beginning of the string content, not the end.
Is that doable?

Thanks!

**Comment by donlvMSFT** [comment]
I'd like to close this thread as the fix already been rolled out due to bug status, please help verify.
Thanks for the discussion!
