### ISSUE TITLE
Error Launching Add-in When Using Documents With an Apostrophe in the Name

### ISSUE THREAD

**Issue by gkarmelich** [OfficeDev/office-js#1841]
When opening a document in Word where there is an apostrophe in the filename, our Word add-in cannot be initialized.

## Expected Behavior

Our add in should be initialized successfully.

## Current Behavior

Currently, the add-in cannot be initialized in this case, even when opening a document with no other data in it besides the filename. Our add-in becomes stuck and it cannot be used.

## Steps to Reproduce, or Live Example

- Create a new document
- `Save as` with any filename that includes an apostrophe, such as `test's.docx`
- Try to launch an add-in that uses OfficeJS

## Your Environment

* Platform: PC desktop
* Host: Word
* Office version number: Version 2103 (Build 13901.20462)
* Operating System: Windows 10

## Useful logs

- [x] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

`Uncaught SyntaxError: Unexpected identifier`

This seems to be a regression from this previous issue: https://github.com/OfficeDev/office-js/issues/737

**Comment by AbidRahman-MSFT** [comment]
@smaremanda, I believe this is a WebView2 issue. I've seen similar issues popping up recently for users using Webview2 where the filepath includes an apostrophe. Here is a repro video for the same issue: https://www.youtube.com/watch?v=ada1E9mQDn0

**Comment by gkarmelich** [comment]
Thanks @AbidRahman-MSFT. I looked at the video you linked and that is the same experience our users are having.

**Comment by ElizabethSamuel-MSFT** [comment]
@croicu Can you take a look since this seems to be a WebView issue?

Thanks.

**Comment by MartinSSeifert** [comment]
We are still seeing customers with this issue - has there been any progress in solving it? cc: @AbidRahman-MSFT @croicu

**Comment by Dengshan2018** [comment]
@MartinSSeifert , what's your Office version? This bug has been fixed a year ago.

**Comment by Dengshan2018** [comment]
No response. Just treat the issue was resolved. Close the issue. Reactive if the issue persists.
