### ISSUE TITLE
Automatically open a task pane with a document on opening document

### ISSUE THREAD

**Issue by arshadshibli** [OfficeDev/office-js#1844]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am using 'Automatically open task pane with document' [https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document](url) feature of office js to load a task pane on document open, I was able to successfully add taskpanes.xml and webextension.xml to the document using Java code with apache poi library. After adding the xml files to the document I am sending the Document in base64 format to the client. But at the client side on loading the document from base64 the taskpane is not loading correctly. But on closing the taskpane and reloading the document it loads the document as well as the task pane correctly

## Expected Behavior
Task pane should load correctly on opening the document using context.application.createDocument(fileContent).open() where fileContent is the base64 format of document

## Current Behavior on 
On  context.application.createDocument(fileContent).open() document load in a new tab , But the taskpane shows error 
![image](https://user-images.githubusercontent.com/36449762/117127336-96790280-adb9-11eb-81cc-7c6f9ba8cb3f.png)
Strange thing is that closing this panel and reloading the tab, document as well as taskPane loading correctly. 

## Context
Automatically opened taskPane shows error. But loading correctly on closing the taskpane and reloading the browser tab. if the webextension.xml and taskpanes.xml was not added correctly  to the document, it should not have loaded the panel on reloading the tab also.
This feature was working correctly earlier, I mean task pane will load as expected with opening the document itself, But recently it stopped working

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]:Word
* Operating System: windows
* Browser (if using Office on the web): Chrome and Mozilla firefox

## Useful logs
Taskpanes.xml added
![image](https://user-images.githubusercontent.com/36449762/117127997-75fd7800-adba-11eb-873f-58af23666e42.png)

Webextension.xml added
![image](https://user-images.githubusercontent.com/36449762/117128125-a218f900-adba-11eb-8438-4c9ef771fc1d.png)

Part of manifest where the taskpaneid mentioned
![image](https://user-images.githubusercontent.com/36449762/117128397-f91ece00-adba-11eb-83bd-5dfb188e7bf9.png)

code part where document created from base64
![image](https://user-images.githubusercontent.com/36449762/117129087-e22cab80-adbb-11eb-9457-b3bf56102ce0.png)

**Comment by nancy-wang** [comment]
Thanks so much for this feedback @arshadshibli ! I've tagged @AbidRahman-MSFT from our team to investigate further.
