### ISSUE TITLE
[Excel on the web] Context menu button not triggering the linked action

### ISSUE THREAD

**Issue by sshukurov** [OfficeDev/office-js#1846]
Affects Excel on the web, does not affect the desktop version.

## Expected Behavior
When I click on a context menu button added using `<OfficeMenu id="ContextMenuCell">` element in the manifest, it should trigger the action defined in the `Action` element.

## Current Behavior
`Action` does not get triggered. Affects both `ExecuteFunction` and `ShowTaskpane` types of action.

## Steps to Reproduce, or Live Example
Minimal repro: https://github.com/sshukurov/excel-custom-functions-context-menu-button

I sideloaded and tested the sample provided here, too: https://github.com/OfficeDev/Office-Add-in-Commands-Samples/tree/master/Excel, the context menu buttons from the sample aren't working either.

## Context
Our Excel JS addin is hosted in production and is used by our customers. We have a context menu button and it was working fine until we discovered the issue today.

I made sure our app adheres to the guide in https://docs.microsoft.com/en-us/office/dev/add-ins/develop/create-addin-commands. I was able to create a repro according to the guide and the issue exists there, too.

## Environment
* Platform: Excel on the web
* Host: Excel
* Office version number: 16.0.14102.35900
* Operating System: Microsoft Windows 10 Pro Version 20H2 OS Build 19042.928

* Browser: Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)

**Comment by nancy-wang** [comment]
Thank you @sshukurov ! I've tagged @keyur32 from our team to investigate this further

**Comment by sohailzafar** [comment]
Thanks for your patience, also following up with the engineering manager.

**Comment by ssnyder-msft** [comment]
This issue should now be resolved.

**Comment by sshukurov** [comment]
@ssnyder-msft thank you, it's indeed working as expected now!
