### ISSUE TITLE
Can not add comment with excel add-in

### ISSUE THREAD

**Issue by Issac-Nguyen** [OfficeDev/office-js#1847]
Can not add comment in excel add-in

## Expected Behavior
Can add comment via function add of comment object

## Current Behavior
Can not add comment into cell in excel add in, error not implemented is thrown when using comments.add function

## Steps to Reproduce, or Live Example
This is my snippet of script-lab
[https://gist.github.com/Issac-Nguyen/ac7a8adfe745e665335efad26b7cea39](url)

## Context
I'm writing an adding which is using the add comment feature for my project, so I need support from the officejs team to make it works.

## Your Environment
I'm using excel on windows (version 2104 (build 13929.20296))

## Useful logs
Console:

> {
>     "items": []
> }
> 
> [ERROR]: Error:
> {
>     "description": "This operation is not implemented.",
>     "message": "This operation is not implemented.",
>     "stack": "NotImplemented: This operation is not implemented.\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:26:295765)\n   at o (https://script-lab-runner.azureedge.net/static/js/2.c071b8cf.chunk.js:2:3296041)\n   at Anonymous function (https://script-lab-runner.azureedge.net/static/js/2.c071b8cf.chunk.js:2:3296188)\n   at u (https://script-lab-runner.azureedge.net/static/js/2.c071b8cf.chunk.js:2:305321)",
>     "name": "RichApi.Error",
>     "code": "NotImplemented",
>     "traceMessages": [],
>     "innerError": null,
>     "debugInfo": {
>         "code": "NotImplemented",
>         "message": "This operation is not implemented.",
>         "errorLocation": "CommentCollection._OnAccess",
>         "statement": "var comments = worksheet.comments;",
>         "surroundingStatements": [
>             "var workbook = context.workbook;",
>             "var worksheets = workbook.worksheets;",
>             "var worksheet = worksheets.getItem(...) /* originally getActiveWorksheet() */;",
>             "// >>>>>",
>             "var comments = worksheet.comments;",
>             "// <<<<<",
>             "var add = comments.add(...);"
>         ],
>         "fullStatements": [
>             "var workbook = context.workbook;",
>             "var worksheets = workbook.worksheets;",
>             "var worksheet = worksheets.getItem(\"{27E93C11-FCC0-4AF1-AD6F-3E41949D5C0A}\") /* originally getActiveWorksheet() */;",
>             "var comments = worksheet.comments;",
>             "var add = comments.add(\"A2\", \"Todo\", undefined);"
>         ]
>     },
>     "httpStatusCode": 501
> }

**Comment by ghost** [comment]
Hi @AlexJerabek,

var comments = workbook.comments;
"This operation is not implemented."

I still facing this issue when trying to add comments in Excel using Excel Javascript Api. You can see the error attachment image below for more detail. I'm getting the error for all comment-related API. Please help me to resolve this issue. Thanks

![image](https://user-images.githubusercontent.com/63444197/117252511-4446e880-ae70-11eb-9b8b-8a4672e93083.png)

**Comment by honxmsft** [comment]
I've tested on Version 2105 (Build 14026.20084 Click-to-Run), Channel OuterRing,
and Version 2104 (Build 13929.20296). It seems the issue does not repro.

Can you check if you can repro this again?

I've checked recent change, and I think this might be caused by a license related problem, I'll update this thread if I have any further update.

**Comment by Issac-Nguyen** [comment]
> I've tested on Version 2105 (Build 14026.20084 Click-to-Run), Channel OuterRing,
> and Version 2104 (Build 13929.20296). It seems the issue does not repro.
> 
> Can you check if you can repro this again?
> 
> I've checked recent change, and I think this might be caused by a license related problem, I'll update this thread if I have any further update.

hi @honxmsft ,
I'm using same version with @tvkien using, but same result as him. Could you please share your snippet example so I can import and check on my computer?

Thanks.

**Comment by honxmsft** [comment]
> > I've tested on Version 2105 (Build 14026.20084 Click-to-Run), Channel OuterRing,
> > and Version 2104 (Build 13929.20296). It seems the issue does not repro.
> > Can you check if you can repro this again?
> > I've checked recent change, and I think this might be caused by a license related problem, I'll update this thread if I have any further update.
> 
> hi @honxmsft ,
> I'm using same version with @tvkien using, but same result as him. Could you please share your snippet example so I can import and check on my computer?
> 
> Thanks.

I tried with your gist in ScriptLab, and the script mentioned by tvkien.

However, before you retry it in your computer, can you tell me what license you have? I think it might be a license issue. Currently, the comment collection feature is required Perpetual 2021 license or O365 subscription.

Also, did this API work for you like several months ago? Or is this the first time you encounter this issue?

**Comment by jipinshi** [comment]
@Issac-Nguyen. if the license is Perpetual, this is by design. If it is this case, you may need to change license to unblock you.

**Comment by Issac-Nguyen** [comment]
> @Issac-Nguyen. if the license is Perpetual, this is by design. If it is this case, you may need to change license to unblock you.

Hi @jipinshi, I think it's a problem because of missing license. We can close this ticket. Thanks.

**Comment by hengchengfei** [comment]
<img width="586" alt="1" src="https://user-images.githubusercontent.com/3182964/171375882-794b99ff-3e6e-405e-b9dd-3b116756efd8.png">
<img width="768" alt="2" src="https://user-images.githubusercontent.com/3182964/171376052-b034749b-c9e3-4114-8f9a-82baedc738f5.png">
