### ISSUE TITLE
Excel add-in reloading when Attach Debugger

### ISSUE THREAD

**Issue by brgruber92** [OfficeDev/office-js#1849]
I'm locally debugging my Excel add-in from VS Code on Excel Desktop. It used to work fine, but since yesterday, when I hit "Attach Debugger" in the task pane, the add-in reloads itself after 5 seconds approximately, making the debug windows to close. 

## Expected Behavior
To keep the Debug windows opened during the execution of the add-in.

## Current Behavior
Reloads the add-in approximately 5 seconds after the "Attach Debugger" option is selected in the task pane.

## Steps to Reproduce, or Live Example
1. From VS code, use the command npm start
2. Open the add-in in Excel
3. Hit "Attach Debugger" and wait 5 seconds
4. The add-in reloads itself and closes the debug windows

## Context
It's not possible to debug the add-in, since it keeps reloading itself

## Your Environment

- Windows 10
- Microsoft® Excel® for Microsoft 365 MSO (16.0.13929.20222) 64-bits
- Edge Version Version 90.0.818.51 (Official build) (64-bit)
- Set-up: VS Code with Yeoman generator, Excel desktop.

**Comment by nancy-wang** [comment]
Thanks @brgruber92! I've tagged @lumine2008 from our team to investigate this further.

**Comment by jipinshi** [comment]
@brgruber92, Thanks reporting the issue. Wonder was there any recent change for manifest or js code and then met the reload issue? Or didn't make any change but it worked before and later it didn't work? Here want to confirm whether it was caused by any regression. And also wonder if you don't attach, will it cause crash after load the taskpane addin and wait 1 min? Another question is which processes was attached with vs code?

**Comment by brgruber92** [comment]
Thank you guys for taking care of this incident. Here are the answers to the questions:

- No, there wasn't any change in the manifest or source code. I don't know if that is related, but my Windows and VS Code both updated in the previous night of the problem.
- If I don't attach a debugger, the add-in works as expected. It only reloads when I attach it - it doesn't matter when : when it starts, after a few interactions or at the last screen of my add-in - it always reloads after 5 seconds
- Checking in the Task Manager, I can see only VS Code process related to it - is there a better way to check that?
![image](https://user-images.githubusercontent.com/78985160/117471565-5e470080-af2e-11eb-86ef-aae4a8429fb1.png)

**Comment by jipinshi** [comment]
@brgruber92, can you have a try for Visual studio to do debug? Looks like not api related regression.

**Comment by jipinshi** [comment]
I think this is similar issue with [this one]( https://github.com/OfficeDev/office-js/issues/1852)

**Comment by jipinshi** [comment]
@smaremanda, can you take a look?

**Comment by smaremanda** [comment]
@jipinshi - we're looking into it. will respond as soon as we understand the root cause.

**Comment by brgruber92** [comment]
Great! Thanks a lot

**Comment by Aniruddha-Shriwant** [comment]
This issue looks similar to #1852 see [this comment](https://github.com/OfficeDev/office-js/issues/1852#issuecomment-839425906)

**Comment by brgruber92** [comment]
Hi @Aniruddha-Shriwant that's the same problem I'm having. I'm closing this incident, so we can focus there. Thank you.
