### ISSUE TITLE
postMessage does not work on On-Premise OWA

### ISSUE THREAD

**Issue by splinter** [OfficeDev/office-js#1851]
We have a customer who is using the Outlook Web Application that is exposed via an on-premise Exchange server.The messageParent method does not post a response back to the parent window.

## Expected Behavior
The messageParent method should send a message to the parent window

## Current Behavior
The messageParent method does not send messages to the parent window

## Steps to Reproduce, or Live Example
- Access Outlook Web Application (OWA) that is hosted via an on-premise Exchange server
- Open a dialog window using the Dialog API [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins)
- Call the messageParent method 

## Context
We depend on the Dialog API to perform authentication and as a result users are unable to authenticate into our add-in

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: OWA (Chrome and Firefox)
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome and Firefox 

[1] https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins

**Comment by exextoc** [comment]
Please make sure that the page calling Office.context.ui.messageParent must also be on the same domain as the parent page.

Also can you share the on-Premise exchange version. Requirements sets supported by different exchange versions can be found [here](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets).

**Comment by splinter** [comment]
Please find the On-Premise Exchange version below:
```
 MS Exchange server 2016 version  15.1.2242.5
```

> Please make sure that the page calling Office.context.ui.messageParent must also be on the same domain as the parent page.

This is working for all our customers that are on Office 365 and as a result cannot be an issue with the domain.

**Comment by westconference** [comment]
@splinter sounds like the same issue as [1286](https://github.com/OfficeDev/office-js/issues/1286). There were some workarounds suggested there;
* https://github.com/OfficeDev/office-js/issues/1286#issuecomment-661881445
* https://github.com/OfficeDev/office-js/issues/1286#issuecomment-731456779

**Comment by exextoc** [comment]
Hey @exextoc ,

Thanks for reporting this issue. We have tracked it in our backlog and are working on it. However, we have have no timelines to share at this point.
