### ISSUE TITLE
Office.context.mailbox.item.SaveAsync throws an error in Onsend Addin if Send Later option is used on OWA

### ISSUE THREAD

**Issue by avisheknand** [OfficeDev/office-js#1853]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi Everyone,

I am facing issue in our OnSend office addin in OWA. When we use send later option in OWA there is an error in the office. js for Office.context.mailbox.item.saveAsync Method. The error states " Connection error occurred while trying to save the item on the serve". If send later option is not used then .saveAsync works fine. Anyone has faced this issue before?

Please let me know your views or recommendations.

**Comment by avisheknand** [comment]
Sorry AlexJerabek for posting at the wrong place. Thank you setting it up for me.

I am adding the function which we use to reproduce the issue.

   
           
       function getItemIDFromOutlookAPI()

       {

       let  itemId = null;
 	Office.context.mailbox.item.saveAsync(function (asyncResult) {

                if (asyncResult.status === Office.AsyncResultStatus.Failed) {

                    console.log("Error while saving the item:" + asyncResult.error.message);
			// This is the place where we get the error when SaveLater option is selected while sending the email.
			// The error is " Connection error occurred while trying to save the item on the serve"
                }
                else {
                    itemId = Office.context.mailbox.convertToRestId(
                        asyncResult.value,
                        Office.MailboxEnums.RestVersion.v2_0);

                }

            });
	}

Please let me know if you need any further details.

Thanks.

**Comment by AlexJerabek** [comment]
Thanks @avisheknand!

@exextoc, can you please take a look?
