### ISSUE TITLE
Angular Add-in Served From Localhost No Longer Loads On Excel Online

### ISSUE THREAD

**Issue by joshuawwright** [OfficeDev/office-js#1854]
## Expected Behavior
I expect an add-in that I am hosting via localhost to load on excel online for ease of development.

## Current Behavior
After uploading my add-in manifest, a new ribbon is shown. After clicking a ribbon button for my web addin a pane is opened, but the add-in fails to load. The new behavior started for me Today (5/7).
 
## Steps to Reproduce, or Live Example
1) Create an angular application for office js.
2) Open a new Excel workbook on Excel online.
3) Upload a new add-in manifest in the Office Add-ins pane, configured to point to the angular dev server aka urls should point to localhost and the port it is being served from (aka something like http://localhost:4200).
4) Once the manifest has loaded, try opening up the add-in.

## Context
The issue makes it difficult for developers on Linux to test their angular office web add-ins. The ability to update a web app real time on Excel Online, makes development/testing/debugging web add-ins a pleasant experience. Otherwise developers on Linux are forced to deploy their applications, or switch over to Windows.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.14102.35903
* Operating System: Linux
* Browser (if using Office Online): Chrome, Edge, and Firefox (Tried all three with the same result)

## Useful logs
![image](https://user-images.githubusercontent.com/1731346/117502097-44141f00-af3c-11eb-9f3b-4466f0ff42d0.png)
![image](https://user-images.githubusercontent.com/1731346/117502111-4aa29680-af3c-11eb-973a-d949d0dd7baa.png)

**Comment by joshuawwright** [comment]
I was able to get my app working by doing the following:

1) Update the manifest urls to point to https. Aka **http**://localhost:4200 to **https**://localhost:4200
2) Run Angular development server using "ng serve app-name --ssl"

Not sure why this wasn't needed in the past ...

**Comment by smaremanda** [comment]
@DesertFoxNV - thanks for the update. Yes - https is a requirement even when running in localhost.

**Comment by joshuawwright** [comment]
@smaremanda Not sure where it should go, but it would be nice to put this somewhere in the documentation. I believe it mentions https is required for deployment, but it would be good also to mention that it is even required in development.

Actually, even better the manifest should be rejected with the reason http is not allowed. Aka add this to the manifest validation.
