### ISSUE TITLE
Outlook outlook.live.com getSelectedDataAsync returns InvalidSelection when there is a valid selection

### ISSUE THREAD

**Issue by ndvbd** [OfficeDev/office-js#1855]
It doesn't work. Returns "InvalidSelection", when there is a valid selection. Am I missing something?
Sometimes, it does work and returns the selection of the text in the subject, even when the body is selected. The behaviour is not consistent.

I tried it on Chome 88 + https://outlook.live.com/mail/0/inbox

## Steps to Reproduce, or Live Example
 Office.initialize = function () {
      Office.context.mailbox.item.getSelectedDataAsync(Office.CoercionType.Text, {}, getCallback);
  };

  function getCallback(asyncResult) {
      var text = asyncResult.value.data;
      var prop = asyncResult.value.sourceProperty;

      console.log("Selected text in " + prop + ": " + text);
  }

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding getSelectedDataAsync(). It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 117069

**Comment by ndvbd** [comment]
@exextoc Hi, it's a killer bug, and it happens to me sometimes also on Outlook Mac. This bug prevents some users from using the add-in completely, so if you can nail it down quickly, that would be lovely.

**Comment by exextoc** [comment]
Hello @ndvbd this issue has been fixed for OWA. The fix should be available within the 2-4 weeks.

**Comment by ndvbd** [comment]
@exextoc is it deployed by now?

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available now

**Comment by ndvbd** [comment]
Looks good now! Thanks!
