### ISSUE TITLE
InvalidArgument: The argument is invalid or missing or has an incorrect format rich api error

### ISSUE THREAD

**Issue by swiftinitdotcom** [OfficeDev/office-js#1856]
getting this error in excel addin when we get data from json into excel. office 365 excel addin

InvalidArgument: The argument is invalid or missing or has an incorrect format.

stack trace-
"RichApi.Error: The argument is invalid or missing or has an incorrect format.
    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:26:235644)
    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:26:297462)
    at https://appsforoffice.microsoft.com/li

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by jipinshi** [comment]
@swiftinitdotcom , can you use script lab to repro the issue and share the gist? And which platform do you use? like windows?MAC? or wac online?

**Comment by swiftinitdotcom** [comment]
When I commented below code it stoped that error but I need these formulas....
 /* temp commented
                                    * RichApi.Error: The argument is invalid or missing or has an incorrect format.
                                    * https://github.com/OfficeDev/script-lab/issues/772
                                    * https://github.com/OfficeDev/Excel-Custom-Functions/issues/158
                                range.dataValidation.clear();
                                range.dataValidation.rule = {
                                    list: {
                                        inCellDropDown: true,
                                        source: mycountries,
                                        autofitColumns: true
                                    }
                                };

                             
                                var range1 = sheet.getRange("K2:K120");
                                const conditionalFormat = range1.conditionalFormats.add(
                                    Excel.ConditionalFormatType.cellValue
                                );

**Comment by jipinshi** [comment]
@swiftinitdotcom, I see there are two parts, one is range.dataValidation.rule and the other one is Range1.conditionalFormats.add(...), may I know which one cause the issue? And can you also share one reproable excel file? Please also let me know which platform do you run it.

**Comment by jipinshi** [comment]
@swiftinitdotcom , could you also share us the Excel build you used and platform like mac or win32 or excel online?

**Comment by jipinshi** [comment]
@swiftinitdotcom, does the issue get resolved? If not,  could you help provide more info asked in the comments?

**Comment by jipinshi** [comment]
Based on no further feedback in last week, close it first. If there is further feedback, please reactive this one or open one new, Thanks. @swiftinitdotcom
