### ISSUE TITLE
GeneralException when trying to track and later select Range objects

### ISSUE THREAD

**Issue by dan-sra** [OfficeDev/office-js#1857]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
I expect to be able to select() tracked Range objects outside of the original Word run context.

## Current Behavior
When trying to select a tracked Range object, a GeneralException is thrown.

## Steps to Reproduce, or Live Example
* Link to live example: https://gist.github.com/dan-sra/d00c7587d5bbba8f7184dfbc98c3ad64

## Context
I am trying to write an add-in to help users avoid certain "banned words" when writing technical reports. When the add-in finds an instance of these phrases, I want the user to be able to click a button and be brought to the instance by selecting it.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Microsoft® Word for Microsoft 365 MSO (16.0.13929.20222) 64-bit 
* Operating System: Windows 10 19041

## Useful logs

- [x] Console errors
```
word-win32-16.01.js:26 Uncaught (in promise) RichApi.Error: GeneralException
word-win32-16.01.js:26 Uncaught (in promise) RichApi.Error: GeneralException
    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:26:239499)
    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:26:301317)
    at https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:26:299422
```
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by yihuax-zz** [comment]
The following code works on my machine, if we keep track of the collection, not just a item in it:

async function findSelect() {
  var searchResults;

  await Word.run(async (context) => {
    searchResults = context.document.body.search("<(canary)>", { matchWildcards: true });
    searchResults.load();
    await context.sync();
    searchResults.items[0].font.color = "green";
    await context.sync();
    context.trackedObjects.add(searchResults);
  });

  setTimeout(function() {
    Word.run(searchResults, async (context) => {
      searchResults.items[0].select();
      await context.sync();
      context.trackedObjects.remove(searchResults);
      console.log("Done");
    });
  }, 2000);
}

**Comment by dan-sra** [comment]
@yihuax Your code did fix the initial problem, but now if you select the same object twice you still get a GeneralException. Code below:

```javascript
async function findSelect() {
  let range;
  let searchResults;
  await Word.run(async (context) => {
    searchResults = context.document.body.search("<(canary)>", { matchWildcards: true });
    searchResults.load();
    await context.sync();
    searchResults.items[0].font.color = "green";
    await context.sync();
    context.trackedObjects.add(searchResults);
  });

  setTimeout(function () {
    Word.run(searchResults, async (context) => {
      searchResults.items[0].select();
      await context.sync();
      // context.trackedObjects.remove(searchResults);
      console.log("First Select");
    });
  }, 2000);

  setTimeout(function () {
    Word.run(searchResults, async (context) => {
      searchResults.items[0].select();
      await context.sync();
      // context.trackedObjects.remove(searchResults);
      console.log("Second Select");
    });
  }, 4000);
}
```
