### ISSUE TITLE
When getAccessToken is using "allowConsentPrompt" to display a pre-authorization popup, the next rights delegation is considered done and redirects immediately

### ISSUE THREAD

**Issue by Medhyena** [OfficeDev/office-js#1858]
I tried using both Office.context.auth.getAccessTokenAsync({ allowConsentPrompt: true}, asyncFunc) and OfficeRuntime.auth.getAccessToken({ allowConsentPrompt: true}). If the user needs to pre-authorize the application, there is a popup asking for some basic rights (profile and email if I'm not mistaken). When the user accepts this one, we fetch a MS Graph token through a request of "on-behalf-of" and it returns a need to the user to delegate some rights : the ones provided in the Azure application. When opening the dialog to the authorize URL, instead of asking for the user to accept the rights, it instantly redirects to the redirectURI.

In my case, it will close the popup and try again, thus open another authorize popup that will automatically redirect since graph said it needs some more rights. You got it, it's endless.

Because of some weird cache, you need to uninstall the app, close outlook, re-open it (on the web you don't need to close it and only to re-install it) and then it will ask you for the "more rights to delegate" thing in the authorization popup.

I've tried adding the "forMSGraphAccess" but that thing doesn't work at all on the OutlookClient, I'm not even sure if it is supposed to help, it only seems to bring more troubles...

## Expected Behavior
The authorize popup should correctly ask for the new rights to delegate to the application after a pre-authorize popup instead of assuming all rights have already been delegated and thus redirecting.

## Steps to Reproduce
1 : You need an account that is office365 but not from the company where the azure application is. The simpler is to have a personal/educational account, but some business account (like the ones Microsoft are using for the validation of the addin) are working too.
2 : Specify some rights in your Azure that the user can delegate, like email.read for Outlook
3 : When this user will start with your app, the pre-authorization popup should appear saying it needs his consent
4 : The process should then break and the authorization popup will always redirect to the redirectURI without asking for consent (and thus not giving it)

## Context
We are trying to validate our add-in with Microsoft and it seems they encounter the issue with a business account. We already tried with some of our clients and this problem seemed to appear for the first time with Microsoft, it took us a while to reproduce it. We would like to push our add-in to the Microsoft Store and that is a BIG issue.

## Your Environment
On Windows, Outlook from office365 and Outlook for the web (outlook.office.com), it's broken everywhere

**Comment by mattgeim** [comment]
Currently, Office isn't able to consent for Graph scopes on behalf of a user. We recommend that administrators grant admin consent for the tenant to deal with this situation.  We do have some documentation on this [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph#distributing-sso-enabled-add-ins-in-microsoft-appsource).  We are investigating how to increase the clarity of admin consent or using a fallback method for Graph scopes currently.  Please feel free to re-open if we didn't answer your question.  Thanks!

**Comment by Medhyena** [comment]
Hello, it doesn't answer my question...
My problem here is that the pre-authorization needed for the add-in (if needed, not for everyone, prob depends on people's Azure configuration I guess) requires the user to accept minimum rights. When doing this, I need then to ask them the permissions to use the particular rights if the on-behalf-of request fails. In this case, it feels like Outlook keeps a cache of the accepting request which directly redirects that popup to the redirectURI.
In this case, the issue is that the user has NOT accepted for graph's scopes but only for minimal (pre-authorization) scopes thus, the graph token request doesn't work...

It is certainly a cache issue from your side where the authorize popup thinks the request has already been done while, yes, it has been done but with fewer scopes.

The only way to fix that for now is to ask the user to re-install the add-in after having accepted pre-authorization.

Also on a side note, as you said it well, Office isn't able to ask for consent for Graph scopes... which is kind of a shame for what I am talking about. It would both solve the problem and make more sense to the user.
