### ISSUE TITLE
Add-in was removed because it made Outlook crash

### ISSUE THREAD

**Issue by KorzunAV** [OfficeDev/office-js#1859]
[Enter feedback here]
'Just had a partner report that she installed Huddle on to her Outlook desktop application on Friday via outlook add-ins. This morning (Monday, April 12th, 2021) she logged in and received an error message that said it was removed because it made Outlook crash. Any ideas on what to look at/troubleshoot on this?'

*"Microsoft 365 Version 2103."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b6cb5f52-dfc5-4fa2-6508-194d6f1c674a
* Version Independent ID: 8f3caf2d-fba3-166f-43bc-1d3e4007abab
* Content: [Troubleshoot user errors with Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting)
* Content Source: [docs/testing/testing-and-troubleshooting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/testing-and-troubleshooting.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
Unfortunately, since this is an issue with the Huddle add-in, please contact their technical support team. Outlook is behaving as expected by disabling the add-in because it is crashing and causing a bad user experience.
