### ISSUE TITLE
Mailbox Item - Add resources operation

### ISSUE THREAD

**Issue by Ideline** [OfficeDev/office-js#186]
I'm trying to compose an appointment in Outlook using my custom add-in for the calendar. I need to be able to book a room by providing the rooms email and name. Right now I'm setting the location (name of the room) using Office.context.mailbox.item.location.setAsync and the only way I have found to book the room is by setting the room as a required attendee using Office.context.mailbox.item.requiredAttendees.setAsync.

If you would book a room manually without my custom add-in the room will be under the items resources when you do a findItem request.

But when the room is booked as a required attendee it will not be under the items resources.  Is there an "add resource operation" that's usable while composing an appointment? Or what operation should I use to actually book a room the correct way?

The add-in is written in Javascript and Vue.js.

**Comment by exextoc** [comment]
This is not possible today. However, we track Outlook add-in feature requests on our user-voice page.
It looks like the feature you want has been requested by others already. Please upvote the [existing request](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/15777979-add-support-in-officejs-for-complex-type-meeting-l). Feature requests on user-voice are considered when we go through our planning process.

[Outlook Add-ins Engineering Team]

**Comment by Ideline** [comment]
Thank you for the response. I will absolutely do that!

I have one more question though in that case. 
When I have set a room as a required attendee using Office.context.mailbox.item.requiredAttendees.setAsync and then use Office.context.mailbox.item.requiredAttendees.getAsync, in the web version of outlook, the room will be included in the result.value but in the desktop version it will not. 

Also when I try to set the required attendees in the desktop version it will not overwrite the rooms email address, only the other required attendees (I guess since it doesn't recognize it as a required attendee), but in the web version it will. This is a major issue since this is the only way for me to actually book the room at the moment. This means that when the user is using the desktop Outlook, they have to manually remove the room as a required attendee if they change their mind and wants to add another room to the meeting. But in the web version I can write a method for it so that it automatically removes the old room  and adds the new one.

Why is it behaving differently in the web and desktop versions? Is there a solution?

-Ideline

**Comment by exextoc** [comment]
The Desktop client treats rooms as separate entities from attendees, whereas the web version doesn't. This is simply a design difference between the two clients.

[Outlook Add-ins Engineering Team]

**Comment by Ideline** [comment]
Yes well so much I figured out already, but is there a way for me to overwrite the already added room OR remove it from the list of required attendees in the desktop client so that the room won't be invited and booked for the meeting? Because I can do that in the web client and this is very much a requested feature, but right now my add-in is behaving differently in the two clients which could be very confusing for the user, who will have to remove it manually while using the desktop client but won't have to do that in the web client. There's a risk that the user will forget to remove a room if they change their mind and thereby book 2 rooms at the same time when only needing 1.

-Ideline

**Comment by JuaneloJuanelo** [comment]
at this point this is a feature request, please add in uservoice, as requested.

**Comment by gercobrandwijk** [comment]
@JuaneloJuanelo Is there please any news on this? This user voice, https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/13316001-add-office-javascript-api-support-for-resources-of, has 341 user votes now. But there is no solution/workaround yet...

Copied from another issue (https://github.com/OfficeDev/office-js-docs/issues/135#issuecomment-429034755) a little more explaination of what I am trying to achieve:

> It is impossible now to remove a Resource (Room) from an appointment using the Office Javascript API.
> 
> To repoduce:
> 
> - Add a room emailaddress to the requiredAttendees with the addAsync call
> - Outlook (desktop client) is moving this attendee to the Resources field (because it recognises it as a room).
> - After that, you are not able to get/clear the Resources, because the api does not expose something for this. Overwriting the requiredAttendees with an empty array does not work. Also clearing the Location field has no effect.
> - Please provide us a solution. A workaround is also fine ;)

**Comment by knight-sword** [comment]
It's already 2022, has this problem been solved, thank you!
