### ISSUE TITLE
[Outlook] Add-in show compatibility problem right after installed Webview2 Runtime

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1862]
Add-in show compatibility problem right after installed Webview2 Runtime. (90.0.818.49)
If uninstall 'Webview2 Runtime' add-in can work normal.
And most effected user is auto installed webview2 Runtime on 04/01.
About 75% percent auto installed webview2 runtime user effected by this problem.

## Expected Behavior
Add-in will not meet compatibility problem.

## Current Behavior
Show compatibility error: Compatibility Problem Error Code: STATUS_INVALID_IMAGE_HASH

## Steps to Reproduce, or Live Example
open third part add-in on Outlook after auto installed Webview2 Runtime.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows 10 1809 or 1909
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office 2102(Monthly Enterprise Channel)
* Operating System: win 10
* Browser (if using Office on the web): Edge Chromium 90.818.46

We have screen shot like: 
![image](https://user-images.githubusercontent.com/15980696/118088025-065e3d00-b3f9-11eb-92d0-78eb59cf47e1.png)

If this problem requires an Add-In aspect for code adaptation, what does the Add-In need to do? Is there documentation to support it?

**Comment by SWei1234** [comment]
Hi @exextoc 
I found a Webview2 Runtime related ticket: 
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1194
Is this the same problem? 
Thanks

**Comment by exextoc** [comment]
Are you able to repro this issue with other 3rd party add-ins? Could you try to repro with ScriptLab for Outlook, which can be installed from the store [here](https://appsource.microsoft.com/en-us/product/office/WA200001603?src=office).
	
When you updated to Webview 2, did you follow all the required steps, as described in this [blog post](https://developer.microsoft.com/en-us/office/blogs/understanding-office-add-ins-runtime/)?

**Comment by Dengshan2018** [comment]
@SWei1234 

> Are you able to repro this issue with other 3rd party add-ins? Could you try to repro with ScriptLab for Outlook, which can be installed from the store [here](https://appsource.microsoft.com/en-us/product/office/WA200001603?src=office).
> 
> When you updated to Webview 2, did you follow all the required steps, as described in this [blog post](https://developer.microsoft.com/en-us/office/blogs/understanding-office-add-ins-runtime/)?

**Comment by SWei1234** [comment]
Hi @exextoc  @Dengshan2018 
Yes, This problem can be repro on other 3rd party add-ins. 
Thanks for your steps. Current office version is Enterprise Channel 2102 should be higher than required version.
Thanks

**Comment by Dengshan2018** [comment]
@SWei1234, Could you try to repro with ScriptLab for Outlook?
Is there any software from your IT department to block webview2 running?

**Comment by SWei1234** [comment]
Hi @Dengshan2018 
How could we know which software will block webview2 running?
Are there any test standard? 
Is there any different between ScriptLab and other 3rd party add-in? We tried some add-ins and all not work. 
Thanks

**Comment by Dengshan2018** [comment]
@SWei1234 , it seems that antivirus is causing the issue when inject the code. you might follow the steps for trouble shooting: https://textslashplain.com/2019/09/27/aw-snap-every-tab-crashes/

**Comment by SWei1234** [comment]
@Dengshan2018 
Thanks for your help. We will try this. 
Thanks
