### ISSUE TITLE
Using getHtml() function is leading to the word doc becoming read-only

### ISSUE THREAD

**Issue by prk21** [OfficeDev/office-js#1863]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
The word doc should not become read-only when the getHtml() code snipped from:https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#getHtml__
is executed in word via Script Lab

## Current Behavior
- The word doc is becoming read-only

## Steps to Reproduce, or Live Example

* Link to live example: 
https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#getHtml__
Executing this snippet word via Script Lab is leading to word doc becoming read-only.

If instead, we execute getOoxml() snippet from : https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#getOoxml__
The word behaves as expected, we can still keep editing the document.

## Context

-This issue was not observed previously
-Previously getHtml() used to work fine

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac, office on Web
* Host [Excel, Word, PowerPoint, etc.]: Word Online
* Office version number: 
* Operating System: MacOS
* Browser (if using Office on the web): Chrome Version 90.0.4430.93 (Official Build) (x86_64)

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by prk21** [comment]
Hi team!
Any updates?

**Comment by AbidRahman-MSFT** [comment]
Hey @prk21 - apologies for the delay.

I am able to repro the same behavior. When using the following gist: [https://gist.github.com/AbidRahman-MSFT/fce5766c420b76ad01c745c8a36c241a](https://gist.github.com/AbidRahman-MSFT/fce5766c420b76ad01c745c8a36c241a) in ScriptLab on Word on Web, I'm unable to continue typing on the canvas. 

@RuoyingLiang - is it possible to investigate this issue?

Steps:
1. Open Word on Web
2. Open Script Lab and import this gist: https://gist.github.com/AbidRahman-MSFT/fce5766c420b76ad01c745c8a36c241a
3. Run the script lab snippet
4. The HTML will be printed in the console
5. Try to place the cursor back in the document and continue typing

**Comment by prk21** [comment]
Hi team, any updates that what is the cause of this issue? and any fix in place yet ?

**Comment by urielgb413** [comment]
Hello, any updates on this issue? seems to happen only for Word Online, as it works as expected in Word for macOS.

**Comment by crispybits** [comment]
**This issue is specific to Word on web and leaves the document in an usuable state until the browser is refreshed.**

Caused by calling `Range.getHtml()` or `Range.getOoxml()` on a non-zero length range.
Gist <https://gist.github.com/crispybits/992c79fd2b14f5abfe702c963e7cce52>

Invoking these methods on a Range object will cause the document to become ReadOnly (Edit toolbar items will be disabled and cannot edit the document).

Document will remain ReadOnly and unusable until the browser is refreshed.

![image](https://user-images.githubusercontent.com/811597/121772576-05dad280-cb6e-11eb-866a-d043762579fe.png)
![image](https://user-images.githubusercontent.com/811597/121772587-1ee38380-cb6e-11eb-85c5-2bfe08c95ac1.png)
![image](https://user-images.githubusercontent.com/811597/121772600-3458ad80-cb6e-11eb-9b49-b31e9d0389d3.png)

**Comment by msoq** [comment]
Hi everyone, I observe the same behavior in our project. Everything works normally, but as soon as `context.document.body.getHtml();` is executed document becomes read-only.
I haven't tried running a project on a desktop client, but for the web version this is the case.
We're using the latest at this moment (1.1.70) version of office.js api.
Checked on Windows 10 ( build 10.0.18362), Chrome (Version 91.0.4472.114 (Official Build) (64-bit))
Is there any progress on this issue?

**Comment by kgeorgiou1234** [comment]
Same where with contentControl.getHtml()
