### ISSUE TITLE
Outlook on the web: Clicking the Send button immediately after refreshing the page does not execute any on-send add-in

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#1865]
When the OnSendAddinsEnabled flag is False and the Send button is clicked immediately after refreshing the page with the F5 key, any on-send add-in will not run.

## Expected Behavior

If you click the Send button, the on-send add-in runs.
The Send button should not be clickable until the on-send add-in is loaded.

## Current Behavior

If you click the Send button, the on-send add-in does not run.

## Steps to Reproduce, or Live Example

1. Create an email in Draft box
2. With the Draft box selected, reload the page with F5
3. When the page is displayed, quickly select the relevant email and click the Send button

In No.2, the operation should be done before the page has finished loading, so the following cases also can be reproduced.
- Immediately after refreshing the page
- Immediately after opening in a new tab
- Immediately after restarting the browser with the Draft box selected in the settings for saving the browser session

If you wait for the page to completely load, this issue does not occur.

https://user-images.githubusercontent.com/58804032/118241901-3571be80-b48c-11eb-8f71-31385eca3084.mp4

## Context

We are using the on-send add-in feature with the OnSendAddinsEnabled flag set to False.
The on-send add-in works very well except for this issue.

This issue is more likely to be encountered by impatient people or in slow connection environments.

If the OnSendAddinsEnabled flag is set to True, the above steps did not cause this issue.
Is it expected behavior that this issue occurs when the OnSendAddinsEnabled flag is False?

When the OnSendAddinsEnabled is True, the user experience is bad as it will send the message with a pop-out window.
Therefore, we strongly hope that this issue will be resolved so that it can be used regularly even when the OnSendAddinsEnabled is False.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 20210510006.05
* Operating System: Windows 10
* Browser (if using Office on the web): Edge Version 90.0.818.56 (Official build) (64-bit)

**Comment by exextoc** [comment]
Hello @clavx , what you're experiencing is expected behaviour.
Since just after hitting refresh the addins framework itself takes some time to load, your onsend addin does not work. But on making the OnSendAddinsEnabled flag to true; this pops up a new window (along with blocking on screen controls) which allows some more time for the addins framework to load and hence the onsend addin works.

**Comment by clavx** [comment]
Thank you for your reply.
I understand the content. 

Are there any plans to change the specifications?

**Comment by exextoc** [comment]
Sorry we do not have any plans as of now to change the specifications. But please feel free to add your suggestion here at [Microsoft 365 Developer Platform New Ideas forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)
