### ISSUE TITLE
Excel add-in is not loading and only shows white screen on some desktop excel application

### ISSUE THREAD

**Issue by ektadesai22** [OfficeDev/office-js#1866]
Excel add-in is not loading only shows white screen on some desktop excel application. 

Can you help us to identify the root cause?
I am getting below general error and it is not helping to identify the cause.
 **"Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page."** 
 
![image](https://user-images.githubusercontent.com/40557245/121253210-7633dc00-c86e-11eb-8a22-f607a8491534.png)

![image](https://user-images.githubusercontent.com/40557245/118443480-8d3d3f00-b6b1-11eb-91b3-c95647cf1534.png)

We found this issue for below configurations.
Configurations:
1.	Windows 10 Home (10.0.19042 build 19042)
Microsoft office Professional Plus 2019 (version 2103, build 13901.20462) – 64 bit
2.	Windows 7 Professional Service pack1
Microsoft office Professional Plus 2016 (16.0.4549.1000) – 64 bit

**Comment by ektadesai22** [comment]
add-in working fine for below configuration
   Windows 10 Home
   Microsoft Office Professional Plus 2016 (version 2104, build 13929.20372) – 64 bit

**Comment by ektadesai22** [comment]
@smaremanda - Could you please provide information on this?

**Comment by ektadesai22** [comment]
@smaremanda - Could you please help me on this?

**Comment by ektadesai22** [comment]
Finally, I found the root cause. 
The office is using Internet Explorer for addin and ES6 is not supported in IE11. 
I have used Arrow functions which are not supported in IE11 and because of that office.js is not loading. I have replaced the arrow functions with normal functions and then it works fine.

**Comment by gourav-bk** [comment]
I was facing the same issue and I have solved it by switching office 2019 to Office 365. This works fine now.

**Comment by ElizabethSamuel-MSFT** [comment]
@ektadesai22 Closing this issue as it seems to be resolved. If you're still facing this issue, do open a new one or comment on this one so we can reopen.

Thanks.

**Comment by Lucius-LaFromboise-Enterprises-LLC** [comment]
Hello,

I am having this same issue. I've been looking around at many other threads with this same issue and it seems like everyone is able to solve it or it just works suddenly. Would you please share the arrow function that you originally used and what you replaced it with? I would like to compare them with what I am using. 

Thank you
