### ISSUE TITLE
On Outlook for the Web, meeting requests don't update the Office.context.mailbox.item and don't fire the ItemChanged event

### ISSUE THREAD

**Issue by Medhyena** [OfficeDev/office-js#1869]
## Context
For our addin to be responsive when pinned, we update the content when the item changes. It works fine on the Outlook Client for Windows.

## Expected Behavior
On Outlook for the Web, when clicking on a meeting invite, it should correctly update the Office.context.mailbox.item and thus firing the ItemChanged EventType.

## Current Behavior
On Outlook for the Web, when clicking on a meeting invite, it doesn't fire the item change event which results in our addin to not be up to date to the item clicked. Also, I noticed that there are two tabs in a email invite and the default one is not triggering the item change while selecting the other tab correctly updates the item.

## Steps to Reproduce, or Live Example
Outlook for the Web ONLY : 
1 : Click on a mail while your addin is opened.
2 : Pin it
3 : Change to a meeting invite
4 : See your Office.context.mailbox.item doesn't update.

## Context
Our addin doesn't update information and thus, it makes the user think he can push something while he's pushing the previous clicked mail. It is really confusing and also a big issue for the web version because it means the users can push items they aren't selecting right now if they don't pay enough attention to what's written in the addin.

## Your Environment
* Platform : Office on the web
* Host : Outlook
* Operating System : Win10
* Browser : Chrome (Also tried Firefox and Edge (Chromium-based))

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by hitmanwar** [comment]
Added in the backlog. Internal tracking id: 117617

**Comment by siseli** [comment]
Why has this issue been closed? Has the bug been fixed?
The issue is a major problem when implementing outlook addins.

**Comment by peronald** [comment]
My mistake. This is an issue we are tracking in our backlog.

**Comment by repl-kannan-d** [comment]
Is this issue still open or addressed? We are also running into the same issue. [exextoc](https://github.com/exextoc) could you pls share if there is any workaround for this problem?

**Comment by repl-kannan-d** [comment]
[exextoc](https://github.com/exextoc) Do we have any timeline for this?

**Comment by exextoc** [comment]
Hey @repl-kannan-d ,

This issue is still open and we are following up internally. However, we still have no timelines at this point.

**Comment by exextoc** [comment]
The original problem mentioned here has been fixed and should be available now. In case the issue persists, please open a separate issue with repro steps.
