### ISSUE TITLE
"Excel found problem with one or more formula references in this worksheet" error and broken charts due to custom functions

### ISSUE THREAD

**Issue by leybal** [OfficeDev/office-js#1870]
Hi
Let's consider the case based on [excel-shared-runtime-scenario](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario) example. We want to show chart based on custom function data (`=MYCUSTOMFORMULA(A1,10)`). This custom function can returns matrix different size.  Since we want make dynamic chart we ussed Name Manager to create references to a range of custom function via `=OFFSET()` and `=COUNTIF()`. You can find an example in [this article](https://excelchamps.com/blog/dynamic-chart-range/).
When the chart refers to names which contain the custom function, "Excel found problem with one or more formula references in this worksheet" error occurs and the chart does not display the data. If we go to another sheet and edit a cell, the chart will work correctly.
If variables in Name Manager refers to the standard formula `=RANDARRAY (10,2) * 100`, then everything always works correctly.
Please take a [look at video](https://drive.google.com/file/d/1VgSA7gPUWtSneaYA4Wi43GCnX8mBvTtb/view?usp=sharing).

As soon as we remove `=OFFSET()` from the variable inside the Name Manager, the error disappears. It looks like there are a conflict between `=OFFSET()` and custom function.

## Expected Behavior

We can create a dynamic chart via `=OFFSET()`, `=COUNTIF()` inside Name Manager and a custom function.

## Current Behavior
Creating a dynamic chart based on `=OFFSET()`, `=COUNTIF()` results in an Excel error and breaks a chart.

## Steps to Reproduce, or Live Example

1. Download [shared-runtime-scenario](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario) example.
2. [Specify equivalent XLL](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/make-custom-functions-compatible-with-xll-udf#specify-equivalent-xll-in-the-manifest) in the manifest
3. Add [MYCUSTOMFORMULA custom function](https://gist.github.com/leybal/a52e932159a454d553e4998e53ab146a)
4. Download [the excel file](https://drive.google.com/file/d/1cHaljBBqS1tbZnRijMxxP4nheGepTnPE/view?usp=sharing) with variables inside the Name Manager and a chart.
5. Go to Sheet2, edit a cell and go back to Sheet1. You should see a correct chart.
6. Please replace `=MYCUSTOMFORMULA(A1,10)` to `=RANDARRAY(10,2)*100`. The chart should work correctly and there will be no errors. 
 
## Context
The team and I have been tracking this issue for several months. It looks like there are a conflict between `=OFFSET()` and custom function inside the Name Manager. At this stage, we cannot create dynamic charts based on custom formulas.

## Your Environment
* Platform: PC desktop and Mac
* Host: Excel
* Office version number: 2104 (13929.20372)
* Operating System: Windows 10 and Mac OS

**Comment by xiaochunms** [comment]
@leybal Thanks to report the issue. You may can try the workaround by changing the Counts defined name to “=IFERROR(OFFSET(Sheet1!$D$1,0,0,Sheet1!$A$2),0)”. Please let me know if it does not work.

**Comment by leybal** [comment]
@xiaochunms thanks a lot. Your recommendations helped us.
