### ISSUE TITLE
GetAppManifests EWS operation for Outlook add-in

### ISSUE THREAD

**Issue by vijay665** [OfficeDev/office-js#1872]
office-js

I have followed the MSDN document to get the app manifests for a mailbox using makeEwsRequestAsync to GetAppManifests EWS operation but it returns error response as **ErrorAccessDenied**.

[https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/getappmanifests-operation?redirectedfrom=MSDN](url)

`<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
  <s:Body>
    <s:Fault>
      <faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorAccessDenied</faultcode>
      <faultstring xml:lang="en-US">The requested web method is unavailable to this caller or application.</faultstring>
      <detail>
        <e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">ErrorAccessDenied</e:ResponseCode>
        <e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">The requested web method is unavailable to this caller or application.</e:Message>
      </detail>
    </s:Fault>
  </s:Body>
</s:Envelope>`

function getSoapEnvelope(request) {
    // Wrap an Exchange Web Services request in a SOAP envelope. 
    var result =
		'<?xml version="1.0" encoding="utf-8"?>' +
		'				<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" ' +
		'					xmlns:xsd="http://www.w3.org/2001/XMLSchema" ' +
		'					xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" ' +
		'					xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"' +
		'					xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">' +
		'					<soap:Header>' +
		'					<t:RequestServerVersion Version="Exchange2013_SP1" />' +
		'                   <t: MailboxCulture>en-US</t: MailboxCulture >' +
		'                        <t: TimeZoneContext>' +
		'                            <t:TimeZoneDefinition Id="GMT Standard Time"/>' +
		'                   </t: TimeZoneContext >' +
		'					</soap:Header>' +
		'					<soap:Body >' +
		'						<m:GetAppManifests>' +
		'						<m:ApiVersionSupported>1.1</m:ApiVersionSupported>' +
		'						<m:SchemaVersionSupported>1.1</m:SchemaVersionSupported>' +
		'						</m:GetAppManifests>' +
		'					</soap:Body>' +
		'				</soap:Envelope>';

    return result;
};

function getAppManifestsRequest() {
    // Return a GetAppManifests EWS operation.
    var requestbody =
        '	<t:GetAppManifests>' +
        '		<t:ApiVersionSupported>1.1</m:ApiVersionSupported>' +
        '		<t:SchemaVersionSupported>1.1</m:SchemaVersionSupported>' +
        '	</t:GetAppManifests>';

    return requestbody;
};

// Send an EWS request
function sendRequest() {
    // Create a local variable that contains the mailbox. 
    var mailbox = Office.context.mailbox;
    var request = getAppManifestsRequest();
    var envelope = getSoapEnvelope(request);

    mailbox.makeEwsRequestAsync(envelope, callback);
};

**Comment by markdon** [comment]
`makeEwsRequestAsync` only supports a limited set of operations listed [here](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/understanding-outlook-add-in-permissions#readwritemailbox-permission).

It may not solve your issue, but getting an EWS auth token from [getCallbackTokenAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-preview#getCallbackTokenAsync_callback__userContext_) and using it to make a request directly to [ewsUrl](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-preview#ewsUrl) has less limitations.

**Comment by exextoc** [comment]
Based on @markdon's comment it's correct that
> `makeEwsRequestAsync` only supports a limited set of operations listed [here](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/understanding-outlook-add-in-permissions#readwritemailbox-permission).

So it is not possible to use GetAppManifests with makeEwsRequestAsync. As for the second comment, getting an EWS auth token actually has more limitations.

Can you please share the use case for this? What information are you trying to get from the mailbox's App manifest? Getting the mailbox's app manifest could cause privacy issues since add-ins should not be able to see what other add-ins are installed on the mailbox.

**Comment by vijay665** [comment]
Thank you for looking into my issue.

We were deploying the App manifest to the user mailbox using API programmatically where we enable supportsSharedFolders, supportsPinning, and other configurations in manifest.xml.

One scenario is that the App not visible on the shared mailbox, to confirm whether this **supportsSharedFolders** node present in the App manifest.xml we use to check the latest manifest located at `C:\Users\[USER NAME]\appdata\local\microsoft\office\16.0\Wef\.`

This is time consuming process to validate individual user mailbox, so get manifest from the exchange will help to quick troubleshooting.

**Comment by exextoc** [comment]
To clarify your use case, is it only trying to get this information through the add-in while the add-in is running? Or is the use case for getting the information in general? In general, there are PowerShell commands such as this: https://docs.microsoft.com/en-us/powershell/module/exchange/get-app?view=exchange-ps that could help with retrieving the mentioned information.

**Comment by vijay665** [comment]
> To clarify your use case, is it only trying to get this information through the add-in while the add-in is running? Or is the use case for getting the information in general? In general, there are PowerShell commands such as this: https://docs.microsoft.com/en-us/powershell/module/exchange/get-app?view=exchange-ps that could help with retrieving the mentioned information.

Yes, that's correct, we have diagnostics in our Mail App where we need an option to download the App manifest while the add-in is running. It will be very helpful if you share the permissions required to GetAppManifests as per the document https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/getappmanifests-operation?redirectedfrom=MSDN

**Comment by exextoc** [comment]
@vijay665 The ability to call GetAppManifests isn't supported, either directly or through makeEwsRequestAsync. I assume you're trying to look at the results for GetAppManifests to confirm that users are using the most recent version of your add-in, i.e; includes your updates to the manifest recently released. If so, one workaround you could use when updating your manifest is to also update the URLs it points to, to include some query parameters. Then on the js side you can look for those query parameters when the add-in loads to confirm if the most recent version of the add-in is being loaded or not. Hope that helps.

**Comment by vijay665** [comment]
> @vijay665 The ability to call GetAppManifests isn't supported, either directly or through makeEwsRequestAsync. I assume you're trying to look at the results for GetAppManifests to confirm that users are using the most recent version of your add-in, i.e; includes your updates to the manifest recently released. If so, one workaround you could use when updating your manifest is to also update the URLs it points to, to include some query parameters. Then on the js side you can look for those query parameters when the add-in loads to confirm if the most recent version of the add-in is being loaded or not. Hope that helps.

**Comment by vijay665** [comment]
> > @vijay665 `**The ability to call GetAppManifests isn't supported, either directly or through makeEwsRequestAsync**`. I assume you're trying to look at the results for GetAppManifests to confirm that users are using the most recent version of your add-in, i.e; includes your updates to the manifest recently released. If so, one workaround you could use when updating your manifest is to also update the URLs it points to, to include some query parameters. Then on the js side you can look for those query parameters when the add-in loads to confirm if the most recent version of the add-in is being loaded or not. Hope that helps.


Thanks for the suggestion. Also, could you please update the document  if GetAppManifests did not support either by makeEwsRequestAsync or with EWS auth token from getCallbackTokenAsync?

https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/getappmanifests-operation?redirectedfrom=MSDN

**Comment by exextoc** [comment]
Thanks for the suggestion. It's not part of the EWS documentation, but the supported APIs are documented in a couple of places in the Outlook add-ins documentation.

For `makeEwsRequestAsync`, the EWS APIs supported by this method are documented here in [Call web services from an Outlook add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/web-services#ews-operations-that-add-ins-support).

And the EWS token returned by `getCallbackTokenAsync` is [limited to retrieving the current item and its attachments](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-1.5&preserve-view=true#getCallbackTokenAsync_options__callback_).
