### ISSUE TITLE
Outlook Event attendees (individual/group) do not have `recipientType` set as expected

### ISSUE THREAD

**Issue by markdon** [OfficeDev/office-js#1873]
On Mac clients and https://outlook.office.com/, When composing an Event (aka. Appointment) and retrieving optional/required attendees ([requiredAttendees.getAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.appointmentcompose?view=outlook-js-preview#requiredAttendees)) the individual users and groups ([EmailAddressDetails](https://docs.microsoft.com/en-us/javascript/api/outlook/office.emailaddressdetails?view=outlook-js-preview)) in the same organisation do not have their [`recipientType` ](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailboxenums.recipienttype?view=outlook-js-preview) property set to `user` or `distributionList`, instead they are set as `other`.

This is likely already reported in #330, however this is not limited to the Mac client.

## Expected Behavior
When retrieving attendees from 
`Office.context.mailbox.item.requiredAttendees.getAsync()`
`Office.context.mailbox.item.optionalAttendees.getAsync()`
The objects returned have their `recipientType` property set to `user` for users and `distributionList` for groups.
This is how Windows behaves.
![image](https://user-images.githubusercontent.com/9063681/118762754-145d0380-b8ba-11eb-9149-8bbb249612ba.png)

## Current Behavior
When retrieving attendees from 
`Office.context.mailbox.item.requiredAttendees.getAsync()`
`Office.context.mailbox.item.optionalAttendees.getAsync()`

In Chrome,
The user and group objects returned have their `recipientType` property set to `other`.
![image](https://user-images.githubusercontent.com/9063681/118763729-af0a1200-b8bb-11eb-9bd4-cd9536623262.png)

In Mac,
The user objects their `recipientType` property set to `user` as expected. 
The group objects have their `recipientType` property set to `other` in error.
![image](https://user-images.githubusercontent.com/9063681/118763676-97cb2480-b8bb-11eb-8b6f-d2ffce6e086f.png)

## Steps to Reproduce, or Live Example
[ScriptLab Gist](https://gist.github.com/markdon/ab3b2629dd617c25538106046a2bbdbd)
Before retrieving attendees with the button, add at least a user and group to requiredAttendees, similar to screenshots above. 

## Context
We'd like to be able to discern between individual users and groups. From attendees, we're trying to select users (email addresses) that can be used to log in to another application which our addin is integrating. A group's email can not be used to log in and this application does not support selecting a group to have its members be moderators.

## Your Environment
The incorrect behaviour is reproduced in:
* Platform: Mac, Chrome
* Host: Outlook
* Office version number: Mac 16.49 (M365 sub), https://outlook.office.com/
* Operating System: macOS 11.3.1
* Browser: Chrome

**Comment by exextoc** [comment]
@markdon Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point. Internal tracking id:
OWA:  117717
Mac: 5125404

**Comment by exextoc** [comment]
Hey @markdon ,

According to our documentation, "group" is not a valid recipientType. The recipient types are [documented here](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailboxenums.recipienttype?view=outlook-js-preview) and are expected to show "other" for group email addresses.

**Comment by markdon** [comment]
@exextoc Thanks for looking at this again 😁  I guess I'm mixing my terminology. When I say group, I'm referring to a recipient that is not an individual and might be a Team, Sharepoint group or similar. When represented as an [EmailAddressDetails](https://docs.microsoft.com/en-us/javascript/api/outlook/office.emailaddressdetails?view=outlook-js-preview) object, I expect them to have the `recipientType` of `distributionList`.

**Comment by exextoc** [comment]
Thanks for reporting this issue . It has been put on our backlog. We unfortunately have no timelines to share at this point .We have a similar github issue at https://github.com/OfficeDev/office-js/issues/1909 .Please follow this link for future updates on this bug

**Comment by exextoc** [comment]
This issue has been fixed. Please verify and confirm.

**Comment by markdon** [comment]
Fixed as tested via Script Lab on OWA and Mac 16.74.1. Thanks @exextoc!
