### ISSUE TITLE
Web browser outlook add-in tab navigation issue for web components

### ISSUE THREAD

**Issue by mydavidzhang** [OfficeDev/office-js#1875]
In web browser (like Chrome) open outlook add-in (https://outlook.office.com/mail/inbox), when there are multiple web components inside add-in, could not use tab to navigate between them. The first web component can be focused, but after click tab the focus will go to add-in close button, which should go to the second web component.

## Expected Behavior
Should be able to use tab to navigate between web components

## Current Behavior
 The first web component can be focused, but after click tab the focus will go to add-in close button although there are other web components.

## Steps to Reproduce, or Live Example
Library used : https://appsforoffice.microsoft.com/lib/1/hosted/Office.js

1. Open https://outlook.office.com/mail/inbox
2. Open add-in
3. Use tab to navigate to add-in content which has web components
4. First web component is focused
5. Use tab try navigate to second web component
6. Second web component could not be focused, and add-in close button is focused

Can hack add-in iframe content as below
```
<html>
<body>
<wc-btn></wc-btn>
<wc-btn></wc-btn>
<wc-btn></wc-btn>
</body>
</html>
```
Then in Chrome -> dev tool -> Sources -> Snippets run below code:
// Create a class for the element
class WCBtn extends HTMLElement {
  constructor() {
    super();
    const shadow = this.attachShadow({mode: 'open'});
    const btn = document.createElement('button');
    btn.innerText = "Web Component Button";
    shadow.appendChild(btn);
  }
}
customElements.define('wc-btn', WCBtn);
<img width="325" alt="Screen Shot 2021-05-19 at 1 25 39 PM" src="https://user-images.githubusercontent.com/10460331/118884236-0c499780-b8ab-11eb-9cde-1401746ef0a4.png">
<img width="333" alt="Screen Shot 2021-05-19 at 1 31 02 PM" src="https://user-images.githubusercontent.com/10460331/118882299-e4f1cb00-b8a8-11eb-8614-e83095a17a61.png">
<img width="725" alt="Screen Shot 2021-05-19 at 1 34 48 PM" src="https://user-images.githubusercontent.com/10460331/118882294-e3c09e00-b8a8-11eb-8975-467bf48e44c7.png">
Attached demo video (unzip to .mov file)
[office-js_issues_1875.mov.zip](https://github.com/OfficeDev/office-js/files/6511545/office-js_issues_1875.mov.zip)

## Context
Tab navigation issue is critical Accessibility issue. Impact customer to use keyboard navigate.

## Your Environment

* Platform: Mac
* Browser : Chrome

**Comment by exextoc** [comment]
@mydavidzhang We cannot repro this with our test add-ins. You need to add tabIndex in your add-in html code, so that tab navigation works correctly.
