### ISSUE TITLE
"Add-in" is not loaded on Office 365 ProPlus 1909 12026.20344

### ISSUE THREAD

**Issue by Kronenberg** [OfficeDev/office-js#1876]
Good day, 
Add-in" is not loaded for some users. _( screenshot with error message was attached to this article below )_
Windows and office versions are consistent across all users. 

## Expected Behavior

Add-in should be opened without any errors.

 ## Question
Do you have any known issues for this specific case/version or what might be the root cause for this?
Can you give me an idea what can help in this case?

p.s. so far, this error can be related to the security settings on the computer itself and Outlook cannot make a request to the remote server since outlook has no rights/permissions.

## Your/Any User Environment
VDI; Citrix presentation layer, VMWare back end
-Windows 10 10.0.18363
-Office 365 ProPlus 1909 12026.20344
Windows and office versions are consistent across all users. All workstations use SentinelOne endpoint protection.
The  users in question have no difference in OS or Office versions, or any other meaningful factor.

## Useful logs
Here is what happen when user click on "Add-in" 
![error](https://user-images.githubusercontent.com/13053374/118940537-80427900-b959-11eb-9c46-61d1f98590f5.png)

**Comment by exextoc** [comment]
Is seems that this an older version of Office, please update your Office 365 version and see if this problem still persists.
