### ISSUE TITLE
Cannot install add-in in shared or delegate mailbox in OWA

### ISSUE THREAD

**Issue by sarea** [OfficeDev/office-js#1877]
when I open another mailbox from the top left menu, I'm not able to install an add-in there, I got an error message that says:

> The operation on mailbox failed because it's out of the current user's write scope.

![Screenshot 2021-05-20 at 11 12 57](https://user-images.githubusercontent.com/16371285/118953572-3cea0980-b95d-11eb-9dbe-1b66071ffab7.png)

We couldn't find a way in the admin settings or in the online exchange settings to give that permission.
Even when installing the add-in from the admin center for that mailbox, we don't get it installed.

For the delegate accounts, that's fine, as we can log in to those accounts using the email id and the password and install the add-in, but the shared mailbox doesn't have a way to log in directly.

Knowing that this functionality used to work a while ago.

**Comment by exextoc** [comment]
> when I open another mailbox from the top left menu, I'm not able to install an add-in there, I got an error message that says:
> 
> > The operation on mailbox failed because it's out of the current user's write scope.
> 
> ![Screenshot 2021-05-20 at 11 12 57](https://user-images.githubusercontent.com/16371285/118953572-3cea0980-b95d-11eb-9dbe-1b66071ffab7.png)
> 
> We couldn't find a way in the admin settings or in the online exchange settings to give that permission.
> Even when installing the add-in from the admin center for that mailbox, we don't get it installed.
> 
> For the delegate accounts, that's fine, as we can log in to those accounts using the email id and the password and install the add-in, but the shared mailbox doesn't have a way to log in directly.
> 
> Knowing that this functionality used to work a while ago.

Can you please specify which client is this? Is this happening in Outlook on the Web/Mac/Win32 or mobile client?

**Comment by sarea** [comment]
Hi @exextoc, it's on the OWA

**Comment by exextoc** [comment]
Can you please share us a repro video and/or the exact repro steps of this issue? This would help us try to repro this locally.

**Comment by sarea** [comment]
Hi @exextoc, step to reproduce the issue:

- user 'A' has access to user 'B'
- user 'A' login to user 'B' by open another mailbox from the top right corner list
- now in the window of the user 'B' mailbox, the user  'A' try to install the add-in from 'create a new draft' => get Add-ins => My add-ins => add custom add-in => add from URL then install!
- the result is the screenshot that added in the issue discription

Hope that helps

**Comment by exextoc** [comment]
Open Another Mailbox" scenario is not fully supported on Outlook Web Add-ins as of now. We are working on our document update to reflect this status.  We track Outlook add-in feature requests on our [Tech Community Page](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by Emailgistics-Arjun** [comment]
With support for shared mailboxes in the preview addin. Will this issue be resolved?

**Comment by exextoc** [comment]
@Emailgistics-Arjun - not quite and I'd like to elaborate on why that's the case. For now I'll be concentrating on delegateAccess feature (which is in production for OWA) - a user in the org having shared their folders with you/provided you with delegate access to their mailbox. I'll get to sharedMailboxes later here.

The moment you're logging into the delegate account using the email and pwd, it's not technically a sharedFolder anymore. It's as though you're signing into your own account. From an add-ins perspective of what we call 'support for delegateAccess/sharedFolders', this is not truly a sharedFolder scenario (I'll also get to the proper way of setting this up). The moment you log in to the account explicitly, you'll get add-ins that were installed for that secondary account but the items will no longer be considered in a shared context.

Our feature for sharedFolders/delegateAccess let's you run add-ins that you have installed for your mailbox, on a mailbox the other user has shared with you. You don't need to install the same add-in on the other users mailbox to be able to use it. In the example shared above, user A has access to user B's mailbox (user B delegated their mailbox to user A). From addins side, what we support is that the add-ins user A has available for their mailbox, the same add-ins can be used when navigating to items in User B's mailbox (User B might as well have 0 add-ins installed for themselves). There is however a dependency that the add-in developers should support sharedFolders (in their manifest) too for the add-in installed for user A to work when accessing items from user B's account. If the specific add-in in question doesn't mark support for sharedFolders in their manifest, you won't be able to use that addin when accessing user B's account.

To be able to set this up, all user A needs to do is navigate to OWA, then from the left navigation pane (where folder structures are present), right click on the parent Folder tree called 'Folders' and then hit 'Add sharedFolder' and enter User B's email address. This will add User B's mailbox to your navigation pane and user A can access folders/items from User B's account. Now, when you navigate to an item in User B's mailbox, we load all add-ins from User A's account and show only those add-ins that have the manifest change for sharedFolders. All other add-ins will be hidden. This is a true sharedFolder/delegateAccess scenario from add-ins perspective.

Now speaking of sharedMailboxes - sharedMailboxes share the same concept as sharedFolders, you don't need the add-in installed for the sharedMailbox to be able to use it or log into the sharedMailbox. You just need to mount the sharedMailbox correctly (as above) to be able to use addins (assuming they have the manifest change) when accessing items from a sharedMailbox. That said, sharedMailboxes support is in preview and only for win32 right now. As and when it goes into preview for OWA, we'll update the documentation to reflect that.

Hope this helps and feel free to get back to us if you have any questions or require further clarifications.
