### ISSUE TITLE
Unable to add shared runtime to common Manifest

### ISSUE THREAD

**Issue by harit-m-kumar** [OfficeDev/office-js#1878]
We have a common manifest for our add-in which works on all the three platforms - Excel, Word and PowerPoint. Currently, I was trying to add shared JavaScript runtime to our application, because i was facing this issue : 

"window.sessionStorage" gets cleared when our application opens a new PowerPoint instance to load a file.

So I was referring the given link -

https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime

On adding the given tags to our common manifest, the add-in was not loading in Word (but not in Excel and PowerPoint), probably because Shared Runtime is available only to Excel and Powerpoint.

  <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="SharedRuntime" MinVersion="1.1"/>
    </Sets>
  </Requirements>

Kindly let me know if there is a way to handle this in the same manifest?

**Comment by jeremy-msft** [comment]
Hi @harit-m-kumar, thanks for reaching out. Unfortunately this isn't possible today -- requirement sets apply to all Hosts declared in your manifest.
