### ISSUE TITLE
Can't fetch email recipient when it's not saved in Outlook 

### ISSUE THREAD

**Issue by mkuszewski** [OfficeDev/office-js#1879]
## Expected Behavior
When calling the method `Office.context.mailbox.item.to.getAsync()`, the array of recipient objects should be returned.

## Current Behavior
Method `Office.context.mailbox.item.to.getAsync()` returns an empty array. This issue occurs only if a recipient isn't saved in Outlook (unknown/new recipient email). 
 
## Steps to Reproduce, or Live Example

- create new email (draft)
- in the recipient field put some unknown email which wasn't used before (i.e. newEmail1234@test.com) and **don't press enter after typing the email** 
- click on the subject field (optional)
- save the draft (Ctrl+S) 
- call `Office.context.mailbox.item.to.getAsync()` which returns empty array
 
## Additional details:
The issue occurs when provided email isn't recognized by Outlook and shouldn't get an oval bubble with X button around the email. It looks like a normal text :
![Screenshot 2021-05-21 at 10 59 45](https://user-images.githubusercontent.com/12995894/119112374-4e4a1900-ba24-11eb-9fde-2b798b7a66d6.png)
![Screenshot 2021-05-21 at 11 00 04](https://user-images.githubusercontent.com/12995894/119112487-6b7ee780-ba24-11eb-8224-8092a030de09.png)

For the following case it works correctly (by pressing enter after typing an unknown email, it gets the blueish oval bubble around)
![Screenshot 2021-05-21 at 11 00 12](https://user-images.githubusercontent.com/12995894/119112232-2d81c380-ba24-11eb-9504-80af82423501.png)

 ## Context

The issue hardly appears on the desktop Outlook app because an unknown contacts gets saved very quickly (after pressing tab or by going to the next input).

Is there any alternative to `Office.context.mailbox.item.to.getAsync()` for fetching a recipient? 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Mac OS 11.3
* Browser (if using Office on the web): Chrome 90.0

**Comment by exextoc** [comment]
Unfortunately this is by design and you can get the recipients in OWA only after this is saved.
