### ISSUE TITLE
More then one dialog can be opened from Add-in Command

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/office-js#188]
Docs state that "An Office Add-in can have only one dialog box open at any time." However, if opened from a Add-In command, more then one dialog can be opened at one time by clicking on the add-in command button repeatedly.

## Steps to Reproduce, or Live Example
1. Add ScriptLab to [Excel]
2. Click "Tutorial" from "ScriptLab" ribbon
3. When the dialog opens, click "Tutorial" again
4. Observe that another dialog opened.

![image](https://user-images.githubusercontent.com/13841696/42341568-5851d780-8048-11e8-931f-12b43aff192a.png)

**Comment by Rick-Kirkham** [comment]
@dmitriyyepishin Can you give me the URL of the documentation that you quoted. It is erroneous. It should say that a given host page (such as a page in a task pane) can only have one dialog open at a time. But every time you click a ribbon button, you launch a new UI-less host page, so you are getting a new dialog every time.

**Comment by JuaneloJuanelo** [comment]
@Rick-Kirkham  this is the page (thanks Bing!)  https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins


can you please fix this documentation error? thANKS!

**Comment by Rick-Kirkham** [comment]
Actually, what that document says is exactly right:
```
"Note
You can open only one dialog box from a host window. An attempt to open another dialog box generates an error. For example, if a user opens a dialog box from a task pane, she cannot open a second dialog box, from a different page in the task pane. However, when a dialog box is opened from an add-in command, the command opens a new (but unseen) HTML file each time it is selected. This creates a new (unseen) host window, so each such window can launch its own dialog box. For more information, see Errors from displayDialogAsync."
```

Later, in the Errors section it says:
`A host window, such as a task pane, can only have one dialog box open at a time.` 
This is also correct.

@dmitriyyepishin 's quotation "An Office Add-in can have only one dialog box open at any time." does not appear in the article, which is why I asked him for the URL of where he is seeing it.

**Comment by JuaneloJuanelo** [comment]
ok could not find that literal instance. closing.
