### ISSUE TITLE
We receive wrong window.outherWidth value when the task pane is closed

### ISSUE THREAD

**Issue by ikaban** [OfficeDev/office-js#1880]
Hi, 
we found a problem with window.outerWidth in Excel for web. When a user resize the browser window and the task pane is open window.outerWidth changes, but if a user close the task pane and resize browser window window.outerWidth does not change. It looks like a bug.

## Expected Behavior

When a user resize a browser window and the task pane is closed, the window.outerWidth should change.

## Current Behavior
When a user resize the browser window and the task pane is closed, the window.outerWidth does not change. The window.outerWidth value is updated only after the page is reloaded or the task pane is open. 

## Steps to Reproduce, or Live Example
* Link to video: [link](https://drive.google.com/file/d/1nXsSK0OfvRtvr_wzn3cPv1MliHy1c2rL/view?usp=sharing) (outerWidth value is displayed in the console)
* Link to code: [link](https://github.com/ikaban/PnP-OfficeAddins/tree/outerWidth-bug)
* Additional details:
In the office-api-helpers.ts file, we added the displayInIframe: true parameter to the Office.context.ui.displayDialogAsync function and added console.log, which displays the window.outerWidth value.

## Context
We calculate the size of the dialog box base on window.outerWidth. If the a user decides to resize the browser window with closed the task pane, the dialog box receive wrong window.outerWidth and the size dialog box is displayed incorrectly. After reload page or open the task pane window.outerWidth value will be updated and the size dialog box will be displayed correctly.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.14117.35903
* Operating System: Mac OS Big Sur 11.3.1
* Browser: Google Chrome

**Comment by jipinshi** [comment]
Tried windows in Chrome, the window.outerWidth should mean the width of the browser size which is browser behavior, so it is not related to taskpane show or not, since when it show, it will resize the left content width. If your location wants to center the dialog in the middle of the content, I guess you can hook Office.addin.onVisibilityModeChanged and then get the taskpane width, and then get the content width. And this solution is limited to web side, not work for mac excel and windows excel.

**Comment by jipinshi** [comment]
@ikaban, let me know whether the comment above helps you.

**Comment by ikaban** [comment]
@jipinshi thank you for your answer! It seems like we have a misunderstanding.

Task pane width is not related to our issue. We need to receive the correct browser width. 

We create a Dialog box via Office.content.ui.displayDialogAsync() based on browser width (window.outerWidth).

For example: Office.context.ui.displayDialogAsync('https://myDomain/myDialog.html', {height: 100, width: outherWidth / 2}); 

The problem is that when a user has resized a browser with a closed task pane, outerWidth is not recalculated. This has been demonstrated in the video ([link](https://drive.google.com/file/d/1nXsSK0OfvRtvr_wzn3cPv1MliHy1c2rL/view)).

Please let us know if you were able to reproduce the problem using the video or the steps above.

**Comment by jipinshi** [comment]
@ikaban, window.outwidth is browser behavior, I tried chrome it can work, so looks like there is bug in the browser you are using.

**Comment by ikaban** [comment]
@jipinshi, you are right. All works correctly in Safari and Mozilla Firefox. But in Google Chrome we have a problem. Thank you so much!

**Comment by jipinshi** [comment]
@ikaban, great to know it can work in other browser, so I will close this case. If you have other issues, please open new.
