### ISSUE TITLE
Can't create custom contextual tab

### ISSUE THREAD

**Issue by matthe68** [OfficeDev/office-js#1883]
## Expected Behavior
I have been reading through Microsoft documentation for Office Web Add-Ins about how to create a custom contextual tab. It states that I need to have a shared runtime to do this and tells me that I need to add <Runtimes> <Runtime resid="Taskpane.Url" lifetime="long" /> </Runtimes> directly following the <Host> tag. What should happen is simply that I have a validated manifest file and can move on with my custom contextual tab. 
## Current Behavior
When I do this I receive an error saying "The element Host in namespace "https://schemas.microsoft.com/office/taskpaneappversionoverrieds' has invalid child element 'Runtimes' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrieds'. List of possible elements expected: 'AllFormFactors, DesktopFormFactor' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides'. 

## Manifest File is Shown Below
<?xml version="1.0" encoding="UTF-8"?>

<OfficeApp 
          xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" 
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" 
          xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides"
          xsi:type="TaskPaneApp">

  

  
  <Id>70777893-f516-42a4-a88e-ab6717d66672</Id>

  
  <Version>1.0.0.0</Version>
  <ProviderName>GPS</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  
  <DisplayName DefaultValue="Athena Utilities" />
  <Description DefaultValue="Athena Utilities"/>
  
  <IconUrl DefaultValue="~remoteAppUrl/Images/Button32x32.png" />

  <SupportUrl DefaultValue="http://www.contoso.com" />
  
  <AppDomains>
    <AppDomain>AppDomain1</AppDomain>
    <AppDomain>AppDomain2</AppDomain>
    <AppDomain>AppDomain3</AppDomain>
  </AppDomains>
  
  
  
  <Hosts>
    <Host Name="Workbook" />
  </Hosts>
  
  <Requirements>
	<Sets DefaultMinVersion="1.1">
		<Set Name="SharedRuntime" MinVersion="1.1"/>
	</Sets>
  </Requirements>
  <DefaultSettings>
    <SourceLocation DefaultValue="~remoteAppUrl/View/Login.html" />
  </DefaultSettings>
  

  <Permissions>ReadWriteDocument</Permissions>

  
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
    
    
    <Hosts>
      
      
      
      <Host xsi:type="Workbook">
		<Runtimes>
		  <Runtime resid="Taskpane.Url" lifetime="long" />
		</Runtimes>
        
        <DesktopFormFactor>
          
          <GetStarted>
            
            <Title resid="A.GetStarted.Title"/>

            
            <Description resid="A.GetStarted.Description"/>

            
            <LearnMoreUrl resid="A.GetStarted.LearnMoreUrl"/>
          </GetStarted>
          
          
          <FunctionFile resid="A.Login.Taskpane.Url"/>
          
          <ExtensionPoint xsi:type="PrimaryCommandSurface">
            
            <CustomTab id="Athena.Tab">
              
              <Group id="A.Login">
                
                <Label resid="A.Login.Label" />
                
                
                <Icon>
                  <bt:Image size="16" resid="A.tpicon_16x16" />
                  <bt:Image size="32" resid="A.tpicon_32x32" />
                  <bt:Image size="80" resid="A.tpicon_80x80" />
                </Icon>

                
                <Control xsi:type="Button" id="A.Login.Login">
                  <Label resid="A.Login.Login.Label" />
                  <Supertip>
                    
                    <Title resid="A.Login.Login.Tt_title" />
                    
                    <Description resid="A.Login.Login.Tt_desc" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="A.tpicon_16x16" />
                    <bt:Image size="32" resid="A.tpicon_32x32" />
                    <bt:Image size="80" resid="A.tpicon_80x80" />
                  </Icon>

                  
                  <Action xsi:type="ShowTaskpane">
                    <TaskpaneId>ButtonId1</TaskpaneId>
                    
                    <SourceLocation resid="A.Login.Taskpane.Url" />
                  </Action>
                </Control>
              </Group>
			  <Label resid="Athena.Tab.Label"/>
            </CustomTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>
    
    
    <Resources>
      <bt:Images>
        <bt:Image id="A.tpicon_16x16" DefaultValue="~remoteAppUrl/Images/Button16x16.png" />
        <bt:Image id="A.tpicon_32x32" DefaultValue="~remoteAppUrl/Images/Button32x32.png" />
        <bt:Image id="A.tpicon_80x80" DefaultValue="~remoteAppUrl/Images/Button80x80.png" />
      </bt:Images>
      <bt:Urls>
        <bt:Url id="A.DesktopFunctionFile.Url" DefaultValue="~remoteAppUrl/Functions/FunctionFile.html" />
        <bt:Url id="A.Login.Taskpane.Url" DefaultValue="~remoteAppUrl/View/Login.html" />
        <bt:Url id="A.GetStarted.LearnMoreUrl" DefaultValue="https://go.microsoft.com/fwlink/?LinkId=276812" />
      </bt:Urls>
      
      <bt:ShortStrings>
		<bt:String id="A.GetStarted.Title" DefaultValue="New Harris Utilities Replacement" />
		<bt:String id="Athena.Tab.Label" DefaultValue="Athena" />
		<bt:String id="A.Login.Label" DefaultValue="Login" />
        <bt:String id="A.Login.Login.Label" DefaultValue="Login" />
		<bt:String id="A.Login.Login.Tt_title" DefaultValue ="Login Taskpane"/>
      </bt:ShortStrings>
      
      <bt:LongStrings>
        <bt:String id="A.Login.Login.Tt_desc" DefaultValue="Click to Show the Login Taskpane" />
        <bt:String id="A.GetStarted.Description" DefaultValue="Click the Login button on the Athena Tab to sign in and get started." />
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
  

</OfficeApp>

**Comment by lindalu-MSFT** [comment]
Hi @matthe68 Please post this question on our [office-js Q&A forum](https://docs.microsoft.com/en-us/answers/topics/office-js-dev.html).

**Comment by ElizabethSamuel-MSFT** [comment]
Closing out as author was asked to post this to Q&A.
