### ISSUE TITLE
Office.context.mailbox.item.itemId discrepancy between Desktop and OWA - SharedCalendars

### ISSUE THREAD

**Issue by bx-steven** [OfficeDev/office-js#1884]
Accessing Outlook Shared Calendar item via REST API from Outlook Desktop is failing.

## Expected Behavior
When retrieving a calendar item Id from a shared calendar context, the Id's should match when opened on Outlook Web App and Outlook Desktop.

## Current Behavior
The value we are retrieving from window.context.mailbox.item.itemId is different when retrieved from Outlook Web App and Desktop. The subsequent calls from outlookRestCall are failing on the error `HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).`

## Steps to Reproduce, or Live Example

* Additional details:
  1. Previously, we've had a flag `officeUtil.item.getSharedPropertiesAsync` in which we would use the following REST Url https://outlook.office.com/api/v2.0/users/<sharedProps.targetMailbox>/calendar/events/<itemRestId\> but now that flag returns undefined. Because of this property returning undefined, we're now using this REST Url https://outlook.office.com/api/v2.0/me/events/<itemRestId\> which works in OWA.

## Context
We were previously able to load the addin from shared calendar context. Now it either crashes or loads indefinitely on the same error message.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office 365 Version 2101
* Operating System: Windows 10 v1909
* Browser (if using Office on the web): Chrome 89

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
To confirm, the client at fault is Outlook Win32? Here you're getting getSharedPropertiesAsync as undefined and an incorrect itemId that causes the REST call to fail but OWA works as expected?

**Comment by bx-steven** [comment]
The client is running on 64 bit version. Confirming that we're getting getSharedPropertiesAsync as undefined. The incorrect itemId is causing the REST call to fail on Desktop whereas the REST call works as expected on OWA.

**Comment by exextoc** [comment]
Is this a calendar that someone(another user) shared with you/gave you delegate permissions to or does this calendar belong to a sharedMailbox to which you have access permissions?

**Comment by bx-steven** [comment]
This is for another user's calendar that was shared with me/gave me delegate permissions.

**Comment by exextoc** [comment]
We're unable to reproduce the issue on our end. A couple of things to try:
 - There should be a newer version of Office available to upgrade to. Can you try to upgrade to see if it still reproduces?
- Does this happen for all calendars shared with you or just for 1 user? If latter, maybe try revoking the permissions, deleting the calendar from your outlook and then requesting them to share again to see if this fixes it.
- Are other folks using the add-in also seeing this issue - getSharedProperties being undefined?
- If it still repro's post an upgrade, could you share the repro steps for us to try it on our end. It'll be good to know who created that event on the shared calendar, is the person who shared the calendar the owner of the item (appointmentOrganizer) or is it a meeting that they are an attendee on (appointmentattendee)? What permissions did they grant to their calendar and how they shared their calendar with you.
- If you use multiple add-ins on calendars, when you open your calendar item as opposed to a shared calendar item, the shared calendar item should only show a subset of the addins from what is shown when opening an item from your own calendar. Do you see this happening? (if you don't have multiple add-ins, it's worth trying to install a couple from Store that target Calendars)
- Could you install ScriptLab from Store and try what it returns for getSharedPropertiesAsync, is it still undefined for the shared calendar item? Maybe sharing a small video of the repro would be helpful too.

**Comment by bx-steven** [comment]
I've upgraded my Office to Version 2103, and the addin still crashes. For context, this is happening for multiple users that are trying to open the addin on a shared calendar item. We've tried removing/resharing a calendar (Can view all details) as well which didn't make a difference:

- As mentioned earlier, the primary issue we're dealing with is that the itemId's are mismatched when opening on OWA versus on Desktop and the error we're receiving is `{"code":"ErrorItemNotFound","message":"The specified object was not found in the store."}`. Is there some sort of replication going on when using Desktop app such that we're not actually accessing the same calendar item?
- Additionally, the issue persists whether or not the item on the shared calendar was created by the owner of the shared calendar or if they're just an appointmentattendee.
- As for using multiple add-ins on calendars, we do see only a subset of addins from the shared calendar item but we expect users to be able to use the addin on shared calendar.
- As for ScriptLab, I'm working on getting this installed on my end.

**Comment by bx-steven** [comment]
I've gotten getSharedPropertiesAsync to return some values. Here is the REST endpoint that we used previously:
`https://outlook.office365.com/api/v2.0/users/{sharedProperties.targetMailbox}/calendar/events/{itemRestId}?$select=LastModifiedDateTime,Body,BodyPreview,iCalUId`
I don't believe this is working anymore. Is there a different REST endpoint for shared calendar?

**Comment by exextoc** [comment]
To make sure I understand the current repro:
1. getSharedPropertiesAsync returns value
2. Get rest id by convertToRestID using item.itemId
3. get token via getCallbackTokenAsync
4. Use values from 1 and 2 to construct https://outlook.office365.com/api/v2.0/users/{sharedProperties.targetMailbox}/calendar/events/{itemRestId}?$select=LastModifiedDateTime,Body,BodyPreview,iCalUId
5. Use token from 3 to submit the REST request.

You have the same code in Outlook desktop (windows) and OWA, but only Outlook desktop is returning {"code":"ErrorItemNotFound","message":"The specified object was not found in the store."}

Could you share the code snippet that is doing the above?

**Comment by bx-steven** [comment]
Those are the exact steps we're doing to submit the REST request. To be clear, this endpoint is what was supposed to be use in shared calendar context and wasn't being used for a while, but after getting getSharedPropertiesAsync working, it's still not working: https://outlook.office365.com/api/v2.0/users/{sharedProperties.targetMailbox}/calendar/events/{itemRestId}?$select=LastModifiedDateTime,Body,BodyPreview,iCalUId

At the time this thread began, we were running the non-shared calendar context code even on shared calendars because of getSharedPropertiesAsync returning undefined which gave us the following request:
https://outlook.office365.com/api/v2.0/me/events/{itemRestId}?$select=LastModifiedDateTime,Body,BodyPreview,iCalUId
This endpoint did work for shared calendar items on OWA only but only Outlook Desktop shared calendar items returned {"code":"ErrorItemNotFound","message":"The specified object was not found in the store."}.

Here's the code snippet that's having issues: 

```javascript
function getMeetingItemAdditionalProps(
  restApiAccessToken,
  itemId,
  itemRestProps
) {
  var itemRestId = officeUtil.getItemRestId(itemId);
  var selectStr = itemRestProps.join(",");
  if (!officeUtil.item.getSharedPropertiesAsync) {
    var eventsEndPoint =
      officeUtil.mailbox.restUrl +
      "/v2.0/me/events/" +
      itemRestId +
      "?$select=" +
      selectStr;
    return outlookRestCall(eventsEndPoint, restApiAccessToken);
  } else {
    //In shared calendar context
    var sharedPropsPr = promisify(officeUtil.item.getSharedPropertiesAsync);
    sharedPropsPr({ asyncContext: accessToken }).then(function (
      resSharedProps
    ) {
      var sharedProps = resSharedProps.value;
      var eventsEndPoint =
        sharedProps.targetRestUrl +
        "/v2.0/users/" +
        sharedProps.targetMailbox +
        "/calendar/events/" +
        itemRestId +
        "?$select=" +
        selectStr; //LastModifiedDateTime,Body,BodyPreview,iCalUId";
      return outlookRestCall(eventsEndPoint, restApiAccessToken);
    });
  }
}
```

**Comment by exextoc** [comment]
Focusing on the current state, with getSharedPropertiesAsync working, here are a few things to confirm:
1. What error are you seeing? on both Outlook, and OWA?  Is the error still ErrorItemNotFound?
2. Could you validate the shared property values (especially for targetMailbox) and what you expect?
3. It will be very helpful if you can try the snippet with Script Lab, so we can try the exact same code on our end.  Script Lab has delegate code sample you can start from and compare with your solution as well.

**Comment by bx-steven** [comment]
With getSharedPropertiesAsync working here's what's happening:

1. Addin is crashing with no error message {%22error_msg%22:{},%22user_id%22:%22[MyEmail@domain.com]%22} on Desktop. I can't find the error on OWA though.
2. There are some discrepancies within the shared property values within Script Lab between Desktop and OWA:
On Desktop, the targetMailbox references the shared calendar's mailbox
On OWA, the targetMailbox references my mailbox. 
Target mailbox should be the shared calendar's mailbox.
3. Here's the snippet of code I'm running in ScriptLab for your reference:
```

$("#run").click(run);

function run() {
    var tokenPr = promisify(Office.context.mailbox.getCallbackTokenAsync);
    return tokenPr({ isRest: true }).then(function (result) {
        if (result.status === Office.AsyncResultStatus.Succeeded) {
            var restApiAccessToken = result.value;
            var meetingRestApiAttr = [
                "LastModifiedDateTime",
                "Body",
                "BodyPreview",
                "iCalUId",
            ];
            getMeetingItemAdditionalProps(restApiAccessToken, meetingRestApiAttr);
        }
    });
}

function getMeetingItemAdditionalProps(
    restApiAccessToken,
    itemRestProps
) {
    var itemRestId = Office.context.mailbox.convertToRestId(Office.context.mailbox.item.itemId, Office.MailboxEnums.RestVersion.v2_0);
    var selectStr = itemRestProps.join(",");

    if (Office.context.mailbox.item.getSharedPropertiesAsync) {
        Office.context.mailbox.item.getSharedPropertiesAsync({
            // Pass auth token along. 
            asyncContext: restApiAccessToken
        },
        function (asyncResult1) {
            console.log(asyncResult1)
            let sharedProperties = asyncResult1.value;
            let delegatePermissions = sharedProperties.delegatePermissions;
            console.log(sharedProperties)
            console.log('item Id: ' + itemRestId)
            var eventsEndPoint =
                sharedProperties.targetRestUrl +
                "/v2.0/users/" +
                sharedProperties.targetMailbox +
                "/calendar/events/" +
                itemRestId +
                "?$select=" +
                selectStr; //LastModifiedDateTime,Body,BodyPreview,iCalUId";
            console.log(eventsEndPoint)
            return outlookRestCall(eventsEndPoint, restApiAccessToken);
        })
    }
    else {
        console.log('not shared calendar')
        console.log('item Id: ' + itemRestId)
        var eventsEndPoint =
            Office.context.mailbox.restUrl +
            "/v2.0/me/events/" +
            itemRestId +
            "?$select=" +
            selectStr;
        console.log(eventsEndPoint)
        return outlookRestCall(eventsEndPoint, restApiAccessToken);
    }

}

function outlookRestCall(endPoint, accessToken) {
    return new Promise(function (resolve, reject) {
        $.ajax({
            url: endPoint,
            dataType: "json",
            headers: { Authorization: "Bearer " + accessToken },
        })
        .done(function (item) {
            resolve(item);
        })
        .fail(function (jqXHR, textStatus, errorThrown) {
            var errorMessage =
                "Request Failed: " +
                textStatus +
                ", " +
                "Endpoint: " +
                endPoint +
                ", " +
                errorThrown +
                ". Server response: " +
                jqXHR.responseText;
            reject(errorMessage);
        });
    });
}

function promisify(f) {
    return function (...args) {
        return new Promise((resolve, reject) => {
            function callback(result, error) {
                if (error) {
                    reject(error);
                } else {
                    resolve(result);
                }
            }
            args.push(callback);
            f.call(this, ...args);
        });
    };
}
```

**Comment by bx-steven** [comment]
I just want to reiterate the fact that the office itemRestId's are different on Desktop and OWA for the same calendar item even in Script Lab. Is that to be expected? Even if we get the shared calendar url working, it's still potentially using an incorrect item Id to retrieve the calendar info. Whereas I'm able to verify that using a hard coded OWA ItemRestId, our Desktop plugin retrieves the calendar info and loads fine on shared calendars without errors.

Working endpoint on Desktop Shared Calendar with OWA itemRestId:
https://outlook.office365.com/api/v2.0/me/events/{itemRestId}?$select=LastModifiedDateTime,Body,BodyPreview,iCalUId

**Comment by exextoc** [comment]
We were unable to repro the issue you are seeing. Are you using a [hybrid deployment](https://docs.microsoft.com/en-us/exchange/exchange-hybrid)?

How did you add the shared calendar in desktop Outlook and OWA? Could you provide the steps you used to add the shared calendar for us to repro?

**Comment by bx-steven** [comment]
We deploy our addin via Centralized Deployment. Regarding adding shared calendar, we've added in multiple ways, both in Outlook Desktop and OWA. 

Regarding the actual bug, we've found a temporary resolution that applies to Outlook Desktop (OWA still works the same):
We're still using the same URL as before (https://outlook.office.com/api/v2.0/me/events/<itemRestId>) but we found a setting in the account settings > Exchange Account Settings> More Settings > Advanced > Turn on shared calendar improvements (preview) that when enabled, allowed us to make a successful REST call. 
Note, the item id we retrieved on Desktop with this setting enabled is still different from the item id that we get on OWA.

**Comment by exextoc** [comment]
Hi @bx-steven, thanks for sending across the full Script Lab code snippet. We tried the snippet as is on our end and it works as expected without any errors/exception. For a shared item the recommendation is to always use the **.../users/...** end point (as you do in the sample snippet shared). Here's what we tried doing and currently only concentrating on Win32 (keeping OWA aside for now to keep things contained to the issue at hand):
1. User A shared their calendar with User B.
2. Log into Outlook as User B.
3. Navigate to calendar module and open the shared calendar for User A (it should be already added if you've accepted the invitation and should show under the "Shared Calendars" section on the left navigation pane).
4. Then open an item from this shared calendar - make sure the item opened is one such that User A was an attendee on the meeting, not a shared calendar item that User A created (to keep things simple).
5. Ran your snippet on the item from step 4 using **.../users/..**. endpoint -> **This succeeds for us**.

We confirmed that it works when the setting **Turn on shared calendar improvements (preview)** checkbox is unchecked/disabled. I believe following the same steps as above, you're seeing an error when using the snippet in Script Lab?
Could you share what your complete Outlook build and channel looks like, navigate to File->OfficeAccount and on the right there should be About Outlook that contains this information, something like the image below- 
![image](https://user-images.githubusercontent.com/28549921/125504072-8589a0d3-3461-47b8-8b6b-6d733779b618.png)

The screenshot has information about your version number, build number and the channel you're on.

Also, could you share what your Exchange setup is along with the build number? By any chance it's a Hybrid environment?

Apologies if it seems like we're going in circles. We expect this to work seamlessly and are trying our best to understand what might be causing this discrepancy for you. We've also not heard about any issues around this area from other customers using the feature, hence the plethora of questions. Please bear with us and rest assured we want to resolve this issue for you ASAP.

**Comment by JuaneloJuanelo** [comment]
@bx-steven  can you please email me so we can have a conversation offline about this?  please email me to juanbl@microsoft.com thanks!!!

**Comment by JuaneloJuanelo** [comment]
@bx-steven  hello Steven I would love to follow up with you on this, I have not seen your email, thanks !
