### ISSUE TITLE
Cookies are not shared between OfficeDialog and task pane using WebView2 (Chromium-based)

### ISSUE THREAD

**Issue by andreagasparin** [OfficeDev/office-js#1887]
The cookies set during authentication via OfficeDialog are lost when the dialog is closed and are not available in the task pane, this problem does not occur using WebView (EdgeHTML) or Excel Online.
We followed this guide to implement authentication:
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api

## Expected Behavior
Cookies that are set via authentication using OfficeDialog should be shared with the task pane as happens using WebView (EdgeHTML).

## Current Behavior
With the use of WebView2 (Chromium-based) the cookies set by authentication using the OfficeDialog are lost and not shared with the task pane.

## Context
Our Addin uses the OfficeDialog to authenticate to a 3rd party domain. After the OfficeDialog took me to the 3rd party authentication URL, some cookies for that domain are returned.
When the OfficeDialog is closed the cookies are lost so the Addin cannot call some APIs in the 3rd party domain.
This happens only with WebView2 (Chromium-based), not with WebView (EdgeHTML).

**Comment by smaremanda** [comment]
@andreagasparin - this is sounding like an issue related to how the SameSite attribute is handled differently by the different browsers. Can you please try setting the SameSite attribute to None and see if that addresses the issue?

**Comment by andreagasparin** [comment]
@smaremanda -I verified that the SameSite parameter is already set to none for the Set-Cookies in the response header from the 3rd party domain.
What I wanted to point out is that using WebView (EdgeHTML) with the task pane and OfficeDialog open I see that they both share the same processes (even when debugging with Edge DevTools I see the Console and Network tabs with the same details for both):
WWAHost.exe
Win32WebViewHost.exe

Using WebView2 (Chromium-based) I see that the task pane and the OfficeDialog have two separate processes of "msedgewebview2.exe" and when the dialog is closed one of the 2 processes is also closed, I think this causes the cookies saved in the OfficeDialog process to be lost

**Comment by andreagasparin** [comment]
Hi @smaremanda @lliu113,
Any news on this?

**Comment by andreagasparin** [comment]
Hi @smaremanda @lliu113,
Any chance having news?

**Comment by smaremanda** [comment]
@andreagasparin - sorry for the delay. I'll need to test this internally for a repro. Can you please send us the version info for
Windows
Office 
Edge WebView2

**Comment by Dengshan2018** [comment]
@andreagasparin do you have the repro steps?

**Comment by andreagasparin** [comment]
Hi @Dengshan2018,
I can't share the project, but I will work to create a program to replicate the problem.

**Comment by andreagasparin** [comment]
Hi @Dengshan2018 @smaremanda,
I created the environment to replicate the issue.
In the attached zip you will find a web server made in Express to simulate 3rd party authentication server, an Excel Add-in that manages the opening of the dialog box with the call to the server and the verification of the cookies.
You will also find a pdf (Steps_to_reproduce.pdf) with the explanation of the steps to replicate the problem.
[Add-In-Chromium.zip](https://github.com/OfficeDev/office-js/files/6694126/Add-In-Chromium.zip)

**Comment by Dengshan2018** [comment]
@andreagasparin, there is cookie issue for add-in in debug mode. You can change two registry key - UseDirectDebugger and UseWebDebugger under "Computer\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\WEF\Developer\[%add-in solution id%]\" to "0" as workaround.

**Comment by andreagasparin** [comment]
Hi @Dengshan2018,
I tried your suggestion but I still see the issue.
When I run "npm start" UseWebDebugger is set to 0 and UseDirectDebugger is set to 1 so I set it to 0 (if I set it to 0 first, however "npm start" brings it back to 1).
Then, I open the add-in but I still have the cookie issue.

**Comment by Dengshan2018** [comment]
@andreagasparin "npm start" set the value. have to reset the registry keys before open the add-in.

**Comment by andreagasparin** [comment]
@Dengshan2018 I have set to 0 the registry keys before open the task pane, but the problem persist.
Does it work for you using the test program I attached earlier?

**Comment by andreagasparin** [comment]
Hi @Dengshan2018 Any news on this?

**Comment by Dengshan2018** [comment]
@andreagasparin yes, the workaround is working for the test program you attached. but have to do it every time. "npm start" will reset the registry keys to "1". Need to ensure the value is "0" before insert the taskpane(not "npm start").
The real fix is in the CC June 2021. you can try if you are Office insider.

**Comment by Dengshan2018** [comment]
@andreagasparin btw: samesite wasn't set to 'None' in your test program for http://localhost:3001.

**Comment by andreagasparin** [comment]
@Dengshan2018 
I hope the fix you are referring to can work in production environment as well (without running npm start).
I'll try to contact the Microsoft 365 admin to get me access to the Office Insider program.
