### ISSUE TITLE
Office 365 Shared Office Add-Ins does not refresh automatically

### ISSUE THREAD

**Issue by gmlu-systech** [OfficeDev/office-js#1890]
**Office 365 Shared Office Add-Ins does not refresh automatically**

Actually we have Office 365 Version 2002 (Build 12527.21814) and we have added an 
a trustful catalog Add-In in the options in the Trust Center and have clicked "Show in menue" there.
The trustful Catalog is stored on a network shared path.

If we open O365 Word (or other O365 programs) we can see the added Office-Add-Ins from the
catalog under the Share folder in the Office Add-Ins Tab ! 

But the Office-Add-Ins did not refresh automatically .
They are not visible automatically with menue ribbons under the "Start" Tab!

If we click "Refresh" in the Office-Add-Ins Shared folder tab, then the Add-Ins 
appears in menue correctly. 

This should be automatically without clicking the refresh button. 

A bug in this Office 365 version?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: 
Citrix VDI Desktops Windows 10 v1909 64bit with Office 365  Version 2002 (Build 12527.21814)
* Host [Excel, Word, PowerPoint, etc.]: Word, Excel, PowerPoint, Outlook, Access
* Office version number: Version 2002 (Build 12527.21814)
* Operating System: Windows 10 v1909 (Build 18363.1500)
* Browser (if using Office on the web): MS Edge 90.0.818.49
 
## Expected behavior
All Add-Ins from the published Catalog should load automatically and automatically visible as icons under "Start" Tab if we open O365 programs.

## Current behavior
The Add-Ins are showed in the "Office-Add-Ins" Window unter Share folder, but not show as buttons under "Start" Tab.
After klicking "Refresh" the Add-Ins appears.

## Steps to reproduce

1. Install the same Office 365 Version
2. Add an trustful Catalog under Trust Center and klick "Shown in menue"
3. Restart O365 Programm (Word, Excel, etc.)
4. Check if the Add-Ins are showed automatically unter "Start" Tab
5. Check if Add-Ins are showed in Shared Folder in the Office-Add-Ins window
6. klick Refresh in the Office-Add-Ins window.
7. Check the Add-Ins in "Start" Tab again - they are visible now ! 

## Useful logs
- [ ] Screenshots:
![image](https://user-images.githubusercontent.com/84896537/119781583-7970b480-becb-11eb-9405-f2397e2db85a.png)

![s](https://user-images.githubusercontent.com/84896537/120978903-48b73780-c775-11eb-8e22-16d6b28459cb.png)

![image](https://user-images.githubusercontent.com/84896537/119781796-b76dd880-becb-11eb-9a1b-2d0e93958fb0.png)

**Comment by slabereemsft** [comment]
Thanks for reporting this issue.  Per our documentation (https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins) there are some limitations:

  Deployment by network share is not supported for production add-ins. This method has the following limitations:

  The add-in can only be installed on Windows computers.
  If a new version of an add-in changes the ribbon, each user will have to reinstall the add-in.

Unfortunately this is part of the each user will need to reinstall it process.
