### ISSUE TITLE
When getAccessToken is using "allowConsentPrompt" to display a pre-authorization popup, the azure authorization popup is using the cache of the pre-authorization (even if the scopes are different)

### ISSUE THREAD

**Issue by Medhyena** [OfficeDev/office-js#1891]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I could not re-open the issue since it was closed by a contributor so here is the linked comment of my answer : https://github.com/OfficeDev/office-js/issues/1858#issuecomment-845736972
 
## Expected behavior
It should correctly display the new scopes to accept/refuse in order that the application can work properly.

## Current behavior
It basically runs as if the request has been done already and thus redirect to the redirectURI without asking for consent on new scopes. So graph refuses all requests due to wrong scopes.

## Steps to reproduce
1. Have a special graph scope in azure
2. Needs an account that needs pre-authorization like an educational account outside of the tenant
3. Open up the add-in
4. Accept the pre-authorization requests with basic scopes (profile, email)
5. The next popup for Azure's scopes is opening and instantly redirecting.

# Provide additional details
Please check the older ticket where a contributor didn't fully understand my issue. I tried to add some informations for the ticket to be clearer. (https://github.com/OfficeDev/office-js/issues/1858)

## Context
Pretty annoying for customers if they get the issue, they have to re-install the add-in manually to clear the pre-authorization request cache.

**Comment by jipinshi** [comment]
@mattgeim, can you help follow the issue?

**Comment by Medhyena** [comment]
Hello,

Microsoft tried to validate our Outlook Addin again to publish it on the store and they seem to have this issue currently.

We're going to tell them that they need to re-install the addin but this isn't a viable solution (our best solution was to make an application for the Azure App Gallery to avoid the pre-authorization pop-up).

Any updates on this?

**Comment by AlexJerabek** [comment]
Hi @Medhyena,
Let me add @slabereemsft to help assist you.

**Comment by slabereemsft** [comment]
@mattgeim - Can you take this one?
