### ISSUE TITLE
Add-ins can not be started when Attack Surface Reduction Rules are active

### ISSUE THREAD

**Issue by AeroRooms** [OfficeDev/office-js#1892]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

We are currently on a pilot phase where we activated all Attack Surface Reduction Rules within the Endpoint Security tab in Microsoft Endpoint Manager. As soon as they are applied we are no longer able to run any add-in for example Wikipedia and receive the error message:

ADD-IN ERROR
This add-in could not be started. Close this dialog to ignore the problem or click "Restart" to try again.

When you use Word Online the issue doesn't occur. The Attack Surface Reduction Rule that seems to have major impact is "Block Office applications from injecting code into other processes".

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Word, Excel, Powerpoint
* Office version number: 16.0.14026.20202
* Operating System: Windows 10 20H2 19042.985
* Browser (if using Office on the web): Edge Chromium
 
## Expected behavior

The add-in should be running normally or display further information

## Current behavior

ADD-IN ERROR
This add-in could not be started. Close this dialog to ignore the problem or click "Restart" to try again.

## Steps to reproduce

1. Enable all ASR as documented here https://docs.microsoft.com/en-us/microsoft-365/security/defender-endpoint/enable-attack-surface-reduction (or only the "Block Office applications from injecting code into other processes" rule)
2. Start Add-in
3. Add-in is being blocked
4. Disable all ASR again
5. Start Add-in
6. Add-in works as expected

## Context

We are using Defender for Endpoint and try to harden some critical devices and users with the recommendations given by Microsoft.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by jipinshi** [comment]
@croicu , could you help take a look?

**Comment by jipinshi** [comment]
@zunquan, is there any update here?
