### ISSUE TITLE
setSignatureAsync behavior not consistent between event-based activation usage and taskpane usage(signature doesn't get replaced)

### ISSUE THREAD

**Issue by kinkoazc** [OfficeDev/office-js#1893]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: BETA
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

After a signature was set as a result of event-based activation, it should be replaced when a second setSignatureAsync call was made from e.g. a taskpane.

## Current behavior

Currently the initial signature(set at event-based activation) gets set under a div with id x_Signature, while the second signature gets set under a div with id Signature. At this point there are two signatures being applied, instead of the second one replacing the first one.

## Steps to reproduce

1. Set the first signature as part of the "OnNewMessageCompose" launch event handling.
2. Set another/the same signature from the taskpane.
3. Now there should be two signatures applied instead of a single one(the first applied signature doesn't get replaced by the second).

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

The taskpane set signature should replace the event-based activation set signature(no official way of clearing the initial signature).

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Thanks for reporting this issue. Are you using this api as a part of any addin?

**Comment by kinkoazc** [comment]
Hello. Yes, in development.

**Comment by exextoc** [comment]
Can you please share the manifest of your addin? The setSignatureAsync should replace the content of the 'Signature' div here. Are you saying that this is happening because of using two different divs?

**Comment by kinkoazc** [comment]
I've used the instructions from https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch to set the event activation(listening for the "OnNewMessageCompose" event). There seems to be a demo repo, https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/outlook-set-signature, but I can't replicate the issue there. Maybe it depends on the context/manifest. The manifest I use can be found here https://gist.github.com/kinkoazc/4b26cdc7bb76bdbd027a0855758fdc6a.

As for the behavior:
1. After the event-based activation method finishes, there is a div with id of Signature inserted(at this point there is one signature present).
2. When setting a new signature through the taskpane, the initial div gets removed/replaced by a div with id of x_Signature(at this point there is one signature present).
3. When again setting a new signature through the taskpane, the initial div gets removed/replaced by a div with id of x_x_Signature and a new div is created, with id of x_Signature(at this point there are two signatures present).
4. Any other signature setting from this moment on triggers the insertion of additional signatures(3, 4, etc.), with corresponding "x_"-appended ids.

**Comment by kinkoazc** [comment]
Closing, as the problem was in my implementation, with calling `body.setAsync` after `body.setSignatureAsync`. Sorry about the false report.
