### ISSUE TITLE
Outlook on the web: Embedded image data does not disappear

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#1894]
# Provide required information needed to triage your issue
If you delete an embedded image after you insert it, you can still get information about the embedded image from the `getAttachmentsAsync` method.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: Windows 10
* Browser (if using Office on the web): Edge Version 90.0.818.66 (Official build) (64-bit)

## Expected behavior

Information about the deleted embedded image cannot be obtained.

## Current behavior

Information about the embedded image that should have been deleted continues to exist.
However, the image information disappears when you actually send the mail.

## Steps to reproduce

1. Compose an email
2. Click "Insert pictures inline" to insert embedded image
3. Delete embedded image with DELETE key

## Link to live example(s)

https://user-images.githubusercontent.com/58804032/119949485-71774a00-bf89-11eb-8332-b68c212400dd.mp4

## Context

It uses `getAttachmentsAsync` and `getAttachmentContentAsync` methods to retrieve embedded image information for copying and checking.
We do not need to copy and check images that are not added when sending mail, so we want to exclude them.

Related Issue
https://github.com/OfficeDev/office-js/issues/900

**Comment by exextoc** [comment]
Hello, thanks for reporting this issue. We could repro this issue at our end and have added this to our backlog. We, however have no timelines to share for the fix.

**Comment by Techno11** [comment]
I also noticed this issue when I was debugging one of my other issues

**Comment by clavx** [comment]
OWA hostVersion: 20211025002.09

I checked the current status.
I was not able to reproduce the issue with the procedure I reported.
This issue seems to have been resolved.

@exextoc Do you have any updates on this?

**Comment by exextoc** [comment]
Hey @clavx ,

Yes, this issue has been fixed and is no longer reproducible. We are closing this bug. You can reopen it if it needs further investigation.
