### ISSUE TITLE
Task pane auto open doesn't work when deployed under Office 365 Organization Centralized Deployment

### ISSUE THREAD

**Issue by ThangaSperumal** [OfficeDev/office-js#1895]
# Provide required information needed to triage your issue

Add-in for excel which is deployed under Office 365 Organization Centralized Deployment (uploaded Manifest) does not work when using Excel Online (Excel Web) .  The same manifest.xml that has been deployed under Centralized Deployment deployed using sideloaded under Insert Add-In Upload file option works fine. 

Also works fine using Office 365 Excel on Windows.

Implemented the following code to Automatically open a task pane based on the following guidelines .
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document

Manifest XML
<Action xsi:type="ShowTaskpane">
<TaskpaneId>Office.AutoShowTaskpaneWithDocument</TaskpaneId>
	
	<SourceLocation resid="Silvon.Taskpane.RefreshViews" />
</Action>

Client side code
Office.context.document.settings.set("Office.AutoShowTaskpaneWithDocument", true);
Office.context.document.settings.saveAsync();

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.14123.35903
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

Expecting Excel on the web should open  the Task pane when opening an existing saved (Saved with Office.AutoShowTaskpaneWithDocument = true) excel file using Excel on the Web.

## Current behavior

Opening an existing saved excel file using Excel on the Web does not open the Task Pane.
If the same Add-In Manifest is deployed using sideloaded under Insert Add-In Upload file option works fine on Excel on web.
 

## Steps to reproduce

1. Set Office.AutoShowTaskpaneWithDocument in the Manifest Xml.
2. Set client side code Office.context.document.settings.set("Office.AutoShowTaskpaneWithDocument", true);
Office.context.document.settings.saveAsync(); under Office.initialize().
3. Publish Web site and update Manifest Xml with Web Url.
4. Deploy the Manifest.Xml under the Office 365 Organization Centralized Deployment.
5. Open Excel Access the Add-in RefreshViews TaskPane.
6. Save the Excel file.
7. Reopen the saved Excel file. 

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by lumine2008** [comment]
@exextoc , it seems this issue related to UX or Central Deployment, so i am looping @lliu113

**Comment by lliu113** [comment]
@ThangaSperumal - thanks for reporting this and sorry you're hitting this issue! This is a known bug, which is in our backlog. We currently do not have an ETA for the fix. 

Internal tracking: 3546573

**Comment by ThangaSperumal** [comment]
Hello Lillian Liu,

Thanks for looking into this issue.

Regards,
Thanga

**Comment by exextoc** [comment]
No action for quite some time. Closing the issue.
