### ISSUE TITLE
Outlook Online Calendar can't open app store by click get add-ins

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#1897]
![image](https://user-images.githubusercontent.com/1878089/120167075-e4a1ea00-c22f-11eb-9a0a-15892f07b5c9.png)

**Comment by exextoc** [comment]
Hey @hello-chenchen ,

Can you share some more details about this scenario? Does nothing happen when you click on "Get Add-ins", or do you get some kind of error?

**Comment by hello-chenchen** [comment]
![image](https://user-images.githubusercontent.com/1878089/120183304-191ea180-c242-11eb-9b49-03878edd2b4c.png)
the only message is [Violation] Forced reflow while executing JavaScript took 40ms
but it seems not the reason.

**Comment by hello-chenchen** [comment]
i can repro this problem in every browser and every network environment by every account type (both Office 365 E5 License, E3 License, free user).

**Comment by exextoc** [comment]
Hey @hello-chenchen,

I can reproduce this issue and we are working on fixing it. Just to confirm, this behaviour does work for you in the overflow menu of Email Read?

**Comment by hello-chenchen** [comment]
@exextoc , yes it work for the email page.
it 's only happened on calendar page.
