### ISSUE TITLE
Office.context.ui.addHandlerAsync does not work after a redirect on Outlook for Windows

### ISSUE THREAD

**Issue by piedrahitapablo** [OfficeDev/office-js#1898]
# Provide required information needed to triage your issue
I'm currently developing an add-in for outlook, we need our users to login using microsoft as an identity provider, for that we show a Office dialog that redirects the users to a page of the add-in after they accept the prompt. The add-in page, registers a handler for the parent messages but the callback is never called and the handler is not registered.

This is only happening on the desktop client for windows, I have tried on the web using different browsers and on the mac client and everything works as expected. Also, it only happens after a redirect, if I open the dialog directly on the add-in page it works.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2008 version (13127.21624)
* Operating System: Windows 10, Version 2004 (Build 19041.985)
* Browser (if using Office on the web): ______
 
## Expected behavior

To register the parent message handler succesfully.

## Current behavior

The handler is never registered and the callback is not called.

## Steps to reproduce

I created this small repository to reproduce the issue: https://github.com/piedrahitapablo/office-handler-bug

1. Clone the repository locally
2. Install the dependencies (`yarn install`)
3. Run the dev server (`yarn start` on mac or `yarn start:windows` on windows)
4. Sideload the add-in using the manifest in https://github.com/piedrahitapablo/office-handler-bug/blob/master/office/manifest.xml
5. Add a client id in https://github.com/piedrahitapablo/office-handler-bug/blob/master/src/taskpane/Taskpane.tsx#L14 that accepts https://lcoalhost:3000/dialog.html as a redirect URI
6. Open the taskpane
7. There are two buttons on the taskpane
    - Show dialog: opens a dialog directly on the add-in page and everything works as expected
    - Show dialog with redirect: opens a dialog on https://login.microsoftonline.com that then redirects the user to the add-in page and the handler registration does not work

## Context

As mentioned above, the add-in requires users to sign in in order to work, so after our users install the add-in, the first time they try to send an e-mail the add-in shows a welcome dialog offering the possibility to sign in and if they accept we show the dialog on https://login.microsoftonline.com. After they accept the prompt and microsoft redirects them to the add-in page, we need them to select a customer since our service is multi-tenant. This issue is preventing our users to login on windows.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Ensure that the dialog box's domain is the same as the domain of the host page, refer to the dialog documentation [here.](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#open-a-dialog-box-from-a-host-page)

**Comment by exextoc** [comment]
Message parent failures are often caused by failing domain validation where the dialog URL is not the same as the taskpane it’s trying to call.   It is okay for the dialog to redirect after launch but it must ensure that all communication between the dialog and the taskpane is according on the same domain.  

 Refer to the document for using dialog with authentication [here.](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api) And documentation for dialog API can be found [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#open-a-dialog-box-from-a-host-page).

**Comment by piedrahitapablo** [comment]
Yeah, I think that's what's happening here and I can solve it just as the dialog with authentication document says, opening the dialog first on the add-in domain and then redirecting to the microsoft domain, and that's a good solution. The only thing that keeps me thinking is that opening the dialog directly on the microsoft domain only fails on the windows client, the rest of them (mac and web) work fine.

Thanks for helping me out with those docs links!
