### ISSUE TITLE
Edge Developer tool is not working on office 365 Current channel 14026.20246

### ISSUE THREAD

**Issue by GauravBagewadi88** [OfficeDev/office-js#1899]
We have developed an Office JS add-in where for debugging purpose we are using edge developer tool but for testing office version we have took current version 14026.20246 where edge developer tool is not working (we could not able see any add-in under debug section to attach the process). It is not working for any Microsoft store add-in as well

Prod/Sandbox
* Platform [PC desktop, Mac, iOS, Office on the web]: Windows
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 14026.20246
* Operating System: Windows 10
* Browser (if using Office on the web): Edge Webview
 
## Expected behavior
Developer should able to attach the add-in process for debugging

## Current behavior
Developer will not able to attach addin process as it is not listing in edge developer tool

## Steps to reproduce
1. Open word with version 14026.20246
2. Open any Microsoft add-in (Wikipedia/Custom addin) from store using insert add-in functionality
3. Open edge developer tool to attach the addin process
4. We could not able see addin under edge developer tool to attach the process

Edge Developer tool is working for us under semi annual Channels 
13127.21336

**Comment by Dengshan2018** [comment]
@GauravBagewadi88 you might use webview2 runtime. You can start the dev tool from context menu by clicking "Attach Debugger".
![image](https://user-images.githubusercontent.com/45212981/129829404-27b2842b-e120-4124-91f3-e648b500c065.png)
