### ISSUE TITLE
The "issue" of having to approve opening of a new window.

### ISSUE THREAD

**Issue by Mangemannen66** [OfficeDev/office-js#19]
I'm using office js helpers( collection of helpers to simplify development of Office Add-ins) for a word addin that I am developing. When you open the addin in word online (office365), the authentication process starts and it opens up a small window (dialog) with the text (translated to english): 

                     Templatehandler wants to open a new window  
                          

                                                  Allow or Ignore   
                                                 (Allow or ignore are buttons)

From the Company that I work for and from my own point of view, it would be nice to have the possibility to get rid of this windowprompt and allow the opening by default.  It seems that this is more a platform-issue as [Michael Zlatkovsky explained on Stackoverflow](https://stackoverflow.com/questions/46928205/how-to-automaticly-approve-opening-of-new-window-for-authenticating) 
He also suggested that I should do a bug report so it is getting tracked here =)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: ______1705
* Operating System: ______Windows 10 Pro v 1709
* Browser (if using Office Online): ______Chrome, Edge, Firefox

## Useful logs

- [ ] Console errors
- [ ] Screenshots

![newwindownotification](https://user-images.githubusercontent.com/6208986/32048494-f66152a4-ba49-11e7-8edd-7c992c7cb562.png)

- [ ] Test file (if only happens on a particular file)

**Comment by sumurthy** [comment]
May be you've explained it in StackOVerflow already - is the add-in opening a dialog window and you get this message prior to that -OR- does the warning dialog show up just at the start-up of add-in?

**Comment by Mangemannen66** [comment]
The warning dialog shows up at the start-up of add-in.

**Comment by danielgwilson** [comment]
Hi! This is now possible with the optional parameter, `promptBeforeOpen=true`.

See the section on Handling pop-up blockers in the Dialog API documentation:
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#dialog-api-scenarios
