### ISSUE TITLE
Outlook: OnMessageRecipientsChanged Not Triggering

### ISSUE THREAD

**Issue by Techno11** [OfficeDev/office-js#1901]
# `onMessageRecipientsChangedHandler` Not Triggering when message recipients are added

## Your Environment

* Platform: Outlook Desktop for Windows, Outlook on the Web
* Host: Outlook
* Office version number: Outlook 16.0.14026.20202
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome 90.0.4430.212
 
## Expected behavior
When I add recipients to a new email in Outlook via the to, cc, etc field for the function defined as `OnMessageRecipientsChanged ` in the manifest.xml to be called.

## Current behavior
Function does not appear to be being called

## Steps to reproduce

1. Setup a project following [these steps](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch)
2. Wherever your callbacks are defined (in the example, it is commands.js) I use the following code:
```javascript
function onRecipientChangedHandler(event) {
  console.log('Recipients Changed!')
  event.completed();
}

function onMessageComposeHandler(event) {
  console.log(event)
  setSubject(event);
}
function setSubject(event) {
  Office.context.mailbox.item.subject.setAsync(
    "Set by an event-based add-in!",
    {
      "asyncContext" : event
    },
    function (asyncResult) {
      // Handle success or error.
      if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
        console.error("Failed to set subject: " + JSON.stringify(asyncResult.error));
      }

      // Call event.completed() after all work is done.
      asyncResult.asyncContext.completed();
    });
}

Office.onReady(() => {
  Office.actions.associate("onMessageRecipientsChangedHandler", onRecipientChangedHandler);
  Office.actions.associate("onMessageComposeHandler", onMessageComposeHandler);
  console.log('Callbacks Registered')
})
```
And, if following the example, commands.html:
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!-- Office JavaScript API -->
    <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/beta/hosted/office.js"></script>

    <!-- Our Event Handler JS Script -->
    <script src="./commands.js"></script>
   
</head>
<body>

</body>
</html>
```
3. Compose a new email. Watch as the subject line changes, indicating that your callbacks are at least _registering_ and that your events are setup properly.  Then, with the console open, add a recipient, and watch as nothing prints.

## Link to live example(s)

1. [This _should_ work, although I can't be sure because the functionality I'm trying to test is what isn't working](https://gist.github.com/Techno11/42034cd86858c217ca887849006a81ee)

# Provide additional details

1. For the above example, I'm not sure if registering these event handlers after the compose email has already been started, but since I can't find any other way to do it, it's the best I could figure out

## Context

I'm looking to listen to the recipients being updated so that when new people are added, I can perform a cross-lookup in our system for functionality in my addin to work properly.

## Useful logs

- No logging is available as nothing happens when this event handler is registered or triggered.

**Comment by exextoc** [comment]
Please ensure that you are on Insider Beta Channel to use event-based activations. New events are in preview (not requirement set 1.10), refer to [this ](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#supported-events) documentation for more details.

**Comment by Techno11** [comment]
I'll do that. Thanks for the response! I'll update here if I have any additional troubles.
