### ISSUE TITLE
MSWord online : content controls in Header are not found/detected

### ISSUE THREAD

**Issue by Foundasys** [OfficeDev/office-js#1902]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When I add a content control to the primary header and footer using MSWord offline then MSWord online does not find the content control in the header. Content controls in the body and footer are found just fine.

Hereby my code:

    async function getCCFromPrimaryHeaderandFooter() {
        return await Word.run(async (context) => {
            let sections = context.document.sections.load();
            await context.sync();

            let header_primary = [];
            let footer_primary = [];

            sections.items.forEach((section, i) => {
                header_primary = section
                    .getHeader(Word.HeaderFooterType.primary)
                    .contentControls.load("items");

                footer_primary = section
                    .getFooter(Word.HeaderFooterType.primary)
                    .contentControls.load("items");
            });
            await context.sync();

            console.log(
                "number of content controls in primary header : " +
                    header_primary.items.length
            );
            console.log(
                "number of content controls in primary footer : " +
                    footer_primary.items.length
            );
        });
    }

# Provide required information needed to triage your issue

## Your Environment

* Platform:  Office on the web
* Host: Word
* Operating System: Windows
* Browser (if using Office on the web): Google chrome
 
## Expected behavior
I expect the content control in the header to be detected

## Current behavior
Header content controls are not found

**Comment by JinghuiMS** [comment]
Thanks for reporting. BUG 5172411 has opened for internal track.

**Comment by xiruatms** [comment]
Thanks for reporting this. Will you please take a try whether you will still hit this issue?

**Comment by Foundasys** [comment]
Hello, I still have this problem but narrowed it down a bit.

![image](https://user-images.githubusercontent.com/6333708/124914570-cda1a500-dff0-11eb-9e02-7cc4b1d633ac.png)
