### ISSUE TITLE
Outlook: addFileAttachmentFromBase64Async with isInline: true not displaying

### ISSUE THREAD

**Issue by Techno11** [OfficeDev/office-js#1903]
# `addFileAttachmentFromBase64Async` with `{isInline: true}` yields no image in body of email

## Your Environment

* Platform: Outlook Desktop for Windows, Outlook on the Web
* Host: Outlook
* Office version number: 16.0.14026.20202
* Operating System: Windows 10
* Browser: Chrome 90
 
## Expected behavior
Image to be added inline of the email body

## Current behavior
Attachment appears to be linked to the email, but is not displayed in the body of the email.  When `getAttachmentsAsync` is called after attempting an inline `addFileAttachmentFromBase64Async `, the attachment shows in the return array.

## Steps to reproduce

1. Compose a new email and execute the following code:
```javascript
     const base64String = '<insert a base64 encoded image string here>';
     Office.context.mailbox.item.addFileAttachmentFromBase64Async(base64String, "logo.png", { isInline: true }, function( result ) {
        console.log(result);
        Office.context.mailbox.item.getAttachmentsAsync((data) => {
          console.log(data)
        })
      });
```

## Link to live example(s)

1. https://gist.github.com/Techno11/afdb9cb3a8512f9254244d68f10a5e49

# Provide additional details

1. This snippit attaches an image inline, and then prints the list of attachments from the email.

## Context

I'd like to attach an image to the body (inline) of the email.

## Useful logs

- ![image](https://user-images.githubusercontent.com/15097541/120537234-0c6d8b00-c3b3-11eb-87a0-9d8b38c702f5.png)
- First console statement is the output of `addFileAttachmentFromBase64Async`, second console statement is the output of `getAttachmentsAsync`, and the body of the email can be seen blank.

**Comment by Techno11** [comment]
Something of note for this issue on Outlook on the Web, I have the react debug tools enabled that outlines elements when a re-rendering is triggered.  After attempting to attach an image inline, the email editor does re-render, as if something is supposed to change, but nothing actually does.

**Comment by exextoc** [comment]
When adding an inline attachment, the attachment won't automatically appear in the message. You'll need to modify the html body of the message to include an `<img>` element with a reference to the inline attachment.

Adding to your example, this code calls `prependAsync` with an `<img>` element, though `setBody` would work as well.

```javascript
const base64String = '<insert a base64 encoded image string here>';
Office.context.mailbox.item.addFileAttachmentFromBase64Async(base64String, "logo.png", { isInline: true }, function( result ) {
	Office.context.mailbox.item.body.prependAsync('<img src="cid:logo.png" />', {coercionType: Office.CoercionType.Html})
});
```

In the `addFileAttachmentFromBase64Async` doc, there's [an example of doing this](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-1.10&preserve-view=true#addFileAttachmentFromBase64Async_base64File__attachmentName__options__callback_) with a signature API. And under `addFileAttachmentAsync`, there's [an example that uses setBody](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-1.10&preserve-view=true#addFileAttachmentAsync_uri__attachmentName__options__callback_).

**Comment by Techno11** [comment]
Thanks! I missed this in the documentation. I'll give it a shot and update here if I have any issues.
