### ISSUE TITLE
getSharedPropertiesAsync() isn't returning correct shared mailbox properties

### ISSUE THREAD

**Issue by somenathmaji** [OfficeDev/office-js#1905]
On a multiple shared mailbox setup, getSharedPropertiesAsync() is returning the properties of the different shared mailbox.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.49
* Operating System: Big Sur (11.4)
* Browser (if using Office on the web): N/A
 
## Expected behavior
The API should return shared properties of the current mailbox.

## Current behavior
Currently, it shows the shared properties of another mailbox.

To better understand the issue -
We've multiple shared mailboxes set up on our current account, let's say sharedMailbox-A, sharedMailbox-B, sharedMailbox-C.

| Action  | Result |
| ------------- | ------------- |
| Opened sharedMailbox-A first and used the getSharedPropertiesAsync() API to get the shared properties of the current mailbox  | It shows shared properties of sharedMailbox-A. |
| Opened sharedMailbox-B next and used the getSharedPropertiesAsync() API to get the shared properties of the current mailbox  | It still shows shared properties of sharedMailbox-A.  |
| Opened sharedMailbox-C next and used the getSharedPropertiesAsync() API to get the shared properties of the current mailbox  | It still shows shared properties of sharedMailbox-A.  |

The API should show the shared properties of the current mailbox.

## Steps to reproduce

1. Setup multiple shared mailboxes on your account
2. Open a shared mailbox A
3. Open script Lab gist and click run
4. Correct shared properties are shown in console
5. Open another shared mailbox B
6. Again hit run from script Lab
7. Wrong shared properties are shown in console

## Link to live example(s)

1. Script Lab gist: https://gist.github.com/somenathmaji/55e7af356d0ab8ffe4f6412d9789dfbd

# Provide additional details

1. Import the code snippet using the above gist on script Lab.
2. Printing 2 logs on the console: first, the requirement set 1.8 is valid or not, and second is the shared properties of the current mailbox.

## Context

We faced the issue only on mac. This works perfectly fine on windows. We use this API to know the shared mailbox details and turn on or off particular features based on that. With this bug, we're not able to turn the feature on even if the user is using a correct shared mailbox on mac.

**Comment by exextoc** [comment]
We are unable to repro this issue at our end. Can you share following to details to help us repro the issue: 
1. Are you using [New Outlook](https://support.microsoft.com/en-us/office/the-new-outlook-for-mac-6283be54-e74d-434e-babb-b70cefc77439) for Mac?  
2. Does it repro on both Old and New Outlook ?
3. What do you mean when you say "Open a shared mailbox A"? Does it mean opening an existing email from shared mailbox A?

**Comment by somenathmaji** [comment]
I tried to repro it now and it's showing `TypeError: window.Office.context.mailbox.item.getSharedPropertiesAsync is not a function.` It's weird because a few days back it used to behave differently and show wrong shared properties. The requirement set 1.8 is supported and I'm using it from a shared mailbox. Here's a screenshot of the error -

<img width="1490" alt="Screenshot 2021-06-10 at 12 56 42 PM" src="https://user-images.githubusercontent.com/10449421/121483131-75748480-c9eb-11eb-9d48-55bf3261ae3e.png">

To answer your questions, here's the following -
1. I'm using old outlook for mac.
2. It did repro on the old outlook for mac, on the new outlook for mac requirement set 1.8 isn't supported.
3. Sorry for the confusion, I meant to open an existing email from shared mailbox A.

Let me know if you need further information.

**Comment by exextoc** [comment]
The New Outlook for mac does support 1.8 requirement set now please check [here](https://support.microsoft.com/en-us/office/outlook-for-mac-release-notes-for-beta-channel-builds-d6347358-5613-433e-a49e-a9a0e8e0462a) for more details. Can you test if you face the same issue on New Outlook as well.

**Comment by somenathmaji** [comment]
I updated the outlook from the beta channel and I can confirm it's working properly on the New Outlook for mac.
However, it's reproducible on the Old Outlook for mac after the update.

**Comment by exextoc** [comment]
Thank you for sharing this issue. As a workaround, users can switch to the new Outlook for Mac experience which works as expected. We are not prioritizing this fix on classic Mac UI; please reopen the issue in case the workaround does not solve your scenario.

**Comment by somenathmaji** [comment]
Thank you for checking this. Most of our customers don't use the beta channel for updates. It will really be helpful if we can get this fix on the current channel.

**Comment by exextoc** [comment]
What do you mean by beta channel ?Do you mean Insider fast?New UI is rolled to production and the using the toggle button in the image we can switch to new UI
<img width="361" alt="Screenshot 2021-06-17 at 10 04 18 AM" src="https://user-images.githubusercontent.com/28549921/122332149-955bf900-cf53-11eb-98e0-0edb6d77803e.png">
