### ISSUE TITLE
Outlook Plugin Not Releasing Memory

### ISSUE THREAD

**Issue by peterdesio** [OfficeDev/office-js#1907]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows
* Browser (if using Office on the web): Edge (through Outlook plugin)
 
## Expected behavior
Memory should release whenever an email is closed 

## Current behavior
Each time an email is opened a new Webview2 task is created and the memory is not released.

## Steps to reproduce

1. Open Salesforce Plugin within Outlook
2. Open an Email
3. View task manager - Webview2 task creates
4. Close the email
5. Memory is not released
6. Rinse and repeat

## Link to live example(s)

# Provide additional details

1. ______
2. ______
3. ______

## Context
This is consuming memory each time an email is opened and not releasing it 

## Useful logs

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Dengshan2018** [comment]
@peterdesio , what do you mean "Memory is not released"? are you seeing the memory of outlook keep increasing when repeat the steps? how much is increased each time?

**Comment by peterdesio** [comment]
It keeps adding a Webview task. We opened this ticket at the request of our Salesforce technician. He has a detailed description of the issue, with screenshots, and will be a better technical resource than me. 

-- 
Pete DeSio 
Principal	
 
CAPITAL S CONSULTING

e: ***@***.***

**Comment by Dengshan2018** [comment]
@peterdesio could you ask Salesforce technician to add more details?

**Comment by Dengshan2018** [comment]
@peterdesio there are a few fix related with memory leaks. they are available in beta channel.
