### ISSUE TITLE
Word Add-In not available in the Office Store

### ISSUE THREAD

**Issue by mstancu-globe** [OfficeDev/office-js#1908]
## Expected Behavior
I have published an Word Add-In to the Office365 available for all people in the organization.

## Current Behavior
The Add-In is not available in the Office Store, it not appearing in the search.

## Steps to Reproduce, or Live Example
The Add-In is called Amelkis DM and it was published by aboulcane@amelkis-solutions.com

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by saurabh-msft** [comment]
Hi @mstancu-globe 

Can you please give us more details as below?
1. When was the add-in published?
2. Publisher Name/ProviderName
3. Screen Snapshots indicating submission went through fine on Partner Center portal
4. Can you confirm the add-in name is 'Amelkis DM' and is only for MS-Word workload?
5. Have you got any email from Microsoft Validation team on validation errors and progress?

**Comment by mstancu-globe** [comment]
Hi @saurabh-msft 

1. It was published on 28 May 2021
2. Amelkis Solutions https://www.amelkis-solutions.com/fr/
3. 
![Published](https://user-images.githubusercontent.com/52195836/121136152-ff7eea80-c83d-11eb-956b-58852303e271.png)
4. Yes it's Amelkis DM
5. The publisher did not receive any email from Microsoft
6. It was published from the account aboulcane@amelkis-solutions.com

**Comment by saurabh-msft** [comment]
Hi @mstancu-globe

We don't seem to have a record of this add-in with our validation team. Is this a published add-in? Or a Sideloaded add-in?
Can you please give a snapshot from the partner center portal indicating this is a published add-in. The snapshot you gave above is from the admin portal. We need the snapshot from partner center portal.

**Comment by mstancu-globe** [comment]
Hi @saurabh-msft 

They don't have a Microsoft Partner account. They will create one and will publish from there.
Thank you very much!

**Comment by saurabh-msft** [comment]
Hi @mstancu-globe 
Based on your last reply, can we close this github issue as resolved? Or if there is something else you need help with.

**Comment by mstancu-globe** [comment]
@saurabh-msft 
Hi, 
Yes, you can close this issue.
Thank you very much!
