### ISSUE TITLE
Outlook Online, item.body.setSelectedDataAsync() inserts text not into the current selection but underneath the default signature

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#1910]
In an Outlook add-in for compose mode, we use the item.body.setSelectedDataAsync() method to insert HTML into the current selection. In case of a new email message that has a signature inserted automatically, the item.body.setSelectedDataAsync() method inserts HTML below the signature.

## Your Environment
* Platform: Office on the web
* Host: Outlook
* Office version number: 
* Operating System: Windows 10, macOs
* Browser (if using Office on the web): Chrome Version 91.0.4472.77, Microsoft Edge Version 91.0.864.41, Safari Version 14.1.1 (16611.2.7.1.4)
 
## Expected behavior
The item.body.setSelectedDataAsync() method shall insert HTML into the current selection, in this case at the first line of the message.

## Current behavior
The item.body.setSelectedDataAsync() method inserts HTML underneath the email signature.

## Steps to reproduce
1. Sign in to Outlook Online, make sure you have an email signature there and the Automatically include my signature on new messages that I compose option is turned on.
2. Click the New message button.
3. Important! In the new message view, do not switch the keyboard focus to another control, leave it untouched in the To field.
4. Open an add-in pane and execute the following code:
`      Office.context.mailbox.item.body.setSelectedDataAsync(`
`        '<p>Text 1</p><p>Text 2</p>',`
`        { coercionType : 'html' },`
`        function (result) { console.log(JSON.stringify(result)); }`
`      );`

5. Note, the 2 paragraphs are inserted underneath the email signature.

## Link to live example(s)
1. You can install the following add-in:
https://online-addins.ablebits.com/testaddin/manifest.xml

It is quite simple, contains just one button that executes the code above.

If you need any additional information, feel free to ask me.

**Comment by DmitryKostochko** [comment]
Oops, we have just found that setSelectedDataAsync() inserts HTML at the very bottom when you forward an email. Here are the steps:
- select an email in Inbox.
- click the Forward button.
- do not switch the keyboard focus to any other control.
- execute the code above.

The presence or absence of an email signature does not affect anything in this case.

Shall I post this issue in a separate bug report?

**Comment by exextoc** [comment]
As per the [documentation](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-1.2&preserve-view=true#setSelectedDataAsync_data__options__callback_) for setSelectedDataAsync() API , If the cursor is not in the body or subject field, an error should returned.we have added an item in our backlog to align with above scenario  . We unfortunately have no timelines to share at this point

**Comment by DmitryKostochko** [comment]
@exextoc, Please have a look at the code sample I provided more carefully. We don't use Office.context.mailbox.item.setSelectedDataAsync, we use the [Office.context.mailbox.item.**BODY**.setSelectedDataAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-preview#setSelectedDataAsync_data__options__callback_) method.

Additional details that I think may be helpful to you:
1. The Office.context.mailbox.item.body.setSelectedDataAsync method works fine in Outlook Desktop for Windows and Outlook for Mac.
2. The Office.context.mailbox.item.body.setSelectedDataAsync method worked fine in Outlook Online 2-3 weeks ago, it looks like the bug was introduced in the last couple of weeks as a part of a recent update?

Please let me know if you need any additional information.

**Comment by exextoc** [comment]
Thanks for clarification and for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by DmitryKostochko** [comment]
Do you have any news about the issue?

**Comment by exextoc** [comment]
@DmitryKostochko Thanks for your patience. We have fixed the bug, and the fix should be available in the next ~2 weeks. 
Closing the bug, please feel free to reactive the thread if you have any comments.
