### ISSUE TITLE
removeWhenEdited with content control causes the issue on Web

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#1912]
when inserting text, html into a content control and mark it removeWhenEdited . It throws the exception on the web

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): Chrome
 
## Expected behavior
- it should not show the error on the web

## Current behavior
{
code: "ItemNotFound"
message: "We couldn’t find the item you requested. Check the OfficeExtension.Error.debugInfo for more information."
}
## Steps to reproduce

1. create content control
2. insert content to that content control
3. mark removeWhenEdited = true.
4. make context.sync()

## Link to live example(s)
https://gist.github.com/jasonhieu1905/99e8b8e6cbd1f46ae5ebe00a0934515c

# Provide additional details

## Context
If you switch **step3** and **step4** in the retro steps, the issue is not happen.

## Useful logs
![image](https://user-images.githubusercontent.com/13063615/121175489-4c39e400-c885-11eb-946c-e9e5385324dd.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by barisbikmaz** [comment]
I suspect that the commands are not synched in the order in which they are typed. On Windows Desktip it works.

**Comment by xiruatms** [comment]
Thanks for reporting this. 
Yes, as @barisbikmaz mentioned: the execution of the APIs packed in one context.sync() will not be guaranteed to be run in the same order as when writing them. 

In this case, you can add one more "await context.sync();" after insertText();
        // insert text        
contentControl.insertText("simple text", Word.InsertLocation.replace); 
await context.sync();       
contentControl.removeWhenEdited = true;        
await context.sync();

If you want to make sure the execution order, please split them with multiple context.sync().

**Comment by AbidRahman-MSFT** [comment]
Closing the issue, please let us know if you have any additional questions. Thanks.
