### ISSUE TITLE
Word Online: insertOoxml() inserts a copy of the OOXML when there's anything more than just the content control in a paragraph

### ISSUE THREAD

**Issue by StephenRieger** [OfficeDev/office-js#1914]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.14207.41013
* Operating System: Windows 10, Mac Catalina/Big Sur
* Browser (if using Office on the web): Mac (Safari, Chrome), Windows (Edge)
 
## Expected behavior
Calling insertOoxml() to update the contents of a content control with valid OOXML should update only the content range of the content control.

## Current behavior
insertOoxml() is both updating the content range of the content control and appending the same OOXML just after the range of the entire content control.

## Steps to reproduce
Use the gist at https://gist.github.com/StephenRieger/1e02a3592f678993819e664fb0641e71, which is just a slightly modified version of Script Labs "Content control basics" example, where I've updated modifyContentControls() to call insertOoxml with the result getOoxml using the content control's content range.

Starting with an empty document, click on the "Setup" and "Insert Buttons" then add any text to the start of the first paragraph, so the first content control is not the only thing in that paragraph. Click the "Modify content controls" button twice. The first time the results appear fine. The second time the contents of the first content control are inserted immediately after the content control.

## Link to live example(s)
https://gist.github.com/StephenRieger/1e02a3592f678993819e664fb0641e71

## Context

We're using insertOoxml() to both insert formatted text (because it can be a fairly large amount of text with complex formatting) and to embed ADDIN fields in a content control because that allows us to embed private data in a content control.

The essential bit here is that we need a way to embed private data (which can be fairly large - typically less than 1K of XML, but sometimes much more) in a content control. That private data needs to be retained when copying/pasting between documents.

## Useful logs
![image](https://user-images.githubusercontent.com/14093851/121422072-b012ea00-c923-11eb-863a-d4d40a89c6f9.png)

**Comment by RuoyingLiang** [comment]
Thanks for reaching us. Unfortunately we cannot repro with the sample code. Could you provide more information? e.g. a repro video, sample document, etc.

**Comment by StephenRieger** [comment]
I've attached a screen recording running the gist from above and will add another gist to illustrate more of the insertOoxml issues I'm seeing.

https://user-images.githubusercontent.com/14093851/122252744-6f195900-ce80-11eb-9546-f497eddaa892.mp4

**Comment by StephenRieger** [comment]
This gist shows the bare minimum of what's needed to reproduce this:

https://gist.github.com/StephenRieger/8485b5d52cac3fdd234db73d87536330

Just click the "Setup" button once, followed by clicking the "Test" button twice. I'm running Mac Catalina/Safari. I've reproduced this in Chrome. I haven't tested this gist on Windows.

And this screen recording shows the results:
https://user-images.githubusercontent.com/14093851/122282135-eb6f6480-ce9f-11eb-9821-522d5579150e.mp4

**Comment by xiruatms** [comment]
Thanks for reporting this. We can repro it now. There's an internal bug 5130762 tracking this.
