### ISSUE TITLE
Word : Replacing starting/end word from range causing removal of that word from range.

### ISSUE THREAD

**Issue by AkshayDudhe** [OfficeDev/office-js#1915]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am working on project where I want to replace words in selection range.When I replace first word from the range it omits the first replaced word and starts from second word which causing position mismatch issue for me. 

## Expected behavior
Range should contain first word after replacement.

## Current behavior
Replaced word is getting removed form the range.

# Script snippet
```
function run() {
  Word.run(async (context) => {
    console.log("script started");
    try{
    var para = context.document.body.paragraphs;
      context.load(para, 'text');
      await context.sync();
    var range = para.items[0].getRange();
      context.load(range, 'text');
      await context.sync();
      console.log(range.text); //here it shows whole paragraph

      var found = "learn"; //first words in range
      var replacement = "Learn"; //replacements

      
        var searchResults = range.search(found,{matchCase: true , matchWholeWord:true});
        context.load(searchResults,'text');
        await context.sync();
        searchResults.items[0].insertText(replacement,Word.InsertLocation.replace);

      context.load(range,'text');
      await context.sync();
      console.log(range.text); //first replaced word is missing from range
    } catch (err){
      console.log(err);
    }
  });
}
```

**Comment by AbidRahman-MSFT** [comment]
Hey @AkshayDudhe - thank you for submitting the issue. Can you provide a sample document or text that you are running this script on?

**Comment by AkshayDudhe** [comment]
@AbidRahman-MSFT, You can use any text, just replace the values for **_found_** and **_replacement_** variable in snippet with first word of your text and it will get reproduced.
I used text starting with word "learn" therefore set those values.
