### ISSUE TITLE
[Excel] Enable/Disable Ribbon button not working on Chrome browser.

### ISSUE THREAD

**Issue by kullachoke-bosuwan-rft** [OfficeDev/office-js#1919]
https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands
Enable/Disable Ribbon button not working on Chrome browser. The code used to work fine and we haven't change anything. Today ribbon api for enable/disable stop working with an error shown in image attached. We have already check following command in doc, the api should support. `Office.context.requirements.isSetSupported('RibbonApi', '1.1')` -> true
![Screen Shot 2564-06-11 at 15 24 29](https://user-images.githubusercontent.com/64405659/121657364-8ba54200-caca-11eb-8a2a-62dd85264bd4.png)

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Mac OS
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Api should works as it used to without any error.

## Steps to reproduce
1. use this function `Office.ribbon.requestUpdate`. 

## Useful logs
Unhandled Promise rejection: The API you are trying to use is not available. It may be available in a different scenario.

**Comment by sohailzafar** [comment]
Hi, thanks for reporting this. Just making sure that you are using shared runtime https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime.

**Comment by kullachoke-bosuwan-rft** [comment]
Yes, we're using shared runtime. Other platform like Excel for Windows and Excel for Mac are working fine. Web version used to work as well until last Friday, It start throwing this error and stop working.

**Comment by sohailzafar** [comment]
Got it, can you also share the version number of chrome? Also is it correct to assume that you have already tried to repro this issue on other browsers like Firefox Safari, or Edge and the issue did not repro there?

**Comment by kullachoke-bosuwan-rft** [comment]
My chrome version: 91.0.4472.77 (Official Build) (x86_64) Mac OS (Cartalina 10.15.7)

By the way, I just test it on Safari and Edge Chromium. The issue also reproducible, I think it happens on all web version.

**Comment by ElizabethSamuel-MSFT** [comment]
@kullachoke-bosuwan-rft Are you still able to repro this?

@preethikakiru Can you take a look?

Thanks.
