### ISSUE TITLE
Word online: ContentControl's cannotEdit property prevents deleting just the content control

### ISSUE THREAD

**Issue by StephenRieger** [OfficeDev/office-js#1922]
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.14209.41004
* Operating System: Mac Catalina, Windows 10
* Browser (if using Office on the web): Safari, Edge, Chrome
 
## Expected behavior
When I set a content control's cannotEdit property, I expect to be able to select the entire content control (and just the content control) and delete it. That works correctly for the desktop clients, but does not work for the web client.

## Steps to reproduce
When a content control whose cannotEdit property is set to true is in a paragraph with text before and after, I can delete the content control if I first select a range that includes text before and after the control control. If I select just the content control, I cannot delete the content control. If set the cursor to the end of the paragraph and press delete until the cursor is at the end of the content control, all characters up to the content control are deleted, but the deletion stops there. At that point, if I triple click to select the entire paragraph, pressing the delete key does nothing.

# Provide additional details
I've attach a sample document that contains a single paragraph with one non-editable content control.

## Context
We'd prefer to mark content controls as non-editable as their content really shouldn't be edited by the user, but not being able to reliably delete a content control means we can't set them as read-only because it's just too confusing. For example, if the content control is at the beginning or end of a document, select all + delete doesn't work.

## Sample document
[non-editable content control.docx](https://github.com/OfficeDev/office-js/files/6641201/non-editable.content.control.docx)

**Comment by leejordan** [comment]
Hello sorry to bother but is there any idea on when this issue might be fixed?

**Comment by anotherstarburst** [comment]
Just commenting to show life in this issue. It still persists, and is causing difficulty.

**Comment by lukamaletin** [comment]
Thank you for your patience. The issue is now resolved and the fix is fully rolled out to production. Please verify it works as expected on your end, and let us know if you face any issues.
