### ISSUE TITLE
Outlook Add-in Icon not working on Android or new Mac UI

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#1924]
## Your Environment

* Android mobile app (Outlook)
* Mac Desktop Outlook (New UI)
 
## Expected behavior
The icon shows as expected like on other platforms.

## Current behavior
Currently, the icon for our add-in on Android and Mac Outlook (new UI) is the default add-in icon.

## Steps to reproduce
Use ```https://cdn.virtru.com/outlookjs/images/virtru16.png``` as your icon image within the manifest and then view the add-in icon on Android or Mac Desktop (new UI).

**Comment by alison-mk** [comment]
Hi @cody-lettau, thank you for submitting this issue! I've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by exextoc** [comment]
We are not able to reproduce this issue from our end.Can you please share the manifest to investigate further?

**Comment by cody-lettau** [comment]
@exextoc can I shoot you an email with the manifest? Maybe we have an issue with the format of our manifest.

We are typically loading the manifest via OWA using a local file. The add-in icon works okay across most platforms (OWA, Mac Desktop -- not the new UI though, iOS, Windows Dekstop), but does not appear on Android or the Mac Desktop - New UI. We see just the default add-in icon instead.

**Comment by exextoc** [comment]
Please email it to OutlookAddins@M365x693897.onmicrosoft.com.

**Comment by cody-lettau** [comment]
@exextoc thank you -- just sent it over.

**Comment by exextoc** [comment]
We are able to reproduce it. 
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by cody-lettau** [comment]
@exextoc thanks for taking a look. Completely understandable that it goes on the backlog, but I'm not sure the bug should be closed.

**Comment by exextoc** [comment]
Apologies for closing the issue. 

We'll update the thread as and when a decision is taken on the bug (fixed / deciding not to fix).

**Comment by exextoc** [comment]
Hello @cody-lettau 

We investigated the issue on android and below are our observations.

Android picks up icon URL based on the device type (Phone / Tablet)
If its tablet, it picks up the URL as https://cdn.virtru.com/outlookjs/images/virtru48.png and the link is working as expected. This URL is same for all other platforms (win32, OWA, Mac Old UI).

If its phone, it picks up the URL as https://cdn.virtru.com/outlookjs/images/virtru32.png, which is broken. This is the reason, the icon appears different on Android devices.

There are 2 possible solutions:
- Please specify the same URL in the manifest, and it will start working for Android as well.
- Please ensure that the https://cdn.virtru.com/outlookjs/images/virtru32.png has the desired icon.

Furthermore, we are investigating the mac issue, and will get back with a resolution soon.

Thanks

**Comment by cody-lettau** [comment]
@exextoc thank you very much for digging into this and pointing out the issue! We will get that size of the icon fixed and give it a try. As for the new Mac UI, if that takes longer that is okay as it doesn't fully support our feature set and we are not supporting it at this time.

**Comment by exextoc** [comment]
@cody-lettau Were you able to solve the issue by changing the size of icon?

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
