### ISSUE TITLE
Script error when loading telemetry script

### ISSUE THREAD

**Issue by deificx** [OfficeDev/office-js#1925]
# Provide required information needed to triage your issue

## Your Environment

The users environment is:

* Platform: **PC desktop**
* Host: **Outlook**
* Office version number: **2016 (16.0.5.5161.1000) MSO 816.0.5.5161.1002) 64 bit**
* Operating System: **Windows 10**
 
## Expected behavior

Parse and run script, no script error.

## Current behavior

When calling `Office.context.ui.displayDialogAsync` a telemetry script seems to fail to parse in Outlook if they happen to use IE11 as the rendering engine. The path includes `…_host_Info=Outlook$Win32$16.01$nl-NL$telemetry$isDialog#…` and the script `appsforoffice.microsoft.com/lib/1/hosted/telemetry/oteljs_agave.js` crashes with a generic "Script error" message on line 0, column 0.

## Steps to reproduce / Link to live example(s)

1. load https://static.vp.vc/me.pexip.outlook.manifest.alpha.xml
2. Launch it from either new message or new event context
3. Click the Login button at the bottom of the add-in, this should prompt for a popup to open (ie. `Office.context.ui.displayDialogAsync` should trigger)
4. Pop-up opens, but script crashes

## Context

So this is a bit hard to reproduce for me because I don't have access to the same outlook version. In most versions this seems to just work as expected. I've tried digging a bit but outside of the outlook context and testing in IE11 but it fails on `isSetSupported`, possible that `requirements` does not exist in the context that script has access to at that time.

**Comment by alison-mk** [comment]
Hi @deificx, thank you for submitting this issue! I've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by exextoc** [comment]
I looked into this and can repro the script error in Outlook 2016 MSI version. However, in my repro this particular script error is handled and does not impact dialog functionality.  In your customer's repro, are dialog functionality impacted if they dismiss the script error (and optionally select not to show the message again)?

**Comment by deificx** [comment]
We've attached a listener on `window.onerror` which trigger every time for our customer and they can't get through that. I guess we could ignore our error handling for this instance but it would be nice if it didn't crash, I think.

**Comment by exextoc** [comment]
At this point fixes for Outlook 2016 are limited to security and serious fixes, so this won't be able to be modified. Also at the end user level they should make sure that IE is not displaying a notification for every script error under IE->Tools->Internet Options->Advanced->Display a notification for every script Error: 

![image](https://user-images.githubusercontent.com/28549921/122844113-c589fb80-d2b5-11eb-96b8-07cb99eeee51.png)
