### ISSUE TITLE
Word online: Can't copy/paste or cut/paste content controls

### ISSUE THREAD

**Issue by StephenRieger** [OfficeDev/office-js#1926]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.14210.41001
* Operating System: Mac/Catalina
* Browser (if using Office on the web): Chrome, Safari
 
## Expected behavior
Copying/pasting (or cutting) a selection that contains a content control should paste a copy of original content control. That's what happens in the desktop app. This should work when pasting into the same document and into a different document.

## Current behavior
Pasting a selection that contains a content control just pastes the text that is in the content control. That means that editing a document can easily break any add-in that uses content controls to store meta-data associated with the contents of the content control.

## Steps to reproduce
Just copy/paste a content control in any document.

**Comment by alison-mk** [comment]
Hi @StephenRieger, thank you for submitting this issue! We've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison
