### ISSUE TITLE
DisplayName hover text rendered with &quot entities when language is german

### ISSUE THREAD

**Issue by siseli** [OfficeDev/office-js#1927]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Your Environment
* Host: Outlook
* Office version number: Web, Office365 (Version in JS: 20210524004.18)
* Operating System: Windows
* Browser: Edge
* Language: German (Switzerland)

We provide an Outlook Addin with DisplayName "Vertec Outlook App" 
Our Addin registers a TaskPane in Outlook.

## Expected behavior
When I hover over the pin button of the task pane, a text "Vertec Outlook App lösen" should appear.
The englisch text would be "Unpin Vertec Outlook App"

## Current behavior
When the outlook language setting is "German (Switzerland)" the hover text ist displayed as "&quot; Vertec Outlook App lösen &quot;".

![grafik](https://user-images.githubusercontent.com/51451007/122164774-91f33f80-ce77-11eb-8a11-31560a76e382.png)

When switching to english language, the hover text is displayed correctly as "Unpin Vertec Outlook App".

## Steps to reproduce
The problem happens with any office addin, when the language of outlook is set to german.

**Comment by exextoc** [comment]
Thanks for reporting this issue . It has been put on our backlog. We unfortunately have no timelines to share at this point
