### ISSUE TITLE
Inline images add by API missing after send

### ISSUE THREAD

**Issue by milankonir** [OfficeDev/office-js#1928]
# Provide required information needed to triage your issue

## Your Environment

* Platform: Office on the web 
* Host: Outlook
* Office version number: N/A
* Operating System: Mac
* Browser (if using Office on the web): Google Chrome 91.0.4472.101 (Official Build) (x86_64)
 
## Expected behavior

The inline images attached via API should not be broken after hitting send.

## Current behavior

After adding inline attachment via API and referencing it in the email body via img with `src="cid:xxx.yyy"`, it displays just fine. After hitting send, the inline images attached via API are not processed correctly and they are broken in the outgoing email.

## Steps to reproduce

1. Add base64 attachment via Script Lab using referenced Gist
2. Wait for inline image to appear in the email
3. Send to any recipient
4. View email in the outbox email or recipient's inbox
5. Inline image is broken

## Link to live example(s)

1. Gist: https://gist.github.com/milankonir/3763c289af69076595f9bbd79e700b2f
2. Video: https://cl.outreach.io/6qurxn1G

# Provide additional details

This only happens in Outlook on Web, also tested in Outlook for Mac and the inline images are sent ok there.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
@milankonir We have fixed the issue. Please check and let us know if it works for you.

**Comment by milankonir** [comment]
I have verified that this now works as expected, thank you!
