### ISSUE TITLE
Custom Word and Outlook add-ins are not loading for 2 specific users with Angular2 SystemJS errors. 

### ISSUE THREAD

**Issue by JulesRM** [OfficeDev/office-js#1930]
My Word and Outlook add-ins are not loading. They fail to load the webpage for our add-in with the error below. We try to navigate to the address for our add-in in a separate Edge and it loads correctly,  https://office.rocketmatter.net/Documents/
Instead of showing the Login screen it just shows the loading spinner because of a JavaScript SystemJS error, 

### This is working ok for everyone except 2 users. Maybe it is limitations in the ActiveDirectory permissions, Word permissions or Office 365 policies?
![image](https://user-images.githubusercontent.com/82992986/122242185-59a42f00-ce80-11eb-9908-97ef06fb80c4.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Windows 10
* Host [Excel, Word, PowerPoint, etc.]: Word and Outlook add-in panes
* Office version number: Word version 2105 Build 14026.20270
* Operating System: Windows 10
* Browser (if using Office on the web): The word Addin pane, I believe it uses Edge
 
## Expected behavior
Add-in should load the web page,
![image](https://user-images.githubusercontent.com/82992986/122255106-097e9a00-ce8b-11eb-8ca8-b99a6bdab259.png)

## Current behavior
 instead it shows an error on the console 
Tracking prevention is just a warning, it does not prevent the add-in from loading correctly.
Error when running Word as administrator:
(SystemJS) XHR error loading ..PromiseObservable.js followed by Office.js has not fully loaded.
![image](https://user-images.githubusercontent.com/82992986/122243504-67a67f80-ce81-11eb-94cc-a8049bba5c3c.png)

Error when running Word normally, not as administrator:
(SystemJS) Invalid or unexpected token followed by Office.js has not fully loaded.
![image](https://user-images.githubusercontent.com/82992986/122244159-e3083100-ce81-11eb-9d2e-c090d4a825ca.png)

### 1. We are seeking guidance to help identify which setting we can change to solve this error.
2. Unfortunately we are currently unable to reproduce it on another machine.

## Link to live example(s)
None

# Provide additional details None

## Context

affecting the users that cannot use the add-in. We are trying to solve this issue by tweaking settings or anything we need to do, but the error is not helpful at all to actually solve the issue. It must be add-in permissions for the Browser Pane, because it loads correctly in a separate Edge browser. This add-in loads correctly for everyone except 2 users!

## Useful logs

- [X ] Console errors
- [X ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by alison-mk** [comment]
Hi @JulesRM, thank you for submitting this issue! 

@AbidRahman-MSFT, can you take a look and help resolve or provide suggestions? 

Thanks, 
Alison

**Comment by exextoc** [comment]
By any chance are those two users on older versions of Office or Windows? Older versions of Office/Windows will run IE11, and has some issues with Angular. 

See

ShaoFeng's response here: 

https://github.com/OfficeDev/office-js/issues/1757

specifically to add: 
`<script type="text/javascript">window.history.replaceState=null;window.history.pushState=null;</script> `
to your index page
