### ISSUE TITLE
conversationId is null on a new mailitem

### ISSUE THREAD

**Issue by 0xA17C** [OfficeDev/office-js#1933]
# Provide required information needed to triage your issue
If I go by the documentation for the conversationId [here](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-1.10#conversationId), a new mailitem should have a conversationId value if the user sets a subject and saves it as a draft.
I tried saving the new mailitem via UI and with the `saveAsync` API, but in both cases I kept getting `null` for the conversationId.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: OfficeOnline
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 0.0.0.0
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome 91
 
## Expected behavior

After saving the new mailItem, the conversationId should return a value.
## Current behavior

`Office.context.mailbox.item.conversationId` returns `null`.

## Steps to reproduce

1. create a new mail
2. add recipient and a subject
3. save the item
4. access `Office.context.mailbox.item.conversationId`

## Link to live example(s)

https://gist.github.com/nanexo/f1054bfb314416ec351ec38ebc1f2c48

## Context

Upon sending the mail the user is able to sync the sent (or rather the to be sent in this case) mail to our system. We use the [OnSend API](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins) for this. To quickly see what mails are part of the same conversation we need the conversationId.

Replying to or forwarding mails do not have this issue. In those cases I always get a conversationId.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by alison-mk** [comment]
Hi @nanexo, thank you for submitting this issue! I've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
This bug is closed due to inactivity for a long time. If the issue resurfaces, please re-open it. Thank you.
