### ISSUE TITLE
The custom function try to read the saved version of manifest in file.

### ISSUE THREAD

**Issue by puripats** [OfficeDev/office-js#1937]
# Provide required information needed to triage your issue
Looks like when the excel save xlsx file they also save the version of manifest to file. This cause some issues when manifest updated but used old file. Then the ERROR-ADDIN occurs.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2008(Build 13127.24668)
* Operating System: Window10
* Browser (if using Office on the web): -
 
## Expected behavior
No need to clear Taskpane Add-In anytime manifest version is changed.

## Current behavior
Need to clear Taskpane Add-In anytime manifest version is changed.

## Steps to reproduce
In this scenario, we try to make it simple. The step to reproduce.
1. Use manifest.xml from this article 
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows.
2. put custom function '=CONTOSO.ADD(10,250)' to cells
3. save file example.xlsx
4. change version manifest in manifest.xml to be 1.0.0.1
5. build manifest again.
6. open file example.xlsx
7. now Excel tell that this 'ADD-IN ERROR' because this ADD-IN in no longer available.(Custom function is still works fine)
8. To fix this, we need to use Document Inspectors to remove it and as far as I known this solution can use in Window installed version or manually delete 'webextensions' folder inside xlsx file.
9. After that, No add-in error and function works fine.

## Link to live example(s)

# Provide additional details

## Context
Today, manifest version changed. I got the error message from my file that I worked yesterday. So this is not actually bug but maybe there are another ways to prevent this to happen or option to not save manifest version.
Then the customers do not need to Document Inspectors when anytime the manifest version change.

## Useful logs

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by alison-mk** [comment]
Hi @puripats, thank you for submitting an issue. If you change the manifest.xml, then for the best experience you will need to stop your node server, close Excel, follow directions to [Clear the Office cache](https://docs.microsoft.com/office/dev/add-ins/testing/clear-cache), and then restart your node server and reopen Excel. 

Does your issue occur even after following these steps? 

Thanks, 
Alison

**Comment by puripats** [comment]
After follow the step, the issue still occurs.

**Comment by alison-mk** [comment]
Hi @puripats, thanks for testing again. Because clearing the cache doesn't help, I've assigned this issue to the engineering team who will be able to provide you with more information or help resolve. 

Cheers,
Alison

**Comment by 4tti** [comment]
@alison-mk, @puripats  yup, this is 'weird' design and the only feasible solution for the end-user is to use windows version of Excel and use 'inspect document' to remove 'Task Pane add-ins'...
![image](https://user-images.githubusercontent.com/19533927/123814980-68fe9000-d8f6-11eb-90b0-a2d42886f854.png)

It would be awesome to have option to not store these things into the file...

**Comment by grangeryy** [comment]
@puripats may I know why you changed the manifest version in "step 4 change version manifest in manifest.xml to be 1.0.0.1"? Accidently or on purpose you need to have an update?

**Comment by puripats** [comment]
> @puripats may I know why you changed the manifest version in "step 4 change version manifest in manifest.xml to be 1.0.0.1"? Accidently or on purpose you need to have an update?

I try to replicate my workflow. When I updated my custom function code the version should update along with it. For example, fixed bug, add feature etc.

**Comment by grangeryy** [comment]
@puripats If I understand it correctly, what we are discussing here is an improvement ask: if code is updated, the manifest version should be automatically update?

**Comment by puripats** [comment]
> @puripats If I understand it correctly, what we are discussing here is an improvement ask: if code is updated, the manifest version should be automatically update?

Yes that's right.

**Comment by grangeryy** [comment]
@mattgeim do we have work item already tracking this ask? Thx!

**Comment by adrianwu8516** [comment]
Hi @puripats, would like to confirm with you if this issue is still bothering you?
