### ISSUE TITLE
Excel Online: Unable to remove event handler if add-in frame has been reloaded

### ISSUE THREAD

**Issue by nikolay-borzov** [OfficeDev/office-js#194]
My add-in app adds a handler for `WorksheetCollection.onActivated` event on startup.
```
Excel.run(context => {
  // this.onWorksheetActivated simply outputs "Worksheet Activated"
  context.workbook.worksheets.onActivated.add(this.onWorksheetActivated);
  return context.sync();
}).catch(ExcelHelper.handleError);
```
Chrome allows reloading add-in frame through context menu item "Reload frame". When it happens the app startup logic is executed.
In order to remove the event handler I added a line before `onActivated.add`
```
context.workbook.worksheets.onActivated.remove(this.onWorksheetActivated);
```

It doesn't seem to work. I see multiple "Worksheet Activated" in console.
When I looked into `GenericEventHandlers.prototype.remove` I noticed that `_this._handlers` is empty.

## Expected Behavior

`context.workbook.worksheets.onActivated.remove` must remove existing event handler even when add-in frame is reloaded
OR
API should unregister event handlers when add-in frame is reloaded
OR
A method to unsubscribe from all events within add-in

## Current Behavior

Looks like event handlers are hanging somewhere. Perhaps reloading add-in frame is not considered as add-in reloading. I know about `eventResult.remove();` method but it isn't applicable for the case.

## Steps to Reproduce, or Live Example

```
export class ExcelEventsService {
  init() {
    this.registerActivatedEvent()
  }

  registerActivatedEvent() { 
    Excel.run(context => {
      context.workbook.worksheets.onActivated.remove(this.onWorksheetActivated);
      context.workbook.worksheets.onActivated.add(this.onWorksheetActivated);
      return context.sync();
    });
  }

  onWorksheetActivated(args) { 
    console.log('Worksheet Activated', args);
  }
}
```

* Additional details:
  1. Unregister event via `context.workbook.worksheets.onActivated.remove`
  2. Register event via `context.workbook.worksheets.onActivated.add`
  3. Reload add-in frame using context menu item "Reload frame"

## Context

Add-in is Angular 2 application. Excel events are registered inside `ngOnInit` of the root component.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: MS Office ProPlus, Excel Version 1805 (Build 9330.2118 Click-to-Run)
* Operating System: Windows 10
* Browser (if using Office Online): Chrome

## Useful logs

There are no errors in console

**Comment by ShawnNiu** [comment]
Hi Nikolay, thanks for trying out the new API! This is a known issue for us right now and we are actively looking through the solutions. We'll keep you updated once the fix rolls out.

**Comment by JuaneloJuanelo** [comment]
tracking internally with 2461790

**Comment by misaunde** [comment]
Any known workarounds for this?

**Comment by nikolay-borzov** [comment]
> Any known workarounds for this?

I had to debounce event handlers. Not a good workaround though.

**Comment by ShawnNiu** [comment]
@misaunde  @nikolay-borzov We fixed the problem. The event handler will be removed once refreshed. The change will be rolled out soon within one or two weeks

**Comment by misaunde** [comment]
@ShawnNiu great news! Btw, when you say rolled out soon, do you mean to the insider track or to everyone?

For now, I ended up just adding the event handler at the root of my app (app.component.ts) so it only got added once, and then I added a condition at the start of my '.onWorksheetActivated()' function so it would only execute when I wanted it to...

**Comment by ShawnNiu** [comment]
the release will be a public one
