### ISSUE TITLE
Setting an internetHeader causes a blank draft to be saved in Outlook

### ISSUE THREAD

**Issue by barclayadam** [OfficeDev/office-js#1940]
In an event-based activation handler if I call `Office.context.mailbox.item.internetHeaders.setAsync` then a draft will be added to Drafts folder of Outlook when closing the email, even if nothing else has happened (i.e. no body added, no recipients etc.).

## Your Environment

* Platform: Windows / OWA
* Host: Outlook
* Office version number: OWA & Outlook 365 v2106 Build 14131.20012
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome v91
 
## Expected behaviour

Setting just a header should not save a draft, the user experience is odd and can leave completely blank drafts even without the user doing anything. Given the headers are a hidden detail to the user, having that trigger a draft seems wrong

## Current behavior

When closing a compose surface (i.e. hitting the x on the tab at the bottom of the window in OWA) a completely blank draft is saved.

It should be noted that if we set a signature (`setSignatureAsync`) and THEN add a header the draft being saved is STILL completely blank, it does not contain the signature we set

## Repro
The below script is added to the manifest for launch-based activation

````typescript
function setHeader(event) {
    Office.context.mailbox.item.internetHeaders.setAsync(
        {'X-My-Header': 'Value1'},

        function (asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Failed) {
                console.error('Setting internet headers failed', asyncResult.error);
            } else {
                console.info('Successfully set internet headers');

            }

            event.completed();
        });
}

Office.actions.associate('onMessageComposeHandler', setHeader);
````

**Comment by lindalu-MSFT** [comment]
Thanks for reporting, I've tagged the Outlook team to triage this and so they'll be in touch if they need additional info.

**Comment by exextoc** [comment]
Your environment settings indicate that this is both Win32 and OWA. Are you hitting this issue in One or Both versions?

**Comment by exextoc** [comment]
A bug has been opened for this on the core product team. 
internal tracking ID: office: 5211332

**Comment by barclayadam** [comment]
@exextoc Thank you for getting back to me. I have seen this in both versions from above. It can also be replicated in other builds of desktop, although primarily testing was with those builds as above

**Comment by exextoc** [comment]
We are able to reproduce the bug in OWA. 
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by barclayadam** [comment]
@exextoc We were seeing this same behaviour in Outlook desktop, which for us is the more critical client. Can you confirm if you have replicated it successfully in the desktop client too?

**Comment by exextoc** [comment]
The same is reproducible in windows outlook client. 
As suggested above, a bug has been opened for this on the core product team.
internal tracking ID: office: 5211332

**Comment by barclayadam** [comment]
Thank you for the quick reply. Is there any way of externally tracking these bugs, or being notified of changes in any way? It affects our product development strategy so would be great to have any sort of insight

**Comment by lindalu-MSFT** [comment]
@barclayadam sadly we don't have a way to connect GitHub with our internal bug database. The Outlook team is VERY responsive and should update you here. You can always @exextoc when you need an update.

**Comment by barclayadam** [comment]
@exextoc is there any update on this bug? Do we have a timeline for a fix for this?

**Comment by exextoc** [comment]
For Windows, the bug has been fixed for builds above 16.0.14308.10000.

**Comment by exextoc** [comment]
For OWA, the bug is in the backlog. We will look into the issue, on priority.

**Comment by exextoc** [comment]
The behaviour is by design in OWA. Any change in outlook item will result in auto-save by the OWA.

**Comment by barclayadam** [comment]
@exextoc I'd urge you to reconsider this decision as it feels like this hurts the UX in two ways:

First, this makes the product inconsistent with Outlook Desktop, as per the previous bug fix whereas I would have expected a more unified approach to these decisions (especially given the direction of One Outlook which suggests unification is a longer-term strategy).

Second, customers are confused by this after installing our add-in that a) sets a signature and b) adds a header about said insertion. 

The issue as we, and our customers, see it, is that they have not actually made any changes to the email, only automation have and therefore to see a "Discard message" popup and a draft item is unexpected and unwanted. 
    
If you are to create an email, add a header and signature but do nothing else you have no opportunity to lose anything valuable., I would not expect to see a "discard changes" popup. If a signature was added through the Outlook UI the user does not get this message, so adding through the API should present the same UX. And headers are entirely invisible, so therefore it is confusing to cause a change in behaviour here.
