### ISSUE TITLE
ExtendedOverrides element of Manifest error is VS2019

### ISSUE THREAD

**Issue by osvath58** [OfficeDev/office-js#1941]
When creating an Office.js Add-in in Visual Studio 2019, adding the <ExtendedOverrides> element to the manifest, in order be able to add keyboard shortcuts, the following error is thrown:
_The element 'OfficeApp' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1' has invalid child element 'ExtendedOverrides' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1_

* PC desktop
* Excel
* Office version number: Version 2002 (Build 12527.20988 Click-to-Run)
* Operating System: Windows 10

**Comment by AbidRahman-MSFT** [comment]
Hey @osvath58, can you share your manifest? @madhavagrawal17 FYI

**Comment by cgaranip** [comment]
Hi, I have the same issue. 
Using VS 2019, office 365 version 1202. 
Followed the steps as in https://docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts

[manifest.txt](https://github.com/OfficeDev/office-js/files/7193231/manifest.txt)

Error: The element 'OfficeApp' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1' has invalid child element 'ExtendedOverrides' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1'. List of possible elements expected: any element in namespace 'http://www.w3.org/2000/09/xmldsig#'.	MPSInputsApp	C:\Projects\OneMPS\master\applications.services.smds.onemps.mpsinputsapp\MPSInputsApp\MPSInputsApp\MPSInputsAppManifest\MPSInputsApp.xml

Attached the manifest file.
