### ISSUE TITLE
Word add-in error in IE- SCRIPT1002: Syntax error in polyfills.79103d5fc64157e59efa.js (1,78)

### ISSUE THREAD

**Issue by rasharmkum** [OfficeDev/office-js#1948]
While running word add-in (developed using Office.js 1.1 API set, angular 12 and typescript) in IE11, we are getting below error messages. We are using IE11 to mimic the customer environment where requirement is that add-in should work in WORD 2016 as well.

We are getting same error for main.js, pollyfills.js, runtime.js and vendor.js-
    SCRIPT1002: Syntax error
    polyfills.79103d5fc64157e59efa.js (1,78)

    SCRIPT1002: Syntax error 
    runtime.fc9b6fc936f6b31d1143.js (1,4)

    SCRIPT1002: Syntax error
    main.bbb9399a14eb1ffd5ae0.js (1,72) 

Since this issue has become blocker for us and for customer to test Word add-In using Word 2016, any help will be much appreciated. 
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/86354991/123145185-32e68980-d47a-11eb-8c75-c1481b0a0267.png)
<img width="843" alt="Capture1" src="https://user-images.githubusercontent.com/86354991/123146064-1eef5780-d47b-11eb-9f6f-f9aa414413bb.PNG">

**Comment by lindalu-MSFT** [comment]
Can you please provide us with your Office version, environment details, and preferably the script itself so we can try to replicate? We can't triage without more info to repro. Thanks, Linda

**Comment by rasharmkum** [comment]
> Can you please provide us with your Office version, environment details, and preferably the script itself so we can try to replicate? We can't triage without more info to repro. Thanks, Linda

Hello, please find below the details:
Office version Office 2016
environment details Windows 10
script Attached in zip format.
[MAC.Builder.zip](https://github.com/OfficeDev/office-js/files/6710422/MAC.Builder.zip)

Additional info-
We have used office.js.

**Comment by ElizabethSamuel-MSFT** [comment]
@rasharmkum Apologies for the late response. Are you still facing this issue?

@wangyun-microsoft Can you take a look?

Thanks.
