### ISSUE TITLE
UI-less autorun get external data not working

### ISSUE THREAD

**Issue by vdboots** [OfficeDev/office-js#1949]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2105
* Operating System: Windows
* Browser (if using Office on the web): ______
 
## Expected behavior
Should grab the result from the fetch command. when opening a new email message

## Current behavior
On Outlook for windows when using a (fetch or xmlhttprequest) it should grab the result(this is working in the browser). But when running the command from a  Outlook for Windows this breaks the code.

## Steps to reproduce

1. Create an application the uses a autorun (for instance : https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/outlook-set-signature).
2. in the example case above add a fetch command in the checkSignature() function. The code wil break right away.

## Context
i am trying to get a signature from an external webservice(azure Function). This works great for outlook on the web but not at all for desktop.

## Useful logs
are there any logs on ui-les for Outlook for Windows ?

**Comment by exextoc** [comment]
For desktop Outlook in this case, only simple CORs is available. Though this document references Excel (https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime) the section on Requesting external Data/CORs applies here as well. 

The current workaround for this is to build your own service on the same domain as your add-in, and let your add-in talk to your service, and let your service talk to the external resource. This isn't an ideal solution, but it is the current method to solve this problem.

**Comment by vdboots** [comment]
Thank you i will wrap than in  an Azure static website together 👍

**Comment by vdboots** [comment]
After running multipe tests is running a command like fetch does not seems to work not even to same origin. 

I used fiddler but when running from autorun fetch does not seem to work. When running from  taskpane it works on desktop.
Is there a working example available ?

**Comment by exextoc** [comment]
We don't have a sample to share, however, we have multiple partners who are using this workaround.
Their add-in's JavaScript is hosted on the same server/origin as the service they are communicating with.
There's probably a missing configuration in Azure to make this work.
Just to confirm, what specific error do you get when making the fetch?

**Comment by vdboots** [comment]
If found the issue. It is working on a normal domain. But when using a subdomain like dev.api.domain.com it stops reacting.

**Comment by exextoc** [comment]
Glad you were able to find the issue. I am closing this issue, please reopen if you have any more questions.
