### ISSUE TITLE
New Outlook for Mac always uses default add-in displayName

### ISSUE THREAD

**Issue by austinhimler** [OfficeDev/office-js#1950]
In the new Outlook for Mac experience, the button label for our add-in always displays the default display name set in the manifest, not the locale override (as displayed in the old Outlook for Mac experience). If the display language is en-us, and there is a locale override for the displayName, the add-in still displays the default value for the displayName instead of the locale override (which is the expected behavior).

For instance, if this is the default display name in the installed add-in manifest and the display language is en-us:

DisplayName DefaultValue="Default Button"

and listed below it is the locale override for en-us:

Override Locale="en-us" Value="English Override" 

The add-in's label is always 'Default Button' rather than the expected behavior (the button label should display 'English Override'). This only occurs in the new Outlook for Mac experience, not in the old Outlook for Mac experience (which displays 'English Override' as expected).

## Your Environment
macOS Big Sur version 11.4
Outlook for Mac version 16.51 (21062001)
new Outlook for Mac experience

## Expected behavior
expect add-in label to use display language locale override

## Current behavior
add-in label uses default display language value

## Steps to reproduce
install add-in with manifest that has a locale override value that's different from the display name default value

## Context
We have customers who want to use the new Outlook for Mac experience and want the button to have the same label in the new UI than it has in the old UI (as to not confuse their users).

**Comment by exextoc** [comment]
Can you please share a sample a manifest where the behavior is reproducible ?

**Comment by austinhimler** [comment]
[github manifest copy.txt](https://github.com/OfficeDev/office-js/files/6717112/github.manifest.copy.txt)

I added the manifest as a txt file, since Github doesnt let me attach xml files. If there's an issue with the txt file, i'd be happy to email you the xml directly if you provide an email address i can use.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding displayName. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by madhavagrawal17** [comment]
@austinhimler, We investigated this issue. It seems the behavior is by design. We don't parse the Overrides when the current locale is the default Locale. For this scenario as en-US is the default and the current locale, we use the default value of the DisplayName. In order to fix this please update the DefaultValue for the property DisplayName in the manifest.
