### ISSUE TITLE
No way to get Accesstoken in ui-less script(Office on Windows).

### ISSUE THREAD

**Issue by vdboots** [OfficeDev/office-js#1952]
No way to get Bootstraptoken in ui-less application

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook Desktop
* Host [Excel, Word, PowerPoint, etc.]: outlook
* Office version number: 2105
* Operating System: Windows 10
 
## Expected behavior
When using a dialog or GetAccessToken()l it would return an accesstoken in an ui-less experience.

## Current behavior
Both methods are not supported at the moment.  so there is no secure way in Outlook for desktop to ui-less response

## Steps to reproduce
1. put a getaccesstoken(); method in a ui-less javascript method and it will break;
2. try to open i dialog to get an bootstraptoken(or other way to authenticate) from ui less will not execute

## Context
we would like to get graph data of the current user to see if the user information is correctly setup for this we need a way to identify the user without opening a Taskpane

**Comment by exextoc** [comment]
UI-Less can generally refer to two different ExtensionPoints. With ExecuteFunction (executed manually by users with a button on the ribbon), this should work, but I suspect you are using **LaunchEvent** (such as AutoRun on new mails), where this function is not supported yet on that ExtensionPoint.

**Comment by lindalu-MSFT** [comment]
Hi @vdboots You can suggest this by going to our feature request forum: https://aka.ms/m365dev-suggestions and click "submit an idea." If you do submit a feature suggestion, please put the link here in a comment. Thanks!

**Comment by exextoc** [comment]
For [Event-Based Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch), we do not yet support [getAccessToken API](https://docs.microsoft.com/en-us/javascript/api/office/office.auth?view=excel-js-preview#getAccessToken_options_).

**Comment by vdboots** [comment]
Is there any timelime if this will be supported? i posted a question for the feature.  It is supported on the web. But now there is now way to get u user token Event-Based.

**Comment by exextoc** [comment]
I cannot comment on the timeline for when this will be supported. 
This is a feature that we know is needed.

**Comment by exextoc** [comment]
We have fixed this bug.
For the Semi-Annual Channel, the fix should be available in build 16.0.14326.20258 or later.
For all other channels, the fix should be available in build 16.0.14425.10000 or later.

When an updated build is available depends on the release channel a customer is on.

**Comment by vdboots** [comment]
thanx great to hear ! 👍
