### ISSUE TITLE
Workbook.save shows a save as dialog

### ISSUE THREAD

**Issue by jwhite-venacorp** [OfficeDev/office-js#1956]
# Provide required information needed to triage your issue

We have a feature in our addin which performs calculations on the workbook, saves the file, gathers some data from the workbook, and then uploads the file to our own cloud file system. To save the file, we are calling `workbook.save(Excel.SaveBehavior.save)`. The first time this feature is used, the workbook saves without a prompt. The second time this feature is used, Excel shows a prompt to save the file. Accepting the default file name and path (which is the same as it was when the file was opened) will save the file and the rest of the code works fine.

I believe this may be related to the `Office.Document.getFileAsync` and `file.getSliceAsync` functions we are calling to get the file's contents. When I skip the `workbook.save` step, the `getFileAsync` callback receives an error result. We then retry the function, and it succeeds.

This bug seems to be particular to a certain file, which unfortunately belongs to a client and may have sensitive data. It is an XLSM file. When I save the file as XLSX, I cannot reproduce the bug. The original (XLSM) file does not have any macros, although the VBA project does have some empty modules and empty forms.

Since this only happens the second time our code is called, I tried using our feature once, then hit `Ctrl-S` to save the file. Excel reported an error: `Errors were detected while saving {file path}. Microsoft Excel may be able to save the file by removing or repairing some feature. To make the repairs in a new file, click Continue. To cancel saving the file, click Cancel.`

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.14210.20004
* Operating System: Windows 10, OS build 19042.1052
* Browser (if using Office on the web): N/A
 
## Expected behavior

`workbook.save(Excel.SaveBehavior.save)` should not show a prompt.

## Current behavior

`workbook.save(Excel.SaveBehavior.save)` shows a "Save as..." prompt.

## Link to live example(s)

# Provide additional details

At this time, we have only seen this with one of our customer's files, and we have not yet found a reproduction case without it.

## Context

We are attempting to locally save the file (to preserve any work in progress) and upload the file to our cloud file system for auditing.

## Useful logs

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by jipinshi** [comment]
@jwhite-venacorp, thanks for reaching us.  may still need your help on finding one reproable gist in scriptlab and one reproable file(maybe data can be changed to other example data since it's secure) but file can be shared. And also better to share one video to make it easier to understand.

**Comment by jipinshi** [comment]
@jwhite-venacorp, hope can get your more input on one reproable gist in scriptlab and one reproable file.
