### ISSUE TITLE
office.js dialog min width isn't 150px

### ISSUE THREAD

**Issue by Simplici** [OfficeDev/office-js#1957]
We have seen a strange behavior for the dialogs in Word addin, it seems that the min width is not 150px as documented, it is in fact 760px on my PC.
## Expected Behavior

The width should be taken into account if it is more than 150px.
## Current Behavior

no matter what value we give to the width property, the dialog width is never less than 760px as if there is a 760px min width limitation. I can't even manually resize the dialog to less than 760px. however, the height works as expected and both height and width work as expected on a Mac.

## Steps to Reproduce, or Live Example

Office.context.ui.displayDialogAsync(<our domain>, {height: 50, width: 50, displayInIframe: true});

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Microsoft 365 MSO (16.0.14026.20202)
* Operating System: WINDOWS 10 family

**Comment by lliu113** [comment]
@Simplici - sorry you're hitting this! Is this something that was working for you before, or has it been broken from the start? Are you able to link the documentation that gives the 150px min width? The height/width parameters are given as a percentage of screen size, so there usually isn't a way to set exact pixel width.

**Comment by Simplici** [comment]
I am not sure, but I think that we don't have this problem before.
here is the link to documentation: https://docs.microsoft.com/en-us/javascript/api/office/office.dialogoptions?view=excel-js-preview
![image](https://user-images.githubusercontent.com/8101111/123786243-0e702e80-d90c-11eb-8584-4f15767a8ad6.png)

we don't really set by pixel, it is just that set by percentage doesn't work. if we set 20% on a 1080p screen, we still get a 760px width dialog.

**Comment by lliu113** [comment]
@Simplici - ah, thanks for the clarification + linking the documentation! I'm unfortunately unable to repro this, the dialog is resizing correctly on Word Desktop for me. Are you able to provide a manifest for your add-in to help us troubleshoot? Are you also able to try launching a dialog via the Script Lab add-in?
