### ISSUE TITLE
Creating a table pushes cells below down by one

### ISSUE THREAD

**Issue by eode** [OfficeDev/office-js#196]
## Expected Behavior
Doing:
```javascript
await window.Excel.run(async function (context) {
  const worksheet = context.workbook.worksheets.getActiveWorksheet();
  const example = worksheet.tables.add(`B1:C1`, false /*has no headers*/);
  example.rows.add(null, [['a', 'b'], ['c', 'd']]);
  return context.sync()
}
```
should not move cells below the specified range down by one when it adds the table.

## Current Behavior
Cells below the specified range move down by one when the table is added.

## Steps to Reproduce, or Live Example
1: have an Office Add-In
2: set it up to call the above code

## Context
I'm attempting to insert a table without implicitly modifying the area below the affected area.

## Your Environment
Windows 10.
Office 365, native installed.  Excel version 1806 (build 10228.20080 click-to-run).

## Useful logs
Nope.

**Comment by JuaneloJuanelo** [comment]
tables by definition require a header row, and hence the line needs to be moved to accommodate this. 
this behavior is by design. if you want to keep the first row make sure you send 'True' in the second parameter to indicate those are the headers of the table.
