### ISSUE TITLE
Html saved by “Office.context.mailbox.item.body.setAsync“ will miss after send event

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#1960]
I tried save a HTML content to body with office api “Office.context.mailbox.item.body.setAsync“. But found that if I set HTML at the very beginning of body some html code(example:<a name="test"></a>) will be 'optimized' after I send this event to others.
And this problem can reproduce every time.
This problem only happened on client especially on Windows Outlook. I tried from windows 1709 to 20H2 all have this problem.
And some Mac also have this problem. But on browser works fine.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac and Windows
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.14026.20294 (just example other version also have this problem )
* Operating System: Windows and Mac
* Browser (if using Office on the web): NA
 
## Expected behavior
I just wonder how could I avoid my HTML be 'optimized' after click 'send' button.
I tried set some dirty data like '&nbsp;', actually it works. But it will generate a new line. 
And if I don't know the optimize rule the risk is not under control. 
And if Microsoft can fix this recently will be best.

## Current behavior
The HTML inserted in the front will be optimized away.

## Steps to reproduce

1. open windows outlook, then open add-in
2. get html body with `Office.context.mailbox.item.body.getAsync("html", {coercionType: Office.CoercionType.Html}, function (result) {
                    htmlBody = result.value;
                });`
3.  htmlBody = '<a name="test"></a><html .....some html code..... <\html>' + htmlBody;
4. Then set htmlBody to body, using api 'Office.context.mailbox.item.body.setAsync'.
5. send this email to others
6. open this event again, will see '<a name="test"></a>' disappeared

## Context

My html body will loss some code and some times the starting html is very important.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
We are able to reproduce the issue on Outlook Windows Client, and the issue has been brought to their notice. 
We are not able to reproduce the bug for Outlook Mac Client. 

Please answer the below questions to help us understand the situation better 
- Is it happening for Mac Old UI or New UI or both ?
- Does it happen always for you ?
- Can you help us with a sample snippet which you tried on Mac ?

**Comment by exextoc** [comment]
On Windows, this is found to be by design. Windows uses Microsoft Word as an HTML render/composer when sending emails, so HTML is sent to Word, and then sent out. Unfortunately, there is no concrete guide as to what the Word Render/Composer supports. You can try looking this up for other sources about this: https://www.google.com/search?q=Word+Outlook+HTML+engine

**Comment by SWei1234** [comment]
Hi @exextoc 
1. Is it happening for Mac Old UI or New UI or both ?
I only tried this on Mac Old UI. 
2. Does it happen always for you ?
Yes, This always happen.
3. Can you help us with a sample snippet which you tried on Mac ?
A little detail about replicate. I schedule meeting on Mac but I open this meeting on Windows Outlook.
Hope this will be helpful.
Thanks

**Comment by SWei1234** [comment]
Hi @exextoc 
I see you said this is by design: 'On Windows, this is found to be by design. ' 
If so what is the design if user using 'Office.context.mailbox.item.body.setAsync' api set some html to body?
Obviously some html on header will be optimized. Is there a way to avoid this problem?
Or this is a known bug? 
Thanks

**Comment by exextoc** [comment]
This is not a bug.
It is a behavior of the client where it may modify the value passed to `setAsync` in order to make it render efficiently with its rendering engine. We have this documented here : https://docs.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-preview#setAsync_data__options__callback_
There's no way to circumvent this behavior of the client.
