### ISSUE TITLE
Can't see Attach Debugger in taskpanel

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#1963]
# Provide required information needed to triage your issue

When click top right corner of taskpanel，there is no “Attach Debugger”！
![1](https://user-images.githubusercontent.com/3182964/123755823-e2928000-d8ee-11eb-8171-e8ff7970fd4b.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___PC___
* Host [Excel, Word, PowerPoint, etc.]: __Excel、Word____
* Office version number: ____Microsoft® Excel® 2016 MSO (16.0.14026.20304) 32 位__
* Operating System: __Windows 10____
* Browser (if using Office on the web): __IE 19041.1052____
 
## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by lindalu-MSFT** [comment]
@AlexJerabek Do you know who I should assign this issue to? There's no SME listed for Script Lab.

**Comment by lindalu-MSFT** [comment]
Hi @darrelmiller Is this a DevX issue? If so, can you please help us triage and move this issue to the correct repo? Thanks in advance, Linda

**Comment by ElizabethSamuel-MSFT** [comment]
@lindalu-MSFT I don't this darrelmiller is on OP. Reassigning to millerds.

@millerds Can you help with this?

@hengchengfei Are you still able to repro this?

Thanks.

**Comment by millerds** [comment]
That menu is part of the add-ins framework (someone on OPC) and not dev tooling.  I'm not sure what triggers it.

**Comment by ElizabethSamuel-MSFT** [comment]
@millerds Thanks for your response.

@jargil Any idea who might be able to help look into this?

Thanks.

**Comment by jargil** [comment]
This is the expected behavior if you're running with Edge's Legacy control.

This is how you debug with Edge legacy: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-devtools-edge-legacy

This is the list of runtimes Office supports: https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins
