### ISSUE TITLE
Excel Add in is making cors error when requesting data from spring boot server even after configured shared runtime

### ISSUE THREAD

**Issue by amanraihot** [OfficeDev/office-js#1964]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: _Mac_____
* Host [Excel, Word, PowerPoint, etc.]: _____Excel_
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web):Chrome ______
 
## Expected behavior

I want do a rest call to server after fetching the data from the sheet using fetch api
## Current behavior
I wanted to make a post request to the spring boot server hosted on port 8080 I have even enabled cross-origin requests there but when I send this post request from my task pane it shows the request blocked due to security checks I am stuck in this for few days 

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by keyur32** [comment]
Thanks for your question (and sorry for the overdue response as this fell through the cracks), however this forum is for issues with our product or documentation, not for programming questions about your code. We suggest you go to [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/office-js-dev.html) <change tag if appropriate> and see if your question has already been asked or ask a new question. Thanks, Microsoft 365 Developer Platform team
