### ISSUE TITLE
Outlook meeting provider add-ins can not show error notifications on Android

### ISSUE THREAD

**Issue by markdon** [OfficeDev/office-js#1966]
Following this example: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting
If the function that adds the meeting to the event attempts to display an error notification with `Office.context.mailbox.item.notificationMessages.addAsync`, no notification appears.

## Your Environment

* Platform Android
* Host Outlook
* Office version number: 4.2123.2
 
## Expected behavior
Error notification appears at top of New Event form.

## Current behavior
No error message is shown.

## Steps to reproduce
1. Sideload my example: https://markdon.github.io/outlook-meeting/manifest.xml
1. Create new event on Android
1. Enable online meeting from 'Online Meeting Sample' provider.

## Link to live example(s)
Manifest: https://markdon.github.io/outlook-meeting/manifest.xml
Repository: https://github.com/markdon/outlook-meeting

# Provide additional details
The same code successfully produces an error message in the web client.

## Context
We'd like to create meeting rooms based on the event name and prompt the user to enter an event name before adding an online meeting.

**Comment by markdon** [comment]
It took me far too long to properly read and pay attention to this section: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting#available-apis

It looks like no APIs outside that list are available in this context...

Seems like some good functionality to make available. In addition to the way I want to use notification messages above, sometimes errors happen. I'm not sure that only reverting the toggle to off is as good of an experience for the user as a notification message would be.

**Comment by exextoc** [comment]
Currently error notification APIs, you requested, are not a part of the mobile add-ins dealing with online meeting . We track Outlook add-in feature requests on our Tech Community Page. Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by markdon** [comment]
[Done](https://techcommunity.microsoft.com/t5/outlook/add-support-for-notifications-api-for-online-meeting-provider/m-p/2514735#M7558)
