### ISSUE TITLE
Inline attached images in signatures are not visible after receiving mails

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#1967]
# Provide required information needed to triage your issue
We are adding inline image attachments using addFileAttachmentFromBase64Async method. Then we set a signature referencing the image attachment  with src="cid:filename" . The images are displayed while composing but are not displayed after receiving the mail.

## Your Environment
* Platform : Office on the web
* Host : Outlook
* Operating System: Windows
* Browser: Chrome / Edge
 
## Expected behavior
An inlined image within the signature should be visible when receiving mails.

## Current behavior
Inline images in signature are not visible to receipients when the emails are composed on some user accounts.
We noticed a difference behavior when setting signature between the user accounts:
- On Mail Accounts which receiving of the image within the signature works, the images are referenced via url https://attachments.office.net when setting the signature.
- On Mail Accounts with problems the images are referenced with blob://... and an error is displayed in the browser console.

## Steps to reproduce
1. Install Script Lab for Outlook
2. Open Sample "Work with client signatures (Compose)"
3. Click on setSignature with inline Image
4. Send the mail to yourself
5. Observe that the inline image is not displayed

## Context
We have an addin which sets signatures. Currently our customers are not able to set inline images in signatures.

## Not Working Example:
Inline image url goes to blob://...
![Attachment Bug](https://user-images.githubusercontent.com/6338132/123935263-59358900-d994-11eb-849b-14af0a3b8b20.gif)
Error on Console
<img width="460" alt="CORS Error Attachment" src="https://user-images.githubusercontent.com/6338132/123935663-b6313f00-d994-11eb-9a10-488675eaa807.png">
Showing placeholder image after sending
<img width="680" alt="After Sending Attachment" src="https://user-images.githubusercontent.com/6338132/123937222-3c9a5080-d996-11eb-9156-c18e3560e6f4.png">

## Working Example:
Inline image url goes to https://attachments.office.net and no CORS error on console
![Working Attachment](https://user-images.githubusercontent.com/6338132/123940280-4bcecd80-d999-11eb-8dfb-05a4c9d5b5f6.gif)

## Related issues
#1439

**Comment by exextoc** [comment]
The issue is reproducible for us. We acknowledge the issue and are working towards a fix.

**Comment by exextoc** [comment]
The issue is fixed. 
Please let us know if you still see the issue happening.

**Comment by barisbikmaz** [comment]
@exextoc Great its working now. Thanks for the fast fix.
