### ISSUE TITLE
[IE11] Unable to upload test manifest

### ISSUE THREAD

**Issue by kullachoke-bosuwan-rft** [OfficeDev/office-js#1968]
We're trying to upload test manifest on IE11 but freeze at blank dialog after clicked on Office Add-ins button

* Platform: web
* Host: Excel
* Operating System: Windows
* Browser: IE11
 
## Expected behavior
Office Add-ins button should open a dialog that allow user to upload test manifest.

## Current behavior
Got blank dialog after clicked on Office Add-ins button.

## Steps to reproduce
1. Go to `insert` tab
2. click Office Add-ins button

![MicrosoftTeams-image (30)](https://user-images.githubusercontent.com/64405659/123964102-50b57080-d9dd-11eb-8434-c2093eb92ac2.png)

**Comment by sshukurov** [comment]
I am experiencing the same problem. I get a warning in the console when I click `Office Add-ins` button:
![image](https://user-images.githubusercontent.com/36232686/127899083-eb5c9acc-c182-4994-8976-5fb20ecc9454.png)

I tried playing around with IE11 security settings and  turning off SmartScreen - it doesn't help.

**Comment by sshukurov** [comment]
Verified just now, the issue got resolved for me - I am able to upload the manifest in IE11.

Thank you!

**Comment by kullachoke-bosuwan-rft** [comment]
I've checked and confirmed that the issue has been resolved.
