### ISSUE TITLE
Potential bug with DialogAPI in Word on macOS - window object not removed

### ISSUE THREAD

**Issue by ajmccann11t** [OfficeDev/office-js#197]
Initiating a dialogAPI window, on macOS, for the SECOND time throws an error and the window does not open. Same code running on Word online and Word on Windows operates as expected.

## Expected Behavior

1. Open a dialog window using the dialogAPI (clicking a button in the taskpane). Window opens.
2. Click to close the new window.
3. Click on the button that triggers the opening of the dialog window again - window opens.

## Current Behavior
On macOS running Word 2016 on Office Insider Slow running Word for Mac Version 116.13.1 (180523):
1. Open a dialog window using the dialogAPI (clicking a button in the taskpane). Window opens.
2. Click to close the new window.
3. Click on the button that triggers the opening of the dialog window again - window does not open and following error in console:

> TypeError: undefined is not an object (evaluating 'dialog.addEventHandler')

Refreshing the taskpane resets everything and the dialog window will open one time.

## Steps to Reproduce, or Live Example
Code used to open:
```
dialogUrl = dialogUrl + 'qLTI.html';

Office.context.ui.displayDialogAsync(dialogUrl, {height: 90, width: 70},
  function (asyncResult) {
    dialog = asyncResult.value;
      dialog.addEventHandler(Office.EventType.DialogMessageReceived, processMessage);
  }
);
```
On macOS running Word 2016:
Install my app, Q for Success, then click **Login**, **Pick Your School** then **Ashford University**. You should get a dialog...close it. Try and choose Ashford again.

## Context
Users will assume my solution is broken. For instance, if I'm using dialogAPI for an auth flow and the user inadvertently closes the window they cannot reopen.

## Your Environment

* macOS 10.13.4
* Word for Mac Version 116.13.1 (180523)

**Comment by codexeon** [comment]
This was fixed in the June release for Mac (18061302). Can you update to the latest version and try the same code.

**Comment by JuaneloJuanelo** [comment]
@jimcaven  can you please update and try it and let us know if it works for you. Will mark the issue as resolved and awaiting validation.

**Comment by ajmccann11t** [comment]
I updated Office and the issue is resolved. Thank you - although this issue was particularly destructive for me because I develop mostly on Mac...and thought my code was broken.

Where could I have found documentation that this was an issue you were working on (or at least aware of)?

**Comment by JuaneloJuanelo** [comment]
closing issue as its fixed ! :)
