### ISSUE TITLE
[Excel addin] - When providing custom totals values, cell formatting is not applied

### ISSUE THREAD

**Issue by swiecaJS** [OfficeDev/office-js#1970]
~~I want to apply the same formatting to table totals as to the whole column above.
Unfortunately, even though I can see when I inspect total cell formatting, that indeed formatting is the same as cells above, it is not applied~~

I want to apply custom formatting to the last row of the table. This row is a "totals" row. Unfortunately this formatting is ignored by the excel.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office web 
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: web
* Operating System: mac os 10.15.7
* Browser (if using Office on the web): latest chrome
 
## Expected behavior
I would like table total cells to respect programmatically applied formatting

## Steps to reproduce

Please refer to my script-lab gist

But the core problem is here:
```
    const currencyFormatting = "$ #,##0.00;[Red]-$ #,##0.00";

    const table = ctx.workbook.worksheets.getActiveWorksheet().tables.getItem(tableId);

    table.showTotals = true;

    const totalRange = table.getTotalRowRange();

    totalRange.set({
      values: [[1, 2, 3, 4, 5]]
    });

    totalRange.set({
      format: {
        fill: { color: "#4472c4" },
        font: { color: "#FFFFFF", bold: true }
      },
      numberFormat: [
        [currencyFormatting, currencyFormatting, currencyFormatting, currencyFormatting, currencyFormatting]
      ]
    });

  await ctx.sync();
```

If I set vales of totals row + apply formatting later it is not respected

## Link to live example(s)

https://gist.github.com/swiecaJS/3ae89f0a892a461ccb0b24572b5c20c8

## Context

Because I am receiving custom totals from an API I need to inject them into the table.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by qinliuMSFT** [comment]
Hi swiecaJS,

Thank you for logging this issue. Are you asking the total row could apply the same numberFormat as the cells above? 

I inspected the numberFormat of used range in the sheet, and got the following information. It seems the data you added in Setup() is in a "General" numberFormat. And the total row applied the currencyFormatting you set.

![image](https://user-images.githubusercontent.com/73509856/124215604-f6282b80-db26-11eb-98e9-40d4025b6637.png)

I'm not sure if I fully understand your scenario, could you please give me more details?

**Comment by swiecaJS** [comment]
Hi @qinliuMSFT 
Sorry in the example provided I applied formatting just to the totals row.

For now, let's ignore that. The main problem is that the totals row formatting is not applied at all.
What is interesting - when you double click on the total row cell - formatting is applied afterward

**Comment by swiecaJS** [comment]
Please take a look at the video - you can see the problem there

https://user-images.githubusercontent.com/12431424/124239020-8f504580-db19-11eb-95cc-7cf40e3be826.mp4

**Comment by swiecaJS** [comment]
What is even more interesting, when you call the same function twice, the formatting is applied correctly. You can try it in another gist. I think this might be a workaround for me until this issue is resolved. 

https://gist.github.com/swiecaJS/0d2d19c36e91e2b78a9bd01391673dc4

**Comment by qinliuMSFT** [comment]
The issue is reproducible from my side. it has been put on our backlog VSO#5243905, will let you know once we have any updates.  Great to know that you have figured a workaround to unblock you.

**Comment by qinliuMSFT** [comment]
Hi @swiecaJS, After investigation, our team has decided to not fix this issue as this is aligning the same behavior as UI. For the table's total row range, we should first set the number format and then assign the values. 

We recommend you the following workaround:
  1. Firstly assigns numberFormat to table.totalRowRange
  2. Then assigns values, the numberFormat is applied.

**Comment by swiecaJS** [comment]
Hi @qinliuMSFT thanks for the recommended workaround. Together with my workaround, I feel like this problem can be resolved if someones encounter it the future

However, I tend to disagree that this is the same behaviour as UI. If you create a table manually, add totals row, and then change formatting it will be applied. I don't think that we can really compare programmatically creating a table vs creating a table by clicking.

For me this shows that the function `set({numberFormat: ''})` is not deterministic. It may or may not apply formatting depending on when I call it to programmatically create a table.

But if you do not want to fix it we can close the case I guess
