### ISSUE TITLE
On appearance change, content controls duplication

### ISSUE THREAD

**Issue by benjamin-almarza** [OfficeDev/office-js#1974]
After we change the content controls' appearance we refresh the page (ctrl+F5) and all of them get duplicated

Document before:
![document-before](https://user-images.githubusercontent.com/51302934/124548938-cb650c80-de71-11eb-9d8f-7c6b885b21c2.png)

Document After:
![document-after](https://user-images.githubusercontent.com/51302934/124548819-98227d80-de71-11eb-9d3a-e71999c7f234.png  )

## Our Environment
This problem only happens in web Office, not in desktop
And I can reproduce it in at least these browsers: 

* Chrome Version 91.0.4472.124 (Official Build) (64-bit)
* Firefox 88.0.1 (64-bit)  (It happens after refreshing twice)

## Expected behavior

All the content control should have the boundingBox appearance and should only appear once.

## Current behavior

It seems that each content control appears twice.

## Steps to reproduce

1.- Upload Basic_Agreement.docx to office.com
[Basic_Agreement.docx](https://github.com/OfficeDev/office-js/files/6767607/Basic_Agreement.docx)

2.- Run the following code in an office addin 

```javascript
function showHideContentControl(isContentControl) {
  const hidden = Word.ContentControlAppearance.hidden;
  const boundingBox= Word.ContentControlAppearance.boundingBox;
  return Word.run(async context => {
    const allContentControls = context.document.contentControls;
    context.load(allContentControls);

    await context.sync();

    allContentControls.items
      .filter(item => !item.isNullObject)
      .forEach(item => {

        if (isContentControl) {
          item.appearance = boundingBox;
        } else {
          item.appearance = hidden;
        }
      });
  });
}

showHideContentControl(true);
```

## Context

This issue affects us because it ruins the document for all practical use cases. We discourage our clients to use our office addin on the web.

**Comment by qinliuMSFT** [comment]
Thanks for bringing this to our attention. The issue is reproducible from my side. it has been put on our backlog VSO#5249602, will let you know once we have any updates.

**Comment by qinliuMSFT** [comment]
Hi @benjamin-almarza , we have fixed this issue, please have a try to ensure it's no longer repro from your side.

**Comment by benjamin-almarza** [comment]
Thanks, it is working fine now :)
