### ISSUE TITLE
Custom Functions with StreamingInvocation show #BUSY! indefinitely.

### ISSUE THREAD

**Issue by thanakrid-kunghair-rft** [OfficeDev/office-js#1975]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
setResult() in StreamingInvocation seems to not working correctly. After the function is called, there are no errors, but custom functions still show #BUSY! even after the function is executed.
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: MacOS
* Browser (if using Office on the web): Chrome
 
## Expected behavior

Custom functions should show input of setResult() in Excel cell.
## Current behavior
Custom functions show #BUSY! after setResult() is called.

## Steps to reproduce

1. clone this project: https://github.com/thanakrid-kunghair-rft/test-add-in
2. install, build, and upload the manifest
3. use any streaming functions in the project, ie., =CONTOSO.INCREMENT(1).

## Link to live example(s)

1. https://github.com/thanakrid-kunghair-rft/test-add-in
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

Streaming function can't show data if setResults() is somehow not working.
## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
![image](https://user-images.githubusercontent.com/73512008/124722487-4e4e9b80-df34-11eb-9bfc-e60cd7c237c1.png)

I logged a value from =CONTOSO.INCREMENT(). As you can see in the gif file, the value keeps incrementing, but the function still shows `#BUSY!`.
![setResults-issue](https://user-images.githubusercontent.com/73512008/124728245-a1771d00-df39-11eb-996e-5340ef1fe86f.gif)

**Comment by wynntee** [comment]
I'm facing the same issue, even for synchronous functions. It happens only for Excel Online.  Everything is ok for Excel desktop.

I noticed it only yesterday (6th July 2021). The functions were working at least on 4th July, so something must have changed in between.

I've even sideloaded a test add-in (empty task pane and only one synchronous custom function). The cell shows #BUSY!.

**Comment by sshukurov** [comment]
The same with me, custom functions get stuck at #BUSY!. I tried samples from MS, tried on different browsers, tried clearing caches, it simply doesn't help. This is very frustrating.

**Comment by qinliuMSFT** [comment]
Hi @sshukurov @wynntee @thanakrid-kunghair-rft , 
Could you please share your Office Online version?  (From File->About)
In addition, could you please also try the following sample in Script Lab?
![image](https://user-images.githubusercontent.com/73509856/124746239-3afef880-df53-11eb-97f4-f9938601b4f6.png)

**Comment by wynntee** [comment]
@qinliuMSFT , there is no such thing as an Office Online version. It's always going to be the latest version, isn't it?  I've tested on Chrome, Edge, and Firefox. All return the same "#BUSY!" message. The browsers' developer's consoles show all kinds of warnings and errors coming from Microsoft's code. The errors were different yesterday compared to today, so Microsoft must have been making some changes in the last 24 hours.

My Office Add-in doesn't use streaming functions. Mostly simple straightforward synchronous functions. For example, simple arithmetic operations. Even those functions return "#BUSY!".

For your information, my Add-in was recently validated by Microsoft AppSource (less than 2 weeks ago), so it has nothing to do with my code. Furthermore, my Add-in works perfectly fine on Excel desktop, using both IE11 and WebView2 runtimes.

**Comment by sshukurov** [comment]
@qinliuMSFT I see version indicated as 16.0.14302.35050 (File > About). A colleague of mine has the same version, he hasn't had any issues. Moreover, I tried Script Lab sample, it worked. After that all other custom functions miraculously started working!

UPD. I rushed. The problem returned.

**Comment by thanakrid-kunghair-rft** [comment]
@qinliuMSFT My version is 16.0.14302.35050, but custom functions still show #BUSY!

**Comment by wynntee** [comment]
@qinliuMSFT 16.0.14302.35050  like the others. It's always going to be the latest.

**Comment by qinliuMSFT** [comment]
Thanks all for your quick response. This issue is reproducible from our side and is under investigation. Will will let you know once we have any updates.

**Comment by qinliuMSFT** [comment]
Hi @sshukurov @wynntee @thanakrid-kunghair-rft ,
We have fixed this issue, please have a try to ensure it's no longer repro from your side.

**Comment by wynntee** [comment]
@qinliuMSFT , thank you for the quick response. The issue is fixed for *sideloaded* add-ins. But it's still happening on my *published* add-in. In fact, it says "This add-in is not supported in this version of Office."... but that's impossible because it passed Microsoft AppSource validation 2 weeks ago and I haven't changed the manifest.

**Comment by wynntee** [comment]
Not sure if it helps, but developer's console in Chrome shows HTTP error 503 from the following endpoint:
https://excel.officeapps.live.com/x/_layouts/RoamingAppsHandler.ashx

**Comment by qinliuMSFT** [comment]
Hi @wynntee , could you please open a new issue for OfficeDev/office-js to explain your problem more specifically? a snapshot or something like that would be helpful. In this issue, we would like to only discuss "Custom Functions with StreamingInvocation show #BUSY! indefinitely".

**Comment by thanakrid-kunghair-rft** [comment]
@qinliuMSFT Custom functions are able to resolve, but the behaviour of streaming functions are a bit off.
Previously, this function will update its value every second, but, from the gif, there seems to be some slight delay as it skip some values.
![setResults-issue-delay](https://user-images.githubusercontent.com/73512008/124856893-8c4fcc00-dfd5-11eb-8bfe-2ec582b9b94c.gif)

**Comment by wynntee** [comment]
@qinliuMSFT , I've opened a new issue as advised.
#1979
