### ISSUE TITLE
Outlook IOS and Android Add-in not support promt dialog for Http 401 Unauthorized

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#1976]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

when i try to go to http 401 unauthorized site on our add-in. like this site: https://httpstat.us/401
the IOS and Android Outlook will failed. it can't promt the auth dialog.

**Comment by exextoc** [comment]
@hello-chenchen  Could you please provide more details such as repro steps and code snippet?

**Comment by hello-chenchen** [comment]
hi @exextoc , just use Office.context.ui.displayDialogAsync to popup a dialog on android or ios. then location.href to https://httpstat.us/401.

code snippet like:
```
var displayUrl = 'https://www.google.com';
Office.context.ui.displayDialogAsync(displayUrl, { height: 75, width: 40 }, function(result) {
    console.log('displayDialogAsync: ' + JSON.stringify(result.value));
});
```
![Screenshot2021_07_09_133454](https://user-images.githubusercontent.com/1878089/125028827-42d9ac80-e0bb-11eb-90d0-17dd75301ef4.jpg)
then:
```
location.href = 'https://httpstat.us/401'
```
![Screenshot2021_07_09_133506](https://user-images.githubusercontent.com/1878089/125028837-466d3380-e0bb-11eb-92e3-8d9cdb1481a6.jpg)

in the mac outlook, when try these code snippet on mac outlook, it can show the promt auth dialog.
![Screenshot2021_07_09_134600](https://user-images.githubusercontent.com/1878089/125029391-22f6b880-e0bc-11eb-95e4-3d5f9c7fe02d.jpg)

infact, this problem is really like this one: https://github.com/OfficeDev/office-js/issues/1592
for this issue https://github.com/OfficeDev/office-js/issues/1592, the root cause is can't promt certification dialog.

and for current issue, the root cause is can't promt auth dialog.

**Comment by exextoc** [comment]
Thanks for reporting this issue . It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
> hi @exextoc , just use Office.context.ui.displayDialogAsync to popup a dialog on android or ios. then location.href to https://httpstat.us/401.
> 
> code snippet like:
> 
> ```
> var displayUrl = 'https://www.google.com';
> Office.context.ui.displayDialogAsync(displayUrl, { height: 75, width: 40 }, function(result) {
>     console.log('displayDialogAsync: ' + JSON.stringify(result.value));
> });
> ```
> 
> ![Screenshot2021_07_09_133454](https://user-images.githubusercontent.com/1878089/125028827-42d9ac80-e0bb-11eb-90d0-17dd75301ef4.jpg)
> then:
> 
> ```
> location.href = 'https://httpstat.us/401'
> ```
> 
> ![Screenshot2021_07_09_133506](https://user-images.githubusercontent.com/1878089/125028837-466d3380-e0bb-11eb-92e3-8d9cdb1481a6.jpg)
> 
> in the mac outlook, when try these code snippet on mac outlook, it can show the promt auth dialog.
> ![Screenshot2021_07_09_134600](https://user-images.githubusercontent.com/1878089/125029391-22f6b880-e0bc-11eb-95e4-3d5f9c7fe02d.jpg)
> 
> infact, this problem is really like this one: #1592
> for this issue #1592, the root cause is can't promt certification dialog.
> 
> and for current issue, the root cause is can't promt auth dialog.

Hello, can you please confirm if you are on the same domain as https://httpstat.us/401 ?

**Comment by hello-chenchen** [comment]
hi @exextoc , sorry i don't understand clearly for what you mean.
in fact, in my manifest, the https://httpstat.us domain is not in my manifest file.
but i think it is the right way to not add the https://httpstat.us to the manifest. Because in my opinion, this situation is offen happened on sso login case.

**Comment by exextoc** [comment]
Hey @exextoc , We meant that all URLs that are being accessed must be a part of the AppDomains list in the manifest. Can you try adding the URL to the AppDomains list and see that the issue still reproduces?

**Comment by hello-chenchen** [comment]
hi @exextoc , i will not add the url to the AppDomains list in the manifest. Cause it is not an undesirable solution.
As i mentioned above, when users try to log in by SSO and redirect to their own company's domain, we cannot stop it and must redirect, which is necessary for SSO login. It is impossible for us to add all the doamins of companies that require SSO login to AppDomains.

**Comment by exextoc** [comment]
@hello-chenchen You do not need to add the redirection URL in AppDomains if you are using location.href on the pop-up window. Hence, the behavior in mac is correct.
