### ISSUE TITLE
Office.context.mailbox.item.recurrence.SeriesTime end values are zero if recurrence started in the past

### ISSUE THREAD

**Issue by thoffmann-fms** [OfficeDev/office-js#1978]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC 
* Host [Excel, Word, PowerPoint, etc.]: Outlook / OWA
* Office version number: x-owa-version: 15.20.4287.33
* Operating System: Win 10
* Browser (if using Office on the web): Edge
 
## Expected behavior

Office.context.mailbox.item.recurrence.SeriesTime should have non-zero values for end year/month/day
`{"recurrenceType":"daily","recurrenceTimeZone":{"name":"Eastern Standard Time","offset":-240},"recurrenceProperties":{"interval":1},"seriesTime":{"startYear":2021,"startMonth":7,"startDay":5,"endYear":2021,"endMonth":7,"endDay":9,"startTimeMinutes":660,"durationMinutes":30}}`
This is working correctly in Windows and Mac Outlook clients.

## Current behavior

If the series started in the past the end values are reported as zero.
`{"recurrenceProperties":{"interval":1},"recurrenceType":"daily","recurrenceTimeZone":{"name":"Eastern Standard Time","offset":-240},"seriesTime":{"startYear":2021,"startMonth":7,"startDay":5,"endYear":0,"endMonth":0,"endDay":0,"startTimeMinutes":660,"durationMinutes":30}}`
## Steps to reproduce

Create a recurring event.  e.g. Daily for 5 days. Save the event. Edit the series and issue a getAsync() against Office.context.mailbox.item.recurrence and the end values should be as expected.  Come back tomorrow and issue the same getAsync() and the end values are zero.
Happens for "Edit This", "Edit All Events", and "Edit all following"

## Link to live example(s)
n/a

# Provide additional details
```
      if (typeof Office.context.mailbox.item.recurrence.getAsync === "undefined") {
        recurrence = Office.context.mailbox.item.recurrence;
      } else {
        recurrence = await GetOutlookStructureAsync("recurrence", Office.context.mailbox.item.recurrence);
        if (recurrence === null) {
          // No recurrence
          resolve();
          return;
        }
      }
```

```
export const GetOutlookStructureAsync = (func: string, evt: any): Promise<any> => {
  const who: string = "GetOutlookStructure " + func;
  return new Promise<any>((resolve, reject) => {
    try {
      DebugLog(who, "Start");
      evt.getAsync((asyncResult: Office.AsyncResult<any>) => {
        if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
          DebugLog(who, JSON.stringify(asyncResult.value));
          resolve(asyncResult.value);
        } else {
          const errorText: string = asyncResult.error.message;
          DebugLogError(who, errorText);
          reject(new Error(errorText));
        }
      });
    } catch (e) {
      DebugLogError(who, "Catch " + e.message);
      reject(e);
    }
  });
};
```

## Context

Causes us unable to use office Add-Ins to edit parts of recurring event.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
We are not able to repro this issue from our side.  Is the recurrence being set using Add-in API recurrence.setAsync  or manually?

**Comment by thoffmann-fms** [comment]
The recurrence was set from OWA before the Add-In was started.

**Comment by exextoc** [comment]
We are still not able to reproduce this issue ,can you please share a test account where it reproduces?

**Comment by thoffmann-fms** [comment]
I can't repro either on newer events, just the one test series I had for the week of July 5th.  I have another test series created on July 12th and it is returning valid data.  Not sure what was happening in that one case.  Thanks for looking into it, though!
