### ISSUE TITLE
Excel Online: Add-in does not work when published, but works when sideloaded

### ISSUE THREAD

**Issue by wynntee** [OfficeDev/office-js#1979]
Excel Online shows a modal dialog with the title "Add-in Error" and message saying that my Office Add-in is not supported in this version of Office, even though it has already been validated by Microsoft AppSource less than 2 weeks ago and published to Office Store.

This happens only for Excel Online when published. Everything is ok when the manifest is sideloaded. Everything is also ok for Excel desktop.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.14302.35050
* Operating System: Windows
* Browser (if using Office on the web): Google Chrome, Microsoft Edge (Chromium), and Firefox
 
## Expected behavior
I expected my Office Add-in to load without the error dialog appearing. I should be able to open the task pane by clicking the Show Task Pane button. I should be able to invoke custom functions.

## Current behavior
The error dialog appears. Screenshot attached:

![image](https://user-images.githubusercontent.com/73103065/124857300-a346ec00-dfde-11eb-884b-6b28bd9df6f2.png)

But Excel Online still registers the custom functions (namespaced by QRS) and the Show Task Pane button (with my logo) still appears in the Home ribbon.

This happens only on Excel Online when published. The same Office Add-in works as expected in Excel for Windows (both IE11 and WebView2 runtimes). The same Office Add-in also works as expected in Excel Online if the manifest is *sideloaded*.

## Steps to reproduce
1. Open new Excel workbook from Office on the web.
2. Insert > Office Add-ins > Store.
3. Search for "QRS Toolbox".
4. Click Add.
5. Edited: Click Show Task Pane button on Home ribbon.
6. Edited: The error dialog will appear.

or

5B. Type the formula "=QRS.VAR.NORMAL(0.95)" into a cell.
6B. The cell will show "#BUSY!" and the error dialog will appear.

## Link to live example(s)

# Provide additional details

## Context
I cannot use my Add-in. Likewise my potential users cannot use it either. The Add-in was published only yesterday (7th July).

## Useful logs

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by wynntee** [comment]
To be clear, my Add-in is meant to be supported in Excel on the web. This was tested during development and validated during the AppSource approval process. And it still works when sideloaded manually.

Please see the following screenshots from Microsoft AppSource and Office Store.

![image](https://user-images.githubusercontent.com/73103065/124909367-f2137680-e01c-11eb-9882-9b30bca2ae92.png)

![image](https://user-images.githubusercontent.com/73103065/124909403-fb044800-e01c-11eb-88eb-97d6d9d3de95.png)

**Comment by Rick-Kirkham** [comment]
I can reproduce, but the error doesn't come when I click Add in the Office Store. It comes when I click the add-ins Show Task Pane button on the ribbon.

**Comment by wynntee** [comment]
@Rick-Kirkham , thank you for the response. I've updated the Steps to Reproduce section accordingly.

For what it's worth, my server logs show only 2 HTTP requests from Excel Online. One for the logo icon. Another for the JSON metadata file.

There are no HTTP requests for any of the other files listed in the manifest. Those files definitely exist (the add-in works on desktop and online if sideloaded).

The Add-in uses a shared JavaScript runtime.

**Comment by wynntee** [comment]
#1986 seems to have a similar issue. Looks like Excel on the web is displaying inconsistent behaviour when Add-ins are sideloaded vs deployed.

**Comment by wynntee** [comment]
Here's a screenshot of the error.

![if_published](https://user-images.githubusercontent.com/73103065/126160130-8f427742-9906-42f3-b180-14c7da468d1c.gif)

**Comment by wynntee** [comment]
Here's a screenshot of the add-in when I sideload the manifest manually. This shows the add-in works in Excel on the web, which contradicts the previous error message.

![if_sideloaded](https://user-images.githubusercontent.com/73103065/126159426-2b203fe4-e150-44aa-b671-ad4fdb107c56.gif)

**Comment by wynntee** [comment]
@Rick-Kirkham is someone looking into this issue? Still needs triage.

**Comment by AbidRahman-MSFT** [comment]
Seems like it could be a store validation issue? @JuaneloJuanelo can you help?

**Comment by JuaneloJuanelo** [comment]
@wynntee  when you sideload your manifest, what manifest are you using?

**Comment by keyur32** [comment]
Hi @wynntee, thanks for the details. We are investigating and will get back to you once we have more information.

**Comment by wynntee** [comment]
@JuaneloJuanelo , it's the same manifest I submitted to Microsoft AppSource.

**Comment by wynntee** [comment]
@keyur32 , please keep me updated soonest. I suspect Excel on the Web is wrongly throwing an error on one of the Requirement Sets listed in my manifest. See screenshot below. Maybe the validation of these Requirement Sets is inconsistent between add-ins from the Office Store vs those that are sideloaded?

![image](https://user-images.githubusercontent.com/73103065/127087871-2870dfb4-597e-447f-9eef-2e1550386a29.png)

**Comment by keyur32** [comment]
Hi there. Update: this is still under investigation but it appears the custom functions 1.3 requirement set check is not working as expected. Will revert back with more details as we have it.

Thank you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wynntee** [comment]
I opened this case separately in Microsoft Partner Center and it's finally been resolved after 1 month. The engineering team said it was a bug in Excel online. Closing this issue now.
