### ISSUE TITLE
Word Online Binding setDataAsync persisting old text data around when document is printed/downloaded.

### ISSUE THREAD

**Issue by kalvenschraut** [OfficeDev/office-js#1980]
We are experiencing an issue where an office binding attached to a content control area is keeping around the old text data added from setDataAsync when it is expected that the new text added would completely overwrite any old existing text. (note this extra text only appears when you try to print the document or download it) 

This is happening only on word online, I am personally using google chrome Version 91.0.4472.124 (Official Build) (64-bit)
word on windows behaves as expected.

From my testing I can't pinpoint exactly how to create a bad binding/content control that has this issue but it doesn't seem to be consistent. I have yet to recreate the issue on the document itself, what I ended up doing in a test case was downloading a document with 1 binding/content control created, and then reupload that very same document. On that reuploaded document I call the setDataAsync function via  a script labs I made and then the problem appears. Its possible a step was missed somewhere in between to recreate this problem as I tried to replicate and couldn't. 

Here is a screen capture of the problem I am trying to describe

![Script Labs test docx - Microsoft Word Online - Google Chrome 2021-07-09 14-32-29](https://user-images.githubusercontent.com/30308012/125128820-2f7f0f00-e0c4-11eb-9c9d-c72f7e914393.gif)
 
The document having issues

[Script Labs test.docx](https://github.com/OfficeDev/office-js/files/6793654/Script.Labs.test.docx)

Script lab git gist 

https://gist.github.com/kalvenschraut/e99757ae6fbadd498e10b361335ed4ba

A customer of mine originally ran into this issue trying to create one of our documents using a template generated by an add-in I developed. I isolated some of the code to the script labs to help determine the problem. Hopefully I can figure out how to go from creating the document and adding the binding to the end product of the document I uploaded to consistently recreate the issue as I believe the problem is likely somewhere in creating the binding/content control, but I figured I would upload my findings so far in hopes to get some more help in this issue.

**Comment by qinliuMSFT** [comment]
Hi @kalvenschraut , Could you still repro this issue? I tried the file and gist you provided, but could not repro this. Please help confirm that.

**Comment by kalvenschraut** [comment]
I am currently unable to, asking my project manager if they can confirm they are not seeing the issue anymore also.


 Was it possible a word online update went out since I posted the issue 6 days ago? Going attach the resulting file after the above screen cap just in case as the contents are different then what the screen cap shows. 

[Scripts Labs after replacement.docx](https://github.com/OfficeDev/office-js/files/6823986/Scripts.Labs.after.replacement.docx)

**Comment by kalvenschraut** [comment]
My product manager confirmed they are unable to reproduce on our internal documents also. Was some kind of update put out that would have fixed this issue already?

**Comment by qinliuMSFT** [comment]
We actually have deployed one update including the fix on content control this Tuesday. Great to know you are unblocked now.
