### ISSUE TITLE
How can I disable my addin for word online

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/office-js#1981]
As RichApi is only available on native word application. We want to disable our addin for Word Online
How can we do that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b7148f0-0384-00d9-16f4-99cdab9c8ecc
* Version Independent ID: 9a7623fd-dd24-267f-a17f-dfcbd496ee0e
* Content: [Specify Office hosts and API requirements - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements)
* Content Source: [docs/develop/specify-office-hosts-and-api-requirements.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/specify-office-hosts-and-api-requirements.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by xiruatms** [comment]
Thanks for reporting this. 

But I'm sorry that I can't repro the issue you reported. Can you share more information please? Are there any sample codes which can be shared? Which browser are you using? Can you share a screen recording of this issue? 

Those information will help us to continue further investigation.

**Comment by abdulkareemnalband** [comment]
@xiruatms  sorry for long delay
I completely forgot about this
here is gist to scriptlab 
https://gist.github.com/abdulkareemnalband/71774fa909fbafc3642095f06184ea50

**Comment by xiruatms** [comment]
@abdulkareemnalband , thank for replying.

I've taken a try, but it seems working properly as the attachment. Any more steps I need to take care?

https://user-images.githubusercontent.com/40648203/159455107-7cfe1f6f-aa19-4d27-9d13-47114a3bfa16.mp4
