### ISSUE TITLE
Custom Contextual tab - Execute Function- Office.context.ui.displayDialogAsync not launching dialog

### ISSUE THREAD

**Issue by jnSWPC** [OfficeDev/office-js#1982]
I have followed the documentation specified at https://docs.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs
While I can get taskpane to show, I am unable to launch a dialog from within a function in functionfile.js when I use executefunction. I see the button in the contextual tab, but on clicking do not see the dialog open. I am unable to figure out where the error is. Appreciate link to a sample code with such a usecase if it is possible.

**Comment by jnSWPC** [comment]
![image](https://user-images.githubusercontent.com/22331494/125466605-7856433d-9118-4302-a0ae-42ecb2f43f65.png)

**Comment by jnSWPC** [comment]
"It remains stuck at We're starting the add-ins runtime, just a moment" and remains stuck there

**Comment by jnSWPC** [comment]
The JSON BLOB is  

"actions": [
    {
      "id": "executeWriteData",
      "type": "ExecuteFunction",
          "functionName": "**funcName**"
    }
  ],
  "tabs": [
    {
      "id": "CtxTab1",
      "label": "Contoso Data",
      "groups": [
        {
          "id": "CustomGroup111",
          "label": "Insertion",
          "icon": [
            {
                "size": 32,
                "sourceLocation": "https://cdn.contoso.com/addins/datainsertion/Images/Group32x32.png"
            },
            {
                "size": 80,
                "sourceLocation": "https://cdn.contoso.com/addins/datainsertion/Images/Group80x80.png"
            }
          ],
          "controls": [
            {
                "type": "Button",
                "id": "CtxBt112",
                "actionId": "executeWriteData",
                "enabled": true,
                "label": "Write Data",
                "superTip": {
                    "title": "Data Insertion",
                    "description": "Use this button to insert data into the document."
                },
                "icon": [
                    {
                        "size": 32,
                        "sourceLocation": "https://cdn.contoso.com/addins/datainsertion/Images/WriteDataButton32x32.png"
                    },
                    {
                        "size": 80,
                        "sourceLocation": "https://cdn.contoso.com/addins/datainsertion/Images/WriteDataButton80x80.png"
                    }
                ]
            }
          ]
        }
      ]
    }
  ]

funcName is implemented in FunctionFile.html

**Comment by ElizabethSamuel-MSFT** [comment]
@jnSWPC Apologies for the late response. Are you still facing this issue?

@preethikakiru Can you take a look?

Thanks.
