### ISSUE TITLE
Streaming functions won't update value to the cells until double click at the formula's cell. 

### ISSUE THREAD

**Issue by thanakrid-kunghair-rft** [OfficeDev/office-js#1984]
# Provide required information needed to triage your issue
This behaviour is happening on some workbooks. I've tried using Document Inspector, but the issue is still persist.
I have streaming functions that use websocket as a datasource, and the functions will call setResult() to show a message like `Retrieving...` while waiting for data from websocket. However, data from websocket won't be shown even after setResult() is called with websocket's messages, but if I double click at the formula's cell the data will be shown immediately.

You can check this behaviour by using the function, `=CONTOSO.STREAMING("message")`, in my test project repository  and the excel file that I attach to this issue.
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: MacOs
* Browser (if using Office on the web): Chrome

-----------------------------
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows 10

![image](https://user-images.githubusercontent.com/73512008/125426156-0563c035-b8f1-4a1d-aead-3a024771c080.png)

 
## Expected behavior
Custom functions update values in its area after setResult() is called.

## Current behavior
Custom functions won't update values in its area after setResult() is called.

## Steps to reproduce

1. Clone the test-project: https://github.com/thanakrid-kunghair-rft/test-add-in on main branch
2. Open the excel file in this issue.
3. Open Developer tool console.
4. Use `=CONTOSO.STREAMING("A")`
5. After 30 seconds, you will notice a message `render` in the console, and the function's cell should still show `Retrieving...` without updating new values.
6. Try double clicking at the function's cell.

## Link to live example(s)

1. https://github.com/thanakrid-kunghair-rft/test-add-in

# Provide additional details

I use setTimeout to mimic this behaviour. Normally, it will have to wait for data from websocket, but, in essence, this issue will show when there's a gap(delay) between the first setResult() call and the following setResult() call.

## Context

Currently, the temporary solution is copying everything to a new workbook, but it won't be a good solution for the project's users.
## Useful logs

- [ ] Console errors
- [ x] Screenshots
![custom-function-not-update](https://user-images.githubusercontent.com/73512008/125428249-f3e3bf2c-fafc-4b1d-8004-f9c525838b51.gif)

- [ x] Test file (if only happens on a particular file)
[custom-function-not-update.xlsx](https://github.com/OfficeDev/office-js/files/6807699/custom-function-not-update.xlsx)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by thanakrid-kunghair-rft** [comment]
Hi
Any updates regarding this issue?

**Comment by grangeryy** [comment]
@xiaochunms could you help to take a look?

**Comment by grangeryy** [comment]
@thanakrid-kunghair-rft， after investigation, we notice you set the cell value in Excel.Run in one streaming function, which is hard to guarantee the update frequency. We also noticed there is another streaming function, which is the typical usage. Can you check if the second streaming function work as expected?

**Comment by thanakrid-kunghair-rft** [comment]
Hi @grangeryy I think the latest commit in main branch does not call the function with Excel.Run().

**Comment by thanakrid-kunghair-rft** [comment]
You'll have to use `=CONTOSO.STREAMING` that has setTimeout.

**Comment by grangeryy** [comment]
@thanakrid-kunghair-rft seems below part misuse the setResult:
![image](https://user-images.githubusercontent.com/50093161/127121654-3d3126a3-745d-47ae-aac0-2963884ac8e8.png). 
More details in [HERE](https://docs.microsoft.com/en-us/javascript/api/custom-functions-runtime/customfunctions.streaminginvocation?view=excel-js-preview)

**Comment by thanakrid-kunghair-rft** [comment]
By misuse, you mean it can't be used in timeout?

**Comment by grangeryy** [comment]
For the line: invocation.setResult(['Retrieving']), you've already showing the error information as the function result, which might be the reason why the function stop execution:
![image](https://user-images.githubusercontent.com/50093161/127806004-1cf2a92f-2e85-44ef-9c60-5ef7a4927dc9.png)
Have you tried to remove this line and see if it works?

**Comment by thanakrid-kunghair-rft** [comment]
Sorry, what do you mean about error information?
`[['Retrieving..']]` is just a normal dynamic array with a string in it.

**Comment by grangeryy** [comment]
So you are using this line to showing the string of "Retrieving..."?

**Comment by grangeryy** [comment]
Sorry, might missunderstand the issue. So after removing  Excel.Run, have you still see the issue?

**Comment by thanakrid-kunghair-rft** [comment]
Yes, the issue still persist, but `=CONTOSO.STREAMING` doesn't have a call to a function with Excel.Run().
In the real app, I show the string of `Retrieving...` first while waiting for the data from Websocket. I want to replicate a similar behavior, so I use timeout instead.

**Comment by grangeryy** [comment]
@xiaochunms, could you help to check whether Excel.Run() doesn't work in this case is expected?

**Comment by xiaochunms** [comment]
@thanakrid-kunghair-rft sorry to hear the issue. Please let me clone your examples locally and back to you with my findings then.

**Comment by xiaochunms** [comment]
@thanakrid-kunghair-rft I tried the same locally, however the value can be updated timely (Please see the screen recording attached. I changed the timeout value from 30s to 1s. I think it should still work as expected with time out value of 30s).

https://user-images.githubusercontent.com/1261601/128321036-cd297335-07a2-4bac-8b22-1243085e26b8.mp4

**Comment by thanakrid-kunghair-rft** [comment]
@xiaochunms This issue occurs on some workbooks. Not sure if you have a chance to run the test-add-in on the workbook that I attached yet.

**Comment by grangeryy** [comment]
BUG 5337749 is created to track this

**Comment by XuanZhouMSFT** [comment]
Thanks for reporting this issue. After careful consideration, our team has decided to not fix this issue in the short term. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.
