### ISSUE TITLE
WorkSheetCalculatedEvent leads to error in German environment

### ISSUE THREAD

**Issue by Alex0cean** [OfficeDev/office-js#1985]
Description:
When we try to get all affected ranges from a WorksheetCalculatedEvent we get an Excel API InvalidArgumentError in Excel Desktop (german culture).
 
How to reproduce:
Use WorksheetCalculatedEventArgs.address as input for Worksheet.getRanges(address) and trigger multiple formulas calculation (e.g. worksheet.calculate()).
This works well in Excel Online (Chrome) or English Culture but fails for Excel Desktop with German Culture.
 
Further investigation:
The reason seems to be that WorksheetCalculatedEventArgs.address uses always a comma to separate multiple ranges (e.g. “A1,B2”) while Worksheet.getRanges(address) expects a comma for Excel online or Excel Desktop (English) but a semicolon (“A1;B2”) for Excel Desktop (German).
 
The documentation says “comma”.
 
Expected behavior:
getRanges() should always expect multiple ranges separated by comma (e.g. “A1,B2”) in the address string.
Otherwise we would need to know where an address is culture specific and where it’s not and how to translate it.

**Comment by 2020Mar** [comment]
@Alex0cean Thanks for reporting and this is a known issue, our team has been working on fixing it. We will update the thread if any progress made. 
By the way could you help describe your scenario(what you want to achieve) in details then we can help provide some workarounds if possible. 
And are you contributing for add-in code or you only use add-in user to write your JS code? 
Thanks!

**Comment by Alex0cean** [comment]
@2020Mar , thanks for your answer. We are developing an add-in. Please check with @lumine2008 for more information. 
So you have an ETA for a fix? I.e. is it worthwhile thinking of a workaround or can we expect a fix rather soon?
(as a workaround we need to find out the culture and dividers and possibly replace them .. - but this seems to be ugly, maybe you have something else in mind)

**Comment by 2020Mar** [comment]
@Alex0cean It is supposted to release no sonner than September update. 
And for the workaround. I think there are two choices. 
The first one is detect the locale and use different list separators for different locales in code side. 
The other is for end users, they can change list separator to comma in win10 OS setting. Control panel->Change date, time, or number formats ->Formats tab Additional Settings. 
I think the first one is more suitable because the latter may bring other issues.

**Comment by shaowan-msft** [comment]
@Alex0cean This issue is fixed by our team and you can validate in latest Excel. The change is included in version 14430.20088 in my side. Thanks!

**Comment by gingerjia** [comment]
Close it as have verified the fix on PROD. If have any other issues, please feel free to let us know. Thanks!
