### ISSUE TITLE
Automatically open a task pane with a document, not working with centralised deployment [Web Excel]

### ISSUE THREAD

**Issue by swiecaJS** [OfficeDev/office-js#1986]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office Web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Web
* Operating System: macOS
* Browser (if using Office on the web): chrome
 
## Expected behavior & Current behavior
In the manifest, I added this config (following [the docs](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document))
I expect the app to open automatically taskpane when returning to the same worksheet. I verified that the flag is being set correctly. And the behavior is correct when sideloading addin. However, as soon as I use office centralized deployment I am losing this feature

## Steps to reproduce

Part of manifest.xml
```
          <Action xsi:type="ShowTaskpane">
                    <TaskpaneId>Office.AutoShowTaskpaneWithDocument</TaskpaneId>
                    <SourceLocation resid="Addin.Url"/>
          </Action>
```

part of index.js

```
Office.initialize = () => {
  Office.context.document.settings.set('Office.AutoShowTaskpaneWithDocument', true);
  Office.context.document.settings.saveAsync(() => {
    render(App);
  });
};
```

## Context
Because my addin creates and updates table it's much handier for the users to open it automatically if it was used before in the worksheet.

**Comment by wynntee** [comment]
@swiecaJS , I'm facing a similar issue for a published add-in. My server logs show that Excel isn't even requesting for the HTML/JS/CSS files. Do your server logs show the same?

**Comment by swiecaJS** [comment]
@wynntee I think your issue is a bit different. My addin works fine, it boots up no problem. What is not working is the feature to automatically open in when you are returning to the same worksheet.

**Comment by lliu113** [comment]
@swiecaJS - thanks for reporting this! This is a known issue, unfortunately we don't have an ETA to share at the moment but it is in our backlog. 
Internal bug #: 3546573

**Comment by kdmadej** [comment]
While I completely understand that fixing bugs takes time and resources that are not always available (other priorities, being short-staffed, you name it), I'd like to ask if there was a chance to update the [docs](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document) with a warning that there is a known issue? I.e. in the section about [testing and verifying opening task panes](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document#test-and-verify-opening-task-panes)?

Would've saved me a lot of time (and nerves 🙈) searching for the source of my issue 😅

**Comment by ElizabethSamuel-MSFT** [comment]
> While I completely understand that fixing bugs takes time and resources that are not always available (other priorities, being short-staffed, you name it), I'd like to ask if there was a chance to update the [docs](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document) with a warning that there is a known issue? I.e. in the section about [testing and verifying opening task panes](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document#test-and-verify-opening-task-panes)?
> 
> Would've saved me a lot of time (and nerves 🙈) searching for the source of my issue 😅

@Rick-Kirkham, is this something you can help document?

Thanks.

**Comment by alex-unicli** [comment]
Is there any plan to fix the issue? It makes the auto-open of add-in with a document unusable for add-ins installed by an organization.

**Comment by shermaro91** [comment]
I'm facing a similar issue. I have a file stored in OneDrive that I open using the Excel desktop app. I want my Office Add-in to automatically launch as soon as the document loads. I’ve embedded the web extension both via Open XML and using Office.js, following the guidance provided in this article:
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document?tabs=xmlmanifest

However, the behavior is inconsistent — sometimes the add-in loads automatically, and sometimes it doesn’t. In most cases it does, but not always. Is there any specific setting or configuration I need to apply to ensure the task pane always launches smoothly every time the document is opened?

Note : I have Desktop add-in
Build: Microsoft® Excel® for Microsoft 365 MSO (Version 2506 Build 16.0.18925.20076) 64-bit
