### ISSUE TITLE
OverriddenByRibbonApi element usage at tab level

### ISSUE THREAD

**Issue by jnSWPC** [OfficeDev/office-js#1987]
Followed document @ https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/overriddenbyribbonapi
Adding OverriddenByRibbonApi doesnt seem to work tab level. Group level seems to hide the button. Help with sample link of the feature implementation will be appreciated.

**Comment by jnSWPC** [comment]
Closing this.. i believe the controls have to be duplicated..

**Comment by davidchesnut** [comment]
Hi @jnSWPC,

Can you provide some additional details on how to reproduce this behavior? We need to know if this is happening on web, or desktop, and which version of Office you are using. Also if you have a small sample of the XML that causes the behavior that would be helpful.

Thanks!
David

**Comment by davidchesnut** [comment]
@sohailzafar can you help with this issue? Thanks!

**Comment by ElizabethSamuel-MSFT** [comment]
@jnSWPC Are you still facing this issue? If so, can you provide more details about your configuration as previously requested, e.g., Office version, platform?

@preethikakiru Can you help with this?

Thanks.
