### ISSUE TITLE
Excel Officejs Excel Run method is leaking memory when running in WebView2

### ISSUE THREAD

**Issue by chanhohang** [OfficeDev/office-js#1988]
I reproduce a memory leak issue similar to my add-in usage by a gist code.
https://gist.github.com/chanhohang/32c736bfd0de706644bf2f00a8afdcd1
Below is a screen capture from the Edge WebView 2 runtime memory to show the memory increase
![excel_run_memory](https://user-images.githubusercontent.com/4111001/125716507-d2ae5e0c-0319-4777-bc39-7ac293c1f5c1.gif)

My Add-in is much more complicated than the gist attached above and the memory usage can go up to 3gb and then crash after 15 to 30 mins.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **Desktop Excel Office 365**
![image](https://user-images.githubusercontent.com/4111001/125716645-7ad7ca1c-6c64-4d41-adfd-886e23fb1f7c.png)
* Host [Excel, Word, PowerPoint, etc.]: **Excel**
* Office version number: **2106 Build 14131.20278**
* Operating System: **Windows 10**
* Browser (if using Office on the web): **Webview 2 Edge Chronium**
 
## Expected behavior
The memory usage should not be going up consistently

## Current behavior
The memory usage is going up linearly and the heap dump shows a lot of string like the one below
`{"ActionId":10356,"Value":{"_ReferenceId":"R!{B0EA95B6-6B87-47F2-A83F-4273C1AAD5EE}!{969774EB-5BBA-4394-859B-3FDB4DCC66C7}"}},{"ActionId":10357,"Value":null},{"ActionId":10359,"Value":{"_ReferenceId":"R!{7C52A738-365E-4A08-85BA-2DB3CCC6FEF4}!{969774EB-5BBA-4394-859B-3FDB4DCC66C7}"}},{"ActionId":10360,"Value":null},{"ActionId":10361,"Value":{"_ReferenceId":"R!{7C52A738-365E-4A08-85BA-2DB3CCC6FEF4}!{969774EB-5BBA-4394-859B-3FDB4DCC66C7}"}},{"ActionId":10362,"Value":null},{"ActionId":10364,"Value":{"_ReferenceId":"R!{E9A2033D-F961-480F-AD96-0EDDD8EA959C}!{969774EB-5BBA-4394-859B-3FDB4DCC66C7}"}},{"ActionId":10365,"Value":null},{"ActionId":10366,"Value":{"_ReferenceId":"R!{E9A2033D-F961-480F-AD96-0EDDD8EA959C}!{969774EB-5BBA-4394-859B-3FDB4DCC66C7}"}},{"ActionId":10367,"Value":null},{"ActionId":10369,"Value":{"_ReferenceId":"R!{6CE39F83-C138-409B-9120-5943E48DD6E5}!{969774EB-5BBA-4394-859B-3FDB4DCC66C7}"}},{"ActionId":10370,"Value":null},{"ActionId":10371,"Value":{"_ReferenceId":"R!{6CE39F83-C138-409B-9120-5943E4"@36424961}`

## Steps to reproduce
- Load the gist into scriptlab https://gist.github.com/chanhohang/32c736bfd0de706644bf2f00a8afdcd1
- Select a number of cells and click the button Highlighted in the task pane
- wait 15-30 mins and monitor the memory usage.

## Link to live example(s)
N/A

# Provide additional details
I was reporting a similar problem in https://github.com/OfficeDev/office-js/issues/1054

## Context
My Add-in is processing frequent cell updates based on my Web Server into Excel cells, it requires to be running for 8 hours+.
Now the add-in will crash less than 30 mins and it's not usable for my clients in WebView2.
The same code is not causing out of memory issue in IE runtime.

## Useful logs
NA

**Comment by smaremanda** [comment]
thanks for reporting the issue @chanhohang. @Dengshan2018 - could you please help debug this issue?

**Comment by chanhohang** [comment]
@smaremanda thanks so much for the repsonse.

To add a bit more color to this issue. My finding so far from the WebView2 heapdump is that i can see a lot of callback window.agavehostcallback is registered in the native_context of windows and the string is within this callback.

I can see a similar issue is reported long time ago https://github.com/OfficeDev/office-js/issues/584.

Just my 2 cents, please feel free to start the investigation from scratch.

Thanks

**Comment by Dengshan2018** [comment]
Investigating.

**Comment by FTSupportsrl** [comment]
We're facing the same issue. The memory goes up consistently and gains in few hours the 4 GB limit. After that the Add in crashes. In a more memory poor environment the crash happens after 30/40 minutes.

**Comment by Dengshan2018** [comment]
@chanhohang @FTSupportsrl The fix is on the way. Please try latest version in Beta Channel or CC Channel later this week.
The fix will be available in Beta Channel(build14324) or CC (Build 14228.20200)
