### ISSUE TITLE
Ribbon button image is getting cut off

### ISSUE THREAD

**Issue by nkrtarm** [OfficeDev/office-js#1990]
We just got this issue this month. The button image is getting cut off. We can reproduce this on Chrome for Mac Version 91.0.4472.164 (Official Build) (x86_64)

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Mac Cartalina and BigSur
* Browser (if using Office on the web): Chrome Version 91.0.4472.164 (Official Build) (x86_64)
 
## Expected behavior
Image should not getting cut off

## Current behavior
<img width="586" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/7779734/125891826-ddd2a8d5-3915-4b0a-a809-40b6886c63fd.png">

## Steps to reproduce
1. Upload manifest and check on an image

**Comment by ElizabethSamuel-MSFT** [comment]
@nkrtarm Apologies for the late response. Are you still facing this issue?

@preethikakiru Can you take a look?

Thanks.
