### ISSUE TITLE
getAllInternetHeadersAsync not working in dialog window

### ISSUE THREAD

**Issue by David74000** [OfficeDev/office-js#1992]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Windows 10
* Browser (if using Office on the web): chrome and edge
 
## Expected behavior
the function getAllInternetHeadersAsync  should return a result object with a **statut** attribut equal to "success", and a **value** attribute equal to the Internet Headers. It works when I open the email in the same browser page.

## Current behavior
it does not work when the email in open in separate window (dialog) in O365 (Outlook web)

## Steps to reproduce
I am using the Script lab addin for test
1. From Outlook web, double click on an email item in order to open it in a new dialog window
2. Open any addin which use the getAllInternetHeadersAsync  (I use Script lab to simplify)

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding getAllInternetHeadersAsync. It has been put on our backlog. We unfortunately have no timelines to share at this point. 

Internal tracking id: 123235

**Comment by exextoc** [comment]
This issue has been fixed, please verify and confirm.
