### ISSUE TITLE
displayDialogAsync works unstable on add-in initialization

### ISSUE THREAD

**Issue by leybal** [OfficeDev/office-js#1993]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hello. I've downloaded and run the [excel-shared-runtime-scenario](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario) add-in sample. I had created a new workbook and then pressed Connect service button on the ribbon. Its always result in add-in initialization with a message in the consol "init globals for command buttons". But in some cases, the dialog box is not displayed. Please take a look at [the video](https://drive.google.com/file/d/1MCbIDeLUGTuJQdQDZDq5rfPMNHx4oqCn/view?usp=sharing).
Seems like unstable behavior. 
Summary: after creating new workbook and pressing Connect service button sometimes the dialog box has been displayed, and sometimes don't.

## Expected Behavior

After creating new workbook and pressing a button on the ribbon the add-in should initialize and the dialog box should be displayed every time.

## Current Behavior

After clicking the Connect service button on the ribbon, the dialog box sometimes the dialog box was displayed and sometimes not.

## Steps to Reproduce, or Live Example

1. Downloaded and run the [excel-shared-runtime-scenario](https://github.com/OfficeDev/PnP-OfficeAddins/tree/master/Samples/excel-shared-runtime-scenario) add-in sample.
2.  Created a new workbook and click Connect service button on the ribbon.
3. Is the dialog box has been displayed?
4. Please repeat step two 5 or 10 times. 

## Context

We creating the add-in for excel and user can initialize the add-in by pressing any button in our custom tab on the ribbon. On the add-in initialization we should set StartupBehavior to load and prepare content for the dialog box. But creating new workbook and pressing a button on the ribbon add-in the [error in the consol](https://drive.google.com/file/d/1oWmrsEec0ZToZfr3QYmEu1v98LNQXAig/view?usp=sharing) apear.

## Your Environment

* Platform: Office on the web
* Host: Excel
* Office version number: 16.0.13808.31877
* Operating System: Windows
* Browser: Google Chrome

**Comment by davidchesnut** [comment]
Transferring this issue to the office-js repo to track as a product bug. See ADO 5022839 for more tracking details.
