### ISSUE TITLE
getFileAsync PowerPoint add in always returning "internal error has occurred" 

### ISSUE THREAD

**Issue by nima-chatlani** [OfficeDev/office-js#1994]
# Provide required information needed to triage your issue

Following this tutorial (the example listed below "getFileAsync(fileType, options, callback)") exactly but each time I run sendFile() I get the error code 5001 and message "An internal error has occurred."

https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=excel-js-preview#getFileAsync_fileType__options__callback_

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Powerpoint
* Office version number: 16.51
* Operating System: Mac OS
* Browser (if using Office on the web): Safari

## Expected behavior

I'm just trying to get the entire file content but never enter this if statement :

```
Office.context.document.getFileAsync(Office.FileType.Compressed, {sliceSize: 65536 /*64 KB*/},
    function (result) {
      if (result.status === Office.AsyncResultStatus.Succeeded) {
        // If the getFileAsync call succeeded, then
        // result.value will return a valid File Object.
        let myFile = result.value;
        let sliceCount = myFile.sliceCount;
        let slicesReceived = 0, gotAllSlices = true, docdataSlices = [];
        console.log("File size:" + myFile.size + " #Slices: " + sliceCount);

        // Get the file slices.
        getSliceAsync(myFile, 0, sliceCount, gotAllSlices, docdataSlices, slicesReceived);
      } else {
        console.log("Error:", result.error.message);
      }
    });

```
## Current behavior

because the result of getFileAsync comes back as a failure I'm never able to get the file content

## Steps to reproduce

This is the code in question so just running sendFile():

```
// Get all of the content from a PowerPoint or Word document in 100-KB chunks of text.
export default function sendFile() {
  Office.context.document.getFileAsync(Office.FileType.Compressed, {sliceSize: 65536 /*64 KB*/},
    function (result) {
      if (result.status === Office.AsyncResultStatus.Succeeded) {
        // If the getFileAsync call succeeded, then
        // result.value will return a valid File Object.
        let myFile = result.value;
        let sliceCount = myFile.sliceCount;
        let slicesReceived = 0, gotAllSlices = true, docdataSlices = [];
        console.log("File size:" + myFile.size + " #Slices: " + sliceCount);

        // Get the file slices.
        getSliceAsync(myFile, 0, sliceCount, gotAllSlices, docdataSlices, slicesReceived);
      } else {
        console.log("Error:", result.error.message);
      }
    });
}


// Get a slice from the file and then call sendSlice.
function getSliceAsync(file, nextSlice, sliceCount, gotAllSlices, docdataSlices, slicesReceived) {
  file.getSliceAsync(nextSlice, function (sliceResult) {
    if (sliceResult.status == "succeeded") {
      if (!gotAllSlices) { // Failed to get all slices, no need to continue.
        return;
      }

      // Got one slice, store it in a temporary array.
      // (Or you can do something else, such as
      // send it to a third-party server.)
      docdataSlices[sliceResult.value.index] = sliceResult.value.data;
      if (++slicesReceived == sliceCount) {
        // All slices have been received.
        file.closeAsync();
        onGotAllSlices(docdataSlices);
      }
      else {
        getSliceAsync(file, ++nextSlice, sliceCount, gotAllSlices, docdataSlices, slicesReceived);
      }
    }
    else {
      gotAllSlices = false;
      file.closeAsync();
      console.log("getSliceAsync Error:", sliceResult.error.message);
    }
  });
}


function onGotAllSlices(docdataSlices) {
  let docdata = new Array()
  for (let i = 0; i < docdataSlices.length; i++) {
    docdata.push(docdataSlices[i]);
  }

  let fileContent = new String();
  for (let j = 0; j < docdata.length; j++) {
    fileContent += String.fromCharCode(docdata[j]);
  }

  console.log("fileContent: ", fileContent)

  // Now all the file content is stored in 'fileContent' variable,
  // you can do something with it, such as print, fax...
}

```

## Context

Working on an add in that searches the powerpoint text, so before doing the search I'm just trying to get the powerpoint content

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

attached is a screenshot of the error message

![image](https://user-images.githubusercontent.com/82898229/126401943-15bfb676-bcb7-4072-a26d-71dcae6850b7.png)

I'm not sure what's going wrong since I'm following the docs exactly, but any help would be greatly appreciated!

**Comment by lliu113** [comment]
@nima-chatlani - sorry you're hitting this! Unfortunately I can't seem to find the tutorial in the link you provided - it links to the document class with it's associated APIs. Did you try one of the examples?

**Comment by nima-chatlani** [comment]
@lliu113 oh my bad, yes I was following the example listed under the  "getFileAsync(fileType, options, callback)" function

**Comment by nima-chatlani** [comment]
> @nima-chatlani - sorry you're hitting this! Unfortunately I can't seem to find the tutorial in the link you provided - it links to the document class with it's associated APIs. Did you try one of the examples?

@lliu113 oh my bad, yes I was following the example listed under the "getFileAsync(fileType, options, callback)" function

**Comment by ElizabethSamuel-MSFT** [comment]
Link with the example mentioned: https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=excel-js-preview#office-office-document-getfileasync-member(1)

@nima-chatlani Thanks for your reply and apologies for the late response. Are you still facing this issue?

@wangyun-microsoft Can you take a look?

Thanks.

**Comment by Hasmik-dev** [comment]
I'm facing this same issue, always getting the "Internal Error".

**Comment by skribble-freddy** [comment]
This seems to be working now. Could someone please confirm?
