### ISSUE TITLE
Cannot delete a control in word online

### ISSUE THREAD

**Issue by libjosep** [OfficeDev/office-js#1995]
I am not able to delete a content control in word online  if the cannotEdit property is true. I am inserting a content control to document with `insertContentControl` function. After insertion, I am setting the `cannotEdit` flag to true to prevent editing the text in the content control. After that, if I select the content control and press "Delete" key, it is not deleting tht content control. Also, since it is not editable, I cannot use "Backspace" to delete it. The same is working in the PC desktop platform.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Office 365
* Operating System: Windows 10
* Browser (if using Office on the web): Google chrome
 
## Expected behavior

Since the content control can be deleted, right clicking on this should show me 'Remove Content Control' option with which I can delete the content control or selecting the content control by clicking on the three dots and hitting the delete key should delete the content control.

## Current behavior

Right clicking on content control not showing "Remove Content Control" option. Selecting the content control by clicking on the 3 dots and hitting delete key not deleting the content control.

## Steps to reproduce

1. Open a document in word online.
2. Insert a content control with `cannotEdit=true`.
3. Try to delete the content control.

## Link to live example(s)

1. https://gist.github.com/Libinjoseph/ac84f2c1ac56e8a02d5ab64a4fa4a112

## Context

I want to insert a not editable content to document and once inserted, I should be able to remove it from the document if it is no longer required to be a part of the document.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by qinliuMSFT** [comment]
Hi @Libinjoseph, the issue is reproducible from my side, it has been put on our backlog VSO5290651, will let you know once we have any updates.

**Comment by lukamaletin** [comment]
Thank you for your patience. The issue is now resolved and the fix is fully rolled out to production. Please verify it works as expected on your end, and let us know if you face any issues.
