### ISSUE TITLE
Inserting a content control to a blank line is taking the whole line as the range

### ISSUE THREAD

**Issue by libjosep** [OfficeDev/office-js#1996]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

If I insert a content control to a blank line in a document, it is taking the whole line as the range in the online version. It is supposed to take the range according to the text inside the content control. This is working fine in the desktop version

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Office 365
* Operating System: Windows 10
* Browser (if using Office on the web): Google chrome
 
## Expected behavior

The content control should not take the whole line. It should shrink to match the length of the available content inside content control.

## Current behavior

Currently, inserting a content control to a blank line is taking the whole line as its range (Please see the screenshots)

## Steps to reproduce

1. Open a document in word online
2. Insert a content control to a blank line

## Link to live example(s)

1. https://gist.github.com/Libinjoseph/ac84f2c1ac56e8a02d5ab64a4fa4a112

## Useful logs

- [ ] Screenshots
- In word online
![image](https://user-images.githubusercontent.com/28481997/126446098-4edd29bd-f31b-4873-acfb-8cbfd01cac98.png)
- In word desktop
![image](https://user-images.githubusercontent.com/28481997/126446602-d0b59106-4011-45e1-881c-7a0f6887f38f.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by qinliuMSFT** [comment]
Thanks for reporting the issue. It is reproducible and has been put on our backlog VSO5290681, will let you know once we have any updates.
