### ISSUE TITLE
Is it possible to change selection after setSelectionDataAsync?

### ISSUE THREAD

**Issue by akellan** [OfficeDev/office-js#20]
Insert any text with setSelectionDataAsync API method, text appears in a document in selected state.

Is it possible, using Office JS API (or maybe other approach), to remove selection from pasted text and place cursor at the end of the inserted text?

* Platform : PC
* Host : Word
* Office version number: 2013
* Operating System: Win 10

**Comment by sumurthy** [comment]
I think this API should help. https://github.com/OfficeDev/office-js-docs/blob/master/reference/word/range.md#selectselectionmode-string

**Comment by JuaneloJuanelo** [comment]
the API mentioned by @sumurthy  is the way to do it.

**Comment by RXminuS** [comment]
Sorry to re-open this so late after the fact...but the select(selectionMode: string) method doesn't seem to be available until API version 1.1. which in turn doesn't seem to be supported by Office 2013. So is this really solved @JuaneloJuanelo ?

**Comment by RXminuS** [comment]
@akellan Were you able to make their suggestions work in Office 2013?

**Comment by JuaneloJuanelo** [comment]
The features in 1.1 are not backported to MSI 2013. Sorry about this.
