### ISSUE TITLE
Kendo UI components (ComboBox, MultiSelect) do not work properly with latest WebView2 in Office Content Add-in

### ISSUE THREAD

**Issue by tsardy** [OfficeDev/office-js#2000]
When changing selection in the Kendo UI ComboBox or MultiSelect the newly selected item does not show up in the control.

It works properly in Task Pane Add-in (replacing xsi:type="ContentApp" by xsi:type="TaskPaneApp" in the manifest) and in Edge browser. Also works well in Edge webview and worked well in past webView2 releases. 

## Your Environment

* Platform PC desktop,
* Host [Excel, , PowerPoint, 
*21H1 OS-build: 19043.1110, Windows Feature Experience Pack 120.2212.3530.0, 
WebView2 version: 91.0.864.70

## Current behavior
When changing selection the newly selected item does not show up in the control.

## Steps to reproduce
The online kendo example used in the enclosed files: https://demos.telerik.com/kendo-ui/combobox/index?_ga=2.120912907.287457084.1626733546-1971334470.1626381659 
Files: kendosample.html, ActiveGraf.xml (add-in manifest)
enclosed are two files to reproduce:
[samples.zip](https://github.com/OfficeDev/office-js/files/6860826/samples.zip)

**Comment by AbidRahman-MSFT** [comment]
Hey @tsardy, thanks for reporting the issue.

@smaremanda, could this be a result of a recent WebView2 change?

**Comment by tsardy** [comment]
@smaremanda Do you have any update on this?

**Comment by tsardy** [comment]
@AbidRahman-MSFT , @sohailzafar , @smaremanda , please update the status. this issue blocks us from releasing the new version of our product and our users are not able to place content panes!

**Comment by tsardy** [comment]
@AbidRahman-MSFT  , @sohailzafar , @smaremanda , please update the status. this issue blocks us from releasing the new version of our product and our users are not able to place content panes! URGENT!

**Comment by Dengshan2018** [comment]
@tsardy 
The fix is in Beta Channel (16.0.14413+) or Preview (16.0.14326.20150+)

**Comment by tsardy** [comment]
@Dengshan2018 Thank you for the info! So it means the fix will be delivered via office update? do you have any idea on when the fix will be delivered to regular end-users on the monthly update channel?

**Comment by Dengshan2018** [comment]
The fix could be in monthly update channel by the end of August.
