### ISSUE TITLE
[Word] issue with DocumentProperties.lastSaveTime

### ISSUE THREAD

**Issue by shubhamsoni2074** [OfficeDev/office-js#2001]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

 DocumentProperties.lastSaveTime should as per documentation `Gets the last save time of the document.`. But it does not seems to be working as after changing document and again checking for lastSaveTime it shows same time. and this time seems to be time of uploading document not last saved.
This issue is on web only for desktop it is working fine.

* Platform [PC desktop, Mac, iOS, Office on the web]: WEB
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: office 365
* Operating System: windows
* Browser (if using Office on the web): chrome , edge 

## Expected behavior
last time when doc was changed and saved is expected 

## Current behavior
lastSaveTime value is random or time at which it was uploaded on office web

## Steps to reproduce
follow code 
```
Word.run(async ctx => {
    const doc = ctx.document
    const properties = doc.properties.load();
    ctx.load(doc, "saved")
    await ctx.sync();
    const time = properties.lastSaveTime;
    console.log("properties", time);
    console.log("saved" , ctx.document.saved);
    return ctx.sync();
  }).catch(console.log)
```

## Context
Need to check when document was last modified and saved need to update server based on that.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuoyingLiang** [comment]
Thanks for contacting us. This is an issue. Open Bug 5317429 to track.
