### ISSUE TITLE
[Outlook Onsend AddIn] SaveAsync Office JS API does not update MIP Label to Exchange Server in Outlook Application for Macos

### ISSUE THREAD

**Issue by Premsagar-lab** [OfficeDev/office-js#2003]
# Provide required information needed to triage your issue
On the basis of email body content, we have to enforce MIP Label as provided by the Enterprise policy. 
We use EWS API to fetch the MIP Label applied by the user on outlook email being composed in Onsend addin. 

To run EWS API, we have to save email for getting item id. 
When we save an email just composed by the user, SaveAsync API works fine and we get item id using that item id we are able to retrieve the MIP Label applied by the user. 
If the MIP Label applied by the user is not required one then we have to ask the user to change the label. So, we block sending the email. Now, when user updates the MIP Label, we again try to fetch the label by saving the email using SaveAsync Office JS API but we don't receive the updated MIP Label in this process. We receive the older label applied by the user. 
Now when we add some delay of around 5 seconds after save async call, we are able to get the updated Label. 

In OWA, it works fine. We face this issue only in Outlook Application for Macos.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___Mac___
* Host [Excel, Word, PowerPoint, etc.]: ___Outlook___
* Office version number: ___16.47___
* Operating System: __MacOS____
 
## Expected behavior

Updated Label should be retrieved.

## Current behavior

We get the older Label.

## Steps to reproduce

1. Compose an email with keyword such that Onsend addin shall block email sent. Apply a MIP Label.
2. Send email.
3. When email is blocked update the MIP Label and send the email.
4. Onsend addin should retrieve the updated Label after saving the email.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

We are blocked on our use case of enforcing the MIP Label as per enterprise policy.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@Premsagar-lab Are you using new Mac Outlook UI or old UI?

**Comment by sumitmodi01** [comment]
We are using Old UI

**Comment by exextoc** [comment]
@Premsagar-lab Can you please share code snippet for applying and fetching MIP label?

**Comment by sumitmodi01** [comment]
> @Premsagar-lab Can you please share code snippet for applying and fetching MIP label?

Here is the sample code.
https://gist.github.com/sumitmodi-lab/3d6a3e1a58b846ce7e5c39657e78262f

We just fetch the label applied by user, then match it with required one, and then ask user to apply the correct label.

**Comment by exextoc** [comment]
Thanks for reporting this issue. We can repro this issue in old mac outlook UI. Can you please try using new mac outlook UI?

**Comment by sumitmodi01** [comment]
When we switch to new mac outlook UI, OnSend addin is not getting invoked. 
Mac Outlook Version : 16.47

**Comment by sumitmodi01** [comment]
I updated my mac outlook app to version : 16.51 and now OnSend addin is getting invoked.

But with new outlook UI, we are not able to get "MIP Sensitivity label Name" using EWS API. 
I checked the internet headers of an email (new UI) having Sensitivity label applied, but that label name is not present in internet headers.
We rely on that internet header to get label (fetched from EWS). Its missing in the email sent from new outlook UI.

Could you help us here, how we can find label name applied by user in new outlook UI.

**Comment by sumitmodi01** [comment]
_### Sample labels from internet headers : Old UI_
msip_labels:
 MSIP_Label_2bdc0c70-012z-3b90-a141-123d4290ber4_Enabled=true;
MSIP_Label_2bdc0c70-012z-3b90-a141-123d4290ber4_SetDate=2021-08-03T13:42:48Z;
MSIP_Label_2bdc0c70-012z-3b90-a141-123d4290ber4_Enabled=true;
MSIP_Label_2bdc0c70-012z-3b90-a141-123d4290ber4_Method=Privileged;
MSIP_Label_2bdc0c70-012z-3b90-a141-123d4290ber4_ActionId=1f3060ff-50ed-4a07-af39-183061f39xtr;
MSIP_Label_2bdc0c70-012z-3b90-a141-123d4290ber4_ContentBits=0;
MSIP_Label_2bdc0c70-012z-3b90-a141-123d4290ber4_**Name=Internal**;
MSIP_Label_2bdc0c70-012z-3b90-a141-123d4290ber4_SiteId=1234ce53-0d96-1234-b58b-68fda2fc1234;

_### Sample labels from internet headers : New UI_
 MSIP_Label_2bdc0c70-012z-3b90-a141-123d4290ber4_Enabled=True;
MSIP_Label_2bdc0c70-012z-3b90-a141-123d4290ber4_SiteId=1234ce53-0d96-1234-b58b-68fda2fc1234;
MSIP_Label_2bdc0c70-012z-3b90-a141-123d4290ber4_SetDate=2021-08-04T06:15:16.2616534Z;
MSIP_Label_2bdc0c70-012z-3b90-a141-123d4290ber4_ContentBits=0;
MSIP_Label_2bdc0c70-012z-3b90-a141-123d4290ber4_Method=Privileged

**Comment by exextoc** [comment]
Hey @sumitmodi-lab ,

We are able to reproduce this issue and have added this to our backlog. Thank you for reporting this. Unfortunately, we have no timelines to share at this point.

**Comment by sumitmodi01** [comment]
Any updates on fixing this issue. We have to use hardcoded sleep(3-4 seconds) to making it work, which we can not use in production.

**Comment by exextoc** [comment]
We have a triage bug for this. Need to change tags and update OP accordingly.


From: sumitmodi-lab ***@***.***>
Date: Thursday, 17 February 2022 at 2:43 PM
To: OfficeDev/office-js ***@***.***>
Cc: Outlook Extensibility Oncall ***@***.***>, State change ***@***.***>
Subject: Re: [OfficeDev/office-js] [Outlook Onsend AddIn] SaveAsync Office JS API does not update MIP Label to Exchange Server in Outlook Application for Macos (#2003)

Any updates on fixing this issue. We have to use hardcoded sleep(3-4 seconds) to making it work, which we can not use in production.

—
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Foffice-js%2Fissues%2F2003%23issuecomment-1042727581&data=04%7C01%7CSachin.Mishra%40microsoft.com%7C311858b494fb4bdd6b1308d9f1f5b40d%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637806859914906007%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=jZ6w%2FWfBkbYblYuavl3oUXqB5vV7fYQRnsijnFR5Xus%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGZ2GINSTQYTWESQOPEJBTDU3S3Z7ANCNFSM5A3PLE6A&data=04%7C01%7CSachin.Mishra%40microsoft.com%7C311858b494fb4bdd6b1308d9f1f5b40d%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637806859914906007%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2Yqw8B%2BjfFbV0chsL9J2jXCIpc11LOXwT5c%2FqUkjTVU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CSachin.Mishra%40microsoft.com%7C311858b494fb4bdd6b1308d9f1f5b40d%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637806859914955997%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=2NhiAjEaAySFU%2FaGJ5hWzSSZ6SsDr6AMeQYlzSCRcG8%3D&reserved=0> or Android<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CSachin.Mishra%40microsoft.com%7C311858b494fb4bdd6b1308d9f1f5b40d%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637806859914955997%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VfWN7l27HTpRdn3wGVt31xglW6lfLo7HXIUJ6hDzfKs%3D&reserved=0>.
