### ISSUE TITLE
How to run desktop Word AddIn with ngrx in MS office 2016

### ISSUE THREAD

**Issue by vinodifour** [OfficeDev/office-js#2004]
I'm trying to load word addIn in desktop MS-office 2016 but not working. it's work fine in online platform. I have tried With Angular 11.0.5 and MS Word 2016 my AddIn working fine with desktop and web, but when upgrading the version of angular CLI to 12.1.1 and also added NgRx framework after that Add-in does not load in desktop word file.

**Code attached on below link :**
https://drive.google.com/file/d/1F89iEdDuYenyRdu3745Ammy7ex76k2h8/view?usp=sharing

**Environment detail :**
PC Desktop : Windows 10
Browser on Web - Microsoft Edge, Mozila Firefox
Office version - 2016/2019, office 365
64 bit Operating System
 
**Additional Details :**

AddIn working fine with Word online version Add-in does not load with MS Word 2016/2019/365 desktop version after upgrading to latest angular version.

**Comment by grangeryy** [comment]
@vinodifour do you still see this issue?
