### ISSUE TITLE
Dialog (modal) "Message from Add-in:" should be removed or customizable. It confuses users.

### ISSUE THREAD

**Issue by jimbarrett33** [OfficeDev/office-js#2006]
When displaying dialog with `displayInIframe: true` (modal) the dialog gets a title "Message from Add-in: <add-in name". I see that https://github.com/OfficeDev/office-js/issues/971 indicates that "For security reasons, we do not currently allow customizable dialog titles" (although I don't really understand), but at least get rid of the "Message from Add-in:" part and leave the add-in name. 

To me this is a bug. It seems like the original developer of this feature had some debug code with the string "Message from Add-in:" that made it into production builds but never made it out of production builds. What is a user supposed to think when reading this?

Issue 971 also indicates to use User Voice which no longer exists. Hence, trying to keep this issue alive.

## Your Environment
Excel (but probably all Office apps that support Dialog API)
 
## Expected behavior
Just the app name, a customizable name, or an option to hide the title altogether.

## Current behavior
Title has the confusing message "Message from Add-in:"

## Steps to reproduce
Open a dialog with `displayInIframe: true`

# Provide additional details
It's probably not that simple but this would seem like a 1 or 2 line fix in the Excel (and other Office app) source code but would be a BIG win for users.

**Comment by lliu113** [comment]
@jimbarrett33 - appreciate your feedback here! We are working on removing this string. As you already mentioned, this is included for security purposes. The main reason is to prevent a malicious add-in from spoofing a legitimate dialog (e.g. an office auth). The string makes it very clear to the user that the dialog belongs to an add-in. However, we understand this can be unappealing and we are investigating other methods to differentiate an add-in dialog.

We have migrated over to the [Microsoft 365 Developer Platform](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Office%20Add-ins%20UX) to track requests, feel free to open a new item there to track this. 

I'll close this issue, please feel free to reactivate if you have any additional questions/feedback. Thanks!
