### ISSUE TITLE
ItemType differs between Office.js and MAPI MESSAGE_CLASS properties

### ISSUE THREAD

**Issue by jak-hammond** [OfficeDev/office-js#2008]
This might be a little niche, but we are writing an add-in and we need to make sure that meeting appointments are not processed. We have achieved this partially by using the `Office.MessageCompose.itemType` property which for a new appointment, correctly returns `Appointment`, however when a meeting invite is **FORWARDED**, then Office.js is returning the item type as `Message`.

Using the Graph API, we are querying the messages `singleValueExtendedProperties` for the following property `String 0x1A` (`MESSAGE_CLASS`) and when this call returns we are getting `IPM.Appointments` which is telling us the message being forwarded is actually an appointment. You can also see this by the unique UI that Outlook displays when forwarding a meeting invite, so it clearly knows this is a special case.

We're wondering why, Office.js is not reporting the same as a query to Graph API when trying to figure out the items type?

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop/Mac/Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook for Mac 16.52 (21072100)
* Operating System: macOS Big Sur 11.4
* Browser (if using Office on the web): Edge Chromium and Google Chrome
 
## Expected behavior
When forwarding a calendar invite in Office.js, it would reflect the unique UI displayed by Outlook and the Graph API call by returning `Appointment` on the `itemType` property.

## Current behavior
Office.js currently returns `Message` for the `itemType`

## Steps to reproduce
1. You will need an add-in that has Graph API access
2. Send yourself a Calendar Invite
3. Attempt to forward it and inspect the `itemType` on the item in Office.js
4. Make a call to Graph API and request the `MESSAGE_CLASS` property
5. It'll return the item as actually being an appointment

## Context
We are making sure that we only process messages and currently, we are now having to make a secondary API call every time to work around this issue.

**Comment by exextoc** [comment]
Thanks for asking about this.

[`Office.context.mailbox.item.itemType`](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailboxenums.itemtype?view=outlook-js-preview) returns either `appointment` or `message` and is just meant to distinguish between these two modes that an add-in can run in (and you may already know the mode if they have different SourceLocation URLs in your manifest).

There is an [`Office.context.mailbox.item.itemClass`](https://docs.microsoft.com/en-us/javascript/api/outlook/office.appointmentread?view=outlook-js-preview&preserve-view=true#itemClass) property, however it's only available in Read/Attendee mode (you can use it to determine whether a user is viewing a meeting request in their inbox). I'm not sure of the reason for this. Perhaps it couldn't be made available as a synchronous property.

As a workaround for your scenario, of determining whether a forwarded message is an appointment, you could check whether the [`Office.context.mailbox.item.start`](https://docs.microsoft.com/en-us/javascript/api/outlook/office.appointmentread?view=outlook-js-preview&preserve-view=true#start) property is populated (it contains the start time of the appointment). You can compare this with your workaround to see if it's a good substitute for you.

Some more information about the item class: You may not be able to discern the meaning of an item class from its name, but there's helpfully documentation for it at [Item Types and Message Classes](https://docs.microsoft.com/en-us/office/vba/outlook/concepts/forms/item-types-and-message-classes). If you do match on the item class, you may want to match using a `startsWith` function to handle cases where the item class has been extended.

**Comment by jak-hammond** [comment]
@exextoc thanks for that explanation, helps understand the differences a little better, we will give the `item.start` approach a look to see if that works but if that `item.itemClass` could be made available across more scenarios, that would be the perfect solution. 

As I say, in our work around at the moment, we are calling Graph directly so I imagine in a compose scenario, the item might not have sync'ed up for Office.js to query but doing an optimistic save or something could potentially resolve this, would you be able to let me know if expanding this property to other scenarios is on the roadmap at all, or could I log it on the Office.js user voice forums?

**Comment by exextoc** [comment]
itemClass is not currently slated to be on the road map. Adding a feature request here would help prioritize the issue:
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

Please let us know if the item.start workaround helped at all.

**Comment by jak-hammond** [comment]
Hi @exextoc unfortunately, checking the `item.start` was no good for us as it seems to be only present when the item is in read mode, but we need to access this information during a message composition.

**Comment by exextoc** [comment]
Thanks for checking @jak-hammond. Unfortunately we misunderstood the requirement and you are correct, item.start is not available on the item. Using Graph the way you currently are today is the way to go for now. We've opened a work item in the backlog to address this issue and unfortunately can't share timelines at the moment on when the work will be complete. Rest assured, once it is, we'll update the thread with the builds that support the functionality/API.

**Comment by jak-hammond** [comment]
If this item is on the backlog, can we please leave this ticket open until some resolution is reached, thanks!
