### ISSUE TITLE
Request: Alternative use of Dialog API in iOS to avoid using a WebView

### ISSUE THREAD

**Issue by raulgg** [OfficeDev/office-js#201]
I am using the Dialog API in Office.js to open an window to authorize the user into our service, where we are also doing OAuth interactions with the most common services out there. While using the Dialog API seems to be working fine overall for our use case, we are facing an issue with iOS and Google's OAuth service.

On August 2016 Google made a change on how their OAuth service works, blocking embedded browsers for performing OAuth requests for safety reasons (more info in [their blog](https://developers.googleblog.com/2016/08/modernizing-oauth-interactions-in-native-apps.html)). Hence, as the Dialog is opening in a WebView, we will not be able to perform any OAuth request to Google and instead we will see a 403 error message.

I believe this issue could be addressed using a SFSafariViewController instead of a WebView in the Office apps for iOS, and this way Google would not be blocking the requests. I guess a parameter in the configuration object (similar to displayInIframe) could do it.

## Expected Behavior
The request to Google's OAuth endpoint should be loaded properly in the mobile apps when using the Dialog API for authorization purposes.

## Current Behavior
When performing an OAuth interaction using the Dialog API with Google's service, a 403 error message appears with a "disallowed_useragent" code.

## Your Environment
* Platform: iOS
* Office version number: 2.15

**Comment by JuaneloJuanelo** [comment]
thanks for reporting this, known issue and we are working on a fix.
tracking internally with 2453637, expect updates soon.

**Comment by ElizabethSamuel-MSFT** [comment]
@lliu113 Can you provide a current status on the bug fix? Thanks.

**Comment by lliu113** [comment]
@raulgg Hey Raul, sorry for the late update response. We investigated the issue, and this is significantly above a bug level fix. For now, this is not a scenario we support (iOS with Google oAuth). 

If this is an important user scenario for you, please submit a feature request at https://officespdev.uservoice.com/

Thanks!
