### ISSUE TITLE
Windows 11 and WebView 3 seems to break or not implement the latest Edge chromium browser

### ISSUE THREAD

**Issue by mikewalker74** [OfficeDev/office-js#2010]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
Installing Microsoft Edge WebView 2 Runtime on a windows 11 machine with Microsoft® Outlook® for Microsoft 365 MSO (16.0.14131.20326) 64-bit seems to revert the runtime for Edge Legacy and not the latest chromium based solution. 

## My Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Surface Book 2
* Host [Excel, Word, PowerPoint, etc.]: Outlook 
* Office version number: 16.0.14131.20326
* Operating System: Windows 11
* Browser (if using Office on the web): ______
 
## Expected behavior

To load the correct browser and render and support the JS methods that are stated to be supported and not rendering as before
![image](https://user-images.githubusercontent.com/35928561/127531105-726080bd-03b4-4e6e-a849-4e664154342c.png)
vs a working machine String
![image](https://user-images.githubusercontent.com/35928561/127531166-cbada5d8-b67f-41d8-9048-4331a464e826.png)

UI Rendering looks like on Windows 11
![image](https://user-images.githubusercontent.com/35928561/127531565-a04dad6b-9137-4a55-aa89-dc7e4c8ffcae.png)
UI Rendering looks like on Windows 10 
![image](https://user-images.githubusercontent.com/35928561/127531696-04ec0d5c-cdbe-4c26-8b0a-c1a9f1f5ea4b.png)

**Comment by dlineg4** [comment]
I'm also have an Office.js add-in that has stopped rendering with the same User Agent string:

Mozilla/5.0 (Windows NT 10.0; Win64; x64; WebView/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19042

This was on Windows 10 and Desktop Outlook
