### ISSUE TITLE
Errors on Office.context.mailbox.item.location.setAsync

### ISSUE THREAD

**Issue by jean-wujingyi** [OfficeDev/office-js#2011]
For newUI of Outlook desktop version, when I open a new meeting event and inject Room info on location field first, then try to using addin to inject meeting link to location field, the location field could not spilt Room info and meeting link correctly. It been used semicolon before but seems invalid now.
<img width="1105" alt="Screen Shot 2021-07-22 at 11 14 28 AM" src="https://user-images.githubusercontent.com/66811843/126585175-dbac8f96-5357-4c8c-9a09-6a1088cb0f80.png">

And for web version of Outlook, it will lose Room tag and changed to a normal location if I just using Office.context.mailbox.item.location.**setAsync** function to set what I get from Office.context.mailbox.item.location.**getAsync** function
<img width="430" alt="Screen Shot 2021-07-22 at 11 18 28 AM" src="https://user-images.githubusercontent.com/66811843/126585559-062c35fa-0355-4a3e-8890-c126a65b7b14.png">

<img width="726" alt="Screen Shot 2021-07-22 at 11 17 55 AM" src="https://user-images.githubusercontent.com/66811843/126585518-dfdb5f3d-61d1-4ad3-aac8-77626be851ed.png">

These issues happened recently, and other products（like Zoom） on Add-ins Store has similar problems. 
Could anyone help to have a look with it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5492f54a-9de7-eb2f-aab2-060ed723e7ab
* Version Independent ID: 13ecc3e7-1a51-3839-a902-7f92a4d041bf
* Content: [Office.Location interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.location?view=outlook-js-preview)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.location.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.location.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
This bug is closed due to inactivity for a long time. If the issue resurfaces, please re-open it. Thank you.
