### ISSUE TITLE
worksheet.freezePanes.freezeAt() failed on one specific file

### ISSUE THREAD

**Issue by lucasqu-venacorp** [OfficeDev/office-js#2014]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __PC desktop____
* Host [Excel, Word, PowerPoint, etc.]: __Excel____
* Office version number: __16.0.13929.20296____
* Operating System: _Windows 10 Pro_____
* Browser (if using Office on the web): ______
 
## Expected behavior
We want to freeze the range `A1:N31` on the attached file, using this javascript API: https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheetfreezepanes?view=excel-js-preview#freezeAt_frozenRange_ . 

## Current behavior
When we trying to freeze `A1:N31`, error occured at `WorksheetFreezePanes.freezeAt()`;
![image](https://user-images.githubusercontent.com/88202215/127677344-027fbf97-9b27-4890-9f0d-b374a13d7f30.png)

## Steps to reproduce
1. Open the attached file, and insert Script Lab add-in ____
2. Try to trigger this function in Script Lab
```
async function freezeAt() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getItem("Sheet1");

    // Freeze the specified range in top-and-left-most pane of the worksheet.
    sheet.freezePanes.freezeAt(sheet.getRange("A1:N31"));

    await context.sync();
  });
}
```
## Link to live example(s)

1. https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheetfreezepanes?view=excel-js-preview#freezeAt_frozenRange_ 

# Provide additional details

## Useful logs

- [x] Console errors
- [x] Screenshots
- [x] Test file (if only happens on a particular file)
[FreezePaneDebug.xlsx](https://github.com/OfficeDev/office-js/files/6908682/FreezePaneDebug.xlsx)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by qinliuMSFT** [comment]
Hi @lucasqu-venacorp , I could not repro your issue on my environment. Do you only have this issue on the specified file and specified version of Excel? 
BTW, could you please have a try on the latest version of Excel? The latest monthly channel version should be 16.0.14228.xxxxx.

**Comment by lucasqu-venacorp** [comment]
@qinliuMSFT  Hi, it is happened on a specified file and we tried different versions of excel and got the same error. I attached the file in the description, you can find it in **Useful Logs** Session. And yes i'll try again with the version you mentioned.

**Comment by qinliuMSFT** [comment]
@lucasqu-venacorp , could I know your attempt result on the up-to-date version? I've tried your provided file in Useful Log on this version, and it could run successfully.

**Comment by lucasqu-venacorp** [comment]
hi @qinliuMSFT  yes. I tested on the update-to-date version: "16.0.14228.20226" on current channel, and can get the same error.
Did you try the script i provided? 
```
async function freezeAt() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getItem("Sheet1");

    // Freeze the specified range in top-and-left-most pane of the worksheet.
    sheet.freezePanes.freezeAt(sheet.getRange("A1:N31"));

    await context.sync();
  });
}
```

**Comment by qinliuMSFT** [comment]
Hi @lucasqu-venacorp , yes I tried the script you provided and the file in the Useful logs, but I could not have a local repro. I will try on another machine later. Will back to you then. 
In addition, could you please confirm the issue only happens on this specified file, and could not repro on some normal files, is it right? 
I'm wondering how this file is different from other files if you only hit this issue on this specified file. Could you please share how you created this file?

**Comment by lucasqu-venacorp** [comment]
@qinliuMSFT Yes thank you very much!  And yes this is a specific file we are hitting the error, others are good.
I think there should not have any difference in creating this worksheet. originally, this file has a lot of contents and names on the sheet. Since I am trying to narrow down the problem, I cleared the worksheet it looks like an empty worksheet now. I guess there is something wrong behind the worksheet, and blocking the `freezeAt` api call 🤦‍♂️

**Comment by qinliuMSFT** [comment]
Thanks @lucasqu-venacorp for the clarification, I'm hoping it will not block your current work since the issue only occurred in this specific file. I've created bug VSO#5338191 to track this. If we have any progress, will let you know.

**Comment by lucasqu-venacorp** [comment]
@qinliuMSFT  thank you! Let me know if there anything I can help for debugging.

**Comment by gingerjia** [comment]
@lucasqu-venacorp thanks very much for reporting the issue. 
The root cause is due to part of the range("A1:N31") in the file isn't in viewable area. If you change the range to a smaller one that totally in viewable area, then won't get this error.

For setting freezePanes in unviewable range isn't allowed and this is by design, which is align with UI:
![image](https://user-images.githubusercontent.com/62282034/129054727-f5b1e712-e2ed-4315-af65-54974fab563a.png)
But the general exception error isn't by design and not user friendly. We will definitely work on this part improvement. 

Thanks again for your question. And please let us know if have any other issues.

**Comment by lucasqu-venacorp** [comment]
@gingerjia thank you!
