### ISSUE TITLE
Powerpoint get all text

### ISSUE THREAD

**Issue by nima-chatlani** [OfficeDev/office-js#2015]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Microsoft 365 Developer Platform Ideas Forum

We're moving away from UserVoice feedback sites on a product-by-product basis throughout the 2021 calendar year. Later in 2021, we will leverage a 1st party solution for customer feedback. Meanwhile, please post feature requests and suggestions at the [Microsoft 365 Developer Platform Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). 

For more information, see [UserVoice pages](https://support.microsoft.com/topic/uservoice-pages-430e1a78-e016-472a-a10f-dc2a3df3450a).

Hello I'm creating a PowerPoint add in and I need to examine/search all the text in the presentation it would be great if that were a feature! I've looked pretty thoroughly through the API and haven't seen anything that gives me what I'm looking for but if there's an existing solution to get all the text in a presentation I would appreciate someone pointing me in the right direction!

**Comment by lindalu-MSFT** [comment]
Hi, thanks for the suggestion. Please go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and click Submit an Idea.
