### ISSUE TITLE
batching custom functions example doesn't work in excel

### ISSUE THREAD

**Issue by eldargum** [OfficeDev/office-js#2016]
When I tried to run a batching custom function in excel I get an error

Verbose	Runtime	[Console] [Log] error message:Host may not have set any promise continuation callback. Promises may not be executed.	

In Office Web app it's working normally. Will this work in excel?

**Comment by ElizabethSamuel-MSFT** [comment]
@grangeryy Can you take a look?

Thanks.

**Comment by davidchesnut** [comment]
Hi @eldargum,

I tried running the manifest.xml from the sample, using the same version of desktop Excel that you specified, and it is running correctly. I recommend you try [clearing the Office cache](https://docs.microsoft.com/office/dev/add-ins/testing/clear-cache). 

BTW: If you made changes to the sample or manifest please let us know so we can try to reproduce the behavior. 

Hope this helps,
David

**Comment by eldargum** [comment]
Hi @davidchesnut,

I added XMLHttpRequest in _fetchFromRemoteService function to get data from the web service. And I see that the request is being executed, but in custom function log -error message:Host may not have set any promise continuation callback. Promises may not be executed.

**Comment by grangeryy** [comment]
@eldargum have you followed the instruction on how to [Receive and handle data with custom functions](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-web-reqs)? If it still doesn't work, it would be of great help if you could share to us the sample your code snippet. THX!

**Comment by eldargum** [comment]
Hi @grangeryy,

my code snippet is below and it's working in office web excel
```
async function _fetchFromRemoteService(requestBatch) {
  // Simulate a slow network request to the server;
  //console.log("_fetchFromRemoteService");
  
  const inputJson = JSON.stringify(requestBatch);
  console.log(inputJson);

  const outputJson=getTestBatching(inputJson);
  const results = await Promise.resolve(outputJson);

  console.log(JSON.stringify(results));

	return results;

}

async function getTestBatching(json) {
	
      return new Promise (function (resolve) {
      
        var xhr = new XMLHttpRequest();

        xhr.onreadystatechange = function () {

             if (xhr.readyState === XMLHttpRequest.DONE) {

                var res =xhr.responseText;
              //  console.log(resFloat);
              var resObj=JSON.parse(res);
              resolve(resObj);
 
             }
         };
        //make request
        var data = json;
        xhr.open("POST", "https://myurl/webservices/getTestAmountBatch.ashx");
        xhr.setRequestHeader("Content-Type", "application/json");
        xhr.send(data);

      });

}
```

**Comment by grangeryy** [comment]
@xiaochunms could you help to take a further look? THX!

**Comment by eldargum** [comment]
I tried also request to github but the error remained
xhr.open("GET", "https://api.github.com/rate_limit");

**Comment by grangeryy** [comment]
Created a bug 5337742 to track this issue.

**Comment by xiaochunms** [comment]
@eldargum sorry for the issue. As it works on web, I am thinking if configuring the project to use shared runtime can help ([configure-your-add-in-to-use-a-shared-runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime))? And is it possible to share a sample project that I can have a try locally at my side?

**Comment by eldargum** [comment]
> @eldargum sorry for the issue. As it works on web, I am thinking if configuring the project to use shared runtime can help ([configure-your-add-in-to-use-a-shared-runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime))? And is it possible to share a sample project that I can have a try locally at my side?

@xiaochunms, thanks. Of course you can share. I'll look into shared runtime.

**Comment by xiaochunms** [comment]
@eldargum, thanks to take efforts to look into shared runtime. And at the same time is it possible for you to share your sample project with me that I can try locally at my side? Sorry for the misleading in my last message if there is any.

**Comment by eldargum** [comment]
> @eldargum, thanks to take efforts to look into shared runtime. And at the same time is it possible for you to share your sample project with me that I can try locally at my side? Sorry for the misleading in my last message if there is any.

@xiaochunms, I added my script

[customfunctions_gh.txt](https://github.com/OfficeDev/office-js/files/6982355/customfunctions_gh.txt)

**Comment by eldargum** [comment]
Hi @xiaochunms,

 have you time to look my issue?

**Comment by xiaochunms** [comment]
Hi @eldargum, sorry for the late response. I tried with the manifest.xml from the sample, and it is running correctly on Excel web and Excel Win32 both. The result is same with @davidchesnut's. So I am thinking the batching should work well. Then I tried to run with manifest-local.xml, which can debug your functions with local host server, unfortunately in Win32 I hit an issue that the resource files cannot be downloaded when installing the Add-in. I've dropped an mail to @davidchesnut to ask him for helps. 

BTW, is the batching sample working well at your side? We may can start from there by adding changes gradually if batching sample works.

**Comment by eldargum** [comment]
thanks @xiaochunms ,

the sample works well, the issue occurs when requesting the web service

**Comment by eldargum** [comment]
@xiaochunms , below is a simple sample with github API to validate one cell formula.

`async function getGithubLimit() {

  return new Promise (function (resolve) {
      
    var xhr = new XMLHttpRequest();

    xhr.onreadystatechange = function () {

         if (xhr.readyState === XMLHttpRequest.DONE) {

            var res =xhr.responseText;
          //  console.log(resFloat);
          var resObj=JSON.parse(res);
          var limit=resObj.rate.limit;
          var resGH="[{\"result\":" + limit+ "}]";
          var resGH2=JSON.parse(resGH);
          resolve(resGH2);

         }
     };
    //make request
    xhr.open("GET", "https://api.github.com/rate_limit");
    //xhr.setRequestHeader("Content-Type", "application/json");
    xhr.send();

  });

}`

**Comment by davidchesnut** [comment]
Hi @eldargum,

I tried the getGithubLimit() sample and it runs fine. However I set it up as its own custom function along with its own description in functions.json. I'm not confident that this is the same configuration as your sample. Since you are just working with sample code, would it be possible to share your project in a GitHub repo so we can try running the same project code and be sure we are doing the exact same testing?

Thanks!

**Comment by xiaochunms** [comment]
Hi @eldargum, 
Like @davidchesnut did, I tried the getGithubLimit()  at my side too and I did not hit the issue when requesting the web service.  I think @davidchesnut's proposal to share your project in a GitHub repo is a good idea that we are running and debugging the exact same project. 

What would you think?

**Comment by eldargum** [comment]
Hi @davidchesnut, @xiaochunms, thank you for your answers

Today I replaced the web server (IIS with npm http-server) and my sample started working. Now I want to understand whether it will work with IIS.

**Comment by davidchesnut** [comment]
Sounds like IIS wasn't serving all of the files. The sample is just using static pages which is definitely supported by IIS. I'd open a browser window and browse directly to the URLs for functions.json functions.js, etc... These should all return the file contents for the http-server you set up. Then try under IIS. I'm guessing one or more will fail. That should help indicate what's happening with IIS.  Hopefully it's simple, like maybe an extra folder name is in the URL path, in which case you can adjust the IIS configuration, or the manifest to use the expected URL path by IIS.

**Comment by eldargum** [comment]
> Sounds like IIS wasn't serving all of the files. The sample is just using static pages which is definitely supported by IIS. I'd open a browser window and browse directly to the URLs for functions.json functions.js, etc... These should all return the file contents for the http-server you set up. Then try under IIS. I'm guessing one or more will fail. That should help indicate what's happening with IIS. Hopefully it's simple, like maybe an extra folder name is in the URL path, in which case you can adjust the IIS configuration, or the manifest to use the expected URL path by IIS.

@davidchesnut , But my sample works fine with IIS in the online Excel version

**Comment by davidchesnut** [comment]
Sorry about that. So when using IIS as the server, you get the error: "Host may not have set any promise continuation callback". And only on Excel on Windows. it does work on Excel on the web. But if you switch the server to Node.js, it starts working on Excel on Windows. And it also works on Excel on the web.

The only other thing I can think of is to try changing the GUID id in the manifest to a new unique guid. Excel will see the add-in as brand new and create a new cache for it, so it shouldn't be loading any out-of-date files if by chance there is still something cached.

if it is still not working.
* Is it possible to post a GitHub repo with the sample so we can test the exact code and project you have?
*  Can you let us know the browser version Excel on Windows is using? To do so:

1. Create a new basic task pane add-in project using yo office or Visual Studio.
2. Start the project and sideload the add-in into Excel.
3. Open the task pane.
4. Choose the personality arrow in the upper-right corner.
![image](https://user-images.githubusercontent.com/8559338/132397795-03ac2a7c-3625-4378-bcc9-72eaf0e165fd.png)
5. Choose **Security Info**.
6. Let us know what the **Runtime** value is. For example it is Microsoft Edge in the following screen shot.
![image](https://user-images.githubusercontent.com/8559338/132397899-d113395c-f183-4da7-bffb-991c32e994a9.png)

Thanks!
David

**Comment by eldargum** [comment]
Hi @davidchesnut , @xiaochunms ,

thanks a lot for the answers! I switched my project to node.js and continued development there.
