### ISSUE TITLE
context.runtime.load("enableEvents") does not work in Windows with Excel 2016 or earlier

### ISSUE THREAD

**Issue by tqdo** [OfficeDev/office-js#2017]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC 
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2016 and earlier
* Operating System: Window
 
## Expected behavior
I expect the code `context.runtime.load("enableEvents")` to run without problems with Excel 2016 or earlier 

## Current behavior
My code which has `context.runtime.load("enableEvents")` returns the error `NotImplemented: This operation is not implemented.` when running in Excel 2016 or earlier

## Steps to reproduce
The below code is the sample code for Excel addin found [here](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator). Just added the line `context.runtime.load("enableEvents");` and the error will appear.

````
export async function run() {
  try {
    await Excel.run(async (context) => {
      /**
       * Insert your Excel code here
       */
      const range = context.workbook.getSelectedRange();

      // Read the range address
      range.load("address");

      // Update the fill color
      range.format.fill.color = "yellow";

      ///////// New code. Adding this line will cause error
      context.runtime.load("enableEvents");

      await context.sync();
      console.log(`The range address was ${range.address}.`);
    });
  } catch (error) {
    console.error(error);
  }
}
````

# Provide additional details
The code works totally fine in Excel 2019 or later

## Context

When the user first starts my add-in, I attach an onEdit handler to the spreadsheet. However, when the user uses my taskpane, I will update a lot of cells in the spreadsheet and I don't want that onEdit trigger to fire so I want to turn them off by first calling 
`context.runtime.load("enableEvents");` and then later `context.runtime.enableEvents =false`

**Comment by keyur32** [comment]
Hi there, sorry for missing this earlier, but this API is only supported in the Excel 1.8 Requirement Set. 

You can learn more here:
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-1-8-requirement-set,  and learn about requirement sets in general here: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets.  You can use these to detect if the version of Office has the capability you are looking for.

thanks.
