### ISSUE TITLE
No mouseleave event when moving the cursor outside Excel Content Pane container

### ISSUE THREAD

**Issue by david-ps** [OfficeDev/office-js#2018]
There appears to be recent  changes introduced that negatively affect the way hover events work in Excel Content Pane Apps that affect the UX.

## Environment
* Platform: PC
* Host : Excel
* Office version number Microsoft 365 MSO 16.0.14228.20200
* Operating System: Windows 10
 
## Expected behavior
There is a mouseleave event when moving the cursor away from a button and outside the Content Pane so the Hover Background and Tip are cleared.

## Current behavior
When moving the cursor away from a button and outside the Content Pane there is NO mouseleave event and the Hover Background and Tip are NOT cleared.

## Steps to reproduce
1. Move mouse cursor over a example button to show Hover Background and Tip
2. Move the cursor outside the Content Pane container 
3. Example button Hover Background and Tip remain

## Example
![Excel-Content_Pane_Hover_Issues](https://user-images.githubusercontent.com/47418828/127838622-76206702-1223-4b53-8e58-dc832e109815.gif)

## Context
This behaviour is confusing and negatively affects the UX.

**Comment by david-ps** [comment]
@AbidRahman-MSFT Note this behaviour does not occur in Excel Online and works as expected.

**Comment by AbidRahman-MSFT** [comment]
Hey @david-ps, thanks for reporting this issue. 

I'm trying to understand the technical implementation here - are you using this [mouseleave event](https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseleave_event) on your content add-in?

If so, did this use to work as expected in Windows and recently the experience has regressed?

Thanks for your time and the info!

**Comment by david-ps** [comment]
Hi @AbidRahman-MSFT 

We are using a 3rd party toolbar shown in the animated example above that manages the hover events, but we assume fails to get a mouseleave event when the cursor travels outside the Content Pane (shape). 

This is new and did not happen previously. We notice there have been some recent changes to Content Pane "Shapes" behaviour  eg. they now are subject to z-order so it appears to be introduced in that update.

**Comment by Dengshan2018** [comment]
@david-ps Thanks for reporting the issue. working on the fix.

**Comment by Dengshan2018** [comment]
The fix is in 16.0.14416+. @david-ps , you can try if you are in Beta Channel.

**Comment by david-ps** [comment]
@Dengshan2018 Great, thanks!
