### ISSUE TITLE
Office Add-in: Read/Write Custom Document Properties with Office JS [Word & Excel API] 1.1 on Windows 10

### ISSUE THREAD

**Issue by akoushke** [OfficeDev/office-js#202]
### Background:
I'm developing an add-in in _macOS_ and I am able to read a custom document property:
```js
return await this.api.run(async (context) => {
  const properties = context.document.properties.customProperties;
  properties.load('key,type,value');
  await context.sync();

  const roomID = properties.items.find(item => item.key === 'Webex_Teams_roomID');
  return roomID ? roomID.value : null;
});
```
and write one:

```js
return await this.api.run(async (context) => {
  context.document.properties.customProperties.add('Webex_Teams_roomID', newRoomID);
  await context.sync();
});
```
Where **this.api** is just **window.word** using `office JS API`. I used help from the following repo which is offered by Microsoft themselves, [office-js-snippets](https://github.com/OfficeDev/office-js-snippets/blob/master/samples/word/07-custom-properties/read-write-custom-document-properties.yaml#L14). 

### Problem:
I'm not able to run my code in window's machine. After debugging the code, I learned that my code gets stuck at this point: `await context.sync();`.

### Office Versions:
Office Versions in macOS: `16.14.1 (180613)`.

Office Version in Windows: `16.0.4639.1000 32-bit`

### Updates:
After some digging, I found that I don't have access to `context.document.properties.customProperties.items`. It will display `<permission denied>` error. Could this be it? 

### More Updates:
`Permissions` is set to `ReadWriteDocument`:
```xml
 <Permissions>ReadWriteDocument</Permissions>
```
### More More Updates:
No it is not `Async/Await` issue. I tested my add-in on IE 11 and it worked fine. I think it is the permission issue. Any ideas?

**Comment by JuaneloJuanelo** [comment]
the problem that you have is that you are using MSI build and the API set you need does not work there. One solution is to  move to Office 365.

**Comment by akoushke** [comment]
Is this the only solution available? How can I make this API functional in this MSI build though? I can't just ask all the users to switch to 365 because the office API is not functional on 2016?

**Comment by akoushke** [comment]
Thanks for your response. I was wondering if this would still work if the users upgrade their office 16 products to `16.0.6769.0000 or higher (**16.0.6868.0000** recommended)` according to [this](https://github.com/OfficeDev/office-js-docs-pr/commit/eba5425d6a8b4f977ea2ead77933d0e8bed75961)?
