### ISSUE TITLE
[Outlook] Duplicated addin pane

### ISSUE THREAD

**Issue by ruleechen** [OfficeDev/office-js#2023]
It appears two outlook addin pane when I double click on the ribbon button to show addin pane.

## Your Environment

* Platform: PC desktop
* Host: Outlook
* Office version number: Microsoft Outlook for Microsoft 365 MSO (16.0.13801.20772) 644-bit
* Operating System: Windows 10
* Browser (if using Office on the web): I think it's embedded IE
 
## Expected behavior
Only one pane on the right hand side.

## Current behavior
A pane display on the right hand side which is correct. But a dupldated pane will display on the left top of the screen.

## Steps to reproduce
1. Open outlook calendar tab
2. Select a time and right click on the calendar to "New Appointment"
3. In the new appointment window, double click (or some more clicks) on the "Schedule with RingCentral" ribbon button

## Useful logs
- Screenshots
![image (2)](https://user-images.githubusercontent.com/907369/128136592-b7360fb2-42b2-4eee-a7fc-4d4a30bd3b33.png)

**Comment by exextoc** [comment]
Does the duplicate taskpane only show up with the "Schedule with RingCentral" add-in or does it happen with other add-ins as well?
Do both taskpanes load?

**Comment by exextoc** [comment]
Are you only seeing a duplicate taskpane with Schedule with RingCentral add-in or does it happen with other add-ins as well.

**Comment by ruleechen** [comment]
> Are you only seeing a duplicate taskpane with Schedule with RingCentral add-in or does it happen with other add-ins as well.

I tried OneNote addin. The same problem exists.

Actually, I can not always reproduce it. I noticed that I can reproduce it much easier when my CPU is heavy used.

![image](https://user-images.githubusercontent.com/907369/128291748-ef2fe668-b8cf-49f7-8b75-10ab0584e3b2.png)

**Comment by ruleechen** [comment]
Additional information
1. Only the one on the correct place will loaded (right hand side).
2. The one on the left top will always on the same place (maybe left 0, top 0) even when I move the Appointment window.
3. After I close the Appointment window the one on the left top still there on the same place.
4. After I close the Outlook application the one on the left top finally gone.

![image](https://user-images.githubusercontent.com/907369/128294323-a6803c8f-e05b-45d0-b45c-7589e5ac1168.png)

**Comment by SylvaD-MS** [comment]
Thanks for reporting the issue.  I have installed Ring Central Scheduler Add-in which requires some sign in with a pop up (which might be the 2nd window that you are seeing?  Can you resize it?).  In addition, could you clarify whether you are already signed in when you repro the issue.  When you don't repro the issue do you see a quick flash?  Finally, how fast is your Network connection because the web pages don't seem to load?  How long does it take for the Add-in to fully load (vs. hanging in that state forever)?

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
