### ISSUE TITLE
Mail shows up as encrypted in Outlook 2019, but it's signed.

### ISSUE THREAD

**Issue by JuergenHoffmann** [OfficeDev/office-js#2024]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

hi folks,
one of our customers uses Office 2019 and if we create mails via code with the later following code-lines. Outlook shows the mails as encrypted in the outbox. the custer has mail signing active and that's the point where the problems start's.

The exact code-line that creates the problem is where we add a userproperty before sending the mail. 
=>  'm.UserProperties.Add "test", OlUserPropertyType.olText, False'

I already made a Ticket at the Microsoft-Support who couldn't help me and did send me here.

Way to reproduce the problem:
- activate email-signing in the outlook options.
- use the following code to create a mail and sent it.
- switch to the Sent-Items folder in Outlook and look for the icon of the mail, which should indicate wether it's signed or encrypted. 
=> The icon is a lock, so it show's up as encrypted. But it shouldnt be.

Code to reproduce the problem:
`Sub test()
    Dim m As MailItem
    Set m = Application.CreateItem(olMailItem)
    m.To = "xyz@outlook.com"
    m.Subject = "test"
    m.Body = "Test"
 
    ‘this line forces outlook to change the icon and “encrypts” the mail
    m.UserProperties.Add "test", OlUserPropertyType.olText, False
 
    m.Display
End Sub`

Has anyone an idea of how to solve the problem? We need the userproperties to identify and work with the mails later on in our outlook-addin.

**Comment by davidchesnut** [comment]
Hi @JuergenHoffmann,

This looks like you are using VBA or VSTO code. This repo is for tracking product bugs found related to Office Add-ins, that use JavaScript. For VBA programming questions you'll want to go to Stackoverflow and use the [vba] and optionally the [outlook] tags: https://stackoverflow.com/questions/tagged/vba+outlook

Hope this helps,
David

**Comment by JuergenHoffmann** [comment]
hi david,
yes your right, the code shown is VB, but in the end you will have the same problem, no matter which programming language your using. I only used VB, as it's buildin to outlook and easy to test for everyone that way.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you take a look? Thanks.
