### ISSUE TITLE
Euro symbol missing when setting more than one cell value at a time.

### ISSUE THREAD

**Issue by timbeese** [OfficeDev/office-js#2025]
# Provide required information needed to triage your issue
I have a table of values that I am setting into the worksheet using the officejs interface.  I have an entire column of data and the data is formatted with a Euro symbol at the left, like this:
  Euro
  €127,819.21

When I insert these values on desktop Excel, the Euro is lost.  However, if I use the web version of Excel, the Euro is maintained.  I've also found that if I insert just a single value, such as '€127,819.21', then the Euro is maintained.  I have recreated this in ScriptLab (code listed below).

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: This only happens on desktop Excel.
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Excel  (16.0.14228.20200) 32-bit 
* Operating System: Windows 10 (21H1 (OS Build 19043.1151)
 
## Expected behavior
I expect the Euro symbol to be retained in my cell, like it does on the web.

## Current behavior
The Euro symbol disappears.

## Steps to reproduce
I have recreated this using ScriptLab:

```
function run() {
  return Excel.run(function(context) {
    var range = context.workbook.getSelectedRange();

    // Make sure to have 1 cell selected, this works
    // range.values = [['€127,819.21']];

    // Make sure to have 2 cells selected, spanning 2 rows, I lose my Euro symbol
    range.values = [['Euro Missing?'], ['€127,819.21']]
    return context.sync();
  });
}

```

## Context
We are attempting to display a report with user data.  The data has currency in Euros, and we want to show the currency symbol.  If I manually set the cell to have the Euro format, then this works as expected.  It also works as expected if I force the cell value to Text.  It's when the cell format is 'General' and I set more than one value at a time, and the value contains a leading Euro character ('€127,819.21'), then the Euro character is lost.  

We have options for how to insert the data.  Sometimes the user may want to use General and let Excel interpret the format, sometimes they may want to have us set raw values and assign a format.  Sometimes they may want the value to appear exactly as it does in the web report, so we force the cell to Text.  It is the scenario where we are not assigning the currency format ourselves, but we are allowing Excel to interpret the format (General), where this problem occurs.

**Comment by gingerjia** [comment]
@timbeese , thanks very much for your question.

I tried on my local PROD Excel, seems the issue not repro with your above gist:
![image](https://user-images.githubusercontent.com/62282034/128806564-5dadd039-b018-4998-b9bc-9f88ebd6a273.png)
The result:
![image](https://user-images.githubusercontent.com/62282034/128806601-9a1a2877-c5fc-4f3e-8b5e-e64346926ed6.png)

And my Excel version is:
![image](https://user-images.githubusercontent.com/62282034/128806637-5b913045-0ec6-4ac6-8946-f72dc8c5d761.png)
Can you help to upgrade your excel version and have a try again?

If still have issues, please let us know. Thanks!

**Comment by timbeese** [comment]
I'm using version 2107.  I tried to upgrade and it did something, but I'm still showing version 2107.  I'll have to check and see if my organization has some setting that's not letting me get the latest.  I'll see if I can get to the latest Office to give it another try.

**Comment by timbeese** [comment]
I upgraded to the beta channel and I'm using Excel version 2109 now.  I see the correct behavior, so it looks like whatever was causing that euro symbol to be lost has been fixed.  Thanks for the update.
