### ISSUE TITLE
Setting conditionalFormat lowerBoundRule and upperBoundRule for databar to automatic only puts bar in one cell of range

### ISSUE THREAD

**Issue by lynneosmith** [OfficeDev/office-js#2026]
We are trying to insert a report using office js into an Excel sheet. I have a range of numeric values in a column and have created a databar conditional format. I want to set the upperBoundRule and lowerBoundRule type to be Excel.ConditionalFormatRuleType.automatic. When I do that, only one cell in the range shows a databar. It is the cell with the highest value.
This happens on the web and desktop versions of Excel, but on desktop, I am able to look at the rule that was created for the range. It correctly shows as automatic. If I change a color in the "Edit rule" dialog and apply it, then the databars for the entire range show as expected, but they will not show after I programmatically set it to automatic.

I am able to successfully set the upperBoundRule and lowerBoundRule to number and specify the min and max values in the formulas. When I do my context.sync() in that case, the databar displays correctly.

I am able to reproduce this problem by modifying your conditional format databar sample in ScriptLab and  have the code below.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop and Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (16.0.14131.20278) 32-bit and the web build is 16.0.14331.35902
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome
 
## Expected behavior
When I select a range of data in a column and create conditional format databars on it, setting the lowerBoundRule and upperBoundRule to automatic, I expect the databars to show in every cell in the range, not just a databar on the cell with the highest value.

## Current behavior
When I have a range of cells with numeric values and create a conditional format databar and then set the upperBoundRule and lowerBoundRule to automatic, the only cell that shows a databar is the cell with the largest numeric values.
If I then (on desktop), go to Manage Rules, then edit the rule I created programmatically, I can see that it is set to automatic on the entire range as I expect it to be even though the bar is only displayed on the cell with the highest value. If I change the color of the databars in the Edit Rule window and apply that, then all the cells in the range show the databar as expected. I should see this behavior when I create the automatic rule programmatically as well.

## Steps to reproduce
In the script lab Basic Conditional Formatting sample, modify the applyDataBarFormat() function to add setting the lower and upper bound rules.

async function applyDataBarFormat() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getItem("Sample");
    const range = sheet.getRange("B8:E13");
    const conditionalFormat = range.conditionalFormats.add(Excel.ConditionalFormatType.dataBar);
    conditionalFormat.dataBar.barDirection = Excel.ConditionalDataBarDirection.leftToRight;
    
    conditionalFormat.dataBar.lowerBoundRule = { type: Excel.ConditionalFormatRuleType.automatic};
    conditionalFormat.dataBar.upperBoundRule = { type: Excel.ConditionalFormatRuleType.automatic};
    
    await context.sync();
  });
}

Next, run the sample, 
Choose "Add sample data".
Choose "Apply data bar format" so that the function above will run.

You will see that only the cell containing the value 5001 shows a databar.

On desktop, you can now go to Conditional Formatting on the ribbon, Manage Rules, and then edit the rule that is displayed that was just created. Only change the color of the databar and then Apply. You will see that all the databars display as expected now on all the cells in the range.

## Context
We are trying to insert a table from a report created by SAS Visual Analytics that our user is viewing in our task pane. We want the user to be able to insert the table in Excel to use Excel to work with their data. However, we are having to use the "number" rule for our databars and we prefer to use the "automatic" rule to get the representation we prefer from the bars values.

![databars](https://user-images.githubusercontent.com/57771416/128195908-753068ba-9e0c-42fd-8d1d-344264b1ea9f.JPG)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by gingerjia** [comment]
@lynneosmith, thanks very much for reporting the issue. I can repro it and opened a bug 5331677 to track the issue. I will update to you when have any progress.

**Comment by gingerjia** [comment]
@lynneosmith, the fix has been check-in. Will update to the thread when deployed to PROD. Thanks!

**Comment by gingerjia** [comment]
@lynneosmith We are doing a survey to understand the pain points of add-in’s developing experience. Would you mind to help fill this survey https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR5eAlIUFFQFHqE95qTMqQuVURVE4QkZPREoxOEk1TFEySDMyQTc0U0o0Ti4u ? It should take less than 5 minutes and will be supper helpful for us. Thank you!

**Comment by donlvMSFT** [comment]
The fix already been release with Office 16.0.14508.34850, please help verify.
I'd like to close this thread, thanks for discussion!
