### ISSUE TITLE
Outlook Add-in not available when viewing draft folder item

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#2029]
# Provide required information needed to triage your issue
It doesn't appear that any add-ins are available (see top ribbon -- and for the pinned Add-in, it says it is not supported for this message type) when viewing an item in the "Drafts" folder.

I cannot find any documentation on this limitation, so I am curious if it is a bug or if we may be missing something in our manifest to enable our add-in for drafts.

This only appears to be an issue on Desktop client (tested on Mac -- not sure on Windows). In the browser, I can pin my add-in and navigate to a draft in the drafts folder and it works as expected.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook 16.47
* Operating System: OSX
* Browser (if using Office on the web): N/A
 
## Expected behavior
The add-in should load and be usable when navigating to the drafts folder and selecting an item (automatically opens/loads if pinned).

## Current behavior
When navigating to the drafts folder and selecting an item, I am then unable to open any add-in from the top ribbon. If that add-in was previously pinned, then I see a message stating:

"Add-in isn't available"
"Add-ins can't be used with this type of message"

![image](https://user-images.githubusercontent.com/7740624/128378725-47720f8c-b346-4ab6-98b1-5cc49f6665a5.png)

![image](https://user-images.githubusercontent.com/7740624/128378810-509cb0de-5665-4910-956a-facc24837b0b.png)

**Comment by exextoc** [comment]
@cody-lettau You will have to select an email from Drafts folder and enter Edit mode for that mail to be able to use add-in or auto launch pinned addin.

**Comment by cody-lettau** [comment]
@exextoc thanks for the insight into what is supported. Much appreciated! Feel free to close this out if there will be no change to this functionality.
