### ISSUE TITLE
Excel host application version is not available in the API

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#2033]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

Some of our add-in's functionality depends on particular Excel features to be available (i.e. dynamic arrays, functions like LET() etc.).

Due to that, whenever a support request comes in, we need to explicitly request the product version from the customer, which consumes time.

Right now we cannot automatically detect which version the client is running: `Office.onReady()` promise only returns the platform type, but not the actual version.

Some of our customers are not on evergreen versions of Excel and some take their time updating, so it would be good to have a way of detecting the actual product version, through `Office.onReady()` or a standalone method like `Office.getPlatformVersion(): Promise<{ platform: Office.PlatformType, major: number, minor: number, patch: number }>`.

## Expected behavior

It is possible to detect the product version to provide better UX to the customer and hint about functionalities that are not available.

## Current behavior

It is not possible to detect the product version

**Comment by wh1t3cAt1k** [comment]
Dear MS team, hi there! Could we get an update please?

**Comment by SiruiSun-MSFT** [comment]
Hi Pavel,
We think Requirement Sets might be able to help you with this. We provide a system called requirement sets to help you determine whether an Office application supports the capabilities you need in your Office Add-in. Office Add-ins use requirement sets specified in the manifest or use a runtime check to determine whether an Office application supports APIs that an add-in needs.
The following links may help you：
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/add-in-commands-requirement-sets
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/office-versions-and-requirement-sets
Thanks，
Microsoft 365 Developer Platform Team

**Comment by wh1t3cAt1k** [comment]
@SiruiSun-MSFT thank you, that is somewhat helpful.

However for telemetry purposes we need to be able to identify the product version that is being used, to expedite support.
