### ISSUE TITLE
OSF.DDA.Error 5001 when calling OfficeRuntime.auth.getAccessToken()

### ISSUE THREAD

**Issue by edfowle** [OfficeDev/office-js#2034]
The latest beta channel builds on both mac and windows consistently throw an error when trying to retrieve an AD access token.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2109 (14329.20000)
* Operating System: Windows 10 Pro 21H1
 
## Expected behavior
OfficeRuntime.auth.getAccessToken() should return a Promise which resolves to the access token.

## Current behavior
OfficeRuntime.auth.getAccessToken() returns a Promise which rejects with the error:

```
{
   "name":"Internal Error",
   "message":"An internal error has occurred.",
   "code":5001
}
```

## Steps to reproduce
1. Use the Yeoman generator to create an Office Add-in that uses single sign-on ([docs](https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart))
2. Replace src/taskpane/taskpane.js with:
```
const ssoAuthHelper = require("./../helpers/ssoauthhelper");

Office.onReady((info) => {
	if (info.host === Office.HostType.Outlook) {
		document.getElementById("getGraphDataButton").onclick = ssoAuthHelper.getGraphData;
	}
	OfficeRuntime.auth.getAccessToken({
		allowSignInPrompt: true,
		allowConsentPrompt: true,
		forMSGraphAccess: true
	}).then(value => {
		console.log("yay!");
		debugger;
	}, reason =>{
		console.log(reason);
		debugger;
	});
});
```
3. Sideload the add-in manually ([docs](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing))
4. In Outlook, compose a new message.
5. In the message compose window, choose the Show Taskpane button in the ribbon to open the add-in task pane.
6. Right-click in the taskpane and click Inspect (or press Ctrl + Shift + I)
7. Right-click in the taskpane and click Refresh (or press Ctrl + R)
    The debug window should now be open and paused on the second debugger statement in taskpane.js.
8. Inspect the contents of the reason variable to see the error.

A copy of the source code for recreating this is attached.
[getAccessTokenBug.zip](https://github.com/OfficeDev/office-js/files/6955765/getAccessTokenBug.zip)

## Context
We are investigating adding more event-based activation functionality to our office-js outlook add-in.

## Useful logs
![image](https://user-images.githubusercontent.com/10868335/128735680-1274d59d-3e91-418e-8861-07bee279b3e5.png)

**Comment by exextoc** [comment]
A few questions to clarify to help us isolate the issue: 
1. Was the token call successful with the Yo Office template, before you updated the code? If not, do you get the same error?
2. Your call includes forMSGraphAccess, there is additional info here https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph to comment out forMSGraphAccess when sideloading (this is not the error you are seeing, but I thought to point this out)

**Comment by exextoc** [comment]
Update: We have an internal repro, and we are investigating this further.

**Comment by jargil** [comment]
@edfowle thanks for your report. This should be fixed in Office's Windows 16.0.14410 build or newer. Likewise 16.53.210810 or newer Mac build should have the fix.

**Comment by edfowle** [comment]
@exextoc thanks for picking this up so quick, looking forward to the fix

**Comment by ilbrando** [comment]
This works from my Windows Outlook, but not from the web version outlook.com. I use version 1.1 of the Office addin API (https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js).

Is there a fix for this in the web version?

**Comment by repl-mohan-krishna** [comment]
![Screenshot (140)](https://user-images.githubusercontent.com/86103151/186369916-9d88841a-24ae-4dac-b82e-c54f67c14cfe.png)
it is not working properly in web version of outlook email(outlook.office.com) 
is there any workaround for this?? @jargil @exextoc
