### ISSUE TITLE
Enable/disable ribbon button using shared runtime opens wrong taskpane when clicked

### ISSUE THREAD

**Issue by anant-matelabs** [OfficeDev/office-js#2036]
# Provide required information needed to triage your issue

## Your Environment

* Platform: Laptop MacBook 
* Host: Excel
* Office version number: 1.1.71
* Add-in runtime: Safari WebKit v1.0.0
* Operating System: macOS Big Sur v11.3.1
* Browser (if using Office on the web): NA

## Context
I'll give a minimal example. 
In my Excel add-in, I have two groups in a custom tab. Login button in first group, _some feature_ button in second group. Both buttons open their respective taskpanes. I want feature button to be disabled until the user logs-in in login taskpane. I use shared runtime to enable/disable as explained [here](https://docs.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands)
 
## Expected behavior

Once the button on manifest is enabled programatically from JS runtime in login taskpane, the other button (which is now enabled) first opens login taskpane, then opens correct taskpane when clicked again.

## Current behavior

After button on ribbon is clicked, it should open the correct taskpane as defined in manifest (and not the taskpane which was used as shared runtime).
i.e. first taskpane is opened when button for second taskpane is clicked in ribbon

## Steps to reproduce

1. Setup a simple Excel add-in as explained in **Context** above 
2. From first taskpane (with shared runtime), enable the second button on ribbon (opens second taskpane)
3. Close first taskpane
4. Open second taskpane
5. The first taskpane will load (issue)
6. When second taskpane is opened again, it opens fine

## Link to live example(s)

NA

# Provide additional details

NA

## Useful logs

No logs as the incorrect taskpane is opened.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by qinliuMSFT** [comment]
Hi @jeremy-msft , could you please have a look at this issue?

**Comment by anant-matelabs** [comment]
Do you have a repro?

**Comment by ElizabethSamuel-MSFT** [comment]
@anant-matelabs Are you still facing this issue?

@preethikakiru / @madhavagrawal17 Can you take a look?

Thanks.
