### ISSUE TITLE
Search method of body with matchWildcards not runs properly

### ISSUE THREAD

**Issue by frantwo** [OfficeDev/office-js#2037]
## Your Environment
Platform: Desktop Windows
Host: Word
Office version number: Microsoft® Word para Microsoft 365 MSO (16.0.14228.20216) 64 bits 
Add-in runtime: Microsoft Edge, Versión 92.0.902.67 (Compilación oficial) (64 bits)
Operating System: Windows 10 Pro, Version 20H2
Browser (if using Office on the web): NA
 
## Expected behavior
I hope to use the search method from body using wildcards and to read the results.

## Current behavior
This source code running properly in the past:

```
export async function testingProcessNotes() {
  await window.Word.run(async (context) => {
    try {
      const searchResults = context.document.body.search('bull*t', {
        matchWildCards: true
      })

      searchResults.load([
        'text',
        'parentContentControlOrNullObject',
        'parentContentControlOrNullObject/title',
        'paragraphs',
        'paragraphs/text',
        'paragraphs/tableNestingLevel',
        'paragraphs/parentTableOrNullObject'
      ])
      await context.sync()
      console.log('results:', searchResults)

      if (searchResults.items.length) {
        let myResult = searchResults.items[0]
        console.log('First item text: ', myResult.text)
      } else {
        console.log('NOT FOUND ITEMS!!')
      }
    } catch (error) {
      console.log('Error into testingProcessNotes:', error)
    }
  })
}
```
But now, the search using wildcard not returns nothing.

## Steps to reproduce
1.  I have one word document with this piece of words in which the word "bullet" is included:
![image](https://user-images.githubusercontent.com/11053804/128858304-699ca130-89c3-4578-a0e3-f21a5b1ac2c5.png)

2. Execute the previos source code.
3. This is the result of console:
![image](https://user-images.githubusercontent.com/11053804/128858567-0aed2e4d-d995-457a-805d-32bdbd5fd73f.png)

## Link to live example(s)
N/A

# Provide additional details
N/A

## Context
I am using Word Preview API.

## Useful logs
The log shared previously into the image of console.

**Comment by AbidRahman-MSFT** [comment]
Hey @frantwo, sorry about the delay. Thanks for posting your issue, we will investigate and get back to you as soon as possible.

**Comment by AbidRahman-MSFT** [comment]
Hey @frantwo - we recently made a change to no longer support `matchWildCards` as it is an invalid parameter for the search function. Replacing `matchWildCards` with `matchWildcards` will fix your issue (note the capitalization on the 'c').

**Comment by frantwo** [comment]
Thank you very much for your answer!
BR!
