### ISSUE TITLE
Officeatworks Plugin not available in Microsoft Office Apps

### ISSUE THREAD

**Issue by rernst-bag** [OfficeDev/office-js#2039]
## Expected Behavior

User should be able to see office at works Template / Content Chooser
It's not available in Word, Excel etc.

## Current Behavior

Content Chooser and Template Chooser is not available in Office Apps
Checkt the Plugin using the following link: https://help.officeatwork.com/en/articles/34-where-to-check-if-office-add-ins-are-deployed-to-the-user

Under ADMIN MANAGED I only get the message: No Plugins available:
![2021-08-10 14_45_32-E-Mail – Remo Ernst (Baggenstos) – Outlook und 3 weitere Seiten - Geschäftlich –](https://user-images.githubusercontent.com/83597386/128995447-0d09ac4b-f5b1-44d7-a4a4-e987913822b1.png)

## Steps to Reproduce, or Live Example
User is loged in with his Account which is synced to Office 365 / Azure
Tenant settings for the plugin is: deploy to everyone
Starting word in usercontext / starting Office apps

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

Tired to start office at works plugin

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Windows 10
* Host [Excel, Word, PowerPoint, etc.]: Word, Excel (Office 365)
* Office version number: Microsoft 365 MSO (16.0.13801.20442) 32Bit (See Screenshot Attached)
![2021-08-11 10_18_07-Window](https://user-images.githubusercontent.com/83597386/128995797-1b53bb3c-30a9-4642-82d4-afc26b486c0d.png)
![2021-08-11 10_18_17-Window](https://user-images.githubusercontent.com/83597386/128995915-189b1921-3502-4d47-b82c-9b70d9523521.png)

* Operating System: Microsoft Windows 10 21H1 (Build 19043.1110) 64 bit (See Screenshot Attached)
![2021-08-11 10_18_32-Window](https://user-images.githubusercontent.com/83597386/128995928-0fb6daf4-76e6-4065-a4ff-3281e859bb8c.png)

* Browser (if using Office Online): -

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by AkhileshShah-MS** [comment]
Hello! 

Is this issue specific to one user or for all the users to whom the add-in is deployed? 
If specific to one user, please try hitting 'Refresh' on admin managed tab in Get Add-ins or alternatively, restarting word/excel where you are not able to view the add-in. 

Please note that it may take upto 24 hours before the add-in is reflected to user's account.

**Comment by rernst-bag** [comment]
Hello!

We currently have it on every user.
Also tried to refresh it with restartingo the office app.

User is experiencing the issue for several days now

Many thanks in advance

Remo

________________________________



Remo 
Ernst, Engineer
A. Baggenstos & Co AG
Neugutstrasse 14, CH-8304 Wallisellen
phone:+41 44 832 66 66
direct:
+41 44 832 67 63
***@***.***
web: www.baggenstos.ch
Video: Wie Spross mit Cloud und Operation Care neue Optionen schafft
Folgen Sie uns auf:  Facebook / Twitter / 
LinkedIn / 
Youtube / 
Instagram
Von: AkhileshShah-MS ***@***.***>
Gesendet: Donnerstag, 12. August 2021 13:37
An: OfficeDev/office-js ***@***.***>
Cc: Remo Ernst (Baggenstos) ***@***.***>; Author ***@***.***>
Betreff: Re: [OfficeDev/office-js] Officeatworks Plugin not available in Microsoft Office Apps (#2039)


Hello!

Is this issue specific to one user or for all the users to whom the add-in is deployed?
If specific to one user, please try hitting 'Refresh' on admin managed tab in Get Add-ins or alternatively, restarting word/excel where you are not able to view the add-in.

Please note that it may take upto 24 hours before the add-in is reflected to user's account.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Foffice-js%2Fissues%2F2039%23issuecomment-897566095&data=04%7C01%7Crernst%40baggenstos.ch%7C504d10a393574cb65b7a08d95d8595e3%7C30e8aa2a7684446e9b95729febb4b786%7C0%7C0%7C637643650605416191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=x0HvpyaThHxCOMo9f77A0iN5TwFmBss5SFJCuQuwD3w%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT5ZQSWU5SZJCF6OYVUK7UDT4OXABANCNFSM5B53SHGA&data=04%7C01%7Crernst%40baggenstos.ch%7C504d10a393574cb65b7a08d95d8595e3%7C30e8aa2a7684446e9b95729febb4b786%7C0%7C0%7C637643650605416191%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ipuh%2BtzRtCFhWemfkjsxq0kO1w7SBjqRpDNEkKI8e2E%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crernst%40baggenstos.ch%7C504d10a393574cb65b7a08d95d8595e3%7C30e8aa2a7684446e9b95729febb4b786%7C0%7C0%7C637643650605426157%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=wpG4zH3PcP0lN4G6OLct6LbOIL%2FtAoFf8znjtLW4p4s%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Crernst%40baggenstos.ch%7C504d10a393574cb65b7a08d95d8595e3%7C30e8aa2a7684446e9b95729febb4b786%7C0%7C0%7C637643650605426157%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=LiJWpyD8teuMwALoMMK3DTC3cjW7%2BqUtGFQNyUccdfY%3D&reserved=0>.

**Comment by AkhileshShah-MS** [comment]
Hello! 

Thanks for confirming the same. For us to proceed further, please share your TenantId, one sample affected user id and fiddler trace when the user refreshes Admin Managed tab to addin-help@outlook.com.

**Comment by rernst-bag** [comment]
Hello!

Sorry for my late response due to vaccations.
I think we found the problem: The Users are not Exchange Online Enabled.

We have one user with Exchange Online License and Mailbox. On this User it is working as expected.

Are the plugins only be pushed / installed if the user has an Exchange Online Mailbox?

Many thanks in advance.
Remo
________________________________



Remo 
Ernst, Engineer
A. Baggenstos & Co AG
Neugutstrasse 14, CH-8304 Wallisellen
phone:+41 44 832 66 66
direct:
+41 44 832 67 63
***@***.***
web: www.baggenstos.ch
Video: Wie Spross mit Cloud und Operation Care neue Optionen schafft
Folgen Sie uns auf:  Facebook / Twitter / 
LinkedIn / 
Youtube / 
Instagram
Von: AkhileshShah-MS ***@***.***>
Gesendet: Freitag, 20. August 2021 10:28
An: OfficeDev/office-js ***@***.***>
Cc: Remo Ernst (Baggenstos) ***@***.***>; Author ***@***.***>
Betreff: Re: [OfficeDev/office-js] Officeatworks Plugin not available in Microsoft Office Apps (#2039)


Hello!

Thanks for confirming the same. For us to proceed further, please share your TenantId, one sample affected user id and fiddler trace when the user refreshes Admin Managed tab to ***@***.******@***.***>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Foffice-js%2Fissues%2F2039%23issuecomment-902527669&data=04%7C01%7Crernst%40baggenstos.ch%7Cad8071f5499d4ed7ee7708d963b47de6%7C30e8aa2a7684446e9b95729febb4b786%7C0%7C0%7C637650449123084693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=QF4W34o%2F8lgaXE5WFoDiiGG%2FQ%2FlHhgx%2BuZ7jDvw3B7E%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT5ZQSUFRRQLRD2Z4PLFPNDT5YG23ANCNFSM5B53SHGA&data=04%7C01%7Crernst%40baggenstos.ch%7Cad8071f5499d4ed7ee7708d963b47de6%7C30e8aa2a7684446e9b95729febb4b786%7C0%7C0%7C637650449123084693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rErdVqhjCODHGktLI5QUWYcw6pMMGpUE3sdyZW8Ds1Q%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crernst%40baggenstos.ch%7Cad8071f5499d4ed7ee7708d963b47de6%7C30e8aa2a7684446e9b95729febb4b786%7C0%7C0%7C637650449123094646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=dp6zB3XT8jp0CiSUhwC1%2FdO%2BVPisgVOoNJNw3FeoURo%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Crernst%40baggenstos.ch%7Cad8071f5499d4ed7ee7708d963b47de6%7C30e8aa2a7684446e9b95729febb4b786%7C0%7C0%7C637650449123094646%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=q5FGKuS6xboWpNZ5cp2pcxbAc3MMElgLiM4sL2uBytg%3D&reserved=0>.

**Comment by AkhileshShah-MS** [comment]
Thats correct. Add-ins are available only for users having exchange online mailbox.
