### ISSUE TITLE
Paragraph context sync issue in MAC

### ISSUE THREAD

**Issue by dinkom** [OfficeDev/office-js#204]
## Expected Behavior
`context.sync()` when loading paragraphs should work or at least provide an exception.

## Current Behavior
While this functionality normally works fine, I've ran into a document with a single paragraph that breaks Office.js. I don't understand why since there is no error message, it just silently fails.

## Steps to Reproduce, or Live Example
* Link to live example: https://gist.github.com/dinkom/9d007446537c879a7c618b0d211d433d
[Paragraph context sync issue.docx](https://github.com/OfficeDev/office-js/files/2231801/Paragraph.context.sync.issue.docx)

* Additional details:
  1. Error happens when paragraph's formatting is changed
  2. Error happens when paragraph is copy-pasted into a new document with keeping just the text

## Context
Since this happens for an at this point unknown reason, it is possible other users will experience this silent fail. In my specific case, it prevents some users from properly using the add-in I'm working on.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.15 (180709)
* Operating System: macOS High Sierra 10.13.6

**Comment by JuaneloJuanelo** [comment]
@dinkom interesting issue. just to confirm, this only happens in MAC? Tried on windows and it works ok.

**Comment by JuaneloJuanelo** [comment]
we reproed it on MAC, apparently a bug. we are tracking with 2462683

**Comment by JuaneloJuanelo** [comment]
update: issue resolved, most probably goes into the september update. btw the issue was in Mac and iOS., both platforms are fixed now.

**Comment by dinkom** [comment]
Great news, thanks!

**Comment by JuaneloJuanelo** [comment]
issue fixed!
