### ISSUE TITLE
Excel 2016 : Cannot get charts titles of a worksheet if one chart is a waterfall.

### ISSUE THREAD

**Issue by zoulou00** [OfficeDev/office-js#2041]
Hello,

Excel 2016 : Cannot get charts titles of a worksheet if one chart is a waterfall.

## Your Environment
* Platform: PC desktop,
* Host: Excel
* Office version number: Excel 2016 (16.0.5188.1000) 64 Bit
* Operating System: Windows 10
 
## Expected behavior
I would like to retrieve all charts titles of a specific worksheet.
As specified in the documentation, properties like chart.title is available in ExcelApi 1.1.
And my Excel version support ExcelApi 1.1, so I except to be able to read this property regardless the chart type.

## Current behavior
It works for charts like LineChart, BarChart, ColumnChart. 
But not for waterfall, I get an exception.
The exception is generated from excel-win32-16.01.debug.js file :
```
UnsupportedOperation: This operation is not supported
debugInfo.code: "UnsupportedOperation"
debugInfo.errorLocation: "Chart.title"
```

My code :
```javascript
...
worksheet.charts.load("items");
await context.sync();
worksheet.charts.items.forEach((chart) => {
   chart.load("title/text"); 
});
await context.sync();
...
```

Thank you for your help

**Comment by donlvMSFT** [comment]
Hi @zoulou00 , thanks for raising up this issue. 

Chart.Title is supported for ApiSet 1.1 for most of the chart types, but the support of API for some chart type are explored in Excel JavaScript API 1.9 requirement set, which includes: maps, box and whisker, waterfall, sunburst, pareto. and funnel. 

Please refer to https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-1-9-requirement-set for more information.

So waterfall chart is not supported on Office2016 as it's only support 1.1 APIs. If you need to develop add-ins supporting these charts, please set the requirement set check to at least 1.9.

**Comment by zoulou00** [comment]
Thanks @donlvMSFT !

Understood, nevertheless it would be helpful to have this info directly in the doc of the code.
Currently we have :
<img width="494" alt="image" src="https://user-images.githubusercontent.com/36133851/129413362-be93cd3a-926e-4695-b809-73557b086d88.png">
