### ISSUE TITLE
Office.context.mailbox.item.from/organizer.getAsync returns error for exchange 2016 In Outlook for Mac

### ISSUE THREAD

**Issue by olliesweez** [OfficeDev/office-js#2042]
## Your Environment
* Platform: Mac
* Host: Outlook
* Office version number: 16.52.808.0
* Operating System: MacOS 11.5.1
* Exchange on premise 2016

## Expected behavior
Office.context.mailbox.item.from/organizer.getAsync should return the sender of the email or the organizer

## Current behavior
Both return 
[Log] from result (outlook-mac-16.00.js, line 20)
Object

error: Object

code: 5001

message: "An internal error has occurred."

name: "Internal Error"

Object Prototype

status: "failed"

value: undefined

Object Prototype

## Steps to reproduce
Office.onReady(info => {
  if (info.host === Office.HostType.Outlook) {
    if (Office.context.requirements.isSetSupported('Mailbox', '1.8')) {
      if (Office.context.mailbox.item.from?.getAsync) {
        Office.context.mailbox.item.from.getAsync(r => console.log('from result', r));
      } else if (Office.context.mailbox.item.organizer?.getAsync) {
        Office.context.mailbox.item.organizer.getAsync(r => console.log('organizer result', r));
      }
    }
  }
}

**Comment by exextoc** [comment]
Hey @olliesweez ,

Are you seeing this issue in the new Outlook for Mac experience or the old Mac UI?

**Comment by olliesweez** [comment]
Hi @exextoc old Mac ui, I can't even use this particular email account (exchange on premise 2016) in the new ui.

**Comment by olliesweez** [comment]
@exextoc Has any progress been made on this issue?

**Comment by exextoc** [comment]
Really sorry about your experience. We are not able to reproduce the issue from our end.
Can you please help us with a sample manifest and a repro video (if possible) ?
You can send the manifest to _admin@a830edad9050849405E20081103.onmicrosoft.com_
