### ISSUE TITLE
Office.context.mailbox.item.location have problem on Mac new Outlook

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#2043]
If I manually set seral locations there. Then use Office.context.mailbox.item.location.getAsync get them all and save it to parameter 'A'. But when I trying set them back with parameter 'A', all locations will be glued together to become one location.

This problem is inevitable in the Mac new outlook. But it works fine on old version Outlook... 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.51 (21071101)
* Operating System: Mac
* Browser (if using Office on the web): ______
 
## Expected behavior
After set them back with parameter 'A', it should be still multiple locations. 

## Current behavior
All locations will be glued together to become one location.

**Comment by exextoc** [comment]
Hey @SWei1234 ,

Sorry for the wait. We are investigating this issue and will get back to you shortly.

**Comment by SWei1234** [comment]
Hi @exextoc 
Thanks for your effort. 
I noticed that MS have other location api like addAsync and removeAsync. Actually it can help improve this problem on Mac. But it can not works well on Windows. 
My need is to add and delete locations freely on both old and new Outlook. If we can, I hope we can do that.
Thanks

**Comment by exextoc** [comment]
Hey @SWei1234 ,

We are unfortunately not able to reproduce this issue. The steps we have tried are:
-> Adding two locations manually in Outlook for Mac.
-> Retrieving them through enhancedLocation.getAsync

We are able to get the response as expected. Could you share a code snippet of the code you're trying to execute. Also could you update to the latest release of Version 16.52 (21080801) and see if this issue still persists?

Also location.addAsync and removeAsync are from an older API set when there was only support for one text location. That will append the display names of all present locations and fetch them, or replace the existing locations with one singular text location.

**Comment by SWei1234** [comment]
Hi @exextoc 
Sorry for wrong title. It's location not enhancedLocation.
I updated to version 16.52 (21080801) but this issue still exist. 
My replicate step is:
1. manual input two(or more ) location like: Camtest and Deqing. Open dev tool->Console
2. Then use: `Office.context.mailbox.item.location.getAsync( { context: {value: 1}}, function (aa) {
                    bb = aa.value;
                });`
3. Then set them back, 'Office.context.mailbox.item.location.setAsync(bb, function (cc) {
                    console.log(cc);
                });'
The screenshot will be like:
![image](https://user-images.githubusercontent.com/15980696/130382851-6bc4a2a2-50ad-405f-bd2e-763023bc7464.png)
![image](https://user-images.githubusercontent.com/15980696/130382860-035c3a7d-b6b0-4fd9-9d68-883a90170ca7.png)

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding location. It has been put on our backlog. We, unfortunately, have no timelines to share at this point 

Internal tracking id: Office: 2285938

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
