### ISSUE TITLE
Office.context.mailbox.item.body.getAsync returns error 9030 APICallFailedDueToItemChange

### ISSUE THREAD

**Issue by masha-mariya4** [OfficeDev/office-js#2044]
## Your Environment
I'm working on Outlook desktop add-in on Mac (High sierra 10.13.6)

## Current behavior
Each time when I open taskpane and run request body.getAsync returns the error "APICallFailedDueToItemChange". The detail of this error is {name: "APICallFailedDueToItemChange", message: "The selected item has been changed.", code: 9030}

code: Office.context.mailbox.item.body.getAsync(Office.CoercionType.Html,  (result) => {..})

I tried to recall the getAsync, but the error will happen persistently. The only way is switching to another email.

## Reproduce steps: 
1. Create any outlook add in which try to get the email body 2. after add-in loaded, reload the add-in window 3. Once the 9030 error happened, those code will always trigger the same error until I switch to another email

## Expected behavior
The request getAsync should be successed for first opened mailbox item

**Comment by masha-mariya4** [comment]
also the same problem was with request Office.context.mailbox.getCallbackTokenAsync((asyncResult) => {..

it returns error for first mailbox item:

diagnostics: {InvokeCodeResult: -2147467259}
error: Error {name: "AccessRestricted", message: "Internal error of protocol: \"-2147467259\".", code: 9017}
status: "failed"
value: undefined

and successed when switch to another emai

**Comment by exextoc** [comment]
Hey @masha-mariya4 ,

Apologies for the delay. Can you tell us the build version number of your Outlook for Mac and whether you are on the New Outlook for Mac experience or the Old Outlook for Mac UI.

Also, I would want to understand your scenario better. What exactly do you mean by re-loading the add-in window- Is your add-in Pinned and you're switching email items?

**Comment by masha-mariya4** [comment]
Hi @exextoc! I use Outlook v16.42(20101102), I guess it old Outlook. My add-in pinned, but almost everytime when I open add-in and run request body.getAsync for first message, it returns errors. When I said 're-loading the add-in window' I mean that I close it and open again, then I see the same error until I switch my pinned add-in to another email.

**Comment by exextoc** [comment]
Hey @masha-mariya4 ,

We are still unable to understand your scenario. Can you list down the repro steps for the issue, and what you see is the behaviour? Added screenshots would also be really helpful.

**Comment by masha-mariya4** [comment]
Hi @exextoc 

When I open my add-in in outlook desktop on mac and run request body.getAsync:

Office.onReady(() => {
..
     Office.context.mailbox.item.body.getAsync(Office.CoercionType.Html,  (result) => {
     ...[here result = undefined and got error {name: "APICallFailedDueToItemChange", message: "The selected item has been changed.", code: 9030}
     })
})  
   
   Then as my add-in is pinned I can switch email item in outlook and when I change it ( and for every next switching of email ) everything works perfect!
   
   But if I close add-in and than open it again, error will appear again for this Office.context.mailbox.item.body.getAsync until I switch to another email. 
   
   Hope it'll help you

**Comment by exextoc** [comment]
@masha-mariya4 we are unable to reproduce this issue. Could you please provide us a sample add-in through email at OutlookAddins@M365x693897.onmicrosoft.com

**Comment by masha-mariya4** [comment]
@exextoc sorry, I can't share my addin code because of intellectual property policy

**Comment by exextoc** [comment]
Please share a **_sample add-in_** where the issue can be reproduced. 
This can be handy in building an add-in: https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/project-quickstart

**Comment by exextoc** [comment]
@masha-mariya4 , a gentle reminder to share the add-in or a sample add-in where the issue can be reproduced to               OutlookAddins@M365x693897.onmicrosoft.com. 

And can you please update the outlook and try it in the New Outlook for Mac. You can switch by using the toggle on the top.
Link to the new Outlook: https://support.microsoft.com/en-gb/office/the-new-outlook-for-mac-6283be54-e74d-434e-babb-b70cefc77439

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
