### ISSUE TITLE
Excel Add-in broke suddenly

### ISSUE THREAD

**Issue by gitty-git-git** [OfficeDev/office-js#2046]
# Provide required information needed to triage your issue
I have a JavaScript Add-in for Excel that has a custom function. Just in the past week it seemed to have broken for most of my users (I haven't tinkered with it for a while). Users get "#BUSY!" for my custom formula. In the online version at office.com, users continually have to click a "trust this add-in" - and that is new as well. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___PC desktop, Mac, Office on the web___
* Host [Excel, Word, PowerPoint, etc.]: __Excel____
* Office version number: __Latest____
* Operating System: ______
* Browser (if using Office on the web): __Chrome____
 
## Expected behavior

Expect the #Busy! to go away but it doesn't. In the online version, I expect to not have to trust the add-in everytime I use it or refresh the page.

## Current behavior

#BUSY! and have to trust the add-in

Suggest to rollback Excel's latest update(s).

## Steps to reproduce

1. ___Load and Add-in that has a custom formula___
2. ____See the above errors__
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

Yes. It has affected many, many users so I know it isn't just my environment.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by qinliuMSFT** [comment]
Thank you for logging this issue, I think we need more details to properly route your issue. Would you mind providing us more details? For example: 
   Steps to reproduce or live example,
   Your environment(Office version number),
   Useful logs.

**Comment by keyur32** [comment]
Hi @gitty-git-git , checking in. Can you provide more details or repro steps? THanks
