### ISSUE TITLE
publish a new excel addin error

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#2047]
we publish a new version of excel addin, it's error for us
1、we add SharedRuntime for our add-in xml :
![image](https://user-images.githubusercontent.com/3963826/129310658-33d1ff08-3ead-4315-9aa8-df68b53420bf.png)
![image](https://user-images.githubusercontent.com/3963826/129310684-6e5a9240-2d2d-47d2-832c-4684b4d236f8.png)

in excel it's ok.
and we validation our manifest,it's passed.
![image](https://user-images.githubusercontent.com/3963826/129310783-964ea41c-10b7-42fb-8e94-67d837f4ed59.png)

but in web excel it's show error
![image](https://user-images.githubusercontent.com/3963826/129310815-5b4c0527-d243-4bf2-b92e-da8fa7f30538.png)

we publish the app store ,also give us some feedback
![image](https://user-images.githubusercontent.com/3963826/129311029-a72502ae-0952-4078-8b6c-620a4a9b6d9b.png)

we also have used office.js 1.1  

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: _web_____
* Host [Excel, Word, PowerPoint, etc.]: __excel____
* Office version number: ______
* Operating System: ____windows__
* Browser (if using Office on the web): __ie and firefox____

**Comment by keyur32** [comment]
Assigning to @lumine2008  who I believe was following up offline on this issue. Thanks.

**Comment by gingerjia** [comment]
@jeremy-msft, seems it's load add-in manifest failure. Could your team help to take a look at it? Thanks!

**Comment by madhavagrawal17** [comment]
@dinglicoding, Could you please share the details on PrimaryCommandSurface Extension Point from your XML manifest? We need to check the details of your manifest to investigate this issue.
