### ISSUE TITLE
UI libraries are not supporting IE 11 anymore - Outlook Office Add-ins

### ISSUE THREAD

**Issue by mohamadAtlassian** [OfficeDev/office-js#2048]
Hello there, 

I am working on outlook office addin product. The product must be installed and supported on all Outlook Desktop version (2013 >). However, most of UI libraries won't support IE 11 anymore. What we should do in this case ? our product is not work on outlook desktop 2013, 2016 and 2019. Is there a way to open another WebView like webview2 instead of IE 11 ?

Specs : 

- Windows 10 
- Outlook® for Microsoft 365 MSO (16.0.14228.20216) 32-bit 
- Outlook Office Addin
- UI Library : Atlaskit by Atlassian

Screenshot :
![image](https://user-images.githubusercontent.com/88886636/129351986-5e734c28-bb87-4692-87a6-5d7fd4c9225e.png)

**Comment by ElizabethSamuel-MSFT** [comment]
@mohamadAtlassian Thanks for asking about this.

@exextoc Can you investigate and advise?

Thanks.

**Comment by exextoc** [comment]
To clarify, is your addin using Atlaskit by Atlassian, and that IE11 is no longer supported by Alaskit, and so addins do not run in some Outlook + Windows version combinations? You mentioned Outlook 2013, 2016, 2019, as well as listing Outlook version 16.0.14228.20216, could you be a bit more specific on the versions of Outlook + Windows that your addin does not work in?

In case it helps, these 2 links describe the versions of Office for which newer webviews are used.
https://developer.microsoft.com/en-us/office/blogs/microsoft-edge-webview-for-office-add-ins/
https://developer.microsoft.com/en-us/office/blogs/announcing-webview2-for-office-add-ins-platform/

**Comment by mohamadAtlassian** [comment]
Now, I am using Outlook version 16.0.14228.20216, however I also tested the application on outlook 2013 and 2019 and get a blank page. Atlaskit is no longer supporting IE, but Microsoft itself will stop supporting IE. Microsoft edge webview is only for office greater than 16.0.11629. I've many clients that are not using this office version, so is there any other way ?

**Comment by exextoc** [comment]
There isn't, except to use a UI library that is compatible on IE on those versions. 

Outlook/Office has already been upgraded with newer versions that support non-IE rendering engines. Older versions (2013/2016) of Office/Outlook will not be upgraded to support WebView. Those users will need to upgrade Office to versions that support the newer Webviews. 

It is possible that you could obtain older versions of the Libraries that do support IE, and serve an older version of your add-in only to users that are on older versions. (for 2013, and 2016 this could be accomplished via VersionOverrides)

https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins
