### ISSUE TITLE
typings file could be listed in package.json

### ISSUE THREAD

**Issue by troywweber7** [OfficeDev/office-js#205]
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

this would allow easy import of the types CommonJS style (I think)

**Comment by lindalu-MSFT** [comment]
If you're still interested in add this feature, please go to our new [Ideas forum](https://aka.ms/m365dev-suggestions) and click **Submit an Idea**. If there's enough interest (votes), we will follow up with you there and add it to our feature request backlog. Thanks, lindalu
