### ISSUE TITLE
About VSTO implementation undo operations

### ISSUE THREAD

**Issue by JunYuZhang0812** [OfficeDev/office-js#2050]
##Content
I started using VSTO recently and found that if I modified Excel using code, I could not undo it.  Looked for many places but did not find a suitable solution.  You have to figure out how to undo it.  The current method is to record the current selection in SheetSelectionChange, put it in the Stack, and backtrack when it needs to be undone.  The downside to this solution is that SheetSelectionChange does not listen to old content when copying into the table from elsewhere.  So how do I do undo in C#?  Thank you for your reply  

## My Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows10

**Comment by Rick-Kirkham** [comment]
@JunYuZhang0812  This repo is for Office Web Add-ins which are something different from Office VSTO add-ins. See [How are Office add-ins different from COM and VSTO add-ins](https://docs.microsoft.com/office/dev/add-ins/overview/office-add-ins#how-are-office-add-ins-different-from-com-and-vsto-add-ins). For questions about VSTO add-ins please go to stackoverflow.com and be sure to tag your question `vsto`.
