### ISSUE TITLE
[Word Online] Content control tag cannot be updated when re-opening in Onedrive 

### ISSUE THREAD

**Issue by tranhuyentran23** [OfficeDev/office-js#2052]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Content control tag cannot be saved successfully when re-opening document in Onedrive then doing some updating.

## Your Environment
* Platform: Office Online
* Host: Word
* Office version number: 16.0.14413.41001
* Operating System: Windows 10
* Browser: Chrome
 
## Expected behavior
Content control tag can be updated successfully when re-opening in Onedrive

## Current behavior
Content control tag cannot be updated

## Steps to reproduce
1. Create a new Word document and insert a content control
2. Close this document then go to OneDrive and open this document again
3. Modify content control tag
4. Download this document and check tag value (or close this document and open again)
5. Observe the content control tag cannot be updated succesfully

![MogsO5juOd](https://user-images.githubusercontent.com/89008454/129545768-576c9166-9d75-4b70-8786-be9fb9f9a611.gif)

Script Lab: https://gist.github.com/tranhuyentran23/49d5eb99b905f896d774eda311f2ed3a

**Comment by qinliuMSFT** [comment]
Hi @tranhuyentran23 , thanks for reporting this issue. I tested your gist on Office Online version 16.0.14404.41000, and it's not repro. Could you please try your scenario on latest Office Online?

**Comment by tranhuyentran23** [comment]
Hi @qinliuMSFT, thanks for your feedback, I tried with the latest Office Online 16.0.14413.41001
I created a new document, 
then inserted a content control
then closed this document and opened it again in Onedrive to modify this content control
then closed this document and opened it again to check the tag value
and I still saw that issue happens. Could you help to test again? Thanks!

![F6WJuMnxUq](https://user-images.githubusercontent.com/89008454/129828854-b669acca-8c9c-4a9e-8adc-6c7f66a76b8b.gif)

**Comment by qinliuMSFT** [comment]
Hi @tranhuyentran23, the issue is reproducible, it has been put on our backlog VSO#5351861, will let you know once we have any updates.
