### ISSUE TITLE
Office Add-in stopped opening in Excel Online

### ISSUE THREAD

**Issue by xinchiyang-venacorp** [OfficeDev/office-js#2054]
# Provide required information needed to triage your issue
Our Vena add-in opens automatically when you open a Vena file. However on August 10th onwards it stopped opening automatically on Excel Online.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): Edge or Chrome
 
## Expected behavior

I expect the Vena Connector add-in to load automatically (and if it's not set up for it to ask me to Trust this Add-In) in Excel Online.

## Current behavior

It stopped doing so on August 10th. The add-in no longer loads automatically on Excel Online.

## Steps to reproduce

1. Download [adhoc_test.xlsx](https://github.com/OfficeDev/office-js/files/6996188/adhoc_test.xlsx)
2. Open it with desktop excel, notice the add-in pops up.
3. Upload it to Office online and open it with Excel Online, there's no add-in pop up.

## Link to live example(s)

N/A

# Provide additional details

N/A

## Context

We've allowed our Vena Connector to open in Excel Online since the beginning of time. It specifically serves the purpose of allowing users to use Excel Online instead of Desktop Excel.
This is a live production issue impacting our customers (I haven't tested on Mac, that's our majority customer use case. I will do that and report back. For windows this impacts our presales team which can no longer demo excel online for our prospects).

## Useful logs

Test file provided in repro steps.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by xinchiyang-venacorp** [comment]
I was able to confirm we can reproduce this on Mac with Excel Online as well.

**Comment by qinliuMSFT** [comment]
Hi @jeremy-msft, it seems related to Shared Runtime, could you please have a look at this issue?

**Comment by keyur32** [comment]
Thank you @xinchiyang-venacorp  for the report. It is under investigation and internally tagged as issue #257763895.  Can you share the Mac build number?

**Comment by xinchiyang-venacorp** [comment]
@keyur32 
Mac build: 16.52 (21080801)
Windows build: 2102 (13801.20294)
Excel Online build: 16.0.14411.35900

However we've been able to reproduce this reliably on any computer we've tried so far.

**Comment by keyur32** [comment]
Old issue but closing out based on internal status of #257763895 (of it not being able to be reproducible anymore). Please re-open if this is still an issue.
