### ISSUE TITLE
Outlook: System UI is showing scrollbar from Appointment/Email overlayed on top of plug-in

### ISSUE THREAD

**Issue by bconners1005** [OfficeDev/office-js#2056]
We recently updated our system to be more inline with flex CSS styling vs. using more strict and rigid versions of different displays as we did in the past.  Once this change was made we noticed that the scrollbar that exists for the Appointment/Email was bleeding into the foreground above the plug-in pane.  It is not interactive (in that it does not allow scroll) and it is not directly accessible to target (you need to traverse the HTML for the 'background' pane of the Appointment/Email to access it).

Being the plug-in is served via an iFrame we don't have direct access to the css to try and augment it from the plug-in itself to fix the issue.

If you target the most outside div of the plug-in (outside of the iFrame) from Chrome or Edge you can change the z-index of the pane to at least 600 and then the scrollbar goes back where it should be.

Any advice on how to rectify this would be greatly appreciated.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: All (though main testing was on Office on the Web)
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: N/A
* Browser (if using Office on the web): Chrome
 
## Expected behavior

The system should be showing the flexed plug-in in front of (with a higher z-index on the outside div) the scrollbar from the Appointment/Email/

## Current behavior

The system shows the scrollbar from the 'background' item of the plug-in overlayed on top of the plug-in iFrame.

## Steps to reproduce

1. Create a basic plug-in using flex design on divs
2. Open manifested plug-in on Outlook on the Web
3. Verify the scrollbar is showing the extra scrollbar

## Context

It is obstructing the UI, but as it is not interactive it is more of a nuisance on the UI than a technical issue.

## Useful logs

- [ ] Console errors
- [X] Screenshots
- [ ] Test file (if only happens on a particular file)

![Screen Shot 2021-08-13 at 5 40 25 PM](https://user-images.githubusercontent.com/35665158/129760539-bcfe924c-3088-4e4d-82b3-0f436ecd78c6.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Hey @bconners1005 ,

Does this issue still exist if the parent div of the add-in is set to:
```
position:absolute;
overflow: hidden;
height: 100vh;
```
Can you share a small HTML snippet (perhaps from `<body>` tag and everything inside along with the CSS styles)?

**Comment by bconners1005** [comment]
Hey @exextoc 
   This does fix it, but it isn't really the best fix given the situation is taking it into absolute is causing side effects to other code down the chain given we're removing it from the original context.

   What I did instead, and does work as well, is setting the z-index to 600 because I keep the divs in flex without having to change to absolute which doesn't break context.
  
  Reason we didn't do this originally was the fact that the core scroll bar was outside of the iFrame so we couldn't access it out of the jump.

  As this closes it I'm going to ahead and set this to close.

  Thanks,
