### ISSUE TITLE
How to get the addin to ask for additional permissions

### ISSUE THREAD

**Issue by EdwinStraver** [OfficeDev/office-js#2057]
I have an Excel addin that takes advantage of SSO to log the user into my app.

I now would like to add some permissions (scopes) to access the users Teams info, using the graph api.
I added the new scopes and permissions in the portal; i added the scopes to the manifest file, and i added them to the actual REST calls.

But I can not get the add-in to ask the user for the new permissions; how can I "reset" the addin, so it will ask the user for the new permissions required?
At the moment, it simply does not ask and when I eventually make my REST call, it fails, as expected with:
"The request was denied because one or more scopes requested are unauthorized or expired. "

**Comment by Rick-Kirkham** [comment]
@EdwinStraver Please show the line of code that calls getAccessToken so we can see what parameters you are passing. 

Assigning to @jargil

**Comment by EdwinStraver** [comment]
Initially, in the client addin, I call:
OfficeRuntime.auth.getAccessToken({ allowSignInPrompt: true, allowConsentPrompt: true, forMSGraphAccess: true }).then(function (accessToken)

This passes me an accestoken (a bootstraptoken), and then I call my server, passing the token in the authorization header. On the server, I have this code:
string[] token = Request.Headers["Authorization"].Split(' ');
 UserAssertion userAssertion = new UserAssertion(token[1]);
ConfidentialClientApplicationBuilder clientBuilder = ConfidentialClientApplicationBuilder.Create(Helpers.getSettingAsync("ida:ClientID").Result);
            clientBuilder.WithClientSecret(Helpers.getSettingAsync("ida:Password").Result);
            clientBuilder.WithAuthority("https://login.microsoftonline.com/common/oauth2/v2.0");

            ConfidentialClientApplication clientApp = (ConfidentialClientApplication)clientBuilder.Build();
            string[] scopes = { "Team.ReadBasic.All", "Files.ReadWrite.All", "Channel.ReadBasic.All", "ChannelMessage.Send" };

 var authResultBuilder = clientApp.AcquireTokenOnBehalfOf(scopes, userAssertion);
            AuthenticationResult authResult = null;
            try
            {
                authResult = await authResultBuilder.ExecuteAsync();
            }
            catch
etc.

Thank you!

**Comment by jargil** [comment]
@EdwinStraver  - The getAccessToken (SSO) API only supports prompting for profile consent. You can read more about this in our documentation:
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph#distributing-sso-enabled-add-ins-in-microsoft-appsource

If your add-in will be deployed by tenant admins, they'll be granting your add-in permission to other scopes during deployment. If your add-in will only be distributed through AppSource, please see the link above for alternatives.
