### ISSUE TITLE
Drag does not work inside content panes in PPT presenter mode

### ISSUE THREAD

**Issue by tsardy** [OfficeDev/office-js#2059]
The mouse events used by the drag actions are incorrectly fired in PowerPoint Presenter mode (inside content panes).
The root seems to be an unwanted event fired automatically in presentation mode by PowerPoint.
Looks like PowerPoint on mouse down fires all 3 right away: mousedown, mouseup, click. 
It used to work in d the past but recently stopped working.

## Your Environment
Platform PC desktop,
Host  PowerPoint,
*21H1 OS-build: 19043.1110, Windows Feature Experience Pack 120.2212.3530.0,
WebView2 version: 91.0.864.70

 
## Expected behavior
drag events should work similarly to edit mode

## Steps to reproduce
Use the enclosed PowerPoint file. Open it in ppt, and try to move the rectangle, it should work.
Now go to presenter mode and attempt to move the rectangle. it will not work.
It is the same for all content panes, including our add-in where charts should be draggable.

[drag problem in presentation mode.pptx](https://github.com/OfficeDev/office-js/files/7006169/drag.problem.in.presentation.mode.pptx)

## Context
the issue blocks the main functionality of our add-in (being able to interact with charts and change their values by dragging them. it is a no-go for us now.

**Comment by lliu113** [comment]
@tsardy - thanks for reporting this bug! I was able to repro with the attached file, thanks for providing it. 
Internal bug number: 5377914

**Comment by Dengshan2018** [comment]
@tsardy  thanks for reporting the issue. How Add-in will use drag&drop during slide show?

**Comment by tsardy** [comment]
@Dengshan2018 it is more like grab-drag-release. Our users can manipulate chart values in presentation mode by dragibg chart points. More about it can be found here: www.activegraf.com

**Comment by Dengshan2018** [comment]
@tsardy working on the fix.

**Comment by 10142904** [comment]
@Dengshan2018  Has it been fixed ? I just tested and it does seem to be fixed, my ppt version is Microsoft 365 MSO (16.0.14326.20262) 32 bit，I tried to upgrade and he said it was already the latest version, ppt's subscription channel is version 2018 Current Channel(preview)

**Comment by Dengshan2018** [comment]
The fix is not out yet.

**Comment by 10142904** [comment]
> The fix is not out yet.

i see, thanks!

**Comment by mike-thompson-day8** [comment]
@Dengshan2018 
Just out of interest, assuming the fix was completed now, how long are the release cycles?  How long before a fix is released? 

I ask because I'm not sure if we are talking about weeks or months or years.  (I'm assuming not "days")

I guess it would go through a Beta channel release first.  Then GA?  If possible approximate timings on both would be interesting. 

OR are you still waiting for the Edge team?  Perhaps the timing is completely out of your hands?

I won't hold you to anything here.  I'm just curious about an approximate, vague guess.

**Comment by Dengshan2018** [comment]
@mike-thompson-day8 this fix is fully under the control. should be weeks. will publish the version which has the fix.

**Comment by 10142904** [comment]
i just updated my ppt to 16.0.14430.20044 and find the bug has been fixed, good news! thanks very much!

**Comment by Dengshan2018** [comment]
The issue should be fixed in Beta 16.0.14511.*
CC preview 16.0.14430.20088

**Comment by tsardy** [comment]
thank you @Dengshan2018 !
