### ISSUE TITLE
End of Line for manifest.xml

### ISSUE THREAD

**Issue by zoulou00** [OfficeDev/office-js#2060]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hello,

Are they any recommandations regarding the eol of the manifest.xml file ?
Until now I deploy directly  from my local computer to a shared folder, the end of line of file is CRLF.

As I would like to deploy from my CI/CD from a linux server, the eol of the file is now LF.
My target is to publish the add-in to the Microsoft store, is it a problem if the eol is LF ?

Thank you

**Comment by ElizabethSamuel-MSFT** [comment]
@zoulou00 Apologies for the late response.

@JuaneloJuanelo Do you know if this will cause a problem with the Store submission?

Thanks.
