### ISSUE TITLE
GetSelection().ContentControls is always empty on Word for Mac, but works on Online Word.

### ISSUE THREAD

**Issue by richie5um** [OfficeDev/office-js#2062]
Trying to get the ContentControls for the current selection (or, more specifically, where the cursor is) fails on Word for Mac, but works fine in Online Word.

I've had to switch to use parentContentControl, but this isn't 100% if that range belongs to multiple content controls (at least, it does in content-control hierarchy - i.e the immediate content control could belong to a parent content control).

Reproduced in this Gist:
https://gist.github.com/richie5um/8edf779e93f6757729c753a76762fd42

## Expected behavior
To get all content controls for the current range.

## Current behavior
Is empty on Word for Mac.

## Steps to reproduce
https://gist.github.com/richie5um/8edf779e93f6757729c753a76762fd42

## Link to live example(s)
https://gist.github.com/richie5um/8edf779e93f6757729c753a76762fd42

**Comment by AbidRahman-MSFT** [comment]
Hey @richie5um, thanks for posting the issue. I tried to reproduce the issue with your gist but was unable to do so. 

Here's a video showing my attempt at reproducing on Word on Mac:


https://user-images.githubusercontent.com/53581099/130653561-91ad1dbe-0ac9-4d67-92a2-17f8ec8307cb.mov
