### ISSUE TITLE
Excel file with Centralized Deployment Add-In crashes when file is opened with OMEX-store Add-In installed

### ISSUE THREAD

**Issue by AlexPhilippov** [OfficeDev/office-js#2064]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Our clients use [Knoema Data Finder Add-In ](https://appsource.microsoft.com/en-us/product/office/wa104379640?tab=overview) via Centralized Deployment - EXCatalog-store add-in.
When a file created with EXCatalog add-in is opened on a machine with OMEX-store add-in the Excel process occupies the one CPU core and after a couple of minutes crashes.
The same occurs when clients with EXCatalog add-in installed open a file with OMEX-store add-in.

## Your Environment
PC, Excel, Microsoft 365 Version 2107(Build 14228.20250) 64 bit, Windows 10
 
## Expected behavior
Excel should not crash.

## Steps to reproduce
1. Install Knoema Data Finder Add-In 
2. Open attached EXCatalog Add-In.xlsx
3. Check Excel CPU usage stats - it constantly uses CPU
4. Wait a couple of minutes, click on any cell in file - Excel crashes

## Context
We exchange files with our clients and different types of add-in store settings cause occasional Excel crashes on both ends.
Also, we have software that prepares xlsx files via open-xml that includes OMEX-store settings.  Opening such files on a machine with EXCatalog add-in results in displaying "Trust this add-in" as if add-in was not installed. Please, let me know if it will require a separate ticket. But after some steps, this leads to the situation described in this issue.

Found the following difference in files created different types of Add-In:
webextension settings for EXCatalog add-in:
`<we:reference id="1ecd6e51-cf73-472a-8789-7abde276e4dc" version="3.3.1.60" store="EXCatalog" storeType="EXCatalog"/><we:alternateReferences><we:reference id="WA104379640" version="3.3.1.60" store="" storeType="OMEX"/></we:alternateReferences>`
webextension settings for OMEX add-in:
`<we:reference id="wa104379640" version="3.3.1.4" store="en-001" storeType="OMEX"/><we:alternateReferences><we:reference id="wa104379640" version="3.3.1.4" store="en-001" storeType="OMEX"/></we:alternateReferences>`

## Useful logs
File for reproducing: [EXCatalog Add-In.xlsx](https://github.com/OfficeDev/office-js/files/7014540/EXCatalog.Add-In.xlsx)
Windows error logs with APPCRASH: [Excel crash.zip](https://github.com/OfficeDev/office-js/files/7014546/Excel.crash.zip)

**Comment by Rick-Kirkham** [comment]
@massonj If you're not the right person for this, can you suggest who is?

**Comment by massonj** [comment]
Thank you for the high quality bug report. We have been able to reproduce this issue internally, and it appears to be a bug within the product, which we are tracking internally as bug 5358792, which our engineers are investigating. Unfortunately, we do not have a suggested workaround at this time, other than avoiding this specific scenario. 

Thanks

Jim

**Comment by ElizabethFerriss** [comment]
Is there an estimated timeline or way that we can track bug 5358792?

**Comment by ElizabethFerriss** [comment]
Is there any update or suggested workaround?

**Comment by grangeryy** [comment]
Hey we are still investigating and have found some clues on the root cause. Will drive a fix as soon as possible. And unfortunately we don't have a work around suggestion at current.

**Comment by AlexPhilippov** [comment]
Hi @grangeryy, it's been two weeks. Any update on this?

**Comment by grangeryy** [comment]
@madhavagrawal17  do you have any update on this BUG 5358792?

**Comment by madhavagrawal17** [comment]
Sorry for the delay. I was finally able to find the root cause for this issue. But I think it will take some time to fix this issue properly. The only workaround I have is to uninstall the Omex Add-in from the machine if a Workbook with ExCatalog is opened.

**Comment by donlvMSFT** [comment]
Hi @AlexPhilippov , seems this thread not updated for a long while, I want to confirm that do you still hit this issue recently?
