### ISSUE TITLE
Custom function argument descriptions are not available at all in Excel Online

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#2065]
On the desktop platform, when one uses the "Fx" (insert function) dialogue on Windows, after selecting a function, there is also a "Function Arguments" dialogue that allows one to review 

a) The list of function arguments
b) Their descriptions
c) Pre-evaluate formula result

Screenshot from Excel Desktop for Windows:

![image](https://user-images.githubusercontent.com/5159662/130078161-79cd695b-3736-483a-9a8e-95a86fd23365.png)

This is currently not available in Excel Online, as after selecting the function, the user is immediately returned to the spreadsheet.

As such, it is **not possible to review argument descriptions at all** in Excel Online, because the argument tooltip doesn't list them either:

![image](https://user-images.githubusercontent.com/5159662/130078772-40279847-e20e-4cd2-a2cc-a75b24cdbe17.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 
* Operating System: Windows
* Browser (if using Office on the web): Edge Chromium latest
 
## Expected behavior

It is possible to review custom function argument descriptions somewhere.

## Current behavior

It is not possible to review custom function argument descriptions anywhere!

**Comment by Rick-Kirkham** [comment]
I have assigned this issue, but in the meantime could you clarify whether your issue is about an end user working with Excel Online or whether it is a developer issue for a developer who is creating custom functions.

**Comment by wh1t3cAt1k** [comment]
Hi Rick, the problem is on the user interface - the part for argument descriptions from CF metadata is essentially useless in Excel Online because there is nowhere that the user can review those descriptions.

I apologise if it's the wrong place for the ticket as I am not sure where else I could put this feedback - UserVoice for Excel seems stale and our suggestions don't appear on the platform anymore.

**Comment by grangeryy** [comment]
To show the tip of argument  should be supported in Web already. I've opened a bug for this: 5356916

**Comment by grangeryy** [comment]
@wh1t3cAt1k  can you also share with us the SessionID ?

**Comment by wynntee** [comment]
@wh1t3cAt1k , in Excel online, the "Fx" button is under the "Insert" tab.  This is different from Excel desktop where it's under the "Formulas" tab.

**Comment by xiaochunms** [comment]
@wh1t3cAt1k I think the parameter description is here:
![image](https://user-images.githubusercontent.com/1261601/130179541-69e931d5-bfef-4749-9c4c-4a1ded9f8bce.png)

However if you expect the parameter description as following screenshot shows, please move the focus to the cell then.

![image](https://user-images.githubusercontent.com/1261601/130179605-2059b2f6-9e11-4fba-be01-e3c35b97059e.png)

Regarding to "Function Arguments" dialogue to popup in online, I think it is more like a new feature request for excel online, I may suggest to submitting the feedback to UserVoice instead.

**Comment by wh1t3cAt1k** [comment]
@grangeryy @xiaochunms the "name" of the argument is indeed displayed as `ConnectionName`, but **description** isn't:

(the highlighted part on the below screenshot is what I'm talking about - there seems to be no possibility to access this tip on the Web)

![image](https://user-images.githubusercontent.com/5159662/130187528-f365a3aa-efbc-48e5-a1e3-5f83f84285b5.png)

**Comment by wh1t3cAt1k** [comment]
@grangeryy the latest session ID is 60db8879-9317-455e-bb1a-da6e3bc8b905

**Comment by xiaochunms** [comment]
@wh1t3cAt1k I understood your concerns. I think it is a feature ask for excel online to display the "description" as you described as unlike desktop, excel online cannot show the details for built-in functions such as "SUM". May provide the feedback to UserVoice work?

**Comment by wh1t3cAt1k** [comment]
@xiaochunms Some of the recent feedback on UserVoice submitted by our team never made it to the platform... Looked to us that it was stale and not monitored anymore.

I would be glad if you could relay this feedback to the Office on the Web development team through internal means so that it's not lost.

In particular, I already submitted the idea about function arguments dialogue to UserVoice two or three days ago but the idea never appeared, and it's been the same experience for our team in the last few months.

**Comment by grangeryy** [comment]
Hey @wh1t3cAt1k, about UserVoice, the system is being deprecated so the better channel here is to use "Give Feedback to Microsoft" button at the right bottom:
![image](https://user-images.githubusercontent.com/50093161/130387467-1e27f67b-d7f4-41b2-8178-a946c359352b.png)

**Comment by wh1t3cAt1k** [comment]
Ok! it's what we used to do as well,  no one seems to contact back from there either - that's why I asked to relay our feedback to the product team...

Thanks for the help anyway!
