### ISSUE TITLE
Recurrence is always null in web clients, while addHandlerAsync's handler is called twice with old and new recurrence value as well.

### ISSUE THREAD

**Issue by balazserdeszlogmein** [OfficeDev/office-js#2066]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
The issues reported in these threads:
- https://stackoverflow.com/questions/63616869/outlook-add-in-calendar-event-recurrence-is-always-null
- https://stackoverflow.com/questions/64556129/outlook-addin-calendar-event-recurrence-is-the-previous-one-after-changed
- https://github.com/OfficeDev/office-js/issues/1537

still persist for me, using latest office.js:
```
/* Outlook Web specific API library */
/* osfweb version: 16.0.14319.10000 */
/* office-js-api version: 20210702.L */
```

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: latest web version
* Operating System: any, but deep testing performed on macOS Big Sur
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Recurrence should be always returned correctly. AddHandlerAsync should only be called once.

## Current behavior
Sporadically, recurrence is null when queried via `item.recurrence.getAsync()`. For example, I could reproduce it all day long, then I restarted my computer and now it is good.

Recurrence event handler with `addHandlerAsync` is still called twice with old and new recurrence values.

## Steps to reproduce
Simply press run on the scriptlab gist, and then change recurrence.

## Link to live example(s)
Scriptlab example:
https://gist.github.com/balazserdeszlogmein/6f6434247f996d5c2f246667c1ef9078

## Context
We are working on a meeting scheduler integration. This issue clearly and heavily impacts our customers, as we cannot reliably determine the recurrency nature of their appointments.

**Comment by exextoc** [comment]
Hey @balazserdeszlogmein ,

We are investigating this issue with recurrence. However, since it's an intermittent issue, we need some time to fully understand this. We will keep you posted.

**Comment by balazserdeszlogmein** [comment]
Thank you @exextoc!

It is more than intermittent, until the browser restart on Thursday I could 100% reproduce - we had discussed this issue several times over the past weeks and we could always reproduce it. I was surprised when the browser restart temporarily solved it.

I tried it again today just a moment ago (after browser restart), the issue is again happening constantly, on every try.
Something weird that is attached to the issue is that the option to remove the recurrence is disabled:

![Screenshot 2021-08-23 at 7 06 17](https://user-images.githubusercontent.com/69678560/130393281-31b86a6b-18bf-4954-82fe-14c9328090f1.png)

This option is not disabled when the bug does not happen.

Let me know please if you need anything else from my side. This issue getting solved is a priority for us and we aim to help you as much as possible.

**Comment by balazserdeszlogmein** [comment]
Are there any updates on this? This issue is affecting us and our customers heavily.

**Comment by balazserdeszlogmein** [comment]
More than a month passed, and still no answer from your side, @exextoc. Can you please update me on the state of this ticket?

**Comment by bjoernbur** [comment]
Any updates on that issue? We have exactly the same problem. The call works in Outlook client but not in Web access.

**Comment by exextoc** [comment]
Apologies for the delay in response. We could repro this issue and has been added to our backlog. We will take a look at this in priority. Will keep you posted once the fix is available.
