### ISSUE TITLE
when i click calendar page  in outlook handler trigger on outlook add-ins 

### ISSUE THREAD

**Issue by Tamil2000** [OfficeDev/office-js#2069]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Microsoft 365 Developer Platform Ideas Forum

We're moving away from UserVoice feedback sites on a product-by-product basis throughout the 2021 calendar year. Later in 2021, we will leverage a 1st party solution for customer feedback. Meanwhile, please post feature requests and suggestions at the [Microsoft 365 Developer Platform Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). 

For more information, see [UserVoice pages](https://support.microsoft.com/topic/uservoice-pages-430e1a78-e016-472a-a10f-dc2a3df3450a).

**Comment by keyur32** [comment]
Hi @Tamil2000, can you please update this with repro steps for your issue you are having? It seems cut off. Thanks.

**Comment by Tamil2000** [comment]
> Hi @Tamil2000, can you please update this with repro steps for your issue you are having? It seems cut off. Thanks.
Hi @keyur32  First of all Thanks for Reply
I am implementing the outlook add-ins related to salesforce , and i am creating the events from add-ins to outlook calendar using outlook create event RestAPI, But This create event function trigger when i open add-ins , i want this automatically trigger this create event function automatically in background ,so In outlook account open or outlook account signIn action ,Trigger this create event on my outlook add-ins
_**In My outlook add-ins implemented using Javascript language**_

Any handler is available for this event trigger ?
