### ISSUE TITLE
Outlook add-ins

### ISSUE THREAD

**Issue by Tamil2000** [OfficeDev/office-js#2070]
I am researching in outlook event handlers , when I open the Outlook any possible to trigger some function in outlook add-ins?

Many ways i tried but not getting any solution, any possible to trigger a event when i open the outlook in my outlook add-ins, If you have any idea about that please share me?

**Comment by keyur32** [comment]
Thank you for this question. To better assist you, we suggest you go to [StackOverflow](https://stackoverflow.com/questions/tagged/office-js) <change tag if appropriate> and see if your question has already been asked or ask a new question. This will allow both the community to help, and allow us to ensure the community can see our answer. When added, please let us know and we will follow up there.  

Thanks, Microsoft 365 Developer Platform team.

**Comment by Tamil2000** [comment]
> Thank you for this question. To better assist you, we suggest you go to [StackOverflow](https://stackoverflow.com/questions/tagged/office-js) and see if your question has already been asked or ask a new question. This will allow both the community to help, and allow us to ensure the community can see our answer. When added, please let us know and we will follow up there.
> 
> Thanks, Microsoft 365 Developer Platform team.

https://stackoverflow.com/questions/68901939/outlook-add-ins-event-handler?noredirect=1#comment121771695_68901939

**Comment by exextoc** [comment]
The functionality you are looking for is currently not present in outlook add-ins. Please go through the documentation to know more about the supported events. 
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch

**Comment by keyur32** [comment]
marking as closed, as answer was provided here as well as on stackoverflow (thank you for posting there). As this now seems like a feature request as this functionality is not yet supported, we would encourage you to post your idea on the [Microsoft Tech Community New Ideas forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform#). Thank you.
