### ISSUE TITLE
insertSlidesFromBase64 after selected slide throws error

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#2071]
# Provide required information needed to triage your issue
Inserting a slide after a selected slide does not work anymore. It throws an exception "Cannot read property 'invokePropertySet' of null"

## Your Environment

* Platform: Office on the web
* Host: PowerPoint
* Operating System: Windows
* Browser: Chrome
 
## Expected behavior
You should be able to insert Slides after a selected slide.

## Current behavior
When you pass a slide id as an option parameter to insertSlidesFromBase64(base, { .., targetSlideId: 258 }) it throws an exception.

## Steps to reproduce
1. Open Script Lab in PowerPoint
2. Select existing Sample "Insert slides from other presentation"
3. Run
4. Choose File and Select a PowerPoint File
5. Click "Insert after selected slide"
6. Observe Error on Console

## Context
We have an addin which inserts slides from other PowerPoint files. Our customers cannot use our addin in Office on Web anymore as it always throws an exception now.

**Comment by keyur32** [comment]
@lliu113  - can you please take a look? I can repro the error on scriptlab.

**Comment by lliu113** [comment]
@barisbikmaz - thanks for reporting this, we will investigate internally. 
Internal bug tracking: 5366182

**Comment by ononder** [comment]
Thanks for reporting the issue @barisbikmaz. We have identified the issue, a fix is currently being checked-in and it will get through the pipeline. Sorry for the inconvenience this issue may have caused.

**Comment by FranCerrada** [comment]
Hi @ononder, any estimations about when the fix will be released? We are also affected by it.

**Comment by ononder** [comment]
Hi @FranCerrada, the fix should be available in most of the production servers as of now. If you still encounter the issue, please let us know.

**Comment by lliu113** [comment]
@barisbikmaz - I'll go ahead and close this issue. Feel free to reopen if you have any questions, thanks!
