### ISSUE TITLE
Mechanism for determining EWS and REST URL

### ISSUE THREAD

**Issue by GrumpyAL** [OfficeDev/office-js#2072]
I have what I hope is a quick question.  We are trying to track down why a specific EWS/REST API URL is being returned in OWA by Office Add-ins. Are you able to share the mechanism by which the REST and EWS URLs are determined when running Office.context.mailbox.ewsUrl (or .restUrl).  How does the framework determine the right URL to use when in OWA.  It doesn't appear to make any extra calls to Exchange.  The specific JS in use is outlook-web-16.01.js.  It looks like when the Extensions load a service.svc action called GetExtensibilityContext is used and this returns the EWS and REST URLs.  However, we were hoping for some more information about what properties in Exchange would impact which URL is used here.  

What we are seeing external URLs returned that are only set on four servers where other servers in the environment do not have an external URL set, including the servers where the mailbox in question resides. 

Is it designed that if there's an external URL set anywhere in the environment, that is what is returned for the EWS/REST URLs?

**Comment by keyur32** [comment]
Thank you for this question. To better assist you, we suggest you go to [StackOverflow](https://stackoverflow.com/questions/tagged/office-js) <change tag if appropriate> and see if your question has already been asked or ask a new question. This will allow both the community to help, and allow us to ensure the community can see our answer. When added, please let us know and we will follow up there.  

Thanks, Microsoft 365 Developer Platform team.

**Comment by GrumpyAL** [comment]
I apologize.  I have reposted the question over on StackOverflow.  Thank you!
