### ISSUE TITLE
Is it possible to trigger the handler in outlook add-ins when i open the outlook Mail calendar tab?

### ISSUE THREAD

**Issue by Tamil2000** [OfficeDev/office-js#2073]

**Comment by keyur32** [comment]
Thank you for this question. To better assist you, we suggest you go to [StackOverflow](https://stackoverflow.com/questions/tagged/office-js) and see if your question has already been asked or ask a new question. This will allow both the community to help, and allow us to ensure the community can see our answer. When added, please let us know and we will follow up there.  Thanks, Microsoft 365 Developer Platform team.
