### ISSUE TITLE
New Outlook for Mac, item.from.getAsync() returns email address in the displayName property

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#2075]
In an Outlook add-in for compose mode, we use the item.from.getAsync() method. In new Outlook for Mac, the method returns the EmailAddressDetails object but with email address in the displayName property.

## Your Environment
* Platform: Mac
* Host: Outlook in the NEW mode
* Office version number: Microsoft Outlook for Mac Version 16.52 (21080801)
* Operating System: MacOS Big Sur Version 11.4 (20F71)
* Browser (if using Office on the web):
 
## Expected behavior
The displayName property shall contain the display name but not an email address.

## Current behavior
The displayName property contains an email address.

## Steps to reproduce
1. Run Outlook for Mac in the New mode
2. Create a new email
3. Open an add-in’s pane and execute the following code:
`    function testFrom2() {`
`      var output = document.getElementById("output");`
`      if (output) { output.value = ''; }`
` `
`      Office.context.mailbox.item.from.getAsync((result) => {`
`        console.log('From', JSON.stringify(result));`
`        if (output) {`
`          output.value += 'From:' + '\r\n' + JSON.stringify(result) + '\r\n';`
`        }`
`      });`
`    };`

Please have a look at the screenshot attached, as you can see, the displayName property contains email address.

## Link to live example(s)
1. You can use our test add-in, just click the Get From details button:
https://online-addins.ablebits.com/testaddin/manifest.xml

## Useful logs
- [ x ] Screenshots

<img width="1121" alt="Screenshot2021-08-24" src="https://user-images.githubusercontent.com/28924916/130611307-a245aedf-f5ea-4695-aebb-a168fbaf315d.png">

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding Display Name. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

Internal tracking id: Office: 2307997

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 16.55.21092802 or later. When an updated build is available depends on the release channel a customer is on. The latest build can be accessed by joining [Office Insiders Program](16.55.21092802).
