### ISSUE TITLE
both Office.context.mailbox.item.from.getAsync and Office.context.mailbox.userProfile.displayName return wrong data

### ISSUE THREAD

**Issue by gitcnd** [OfficeDev/office-js#2079]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am having the same problem as https://github.com/OfficeDev/office-js/issues/872

It is easily reproduced.

Load the ScriptLab sample "Get from (message compose)" and click the "Who is this from?" button - the answer wrongly returns the email address in place of he name.

The same problem exists for both Office.context.mailbox.item.from.getAsync as well as Office.context.mailbox.userProfile.displayName

**Comment by gitcnd** [comment]
It also returns the wrong time zone (PST - but that is not my zone).

Note: it FAILS as described from outlook.exe (windows).
It *works* OK from https://outlook.live.com/mail/0/inbox

So this is just a fault with the .EXE (and possibly other clients) - but not with the web version.

**Comment by exextoc** [comment]
We are unable to reproduce this issue on our end. Could you please provide us more details about the platform and the version of the Outlook client?

**Comment by gitcnd** [comment]
Can you send some screen-shots showing what you have tested?  I fails every time for me, using the most recent Office on the most recent Windows 10, with everything updated to now.  

![Screen Shot 2021-08-27 at 1 06 07 pm](https://user-images.githubusercontent.com/4301826/131066348-902038ef-8299-4c8b-a012-f53ca87fd06b.png)

![Screen Shot 2021-08-27 at 1 11 33 pm](https://user-images.githubusercontent.com/4301826/131066363-34bf491e-e4e5-420f-beca-e06ef7e3249d.png)

**Comment by exextoc** [comment]
I'm able to reproduce the displayName issue in Windows Outlook, however, I cannot reproduce this is the web client (OWA).

For time zones, Windows Outlook returns your system's time zone whereas the web client returns the value configured in the settings. In the web client, click on the  Settings icon -> General -> Language and time, and check the value of Current time zone. 
Is this the behavior you are observing or something different?

**Comment by gitcnd** [comment]
When can we expect you to fix this bug?

The OWA client is not affected - please carefully read my report - I already said that.

Note that your idea about the time zone is not correct - Windows outlook is NOT returning my system's time zone at all - you need to work out which zone you want to return, and fix the bug that's returning the wrong thing.  I suggest you make it return the same thing as OWA does - using different zones in different clients makes no sense.

**Comment by exextoc** [comment]
The From Bug has been filed with the Product Team. I unfortunately cannot share a time line or update status to this bug at this time.
Internal Reference Id:  5378628

The Time Zone in Windows Outlook should be taken from the Windows System: 

![image](https://user-images.githubusercontent.com/28549921/131769255-bbcd5471-e198-4845-98d4-a45485bb4d28.png)

The value returned in the API should be the value in the above dialog. 
Are you observing something different? What Time Zone is being returned in your case?
This value is refreshed in the API on **Reboot** of Outlook. (if you are seeing an outdated value, you may need to reboot)

OWA's Time Zone is returned via it's settings: 

![image](https://user-images.githubusercontent.com/28549921/131769482-52164d39-aa74-4cac-908f-4084176332e8.png)

The API cannot return the same time zone in both cases, as the clients themselves are getting their Time Zones from different sources. (Win32 from Windows, OWA from their own Settings)

**Comment by gitcnd** [comment]
OK - never mind the time zones.  When will the name/email mixup be fixed ?

**Comment by exextoc** [comment]
The name/email bug has been filed with the Product Team. We unfortunately have no timelines to share at this point. Once the bug is fixed, we'll update the thread to reflect the same.
Internal Reference Id: 5378628

**Comment by exextoc** [comment]
@gitcnd are you still able to reproduce this issue in Outlook.exe?
