### ISSUE TITLE
Visio - Event handlers are not executed on IE11

### ISSUE THREAD

**Issue by joelfmrodrigues** [OfficeDev/office-js#208]
Visio event handlers don't seem to be working on Internet Explorer 11
Tried [onPageLoadComplete](https://dev.office.com/reference/add-ins/visio/pageloadcompleteeventargs) and [onDocumentLoadComplete](https://dev.office.com/reference/add-ins/visio/documentloadcompleteeventargs) examples from documentation.
Works well on Chrome and Edge

## Expected Behavior
Custom event handlers should be executed after the event happened.

## Current Behavior
Custom events are not triggered on IE11.

## Steps to Reproduce, or Live Example
Try sample code provided on documentation. For the samples to work on chrome, I had to include the session when running the code block
Example:
"Visio.run(function(ctx)" works when changed to "Visio.run(mySessionObject, function(ctx)"

https://dev.office.com/reference/add-ins/visio/pageloadcompleteeventargs
https://dev.office.com/reference/add-ins/visio/selectionchangedeventargs

## Context
Trying to create an application (embedded in a classic SharePoint page) that loads shape data from a Visio file and displays it on a custom panel.

## Your Environment
* Operating System: Win 10
* Browser (if using Office Online): Internet Explorer 11

## Useful logs
No errors or logs

**Comment by rahul-mi** [comment]
Hi,

Thank you for reaching out and the detailed description of the issue you are facing. 

We checked internally and found that with the session parameter added to Visio.Run function, pageload and document load events are working with IE11. We have also updated the documentation and it should reflect the same soon.

Could you check it again with the session parameter added and if it's still now working, share more details (Error screenshot, your code snippet etc.)? - so that we can investigate and improve the experience.

Regards
Rahul Mittal | Program Manager | Microsoft Visio

**Comment by joelfmrodrigues** [comment]
Hi @rahul-mi 

Thanks for the information.
I'm currently using TypeScript. Could that be a problem? Not using WebPack or any other module loaders, simply tsc to convert to typescript.

Sample code below. The onPageLoadComplete function is never executed on IE11, but as I mentioned before, it runs on Chrome and Edge.


    addOnPageLoadCompleteEventHandler = async (): Promise<any> => {

        try {
            await Visio.run(this._session, async (context: Visio.RequestContext) => {

                var doc: Visio.Document = context.document;
                const onPageLoadCompleteEventResult: OfficeExtension.EventHandlerResult<Visio.PageLoadCompleteEventArgs> =
                    doc.onPageLoadComplete.add(
                        this.onPageLoadComplete
                    );

                await context.sync();
                console.log("Page Load Complete handler attached");
            });
        } catch (error) {
            this.logError(error);
        }
    }


    onPageLoadComplete = async (args: Visio.PageLoadCompleteEventArgs): Promise<void> => {

            console.log("Page Loaded Event: " + JSON.stringify(args));
    }

Thanks,
Joel

**Comment by keyur32** [comment]
@rahul-mi  - can you check if we need to follow up on this please?

**Comment by joelfmrodrigues** [comment]
Hi @rahul-mi and @keyur32 

Thanks for raising this again. I have just retested it and was unable to see the bug now.
Same code (SharePoint Framework web part), but now updated to the latest SharePoint Framework version - not sure if this can have an impact.
This is the code, in case you want to give it a try at your end.
https://github.com/joelfmrodrigues/sp-dev-fx-webparts/tree/react-visio-191/samples/react-visio

I will close the item.
Many thanks
