### ISSUE TITLE
insertWorksheetsFromBase64 not working with Sensitivity label

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#2081]
Hi Guys,

We are creating an Excel addin and we are now in the phase of testing it worldwide.

Our tool makes use of the insertWorksheetsFromBase64 (it is so cool!!!) and it works in most cases for us. BUT we found that people using Miscrosoft's Sensitivity Label feature, are getting an error ('There was an internal error while processing the request.') whenever this function is called.
The template that we load with this function, did not change!
They get this error in the Desktop version of Excel, it is working perfectly in the online version!

## Expected Behavior
We expect that a template is downloaded and loaded into our workbook and that it works on Desktop and Online.

## Current Behavior
We see that the function 'insertWorksheetsFromBase64' throws an error 'There was an internal error while processing the request.' BUT only for our users with Sensitivity Label activated. 

Next to that, we see that it is working for Online and failing for Desktop. Again, same code, same template that we try to load.

## Steps to Reproduce, or Live Example
Unfortunately we have nothing to reproduce it because our region is not using Sensitivity Labels...yet.

## Context
We are currently testing worldwide, and the plan is to go live next month. This issue is our top priority this moment.

We provide an Excel Addin to our users, worldwide, where they need to enter portfolio data.

Our solution, downloads templates and adds them to the workbook that the user is using. The users enters their values and they can save the data.

We got this issue since last week. But it turns out that some testers were also invited this week to test the Sensitivity Label feature.

## Your Environment

* Platform: PC desktop (FAILS), Online (Works)
* Host [Excel, Word, PowerPoint, etc.]:  Excel
* Office version number: 16.0.14228.20250
* Operating System: Windows 10
* Browser (if using Office Online): Edge

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- 
![afbeelding](https://user-images.githubusercontent.com/46490607/130977940-4892b408-6214-4f3a-9121-523bf6c2e9b6.png)

- 
![afbeelding](https://user-images.githubusercontent.com/46490607/130934837-72bd1079-1037-4d63-bca0-dcc131249e2e.png)

- [ ] Test file (if only happens on a particular file)
- [  x ] This is the error we get:
`{"ErrorMessage":{"code":"GeneralException","message":"There was an internal error while processing the request.","errorLocation":"Workbook.insertWorksheetsFromBase64","statement":"workbook.insertWorksheetsFromBase64(...);","surroundingStatements":["var workbook = context.workbook;","// >>>>>","workbook.insertWorksheetsFromBase64(...);","// <<<<<","var application = workbook.application;","application.suspendApiCalculationUntilNextSync();","application.suspendScreenUpdatingUntilNextSync();"],"fullStatements":["Please enable config.extendedErrorLogging to see full statements."]},"Stack":"RichApi.Error: There was an internal error while processing the request.\n    at new n (https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:26:236004)\n    at n.o.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:26:299226)\n    at https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:26:297331\n    at async sync (https://msc-web-epas-acc.azurewebsites.net/js/Global.js?nocache=9.0.269.13:1064:9)\n    at async addTemplateSheet (https://msc-web-epas-acc.azurewebsites.net/js/Global.js?nocache=9.0.269.13:1122:5)\n    at async https://msc-web-epas-acc.azurewebsites.net/js/POCOST.js?nocache=9.0.269.13:14:9\n    at async updateSheet (https://msc-web-epas-acc.azurewebsites.net/js/POCOST.js?nocache=9.0.269.13:10:5)\n    at async load (https://msc-web-epas-acc.azurewebsites.net/js/POCOSTRun.js?nocache=9.0.269.13:100:9)\n    at async refresh (https://msc-web-epas-acc.azurewebsites.net/js/POCOSTRun.js?nocache=9.0.269.13:340:9)\n    at async updatePOCOST (https://msc-web-epas-acc.azurewebsites.net/js/POCOSTRun.js?nocache=9.0.269.13:20:5)"}`

**Comment by keyur32** [comment]
Cool use case. Assigning to @lumine2008 to help investigate.

**Comment by qinliuMSFT** [comment]
Hi @ALDriehuis, thank you for logging this issue. I'm trying to repro this problem by using the sample snippet ***Insert external worksheets*** in Script Lab. But I'm not able to repro. My repro file's permission like below. 
![image](https://user-images.githubusercontent.com/73509856/131062652-c541cafb-39e2-47ce-bcb6-2d20a43d0b40.png)

Could you please check and compare my snippet and file permission with yours? I'm wondering if my repro environment is right?

**Comment by ghost** [comment]
Hi,

First or all, thanks for looking into this case.

But I do not know how to answer your question. What do you mean with repro environment and how can I check these settings.

Maybe good to tell. Our company is doing a test in (only) Brazil with Sensibility Label. In my region we are not using it, and I have no experience on this at all.
But if you could provide me some additional information on how to set it up on my local machine then I am more than happy to do that!

**Comment by qinliuMSFT** [comment]
Hi @ALDriehuis, sorry the "environment" may cause the misunderstanding. I'm talking about the snippet/sensibility permission, etc. Could you please help answer the following questions?
1. Could you please give us a sample snippet to help repro? I'm using the sample snippet ***Insert external worksheets*** in Script Lab, I'm wondering if it's enough to repro this issue?
2. Could you please confirm the system locale is English or Portuguese (Brazil) on the testing machine?
3. Could you please check the sensibility permission by clicking "View Permissions..." once you open a workbook with Sensibility Label?

**Comment by ghost** [comment]
Hi,

Many thanks for your time spend until now, but I suggest we close the issue right now. I do not get any feedback from our team and because I am living in a region where our company has not yet rolled out Sensitivity Labels, I can not supply any additional data. Many thanks again!

Lou
