### ISSUE TITLE
Getting custom property from word online giving “\n ” value while reading with below code

### ISSUE THREAD

**Issue by vinodifour** [OfficeDev/office-js#2082]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: office365
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Online word should read custom property added in word document from online office 365 word
 
## Current behavior
While reading custom property from online 365 is giving “\n ” value while reading with below code
```
Word.run(async (context: any) => {
  context.document.properties.customProperties.load('items');
  await context.sync();
}).then((res: any) => {
    console.log(res, 'custom property response');
  })
  .catch((err: any) => {
    console.log(err);
  });
```
Note: Able to read property from desktop word with same document but not in online word 365

## Steps to reproduce
You can load the document provided in link [TestDocument] (https://ifourtechnolab-my.sharepoint.com/:w:/p/vimal/EdlJnWq00HBHvJM-R1VGv6QB9j9rOymNP0rhEwZsf55LQA?e=dbDvYt) and try to read the property with provided code

Property that is added to the document
[wordCustomproperty](https://ifourtechnolab-my.sharepoint.com/:i:/p/vimal/ETgA4owBaGFJriG7biQTRCgBVuSxD93tJN8vg8BUIdUYzA?e=CwhzGx)

## Please find bellow screenshot for output value
[Output value](https://ifourtechnolab-my.sharepoint.com/:i:/p/vimal/EQLUC8OOLDtKtY20b4i01ZwBRDPTQ3TAgcXNwlF2FgDPUw?e=f83gyz)

**Comment by keyur32** [comment]
@RuoyingLiang  can you please take a look at this Word Online issue?

**Comment by vinodifour** [comment]
@slabereemsft  any updates on above issue?

**Comment by slabereemsft** [comment]
@vinodifour  - Actually, we need @RuoyingLiang  to comment here.

**Comment by RuoyingLiang** [comment]
Sorry for late response. Open bug 5403524 for this issue and will update the thread once we have progress.

**Comment by xiruatms** [comment]
Thanks for reporting this to us. 

@vinodifour Could you help to provide more information to confirm the issue:
1. Which customproperty was returned with "\n"?  Are all the customproperties returned as "\n" or a specific one?
2. Have you every tried with sample codes in scriptlab? When I tested with the sample, I got following result :
        Property Name:matterId; Type=String; Property Value=01FC6RH5E9SX2TQFENC63KQGRQ
        Property Name:folderId; Type=String; Property Value=01FC9X04NNVFC57SGHRE9JQVKW
        Property Name:workItemId; Type=String; Property Value=338741d4-8653-442b-89f6-19cff076b525
        Property Name:documentId; Type=String; Property Value=01FC9X48NXMA7VKDF6FP8W8ZY8
        Property Name:matterName; Type=String; Property Value=Yan Cui and Yinan
        Property Name:folderName; Type=String; Property Value=test
        Property Name:documentName; Type=String; Property Value=Letter - Grantor Trust 
        Property Name:planningState; Type=String; Property Value=
        Property Name:ED_strategy; Type=String; Property Value=L
        Property Name:ContentTypeId; Type=String; Property Value=0x010100CDDA4BB5C25C6E4787624DE81885F008
        Property Name:_dlc_DocIdItemGuid; Type=String; Property Value=aa5d3257-5f57-4aab-b5c3-c7273d34376a
        Property Name:MediaServiceImageTags; Type=String; Property Value=
3.  If possible, will you please post the entire code snippet instead of the partial ones?

With more information, this issue might be addressed soon. Thanks a lot for your help!

**Comment by JensMadsen** [comment]
In the documentation there is no mention of `items` in the load method. However, I see `items` when JSON stringify? Could you please explain?
