### ISSUE TITLE
AppointmentAttendeeCommandSurface TaskPane swallows first click

### ISSUE THREAD

**Issue by 0xA17C** [OfficeDev/office-js#2083]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
When I open an addin on an appointment (`AppointmentAttendeeCommandSurface`), there seems to be an overlay preventing the first click to register. You can see a black outline around the taskpane and the close button has the hover state. I can reproduce this with a blank snippet in Script Lab as well as with the addin we are developing.

![image](https://user-images.githubusercontent.com/6525829/130988156-44c5e8ac-3e1b-43f7-a98b-7d9ad22ba681.png)

Clicking anywhere within the dialog (taskpane or the appointment view itself) seems to remove this overlay. Closing and reopening the addin does not help, the same happens each time the addin is loaded.

This does not occur with taskpanes for `MessageReadCommandSurface`, `MessageComposeCommandSurface` or even `AppointmentOrganizerCommandSurface`.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: OfficeOnline
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 0.0.0.0
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome 92, Firefox 91 (both display this behavior)

## Steps to reproduce

1. Open a blank snippet in Script Lab on an appointmentItem.
2. Try to click on "Run"
3. First click does not register (or registers on the overlay)
4. The next click goes through and "Run" is executed.

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Thanks for raising this issue. We have put it in our backlog. Currently, we do not have any timeline to share.
