### ISSUE TITLE
[MailboxItem]: getComposeTypeAsync has error when opening from external tools

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#2084]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

An internal error as occured when calling Office.context.mailbox.item.getComposeTypeAsync.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows
* Host [Excel, Word, PowerPoint, etc.]: Outlook App
* Office version number: 
   * ![Capture](https://user-images.githubusercontent.com/13063615/131091830-1967e166-d299-4ba9-a8a2-755a4a20c626.PNG)

* Operating System: Windows 10 Pro - 20H2 - 19042.1165

## Expected behavior
- It should get composeType and coercionType successfully.

## Current behavior
![3](https://user-images.githubusercontent.com/13063615/131068049-f107a0c4-9b6c-4a1d-8c81-80bf592572f5.PNG)

## Steps to reproduce

1. On Windows, right click any image 
2. Send To -> Mail recipient
3. execute this api : getComposeTypeAsync ( you can try with any scriptlab example)
4.  Observe the error.

## Link to live example(s)
ScriptLab : sample "Work with client signatures (compose)"
![hrm9iYCRdA](https://user-images.githubusercontent.com/13063615/131067650-b03c4a41-d88d-47f0-a3a5-c48a19aa79b9.gif)

## Context
It blocks me to insert signature.

**Comment by exextoc** [comment]
Thanks for reporting this issue about the `getComposeTypeAsync` API.
This is a known issue. Internal product bug 5344464.
We unfortunately have no timelines to share regarding the resolution of this issue.

**Comment by JackTheDane** [comment]
Is there any update on this issue? We are seeing similar problems when this API is invoked in a mail item created via a "Quick steps" action in Windows Desktop.

![image](https://user-images.githubusercontent.com/35668734/192545309-e39b7249-d975-4a0c-b12c-6bfdd9ad8b6e.png)
