### ISSUE TITLE
Issue when try to use together two addins functions 

### ISSUE THREAD

**Issue by FromPerm** [OfficeDev/office-js#2086]
Our customers try to use external add-in Hodrick Prescott Filter (downloaded from https://web-reg.de/webreg-hodrick-prescott-filter) like a VBA add-in with our custom functions from Knoema Data Finder add-in and get an error #VALUE 

## Your Environment
PC, Excel, Microsoft 365 Version 2107(Build 14228.20250) 64 bit, Windows 10

## Steps to reproduce
1. Open Excel.
2. Install Knoema Data Finder add-in
3. Install Hodrick Prescott Filter (VBA)
4. Close current file, because of existing issue https://github.com/OfficeDev/office-js/issues/2051
5. Create the new excel file.
6. Try to add formula "=HP(KNOEMA.GET("IMFWEO2021Apr", "", "", "614", "NGDPD"), 10)"
7. The cell has value #VALUE

Could we use VBA add-in formulas with JS add-in formula?
We tried to use our formula with our formula "=KNOEMA.GET("IMFWEO2021Apr", KNOEMA.GETDATES("IMFWEO2021Apr", "A", "@rows", "512", "NGDP_RPCH"), "", "@rows", "512", "NGDP_RPCH")"
[knoema formula example.xlsx](https://github.com/OfficeDev/office-js/files/7077306/knoema.formula.example.xlsx)
and all works as expected.

**Comment by xiaochunms** [comment]
Hi @FromPerm thanks to raise the question. I noticed your usage would be call JS add-in formula in a VBA add-in formula, i.e. "=HP(KNOEMA.GET("IMFWEO2021Apr", "", "", "614", "NGDPD"), 10)", "HP" is a VBA add-in formula, while "KNOEMA.GET" is a JS add-in formula. I am sorry that usage is not supported. You may know VBA formula is a sync call, while JS formula is an async call. For a sync call it returns immediately once calculation completes, however for an async call it will return immediately but without result calculated, the result will be calculated later. The behavior of async call does not fit in a sync call.

**Comment by FromPerm** [comment]
Thanks for your answer!

**Comment by AlexPhilippov** [comment]
Can we have some links on documentation on this, so it will be clear for everyone?
Also, it feels like Excel shouldn't allow using such formulas together or at least have some meaningful error shown other than #VALUE.
