### ISSUE TITLE
CustomXmlNode.setXMLAsync() fails (error 6100) in Word 16.0.13801.20864, works using 16.0.8201.2200

### ISSUE THREAD

**Issue by benmcinerney** [OfficeDev/office-js#2088]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Description Of Issue

We have production release of Word Add-In working for about a year, on Word 2016 (16.0.8201.2200).
Business is moving to M365 Semi-Annual Enterprise Edition (Word 16.0.13801.20864) and testing fails with '6100 Custom XML Error'

## Your Environment
Fails in this environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: **16.0.13801.20864**
* Operating System: Win 10 Enterprise (v1809)
* Browser (if using Office on the web): n/a - internally, Add-In is using **Edge WebHTML (WebView)**

Works as expected in this environment:
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: **16.0.8201.2200**
* Operating System: Win 10 Enterprise (v1809)
* Browser (if using Office on the web): n/a - internally, Add-In is using **IE 11**

## Expected behavior
Update Word document's SharePoint property via customXmlPart using Add-In pane fields.
User clicks Update button. Properties are updated.

## Current behavior
User clicks Update button. Properties are not updated. Log reports '6100 Custom XML Error'.
Some user testing reports of immediate second attempt working (user clicks update button again)

## Steps to reproduce
YAML for ScriptLab - https://github.com/benmcinerney/public/blob/main/setDocumentProperties-v2.yml

The test will set three custom document properties, targeting:

- Change existing text value
- Add text value to node that is currently **null**
- Remove text value and set attributes to **null**

### Environment setup
1. Open attached Word document in Word M365 - DC-Civ Test Add in Issue.docx
2. Open ScriptLab and import YAML snippet - setDocumentProperties-v2

### Run tests
1. Navigate to File -> Info -> Show All Properties: original properties visible
2. Click `Update Properties` button - 1st run fails , log = "FAILED with: 6100 Custom XML Error."
3. Click `Update Properties` button - 2nd run succeeds, log = "Success!"
4. Navigate to File -> Info -> Show All Properties: original properties still visible
5. Save document
6. Navigate to File -> Info -> Show All Properties: original properties still visible
7. Close document
8. Open document
9. Navigate to File -> Info -> Show All Properties : NEW properties visible

Therefore, TWO bugs present, in core Word interface and Word API (Office JS)

1. API Update doesn't work first time, no code changes, but second time function is called it works fine
2. File Info Properties doesn't update to reflect actual custom property values in real time

## Context
The system allows a user to select a Word template from within SharePoint 2013.
Each template has an associated content type with multiple site columns.
The Word Add-In guides the user to populate these fields (including web services back to SharePoint lists for populating dropdowns)
When they first open an add-in pane, its form fields are rehydrated with the SharePoint properties
They make any changes, press Update button which modifies these CustomXMLPart properties and updates document body content controls text respectively.

## Useful logs
- [X] Console errors
- [X] Word Document containing custom properties to use in ScriptLab (Word)
- [ ] Screenshots - Screen-scrap pane contents
- [ ] Test file (if only happens on a particular file)

[ScriptLab Console Output.txt](https://github.com/OfficeDev/office-js/files/7118315/ScriptLab.Console.Output.txt)

[DC-Civ Test Add in Issue.docx](https://github.com/OfficeDev/office-js/files/7118278/DC-Civ.Test.Add.in.Issue.docx)

**Comment by benmcinerney** [comment]
Update:
I reviewed code posted on MS Documentation page for setXmlAsync and noticed i had an extra wrapper around my function (i think based on earlier ScriptLab example code):
```
return Word.run(async context => {
   Office.context.document.customXmlParts.getByNamespaceAsync(settings.namespace, function(result) {
  ...
  ...
};

```
I removed this code wrapper and early testing appears to have resolved issue. 
Other users testing now to confirm resolution.

**Comment by benmcinerney** [comment]
No, its failing (again).
The pattern seems to be it updates successfully on the first call to the function, but subsequent calls fail (to update other document properties).
This appears to suggest that the document content is getting out of sync - so the XML must be presenting itself as corrupt on the subsequent calls.
So, am I missing a line of code that deals with syncing:   context.sync().
I successfully ran the function in ScriptLab - so this is perplexing.

**Comment by AbidRahman-MSFT** [comment]
Hey @benmcinerney - is the issue resolved if you add a 'context.sync()' directly after setting the XML?

**Comment by benmcinerney** [comment]
Hi @AbidRahman-MSFT, no I haven't tried that - i wasnt sure if it was a correct approach. I will try it this morning and get back to you.
I have been focussing on changing the update to do all nodes (document properties) at once, as in manipulating the entire XML (from xpart.getNodesAsync(settings.xpathroot) and then using node.setXmlAsync(allDocProps).

**Comment by benmcinerney** [comment]
Hey @AbidRahman-MSFT , @shaofengzhu,

I have made significant changes to the Issue statement above, now supplying you with the Word document to test on, and my ScriptLab snippet (YAML) for you to directly test against.

In the **Run Tests** section, you will see the issue manifesting itself.
This is the same behaviour that I was experiencing with updating single node  values - whereas this new code snippet is updating a single batch of properties.

Note that I am testing on the latest Word on my home PC, v 2108 (Microsoft® Word for Microsoft 365 MSO (16.0.14326.20062) 32-bit ) - This is slightly later than my work PC, but regardless, its failing on both environments

**Comment by benmcinerney** [comment]
Hey @AbidRahman-MSFT , @shaofengzhu, - any update? should only take 10 mins to confirm issue with supplied docx and ScriptLab yaml?!

**Comment by AbidRahman-MSFT** [comment]
Hey @benmcinerney - we have been able to repro the issue that you have mentioned here. We've created an internal task (#5405181) to track the progress. I will let you know if we have any updates. Thanks.

**Comment by benmcinerney** [comment]
Thanks @AbidRahman-MSFT , that is brilliant news - thank you again for taking the time to investigate this! My client is keenly waiting for a resolution!

**Comment by benmcinerney** [comment]
Hey @AbidRahman-MSFT , any chance of a timeframe for this so that I can plan which course of action to take (ie wait for remedy or plan for workaround)

**Comment by AbidRahman-MSFT** [comment]
Hey @benmcinerney - we don't have any updates to share as of now. If your users are on older Office versions, I would suggest planning for a workaround as it will take a few months to roll out any changes that we make to fix the issue.
