### ISSUE TITLE
Dialog Not Communicating With Outlook or Word add-in

### ISSUE THREAD

**Issue by JamesBigChange** [OfficeDev/office-js#2092]
Our Outlook and Word add-ins open a dialog using Office.context.ui.displayDialogAsync() but following an Office update to version 2108, the add-ins no longer receive messages or events back from those dialogs.

The add-in dialogs are working as expected in Office Online (in a browser).

Our issue appears somewhat similar to: https://github.com/OfficeDev/office-js/issues/2089  but I can't be certain.

## Your Environment
* Platform: PC desktop
* Host: Word & Outlook
* Office version number: 2108 (build 14326.20238 Click-to-Run)
* Operating System: Windows 10
 
## Expected behavior
The add-in task pane should receive messages from the dialog popup window as they did before this Office update.

## Current behavior
The dialog opens correctly but cannot send information back to the add-in task pane.
The following error can be seen in the browser console of the dialog. I don't know if this is related:

_Uncaught (in promise) 
OSF.DDA.Error
code: 7000
message: "You don't have sufficient permissions for this action."
name: "Permission Denied"_

## Steps to reproduce
1. Open a dialog using Office.context.ui.displayDialogAsync()
2. Send a message back to the task pane using: Office.context.ui.messageParent()

## Context
This is affecting our customers who have installed Office update 2108.
A workaround is to use Office Online (in a browser).

**Comment by jargil** [comment]
@JamesBigChange - please take a look at this announcement. Is your taskpane/dialog doing a cross-domain messageParent/messageChild call? Let me know if the documentation I'm sharing helps.

https://developer.microsoft.com/en-us/office/blogs/action-required-update-your-office-add-in-dialog-for-cross-domain-communication/?_cache_bypass=1630098590

**Comment by JamesBigChange** [comment]
> @JamesBigChange - please take a look at this announcement. Is your taskpane/dialog doing a cross-domain messageParent/messageChild call? Let me know if the documentation I'm sharing helps.
> 
> https://developer.microsoft.com/en-us/office/blogs/action-required-update-your-office-add-in-dialog-for-cross-domain-communication/?_cache_bypass=1630098590

@jargil - thanks for sharing this post. I will give it a try and report back.
I'm curious as to why our dialogs continue to work on 'Office on the web' whereas the post states that this update was released to this build from 19-Jul-2021.

**Comment by moshikonachmias** [comment]
@JamesBigChange what is the parameter you are sending to messageParent ? string or boolean?

**Comment by JamesBigChange** [comment]
@moshikonachmias I am passing a string (JSON) but will try with the new DialogMessageOptions parameter later today.

**Comment by moshikonachmias** [comment]
Good luck!
For me that was the problem.

**Comment by JamesBigChange** [comment]
@jargil I can confirm that this resolved our issue.
Is there a way to subscribe to these blog posts so that we don't miss future updates?

**Comment by lliu113** [comment]
@JamesBigChange - great question, you can subscribe to blogs via the [RSS feed](https://developer.microsoft.com/en-us/office/blogs/feed/), You can also subscribe to the [Microsoft 365 Community channel](https://www.youtube.com/c/Microsoft365PnPCommunity/featured), which uploads the monthly community calls, where this change was announced.

For your question on why this is working on Office on the web, we currently have a grace period where this is not a breaking change for Online. If you are using the windowed dialog, your users will see a user prompt asking them to trust the domain. If you are using the inline dialog, there is no prompt - it will continue working as before until the grace period is over.
