### ISSUE TITLE
Excel duplicates and replaces formulas within a column.

### ISSUE THREAD

**Issue by harri-rajala-koivu-solutions** [OfficeDev/office-js#2093]
When adding column data to the table, Excel copies and replaces formulas from other rows.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2108 (Build 14326.20238) 
* Operating System: Windows 10 Version 21H1 (OS Build 19043.1165)
 
## Expected behavior
Excel should not copy formulas from other rows. See the example code for more information.

## Current behavior
If the **"Fill formulas in tables to create calculated columns"**-option (Options->Proofing->AutoCorrect Options->AutoFormat As You Type) is **turned on**, then the following example code does not work. Excel copies the formula to the row where it should not be. And it also replaces formulas with different (wrong) formulas.

If the **"Fill formulas in tables to create calculated columns"**-option is **turned off**, the example code works.

The example code should work regardless of whether the user has set the "calculated columns" to on or off. Or, if that is not possible, then there should be a way to disable and enable the "calculated columns" feature using Excel JS. That way, our add-in could disable "calculated columns" before adding formulas to the table and then enable it at the end.

See the example code for more information.

## Steps to reproduce
```typescript
await Excel.run(async (context: Excel.RequestContext) => {
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    sheet.getRange("A1:A3").values = [
        ["Formulas should be only in SUM, MIN, MAX, and AVERAGE rows. <none> rows should not have any formula."],
        ["But because of the 'calculated columns' feature, the first <none> row has a MIN formula."],
        ["And also, the SUM row has a MIN formula."]
    ];
    sheet.getRange("A4:D4").values = [
        [1, 2, 3, 4],
    ];
    const tableName = "TableWithFormula";
    // Delete existing table
    let table = sheet.tables.getItemOrNullObject(tableName);
    await context.sync();
    if (table && !table.isNullObject) {
        table.delete();
    }
    // Create table
    table = sheet.tables.add("A5:C5", true);
    table.name = tableName;
    table.getHeaderRowRange().values = [["Text", "Formula", "Info"]];
    table.getHeaderRowRange().getCell(0, 0).getRowsBelow(7).values =
        [["<none>"], ["SUM"], ["MIN"], ["<none>"], ["MAX"], ["AVERAGE"], ["<none>"]];
    table.getHeaderRowRange().getCell(0, 1).getRowsBelow(7).values =
        [[""], ["=SUM($A$4:$D$4)"], ["=MIN($A$4:$D$4)"], [""], ["=MAX($A$4:$D$4)"], ["=AVERAGE($A$4:$D$4)"], [""]];
    table.getHeaderRowRange().getCell(0, 2).getRowsBelow(7).values =
        [[""], ["SUM = 10"], ["MIN = 1"], [""], ["MAX = 4"], ["AVG = 2.5"], [""]];
    await context.sync();
});
```

## Context
Our add-in adds many different formulas to the column. Also, some rows do not have any formula at all. Our add-in should be able to add formulas to the table regardless of whether the user has set the "calculated columns" to on or off.

**Comment by qinliuMSFT** [comment]
Hi @harri-rajala-koivu-solutions, thanks for logging this issue. It's reproducible from us, and has been put on our backlog VSO#5389572, will let you once we have any updates.

**Comment by guliums** [comment]
Hi @harri-rajala-koivu-solutions, thanks for the detailed description and demo code. With "calculated columns" features, Excel will automatically expand the formula to the rest of the column in the table. But I think your requirement is very reasonable and we will evaluate if we can support disable "calculated columns" by JS API. Meanwhile could you try below workaround to see if it can unblock your scenario?

If the table column already contains data, Excel will not create the calculated column and the result can be correct. So a workaround could be that to set range values to non-formula values firstly, and then set the values to the target formulas. 

table.getHeaderRowRange().getCell(0, 0).getRowsBelow(7).values =
      [["<none>"], ["SUM"], ["MIN"], ["<none>"], ["MAX"], ["AVERAGE"], ["<none>"]];
table.getHeaderRowRange().getCell(0, 1).getRowsBelow(7).values =
      [[""], ["1"], ["1"], [""], ["1"], ["1"], [""]];
table.getHeaderRowRange().getCell(0, 1).getRowsBelow(7).values =
      [[""], ["=SUM($A$4:$D$4)"], ["=MIN($A$4:$D$4)"], [""], ["=MAX($A$4:$D$4)"], ["=AVERAGE($A$4:$D$4)"], [""]];

**Comment by harri-rajala-koivu-solutions** [comment]
Hi @guliums, thanks for the workaround. It works, but it is not a good solution to our issue. Our tables might have, for example, 15000 rows and 250 columns. This workaround will slow down our add-in application because we need to put column data twice, first with an empty string and "1". After that, with real data. 

What is your estimation of when "disable calculated columns by JS API" would be available?

**Comment by harri-rajala-koivu-solutions** [comment]
Hi @guliums, can you please check another critical bug report (**#2097** _The table is broken if the first row in the first column is an empty string_) that I added today. It might be related to this issue?

**Comment by guliums** [comment]
Hi @harri-rajala-koivu-solutions , I just found that it does not need to set every cell to "1". It only need one cell in the column has existing data to avoid Excel auto expand the formula. So the workaround could be just set the last cell in the column to "1", and then set the formula. I think in that way it should not slow down the add-in too much.
For "disable calculated columns by JS API", it is a new API requirement and we have put it to our backlog. I'm afraid I do not have an timeline for it now, but we will let you know once we have update.

**Comment by harri-rajala-koivu-solutions** [comment]
Hi @qinliuMSFT I tested that, and it works. I will change our add-in application to use that workaround.

Please let me know when you have an update related to "disable calculated columns."

**Comment by gingerjia** [comment]
Thanks @harri-rajala-koivu-solutions for reported the issues!
For this specific issue, we have confirmed it's by design and provided workaround to unblock your side. 
If you do need this new feature, can you help to tag it as product feature request, and our PM will priority the work. 

Thanks again!

**Comment by Phrogz** [comment]
I am disappointed that someone thinks this is "by design". At a minimum:

1. The API should honor the UI setting for disabling "Automatically fill formulas".
2. The API should *not* create a calculated column if any formula set in the column is different from another. It currently links them all to be the last issue.
3. The API should provide a setting—at the Workbook, Worksheet, Table, or TableColumn level—to disable this behavior, _even if all formulae are set to the same value_.

@gingerjia Providing a workaround is not an excuse to not fix what is surprising, mostly-indefensible, and uncontrollable behavior. I'm going to file a new bug around this, as the workaround suggested by @guliums does not work AFAICT.
