### ISSUE TITLE
[Excel] Duplicate taskpane thread

### ISSUE THREAD

**Issue by sshukurov** [OfficeDev/office-js#2096]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We are building an Excel JS Addin using Custom Functions and Shared Runtime.

Clicking the Taskpane command button (on the ribbon) fast enough upon page load leads to duplicate taskpane threads being loaded. Though not a very frequent bug, this one is very unpleasant, because it leads to unexpected behavior of our addin and various functionality it comes with.

## Environment
- Platform: Office on the web
- Host: Excel
- Office version number: 16.0.14430.31875
- Operating System: Microsoft Windows 10 Pro Version 10.0.19042 Build 19042
- Browser: Google Chrome Version 92.0.4515.159 (Official Build) (64-bit)

## Expected behavior
Single taskpane thread is expected upon page load at all times.

## Current behavior
Duplicate taskpane.html threads are loading sometimes when we try to open the taskpane as soon as the page loads.
![Screenshot 2021-09-02 113922](https://user-images.githubusercontent.com/36232686/131816334-a454a351-773c-481b-b6b0-bc70dd2c52a8.png)

## Steps to reproduce using a minimal repro
1. Clone and build the repo from https://github.com/sshukurov/excel-duplicate-taskpane-thread
2. Load the sample workbook: [Duplicate taskpane thread.xlsx](https://github.com/OfficeDev/office-js/files/7097585/Duplicate.taskpane.thread.xlsx)
3. Sideload the addin manifest
4. Refresh the page (F5) and click the taskpane ribbon button as soon as it appears upon page load

## Screencast
https://user-images.githubusercontent.com/36232686/131816230-bdc1ae5f-5d57-4566-84a6-ff315215931a.mp4

**Comment by wh1t3cAt1k** [comment]
It's quite an old bug (several months at the least), not a recent regression, it's just that only recently we managed to find a minimal repro for this.

**Comment by slabereemsft** [comment]
@shaofengzhu - This looks like a Shared Runtime bug to investigate first.

**Comment by wh1t3cAt1k** [comment]
@slabereemsft @shaofengzhu any news on that bug? We are still affected, the issue is pretty ugly...
