### ISSUE TITLE
The table is broken if the first row in the first column is an empty string.

### ISSUE THREAD

**Issue by harri-rajala-koivu-solutions** [OfficeDev/office-js#2097]
The table is broken if you add column data with an empty string in the first row. 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2108 (Build 14326.20238)
* Operating System: Windows 10 Version 21H1 (OS Build 19043.1165)
 
## Expected behavior
The empty value in the first row should not break the table.

## Current behavior
The table has two columns Key and Value. The first row does not have Key, so it is an empty string. The table is broken if you first add the Key column where the first row has an empty string. Only the first row is inside the table. All other rows are outside of the table.

If you first add the Value column, then the table is ok. All rows are inside the table.

Note that the "Fill formulas in tables to create calculated columns"-option does not affect this issue. It does not matter if the "calculated columns" feature is turned on or off. In both cases, the table is broken.

## Steps to reproduce
```typescript
await Excel.run(async (context: Excel.RequestContext) => {
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    sheet.getRange("A1:A1").values = [
        ["The table has two columns Key and Value. The first row does not have Key, so it is an empty string."]
    ];

    sheet.getRange("A3:A4").values = [
        ["If you first add the Key column where the first row has an empty string, the table is broken."],
        ["Only the first row is inside the table. The other 3 rows are outside of the table."],
    ];
    const tableNotOk = sheet.tables.add("A5:B5", true);
    tableNotOk.getHeaderRowRange().values = [["Key", "Value"]];
    tableNotOk.getHeaderRowRange().getCell(0, 0).getRowsBelow(4).values =
        [[""], ["a"], ["b"], ["c"]];
    tableNotOk.getHeaderRowRange().getCell(0, 1).getRowsBelow(4).values =
        [["<none>"], ["a1"], ["b1"], ["c1"]];

    sheet.getRange("A11:A12").values = [
        ["If you first add the Value column, then the table is ok."],
        ["All 4 rows are inside the table."],
    ];
    const tableOk = sheet.tables.add("A13:B13", true);
    tableOk.getHeaderRowRange().values = [["Key", "Value"]];
    tableOk.getHeaderRowRange().getCell(0, 1).getRowsBelow(4).values =
        [["<none>"], ["a1"], ["b1"], ["c1"]];
    tableOk.getHeaderRowRange().getCell(0, 0).getRowsBelow(4).values =
        [[""], ["a"], ["b"], ["c"]];
    await context.sync();
});
```

**Comment by guliums** [comment]
Hi @harri-rajala-koivu-solutions , the table created from one row with hasHeaders=true is a little different than other table. After creating table from A5:B5, it looks like A6:B6 is also a table row. But if you edit A7, the table won't auto expand to A7 if you didn't set the value in A6 firstly. That also happens when create table from UI button. 
Would it work for you to create table from 2 rows instead of just 1 row? That is to change "A5:B5" to "A5:B6" when create table.

const tableNotOk = sheet.tables.add("A5:B6", true);
    tableNotOk.getHeaderRowRange().values = [["Key", "Value"]];
    tableNotOk.getHeaderRowRange().getCell(0, 0).getRowsBelow(4).values =
        [[""], ["a"], ["b"], ["c"]];
    tableNotOk.getHeaderRowRange().getCell(0, 1).getRowsBelow(4).values =
        [["<none>"], ["a1"], ["b1"], ["c1"]];

**Comment by harri-rajala-koivu-solutions** [comment]
Hi @guliums. Yes, that works but not anymore after you have deleted existing rows and added new rows. And actually, this is an issue only with the latest Excel version, 2108. 

If you run this code with the previous version 2107 (Build 14288.20250), you can see that both tables are ok.
But if you run this same code with 2108 (Build 14326.20238), you can see that the first table is broken.

```typescript
await Excel.run(async (context: Excel.RequestContext) => {
    const sheet = context.workbook.worksheets.getActiveWorksheet();

    // Create the table and set the initial data.
    const tableNotOk = sheet.tables.add("A2:B3", true);
    tableNotOk.getHeaderRowRange().values = [["Key", "Value"]];
    tableNotOk.getHeaderRowRange().getCell(0, 0).getRowsBelow(4).values =
        [["k1"], ["k2"], ["k3"], ["k4"]];
    tableNotOk.getHeaderRowRange().getCell(0, 1).getRowsBelow(4).values =
        [["v1"], ["v2"], ["v3"], ["v4"]];
    await context.sync();

    // Clear table.
    tableNotOk.getDataBodyRange().delete(Excel.DeleteShiftDirection.up);
    await context.sync();

    // Add new data with an empty string in the first cell.
    // The table is ok if the Excel version is 2107.
    // The table is broken if the Excel version is 2108.
    tableNotOk.getHeaderRowRange().getCell(0, 0).getRowsBelow(3).values =
        [[""], ["a"], ["b"]];
    tableNotOk.getHeaderRowRange().getCell(0, 1).getRowsBelow(3).values =
        [["<none>"], ["a1"], ["b1"]];
    await context.sync();


    // Create the table and set the initial data.
    const tableOk = sheet.tables.add("A9:B10", true);
    tableOk.getHeaderRowRange().values = [["Key", "Value"]];
    tableOk.getHeaderRowRange().getCell(0, 0).getRowsBelow(4).values =
        [["k1"], ["k2"], ["k3"], ["k4"]];
    tableOk.getHeaderRowRange().getCell(0, 1).getRowsBelow(4).values =
        [["v1"], ["v2"], ["v3"], ["v4"]];
    await context.sync();

    // Clear table.
    tableOk.getDataBodyRange().delete(Excel.DeleteShiftDirection.up);
    await context.sync();

    // Add new data with an empty string in the first cell.
    // But in this case, add the Value column first.
    // The table is ok in both Excel versions 2107 and 2108.
    tableOk.getHeaderRowRange().getCell(0, 1).getRowsBelow(3).values =
        [["<none>"], ["a1"], ["b1"]];
    tableOk.getHeaderRowRange().getCell(0, 0).getRowsBelow(3).values =
        [[""], ["a"], ["b"]];
    await context.sync();
});

```

**Comment by guliums** [comment]
Hi @harri-rajala-koivu-solutions, thanks very much for the helpful information. I can repro the issue, internal 5396209 was reported to track it. I will let you know when we have update.

**Comment by yuc014** [comment]
Hi @harri-rajala-koivu-solutions, I tried the code below and it works.
```
async function run() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    const table = sheet.tables.add("A5:B5", true);

    table.getHeaderRowRange().getCell(0, 0).getRowsBelow(3).values = [["something"], ["a"], ["b"]];
    table.getHeaderRowRange().getCell(0, 0).getRowsBelow(1).values = [[""]];
  });
}
```
Hope that would unblock your issue.

**Comment by harri-rajala-koivu-solutions** [comment]
Hi @yuc014 Thanks, that works as a workaround. But like I said, the example code was working with version 2107 without any workaround, but not with version 2108. With 2108 you must use the workaround you provided.

**Comment by yuc014** [comment]
Hi @harri-rajala-koivu-solutions, let me explain why the behavior changed.
From this issue: https://github.com/OfficeDev/office-js/issues/1916, we realized the behavior is not constant on PC and Web (Web is ok). 
After change, PC and Web have same behavior. So your issue should also repro on web, it's better if you help us confirm that.
Now we continues investigate the root cause, and I will let you know when we have update.

**Comment by harri-rajala-koivu-solutions** [comment]
Hi @yuc014 and @guliums 
I can confirm that I can repro the issue on Web (Build 16.0.14501.31875).

I have created issue #1916 you are referring to. Actually, I have created 3 issues (#1916, #2093, and #2097) that are all somehow related to the same thing. As a developer, I want that my code works as I have written that. If I put data to Excel table using Excel JS, I want that it really goes to Excel as it is, without any fancy extra logic that removes or replaces formulas or table is broken if the first row is an empty string, etc. It is the same thing in any programming language. If I, for example, create an array in JavaScript like this `const myArray = ['','b','c','d'];` I really mean that array should have exactly those 4 values. I don't want that JavaScript says, "Yes, I know that you want an array with those four values, but instead of that, I created this kind of array `['x','c','c']`".

Our application reads rows from the database and puts data into an Excel table. And because of these Excel bugs, I need to analyze table data and check if the first value is an empty string or if the column has different formulas, etc. And then, based on that, I need to use an different kinds of workarounds. It should be that I can put data to Excel table as it is, without worrying that Excel changes my values or formulas. And it should work exactly the same way regardless of whether the user is using or not "calculated columns" or any other features. These kinds of "calculated columns" etc. features should affect only when the end-user is using UI. Those should not affect how add-in works.

**Comment by gingerjia** [comment]
@harri-rajala-koivu-solutions Thanks for the detail suggestions and comments!
For #1916, it has been fixed and we have verified at PROD also. Thanks.

For #2093, it's a kind of feature gap, so do need your help to tag it as new requirement, and our PM will priority the work. 

For #2097, after investigated the code, this issue is also a by design behavior since the API developed, as the code consider the first value of array const myArray = ['','b','c','d']; as blank and the length ==0, so will skip auto-expanded them as table rows. 
For why "the example code was working with version 2107 without any workaround, but not with version 2108.", it's due to the #1916 issue hidden the behavior before and exposed after #1916 was resolved. 

We are working on improving our quality and provide better and better experience. Thanks very much for all the issues reported! 
If any new issues or suggestions, please let us know.
