### ISSUE TITLE
Unable to authenticate in add-in for Citrix shared virtual desktop environments

### ISSUE THREAD

**Issue by AbidRahman-MSFT** [OfficeDev/office-js#2098]
Trying to log into the SmartCite add-in fails when using the add-in in a shared virtual desktop environment. 
Please see below video for user flow:

https://user-images.githubusercontent.com/53581099/131911775-7e18db23-6ee5-44cb-9daa-1686e26fa37b.mov

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: The issue occurs on Win32 and on Web (IE and Chrome), not tested on Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: Windows
* Browser (if using Office on the web): Both IE and Chrome has this issue, untested on others
 
## Expected behavior
Expected behavior is the dialog will close and the add-in will be authenticated.

## Current behavior
The dialog does not close and results in a blank screen. The add-in is not authenticated.

## Steps to reproduce

1. Only reproducible in the shared virtual desktop environment. 

# Provide additional details
From the customer: 

We have observed that this issue is happening only in Shared Virtual Desktops( Citrix Pool VDI's).
 
Shared VDI- There will be  n number of VDI's which is shared in a pool allocated to n+ users who can get any random VDI based on the VDI availability.
 
We tried to reproduce the same issue in our dedicated VDI( Assigned only to one specific user) and we were not able to reproduce it. Also we can see that in this kind of shared VDIs there are some  restrictions where we are not even allowed to open Start menu and will have only a limited access.

**Comment by AbidRahman-MSFT** [comment]
@jargil, @lliu113 - any ideas what could be the issue here? Is it possible the virtual environment is blocking some network call needed to finish the authentication process?

**Comment by leewisestamp** [comment]
We have a customer experience the same issue. Bump.

**Comment by ElizabethSamuel-MSFT** [comment]
@jargil @preethikakiru Any thoughts here? Thanks.

**Comment by jargil** [comment]
Could you try installing the WebView2 runtime and trying again?
https://docs.microsoft.com/en-us/DeployOffice/webview2-install

**Comment by leewisestamp** [comment]
There has been no MSFT comment on this. It should remain open.

**Comment by wangyun-microsoft** [comment]
@leewisestamp Have you got a chance to try @jargil's ask on Aug 10?

Thanks.
