### ISSUE TITLE
Text insertion in specific place disappear after focus back to the document

### ISSUE THREAD

**Issue by KirillSelyukov** [OfficeDev/office-js#21]
I use MS word add in, for example Script Lab, when I try to insert text in specific position(double click anywhere in document)  and switch to document  my insertion disappears.

## Expected Behavior
Inserted text should remain on the same place and should not disappear 

## Steps to Reproduce, or Live Example
- Open word
- create new document
- open Script lab add in
- double click in any place in the document
- insert simple text using Script Lab(for example 'basic document assemble -> add h1 title')
- click on the document to focus it
- click on the document one more time
- inserted text disappear 

## Your Environment
Platform : PC
Host : Word 15, Word 16
Office version number: 2013, 2016
Operating System: Win 10

## Example 
https://1drv.ms/v/s!AjsNYhyPk0sRhU5MrvLIMmNHyLtL

**Comment by JuaneloJuanelo** [comment]
this does not repro.
