### ISSUE TITLE
Attachments missing on the EWS server for saved draft email

### ISSUE THREAD

**Issue by bohap** [OfficeDev/office-js#210]
Hello,
I am using **Office.context.mailbox.item.saveAsync** method for saving a draft email. This method returns **itemId** which I later use to make call to the EWS server to retrieve the email eml content, but the returned eml content is missing some of the attachments.
This is only happening on the Desktop App (Outlook 2013) with cache mode enabled,  when using Outlook on the Web it works correctly.
I am using ews-java-api to retrieve the email from the EWS. https://github.com/OfficeDev/ews-java-api/wiki/Getting-Started-Guide#binding-to-an-existing-item
I can't use the **Office.context.mailbox.item.saveAsync.makeEwsRequestAsync** because of the 1MB response limitation.

**Comment by exextoc** [comment]
In Cached mode it will take time for the item to sync up to the server. People usually poll until the data they want is there. Also, they can write a custom property, and check for that property to make sure their item is up to date if necessary. You can find some details about custom property here: [Client Extension Message Object Protocol](https://msdn.microsoft.com/en-us/library/hh968601(v=exchg.80).aspx), [Mail App Custom Properties](https://msdn.microsoft.com/en-us/library/hh968549(v=exchg.80).aspx) and [Mail App Accesses Custom Properties](https://msdn.microsoft.com/en-us/library/hh968567(v=exchg.80).aspx)

**Comment by bohap** [comment]
@exextoc  thanks for the answer.
I have gone with a different solution - the email is send from code, and then the user mailbox is searched for that email, but I found another problem.
I am using the following soap request for sending the email
<?xml version="1.0" encoding="utf-8"?>
    <soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" 
                    xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
                    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" 
                    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"> 
      <soap:Header> 
        <RequestServerVersion Version="Exchange2013" xmlns="http://schemas.microsoft.com/exchange/services/2006/types"
                              soap:mustUnderstand="0"/>
      </soap:Header> 
      <soap:Body> 
        <SendItem xmlns="http://schemas.microsoft.com/exchange/services/2006/messages" 
                    SaveItemToFolder="true"> 
          <ItemIds>
            <t:ItemId Id="@emailId" ChangeKey="@changeKey"/> 
          </ItemIds> 
          <m:SavedItemFolderId>
             <t:DistinguishedFolderId Id="sentitems" /> 
              </m:SavedItemFolderId>" 
        </SendItem> 
      </soap:Body> 
    </soap:Envelope> 

and it works fine from the web, but when using in outlook desktop the email is send only with one attachment, the others are ignored.
The get the `@emailId` I am using the `Office.context.mailbox.item.saveAsync`, and to retrieve the the `@changeKey` I am using this soap request:
```
<?xml version="1.0" encoding="utf-8"?> 
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" 
               xmlns:xsd="http://www.w3.org/2001/XMLSchema"
               xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" 
               xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"> 
  <soap:Header>
    <RequestServerVersion Version="Exchange2013" xmlns="http://schemas.microsoft.com/exchange/services/2006/types"
                              soap:mustUnderstand="0"/> 
  </soap:Header>
  <soap:Body>
    <GetItem xmlns="http://schemas.microsoft.com/exchange/services/2006/messages" 
                xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"> 
      <ItemShape>
        <t:BaseShape>IdOnly</t:BaseShape> 
      </ItemShape>
      <ItemIds>
        <t:ItemId Id="@emailId"/> 
      </ItemIds>
    </GetItem>
  </soap:Body> 
</soap:Envelope>
```
Do you have any idea how to fix this?

**Comment by exextoc** [comment]
This is not possible today. However, we track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). It looks like the feature you want has been requested by others already. Please upvote the existing request [link](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/34593391-immediate-synced-to-the-server-saveasync-to-get). Feature requests on user-voice are considered when we go through our planning process.
