### ISSUE TITLE
Office.context.mailbox.item.body.getAsync returns the wrong content (or perhaps Office.context.mailbox.item.saveAsync saves the wrong content)

### ISSUE THREAD

**Issue by gitcnd** [OfficeDev/office-js#2101]
The 5-character email body "Hello" turns into 40,000 bytes of HTML/XML formatting etc when returned (or saved?) by Office.context.mailbox.item.body.getAsync (or Office.context.mailbox.item.saveAsync ?) even though when that email is received, the body is only 7k.

## Your Environment
Outlook.EXE (current) on Windows 10 (Current)
 
## Expected behavior
Should return the same email body as what recipients received (or will receive).

## Current behavior
Returns a huge amount of data that's not the same.

## Steps to reproduce
1. Compose an email with just a few chars in the body), but do not send.
2. Save it: Office.context.mailbox.item.saveAsync
3. Load back what you saved: Office.context.mailbox.item.body.getAsync(Office.CoercionType.Html,...
4. complete the sending
5. look at the received email bodys' HTML.

The content at #3 should match exactly with the content at #5.

## Context
My Add-In needs to process the users email they're writing - this bug makes that impossible.

## Useful logs

This is what arrives after sending (step 5):

     <html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40">\r\n<head>\r\n<meta http-equiv="Content-Type" content="text/html; charset=us-ascii">\r\n<meta name="Generator" content="Microsoft Word 15 (filtered medium)">\r\n<style></style>\r\n</head>\r\n<body lang="EN-US" link="#0563C1" vlink="#954F72" style="word-wrap:break-word">\r\n<div class="WordSection1">\r\n<p class="MsoNormal">Hello<o:p></o:p></p>\r\n</div>\r\n</body>\r\n</html>

This is what is being returned by Office.context.mailbox.item.body.getAsync

     <html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40"><head><meta name=ProgId content=Word.Document><meta name=Generator content="Microsoft Word 15"><meta name=Originator content="Microsoft Word 15"><link rel=File-List href="cid:filelist.xml@01D7A1BA.6D9FD7E0"><link rel=themeData href="~~themedata~~"><link rel=colorSchemeMapping href="~~colorschememapping~~"><style></style></head><body lang=EN-US link="#0563C1" vlink="#954F72" style='tab-interval:.5in;word-wrap:break-word'><div class=WordSection1><p class=MsoNormal>Hello<o:p></o:p></p></div></body></html>

Note that OWA (Using outlook in a web browser) works OK - only the .EXE version seems to misbehave.

## Update

It looks like the bug is being caused by the Office.js component internally returning the "getOoxml()" result (i.e. the Office Open XML representation) when it *should* instead be returning the getHtml() representation when we explicitly asked for Office.CoercionType.Html  (e.g. see https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview )

**Comment by gitcnd** [comment]
Note that OWA (Using outlook in a web browser) works OK - only the .EXE version seems to misbehave.

**Comment by ElizabethSamuel-MSFT** [comment]
@gitcnd Thanks for raising this.

@exextoc Can you take a look?

Thanks.

**Comment by gitcnd** [comment]
The problem doesn't happen in OWA.

the workaround I'm using at the moment is to manually delete everything inside the  blocks that are ABOVE the <style> info (i.e. leave those [if] things after the <style> alone) - I don't know what possibly bad side-effects that might have, and it's still not exactly the same output as I'm seeing when I "view source" on the eventual emails that get received.

I've also noticed that it's "breaking" my UTF8?  replace it with html &; stuff - is there a way to stop it doing that ?  I *thought* I'd set my content-type properly, and I do see this when I inspect it:-

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"><meta content="text/html; charset=utf-8">

**Comment by exextoc** [comment]
Each outlook client uses the underlying WordMail to render the body. for Desktop, what is returned with getBody call is what word is currently rendering in the reading pane. It's not until you send the email that word converts whats' being rendered into the HTML that you're looking for.

**Comment by ElizabethSamuel-MSFT** [comment]
Refined descriptions partly based on this issue: PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57068.
