### ISSUE TITLE
Add-in "Pin" logic is broken (does opposite of what it says, and the link always does the same thing regardless of whether you click pin or unpin)

### ISSUE THREAD

**Issue by gitcnd** [OfficeDev/office-js#2102]
When installing new add-ins, Microsoft-365 helpfully tells us "... pinned for quick access ..." which is untrue.
It also gives us the option to "un=pin" as well - which is broken.

- Add-ins do NOT get pinned, even though they say they are.
- When you "Un-pin" them, they then DO become pinned.
- After you un-pin them, if you re-pin them again, they stay pinned.

## Your Environment
OWA "Modern" on the web
Browser (if using Office on the web): Chrome on Mac
 
## Expected behavior
The correct "pinned" or "un pinned" behaviour which should match what the prompts say and do at install time.

## Current behavior
The opposite of what is says really happens
the pi/unpin link has additional misbehaviour.

## Steps to reproduce
1. Install "Script Lab for Outlook"
2. Read that it tells you it has been pinned
3. Finish the install - notice that it is NOT pinned.
4. uninstall it
5. re-install "Script Lab for Outlook"
6. click the "un-pin" link in the popup that tells you it has been pinned
7. finish the install
8. Notice now how it IS pinned this time.
9. uninstall it
10. re-install "Script Lab for Outlook"
11. click the "un-pin" link in the popup that tells you it has been pinned, and then click it a second time, so it will be pinned this time.
12. finish the install
13. Notice now how it IS still pinned - indicating that the logic of the "pin/unpin" link is not just "opposite", it is not actually functioning correctly at all.

## Context
Must be fixed - the procedure to manually pin an Add-in is WAY beyond the capacity of my millions of simple users, and Office.js does not give our add-in access to set this pin state itself.

## Suggestion1
Aside from fixing this bug, please allow our Add-ins to perform this "Pin" step themself - we can then make this an option for our users in our task-pane (once the find how to open the un-pinned add-in for the first time) to make it easy from them *next* time.

## Suggestion2
Please call something inside our add-in at install time (like the "action" command, except for setup/install), so we can perform first-time installation actions as needed.

## Screenshots

These are the Pin/Unpin screens I am talking about:-

![Screen Shot 2021-09-05 at 4 17 58 pm](https://user-images.githubusercontent.com/4301826/132117883-00ed5350-89f5-4308-acf8-620e4abe2e05.png)

![Screen Shot 2021-09-05 at 4 17 49 pm](https://user-images.githubusercontent.com/4301826/132117889-d544e3e6-bd57-49d3-828d-c656dec38628.png)

If you do **not** click the "Unpin add-in" link at all, then the add-in is NOT pinned (even though we are told it was):-

<img width="599" alt="Screen Shot 2021-09-05 at 4 36 31 pm" src="https://user-images.githubusercontent.com/4301826/132117946-18dac13f-c37e-4c49-b432-951743a01e05.png">

Clicking "Unpin add-in" *always* pins it, and re-clicking "Pin add-in" (after unpinning) has no effect - it always stays pinned no matter how many time you click that link:-

![Screen Shot 2021-09-05 at 4 41 53 pm](https://user-images.githubusercontent.com/4301826/132118012-4ac89c7e-df3b-4d55-91c6-a1171599fb56.png)

![Screen Shot 2021-09-05 at 4 20 42 pm](https://user-images.githubusercontent.com/4301826/132117937-de2c3021-f879-43c1-840b-043bff51aef8.png)

Tests and screenshots are from OWA - but this bug affects all versions of Office as far as I can tell (Mac native, windows EXE, and classic - ALL of those **never** "pinned" script lab when I installed it, even though ALL of them **said** they had).

**Comment by exextoc** [comment]
We are not able to repro the issue at our end, Pinning/UnPinning works fine for us. Can you please share a small video reproing the issue, it will help us understand more.
