### ISSUE TITLE
insertHtml - Vertical Tab does not work in Word Online

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#2103]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

We are currently migrating a VSTO Add In to Office.js. To support the old documents we need to insert CHR(10) or an equivalent character using insertHtml. Since &#10; was converted to whitespace I ended up using vertical tab (\v) which interestingly works fine in Word Desktop but not in Word Online. It sometimes results in a "can't save the document" and the vertical tab does not show.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Web, PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2108 (desktop)
* Operating System: Windows
* Browser (if using Office on the web): Edge, Chrome, Firefox
 
## Expected behavior
Line Breaks with a vertical tab consistently in Word Online and Desktop.

## Current behavior
It works in Word Desktop but shows weird behavior in Word Online.

## Steps to reproduce

I have created a ScriptLab Gist to reproduce the issue:
https://gist.github.com/tillkaemmerer/46661415df4ac08e5bca73b7f044abd1

1. Click "Init" and wait for the ContentControl to be created and filled.
2. Click "Insert"
3. If you want to try other characters you can change the ``const chr10`` in the first line of JS

**Comment by qinliuMSFT** [comment]
Thanks @tillkaemmerer for logging this issue. The issue is reproducible form our end, and has been put on our backlog VSO#5398128, will let you know once we have any updates.

**Comment by xiaoyuMS** [comment]
Thanks for reaching us @tillkaemmerer  . It looks like a gap between Word Online and Desktop.
As far as i know, the CHR(10) represents a line break.
So I am glad to provide a workaround which is using "\<br/>"  tag to inserts a line break. It is consistent on both sides.
I hope it can help you~
