### ISSUE TITLE
Add-ins not showing up on Android/iOS web browsers

### ISSUE THREAD

**Issue by s-pilkhwal** [OfficeDev/office-js#2104]
Outlook add-ins are missing on Android/iOS web browsers

* Platform : Mobile Phones (Android / iOS)
* Host : Outlook
* Office version number: latest (outlook.com)
* Operating System: Android, iOS
* Browser (if using Office on the web): Chrome, Safari, Brave, Firefox
 
## Expected behavior
Installed add-ins list should be displayed and add-in should work as expected

## Current behavior
Installed add-ins list is missing.

**Comment by exextoc** [comment]
Currently Outlook Add-ins are not supported on Android/iOS web browsers. We track Outlook add-in feature requests on our Tech Community Page. Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by s-pilkhwal** [comment]
If possible, Can you please provide any links to community announcement/documentation about removal of support for Android/iOS web browsers. It would be really helpful.

**Comment by exextoc** [comment]
Please check https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-mobile-addins . It says
 Important
Add-ins don't work in the modern version of Outlook in a mobile browser. For more information, see[ Outlook on your mobile browser is being upgraded.](https://techcommunity.microsoft.com/t5/outlook-blog/outlook-on-your-mobile-browser-is-being-upgraded/ba-p/1125816)
