### ISSUE TITLE
Outlook - item.saveAsync results in Error 9022 - MessageInDifferentStoreError

### ISSUE THREAD

**Issue by carlosb1504** [OfficeDev/office-js#2105]
We are using the new [`onNewMessageCompose` Launch Event](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch) to pre-save the Message at the point that the user begins to compose it. That's working fine but we have hit an issue whereby if the user then switches the sending account via the 'From' drop down (pictured) in the Message Compose pop-out
![image](https://user-images.githubusercontent.com/47693383/132504258-eb60cb0b-da66-4e6e-b73a-6cecdaeffc22.png)
then subsequent calls to `item.saveAsync()` fail with the above OSA.DDA error, see screenshot: 
![image](https://user-images.githubusercontent.com/47693383/132504429-438e9948-6a22-4df9-8e25-357c90821afe.png)
meaning we are unable to obtain the restId of the message in order to call Graph API with it in our code as we would like to.

I can understand why we are seeing this, because as the message states (albeit with misleading 'EWS' terminology), Outlook is detecting that this message has already been saved under another account. The question is: is there a way to work around this, such that we can _re-save_ the message in the account that has been switched to, so that we can obtain a valid restId and continue processing of the message, or any other suggestions we might have missed to deal with this?

Many thanks

**Comment by exextoc** [comment]
Currently the feature: re-save a message to a different store, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by carlosb1504** [comment]
Hello @exextoc - thanks for the reply. The link you supplied to request this feature shows a 404 unfortunately - can you advise on the correct link? We have a few other things we would like to vote for too if possible.

Thanks

**Comment by exextoc** [comment]
Our bad! Updated the link on the previous comment, worth giving it a shot now

**Comment by carlosb1504** [comment]
Thanks @exextoc - will take a look at what's there and add something on - although I'm not sure if I like my odds 🤣
![image](https://user-images.githubusercontent.com/47693383/132679786-a7991ca6-b343-4d97-9b0d-6389082e932d.png)

**Comment by cody-lettau** [comment]
Are there any known workarounds for this issue?

I also wouldn't consider this a feature request (and hence should not be closed). This seems more like a bug considering the message is saved under a different inbox, where it should not be. By not allowing a save to occur after changing the sender, there could easily be a leak of data across mailboxes.
