### ISSUE TITLE
Number format `hh:mm` is given as `h:mm` on Excel for Mac

### ISSUE THREAD

**Issue by Rinzwind** [OfficeDev/office-js#2107]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

On Excel for Mac, for a cell with number format `hh:mm`, `Range.numberFormat` gives the format as `h:mm`.

The Script Lab snippet given below sets up an example as follows:

```
const range = sheet.getRange("A1:B1");
(range.values as any) = 9 / 24;
range.numberFormat = [["h:mm", "hh:mm"]];
```

On Excel for Mac (v16.52, 21080801; using macOS 10.15.7), the snippet then logs:

```
range.text: 9:00,09:00
range.numberFormat: h:mm,h:mm
range.numberFormatLocal: u:mm,uu:mm
```

Note that the `text` for both cells is different (`9:00` versus `09:00`), and that `numberFormatLocal` also gives different formats for the cells as expected (`u:mm` versus `uu:mm`). However: `numberFormat` unexpectedly gives the same format `h:mm` for both cells.

For comparison, in Office on the web (using Chrome 93.0.4577.63), the snippet logs the expected result where `numberFormat` gives a different format for the two cells:

```
range.text: 9:00,09:00
range.numberFormat: h:mm,hh:mm
range.numberFormatLocal: u:mm,uu:mm
```

**Complete Script Lab snippet:**
```
name: 'Test Number Format HH:MM'
description: ''
host: EXCEL
api_set: {}
script:
  content: |
    (async () => {
      await Excel.run(async (context) => {
        const sheet = context.workbook.worksheets.getActiveWorksheet();
        const range = sheet.getRange("A1:B1");
        (range.values as any) = 9 / 24;
        range.numberFormat = [["h:mm", "hh:mm"]];
        await context.sync();
      });
      await Excel.run(async (context) => {
        const sheet = context.workbook.worksheets.getActiveWorksheet();
        const range = sheet.getRange("A1:B1");
        range.load(["text", "numberFormat", "numberFormatLocal"]);
        await context.sync();
        console.log(`range.text: ${range.text}`);
        console.log(`range.numberFormat: ${range.numberFormat}`);
        console.log(`range.numberFormatLocal: ${range.numberFormatLocal}`);
      });
    })();
  language: typescript
template:
  content: ''
  language: html
style:
  content: ''
  language: css
libraries: |
  https://appsforoffice.microsoft.com/lib/1/hosted/office.js
  @types/office-js
```

**Comment by ElizabethSamuel-MSFT** [comment]
@Rinzwind Thanks for bringing this to our attention.

@lumine2008 Can you take a look?

Thanks.

**Comment by gingerjia** [comment]
@Rinzwind, thanks for reporting the issue. 
We can repro it on MAC and bug 5411990 was created for track it. When have progress, will update the thread to let you know.
If have any other issue, please let us know. Thanks!

**Comment by gingerjia** [comment]
@Rinzwind We are doing a survey to understand the pain points of add-in’s developing experience. Would you mind to help fill this survey https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR5eAlIUFFQFHqE95qTMqQuVURVE4QkZPREoxOEk1TFEySDMyQTc0U0o0Ti4u ? It should take less than 5 minutes and will be supper helpful for us. Thank you!
