### ISSUE TITLE
Office JS: Word: Get page orientation and size

### ISSUE THREAD

**Issue by jrpally** [OfficeDev/office-js#2110]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am trying to get page orientation and size, for this purpose I am using this code:

**THE CODE FOR WORD OFFICE ONLINE DOES NOT WORKS! EVEN IF YOU CHANGE THE PAGE MARGINS, IT DOES NOT CHANGE THE OOXML!! I THINK IS A BUG**

```
let header = context.document.sections.getFirst().getHeader('primary');
let ooxml = header.getOoxml();
await context.sync();
let _size: ISize = this.getSize(ooxml.value);
```

In the code getSize I process the XML:

```
<w:sectPr w:rsidR="00000000" w:rsidSect="008D1670">
    <w:pgSz w:w="15840" w:h="12240" />
    <w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/>
    <w:cols w:space="720"/>
    <w:docGrid w:linePitch="360"/>
</w:sectPr>
```

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: ______Word
* Office version number: ______Office 2019
* Operating System: ______Windows 10
* Browser (if using Office on the web): ______
 
## Expected behavior

header.getOoXml() should get the page size including orientation Example:
```
<w:sectPr w:rsidR="00000000" w:rsidSect="008D1670">
	<w:pgSz w:w="15840" w:h="12240" w:orient="landscape"/>
	<w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/>
	<w:cols w:space="720"/>
	<w:docGrid w:linePitch="360"/>
</w:sectPr>
```

## Current behavior

It is getting the XML without orient attribute:
`<w:pgSz w:w="15840" w:h="12240" w:orient="landscape"/>`

## Isolation:
If I use 
`context.document.body.getOoxml()`

It returns orient='landscape' but I can't use body getOoxml for performance. (Example larger documents).

Any way to read the orientation faster?

**Comment by AbidRahman-MSFT** [comment]
Hey @jrpally thanks for reporting the issue. @RuoyingLiang, this looks to be specific to Word on Web, can you please investigate?

**Comment by jrpally** [comment]
Ys @AbidRahman-MSFT is specific for Word on Web
