### ISSUE TITLE
Word addin: context.document.body.text contains the comments as one character

### ISSUE THREAD

**Issue by ndvbd** [OfficeDev/office-js#2114]
I see another issue now, which "kills" our add-ins.
The context.document.body.text returns the comments as well (which ruins the text). The comment appears as a special character in the text \x05
I believe comments should not appear there. Can you fix it please?

I saw that behaviour on Word 365 (desktop) on Windows.

**Comment by AbidRahman-MSFT** [comment]
Hey @ndvbd - unfortunately, this is by design. 

As a workaround, try the following snippet that removes all comment characters from the text of the document body:

```
async function run() {
  await Word.run(async (context) => {
    const body = context.document.body;
    body.load('text');
    await context.sync();
    const txt = body.text.replace('\x05','');
    console.log(txt);
    console.log(txt.length);
  });
}
```

**Comment by ndvbd** [comment]
@AbidRahman-MSFT What is the link to the online documentation showing this behaviour? How should developers know about this?

**Comment by AbidRahman-MSFT** [comment]
Hey @ndvbd, we will work with the documentation team to ensure this is correctly documented as part of the Body.text documentation. Thanks for your patience.
