### ISSUE TITLE
How to open taskpane programmatically in desktop outlook

### ISSUE THREAD

**Issue by mohamadAtlassian** [OfficeDev/office-js#2115]
## How to open taskpane programmatically in desktop outlook

Outlook 2013 is using internet explorer as a browser, and that is causing so much problem in our add-in. The add-in is not stable and can't keep fixing bugs caused by internet explorer dialog . I am searching for a way to use taskpane instead of dialog because it is much more stable. However, I didn't find a way to open task pane programmatically, is there any office api or method to open task pane programmatically in outlook 2013 ?

**Comment by exextoc** [comment]
Currently the feature: open taskpane programmatically with in web add-in, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](https://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process. 

Note that new feature requests are typically evaluated for upcoming releases of Office
