### ISSUE TITLE
[Outlook] Stuck in infinite loop when I try to response to send event. (Mac Only)

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#2116]
Precondition:
Need install a Mac plugin which will also response to send event.

Add-in will stuck in a infinite loop if I try to response to send event. The problem looks like Mac plugin was triggered by the send event then send that event again. And Add-in triggered by this event. Then using completed({allowEvent: true}) send the event again. 
But the problem is at this time Mac plugin and add-in were triggered again and again.
And If I use other parameter in completed function like, completed(true)/completed(), the whole send process is blocked.
What I'm curious about is that logically, the event triggering mechanism should have its own limitations and will not be triggered for the second time. However, considering that there are two different platforms, they may be triggered by each other. However, add in can do nothing about such problems, because the completed interface logic will hijack the send event. Can we make some changes?
My suggestion is:
1. Trigger add-ins before Mac plugin, just like windows which have no problem.
2. When you want add in to receive the on send event, you can choose not to block.

Note: This problem will not happen on windows. Because Windows plugin will be triggered right after add-in.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.52 (21080801)
* Operating System: Mac 
* Browser (if using Office on the web): NA
 
## Expected behavior
When install a Mac plugin which will response to send event. Add-in will not stuck in a infinite loop. 

## Current behavior
Add-in will not stuck in a infinite loop. 

## Steps to reproduce
Add-in will stuck in a infinite loop if I try to response to send event. The problem looks like Mac plugin was triggered by the send event then send that event again. And Add-in triggered by this event. Then using completed({allowEvent: true}) send the event again. 

This is not only a problem for add-in also is a problem for Mac plugin. But as an add-in developer , I wish I can get some suggestions. 
Thanks

**Comment by exextoc** [comment]
@SWei1234 Thanks for raising the issue. We tried it from our end but we were not able to repro it. We would like to get to know the following things for better clarity.

  1. What is the use case in which a plugin and an add-in are being run together if so?
  2. Please provide the plug-in and add-in links so that we can repro the exact problem.
  3. Can you please provide a short video of the issue?

**Comment by SWei1234** [comment]
Hi @exextoc 
Thank you very much for giving me help on this ticket.
Can you provide me a email address for sharing this recording?
Thanks

**Comment by exextoc** [comment]
Sure, please share the recording to OutlookAddins@M365x693897.onmicrosoft.com .

**Comment by SWei1234** [comment]
Hi @exextoc 
Already send the recording to your mailbox. 
If any question please reply here.
Thanks

**Comment by exextoc** [comment]
@SWei1234 Thanks for the recording. On looking at it, we could see that you are trying in the old outlook UI. Can you please update and try it the New Outlook for Mac. You can switch by using the toggle on the top. [Link to new Outlook for Mac: https://support.microsoft.com/en-gb/office/the-new-outlook-for-mac-6283be54-e74d-434e-babb-b70cefc77439]

Also, we are unable to repro the issue, could you please share the add-in code as well for a better understanding?

**Comment by SWei1234** [comment]
Hi @exextoc 
Yes, I'm trying on old UI Mac Outlook.  But I think before Microsoft force every one use new UI, add-in still need handle this.
For manifest file, I add below:
`<ExtensionPoint xsi:type="Events">
              <Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="onSendFunction" />
 </ExtensionPoint>`

My onSendFunction function is:
`function onSendFunction(event) {
    event.completed({allowEvent: isCompleted});
    return;
}`

Function file code is like:
import { onSendFunction } from 'script/onSend'
window.onSendFunction = onSendFunction;

Thanks

**Comment by exextoc** [comment]
@SWei1234  We are unable to repro the issue from our side with the code changes that you specified.
Kindly share the add-in to OutlookAddins@M365x693897.onmicrosoft.com and we would like to collect the logs to understand the issue more. 

Kindly follow these steps to get us the incident ID: 

1. Repro the issue 
2. Click on the Help tab from Outlook Menu 
3. Click on collect Diagnostics 
4. This will generate an Incident ID, share that with us.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.

**Comment by SWei1234** [comment]
Hi @exextoc 
Just want to confirm, is there a way we can forbidden/deactivate some plugin when add-in is installed?
If we can, this might be another way to solve this problem.
Thanks
