### ISSUE TITLE
saveAsync not working rightly when try to saving a draft (Add-in, Outlook)

### ISSUE THREAD

**Issue by thao33** [OfficeDev/office-js#2118]
# call saveAsync for draft item. Response is success but return body is out-of-date. It returns the old body when saving draft.
Maybe saveAsync not worked rightly at cache mode of Outlook or something like that..

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: only PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.52(21080801)
* Operating System: windows 10
 
## Expected behavior
getGetItem (by SOAP) after saveAsync will return right body of email.
References: https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/getitem-operation-email-message

## Current behavior
response's body is older version of it. (when saving draft)

## Steps to reproduce

1. Create a draft with subject and body
2. Open draft at step 1
3. Edit body (add more contents)
4. call saveAsync to get ItemId
5. makeEwsRequestAsync to get item's detail
6. at callback function of step 5, checking body from response and it's not return rightly body 
7. because callback function of step 5 response is success, so we trigger send email
8. At receiver's email, check the body of it and it's not the expectation result.

## Context
My add-in trigger send client email. From composing window, it works. But from draft item, it doesn't.

**Comment by exextoc** [comment]
The issue you are observing looks to be related to inconsistent item state. Changes made to an item using the Office.js API, including saveAsync, go to the client first and these changes, when using Outlook Desktop in Cached Mode, are not synced to the exchange server immediately. Instead the server copy of the item gets updated when Outlook Desktop sync's with exchange. This matches your observation from your repro steps at step 6 that the body from EWS response does not have the updated content.
 
To avoid this problem, it is recommended that all changes to the same item be made either via REST/EWS or through the Office.Js API's. Mixing the two can result in conflicts. If this is not possible, then we have seen partners following the pattern of not making the changes via REST/EWS until they have detected the change that were made from the client. 

We understand this is not ideal and we are trying to move as many server side API's to the Office.JS API suite as possible. Please help us understand your scenario, of why the addin needs to trigger sending of the email. We also encourage you to request this feature at our [Tech Community](https://aka.ms/M365dev-suggestions) page.

**Comment by thao33** [comment]
@exextoc 
Thank you for your support.

> To avoid this problem, it is recommended that all changes to the same item be made either via REST/EWS or through the Office.Js API's. Mixing the two can result in conflicts.

Sorry but I don't really understanding how to mixing the two of them.. Could you please guide me more?

Let me describe my add-in scenario.

My add-in basically do 2 things bellow:
1. collect mail subject, body
2. by clicking add-in own "Send" button (not outlook "Send" button) : we not only trigger Exchange server sending client email, but also sending data at step 1 to my server for business.

**Comment by exextoc** [comment]
Thanks for clarifying the method used to send the email.

Calling saveAsync in Outlook for Windows will save the message locally (if Outlook is running in cached mode), but there is a delay before the message is synced up to the server. Calling GetItem through makeEwsRequestAsync will return the server's copy of the message, and asking Exchange to send the message also sends the server's copy.

So in a sense, there are potentially 3 versions of the message (or, 3 places where the message can be observed):
1. The version that the sender sees in Outlook (before sending the message)
2. The version returned by GetItem
3. The version sent to other users
 
In your testing, you mentioned the version received by other users (#3 in the list above) is not the expected result. Does that version differ from #1 or from #2 (or from both)?

**Comment by thao33** [comment]
@exextoc Thank you for quick response.

> In your testing, you mentioned the version received by other users (#3 in the list above) is not the expected result. Does that version differ from #1 or from #2 (or from both)?

In our add-in, version #3 is the same version #2, both (out-of-date) are differ from version #1 (it's up-to-date)

**Comment by thao33** [comment]
I have more details for this issue.

This reproduce steps are quite the same as the one which i said before at https://github.com/OfficeDev/office-js/issues/2118#issue-994809825
But, important is it has up-to-date body.

## Steps to reproduce
1. Create a draft with subject and body
2. Open draft at step 1
3. Edit body (add more contents)
4. **Save it as draft and leave it**
5. **Back to editing but do nothing (edit nothing)**
6. call saveAsync to get ItemId
7. makeEwsRequestAsync to get item's detail
8. at callback function of step 7, checking body from response and it's **up-to-date** body 
9. because callback function of step 5 response is success, so we trigger send email
10. At receiver's email, check the body of it and **it's the expectation result.**

**Comment by thao33** [comment]
@exextoc I am sorry to rush you, but any update on this issue? Our clients still facing this.. So hope to hear from you soon.

**Comment by exextoc** [comment]
A delay is expected for the item to reach the server. Do you have an add-in backend?

**Comment by thao33** [comment]
@exextoc 
We already try to adding setTimeout to getItemId/saveAsync step but nothing changed..

```
      setTimeout(function() {
        mailboxItem.saveAsync(function(result) {
          if(result.status == RESPONSE_SUCCESS) {
            localStorage['id'] = result.value;
            resolve(result.value);
          } else {
            senseData.loopGetItemId(LONG_DELAY, resolve);
          }
        });
      }, 30000);
```

> Do you have an add-in backend?

For sending data to our server? Yes !

**Comment by exextoc** [comment]
A couple of things to clear up:

> I have more details for this issue.
> 
> This reproduce steps are quite the same as the one which i said before at [#2118 (comment)](https://github.com/OfficeDev/office-js/issues/2118#issue-994809825) But, important is it has up-to-date body.
> 
> ## Steps to reproduce
> 1. Create a draft with subject and body
> 2. Open draft at step 1
> 3. Edit body (add more contents)
> 4. **Save it as draft and leave it**
> 5. **Back to editing but do nothing (edit nothing)**
> 6. call saveAsync to get ItemId
> 7. makeEwsRequestAsync to get item's detail
> 8. at callback function of step 7, checking body from response and it's **up-to-date** body
> 9. because callback function of step 5 response is success, so we trigger send email
> 10. At receiver's email, check the body of it and **it's the expectation result.**

Based on your response here, you said you are getting the expected result in step 10, so what is the issue/unexpected behavior here?

As for the code you shared in the most recent comment:
> @exextoc We already try to adding setTimeout to getItemId/saveAsync step but nothing changed..
> 
The timeout you are setting here is delaying the call for saveAsync and will not help with the sync issue between client side and exchange servers. It is advised on our [documentation ](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#:~:text=does%20not%20exist.-,saveAsync(callback),-Asynchronously%20saves%20an)that using the returned itemId from saveAsync with EWS requests could have sync issues. As a workaround, after calling saveAsync you can continue to compare the result from makeEwsRequestAsync to the original unedited item body until you can confirm the item is updated in the exchange server.

**Comment by thao33** [comment]
@exextoc 
> Based on your response here, you said you are getting the expected result in step 10, so what is the issue/unexpected behavior here?

Oh, repro steps are quite the same... sorry to make you confused.

The diff point is: At unexpected result repro steps, highlighted step 4 and 5 not be included.

So, repro is described in a sentence like this
1. Context1 : When the result is **unexpected**:
User have a draft email, start to edit, then send it through my add-in.

2. Context2: When the result is **expected**:
User have a draft email, start to edit, but before sending, user save it again as draft by manual and click to another draft. Then back to saved draft before and send it through my add-in.

-------
> As a workaround, after calling saveAsync you can continue to compare the result from makeEwsRequestAsync to the original unedited item body until you can confirm the item is updated in the exchange server.

I'll try it again. But I know this resolution has its own problems because i tried it once before. The body return from `makeEwsRequestAsync` is not the same the one from `Office.mailbox.item.body.getAsync(Office.CoercionType.HTML, callback)` method. Some html tags in makeEwsRequestAsync response not be found at response of Office.mailbox.item.body.getAsync. So, basically, can't using `include` to compare.. It sucks..

> It is advised on our documentation that using the returned itemId from saveAsync with EWS requests could have sync issues.

Could have sync issues?? But the document also said "Until the item is synced, using the itemId will return an error.", right?
In my case, the return is not an error, it's Office.AsyncResultStatus.Succeeded..

**Comment by exextoc** [comment]
I think there may have been some confusion as to what may be going on here. 

Here are some facts that may explain what is going on: 

- item.body.getAsync() will return to you the HTML that is saved to the mail item at that time. This can be different than the HTML that eventually gets sent, as Outlook will sometimes adjust HTML/Tags etc during the sending process. It should render the same as it looks visually though to another Win32 Client when it is received. 

- After an email is sent, the itemid is no longer valid. ItemId's are folder based, so in the process of sending an item Id moves the item from the drafts folder -> outbox -> Sent items. There is currently no way to get the ItemId of the item in the Sent Folder.

- If you are saving changes to an email to the server via EWS with the ItemId, and making changes to the item locally with the client, this is going to result in conflicts. (usually the last writer wins...) If you are just reading properties from the server, that should be fine.

Some questions: 
- What scenario are you trying to achieve? It's unclear to me why you are using the ItemId to get the Body via makeEwsRequestAsync(), instead of just using item.body.getAsync(). 

- How are you triggering "send" of an email? (we don't have a client side API to do this...) are you just relying on the user to hit send?

-  I'm not sure about this comment _"Could have sync issues?? But the document also said "Until the item is synced, using the itemId will return an error.", right?
In my case, the return is not an error, it's Office.AsyncResultStatus.Succeeded.."_ 

The EWS call will only return an error if the item is not there. Otherwise, it will return success, even if it isn't the latest version. Can you point to the documentation that calls this out?

**Comment by exextoc** [comment]
Is this what you are trying to do? 

1) On the Client Side modify the item
2) Wait for the update to the server
3) Use an EWS call to send the email? 

The problem being that in step #2, you have trouble detecting if the body is truly updated at the body can be slightly different from the one you get from item.body.getAsync() ? 

If this is the case, using the body as an indicator as to when the server updates, is probably not the best way to go about it. 
What you could do, is use CustomProperties to save some sort of custom value, before you call save(). Then check for that custom property, instead of checking the body. 

See: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/metadata-for-an-outlook-add-in

For info on checking custom Properties.

**Comment by thao33** [comment]
Thank you for your explanation.

> What scenario are you trying to achieve? It's unclear to me why you are using the ItemId to get the Body via makeEwsRequestAsync(), instead of just using item.body.getAsync().

No, i just get the Body via makeEwsRequestAsync() to compare it's update-to-date or out-of-date (just for debugging purpose)

> How are you triggering "send" of an email? (we don't have a client side API to do this...) are you just relying on the user to hit send?

With our add-in design, if add-in not triggering "send" email, user have one more step to finish "send email" job. So, we have "Send" button at add-in, which do 2 things: 1 - triggering send email via EWS, 2 - send some data to our servers.

> The EWS call will only return an error if the item is not there. Otherwise, it will return success, even if it isn't the latest version

Oh.. "even if it isn't the latest version" is the part i didn't understand when read documents. Sorry for expecting sth not existed from beginning.

-------------

So, i have only one question this time.

Suppose i figured it out the the way to compare the result from makeEwsRequestAsync to the original item body as you said. And the comparing result is out-of-date body. So, which method we should use to tell EWS that "hey, the version of email at EWS is out-of-date, can you force sync it right now for me?" 

> after calling saveAsync you can continue to compare the result from makeEwsRequestAsync to the original unedited item body until you can confirm the item is updated in the exchange server.

**Comment by thao33** [comment]
oh, sorry i missed  https://github.com/OfficeDev/office-js/issues/2118#issuecomment-940550053

Thank you, i'll try CustomProperties.

**Comment by exextoc** [comment]
> Suppose i figured it out the the way to compare the result from makeEwsRequestAsync to the original item body as you said. And the comparing result is out-of-date body. So, which method we should use to tell EWS that "hey, the version of email at EWS is out-of-date, can you force sync it right now for me?"

There is unfortunately no way to do this. 

I think the CustomProperty method is probably the best way to tell if the item is out of date.

**Comment by thao33** [comment]
@exextoc Thank you for your support.
> There is unfortunately no way to do this.

Ok. Thank you.

> I think the CustomProperty method is probably the best way to tell if the item is out of date.

I've tried it. By now, just like magic, problem solved !! Thank you so much for suggesting me.

I'm really appreciate !!
