### ISSUE TITLE
Office.context.mailbox.displayNewAppointmentForm method opens up a new appointment window but always shows "Reminder" as "None" even when the default is set to some value on Mac Outlook 2016

### ISSUE THREAD

**Issue by bandhan-nawal** [OfficeDev/office-js#212]
## Expected Behavior

I have set the Reminder on Outlook 2016 for Mac Preferences -> Calendar -> Default Reminder (say 15 minutes). In my add-in when I click on a button to open new appointment window using Office.context.mailbox.displayNewAppointmentForm method, the reminder should be shown as 15 minutes. This is working as expected for Outlook for Windows and OWA. Its should also work the same in Mac Outlook 2016.
## Current Behavior

In Mac Outlook 2016, on clicking the button which calls Office.context.mailbox.displayNewAppointmentForm method opens an appointment window which always shows "Reminder" as "None".
## Steps to Reproduce, or Live Example

* Link to live example:
Please add the add-in into your Outlook for Mac from Office Store named "ConX Scheduler for Outlook" (Search "Infocus ConX Scheduler").

* Additional details:
  1. Go to Outlook Preferences->Calendar->Default Reminder->Set some value(say 15 min).
  2. Click on second option "Schedule ConX Meeting" in the add-in's dropdown menu.
  3. A new appointment window will open with some values in Subject, Location and Body.
  4. Opened appointment, now showing Reminder to "None" whereas reminder set to 15 min.

## Context

There is an inconsistent behaviour between all the Outlook platforms for our add-in. On Windows and OWA, Office.context.mailbox.displayNewAppointmentForm method opens an appointment with Default set "Reminder" but for Mac, it always displays "None" even if it is set to some value.

## Your Environment

* Platform: Mac
* Host: Outlook
* Outlook for Mac version number: 16.15 (18070902)

**Comment by macOutlookExtensibility** [comment]
Thanks for reporting the issue. We will take this up as a bug fix.

**Comment by exextoc** [comment]
Is there a way to assign to @macOutlookExtensibility?

**Comment by macOutlookExtensibility** [comment]
This bug is fixed and fix is available from builds 180813 onwards

**Comment by neso613** [comment]
@macOutlookExtensibility 
 This issue again seen in ConX Outlook add-in. Is this is again changed by API release. Please help me for this issue.

**Comment by exextoc** [comment]
@nehasoni3  We weren't able to find the Add-in "ConX Scheduler for Outlook" in store. Can you confirm if the Add-in is still available in store for installation? Please do share a screenshot of the Add-in in store if possible.
We were not able to repo this issue from our side when we tested Office.context.mailbox.displayNewAppointmentForm API independently. The reminder value is being picked from Outlook settings. If you are still facing this issue, Could you please provide the Mac Outlook Version number as well?
