### ISSUE TITLE
Microsoft Word 16.0.14326.20164 crashes while executing: distributeColumns()

### ISSUE THREAD

**Issue by jrpally** [OfficeDev/office-js#2120]
**context.document.body.tables.items[0].distributeColumns();** makes the MS Office to crash

Literally execute using the Script Lab tool the following code:

```
$("#run").click(() => tryCatch(getTableCell));
$("#setup").click(() => tryCatch(insertTable));

async function getTableCell() {
  await Word.run(async (context) => {
    let firstCell = context.document.body.tables.getFirst().getCell(0, 0).body;
    await context.sync();
    context.document.body.load('tables/items/length');
    await context.sync();
    context.document.body.tables.items[0].distributeColumns();
    await context.sync();
    firstCell.load("text");

    await context.sync();
    console.log("First cell text is " + firstCell.text);
  });
}

async function insertTable() {
  await Word.run(async (context) => {
    // Use a two-dimensional array to hold the initial table values.
    let data = [
      ["Tokyo", "Beijing", "Seattle"],
      ["Apple", "Orange", "Pineapple"]
    ];
    let table = context.document.body.insertTable(2, 3, "Start", data);
    table.styleBuiltIn = Word.Style.gridTable5Dark_Accent2;
    table.styleFirstColumn = false;

    await context.sync();
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}

```

**Comment by AbidRahman-MSFT** [comment]
Hey @jrpally, are you seeing this issue on Windows, Mac or on Web? Can you also please provide additional version information?

**Comment by jrpally** [comment]
Hi @AbidRahman-MSFT This is happening in Office for Desktop. The version is specified in the bug report. I have a memory dump 700 MB if you want I can submit the place you provide.

**Comment by jrpally** [comment]
HI @AbidRahman-MSFT I just tested on Office Online and all works fine. I do not have MAC to test it.

For now the bug is for Word desktop

**Comment by AbidRahman-MSFT** [comment]
Can also reproduce on Mac, thank you for creating the issue. We will investigate and get back to you.

**Comment by jrpally** [comment]
@AbidRahman-MSFT Not only distributeColumns is making the product crash, also :
context.document.body.tables.items[0].**autoFitWindow()**;

**Comment by yihuax-msft** [comment]
@jrpally @AbidRahman-MSFT Certainly Word should not crash, no matter what. We will make our APIs more robust. Thanks for letting us know the issue. We will fix the crashing issue.

In the meantime, you can make the API calls simpler. For example, you don't need to keep using context.document.body.tables, which increase the traffic with the host. You can just assign it to a local variable and the crash can be avoided. That is the style we commonly use and that is why we didn't notice the issue earlier. You can do this way:

async function getTableCell() {
  await Word.run(async (context) => {
    let firstTable = context.document.body.tables.getFirst();
    let firstCell = firstTable.getCell(0, 0).body;
    firstTable.distributeColumns();
    firstCell.load("text");
    await context.sync();
    console.log("First cell text is " + firstCell.text);
  });
}

**Comment by jrpally** [comment]
Thanks for the response @yihuax-msft
