### ISSUE TITLE
Custom Functions - allow streaming function to be volatile

### ISSUE THREAD

**Issue by jordandev** [OfficeDev/office-js#2122]
We are using streaming custom functions to load data from an external service and give users a refresh rate parameter (ex. refresh every 5 seconds, every 5 minutes, etc).

The issue we have found is that streaming functions do not refresh if - F9, Ctrl+F9, pressing Enter in the functions cell, clicking Calculate Now / Sheet. I believe this is expected because Excel sees this formula as not having "changed" because the parameters haven't changed. This means that a user cannot easily manually refresh the formula data (Ctrl+Alt+Shift+F9 seems to be the only way, which is not very familiar for users).

So volatile formulas are the way to handle this. But @stream and @volatile are mutually exclusive for some reason. I am not sure if there is a bigger underlying reason for this but for us we really need both @stream and @volatile on the same function. Otherwise we need to make two versions of the same formula, one for streaming and one being volatile, which just adds to user confusion.

**Comment by grangeryy** [comment]
@jordandev, currently the behavior is by design. Have you tried ctrl+alt+f9?

**Comment by jordandev** [comment]
I realize it is by design yes. But we are getting feedback that this is confusing for users as they are functions that rely on external data that can change frequently regardless of parameters but cannot be volatile if they are streaming. So it puts these functions into a weird place where they need to be both volatile but have the ability to update without interaction as a streaming function. But this is not possible with these being mutually exclusive.

Using Ctrl+Alt+F9 is really just not obvious enough to users for whatever reason (yes we can try to train users, but not easy). We don’t want to have to implement our own specific “Calculate” button to refresh our streaming functions manually as that is quite awkward but it may come to that to give users a more obvious way. 🤷🏻‍♂️

Even just being able to refresh if the formula cell is edited and Enter is pressed would help a lot instead of needing fully volatile. It is not clear to users why the data doesn’t update when they know it has changed externally in this case.

It’s like there needs to be a 3rd category of functions that are not fully volatile but rely on external data so refresh with Calculate Now / formula cell edit / etc but not every cell edit in the sheet like volatile. Anyways I’m not trying to reinvent Excel behaviour here so was just hoping that @stream and @volatile didn’t have a blocking reason they couldn’t co-exist but if this is really necessary we will have to make due. Thanks

**Comment by XuanZhouMSFT** [comment]
Thanks for waiting. Currently the feature you requested is not a part of the product. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process.
