### ISSUE TITLE
ooxml trackrevision absent using getOOXML() function

### ISSUE THREAD

**Issue by rulopimentel** [OfficeDev/office-js#2123]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When we use getOOXML() function according to https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#getOoxml__ documentation, it returns the flattened XML. However, it does not returns the trackRevisions (aka track changes) element.

# Word Add-In trackRevisions (aka track changes) missing from ooxml data

## Your Environment

* Script Lab
* Add-In test https://gist.github.com/rulopimentel/782c762df26ec61c0ad4dd9465fa0043 
* Microsoft Word desktop
* Office version number: 365 suscription
* Operating System: Windows 10
* Browser (if using Office on the web): webview2
 
## Expected behavior
The getOOXML() function must returns in the settings package the trackrevision element when the  "Track Changes" ribbon button is active.

## Current behavior
The getOOXML() function does not returns in the settings package the trackrevision element when the "Track Changes" ribbon button is active. But, if you read the docx file XML packages, you can find it in the settings.xml file.

## Steps to reproduce

1. Install Script Lab add-in in the Microsoft Word
2. Open the script from https://gist.github.com/rulopimentel/782c762df26ec61c0ad4dd9465fa0043 
2.  Activate "Track Changes" ribbon button
3. Write in the document body any text.
4. Save the document.
5. Open the document with an OOXML viewer. Search by the Settings.xml and verify that the trackrevision element is present.
6. Run the Script Lab script and push the button "OOXML". Copy the console result and paste it into the blocknotes application.
7. Search by the Settings.xml and verify that the trackrevision element is absent.

## Context
Before updating or save a word document I need to verify if the "Track Changes" is turned off, because when I load another document body using the insertFileFromBase64 function, all the body is marked as a change.

**Comment by AbidRahman-MSFT** [comment]
Hey @rulopimentel - what are you attempting to do with the settings.xml part of the OOxml? Are you trying to turn Track Changes on/off by modifying the xml?

**Comment by rulopimentel** [comment]
At the moment I would like to know if the Track Changes button is on. Our Add-In loads a remote document to update their content, but when the user leaves the Track Changes button on, and the next document is loaded, calling the context.document.body.clear() and context.document.body.insertFileFromBase64 functions, the new document body is marked as a Track change.

So, if we could know if the Track Changes button is activated, we could show a message to the user asking him to disabled the button before update the remote document. However, if I use the getOOXML()  function, it does not return the trackrevision node in the XML.

**Comment by rulopimentel** [comment]
Hi @AbidRahman-MSFT  
Please let me know if you need any further information

**Comment by handofthecode** [comment]
@rulopimentel You can use the word API to generate a docx file. Then just unzip it and look in that settings.xml for the trackRevisions tag. Confirmed working 👍

**Comment by rulopimentel** [comment]
Hi @handofthecode . You are correct, unzipping the file and looking in  settings.xml you can find the "trackRevisions" tag. However, if you are using the Word API to get this value using the getOoxml() function ( [Word.Body class - Office Add-ins | Microsoft Docs](https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#getOoxml__)), the "trackRevisions" tag is missing.

This open issue is about this behavior because I need to know the "trackRevisions" tag (using the Word API in execution time) before sending its oxml content to an Endpoint.

**Comment by handofthecode** [comment]
I achieved the same thing you're trying to do.

Since the getOoxml() method doesn't return what you need, you can **use the word API** to generate the docx file and parse it on the client (or send it to a service if you prefer) to extract the tag from settings.xml.
