### ISSUE TITLE
Our Excel add-in crashes for a client on version 2108 with build number: 14326.20238 (fixed by updating to a newer build)

### ISSUE THREAD

**Issue by cidev5** [OfficeDev/office-js#2124]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We would like some background on an issue a client reported to us using our add-in that is specific to the Excel version in the title.

I've attached two screenshots below.

We would like to know what is the cause of this error, and why it would occur on some machines with this Excel version and not on another machine with the same version of Excel installed.

We would also like to know to as of when this bug can be traced, i.e. when was it introduced.

## Current Behavior
The add-in fails to load and presents a blank white screen instead of the log in screen.

This started occurring only recently; about 2-4 weeks ago.

We addressed the client's issue today by upgrading from 14326.20238 to a newer build.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16 - version 2108 with build number: 14326.20238
* Operating System: Windows

## Useful logs

![Picture3](https://user-images.githubusercontent.com/22505624/133502551-20faee74-0eb2-4428-896c-9dc5922b11dc.png)
![Capture](https://user-images.githubusercontent.com/22505624/133502557-8cfe9fae-c99b-453e-9693-1c0942f5d703.PNG)

**Comment by AlexJerabek** [comment]
Thank you for reporting this @cidev5.

@lumine2008, could you please investigate?

**Comment by AlexJerabek** [comment]
@cidev5, may I also clarify that you're not seeing this issue in the latest available version, correct? Are all your users able to update the the latest version of Excel and avoid this issue?

**Comment by cidev5** [comment]
Hi @AlexJerabek, I myself could not reproduce the issue so I never experienced it. Only one user of our add-in so far had the issue, and after upgrading to what was the latest version at the time no longer experienced it. I do not know if there is a newer still available version and if the user has installed it. Any of our users who might encounter the issue should be able to update to the latest/fixed version of Excel and avoid the issue, yes.

**Comment by RuoyingLiang** [comment]
@cidev5 We are doing a survey to understand the pain points of add-in’s developing experience. Would you mind to help fill this survey https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR5eAlIUFFQFHqE95qTMqQuVURVE4QkZPREoxOEk1TFEySDMyQTc0U0o0Ti4u ? It should take less than 5 minutes and will be supper helpful for us. Thank you!

**Comment by gingerjia** [comment]
@cidev5, thanks for reporting the issue. But as you cannot repro it, and from the snapshot attached, we also didn't get enough info to help with the further diagnostic. So we would like to revisit it if the issue happens again. Please let us know if have any other concerns. Thanks!
