### ISSUE TITLE
Can't open task pane from link in Outlook NotificationMessages 

### ISSUE THREAD

**Issue by elegault** [OfficeDev/office-js#2125]
I'm setting a notification message as per this code:

````
function showInfoBar() {
  Office.context.mailbox.item.notificationMessages.addAsync("CommandsKey1", {
    type: Office.MailboxEnums.ItemNotificationMessageType.InsightMessage, //"insightMessage"
    message: "Open the Task Pane for more details",
    icon: "Icon.16x16",
    actions: [
      {
        actionText: "Show Task Pane",
        actionType: Office.MailboxEnums.ActionType.ShowTaskPane, //"showTaskPane"
        commandId: "msgComposeOpenPaneButton",
        contextData: "{''}",
      },
    ],
  });
}
````

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook Online
* Office version number: n/a
* Operating System: n/a
* Browser (if using Office on the web): Edge, Chrome
 
## Expected behavior
The task pane should open if the value of the commandId parameter for the Office.NotificationMessageAction interface matches the id of a Button Control element; e.g.:

````
<Control xsi:type="Button" id="msgComposeOpenPaneButton">
  <Label resid="msgComposeTaskPaneButton.Label"/>
  <Supertip>
    <Title resid="msgComposeTaskPaneButton.Label"/>
    <Description resid="msgComposeTaskPaneButton.Tooltip"/>
  </Supertip>
  <Icon>
...
  </Icon>
  <Action xsi:type="ShowTaskpane">
    <SourceLocation resid="msgComposeTaskpane.Url"/>
  </Action>
</Control>
````

## Current behavior
The task pane doesn't open by clicking the "Show Task Pane" link in the notification message.  However, the task pane does open if clicking a button defined in the manifest.

## Steps to reproduce
1. Create a new message to load the add-in
2. Click the link in the notification message

## Useful logs
The following error is shown in the DevTools console:
![image](https://user-images.githubusercontent.com/4130365/133531505-c85ce584-0385-433b-aad0-445e71fc44fd.png)

Note: this seems similar to #1388 but in a completely different context.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding the launch of the task pane from the Outlook Notification message. We are able to reproduce the issue, and it has been put on our backlog. We, unfortunately, have no timelines to share at this point.
Internal tracking id: Outlook Web: 128572

**Comment by JackTheDane** [comment]
Hi team,

Is there any progress or timeline for this bug at the moment? Our solution relies heavily on actionable messages to authenticate our users, and we've had to ask our users to open the taskpane manually for nearly a month at this point.

![image](https://user-images.githubusercontent.com/35668734/136362951-e5690cf7-1002-4153-8998-f128ef62d7ac.png)

Any information you could share would be appreciated.

**Comment by exextoc** [comment]
This issue is fix and currently rollout in the progress .We will update you once this reaches production

**Comment by exextoc** [comment]
@JackTheDane Fix has reached production. Can you please check and confirm if things are working for you? Thanks.

**Comment by JackTheDane** [comment]
@exextoc I have checked and can verify that in our use case, the action link works once again.

Big thanks to the team!

**Comment by elegault** [comment]
This is not working in Outlook Online, but is working in Outlook for Windows.

**Comment by exextoc** [comment]
@elegault Fix was rollingout last week. Can you please try again now to check if it is fixed for you?

**Comment by elegault** [comment]
@exextoc No, it's still not working for me!

**Comment by exextoc** [comment]
@elegault Can you share a test account where the issue reproduces? You can email us the account details at OutlookAddins@M365x693897.onmicrosoft.com

**Comment by elegault** [comment]
@exextoc Done. I assume I don't have to configure my test add-in for your use with that mailbox?

**Comment by exextoc** [comment]
@elegault Thanks for sharing the details over email. We will get back to you soon.

**Comment by exextoc** [comment]
> @exextoc Done. I assume I don't have to configure my test add-in for your use with that mailbox?

Hello, there is a two step auth enabled for this account and as a result we are unable to log in. Can you please disable it and confirm?

**Comment by elegault** [comment]
@exextoc Done

**Comment by exextoc** [comment]
Hey @elegault ,

Sorry for the delay, but we were unable to load the add-in in your mailbox (I am assuming that the only custom add-in installed is the one). Is the add-in live right now?

**Comment by barisbikmaz** [comment]
Same for us. We also get a CSP error in Online
![Mail Signature](https://user-images.githubusercontent.com/6338132/140783764-5c663e48-77b9-4517-9bfe-c29a6ccf1d57.gif)

**Comment by elegault** [comment]
> Hey @elegault ,
> 
> Sorry for the delay, but we were unable to load the add-in in your mailbox (I am assuming that the only custom add-in installed is the one). Is the add-in live right now?

My apologies @exextoc, I didn't know you needed the add-in to be deployed and I thought you had some other mechanism for testing. I have now deployed an add-in that is live from GitHub pages that will be activated when you compose a new email or appointment/meeting request.

**Comment by exextoc** [comment]
@elegault  Thanks for your patience. We have fixed the bug from our end. Can you please try it once and let us know your feedback?

**Comment by barisbikmaz** [comment]
Works again for me. Thanks.

**Comment by elegault** [comment]
@exextoc It is now working for me!
