### ISSUE TITLE
Excel Add-in does not get added to Home ribbon

### ISSUE THREAD

**Issue by bferreira** [OfficeDev/office-js#2126]
# Provide required information needed to triage your issue
When installing add-in on Excel Volue Insight, it opens the task pane but it is not added to the Home ribbon as normal. For next usage, the user needs to go to My Add-ins panel to open the task pane again.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: MS Office Professional Plus 2016 (16.0.5188.1000) 64-bit 
* Operating System: Windows 10 Enterprise version 21H1, OS build: 19043.1165
* Browser (if using Office on the web): ______
 
## Expected behavior

When installing add-in on Excel Volue Insight, it gets added to the Home ribbon on excel and it's present when you open new excel files as well.

## Current behavior

When installing add-in on Excel Volue Insight, it opens the task pane but it is not added to the Home ribbon as normal. Next time he opens the an excel file, the user needs to go to My Add-ins panel to open the task pane again.

## Steps to reproduce

1. Go to Insert menu item. 
2. Click on ‘My Add-ins’. A pop-up will appear with all of your Office Add-ins.
3. If it is the first time using it, go to Store and search by Volue Insight API. Click add.
4. A new button Should be added to your Home menu but instead that the task pane will open.

## Context

A client is trying to use our add-in and it is causing them issue to re-open every time they want to use it.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
The add-in:
![image](https://user-images.githubusercontent.com/1233578/133604816-c13327b9-5756-4575-b6a6-ab5bb119a9c9.png)
The button that should be added to Home
![image](https://user-images.githubusercontent.com/1233578/133604953-db0fed78-213b-45b3-836f-157ecf07ea34.png)
- [ ] Test file (if only happens on a particular file)

**Comment by bferreira** [comment]
Any updates here?

**Comment by bferreira** [comment]
It has been more than a month. Any updates?

**Comment by keyur32** [comment]
Hey there, sorry for missing this. 

Please see this documentation: https://docs.microsoft.com/en-us/office/dev/add-ins/design/add-in-commands#supported-platforms. 

It appears the customer is not on a supported version of Office that supports the add-in commands feature.
