### ISSUE TITLE
No option to open hyperlink in Word add-in in Office 2019

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#2127]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **PC Desktop**
* Host [Excel, Word, PowerPoint, etc.]: **Word**
* Office version number: **Microsoft® Word 2019 MSO (16.0.10373.20050) 64-bit**
* Operating System: **Windows 10**
 
## Expected behavior
Word add-in should show an option to open hyperlink in Office 2019.

## Current behavior
I am having word add-in, built using Angular 12, TypeScript and Telerik Kendo controls. When I open the same add-in in Office 2019 and creates a link in the Editor, I don't see option "Open link in new Window" when I right click on the link. Same option is visible in Office 365. Hence I am suspecting this is something related to IE browser and add-in behavior in Office 2019.

I have attached images of different behavior of right click context menu in both Office 365 and Office 2019 versions.

<img width="482" alt="kendo-editor-right-click-issue" src="https://user-images.githubusercontent.com/36051026/133607978-6a5a36ca-e2b6-4f27-beab-59db6df4d6f0.png">

<img width="250" alt="link-rightclick-in-O365" src="https://user-images.githubusercontent.com/36051026/133607984-7f1d2a72-348a-4e1d-bc49-fd4f325e6c45.png">

**Comment by ghost** [comment]
Team - Could you please share updates on this ticket?

**Comment by AbidRahman-MSFT** [comment]
Hey @ShahViral6438,

The right-click context menu is dependent on the browser runtime being used by the add-in. 

The following documentation lists the different browsers that are currently being used: [Browsers used by Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)

You will notice that for Office 2019, the browser runtime is IE11, the context menu you are seeing is the default context menu in IE11. 

In your second screenshot, the browser being used is Microsoft Edge, the context menu you are seeing is the default context menu in Edge (specifically in Webview2). 

This is by design, we cannot change the IE11 context menu. Please let me know if you have any questions.

**Comment by ghost** [comment]
@AbidRahman-MSFT
Thanks for response.
Is there any way to customize right click context menu to have that "Open Link" option? If you / your team are not the right point of contact to answer on this ask, could you please forward this ticket to respective team / person?

**Comment by ghost** [comment]
@AbidRahman-MSFT @robert-gavrila 
We have had the same issue in below browser also:

![91cd1681-7418-4367-b70b-5290b5a9bdb5](https://user-images.githubusercontent.com/36051026/138249558-8f2286dd-825e-43b1-8619-a3bf33a70a81.png)

Could you please suggest how to proceed further? Could you also suggest which browser (and in which versions) supports _**right click + open link in new window**_ ?

**Comment by AbidRahman-MSFT** [comment]
Hey @ShahViral6438, these are the native right-click menus for each browser. The Office JS platform does not explicitly create any right-click context menus. The 'right click + open link in new window' option only exists in the Microsoft Edge with WebView2 (Chromium-based) browser engine. Similar to how you can see the same option when browsing any webpage using the new MSFT Edge browser.

You can try to create the custom right-click menu in the add-in yourself, using libraries that are available for your specific JS application. For e.g. if your application is a React App, you can utilize something like [this](https://techion.hashnode.dev/react-custom-right-click-context-menu) to create a custom context menu for Edge. However, there is NO OfficeJS APIs that allow you can utilize for this purpose and any custom right-click menus are also not allowed in IE.
