### ISSUE TITLE
auth.getAccessTokenAsync doesn't seem to work with Microsoft Graph client

### ISSUE THREAD

**Issue by xstos** [OfficeDev/office-js#213]
## Expected Behavior
I assumed that token would work with Microsoft Graph Client

## Current Behavior
graphClient err variable contains:

```
{
  "statusCode": 401,
  "code": "InvalidAuthenticationToken",
  "message": "Access token validation failure.",
  "requestId": "f631ae74-5914-4184-b5f0-25d197e8e4a6",
  "date": "2018-08-06T20:55:51.000Z",
  "body": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token validation failure.",
    "innerError": {
      "request-id": "f631ae74-5914-4184-b5f0-25d197e8e4a6",
      "date": "2018-08-06T16:55:51"
    }
  }
}
```

## Steps to Reproduce, or Live Example
Started with: https://github.com/OfficeDev/Word-Add-in-Tutorial

my-word-add-in-manifest.xml

added WebApplicationInfo node as follows:
```
<VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
...
    <WebApplicationInfo>
      <Id>{CLIENT ID HERE}</Id>  
      <Resource>api://localhost:3000/{CLIENT ID HERE}</Resource>  
      <Scopes>  
          <Scope>Files.Read.All</Scope>  
          <Scope>Sites.ReadWrite.All</Scope>  
          <Scope>offline_access</Scope>  
          <Scope>openid</Scope>  
          <Scope>profile</Scope>  
          <Scope>User.Read</Scope>  
      </Scopes>  
    </WebApplicationInfo>  
</VersionOverrides>  
```

package.json

```
{
  "name": "my-word-add-in",
  "description": "",
  "author": "",
  "version": "0.1.0",
  "scripts": {
    "start": "browser-sync start --config bsconfig.json",
    "validate": "./node_modules/.bin/validate-office-addin",
    "build": "webpack --config webpack.config.js"
  },
  "dependencies": {
    "@microsoft/microsoft-graph-client": "^1.1.0",
    "@microsoft/office-js-helpers": "^1.0.2",
    "axios": "^0.18.0",
    "babel": "6.5.2",
    "babel-cli": "^6.18.0",
    "babel-core": "^6.17.0",
    "babel-loader": "^6.2.5",
    "babel-preset-es2016": "^6.16.0",
    "core-js": "^2.4.1",
    "jquery": "^3.1.1",
    "msal": "^0.1.9",
    "office-addin-validator": "^1.0.1",
    "office-ui-fabric-js": "^1.3.0",
    "webpack": "1.13.1"
  },
  "devDependencies": {
    "@types/office-js": "^0.0.37",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.26.0",
    "browser-sync": "2.18.13"
  }
}

```

app.js

```
const MicrosoftGraph = require("@microsoft/microsoft-graph-client");

var graphClient = null;
'use strict';
(function () {
    Office.initialize = (reason) => {
        $(document).ready(() => {

            // TODO1: Determine if the user's version of Office supports all the 
            //        Office.js APIs that are used in the tutorial.
            if (!Office.context.requirements.isSetSupported('WordApi', 1.3)) {
                console.log('Sorry. The tutorial add-in uses Word.js APIs that are not available in your version of Office.');
            }

            // TODO2: Assign event handlers and other initializaton logic.
            $('#insert-paragraph').click(insertParagraph);
        });
    };

    // TODO3: Add handlers and business logic functions here.
    function insertParagraph() {
        Word.run(context => {
            Office.context.auth.getAccessTokenAsync(result => {
                if (result.status === "succeeded") {
                    var accessToken = result.value;
                    graphClient = MicrosoftGraph.Client.init({
                        authProvider: (done) => {
                            done(null, accessToken); //first parameter takes an error if you can't get an access token
                        }
                    });
                    console.log("Got token", accessToken);
                    graphClient.api("https://graph.microsoft.com/v1.0/me/")
                        .get((err, res) => {
                            console.log(res);
                        });
                } else {
                    console.log("Error obtaining token", result.error);
                }
            });

            return context.sync();
        })
            .catch(error => {
                console.log("Error: " + error);
                if (error instanceof OfficeExtension.Error) {
                    console.log("Debug info: " + JSON.stringify(error.debugInfo));
                }
            });
    }
})();
```

* Additional details:
![o365addin1](https://user-images.githubusercontent.com/950443/43730153-677903ac-9978-11e8-9e08-3c6982d7b141.png)
![o365addin2](https://user-images.githubusercontent.com/950443/43730154-6785a7ba-9978-11e8-9aa3-92325e513c5c.png)
![o365addin3](https://user-images.githubusercontent.com/950443/43730155-67949004-9978-11e8-9748-c111d3731423.png)
![o365addin4](https://user-images.githubusercontent.com/950443/43730844-b419a9da-997a-11e8-9962-c75eb70e4818.png)
![o365addin5](https://user-images.githubusercontent.com/950443/43730848-b67e1f30-997a-11e8-9e1a-12eeb2042d37.png)
![o365addin6](https://user-images.githubusercontent.com/950443/43731119-808a1a36-997b-11e8-92a6-2e31f0a6b80e.png)

## Context
I was trying to access the Graph API client side using javascript.

## Your Environment

* Platform: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: Windows
* Browser (if using Office Online): Chrome latest

**Comment by Rick-Kirkham** [comment]
The token doesn't work that way. You need to exchange it for another token using the "On Behalf Of" flow. Please see the articles in this node of the developer documentation: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins. You should also check for support of `IdentityAPI 1.1` in the same place where you check for WordApi 1.3. (Note that the "PI" is capitalized in the name of IdentityAPI.)

**Comment by xstos** [comment]
Holy cow it worked! Thanks for the nudge in the right direction. 

![behalf_of_postman](https://user-images.githubusercontent.com/950443/43783688-5018059c-9a30-11e8-8815-9f7272dd27fb.png)

Took me a couple of weeks to finally figure this out end to end. I've been spoiled in VBA, VSTO, and AddinExpress land I guess. The process was kinda painful.

If I was going about documenting the app development process I'd supplement all this documentation with a dummy readonly azure tenant with an accompanying integration c# solution that has one narrow unit test per use case. People can just download it and run it in the debugger and inspect what's happening. I usually rely on Stackoverflow for good examples, but this content is too new and specific to have accreted enough information. Some kind of wizard for configuring the app portal and manifest would help too, since hand-editing data seems a bit regressive and error prone. I can imagine thousands of devs all encountering the same problems due to lack of end-to-end examples.

Rich Hickey gave a talk once about simple being hard. I think consolidating these docs into an active integration demo app would help us 3rd party guys tremendously. I've been dreaming about all the errors i've been encountering for days now. Pretty frustrating.

**Comment by Rick-Kirkham** [comment]
@xstos 
Thanks for the suggestions. We do have two end-to-end samples. See the "Completed" folder of the following:
[Office-Add-in-NodeJS-SSO](https://github.com/OfficeDev/Office-Add-in-NodeJS-SSO)
[Office-Add-in-ASPNET-SSO](https://github.com/OfficeDev/Office-Add-in-ASPNET-SSO)
