### ISSUE TITLE
[Outlook] Can we get manifest permission level by 'Office.context.mailbox.initialData.permissionLevel'?

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#2130]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Just a quick question:
 Can we get the manifest's permission level by 'Office.context.mailbox.initialData.permissionLevel' ?

I see it's match manifest's permission setting. 
But the question is, I didn't see the doc about this. Did Microsoft support this attribute? Have a wiki for it?

**Comment by exextoc** [comment]
Thanks for the post. As you had mentioned there are 4 types of permission levels: Kindly refer to https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-owemxml/f466a8a7-5a2d-4e6b-b0db-957bebd181b1

When the command "Office.context.mailbox.initialData.permissionLevel" is executed, you can find values as mentioned below

<img width="1006" alt="Screenshot 2021-09-18 at 1 39 20 PM" src="https://user-images.githubusercontent.com/28549921/133881782-0d48d6fa-ef3d-4b22-be3b-dc5922f9e526.png">

And, we will make sure to update the doc too.
.

**Comment by exextoc** [comment]
Thanks for the post @SWei1234 . Can you please let us know the use case of this information so that we can help better?

**Comment by AlexJerabek** [comment]
Tagging @ElizabethSamuel-MSFT to follow for potential documentation updates.

**Comment by SWei1234** [comment]
Hi @exextoc and  @ElizabethSamuel-MSFT
Sometimes we want to run some function in add-in only manifest have set a high level permission. 
At this time, we might need to know which permission level we have set in manifest. If we can't know the level we might need to make two different add-in(most code is same) Or get an error/exception when trying run this function.
Thanks

**Comment by exextoc** [comment]
This information is currently not exposed. If you need this feature and wish to file a request, please use the link: https://aka.ms/M365dev-suggestions.
