### ISSUE TITLE
ExtendedOverrides element of Manifest error

### ISSUE THREAD

**Issue by cgaranip** [OfficeDev/office-js#2132]
When creating an Office.js Add-in in Visual Studio 2019, adding the ExtendedOverrides element to the manifest, in order to be able to add keyboard shortcuts, the following error is thrown:

Error: The element 'OfficeApp' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1' has invalid child element 'ExtendedOverrides' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1'. List of possible elements expected: any element in namespace 'http://www.w3.org/2000/09/xmldsig#'. 

Using VS 2019, office 365 version 1202.

Followed the steps as in https://docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts

Attached the manifest file in txt format.
[manifest.txt](https://github.com/OfficeDev/office-js/files/7193238/manifest.txt)

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue @cgaranip.

@AbidRahman-MSFT, could you please investigate?

**Comment by AbidRahman-MSFT** [comment]
Hey @cgaranip - thanks for reporting the issue. 

We have fixed the namespacing issues in VS 2022, as a workaround for now, you can use the preview version of VS 2022 to add the ExtendedOverrides into the manifest - https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview 

We will continue to investigate the VS 2019 issue and get back to you with any updates.

**Comment by AbidRahman-MSFT** [comment]
Hey @cgaranip - as a workaround for VS 2019, please try the following:

1. Create a file named `offappmanifest-1.1.xsd`
2. Copy and paste the schema found in https://docs.microsoft.com/en-us/openspecs/office_file_formats/ms-owemxml/00e4ee5d-2eb8-47f2-9008-8beb6ff45189 to the blank file created in step 1.
3. Replace the `offappmanifest-1.1.xsd` file at `C:\Program Files (x86)\Microsoft Visual Studio\2019\<InstallType>\Xml\Schemas\1033\` location with the new .xsd file. Note that the `1033` could be a different value depending on the locale that was installed.
4. Restart VS 2019

This should replace the namespace file with the correct one in your local system. Please let me know if you have any issues.
