### ISSUE TITLE
Automatically open a task pane with a document.

### ISSUE THREAD

**Issue by careernavigator** [OfficeDev/office-js#2134]
**Issue Summary**
Automatically open a task pane with a document in office 2019 is causing an issue when user clicks on add-in icon again presented on word toolbar. It would load the add-in in a new task pane window, so user would see two task pane in office 2019.  

**Your Environment**
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: Word
Office version number: Microsoft® Word 2019 64-bit
Operating System: Windows 10
 
**Expected behavior**
Word add-in should reload in existing task pane window only.

**Current behavior**
We implemented add-in automatically load behavior by following it- https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document
Automatically open a task pane with a document in office 2019 is causing an issue when user clicks on add-in icon again which is present on the word toolbar. Clicking the add-in icon again would load the add-in in a new task pane window, so user would see two task pane in office 2019.  in O365 it works fine.

**Steps to reproduce**
1. Open a word document. Click add-in icon to load the add-in. Save the document.
2. Open the saved document again, it would auto load the add-in task pane. Now if the user clicks on add-in icon again which is presented on the word toolbar, it is loading the add-in in a new task pane window. so user is seeing two task pane now. This issue is occurring in office 2019 only.

**Comment by AlexJerabek** [comment]
Hi @careernavigator,

Thanks for reporting this. @sohailzafar, could you please take a look?

**Comment by careernavigator** [comment]
@sohailzafar  Hello, any updates on this issue? Please do let me know if any other detail is required on this. Thank you!

**Comment by ghost** [comment]
@AlexJerabek @sohailzafar 
Team - Could you please share updates on this ticket?

**Comment by AlexJerabek** [comment]
Tagging @AbidRahman-MSFT to increase visibility.

**Comment by careernavigator** [comment]
Team - Could you please share updates on this ticket?

**Comment by AbidRahman-MSFT** [comment]
Hey @careernavigator - we are investigating the issue. We have opened an internal bug (#5472999) to help track progress, we will let you know as soon as we find out more.

In the possible case that this is a bug, it will take us some time to prioritize and fix for Office 2019. I would highly suggest avoiding this user flow or attempting to find workarounds if you are looking for a quick solution.

**Comment by AbidRahman-MSFT** [comment]
This issue has been fixed on versions 16.0.10385.20005 and greater.
