### ISSUE TITLE
displayDialogAsync breaks Outlook OnSend addins since recent Microsoft Update

### ISSUE THREAD

**Issue by sys0601** [OfficeDev/office-js#2136]
We had working code for an OnSend Outlook addin that was displaying a prompt using displayDialogAsync. It appears to have stopped working. The sample code is included later.

We made no changes to the code. I know that there was an update released by Microsoft for Cross Domain pop-ups and I am wondering if that change accidentally broke OnSend. 

## Expected Behavior

Code is similar to the following.

function showDialog() {
    let popupPage = hostUrl + "/" + "page.html"
    Office.context.ui.displayDialogAsync(popupPage,
        { height: 50, width: 50, displayInIframe: true }, dlpDialogCallback);
}

This used to display the pop up dialog but now does not work. Please note that there is no cross domain stuff happening here. We even tried with a simple blank page and it still does not display.

We further simplified the code by getting rid of dlpDialogCallback but that did not work either.

## Context
We are trying to display a prompt to the user on the OnSend event.

## Your Environment
Windows 10
Office 365 OWA (Tested on Chrome and Edge)

**Comment by codexeon** [comment]
This issue is likely not related to cross origin in your add-in, and similar to this issue: https://github.com/OfficeDev/office-js/issues/2129 which has a fix deployed recently. Could you confirm it is working now for you?

**Comment by sys0601** [comment]
Thanks @codexeon. It appears to be working now. We will test over the next few days and report if any problems. Thank you again for your help.

**Comment by exextoc** [comment]
Closing the issue. Please reopen if you face the problem again.
