### ISSUE TITLE
Paragraphs in tables are not returned (Word 2016 16.0.5188.1000 -Desktop)

### ISSUE THREAD

**Issue by bkonic** [OfficeDev/office-js#2137]
For a task pane add-in in word, we need to get all paragraphs in the document's body - including the text inside the tables.
We use the following code-segment:

```
       var documentBody = context.document.body;
        var paragraphs = context.document.body.paragraphs;
        context.load(documentBody);
        context.load(paragraphs, "items");
        await context.sync();
```

## Environment:
Word 2016 (16.0.5188.1000) 32-Bit
Windows 10 
Word Taskpane-Addin
Note: The add-in is rendered in a IE 11 frame due to the version of word.
 
## Expected behavior
Includes paragraphs in tables 

## Current behavior
 Does omit paragraphs in tables. 

## Steps to reproduce

1. Create a word document - include a table an put some text in it, also write some text outside the table
2. Execute code above in the environment above
3. The code will return only paragraphs outside the table

## Link to live example(s)
No examples included, since it behaves different and as expected in word online.

## Context
We create a task pane add-in that analyses all the text in the document. Omitting the text in the tables is not an option.
Going through the paragraphs also is needed to map objects in the application according to their order in the paragraph collection.
In this environment (using word api 1.1) , search API and also document.body.contentcontrols include results that are inside a table. document.body.paragraphs should include them as well.

**Comment by AlexJerabek** [comment]
Thank you for reporting this @bkonic. Does this behavior happen in the latest versions of Word (either the web or desktop version Microsoft 365)? Or is it only on Word 2016?

@AbidRahman-MSFT, could you please follow up and investigate?

**Comment by bkonic** [comment]
Thanks  @AlexJerabek !
The issue does NOT occur in the latest versions of Word (neiter the web nor desktop Microsoft 365). Only in Word 2016.
Just to be clear: We need it to be working in Word 2016 (16.0.5188.1000) 32-Bit since our customers are currently not able to upgrade .

**Comment by bkonic** [comment]
@AlexJerabek  @AbidRahman-MSFT 
Do you have an update on the issue? Have you been able to reproduce it?
Thanks for a quick update.

**Comment by AbidRahman-MSFT** [comment]
Hey @bkonic - apologies for the wait and thanks for the patience.

We did investigate this issue and are able to reproduce it, we have created an internal bug (5483190) to investigate further. Will keep you updated on any progress. Thanks.

**Comment by bkonic** [comment]
Hi @AbidRahman-MSFT,
Do you have any Updates? Thx

**Comment by AbidRahman-MSFT** [comment]
Hey @bkonic - after further investigation, this behavior is by design for Word 2016. The behavior was implemented after Word 2016 version was released and at that time, the paragraph collection only contained top-level paragraphs. 

There is no way to retroactively add this feature for past versions. Is there any reason the users are unable to upgrade?

**Comment by aafvstam** [comment]
This is why requirement sets were introduced don't you agree?

If this is not supported in the 1.1 API it should be pointed out/added to the requirement set documentation:
[Word JavaScript API - Paragraphs](https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-1.1#paragraphs)

[Word JavaScript API requirement sets](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/word-api-requirement-sets)
If it is not part of a requirement set there is no way to differentiate between versions and renders it useless when the results  are not clear.

@AbidRahman-MSFT At what API requirement set are the paragraphs in tables added to the Paragraphs API result set?

**Comment by bkonic** [comment]
@AbidRahman-MSFT : Some large customers have other legacy applications hindering them from upgrading quickly without months of testing. 

@aafvstam : I fully agree.  Right now, it seeems kind of random. This should be in the documentation.

**Comment by AbidRahman-MSFT** [comment]
Hey @aafvstam and @bkonic,

I agree with you completely. We will get that information updated in the documentation. 

Paragraphs in tables were introduced as part of requirement set 1.3, this requirement set also introduced several methods for the Paragraph class that can allow you to differentiate between a paragraph in a table and a regular paragraph (for e.g. [parentTable property](https://docs.microsoft.com/en-us/javascript/api/word/word.paragraph?view=word-js-preview#parentTable)).

You can use the requirement set check for 1.3 to determine whether or not Body.Paragraphs will return paragraphs inside of a table. We will keep this issue open until we have clarified the documentation for Body.Paragraphs.

**Comment by AbidRahman-MSFT** [comment]
The documentation has now been updated. Please see the note for the [paragraph property in the body class](https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#paragraphs).
