### ISSUE TITLE
Excel Add-in: data stored in localStorage not accessible across sessions

### ISSUE THREAD

**Issue by beatrixmorar** [OfficeDev/office-js#2140]
I have an Excel Add-in build with Office JS API that features custom add-in commands. One of these commands opens a dialog (using the Office Dialog API) which displays a SPA built with Vue.js. I need to store some data to be accessible both from the add-in and dialog. For this purpose, I tried to use the localStorage of the browser, but somehow it seems that the data is not accessible across sessions. The host of the dialog is the UI-less function file (commands.js) and the dialog has the same domain as the add-in itself.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft 365 MSO (16.0.14326.20384) 64-bit 
* Operating System: Windows 10 Pro
* Browser (if using Office on the web): -
 
## Expected behavior
Dialog and host share data via localStorage. From both ends, one can read and write data to/from the localStorage.

## Current behavior
Data is being added to localStorage from the host, but it is not available from the dialog (no value is returned by localStorage.getItem(key)) and the other way round.

## Steps to reproduce
1. Store some data in localStorage from host window: call the setItem method of the window.localStorage object in the host page before the displayDialogAsync call, for example window.localStorage.setItem("ursername", "ADMIN").
2. Try to retrieve data from localStorage in the dialog: window.localStorage.getItem("username").

# Provide additional details
In addition, I tried to use cookies to store data and access it from the dialog, but I encounter the same problem as with the localStorage.

## Context
I need a common place where I can store data and to be accessible from different places: dialogs, host windows for dialog, task pane etc. To achieve this, localStorage seemed a natural candidate since it is expected that the data stored there is acessible acrosss sessions. For obvious reasons, sessionStorage is not a solution and also communication via Office Dialog API methods ([messageParent](https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=excel-js-preview#messageParent_message__messageOptions_) and [messageChild](https://docs.microsoft.com/en-us/javascript/api/office/office.dialog?view=excel-js-preview#messageChild_message__messageOptions_)) might not fit in all cases.

## Useful logs
local storage for host:
![image](https://user-images.githubusercontent.com/52167887/134494572-a4a0b56e-61f9-4494-8ebd-3a1b3e044d9c.png)

local storage for dialog:
![image](https://user-images.githubusercontent.com/52167887/134494628-67a6d8bb-a371-4ea6-b326-641979eed2cd.png)

**Comment by AlexJerabek** [comment]
Hi @beatrixmorar,

Have you looked into using our SharedRuntime as a storage solution? Here's a sample showing how to enable the SharedRuntime to share data between a custom function and a taskpane: https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/excel-shared-runtime-global-state

You might also be able to use the [OfficeRuntime.Storage](https://github.com/OfficeDev/PnP-OfficeAddins/tree/main/Samples/excel-shared-runtime-global-state) object to persist information.

Let me tag @jeremy-msft to follow up.

**Comment by jeremy-msft** [comment]
Assigning over to @lliu113 to assist from the dialog perspective.

**Comment by beatrixmorar** [comment]
Thanks for the quick response, @AlexJerabek 

I've seen the SharedRuntime approach in the past, will check that out again to see if it fits.
I tried the OfficeRuntime.Storage as well, I already store there some information. But the problem is when I try to read that information from my dialog, I get an error which says that I do not have permission to perform that action:

> OSF.DDA.Error
code: 7000
message: "You don't have sufficient permissions for this action."
name: "Permission Denied"

In addition to that error, there is a warning saying "Tracking Prevention blocked access to storage for https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js."

**Comment by alettieri** [comment]
I wonder if this is related to #1868.

I had the same issue and ended up turning off the debug flag. Which solved my use case.

**Comment by beatrixmorar** [comment]
@alettieri Thanks for the hint.

Just for others following this thread: please have a look at @alettieri 's comment on #1868

**Comment by ElizabethSamuel-MSFT** [comment]
Seems like the response on the other thread unblocked this issue so closing.

@beatrixmorar If there's something else that should be addressed here, let us know so we can reopen.

Thanks.
