### ISSUE TITLE
(Re-Submission) No way to sideload/test iPad/iPhone Outlook add-ins

### ISSUE THREAD

**Issue by gitcnd** [OfficeDev/office-js#2141]
See my comment on the issue you transferred to documentation repo:-
https://github.com/OfficeDev/office-js-docs-pr/issues/2947#issuecomment-925733756

The side-loading method only works for the Android app: it does NOT work for my iPhone.

**Comment by exextoc** [comment]
Sideloaded addins should be available to both Android and iOS. Will it possible for you to share your manifest with us so that we can have a look.

**Comment by gitcnd** [comment]
I copied the MojiLaLa manifest, because I wanted to start from a know-to-work-for-sure state. Here is theirs (I use my URLs, not theirs, but everything else is the same - including the icon size and type etc).

[MojoLaLa.zip](https://github.com/OfficeDev/office-js/files/7218218/MojoLaLa.zip)

You can probably edit their manifest and delete the digital signature, and then literally side-load that to see if it shows up in iOS for you ?

**Comment by exextoc** [comment]
I side-loaded the manifest that you provided and I can see it in both iOS and android. Can you first try exactly with the manifest that is attached here before making any change and check. 
Also, will like to confirm whether you changed the Id in the manifest. It must be a unique id so you should change it whenever you are making any modification.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
