### ISSUE TITLE
User with apostrophe in email address is not added in required Attendee using Office API.

### ISSUE THREAD

**Issue by Vineet-Yadav** [OfficeDev/office-js#2142]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We have email/room containing apostrophe (first'lastName@mail.com).

**Current behavior**: Using office API (Office.context.mailbox.item.requiredAttendees.addAsync) : "emailAddress": "first'lastName@mail.com" is not added in requiredAttendees as this have aporstrophe.
**Expected Behaviour**: "emailAddress": "first'lastName@mail.com" must be added in requiredAttendees.

##**Environment**
Platform [PC desktop, Mac, Office on the web]
Host [Excel, Word, PowerPoint, etc.]: OWA + Native Outlook
Operating System:Window 10
Browser : Chrome (We support all browsers ie Microsoft Edge| Mozilla | Safari)

**Steps**:
Passed Scenario:
1. Open calendar --> click on any time slot to book a meeting, paste email address (first'lastName@mail.com) to invitee attendee, its work.

Failed Scenario:
2. Now add attendee using office api ie
Code Snippet
var emailArray = [ { "displayName": "Allie Bellew", "emailAddress": "first'lastName@mail.com" }, { "displayName": "Alex Darrow", "emailAddress": "firstNamelastName@mail.com" } ];
function setRequiredAttendees() {  
  Office.context.mailbox.item.requiredAttendees.addAsync(emailArray, function(asyncResult) {
	  if (asyncResult.error){		
	  }
	if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
	} else {
	  console.error(asyncResult.error);
	}
  });
}
3. In above case "emailAddress": "first'lastName@mail.com" is not added in requiredAttendees as this have aporstrophe.
4. In above case only "emailAddress": "firstNamelastName@mail.com" is added in requiredAttendees.

**Please suggest how email address ("emailAddress": "first'lastName@mail.com") with apostrophe will be added in requiredAttendees as we mentioned in point #3.**

**## Context**
We have outlook addin which fetch data from api and add emailAddress using office api (Office.context.mailbox.item.requiredAttendees.addAsync.

**## Useful logs**
![image](https://user-images.githubusercontent.com/20768802/134625005-5eae6764-7190-4175-9a98-37bf8d38c89d.png)

**Comment by AlexJerabek** [comment]
Thanks for reporting this issue @Vineet-Yadav.

@exextoc, could you please investigate?

**Comment by exextoc** [comment]
Thanks for reporting this issue. We are able to reproduce it. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by Vineet-Yadav** [comment]
@exextoc , Any Update regarding this.

**Comment by exextoc** [comment]
This bug is in our backlog and we will keep you posted on the progress.Meanwhile can you please let us know how many users are impacted by this??

**Comment by Vineet-Yadav** [comment]
Hi @exextoc , 

We have multiple clients which have multiple exchange rooms/ users impacting with this. Please share the tentative info to fix this.
