### ISSUE TITLE
[WordApp iOS] : api insertHtml with an image tag including src base64 is not working.

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#2144]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am developing Microsoft Office Addins, when I am trying to use api cc.insertHtml with an image . The image is not showing on ios devices, but working well on windows and macos.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: iOS
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Word 2.53.1
* Operating System: ios 14.7.1
* Browser (if using Office on the web): ______
 
## Expected behavior
It should work on ipad

## Current behavior
on Windows (using Scriptlab)
![6](https://user-images.githubusercontent.com/13063615/134619883-55a6a0a6-db1a-49cd-87ea-c8fee45fa05d.PNG)

on Ipad ( Yeoman generate officeaddins, because Scriptlab is not available yet)
![4aJdD9oX2J](https://user-images.githubusercontent.com/13063615/134619000-df8cd59e-c96b-4bbe-9992-5a7a84a01b2e.gif)

## Steps to
Yeoman
1. Yeoman generate officeaddins (https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/sso-quickstart)
2. insert image using cc.insertHtml api
3. observe the result : Works fine on Windows, but failed on Ipad

Scriptlab : 
https://gist.github.com/jasonhieu1905/644ab50fd6258cf2c0ab0cf0176ed651

Execution script :
```
const htmlTag = '<img src="data:image/jpg;base64,data" height="200" width="300" />
cc.insertHtml(htmlTag, "Replace")
```

**Comment by barisbikmaz** [comment]
Inserting an image as base64 with html works on:
- PC, 
- Web
- MacOs 

but only **not** on ios. 
Seems to be a parity problem.

**Comment by AlexJerabek** [comment]
Thanks for reporting this and providing sample code to reproduce the issue @jasonhieu1905.

@AbidRahman-MSFT, could you please investigate.

**Comment by AbidRahman-MSFT** [comment]
Hey @jasonhieu1905 - thanks for reporting the issue. We have opened an internal bug (5483236) to help investigate. We will keep you updated on any progress.
