### ISSUE TITLE
Word add-in suddenly disappears from ribbon and needs to be reinstalled

### ISSUE THREAD

**Issue by pb-jeff-oneill** [OfficeDev/office-js#2146]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I've had two different customers report this.

They are using our Word add-in with a task pane.  Suddenly, the task pane disappears and the Word add-in is uninstalled.  They need to reinstall the Word add-in to use it again.

This is an intermittent issue and happens infrequently.  

I have not been able to recreate it.

Here are some details of the customer environments:

- Customer 1: Desktop Word Office 365 (16.53) on Mac
- Customer 2: Desktop Word Office 365 on Windows 10

If it is helpful, I can get more details or get the environment of the users who reported this bug.

This could be an application issue instead of an Office-js one.  Tagging @sumurthy and @yihuax since they were extraordinarily helpful with a previous issue that was on the application side.

**Comment by AbidRahman-MSFT** [comment]
Hey @pb-jeff-oneill - thanks for reporting the issue. A few follow up questions to help us investigate:

1. How did the user first acquire the add-in? Was it admin installed or did the user install through AppSource/add-in store in the app?
2. Has the issue ever occurred on Web? Or is it limited to Windows/Mac?
3.  Is this specific to when the add-in receives an update? 

This does sound like it could be related to the cache - @madhavagrawal17 please let me know if this issue seems familiar to you.

**Comment by pb-jeff-oneill** [comment]
Hi @AbidRahman-MSFT, thank you for getting back to me.

> 1. How did the user first acquire the add-in? Was it admin installed or did the user install through AppSource/add-in store in the app?

One user installed from the ribbon in Word (Insert -> Add-Ins) and the other installed from AppSource.

> 2. Has the issue ever occurred on Web? Or is it limited to Windows/Mac?

Only on Windows/Mac.  Very few, if any, of my customers use browser-based Word.

> 3. Is this specific to when the add-in receives an update?

No, my add-in was last updated on July 5, 2021.

**Comment by AbidRahman-MSFT** [comment]
Hey @pb-jeff-oneill,

After discussing with the feature team, the only time the add-in can 'disappear' from the ribbon is:
- either the user explicitly removes it
- there has been an identity change

Could it be possible that the user is getting auto signed out?  If they are getting signed out, then they may no longer be entitled to that add-in. Also, is it possible the user is switching accounts?

**Comment by pb-jeff-oneill** [comment]
> Could it be possible that the user is getting auto signed out?

I assume you mean signed out of Word.

I suppose this is possible.  This doesn't ever happen to me.  

Could a company have a security setting that automatically logs users out of Word after a certain amount of time?

If so, Word must do so without notifying users (otherwise my customers would have likely mentioned it) which makes for a bad user experience with add-ins suddenly disappearing.

> is it possible the user is switching accounts?

This is not happening.

**Comment by AbidRahman-MSFT** [comment]
Thanks @pb-jeff-oneill - unfortunately, we don't have enough info here to figure out what could be causing the issue. If you are able to get a hold of a customer that can consistently repro the issue in certain environments, please let us know and we can try to investigate further.

**Comment by pb-jeff-oneill** [comment]
This happened again to one of my users.  She checked to see if she was still logged in to Word and she was.  It looks like the problem is not related to authentication.

This is a classic intermittent issue that is not amenable to reproduction.  There isn't much we can do.

It is creating a very bad experience for Word add-in users and this must be happening with many if not all add-ins.  It seems like a very important bug for Microsoft to fix.

**Comment by madhavagrawal17** [comment]
@pb-jeff-oneill, Can you follow the below instruction to send a frown from within the Office application when you see the issue that will help us to capture the logs and investigate the issue. 
Detailed here: https://support.microsoft.com/en-us/office/how-do-i-give-feedback-on-microsoft-office-2b102d44-b43f-4dd2-9ff4-23cf144cfb11.
In the description, please be sure to indicate "To Office Platform team: Following up on issue [GitHub issue link]. Please contact me for further information."

**Comment by pb-jeff-oneill** [comment]
FYI, this is still happening to my customers.  :(

I passed on those instructions so you are hopefully getting debugging info.

**Comment by AbidRahman-MSFT** [comment]
Hey @pb-jeff-oneill - can you please share your manifest file for the add-in?

**Comment by pb-jeff-oneill** [comment]
Hi @AbidRahman-MSFT, yes, no problem.  Attached.

[manifest.zip](https://github.com/OfficeDev/office-js/files/7652092/manifest.zip)

**Comment by AbidRahman-MSFT** [comment]
Hey @pb-jeff-oneill - there's nothing in the manifest that would be causing issues with loading add-in resources. Please continue to encourage your customers to send a frown whenever the issue occurs and we will continue to investigate. If you are able to get a consistent repro for this issue, also let us know and we will try to reproduce it and investigate further.

**Comment by pb-jeff-oneill** [comment]
I received some very helpful feedback from a customer:

> Just a quick note about the Microsoft Bug with Word Add-ins.  At least for me, this happens each time I update word.  More specifically, upon updating word on a Mac, nothing appears different with the add-in in the ribbon.  However, the next time I click on the add-in in the ribbon, it disappears.  The same is true with my other add-ins.

Can you please look into this?

**Comment by trigurl** [comment]
Hello Jeff, my coworkers and I have been chatting about this a bit.  We want to see if we can reproduce this issue.  Can you confirm the steps?

1) Boot Word on Mac
2) Install the Patent Bots GCP add-in from the Office store.
3) After the add-in is installed there will be a custom tab created on the Ribbon.
4) Force Word Mac to update.
5) After Word Mac updates, verify the "Patent Bots GCP" tab is still there (don't click any buttons yet), as well as any other add-ins that were previously installed.  Are your other add-in buttons still appearing? 
6) Don't click any add-in buttons yet, but verify that the user is still signed in with their account.
7) Go to the Insert tab | click on My Add-ins button to bring up the Office Add-ins dialog.  Look in the dialog, under "My Add-ins" do you see the list of store add-ins that you installed listed?  For example is Patent Bots GCP there? 
8) Close the Office Add-ins dialog.
9) Wait 5 minutes to see if the UI makes any changes.
10) Click on "Patent Bots" button in the "Patent Bots GCP" tab

Results:  Customer says their add-in completely disappears?   
If you go to step 7) and open the insertion dialog, is the "Patent Bots GCP" icon still there?  
If the "Patent Bots GCP" icon is not in the dialog, can you hit the "Refresh" button at the top right?  Do your add-ins come back?

**Comment by pb-jeff-oneill** [comment]
@trigurl, thank you for looking into this.

The biggest issue in trying to reproduce this is that it doesn't happen to everyone.  For example, I have a nearly identical setup (Mac/Word versions) as one of my customers, they experience this issue about once/month, and I have never experienced it.

This is the precise process:

1. Patent Bots GCP add-in is in the ribbon.
2. One user said that when they clicked the add-in in the ribbon (not sure if this means the tab or a button in the tab), all of their add-ins disappeared (Grammarly was an example).  Another user said that the add-in disappeared when they clicked a button in a task pane of the add-in.
3. Afterwards, when the My Add-Ins dialog is opened (Insert->Add-ins->My Add-Ins), the add-ins are still listed there.  So the user can just click to show the add-in again and they don't need to search in the store.  Though people are not aware of this so some go directly to the store to add them again.

**Comment by trigurl** [comment]
In these situations we try our best to come up with some sort of pattern also try to ask questions to narrow down a path to dig further.  In some cases we might need to add more telemetry and have customers continue to send us frowns so we can see what their telemetry is telling us.   Do you know whether their computer is being shared?  I'm asking because I wonder if various people are signing in/out on the same machine.

**Comment by pb-jeff-oneill** [comment]
My users are attorneys so computers are not shared.

**Comment by trigurl** [comment]
> My users are attorneys so computers are not shared.

Hi Jeff, I'm trying to see if I can repro this.  Do you know whether your customers are being updated by IT admin vs app store or Microsoft Autoupdate (invoke the check for updates command in Word Help menu)?

Thanks!

**Comment by trigurl** [comment]
I've looked through our data and can't figure out how users are getting into this situation.  Please have them send a frown and details regarding whether they were upgrading, did they refresh the add-in dialog?

**Comment by helenula** [comment]
Hi there! 

Just following up on the original issue reported here.
Some of our customers who use another Word add-in also report the same issue. Unfortunately, there are no particular steps I can share with you to help with reproducing the problem. However, it doesn't make it any less painful.
Would appreciate it if you could address this issue some time soon. 

Thank you!

**Comment by antonia-rose** [comment]
Since a few weeks we get the same error reports from our users (especially Mac users). I think the reason is an update of word. But I can't tell our customers to reinstall the add-on every few weeks. We will try to investigate this further.

**Comment by trigurl** [comment]
We are gathering some data from our telemetry to find a way to fix this.

**Comment by carlcarlsoniv** [comment]
Adding a comment here after coming across this while searching about a similar issue some of our users are experiencing. After our add-in is installed, a button is added under the Home ribbon. Multiple users are reporting that this button disappears without them removing it and without any notice. 

They then have to go to Insert - My Add-ins, find our add-in which is listed under MY ADD-INS, then select Add, which is very inconvenient. 

Some users have to do this every time they open Word, even if Word is currently open and they're only opening a new document.

Is there any setting or configuration that would disable or remove add-ins from a user's ribbon like this?

**Comment by JensMadsen** [comment]
Our customers report the same issue. I do not know how to reproduce

**Comment by pb-jeff-oneill** [comment]
This is still happening.  Any updates would be appreciated.
