### ISSUE TITLE
Add-in panel CSS incorrectly adds unwanted scroll bars (ms-Panel-content height is wrong)

### ISSUE THREAD

**Issue by gitcnd** [OfficeDev/office-js#2147]
I notice today that all add-ins now have unwanted scroll bars that show up when not needed, and overlap our add-in UI (the unwanted right scroll bar goes over the top of the right-hand side of our add-in, which causes an unwanted bottom side-ways scroll bar to show up as well.)

I notice that if I modify the "ms-Panel-content" CSS height calculation (the amount subtracted) that the problem goes away, however, the subtraction amount that I need to modify it by changes based on the screen size - so something more complicated is obviously broken with that CSS calculation.

## Your Environment

* Platform: Windows 10 and Mac OSX, using Office on the web
* Host: Outlook
* Office version number: web latest
* Operating System: PC and Mac
* Browser (if using Office on the web): Chrome and Edge on Windows 10, Firefox and Chrome on Mac
 
## Expected behavior
No scroll bars when the content in the side pane can fit properly.

## Current behavior
Always shows scroll bars.

## Steps to reproduce
1. Open any Add-in (e.g. OneNote) Pane

## Link to live example(s)

The problem:-
![Screen Shot 2021-09-28 at 7 55 06 pm](https://user-images.githubusercontent.com/4301826/135067371-c2ffe93e-d851-4334-b3a3-020f04170d58.png)

Modifying "Panel-content" CSS fixes it:
![Screen Shot 2021-09-28 at 7 55 48 pm](https://user-images.githubusercontent.com/4301826/135067505-be29172c-dfb2-4e94-89f0-d01d007f5d2d.png)

# Provide additional details
1. I'm pretty sure this was working OK last week.

## Context
I was in the middle of designing my side-pane UI, when this new problem showed up.  It would be nice to have it fixed, so I can make sure my own CSS works OK for all screen sizes.

**Comment by exextoc** [comment]
Thanks for reporting this issue and suggestions. This issue has already been reported here #1071 . We are currently working on rolling out the fix. Please follow #1071 for more updates on the same.
