### ISSUE TITLE
Pressing two times on the created ribbon-button stops the debugging session

### ISSUE THREAD

**Issue by dennismeissel** [OfficeDev/office-js#2149]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Environment

* Platform: Desktop PC
* Host: Word or Excel, started from Visual Studio 2019
* Office version number: 2108 (Microsoft Office Home and Business 2019)
* Operating System: Windows 10
 
## Expected behavior

The buttons should not stop the debugging-session

## Current behavior

If I [debug office add-ins in Visual Studio](https://docs.microsoft.com/office/dev/add-ins/develop/debug-office-add-ins-in-visual-studio) and press **two times** any ribbon-button that I've created in the manifest (see [Action element](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/action)), debug session stops and in the output-window I see `The program 'winword.exe' has exited with code -1 (0xffffffff).` for word or `The program 'excel.exe' has exited with code -1 (0xffffffff).` for excel, although the application is still running.

## Steps to reproduce

1. Create a new Project in Visual Studio 2019 (template Word Web Add-in or Excel Web Add-in).
2. Close all word/excel instances, depending on the project type.
3. Run the project from VS 2019 (Debug -> Start Debugging)
3. Press the created button (In the default project it is "Show Taskpane", but you can create your own button)
4. Wait until button has finished its action and press it again.
4. The debug session will be stopped, the output window of VS will show a message

## Additional details

1. I tried to create my own button and [action](https://docs.microsoft.com/office/dev/add-ins/reference/manifest/action) manually (type ExecuteFunction or ShowTaskpane). It doesn't help.
2. If I point the manifest file to a remote server and delete the web-project from the Visual Studio, the problem is still there, the debugger stops after the second click.

**Comment by timburg1** [comment]
I can reproduce this behaviour. My testFunc() just contains a call to console.log with the name of the called function. Running the add-in from Excel and clicking the button twice only yields "testFunc" once in the Visual Studio Output window:

Verbose logs are written to:
C:\Users\tim\AppData\Local\Temp\visualstudio-js-debugger.txt
Tracking Prevention blocked access to storage for https://appsforoffice.microsoft.com/lib/1/hosted/office.js. [https://localhost:44353/Functions/FunctionFile.html?_host_Info=Excel$Win32$16.01$en-US$$$$0]
testFunc
The program 'excel.exe' has exited with code -1 (0xffffffff).
The program '[16052] iisexpress.exe' has exited with code 0 (0x0).

I've attached the log generated by VS.
[visualstudio-js-debugger.txt](https://github.com/OfficeDev/office-js/files/7587335/visualstudio-js-debugger.txt)

**Comment by dbi-cc** [comment]
Today starting development of OfficeJS (Word) Plugin. I used the default App enroled by yoman (Angular flavor). I could reproduce the same issue.
