### ISSUE TITLE
Feature: Office JS Save and Close methods for Word, Excel and PowerPoint

### ISSUE THREAD

**Issue by jaime-rivas** [OfficeDev/office-js#2150]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Office JS Save and Close methods for Word, Excel and PowerPoint

Hello!

These are two features which we are extremely interested in. I've been asking in many Community Calls but I haven't had any ETAs yet, so hopefully posting here helps.

Please could we have a consistent method for Word, Excel and PowerPoint to save a file? Word and Excel have ‘context.document.save()’ and ‘context.workbook.save() but they lack similar options for behaviors (eg. skip the save dialogue). PowerPoint does not have context.presentation.save() yet. Please could we have an equivalent method for all three (Word, Excel, PowerPoint) with similar options/behaviors? This is really needed for developers. Please an ETA would be appreciated.

Similar to the previous question, could we have an equivalent method for all three (Word, Excel, PowerPoint) to close files with similar options/behaviors? This is also really needed for developers. Please an ETA would be appreciated.

Thank you so much in advance!

**Comment by chiz-ms** [comment]
Thank you for this feature request. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please see if your feature has already been requested or request a new feature. Feature requests are considered when we go through our planning process.

Thanks,
Microsoft 365 Developer Platform team

**Comment by jaime-rivas** [comment]
Thank you! Leaving the link to this request in the Platform Ideas Forum:

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/office-js-save-and-close-methods-for-word-excel-and-powerpoint/idi-p/2800214
