### ISSUE TITLE
Office.context.mailbox.item.body.getAsync drops line breaks in compose mode in OWA

### ISSUE THREAD

**Issue by sys0601** [OfficeDev/office-js#2151]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
Office.context.mailbox.item.body.getAsync() drops line breaks when used in Outlook OWA in Compose Mode.

It works ok in Read mode and it works OK in REad/Compose on the Outlook desktop. Error only occurs specifically in OWA and Compose mode.

## Your Environment

I have tested this on Chrome and Edge and the results are the same.
I have also tested our own code and a simple script in Script lab with same results.
 
## Expected behavior
Line breaks would be preserved.

## Current behavior
If I create an email with the body consisting of the following 3 words on seperate lines
grumpy
old
man

Office.context.mailbox.item.body.getAsync()  will return one word... combining them all together:
grumpyoldman

## Steps to reproduce
Try the following code in Script lab. (link given later)
Please test on OWA and in Compose mode.

$("#get-selected-data").click(getBodyText);

function getBodyText() {
  Office.context.mailbox.item.body.getAsync(Office.CoercionType.Text, { asyncContext: "This is passed to the callback" }, (result) => {
    if (result.status === Office.AsyncResultStatus.Succeeded) {
      console.log(result.value.length);
      console.log(result.value);
      console.log(result.asyncContext);
    } else {
      console.error(result.error);
    }
  });
}

## Link to live example(s)

Script Lab Link
https://gist.github.com/sys0601/d4c6e37fccdbf9adb9e018fc463ab13b

# Provide additional details

1. Login into OWA
2. Create a new email
3. Type 3 words in the body... each on its own line
4. Run the script

## Context

We are doing some verification tests on the email before it is sent out. This makes the tests difficult as the information returned for the body has words running into each other.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding the body.getAsync API in OWA.  It has been put on our backlog. We, unfortunately, have no timelines to share at this point.
Internal tracking id: Office: 2380361

**Comment by sys0601** [comment]
Thanks. Is there anyway it could be prioritized. It is very difficult to use in its current form as words end up getting combined.

**Comment by exextoc** [comment]
@sys0601  As a workaround to this issue, Could you try using the API with CoercionType.Html to get the line breaks.

**Comment by sys0601** [comment]
Thanks. This will do for now but it would be great to get a fix as the HTML may caused it's own issues depending on the use case (it is ok for my needs for now).

**Comment by onestep** [comment]
I experience the same issue in read mode now. Body is returned with line breaks in Exchange 2019 OWA, and without line breaks in Office 365 OWA. This only happens with emails in HTML format, emails in text format are returned as expected.

![example HTML body](https://user-images.githubusercontent.com/1419318/162242347-4474c5bb-fdc7-41d2-b396-2886b20af1b4.png)
![value from console debugger](https://user-images.githubusercontent.com/1419318/162243353-c83bb7bc-6158-4af0-b4e1-c971d1015422.png)
