### ISSUE TITLE
Excel Add-in: add-in misbehaving on Windows version 10.0.19043 and Office version 2018 Build 14326.20404

### ISSUE THREAD

**Issue by cidev5** [OfficeDev/office-js#2153]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We have an add-in that has stopped behaving correctly for a client that has updated their OS and Excel to the mentioned versions.

I was able to reproduce the issue and it appears present only when Excel is using the Legacy Edge browser engine. Once I install the Webview2 runtime the issue doesn't occur.

I've noted the Windows version because I could not reproduce this on an older version of Windows 10 with the same specific Excel version but it's possible the Windows version is irrelevant and something else was at play during my testing.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2108 Build 14326.20404
* Operating System: Windows 10 Enterprise Evaluation 10.0.19043 Build 19043
* Browser (if using Office on the web): ______
 
## Expected behavior

On a clean install of the latest Windows and latest current channel update to Excel the add-in should function correctly.

## Current behavior

Various issues occur after saving an excel file with a custom function in it, and then reopening the file.

User can no longer sign-out of our add-in using the Sign Out button and custom functions cease to function correctly after a minute of time has elapsed.

## Steps to reproduce

1. Install and log in to our add-in with our test credentials ("Remember my login" can be checked)
2. Enter one of our custom function into a cell and observe that it returns values initially (I can provide the function to test with)
3. Save the workbook to a local file system.
4. Close Excel and open saved file directly, log in again if you did not click "Remember my login".
5. Observe that immediately, the custom function will still work up until a minute or so has passed.
6. Wait the required amount of time and observe that refreshing functions now returns an add-in produced error relating to authentication. Also observe that trying to sign out has no effect.

## Link to live example(s)

This can be reproduced currently in the live add-in available in the Microsoft store. 

May I private message someone the add-in name to search, and the login credentials to test this with?

## Context

At least one client of ours is now affected, and assuming more clients will be updating their versions we might have an uptick of issues related to this. I would rate this very critical from a business standpoint.

**Comment by cidev5** [comment]
I believe I've identified where the issues are manifested in our code.

We have this method that is called at a 30 second interval:

![image](https://user-images.githubusercontent.com/22505624/135544818-960e8f4f-74d4-4248-9e6c-ebd56c8c160d.png)

I expect the console.log to print to the console every 30 seconds, and it does so normally. However, under the conditions I've indicated above the console.log prints a total of 2 times and then no more.

This could only happen if `OfficeRuntime.storage.setItem` failed to `setItem` and thus did not set `this.isUpdatingToken` to false.

![image](https://user-images.githubusercontent.com/22505624/135544870-b504f8fb-f175-4b80-98f6-f81612a52210.png)

Similarly our log out button requires `removeItem` to resolve but it must not be doing this and thus one cannot log out.


Can this issue please be escalated?

**Comment by cidev2** [comment]
Hi,

Could you please treat this with high priority? It's making our enterprise application unusable since it's affecting the authentication and authorization.

Thanks,
Petre Lukarov

**Comment by cidev5** [comment]
Is there any movement on this, or at least a suggestion of a way we can circumvent the issue? Have you been able to reproduce it?

~~From what I can tell `OfficeRuntime.storage.setItem` is simply not setting the item to storage or something is immediately clearing it out of storage.~~

~~I've tested trying to set a simple test key/value pair and inspect Local Storage within Microsoft Edge DevTools, and I do not see any entries that I expect to see. Setting values directly to Local Storage using the native window LocalStorage API works as expected. I've removed all references to `removeEntry` and `removeEntries` from our code in case they were being tripped somehow but the result is the same.~~

Please disregard above. It would seem I should be looking in AsyncStorage in the Wef folder.

Update: I see the values in question in AsyncStorage. And removing items does appear to remove them. But the `.then` method on what is expected to be a promise don't seem to get called, as I cannot console.log anything from within them.

**Comment by madhavagrawal17** [comment]
@cidev5, I tried to reproduce this issue locally but OfficeRuntime.storage.* APIs are working properly for me.  We handle OfficeRuntime.storage.* APIs differently for SharedRuntime and Non-SharedRuntime scenario. So, I want to understand if your add-in is a SharedRuntime add-in or not. In order to debug this issue could you please provide us below details:
1. Manifest file of the add-in (If you have your add-in published to the store then please provide the details of the store add-in so that I could check the manifest details about it). 
2. As we will need to get further information from you and follow up offline, can you please send a frown from within the Office application, as detailed here: https://support.microsoft.com/en-us/office/how-do-i-give-feedback-on-microsoft-office-2b102d44-b43f-4dd2-9ff4-23cf144cfb11. 
In the description, please be sure to indicate "To Office Platform team: Following up on issue [GitHub issue link].  Please contact me for further information."

**Comment by cidev5** [comment]
@madhavagrawal17 Thank you for the reply.

Our add-in does not use the SharedRuntime. I understand the browser it uses is IE11 when the Webview2 runtime is not installed. The problem as I mentioned is apparent in Legacy Edge only.

Regarding 1. I have sent you an email indicating the name of the add-in in the store. We wish to not publicize it as it is intended for our clients and not the general public.

2. has been completed.
