### ISSUE TITLE
Add-In doesn't show update ability when new version is available in store.

### ISSUE THREAD

**Issue by FromPerm** [OfficeDev/office-js#2155]
When new version of [Add-in](https://appsource.microsoft.com/en-us/product/office/wa104379640?tab=overview) is available in MS store our clients don't see any information about update ability.

## Your Environment
PC, Excel, Microsoft 365 Version 2107(Build 14228.20250) 64 bit, Windows 10
 
## Expected behavior
After new version of add-in is available in MS store it automatically should show update page.

# Provide additional details
Office Online works as expected - when you open Add-In it shows update ability if new version is available in store Add-In. After updating online, the desktop also updates the version.

**Comment by ElizabethSamuel-MSFT** [comment]
@FromPerm Are you still facing this issue?

@JuaneloJuanelo @preethikakiru Any ideas about this?

Thanks.
