### ISSUE TITLE
Word addin proactively rejects IE 11

### ISSUE THREAD

**Issue by GeorgHue** [OfficeDev/office-js#2156]
Hi there,

I am running addin tests using Windows 10 21H1 and Microsoft Word 2016 (16.0.5188.1000) MSO (16.0.5215.1000) 32-Bit volume license edition. 

The addin cannot be loaded: "ADD-IN ERROR Sorry, we couldn't load the add-in because your browser version is not supported. Click here for a list of supported browser versions". 

Does that mean that every office version using IE 11 for addins is not longer usable?

"Click here for a list of supported browser versions" is a bit of irony because I cannot switch to another browser if that office version only uses IE 11.

Many greetings
George

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00c430f1-bbf5-53b8-a225-4fbe8fc39c3b
* Version Independent ID: 0a069a0d-4d35-71ee-53af-8c55fe8548a0
* Content: [Browsers used by Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)
* Content Source: [docs/concepts/browsers-used-by-office-web-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/concepts/browsers-used-by-office-web-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by GeorgHue** [comment]
I repeated my tests and I observed on the test system that IE was **disabled** in "control panel | Programs and features | Turn windows features on or off". Office had no chance to load IE. 

So I have to modify my questions: Are addins in Office 2016 volume license edition are still usable if IE is disabled? Is it possible to switch to another addin browser in such cases?

Many greetings
George

**Comment by AbidRahman-MSFT** [comment]
Hey @GeorgHue - if you are using Word on Windows in Office 2016, unfortunately IE is the only browser that can run Office Add-ins. You can of course use Word on Web where add-ins can run on the underlying browser (for e.g. running Word in the Edge browser will use the Edge browser as the add-in runtime). 

The webpage [here](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) lists all the browsers that are used for add-ins depending on the version of Office that you are on.

**Comment by GeorgHue** [comment]
Hey @AbidRahman-MSFT, thank you very much for the information. I will close this issue now.
