### ISSUE TITLE
Unable to show Addin while sideloading in MAC.

### ISSUE THREAD

**Issue by jrpally** [OfficeDev/office-js#2157]
As you can see I have the file in the right WEF folder in MAC

But I can't see the Addin. I downloaded Word via Apps for MAC
![image](https://user-images.githubusercontent.com/8353590/135739122-c039fe9c-571b-40b4-978a-ba1562d94bf6.png)

**Comment by nancy-wang** [comment]
thanks so much for this feedback @jrpally! Tagging @AbidRahman-MSFT - Abid, might you be able to see what the source of this issue is?

**Comment by AbidRahman-MSFT** [comment]
Hey @jrpally - this issue can arise if the manifest is not valid. Are you having these issues after modifying the manifest? Does it occur on a brand new manifest that was generated with yeoman generator?

**Comment by jrpally** [comment]
HI @AbidRahman-MSFT. I would say that I modified the manifest to write my app, yes initially I used yeoman. Can I provide the manifest to you by email? If you can provide me your email please?

**Comment by AbidRahman-MSFT** [comment]
Hey @jrpally - are you having the same issue with a brand new manifest? Or does the issue only occur with your modified manifest?

If the issue is only with your modified manifest, I would first suggest validating the manifest using the tools we have here: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest

**Comment by jrpally** [comment]
Hi @AbidRahman-MSFT 

I got:
Error # 1:
XML Schema Validation Error: Error found during XML Schema validation.
  - Details: The element 'VersionOverrides' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides' has invalid child element 'Hosts' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides'. List of possible elements expected: 'EquivalentAddins, ConnectedServiceControls' in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides' as well as any element in namespace 'http://schemas.microsoft.com/office/taskpaneappversionoverrides/1.1'.
  - Line: 61
  - Column: 6

Error # 2:
XML Schema Violation: Your manifest does not adhere to the current set of XML schema definitions for Office Add-in manifests.

Error # 3:
Missing Support URL: The manifest support URL could not be found.

Any way I can update my current manifest?

Strange it works for Office Desktop and Web Version

**Comment by AbidRahman-MSFT** [comment]
Hey @jrpally, you can alter the xml manifest directly and update the instance in the wef folder to see if it fixes the sideloading issue. Once the validator issues are resolved and the manifest passes validation, it should display as expected when trying to sideload. 

I'm also including @madhavagrawal17 for any specific questions you may have around the manifest.

**Comment by jrpally** [comment]
Hi @AbidRahman-MSFT just curious why Word for desktop not validating the manifest? Same with Word for Web, my manifest works there. Backward compatibility?

**Comment by AbidRahman-MSFT** [comment]
Hey @jrpally - please forward the manifest at abid.rahman@microsoft.com. There may be some properties specific to mac that is causing the issue here. We can investigate and let you know. Thanks!

**Comment by jrpally** [comment]
Hi @AbidRahman-MSFT I sent to your mail

**Comment by AbidRahman-MSFT** [comment]
Hey @jrpally - sorry for the delay here. We are unable to reproduce the issue. We have tried to sideload the manifest on our machines and it is working as expected. Are you still having issues?

**Comment by ElizabethSamuel-MSFT** [comment]
@jrpally Are you still facing this issue?

Thanks.
