### ISSUE TITLE
Table column cell value is not reflected after updating

### ISSUE THREAD

**Issue by saivishnutammineni** [OfficeDev/office-js#2158]
I am creating a excel add in, which would read data from table in a excel sheet, perform some calculation, update some columns in the table.

When the writing back to excel is complete, only few of the updated cells reflect the change. Others show old values.

* Platform [PC desktop, Mac, iOS, Office on the web]:  WEB
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: O365 Build number 16.0.14519.31877
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
The updated cells should have updated data shown

## Current behavior
Some changes are not reflected in the updated cells.

## Steps to reproduce

1. Create a table with huge row height. (nearly half of window size each)
2.  Add many rows so that most of the rows are not visible on the screen
3. Try updating some columns in every row programatically via add in
4. The data is not reflected in the excel sheet in some columns
5. The interesting thing is if i double click on the cell the correct value is shown, or when i read table data programatically through add in, i get correct data

# Provide additional details
1. As might have been apparent from the steps to reproduce we are able to see this issue when the rows that are updated are not in view
2. So based on observation 1 above we decreased the size of rows (all rows were in the viewport) to be smaller and all changes reflected well
3. Another observation here is, when i add 100 rows of data to table, add a value in the first cell of a column and drag down to copy the value to other cells in the column, the data is not copied to all cells, but some cells still show old data
4. So is this issue something related to Excel on Web not updating cells which are not in view port?

**Comment by chiz-ms** [comment]
Thanks for reporting this issue. We have been investigating but haven't succeeded in reproducing it. Could you help to provide more details so that we could stably repro this issue? Such as:

1. A screenshot of the Excel Online web page;
2. The necessary row/column count of the table;
3. The API you called to update the columns;
4. Whether you have scrolled the cells into the view and still seen outdated values;
5. The O365 update channel (https://docs.microsoft.com/en-us/deployoffice/overview-update-channels) you're in.

And please feel free to add any other information that could be helpful to reproduce the issue.

**Comment by saivishnutammineni** [comment]
I have created a repo for reproducing for the issue, please find the code [here](https://github.com/saivishnutammineni/excel-update-issue).
The excel sheet along with various alignments of text is attached.
[excel-issue.xlsx](https://github.com/OfficeDev/office-js/files/7317419/excel-issue.xlsx)

Steps to reproduce the issue:
1. Sideload the sample excel add-in from above repo in office online.
2. If using a new excel sheet click on run button once. and then click on update button.
3. If using the excel sheet attached update button can be used directly.
4. Note that `col7` has the long text wrapped.
3. The code logic is when update is clicked the data in `col3` is changed between a and b.
3. We can notice that after clicking on update and when we scroll to check the changes in the rows, some rows show old value i.e when it should have been 'a' it would be 'b' and vice versa. And double clicking on a cell with the issue will show th correct value
4. The below screen shots show the issue. the first screen shot is the cell with issue showing 'b', and on double clicking on cell shows 'a'!
![image](https://user-images.githubusercontent.com/51150765/136696755-6dc8c005-4064-4267-b4b7-4876cc5e992c.png)
![image](https://user-images.githubusercontent.com/51150765/136696806-769ce742-47eb-4749-b986-c70e9a49f5fa.png)

Hope this will help in reproducing the issue.

Note:
1. This is with office online in chrome browser
2. The initial clicks of update button click does work fine. I had to repeat the update button click multiple times (not immediate clicks. just multiple times with some gap in between)

**Comment by chiz-ms** [comment]
Bug VSO#5488252 is opened in our backlog to track this issue.

**Comment by yuc014** [comment]
Hi, @saivishnutammineni. Thanks for reporting this issue. 
After investigation, I thought this is an UI refreshing issue. The right value is saved in the cell, but shown old value on UI. This issue would not affect calculation in the sheet.
I would like give a workaround to unblock your issue.
```
async function update() {
  await Excel.run(async (context) => {
    try {
          const activeSheet = context.workbook.worksheets.getActiveWorksheet();
          let table = activeSheet.tables.getItemOrNullObject("Sample");
          table.load("isNullObject");
          await context.sync();
          if (table.isNullObject) {
            console.log("table is not present. Please click on run first!");
            return;
          }

          //add code part one
          table.columns.getItem("Col7").getDataBodyRange().format.wrapText = false;
          await context.sync();

          const updatedColumnValue = updatedValue === "a" ? "b" : "a";
          updatedValue = updatedColumnValue;
          const updatedColumnValues = new Array(20).fill(updatedColumnValue).map((i) => [i]);
          table.columns.getItem("Col3").getDataBodyRange().values = updatedColumnValues;

          //add code part two
          table.columns.getItem("Col7").getDataBodyRange().format.wrapText = true;
          activeSheet.getRange("A1").select(); // back to the top, can be remove if do not need
        } catch (error) {
          console.error(error);
        }
  });
}
```
I added four lines of code in your 'update' method. Take a look at "add code part one" and "add code part two".
Hope that would unblock your issue, if this not work, please let me know.
We will continues investigate the root cause, thank you!

**Comment by saivishnutammineni** [comment]
Hi,
Thanks for the workaround. I am glad the issue could be reproduced. We are following a workaround where we update the sheet twice. As currently the number of rows we are dealing with are very less in prod and we started to decrease the row size by restricting it's height we are not seeing the issue. Will certainly try this.
