### ISSUE TITLE
Office.js not detecting content controls

### ISSUE THREAD

**Issue by libjosep** [OfficeDev/office-js#2160]
I have a document with two content controls. I am using office.js to print the text in all the content controls, but it is not printing the text for all the content controls. I have added a VBA to achieve the same and it is printing the text for all the content controls.

    Sub getCCText()

        Dim ContentControl As ContentControl

        For Each ContentControl In ActiveDocument.ContentControls
            Debug.Print ContentControl.Range.Text
        Next ContentControl
    End Sub

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop and Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2108
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome
 
## Expected behavior

When I use `context.document.body.contentControls`, it should return me the collection of all the content controls in the document.

## Current behavior

Currently, `context.document.body.contentControls` is returning a collection of all the rich text content controls in the document. It isn't giving plain text content controls.

`context.document.body.contentControls` should give a collection of all the content controls in the document.

## Steps to reproduce

1. Add different types of content controls to a document
2. Use `context.document.body.contentControls` to get the content controls available in the document

## Link to live example(s)

1. https://gist.github.com/libjosep/7867e132990280af76326f49be92ab39

# Provide additional details

1. I have a document to reproduce this issue. Please use https://a830edad9050849nda3296-my.sharepoint.com/:w:/g/personal/libin_a830edad9050849nda3296_onmicrosoft_com/EQXclZufC_BBlj2H-QsLEQQBn6WMsBN4Zf5gKobrc_hv_A?e=Tly1mv to run the scriptlab snippet

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by AbidRahman-MSFT** [comment]
Hey @libjosep,

Unfortunately this behavior is by design. We do not currently support plain text content controls in the Office JS platform. The content control APIs will only return rich text content controls. This is noted in the header of the following documentation: https://docs.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview

**Comment by dasramen** [comment]
The documentation says plain text CC is supported!!
