### ISSUE TITLE
Outlook Add-ins do not work on iPad 

### ISSUE THREAD

**Issue by gitcnd** [OfficeDev/office-js#2161]
## Expected Behavior
Can load and use add-ins

## Current Behavior
a. on first-run of outlook after a fresh install, it wrongly reports "add ins have been disabled by your organisation"
b. close and re-start outlook, and then then both add-ins sub-menus (the ... menu from in a message, and the add-in settings menu item) hang forever on a loading screen.

## Steps to Reproduce, or Live Example
Set up a new account on iPad outlook, and try to load some add-ins.  If (by fluke) it works, load some more and reboot your iPad.  It will always lock up soon, and is not recoverable.

## Context
Trying to test my add-in on Outlook.
I've tried 2 different accounts (hotmail plus an organisational office 365), and about 20 different scenarios (resetting accounts, deleting and re-adding accounts, uninstalling and re-installing outlook)

## Your Environment
Modern iPad, latest iOS, latest Office.

**Comment by exextoc** [comment]
Thanks for reporting this issue . It has been put on our backlog. We unfortunately have no timelines to share at this point  but we are looking to it on priority

**Comment by readnotify** [comment]
My iPad is still locked-up on "initializing".  I've force-closed Outlook and re-started it - same problem.

@nancy-wang - please REMOVE the tag "product feature request" - this is NOT a feature request - this is a bug in your code which prevents all add-ins from working on iPad.
