### ISSUE TITLE
Icons missing in the Mac ribbon

### ISSUE THREAD

**Issue by YossiCohen** [OfficeDev/office-js#2162]
I've created a simple add-in for Excel by using OfficeJS.
Everything worked fine when I've tried to use it on a Windows machine and on Excel for Web (in chrome browser).
When I tried to use the add-in on a Mac the add-in worked but I couldn't see the ribbon icons.

I thought that the icon was corrupted as suggested here: https://stackoverflow.com/a/53367657/1726419 so I've used the icon from the template example - it still didn't work.

any suggestions?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.53
* Operating System: macOS 11.3.1
* Browser (if using Office on the web): ______
 
## Expected behavior
See the icons :-)

## Current behavior
Can't see icons

## Steps to reproduce
that's a problem because the server is in a closed environment

# Provide additional details
I've tried to use PNG and BMP images
also tried HTTP and HTTPS URLs
in all cases - things worked properly on browser and windows and didn't work on Mac.

## Context
Without icons, in the ribbon, the add-in looks unprofessional.
I've also tried to clear the cache - didn't worked

## Useful logs

- [ ] Console errors
Is there a way to see console log /debug this?
- [ ] Screenshots:
- [ ] On web browser:
![image](https://user-images.githubusercontent.com/13462946/136201865-4e9b2ad6-8647-4a18-b970-76c0e79e55f2.png)
- [] On Excel for Mac:
![image](https://user-images.githubusercontent.com/13462946/136201949-281b3c5c-016b-48d0-a376-01ef6de9a8a3.png)

- [ ] Test file (if only happens on a particular file)

**Comment by nancy-wang** [comment]
thanks so much for sharing this feedback with us @YossiCohen! Connecting you with @gingerjia who may be able to help figure out what's going on here.

**Comment by YossiCohen** [comment]
Is there any errors log that can be enabled to see what went wrong?

**Comment by YossiCohen** [comment]
I've asked this also at  SO: https://stackoverflow.com/questions/69456784/officejs-addin-ribbon-icons-not-showing-on-mac

**Comment by gingerjia** [comment]
@YossiCohen We have worked with partner team for the issue. Any progress will update here. Thanks!

**Comment by YossiCohen** [comment]
The problem was related to self-signed certificates, Excel for Mac not displaying ribbon images if they are not signed with proper CA.

The Web and Windows versions work and also display icons from HTTP (not HTTPS) but again - in Mac, you must have a good certificate.

After moving the server to use a certificate that was signed properly the icons in the ribbon were also displayed properly.

last note, the images in the task-pane displayed properly even though I had a self-signed certificate.

**Comment by ElizabethSamuel-MSFT** [comment]
@YossiCohen Glad to hear your issue was resolved. Closing out this issue.
