### ISSUE TITLE
OAuth dialog not completing for Outlook add-in in specific browsers.

### ISSUE THREAD

**Issue by liaofranku** [OfficeDev/office-js#2164]
From the main add-in process, we use `Office.context.ui.displayDialogAsync` to start a Google sign-in dialog.

After authentication succeeds in the dialog, Google sign-in redirects to [this HTML file](https://addin.meet/static/oauth_redirector.html) which messages the main process which is listening for a token.

Recently (within the last 2-3 days), this flow stopped working due to an Office.js error, but only in  Chrome/Firefox.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook on Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Browser (if using Office on the web): Chrome/Firefox
 
## Expected behavior
1. Google sign-in completes and redirects to https://addin.meet/static/oauth_redirector.html within the dialog
2. dialog runs script from above file, messaging parent with token
3. parent closes the dialog

## Current behavior
1. Google sign-in completes and redirects within the dialog
2. dialog tries to message parent
3. dialog throws error
4. dialog hangs on blank screen and does nothing more

## Steps to reproduce
1. Download Google Meet add-in from https://appsource.microsoft.com/en-us/product/office/wa104381851
2. Try to 'Add a meeting' or log-in to a Google account through the settings pane
3. After attempting to logging in, observe that the dialog stays on white screen and that you remain not logged-in

# Provide additional details
My own debugging notes:
- The cause _should_ be external to our own add-in code because I observed the issue showing up in old previously-working add-in builds from past manifests.
- Both the parent and dialog throw their own noteworthy errors, but the parent does so first. I think the dialog only throws an error because the Office.js dialog lifecycle broke in the parent. See log links and code examples below.
- The issue does not repro in Safari/IE, so it's possible that the error is caused by code becoming newly incompatible in latest Chrome/Firefox versions.

The code for our dialog sign-in callback can be seen in [this file](https://addin.meet/static/oauth_redirector.html).

Our code for the parent process basically looks like this:
```
Office.context.ui.displayDialogAsync(
  oauthUrl, dialogSize, (result) => {
    if (result.status == Office.AsyncResultStatus.Failed) handleError(...);

    const dialog = result.value;

    dialog.addEventHandler(
        Office.EventType.DialogMessageReceived, (event) => {
            dialog.close();
            ... // Extract and use token from `event.message`.
        });

    dialog.addEventHandler(
        Office.EventType.DialogEventReceived, (event) => {
          handleError(event.error);  // 12006 thrown here as soon as
                                     // dialog opens.
          dialog.close(); // This line doesn't close dialog, so lifecycle
                          // is likely broken by this point.
        });
  }
);
```

## Useful logs
- Screencast: https://youtu.be/SSrvPPzbxcY
- Parent process errors: https://pastebin.com/k24Zy8dK
- Dialog errors: https://pastebin.com/kvPtRadL

Thanks :)

**Comment by iotataru** [comment]
@liao-frank after investigation, we determined this is caused by the "Cross-Origin-Opener-Policy" header which is unfortunately not supported by the platform at this time. We recommend removing this header from the webpages loaded by the dialog window.

**Comment by liaofranku** [comment]
Thank you!
