### ISSUE TITLE
Access mailbox.item on select

### ISSUE THREAD

**Issue by tayokens** [OfficeDev/office-js#2165]
Is there any plan on giving Outlook 365 Addins (mobile and desktop) the ability to access items in the inbox once selected, without the need of opening the item and pushing the Addin button?

And more, modify the content of the email before showing it to the user.

I'd find this very useful in so many scenarios, being able to scan the contents of the email (raw if possible, even if it's encrypted or signed) preventing the user to open attachments, even adding info to the email body or subject, showing notification balloons related to email content, etc.

**Comment by nancy-wang** [comment]
Hey @tayokens thanks so much for taking the time to share your suggestions for improving our product! Passing along your feedback to @exextoc to consider as a feature request.

**Comment by exextoc** [comment]
Currently the feature you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
