### ISSUE TITLE
Cursor jumps between the document and MS word add-in task pane without any mouse clicking.

### ISSUE THREAD

**Issue by careernavigator** [OfficeDev/office-js#2166]
**Issue Summary**
While using the word add-in, Cursor jumps between the document and add-in task pane without any mouse clicking. We have developed this word add-in using office JS, angular 12 & Kendo UI. Cursor behavior is weird in Office 365 v2102. And cursor is not available in the input field in some specific scenario.

**Your Environment**
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: Word
Office version number: Microsoft® Word O365 v2102
Operating System: Windows 10, 64 bit
 
**Expected behavior**
Cursor should be positioned correctly in the input field so that user could type the text, and it should not jump from document to add-in task pane automatically.

**Current behavior**
While using the word add-in, Cursor jumps between the document and add-in task pane without any mouse clicking.  
Cursor behavior is weird in Office 365 v2102 (have not tested it in Office 2019). 
Cursor is not available in the input field in some specific scenario.

**Useful logs**
PFA code snippet [below-]
https://github.com/OfficeDev/office-js/files/7254381/WordAddInDemoProject.zip

**Comment by careernavigator** [comment]
PFA issue recording-

https://user-images.githubusercontent.com/46817939/136573176-7bc1baa6-d51b-4739-9eaf-38a002ccd6e6.mp4


https://user-images.githubusercontent.com/46817939/136573189-b19624a0-b662-40b4-8598-7c3bcf127d56.mp4

**Comment by ElizabethSamuel-MSFT** [comment]
@careernavigator Sorry we're now getting to this issue. We'll take a look.

Thanks.

**Comment by grangeryy** [comment]
Hey @careernavigator, we tried to use the code snip provided in .zip file but we can't load the add-in :(

- Could you share with us the sample manifest instead?  
- Did you use any Event related APIs in the add-in?
- How did you start the project, such as Yo Tool, Visual studio, or else?

Thanks!
