### ISSUE TITLE
Outlook - Incorrect ewsUrl is used when making a EWS SOAP call

### ISSUE THREAD

**Issue by shnitze** [OfficeDev/office-js#2168]
# Provide required information needed to triage your issue

When using the makeEWSRequestAsync function to call an on-prem Exchange server in order to send an email, the call fails with the error message `The underlying connection was closed`. I've deduced that the ewsUrl used to make the call is incorrect and has a different domain than the OWA and accessing the url in the browser returns a `504 Gateway Timeout` error.

Is there a way to specify which url to make the calls to?

I'm using the Visual Studio template for Outlook Web Add-in. When debugging the add-in, I'm prompted to enter a EWS url but the add-in is using a different url...

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook on the web/Outlook 2016 Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook 2016 (16.0.5173.1000)
* Operating System: Windows 10 Enterprise 1909
* Browser (if using Office on the web): Firefox/Edge/IE/Chrome
 
## Expected behavior

The add-in executes a EWS call with the provided EWS Url

## Current behavior

The add-in used a different EWS url than the provided

## Steps to reproduce

Making an EWS call using the `makeEWSRequestAsync` function to call an on-prem Exchange server

**Comment by exextoc** [comment]
Can you clarify if this is an issue for both OWA and Outlook Win32? Also, which urls you are referring to/how were you able to deduce the different urls?

**Comment by exextoc** [comment]
Some more clarification questions: 

Does the on-prem server have different internal and external ews URLs?

**Comment by shnitze** [comment]
I can't confirm if this issue applies for both OWA and Outlook Win32 since I can't debug on the Desktop app.

To get the valid url for EWS, I went in Outlook Desktop (2016) under Account Settings there's a link to the OWA. I simply changed it from `https://XYZ/owa/` to `https://XYZ/ews/exchange.asmx`

As for if the on-prem server have different internal and external urls, I'm not sure. Is there a way to figure that out?

**Comment by exextoc** [comment]
Is this bug happening in Outlook or on OWA? (or both?) 

I don't believe the URL that Win32 Outlook uses for makeEWSRequestAsync is the one under account settings. It uses the URL obtained via Autodiscover when Win32 connects to the exchange server. 

What version of Exchange is the OnPrem Server? 

This is likely some sort of configuration error on that OnPrem server. It may be worthwhile to try and look at some Fiddler traces and see the actual response from the Exchange Server when makeEWSRequestAsync. You should also be able to identify the URL that Outlook is going to make the EWS request against as well. 

I only mentioned Internal/External, as if you know that was the case, then maybe Outlook was going to the other URL, but you should verify what URL you are going to (and why do you think it's incorrect?) first.
