### ISSUE TITLE
Excel.js shape.getImage returns cropped image after shape was rotated.

### ISSUE THREAD

**Issue by damogongzi** [OfficeDev/office-js#2169]
# Provide required information needed to triage your issue

Shape.getImage() returns cropped image instead of full shape image when the shape has certain degree.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: MAC OS
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Office online
* Operating System: ______
* Browser (if using Office on the web): Chrome
 
## Expected behavior

It should return the full image without crop.

## Current behavior

The image was not full. Checkout below base64 image string.

iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAX6SURBVHhe7Z1PaBxVGMBz8ODBQw8ePAh68FTM7G6yJta22bTJwUPBzMymSZqkiX8bY0wT8eBBaMGDoHZn8qekJpEQqyUoSpVqbautNUVvCiooeKigUEFBaMG6s5uO3zf7Yhvy7XZ3582f3fl+8Ls05L033+6X9968rzMNDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMwDMMw4SH2mLEFvN+NCT2TjOlGuxsb1Uw6phnDblTUzIsx1TjsRmhjBlxyI4zltNJl7hEh3gj80K5Db8S7Z64XM9E9+29872yumE09c9nm3vnrRe1byCX3LdrFbBlctlv3H98k/nthfJmvU6lDd4iPYCM7njlpU+488LGdGj1dte1j5+xd419Ubefkqt35wqW6smXw7Tx8IFcb1al7Rfg3Q/0iK9+dBz5az94uEXoa6pdZue4a/9yO6WZO0TKGCHtxqAZYeXZMfmU39c5lITO+Lzpv3ArVCCvP1qETa7A6+yeRPvKACHlpqEZYObaNnHLmDUU90ivCfXuohlj34koxpk9Z8IEsiFCXB9UY61JYsif75rOwof1pa/fsXSLU5UE2yLpy2/CKM28oqvmgCHP5UA2y1dv27CeFeaMrMyJCXBlUo2x17j54wU7oM/CnylwR4a0cqmG2Cp15Y9FSNPNyxfPGrZCNsxX7yJPv24pm5PHOtghtdVCNs5WZGv0M5g0TJ/IJEdbqoTpgy7fj4Jd2PD1tKbpxSoTUHVQnbPkm+5dysKq60rznjbtFSN1BdcKW5/anPnDmDaXL3CHC6R6qI/b2to+dKcwbmvGyCKUcqM7Y0uIt9UT6aFZRjfNl3VKvBKpDtrQtg8t5yI4/t3a/do8IozyoDtnibn/6w/Vb6o+KEMqF6pSlxcINPIqF/carInzyoTpmN+scxfbgUWyJEh4ZUJ2zm23d/w6sqMyrWPgnQucNVOfsRssu4ZEBNQD2pk4Jj2bmyyrhkQE1CFY4uWo39R7Do9gf7hs6dKcImbeQA2EdKy7hkQE1EPZmCQ8scwdEqPyBGkzU3T1+3o6lp6xGLbMswuQf1IAirXMUu2DBRP6zq6PYasENDzmwiLrt8RU7rppZ2G/ERYj8Be/pUwOLoqnRT3GJu1Z1CY8M4ukZi7OkUMKDsXBVwiMDWNZZnCWX7OZ9iznYb/wGf6q2iNAEA+5Ao54l0kp4ZICHLFHOEqklPLJQ1MwrcX06clnSMXHRKeGJa+YZEYpwgH83YVd6DVOXGni9Kr2ERyaQsodj+lQOvzXU4OtNUcIDS1yJJTwy+T9LnniPvIB6sn3srB1TzTx+CcXlh5MoZAnOk/Huo5YnJTyyiUKWYAmPopt/l3yaQpio5yzBR4bgLXXPSni8AO9wwqD/qrcs8aWExytg0BM4eLy/Q11crYnzhlPCoxrfhn7eoMDzY8ySh4dPkBdYa7YOvYtF0ddgjvS2hMdLnCyBpWGtZ4mvJTxeUg9Z4jxNQYP9hmbMicuqbWo6S7CEp+eYBbvxH30r4fEakSVXsByGvOgQG0gJjx/ABzJca1nSNlJ4mgKOXVxG/YDLREU1f8ViY+riw2ahhGc6mBIev3CyRDPXsM6VCkJohHmjuW8+B2P9JZASHr9Yz5KWweOhzhK8uwDzhgX7jWBKePwk7FkSihIeP3GyRDMv47NnqYAEaeFpCjO4xD0phhsNsPA4jFmS7H8rD1+W3/H4QAw1OuBGK0xZEqoSniCAuaQLswSPQakA+WnquUIJj6JlXhLDiyaYJQ8NLAWaJXiAltg7m41pU2fFsKJLIUsMp1iACpYf4hcCxvBHKEt4gsDJkv4liwqW1+LTFKD/tbiW6RTDYYLKkpop4QmCmG5842eWrJfwwBdhtSaPYr0GX0XkZ5a0DCzfqKkSniDAbyv+3woqgDKtyRKeIFjPEnzNERVIGbY/fw73G7iqel10y5TCyZK+BU+yBOeNRM8cPqD4O543ysTLLKmLEp4ggKXoxWTfQpYKarXim+Lwg67ohShMAeflkRKzRLwQJafoxpuiiwjQ0PAfjR9RHO90t7sAAAAASUVORK5CYII

## Steps to reproduce

1. Add shape into excel.
2. Rotate the shape to certain degree.
3. Call shape.getImage() api, the image returned is not full image.

**Comment by chiz-ms** [comment]
Thank you for reporting this issue regarding [Shape.getAsImage](https://docs.microsoft.com/en-us/javascript/api/excel/excel.shape?view=excel-js-preview&viewFallbackFrom=excel-js-1.14#getAsImage_format_) API. The issue has been confirmed and put on our backlog as VSO#5490219.

**Comment by donlvMSFT** [comment]
Thanks @damogongzi for reaching us, the fix for this issue is in process of rolling out, and will release in 2 weeks.
I'll update here when it's on PROD.

**Comment by donlvMSFT** [comment]
The fix already been released to public clouds, @damogongzi , please help verify and see if it works.
