### ISSUE TITLE
Outlook-win: Office.context.mailbox.item.to contains own address in sent mails

### ISSUE THREAD

**Issue by brafreider** [OfficeDev/office-js#2170]
Since around 2021-10-05 our Outlook AddIn started to display wrong recipients for mails in sent-items. Instead of the first recipient of a mail, it always returned the own address. Web client is not affected. 

- Within the inbox, our AddIn uses item.from.emailAddress to lookup contacts in CRM. 
- To identify sent items, it compares userProfile.emailAddress with item.from.emailAddress. If true, it uses item.to[0].emailAddress for lookup

since last week, more and more customers, all using current Outlook-Win clients from Office 365, reported the wrong lookup address for sent items.
Before posting this issue, I updated @microsoft/office-js to 1.1.71

in Outlook web client, item.to[0].emailAddress contains the first recipient, this is what I would expect. In Outlook-Win, [0] contains the own address and [1] contains the first recipient. If this is the intended behavior, it should be consistent across different client-implementations.

I'm not sure, if this has to be addressed here, because it's probably a new Outlook bug/feature, but to be able to develop cross-client AddIns, the API should be consistent...

BTW: is there a better way to identify SENT items  than comparing userProfile.emailAddress with item.from.emailAddress? I was searching for a direction or sent flag, but without luck.

Cheers,
Björn

**Comment by exextoc** [comment]
I repro the issue with your own email in the item.to. I have filed a bug with the core team, to look into: 

Internal Bug Id: 5494808 

There is no Parent Folder or "Sent Items" property. You could do a makeEwsRequestAsync with GetItem and get the ParentFolderId, or some other info in GetItem may be what you need. 

https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/getitem-operation
https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/message-ex15websvcsotherref

**Comment by exextoc** [comment]
The core team repros and have identified the issue with the Sender being added to item.to. This bug repros in builds: 16.0.14426.10000 and later. 

We will attempt to backfix into those builds ASAP, and will update this thread with progress.

**Comment by exextoc** [comment]
We were able to send out an update to fix this bug. It should be live by now on all builds that had the issue. No updates/reinstallation of Outlook is necessary, but Outlook will need to be rebooted, and maybe the computer rebooted as well. An internet connection is also required for the update to work. 

If you are still seeing the issue, please let us know the build number, and delivery channel that you are on.
