### ISSUE TITLE
Problem in Word OFFICE_ONLINE mode with contentControl.search

### ISSUE THREAD

**Issue by benjamin-almarza** [OfficeDev/office-js#2171]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

In office online mode contentControl.search throws an exception

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: Windows 10 Pro 
* Browser (if using Office on the web): Chrome is up to date Version 94.0.4606.81 (Official Build) (64-bit)
 

This problem doesn't happen in desktop:

* Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2109 Build 16.0.14430.20256) 64-bit 

## Expected behavior

We expect the online version to behave in a similar way than desktop. And be able to search.
If we have to change something please let us know

## Current behavior

In office Word online `await context.sync();` throw an exception after search.

## Steps to reproduce

Run the function "onSubmitFunction"  in Office Word addin online

```javascript
const content = ` 
<html>
    <body>
      <p>
          something [ContractTitle]  [OurIndustry]  [Make] something
      </p>
    </body>
</html>
`;

async function MyScript(context) {
  const currentSelection = context.document.getSelection();
  const range = currentSelection.insertHtml(content, Word.InsertLocation.start);

  const contentControl = range.insertContentControl();
  
  const result = contentControl
    .search("ContractTitle", {
      ignorePunct: false,
      matchCase: true,
      matchPrefix: false
    })
    .load();

  try {
    // this line fails in online
    await context.sync();
  } catch (e) {
    console.error(e);
  }

  console.log(result)
}
const onSubmitFunction= () => {
  try {
    Word.run(MyScript);
  } catch (e){
    console.error(e);
  }
};
```

## Context

This part of the code used to work recently, both on desktop and online.

It is a key functionality for our application.

## Useful logs
This is the error object e.debugInfo
```json
{
    "code": "InvalidArgument",
    "message": "The argument that you provided is not valid. Check the OfficeExtension.Error.debugInfo for more information.",
    "errorLocation": "ContentControl._search2",
    "statement": "var _Search2 = insertContentControl._Search2(...);",
    "surroundingStatements": [
        "...",
        "// Instantiate {selection}",
        "var insertHtml = selection.insertHtml(...);",
        "// Instantiate {insertHtml}",
        "var insertContentControl = insertHtml.insertContentControl();",
        "// Instantiate {insertContentControl}",
        "// >>>>>",
        "var _Search2 = insertContentControl._Search2(...);",
        "// <<<<<",
        "// Instantiate {_Search2}",
        "_Search2.load();"
    ],
    "fullStatements": [
        "Please enable config.extendedErrorLogging to see full statements."
    ]
}
```

**Comment by chiz-ms** [comment]
Thank you for reporting this issue regarding `ContentControl.search` API in Word Online. ADO#5494213 is opened in our backlog to track this issue.

**Comment by kevinjansz** [comment]
This error with `ContentControl.search(...)` seems to be a recent regression and we have users seeing this live in production for word online. The only work around we can advise at the moment is for users to use word desktop instead. 

Is there anything the Word Online team could advise on work-arounds that would be possible in word online (different parameter options for example?). 

Knowing rough timelines for this backlog item (`ADO#5494213`) would be useful too - so we can pass this on to our users for how long they should avoid word online for.

**Comment by chiz-ms** [comment]
Hi @kevinjansz, we believe we have fixed this issue and the fix should arrive production in a few weeks. We'll update here when it's available. Thanks again for the report.

**Comment by chiz-ms** [comment]
Hi @benjamin-almarza and @kevinjansz, we believe the fix should have arrived production. Please verify and see if it works.

**Comment by benjamin-almarza** [comment]
thanks. I will check
