### ISSUE TITLE
Outlook IOS APP, Add-in same have no access for localStorage to save some data here

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#2173]
**Is there some limitation for the Add-in's localStorage of Outlook IOS App?**
Our customer told us all their IOS device can't remember some data on their Outlook App. In our design, these data was stored at Outlook localStorage. So, we want to check with you for some suggestion, Is there some limitation for the Add-in's localStorage of Outlook IOS App?
Such as safari browser's limitation on IOS or any other influencing factors.

**Comment by exextoc** [comment]
Thanks @hello-chenchen for your query. We will get back to you soon on this.

**Comment by exextoc** [comment]
@hello-chenchen 

1. Are you using window.localStorage from your addin's code?
2. Is it throwing any error?
3. Can you also please describe your use-case for which window.localStorage is being used?

**Comment by hello-chenchen** [comment]
hi @exextoc thank you for your reply.
1.  we use localStorage.setItem('key', 'value') to save our data, and localStorage.getItem('key') to get our data.
2.  sorry i haven't get the debug log from our customer right now, it need hours or days maybe.
3.  we use it on the online meeting provide for mobile, FYI [Create an Outlook mobile add-in for an online-meeting provider](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting). 

In this situation, we will save our customer's some option data to the localSotrage. when they re-open outlook and use our add-in, they will use the saved option instead the web default. It works fine in my IOS device. But, in our customer's IOS debice, it seems the option they saved in last operation,  will be lost after they re-open outlook App in IOS device. All their employee's IOS device was been effected.
In my opinion, the high probability root cause is the impact of their company’s unified security settings. But i don’t know which option impact this problem.

i think maybe some safari options , such as: PRIVACY & SECURITY options, SETTINGS FOR WEBSITES → COntent Blockers, Advanced → Website Data, Advanced → Experimental Features.

So i want to get some suggestion from your side.

**Comment by exextoc** [comment]
@hello-chenchen localProperties api is provided by the underlying browser. We do not interfere with the API. To proceed with your Customer we can try following things to find a solution/workaround,
1. Is your customer able to use this api in safari browser in the same device? If no, what is the error which the API returns?
2. Read through (https://developer.mozilla.org/en-US/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API#testing_for_availability), this article talks about different reasons why local storage might not be available.
3. We provide another way to store user state, using RoamingSettings. LocalStorage and RoamingSettings are generally used for different purposes but try to read if using this solves your purpose (https://docs.microsoft.com/en-us/javascript/api/outlook/office.roamingsettings?view=outlook-js-preview).

**Comment by hello-chenchen** [comment]
hi @exextoc , thanks for your reply. our customer's feedback for us:
```
the iOS ones are becoming less easy to reproduce. 
But they will continue to test. 
```
i will keep tracking this issue, and do some research for RoamingSettings.
Thanks a lot.

**Comment by exextoc** [comment]
Hey @hello-chenchen ,

Please do confirm if there's further help you need from us, or we will close this issue.
