### ISSUE TITLE
[SSO] SSO in Word in Addin, which is inside Assignment which is inside Desktop Teams (EDU). 

### ISSUE THREAD

**Issue by MicGensty** [OfficeDev/office-js#2175]
Currently, SSO is not supported when Teams is the host. 
But I can't use a fallback dialog to sign in the user - the dialogue opens a browser from outside Teams desktop (and then there is no communication between the opened browser outside the Teams and the add-in). 

This situation **occurs  if the Word document is opened from Assignment (in Teams for Education desktop version)**. 
In other places in the Teams I can use fallback dialog, the problem is Assignments.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Teams for Education desktop.
* Host [Excel, Word, PowerPoint, etc.]: Word in Teams  (Microsoft Teams Version 1.4.00.26376 (64-bit).)   !IMPORTANT: WORD opened in ASSIGNMENT in Teams (EDU)
* Office version number: 16.0.14530.41001
                         16.0.14609.41000 
                         16.0.14611.41010
                         16.0.14530.41001
* Operating System: Win/Mac

It happen in Microsoft **Teams for Education desktop**, when Word is opened **inside the Assignment**

 
## Expected behavior

Shouldn't be running into issues opening a fallback dialog.

## Current behavior

Opening browser window outside Teams app so fallback doesn't work.

## Steps to reproduce

1. You need Teams for Education desktop version
2. Create Assignment
3. As student hand in assignment with the Word document
4. As a teacher, go to the assignments (in desktop Teams), view the Assignment, open the Word document from the student.
5. In the Word install Add-in with SSO with fallback implemented, for example https://docs.microsoft.com/pl-pl/office/dev/add-ins/develop/create-sso-office-add-ins-nodejs
6. try to log in with SSO fallback - fallback doesn’t work, only system browser opened

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @MicGensty. I apologize for the late reply. I am connecting you with @mattgeim who may be able to help.

**Comment by MicGensty** [comment]
Great, thank you.
@mattgeim do you know any workaround for this issue? 
Or, maybe you can share some information when a fix can be expected?

**Comment by mattgeim** [comment]
@MicGensty Sorry for the delay here.  

The workaround would be to open the document from teams inside of the Word desktop client or Office on the web instead of viewing it directly in teams. 

Right now we are working to enable it but I don't have a timeline to share yet - it is a high priority to enable this scenario in all the places Office documents can be opened. We will announce functionality when it is available, in our documentation for SSO as well as a blog post likely.   Feel free to close the issue if this answered your question, or let us know if you have additional ones.

Thanks,
Matt

**Comment by MicGensty** [comment]
@mattgeim, 
Is there any news on enabling SSO for the user flow we described? It is the most natural way for a teacher to access a document they need to provide feedback on with our add-in.

We have during the spring told customers about the workaround, but it is still a big issue for us, as it adds overhead for each customer making sure they manage to log in the first time, and they are not particularly happy about the complication either.

**Comment by amitsd85** [comment]
@mattgeim : Could you Please provide any update on the above solutions, we are also facing the same issue mentioned above.

**Comment by SAgnihotri200895** [comment]
@mattgeim Do we have any update on this ?

**Comment by mattgeim** [comment]
Unfortunately, there isn't support for SSO with Office add-ins inside of a Teams at this time and we don't have a date to share on updates for this currently.

One option would be to log the feature request for this support at  https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform - this can help us track requests from the community and we can follow up there.  If it was already logged, please feel free to reference that item, I wasn't able to locate a request, but it is possible it was missed when I searched.

I will close this issue, but feel free to re-open if something was misunderstood and please feel free to add a link to a logged feature request if you choose to do so. 

Thanks,
Matt
