### ISSUE TITLE
Loading a presentation with >= 150mb causes out of memory crash

### ISSUE THREAD

**Issue by nermin-slidelizard** [OfficeDev/office-js#2179]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We have an add-in which utilizes the GetFileAsync function to load the current **presentation** into memory.
As most of our clients work with rather large presentations exceeding 200mb and 300 slides per presentation, the JS runtime crashed after trying to load all slices. RAM cannot be an issue, at least i thought so.
After some investigation of the heap size it seems that the **GetSliceAsync** method adds approx. 70-100mb upon every call to the RAM which within itself would not be a problem but it seems that there is a memory leak and those resource are not released properly which then leads to a presentation of 150mb taking up space of about 2,3GB RAM which then results in an out of memory crash.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC and Mac
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: Version 2109 Build 16.0.14430.20292 64-bit with WebView2, MacOS Big Sur Safari 15
* Operating System: Windows 10 Pro 19043.1288
* Browser (if using Office on the web): ______
 
## Expected behavior

Ideally only 4mb should be allocated per slice as given by the argument.
If that is not possible, at least the memory should be released after each slice has been loaded successfully.
Increasing the Slice size could also pose a solution.

## Current behavior

As stated in the summary after every file.GetSliceAsync call approx. 70-100mb are being allocated which results in an out of memory crash after loading several slices.

## Steps to reproduce

1. Download this [presentation](https://www.dropbox.com/s/1qqw72h42y60o8e/Big-Presentation-Sample.pptx?dl=0)
2. Import this code https://gist.github.com/nermin-slidelizard/16cf8280da004e5e3908d7f23bc78a23 into script lab
3. Run the code and watch the memory within the inspector and wait for the crash.

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue with our team @nermin-slidelizard. Our team will look into it!

**Comment by LeonardoDavinci** [comment]
Any updates on this? We are having the same problem when loading a larger presentation file (around 140-180mb).

**Comment by ElizabethSamuel-MSFT** [comment]
@LeonardoDavinci Are you still facing this issue?

@preethikakiru Can you provide current status?

Thanks.

**Comment by LeonardoDavinci** [comment]
@ElizabethSamuel-MSFT yes we still have the issue with larger presentation files! We would be very glad if someone could look into it, since it makes the GetFileAsync API not really usable at all.

**Comment by ElizabethSamuel-MSFT** [comment]
@LeonardoDavinci Thanks for the update.

@wangyun-microsoft Can you take a look and provide status of this issue?

Thanks.

**Comment by wangyun-microsoft** [comment]
Thanks for reporting this. We will investigate it. However, we have no timelines to share at this point.
