### ISSUE TITLE
Cannot load custom conditional format properties when other conditional format types are present

### ISSUE THREAD

**Issue by jesparaz-vena** [OfficeDev/office-js#2180]
Given `const conditionalFormats: Excel.ConditionalFormatCollection` and a sheet with a custom conditional format (type `Excel.ConditionalFormatType.custom`) _and_ conditional formats of other types (e.g. `Excel.ConditionalFormatType.colorScale`), loading properties via `conditionalFormats.load('items/custom/rule/formula')` will fail on `await context.sync()`.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2109
* Operating System: Windows 10 Pro
* Browser (if using Office on the web): N/A
 
## Expected behavior

We should be able to load the properties via `conditionalFormats.load('items/custom/rule/formula')`, then other conditional format types should read `null` (or `undefined`) on properties that do no exist.

## Current behavior

RichApi Error: This operation is not permitted for the current object.

## Steps to reproduce

1. Create a `custom` conditional format, then a `colorScale` conditional format
2. Try to load `'items/custom/rule/formula'` on the active worksheet's `ConditionalFormatCollection`

## Link to live example(s)

1. https://gist.github.com/jesparaz-vena/18b291d77a39b73242c0af39f6cc2061

# Provide additional details
N/A

## Context

Our Vena Add-In creates and deletes custom conditional formats when users open and close different views. If the user has other conditional formats (e.g. `colorScale`, `dataBar`), we cannot directly read `conditionalFormats.load('items/custom/rule/formula')` in order to delete our conditional formats.

As a workaround we are filtering the conditional formats, then reading the properties, but this requires a second `await context.sync()`, i.e.

```js
conditionalFormats.load('items');
await context.sync();

const customConditionalFormatItems = conditionalFormats.items.filter(
  ({ type }) => type === Excel.ConditionalFormatType.custom,
);

const conditionalFormatsToDelete = customConditionalFormatItems
  .reverse()
  .map(item => item.load('custom/rule/formula'));
await context.sync(); // second context sync
```

(Note: we need to load the formula because users can create their own custom conditional formats, so we need to check if the formula contains the name of a hidden sheet that our service uses in order to know if we should delete the conditional format).

**Comment by chiz-ms** [comment]
Could you try using `customOrNullObject` property instead of `custom` property and see if it works?

**Comment by jesparaz-vena** [comment]
> Could you try using `customOrNullObject` property instead of `custom` property and see if it works?

@chiz-ms this works perfectly 🎉 

We are able to load the properties via `conditionalFormats.load('items/customOrNullObject/rule/formula')`.

Please feel free to close this ticket. Thank you!

**Comment by chiz-ms** [comment]
Thank you for the confirmation, @jesparaz-vena. I'll close this issue.
