### ISSUE TITLE
A RichAPI error is occurring on the Office word online when try to access the tables via Office JavaScript Word APIs.

### ISSUE THREAD

**Issue by crestbala** [OfficeDev/office-js#2182]
The issue has been appeared on the Office online when I try to access the **context.document.body.tables** through JavaScript Word APIs. I've created an officejs plugin using react framework, I don't think that it would be an issue because I am not able to reproduce the issue on Office Desktop app, however, it has been showed on the Word online. Also, I've checked the tables API in the **ScriptLab** plugin as well and it is showing the same error when accessing the tables items property.

**Environment**

Platform: Office online
Host [Excel, Word, PowerPoint, etc.]: Word
Office version number: 16.0.14613.41000
Operating System: Windows 10 Pro

Browser (if using Office on the web): Google Chrome version 94.0.4606.81
 
**Expected behavior**

If we able to access the tables on Office Desktop, that should be work same on the Office online rather than throwing an error.

**Current behavior**

The above error which I have mentioned occurs when access the tables property via the Office Word APIs. I am not sure exactly what causes the issue, but I suspect the issue might be occurred in the word-web-16.00.js file at 26 line.

**Steps to reproduce**

1. Go to the https://onedrive.live.com/
2. Open a word document from your side, then just install the **ScriptLab** plugin.
3. Then, create a snippet, replace the existing run() function with the below code:

```
async function run() {
      await Word.run(async (context) => {
        const tables = context.document.body.tables;
        tables.load();
        await context.sync();
        console.log(tables.items)
      });
    }
```
4. Once if you edited, please try to click "Run" button, then you can see that error on both ScriptLab console and as well as the Dev tool console.

**Link to live example(s)**
1. https://gist.github.com/crestbala/139c55b4e8fdbeb77e88de3a5bb07b41

**Context**

The issue has really affected our tool that we are not able to play with the tables data, we are unable get/modify on the document, we do some kind of proof reading using the JavaScript APIs, it would be great if you resolve the issue.

**Useful logs**
Console errors:
```
index.tsx:81 RichApi.Error: Cannot read properties of null (reading 'toUpperCase')
    at new n (word-web-16.00.js:26)
    at n.i.processRequestExecutorResponseMessage (word-web-16.00.js:26)
    at word-web-16.00.js:26
```
```
[ERROR]: Error:
{
    "stack": "RichApi.Error: Cannot read properties of null (reading 'toUpperCase')\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:26:311301)\n    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:26:374532)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:26:372637",
    "message": "Cannot read properties of null (reading 'toUpperCase')",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "Cannot read properties of null (reading 'toUpperCase')",
        "errorLocation": "Table.shadingColor",
        "statement": "tables.load();",
        "surroundingStatements": [
            "var root = context.root;",
            "var body = root.body;",
            "// Instantiate {body}",
            "var tables = body.tables;",
            "// Instantiate {tables}",
            "// >>>>>",
            "tables.load();",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}
```

Screenshots:

1. https://www.screencast.com/t/vEMfDVCaH
2. https://www.screencast.com/t/FmLUjhqN

Kindly, please check this from your end.

Many Thanks,

**Comment by chiz-ms** [comment]
Hi @crestbala, thanks for reporting this issue regarding `TableCollection.load`. Unfortunately we haven't succeeded in reproducing this issue yet. Could you share some further information to help us identify the issue? For example:
- Does it only appear with some certain versions of Word Online?
- Does it only appear with `context.document.body.tables`?
- Does it only appear with `load` method?
- Have you tested with Incognito mode or after cleaning browser cache?

Anything that might be related to the repro would be helpful. Thanks.

**Comment by crestbala** [comment]
Hiya @chiz-ms , 

I have been tried different browsers(including Chrome, MSEdge), the issue is still getting appeared on Word online.

No, it is not appeared only on certain version of word web. 
It has been occurred when I try to access the "**context.document.body.tables**" while load the tables(**tables.load()**). 
Yes, the issue is being appeared on **load** method.
Yes, I've checked this on Incognito too after clear the cookies & caches, but it is occurred on there also.

Screengrab(for your reference):
1. https://www.screencast.com/t/ql2UOp7E
2. https://www.screencast.com/t/Pzw0uzBuw8

Kindly please shed some lights on this.

Many thanks,

**Comment by chiz-ms** [comment]
Hi @crestbala, thanks for all the details. Could you please also share a document file (with all sensitive data removed) that could repro this issue?

**Comment by crestbala** [comment]
Hi @chiz-ms, 

Here I've shared the document link, kindly please take a look at this.

Link: https://1drv.ms/w/s!AselupYGuZUJsw2xwkPBrMRSHqxM?e=6bD8XT

Many thanks,

**Comment by chiz-ms** [comment]
Hi @crestbala, thanks for the additional information. The issue has been confirmed and put on our backlog as ADO#5519802.
In the meantime, could you try this workaround and see if it works?
- Select Table 1 in the document:
![image](https://user-images.githubusercontent.com/19398640/138643924-8337bc28-e530-433e-9993-5e6bb7aea558.png)
- Set cell shading to "No Color":
![image](https://user-images.githubusercontent.com/19398640/138643962-73ae9a44-0e97-4abb-bd52-3a5d1d7f6b71.png)
- Run the script and see the result.

**Comment by crestbala** [comment]
Thanks for your insights @chiz-ms , it is working correctly when I set the **Cell Shading** color to "No Color".

Many thanks,
