### ISSUE TITLE
Outlook add-in - React Web App - MSAL authentication - SSO - Desktop Mode issue

### ISSUE THREAD

**Issue by skurian123** [OfficeDev/office-js#2184]
Authentication implemented using MSAL package ( "@azure/msal-browser": "^2.16.1", "@azure/msal-react": "^1.0.1",) For Outlook Web client - online (O365 version), it's working as expected with login popup opened and getting authenticated successfully whereas it fails to load login popup window for Outlook desktop mode. Similar issue was earlier reported by few users under- #1072 And team responded that bug was fixed for core MSAL package but currently it's not working for React based Outlook Add-in with msal-react.

## Your Environment

* PC desktop
* MS Outlook
* Office version number: Office 365
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Authentication implemented using MSAL package ( "@azure/msal-browser": "^2.16.1", "@azure/msal-react": "^1.0.1",) For Outlook Web client - online (O365 version), it's working as expected with login popup opened and getting authenticated successfully whereas it fails to load login popup window for Outlook desktop mode. But we except the same behaviors of login popup for outlook desktop mode as well.

## Current behavior
Authentication implemented using MSAL package ( "@azure/msal-browser": "^2.16.1", "@azure/msal-react": "^1.0.1",) For Outlook Web client - online (O365 version), it's working as expected with login popup opened and getting authenticated successfully whereas it fails to load login popup window for Outlook desktop mode.

## Steps to reproduce
Access Outlook Add-in from Outlook desktop client
Responded with "You'll need a new app to open this about link"

## Link to live example(s)
n/a

# Provide additional details

**MSAL Configuration**

export const msalConfig = {
  auth: {
    authority:.authority,
    clientId: clientId,
    redirectUri: redirectUri,
    navigateToLoginRequestUrl: true,
  },
  cache: {
    cacheLocation: "localStorage",
    storeAuthStateInCookie: true,
  },
};

**Relevant Code Snippets**

this.context.instance
        .loginPopup(loginRequest)
        .then((response) => {
          this.setState({ currentLoggedInAccount: response.account });
        })
        .catch((e) => {
          console.log(e);
        });

## Context
We initially raised this issues  - https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4095

As per their suggestion we have implemented the below steps;
_In order to do popup auth in an office add-in, the application must open a dialogue using the office SDK, and then perform loginRedirect inside that popup, which this sample demonstrates._ 

Below is our understand and outcome of the sample code codebase.

1. We observed the app.tsx, signinO635 function tries to open a office SDK dialog box in which login html has been called.
2. This login.html in turn call login.js which does the AD authentication using MSALinstance.handleRedirectPromise()
3. Response (includes access token) is return to signinO365. Token is saved in variable in app.tsx
4. If response has success status, dialog box will be closed.

Based on the above understanding, we have retrofitted this logic into our code which has been written in React with JavaScript and using class components.

Only difference between our code and the sample is we are using JavaScript instead of typescript

Our code flows a follows:

1. Initial html file will call parent component (index.js)
2. index.js parent component will render child component app.js
3. While rendering app.js under componentdidmount event, we are calling login asynchronous function which embedded the same logic of signinO365 function shared in the sample code and it calls Office.dailog (Office.context.ui.displayDialogAsync)
4. Inside OfficeDialog function we have called login.html inturn call login.js component which does AD Authentication using MSALinstance.handleRedirectPromise()
5. Same code which receives the Response (includes access token) has been included in this login asynchronous function.

Outcome: Our code flows come till calling login asynchronous function (Refer point #4 from our code flow) after which we expect dialog to open and authenticate the user but this flow gets terminated here and we are not seeing the dialog popup.

Can we have quick WebEx or Teams session to run the code flow and help us with your inputs?

## Useful logs
n/a

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by skurian123** [comment]
Appreciate if someone could look into the issue at the earliest please

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @skurian123. Connecting you with @exextoc who may be able to help.

**Comment by pkkj** [comment]
Hi @skurian123, we have several questions. 1) You mention the dialog doesn't open after you call displayDialogAsync. Would you like to share the part where you call this API? 2) Have you try any example code in your Outlook environment (or Excel)? Does the sample work?

Thank you very much.

**Comment by skurian123** [comment]
Hi @pkkj, thanks for your time to look into our issue. In our App component under componentdidmount we are calling login function which interns calls SIgnINO365 helper function where it reaches there and it runs without opening the dialog popup. We are not getting any error

Please find code block where we were calling above method:

export const signInO365 = async (

  setState: (x: AppState) => void,

  setToken: (x: string) => void,

  displayError: (x: string) => void

) => {

  setState({ authStatus: "loginInProcess" });



  await Office.context.ui.displayDialogAsync(

    dialogLoginUrl,

    { height: 40, width: 30 },

    (result) => {

      if (result.status === Office.AsyncResultStatus.Failed) {

        displayError(`${result.error.code} ${result.error.message}`);

      } else {

        loginDialog = result.value;

        loginDialog.addEventHandler(

          Office.EventType.DialogMessageReceived,

          processLoginMessage

        );

        loginDialog.addEventHandler(

          Office.EventType.DialogEventReceived,

          processLoginDialogEvent

        );

      }

    }

  );

**Comment by pkkj** [comment]
Hi @skurian123 , I would like to confirm that the Dialog API is working correctly in your environment. Would you like to side load this very simple add-in to verify that: [Manifest](https://kepengtestapp.azurewebsites.net/manifest/AzureOutlook.xml). It's an app command so you can click "Show Taskpane" first, and then click "launchDialogSameOrigin" button in the taskpane.

One more small problem is that in your code, there is no need to put "await" before Office.context.ui.displayDialogAsync, since this function doesn't return any Promise.

![image](https://user-images.githubusercontent.com/7818153/138212299-62479077-d50a-4318-8f4b-9f5dfddc02d8.png)

**Comment by skurian123** [comment]
@pkkj - we are able to move a little and we could see the dialog popping up now, but when we implement the same codebase we could see a consent popup coming in the webmail but not in the outlook native app.

**Comment by pkkj** [comment]
@skurian123 would you like to share a screenshot for the popup in Outlook Online,? Thanks.
