### ISSUE TITLE
Unable to use responseType: 'blob' in XHR requests

### ISSUE THREAD

**Issue by barclayadam** [OfficeDev/office-js#2186]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Overview

Tying to use `responseType = 'blob'` on an HXR request in Outlook Event-Based Activation causes an error `Native module BlobModule is required for blob support`

## Your Environment

* Platform: PC
* Host: Outlook (EVent-Based Activation)
* Office version number: 2109 Build 14430.20270
* Operating System: Windows 10
 
## Expected behavior
To be able to load a remote resource using XHR as a blob (and to then read using a `FileReader`).

## Current behavior
An exception is thrown with the shape: `{ [Invariant Violation: Native module BlobModule is required for blob support] name: 'Invariant Violation', framesToPop: 1 }`

## Steps to reproduce
Run the below code in an event-based command:

function loadAsBase64(url: string): Promise<string> {
    return new Promise(function (resolve, reject) {
        try {
            const xhr = new XMLHttpRequest();

            xhr.onreadystatechange = function () {
                if (xhr.readyState !== 4) {
                    return;
                }

                if (xhr.status == 200) {
                    const reader = new FileReader();

                    reader.onloadend = function () {
                        resolve((reader.result as string).split(',')[1]);
                    };

                    reader.readAsDataURL(xhr.response);
                } else {
                    reject(new Error('Could not load image at ' + url));
                }
            };

            xhr.open('GET', url);
            xhr.responseType = 'blob';
            xhr.send();
        } catch (e) {
            reject(e);
        }
    });
}

## Context

We are trying to load images to embed them as attachments but want 2 things that the built in method taking a URL does not give us:

 - Better control over how errors are displayed, instead of as a "download failed" attachment being added
 - Better caching control of the images being loaded

**Comment by barisbikmaz** [comment]
I also ran into the problem. Within the runtime it is not possible to add a responseType to the request which makes it impossible to download an image. 

I tried it with fetch.blob(), fetch.arrayBuffer()=, xhr and setting responseTypes nothing worked.

Our use case is to download an image from SharePoint within the runtime.

On Outlook for Web everything works fine.

Would be really great if you could enable this.

**Comment by JunielKatarn** [comment]
`blob` type is not currently supported. I will communicate this to the corresponding component owners.

**Comment by exextoc** [comment]
Tracking project: https://github.com/microsoft/react-native-windows/issues/3178

**Comment by JunielKatarn** [comment]
FYI, `blob` support for Office JS has been deployed.
