### ISSUE TITLE
ItemId is null for appointment in edit view / Outlook "New Design" for Mac

### ISSUE THREAD

**Issue by lukesolar** [OfficeDev/office-js#2188]
When we try to get the itemId of any appointment in our calendar TaskPane, the itemId is null. This issue only happens on Outlook New Design **edit** view of an appointment. 

We cannot use getItemIdAsync() since that function is not available in the requirement set 1.7. 

Outlook: 16.48 (New Design: ON)
RequierementSet: 1.7 https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-1.7
Office.context.requirements.isSetSupported('Mailbox', '1.8'): false
Office.context.requirements.isSetSupported('Mailbox', '1.7'): true

The issue has also been reported during the Microsoft Add-in verification for Windows 10(Version 2109 Build 16.0.14430.20256) 64-bit.

## Expected Behavior
When in the edit view on an appointment, `Office.context.mailbox.item.itemId` should return the item id 
The same code in the read only view of the same appointment returns the itemId just fine!

## Current Behavior
Office.context.mailbox.item.itemId -> returns null
Office.context.mailbox.item.saveAsync -> returns undefined

## Steps to Reproduce, or Live Example
```
Office.onReady(function() {
    // Checks for the DOM to load using the jQuery ready function.
    $(document).ready(function () {

        console.log(Office.context.mailbox.item.itemId);
    });
});
```

Is the Add-in initialized and code wrapped? yes
```
Office.onReady(function() {
    $(document).ready(function () {
       // all code goes here
```

## Context
Users of Outlook Add-in with Outlook New Design cannot use our Add-in. 

## Your Environment
Outlook for Mac 16.48 (New Design: ON)
Most likely also for some cases on Windows - Windows 10(Version 2109 Build 16.0.14430.20256) 64-bit 

## Useful logs
Office.context.mailbox.item.itemId -> returns null
Office.context.mailbox.item.saveAsync -> returns undefined
Office.context.mailbox.item.getItemIdAsync -> not available in 1.7
Office.context.mailbox.item.setItemIdAsync -> not available in 1.7

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @lukesolar. Connecting you with @macOutlookExtensibility who may be able to help.

**Comment by exextoc** [comment]
@lukesolar As per the documentation `Office.context.mailbox.item.itemId` is not available in AppointmentCompose or MessageCompose objects. `itemId` is only available in AppointmentRead and MessageRead(for items which are already present on Exchange server). Refer: https://docs.microsoft.com/en-us/javascript/api/outlook/office.appointmentcompose?view=outlook-js-1.7
