### ISSUE TITLE
Microsoft 365 Version 2108: Build 14326.20508 -> R1C1 excel formula values cause range values setting error

### ISSUE THREAD

**Issue by jnSWPC** [OfficeDev/office-js#2189]
The dataset being bound to the excel table has R1C1 excel formula values. There was no error binding to the table and rendering in 2102 version or the recent 2109 version. However the Version  2108 throws an error.  Could you please look into this urgently since this appears to be the next Semi-Annual Enterprise release. 

The dataset sample:
![image](https://user-images.githubusercontent.com/22331494/137948809-d293751a-b3f3-43c9-a83e-76924206aae4.png)

The code snippet where it errors:
![image](https://user-images.githubusercontent.com/22331494/137948943-8f8dddfa-befc-4301-b68d-fb372557b832.png)

The error message during range value set:
![image](https://user-images.githubusercontent.com/22331494/137949263-4a46d220-340c-4359-9ce0-f0b9d5ed6d8d.png)

The UI with no data:
![image](https://user-images.githubusercontent.com/22331494/137949442-91e570fa-cc27-45f6-82ab-4d3047dcbd7b.png)

In 2102 or 2109.. Works fine with existing logic. No error setting range.. See below:
![image](https://user-images.githubusercontent.com/22331494/137949777-62cc20b6-6203-47c3-a95f-1a7777da4b92.png)

**Comment by gingerjia** [comment]
@jnSWPC, thanks very much for reporting the issue! Our fix for this issue has been check-in to July fork and planned to finish deployment at Nov, 9th.  So the issue won't impact SAC from with this fix. 
We will update the thread when the deployment to SAC Preview is done. 
And please let us know if any other further issues. Thanks again!

**Comment by amrjnarayan** [comment]
Hello.. Has the fix been released or is on track to release this week?

**Comment by yuc014** [comment]
Hi, @amrjnarayan @jnSWPC .
Our fix is already deployed to SAC Preview.
If you still see the issue, please let me know, I will keep follow up. Thank you.

**Comment by donlvMSFT** [comment]
I'd like to close this thread as the fix is released. Thanks for the discussion!
