### ISSUE TITLE
dialog.close() causes an error in the Office dialog API

### ISSUE THREAD

**Issue by irynakaban** [OfficeDev/office-js#2190]
Hello,
we found a problem with OfficeDialog API. When a user open dialog with option “displayInIframe: true” - the function dialog.close() doesn’t work and we can see error in console, but if we use the option “displayInIframe: false” - the function dialog.close() works.

## Expected Behavior
When dialog.close() is called, the dialog box should be closed.

## Current Behavior
When dialog.close() is called, the dialog box does not be closed.

## Steps to Reproduce, or Live Example
Link to video: [link](https://drive.google.com/file/d/1NeC4a5vOoCQmNMwrbrZOfGZYXkxYFfos/view?usp=sharing) (error is displayed in the console)
Link to code: [link](https://github.com/irynakaban/excel-shared-runtime-scenario)

## Context
This problem appeared on October 20 on the production version of our add-in. There was no such mistake before. Maybe this problem appeared with the Office API update.

## Environment
Platform: Office on the web
Host: Excel
Office version number: 16.0.14117.35903
Operating System: Mac OS Big Sur 11.6
Browser: Google Chrome

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @irynakaban. Connecting you with @lliu113 who may be able to help.

**Comment by iotataru** [comment]
The issue has been resolved.

**Comment by lliu113** [comment]
Closing bug as fixed
