### ISSUE TITLE
excel-web-16.00.js:26 Uncaught TypeError: Cannot set properties of undefined (setting 'targetOrigin') at OSF.DDA.WAC.Delegate.closeDialog

### ISSUE THREAD

**Issue by sachin161194** [OfficeDev/office-js#2191]
This functionality was working fine till yesterday ,But now getting error from Excel-web-16.00.js library suddenly & it is impacting our PRODUCTION & DEV & LOCAL Environment.

Issue Summary :-
On Office JS Online , while Login in our excel Add-in with our call-back authentication pop up.
After getting Successfully Authenticated also ,Dialog is not getting closed and we are getting error from excel-web-16.00.js library.

![image](https://user-images.githubusercontent.com/92863921/138097737-feeea375-de4d-400b-a395-bf367423814f.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______ Office on the web
* Host [Excel, Word, PowerPoint, etc.]: ______ Excel
* Office version number: ______ latest version (https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js)
* Operating System: ______ windows10/mac
* Browser (if using Office on the web): ______ Chrome /Firefox/Edge
 
## Expected behavior

From Office.JS Online,In Excel
On Successful login ,when we call Dialog.close() ,the dialog box needs to get closed and we will redirected to our Addin landing page(Data Loader Screen).

## Current behavior

Currently After Authentication on login, while Calling dialog.close() for closing Login Dialog pop up , we are getting some error from excel-web-16.00 library ,which was working fine earlier.

## Steps to reproduce

1. ______ Open Dialog from Add-in in Excel Online (In Office.js Online)
2. ______ Then close it Programmatically with calling dialog.close(); 
3. ______ It is not getting closed programmatically after calling above function also ,previously it was working fine.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

It is Impacting  PRODUCTION Live Application.

## Useful logs

- [*] Console errors
![image](https://user-images.githubusercontent.com/92863921/138099577-9fdddb27-dd5e-49d3-b58c-01387816026f.png)
![image](https://user-images.githubusercontent.com/92863921/138099724-d766e5b9-0b3c-4dbc-b89f-e715e6857830.png)
- [*] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @sachin161194 . We are taking a look to fix this.

**Comment by iotataru** [comment]
The issue has been resolved.
