### ISSUE TITLE
dialog.close from DialogApi does not work anymore in PowerPoint Online

### ISSUE THREAD

**Issue by nickdekesel** [OfficeDev/office-js#2192]
In PowerPoint Online when we are trying to close a dialog that was opened with the DialogApi the dialog is not closing and we are getting the following error.
`Uncaught TypeError: Cannot set properties of undefined (setting 'targetOrigin')
    at OSF.DDA.WAC.Delegate.closeDialog (powerpoint-web-16.00.js:26)
    at <computed> (powerpoint-web-16.00.js:26)
    at OSF.DialogHandler.value [as close] (powerpoint-web-16.00.js:26)`
This has worked fine before but recently started failing.

## Expected Behavior
We expect the dialog to close and not throw an error.

## Current Behavior
It throws an error as seen above eventhough the domain of the dialog and the app running in the taskpane are the same.

## Steps to Reproduce, or Live Example

* Steps to reproduce:
  1. Open a dialog from the task pane with DialogApi in an iframe
  2. Send a message to the parent from the dialog
  3. Close the dialog on receiving the message from the dialog

## Context
We open the dialog using an iframe.
The host in the taskpane is the same as in the dialog.
We are using the beta channel of office.js.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: Build 16.0.14610.40504
* Operating System: Windows
* Browser (if using Office Online): Chrome

## Useful logs

- [ ] Console errors
`Uncaught TypeError: Cannot set properties of undefined (setting 'targetOrigin')
    at OSF.DDA.WAC.Delegate.closeDialog (powerpoint-web-16.00.js:26)
    at <computed> (powerpoint-web-16.00.js:26)
    at OSF.DialogHandler.value [as close] (powerpoint-web-16.00.js:26)`

**Comment by errishab111195** [comment]
was there any verison upgrade done recently?

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @nickdekesel. We are working on fixing this issue.

**Comment by iotataru** [comment]
The issue has been resolved.

**Comment by lliu113** [comment]
Closing as bug is fixed
