### ISSUE TITLE
Excel: cannot conditionally expose custom functions despite conditionally calling CustomFunctions.associate

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#2193]
## Rationale

We have an add-in that provides Excel integration functionality for various kinds of products. Each type of product has a set of similarly named functions, which can total several dozens **product-specific** functions like "CURRENTUSERBALANCE", **per each product.** 

_(just for the record, we cannot meaningfully expose a universal function "CURRENTUSERBALANCE" for all products because the set of meaningful parameters for the function differs across the products that we support integration with)_

Since the functions for different products are named similarly (though with a prefix: e.g. P1.CURRENTUSERBALANCE, P2.CURRENTUSERBALANCE) we still don't want to pollute the IntelliSense with functions for irrelevant products, as most our clients use just one or two of the many that we support.

Thus, I would like to expose the functions only when in the add-in the user defines a product connection with the relevant type.

I implemented the logic to conditionally call `CustomFunctions.associate` for relevant product-specific subsets of custom functions only when the customer defines a product connection.

However, it seems that all functions from the metadata are exposed at once, regardless of whether the associated implementation is available or not.

## Your Environment

Reproduces on any environment, but I tested on Chrome / Excel Online latest
 
## Expected behavior

The function should not visible in the Intellisense unless it has an associated implementation.
Ability to dynamically plug / unplug the available custom functions exposed from the add-in.

In our legacy XLL add-in the functions are not visible unless we register them through the code.

## Current behavior

All custom functions from the metadata are exposed in the add-in regardless of whether we called `CustomFunctions.associate` for them.

## Steps to reproduce

* Create an simple add-in with one function in the metadata, e.g. `CONTOSOGETANSWER()`
* Important: use **manual** metadata JSON as opposed to a generator.
* In the functions file, delay `CustomFunctions.associate` call by 30 seconds
* Open the file and insert the add-in
* Observe that  `CONTOSOGETANSWER()` is immediately available despite it not being associated.

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @wh1t3cAt1k! Connecting you with @grangeryy who may be able to help.

**Comment by grangeryy** [comment]
@wh1t3cAt1k  Currently we don't support the capability for Custom Functions. I created a new feature to track in backlog:5514799.

**Comment by grangeryy** [comment]
@wh1t3cAt1k internally this ask is still tracking in our backlog. To make it more visible to people who have the same ask, we recommend you posting the requirement in [Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) (which is a new version of "UserVoice").

**Comment by wh1t3cAt1k** [comment]
@grangeryy could we please keep this open? This is important to us since we're exposing a function called TEXTSPLIT, and a function with the same name gets added by Microsoft in the new versions of Excel.

In our COM-based add-in, we can conditionally expose this function based on whether Excel supports the new function. In Office.js we can't.

**Comment by parched** [comment]
This is in the ideas forum [here](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/allow-code-in-custom-functions-add-in-to-limit-the-function-list/idi-p/3608176).

This is already implemented by `Excel.CustomFunctionManager` and the Script Lab add-in uses it. It's just not in the public API.

**Comment by wh1t3cAt1k** [comment]
This is a duplicate of https://github.com/OfficeDev/office-js/issues/3486
