### ISSUE TITLE
AddinServiceHandler.ashx getAddIns ResponseCode 6; What does ResponseCode 6 mean?

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#2194]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
What does Response Code 6 mean from the AddinServiceHandler.ashx api call? 

Customer has successfully centrally deployed our addin manifest.xml that has passed validation and set to all users within their M365 subscription for our addin. A M365 user of theirs then goes to online office.com Excel, and does an Insert->Office AddIns->'Admin Managed' and clicks the 'Refresh' button. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.0.0
* Operating System: Windows 10
* Browser (if using Office on the web): Edge
 
## Expected behavior

We have other customers and ourselves that see our addin in the 'Admin Managed' section of Office Add-ins, with a successful central deployment.

## Current behavior

Our addin is not listed under their 'Admin Managed' Office Add-ins section

The AddinServiceHandler.ashx getAddIns call response returns 'ResponseCode 6' 

Response:
{"RefreshToken":"0.AQcAHlE0aKNSK0mPpWZGC5sEuyXf42eKJiRDpVAN4cf5cocHAPY.AgABAAAAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P-GNTcgWmg60pBmdq_v-ofTSxI0ZdRSxtKQX4Opq2qFHar7sREDKbA1t_9MLUiSpNnInmUltFtP7Mo9i4KtetEXZB1UAQEOJ8hbjCMbdToXKHlSBCkqWaK_S4b782Be66ePL5uhOoncRwZSmg_Z0rXvYsWHQOqfVlm0wsIPMuWDqWWgPTKyQeYLqR2M6eXqwfJfUH6fxa7-9iHtmDR8xOFMvYSzK416bl5rr5lxGJwox2oHmNnti-pDfMz0P28fUFME8SNR7au_UOwq72cnNbQSOGDEVi5NTNpRGPMb8D9MpLqtnZk__gLXa2Oj4R3NTigp5bvwwHve1w2bpnm7ufO2CmDbxcnMyQye5H58fNjo5zAJPEKba5u47bwCMywXlQMyj3_0Sp_lG-TQ3GW6ZDkaole5DTjZNHZQNt_8aF5XsnCyZaTCRZdFzZHrYzEFHbPmVXxWjN8GVR6EChzNq7YDA7iTgEy_UlLtmWNGUq5M1SQn5eLxdzfGiaT6SD8WbuUJgPej3NuU6QtG4ZYNrgobh7xnA-1qqiL3BBjQHGvoZwO77tWA8td2A4Hiwcw4V19RYzauh3IpPgvyno0IZAanhmuB9vnoP364tNfqeT6ysNEE3yJTwERFLzjceH1lP5h635_3Db8dAt8VhrKBO0SWHqM8IQWGxFLbR9YN_1qCWdhxLmOKwelXHywXBkFc5Hjw6KEB-8KYS-EkDbVTI9YGa-lLHp09Axm57m1Y-K6om1B6N_xgnwf_4BjvMfGuZHsXMwjHZIv6R6mGOB8TujXSm2s27w1JquFf2UrTY4Q79LvCpoQWLFlfSVa5gtLX4aYni7R3VMoXZlO7BNiCd81E8X6-LiG3dsYOD9ju0TxPbj73JwafKyh0i7Nc-Xs4HN3QxlXnWUeZCoAm8klSwK-o_JJLA5qHpsEGsTP3rw0SpX2LtyT8iTqW3__dNsVrHH1MrxbTCeh7tcdQfytArEVNeJcWj4eKALYfpdKOejR7VlOKMMv0k7gHGYcpiJhY2WgYs-Wh85SymFFDHvXtEJDvic603furK1t0ibAhQZeiEDVy4E75ZAI7-Sicr1cDST-VOGvsukueidsTUGhRBW5M2m39v3I4tjc","ResponseCode":6,"TenantId":"6834511e-52a3-492b-8fa5-66460b9b04bb","UserId":"7f02bd5f-0055-401b-a978-b9571b05b276"}

## Steps to reproduce
No need for you to reproduce, we need to know what ResponseCode 6 means, so we can help resolve the issue with our customer.

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @TonyNSPF! Connecting you with @dingjin-ms who may be able to help.
