### ISSUE TITLE
New Footnotes API not providing 'body' or 'reference', but provides 'type'

### ISSUE THREAD

**Issue by sureshjoshi** [OfficeDev/office-js#2195]
I just saw that the [Word Preview has a Footnote/Endnote API](https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#footnotes) in Office Online, so I'm testing it out (knowing that it's not final, subject to change, draft, etc etc etc). However, I'm unable to even get a hello world example running - so I'm wondering if it's not yet implemented - or if I'm doing something wrong. Or if maybe I don't have access to the correct version?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.14618.41000
* Operating System: MacOS 11.6
* Browser (if using Office on the web): Chrome 95.0.4638.54
 
## Expected behavior

After creating some footnotes, running the attached code, I would expect to see a fully populated NoteItem for each footnote.

## Current behavior

The NoteItemCollection is the correct size, however, each NoteItem is simply populated with `{ type: "Footnote" }` and not the content of the footnote itself.

## Script Lab example

```
name: Footnotes
description: Testing out the Footnote API
host: WORD
api_set: {}
script:
  content: |
    $("#setup").click(() => tryCatch(setup));
    $("#run").click(() => tryCatch(run));

    async function setup() {
      await Word.run(async (context) => {
        const body = context.document.body;
        body.clear();
        body.getRange("Start").insertFootnote("My first ever footnote");
        await context.sync();
      });
    }

    async function run() {
      await Word.run(async (context) => {
        const footnotes = context.document.body.footnotes;
        footnotes.load();
        await context.sync();
        console.log(footnotes);

        // Trying to access data directly
        const footnote = footnotes.items[0];
        console.log(footnotes.items[0].type);
        console.log(footnotes.items[0].reference);
        console.log(footnotes.items[0].body);
        console.log(footnotes.items[0].doesntexist);
      });
    }

    /** Default helper for invoking an action and handling errors. */
    async function tryCatch(callback) {
      try {
        await callback();
      } catch (error) {
        // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
        console.error(error);
      }
    }
  language: typescript
template:
  content: |
    <button id="setup" class="ms-Button">
        <span class="ms-Button-label">Setup</span>
    </button>
    <button id="run" class="ms-Button">
        <span class="ms-Button-label">Run</span>
    </button>
  language: html
style:
  content: |-
    section.samples {
        margin-top: 20px;
    }

    section.samples .ms-Button, section.setup .ms-Button {
        display: block;
        margin-bottom: 5px;
        margin-left: 20px;
        min-width: 80px;
    }
  language: css
libraries: |
  https://appsforoffice.microsoft.com/lib/beta/hosted/office.js
  @types/office-js

  office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
  office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

  core-js@2.4.1/client/core.min.js
  @types/core-js

  jquery@3.1.1
  @types/jquery@3.3.1

```

## Context

Just testing out the new API for an application being developed (in order to replace a lot of nasty `insertOOXML`).

## Useful logs

![image](https://user-images.githubusercontent.com/3823045/138199266-643a9604-2a35-4970-b747-b0acf45ee610.png)

In the image above, in the ScriptLab console, the NoteItem object only contains a "Footnote" type and then two empty Objects. Note that this is the case, even when the footnote reference is attached to text or not.

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @sureshjoshi! Connecting you with @RuoyingLiang who may be able to help.

**Comment by JinghuiMS** [comment]
Thank you for using footnote API and asking your questions. In your scenario, we have got the body of footnote by calling footnotes.items[0].body, we can continue the following operation on the footnote body, such as footnotes.items[0].body.text. So we can get the text on the footnote body.

You can refer to this sample:
https://gist.github.com/JinghuiMS/4e5b7de8c5b5e93fefa6d04d69dc70e1

Feel free to let us know if you have any issues.

**Comment by sureshjoshi** [comment]
Thanks @JinghuiMS 

I did try digging in deeper to the object, but I didn't see anything - but maybe I mistyped something, as there are no TS types yet, and I didn't see the objects. 

But, based on what you've said, it sounds like it's just the toJSON or whatever emits it as a string that's causing my issues?

I'll test out again and report back!

**Comment by sureshjoshi** [comment]
Okay, looks like it's working now, as I'm able to retrieve text from the API.

```typescript
  await Word.run(async (context) => {
    const footnotes = context.document.body.footnotes;
    footnotes.load();
    await context.sync();
    console.log("Context.sync()");
    console.log("Footnotes: " + JSON.stringify(footnotes));
    
    const footnote = footnotes.items[0];
    console.log("Footnote Reference: " + JSON.stringify(footnote.reference));
    console.log("Footnote Type: " + footnote.type);
    console.log("Footnote Body: " + JSON.stringify(footnote.body));
    
    const footnoteBody = footnote.body;
    footnoteBody.load();
    await context.sync();
    console.log("Context.sync()");
    console.log("Footnote Body Text: " + footnoteBody.text);
  });
```

Console.log:

```
Context.sync()
Footnotes: {"items":[{"type":"Footnote"}]}
Footnote Reference: {}
Footnote Type: Footnote
Footnote Body: {}
Context.sync()
Footnote Body Text:  My first ever footnote
```

The need to `load()` and `context.sync()` twice is unfortunate while loading footnotes (one for the items, one for the body). 

But, that answers my question, thanks!

**Comment by sureshjoshi** [comment]
@JinghuiMS Is there any way to get an entire list of the footnotes without calling `context.sync()` on each footnote?

**Comment by JinghuiMS** [comment]
@sureshjoshi 
you can use 'context.document.body.footnotes' to get all footnotes of current body.

    async function getfnfrombody() {
      await Word.run(async (context) => {
        const body = context.document.body;
        const result = body.footnotes;
        result.load("length");
        await context.sync();
        console.log("The count of footnote in body:" + result.items.length);
      });
    }

**Comment by sureshjoshi** [comment]
Thanks @JinghuiMS - but I don't have access to all of their text's though. I found a workaround though an hour or so ago. Not perfect, but saves a LOT of time when iterating and reading through hundreds of footnotes.

Thanks for the quick response!

**Comment by JinghuiMS** [comment]
That's cool you found a way to unblock yourself.
