### ISSUE TITLE
How to make Outllook Addin appear on the Calendar Meeting ribbon?

### ISSUE THREAD

**Issue by jfoclpf** [OfficeDev/office-js#2199]
I am here around for hours reading the extensive MS documentation about Outllook addins. I could already create an addin and uploaded it to Outlook but it is only available when I open mail messages, and not Calendar Meetings. 

Nowhere I can find where I need to change the manifest XML such that the addin appears in the Meeting ribbon, like the Teems or Skype Addin

[![enter image description here][1]][1]

Which elements must I add to the manifest.xml, such that my Outllook Addin appears on the Calendar Meeting ribbon?

  [1]: https://i.stack.imgur.com/NLtmY.png

**Comment by exextoc** [comment]
Refer to (https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extensionpoint) to read about different extension points which are available on different surfaces in Outlook.
Specifically I think (https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extensionpoint#appointmentorganizercommandsurface) would be of interest for you. This extension point makes your addin visible on Appointment compose surface.

**Comment by jfoclpf** [comment]
Thanks, it is working
