### ISSUE TITLE
Need to use two clicks in document to make cursor active again after text insertion using add in

### ISSUE THREAD

**Issue by KirillSelyukov** [OfficeDev/office-js#22]
## Expected Behavior

I expect to use one click to get cursor  active

## Current Behavior
Need to make two clicks to make cursor active

## Steps to Reproduce, or Live Example
- Open word
- use blank document
- With add in using shared api method setselectionDataAsync() insert text
- click on the document to focus it
- click on the document one more time to get active cursor

## Your Environment
* Platform : PC
* Host : Word 15, Word 16
* Office version number: 2013, 2016
* Operating System: Win 10

**Comment by sumurthy** [comment]
Could you call a select() on a empty range (end of a range) to get around this issue?

**Comment by dmahugh** [comment]
Closing this old issue due to inactivity. Let us know if you feel it should be reopened.
