### ISSUE TITLE
getRange, given a named range, is returning a columnIndex that is not zero-based as expected but rather 1 based

### ISSUE THREAD

**Issue by cidev5** [OfficeDev/office-js#2200]
We've very recently started noticing our Excel add-in is not populating cells with data as we expect, and getting a "parameter out of range" error message.

I am not sure how I can have you reproduce the issue, but I am wondering if this is something known that is due to a recent change? This was working on our end until just recently.

In the screenshot below, when I set a breakpoint, the `const columnRange` is being given an object with a columnIndex that doesn't align with what I know to be the actual zero-based index of that column in the sheet, given the named range. Where it should be 11, I am getting the value 12.

Please let me know what next steps I can take to help in having this issue looked at.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2108 (Build 14326.20508)
* Operating System: Windows 10
* Browser (if using Office on the web): ______

## Useful logs
![out-of-range](https://user-images.githubusercontent.com/22505624/138356034-13858289-81ac-42fe-8f52-de4c5d4d4264.PNG)

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @cidev5! Connecting you with @dingjin-ms  who may be able to help.

**Comment by shaowan-msft** [comment]
Hi @cidev5  thanks for contacting us. Our team is already working on your issue. 
I can not reproduce your issue in my side. My Excel version is 14527.20216. Could you provide more information to help on investigation?
1. Could you print the columnRange address and tell what it is?
2. Could you import this gist and tell what is result in output window after run?https://gist.github.com/2020Mar/6a1b7aab0d5da2863dcbd10f4841b4be 

Thanks,
Shaoping

**Comment by cidev5** [comment]
Hi @shaowan-msft,

1. The columnRange address is `M:M` (is expected to be `L:L`)
2. the output from the gist is: 
    `The range address was "Sheet3!A1:D1".`
     `The range columnIndex was "0".`

**Comment by cidev5** [comment]
Hi, it seems the issue was with our template and the named ranges in question getting assigned to different columns somehow (it was altered).

**Comment by shaowan-msft** [comment]
Hi @cidev5, glad to know you find the issue with your template. Can you help mark this issue as resolved?
