### ISSUE TITLE
When you create a message by profile card, cannot retrieve recipients' DisplayName.

### ISSUE THREAD

**Issue by mayanagi** [OfficeDev/office-js#2201]
When you create a message by clicking an email address in the profile card like the picture below, add-ins cannot get recipient's DisplayName.

![image](https://user-images.githubusercontent.com/60973869/135213664-82385bc0-2940-4c81-85ec-c65a41a20fa1.png)

I assume that this behavior is by design.
That's because I understand add-in can get recipient's DisplayName from the name-resolved value in a message being composed. However, the recipient is NOT name-resolved when creating a message by clicking an email address in the profile card as below.

![image](https://user-images.githubusercontent.com/60973869/135214163-c4470ce1-4709-40ef-9a15-fcde1f3c6cb4.png)

ASK: Could you please add the notice like "You cannot retrieve DisplayName when creating a message by clicking an email address in the profile card" if this behavior is by design.

You can reproduce this behavior by following steps.
1. Create a sample add-in getting the recipient's DisplayName in a message being composed.
2. Create a new message by clicking an email address in the profile card.
3. DisplayName cannot be retrieved by the add-in.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ff885432-1d36-09cf-8f45-917a81801cc6
* Version Independent ID: 67e60dcf-4d6a-9915-536c-cd9bb35ba116
* Content: [Get or modify recipients in an Outlook add-in - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/get-set-or-add-recipients?source=docs)
* Content Source: [docs/outlook/get-set-or-add-recipients.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/get-set-or-add-recipients.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Can you advise if this behavior is by design? Thx.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Thanks for that update. After we've updated the documentation, I'll move this item to the office-js repo.

@mayanagi We're working on noting this in the documentation so look out for PRs soon.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
The docs have been updated with this info (see PR https://github.com/OfficeDev/office-js-docs-pr/pull/2998). Transferring to the product repo to track the fix.

**Comment by exextoc** [comment]
Thanks for your patience. We have updated the document. Kindly reopen the bug if you have any other queries.
