### ISSUE TITLE
setSignatureAsync on Mac Outlook

### ISSUE THREAD

**Issue by skerr4311** [OfficeDev/office-js#2202]
## Add-in for Mac
I am working on an add-in that uses setSignatureAsync.  I am using launch events to set the signature and It is working really well on outlook web and outlook windows. I have moved on to mac and noticed that launch events do not seem to work on mac. While running through some debugging steps I noticed that for mac:
1. body.setAsync - works on mac
2. subject.setAsync - works on mac
3. body.setSignatureAsync - does not work on mac

to help me debug the issue I wrote the following function:
```
function set_signature(str) {
  try {
    Office.context.mailbox.item.body.setSignatureAsync(
      str,

      {
        coercionType: Office.CoercionType.Html,
      },

      function (asyncResult) {
        if (asyncResult.status == Office.AsyncResultStatus.Failed) {
          Office.context.mailbox.item.body.setAsync(
            "<h4>set_signature - " + asyncResult.error.message + "</h4>",
            {
              coercionType: Office.CoercionType.Html,
            },

            function (asyncResult) {
              if (asyncResult.status == Office.AsyncResultStatus.Failed) {
                console.log("There was an error: " + asyncResult.error.message);
              } else {
                console.log("Success!!!");
              }
            }
          );
          console.log("There was an error: " + asyncResult.error.message);
        } else {
          Office.context.mailbox.item.body.setAsync(
            "<h4>set_signature - " + JSON.stringify(asyncResult) + "</h4>",
            {
              coercionType: Office.CoercionType.Html,
            },

            function (asyncResult) {
              if (asyncResult.status == Office.AsyncResultStatus.Failed) {
                console.log("There was an error: " + asyncResult.error.message);
              } else {
                console.log("Success!!!");
              }
            }
          );
          console.log("set_signature - " + JSON.stringify(asyncResult));
        }
      }
    );
  } catch (err) {
    Office.context.mailbox.item.body.setAsync(
      "<h4>try - catch - " + err + "</h4>",
      {
        coercionType: Office.CoercionType.Html,
      },

      function (asyncResult) {
        if (asyncResult.status == Office.AsyncResultStatus.Failed) {
          console.log("There was an error: " + asyncResult.error.message);
        } else {
          console.log("Success!!!");
        }
      }
    );
  }
}
```
and fired it manually in the taskpane and finally, I am getting an error message
```
set_signature - You don't have sufficient permissions for this action 
```
My work around for this would be to use body.setAsync but before i head down this path I would like to ask the questions: 
- has anyone ran into the 'permissions' issue and how did you solve it?
- has anyone managed to get launch events working on mac?

Thanks to anyone that has any insight or answers to the above questions.

**Comment by exextoc** [comment]
@skerr4311  Thanks for reporting this issue regarding `setSignatureAsync` api. It has been put on our backlog. We unfortunately have no timelines to share at this point. Internal Tracking Id MAC 5515082

**Comment by skerr4311** [comment]
Thanks for looking into this issue. While building a body.setAsync work around I have notice that Office.context.mailbox.item.getComposeTypeAsync throws the same error "You don't have sufficient permissions for this action" on Mac.

**Comment by exextoc** [comment]
It should be available in 1.10 api set which is currently in [Insiders](https://insider.office.com/en-us/join/mac).

**Comment by skerr4311** [comment]
> It should be available in 1.10 api set which is currently in [Insiders](https://insider.office.com/en-us/join/mac).

Hi @exextoc 
Sorry It has taken so long to get back to you. I have been working hard on the widows desktop part of this project. I took your advice, followed the link and have tested on mac using the 'Current Channel (Preview)' and 'Beta Channel' and both of them are still not allowing me to write to the signature.

I would also like to ask you, when will LaunchEvent support be available for Mac? I have the following set up and working on Windows Desktop:
`
<LaunchEvent Type="OnNewMessageCompose" FunctionName="onMessageComposeHandler"/>
<LaunchEvent Type="OnNewAppointmentOrganizer" FunctionName="onAppointmentComposeHandler"/>
`
but even in the Beta version on Mac this still does not work.

Thanks

**Comment by exextoc** [comment]
Is Launch Event and Signature API are still not working for you in latest version?? Can you please share the Outlook Mac Version on which you are trying Signature and LaunchEvent ?? Are you in Old UI or New UI of Outlook Mac?? LaunchEvent is in production now ,are you still not seeing it working??If you are still facing the issue ,can you please share the Logs with us(Help-->Collect Diagnostic)??

**Comment by skerr4311** [comment]
Hi @exextoc ,
Thanks for getting back to me. I will get that information to you withing the next few hours. My partner is currently using the Mac for work.

Thanks,

**Comment by skerr4311** [comment]
Hi @exextoc,
I have switched to the New UI of outlook on Mac and now the setSignature and LaunchEvents are both working perfectly. Thank you for taking the time to get back to me about this matter. I really appreciate your help!

Thanks,
