### ISSUE TITLE
Unexpected exfc_main notification appears when blocking email on send

### ISSUE THREAD

**Issue by edfowle** [OfficeDev/office-js#2203]
When blocking any email by implementing the onsend feature and calling `.completed({ allowEvent: false });`, an unexpected additional notification appears:
![image](https://user-images.githubusercontent.com/10868335/138451895-51398312-5374-41ff-98f9-f327e649d924.png)
This occurs in OWA but not in the O365 Outlook Windows application.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 
* Operating System: Windows 10 Pro (19043.1288)
* Browser (if using Office on the web): Google Chrome (95.0.4638.54)
 
## Expected behavior
Only expected notifications should appear

## Current behavior
An additional notification with the caption "exfc_main" appears

## Steps to reproduce
Reproducible using the Outlook-Add-in-On-Send sample project
https://github.com/OfficeDev/Outlook-Add-in-On-Send

## Context
Negative user experience as our users think some unknown issue has occurred with our add-in

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @edfowle! Connecting you with @exextoc who may be able to help.

**Comment by exextoc** [comment]
@edfowle Thanks for reporting this issue regarding block onSend. It has been put on our backlog. We unfortunately have no timelines to share at this point. Internal Tracking Id 2419285

**Comment by carlosb1504** [comment]
hi @exextoc & @isabela-dominguez - We are also experiencing this behaviour any time that our add-in prevents the onSend action in Outlook Web Access - our custom error message is replaced with the text 'exfc_main'. This represents a fairly major degradation of service for us, so would need this to be dealt with as a matter of urgency. With that in mind do you have any timescales available for a fix or can you suggest a channel for us to escalate this issue within MS? 

Many thanks

**Comment by edfowle** [comment]
Hi @exextoc, has there been any progress with this? or any timelines you can share? thanks

**Comment by exextoc** [comment]
Hey all,

We are working on a fix for this bug, and will inform you as soon as the fix is available.

**Comment by exextoc** [comment]
@edfowle Thanks for your patience. We have fixed the bug from our end. Can you please try it once and let us know your feedback?

**Comment by edfowle** [comment]
@exextoc looks good to me, thanks. I'll close this once our testers have taken a look

**Comment by edfowle** [comment]
confirmed fixed
