### ISSUE TITLE
Office.context.mailbox.item.to getAsync returning error code 5010 in Outlook 2016

### ISSUE THREAD

**Issue by nbreath** [OfficeDev/office-js#2204]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When using `Office.context.mailbox.item.to.getAsync`, `Office.context.mailbox.item.cc.getAsync` or `Office.context.mailbox.item.bcc.getAsync` in compose/edit mode the result for the callback has the error `code: 5010, message: "internal error"`. It only occurs in Office 2016 that is using Internet Explorer to render the add-in. In Office 2019 and 365 works just fine.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office 2016 (16.0.5197.1000) MSO (16.0.5215.1000) 64-bit, Office 2016 MSO (16.0.4266.1001) 64 bits
* Operating System: Windows 10
* Browser (if using Office on the web): n/a
 
## Expected behavior

Get the list of emails for each field.

## Current behavior

The getAsync methods callback result has an error code 5010 that isn't documented in the list of errors.

## Steps to reproduce

Use `Office.context.mailbox.item.to.getAsync` in Outlook compose/draft mode email or editing a calendar appointment.

## Link to live example(s)

n/a

# Provide additional details

n/a

## Context

I can't get the list of emails in this fields in Outlook 2016. Works fine for Outlook 2019 and 365 desktop and web.

## Useful logs

- [x] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Error:
`{code: 5010, name: "Internal error", message: "An internal error has ocurred"}`

I debugged a little and found the next. Not 100% sure is related but regarless I'm leaving it here:
```
window.OSF.DDA.OutlookAppOm._instance$p._throwOnMethodCallForInsufficientPermission$i$0(1,this._propertyName$p$0+".getAsync")
_permissionLevel$p$0

window._u.ExtensibilityStrings.l_ElevatedPermissionNeededForMethod_Text
```

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @nbreath! Connecting you with @exextoc who may be able to help.

**Comment by exextoc** [comment]
@nbreath Does this issue reproduce a 100% of the time on all emails or is it intermittent? Is this only on some emails?
The insufficient permission error may or may not be related.

**Comment by nbreath** [comment]
@exextoc 100% of the time, with any email or even if it's empty.

**Comment by exextoc** [comment]
We are looking into this issue further, and we will get back to this post with our findings soon.

**Comment by exextoc** [comment]
We were unable to repro the issue you are seeing. Does this issue repro for multiple users or a single user? Does it repro for multiple machines? Does it repro for all add-ins or just a single add-in?

**Comment by nbreath** [comment]
So we kind of fixed it. To anyone that is facing something similar in `Outlook 2016`, don't try to handle/convert the `getAsync callback` into `Promises`. Even if you added polyfills for promises for IE11.

It will work for `Outlook 2019` onwards but will raise the code 5010 in `Outlook 2016`.
