### ISSUE TITLE
After Disable Teams for Outlook add-in, the other online meeting service provider is also disappeared on android outlook

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#2205]
after follow this document to disable teams for outlook add-in: [Manage meeting policies in Teams](https://docs.microsoft.com/en-US/MicrosoftTeams/meeting-policies-in-teams?WT.mc_id=TeamsAdminCenterCSH#allow-the-outlook-add-in)

the other online meeting service provider which designed followed by this document is also disappeared: [Create an Outlook mobile add-in for an online-meeting provider](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting)

this only happened on android outlook, but IOS outlook version is worked fine.

**Comment by hello-chenchen** [comment]
Teams disappeared:
![image](https://user-images.githubusercontent.com/1878089/138647222-b9565c6f-3dfa-42d3-9623-037af927f90f.png)

**Comment by hello-chenchen** [comment]
But i have the other online meeting provider:
![image](https://user-images.githubusercontent.com/1878089/138647508-d9b83d4c-6e3d-4d65-9e11-61b13abc7f7f.png)

**Comment by exextoc** [comment]
This is to inform that a fix has already been made will the rollout will be complete by next week. Will keep you posted on this thread.

**Comment by exextoc** [comment]
@hello-chenchen We have fixed the bug and the fix is available in build 4.2142.0 or later. Kindly test it and let us know your feedback.
