### ISSUE TITLE
Get recurrence edit mode 

### ISSUE THREAD

**Issue by 3volutions** [OfficeDev/office-js#2207]
Hello

Is it possible somehow to get the edit mode for the appointment if it includes recurrence's? I searched the entire api documentation for the current office js (Version 1.10) but didn't find anything. Did i misss something?

![image](https://user-images.githubusercontent.com/28921672/138686401-c23d643c-10b0-4566-b1c7-119c8b846ffd.png)

**Comment by ElizabethSamuel-MSFT** [comment]
@3volutions Can you check if the following article is helpful?

[Get and set recurrence](https://docs.microsoft.com/office/dev/add-ins/outlook/get-and-set-recurrence)

Thanks.
