### ISSUE TITLE
Outlook: Desktop "a problem occurred while trying to reach this addin" in modal. 

### ISSUE THREAD

**Issue by cbishop-fv** [OfficeDev/office-js#2208]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows desktop 
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2109 Build 16.0.14430.20292
* Operating System: Windows 10 v 19043.1288
* Browser (if using Office on the web): N/A
 
## Expected behavior
The user should open the dialog modal and see the page.

![image](https://user-images.githubusercontent.com/56599161/138745479-b7daebd2-74fc-4c27-81e0-91fad322744c.png)

## Current behavior

The initial application loads correctly.
User clicks a button to open a dialog modal and the application crashes.   
The same users do not have the same issue when using office 360 web version only desktop crashes.  
This only happens for some users but not all.  
Problematic and successful users are often at the same office.  
The users are unable to right-click to open dev tools and thus there is no way to get further info from the console or network dev tools etc.   

![image (5)](https://user-images.githubusercontent.com/56599161/138744893-d1749077-53c5-4de2-aa32-11a2d3f76b8b.png)

## Steps to reproduce

1. Install Filevine office outlook add-in
2. open the adding and click Sign in
3. crash happens to some users but not all when the modal opens.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by atsopuronen** [comment]
The same issue with identical error message details plus a different message variant of ADD-IN ERROR has been reported also by multiple customers of ours, and also here: https://github.com/OfficeDev/office-js/issues/1620.

Something  is broken.

**Comment by exextoc** [comment]
It appears your add-in code in the dialog is not initializing properly.
Can you confirm that you are correctly invoking Office.onReady or Office.initialize in the dialog's JS file before running any code?

**Comment by cbishop-fv** [comment]
> It appears your add-in code in the dialog is not initializing properly. Can you confirm that you are correctly invoking Office.onReady or Office.initialize in the dialog's JS file before running any code?

I would think it would error for users on web and all users if this were the case. It also errors for users that it has worked for previously.

But I can also confirm we check for office before render.

``` if (Office) {
  Office.initialize = () => {
    isAppInitialized = true;

    render();
  };
} else {
  console.error('No `Office` global found.');
}

**Comment by cbishop-fv** [comment]
> It appears your add-in code in the dialog is not initializing properly. Can you confirm that you are correctly invoking Office.onReady or Office.initialize in the dialog's JS file before running any code?

In addition, the page that is rendered in the modal has no dependency on office.js at this point. it is our auth form.

**Comment by atsopuronen** [comment]
https://github.com/OfficeDev/office-js/issues/1620#issuecomment-951514281

> We observed the same issue today. We uninstalled the Microsoft Edge WebView2 Runtime 95.0.1020.30 then the issue was instantly fixed with a relaunch of the Outlook Add-in.
> See this thread for updates and workaround. MicrosoftEdge/WebView2Feedback#1860

**Comment by cbishop-fv** [comment]
We tracked this back to an issue with our AWS cloudfront settings and react routing. Why the 404 only caused some clients to crash and not others I am not sure. 

required fix was:
![image (6)](https://user-images.githubusercontent.com/56599161/139096142-1ddd5066-6994-44be-9ec4-a7d275291a94.png)
