### ISSUE TITLE
Outlook Office.context.mailbox.item.body.prependAsync will put content inside of table if body starts with a table

### ISSUE THREAD

**Issue by neville-jones** [OfficeDev/office-js#2209]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2109 (Build 14430.20306 Click-toRun); OOTW Current Channel
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
The prependAsync method should insert content prior to the existing body content.

## Current behavior
If a message body immediately begins with a table then prependAsync inserts the content inside of the table data rather than before the opening table element.

## Steps to reproduce

1. Create new message, add recipient, set subject to "Test"
2. Place cursor in body at very start of body, insert 2x3 table with some data in the table
3. Run Script Lab snippet to prepend body

## Link to live example(s)

[https://gist.github.com/neville-jones/f53b97fcf914d038f783d661743fd68d](url)

```
$("#run").click(prependBody);

function prependBody() {
  Office.context.mailbox.item.body.prependAsync(
    "<p>Hello World</p><p>&nbsp;</p>",
    { coercionType: Office.CoercionType.Html },
    prependBodyCallback
  );
}

function prependBodyCallback(asyncResult) {
  if (asyncResult.status == Office.AsyncResultStatus.Failed) {
    console.log("Failed prepending the body: " + asyncResult.error);
  }
}
```

## Context

Users when adding table data to a message do not expect extra text to be inserted inside the table.

## Useful logs

Before prepend
![image](https://user-images.githubusercontent.com/62081302/138810521-1ee360ee-8a7c-421c-b0ff-609e3cc475db.png)

After prepend
![image](https://user-images.githubusercontent.com/62081302/138810548-63788134-5bcd-4196-9868-fd48ca1187cf.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@neville-jones Thanks for reporting this issue. After careful consideration, our team has decided to not fix this issue in the short term. 
As a workaround, kindly insert a new line before calling Office.context.mailbox.item.body.prependAsync()

We recommend you to upvote or create a new [Tech Community](http://aka.ms/M365dev-suggestions) item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue we will re-activate as needed.
