### ISSUE TITLE
Loading error for office addin - sometime - error Office 365 has been configured to prevent individual acquisition of office store addins

### ISSUE THREAD

**Issue by shyambhiogade** [OfficeDev/office-js#221]
## Expected Behavior
Office add-in load should be successful as it works sometime and i am getting this error sometime

## Current Behavior
Sometime i am getting the error when office addin is trying to load from an integrated in an excel file. Somtime it works, please find the snapshot,

## Steps to Reproduce, or Live Example
https://stackoverflow.com/questions/51659002/loading-error-for-office-addin-sometime-error-office-365-has-been-configured

**Comment by ElizabethSamuel-MSFT** [comment]
@shyambhiogade Seems this may be related to how the tenant is configured. If that is not the case, let us know and we'll reopen this issue. Thanks.
