### ISSUE TITLE
The ContextMenuText and ContextMenuCell menus DO NOT WORK IN EXCEL (using preview channel). 

### ISSUE THREAD

**Issue by timmaffett** [OfficeDev/office-js#2210]
[Enter feedback here]
If the simplest example of ContextMenuText or ContextMenuCell are present in an manifest.xml for excel (current preview channel version as of Oct 25, 2021) the addin will not load and get an error.   (This bug has been present since at least Dec of 2020)
Exactly as described here:
   https://github.com/OfficeDev/office-js/issues/1560

that issue was erroneously closed by over eager employees trying to clear issues without resolving the underlying bug.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 46c4dafc-01a5-84c3-9cc0-dbc862a6c162
* Version Independent ID: 9d280f3c-be20-bd7f-0cee-bf39cb17e504
* Content: [OfficeMenu element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officemenu)
* Content Source: [docs/reference/manifest/officemenu.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/officemenu.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Thanks for your interest in Office Add-ins. We use the issues of this repo to track problems with the documentation. Since you believe you have encountered a bug, I will transfer this to the office-js repo.

**Comment by trigurl** [comment]
> [Enter feedback here] If the simplest example of ContextMenuText or ContextMenuCell are present in an manifest.xml for excel (current preview channel version as of Oct 25, 2021) the addin will not load and get an error. (This bug has been present since at least Dec of 2020) Exactly as described here: #1560
> 
> that issue was erroneously closed by over eager employees trying to clear issues without resolving the underlying bug.
> 
> #### Document Details
> ⚠ _Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking._
> 
> * ID: 46c4dafc-01a5-84c3-9cc0-dbc862a6c162
> * Version Independent ID: 9d280f3c-be20-bd7f-0cee-bf39cb17e504
> * Content: [OfficeMenu element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/officemenu)
> * Content Source: [docs/reference/manifest/officemenu.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/officemenu.md)
> * Product: **non-product-specific**
> * Technology: **add-ins**
> * GitHub Login: @o365devx
> * Microsoft Alias: **o365devx**

Hi, I'm sorry you are having trouble.  Here's a manifest I created with ContextMenuCell in Excel.  Can you give it a try, it's showing up for me when you right click on a cell at the bottom of the menu.

<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="TaskPaneApp">
  <Id>669a52a9-957a-4579-809f-df1a11a64752</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Microsoft</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Wikipedia in Context Menu"/>
  <Description DefaultValue="Wikipedia in Context Menu"/>
  <IconUrl DefaultValue="https://wikipedia.firstpartyapps.oaspapps.com/wikipedia/images/wikipedia_32x32.png" />
  <AppDomains>
    <AppDomain>AppDomain1</AppDomain>
    <AppDomain>AppDomain2</AppDomain>
    <AppDomain>AppDomain3</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Workbook"/>
  </Hosts>
  <DefaultSettings>
    <SourceLocation DefaultValue="https://wikipedia.firstpartyapps.oaspapps.com/wikipedia/wikipedia_dev.html" />
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>

  <VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Description resid="residToolTip" />
    <Requirements>
      <bt:Sets DefaultMinVersion="1.1">
        <bt:Set Name="Settings" />
      </bt:Sets>
    </Requirements>
    <Hosts>
      <Host xsi:type="Workbook">
        <DesktopFormFactor>
          <FunctionFile resid="residDesktopFuncUrl" />

          <ExtensionPoint xsi:type="ContextMenu">
            <OfficeMenu id="ContextMenuCell">
                <Control xsi:type="Menu" id="myMenuID">
                  <Label resid="residLabel" />
                  <Supertip>
                      <Title resid="residLabel" />
                      <Description resid="residToolTip" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="icon1_16x16" />
                    <bt:Image size="32" resid="icon1_32x32" />
                    <bt:Image size="80" resid="icon1_80x80" />
                  </Icon>
                  <Items>
                    <Item id="myMenuItemID">
                      <Label resid="residLabel2"/>
                      <Supertip>
                        <Title resid="residLabel2" />
                        <Description resid="residToolTip" />
                      </Supertip>
                      <Icon>
                        <bt:Image size="16" resid="icon1_16x16" />
                        <bt:Image size="32" resid="icon1_32x32" />
                        <bt:Image size="80" resid="icon1_80x80" />
                      </Icon>
                      <Action xsi:type="ShowTaskpane">
                        <SourceLocation resid="residUnitConverterUrl" />
                      </Action>
                    </Item>
                  </Items>
                </Control>
            </OfficeMenu>
         </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>
    <Resources>
      <bt:Images>
        <bt:Image id="icon1_16x16" DefaultValue="https://wikipedia.firstpartyapps.oaspapps.com/wikipedia/images/wikipedia_32x32.png">
        </bt:Image>
        <bt:Image id="icon1_32x32" DefaultValue="https://wikipedia.firstpartyapps.oaspapps.com/wikipedia/images/wikipedia_32x32.png">
        </bt:Image>
        <bt:Image id="icon1_80x80" DefaultValue="https://wikipedia.firstpartyapps.oaspapps.com/wikipedia/images/wikipedia_32x32.png">
        </bt:Image>
        <bt:Image id="icon2_32x32" DefaultValue="https://wikipedia.firstpartyapps.oaspapps.com/wikipedia/images/wikipedia_32x32.png">
        </bt:Image>
        <bt:Image id="icon3_32x32" DefaultValue="https://wikipedia.firstpartyapps.oaspapps.com/wikipedia/images/wikipedia_32x32.png">
        </bt:Image>
      </bt:Images>
      <bt:Urls>
        <bt:Url id="residDesktopFuncUrl" DefaultValue="https://wikipedia.firstpartyapps.oaspapps.com/wikipedia/wikipedia_dev.html">
        </bt:Url>
        <bt:Url id="residUnitConverterUrl" DefaultValue="https://wikipedia.firstpartyapps.oaspapps.com/wikipedia/wikipedia_dev.html">
        </bt:Url>
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="residLabel" DefaultValue="Wikipedia Menu">
        </bt:String>
        <bt:String id="residLabel2" DefaultValue="Wikipedia Button">
        </bt:String>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="residToolTip" DefaultValue="Wikipedia Tooltip">
        </bt:String>
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>

**Comment by trigurl** [comment]
I'm sorry you are having issues, here's a sample manifest with ContextMenuCell in Excel, can you give it a try?  Just rename the file with a .xml extension.   In this example, I created a submenu in the ContextMenuCell, then added one button to it.

**Comment by trigurl** [comment]
[ContextMenuOnMenuButton.log](https://github.com/OfficeDev/office-js/files/7464543/ContextMenuOnMenuButton.log)

**Comment by timmaffett** [comment]
Hi Angela,
   Thanks for the working example!  I was able to add this
<ExtensionPoint></ExtensionPoint> to my manifest and get a working
ContextMenu.  The reason why all the previous examples I had used didnt
work is that they were attempting to place a SINGLE (non-parent) menu item
onto the context menu.  I am still unable to get that working.
Is it possible that only parent menu items (with children menus defined
with <Items><Item></Items>) work ?

If it is possible to have add NON-parent menu item onto the context menu I
would love a working example.

(I had been using something based on this example, but it does not work)

<ExtensionPoint xsi:type="ContextMenu">
    <OfficeMenu id="ContextMenuText">
        <Control xsi:type="Button" id="Button1Id1">
            <Label resid="ContextMenuItem.Label" />
            <Supertip>
                <Title resid="ContextMenuItem.Label"/>
                <Description resid="ContextMenuItem.Tooltip"/>
            </Supertip>
            <Icon>
                <bt:Image size="16" resid="Icon.16x16"/>
                <bt:Image size="32" resid="Icon.32x32"/>
                <bt:Image size="80" resid="Icon.80x80"/>
            </Icon>
            <Action xsi:type="ExecuteFunction">
                <FunctionName>doStuff</FunctionName>
            </Action>
        </Control>
    </OfficeMenu>
</ExtensionPoint>


Thank you in advance for any more assistance you can provide!

-tim

**Comment by trigurl** [comment]
So we only support the following:
1) One submenu added to the ContextMenuText/Cell that contains buttons (this is the sample I provided earlier)
OR
2) Add buttons to ContextMenuText/Cell without being in a submenu.  For example this will add one button to the ContextMenuCell.

Note - if you take my previous sample manifest, replace the ExtensionPoint with this snippet instead you will see one button on the ContextMenuCell.  

          <ExtensionPoint xsi:type="ContextMenu">
          <OfficeMenu id="ContextMenuCell">
            <Control xsi:type="Button" id="ContextMenuButton1">
              <Label resid="residLabel2" />
              <Supertip>
                <Title resid="residLabel2" />
                <Description resid="residToolTip" />
              </Supertip>
              <Icon>
                <bt:Image size="16" resid="icon1_32x32" />
                <bt:Image size="32" resid="icon1_32x32" />
                <bt:Image size="80" resid="icon1_32x32" />
              </Icon>
              <Action xsi:type="ShowTaskpane">
                <TaskpaneId>MyTaskPaneID1</TaskpaneId>
                <SourceLocation resid="residUnitConverterUrl" />
              </Action>
            </Control>
          </OfficeMenu>
         </ExtensionPoint>

**Comment by timmaffett** [comment]
Hi Angela,
   Your single button example indeed works for me!!  The only difference
that I could see from my version that was causing the addin to fail to load
(below)

<ExtensionPoint xsi:type="ContextMenu">
            <OfficeMenu id="ContextMenuCell">
              <Control xsi:type="Button" id="ContextMenuButton1">
                <Label resid="MenuLabel" />
                <Supertip>
                  <Title resid="MenuLabel" />
                  <Description resid="MenuDescription" />
                </Supertip>
                <Icon>
                  <bt:Image size="16" resid="Icon.16x16" />
                  <bt:Image size="32" resid="Icon.32x32" />
                  <bt:Image size="80" resid="Icon.80x80" />
                </Icon>
                <Action xsi:type="ExecuteFunction">
                  <FunctionName>actionTestShared</FunctionName>
                </Action>
              </Control>
            </OfficeMenu>
          </ExtensionPoint>

  Was that I was using MenuLabel and MenuDescription as the resid's for
the<Label><Title> and <Description>   (these were properly declared in the
short string section)
When I made that change to you example it also caused the addin to fail to
load.
So! - I have gotten to the bottom of what was causing all my frustration in
the first place!  Apparently some resid names can cause problems... ?!

I have included the <bt:ShortStrings> section below:

        <bt:String id="MenuTitle" DefaultValue="Shared Runtime Test Title"/>
        <bt:String id="MenuLabel" DefaultValue="Shared Runtime Test Label"/>
        <bt:String id="MenuDescription" DefaultValue="Shared Runtime Test
Description"/>


thank you for all your help, have a great day!

-tim

**Comment by ElizabethSamuel-MSFT** [comment]
Looks like the issue author was unblocked so closing.
