### ISSUE TITLE
Office lib taking more than 1100 miliseconds to load in the ItemSend event

### ISSUE THREAD

**Issue by albeiroespitia** [OfficeDev/office-js#2212]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Mac, iOS, Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 20211018001.04
* Operating System: Windows, macOS, Linux
* Browser (if using Office on the web): Chrome, Firefox, Edge
 
## Expected behavior
The time it takes to load the Office library before calling the ItemSend event function should be less than 500 ms

## Current behavior
The call to the function in ItemSend event is taking around 1100 ms in desktop and around 700 ms in web, and this time is mostly the time it takes to the Office lib to be ready ( realized this calling Office.onReady function )

## Steps to reproduce

1. Create a new message
2. Put some timer in the ItemSend event function attached
3. Put a Office.onReady function with a timer in the callback outside the ItemSend event function to realize that this is taking most of the time

## Link to live example(s)
manifest.xml
```
<ExtensionPoint xsi:type="Events">
  <Event Type="ItemSend" FunctionExecution="synchronous FunctionName="onItemSendHandler" />
</ExtensionPoint>
```

index.ts
```
import type Command from '@sdk/commands/command';
import ItemSendCommand from '@sdk/commands/item-send';

Office.onReady(() => { // Just for testing purpose
  console.log(performance.now()) // Takes around 900 ms
});

type EventHandler = (event: Office.AddinCommands.Event) => Promise<void>;
declare global {
  interface Window {
    onItemSendHandler: EventHandler;
  }
}

type CommandClass = {
  new (event: Office.AddinCommands.Event): Command;
};

const handler = (Class: CommandClass): EventHandler => {
  console.log(performance.now()) // Takes around 100 ms
  return (event): Promise<void> => {
  console.log(performance.now()) // Takes around 1000 ms
    return new Class(event).run();
  };
};

window.onItemSendHandler = handler(ItemSendCommand);
```

## Context
How has this issue affected you? : The users are complaining the addin is taking too long to send the email, this 1 second thing is the only thing that we don't have control over. The extra time needed is very critical since it comes between hitting the send button and the email going out.

## Useful logs
Time it takes to link the handler to the window object in miliseconds
![Screenshot from 2021-10-27 14-55-56](https://user-images.githubusercontent.com/21091714/139137772-21a5b263-3688-46c0-9271-9a9399b7066c.png)

Time it takes to load the office library in miliseconds
![Screenshot from 2021-10-27 14-56-03](https://user-images.githubusercontent.com/21091714/139137723-1d88024d-d48e-46b9-b3b9-290b5b3e9da1.png)

Time it takes to call the ItemSend function atacched after the office library is fully loaded in miliseconds
![Screenshot from 2021-10-27 14-56-10](https://user-images.githubusercontent.com/21091714/139137790-1a7108da-7d13-4d30-9dea-c045161cc1a0.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Thanks for reporting this issue. We are aware of these performance issues, and we have work items in development and in the backlog that may improve this in the future. We unfortunately have no timelines to share at this point.

One thing to try would be loading office.js as the first script in your HTML, if you are not doing so already.
