### ISSUE TITLE
Office.auth... not recognized by typescript/intellisense

### ISSUE THREAD

**Issue by wilcotroost** [OfficeDev/office-js#2213]
I would like to use the method Office.auth.getAccessToken to create SSO for my TaskPad application for Outlook and Word. Using Vscode and Angular12 my intellisense and typescript compiler do not recognize 'auth' behind Office (Office.auth.getAccessToken). 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac and PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook and Word
* Office version number: ______
* Operating System: MacOS / Windows
* Browser (if using Office on the web): Safari / Edge / Chrome
*  
## Expected behavior
I would expect that this function is recognized by intellisense and typescript. 

## Current behavior
The function is not recognized resulting in an compile error. If I bypass strict type checking then the compile finishes but the code does not run. 

## Steps to reproduce
1. Create a Angular project for a Office AddIn 
2. Use Vscode to type Office.auth 
3. auth will be underlined as an error

## Context
I cannot use the function in my code which seems to be the only way to acquire a Office365 token. Msal2 works only in popup mode and this is refused in the desktop client.

**Comment by exextoc** [comment]
Office.auth.getAccessToken is enabled in the IntelliSense for TypeScript add-in projects by using the type definitions from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/office-js). I checked DefinitelyTyped and was able to verify that getAccessToken is defined. 

You can enable IntelliSense for a TypeScript project with these [instructions](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/referencing-the-javascript-api-for-office-library-from-its-cdn#enabling-intellisense-for-a-typescript-project).

For the implementation of Office.auth.getAccessToken(), the API still needs to be rolled out for Outlook. We will update this when the API has been rolled out.

**Comment by wilcotroost** [comment]
Thanks exetoc. I am using the DefenitelyTyped index.d.ts file according to the same instructions you mention. My intellisense/typescript does not allow me to use Office.auth(.getAccessToken). In this type definition file I can find getAccessToken as part of the Auth interface. But even Office.Auth is not accepted. Did you try this in Angular/Vscode yourself?

I didn't realize that the Auth interface was specific for the different applications. Maybe it would be a good idea to mention this in this [Microsoft announcement](https://devblogs.microsoft.com/microsoft365dev/announcing-general-availability-of-single-sign-on-sso-for-office-add-ins/) dated more then a year back.

**Comment by exextoc** [comment]
The announcement you referenced is for **OfficeRuntime**.auth.getAccessToken(), which is supported on W/X/P/O today and you can use it now. It is an equivalent to Office.auth.getAccessToken. You should use this API if you are working on multiple hosts since it works on all of them. Please note that in Outlook, this API is not supported if the add-in is loaded in an Outlook.com or Gmail mailbox.

The Office.auth interface is a new equivalent interface that will soon be supported on Outlook. It will receive any new API types moving forward.

For the intellisense, we are currently looking into the issue.

**Comment by wilcotroost** [comment]
After adding the @types/office-runtime typefile and putting "office-runtime" in my compiler options in tsconfig.app.json I managed to compile my code with OfficeRuntime.auth.getAccessToken(). 

Then I followed the instructions at https://docs.microsoft.com/en-us/office/dev/add-ins/develop/register-sso-add-in-aad-v2 and https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/sso-in-office-add-ins.md. 

If I run the code from online Outlook a request gets fired to microsoft with the following URL;

`https://ccs.login.microsoftonline.com/common/oauth2/authorize?response_type=token&client_id=<<myclientid>>&resource=api%3A%2F%2Flocalhost%3A3000%2F<my clientid>&redirect_uri=https%3A%2F%2Foutlook.office.com%2Fowa%2FextSSO.aspx&state=c917de2d-cc64-4b49-b320-f47687a0308c%7Capi%3A%2F%2Flocalhost%3A3000%2F89358f61-1197-45b6-a81f-e903ba6870b9&client-request-id=f5ecbc25-6035-445a-8847-78862de19377&x-client-SKU=Js&x-client-Ver=1.0.15&prompt=none&login_hint=<my username>%40<my domain>&domain_hint=<my domain>`

The server response from Microsoft is : 404 Not Found. 

If I run the code from online Word I don't see a http request but the Promise fails with a unexpected server error. 

Can anyone give me a push in the right direction?

@exextoc : is Office365 Outlook Web edition the same as outlook.com?

**Comment by exextoc** [comment]
Yes, Outlook web is the same as outlook.com

For the intellisense issue, we have identified the issue and are working on the fix. 

For the issue with SSO, we are reaching out to our partner team for more guidance.

**Comment by exextoc** [comment]
To clarify the last comment, are you using OWA with an outlook.com account?

**Comment by wilcotroost** [comment]
We are using the online version of Outlook as part of a paid Office365 business subscription. I presume that Outlook.com is the personal variant of this. Is this presumption incorrect? 

@exextoc Any news on the progress of the intellisense fix?

In my [github discussion](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29771) regarding this matter it is mentioned that this feature is still in preview. Is this correct?

The only thing we like to achieve is creating a app that runs with the already acquired authentication token in online and desktop versions of Outlook, Word and Excel. We did not find a way to reach this goal. Please help.

**Comment by wilcotroost** [comment]
Any news on this subject?

**Comment by exextoc** [comment]
For the intellisense fix, it should be live around January after the holidays. 
As for your question around the authentication token can you ask/open as a separate question/issue for better tracking? Meanwhile, this documentation might help provide some guidance: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins#using-the-sso-token-as-an-identity
