### ISSUE TITLE
Issue while retrieving date format data from a chart using getDimensionValues from Excel.ChartSeries class

### ISSUE THREAD

**Issue by krajdeepr** [OfficeDev/office-js#2214]
I generated a chart with date format ( M/D/YY ) data as category

Date | Volume ('000) | Closing Price
-- | -- | --
6/22/2020 | 1,383 | $121.07
6/19/2020 | 3,961 | $122.47
6/16/2020 | 1,466 | $125.15
6/15/2020 | 1,229 | $121.65
6/18/2020 | 697 | $124.16
6/17/2020 | 690 | $124.15
6/12/2020 | 1,195 | $121.91
6/11/2020 | 2,511 | $118.01
6/10/2020 | 1,326 | $129.87
6/9/2020 | 1,419 | $131.87
6/8/2020 | 1,555 | $135.75
6/5/2020 | 1,547 | $132.06
6/4/2020 | 995 | $128.89
6/3/2020 | 1,104 | $129.05
6/2/2020 | 814 | $126.00
6/1/2020 | 721 | $124.89

![start_month](https://user-images.githubusercontent.com/37655339/139199502-13b42c1e-12b2-40e7-8d50-6e0346d2932b.PNG)

In the chart seen in the image above, the dates on the X-axis are sorted in the ascending order. Then I retrieved chart data using 
1) getDimensionValues(Excel.ChartSeriesDimension.categories), output - I got the data in general format instead of date format and the order of the data was preserved ( not sorted as in the chart ).
[
    44004,
    44001,
    43998,
    43997,
    44000,
    43999,
    43994,
    43993,
    43992,
    43991,
    43990,
    43987,
    43986,
    43985,
    43984,
    43983
]

2) getDimensionValues(Excel.ChartSeriesDimension.values)), output - The data given is according to the sorted data of the categorical axis.
[
    [
        721.143,
        813.545,
        1104.294,
        995.342,
        1546.599,
        1555.116,
        1419.3,
        1326.19,
        2511.271,
        1194.595,
        1228.928,
        1466.31,
        689.75,
        696.935,
        3961.448,
        1383.133
    ],
    [
        124.89,
        126,
        129.05,
        128.89,
        132.06,
        135.75,
        131.87,
        129.87,
        118.01,
        121.91,
        121.65,
        125.15,
        124.15,
        124.16,
        122.47,
        121.07
    ]
]

Combining both the outputs,

 | Volume ('000) | Closing Price
-- | -- | --
6/22/2020 | 721 | 125
6/19/2020 | 814 | 126
6/16/2020 | 1,104 | 129
6/15/2020 | 995 | 129
6/18/2020 | 1,547 | 132
6/17/2020 | 1,555 | 136
6/12/2020 | 1,419 | 132
6/11/2020 | 1,326 | 130
6/10/2020 | 2,511 | 118
6/9/2020 | 1,195 | 122
6/8/2020 | 1,229 | 122
6/5/2020 | 1,466 | 125
6/4/2020 | 690 | 124
6/3/2020 | 697 | 124
6/2/2020 | 3,961 | 122
6/1/2020 | 1,383 | 121

We can observe that there is a clear mismatch of the retrieved data from the original data and if I generate a chart using this retrieved data obviously it would be different from the original chart.

![start_month_after](https://user-images.githubusercontent.com/37655339/139204896-f371e417-7b46-48c0-bbb6-ebdedb553f6f.PNG)

So how do you suggest I proceed on this issue and
FYI, The chart is not getting sorted when the date format is ( D/M/YY ) so no issues while retrieving the chart data.

![start_date](https://user-images.githubusercontent.com/37655339/139205276-9c8ee053-8b1e-40a9-8afa-3af4bd6e818d.PNG)

**Comment by chiz-ms** [comment]
Thank you for reporting this issue regarding `ChartSeries.getDimensionValues` API. ADO#5533223 is opened in our backlog to track this issue.

**Comment by chiz-ms** [comment]
We have fixed the issue and the fix is in the release process. We'll get back to this thread when it's publicly available.

**Comment by SiruiSun-MSFT** [comment]
Hi Krajdeepr, the fix has been released into production already. Thanks again for your reporting!

**Comment by donlvMSFT** [comment]
I'd like to close this thread as the fix already released. Thanks for the discussion!
