### ISSUE TITLE
Updating Footnote text with Footnote API has unexpected UI problems 

### ISSUE THREAD

**Issue by sureshjoshi** [OfficeDev/office-js#2217]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

While using the Footnote API to try to programmatically replace footnote text content, I'm seeing some "strange" behaviour using the `insertText` API with "Replace" and then `.clear()` + `.insertText("some content", "Start")`

I've attached a video showing the behaviour I'm seeing. Note that the final button "Clear/Update End" is the workaround for how I thought "Replace" would otherwise work.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.14622.41000
* Operating System: MacOS 12.0.1
* Browser (if using Office on the web): Chrome 95.0.4638.54
 
## Expected behavior

Footnote text content can be updated/replaced via the `.insertText("some content", "Replace") API.

## Current behavior

Using "Replace" causes the footnote number to be moved to the end of the footnote, which is incorrect.

Alternatively, using `.clear()` and then insert with "Start" wipes out the text entirely, and shows a flash of the inserted text before it disappears.

## Script Lab example

```
name: Updating footnote text
description: ''
host: WORD
api_set: {}
script:
  content: |
    $("#setup").click(() => tryCatch(setup));
    $("#updatestart").click(() => tryCatch(updateStart));
    $("#updatereplace").click(() => tryCatch(updateReplace));
    $("#updateend").click(() => tryCatch(updateEnd));

    async function setup() {
      await Word.run(async (context) => {
        context.document.body.clear();
        const p1 = context.document.body
          .insertParagraph("Placeholder text for the first footnote.", "Start")
          .getRange("End");
        p1.insertFootnote("First footnote content");
        await context.sync();
      });
    }

    async function updateReplace() {
      await Word.run(async (context) => {
        const footnotes = context.document.body.footnotes;
        footnotes.load();
        await context.sync();

        const footnote = footnotes.items[0];
        const footnoteBody = footnote.body;
        footnoteBody.load("text");
        await context.sync();

        footnoteBody.insertText("Replaced footnote content", "Replace");
        await context.sync();
      });
    }

    async function updateStart() {
      await Word.run(async (context) => {
        const footnotes = context.document.body.footnotes;
        footnotes.load();
        await context.sync();

        const footnote = footnotes.items[0];
        const footnoteBody = footnote.body;
        footnoteBody.load("text");
        await context.sync();

        footnoteBody.clear();
        footnoteBody.insertText("This is at the start.", "Start");
        await context.sync();
      });
    }

    async function updateEnd() {
      await Word.run(async (context) => {
        const footnotes = context.document.body.footnotes;
        footnotes.load();
        await context.sync();

        const footnote = footnotes.items[0];
        const footnoteBody = footnote.body;
        footnoteBody.load("text");
        await context.sync();

        footnoteBody.clear();
        footnoteBody.insertText("This is at the end.", "End");
        await context.sync();
      });
    }

    /** Default helper for invoking an action and handling errors. */
    async function tryCatch(callback) {
      try {
        await callback();
      } catch (error) {
        // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
        console.error(error);
      }
    }
  language: typescript
template:
  content: |
    <button id="setup" class="ms-Button">
        <span class="ms-Button-label">Setup</span>
    </button>
    <button id="updatereplace" class="ms-Button">
        <span class="ms-Button-label">Update Replace</span>
    </button>
    <button id="updatestart" class="ms-Button">
        <span class="ms-Button-label">Clear/Update Start</span>
    </button>
    <button id="updateend" class="ms-Button">
        <span class="ms-Button-label">Clear/Update End</span>
    </button>
  language: html
style:
  content: |-
    section.samples {
        margin-top: 20px;
    }

    section.samples .ms-Button, section.setup .ms-Button {
        display: block;
        margin-bottom: 5px;
        margin-left: 20px;
        min-width: 80px;
    }
  language: css
libraries: |
  https://appsforoffice.microsoft.com/lib/beta/hosted/office.js
  @types/office-js

  office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
  office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

  core-js@2.4.1/client/core.min.js
  @types/core-js

  jquery@3.1.1
  @types/jquery@3.3.1
```

## Context

Just testing out the new API for an application being developed (in order to replace a lot of nasty `insertOOXML`).

## Useful logs

Video of the problem:

https://user-images.githubusercontent.com/3823045/139363001-c2d5ada8-37bc-4e51-b27e-4a894ea75889.mov

**Comment by chiz-ms** [comment]
Thank you for reporting this issue regarding `Body.insertText` API in footnotes. The issue is confirmed and tracked as ADO#5539078 in our backlog.

**Comment by xiaoyuMS** [comment]
Hi, @sureshjoshi, thanks for your experience with these new apis
I have made a fix and it will be rolled out to production in several weeks.

**Comment by sureshjoshi** [comment]
@xiaoyuMS Thanks for the quick fix! 

Please let me know when the new Word/OfficeJS is released, and I can re-test

**Comment by xiaoyuMS** [comment]
Hi, @sureshjoshi 
Thanks for waiting. This fix has reached the production ring, please have a try~

**Comment by sureshjoshi** [comment]
Thanks @xiaoyuMS! 

I'll test it out in a couple of days.

**Comment by sureshjoshi** [comment]
@chiz-ms @xiaoyuMS  

Awesome, it works! Confirmed that using all of the buttons generate the same footnote content result.

Thanks!

**Comment by sureshjoshi** [comment]
@xiaoyuMS @chiz-ms 

Is there any timeline when footnotes will reach the Desktop versions of Word?

**Comment by xiaoyuMS** [comment]
@sureshjoshi 
We don't have a plan for Footnote APIs on Desktop at present. And we are collecting the customer requirements (better with MAU prediction) which will help us to see whether and when to plan these requirements.

**Comment by sureshjoshi** [comment]
Thanks @xiaoyuMS - if there is some way we could discuss privately, I could provide some context for our use case and maybe that would help?

**Comment by grangeryy** [comment]
@sureshjoshi, we'd love to have a more focused discussion on footnotes APIs. Pls leave the contact through the [SURVEY](https://forms.office.com/r/KqR29e5rPu) and we'll reach out soon :)

**Comment by PrashantShrimal** [comment]
@xiaoyuMS @chiz-ms
Is there any other way to add insert footnote functionality in word desktop add-in using office-js?

**Comment by sureshjoshi** [comment]
@grangeryy I haven't heard back regarding these APIs - I was wondering if the roadmap had changed at all?

**Comment by xiaoyuMS** [comment]
@PrashantShrimal 
Currently, you can try to insert footnotes by directly modifying the ooxml on Word desktop. I think @sureshjoshi may have some experience on that. We also provide some JS APIs to insert ooxml, such as [Body.insertOoxml()](https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#word-word-body-insertooxml-member(1)).

**Comment by xiaoyuMS** [comment]
Hi @sureshjoshi,
While I am not quite sure of the exact timeline, the good news is footnote/endnote APIs on desktop are already planned.

**Comment by sureshjoshi** [comment]
Thanks @xiaoyuMS - that's excellent news!
