### ISSUE TITLE
outlook calendar screen add-ins not opened ,it is showing error

### ISSUE THREAD

**Issue by Tamilarasan-ThiDiff** [OfficeDev/office-js#2218]
when i open outlook add-ins in calendar screen , some time this error came , add-ins not opend
<img width="1280" alt="Screen Shot 2021-10-29 at 12 54 38 PM" src="https://user-images.githubusercontent.com/90826888/139426111-dbdc730d-58e1-48ed-9fb2-b571779e680d.png">

**outlook-web-16.01.js:20 Uncaught TypeError: Cannot read properties of null (reading '_appName')
    at Object.d [as callback]** , 
any thoughts and suggestions about this issue please share me

Note :  add-ins developed by using javascript

[https://stackoverflow.com/questions/69765119/in-outlook-mail-calendar-screen-try-to-run-add-ins-error-shown
](url)

**Comment by exextoc** [comment]
Hey,

Hey, if your add-in has been hosted online, could you share the manifest with us so that we can test this out?

**Comment by pietrofxq** [comment]
I am having the same issue. Did you manage to fix it?

**Comment by pietrofxq** [comment]
For me this happens only when opening a popup directly from a command. Running the same function from the Taskpane works fine, even though both URL's opened in the popup are the same

![image](https://user-images.githubusercontent.com/6238029/156831200-1d7ba38d-d954-4aa0-94cb-b2b7133924e1.png)

**Comment by pietrofxq** [comment]
update: this is not happening when opening the popup with 
```
displayInIframe: true
````

**Comment by exextoc** [comment]
@pietrofxq Is your query resolved now?

**Comment by pietrofxq** [comment]
@exextoc I was able to make it work with `displayInIframe: true` and doing a post message from dialog to window. Opening the dialog directly from the function without `displayInIframe: true` still breaks the app with that error, maybe worth looking into why

**Comment by exextoc** [comment]
@pietrofxq ,

The Display Dialog should work with `displayInIframe: false`. Can you try adding a simple code snippet which displays the dialog from you add-in and try again, and then perhaps share the code snippet with us? (Share the code of the entire `ExecuteFunction` method that you're trying out)
