### ISSUE TITLE
Image disappears when replacing selected image with it's own ooxml

### ISSUE THREAD

**Issue by rvanlaak** [OfficeDev/office-js#222]
We are working on placing a comment on an image, but this is really hard as the only way to do this is by working with the OOXML.

We found the following bug; the image in a Word document disappears when replacing selected image with it's own ooxml.

## Expected Behavior

The image should not dissapear. For text (with formatting) replacing with it's own ooxml works okay.

## Current Behavior

The image disappears, and after hovering the image format it comes back.

## Steps to Reproduce, or Live Example

![replacing](https://user-images.githubusercontent.com/2707563/44078844-d7811f42-9fa7-11e8-871a-80e898bed985.gif)

Note: in the last part of the example we go to the image formatting ribbon. We don't actually click the style there, but solely hover it.

## Your Environment

* Platform: PC desktop
* Host: Word
* Office version number: Office 2016 build 1807
* Operating System: Windows 10
* Browser (if using Office Online): N/A

## Useful logs

https://gist.github.com/rvanlaak/1f06f8cc82d18d2e948110851522440d

**Comment by rvanlaak** [comment]
Another note; when running the code on a table (so, replacing the table OOXML with it's own OOXML), an error regularly pops up that the table was damaged.

![image](https://user-images.githubusercontent.com/2707563/44101943-dde07e50-9fe8-11e8-99c3-a3596b1324f5.png)

**Comment by rvanlaak** [comment]
Any update on this bug report?

**Comment by JuaneloJuanelo** [comment]
yes this is a bug. we are tracking internally with 3515089.
Alternatively, please use the 1.0 API setSelectedDataAsync, to replace the OOXML, that one works as you expect.

`   Office.context.document.setSelectedDataAsync(myOOXML, {coercionType:'ooxml'});`


btw here is a snippet you can try the workaround (uncomment the code :)) 
https://gist.github.com/JuaneloJuanelo/cdf7e583c3f8fe77760fc8ea70784f88

**Comment by JuaneloJuanelo** [comment]
@rvanlaak  the fix is in. Can you please try it?  its on the latest insiders fast release (aka 16.0.12126.20000).  I just tried it myself an its working but it will be really awesome if you can also confirm it. thanks!

**Comment by rvanlaak** [comment]
Thanks, will put it on my list to test, but will not be able to get to it this week.

A new feature release is coming? I found [`customxmlpart`](https://docs.microsoft.com/en-us/javascript/api/word/word.customxmlpart?view=word-js-preview) in `Word.Preview`. Will that allow replacing text selections with our own xml without Word adding a revision on it?

**Comment by JuaneloJuanelo** [comment]
@rvanlaak  thanks! 
please lets not mix content from different issues. customXML parts is releases since 2013. and yes you should have the APIs you need to get the XML part content and replace it anywhere you need.  please check our the documentation here:  https://docs.microsoft.com/en-us/javascript/api/office/office.customxmlpart?view=word-js-preview

also here is a relevant sample: https://github.com/OfficeDev/Word-Add-in-Work-with-custom-XML-parts



any insertion via API  will cause a revision. including XML. 
thanks!

**Comment by rvanlaak** [comment]
Yes, I hereby can confirm it works.

> any insertion via API will cause a revision. including XML.

Thank you for verifying that, as that actually is an issue for us. We replace the selected content with it's exact same content, but with a comment included. The above behavior causes a revision to get added on the selection where we don't want it to. But, that is whole other issue.

**Comment by JuaneloJuanelo** [comment]
awesome! thanks for checking. case closed!
