### ISSUE TITLE
Excel CustomFunctions automatically executed upon start of workbook

### ISSUE THREAD

**Issue by chanhohang** [OfficeDev/office-js#2220]
I follow the tutorial with my add-in and customfunctions sharing data.

https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial

When my workbook is saved with my CustomFunctions as a cells formula. The excel will execute the customfunctions and thus trigger connection to my add-in when the workbook is opened.

What we want to support to the user is we can disable the auto-connect of add-in from excel following the tutorial below

https://docs.microsoft.com/en-us/office/dev/add-ins/develop/run-code-on-document-open

`Office.addin.setStartupBehavior(Office.StartupBehavior.none)`

Is there any way to disable CustomFunctions from auto-executing on a saved workbook upon opened?

**Comment by xiaochunms** [comment]
@chanhohang sorry for the issue. Suppose calculation will be not triggered on workbook loading. But there are some exceptions, such as the result saved in workbook is not a final result but an intermediate one, such as #NAME, or the function is a streaming function. May you please share more details about the function? BTW, are you using online version or desktop version?

**Comment by chanhohang** [comment]
@xiaochunms 

Our function is a streaming function which is getting data from our websocket. and the excel runtime that we are testing with is Desktop office365 version.

**Comment by xiaochunms** [comment]
@chanhohang  Thanks for your information. Unfortunately formula calculation will be triggered on workbook loading if it is a streaming function. I don't quite understand well the logic that the function connects to add-in as the function can access the web via websocket in its logic.

**Comment by chanhohang** [comment]
@xiaochunms is there any way to mark a Streaming Function as non-executable until the related add-in is started/loaded?

**Comment by wh1t3cAt1k** [comment]
Related: https://github.com/OfficeDev/office-js/issues/2012

Our clients with large workbooks also experience inconvenience due to this behaviour, I suggest that there be implemented an add-in manifest switch that disables automatic recalculation of functions upon start-up.

**Comment by jiju-MS** [comment]
@chanhohang, currently it is not able to set streaming function as non-executable since it need to follow the excel calculation behavior.

**Comment by chiz-ms** [comment]
@chanhohang and @wh1t3cAt1k, if there's a feature request for "marking a Streaming Function as non-executable until the related add-in is started/loaded", please go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) and see if your feature has already been requested or request a new feature. Thanks.

**Comment by chanhohang** [comment]
@chiz-ms thank you so much for your suggestion, i have submitted the idea https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/office-365-excel-custom-function-streaming-function-should-not/idi-p/2995951#M485.
