### ISSUE TITLE
How to debug on Excel installed version

### ISSUE THREAD

**Issue by lordbenz** [OfficeDev/office-js#2221]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

**Task Pane APP**

I faced a problem after click the button on Ribbon and Function is open a new task pane but it does not working and my IEChooser can't see any task pane process on the Excel and in the foot of excel show message "my add-ins is working on your function" is there anyway to debug this? 

**Window10** 
Excel version 2102(Build 13801.21004)
Semi-Annual Enterprise Channel 

**Additional Information**
The problem that I faced will be solved after I restart and Current Channel version is working fine in the same machine.

![image](https://user-images.githubusercontent.com/28835449/140026258-6c416d1d-4a19-48ff-a18d-f4f1d6fcd24b.png)

**Comment by chiz-ms** [comment]
@millerds or @mattgeim, could you help to assign this issue to the correct owner? Thanks.

**Comment by millerds** [comment]
The message in the toolbar "Refinitive Add-in is working on your Sign In" looks like something about a specific add-in and not from Excel.

Newer webview technology used to render the taskpane is not going to work with IEChooser.  Instead you can use VS Code  (debugger tab) or you can use the attach debugger command from the taskpane menu to get the newer devtools.
