### ISSUE TITLE
Excel: returning large datasets from a custom function makes it infinitely stuck in #BUSY

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#2222]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **Excel Online**
* Host [Excel, Word, PowerPoint, etc.]: **Excel**
* Office version number: **latest**
* Operating System: Windows
* Browser (if using Office on the web): Google Chrome latest evergreen

## Current behavior

Functions returning relatively large datasets (~5000 rows, 20 columns) get infinitely stuck with #BUSY with no further indication.
 
## Expected behavior

**Short-term fix:** an explicit error message that "the custom function returned too many rows and the request timed out"
**Near-term fix:** large datasets returned successfully through payload batching in add-in-to-host API calls (if that's the root cause for the error?).

## Steps to reproduce

1. Use sample add-in https://github.com/VelixoSolutions/repro-too-many-rows-in-output
2. =CONTOSO.OUTPUT(1000) succeeds
3. =CONTOSO.OUTPUT(10000) will get stuck in #BUSY indefinitely (try a higher number if it's machine-specific)

You can observe in the debugger that the function assembles the dataset relatively quickly and returns it, the failure happens later. 

While it is not present in the minimal repro, in our live add-in I've seen HTTP 500 errors stemming, apparently, from the add-in trying to communicate the function result to the Excel host.

My best guess is that this payload needs to be batched.

## Business case / impact

The impact is 5/10, this hinders the migration from our legacy XLL product to the new cross-platform add-in.
The same custom function in legacy XLL add-in successfully supports large datasets.

**Comment by chiz-ms** [comment]
Thank you for reporting this issue regarding Custom Functions. ADO#5549594 is opened in our backlog to track this issue.

**Comment by gmichaud** [comment]
Hi @chiz-ms, is there any update on this issue? We have one potential client that has a Mac-only ecosystem and using our legacy XLL product is not an option for them.

**Comment by chiz-ms** [comment]
Hi @gmichaud, the team has been investigating this issue but so far we don't have anything to share yet. We'll come back to this thread once there's any update. Thanks.

**Comment by wh1t3cAt1k** [comment]
Good morning @chiz-ms ! 

Apologies for another ping - we're frequently being nudged by our clients about this limitation because there is no real workaround. We need to maintain function-level compatibility with our XLL product, and a certain function is frequently used to return relatively large datasets from the ERP.

I wanted to at least understand, if possible, if this bug is in the team's upcoming iteration plans, or not a priority yet?

We wanted to advertise our Office.js based product as "next generation cross platform product" and eventually encourage everyone to make a switch; but with limitations like this, for now it seems like there is a long ways to go towards feature parity with XLL, which impacts our product strategy. I dream of the day when the JS-based framework can be pushed to the same limits as XLL-based add-ins. 🚀

**Comment by jiju-MS** [comment]
Hi, wh1t3cAt1k, 
we are working on this issue and we'd like to know more details of your scenario, hope you can help with it.
1. As you mentioned, your scenario is about ERP and it need to return large datasets by Custom Function, could you tell us for common cases, what's the number of cells need to be returned? 
2. Seems you have XLL product already, so does win32&MAC have similar issue in your case? or the user actually use XLL on win32&MAC
3. If an explicit error message can be provided for such scenario, will it be helpful?

**Comment by wh1t3cAt1k** [comment]
Hi @jiju-MS . ( cc @chiz-ms @keyur32 ) 

1. Sometimes people will use our custom function to return the General Ledger transactions for a whole month. It is a single function that spills into a huge range. As such, it can return up to ~10k-100k lines, each with a dozen columns or so. Thus, it is realistic to expect something on the order of **~100k - 1 million cells returned from a single function**.

![telegram-cloud-photo-size-1-5050820371628010308-y](https://user-images.githubusercontent.com/5159662/147140007-6e05012e-290c-4632-89ed-ca1042d592e4.jpg)

In our common scenarios, people then do lookups, filters & sorts on the resulting spill range using Excel 365's dynamic array functions like SORT(), FILTER(), SUM() etc.

I want to emphasise that using dynamic arrays of this size is **practical and many of our clients do it on a daily basis using our XLL add-in!** Referencing it like `A1#` is **instant**. Doing UNIQUE() on it is under two seconds.

**2. The issue reproduces on any platform (Windows, Online, Mac) using Velixo's Office.js based add-in.**

Here's our story: we used to provide just an XLL-based add-in, which is for Windows & Excel Desktop only. As demand for cross-platform solutions, including Excel Online, started to appear, we invested a lot of effort into developing an Office.js-based add-in. 

Our ideal scenario from the maintenance perspective is **switching everyone to Office.js**, including Windows users - but due to limitations like this it proves difficult. 

This requires us to maintain two products at the moment, with a lot of duplicate logic. And one of this products (Office.js-based) never quite catches up in terms of performance, bugs, and limitations. 

We want to overcome this trend and make the office.js-based add-in our sole next-generation product and eventually switch everyone to using it.

3. Because many clients have both Macs and Windows, we need to maintain strict function-level compatibility between our old XLL-based add-in and the new Office.js-based add-in. 

**This means that an error message will not help us much in this scenario** - since people can retrieve 100 000-500 000 cells using our XLL product, they have an expectation that they will be able to do the same in our cross-platform add-in. 

Not being able to do this raises the strategic question: how can we make this our next generation universal product and how can we eventually drop our XLL add-in if it seems much more limited than what we are able to do with XLL?

**Conclusion**:  

Excel custom functions should support very large spilling ranges even on office.js platform just as they do with XLL... 

If this is a question of API call payload limitation when an add-in returns the result to the host, probably this needs to be done through "chunking" to support arbitrarily sized result sets.

**Comment by jiju-MS** [comment]
Thanks for the very details of your scenario which help us to understand more, we will continue dig into this issue.

**Comment by wh1t3cAt1k** [comment]
Hi @jiju-MS , please share any updates regarding this 🙏

**Comment by JHJ-MS** [comment]
Hi @wh1t3cAt1k, we are actively working on fixing it now, I'll update you when we have progress.

**Comment by wh1t3cAt1k** [comment]
Thanks a lot @JHJ-MS !

**Comment by RuizhiSunMS** [comment]
@wh1t3cAt1k , this ADO is numbered with id #5549594. We will inform you as soon as it is fixed.
Thanks.

**Comment by wh1t3cAt1k** [comment]
Hi @grangeryy @yaweizhu-henson @RuizhiSunMS , any update on this? Pretty critical issue for us and a dealbreaker for the customers.

**Comment by yaweizhu-henson** [comment]
hi @wh1t3cAt1k , sorry to keep you waiting this long. I just looked this id #5549594 up in our system, and it shows that this bug was fixed on Mar 21. Maybe it is in the process to be published to production? I'm not sure about that. I will try to contact with the engineer who fixed it and make sure what is really going on. I will comment here if I have anything update.

**Comment by JHJ-MS** [comment]
Thank you @yaweizhu-henson. 

Hi @wh1t3cAt1k, our finished fixing works on #5549594 is to remove the response payload limitation to fix the issue on Excel online that the functions return #BUSY when the functions count is large or the functions' parameter is large. 

For your issue, I tested a function that returns 10000 rows * 100 cols * 20 characters, it works fine on Win32 for me.
![image](https://user-images.githubusercontent.com/94002141/173851358-2562aac7-3c98-40a2-bf70-da4f1b7c55b5.png)

Could you please provide a repro example function using Script Lab Addin?

Thanks,
Haijia

**Comment by wh1t3cAt1k** [comment]
This is incredible. Half a million cells returned from one function and it's working successfully :) Thanks a lot!

**Comment by wh1t3cAt1k** [comment]
![image](https://user-images.githubusercontent.com/5159662/176537136-22ff06a4-65f6-4759-bd15-9b1846080293.png)

**Comment by wh1t3cAt1k** [comment]
@grangeryy @yaweizhu-henson @JHJ-MS one question for you guys: **does this need any update to the Excel host** or was the fix done completely on the Office.js side?

**Comment by JHJ-MS** [comment]
Great to hear that! It seems your issue's recovery is not related to our fix #5549594, our fix is only targeted at a CF **WAC** payload limitation issue. As far as I know, what your mentioned should work fine at the very beginning. So I think no need for any update. Thanks.
