### ISSUE TITLE
`Word.Range.expandTo` edits the undo stack

### ISSUE THREAD

**Issue by Theo-Evrard** [OfficeDev/office-js#2225]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
This issue is related to the `expandTo` method of the `Range` class from the `Word Javascript API`.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **Office on the web** (haven't been able to try it on PC Desktop)
* Host [Excel, Word, PowerPoint, etc.]: **Word**
* Office version number: **latest**
* Operating System: **Ubuntu**
* Browser (if using Office on the web): tested on **Opera and Chrome**
 
## Expected behavior

The `expandTo` method should return a new range that extends from two given ranges. I believe it should also not have any side effect on the `undo` stack.

## Current behavior

The method does return a new range that extends from the two given ranges.

But it also edit the `undo` stack. Once triggered, the `undo` stack seems to have get the expanded new range as an item in the `undo` stack.
To actually undo the last text edit from the document, I now need to `ctrl + z` (or click on the undo button) multiple times. 

## Steps to reproduce

1. Write some text in your document.
2. Run the following script lab: https://gist.github.com/Theo-Evrard/bfdfcb725f2a6d4ba62a643ae02affae
3. The document text should get printed in the console.
4. Click on the `undo` button of Office-Word. The `undo` should not behave as expected and should have not undo your text.
5. Click multiple time on the `undo` button. Now your text has been undone correctly.

## Context

We are trying to get the actual active selection range (start and end position in the document text). To achieve this, we are using the `expandTo` method with something like:
```typescript
void Word.run(async (context): Promise<void> => {
      const documentStartRange = context.document.body.getRange('Start')
      const selectionStartRange = context.document.getSelection().getRange('Start')
      const selectionRange = context.document.getSelection().load('text')
      const rangeBeforeSelection = selectionStartRange.expandTo(documentStartRange).load('text')

      await context.sync()

      const start = rangeBeforeSelection.text.length
      const end = start + selectionRange.text.length
    })
```

Thanks for any help you can provide with that issue.

**Comment by chiz-ms** [comment]
Thanks you for reporting this issue regarding `Range.expandTo` API. ADO#5549623 is opened in our backlog to track this issue.
