### ISSUE TITLE
Outlook - Mac 'Old UI' - changing 'From' address during composition breaks office.js functionality

### ISSUE THREAD

**Issue by carlosb1504** [OfficeDev/office-js#2227]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
Changing 'From' address during email composition should not stop calls to office.js APIs from being successful.

## Current Behavior

With the same add-in enabled on multiple accounts linked in a single instance of Outlook:

**in Windows Outlook / OWA / Mac 'New UI'**: User can successfully switch between multiple 'From' accounts, and the calls to Office.js APIs made by the add-in continue to work.

**in Mac 'Old UI'**: User switches to another 'From' account with the same add-in enabled, and various calls to office.js APIs break, with various error messages. See example below.

## Steps to Reproduce, or Live Example

1. Download attached office.js outlook task pane add-in. 
2. Enable the add-in on more than one account linked to the same instance of Outlook on Mac, in the Old UI.
3. Compose an email beginning in Account 1
4. Open the add-in task pane. Click 'Run', note that the activity is successful (in this case, setting, and then getting an internet header on the message, but this is an example and I have noted that multiple APIs do break. Another example is item.loadCustomPropertiesAsync().)
5. Switch to Account 2 by using the 'From' dropdown.
6. Open the task pane, Click 'Run' once more. Note that a general error is received.

As mentioned earlier, the above steps can be carried out in Mac new UI, Windows, OWA clients without issue.
[mac-from-address-switch-test.zip](https://github.com/OfficeDev/office-js/files/7474792/mac-from-address-switch-test.zip)

## Context

We require a consistent experience across Outlook clients, so that our add-in can function when the user switches to a different sending account during composition, which is a fairly common use case.

**Comment by carlosb1504** [comment]
any updates on this one please?

**Comment by liamtim** [comment]
Any updates here? It appears all Web add-ins become greyed out / disabled when switching to a delegate/shared mailbox on Outlook for Mac new UI.
