### ISSUE TITLE
Add or remove column in table with vertical text direction crashes

### ISSUE THREAD

**Issue by svdsande** [OfficeDev/office-js#2228]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2110 (build 14527.20234)
* Operating System: Windows 10 version 21H1
* Browser (if using Office on the web): Not applicable
 
## Expected behavior
After you just inserted an HTML table that has a cell with vertical text direction using the Office.js API you should be able to remove or add new columns without facing any errors.

## Current behavior
Removing or adding a column after you just inserted an HTML table that has a cell with vertical text direction using the Office.js API crashes.

## Steps to reproduce
1. Insert HTML table
2. Set one cell to vertical text
3. Add a new column using `table.addColumns(Word.InsertLocation.end, 1)` or `table.removeColumns()`
4. Force synchronization using `Context.sync()`
5. General exception is thrown 
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/8696909/140339816-f5480737-65d3-413b-aaf7-f0f1dbd83282.png)

## Link to live example(s)
1. [Please see gists](https://gist.github.com/svdsande/abbb7d9607a0ba588f91b4e5f765195a)

# Provide additional details

1. Please make sure that before you hit the sync button one cell has a vertical text direction. You should see the error message in the console after hitting the sync button.

## Context
The company I work for creates a Word plugin. This plugin provides HTML data to insert into a Word file.

The data that is inserted is collected on our website and can be updated or modified at any moment. So to ensure that the data stays updated we need to be able to synchronize the data within the word file.

The data can be in table format, and the amount of columns is quite high. Being able to set the headers of the columns creates space for our users. Without this option, our users will have a lot of unreadable tables or tables that take too much space and make the entire document unreadable.

## Useful logs
- [x] Console errors
- [x] Screenshots
- [x] Test file (if only happens on a particular file)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/8696909/140343217-56418d36-a54d-4b4a-a1a5-d1137caa9918.png)

**Comment by svdsande** [comment]
@AbidRahman-MSFT Is there something I can further clarify or something I can help you guys with?

**Comment by yihuax-msft** [comment]
I checked the code and found it's by design. When we operate on a table, such as adding a column or deleting a column, we require the table must be a "uniform" table.  In this scenario, if a cell has a different text direction, the table is no longer uniform and thus it fails.  If you must have a cell with different text direction, maybe you can fort perform all other operations, adding/deleting columns/rows, and then change the special cell's text direction? Thanks.

**Comment by svdsande** [comment]
I understand that implementation might benefit from requiring the use of a uniform table. Changing the text orientation once the operations such as adding and removing columns are done might solve the problem. However, I cannot imagine that it is intended to throw an expectation in the scenario that I build.

**Comment by yihuax-msft** [comment]
@svdsande , If we let the API fail quietly, not throw an exception, then, how can you know the API failed?
