### ISSUE TITLE
Office.onReady()

### ISSUE THREAD

**Issue by michahell** [OfficeDev/office-js#223]
Where, for the life of me, can I find the documentation regarding `Office.onReady()` ?
It seems to already be in the typings for OfficeJs (`@types/office-js`) since `0.0.83`, which was released a month ago.

**Comment by Rick-Kirkham** [comment]
We have a work item to doc this, but it's relatively new and we've been preoccupied working on an entirely new system for generating reference documentation. In the meantime, see Michael Zlatkovsky's comments in this issue: https://github.com/OfficeDev/office-js/issues/5

**Comment by JuaneloJuanelo** [comment]
@Rick-Kirkham  please add Work item ID.

**Comment by Rick-Kirkham** [comment]
https://office.visualstudio.com/OC/_workitems/edit/2446806

**Comment by JuaneloJuanelo** [comment]
tracking internally with 2446806

**Comment by Rick-Kirkham** [comment]
This is now documented in https://docs.microsoft.com/en-us/office/dev/add-ins/develop/understanding-the-javascript-api-for-office

**Comment by michahell** [comment]
great, thanks!

**Comment by michahell** [comment]
I think this issue can then be referenced and closed, too, no? 
https://github.com/OfficeDev/office-js-docs-pr/issues/282
