### ISSUE TITLE
Outlook for Android 4.2142.1 (42142810) will not load manifest with uppercase GUID in <id> tag

### ISSUE THREAD

**Issue by GrumpyAL** [OfficeDev/office-js#2230]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform: Android
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 4.2142.1 (42142810)
* Operating System: Android 12
* Browser (if using Office on the web): n/a
 
## Expected behavior
Manifest will load in Android if GUID is upper or lowercase.  However, this does specify that GUID should be uppercase:
https://docs.microsoft.com/en-us/windows/win32/msi/guid And the manifest XML documentation specifies that the ID is a guid.

## Current behavior
If a manifest contains a GUID that is uppercase, Android will not load the Add-in icon.  If that guid is changed to lowercase, it loads fine.

If lowercase is the expected format for the Id, I did not see that documented here (https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/id) nor does it seem to impact other clients so far.

## Steps to reproduce

1. Edit a manifest so the GUID is all uppercase
2. Sideload the manifest in OWA.  Note the icon shows correctly with other add-ins in OWA.
3. Open Outlook for Android and the icon will be missing.
4. Edit the manifest so the GUID is all lowercase
5. Remove the previous manifest in OWA and re-add with the new one.  Note the icon still shows correctly with other add-ins in OWA.
6. Close Outlook on Android (swipe the app away) and relaunch.
7. The icon should now show as expected.

## Link to live example(s)
Any manifest will work, can use one of the samples from this repo.

# Provide additional details
n/a

## Context
We have noticed the icon for our add-in disappearing from some of our Android users.  No impact seen on other Outlook clients yet.

## Useful logs
Unable to capture any logs

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@GrumpyAL Thanks for raising the issue. We are unable to reproduce the issue. Can you please share your manifest so that we can understand it better?

**Comment by GrumpyAL** [comment]
[sample.zip](https://github.com/OfficeDev/office-js/files/7499463/sample.zip)

Hello!  Here are two sample manifests.  These are slightly modified versions of the Token Viewer demo so that it shows up on mobile devices.  If I load both of these, I can see each one in OWA but only the lowercase one in Outlook for Android.

**Comment by exextoc** [comment]
@GrumpyAL Thanks for reporting this issue and we are able to repro the issue. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

Internal tracking id: Eg: Outlook Android: 5558959
