### ISSUE TITLE
The text "Bottom of Form" shows up when not wanted sometimes...

### ISSUE THREAD

**Issue by gitcnd** [OfficeDev/office-js#2232]
## Expected Behavior
MS-Word should not insert text we do not want.

## Current Behavior
If a &lt;form> element is present in HTML when inserted into an outlook email (when MS-Word is the editor), the unwanted text "Bottom of Form" is added to the email by MS-Word.

## Steps to Reproduce, or Live Example
Using outlook (the App, not OWA):
Office.context.mailbox.item.body.setAsync( "a &lt;form> here", { coercionType: "html" })

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook (using Word as the editor)
* Office version number: Current
* Operating System: Mac
* Browser (if using Office Online): Not online.

## Suggestion:
Find the source-code for MS-Word, and search for the string "Bottom of Form" - this issue looks to me like someone has accidentally left some testing/debugging output statements in the production code.  I've found other examples on the web of people with the same problem  (ins MS-Word, not Outlook) - and they are also seeing "Top of Form" show up unwanted too - finding and removing those test-lines from the production products would be a good idea.

**Comment by exextoc** [comment]
@gitcnd  Thanks for reporting this. We are unfortunately not able to reproduce the issue. Can you please share a small video of the bug to 'OutlookAddins@M365x693897.onmicrosoft.com'?

**Comment by gitcnd** [comment]
It's probably easier for you to search through your source code for the phrase "Bottom of Form" - which is the cause of the bug.

Alternatively, use script-lab or anything to insert some html that includes the tag <form> to see the bug show up.

Remember that a google search for this weird issue shows many other people having the same problem in other situations too, so fixing this here will also fix all the other problems it's causing elsewhere as well.

**Comment by exextoc** [comment]
@gitcnd I have tried to reproduce the issue in the latest version of Outlook and it is not reproducible. Could you please update the outlook to the latest version and try to reproduce it. Also, could you please share a video of it when it is reproducible?

**Comment by gitcnd** [comment]
Please fix this Bug ASAP.  You do not need any more feedback from anyone to find and fix this - search for the string "Bottom of Form" in the Office-product source code, and find the line of old debugging dev code that's been left in there which inserts this unwanted diagnostic text into our documents, and remove that line.

Here are a pile of other people's complaints about this same bug, stretching back SEVENTEEN YEARS.

https://www.pcreview.co.uk/threads/how-do-i-remove-the-words-top-of-form-and-bottom-of-form.2185320/

https://answers.microsoft.com/en-us/outlook_com/forum/all/when-i-paste-a-table-from-excel-to-outlook-the/527fc57f-e593-4d6a-adce-1796d5b94a51?auth=1

http://www.wordbanter.com/showthread.php?t=32323

https://www.msofficeforums.com/word/16783-documents-have-re-formatted.html

https://electroanswers.com/microsoft-office/how-do-i-get-rid-of-top-of-form-and-bottom-of-form-in-word/

http://www.office-archive.com/28-word/382196ec10e28329.htm

... and so on... there are literally thousands of people complaining about this same bug for two decades now.

**Comment by gitcnd** [comment]
Screencast of bug: https://autode.sk/3tqqEY8

**Comment by gitcnd** [comment]
Another screencast demo: https://autode.sk/3I1CdZP

**Comment by gitcnd** [comment]
Another demo - showing the bug with `<form>` and `</form>` at the same time:
https://autode.sk/33mkspo

**Comment by gitcnd** [comment]
Update - the above related to Mac Outlook.  I notice on Windows outlook, it inserts something different, but still unwanted - it looks like this:-

![Screen Shot 2022-01-14 at 5 52 42 pm](https://user-images.githubusercontent.com/4301826/149471422-193aa461-005e-4fa0-9e8a-672794251733.png)

(some weird graphic, followed by [] square brackets)

**Comment by exextoc** [comment]
@gitcnd Thanks for your repro video and we are able to reproduce it now. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

Internal tracking id: 2453187
