### ISSUE TITLE
Office add-in taskpane / dialogs open in default browser

### ISSUE THREAD

**Issue by tobiasviehweger** [OfficeDev/office-js#2233]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows 10
* Browser (if using Office on the web): IE WebView

![image](https://user-images.githubusercontent.com/2111803/140776961-c6180b70-6c07-4ba5-b440-13c9bc23df61.png)
 
## Expected behavior
Open the task pane

## Current behavior
We have a customer who is running into an odd error. When opening the add-in (task pane or dialog) via a ribbon command, the add-ins SourceLocation URL is opened in a browser window, outside of Office. This seems to mostly happen in their remote desktop environment, which points to some configuration setting. From what I got from the docs, this seems to be related to the AppDomain part of the manifest, though I understand this should never happen for the taskpane, since that is always included automatically? Is there any whitelist customization for SourceLocations that we should be aware of? Other add-ins inside Outlook (like MS Insight) open a taskpane correctly. 

## Steps to reproduce
Not possible to reproduce in our own env

**Comment by tobiasviehweger** [comment]
This is our manifest, as listed in AppSource: https://office365.yasoon.com/jira/manifest-store.xml

**Comment by exextoc** [comment]
Does this issue repro 100% of the time for the customer? If possible can you share a repro video or screenshot? Does this repro on any other platforms? (OWA, Mac?) 

It might also be worth checking if you are making any window.open calls in your code?

**Comment by tobiasviehweger** [comment]
Hi @exextoc,

- Happens 100% of the time in the virtualized environment (Citrix, RemoteDesktop, not exactly sure)
- Happens only on Windows (saw it working on OWA)
- It still uses the IE 11 webview, despite the newish Office version
- We do make some calls to window.open, but not at that early point. We have 3 ribbon commands, 2 use a ribbon functions file to call displayDialogAsync with our code, the third one uses ShowTaskPane. It happens for all three, even the ShowTaskPane one, which opens an empty task pane with a spinner and in addition the SourceLocation in the default browser - which kind of rules out our code, since it isn't even loaded at that point

My best guess is currently some kind of configuration issue, like Trusted Sites, Protected mode and app domains, but I'm not sure where to look exactly.

I'll send the customer to this thread to provide video/screenshots, do you have an email address where we can send that to, might contain sensitive info.

Thanks
Tobias

**Comment by exextoc** [comment]
The Office version is quite recent so this could have something to do with still using IE, we would recommend the customer to upgrade to WebView2 and see if the problem still persists. [Here ](https://docs.microsoft.com/en-us/deployoffice/webview2-install) is the link to our WebView2 documentation. It is also listed in our documentation [here ](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) for which browser should be used for what platform/version of office. Let us know if this problem still persists once upgraded.

**Comment by tobiasviehweger** [comment]
To be totally honest, I don't think thats the only factor.. The customer has shown me that it's working on their non-virtualized machines (other team), where the exact same version of Office is installed and IE is also used as a webview, and it's working on these machines.. Still trying to get hold on the video/screenshots - any possibility to share those privately?

**Comment by atsopuronen** [comment]
If I understood correctly, your Task pane is opening in a separate (default browser (window) instead of within Outlook window?

One of our customers had a similar problem, and it was caused by Zscaler's web app authentication. See below our internal notes about the case. I have replaced our domain details with "Contoso":

> Customer was running Zscaler proxy and authentication service. When user clicked our add-in, Task pane’s HTML content from (officejs.contoso.com) was loaded in user’s default browser.
> 
> Upon closer inspection, browser was briefly directed through gateway.zscaler.net, an web app authentication service. 
> 
> Our service is however not compatible with such service, as it doesn’t support authentication cookies.
> 
> Customer had to exempt contoso.com from cloud app authentication.
> https://help.zscaler.com/zia/exempting-urls-cloud-apps-authentication
> https://help.zscaler.com/zia/about-zscaler-cookies
> https://help.zscaler.com/zia/about-authentication-profile#authentication-frequency

We also had another similar case in our archives, although we never were able to determine the exact root cause. Nevertheless, here are our notes:

> Our add-in works before VPN is activated and while VPN is active. However, it breaks as soon as VPN is de-activated. 
> Computer reboot is required to fix add-in's functionality.
> 
> INITIAL ANALYSIS:
> This would indicate the VPN connection is making changes to DNS, firewall or proxy settings, but doesn't automatically revert those changes after VPN is disconnected.

**Comment by tobiasviehweger** [comment]
That is very good feedback @atsopuronen - thanks. It would make sense, since that probably breaks the AddDomains list, which validates the intercepted URL and then decides it needs to open this outside Outlook.

**Comment by exextoc** [comment]
@tobiasviehweger to share screenshots / videos privately with us, please create a private GitHub repo and @-mention exextoc so that we can access it.

Does the information from @atsopuronen help you here?

**Comment by ramjiyaniprajal** [comment]
how did you resolve the issue?
