### ISSUE TITLE
Add-ins not showing up on Outlook android app

### ISSUE THREAD

**Issue by s-pilkhwal** [OfficeDev/office-js#2236]
Similar to issue #676, addin is not showing on Outlook android v4.2142.2 but its showing up on v4.2141.0 

* Platform: Outlook for Android
* Host: Outlook
* Outlook app version number: v4.2142.2
 
## Expected behavior
Addin should load and show up along with other installed addins

## Current behavior
Apart from "Send to OneNote" addin, no other installed addin is loaded.

## Useful logs
- Already installed addins is loading on Outlook app v4.2141.0
- Already installed addins not loaded no Outlook app v4.2142.1
- unable to install addins from the "More Add-Ins" button, getting error saying "Failed to update status. Please try again."
- Already installed  addins not loaded on latest Outlook app v4.2142.2, able to install addin like "Report Phishing" using "More Add-Ins" button
- I have tried with Message Header Analyzer addin as well and its not showing as well

Test Button is the add-in I'm working on:
![Outlook apk v4 2141 0](https://user-images.githubusercontent.com/51193971/140892433-352d964f-7e61-4077-8941-9c2a0a8cdc5b.jpg)

![Outlook apk v4 2142 1](https://user-images.githubusercontent.com/51193971/140892454-c62febdd-5ceb-4dd0-be87-172baa8b3b85.jpg)

![Outlook apk v4 2142 2](https://user-images.githubusercontent.com/51193971/140892460-2ffa5670-8563-4a59-b1bb-bfc8acc5d4ba.png)

**Comment by exextoc** [comment]
@s-pilkhwal Thanks for reporting the issue. We are unable to reproduce it. 
Can you try installing add-ins other than Report Phishing and Message Header Analyser and let us know your feedback, please?

**Comment by s-pilkhwal** [comment]
@exextoc  I tried with Trello app and its loading up fine, any idea why "Message Header Analyzer" isn't loading up ? That might help me figure out whats wrong with my addin manifest. I have been using the "Test Button" addin since last 4+ years and recently after v4.2142.1 the addin stopped loading on Outlook Android.

**Comment by exextoc** [comment]
@s-pilkhwal  Thanks for the confirmation. "[Message Header Analyzer](https://appsource.microsoft.com/en-us/product/office/WA104005406?tab=DetailsAndSupport)" is currently not being supported in Android. 

And, we have been facing an issue with the Private add-in installation and we are currently working on it. Unfortunately, we don't have timelines to share now, but we will keep you posted once it's rolled out.

**Comment by s-pilkhwal** [comment]
@exextoc  any specific reason you guys have found on why private add-ins aren't working ? Is it something related to the Outlook for Android release as if I install v4.2141.0 my add-in is working as expected. Is there any why by which I can help you to get some more information on this issue ?
Is there an internal bug already added for this issue?

**Comment by exextoc** [comment]
@s-pilkhwal It is related to the latest Android release. We are already tracking this issue at Internal bug id: 5558959. We will update you once the fix is rolled out. Thanks for the support :)

**Comment by s-pilkhwal** [comment]
@exextoc  is this issue also observed on iPhone Devices ?

**Comment by exextoc** [comment]
@s-pilkhwal , No. We are not experiencing this issue in iOS.

**Comment by MattBeauceron** [comment]
@exextoc Any update on when a fix will be rolled out? We are also experiencing this issue with our Android users.

**Comment by exextoc** [comment]
This issue has been fixed and deployed from our side.
Please check with the latest build of Microsoft Outlook for Android, from the play store.

**Comment by s-pilkhwal** [comment]
I can confirm the private add-ins are now showing up and working as expected on Outlook for Android app v4.2145.1
