### ISSUE TITLE
Excel formatting cell color affects cell not in range

### ISSUE THREAD

**Issue by GregReddick** [OfficeDev/office-js#2237]
Changing the color of a range of cells affects a cell that is not in the range.

This one is really weird and kind of unexplainable. Formatting a set of cells to one color affects a cell that is outside the range of cells that was messed with. I have isolated the code down to just the parts of my code that show the problem.

## Your Environment
Windows Excel. Microsoft® Excel® for Microsoft 365 MSO (Version 2110 Build 16.0.14527.20234) 64-bit 
Windows 11
 
## Expected behavior
Changed the color of cells A6 through A11, but cell A13 changes color.

## Steps to reproduce

1. Create a new Excel Task Pane add-in using "Yo Office" using Typescript.
2. Replace the "run()" code in taskpane.ts with this code:
```
export async function run() {
  const colorBlue: string = "CCCCFF";
  try {
    await Excel.run(async (context) => {
      let wks: Excel.Worksheet = context.workbook.worksheets.add("Worksheet with formatting bug");
      wks.activate();

      wks.getRange("A6:A11").numberFormat = [["@"]];

      wks.getRange("A6:A11").format.fill.color = colorBlue;

      wks.getRange("A6").values = [["2:1.11"]];
      wks.getRange("A7").values = [["2.8:4.17"]];
      wks.getRange("A8").values = [["19:15.14"]];
      wks.getRange("A9").values = [["2.2:14.5"]];
      wks.getRange("A10").values = [["1.0:0.0"]];
      wks.getRange("A11").values = [["-7"]];

      wks.getRange("A13").values = [["This cell shouldn't change color"]];
      await context.sync();
    });
  } catch (error) {
    console.error(error);
  }
}
```

3. Start the app. Open the task pane, click run.

The result is that cell A13 changes to be blue.

**Comment by chiz-ms** [comment]
Thanks for reporting this issue regarding formatting APIs. The issue has been confirmed and tracked as ADO#5563249 in our backlog.

**Comment by dingjin-ms** [comment]
Hi @GregReddick , thank you for your report!
After some investigation, I found that this issue also repros when editing from UI, and I'm discussing the problem with UI team. Will let you know if we have progress.

**Comment by GregReddick** [comment]
Thank you. I wasn't seeing this outside of the JavaScript. My equivalent C# code driving Excel through COM didn't show the problem. However, it doesn't surprise me that this is an Excel bug. It is really odd.

**Comment by dingjin-ms** [comment]
Hi @GregReddick, after some investigations of Excel team, they think it's an autofill by design behavior. If you have further questions or concerns, please just let me know. Thank you very much!

As for the C# code you have mentioned, I'm not sure if it's using the same code path as Excel UI or Rich API so that it has a different behavior.

**Comment by GregReddick** [comment]
Really? By Design? I was able to reproduce it in the UI. If you change the color of 3 or more cells back color (doesn't happen with 2), say A6:A8, fill them with values, then change a value within 3 cells (doesn't happen with 4), say, A11, it changes the back color to match the above cells. They think this is by design? If so, I think they should revisit their design. This makes no sense from a UI perspective. It doesn't follow that that is anything that a user would want.

So not a JavaScript API bug, but I still think this is an Excel bug. It does not happen in the web version of Excel.

Thank you for following up on this. I know it's not a bug in your department, but can you add to the bug you submitted with UI that the user (me) thinks this is stupid design. I will be adding to my blog post at https://blog.xoc.net about this, as well as filing a separate bug though Excel.

**Comment by GregReddick** [comment]
It also doesn't happen through VBA. Here is some VBA code:
```
Public Sub ExcelBug()
    Sheet1.Range("A1:A3").Interior.Color = vbBlue
    Sheet1.Range("A1").Value = "a"
    Sheet1.Range("A2").Value = "b"
    Sheet1.Range("A3").Value = "c"
    Sheet1.Range("A5").Value = "d"
End Sub
```
If the code puts the value in cell A5, it doesn't change to blue. But if I put it in by hand (after the other code, commenting out the A5 line), it does. Oddly, if the code puts the value in A5, then I change the value, it doesn't change color. This just seems completely non-deterministic on when it will and won't change color from a user's perspective.

**Comment by dingjin-ms** [comment]
Hi @GregReddick , really sorry for the inconvenience! I will sync your feedback with UI team and double confirm about the behavior. Thank you very much!

**Comment by yuc014** [comment]
Hi @GregReddick, really sorry for the late reply.
As Excel Rich Api part, we need align with UI team. And the autofill behavior is designed as it at the beginning.
I fully understand your feeling, and we really want to make Rich Api better and better.
If this issue still block you, I recommend you request this as new feature on https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform. And then PM will reach you.
Really sorry for the inconvenience.

**Comment by GregReddick** [comment]
Okay, I'm going to put this in the stupid design department. Since I can work around it, I'm just going to close it.

**Comment by tofl** [comment]
I'll add (for those reading this who are stuck with a similar bug) that this doesn't only happen following the pattern @GregReddick described.

I'm working on an add-in that needs to change the style of lots of cells and in some cases the format styling is repeated to entire columns of data and not just when there's 3 cells in a row, I can't see any distinct pattern. Also, it doesn't happen to cells containing numbers and it's not just a problem with the back color, but also font weight and font color.

This is a very frustrating error, as I thought it was related to my code.
