### ISSUE TITLE
range.getHTML() returns wrong for footnotes and endnotes

### ISSUE THREAD

**Issue by AlexeyVanyukevich** [OfficeDev/office-js#2239]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I have an issue with my Word-office.js-Add-in, implemented with Angular.

When I call range.getHTML() in my macOS Big Sur & Word 16.54 setup the html contains wrong values for endnotes and footnotes as well. After I get all the content I need to edit it and put to the same range. Everything replaced fine, expect of endnotes and footnotes, if the endnote contains wrong value the footnote is removed.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.54
* Operating System: macOS Big Sur 11.4
 
## Expected behavior
when calling range.getHTML() endnotes and footnotes should have the correct value

## Steps to reproduce
1. Create document containing footnotes and endnotes
2. Create a new Word Task Pane add-in using "Yo Office" using Angular.
3. Use this code snippet to grab html
    `getHTML(startParagraphIndex: number, endParagraphIndex: number): Promise<string> {
        return Word.run(async context => {

            const paragraphs = context.document.body.paragraphs;
            paragraphs.load('empty');
            await context.sync();
            const contentParagraphs = paragraphs.items.slice(startParagraphIndex, endParagraphIndex);
            const range = contentParagraphs[0].getRange().expandTo(contentParagraphs[contentParagraphs.length - 1].getRange());
            const result = range.getHtml();
            await context.sync();
            return result.value;
   }`

## Useful logs
![Screenshot 2021-11-10 at 11 50 09](https://user-images.githubusercontent.com/42092238/141080678-194251fa-610c-4f0b-8d30-1d43200040b5.png)
![Screenshot 2021-11-10 at 11 50 30](https://user-images.githubusercontent.com/42092238/141080735-da70fa65-cbb5-4a49-a8a1-7b937e8d5984.png)

**Comment by chiz-ms** [comment]
Hi @AlekseyVanyukevich, thanks for reporting this issue. We are still working on reproducing this issue on our side. Could you help to provide the following information?
- Is this issue also observed with Word Online?
- When the issue is observed, what was the actual behavior vs. expected behavior? e.g. did you get an unexpected exception, or did you see some unexpected value? If it was some unexpected value, could you provide an example of the document content, the actual returned value and the expected value?

**Comment by AlekseyVanyukevich** [comment]
1. The issue only present on Mac.

**Comment by AlexeyVanyukevich** [comment]
1. The issue only present on Mac.
2. I get unexpected value for endnote/footnote character. I need the correct values so that I can update the document content from the taskpane later. Please try to get the html from 728 to 738 index using the code and file I've attached
[test.docx](https://github.com/OfficeDev/office-js/files/7568633/test.docx)
.

**Comment by chiz-ms** [comment]
Thanks for the additional information, @AlekseyVanyukevich. Transferring to @AbidRahman-MSFT since this issue is only on Mac.
