### ISSUE TITLE
insertHtml() in Word does not honor margin-left style in Office on the web

### ISSUE THREAD

**Issue by jonathanstokes** [OfficeDev/office-js#2240]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When `insertHtml()` includes a `<p style="margin-left: 40px">`, it appears indented as expected on Desktop Word, but does not get indented in the web version of Word. 

## Environment
* Platform: Office on the web (compared to Mac desktop)
* Host: Word
* Office version number: 16.0.14629.41001
* Operating System: MacOS 11.6.1
* Browser (if using Office on the web): Chrome 95.0.4638.69
 
## Expected behavior
On Word desktop, the paragraph is indented as expected:
![image](https://user-images.githubusercontent.com/7317544/141116280-a7f819be-cc24-4195-bec9-72c4cc5ff28d.png)

## Current behavior
But in Office on the web, the same paragraph gets no indentation:
![image](https://user-images.githubusercontent.com/7317544/141116444-5d3215ab-14eb-45c1-ac95-8d90846b6552.png)

It should be indented in the web version too.

## Steps to reproduce
Script Lab script used for both of the above screenshots:
```
async function addFormattedText() {
  await Word.run(async (context) => {
    await context.document
      .getSelection()
      .insertHtml(
        '<p>This is normal.</p><p style="margin-left:40px;">But this is a block quote indented line.</p><p>And this is normal again.</p>',
        "Replace"
      );
    await context.sync();
  });
}

addFormattedText();
```

## Link to live example
- [Script Lab Gist for the same script quoted above](https://gist.github.com/jonathanstokes/a5f0da24ccff61bb06b792ab2e8363dd)

## Context
In my specific case, I'm inserting snippets of HTML that come from an external WYSIWYG editor. The formatting allowed in this editor is very limited, but block indenting a paragraph is one of the changes allowed. Because of this bug, my Add-in behaves differently on different platforms.

**Comment by chiz-ms** [comment]
Thanks for reporting this issue regarding `Range.insertHtml` API. The issue is now tracked as ADO#5566492 in our backlog.
