### ISSUE TITLE
Cannot edit ContentControl tags in Word Online

### ISSUE THREAD

**Issue by ubabukos** [OfficeDev/office-js#2241]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
Currently unable to edit some content controls in Word Online. Attached is below is a sample document with a citation and the ScriptLab code to test against.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **web**
* Host [Excel, Word, PowerPoint, etc.]: **Word**
* Office version number: **N/A**
* Operating System: **MacOS**
* Browser (if using Office on the web): **Chrome**
 
## Expected behavior

Should be able to edit ContentControl tags

## Current behavior

Word throws the following error `RichApi.Error: The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information.`
Below is the output from the error debugInfo:
```javascript
{
  "code": "NotAllowed",
  "message": "The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information.",
  "errorLocation": "ContentControl.tag",
  "statement": "v.tag = ...;",
  "surroundingStatements": [
    "var v = context.root._getObjectByReferenceId(\"{64668738-6006-43a9-958a-6b318eb39e5a}{18}\");",
    "// >>>>>",
    "v.tag = ...;",
    "// <<<<<"
  ],
  "fullStatements": [
    "Please enable config.extendedErrorLogging to see full statements."
  ]
}
```

## Steps to reproduce

1. Open the attached document.
2. Paste the attached ScriptLab code into ScriptLab editor.
3. Place the cursor inside of the ContentControl within the document.
4. Press the "Run" button for ScriptLab to execute the code.

## Context

This functionality is the fundamental part of how our Word add-in works. 

## Useful logs

- [x] Console errors
- [ ] Screenshots
- [x] Test file (if only happens on a particular file)

* [Sovacool et al citation.docx](https://github.com/OfficeDev/office-js/files/7512815/Sovacool.et.al.citation.docx)
* [scriptLabCode.txt](https://github.com/OfficeDev/office-js/files/7512845/scriptLabCode.txt)

**Comment by els-ts** [comment]
@massonj @RuoyingLiang - this it not really a "product feature requests" but a "bug report".

In general this feature is available and works most of the time, however we've recently discovered that there are some ContentControls that throws this error when we try to modify them. We've managed to find the CC that is consistently throwing this error (at least for us) and now asking for investigation about what's so "special" in this element.

We have no issue modifying this with Word desktop applications and if I'm not mistaken it's failing also on other methods, for example `contentControl.insertText(...)` etc.

**Comment by chiz-ms** [comment]
Thanks for reporting this issue regarding `ContentControl.tag` API. The issue has been confirmed and tracked in our backlog as ADO#5579330.

**Comment by xiaoyuMS** [comment]
Hi @els-tsan you provide the process of how you created these uneditable CC ?

**Comment by xiaoyuMS** [comment]
Hi, @els-ts~
As you mentioned above, these CCs are "special".
Could you please share the process of how you created these uneditable CCs for further investgation?

**Comment by RuoyingLiang** [comment]
@els-ts , @ubabukos we found there is a hidden section in the content control paragraph, which may cause this unexpected behavior. We will do more investigation. Meanwhile, could share more information of why need the hidden section, is that auto generated?

**Comment by els-ts** [comment]
@xiaoyuMS @RuoyingLiang - to be honest we don't know. This is example we've received from our user and we have no idea how this ContentControl ended up in this state 😓  

I can only presume that our users have another add-in that somehow add this hidden section into our element (or there's some unknown Word functionality that does this), as this is something we not really expect to happen. As I've mentioned earlier most of the ContentControls our add-in is creating works fine and we've not intended to create this.

@RuoyingLiang - can you shed a bit more light about what the "hidden section" really mean? What does it contains? There's still little chance we doing it ourselves, but completely by accident.

**Comment by xiaoyuMS** [comment]
@els-ts @ubabukos, thanks for more details~

We did a further investgation to find that there is a shading on this CC(both on whole CC and inside text) which is not supported on Word Web right now. 
I have repro this CC by set the shading of a range including CC to Blue and set the paragraph in CC to no color. Then, it looks like a no color text but the shading of this range is blue which you can see in the xml. 

I tried two ways to mitigate this: open the document on Desktop, you can select a range(not paragraph) including the CC and set the shading to other color then back to no color, the other way is using the format painter to set this CC the same as other no shading range.

**Comment by els-ts** [comment]
@xiaoyuMS - thank you for the investigation 🏆 

Is there a way to clear this using an API? And maybe getting a better error message, so we can react to this error on behalf of our users? Or any other way we can programmatically find out what's the issue with the documents containing those CCs?

**Comment by xiaoyuMS** [comment]
@els-ts here is a workaround On Desktop to fix the CC in this doc( Sovacool et al citation.docx )

I created a custom style named "MyCustomStyle" (this can be created by UI operation) whose font is the same as the content in CC and used this style to fix this CC.
```
async function run() {
  await Word.run(async (context) => {
    const control = context.document.getSelection().parentContentControl;
    control.load("style");
    await context.sync();
    control.style = "MyCustomStyle"
    await context.sync();
  });
}
```
It is workable for this CC but may not solve all problems in your side. Hope it is helpful for you.

Thanks~

**Comment by els-ts** [comment]
@xiaoyuMS - (sorry for late reply) if I understand correctly there is no viable option to fix in on web? 🤔   If so, is there a way to at least detect it in Office Online?

**Comment by xiaoyuMS** [comment]
- Yes, the shading of paragraph is an unsupported feature so that we don't have any ways to remove this shading of the paragraph on web.
- It is not available at the moment, but we have a work item in backlog to improve these error messages.
