### ISSUE TITLE
Edge (Webview2) widens the dialog to fit the title

### ISSUE THREAD

**Issue by EdwinStraver** [OfficeDev/office-js#2242]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When opening a dialog using the JS API (Office.context.ui.displayDialogAsync) , and specifying the width and height, Edge (WebView2) seems to ignore the width, and widen the dialog, in order to fit the title (which includes the url, which is in itself already not desirable) This causes an ugly dialog to be displayed for us.

Is there a way to avoid this?

**Comment by ElizabethSamuel-MSFT** [comment]
@EdwinStraver Are you still facing this issue?

@massonj Can you assign to the appropriate person to take a look?

Thanks.

**Comment by EdwinStraver** [comment]
Hi Elizabeth, yes, we are still facing this issue.

**Comment by ElizabethSamuel-MSFT** [comment]
@EdwinStraver Thanks for letting us know.

**Comment by EdwinStraver** [comment]
@ElizabethSamuel-MSFT Do you know if some action will be taken on this? It has been a long time, and it is quite a nuisance for us.

**Comment by ElizabethSamuel-MSFT** [comment]
@EdwinStraver It would depend on what the team finds when they investigate.
