### ISSUE TITLE
Cannot delete content control manually using keyboard in browser version

### ISSUE THREAD

**Issue by libjosep** [OfficeDev/office-js#2243]
I am using `insertContentControl` function to insert a content control to current selection. I am also making it not editable by setting `cannotEdit = true`. If I select the whole paragraph where I insert this content control and press Backspace or Delete key on the keyboard, it is not deleting it. This happens only in the browser version.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Office 365
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

If I select the whole paragraph having the content control and press Delete/Backspace on the keyboard, it should delete the whole paragraph.

## Current behavior

If I select the whole paragraph having the content control and press Delete/Backspace on the keyboard, it is not deleting anything.
## Steps to reproduce

1. Insert a content control to a paragraph as shown in the attached screenshot. Make content control not editable by setting `cannotEdit = true`.
2. Select the paragraph containing the inserted content control and press delete key
## Link to live example(s)

1. https://gist.github.com/libjosep/5cda73e1fa044abbe2d5f2b04ea61af9

# Provide additional details

1. Add a paragraph to a blank document.
2. Place cursor between 2 words and click run button to insert content control.
3. Select the whole paragraph and press Delete

## Useful logs

- [x] Screenshots
![image](https://user-images.githubusercontent.com/28481997/141258475-a91e98c7-c27a-40f8-9061-a05848b0de5a.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by chiz-ms** [comment]
Thanks for reporting this issue regarding content control in Word Online. ADO#5567218 is created in our backlog to track this issue.

**Comment by RuoyingLiang** [comment]
Hi Chi,

Could you assign Word API related issue to the rotation contact in Word API fc? I don't have bandwidth to go through the issues and may delay the response...

Thanks
Ruoying

**Comment by RuoyingLiang** [comment]
Ruoying Liang would like to recall the message, "[OfficeDev/office-js] Cannot delete content control manually using keyboard in browser version (Issue #2243)".

**Comment by lukamaletin** [comment]
Thank you for your patience. The issue is now resolved and the fix is fully rolled out to production. Please verify it works as expected on your end, and let us know if you face any issues.
