### ISSUE TITLE
Inconsistent behavior between platforms when editing paragraphs with Word.Range

### ISSUE THREAD

**Issue by Fruch6807** [OfficeDev/office-js#2244]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
When a paragraph tracked by a `Word.Range` object is split in two, both of them should be associated with the same `Word.Range` object. Word on Mac and Windows behaves this way, while Word Online does not.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.54 (21101001)
* Operating System: MacOS
* Browser (if using Office on the web): Chrome 94.0.4606.81
 
## Expected behavior

When a paragraph tracked by a `Word.Range` object is split in two, both of them should be associated with the same `Word.Range` object.

## Current behavior

When a paragraph tracked by a `Word.Range` object is split in two, only the first of them is associated with the same `Word.Range` object.

## Steps to reproduce

1. Open a document with at least one paragraph.
2. Create a `Word.Range` object for the first paragraph.
3. Insert a line break in the first paragraph.
4. Call `select()` on the range object created earlier.

## Link to live example(s)

1. [Example in script lab](https://gist.github.com/Fruch6807/9403bde4e9788674e09971443b1213ac)

# Provide additional details

1. Open a document with at least one paragraph.
2. Run the exaple script attached below.
3. Click "Create range" button in the example script.
4. Insert a line break in the first paragraph.
5. Click "Select range" button in the example script.

## Useful logs

- [x] Screenshots

https://user-images.githubusercontent.com/24506031/141260120-8f7cfe23-d352-4ada-89a0-8999885eec38.mov

https://user-images.githubusercontent.com/24506031/141260140-c631d02a-e7bc-466c-8607-a62b51ea040e.mov

**Comment by chiz-ms** [comment]
Thanks for reporting this issue regarding `Word.Range` in Word Online. ADO#5567236 is opened in our backlog to track this issue.
