### ISSUE TITLE
Outlook on the web: Custom property returns value of the item in another folder

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#2245]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
For threaded mail, selecting the same message in another folder does not change the value of the custom property.

I think this issue occurs because the switching process is not working properly when the same email that exists in two folders is selected.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: Windows 10
* Browser (if using Office on the web): Version 95.0.1020.40 (Official build) (64-bit)

## Expected behavior

Returns the custom property values of the item in the selected folder

## Current behavior

Returns the custom property values of the item in another folder

## Steps to reproduce

1. Send an email to oneself
2. Select the received message in Inbox
3. Then select the same message in Sent Items

or

1. Add oneself to the mailing list
2. Send an email to the mailing list
3. Select the received message in Inbox
4. Then select the same message in Sent Items

In the video, a specific prefix is added for each folder.
- Inbox: "INBOX" prefix
- Sent Items: "SENT" prefix

https://user-images.githubusercontent.com/58804032/141263772-d93f6bf6-6a23-491e-84ad-863fbb6f21b6.mp4

## Context

We're using the On-Send feature to add custom property to the email.
The email will then go into the Sent Items folder, and depending on the user's operation, we may encounter this issue.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding the custom property. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.
Internal tracking id: Eg: Outlook Web: 134546
