### ISSUE TITLE
ScriptLab for Outlook Set Selected Text fails with error

### ISSUE THREAD

**Issue by Earthman55** [OfficeDev/office-js#2246]
Tried running Set Selected Text sample in ScriptLab for Outlook and experienced failure with message:
[ERROR]: [
    "Object doesn't support property or method 'setSelectedDataAsync'",
    "https://script-lab-runner.azureedge.net/",
    57,
    5,
    TypeError: Object doesn't support property or method 'setSelectedDataAsync'
]

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2016
* Operating System: WIndows 10 
* Browser (if using Office on the web): NA
 
## Expected behavior

Sample runs without error

## Current behavior

[ERROR]: [
    "Object doesn't support property or method 'setSelectedDataAsync'",
    "https://script-lab-runner.azureedge.net/",
    57,
    5,
    TypeError: Object doesn't support property or method 'setSelectedDataAsync'
]

## Steps to reproduce

1. Choose Code from ScriptLab in Outlook.
2. From Samples in main menu, choose "Set selected text" and view code.
3. Choose Run from ScriptLab in Outlook.
4. Click on "Replace Selected Text" button in taskpane, resulting in error.

## Link to live example(s)

1. Follow steps above
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

Trying to use setSelectedDataAsync in an add-in that I am building, and seeing problems with the function, so exercising function in ScriptLab to better understand function.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Can you also provide your office build number? Is the add-in using IE or WebView? But based on our documentation [here](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting#:~:text=Error%3A%20Object%20doesn%27t%20support%20property%20or%20method%20%27defineProperty%27), this could be the common error listed in the table. Please try the resolution to check for compatibility mode and let us know if the problem still persists

**Comment by Earthman55** [comment]
The office build number is: 16.0.14527.20234

 

I am not sure I know how to distinguish between IE or WebView – I am just using the “Script Lab for Outlook” browser panel that appears in Outlook when the add-in is run.

 

With regard to the link you provided:

*	Is the common error to which you refer “Error: Object doesn't support property or method 'defineProperty'”?          If so, there are no websites listed in the Compatibility View list, “Display intranet sites in Compatibility View” is unchecked, and “Use Microsoft compatibility lists” is checked.  Unchecking “Use Microsoft compatibility lists” has no effect.
*	The actions recommended under “Outlook add-in doesn't work correctly” also have no effect.

 

The error persists.  Note that this is a ScriptLab sample, so I have no control over what it is or where it is hosted.  I did get the SetSelectedDataAsynch working in another sample that I developed and running on localhost:3000.

 

Please let me know your thoughts.

Thanks… Lindsay

**Comment by exextoc** [comment]
`setSelectedDataAsync` is only available in compose mode. Can you confirm that you are not in Read mode?
Can you please share the snippet with us? Choose the "Share" menu within the snippet. Then share as a private [GitHub Gist](https://docs.github.com/en/github/writing-on-github/editing-and-sharing-content-with-gists/creating-gists) and grant us access.

**Comment by Earthman55** [comment]
As noted earlier, this is the ScriptLab sample code that is provided with ScriptLab, for which I expect the Add-in development team at Microsoft is responsible.  In any event, I had nothing to do with this code.

 

I did try the sample in compose mode and found that it did indeed work.  I also just noticed that the taskpane has a “Required Mode: Compose” statement, which was not obvious to me when I created the post.  

 

I should also note that the web page documenting setSelectedDataAsync at https://docs.microsoft.com/en-us/office/dev/add-ins/develop/read-and-write-data-to-the-active-selection-in-a-document-or-spreadsheet makes no mention of the compose mode limitation.

 

Thanks for your help…

**Comment by exextoc** [comment]
Just to clarify, is this issue resolved now? Can we close the github?

The documentation that you linked looks like it's for Word. Please refer to [this](https://docs.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-preview#setSelectedDataAsync_data__options__callback_) documentation for Outlook. You should see applicable modes under Remarks.

**Comment by Earthman55** [comment]
You may close this item.
