### ISSUE TITLE
Not getting all Office.js Word Document Styles

### ISSUE THREAD

**Issue by vimal-darji-ifour** [OfficeDev/office-js#2247]
Hello There, I am trying to get list of styles supported by Office Word Document, as mentioned in below image.
![image](https://user-images.githubusercontent.com/39907946/141472740-86486560-48e1-4619-8a5a-3d61919f59df.png)
To Retrive styles from Office.js I am getting below list.
![image](https://user-images.githubusercontent.com/39907946/141472765-30458fdb-c022-4748-a68c-ae4e3cd453cd.png)
Please help me to get all styles (in Office Word Document) with Office.js API.

**Comment by vimal-darji-ifour** [comment]
@AbidRahman-MSFT any update on this?

**Comment by AbidRahman-MSFT** [comment]
Hey @vimal-darji-ifour,

There is currently no way to fetch all available document styles from the Office JS API for Word. Word.Style will return the current style for each element in the document, it will not return all styles that are available to use. Word.Style is also an enum, so you are not able to set the style using this property. 

If you are looking for a way to fetch all available styles and/or set a certain style to the document without modifying the Ooxml directly, please post your feature suggestion here: [M365 Developer Platform - Microsoft Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/office%20add-ins%20development# )

**Comment by wangyun-microsoft** [comment]
This is in our plan and we don't have an ETA yet. I'll give an update once we have further progress on this. 

Thanks.

**Comment by wangyun-microsoft** [comment]
This should be available with our Word API 1.5 requirement set: https://learn.microsoft.com/en-us/javascript/api/requirement-sets/word/word-api-1-5-requirement-set?view=word-js-preview

@vimal-darji-ifour , Can you try retrieveStylesFromBase64 API to solve your problem?
