### ISSUE TITLE
Add-in loads in Excel web-version and Excel365 but not in Excel2019

### ISSUE THREAD

**Issue by Freymaurer** [OfficeDev/office-js#2249]
# Provide required information needed to triage your issue

I am currently trying to set up a minimal example template for an Excel web add-in ([this one](https://github.com/Freymaurer/SAFE-MinExcel)). It is based on the F# [SAFE stack](https://safe-stack.github.io) and parses client side f# code to js with [Fable](https://fable.io). To the problem i have: The add-in works perfectly fine for Excel365 and the Office on the web, but will not open in Excel 2019.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop and Office on the web.
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft Excel 2019 MSO (16.0.10379.20043) 64-bit
* Operating System: Windows
* Browser (if using Office on the web): Opera, Edge
 
## Expected behavior
I found the [Support for ie 11](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11) docs relevant for Excel 2019 and added bable translation to my webpack, so i expected it to work for Excel 2019.

## Current behavior
Instead when i open the add-in (sideloading via shared network with myself), the add-in window stays white and the F12 developer tools show me the following:
![image](https://user-images.githubusercontent.com/39732517/141490306-f96446ef-661b-4c8d-8d77-f731407da593.png)

If you need additional information about this pls tell me!

## Steps to reproduce
1. Download repo and follow install instructions [here](https://github.com/Freymaurer/SAFE-MinExcel#install-pre-requisites).
2. Run the web-app and sideload the manifest.xml via shared network.
3. Open the add-in in Excel 2019.

**Comment by Freymaurer** [comment]
Hey @croicu if you need any additional info pls tell me! Getting this to work is important to me and i'd like to help as much as possible.

**Comment by Freymaurer** [comment]
Hey @zacfarnsworth can i do anything to help with this issue? This is of high priority for me and i would really like to help get this done faster.

**Comment by zacfarnsworth** [comment]
Sorry about the delay on this, I am currently trying to install a build of Excel 2019 and will look into this.

**Comment by Freymaurer** [comment]
I actually think i found the problem. I tried to open the web app on IE 11 and it didn't work. I guess my "bable translation to my webpack" how i called it in the post above does not work correctly.

**Comment by zacfarnsworth** [comment]
Yes I was actually just about to comment that I’m pretty positive it has to
do with the fact that Excel 2019 still uses IE11 for it’s WebView control
for add-ins, and the issue likely stems from how the code is being
translated to JavaScript ES5.

**Comment by Freymaurer** [comment]
Yes i worked on this for the last few days and finally got it running. The problem came from the update to webpack5 in combination with some other dependency updates. The minimal example repo i linked in my first answer works now. If anyone finds this issue i will describe the core changes i needed to do:

- add `target: ["web", "es5"],`  to webpacks `module.exports`
- Use `babel-loader` with polyfills and core-js 3

```js
var CONFIG = {
    babel: {
        presets: [
            ['@babel/preset-env', {
                modules: false,
                // This adds polyfills when needed. Requires core-js dependency.
                // See https://babeljs.io/docs/en/babel-preset-env#usebuiltins
                // Note that you still need to add custom polyfills if necessary (e.g. whatwg-fetch)
                useBuiltIns: 'usage',
                corejs: 3
            }]
        ],
    }
}

module.exports = {
    module: {
        rules: [
            {
                test: /\.m?js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader',
                    options: CONFIG.babel
                },
            },
    }
};
```

- `package.json` needs:

```json
"devDependencies": {
        "@babel/core": "^7.16.0",
        "@babel/preset-env": "^7.16.0",
        "babel-loader": "^8.2.3",
        "core-js": "^3.19.2",
        "webpack": "^5.61.0",
        "webpack-cli": "^4.9.1",
        "webpack-dev-server": "^4.4.0"
    }

``` 

@zacfarnsworth and team: sry about the inconvinience with this issue!
