### ISSUE TITLE
setSelectedDataAsync broken for large base64 strings in Powerpoint

### ISSUE THREAD

**Issue by jacob-j** [OfficeDev/office-js#225]
We have come across a issue with the Office.js API in Powerpoint desktop.
When we insert a base64 string as image, and if the image is really large, it just fails in the middle of it resulting in a half-inserted image. (See screenshot).
The API we are using is Office.context.document.setSelectedDataAsync

I have tried the exact same API in Word, Word Online and Powerpoint Online. There it works fine.
So something is up with Powerpoint on desktop.

<img width="701" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/5649576/44329623-31441e00-a465-11e8-840b-effbd0b66a6c.png"> Inserting in Powerpoint

<img width="184" alt="pastedgraphic-2" src="https://user-images.githubusercontent.com/5649576/44329655-45881b00-a465-11e8-9a0c-7f7f990a9f53.png"> AsyncResult in powerpoint.

## Expected Behavior
Insert full-size base64 image, or atleast fire error if the api can't.

## Current Behavior
No error, but large images are just half-size inserted.

## Steps to Reproduce, or Live Example
Insert a large base64 string using Office.context.document.setSelectedDataAsync API.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac and PC desktop. 
* Host [Excel, Word, PowerPoint, etc.]: Powerpoint
* Office version number: 16.16
* Operating System: Mac

We offer this "insert original sizes" as a premium feature, so feedback on this issue asap would be much appreciated :)

**Comment by JuaneloJuanelo** [comment]
@jacob-j can you please specify in more detail what does large image means? (in MB or GB)  thanks!

**Comment by jacob-j** [comment]
@JuaneloJuanelo The image I tested was at 6MB

**Comment by jacob-j** [comment]
@JuaneloJuanelo Do you have any news on this issue? Thanks

**Comment by jacob-j** [comment]
@JuaneloJuanelo Any progress on this issue?

**Comment by JuaneloJuanelo** [comment]
we have a confirmation that this is a bug and we are working on a fix. Reference 2674065.

**Comment by jacob-j** [comment]
@JuaneloJuanelo Hello Juan. Do we have any updates on this issue? :) Thanks in advance

**Comment by JuaneloJuanelo** [comment]
yes its now working! please try it! have you?

**Comment by JuaneloJuanelo** [comment]
@jacob-j  can you please test and let me know? thanks!

**Comment by jacob-j** [comment]
@JuaneloJuanelo We have tried it here at Pickit and it works fine :) Thanks for the support Juan!

**Comment by JuaneloJuanelo** [comment]
@jacob-j  thanks so much for confirming the fix! I am closing this issue now.

**Comment by ogomez92** [comment]
Is this broken for office online? I get an error saying cannot modify selection when using setSelectedDataAsync in Powerpoint Online.
