### ISSUE TITLE
On-send event withdrawn on browser window resize Outlook on the Web

### ISSUE THREAD

**Issue by Hamish-A-SB** [OfficeDev/office-js#2250]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

As far as I can tell, my code is fine and it is something in Outlook on the web that is causing the problem so I am submitting this issue.

The problem is for Outlook on the web in all browsers I have tested (Chrome, Firefox and Edge).  The on-send feature is used for an Outlook add-in that displays a dialog box when the send button is pressed. The problem is that when it runs online and the Outlook browser window is resized (NOT the dialog window), the whole on-send function file js script is run again. The original dialog persists however and it cannot be closed as the dialog variable is now undefined (from the script being rerun) so the .close() method cannot be used. Also since the dialog variable is redefined, communication with the dialog cannot be done and the add-in is rendered useless.

The reloading of the Javascript only happens when the window width is being increased (not decreased) and it happens at around these points: 490px 650px, 1025px, 1400px, 1920px (Outlook window width not the dialog window width). This makes me think that Microsoft has some sort of dynamic styling or js that reloads the add-in for different screen sizes on the web.

The dialog is being opened as an iframe. When the dialog is instead opened using: displayInIframe: false (as a seperate pop-up window) a second dialog opens when the screen is resized.

The general structure of the function file js code that results in this behaviour is:

```
Office.onReady(() => {});
var dialog
function openDialog(event) {
      Office.context.ui.displayDialogAsync() function (asyncResult) {url, {height: 50, width: 50},displayInIframe: true}, 
      function(asyncResult){
              if (asyncResult.error.code == 12007)) {
                        dialog.close()    //this will not run as 'dialog' is now undefined from the script rerun
                        event.completed({allowEvent: false})
                       }
                  } else {
                        dialog.addEventHandler(Office.EventType.DialogMessageReceived, doSomething);}
      }
```

**Comment by teejay001** [comment]
Hi,

We are facing this same issue in our product development.

Please, is there any update or alternatives solution?

**Comment by t-ariyoshi30907** [comment]
I am facing the same problem with my product.
the customer is in trouble, could you improve it as soon as possible?

**Comment by johnrussellmoore** [comment]
Ah, just spent a whole day on this thinking I was going mad! Exact same problem - please let me know of a workaround!

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding on send pop-up. It has been put on our backlog. We, unfortunately, have no timelines to share at this point 

Internal tracking id: Office: 2453181

**Comment by bfsjmoore** [comment]
I'm sorry for my ignorance by could you clarify how/where I should be reporting this error? I am just developing an Outlook addin, not using any code downloaded from Github. I found this page through an internet search. Where is the official place to report Office Addin bugs? Thanks.
