### ISSUE TITLE
Outlook add-in offline not saving the email in the outbox folder

### ISSUE THREAD

**Issue by albeiroespitia** [OfficeDev/office-js#2251]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 20211018001.04
* Operating System: Windows
 
## Expected behavior
When there is no internet connection outlook should save the email in the outbox folder

## Current behavior
When there is no internet connection outlook is showing an error message related to my add-in and preventing the email to be saved in the outbox folder
"Outlook can't send this message because there's a problem with the add-in 'add-in name' " 

## Steps to reproduce
1. Install an add-in that uses ItemSend event
2. Disconnect from internet
3. Send an email

# Provide additional details
1. Our add-in is using ItemSend event

## Context
I'm trying to prevent the user from getting stuck in the email compose windows, or at least show an error message not related to the add-in, I've research for a place in the manifest to not try and download the add-in if the user doesn't have internet and found nothing.  Is there anyway to add that type of behavior?

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by alison-mk** [comment]
Hi @albeiroespitia, thank you for submitting this issue! I've assigned it to the @exextoc engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by exextoc** [comment]
The current ItemSend event add-in is designed for critical add-ins that must be run before send. As a result, if you are in offline mode, you cannot run add-ins, and so the message cannot be sent. We understand that this is not ideal in certain situations. One option would be to use [Smart Alerts](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough) which is currently in Preview.

**Comment by albeiroespitia** [comment]
> The current ItemSend event add-in is designed for critical add-ins that must be run before send. As a result, if you are in offline mode, you cannot run add-ins, and so the message cannot be sent. We understand that this is not ideal in certain situations. One option would be to use [Smart Alerts](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough) which is currently in Preview.

Yeah, we have been trying to implement the smart alerts solution, but it's just not working for us, the onMessageSendHandler function is not getting called at all, what's the difference between this and the ItemSend event?

**Comment by exextoc** [comment]
Can you check/confirm if your Office client is in Preview? Can you also re-share your Outlook version/office build number that can be found in Outlook when you go under Files and Office Account?
it should look something like this:
![image](https://user-images.githubusercontent.com/28549921/142918812-5ac73cef-ad89-4075-9838-ec0344fa2b02.png)


Smart Alerts is the new and improved version of ItemSend and there are different Send Modes that you can adjust in the manifest to control things like whether an email can be still sent or not when the add-in is unavailable, and Smart Alerts should allow the email to be saved in the Outbox folder when you have lost internet connection.
