### ISSUE TITLE
How to get the calendar for an email address in o365 in outlook add-in?

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#2252]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I want to write a meeting related add in, and I want to get the calendar for an email address in o365 in outlook add-in, I don't see the API, need help, thanks.

**Comment by exextoc** [comment]
The documentation link for the add-in APIs : [Documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets)

Also, could you please elaborate on your requirement so that we could assist you better.

**Comment by ghost** [comment]
Requirements: Every time we have a meeting we need to invite one of the person from special team, there are more than 20 members in the team and we only need any of them. currently we need find person who is available one by one, it takes a lot of time. We want outlook add-in to query who is available at given time slot, so I need to query user calendar in add in.

**Comment by exextoc** [comment]
@timothyzhang999 you can leverage the graph APIs to achieve the same. 

Documentation: [Link](https://docs.microsoft.com/en-us/graph/outlook-get-free-busy-schedule)

**Comment by ghost** [comment]
How to use this API? I tried to get token in add-in and postman, get error,
**I get token in add-in this way:**
```
Office.context.mailbox.getCallbackTokenAsync({isRest: true}, function(result){
  if (result.status === "succeeded") {
    var accessToken = result.value;
  } else {
    // Handle the error.
  }
});
```

And I use this accessToken as Bear token in postman, post to https://graph.microsoft.com/v1.0/me/calendar/getschedule,
get this error:
```
{
    "error": {
        "code": "InvalidAuthenticationToken",
        "message": "Access token validation failure. Invalid audience.",
        "innerError": {
            "date": "2021-11-18T02:27:58",
            "request-id": "0204f326-c6f4-4b72-9c35-c61a0be1fe45",
            "client-request-id": "0204f326-c6f4-4b72-9c35-c61a0be1fe45"
        }
    }
}
```

The other question is we will get CROS error when I post request from add-in to https://graph.microsoft.com/v1.0/me/calendar/getschedule.

**Comment by exextoc** [comment]
@timothyzhang999 Please refer to the following link  to get the access token for using graph APIs. 
Url: [https://docs.microsoft.com/en-us/graph/auth-v2-user](https://docs.microsoft.com/en-us/graph/auth-v2-user)

**Comment by timothyzhang999** [comment]
Hi @exextoc , thanks, but I'm afraid the link you gave can't be used by add-in app.

**Comment by ghost** [comment]
I tried it, I also looked the sample: https://github.com/OfficeDev/office-js-helpers, https://docs.microsoft.com/en-us/office/dev/add-ins/develop/grant-admin-consent-to-an-add-in, it needs org ADMIN login. Is it possible login without org ADMIN, we only need to get Schedule.

**Comment by exextoc** [comment]
The authentication to Graph API is possible through [SSO API ](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph)or through [Dialog API](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph-without-sso). I have linked the documentations here. Please see if this helps you.
