### ISSUE TITLE
PowerPoint.createPresentation does not work anymore in PowerPoint Online

### ISSUE THREAD

**Issue by FranCerrada** [OfficeDev/office-js#2254]
In PowerPoint Online when trying to create a presentation using powerpoint web api the presentation is not created and we get the following error:
```
powerpoint-web-16.00.js:26 Uncaught (in promise) RichApi.Error: An internal error has occurred.
    at new n (powerpoint-web-16.00.js:26)
    at o (powerpoint-web-16.00.js:26)
    at Object.OSF.DDA.issueAsyncResult (powerpoint-web-16.00.js:26)
    at Object.onComplete (powerpoint-web-16.00.js:26)
    at Object.callback (powerpoint-web-16.00.js:26)
    at v (powerpoint-web-16.00.js:26)
```
This was working yesterday and nothing has change in our side. We are using the beta channel, but also tried using the release channel and the issue is still reproducible.
If it helps, I can say that this dialog is not showing anymore 
![image](https://user-images.githubusercontent.com/19287486/142223759-631ec200-c1cc-478f-8005-9c4b6bba4153.png)

## Your Environment

* Platform: Office Online
* Host: PowerPoint
* Operating System: Windows 10
* Browser: Chrome
 
## Expected behavior
Presentation will be created in new tab of the Browser
## Current behavior
It throws the above error and the presentation is not created

## Steps to reproduce

1. Open an add-in that can create a presentation in PowerPoint Online
2. Invoke PowerPoint.createPresentation(base64file) passing the url to the presentation you want to create in base64.

## Context
The creation of the presentation happens from an Dialog loading an iframe.

## Useful logs
```
powerpoint-web-16.00.js:26 Uncaught (in promise) RichApi.Error: An internal error has occurred.
    at new n (powerpoint-web-16.00.js:26)
    at o (powerpoint-web-16.00.js:26)
    at Object.OSF.DDA.issueAsyncResult (powerpoint-web-16.00.js:26)
    at Object.onComplete (powerpoint-web-16.00.js:26)
    at Object.callback (powerpoint-web-16.00.js:26)
    at v (powerpoint-web-16.00.js:26)
```

**Comment by alison-mk** [comment]
Hi @FranCerrada, thank you for submitting this issue! We've assigned it to @lliu113 and @ononder, who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by ononder** [comment]
We have identified the issue that is causing this and currently waiting for the fix to be deployed. Thanks for your feedback.

**Comment by FranCerrada** [comment]
Thanks!

**Comment by ononder** [comment]
The issue should be fixed now, let us know if you have any follow up questions regarding this. Thanks for your feedback.

**Comment by FranCerrada** [comment]
I can confirm is working again. Thank you!
