### ISSUE TITLE
Roaming error with some specific account

### ISSUE THREAD

**Issue by markb-trustifi** [OfficeDev/office-js#2256]
# Provide required information needed to triage your issue
We cannot save roaming data using office-js SDK for 1 specific account `mmizrahitest@outlook.com`.
It doesn't work with this account in different PCs and other outlook.com accounts do work on this PC.

```
Office.context.roamingSettings.set(name, data);
Office.context.roamingSettings.saveAsync(result => {
   if (result.status === Office.AsyncResultStatus.Failed) {console.error('roamingSettings error: ', result);}
   callback(result);
});
```
We receive an error:
`OSF.DDA.Error {name: 'GenericSettingsError', message: 'An internal error has occurred.', code: 9019}`

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: OWA, PC desktop, Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: v16.54, 365 subscription
* Operating System: Windows, Mac
* Browser (if using Office on the web): Chrome
 
## Expected behavior
The code should save roaming data

## Current behavior
The error received:
`OSF.DDA.Error {name: 'GenericSettingsError', message: 'An internal error has occurred.', code: 9019}`

## Steps to reproduce
Run the given code

## Link to live example(s)
Script Lab is not supported by Outlook for Mac for "Microsoft Account"

## Context
It prevents the saving profile data in the roaming storage.

## Useful logs
`OSF.DDA.Error {name: 'GenericSettingsError', message: 'An internal error has occurred.', code: 9019}`

**Comment by alison-mk** [comment]
Hi @markb-trustifi, thank you for submitting this issue! I've assigned it to the Outlook engineering team @exextoc who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by exextoc** [comment]
Can you please confirm which platforms you are seeing this in? The office version number you provided is for Mac, are you seeing this in Windows? If so, what is the windows office version number?

**Comment by markb-trustifi** [comment]
I see it in OWA in Chrome browser and in desktop clients in both Mac and Windows.
There is something wrong with the outlook account itself because other accounts work correct.

**Comment by exextoc** [comment]
Do you notice other issues with this account?  For example, could you create and send email with this account? Is it possible that the mailbox is full?

**Comment by markb-trustifi** [comment]
> Is it possible that the mailbox is full?

This account looks ok and can send and recieve emails.

**Comment by exextoc** [comment]
@markb-trustifi the error you are receiving also indicates that the total size of the roaming settings for the account you are using is greater than the limit of 32 KB characters.

This means that length of the serialized form of the new settings you are adding + the length of the serialized form of already existing settings is greater than 32 * 1024 characters.

Try debugging your add-in by using our debug JavaScript library in-order to confirm this.
Use `https://appsforoffice.microsoft.com/lib/1.1/hosted/office.debug.js` in your add-in's HTML file instead of `.../hosted/office.js`. Run your add-in and it will pull down the Outlook debug JS file ([link](https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-win32-16.02.debug.js)).

In the Outlook JS file, you can set a breakpoint here:

```
var settingsMaxNumberOfCharacters = 32 * 1024;
function saveSettingsRequest(data) {
  ...
  ...
  var serializedSettings = saveSettingsRequest_OSF.DDA.SettingsManager.serializeSettings(data);

  if (JSON.stringify(serializedSettings).length > settingsMaxNumberOfCharacters) {
    var asyncResult_1 = createAsyncResult(undefined, saveSettingsRequest_OSF.DDA.AsyncResultEnum.ErrorCode.Failed, 9019, commonParameters.asyncContext, "");

    if (!!commonParameters.callback) {
      setTimeout(function () {
        if (!!commonParameters.callback) commonParameters.callback(asyncResult_1);
      }, 0);
    }
  }
  ...
  ...
}
```

**Comment by markb-trustifi** [comment]
Thank you for this answer. I'll implement it.
