### ISSUE TITLE
Web Outlook Dialog Will Not Close After Some Long Delay

### ISSUE THREAD

**Issue by gaambion** [OfficeDev/office-js#2257]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **PC Laptop**
* Host [Excel, Word, PowerPoint, etc.]: **Web Outlook**
* Office version number: **20211101003.17**
* Operating System: **Windows 11**
* Browser (if using Office on the web): **Microsoft Edge**
 
## Expected behavior

- Open a dialog thru on send event of web Outlook.
- Leave the dialog open for 5 minutes or longer.
- Close the dialog by clicking on the "X" button.
- Dialog will close and cancel the sending of email.

## Current behavior

- Open a dialog thru on send event of web Outlook.
- Leave the dialog open for 5 minutes or longer.
- Close the dialog by clicking on the "X" button.
- Dialog will not close and an error will be thrown in the console. Error came from the get

## Steps to reproduce

1. Call the function displayDialogAsync thru on send event of web Outlook.
2. Leave the dialog open for 5 minutes or longer.
3. Close the dialog by clicking on the "X" button.

## Context

I am trying to attach an additional feature/process during on send event of web outlook. This will open a dialog that will fetch some data from user for further internal processing. Closing the dialog within a few minutes will not cause any issues but when the dialog is left open for a long period of time, the close button of the dialog will not work anymore and will require a hard refresh from the user in order to remove the dialog.

Note: I have tried this on both Javascript and Angular. Issues can be found on both approach.

## Useful logs

- [x] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

![image](https://user-images.githubusercontent.com/22429474/142482542-61d2df28-d360-4d57-a4dd-05aaab011128.png)

![image](https://user-images.githubusercontent.com/22429474/142481140-18bf861c-2920-4bec-81a7-5a82333bbac2.png)

**Comment by alison-mk** [comment]
Hi @gaambion, thank you for submitting this issue! I've assigned it to the Outlook engineering team @exextoc who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by neville-jones** [comment]
As per [https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=windows#how-does-the-on-send-feature-work](url) :

> Validation is done on the client side in Outlook when the send event is triggered, and the add-in has up to 5 minutes before it times out. If validation fails, the sending of the item is blocked, and an error message is displayed in an information bar that prompts the user to take action.

Can't recall if this is mentioned in the API documentation, but you have to use a timer to automatically close the dialog prior to the 5 minute timeout.

**Comment by gaambion** [comment]
> As per [https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=windows#how-does-the-on-send-feature-work](url) :
> 
> > Validation is done on the client side in Outlook when the send event is triggered, and the add-in has up to 5 minutes before it times out. If validation fails, the sending of the item is blocked, and an error message is displayed in an information bar that prompts the user to take action.
> 
> Can't recall if this is mentioned in the API documentation, but you have to use a timer to automatically close the dialog prior to the 5 minute timeout.

Thank you for this information. I was not able to see this one as I only looked through the dialog documentation. Will keep this noted.
