### ISSUE TITLE
paragraph.text property contains a special character when the paragraph has a comment.

### ISSUE THREAD

**Issue by Fruch6807** [OfficeDev/office-js#2258]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
`paragraph.text` property contains `\u0005` special character when the paragraph has a comment.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.55 (21111400)
* Operating System: macOS Big Sur 11.6
* Browser (if using Office on the web): –
 
## Expected behavior
The `paragraph.text` property should only contain the real text of the paragraph.

## Current behavior
The `paragraph.text` property has a `\u0005` character at the end of the comment.

## Steps to reproduce

1. Add a comment to a paragraph ("Review" tab, "New Comment" button)
2. Retrieve the `paragraph.text` property of the paragraph with a comment

## Link to live example(s)

1. https://gist.github.com/Fruch6807/4e525354716541d98f3553827edd2a4f

# Provide additional details

1. Click the "Run" button
2. Notice how the first paragraph has a special character in console.

## Useful logs

- [x] Screenshots
![image](https://user-images.githubusercontent.com/24506031/142587530-2094a38b-d096-4590-b241-03fd87d40dd4.png)
- [x] Test file (if only happens on a particular file)
[with-comment.docx](https://github.com/OfficeDev/office-js/files/7568702/with-comment.docx)

**Comment by alison-mk** [comment]
Hi @Fruch6807, thank you for submitting this issue! We've assigned it to @AbidRahman-MSFT who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by AbidRahman-MSFT** [comment]
Thanks for posting this issue @Fruch6807 - this looks to be a similar issue as #2114 , you can use the workaround provided in that issue to solve this problem and we will ensure we update the documentation to be accurate.

**Comment by Fruch6807** [comment]
@AbidRahman-MSFT thank you for this workaround, but I'm still not sure this is the intended behavior, since this character is not added in Office on the web:

![image](https://user-images.githubusercontent.com/24506031/142906697-e7ab4530-04e7-446d-94e8-8fa4fe8034ae.png)

**Comment by AbidRahman-MSFT** [comment]
Thanks for highlighting that @Fruch6807. Comments are a new feature on Word Web so we need to make sure they work similar to Windows/Mac. Adding @RuoyingLiang here as FYI. I will work with them team to ensure the behavior is the same cross platform.
