### ISSUE TITLE
[ Outlook ] question on getting 'Sensitivity' setting in compose mode

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#2264]
I have a question on getting 'Sensitivity' setting.
Actually, I have already get 'Sensitivity' setting from a saved event. ( use rest api )
But the problem is I can't get this setting on a composing event, no matter I using rest or office.js api.
Does Microsoft support add-in get 'Sensitivity' setting on compose mode now?

**Comment by exextoc** [comment]
For specifics on REST/ Graph API, this is best to check with graph documentation and forums.  For composing events, the item may not be synced to the server until save. If you want to check if this is an addin specific issue, please include the API call and the error you are getting.

In general, for setting / getting properties that are on the client, the best experience for users of the addin would be to have OfficeJS API support.  We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by SWei1234** [comment]
Hi @exextoc 
I see office.js already have this api: https://docs.microsoft.com/en-us/javascript/api/outlook/office.sensitivity?view=outlook-js-preview
Just not support commercial applications for the time being. 
For rest api, we need itemId which only generate after event synced to the server. But some sensitivity option can be see directly on UI, like: 
![image](https://user-images.githubusercontent.com/15980696/142963262-1063844a-e7e3-4fce-a156-ec18e4d5949d.png)
The following is only from the user's point of view:
I don't think these UI options need to be synchronized with the server before they can get values. I feel that such logic is inefficient.
I think the design of office.js is reasonable, but I don't know when this interface can be opened.
If any update about this feature please let me know. Thank you very much for your support.

**Comment by exextoc** [comment]
Thanks for pointing out the https://docs.microsoft.com/en-us/javascript/api/outlook/office.sensitivity?view=outlook-js-preview in preview. I missed that.  Sorry for the confusion.  You are right that such OfficeJS APIs (that get/set client properties) would be client side as much as possible, and avoiding sync delays and having client reflect the changes as soon as possible are some of the reasons we would want Office JS API over REST API.  

I don't currently have update on the feature, but please let us know if you have thoughts or hit issues with the Sensitivity OfficeJS API.  I have also edited my previous comment to avoid confusion

**Comment by SWei1234** [comment]
Yes, we have a plan to get this attribute, but at present, it seems that no interface can meet the requirements.
Only hope that this interface can be released in the near future.
Thanks

**Comment by SWei1234** [comment]
Hi @exextoc 
Another strange thing about this api is: 
I tried 'https://docs.microsoft.com/en-us/javascript/api/outlook/office.sensitivity?view=outlook-js-preview#getAsync_options__callback_' this office api, but never get a response.
I have included the 'https://appsforoffice.microsoft.com/lib/beta/hosted/office.js' and manifest file permission is 'ReadWriteItem'

My code is:
`Office.context.mailbox.item.sensitivity.getAsync(function(asyncResult) {
  if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
    console.log("Sensitivity: " + asyncResult.value);
  } else {
    console.log("Failed to get sensitivity: " + JSON.stringify(asyncResult.error));
  }
});`
It never run callback, any idea?
This problem currently looks only happened on OWA/PWA. Is there a way to prevent this problem? Like, detect add-in is running on a preview environment ?

**Comment by exextoc** [comment]
Hello @SWei1234 

Thanks for reporting this issue regarding the Sensitivity APIs in OWA. It has been put on our backlog. 
We, unfortunately, have no timelines to share at this point.
Internal tracking id: Eg: Outlook Web: 136308

The Sensitivity APIs are still in preview, and we have not decided which API set to ship these APIs in.

**Comment by SWei1234** [comment]
Hi @exextoc  
I will close this ticket now. If any update please reopen this ticket or send me a message here. 
Thanks
