### ISSUE TITLE
Content Office Add-ins Lost focus after select file from file input 

### ISSUE THREAD

**Issue by 10142904** [OfficeDev/office-js#2265]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

after i updated office to Microsoft 365MSO (version 2111 Build 16.0.14701.20030) 32 bit, when click file input button from my content office add-in and select a file, return to content add-in, i can not interaction with it. It seems to have lost focus and also not accept mouse clicks unless I move focus to another element first and then click on it, now it works fine

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: 16.0.14701.20030
* Operating System: windows
* Browser (if using Office on the web): ______
 
## Expected behavior
I can still interact with add-in when I have selected the file

## Current behavior
I can't interact with add-in when I've selected the file from file input

## Steps to reproduce
1. insert a content add-in which include file input
2. click the input and File dialog box appears_ and select a file, click open
3. the content add-in can not be click and freeze

## Link to live example(s)
1.  insert a content add-in: GeoGebra for PowerPoint
2. Select the menu in the top right corner, choose File and select Open and select a file to open
3. the content add-in can not be click and freeze

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by preethikakiru** [comment]
Hi @10142904, thank you for submitting this issue! I've assigned this issue to @lliu113 who will be able to further help you resolve this issue and provide you with more information!
Best,
Preethika

**Comment by 10142904** [comment]
Hi, @lliu113 Has the problem been solved? i have updated office to 16.0.14729.20156 and fond the bug has not been fixed，When will it be repaired?

**Comment by s-o-na** [comment]
Hi, 

I am developing an add-in for PowerPoint, which has file upload functionality. On Windows when a user tries to upload a file, the main window loses focus and the add-in becomes unusable (if you minimize and maximize the PowerPoint window, or try to resize the add-in the focus will be back)
Is there a way to bring back the focus to the main window programmatically? any available functions in Office.js?

Thanks,
Sona

**Comment by ElizabethSamuel-MSFT** [comment]
@massonj Can you assign to the appropriate person to take a look?

Thanks.
