### ISSUE TITLE
Excel shared runtime with CustomFunction not working upon service restarted

### ISSUE THREAD

**Issue by chanhohang** [OfficeDev/office-js#2267]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 365
* Operating System: Windows 10
* Browser (if using Office on the web): NA
 
## Expected behavior

My Excel add-in manifest is with long runtime and Custom functions supported. (Part of the manifest)
`        
        <Runtimes>
          <Runtime resid="TbricksAddin.Url" lifetime="long" />
        </Runtimes>
        <AllFormFactors>
          <ExtensionPoint xsi:type="CustomFunctions">
            <Script>
              <SourceLocation resid="Functions.Script.Url"/>
            </Script>
            <Page>
              <SourceLocation resid="TbricksAddin.Url"/>
            </Page>
            <Metadata>
              <SourceLocation resid="Functions.Metadata.Url"/>
            </Metadata>
            <Namespace resid="Functions.Namespace"/>
          </ExtensionPoint>
        </AllFormFactors>
...
      <bt:Urls>
        <bt:Url id="GetStarted.LearnMoreUrl" DefaultValue="https://go.microsoft.com/fwlink/?LinkId=276812"/>
        <bt:Url id="Functions.Script.Url" DefaultValue="https://localhost:20080/excel-app/functions.js"/>
        <bt:Url id="Functions.Metadata.Url" DefaultValue="https://localhost:20080/excel-app/functions.json"/>
        <bt:Url id="Functions.Page.Url" DefaultValue="https://localhost:20080/excel-app/functions.html" />
        <bt:Url id="TbricksAddin.Url" DefaultValue="https://localhost:20080/excel-app/taskpane.html?sharedRuntime=true"/>
      </bt:Urls>
`

Everything now is working normally when the local process is running together with Excel.
When we terminate our process listening on port https://localhost:20080 and do a few times of connect/disconnect. (that's basically trying to establish a network connection to https://localhost:20080, the add-in will be disappeared from the menu.

When we start our local process to listen port https://localhost:20080 and reload the add-in, the add-in will be able to loaded up but the add-in panel is becoming blank.

What we are expecting is the add-in panel should work after restarted the local process as if normal connect of the add-in.

## Current behavior
Please check above description.

## Steps to reproduce

1. setup a manifest/add-in that supports long runtime, custom functions and connect to a localhost process
2. terminate the local process while the excel is connected to the add-in, connect/disconnect the add-in a few times by clicking the button on ribbon.
3. the add-in will be disappeared with error, restart the local process and reload the add-in
4. when the add-in is successfully reload, click connect button to resume operation.

## Link to live example(s)

N.A.

# Provide additional details

1. Can update the https://github.com/OfficeDev/Excel-Custom-Functions sample with Runtime=Long
2. Can also add a streaming function that based on timer
3. Please refer to the manual step from the attached gif
![add-in-restarted-during-operation](https://user-images.githubusercontent.com/4111001/142980542-ecfc0885-c393-4227-9c2e-eec35e865d86.gif)

## Context

Our client is required to manually restart the whole excel process to recover from process restarted.

## Useful logs

N.A.

**Comment by jiju-MS** [comment]
Hi, chanhohang, 
we'd like to verify some details about your issue:
1. Do you hold your custom function files(like function.js and metadata.json) on the same service using  https://localhost:20080?
2. Does this blank taskpane issue happened before you using shared runtime(long runtime)
3. May I ask the expecting behavior for your user scenario? Will it be the add-in taskpane should remain when the add-in service is disabled due to some reason or disconnect on purpose?

**Comment by chanhohang** [comment]
> Hi, chanhohang, we'd like to verify some details about your issue:
> 
> 1. Do you hold your custom function files(like function.js and metadata.json) on the same service using  https://localhost:20080?

chanhohang=> That's Correct. The Custom Function and taskpane is the same https://localhost:20080
Please feel free to check the attached manifest file.
[TbricksExcelManifest.txt](https://github.com/OfficeDev/office-js/files/7606095/TbricksExcelManifest.txt)

> 2. Does this blank taskpane issue happened before you using shared runtime(long runtime)

chanhohang => we never test disconnect/reconnect without long runtime. So i will say not applicable to my case.
> 3. May I ask the expecting behavior for your user scenario? Will it be the add-in taskpane should remain when the add-in service is disabled due to some reason or disconnect on purpose?

chanhohang => so this user scenario is to make sure our excel add-in/custom function will seamlessly resume the operation when our process is restarted.

Please feel free to let me know any more questions that can help the investigation of this issue. 

Thanks,

**Comment by jiju-MS** [comment]
we are trying to repro the issue locally, here are some thoughts may help:
Excel need to download all files related to custom function like function.js, metadata.json and taskpane.html(sharedruntime), so if the service which hold this files(https://localhost:20080) disabled, then it can not download and will show blank taskpane. so if in the real scenario, your service process restart will not affect the js, json and html file, maybe you can try to deploy those files in different service(for testing, maybe github page or azure or other localhost)

**Comment by chanhohang** [comment]
@jiju-MS 

thank you so much for your reply and suggestion. deploying the resources localhost is part of the "mandatory" requirement for our solution. 

So it will be great if Excel can handle better the connection loss to add-in resources.

**Comment by chiz-ms** [comment]
Hi @chanhohang, after investigation the team feels this would be a new feature request to Custom Functions. Please go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) and see if your feature has already been requested or request a new feature there.

**Comment by Stepan-Valkov** [comment]
I have created a feature request for this issue: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/excel-add-in-with-custom-functions-should-reload-without-issues/idi-p/3135920#M700
