### ISSUE TITLE
Office.context.mailbox.userProfile.emailAddress returns UPN in Outlook for Android

### ISSUE THREAD

**Issue by GrumpyAL** [OfficeDev/office-js#2269]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Android
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook for Android 4.2144.1 (42144813)
* Operating System: Android
* Browser (if using Office on the web): n/a
 
## Expected behavior
When getting the user's SMTP address from Office.context.mailbox.userProfile.emailAddress the Primary SMTP address is returned.(This is the current behavior on other Platforms).

## Current behavior
When getting the user's SMTP address from Office.context.mailbox.userProfile.emailAddress the UPN is returned.

## Steps to reproduce

1. Use an account with a different Primary SMTP and UPN.  You can do this via Exchange Online PowerShell to change the Primary SMTP without altering the UPN `Set-Mailbox user@example.com -WindowsEmailAddress userAlias@examplecompany.com`
2. Create an Outlook Add-in (or alter an existing one) to print out the user's email address.
3. Note that on Outlook on the Web and Outlook on Windows and/or Outlook on iOS the primary SMTP address is printed.
4. Note that on Outlook for Android, the UPN is printed instead.

## Link to live example(s)
n/a - I tried to get something working via ScriptLab but it doesn't appear to be available on Android.

# Provide additional details
n/a

## Context
This may impact how we track metrics for our customers in some solutions.  The user may be seen as two different people.

## Useful logs
n/a

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by preethikakiru** [comment]
Hi @GrumpyAL, thank you for submitting this issue! I've assigned it to the Outlook Engineering Team @exextoc who will be able to provide you with more information!
Best,
Preethika

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding userProfile.emailAddress API. It has been put on our backlog. We unfortunately have no timelines to share at this point. Internal tracking Id: 2474019.

**Comment by exextoc** [comment]
This issue has been fixed and will be part of Outlook android release 4.2152.0. We have started rollout of this release, please look out for the update.
