### ISSUE TITLE
reading wrong namespace for customXmlParts using namespace

### ISSUE THREAD

**Issue by vmrathod** [OfficeDev/office-js#227]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
Thank you for your understanding and continued feedback.

I am using following method to read a customXmlParts using namespace.
`function showXMLPartsInNamespace() { `
`  Office.context.document.customXmlParts.getByNamespaceAsync("http://xyz.com/schemas", function `
`(eventArgs) { `
`  write("Found " + eventArgs.value.length + " parts with this namespace"); `
`  }); `
`}`

I have two files in my customxml "item1.xml" and "item2.xml".
Item1.xml has namespace 

> http://xyz.com/schemas

 and Item2.xml has namespace 

> http://xyz.com/externalschemas

But above code sometime read the customXmlParts  of "http://xyz.com/externalschemas" even though I have specified the namespace is "http://xyz.com/schemas". 
Is there any solution to stop to read a customXmlParts   of "http://xyz.com/externalschemas" namespeace?

**Expected Behavior**
Office.context.document.customXmlParts.getByNamespaceAsync should always read customXmlParts   from given namespace

**Current Behavior**
sometime Office.context.document.customXmlParts.getByNamespaceAsync read customeXmlParts from wrong namespace

Your Environment
Platform: PC desktop
Host: Word
Office version number: Office 2016 build 1803
Operating System: Windows 10
Browser (if using Office Online): N/A

**Comment by JuaneloJuanelo** [comment]
please provide a copy of such document, until then we cannot investigate.

**Comment by vmrathod** [comment]
Here you find my gist [https://gist.github.com/vmrathod/4d2b0c48be5c3b9089a36e3c1e946906](url)

I have used following code to read a namespace **http://www.apttus.com/schemas**
`async function readSchema() {`
                ` await Word.run(async (context) => {`
               ` Office.context.document.customXmlParts.getByNamespaceAsync(`
                 `   "http://www.apttus.com/schemas",`
                  `  function (asyncResult) {`
                      `  asyncResult.value[0].getXmlAsync({}, function (e) {`
                     `       console.log(e.value);`
                     `   })`
                   ` });`
               ` await context.sync();`
            `});`
       ` }`
and for namespace **http://www.apttus.com/externalmetadata**

`async function readExternal() {`
                ` await Word.run(async (context) => {`
               ` Office.context.document.customXmlParts.getByNamespaceAsync(`
                 `   "http://www.apttus.com/externalmetadata",`
                  `  function (asyncResult) {`
                      `  asyncResult.value[0].getXmlAsync({}, function (e) {`
                     `       console.log(e.value);`
                     `   })`
                   ` });`
               ` await context.sync();`
            `});`
       ` }`

In both cases code always read the namespace **http://www.apttus.com/schemas** and also verified both functions are getting length 1 for both namespace.

Here are the document and .zip file.

[VR_220818_Regenerated_HD XAJS 1949 AGT-001_2018-08-24_2.0.0 (1).zip](https://github.com/OfficeDev/office-js/files/2323044/VR_220818_Regenerated_HD.XAJS.1949.AGT-001_2018-08-24_2.0.0.1.zip)

[VR_220818_Regenerated_HD XAJS 1949 AGT-001_2018-08-24_2.0.0 (1).docx](https://github.com/OfficeDev/office-js/files/2323037/VR_220818_Regenerated_HD.XAJS.1949.AGT-001_2018-08-24_2.0.0.1.docx)

**Comment by vmrathod** [comment]
Here you find my gist https://gist.github.com/vmrathod/4d2b0c48be5c3b9089a36e3c1e946906

I have used following code to read a namespace **http://www.xyz.com/schemas**
`async function readSchema() {`
                ` await Word.run(async (context) => {`
               ` Office.context.document.customXmlParts.getByNamespaceAsync(`
                 `   "http://www.xyz.com/schemas",`
                  `  function (asyncResult) {`
                      `  asyncResult.value[0].getXmlAsync({}, function (e) {`
                     `       console.log(e.value);`
                     `   })`
                   ` });`
               ` await context.sync();`
            `});`
       ` }`
and for namespace **http://www.xyz.com/externalmetadata**

`async function readExternal() {`
                ` await Word.run(async (context) => {`
               ` Office.context.document.customXmlParts.getByNamespaceAsync(`
                 `   "http://www.xyz.com/externalmetadata",`
                  `  function (asyncResult) {`
                      `  asyncResult.value[0].getXmlAsync({}, function (e) {`
                     `       console.log(e.value);`
                     `   })`
                   ` });`
               ` await context.sync();`
            `});`
       ` }`

In both cases code always read the namespace **http://www.xyz.com/schemas** and also verified both functions are getting length 1 for both namespace.

Here are the document and .zip file.
[VR_220818_Regenerated_HD XAJS 1949 AGT-001_2018-08-24_2.0.0.docx](https://github.com/OfficeDev/office-js/files/2323237/VR_220818_Regenerated_HD.XAJS.1949.AGT-001_2018-08-24_2.0.0.docx)

[VR_220818_Regenerated_HD XAJS 1949 AGT-001_2018-08-24_2.0.0.zip](https://github.com/OfficeDev/office-js/files/2323240/VR_220818_Regenerated_HD.XAJS.1949.AGT-001_2018-08-24_2.0.0.zip)

**Comment by vmrathod** [comment]
Is anybody get a chance to see my comment?
