### ISSUE TITLE
Add-ins are disabled entirely when using 'share' functionality from an external application to send mail

### ISSUE THREAD

**Issue by carlosb1504** [OfficeDev/office-js#2271]
Any Office-JS based web add-in which subscribes to the MessageCompose surface, is seemingly completely absent from the Outlook Window which is created when a user performs any kind of 'share' operation from an external application. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2110 Build 16.0.14527.20234
* Operating System: Windows 10
* Browser (if using Office on the web): N/A
 
## Expected behavior

Add-ons enabled for a given account, should be present no matter how Outlook is opened.

## Current behavior
When Outlook is closed, and the user shares a file from an external application (Eg. Adobe Acrobat Reader), an instance of Outlook is started, and a new mail compose window spawned, but this compose window has no add-ins enabled.

## Steps to reproduce

1. Enable _any_ office-js based web add-in on your account which subscribes to the message compose surface (i.e. works "on compose")
2. Close Outlook completely
3. Open any external application with the ability to share to a mail client. Adobe Acrobat Reader DC is a very common example of this.
4. Open a document within that external app, e.g. any PDF file
5. Perform a 'share' operation from the external app, or 'send file via email' type action, choose to send via Microsoft Outlook if multiple clients are installed, and choose the desktop client option if there are webmail clients listed.
6. Observe that a new mail window is spawned with the file that was being viewed automatically attached as expected, but in this new window, your add-in that was enabled in Step 1 is not present. No Ribbon buttons appear for it, no LaunchEvents are invoked.

## Context

This seems to be quite an easy way to circumvent any office.js based add-in, and represents a fairly serious shortcoming for any application where security is a factor.

**Comment by exextoc** [comment]
Currently the feature: addins on email started from external app or 'send file via email', you requested, is not a part of the product. This behavior is documented [here](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-add-ins-overview#mailbox-items-available-to-add-ins):

> Created through Simple MAPI. Simple MAPI is used when an Office user creates or sends an email from an Office application on Windows while Outlook is closed. For example, a user can create an Outlook email while working in Word which triggers an Outlook compose window without launching the full Outlook application. If, however, Outlook is already running when the user creates the email from Word, that isn't a Simple MAPI scenario so Outlook add-ins work in the compose form as long as other activation requirements are met.

We track Outlook add-in feature requests on our [Tech Community Page](https://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
