### ISSUE TITLE
Add notification on email sent

### ISSUE THREAD

**Issue by margielovelet** [OfficeDev/office-js#2272]
Is there a way I can add notification on the email I am sending using the add-in. I can add notification on the emails on my mailbox.
I can also add notification on the email in the compose window. But I wanted the notification in the compose window to persist even after is was sent. Is this possible. Thanks.

**Comment by grangeryy** [comment]
@margielovelet, could you please provide more details on this? 
- What Platform are you using? [PC desktop, Mac, iOS, Office on the web]
- Host? [Excel, Word, PowerPoint, Outlook, etc.]
- Office version number?
- Operating System?

**Comment by margielovelet** [comment]
@grangeryy 
Answers below, thank you.

What Platform are you using? [PC desktop, Mac, iOS, Office on the web]
Answer: Office on web and Windows PC

Host? [Excel, Word, PowerPoint, Outlook, etc.]
Answer: Outlook

Office version number?
Answer: Outlook 365

Operating System?
Answer: Windows 10

**Comment by exextoc** [comment]
Currently, the feature to persist notifications through send, that you requested, is not a part of the product. We track Outlook add-in feature requests on our Tech Community Page. Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

Github Label: “Type: product feature request”
https://aka.ms/M365dev-suggestions
