### ISSUE TITLE
New requirement sets for Word API anytime soon?

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/office-js#2273]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Question: Are you planning to release new requirement sets for the Word API at some time? There are some very useful features (e.g. document.settings) in the preview set but the latest release (1.3) was in 2017. Excel API (https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/word-api-requirement-sets) seems to get updated every half year. So have you given up Word? Will the Word API be deprecated?

**Comment by grangeryy** [comment]
@RuoyingLiang do you have any information on the new requirement set for Word APIs?
