### ISSUE TITLE
[Excel] Sometimes the Office.context.ui.displayDialogAsync shows a blank page.

### ISSUE THREAD

**Issue by knight-baron** [OfficeDev/office-js#2274]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Sometimes the Office.context.ui.displayDialogAsync shows a blank page. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2102 Semi-annual
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome
 
## Expected behavior
The dialog must display a message each time it is opened.

## Current behavior
Sometimes when Office.context.ui.displayDialogAsync is opened no message is displayed and only a blank page is displayed. But when we increase the size of the dialog, the text is displayed.

## Steps  to reproduce
Press the button that runs. Office.context.ui.displayDialogAsync Repeat, you will find that sometimes the page a blank page.

When the Office.context.ui.displayDialogAsync box opens
https://drive.google.com/file/d/1-PaJ9684HFer1EeJjy4utVVlMM3b3bVy/view?usp=sharing

When the size is anchored, the Office.context.ui.displayDialogAsync displays a message.
https://drive.google.com/file/d/1A7o37J0p5GOy7570fzg-mIdQKBki3CgC/view?usp=sharing

**Comment by grangeryy** [comment]
@knight-baron, for this issue, could you share with us additional information, for example, which add-in are you using to stably hit this problem? What are the steps you are taking to reproduce this issue? Thx!

**Comment by knight-baron** [comment]
Press the button that runs. Office.context.ui.displayDialogAsync Repeat, you will find that sometimes the page a blank page.
This problem is found only in Excel Semi-annual.
screen record: https://drive.google.com/file/d/1dEfjGLuVO4VuJRaCWB-1qgYwXVW8aTXF/view?usp=sharing

**Comment by knight-baron** [comment]
@grangeryy Any more updates?

**Comment by grangeryy** [comment]
@lliu113 do you have more information on this issue?
