### ISSUE TITLE
Deployed add-in does not always show up

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/office-js#2275]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I have an add-in for Word. I have deployed the add-in to a test user account which is used in our CI/CD flow. In the flow we have a UI test which requires (of course) that the add-in show up for the user.However, the add-in does not show some times. I have no idea why? I see this kind of errors in the console all the time that could be related

net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://c1h-word-edit-15.cdn.office.net/we/s/h92F5688C419FD0AA_App_Scripts/wordVersionHistory.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://c1h-word-edit-15.cdn.office.net/we/s/h4E64BC8659A312AA_App_Scripts/uiFabricLazy.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://amcdn.msftauth.net/meInlineBackCompat.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://c1h-word-edit-15.cdn.office.net/we/s/h79859FBC89C6FF73_App_Scripts/versionHistory.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://c1h-word-edit-15.cdn.office.net/we/s/h78118D1251243BF7_App_Scripts/pdfjsWorker.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://c1h-word-edit-15.cdn.office.net/we/s/h0F1E70A6D397BEB2_App_Scripts/al.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://c1h-word-edit-15.cdn.office.net/we/s/h041615371FF39279_App_Scripts/appChrome.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://c1h-word-edit-15.cdn.office.net/we/s/hE04CB12C10C9F35C_App_Scripts/sharedCommentsLazy.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://c1h-word-edit-15.cdn.office.net/we/s/h2ADAD56D09EC6DB1_App_Scripts/floatingContainerManager.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://c1h-word-edit-15.cdn.office.net/we/s/h28BD8EFF1283FA66_App_Scripts/uiSlice20.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://c1h-word-edit-15.cdn.office.net/we/s/h8F800AEB9D180D26_App_Scripts/healthOffline.worker.min.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://c1h-word-edit-15.cdn.office.net/we/s/hABDF6C6F5A63ADA2_App_Scripts/workerboot.min.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://wordwebclientbuilds.blob.core.windows.net/ooui/d7544f9f92a4288740dc16921be5508a3fcb21f4/WordEditorDS.collab.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://wordwebclientbuilds.blob.core.windows.net/ooui/d7544f9f92a4288740dc16921be5508a3fcb21f4/WordEditorDS.box4.dll2.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://cdn.uci.officeapps.live.com/mirrored/smartlookup/2021.11.10883156/scripts/microsoft.office.smartlookup.host.runtime.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://wordwebclientbuilds.blob.core.windows.net/ooui/d7544f9f92a4288740dc16921be5508a3fcb21f4/WordEditorDS.box4.dll1.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://wordwebclientbuilds.blob.core.windows.net/ooui/d7544f9f92a4288740dc16921be5508a3fcb21f4/WordEditorDS.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://wordwebclientbuilds.blob.core.windows.net/ooui/d7544f9f92a4288740dc16921be5508a3fcb21f4/WordEditorDS.common.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://wordwebclientbuilds.blob.core.windows.net/ooui/d7544f9f92a4288740dc16921be5508a3fcb21f4/WordEditorDS.box4.dll3.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://wordwebclientbuilds.blob.core.windows.net/ooui/d7544f9f92a4288740dc16921be5508a3fcb21f4/WordEditorDS.box4.dll4.js.map: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://wordwebclientbuilds.blob.core.windows.net/ooui/d7544f9f92a4288740dc16921be5508a3fcb21f4/WordEditorDS.worker.js.map: Fetch through target failed: Target not supported; Fallback: HTTP error: status code 403, net::ERR_HTTP_RESPONSE_CO

Also, when I go to "my addin" I often see this 
![image](https://user-images.githubusercontent.com/6726111/143408573-72348934-e5bd-4d1c-bc9d-b7bc18ed8bb1.png)

These problems block our progress. Can you help? 

Best Regards 
Jens

**Comment by grangeryy** [comment]
@JensMadsen, which deployment approach did you choose for the Word add-in: [Deploy and publish Office add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish) or did you use the [Centralized Deployment in the admin center](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide)? Have you tried other add-in for the test account, and will the same issue happen?

**Comment by JensMadsen** [comment]
@grangeryy Sorry about the missing information. I was just a bit frustrated :-) I use centralized deployment, I.e. I go to office365 admin center and deploy the manifest to users from there. When the addin does not show up this request time-out

```https://euc-word-edit.officeapps.live.com/we/AddinServiceHandler.ashx?action=getAddIns&app=word&catalog=privatecatalog&clientCode=WAC_Word&clientVersion=16.0.0.0&corr=2e89aca6-d71c-bf62-4562-b50ed2f7e148&WOPIsrc=https%3A%2F%2Fkarnovgroup%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fu0158066%5Fkarnovgroup%5Fcom%2F%5Fvti%5Fbin%2Fwopi%2Eashx%2Ffiles%2Fe86fde5cbf644f1ab65c7112ba3d3c1f&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkRya21Mczl1akhnMkp1SE5CRm5vOERicXBJSSJ9.eyJhdWQiOiJ3b3BpL2thcm5vdmdyb3VwLW15LnNoYXJlcG9pbnQuY29tQGYxOWRjMGZiLTZjYzktNDVlNi04ZmQwLWRlZDRjMDcyMDNkZSIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMEA5MDE0MDEyMi04NTE2LTExZTEtOGVmZi00OTMwNDkyNDAxOWIiLCJuYmYiOiIxNjM4MTc0MTk1IiwiZXhwIjoiMTYzODIxMDE5NSIsIm5hbWVpZCI6IjAjLmZ8bWVtYmVyc2hpcHx1MDE1ODA2NkBrYXJub3Zncm91cC5jb20iLCJuaWkiOiJtaWNyb3NvZnQuc2hhcmVwb2ludCIsImlzdXNlciI6InRydWUiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwxMDAzMjAwMTFiNjdhM2FkQGxpdmUuY29tIiwic2Vzc2lvbmlkIjoiYzg5NmQzZTAtN2FlZC00MDU5LTkwZDUtZDVkMjg5ZmI1MjYxIiwic2lnbmluX3N0YXRlIjoiW1wia21zaVwiXSIsInhtc19jYyI6IltcIkNQMVwiXSIsImlzbG9vcGJhY2siOiJUcnVlIiwiYXBwY3R4IjoiZTg2ZmRlNWNiZjY0NGYxYWI2NWM3MTEyYmEzZDNjMWY7TU1Jb2RUdWsyeFpwNFNMUjJSVDdxT0dxM2xNPTtEZWZhdWx0Ozs3RkZGRkZGRkZGRkZGRkZGO1RydWU7OzswOzc1Y2YwN2EwLWIwN2UtMzAwMC04N2YyLWJmNzIwNWNhMjYyMyJ9.dPjwFMGBPK9wcShHoq_-IIwKxIK5DwhlyS9WP7uARsitQg0l6q9I9653mr9ghrW1_SnAIYOUiKJljIIu9sncuJenhXaQo5uEJmZWCGveJJi2Km-kpTfh5abV7qBiDU1M673guFgwGbLYjm5jNrhJZJfzHFr1DlSFm_rpjZqLtTqEJqHgjLp3MDR3dGScD9Ki0ABsHMPsE1jvdGC4sCRMn35yZldQ-YMuLv4iONN5ajmXGvvz8JtnPQ-axVlpBTUaK_rT8rytGSYDZG-Sz6ursHTF1794UyuSNlfqVgXrlS7hcKtI3VByJ1E0SvGCiWbteDn3fHrN9jl2asQ7PSIItQ&access_token_ttl=1638210196759```

When this request succeeds everything is fine

**Comment by theboyknowsclass** [comment]
We're also having this issue, seems to fail 3 out of 4 times

**Comment by grangeryy** [comment]
Adding @AkhileshShah-MS to see if he knows about this issue.

**Comment by NickDarvey** [comment]
We're also, inconsistently, seeing this too. 

When it succeeds the network calls look like:

```
POST: https://word-edit.officeapps.live.com/we/AddinServiceHandler.ashx?action=getAddIns&app=word&catalog=privatecatalog&clientCode=WAC_Word&clientVersion=16.0.0.0&corr=5970f347-d717-d37f-5e56-4c0e956c45d4&WOPIsrc=https%3A%2f%2fexample%2Dmy%2Esharepoint%2Ecom%2fpersonal%2fme%5Fexample%5Forg%2f%5Fvti%5Fbin%2fwopi%2Eashx%2ffiles%2fd987952cbb85499cb47a307ae5f763bf&access_token=<ACCESS_TOKEN>
```

```json
{
  "RefreshToken": "<REFRESH_TOKEN>",
  "ResponseCode": 1,
  "TenantId": "<TENANT_ID>",
  "UserId": "<USER_ID>",
  "AddIns": [
    {
      "AddInState": "Ok",
      "ProductId": "<PRODUCT_ID>",
      "StoreInfo": { "AssetId": "<ASSET_ID>", "ContentMarket": "en-SG" },
      "Version": "1.0.0.0"
    }
  ]
}
```

When it fails the network call looks like this:

```
POST: https://word-edit.officeapps.live.com/we/AddinServiceHandler.ashx?action=getAddIns&app=word&catalog=privatecatalog&clientCode=WAC_Word&clientVersion=16.0.0.0&corr=5970f347-d717-d37f-5e56-4c0e956c45d4&WOPIsrc=https%3A%2f%2fexample%2Dmy%2Esharepoint%2Ecom%2fpersonal%2fme%5Fexample%5Forg%2f%5Fvti%5Fbin%2fwopi%2Eashx%2ffiles%2fd987952cbb85499cb47a307ae5f763bf&access_token=<ACCESS_TOKEN>
```

```json
{
  "RefreshToken": null,
  "ResponseCode": 2,
  "TenantId": "<TENANT_ID>",
  "UserId": "<USER_ID>",
}
```

**Comment by NickDarvey** [comment]
My issue is consistent with #1245, specifically [this detail](https://github.com/OfficeDev/office-js/issues/1245#issuecomment-676898200).

**Comment by cespujunk66** [comment]
> @grangeryy Sorry about the missing information. I was just a bit frustrated :-) I use centralized deployment, I.e. I go to office365 admin center and deploy the manifest to users from there. When the addin does not show up this request time-out
> 
> `https://euc-word-edit.officeapps.live.com/we/AddinServiceHandler.ashx?action=getAddIns&app=word&catalog=privatecatalog&clientCode=WAC_Word&clientVersion=16.0.0.0&corr=2e89aca6-d71c-bf62-4562-b50ed2f7e148&WOPIsrc=https%3A%2F%2Fkarnovgroup%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fu0158066%5Fkarnovgroup%5Fcom%2F%5Fvti%5Fbin%2Fwopi%2Eashx%2Ffiles%2Fe86fde5cbf644f1ab65c7112ba3d3c1f&access_token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IkRya21Mczl1akhnMkp1SE5CRm5vOERicXBJSSJ9.eyJhdWQiOiJ3b3BpL2thcm5vdmdyb3VwLW15LnNoYXJlcG9pbnQuY29tQGYxOWRjMGZiLTZjYzktNDVlNi04ZmQwLWRlZDRjMDcyMDNkZSIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMEA5MDE0MDEyMi04NTE2LTExZTEtOGVmZi00OTMwNDkyNDAxOWIiLCJuYmYiOiIxNjM4MTc0MTk1IiwiZXhwIjoiMTYzODIxMDE5NSIsIm5hbWVpZCI6IjAjLmZ8bWVtYmVyc2hpcHx1MDE1ODA2NkBrYXJub3Zncm91cC5jb20iLCJuaWkiOiJtaWNyb3NvZnQuc2hhcmVwb2ludCIsImlzdXNlciI6InRydWUiLCJjYWNoZWtleSI6IjBoLmZ8bWVtYmVyc2hpcHwxMDAzMjAwMTFiNjdhM2FkQGxpdmUuY29tIiwic2Vzc2lvbmlkIjoiYzg5NmQzZTAtN2FlZC00MDU5LTkwZDUtZDVkMjg5ZmI1MjYxIiwic2lnbmluX3N0YXRlIjoiW1wia21zaVwiXSIsInhtc19jYyI6IltcIkNQMVwiXSIsImlzbG9vcGJhY2siOiJUcnVlIiwiYXBwY3R4IjoiZTg2ZmRlNWNiZjY0NGYxYWI2NWM3MTEyYmEzZDNjMWY7TU1Jb2RUdWsyeFpwNFNMUjJSVDdxT0dxM2xNPTtEZWZhdWx0Ozs3RkZGRkZGRkZGRkZGRkZGO1RydWU7OzswOzc1Y2YwN2EwLWIwN2UtMzAwMC04N2YyLWJmNzIwNWNhMjYyMyJ9.dPjwFMGBPK9wcShHoq_-IIwKxIK5DwhlyS9WP7uARsitQg0l6q9I9653mr9ghrW1_SnAIYOUiKJljIIu9sncuJenhXaQo5uEJmZWCGveJJi2Km-kpTfh5abV7qBiDU1M673guFgwGbLYjm5jNrhJZJfzHFr1DlSFm_rpjZqLtTqEJqHgjLp3MDR3dGScD9Ki0ABsHMPsE1jvdGC4sCRMn35yZldQ-YMuLv4iONN5ajmXGvvz8JtnPQ-axVlpBTUaK_rT8rytGSYDZG-Sz6ursHTF1794UyuSNlfqVgXrlS7hcKtI3VByJ1E0SvGCiWbteDn3fHrN9jl2asQ7PSIItQ&access_token_ttl=1638210196759`
> 
> When this request succeeds everything is fine
 
Same problem here!

**Comment by JensMadsen** [comment]
This is related to https://github.com/OfficeDev/office-js/issues/2289 I think. 

Any updates from Microsoft? This Is really a problem for us.

**Comment by AkhileshShah-MS** [comment]
Hi! 
Apologies for the delay on updating this thread. We are aware of this issue on Word Online and team is actively working on fixing it. I will come back with an update on this soon. 
Please let me know if you are facing similar issue with any other platform apart from Word Online. 
Thanks!

**Comment by AkhileshShah-MS** [comment]
Adding @RuoyingLiang to help on this

**Comment by JensMadsen** [comment]
@AkhileshShah-MS Do have an update on this issue?

**Comment by RuoyingLiang** [comment]
Hi @JensMadsen , sorry for the late response. The issue has been fixed. Could you help to check if you are still encounter this issue?

**Comment by JensMadsen** [comment]
@RuoyingLiang It has actually been solved for some time (to the point where I re-enabled UI tests), but I have experienced the error this week again. Thats why I asked for an update. I think it is the same error but I have not investigated it in detail. In any case, when I opened this issue the addin would load 1 out of 10. It is way better now! Thanks

**Comment by RuoyingLiang** [comment]
@JensMadsen Did you recently update the add-in? Does the add-in disappear after the upgradation? 
Is this happened in Word Online?

**Comment by NickDarvey** [comment]
@RuoyingLiang

>Did you recently update the add-in? Does the add-in disappear after the upgradation?
Is this happened in Word Online?

I know you're asking @JensMadsen, but this is exactly what we see! When we deploy an update to our add-in, it disappears. If we rollback the update, it reappears.

**Comment by RuoyingLiang** [comment]
Thanks @NickDarvey Is this issue happens in online or windows or Mac?

**Comment by JensMadsen** [comment]
@RuoyingLiang I have only investigated it in Word online (this is how we currently run UI tests in our CICD pipeline). The manifest has not been updated for months. In this case the addin is uploaded using admin.micorsoft.com and deployed to our test user used in our CICD pipeline. I will give an update if I get reports on this on Windows Desktop and/or when the app is deployed from App Source.

**Comment by guliums** [comment]
Hi @NickDarvey , thanks very much for reporting the issue. Does "deploy an update to our add-in" means you upload a new manifest file from admin.micorsoft.com? May I know it disappears from user's ribbon or disappear from "Admin Managed" tab in Office Add-ins dialog? Does rollback the update means upload the old manifest file? Is it possible that the issue is in the new version of the manifest? Could you get a session id after the add-in disappears, that will be very helpful! Thanks very much.

**Comment by NickDarvey** [comment]
Hi @RuoyingLiang, @guliums. Sorry for the delay.

I mean we deploy a change to the webapp such as altering the `index.html` or `taskpane.js` which is loaded when the add-in is opened. There is no change to the manifest.

This was happening on Word Online.

If it helps you investigate, I did have a support request open, case 28927071, in which I recorded and shared HARs for diagnosis. It would include the session ID and many more details. (I have to admit I gave up on that support request and let it close as it was going around in circles.)

**Comment by NickDarvey** [comment]
I just tested and can see it occurring right now. Notably, we deployed an update just yesterday  (again, to the taskpane.js).

This request:
```
POST https://word-edit.officeapps.live.com/we/AddinServiceHandler.ashx?action=getAddIns&app=word&catalog=privatecatalog&clientCode=WAC_Word&clientVersion=16.0.0.0&corr=dcb60f42-f719-2f37-1797-bdf02f78adde&WOPIsrc=https://example-my.sharepoint.com/personal/me_example_com/_vti_bin/wopi.ashx/files/b39efc6ab00749abac853f877be32118&access_token=omitted&access_token_ttl=1645628160846
```

times out after one minute. No add-ins are listed in 'admin managed', my add-in doesn't show in the UI (even though it was showing before).

```json
"SessionId":"ECAA0454-DB3A-45B8-8752-8A610F14F2C7","UserId":"100320017467ac41"
```

**Comment by guliums** [comment]
Hi @NickDarvey , thanks very much for the details. Is there any error message showed in 'admin managed' while No Add-ins are listed? Will the add-in show up if you click the refresh in the Office Add-ins dialog?

**Comment by NickDarvey** [comment]
@guliums 

>Is there any error message showed in 'admin managed' while No Add-ins are listed?

No, just a loading icon and then 'no add-ins available' after the request times out.

>Will the add-in show up if you click the refresh in the Office Add-ins dialog?

No, just a loading icon and then 'no add-ins available' after the request times out. 😅

**Comment by guliums** [comment]
Thanks @NickDarvey for confirmation. 
@AkhileshShah-MS looks like the issue is similar to the original one that request AddinServiceHandler.ashx?action=getAddIns timeout. Could you confirm it is fixed or not?

**Comment by AkhileshShah-MS** [comment]
@RuoyingLiang I recall this issue was fixed months back by your team. Can you please look into why its happening again

**Comment by JensMadsen** [comment]
This is really bad at the moment so perhaps the status: fixed label should be removed

**Comment by AkhileshShah-MS** [comment]
@RuoyingLiang Please take a look into this.

**Comment by JensMadsen** [comment]
It is this request (I have removed access token etc from request below) which times out after 60 s:
```
https://euc-word-edit.officeapps.live.com/we/AddinServiceHandler.ashx?action=getAddIns&app=word&catalog=privatecatalog&clientCode=WAC_Word&clientVersion=16.0.0.0
```

**Comment by JensMadsen** [comment]
The request just succeeded :-) Did you fix something on your side @RuoyingLiang ?

**Comment by JensMadsen** [comment]
..... time out again

**Comment by JensMadsen** [comment]
@RuoyingLiang and @[AkhileshShah-MS](https://github.com/AkhileshShah-MS) Any news on this issue? We cannot deploy updates to our addin

**Comment by JensMadsen** [comment]
@AkhileshShah-MS any news on this issue?

**Comment by RuoyingLiang** [comment]
@JensMadsen, sorry for the late response. The corresponding team is investigating the issue and we will update here once it's fixed. Is this a random failure or constantly repro?

**Comment by JensMadsen** [comment]
@RuoyingLiang It happens randomly. I cannot figure out the pattern

**Comment by RuoyingLiang** [comment]
Thanks @JensMadsen . After investigation we suspect it's a new issue. Is that possible you could share the network trace for the latest repro?

**Comment by JensMadsen** [comment]
@RuoyingLiang I experienced this issue several times yesterday, but today I cannot reproduce it. I will try again later. When you say network trace what do you mean exactly? I can get you the request which fails?

**Comment by guliums** [comment]
Hi @JensMadsen I think it is Fiddler trace, you could refer to https://docs.microsoft.com/en-us/power-query/web-connection-fiddler for how to capture it. A screen shot of F12 developer tools network tab with failed request will also be helpful. Thanks for your support!
