### ISSUE TITLE
Office.js API - Add nested content control in word file

### ISSUE THREAD

**Issue by vimal-darji-ifour** [OfficeDev/office-js#2276]
## Office.js API - Add nested content control in word file

I am developing a plugin for Office Word, I want to add a feature that allows users to add content in hierarchical order in form of nested content control. 
```
        let wordContentControl:any;
        Word.run(async context => {
           
            const range = context.document.getSelection();
            range.clear();
            wordContentControl = range.insertContentControl();
            wordContentControl.tag = "NameTest";
            wordContentControl.insertText("Sample", 'End');
            wordContentControl.cannotEdit = false;
            wordContentControl.appearance = 'BoundingBox';

            wordContentControl.font.color = 'red';
            await context.sync()


        }).catch((error) => {
            console.log(error);
        });
        Word.run(async context => {
            var contentControlsWithTag = context.document.contentControls.getByTag('NameTest');
            // Queue a command to load the tag property for all of content controls.
            context.load(contentControlsWithTag, 'tag');

            // Synchronize the document state by executing the queued commands,
            // and return a promise to indicate task completion.
            return context.sync().then(function () {
                if (contentControlsWithTag.items.length === 0) {
                    console.log('No content control found.');
                }
                else {
                    return context.sync()
                        .then(function () {
                           
                            context.sync();
                            var ccs = context.document.contentControls;
                            
                            ccs.load("NameTest");
                            
                            console.log("Nr cc: " + ccs.items.length);
                            let cc = ccs.items[0];

                        });
                }
            });
        });
```

This is what I have done so far. but I am unable to find a way to add content control within/nested content control.
Your help would be much helpful for me.

![image](https://user-images.githubusercontent.com/39907946/143439750-88a14953-5a68-4060-8643-f8853026c4a4.png)

For additional information about JavaScript programming, see the [JavaScript at Microsoft](https://docs.microsoft.com/javascript/) community hub.

**Comment by chiz-ms** [comment]
Hi @vimal-darji-ifour, I tested and calling `insertContentControl` inside a content control should work:

    var contentControl = context.document.getSelection().insertText('outer\n', Word.InsertLocation.start).insertContentControl();
    contentControl.insertText('inner', Word.InsertLocation.end).insertContentControl();

![image](https://user-images.githubusercontent.com/19398640/143545286-2655600d-fe35-4964-a815-cc222f332786.png)

By the way, I've posted the same answer at https://stackoverflow.com/questions/70109638/office-js-api-add-nested-content-control-in-word-file. Please see if it works for you.
