### ISSUE TITLE
Not able to find the Id of date picker content control using office.js API

### ISSUE THREAD

**Issue by vmrathod** [OfficeDev/office-js#228]
when I try to fetch the Ids of all the content controls on document using below code

` var contentControls = context.document.contentControls;`
`context.load(contentControls, 'id,subtype,type');`

This code is fetching the all the content controls ids except those content controls shown as **date picker**.
Need a solution how to read the date picker content controls.

**Expected Behavior**

context.document.contentControls should read all the content controls on document.

**Current Behavior**
context.document.contentControls not able to read the date picker content controls

**Your Environment**
Platform: PC desktop
Host: Word
Office version number: Office 2016 build 1803
Operating System: Windows 10
Browser (if using Office Online): N/A

**Comment by JuaneloJuanelo** [comment]
currently the API only supports rich text content controls. please upvote a request in the OfficeDev uservoice channel

**Comment by KeyurPatel268** [comment]
@JuaneloJuanelo  If you get chance to look my stackoverflaw, could you please suggest us? 
https://stackoverflow.com/questions/52205026/word-2016-addin-office-word-js-can-update-document-run-time-after-remove-few-co
