### ISSUE TITLE
[Excel] CustomFunctions shouldn't automatically execute upon start of the workbook

### ISSUE THREAD

**Issue by knight-baron** [OfficeDev/office-js#2281]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

##CustomFunctions shouldn't automatically execute upon start of the workbook

That CustomFunctions Autorun is quite problematic as some users want to see the last data after pause streaming and close the workbook when they reopen it causing the last stored data to be lost because CustomFunctions automatically executed upon start of the workbook

**Comment by chiz-ms** [comment]
Hi @knight-baron, could you take a look and see if this issue is identical to #2220?

**Comment by knight-baron** [comment]
@chiz-ms  I'm sure this is the same problem.

**Comment by chiz-ms** [comment]
Thanks for the confirmation, @knight-baron! This would be a feature request so please feel free to go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) and vote for the existing feature request.

**Comment by knight-baron** [comment]
I'm sure this is the same problem.

**Comment by knight-baron** [comment]
thank you very much
