### ISSUE TITLE
Office.context.requirements.isSetSupported not available in Desktop Outlook Event Activation

### ISSUE THREAD

**Issue by barclayadam** [OfficeDev/office-js#2286]
I am unable to use `Office.context.requirements.isSetSupported` in an event based activation script on Desktop Outlook

## Your Environment

* Platform: PC Desktop
* Host: Outlook

## Expected behavior
That I could use `isSetSupported` to determine supported features, such as knowing 1.11 is supported and that I can stop using a workaround for the lack of onRecipientsChanged event in previous versions.

## Current behavior
An error of `TypeError: Unable to get property 'isSetSupported' of undefined or null reference` is thrown

## Steps to reproduce
In an event-based activation script, try to use the `Office.context.requirements.isSetSupported` method in Outlook on Windows

**Comment by exextoc** [comment]
What build of Outlook are you using? Support for the Mailbox requirement set for Office.context.requirements.isSetSupported is supported in builds >= 16.0.14729.10000. We currently have items in the backlog to add support for other requirement sets, and we unfortunately have no timelines to share at this point.

**Comment by barclayadam** [comment]
I'm using "Microsoft® Outlook® for Microsoft 365 MSO (Version 2110 Build 16.0.14527.20234) 32-bit".

I cannot see that build being available on beta channel or otherwise so cannot test it out. Is it right that the method to even try to test for support will not be available at all in earlier versions?

**Comment by exextoc** [comment]
Build 16.0.14729.10000 is the base build for the November release, which should be rolled out to the Beta Channel very soon. We are working on implementing this fix for previous builds (up to the September 2021 release).
