### ISSUE TITLE
Office.ribbon.requestUpdate steals focus from my TaskPane app

### ISSUE THREAD

**Issue by timbeese** [OfficeDev/office-js#2287]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

As part of my task pane add-in, I can take actions that cause our ribbon state to change.  When I call requestUpdate on the ribbon, my keyboard focus returns to the worksheet, even if I had it in the taskpane.  This is only an issue on the Excel web client.

## Your Environment
* Platform: Office on the web
* Host: Excel
* Operating System: Windows 10 - Version 21H1 (OS Build 19043.1387)
* Browser: Chrome (96.0.4664.45), Edge (96.0.1054.41)
 
## Expected behavior
I would expect my focus to remain in the taskpane when I am updating the ribbon.  It does do this for the desktop Excel client.

## Current behavior
My keyboard focus moves back to the worksheet.  I would prefer for the focus to stay in the taskpane.

## Steps to reproduce
1. Create a taskpane add-in that has a button on it.  That button should do the following code:
`         

        const enableButtons = {
          tabs: [
            {
              id: 'SAS.CustomTab',
              groups: [
                {
                  id: 'SAS.Group.Navigate',
                  controls: [
                    {
                      id: 'SAS.PageBackward',
                      enabled: true,
                    },
                    {
                      id: 'SAS.PageForward',
                      enabled: true,
                    },
                  ],
                },
              ],
            },
          ],
        };
        await Office.ribbon.requestUpdate(enableButtons);

`
2. Click in the taskpane to give it focus and tab to the button with the keyboard.
3. Press the space bar to click the button.  I would expect to be able to click this multiple times
4. Focus is returned to the worksheet if you're running in the web client.
5. Focus is retained on the task pane if you're running in the desktop client.

## Link to live example(s)
I attempted to reproduce with scriptlab, but the Office.ribbon.requestUpdate gave an error in the console when I tried to call it.

# Provide additional details
I'd be happy to have an MS Teams call to demonstrate the issue.  I don't have something public that I can share.

## Context
For keyboard users, if they are navigating through the app, it is a much better experience if their focus remains in the app unless they are taking an action that specifically sends them back to the worksheet.  In our case, we're trying to activate content in the app, but our ribbon update is causing them to lose focus in the place where we just sent them.

**Comment by preethikakiru** [comment]
Hi @timbeese, thanks for bringing attention to this issue! I'm currently looking into it and will come back with my findings soon. 
Thanks!
Best, 
Preethika

**Comment by preethikakiru** [comment]
@timbeese Would it be possible for you to share a screen recording of this scenario on Excel Online?

**Comment by timbeese** [comment]
![focus-issue](https://user-images.githubusercontent.com/16708768/145104106-6bd5a29e-a6fa-441c-92f2-d645c81e1ccf.gif)

When the selection is on a shape that our add-in inserted into the worksheet, we enable a couple of buttons on the ribbon (Update / Find Selection).  When we set focus over to our task pane, the selected shape in the worksheet becomes unselected, and the new selected cell is the last cell that was selected prior to selecting the shape.

Our add-in detects this change, and if we need to update the buttons on the ribbon, we call Office.ribbon.requestUpdate.  When this happens, the focus that we have on our tabs (Home / Reports / Data) goes away.

**Comment by preethikakiru** [comment]
Another quick question, for the above scenario what would the ideal behavior be?

**Comment by timbeese** [comment]
The ideal behavior would be that when we set the focus to an item in the taskpane that it would remain focused.  I understand if we do something to activate a sheet or select a cell that focus will go to the worksheet.  But simply changing the enabled state of the ribbon should not cause the focus to change.
