### ISSUE TITLE
Any actionable element not showing Hand Cursor in Mac Excel IDV add-in task pane.

### ISSUE THREAD

**Issue by ppagadala** [OfficeDev/office-js#2288]
# Any actionable items like Button, Hyperlink etc are not showing Hand cursor on hover of that element.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.55 (21111400)
* Operating System: MacOS Catalina
* Browser (if using Office on the web): No
 
## Expected behaviour
Hand Cursor has to be shown on mouse hover of the actionable elements

## Current behavior
Hand Cursor is not showing on mouse hover of the actionable elements.

## Steps to reproduce

1. Add any HTML actionable item in task pane app.
2. Launch app from the Ribbon
3. Mouse over on those elements

## Context
Issue is occurring only on Mac Excel IDV/Desktop app

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ppagadala** [comment]
Video recording for Reference


https://user-images.githubusercontent.com/11500788/144556348-2e319b4a-53f1-4950-be0f-543f7e9ddf72.mp4

**Comment by jargil** [comment]
@ppagadala - thanks for reporting this. Could you please provide a working sample we can use to reproduce and investigate? Preferably a gist we can put into Script Lab. Thank you.

If you try the same using Excel Web under Safari, are you able to reproduce the same?
