### ISSUE TITLE
Office AddIn stops working on word online

### ISSUE THREAD

**Issue by jonathanhotono** [OfficeDev/office-js#2289]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Word Online only
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Office Online
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome, edge
 
## Expected behavior
Office add-in should work on both word online and desktop.

## Current behavior
All office add-in stops working on word online on all of our tenants. The add-in still shows up on Word desktop and powerpoint as designed to be.

## Steps to reproduce
1. Deploy sample HelloWorld office add-in manifest.xml via admin.microsoft.com globally.
2. Open word online/any documents within sharepoint and office add-in would not show up
3. Open word desktop and the add-in would show up

Screenshot below on word online add-in area:
![image](https://user-images.githubusercontent.com/6864547/144986593-c2bb87a2-b7c7-4d77-8a2c-7b7725075d2f.png)
`https://auc-word-edit.officeapps.live.com/we/AddinServiceHandler.ashx?action=getAddIns&app=word&catalog=privatecatalog&clientCode=WAC_Word&clientVersion=16.0.0.0&corr=db413d39-d71e-aede-ccbe-6e686c68a5bb` seems to be not working:
![image](https://user-images.githubusercontent.com/6864547/144986687-b0e0ba63-02c1-441d-b140-936005d8b705.png)

While in word desktop, the add-in shows correctly, including Script Lab!
![image](https://user-images.githubusercontent.com/6864547/144986908-14d3eb7d-2ee6-44a8-874b-97f7e87fff7f.png)

Could be related to #2275

**Comment by shochdoerfer** [comment]
We have the same problem in our tenant. Addins are working fine in Excel and Powerpoint but don't seem to load in Word.

**Comment by jonathanhotono** [comment]
This problem has been around for a month now and been quite distruptive for our clients. I raised this issue with o365 support team and they told me its not within their responsibility to support. Can anyone from the team please respond?

**Comment by AkhileshShah-MS** [comment]
Hi Jonathan! Team is currently working on fixing the issue. We will update back soon.

**Comment by jonathanhotono** [comment]
@AkhileshShah-MS is this issue fixed? I am still unable to see the add-ins across all tenants on word online.

**Comment by AkhileshShah-MS** [comment]
Adding @RuoyingLiang to help with this

**Comment by AkhileshShah-MS** [comment]
@jonathanhotono we are actively working on fixing this. And will come back with an answer soon.

**Comment by cespujunk66** [comment]
Hi , we have had this issue for a while too but today it seems it disappeared. Did someone fix it ? 
Thanks

**Comment by shochdoerfer** [comment]
Works for me, too.

**Comment by preethikakiru** [comment]
Since it seems the issue has disappeared, I resolved the issue. 
Best, 
Preethika
