### ISSUE TITLE
Add functionality to set LinkToPrevious to Word Header/Footer sections

### ISSUE THREAD

**Issue by dgtllion** [OfficeDev/office-js#2292]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi Office.js team,

Is it possible to add functionality to set the "Link To Previous" to header/footer sections?

I see that it is possible in Office VBA but not in Office.js see link:
https://docs.microsoft.com/en-us/office/vba/api/Word.HeaderFooter.LinkToPrevious

Thanks!

**Comment by chiz-ms** [comment]
Thank you for proposing this feature request. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please see if your feature has already been requested or post a new request there.

**Comment by dgtllion** [comment]
Hi @chiz-ms,

I've looked there but there is nothing to find about that. 
Do i need to add a request there?

**Comment by chiz-ms** [comment]
Hi @dgtllion, please feel free to post a new request there for your feature.

**Comment by dgtllion** [comment]
@chiz-ms do you may be know how long it will take to get it done by you/Microsoft?
4 months ago i requested it there but its not even looked up by someone.

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/office-js-add-in-add-functionality-to-set-linktoprevious-to-word/idi-p/3033549

**Comment by chiz-ms** [comment]
Hi @dgtllion, the feature requests are considered when we go through our planning process. However currently we do not have a timeline to share.

**Comment by dgtllion** [comment]
Can you give an estimation? Is it for months or years to wait?

**Comment by RuizhiSunMS** [comment]
> Can you give an estimation? Is it for months or years to wait?

@dgtllion Sorry for having no release timeline at present. 
One way might help is to submit your request on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) as well. The priority will get higher and we will re-think our plan after getting votes.
Thanks.

**Comment by RuizhiSunMS** [comment]
I'm sorry but we don't have explicit timeline at present indeed....
We recognize your submit on the forum but it lacks of votes to support us re-plan the schedule.
