### ISSUE TITLE
Office JS – Excel Add-In Ribbon doesn't show in the toolbar after inserting our Excel Add-in (Stratum Excel Connector) from Office Store.

### ISSUE THREAD

**Issue by ThangaSperumal** [OfficeDev/office-js#2293]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

Our Add-in for excel (Office JS Add-In) which is inserted/downloaded from Office store (Stratum Excel Connector) does not work when using Excel 2016 64 bit version (Microsoft® Excel® 2016 (16.0.5239.1001) MSO (16.0.5215.1000) 64-bit) on Windows 10 PC. The same Excel Add-in works fine when inserted/downloaded from Office store using Office 2016 32 bit (Microsoft® Excel® 2016 MSO (Version 2110 Build 16.0.14527.20234) 32-bit), Office 2019, Office 365 versions and Office on the Web.

After I insert our Add-In, it automatically opens the “Get Stratum Data” pane without even selecting/clicking on any commands. We could not even select/click on any command as it does not show our Excel Add-In ribbon under the toolbar.

It appears inserting our Add-in (Stratum Excel Connector) from office store for some reason does not completely download all the needed files/folder under the users Office\16\WEF folder. I see only folders Resources, Icons and a folder with GUID but its missing these folders AddinInfo, AggregatedCache , AppCommands and CustomFunctions. Seeing this behavior only for Excel 2016 64 bit version. (See attached screenshot). Not sure this behavior is anything to do with the Runtime browser Engine (IE11) that has been used as part of Office 2016 64 bit version is causing this issue. But not seeing the same behavior on Office 2016 32bit version.

Also the Security Info window accessed from the “Get Stratum Data” pane shows only URL and SSL values, it’s not showing Source, Runtime and Version details (See attached screenshot)

Deleted the contents of the WEF folder, restarted the PC and reinserted the same Excel Add-in but still the same issue.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® 2016 (16.0.5239.1001) MSO (16.0.5215.1000) 64-bit
* Operating System: Windows 10 Pro
* Browser (if using Office on the web): ______
 
## Expected behavior

Expecting Excel on Office 2016 64 bit should show the Add-In Ribbon in the toolbar after inserting the Add-In from office store.

## Current behavior

Add-In ribbon does not show under the toolbar after inserting our published Office JS Excel Add-In from office store.

## Steps to reproduce

1.	Access Excel 2016 64 bit version.
2.	Select Menu option Insert/My Add-Ins to insert our Excel Add-In.
3.	Select Store and search for Stratum.
4.	Select and Add Add-In “Stratum Excel Connector”
5.	Verify the toolbar and check the Security Info Window.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] 
![Mssing Add-In Ribbon](https://user-images.githubusercontent.com/83717423/145077963-dd4793ba-f945-4ce4-8bca-fb5086d5b545.png)
![Users WEF folder](https://user-images.githubusercontent.com/83717423/145077987-0b3896ce-8c73-42e3-b7ec-e27d9524ee2e.png)
![Security Info window](https://user-images.githubusercontent.com/83717423/145078008-221d29c3-0e82-4a6e-a572-c2b988447eb9.png)

- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by chiz-ms** [comment]
Thank you for reporting this issue. @croicu could you take a look and see who should be the best contact for this? It looks related to activation or downloading from catalog.

**Comment by trigurl** [comment]
> # Provide required information needed to triage your issue
> Our Add-in for excel (Office JS Add-In) which is inserted/downloaded from Office store (Stratum Excel Connector) does not work when using Excel 2016 64 bit version (Microsoft® Excel® 2016 (16.0.5239.1001) MSO (16.0.5215.1000) 64-bit) on Windows 10 PC. The same Excel Add-in works fine when inserted/downloaded from Office store using Office 2016 32 bit (Microsoft® Excel® 2016 MSO (Version 2110 Build 16.0.14527.20234) 32-bit), Office 2019, Office 365 versions and Office on the Web.
> 
> After I insert our Add-In, it automatically opens the “Get Stratum Data” pane without even selecting/clicking on any commands. We could not even select/click on any command as it does not show our Excel Add-In ribbon under the toolbar.
> 
> It appears inserting our Add-in (Stratum Excel Connector) from office store for some reason does not completely download all the needed files/folder under the users Office\16\WEF folder. I see only folders Resources, Icons and a folder with GUID but its missing these folders AddinInfo, AggregatedCache , AppCommands and CustomFunctions. Seeing this behavior only for Excel 2016 64 bit version. (See attached screenshot). Not sure this behavior is anything to do with the Runtime browser Engine (IE11) that has been used as part of Office 2016 64 bit version is causing this issue. But not seeing the same behavior on Office 2016 32bit version.
> 
> Also the Security Info window accessed from the “Get Stratum Data” pane shows only URL and SSL values, it’s not showing Source, Runtime and Version details (See attached screenshot)
> 
> Deleted the contents of the WEF folder, restarted the PC and reinserted the same Excel Add-in but still the same issue.
> 
> ## Your Environment
> * Platform [PC desktop, Mac, iOS, Office on the web]: PC
> * Host [Excel, Word, PowerPoint, etc.]: Excel
> * Office version number: Microsoft® Excel® 2016 (16.0.5239.1001) MSO (16.0.5215.1000) 64-bit
> * Operating System: Windows 10 Pro
> * Browser (if using Office on the web): ______
> 
> ## Expected behavior
> Expecting Excel on Office 2016 64 bit should show the Add-In Ribbon in the toolbar after inserting the Add-In from office store.
> 
> ## Current behavior
> Add-In ribbon does not show under the toolbar after inserting our published Office JS Excel Add-In from office store.
> 
> ## Steps to reproduce
> 1. Access Excel 2016 64 bit version.
> 2. Select Menu option Insert/My Add-Ins to insert our Excel Add-In.
> 3. Select Store and search for Stratum.
> 4. Select and Add Add-In “Stratum Excel Connector”
> 5. Verify the toolbar and check the Security Info Window.
> 
> ## Link to live example(s)
> 1. 
> 2. 
> 3. 
> 
> # Provide additional details
> 1. 
> 2. 
> 3. 
> 
> ## Context
> ## Useful logs
> * [ ]  Console errors
> * [ ]  Screenshots
> * [ ]
>   ![Mssing Add-In Ribbon](https://user-images.githubusercontent.com/83717423/145077963-dd4793ba-f945-4ce4-8bca-fb5086d5b545.png)
>   ![Users WEF folder](https://user-images.githubusercontent.com/83717423/145077987-0b3896ce-8c73-42e3-b7ec-e27d9524ee2e.png)
>   ![Security Info window](https://user-images.githubusercontent.com/83717423/145078008-221d29c3-0e82-4a6e-a572-c2b988447eb9.png)
> * [ ]  Test file (if only happens on a particular file)
> 
> Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

Hello, can you please try a later build of Excel 64 bit.  The documentation says Add-in Commands requires build 16.0.6769+
https://docs.microsoft.com/en-us/office/dev/add-ins/design/add-in-commands#command-capabilities

Thanks Angela

**Comment by trigurl** [comment]
Hello, can you please try a later build of Excel 64 bit. The documentation says Add-in Commands requires build 16.0.6769+
https://docs.microsoft.com/en-us/office/dev/add-ins/design/add-in-commands#command-capabilities

Thanks Angela

**Comment by ThangaSperumal** [comment]
Hello Angela,

Thanks for your update.  This issue is happening only on Excel 2016 64 bit version and work fine on Office 2019 and Office 365 subscriptions.  I did some search looking for the Excel 2016 64 bit latest build but could not find the exact build/version number. Do you know the latest build number for the Excel 2016 64 bit version that I can upgrade to?

Thanks,
Thanga

**Comment by trigurl** [comment]
Hello, the article I sent you above has this:
Basically, make sure the digits after the 16.0 are > 6769.  The Excel 64 bit version you were using is 5239 so that is an older unsupported build.   Add-in Commands was introduced around that time frame, so verify the build.  The 32 bit Excel you said you were using build 14527, so that build is newer. 

**Supported platforms**
Add-in commands are currently supported on the following platforms, except for limitations specified in the subsections of Command capabilities earlier.

Office on Windows (build 16.0.6769+, connected to a Microsoft 365 subscription)
Office 2019 or later on Windows
Office on Mac (build 15.33+, connected to a Microsoft 365 subscription)
Office 2019 or later on Mac
Office on the web
