### ISSUE TITLE
Excel: RichText support

### ISSUE THREAD

**Issue by lucas-gismondi** [OfficeDev/office-js#2294]
Hi there, are there any plans to support RichText in the Excel API? As of right now it looks like I can only set formatting for the entire cell and not specific pieces of text within the cell. Thank you!

**Comment by chiz-ms** [comment]
Thank you for proposing this feature request. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please see if your feature has already been requested or post a new request there.

**Comment by lucas-gismondi** [comment]
done! https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/richtext-support-excel-js-api/idi-p/3033874#M531

**Comment by andrewtsybulia** [comment]
bump :)

**Comment by XuanZhouMSFT** [comment]
Thanks for waiting and help posted the feature request. After careful consideration, our team has decided to not do this feature in short term. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.
