### ISSUE TITLE
Office.context.mailbox.item undefined when switching between inline replies with pinned task pane

### ISSUE THREAD

**Issue by milankonir** [OfficeDev/office-js#2295]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft 365 MSO (Version 2110 Build 16.0.14527.20234) 32-bit 
* Operating System: Windows 10
* Browser (if using Office on the web): N/A
 
## Expected behavior

The `Office.context.mailbox.item` should be available when `ItemChanged` event triggers. 

## Current behavior

Inline reply - pinned compose task pane triggers `ItemChanged` event before `Office.context.mailbox.item` is available.

## Steps to reproduce

1. Create compose task pane add-in that adds `ItemChanged` event handler
```
Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, () => {
  Office.context.mailbox.item.subject.getAsync(result => console.log(result.value));
});
```
2. Go to your inbox and hit reply
3. Open the add-in and pin the task pane
4. Switch to another item in the inbox and hit reply
5. The cached task pane will display and will trigger `ItemChanged` event immediately
6. Call to `Office.context.mailbox.item` will crash due to item being null / undefined.

## Link to live example(s)
I was unable to reproduce with Script Lab, there seems to be some display between the task pane being displayed and the `ItemChanged` event triggering

# Provide additional details
Our add-in guards every call to Office API with `await Office.onReady();`

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by milankonir** [comment]
We have found out that the when going through this scenario the `ItemChanged` triggers twice:

First time when user leaves inline reply of the first email - `Office.context.mailbox.item` is null at that point
Second time when user enters the inline reply of the second email - `Office.context.mailbox.item` is defined at that point.

I don't know if it is intentional to trigger `ItemChanged` event when user navigates away from an inline reply, but we can easily work around that by checking `Office.context.mailbox.item` presence and only trigger the subsequent logic if it's defined.

**Comment by exextoc** [comment]
I believe this is the default behavior in Desktop Outlook, for which we have documented a guideline to always check for null before doing any work in the `ItemChanged` event handler, on this [page](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/pinnable-taskpane).

![image](https://user-images.githubusercontent.com/28549921/145747779-4e642cfd-9577-4563-aad3-4dceddc0f0fb.png)

However, if this is a separate issue, let us know.

**Comment by milankonir** [comment]
Thanks for linking the docs, as suggested, we now check for the presence of Item in the change handler.
