### ISSUE TITLE
How to set Word lineSpacing in (real) points ? 

### ISSUE THREAD

**Issue by waveheart** [OfficeDev/office-js#2296]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I set linespacing in what the  documents write, but the fact is the paragraph's linespacing is set by grid unit, not by points
i found this in [documents](https://docs.microsoft.com/zh-cn/javascript/api/word/word.paragraph?view=word-js-preview#lineSpacing)
 ```
lineSpacing


Gets or sets the line spacing, in points, for the specified paragraph. In the Word UI, this value is divided by 12.
````
### example

```
await Word.run(async (context) => {
  // Adjusts line spacing.
  context.document.body.paragraphs.getFirst().lineSpacing = 20;

  await context.sync();
});
```

## i expectd the paragraph's linespacing would be 12, in points!

![image](https://user-images.githubusercontent.com/25602259/145317858-0ac743a6-1773-4e8e-a61b-de73b8348f56.png)

## and another fact is, if i set the paragraph's linespacing as 30 points , i print the value in console, it's -30, its an negative value.

![image](https://user-images.githubusercontent.com/25602259/145317611-c9af7a89-eee0-4f9a-a089-cc7f35548369.png)

#### so how about set the value to a negative value in word ui? I tried that , a dispointed result is , it throw an error ! TT
 
![image](https://user-images.githubusercontent.com/25602259/145317653-e0cebbcc-ae3b-455d-a24c-554fe3ecee64.png)

**Comment by chiz-ms** [comment]
Thank you for reporting this issue regarding `Paragraph.lineSpacing` API. The behavior inconsistency with documentation is confirmed and tracked in our backlog as ADO#5649619. Regarding the feature request to support setting line spacing in points, please go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) and see if your feature has already been requested or request a new feature.

**Comment by Axios1027** [comment]
This problem still exists, I set the line spacing to 30 points through code, but it shows up as multi-block 2.5 on word. In fact, the fixed value of 30 points and multi-line spacing 2.5 do not look consistent.
![image](https://user-images.githubusercontent.com/45395511/223665014-cda07878-6415-4d11-9adc-dc8ff11d1fc6.png)
![image](https://user-images.githubusercontent.com/45395511/223665550-f2a89bb1-1827-45b3-b3f9-f1571a638a86.png)
