### ISSUE TITLE
OfficeRuntime.auth.getAccessToken()  is failing 

### ISSUE THREAD

**Issue by abdulkareemnalband** [OfficeDev/office-js#2298]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
We have an issue with our SSO implementation for our Word and Outlook add-in. 
 
We have updated our Application manifest as instructed here.

```xml
<WebApplicationInfo>
                <Id>1064f7e4-a9e2-467d-8d42-f45cc59f145d</Id>
                <Resource>api://app.boarddecisions.com/1064f7e4-a9e2-467d-8d42-f45cc59f145d</Resource>
                <Scopes>
                  <Scope>openid</Scope>
                  <Scope>profile</Scope>
                </Scopes>
</WebApplicationInfo>
```
 
 

But, SSO is not working, and we get below error in the workflow

 

When `OfficeRuntime.auth.getAccessToken()` we are getting an as followed
```json
{
    "name": "API Not Supported",
    "message": "The identity API is not supported for this add-in.",
    "code": 13000
}
```
## Your Environment

* Platform [PC desktop,]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Word,Outlook
* Office version number: Microsoft 365 MSO (Version 2110 Build 16.0.14527.20270) 64-bit
* Operating System: Windows 10
* Browser (if using Office on the web): ______
 
## Expected behavior
`OfficeRuntime.auth.getAccessToken()` should return token

## Current behavior
 `OfficeRuntime.auth.getAccessToken()`  is throwing
 following error
 ```json
{
    "name": "API Not Supported",
    "message": "The identity API is not supported for this add-in.",
    "code": 13000
}
```

## Steps to reproduce
[manifests.zip](https://github.com/OfficeDev/office-js/files/7683964/manifests.zip)
https://appsource.microsoft.com/en-us/product/office/WA104380444?tab=DetailsAndSupport
https://appsource.microsoft.com/en-us/product/office/WA104380449?tab=DetailsAndSupport
We have provided above manifests to appsource team and they have approved them.

When I side load above manifests it works
But when I use one from appsource it does not

**Comment by RuoyingLiang** [comment]
Thanks for reaching us. @mattgeim could you help to take a look this SSO question?

**Comment by mattgeim** [comment]
@abdulkareemnalband you mentioned that the sideloaded manifest worked fine but not the ones from AppSource.  Is this still the case? 

Was this an initial submission to AppSource or an update to enable SSO for an existing listing?

**Comment by abdulkareemnalband** [comment]
An update to enable SSO
