### ISSUE TITLE
CDN Issue - Source Maps for ariatelemetery 404 Response

### ISSUE THREAD

**Issue by LanceEa** [OfficeDev/office-js#23]
Looks like the CDN version is having an issue loading source maps for ariatelemetry. I'm guessing since this a Production endpoint that we wouldn't want to load sourcemaps. But, I wanted to bring it to your attention just encase you hadn't seen it yet.

<img width="1028" alt="screen shot 2017-11-01 at 12 08 40 pm" src="https://user-images.githubusercontent.com/8103374/32287121-bfb83124-befd-11e7-8d1f-1ca96e63ed1a.png">

Regards,
Lance

**Comment by Zlatkovsky** [comment]
Thanks!  I will pass it along to the team.

**Comment by EBMike** [comment]
this still happens as of 1.1.8 if using unpkg (ie. "https://unpkg.com/@microsoft/office-js/dist/office.js")

**Comment by Zlatkovsky** [comment]
@wandyezj, passing this to you to investigate (and to check whether it's still happening -- the double-slash issue should be gone now, so perhaps it's not anymore?)

**Comment by lindalu-MSFT** [comment]
@wandyezj Can you follow up and let us know if this is in the backlog or if there's a fix?

**Comment by smaremanda** [comment]
closing this issue. @wandyezj - please reopen or follow up again if this is still an issue.
