### ISSUE TITLE
Custom Functions Accessing Sheet Properties

### ISSUE THREAD

**Issue by PeterTippett** [OfficeDev/office-js#230]
Currently testing this function as want to store information between sheet opening.

An example is storing the token for API access.

This isn't working for Custom functions but works for the normal add-ins. Think this is related to context?

BUT I can access the url property in this - Office.context.document.url

Note. Testing with the Excel On-line version

Sample Code

function getProperty(name) {
    var setting = Office.context.document.settings.get(name);
    console.log("ReadSettings: "+ name+", "+setting);
    if (setting == ""){
        return null;
    } else {
        return setting;
    }
}

function setProperty(name, data) {
    console.log("setSetting: "+name+":"+data);
    Office.context.document.settings.set(name, data);
    Office.context.document.settings.saveAsync(function (asyncResult) {
        console.log('set settings saved with status: ' + name + " - "+ data + ", " + asyncResult.status);
    });
}

**Comment by PeterTippett** [comment]
Accessing the new Runtime so can use the Asycn Function, but not working.

This line from the documentation seems to imply that this only works with Addins that have normal UI activity. This implies that can now have custom functions as part of the normal Addins.

Only custom functions within an add-in will use the new JavaScript runtime that's described in this article. If an add-in includes other components such as task panes and other UI elements, in addition to custom functions, these other components of the add-in will continue to run in the browser-like WebView runtime. Additionally:

**Comment by keyur32** [comment]
Hey Peter,  

Given custom functions execute during Excel's calculation chain, we want to make sure the APIs we expose can work consistently across all platforms.  Last week, we updated the runtime on Excel Insiders: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime.  

On Desktop and eventually MAC versions, you will only have access to a the APIs described there.  We're still working on guidance to expose other OfficeJS APis (plan is to expose any read operations, but any set/save operatations that change the document will not be supported through the custom functions runtime).

Can you describe the scenario you were trying to accomplish?

**Comment by PeterTippett** [comment]
The UI side of the Addin sets a document ID that is stored using the `Office.context.document.settings.set(name, data); `  This is linked in my backend to data that is stored for that document. This allows to fully track this document to my backend.

I then want to access this to get the document ID I have created for the custom functions so this pulls the right data from my system for this document.  I can't use `Office.context.document.url` to extract an ID of the document as this only works on the online versions, as need a way to identify the document across all platforms. 

This needs to work across sessions and also when they open in different environments.

I developing on Mac and then testing across all platforms.  Currently, this is extracting accounting data as a function using a custom function like =GLBALANCE(AccountID) which then connects to my backend which then pulls the data from the accounting system they are connected to, currently XERO. 

I'm already doing this with GoogleSheets and have users. One user has this linked to five different companies pulling in financial data for 12 months do 2,000 calculations in 3 seconds using custom functions.  The Excel version is much faster (>10x) as have my code working with the online version using the ID from the url which works across all platforms. Now need an "id" that works on the Desktop versions.

I don't need the "set.Item" ability, but need the "get.Item" and this works across all platforms.

What has been documented for the "runtime" implies that I have access to this, but then is no working example. The code sample I can't get to work and even went through the "stock-ticker" example and inserted it and it didn't work.

**Comment by keyur32** [comment]
Hey, coming back to this one, we do have some features in our backlog to allow access to our APIs for Custom Functions. Using this as an open call - what other scenarios would you want?

**Comment by PeterTippett** [comment]
Keyur

I’ve place this project on hold currently and moved onto a Cyber Security product which is using the Xero code I've already done.  Will likely look at open sourcing the code of what I’ve done in the future once I have my new venture up and running which will be in the next few months.

www.cyberbund.com <http://www.cyberbund.com/>

**Comment by keyur32** [comment]
Closing this issue out, as this feature is in our backlog and is currently being worked on..
