### ISSUE TITLE
 Office.context.mailbox.item.sessionData only available in beta library, doesn't persist between launch events and taskpane

### ISSUE THREAD

**Issue by carlosb1504** [OfficeDev/office-js#2300]
# Provide required information needed to triage your issue

 Office.context.mailbox.item.sessionData which was advertised as becoming GA in the [Outlook 1.11 requirement set](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.11/outlook-requirement-set-1.11). Seems to first of all only available in the beta version of the office.js library, and also doesn't persist data between launch events and taskpane.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop, Outlook Web Access
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft 365 MSO (Version 2111 Build 16.0.14701.20204) 32-bit 
* Operating System: Win10
* Browser (if using Office on the web): Chrome Version 96.0.4664.45 (Official Build) (64-bit)
 
## Expected behavior

Expected the Office.SessionData API to be fully available in the generally available (non-beta) version of the Office.js library. Also expected data that was pushed into this object during an `onMessageCompose` LaunchEvent, to be persisted and available for retrieval inside taskpane code in the same add-in.

## Current behavior

Attempting to use sessionData method such as [getAsync()](https://docs.microsoft.com/en-us/javascript/api/outlook/office.sessiondata?view=outlook-js-1.11&preserve-view=true#getAsync_name__callback_) result in the following message:

`Sys.FeatureNotEnabled: The feature sessionData.getAsync, is only enabled on the beta api endpoint`

This goes away if we update our reference to the beta version of the libary and we can then use the get/set methods etc. However, when we 'set' an attribute on the sessionData object during an `onMessageCompose` launch event. This is then unretrievable later via the taskpane. Behaviour which is important to our use case and we were told in another ticket would be supported. Instead we see the below 'key not found' error:
![image](https://user-images.githubusercontent.com/47693383/145436646-a6df2a51-a2d3-43bd-a3cc-09a0d3bc12b7.png)

## Steps to reproduce

1. unpack the attached test add-in to a folder, run npm install
2. run `npm run build:dev`
3. run `npm run dev-server`
4. install the manifest 'manifests\outlook-sessiondata-test-manifest.xml' to a local instance of Outlook at the same version specified in the triage info of this ticket.
5. Open a new email, see that the subject is set by the add-in. This indicates the sessiondata has also been set ('itemId': [message item id])
6. Open the taskpane using the provided button
7. Observe the error above in the console

[outlook-sessiondata-test.zip](https://github.com/OfficeDev/office-js/files/7686862/outlook-sessiondata-test.zip)

**Comment by JuaneloJuanelo** [comment]
thanks for reporting this Carl, there might be delay on fully releasing the feature.

i think you are reporting 2 aspects on this email.

1. Can you please verify the latest build you have?  16.14701.20226 is the latest for win32 and you seemed not to be on it.
2. you mention data persisted with  sessionData  is not available for both taskpane and js runtime, i am assuming this a behavior you are experiencing on the beta builds?  this sounds like a bug we need to fix, will try to repro internally. thanks !

**Comment by carlosb1504** [comment]
Hi, 

1. 16.0.14701.20204 was the latest available to me on the current channel as of yesterday. Having checked this morning there is indeed an update to 14701.20226 which I have tried and the behaviour appears to be the same. 
2. The Outlook build is the current channel, however I mentioned that the SessionData API appeared to be unavailable at all using the `https://appsforoffice.microsoft.com/lib/1/hosted/office.js` reference. I was only able to use it at all using `https://appsforoffice.microsoft.com/lib/beta/hosted/office.js` and it's using this version of the library that I saw the behaviour described above.

Hope that clarifies things.

Cheers

**Comment by exextoc** [comment]
We have fixed this issue internally and are working on applying the fix to previous builds.
Internal tracking bug : Office 5654146.

**Comment by JackTheDane** [comment]
Do you have any ETA of when the fix might be released to production that you can share?

**Comment by exextoc** [comment]
This is currently is fixed in Nov builds and forward. As for older builds, we are still in the process of porting it over and will share the exact build numbers once we have more details

**Comment by exextoc** [comment]
SessionData is available at the production endpoint now. 
Still working on getting the updated build numbers with the fix.

**Comment by exextoc** [comment]
The fix build is 16.0.14701.20290.
And we have updated the hosted JavaScript libraries as well.
