### ISSUE TITLE
[Outlook] multi-line text sent within <pre> tags being transformed and original <pre> tags are removed

### ISSUE THREAD

**Issue by joshuayuen99** [OfficeDev/office-js#2301]
# Provide required information needed to triage your issue
Multi-line email bodies that are surrounded by a single set of `<pre>` tags are instead transformed into a multi-line email with separate `<pre>` tags surrounding each line of the body. There are now also empty `<o:p>` tags inserted at the end of each line too.

## Your Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: 2111 (Build 14701.20226 Click-to-Run)
* Operating System: Windows 10 Pro N version 21H1 (OS build 19043.1348)
 
## Expected behavior
Text/HTML within `<pre>` tags are left untouched as before, and the original surrounding `<pre>` tags remain as is.

## Current behavior
Email bodies containing multi-line text surrounded by a single set of `<pre>` tags are transformed on-send (viewing the body source before sending shows the correctly formatted text as written/inserted), resulting in:
- the original `<pre>` tags being completely removed
- each line within the original `<pre>` tags being surrounded with newly inserted `<pre>` tags of their own
- each line within the original `<pre>` tags having `<o:p></o:p>` tags inserted at the end, just before the newly inserted `</pre>` tag

## Steps to reproduce

1. Insert multi-line text into the email body surrounded by a single set of `<pre>` tags
2. Send the email
3. View the source of the sent email

# Provide additional details
This behavior was not the case previously, and used to behave similarly to how the Office on the web version still does, and as described in the expected behavior section above.

## Context
We rely on the behavior of text/HTML within `<pre>` tags remaining untouched to retain the integrity of S/MIME messages that are signed with our add-in. To elaborate, we insert S/MIME signed/encrypted text via our add-in directly into the email body to enable us to send/receive similarly formatted emails with add-ins for other email clients (such as Thunderbird for now).

## Useful logs
Relevant snippet of email body before sending:
![image](https://user-images.githubusercontent.com/56708104/145495702-68ce4ac5-fb8f-48e6-8118-93f14c9ad50a.png)

Relevant snippet of received email body:
![image](https://user-images.githubusercontent.com/56708104/145495780-fb9eb348-9ee5-44e5-a930-ce5f77e52bc6.png)

**Comment by exextoc** [comment]
In Desktop Outlook, we use Word underneath the covers to render emails. This means that we do not have control of how the email will be formatted. In general, Word will modify the HTML to optimize it for rendering, which is most-likely what is happening in your case.

We also have documentation line about the behavior `Office.context.mailbox.item.body` APIs. In general, `setAsync` and `getAsync` are not idempotent. See documentation [here](https://docs.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-preview#getAsync_coercionType__options__callback_). So, unfortunately, you should not rely on them for your scenario.

**Comment by joshuayuen99** [comment]
Thanks for letting us know. Is it possible there's some undocumented API or some other way to directly set/get the email body without being touched by the extra Word renderer?

**Comment by exextoc** [comment]
There unfortunately isn't.
