### ISSUE TITLE
Event activation capability vs DefaultMinVersion

### ISSUE THREAD

**Issue by milankonir** [OfficeDev/office-js#2302]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.13801.21050
* Operating System: Windows 10
* Browser (if using Office on the web): N/A
 
## Expected behavior

Add-in that contains `<ExtensionPoint xsi:type="LaunchEvent">` should be able to load in Outlook clients that do not support requirement set 1.10 and the launch events just should be ignored.

## Current behavior

The add-in fails to load.

## Steps to reproduce

1. Create add-in that defines `<ExtensionPoint xsi:type="LaunchEvent">` and specifies minimal version lower than 1.10, e.g. 
```
<Requirements>
  <Sets DefaultMinVersion="1.8">
    <Set Name="Mailbox" />
  </Sets>
</Requirements>
```
2. Install the add-in into PC desktop Outlook client that does not support requirement set 1.10 yet.
3. Open task pane
4. Add-in does not load

## Link to live example(s)

# Provide additional details
We would expect to be able to use the new launch event features for users on recent Outlook versions while still maintaining compatibility with older versions.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Thanks for reporting this.
The Event-Based Activation should not impact the taskpane. Does your add-in work when you remove the Event-Based Activation elements from the manifest?

Also, when the add-in fails to load, what error message do you get?
Do you have a manifest you can share with us assuming there are no privacy concerns at the moment?

**Comment by milankonir** [comment]
We have verified, that removing the Event-Based Activation from the manifest fixes the problem. There is no error displayed to user, the task pane just remains blank.

We have limited debugging capability as our dev boxes are on latest Microsoft 365 clients and we have only seen the problem impacting our customers. Debugging with customers is tricky as they are on legacy Edge WebView that requires installing additional tools.
Do you have any suggestion what diagnostics we should try to collect?

Does Microsoft provide any documentation that would allow developers to troubleshoot problems on older versions of Outlook clients, e.g. do you provide virtual images with older Outlook clients pre-installed?

@exextoc  Is it possible to send the manifest your way without posting here at the public tracker?

**Comment by exextoc** [comment]
To send us your manifest, please create a private repo in GitHub, at-mention exextoc and we will be able to access it and check your manifest.

Just to clarify, it seems that your customers are able to reproduce this issue, and they are using the legacy Edge WebView for running add-ins. So, for the environment you provided earlier on for this issue (Office version number = 16.0.13801.21050 and Operating System = Windows 10), is that for your impacted customers or your dev boxes? If it is for your impacted customers, and their Windows 10 version is greater than 1903, they should be able to install WebView2 to resolve this issue. Here's a link to our browser support matrix : https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

**Comment by milankonir** [comment]
I have published the manifest into https://github.com/milankonir/office-manifest and gave you access if you still need it altho you have a repro.

The Office and Windows version provided in the issue description are from our impacted customer (where the issue is reproducible). They are indeed on the legacy Edge WebView.

Our work around for the time being is that we also distribute an alternative version of manifest that does not contain launch events. We can also suggest the WebView2 upgrade.

But is this something that will also be fixed for the legacy WebView? We have non IT users installing the add-in and it's challenging to explain Outlook versioning / webview to them - we usually have to troubleshoot the issue with them and this does not scale well.

**Comment by exextoc** [comment]
Thanks for sharing your manifest.
We are actively investigating this issue now and we will update this thread with our findings.

**Comment by exextoc** [comment]
Office build 16.0.13801.21050 is from the Semi-Annual Channel (SAC).
A new build was recently released to this channel, and we are unable to reproduce this issue.
Can you check if updating to the latest build on SAC resolves this issue?

**Comment by milankonir** [comment]
What is the version this has been fixed in? Was it fixed for legacy Edge rendering engine or does it rely on rendering engine being upgraded to Chromium Edge?

We can see multiple users on versions newer than `16.0.13801.21050` that are still on legacy Edge rendering engine. Will it work for them?

![image](https://user-images.githubusercontent.com/72383088/151385579-64d7d070-7f2d-4171-be27-7fdeea75e0ba.png)

**Comment by exextoc** [comment]
The latest build for the Semi-Annual Channel (SAC) is 16.0.14326.20738, which is currently deployed to 100%. Customers on the older builds will have to move to this newer build. During our tests, we were unable to reproduce this issue on the latest SAC build, so the issue appears "fixed" in newer builds. We disabled the Chromium Edge sandbox and the taskpane add-ins were rendered and worked successfully using both legacy Edge and Internet Explorer as the underlying browsers.
