### ISSUE TITLE
Outlook Desktop, link title is broken after sending emails

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#2303]
In an Outlook add-in for compose mode, we use the Office.context.mailbox.item.body.setSelectedDataAsync() method to place HTML markup into the body of an email being composed. If HTML contains a link with the title attribute, the title looks broken in incoming/received emails.

## Your Environment
* Platform: PC desktop, Office on the web
* Host: Outlook
* Office version number: 2011 (Build 14701.20226 Click-to-Run)
* Operating System: Windows 10 21H1
* Browser (if using Office on the web): Chrome (96.0.4664.93)
 
## Expected behavior
Link title should look correctly, as specified in the code.

## Current behavior
Link title is enclosed in quotation marks and contains additional characters.

## Steps to reproduce
Create a new email in Outlook Desktop and execute the code below:

`    function imageWithLink() {`
`      var htmlData = `
`        '<p>' +`
`          '<a href="https://microsoft.com" title="Link Title" target="_blank">' +`
`            '<img width="200" height="100" src="https://i.imgur.com/WJXklif.png">' + `
`          '</a>' + `
`        '</p>';`
`      Office.context.mailbox.item.body.setSelectedDataAsync(htmlData, { coercionType: 'html' }, function (asyncResult) {`
`        console.log('done', asyncResult);`
`      });`
`    }`

Send the email to yourself. Then, sign-in to Outlook Online using for example the Chrome browser, select the received test email and check the title of the link. I have attached a screenshot, please see it below.

## Provide additional details
I'm not sure, but it looks like Outlook Desktop is breaking the HTML markup.

## Useful logs
- [ x ] Screenshots
![link_title](https://user-images.githubusercontent.com/28924916/145575054-f13f712a-ed98-4c64-bc8b-5a49e6f5049d.png)

**Comment by exextoc** [comment]
Thanks for reporting this.
I am able to reproduce this issue. The presence of the `target` attribute of the `a` element results in an extra `t` in the formatted HTML.

Desktop Outlook uses Word for formatting and processing HTML. And Word will sometimes modify the HTML for better rendering. That modification could be the reason for this issue.

Here's the modified HTML after I tried your scenario, even before I sent the email:

```
<a href="https://microsoft.com/" title="Link Title t ">  
    <span style='color:blue;mso-no-proof:yes;text-decoration:none;text-underline:none'>`
        <img border=0 width=200 height=100 id="_x0000_i1025" src="https://i.imgur.com/WJXklif.png">
    </span>
</a>
```

**Comment by exextoc** [comment]
This issue was found to involve another product team that owned the code. After careful consideration, it was decided to not fix this issue in the short term. We recommend you to upvote or create a new  [Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue we will re-activate as needed.
