### ISSUE TITLE
Contextual add-ins failing to load page when clicked in OWA O365

### ISSUE THREAD

**Issue by westconference** [OfficeDev/office-js#2306]
Contextual Outlook add-in using a regular expression is failing to launch view when clicking highlighted text in OWA. An error is output to the developer console indicating a problem with manifest caching.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: OWA when viewed in Firefox, Chrome on both Mac and Windows.
* Host [Excel, Word, PowerPoint, etc.]: Outlook OWA Office 365
* Office version number: N/A
* Operating System: Windows and Mac
* Browser (if using Office on the web): Seen in Firefox and Chrome at least.
 
## Expected behavior
On being clicked, the highlighted area of the text should load the add-in's specified resource in a dialog under the text.

## Current behavior
An error is thrown in the console and no dialog appears.
```
Uncaught TypeError: n.get_TypeString is not a function
    at Object.cache (ManifestCacheProvider.ts:70)
    at H.insertOsfControl (OsfControlAdapter.ts:95)
    at refCallback (OsfHostContainer.tsx:55)
    at Cc (react-dom.production.min.js:255)
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Jo (react-dom.production.min.js:122)
    at Tc (react-dom.production.min.js:248)
    at fc (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
```
* Exception in console after clicking contextual add-in highlighted text. react-dom.production.min.js:123 

```
const sourceLocation: string =
        addinCommand.get_TypeString() === ('Preinstalled' as ExtensionType) &&
        addinCommand.get_ConsentState() !== ConsentStateType.Consented
            ? buildConsentUrl(addinCommand.get_RequestedCapabilities())
            : addinCommand.get_EntryPoint();
```
Excerpt of method with failing line of code from ManifestCacheProvider.ts (OWA Microsoft code presumably).

## Steps to reproduce

Create a contextual add-in with a basic regular expression match.
e.g.
```
<ExtensionPoint xsi:type="DetectedEntity">
              <Label resid="menuLabel" />
              <SourceLocation resid="detectedEntityFuncFile" />
				<Rule xsi:type="ItemHasRegularExpressionMatch"
					PropertyName="BodyAsPlaintext"
					RegExName="Example"
					RegExValue="example"/>
            </ExtensionPoint>
```
* Contextual add-in extension point definition to match on the word example.
Install the add-in.
View an email in OWA that has the word 'example' and confirm that it is highlighted.
Open developer console and click the word 'example' that has been highlighted.
Observe that add-in dialog does not appear and that an error is logged to the console.

# Provide additional details
Note this was last seen to be working around 8th of November 2021.

## Context
Breaks my contextual add-in in OWA as the dialog with the add-in UI will not open.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding Contextual Add-in. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
@westconference We have fixed the issue regarding Contextual Add-in. Kindly test it and let us know your feedback, please.
