### ISSUE TITLE
[Outlook]  'OnMessageSend ' and 'OnAppointmentSend' was not triggered

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#2308]
I tried below steps to testing 'OnMessageSend ' and 'OnAppointmentSend' on Outlook application add-in.

https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough

But it seems that the event was not triggered.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2110 (14527.20276)
* Operating System: Win 10
* Browser (if using Office on the web): NA
 
## Expected behavior
The 'OnMessageSend ' and 'OnAppointmentSend' event should be triggered.

## Current behavior
The 'OnMessageSend ' and 'OnAppointmentSend' event was not  triggered.

## Steps to reproduce
If necessary I can share you the demo.

**Comment by exextoc** [comment]
This feature is currently in preview, and only available if you are in the Insiders Fast Channel. (it appears the documentation on the feature may have mistakenly linked to Preview Events, which is not relevant to this feature, I will look into clarifying/fixing this)

Otherwise, if you believe you are in the channel you can provide your manifest to check it over.

**Comment by SWei1234** [comment]
Here is the manifest file please check it.
[manifest.zip](https://github.com/OfficeDev/office-js/files/7718171/manifest.zip)

**Comment by exextoc** [comment]
To clarify you need to be in Office Insiders: https://insider.office.com/en-us/join/windows
And in the BETA channel, NOT the Current Channel.

**Comment by ElizabethSamuel-MSFT** [comment]
@SWei1234 We've updated the "How to preview" section to clarify about the required channel (PR https://github.com/OfficeDev/office-js-docs-pr/pull/3139). Do give it a try and if you're still facing issues with trying to preview the feature, let us know by opening a new issue or asking us to reactivate this one.

Thanks.

**Comment by SWei1234** [comment]
Hi @ElizabethSamuel-MSFT 
I created a new issue for this problem: https://github.com/OfficeDev/office-js/issues/2342
This issue will be closed.
Thanks
