### ISSUE TITLE
Dialog sizing is incorrect

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/office-js#231]
When using Dialog API (Office.context.ui.displayDialogAsync), height and width provided in the configuration object are switched and the resulting dialog has the passed in width as height and passed in height as width.

## Expected Behavior
The width of the dialog should correspond to the width property of the configuration object sent as an argument to the function. Sam with the height parameter.

## Current Behavior
When using Dialog API (Office.context.ui.displayDialogAsync), height and width provided in the configuration object are switched and the resulting dialog has the passed in width as height and passed in height as width.

## Steps to Reproduce, or Live Example
Install [Script Lab](https://aka.ms/scriptlab).
From ScriptLab ribbon, click "Code"
In Code task pane, click menu on top left then "Import"
Paste this snippet URL https://gist.github.com/4e01c9763b9af35d9268d3a4ed567c98
On ScriptLab ribbon, click "Run"
In Run task pane, click "Open Wide Dialog" and observe that dialog is tall, not wide
In Run task pane, click "Open Tall Dialog" and observe that dialog is wide, not tall

## Context
Our dialog are all sized incorrectly due to this regression.

## Your Environment

* Platform PC desktop
* Host Excel
* Office version number: 1807
* Operating System: Windows 7

**Comment by JuaneloJuanelo** [comment]
known issue, we are currently fixing this.

**Comment by ATrogolo** [comment]
Hello @JuaneloJuanelo, 
when this bug will be released? 

Thanks in advance,
Andrea

**Comment by ATrogolo** [comment]
@JuaneloJuanelo or @dmahugh : any news about this issue?

**Comment by JuaneloJuanelo** [comment]
@ATrogolo  this is already fixed.. back to normal.
