### ISSUE TITLE
Word `context.sync` performance issues with 100's of Content Controls

### ISSUE THREAD

**Issue by els-ts** [OfficeDev/office-js#2311]
Our add-in is quite often creating 100's and sometimes 1000's of Content Controls elements across many pages in Word document. We've noticed that general performance suffer proportionally to the number of those elements. Based on the requirements of the text contents we're using either `insertText` or `insertHtml` methods and we've also noticed that the later is causing even worse results that the former.

This is common across platforms and environments.

## Your Environment

* Platform: N/A
* Host: Word
* Office version number: N/A
* Operating System: N/A
* Browser (if using Office on the web): N/A
 
## Expected behavior

I would expect that `context.sync` is taking maximum up to few hundreds of milliseconds and not tens or hundreds of seconds. 

## Current behavior

Simple script from the example bellow can take up to few minutes to complete, which is way more than unacceptable from user's point of view.

## Steps to reproduce

Execute the bellow examples in the Script Lab using either `insertText` or `insertHtml` option, pressing *Run* button few times and observe results in the developer console (those results may not be visible in Script Lab console):

```typescript
$("#run").click(() => tryCatch(run));

const numberOfControls = 1000;

async function run() {
  await Word.run(async (context) => {
    console.time('controls');
    for (let i = 0; i <= numberOfControls; i++) {
      const selection = context.document.getSelection();
      const paragraph = selection.insertParagraph('', Word.InsertLocation.after)
      const control = paragraph.insertContentControl();
      control.appearance = Word.ContentControlAppearance.boundingBox;

      // change this line to test different insert functions
      // control.insertText(`${i}`, Word.InsertLocation.replace);
      control.insertHtml(`${i}`, Word.InsertLocation.replace);
    }
    console.timeEnd('controls');

    console.time('sync');
    await context.sync();
    console.timeEnd('sync');
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}
```

**Comment by chiz-ms** [comment]
Thank you @els-ts for reporting this issue regarding Word API performance. The issue has been tracked as ADO#5676469 in our backlog.

**Comment by ubabukos** [comment]
Hi @chiz-ms following the suggestion by MS to batch content controls into smaller chunks, we did notice a performance improvement albeit a small one, when adopting this approach. We plan to implement a solution similar to the code snippet below into the add-in as the __temporary workaround__ so please continue to work on a much better, long term solution to improving this particular performance issue.

```javascript
$("#with-batching").click(() => tryCatch(withBatching));

const numberOfControls = 1000;
const CHUNK_MARKER = 10;

async function withBatching() {
  await Word.run(async (context) => {
    let controls: Word.ContentControl[] = [];

    console.time("controls");
    for (let i = 0; i <= numberOfControls; i++) {
      const selection = context.document.getSelection();
      const paragraph = selection.insertParagraph("", Word.InsertLocation.after);
      const control = paragraph.insertContentControl();
      control.appearance = Word.ContentControlAppearance.boundingBox;

      // change this line to test different insert functions
      // control.insertText(`${i}`, Word.InsertLocation.replace);
      control.insertHtml(`${i}`, Word.InsertLocation.replace);
      controls.push(control);
    }
    console.timeEnd("controls");
    
    console.log("batch in groups of: ", CHUNK_MARKER);
    console.time("with batching...");
    batchProcessContentControls(context, controls, CHUNK_MARKER);
    console.timeEnd("with batching...");
  });
}

// Basic logic for batch processing content controls before call `context.sync` 
const batchProcessContentControls = async (
  context: Word.RequestContext,
  controls: Word.ContentControl[],
  divisor: number,
): Promise<boolean> => {

  if (!changes.length) return true;
  const batchedChanges = changes.splice(0, divisor);
  await context.sync();

  return batchProcessContentControls(context, changes, divisor);
};

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}
```

**Comment by els-ts** [comment]
In addition to what @ubabukos said, some view on the metrics:

No: of content controls in the document | Average times with existing implementation | Average times with batches of 10 | Average times with batches of 25 | Average times with batches of 50
-- | -- | -- | -- | --
40 | 1.305s | 1.571s | 1.266s | 1.288s
80 | 2.320s | 2.715s | 2.384s | 2.407s
160 | 5.322s | 5.272s | 5.046s | 4.903s
320 | 18.839s | 15.430s | 10.113s | 11.016s
640 | 45.463s | 29.917s | 24.772s | 25.787s
1280 | 109.005s | 72.983s | 105.297s | 58.899s

The times got bit better with batching, but the numbers are still way below acceptable 😞

**Comment by els-ts** [comment]
@chiz-ms - are there any updates on this from your side?

**Comment by JHJ-MS** [comment]
HI @els-ts, we are continuing to follow up. Thanks.

**Comment by adarshsosale** [comment]
@JHJ-MS, @chiz-ms  It's been over a year, has there been any updates regarding this? I'm facing a more severe issue on a document with ~85 content controls, where context.sync() keeps taking more time on each run and very quickly hits 5+ minutes.
I've already opened an issue here - https://github.com/OfficeDev/office-js/issues/3565

**Comment by YijunMS** [comment]
@adarshsosale @els-ts @ubabukos Thanks for your attention to this issue. Recently we deployed some changes for **Word Online**, which would improve performance of heavy content control scenarios.

**Comment by jipyua** [comment]
hi @els-ts @ubabukos for Word desktop and mac, we profiled the provided code above and found that the bottleneck is at insertHtml side, we have made some improvement and please update to latest M365 office version to have a further try. thanks.

**Comment by els-ts** [comment]
Thank you for looking into it. I'll close this for now, and if we find more issues, we'll create a new ticket 👍🏻
