### ISSUE TITLE
Streaming function does not compile in Javascript add-in, but works in typescript?

### ISSUE THREAD

**Issue by gar3thjon3s** [OfficeDev/office-js#2313]
I generated a new custom functions project using the yo office generator, and choose javascript as the language. If I edit the clock function to be (note the matrix string response):

```
/**
 * Displays the current time once a second
 * @customfunction
 * @param {CustomFunctions.StreamingInvocation<string[][]>} invocation Custom function invocation
 */
function clock(invocation) {
  const timer = setInterval(() => {
    const time = currentTime();
    invocation.setResult([[time, "hi"]]);
  }, 1000);

  invocation.onCanceled = () => {
    clearInterval(timer);
  };
}
```

When I run `npm start` I get a compilation error complaining about the StreamingInvocation signature:

`Invalid type: CustomFunctions.StreamingInvocation (18,12)`

If I generate a new custom functions project using yo office generator, and choose typescript as the language, I can edit the clock function to be:

```
/**
 * Displays the current time once a second.
 * @customfunction
 * @param invocation Custom function handler
 */
export function clock(invocation: CustomFunctions.StreamingInvocation<string[][]>): void {
  const timer = setInterval(() => {
    const time = currentTime();
    invocation.setResult([[time, "hi"]]);
  }, 1000);

  invocation.onCanceled = () => {
    clearInterval(timer);
  };
}
```

It works as expected, spilling the time and "hi" into the next cell.

Am I doing something wrong with the function declaration with the Javascript version, or is just not supported?

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Office 365 version 2111 (Build 14701.20226)
* Operating System: Windows 10 Enterprise OS Build 19042.1348
 
## Expected behavior
I expect the JS version to behave as the TS version does.

## Current behavior
The JS version fails to compile.

## Steps to reproduce
See description above.

## Context
Experimenting with Office.js custom functions to see how they work.

**Comment by igor-ribeiiro** [comment]
Hello @gar3thjon3s, thanks for raising this issue! 
I can indeed reproduce the issue locally, so it is a real problem.

Both projects generated from yo office (typescript and javascript) use the same tool to interact with Custom Functions which are the [custom-functions-metadata-plugin](https://github.com/OfficeDev/Office-Addin-Scripts/tree/master/packages/custom-functions-metadata-plugin) and [custom-functions-metadata.](https://github.com/OfficeDev/Office-Addin-Scripts/tree/master/packages/custom-functions-metadata)

I investigated the test cases of these projects and there are no tests for the `string[][]` as a parameter. 
When I add these tests, they fail, so there is a problem with JS handling these cases.

For now, I will open an internal bug for us to investigate further on why this is happening.

**Comment by sdbarrington** [comment]
Hi, did this ever get fixed? or is the fix to switch to typescript?

**Comment by igor-ribeiiro** [comment]
> sdbarrington

Unfortunately, this did not get fixed yet. You can try using typescript until then

**Comment by sdbarrington** [comment]
Ok thanks will try that. Are there any tips or tricks to convert the functions to typescript or a tutorial on it you know of? many thanks in advance!

**Comment by igor-ribeiiro** [comment]
@sdbarrington There is not really a tutorial for it, but you can try to look at the example repositories template using typescript and base yourself on that: https://github.com/OfficeDev/Excel-Custom-Functions.
You can also create a new typescript custom function project using `Yo Office`: https://github.com/OfficeDev/generator-office

**Comment by millerds** [comment]
There is a fix for this in the pipeline now and should be released in the next month.
