### ISSUE TITLE
Word Content Control Id is not persisted / consistent in Word online

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js#2315]
We were using the contentcontrol.id to tie in to our application specific metadata.  This appears to be consistent in Word desktop (and also it used to be consistent in Word online).

## Steps to reproduce
Programatically create a content control in word online
Save the created content control id to the document (we use the metadata)
Open the document, and read the id from the content control

## Expected behavior
Content Control Id matches what was stored in metadata

## Current behavior
Content Control seems to have a new Id

**Comment by xiruatms** [comment]
hi, @theboyknowsclass , thanks for reaching out to us.

I've tried but can't repro the issues you posted. Will you please help to provide a little more information?
1. Which word online are you using?
2. The code snippet you're using will be much helpful.
3. What's the exact steps to repro the issue?

The more information we got, the sooner we might help.

Thanks.

**Comment by theboyknowsclass** [comment]
this can be closed, i no longer see the issue. thanks!

**Comment by chiz-ms** [comment]
Thanks for the confirmation @theboyknowsclass. I'll close the issue.
