### ISSUE TITLE
Internet Explorer retirement in June 2022 vs. Office Add Ins in MSI Installs

### ISSUE THREAD

**Issue by ndeeH** [OfficeDev/office-js#2318]
IE will be retired in June 2022 by windows update. (IE will only be available via Edge internal IE Mode)
Short question:
**_What browser will be used from June 2022 by Office AddIns when called from an Office MSI install?_**
(I think only "up-to-date" installs of office via M365 will benefit from WebView2 = Edge Chromium)

**Comment by ElizabethSamuel-MSFT** [comment]
@ndeeH Apologies for the late response. Can you check if [Browsers used by Office Add-ins](https://docs.microsoft.com/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) answers your question?

Thanks.

**Comment by jargil** [comment]
This is our official documentation around runtimes supported:
https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

**Comment by ndeeH** [comment]
> @ndeeH Apologies for the late response. Can you check if [Browsers used by Office Add-ins](https://docs.microsoft.com/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) answers your question?
> 
> Thanks.

Yes - that seems complete.
