### ISSUE TITLE
Document custom properties not save in Office 365 for Windows

### ISSUE THREAD

**Issue by codecrasher99** [OfficeDev/office-js#232]
## Expected Behavior
The document custom properties are not getting saved via office web add-in when the add-in loads in Office 365 for windows. The same code works fine in Office 365 online. The [stackoverflow query](https://stackoverflow.com/questions/52062904/document-custom-properties-not-save-in-office-365-for-windows) contains details about the problem.

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by JuaneloJuanelo** [comment]
answered on stack.
