### ISSUE TITLE
Cannot see the add-in after adding xml from exchange under admin-managed.

### ISSUE THREAD

**Issue by g138** [OfficeDev/office-js#2320]
I have added the manifest.xml file to the exchange, but the user under the tenant id cannot see them.

Does it take time to upload? 

Also, the manifest contains `<MobileFormFactor>`. I cannot see it on my iPhone aswell.

**Comment by ElizabethSamuel-MSFT** [comment]
@g138 Are you still facing this issue? If so, can you let us know how you added the manifest to Exchange? Which of the [deployment options](https://docs.microsoft.com/office/dev/add-ins/publish/publish) did you use?

Thanks.
