### ISSUE TITLE
Outlook when schedule a meeting and delete it, when try to schedule again - the location is not updated

### ISSUE THREAD

**Issue by leahsilver1** [OfficeDev/office-js#2322]
# Provide required information needed to triage your issue
I schedule a google-meet meeting and delete then meeting from the location and body.
I then schedule another appointment at Google-Meet.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2111 Build 16.0.14701.20254
* Operating System: Windows
 
## Expected behavior
when I schedule the second time, the meeting will be appear in the location

## Current behavior
 the meeting is written only in the body and not in the location.

## Steps to reproduce

1.  schedule a google-meet  meeting in outlook
2. delete the meeting from  body and location
3. schedule  google-meet meeting again

## Useful logs
![image](https://user-images.githubusercontent.com/93973062/146957790-cf04b2a5-f117-4517-bec6-6c6d4f38bb4b.png)

**Comment by LuyiH** [comment]
Hi, thank you for your feedback. 
For this Outlook function question, I would suggest raising this question in the "Outlook - Help - Connect Support", there you can find the experts of Outlook product, to help you solve this issue
![20211223094541](https://user-images.githubusercontent.com/96099540/147175218-c94e69d0-4bbb-4f0e-9123-041f251222bb.png)
.
