### ISSUE TITLE
Detect changes for the whole document

### ISSUE THREAD

**Issue by AlexeyVanyukevich** [OfficeDev/office-js#2324]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Environment
* Platform Mac OS
* Host Word
* Office version number: 16.56
* Operating System: Big Sur 11.4
 
## Expected behavior
I would like to insert one or more content controls and then create bindings to subscribe for data changes on the whole document 

## Current behavior
I was able to do so, but from a couple of minutes the taskpane closes

## Steps to reproduce
This how I'm trying to inset content controls with bindings and add data change event handler for them

`return Word.run(async context => {
            const sections = context.document.sections;
            const paragraphs = context.document.body.paragraphs;

            sections.load(['body/paragraphs/tableNestingLevel', 'body/paragraphs/isListItem']);
            paragraphs.load(['tableNestingLevel', 'isListItem']);
            await context.sync();

            const paragraphsItems = paragraphs.items;
            const sectionsItems = sections.items;

            const chunks: Word.Paragraph[][][] = [];
            const sectionsParagraphsCount = sectionsItems.reduce((acc, section) => acc + section.body.paragraphs.items.length, 0);
            const sectionsParagraphs = sectionsItems.map(x => x.body.paragraphs.items).concat(paragraphsItems.slice(sectionsParagraphsCount));
            for (const { sectionParagraphs, sectionIndex } of sectionsParagraphs.map((sectionParagraphs, sectionIndex) => ({ sectionParagraphs, sectionIndex }))) {
                let index = 0;
                chunks[sectionIndex] = [];
                while (index >= 0 && index < sectionParagraphs.length) {
                    const iterationParagraphs = sectionParagraphs.slice(index);
                    const elementIndex = iterationParagraphs.findIndex(x => x.tableNestingLevel || x.isListItem);
                    if (elementIndex >= 0) {
                        const key = iterationParagraphs[elementIndex].tableNestingLevel ? 'tableNestingLevel' : 'isListItem';
                        const paragraphsSlice = iterationParagraphs.slice(0, elementIndex);
                        chunks[sectionIndex].push(paragraphsSlice);
                        const endElementIndex = iterationParagraphs.slice(elementIndex).findIndex(x => !x[key]);
                        const elementParagraphs = iterationParagraphs.slice(elementIndex, endElementIndex >= 0 ? elementIndex + endElementIndex : undefined);
                        if (endElementIndex >= 0) {
                            index += elementIndex + endElementIndex;
                        } else {
                            index = endElementIndex;
                        }
                        chunks[sectionIndex].push(elementParagraphs);
                    } else {
                        chunks[sectionIndex].push(iterationParagraphs);
                        index = -1;
                    }
                }
            }

            const normalizedChunks: Word.Paragraph[][][] = [];
            for (const { sectionChunks, index } of chunks.map((sectionChunks, index) => ({ sectionChunks, index }))) {
                normalizedChunks[index] = [];
                let tmp: Word.Paragraph[] = [];
                for (const chunk of sectionChunks) {
                    tmp.push(...chunk);
                    if (tmp.length > 1000) {
                        normalizedChunks[index].push([...tmp]);
                        tmp = [];
                    }
                }
                if (tmp.length) {
                    normalizedChunks[index].push([...tmp]);
                }
            }

            const ccsIds: string[] = [];
            for (const sectionChunks of normalizedChunks) {
                for (const chunk of sectionChunks) {
                    if (chunk.length) {
                        const slice = chunk.slice();
                        const range = slice[0].getRange().expandTo(slice[slice.length - 1].getRange());
                        const cc = range.insertContentControl();
                        const title = this.generateId();
                        ccsIds.push(title);
                        cc.title = title;
                        cc.appearance = Word.ContentControlAppearance.hidden;
                        await context.sync();
                    }
                }
            }
            await Promise.all(ccsIds.map(ccsId => {
                return new Promise<void>((res, rej) => {
                    Office.context.document.bindings.addFromNamedItemAsync(ccsId, Office.BindingType.Text, { id: ccsId },
                        result => {
                            if (result.status == Office.AsyncResultStatus.Succeeded) {
                                const binding = result.value;
                                binding.addHandlerAsync(Office.EventType.BindingDataChanged, result => {
                                    console.log('update');
                                }, result => {
                                    if (result.status === Office.AsyncResultStatus.Succeeded) {
                                        res();
                                    } else {
                                        rej();
                                    }
                                })
                            } else {
                                rej();
                            }
                        });
                })
            }));
        });`

# Provide additional details

You can use document that I attach to reproduce the issue
[data-change-issue.docx](https://github.com/OfficeDev/office-js/files/7761955/data-change-issue.docx)

**Comment by AlexeyVanyukevich** [comment]
I think I found the cause of the problem. it seems like the sidebar crash occurs after inserting the content control. adding it is successful, but the sidebar crashes after a while

**Comment by AbidRahman-MSFT** [comment]
Hey @AlekseyVanyukevich - please refer to the following gist that adds a binding to a content control for the first paragraph. You can use a similar concept to create a content control that encapsulates the entire document. 

https://gist.github.com/AbidRahman-MSFT/e437f4b4610c917872a5c3d6e00ac911

Let me know if that helps.
