### ISSUE TITLE
Exception thrown when trying to access SlideMaster shapes in PowerPoint

### ISSUE THREAD

**Issue by angelmedina262** [OfficeDev/office-js#2328]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

On PowerPoint online, we are trying to access the SlideMaster shapes of a simple presentation. We call `load` for each of the properties and for each of the shapes so that we can read them. A minimal sample code is below:

```
$("#run").click(run);
function run() {
  PowerPoint.run(async (context) => {
    try {
      console.log("1. Loading slide masters");
      context.presentation.slideMasters.load();
      await context.sync();

      const slideMasters = context.presentation.slideMasters.items;
      console.log("slideMasters:", slideMasters.length);

      console.log("2. Loading slide master's shapes");
      const firstSlideMaster = slideMasters[0];
      firstSlideMaster.shapes.load();
      await context.sync();

      console.log("3. Getting shapes info");
      const shapes = firstSlideMaster.shapes.items;
      console.log("shapes:", shapes.length);
    } catch (e) {
      console.error(e);
    }
  });
}
``` 

We tested on both PowerPointAPI Beta and 1.1 versions.

## Your Environment

* Platform: Office on the web
* Host: PowerPoint
* Office version number: Office Online (build 16.0.14815.40505), PowerPointApi BETA and release 1
* Operating System: Windows 10 64-bits
* Browser (if using Office on the web): Microsoft Edge
 
## Expected behavior

The SlideMaster shapes are loaded and we can read each of their properties.

## Current behavior

We are getting a GeneralException when we try to load the shapes ` firstSlideMaster.shapes.load()`.

## Steps to reproduce

1. Copy the code above and paste it into the Script Lab on PowerPoint Online. Make sure you have a presentation with a valid Slide Master.
2. Run the script and open the console.

# Provide additional details

1. The same sample code above can be executed in the PowerPoint desktop version with no problem. It seems to be a problem specific to the online version.

## Useful logs

![image](https://user-images.githubusercontent.com/96616735/147347630-0cc37e7c-2b7d-44df-8558-848a45ed3a67.png)

**Comment by Wenjun-Gong** [comment]
Thanks for reporting the issue @angelmedina262 . Assign to @lliu113 to take a look.

**Comment by lliu113** [comment]
Assigning to @ononder for investigation

**Comment by yauheni-p** [comment]
@ononder  Any updates here?
