### ISSUE TITLE
Document.getFilePropertiesAsync method fails in unsaved Excel document

### ISSUE THREAD

**Issue by codecrasher99** [OfficeDev/office-js#233]
Document.getFilePropertiesAsync method does not return a success when invoked for an unsaved Excel document. It works fine if the excel is in a saved state. Is this a bug or is this missing in the Excel API. The stackoverflow [query](https://stackoverflow.com/questions/52100183/document-getfilepropertiesasync-method-fails-in-unsaved-excel-document) contains details about the problem.

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by codecrasher99** [comment]
Examining the asyncResult.status seems to be a crude workaround for the issue.

asyncResult.status === Office.AsyncResultStatus.Succeeded

However this does not mean that the issue is fixed.

**Comment by codecrasher99** [comment]
Reopening the issue

**Comment by ztdan4ik** [comment]
Hi there
Any news?

Excel 1912, `getFilePropertiesAsync` throws internall error

**Comment by lumine2008** [comment]
it would be great if you share us the snippet for us to repro this issue. thanks a lot

**Comment by lumine2008** [comment]
I'm going to close this issue for now, please reactivate if you're still seeing this. If you can provide us the snippet or gistto help us test that would be extremely helpful. Thanks!

**Comment by bagulin** [comment]
@lumine2008 I have the same issue for Excel only (in Word code works fine)
code to reproduce:
```
  <body>
  <div id="error">
    Error Log
  </div>
  <script type="application/javascript">
    const debugLog = document.getElementById('error');
    var interval = setInterval(function() {
      Office.context.document.getFilePropertiesAsync(function(res) {
        if ((res.status === Office.AsyncResultStatus.Succeeded)) {
          debugLog.innerText += '\n done'
          clearInterval(interval);
        } else {
          debugLog.innerText += '\n error';
        }
      })
    }, 1000)
  </script>
</body>
```
