### ISSUE TITLE
set cell.value="xxx" multiply,contentcontrol were deleted.

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#2330]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

1、Add a ContentControl to Table
2、set ContentControl .removeWhenEdited = false
3、set TableCell.value = "aaaa" above 3 times
4、ContentControl were deleted
![9](https://user-images.githubusercontent.com/3182964/147457898-a185d5ca-afc4-4970-b563-6c4ff398d538.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __PC desktop____
* Host [Excel, Word, PowerPoint, etc.]: __Word____
* Office version number: ___office 2019 16.0.10380.20037___
* Operating System: ___Windows 10___
* Browser (if using Office on the web): ___IE11___
 
![1](https://user-images.githubusercontent.com/3182964/147458104-14082903-9f8c-420e-98d4-97878c95d35c.png)

**Comment by chiz-ms** [comment]
Hi @hengchengfei, is this the same issue as #1143? I've already reopened that issue based on your comment there.

**Comment by hengchengfei** [comment]
@chiz-ms not the same error.
#1143 Error: "Invalid Parameters"
#2330  Error：ContentControl deleted (ContentControl.removeWhenEdited = false)

**Comment by AbidRahman-MSFT** [comment]
Hey @hengchengfei - what is the expected behavior here? Is the content control being unexpectedly deleted when you are changing the value of a table cell in the content control?

**Comment by hengchengfei** [comment]
> Hey @hengchengfei - what is the expected behavior here? Is the content control being unexpectedly deleted when you are changing the value of a table cell in the content control?

Yes,I want to change the value of table cell in ContentControl，but the ContentControl  is being unexpectedly deleted.
