### ISSUE TITLE
Word: paragraph.search not working with tabs

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/office-js#2331]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

In the Word API the paragraph.search does not work with soft new lines (shift+enter in the Word application); \t or \u000b in the string. However, Word online search functionality works if match Case = False

## Your Environment
Word Online
Word
Chrome
 
## Expected behavior
Be able to search string that includes vertical tabs / soft newlines. These are often used in Word documents

## Current behavior - Steps to reproduce
*In Word online search function i.e. ctrl+f*
- With this test document [demo (2).docx](https://github.com/OfficeDev/office-js/files/7780567/demo.2.docx) 
- highlight text (which contains a soft newline)
- ctrl+f
- search in word finds the string in the document IFF match case = false

In my addin using the office js Word API

- get paragraphs (there is only a single one)
- paragraph.search(<content of paragraphs>)
- no search result. I have tried: all combinations of `matchCase`, `IgnorePunct`, `IgnoeWhitespace`. I have tried to replace `\v` and/or `\u000b` with `''` and/or `' '`. but no luck. 

I have the same issue with horizontal tabs i.e. `\t`. 

## How this affects our app 

We use the search functionality to identify substring in paragraphs from the Word document. If we cannot identify substrings which include tabs the core functionality of our addin does not work.

**Comment by Wenjun-Gong** [comment]
@JensMadsen , do you see this issue only for Word Online, or also for other endpoints (win32, mac)?

**Comment by JensMadsen** [comment]
Dear @Wenjun-Gong . Thank you for a swift reply. I have created a demo in script lab https://gist.github.com/JensMadsen/7c39ac800e435018bcfede4ed44a17da that you can use with the attached test document above. The same problem exists with normal tabs (\t). I have not tested with window desktop due to holiday and corona. I will try to get my hands on a windows computer later today! However, I guess that the same problem exists on Windows. Before reporting this yesterday I had implemented a hack some weeks ago that partly solved the problem (I realized that the problem was more severe yesterday) and as far as I remember this was also reported on windows installations.

**Comment by RuoyingLiang** [comment]
@JensMadsen , thanks for the details. Open a BUG 5696095 to track this issue. Will reply here once we have update.
