### ISSUE TITLE
In new email switching between account does not trigger the onNewMessage Flow

### ISSUE THREAD

**Issue by vdboots** [OfficeDev/office-js#2334]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop, Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.57
* Operating System: Mac, Windows 11
 
## Expected behavior
If you have multiple accounts setup in your outlook. and open a new email and then switch between the accounts. Expected is that it removes the signature from one account en sets the signature of another account.

## Current behavior
When switching it removes to signature of the old account. But it does not trigger the new one.

## Steps to reproduce
1. Add two accounts to a single outlook setup
2. Open a new email from a single outlook.
3. In the new mail switch to another account where you have a different signature.

## Context
We have customers with multiple tenants, or multiple accounts in tenants. they would like to use the signatures in these setups.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Wenjun-Gong** [comment]
Hi @vdboots , thanks for reporting this issue. Are your customers using an JS add-in for the signature, or the default signature feature in Outlook?

**Comment by vdboots** [comment]
An office js signature. And IT is reproducable with the demo Outlook addinOp 29 dec. 2021 03:50 schreef Wenjun Gong - MSFT ***@***.***>:
Hi @vdboots , thanks for reporting this issue. Are your customers using an JS add-in for the signature, or the default signature feature in Outlook?

**Comment by exextoc** [comment]
Hey @vdboots,

From what you have described, this issue seems similar to #2211 . If so, that's already in our backlog and we are working on that. Unfortunately, we have no timelines to share at this point. Internal tracking ID: 5256718
