### ISSUE TITLE
range.InsertContentControl() not working on certain parts of a document, only on Office 365 Word Online, desktop is working

### ISSUE THREAD

**Issue by tomprod** [OfficeDev/office-js#2336]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome latest
 
## Expected behavior
Inserting a content control should work consistently accross platforms (office online <> office desktop)

## Current behavior
When i run my example code to insert a content control on a sentence on page 3/8 of the example document, it doesn't work (generalException occured) on office word online, selected text is as follows : 
![image](https://user-images.githubusercontent.com/65723479/147767999-fd360ba9-002a-489c-ae05-24dab2b153a6.png)

![image](https://user-images.githubusercontent.com/65723479/147796419-76d386f6-d2d8-4963-ab0e-fdc380ea1862.png)

Other hints i am aware of :
- the document was converted from doc to docx then converted to the most recent version of docx (file -> convert), then i worked on it successfully on desktop and not successfully on office word online
- if i copy and paste all the contents of the document to a new one, everything works just fine on office word online. The problem seems to have only something to do with that particular .docx (and probably others that will be used with my addin) 

## Steps to reproduce
1. select the text "exceptionnel" on page 3/8 of the example document
2. run my example code 

## Link to live example(s)
Document : https://teamwebexpert-my.sharepoint.com/:w:/g/personal/devext_teamwebexpert_onmicrosoft_com/EdUVu_Zm4d9OsoDw1xJFgykBfUObYp7WhDvR78cFRNJVqQ?e=CuHpkf
Scriptlab gist : https://gist.github.com/tomprod/32195f6e135085a06cb1db9b7c808da2

## Context
I am trying to populate data with content controls who have a tag to each of them, and what i need to do is first transform formulas to content controls, so i can populate data in them and refresh data in them when needed. This works just fine on desktop, only that on office online, page 3/8 of the document doesn't want content controls, only on office word online, and i just don't understand why

## Useful logs
- [x] Console errors
- [x] Screenshots
- [x] Test file (if only happens on a particular file)

**Comment by Wenjun-Gong** [comment]
Thanks for reporting the issue. Add @RuoyingLiang to take further look.

**Comment by xiaoyuMS** [comment]
Hi @tomprod 

I would like to share you my investigation.
It is by-design that we can't insert a content control in a not-fully-supported paragaph. (Paragraph becomes not-fully-supported when it contains items which are not supported in Word Online, such as shape, shading...) 

For this paragraph where we can't insert a content control in selected text.
**paragraph in 3/8 page**
![image](https://user-images.githubusercontent.com/90585978/147815487-8623b755-f08b-4492-b92b-3a330cb10502.png)


We could see in the xml file that there is a shading element in this paragraph.
**document.xml**
![image](https://user-images.githubusercontent.com/90585978/147814265-bdffa8cf-2179-46b7-a32b-458d45d9e2d5.png)

Paragraph shading is not supported in Word Online, so this paragraph becomes not-fully-supported.
**And It works after i removed the shading of this paragraph.**

This could also explain the second hint you are aware of, there is no shading in the new document where you paste the content  .
**document.xml**
![image](https://user-images.githubusercontent.com/90585978/147816279-0d190c95-c10e-43dc-afe6-0e3b02084f4b.png)

**Comment by tomprod** [comment]
Hey, thank you so much for sharing this, then it's not really a bug, i will check on how to remove shading as i don't really need it and it should work.

**Comment by tomprod** [comment]
Hey, i have the same problem with another block of ooxml, insertContentControl crashes on it on office word online, can you tell me what's wrong with it please ? :
    <w:p>
            <w:r w:rsidRPr="47C124BC" w:rsidR="47C124BC">
                <w:rPr>
                    <w:rFonts w:asciiTheme="minorAscii" w:eastAsiaTheme="minorAscii" w:hAnsiTheme="minorAscii" w:cstheme="minorAscii" />
                    <w:sz w:val="20" />
                    <w:szCs w:val="20" />
                    <w:highlight w:val="yellow" />
                </w:rPr>
                <w:t>#DC{-&amp;70-&amp;71-&amp;72-&amp;73-&amp;74-&amp;75-&amp;79-&amp;60-&amp;61-&amp;62-&amp;63-&amp;64-&amp;65-&amp;68}</w:t>
            </w:r>
</w:p>

here is a link to the document (page 5) : https://teamwebexpert-my.sharepoint.com/:w:/g/personal/devext_teamwebexpert_onmicrosoft_com/EdPjICcWgy9MtJ4iJLodFYMBp0dCt-HKlkh9Z3PQOCB3hg?e=CE3FjS

**Comment by xiaoyuMS** [comment]
Hi @tomprod
Sorry, I didn't make it clear last time.

1. Any part of the paragraph is not supported will result in the entire paragraph not being supported.
2. It is not allowed to insert a content control in any part of the paragraph that is not fully supported.

So we need to go through the whole paragraph if there is a problem .
In the paragraph you mentioned, there are several **<w:spacing>** (character spacing) elements which are not supported on Word Online.

![image](https://user-images.githubusercontent.com/90585978/148488034-64082ea8-f2b0-4649-977f-b3844f50a6b7.png)

![image](https://user-images.githubusercontent.com/90585978/148487298-6779671f-9670-4cc8-b8ef-b42d1977d0db.png)

**Comment by tomprod** [comment]
Hey, i still have issues inserting a content control in another document, can you please check and tell me why ? It fails at #Client.CodeNAF
Thank you very much
Here is a link to the word document : https://teamwebexpert-my.sharepoint.com/:w:/g/personal/devext_teamwebexpert_onmicrosoft_com/ERmFs9qH1WJAoyehyDza3pcBynB9u3zn84drjOsCVVb7Cg?e=WQOESu

**Comment by xiaoyuMS** [comment]
Hi @tomprod
As you can see, there is a <w:snapToGrid/> element which is not supported in Word Online. The value 0 means **Off** value.
![image](https://user-images.githubusercontent.com/90585978/149081959-06b68a58-f113-432c-95e1-2c248f2058d3.png)

There are two ways that I tried to resolve this.
1. Delete the elements directly in xml file.

2. Use UI operation to **turn on** this 'snapToGrid' function (This solution can remove most of the snapToGrid elements, but not work fine on the signature part in the end of this document).
    
![image](https://user-images.githubusercontent.com/90585978/149085604-078e0a96-bf6c-4114-ad6c-13fc2c16149d.png)
![image](https://user-images.githubusercontent.com/90585978/149085674-a69e90f6-dd46-4fcf-ac26-92718ba2fbca.png)

**Comment by msoq** [comment]
Hi @xiaoyuMS, it seems that our team faced the same issue trying to insert ContentControls using the Word Online platform, I hope you can give some advice on how to deal with this situation.
Do you know if there is a complete list of ooxml attributes that make a paragraph unsupported for ContentControls? Is there a way to understand that the paragraph is unsupported other than parcing its ooxlm content? Is there any best practice how to clean up all unsupported ooxml attributes before inserting a ContentControl?
It would be very nice to hear your opinion on these questions!

**Comment by xiaoyuMS** [comment]
Hi @mikalai-sokarau, thanks for the suggestions. 
We will see how we can improve this. The issue has been tracked in our backlog as ADO#6085257

**Comment by msoq** [comment]
@xiaoyuMS, thanks for pointing your attention to this problem!
Maybe it's a silly question but do external users have access to the backlog you mentioned? Can I track progress of ADO#6085257 somehow?

**Comment by xiaoyuMS** [comment]
It is for internal use. We will come back for any update~

**Comment by docu-bill** [comment]
Has there been any progress on this? Is there any way to strip all the unsupported features out of a paragraph?

**Comment by xiaoyuMS** [comment]
Hi @docu-bill 
Sorry, we haven't made much progress on this. To solve this issue, we depend on the Word Web team to fill the feature gaps.

From the API side, exposing more meaningful error message is a potential way but still need more investigation. Given the current plan, we don't have a clear timeline for this work item.

As for stripping out all unsupported features, I don't know of a way to do that for now.

**Comment by docu-bill** [comment]
@xiaoyuMS, thank you. Yes better error messages would be very helpful.

**Comment by nickamckenna** [comment]
This is also a problem for us!

**Comment by maxcroy1** [comment]
@xiaoyuMS - same here. Is there a list of unsupported features that developers can reference to get ahead of this?

**Comment by jwilliams-symplr** [comment]
This is also blocking any new developments for me as well.

**Comment by xiruatms** [comment]
Thank you all. Currently, there's no such a list of unsupported features. We're working on those gradually, but there's no guaranteed timeline yet.
