### ISSUE TITLE
Range.autoFill does not work in TypeScript

### ISSUE THREAD

**Issue by gkfirst8** [OfficeDev/office-js#2338]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
When using office.js in Javascript I was nicely able to use FlashFill via the .autoFill of Range in Excel:
```
var myRange = worksheet.getRange('U2:W2');
myRange.autoFill(undefined, Excel.AutoFillType.FlashFill);
```
However why I try to do the same in TypeScript I get: "The argument is invalid or missing or has an incorrect format." (Note however that in TypeScript Excel.AutoFillType.FlashFill is invalid and should be Excel.AutoFillType.flashFill )

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ????
* Operating System: N/A
* Browser (if using Office on the web): Google Chome
 
## Expected behavior

I would expect both the Javascript and TypeScript interface to work the same or at least comparable. Any howto would be welcome or a fix to make it work.

## Current behavior

In TypeScript I get: "The argument is invalid or missing or has an incorrect format." (But in Javascript this works)

## Steps to reproduce

1. Write the suggest code above in Javascript and notice it works
2. Write the same code in TypeScript using the @types/office-js and nice you get the mentioned error

## Link to live example(s)

1. Working example in Javascript: https://gist.github.com/gkfirst8/acb58aefcf07fa1ffc34518efac3be7b
    (Notice that when you follow the auto-complete of Script Lab you end up with Excel.AutoFillType.flashFill which ends up in the same error)
3. TypeScript invalid example that does work: https://gist.github.com/bbcc6e635bec3e588608fddff77d71a8
![image](https://user-images.githubusercontent.com/10880452/147880301-4d65cdd6-0e0b-4559-a509-92fe53157409.png)

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by gkfirst8** [comment]
As I use Angular and the TypeScript compiler it comes with the syntax error stops me from tricking the system and still using the FlashFill (note the casing)

**Comment by millerds** [comment]
This isn't a problem with the dev tooling, it's something with-in the api.  The typescript compiler and syntax checking is simply respecting the office.js definition file retrieved (index.d.ts) and the runtime behavior is also controlled by the office.js code imported by the browser.

**Comment by honxmsft** [comment]
Hi @gkfirst8, after we investigated the problem, we found

1. The autofill API with flash fill currently can only work with the range that has only one column.
2. The flash fill content does not support formula. You can also try this in flash fill UI button.

The reason that `Excel.AutoFillType.FlashFill` can work is that the `Excel.AutoFillType.FlashFill` is `undefined`. So the `myRange.autoFill(undefined, Excel.AutoFillType.FlashFill);` is equivalent to `myRange.autoFill();`.

If the autoFill default options behavior is your expectation, you can just use it in the way of  `myRange.autoFill();` or `myRange.autoFill(undefined, undefined);`.

For flash fill usage, you can refer https://support.microsoft.com/en-us/office/using-flash-fill-in-excel-3f9bcf1e-db93-4890-94a0-1578341f73f7

**Comment by gkfirst8** [comment]
Thanks @honxmsft for explaining.
Maybe good to document the limitation of the API on the flashFill part?
I'll see if I can use the .autoFill(); version. Currently I was able to use worksheet.getUsedRange() to get the range to fill with .autoFill(<range>) which works well.

**Comment by dingjin-ms** [comment]
Thank you @gkfirst8 for advising! ADO #5715727 opened to track the documentation problem.
