### ISSUE TITLE
Excel application hangs on custom property retrieval for saved workbook

### ISSUE THREAD

**Issue by codecrasher99** [OfficeDev/office-js#234]
Excel custom property retrieval causes the excel application to hang for saved workbook.  The same code snippet works fine if the excel workbook is in an unsaved state. The stackoverflow [query](https://stackoverflow.com/questions/52102047/excel-custom-property-retrieval-fails-for-saved-workbook) contains details about the problem.

## Steps to Reproduce, or Live Example

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by XiangGaoMSFT** [comment]
Thanks for reporting this issue.

I can repro it by [this gist](https://gist.github.com/XiangGaoMSFT/4cafb6f0c1a4a981f6d0a4c2386c3b38)
This issue has been fixed in latest version. We'll try to port the fix to 16.0.9126.xxxx

Tracked by internal bug 2536476

**Comment by codecrasher99** [comment]
Thanks for the fix.
