### ISSUE TITLE
Word Addin Javascript empty string font.color or font.highlightColor after I set it

### ISSUE THREAD

**Issue by citasionm** [OfficeDev/office-js#2341]
# Provide required information needed to triage your issue
I have the following code that sets the font.color

```
    Word.run(async (context) => {
          const newRange = await getTextRange(context, locationText, offset, length);
          if (newRange === null) return null;
          suggestedPosition = newRange;
          suggestedPosition.load('font');
          await context.sync();
          suggestedPosition.font.color = 'White';
          suggestedPosition.track();
          await context.sync();
        });
```

This works and changes the color to white. Then after I reopen the taskpane, I want my script to be able to find if there is any white colored text left over. I do this by searching through text.

```
    Word.run(async function(context) {
          const body = context.document.body.getRange().getTextRanges([' '], true);
          context.load(body, ['text', 'font']);
          await context.sync();
          for (let i = 0; i < body.items.length; i += 1) {
            const word = body.items[i];
            if (word.font.color === 'White') console.log('found word!!!');
          }
        })
```

What I get back instead is all the colors of the rest of the text (usually #000000) but the color that I changed, I get back ''.
What is it that I am doing wrong? I also tried instead of White to use a random color (#123543) but still the same weird issue.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Online (latest)
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

I should be able to get the properly changed color instead of an empty string. (there are no mixed colors either)

## Current behavior

I get an empty string.

I should be getting the proper hex color.

## Steps to reproduce

See code for reproducing

## Context

I am trying to highlight some text using a specific color and then I want to be able to find the highlighted text in a new session (i.e., I cannot use track() for the ranges that I've changed)

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by jingxuan0109** [comment]
Hi, 
I cannot repro this issue.  I use this https://gist.github.com/jingxuan0109/9f925366e1f916aee770e56e6ca4b798 on script lab. 

1. set color
2. close taskpane
3. get color

The color is right. I am just wondering whether you can give us more information and a script and document would be helpful. 

Thanks

**Comment by citasionm** [comment]
Thank you for testing. Quick question, is there an easy to load the yaml file on word online for testing? I want to see if there is something weird with my document.

**Comment by jingxuan0109** [comment]
You can use "Script Lab" addin to test my script. https://docs.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab

**Comment by citasionm** [comment]
I can verify that even with the script provided the bug exists on a specific document that I had. On a new one this does not occur.

[Document 1.docx](https://github.com/OfficeDev/office-js/files/7825952/Document.1.docx)

**Comment by citasionm** [comment]
I can verify that the issue persists in a specific document of mine but I cannot figure out why. Here's the attached document:

[Document 1.docx](https://github.com/OfficeDev/office-js/files/7825965/Document.1.docx)

**Comment by jingxuan0109** [comment]
I cannot reproduce it on my side. I am just wondering whether you can try it on new document.

**Comment by citasionm** [comment]
In a new document it works correctly. But in the attached document in shows up like this (notice the empty string).

![image](https://user-images.githubusercontent.com/97069384/148485173-0f039c17-4e5a-4698-8d0a-37eea84ee60e.png)

**Comment by jingxuan0109** [comment]
I see, that because you have a period after "said". I am just wondering whether you can try to set period into the same color. This is by design behavior. https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-blank-null-values#null-property-values-in-the-response

**Comment by citasionm** [comment]
So that is what "mixed color" means in the documentation. It is if multiple characters have different colors. I was scratching my head about that. Thanks so much. I'll close the ticket now.
