### ISSUE TITLE
Subject not been returned by OfficeJS API

### ISSUE THREAD

**Issue by splinter** [OfficeDev/office-js#2343]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.55 (21111400)
* Operating System: Mac OS
* Browser (if using Office on the web): N/A
 
## Expected behavior
The [Subject API](https://docs.microsoft.com/en-us/javascript/api/outlook/office.subject?view=outlook-js-preview) should return the subject.

## Current behavior
Subject is not returned

## Steps to reproduce
The issue seems to be happening sporadically (we suspect that this could be due to a poor connection on the client machine). However, the body in these scenarios is returned.

## Link to live example(s)
N/A

# Provide additional details
N/A

## Context
This is impacting a very small subset of customers at the moment 

## Useful logs
N/A

**Comment by exextoc** [comment]
@splinter We are not able to repro this. What is the asyncResult.status when the subject is not returned? Can you share repro steps?
