### ISSUE TITLE
Is There any Document to guide create excel addin on Angular?

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/office-js#2346]
I am trying to implement Excel AddIn with Command, TaskPane, Functions and angular.

Is there any document or details steps to implement in one angular project?

**Comment by RuizhiSunMS** [comment]
Thanks for your comment, @JHJ-MS please take a look.

**Comment by AkhileshShah-MS** [comment]
@dingjin-ms could you please help @Edward-Zhou with the query.

**Comment by JHJ-MS** [comment]
To implement Excel Custom function Add-in using Angular, please see the reply here https://stackoverflow.com/questions/70575286/office-excel-addin-custom-function-with-angular-template/70740530#70740530

**Comment by Edward-Zhou** [comment]
Please check the comments in your link. Can you implement excel addin with custom function in angular with your suggestion?

**Comment by JHJ-MS** [comment]
Currently, we don't have a document to guide creating excel Custom Functions Add-in with Angular. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests are considered when we go through our planning process. Thanks, Microsoft 365 Developer Platform team

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
