### ISSUE TITLE
API needed to select multiple chart in Excel in sheet and across workbook with officeJS.

### ISSUE THREAD

**Issue by alok0914** [OfficeDev/office-js#2347]
Allowing user to select multiple chart in installed version as well as online version of Excel in sheet and across workbook with office JS and get data and change data related to all charts using Office JS API's. This feature is required for adding functionality to multiple charts in one go. The functionality is needed in sheet as well as multiple sheets of a workbook.

Step 1: Select multiple chart using CTRL button in sheet or across multiple sheets.
Step 2: Try adding color or any other functionality to multiple charts.

End Result: The color is not applied to multiple chart in on go.
Expected Result: Office JS should have API to get data related to multiple charts, to apply functionality to it.

**Comment by chiz-ms** [comment]
Thanks for the suggestion @alok0914. For feature requests please go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) and see if your feature has already been requested or request a new feature there.
