### ISSUE TITLE
Range.getCellProperties() returns #000000 for all border colors

### ISSUE THREAD

**Issue by sheldoncoates** [OfficeDev/office-js#2349]
# Provide required information needed to triage your issue

```
cellPropertiesArray = smallRange.getCellProperties({
                format: {
                    borders: {
                        color: true,
                    },
                },
            })
```

When running this code on a range with no borders the following is produced in the cellPropertiesArray:
```
[
        {
          "format": {
            "borders": {
              "bottom": { "color": "#000000" },
              "diagonalDown": { "color": "#000000" },
              "vertical": { "color": "#000000" },
              "diagonalUp": { "color": "#000000" },
              "horizontal": { "color": "#000000" },
              "top": { "color": "#000000" },
              "left": { "color": "#000000" },
              "right": { "color": "#000000" }
            }
          }
        },
]
```

When running on a range WITH border colors it will return the correct color.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac, Office on the web, can't test PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.56 (21121100)
* Operating System: Mac OS
* Browser (if using Office on the web): Google Chrome
 
## Expected behavior

The borders should be the correct color.

## Current behavior

Borders are black if no border color is set by the user.

**Comment by chiz-ms** [comment]
Hi @sheldoncoates, could you also include `style` under `borders` and check it against `Excel.BorderLineStyle.none`? I suppose this would work for you.

**Comment by sheldoncoates** [comment]
Hi @chiz-ms, i tried this using border style and you're correct the border style does show as `None`. Now the issue is when i go to re-apply the border to the range by doing `Range.SetCellProperties()`, theres no borders at all on the cells that have the style property as `None`. Is there any way to keep the default borders on the cells that have the style as `None`? Ideally if no border has been applied to the cell we would like to keep the way it looks and not remove the border completely.

**Comment by jipinshi** [comment]
@sheldoncoates, could you try range.copyFrom("B3", Excel.RangeCopyType.formats), suppose this one can copy style.none if the src range is with style none.

**Comment by jake-chambers** [comment]
Hi @jipinshi, not sure we understand your suggested solution - but is this not a bug? Can't `getCellProperties()` just be fixed to stop incorrectly returning #000000? Why doesn't it just return the correct border colour?

We're basically saving all the cell states of a spreadsheet in our document database. This is done by storing the JSON representation of each cell, if the border styles are not being retrieved correctly, we cannot successfully rewrite the saved values onto another spreadsheet.

**Comment by jipinshi** [comment]
@jake-chambers , I tried below script, and the format and color didn't change. Hope this can unblock you.

   var worksheet = context.workbook.worksheets.getFirst();
    var range = worksheet.getRange("A1");
    var color =range.getCellProperties({
      format: {
        borders: {
          color: true,
          style: true,
        },
        
      },
    })
    await context.sync();

    var range1 = worksheet.getRange("C2");
    range1.setCellProperties(color.value);

**Comment by sheldoncoates** [comment]
@jipinshi as you can see from the initial post, we are doing the following to retrieve cell properties for a range:
```
cellPropertiesArray = smallRange.getCellProperties({
                format: {
                    borders: {
                        color: true,
                        style: true,
                    },
                    fill: {
                        color: true,
                    },
                    font: {
                        bold: true,
                        color: true,
                        italic: true,
                        name: true,
                        size: true,
                        strikethrough: true,
                        underline: true,
                    },
                },
            })
```
as you can see we are doing as you and your colleague suggested.

when we apply the properties back to a new sheet we do the following:
1. we get our stored data which is the raw jSON from smallRange.getCellProperties. Here a snippet of what it looks like:
```
cellProperties = {
  "format": {
    "font": {
      "size": 11,
      "color": "#000000",
      "name": "Calibri",
      "underline": "None"
    },
    "fill": { "color": "#FFFFFF" },
    "borders": {
      "bottom": { "color": "#000000", "style": "None" },
      "diagonalDown": { "color": "#000000", "style": "None" },
      "vertical": { "color": "#000000", "style": "None" },
      "diagonalUp": { "color": "#000000", "style": "None" },
      "horizontal": { "color": "#000000", "style": "None" },
      "top": { "color": "#000000", "style": "None" },
      "left": { "color": "#000000", "style": "None" },
      "right": { "color": "#000000", "style": "None" }
    }
  }
}
```
as you can see each border is coming with the color as #000000 and the style as None. 

Please note that there are NO diagonal borders on the sheet either. so when we go to apply we now have diagonal borders if we dont apply the style.

2. Next we apply the properties to our active spreadsheet as follows:
```
newRange.setCellProperties(cellProperties)
```

The other properties are coming as expected, but borders is not correct. The border color is not #000000 by default and applying style None to our new sheet removes the borders completely.

This seems to be a bug since the default border colour is not #000000 and when we apply the style as None they disappear and the range cells have no border at all. We would expect either the correct color to be sent here (some type of grey which is the default) or style None to NOT completely remove the borders from the cells in the range.

Please let us know if this will be fixed or if there is another way to do this without changing our current usage too much.

**Comment by jipinshi** [comment]
@sheldoncoates , I'm confused by the statements. Can you attach one short video to describe it from end to end to better understand the issue?

The other properties are coming as expected, but borders is not correct. The border color is not #0 by default and applying style None to our new sheet removes the borders completely.

**Comment by sheldoncoates** [comment]
@jipinshi heres a video example of whats happening in our add in and it shows whats happening as described above:

https://user-images.githubusercontent.com/17774519/149176192-654664aa-17d2-4654-941c-25f9c60cd892.mov

In the video we are saving the data that comes from Range.getCellProperties() from sheet1. its saved as outlined in my earlier reply. And when we reapply those properties to a new sheet and a new range with Range.setCellProperties() you can see the result in the video is that no borders are visible where the data resides.

**Comment by jipinshi** [comment]
@sheldoncoates , thanks for providing the video, with the script I showed you above cannot repro on both online/win32/MAC, so it would be nice to show me the code snip in the demo you are running. Here is the gist I tried https://gist.github.com/dingjin-ms/1d6f2af74bdc34f3fd189231cba36980.

It would make the problem easier to dig out if you can try with Scriptlab to repro the problem with one gist and share the gist to me.

**Comment by jipinshi** [comment]
Here is the gist I tried https://gist.github.com/dingjin-ms/1d6f2af74bdc34f3fd189231cba36980

**Comment by sheldoncoates** [comment]
@jipinshi after running your gist i can see that the issue is not the borders but the fill is causing the borders to not show as default. our getCellProperties() has the following load options:
```
format: {
                    borders: {
                        color: true,
                        style: true,
                    },
                    fill: {
                        color: true,
                    },
                    font: {
                        bold: true,
                        color: true,
                        italic: true,
                        name: true,
                        size: true,
                        strikethrough: true,
                        underline: true,
                    },
                },
```

and when this is run getCellProperties() on an empty sheet the fill is #FFFFFF for all cells... because of this the fill is applied to all the cells when we do setCellProperties() overriding all the borders. i tried the other fill options but none are working to stop the behaviour.

Do you have any suggestions on how to stop this from happening?

**Comment by jipinshi** [comment]
@sheldoncoates, thanks explain more clear, I can repro the issue now. Have opened bug 5721552 to track it. So can you remove fill property first to unblock you firstly?  Will let you know the result if there is update.

**Comment by sheldoncoates** [comment]
@jipinshi thanks for your help. we have a requirement to have most of the spreadsheet properties copied so although this resolves the border issue it now creates another with background colors. Where can we track the status of the issue you mentioned above?

**Comment by jipinshi** [comment]
@sheldoncoates , may I know whether the addin is released now?  What's the status of the addin? And what's the potential number of the end user who may use the addin. As for this bug, need triage team to give priority based on the resource allocation and other impacts.

**Comment by jake-chambers** [comment]
@jipinshi The addin is released, you can download it [here](https://appsource.microsoft.com/en-cy/product/office/WA200002252?tab=Overview). This blocks us from iterating on one of our latest features, there are around 3000 people using the add in.

**Comment by yuc014** [comment]
Hi @jake-chambers @sheldoncoates,

Please try this workaround:
```
const sheet = context.workbook.worksheets.getActiveWorksheet();
    var smallRange = sheet.getRange("A1:B3")
    smallRange.load();
    await context.sync();

    var cellPropertiesArray = smallRange.getCellProperties({
      format: {
        borders: {
          color: true,
          style: true,
        },
        fill: {
          color: true,
          tintAndShade : true,
        },
        font: {
          bold: true,
          color: true,
          italic: true,
          name: true,
          size: true,
          strikethrough: true,
          underline: true,
        },
      },
    })
    await context.sync();
    
    var newRange = sheet.getRange("E1:F3")
    newRange.clear("Formats");

    for(var i = 0; i<smallRange.rowCount; i++){
      for(var j = 0; j<smallRange.columnCount; j++){
        if (cellPropertiesArray.value[i][j].format.fill.color != "#FFFFFF" || cellPropertiesArray.value[i][j].format.fill.tintAndShade != null) {
          delete cellPropertiesArray.value[i][j].format.fill.tintAndShade;
          newRange.getCell(i, j).setCellProperties([[cellPropertiesArray.value[i][j]]]);
        } 
      }
    }  
```

When cell color == "#FFFFFF" and tintAndShade == null, means this is a default style cell. Then we do nothing for set new format.

The root cause is: when we "getCellProperties", it get the fill color of the cell. If the style of the cell is default, we can still get the color "#FFFFFF" from it. Then when we "setCellProperties", we set the color to the new range. Like we make it white in UI (you can try it, and the border will disappear). 

Hope this workaround would unblock you.

**Comment by tjennz12** [comment]
Hello - this issue which appears to me as a bug seems to still be present.

 I have a similar use-case as the OP. I want to store the default cell properties when the add-in loads, for the purposes of "resetting" the cell formats (fill color, border color, border style etc.) after they've potentially been edited by the user. 

It's clear when the Excel sheet loads, it has a white fill color, and a black border that's present (the classic Excel cell style). However, the issue is whenever I try to load these properties from any of the cells programatically, what's returned is a white fill color (good!), black border color (good!) but a border-style of "None" (bad!). The border style when looking at the sheet is clearly "Continuous". So, when I try and "reset" cells back to their original formatting, since the border style returned "None", it erases all the borders.

So, right now, my only option for being able to reset back to default cell format properties is to hardcode a cell border style of "Continuous", which is not ideal.

This is a code snippet showing how I'm programming on my end:
```
const worksheet = context.workbook.worksheets.getActiveWorksheet();
const maxRows = 1048576;
const maxColumns = 16384;
const cell = worksheet.getCell(maxRows - 1, maxColumns - 1);
cell.format.borders.load("items");
await context.sync();
cell.format.fill.load("color, tintAndShade");
await context.sync();
cell.format.borders.items.forEach((border, index) => {
   console.log(
   // Border style is "None" - not what I want or expect!
   `Index: ${index}, Border position: ${border.sideIndex}, Border color: ${border.color}, Style: ${border.style}`
   )
 });
```

**Comment by SiruiSun-MSFT** [comment]
Hi @tjennz12, I don’t know if I misunderstood your words since I can’t reproduce the issue you mentioned from my side.
First of all, the default style of excel cell is "None" - no border, as shown in the picture below.
![image](https://github.com/OfficeDev/office-js/assets/86719968/64cfe658-7af4-4804-aa75-22b1f305346e)
After we set the border to "Continuous", the border will turn black and appear.
![image](https://github.com/OfficeDev/office-js/assets/86719968/340c21e9-c998-422b-962a-d480c3237999)
When our border style is kept None, no border color will be displayed. Therefore, even if the color can get the default black, it will still be displayed as borderless.
According to the gist you provided, after I successfully set the cell border, I can get the correct attributes.
![image](https://github.com/OfficeDev/office-js/assets/86719968/a73d183e-3b24-4692-a6dd-cc961a4ed33d)

**Comment by tjennz12** [comment]
Hello @SiruiSun-MSFT - Thanks for looking into this for me.

I understand the picture you've shown. Clearly, from the picture of the cells, we can see there is a gray-colored border. The main problem right now is if I try to load the cell format properties when the app loads (cell fill color, border color, and border style), then reapply the cell format properties immediately afterward, the cells look differently. In other words, the properties that are loaded are not actually what's visible - there's clearly a gray colored border. When the cell format properties are loaded, I get cell fill color as white, cell border color as black, and the cell border style as "None". When I reapply those properties, the gray colored border disappears. I just want to be able to "reset" all of the cell format properties by loading them programmatically without having to hardcode their values.


here is how you can reproduce, if you'd like:

1. Initialize a `yo office` project
  - `mkdir cell-debug`
  - `cd cell-debug`
  - `yo office`
    - select `Office Add-in Task Pane project using React framework`
    - select `Typescript`
    - name the project `cell-debug`
    - select `Excel`
 2. Open up a code editor and replace the following files with the code listed below

First create a file `src/utils.tsx`:

```
/* global Excel, console */

export async function resetCellProps() {
  try {
    await Excel.run(async (context) => {
      const worksheet = context.workbook.worksheets.getActiveWorksheet();
      const cell = worksheet.getCell(0, 0);
      cell.format.borders.load("items");
      await context.sync();
      cell.format.fill.load("color, tintAndShade");
      await context.sync();
      const border = cell.format.borders.items[0];
      console.log("Color", cell.format.fill.color);
      cell.format.borders.items.forEach((border, index) => {
        console.log(
          `Index: ${index}, Border position: ${border.sideIndex}, Border color: ${border.color}, Style: ${border.style}, TintAndShade: ${border.tintAndShade}`
        );
      });
      const range = worksheet.getRange("A4:D7");
      range.format.fill.color = cell.format.fill.color;
      range.format.borders.getItem("EdgeBottom").color = border.color;
      range.format.borders.getItem("EdgeBottom").style = border.style;
      range.format.borders.getItem("EdgeBottom").tintAndShade = border.tintAndShade;
      range.format.borders.getItem("EdgeTop").color = border.color;
      range.format.borders.getItem("EdgeTop").style = border.style;
      range.format.borders.getItem("EdgeTop").tintAndShade = border.tintAndShade;
      range.format.borders.getItem("EdgeLeft").color = border.color;
      range.format.borders.getItem("EdgeLeft").style = border.style;
      range.format.borders.getItem("EdgeLeft").tintAndShade = border.tintAndShade;
      range.format.borders.getItem("EdgeRight").color = border.color;
      range.format.borders.getItem("EdgeRight").style = border.style;
      range.format.borders.getItem("EdgeRight").tintAndShade = border.tintAndShade;
    });
  } catch (error) {
    console.error(error);
  }
}
```

Next, edit `src/taskpane/components/App.tsx` to be the following file:
 
 ```
import * as React from "react";
import Header from "./Header";
import HeroList, { HeroListItem } from "./HeroList";
import TextInsertion from "./TextInsertion";
import { makeStyles } from "@fluentui/react-components";
import { Ribbon24Regular, LockOpen24Regular, DesignIdeas24Regular } from "@fluentui/react-icons";
import { DefaultButton } from "@fluentui/react";
import { printCellProps } from "../../utils";

/* global Excel, console */

interface AppProps {
  title: string;
}

export interface AppState {}

export default class App extends React.Component<AppProps, AppState> {
  constructor(props, context) {
    super(props, context);
    this.state = {};
  }

  click = async () => {
    console.log("printing cell props");
    resetCellProps();
  };

  render(): React.ReactNode {
    return (
      <div>
        <Header logo="assets/logo-filled.png" title="" message="Welcome" />
        <TextInsertion />
        <DefaultButton className="ms-welcome__action" iconProps={{ iconName: "ChevronRight" }} onClick={this.click}>
          Update
        </DefaultButton>
      </div>
    );
  }
}
```

3. Run the following 3 commands in the terminal: `npm install`, `npm run build`, `npm run start`.
4. When the Add-in loads in Excel, press the `Update` button. 
5. View the server console, by right-clicking the taskpane, selecting "inspect element", and then click "console" to view the log.

Excel add-in should look like this:
<img width="1694" alt="Screenshot 2023-11-25 at 4 33 16 PM" src="https://github.com/OfficeDev/office-js/assets/7572613/56e68650-cc22-4350-85a7-f0f3570085f3">

After clicking the update button, it looks like the following picture. Note the cell borders have disappeared in the range "A4:F7" even though I was just trying to reapply original format, and should have resulted in no changes.
<img width="1701" alt="Screenshot 2023-11-25 at 6 05 00 PM" src="https://github.com/OfficeDev/office-js/assets/7572613/d6629de5-1845-4fa4-bbf4-0aaf5d1b41ed">

**Comment by SiruiSun-MSFT** [comment]
Hi @tjennz12, Thanks for your detailed providing. I can see the disappeared borders as your screenshot shows.
After looking deeply into your gist, I find the issue is come from this command:
![image](https://github.com/OfficeDev/office-js/assets/86719968/a84ef56a-1216-4ad5-bb09-a48c3352874a)
Because the default color of our Excel fill is white. Therefore, in this step, the fill color of the selected "A4:F7" will be set to white. Since there is no border at this time, the entire area will be displayed as a complete white. You can change the fill color of this area to no-fill through the UI to regain the gray border.
![image](https://github.com/OfficeDev/office-js/assets/86719968/c47707e5-4e2f-4fb4-a414-8070be75682a)

I fully understand your need to revert fill settings to default. Therefore, we recommend that you use the following API at this step:
```
range.format.fill.clear();
```
For more information, please refer to this link: https://learn.microsoft.com/en-us/javascript/api/excel/excel.rangefill?view=excel-js-preview#excel-excel-rangefill-clear-member(1)

Hope the above reply will help you out!

**Comment by tjennz12** [comment]
HI @SiruiSun-MSFT , using `range.format.fill.clear();` solved the problem for me, thank you! 

Essentially it seems there is a layer of color-formatting underneath another layer of color-formatting. The top layer can be edited by the user, while the bottom layer cannot. When `clear()` is run, the top layer is removed exposing the bottom layer.
