### ISSUE TITLE
Excel JS Addin taskpane doesn't load completely

### ISSUE THREAD

**Issue by savanetllc** [OfficeDev/office-js#2350]
Hi, I am developing Excel JS addin however most of the time, Office doesn't initialized so taskpane doesn't load completely.  I am sorry for making a duplicate issue but there is no response on first issue.  Please note, we have same response in multiple offices (USA, UK, Asia) so I don't think its because of slow Internet.

Here is a render function in App.js which keep showing Progress control.
`
 render() {
        const { title, isOfficeInitialized } = this.props;
        
        if (!isOfficeInitialized) {
            return (
                <Progress
                    title={title}
                    logo={require("./../../../assets/logo-filled.png")}
                    message="Please right click and refresh the page to see app body."
                />
            );
        }
`
And here is complete (startup) index.js file
`
import "office-ui-fabric-react/dist/css/fabric.min.css";
import App from "./components/App";
import { AppContainer } from "react-hot-loader";
import { initializeIcons } from "office-ui-fabric-react/lib/Icons";
import * as React from "react";
import * as ReactDOM from "react-dom";
import './taskpane.css';
/* global document, Office, module, require */

initializeIcons();

let isOfficeInitialized = false;

const title = "Add-in";

const render = (Component) => {
  ReactDOM.render(
    <AppContainer>
      <Component title={title} isOfficeInitialized={isOfficeInitialized} />
    </AppContainer>,
    document.getElementById("container")
  );
};

/* Render application after Office initializes */
Office.initialize = () => {
  isOfficeInitialized = true;
  render(App);
};

/* Initial render showing a progress bar */
render(App);

if (module.hot) {
  module.hot.accept("./components/App", () => {
    const NextApp = require("./components/App").default;
    render(NextApp);
  });
}

`

Please any response? Thank you in advance.

**Comment by chiz-ms** [comment]
Adding the link to the original issue: #2321

**Comment by RuizhiSunMS** [comment]
Causing there has been passed so long, we decide to close this issue. Please feel free to re-active and contact us if there were other questions.
Thanks.
