### ISSUE TITLE
Outlook Desktop on Windows 11 All add-ins fail to load since January 1st 2022

### ISSUE THREAD

**Issue by cdmdotnet** [OfficeDev/office-js#2351]
# Provide required information needed to triage your issue
Sometime between December 28 2021 and January 7th 2022 Javascript based add-ins stopped working on Desktop Outlook 2019 on Windows 11.
Outlook online is unaffected, Outlook Desktop 2019 on Windows 10 is unaffected, It seems to be Outlook setups using the new Webview2 runtime.

## Your Environment

* PC Windows 11
* Outlook 2019/365
* Microsoft® Outlook® 2019 MSO (Version 2111 Build 16.0.14701.20254) 64-bit 
* Windows 11
* Not affected
 
## Expected behavior
Upon opening Outlook, Command buttons appear in the Toolbar/Outlook ribbon. Said buttons can be clicked to open task panes.

## Current behavior
No icons are added to the Outlook ribbon.

## Steps to reproduce
Windows 11. Outlook 2019
Click Get Addins
Select and install either Zoom for Outlook or HubSpot Sales.

## Link to live example(s)

# Provide additional details
Earlier today this wasn't affecting a Windows 10 machine I have, however after installing whatever Office decided was an update, Windows 10 is now affected.
The buttons/icons are added to outlook.office.com so it's not affecting the web version of outlook and the mobile version of outlook seem sunaffected.

## Context
Every publicly available add-in in Outlook I have is now dead and unusable.

## Useful logs
If i knew how to debug the inner workings of Outlook and the AppStore I would provide them... but there is no documentation on how to do that.

**Comment by exextoc** [comment]
To investigate this further, try capturing a [fiddler](https://www.telerik.com/download/fiddler) trace starting before booting Outlook and look for failures and EWS calls that have GetAppManifests.
 
 Are you able to access the add-in store/Get Add-ins in Outlook Desktop? If not, then the issue could be that [connected experiences](https://docs.microsoft.com/en-us/deployoffice/privacy/connected-experiences#choose-whether-these-connected-experiences-are-available-to-use) need to be enabled.
 
Can you also verify if the add-ins manifest files were downloaded by going to `{userprofile}\AppData\Local\Microsoft\Office\16.0\Wef\{guid}\{hash}\Manifests`
(things in {} are specific to your account)
