### ISSUE TITLE
Office js: getFileAsync() as PDF returns PP presentations in portrait orientation

### ISSUE THREAD

**Issue by rocketboy1908** [OfficeDev/office-js#2352]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We are developing an Office add-in to retrieve PowerPoint presentations in PDF format from the Office JS API and then upload them to a cloud. The issue is that all the presentations are in portrait orientation when retrieved as PDF. Could change that to landscape mode or add on option to chose the desired orientation?

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Mac, iOS, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Powerpoint
* Operating System: Mac OS
* Browser (if using Office on the web): Chrome
 
## Expected behavior
I would expect any PP presentations retrieved as PDF files to be in landscape orientation.

## Current behavior
Currently all PP presentations retrieved as PDF files are in portrait orientation.
Either change the default orientation to landscape or add an option to choose the orientation.

## Steps to reproduce
1. Create an Office add-in for PowerPoint
2. Use getFileAsync() and getSliceAsync() to retrieve a presentation as PDF
3. Upload/download the retrieved PDF file and check its orientation

**Comment by chiz-ms** [comment]
Thank you @rocketboy1908 for reporting this issue. @ononder please see if this is a feature request.
