### ISSUE TITLE
Excel AddIn Command Open FilePicker Dialog and read local file

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/office-js#2353]
I want to insert the image from local disk by Excel AddIn Command.

Something like below:

![image](https://user-images.githubusercontent.com/16079555/148724022-cd78bd16-55d4-411a-a033-cea5801afda9.png)

Is there any guide for this?

I tried code below:

```
function InsertImgWithPreview(event: Office.AddinCommands.Event) {
  // dynamic create file input
  let fileInput = document.createElement("input");
  fileInput.type = "file";
  fileInput.style.display = "none";
  fileInput.onchange = async () => {
    var reader = new FileReader();
    reader.onload = () => {
      Excel.run(function (context) {
        var startIndex = reader.result.toString().indexOf("base64,");
        var myBase64 = reader.result.toString().substr(startIndex + 7);
        var sheet = context.workbook.worksheets.getActiveWorksheet();
        var image = sheet.shapes.addImage(myBase64);
        image.name = "Image";
        return context.sync();
      }).catch();
    };
    // Read in the image file as a data URL.
    reader.readAsDataURL(fileInput.files[0]);
  };
  fileInput.click();
  event.completed();
}
```
But, it will throw error `File chooser dialog can only be shown with a user activation.`

How to achieve insert local image to Excel worksheet by command in Ribbon

**Comment by yuc014** [comment]
Hi @Edward-Zhou,

If you want insert a local image by excel api. You can try this gist for example: https://gist.github.com/yuc014/816444853a4de1b74fbb83c760d28ee9

Reference: https://docs.microsoft.com/en-us/javascript/api/excel/excel.shapecollection?view=excel-js-preview#addImage_base64ImageString_

Hope that would unblock you. Thanks.

**Comment by Edward-Zhou** [comment]
Could you share more details about this? If you check my code carefully, you will find I already use the code from your first link.

It will return the error in my original post.

```
      const myFile = <HTMLInputElement>document.getElementById("selectedFile");
      const reader = new FileReader();
```

I want to read local file by Excel Command from Ribbon.

**Comment by Edward-Zhou** [comment]
@yuc014 
Could you share more details about this? If you check my code carefully, you will find I already use the code from your first link.

It will return the error in my original post.

```
      const myFile = <HTMLInputElement>document.getElementById("selectedFile");
      const reader = new FileReader();
```

I want to read local file by Excel Command from Ribbon.

**Comment by yuc014** [comment]
Hi @Edward-Zhou,

I tried your code but cannot repro your error, see my repro video below:

https://user-images.githubusercontent.com/87364252/148926483-a9d602a2-cf7d-4484-b290-1dd48b334f2d.mp4

Could you give me some more details about the repro steps?

Also, including the platform you used(desktop, online) and the version would be better. 

Thank you.

**Comment by Edward-Zhou** [comment]
@yuc014 Thanks, you teach me how to test code with script lab, it might be an issue with my environment.
