### ISSUE TITLE
TypeScript type definition for isSetSupported method

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#2354]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

What is the difference between these `isSetSupported` methods defined in `@types/office-js`?

![isSetSupported](https://user-images.githubusercontent.com/58804032/148637267-ba6cde6f-3eab-4f47-a662-1fbca90db140.png)

This method returns the value as expected.
[isSetSupported in Office.RequirementSetSupport interface](https://docs.microsoft.com/en-us/javascript/api/office/office.requirementsetsupport?view=common-js-preview#isSetSupported_name__minVersion_)
``` ts
console.log(Office.context.requirements.isSetSupported("Mailbox", "1.11"));
```

This method results in an error.
[Office.isSetSupported](https://docs.microsoft.com/en-us/javascript/api/office?view=common-js-preview#Office_isSetSupported_name__minVersion_)
``` ts
console.log(Office.isSetSupported("Mailbox", "1.11"));
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5530f30f-9d7b-a2e2-b30f-098556733c73
* Version Independent ID: 88f35bab-8f86-dd9b-66fa-43a554121a9b
* Content: [office package - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office?view=common-js-preview#Office_isSetSupported_name__minVersion_)
* Content Source: [docs/docs-ref-autogen/office/office.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ghelyar** [comment]
Also `OfficeRuntime.apiInformation.isSetSupported`
