### ISSUE TITLE
How to insert notes for Range in Excel

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/office-js#2355]
I want to insert notes for excel cell by excel addin.

Based on [Work with comments using the Excel JavaScript API](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-comments), we can insert comments.

But, I did not find any api which shows how to insert notes.

**Comment by AkhileshShah-MS** [comment]
@RuoyingLiang Please help Edward with the request.

**Comment by SiruiSun-MSFT** [comment]
Thanks for letting us know this issue. However, currently, the feature: insert notes for excel cell, you requested, is not a part of the product. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests are considered when we go through our planning process. Thanks, Microsoft 365 Developer Platform team

**Comment by johnnyoshika** [comment]
I'd really like the ability to add notes via javascript API as well. Here's someone else requesting it:

https://techcommunity.microsoft.com/idea/microsoft365developerplatform/add-support-for-notes-to-office-js-api-for-excel/4017916

Anyone know that status of this feature request?
