### ISSUE TITLE
Admin deployed add-ins are not automatically pinned to ribbon in Web Outlook in certain circumstances

### ISSUE THREAD

**Issue by atsopuronen** [OfficeDev/office-js#2358]
## Background
NOTE: This same question was posted on [Office add-ins Community call September 08, 2021](https://techcommunity.microsoft.com/t5/microsoft-365-pnp-blog/office-add-ins-community-call-september-8-2021/ba-p/2747100), and I was requested to post a ticket here.

## Issue explained
Back in Office add-ins Community call March 09, 2021, Microsoft revealed that admin-deployed add-ins would be automatically pinned to the ribbon in Web Outlook starting 21 April, 2021. 

We have many customers who already had deployed our add-in via Centralized Deployment before that date, but would now like to have it auto-pinned in Web Outlook.

However, in our internal testing and testing done by our customers, re-deployed (remove+add) add-ins are not automatically pinned in Web Outlook. In addition to lack of auto-pinning, we are naturally not seeing the "nudge" notification.

Completely new add-ins (not previously centrally deployed) are properly auto-pinned.

I suspect the issue is in the design - the auto-pin was probably designed to increase the visibility of completely new add-ins, hence the nudge notification. But the auto-pinning is needed also for previously deployed add-ins. Centralized Deployment probably remembers the add-in was previously deployed (because of the same App ID) so neither auto-pinning nor nudge notification are triggered.

## Your Environment
Our add-in is a business-line add-in (not available as Store add-in).
Manifest can be provided upon request.
 
## Expected behavior
Add-ins deployed via Centralized Deployment before April 21, 2021 should be auto-pinned in Web Outlook when they are re-deployed or updated. They don't need to have the nudge notification (unless you can track whether the user has ever used the add-in).

## Current behavior
Add-ins deployed via Centralized Deployment before April 21, 2021 are **not** auto-pinned in Web Outlook when they are re-deployed or updated.

## Steps to reproduce
If you are able to control "_auto-pin admin-managed add-ins upon deployment_" in your test environment, then please follow these steps.
1. Make sure the "_auto-pin admin-managed add-ins upon deployment_" feature is disabled.
2. Deploy an add-in via Centralized Deployment.
3. Verify in Web Outlook that the add-in is now available only via the three dots menu.
4. Enable "_auto-pin admin-managed add-ins upon deployment_" feature.
5. Remove the add-in's centralized deployment and wait for it to be removed from the user's Web Outlook.
6. Re-deploy the add-in via Centralized Deployment.

-> Add-in is not auto-pinned to the ribbon of Web Outlook.

**Comment by atsopuronen** [comment]
Would you have any updates regarding this ticket?

**Comment by exextoc** [comment]
Currently there is no support for this feature. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by atsopuronen** [comment]
I have submitted an idea to Tech Community Page here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-ins-deployed-before-april-21-2021-should-be-auto-pinned-in/idi-p/3600742

**Comment by exextoc** [comment]
Keeping this as closed as it has been diverted back to the techcommunity page.
