### ISSUE TITLE
including office-js into an @angular/cli project fails to run production build

### ISSUE THREAD

**Issue by brugh** [OfficeDev/office-js#236]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Adding the @microsoft/office-js to an angular6 project will allow 
```
ng build --prod  --aot
``` 
to run correctly but when the site is opened, the debugger shows a console message 
``` 
Error: No NgModule metadata found for 'jg'.
```

## Expected Behavior
A correctly loading site like ``ng build`` without --prod produces

## Current Behavior
Site is not loading and the console gives an error:
Error: No NgModule metadata found for 'jg'.

## Steps to Reproduce, or Live Example
> ng new o365
> npm install @microsoft/office-js
> add 
```
<script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
```
to index.html

> change main.ts to: 
```
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}
declare const Office: any;
let reason: boolean = false;

Office.initialize = () => {
  reason=true;
  platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => {
      console.log(err);
  });
};

setTimeout(() => {
  if (!reason) {
    platformBrowserDynamic().bootstrapModule(AppModule);
  }
}, 1000);
```
> ng build --prod --aot
> upload files to https server

## Context
the developer site is slow to load and we need to run the site in production so our office add-in will run for our clients

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Windows 10 64-bit + Word 2016 + Office 365
* Host [Excel, Word, PowerPoint, etc.]: Word, Excel, Powerpoint, ..
* Office version number: 1803 build 9126.2275
* Operating System: Windows 10 64-bit
* Browser (if using Office Online): Edge, Firefox, Chrome

## Useful logs
please let me know what will help you

**Comment by brugh** [comment]
OH, and I enabled all polyfills as per documentation. The projects becomes VERY VERY slow though. Load times skyrocket from 1.5s to over 6s with polyfills enabled. Can office-js be build without them? If I only enable ```shim```, ```es7/reflect``` and ```zone``` the add-in loads fine, sideloaded into local office apps

**Comment by ElizabethSamuel-MSFT** [comment]
@JuaneloJuanelo Is there someone who can provide guidance for this situation? Thanks.

**Comment by JuaneloJuanelo** [comment]
sounds like @nokafor is the right person to follow up on this

**Comment by millerds** [comment]
This doesn't look like a DevX tooling project . . . it's adding Office.js to an existing Angular project.  I don't have any expertise in Angular to know how this works.  (note our Angular template doesn't use the angular cli so it's not the same thing).

**Comment by ElizabethSamuel-MSFT** [comment]
@slabereemsft Is Office.js performance in this case something you can speak to? Thanks.
