### ISSUE TITLE
Getting "Permission Denied" when using saveAsync with Outlook requirement set 1.6 - only for the users own events

### ISSUE THREAD

**Issue by lukesolar** [OfficeDev/office-js#2360]
Getting "Permission Denied" when using saveAsync with Outlook requirement set 1.6 
- This error only happen for events/items the user did create himself. For events someone else created, where he got invited, the function returns the result and item id just fine.

Affected users have M365 with Outlook 16 (Office 2019), build number 16.0.10382.20010, with highest requirement set 1.6 where we encounter the problem.

- The Add-in works fine from Outlook on the Web
- The Add-in works fine for Outlook 16 (Office 365), build number 16.0.14729.2019 (requirement set 1.8+)
- The Add-in does not work for Outlook 16 (Office 2019) build number 16.0.10382.20010 (highest requirement set supported here is 1.6)

## Expected Behavior
The method saveAsync in requirement set 1.6 should return a valid result and the ID of the item. 

## Current Behavior
The function returns (only for items created be the user himself) an error.
```
{
"description":"Permission denied",
"number":-2146828218,"stack":
"Error: Permission denied\n   at b.prototype.execute (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:20:98268)\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:20:187519)\n   at z (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:20:187490)\n   at H (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:20:187044)\n   at U (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:20:186043)\n   at Zr (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:20:242447)\n   at getItemIdAsync"
}
```

## Steps to Reproduce, or Live Example
1. Install Outlook with Office 2019 and the mentioned build number if possible
2. Use the method saveAsync in a Compose context (we use a Task Pane) https://docs.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-1.6#outlook-office-messagecompose-saveasync-member(1) 

## Your Environment

* PC desktop
* Host: Outlook
* Office version number: 16 (Office 2019) - Requirement Set 1.6 
* Operating System: Win

## Useful logs
`Permission denied\n   at b.prototype.execute (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:20:98268)\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:20:187519)\n   at z (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:20:187490)\n   at H (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:20:187044)\n   at U (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:20:186043)\n   at Zr (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:20:242447)\n   at getItemIdAsync
`

**Comment by AkhileshShah-MS** [comment]
Thanks for raising the issue, @lukesolar. @exextoc Could you please help look into this?

**Comment by exextoc** [comment]
Question about the repro, @lukesolar , are you seeing this error on some or all machines with Office 2019 (if so, any rough estimate on how many)?  Is the repro machine specific (same machine, different account)?  
Do you see errors with other async API calls?

**Comment by exextoc** [comment]
Other questions: do you see this repro in ScriptLabs (https://appsource.microsoft.com/en-us/product/office/WA200001603?src=office&tab=Overview) or with saveAsync in mail (instead of event)?

**Comment by exextoc** [comment]
I want to also add that I cannot repro this issue so far.  I am using 16.0.10382.20010.  To repro, I create a new meeting and run this code in the addin taskpane:

Office.context.mailbox.item.saveAsync
(
	function(asyncResult)
	{
          console.log(asyncResult.value);
	}
);

**Comment by lukesolar** [comment]
Hi @exextoc thanks for your answers!
I'll ask the affected customer to give the script lab a try. Unfortunately I could not manage to install that specific Outlook version in my own dev environment. We have a MS Developer Account, do you know how we can install that specific Outlook version?

**Comment by lukesolar** [comment]
The Script Lab Add-in is very useful! Thanks for sharing!

Can you try and see if in your setup what the supported requirement sets are? Because what surprises me, is that if we run that for the affected users, it appears that the highest requirement set is 1.6.

Here's some code which might help. 
```
function _getRequirementsSetCheckList() {
  return {
    "1.1": Office.context.requirements.isSetSupported("Mailbox", "1.1"),
    "1.2": Office.context.requirements.isSetSupported("Mailbox", "1.2"),
    "1.3": Office.context.requirements.isSetSupported("Mailbox", "1.3"),
    "1.4": Office.context.requirements.isSetSupported("Mailbox", "1.4"),
    "1.5": Office.context.requirements.isSetSupported("Mailbox", "1.5"),
    "1.6": Office.context.requirements.isSetSupported("Mailbox", "1.6"),
    "1.7": Office.context.requirements.isSetSupported("Mailbox", "1.7"),
    "1.8": Office.context.requirements.isSetSupported("Mailbox", "1.8"),
    "1.9": Office.context.requirements.isSetSupported("Mailbox", "1.9"),
    "1.10": Office.context.requirements.isSetSupported("Mailbox", "1.10"),
    "1.11": Office.context.requirements.isSetSupported("Mailbox", "1.11")
  };
}
console.log(_getRequirementsSetCheckList());
```

**Comment by exextoc** [comment]
As a FYI, I just realize Script Lab is not longer supported with IE browser, for details, see https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

In terms of the features supported in my installation of Office 2019, I am also getting up to 1.6.  {"1.1":true,"1.2":true,"1.3":true,"1.4":true,"1.5":true,"1.6":true,"1.7":false,"1.8":false,"1.9":false,"1.10":false,"1.11":false}.  I am going to confirm if this is correct (our documentation indicates 1.7. https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#:~:text=Outlook%20add-ins%20declare%20what%20API%20versions%20they%20require,API%20requirement%20set%20that%20supports%20the%20add-in%27s%20scenarios). However, on my installation with 1.6 support, saveAsync is working fine on my end. 

Are you saying that you have users with Office 2019 version with higher requirement sets and saveAsync works for these users? It might also be useful to understand if Office 2019 was installed or updated differently for the affected users.

For Office 2019 installation, I am not familiar with the licensing or account requirement.  See if https://docs.microsoft.com/en-us/DeployOffice/overview-office-deployment-tool is helpful, the tool includes a configuration to install Office 2019.

**Comment by lukesolar** [comment]
Hi @exextoc - Thanks for your comments and insights. We could not reproduce this reliably. The affected users were updated to the Office365 version of Outlook which eliminates this problem. Closing this for now.
