### ISSUE TITLE
Excel crash in Mac Desktop app when focussing other workbook 

### ISSUE THREAD

**Issue by Alex0cean** [OfficeDev/office-js#2361]
When we show toaster messages to the user we first call the API Office.addin.showAsTaskpane(); to ensure that the add-in task pane is visible. In Mac Excel the task pane is opened in the currently active Excel window and thus potentially not in the one where our add-in is running.
See attached video. Our add-in only runs in the left window. The right window is just a blank Excel workbook. But when the user focuses on the right window then the Office.addin.showAsTaskpane(); call (triggered from our runtime in the left window) opens the pane in the window on the right. If you then click in the left window again Excel completely crashes (not part of the video).
The API works fine in Windows Excel. Even if the Excel workbook is no the active one the API opens the task pane in the correct window.

## Your Environment
Excel 16.56 for Mac
 

https://user-images.githubusercontent.com/80747078/149165564-71542203-7a47-4d00-b747-d9666a3b4fa8.mov

**Comment by AkhileshShah-MS** [comment]
Thanks for raising the issue, @Alex0cean. @dingjin-ms could you please help with this.

**Comment by yuc014** [comment]
Hi @Alex0cean,

Thanks for reaching us. 

I tried some other addins on Excel 16.56 for Mac, and they look fine.

Then I wrote a gist: https://gist.github.com/yuc014/90ebf43c7116fa57f984437966d9478a. And it also looks fine.
See my video:

https://user-images.githubusercontent.com/87364252/149303835-78733bc1-04b7-48b5-81e0-442379499982.mov




Could you send me your addin code snippet and repro steps? Then I can try to repro this issue.

And also for the repro excel files in your video.

Thanks.
