### ISSUE TITLE
Excel for Mac - Broken icons when displaying on the extend screen

### ISSUE THREAD

**Issue by teerayutRefinitiv** [OfficeDev/office-js#2362]
![image](https://user-images.githubusercontent.com/97648281/149254064-85012990-8346-4f6e-96e4-71f1009a3264.png)

I have tried with many resolutions on the extend screen, all are failed
![image](https://user-images.githubusercontent.com/97648281/149255737-ddbefb32-e8b3-4bb2-8e1c-7041075ffd1c.png)
![image](https://user-images.githubusercontent.com/97648281/149255760-1aa0419e-fa93-4ff8-a8a8-83f38505b917.png)
![image](https://user-images.githubusercontent.com/97648281/149255783-ffc268cc-15be-4275-aab5-26cecae8201b.png)
![image](https://user-images.githubusercontent.com/97648281/149255806-d621af2f-3f82-4b61-8ce9-7b05538c5874.png)
![image](https://user-images.githubusercontent.com/97648281/149255847-636fb7a3-fbb1-4a44-be67-96017c43ba52.png)

**Detail** 
Mac Os :  Big Sur
Extend screen : Dell UltraSharp 24 Monitor - U2414H
Example icon : 
-   https://cdn.refinitiv.com/public/libs/rfo/assets/images/excel-comp-list-16.png
-   https://cdn.refinitiv.com/public/libs/rfo/assets/images/excel-comp-list-32.png
-   https://cdn.refinitiv.com/public/libs/rfo/assets/images/excel-comp-list-64.png
-   https://cdn.refinitiv.com/public/libs/rfo/assets/images/excel-comp-list-80.png
-   https://cdn.refinitiv.com/public/libs/rfo/assets/images/excel-palette-16.png
-   https://cdn.refinitiv.com/public/libs/rfo/assets/images/excel-palette-32.png
-   https://cdn.refinitiv.com/public/libs/rfo/assets/images/excel-palette-64.png
-   https://cdn.refinitiv.com/public/libs/rfo/assets/images/excel-palette-80.png

Example code :
```
<Icon>
          <bt:Image size="16" resid="compList16x16" />
          <bt:Image size="32" resid="compList32x32" />
          <bt:Image size="64" resid="compList64x64" />
          <bt:Image size="80" resid="compList80x80" />
</Icon>
```

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.56(21121100)
* Operating System: Mac Big Sur
* Browser (if using Office on the web): It worked

**Comment by AkhileshShah-MS** [comment]
Thanks for raising the issue @teerayutRefinitiv . @dingjin-ms could you please help with this?

**Comment by yuc014** [comment]
Hi @teerayutRefinitiv,

Thanks for reaching us.

I want to confirm some more details about your issue:
1. Is any other icons in Ribbon appear same issue? Or any other addin's icon face same issue?
2. Have you tried both Mirror and Extend display? And both not work?
3. Have you change your scale rate?
![image](https://user-images.githubusercontent.com/87364252/149461636-38d629b3-58e7-4844-a2b7-9de81ceb72ee.png)
4. Could you try to close your laptop and only work on extend screen, to see if the issue still appear.

And wish you could give me your code snippet, then I could try to repro it. Thank you.

**Comment by teerayutRefinitiv** [comment]
Sorry for late reply.
I'll try to check it again and I'll reply to you.
