### ISSUE TITLE
PowerPoint on the web : The icons are not show on the right side of the task pane.

### ISSUE THREAD

**Issue by donlawatch** [OfficeDev/office-js#2363]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
When I open the task pane in desktop app, the icons show on the right side of the task pane but not on the web.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: -
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome, Edge
 
## Expected behavior

Both desktop app and web, The icons show on the right side of the task pane. 

## Current behavior

Only the desktop app shows the icons on the right side of the task pane.

# Provide additional details

An `<IconUrl />` has already been defined in the manifest file.
Example code `<IconUrl DefaultValue="https://cdn.refinitiv.com/public/libs/rfo/assets/images/R_32x32.png" />`

## Useful logs

- Desktop app
![image](https://user-images.githubusercontent.com/80447115/149269280-afd9c11f-e8e2-4b43-9a1a-b94c65cd61dd.png)

- Web
![image](https://user-images.githubusercontent.com/80447115/149269332-d9f0870c-8345-4f84-98f3-3bfdc48f31c7.png)

**Comment by AkhileshShah-MS** [comment]
Thanks for raising the issue @donlawatch . @lliu113 could you please help with this?

**Comment by lliu113** [comment]
@donlawatch - apologies for the late response. I can repro, bug has been opened (internal bug id: 5755662)

**Comment by puripats** [comment]
Hi team, Is there any progress on this issue?
