### ISSUE TITLE
Support for context menus in Outlook Web Add-ins

### ISSUE THREAD

**Issue by lukesolar** [OfficeDev/office-js#2364]
As it seems, currently Outlook Web Add-ins do not support context menus (e.g. the menu which appears when the user right clicks on an appointment).
However, native Add-ins seem to support this (There is a "Send to Onenote" button which appears on Outlook).

This functionality is very useful, especially since Web Add-ins also do not support tasks panes to stay always open. This causes that the user needs to reopen the task pane again and again every time he opens an appointment. 

Our use case would be: right click "Take Notes" which opens a Task Pane where the user can take meeting notes. 

Looking forward to get the OfficeDev's feedback on this!
Thank you
Lukas

**Comment by AkhileshShah-MS** [comment]
Thanks for raising this request @lukesolar . @exextoc could you please take a look into this feature request.

**Comment by exextoc** [comment]
In your scenario, would users prefer having a pinned (always open) task pane or the context menu in calendar?  We are also interested in your insights on the preference on right click "Take Notes" over having a "Take Notes" in the ribbon.

Currently the feature: pinned task pane in calendar or context menus, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](https://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by lukesolar** [comment]
Posted here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/context-menus-in-outlook-web-add-ins/idi-p/3065601

**Comment by exextoc** [comment]
@lukesolar Would like to clarify, the previous question we asked. Would pinning on the Calendar also solve this issue?

**Comment by lukesolar** [comment]
@exextoc Yes that would be even better for the customer who requested this. However, having additional options in the context menus is still also valuable. - Is there any chance to get one or both of the features short/mid-term? Is it under active development? Thanks!

**Comment by exextoc** [comment]
I unfortunately cannot comment on any work that the team is doing, but I would not expect either feature in the short/mid term. Pinning in Calendar is something that has been discussed before, and is more likely to be done at some point...but nothing can be committed to at this time. 

Adding stuff to the tech community forum is the best way to change priority of these work items. (which you've already done)

**Comment by claell** [comment]
Just out of curiosity. What is the scope of the Web Add-ins? Are they planned to replace the native, legacy Add-ins or is it just meant to be an addition with limited capabilities?

Maybe not the right place to ask this (sorry), but seeing this closed, indicates that it is currently more seen as some addition with limited capabilities and not wanted to really replace the old Add-ins?

**Comment by Tsathyapriya80** [comment]
Any updates for this feature/issue??

**Comment by gangstabob** [comment]
Do you have any updates when context menu customization would be available for web-based Outlook?
