### ISSUE TITLE
The text "Bottom of Form" shows up when not wanted sometimes (please un-close 2232)

### ISSUE THREAD

**Issue by gitcnd** [OfficeDev/office-js#2365]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Please un-close this was-not-fixed issue: https://github.com/OfficeDev/office-js/issues/2232

**Comment by gitcnd** [comment]
demo: https://autode.sk/3I1CdZP

**Comment by gitcnd** [comment]
Another demo: https://autode.sk/33mkspo

**Comment by AkhileshShah-MS** [comment]
@exextoc This issue is in continuation of #2232 . Please take required action to help fix the issue. 
@gitcnd previous issue was closed automatically as it was waiting for author's response on additional details for multiple days. Thanks for providing the details and team would look into it.
