### ISSUE TITLE
[Outlook For Mac] Need Programatic way to differentiate between Old UI and New UI

### ISSUE THREAD

**Issue by harshdesh7** [OfficeDev/office-js#2366]
# Need a way to programatically differentiate between using Outlook for Desktop Old UI vs New UI

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: MacOS
* Host [Excel, Word, PowerPoint, etc.]: Outlook for Desktop
* Office version number: 16.56
* Operating System: MacOS Big Sur
* Browser (if using Office on the web): N/A
 
## Expected behavior
Within office.context interface, there should be a metric which tells which UI of outlook one is using (new or old). Here is the documentation to the interface: https://docs.microsoft.com/en-us/javascript/api/office/office.context?view=outlook-js-1.1#platform

## Current behavior

currently office.context.platform only says 'Mac' on MacOS and office.context.diagnostics lists out 'Mac' and 'Outlook' but not whether the Old UI or New UI is being used

## Steps to reproduce

1. Find some code that references office.context
2. Debug (probably inside web browser), hover over office.context, spot platform and diagnostics

## Context

Currently working on a product where I need to know if I am using old or new ui so I can determine whether I need to make calls to the EWS or MS Office API 

## Useful logs

![Screen Shot 2022-01-13 at 5 33 03 PM](https://user-images.githubusercontent.com/39777192/149430824-758006e1-cb02-4d2c-b4f2-d3ce74d14040.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by AkhileshShah-MS** [comment]
Thank you for raising the request, @harshdesh7.  @macOutlookExtensibility please help with the request.

**Comment by exextoc** [comment]
In the Outlook Old UI, the maximum API Set we support is 1.8. So you could leverage the following API to know whether it is an old UI or new UI.

if (Office.context.requirements.isSetSupported('Mailbox', '1.9')) {
  // Perform actions for new UI
}
else {
  // Perform actions for old UI
}
