### ISSUE TITLE
Word paragraphs and ranges return incorrect text with arrow icons

### ISSUE THREAD

**Issue by fiftydegrees** [OfficeDev/office-js#2368]
Calling the getter `.text` on a paragraph or range returns incorrect text if there is an arrow-like icon in the text.

![image (2)](https://user-images.githubusercontent.com/5269843/149552687-3b1b2dbb-ffb3-4598-9bad-1c5c7ddd9257.png)

## Expected Behavior

The actual text is being returned with a Unicode character instead.

## Current Behavior

The text is being returned with an opening parenthesis in place of the arrow icon, leading us to a misunderstanding of the text.

Based on the above screenshot, the text returned is the following:

```
Prmier sujet ( je sait pas quoi\nDeuxième sujet ( on ne voit rien là dedans 
```

## Steps to Reproduce, or Live Example

In any Word document, insert a sentence and press `-`, `-` then `>` keys to trigger a replacement. The issue occurs as soon as the [Wingdings font](https://en.wikipedia.org/wiki/Wingdings) is being used.

## Context

We provide a spellchecking solution for our end-users and the opening parenthesis leads to a misunderstanding of the text and false-positive (we notice the users that there is unclosed parenthesis but they cannot see any parenthesis).

## Your Environment

Platform: PC desktop, Mac
Host: Word
Office version number: latest M365 subscription
Operating System: macOS or Windows
Browser (if using Office Online): Edge

**Comment by RuizhiSunMS** [comment]
Thank you for reporting this issue!
We found it a bug and have put this into our backlog with an ADO id of 5726980. 
Since it's hard to share timelines at this point, we'd reply if the bug was fixed.
