### ISSUE TITLE
Problem with Icons of Addin Commands in Outlook 2016 Desktop

### ISSUE THREAD

**Issue by mrfloppy82** [OfficeDev/office-js#237]
Hello,

i have a problem with icons in the Ribbon bar. There are not shown, only the standard fallback icons (blue) are shown. My Outlook Version is 2016 build 1807.

Here is a snippet of my Manifest.xml:

                <Control xsi:type="Button" id="dvelop.Office.Button.Show.d3one">
                    <Label resid="dvelop.Office.Label.Show.d3one" />
                    <Supertip>
                      <Title resid="dvelop.Office.Label.Show.d3one" />
                      <Description resid="dvelop.Office.Des.Show.d3one" />
                    </Supertip>
                    <Icon>
                      <bt:Image size="16" resid="dvelop.Office.Icon.Show" />
                      <bt:Image size="32" resid="dvelop.Office.Icon.Show" />
                      <bt:Image size="80" resid="dvelop.Office.Icon.Show" />
                    </Icon>
                    <Action xsi:type="ShowTaskpane">
                      <SourceLocation resid="dvelop.Office.Url.Home" />
                      <SupportsPinning>true</SupportsPinning>
                    </Action>
                  </Control>
               
      <Resources>
        <bt:Images>
          <bt:Image id="dvelop.Office.Icon.Store" DefaultValue="https://d3one1.dev.local/groupware/static/Images/store32x32.png" />
		  <bt:Image id="dvelop.Office.Icon.Show" DefaultValue="https://d3one1.dev.local/groupware/static/Images/d3logo32x32.png" />
        </bt:Images>
      </Resource>

The Images are 32x32 Pixel. I have a simular Addin with the same icons for Word. In Word, the icons are shown correct.

Regards,

Nico

**Comment by exextoc** [comment]
@mrfloppy82 Your Resources XML element is not correctly closed. It should end with </Resources> instead of </Resource>. Is this just a copy/paste typo here? Your manifest won't install with this typo. That said, the first thing to check is whether you are able to access the icon if you copy/paste its url into a web browser on your machine.

**Comment by mrfloppy82** [comment]
That is only a copy paste Problem. The original Manifest is valid. I can call the URL in a Webbrowser and the icons are shown correctly. Must they have a special format for Outlook?

**Comment by exextoc** [comment]
PNG file formats are fine for Outlook. Can you try with an icon from a publicly available endpoint that we can also access in-house? If that doesn't work, and you don't have any sensitive data in your manifest, kindly share it with us so that we can try it out on our end to see if we can repro this issue.

**Comment by mrfloppy82** [comment]
I have tried it with the following icon:

https://d1nhio0ox7pgb.cloudfront.net/_img/v_collection_png/48x48/shadow/ok.png

It does not work. I attach our manifest

[OutlookAddin.zip](https://github.com/OfficeDev/office-js/files/2356104/OutlookAddin.zip)

**Comment by exextoc** [comment]
Thanks for providing the manifest for your add-in.
I tried it and and the icons are showing up for me.
My build of Outlook is more recent though.

Is this problem affecting all add-ins you have installed?
If you don't have any add-in installed, can you install one (for example Evernote) using the "Get Add-ins" button in the ribbon and let me know if the icon show up?

Here's a screenshot of the icons from your manifest showing up in my ribbon, together with the icon for the Evernote add-in.

[https://i.imgur.com/x63LkgI.png](https://i.imgur.com/x63LkgI.png)

**Comment by sharaaU7** [comment]
This is in the context of Word add-in (agave). I am trying to change the icon for the button, but new icon is not being picked up. I  still see the default icon.
 
![image](https://user-images.githubusercontent.com/6740088/63054108-18175700-be98-11e9-9b0b-7b70b0154322.png)


So far, I have tried cleaning the cache, renaming file, updating manifest to reflect the new name, making edge browser request every time from the server. 
Does anyone have any pointers?

**Comment by jd-piq** [comment]
Having the same issue in Excel desktop (16.0.11901.20170) 64-bit

**Comment by ElizabethSamuel-MSFT** [comment]
@mrfloppy82 @sharaaU7 @jd-piq Can you let us know if this still repros for you in your respective host application?

Thanks.
