### ISSUE TITLE
Show result for Excel Custom Function in Function Arguments dialog

### ISSUE THREAD

**Issue by beatrixmorar** [OfficeDev/office-js#2371]
Hi,

Is it possible to show the formula result for a custom function in the Function Argument dialog, like it is done for the built-in functions in Excel?

Example for SUM built-in function:
![image](https://user-images.githubusercontent.com/52167887/149799370-1703d8ee-10f1-425f-bba0-a38a3089fcbe.png)

Would like to achieve the same for my custom function:
![image](https://user-images.githubusercontent.com/52167887/149799510-fff84760-825d-488c-92e9-1aa56dabf193.png)

**Comment by JHJ-MS** [comment]
Sorry, this feature is not supported currently. We track feature requests on https://aka.ms/m365dev-suggestions  You can add your request here. Feature requests are considered when we go through our planning process. Thanks.

**Comment by beatrixmorar** [comment]
Thank you for the quick response. I have added a feature request on the developer platform:
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/excel-custom-functions-display-formula-result-in-function/idi-p/3064211#M634
