### ISSUE TITLE
Store email in separate data store

### ISSUE THREAD

**Issue by Iso5786** [OfficeDev/office-js#2376]
Hi,

currently within an Outlook web addon via office-js it is not possible to store a mail in a separate data store (outside the users mailbox).
Via VSTO this is possible.

We would like to have this feature available via office-js as we are working on an encryption solution, and want to give the recipient of a mail the possibility to store unencrypted mails in a local data store, such that they are not synchronized with the mail server.

Regards,
Daniel

**Comment by exextoc** [comment]
Hi @Iso5786, Thanks for raising the request. Kindly file a feature request, at https://aka.ms/M365dev-suggestions .

**Comment by Iso5786** [comment]
Hi @exextoc,
ok, I did: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/officejs-outlook-store-email-in-separate-data-store/idi-p/3065578#M637

Regards,
Daniel
