### ISSUE TITLE
[Word Online] Error on document body search with escaping symbols

### ISSUE THREAD

**Issue by yarikzub** [OfficeDev/office-js#238]
I try to find text between curly brackets with the following code. 

```
Word.run(function (context) {
	const searchResults = context.document.body.search('\\{*\\}', { ignoreSpace: false, matchWildCards: true });
	context.load(searchResults, 'text');
	...
});
```

Everything works fine in Windows and Mac Word. But in Word Online (Chrome, IE11) I have following error with the same plugin:

`{"name":"RichApi.Error","code":"InvalidArgument","traceMessages":[],"innerError":null,"debugInfo":{"code":"InvalidArgument","message":"The argument you provided is not valid. Check the OfficeExtension.Error.debugInfo for more information.","errorLocation":"Body.search","statement":"var search=body.search(...);","surroundingStatements":["...","var body=root.body;","// Instantiate {body}","var v=Microsoft.WordServices.SearchOptions.newObject();","v.ignoreSpace=...;","v.matchWildCards=...;","// >>>>>","var search=body.search(...);","// <<<<<","// Instantiate {search}","search.load([\"text\"]);"],"fullStatements":["Please enable config.extendedErrorLogging to see full statements."]}}`

**Comment by Rick-Kirkham** [comment]
When you are programmatically searching, you put the character that you want to escape between to square brackets, instead of putting a backslash in front of it. See https://docs.microsoft.com/en-us/office/dev/add-ins/word/search-option-guidance#escaping-the-special-characters
