### ISSUE TITLE
Outlook desktop (new Mac OS X UI preview): addFileAttachmentFromBase64Async throws code: 5001, message: "An internal error has occurred." in pinned add-in

### ISSUE THREAD

**Issue by guzman-rc** [OfficeDev/office-js#2382]
# Provide required information needed to triage your issue
In an Outlook add-in (**new Mac UI preview**) for compose mode, we are using the addFileAttachmentFromBase64Async method to add attachments. In Outlook desktop "**new Mac UI preview**", the "Internal Error" occurs if the add-in's pane is pinned.

In Mac Outlook desktop "**Classic UI**" this method work correctly.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft Outlook for Office 365 MSO version 16.57 (22011101)
* Operating System: Monterey (v.12.0.1)
 
## Steps to reproduce or live example

1. Install MetaClean for Outlook from Microsoft App Source (https://appsource.microsoft.com/en-us/product/office/WA200003633)
2. Start Outlook and **select new Mac UI preview** for Outlook.
3. Create a new email in Outlook desktop.
4. Click "MetaClean for Metadata" button.
5. Click on the add-in’s pane and select a file to attach.
6. The code that causes the error is (See Screenshots from Web Inspector):
`function sendFileToOutlook(file, attachmentName) {
		var reader = new FileReader();
		
		try {
			if(fileBuffer.length == 0)
				showErrorWarningMessages();
			
			reader.readAsDataURL(file);
					   
			reader.onload = function () {
				//Remove data url part
				var base64String = reader.result
					.replace("data:", "")
					.replace(/^.+,/, "");
								
				//Adjuntamos el fichero procesado a Outlook
				Office.context.mailbox.item.addFileAttachmentFromBase64Async(
					base64String,
					attachmentName,
					{ isInline: false },
					function (asyncResult) {
						if (asyncResult.status === Office.AsyncResultStatus.Failed) {
							var attachErrorMessage = 'An error occurred when attaching to Outlook';
							
							if(asyncResult.error.message != null && asyncResult.error.message.length > 0)
								attachErrorMessage += ' :::: ' + asyncResult.error.message;
											
							fileNameMessages.push({message: attachErrorMessage, fileName: attachmentName, errorCode: 1});
							showErrorWarningMessages();
											
						} else {
							if(fileBuffer.length > 0)
								processFile(fileBuffer.shift(), false);
							else 
								showErrorWarningMessages();
						}
				});
			};
					   
			reader.onerror = function (error) {
				var errorMessage = 'An error occurred while loading file data';
							
				if(error.message != null && error.message.length > 0)
					errorMessage += ' :::: ' + error.message;
								
				fileNameMessages.push({message: errorMessage, fileName: attachmentName, errorCode: 1});
				
				if(fileBuffer.length > 0)
					processFile(fileBuffer.shift(), false);
				else 
					showErrorWarningMessages();
			};
		
		} catch(err) {
			var messageError = (err != null && err.message != null) ? 'An error occurred when attaching to Outlook :::: ' + err.message : 'An error occurred when attaching to Outlook';
							
			fileNameMessages.push({message: messageError, fileName: attachmentName, errorCode: 1});
			showErrorWarningMessages();
		}
	}`

# Provide additional details

1. In Mac Outlook desktop "**Classic UI**" this method work correctly.

## Context
This bug is causing complaints from our customers.

## Useful logs

- [ ] Console errors
- [ ] Screenshots from Web Inspector

Enable new Mac UI preview:
![OutlookMacError_3](https://user-images.githubusercontent.com/96702862/150674131-ba297cb0-8dc0-49e3-9d0c-edb152eb2e0f.png)

Debug from Web Inspector:
![OutlookMacError_1](https://user-images.githubusercontent.com/96702862/150651424-53b4b1af-c8ca-42f3-bcc7-3bd9b3625b78.png)

![OutlookMacError_2](https://user-images.githubusercontent.com/96702862/150651429-3a6fcd03-ed4c-44ef-abc0-ef92606a2184.png)

- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by JackTheDane** [comment]
Just want to chime in that we are also seeing the same error in an Event-Based context, where we have narrowed down the issue to the `addFileAttachmentFromBase64Async` method as well in Outlook Desktop for Mac with the new UI.

**Comment by exextoc** [comment]
Thanks for reporting the issue. We are looking into this.

**Comment by exextoc** [comment]
We used the add-in provided by you and for us it attaches the attachment as expected. Not sure if we are missing any step to reproduce the issue. Can you please share a video for the issue to help us understand more.

**Comment by guzman-rc** [comment]
The error appears randomly.
Please create new emails and attach files, the error will appear after several attempts.

**Comment by exextoc** [comment]
we are able to repro the issue with the following steps:
1. Install the add-in
2. Reply to an email
3. Switch to full compose mode
4. Close the full compose mode window
5. Click on "Resume Editing" button on the nested compose window
6. Open the add-in
7. Attach a file through the add-in

We see the below error in the add-in:
![7dc5034c-e67d-4184-99f7-6adb4ac0adea](https://user-images.githubusercontent.com/28549921/152326472-357f0a4a-757a-483a-88a6-a14e79badd6c.jpg)

Can you please confirm is it the same for you?

**Comment by guzman-rc** [comment]
Yes, that is the error.
The error only occurs in Outlook desktop "**new Mac UI preview**", in classic view the function call:
Office.context.mailbox.item.addFileAttachmentFromBase64Async
works correctly.

**Comment by hiddenkirby** [comment]
I'd like to add, that I am seeing this issue as well... but it is very specific to ONLY when composeType is 'forward' for me.  

I have a SO here - https://stackoverflow.com/questions/70975668/officejs-outlook-add-in-getting-internal-error-when-using-addfileattachmentfro

**Comment by exextoc** [comment]
@guzman-rc Thanks for reporting this issue. We are able to reproduce this issue internally. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by guzman-rc** [comment]
Can you provide an approximate date to resolve this issue?
We need to know the resolution date to inform our clients.
Thanks a lot.

**Comment by hiddenkirby** [comment]
This issue seems to have fixed itself for our add-in after the latest "Outlook for Mac" client update. I am however seeing a coincidentally new issue only on Outlook for Mac clients where the removeAttachmentAsync() method is returning success and not actually removing the attachment.  I can post a new issue, but the timing seems oddly related.  I'd be curious if @guzman-rc issue was also resolved in that last month on it's own. (or with a Client patch)

**Comment by guzman-rc** [comment]
The bug has not been fixed yet.
My version of Outlook for Mac is: 16.58 (22021501)

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 16.59 or later. When an updated build is available depends on the release channel a customer is on. 

[Outlook Add-ins Engineering Team]

**Comment by guzman-rc** [comment]
I just updated Outlook to build 16.59 and **now the error only occurs when I drag the files to the add-in’s pane**.
If I click on the add-in’s pane to select the files, the plugin works correctly.

**Comment by exextoc** [comment]
We are unable to reproduce this issue on our end with the given Outlook version and the add-in mentioned by you. Could you please send us a recording where you are able to reproduce the issue? Also, after you reproduce the issue, could you collect the diagnostics and provide us with the diagnostics ID. The steps to collect the diagnostics are as below.

Click on Help -> Collect Diagnostics.
Click OK when the Pop Up arrives
Copy the diagnostics ID generated and provide us with the same.

**Comment by guzman-rc** [comment]
This bug only affects Outlook for Mac OS (Monterey 12.2.1), Outlook Desktop version (16.59).
The bug occurs 90% of the time and **only occurs when files are dragged to the add-in’s pane** (new Mac UI preview and classic view).
**MetaClean for Outlook on Windows and Outlook Web works fine.**

**Comment by exextoc** [comment]
We could not reproduce the issue with the steps mentioned by you. So, if it is a consistent repro, then could you send the diagnostics ID and also record a video for the same. This will help us debug the issue.

**Comment by exextoc** [comment]
I was able to reproduce this issue in full compose mode. Thanks for reporting this issue regarding addFileAttachmentFromBase64Async. It has been put on our backlog. We, unfortunately, have no timelines to share at this point  

Internal tracking id: Office: 2576970

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.

**Comment by guzman-rc** [comment]
The issues have not yet been resolved.
Please, can you re-open the issue?

**Comment by guzman-rc** [comment]
In an Outlook add-in (new Mac UI preview) for compose mode, we are using the addFileAttachmentFromBase64Async method to add attachments. In Outlook desktop "new Mac UI preview", the "Internal Error" occurs if the add-in's pane is pinned.

In Mac Outlook desktop "Classic UI" this method work correctly.

My version of Outlook for Mac is: 16.65 (22091101)

This error was reported in January 2022 and we are still the same.

**Comment by exextoc** [comment]
We are now working on this bug on priority. We, unfortunately, have no timelines to share at this point.

**Comment by guzman-rc** [comment]
This issue is already being processed from this thread:
https://github.com/OfficeDev/office-js/issues/2890

**Comment by exextoc** [comment]
We have fixed this issue and fix will be available on build >=  16.67(22101904) .It will reach Production soon

**Comment by guzman-rc** [comment]
Ok, we will check in the next version if the bug has been fixed.
