### ISSUE TITLE
"saveAsync" breaks all image attachments of a message in Outlook for Mac 

### ISSUE THREAD

**Issue by shff** [OfficeDev/office-js#2383]
# Provide required information needed to triage your issue

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: macOS
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.56 (21121100)
* Operating System: macOS Big Sur 11.1 (20C69)
* Browser (if using Office on the web): N/A
 
## Expected behavior
Images **keep working** after calling saveAsync in an extension.

## Current behavior
Images show up normally for the Outlook user but **are broken** on the recipient's side.

## Steps to reproduce
1. Click "New Email"
2. Type a Recipient, Subject and Message
3. Drag an image from some local folder
4. Open the extension and have it call `saveAsync`
5. Send the email
6. The images **don't show up** correctly for the recipient.

<img width="260" alt="Screenshot 2022-01-24 at 17 29 35" src="https://user-images.githubusercontent.com/25377830/150826137-ff7b8702-6f92-428c-b572-829e4e6c3247.png">

## Link to live example(s)
Created using ScriptLab: https://gist.github.com/shff/5c7a686a97e268b26eaa0559354a4eb8

Here's the only important part:
```js
$("#run").click(run);

function run() {
  Office.context.mailbox.item.saveAsync(() => {});
}
```

# Provide additional details
You can either use the button as above or something like this:

```js
Office.onReady(() => {
  Office.context.mailbox.item.saveAsync(() => {});
});
```

## Context
I'm trying to create an extension that doesn't break functionality for users.

**Comment by shff** [comment]
Bug is still present in version `16.57 (22011101)`.

**Comment by thao33** [comment]
@shff i'm also using `saveAsync` at Outlook for Mac. But i can't reproduce your issue. Btw, I'm using `makeEwsRequestAsync` to sending email.

**Comment by fjaeger** [comment]
@thao33 We can reliably reproduce this bug. We do not use `makeEwsRequestAsync` but let the user send the message manually. The only reason we use `saveAsync` in the first place is to get the email's item identifier.

**Comment by exextoc** [comment]
we are not able to repro this at our end, can you please share the repro video or some test tenant where this issue is reproable.

**Comment by fjaeger** [comment]
You should be able to reproduce this by first dragging an image into a draft email and afterwards opening the task pane with the simple demo add-in source:

`Office.onReady(() => {
  Office.context.mailbox.item.saveAsync(() => {});
});`

When sending the email next, the image attachment will be broken. It seems that either the part in a multipart message is broken, e.g.

```
Content-Type: image/jpeg; name="image001.jpg"
Content-Description: image001.jpg
Content-Disposition: inline; filename="image001.jpg"; size=1;
	creation-date="Wed, 02 Feb 2022 16:28:21 GMT";
	modification-date="Wed, 02 Feb 2022 16:28:21 GMT"
Content-ID: <image001.jpg@01D8185A.3DDDD0E0>
Content-Transfer-Encoding: base64

AA==
```

or it is still referring to a local file source:

```
<img width="128" height="128" style="width:1.3333in;height:1.3333in" id="_x0000_i1026" src="file:////Users/fabian/Library/Containers/com.microsoft.Outlook/Data/Library/Application%20Support/Microsoft/Temp/~WRS%7bB2540FE8-E58A-1B43-8DC5-04B703F5780B%7d.fld/image001.png" alt="">
```

**Comment by exextoc** [comment]
We are not able to repro this issue at our end. Please share the demo test tenant where the issue is reproable.

**Comment by fjaeger** [comment]
Please try with the following demo add-in: https://d1eml6gikbp2iz.cloudfront.net/save-async-issue-demo/manifest.prod.xml

Then follow the following steps on Outlook for Mac (not using the new UI):

1. Create new email
2. Drag&drop an image into the email body
3. Open the demo add-in's task pane and click on the "Run" button to call `saveAsync`
4. Send the email
5. Open the email with a different email application, e.g. Apple Mail

You should see that the image is broken due to the call of `saveAsync`

**Comment by exextoc** [comment]
The manifest you have provided loads dummy "Contoso" website in the taskpane. 
We cannot reproduce the issue with the manifest provided.

**Comment by fjaeger** [comment]
@exextoc Please scroll to the bottom of that "dummy" sidebar. There should be a button at the bottom, which simply calls `Office.context.mailbox.item.saveAsync(() => {});`

**Comment by exextoc** [comment]
Unfortunately, we are still not able to reproduce. A few questions:
1. Is it broken only in different mail application? What happens if you open it with Mac-outlook, outlook on web?
2. Can you share test tenant where this is reproducible?
3. Can you share video of the issue?

**Comment by fjaeger** [comment]
You can find a video of the issue here: https://drive.google.com/file/d/1eNOjLEeWycOG5gKiRjUAKFMPfa-fwW3L/view?usp=sharing 

You can see that even when sending to myself and opening in Outlook for Mac, the image is broken after the add-in has been used during composing the email.

**Comment by exextoc** [comment]
Ah, that should have been our first question. I can see that you are trying it on old UI, can you check that you are facing the issue on new UI also.

**Comment by fjaeger** [comment]
I can confirm that this issue does not manifest anymore in the new Outlook UI for Mac. 

Do you still work on issues for the legacy Outlook UI on Mac?

**Comment by exextoc** [comment]
Thank you for sharing this issue. As a workaround, users can switch to the New Outlook for Mac experience which works as expected. We are not prioritizing this fix on classic Mac UI; please reopen the issue in case the workaround does not solve your scenario.
