### ISSUE TITLE
Word Add-In: Error Installing Add-In via AppSource Link ("Can't Open File")

### ISSUE THREAD

**Issue by MorganWilliamson** [OfficeDev/office-js#2384]
# Provide required information needed to triage your issue
We utilize a link from AppSoure to allow our customers quick installation of our add-in. Previously, they would only need to click the link to have our add-in installed, added to the ribbon menu, and ready to use. Following a recent update (on January 4th, 2022), this link no longer works. Instead, users will now be met with an error ([screenshot here.](https://lh3.googleusercontent.com/pw/AM-JKLURFE2BZ6j4b-Mv3FoIkbNGod_m8nVFdFjILQMqcR3iBfG65a2ydzVLIsMFX14_XJ1bEZFKwPj9xOh-CA5SKGMekPjj_qMq_Ostw7yCF-5TtQX-KcSJlFa_mgiaLYt5VTAWsmlm6_eLs22aee7KB7M=w276-h316-no)) 

We have noticed that other add-ins appear to be facing the same issue. This is not exclusive to any one platform, nor have we performed any changes to the link or our environment that would cause this error. We believe the timing can be matched to the [Current Channel release](https://docs.microsoft.com/en-us/officeupdates/current-channel#version-2112-january-04) on January 4th. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.57 (22011101)
* Operating System: macOS Big Sur (Version 11.6)
 
## Expected behavior

When users click on the link we provide, Microsoft Word will automatically open, our add-in is installed, added to the ribbon menu, and are then informed that installation is complete. We've had this link working in a button on our installation page so that our users can install our add-in with a single click.  

## Current behavior

Users click the link, Word opens, and the error is triggered at this point. Installation does not complete as expected. See attached screen recording [here](https://photos.google.com/share/AF1QipM38i3_yZo7UbceyVkqZ2YZ_4f5FOHXnBunxLzU8Svx7uC3qWqtyPkSKwH8LhxjHQ/photo/AF1QipO5RW985LlPIgOjXTuFDeErvOZTnd9fLwtPx1E-?key=akxNNHVPS01Tc1RsZ3BsRlhCYkJ0Y2UzSk8zQnBB).

The add-in can be installed by opening the Office Add-in Store inside of Word. Users can search for our add-in and click to install it there, which functions as expected. However, this is not optimal and is not the user experience that we have previously been able to offer. 

## Steps to reproduce

1. Copy and paste the complete AppSource Link listed below. Error should prompt as soon as you hit enter.
2. To verify that the alternative method is working, open a new document in Microsoft Word
3. Click "Insert" -> "My Add-ins" -> "Store"
4. Search for "Woodpecker" (there should only be one result)
5. Click "Add" -> Check the box to accept Terms & Conditions -> "Continue"

The alternative method should currently work, our add-in should appear in the ribbon menu as we expect from the AppSource Link.

## Link to live example(s)

1. **AppSource Link**: ms-word:ofe%7Cu%7Chttps://store.office.com/addinstemplate/en-001/f8c92b89-a710-441c-a904-2f069c07975e/WA104381028/r_woodpeckerweb.com/Woodpecker-Legal-Document-Automation.docx

## Context

Prior to this issue, we were able to offer customers a seamless installation experience. Taking out the extra installation steps allows us to simplify the process for our customers. As a small team, the extra time required to walk customers through the installation process can slow down our effectiveness in the onboarding phase and overall. 

Ideally, we would like the one-click installation to work again. The simplicity of having a single button for our customers to click made installation and onboarding much smoother, and reduces the chance of a new issue spiking up when existing users need to reinstall. Our preferred solution is for this to work the way it did at the start of this month and prior. 

Any acknowledgement, update, or assistance here would be greatly appreciated. 

## Useful logs

- [ ] Console errors
- [x] Screenshots
    - [Screenshot](https://lh3.googleusercontent.com/pw/AM-JKLURFE2BZ6j4b-Mv3FoIkbNGod_m8nVFdFjILQMqcR3iBfG65a2ydzVLIsMFX14_XJ1bEZFKwPj9xOh-CA5SKGMekPjj_qMq_Ostw7yCF-5TtQX-KcSJlFa_mgiaLYt5VTAWsmlm6_eLs22aee7KB7M=w276-h316-no)
    - [Screen recording](https://photos.google.com/share/AF1QipM38i3_yZo7UbceyVkqZ2YZ_4f5FOHXnBunxLzU8Svx7uC3qWqtyPkSKwH8LhxjHQ/photo/AF1QipO5RW985LlPIgOjXTuFDeErvOZTnd9fLwtPx1E-?key=akxNNHVPS01Tc1RsZ3BsRlhCYkJ0Y2UzSk8zQnBB)
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by gkarmelich** [comment]
Is there any update on this? I am also seeing this bug and I have been unable to get any support from Microsoft. Every channel (Azure team, Office 365 help) I have contacted has not been able to help. This issue has caused much confusion to our users and it is concerning nobody on the Microsoft team has any idea about this.

**Comment by RuizhiSunMS** [comment]
Sorry for delay @gkarmelich , my colleagues still have to do some discussions on it.

**Comment by RuizhiSunMS** [comment]
Hello @gkarmelich , sorry for such delay on this issue.  
We had some investigations about this with other teams. And the following suggestions are what we got.
1. The reason why you can't install your add-in by clicking previous link is that the link has been changed. Now the link is https://pages.store.office.com/addinsinstallpage.aspx?assetid=wa104381028&rs=en-us&correlationid=42fbddf5-50c5-8eed-5ad2-f3330b1d8f0finstall
2. That link is not generated by our side or other team we discussed with( could be generated by Store we guess). As far as we understood that the link will not be changed usually but indeed it can be occasionally(like this case).  

Hope these can be helpful.

**Comment by gkarmelich** [comment]
Thanks for the update @RuizhiSunMS. We have noted this for the future.

**Comment by RuizhiSunMS** [comment]
Close this issue.
Do please contact us if any block happened.
