### ISSUE TITLE
Custom Outlook add-in grayed out Quick Access Toolbar options

### ISSUE THREAD

**Issue by Pradhi15** [OfficeDev/office-js#2385]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **PC Desktop**
* Host [Excel, Word, PowerPoint, etc.]: **Outlook**
* Office version number: **2016**
* Operating System: **Windows 10**
* Browser (if using Office on the web): ______
 
## Expected behavior

Quick access options should be available even after addin is installed

## Current behavior

Once the addin been installed, Quick access toolbar options are grayed out. 

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Is this custom Outlook Add-in built using the [modern Office add-in's framework](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins), or is it built using the [COM/VSTO framework](https://docs.microsoft.com/en-us/visualstudio/vsto/getting-started-programming-vsto-add-ins?view=vs-2022)?

**Comment by Pradhi15** [comment]
Hello,

It is built using COM/VSTO framework...
And it's not publicly available. It has to stay inside our network, hence i cannot share the addin with you too

**Comment by Pradhi15** [comment]
Hello,

Please let me know if you need further details on this.

**Comment by exextoc** [comment]
Unfortunately, office-js refers to Office add-ins built using the modern web framework.
For help on COM/VSO add-ins, please post in the Outlook forum : https://answers.microsoft.com/en-us/outlook_com/forum
