### ISSUE TITLE
EnhancedLocation returns old locations after attachment is added to appointment

### ISSUE THREAD

**Issue by v-somov** [OfficeDev/office-js#2388]
When editing an appointment in OWA if you change the locations in the appointment editor and add attachment and then add new locations when you call `Office.context.mailbox.item.enhancedLocation.getAsync` it returns old locations, & not any new locations added by the user.
Subscribe to the `Office.EventType.EnhancedLocationsChanged` event also doesn’t work as expected.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: OWA
* Browser (if using Office on the web): Chrome, Safari
 
## Expected behavior
`Office.context.mailbox.item.enhancedLocation.getAsync` should return all locations that the user has entered into the appointment editor, not old locations from the previous appointment state. 

## Current behavior
Old locations are returned. For instance, if:
- location added in appointment editor or through `api` 
- attachment is uploaded by user
- location added in appointment editor or through `api`.
- Calling `Office.context.mailbox.item.enhancedLocation.getAsync` will return the locations result before attachment was added. 

## Steps to reproduce
1. Create a new appointment
2. Add a location
3. Add attachment
4. Add a location
5. Log `Office.context.mailbox.item.enhancedLocation.getAsync` to console
6. Observe that returned array do not have latest added location

## Context
We need to be able to sync Add-In with appointment locations. When subscribed to the `Office.EventType.EnhancedLocationsChanged` event the locations also returned wrong (all added/removed locations are not returned).

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding EnhancedLocation.getAsync. We are able to reproduce this issue internally. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by cdeliens** [comment]
Any updates on this issue?

**Comment by exextoc** [comment]
The issue has been fixed. Please let us know if issue persists.
