### ISSUE TITLE
displayDialogAsync in ItemSend fails when sending from pop out window

### ISSUE THREAD

**Issue by milankonir** [OfficeDev/office-js#2389]
# Provide required information needed to triage your issue

Displaying dialog through `Office.context.ui.displayDialogAsync` during `ItemSend` event triggered in OWA pop out window fails with error 12007 (dialog already opened).
This is especially problematic when the `OnSendAddinsEnabled` policy is enabled for the mailbox as then every sent item automatically pops out on send.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: macOS Monterey 12.1
* Browser (if using Office on the web): Google Chrome Version 97.0.4692.71 (Official Build) (x86_64)
 
## Expected behavior

The dialog should display and `AsyncResultStatus` of `Office.context.ui.displayDialogAsync` should be `Succeeded`.

## Current behavior

The dialog gets displayed, but the `AsyncResultStatus` of `Office.context.ui.displayDialogAsync` is `Failed` with error code 12007 (dialog already opened).

## Steps to reproduce
1. Install the linked add-in
2. Compose new email
3. Open the message in new window (pop out)
4. Send the email

## Link to live example(s)
Repro video: https://cl.outreach.io/4guZZ5Jl
Add-in that can be used to reproduce the problem: https://github.com/milankonir/onsend-dialog-addin

# Provide additional details
N/A

## Context
Sometimes we need to interact with our users during ItemSend event (confirmations, providing additional data etc.) and we need to be able to display dialogs reliable on all experiences.

## Useful logs
N/A

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by milankonir** [comment]
Looks like this was already reported in #2356

**Comment by exextoc** [comment]
As you noticed, this is already filed with #2356 . We are actively working on this issue and will provide update on original issue #2356
