### ISSUE TITLE
Use Word.run in dialog api

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/office-js#239]
I want to get word openxml from dialog api.

I try code below:
`(function () {
    Office.onReady(function () {
        //Office is ready
        $(document).ready(function () {
            //the document is ready
            $("#LoadComment").click(loadOoXml);
        });
    });

    function loadOoXml() {
        console.log("Load Comment Button is clicked");
        Word.run(function (context) {
            // Create a proxy object for the document body.
            var body = context.document.body;
            // Queue a commmand to get the OOXML contents of the body.
            var bodyOOXML = body.getOoxml();
            // Synchronize the document state by executing the queued commands
            // and return a promise to indicate task completion.
            return context.sync()
                .then(function () {
                    currentOOXML = bodyOOXML.value;
                    xmlToComments(currentOOXML);
                });
        })
            .catch(errorHandler);
    }
    function xmlToComments(ooXml) {
        $.ajax({
            type: "POST",
            url: "/api/comments/convertOOXmlToComments",
            // The key needs to match your method's input parameter (case-sensitive).
            data: JSON.stringify(ooXml),
            contentType: "application/json; charset=utf-8",
            dataType: "json",
            success: function (data) {
                $("#jsGrid").jsGrid({
                    height: "500px",
                    width: "100%",
                    filtering: true,
                    sorting: true,
                    paging: true,
                    autoload: true,
                    pageSize: 10,
                    pageButtonCount: 5,

                    data: data,
                    fields: [
                        { name: "Id", type: "number", width: 150, validate: "required" },
                        { name: "CommentedText", type: "text", width: 200 },
                        { name: "Date", type: "date", width: 100 },
                        { name: "Author", type: "text", width: 200 },
                        { name: "Text", type: "text", width: 200 },
                    ]
                });
            },
            failure: function (errMsg) {
                showNotification("result", data);
            }
        });
    }
    function errorHandler(error) {
        // $$(Always be sure to catch any accumulated errors that bubble up from the Word.run execution., $loc_script_taskpane_home_js_comment35$)$$
        console.log("Error: " + error);
        if (error instanceof OfficeExtension.Error) {
            console.log("Debug info: " + JSON.stringify(error.debugInfo));
        }
    }

})();
`
Above code is in the dialog api html file.

The dialog shows correctly, but after I run loadOoXml which called `Word.run`, it throws exception below:

> Debug info: {"code":"GeneralException","message":"An internal error has occurred."}

**Comment by Rick-Kirkham** [comment]
You can't use most of the APIs in the dialog. There are only 2 APIs that you can use. See the note about 1/4 of the way down in this article: [Use the Dialog API](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins)
