### ISSUE TITLE
Bubble Chart

### ISSUE THREAD

**Issue by jnSWPC** [OfficeDev/office-js#2391]
I have created a bubble chart following sample at https://github.com/OfficeDev/office-js-snippets/blob/main/samples/excel/10-chart/chart-bubble-chart.yaml

I would like to know how to set via api
1. Axes Scale - Value changes by 1
![image](https://user-images.githubusercontent.com/22331494/151274945-0f71d8c1-45fa-42e7-a2ea-a3efd1e4fbd3.png)

2. the bubblescale property- Control the size of the bubble 
![image](https://user-images.githubusercontent.com/22331494/151275037-fe68f56d-a386-45fe-970d-91110e3ccf6e.png)

**Comment by Sreeram-ms** [comment]
Hi @jnSWPC, Could you please post this to StackOverflow and tag it with office-js?

https://stackoverflow.com/questions/tagged/office-js

**Comment by RuizhiSunMS** [comment]
Reply at https://stackoverflow.com/questions/70879580/officejs-bubblechart-scale-bubble-size-and-set-axes-value-scale

**Comment by RuizhiSunMS** [comment]
Close the issue for long time waiting for feedback. Please re-active issue if there was any other question.
