### ISSUE TITLE
Is internetMessageId of office.js and microsoft graph api is the same?

### ISSUE THREAD

**Issue by thao33** [OfficeDev/office-js#2392]
Hi,
I'm a developer using both office.js and microsoft graph api.
I have questions, and yes, I tried to find out the answer but got nothing. 

My questions is: 
1. Is internetMessageId of office.js and microsoft graph api is the same ? 
2. And when we sending message, then it's moved from draft to sent folder,(or when message be moving between folders) internetMessageId will not change?

I've posted this Q&A to the community but seems like it didn't get any attention.
So, if you can answer immediately please help me !!

**Comment by thao33** [comment]
Sorry but still investigating?

**Comment by exextoc** [comment]
The InternetMessageId is assigned by the sending Message Transfer agent (MTA).
It is a part of the RFC spec, check out here https://en.wikipedia.org/wiki/Message-ID. 

- It is expected to be the same, you can get it from either graph call or Office.context.mailbox.item.internetMessageId
- The internetMessageId shouldn't change when you move messages from folders.

**Comment by thao33** [comment]
@exextoc Thank you for your support !
You really made my day !!
