### ISSUE TITLE
Excel custom function returns #BUSY on Excel Web when the permission is WriteDocument

### ISSUE THREAD

**Issue by ltrcx** [OfficeDev/office-js#2394]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hello, I have an excel add-in that has some custom functions (functions.html, functions.js...) and a task pane. It's not using the shared runtime. Task pane has some html inputs to get credentials from the user. These credentials are stored with OfficeRuntime.storage. Then these are accessed within the custom functions to make an API call. 

Custom function or task pane js methods doesn't read anything from the Workbook cells or uses any [read API specified here.](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins)

As suggested in the documentation I wanted to use the least permission required which is WriteDocument. **It's working as expected on desktop Mac** (Version 16.57 22011101) but doesn't work on Excel online. I tried with Safari (Version 15.3 (16612.4.9.1.7, 16612)) and Chrome (Version 97.0.4692.99 (Official Build) (x86_64)).

## Your Environment

* Platform: Office on the web
* Host : Excel
* Office version number: Office on the web
* Operating System: Mac OS
* Browser :Chrome (Version 97.0.4692.99 (Official Build) (x86_64))
 
## Expected behavior

Custom function to return the data.

## Current behavior

Custom functions get stuck in #BUSY.

## Steps to reproduce

1.  Run `yo office` and create an "Excel Custom Functions Add-in project"
2. Change the permission from "ReadWriteDocument" to "WriteDocument" in manifest.xml
3. Change your taskpane.js as follows to make sure there is no read related API is used.
```
Office.initialize = () => {
  document.getElementById("sideload-msg").style.display = "none";
  document.getElementById("app-body").style.display = "flex";
  document.getElementById("run").onclick = run;
};

export async function run() {
  console.log("Hello World!");
}

```
4. Run dev server with `npm run dev-server`
5. Upload your manifest.xml from Excel web version
6. Try to run =CONTOSO.ADD(1,2)

**Comment by rundongmsft** [comment]
Hi @Itrcx. Thanks for your reporting, bug 5760650 has been assigned for tracking this issue. Before the further fix, please use "ReadWriteDocument" permission as a workaround.
