### ISSUE TITLE
Keyboard shortcut support

### ISSUE THREAD

**Issue by sjhstone** [OfficeDev/office-js#24]
## Expected Behavior
Support for key combo press (keyboard shortcut) event trigger.

## Current Behavior
Currently, we can only trigger add-in reaction by
* adding new UI component on Ribbon / side panel;
* adding selection in the context menu (right-click triggered).

## Context
Many user scenarios call for continuous and seamless environment change.

An existing example is the equation editor. In desktop client of Word, PowerPoint and OneNote, we can create new equation field by pressing <kbd>Alt</kbd> + <kbd>=</kbd>.

## Case: code pieces in document
Take code formatting as an example. The solutions we have now are very limited. They all have unsatisfactory experiences.

### Analysis: Pasting from other text editor
We can copy HTML-formatted code from VS Code or other code editors into Word. However, it involves launching instances of other applications.

### Analysis: Existing Add-in `code format`
Or, we can use the existing `code format` add-in.  If a user wants to write directly in Word document, he is then required to edit the code in regular text environment first, where auto-indentation and auto-capitalization experience can be horribly disturbing. It also requires the user to do selection after they get the code ready.

### Ideal flow
1. Create a new field by pressing combo key, like <kbd>Alt</kbd> + <kbd>,</kbd>, or <kbd>Alt</kbd> + <kbd>Shift</kbd> + <kbd>{</kbd>,
2. A new field is created and cursor is active inside it,
3. A ribbon tab is highlighted, with options to publish the snippet as a Gist, or to the user defined endpoint,
3. When the user get his cursor outside this region, the field becomes inactive, and code highlighter is executed on the given code snippet.

## Wrapping up
From discussion with staffs here at O365 DevDays 2017 in Shanghai, there are no current public API available for such experiences. They suggest that an issue should be posted here to stress such needs. The proposed ideal flow case also requires other potential API creations. However, the general idea here is to further modularize document elements and integrate them more seamlessly, in a way that is similar to the Python Jupyter Notebook experience or Mathematica Notebook experience.

**Comment by sumurthy** [comment]
Thanks for the detailed notes. Though I'm not sure how much of key stroke events can be propagated to a web add-in. Will get back...

**Comment by sumurthy** [comment]
This is pretty low in the roadmap at this time. No ETA yet.

**Comment by 1TheMuffinMan** [comment]
That's a bummer that this is low priority. Excel for Mac for example is a pretty poor implementation compared to Windows and it would be great if developers could bridge the gap with the Javascript API.

What do you mean you're not sure how much of key stroke events can be propagated to a web add-in? You're already propagating events from a native application to a web add-in everywhere else.

**Comment by JuaneloJuanelo** [comment]
this is a feature request, please use https://officespdev.uservoice.com/

**Comment by rvanlaak** [comment]
Unfortunately under review since 2016 already. This feature would be a big step in closing the functionality gap between VBA and Office JS.

Reference: https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/6572900-add-keyboard-shortcut

https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/14060244-enable-binding-keyboard-shortcuts-to-a-button-in-o
