### ISSUE TITLE
Inserting ooxml and docx does not work anymore in Office Online

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#240]
## Expected Behavior
We want to insert ooxml or a docx as base64 into a word document.

## Current Behavior
Insertion does not work. An error occurs telling that the ooxml is malformed.

## Steps to Reproduce, or Live Example

[Script Lab - InsertBase64FromFile](https://gist.github.com/barisbikmaz/ac7a43135a10d8896867fb042a38d5d2).

[Script Lab - Insert Ooxml](https://gist.github.com/barisbikmaz/cf0fc81647ebf11995686e7262ffe843)

## Context
Our customers can't insert docx files in Online anymore.

## Your Environment
* Platform: Office Online
* Host : Word
* Operating System: Win
* Browser : Chrome, IE, Opera, Edge

## Useful logs
```
{
  "name": "RichApi.Error",
  "code": "GeneralException",
  "traceMessages": [],
  "innerError": null,
  "debugInfo": {
    "code": "GeneralException",
    "message": "ooxmlIsMalformated",
    "errorLocation": "ContentControl.insertFileFromBase64",
    "statement": "var insertFileFromBase64=insertContentControl.insertFileFromBase64(...);",
    "surroundingStatements": [
      "...",
      "var selection=root.getSelection();",
      "// Instantiate {selection}",
      "var insertContentControl=selection.insertContentControl();",
      "// Instantiate {insertContentControl}",
      "insertContentControl.appearance=...;",
      "// &gt;&gt;&gt;&gt;&gt;",
      "var insertFileFromBase64=insertContentControl.insertFileFromBase64(...);",
      "// &lt;&lt;&lt;&lt;&lt;",
      "// Instantiate {insertFileFromBase64}",
      "insertContentControl.removeWhenEdited=...;"
    ],
    "fullStatements": [
      "Please enable config.extendedErrorLogging to see full statements."
    ]
  }

```

**Comment by JuaneloJuanelo** [comment]
this is a known issue and an active escalation on the team.

**Comment by LezaMax** [comment]
@barisbikmaz do you by any chance have an approximated date when you started observing this behavior. We are investigating right now but in parallel I'm gathering more context.

**Comment by barisbikmaz** [comment]
It was told us by a customer on 6th of september. Probably in that range.

**Comment by LezaMax** [comment]
Thank you, this was indeed an issue that was resolved since last Friday.  Do let us know if you are still experiencing problems.

**Comment by barisbikmaz** [comment]
Thanks, looks ok in my first testing. Closing the issue.
