### ISSUE TITLE
No response after user click ignore button when trigger the dialog by Office.context.ui.displayDialogAsync

### ISSUE THREAD

**Issue by otisyuan789** [OfficeDev/office-js#2400]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___web___
* Host [Excel, Word, PowerPoint, etc.]: ___outlook___
* Office version number: ______
* Operating System: __windows10____
* Browser (if using Office on the web): __chrome____
 
## Expected behavior
![image](https://user-images.githubusercontent.com/60979902/151524706-5b797ac6-667f-4453-b409-3958f79c483e.png)
It should cancel this trigger dialog action after user click ignore button in the small dialog.

## Current behavior
![image](https://user-images.githubusercontent.com/60979902/151524706-5b797ac6-667f-4453-b409-3958f79c483e.png)
No response after click ignore button in dialog and we got an error in the console below
![image](https://user-images.githubusercontent.com/60979902/151525506-a3441bf4-e1e9-4dbc-8f28-300477b5689c.png)

## Steps to reproduce

1. trigger a dialog with iframe
2. then click the ignore button in that small dialog

## Link to live example(s)

# Provide additional details

## Useful logs

- [ ] Console errors
- [ ] Screenshots
![image](https://user-images.githubusercontent.com/60979902/151524706-5b797ac6-667f-4453-b409-3958f79c483e.png)

![image](https://user-images.githubusercontent.com/60979902/151526173-b86e1616-2513-467d-8b1d-9691aae897f3.png)

- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
We are not able to repro this at our end, can you please share a hosted manifest with which we can repro or a test tenant where this issue is reproable.
