### ISSUE TITLE
Office.js SourceMaps.getMapForGeneratedPath: exception. It is impossible to debug an Outlook Add-In with Visual Studio

### ISSUE THREAD

**Issue by rulopimentel** [OfficeDev/office-js#2401]
# Office Add-In development.
I am trying to debug an Outlook Add-In application, but the Office.js library throws a Source Map exception.

## Your Environment

* Visual Studio 2019
* Office version number: Office 365
* Operating System: Windows
* Browser (if using Office on the web): Microsoft Edge
 
## Expected behavior
Add-In runs in the Outlook web application.

## Current behavior
- Add-In does not show in the Outlook web application. Exceptions are logged in the Visual Studio.
* SourceMaps.getMapForGeneratedPath: exception while processing path: https://outlook.live.com/mail/0/, sourcemap: owa.mailindex.js.map
* Failed to load resource: the server responded with a status of 404 () [https://outlook-1.cdn.office.net/owamail/20220121003.04/]
SourceMaps.getMapForGeneratedPath: exception while processing path: https://amcdn.msftauth.net/me?partner=Exchange&version=10.21153.1&market=en-US&wrapperId=suiteshell, sourcemap: meInlineBackCompat.min.js.map
* Failed to load resource: the server responded with a status of 404 (Not Found) [https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints]

## Steps to reproduce

1. Using Visual Studio 2019, create a new Project.
2. Create an web Outlook Add-In 
3. Compile and execute.
4. Check the Output window in Visual Studio.

## Context
- This issue completely blocks the add-in development.

## Useful logs
SourceMaps.getMapForGeneratedPath: exception while processing path: https://outlook.live.com/mail/0/, sourcemap: owa.mailindex.js.map
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at new SourceMap (C:\ProgramData\Microsoft\VisualStudio\EdgeAdapter\a071c5c8\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMap.js:19:25)
    at C:\ProgramData\Microsoft\VisualStudio\EdgeAdapter\a071c5c8\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:58:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Failed to load resource: the server responded with a status of 404 () [https://outlook-1.cdn.office.net/owamail/20220121003.04/]
SourceMaps.getMapForGeneratedPath: exception while processing path: https://amcdn.msftauth.net/me?partner=Exchange&version=10.21153.1&market=en-US&wrapperId=suiteshell, sourcemap: meInlineBackCompat.min.js.map
SyntaxError: Unexpected token w in JSON at position 0
    at JSON.parse (<anonymous>)
    at new SourceMap (C:\ProgramData\Microsoft\VisualStudio\EdgeAdapter\a071c5c8\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMap.js:19:25)
    at C:\ProgramData\Microsoft\VisualStudio\EdgeAdapter\a071c5c8\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:58:28
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Failed to load resource: the server responded with a status of 404 (Not Found) [https://client-s.gateway.messenger.live.com/v1/users/ME/endpoints]

**Comment by exextoc** [comment]
1. Can you help us with the steps you followed to understand more around it ?
2. Did you make any changes to the files, or you were not able to start the initial debugging ? 

You can follow these docs for smooth debugging 
1. https://docs.microsoft.com/en-us/visualstudio/vsto/configuring-a-computer-to-develop-office-solutions?view=vs-2022
2. https://docs.microsoft.com/en-us/office/dev/add-ins/develop/develop-add-ins-visual-studio
3. https://docs.microsoft.com/en-us/visualstudio/vsto/walkthrough-creating-your-first-vsto-add-in-for-project?view=vs-2022

Furthermore, you can use Visual Studio Code for the same 
1. https://code.visualstudio.com/docs/other/office
2. https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator

**Comment by rulopimentel** [comment]
Hi @exextoc , These are the steps to reproduce the behavior: 

1. Using Visual Studio 2019, create a new Project. Create a new web Outlook Add-In (c#)
2. Compile and execute.
3. Wait for Outlook to be launched on the web.
4. Start the session
5. Compose a new message
3. Read the log in the Output window in Visual Studio.

**You could read the next exceptions:**
Failed to load resource: the server responded with a status of 404 (Not Found) [https://login.live.com/favicon.ico]
SourceMaps.getMapForGeneratedPath: exception while processing path: https://outlook.live.com/mail/0/, sourcemap: owa.mailindex.js.map
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at new SourceMap (C:\ProgramData\Microsoft\VisualStudio\EdgeAdapter\a071c5c8\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMap.js:19:25)
    at C:\ProgramData\Microsoft\VisualStudio\EdgeAdapter\a071c5c8\node_modules\vscode-chrome-debug-core\out\src\sourceMaps\sourceMapFactory.js:58:28
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by exextoc** [comment]
A few clarifying questions:
1. Are you developing "VSTO add-in" and not "Modern Outlook Web-Addin"?
2. Which public documentation are you following for development?

**Comment by rulopimentel** [comment]
1. Modern Outlook web Add-In
2. Using the official office Add-In guide

Please , in my previous comment I explain how to replicate the issue .

**Comment by exextoc** [comment]
Can you please share documentation link which you are referring to?

**Comment by rulopimentel** [comment]
The documentation is in https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=visualstudio

**Comment by rulopimentel** [comment]
The exceptions have disappeared. It works as expected.
