### ISSUE TITLE
Office 2016 VLSC versions still use Internet Explorer to display Add-Ins

### ISSUE THREAD

**Issue by ndreisg** [OfficeDev/office-js#2406]
# Office 2016 VLSC versions still use Internet Explorer to display Add-Ins

## Your Environment

* Platform: PC Desktop
* Host: Excel/Word
* Office version number: 16.0.5266.1000
* Operating System: Windows 10
 
## Expected behavior
Since Internet Explorer support will soon be discontinued, I would expect VLSC versions to use the new WebView 2 instead (like the C2R versions already do).

## Current behavior
VLSC versions are still using Internet Explorer to display Add-Ins

## Context
Office 2016 still has extended support until 2025 so we want our Add-In to still support Office 2016.
Supporting Internet Explorer is sometimes very tricky and many ES6 features can't be used at all or need to be polyfilled which means a lot of extra effort.
C2R versions of Office 2016 are already using the new WebView 2 instead of Internet Explorer, so it seems the required updates are already out there and just need to be published to VLSC versions as well.

**Comment by JinghuiMS** [comment]
Thanks for reaching us. This is current design, you can refer to the following document.
https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

If you need it working on WebView 2, you can submit the new requirement for new feature asking.

**Comment by jozefizso** [comment]
Office 2016 VLSC should display content using WebView 2.

**Comment by JinghuiMS** [comment]
For feature requests please go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) and see if your feature has already been requested or request a new feature there. Thanks.

**Comment by ndreisg** [comment]
Posted a feature request here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/office-2016-vlsc-should-display-add-ins-using-webview-2/idi-p/3167940

**Comment by JinghuiMS** [comment]
@ndreisg Thanks for posting new request. If you have no further issue, I will close this github issue.
