### ISSUE TITLE
Office js object table.sort.fields is empty when table's header is hidden in Excel

### ISSUE THREAD

**Issue by Stepan-Valkov** [OfficeDev/office-js#2409]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2112 Build 16.0.14729.20254
* Operating System: Windows 10
* Browser (if using Office on the web): n/a
 
## Expected behavior
table.sort.fields should be available when the header of the table is hidden. 
If user toggles the header row back on, the fields will become available again, which to me means that they are stored, but made unavailable artificially

## Current behavior
table.sort.fields is an empty collection if user hides the header of the table

## Steps to reproduce
1. create a table with some data
2. sort it and call table.sort.fields to make sure that the collection isn't empty
3. hide the header and call table.sort.fields, this time the collection is empty

## Link to live example(s)
gist link: https://gist.github.com/Stepan-Valkov/7b265365bc5431ce165ac9cee7074376

# Provide additional details
Please also note that filter buttons for the table are visible at the end of the scenario in the gist. This doesn't feel intentional since the the checkbox responsible for the filter buttons on the excel UI "Table Design" panel turns inactive when the header is hidden manually. This might be a separate issue.

**Comment by guliums** [comment]
Thank you @Stepan-Valkov for reporting this issue. The issue has been confirmed and tracked as ADO#5781997 in our backlog.
