### ISSUE TITLE
error:5001 - office.context.auth.getaccesstokenasync

### ISSUE THREAD

**Issue by SSAndersen** [OfficeDev/office-js#241]
## Expected Behavior
I'am creating an outlook add-in, and trying to create SSO access.

Get the app-token, as callback on the office.context.auth.getaccesstokenasync method

## Current Behavior
It works:
 -100% in Chrome
 -50% ish in outlook desktop
 -0% in internet explorer 11
in IE11 i get an 5001 error  internal server error.
![image](https://user-images.githubusercontent.com/24933635/45298010-752bbf80-b507-11e8-8f56-1f61521a1dd6.png)

This is where it fails:
![image](https://user-images.githubusercontent.com/24933635/45298262-47934600-b508-11e8-91cb-c71ce6017e0a.png)

I have the completed the "on behalf of" flow and i get the token in chrome, and half of the try's in desktop, but when i try to get it running in IE it's simply rejecting it.
That sad, i have to reload the entire mailbox to get it to run the code again, i seems it just skip it.

the code runs on nodejs using webpack-dev-server
and works fine in Chrome 
half the time in desktop
never in IE11

**Comment by ox4** [comment]
I'm having exactly the same issue in Chrome. However, only when I'm signed in in more than 1 account. 
![untitled](https://user-images.githubusercontent.com/11349411/45420157-1777ae80-b692-11e8-823f-0524cc6f4aa7.png)

**Comment by exextoc** [comment]
For Outlook desktop, we are not seeing significant number of error 5001. Could you confirm that you are also getting '5001' in Outlook desktop and the Outlook version you are using?

**Comment by sugarp** [comment]
Update:

Have u done anything particular to make it work for Outlook desktop? I'm trying Outlook 2016 MSO 16.0.8431 and Im getting 5001. On the other hand I managed to get it working in IE and Chrome.
Thanks for any lead.

In IE we were having troubles with SSL certificate when developing on localhost. Error code was 13005 which was misleading but once we published the app to server with valid certificate it has started working.

**Comment by sugarp** [comment]
In IE we were having troubles with SSL certificate. Once we published the app to server with valid certificate it has started working.

**Comment by exextoc** [comment]
Bug 936876<https://o365exchange.visualstudio.com/web/wi.aspx?pcguid=d1a8f71c-7f64-45ad-9c5c-19c2f469d620&id=936876>: [OfficeDev/office-js] error:5001 - office.context.auth.getaccesstokenasync (#241)


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by exextoc** [comment]
What version of Outlook are you using? Could you please provide a version number for Outlook 2016? Did the SSL certificate issue resolve your issue in Outlook 2016 as well?

**Comment by sugarp** [comment]
> What version of Outlook are you using? Could you please provide a version number for Outlook 2016? Did the SSL certificate issue resolve your issue in Outlook 2016 as well?

I updated my comment and no, desktop is still not working.

**Comment by SSAndersen** [comment]
If i recall this correct, there were an update to the SSO system (made it office insiders only in some versions), my solution were to use SSO where possible, and then switch to manuel login on errors. Altleast at the time, this were the solution i came up with.

**Comment by exextoc** [comment]
@sugarp Thanks for providing the version. Do you know if you see the same 5001 error in newer version of Outlook (for example, recent monthly channels or the newer Semi-Annual build, like 9126)?  16.0.8431 was one of the first build that had SSO in preview, but SSO preview was only enabled for monthly channel of 16.0.8431, and not for the Semi-Annual channel.

**Comment by Harshagracy** [comment]
Hi 

I am struck with the same iisue. I am trying in outlook from browser(chrome, IE). 

```
Office.context.auth.getAccessTokenAsync({forceConsent: false}, (result) =>{
    if (result.status.toString() === "succeeded") {
        // Use this token to call Web API
        var ssoToken = result.value;
       ssoToken;
    } else {
        if (result.error.code === 13003) {
            // SSO is not supported for domain user accounts, only
            // work or school (Office 365) or Microsoft Account IDs.
        } else {
            // Handle error
        }
    }
});
```

Please reopen this issue .

**Comment by Harshagracy** [comment]
And it works perfectly in the outlook desktop app.

**Comment by kbrandl** [comment]
@Harshagracy I've reopened this issue, per your request. @niteshgolchha85 are you able to assist with this one (since it's SSO-related)?

**Comment by Harshagracy** [comment]
Thanks @kbrandl . Please let me know if you require any more detail to get to the root of the issue.

**Comment by niteshgolchha85** [comment]
@Harshagracy can you send across what's the exact error that you are getting? Is this error only for getAccessTokenAsync API or for others under Office.context also?

**Comment by Harshagracy** [comment]
To getCallbackTokenAsync, I am getting this error. 
```
code: 5001
message: "Er is een interne fout opgetreden."
name: "Interne fout"
```
![image](https://user-images.githubusercontent.com/14230498/68273167-b4ae5700-008b-11ea-94ed-4497e3ea1ba9.png)

**Comment by jargil** [comment]
@Harshagracy - 5001 is an internal error, so several things could have gone wrong, one possible being you have an old Office.js version cached in your browser. Could you try clearing your browser cache and retrying?

If you still hit the same problem, please comment again adding your session id (in Word Online, go to File, then About) and please paste the information that shows under the Diagnostics section. This will help us try to diagnose if there's a problem in our end.

Thank you for taking the time to report issues with our platform!
