### ISSUE TITLE
Microsoft Graph instead of Outlook REST API (version 2.0)

### ISSUE THREAD

**Issue by sztukiecki** [OfficeDev/office-js#2410]
I saw that the Outlook REST API will be removed in November 2022 and wanted to start using Microsoft Graph instead.
But the only solution I found to get the authorization token is to show login popup to user.
This doesn't make sense to me, as the user is already authenticated in the context of his Outlook account.

There is also Office.context.mailbox.getCallbackTokenAsync(), which returns the token, but it doesn't work with Microsoft Graph.
Do you have a better solution for that?

**Comment by exextoc** [comment]
There are a few authentication options for Outlook add-ins. These options are detailed in the documentation [here](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/authentication). 

One option is to use SSO. Single sign-on access tokens provide a seamless way for your add-in to authenticate and obtain access tokens to call the [Microsoft Graph API](https://docs.microsoft.com/en-us/graph/overview). More documentation on SSO can be found [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins).
