### ISSUE TITLE
Inserting a content control with customXML binding to a document package removes custom style in last paragraph

### ISSUE THREAD

**Issue by dhoelzl** [OfficeDev/office-js#2411]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
When inserting a content control via insertOoxml wich has an xpath binding to a node in a customXML containing a complete dockument package wich defines and assignes custom styles the style of the last paragraph in this referenced package gets unexpectedly removed when Word applies the binding and the package content is inserted into the document and displayed.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac and PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Word for Mac 16,45 (21011103) / Office Professional Plus 2019 (16.0.10339.20026) 64-Bit
* Operating System: macOS and Windows
 
## Expected behavior
When executing the reproduction steps, the custom style of the last paragraph should be preserved like the style of the other paragraphs.

## Current behavior
The custom style of the last paragraph gets removed.

## Steps to reproduce

1. Open the attached word document

[LastParagraphStyleReproduction.docx](https://github.com/OfficeDev/office-js/files/7986731/LastParagraphStyleReproduction.docx).

The document itself is empty but it contains a customXML with the following attribute.

LastParagraphStyleReproduction.docx -> customXML -> item1.xml
f:fields -> f:record -> f:field ref="FSCFIELDSUT_1_1001_FieldsTestField2" -> text attribute

Especially note the style attribute of the last paragraph containing the text "line 3" which is assigned to the custom style "FSCFIELDSUT" like all other lines, e.g. "line 2".

```XML
<?xml version="1.0" standalone="yes"?>
<?mso-application progid="Word.Document"?>
<pkg:package xmlns:pkg="http://schemas.microsoft.com/office/2006/xmlPackage">
  <pkg:part pkg:name="/_rels/.rels" pkg:contentType="application/vnd.openxmlformats-package.relationships+xml">
    <pkg:xmlData>
      <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
        <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
      </Relationships>
    </pkg:xmlData>
  </pkg:part>
  <pkg:part pkg:name="/word/document.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml">
    <pkg:xmlData>
      <w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
        <w:body>
          <w:p>
            <w:pPr>
              <w:pStyle w:val="FSCFIELDSUT"/>
            </w:pPr>
            <w:r>
              <w:t xml:space="preserve">multiline text </w:t>
            </w:r>
          </w:p>
          <w:p>
            <w:pPr>
              <w:pStyle w:val="FSCFIELDSUT"/>
            </w:pPr>
          </w:p>
          <w:p>
            <w:pPr>
              <w:pStyle w:val="FSCFIELDSUT"/>
            </w:pPr>
            <w:r>
              <w:t xml:space="preserve"> line 1</w:t>
            </w:r>
          </w:p>
          <w:p>
            <w:pPr>
              <w:pStyle w:val="FSCFIELDSUT"/>
            </w:pPr>
          </w:p>
          <w:p>
            <w:pPr>
              <w:pStyle w:val="FSCFIELDSUT"/> <!-- This will be preserved correctly -->
            </w:pPr>
            <w:r>
              <w:t xml:space="preserve"> line 2</w:t>
            </w:r>
          </w:p>
          <w:p>
            <w:pPr>
              <w:pStyle w:val="FSCFIELDSUT"/>
            </w:pPr>
          </w:p>
          <w:p>
            <w:pPr>
              <w:pStyle w:val="FSCFIELDSUT"/> <!-- This gets unexpectedly removed -->
            </w:pPr>
            <w:r>
              <w:t xml:space="preserve"> line 3</w:t>
            </w:r>
          </w:p>
          <w:p/>
          <w:sectPr>
            <w:pgSz w:w="12240" w:h="15840"/>
            <w:pgMar w:top="1417" w:right="1417" w:bottom="1134" w:left="1417" w:header="720" w:footer="720" w:gutter="0"/>
            <w:cols w:space="720"/>
          </w:sectPr>
        </w:body>
      </w:document>
    </pkg:xmlData>
  </pkg:part>
  <pkg:part pkg:name="/word/_rels/document.xml.rels" pkg:contentType="application/vnd.openxmlformats-package.relationships+xml">
    <pkg:xmlData>
      <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
        <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
      </Relationships>
    </pkg:xmlData>
  </pkg:part>
  <pkg:part pkg:name="/word/styles.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml">
    <pkg:xmlData>
      <w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
        <w:style w:type="paragraph" w:default="1" w:styleId="Normal">
          <w:name w:val="Normal"/>
          <w:qFormat/>
        </w:style>
        <w:style w:type="character" w:default="1" w:styleId="DefaultParagraphFont">
          <w:name w:val="Default Paragraph Font"/>
          <w:uiPriority w:val="1"/>
          <w:semiHidden/>
          <w:unhideWhenUsed/>
        </w:style>
        <w:style w:type="character" w:styleId="PlaceholderText">
          <w:name w:val="Placeholder Text"/>
          <w:basedOn w:val="DefaultParagraphFont"/>
          <w:uiPriority w:val="99"/>
          <w:semiHidden/>
        </w:style>
        <w:style w:type="character" w:customStyle="1" w:styleId="BalloonTextChar">
          <w:name w:val="Balloon Text Char"/>
          <w:basedOn w:val="DefaultParagraphFont"/>
          <w:link w:val="BalloonText"/>
          <w:uiPriority w:val="99"/>
          <w:semiHidden/>
        </w:style>
        <w:style w:type="character" w:customStyle="1" w:styleId="HeaderChar">
          <w:name w:val="Header Char"/>
          <w:basedOn w:val="DefaultParagraphFont"/>
          <w:link w:val="Header"/>
          <w:uiPriority w:val="99"/>
        </w:style>
        <w:style w:type="character" w:customStyle="1" w:styleId="FooterChar">
          <w:name w:val="Footer Char"/>
          <w:basedOn w:val="DefaultParagraphFont"/>
          <w:link w:val="Footer"/>
          <w:uiPriority w:val="99"/>
        </w:style>
        <w:style w:type="paragraph" w:styleId="BalloonText">
          <w:name w:val="Balloon Text"/>
          <w:basedOn w:val="Normal"/>
          <w:link w:val="BalloonTextChar"/>
          <w:uiPriority w:val="99"/>
          <w:semiHidden/>
          <w:unhideWhenUsed/>
        </w:style>
        <w:style w:type="paragraph" w:styleId="Header">
          <w:name w:val="header"/>
          <w:basedOn w:val="Normal"/>
          <w:link w:val="HeaderChar"/>
          <w:uiPriority w:val="99"/>
          <w:unhideWhenUsed/>
        </w:style>
        <w:style w:type="paragraph" w:styleId="Footer">
          <w:name w:val="footer"/>
          <w:basedOn w:val="Normal"/>
          <w:link w:val="FooterChar"/>
          <w:uiPriority w:val="99"/>
          <w:unhideWhenUsed/>
        </w:style>
        <w:style w:type="paragraph" w:customStyle="1" w:styleId="FSCFIELDSUT">
          <w:name w:val="FSCFIELDSUT"/>
          <w:basedOn w:val="Normal"/>
          <w:uiPriority w:val="99"/>
          <w:qFormat/>
        </w:style>
      </w:styles>
    </pkg:xmlData>
  </pkg:part>
</pkg:package>
```

2. In the JavaScript console of an OfficeJS-AddIn execute the following (In my test executed in Office for the Mac, please adjust syntax if used JavaScript version does not support all used language features). This will insert a custom control which is bound to the previous mentioned custom XML node.

```JavaScript
        await Word.run(async (context) => {
          const ooXML = `<?xml version='1.0' standalone='yes'?>
          <?mso-application progid='Word.Document'?>
          <pkg:package xmlns:pkg='http://schemas.microsoft.com/office/2006/xmlPackage'>
            <pkg:part pkg:name='/_rels/.rels' pkg:contentType='application/vnd.openxmlformats-package.relationships+xml' pkg:padding='512'>
              <pkg:xmlData>
                <Relationships xmlns='http://schemas.openxmlformats.org/package/2006/relationships'>
                  <Relationship Id='rId1' Type='http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument' Target='word/document.xml'/>
                </Relationships>
              </pkg:xmlData>
            </pkg:part>
            <pkg:part pkg:name='/word/document.xml' pkg:contentType='application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml'>
              <pkg:xmlData>
                <w:document xmlns:w='http://schemas.openxmlformats.org/wordprocessingml/2006/main'
                  xmlns:w14='http://schemas.microsoft.com/office/word/2010/wordml'
                  xmlns:w15='http://schemas.microsoft.com/office/word/2012/wordml'>
                  <w:body>
                    <w:p>
                      <w:sdt>
                        <w:sdtPr>
                          <w:alias w:val='Test Feld 2'/>
                          <w:tag w:val='FSCFIELDSUT_1_1001_FieldsTestField2'/>
                          <w:placeholder><w:docPart/></w:placeholder>
                          <w15:dataBinding
          w:prefixMappings="xmlns:f='http://schemas.fabasoft.com/folio/2007/fields'"
          w:xpath="/*[name()='f:fields']/*[name()='f:record']/*[name()='f:field' and @ref='FSCFIELDSUT_1_1001_FieldsTestField2']/@text"
          w:storeItemID="{4E8A9591-F074-446B-902F-511FF79C122F}"/>
                        </w:sdtPr>
                        <w:sdtContent></w:sdtContent>
                      </w:sdt>
                    </w:p>
                  </w:body>
                </w:document>
              </pkg:xmlData>
            </pkg:part>
          </pkg:package>`;
          context.document.getSelection().insertOoxml(ooXML, Word.InsertLocation.replace);
          await context.sync();
        });

```
3. After insertion, select the next to last line ("line 2") and check the assigned style, which should be "FSCFIELDSUT":

<img width="495" alt="NextToLast_Style_OK" src="https://user-images.githubusercontent.com/25737508/152160756-784e654f-d25b-4293-a485-34cbb4bccb36.PNG">

4. Select the last line ("line 3") and check the assigned style. It should also be "FSCFIELDSUT" like defined in the custom XML node, but the style is **unexpectedly not assigned** (it's assigned to the "Normal" style):

<img width="496" alt="Last_Style_NOK" src="https://user-images.githubusercontent.com/25737508/152161069-17922a02-f7f5-4ad8-8996-6f20c27dde8a.PNG">

5. Modify the text of an arbitrary line in the inserted custom control and save the document. This will update the text attribute in the custom XML, however the custom style in the last paragraph is now also missing in the package XML (record entry in item1.xml) which Word will generate from the modification.

**Comment by yihuax-msft** [comment]
@dhoelzl @RuizhiSunMS, This is a known issue. You are inserting three paragraphs into an empty document. But, the empty document in fact contains one paragraph. You can see this empty paragraph by clicking the Home tab in the ribbon, and then clicking the button with a mark like a paragraph end. Now you can see the empty document has an EOP (end of paragraph) mark, and this paragraph has its own style.

Now, when you insert three paragraphs, the first two paragraphs are inserted as independent paragraphs, and that is why the first two paragraphs have the "correct" style.  The third paragraph is in fact merged with the empty document's existing empty paragraph, and the new paragraph will use the empty paragraph's original style. (If we don't allow this merge, we won't be able to insert some short text into an existing paragraph using insertOoxml API.)

Thus, clearly, the workaround will be to insert four paragraphs: The first three is what you wanted to insert and the last one is an extra empty paragraph.  If necessary, after the insertOoxml is finished, you can delete the empty paragraph after the third paragraph. 

Let me know whether it works. Thanks.

**Comment by RuizhiSunMS** [comment]
Hello Yihua,

Thank you for your effort and workaround.

Yours sincerely,
Ruizhi
________________________________

**Comment by dhoelzl** [comment]
Hello!

Thank you for looking at this.

Our purpose is to use the data binding without further modifying the content of the content control or the bound document.

Deleting the last paragraph programmatically after the insertion would partially solve it, but once the source document in the custom XML changes (we update the content of the custom XML prior to the document being opened) the extra inserted paragraph will show up again and would require to scan the complete document and update all fields to remove the inserted paragraph there, so there would not be any benefit of using the automatic updating mechanism of the data binding. Additionally I could not find any API to enumerate all custom controls directly, only Word.Paragraph.parentContentControlOrNullObject.

Alternatively setting the content text style of the added last dummy paragraph to a 1pt size in the custom XML instead of deleting it afterwards does not help, as this will always display an extra line. Setting that paragraph itself hidden also will not work as the style of the last paragraph is always ignored.
This is how it looks when using an additional 1pt sized text in the last paragraph with a single dot as character:

![2022-03-02  Package Binding](https://user-images.githubusercontent.com/25737508/156337370-faa67124-f6a2-4ec4-ae3b-0ecd1cd63d56.png)

Regards,
Dominik Hölzl

**Comment by yihuax-msft** [comment]
Thank you for your information. Let me see whether we can improve the API by adding an optional parameter. I will let you know.

**Comment by yihuax-msft** [comment]
@grangeryy Phoebe, This is the issue I mentioned a moment ago. It occurs with the last paragraph when inserting html/ooxml.

**Comment by yihuax-msft** [comment]
@dhoelzl, What do you mean by "enumerate all custom controls"? Do you mean to enumerate all content controls? You can do so by getting context.document.body.contentControls. Thanks.

**Comment by dhoelzl** [comment]
Thank you for that information! But as mentioned, removing all additional paragraphs programmatically won't work in our case. This is also because there is currently no way in Microsoft Word / OfficeJS to get called when a document gets opened.
As mentioned here: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/shared-runtime-requirement-sets and here https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/shared-runtime-requirement-sets the shared JavaScript runtime isn't released yet.

What I also have to mention is that this problem does not only occur with OfficeJS but also when using classic COM-AddIns and the native Word application on Windows. There we could run code when a document is opened, but as mentioned we would loose the benefits of the data binding when we would require to patch the document each time it is opened.


> @dhoelzl, What do you mean by "enumerate all custom controls"? Do you mean to enumerate all content controls? You can do so by getting context.document.body.contentControls. Thanks.

**Comment by yihuax-msft** [comment]
We don't have the way to meet your need by changing our API with a new optional parameter. I have proposed to our team and they will consider it. I am not sure what our team will do, though.... 

At this moment, the workaround is still inserting an extra line at the end. Thanks.

**Comment by grangeryy** [comment]
@dhoelzl does the work around mentioned above solve the issue for you?

**Comment by dhoelzl** [comment]
Hello!

Thank you for the reply.

The workaround is not a real solution for our problem, because we do not want the extra paragraph in the content control, as this changes the way the document will look. If multiple content controls are among each other, there will always be a gap between them.

Regards,
Dominik

**Comment by vikramatcoupa** [comment]
[ooxml_formatting_issue.xml.zip](https://github.com/OfficeDev/office-js/files/10402294/ooxml_formatting_issue.xml.zip)

![image](https://user-images.githubusercontent.com/75301978/212087780-4a6231b3-06fb-4e0e-9ee4-894c98b1d5c5.png)

We do have the same problem as mentioned here. With the attached ooxml inserted into the document, we see the last paragraph's style removed.  Can we expect a fix for this issue, as the work around is really not a work around that we can share with our customers. 

Thanks,
Vikram
