### ISSUE TITLE
OfficeRuntime.Storage: Where is the data actually stored on Excel Desktop & Web?

### ISSUE THREAD

**Issue by ltrcx** [OfficeDev/office-js#2412]
Hello, I have an excel add-in that has some custom functions (functions.html, functions.js...) and a task pane. It's not using the shared runtime. Task pane has some html inputs to get credentials from the user. These credentials are stored with OfficeRuntime.storage. Then these are accessed within the custom functions to make an API call.

The data is shared with the OfficeRuntime.storage between task pane and the custom functions.

I read the [documentation](https://docs.microsoft.com/en-us/javascript/api/office-runtime/officeruntime.storage?view=common-js-preview) but there is not much detail about where the data is stored. I've investigated the web version and I see that the data created with OfficeRuntime.storage is actually stored in local storage. I wonder where exactly the data is stored on Excel Desktop.

Is it saved in user's computer where the Excel is running? Is is possible to access these credentials from another add-in running on the same computer? I want to make sure that the data I stored with OfficeRuntime.storage is isolated from other users and other add-ins.

Note: I initially asked my question in [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/713062/officeruntimestorage-where-is-the-data-actually-st.html) but haven't got an answer for a week.

**Comment by JHJ-MS** [comment]
Yes. For add-in on Excel online, the data created with OfficeRuntime.storage is stored in local storage.
For add-in on Excel Desktop, each add-in has an independent sandbox that guaranteed the runtime(and the data) of one add-in is isolated from other add-ins. The data stored with OfficeRuntime.storage is stored in the corresponding local storage.

Here is another [documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-runtime#store-and-access-data) about OfficeRuntime.storage for reference.

**Comment by ltrcx** [comment]
@JHJ-MS Thanks a lot for the details.

The documentation page you shared also mentions:
>Unless you have a specific reason to use a UI-less function, we recommend using custom functions with a [shared runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime).

I didn't use the shared runtime because all I need is to share API credentials between taskpane and custom function. And I can do that with OfficeRuntime.storage without using **shared runtime**. I wonder why the shared runtime is suggested everywhere while there is a solution like OfficeRuntime.storage? Do you see any downside in my implementation?

**Comment by JHJ-MS** [comment]
Hi @ltrcx,
Actually, on Excel desktop, a non-SharedRuntime CF add-in will run code for custom functions and the task pane in separate JavaScript runtime. The purpose of SharedRuntime is to configure an add-in to share code in the same JavaScript runtime. This enables better coordination across your add-in and access to the task pane DOM and CORS from all parts of your add-in. Compare to OfficeRuntime.storage, using SharedRuntime enables custom functions and task pane share state more directly.

[Here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime#about-the-shared-javascript-runtime) is a short introduction and suggested scenarios of SharedRuntime.

In my opinion, if OfficeRuntime.storage has no limitation of your scenario, it is definitely ok using it as your solution.

In addition, there are details on how to config a CF add-in to use SharedRuntime [here.](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial#create-the-add-in-project)

**Comment by ltrcx** [comment]
@JHJ-MS Thank you so much for the help.

**Comment by swaroopa-rani** [comment]
Hi @JHJ-MS, Our end goal is to share data from custom functions to the dialog box with custom functions runtime in windows excel desktop. The approach we were taking for this was OfficeRuntime.storage, which works in Excel live but not in Excel desktop. We're not sure whether OfficeRuntime.storage data is being passed to the dialogue box or not. Is it possible to pass OfficeRuntime.storage from custom functions to a dialogue box in Windows Excel Desktop?

The way we were setting the OfficeRuntime.storage is in the below image.
![image](https://user-images.githubusercontent.com/58599662/165308421-16bf7d01-559a-4eaf-8d82-1cb9d0066c57.png)

The way we were getting/reading the OfficeRuntime.storage is in the below image.
![image](https://user-images.githubusercontent.com/58599662/165308834-2844754d-e62f-42f1-8765-1447ea5a1835.png)

Thanks in advance!
