### ISSUE TITLE
word: range.search on empty string crashes

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/office-js#2413]
Not if if this is intended but search with an empty string e.g. 
``` ts
async function run() {
  await Word.run(async (context) => {
    const found = context.document.body.getRange()
    found.load('text')
    await context.sync();
    found.search('')
  });
}

```

yields : 

[ERROR]: Error:
{
    "stack": "RichApi.Error: The argument you provided is not valid. Check the OfficeExtension.Error.debugInfo for more information.\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:26:307868)\n    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:26:371612)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:26:369717",
    "message": "The argument you provided is not valid. Check the OfficeExtension.Error.debugInfo for more information.",
    "name": "RichApi.Error",
    "code": "InvalidArgument",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "InvalidArgument",
        "message": "The argument you provided is not valid. Check the OfficeExtension.Error.debugInfo for more information.",
        "errorLocation": "Range._search2",
        "statement": "var _Search2 = v._Search2(...);",
        "surroundingStatements": [
            "var v = context.root._getObjectByReferenceId(\"{cc2a16df-b4e7-4903-8aba-0744368be722}{223}\");",
            "// >>>>>",
            "var _Search2 = v._Search2(...);",
            "// <<<<<",
            "// Instantiate {_Search2}"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 400
}

**Comment by xiruatms** [comment]
@JensMadsen , thanks for reporting this.

I confirm this is an expected result as the error message shows:
..
"code": "InvalidArgument",
"message": "The argument you provided is not valid. Check the OfficeExtension.Error.debugInfo for more information.",
...

Empty string is not accepted as a string to be searched.
