### ISSUE TITLE
call Office.onReady in a dialog page raise exception

### ISSUE THREAD

**Issue by oldoldman** [OfficeDev/office-js#2414]
I have an excel dialog page (```dialog.html```) which is opened from an add in command function and I follow this [doc](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#handle-dialogparentmessagereceived-in-the-dialog-box) to set up to enable the dialog to receive message from parent , in ```dialog.html```
```javascript
// send message to parent
setTimeout(()=>{
  Office.context.ui.messageParent('hello from dialog')
}, 1000);
// setup up to receive message from parent
Office.onReady(()=>{
  Office.context.ui.addHandlerAsync(Office.EventType.DialogParentMessageReceived,args=>{
    console.log('message from host '+args.message)
  })
}) 
```
in command function
```javascript
function showdialog(event) {
  Office.context.ui.displayDialogAsync(
    'https://localhost/dialog.html',
    {height:50,width:60},
    result=>{
      let dialog = result.value
      dialog.addEventHandler(Office.EventType.DialogMessageReceived,args=>{
        // console.log('message from dialog '+args.message)
        dialog.messageChild('hello from parent')
        setTimeout(()=>{
          dialog.close()
        }, 100000);
      })      
    })
  event.completed()
}
```
the bi-direction communication works fine. 

The imperfect is that in the console output of ```dialog.html``` I found the following exception
```
Uncaught (in promise) 
OSF.DDA.Error
code: 7000
message: "You don't have sufficient permissions for this action."
name: "Permission Denied"
[[Prototype]]: Object
```
I've tried a do nothing callback but in vain 
```javascript
Office.onReady(()=>{})
```
 the exception disappears only when comment the ```Office.onReady``` completely. So my question is can I call ```Office.onReady``` in a dialog page?

**Comment by pkkj** [comment]
Hi,

This is a known issue. However, this exception is just a false alarm and it has no impact to later API call. This issue is expected to be fixed in the next release of Office.js.

Thanks.
Kejing

**Comment by oldoldman** [comment]
ok. thanks
