### ISSUE TITLE
enhancedLocation.removeAsync will return error 2006 when the room emailAddress's top level domain are more than 6 character in Windows Outlook

### ISSUE THREAD

**Issue by NgaiKaKit** [OfficeDev/office-js#2417]
# Provide required information needed to triage your issue
enhancedLocation.removeAsync will return error 2006 when the room emailAddress's top level domain are more than 6 character in Windows Outlook.

## Your Environment

* Platform: PC desktop
* Host: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2201 Build 16.0.14827.20158) 64-bit 
* Operating System: Windows 11
 
## Expected behavior
```
officeItem.enhancedLocation.removeAsync(
          [{ id: 'room1@test.abcdefgh', type: 'room' }],
          (result) => console.log(result)
        );
```
result should be `{value: undefined, status: 'succeeded'}`
## Current behavior

result was:
```
error: OSF.DDA.Error
code: 2006
message: "The format of the specified data object is invalid."
name: "Invalid Format Error"
```

But if we change the domain to 6 character
```
officeItem.enhancedLocation.removeAsync(
          [{ id: 'room1@test.abcdef', type: 'room' }],
          (result) => console.log(result)
        );
```
result will be `{value: undefined, status: 'succeeded'}`

# Provide additional details
- This is not related to the room existing or not, just are dummy domain name (e.g. xxx.xxxxxxxx) will trigger the error.
- Same error not occur in Browser version, which can success remove the room
- Didn't try mac yet.

## Context
Our customer are using special domain which end by xxx.software , which cannot call the removeAsync() function

**Comment by samantharamon** [comment]
Thank you for reporting this, @NgaiKaKit.

@exextoc, could you please assist with this? Thanks!

**Comment by NgaiKaKit** [comment]
Just found a related issue, for addAsync function
```
officeItem.enhancedLocation.addAsync(
          [{ id: 'room1@test.abcdefgh', type: 'room' }]
        );
```
Will not return error message, but the room cannot add to outlook when top level domain more than 6 characters

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding enhancedLocation and the limited characters in the top level domain. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 5793526

**Comment by NgaiKaKit** [comment]
Thank you for your information.
May I know that is my assumption are correct, which the problem are cause by top level domain more than 6 characters,
So I can avoid this scenario when implement the outlook add-in

**Comment by exextoc** [comment]
Can confirm this was casued by top level domains containing more than 6 characters. This has been fixed in builds later than: 
16.0.15112.10000. (this will not be the exact number of the monthly builds, but any monthly build after it will have the fix)
