### ISSUE TITLE
A pane add-in closes without user action

### ISSUE THREAD

**Issue by andreismolingmail** [OfficeDev/office-js#2418]
# Provide required information needed to triage your issue
Download the sample add-in project here: [http://s3.amazonaws.com/temp.add-in-express.com/support/as/test-excel-app.zip](http://s3.amazonaws.com/temp.add-in-express.com/support/as/test-excel-app.zip). 

Install the certificate; see the ssl folder.
Start node app.js to run the application on https://localhost:4200. 
Start  Excel Online and load the add-in's manifest.
This miniature add-in shows a task pane. 

Click the button on the pane. This updates the value of the selected cell: the book, sheet, cell and value are irrelevant. 
Switch to another tab in your browser or to another window in your Windows and wait; in my case, I minimized the browser. To gather information for this report, I waited 30 minutes; our testers believe one would need to wait 20-60 minutes. 

The time's gone; switch back to the tab/browser to find the pane disappearing. There are reports that the pane may be visible for 1-2 seconds after you switch to the browser and you may even have time to click it but it ignores the clicks. Anyway, the pane simply disappears after you switch to the browser. Once I saw an unhappy face icon displayed instead of the pane contents. Don't know how to reproduce this one. 

## Environment

* Platform: Office on the web
* Host: Excel
* Operating System: Windows 10 Pro 21H2 19044.1466; our testers may have other Windows builds
* Browser: Firefox auto-updated; say, now I have 96.0.3 (64-bit), Microsoft Edge Version 98.0.1108.43 (Official build) (64-bit), other browsers may have been used.
 
## Expected behavior
The pane shouldn't close unless the user closes it.

## Current behavior
In Excel Online, if the pane is inactive for some time, it gets closed without the user's consent.

Thank you.

**Comment by samantharamon** [comment]
Thank you for reporting this and providing the steps you took, @andreismolingmail.

 @dingjin-ms, could you please assist with this? Thanks!

**Comment by gingerjia** [comment]
@andreismolingmail, this is due to the session has been inactive for long time and need to silent load when you back to the session. During silent loading happens, the taskpane will be closed automatically. 
If you think it's a blocker for your side, please help to visit https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform to request a new feature and our PM will priority the work. Thanks!

**Comment by andreismolingmail** [comment]
Thank you!

**Comment by RuizhiSunMS** [comment]
Close this issue for having answered the question. Please contact us if there were any other questions.
