### ISSUE TITLE
Outlook 2016 - makeEwsRequestAsync - AccessDenied -> callbackToken missing ParentItemId

### ISSUE THREAD

**Issue by rstoye** [OfficeDev/office-js#2419]
We have developed an Outlook Add-In with backwards compatibility for Outlook 2016 and 2019 as well as Exchange 2016 and 2019. For accessing attachment information of the mail item via soap request we use `makeEwsRequestAsync`. This works fine on any legacy platform (OWA with any browser and Outlook 2019 for both Exchange 2016 and 2019) except with Outlook 2016. We have two different testing environments with different Versions for Outlook.

### environment 1
* this is the test Exchange 2016 Server where we're also having Office 2016 installed
* Platform [PC desktop, Mac, iOS, Office on the web]: **Hyper-V virtual machine**
* Host [Excel, Word, PowerPoint, etc.]: **Office Professional Plus 2016 - Outlook**
* Office version number: **16.0.4266.1001 64-Bit**
* Operating System: **Windows Server 2016 Standard Evaluation**

### environment 2
* Platform [PC desktop, Mac, iOS, Office on the web]: **PC desktop**
* Host [Excel, Word, PowerPoint, etc.]: **Office Professional Plus 2016 - Outlook**
* Office version number: **16.0.5266.1000 64-Bit**
* Outlook version number: **16.0.5197.1000**
* Operating System: **Windows 10 Pro**
 
## Expected behavior
Considering how the ews request works on every other client, we expected for the request to also work in Outlook 2016 and return a list of attachments for the current mail item.

## Current behavior
When calling `makeEwsRequestAsync` with this soap request
```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">
    <soap:Header>
        <t:RequestServerVersion Version="Exchange2013" />
    </soap:Header>
    <soap:Body>
        <m:GetItem>
            <m:ItemShape>
                <t:BaseShape>IdOnly</t:BaseShape>
                <t:AdditionalProperties>
                    <t:FieldURI FieldURI="item:Attachments" />
                </t:AdditionalProperties>
            </m:ItemShape>
            <m:ItemIds>
                <t:ItemId Id="${itemId}" />
            </m:ItemIds>
        </m:GetItem>
    </soap:Body>
</soap:Envelope>
```

we get the following response

```xml


<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Header>
      <h:ServerVersionInfo 
          xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" 
          xmlns="http://schemas.microsoft.com/exchange/services/2006/types" 
          xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
          MajorVersion="15" 
          MinorVersion="1" 
          MajorBuildNumber="2242" 
          MinorBuildNumber="4" 
          Version="V2017_07_11" />
   </s:Header>
   <s:Body xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <m:GetItemResponse 
          xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" 
          xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
         <m:ResponseMessages>
            <m:GetItemResponseMessage ResponseClass="Error">
               <m:MessageText>Der Zugriff wird verweigert. Überprüfen Sie die Anmeldeinformationen, und versuchen Sie es dann erneut., Fehler beim Abrufen der korrekten Eigenschaften.</m:MessageText>
               <m:ResponseCode>ErrorAccessDenied</m:ResponseCode>
               <m:DescriptiveLinkKey>0</m:DescriptiveLinkKey>
               <m:Items />
            </m:GetItemResponseMessage>
         </m:ResponseMessages>
      </m:GetItemResponse>
   </s:Body>
</s:Envelope>
```
Since it seemed to be an authentication error we used `getCallbackTokenAsync` to print out the jwt authentication token. We copied the token for Outlook 2016 and OWA and then used jwt.io to compare the payload for both. Here are the results:

**OWA**

```json
{
  "nameid": "1956cdc3-5405-4286-829c-def09efdd4c4@test-exchange.local",
  "ver": "Exchange.Callback.V1",
  "appctxsender": "https://localhost:3000/taskpane.html@test-exchange.local",
  "appctx": "{\"smtp\":\"testuser@test-exchange.local\",\"scope\":\"ParentItemId:AAMkADRkOTFiODNiLWUyNTAtNGM0MC0...\"}",
  "iss": "00000002-0000-0ff1-ce00-000000000000@test-exchange.local",
  "aud": "00000002-0000-0ff1-ce00-000000000000/testdc01.test-exchange.local@test-exchange.local",
  "exp": 1644249532,
  "nbf": 1644249232
}
```

**Outlook 2016**
```json
{
  "nameid": "1956cdc3-5405-4286-829c-def09efdd4c4@test-exchange.local",
  "ver": "Exchange.Callback.V1",
  "appctxsender": "https://localhost:3000/taskpane.html@test-exchange.local",
  "appctx": "{\"smtp\":\"testuser@test-exchange.local\",\"scope\":\"ParentItemId:\"}",
  "iss": "00000002-0000-0ff1-ce00-000000000000@test-exchange.local",
  "aud": "00000002-0000-0ff1-ce00-000000000000/testdc01.test-exchange.local@test-exchange.local",
  "exp": 1644249347,
  "nbf": 1644249047
}
```
Assuming that office.js uses the same token with `makeEwsRequestAsync` it's clear why we don't have access, considering how the token is missing the `ParentItemId` in its payload.

# Provide additional details
1. the permissions for the add-in are set to `ReadWriteMailbox` in the manifest
2. the add-in runs in `MailCompose` mode
3. before calling `makeEwsRequestAsync` we're also calling `Office.context.mailbox.item.saveAsync` and await the result
4. switching between cached and non cached exchange mode and restarting Outlook 2016 doesn't fix the problem

## Context
We are simply trying to get the attachment information for the current mail item. Since `getAttachmentsAsync` requires Mailbox API 1.8 which neither Outlook 2016 nor 2019 support, we're forced to call EWS directly to get the information.

I created this as a bug report, because we think that this is not expected behavior.

**Comment by samantharamon** [comment]
Thank you for reporting this and for providing detailed information, @rstoye.

@exextoc, could you please assist with this?

**Comment by exextoc** [comment]
Based on the 2 environments you provided is one of the environments failing and one succeeding? Or are both of them failing? We use different tokens for getCallbackTokenAsync and makeEwsRequestAsync so the difference in tokens would not be the cause of the issue. If possible can you take a fiddler trace of the makeEwsRequest to see if the request is going through properly?

**Comment by rstoye** [comment]
Both environments are failing.

I also just tested the add-in with 3 different windows-accounts that are logged in on our test server. All 3 accounts have outlook set up with the same exchange account, which is "testuser". All 3 accounts get different errors when making the EWS request.

Administrator -> `ErrorAccessDenied`

rstoye -> `ErrorConnectionFailed` ->  roughly translated error message:
> Could not establish a connection. The mailbox /o=test-exchange/ out=Exchange Administrative Group/FYDIBOHF23SPDLT /cn=Recipients/cn=2fb3f7d527b0449da023b34f47b1fb53-testuser couldn't be opened

testuser -> `ErrorItemNotFound`

I'm not a seasoned Fiddler user, so from my laymans perspective it seems like the requests go through successfully. Any specific information you were looking for?

**Comment by exextoc** [comment]
In general this is how it works. 
makeEwsRequestAsync will use EWS to contact the Exchange Server for a Token. Then use that Token and your XML payload and make another EWS call to Exchange, then give you back the results. 

(i.e. the Outlook Client is kind of acting as a passthrough for your call). This hasn't changed too much between client versions of Outlook, (but there have been bugs fixed so make sure you are on the latest version of whatever build of Outlook you are on (2016, 2019, C2R/365, etc.) 

If there are errors, it is most likely something configured incorrectly on the server, or something wrong in the XML request that is being sent. (i.e. those are other variables that could cause the error). It is possible there is a client side bug in outlook.exe, but there are currently no known issues. (Outlook 2016 is currently out of support to backfix bugs as well)

Using Fiddler you could look at the **Request**, (you may need to decrypt https traffic). and compare working requests from say Outlook 2019 vs 2016 against the **SAME** Exchange Server. and see what the difference is to help track down the error. Also to make sure the XML payload is exactly the same or not. 

I think possible errors here are: 
* The XML request is being created differently for some reason
* The Exchange Server is not returning the Token that it needs to make the EWS call (this token is cached so it is only requested the first time you call MakeEWSREquestAsync) 
* The Exchange Server has an error when processing your XML. 
* The Request is going to the wrong endpoint 
 
Hopefully Fiddler can help figure out where the error is. 

As to your specific errors, ErrorItemNotFound, can happen if the itemId got mangled for some reason. Or more likely the Item got moved or deleted. (Moving the Item changes it's EWSId) 

(to be clear I don't think there is anything wrong with your soap request, but looking at the request in fiddler,  can make sure there's not some weird bug where the XML request got changed between your JS calls and when the call was made.)

**Comment by xeras** [comment]
Hi @exextoc,

I'm a colleague of @rstoye and just wanted to avoid some confusion and clarify the behavior.

When we test the SOAP request in OWA (provided by the same Exchange Server 2016) it works perfectly.

We could reproduce this behavior by sending the SOAP request with postman:
- if we use the token, that we received from `getCallbackTokenAsync()` while using the add-in with OWA, the request succeeds
- if we use the token, that we received from `getCallbackTokenAsync()` while using the add-in with the desktop client 2016, the request fails.

Both tokens are already provided by @rstoye in the issue description. 

This leads me to the conclusion that the request it self is not the problem. I guess that the desktop client don't send the item id to the exchange server, so that the exchange server could use the item id in the jwt claims, but this is only speculation.

**Comment by exextoc** [comment]
To help us understand what is going on, a Fiddler trace will reveal the network requests and responses, so if it is not too much to ask, please grab a trace and send it to us. For security reasons, please create a private repo and at-mention "exextoc" so that we can privately access it instead of making it public. Here's a link to Fiddler's website that has all you need to help you install and capture a network trace: https://docs.telerik.com/fiddler/configure-fiddler/tasks/configurefiddler

**Comment by rstoye** [comment]
I created a trace file and uploaded it to a private repository. @exextoc you should have an invite to the repository.

**Comment by exextoc** [comment]
It looks like the fiddler trace is from an RTM build which is not supported (unless you have extended support). Can you please provide a fiddler trace from a more recent build like env 2?

**Comment by rstoye** [comment]
> It looks like the fiddler trace is from an RTM build which is not supported (unless you have extended support).

Sorry for the late response, are you talking about the Outlook client or the Exchange Server?

**Comment by exextoc** [comment]
The Outlook client

Could you collect a fiddler trace from the "Environment 2" that you specified in your initial post?
