### ISSUE TITLE
.doc file does not disable ribbon buttons

### ISSUE THREAD

**Issue by leoseccia** [OfficeDev/office-js#242]
## Expected Behavior
Addin ribbon buttons should not be enabled because of the legacy document format (.doc)

## Current Behavior
Addin ribbon buttons are enabled. officejs api does not allow interaction with the document

## Steps to Reproduce
  1. Install Script Lab on Word Desktop
  2. (Unzip and) Open the document attached to this Issue 
  3. Select the Script Lab Tab, click on Run and try to run a script which interact with the document content (eg. Basic API call)

## Context
This is a big issue because our testers and clients are reporting that our app is not working when trying to scan legacy documents. [As far as we know, by design - the ribbon buttons should be disabled for these legacy formats. ](https://stackoverflow.com/questions/39253494/officejs-read-old-doc-file/39255670#comment91150451_39255670)

## Your Environment

* Platform: PC Desktop
* Host: Word Office 365
* Office version number
![image](https://user-images.githubusercontent.com/2159624/45434482-76dfb980-b6a6-11e8-9b28-013ca4b416d0.png)
* Operating System: Win 7 Ent.

## File
[test2.zip](https://github.com/OfficeDev/office-js/files/2375796/test2.zip)

**Comment by lliu113** [comment]
@leoseccia hey Leonardo, so sorry for the late response. I tried your repro steps but it looks like the buttons are disabled for me (see attached screenshot). 

![github button disabled](https://user-images.githubusercontent.com/6591834/72031914-c60a1000-3242-11ea-9d14-e17ba387a6bc.JPG)

Are you still seeing this issue? 

Thanks!

**Comment by leoseccia** [comment]
Hello @lliu113, I haven't got the original test environment anymore.
I tried again on my actual machine (W10 / O365 v16) and I cannot longer replicate... 
I am going to close the issue. Thanks for getting back to me.
