### ISSUE TITLE
Edit recipient on OWA does not trigger a "RecipientsChanged" event handeler

### ISSUE THREAD

**Issue by teejay001** [OfficeDev/office-js#2422]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome
 
## Expected behavior
When the recipient is edited directly and changed to another, the registered ‘RecipientsChanged’ event handler should be triggered.

## Current behavior
When the recipient is edited directly and changed to another, the registered ‘RecipientsChanged’ event handler should be triggered. It does however triggers when the recipient is removed or added.

## Steps to reproduce
1.	Enable any office-js based web add-in on your account which subscribes to the message compose surface (i.e. works "on compose")
2.	Ensure the taskpane is open as there is a constraint on the event “RecipientsChanged’” only available on taskpane.
3.	Register an handler for the “RecipientsChanged’ event with the mailbox item
4.	Add/Remove a recipient and confirm the handler was triggered
5.	While having a recipient, edit the recipient and change it to another
6.	Confirm the handler was not triggered

## Link to live example(s)
link to github repo: https://github.com/teejay001/OWA_RecipientUpdateHandeler.git

## Context
This breaks the entire add-in functionality since when the recipient is changed, there is no event raised and there is no prompt for reaction breaking business activities.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by samantharamon** [comment]
Thank you for detailing the steps you took and for providing a link to your repo, @teejay001.

@exextoc , could you please assist with this?

**Comment by exextoc** [comment]
We are not able to reproduce the issue at our end. Please answer the below questions to help us debug the issue. 
- Is the repro consistent for you or does it happen once in a while?
- Is it something which was working earlier and broke recently? 
- Can you please share a repro video of the experience with us?

**Comment by teejay001** [comment]
Hi,

Is the repro consistent for you or does it happen once in a while? - This happens consistently
Is it something which was working earlier and broke recently? - I don't know if this was working initially, this was discovered during a demo.
Can you please share a repro video of the experience with us? - Link to the requested video/gif .. https://github.com/teejay001/OWA_RecipientUpdateHandeler/blob/main/Animation.gif

**Comment by carlosb1504** [comment]
any update on this one please?

**Comment by exextoc** [comment]
This scenario is as per design for us.Can you please help us understand how it is impacting you??

**Comment by teejay001** [comment]
Hi,

Thanks for the response.

The issue highlighted is the fact that the event ["RecipientsChangedEvent"](https://docs.microsoft.com/en-us/javascript/api/outlook/office.recipientschangedeventargs?view=outlook-js-1.7) is not being triggered even though the recipient has clearly being changed. Not sure how this would be in line with design.

The implication of this is that developers are not able to respond to this change and ensure all necessary business logic is triggered to provide value to users/customers.

**Comment by exextoc** [comment]
Currently the feature you requested, is not a part of the product. We track Outlook add-in feature requests on our Tech [Community Page](http://aka.ms/M365dev-suggestions).Please submit your request there and choose the appropriate label. Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by exextoc** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
