### ISSUE TITLE
Escaping "[" "]" in capturing groups in document.body.search is not supported (Desktop word and Word online)

### ISSUE THREAD

**Issue by tomprod** [OfficeDev/office-js#2423]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: Windows 10
* Browser (if using Office on the web):  98.0.4758.82 (Official build) (64 bits)
 
(please note same problem happens on both word online and desktop) 

## Expected behavior

const searchResults = context.document.body.search('[[[][]]a-z]{1,}', { matchWildcards: true, matchCase: true });
searchResults.load('text');
await context.sync();
// expecting searchResults to contain "[test]" in items[0].text

## Current behavior
![image](https://user-images.githubusercontent.com/65723479/153373673-4b7ffb13-8377-4107-be22-f75ab604b5d2.png)

## Steps to reproduce
1.write text "[test]" in a blank word document

2. in scriptlab

```
async function run() {
  await Word.run(async (context) => {
    const body = context.document.body;

    const res = body.search("[[[][]]a-z]{1,}", {
      matchWildcards: true,
      matchCase: false,
    })    
    res.load("text");
    await context.sync();
    console.log(res.items[0].text);
  });
}
```

## Context
I am trying to detect strings representing special templating fields like #DC{[mycode+mycode2] / 100} and cannot proceed because of the mentionned problem

**Comment by samantharamon** [comment]
Thank you for reporting this, @tomprod.

@grangeryy, could you please assist with this?

**Comment by xiruatms** [comment]
@tomprod , thanks for connecting with us.

When I tried your search string in the "Find and Replace" dialog with Word on Win32, it complains that "The Find What text contains a range that is not valid.". 

Usually, APIs work in the similar way as native features on Word. That's why API took this as an invalid argument.

Just want to confirm how you got the search string "[[[][]]a-z]{1,}", have you every verified the feasibility somewhere else?  Or will you please share more details of your scenarios so that other options might be evaluated?

**Comment by tomprod** [comment]
@xiruatms thank you for your answer. 

I got the search string as i looked at the documentation on searching in word with office js at 
[https://docs.microsoft.com/en-us/office/dev/add-ins/word/search-option-guidance](url)

which states : 

![image](https://user-images.githubusercontent.com/65723479/153558420-30e050ba-a1ac-47e9-966b-3cbcb2b3e263.png)

![image](https://user-images.githubusercontent.com/65723479/153558460-da751682-364f-41e3-bed5-9db6da66e1c3.png)

and i know by experience that [a-z] is valid and works...


...as i previously ended up with several successful word office JS search strings like 

```
let searchString = `#{1}DC{1}[{]{1}[(&%$0-9A-Za-z+-/*=)]{1,}[}]{1}`;
```

which can successfully search for #DC{&7=1}

but, taking a more simple example, if i do [a-z]{1,} i can search for "test" (and the API accepts it and works as expected) but i cannot search for brackets as i don't understand how i can put them in a range, if i do [[]a-z]{1,} it doesn't work, and if i try to escape the brackets in the range, like [[[][]]a-z] it doesn't work neither.

As for the scenarios, i have several text strings in word documents that are fields that i need to detect and replace with their actual values that i get from a backend, fields like : 
#DC{H!A0D}
#DC{[H!A0D+H!A0E] /100}

My only problem is about brackets : i cannot put them in a range without getting an exception, so i'm trying to figure out how i can detect them and it seems that you can only escape them outside a range which is the reason why i created this issue.

**Comment by xiruatms** [comment]
@tomprod , thanks for making more clarification about your use cases.

Given “[” or "]" has special meaning in wildcard searches, if you want to search for them, it's best that you always put a backslash in front of “[” or "]".

In your use case, you may consider the search string as "[\[][a-z]{1,}[\]]". With this, "[test]" can be successfully found as I tested.

```
async function run() {
  await Word.run(async (context) => {
    const body = context.document.body;

    const res = body.search("[\[][a-z]{1,}[\]]", {
      matchWildcards: true,
      matchCase: false,
    })
    res.load("text");
    await context.sync();
    console.log(res.items[0].text);
  });
}
```
Please take a try and let me know whether it works for you.

**Comment by tomprod** [comment]
@xiruatms Thank you for you answer.

Yes it works for "[test]" but it will not work if i want to search for [] brackets that could be anywhere in the search string, like "#DC{[H!A0D+H!A0E] /100}"

That's why i was looking for a way to use brackets inside a capturing group like [a-z[]]

I took "[test]" as a simple example to explain my problem but maybe it was too simple, sorry for that

**Comment by xiruatms** [comment]
@tomprod , I'm not quite sure about your string pattern, but following search string works in my test case:
#DC[{][\[][A-Z][\!][A-Z0-9+]{1,}[\!][A-Z0-9]{1,}[\]][ /0-9]{1,}[\}]

With it, "#DC{[H!A0D+H!A0E] /100}" will be found.

There might be other better options of search string, this is just for your reference.

Please take a try and let me know whether it fits your need.

**Comment by tomprod** [comment]
@xiruatms of course it will work because you know in advance that there will be a [ at the beginning, a ] at the end etc... but i can have : 
 
#DC{[H!A0D+H!A0E] /100}
#DC{[H!A0D+H!A0E] - [H!A0F + H!A0Y] /100}

So that's why i'm trying to put the brackets **inside** the capturing group, like "[[]a-z0-9!+-/*]" just like i would do with regexes, so i could search for strings which contains "these specific characters #DC{**here**}"

Standard regex equivalent would be (with case insensitive option) : 

```
#DC{[A-Z\[\]0-9+!\/]*}
```

That is what i am trying to achieve with Office Word regexes, but it seems it is impossible for now.

**Comment by xiruatms** [comment]
@tomprod , as I didn't know what is the exact pattern you're trying to search, I can only show you a simple sample with escaping which API currently supported. It seems there's no explicit APIs issues now. I would like to try to design the wildcard string for you, but given I'm not a wildcard design expert, I can't make any promise here.

Whatever, I will be very glad to help if you identified any API issues.

**Comment by tomprod** [comment]
@xiruatms i don't know, this is hard to explain, but if you take my last comment, and read it, you will see that Word APIs don't support brackets in a [a-z] range, which is clearly a problem to me, the documentation states that you can escape brackets (which are special characters to word regexes) with other brackets, like [[] which works outside of a range, but does not work inside a range.

To me, it is clearly an API issue, because you can range [a-z] any characters, except special ones... ( "[ [[] []]a-z]{1,}" does not work, i added spaces because it is unreadable otherwise) so if somebody wants to search for special characters with a range, he cannot do it.

**Comment by xiruatms** [comment]
@tomprod , in the last code snippet I posted, you can see, brackets can be searched with escaping.

`async function run() {
  await Word.run(async (context) => {
    const body = context.document.body;

    const res = body.search("[\[][a-z]{1,}[\]]", {
      matchWildcards: true,
      matchCase: false
    });
    res.load("text");
    await context.sync();
    console.log(res.items[0].text);
  });
}`

![image](https://user-images.githubusercontent.com/40648203/154457590-126d4f08-d544-4dcc-9dc4-fcbd746b8047.png)

**Comment by tomprod** [comment]
@xiruatms you are right, this works. I just tested in Scriptlab with [test]. But it doesn't work with the string i provided in my initial post : 

"Context
I am trying to detect strings representing special templating fields like #DC{[mycode+mycode2] / 100} and cannot proceed because of the mentionned problem"

And not with the other strings i posted after.

Because, i think, this is my opinion, again, that you cannot escape brackets inside a range : in your example you are telling Word to look for a first bracket, then 1 or many a-z, then a final bracket, which doesn't match with the context i am explaining. 

Putting it more simple : i am trying to answer the question : "are there brackets in my string ? if so please find that string until next space"

Which, with regex, is really simple : 

```
#DC{[A-Z\[\]]*}
```

But, with Word regexes, as brackets cannot be put inside a range without getting an exception, i am stuck there

I really tried to use your code and tell to myself "oh maybe he's trying to tell me not to put escaped brackets INSIDE a range but OUTSIDE, so i tried "[\[][\]][a-z]{1,}" but it doesn't work, it doesn't find the string, or i am missing something, some trick that you are trying to tell me ?

**Comment by xiruatms** [comment]
@tomprod , if that's not a good example, how about the following one? When your pattern is a little more complex, the search text should be well designed:
`async function run() {
  await Word.run(async (context) => {
    const body = context.document.body;

    const res = body.search("#DC[\]\[a-z]{1,}", {
      matchWildcards: true,
      matchCase: false
    });
    res.load("text");
    await context.sync();
    console.log(res.items[0].text);
  });
}`
![image](https://user-images.githubusercontent.com/40648203/154470063-a4b4d052-e21e-446a-82d6-f96b8761e229.png)

**Comment by tomprod** [comment]
@xiruatms Yes it works 🎉 So yes, to escape [] inside range groups we can use backslash \ ! Didn't know it.
Thank you very much
