### ISSUE TITLE
Bug Report - Office Add-Ins "store" garbled inside Outlook App on Mac

### ISSUE THREAD

**Issue by gitcnd** [OfficeDev/office-js#2425]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Open any store item, and the "screenshots" CSS inflates (and is all warped) immediately, blocking text from view

## Steps to Reproduce, or Live Example
1. Click "Get Add-ins" from Outlook on Mac
2. Click on any add-in

* Additional details:
  1. example screenshot of one
<img width="957" alt="Screen Shot 2022-02-12 at 10 21 36 pm" src="https://user-images.githubusercontent.com/4301826/153711241-933eaf47-9f94-4c67-9975-64ddaadd8242.png">

## Your Environment
* Platform [Mac]: ______
* Host [Outlook]: ______

**Comment by exextoc** [comment]
We are not able to reproduce this issue from our side ,Can you please share Display settings and Outlook build version on which you are seeing this issue?

**Comment by gitcnd** [comment]
Microsoft Outlook for Mac 16.16.27(201012)
Also other Mac Outlooks versions too - it's the same on all my test machines.
It's not *every* store entry (e.g. Evernote still works), but it *is* almost all of them.

See screencast:  https://autode.sk/3BN5u8N

The Store expands the screenshots wrongly.
