### ISSUE TITLE
New Outlook Mac: body.getAsync should only return email body, not the whole html document

### ISSUE THREAD

**Issue by sybers** [OfficeDev/office-js#2426]
On "New Outlook" for Mac: `item.body.getAsync()` should only return email body, not the whole html document.

## Your Environment
* Platform: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.57 (22011101)
* Operating System: macOS
 
## Expected behavior
`Office.context.mailbox.item.body.getAsync("html")` should return the email inner body, not the whole document including `<html>`, `head` and `<body>` tags.

## Current behavior
When using the "New Outlook" version on macOS, `Office.context.mailbox.item.body.getAsync("html")` returns the whole email content, including `<html>`, `<head>` and `<body>` tags.

```js
Office.context.mailbox.item.body.getAsync(Office.CoercionType.Html, {}, ({ status, value }) => {
  if(status === Office.AsyncResultStatus.Succeeded) {
    console.log(value);
  }
});
```

Using the above code on OWA returns something like:
```html
<div style="font-family: Calibri, Arial, Helvetica, sans-serif; font-size: 12pt; color: rgb(0, 0, 0);"><br></div>
```

With the New Outlook version on Mac, we get this instead:
```html
<html>

<head>
<meta http-equiv=Content-Type content="text/html; charset=utf-8">
<meta name=Generator content="Microsoft Word 15 (filtered)">
<style>
<!--
 /* Font Definitions */
 @font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
span.EmailStyle17
	{font-family:"Calibri",sans-serif;
	color:windowtext;}
.MsoChpDefault
	{font-family:"Calibri",sans-serif;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
-->
</style>

</head>

<body lang=en-FR link="#0563C1" vlink="#954F72" style='word-wrap:break-word'>

<div class=WordSection1>

<p class=MsoNormal>&nbsp;</p>

<p class=MsoNormal>&nbsp;</p>

</div>

</body>

</html>
```

## Steps to reproduce
1. Switch to "New Outlook"  version on macOS (using top right toggle)
2. In the add-in, call `Office.context.mailbox.item.body.getAsync("html")`
3. The result should only contain the email body, as stated in the docs, not the whole email content.

## Link to live example(s)
This only happens with the "New Outlook" version, so unfortunately I can't create a repro with scriptlab.

## Context
We're developing an Add-In and many clients are starting to switch to the "New Outlook" version, this bug prevents us from supporting all versions of outlook (OWA, PC and Mac).

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by sybers** [comment]
Hello @exextoc, any updates on this? Thanks!

**Comment by exextoc** [comment]
Thanks for reporting this issue. It is on our backlog. We unfortunately have no timelines to share at this point.
Internal tracking id: Office : 5825347

**Comment by sybers** [comment]
Hey, any updates on this issue ? Was is resolved yet ?

**Comment by exextoc** [comment]
Hey @sybers ,

We are still following up on this issue, and will keep this thread posted if there are developments.

**Comment by exextoc** [comment]
@sybers Can you help us with following to better understand your scenarios:
1. Do you already have an Addin which works on Old Outlook and causes issue on New Outlook on Mac? If Yes, Can you share the output of body.getAsync() API in Old and New Outlook on Mac?
2. As a workaround can you extract the body using the <body> tag from the output you are getting in Mac?

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
