### ISSUE TITLE
smart quotes get corrupted when getHtml() is called (MacOS only)

### ISSUE THREAD

**Issue by rogozind** [OfficeDev/office-js#2428]
I have a document with a smart quote:
<img width="213" alt="image" src="https://user-images.githubusercontent.com/10505245/153990458-0d524df9-74c5-41fe-98ba-d0b2f9cae835.png">

(the document is the standard "Welcome to Word" from MS Word library).

When I use body.getHtml() API on Windows the HTML contains the symbol correctly.

When I do the same on MacOS I get 3 strange characters instead:

<img width="185" alt="image" src="https://user-images.githubusercontent.com/10505245/153990409-45e7349a-ad3c-4913-bf0f-234e1007e179.png">

The same code in the browser produces 3 HTML entitles for the respective characters.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __Windows, MacOS and Broswer____
* Host [Excel, Word, PowerPoint, etc.]: _Word_____
* Office version number: __16 ____
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior

I want to see smart quotes handled by macOS and Web the same way Windows does. 

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by yihuax-msft** [comment]
I cannot reproduce this issue on Mac.  For example, if I select "you've" and then get selected text, I got 6 characters, which is correct. Are you using Word on MAC of another language?

![image](https://user-images.githubusercontent.com/85257380/155645761-5c470450-c36a-4ac3-bdbf-a317713b8a7a.png)

**Comment by rogozind** [comment]
The problem is not getSelection(). The problem is body.getHtml() API. Take the entire HTML using getHtml() and look for that area. All smart characters will exhibit this issue.
I have Mac English version.

**Comment by yihuax-msft** [comment]
You are right. Looks that, if you get the whole body's html of that specific document, the issue does occur.
If we remove the lines above and below the interested place, that is, if the whole body only contains the paragraphs with the quote mark, body.getHtml works correctly.
We need to investigate further. Also, if you convert the 3 garbage characters into the coding values, I guess, it probably shows something.
Thanks for letting us know. If you have to call body.getHtml, you probably need to scan the returned text string, find the occurrences and replace them.

**Comment by rogozind** [comment]
I'm glad you reproduced it. I'll wait for the fix. It is not super critical because our users are primarily on Windows.
Any expectation when this can be fixed? And whether or not the fix will require Office client upgrade?

**Comment by yihuax-msft** [comment]
@rogozind, After my investigation, I think it is a behavior by design. Clearly, it is not "3 garbage characters", because when opening the html file with these "3 garbage characters", both Google Chrome and Apple Sarafi can display back the quote mark correctly. Also, Word can also display it correctly if you open the saved html file.

I think the quote mark is not an ordinary single quotation mark. This even can be seen in win32. You can see that in the html text obtained in windows, the mark is a ’ not a ' .

So, I doubt we want to any change for it. Even it is a good change, it may result in many problems for the customers who are depending on it.  Thus, could you just do a special check in your javascript on Apple platforms?

Thanks.

**Comment by rogozind** [comment]
I do not see either Chrome or Word being able read this file. Here is what I do:
1. Print getHtml() to Javascript console.
2. Copy paste this text to a file (rename to html). [raw.html.txt](https://github.com/OfficeDev/office-js/files/8157348/raw.html.txt)
3. Open it in Chrome: 
<img width="598" alt="image" src="https://user-images.githubusercontent.com/10505245/156069862-4896a4da-e60f-4dfc-af64-a09a7d31f5fa.png">
4. Open it in Word: 
<img width="833" alt="image" src="https://user-images.githubusercontent.com/10505245/156069923-d0db503a-1b21-49aa-bfa3-4f3c5249fa18.png">

This smart quote is Hex 0x2019. As the system exports UTF-8 string it is supposed to convert this code point to 3 bytes: E2 80 99. Instead it produces 3 symbols (6 bytes). The fact I see 3 symbols and not 3 bytes tells me that the system seems to do some kind of double conversion. Maybe reading raw bytes and interpreting them as latin1 and not as UTF8 to begin with?

Windows does not do that and produces correctly encoded smart character (3 bytes). Maybe because these are originally Windows characters and they are not handled properly on Mac?

I am not sure how can I workaround this issue because it happens for all smart quotes I tried. So I would need to know how these are converted.

Now, if I save this file from Word as HTML then the file is encoded correctly. Here is hex version:
<img width="502" alt="image" src="https://user-images.githubusercontent.com/10505245/156071775-2a48632f-5430-4e07-8a55-d6a522562d0f.png">
 Looks like only getHtml() API is having troubles.




--

**Comment by yihuax-msft** [comment]
I think you are right. I found I made a mistake today. Let me investigate more. Thanks.

**Comment by rogozind** [comment]
Sure thing. And thank you for such deep investigation.

**Comment by yihuax-msft** [comment]
@rogozind, My investigation found that on MAC, the returned html string is in fact a UTF-8 string. The quote mark is correct in that it occupies three bytes, with values 0xE2 0x80 0x99. See https://www.compart.com/en/unicode/U+2019. The task is to convert the utf-8 string to a normal javascript string. For some reason, the line
        var string = new TextDecoder().decode(uint8array);
does not work on my old MAC. Could you try whether it works on your machine? Thanks,

**Comment by rogozind** [comment]
Is this what you re looking for:
<img width="801" alt="image" src="https://user-images.githubusercontent.com/10505245/156275400-2b2f88be-3bc4-477b-bcfb-472140ff644e.png">
Seems to do teh right things both ways. This is the JS console from the addin.

**Comment by yihuax-msft** [comment]
Yes. But the decoded string still displays wrongly on my machine. If it works on your machine, it would be great in that the issue is resolved. My machine is just tooooo old.

**Comment by rogozind** [comment]
This test does work in the same JS console in the addin. But actual body.getHTML() does not. 
Is there any way to debug  getHTML()? Maybe a non-minified  version of the source code? If yes I can possible debug it for you.

**Comment by yihuax-msft** [comment]
@rogozind, It is indeed a bug in our source code, and I have fixed it. I will put the fix into the official build sometimes next week, and you should be able to see the fix in a release version roughly 16.0.15111.  Thanks for helping us find this issue.

**Comment by rogozind** [comment]
Yey! Thank you!
