### ISSUE TITLE
Excel API 1.1 - unable to append data to table

### ISSUE THREAD

**Issue by jeroenrosendaal** [OfficeDev/office-js#2429]
After updating our server we encounter problems with appending data to a table.
Before the update the code was running as expected.

## Your Environment
* Excel API 1.1
* Windows Server 2019 Standard (17763.2565)
* Office 2016 (16.0.52)

 
## Expected behavior
Rows are added to the selected table.

## Current behavior
Rows are not added to the table and triggers the error below:
```
Error: InvalidArgument: The argument is invalid or missing or has an incorrect format.
Debug info: {"code":"InvalidArgument","message":"The argument is invalid or missing or has an incorrect format.","errorLocation":"TableRowCollection.add"}
```
## Output
https://ibb.co/NWZq4Yb

## Steps to reproduce
1. Create a default Excel Add-in through Yo Generator with the following settings:
    - Office Add-in Task Pane Project.
    - Javascript
    - Excel
2. Add the code below to ```run``` function

```javascript
export async function run() {
  try {
    Excel.run(function (context) {
      //var sheet = context.workbook.worksheets.getItem("Sample");
      var sheet = context.workbook.worksheets.getActiveWorksheet();
      var expensesTable = sheet.tables.add("A1:D1", true /*hasHeaders*/);
      expensesTable.name = "ExpensesTable";
  
      expensesTable.getHeaderRowRange().values = [["Date", "Merchant", "Category", "Amount"]];
  
      expensesTable.rows.add(null /*add rows to the end of the table*/, [
        ["1/1/2017", "The Phone Company", "Communications", "$120"],
        ["1/2/2017", "Northwind Electric Cars", "Transportation", "$142"],
        ["1/5/2017", "Best For You Organics Company", "Groceries", "$27"],
        ["1/10/2017", "Coho Vineyard", "Restaurant", "$33"],
        ["1/11/2017", "Bellows College", "Education", "$350"],
        ["1/15/2017", "Trey Research", "Other", "$135"],
        ["1/15/2017", "Best For You Organics Company", "Groceries", "$97"]
      ]);
  
      sheet.activate();
  
      return context.sync();
    })
    .catch(function (error) {
      console.log("Error: " + error);
      if (error instanceof OfficeExtension.Error) {
        console.log("Debug info: " + JSON.stringify(error.debugInfo));
      }
    });
  } catch (error) {
    console.error(error);
  }
}
```

**Comment by yuc014** [comment]
Hi @jeroenrosendaal, 

After investigation, I can repro your issue and the full error log is: 
```
Debug info: {
    "code": "InvalidArgument",
    "message": "The argument is invalid or missing or has an incorrect format. |DEBUG ONLY|-2147024809",
    "errorLocation": "Table.name",
    "statement": "add.name = ...;",
    "surroundingStatements":
    [
        "var workbook = context.workbook;",
        "var worksheets = workbook.worksheets;",
        "var activeWorksheet = worksheets.getActiveWorksheet();",
        "var tables = activeWorksheet.tables;",
        "var add = tables.add(...);",
        "// >>>>>",
        "add.name = ...;",
        "// <<<<<",
        "var headerRowRange = add.getHeaderRowRange();",
        "// Instantiate {headerRowRange}",
        "headerRowRange.values = ...;",
        "var rows = add.rows;",
        "var add1 = rows.add(...);",
        "..."
    ],
    "fullStatements":
    [
        "Please enable config.extendedErrorLogging to see full statements."
    ]
}
```
The root cause is that you want to add two table with the same name. You could confirm it by searching the table name "ExpensesTable" in your file.

You could remove this line: `expensesTable.name = "ExpensesTable";` or give the table another name, then everything would be fine.

If you still block by the issue, please let me know.

**Comment by jeroenrosendaal** [comment]
@yuc014 I removed the ```expensesTable.name = "ExpensesTable";``` part but results in the same error. I'm running the add-in in a empty Excel file so there are no other tables

**Comment by yuc014** [comment]
@jeroenrosendaal 
Ok, that's weird. Here is my screen recording:
[myTestVideo.zip](https://github.com/OfficeDev/office-js/files/8068199/myTestVideo.zip)  (Compressed)

Project repo: https://github.com/yuc014/Test_tableAdd_Addin

Could you make a screen recording and provide your project sample? It is better for me to debug in your scenario.

**Comment by jeroenrosendaal** [comment]
@yuc014 I cloned your repo and ran the code.
Here is my recording
[recording.mov.zip](https://github.com/OfficeDev/office-js/files/8068919/recording.mov.zip)

**Comment by jeroenrosendaal** [comment]
@guliums @KelBowen Can you give an update?

**Comment by guliums** [comment]
Hi @jeroenrosendaal , sorry for late response. Are you using Office 2016? According to document [Excel.TableRowCollection class - Office Add-ins | Microsoft Docs](https://docs.microsoft.com/en-us/javascript/api/excel/excel.tablerowcollection?view=excel-js-preview#excel-excel-tablerowcollection-add-member(1)), this API only support insert single row in ExcelAPI 1.1. And it support add mutiple row after Excel APi 1.4. Could you try it on a latest version that support Excle APi 1.4? https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets
In Office 2016 you could split your code to insert single row one by one as workaround. Thanks.

**Comment by jeroenrosendaal** [comment]
@guliums Yes we are using Office 2016 with Excel API 1.1. I updated the code so it will insert one row, but results in the same error. See recording. We cannot update to Excel API 1.4 due to Windows version.
[recording.zip](https://github.com/OfficeDev/office-js/files/8130445/recording.zip)

**Comment by guliums** [comment]
Hi @jeroenrosendaal , could you help provide the session id after you hit the issue? You could get it from “File”->”Account”->”About Excel” , click the "About Excel" button and there is session ID. That will be very helpful for our investigation. Thanks!

**Comment by jeroenrosendaal** [comment]
@guliums Sure, this is what I see.

<img width="653" alt="Schermafbeelding 2022-02-24 om 08 44 17" src="https://user-images.githubusercontent.com/37666832/155480288-84ac4266-45a6-4080-b65e-7b963d63da70.png">

**Comment by jeroenrosendaal** [comment]
@guliums Is this the information you need?

**Comment by guliums** [comment]
Thanks @jeroenrosendaal for the information. We are investigating this and will update to you back when we have progress.

**Comment by guliums** [comment]
Hi @jeroenrosendaal , thanks very much for reporting the issue. This should be a bug in Office 2016 and I have created ADO#5864356  internally in our backlog. As a workaround, could you try adding an extra argument as first parameter? Below code should work on Office 2016.
expensesTable.rows.add(null,null, [["1/1/2017", "The Phone Company", "Communications", "$120"]])

**Comment by jeroenrosendaal** [comment]
Hi @guliums, thanks for your feedback. With the extra parameter it works indeed.
