### ISSUE TITLE
Office.context.mailbox.item.addFileAttachmentFromBase64Async is not a function

### ISSUE THREAD

**Issue by P4trik** [OfficeDev/office-js#243]
Can't call the method  "addFileAttachmentFromBase64Async" of the mail item in compose mode.
I linked this lib: <script src="https://appsforoffice.microsoft.com/lib/beta/hosted/office.js"></script>
Everything else works finde for me. I'm using the Outlook Online Client (OWA).

But I'm happy that these method is now part of the lib :-)

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Browser (if using Office Online): Chrome Newest

## Useful logs
Unhandled promise rejection TypeError: Office.context.mailbox.item.addFileAttachmentFromBase64Async is not a function
    at index.js:9222
    at Object.dispatch (index.js:50390)
    at dispatch (<anonymous>:1:28684)
    at Object.SetAttachmentToOutlookItem (index.js:69293)
    at AttachmentItem.componentWillMount (index.js:69248)
    at callComponentWillMount (index.js:36063)
    at mountClassInstance (index.js:36159)
    at updateClassComponent (index.js:37500)
    at beginWork (index.js:38141)
    at performUnitOfWork (index.js:40953)
    at workLoop (index.js:40976)
    at renderRoot (index.js:41007)
    at performWorkOnRoot (index.js:41563)
    at performWork (index.js:41484)
    at performSyncWork (index.js:41461)
    at requestWork (index.js:41361)
(anonymous) @ core.js:6271
module.exports @ core.js:3164
(anonymous) @ core.js:6265
module.exports @ core.js:2093
queue.(anonymous function) @ core.js:2382
run @ core.js:2368
listener @ core.js:2372

**Comment by exextoc** [comment]
The [Preview API Requirement Set](https://docs.microsoft.com/en-us/javascript/office/objectmodel/preview-requirement-set/outlook-requirement-set-preview?context=outlook%2Fcontext&view=office-js) does not guarantee that an API is supported across all platforms. We are working to bring this functionality to all platforms soon.

<blockquote>
Note: This documentation is for a preview requirement set. This requirement set is not fully implemented yet, and clients will not accurately report support for it. You should not specify this requirement set in your add-in manifest. Methods and properties that are introduced in this requirement set should be individually tested for availability before using them.
</blockquote>

**Comment by P4trik** [comment]
Would be great to know on which platforms I have at least to expect it could work.
For experimental usage: What kind of Requirement MinVersion do I have to set? 1.7?

**Comment by exextoc** [comment]
There is no way to specify that your add-in requires an API that is currently in preview. `addFileAttachmentFromBase64Async` is currently supported in the latest version of [Outlook for Windows (CTR)](https://docs.microsoft.com/en-us/officeupdates/update-history-office365-proplus-by-date) with plans to bring support to other clients in the future. When it is added to an API requirement set, it will be guaranteed to be supported across all clients in their latest version. Please note that since the API is in Preview, it may change.
