### ISSUE TITLE
setSignatureAsync with coercionType html and data contains &apos; does not displayed Outlook for Windows

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#2430]
* Platform : PC desktop
* Host : Outlook
* Office version number: 2112 (Build 14729.20260)
* Operating System: Windows

 
## Expected behavior
it should show `'` like outlook online. 

Outlook for Online
![image](https://user-images.githubusercontent.com/13063615/154016655-de9e7a51-6b01-4f54-89e4-87b4497f4fda.png)

Outlook for Windows
![image](https://user-images.githubusercontent.com/13063615/154015801-ec7bc490-2a06-4c10-b707-7fdf73f94a82.png)

## Current behavior
It does not work on outlook for PC (only `&apos;`) , other html entities work fine.

## Steps to reproduce

1. Try a sample from scriptlab api setSignatureAsync with coercionType is html.
2. insert data contains `&apos;` .
3. in outlook online, it can show `'` in the mail body, but outlook for windows it keep `&apos;`

**Comment by exextoc** [comment]
Unfortunately, `&apos` is only supported in latest HTML 5, which Outlook for Windows does not support. It works in Outlook for Online because the browsers chose to support it. You can try instead using HTML code &#39; or just the symbol '.
