### ISSUE TITLE
ItemSend event broken

### ISSUE THREAD

**Issue by svlc1** [OfficeDev/office-js#2434]
When using an add-in that uses the ItemSend event the mail item stays in drafts.

## Your Environment

* Platform: Office on the web
* Host: Outlook
* Browser (if using Office on the web): Firefox
 
## Expected behavior
The mail item is sent.

## Current behavior
When sending the mail item, the browser shows a pop-up that disappears very quickly. The mail item is not sent, but instead put in the drafts folder. The ItemSend event is also not triggered.
When sending the mail from the drafts folder the mail is send correctly and the ItemSend event is triggered.

## Steps to reproduce
Can be reproduces using the Contoso example project:
https://github.com/OfficeDev/Outlook-Add-in-On-Send

**Comment by neville-jones** [comment]
same as #2431  ?
