### ISSUE TITLE
I am able to send POST request to domain not listed in AppDomains

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/office-js#2435]
I am able to send a request to an external domain (Rollbar API) which is not listed in the AppDomains section of my manifest. Is that intentional (see https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-1#specify-domains-you-want-to-open-in-the-add-in-window)? I list my API endpoint but perhaps that is not needed either? I am confused :-)  

This is seen on Word Windows Desktop, Version 2109 14430.20270, Windows 10 Enterprise

**Comment by RuizhiSunMS** [comment]
Hello @JensMadsen , please add some information following the format below to make us clear about your question ( or this issue happened together with the other one you submitted today?)
Platform : 
Host : 
Office version number: 
Operating System:

**Comment by JensMadsen** [comment]
@RuizhiSunMS I have tried to provide the information you asked for :-)

**Comment by RuizhiSunMS** [comment]
Thanks @JensMadsen .
@yihuax-msft another issue about word desktop, would you please take a look ?

**Comment by jargil** [comment]
@JensMadsen - yes this is expected. AppDomains lists the domains that you'll be allowed to navigate to in the add-in frame as well as which domains will be able to call Office APIs, it does not prevent doing XHRs, that's controlled by the browser via CORS, etc., but not by Office.

**Comment by JensMadsen** [comment]
Thank you for the explanation @jargil . I misunderstood things. I thought that we had to label our API as allowed in order to send requests to it.
