### ISSUE TITLE
AgaveErrorUX folder wrong name

### ISSUE THREAD

**Issue by MarioVitale** [OfficeDev/office-js#2437]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When opening office.js in Outlook web on Exchange (I tested it in versions 2013, 2016, 2019), the add-in tries to load the node_modules/@microsoft/office-js/dist/AgaveErrorUX/index.html file but in this repository the folder is called agaveerrorux. This blocks the add-in in Outlook web.
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Browser (if using Office on the web): Edge 98.0.1108.50
 
## Expected behavior

Loading the correct folder AgaveErrorUX
## Current behavior

Missing folder AgaveErrorUX, but is present with wrong name agaveerrorux
## Steps to reproduce

1. Open plugin from outlook web

**Comment by exextoc** [comment]
@MarioVitale are you trying to create a new Outlook Addin and facing this problem? What are the exact steps that you have followed?

**Comment by MarioVitale** [comment]
I tested one of our plugins that works well in O365.
On the outlook web on exchange server the user must confirm the identity of the plugin (Error message: This add-in has been disabled to help keep you safe. To continue using the add in, validate that this item is hosted in a trusted domain or open it in the Office desktop app.)
At first launch from web office js tries to open AgaveErrorUX to bring up the trust domain popup and the plugin not finding the correct folder goes into error.
By renaming the agaverrorux folder and files to AgaveErrorUX instead, the plugin opens the trust domain popup, and everything works correctly.

‘Trust domain popup’:
![Popup](https://user-images.githubusercontent.com/25910212/154648273-a255c737-d44a-4e5c-8b4f-579aaeef0c34.png)

To test this flow I sideloaded a plugin with @microsoft/office-js 1.1.73 npm library.

**Comment by exextoc** [comment]
We are not able to repro this ,can you help us with these queries for further investigation:-
1)Is the repro consistent for all add-ins or happens for some add-ins?
2)Since when are you seeing this issue, was this happening before? 
3)Can you help us with a test account/repro video where it doesn't find the correct folder and goes into error?

**Comment by MarioVitale** [comment]
I created 2 projects, one using Node as http server and one using wildfly.
With Node the problem does not arise because node works with insesitive case path.
![Node-OK](https://user-images.githubusercontent.com/25910212/155534560-60d40925-e03c-44c3-8073-2a546ef7e5d8.png)

Instead with wildfly the problem arises because it works with path case sensitive.
![Wildfly-Error](https://user-images.githubusercontent.com/25910212/155534602-559029a8-2461-446c-89f9-b63057850383.png)


At this [link](https://farnet-my.sharepoint.com/:u:/g/personal/mario_vitale_farnetworks_com/ES_KTGLgsqVHhUT6ORx5oHABIb5mZjZvo-pMg-v040m23g?e=9XC2Zg) you will find an archive that contains the 2 projects and the manifest to load in Exchange 201X to run the test.

To launch the first project, use npm start in the OutlookAddinTest folder.
To launch the second project, launch standalone.sh or standalone.bat in wildfly-26.0.1.Final/bin.

**Comment by exextoc** [comment]
Hey @MarioVitale ,

We are unfortunately unable to replicate this issue. Will it be possible for you to share a test account credential with us where this issue is reproducible at `OutlookAddins@M365x693897.onmicrosoft.com`?

**Comment by MarioVitale** [comment]
I have emailed you the info.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding the AgaveErrorUX folder. It has been put on our backlog. We, unfortunately, have no timelines to share at this point 

Internal tracking id: Office: 2629527

**Comment by johnbergvall** [comment]
We have customers that are having problems as well.

Our workaround for the time being:

`grep -lR AgaveErrorUX node_modules/@microsoft/office-js | xargs sed -E -i 's~AgaveErrorUX/~agaveerrorux/~g;s~([/\\])AgaveErrorUX~\1agaveerrorux~g;s~AgaveErrorUX.(css|js|html)~agaveerrorux.\1~g'`
