### ISSUE TITLE
Not able to retrieve location through API when it is filled as free text in calendar event

### ISSUE THREAD

**Issue by harishvgupta** [OfficeDev/office-js#244]
When the location field is entered only as a free text and not through the autocomplete options appearing, the value returned through the API Office.context.mailbox.item.Location.getAsync is an empty string and not the corresponding text entered.

## Expected Behavior
The location should be retrievable even when it is entered as free text and not selected through autocomplete fields.

## Current Behavior
Currently, the location is retrieved as blank string if entered as free text.

## Steps to Reproduce, or Live Example
- Create a new calendar event.
- Enter a location. For eg, Boston. Do not select it from the autocomplete. Do not press enter after entering the location. Just click somewhere on the page.
- Try to access it through add-in using the following Office.context.mailbox.item.Location.getAsync

Attaching screenshot depicting the problem.[
![locationvalueentered](https://user-images.githubusercontent.com/43240238/45489747-6e9a8380-b765-11e8-81fd-a865dccdf4dd.PNG)
![valueretrievedasblank](https://user-images.githubusercontent.com/43240238/45489748-6e9a8380-b765-11e8-8479-2e4c60017a02.png)

](url)

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding location API in calendar event. It has been put on our backlog. We unfortunately have no timelines to share at this point.
