### ISSUE TITLE
Speech Sdk not working on Outlook app on mac 

### ISSUE THREAD

**Issue by alexisweeren** [OfficeDev/office-js#2440]
I am using the speech sdk speech to text in a custom outlook add-in. When I am using the add-in on outlook on the web it works with no problem but when mac users are using the Outlook add-in on the native outlook app it doesn't always work. Are there any limitations to using the add-in on the native Outlook app for macs?

It isn't working for the Microsoft Outlook for Mac version 16.57.

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by eric-urban** [comment]
@alexisweeren @KelBowen - In case this is an issue with the Cognitive Services Speech SDK, please see [https://github.com/MicrosoftDocs/azure-docs/issues/88349](https://github.com/MicrosoftDocs/azure-docs/issues/88349). I hope this helps!

**Comment by ajays-msft** [comment]
This forum is limited to supporting office-js apis. For any other issues, please find more information from learn.microsoft.com
