### ISSUE TITLE
Using Outlook REST API in hybrid setup

### ISSUE THREAD

**Issue by plamenbotev** [OfficeDev/office-js#2441]
Hello,
We are using the Outlook REST API for various tasks in our addin. 
Can you please share if the Outlook REST services are available in hybrid setup environment with Exchange 2019? 
Currently I am struggling to find definitive documentation about that other than: 
https://techcommunity.microsoft.com/t5/exchange-team-blog/on-premises-architectural-requirements-for-the-rest-api/ba-p/605609

Best Regards,
Plamen

**Comment by exextoc** [comment]
Are you using REST API in your addin with token from getcallbacktokenasync addin API call? If so, REST API with getcallbacktokenasync should work in on-premise Exchange 2016 and 2019

**Comment by plamenbotev** [comment]
Hello @exextoc,
Thank you so much for taking the time to look into this.
Yes, we are using the REST API with token from getcallbacktokenasync.
Should the services work out of the box in this case or is there anything specific on the exchange server that must be done additionally? If any I would really appreciate if you point me in the right direction in the documentation.

Best Regards,
Plamen

**Comment by exextoc** [comment]
Please use [documentation link](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api) for REST APIs. As mentioned earlier REST APIs should work with on-prem exchange 2016 and 2019.
If the documentation doesn't help, please provide the exact error to be able to help better.
