### ISSUE TITLE
Input file html dialog component is disabled when sideloading, 

### ISSUE THREAD

**Issue by jrpally** [OfficeDev/office-js#2442]
yarn sideload 

Causes:
Input file html dialog component is disabled when sideloading MS Word.

**Comment by RuizhiSunMS** [comment]
Hello @jrpally , can you provide some more information about your issue? It's pretty hard for us to locate based on what you provided. 
One suggested format is as below:
Platform :
Host :
Office version number:
Operating System:
Current Behavior
Expected Behavior
Step to Reproduce Issue
Thanks.
