### ISSUE TITLE
Twice or Unable sign-in with the Admin Managed

### ISSUE THREAD

**Issue by Refinitiv-365** [OfficeDev/office-js#2443]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
Twice or Unable sign-in with the Admin Managed in Insert tab. It's 
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome, Microsoft Edge, Firefox
 
## Expected behavior

Single sign in from the Admin Managed
## Current behavior

After you click "Sign In" in Add-ins.
![image](https://user-images.githubusercontent.com/98725157/155060547-bcad1c2c-0d93-49b1-853b-c76cb160e49e.png)
It will redirect to Pick an account and choose your account it's sign in process.
![image](https://user-images.githubusercontent.com/98725157/155062691-5fdd4297-6d4c-42df-97d4-71105eaaced9.png)
And it's redirect to first page and you sign in again
![image](https://user-images.githubusercontent.com/98725157/155062619-9e6c5b7a-9cc8-449b-b27e-afdafd8a1ec8.png)

## Steps to reproduce

1. sign in and open new workbook
2. sign out but the workbook is still opened
3. clear local storage, session storage and cookies
4. found warning msg : sign in with valid profile to see add-ins

## Link to live example(s)

# Provide additional details

## Useful logs

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by guliums** [comment]
@AkhileshShah-MS Looks like an issue with Centralized Deployment, could you help triage? Thanks

**Comment by guliums** [comment]
According to @AkhileshShah-MS it is auth issue on client side. @preethikakiru could you help triage? Thanks!
