### ISSUE TITLE
Content add-ins intermingle document settings if PPT slide with add-in is copied

### ISSUE THREAD

**Issue by sebiJo** [OfficeDev/office-js#2445]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When a slide which contains a content add-in is copied, the copied add-ins will share the same settings object, which is very problematic. The behavior also occurs when the insertBase64 method is used (since it is similar to copying). The bug does not occur when a fresh copy of the add-in is added to a slide.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: 16.0.14326.20784 
* Operating System: Windows 10 (Home, 19043.1466)
* Browser (if using Office on the web): Edge Legacy Engine
 
## Expected behavior
Two add-in instances must always have their own settings object. Document Settings need to be clearly separated.

## Current behavior
When a slide with a content add-in is copied, the copied add-ins will share the same settings object.

## Steps to reproduce
1. Insert a content add-in to a slide and save some settings in this add-in
2. Copy the slide with the add-in
3. Change some settings in the copied add-in instance
4. Go back to the original add-in slide and reload it
5. Observe that the original add-in will read the settings from the copied add-in!

## Link to live example(s)
Test with the following PPT and a simple Breaktime add-in:
[office-bug.pptx](https://github.com/OfficeDev/office-js/files/8116014/office-bug.pptx)

# Provide additional details
So far, I could not reproduce this with Mac. I could also not reproduce with Windows 11 or Office Online.

## Context
This bug makes it impossible to work with two add-in instances in the same slide deck. Most users will always copy the slide with a content add-in, instead of choosing the long way via Insert->My Addins. Users will think that the add-in implementation does not work.

**Comment by ononder** [comment]
Logged internal bug 5969153

**Comment by sebiJo** [comment]
Addition: When you delete the previously copied slide with an add-in, a Zombie of the add-in keeps living in the memory and  still responds to events, such as switching slides or switching to presentation mode. This can lead to the effect that an add-in suddenly starts playing sounds/music, even though all slides of the entire slide deck have been removed by the user.
