### ISSUE TITLE
Dialog's "wants to display a new window" has white-on-white message text

### ISSUE THREAD

**Issue by markdon** [OfficeDev/office-js#2446]
In Outlook Web, when an add-in tries to open a dialog from a ui-less function with the `promptBeforeOpen: true` option, the dialog has unreadable white-on-white text.

In my case, I'm opening a dialog from an on-send event handler. 

Light mode:
![image](https://user-images.githubusercontent.com/9063681/155237546-b97124f1-a3b0-4038-8ce3-7384faa909f6.png)
Dark mode:
![image](https://user-images.githubusercontent.com/9063681/155237570-a7ef68b8-7dc4-4370-b6bb-c76a8fdd7839.png)

## Your Environment

* Platform: Web
* Host: Outlook
* Browser: Chrome
 
## Expected behavior
Text/background colour combo has an accessible contrast ratio.

## Current behavior
Text is unreadable for everyone.

**Comment by exextoc** [comment]
We are not able to reproduce this issue ,can you please share the manifest or sample code which you are using ??

**Comment by markdon** [comment]
I figured out what's happening.

Part of how this dialog works involves opening the addin's FunctionFile URL in an iframe. The dialog text and buttons are created inside this iframe. CSS that appears when loading the FunctionFile URL can affect this dialog!

My addin supports dark mode, which was turning the dialog text white.

I may open a docs issue to make this behaviour more obvious.
