### ISSUE TITLE
Formulas in tables does not work

### ISSUE THREAD

**Issue by d4rth-v4d3r** [OfficeDev/office-js#245]
Excel stopped adding rows to tables if a cell contains a formula. The formula works if it is written.

## Expected Behavior
All rows must be rendered in spreadsheet without any errors. 

## Current Behavior
Now it only print some rows and throws a General Exception error, as will be described below:

![image](https://user-images.githubusercontent.com/5044302/45508839-2a9e8300-b753-11e8-830a-d5d8a29e763c.png)

## Steps to Reproduce, or Live Example

* Additional details:
  1. Using this version
`  <script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>`

  2. Using Office-Fabric-UI-React 6.67.3

  3. Sample code

`        const processElement = element => {
                let updateDate = moment(element.updateDate);
                return {
                    Item: element.index,
                    Customer: element.code,
                    Address: element.address,
                    Visited: element.visited ? "Yes" : "No",
                    Updated: updateDate ? updateDate.format("L LTS") : "",
                    Time: "=IFERROR(IF([@Visited]="Yes",[@Visited]-OFFSET([@Updated],-1,0),0),0)",
                    Frequency: getInterval(element.dayInterval)
                };
            };
`
`
            return Promise.all(
                dataBinding.map((element, index) => {
                    let data = processElement(element);
                    let values = _.values(data);
                    return dataTable.rows.add(null, [values]);
                })
            )`

## Context
This code worked perfectly two days ago in my machine and now it works only in a dev machine with Office Version 1804 (Build 9226.2156)

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PCDesktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 1808 Build 10730.20102 Click-to-Run
* Operating System: Microsoft Windows [Version 10.0.17134.285]

## Useful logs
![image](https://user-images.githubusercontent.com/5044302/45508241-908a0b00-b751-11e8-9a87-aa0700c65d83.png)

`GeneralException: There was an internal error while processing the request.
   {
      [functions]: ,
      __proto__: { },
      code: "GeneralException",
      debugInfo: {
         [functions]: ,
         __proto__: {
            [functions]: ,
            __proto__: null
         },
         code: "GeneralException",
         errorLocation: "TableRowCollection.add",
         fullStatements: [ ],
         message: "There was an internal error while processing the request.",
         statement: "var add1=rows.add(...);",
         surroundingStatements: [
            0: "var workbook=context.workbook;",
            1: "var tables=workbook.tables;",
            2: "var table=tables.getItem(...);",
            3: "var rows=table.rows;",
            4: "var add=rows.add(...);",
            5: "// >>>>>",
            6: "var add1=rows.add(...);",
            7: "// <<<<<",
            8: "var add2=rows.add(...);",
            9: "var add3=rows.add(...);",
            10: "var add4=rows.add(...);",
            11: "var add5=rows.add(...);",
            12: "var add6=rows.add(...);",
            13: "...",
            length: 14
         ]
      },
      description: "There was an internal error while processing the request.",
      innerError: null,
      message: "There was an internal error while processing the request.",
      name: "OfficeExtension.Error",
      stack: "GeneralException: There was an internal error while processing the request.
   at Anonymous function (https://unpkg.com/@microsoft/office-js@1.1.8/dist/excel-win32-16.01.js:21:220328)
   at ai (https://unpkg.com/@microsoft/office-js@1.1.8/dist/excel-win32-16.01.js:21:268314)
   at ft (https://unpkg.com/@microsoft/office-js@1.1.8/dist/excel-win32-16.01.js:21:268401)
   at d (https://unpkg.com/@microsoft/office-js@1.1.8/dist/excel-win32-16.01.js:21:268221)
   at c (https://unpkg.com/@microsoft/office-js@1.1.8/dist/excel-win32-16.01.js:21:266917)",
      traceMessages: [
         length: 0
      ]
   }
`

**Comment by JuaneloJuanelo** [comment]
hello thanks for reporting this. I was not able to reproduce the behavior. i was trying my own sample (here is a [Gist ](https://gist.github.com/JuaneloJuanelo/171895a746d3cb1c2681a88b37dca916) you can import on scriptlab). I am not getting an error.

Can you please include a snippet that inserts the sample table and the formula you are trying to write? (similar to the one i sent, check the create table snippet)
that way we can investigate in more detail.

**Comment by d4rth-v4d3r** [comment]
Forgot to comment that I resolved this issue adding `babel-polyfill` npm package
