### ISSUE TITLE
Caanot load addin in yarn workspace in Word version using ie11

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/office-js#2452]
I have created a fresh project using yeoman https://github.com/OfficeDev/generator-office
I choose: typescript, Word and React. Everything works fine out of the box. 

If I do the exact same thing in a fresh yarn workspace it does not work. I suspect that the problem is that some packages (related to polyfill??) do not work as expected. 

I have experimented with the `nohoist` config but no luck. Do you have any experience with this problems?

**Comment by nkkinariwala** [comment]
@millerds - Is it something you can help with?

**Comment by millerds** [comment]
The projects we output using 'yo office' are setup using npm packaging instead of yarn.  I'm not sure what you mean by "do the exact same thing in a fresh yarn workspace" . . . can you explain what you are doing to accomplish this?

**Comment by JensMadsen** [comment]
@millerds I think that this is a webpack/yarn/babel problem. I create a yarn workspace root with a subfolder foo. In the subfolder I put my yeoman generated add-in. Now foo is a yarn workspace. Yarn workspace gather dependencies in the root level node_modules. I think this is where thing goes wrong because some parts are not transpiled correctly by babel because the workspace node_modules folder has symlinks. So in conclusion this Is not a office-js problem; so feel free to close this issue (I have solved my own problem ;-) ). Sorry about the noise! I was just getting desperate trying to support IE11 .. :-D
