### ISSUE TITLE
Unable to run embedded WASM (which uses SharedArrayBuffer)

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#2453]
# Provide required information needed to triage your issue
I am attempting to instantiate a WASM module within my Outlook add-in and am running into issues with the use of ```SharedArrayBuffer``` not being available.

![image](https://user-images.githubusercontent.com/7740624/155804690-c8696a2d-3d8f-489a-ad5b-ca71941621a4.png)

From my reading, it appears that there are specific security requirements that must be met in order to use ```SharedArrayBuffer```. Specifically, several headers must be set with specific values. You can find more details [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer).

As WASM is a fairly popular technology and allows developers to add functionality that is just not possible with javascript, I'm hoping that Office add-ins would support this (in all environments -- OWA and desktop).

## Your Environment
I tested this in Chrome and Firefox, but would also like to see this supported on desktop clients as well.
 
## Expected behavior
The ability to use ```SharedArrayBuffer``` (and other common functionality used by WASM) in Office add-ins.

**Comment by exextoc** [comment]
Could you provide [ULS logs](https://docs.microsoft.com/en-us/office365/troubleshoot/diagnostic-logs/collect-office-diagnostic-logs) to help us better diagnose this issue?
