### ISSUE TITLE
The OnSend add-in does not run in Outlook on the web when I follow certain steps to send an email.

### ISSUE THREAD

**Issue by t-miyake** [OfficeDev/office-js#2454]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

The OnSend add-in does not run in Outlook on the web when I follow certain steps to send an email.
Also, depending on the procedure, the email will not be sent.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook on the web
* Office version number: ______
* Operating System: Windows10 or 11
* Browser (if using Office on the web): Edge (98.0.1108.62)
 
## Expected behavior

OnSend add-in works properly when sending emails.

## Current behavior

The OnSend add-in does not run in Outlook on the web when I follow certain steps to send an email.
Also, depending on the procedure, the email will not be sent.

## Steps to reproduce

If you follow the steps below to send an email, the OnSend add-in will not be run and the email will be sent immediately.
1. Select any m365 group from the Folders on the left.
2. Press the New message button to create and send a new email.

If you follow the steps below to send an email, the email will not be sent.
OnSend add-in will also not be run.
1. Select any m365 group from the Folders on the left.
2. Press the New message button to create a new email.
3. Press the button in the upper right corner of the new email to view it in a new window.
4. Select Inbox from Folders.
5. In the email that opens in a new window, enter the recipient and body text, and click the Send button.

## Link to live example(s)

# Provide additional details

  
## Context

We provide solutions to prevent misdirection of e-mails by displaying a confirmation screen before sending an e-mail, and blocking the sending of e-mails depending on the contents and destination of the e-mail.

If the OnSend add-in is not executed correctly, our solution will be useless.

## Useful logs

The following URL is a video of the actual operation and the problem being encountered.
https://user-images.githubusercontent.com/9583126/155931156-918d5d6d-a5d0-4434-ac32-fbca41fae52a.mp4

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Thanks for reporting the issues regarding on-send add-in. We are able to reproduce both issues internally. It has been put on our backlog. We unfortunately have no timelines to share at this point. Internal tracking ID: 2647522

**Comment by t-miyake** [comment]
It has been almost a year now and this problem does not been fixed.
Do you have any updates?

**Comment by exextoc** [comment]
Hey @t-miyake , we are yet to fix this issue. We are following this up internally and will keep this thread posted for updates. However, we have no timelines to share.
