### ISSUE TITLE
Description of item cannot be updated anymore after calling saveAsync

### ISSUE THREAD

**Issue by lukesolar** [OfficeDev/office-js#2455]
After calling saveAsync on an occurrence of a meeting series, the Description of the item cannot be updated anymore by the user and the items id becomes invalid. 

This is a serious bug related to Outlook (Office 2016). 

## Your Environment

* Platform: PC
* Host: Outlook
* Office version number: Office 2016 (16.0.5278.1000) 32-bit
* Operating System: Windows
* Calendar Provider: Exchange 2016
 
## Expected behavior
Only occurrences of meeting series are affected by this bug. After calling [saveAsync](https://docs.microsoft.com/en-us/javascript/api/outlook/office.appointmentcompose?view=outlook-js-1.4&preserve-view=true#outlook-office-appointmentcompose-saveasync-member(1)) the users should be able to continue to change the description and save the item. 

## Current behavior
Instead, after calling saveAsync, when the user changes the description and saves the item, all changes to the description are lost. 

## Steps to reproduce
1. Create a meeting series
2. Open the first occurrence of the series
3. Call saveAsync on that occurrence (and make sure the call returns a valid item id)
4. Change the description of the occurrence by adding some text 
5. Save / Send the update
6. Reopen the occurrence -> The description is unchanged and does not reflect the changed text

# Provide additional details

## Context
This issue was uncovered because our app allows the user to add a link to each meeting occurrence to take meeting notes. This essentially blocks our Add-in from working correctly and we probably loose this customer until they update in 2024.

**Comment by exextoc** [comment]
Thanks for reporting this issue. After careful consideration, our team has decided to not fix this issue. Outlook 2016 has ended mainstream support. We recommend you to upvote or create a new [Tech Community](http://aka.ms/M365dev-suggestions) item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue we will re-activate as needed.
