### ISSUE TITLE
Outlook TypeError: Cannot set properties of undefined (setting 'targetOrigin')     at OSF.DDA.WAC.Delegate.closeDialog

### ISSUE THREAD

**Issue by dm-shlandii** [OfficeDev/office-js#2458]
WebAddin for Outlook. OfficeJS 

We have functionality which open Dialog (via dialogAPI) from commands.js
Dialog showed correctly, but when button is pressed and it should close - got at error.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: _Windows
* Browser (if using Office on the web):  Using on web - Chrome
 
## Expected behavior
Dialog is closing.

## Current behavior
Dialog not closing and further logic is not executed.

## Steps to reproduce
1. Open Dialog 
2. Close dialog

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context
Production build

## Useful logs
- [* ] Console errors
Uncaught TypeError: Cannot set properties of undefined (setting 'targetOrigin')
    at OSF.DDA.WAC.Delegate.closeDialog (outlook-web-16.01.js:20:212335)
    at g.<computed> (outlook-web-16.01.js:20:86901)
    at OSF.DialogHandler.value [as close] (outlook-web-16.01.js:20:187604)
    at Array.w (commands.js:1:5202)
    at OSF.EventDispatch.fireEvent (outlook-web-16.01.js:20:167958)
    at OSF.EventDispatch.fireOrQueueEvent (outlook-web-16.01.js:20:168381)
    at Object.onEvent (outlook-web-16.01.js:20:85966)
    at outlook-web-16.01.js:20:121026
    at M (outlook-web-16.01.js:20:108475)

**Comment by stefanoslig** [comment]
@dm-shlandii check this one https://github.com/OfficeDev/office-js/issues/2457. It's the same issue. As a workaround try to set `displayInIframe: false` when you open the dialog

**Comment by ab1osborne** [comment]
Our customers are seeing the issue as well. Please fix asap.

**Comment by neville-jones** [comment]
Seen by our customers too. Huge impact on customers as dialog shown from an on send event handler - users cannot close dialog so messages cannot be sent from OOTW. Please fix ASAP

**Comment by exextoc** [comment]
Issue has been fixed and rolled out. Please confirm.

**Comment by nkkinariwala** [comment]
@dm-shlandii - looks like issue is fixed and rolled out. can you please confirm from your side?

**Comment by ElizabethSamuel-MSFT** [comment]
Seems like this was fixed so closing out.

@dm-shlandii If you're still facing this issue, please comment so we can reopen. Or create a new issue.

Thanks.
