### ISSUE TITLE
Sensitivity label requirement causing error AccessDenied: You don't have sufficient permissions for this action

### ISSUE THREAD

**Issue by szilardd** [OfficeDev/office-js#2459]
I have an Excel add-in that was working correctly. At some point, my organization introduced a requirement to assign a sensitivity label for documents, and it looks like that breaks the add-in.

## Your Environment

* Platform: PC Desktop
* Host: Excel
* Office version number: Office 365, Excel Version 2112 (Build 14729.20322)
* Operating System: Windows 10 Professional
* Browser (if using Office on the web): -

## Expected behavior

The add-in should retrieve data from an API and display it in the sheet. It's not very relevant, because the error has to do with how the add-in is initialized.

## Current behavior

This is a task pane add-in that is configured to open automatically when opening the excel file, as described here: https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document

Because of the sensitivity requirement, now when opening an Excel document, this warning appears:
![image](https://user-images.githubusercontent.com/968502/156548689-e1a27cbb-cb01-4364-aa8d-12135aefaa39.png)

If a debugger is attached, this error is shown in the console:

```js
Error: Uncaught (in promise): AccessDenied: You don't have sufficient permissions for this action.
RichApi.Error: You don't have sufficient permissions for this action.
    at new RuntimeError (appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.debug.js:10710:36)
    at RequestContext.ClientRequestContext.processRequestExecutorResponseMessage (appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.debug.js:13967:24)
    at appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.debug.js:13888:43
    at ZoneDelegate.invoke (:3000/polyfills.js:377:30)
    at Object.onInvoke (:3000/vendor.js:68991:33)
    at ZoneDelegate.invoke (:3000/polyfills.js:376:36)
    at Zone.run (:3000/polyfills.js:136:47)
    at :3000/polyfills.js:870:40
    at ZoneDelegate.invokeTask (:3000/polyfills.js:412:35)
    at Object.onInvokeTask (:3000/vendor.js:68969:33)
    at resolvePromise (:3000/polyfills.js:811:39)
    at :3000/polyfills.js:718:21
    at rejected (:3000/vendor.js:141247:89)
    at ZoneDelegate.invoke (:3000/polyfills.js:377:30)
    at Object.onInvoke (:3000/vendor.js:68991:33)
    at ZoneDelegate.invoke (:3000/polyfills.js:376:36)
    at Zone.run (:3000/polyfills.js:136:47)
    at :3000/polyfills.js:870:40
    at ZoneDelegate.invokeTask (:3000/polyfills.js:412:35)
    at Object.onInvokeTask (:3000/vendor.js:68969:33)
```

It looks like the issue it's because the add-in is configured to open automatically and it doesn't wait until the sensitivity label is selected.

I'm using `[Office.onReady]`(https://docs.microsoft.com/en-us/office/dev/add-ins/develop/initialize-add-in) to delay initialization of functionality until Office is ready. But even if I delay this initialization and select the Sensitivity label before, it still doesn't work.

Reloading the add-in doesn't solve it either.

The only way to make it work is to close the add-in and then load it again from the ribbon.

I'm using version 1.1 of office.js, but I also tried with the latest beta version

https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
https://appsforoffice.microsoft.com/lib/beta/hosted/office.js

Is there a different way to delay the opening or initialization of the add-in to wait until the Sensitivity label is selected?

## Steps to reproduce

1. Make sure that the user account used to log in with Office has Sensitivity requirements
2. Open the attached XLSX file: [SampleSensitivityIssue.xlsx](https://github.com/OfficeDev/office-js/files/8177307/SampleSensitivityIssue.xlsx)
3. The excel file will load the add in and display an `Unknown error` error message
4. If a debugger is attached, the Console tab will show the error from above (it will be slightly different because it uses the minified version of office.js)

## Useful logs

- [x] Console errors (see above)
- [x] Screenshots (see above)
- [x] Test file (attached above)

**Comment by SiruiSun-MSFT** [comment]
Hi Szilard,
Thanks for letting us know about this issue. We are trying to resolve this and will reply if there is progress.
Thanks, Microsoft 365 Developer Platform team

**Comment by RuizhiSunMS** [comment]
Hello @szilardd , thanks for reporting this issue. We have put this into our back log and will track it as an ADO item.
The update will be committed here as soon as it is fixed while we don't have an explicit timeline now.

**Comment by georgechr** [comment]
THis is causing serious issues for us. Is there an ETA on the fix?

**Comment by SiruiSun-MSFT** [comment]
Hi @szilardd and @georgechr, we have fixed the problem and the fix has been rolled out to the current channel, build version above 16.0.15215.10000. Thank you for your report!
