### ISSUE TITLE
Excel API 1.1 - React project

### ISSUE THREAD

**Issue by jeroenrosendaal** [OfficeDev/office-js#2460]
We are trying to create a Office add-in based on React but we are getting the error:
```
Line: 76
Error: Unable to get property 'length' of undefined or null reference
```
```
Unhandled exception at line 76, column 11005 in https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
0x800a138f - JavaScript runtime error: Unable to get property 'length' of undefined or null reference
```
<img width="403" alt="HH6xuR35rCzH" src="https://user-images.githubusercontent.com/37666832/156721793-00261902-0cbe-4e53-88b2-3a2bd868dc66.png">

## Your Environment
- Windows Server (version: 1809, OS build: 17763.2565)
- Excel API 1.1
- Office 2016 (16.0.5278.1000) 64-bit
 
## Expected behavior
A working default Office add-in

## Current behavior
Triggers the error:
```
Line: 76
Error: Unable to get property 'length' of undefined or null reference
```

## Steps to reproduce
1) yo office
2) Office Add-in Task Pane using React framework
3) Javascript

**Comment by R3D13** [comment]
I stumbled upon this issue as well while trying to make my React add-in run with IE11/Excel using IE11.

- Windows 10 Pro (version: 22H2, OS build: 19045.2193)
- Excel API version does not matter, tested from 1.1 to 1.8
- Office 2019 (16.0.10392.20029) 64bit

any news on this topic?

**Comment by Wujiao233** [comment]
Same problem here...
- Windows Server (version: 1809 build: 17763.4737)
- Excel API 1.1
- Office 2019 MSO (16.0.10401.20025) 64-bit

And if i use `office.debug.js` then error is at (877.25)

**Comment by Wujiao233** [comment]
FYI I turn to use `office.debug.js` locally and change the code in line 816 to this 
```
 if (promise && promise._subscribers && promise._subscribers.length !== 0) {
     lib$es6$promise$asap$$asap(lib$es6$promise$$internal$$publish, promise);
 }
```
and now it's seems working fine.
