### ISSUE TITLE
(Outlook requiredAttendees getAsync) : return attendees are inconsistent on Outlook for Mac and Windows 

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#2461]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Mac 
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 
   - PC desktop Version 2203 Build 16.0.15018.20002) 64-bit
   - Mac 16.58 (22021501)
* Operating System: Windows + Mac
 
## Expected behavior
- required attendees list should be consistent on Mac and Windows.

## Current behavior
Windows: returns the organizer

![requiredAttendees_windows](https://user-images.githubusercontent.com/13063615/156735689-fa0e74c8-b695-44e5-8d09-0565a89a3b24.PNG)

Mac: returns empty
<img width="1164" alt="requiredAttendees_Mac" src="https://user-images.githubusercontent.com/13063615/156735796-06ab231b-9820-4e75-9836-fdfdd858ca99.png">

## Steps to reproduce

1. New an appointment on outlook
2. Log out the result Office.context.mailbox.item.requiredAttendees.getAsync 
3. see the different results on Mac and Windows

## Link to live example(s)
https://gist.github.com/jasonhieu1905/cf7b1b6ebfd211ff1b3dead5cba2d838

**Comment by JuaneloJuanelo** [comment]
Hey @jasonhieu1905 one problem that we have here is that organizers are recognized differently on the actual products (in Windows there is no such thing as an organizer while in OWA and Mac there is such notion.   The API is mapping to what's supported on the products.   Can you please share how this is impacting your scenario?

**Comment by jasonhieu1905** [comment]
@JuaneloJuanelo : We have an outlook addin to insert the mail signature. We depends on the api mailbox item to return **recipientType** from **requiredAttendees, optionalAttendees**  to  define a signature is internal/external users. So when we create a new appointment by default, we get differently attendees between Windows and Mac so that the mail scope is currently not working correctly. Hope that helps.

**Comment by JuaneloJuanelo** [comment]
@jasonhieu1905 and how is this impacting your scenario exactly? the organizer/empty is always internal, right? or in what case is not?  Also, for additional safety, you can get the profile user to identify who is the sender. (by using Office.context.mailbox.userProfile.emailAddress)

Can you please confirm you are unblocked?

**Comment by jasonhieu1905** [comment]
@JuaneloJuanelo : We currently add the organizer to the check list, so I can confirm this is unblocked for now. Thanks.

**Comment by JuaneloJuanelo** [comment]
ok @jasonhieu1905  thanks for the confirmation.  At this point we dont visualize a problematic scenario here, so closing the case.
