### ISSUE TITLE
What is the release date for Office.Actions.replaceShortcuts(shortcuts) ?

### ISSUE THREAD

**Issue by puripats** [OfficeDev/office-js#2462]
What is the release date for Office.Actions.replaceShortcuts(shortcuts)  ?

https://docs.microsoft.com/en-us/javascript/api/office/office.actions?view=common-js-preview

For example,
replaceShortcuts(shortcuts)
This API is provided as a preview for developers and may change based on feedback that we receive. Do not use this API in a production environment.

When this actions will be in production environment?

**Comment by nkkinariwala** [comment]
@AbidRahman-MSFT - is this something you can help with?

**Comment by AbidRahman-MSFT** [comment]
Hey @puripats - we expect to release to production within the next month or two. The preview phase allows us to get feedback from developers to ensure the API is able to satisfy crucial user scenarios. If you have any feedback for us, please let us know!

**Comment by puripats** [comment]
> Hey @puripats - we expect to release to production within the next month or two. The preview phase allows us to get feedback from developers to ensure the API is able to satisfy crucial user scenarios. If you have any feedback for us, please let us know!

Good to hear that guys. Thanks.
