### ISSUE TITLE
Add-ins cannot be loaded in Microsoft Office Professional Plus 2019

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#2463]
(* Link on StackOverflow: https://stackoverflow.com/questions/71348197/add-ins-cannot-be-loaded-in-microsoft-office-professional-plus-2019 *)

Someone contacted me because he could not load our add-ins (using `ExcelApi 1.2`) in add-in stores; a blank page was shown. He could not use Advanced Formula Environment either, here is the error message:

[![enter image description here][1]][1]

Here is version information of his Excel:

[![enter image description here][2]][2]
 
[![enter image description here][3]][3]

And we do see [from this page](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets):

[![enter image description here][4]][4]

Several days ago, another user in China told me the same problem: he used also Professional Plus 2019, and he could not load any of these add-ins:

[![enter image description here][5]][5]

Could anyone advise?

  [1]: https://i.stack.imgur.com/H10IN.jpg
  [2]: https://i.stack.imgur.com/fMwf6.jpg
  [3]: https://i.stack.imgur.com/cXNbw.png
  [4]: https://i.stack.imgur.com/5wjIG.png
  [5]: https://i.stack.imgur.com/IcJfH.png

**Comment by davidchesnut** [comment]
Hi @chengtie,

Sorry for the late response on this issue. Let me loop in @ElizabethSamuel-MSFT to see if this is perhaps a doc issue or not.

Thanks,
David

**Comment by ElizabethSamuel-MSFT** [comment]
From what I can tell, the documentation is correct. Assigning to @guliums to investigate.

Thanks.

**Comment by guliums** [comment]
Hi @chengtie , Office 2019 are using IE11 webview as add-in runtime. I think that error message is from the code in your add-in. If you want your add-in work in Office 2019, you should provide an alternate experience that does not use any of the HTML5
features that are not supported in IE, and remove the check code like below code:

if (navigator.userAgent.indexOf("Trident") === -1) {

    // IE is not the browser. Provide a full-featured version of the add-in here.

} else {

    // IE is the browser. So here, do one of the following: 
    //  1. Provide an alternate experience that does not use any of the HTML5
    //     features that are not supported in IE.
    //  2. Enable the add-in to gracefully fail by putting a message in the UI that
    //     says something similar to: 
    //      "This add-in won't run in your version of Office. Please upgrade to 
    //      either one-time purchase Office 2021 or to a Microsoft 365 account."          

}

Please see more details in

https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

https://docs.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11

**Comment by chengtie** [comment]
> Hi @chengtie , Office 2019 are using IE11 webview as add-in runtime. I think that error message is from the code in your add-in. If you want your add-in work in Office 2019, you should provide an alternate experience that does not use any of the HTML5 features that are not supported in IE, and remove the check code like below code:
> 
> if (navigator.userAgent.indexOf("Trident") === -1) {
> 
> ```
> // IE is not the browser. Provide a full-featured version of the add-in here.
> ```
> 
> } else {
> 
> ```
> // IE is the browser. So here, do one of the following: 
> //  1. Provide an alternate experience that does not use any of the HTML5
> //     features that are not supported in IE.
> //  2. Enable the add-in to gracefully fail by putting a message in the UI that
> //     says something similar to: 
> //      "This add-in won't run in your version of Office. Please upgrade to 
> //      either one-time purchase Office 2021 or to a Microsoft 365 account."          
> ```
> 
> }
> 
> Please see more details in
> 
> https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins
> 
> https://docs.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11

You are right, IE is the issue, thank you all for the investigation.
