### ISSUE TITLE
Office.context.mailbox.item.organizer does not return recipientType

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#2466]
# Provide required information needed to triage your issue

## Your Environment

* Platform: PC & Online
* Host: Outlook
* Office version number: (Version 2202 Build 16.0.14931.20116) 64-bit 
* Operating System: Windows
* Browser: Chrome
 
## Expected behavior

getAsync should return Office.EmailAddressDetails object with recipientType according to [docu](https://docs.microsoft.com/en-us/javascript/api/outlook/office.organizer?view=outlook-js-1.11)

```
Office.context.mailbox.item.organizer.getAsync(function(asyncResult) {
    if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
      var apptOrganizer = asyncResult.value;
      console.log(apptOrganizer);
    } else {
      console.error(asyncResult.error);
    }
  });
```

## Current behavior
In the returned Office.EmailAddressDetails object the recipientType is always undefined.
`{
  emailAddress: "john.doe@mytenant.com", 
  displayName: "John Doe", 
  recipientType: undefined
}`

## Steps to reproduce
1. Create a new appointment
2. Run Script Lab with the "Get organizer (Appointment Organizer) snippet
3. Change the code to output the result object
4. See console for output

## Context
We insert a content in to the appointment based on the type of the organizer and attendees.

**Comment by JuaneloJuanelo** [comment]
Hey @barisbikmaz, are you reporting a documentation issue, or is there something that you are expecting to use in the properties? if you can clarify your scenario will be very helpful for us to prioritize this bug properly. thanks!

**Comment by barisbikmaz** [comment]
Hi @JuaneloJuanelo,
Scenario is: 
- Organizer creates a new appointment
- I check the recipientType of the appointment organizer
- Generate a signature based on his recipientType (external or internal)

Problem the recipientType property of the organizer is always undefined. Is this intentional or a bug?

**Comment by JuaneloJuanelo** [comment]
thanks for the additional detail @barisbikmaz.  I wonder if there is a special condition by which we assume the organizer is an "external" recipient.  should not we always assume is internal?  Curious to learn how this breaks your scenario.

**Comment by barisbikmaz** [comment]
Hi @JuaneloJuanelo,
currently it does not break our scenario if we can assume that the organizer is always internal, which he probably is, but we were not sure.
So we just wonder if the API returns undefined because the organizer is always internal, because there is no documentation about this behavior.

**Comment by JuaneloJuanelo** [comment]
I really don't see a good reason why you should consider the organizer of an appointment as an external recipient. In fact, we never return "ExternalUser" as recipientType, so I think for your scenario you could safely assume that's the case.  We will also make sure to document this properly. thanks for reporting this !
