### ISSUE TITLE
Ribbon Images Not Shown During Localhost Development Due To CORs

### ISSUE THREAD

**Issue by joshuawwright** [OfficeDev/office-js#2467]
Add-in icons on a custom ribbon are not shown when running from development (localhost), however the add-in works with no issues in the side-loaded panel. This is a recent development, that is being caused by a CORs issue.

![image](https://user-images.githubusercontent.com/1731346/157103098-e5f5b3bd-c89f-4015-8715-05d84aff8bcf.png)

## Your Environment
* Platform: Office on the web
* Host: Excel
* Office version number: N/A
* Operating System: Linux
* Browser: Google Chrome (Version 98.0.4758.102)
 
## Expected behavior
The icons should load the icons specified in the manifest.

## Current behavior
Currently, the add-in images are not shown. It appears there is a CORs issue. See log in useful logs section.

## Steps to reproduce
1. Create an excel add-in using the yo generator in the documentation and then run the app using the npm start:web script. You will notice that add-in button in the ribbon has an asset that is not loaded.

## Link to live example(s)
Reproduction requires localhost (see section above).

# Provide additional details
N/A

## Context
While developing an app I can no longer see the icons for the add-in buttons.

## Useful logs
Here one of the CORs error related to the image asset used for the button:
`Access to image at 'https://localhost:4201/assets/icons/update-80.png' from origin 'https://usc-excel.officeapps.live.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.`

An error is shown for each asset. So in my case I have 6 buttons and see 6 errors. If I open the image in new tab, the image shows as expected.

**Comment by nkkinariwala** [comment]
@grangeryy - Is it something you can help with?

**Comment by grangeryy** [comment]
@DesertFoxNV thank you for reporting the issue. We'll have an investigation and circle back soon:)

**Comment by joshuawwright** [comment]
Thanks! I was have a second developer who confirmed the behavior.

**Comment by grangeryy** [comment]
@DesertFoxNV, 

- it this issue stably reproduced for you?
- For another developer who saw the same behavior, does him/her using the same environment?

THX!

**Comment by joshuawwright** [comment]
@grangeryy 

> it this issue stably reproduced for you?

Yes

> For another developer who saw the same behavior, does him/her using the same environment?

We both use the latest Ubuntu LTS and use Google Chrome.

**Comment by grangeryy** [comment]
@mattgeim , is it something you can help with?

**Comment by igor-ribeiiro** [comment]
I didn't try on Linux, but I can confirm the icons are showing correctly in a Windows machine

**Comment by joshuawwright** [comment]
@igor-ribeiiro @grangeryy I was able to get the icons working on localhost. I uninstalled google chrome and all config files and was able to get it to work.

Thanks for looking into this. I should have tried uninstalling chrome first XD.
