### ISSUE TITLE
How to use Office.js Ribbon API for Customizing a Ribbon Through Size Definitions and Scaling Policies

### ISSUE THREAD

**Issue by gopinathshiva** [OfficeDev/office-js#2468]
In my project, I'm currently loading ribbons in Excel add-in using Office.js Ribbon API 

`Office.ribbon.requestCreateControls(Ribbon_JSON_HERE);`

I would like to know how to achieve customizing a ribbon's size definition and scaling policies via Ribbon API. I found a doc which can do this in manifest.xml way - https://docs.microsoft.com/en-us/windows/win32/windowsribbon/windowsribbon-templates . I need this ability to do this using Ribbon API.

Any help on this is really appreciated.

**Comment by davidchesnut** [comment]
Hi @gopinathshiva,

I apologize for the late response on your issue. @AbidRahman-MSFT can you help with this issue? If this isn't possible it would be great to add this as a feature request at https://aka.ms/m365dev-suggestions.

Thanks,
David

**Comment by AbidRahman-MSFT** [comment]
Hey @gopinathshiva - we currently do not support sizing and scaling policies via the Ribbon API. As David suggested, please log a feature request at https://aka.ms/m365dev-suggestions. 

Thanks,
Abid

**Comment by gopinathshiva** [comment]
Thanks for the info. Logged the ticket - https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/using-office-js-ribbon-api-for-customizing-a-ribbon-through-size/idi-p/3269731#M852
