### ISSUE TITLE
getAccessToken fails in Excel custom function

### ISSUE THREAD

**Issue by tj-aew** [OfficeDev/office-js#2469]
# Provide required information needed to triage your issue

I'm trying to use `getAccessToken` in an Excel custom function, like so:

```
/**
 * DEBUG: Get an access token.
 * @customfunction
 * @return {string} The token string.
 */
async function testGetToken(): Promise<string> {
    try {
        let token = await OfficeRuntime.auth.getAccessToken({
            allowSignInPrompt: true,
        });
        return `Worked: ${token}`;
    } catch (error) {
        console?.error(`Failed to get token:`, error);
        return `Error: ${error.message ?? String(error)}`;
    }
}
```

## Your Environment

* Platform: Desktop Excel, Excel for the Web
* Host: Excel
* Office version number: 2201 (14827.20198 Click-to-run)
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

Getting an access token, as we can in an add-in with a task pane.

### Shared Runtime

When the custom functions are set up to use the shared runtime, we get this error:

<pre>
Cannot read properties of undefined (reading 'getAccessTokenAsync')
</pre>

Note the "Async" on the end, whereas our code calls `OfficeRuntime.auth.getAccessToken`. So it's at least managing to call the function, but apparently internally that function is failing.

### Separate Runtime

When the custom functions are set up to use a separate runtime, we get this error from **Desktop** Excel:

<pre>
Cannot read properties of undefined (reading 'getAccessToken')
</pre>

...and indeed, if we look, `OfficeRuntime.auth` is undefined (`OfficeRuntime` is not).

But from **Excel for the Web**, we get the same error as the shared runtime:

<pre>
Cannot read properties of undefined (reading 'getAccessTokenAsync')
</pre>

Is this function not supported from custom functions? Or is there some precondition to using it?

Thanks.

**Comment by tj-aew** [comment]
I should have said: For the shared runtime, I was working within our current custom functions project, which was bootsrapped a couple of years ago and set up with the shared runtime.

To see if it worked when custom functions aren't using a shared runtime, I did `yo office` and created a custom functions add-in using TypeScript:

<pre>
C:\temp>yo office

     _-----_     ?--------------------------?
    |       |    ¦   Welcome to the Office  ¦
    |--(o)--|    ¦   Add-in generator, by   ¦
   `---------´   ¦ @OfficeDev! Let's create ¦
    ( _´U`_ )    ¦    a project together!   ¦
    /___A___\   /?--------------------------?
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

? Choose a project type:
  Office Add-in Task Pane project
  Office Add-in Task Pane project using Angular framework
  Office Add-in Task Pane project using React framework
  Office Add-in Task Pane project supporting single sign-on
  Office Add-in project containing the manifest only
> Excel Custom Functions Add-in project
? Choose a script type: (Use arrow keys)
> TypeScript
  JavaScript
? What do you want to name your add-in? temp-fns
</pre>

Then pasted in the function above, did `npm run build:dev` to build it, then `npm run start:desktop` to run it (geenrally takes two-three times before it successfully loads the functions). Then using the function gives me the errors described.

**Comment by tj-aew** [comment]
I scaffolded a new project from scratch (the one that was using shared runtime is about three years old) and something must be different in the manifest or build process because that freshly-scaffolded one works. So we'll migrate our code to the re-scaffolded project.

**Comment by jabbera** [comment]
I can't figure out why this is happening on mine and a fresh scaffold does not fix it. Did you ever figure it out?

**Comment by tj-aew** [comment]
@jabbera - Sadly, no. Since it worked with the fresh project, we didn't look into it further.
