### ISSUE TITLE
Word RequestContext does contain application createDocument Method

### ISSUE THREAD

**Issue by isawek** [OfficeDev/office-js#247]
Word API supports to create a new document from a base64 file since Version 1.3
https://docs.microsoft.com/en-us/javascript/office/requirement-sets/word-api-requirement-sets?view=office-js

this is not included in the npm office-js. 

## Expected Behavior
the following code snippet should open a new Word Document based on the base64File.

...
Word.run(async(context) => {
     let myNewDoc = context.application.createDocument(base64File);
     context.load(myNewDoc);
     ...
});

## Current Behavior
Property 'application' does not exist on type 'RequestContext'.
After replacing the content of the file '\node_modules\@types\office-js\index.d.ts' with the current version it works for me

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16
* Operating System: Windows 10

@Zlatkovsky , @kbrandl , @AlexJerabek , @ElizabethSamuel-MSFT

**Comment by Zlatkovsky** [comment]
Thanks for reporting.  We need to update the NPM package, it has gotten out-of-date relative to the CDN.  Will do this in the near future.  (We are working on a process to help automate this, so that we don't have to keep manually keeping up with the CDN deployments)

**Comment by Zlatkovsky** [comment]
I've just updated the NPM package.  Could you please try with the latest version?

**Comment by Zlatkovsky** [comment]
Closing the issue for now, feel free to reopen if you're still seeing a problem
