### ISSUE TITLE
Office.addin is undefined on outlook addin - can't install SharedRuntime on manifest

### ISSUE THREAD

**Issue by pietrofxq** [OfficeDev/office-js#2471]
I am trying to call the methods `Office.addin.showAsTaskpane()` and `Office.addin.hide()`. The object `Office.addin` is undefined inside my taskpane. I've read that I need SharedRuntime to make it work, but adding this on my manifest:

```
<Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="Mailbox" MinVersion="1.5"/>
      <Set Name="SharedRuntime" MinVersion="1.1"/>
    </Sets>
  </Requirements>
```

throws this error when installing the manifest: 

```
The Requirements element includes an unsupported Set 'SharedRuntime'.
```

What should I do to be able to use those methods to show/hide the taskpane from code?

**Comment by AbidRahman-MSFT** [comment]
Hey @pietrofxq, please note that shared runtime feature is only supported on Excel (and on PPT Web). Shared runtime is currently not supported on Outlook. I will assign this issue to the Outlook team to see if there are alternative ways to open/close the task pane in Outlook.

**Comment by pietrofxq** [comment]
Thanks! I found a workaround to hide the taskpane (which is what I need) by using

```
Office.context.ui.closeContainer()
```

However this makes the add-in stop working, so this method cannot be called while there is something going on (like an open popup). The workaround for that is to listen to events on the dialog, and call it if error 12006 is received (means dialog closed on X button)

**Comment by exextoc** [comment]
closeContainer() is basically the same as closing the taskpane manually. There is no way in Outlook to "hide" the taskpane and have it still be running in the background. 

What is your scenario? Would an ExecuteFunction add-in instead of ShowTaskpane be more appropriate if you do not want to show a taskpane?

**Comment by pietrofxq** [comment]
@exextoc I thought that this what SharedRuntime did, by reading this section of the docs:

```
Find the <VersionOverrides> section and add the following <Runtimes> section. The lifetime needs to be long so that your add-in code can run even when the task pane is closed. 
```

The use case is the following:
1. User clicks on add-in button in email
2. Taskpane opens and we show a screen "Validate event..." - this checks if the meeting was booked in our app
3. if meeting was booked in our app, we open a dialog to allow the user to reassign it. Here we dont need the taskpane anymore, but I can't close it until user is done with popup otherwise even closing it wont work
4. if meeting wasn't booked in our app we show a custom view in the taskpane.

But if SharedRuntime won't change that, then we still sticky with current workaround

**Comment by exextoc** [comment]
As Abid Mentioned, SharedRuntime is not supported in Outlook, so the unfortunately it doesn't apply. 

An ExecuteFunction ExtensionPoint would allow you to show the dialog (via https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins) ...but not the Taskpane. If you can do everything in DisplayDialogAsync you could see if you want to use that. 

If you want to use both the Dialog OR Taskpane dependent on the Item that is loaded, then your workaround will have to do. (there is no way to currently in outlook to hide the taskpane, and have it still be running)
