### ISSUE TITLE
Outlook add-in: Calling CustomProperties.saveAsync error when Encrypt/Digitally sign S/MIME options set

### ISSUE THREAD

**Issue by jlara005** [OfficeDev/office-js#2475]
If you have encrypt/sign options enabled on an email and try to save custom properties, you get an error.

## Your Environment
* Office on the web
* Outlook
* https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
* Windows 10 21H2
* Edge 99.0.1150.39
* S/MIME control: 4.0800.20.21.804.1
 
## Expected behavior
For the custom properties to get saved without error

## Current behavior
I am currently developing an add-in that saves custom properties before sending an email. Properties get saved successfully if I don't have the encrypt/digitally sign options set.

## Steps to reproduce
1. Open outlook web https://outlook.office.com/mail/
2. Create a new email
3. Go to message options
4. Set "encrypt this message (S/MIME)" and "digitally sign this message (S/MIME)"
5. Open add-in
6. Fire set CustomProperties.SaveAsync

## Useful logs
![image](https://user-images.githubusercontent.com/29823126/158186169-64bf9aae-a004-4f3f-9173-f2a6cd958b59.png)
![image](https://user-images.githubusercontent.com/29823126/158186450-fccdc845-ba3e-4bea-8aac-60e98dc9437a.png)
![image](https://user-images.githubusercontent.com/29823126/158191091-84860d11-725d-476b-86e5-aad0dc93fbb7.png)

{"Data":"The operation failed. Microsoft.Exchange.Clients.Smime.SmimeException: Exception of type 'Microsoft.Exchange.Clients.Smime.SmimeException' was thrown. ErrorCode: CannotGetSubjectCertFromStore\u000d\u000a   at Microsoft.Exchange.Clients.Smime.CertHelper.PickCert(ILogger logger, ICertStoreFactory storeFactory, KeyUsage keyUsage, SmimeControlSettings settings, String dialogMessage, Boolean canThrowException, DateTime now)\u000d\u000a   at Microsoft.Exchange.Clients.SmimeAX.InternalSign(EmailMessage msg, String signingCertificate, Boolean clearSign)\u000d\u000a   at Microsoft.Exchange.Clients.SmimeAX.CreateSmimeFromMessage(Int32 smimeType, String emailMessage, String encryptionCertificates, String signingCertificate)\u000d\u000a","ErrorCode":67}

**Comment by exextoc** [comment]
We are able to repro this bug. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Thank you for reporting the issue. We were trying to fix this bug but it is no longer repro for us. Can you please confirm if you are still facing this issue?

**Comment by chateaulav** [comment]
Recieving same error, when attempting to leverage smime through Outlook 365:

`
{"Data":"The operation failed. Microsoft.Exchange.Clients.Smime.SmimeException: Exception of type 'Microsoft.Exchange.Clients.Smime.SmimeException' was thrown. ErrorCode: CannotGetSubjectCertFromStore\u000d\u000a   at Microsoft.Exchange.Clients.Smime.CertHelper.PickCert(ILogger logger, ICertStoreFactory storeFactory, KeyUsage keyUsage, SmimeControlSettings settings, String dialogMessage, Boolean canThrowException, DateTime now)\u000d\u000a   at Microsoft.Exchange.Clients.SmimeAX.InternalSign(EmailMessage msg, String signingCertificate, Boolean clearSign)\u000d\u000a   at Microsoft.Exchange.Clients.SmimeAX.CreateSmimeFromMessage(Int32 smimeType, String emailMessage, String encryptionCertificates, String signingCertificate)\u000d\u000a","ErrorCode":67}
`
