### ISSUE TITLE
Office.context.document.url is returning empty string on word add ins load 

### ISSUE THREAD

**Issue by salmanansari-gep** [OfficeDev/office-js#2476]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# On opening a taskpane in word online, Office.context.document.url is returning empty string on load, it was working previously 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.15110.41003
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Office.context.document.url should return document full URL

## Current behavior
Our API call is breaking as we trying to read file details from document URL

## Steps to reproduce
1. Open Any Word document online
2. insert you word ins
3. click on on show taskpane
4. on load you will notice data is not loading

# Provide additional details
**Sample Code**

getFileID() {
    var name = "WOPISrc";

    var url = Office.context.document.url;
    name = name.replace(/[\[\]]/g, "\\$&");
    var regex = new RegExp("[?&]" + name + "(=([^&#]*)|&|#|$)"),
      results = regex.exec(url);
    if (!results) return null;
    if (!results[2]) return "";
    var myurl = decodeURIComponent(results[2].replace(/\+/g, " "));
    var finalobj: any = myurl.split("/");
    finalobj = finalobj[finalobj.length - 1]
    return finalobj;
  }

**Sreenshots**

![image](https://user-images.githubusercontent.com/40595974/158199799-27a3bcdf-3437-4d7f-9dd6-332d90e30529.png)

## Context
This is blocker for us hence stopping our business workflow

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by salmanansari-gep** [comment]
@grangeryy @AbidRahman-MSFT 
Do we have any update on this issue?

**Comment by xiruatms** [comment]
@salmanansari-gep , thanks for reaching out to us.

I've taken a try, but it seems working properly, I can't repro what you described.

Will you please help to provide more details? Are you still hitting this issue? Can you isolate the usage of Office.context.document.url outside your codes to confirm? If possible, can you have a screen record of your testing? All these information will help us to move forward to identify the issue.

**Comment by NataliaKravcheniaTR** [comment]
@xiruatms, it works in Sharepoint but it's not working in NetDocuments which has the WOPI integration

**Comment by salmanansari-gep** [comment]
@xiruatms Yes we have WOPI implementation and we are using office add-ins over there

**Comment by salmanansari-gep** [comment]
@xiruatms @grangeryy 

As this is blocking our business use case do we have any alternate way that we can point to any of the older version where this was working?

Any ETA when this will be fixed and available to us?

**Comment by AbidRahman-MSFT** [comment]
Hey @salmanansari-gep,

We did implement a change in behavior recently that may have impacted this scenario. I want to know more about your specific scenario to figure out if we can have alternative solutions here or if there is a bug we can fix. Can you please reach out to me on email (abid.rahman@microsoft.com) and provide some context on the following questions:

1. Do you own the WOPI server implementation? If so, are you manually setting the URL for these files that you are then fetching from inside the Office Add-in?
2. What information are you extracting from the file url? Let's figure out if its possible to get this info some other way.
3. Can you provide an example of what an expected file url is? 

Thanks,
Abid

**Comment by salmanansari-gep** [comment]
@AbidRahman-MSFT have shared the details on mail
