### ISSUE TITLE
Sideloading valid manifest in Excel Web generates invalid result

### ISSUE THREAD

**Issue by jasonclg** [OfficeDev/office-js#2477]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Your Environment

* Platform: Office on the web
* Host: Excel
* Office version number: Excel on the web latest
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome
 
## Expected behavior

The manifest was marked valid when running against validator locally
`npx office-addin-manifest validate manifest.xml`
It should be sideloaded successfully in Excel Web like in Excel Desktop.

## Current behavior

"Your add-in manifest is not valid" popped up.

## Steps to reproduce

Sideload the test manifest file in Excel Web

## Link to live example(s)

Test manifest file => https://gist.github.com/jasonclg/fa4bc51cdfd0ce82efbcb711aed06d45

# Additional details

1. if both buttons use **Taskpane.Url**, it's valid
2. if neither button uses **Taskpane.Url**, it's valid
3. if only one button uses **Taskpane.Url**, it's invalid (current code in gist)
4. DefaultValue of the Url doesn't impact the result. **Taskpane0.Url** can be used in the failure case above to pass the validation even if its value is the same as **Taskpane.Url**.

**Comment by AbidRahman-MSFT** [comment]
Hey @jasonclg,

Thank you for reporting this issue, looks like there is inconsistency between what is considered a valid manifest in Excel desktop vs Excel Web. I will add our developer experience team to follow up on the issue.
