### ISSUE TITLE
The open extension of the outlook meeting gets overwritten when saving it in the Outlook Desktop App

### ISSUE THREAD

**Issue by Manuri** [OfficeDev/office-js#2478]
I have an outlook add-in that allows the user to save some data to an open extension in the outlook event. 
The open extension data saved (By sending a PATCH request to the graph API) gets overwritten when saving the event (By pressing the "Send" button) in the Outlook Desktop App.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook desktop app
* Office version number: office-js 1.0.167
* Operating System: Windows 10 Home
* Browser (if using Office on the web): N/A
 
## Expected behavior
When the meeting invitation is sent (By pressing the "Send" button), the open extension data saved (By sending a PATCH request to the graph API) before that should persist.

## Current behavior
When the meeting invitation is sent (By pressing the "Send" button), the open extension data saved before that is overwritten.

## Steps to reproduce

1. Create a meeting in the Outlook add-in, add subject/invitees etc

2. Open the outlook add-in and follow the necessary steps that triggers a PATCH request that saves the open extension. After this when I fetch the event through the Graph API, I can see that the extension is saved.

3. Now press "Send". After this when I fetch the event again through the Graph API, I can see that the extension data is gone.
Please note that this only happens in the Outlook Desktop app and when creating a meeting (with invitees). This does not occur when saving an appointment (that doesn't have invitees)

**Comment by exextoc** [comment]
The issue you are observing may be related to inconsistent item state. Changes to an item via Graph/EWS/ REST (MakeEwsRequestAsync, or via a backend call), are updated directly in the exchange server. Changes made to an item using the Office.js API go to the client first and these changes, when using Outlook Desktop in Cached Mode,  are not synced to the exchange server immediately. Instead the server copy of the item gets updated when Outlook Desktop sync's with exchange. So an  item can get in an inconsistent state if it is updated using office.js and Graph/REST/EWS before Outlook client gets a chance to sync its state. And when the sync happens, sometimes, exchange resolves the conflict by overwriting the client copy so the client items changes can be lost. 
 
To avoid this problem, it is recommended that all changes to the same item be made either via REST/EWS/Graph or through the Office.Js API's. Mixing the two can result in conflicts. If this is not possible, then we have seen partners following the pattern of not making the changes via REST/EWS until they have detected the change that was made from the client. 
 
One approach to solve this would be
 
1.     Make the call CustomProperties, but also include a "timestamp" or GUID as part of the change.
2.     Send the call to a backend to make the EWS/Rest Call, along with the timestamp/GUID
3.     On the backend do not make changes to the item until that timestamp/GUID is there. 
 
We understand this is not ideal and we are trying to move as many server side API's to the Office.JS API suite as possible. Please help us understand your scenario, of what you are trying to accomplish via REST, EWS or Graph.

**Comment by Manuri** [comment]
@exextoc Apologies for the delayed response and thanks for the feedback!

I read a bit about custom properties and I think we can make use of it to fix our issue. 
However, I do have some questions about custom properties. 

**1.** I was able to successfully set custom properties in the add-in following [this](https://docs.microsoft.com/en-us/javascript/api/outlook/office.customproperties?view=outlook-js-preview) documentation.

But fetching these properties using the Graph API wasn't that straight-forward. I managed to get it to work with the following URL. 
```
https://graph.microsoft.com/v1.0/me/events/EVENT_ID?$expand=singleValueExtendedProperties($filter=id eq 'String {00020329-0000-0000-C000-000000000046}  Name cecp-ADDIN_ID_FROM_MANIFEST')
```

I don't fully understand what `00020329-0000-0000-C000-000000000046` is. It is one of the IDs from [here](https://docs.microsoft.com/en-us/office/client-developer/outlook/mapi/commonly-used-property-sets) and it has the name "PS_PUBLIC_STRINGS". 
Can you explain how these IDs work and why should I use this specific one to fetch the custom properties?

<br />

**2.** [This](https://docs.microsoft.com/en-us/graph/api/resources/extended-properties-overview?view=graph-rest-1.0) documentation says, 

>Use extended properties only if you need to access custom data for Outlook MAPI properties that are not already exposed in the [Microsoft Graph API metadata](https://docs.microsoft.com/en-us/graph/call-api#microsoft-graph-api-metadata)

This statement is not clear to me. Can you please give an example for this so that we can understand if it is right for us to use custom properties?

<br />

**3.** What are the risks of using custom properties?

**Comment by exextoc** [comment]
1) That should be fine for Custom Properties. They are named props that are stored under PS_PUBLIC_STRINGS. 

When you save custom properties via the JS API, it creates a JSON dictionary that is eventually saved to an Outlook MAPI property on that item.  with the name "cecp-[ADDIN-ID]". 

Then when the add-in is opened again, on Load, we read that JSON string from the property and expose it to the add-in via the JS APIs. 

2) Graph is essentially just accessing the raw property cecp-[ADDIN-ID]. It is ok to access the property in this manner. 

3) There are some dangers if you are accessing an item both via JS functions, and via Graph. Using the JS APIs means those changes will happen on client side. Accessing things via Graph, is accessing things on the server. (as I mentioned in my previous reply). Ideally you only make changes to the item via one method.

**Comment by Manuri** [comment]
@exextoc Thanks for the answers.

> That should be fine for Custom Properties. They are named props that are stored under PS_PUBLIC_STRINGS.

PS_PUBLIC_STRINGS: This does not mean that the properties are visible to the "public" (i.e. can be accessed without authorization), right?

**Comment by exextoc** [comment]
The outlook add-in API limits access to Custom Properties to ONLY the Add-in that creates them. However, since they are stored on the item, that means that if someone has access to the item, they can potentially access those properties via EWS, Extended MAPI,  Graph or REST. They should not be used to store sensitive information such as user credentials or security tokens.

**Comment by Manuri** [comment]
@exextoc We managed to make it work with custom properties. Thanks for the help. Will get back to you if we encounter any issues.
