### ISSUE TITLE
Bookmark end missplaced when insertOoxml with replace in a content control

### ISSUE THREAD

**Issue by cebrotea** [OfficeDev/office-js#2479]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2108 (Microsoft Word for Microsoft 365 MSO (16.0.14326.20850) 64 bit)
* Operating System: Windows 10 Pro 10.0.19044 Build 19044
* Browser (if using Office on the web): ______
 
## Expected behavior

The bookmark end should be placed correctly.

For this example: The bookmark end should be placed after the word "this"

## Current behavior

The bookmark end is misplaced.

For this example: The bookmark end is placed before the word "this"

## Steps to reproduce

1. Get the body content of the source.docx as Ooxml ( let sourceContent = context.document.body.getOoxml() )
2. Insert the content from step 1 in the contentcontrol in the main.docx using insert with replace ( contentControl.insertOoxml(content, Word.InsertLocation.replace); )
3. Check location of the endbookmark

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

We are trying to update parts of the document without compromising the integrity of that part.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 
[main.docx](https://github.com/OfficeDev/office-js/files/8252056/main.docx)
[source.docx](https://github.com/OfficeDev/office-js/files/8252057/source.docx)

**Comment by grangeryy** [comment]
@yihuax , not sure if you know anything on this issue?

**Comment by yihuax-msft** [comment]
I cannot find any issue.

The attached source.docx has one line of text as "This is a new text."
The attached main.docx has one line of text "This is a dummy text." inside a content control.

I get the the ooxml of the line in source.docx and put it into main.docx's content control, and it works correctly in that the content control now has text "This is a new text." in it. What is the problem?

By "the bookmark end" I think you meant the content control's end tag, right? The end tag should be at the location after the word "text.". How can it be placed after the word "this"? 

Please explain in more details. Thanks.

**Comment by cebrotea** [comment]
When I say bookmark end I mean the BookmarkEnd Element: **https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.wordprocessing.bookmarkend?view=openxml-2.8.1**

There is only one bookmark (the same) set on the word This in both word documents. Check the position of the BookmarkStart and BookmarkEnd before and after replacing the content control content with the updated text. After content is replaced in the content control, you will notice that the bookmark is misplaced.

**Comment by cebrotea** [comment]
@yihuax-msft  we're you able to reproduce it now ?

**Comment by yihuax-msft** [comment]
@cebrotea Thanks for the information. I didn't notice there was a bookmark there. Yes, I can repro it. Let me find some time to investigate.

**Comment by yihuax-msft** [comment]
@cebrotea Looks it is indeed an issue with our this API. But it should not block you, since on my machine the following workaround can put the bookmark at the correct location. The workaround is that, instead of calling
        contentControl.insertOoxml(content, "Replace");
you can call
        contentControl.getRange("Content").insertOoxml(content, "Replace");
Does it also work on your machine? Thanks!

**Comment by cebrotea** [comment]
@yihuax-msft  I tried to do this one on my machine and it didn't work. Am I doing it wrong ?

I attached a gist and the document I am using.

https://gist.github.com/cebrotea/7035766a1b7f581d889b008396ef608e
[test.docx](https://github.com/OfficeDev/office-js/files/8332088/test.docx)

**Comment by yihuax-msft** [comment]
@cebrotea, It is due to something wrong in your document.

Your document starts with the following characters:
1. Content control start tag
2. T
3. h
4. i
5. s
6. space
7. i
8. s
9. ......

In fact, the bookmark is placed on the first FIVE (5) characters!!!! That is, the bookmark is on "[startTag]This". Therefore, when you get the OOXML of "This is ...", the bookmark is not in the OOXML, since the range does not cover the bookmark's whole range.  Even you have inserted OOXML and replaced the content control content, the original bookmark is still there, hooked to the start-tag. 

So, there is no issue here. Everything is by design. You need to make sure the bookmark is not placed on the start tag. That is, make sure the bookmark is entirely in word "This" (4 characters, not 5 characters). You can turn on the ribbon's Developer tab, and click the Developer's "Design Mode" button to see the content control's start and end tags.

Thanks!

**Comment by yihuax-msft** [comment]
Your original issue should have the same cause.  Let me know whether it works without the workaround if you do not put the bookmark on the content control's start tag. Thanks.
