### ISSUE TITLE
Excel crashes when calling PivotHierarchyCollection.load() on an Analysis Services cube pivot table

### ISSUE THREAD

**Issue by chrismiller** [OfficeDev/office-js#248]
Using v1.8 of the office-js Excel API and latest Office Insider builds, Excel crashes and restarts when calling PivotHierarchyCollection.load() if the pivot table is pointing to a multidimensional Analysis Services cube. When the pivot table is just pointing to data within Excel, the code works as expected.

## Expected Behavior
The following should log the pivot table name and its hierarchies to the console:

Excel.run(async context => {
                const sheet = context.workbook.worksheets.getActiveWorksheet();
                sheet.load('pivotTables');
                await context.sync();
                var pivTabs = sheet.pivotTables;
                pivTabs.load('items');
                await context.sync();
                const pvtTab = pivTabs.items[0];
                const pvtHiers = pvtTab.hierarchies;
                pvtTab.load();
                pvtHiers.load('items');
                await context.sync();
                await console.log(pvtTab.name);
                await console.log(pvtHiers.items[0]);
});

## Current Behavior
Excel crashes and restarts

## Steps to Reproduce, or Live Example
  1. Create a pivot table in Excel that is pointing to a multidimensional Analysis Services cube (I believe any cube will do. Make sure it is multidimensional though. I haven't yet tried with a tabular cube).
  2. Try to access the pivot table hierarchies via an Excel add-in using office-js ExcelApi 1.8, using code similar to the above.
  3. Excel will crash when the pvtHiers.load('items'); code is run

## Context
Our users use Excel pivot tables to explore multidimensional Analysis Services cubes. We need to create an Excel add-in with office-js that allows users to right-click on a pivot table cell and retrieve additional information related to that cell, displaying the retrieved results in a task pane. To do this we need to figure out what dimension(s) and measures the cell corresponds to.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Excel 1810 build 10910.20007
* Operating System: Windows 10 Pro 10.0.17134 build 17134
* SQL Server Analysis Services 13.0.4522.0

## Useful logs
Excel crashes completely. If you can point me at any logs I will add them here.

**Comment by Zlatkovsky** [comment]
Thanks for reporting the crash!  I have passed it along to a colleague who will be investigating this further, and will get back to you with any questions/updates.

**Comment by JuaneloJuanelo** [comment]
The update here is that the first release of Pivot Table API will not support Cubes. in further releases this will be included. (we'll fix a bug to not crash Excel)

**Comment by chrismiller** [comment]
That's unfortunate but thanks for letting me know. Is cube support scheduled v1.9 or has that not been decided yet?

**Comment by JuaneloJuanelo** [comment]
Yes I know. The fix is in and backported to many builds back. When cubes are supported , it will just work.
