### ISSUE TITLE
Urgent: How to get Office version which uses IE11 

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/office-js#2481]
I desperately need a way to test my addin on an installation that uses Office running IE11. I am no longer able to load word online in IE11 (no longer supported) 
![image](https://user-images.githubusercontent.com/6726111/158553484-6fc56361-e6e9-4ec7-8794-2c70fbc3ca9d.png)
and therefore I need a way to test if my addin works on older Office versions that use the IE11 browser for running addins. According to this page: https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins Office 2016 and office 2019 use IE11. Therefore I uninstalled Office 365 on my computer (using the Microsoft cleanup/uninstall tool https://aka.ms/SaRA-officeUninstallFromPC) -> bought an Office 2019 license -> and installed it. 

Problem is that when I start Word, open the add-in and go to "security info" I see that my Word installation uses Edge and not IE11
![image](https://user-images.githubusercontent.com/6726111/158555099-be8106de-8705-4fff-87c4-48d3be258054.png)

Can you please help with instructions on how to get a version of Office that uses IE11? I desperately need this. If I cannot test the addin in an office version that uses IE11 I cannot deploy updates to our product.

**Comment by croicu** [comment]
Jens, I think you can use Office 2016 or use a version of windows 10 prior to 19H1 (version 1903) or windows 8.1. We are always use Edge on newer windows versions.

**Comment by Rick-Kirkham** [comment]
@JensMadsen Have you seen this article? 
[Testing on IE 11](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/ie-11-testing)

**Comment by JensMadsen** [comment]
@Rick-Kirkham I know about this page but I did not check for the latest updates!! Thank you. The section https://docs.microsoft.com/en-us/office/dev/add-ins/testing/ie-11-testing#install-a-version-of-office-that-uses-internet-explorer kind of works. So thats perfect!. Still the `npx office-addin-dev-settings webview <path-to-manifest> <webview>` does not work (never did which is why I have tried other means :-)). 

The office-addin-settings command states that "The web view type is set to Microsoft Internet Explorer." but the runtime is still Edge. I have tried many ways to make this work (new manifest, clear cache etc.)

**Comment by ndeeH** [comment]
@Rick-Kirkham The npx command does not work to switch testing to use IE. Testing in IE mode in Edge is not an option because:
![image](https://user-images.githubusercontent.com/11518242/170074015-ca75522e-54d2-431b-a476-cf36092e0a7a.png)
So I hope MS will hardly replace IE by an Update in all MSI Office Versions. Do not love to have untested Add Ins around because of your IE retirement.
