### ISSUE TITLE
Custom function return type as any does not accept any value to be returned

### ISSUE THREAD

**Issue by sheldoncoates** [OfficeDev/office-js#2486]
When specifying the return type of a custom function as `{any}` I want the custom function to be able to return a `string, number, string[][], ect.` but with a return type as `{any}` I can't return a `string[][]` because it results in a `#VALUE!` error.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 16.59 (22031300)
* Operating System: macOS Monterey version 12.3 
* Browser (if using Office on the web): Chrome (latest)
 
## Expected behavior
I would expect an `any` type to accept any type to be returned such as `string, number, string[][], ect.`

## Current behavior
Currently the custom function will resolve to a `#VALUE!` error

## Steps to reproduce
1. Create a custom function with return type as `{any}`
2. Return a `string[][]` as shown on this example page where they return apple, oranges, pears: [link](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-dynamic-arrays)
3. observe a `#VALUE!` error

## Context
We are trying to add the ability for users to use a custom function to fetch singular values: `string, number` and also a list of values: `string[][]`

**Comment by davidchesnut** [comment]
Hi @sheldoncoates 

The simple way to return single values in addition to arrays is to just return an array with a single value as follows:

```js
/**
 * Get text values that spill both right and down.
 * @customfunction
 * @returns {string[][]} A dynamic array with multiple results.
 */
function spillRectangle() {
  return [['apples']];
}
```

The `string[][]` syntax is important because it adds the dimensionality value to the functions.json. Without that Excel won't realize the function supports arrays.

```json
 "functions": [
        {
            "description": "Get text values that spill both right and down.",
            "id": "SPILLRECTANGLE",
            "name": "SPILLRECTANGLE",
            "parameters": [],
            "result": {
                "dimensionality": "matrix",
                "type": "string"
            }
        },
```

You can change it to `any[][]` which will remove the "type": "string" and then you truly are returning single numbers, strings, or even arrays if your function needs to.

```js
/**
 * Get text values that spill both right and down.
 * @customfunction
 * @returns {any[][]} A dynamic array with multiple results.
 */
 function spillRectangle() {
  return [[5]];
}
```

Hope this helps!
David

**Comment by sheldoncoates** [comment]
Thank you @davidchesnut this resolved the issue.
