### ISSUE TITLE
Office.addin is undefined

### ISSUE THREAD

**Issue by tj-aew** [OfficeDev/office-js#2489]
# Provide required information needed to triage your issue

`Office.addin` is `undefined`.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop, Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2202 Build 16.0.14931.20128) 64-bit 
* Operating System: Windows
* Browser (if using Office on the web): Chrome, Edge
 
## Expected behavior

`Office.addin` should be an object with a `showAsTaskpane` function as documented [here](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/show-hide-add-in).

## Current behavior

`Office.addin` is `undefined` instad.

## Steps to reproduce

1. Create a custom functions add-in
2. Follow the steps [here]() to enable the shared runtime
3. Try to use `Office.addin.showAsTaskpane()` in a function

**Comment by tj-aew** [comment]
Actually, if I try to scaffold an entirely new project, switching it to the shared runtime makes it just completely fail to load the functions. The `undefined` issue above is with an existing project already configured to use the shared runtime (and double-checked).

**Comment by tj-aew** [comment]
If I scaffold an entirely new project, apply the shared runtime steps, and try to use it, it works. So I guess it must be something about our existing project which we'd already moved to the shared runtime, though I can't imagine what it would be. Any suggestions what to look at in the manifest or build?

**Comment by davidchesnut** [comment]
Hi @tj-aew,

It sounds like the shared runtime isn't loading. I'd double check the manifest. Can you compare your manifest against the sample manifest that you got to work? In particular I'd double check the location of the `<Requirements>` and `<Runtimes>` elements. They have to exactly match the order defined in [Configure your Office Add-in to use a shared JavaScript runtime](https://docs.microsoft.com/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime). 

Thanks!
David
