### ISSUE TITLE
Confirm popup in Office Online does not stop propagation of click event

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#249]
When you open a dialog on Office Online you get a confirm popup. Here you can click ok to open the office dialog. The problem here is that the click on the ok or cancel button in the confirm popup is propagated to the underlying app and changes the UI if there are some elements listening for a click event.

## Expected Behavior
The click on confim popup should not be propagated to the document / app;

## Current Behavior
As an example we have a UI Fabric pane in our addin which closes when the user clicks outside the pane.
Now the users opens the pane and click sth which opens an office dialog. This opens the confirm popip on Office Online. When the user now clicks ok in the popup our pane in the addin gets closed. This is not what the user expects. Also when you design components which live in that pane, the listener for the dialog gets killed.

## Steps to Reproduce, or Live Example
Here [https://github.com/hxltinh/office-js-bug-reproduction](https://github.com/hxltinh/office-js-bug-reproduction)
is a little example which displays a message on the app when user clicks sth. Notice that the message is also displayed when user opens the confirm popup and clicks a button there.

## Context
In our addin a user can start an authentication from a pane. On Office Online the user has no chance to connect now as the confirm popup closes the pane and kills the listener for the dialog result.

## Your Environment
* Platform : Office Online
* Host : Word
* Browser: Chrome, IE 11, Edge

**Comment by JuaneloJuanelo** [comment]
Thanks for reporting we are investigating this issue.

**Comment by danielgwilson** [comment]
Hey @barisbikmaz, we're still looking into this - in the meantime, however, there's a potential workaround.

See the Dialog API docs section on handling popup blockers:
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins

The allow popup prompt in online is now optional; by passing the optional parameter `promptBeforeOpen=false`, you can suppress the allow prompt. That does mean you **must** trigger the dialog via a button in the TaskPane, but this may help you to avoid clicks propagating incorrectly.
