### ISSUE TITLE
Outlook for Mac not handling adding/removing attachments properly

### ISSUE THREAD

**Issue by hiddenkirby** [OfficeDev/office-js#2490]
# Provide required information needed to triage your issue
Use scriptlab on Outlook for Mac version 16.59 (22031300)
Open a compose window
Run this gist in script lab https://gist.github.com/hiddenkirby/6bed684bac672bbca6613351c7f307e5

Notice only one attachment present when API returned two AsyncResult.success calls.  I am seeing this issue with removeAttachmentAsync as well. This seems to have appeared after a recent Outlook for Mac update. 

The same code does not have an issue in any Web Outlook or Windows Outlook Client

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.59 (22031300)
* Operating System: OSX 12.0.1 Monterey
* Browser (if using Office on the web): N/A
 
## Expected behavior

I would expect to see two attachments created, listed in the console, and then file1.png to be removed after clicking "RUN" in that script lab example.

## Current behavior

Instead, I am not seeing attachments being added or removed properly even if the API returns an asyncResult.success

## Steps to reproduce

1. Use scriptlab on Outlook for Mac version 16.59 (22031300)
2. Open a compose window
3. Click "RUN" this gist in script lab https://gist.github.com/hiddenkirby/6bed684bac672bbca6613351c7f307e5
4. Notice there are not two attachments.

## Link to live example(s)

1. Use scriptlab on Outlook for Mac version 16.59 (22031300)
2. Open a compose window
3. Click "RUN" this gist in script lab https://gist.github.com/hiddenkirby/6bed684bac672bbca6613351c7f307e5
4. Notice there are not two attachments.

## Context

https://appsource.microsoft.com/en-us/product/office/WA200003007?src=office&tab=Overview
Our live add-in is not working correctly for Mac Clients and affecting our customers. Sometimes attachments do not properly add or delete.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by davidchesnut** [comment]
Thanks for reaching out @hiddenkirby. @exextoc can you help with this issue?

Thanks!
David

**Comment by exextoc** [comment]
@hiddenkirby I have tested the Script Lab on Outlook Mac, Web, and Windows. In all three places, I could see only 1 attachment after I ran the code. So for me, the behavior was identical. Could you please elaborate on the issue as to what is your expectation here?

**Comment by hiddenkirby** [comment]
The code should:
1. Add a file named file1.png
2. Add another file named file2.png
3. log both files to the console
4. remove file1.png

Instead, you only saw 1 attachment after you ran the code. And when you see the console log you only see 1 attachment. And since the length of the attachments array was not 2, it did not try to remove file1.png.  #1 and #2 return asyncResult.success from the API yet there are not 2 attachments.

**Comment by exextoc** [comment]
With the code snippet you provided, the same behavior is observed on all 3 platforms (Windows, Web, and Mac). Could you please recheck the code and see if there could be any potential bug in the code?

**Comment by hiddenkirby** [comment]
Hrm, this is definitely an intermittent issue.

I am working on a new script that might help bring this to light.

**Comment by hiddenkirby** [comment]
I have created a new script. https://gist.github.com/hiddenkirby/49e58ec35716c4d48189e75ede4b6d8b

This helps get closer to replicating the issue, but it does not occur every time.

If you click the "run" button multiple times, occasionally the Outlook interface is missing expected attachments.

As an example:
1. open a compose window
2. import the above script/gist.
3. clicking the "run" button three times should show exactly "file-4.png", "file-5.png", and "file-6.png". 

This has never failed for me on Web or Windows.
![image](https://user-images.githubusercontent.com/296667/160863208-c5a33318-a3b0-4119-acef-b39f38d80644.png)

However occasionally on Outlook for Mac, I will be missing attachments like so...
<img width="1031" alt="Screen Shot 2022-03-30 at 10 48 32 AM" src="https://user-images.githubusercontent.com/296667/160863497-ba22ec23-f25c-4056-867a-4280d415e0f7.png">

The console output for the above issue is as follows:
```
Created Attachment:
file-1.png
12CB29BE-90F0-4C13-BFCF-6C01B2243F44
Created Attachment:
file-2.png
C5BE1159-FFB6-48CF-BB2D-12989E82E6C7
list of attachments: 
▶[Object, Object]
Lets remove attachment at index 0: 
file-1.png
Attachment removed successfully.
Created Attachment:
file-3.png
F39124AF-28D4-41C6-AAE1-787FB433AEBC
Created Attachment:
file-4.png
5C8264EC-6DB1-41B5-B73E-277596914F20
list of attachments: 
▶[Object, Object, Object]
Lets remove attachment at index 0: 
file-2.png
Attachment removed successfully.
Created Attachment:
file-5.png
DCD3D241-A0AB-476F-8ED7-347F54F4248C
Created Attachment:
file-6.png
1B5F516D-A4D3-4183-826F-3692931869C4
**list of attachments: 
▶[Object, Object]**
Lets remove attachment at index 0: 
file-5.png
Attachment removed successfully.
```

I believe there is some sort of [new] disconnect between the UI and the asynchronous responses. Both when the script runs correctly or fails the console log output shows the same output.

I have seen the issue occur anywhere between 3 10 clicks of the "run" button. This seems like some sort of timing issue with the async calls in the API.

**Comment by exextoc** [comment]
@hiddenkirby Thanks for reporting this issue. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

**Comment by hiddenkirby** [comment]
Thank you.  This is a big deal for our Mac users.

**Comment by exextoc** [comment]
The product bug is resolved as we are not able to reproduce the issue at our end.

**Comment by mebbert** [comment]
This is definitely a real bug. I regularly drop attachments to an Outlook email (Mac OS Montery 12.6; Outlook 16.67) and the attachments will disappear, reappear, and disappear again. Sometimes it's just some of the attachments that disappear. As @hiddenkirby said, it's intermittent.

**Comment by davidchesnut** [comment]
Hi @mebbert, just curious when you reproduce this issue do you wait for Run to finish before clicking it again? Or do you have to click it repeatedly? I ask because if you await in JS, the await frees the thread to work on other events (button click). Which means you can have a second or third instance of the button event running before the first one is finished. Also I wasn't sure if that's the same scenario your users are encountering. If they are pressing the button repeatedly, and this is indeed what causes the behavior, you can disable the button at the beginning of the run event, then enable it when the attachment work is complete.
```javascript
async function run() {
  $("#run").prop("disabled", true);
  // add a test file as attachment
  if (await createBase64Attachment(`file-${attachmentCount}.png`, testBase64String)) {
    // add another test file as an attachment
    if (await createBase64Attachment(`file-${attachmentCount}.png`, testBase64String)) {
      // get list of attachments
      const allAttachments = await getAllAttachments(false);
      console.log("list of attachments: ", allAttachments);
      // remove first file attachment
      console.log("Lets remove attachment at index 0: ", allAttachments[0].name);
      remove(allAttachments[0].id);
    }
  }
  $("#run").prop("disabled", false);
}
```

**Comment by mebbert** [comment]
Looks like I misunderstood the nature of your post. 

I thought your .js code was testing the same event of dragging and dropping attachments into an email. I'm not writing plugins for end users. I'm just experiencing the same thing you describe as a "lay" end user whose attachments disappear intermittently.
