### ISSUE TITLE
How to use the ChartBinOptions class to change the bin with and count on a Histogram

### ISSUE THREAD

**Issue by EdwinStraver** [OfficeDev/office-js#2491]
I have written some very simple code to create a Histogram, like so:

await Excel.run(async (context) => {
    let sheet = context.workbook.worksheets.getItem("Sample");
    let dataRange = sheet.getRange("A1:A50");
    let chart = sheet.charts.add(
      Excel.ChartType.histogram, 
      dataRange, 
      Excel.ChartSeriesBy.auto);
    await context.sync();
});

Now, I simply want to use/access the ChartBinOptions to change the number of bins used in the ChartBinOptions, as described in 
https://docs.microsoft.com/en-us/javascript/api/excel/excel.chartbinoptions?view=excel-js-preview

But I can not figure out how to use this class.

Any help would be appreciated.

Edwin

**Comment by donlvMSFT** [comment]
Hi @EdwinStraver , thanks for reaching us. 

You could refer to the Chart Format -> Horizontal Axis -> Axis Options to see the Bins options. When type is "Bin width" you could set the width, and when type is "Number of bins" you could set the count.

So the code could be like below, please mention you need to set the right type before set other properties:

```javascript
await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    let crt = sheet.charts.getItemAt(0);
    let series = crt.series.getItemAt(0);
    let bins = series.binOptions;
    // set bins width
    bins.type = Excel.ChartBinType.binWidth;
    bins.width = 3;
    // set bins conut
    bins.type = Excel.ChartBinType.binCount;
    bins.count = 5;
    await context.sync();
    console.log(series.binOptions.toJSON())
});
```

**Comment by EdwinStraver** [comment]
Thank you!!
