### ISSUE TITLE
[Outlook] API call slowly in outlook for mac

### ISSUE THREAD

**Issue by Howard-Song** [OfficeDev/office-js#2492]
## Issue

outlook for mac version: 16.59(22031300)

License: Microsoft 365 Subscription

Office-js version: 2.3.0(https://appsforoffice.microsoft.com/lib/1/hosted/Office.js)

In our addin, we add a setInterval to call **window.Office.context.mailbox.item.body.getAsync, window.Office.context.mailbox.item.to.getAsync, window.Office.context.mailbox.item.cc.getAsync, window.Office.context.mailbox.item.bcc.getAsync** in 300ms once. It worked well in outlook for web(Chrome, FireFox, Safari, IE) and outlook for windows(version:2019). but in outlook for mac in **New outlook**, these API call doesn't respond quickly so this will cause the performance issues. 
![image](https://user-images.githubusercontent.com/28775661/159883169-2cf41245-c689-40fb-a8bf-513bd7cd13fa.png)

I find a document to describe that **Office supports no more than 50 batch jobs in the queue**, and in our addin the error "wait for previous api complete" is just show when the unfinished api count reaches 50.

So can someone help me to check what is different in Offce-js from **New outlook to old version** in Office365?

PS: use uncheck to switch new outlook into old version
![image](https://user-images.githubusercontent.com/28775661/159882133-818bb188-d112-46df-ae0b-642e28266941.png)

**Comment by davidchesnut** [comment]
Hey @exextoc team can you please take a look at this issue? Thanks!

**Comment by exextoc** [comment]
Thanks for reaching out. Can you please share your code snippets, so that we can try to repro at our end and debug better?

**Comment by exextoc** [comment]
@JesseHeisenberg Can you please share your code-snippets used for performance testing? We would like to use same scripts so that we can repro this performance problem inhouse. Thanks.
