### ISSUE TITLE
We use Office-Add-in with Window10 with Office 365 2202 32bit It is run on IE11 is this expecting?

### ISSUE THREAD

**Issue by puripats** [OfficeDev/office-js#2493]
# Provide required information needed to triage your issue
We use Office-Add-in with Window10 with Office 365 2202 32bit It is run on IE11 is this expecting?
As we investigated, our version should run on Microsoft Edge1 with WebView2 (Chromium-based) however, as I seen it's used IE11 to run on it so we need to confirm is this expected? and if it is, Is there a plan to move to use Edge WebView2?
https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/concepts/browsers-used-by-office-web-add-ins.md

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2202 build 16.0.14931.20118
* Operating System: Window10 19044.1586
* Browser (if using Office on the web): 
 
## Expected behavior
Office add-in used edge WebView2.

## Current behavior
Office add-in used edge IE11.

## Steps to reproduce
run Microsoft add-in in 32 bit version.

**Comment by davidchesnut** [comment]
Hi @puripats,

You are correct that it should be using Edge WebView2. How are you confirming which webview is loaded? We recommend using the personality menu when your add-in is loaded in the task pane.
![image](https://user-images.githubusercontent.com/8559338/159998099-ec238d7a-d34d-4a97-b908-f6a80b221d5e.png)

Then choose **security info**, and you should get a dialog like the following:

![image](https://user-images.githubusercontent.com/8559338/159998400-5104561f-b15d-409a-9f0e-671944d2fe8f.png)

It would help to confirm if you are seeing a different runtime value in this dialog.

Thanks!
David

**Comment by puripats** [comment]
@davidchesnut Thanks David for confirmation, as I checked with team. I found out that only 1 pc that point to IE11 somehow. I don't know why yet but I am clear now that it's should be Edge WebView.

**Comment by davidchesnut** [comment]
Hi @puripats, 

Just for more info you can switch the WebView that Office uses. See [Test your Office Add-in on Internet Explorer 11](https://docs.microsoft.com/office/dev/add-ins/testing/ie-11-testing#switch-to-the-internet-explorer-11-webview) for more info.
