### ISSUE TITLE
Problem with Data Horizontal Classification

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#2494]
# Provide required information needed to triage your issue
I have been doing some tests with sorting the data in the Excel Online environment and saw a problem with the action recorder. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel Online
* Office version number: Build 16.0.15122.37951
* Operating System: Win 10
* Browser (if using Office on the web): Chrome
 
## Expected behavior

The data should be sorted horizontally, as recorded in the script.

## Current behavior

When running the horizontal data sorting in row 1 via the application, everything works perfectly but when it comes time to save the process action, the execution of the saved script fails. The sorting is not done.
This is due to the missing direction parameter in the generated code. 

## Steps to reproduce

Original code:
	selectedSheet.getRange("A1:F1").getSort().apply([{key: 0, ascending: true}], false, false);

Adapted Code:
	 selectedSheet.getRange("A1:F1").getSort().apply([{key: 0, ascending: true }], false, false, ExcelScript.SortOrientation.columns );

## Link to live example(s)

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
- [x] No console Errors

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by davidchesnut** [comment]
Hi @aletrovato, thanks for letting us know about this!

@peronald can you help with this issue?

Thanks!
David

**Comment by peronald** [comment]
Hi @aletrovato. Thanks for reporting this issue. It has been put on our backlog to be fixed, but we don't have a timeline to share at this time.

**Comment by ghost** [comment]
Thank you @peronald for your attention

**Comment by peronald** [comment]
Hey @nancy-wang can you follow up on this issue? Thanks!

**Comment by nancy-wang** [comment]
Hi @aletrovato,

Apologies for the late reply - shared your feedback with the team a while back and it seems I forgot to follow up here. We recently fixed this issue, so you should be able to see the correct behavior reflected in your script if you test it sometime next week. Please let us know if you continue to have issues or have other questions regarding scripting, and happy holidays!

Warmly,
Nancy

**Comment by ghost** [comment]
Nancy, hi!

 

Thank you for your help. 

Have a great holidays!

 

My best!

 

 


 <https://mvp.microsoft.com/pt-br/PublicProfile/5003195?fullName=Alessandro%20Trovato> 

 

 <https://www.linkedin.com/in/alessandrotrovato/> 

Alessandro Trovato

Microsoft MVP / Instrutor LinkedIn Learning

 

Blog, Catálogo das Aulas e cursos <https://linktr.ee/alessandrotrovato> 

 <http://www.youtube.com/aletrovato> +1.100 vídeo aulas no Youtube

 <https://bit.ly/apptrovato> App gratuito na Play Store

 

Compartilhando conhecimento, sempre!

 

 

De: Nancy Wang ***@***.***> 
Enviada em: sexta-feira, 16 de dezembro de 2022 21:04
Para: OfficeDev/office-js ***@***.***>
Cc: aletrovato ***@***.***>; Mention ***@***.***>
Assunto: Re: [OfficeDev/office-js] Problem with Data Horizontal Classification (Issue #2494)

 

Hi @aletrovato <https://github.com/aletrovato> ,

Apologies for the late reply - shared your feedback with the team a while back and it seems I forgot to follow up here. We recently fixed this issue, so you should be able to see the correct behavior reflected in your script if you test it sometime next week. Please let us know if you continue to have issues or have other questions regarding scripting, and happy holidays!

Warmly,
Nancy
