### ISSUE TITLE
[Outlook for Mac] Office.context.mailbox.ewsUrl property provides empty string

### ISSUE THREAD

**Issue by yurabandura** [OfficeDev/office-js#2495]
# Empty mailbox.ewsUrl property on Outlook for Mac with Microsoft Exchange account

## Your Environment

* Platform: Mac
* Host : Outlook for Mac
* Office version number: 16.59
* Operating System: macOS Catalyna 10.15.3
* Browser (if using Office on the web): Chrome 87.0.4280.88
 
## Expected behavior
`ewsUrl` to provide valid url like `'https://east.exch091.serverdata.net/EWS/Exchange.asmx'`

## Current behavior
Currently `Office.context.mailbox.ewsUrl ` provides empty string

## Steps to reproduce
Read `ewsUrl` of `Office.context.mailbox` in Office Addin taskpane on Outlook for Mac with Microsoft Exchange account.
Permission level - `ReadWriteMailbox`.
Mode: `Read`.

# Additional details
`ewsUrl` is correct when using same Microsoft Exchange account on Windows desktop Outlook client or on OWA
`ewsUrl` also correct on Outlook for Mac when using Microsoft Account or Exchange/ Office 365 Account

**Comment by exextoc** [comment]
If it is a consistent repro with you, then could you please collect the diagnostics and share the diagnostics ID with us?
Steps to collect the diagnostics.

Click on Help->Collect Diagnostics.
Click OK on the Pop-up.
Copy the diagnostic ID from the next Pop-up and provide us with the same.

**Comment by yurabandura** [comment]
> If it is a consistent repro with you, then could you please collect the diagnostics and share the diagnostics ID with us? Steps to collect the diagnostics.
> 
> Click on Help->Collect Diagnostics. Click OK on the Pop-up. Copy the diagnostic ID from the next Pop-up and provide us with the same.

Diagnostic ID is GW57CZMC

**Comment by exextoc** [comment]
@yurabandura From the logs, it looks like you are using old UI. Can you please switch to the new UI and let us know if you are facing the issue?

**Comment by yurabandura** [comment]
@exextoc New UI does not support adding Microsoft Exchange accounts. It is under Coming Soon section.

**Comment by exextoc** [comment]
Thanks, @yurabandura. We believe that you are using an onPremise account. 

1. Are you able to repro it consistently?
2. Can you please share a test account configured with the steps that you have mentioned so that we can repro it at our end and debug it better?
Please share the test creds to OutlookAddins@M365x693897.onmicrosoft.com
