### ISSUE TITLE
[Outlook for Mac] Allow inserting <style> tag

### ISSUE THREAD

**Issue by pietrofxq** [OfficeDev/office-js#2496]
Our add-in inserts a React component with

```
Office.context.mailbox.item.body.setSelectedDataAsync(html, { coercionType: Office.CoercionType.Html })
```

We changed the component to use styled components instead of having all the styles inline. This works fine everywhere (office web, office desktop for windows) except for Outlook for mac. I tried manually inserting <style> tags and it doesn't take any effect. We would expect the behaviour to stay consistent across the different outlook apps, but this is preventing us from releasing the update to our new components

**Comment by exextoc** [comment]
Could you please share a sample code snippet so that we could reproduce this in-house?

**Comment by pietrofxq** [comment]
I ended using the library Juice to inline all styles in our component's html. So no need to fix it on outlook end since there is a workaround
