### ISSUE TITLE
Taskpane: Spacing in release massages 

### ISSUE THREAD

**Issue by barano21** [OfficeDev/office-js#2499]
When the message of a new Add-in release appears in the taskpane, there is no spacing on the left. See atached image:
![image](https://user-images.githubusercontent.com/96837254/160377548-3dd2a4c2-fd0c-4177-b340-42255039a960.png)

## Your Environment
Platform: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (version 2202 compilation16.0.14931.20128) 64 bits 
Operating System: Windows 11
Browser: Edge
Manifest version:  2.4.0
 
## Expected behavior
The content on the taskpane shouldn't be touching the left border. Some padding should be added there.

## Current behavior
When the message of a new Add-in release appears in the taskpane, there is no spacing on the left. See atached image:
![image](https://user-images.githubusercontent.com/96837254/160377548-3dd2a4c2-fd0c-4177-b340-42255039a960.png)

## Steps to reproduce
1. Open MS Word 
2. Open MathType add-in with a new release
3. See the message

**Comment by grangeryy** [comment]
@yihuax @RuizhiSunMS any idea on this? I can reproduce on my win32 machine (windows, Office Version 2204(Build 15109.20000 Click-to Run, Beta Channel)). It won't impact Word online as the update experience for online is a pop-up dialogue:
![image](https://user-images.githubusercontent.com/50093161/160593250-e4b08787-93d9-440e-8da0-c65de11ff737.png)

**Comment by yihuax-msft** [comment]
Maybe Heidi's team knows?

**Comment by grangeryy** [comment]
@AbidRahman-MSFT do you know any information about this issue?

**Comment by grangeryy** [comment]
The issue has been fixed. @barano21 please have a try and let us know if it's resolved:)
