### ISSUE TITLE
Table.sort.reapply() crashes Excel

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js#25]
## Expected Behavior
Table has been sorted. User changes one or more cell values in the sort-on column, so the table rows are no longer in the proper sort order. Code calls myTableObject.sort.reapply(). The table is resorted on the existing criteria so it is again in desired sort order.

## Current Behavior
When myTableObject.sort.reapply() runs, Excel crashes. There is no error message.

## Steps to Reproduce, or Live Example
1. Create an add-in (or Script Lab snippet) that 
    A. Calls `myTableObject.sort.clear();`
    B. Loads the `TableSort `object with `myTableObject.load('sort');`
    C. Calls `context.sync`
    D. Calls `myTableObject.sort.reapply();`
2. Assign the function to a button.
3. Create a table (manually or with code, doesn't matter) with 2 or more columns and rows. One column has text values that are NOT in alphabetical order.
4. Sort the column in Z-A order.
5. Change one of the column values so that it is out of order alphabetical order.
6. Click the button.

Excel crashes.
The crash won't happen unless you call `myTableObject.sort.clear();` before you call `myTableObject.sort.reapply();`. But Excel should not crash. 

## Context
I'm creating an Excel.js tutorial.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1712 8731,1000 Click to Run
* Operating System: Win 10
* Browser (if using Office Online): N/A

**Comment by sumurthy** [comment]
This is under investigation.

**Comment by JuaneloJuanelo** [comment]
i think this does not happen anymore. scriptlab used:
https://gist.github.com/JuaneloJuanelo/9d0a4fe3c5e2f427289bda44442df04a

if you still repro reopen and adjust the sample so its reproable.

**Comment by Rick-Kirkham** [comment]
Doesn't repro anymore.
