### ISSUE TITLE
New Outlook Message Compose mode : null and empty strings coming while getting recipients

### ISSUE THREAD

**Issue by gs-achandrakamal** [OfficeDev/office-js#2502]
- While trying to get recipients using Office.context.mailbox.item.to/cc/bcc.getAsync, emailAddress values come as null or empty string even with success as status

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Microsoft Outlook on Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook(Version 16.57, 16.58, 16.59)
* Office version number: ______
* Operating System: macOS Monterey
* Browser (if using Office on the web): NA
 
## Expected behavior
Recipients should be fetched properly if status is "Succeeded" using the mentioned getAsync method

## Current behavior
- While trying to get recipients using item.to/cc/bcc.getAsync(), emailAddress values come as null or empty string even with success status

## Steps to reproduce

1. Add a listener to the RecipientsChanged event, which checks for a change in to/cc/bcc recipients and calls Office.context.mailbox.item.to/cc/bcc.getAsync
2. Compose new message, add/remove recipient
3. Observe null/empty values come in the list comes even if getAsync method is returned with status as successful

## Link to live example(s)

# Provide additional details

1. This is faced by few of our customers. We have logs where emailAddresses are coming as null and empty
2. It's working as expected from Outlook web

## Context

Not getting the proper recipients on recipient change event, is breaking one of our crucial functionality .

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@gs-achandrakamal We are unable to reproduce the issue at our end. Can you please share a code snippet so that we can debug better?

**Comment by gs-achandrakamal** [comment]
Hi @exextoc , 

On Office.EventType.RecipientsChanged event, we call our getRecipientsFull method to get current to,cc and bcc recipients. 

`getRecipientsFull() {
                return new Promise((success, reject) => {
                    let records = [];
                    item.to.getAsync((toResult) => {
                        if (toResult.status === Office.AsyncResultStatus.Succeeded) {
                            records = records.concat(toResult.value);
                            item.cc.getAsync((ccResult) => {
                                if (ccResult.status === Office.AsyncResultStatus.Succeeded) {
                                    records = records.concat(ccResult.value);    
                                    item.bcc.getAsync((bccResult) => {
                                        if ((ccResult.status === Office.AsyncResultStatus.Succeeded)) {
                                            records = records.concat(bccResult.value);
                                        } else {
                                            // Logic to log the error(Type 1) for 'bcc'
                                        }
                                        success(this.getSanitisedData(records);
                                    });
                                } else {
                                     // Logic to log the error(Type 1) for 'cc'
                                    success(this.getSanitisedData(records));
                                }
                            })
                        } else {
                            // Logic to log the error(Type 1) for 'to'
                            success(this.getSanitisedData(records));
                        }
                    })
                });
            }`

Here getSanitisedData() just filters out the objects whose emailAddress is proper. It also logs an error(Type 2) for falsy or improper email addresses.

For some of our users following logs have been observed:

- Type 1 =>  error.message : "An internal error has occurred." error.code : 5001
- Type 2 => Null ,empty or falsy values are observed in email addresses.

We more concerned about Type 2, as this is happening while getting to/cc/bcc recipients using getAsync, even if result's status is successful.

Type 1 is a standard error received from Office js for getAsync failure cases.

**Comment by gs-achandrakamal** [comment]
Also, as mentioned before, this whole flow is working fine for those users from older Outlook as well as from the web.

**Comment by exextoc** [comment]
Thanks, @gs-achandrakamal for the details. We are still unable to repro the issue at our end. 
Are you able to repro the issue consistently in Outlook MAC? 

It will be better if you could create a test tenant with the same configuration and share the details to "OutlookAddins@M365x693897.onmicrosoft.com" so that we can debug it better or please share a small video/gif describing the issue.

**Comment by gs-achandrakamal** [comment]
I have shared the test tenant details along with a small video to show the entry points for debugging the  issues to the above link. Please let me know, if anything else is needed.
Also, it is suspected that item.from.getAsync is also returning null email address while getting sender information.

**Comment by exextoc** [comment]
Thanks @gs-achandrakamal . We have received details. We will get back to once we go through details and try to repro inhouse.

**Comment by exextoc** [comment]
@gs-achandrakamal We are still not able to repro this inhouse by following steps suggested in the video. Can you please share  a diagnostics ID when the issue is reproducible in "New Outlook Mac"?

**Comment by gs-achandrakamal** [comment]
Hi @exextoc
We are checking with the users facing this and added more logs for item.from.getAsync part, in case 'null' emailAddress is received. I'll update in sometime.
