### ISSUE TITLE
Content Controls Event Handlers not running

### ISSUE THREAD

**Issue by aafvstam** [OfficeDev/office-js#2503]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I researched the Content Control Event handlers some time ago and re-checked recently and they seem not to work. First time I noticed was November 2019 and has not changed over time. Adding the issue slipped my attention so here it is with some delay 😉

@davidchesnut was able to repro the issue in a scriptlab:
https://gist.github.com/davidchesnut/6cea5be3e35e38d79b6d7140c0596e20

I picked this gist up and created another repro to show that the events fail when events are not in in code run but split into segments (steps):
https://gist.github.com/aafvstam/b500fd49ed615f6546c318a44d64c809

## Expected behavior
onSelectionChanged and onDeleted events to be triggered when changing selection or deleting the Content Control

## Current behavior
The events are not triggered, especially when run from separate functions as seen in the demo

## Steps to reproduce
Run the Gists and watch the console

## Link to live example(s)
1. https://gist.github.com/davidchesnut/6cea5be3e35e38d79b6d7140c0596e20 (@davidchesnut)
2. https://gist.github.com/aafvstam/b500fd49ed615f6546c318a44d64c809 (@aafvstam)

# Provide additional details
Track internal mailthread with @davidchesnut @keyur32 and @JuaneloJuanelo Subject "OfficeJS API Events"
If you need that I can dig up the mail, but the Gists are probably clear enough to repro.

**Comment by nkkinariwala** [comment]
@AbidRahman-MSFT - Can you please help here?

**Comment by AbidRahman-MSFT** [comment]
@ElizabethSamuel-MSFT - is this related to the recent discussion we had around content control events not working as expected?

**Comment by ElizabethSamuel-MSFT** [comment]
@aafvstam We're in the process of adding Script Lab samples for these preview events. So far, we've added a sample for [ContentControl.onDeleted](https://github.com/OfficeDev/office-js-snippets/blob/main/samples/word/99-preview-apis/content-control-ondeleted-event.yaml). Can you give it a try?

Thanks.

**Comment by aafvstam** [comment]
The repo I provided to test failing of the onDeleted (and the onSelectionChanged) events shows that it is not working, but I will have a look at my Live Stream this Thursday and chime back.

**Comment by aafvstam** [comment]
@ElizabethSamuel-MSFT @davidchesnut The Script Lab sample is interesting as it shows (was not in the Docs documentation at the time I posted the issue) that it:

Stores the contexts in a 'global' variable:
let eventContexts = [];
**eventContexts[i] =** contentControls.items[i].onDeleted.add(contentControlDeleted);

And has to track the item
**contentControls.items[i].track();**

I guess the first part is to keep the context from being garbage collected, as we've seen years ago with VSTO objects to keep it in scope. The second, I thought, should be managed by using the Word**.run** implementation vs the Word.**RequestContext**.

Result of storing the context this way was that suddenly my 'old' implementation from a previous call that was still in my test code started to work again:

// this fails (bug in the API?)
contentControl.onDeleted.add(handleContentControlDeleted);
console.log("Added Delete Handler");

// this fails (bug in the API?)
contentControl.onSelectionChanged.add(handleSelectionChanged);
console.log("Added Changed Handler");

https://github.com/aafvstam/BlazorAddIn/blob/master/BlazorAddIn/Pages/Index.razor.js

So when I deleted a content control I now got two onDeleted notifications and a onSelectionChanged notification 😜

Will play a bit more with the code, but the used option to track the items seems to be working. I even notice the documentation for OnDelete was updated 👍

**Comment by ElizabethSamuel-MSFT** [comment]
@aafvstam Thanks for taking the time to try it and give your feedback. These APIs are still in preview so your feedback can help us make improvements. We'll share this with the product team so they can investigate the possible bugs you've reported.

Thanks.
