### ISSUE TITLE
EXCEL insertWorksheetsFromBase64 alters data source from pivot tables

### ISSUE THREAD

**Issue by jde-chil** [OfficeDev/office-js#2505]
# Provide required information needed to triage your issue
If a pivot table has a table as a data source it is not correctly imported using the insertWorksheetsFromBase64 method
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac, PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Mac os 16.59 latest, Excel 2202 latest
* Operating System: Mac os 11.6, windows 10
* Browser (if using Office on the web): N/A
 
## Expected behavior

Imported pivot tables using insertWorksheetsFromBase64 should keep their data source unaltered
## Current behavior

If you create a table, insert a pivot table in a different sheet and define its source as the table previously created. Save the template file and import the base64 representation of the file using insertWorksheetsFromBase64, the data source is modified with a random string added
for example, data source before `Table1` data source after import `'2F9A02C21'!Table1`

The order of the sheets in the template does not appear to change the end result
## Steps to reproduce

1. (a base64 text version of the file is provided at the end of the ticket) Create an excel file and insert a table, a pivot table and set the table as the data source
<img width="645" alt="Screenshot 2022-03-30 at 14 28 10" src="https://user-images.githubusercontent.com/16058184/160836365-7ebc7a36-f898-4e5a-bee7-0c95c7563dca.png">

2. run the following code snippet (taken from https://docs.microsoft.com/fr-fr/javascript/api/excel/excel.workbook?view=excel-js-preview#excel-excel-workbook-insertworksheetsfrombase64-member(1))
```
Excel.run(async (context) => {
    // if from a reader, else replace reader.result.toString() by content of txt file
    let startIndex = reader.result.toString().indexOf("base64,");
    let workbookContents = reader.result.toString().substr(startIndex + 7);
    context.workbook.insertWorksheetsFromBase64(
         workbookContents
     );
    await context.sync()
}).catch((e) => console.error(e));
```
3. the data source has been altered
<img width="572" alt="Screenshot 2022-03-30 at 14 32 04" src="https://user-images.githubusercontent.com/16058184/160837233-2aa07927-78bd-4eac-bc23-ce4db38c67c2.png">

## Link to live example(s)

# Provide additional details

## Useful logs

- [ ] Console errors `no errors`
- [ ] Screenshots
- [x] Test file (if only happens on a particular file)
a base 64 representation of an excel file that can be directly injected in insertWorksheetsFromBase64 (the `data:application/octet-stream;base64,` must be removed)
[base64.txt](https://github.com/OfficeDev/office-js/files/8380580/base64.txt)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by nkkinariwala** [comment]
@guliums  - Is it something you can help with?

**Comment by guliums** [comment]
@jde-chil Thanks very much for reporting the issue. The issue has been confirmed and tracked as ADO#5938043 in our backlog.

**Comment by jde-chil** [comment]
Thanks a lot

**Comment by csomgergely** [comment]
Dear Microsoft, are there any news regarding this issue? The last comment is more than an year old - which states it is on your backlog :(

**Comment by XuanZhouMSFT** [comment]
Thanks for waiting.
The insertWorksheetsFromBase64 API will follow the same behavior of copy/move worksheet action. After investigation, we found the behavior is the same as copy/move worksheet action, so it's by design.
After careful consideration, our team has decided to not fix this issue as it's a design change requirement. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.
