### ISSUE TITLE
insertWorksheetsFromBase64 does not support xlsm/xltm files.

### ISSUE THREAD

**Issue by mburbea** [OfficeDev/office-js#2506]

**Comment by nkkinariwala** [comment]
@guliums  - Is it something you can help with?

**Comment by RuizhiSunMS** [comment]
Hello @mburbea 
Those supported file types are parts of original design. One of reasons why it's designed like this is to keep consistent with the API online. 
The workaround mentioned in #1482 is the one you can take as reference.
Thank you.
