### ISSUE TITLE
This add-in could not be started.    Some users see this after switching to Edge WebView2

### ISSUE THREAD

**Issue by DansGithubAccount22** [OfficeDev/office-js#2507]
Summary
Task Pane Office Add-in doesn't load after enabling Edge WebView2 for some users.  The problem is intermittent.

Details
Recently we tried enabling Edge WebView2 by updating the registry setting specified here
 https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

Once enabled, some not all, can no longer get the add-in to load and see :   

This add-in could not be started. Close this dialog to ignore the problem ..

![image](https://user-images.githubusercontent.com/102698422/160931524-75c7d58b-20b3-4ba9-9326-6a9a62a708f2.png)

We can clear the cache ( specifically remove files in  this folder below )  restart Word/Excel and our add-in works for a period of time.

%user%\AppData\Local\Microsoft\Office\16.0\Wef\webview2\e742e97f-16d9-4913-b446-6f5cf4c314b4_ADAL\2\EBWebView\Default\Cache

If we toggle the registry back we no longer see the issue.  We also noticed that this issue only happens if Outlook is running at the same time.

## Your Environment
* Office: Word or Excel
* Office Version: Multiple versions of office and Edge Webview2
* Zoom for Outlook add-in
* 16.0.13801.21156 , 16.0.13801.21106
* Word 2102/2202 
* Edge Webview2 94.X , 99.X
* Operating System:  Windows 20H2
While our users are on the same version of office and windows, some are on different versions of Edge WebView2.  We have tried updating office and updating the Edge WebView2. 

## Current behavior
Unable to use an outlook add-in (zoom) and other office add-in at the same time

## Steps to reproduce

1)  Outlook is running and using an add-in like zoom that uses Edge Webview 2
2)  Try to use a task pane add-in in Word or Excel

**Comment by Dengshan2018** [comment]
@DansGithubAccount22 the issue repro only specific Add-in or for all add-ins?

**Comment by DansGithubAccount22** [comment]
We have a Microsoft Dynamics add-in and I get the same issue

![image](https://user-images.githubusercontent.com/102698422/161052124-0656f1f3-a975-4ff0-9466-9c56bd3641ae.png)

**Comment by DansGithubAccount22** [comment]
I want to also add that we have seen a similar issue to this reported before
https://github.com/OfficeDev/office-js/issues/1620

We have tried these steps but it does not fix the issue for us.  The issue comes back

Remove this folder:
%userprofile%\AppData\Local\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\

Execute the following Powershell:
Get-AppxPackage "Microsoft.Win32WebViewHost" | foreach {Add-AppPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}


Also that other issue mentions Edge WebView2 v95.  We're getting this in on v94 and v99

**Comment by nkkinariwala** [comment]
@millerds , @mattgeim  - Is it something you can help with?

**Comment by millerds** [comment]
This doesn't look like a tooling issue . . . it looks like an issue with the framework and/or webview2

**Comment by Dengshan2018** [comment]
@DansGithubAccount22 could you follow steps to check if Webview2 is used.
![image](https://user-images.githubusercontent.com/45212981/161440470-725081a5-6190-4851-84c8-b9d802251dde.png)

**Comment by Feetterer20** [comment]
@Dengshan2018 Hello, I am on @DansGithubAccount22's scrum team and I will continue to follow up on this issue this week while he is out on PTO.

Following the steps you've provided, I was able to see the following:

- Here is what I found when looking up the webview2 runtime that is installed on our work machines:
![webview2 runtime confirmation](https://user-images.githubusercontent.com/98554587/161863514-8fde7ec8-c3e5-49e9-be27-de309b5a6331.png)

- I ran into this add-in message when trying to add the People Graph to an excel spreadsheet. This could be related to how m365 is configured on our work machines:
![People graph unavailable for our laptops](https://user-images.githubusercontent.com/98554587/161863653-19aa0fa1-c736-4789-b226-4ac5b878996f.png)

- Although I couldn't see the security info for the People Graph, I did go to the security info after adding in our custom add-in to an excel spreadsheet and saw this:
![Security info for custom add-in](https://user-images.githubusercontent.com/98554587/161864108-682149d5-014e-4113-9fd1-df57d2b65a45.png)

Thank you for all of your help as we continue triaging this issue! Please let me know what I can do further to help you investigate things on your end.

**Comment by Dengshan2018** [comment]
@Feetterer20 , so you can insert custom add-in which is using Webview2. On that machine, do you see the failure of inserting "Microsoft Dynamics"? if failed, could you share the network trace through fidler tool?

**Comment by Feetterer20** [comment]
@Dengshan2018 I was able to add our custom add-in in this case. Unfortunately our issue is that 10% of our users who have had the registry change to use Edge WebView2 are experiencing the issue with our custom task pane add-in no longer loading, and the issues seem to be intermittent.

- When trying to add the "Microsoft Dynamics" add-in to an excel file, I do run into this issue:
![Microsoft Dynamics Error](https://user-images.githubusercontent.com/98554587/162050705-cae85999-b247-475f-ab71-2d684ef248fb.png)
    - Something to note here is this is after I've been using our custom add-in and the Office cache on my machine is being populated and utilized.

- I tried a couple of things out here. After running into the error mentioned above, I cleared my office cache on my machine and tried again, and the "Microsoft Dynamics" add-in loaded for me then. When things load correctly, I see a lot of fiddler activity, unfortunately when things don't load correctly, not much is happening when I monitor fiddler.

Do you know of any good tools to securely share Fiddler logs? This is something I want to be very cautious of as this is a public repo.

Thank you again for your help!

**Comment by Dengshan2018** [comment]
@Feetterer20 I added you to my private repository. you can share the information there.

**Comment by Feetterer20** [comment]
@Dengshan2018 Thank you for adding me to your private repo. I've gone ahead and uploaded a document with a screenshot of the Fiddler activity that occurred when attempting to load in the "Microsoft Dynamics" add-in and having it fail with the same message as is displayed in my previous comment. 

Overall, there isn't much Fiddler activity at all when this happens. When things do load correctly, there appears to be a lot more activity in Fiddler.

While continuing to troubleshoot this with our users this week, something interesting that we've found is that we're not able to clear the Office cache while having Outlook open. More specifically, every folder in the Office cache deletes, but the webview2 folder won't delete until Outlook is closed. This makes us wonder if Outlook is also using WebView2 and could be getting in the way here when trying to load these add-ins? Usually once we close Outlook and clear the Office cache, this is the workaround for our users that has been working for a period of time until they see the add-in error again after some time.

As always, thank you again for your help. Please let me know what else I can do to help you troubleshoot things on your end.

**Comment by cidev5** [comment]
Hi, users of our add-in are experiencing a similar issue with the same message starting this Monday, with more users being affected by the day.

In our case the only workaround is to either use the online version of Excel via office.com or to run Excel with Windows 8 compatibility mode turned on (accessible via the Properties of the Excel shortcut and then the Compatibility tab).

I should note that both our add-in and the Microsoft Dynamics add-in exhibit this same behavior, as I tried the Microsoft Dynamics add-in as well. I uninstalled WebView2 runtime but that didn't help either add-in.

**Comment by Dengshan2018** [comment]
> @Dengshan2018 Thank you for adding me to your private repo. I've gone ahead and uploaded a document with a screenshot of the Fiddler activity that occurred when attempting to load in the "Microsoft Dynamics" add-in and having it fail with the same message as is displayed in my previous comment.
> 
> Overall, there isn't much Fiddler activity at all when this happens. When things do load correctly, there appears to be a lot more activity in Fiddler.
> 
> While continuing to troubleshoot this with our users this week, something interesting that we've found is that we're not able to clear the Office cache while having Outlook open. More specifically, every folder in the Office cache deletes, but the webview2 folder won't delete until Outlook is closed. This makes us wonder if Outlook is also using WebView2 and could be getting in the way here when trying to load these add-ins? Usually once we close Outlook and clear the Office cache, this is the workaround for our users that has been working for a period of time until they see the add-in error again after some time.
> 
> As always, thank you again for your help. Please let me know what else I can do to help you troubleshoot things on your end.

Seems there is no useful information in the log.

Could you upload more logs by following the steps from https://docs.microsoft.com/en-us/office365/troubleshoot/diagnostic-logs/collect-office-diagnostic-logs?

**Comment by Dengshan2018** [comment]
> 

@cidev5 if you uninstalled webview2 runtime, add-ins will run on other webviews, Spartan or Trident. If you still see the issue, then the issue should be related with other services.

Would you like to share more logs by 
@Dengshan2018 Thank you for adding me to your private repo. I've gone ahead and uploaded a document with a screenshot of the Fiddler activity that occurred when attempting to load in the "Microsoft Dynamics" add-in and having it fail with the same message as is displayed in my previous comment.

Overall, there isn't much Fiddler activity at all when this happens. When things do load correctly, there appears to be a lot more activity in Fiddler.

While continuing to troubleshoot this with our users this week, something interesting that we've found is that we're not able to clear the Office cache while having Outlook open. More specifically, every folder in the Office cache deletes, but the webview2 folder won't delete until Outlook is closed. This makes us wonder if Outlook is also using WebView2 and could be getting in the way here when trying to load these add-ins? Usually once we close Outlook and clear the Office cache, this is the workaround for our users that has been working for a period of time until they see the add-in error again after some time.

As always, thank you again for your help. Please let me know what else I can do to help you troubleshoot things on your end.

Seems there is no useful information in the log.

Could you upload more logs by following the steps from https://docs.microsoft.com/en-us/office365/troubleshoot/diagnostic-logs/collect-office-diagnostic-logs?

**Comment by DansGithubAccount22** [comment]
@Dengshan2018  I noticed for me, that when my add-in says that it can't be started and I close outlook and try again the add-in starts.   It seems perhaps that outlook is preventing some add-in cache file from being updated that needs to be?

**Comment by DansGithubAccount22** [comment]
> @Dengshan2018 I noticed for me, that when my add-in says that it can't be started and I close outlook and try again the add-in starts. It seems perhaps that outlook is preventing some add-in cache file from being updated that needs to be?

Actually, that was not reproducible.  In another instances just closing outlook did not allow the add-in to restart.   
I've yet to reproduce the issue when I enable the officediagnostic logging.  That almost feels like a workaround for us to try..

**Comment by DansGithubAccount22** [comment]
Based on some recent testing, we've been able to isolate a problem when outlook is using the zoom add-in and we try to use a word/excel task pane add-in at the same time, since we switched to Edge WebView2.
I've opened a ticket with Microsoft

**Comment by Dengshan2018** [comment]
@DansGithubAccount22 do you have consistent repro with Zoom add-in?

**Comment by DansGithubAccount22** [comment]
The zoom add-in is deployed through the admin center
![image](https://user-images.githubusercontent.com/102698422/169174379-c6c36688-5c86-4d53-80a4-f470ae10feb8.png)

Then any task pane word add in
https://appsource.microsoft.com/en-us/product/office/wa104379629?tab=overview

**Comment by Dengshan2018** [comment]
I tried following steps:
1. Insert Zoom meeting in the outlook
2. insert wikipedia add-in in the word.

I didn't see the issue. Both add-ins work fine.
@DansGithubAccount22 , Could you provide more logs by following the steps from https://docs.microsoft.com/en-us/office365/troubleshoot/diagnostic-logs/collect-office-diagnostic-logs?

**Comment by DansGithubAccount22** [comment]
I may need to provide a couple additional steps.  In outlook, you have to use the add-in and see that its running Zoom
![image](https://user-images.githubusercontent.com/102698422/169296535-122798fd-499a-47e1-9678-68a0b0dabf14.png)
Make sure word/excel is closed at the time.   Once zoom is running, then try to use the wiki add in, in word or excel.

I will also collect those logs and send the, can you grant me access to where you want the logs uploaded @dengshan2018

**Comment by Dengshan2018** [comment]
@DansGithubAccount22 , any update?

**Comment by DansGithubAccount22** [comment]
We were able to determine this issue was environmental

**Comment by 4tti** [comment]
hello @DansGithubAccount22 would it be possible to share more details how have you resolved that, please? TIA!

**Comment by Dengshan2018** [comment]
@4tti , just for your information, from another thread, word and excel launched under Administrator. If they launch normally, there is no issue. @4tti let me know if you have different behavior. Feel free to open new issue and assign to me.

**Comment by 4tti** [comment]
Hello @Dengshan2018 , thanks for the info.
I was curious because we had one incident when this was happening intermittently but then customer closed the incident and was not reacting anymore. 
And do you have idea why running it under Admin should cause this issue? 
Thank you very much!

**Comment by Dengshan2018** [comment]
There is known bug that webview2 creation might fail under Admin when Windows explorer is running into some issue.

**Comment by 4tti** [comment]
Thanks!
