### ISSUE TITLE
Outlook for Windows: Custom properties are not set for meeting

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#2508]
# Provide required information needed to triage your issue
Custom property values are not assigned to emails sent after creating a meeting.
This issue occurs in Outlook for Windows and not in Outlook on the web.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2203 (Build 15028.20160) Current Channel
* Operating System: Windows 10 Pro 20H2
* Browser (if using Office on the web): Version 99.0.1150.55 (Official build) (64-bit)

## Expected behavior

The email contains custom property values.

## Current behavior

The email does not contain a custom property value.

## Steps to reproduce

1. Select New Meeting/Appointment
2. Add attendees
3. Add custom properties
4. Select Send

## Context

Our add-in provides the ability to manage the content of the email sent to the outside.
We have embedded the information with custom properties to identify the target email.

Is there a workaround to uniquely identify the email other than adding custom properties?

## Useful logs

This video shows the difference in behavior of custom properties in Outlook for Windows and Outlook on the web.

https://user-images.githubusercontent.com/58804032/161004831-9b74425f-acf0-4835-b0ee-54b963bb0b18.mp4

**Comment by exextoc** [comment]
Just to update here, we're following up on this, and will get back to you with an update soon.

**Comment by Oleg-O** [comment]
Thanks for reporting this issue regarding Custom Properties for meeting messages. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 2708169

**Comment by Oleg-O** [comment]
We have fixed the bug and the fix should be available in build 16.0.15528.10000 or later. When an updated build is available depends on the release channel a customer is on.
