### ISSUE TITLE
Outlook: Office.context.mailbox.item.to and Office.context.mailbox.item.cc returns only 20 email addresses

### ISSUE THREAD

**Issue by Ramesh8264** [OfficeDev/office-js#2509]
# Provide required information needed to triage your issue
In TO && CC fields max 20 email addresses are getting but the mail contains 200+ receipents

## Your Environment

* Platform [PC desktop, Windows Office on the web]: ______
* Host [Outlook]: Outlook
* Office version number: 1.1
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome
## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
This is as per the platform behavior. For more details, please refer to https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-1.1#properties

If you need this property change and wish to file a feature request, please use the below link: https://aka.ms/M365dev-suggestions
