### ISSUE TITLE
GeneralException thrown when context.sync() is executed in the presentation mode of online PowerPoint

### ISSUE THREAD

**Issue by moeBabazadeh** [OfficeDev/office-js#2512]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
I'm trying to implement some functionalities using Tags in my add-in. It works fine in the desktop version of PowerPoint (both edit and read modes) and edit mode of Office Online, but it's thrown an error on the read mode of Office Online.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: 16.0.15129.40520
* Operating System: Windows 11
* Browser (if using Office on the web): Firefox 98.0.2 (64-bit) / Google Chrome Version 100.0.4896.60 (Official Build) (64-bit)
 
## Expected behavior

context.sync() function should sync tags without any error.

## Current behavior

In the read mode, I need to read the presentation and slide tags. In order to do this, I need to call context.sync(), but it's throwing an error

## Steps to reproduce

Here is the function I am calling on Clicking the button 
```
function setPresentationTag() {
        try {
            PowerPoint.run(async (context) => {
                try {
                    context.presentation.tags.add("TEST_TAG","Test Tag");
                    await context.sync();
                    showNotification('OK');
                    return (true);
                } catch (error) {
                    showNotification('Error');
                    console.error(error);
                    console.error(JSON.stringify(error));
                    return (false);
                }
            });
        } catch (error) {
            app.showNotification('Error');
            console.error(error);
            return (false);
        }
    }
```

# Provide additional details

Here is the screenshot of the error
![S1](https://user-images.githubusercontent.com/57384/161275983-6bcb29ca-978a-4fda-8b09-8b1b1d3c66f8.png)

## Context

We are unable to use Tags Collection and our add-in relies on presentation and slide tags, so this breaks our functionality.

**Comment by nkkinariwala** [comment]
@LuyiH - Is it something you can help with?

**Comment by moeBabazadeh** [comment]
Our add-in will be launched soon, so we need to be able to make use of this functionality. Is there anything you can suggest?
