### ISSUE TITLE
copy to clipboard not working in Excel web

### ISSUE THREAD

**Issue by Raja315** [OfficeDev/office-js#2513]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I was trying to copy data to clipboard as part of custom tab ribbon commands in Excel using copy-to-clipboard(https://github.com/sudodoki/copy-to-clipboard). This npm package internally using document.execCommand(‘copy’) commands to copy data to clipboard. I tried this in chrome dev console and command is working. This was working in Excel Desktop but its failing in Excel Web. I tried few other alternatives to copy data but they are failing in web. Is this a known limitation or can someone help me how you can copy data to clipboard in Excel web commands ?

**Comment by JinghuiMS** [comment]
@Rick-Kirkham  This's not an excel api issue, it may be addin runtime issue on excel online. Please reassign it to correct team to better handle it. Thanks!

**Comment by Rick-Kirkham** [comment]
@slabereemsft Can you help find the right person to look into this issue?

**Comment by slabereemsft** [comment]
Abid - Is the WAC suppressing something here that's affecting copy?

**Comment by Raja315** [comment]
@AbidRahman-MSFT , I had a chat with Abid and he informed he will update the issue
