### ISSUE TITLE
Update PowerPoint slide with controls built on server

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#2516]
Hi,

I have an issue when trying to update a PowerPoint slide, more exactly I want to build on the server the controls that are not available on the frontend version of PowerPoint and then insert them into the slide.

Is there any way of doing this without inserting a new slide which is base64 encoded?

Thank you

**Comment by Rick-Kirkham** [comment]
@danielpdev Thanks for your interest in Office Add-ins. The issues in this repo are for tracking possible bugs in the Office JavaScript library. Programming questions like this one should be made on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/). Be sure to tag the question `office-addins-dev`.

**Comment by danielpdev** [comment]
Thank you @Rick-Kirkham, I just asked on the [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/products/).
