### ISSUE TITLE
slide.setSelectedShapes throws GeneralException (Preview APIs)

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#2517]
I tried the following:
```
PowerPoint.run(async (context) => {
	context.presentation.load('slides/items');
	await context.sync();
	const slide = context.presentation.slides.items[0];
	slide.load('shapes');
	await context.sync();
	context.presentation.slides.items[0]['setSelectedShapes'](context.presentation.slides.items[0].shapes.items[0].id);
	await context.sync();
});
```

Unfortunately when I call `setSelectedShapes` it throws a GeneralException error:
```
core.mjs:6485 
        
       ERROR Error: Uncaught (in promise): GeneralException: GeneralException
RichApi.Error: GeneralException
    at new RuntimeError (powerpoint-win32-16.01.debug.js:10492:36)
    at RequestContext.ClientRequestContext.processRequestExecutorResponseMessage (powerpoint-win32-16.01.debug.js:13770:24)
```

Do you know what can cause this issue?
Office js version: https://appsforoffice.microsoft.com/lib/beta/hosted/office.debug.js

**Comment by Rick-Kirkham** [comment]
I'm not familiar with the syntax of this line:

```
context.presentation.slides.items[0]['setSelectedShapes'](context.presentation.slides.items[0].shapes.items[0].id);
```

Could you explain it?

**Comment by danielpdev** [comment]
> 

I'm saying: from the first slide, select the first shape.
It is just a way of how to reproduce the error, not a good to use approach

**Comment by danielpdev** [comment]
It will be great for us to have it working.

Do you think it can be fixed?

**Comment by Rick-Kirkham** [comment]
I cannot reproduce your error. Your code does not error for me. Also, I still don't understand the syntax of that line. I don't think it's valid JavaScript. Please try to reproduce your error in Script Lab and then export your snippet as a gist that we can use to try to reproduce. Also, please use correct JavaScript.

**Comment by danielpdev** [comment]
What versions of the office-js library are you using ?
I still get the same error.
I used:
```
	<script type="text/javascript"
					src="https://appsforoffice.microsoft.com/lib/beta/hosted/office.debug.js"></script>
```

and `Office.context.diagnostics`: 
```
{
    "host": "PowerPoint",
    "version": "16.0.15028.20160",
    "platform": "PC"
}
```

**Comment by theboyknowsclass** [comment]
is there a setSelectedShapes for powerpoint Slide object?  i can't see it here -> 
https://docs.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.slide?view=powerpoint-js-preview

**Comment by danielpdev** [comment]
it is not on the docs, but it is loaded by: https://appsforoffice.microsoft.com/lib/beta/hosted/office.debug.js

**Comment by danielpdev** [comment]
![image](https://user-images.githubusercontent.com/3756051/163118296-ec980d8d-b81f-489c-bf3a-3a131c11517f.png)
Loded by:  https://appsforoffice.microsoft.com/lib/beta/hosted/office.debug.js -> which loads -> https://appsforoffice.microsoft.com/lib/beta/hosted/powerpoint-win32-16.01.debug.js

Unfortunately it does not work for me, does it work for someone? If it does, what PowerPoint version are you using?

**Comment by danielpdev** [comment]
Today was a good day, undocumented APIs seem to be working 🥇
Tried again some stuff and found out that if you're going to use directly the slide object it just work and does not throw any exceptions.

**Comment by theboyknowsclass** [comment]
ah great news @danielpdev !  do you know which platforms this is available in?  i'm wondering what else there is left undocumented!

**Comment by danielpdev** [comment]
Hi @theboyknowsclass,
I've only checked for PowerPoint, you can try for other platforms by building add-ins for them or change, maybe it will work.
Or you can search the the files related for the platform: https://github.com/OfficeDev/office-js/tree/release/dist

**Comment by danielpdev** [comment]
I'll close the issue.
