### ISSUE TITLE
 Office.addin.beforeDocumentCloseNotification.*() throws GeneralException (JS - Preview APIs)

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#2518]
Hi,

I have an issue when trying to call:
```
Office.addin.beforeDocumentCloseNotification.enable()
Office.addin.beforeDocumentCloseNotification.disable()
Office.addin.beforeDocumentCloseNotification..onCloseActionCancelled(() => {});
```

it throws:
```
core.mjs:6485 
        
       ERROR Error: Uncaught (in promise): GeneralException: GeneralException
RichApi.Error: GeneralException
    at new RuntimeError (powerpoint-win32-16.01.debug.js:10492:36)
    at RequestContext.ClientRequestContext.processRequestExecutorResponseMessage (powerpoint-win32-16.01.debug.js:13770:24)
```

**Comment by Rick-Kirkham** [comment]
@jeremy-msft  Can find someone who can investigate and help this customer?

**Comment by guliums** [comment]
Hi @danielpdev , thanks for reporting the issue! From your error message, you are using this API on PowerPoint. Unfortunately currently this API is only supported for Excel app. If you need this API on PowerPoint, you might go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) to request a new feature. Thanks.
