### ISSUE TITLE
Bindings are not being persisted when created  in Excel Online

### ISSUE THREAD

**Issue by pfilipp** [OfficeDev/office-js#252]
## Short summary
Saving excel workbook with bindings defined on Excel Online doesn't store binding data. 
The problem doesn't occur on Desktop version of Excel (tested on macOS).

## Expected Behavior
After saving file using Excel Online I should be able to load the file to Excel (online and desktop alike) along with bindings defined during previous session on Excel. 

## Current Behavior
If I save the file using Mac version of Excel that contains some data bindings those bindings will be available when I load file later on on both desktop and Online versions of Excel. If I perform the same operations using Excel Online, the bindings will get lost on saving file. 

**Low level explanation:** on desktop, saving dumps all data bindings to example.xlsx/xl/webextensions/webextensions1.xml. On Excel Online, after saving, there is no such folder as webextensions inside xlsx file.

## Example
Link to live example: https://gist.github.com/6b53ec53ee37e1697b987eebf28c825d

## Additional details:
  1. Open example in ScriptLab in desktop version of Office
  2. Select any range
  3. Click ‘Create binding’
  4. Save document and close office
  5. Reopen Office, load file, load ScriptLab with example
  6. Click ‘Highlight’. Observe as range is highlighted.
  7. Repeat steps for Office Online
  8. Observe that in Office Online it does not work. 

## Context
I am trying to load data from external source and be able to later on track inserted tables within workbook. 

## Your Environment
* Platform: Mac + Online
* Host: Excel
* Office version number:  Mac: 16.16.1 (180814), Online: 16.0.10904.31876
* Operating System: macOS 10.13.6
* Browser (if using Office Online): Chrome Version 68.0.3440.106

## Current workaround
It turns out that data is being persisted when using different set of API methods. 
If I create binding using 
`Office.context.document.bindings.addFromNamedItemAsync()`
instead of:
`context.workbook.bindings.add()`
the bindings will be stored in the file.

**Comment by JuaneloJuanelo** [comment]
Thanks for reporting the issue with so much detail.  I was able to repro the issue in Online, this is a bug. We will fix it as soon as possible.

**Comment by JuaneloJuanelo** [comment]
we are tracking with 2578281

**Comment by sedano** [comment]
Any updates for this fix? Or any place I can check the status of 2578281?

**Comment by kbrandl** [comment]
@sedano `2578281` corresponds to a Microsoft-internal work item, so it's not possible for external folks to access it.

@weshi -- I see that you recently commented on that work item -- can you please provide an update on the status of this fix (by adding a comment here within this GitHub issue)?

**Comment by MandytMSFT** [comment]
@sedano sorry for the late update. This issue has been fixed on March this year.  It deployed to Excel Online in 2 weeks. I just tried on online, already fixed. Thanks for your reporting.
