### ISSUE TITLE
Excel context.application.cultureInfo.datetimeFormat.shortDatePattern does not provide usable pattern string

### ISSUE THREAD

**Issue by stsoib** [OfficeDev/office-js#2520]
# Provide required information needed to triage your issue
On Excel Online, when File -> Options -> Regional Format Settings is set to French (France), system short date format on `cultureInfo.datetimeFormat.shortDatePattern` is `jj/mm/aaaa`, i.e. notations for date, month and year are localized to French ("jour", "mois", and "an"). In contrast, long date format is `dddd d MMMM yyyy`, which follows the d-M-y notations.

If the notations are not standardized across all locales, `shortDatePattern` is unusable for date string formatting purposes.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: n/a
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

`cultureInfo.datetimeFormat.shortDatePattern` should have d-M-y notations, just like `longDatePattern`, or its Windows Registry counterpart.

## Current behavior

`cultureInfo.datetimeFormat.shortDatePattern` is localized and it is not using the d-M-y notations for at least some non-English locales.

## Steps to reproduce

1. Create an Excel workbook in Office for web.
2. Go to File -> Options -> Regional Format Settings and change it to French (France).
3. Run this script in ScriptLab (example provided in [documentation](https://docs.microsoft.com/en-us/javascript/api/excel/excel.cultureinfo?view=excel-js-preview#excel-excel-cultureinfo-datetimeformat-member)): https://raw.githubusercontent.com/OfficeDev/office-js-snippets/prod/samples/excel/50-workbook/culture-info-date-time.yaml

![Capture](https://user-images.githubusercontent.com/103209704/162262542-1a23fd8d-ab59-4429-b5e7-65010e2471c3.PNG)

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

We need to parse and compose date string based on user's system short date pattern in our app in Excel.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by yuc014** [comment]
`cultureInfo.datetimeFormat.shortDatePattern` return `jj/mm/aaaa` in French (France) region is align with UI.

![image](https://user-images.githubusercontent.com/87364252/162921133-de6f22e8-f3cf-4c6e-8db9-2b537605ccaa.png)
(Select one cell, right click, select Number Format->custom)

For the long date format, this is another separate issue, will tracked by bug 5966425.
![image](https://user-images.githubusercontent.com/87364252/162923952-746b05c3-8494-4394-97e5-9f3a0c424a3c.png)

As a workaround, you can use `Range.numberFormat` and `Range.numberFormatLocal` like this:
```
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    let r = sheet.getRange("A1");
    r.values = [["1/1/2022"]]
    r.load("numberFormat"); 
    r.load("numberFormatLocal"); 
    await context.sync();

    console.log(r.numberFormat[0][0]);
    console.log(r.numberFormatLocal[0][0]);
    r.clear();
    await context.sync();
```
Will log:
```
m/d/yyyy

jj/mm/aaaa
```

I'm not sure your exactly scenario, if this workaround is not work for you, please let me know.

Gist: https://gist.github.com/yuc014/8ddc1d8e1591788a50b79f95035ac2ec

**Comment by stsoib** [comment]
The workaround would not work for us. We need to know user's short date pattern without changing anything in the worksheet.

**Comment by yuc014** [comment]
Ok, then I would try to suggest you:

1. Add a new worksheet, get the date format, and delete it. Which is no effect to user, even insensitive.
```
const sheet = context.workbook.worksheets.add();
let r = sheet.getRange("A1");
r.values = [["1/1/2022"]]
r.load("numberFormat"); 
r.load("numberFormatLocal"); 
await context.sync();

console.log(r.numberFormat[0][0]);
console.log(r.numberFormatLocal[0][0]);
r.clear();
await context.sync();
sheet.delete();
```
2. If do something within user's worksheet is strictly forbidden. Then go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) to request a new feature.

**Comment by keyur32** [comment]
@stsoib - did the latest suggestion work for you?

**Comment by stsoib** [comment]
> @stsoib - did the latest suggestion work for you?

No. If this is not regarded as a bug, we will request a new feature as instructed. Thanks.
