### ISSUE TITLE
"One or more add-ins failed to install or load custom functions" on Excel online

### ISSUE THREAD

**Issue by toni-lyttinen** [OfficeDev/office-js#2523]
We are developing an add-in for excel which was initiated with the [Yeoman generator](https://github.com/OfficeDev/generator-office). Our add-in uses custom functions that are written in the cells and we form and batch requests from the cells that are sent to a separate API which returns the calculated values and writes them to the cells. We are using the typescript version of the add-in.

The add-in is hosted in a Azure blob and the manifest is shared from Microsoft Admin panel to the users. When the add-in is loaded in the Excel desktop version it works fine. However, when we load the add-in in online Excel (all browsers we tested so far) we receive an error notification stating "One or more add-ins failed to install or load custom functions". The functions are loaded however. In case we decide to refresh the page, we receive the same error message, but the custom functions are not listed unless we import the add-in again to the Excel online session. In any case we receive the same error message every time in the online version. This issue occurs **only** in the production version (built) and in the online Excel environment.

Not sure if related: For some reason every time the add-in is loaded we receive warnings in the console (see screenshots at the end). Apparantly our functions are loaded twice for some reason.

## Expected Behavior
When the add-in is loaded to the online Excel, the custom functions are loaded and stored correctly without any error messages.

## Current Behavior
The "One or more add-ins failed to install or load custom functions" error message is promted every time we open the online Excel with the add-in imported. When we import the add-in we receive the same error message but the custom functions are listed in the functions. If we refresh the page, we still receive the same error message but the custom functions are not listed within the functions. However, the add-in works and if we use the custom functions, they are recognized and function correctly although they are not listed within the functions.

## Steps to Reproduce, or Live Example
  1. Generate excel add-in with Yeoman
  2. Build production version
  3. Host the built version on Azure blob
  4. Import manifest that fetches data from the built version from blob
  5. "One or more..." error

* Link to live example: ______

* Additional details:

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): Chrome, Firefox, Edge, Safari

## Useful logs
Not sure if related but each time the add-in loads we receive the following warnings in the console
- [ ] Console errors
- [ ] Screenshots
![image](https://user-images.githubusercontent.com/66460721/162691852-7b1dac45-cb4f-4aa3-833c-1f8356b9385d.png)
![image](https://user-images.githubusercontent.com/66460721/162694963-efa4b66d-eb3e-4166-bb9e-d0e6d09264a3.png)
- [ ] Test file (if only happens on a particular file)

**Comment by keyur32** [comment]
Assigning to @grangeryy  to help.

Off the top of my head - I would check your cache in your browser to see if you don't have an older instance of the add-in cached somewhere. The error you are getting seems to indicate the function names already exist so the new add-in can't be installed.

**Comment by toni-lyttinen** [comment]
> Assigning to @grangeryy to help.
> 
> Off the top of my head - I would check your cache in your browser to see if you don't have an older instance of the add-in cached somewhere. The error you are getting seems to indicate the function names already exist so the new add-in can't be installed.

Thank you for your response.

I've searched for similar issues reported online and there first ran into proposals where the cache might be the culprit. I've tried the solutions presented there, but so far that has not fixed our issue. I have also tried to associate the custom functions with the metadata as suggested in the Office documentation (see 3rd link).

Link to documentation that I've tried:
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache

https://answers.microsoft.com/en-us/msoffice/forum/all/one-or-more-add-ins-failed-to-install-custom/2cff7971-399f-427d-9d39-e615f49c9302

https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-troubleshooting

**Comment by grangeryy** [comment]
Adding @jiju-MS

**Comment by toni-lyttinen** [comment]
One thing I also noticed is that if I run the add-in on desktop Excel and add any COM add-in (for example Analysis ToolPak) a notification for "One or more add-ins failed to install custom funtions" is given and and the custom functions disappear from the "Insert function" list. The add-in works fine if you have COM add-ins already added but incase you add them while the Excel is open it breaks the custom functions of our add-in and adds "xldudf" string to every cell where our custom functions are called.

Hopefully this helps debugging this issue.

**Comment by toni-lyttinen** [comment]
Any progress on this ?

**Comment by yaweizhu-henson** [comment]
Sorry for the late response, I will let engineer have a look at this issue!

**Comment by JHJ-MS** [comment]
Hi @toni-lyttinen , thanks for your reporting, and sorry for the late response.

I use Yo Office to generate a CF addin project locally and upload its manifest on excel online. It works fine. A locally built project works fine for you too, right?

I'd like to further understand the repro steps. For the repro step "Host the built version on Azure blob", do you mean you put the JS and JSON files on Azure? For the step "Import manifest that fetches data from the built version from blob", do you mean to upload the manifest on excel online?

If you don't mind, could you please provide your add-in's manifest to us, which may help us repro it?

Btw, the COM add-in affecting CF JS Addin's loading issue on the Desktop is a known issue and is a different issue from the online one. We have an internal Backlog item #5349227 tracking it. It is under investigation.

Thanks.

**Comment by donlvMSFT** [comment]
Hi @toni-lyttinen , for the COM add-in affecting CF JS Addin's loading issue on the Desktop, we have a fix currently in rolling out process. It should be available for Current Channel in 1 week, and if you have Office version >15831.20122, could you do some validation and let us know if it's resolved?

**Comment by donlvMSFT** [comment]
I'd like to close this issue due to current status, please raise a new one or reactive if there're further questions. Thanks!

**Comment by jungjin09** [comment]
same problem 365 Version 2312 Build 16.0.17126.20132 (64bit)
