### ISSUE TITLE
When is the Shape.lineFormat(),  Shape.height() and Shape.width() will be available for PowerPoint API on production?

### ISSUE THREAD

**Issue by savepong** [OfficeDev/office-js#2526]
## Hi There,

Currently, we are using the PowerPoint API Version 1.3 in our Add-in but it does not support getting the selected shape, getting shape location, and getting sizing, so we cannot implement a placeholder located and correct size as a user's selection

We saw those functions are available in the [API List of PowerPoint JavaScript APIs Preview](https://docs.microsoft.com/en-us/javascript/api/requirement-sets/powerpoint/powerpoint-preview-apis?view=common-js-preview) but need to make sure when it will have a fully released on production. That will make it easier for us to plan the development of our Add-in in the near future.

Hope to get a reply from you ASAP. 🙂

**Comment by theboyknowsclass** [comment]
Hi, we would also like to follow this.

**Comment by keyur32** [comment]
@LuyiH  - can you please comment? 

For folks who want to follow API updates, one great place to stay updated on what's coming is through our community calls, which I'm hoping you're already aware of and you can ignore my commentary :-)

**Comment by theboyknowsclass** [comment]
I was on yesterdays, but no timelines In this one…

Sent on the go. Apologies for typos and brevity
________________________________

**Comment by theboyknowsclass** [comment]
Any update on this?

**Comment by LuyiH** [comment]
Hi, The estimated time for the official release is mid-June, hope this could help you with the plan.

Thanks
