### ISSUE TITLE
Different return value of compareLocationWith()

### ISSUE THREAD

**Issue by bojanClarivate** [OfficeDev/office-js#2527]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Article URL

https://docs.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview#word-word-range-comparelocationwith-member(1)
## Issue

 I am using compareLocationWith()  to see if a user has selected a content control created by my add-in.
I've found that there's a discrepancy between Word online and Word desktop when running the following code against the same content control in the same document:

```
  const range = context.document.getSelection();
  const contentControls = range.contentControls;
  await context.sync();
  const items = contentControls.items;

  if (items.length === 1) {
  const contentControl = items[0];
  const contentControlTitle = contentControl.title;
  if (contentControlTitle === "My Content Control") {
    const contentControlRange = contentControl.getRange(Word.RangeLocation.whole);
    const comparison = contentControlRange.compareLocationWith(range);
    await context.sync();
    console.log(comparison.value);
  }
```
For Word Online console.log(comparison.value); returns insideStart
For Word Desktop console.log(comparison.value); returns Equal
Is that expected outcome?

Update: 
After some updates you published on API, results are now changed, but still different:
For Word Online console.log(comparison.value); returns **contains**

**Comment by AlexJerabek** [comment]
Hi @bojanClarivate,

The discrepancy between the web and desktop versions seems unintentional. I'm going to transfer this issue to the product repo so members of the product team can take a look. 

Also tagging @ElizabethSamuel-MSFT for awareness.

**Comment by bojanClarivate** [comment]
Hi,
Any progress on this?

**Comment by bojanClarivate** [comment]
Hi all after some API updates that i noticed on your side, outcome is a little bit different. I updated original post with new findings.
