### ISSUE TITLE
Powerpoint Preview API - Shapes containing images are not resized properly

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js#2528]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi, i'm using the Powerpoint Preview API and using the shapes.top/left/width/height to set the position and size of an image that has already been inserted.

However the re-render does not complete properly for the image, the position is moved correctly, but not the size.

e.g. 
![image](https://user-images.githubusercontent.com/2139941/162951039-c092537b-e215-47b2-9287-8c13c5904291.png)

where you can see the 'handles' are the correct size, but the image is still rendered outside.

this is tested on powerpoint online using office.com

**Comment by theboyknowsclass** [comment]
(not this does not happen on powerpoint desktop)

**Comment by danielpdev** [comment]
+1

**Comment by keyur32** [comment]
@LuyiH  - can you please take a look?

**Comment by theboyknowsclass** [comment]
Hi, is there any update on this?

**Comment by LuyiH** [comment]
Sorry for my very late response. 
@ononder would you please help check this API?
