### ISSUE TITLE
Two different isInline statuses for messages shared from Microsoft Teams

### ISSUE THREAD

**Issue by ksobolewskiVL** [OfficeDev/office-js#2530]
# Provide required information needed to triage your issue

Office.context.mailbox.item.attachments returns different isInline information for opened Outlook Add-in from email and switched Outlook Add-in which is pinned

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: Windows
* Browser (if using Office on the web): -
 
## Expected behavior

Office.context.mailbox.item.attachments returns same information for Outlook Add-in opened from email and switched Outlook Add-in which is pinned

## Current behavior

Outlook Add-in opened from email returns true
Switched Outlook Add-in which is pinned returns false

## Steps to reproduce

1. Open Microsoft Teams in browser
2. Find message in conversation
3. Go to options for this message
4. Click "Share with Outlook"
5. Choose recipient and sent email
6. Open Outlook Add-in for a received e-mail
7. Check Office.context.mailbox.item.attachments, isInline status should be set as true
8. Pin Outlook Add-in
9. Switch to other mail
10. Back to email with message from MS Teams
11. Check Office.context.mailbox.item.attachments, isInline status should be set as false 

## Context

Depending on the type of addin opening the returned values are different, this may have to do with the type of attachment.
Attachment content type: "application/octet-stream"

The attachments for this message are: Ms Teams Icon and probably inicials

**Comment by keyur32** [comment]
Thank you for the report, assigning over to @exextoc to help.

**Comment by exextoc** [comment]
I'm currently not able to repro what you are describing. 

Running the following code: 

```
for (var i = 0; i < Office.context.mailbox.item.attachments.length; i++)
{
 console.log(Office.context.mailbox.item.attachments[i].name + " " + Office.context.mailbox.item.attachments[i].isInline); 
}

```

returns 

```
logo true
bbca517c-48a6-4f63-bf7d-fac9edd1fa4a true
```

in both steps 7 and 11. 

If you still repro the problem, please provide the detailed Build Version of Outlook that you are on. (i.e. 16.0.XXXXX.YYYYY), and perhaps save off the .msg file that repros the problem and upload it somewhere that we can access it.
