### ISSUE TITLE
Excel Online spams the console

### ISSUE THREAD

**Issue by christian-sap** [OfficeDev/office-js#2532]
Since some weeks Excel Online spams the console by logging every single HTTP request. See attached screenshot.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Excel Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Browser (if using Office on the web): All
 
## Expected behavior
No console spamming

## Current behavior
Console spamming

## Steps to reproduce
1. Use any Excel add-in
2. Open the console
3. You will see an entry for every single HTTP request done by Excel Online. This makes it impossible to use the console for development/support.

![SNAG-1528](https://user-images.githubusercontent.com/79985386/163121263-392bab15-7259-4ce7-a04c-9af02b25e88a.jpg)

# Provide additional details
Console spamming is done by MicrosoftAjaxDS.js

## Useful logs
- [x ] Screenshots

**Comment by keyur32** [comment]
Thanks for the report, @christian-sap. I was able to verify (doesn't happen with all add-ins) but I found one that did ;-).

Internal bug logged: 5971922.
