### ISSUE TITLE
Outlook API's `appendOnSendAsync` adds referenced image as attachment

### ISSUE THREAD

**Issue by fjaeger** [OfficeDev/office-js#2534]
When using `appendOnSendAsync` with some HTML text that includes an `<img />` tag, which references a remote source URL via the `src` parameter, Outlook (at least modern Mac UI) attaches the referenced image to the email and modifies the `<img />` tag to refer to the attached file instead of the remote source.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac modern UI
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: latest
* Operating System: macOS Monterey 12.3
* Browser (if using Office on the web): n/a
 
## Expected behavior
When requesting to insert a certain HTML tag, such as `<img />` then it is expected to **not** modify that referenced image and attach it statically to the email instead.

## Current behavior
The image that is referenced in the `<img />` tag is attached to the email as a file

## Steps to reproduce
Have a simple add-in that uses `appendOnSendAsync` to append some HTML text with an `<img/>` tag referencing a **remote** image URL as its source.

## Link to live example(s)
n/a

# Provide additional details
n/a

## Context
We try to use `appendOnSendAsync` to add a disclaimer to our users' emails, which includes a remote image in the HTML source.

## Useful logs
n/a

**Comment by keyur32** [comment]
Assigning to @exextoc to help advise on behavior

**Comment by exextoc** [comment]
Hey @fjaeger 

Please answer the below questions to help us understand the situation better
1. Was it working before? Is this something which has happened recently?
2. How does it impact your workflow? Is it a blocker for your scenarios?

**Comment by fjaeger** [comment]
@exextoc Thanks for getting back to me!

1. We recently started using the API  `appendOnSendAsync` for our purpose and therefore do not know if the behavior was different before. 
2. As we rely on appending some HTML, including an `<img />` tag, the current behavior breaks this core functionality of our app. As long as `<img />` tags are automatically converted to an image attachment, the whole functionality of our add-in is broken 😞

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding appendOnSendAsync. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 5496917

**Comment by fjaeger** [comment]
@exextoc I cannot confirm that this issue was properly fixed. We still see an attachment MIME part being created when we try to insert an HTML image via `appendOnSendAsync`!
