### ISSUE TITLE
Outlook add-in: Users keep getting prompts to trust the domain after clicking "Ok" on OWA

### ISSUE THREAD

**Issue by jlara005** [OfficeDev/office-js#2535]
Users keep getting prompts to trust the domain after clicking "Ok" on OWA. This happens whenever they load the add-in.

## Your Environment
Office on the web
https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
Windows 10 x64 Enterprise
Edge v100.0.1185.29 x64
 
## Expected behavior
Based on [this ](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/privacy-and-security#end-users-perspective) documentation users should only get the prompt once.

## Current behavior described by our users
1. In OWA, click "send" on a new message. Add-in stops email from sending (this is expected on-send functionality).
2. "Do you trust" prompt occurs. I click "yes".
3. Click add-in link at top of the insight message to open the add-in panel.
4. "Do you trust" prompt occurs. I click "yes".
5. Finish using add-in which closes the panel.
6. Click "send".
7. "Do you trust..." prompt occurs. I click "yes".
8. Message is sent.

## Provide additional details
This add-in uses the On-Send feature which stops an e-mail from sending if it doesn't have specific information. I am not sure if that has something to do with it.

The add-in is being hosted on a different azure domain than the O365 domain.

## Questions
1. Is there a way to "trust" this domain on the O365 tenant or manifest so users don't get this prompt?
2. What is happening behind the scenes when you click "Ok"? Is a cookie being set? Could it be edge browser is not allowing cookies?

## Screenshots
![image](https://user-images.githubusercontent.com/29823126/163402162-86e9d4f0-df88-48cc-9fa7-4ba0a715c5a4.png)

**Comment by codexeon** [comment]
Hello @jlara005, could you confirm more details about your environment to help us diagnose. If you navigate to edge://settings/content/cookies could you look at your "Block third-party cookies" setting. If third-party cookies are blocked, could you allow them and see if you still get multiple prompts. Only one prompt is expected, but storage access could be impacting you.

**Comment by jlara005** [comment]
Hi @codexeon. These are the settings used:
![image](https://user-images.githubusercontent.com/29823126/163466176-320e38da-e2c8-4f2b-8b5f-f0cae9d7a0c1.png) I asked the user to try on Chrome and he only gets one prompt there so it seems it is an issue with edge. Is there a way for the add-in to trust the domain on the tenant/manifest?

**Comment by exextoc** [comment]
Hey @jlara005 

Can you check the tracking prevention setting that you're using on edge?

![image](https://user-images.githubusercontent.com/28549921/164069735-4d46b335-1f04-49a0-b327-0bafdf81368a.png)

Try setting it to basic once and check if it works or not?

**Comment by jlara005** [comment]
> Hey @jlara005
> 
> Can you check the tracking prevention setting that you're using on edge?
> 
> ![image](https://user-images.githubusercontent.com/28549921/164069735-4d46b335-1f04-49a0-b327-0bafdf81368a.png)
> 
> Try setting it to basic once and check if it works or not?

For anyone having this issue - Edge and FireFox have the "tracking prevention" setting. If you set it to "Strict" you will get the multiple prompts. In Chrome you will get the multiple prompts if you have "block third-party cookies" enabled. Thank you @exextoc for the guidance.
