### ISSUE TITLE
"The argument is invalid, missing or has an incorrect format." error message on "Excel.createWorkbook" in excel office add-in for mac

### ISSUE THREAD

**Issue by mkotadiya-valorx** [OfficeDev/office-js#2537]
Starting from April 12, 2022 "Excel.createWorkbook" method has started failing while opening ".xlsm" files on office add-ins for mac.
It works well on office add-ins for windows.

While further investigating our team found out that an update (Version 16.60 (22041000)) was released for "Office for Mac" on April 12, 2022, in which the method has started failing.
[Update history for Office for Mac](https://docs.microsoft.com/en-us/officeupdates/update-history-office-for-mac)

## Expected Behavior

".xlsm" file should open as it used before Office for Mac Version 16.60

## Current Behavior

Throws "The argument is invalid, missing or has an incorrect format." error message

## Steps to Reproduce, or Live Example

*  [Sample Code](https://gist.github.com/maulik-kotadiya/959829b01b47ea21706883536fe88582)
    * Run the code in the script lab to reproduce the issue
* Runs well on office add-ins for windows.
* _**Throws error on office add-ins for mac**_

* Additional details:
  1. Code breaks on Office for Mac Version 16.60 (22041000)

## Context

Our users are blocked from opening their files on mac due to a new update

## Your Environment

* Platform: Mac
* Host: Excel
* Office version number: 16.60
* Operating System: Mac OS

## Useful logs

- [ ] Console errors
- {
"message": "The argument is invalid, missing or has an incorrect format.",
"name": "RichApi.Error",
"code": "InvalidArgument",
"traceMessages": [],
"innerError": null,
"debugInfo": {
"code": "InvalidArgument",
"message": "The argument is invalid, missing or has an incorrect format.",
"errorLocation": "Application.createWorkbook",
"statement": "var createWorkbook = application.createWorkbook(...);",
"surroundingStatements": [
"var workbook = context.workbook;",
"var application = workbook.application;",
"// >>>>>",
"var createWorkbook = application.createWorkbook(...);",
"// <<<<<",
"createWorkbook.open();"
],
"fullStatements": [
"Please enable config.extendedErrorLogging to see full statements."
]
},
"httpStatusCode": 400,
"line": 26,
"column": 254119,
"sourceURL": "[https://appsforoffice.microsoft.com/lib/1/hosted/excel-mac-16.00.js"](https://appsforoffice.microsoft.com/lib/1/hosted/excel-mac-16.00.js%22),
"stack": "n@[https://appsforoffice.microsoft.com/lib/1/hosted/excel-mac-16.00.js:26:254119\n@https://appsforoffice.microsoft.com/lib/1/hosted/excel-mac-16.00.js:26:318467\n@https://appsforoffice.microsoft.com/lib/1/hosted/excel-mac-16.00.js:26:316548\npromiseReactionJob@[native](https://appsforoffice.microsoft.com/lib/1/hosted/excel-mac-16.00.js:26:254119/n@https://appsforoffice.microsoft.com/lib/1/hosted/excel-mac-16.00.js:26:318467/n@https://appsforoffice.microsoft.com/lib/1/hosted/excel-mac-16.00.js:26:316548/npromiseReactionJob@[native) code]"
}

**Comment by valorx-git** [comment]
We are having customers who are unable to use their spreadsheets. This is quite critical.
Is there an option for paid support assuming it would be faster?

**Comment by keyur32** [comment]
Tracking internal item #302533027. Assigning to @guliums to help track this issue and investigate.

**Comment by guliums** [comment]
Hi @valorx-git @maulik-kotadiya , This API is designed to only support .xlsx file, you could refer to https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-workbooks#create-a-workbook which says "The method accepts a base64-encoded string representation of an .xlsx file as an optional parameter.". Supporting xlsm file is not align with our design that we are trying to avoid mixing macros and new office.js API model, so we made a change recently to block this API from creating macro (.xlsm) file. We understand that this is a behavior change that may break existing add-ins using that capability. Sorry for the inconvenient. Could you provide some more information about your add-in scenario, so we can try to find if there is any alternative solutions.
1. How many of your customers will be impacted? Is this a critical blocking issue for your add-in?
2. What is the functionality of macros in your scenario? Can you create .xlsx file instead of .xlsm file in that case?

**Comment by mkotadiya-valorx** [comment]
Hi @guliums,
Valorx customers use the add-in to open the excel file stored in their infrastructure to leverage the salesforce functionality within their existing excel workbooks. it can be "xlsx" or "xlsm" based on the use cases. They may have the macro to support the use cases. The sudden change has blocked our customers from using the valorx add-in. Customer files are retrieved from their infrastructure as a base64 and the valorx add-in uses the "Excel.createWorkbook" method which takes base64 as an argument to open those files

1. As of now more than 25 users have been affected and we are looking at 400+ more users once they upgrade to the 16.60. This issue is not only critical but "code red"
2. As I mentioned it depends on the uses cases and can vary from user to user. We cannot create ".xlsx" files as it does not support the macros.

I'd appreciate it if you provide us with an alternative to achieve the ".xlsm" file opening functionality from within the add-in meanwhile we get to the resolution of this ticket.

**Comment by mkotadiya-valorx** [comment]
Hi @guliums @keyur32 
Do we have any updates on this issue?
We have got more customers reporting this issue in the last 2 days.
We'd appreciate it if the concerned team can get on a call to discuss the issue in detail.
Lastly, Wouldn't it be possible for an API call to show an explicit warning on-screen before opening the ".xlsm" file stating that it's macro-enabled rather than just breaking the entire flow?

**Comment by guliums** [comment]
Hi @maulik-kotadiya , sorry for the late response. We understand that the behavior change has critical impact for your add-in. We are actively working on discussing and revisiting the design decision, tracked by 5982404 internally. I will let you know when we have update. Before we have a solution, you may suggest your customers to use an old build that does not have that change as temporary workaround. Thanks for your support and sorry for the inconvenient.

**Comment by mkotadiya-valorx** [comment]
@guliums we appreciate your efforts on it.
Could you please provide us with a way to track the progress on 5982404? Where can I find a public support statement or known issue statement about this behavior change?

**Comment by valorx-git** [comment]
@guliums @keyur32 
We had 3 of our fortune 500 customers report support tickets with us relating to v16.60 and I just got off an escalation call (please provide a non-public channel to share ticket details and user feedback).

Having them downgrade to v16.59 is not a feasible workaround. Users ask us, "why am I doing this or wasting time on this".

Moreover, it's not like you have stopped opening of .xlsm file type. There should have been an alternative API to allow this OR Macro's can run in a sandboxed environment from a security standpoint OR even a better suggestion. Right now users are simply not able to open their business critical spreadsheet apps.

**Comment by guliums** [comment]
Hi @valorx-git , sorry for the late response. Could you provide your contact information and we will contact you for updates and learn your ticket details and user feedback. Thanks for your support!

**Comment by valorx-git** [comment]
Please contact me and my team by emailing/setting up a meeting. Please use the email support@valorx.com

**Comment by JHJ-MS** [comment]
will close this thread as it is tracking in the email thread.

**Comment by 4tti** [comment]
Not sure it is good idea to close this thread as there are more people interested on the outcome of the internal investigation.
This is potential issue even for us, at least future wise.

**Comment by guliums** [comment]
Hi @4tti thanks for comments. Could you share your add-in scenarios using this API capability to create macro (.xlsm) file? Any comments are appreciated!

**Comment by 4tti** [comment]
> Hi @4tti thanks for comments. Could you share your add-in scenarios using this API capability to create macro (.xlsm) file? Any comments are appreciated!

Hello @guliums  well, we don't use it as of now. I just was curious about the outcome cause I know that with our legacy addin, the xlsm was heavily used to automate processes, some kind of ETL processes but also really to simplify user flow. And the VBA is customized by the customers and then used as a kind of template for the reports. And I know that this could be pretty powerful even with the web based add-ins unless the Office Scripts are available everywhere (desktop).

**Comment by JimbobTheSailor** [comment]
Is there an update on this. My Excel Add-in also allows my customers to use xlsm files. This is a critical workflow, as my customers use their existing Marco enabled workbooks to do their business logic as they need. My Excel API uses the output of their business logic in Excel Tables. This was a very bad idea to remove excel macros.  My clients can NOT run two Add-ins on their files. One for their logic, the other for my code. 

Can I have some resolution on this please

**Comment by guliums** [comment]
Hi @JimbobTheSailor , thanks for the question. This issue is about Excel.createWorkbook API which is used to create workbook with macros, I believe this issue has been resolved. Are you still see the error when calling to Excel.createWorkbook API? If yes, could you provide which Excel version you are using? Thanks!

**Comment by JimbobTheSailor** [comment]
Thanks @guliums . When you say 'solved' do you mean reverted back to how it was (supporting xlsm) or is there another solution?

**Comment by guliums** [comment]
Hi @JimbobTheSailor , when using Excel.createWorkbook(base64) to create a Macro workbook,  the latest behavior is the add-in user will be prompted with a "Trust this add-in?" dialog. The user must select the "Trust add-in" button to continue the process of creating macro workbook.
![image](https://github.com/OfficeDev/office-js/assets/53261170/eb738d53-0472-4e96-9866-d9a251371c87)
In older builds without above change, the behavior is like before that the workbook will be created directly.

**Comment by JimbobTheSailor** [comment]
Thanks @guliums. That is a good solution. Well done in responding to this issue and creating a good way forward for all parties.
