### ISSUE TITLE
Office.addin.showAsTaskpane() got a grey taskpane

### ISSUE THREAD

**Issue by Refinitiv-365** [OfficeDev/office-js#2538]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2203 Build 16.0.15028.20152 32-bit
* Operating System: Windows 10
![MicrosoftTeams-image](https://user-images.githubusercontent.com/98725157/163760624-4db884f5-2966-4206-94f9-947e45619672.png)

 
## Expected behavior
It should show the add-in task-pane properly

## Current behavior
After call Office.addin.showAsTaskpane(), It shows a grey taskpane.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/98725157/163760843-e1b0fa9f-3d65-4e23-9e43-7d5445d6dfbc.png)
But if the taskpane moved from sidebar by Task Pane Option > Move, It can show properly.
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/98725157/163761020-d4c5a074-fad9-47a6-9181-eea1947da8d8.png)

## Steps to reproduce
1. Sideload Add-in
2. Make script call Office.addin.showAsTaskpane()
3. Got a grey task pane

**Comment by Refinitiv-365** [comment]
###  In my investigation
In current behavior, Taskpane does not show web view and can not right click to use the inspect. But i can attach debugger can check Element, Sources has loaded same Expected behavior.
![image](https://user-images.githubusercontent.com/98725157/165883753-f423fdf8-3ceb-49f1-aa83-e369b621c100.png)

![image](https://user-images.githubusercontent.com/98725157/165883738-fa649ec1-b973-4d11-9c7f-b4b762fbb34b.png)

**Comment by grangeryy** [comment]
Hi @Refinitiv-365 does this issue still persist?
