### ISSUE TITLE
PowerPoint.createPresentation does not work for 40M+ PPTX

### ISSUE THREAD

**Issue by bonniezlai** [OfficeDev/office-js#2539]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
In Powerpoint desktop when try to create a new presentation with api PowerPoint.createPresentation that more than 40M, the new presentation not created and got the following error:

powerpoint-win32-16.01.js:26 
        
       Uncaught (in promise) RichApi.Error: An internal error has occurred.
    at new n (powerpoint-win32-16.01.js:26:237543)
    at r (powerpoint-win32-16.01.js:26:531524)
    at Object.OSF.DDA.issueAsyncResult (powerpoint-win32-16.01.js:26:69279)
    at Object.onComplete (powerpoint-win32-16.01.js:26:81413)
    at powerpoint-win32-16.01.js:26:101149
    at Object.agaveResponseCallback (<anonymous>:1:8029)
    at window.agaveHostCallback (<anonymous>:1:10461)
    at <anonymous>:1:8

But api context.presentation.insertSlidesFromBase64 is working with same size slide.

## Your Environment

* Platform : PC desktop
* Host : PowerPoint
* Office version number: version 2203
* Operating System: Windows

## Expected behavior

Presentation will be created in new tab of the Browser
## Current behavior

It throws the error and the presentation is not created
## Steps to reproduce

1.call api createPresentation with a pptx more than 40M

## Useful logs
powerpoint-win32-16.01.js:26 
        
       Uncaught (in promise) RichApi.Error: An internal error has occurred.
    at new n (powerpoint-win32-16.01.js:26:237543)
    at r (powerpoint-win32-16.01.js:26:531524)
    at Object.OSF.DDA.issueAsyncResult (powerpoint-win32-16.01.js:26:69279)
    at Object.onComplete (powerpoint-win32-16.01.js:26:81413)
    at powerpoint-win32-16.01.js:26:101149
    at Object.agaveResponseCallback (<anonymous>:1:8029)
    at window.agaveHostCallback (<anonymous>:1:10461)
    at <anonymous>:1:8

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
![image](https://user-images.githubusercontent.com/86827977/163776220-956c6071-8129-4d8c-a70a-d4b0e1430ee2.png)

**Comment by gavinliuc** [comment]
@LuyiH Hello, do you have any suggestion on this issue we met? Thank you!

**Comment by gavinliuc** [comment]
@slabereemsft @LuyiH Could you please let us know when can we get some update about the issue we met? Thanks.

**Comment by gavinliuc** [comment]
@LuyiH We have tried this a few days ago. It appreared the same result. Is this kind of protection on purpose to limit to open a latger file?

**Comment by LuyiH** [comment]
Hi, @ononder  would you please help a check on this?
