### ISSUE TITLE
[Outlook] Office.js on Browsers incorrectly don't add new line tag `\r` on the mailbox body

### ISSUE THREAD

**Issue by revanthroe** [OfficeDev/office-js#2540]
Office incorrectly neglects next line tag `\r` between words in the mailbox body on browser Chrome and Edge

## Expected Behavior
Office.js should always treat next line and encode with `\r` everytime as can be seen in native Outlook desktop app.

## Current Behavior
In the outlook mail body, if we have words separated with new line breaks, it ignores the space and treats them as a single work without any tags such as `\r` in browsers Google Chrome (100.0.4896.127) and Edge (100.0.1185.36). Whereas the line break between words is rightly encoded with `\r` in Outlook Desktop app (16.57) on Mac with OS Big Sur 11.6.1.
We should make sure we always encode the line break between words in a mail with `\r` on all browsers.

## Steps to Reproduce, or Live Example
I have attached message.eml which contains words separated with line breaks that is used to reproduce the issue on both Chrome and Edge browsers.
Create a mail using eml file and use this command to see the difference in the body encoding on browser vs on Outlook native desktop app.
Enter the following command in Devtools:
```Office.context.mailbox.item.body.getAsync('text', (r) => {window.mb = r});```
```window.mb```

As can be seen from the attached screenshots, on chrome browser with exact same mail and words we ignore `\r` tags between words which results in incorrect number of desired results in our application
<img width="1203" alt="Screen Shot 2022-04-18 at 5 28 09 PM" src="https://user-images.githubusercontent.com/36574866/163884997-e60c19ed-813e-4ab6-94e8-2b1eee55c317.png">
 
<img width="1082" alt="Screen Shot 2022-04-18 at 5 27 07 PM" src="https://user-images.githubusercontent.com/36574866/163885009-cb219ca9-2a30-440e-91eb-d856164df479.png">

## Context
I'm working on an Outlook add-in which makes use of the words in the mail to get corresponding matched keywords.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac OS Big Sur 11.6.1
* Host [Excel, Word, PowerPoint, etc.]: Outlook Version 16.57
* Office version number: 16.57
* Operating System: MacOS
* Browser (if using Office Online): Google Chrome (100.0.4896.127) and Edge (100.0.1185.36)

[message.eml file content to create a mail](https://drive.google.com/file/d/1RfdPMIl6Ri7hNygbaWPa9Bh_Wb6qiyQn/view?usp=sharing)

**Comment by exextoc** [comment]
We are not able to reproduce the issue on the Old Mac UI. 
Can you please switch to the new UI (16.59) and try reproducing the same?

**Comment by revanthroe** [comment]
The issue happens on Outlook.com website on browsers, not on native Outlook app and also I am already on the latest available version of Outlook.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding getBodyAsync in OWA. It has been put on our backlog. We, unfortunately, have no timelines to share at this point

Internal tracking id: Office: 582010

**Comment by exextoc** [comment]
This issue has been fixed and fix is available in latest versions.
