### ISSUE TITLE
PowerPoint : What is the release date for PowerPoint shared runtime ?

### ISSUE THREAD

**Issue by donlawatch** [OfficeDev/office-js#2541]
Hi, we are using shared runtime to run an application, and open/hide the task pane on PowerPoint, 
but this API is only available in the preview version [(Preview support for version 1.1 on Word and PowerPoint).](https://docs.microsoft.com/en-us/javascript/api/requirement-sets/common/shared-runtime-requirement-sets?view=common-js-preview#preview-support-for-version-11-on-word-and-powerpoint)

When it will be available in the production environment ?

**Comment by preethikakiru** [comment]
Hello @donlawatch, 
Thanks for the question! We currently do not have an estimated date on when shared runtime will be available in the production environment for power point, but it is a goal we are currently working towards. 
Best, 
Preethika
