### ISSUE TITLE
Excel partial cell font color

### ISSUE THREAD

**Issue by sweco-nlmdek** [OfficeDev/office-js#2544]
Hello,

I would like to be able to change the font color of a specific part of the text in a cell;
In VBA you would do something like this  

`
Public Sub changeColor()
    Range("A1").Characters(Start:=7, Length:=5).Font.ColorIndex = 3
End Sub
`

**Comment by yuc014** [comment]
Currently, the feature: set part of text in a cell property you requested, is not a part of the product. 

We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests are considered when we go through our planning process. 

Thanks, Microsoft 365 Developer Platform team
