### ISSUE TITLE
Show taskpane when ribbon is selected

### ISSUE THREAD

**Issue by EdwinStraver** [OfficeDev/office-js#2545]
II have created an add-in with a  custom ribbon. I would like my Taskpane to be opened, as soon as the user selects the ribbon.
Note that I do not mean "when the user presses an item on the ribbon itself" (I know how to do that), but rather, as soon as my ribbon is selected and becomes visible.

Is this possible?

**Comment by AbidRahman-MSFT** [comment]
Hey @EdwinStraver,

To clarify, you are looking for a way to open the task pane when the user "selects your add-in ribbon"? Does this mean when the user clicks on a custom tab in the ribbon that has been created by your add-in? 

There is unfortunately no way to achieve this behavior today. I would suggest posting the feature request at [aka.ms/m365dev-suggestions](https://aka.ms/m365dev-suggestions).
