### ISSUE TITLE
Application.Transpose results in error when array contains a String.

### ISSUE THREAD

**Issue by ChunQi-Lim** [OfficeDev/office-js#2547]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

On Microsoft Excel for Mac Version 16.60 (22041000), Macros utilizing the function Application.Transpose on an Array containing a string causes Runtime error 1004 error and incorrect value is assigned.

## Expected Behavior
The Array is transposed correctly: ("String",2,"","") to ("String";2;"";"")

## Current Behavior
The Macro fails and random characters are assigned to the cell containing the string value.

## Steps to Reproduce, or Live Example
Run the macro below:
Sub transposeTest()
    Dim Arr1(1 To 4) As Variant
    Arr1(1) = "String"
    Arr1(2) = 2
    Range("A1:A4") = Application.transpose(Arr1)
End Sub

After clicking on Debug and click on Run, the macro will continue and result in the odd character below:

<img width="90" alt="image" src="https://user-images.githubusercontent.com/8627901/164555573-31d18337-640c-4cd3-8aae-c08355283eb8.png">

## Context
Existing Macros are not working correctly. Macro workbooks are not usable for Mac users on Excel 16.60

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.60 (22041000)
* Operating System: macOS 12.3.1

## Useful logs

<img width="429" alt="image" src="https://user-images.githubusercontent.com/8627901/164556064-55b69fd7-39a7-4b19-b386-f4d4bc10e1f1.png">

**Comment by valorx-git** [comment]
@JHJ-MS
This was not published as a known issue and not sure why a working function was broken. Can you please provide an update?
