### ISSUE TITLE
Outlook add-in for event-based activation - Cancel event

### ISSUE THREAD

**Issue by thoffmann-fms** [OfficeDev/office-js#2549]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Please add an Outlook function OnAppointmentCancel for Calendar events so it's possible to rollback any needed actions after the Add-In has done processing but the user clicks the Close/Cancel button to delete the Calendar event.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26e021a8-709c-518e-1e44-7883343841a8
* Version Independent ID: a376eb35-7bd9-0cea-2446-8b11f7755494
* Content: [Office.AddinCommands.Event interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/office/office.addincommands.event?view=common-js-preview)
* Content Source: [docs/docs-ref-autogen/office/office/office.addincommands.event.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/office/office/office.addincommands.event.yml)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @timothyhoffmann,

Thank you for this feature request. I'm going to transfer this issue out of the documentation repo and into the product repo, where it will be viewed by members of the Outlook crew.

**Comment by exextoc** [comment]
We track Outlook add-in feature requests on our [Tech Community Page ](http://aka.ms/M365dev-suggestions) . Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
