### ISSUE TITLE
Getting "Out of stack space" error with latest OfficeJS with Angular 6 app when trying to execute Word.run

### ISSUE THREAD

**Issue by rasikat86** [OfficeDev/office-js#255]
## Expected Behavior
Should be able to get the context in Word.run.

## Current Behavior
App throws out of stack space error. 

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. This is the code snippet which throws the error - 
 setBindingFromSelectedText(fieldId, form) {
    Word.run(function (context) {
      const range = context.document.getSelection();
      context.load(range);
      return context.sync().then(function () {
        return context.sync().then(function () {
            console.log("In a table cell");
        });
      });
    });
  }
 
My package.json is as follows - 
{
  "name": "word-app",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "dev": "ng serve --ssl --ssl-key ssl/localhost.key --ssl-cert ssl/localhost.crt",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.2.0",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@microsoft/office-js-helpers": "^1.0.2",
    "@ng-select/ng-select": "^0.31.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "mydatepicker": "^2.6.3",
    "ngx-dropdown": "0.0.22",
    "npm": "^5.8.0",
    "npm-run-script": "0.0.4",
    "rxjs": "^5.5.6",
    "web-animations-js": "2.3.1",
    "zone.js": "^0.8.19"
  },
  "devDependencies": {
    "@angular/cli": "^1.6.8",
    "@angular/compiler-cli": "^5.2.0",
    "@angular/language-service": "^5.2.0",
    "@types/jasmine": "~2.8.3",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "@types/office-js": "0.0.52",
    "angular-tree-component": "^7.1.0",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "jquery": "^3.3.1",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "ng-diff-match-patch": "^2.0.6",
    "protractor": "~5.1.2",
    "ts-node": "~4.1.0",
    "tslint": "^5.9.1",
    "typescript": "~2.5.3"
  }
}

## Context
I am not able to do any interaction with the word document from the officeJS plugin and this is affecting a lot of functionalities from the plugin. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Windows 10
* Host [Excel, Word, PowerPoint, etc.]:  WOrd
* Office version number: 
* Operating System: ______
* Browser (if using Office Online): ______

**Comment by sameera** [comment]
What's the purpose of the `context.load(range);` in your code?
If you are trying to load some property of the range, load it specifically as `range.load(["rowCount",...])`

**Comment by rasikat86** [comment]
Actually, context.load is something we are using later. I am simply trying to get selected Text using below function - 

  setBindingFromSelectedText(fieldId, form): Promise<OfficeResult> {
      this.document.getSelectedDataAsync(Office.CoercionType.Text, {}, (asyncResult) => {
        if (asyncResult.status === Office.AsyncResultStatus.Failed) {
          // reject({
          //   error: 'Error: ' + asyncResult.error.message
          // });
        } else {
          this.populateInput(form, fieldId, asyncResult.value);
          this.setBindingInDoc(fieldId);
          // resolve({
          //   success: 'Successfully got selected text.'
          // });
        }
      });
  }

Even this returns an error like - 
ERROR Error: Out of stack space

**Comment by rasikat86** [comment]
Hi, any update on this?

**Comment by sameera** [comment]
Nothing in your code screams out as being problematic to me.
It would really help if you could create a simple ScriptLab script that replicate this issue.  It would help you get a faster response from the Office.js team.

**Comment by JuaneloJuanelo** [comment]
@rasikat86  is there a reason why you are not using the Word Specific APIs?

**Comment by rasikat86** [comment]
Hi, We figured out what the issue was - we were overriding the equals method on Object.prototype which was causing the error. It's working well now. Although the error stack trace was too vague to figure out the root cause. Thanks for your help though.

**Comment by Zlatkovsky** [comment]
@rasikat86, OK, glad you were able to find the issue.  If you feel like there is something that Office.js is doing that is incorrect, feel free to share the code that you had with overwriting the `Object.prototype`, and we can investigate further (though in general, overwriting prototypes is a dangerous thing :-))
