### ISSUE TITLE
Outlook Autorun setSignatureAsync moves focus out of screen with single  setSignatureAsync event triggered

### ISSUE THREAD

**Issue by vdboots** [OfficeDev/office-js#2551]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Web
* Operating System: ______
* Browser (if using Office on the web): Edge(Chromium) / Safari
 
## Expected behavior
Inserts the signature while user can continue typing mailadres in the to field. 

## Current behavior
In the browser the cursor moves from the "To" field to the and not to the body anymore.

## Steps to reproduce
1.  launch script where a email is added. 
2. open new email and start typing a name.

**Comment by vdboots** [comment]
This issue is new since this version moves the focus completely out of message at all.

In the production and the beta this issue occurs at the moment.

**Comment by exextoc** [comment]
Could you help us out with more detailed repro steps and a test add-in if possible?
Please send it across to: outlookwebaddins@M365x50631954.onmicrosoft.com
