### ISSUE TITLE
Inconsistent requirement set 1.8 for Outlook method: getAllInternetHeadersAsync:

### ISSUE THREAD

**Issue by NinaM31** [OfficeDev/office-js#2554]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Article URL

https://docs.microsoft.com/en-us/javascript/api/requirement-sets/outlook/requirement-set-1.8/outlook-requirement-set-1.8?view=common-js-preview
## Issue

> Added [Office.context.mailbox.item.getAllInternetHeadersAsync](https://docs.microsoft.com/en-us/javascript/api/requirement-sets/outlook/requirement-set-1.8/office.context.mailbox.item?view=common-js-preview#methods): Adds a new method that gets all the internet headers for a message item. Read mode only.

According to the doc `getAllInternetHeadersAsync` is only supported in 1.8, however the latest iOS outlook version `4.2213.0` supports this method but the latest Android outlook version `4.2211.1` does not.   

When using `getAllInternetHeadersAsync`: We were facing an issue of `your request is being worked on` on Android devices(as expected by the docs), however iOS version worked perfectly fine (not as expected by the docs) .

Thank you for taking a look
I had to mention that because it took me 2 days to figure out why only android clients were facing an issue 🙃.

**Comment by AlexJerabek** [comment]
Thanks for reporting this @NinaM31.

@samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi @NinaM31,

Thank you for letting us know. I'm sorry to hear it took some further troubleshooting to figure out the issue. We'll definitely look into this, so that we can update our docs accordingly.
