### ISSUE TITLE
Region settings for PowerPoint using Addin APIs

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#2555]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi,

Is there a way to get the user system region settings using the PowerPoint addin APIs?

Thanks,
Daniel

**Comment by ElizabethSamuel-MSFT** [comment]
@danielpdev Thanks for your question.

@LuyiH Can you take a look?

Thanks.

**Comment by danielpdev** [comment]
Thank you @ElizabethSamuel-MSFT

**Comment by LuyiH** [comment]
Hi @danielpdev, currently there is no API to support checking the system region setting.

Thanks
Luyi
