### ISSUE TITLE
OWA dialog displayed in iframe has inaccessible close icon

### ISSUE THREAD

**Issue by milankonir** [OfficeDev/office-js#2556]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: outlook.office.com
* Operating System: macOS Monterey 12.3.1
* Browser (if using Office on the web): Google Chrome 100.0.4896.127 (Official Build) (x86_64)
 
## Expected behavior

User should be able to use keyboard to navigate to the dialog's close icon

## Current behavior

Once user keyboard navigates inside the add-in iframe, focus is trapped inside the iframe and it's impossible to use keyboard navigation to reach back to the close icon.

## Steps to reproduce

1. Open dialog with `displayInIframe: true` option
2. Try to navigate through dialog with keyboard

## Link to live example(s)

# Provide additional details

## Context

Minor accessibility inconvenience issue (users can use esc key to close the dialog).

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ElizabethSamuel-MSFT** [comment]
@milankonir Thanks for raising this issue.

@exextoc Can you take a look?

Thanks.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding the accessibility of our add-in dialogs. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 2764369
