### ISSUE TITLE
Office.context.mailbox.item.conversationId and itemId sporadically returns incorrect value

### ISSUE THREAD

**Issue by fmcgough** [OfficeDev/office-js#2557]
We have an Outlook add-in to allow our customers to store conversations in a CRM system. This works by sending a conversation ID from the add-in to our API, which then queries the Microsoft graph API for messages matching the conversation ID. However for a small proportion of these requests, no messages are returned from the graph API.

We have recently added some additional error reporting around this scenario, recording the value of `Office.context.mailbox.item.conversationId` and `Office.context.mailbox.item.itemId`. There seem to be a couple of different things going on here - for one user, the message IDs can be used to retrieve an item from their inbox, but the conversation ID reported in the response differs from the value of `Office.context.mailbox.item.conversationId`. For another user, the graph API returns a 404 response for the message ID indicating that it belongs to a different mailbox altogether.

I haven't been able to reproduce this issue locally in my environment.
 
## Expected behavior
A GET request to the graph API using the conversation ID reported by `Office.context.mailbox.item.conversationId` returns at least one message.
`https://graph.microsoft.com/v1.0/me/messages?$filter=conversationId eq 'xxxxx'`

## Current behavior
In a small number of cases, 0 messages are returned.

## Your Environment

* Platform: PC, Mac, Outlook web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows, Mac
* Browser (if using Office on the web): Chrome

**Comment by ElizabethSamuel-MSFT** [comment]
@fmcgough Thanks for asking about this.

@exextoc Can you take a look?

Thanks.

**Comment by fmcgough** [comment]
Received a couple more error reports for this issue over the weekend. A user tried to store 2 different emails. Our diagnostics showed that the add-in reported a different `conversationId` for each email (neither of which returned any results), but interestingly the `itemId` for each email was identical. Querying for this message ID returns a 404 response from the API indicating that it belongs to a different mailbox. Meanwhile, the RFC-ID reported by `item.internetMessageId` differed between the two emails.

I hope these details are helpful to you - please let me know if there's more info I can provide.

**Comment by Oleg-O** [comment]
Hello Frankie, sorry about the delay in following up here. Does your add-in support shared folders/mailboxes (this is controlled by [SupportsSharedFolders](https://docs.microsoft.com/en-us/javascript/api/manifest/supportssharedfolders?view=common-js-preview) manifest element)? That could be one reason why you may be seeing evidence indicating more than one mailbox is involved.

Also, just to understand impacted clients and versions better, is it possible for you to log the data from Office.context.diagnostics object - host, version and platform - and share some more detail which host, version and OS you see this on?

**Comment by fmcgough** [comment]
> Does your add-in support shared folders/mailboxes (this is controlled by [SupportsSharedFolders](https://docs.microsoft.com/en-us/javascript/api/manifest/supportssharedfolders?view=common-js-preview) manifest element)?

No, it doesn't - we don't include this element in the manifest at all since the documentation states it defaults to `false`.

Regarding `Office.context.diagnostics` - we include these details in a built-in diagnostics screen in the add-in and have asked a couple of affected users to share these with us already:
- `pc`, `Outlook`, `16.0.14729.20260`
- `pc`, `Outlook`, `16.0.14827.20192`

I'll make an update to the add-in and include these values in the error reporting we collect when a user runs into this error, to help get a broader picture of the affected versions.

**Comment by fmcgough** [comment]
A few more version numbers for you:
- `16.0.15128.20178` (PC, Outlook)
- `16.59.313.0` (Mac, Outlook)

**Comment by timwan10** [comment]
A local EWSId would not be on the server anymore, if the message locally was moved and hadn't synced up yet. (i.e. unfortunately the EWSId will change as soon as an item is moved). So for example something like: 

1) Get the EWSId
2) Start a GetItem Call
3) User Moves the Message (now the ewsid from step 1 is not valid...though this would be timing related for when the changes sync to server)

or 

1) User Moves the Message
2) Get EWSId, start the GetItem Call
3) The step from 1 hasn't sync'ed to server yet, and results in an error. 

Is there anything unique/special about the emails that exhibit the bug? Are they on older e-mail messages or messages that were copied into an inbox? 

Do you have some sample values for the EWSId / Conversation IDs? Especially in the case where you can get the item locally and on the server, but then the Conversation Ids are different? (i.e. could you supply both the EWSId, and the two different Conversation Ids?) 

Does your add-in run in MessageRead Mode or MessageCompose Mode? (both?)

**Comment by fmcgough** [comment]
@timwan10 Both of the scenarios you describe above seem unlikely to me, we have several screenshots from users showing the message they are trying to store in their regular Focused inbox in Outlook. As far as I'm aware, the `conversationId` changes only if the subject is changed, which isn't the case for these users.

The add-in runs in MessageRead mode only.

Example conversation ID recorded as not found: 
`AAQkAGJlZGQwMjgyLTY3MjItNGRiZi04ZjllLWI1ZDJlOWFhM2RhYwAQADSxm3xWwemr3Lp0GNoOdt8=`
Associated with the following two message IDs: -`AAMkAGJlZGQwMjgyLTY3MjItNGRiZi04ZjllLWI1ZDJlOWFhM2RhYwBGAAAAAADGLsKBL4R8RLbW/7LI0OBSBwCWMFaeHvOFQLY81wtLtwK0AAAAAAEJAACWMFaeHvOFQLY81wtLtwK0AACkFKr6AAA=`
-`AAMkAGJlZGQwMjgyLTY3MjItNGRiZi04ZjllLWI1ZDJlOWFhM2RhYwBGAAAAAADGLsKBL4R8RLbW/7LI0OBSBwCWMFaeHvOFQLY81wtLtwK0AACkFJ6WAACWMFaeHvOFQLY81wtLtwK0AACkFMS+AAA=`
These messages could both be retrieved from the server, which reported a different conversation ID of `AAQkAGJlZGQwMjgyLTY3MjItNGRiZi04ZjllLWI1ZDJlOWFhM2RhYwAQAMawXKE7K4IorU-E63s-T58=`.

Another example conversation ID recorded as not found: `AAQkADkzNTZhYTljLTQzYzAtNGVmYi1iMjA5LWI0Mzg0MWYyMzNkYQAQAIYiUcExQsFGuLF4-s5egDs=`
In this case, the associated message ID also cannot be retrieved from the server, returning a 404 response: `AAMkADkzNTZhYTljLTQzYzAtNGVmYi1iMjA5LWI0Mzg0MWYyMzNkYQBGAAAAAAACOF5v6N4pT6eVVb5gMqu7BwCPdTD5T+EQTpm7Ll2/YzosAAAAAAEMAACPdTD5T+EQTpm7Ll2/YzosAADEEoHvAAA=`. This user seems to be experiencing the issue consistently across both PC and OfficeOnline platforms.

**Comment by timwan10** [comment]
1) To clarify/confirm does OfficeOnline = Outlook Web Access? And you are seeing this issue in general across all platforms? (OWA, Mac, PC) 

2) In the issues where the message ID cannot be retrieved from the server, something may have been cached in the Outlook Windows Profile, and if the user's mailbox moved on the server it could cause the error. In this case I would suggest recreating the profile: https://www.nextofwindows.com/how-to-re-create-outlook-profile-windows-10#:~:text=To%20perform%20and%20reset%20your%20Outlook%20profile%2C%20you,and%20Remove%20it%2C%20then%20Add%20a%20new%20one.

3) In the case where the conversation Id's are incorrect, you could try this too, but It's doubtful that would help. In this case, I decoded your Ids, and the mailbox section are identical on the Conversation ID and MessageId. The part that is off is the actual PR_CONVERSATION_ID property that is included in the IDs. In this case, it's pretty hard to track down. Is there anything unique that the user does? (sorting / moving / changing the tiem). Or do they have a COM add-in that modifies the messages in some way? Do those messages show up in the correct conversation in the Outlook UI. 

If you are on windows in this situation, you could ask them to delete their OST file to resync messages from the server to see if this fixes the issue. (for safety, instead of deleting you could just ask them to move it elsewhere, which will trigger Outlook to resync from the server)

**Comment by fmcgough** [comment]
Yes, we are seeing this issue across all platforms. It looks like "OfficeOnline" is what `Office.context.diagnostics.host` reports for Outlook Web Access. Do you think it's likely that caching issues are also causing the same behaviour on Mac or OWA?

**Comment by timwan10** [comment]
The Profile / OST solutions would only work for that PC (if they work at all). I think maybe there maybe multiple issues here that have a similar result. It would be interesting to know if creating a new profile or deleting the OST helped mitigate the problem for this user. 

However, problems in OWA / OfficeOnline, would not be covered by this, and likely points to a server issue. Are there a certain class of issues that you only see on OWA? And another that is only on PC? (same with mac)

**Comment by fmcgough** [comment]
Have done a bit more digging into the data, and it does seem like there are a number of different scenarios here, which unfortunately don't appear to be specific to any particular platform.

On Mac, we have error reports from 3 different users:
- For the first user, the conversation IDs reported return no results from the API, but the message IDs can be used to retrieve a message from the server. Example conversation ID and message ID: `AAQkADg4OTU1YWYyLTY2YWUtNGI0Ny1iZDExLTVkNzIxZWFmZDZiYQAQAOpIlsqvofhOuVv8G1zX2FI=`, `AAMkADg4OTU1YWYyLTY2YWUtNGI0Ny1iZDExLTVkNzIxZWFmZDZiYQBGAAAAAABWKnm3v4OrQajS7lrjG867BwCQWFpHildeQ6dte6/g+yCIAAAAAAEJAACQWFpHildeQ6dte6/g+yCIAAASXZUyAAA=`.
- For a second user (just 1 event): no results returned for conversation ID `AAQkADlkZGRjZDk5LTc2MGQtNDU3My1hY2JkLWNhN2VhMTNmNDk3ZQAQADiQZk73t2pIvoi1rjHP4Cs=`, 404 Not Found response returned for message ID `AAMkADlkZGRjZDk5LTc2MGQtNDU3My1hY2JkLWNhN2VhMTNmNDk3ZQBGAAAAAADejcc49XRzQKucPKNHnIx5BwDgpsRsgueKSq0K/YXiXKTpAAAAAAEMAADgpsRsgueKSq0K/YXiXKTpAAB8lnkgAAA=`.
- For a third user, most strangely of all - each of the conversation IDs reported **does** return a message from the API, with the RFC-ID matching what was included in the original error report. Example conversation ID: `AAQkADBlZjYzOTczLWE1ZTItNDI3Yi04MzVjLTM0YTM0NTRmYzg2OAAQAI_fRg0qU0-9pPKDIwO68vM=`, message ID: `AQMkADBlZjYzOTczLWE1ZTItNDI3Yi04MzVjLTM0YTM0NTRmYzg2OABGAAAD7tF+Xh6W1UyRt5cGhc5SJAcAS86mTqcGO0+iI5N/vlALfwAAAgEMAAAAS86mTqcGO0+iI5N/vlALfwABmXe2SQAAAA==`. The requests made by this user are a little older, most recently on 12th May - is there something that could have changed on the server between now and then that would explain this?

Another user experiences this issue both on PC and OWA/OfficeOnline. For this user, the message IDs reported can't be retrieved from the server. Example conversation ID / message IDs: 
- PC: `AAQkADkzNTZhYTljLTQzYzAtNGVmYi1iMjA5LWI0Mzg0MWYyMzNkYQAQAKs7nZFNc02svnYMQ4dyvG4=` / `AAMkADkzNTZhYTljLTQzYzAtNGVmYi1iMjA5LWI0Mzg0MWYyMzNkYQBGAAAAAAACOF5v6N4pT6eVVb5gMqu7BwCPdTD5T+EQTpm7Ll2/YzosAAAAAAEMAACPdTD5T+EQTpm7Ll2/YzosAADMv+MaAAA=`
- OfficeOnline: `AAQkADkzNTZhYTljLTQzYzAtNGVmYi1iMjA5LWI0Mzg0MWYyMzNkYQAQAHHc8cgrpc5IpGEUePrNM1s=` / `AAMkADkzNTZhYTljLTQzYzAtNGVmYi1iMjA5LWI0Mzg0MWYyMzNkYQBGAAAAAAACOF5v6N4pT6eVVb5gMqu7BwCPdTD5T+EQTpm7Ll2/YzosAAAAAAEMAACPdTD5T+EQTpm7Ll2/YzosAADEEoGfAAA=`

**Edit**: The Windows user mentioned above has tried deleting and recreating their Outlook profile as suggested, with no improvement. They have also confirmed that they have no COM add-ins (apart from one which is shown as disabled for performance reasons), and that they are not doing anything unusual with regard to sorting/moving/changing the mail item.

**Comment by fmcgough** [comment]
Hi @Oleg-O, do you have any updates or further suggestions to share on this? The issue is still affecting a small number of users fairly consistently.

**Comment by Oleg-O** [comment]
Hi Frankie, I've spent some time today trying to reproduce the issue under various conditions and was still unable to. Thanks for answering Tim's questions above, this helps. However, I do have additional questions that may help us get to the bottom of this, and would appreciate your answers:

1. For those people who reproduce it, does this happen on specific existing messages or keep on reproducing on new/recent messages as well?
2. For those repro messages, does this consistently repro for **those messages** or they start working sometime later (e.g., an hour or a day later) **on the same messages**?
3. For those repro messages, does this repro on the same messages **in a different client** (say, same message shows the issue on both Windows Desktop Outlook **and** OWA a.k.a. Outlook Web App a.k.a. OfficeOnline)?
4. Are all the repro cases in Inbox folder, or some/all of them observed in folders other than Inbox?
5. I see you mentioned "Focused Inbox" earlier in the thread. Does this only ever happen when "Focused Inbox" is enabled? Does this still reproduce if "Focused Inbox" is turned off?
6. Do the users who reproduce the issue use inbox rules?

I am assuming you're using **convertToRestId** JS API to convert the EWS IDs (returned from itemId and conversationId JS APIs) to REST IDs before using them with Graph - could you please confirm this too?

**Comment by fmcgough** [comment]
Hi, apologies for the delay in getting back to you on this. We've had a response from one of our customers to your questions, they report:
- the error occurs periodically, not on every request
- if they keep trying it eventually works
- they're not using Focused Inbox
- they're accessing Outlook on desktop only (on Windows)
- no inbox rules are in use.

I hope this is helpful for you, we'll continue asking your questions to customers who write in to report this error.

**Comment by fmcgough** [comment]
Hi @Oleg-O,

Apologies for the lack of feedback on this. We have another user now reporting that they are encountering this error for every conversation they try to store. They report that it keeps happening for new/recent messages as well as for existing ones, and that the error occurs consistently even when they re-try hours or days later. Our error reporting shows that they are using a variety of different clients including Windows desktop, OWA and iOS. The error occurs for messages in the Sent folder as well as for inbox messages, and occurs regardless of whether Focus Inbox is enabled or not. The user didn't know what we meant by "inbox rules" so it sounds like they aren't using them.

**Comment by jadesay** [comment]
Raised by customer here: https://secure.helpscout.net/conversation/2122339173/348117/ - Customer has answered Microsoft's questions in their email.
