### ISSUE TITLE
Select discontiguous cells in Excel

### ISSUE THREAD

**Issue by PradeeshKS1** [OfficeDev/office-js#2558]
RangeAreas class is missing the select() method similar to Range class.

**Comment by ElizabethSamuel-MSFT** [comment]
@PradeeshKS1 Thanks for raising this issue.

@guliums Can you take a look?

Thanks.

**Comment by guliums** [comment]
Hi @PradeeshKS1 , Thank you for reaching us. Based on my knowledge, so far we don't have this method.

I'd recommend going to [Microsoft 365 Developer Platform Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) and see if this feature has already been requested or request a new feature. Thanks for your support!

**Comment by PradeeshKS1** [comment]
Thank you.. wil request it as new feature.

**Comment by kyle-apex** [comment]
@PradeeshKS1 I did not see a post about selecting multiple ranges, so I created the following and would appreciate upvotes from anyone else who would like to see this feature.  Thanks!

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/select-multiple-discontiguous-cells-ranges-rangeareas-in-excel/idi-p/3607100
