### ISSUE TITLE
Slow GUI update of Outlook inbox after moving email with makeEwsRequestAsync to subfolder

### ISSUE THREAD

**Issue by coffeeforyou** [OfficeDev/office-js#2559]
**Use case:** I am moving an email with `makeEwsRequestAsync(...<m:MoveItem>...)` from the inbox to a subfolder. The call succeeds, and the email move is confirmed in the returned XML response (OSF.DDA.AsyncResult).

**Problem:** It takes a few seconds for the Outlook Desktop inbox to be updated (= email disappears from inbox and shows in subfolder), even after the XML confirmation has been received that the email has been successfully moved.

**Question:** Can I somehow notify the GUI of the Outlook host about the fact than an email has been moved from the inbox to a subfolder? Or is there any other way to ensure a quick update of the Outlook host GUI?

**Environment:**
Windows 10 Pro desktop with Microsoft® Outlook® 2019 MSO 32-bit
Developing Office add-in for Outlook
Using Microsoft 365 E5 instant sandbox

**Comment by AlexJerabek** [comment]
Thank you for reporting this issue @coffeeforyou.

@exextoc, could you please investigate?

**Comment by exextoc** [comment]
The makeEwsRequest async call goes up to the server, and moves it there. So as you suspect, it takes the server some time to sync the change back down to the client. Unfortunately, this isn't something that can be sped up or quick update. 

Are you doing anything else in the call or just a move? You may want to suggest a client side office.js function in our Tech Community forum.  

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
