### ISSUE TITLE
Add-in Error - This add-in is no longer available

### ISSUE THREAD

**Issue by mattblackdev** [OfficeDev/office-js#256]
Friends,

I wanted to share my experience with this issue. At Medtronic we are developing a Word add-in and we needed to setup a stage environment. So we have 2 manifests, one for the local webpack dev server and another for the stage server. Soon, we will need a third for prod. FYI, I am on macOS, latest High Sierra v10.13.6 running the company installed O365 and Word shows v16.17.

To create the manifest for stage, I simply copied the dev manifest and modified all the urls to point to the stage server. While side-loading this one a few times and switching between it and the dev mani., at some point Word would not load the add-in via office-toolbox, nor show it in the list of developer add-ins. It sadly displayed, "Add-in Error - This add-in is no longer available. If this add-in's manifest was removed, please restore it to its previous location and try again"

![screen shot 2018-09-24 at 11 11 23 pm](https://user-images.githubusercontent.com/5210361/45993441-000acf00-c05d-11e8-91a9-7ef56b27dbd9.png)

It did this for both the stage and dev manifest. The only thing I could do was upload the stage mani. to Word Online. I tried tweaking little things like the <Id />, <Version />, etc. to no avail. However, I created a new "yo office" generated add-in and it side-loaded just fine. Then, I sought to destroy every bit of Office related cache-looking files and folders on my system. No luck. As a last resort, I decided to reinstall Office. Still no luck! I followed a guide to completely remove office from disk, hoping to inadvertently trash some obscure remnants of my corrupted developer side-loaded add-in, and reinstalled Office three more times, finally remembering to restart my machine before and after the last attempt...

No luck.

But alas, duty calls. I remembered my previously successful test of the newly generated add-in project and its glorious "Your sample add-in loaded succesfully." popup. 

I copied the new project’s manifest into our project and it mysteriously side-loaded our project just fine. Then I started swapping lines of the new mani. with our mani, except for the resids, the little xml attribute that maps strings to usages 20 lines above. I left them as “Contoso.blah.blah” instead of “Medtronic.blah.blah”. Side-loaded fine.
 
Then I changed them all to “Medtronic.blah.blah” and it failed! Someone shoot me! At this point the manifest was back to its original state. So I changed them all to “MDT.blah.blah” and it worked again!
 
So, I thought, is the whole manifest getting hashed, cached and keyed by hash signature? But if that were the case, changing any character in the manifest should change the hash signature, which did not have an effect. The only thing that worked was changing these oh so vital resids.
 
I dug deeper still, trying to find maybe one of the resids to blame. After much trial and error, I am 51% certain the Url resources’ resids are to blame. Changing their resids seem to have an effect, but not their values, while changing other resources’ resids don’t, nor any of their actual values, as far as I can tell, and that’s as far as I want to dig on this.
 
Still doesn’t explain why completely uninstalling and reinstalling the entire Office suite did not matter… Lord have mercy. Bless you Microsoft.

**Comment by JuaneloJuanelo** [comment]
@mattblackdev  quick question: did you changed also the IDs of the manifests? or just the URLS?  please try that and let me know how it goes. thanks!

**Comment by RXminuS** [comment]
Wow, thanks for writing such detailed history. having the same issue and gone through same steps. But this might at least provide a short term fix!

**Comment by RXminuS** [comment]
Ok, I think my issue must be unrelated (although the same error messages) because a copmletely fresh `yo office` manifest file doesn't sideload either

**Comment by jamesdlow** [comment]
Did anyone ever find a way around this? I'm having the same issue in Excel.

**Comment by wh1t3cAt1k** [comment]
I just faced a similar issue after I had been side-loading locally for a while and then installed a store version as soon as it got approved.

Upon calling an add-in's custom function in Excel for Mac, I get a second taskpane tab saying "this add-in is no longer available".

Clearing Mac office caches as indicated in https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac does not help: it still tries to load custom functions, apparently, from nowhere as opposed to the add-in I just installed from the store.

**Comment by abimaelmartell** [comment]
Any fix on this? I'm having this same issue

**Comment by defusioner** [comment]
Having the same issue

**Comment by wh1t3cAt1k** [comment]
Guys, consider reopening this. Everyone on our team reproduces the issue using the steps provided above.

**Comment by ralphtheninja** [comment]
I have the same issue and there's no apparent way or workaround to make this work. Why was this issue just closed without giving a single explanation?

**Comment by ralphtheninja** [comment]
Ping. Linking into the future https://github.com/OfficeDev/office-js-docs-pr/issues/2297#issuecomment-894850045

You guys on Mac having this problem. You might want to try my dirty solution if that works for you. Maybe backup the `~/Library/Containers/com.microsoft.{host}` before attempting it.

**Comment by jonathanstokes** [comment]
> Ping. Linking into the future [OfficeDev/office-js-docs-pr#2297 (comment)](https://github.com/OfficeDev/office-js-docs-pr/issues/2297#issuecomment-894850045)
> 
> You guys on Mac having this problem. You might want to try my dirty solution if that works for you. Maybe backup the `~/Library/Containers/com.microsoft.{host}` before attempting it.

This worked for me, on MacOS Big Sur (11.6.1).  I deleted `~/Library/Containers/com.microsoft.Word`, and then I could side-load in the Desktop version again.

**Comment by wh1t3cAt1k** [comment]
@grangeryy @keyur32 pinging for notice, there seem to be a few votes for additional investigation of this issue, see @ralphtheninja 's comment...

**Comment by pasunmaa** [comment]
Same issue here. I wonder if there is any other solution than quick and dirty?

**Comment by nmathew22** [comment]
I ran into this issue when following the tutorial for creating an Office Addin for Excel with Yeoman outlined here: https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=yeomangenerator

Interestingly, the add-in would show properly without the error as long as I didn't have the addin folder open in VSCode. Not sure why VSCode would be affecting the addin, but wanted to share in case it helps anyone out.

**Comment by Adri99x** [comment]
any updates on this issue ?

**Comment by ESteanes** [comment]
I had this issue but quitting powerpoint and reopening it fixed it for me 🤷

**Comment by RuizhiSunMS** [comment]
Hi @ESteanes , sorry to hear that you got blocked. We highly suggest you create your own issue in this channel. Your question may be different from this case and also we can track your problem better with a new one.
