### ISSUE TITLE
Drag & drop images into a Word document (Windows)

### ISSUE THREAD

**Issue by paul-sudo** [OfficeDev/office-js#2561]
Use case: I would like to drag and drop images from the Taskpane into the Word document.

Problem: I have no problems inserting images into Excel or PowerPoint using drag and drop. On Linux/MacOS it also works in Word - only Windows 10/11 has problems and always inserts a link instead of the image. While debugging I noticed that the dropeffect is set to "link", but overriding this had no success.

So is it possible that instead of a link the image is inserted - like in macOS/Linux?

Environment:
Microsoft® Word for Microsoft 365 MSO (Version 2203 Build 16.0.15028.20226) 64-bit
Developing Office add-in for Word

**Comment by AlexJerabek** [comment]
Hi @paul-sudo,

Thanks for reporting this issue. @grangeryy, could you please investigate?

**Comment by GavinGu07** [comment]
Thanks @paul-sudo.
It could be better if you can tell us how to reproduce your issue. When I tried to drag the image from Taskpane into the document, there will be a prohibition symbol which indicates such operation is not allowed.

**Comment by paul-sudo** [comment]
Hi GavinGu07, thanks for your reply.
In my taskpane is a list of images (standard html img tags). These images can be placed in the document with drag & drop without any problems. I didn't notice any "prohibition sign" there either. As described above, it works everywhere - only Word under Windows 10/11 does not. Here it inserts the http/https link of the image, is that intentional?

**Comment by GavinGu07** [comment]
Hi @paul-sudo,
Yes, it is by design. If you drag an image from a webpage to a word document, it will also display as a link. Instead, if you drag the image to PowerPoint, it will display as an image.

**Comment by paul-sudo** [comment]
Okay thanks, so if there is no other way to solve this - the ticket can be closed.
