### ISSUE TITLE
setCellProperties throws an "Internal Error" when number of cells is too large

### ISSUE THREAD

**Issue by LeapSoftware** [OfficeDev/office-js#2564]
If you provide 80,000 cells to change via setCellProperties, the function works as expected,
If you provide 90,000 cells to change you recieve a RichApi.Error: An internal error has occurred.

What is the limit? Why is the error not defined and, why is there an error?

## Your Environment

* Platform: **PC**
* Host **EXCEL WEB**
* Operating System: **WINDOWS**
* Browser **CHROME**
 
## Expected behavior
I expect there to be a defined limit to setting cell properties, and perhaps receive a relevant error message. The limit i expect however is 5mb (as is typical with the excel API), 90,000 cell properties should not exceed this however.

## Current behavior
RichApi.Error: An internal error has occurred. When changing 90,000 cells properties

## Steps to reproduce
1. Create a set of 90,000 cell properties
2. Try to set these properties to a range

## Link to live example(s)
```
const sheet = context.workbook.worksheets.getActiveWorksheet();
      //Properties
      const writableCellProps: Excel.SettableCellProperties = {
        format: {
          fill: {
            color: "blue",
          },
        },
      };
      //Array of 90,000 cells
      const arr = [];
      for (let i = 0; i < 1000; i++) {
        arr[i] = [];
        for (let j = 0; j < 90; j++) {
          arr[i][j] = writableCellProps;
        }
      }
      //Range to write to
      const range = sheet.getRange(`A1`).getResizedRange(arr.length - 1, arr[0].length - 1);
      //Set properties
      range.setCellProperties(arr);

      await context.sync();
```
# Provide additional details
90,000 doesnt work, 80,000 does work.

## Context
I was trying to change the cell properties of 100,000 cells, we need this as a company (it is entirely possible to change the values of a range this big, so we also wanted to change the properties at the same time, this failed)

**Comment by AlexJerabek** [comment]
Hi @LeapSoftware,

Thank you for reporting this issue. I suspect you are hitting that 5MB limit. You might have to batch setCellProperties calls at that 80,000 cell count.

Let me tag @guliums to help investigate and confirm. We should also consider a more helpful error message.

**Comment by SiruiSun-MSFT** [comment]
Hi @LeapSoftware , sorry for delay response. After investigation, it turned out that the bug is in Excel side when set cell properties on a large table (bug id: 6244786). We have contact Excel team and they are actively working on it. Unfortunately, I don't have a timeline to share at this point, but I will keep updated in this thread. Thanks!

**Comment by SiruiSun-MSFT** [comment]
Hi @LeapSoftware, 
We did some testing on the latest version these days and found that this issue may have been fixed. Could you please verify whether the problem still exists? Thanks!
