### ISSUE TITLE
Redistribute VBA 7.1 ?

### ISSUE THREAD

**Issue by jeanfrancoisdesrosiers-eaton** [OfficeDev/office-js#2566]
We have legacy software that still uses VBA (Visual Basic for Applications). Following all my researches into MS web sites, I found VBA (not to be confused with VB.net) stopped being distributed at 6.5. BUT FOR SECURITY AND LEGAL REASONS I need a response from MS stating that: 
1) Visual Basic for Application (VBA) stopped being distributed for use by 3rd parties at 6.5.  
2) That the current 7.1 being bundled into MS Office cannot be redistributed by 3rd parties.

**Comment by dingjin-ms** [comment]
Hi @ZappedSquirrel , thank you for raising the question. We'll discuss more about this problem internally and will let you know as soon as we got a conclusion!

**Comment by dingjin-ms** [comment]
Hi @ZappedSquirrel , the redistribution feature is not related to VBA version, but only related to VBA SDK license. But as the license is not being sold any more, only existing license could distribute VBA.

**Comment by jeanfrancoisdesrosiers-eaton** [comment]
Great. Thank you for this answer. We still seem have a valid VBA SDK redist contract dating from 2002, signed by a Erik Stevenson (MS contract admin) on Nov 4th 2002. Since then, the resources turnover made us lose the technical ties with MS. I'm searching for the 7.1 SDK package to integrate and distribute. We are still at 6.5 + security patches. It seems MS does not make this package public. Sorry to bring you 20 years back.

**Comment by dingjin-ms** [comment]
Glad we answered your question! Please let us know if you still have any other problem. Thank you :)

**Comment by jeanfrancoisdesrosiers-eaton** [comment]
I'm searching for the VBA 7.1 SDK package to integrate and distribute.  It seems MS does not make this package public.

**Comment by dingjin-ms** [comment]
Hi @ZappedSquirrel , sorry for the late response. For the VBA SDK, you could connect Yaqi by Yaqi.Yang@microsoft.com directly, he would send you the updated SDK. Thank you!

**Comment by jeanfrancoisdesrosiers-eaton** [comment]
Thank you very much! We now seem to be talking to the right persons at MS and we'll continue directly with them. Now closing this "issue" here.
