### ISSUE TITLE
Office.Recipients (interface) getAsync: In OWA, the To field is not resolved after losing the field focus

### ISSUE THREAD

**Issue by Schaffora** [OfficeDev/office-js#2569]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

This issue is published on StackOverflow: https://stackoverflow.com/questions/72084690/office-recipients-interface-getasync-in-owa-the-to-field-is-not-resolved-aft

The "getAsync" function of the office recipient interface returns resolved recipients.

[Unresolved Recipient](https://i.stack.imgur.com/bfqPh.png)

[Resolved Recipient](https://i.stack.imgur.com/fYSdR.png)

In case a recipient is not resolved, this recipient won't be returned by this function.

We find a way/bug how to add a recipient that won't be properly resolved.

In case an outlook user enter an email address (without clicking on the outlook recipient proposals, without pressing tab/space or ";") and then click on another field (change field focus), for example by pressing on the messsage body, the content of the To field is not resolved.

In case the field focus is lost, the content of the fields should be resolved.

We have tested this behaviour with the Script Lab Add-in and we could confirm the issue.

[Script Lab Example](https://i.stack.imgur.com/2L2hK.png)
In addition, we could notice that if we set a new recipient using the setAsync or addAsync method, the start content of the to field is not resolved, only the new added email adress is validated.

[Script Lab after setAsync](https://i.stack.imgur.com/DN96H.png)
Our suggestions:

The set method should remove the start content or resolved the start email address also.
The main issue is the missing "resolve" on field focus lost.
Our question:

Why the field is not resolved after field focus change?

How is it possible to get the recipient value in this specific case ?

**Comment by AlexJerabek** [comment]
Thank you for reporting this issue. @exextoc, could you please investigate?

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding To field not getting resolved in OWA. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: [155529]

**Comment by Schaffora** [comment]
Thanks for the information! We hope this issue can be resolved as soon as possible. Best Regards Raphy

**Comment by exextoc** [comment]
Thank you for reporting this issue. We again looked at the issue and as per the current design, only resolved recipients are returned for Recipients.getAsync. We are updating our documentation to help reflect the same.

**Comment by Schaffora** [comment]
Hello @exextoc, the documentation is OK, like you wrote, only resolved recipient should be returned by the function. The issue is that the recipient is still not resolved after field focus changed. When an outlook  user/client wrote something in the TO/BCC field, then he change the field focus (without using "Tab", ";" or the Email Adress Proposal), he would expect that the content of the filled field is resolved. Unfortunately currently it is not the case. The resolve recipient function is only call when the user add a ";" at end of the email adress or when he press on "Tab" or click on one of the email proposals. Fix would be that when the user change the field focus that automatically, the content of the field are resolved. (You can find pictures and a good explanation here: https://stackoverflow.com/questions/72084690/office-recipients-interface-getasync-in-owa-the-to-field-is-not-resolved-aft)

**Comment by Schaffora** [comment]
@exextoc Hello, do you have any news about this topic ? 
Thank you, Best Regards, Raphy
