### ISSUE TITLE
displayDialogAsync - set dialog size in px

### ISSUE THREAD

**Issue by vyazadji** [OfficeDev/office-js#257]
Please add a possibility to set size of dialog in px

## Expected Behavior
Developers can set height and width in px.

## Current Behavior
We can use only percentages:

`Office.context.ui.displayDialogAsync('https://myDomain/myDialog.html', {height: 30, width: 20});
`

https://docs.microsoft.com/ru-ru/javascript/api/office/office.ui?view=office-js
https://docs.microsoft.com/ru-ru/javascript/api/office/office.dialogoptions?view=office-js#height

## Context
My popup has some fixed size but I can't set it properly. For example user can change size of the main outlook windows in this case it will affect the size of my popup. Using percentages is very uncomfortable. 

Thanks.

**Comment by danielgwilson** [comment]
Hi! We're looking into this :)

**Comment by JuaneloJuanelo** [comment]
@vyazadji  this is a really a new feature request. We track petitions here https://officespdev.uservoice.com/ please create an item for this. thanks!

**Comment by hbnrmx** [comment]
The uservoice seems to have been disabled. Instead I found
* a feature request in the new tracker https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/allow-dialogs-to-be-sized-using-pixels-and-not-just-percentages/idi-p/3043580
* a duplicate #305
* a potential workaround https://github.com/OfficeDev/office-js-helpers/blob/master/src/helpers/dialog.ts

**Comment by nshelia-da** [comment]
Issue is closed and moved to the completely different website where I can't even watch the progress on this. Why it's called a feature ? looks like a bug

**Comment by GabrielHangor** [comment]
Soo?
