### ISSUE TITLE
Feature Request - Add Image Shape (png / svg) for PPT API

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js#2570]
Hi,

I can see there are specific Add... methods to add different types of shapes... can methods also be added for images SVG / PNG?

I can add these via the Common API but they are quite limited - esp in terms of tracking the shape that was just created and modifying it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b0bc792a-f625-a4b4-2857-42c04f551d5d
* Version Independent ID: 9153e265-d150-3e8d-3b96-5ccde69ec511
* Content: [PowerPoint.ShapeCollection class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.shapecollection?view=powerpoint-js-preview)
* Content Source: [docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.shapecollection.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/powerpoint/powerpoint/powerpoint.shapecollection.yml)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @theboyknowsclass,

Thanks for raising this feature request. I'm going to transfer this issue to the office-js repo, where it'll be seen by the feature crew.

**Comment by LuyiH** [comment]
Hi, thanks for the request. 
The addSVG API is in our support plan,  I would suggest visiting [Microsoft 365 Developer Platform Ideas](https://aka.ms/m365dev-suggestions) to submit your idea, and this could help us prioritize.
