### ISSUE TITLE
Add-ins not loading in Firefox.  Work in Chrome.

### ISSUE THREAD

**Issue by atuszyn** [OfficeDev/office-js#2571]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Launching Excel Online by submitting a form inside of a web page.  Response to submit is the Excel Online page.  We specify an add-in to be included.  In Chrome, the add-in takes about 30 seconds to load.  In Firefox, the Add-in loading message appears in the status bar, but never goes away, and the add-in never loads.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __PC/Mac____
* Host [Excel, Word, PowerPoint, etc.]: ___Excel___
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): __Firefox__
 
## Expected behavior
This form is loaded in a web page and then submitted:

Non-production environment:
`<form id="cxp_wac_main_form" action="https://ffc-excel.officeapps.live.com/x/_layouts/xlviewerinternal.aspx?edit=1&amp;ui=en-us&amp;sftc=1&amp;rs=en-us&amp;WOPISrc=https%3A%2F%2Fwopi-test.cengage.com%2Fservices%2Fv1%2Fspreadsheet%2Fwopi%2Ffiles%2F1avje15ps%216p58%211g1j7klm1%21vh51%21t&amp;access_token=0000l2gaviue-00002u4-0&amp;host_install_addins=%5B%7B%22addinId%22%3A%22wa104379190%22%2C%22type%22%3A%22TaskPaneApp%22%7D%5D" method="post" target="cxp_wac_main_iframe">&lt;input name=="host_install_addins" value="{{"addinId":"wa104379190", "type":"TaskPaneApp"}}"/&gt;</form>`
 
Production environment:
`<form id="cxp_wac_main_form" action="https://excel.officeapps.live.com/x/_layouts/xlviewerinternal.aspx?edit=1&amp;ui=en-us&amp;sftc=1&amp;rs=en-us&amp;WOPISrc=https%3A%2F%2Fwopi.cengage.com%2Fservices%2Fv1%2Fspreadsheet%2Fwopi%2Ffiles%2F1avje15ps%216p58%211g1j05b64%21hf9d%21t&amp;access_token=0000l2geslrt-00002u4-0&amp;host_install_addins=%5B%7B%22addinId%22%3A%22wa104379190%22%2C%22type%22%3A%22TaskPaneApp%22%7D%5D" method="post" target="cxp_wac_main_iframe">&lt;input name=="host_install_addins" value="{{"addinId":"wa104379190", "type":"TaskPaneApp"}}"/&gt;</form>`

Response from form submission loads Excel online, requested addin loads, and user is able to launch addin.

## Current behavior
In Firefox, Loading Add-ins message appears in status bar, and never clears.  Addin never becomes available.
In Chrome, Loading Add-ins message appears in status bar for about 30-45 seconds, and the clears when the Addin's icon appears in the toolbar.

## Steps to reproduce

1. Unzip ExcelFormSubmit.html.zip
[ExcelFormSubmit.html.zip](https://github.com/OfficeDev/office-js/files/8643260/ExcelFormSubmit.html.zip)
2. Open ExcelFormSubmit.html using Chrome
3. Click on Submit to Non-Prod or Submit to Prod button
4. Note that new tab opens, Loading Add-ins message appears in status bar, and after about 30-45 seconds message clears and Show Toolpak icon appears in toolbar
5. Repeat steps 2 and 3 using Firefox
6. Note that new tab opens, Loading Add-ins message appears in status bar, and never clears, nor does Show Toolpak icon appear

## Link to live example(s)
Attached zip file can be used as live example

## Context
Students need Toolpak to complete assignment.  Current workaround is to use Chrome instead of Firefox

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Wenjun-Gong** [comment]
Assigned to @AbidRahman-MSFT to take further look

**Comment by Wenjun-Gong** [comment]
@JHJ-MS , would you please help to re-route? Thanks.
