### ISSUE TITLE
PowerPoint Preview API - values for Shape. top/left/width/height are not consistent over platforms

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js#2572]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

we insert a shape using setSelectedDataAsync with the following position and size:

height: 400
left: 50
top: 50
width: 600

when i retrieve this Shapes API Shape.top, Shape.left etc. it returns different values in Powerpoint for Windows, Powerpoint Online and Powerpoint on Mac OS X

in Powerpoint for Windows and Powerpoint on office.com

height: 300
left: 37.5
top: 37.5
width: 450

which is 3/4 of the reral values

but in Powerpoint for Mac OS X i get the correct values

height: 400
left: 50
top: 50
width: 600

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by LuyiH** [comment]
Hi, @ononder would you please help check this on Windows and Online?
Thanks

**Comment by theboyknowsclass** [comment]
https://gist.github.com/theboyknowsclass/4d03c136088c8d97ea44371afcc4b146 is the gist sorry.

i see there has been some changes recently?
