### ISSUE TITLE
Replacing contents of ContentControls removes Review Comment

### ISSUE THREAD

**Issue by els-ts** [OfficeDev/office-js#2574]
If a Content Control contains any review comments, those are removed when the contents of that control are replaced with any other text.

## Your Environment

* Platform: any
* Host: Word
* Operating System: Windows / Mac
 
## Expected behavior
Comments remain untouched.

## Current behavior
Comments are removed, sometimes a random character is added: `[?]`

## Steps to reproduce

1. Open attached document 
[Example.docx](https://github.com/OfficeDev/office-js/files/8661103/Example.docx)

2. Select any ContentControl
3. Run this code in Script Lab:

```typescript
$("#run").click(() => tryCatch(run));

async function run() {
  await Word.run(async (context) => {
    const control = context.document.getSelection().parentContentControl;

    await context.sync();

    control.insertText('Boom!', 'Replace')

    await context.sync();
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}
```

## Context
This affect the workflow of our users, which quite often are using Reviews Tools.

**Comment by grangeryy** [comment]
@els-ts, thanks for reporting the issue! We'll do some investigation soon.

**Comment by grangeryy** [comment]
Hey @els-ts, we have some update on this:
insertText() with replace option means first remove all text and then replace with new one. So all the formatting, comments and even content controls if the selection contains content controls will be removed and new text inserted. This behavior is consistent with actions from UI (select some text and delete it or select some text and type something new to replace). To keep the original comments, a work around solution is: first get the original comment and then insert back on new text.

**Comment by els-ts** [comment]
Thank you for clarifying this.

> first get the original comment and then insert back on new text

Are you able to point me out to the correct API that would be able to do this? Is it available on all platforms?

**Comment by grangeryy** [comment]
@els-ts sorry for the late response. Have you worked out the solution?

**Comment by els-ts** [comment]
@grangeryy - no, not yet. We haven't got time to look back to this issue yet.
