### ISSUE TITLE
excel-online(excel-javascript-api): selecting named ranges steals focus from taskpane/dialog

### ISSUE THREAD

**Issue by fds-sj** [OfficeDev/office-js#2576]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Selecting a named range using excel javascript api steals the focus from taskpane/dialog and sets it to the worksheet. This unexpected behavior messes with keyboard-only user workflows.
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Selecting named ranges behaves the same way as normal ranges where the focus is not being set to worksheet.

## Current behavior
Focus is being set to worksheet if a named range is selected using the excel javascript api call.
![focus-bug](https://user-images.githubusercontent.com/105348054/167818839-1c56b834-6114-48d4-8730-3199b7facd89.gif)

## Steps to reproduce
1. Open an Excel Online Worksheet and Install Script Lab Add-In.
2. Download this file - [named-range-focus-bug.txt](https://github.com/OfficeDev/office-js/files/8668511/named-range-focus-bug.txt)
3. Import Snippet in Script Lab and paste the content of the text file.
4. Run the snippet to reproduce the bug.

**Comment by yuc014** [comment]
Hi @fds-sj,

I tried your gist but not repro your issue. See the video below. 

https://user-images.githubusercontent.com/87364252/168023570-7c44d6be-c64d-4276-9947-e7149f26ecdd.mp4

I need more detail about it:
1. Whether your workbook just created and do nothing on it?
2. Your build number of excel online, go File->About->build. (Like 16.0.15310.35903)
3. By my video, any difference operations or more details?

Thanks.

**Comment by fds-sj** [comment]
1. Whether your workbook just created and do nothing on it? 
        - also happens on already existing workbooks with named ranges
2. Your build number of excel online, go File->About->build. (Like 16.0.15310.35903)
        - 16.0.15310.31876
3. By my video, any difference operations or more details?
        - based on the video, it seems that the focus is not being stolen by the worksheet, however, it still seems that the focus is being removed from the taskpane indicated by the blue highlight around the select button disappearing. If that's the case, this still messes with keyboard-only user workflows. Can we verify if the focus stays/switches after selecting named ranges by pressing tab to cycle to other buttons on the taskpane?

**Comment by yuc014** [comment]
Yes, the focus is removed from the taskpane when I only use my keyboard. 
Bug 6050365 has been assigned for tracking this issue. Thanks for reporting this issue.  
Does this issue block your users? If yes, maybe I could give some workarounds for your scenario.

**Comment by fds-sj** [comment]
Yes, this issue blocks users who rely on keyboard-only workflows. We already have a workaround for this, but still filed the issue for it to be properly resolved. Thank you for addressing the issue. 

Regarding tracking of Bug 6050365, how would we be able to know if the issue has been resolved already so that we could test?

**Comment by yuc014** [comment]
Hi @fds-sj, this is an internal bug, you could not track it directly. 
Will update here when we fix it.

**Comment by fds-sj** [comment]
Okay, I see. Thanks for the quick responses! Will look forward to the update.
