### ISSUE TITLE
Excel JavaScript Api Custom function with custom type paramter

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/office-js#2578]
I am trying to implement Excel custom function with Script Lab.

I tried code below:

```
/**
 * 返回米可爱分享
 * @customfunction
 * @param {MeekouType} input
 */
function meekou(input: MeekouType) {
  return input;
}

export enum MeekouType {
  Phone = "Phone",
  Email = "Email",
}
```
There is no type smart pips for @param.

Here is my screenshot.

![](https://i.stack.imgur.com/ZvvZk.png)

I prefer it will have message for enum like below

![](https://i.stack.imgur.com/wZSgg.png)

**Comment by grangeryy** [comment]
Hey @Edward-Zhou, the Custom Function doesn't support this. We suggest you to [Microsoft 365 Developer Platform - Microsoft Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) so this could be tracked more easily.
