### ISSUE TITLE
Outlook's 365 RoamingSettings doesn't allow storing 2 Mb of settings

### ISSUE THREAD

**Issue by ox4** [OfficeDev/office-js#258]
Hello guys!

According to [Office.RoamingSettings interface documentation](https://docs.microsoft.com/en-us/javascript/api/outlook/office.roamingsettings?view=office-js) a maximum of 2 Mb is available for the settings of each add-in, and each individual setting is limited to 32 Kb.

## Expected Behavior
RoamingSettings should allow storing up to 2 Mb of settings.

## Current Behavior
Office.js 16.01 does not seem to take into account the size in bytes of each setting. Instead, it limits the settings size based on the characters count taken by all settings without considering the size of each setting.  

## Steps to Reproduce, or Live Example
The Add-in loads Offect.js from https://appsforoffice.microsoft.com/lib/1/hosted/office.js
Given the roaming settings are empty.
  1. Add a setting with key "key1" and a value containing ~30kb of data.
I used this function to generate that much data:
```javascript
function generateStringOfSizeInKb(size) {
      // size of 'a' char in UTF-8 is 1 byte so repeating 'a' N*1024 times gives a string of N Kb
      var numberOfAChars = size * 1024;
      return new Array(numberOfAChars + 1).join('a');
 }
```
  2. Add a setting with key "key2" and a value containing ~30kb of data.
  3. Call `Office.context.roamingSettings.saveAsync()`
The last step returns the following error in the callback
![chrome_2018-09-26_17-02-26](https://user-images.githubusercontent.com/11349411/46130488-20e04980-c242-11e8-905d-441f08fd08c8.png)

I have inspected `Office.context.roamingSettings.saveAsync()` function (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-web-16.01.js) and found the following condition:

![chrome_2018-09-27_10-53-35](https://user-images.githubusercontent.com/11349411/46131155-a1537a00-c243-11e8-8a8e-2caaaaed998b.png)

`u.DDA.SettingsManager.serializeSettings(this.get__data$p$0()` returns the object with all settings with the following structure:
```javascript
{ key1: "value1", key2: "value2" }
```

So `window.JSON.stringify(u.DDA.SettingsManager.serializeSettings(this.get__data$p$0())).length > 32768` seams to mean that **the number of chars in JSON representation of JS object with all the roaming settings cannot be greater than 32768** and I can't find any ways to fill the roaming settings up to 2 Mb. 

## Context
I'm working on an Outlook 365 Add-in with the requirement to use RoumingSettings to store quite a lot user's data. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook 365
* Office JS version number: 16.0.10910.10000
* Operating System: Windows 10
* Browser (if using Office Online): Chrome 69

## Useful logs

- [x] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Please let me know if any further details are required. 
Thanks in advance.

**Comment by exextoc** [comment]
The limit is actually 32KB for the serialized object/data. The 2MB limit in our documentation is inaccurate. We will get the documentation fixed. To store quite a lot of user's data, we recommend using a service.

**Comment by ox4** [comment]
Thank you.
