### ISSUE TITLE
Error on getByNamespace("") in Word

### ISSUE THREAD

**Issue by roskam** [OfficeDev/office-js#2580]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 365 (version 2205)
* Operating System: Windows 10
* Browser (if using Office on the web): Edge__
 
## Expected behavior

Is expected to receive the customxmlparts with no namespace defined, as does the getByNamespaceAsync("") which gives me the correct result
## Current behavior

I receive an error:
[ERROR]: Error:
{
    "stack": "RichApi.Error: InvalidArgument\n    at new n (https://appsforoffice.microsoft.com/lib/beta/hosted/word-win32-16.01.js:26:244812)\n    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/beta/hosted/word-win32-16.01.js:26:309146)\n    at https://appsforoffice.microsoft.com/lib/beta/hosted/word-win32-16.01.js:26:307208",
    "message": "InvalidArgument",
    "name": "RichApi.Error",
    "code": "InvalidArgument",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "InvalidArgument",
        "message": "InvalidArgument",
        "errorLocation": "CustomXmlPartCollection.getByNamespace",
        "statement": "var byNamespace = v.getByNamespace(...);",
        "surroundingStatements": [
            "var v = context.root._getObjectByReferenceId(\"J!00000015\");",
            "// >>>>>",
            "var byNamespace = v.getByNamespace(...);",
            "// <<<<<",
            "// Instantiate {byNamespace}",
            "byNamespace.getCount();"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 400

## Steps to reproduce

This is the code I used. This code works fine if the namespace is not empty
async function run() {
  await Word.run(async (context) => {
    const body = context.document.body;
    const customXmlParts = context.document.customXmlParts;
    const filteredXmlParts = customXmlParts.getByNamespace("");
    console.log("customxmlparts", filteredXmlParts);
    const numberOfPartsInNamespace = filteredXmlParts.getCount();
    await context.sync();
    console.log("aantal customxmlparts", numberOfPartsInNamespace);
}

## Link to live example(s)
https://gist.github.com/roskam/8e9cadc1901e7b14630231f95cc99f81.js

1. ______
2. ______
3. ______

# Provide additional details

1. You need to add a customxmlpart to the testdocument, with no namespace added to it
2. ______
3. ______

## Context

I'm trying to rewrite an addin with typescript for a Q&A taskpane, the questions and answers are saved in/to  a customxmlpart with the document. So that the questions and answers can be used to know how the document was build

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by grangeryy** [comment]
@roskamm, based on [API documentation](https://docs.microsoft.com/en-us/javascript/api/excel/excel.customxmlpartcollection?view=excel-js-preview#excel-excel-customxmlpartcollection-getbynamespace-member(1)), getByNamespace(namespaceUri: string), the parameter must be a fully qualified schema URI; for example, "http://schemas.contoso.com/review/1.0".

**Comment by roskam** [comment]
But that is a change of functionality because in the past (in vsto but also in the function getByNamespaceAsync) it was also possible to set the namespaceUri to an empty string (so that you could get a customxmlpart with no fully qualified schema Uri set.
