### ISSUE TITLE
Some O365 account have issue with ideas task pane and blank

### ISSUE THREAD

**Issue by Refinitiv-365** [OfficeDev/office-js#2581]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac  on the web , PC on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Excel online build version 16.0.15310.31876
* Operating System: Window, Mac
* Browser : All
 
## Expected behavior

- It should not show ideas task pane because It show pop up login add-ins 
- if open new sheet could not show ideas task pane while click login add-ins  

## Current behavior

https://user-images.githubusercontent.com/98725157/168019798-717b2196-1fa7-4be9-ac16-05838da182f9.mp4

## Steps to reproduce

1. upload Refinitiv add-ins 
2. click sign in 
3. show pop-up add-ins for sign in and show ideas task pane
4. if open new sheet it show ideas task pane while click sign in 

# Provide additional details

1. this issue occur by user to sign in another device it will be found as well. 
2. if sign in done, this ideas task pane open. 

# Question
1. why is this issue only found on some account?

**Comment by preethikakiru** [comment]
Hi @Refinitiv-365, I was wondering if you could give me more context on what the expected behavior should be?

**Comment by preethikakiru** [comment]
@Refinitiv-365 Hi, I attempted to reproduce this issue, but whenever I click sign-in it pops up the taskpane with the log-in instructions (which I am assuming is the expected behavior) and even when traversing through sheets the taskpane on the side remains the same unless I go make changes. Can I assume that this issue has been resolved?
