### ISSUE TITLE
Allow Multiple Separate Add-ins to Share a Single Ribbon Group/Tab

### ISSUE THREAD

**Issue by PawluMuscat** [OfficeDev/office-js#2582]
There currently isn't a way for grouping multiple add-ins together, meaning you have to have separate tabs and groups for each add-in you create. This ends up with the over population of the ribbon and an awful end user experience if they're using multiple add-ins that could easily be grouped together in their own tab/group if it was possible. 

If it was possible to have a unique group ID that we could place in the manifest files of each add-in that would check to see if that group already exists, placing it there if it does, or creating the group if not. It would allow for much nicer UX design and be highly beneficial. Whilst also not allowing for other add-ins to accidentally/maliciously take over the tab/group. 

The XML CustomUI method that exists is a good example of this, allowing for shared groups of custom controls. If this could hook into the same system it would also allow for the co-existence of custom controls with the Agave controls which could also be beneficial if they're commonly used together. (As illustrated below)
![CustomGroup](https://user-images.githubusercontent.com/36282780/168080557-53f3ddb9-4d96-4144-a81d-24dcc192c0ac.png)

**Comment by jeremy-msft** [comment]
Currently the feature you requested is not a part of the product. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. Thanks, Microsoft 365 Developer Platform team
