### ISSUE TITLE
[Outlook Deeplink] Impossible to send "<" and ">" through deeplink

### ISSUE THREAD

**Issue by IQbrod** [OfficeDev/office-js#2584]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC using Office web
* Host [Excel, Word, PowerPoint, etc.]: Outlook/Calendar
* Office version number: latest (browser)
* Operating System: Windows
* Browser (if using Office on the web): Chrome 101.0.4951.64
 
## Expected behavior
I would like to create an event with such name using deeplink
`Daniel <> Peter`

## Current behavior
Does result in 
`Daniel &lt;&gt; Peter`

## Steps to reproduce
Use one of these links 
- https://outlook.office.com/calendar/0/deeplink/compose?rru=addevent&path=%2Fcalendar%2Faction%2Fcompose&subject=Daniel%20%20%3C%3E%20Peter
- https://outlook.office.com/calendar/0/deeplink/compose?rru=addevent&path=%2Fcalendar%2Faction%2Fcompose&subject=Daniel%20%20<>%20Peter

## Link to live example(s)
-

# Provide additional details
It looks like encoding problem

## Context
We're trying to generate interviews on outlook without account through deeplink, we have some clients using outlook only.
We are stuck with these characters as it represents 1<>1 interviews.

## Useful logs
-

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @IQbrod. Connecting you with @exextoc who may be able to help.

**Comment by exextoc** [comment]
Hi @IQbrod, could you please let us know if you're trying to use the deeplink from an add-in?

**Comment by IQbrod** [comment]
@exextoc users click on div which triggers a js script
`window.open("https://outlook.office.com/calendar/0/deeplink/compose?rru=addevent&path=%2Fcalendar%2Faction%2Fcompose&subject=Daniel%20%20%3C%3E%20Peter");`

**Comment by janormanms** [comment]
We've elected to Won't Fix this issue as the current handling of the query parameters for opening calendar compose does the extra sanitization step for security and that will be prioritized over special character handling
