### ISSUE TITLE
API to save a value to a workbook

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#2585]
It seems that previously you published an API to save/embed a value to an Excel workbook (rather than the cache of the integrated browser), so that the add-in could get it later.

Could anyone tell me what's the API?

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @chengtie. Connecting you with @guliums who may be able to help.

**Comment by yuc014** [comment]
Hi @chengtie, you can see all our apis on: https://docs.microsoft.com/en-us/javascript/api/excel?view=excel-js-preview

And I guess you want this: https://docs.microsoft.com/en-us/javascript/api/excel/excel.workbook?view=excel-js-preview#excel-excel-workbook-save-member(1)?

**Comment by chengtie** [comment]
> Hi @chengtie, you can see all our apis on: https://docs.microsoft.com/en-us/javascript/api/excel?view=excel-js-preview
> 
> And I guess you want this: https://docs.microsoft.com/en-us/javascript/api/excel/excel.workbook?view=excel-js-preview#excel-excel-workbook-save-member(1)?

"save(saveBehavior)" is not what I wanted.

For instance, an add-in may want to save a value representing **last modified time** of the workbook to that workbook, so that next time the add-in could read that value from the workbook. The add-in does not want to save it to a cell; it seems that there is a "cache" in the workbook we can use.

I'm taking about this API, and I don't think "save(saveBehavior)" could do that.

**Comment by guliums** [comment]
Hi @chengtie , is document custom property API you needed? https://docs.microsoft.com/en-us/javascript/api/excel/excel.custompropertycollection?view=excel-js-preview#excel-excel-custompropertycollection-add-member(1)

**Comment by chengtie** [comment]
> Hi @chengtie , is document custom property API you needed? https://docs.microsoft.com/en-us/javascript/api/excel/excel.custompropertycollection?view=excel-js-preview#excel-excel-custompropertycollection-add-member(1)

Yes, this is what I'm looking for... Thank you.
