### ISSUE TITLE
Defining CustomFunctions from Angular

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#2586]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi,

I tried to find a way to define an excel custom function from within Angular application and it seems to be working on Excel Office running on MacOS, but the issue is that the same manifest file errors on windows and the addin does not get loaded. I tried to fix it but without any luck.

Not sure if it is a bug or I just got it to work by multiple try&error on MacOS, but my questions are:
1. Is there a documented way of defining Custom functions from within Angular ?
2. How does that it works on MacOS, but on Windows the same manifest errors out?

I want this because it will be nice for development as we can use the things we already have in place(services, etc).

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @danielpdev. Connecting you with @guliums who may be able to help.
