### ISSUE TITLE
Item id is reused in e-mail draft or replay

### ISSUE THREAD

**Issue by ksobolewskiVL** [OfficeDev/office-js#2588]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.15128.20158
* Operating System: Windows
* Browser (if using Office on the web): -

## Context
When preparing drafts or replays, we have noticed in some cases that the item id is detected as reused.
How is the item id created? Can an item id return to the pool after it has been sent or in other circumstances?

For received mails we use the internet message id and have not noticed any similar cases.

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @ksobolewskiVL. Connecting you with @exextoc who may be able to help.

**Comment by samantharamon** [comment]
Hi @ksobolewskiVL,

Thank you for your post. To help us investigate this, could we request you to share how you retrieve the item ID? Additionally, would you be able to provide a screenshot of the error (if applicable) when the ID is detected as reused?

For information about identifiers in Exchange, please see [EWS identifiers in Exchange](https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/ews-identifiers-in-exchange).
