### ISSUE TITLE
Office.context.mailbox.item.loadCustomPropertiesAsync not work when second open edit event in Mac os 12.3.1 Outlook 16.58 (22021501)/16.61 (22050700) in New Outlook UI

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#2589]
repro step:
1. open a new event, open an add-in, for example one note, set custom info:
code snap:
set custom info:
```
function setCustomInfo () {
    Office.context.mailbox.item.loadCustomPropertiesAsync((result) => {
        console.log(result);
        let customProps = result.value;
        customProps.set("demo", 'test');
        customProps.saveAsync((asyncResult) => {
            console.log(asyncResult);
        })
    })
}
```
2. check custom info have set. get custom info(custom info existed):
code snap:
get custom info:
```
function getCustomInfo () {
    Office.context.mailbox.item.loadCustomPropertiesAsync((result) => {
        console.log(result);
    });
}
```
![image](https://user-images.githubusercontent.com/1878089/168760059-65e057dc-e293-49f1-b120-b3ec49e389b6.png)

3. save this event.
4. re-open this event and add-in(in here, it's one note add-in).
5. check custom info again:
code snap:
get custom info:
```
function getCustomInfo () {
    Office.context.mailbox.item.loadCustomPropertiesAsync((result) => {
        console.log(result);
    });
}
```
6. get nothing in custom info:
![image](https://user-images.githubusercontent.com/1878089/168760865-e96a2e17-422f-4194-82fa-90fc0fcf1bdd.png)

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @hello-chenchen. Connecting you with @macOutlookExtensibility who may be able to help.

**Comment by exextoc** [comment]
Hi @hello-chenchen, thanks for reporting the issue. It has been put on our backlog. We unfortunately have no timeline to share at this point. Internal tracking id: 6072701

**Comment by exextoc** [comment]
@hello-chenchen Could you please update your outlook to version 16.66 and above and verify if the issue is still reproducible?
