### ISSUE TITLE
is it possible to programmatically add office addin manifest file in an excel file

### ISSUE THREAD

**Issue by shyambhiogade** [OfficeDev/office-js#259]
Hi, 
i have a question.

is it possible to add office addin manifest file in an excel file programatically. 

we are providing a onpremise solution to users. we have created a office manifest file and the office addin is hosted on an internal server, when our product is installed we modify the manifest file to have correct name of hosting server.

to be able to user the office addin, our user need to open the excel and add the shared folder path where the manifest file is available as secure catalog which is lot of manual intervention. 

i want to grammatically add manifest file in excel after the server name is changed in manifest file and then our user will download the excel file and because the manifest file is already integrated, in excel it will start the office addin. 

let me know if its possible to addin office addin through manifest file in an excel programmatically.

**Comment by shyambhiogade** [comment]
@kenotron  @yinaa @craigomatic can you please reply to my query

**Comment by JuaneloJuanelo** [comment]
no this is not possible today.
We also don't recommend to use a file share catalog for deploying your add-in, its certainly possible, but you will lose most of the value of the platform, for instance your add-in will be Windows-only. Will not work in Online or Mac.

IF thats ok with you, here is an article you can try https://social.msdn.microsoft.com/Forums/office/en-US/29081a50-b7bc-44f0-8d4b-c0ddfedb599b/add-app-to-trusted-app-catalogue-in-a-conventient-way
