### ISSUE TITLE
Mac Outlook Language set to Spanish returns es-MX

### ISSUE THREAD

**Issue by thoffmann-fms** [OfficeDev/office-js#2591]
When the per-App language in Language & Region is set to "Español" the locale reported by Office.Context.displayLanguage is "es-MX".  When set to "Español (México)" is it also set to "es-MX".

## Your Environment
Mac OS 12.4, Outlook 16.61 
 
## Expected behavior
"es-ES" should be reported for Español

## Current behavior
Office.Context.displayLanguage is "es-MX"

## Steps to reproduce
Set app-specific language for Outlook in Language & Settings to Español and launch Outlook.  Execute an add-on and check the value of Office.Context.displayLanguage

## Context
Took some extra debugging time to see that es-MX needed to be in the Manifest.xml file for the Add-In.  Everything worked fine for Windows Outlook and OWA.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @timothyhoffmann. Connecting you with @macOutlookExtensibility who may be able to help.

**Comment by exextoc** [comment]
@timothyhoffmann we are unable to reproduce this issue. Could you please share a video with us reproducing the same?

**Comment by thoffmann-fms** [comment]
I think the problem is that I didn't restart the browser after changing the language.  While some of the text displayed is in the selected language and API doesn't reflect the change without a restart.
