### ISSUE TITLE
Meeting created with google addon does not display correctly on MAC outlook

### ISSUE THREAD

**Issue by echowwl** [OfficeDev/office-js#2592]
repro step:
**1. schedule an event via google calendar using google meet video conferencing**
![image](https://user-images.githubusercontent.com/105787768/169025263-fe37133e-9000-4912-a97d-dafa659ae4ae.png)
**2. invite a google email as a guest then click save
3. go to the outlook application
a.open the event at the old UI outlook calendar:**
![image](https://user-images.githubusercontent.com/105787768/169027092-e0b03517-af87-47d4-a5c6-3faa010cc3df.png)

**b.double click the event:**
![image](https://user-images.githubusercontent.com/105787768/169027124-d24fdbc3-b129-41db-b522-304af7771b21.png)

**c.open the event at the new UI outlook calendar:**
![image](https://user-images.githubusercontent.com/105787768/169027324-5727cadd-3be0-42a3-b2aa-9b143ce37f0e.png)

**d.double click the event:**
![image](https://user-images.githubusercontent.com/105787768/169028408-672e3a6c-53a3-41c6-be54-5d6b2101080b.png)

**4.if I schedule an event via google calendar using zoom addon:
a.open the event at the new UI outlook calendar:**
![image](https://user-images.githubusercontent.com/105787768/169027942-29ad3fff-6636-4b86-b701-16ca24be7e4c.png)

**b.when i click the "join" button, get the error:**
![image](https://user-images.githubusercontent.com/105787768/169028008-56bbe774-6771-4cc2-9f3a-23eb5a5195b2.png)

**c.double click the event:**
![image](https://user-images.githubusercontent.com/105787768/169028065-f71a026f-04ad-40cc-8b08-61c3b910d6d5.png)

**Comment by exextoc** [comment]
Hi @echowwl, form the details shared it seems like you're using the old UI. Please check with the new UI if this works for you. We are not fixing bugs for the old UI.

**Comment by echowwl** [comment]
The same is the case when I test it on the new UI.
![image](https://user-images.githubusercontent.com/105787768/170901886-c47e6ad9-fe41-4129-b8f4-310158635a29.png)

**Comment by exextoc** [comment]
@echowwl Are you using any add-in in the outlook app?

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.

**Comment by echowwl** [comment]
Sorry, I still have this problem

**Comment by echowwl** [comment]
Please help me reopen this ticket

**Comment by JasonKeirstead** [comment]
Reopen. Still broken. Google Meet invites on MacOS Outlook have no join button, regardless if the add-in is installed or not.

This auto-closing of unresolved issues is annoying.
