### ISSUE TITLE
[Outlook] location.getAsync get a strange result when using 'Scheduling Assistant' on Mac Outlook (New UI)

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#2593]
On Mac Outlook, using 'Scheduling Assistant' add a location 'sanjuZR'. Then use location.getAsync will return 'sanjuZR; sanjuZR'. The correct result should be only one 'sanjuZR'. 
But on create event interface there is only one 'sanjuZR' in location. 
![image](https://user-images.githubusercontent.com/15980696/169189936-36e98d8a-58a6-424d-9a99-327cee50f7e6.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook (new UI)
* Office version number: 16.55 (21111400)
* Operating System: 10.15.7
* Browser (if using Office on the web): ______
 
## Expected behavior
location.getAsync should return only one 'sanjuZR'.  

## Current behavior
Will return 'sanjuZR; sanjuZR'.

## Steps to reproduce

1. create a new event under Mac outlook new UI
2. use 'Scheduling Assistant' insert a location
3. get location by API 'location.getAsync'

**Comment by exextoc** [comment]
Hi @SWei1234, we are not able to repro this scenario at our end. Could you please update to the latest version of Mac Outlook and check if this issue still exists. If yes, then kindly share a video of the same that will help us to investigate the issue quickly.

**Comment by SWei1234** [comment]
Hi @exextoc 
Yes, sure I will try update my Outlook. But can you share me the outlook version which not repro this problem? This will be a reference standard for me. Thanks

**Comment by SWei1234** [comment]
Hi @exextoc 
    And one more problem about this api. 
    Steps: 
    1. switch outlook to new UI
    2. open a new event then add a location(BOSS A). 
    3. Get this location by 'location.getAsync' API then use 'location.setAsync' set it back. 
     Expected: 
    BOSS A's calendar should receive this event.
    Actually: 
   BOSS can not get this event. 
   
   I tried this on new version Outlook (16.61 22050700) . And this problem still show up. 
   And I notice that when I manually insert a location, the 'Save' button become 'Send'. But After use 'location.getAsync' and  'location.setAsync', the button will back to 'Save'. This is very strange. 
Screenshot: 
![image](https://user-images.githubusercontent.com/15980696/169749410-dda70df3-ebb8-4a8a-b133-5e0d59591aa3.png)
Here I insert location manually. 
![image](https://user-images.githubusercontent.com/15980696/169749475-c3d83c0e-3c15-4554-8ef1-b871279f1a79.png)
But in this picture, it's become a save button... 

   Can you try this problem? And I replicate this problem only on Mac Outlook new UI.

**Comment by exextoc** [comment]
@SWei1234 we are unable to reproduce the issue you have mentioned with the BOSS A value. It works fine on our end.

Try using the below code snippet and see if the issue is still reproducible.

`Office.context.mailbox.item.location.getAsync(res=>{ Office.context.mailbox.item.location.setAsync(res.value, res2=>{console.log(res2);});});`

**Comment by SWei1234** [comment]
Hi @exextoc 
  I tried this on another Mac and running your code. This problem still exist. 
  Mac version (12.3.1)  Outlook 1658 (22021501)
  I will try attach a recording later to show how replicate this problem. Hope this will help you.
Thanks

**Comment by SWei1234** [comment]
Hi @exextoc 
    Any update? Or anything else I can provide for you?
Thanks

**Comment by exextoc** [comment]
@SWei1234 Could you please attach a recording for the issue? Thanks.

**Comment by SWei1234** [comment]
@exextoc 
Sure. But can I share this with you by an email? It's will be hard for me share a recording on github...
Can you provide me a temp email address? 
Thanks

**Comment by exextoc** [comment]
@SWei1234 Please use email: OutlookAddins@M365x693897.onmicrosoft.com

**Comment by exextoc** [comment]
We have not received any communication from you on this thread or on our email. We are closing this from our end.

**Comment by SWei1234** [comment]
> We have not received any communication from you on this thread or on our email. We are closing this from our end.

Sorry for reply late. I have send the recording to [OutlookAddins@M365x693897.onmicrosoft.com](mailto:OutlookAddins@M365x693897.onmicrosoft.com). Please check the attachment. Thanks

**Comment by SWei1234** [comment]
Hi @exextoc  
    Have you received the mail? Or need I send the recording again?
Thanks

**Comment by SWei1234** [comment]
Hi @exextoc 
   Need I share you more recording? Or anything else need I supply?
Thanks

**Comment by SWei1234** [comment]
Hi @exextoc  
   We receive more ticket about this issue ? Any update?
   This problem can even replicate on OWA. 
Thanks

**Comment by exextoc** [comment]
Hey @SWei1234 

We have the repro video and working on the repro. 
We'll get back to you in some time around it. 

Thanks a lot for your patience.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding undesirable behaviour of location.getAsync. We are able to reproduce the problem. It has been put on our backlog. We unfortunately have no timelines to share at this point
 
Internal tracking id: Office: [6278732]

**Comment by SWei1234** [comment]
Hi @exextoc  
    Actually we tried 'Office.context.mailbox.item.enhancedLocation' API. It looks working good on Mac Outlook NEW UI. But I'm not sure this is the final solution. Can you help me confirm this with develop team? 
Thanks

**Comment by exextoc** [comment]
We are going to make sure that location.getAsync returns proper value as this API is not deprecated. EnhancedLocation allows get/set a set of locations. You can go ahead and use it.
