### ISSUE TITLE
Error while adding data validation rule

### ISSUE THREAD

**Issue by libjosep** [OfficeDev/office-js#2594]
I am getting an invalid argument exception when I try to add a data validation rule to a range in excel. I am initially setting a data validation prompt for a range of cells(Eg: B5:B10). In the next step, I am adding a data validation prompt to a range that contains the initial range I picked for the data validation prompt(Eg: B1:B10). Then I set data validation rule using 
`range.dataValidation.rule = {
      list: {
        inCellDropDown: true,
        source: "Item 1, Item 2"
      }
    };` 
At this point, I am getting an error saying `The argument is invalid or missing or has an incorrect format.`

If I set prompt before rule, it will work. Please see the attached scriptlab sample.
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 365
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

It should set data validation rule for the range specified.

## Current behavior

Throwing exception.

## Steps to reproduce

1. Run the attached scriptlab sample
2. Click the button"Set rule After Prompt"
3. Check console to find the exception

## Link to live example(s)

1. [Scriptlab sample](https://gist.github.com/libjosep/cd821b54fd216f61b2cf7cdd977189da)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @libjosep. Connecting you with @JHJ-MS who may be able to help.

**Comment by guliums** [comment]
Hi @libjosep, thanks for reporting this. Currently this API does not support ranges with different rules on different cells. If B5:B10 already has data validation, you could set data validation rule to B1:B4 and B5:B10 in two API calls as workaround. If you need that functionality, you could go to [Microsoft 365 Developer Platform Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) and see if this feature has already been requested or request a new feature. Thanks for your support!

**Comment by libjosep** [comment]
In my case, I can have n number of ranges to set data validation prompts and another n number of ranges to set prompts. My current approach is like this - I have an array of ranges to set data validation rules and another array of ranges to set data validation prompts. First I set data validation prompt for all the ranges. In the next step, I set data validation rules to all the ranges. So comparing them to check overlapping will be difficult for me.

After I change my execution order to set data validation rules first and then prompts, this error is not coming. Can I go ahead with this workaround?

**Comment by guliums** [comment]
Hi @libjosep , I think it is not related to the order of rules or prompts, but depends on the range size in each steps. If you set data validation rules to a small range(like B5:B10), then set prompts on a large range(B1:B10), it will not work. Because currently both set rule or prompt do not support ranges with already existing different rules on different cells. If you don't see errors after change the order, I think it should be good workaround.

**Comment by libjosep** [comment]
As @guliums said, this depends on the range size. It is difficult to split ranges based on overlap condition since I have too many ranges to check. Since it works if we divide in to small ranges, can you fix it without splitting the ranges?
