### ISSUE TITLE
excel-online(office-dialog-api): lost worksheet focus after closing Office dialog

### ISSUE THREAD

**Issue by fds-rpg** [OfficeDev/office-js#2596]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

the focus on the worksheet is lost after you close the Office dialog.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows 10
* Browser (if using Office on the web): Google Chrome
 
## Expected behavior
the focus should be in the worksheet and keyboard keys should work to interact in the worksheet

## Current behavior
After selecting a cell using Office dialog and closing it, the focus is not pointed in the worksheet anymore.
![Animation4](https://user-images.githubusercontent.com/105926601/169547985-25ec4254-83e3-4fbb-ade4-53b520fee236.gif)

## Steps to reproduce
1. Download [dialog-api-focus-bug](https://github.com/fds-rpg/dialog-api-focus-bug) repository
2. To serve, run `yarn install`, then run `node serve.js`.
3. Open Excel web, then click "Office add-ins" on Insert Tab from tab list
4. click "upload my add-in" and select `manifest.xml` file from the repo folder
5. click test addin from tab list and click "open dialog" button from the taskpane

**Comment by JHJ-MS** [comment]
Thank you for sharing this issue, and connecting you with @AbidRahman-MSFT who may be able to help.
