### ISSUE TITLE
Worksheet.WorksheetProtection.protect() method fails if any parameter is passed

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js#26]
If the method in the title is called with a parameter, it always throws : “InvalidArgument: The argument is invalid or missing or has an incorrect format”.

## Expected Behavior
The method should protect/unprotect the sheet in accordance with the options passed in the WorksheetProtectionOptions object.

## Current Behavior
If any WorksheetProtectionOptions object is passed to the method, it throws “InvalidArgument: The argument is invalid or missing or has an incorrect format”.

## Steps to Reproduce, or Live Example
* Link to live example: 
Our own snippet in our own reference topic fails with exactly this error: https://github.com/OfficeDev/office-js-docs/blob/ExcelJs_OpenSpec/reference/excel/worksheetprotection.md

## Context
I need to be able to selectively protect the worksheet from some user actions, but not all. This requires a WorksheetProtectionOptions parameter.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1712, 8801.1000 Click-to-run 
* Operating System: Win 10
* Browser (if using Office Online):N/A

**Comment by Zlatkovsky** [comment]
We found out about that one just a few days ago.  It's an issue that hasn't rolled to the main public yet (it's starting in October fork and in internal builds).  Good news is that we can fix this at the JS layer, so a fix is forthcoming.

**Comment by Zlatkovsky** [comment]
Fixed in the EDOG environment, will be going out to production in a week or two.
@Rick-Kirkham , if you are on corp-net, it will redirect to EDOG automatically, so the snippet should now "just work"
