### ISSUE TITLE
How to 

### ISSUE THREAD

**Issue by jlara005** [OfficeDev/office-js#2600]
Hi,

Is it possible to change the position of an Outlook Add-In Icon to appear at the beginning or to make it "pin to ribbon" using the manifest? We have users who are complaining that it is hard to find and bad user experience having to click the ellipsis to get to it.

![image](https://user-images.githubusercontent.com/29823126/170112369-8a61d4f1-383a-40e6-bd2e-f2c8a9a8c369.png)

**Comment by timwan10** [comment]
There currently isn't an option in the manifest to move the ribbon button. 

A User could switch to Classic Ribbon, that usually allows for more horizontal space on the ribbon: 

![image](https://user-images.githubusercontent.com/17890744/170142935-1a34b3ce-6939-4c7a-b6ca-570bc49b94c1.png)

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
