### ISSUE TITLE
Context Multiple Menu is not working on Excel Desktop

### ISSUE THREAD

**Issue by sachin161194** [OfficeDev/office-js#2601]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# [OfficeMenu multiple menu controls works on office 365 not on office desktop ](https://techcommunity.microsoft.com/t5/excel/officemenu-multiple-menu-controls-works-on-office-365-not-on/m-p/3412863) 

We have updated the manifest file with "officeMenu" multiple menu controls work on office 365, not on the office desktop
We are using Office Js to develop a context menu.

Already raised a concern in Microsoft Dev community channel but got no success.
Not sure what I'm doing wrong here.  Please help!

More info on manifest file
https://docs.microsoft.com/en-us/answers/questions/859215/officemenu-multiple-menu-controls-works-on-office.html

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 365
* Operating System: windows 10
* Browser (if using Office on the web): ______
 
## Expected behavior

As it mentioned in the documentation ,We can add multiple Context menu on right click whether its a excel Desktop or Excel Online.
So when we add multiple Context Menu control in manifest then it needs to reflect in Excel Online as well in Excel Desktop

## Current behavior

Currently after adding multiple context menu Control on manifest.Its working fine in Excel online but same is not working in Excel Desktop. As you can see below in screenshot ,"Odata Integration" Menu is missing from Excel Desktop Right click menu 

![image](https://user-images.githubusercontent.com/92863921/170265476-694d833a-0bc2-456f-8ccc-8ad9fdb35589.png)

## Steps to reproduce

1. ______ Just add multiple Context menu control in manifest
2. ______ upload manifest in excel desktop & in excel Online
3. ______ Its not working in excel Desktop

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by trigurl** [comment]
Hello, the Desktop behavior is actually correct.  Per intended design, we only allow an add-in to add either a button control or a menu control to a context menu.  At the time it was designed this way so that the Office context menu doesn't get flooded with 3rd party controls. Within your menu, you can only have buttons at the moment.

Unfortunately, we are aware of some inconsistencies between Online and Desktop client.  This is one of them.  in your situation I would refer to the desktop behavior of putting one menu into the context menu, then adding all your buttons into the menu.

**Comment by sachin161194** [comment]
Hi @trigurl ,
Thanks for the suggestion : **_I would refer to the desktop behavior of putting one menu into the context menu, then adding all your buttons into the menu_**

I am not able to group the child element here of the menu ,Group element is not working in the context menu section of manifest.

 Please suggest how to bifurcate into two groups of child inside menu.

Like below horizontal split between 2 sections :- 

![image](https://user-images.githubusercontent.com/92863921/171092352-e5fa1da5-15ca-4291-8b9d-92550ff26081.png)

There is not much resource available on documentation for same.
Please help :)

**Comment by ElizabethSamuel-MSFT** [comment]
@trigurl Do you have any suggestions for the user to get past this? Thanks.
