### ISSUE TITLE
I am wondering if outlook web add-ins can be mobile and move around the screen similar to what old microsoft com add ins used to do and not just be docked to one location in the application,

### ISSUE THREAD

**Issue by paulflaherty555** [OfficeDev/office-js#2602]
I am wondering if outlook web add-ins can be mobile and move around the screen similar to what old microsoft com add ins used to do and not just be docked to one location in the application,

**Comment by nancy-wang** [comment]
Thanks for the question @paulflaherty555 ! Tagging @exextoc who may be able to help answer.

**Comment by exextoc** [comment]
Currently, the feature of moveable add-ins is not part of the product. We have fixed task pane add-ins. 
We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

Github Label: “Type: product feature request”
https://[aka.ms/M365dev-suggestions](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FM365dev-suggestions&data=04%7C01%7CDaniele.Bercovici%40microsoft.com%7C82496bc384404255bc6808d8fe1fde30%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637538760227690968%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9visic2Ti%2FATFoVGDNcvO86URULWWtAvqsNRK%2BH37G8%3D&reserved=0)

[Outlook Add-ins Engineering Team]

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
