### ISSUE TITLE
All Word 2016 add-ins erroneously auto-open, doesn't respect "Office.AutoShowTaskpaneWithDocument", sets taskpane visibility to "1"

### ISSUE THREAD

**Issue by jamding** [OfficeDev/office-js#2603]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Original post on [Stackoverflow](https://stackoverflow.com/questions/72374813/all-word-2016-add-ins-erroneously-auto-open-doesnt-respect-office-autoshowtas), on which I was recommended to file a bug report.

I've observed that O365 is consistent with the [docs](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document) on "Auto Open" behavior for Office.js taskpanes, but W2016 is not, so I'm wondering if this is a bug or if there's alternate instructions I should refer to.

I've tested this with my add-in, a newly created word add-in (template), and the Wikipedia add-in on the store.

## Your Environment
Described observations tested on AWS Workspace build of O2016 and 2 other versions on Windows ("MSI" version). Also tested on O365 Mac OS.

## Expected behavior
I expect W2016 behavior to be consistent with O365 behavior, which is consistent with the documentation.

## Current behavior

Word documents saved in W2016 while an Office.js taskpane is open will auto-open, even if `Office.AutoShowTaskpaneWithDocument` is absent or set to false. This is because visibility is set to "1" in `word/webextensions/taskpanes.xml` (whereas its set to "0" in O365). For users who don't have the add-in installed, any document saved with the add-in open (even those with auto open absent or set to false) will show a blank add in. 

## Steps to reproduce

1. Install wikipedia add-in on W2016
2. create new word doc and open wikipedia add-in
3. save word doc and send to other computers to open and observe behavior

## Context
Customer's organization with considers the W2016 behavior unacceptable and is planning to remove all add-ins unless I can find a solution.

**Comment by nancy-wang** [comment]
Thanks for letting us know about this issue @jamding! Tagging @grangeryy who may be able to help.
