### ISSUE TITLE
Backspace causes navigation in React Word Addin

### ISSUE THREAD

**Issue by cwil423** [OfficeDev/office-js#2604]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment
Macbook Pro (M1)
React App
Word Addin
 
## Expected behavior
When a user uses the backspace key, it does nothing when a user is not typing in an input field

## Current behavior
Pressing the backspace key causes react to navigate to the previous url.

**Comment by nancy-wang** [comment]
Thanks for raising this issue with our team @cwil423! Tagging @grangeryy who may be able to help out here.

**Comment by cwil423** [comment]
I've disabled this in most cases by adding 
`<script>
      window.onkeydown = function(e) {
        if (e.keyCode == 8 && e.target == document.body)
          e.preventDefault();
      }
    </script>`
But the issue still persists when selecting from a dropdown.
I've tried to console.log(e) when hitting backspace after opening the dropdown but nothing gets logged.

**Comment by ElizabethSamuel-MSFT** [comment]
@wangyun-microsoft Can you take a look?

Thanks.
