### ISSUE TITLE
A table in this document has become corrupted error thrown when ".insertOoxml with Replace" a sample text into a content control that has a table

### ISSUE THREAD

**Issue by cebrotea** [OfficeDev/office-js#2606]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I have created a document which contains 2 content controls:
**tableCC** - which contains a sample table
**textCC** - which contains a sample text

I created a gist that gets the ooXML content of the textCC
let textCCContent = textCC.getFirstOrNullObject().getRange("Content").getOoxml();

and this content is inserted using Replace in the content control that has the table.
tableCC.getFirstOrNullObject().getRange("Content").insertOoxml(textCCContent.value, Word.InsertLocation.replace);

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2108 (Microsoft Word for Microsoft 365 MSO (16.0.14326.20850) 64 bit)
* Operating System: Windows 10 Pro 10.0.19044 Build 19044
* Browser (if using Office on the web): ______
 
## Expected behavior
The **tableCC** contentcontrol should not contain any reference to the table, because we are replacing the entire cc content with a sample text, and no table should get corrupted.

## Current behavior
An error popup is thrown saying that "A table in this document has become corrupted"
The content of the **tableCC** contains a table with a cell and in that cell the value of the **textCC** 

## Steps to reproduce

1. Open the testTableText.docx
2. Import the gist https://gist.github.com/cebrotea/e3799d1a23698aa0e0e08ab7a8730b70
3. Click the button that will get the content and replace the table cc with it

## Context

I am trying to update document parts with ooxml content

## Useful logs

![image](https://user-images.githubusercontent.com/25769865/171006239-93ade1b1-c915-460c-a7d1-b78ee866cf2c.png)
![image](https://user-images.githubusercontent.com/25769865/171006361-30004d68-ff83-425d-af13-9d5c3afe8b9d.png)
![image](https://user-images.githubusercontent.com/25769865/171006511-89fb1ceb-59d3-4c1a-a773-cba6a219da0b.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 
[testTableText.docx](https://github.com/OfficeDev/office-js/files/8798855/testTableText.docx)

**Comment by cebrotea** [comment]
anyone looking into this, any updates ?

**Comment by xuruiyao-msft** [comment]
@cebrotea 
Thanks for reporting . We have created an internal work item 6115670 on it. We will keep track of this issue and let you know if there are any updates.

**Comment by cebrotea** [comment]
Thank you!

**Comment by cebrotea** [comment]
Hey guys, any progress with this one? it has a huge impact on us since we work with a lot of tables and we could not find any workaround yet

**Comment by jipyua** [comment]
@cebrotea , by looking at the document you provided we found that actually we should disable this kind of "Replace" operation on this kind of content control. As this content control only contains partial of the table and removing/replace it's content will leave the table with an incomplete structure, and thus the error you saw. So what we are going to do is similar as "InsertText" with "Replace" option on this content control which will throw "GeneralException" which means we shoud forbid this kind of operations.

**Comment by cebrotea** [comment]
The table content control contains full table, not part of table as you can see in the document.xml of the document
![image](https://user-images.githubusercontent.com/25769865/208367777-bebbb87c-74e6-4a26-923a-3a915974c421.png)

**Comment by jipyua** [comment]
In the word rich client data model, it's not exactly same as the ooxml, as you can see from UI, the content control end tag doesn't include the last table cell and table row end tag.

**Comment by cebrotea** [comment]
Then why do we display something else than what we write in the ooxml ? 
Why do we care about ui when we use a method called insertOoxml which should work with ooxml data?
