### ISSUE TITLE
How to access the local file worksheet object in officejs

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/office-js#2607]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am trying to access the excel local from Script Lab.

I am able to insert the worksheets from the local excel file by referening [Insert a copy of an existing workbook into the current one](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-workbooks#insert-a-copy-of-an-existing-workbook-into-the-current-one).
```
// Retrieve the external workbook file and set up a `FileReader` object. 
let myFile = document.getElementById("file");
let reader = new FileReader();

reader.onload = (event) => {
    Excel.run((context) => {
        // Remove the metadata before the base64-encoded string.
        let startIndex = reader.result.toString().indexOf("base64,");
        let externalWorkbook = reader.result.toString().substr(startIndex + 7);
            
        // Retrieve the current workbook.
        let workbook = context.workbook;
            
        // Set up the insert options. 
        let options = { 
            sheetNamesToInsert: [], // Insert all the worksheets from the source workbook.
            positionType: Excel.WorksheetPositionType.after, // Insert after the `relativeTo` sheet.
            relativeTo: "Sheet1" // The sheet relative to which the other worksheets will be inserted. Used with `positionType`.
        }; 
            
         // Insert the new worksheets into the current workbook.
         workbook.insertWorksheetsFromBase64(externalWorkbook, options);
         return context.sync();
    });
};

// Read the file as a data URL so we can parse the base64-encoded string.
reader.readAsDataURL(myFile.files[0]);
```
But, I don't want to insert the whole worksheets, I only need to access the specific worksheet.

How to read the specific worksheet by office-js?

**Comment by JinghuiMS** [comment]
https://docs.microsoft.com/en-us/javascript/api/excel/excel.insertworksheetoptions?view=excel-js-preview#excel-excel-insertworksheetoptions-sheetnamestoinsert-member
![image](https://user-images.githubusercontent.com/56814588/172100689-630b4eab-173b-4c9e-a953-9748b48f7160.png)
You can write specific sheetname. If no, all the worksheets from the source workbook are inserted by default.

**Comment by Edward-Zhou** [comment]
I need to read the content of the local workbook instead of inserting the worksheets to my current workbook.

**Comment by JinghuiMS** [comment]
After you specific sheetname, calling reader.readAsDataURL(myFile.files[0]); should meet your needs.

**Comment by Edward-Zhou** [comment]
@JinghuiMS  Have you tested your suggestion? I need to read specific worksheet? What is meaning by `myFile.files[0]`?

And I don't want to insert worksheet, I just want to read the content.

What do you mean by `After you specific sheetname`

**Comment by JinghuiMS** [comment]
Sorry for that. After I went through API document, we don't have such api now. I'd recommend going to [Microsoft 365 Developer Platform Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) and see if this feature has already been requested or request a new feature. 
We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests are considered when we go through our planning process.

**Comment by tobony** [comment]
.
