### ISSUE TITLE
[PowerPoint API] Unselect the selected TextBox object in PowerPoint slide

### ISSUE THREAD

**Issue by savepong** [OfficeDev/office-js#2608]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Hi There,

When we need to update content for multiple TextBox objects in the same time, it will update only selected object. 
So, We need to unselect the previous updated TextBox. then select another one before update it. 

Hope to get a reply from you ASAP. 🙂

**Comment by mattgeim** [comment]
Hello,

Is this a request for a new API feature?  Or a question on existing API functionality?  https://docs.microsoft.com/en-us/javascript/api/powerpoint?view=powerpoint-js-1.1  is our API documentation page, for reference. 

Thanks!

**Comment by savepong** [comment]
Hi @mattgeim, I requested for a new API feature. It doesn't have in PowerPoint API 1.1 as your mentioned above.
