### ISSUE TITLE
Word Addin content is blocked because it isn't signed by a valid certificate when being IIS hosted in a website having a (*) wildcard certificate.

### ISSUE THREAD

**Issue by cebrotea** [OfficeDev/office-js#2613]
Word addin not loading when is hosted in a website that has a wildcard certificate **( Issued to: *.domain.com)** 
Changing the website certificate to a named certificate **(Issued to: machineName.domain.com)** fixes the problem.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: WORD
* Office version number: 2108 (Microsoft Word for Microsoft 365 MSO (16.0.14326.20850) 64 bit)
* Operating System: Windows 10 Pro 10.0.19044 Build 19044
* Browser (if using Office on the web): ______
 
## Expected behavior

The addin should load no matter if the certificate is issued as a wildcard certificate

## Current behavior

The addin cannot be loaded and it shows the following message: The content is blocked because it isn't signed by a valid certificate

## Steps to reproduce

1. Create an IIS website that has a wildcard certificate ( **( Issued to: *.domain.com)** )
2. Deploy the addin files in the website location
3. Open word and try to open a taskpane that points to the addin

## Context

Hosting the office js addin in a SAAS Environment is not possible because of this issue

## Useful logs

![image](https://user-images.githubusercontent.com/25769865/172184868-53741354-79a8-48ea-9b14-07cca41dd3e0.png)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by samantharamon** [comment]
Thank you for reporting this, @cebrotea. @grangeryy, could you please assist with this? Thank you.

**Comment by cebrotea** [comment]
looks like I will close this one as not reproducible for now. It is reproduced when using self-signed wildcard certificates. Thank you.
