### ISSUE TITLE
Manifest not getting loaded on "Upload My Add-In"

### ISSUE THREAD

**Issue by sahil1504001** [OfficeDev/office-js#2614]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Manifest not getting loaded on "Upload My Add-In" for my organization tenant account

I logged in to office.com using my organization's tenant and for one of the accounts I'm able to upload and load the manifest and for some accounts, it's not loading the manifest.

The manifest insertion is working on Excel but not on PowerPoint for the same account.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: ______
* Operating System: Windows/Mac
* Browser (if using Office on the web): All Browsers
 
## Expected behavior
The manifest should get inserted and loaded on PowerPoint and the user should be able to use the Add-In.

## Current behavior
The manifest is not getting inserted and loaded on PowerPoint, So, unable to use the Add-In application.

## Steps to reproduce - steps I followed for my tenant account.
1. Log in to office.com
2. Open a PowerPoint presentation or create a new one on Browser
3. Insert -> Add-Ins -> Upload my Add-Ins
4. Browse and upload a **validated** manifest.
5. The manifest tab is not loaded in the Tab section.

## Link to live example(s)

1. Not applicable

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by sahil1504001** [comment]
https://user-images.githubusercontent.com/79520782/172312886-0631e5ee-4f7d-4b61-826e-a8103e852160.mp4

**Comment by sahil1504001** [comment]
[manifest.zip](https://github.com/OfficeDev/office-js/files/8850727/manifest.zip)

**Comment by LuyiH** [comment]
Hi, I tried the manifest you attached, and it doesn't work for me also.
It should not relate to the account, can you confirm that the same manifest can work with other accounts?

**Comment by sahil1504001** [comment]
@LuyiH - It's the same manifest, If you want I can provide the recording for the working account as well.

**Comment by LuyiH** [comment]
> @LuyiH - It's the same manifest, If you want I can provide the recording for the working account as well.

Please help with this, thanks

**Comment by sahil1504001** [comment]
@LuyiH - it would insert a button at the end of the current selected Tab. Ex. Home or Insert

**Comment by sahil1504001** [comment]
This manifest is generated using yo office generator.

**Comment by LuyiH** [comment]
> @LuyiH - it would insert a button at the end of the current selected Tab. Ex. Home or Insert

Thanks. I had tried the manifest, it doesn't work for me. I mean the recording with the account that works with this manifest

**Comment by sahil1504001** [comment]
https://user-images.githubusercontent.com/79520782/172540468-7938b30d-6b42-484d-9767-89e37dc773e5.mp4

**Comment by sahil1504001** [comment]
@LuyiH - Please find the recording attached.

**Comment by alok0914** [comment]
@LuyiH Can you please look into the issue, why this is happening its needed on urgent basis

**Comment by ppagadala** [comment]
@LuyiH Facing same issue. Could you expedite this issue as it is blocker for us?.

**Comment by ibratnawaz** [comment]
@LuyiH I'm also facing the same issue.

**Comment by alok0914** [comment]
@LuyiH Same issue for the whole of my team of round 15 people.

**Comment by Wenjun-Gong** [comment]
@shaofengzhu , any manifest expert can help on this?

**Comment by sahil1504001** [comment]
Hello @LuyiH @Wenjun-Gong  @shaofengzhu,

Any updates on the issue?

**Comment by LuyiH** [comment]
Hi @sahil1504001 we are locating and analyzing the issues and will back to share update once we have it

**Comment by sahil1504001** [comment]
Thank you @LuyiH

**Comment by ssnyder-msft** [comment]
@sahil1504001 I've identified the problem and I'm working on a fix. Thanks for your patience.

**Comment by sahil1504001** [comment]
@ssnyder-msft - Ohh great, Thank you soo much!

**Comment by ssnyder-msft** [comment]
> @ssnyder-msft - Ohh great, Thank you soo much!

As a check can you delete your browser cache and ensure your local storage is completely clear and try again. If that fixes your problem please let me know.

**Comment by sahil1504001** [comment]
Hello @ssnyder-msft - I tried as mentioned, but, still it's not working.

**Comment by Hiteshg16** [comment]
Hi @ssnyder-msft I have also tried but still same issue

**Comment by alok0914** [comment]
hi @ssnyder-msft can you please provide some solution to this?

**Comment by sahil1504001** [comment]
Hello @ssnyder-msft, any update on this issue?

**Comment by ssnyder-msft** [comment]
> Hello @ssnyder-msft, any update on this issue?

The fix for this is mostly rolled out. Are you still seeing this issue?

Be sure to clear your local storage:
https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/storage/localstorage

**Comment by sahil1504001** [comment]
It working @ssnyder-msft, Thank you very much!
