### ISSUE TITLE
Outlook javascript add-in does not run when email is encrypted

### ISSUE THREAD

**Issue by t-ariyoshi30907** [OfficeDev/office-js#2618]
I'm providing an add-in in Outlook on the Web, but I'm seeing unexpected behavior when I encrypt my email.

Details are described below.

■Expected behavior

The result dialog is displayed when the "displayDialogAsync" method is executed.

■Current behavior

The result dialog is not displayed even though the "displayDialogAsync" method is executed,and an email was sent.

■Steps to reproduce

1) Download the official sample. 　 　 
https://github.com/OfficeDev/Outlook-Add-in-On-Send/blob/master/outlook-add-in-on-send/Contoso%20Message%20Body%20Checker.xml/
2) Rewrite the contents of the "app.js" file to the source code of following"index.js"
3) Run the "yarn start" command in your local environment.
4) Install the add-in with the manifest file.
5) Write an Email.
6) Click “Encrypt”.
7) Click “Send" button.
This problem always occurs. Please tell me how to solve this problem.

I share this result on video and source code.

■video

https://drive.google.com/file/d/1h3oJSZxObmOXwBw5Z1rjG92U36d9zSFz/view?usp=sharing

■source code

index.js

```
/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
 * See LICENSE in the project root for license information.
 */

var mailboxItem;

Office.initialize = function (reason) {
    mailboxItem = Office.context.mailbox.item;
}

// Entry point for Contoso Message Body Checker add-in before send is allowed.
// <param name="event">MessageSend event is automatically passed by BlockOnSend code to the function specified in the manifest.</param>
function validateBody(event) {
  Office.context.ui.displayDialogAsync(
  "https://localhost:3000/index.html",
    {
      height: 65,
      width: 40,
      displayInIframe: true,
      asyncContext: event,
    },
      (asyncResult) => {
        asyncResult.value.addEventHandler(Office.EventType.DialogEventReceived,
        (processMessage) => {
          asyncResult.value.close()
          asyncResult.asyncContext.completed({ allowEvent: false })
        }
      )
    }
  )
}
```

**Comment by exextoc** [comment]
Add-ins are not activated if the current message item, in a compose or read form, is encrypted. Please refer to the documentation for details.
https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-add-ins-overview?view=common-js-preview#mailbox-items-available-to-add-ins

**Comment by t-ariyoshi30907** [comment]
@exextoc 
thanks for your reply.
The document you shared has the following description. What does this mean?

>Add-ins activate on digitally signed messages in Outlook associated with a Microsoft 365 subscription. 
>On Windows, this support was introduced with build 8711.1000.

I want to use OME and add-ins together.

If I work with the following documents, can I use them together?

■Document url
https://docs.microsoft.com/ja-jp/microsoft-365/compliance/set-up-new-message-encryption-capabilities?view=o365-worldwide

**Comment by exextoc** [comment]
Hey @t-ariyoshi30907 ,

Add-ins support for IRM messages is only limited to those for whom the tenant administrator has enabled the setting "Allow programmatic access" for the users in that tenant. These are not available for Outlook for Live, for instance.

You can find the documentation here: https://docs.microsoft.com/en-us/javascript/api/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview?view=common-js-preview#add-in-activation-on-items-protected-by-information-rights-management-irm

**Comment by t-ariyoshi30907** [comment]
@exextoc 

Sorry, I couldn't understand the explanation.

If I sign in to an admin account with an "Office 365 E3" license and create a mail flow in Exchange Online, will add-ins be supported?

I will read and work on this document.

■Document url
https://docs.microsoft.com/ja-jp/microsoft-365/compliance/set-up-new-message-encryption-capabilities?view=o365-worldwide

**Comment by exextoc** [comment]
@t-ariyoshi30907 Kindly make sure the setting "Allow Programmatic Access" is enabled in your admin settings. If its enabled, the add-ins will get invoked on IRM mails. For more info on how to configure the usage rights, please check this link https://docs.microsoft.com/en-us/azure/information-protection/configure-usage-rights#usage-rights-and-descriptions : Encoding in policy: OBJMODEL

**Comment by t-ariyoshi30907** [comment]
@exextoc 
Thank you.
By the way. I want to ask another question

Even if I change the setting, in some cases the dialog is not displayed and an email is sent.

The cases where problems occur are described below.

1. Click on the encrypted email in inbox.
2. Click Reply or Forward.
3. Write and send an email.

Customers are having trouble with this issue. I want you to fix it as soon as possible before trouble occurs.

**Comment by exextoc** [comment]
@t-ariyoshi30907 Can you please be more specific with the cases where the add-in does not launch? Because the cases that have been listed cover most of the use cases.

    1. Does the add-in launch for non-encrypted mails?
    2. For Reply/Forward and new mail - Is it for encrypted/non-encrypted?

**Comment by t-ariyoshi30907** [comment]
@exextoc 
Thank you for your reply.
1. yes. A add-in is run when sending non-encrypted email.
2. Add-in is run when sending a new email.and does not run when Reply or Forward.
Share the video of this issue.

■video URL
https://drive.google.com/file/d/15jlDnEz9OF2HcdAOaIOACqbA1US-zL1_/view?usp=sharing

**Comment by exextoc** [comment]
@t-ariyoshi30907 Addins are not yet enabled on encrypted emails (IRM) emails. 

This feature is work in progress and available for preview in only "Outlook on Windows". [Link.](https://docs.microsoft.com/en-us/javascript/api/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview?view=common-js-preview#add-in-activation-on-items-protected-by-information-rights-management-irm
) 

Apologies for causing confusion in earlier comments.

**Comment by t-ariyoshi30907** [comment]
@exextoc 
thank you! I understand.
I have received a request from my customer. I hope it will be available in Outlook on the web.

**Comment by exextoc** [comment]
yes, the feature is in progress. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Currently IRM feature, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
