### ISSUE TITLE
Excel for Mac suspends TaskPane apps when it loses focus

### ISSUE THREAD

**Issue by sameera** [OfficeDev/office-js#262]
We are noticing this issue on the Mac, where a user would start a long running process in our taskpane app (e.g. one that generates 100s of table rows) and switches to another application. It seems that the taskpane is "suspended" after Excel loses focus; and it would resume immediately after Excel regains focus.
NOTE: This is happening on v16.x versions of Excel for Mac only. We were unable to repro this on v15.39. But immediately after update to v16.16 this repro'd.  Other versions known to repro: 16.17, 16.15. We have tested on Sierra 10.12.6, 10.122 and Mojave 10.14. MacOS version had no impact on the issue (repor'd or didn't repro based on Excel version).

## Expected Behavior
For taskpanes to be able to run while Excel is open in the background.

## Current Behavior
TaskPane is suspended from calling Excel APIs when Excel loses focus 

## Steps to Reproduce, or Live Example
1. Start a long running operation in a TaskPane app on Excel for Mac
2. While the operation is running, switch to any other app. The taskpane will appear to be stuck on current operation and will not make any updates to the worksheet. The app isn't frozen, in that, any animated gifs would continue to animate.
3. Switch back to Excel and the Taskpane immediately resumes completing its work.

* Additional details:
  1. Only happens of Office for Mac
  2. Does not repro on v15.39.
  3. Reproduced on 16.17, 16.15

## Context
Our takspane app is importing data from a Webservice on to Excel, in batches. If the user starts the import and switches to another app, expecting the import to complete in the background, what actually happens is the app getting suspended on the current write-to-sheet operation and waits until Excel regains focus.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac 
* Host [Excel, Word, PowerPoint, etc.]: Excel 
* Office version number: 16.17, 16.15
* Operating System: MacOS Sierra and Mojave
* Browser (if using Office Online): n/a

**Comment by LanceEa** [comment]
I can confirm that I have seen the same issue as well and I'm testing on High Sierra with the Insider Fast build. Some of our table loads will be 2-5 minutes so it requires a user to stop using their computer until the load is finished.

**Comment by JuaneloJuanelo** [comment]
thanks for reporting this folks. Yes this is a known issue and we are in the process of investigating/fixing. thanks for reporting it. Tracking internally with 2554389

**Comment by JuaneloJuanelo** [comment]
this issue is fix and shipped on since Ver 16.20 (december update)
