### ISSUE TITLE
Disable events and calculation in Office Add-in does not disable them in VBA

### ISSUE THREAD

**Issue by osvath58** [OfficeDev/office-js#2622]
# We encountered a problem when we turn off events and calculations in Excel with Office Add-in, where VBA still handles events. It looks like turning off events in VBA or Office Add-in does not do it at the Excel application level but only at the Office Add-in or VBA level.

## Your Environment
* PC desktop
* Excel
* Version 2102 (Build 13801.20960 Click-to-Run)
* Windows 10
 
## Expected behavior
I expect that disabling events or calculations in an Office Add-in or in VBA, would disable them for Excel at the application level.

## Current behavior
We encountered a problem when we turn off events and calculations in Excel with Office Add-in, where VBA still handles events. It looks like turning off events in VBA or Office Add-in does not do it at the Excel application level but only at the Office Add-in or VBA level.

## Steps to reproduce
1. Turn off events and set calculations to Manual in an Office Add-in
2. In VBA check the value of Application.EnableEvents, and it will still be True

## Context
We are trying to run a long process in Excel from an Office Add-in and need to turn off events and calculations until the process is complete, then turn them both on again. Our workbook also has VBA code that handles events, and these events are getting fired during the long process, but should not be.

**Comment by gingerjia** [comment]
@osvath58 Thanks for reporting the issue! Currently it's by design that Excel JS API event handle is separated from VBA event handle, which means we cannot turn off VBA event by JS API. :( 
If it's a block for your side, may you help to create a request at https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform? Thanks!

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
