### ISSUE TITLE
How to insert Header and footer data with insertooxml

### ISSUE THREAD

**Issue by vbachu-rsi** [OfficeDev/office-js#2623]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I have open xml string file, which has Body data, Header data and Footer data. I am trying to insert data with  

```

context.document.body.insertOoxml(WORD_DATA, "Start"); //WORD_DATA is in XML string

Or

 Office.context.document.setSelectedDataAsync(WORD_DATA,{coercionType:Office.CoercionType.Ooxml},(res)=>{
         console.log(res);
 })


```

In both cases body data only inserting but not Header and footer. How to extract Header and Footer in the respective sections

I tried this also
 

```
var myFooter = mySections.items[0].getFooter(Word.HeaderFooterType.primary);
            
 myFooter.insertOoxml(WORD_DATA, Word.InsertLocation.end);

```

In this case also inserting Body data only. How to insert Header and Footer data from XML string

**Comment by jipyua** [comment]
Hi vbachu,

Document.body.insertOoxml() means inserting the content into the main body of the document, so the header/footer data will not be inserted. It’s correct that you need to call the following code in order to insert something into header/footer. 

var myFooter = mySections.items[0].getFooter(Word.HeaderFooterType.primary);
myFooter.insertOoxml(WORD_DATA, Word.InsertLocation.end);

But before doing this, you will need to first get the content you want to insert as a separate ooxml, such as you can first call mySections.items[0].getFooter(Word.HeaderFooterType.primary).getOoxml(); to get the ooxml representation of the header/footer content from another template file to generate a separate ooxml of headerfooter and then call insertOoxml API.

**Comment by vbachu-rsi** [comment]
Hi jipyua,

Thank you for throwing some light on my issue. But my problem not solved. Please guide me where am I doing wrong

` Office.context.document.setSelectedDataAsync(WORD_DATA,{coercionType:Office.CoercionType.Ooxml})`

```
 await Word.run(async (context) => {
         let header = context.document.sections;

        let headerOOXML = header.getFirst().getHeader('Primary').getOoxml();
        await context.sync();
       console.log("header OOXML contents: " + headerOOXML.value);
}
```
headerOOXML has signature or representation of Header XML which does not have data which was in WORD_DATA. How to extract header/footer data

**Comment by jipyua** [comment]
hi,

I am not sure how WORD_DATA is generated, but would you please give some snapshots of what data in the header not shown inside headerOOXML?

**Comment by vbachu-rsi** [comment]
WORD_DATA is a OpenXML file which holds body, header and footer data like this

![image](https://user-images.githubusercontent.com/93675161/173071228-f67c402f-d8c6-434e-99f9-c331e4f4f0eb.png)

`
Office.context.document.setSelectedDataAsync(WORD_DATA,{coercionType:Office.CoercionType.Ooxml})
`

By this I am able to load body data perfectly 

but in header and footer also same data is loading like this

![image](https://user-images.githubusercontent.com/93675161/173075835-cc16b2f2-b3cf-479b-94b2-ef4714873027.png)

**Comment by jipyua** [comment]
hi, As said earlier, you need to prepare a separate headerooxml by calling header.getFirst().getHeader('Primary').getOoxml(); from a template file which contains the header data/format you'd like to insert to other files' header/footer and then call header.getFirst().getHeader('Primary').insertOoxml() with the headerooxml in a target file.

**Comment by curtk** [comment]
Hey vbachu-rsi,

I believe I had this same problem as you, but I've figured it out... You probably have as well, but in-case you didn't.

In my case, I had extracted xml from a preformatted word document with a header / footer.

I then attempted to insert that XML using the following method:

`context.document.sections.getFirst().getHeader("Primary").insertOoxml(XML, "Replace");`

The issue with this is that the header content is generated into the following package:

` <pkg:part pkg:name="/word/header1.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.header+xml">`

However, the "getHeader("Primary") method returns a "Word.Body."

So when you attempt to insert your XML header/footer payload into the header using

`context.document.sections.getFirst().getHeader("Primary").insertOoxml(XML, "Replace");`

With the header content in the header1.xml package, it will not work.

You need to send the header content as if you were inserting XML into the body, like this

`<pkg:package xmlns:pkg="http://schemas.microsoft.com/office/2006/xmlPackage">
  <pkg:part pkg:name="/_rels/.rels" pkg:contentType="application/vnd.openxmlformats-package.relationships+xml" pkg:padding="512">
    <pkg:xmlData>
      <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
        <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
      </Relationships>
    </pkg:xmlData>
  </pkg:part>
  <pkg:part pkg:name="/word/document.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml">
    <pkg:xmlData>
      <w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
        <w:body>
          <w:p>**HEADER CONTENT**</w:p>
        </w:body>
      </w:document>
    </pkg:xmlData>
  </pkg:part>
  <pkg:part pkg:name="/word/_rels/document.xml.rels" pkg:contentType="application/vnd.openxmlformats-package.relationships+xml" pkg:padding="256">
    <pkg:xmlData>
      <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
        <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>
        <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/numbering" Target="numbering.xml"/>
      </Relationships>
    </pkg:xmlData>
  </pkg:part>
</pkg:package>`

You don't even need to include the header1.xml or footer1.xml packages or their relationships.
