### ISSUE TITLE
The Word API is throwing an error as "RichApi.Error: ItemNotFound" when try to get the ranges.

### ISSUE THREAD

**Issue by crestbala** [OfficeDev/office-js#2624]
Have been trying to retrieve ranges from the paragraph ranges by a paragraph index, a range start & end index and using the "expandTo" method to generate a range, but when run a function, it is throwing an error "Uncaught RichApi.Error: ItemNotFound".

## Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Office 365 version 2205 (16.0.15225.20172)
* Operating System: Windows 10
 
## Expected behavior
Expected to be get a range rather than displaying an error message.

## Current behavior
1. It seems like the range items is not loaded and not synced properly.

## Steps to reproduce
1. Open ScriptLab
2.  Just import this snippet URL ---> https://gist.github.com/crestbala/9f657764c4a2e03f2265cc906fde41e8
3. And, click the "Run" button, you would see that error.
4. Sample document for your use: https://perfectdigital-my.sharepoint.com/:w:/g/personal/bala_perfectdigital_onmicrosoft_com/EUjAlUhYmJxMr4sPsztP78ABo20lcxgSoGNjerporzRP_A?e=dpENzD

## Link to live example(s)
1. https://www.screencast.com/t/oXucifIN

# Provide additional details

Code:

```
$("#run").click(() => tryCatch(run));

async function getParaRanges() {
  return Word.run(async (ctx) => {
    let bodyRange = ctx.document.body.getRange();
    bodyRange.load();
    await ctx.sync();
    let paraRanges = bodyRange.getTextRanges(
      [". ", ".\n", ".\v", "? ", "?\n", "?\v", "! ", "!\n", "!\v", "\r"],
      true
    );
    paraRanges.load("items");
    await ctx.sync();
    return await Promise.all(
      paraRanges.items.map(async (item) => {
        let range = item.getRange();
        range.load();
        range.track();
        return range;
      })
    );
  });
}

async function getRangeByIndexes(paragraph, rangeStart, rangeEnd) {
  return Word.run(async (ctx) => {
    const charRanges = paragraph.search("?", { matchWildcards: true });
    charRanges.load();
    await charRanges.context.sync();

    const targetRange = charRanges.items[rangeStart].expandTo(charRanges.items[rangeEnd]);
    targetRange.load();
    targetRange.track();
    await targetRange.context.sync();

    return targetRange;
  });
}

async function run() {
  let ranges = await getParaRanges();
  // console.log(ranges[0].text.slice(8, 19))
  let targetRange = await getRangeByIndexes(ranges[0], 8, 19);
  console.log(targetRange);
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}
```

## Context
This is really affected us because we are using "TrackChanges" feature which causes we are unable to get the exact boundary ranges, we want to overcome this problem by range start and end index. If you guys know any other way let me know, we will try to implement that.

## Useful logs

screenshot: https://www.screencast.com/t/JUIPCJvE8Zb

`[ERROR]: Error:
{
    "stack": "RichApi.Error: ItemNotFound\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:26:245243)\n    at n.i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:26:309577)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:26:307639",
    "message": "ItemNotFound",
    "name": "RichApi.Error",
    "code": "ItemNotFound",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "ItemNotFound",
        "message": "ItemNotFound",
        "errorLocation": "RangeCollection.getItem",
        "statement": "var _Search2Item = _Search2.getItem(...);",
        "surroundingStatements": [
            "var v = context.root._getObjectByReferenceId(\"r!0001F704\");",
            "var _Search2 = v._Search2(...);",
            "// >>>>>",
            "var _Search2Item = _Search2.getItem(...);",
            "// <<<<<",
            "var _Search2Item1 = _Search2.getItem(...);",
            "var expandTo = _Search2Item.expandTo(...);",
            "expandTo.load();",
            "// Instantiate {expandTo}"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 404
}`

**Comment by jipyua** [comment]
Thanks for reporting, this bug is now tracked by internal bug 6211840, we will update this when we have some progress.

**Comment by jipyua** [comment]
hi, we found that this is related with how you write the code. In method getRangeByIndexes(), you should pass the variable paragraph as the first parameter inside Word.run and it will be working, please have a try.

async function getRangeByIndexes(**paragraph**, rangeStart, rangeEnd) {
  return Word.run(paragraph, async (ctx) => {
    const charRanges = paragraph.search("?", { matchWildcards: true });
    charRanges.load();
    await charRanges.context.sync();

    const targetRange = charRanges.items[rangeStart].expandTo(charRanges.items[rangeEnd]);
    targetRange.load();
    targetRange.track();
    await targetRange.context.sync();

    return targetRange;
  });
}
