### ISSUE TITLE
Excel: While loading an excel template using a base64 string using insertWorksheetsFromBase64 method, Worksheet.activate() method throwing General Exception

### ISSUE THREAD

**Issue by rajeshgaur23** [OfficeDev/office-js#2625]
# Provide required information needed to triage your issue
We are using the office.js' `insertWorksheetsFromBase64` method to load our excel template files on the fly. this template has multiple sheets and we are trying to activate the first sheet using `worksheet.activate()` method.

After downloading and installing the add-in when we try to use load an excel base64 files using this method the first time. it breaks at `worksheet.activate()` step and  it throws a `General Exception` (screenshot attached)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: MAC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1.1.10
* Operating System: Mac OS big sir
* Browser (if using Office on the web): NA
 
## Expected behavior

  `sheets.items[0].activate()` should activate the first sheet without throwing any exception like it works when we load any base64 excel file with an add-in already installed 

## Current behavior

when code reaches at `sheets.items[0].activate()` it throws a "GeneralException: There was an internal error while processing the request."

This issue is happening only when the add-in is installed the first time and we try to activate a worksheet

## Steps to reproduce

1. install any new add-in
2. convert an excel file into a base64 string  
3. load this string using `insertWorksheetsFromBase64` method 
4. then try to activate the first or any sheet using `context.workbook.worksheets.items[0].activate`

## Link to live example(s)
Script lab link => https://gist.github.com/raj01104/b48bf3e914b0a24ed018ccc5b97ba7ca

# Provide additional details
This behavior is only observed when we download the add-in and the first time we try to load and activate the base64 excel file using insertWorksheetsFromBase64 method.
This issue is not occurring when add-in is already installed 

## Context
We have a list of base64template excel template strings which we try to load on the fly using our excel add-in.
Whenever our add-in is installed the first time loading these template flow doesn't work

## Useful logs
<img width="638" alt="Screenshot 2022-06-08 at 7 34 52 PM" src="https://user-images.githubusercontent.com/87488033/172845843-bd56296d-e6cc-4da9-acb3-f87837dcbe9a.png">

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by gingerjia** [comment]
@raj01104 Thanks very much for reporting the issue. We can repro the issue and opened a bug #6147170 to track it. Our engineer will work on the fix and reply here when have progress. If you have any other questions, feel free to let us know. Thanks!

**Comment by theawesomenayak** [comment]
Hi Team, any update on the above bug? We have been following up with MS support using our corporate channel (Intuit) but not able to get an update. This is affecting one of our products and impacting over 1K customers.

**Comment by yuc014** [comment]
@theawesomenayak @raj01104 
One of our engineers is working on the fix. Really sorry for the inconvenience.

**Comment by guliums** [comment]
Hi @raj01104 @theawesomenayak May I know is this a recent issue or it happened from the beginning?

**Comment by rajeshgaur23** [comment]
@guliums This is happening from beginning only

**Comment by Subhanansahoo** [comment]
@yuc014 @guliums Can we have an ETA on the fix being implemented?

**Comment by guliums** [comment]
Hi @Subhanansahoo @raj01104 @theawesomenayak , sorry for inconvenience. After investigation, it turned out that the bug is in Excel side when open template file from Microsoft AppSource that impacted office.js API. We have contact Excel team and they are actively working on it. Unfortunately I don't have a timeline to share at this point, but I will keep updated in this thread.  
As the bug is caused by opening template file from appsource, could you suggest your users to use the add-in store in Excel app to install your add-in? In that way it will not have this bug. Thanks!

**Comment by Subhanansahoo** [comment]
@guliums Any further updates on the resolution of this issue?

Thanks for your suggestion to install the add-in from the Excel add-in Store. However, this will break the seem less user journey to install the add-in.
Currently, we embed this link inside our product (ms-excel:https://api.addins.store.office.com/addinstemplate/en-GB/ea26f6e7-8229-4bb0-b188-ba20148571f5/WA200003784/none/Spreadsheet-Sync.xlsx?omexsrctype=1)
Now, when the user clicks on this link from our product, excel opens with the add-in installed. This automates the complete process. But, the method you suggested - has a few manual steps and few users will use this.

Alternately, is there any custom link/URL we can use to eliminate the error while keeping the same user workflow?
cc: @raj01104 @theawesomenayak

**Comment by guliums** [comment]
Hi @Subhanansahoo , an engineer from Excel Team is actively working on this bug, it may need some time as the bug affect not only office.js API but also Excel native feature.  As temporary workaround, could you try to remove the "?omexsrctype=1" from the URL? If that works it should not have such issue. Thanks!

**Comment by Subhanansahoo** [comment]
Thanks, @guliums !
@raj01104 Can we please try the workaround suggested?

**Comment by Subhanansahoo** [comment]
@guliums We tried the workaround suggested by removing extra URL parameters, buts it's not working. 
Any further updates on the resolution of the bug? Currently, it has started affecting 2K Intuit customers.
Is there any other way, we could expedite the bug fix? 
cc: @raj01104 @theawesomenayak

**Comment by guliums** [comment]
Hi @Subhanansahoo , that is wired.  I cannot repro if I try to open [https://api.addins.store.office.com/addinstemplate/en-GB/ea26f6e7-8229-4bb0-b188-ba20148571f5/WA200003784/none/Spreadsheet-Sync.xlsx](https://api.addins.store.office.com/addinstemplate/en-GB/ea26f6e7-8229-4bb0-b188-ba20148571f5/WA200003784/none/Spreadsheet-Sync.xlsx). The url should NOT have any parameters after .xlsx. Could you provide repro video if you still see the issue after removing "?omexsrctype=1"? Thanks for your support!

**Comment by Subhanansahoo** [comment]
This issue is being actively address by Microsoft team and communication is happening on a daily basis

Thanks & Regards
Subhanan
________________________________

**Comment by noseworthy** [comment]
> @guliums Any further updates on the resolution of this issue?
> 
> Thanks for your suggestion to install the add-in from the Excel add-in Store. However, this will break the seem less user journey to install the add-in. Currently, we embed this link inside our product (ms-excel:https://api.addins.store.office.com/addinstemplate/en-GB/ea26f6e7-8229-4bb0-b188-ba20148571f5/WA200003784/none/Spreadsheet-Sync.xlsx?omexsrctype=1) Now, when the user clicks on this link from our product, excel opens with the add-in installed. This automates the complete process. But, the method you suggested - has a few manual steps and few users will use this.
> 
> Alternately, is there any custom link/URL we can use to eliminate the error while keeping the same user workflow? cc: @raj01104 @theawesomenayak

Hey @Subhanansahoo, I know this is a long shot, and you're not Microsoft support but do you a link to any documentation from Microsoft on how you hosted this file at https://api.addins.store.office.com and set up the install process? We're trying to achieve the same seamless install flow from a link on our website and we can't find any documentation at all. You're the first person I've seen talking about this, so if you're able to point me in the right direction it'd be greatly appreciated! Thanks so much! 😁
