### ISSUE TITLE
Register the online-meeting template for PGiConnect

### ISSUE THREAD

**Issue by paulnearney** [OfficeDev/office-js#2626]
Can you register the online-meeting template for our PGiConnect service?

                let tableString = "";
                for (let number of numbers) {
                    tableString = "<tr>" +
                        "<td style=\"width:112.5pt;padding:0in 5.4pt 0in 5.4pt;\" valign=\"top\" width=\"145\">" +
                        "<span style=\"font-size:10.5pt;font-family:'Segoe UI',sans-serif;line-height:1.8;\">" + number.location + ":</span>" +
                        "</td>" +
                        "<td style=\"width:130.5pt;padding:0in 5.4pt 0in 5.4pt;\" valign=\"top\" width=\"155\">" +
                        "<span class=\"x_MsoHyperlink\"><span style=\"font-size:10.5pt;font-family:'Segoe UI Semibold',sans-serif;color:#6264a7;line-height:1.8;\"><a href=\"" + number.url + "\">" +
                        "<span style=\"color:#6264a7;line-height:1.8;\">" + number.ddi + "</span></a></span></span>" +
                        "</td>" +
                        "</tr>";
                }

                body += "<div class=\"x_WordSection1\">" +
                    "<p class=\"x_MsoNormal\">&nbsp;<br/><br/>" +
                    "<span style=\"line-height:1;\">___________________________________________________</span><br/>" +
                    "<span style=\"font-size:10.5pt;font-family:'Segoe UI',sans-serif;line-height:1.3;\">&nbsp;</span><br/>" +
                    "<span style=\"font-family:'Segoe UI',sans-serif;font-size:24px;line-height:1;\">Microsoft Teams meeting</span><br><br>" +
                    "<strong><span style=\"font-size:10.5pt;font-family:'Segoe UI',sans-serif;line-height:1.5;\">Join on your computer or dial in</strong></span><br>" +
                    "<strong><span style=\"font-size:10.5pt;font-family:'Segoe UI Semibold',sans-serif;color:#6264a7;line-height:1.5;\"><a href=\"" + meetUrl + "\"><span style=\"color:#6264a7;line-height:1.5;\">Click here to join meeting</span></a></span></strong><br><br>" +
                    "<strong><span style=\"font-size:10.5pt;font-family:'Segoe UI',sans-serif;line-height:2;\">Or call in by phone</span></strong><br>" +
                    "<span style=\"font-size:10.5pt;font-family:'Segoe UI',sans-serif;line-height:1.5;\">Join the meeting from your phone by calling any of the access numbers below.<br />Conference ID: " + passcode + "#</span><br>" +
                    "<span style=\"font-size:10.5pt;font-family:'Segoe UI',sans-serif;line-height:1.7;\">On a mobile device? Tap any phone number to dial in without having to enter the Conference ID.</span>" +
                    "<table class=\"x_MsoNormalTable\" style=\"border-collapse:collapse;\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">" +
                    "<tbody>" + tableString + "</tbody>" +
                    "</table>" +
                    "<span style=\"font-size:10.5pt;font-family:'Segoe UI Semibold',sans-serif;\"><span class=\"x_MsoHyperlink\"><span style=\"color:#6264a7;\"><a href=\"" + meetingOptionsUrl + "\">" +
                    "<span style=\"color:#6264a7;line-height:0.5;\">Meeting options</span></a></span></span></span></p>" +
                    "<span style=\"font-size: 1.0pt; color: #fffff9; line-height:1;\">reservationid" + reservationId + "reservationid</span><br />" +
                    "<span style=\"line-height:1;\">___________________________________________________</span></p>" +
                    "<p class=\"x_MsoNormal\">&nbsp;</p>" +
                    "</div>";

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a55fe4-0fe1-858c-26a4-dddc3ee128ea
* Version Independent ID: 0a643291-936f-b374-37fd-7db497c73cce
* Content: [Create an Outlook mobile add-in for an online-meeting provider - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting)
* Content Source: [docs/outlook/online-meeting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/outlook/online-meeting.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@paulnearney Thanks for trying the online-meeting feature! We'll get this info to the team and let you know once the registration is complete.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@paulnearney The team has requested the following information/updates:

- Your text should say something like "PGiConnect meeting" instead of "Microsoft Teams meeting"
- We will need complete HTML content. You can share HTML content from any meeting which you created using your add-in.
The HTML you have shared doesn’t have your meeting URL and phone number, etc. That is, we need the actual info instead of variables or other placeholders.

Thanks.

**Comment by paulnearney** [comment]
Thanks @ElizabethSamuel-MSFT 

Our service augments a standard Teams meeting with additional dial-in details - hence wanting to leave the text as "Microsoft Teams meetings".

I can provide a sample of complete HTML content, but in real-world usage, the list of telephone numbers will vary in length and detail from customer to customer.

Is there any issue with either of the above?

**Comment by ElizabethSamuel-MSFT** [comment]
Thanks for your response, @paulnearney. The team asked the following:

> Can you let us know what is the current behavior you're seeing? Are you not seeing the join button?
>
> If the meeting link and text is the same as Teams then feature extraction should be happening already. At least the join URL should be extracted and even join meeting button should be appearing.

Thanks.

**Comment by paulnearney** [comment]
Thanks @ElizabethSamuel-MSFT 

I'm not seeing the join button light up on iOS or Android. I've pasted the full HTML of the meeting invite body (generated on iOS) below.

```
<meta http-equiv="Content-Type" content="text/html; charset=us-ascii"><div class="x_WordSection1"><p class="x_MsoNormal">&nbsp;<br><br><span style="line-height:1;">___________________________________________________</span><br><span style="font-size:10.5pt;font-family:'Segoe UI',sans-serif;line-height:1.3;">&nbsp;</span><br><span style="font-family:'Segoe UI',sans-serif;font-size:24px;line-height:1;">Microsoft Teams meeting</span><br><br><strong><span style="font-size:10.5pt;font-family:'Segoe UI',sans-serif;line-height:1.5;">Join on your computer or dial in</strong></span><br><strong><span style="font-size:10.5pt;font-family:'Segoe UI Semibold',sans-serif;color:#6264a7;line-height:1.5;"><a href="https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZjM2M2MzNjctNzI4OS00OTFkLTg5NGItMmIxNTdlMTk5MTFl%40thread.v2/0?context=%7b%22Tid%22%3a%22c15d600f-df56-492b-8595-d6194a590fbd%22%2c%22Oid%22%3a%22249cd172-a4a8-464d-a286-d55ebd10efa6%22%7d"><span style="color:#6264a7;line-height:1.5;">Click here to join the meeting</span></a></span></strong><br><br><strong><span style="font-size:10.5pt;font-family:'Segoe UI',sans-serif;line-height:2;">Or call in by phone</span></strong><br><span style="font-size:10.5pt;font-family:'Segoe UI',sans-serif;line-height:1.5;">Join the meeting from your phone by calling any of the access numbers below.<br>Conference ID: 12345#</span><br><span style="font-size:10.5pt;font-family:'Segoe UI',sans-serif;line-height:1.7;">On a mobile device? Tap any phone number to dial in without having to enter the Conference ID.</span><table class="x_MsoNormalTable" style="border-collapse:collapse;" border="0" cellspacing="0" cellpadding="0"><tbody><tr><td style="width:112.5pt;padding:0in 5.4pt 0in 5.4pt;" valign="top" width="145"><span style="font-size:10.5pt;font-family:'Segoe UI',sans-serif;line-height:1.8;">US:</span></td><td style="width:130.5pt;padding:0in 5.4pt 0in 5.4pt;" valign="top" width="155"><span class="x_MsoHyperlink"><span style="font-size:10.5pt;font-family:'Segoe UI Semibold',sans-serif;color:#6264a7;line-height:1.8;"><a href="tel:+1-646-307-1479,*,8844829075"><span style="color:#6264a7;line-height:1.8;">+1-646-307-1479</span></a></span></span></td></tr></tbody></table><span style="font-size:10.5pt;font-family:'Segoe UI Semibold',sans-serif;"><span class="x_MsoHyperlink"><span style="color:#6264a7;"><a href="https://teams.microsoft.com/l/meetup-join/19%3ameeting_ZjM2M2MzNjctNzI4OS00OTFkLTg5NGItMmIxNTdlMTk5MTFl%40thread.v2/0?context=%7b%22Tid%22%3a%22c15d600f-df56-492b-8595-d6194a590fbd%22%2c%22Oid%22%3a%22249cd172-a4a8-464d-a286-d55ebd10efa6%22%7d"><span style="color:#6264a7;line-height:0.5;">Meeting options</span></a></span></span></span></p><span style="font-size: 1.0pt; color: #fffff9; line-height:1;">reservationid12345reservationid</span><br><span style="line-height:1;">___________________________________________________</span></p><p class="x_MsoNormal">&nbsp;</p></div>
```

**Comment by ElizabethSamuel-MSFT** [comment]
@paulnearney Thanks for this info. I'll pass along to the team and we'll update you soon.

Thanks.

**Comment by paulnearney** [comment]
@ElizabethSamuel-MSFT , here's some more detail, in case it comes in useful.

When we toggle the online meeting slider to On, I'm fetching the Exchange Identity, prompting for auth (if needed), and calling Graph as the user (delegated permissions) to generate a new Teams meeting. I'm then returning this URL to the client.

I then grab the current message body, and append my meeting details section to it according the the logic in my initial post. I'm then calling body.setAsync to set the message body (I set the location to "Microsoft Teams Meeting" too)

**Comment by ElizabethSamuel-MSFT** [comment]
@paulnearney Thanks for the additional details. Will pass along to the team as well.

Thanks.

**Comment by paulnearney** [comment]
Hi @ElizabethSamuel-MSFT 

I've been experimenting with different HTML to see if I can get the Join link to light up but not managed to make it work. Is it possible to get an overview from the team as to what exactly they are looking for in the HTML?

**Comment by ElizabethSamuel-MSFT** [comment]
@paulnearney Thanks for this update. I'll make sure they're aware of this.

Thanks.

**Comment by paulnearney** [comment]
@ElizabethSamuel-MSFT, another update.

I've tried replacing the meeting body with the full HTML that is returned from creating the OnlineMeeting via graph. I'm accessing the meeting body this way:

`HttpUtility.UrlDecode(meeting.JoinInformation.Content.Split(",")[1]);`

This still doesn't enable the Join button etc.

**Comment by paulnearney** [comment]
Hi @ElizabethSamuel-MSFT , is there any update on this? We have a number of customers waiting for this feature and it would be good to be able to give them an update. Thanks

**Comment by exextoc** [comment]
Thanks for providing the HTML, we tried the HTML snippet and the join button did not appear for us as well. We will identity the changes and do the needful to show join button.

**Comment by paulnearney** [comment]
OK, thanks @exextoc. Do you have an ETA of when our customers could expect to see this functionality?

Will the appearance of the join button just be driven from the existence of a Teams URL? It would be good to know what rules to follow if we need to change the content of our meeting template in the future.

**Comment by exextoc** [comment]
On digging futher we realised the join button should not be already appearing for meetings created with PGiConect addin. We will have to add rules based on the HTML you provided. Yes, the rule will check for existance of Teams URL. 
We have added this task to our backlog but we cannot share any timelines at the moment.

**Comment by paulnearney** [comment]
Thanks @exextoc. Is there any way for me to get a notification when timelines are available?

**Comment by exextoc** [comment]
Yes definitely we will keep you posted here.

**Comment by exextoc** [comment]
Hey @paulnearney ,

Thank you for raising this request and your patience with the same. We add the Join button functionality for meeting add-ins periodically and are tentatively going to pick this next up by Oct 2022. There is no more inputs needed from your end at the moment and we will keep you posted once this is implemented.

**Comment by DivyaPatidar** [comment]
@paulnearney Can you share Office Store assetId of your add-in? To know more on how to get assetId, you can check [here](https://learn.microsoft.com/en-us/microsoft-365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins?view=o365-worldwide#:~:text=To%20determine%20the,assetid%3DWA104099688.).

**Comment by paulnearney** [comment]
Thanks for the response, but in the 3 years that have passed since logging this request, the project is well and truly dead!
