### ISSUE TITLE
Register the online-meeting template for Moxo

### ISSUE THREAD

**Issue by suryakiranchikkala** [OfficeDev/office-js#2627]
Can you register the online-meeting template for our Moxo Service

 '<br>' +
 	'Test User is inviting you to a scheduled Moxo meeting.' +
 	'<br><br>' +
 	'Join Moxo Meeting:'+
 	'<br>' +
	'<a href="https://moxo.moxo.com/428427995" target="_blank">https://moxo.moxo.com/428427995</a>' + 	
	'<br><br>' +
    'Meeting ID: 428427995' +
	'<br><br>' +
	'Passcode: 234w2323' +
	'<br><br>';

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a55fe4-0fe1-858c-26a4-dddc3ee128ea
* Version Independent ID: 0a643291-936f-b374-37fd-7db497c73cce
* Content: [Create an Outlook mobile add-in for an online-meeting provider - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting)
* Content Source: [docs/outlook/online-meeting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/online-meeting.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@suryakiranchikkala Thanks for your request. We'll have the product team take a look.

Thanks.

**Comment by exextoc** [comment]
@suryakiranchikkala Is your addin approved and available in our store?

**Comment by suryakiranchikkala** [comment]
No. It's under development

**Comment by nancy-wang** [comment]
@exextoc following up here - based on your investigations, is there anything we could do here as part of the product team? thanks for your help!

**Comment by exextoc** [comment]
Hey @suryakiranchikkala ,

Thank you for raising this request and your patience with the same. We add the Join button functionality for meeting add-ins periodically and are tentatively going to pick this next up by Oct 2022. There is no more inputs needed from your end at the moment and we will keep you posted once this is implemented.

**Comment by DivyaPatidar** [comment]
@suryakiranchikkala Can you share Office Store assetId of your add-in? To know more on how to get assetId, you can check [here](https://learn.microsoft.com/en-us/microsoft-365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins?view=o365-worldwide#:~:text=To%20determine%20the,assetid%3DWA104099688.).
