### ISSUE TITLE
Register the online-meeting template for Viqueens

### ISSUE THREAD

**Issue by zjmchoi** [OfficeDev/office-js#2628]
'<br>' +
    '<a href="https://viqueens.com/meeting?id=123456789" target="_blank">Join Viqueens meeting</a>' +
    '<br><br>' +
    'Phone Dial-in: +1(123)456-7890' +
    '<br><br>' +
    'Meeting ID: 123 456 789' +
    '<br><br>' +
    'Want to test your video connection?' +
    '<br><br>' +
    '<a href="https://viqueens.com/testmeeting" target="_blank">Join test meeting</a>' +
    '<br><br>';

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a55fe4-0fe1-858c-26a4-dddc3ee128ea
* Version Independent ID: 0a643291-936f-b374-37fd-7db497c73cce
* Content: [Create an Outlook mobile add-in for an online-meeting provider - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting)
* Content Source: [docs/outlook/online-meeting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/online-meeting.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Assigning to @exextoc for registration.

**Comment by nancy-wang** [comment]
@exextoc wanted to make sure you were aware of this - thank you for your help and @zjmchoi for raising this issue with our team!

**Comment by exextoc** [comment]
Thank you for raising this request. We add the Join button functionality for meeting add-ins periodically and are tentatively going to pick this next up by Oct 2022. There is no more inputs needed from your end at the moment and we will keep you posted once this is implemented.

**Comment by DivyaPatidar** [comment]
@zjmchoi  Can you share Office Store assetId of your add-in? To know more on how to get assetId, you can check [here](https://learn.microsoft.com/en-us/microsoft-365/enterprise/use-the-centralized-deployment-powershell-cmdlets-to-manage-add-ins?view=o365-worldwide#:~:text=To%20determine%20the,assetid%3DWA104099688.).
