### ISSUE TITLE
Implementing Outlook's Every Meeting Online (EMO) for third-party online meeting providers

### ISSUE THREAD

**Issue by markdon** [OfficeDev/office-js#2630]
Recently, a new feature was released that allows customers to choose a third party meeting provider as their every meeting online provider instead of Teams. Some related documentation: https://support.microsoft.com/en-au/office/make-every-meeting-online-70f9bda0-fd29-498b-9757-6709cc1c73f0?preview=true

How do I get this integration with our online meetings solution? We have a fully featured add-in (on par with Zoom) but it's not in AppSource.

Linked document is related. I don't believe the documentation I'm looking for exists.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52a55fe4-0fe1-858c-26a4-dddc3ee128ea
* Version Independent ID: 0a643291-936f-b374-37fd-7db497c73cce
* Content: [Create an Outlook mobile add-in for an online-meeting provider - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting)
* Content Source: [docs/outlook/online-meeting.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/online-meeting.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by nancy-wang** [comment]
thanks for the question @markdon! Tagging @exextoc who may be able to help out here.

**Comment by samantharamon** [comment]
Hi @markdon,

Thank you for your post. I understand that you're currently in conversation with the feature crew about this via email. I'm working with them to determine any documentation updates needed.

**Comment by markdon** [comment]
@samantharamon That conversation is related to a different feature, which is to show a "Join" button when meetings from my add-in are detected: https://github.com/OfficeDev/office-js-docs-pr/issues/3263

The feature that I'm interested in here allows an add-in to replace Teams as the default meeting provider in Mac/Windows/Web Outlook clients. It has currently been enabled for Zoom, WebEx, BlueJeans, GoToMeeting, Google Meet and JioMeet. 

It would be great if this integration was open to all meeting provider add-ins. Otherwise, I would like to know what the requirements my meeting provider needs to meet to be eligible for the same level of integration as the above providers.

**Comment by samantharamon** [comment]
Thanks for the clarification, @markdon. I've raised this with the feature crew, so that they could also address this.

**Comment by exextoc** [comment]
Hey @markdon ,

We have reached out to you over email and can continue the conversation there. Is it alright if we close this github thread?

**Comment by markdon** [comment]
Sure
