### ISSUE TITLE
Issues using Azure Static Website with Outlook Add-in

### ISSUE THREAD

**Issue by jeff1haupt** [OfficeDev/office-js#2632]
I was able to deploy my outlook add-in to Azure storage and then set it up as a static website, but outlook is not letting me load the manifest file from the url.  Any specifics on how best to do this would be helpful!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b9105a4-a164-1e91-11ad-8ccb4f4d6b2d
* Version Independent ID: f4e5fae7-ac16-f852-8529-6b0fdd7bdad4
* Content: [Publish an add-in using Visual Studio Code and Azure - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish-add-in-vs-code)
* Content Source: [docs/publish/publish-add-in-vs-code.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/publish/publish-add-in-vs-code.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by peronald** [comment]
Hi @jeff1haupt - What is the error you are getting when trying to load the manifest file with the url?

**Comment by jeff1haupt** [comment]
Thanks for the quick response @peronald! Here's the screenshot of what I'm getting:

![image](https://user-images.githubusercontent.com/66330433/139914304-493c26b7-d67c-4b98-9e53-341c666430a6.png)

A lot of stackoverflow boards talk about this being a DNS issue, but since this is coming from my Azure storage account, I wasn't sure that would be an issue.

**Comment by samantharamon** [comment]
Hi @jeff1haupt,

I just wanted to follow up on this issue you opened and whether you are still getting an error when you load the manifest using the URL.

**Comment by exextoc** [comment]
Hey @jeff1haupt,

Is your manifest enclosed in any <xml> or Doctype tag? Your manifest should have `<OfficeApp>` as the root element and nothing outside this element.
