### ISSUE TITLE
hello,I have an asynchronous problem

### ISSUE THREAD

**Issue by tomuGo** [OfficeDev/office-js#2638]
i want to insert a picture,and range.insert is error in then();  
the error message tell me use context.trackedObjects.add(),and i have no idea to solve
thanks
![image](https://user-images.githubusercontent.com/24789356/173516754-c97be0af-3060-47e0-a6e8-a96e65f2e0a3.png)
![image](https://user-images.githubusercontent.com/24789356/173516820-b39808b1-a269-4dff-b569-840430e4a33a.png)

**Comment by massonj** [comment]
Thanks for your question, however this forum is for issues with our product or documentation, not for programming questions about your code. We suggest you go to [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/office-js-dev.html)  and see if your question has already been asked or ask a new question. Thanks, Microsoft 365 Developer Platform team

**Comment by GavinGu07** [comment]
Hi @tomuGo, thanks for your question.

How you get your range? If you get your range in another method, you should define your range as a global variable, track in that method and add it in the second line as:
`.then(range, function() {`
It would be better if you can post your full code.
