### ISSUE TITLE
New line inserted above signature with different font

### ISSUE THREAD

**Issue by s4eideh** [OfficeDev/office-js#2639]
There is an issue after inserting the signature into a new Email `setSignatureAsync ` via Office.js API .There is a line above the signature with different formatting (Font Calibri 12) 

## Your Environment
Microsoft® Outlook® for Microsoft 365 MSO (Version 2205 Build 16.0.15225.20172) 64-bit 
Host:  Outlook for Windows Desktop
Operating System: Windows

 
## Expected behavior
No extra line should be inserted, or that the line should at least match the font of the rest of the document (Which in our case is Arial 10)

## Current behavior
a new line always inserted above the signature with different formatting (Font Calibri 12)

**Comment by Adrian-MSFT** [comment]
Hi @s4eideh 

Thanks for bringing this to our attention.
Can you please include screenshots, snippets, and HTML fragments that you are inserting as signature that can reproduce the issue?

Thank you,
Adrian

**Comment by s4eideh** [comment]
Hi Adrian, 
Thank you for your reply.

This issue happens for any HTML that is inserted 

I have attached two images. 
one for the native Outlook Desktop signature with `setSignatureAsync` and the other with the enabled add-in. 
 in both cases, there is an extra line with a different font format.

![C1](https://user-images.githubusercontent.com/38518799/174812231-c83f0cb4-fd5d-403b-8ede-23886ed83182.png)

![C3](https://user-images.githubusercontent.com/38518799/174812235-ad925f87-9d58-4428-98f2-d7502be76c3e.png)

**Comment by Adrian-MSFT** [comment]
Hi @s4eideh ,

Thanks for reporting this issue. After careful consideration, our team has decided to not fix this issue in the short term. We recommend you to upvote or create a new [Tech Community](http://aka.ms/M365dev-suggestions) item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.

Thank you,
Adrian
