### ISSUE TITLE
Office.context.mailbox.item.subject.setAsync shows success but Subject text is not populated in Subject field of Appointment form. Only occuring on Outlook for Mac, working fine on Windows or Outlook.com website.

### ISSUE THREAD

**Issue by bandhan-nawal** [OfficeDev/office-js#264]
## Expected Behavior

I have an outlook web add-in. When I call `Office.context.mailbox.item.subject.setAsync` to populate Subject in appointment/meeting, it populates the subject correctly, but when I clear the populated subject by using backspace or delete and again call `Office.context.mailbox.item.subject.setAsync`, it should again populate the subject.

## Current Behavior

Currently, for the above scenario, it does not populate the subject again even though the `asyncResult` object I get from `Office.context.mailbox.item.subject.setAsync` callback shows that it has succeeded.

## Context

What I am currently doing is first populating the Subject on the click of a button as follows:
First I check if there is already any text on Subject field in Appointment form. If there is some text then I do not populate any text and let it remain. But if there is no current text, then I populate my default **SUBJECT**.

I am also removing the subject on the click of a button as follows:
If there is already any text on Subject field in Appointment form and if that text is equal to my default **SUBJECT**, then only I use `Office.context.mailbox.item.subject.setAsync('')` i.e set the subject to empty string `''` (clears the subject field), otherwise I let the current text remain on subject field.

Here is the code:

```
const SUBJECT = "My Default Subject";

function populateSubject(sub) {
  Office.context.mailbox.item.subject.setAsync(sub,
    { asyncContext: { var1: 1, var2: 2 } },
    function (asyncResult) {
      if (asyncResult.status == Office.AsyncResultStatus.Failed) {
        // write(asyncResult.error.message);
        // log the error
      }
      else {
        // Successfully set the subject.
        // Do whatever appropriate for your scenario
        // using the arguments var1 and var2 as applicable.
      }
    });
}

function addSubject() {
  Office.context.mailbox.item.subject.getAsync(function (asyncResult) {
    if (asyncResult.status == Office.AsyncResultStatus.Succeeded) {
      if (asyncResult.value == null || asyncResult.value.trim() === '') {
        populateSubject(SUBJECT);
      }
    }
  });
}

function removeSubject() {
  Office.context.mailbox.item.subject.getAsync(function (asyncResult) {
    if (asyncResult.status == Office.AsyncResultStatus.Succeeded) {
      if (asyncResult.value != null && asyncResult.value.trim() != '' && asyncResult.value === SUBJECT) {
        populateSubject('');
      }
    }
  });
}
```
But what actually happens is:
Firstly when I do not edit the Subject field by typing anything into it and try to populate the subject, it gets successfully populated. But if I type something in the Subject field and then clear it using backspace or delete and then try to populate Subject using my code, then it does not populate the default **SUBJECT** (that should have been populated since there is no text in Subject field currently) even though the `asyncResult` object I get from `Office.context.mailbox.item.subject.setAsync` callback shows that it has succeeded.

All the above things are working correctly in Outlook for Windows and Outlook.com website but not in Outlook for Mac. So, I believe this is a bug with Outlook for Mac.

## Environment

* Platform: Mac
* Host: Outlook
* Outlook for Mac version number: 16.17(180909)

**Comment by satishkrsharma** [comment]
I am also facing same issue during development. Please give your response ASAP.

**Comment by kbrandl** [comment]
@exextoc can you please look into this issue?

**Comment by macOutlookExtensibility** [comment]
@bandhan-nawal / @satishkrsharma We are not able to reproduce the issue on 16.17(180909) on New Message/Appointment/Meeting. 

1. User enters some subject.
2. User clears out the subject using delete key.
3. Set subject from add-in using `addSubject()` from your snippet.
With the above flow the issue cannot be reproduced.

Can you give us the flow of events?

**Comment by bandhan-nawal** [comment]
@macOutlookExtensibility  Flow is as follows:
1. User clicks on `addSubject()` to populate the subject (working fine i.e. **My Default Subject** gets added)
2. Remove some part of this subject i.e. let the subject be **My Default**.
3. Now click on `removeSubject()`. But this subject would not be cleared as the subject is not equal to **My Default Subject** which is the desired behavior (working fine).
4. Now clear the whole subject using delete key or backspace key.
5. Again click on `addSubject()`, the subject would not be populated (this is not desired as my code checks if there is no subject text in subject field then it should populate **My Default Subject** in the subject field otherwise do nothing).

Performing all the above steps are mandatory to reproduce this because in my original application I am performing `addSubject` and `removeSubject()` on the click of **same button** and distinguishing whether to add or remove on the basis that **appointment body** is empty or having my **DEFAULT BODY TEXT**.

**Comment by macOutlookExtensibility** [comment]
With the same exact repro steps, the same Outlook for Mac version and the same code snippet from your question, the API is working properly.

I wanted to know, if you are sure that the removeSubject()/addSubject() is called appropriately? Just to rule out the scenario where removeSubject() is called instead of addSubject().

And If possible, can you share the add-in manifest, so that we can try it out?

**Comment by bandhan-nawal** [comment]
@macOutlookExtensibility For live example:
Please add the add-in into your Outlook for Mac from Office Store named "ConX Scheduler for Outlook" (Search "Infocus ConX Scheduler")
Now, perform the following steps to reproduce the issue:
1. Click on second option "Schedule ConX Meeting" in the add-in's dropdown menu.
2. A new appointment window will open with some values in Subject, Location and Body. The subject populated will be **InFocus ConX Meeting**.
3. Try clearing the subject **partially**. For example, let the subject remain as **InFocus ConX**.
4. Click on add-in's Add/Remove Meeting button on appointment window. Location and Body will be cleared out. But subject will remain as **InFocus ConX**.
5. Now, clear the whole subject using backspace or delete keys.
6. Again click on add-in's Add/Remove Meeting button. Location and body gets populated but subject remains empty. This is not the desired behaviour. The default subject i.e. **InFocus ConX Meeting** should get populated.
7. This functionality is working as expected on Outlook for Windows and website outlook.com but failing on Outlook for Mac.

**Comment by macOutlookExtensibility** [comment]
Thanks for reporting this issue, we are able to reproduce it, we are working towards fixing it.

**Comment by neprasad-microsoft** [comment]
This is not reproducible any more.
Code snippet used for testing:


Office.context.mailbox.item.subject.getAsync(function (asyncResult) {
if (asyncResult.status == Office.AsyncResultStatus.Succeeded) {
if (asyncResult.value == null || asyncResult.value.trim() === '') {
Office.context.mailbox.item.subject.setAsync("Test Subject",
{ asyncContext: { var1: 1, var2: 2 } },
function (asyncResult) {
if (asyncResult.status == Office.AsyncResultStatus.Failed) {
showMessage(asyncResult.error.message);
// log the error
}
else {
// Successfully set the subject.

}
});
  }
}
});
