### ISSUE TITLE
Office.context.mailbox.item.getAttachmentContentAsync fails for attachment with extension ".mht"

### ISSUE THREAD

**Issue by teejay001** [OfficeDev/office-js#2640]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number:  16.0.15225.20204
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Attachment content to be returned for all file types

## Current behavior
The api call fails with the following error:
![image](https://user-images.githubusercontent.com/99417649/173858356-9be0053a-f23e-46db-9ed7-52c6f49477fb.png)

## Steps to reproduce
1. Using the OneNote application, create a new note and send as an attachment (file -> send -> send as attachment)
2. Outlook desktop is opened with the attachments in place.
3. Add the necessary message inputs (e.g Recipient and Subject)
4. Save the message as draft
5. From Outlook on Web, try sending the draft
6. The message fails.

## Link to live example(s)
Using the Yo Office template, and updating for messageEdit rather than MessageRead

Office.onReady((info) => {
  if (info.host === Office.HostType.Outlook) {
    document.getElementById("run").onclick = run;
  }
});

async function getAllAttachments() {
  Office.context.mailbox.item?.getAttachmentsAsync((asyncResult) => {
    if (asyncResult.status === Office.AsyncResultStatus.Failed) {
      console.error("Error getting all attachments");
    } else {
      console.info(JSON.stringify(asyncResult.value));
      asyncResult.value.map((i) => {
        ProcessAttachments(i.id);
      });
    }
  });
}

async function ProcessAttachments(id) {
  Office.context.mailbox.item?.getAttachmentContentAsync(id, (asyncResult) => {
    if (asyncResult.status === Office.AsyncResultStatus.Failed) {
      console.error(`Error getting attachment content for ${id}`);
    } else {
      console.info(`Got attachment content for ${id}`);
    }
  });
}

export async function run() {
  getAllAttachments();
}

## Context
trying to process the content of the message to meet business requirements.

## Useful logs

- [X] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by samantharamon** [comment]
Thank you for reporting this, @teejay001. @exextoc, could you please help investigate this?

**Comment by exextoc** [comment]
@teejay001 Can you please share a video explaining the issue and a fiddler trace so that we can debug it better? We need to understand when and how is the getAttachmentContentAsync() being invoked.

**Comment by teejay001** [comment]
To show a video explanation for this would require exposing personal details. Please, can you provide an email I can send this to. I have also attached a word document with pictures showing each step of reproducing the issue at your end.

You need the OneNote App to reproduce the issue.

[OneNote Attachments Error.docx](https://github.com/OfficeDev/office-js/files/8966825/OneNote.Attachments.Error.docx)

**Comment by exextoc** [comment]
@teejay001  Please share the video to "OutlookAddins@M365x693897.onmicrosoft.com".

**Comment by teejay001** [comment]
Video clip sent to email address.

**Comment by exextoc** [comment]
@teejay001 Thanks for the video.
We believe that you are using some onSend add-in while composing a message which invokes "Office.context.mailbox.item.getAttachmentContentAsync". Can you please share its manifest also to the same mail id?

**Comment by teejay001** [comment]
Hi,

The attachment contains the manifest and a sample helpful app.

[TestingOnSend.zip](https://github.com/OfficeDev/office-js/files/8974510/TestingOnSend.zip)

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding the error message in Office.context.mailbox.item.getAttachmentContentAsync(). It has been put on our backlog. We, unfortunately, have no timelines to share at this point.
Internal tracking id: Eg: Office: 2871645

**Comment by teejay001** [comment]
Hi @gergzk,

any reason why you closed this issue? Is this fixed? Perhaps some explanation would be beneficial.

Cheers

**Comment by gergzk** [comment]
@teejay001 - we're doing bulk closing of issues that haven't been updated in a long time (in this case, over 21 months). We're revving our internal processes to better reflect what actually happened here; in the meantime many of these old issues are fixed but the item never got closed. In other cases, they are no longer timely. The goal is to reduce the issue volume so we can pay better attention to each issue, as well as ensure that outcomes are clearly reflected back here.

**Comment by rajjha-msft** [comment]
The issue is fixed and deployed from our end. Please reach out if the issue is still reproducible.
