### ISSUE TITLE
Is there a way to detect in ItemSend event if the event is a cancellation type

### ISSUE THREAD

**Issue by trenoncourt** [OfficeDev/office-js#2641]
Hello,
I'm developping an outlook addin js, i want to have different feature based on appointment itemSend type: Different api calls based on the event creation, update and cancel. 
I'm able to detect the difference between creation and update while adding a custom property in creation event. But not able to detect difference between update and cancel. I have checked properties of the event type and of the item type.
Thanks

**Comment by timwan10** [comment]
This is not possible today. We track Outlook add-in feature requests on our Tech community Page: 

https://aka.ms/M365dev-suggestions
