### ISSUE TITLE
Deploy OneNote addin for organization

### ISSUE THREAD

**Issue by kgeorgiou1234** [OfficeDev/office-js#2643]
OneNote add-in does not seem to be able to be uploaded via admin center or integrated apps for the organization

## Your Environment

- Platform [PC desktop, Mac, iOS, Office on the web]: Office on Web
- Host [Excel, Word, PowerPoint, etc.]: OneNote
- Office version number: 16.0.15325.41001
- Operating System: Windows
- Browser (if using Office on the web): Edge

## Expected behavior
Being able to deploy and publish OneNote Add-in using Microsoft 365 admin center. 

## Current behavior
Cannot deploy the OneNote add-in for the organization 

## Steps to reproduce
Try to upload a manifest for OneNote add-in
- When we try to upload the add-in from admin center we get no error, but the add-in is not uploaded. We noticed the following tooltip

![image](https://user-images.githubusercontent.com/107611022/174019661-8a6739a3-757b-4512-9448-84ea7ae77e71.png)

- When we try from integrated apps we get the following error (different guid each time) and from the network we receive the following response for the manifest: UnableToUploadAddInsForBlockedApps

![image](https://user-images.githubusercontent.com/107611022/174019751-858fc832-8b1a-44ca-ab13-cc84a5cb6f67.png)

- We also tried with admin account to upload the manifest from the My organization tab, but this did not make the add-in available for the rest of the users

Attached the manifest with the image and end point URL's removed.

[manifest-staging-onenote-ticket.txt](https://github.com/OneNoteDev/OneNoteApi/files/8916831/manifest-staging-onenote-ticket.txt)

## Context
- The manifest is valid since it is tested using the validation tool 
- We need the add-in deployed for the organization and this is our only option as per article: https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish. This is the link from OneNote add-in documentation as well: https://docs.microsoft.com/en-us/office/dev/add-ins/onenote/

**Comment by kgeorgiou1234** [comment]
Any update on this?

**Comment by exextoc** [comment]
No action for quite some time. Closing the issue.
