### ISSUE TITLE
"This add-in could not be started" bug

### ISSUE THREAD

**Issue by pb-jeff-oneill** [OfficeDev/office-js#2645]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We get frequent bug reports where our Word add-in stops working and users see this message in the side panel:

![image](https://user-images.githubusercontent.com/55557751/174124607-f82c8c06-bd13-4e9a-ae8e-56807b62f76d.png)

Clicking the Restart button does not help and the message comes back.

Uninstalling the add-in, restarting the computer, and reinstalling the add-in usually makes this problem go away.

It is a terrible user experience for end users, and it generates a lot of support requests for us.

We would appreciate it if you could make it a priority to fix this.

**Comment by preethikakiru** [comment]
Hi @pb-jeff-oneill, thanks for making us aware of this issue. I understand that this would be an inconvenient experience for users. To get more context, is your add-in available for Word online and desktop and if so does this error occur for both?

**Comment by pb-jeff-oneill** [comment]
Our add-in available both desktop and online, but nearly all of our users are on desktop.

I've only received bug reports for desktop.
