### ISSUE TITLE
Addin loaded in blank presentation

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#2646]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi,

I have a problem with an addin being loaded in any blank presentation I open even though it was stopped:

How to reproduce 1:
1. Start a PowerPoint addin with `office-addin-debugging start manifest.xml`
2. Stop the PowerPoint addin using
 - `office-addin-debugging stop manifest.xml` or
 - `office-addin-debugging stop all`
3. Open a blank PowerPoint presentation and unfortunately the addin is still there. 

How to reproduce 2:
1. use `PowerPoint.createPresentation(base64)`
2. addin loaded in the new presentation
 the base64 string for new presentation does not contain the addin, but unfortunately the addin is added in the new presentation

How should I stop the addin or prevent it from being added to a new presentation or disable it completely after first load?

Thanks

**Comment by millerds** [comment]
@danielpdev when you run the start command the webpack server starts that hosts the add-in and the host application (in this case PowerPoint) starts as well with the add-in loaded.  When you run the stop command only webpack is shutdown and the host (PowerPoint) it left open with the reference to the add-in already loaded in the ribbon.  If you then open a new blank presentation then the add-in ribbon button will still be there.  You have to close PowerPoint completely (or remove the add-in manually) before it will be unloaded.

**Comment by danielpdev** [comment]
Ok, so this is how it supposed to work, but what is the reference that is left out for other blank presentations to pick up the addin?
I really need to remove the addin from the next presentation that is going to be opened.

If you ask me, a new presentation should not load/keep any old data, as the name suggests, it is a **blank** presentation.

**Comment by millerds** [comment]
Ribbon entries are not content.  The presentation itself is blank, but the add-in hooked into the ribbon is not tied to the document.  If you had gotten an add-in from the store, instead of running one locally, then you would have it added to the ribbon to be used in any presentation and not just the current one.

**Comment by danielpdev** [comment]
Ok, is there a way to remove it from the next presentation?

You mentioned something about some references being left over for the PowerPoint host, is there any way we can delete them?
Like modifying the registry and removing something from there?

Thank you

**Comment by millerds** [comment]
The references aren't left over, they are part of the PowerPoint session.  In order for it to be removed after "office-addin-debugging start ..." you have to close PowerPoint . . . all open windows.  This should remove the temporary reference and when you start PowerPoint again it will be gone.
