### ISSUE TITLE
Office.context.mailbox.item.getAttachmentContentAsync fails for "outlook item" attachments

### ISSUE THREAD

**Issue by teejay001** [OfficeDev/office-js#2647]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.15225.20204
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Attachment content to be returned for successfully

## Current behavior
API call fails with the console error below
![image](https://user-images.githubusercontent.com/99417649/174261383-778f151c-e5e1-4023-af3a-9e65194fc257.png)

## Steps to reproduce
1. From outlook desktop, create a new compose message
2. Attach a contact as "As a Outlook Contact" OR a task OR an outlook note
3. Save the message as a draft
4. From Outlook on Web, try sending the draft
5. The message fails.

## Link to live example(s)
Using the Yo Office template, and updating for messageEdit rather than MessageRead

Office.onReady((info) => {
if (info.host === Office.HostType.Outlook) {
document.getElementById("run").onclick = run;
}
});

async function getAllAttachments() {
Office.context.mailbox.item?.getAttachmentsAsync((asyncResult) => {
if (asyncResult.status === Office.AsyncResultStatus.Failed) {
console.error("Error getting all attachments");
} else {
console.info(JSON.stringify(asyncResult.value));
asyncResult.value.map((i) => {
ProcessAttachments(i.id);
});
}
});
}

async function ProcessAttachments(id) {
Office.context.mailbox.item?.getAttachmentContentAsync(id, (asyncResult) => {
if (asyncResult.status === Office.AsyncResultStatus.Failed) {
console.error(Error getting attachment content for ${id});
} else {
console.info(Got attachment content for ${id});
}
});
}

export async function run() {
getAllAttachments();
}

## Context
Trying to process the content of the message to meet business requirements.

## Useful logs

- [x] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@teejay001 Can you please share a video explaining the issue so that we can debug it better? We need to understand when and how is the getAttachmentContentAsync() being invoked.

**Comment by teejay001** [comment]
To show a video explanation for this would require exposing personal details. Please, can you provide an email I can send this to. I have also attached a word document with pictures showing each step of reproducing the issue at your end.

[OutlookItem Attachment Error.docx](https://github.com/OfficeDev/office-js/files/8967126/OutlookItem.Attachment.Error.docx)

**Comment by exextoc** [comment]
@teejay001 Please share the video to "OutlookAddins@M365x693897.onmicrosoft.com"

**Comment by teejay001** [comment]
Video clip sent to email address.

**Comment by teejay001** [comment]
Video clip sent to email address.

**Comment by exextoc** [comment]
@teejay001 Thanks for the video.
We believe that you are using some onSend add-in while composing a message which invokes "Office.context.mailbox.item.getAttachmentContentAsync". Can you please share its manifest also to the same mail id?

**Comment by teejay001** [comment]
Hi,

The attachment contains the manifest and a sample helpful app.

[TestingOnSend.zip](https://github.com/OfficeDev/office-js/files/8974518/TestingOnSend.zip)

**Comment by exextoc** [comment]
@teejay001 Thanks for the supporting files. As per our current design, getAttachmentContentAsync API throws a 9043 error if the attachment is an item type other than an email or calendar item (such as a contact or task item). Kindly refer https://docs.microsoft.com/en-us/office/dev/add-ins/reference/javascript-api-for-office-error-codes

**Comment by teejay001** [comment]
Okay, thanks for the update.
