### ISSUE TITLE
"Office.context.mailbox.item" is "undefined"  by certain steps.

### ISSUE THREAD

**Issue by t-ariyoshi30907** [OfficeDev/office-js#2648]
I'm providing an add-in in Outlook on the Web, but I'm seeing unexpected behavior when I encrypt my email.

■Expected behavior

"Office.context.mailbox.item" is returned.

■Current behavior

"Office.context.mailbox.item" is not returned.

■Steps to reproduce

1. Download the official sample. 　 　
https://github.com/OfficeDev/Outlook-Add-in-On-Send/blob/master/outlook-add-in-on-send/Contoso%20Message%20Body%20Checker.xml/
2. Rewrite the contents of the "app.js" file to the source code of following"index.js"
3. Run the "yarn start" command in your local environment.
4. Install the add-in with the manifest file.
5. Write an Email.
6. Click Group folder.
7. send Email.

This problem always occurs. Please tell me how to solve this problem.
I share this result on video and source code.

■video

https://drive.google.com/file/d/1GzfYBYuwf3befGJ4tFBQUEX6R592MHyQ/view?usp=sharing

■source code

index.js
```


/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
 * See LICENSE in the project root for license information.
 */

var mailboxItem;

Office.initialize = function (reason) {
    mailboxItem = Office.context.mailbox.item;
    console.log(mailboxItem)
}

// Entry point for Contoso Message Body Checker add-in before send is allowed.
// <param name="event">MessageSend event is automatically passed by BlockOnSend code to the function specified in the manifest.</param>
function validateBody(event) {

  console.log(mailboxItem)

  Office.context.ui.displayDialogAsync(
  "https://localhost:3000/index.html",
    {
      height: 65,
      width: 40,
      displayInIframe: true,
      asyncContext: event,
    },
      (asyncResult) => {
        asyncResult.value.addEventHandler(Office.EventType.DialogEventReceived,
        (processMessage) => {
          asyncResult.value.close()
          asyncResult.asyncContext.completed({ allowEvent: false })
        }
      )
    }
  )
}
```

**Comment by exextoc** [comment]
@t-ariyoshi30907 Thanks for reaching out. We do have the following questions. 

1. When you mention "I'm seeing unexpected behaviour when I encrypt my email.", does it mean that the email is IRM protected. For more info,

https://docs.microsoft.com/en-us/javascript/api/requirement-sets/outlook/preview-requirement-set/outlook-requirement-set-preview?view=common-js-preview#add-in-activation-on-items-protected-by-information-rights-management-irm

2. It's expected that the add-ins should not get triggered in the Group mailbox. And I am able to repro the issue in a specific order.
It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

Internal tracking id: Eg: Outlook: 2877582

**Comment by t-ariyoshi30907** [comment]
@exextoc 

sorry！I was writing the wrong content. 
It also happens when the email is not encrypted.

my customers are having trouble with this issue. Please fix it as soon as possible so that no error occurs.

**Comment by t-ariyoshi30907** [comment]
@exextoc 
Hi, Could you give me an update on the situation?

and there's one more thing I'd like to ask you about.

When I send an email from outlook on the web and in the Group mailbox, the add-in doesn't launch. 

On the other hand, Outlook for windows.
the add-ins triggered.

Is it supported in Outlook on windows?

**Comment by t-ariyoshi30907** [comment]
@exextoc 
Sorry to bother you again.
I need to explain to the customer, and I would like an answer to the question I asked the other day.

**Comment by t-ariyoshi30907** [comment]
@exextoc 
Hi, Could you give me an update on the situation?
I need to explain to the customer, and I would like an answer to the question I asked the other day.

**Comment by exextoc** [comment]
It's expected that the add-ins should not get triggered in the Group mailbox. This issue is in our backlog. Unfortunately, we do not have any timelines to share at this point.
Internal Tracking id - 160938

**Comment by t-ariyoshi30907** [comment]
@exextoc 
Thank you for your reply. 
Have you decided on a plan to fix it?

by the way, please answer to this question I asked the other day.
```

When I send an email from outlook on the web and in the Group mailbox, the add-in doesn't launch.

On the other hand, Outlook for windows.
the add-ins triggered.

Is it supported in Outlook on windows?
```

**Comment by t-ariyoshi30907** [comment]
@exextoc 
Sorry to bother you again.
Could I have one more question?

I reproduced it with this procedure.

## Steps to reproduce
1. Click on the microsoft365 group folder.
2. Click "New Email".
3. Create and send E-mail.

Is the problem caused by the same cause?

■video
https://drive.google.com/file/d/1FzuUYhPvlzmrWw5aLgx59xShQho7f66k/view?usp=share_link

**Comment by t-ariyoshi30907** [comment]
@exextoc 
Hello,
When I checked the issue today, the same problem was no longer occurring! It seems that when I click on the "Groups" folder while composing an email, the email composition page now closes.
Did you fix the program?

**Comment by t-ariyoshi30907** [comment]
@exextoc

This issue is still ongoing. It has been a long time since we requested improvements. Could you please provide an update on the current status of the response?

**Comment by t-ariyoshi30907** [comment]
@exextoc 
I wanted to reach out with a question. Upon retesting the issue I reported here today, I confirmed that the problem has been resolved. Now, even when sending emails from the group mailbox, the add-in is functioning properly.

However, upon checking the official documentation, it still states that "group mailboxes are not supported."

Which is correct, my test results or the content of the documentation?

**Comment by ajays-msft** [comment]
@t-ariyoshi30907 - Can you please point to the documentation you are referring to?

**Comment by t-ariyoshi30907** [comment]
@ajays-msft 
Hi. I see this page.
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-add-ins-overview#mailbox-items-available-to-add-ins

> Outlook add-ins activate when the user is composing or reading a message or appointment, but not other item types. However, add-ins are not activated if the current message item, in a compose or read form, is one of the following:
>・
>・
>・
> In a [group mailbox](https://learn.microsoft.com/en-us/microsoft-365/admin/create-groups/compare-groups?view=o365-worldwide&preserve-view=true#shared-mailboxes), in a shared mailbox*, in another user's mailbox*, in an [archive mailbox](https://learn.microsoft.com/en-us/office365/servicedescriptions/exchange-online-archiving-service-description/archive-client-and-compliance-&-security-feature-details?tabs=Archive-features#archive-mailbox), or in a public folder.

**Comment by t-ariyoshi30907** [comment]
@ajays-msft 
Two weeks have passed since my last message, and I haven't heard back from you yet. Could you please provide an update on the status of my inquiry?

**Comment by DivyaPatidar** [comment]
@t-ariyoshi30907 We recently fixed #4085 . As message compose is happening from user's mailbox, add-ins would work.

**Comment by t-ariyoshi30907** [comment]
@DivyaPatidar 
Thank you for fixing this bug! And I have a request. Could you please document in the official Office Add-in documentation that the add-in works in a group mailbox? I've provided more details in the following comment:https://github.com/OfficeDev/office-js/issues/2648#issuecomment-2068640535

**Comment by DivyaPatidar** [comment]
@t-ariyoshi30907 At this time, we don't have a planned documentation update, since we undergoing multiple changes. We will update you once we have the documentation ready.

**Comment by t-ariyoshi30907** [comment]
@DivyaPatidar 
Understood, thank you very much!
