### ISSUE TITLE
Deployment for unpkg.com/browse/@microsoft/office-js@1.1.74/dist/powerpoint-win32-16.01.debug.js is corrupted 

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#2649]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi

I want to make a diff between: 
`https://unpkg.com/@microsoft/office-js@1.1.74/dist/powerpoint-win32-16.01.debug.js` and
`https://unpkg.com/@microsoft/office-js@1.1.75-custom.0/dist/powerpoint-win32-16.01.debug.js`

but it seems like the file `https://unpkg.com/@microsoft/office-js@1.1.74/dist/powerpoint-win32-16.01.debug.js` has content corrupted and only has about 300 lines of code.

Can you please fix it? I need to see the changes and if there is something in the new version that can help me bring more features to the office addins.

**Comment by massonj** [comment]
I would recommend the documentation site as the best way to keep up on changes to PowerPoint APIs, anytime we release a new requirement set (collection of APIs) you will see it here - https://docs.microsoft.com/en-us/javascript/api/requirement-sets?view=common-js-preview#powerpoint

**Comment by danielpdev** [comment]
Hi @massonj ,

I fully agree with you, but using `https://unpkg.com/@microsoft/office-js@*` I can dig into the latest changes and it will help me to make a diff between the latest preview versions released and make use of the latest features or bug fixes.

**Comment by danielpdev** [comment]
If you open `https://unpkg.com/@microsoft/office-js@1.1.74/dist/powerpoint-win32-16.01.debug.js` it will display just a chunk of the file and this is not ok.
