### ISSUE TITLE
Event handler best practices with corresponding documentation

### ISSUE THREAD

**Issue by LanceEa** [OfficeDev/office-js#265]
This is a cross-post per @kbrandl suggestion. Please see the following issue from the docs repository:

https://github.com/OfficeDev/office-js-docs-pr/issues/432

## Context

I'm trying to make sure I understand how the new events work to make sure I do not introduce memory leaks into my application.

My scenario is I add a **TableSelectionChanged** event to tables created by my add-in. The handler  reference is then stored so that it can be removed later if a user deletes the table via the add-in. I know that this javascript reference will disappear when a user closes the side-panel of the add-in or refreshes the panel.

A couple of questions:

- What about on the excel-side? Will that event get cleaned up when I close the add-in? 
- The next time I open my add-in I then re-add the event so will excel itself then have two event handlers register? 
- What if a user manually deletes a table and does not delete it through my add-in? I would still have this reference to the handler for that table and this could potentially be a memory-leak if the user keeps the side-panel open for a long time, correct?

Let me know if you need additional information.

Thanks,
Lance

**Comment by JuaneloJuanelo** [comment]
closing as this was solved on the cited documentation thread.
