### ISSUE TITLE
Ribbon api is not supported in Preview APIs for PowerPoint

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#2650]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi,

I've read here: `https://docs.microsoft.com/en-us/javascript/api/requirement-sets/common/ribbon-api-requirement-sets?view=common-js-preview` the following sentences:
* The Ribbon API is supported for production add-ins only in Excel. 
* **It's available as a preview in PowerPoint and Word, but only in Office on Windows (subscription) and Mac.**

from the one above I assume that it works for PowerPoint using the preview APIs and I tried to include:
I've tried using this version: `https://unpkg.com/@microsoft/office-js@1.1.75-custom.0/dist/office.js` and `https://appsforoffice.microsoft.com/lib/1/hosted/office.js` which I've seen are the latest ones, but it does not work.
This call returns `false` => `Office.context.requirements.isSetSupported('RibbonApi', '1.1')`

What can I do next?

PS: I tested on both Mac and Windows and I have the same issue

**Comment by AbidRahman-MSFT** [comment]
Hey @danielpdev - are you still having issues with Ribbon API 1.1 for Mac/Windows on PPT?

**Comment by danielpdev** [comment]
Hi @AbidRahman-MSFT , I will retest with latest version of preview APIs and let you know.

**Comment by danielpdev** [comment]
Hi @AbidRahman-MSFT ,

Sorry for late response, I've tested with the latest preview apis from : `https://appsforoffice.microsoft.com/lib/beta/hosted/office.js` and it still does not work for me.

Thanks.

**Comment by Gayle448** [comment]
Hello, did you solve the issue later? I had the same issue as you.
