### ISSUE TITLE
insertInlinePictureFromBase64 Corrupts Memory in Word

### ISSUE THREAD

**Issue by gullbyrd** [OfficeDev/office-js#2652]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

insertInlinePictureFromBase64 seems to corrupt application memory in Word. 

My Environment:
Platform: Windows 11, PC.
Host: Word Version 2205 Build 15225.20204 Click-to-Run)
 
## Expected behavior
I expect to be able to run my addin against Document A, then create Document B, insert a base64 logo (using either body.insertInlinePictureFromBase64 or paragraph.insertInlinePictureFromBase64), return to Document A and have it behave normally.

## Current behavior
After I create Document B (including the base64 logo) and then return to Document A, Document A is not navigable. I can't scroll, page up / page down, or anything. There is a blurry second image of the document in the background, and this seems to scroll although it comes and goes. Sometimes the document text disappears completely. The length of the base64 is only 2700 bytes. The image displays normally in Document B.  If I do not include the base64 image, the problem goes away.

## Steps to reproduce
0. Open a document with a few pages of text so scrolling and paging can be tested.
1. Using Office.js (latest production version), create a new document.
2. Insert a base64 image. 
3. Open the new document.
4. Close the new document and return to the original document.
5. Try to scroll.

**Comment by GavinGu07** [comment]
Thanks for reporting @gullbyrd. We have reproduced your issue and created a work item on it. We will keep track on this issue and let you know if there are any updates.

**Comment by jipyua** [comment]
hi @gullbyrd , for this issue per my testing on latest build 16.0.17531, this issue doesn't reproduce anymore and should have been fixed. please feel free to update to the latest build and have a try. thanks.
