### ISSUE TITLE
Word add-ins now disappear each time I reopen Word

### ISSUE THREAD

**Issue by pb-jeff-oneill** [OfficeDev/office-js#2653]
Normally, once you install a Word add-in, the add-in is there each time you open a Word document.  As of today, the add-ins disappeared each time I closed and reopened Word.  I had to go to the Insert ribbon to re-add them.

There were two problems:
1. The add-ins disappeared each time I closed and reopened Word.
2. It seems than an older version of my add-in was installed.  One button was missing in the ribbon of my add-in and this was the most recently added button.

I found a fix, but most people wouldn't try this and I don't know if it will be permanent:
- Go to Insert ribbon -> My Add-ins
- Normally this would open a dialog showing the add-ins that were previously installed, but it was showing no add-ins and had a message to install add-ins from the Microsoft store.  No add-ins were shown here even though I had re-added them as indicated above and you could see them in the ribbon.
- This dialog has a refresh button in the top right corner.  Clicking the refresh caused the above problems to go away.

This has fixed both problems:
- Add-ins now stay after closing and reopening Word
- All of my add-in buttons are shown so it seems to be the latest version of my add-in

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac 12.4
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.62
* Operating System: Mac 12.4
* Browser (if using Office on the web): N/A

**Comment by alison-mk** [comment]
Hi @pb-jeff-oneill, thank you for reporting this issue! I've assigned it to @grangeryy who should be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by grangeryy** [comment]
@pb-jeff-oneill, do you still reproduce the issue? And does it happen for a specific add-in or also happen to multiple different add-ins? I'm also adding @AbidRahman-MSFT to see if he's aware of this problem.

**Comment by pb-jeff-oneill** [comment]
I am no longer able to reproduce this.

**Comment by wangyun-microsoft** [comment]
@pb-jeff-oneill If you could no longer reproduce this, I'll close this one. Please reopen when needed. Thanks.
