### ISSUE TITLE
Removed Excel online add-in results in task pane with "Trust this add-in" button

### ISSUE THREAD

**Issue by ronald-forscale** [OfficeDev/office-js#2654]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# After clicking Remove and re-opening the spreadsheet, a task pane with "Trust this add-in" button appears. Decline results in the same task pane the next time, which is very annoying for the user and the developer who gets the blame.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome, Edge
 
## Expected behavior
After removing the add-in, it should not be mentioned anymore when opening the spreadsheet.

## Current behavior
The initial assumption of the cause of the problem was that the add-in uses the feature to open the task pane with a document, but removing this feature from the code and manifest file, the issue remained. https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document

## Steps to reproduce

1. Install the **ProjectSheet - Gantt chart** add-in from the Office Store using **Insert > Office Add-ins > STORE**
2. Remove the add-in using **Insert > Office Add-ins > MY ADD_INS**
3. A dialog appears that states the add-in is hidden in the Microsoft account, click Remove
4.  After re-opening the spreadsheet, a task pane with "Trust this add-in" button appears, mentioning the add-in.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context
Users of the add-in complain that it cannot be removed, they call it intruding. They assume the task pane with **Trust this add-in** button is coming from the add-in, which is not the case.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 
![remove add-in](https://user-images.githubusercontent.com/83950151/174763548-4cd110d9-dbc6-4144-90ee-dbf9f0bb626a.PNG)
![trust this add-in](https://user-images.githubusercontent.com/83950151/174763198-835a9670-c41f-4e9a-812b-dbcee148988e.PNG)

**Comment by alison-mk** [comment]
Hi @ronald-forscale, thank you for submitting this issue. I've assigned it to @guliums who should be able to provide you with more information or help resolve the issue. 

Cheers,
Alison
