### ISSUE TITLE
Outlook on-send Add-In freezing when open a dialog in Desktop

### ISSUE THREAD

**Issue by moshikon** [OfficeDev/office-js#2656]
Our Add-In is using the On-Send functionality and it used to work for both OWB and Desktop without any problems.

Our users started to notice that on Outlook for Mac when the on-send is triggered and opens a modal, Outlook is freezing and not responding.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.63 (22061407)
* Operating System: macOS
 
## Expected behavior
Outlook not freezing and user can interact with the modal.

## Current behavior
Outlook for Mac is freezing and not responding when the on-send is triggered and opens a modal.

## Link to live example(s)
https://user-images.githubusercontent.com/16401242/174957942-cb143200-087f-473b-95d0-911dce334d56.mov
![image](https://user-images.githubusercontent.com/16401242/174956796-239e824e-c10d-4124-ad4a-4c9a266f4995.png)

## Context
Users are not able to use Outlook for Mac Desktop without uninstall the add-in.

## Useful logs
[Microsoft Error Reporting log version.txt](https://github.com/OfficeDev/office-js/files/8954927/Microsoft.Error.Reporting.log.version.txt)

Collect Diagnostics: G5KG774C

**Comment by exextoc** [comment]
@moshikon We tried with a few of our onSend add-ins and it worked as expected. Can you please share the manifest of your add-in so that we can try to repro the issue and debug it?

**Comment by moshikon** [comment]
@exextoc https://aka.ms/li-gong-plugin/scheduling_add_in.xml

**Comment by codexeon** [comment]
This issue only exists in Insider Beta version 22061407, it will be fixed in the next Insider Beta release but until that is available you can switch to Current Channel or Current Channel (Preview) which does not have the issue. To switch channels, use Help > Check for Updates > Advance > Update Channel

**Comment by exextoc** [comment]
@moshikon Can you please try the same on the latest version and let us know if it's still reproducible?

**Comment by moshikon** [comment]
@exextoc Is there an option to downgrade my Outlook Desktop version with the Microsoft AutoUpdate tool?

**Comment by exextoc** [comment]
@moshikon  Yes, please refer to https://docs.microsoft.com/en-gb/officeupdates/update-history-office-for-mac
