### ISSUE TITLE
internetMessageId changes after sending - Outlook Desktop client draft email

### ISSUE THREAD

**Issue by jonoshearman** [OfficeDev/office-js#2659]
Main problem: internetMessageId changes after sending draft email only on Outlook Desktop client

## Provide required information needed to triage your issue
We are using an Outlook addin to save a draft email and retrieve message.id and message.internetMessageId from the graph.
We store these values in order to be able to find the email on the graph at a later stage after sending in order to process through our CRM system.

This process works perfectly on Outlook Web (OWA) - a message with the same internetMessageId will exist in the user's Sent folder and we can query the graph and retrieve it.

However, on Outlook Desktop both these ids change significantly. The office-js documentation does state that the message id will change if the folder changes so we expect that change. The issue here is that internetMessageId also changes and so there is no way to retrieve this same email without going down the CustomProperties route which we'd prefer to avoid if possible.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Windows desktop client
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: "Microsoft® Outlook® for Microsoft 365 MSO (Version 2203 Build 16.0.15028.20242)"
* Operating System: Windows 10 build 19044.1766
* Browser (if using Office on the web): -
* extra details - the user is connected to Exchange in cached mode
 
## Expected behavior
Ideally one of these ids should be consistent so that we can retrieve the email after sending. I would expect the internetMessageId to be the more permanent one here.

## Current behavior
Currently both Message.id and Message.internetMessageId change significantly after sending an email on the Outlook Desktop client.
This makes it impossible to locate the email after it's sent

## Steps to reproduce

1. Compose a new message in outlook desktop
2. In an addin, save the draft:
`Office.context.mailbox.item.saveAsync`
3. then retrieve the itemId:
`Office.context.mailbox.item.getItemIdAsync`
4. then send this itemId with an accessToken to some backend service that will contact the graph using this same ID
5. eg request /me/messages/{ItemIdFromAddin}
6. This will successfully return a Message Object with both id and internetMessageId set.
7. save these ids somewhere.
8. Go back to the Outlook Desktop client and send the draft message.
9. If you run the same request to the graph on the backend service it will return 404.
either `/me/messages/{itemId}` or `/me/mailFolders/SentItems/messages?$filter=internetMessageId eq {internetMessageId}`
10.  changing the request to /me/mailFolders/SentItems you can see the newly sent email at the top but both ids are completely different. 

## Link to live example(s)
--

# Provide additional details
--

## Context
The context for us is we are storing crm details about an email, filed through our addin. We rely on the email ids to identify the email after sending. Other github issues have mentioned using CustomProperties or internet message headers, but this seems to be an issue with Outlook Desktop rather than a compose/sent id problem as it works fine with Outlook Web.

## Useful logs
--

**Comment by alison-mk** [comment]
Hi @jonoshearman, thank you for submitting this issue! I've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by Oleg-O** [comment]
Hi @jonoshearman, why do you want to avoid the CustomProperties route?

**Comment by justisfaulkner** [comment]
Running into the same issue with the changing `internetMessageId`s if a draft is later sent by a user using the classic Outlook desktop.

Since we can not control which client's our end users utilize, our downstream behavior which relies on `internetMessageId` as our durable source of truth is unreliable due to this bug.
