### ISSUE TITLE
Create meeting with google addon and invite O365 user in google calendar，After opening the event on Outlook in the MAC, click the join button and report an error

### ISSUE THREAD

**Issue by echowwl** [OfficeDev/office-js#2660]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

1. create a meeting in google calendar by google addon:
![image](https://user-images.githubusercontent.com/105787768/175261165-aae039d9-94f7-4714-9c73-4f9267a972e5.png)
2. click the event in the outlook calendar:
![image](https://user-images.githubusercontent.com/105787768/175263654-a4ea7c00-7804-43f7-bb10-5d835ec65037.png)
3.get the error:
![image](https://user-images.githubusercontent.com/105787768/175263702-2e6c6d30-df49-4dbf-aacf-f2f989b499a4.png)
4.open the invitation:
![image](https://user-images.githubusercontent.com/105787768/175263877-97c4fdb1-350e-4f6a-abfa-930540910382.png)

**Comment by exextoc** [comment]
@echowwl Thanks for reporting this issue regarding the issue in join experience. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

Internal tracking id: Eg: Office: 2890596

**Comment by echowwl** [comment]
We have added a join link to the email template, why do some "join" buttons of different email templates can jump normally, while others cannot, and the error The application can't be opened is reported?

**System version information is:**
macos monterey, version 12.3.1
outlook version:16.62
1. normally jump:
![image](https://user-images.githubusercontent.com/105787768/184787422-afc28edc-eff7-461a-afd2-fb59d7e4f2b8.png)

2. error report
![image](https://user-images.githubusercontent.com/105787768/184787831-e371d96c-1860-4d5d-b478-118a067c2b59.png)
![image](https://user-images.githubusercontent.com/105787768/184787841-33224112-1bb8-4b36-bf0f-8aaffa13d57a.png)
![image](https://user-images.githubusercontent.com/105787768/184787850-a0ed3b95-0e73-4d5e-9f78-ceeda45ae8e8.png)
