### ISSUE TITLE
ItemSend times out when office.js fails to load

### ISSUE THREAD

**Issue by milankonir** [OfficeDev/office-js#2661]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.62
* Operating System: macOS Monterey 12.4
* Browser (if using Office on the web): N/A
 
## Expected behavior

When office.js fails to load during `ItemSend` execution (script error or network error), the Send process should be terminated with an error that office-js platform failed to initialize.

## Current behavior

When office.js fails to load during `ItemSend`, the send is stuck until the 5 minutes timeout is hit.

## Steps to reproduce

1. Block Office CDN or introduce script error into the office.js script
2. Install any `ItemSend` add-in
3. Compose new message and send
4. The send is stuck for five minutes

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

## Context

Script / network failures during office.js initialisation can happen, but the platform should gracefully handle them and terminate the send. Instead, user is stuck for five minutes. Only after that, they are able to retry the send.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by alison-mk** [comment]
Hi @milankonir, thank you for submitting this issue! I've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by exextoc** [comment]
@milankonir  Can you please be more specific with the problem? Are you facing office.js load problem in the add-in or are you trying to create the error programmatically?
As if there is an issue in the loading office.js, we show an error almost immediately.

**Comment by milankonir** [comment]
@exextoc We are facing issues with office.js load within our add-in - our crash telemetry in Rollbar shows cases where `Office` namespace is not defined during our add-in scripts execution even tho the `<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>` is correctly ordered as the first script in the add-in index / commands page. This means the office-js either failed to load / execute.

Based on that we simulated the conditions locally by network blocking `appsforoffice.microsoft.com`.

With that, we have observed that on Windows, the error is shown almost immediately, in OWA it takes a a little bit longer (we would be ok with that).
The problem is the **Mac** platform where there is no error until the 5 minutes onSend timeout is hit.

**Comment by exextoc** [comment]
Thanks @milankonir for providing these details for better clarity.

One more thing: Are you using "Outlook Mac New UI" or  "Outlook Mac Old UI" when testing this?

We tried this internally with "Outlook Mac New UI" and are not able to repro with "blocking office.js network call". We observe that "Send" immediately fails with error message.

Is it possible for you to share your addin (only necessary things) so that we can try repro-ing with you addin?

**Comment by milankonir** [comment]
The way I reproduce this:

1. Install following add-in https://github.com/milankonir/onsend-prevent-addin (it does not have any `ItemSend` handling besides `event.completed({ allowEvent: false });`)
2. Add `127.0.0.1       appsforoffice.microsoft.com` entry into hosts file (simulates office-js scripts to be unreachable)
3. Make sure that the office-js scripts are not network cached (for Outlook for Mac `rm -fr ~/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/WebKit/NetworkCache`)

The behaviour:
1. Outlook for Windows: https://share.getcloudapp.com/rRuObnxx  - times out in couple seconds ✅ 
2. Outlook Web Access: https://share.getcloudapp.com/OAu8nxXN - times out in couple seconds ✅ 
3. Outlook for Mac Old UI: https://share.getcloudapp.com/Wnu70AgB - processing until the 5 minutes timeout is hit (the video is cut after one minute) ❌ 
4. Outlook for Mac New UI: https://share.getcloudapp.com/jkuX4y5O - processing until the 5 minutes timeout is hit (the video is cut after one minute) ❌ 

As you can see, the problem affects both new and old Outlook for Mac. I'd expect the Mac platform to have some shorter timeout when office-js scripts fail to initialise similar to Windows and OWA.

**Comment by exextoc** [comment]
Thanks @milankonir for providing these details. We are trying out again to repro this with these steps.

**Comment by exextoc** [comment]
Hi @milankonir, we don't have a solid repro at this point. Could you please share a video showing the repro steps and also share the diagnostic logs to help us investigate this issue quicker? Thanks!

**Comment by milankonir** [comment]
@exextoc Here are the full steps to reproduce including cloning the test add-in and installing it into the Outlook https://share.getcloudapp.com/mXuxbzG1

**Comment by exextoc** [comment]
We are able to repro this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point 
Internal tracking id: [6304800]

**Comment by eldhose-peter-imanage** [comment]
@exextoc When office.js fails to load ItemSend execution (network error), is there a way to allow "Send" even if the add-in fails.

**Comment by exextoc** [comment]
We recommend using the On send APIs with smart alert instead of on Send APIs. 
Please implement to new API to resolve the issue. You can find the documentation here - https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest
