### ISSUE TITLE
Office.CustomProperties.saveAsync slowness on Outlook for Mac

### ISSUE THREAD

**Issue by milankonir** [OfficeDev/office-js#2666]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook (new UI)
* Office version number: 16.62 (22061100)
* Operating System: macOS Monterey 12.4
* Browser (if using Office on the web): N/A
 
## Expected behavior

We assume that Outlook for Mac uses cached mode and update to custom properties should be a local operation.

## Current behavior

It takes considerably longer to save custom properties in Outlook for Mac even compared to OWA which runs a network request when saving custom properties

## Steps to reproduce

N/A

## Link to live example(s)

Here are some data from outer telemetry the columns are percentiles (in how big % of cases it took longer than xxx to save custom properties) grouped by platform.
The `Mac` platform is the old Mac UI (note that we have a limited amount of telemetry there as most of our users switched to new UI),  the `MacNew` is the new Mac UI.

As you can see, `Mac` performs considerably worse than even the web where it almost always takes more than 200ms to save custom properties and in 7% of cases it even takes more than 10 seconds.

![image](https://user-images.githubusercontent.com/72383088/175965424-d3fb9cd4-d9a2-4182-8a7b-1157de12e47f.png)

# Provide additional details

N/A

## Context

We update custom properties both from the panel and in the `ItemSend` handler. It's especially a problem in the `ItemSend` where it creates unpleasant delays in email sending.
Is there any explanation why the Mac platform performs worse than other platforms? Does Microsoft collect any performance metrics they can look into?

## Useful logs

N/A

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by preethikakiru** [comment]
Hi @milankonir, thanks for making us aware of this issue! I have assigned it to @ajays-msft who should be able to give you more insight and information to help resolve this for the future. 
Best, 
Preethika

**Comment by milankonir** [comment]
Thanks for the quick response @preethikakiru 

On top of our telemetry data, I have also played with following Gist (it just loads custom properties, sets one simple value and saves them): https://gist.github.com/milankonir/de0b55f80c2b9e39c23d38d714b060e5

In new Outlook UI for Mac, the save consistently takes over ~400ms on my machine:

![image](https://user-images.githubusercontent.com/72383088/176036697-0a263f8a-6974-4c3d-b2c9-ed47a25e38fe.png)

If I switch back to the old Outlook UI for Mac, the first save takes only ~40ms and subsequent saves even less (~10ms):

![image](https://user-images.githubusercontent.com/72383088/176036808-6bb9e618-f5ea-41de-a082-0fd561f60be4.png)

-----------

Maybe related, I can see somewhat similar performance degradation in the `Office.context.mailbox.item.getItemIdAsync` API. In the new UI, the first call to this API always takes ~200 ms or more, while in the old UI it only takes ~19 ms.

Similar to the `saveAsync`, I'd expect the `getItemIdAsync` to be a local operation (as even the documentation suggests for Outlooks running in cached mode). Let me know if you'd like a separate issue for tracking this.

**Comment by exextoc** [comment]
Thanks for reporting this issue. We will try to repro this inhouse using script-labe script and get back to you soon.

**Comment by exextoc** [comment]
Hi @milankonir, thanks for reporting this issue regarding new UI. It has been put on our backlog. We unfortunately have no timelines to share at this point. 

Internal tracking id: Office: 2896680

**Comment by exextoc** [comment]
This issue has been fixed.
