### ISSUE TITLE
Getting error as `The file format and extension of *.htm doesn't match`

### ISSUE THREAD

**Issue by gopinathshiva** [OfficeDev/office-js#2667]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

In Mac, when a user tries to install the product for the first time, they get an alert "The file format and extension of "***.htm" doesn't match. the file could be corrupt or unsafe". Do you want to open it?

Can someone pls help me on how to resolve this issue ?

## Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: latest from Office CDN
 
## Expected behavior
User should not get an alert stating the file could be corrupt or unsafe

## Current behavior
User is getting an alert stating the file could be corrupt or unsafe

**Comment by preethikakiru** [comment]
Hi @gopinathshiva, thank you for making us aware of this issue! Just to clarify, so when a user tries to install your excel add-in on Mac they receive an alert that the add-in might be corrupt?

**Comment by gopinathshiva** [comment]
yes @preethikakiru . This is the message shown to the user **The file format and extension of "Spreadsheet-Sync.htm" doesn't match. the file could be corrupt or unsafe. Do you want to open ?**

**Comment by JHJ-MS** [comment]
Is your add-in an Office-JS-Addin or COM add-in? Has your add-in been published to the add-in store? If so, could we know its name to have a try to repro this issue? Or a screenshot is also helpful.

**Comment by gopinathshiva** [comment]
@JHJ-MS Thanks for the reply.

It is an Office-JS-Addin. It is already available in the store with name Spreadsheet Sync - https://pages.store.office.com/addinsinstallpage.aspx?rs=en-GB&assetid=WA200003784&isWac=True&ui=en-US&ad=GB

**Comment by alettieri** [comment]
I'll drop a comment here, because we are experiencing the same issue. https://appsource.microsoft.com/en-us/product/office/WA200003983

**Comment by gopinathshiva** [comment]
@alettieri any update on this ?
