### ISSUE TITLE
Checking for a feature/requirement set does not work in Outlook desktop (Windows)

### ISSUE THREAD

**Issue by ghelyar** [OfficeDev/office-js#2668]
# Provide required information needed to triage your issue
There doesn't seem to be any way to reliably check for the availability of a requirement set or feature on Outlook desktop for Windows when running from event-based activation.

Our add-in targets 1.10 as a minimum version, but uses `Office.SessionData` from requirement set 1.11 to provide extra functionality if it's available.

[The documentation](https://docs.microsoft.com/en-us/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets?view=common-js-preview#using-apis-from-later-requirement-sets) says this should be possible by either using `Office.context.requirements.isSetSupported('Mailbox', '1.11')` or checking whether `Office.context.mailbox.item.sessionData.*` exist before using them,

However, when running from the semi-annual channel, which is currently on version 2108, which is requirement set 1.10, neither of these options work. I also found `Office.isSetSupported` and `OfficeRuntime.apiInformation.isSetSupported` while trying to find a way to do this, and neither of these worked either.

Checking for the existence of `Office.context.mailbox.item.sessionData.getAsync` results in the API being called, but then throws an error when calling it:
> The feature sessionData.getAsync, is only enabled on the beta api endpoint

Checking with `Office.context.requirements.isSetSupported`, `Office.isSetSupported` and `OfficeRuntime.apiInformation.isSetSupported` all result in an undefined reference error e.g.
> Unable to get property 'isSetSupported' of undefined or null reference

When digging into this, I found that `Office.context.requirements`, `OfficeRuntime.apiInformation` and `Office.isSetSupported` are all undefined when running from event-based activation on Outlook desktop.

## Your Environment

* Platform: Windows desktop
* Host: Outlook
* Office version number: 16.0.14326.21018
* Operating System: Windows 10 21H2
 
## Expected behavior

- `isSetSupported` functions and their parent objects should always exist, and should safely return a boolean value depending on whether the requirement set is supported.
- Checking for the presence of a function should work as documented. It's no good checking that a function exists and then when you try to use it, it throws an error saying that it isn't available in this version.
- The documentation should say when you should use each of the 4 supposedly available options, and what the difference is between them (even if that difference is just the version in which they became available)

## Current behavior

- `isSetSupported` throws undefined reference errors
- Checking the presence of a function does not mean that the function is actually supported in that version.

## Steps to reproduce

1. Install Outlook semi-annual with requirement set < 1.11 e.g.
```xml
<Configuration ID="1b5f8161-1ef0-492b-a137-567429be600d">
  <Add OfficeClientEdition="64" Channel="SemiAnnual" Version="16.0.14326.21018">
    <Product ID="O365ProPlusRetail">
      <Language ID="en-us" />
      <ExcludeApp ID="Access" />
      <ExcludeApp ID="Excel" />
      <ExcludeApp ID="Groove" />
      <ExcludeApp ID="Lync" />
      <ExcludeApp ID="OneDrive" />
      <ExcludeApp ID="OneNote" />
      <ExcludeApp ID="PowerPoint" />
      <ExcludeApp ID="Publisher" />
      <ExcludeApp ID="Teams" />
      <ExcludeApp ID="Word" />
      <ExcludeApp ID="Bing" />
    </Product>
  </Add>
  <Updates Enabled="FALSE" />
  <RemoveMSI />
</Configuration>
```
2. Follow the quick start for event-based activation
3. Try to use `Office.context.requirements.isSetSupported('Mailbox', '1.11')` or any of the other options listed above.

**Comment by preethikakiru** [comment]
Hi @ghelyar, thank you for making us aware of this! I have assigned this issue to @JuaneloJuanelo and @samantharamon who will be able give your more information that will help you get to a resolution.

**Comment by exextoc** [comment]
@ghelyar, this has been fixed in the newest versions of the Semi-Annual Channel, which will be released soon. We are going to update our documentation to reflect what you pointed out. The checks that you performed are all valid, however, won't been needed any more in the upcoming Semi-Annual Channel release.

**Comment by ghelyar** [comment]
Thanks for the update.

> won't been needed any more in the upcoming Semi-Annual Channel release.

Does this mean that semi-annual channel will be updated to some version that meets requirement set 1.11, so SessionData will work from SAC in the upcoming release, but it would still be needed for future requirement sets?

**Comment by exextoc** [comment]
In general, we don't add new features to older releases, so unfortunately, the 16.0.14326.* Semi-Annual Channel release will not be updated to support requirement set 1.11. It will stay on 1.10.
