### ISSUE TITLE
Word Online: SmartArt disappears from document

### ISSUE THREAD

**Issue by abhijeetnarvekar** [OfficeDev/office-js#267]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi,

Unexpected Behavior: 
If SmartArt is selected and context.document.getSelection(); API is called, SmartArt itself disappears from document.

Expected Behavior:
API document.geSelection() should not corrupt document.

Video and document attached for the issue:
https://drive.google.com/open?id=1zHb-pEhI2NVVetU8MBTdmDT-L_4i5Znp

Steps to reproduce:
1. Open document with SmartArt
2. Select SmartArt
3. Run the following code.

```
Word.run(function (context) {    
    var range = context.document.getSelection();	
    return context.sync().then(function () {		
        console.log('Inserted the text at the end of the selection.');		
    });  
}).catch(function (error) {
    console.log('Error: ' + JSON.stringify(error));
    if (error instanceof OfficeExtension.Error) {
        console.log('Debug info: ' + JSON.stringify(error.debugInfo));
    }
});
```

4. Wait for 10-15 secs
5. Refresh document(f5)
6. SmartArt disappears 

Does anyone know why this happens? Is there any solution or workaround?

Thanks,
Abhijeet

**Comment by XuanZhouMSFT** [comment]
It's a known issue and we are actively investigating it. Tracked by internal bug 2641084.

**Comment by abhijeetnarvekar** [comment]
@XuanZhouMSFT is there any workaround you know to preserve the SmartArt?
