### ISSUE TITLE
Allow .msg file export through JS add-in API in Outlook-Desktop

### ISSUE THREAD

**Issue by mspiess** [OfficeDev/office-js#2671]
Feature Request:
I'd like to create an add-in which create a .msg file of an email and sends it to a remote server for archival purposes.
Outlook already can create .msg files through the "Save as..." dialog but this functionality is not exposed to the Office API.

I could access all relevant information through the API and create an .eml file for example (or use EWS/graph-API for that), but I'd prefer to leverage the existing outlook functionality.

 

I suggest a method `getMsgFileAsync( options: Office.AsyncContextOptions, callback?: (asyncResult: Office.AsyncResult<ArrayBuffer>) => void): void` on the `Office.context.mailbox.item` object.

As far as permissions go, "ItemRead" should suffice.

**Comment by preethikakiru** [comment]
Thanks for sharing your request @mspiess, I assigned this issue to @JuaneloJuanelo who will be able to provide you with more information moving forward.

**Comment by preethikakiru** [comment]
I actually reassigned this issue to @exextoc.

**Comment by Oleg-O** [comment]
Hi Marco, looks like you've already [added this](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/allow-msg-file-export-through-js-add-in-api-in-outlook-desktop/idi-p/3561260) as a new feature idea on our Tech Community page - that's the right way to request it. We review those regularly and consider adding them to our backlog.

**Comment by jneilliii** [comment]
How are we to know when/if this gets integrated if there's no issue open to track it's progress. I've commented on the feature request on the community forum, but it seems short-sided that this option isn't already available when the "New Outlook" is completely eliminating the ability to use VSTO or VBA add-ins.

**Comment by billyStp** [comment]
I need this feature as soon as possible ! That will be a great feature to add in office.js for Outlook.  It will make the work with more easier... as it will advoid us to use EWS or Graph API.
