### ISSUE TITLE
PowerPoint: Unexpected behavior of slide insertion using office.js

### ISSUE THREAD

**Issue by estet** [OfficeDev/office-js#2672]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Something strange happens to a slide inserted using office.js

![image](https://user-images.githubusercontent.com/604635/176441180-1efd1558-6810-4924-a098-fbec52fbfba7.png)

Code that is used:
```           
originalSlideUrl = '...';
const options = {
              formatting: 'UseDestinationTheme',
              targetSlideId: `${targetSlideId}#`,
};
context.presentation.insertSlidesFromBase64(originalSlideUrl, options);
```

But the same slide inserted by copying from one PowerPoint instance into another using Destination Theme formatting gives different result:
![image](https://user-images.githubusercontent.com/604635/176441672-0455ca7d-694c-4546-bd6c-1db70d1a9b59.png)

## Environment
Platform: Office Online
Host: PowerPoint
Operating System: Windows 10
Browser: Chrome
 
## Expected behavior
Office.js should follow behavior of slide insertion in PowerPoint for Desktop

## Current behavior
Pagination goes off it's place

## Link to live example(s)
1. Content to reproduce the issue could be found in this repo https://github.com/estet/SlideInsertioOfficeJsIssue

**Comment by preethikakiru** [comment]
Thanks for submitting this issue @estet, I've assigned it to @LuyiH who should be able to provide you with more information to help you resolve this issue.

**Comment by LuyiH** [comment]
@wangyun-microsoft   please help follow this question

**Comment by wangyun-microsoft** [comment]
I'm adding Onur into this one as well. 

@ononder can you please look at this one?

Thanks.

**Comment by estet** [comment]
@preethikakiru @ononder @wangyun-microsoft Do you need any other information to speed up the resolution?

**Comment by wangyun-microsoft** [comment]
Thanks for reaching out. Unfortunately, we don't have a target date to provide a fix for now.

**Comment by estet** [comment]
Thanks for responding @wangyun-microsoft. 

This is a problem for our product - the same functionality gives different results depending on a platform (VSTO/Web Add-ins)
