### ISSUE TITLE
setSignatureAsync fails with InternalError

### ISSUE THREAD

**Issue by barclayadam** [OfficeDev/office-js#2673]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2203 Build 16.0.15028.20282
* Operating System: Windows
 
## Expected behavior
When calling setSignatureAsync no error occurs and the signature is set on the body of the email

## Current behavior
For at least one of our users in a large company, when trying to set their signature from an event-based activation add-on (or task pane) the call fails with the error:

`{"name":"InternalError","message":"The operation failed.","code":5001}`

This customer has hundreds of users, who should all have the same build, and they have only reported the error for this one user so far.

## Steps to reproduce
We cannot reproduce this for other users on the same platform / version. We, therefore, need to know what other information you may need to diagnose what is happening for this user, and why they cannot set a signature.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by preethikakiru** [comment]
Thanks for submitting this issue @barclayadam, I've assigned this to @exextoc who will be able to give you more information moving forward.

**Comment by JuaneloJuanelo** [comment]
@barclayadam  do you have more details on what OS is this? (windows 8, windows 10?)
Also there are new builds available for that Channel, is the user applying those updates? 

Btw the other aspect you want to check is if the user is inserting the image on Plain text mode. you might get an error there.

**Comment by JuaneloJuanelo** [comment]
Tried insert signature on that build and it works. Closing as non-reproducible.

**Comment by barclayadam** [comment]
@JuaneloJuanelo our customer has confirmed that they have this version of Outlook (as per original submission) & Windows 10 Enterprise 20H2 19042.1766 on approximately 1200 machines, but only a single user appears to be having this issue at this time.

The customer has said, as a test, they could try upgrading this single user. Before they do that, would it be helpful if we can try to get any logs?

**Comment by barclayadam** [comment]
Further to the above, this user has been upgraded to "Microsoft 365 Apps Update - Monthly Enterprise Channel Extended Quality Update for x64 based Edition Version 2204 (Build 15128.20312)" and the issue persists.
