### ISSUE TITLE
Outlook Mac Client with new UI, can't set enhanced location

### ISSUE THREAD

**Issue by dimitarbikov** [OfficeDev/office-js#2677]
We have an add-in that searches for rooms and sets them as an enhancedLocation.
It does not set the enhancedLocation on Mac Outlook client version 16.62 with the new UI.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:  Mac Outlook client v16.62 with the new UI enabled
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number:  The Office JavaScript API library that can be accessed via the Office JS content delivery network (CDN)
* Operating System: Mac
 
## Expected behavior

When we set enhancedLocation by 
`Office.context.mailbox.item.enhancedLocation.addAsync({
            id: "somemail@asd.com",
            type: Office.MailboxEnums.LocationType.Room,
        })`
        
 And after calling getAsync on the enhancedLocation should return the enchancedLocation array with the 1 entry.

## Current behavior
When we call getAsync on the enhancedLocation it returns empty array.
IMPORTANT: The resource does get added to the location field in the UI, as in, we can see the name of it added, but 
when submitting the event, there is no invitation sent to that resource. 
This happens only on our meeting rooms that are on Exchange, and only on the Outlook for Mac v16.62 with the new UI.
Switching to the old UI on the same Outlook for Mac version ( 16.62) fixes that issue. 
Version 16.61 also works as indented, as well as the Windows Outlook Client running with the new UI.

## Steps to reproduce

1. Open a new Event view ( AppointmentCompose Context ) in the Mac Outlook client v16.62 with the New UI enabled.
2. Call Office.context.mailbox.item.enhancedLocation.addAsync() with a meeting room that's on exchange. ( this is important, because using dummy data actually works, example:  { id:"test@test.com", type: Office.MailboxEnums.LocationType.Room } )
3. Observe that the resource gets added by its name to the location field in the UI.
4. Call Office.context.mailbox.item.enhancedLocation.getAsync() and check if the meeting room has been set. 

## Link to live example(s)
1. Script lab example: (https://gist.github.com/dimitarbikov/53e0fec55f3f5b4860e56a2bde63f28a)

## Context

We have an add-in that searches for meeting rooms and adds them as a location on the Events. 
Users that will use the newest version of Outlook for Mac and have switched to the new UI will have the impression that the room is added as a location for the Event, but no invitation will be sent to that room.

## Useful logs

- [yes ] Screenshots
On OWA :
![Screenshot 2022-06-30 113052](https://user-images.githubusercontent.com/99324259/176643629-02089945-1544-453c-a4c4-c433d2e179b1.png)
Mac Outlook client 16.62 new UI

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/99324259/176645552-71b263c9-0f4b-473e-b07c-b2f677bab8ce.png)

**Comment by exextoc** [comment]
Hi @dimitarbikov, thanks for reporting this issue regarding enhancedLocation. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: 2906045

**Comment by dimitarbikov** [comment]
Hello team and @ajays-msft 

Can we get an update on this?

**Comment by dimitarbikov** [comment]
Hello @exextoc, @preethikakiru  and @ajays-msft . Any update on this?

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 16.65.825.0 (16.65.22082501) or later. When an updated build is available depends on the release channel a customer is on. 

[Outlook Add-ins Engineering Team]
