### ISSUE TITLE
Office Init ERROR TypeError: Cannot read properties of undefined (reading 'getSharedPropertiesAsync') only on select users

### ISSUE THREAD

**Issue by bconners1005** [OfficeDev/office-js#2678]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
We are currently running into an issue with a user running Chrome 103.0.5060.53 wherein the add-in is not loading on Outlook on the Web due to the above error.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Mac OS 12.3.1
* Browser (if using Office on the web): Chrome
 
## Expected behavior

When loading the add-in and checking if features/information is available getSharedPropertiesAsync should not be returning undefined and throwing termination errors to the system.

## Current behavior

When the system loads the system and hits the check for getSharedPropertiesAsync the system throws an init error from OfficeJS saying the property is undefined.

## Steps to reproduce

1. Create a simple app wherein you check item.getSharedPropertiesAsync method for undefined
2. Open plug-in with check
3. If issue procs getSharedPropertiesAsync will return undefined check and system will terminate

# Provide additional details

1. This issue seems to be sporadic as I could not reproduce it, but could see it live on the user in question

## Context

This issue is blocking a sales team from inputting valuable data on potential clients.  We could disable the feature but it would require code time and then deployment interruptions for other users.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Office Init ERROR TypeError: Cannot read properties of undefined (reading 'getSharedPropertiesAsync')
Specific line in question: diagnosticObject.officeAPIEnvSettings.isDelegatedAccess = !!_Item.getSharedPropertiesAsync where _Item is defined with the current item selected in OWA.

**Comment by exextoc** [comment]
@bconners1005 Thank you for reaching out about this. Are you able to reproduce this in any other Outlook Platform (Windows, Mac, mobile, etc.)? Or is this something you are only seeing on Outlook on the web?

**Comment by bconners1005** [comment]
@exextoc We are unable to open the add-in on anything other than OWA because of Safari restrictions that blocks all access to our code due to the new-ish security implementations on newer Mac OS versions past Big Sur.

**Comment by exextoc** [comment]
@bconners1005 I see you mentioned above that you cannot consistently reproduced this issue, but you can see it live for a particular user. Is this issue consistent for that particular user or also sporadic?

**Comment by bconners1005** [comment]
@exextoc it is consistent.  It will happen every time the user opens the add-in on Chrome.

**Comment by exextoc** [comment]
Can you please help with following queries:
1. Is the issue only reproducible for one user while same add-in works fine for all other users?
2. Is the add-in working fine in all other browsers? And is it working fine in outlook Desktop?
3. Is the user calling the getSharedPropertiesAsync API from the item from delegated mailbox?
4. If possible, can you share the manifest and the code snippet with us to understand the issue more.
