### ISSUE TITLE
Word Online: OBJ characters get inserted in a document having fields

### ISSUE THREAD

**Issue by abhijeetnarvekar** [OfficeDev/office-js#268]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am creating a word addin which requires to get current selection

Unexpected Behavior:
In Word Online if I upload the document containing fields and select data between fields and query getSelection API. OBJ characters get inserted in document.

Expected Behavior:
document.getSelection() should not corrupt document.

Attached sample document and video recording of issue:
https://drive.google.com/drive/folders/1McawZdvswlO5iB3_8VSyymBY5cduMc6g?usp=sharing

Steps to reproduce:
1. Open Word Online
2. Upload document containing fields(Download from above URL)
3. Run the below code
4. Refresh document
5. Observe fields property is lost and OBJ character get inserted.

```
Word.run(function (context) {
    var textSample = 'This is an example of the insert text method.';
    var range = context.document.getSelection();
    range.insertText(textSample, Word.InsertLocation.end);
    return context.sync().then(function () {
        console.log('Inserted the text at the end of the selection.');
    });  
}).catch(function (error) {
    console.log('Error: ' + JSON.stringify(error));
    if (error instanceof OfficeExtension.Error) {
        console.log('Debug info: ' + JSON.stringify(error.debugInfo));
    }
});
```

Thanks,
Abhijeet

**Comment by XuanZhouMSFT** [comment]
Thanks for reporting it. This is a known issue and we are investigating and fixing. Tracked internally with 2541524.

**Comment by silviulupu** [comment]
Hello,

Since last Friday ( 7th of May ) we are facing exactly the same issue with Word document on Word Online ( no change in the code on our side ). 
 
For some controls ( but not for all ) we get OBJ instead of the text expected after refreshing the document. 
Do you have any idea ? 

Thanks,
Silviu
