### ISSUE TITLE
Contextual add in fails to initialize on OWA in appointment context

### ISSUE THREAD

**Issue by maartendebal** [OfficeDev/office-js#2681]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Contextual add in doesn't initialize on OWA in appointment context.
The link is highlighted but the window doesn't show up.

## Your Environment
* Platform: OWA on Chromium
* Host: Outlook
* Office version number: OWA
* Operating System: Windows 10
* Browser (if using Office on the web): Brave
 
## Expected behavior
Contextual add in shows up after clicking the highlighted link.

## Current behavior
Link is hightlighted but add in doesn't show up.
Following error is thrown: 
owa.ven.extframework.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'contextualTerms')
    at owa.24156.js:2:2044118
    at Array.forEach (<anonymous>)
    at owa.24156.js:2:2044095
    at owa.ven.extframework.js:2:313011
    at i (owa.ven.extframework.js:2:316562)
    at t.promiseMiddleware (owa.ven.extframework.js:2:318207)
    at t.dispatchWithMiddleware (owa.ven.extframework.js:2:316913)
    at Pe (owa.ven.extframework.js:2:113331)
    at n (owa.ven.extframework.js:2:113230)
    at t.default (owa.ven.extframework.js:2:315568)

## Steps to reproduce
- Clone repo: https://github.com/maartendebal/contextul-addin-owa-issue
- Create new certs (add in needs https)
- Run angular app with 'npm run start'
- Install manifest
- Send meeting request from a different account to the one with the manifest installed with the body "Click here".
- Open de meeting with the account which has the manifest installed.
- The words "Click here" should be highlighted.
- Click on "Click here"

## Additional details
The contextual add in does work on Outlook desktop in appointment context.

**Comment by grangeryy** [comment]
@maartendebal thank you for reporting the issue. I've added @exextoc to take a look. THX!

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding contextual add-in not working in OWA Calendar. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office:  162429

**Comment by maartendebal** [comment]
Hi all,

Any news on this. Do you think this will get fixed? 
If not, this poses a risk to our project so I would like to now. 

Thank you very much.
Kind regards,
