### ISSUE TITLE
getFileAsync returns 5001 with PDF file open in Word

### ISSUE THREAD

**Issue by F-Fontinha** [OfficeDev/office-js#2682]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

getFileAsync returns Error 5001 when trying to read the document after it was converted from pdf by word.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.62 (22061100)
* Operating System: MacOS 12.4
 
## Expected behavior

After calling getFileAsync with file type Compressed, the function should return a successful result.

## Current behavior

After calling getFileAsync with file type FileType.Compressed, the function returns an "Internal Error" with the code "5001".

## Steps to reproduce
- Open a Pdf file with Word and let it convert the file;
- Call the getFileAsync() function with type FileType.Compressed;
- The function will return an error.

**Comment by grangeryy** [comment]
Thank you @F-Fontinha for reporting the issue. We'll take a look. @wangyun-microsoft @grangeryy

**Comment by jipyua** [comment]
would you please provide use the pdf document you are using? does it contain specific content that word can't covnert?

**Comment by F-Fontinha** [comment]
Any file returns the same result for me. Here's an example with a simple pdf with just one line.
[example.pdf](https://github.com/OfficeDev/office-js/files/9044277/example.pdf)

**Comment by jipyua** [comment]
hi F-Fontinha, for this case it's because the file save hasn't really happened, and the file type is still pdf, thus you saw this error. if you save the file to local disk and try again, it will succeed.

**Comment by F-Fontinha** [comment]
Hi. And isn't there any way to actually read it as docx without saving it locally? As I understand, the getFileAsync function reads the file you are currently seeing (which I thought would be a docx file converted from pdf in this case). For example, when you create a new docx file you can use getFileAsync function without needing to save it locally first.

**Comment by jipyua** [comment]
so far this is a limitation for PDF converted files, it will have to be first saved and then will be truly docx files.
