### ISSUE TITLE
Admin Portal/GetSharedPropertiesAsync API Timeout

### ISSUE THREAD

**Issue by Kronenberg** [OfficeDev/office-js#2683]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Good day Office.JS team, at this stage I will describe the issue from admin perspective, but below you'll get the step by step guide.

So, as admin wanted to change **userB** principal name or email to **userTheKIng** under the admin portal, but looks like he is breaking the shared mailbox flow of this user because this **userB** shared his mailbox to some other users, but all other users still see the previous name "**userB**" under their accounts.

If we will try to use _GetSharedPropertiesAsync_ method under shared folder/mailbox of user **userTheKIng** we will get the previous email and name.

Maybe this is the timeout, or even expected behavior, we want to know, how much time it should take, or admin should re-add **userB** using his new credential's. We need to know.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: any platform web and all native versions
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: I think it's also not related because we found it in all different platform's.
* Operating System: Mac/Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
1. after I am changing the **userB** to **userTheKing** as an admin I am expecting get updated email which is **userTheKing** and user name via outlook web/mac/win and in this case via GetSharedPropertiesAsync API.

**Expected output:**
```
“value”: {
        “delegatePermissions”:63,
        “owner”: “userTheKing@onmicrosoft.com”,
        “targetRestUrl”: “https://outlook.office.com/api”,
        “targetMailbox”: “userTheKing@onmicrosoft.com”
    },
```

_Question_: After I am changing the user name or email as admin  how much time it takes to actually change this user mailbox, because even after the change if I want to add/share mailbox via _outlook_ or _GetSharedPropertiesAsync AP_I of the **userTheKIng** I can still see the previous one **userB**. Maybe this whole flow that I am doing is not possible and not supported by Microsoft, but still it's good to have an answer because this flow very important for our product :)

## Steps to reproduce
Step by step example how to reproduce this issue:
1. as an admin I will go to the admin portal and create two users under my **organization userA_@onmicrosoft.com** and **userB_@onmicrosoft.com**
2. then I will share **userB** mailbox to **userA**, so **userA** has the whole mailbox of the **userB**
3. under userA I will run my add-in and call **GetSharedPropertiesAsync** API and it return me the value as I expected.
Here is the output:
```
“value”: {
        “delegatePermissions”:63,
        “owner”: “userB_@onmicrosoft.com”,
        “targetRestUrl”: “https://outlook.office.com/api”,
        “targetMailbox”: “userB_@onmicrosoft.com”
    },
```
4. as an admin I want to change the **`userB`** principal name to **userTheKing** and its case I usually see that email also will be changed under the admin portal.
5. under **userA** I will run my add-in and call **GetSharedPropertiesAsync** under **userB** folder and I didn't get the updated name and mailbox of this user, but the mailbox of **userB** was changed to **userTheKing** by the admin.
Here is the output and it's the same:
```
“value”: {
        “delegatePermissions”:63,
        “owner”: “userB_@onmicrosoft.com”,
        “targetRestUrl”: “https://outlook.office.com/api”,
        “targetMailbox”: “userB_@onmicrosoft.com”
    },
```

## Useful logs
All details of this issue are very private but if want some extra details and I will provide anything you need.

**Comment by grangeryy** [comment]
Thank you @Kronenberg for reporting the issue. I've added @exextoc to take an investigation.

**Comment by exextoc** [comment]
Can you please share the steps, how did you share the user B mailbox to User A? Is it a shared mailbox account?

**Comment by Kronenberg** [comment]
Good day @exextoc here is the additional steps: 
1. Admin goes to https://portal.office.com/AdminPortal/Home?#/SharedMailbox
2. Admin add members to this mailbox(**userB**) under the same link
3. Admin goes to Azure Portal https://portal.azure.com/#view/Microsoft_AAD_IAM/UserDetailsMenuBlade/~/Profile/userId/very_nice_user_id and under this page he has ability to change principal name of this user **userB** or email and admin changing the user principal name from **userB** to **userTheKing**
4. Admin can see that this user was updated in Azure Portal And Outlook Office Portal as expected and **userB** became **userTheKing**
5. Then client want to use GetSharedPropertiesAsync API and still getting the previous username and even if admin want's to add userTheKing as a shared mailbox via Outlook Native itself he still see the previous user.

**Comment by exextoc** [comment]
Thank you for reporting the issue. It takes minimum 24 hours to get the updated username post the changes are made.
