### ISSUE TITLE
context.workbook.close(Excel.CloseBehavior.skipSave); not working properly

### ISSUE THREAD

**Issue by m14d3n** [OfficeDev/office-js#2684]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Office 365
* Operating System: Windows
* Browser (if using Office on the web): Edge, Chrome
 
## Expected behavior

Workbook should be closed without saving data and without prompting user.

## Current behavior

Dialog box shows stating: "You can now close this browser tab Give feedback". 
![image](https://user-images.githubusercontent.com/1979113/177049800-c57e88c7-98dd-4edb-a9b3-450727066ab8.png)
If you try to close tab or refresh another alert is shown stating "Leave site? Changes you made may not be saved."
![image](https://user-images.githubusercontent.com/1979113/177050008-b1231010-dedc-44c9-bcdb-3f3043f199fc.png)
End users are scared by the alert.

## Steps to reproduce

1.  In excel addin execute 
    Excel.run(async (context) => {
      await context.workbook.save(Excel.SaveBehavior.save);
      await context.workbook.close(Excel.CloseBehavior.skipSave);
    });

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by grangeryy** [comment]
Thank you @m14d3n for reporting the issue. I've added @yaweizhu-henson to see if he can help to resolve it. THX!

**Comment by JinghuiMS** [comment]
@m14d3n 
I can't repro this issue on my side, if you close the workbook on the UI (click x on the tab), will this "Leave site" dialog also appear?
It's definitely not right to have this error, if you can provide a repro video, that will be helpful for us to better understand your scenario. Thanks!
