### ISSUE TITLE
Word on Windows/Mac adding custom document property as string, read back as Date

### ISSUE THREAD

**Issue by neville-jones** [OfficeDev/office-js#2685]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform: PC desktop or Mac
* Host: Word
* Office version number: Windows: 2204 (Build 15128.20280 CTR); Mac: 16.62 (22061100)
* Operating System: Windows 10 or macOS Big Sur 11.6
 
## Expected behavior
When adding a custom document property where you specify a name and a value, if the value is a javascript string then when reading the custom document property back would expect it to always be a string.

## Current behavior

For Word on Windows or MacOS, when writing a string value of a certain syntax (e.g. a date represented as a string using ISO 8601) it comes back as a javascript date instance. Does not occur with Word on the web; value returned then is a javascript string as expected.

## Steps to reproduce

See script lab supplied example below

## Link to live example(s)

1. Script lab snippet - https://gist.github.com/neville-jones/3d07468360c378f54a6d0428fd2e4420

# Provide additional details

1. click button "Add two custom doc props with string values" - console will report properties created and their values
2. click button "Get 'Test 1 Property' and display value and type" - console will report value read was of 'MS Office Date' type and provide the .toString() output of the javascript date value
3. click button "Get 'Test 2 Property' and display value and type" - console will report value read was of 'MS Office String' type and provide its value; the only difference with the original string inputs was that 'Test Property 2' value was prefixed with value 'a'.

Similar behaviour observed in Excel but not exactly the same; will raise another issue for that.

## Context

We want an ISO 8601 date stored as a string and returned as a string as this value is used in a hash calculation; storing and returning it as a date can lead to hash validation errors because the returned date value can differ slightly from what was originally written (by parts of a millisecond, but this is enough to break the hash calculation).

**Comment by GavinGu07** [comment]
Hi @neville-jones, Thanks for submitting this issue! This is by design that converting a string in ISO8601 format to a date type, both in Word and Excel. If you want to store as a string, you can convert it in your JavaScript code.

**Comment by neville-jones** [comment]
Hi @GavinGu07 - we do want to store the value as a string, hence why we pass down a string representation of the datetime, but, as you have confirmed, Word is actually converting it to a date type when storing it, which is "by design". Part of the problem with trying to work around this is that when we read the date value back, it appears to be time shifted by a second so this is very problematic when using the input and stored values as part of a hash comparison.

For example, on our workstation:
```
input value = Custom Document Property added. Name = 'Test 1 Property', Value = '2022-01-01T10:00:00Z' (javascript string)
read value = MS Office Date: Sat Jan 01 2022 20:59:59 GMT+1100 (Australian Eastern Daylight Time)
```

We want to continue using the ISO8601 representation of the value because we have an equivalent COM add-in which has been using this representation when storing the value (and they explicitly store it as a string custom document property type, not a date).

**Comment by GavinGu07** [comment]
I understand your concern. However, this conversion was asked by many customers before, so we designed it like this. I also noticed your reply in #2686, and I'd recommend going to [Microsoft 365 Developer Platform Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) and see if this feature has already been requested or request a new feature. 

Another workaround is adding some characters into the ISO string (like what you did in Test 2 Property) to prevent the conversion and truncate the returned string to get the time you want.

**Comment by neville-jones** [comment]
Hi @GavinGu07, can you at least explain why the time shift back one second occurs? In my script lab sample we write down a string value of 2022-01-01T10:00:00Z but when we read it back it has date value of Sat Jan 01 2022 20:59:59 GMT+1100

**Comment by GavinGu07** [comment]
Hi @neville-jones. After investigation, we think it could be a bug. We have created an internal work item 6248145 on it. We will keep track of this issue and let you know if there are any updates.

**Comment by jipyua** [comment]
@neville-jones the time shift by one-second issue has been fixed, the fix will be rolled out together with M365 office update, please feel free to have a try when it's available.
