### ISSUE TITLE
Excel on Windows/Mac adding custom document property as string, stored as date, read back as office-js Date but is a javascript string

### ISSUE THREAD

**Issue by neville-jones** [OfficeDev/office-js#2686]
## Your Environment

* Platform: PC desktop or Mac
* Host: Excel
* Office version number: Windows: 2204 (Build 15128.20280 CTR); Mac: 16.62 (22061100)
* Operating System: Windows 10 or macOS Big Sur 11.6
 
## Expected behavior

When adding a custom document property where you specify a name and a value, if the value is a javascript string then when reading the custom document property back would expect it to always be a string.

## Current behavior

For Excel on Windows or MacOS, when writing a string value of a certain syntax (e.g. a date represented as a string using ISO 8601) it is stored as a custom document property of Date type, and when reading its value office-js reports it as of type Date, but javascript says it is of type string. The string value looks like an ISO 8601 value, but it has millisecond resolution now even though the original value that was written did not specify milliseconds.
Does not occur with Excel on the web; value returned then is a javascript string as expected.

## Steps to reproduce

See script lab supplied example below.

## Link to live example(s)

1. Script lab snippet - https://gist.github.com/neville-jones/c8c95673535ab4421b3d7b31c5088c4f

# Provide additional details

1. click button "Add two custom doc props with string values" - console will report properties created and their values
2. click button "Get 'Test 1 Property' and display value and type" - console will report value read was of 'MS Office Date' type but code checks to see if is a javascript string type and if so just output its value which is occurring in this sample; note presence of milliseconds in the output but was not part of input.
3. click button "Get 'Test 2 Property' and display value and type" - console will report value read was of 'MS Office String' type and provide its value; the only difference with the original string inputs was that 'Test Property 2' value was prefixed with value 'a'.

Similar, but slightly different issue in Word - #2685 

## Context

We want an ISO 8601 date stored as a string and returned as a string as this value is used in a hash calculation; storing and returning it as a date can lead to hash validation errors because the returned date value can differ slightly from what was originally written (by parts of a millisecond, but this is enough to break the hash calculation).

**Comment by yuc014** [comment]
Hi @neville-jones , I could repro it on win32 and online (16.0.15425.35901). They both shows Date type.
And after see the code, this is by design. When it receives a new custom document property, it will try to parse the value by ISO8601, to see whether this is a date property.
About you say "Does not occur with Excel on the web". Could you give me your web build number? Since win32 and web worked same by my side.
And I would like to give you a workaround.
```
for (var i = 0; i < properties.items.length; i++)
        console.log(
          "Property Name:" +
            properties.items[i].key +
            "; Type=" +
            typeof(properties.items[i].value.toString()) +
            "; Property Value=" +
            properties.items[i].value.toString()
        );
```
Will shows:
![image](https://user-images.githubusercontent.com/87364252/177243995-5c2cc135-6786-4b3d-95c2-52dbf0dd9dc7.png)

**Comment by neville-jones** [comment]
Hi @yuc014 , I have re-tested in Excel web and have found it works the same there so I must have been mistaken with the similar case for Word.

The workaround is not ideal for our situation, as we are using the value in a hash calculation and the string value we start with as the input is retrieved in the future and needs to be identical as its original input, otherwise the hash does not validate.

**Comment by yuc014** [comment]
Ok, then what about parse date to timestamp(milliseconds) and do hash.
I see timestamp is saved as string.
![image](https://user-images.githubusercontent.com/87364252/177257273-a10fb045-fb85-4a62-8ffa-321c5d505fc4.png)

**Comment by neville-jones** [comment]
We have an equivalent COM add-in which has been storing the timestamp as a ISO8601 string representation of the datetime (in syntax YYYY-MM-DDTHH:mm:ssZ) so our Office web add-in has to use the same representation for interoperability between the two add-ins so the hash calculation algorithm can remain the same.
The COM add-in has been in use since 2008 so many workbooks in use at customer sites with this custom property having this type and string representation.

At the moment, the workaround we can see is to use a regex to remove any millisecond information during the read and conversion back to string process. Again, we were surprised that passing a string to be added as the value for a custom property resulted in it being stored as a date type. Ideally the API method should have an optional parameter to indicate how the value should be stored to avoid this type of conversion automatically happening without developer control?

**Comment by yuc014** [comment]
It's good to hear that at least a workaround could work.
For this api, yes, it needs a parameter to make this function better.
I would recommend you go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) and see if this feature has already been requested or request a new feature.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
