### ISSUE TITLE
Please check the release version

### ISSUE THREAD

**Issue by Arvini92** [OfficeDev/office-js#2687]
Please check the current release version, it seems there is a lack of lines in office.js, and in other files like https://github.com/OfficeDev/office-js/blob/release/dist/office.debug.js it ends on the else statement. Diff between CDN office js and this one
![Screenshot (297)](https://user-images.githubusercontent.com/24441434/177200726-929f3155-6737-4a33-8ced-adef50f1eb71.png)
![Screenshot (298)](https://user-images.githubusercontent.com/24441434/177200760-304b6f92-ebd4-4183-b60b-34a27b70aede.png)
.

**Comment by JinghuiMS** [comment]
@Arvini92 Thanks very much for reporting this issue.
Assign it to @jayrathi who recently updated the https://github.com/OfficeDev/office-js/blob/release/dist/office.debug.js.

**Comment by JinghuiMS** [comment]
@Arvini92 Please double check whether it works for you, because
https://github.com/OfficeDev/office-js/blob/release/dist/office.debug.js. had been updated. Thanks!
