### ISSUE TITLE
use schedule assistant for zoom in OWA, Outlook calls our oneClickPrepareMeeting interface twice, 

### ISSUE THREAD

**Issue by echowwl** [OfficeDev/office-js#2688]
1. reproduce the issue:
![image](https://user-images.githubusercontent.com/105787768/177293721-7b6bf31a-9ade-48e3-a49d-c7ce285f7c12.png)
https://success.zoom.us/rec/share/y89AUFCFKhuh7akv4p8spuAgnpRJV3xpWXe9u-9MkrINhsRqetYJIqCmC_UcD5T0.Jx4iXwkYhtfzuGON
Passcode: e0b%m!z6
add online meetings to all meetings should be a new feature of Microsoft.

From the console log of dev-tool, we can see that after clicking the schedule assistant, Outlook calls our oneClickPrepareMeeting interface twice, and we will generate two meeting numbers, and we update the meeting body to the second latest meeting number, but After clicking save button, the meeting number of the location is updated to the first meeting number by Outlook.
![image](https://user-images.githubusercontent.com/105787768/177293847-cb05d4a8-80e9-4b94-a4ef-a03598c1f9fd.png)
why the schedule assistant calls our oneClickPrepareMeeting interface twice?

**Comment by exextoc** [comment]
Thanks for reporting this issue. We are able to repro the issue at our end. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office:  162614

**Comment by echowwl** [comment]
I can not reproduce the issue now, we can close it now
