### ISSUE TITLE
Two Taskpanes when using Auto-open Taskpane

### ISSUE THREAD

**Issue by dgrudenic** [OfficeDev/office-js#269]
## Expected Behavior
I would expect if you are using Auto-open in combination with some buttons in the ribbon that after document opens with taskapne on the side you'll not end up with two Taskpanes after you click some navigation button in the ribbon. 

## Current Behavior
I was playing with Auto-open Taskpane online example at https://github.com/OfficeDev/Office-Add-in-Commands-Samples/tree/master/AutoOpenTaskpane

and if you set auto-open on and save document next time you open document taskpane opens which looks like normal behaviour. 
Strange and unexpected behaviour is when you open the document and click ribbon button "Auto open sample" it will open additional Taskpane and you'll end up having two Taskpanes. 

## Steps to Reproduce, or Live Example
https://github.com/OfficeDev/Office-Add-in-Commands-Samples/tree/master/AutoOpenTaskpane

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Works same on Mac and PC (I was using Mac).
* Host [Excel, Word, PowerPoint, etc.]: Excel, Word, PowerPoint
* Office version number: 16.17 (180909)
* Operating System: macOS High Sierra (10.13.6)

**Comment by dgrudenic** [comment]
Any update on this one?

**Comment by danielgwilson** [comment]
Weird - I'll look into it, sorry for the delay @dgrudenic

**Comment by danielgwilson** [comment]
This is definitely a bug and a fix is being looked into

**Comment by ElizabethSamuel-MSFT** [comment]
@danielgwilson Any update on this? Or can you tag the current feature owner?

Thanks.

**Comment by lindalu-MSFT** [comment]
@dgrudenic in Zagreb! Greetings, can you verify this has been fixed in the latest Office build?

**Comment by ElizabethSamuel-MSFT** [comment]
@danielgwilson Can you provide a current status on this? Thx.

**Comment by lliu113** [comment]
@dgrudenic - thanks for reporting this issue to us, it looks like this has been fixed! I wasn't able to repro this anymore, after opening the document (and the taskpane auto-opening), clicking on the auto-open sample button refreshes the already opened pane instead of launching a new one. 

Will close this issue for now, please reactivate if you're still seeing the double taskpane on your end and we can investigate. Thanks!

**Comment by wh1t3cAt1k** [comment]
@lliu113 @lindalu-MSFT I am still reproing that on large Excel files in Excel Online.

![image](https://user-images.githubusercontent.com/5159662/185501900-2b7fde99-1b3b-4095-884a-a5525a02a43a.png)

**Comment by ElizabethSamuel-MSFT** [comment]
@wh1t3cAt1k Thanks for the update. However, this issue is pretty old so can you open a new issue so we can start a fresh investigation?

Thanks.
