### ISSUE TITLE
Syntaxerror in npm package with version 1.1.76 

### ISSUE THREAD

**Issue by rwolfdev** [OfficeDev/office-js#2690]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
I can not use the npm package of office-js to build my word-add-in. I defined the package in my package.json as follows:
"@microsoft/office-js": "^1.1.76",

But whenever i try to start my web app i get an error in the console which informs me about an unexcected end of input inside the office.js file. 

## Your Environment

* Operating System: Windows
* Browser (if using Office on the web): Edge
 
## Expected behavior

Adding office-js with script tag without getting an error. 

## Current behavior

I tried to set the source of office-js on my page layout with  
```
    <script src="~/office-js/office.js"></script>
```
but when I start my web application I can see in the console the following error:
```
Uncaught SyntaxError: Unexpected end of input (at office.js:76:13488)
```

## Steps to reproduce

1. download npm package with version 1.1.76
2. copy dist path to root path of your web application
3. add script tag to your html to add office-js to your web app

*There is a test project to reproduce this error: https://github.com/rwolfdev/office-js-test*

## Useful logs
- [X] Screenshots 
![image](https://user-images.githubusercontent.com/18228345/177539427-5f100dce-b23d-4d66-bd82-9bda82fae94e.png)

**Comment by wandyezj** [comment]
Add-Ins should **NOT** typically reference the office-js NPM package.

Per [office-js NPM package readme](https://www.npmjs.com/package/@microsoft/office-js)

> This NPM package is provided for the following scenarios:
> 1. Development of an Add-in behind a firewall, when accessing the Office.js CDN is not possible.
> 2. Offline access to the Office.js APIs to facilitate offline debugging.


Instead, you should reference office-js from the CDN and use the [@types/office-js](https://www.npmjs.com/package/@types/office-js) package for IntelliSense via `npm install --save-dev @types/office-js`

For more information see [Accessing the Office JavaScript API library](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/understanding-the-javascript-api-for-office)

**Comment by wandyezj** [comment]
@AlexJerabek we should consider adding a big warning at the top of the [@microsoft/office-js](https://www.npmjs.com/package/@microsoft/office-js) README.md that puts the target scenarios first and a link to the docs on how to use the CDN.

This is a common mistake I've seen a few developers make.

**Comment by rwolfdev** [comment]
I have understand the usage scenarios of the npm package. And my solution must work behind a firewall where there is no access to the CDN. For this reason I have tried to use it.

**Comment by JinghuiMS** [comment]
Thanks for reaching us. To better assist you, we suggest you go to Microsoft Tech Community New Ideas forum for the Microsoft 365 Developer Platform ([https://docs.microsoft.com/answers/products/m365](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)) and see if your feature has already been requested or request a new feature.

**Comment by wandyezj** [comment]
Hello @rwolfdev,

Did you follow the instructions in the [NPM Readme](
https://www.npmjs.com/package/@microsoft/office-js) in the section titled __Use the NPM package__?

It would be helpful to see the instructions implemented in the:
> test project to reproduce this error: https://github.com/rwolfdev/office-js-test
