### ISSUE TITLE
Requirement check for Powerpoint API 1.4 fails

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js#2691]
Hi i can't seem to get the requirement check working for Powerpoint Api 1.4 on web

https://gist.github.com/theboyknowsclass/7f53b99b961674cf9e60787c60058a08

# Provide required information needed to triage your issue

## Your Environment
* Operating System: Windows 10
* Browser (if using Office on the web): Edge
 
## Expected behavior
expect the Office.context.requirements.isSetSupported("PowerPointApi", "1.4") to return true (since this was apparently made available in May 2022)

## Current behavior
returns false...

## Steps to reproduce
see the gist

**Comment by JinghuiMS** [comment]
@theboyknowsclass
For powerpoint common API, the latest version should be 1.1. 
For powerpoint JS API, the latest version should be 1.4.
More detailed info you can refer to this document: 
https://docs.microsoft.com/en-us/javascript/api/requirement-sets/common/office-add-in-requirement-sets?view=common-js-preview

**Comment by theboyknowsclass** [comment]
Yes, I understand that, but the code here https://docs.microsoft.com/en-us/javascript/api/requirement-sets/powerpoint/powerpoint-api-requirement-sets?view=common-js-preview#checking-for-requirement-set-support-at-runtime seems to return the wrong value in scriptlab

**Comment by JinghuiMS** [comment]
Thanks for reporting this issue. It has been put on our backlog<Bug#6224524> for internal track.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
