### ISSUE TITLE
Footnotes on Microsoft Word (Desktop) NotImplemented Exception

### ISSUE THREAD

**Issue by gofish543** [OfficeDev/office-js#2692]
How can one access, insert, update, and otherwise manipulate footnotes in a desktop environment? None of the API calls which work on web are working locally. 

This really puts a significant damper on the development of add-ins if I cannot use the same functionality across platforms. Is there any intention to add this in the future?

**Comment by sureshjoshi** [comment]
There is some information about that here: https://github.com/OfficeDev/office-js/issues/2217#issuecomment-1174660505

Right now, footnotes/endnotes are WordOnline 1.1 (released relatively recently), with desktop support coming at some point.
