### ISSUE TITLE
Does the current version of office.js allow the insertion of images (e.g. logos) in headers and footers of Word documents?

### ISSUE THREAD

**Issue by mornir** [OfficeDev/office-js#2694]
This question has been asked about headers in Excel worksheet: https://stackoverflow.com/questions/68696821/adding-image-to-worksheet-header-footer-office-js-excel
The answer was that this feature was planned.

Also asked about Word, but without an answer: https://stackoverflow.com/questions/66805165/how-can-i-insert-picture-in-footer-section-with-javascript-office-js

Hence my question 😊

**Comment by JinghuiMS** [comment]
@mornir Thanks for reaching us.
I want to confirm one thing, you said footer not footnote. 
For footer, I would recommend you go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) and see if this feature has already been requested or request a new feature.

**Comment by mornir** [comment]
Thanks for the quick answer. Yes, in the **footer**. 

I didn't find this feature in the submitted ideas. I'm going to submit a new one.

**Comment by mornir** [comment]
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/office-js-allow-insertion-of-images-in-headers-and-footers-for/idi-p/3570889#M1093

**Comment by JinghuiMS** [comment]
Thanks for submitting the new feature request!

**Comment by hengchengfei** [comment]
use insertFileFromBase64 @mornir 

```ts
  await Word.run(async (context) => {
    const sections = context.document.sections;
    sections.load("items");

    await context.sync();
    sections.items[sections.items.length - 1].getFooter("FirstPage").insertFileFromBase64(desc, "End");

    await context.sync();
  }).catch((e) => {
    console.log(e);
  });
```
