### ISSUE TITLE
Using prependAsync changes the formatting of the text to Calibri 11 (macOS "new" Outlook)

### ISSUE THREAD

**Issue by shff** [OfficeDev/office-js#2696]
Using prependAsync in HTML mode changes the formatting of the text to Calibri 11.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.59
* Operating System: macOS 14 and 15
* Browser (if using Office on the web): -

## Expected behavior
The font should not change.

## Current behavior
The font changes to Calibri 11, even though the default is something else.

## Steps to reproduce
1. Change the Outlook for macOS default Compose Font to something other than Calibri 11pt.
2. Create a new message. The font of the message will be the one chosen above.
3. Run the shared snippet.
4. The font of the me changes to Calibri 11pt

## Link to live example(s)
ScriptLab Script: https://gist.github.com/shff/68dd8db3a4d14ca5e24d0022fafe92aa

## Context
I'm trying to add text using the API.

I'm using it in the simplest possible way to add HTML (I'm adding a text string here as an example but I do use it to add HTML in a real case scenario).

```js
Office.context.mailbox.item.body.prependAsync("hello", { coercionType: Office.CoercionType.Html });
```

## Useful logs
- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

### Before Clicking "Run"

<img width="844" alt="Screenshot 2022-07-07 at 16 55 01" src="https://user-images.githubusercontent.com/25377830/177805454-1fe17925-6f47-4efe-bb0e-3cd72c69ffc7.png">

### After Clicking "Run"

<img width="847" alt="Screenshot 2022-07-07 at 16 55 18" src="https://user-images.githubusercontent.com/25377830/177805468-2e6483fb-3bb0-4007-9711-1c3c23538b03.png">

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: 6239410

**Comment by bchenhs** [comment]
@exextoc Hi, we have a large number of users reporting the same issue. Can we escalate to address this issue? This font change issue also accompany performance degradation, rendering the add-on practically unusable. Thank you.

**Comment by exextoc** [comment]
Thank you for raising the issue. We are working on this right now. Unfortunately, we don't have any timelines to share with you at the moment.

**Comment by Sophie1142** [comment]
Hello, this is also an issue for us (though it changes font size from 12 to 10). Any updates?
