### ISSUE TITLE
[Word Online] Content with image is inserted outside content control

### ISSUE THREAD

**Issue by tranhuyentran23** [OfficeDev/office-js#2698]
# Provide required information needed to triage your issue

## Your Environment

* Platform: Office Online
* Host: Word
* Office version number: 16.0.14413.41001
* Operating System: Windows 10
* Browser: Chrome
 
## Expected behavior
Content with an image will be inserted inside the content control

## Current behavior
Content with an image is inserted outside content control

## Steps to reproduce
1. Create a new document
2. Run the attached Script lab
3. Create 2 content controls
4. Modify the content controls
5. Observe the content is inserted outside the content control
(maybe this issue will not happen for the time, please close the opening document and repeat steps 1 - 5 again)

## Link to live example(s)
![chrome_QGu96297zd](https://user-images.githubusercontent.com/89008454/177918174-e0673ce0-5ac0-4e96-8dc2-a665df303f18.gif)

Script Lab: 
https://gist.github.com/tranhuyentran23/8aca6982e23051f83a4cb0d653bb7b2c

**Comment by JinghuiMS** [comment]
Thanks for reporting this issue. It has been put on our backlog<Bug#6225785> for internal track. We unfortunately have no timelines to share at this point.
