### ISSUE TITLE
Office for Mac (WKWebView) file download support

### ISSUE THREAD

**Issue by hbnrmx** [OfficeDev/office-js#2700]
# Provide required information needed to triage your issue

We have an office addin with a sidepane that can download files:
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>my sidepane</title>
  </head>

  <body>
    <script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
    <script>
      const anchor = document.createElement('a')

      anchor.href = 'https://file-examples.com/storage/fe0a8978a262cb51f92368e/2017/02/file-sample_100kB.doc'
      anchor.download = 'myFileName.doc'
      anchor.style.display = 'none'

      document.body.appendChild(anchor)
      anchor.click()
      document.body.removeChild(anchor)
    </script>
  </body>
</html>
```

I have whitelisted the domain so that it opens within the same window in the `manifest.xml`:
```xml
  <AppDomains>
    ...
    <AppDomain>https://file-examples.com</AppDomain>
  </AppDomains>
```

The download works fine when opening the addin in any browser or in Office for Windows,
but seems to fail in Office for macOS (WKWebView):
<img src="https://user-images.githubusercontent.com/46070579/178313818-590a5d9b-d009-4064-9219-76e0e38dd659.png" width=300 />

I have tried to use different `Content-Disposition` and `Content-Type` headers without any success.

Do you have hints or pointers for how to resolve this issue?
Thank you!

## Your Environment

* Platform: Mac (javascript addin)
* Host: Excel, Word, PowerPoint
* Office version number: Microsoft® Excel for Mac Version 16.61.1 (22052000)
* Operating System: macOS
* Browser (if using Office on the web): macOS WKWebView
 
## Expected behavior

File is downloaded.

## Current behavior

Files raw content is displayed.

## Steps to reproduce

1. Create an addin with a sidepane as shown above
2. Click Ribbon button to open the sidepane

## Context

Cannot download files, rendering our addin unusable on macOS.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by oFlo193o** [comment]
Hi there! Any news ?

**Comment by yaweizhu-henson** [comment]
Sorry for late response.
I will let engineer have a look at it ASAP!

**Comment by JinghuiMS** [comment]
It's not a specific Excel API issue, involve add-ins platform into this thread to better handle it!

**Comment by hbnrmx** [comment]
Hi @yaweizhu-henson,
Hi @JinghuiMS,

as this is probably a macOS / Webkit / `WKWebview` host configuration issue,
Could you kindly point me to the correct repo?

Thank you!

**Comment by oFlo193o** [comment]
Hi there. Any news?

**Comment by ElizabethSamuel-MSFT** [comment]
@jargil Can you take a look? Thanks.

**Comment by jargil** [comment]
This is not supported in Mac by directly navigating to the file. Please use the OpenBrowserWindowApi: https://docs.microsoft.com/en-us/javascript/api/requirement-sets/common/open-browser-window-api-requirement-sets?view=excel-js-preview
