### ISSUE TITLE
RichApi.Error when loading inline images

### ISSUE THREAD

**Issue by rogozind** [OfficeDev/office-js#2702]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We use the code below to fetch inline images from a word document. This code used to work a few months ago. Recently (not sure exactly when) it started to throw this error under specific scenario:
```word-web-16.00.js:25 Uncaught (in promise) RichApi.Error
    at new n (word-web-16.00.js:25:309170)
    at i.processRequestExecutorResponseMessage (word-web-16.00.js:25:373336)
    at word-web-16.00.js:25:371399
    at async taskpane.js:2:830146
```
The error happens if the in mage is an external URL AND the image is off screen and not been loaded yet. If I scroll down to the image forcing it to load the code below works.

The code:
```
const LOAD_OPTIONS = Object.freeze(['imageFormat'])

loadInlineImagesData = () => new Promise((resolve, reject) => {
    Word.run(async(context) => {
      try {
        const images = context.document.body.inlinePictures
        images.load(LOAD_OPTIONS)
        await context.sync()
        
        const imageData = images.items.map((image) => {
          return {
            format: image?.imageFormat,
            base64: image?.getBase64ImageSrc()
          }
        })
        await context.sync()
        
        resolve(imageData)
      } catch (error) {
        console.log('Error: ', error)
        reject(error)
      }
    })
  })
```
The crash happens on the second .sync() call.

We tried various ways: iterating picture by picture ad doing individual sync, no luck. It always crashes when it tries to load base64 data for the item still not loaded.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on Web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16
* Operating System: MacOS
* Browser (if using Office on the web): Chrome
 
## Expected behavior

It needs to be able to return the image data for all images. It used to do it before.

## Current behavior

Crash on loading data from unloaded images.

## Steps to reproduce

1. Take Welcome To Word document.
2. Try to load the pictures w/o scrolling it to the end.
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by xiruatms** [comment]
@rogozind , thanks for reporting this.

If possible, will you please share a testing document with us? That'll be much helpful for us to verify your case.

**Comment by rogozind** [comment]
Attached.

[Welcome to Word.docx](https://github.com/OfficeDev/office-js/files/9111727/Welcome.to.Word.docx)

**Comment by xiruatms** [comment]
@rogozind , thanks for providing the sample document.

I've taken a try but didn't encounter the issue you reported. Will you please help to isolate the suspected codes in a simple scriptlab code snippet which could repro this issue? 

Following are the codes I used for testing.  Sorry about the formatting, it seems something wrong with the github editor.
async function getImage() {
  await Word.run(async (context) => {
    try {
      const images = context.document.body.inlinePictures;
      images.load();
      await context.sync();
      for (let index = 0; index < images.items.length; index++) {
        let base64 = images.items[index].getBase64ImageSrc();
        await context.sync();
        console.log(base64);
      }
    } catch (error) {
      console.log('Error: ', error)
    }
  });
}

**Comment by rogozind** [comment]
ok, I'll try to put something together but it will take a bit.

**Comment by rogozind** [comment]
Try this example: https://github.com/MariSytnyk/office-document-loading-issue

**Comment by JinghuiMS** [comment]
Thanks for reporting this issue. It has been put on our backlog<Bug#6320493> for internal track. We will keep track of this issue and let you know if there are any updates.
