### ISSUE TITLE
Simple space regex won't work when regional setting is "Germany"

### ISSUE THREAD

**Issue by abhinovpankaj** [OfficeDev/office-js#2703]
I am using word API to create  a simple Word Add-in for find and replace function.

Regional settings: US
The below code like charm, and it searches just fine.
```
`async function wildcardSearch() {
  await Word.run(async (context) => {
    // Check out how wildcard expression are built, also use the second parameter of the search method to include search modes
    // (i.e. use wildcards).
    let results = context.document.body.search(" {2,}", { matchWildcards: true,  });
    results.load("length");

    await context.sync();}`
```

Once the regional settings changes to attached image, simple search starts to throw exception.
![image](https://user-images.githubusercontent.com/15319976/178551878-e652ff60-3147-458a-9f64-bf78ce56eb04.png)

Exception :

[ERROR]: Error:
{
    "stack": "RichApi.Error: GeneralException\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:244488)\n    at i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:308654)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:306717",
    "message": "GeneralException",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "GeneralException",
        "errorLocation": "",
        "statement": "_Search2.load([\"length\"]);",
        "surroundingStatements": [
            "var root = context.root;",
            "var body = root.body;",
            "// Instantiate {body}",
            "var _Search2 = body._Search2(...);",
            "// Instantiate {_Search2}",
            "// >>>>>",
            "_Search2.load([\"length\"]);",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}

**Comment by AlexJerabek** [comment]
Hi @abhinovpankaj,

Thanks for reporting this issue. This appears to be a product bug, so I'll transfer this issue to the office-js repo. There, members of the product team can investigate your findings.

**Comment by AlexJerabek** [comment]
@abhinovpankaj, can you please also provide the following system information:

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______

**Comment by abhinovpankaj** [comment]
> Platform [PC desktop]
Office version number: 
![image](https://user-images.githubusercontent.com/15319976/178561064-88a46df5-8a2e-478e-a55f-d89060a45afd.png)

Operating System: Win 11
Browser (if using Office on the web): NA

I have tried this on Win 10 as well. Not sure about the office version there( Its user's machine)

**Comment by abhinovpankaj** [comment]
Any suggestions? Or any different regex which will work.

**Comment by abhinovpankaj** [comment]
What should I do?

**Comment by xuruiyao-msft** [comment]
We are investigating this issue. Will update status soon.

**Comment by xuruiyao-msft** [comment]
@abhinovpankaj  We've created a work item 6255730 on it and tracked the progress. Once there's any update we'll sync with you.

**Comment by abhinovpankaj** [comment]
Thanks for the update. Will keep an eye.

**Comment by abhinovpankaj** [comment]
Any progress on this issue?

**Comment by xuruiyao-msft** [comment]
@abhinovpankaj Hi, This scenario works fine on latest version. I can reproduce the issue before but now everything is ok. I cannot reproduce it.  Would you please upgrade your word version to latest and try it again?

**Comment by abhinovpankaj** [comment]
That's great news, I will give it a try and update.

**Comment by jipyua** [comment]
@abhinovpankaj this bug has been fixed and will be rolled out gradually, it should be available in next month's update, please update your M365 Office to the latest version and have a try. thanks.
