### ISSUE TITLE
External images set through `body.setAsync` are blocked in reply

### ISSUE THREAD

**Issue by milankonir** [OfficeDev/office-js#2705]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft Outlook for Microsoft 365 MSO (Version 2206 Build 16.0.15330.20144) 32-bit 
* Operating System: Microsoft Windows 10 Pro for Workstations 10.0.19044 Build 19044
* Browser (if using Office on the web): N/A
 
## Expected behavior

`<img>` tag pointing to external image that is added into email content through API should never be blocked from downloading.

## Current behavior

`<img>` tag to external image set through `Office.context.email.body.setAsync` is blocked (replaced by static white box asset) when replying to an email containing external image.

## Steps to reproduce

1. Got to Outlook options -> trust centre -> automatic downloads and make sure automatic image download is disabled (with no exceptions).
![image](https://user-images.githubusercontent.com/72383088/178677037-25dda640-21db-4d46-8c92-6cb9cf1a1883.png)
2. Send an external email to your inbox
3. Reply to that email
4. Insert img using attached script lab file
5. See the img being blocked / replaced by a white box

## Link to live example(s)

1. ScriptLab Gist: https://gist.github.com/milankonir/4e459bc64ed821892d16ae0d22e102b8
2. Repro video: https://share.getcloudapp.com/E0uyXqy8

# Provide additional details

## Context

Users that have the automatic image download disabled and don't download the images manually when replying to an existing email are not able to insert images to the email through our add-in.

Tis especially problematic when we insert images into the email during `ItemSend` as the user has no chance to intervene and an unprofessionally looking email will be sent (white box instead of an actual image).

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Hello @milankonir, are you able to reproduce this issue on any other platform, or does this only seem to persist on Win32?

**Comment by exextoc** [comment]
Are you able to set the body with the external image when the Automatic Download settings are configured differently?

**Comment by milankonir** [comment]
@exextoc It only affects Windows, Mac and OWA works fine.
I'm able to set external image when the automatic download is allowed (either completely or via exception - e.g. allow downloading images from trusted sites).

**Comment by exextoc** [comment]
I have followed the repro steps and am not able to repro this. The image appears on my end when running the script you provided. I will continue to look into this.

**Comment by exextoc** [comment]
@milankonir I was able to reproduce this issue. We will be reviewing the design of this functionality, but unfortunately don't have a timeline to share at the moment. In the meantime, these are some workarounds that you can consider using:

1. Download the images from the email thread which will stop the image insertion from being blocked.
2. Use the `item.addFileAttachmentAsync` API and then the `body.setAsync` API to include this image as an inline attachment.
3. Base64 encode the image binaries and use the `item.addFileAttachmentFromBase64Async` API and then the `body.setAsync` API to include this image as an inline attachment from Base64.

**Comment by milankonir** [comment]
@exextoc Thanks for looking into this and for the suggested workarounds.

The workarounds are unfortunately not suitable for our use case us as the image link points to a dynamic resource which is intended to be loaded on recipients end.
