### ISSUE TITLE
Redirect URL mismatch error when using SSO with Office.js in Outlook add-in, if Outlook URL is custom/vanity URL.

### ISSUE THREAD

**Issue by Aaditya-Rane** [OfficeDev/office-js#2710]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ---
* Operating System: ---
* Browser (if using Office on the web): Chrome
 
## Expected behavior
When URL for Outlook is **a custom/vanity URL**, then office-js should be able to fetch access tokens using SSO in the outlook add-in.

## Current behavior
Redirect URL mismatch error when using SSO with Office.js in Outlook add-in, if Outlook URL is custom/vanity URL.

## Steps to reproduce
1. Change the outlook URL to some **custom/vanity URL**.
2. Follow the steps provided in [Enable single sign-on (SSO) in an Office Add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)
3. Use code mentioned in [Add client-side code](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins#add-client-side-code) of the same document to fetch access token using SSO.

# Observations
1. After following above steps, when opened add-in in outlook, we receive following error, with redirect uri as "https://<outlook_custom_url>/owa/extSSO.aspx"

![219981-image](https://user-images.githubusercontent.com/30556436/179179152-b0b0e6cd-bdf2-4a03-8fe2-23b85f0b53cb.png)

**Please provide input on this issue.**

**Comment by exextoc** [comment]
For vanity domains, the tenant will need to add an additional reply URL. The tenant administrator can resolve it manually.

 

More on it can be found here: [https://stackoverflow.com/questions/38372040/change-azure-active-directory-reply-url-via-powershell-command](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2f%2fstackoverflow.com%2fquestions%2f38372040%2fchange-azure-active-directory-reply-url-via-powershell-command&data=04%7c01%7cSachin.Gaikwad%40microsoft.com%7c8e153a107cfe48c3789a08da01a68c68%7c72f988bf86f141af91ab2d7cd011db47%7c0%7c0%7c637824112138152230%7cUnknown%7cTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7c3000&sdata=EAvQzXLxmiS9BMGEFEWxPN8lcblIbOps%2BP4PWWOF4UU%3D&reserved=0)

**Comment by Aaditya-Rane** [comment]
Hi @exextoc 

The current issue is happening at the point "1. getAccessToken()" from the below flow [How it works at runtime](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph#how-it-works-at-runtime).

**We are receiving a redirect URI error for an application with clientId "bc59ab01-8403-45c6-8796-ac3ef710b3e3" which is Microsoft's application with the name "Outlook Online Add-in App"**. We only have the "Service Principal" of this application in our tenant. 

We don't have access to this application our tenant, so we can not modify 'replyUrls' either from the Azure admin center or Powershell.

**Comment by exextoc** [comment]
Could you try running the [script](https://stackoverflow.com/questions/38372040/change-azure-active-directory-reply-url-via-powershell-command) mentioned in Powershell (if you haven't already) and tell us what errors you are facing? That will help us understand how best to proceed.

**Comment by Aaditya-Rane** [comment]
Hi @exextoc,

As I have mentioned in a previous comment, "bc59ab01-8403-45c6-8796-ac3ef710b3e3" is Microsoft's application with the name "Outlook Online Add-in App". 

While executing the given PowerShell script with appId : "bc59ab01-8403-45c6-8796-ac3ef710b3e3", 
`Get-AzureADApplication -Filter "AppId eq '$($appId)'"`  returns nothing as it executes filter query on the list of applications with appId "bc59ab01-8403-45c6-8796-ac3ef710b3e3".
We don't have the Azure application with the given appId in our tenant, but we only have the Service principal (Enterprise application).

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding SSO use for vanity domains. This is a known issue that we are looking into. We unfortunately have no timelines to share at this point, but we will update this thread when we have a fix. Internal tracking id: Office: 165553

**Comment by exextoc** [comment]
Hi @Aaditya-Rane 
We investigated this issue and found that this needs a new feature implementation which is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
Github Label: “Type: product feature request”

**Comment by Aaditya-Rane** [comment]
We have raised outlook add-in feature requests in Tech community page\
[Support SSO with Office.js in Outlook add-in, if Outlook URL is custom/vanity URL](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/support-sso-with-office-js-in-outlook-add-in-if-outlook-url-is/idi-p/3742021)

As office.js SSO and vanity URL are not compatible with each other. I think this should be consider as bug.

**Comment by nikhil452** [comment]
Any update on the fix.

**Comment by exextoc** [comment]
Hey @nikhil452 ,

We are tracking this as a product request on our Tech Community page, and we go through them during our planning process. However, we have no timelines to share..

**Comment by exextoc** [comment]
@Aaditya-Rane @nikhil452 We have a limitation on Outlook Web extensibility for this API whereby it does not work with Vanity Domains. According to our design, it should work with O365/M365 domains. We presently do not have a solution for this limitation. We are working on an improved authentication model for Add-ins, which should resolve this issue for users. getAccessTokenAsync will not work, but we recommend implementing a fallback with a login screen/display dialog.[Use SSO to get the identity of the signed-in user - Office Add-ins | Microsoft Learn](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/use-sso-to-get-office-signed-in-user-token?source=recommendations&tabs=vs2019)
