### ISSUE TITLE
Outlook SSO Addin throws 13012 Error

### ISSUE THREAD

**Issue by avisheknand** [OfficeDev/office-js#2711]
We have updated our app to use   OfficeRuntime.auth.getAccessToken from OfficeRuntime.auth.getAccessTokenAsync . The new method OfficeRuntime.auth.getAccessToken works fine on the OWA however, when we use Outlook for Desktop is throwing 13012 error. 

## Your Environment

* Platform :  Outlook desktop
* Host: Outlook
* Office version number: Office 365 Version 2206 Build 1533.20246
* Operating System: Windows 11

## Expected behavior

Expected behavior is that it should work fine as we have also provided Admin consent to the app
## Current behavior

Currently when using the new method OfficeRuntime.auth.getAccessToken we are getting 13102 error on Outlook desktop. However, it works fine in OWA

Code: 

` if (options === undefined) options = { allowSignInPrompt: true, allowConsentPrompt: true, forMSGraphAccess: true };
    
 let ssoToken = await OfficeRuntime.auth.getAccessToken(options);`

**Comment by ztcddsb** [comment]
@avisheknand Can you provide the right version of your Outlook? The version listed above missed a digit. It is possible that you have an old build of Outlook that does not support this API.

OWA is a separate codebase and its logic is different from Mac/Win32.

"forMSGraphAccess" is just a performance shortcut and it is most likely the reason you get this error, can you confirm if the API works without it? The parameter is only needed if the add-in is published to AppSource

**Comment by avisheknand** [comment]
Thanks @ztcddsb ! Here is the screenshot of my Outlook version

![image](https://user-images.githubusercontent.com/80862413/179653095-e8916bea-32b5-4ff6-9113-db6838ec5d6d.png)


I have tried to use without "forMSGraphAccess" and the API works fine!  :) However, we are planning to publish this app to AppSource soon. 

I have also tried the Outlook SSO Addin Demo app and it also has similar issue : https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO

**Comment by ztcddsb** [comment]
Thanks for sharing the version.
Did you sideload the add-in by any chance?

**Comment by avisheknand** [comment]
@ztcddsb , yes the add-in was sideloaded

**Comment by ztcddsb** [comment]
@avisheknand 
I think that is the problem, you should not side-load when passing forMSGraphAccess, this will fail the validation.

This flag checks if the add-in was installed by an administrator and thereby administrator would have already consented to Graph scopes, or fail otherwise.

**Comment by avisheknand** [comment]
@ztcddsb, Thanks for the info. I have not tried by deploying the add-in from the admin center.

From this [article ](https://docs.microsoft.com/en-us/javascript/api/office-runtime/officeruntime.authoptions?view=common-js-preview) i thought that if you are using forMSGraphAccess parameter, admin consent for graph is required... therefore i tired to grant Admin consent from the Azure -> Enterprise App and as well as using the admin consent url  https://login.microsoftonline.com/common/adminconsent?client_id={client-id}&state=12345

**Comment by ztcddsb** [comment]
@avisheknand This seems like a common issue that add-in developers encountered. 
We might need to rephrase the article as it causes confusion. I will talk with my team and create a task for it.
Thanks for bring it up.

**Comment by avisheknand** [comment]
@ztcddsb , Great Idea!  Thanks lots for your help.

**Comment by ztcddsb** [comment]
@avisheknand I have created a task for our technical writer, I will close the ticket for now if you don't have any further questions.
