### ISSUE TITLE
Content control with Table of content inside cannot be modified or cleared

### ISSUE THREAD

**Issue by tranhuyentran23** [OfficeDev/office-js#2712]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Your Environment

* Platform: Office Online
* Host: Word
* Office version number: 16.0.14413.41001
* Operating System: Windows 10
* Browser: Chrome
 
## Expected behavior
Content with Table of Content will be modified or cleared successfully

## Current behavior
Content with Table of Content cannot be modified or cleared

## Steps to reproduce

1. Create a new document
2. Run the attached Script lab
3. Click Create content control
4. Add a Table of Content to this content control 
5. Add some section with Heading then Update the Table of Content
6. Click Modify content control
7. Observe the content inside the content control cannot be modified and an error is thrown
<img width="434" alt="replace-content-with-TOC-not-allowed" src="https://user-images.githubusercontent.com/89008454/179219790-57a28096-e0c3-4af0-840a-388b5e2a0741.PNG">

## Link to live example(s)
![chrome_094oc7wfvs](https://user-images.githubusercontent.com/89008454/179191134-662c4fa9-d66a-4990-be42-d721caed7314.gif)

Script Lab: https://gist.github.com/tranhuyentran23/9a0932b7b8ed81d3ba2e5ee4971928df

**Comment by JinghuiMS** [comment]
Thanks for reporting this issue. It has been put on our backlog<Bug#6258921> for internal track. We unfortunately have no timelines to share at this point.
