### ISSUE TITLE
OneNote paragraph getHtml() API does not return color information.

### ISSUE THREAD

**Issue by rogozind** [OfficeDev/office-js#2713]
I am trying to get paragraph html in OneNote. I have a line with various fonts, sizes, bold/italic and foreground and background colors. The HTML I get back contains styles for everything except colors. So the color information is lost.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __Office on Web
* Host [Excel, Word, PowerPoint, etc.]: _OneNote_____
* Office version number: ___Office 365___
* Operating System: ___MacOS___
* Browser (if using Office on the web): __Chrome____
 
## Expected behavior

The styles for the span tag should return color and background info for the paragraph.

## Current behavior

Color info is not returned.

## Steps to reproduce

1. Create a line with colored text
2. Use getHTML() to get the HTML from the paragraph.
3. Review the HTML returned.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by LuyiH** [comment]
Hi @rogozind, could you help open this issue in [https://github.com/OneNoteDev/OneNoteApi](url), and MS engineer will help you solve this issue there

**Comment by rogozind** [comment]
Will do, thanks.
