### ISSUE TITLE
Powerpoint web: SetSelectedDataAsync is incorrectly converting points to pixels, but API documentation says points

### ISSUE THREAD

**Issue by lynneosmith** [OfficeDev/office-js#2714]
When using setSelectedDataAsync to insert content like images, graphs, etc, PowerPoint on the web is taking the top, left, width and height parameters and converting them to points... but they were specified as points already so now their value is incorrect. If you use the new Shape API to check the left, top, width and height values, you can see that their values are incorrect. This works correctly on desktop.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: ______
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
If I specified left, top, width and height when I insert an image with setSelectedDataAsync and then immediately load the left, top, width and height values for the shape, they should be the same as they were when I just inserted them.

## Current behavior
Currently, on PowerPoint web, if I specify
 setSelectedDataAsync(
    getImageAsBase64String(),
    {
      coercionType: Office.CoercionType.XmlSvg,
      imageLeft: 500,
      imageTop: 500,
      imageWidth: 400
    }
and then immediately check those values using the shape.left, shape.top, shape.width, shape.height values, they will change.
In the case above, instead of being 500, 500, 400 - they become 375, 375, 300

If I do the same thing on desktop Powerpoint, they are 500, 500, 400 as I expect when I get load and check them on the shape.
I can also tell from the insertion point on the web vs the desktop - you can see from where the image is placed on the slide that they are different and that the web is wrong.
The web version of Powerpoint appears to be assuming that I passed pixels to setSelectedDataAsync and then translates them to points.

Your documentation clearly says for both setSelectedDataAsync and on the Shape, they are all points.

https://docs.microsoft.com/en-us/javascript/api/office/office.setselecteddataoptions?view=powerpoint-js-1.4
Note this says:
imageHeight | This option is applicable for inserting images. Indicates the image height. If this option is provided without the imageWidth, the image will scale to match the value of the image height. If both image width and image height are provided, the image will be resized accordingly. If neither the image height or width is provided, the default image size and aspect ratio will be used. **This value is in points.**
imageLeft | This option is applicable for inserting images. Indicates the insert location in relation to the left side of the slide for PowerPoint, and its relation to the currently selected cell in Excel. This value is ignored for Word. **This value is in points.**
imageTop | This option is applicable for inserting images. Indicates the insert location in relation to the top of the slide for PowerPoint, and its relation to the currently selected cell in Excel. This value is ignored for Word. **This value is in points.**
imageWidth | This option is applicable for inserting images. Indicates the image width. If this option is provided without the imageHeight, the image will scale to match the value of the image width. If both image width and image height are provided, the image will be resized accordingly. If neither the image height or width is provided, the default image size and aspect ratio will be used. **This value is in points.**

Your documentation for the Shape class says:
https://docs.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.shape?view=powerpoint-js-1.4

height | **Specifies the height, in points, of the shape.** Throws an InvalidArgument exception when set with a negative value.
left | The distance, **in points**, from the left side of the shape to the left side of the slide.
top | The distance, **in points**, from the top edge of the shape to the top edge of the slide.
width | Specifies the width, **in points**, of the shape. Throws an InvalidArgument exception when set with a negative value.

## Steps to reproduce
I reproduced this problem using ScriptLab:
1. I modified your Insert SVG ScriptLab sample - Note: LEAVE IN THE getImageAsBase64String method. I did not modify that.

$("#insert").click(newImage);
$("#find").click(find);

function newImage() {
  Office.context.document.setSelectedDataAsync(
    getImageAsBase64String(),
    {
      coercionType: Office.CoercionType.XmlSvg,
      imageLeft: 500,
      imageTop: 500,
      imageWidth: 400
    },
    function(asyncResult) {
      if (asyncResult.status === Office.AsyncResultStatus.Failed) {
        console.error(asyncResult.error.message);
      }
    }
  );
}

async function find() {
  await PowerPoint.run(async (context) => {
    var shapes = context.presentation.slides.getItemAt(0).shapes;
    shapes.load("items");
    await context.sync();

    var cr = shapes.getCount();
    await context.sync();
    for (let i = 0; i < cr.value; i++) {

      const newShape = shapes.getItemAt(i);
      newShape.load("top");
      newShape.load("left");
      newShape.load("width");
      newShape.load("type");
      await context.sync();
      console.info(`index: ${i} type: ${newShape.type} top: ${newShape.top.toString()} left: ${newShape.left.toString()} width: ${newShape.width.toString()}`);
    }

    await context.sync();
  });
}

3. On the HTML tab, I added an extra button:

<section class="ms-font-m">
    <p>This sample shows how to insert an SVG image using an XML string as the source.</p>
</section>

<section class="samples ms-font-m">
    <h3>Try it out</h3>
    <button id="insert" class="ms-Button">
        <span class="ms-Button-label">Insert new SVG</span>
    </button>
	<button id="find" class="ms-Button">
	        <span class="ms-Button-label">Find</span>
	    </button>
</section>

5. When you click the Insert button, the SVG will be entered on the first slide. It is fine to use the title/subtitle initial first slide. 
6. When you click the Find button, you will see the values the image for top, left and width are specified in the console. They do NOT match the 500,500,400 values that were used in the insertion code in this sample. On the web, they will be 375, 375 and 300. On the desktop, if you run this sample, they will correctly display in the console as 500, 500, 400.

# Provide additional details
The above description should be thorough. Run it in both desktop and web and you will see the difference.

## Context
Our application inserts report content and then gives the user the ability to update the content. We need to be able to check the location that the user has positioned the shape and then reliably put it back in the same location. We are unable to do that if the web version of powerpoint changes the values given to setSelectedDataAsync. This makes the update portion of our product very unreliable on the web. If we try to convert the values and then you fix this bug, we will break our users in the field.  We will also likely run into some rounding issues trying to work around the incorrect conversion that powerpoint web is doing to the points values we specify to setSelectedDataAsync. It also conflicts with your documentation.

## Useful logs

- [ ] Screenshots
![pp_web_incorrectvalues](https://user-images.githubusercontent.com/57771416/179303658-7ed6e01c-1e8b-4544-8936-779362fad89f.JPG)
![pp_desktop_correctvalues](https://user-images.githubusercontent.com/57771416/179303661-40a44bca-17ce-468a-ac3b-1105becae5a5.JPG)

- [ ]Console logs
On desktop (CORRECT):

index: 2 type: Image top: 500 left: 500 width: 400

On web (WRONG):

index: 2 type: Image top: 375 left: 375width: 300

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by xuruiyao-msft** [comment]
@lynneosmith  Thanks for reporting the issue. I can reproduce it. The setSelectedDataAsync method behaves different on WAC platform from the desktop platform. We've create the work item 6268407 to track it. If there's any further update, we'll sync with you.

**Comment by lynneosmith** [comment]
I wanted to check back to see if there is any update on this work item since it's been three weeks since we've heard anything? We are really hoping for a fix soon as this issue will impact us being able to ship our product. Thanks.

**Comment by sashakar** [comment]
Hello @ahegongzhu  Could you please provide an update to this issue? There has been no update in almost 6 weeks. Thanks so much.

**Comment by ahegongzhu** [comment]
since

**Comment by jipyua** [comment]
hi @lynneosmith @sashakar sorry for the waiting, the fixing and deployment need some time. Now the deployment is almost done. If your PowerPoint Online version is equal to or greater than 16.0.15631.40512, then it will contain our fix. Feel free to have a try and let us know whether it works for you. Thanks.

**Comment by lynneosmith** [comment]
The fix works for us. Thank you very much for your assistance!
