### ISSUE TITLE
Office Dialog when closed, stops debugging in Visual Studio 

### ISSUE THREAD

**Issue by ravipuri** [OfficeDev/office-js#2715]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am debugging an Excel add-in, in Visual Studio 2022 and when the add-in completes authentication using Office dialog, closing the dialog manually or programmatically causes excel.exe to exit and thereby terminating my debugging session.

Error message:
The program 'excel.exe' has exited with code 4294967295 (0xffffffff).

Office Dialog code
```

export let loginDialog;
export function LoginFallbackInterop() {

    let url = "/azureadauth/login";
    let fullUrl = location.protocol + '//' + location.hostname + (location.port ? ':' + location.port : '') + url;

    Office.context.ui.displayDialogAsync(fullUrl,
        { height: 60, width: 30 }, function (result) {
            
            loginDialog = result.value;            
            
            loginDialog.addEventHandler(Microsoft.Office.WebExtension.EventType.DialogMessageReceived, processMessage);
        });
}
export function processMessage(arg) {
  loginDialog.close(); 
}

```

**Comment by yaweizhu-henson** [comment]
Thank you for your feedback, I will let engineer have a look at this issue

**Comment by rajeshpatil74** [comment]
Any solution for this issue ??
