### ISSUE TITLE
Excel add-ins using shared runtime and custom functions not rendering the task pane

### ISSUE THREAD

**Issue by caolgood** [OfficeDev/office-js#2716]
When opening a desktop Excel file with an add-in using a shared runtime installed, there is a chance that the task pane will fail to render the page and only show a blank screen. 
As soon as you resize the taskpane or the excel window the taskpane display pops back in. 

![image1](https://user-images.githubusercontent.com/23510349/179595694-e6e1de75-51ad-450b-9ea9-471febf297e0.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: (Version 2206 Build 16.0.15330.20246) 64-bit
* Operating System:  Windows 10 or 11, not reproducible on mac
* Browser (if using Office on the web): (Embedded) Edge with webview 2

## Context

Despite the workaround most of our users are going to be confused and will need to contact support for this
I have reproduced on other add-ins than the sample here, but so far only on addins with a shared runtime. Not only an issue with dev mode either, we have also seen this on our production addins on the office store.
The rate of reproduction seems to vary between machines, very consistent for some, takes multiple attempts for others. 

## Useful logs

When this issue occurs, there are no errors on the console logs or runtime logs, and the DOM is fully loaded in the edge devtools. Custom functions and other buttons still work. 

## Link to live example(s)
https://github.com/caolgood/shared-runtime-sample
Copy of the sample repo generated below 

## Steps to reproduce

1.  Use the yeoman office generator to create an excel Custom functions addin
     https://github.com/OfficeDev/generator-office
1. follow the steps in https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime to migrate to a shared runtime environment
2. run npm install, npm run build, npm run start:desktop
3. open an Excel file, install the addin 
4. add one of the addin’s custom functions (`=CONTOSO.CLOCK()`)
5. open the task pane
6. save and close the file,  then reopen
7. repeat steps 6-7 a few times until the task pane fails to display

**Comment by yaweizhu-henson** [comment]
Thanks for feedback, I will let engineer have a look into this issue

**Comment by celluj34** [comment]
We are having the same problem. I thought https://github.com/OfficeDev/office-js/issues/1303 might be related but it's hard to reproduce reliably.

**Comment by aluke1** [comment]
We are having the same issue. This is very frustrating to our users since they think the Add-In did not install properly when the task pane fails to load initially. We are also using a shared runtime with custom functions. I have not seen this issue on mac, only web and windows versions of excel.

**Comment by parched** [comment]
We have a similar problem. Specifically the taskpane is blank when it's first opened, but if you resize it, the content appears.

**Comment by bhattikashif** [comment]
We are facing same problem, any find a solution to this problem?

**Comment by Biktop** [comment]
The same issue under windows excel. And it works well under Mac and browser

**Comment by taralex77** [comment]
we are seeing the same issue. Had to roll back our release with support of shared runtime because of that.

**Comment by aluke1** [comment]
Hi @JinghuiMS (or others), has there been any progress on this? I have taken the debugging as far as I can. Here is what I have learned: 

1) The issue is only reproduce able on windows 11, but not all windows versions and excel versions. I am still not sure why I can reproduce the issue on some windows/excel combinations but not others. 

2) I can confirm the issue occurs on these windows + excel + edge combinations: 
     windows: Windows 11 Pro, 21H2, 22000; excel: Version 2207, Build 16.0.15427.20182; edge: 108.0.1462.46
     windows: Windows 11 Home, 22H2, 22621.525; excel: Version 2210, Build 15726.20202; edge: 108.0.1462.46

3) There are no errors or issues with js promises hanging when the task pane fails to load (as noted [in this issue](https://github.com/OfficeDev/office-js/issues/1303)). My logging indicates that all the js executes successfully.

4) The only workaround I have found is re-sizing the taskpane. Programmatically interacting with the DOM upon initialization does not do anything. 

This issue has been on-going for months and it is preventing us from releasing our product. Refactoring the application to avoid the shared runtime is not an option for us. Have there been any updates?

**Comment by randomevents** [comment]
@aluke1 @JinghuiMS  you can add these two to the list as well:
windows: Window 10 Enterprise, 21H2, 19044.2486; excel Version 2208, Build 15601.50456, Semi Annual Enterprise Channel, edge: 109.0.1518.78
windows: Window 11 Enterprise, 22H2, 22621.1265; excel Version 2301, Build 16026.20145, Current Channel, edge: 110.0.1587.46

**Comment by Biktop** [comment]
Any news regarding the issue? This bug blocks us from using shared runtime at all.

**Comment by donlvMSFT** [comment]
Hi @Biktop @randomevents , 

Product team had some fix which should related to this issue, could you help verify on latest CC version or semi-annual preview later than 16.0.16130.20306?

Thanks.

**Comment by Biktop** [comment]
Hi @donlvMSFT ,

I cannot reproduce this issue anymore on 16.0.16227.20212. It seems that it's fixed.

Thanks!
