### ISSUE TITLE
"onNewMessageCompose" launch event not working on desktop

### ISSUE THREAD

**Issue by maxxpm-ben** [OfficeDev/office-js#2717]
# Provide required information needed to triage your issue
The launch event onNewMessageCompose will not trigger the handler function on desktop. The function triggers as expected when using the web version, but I cannot get it to trigger from a desktop client. I have tried two different machines, both running Windows 10, and neither will trigger the handler function.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.15330.20264
* Operating System: Windows 10 21H1
 
## Expected behavior

The onNewMessageCompose handler function to trigger when a new message is composed on a desktop client.

## Current behavior

It appears that the function is not being called, but I am not receiving any errors, so I am not exactly sure why the function isn't being triggered.

## Steps to reproduce

Manifest File
```<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
  xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xsi:type="MailApp">
  <Id>5b9ee700-792a-4bff-88b8-afa04d121662</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>MAXX PM</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="MAXX PM"/>
  <Description DefaultValue="MAXX PM Outlook Add-In"/>
  <IconUrl DefaultValue="https://cdn.maxxpm.com/logos/icon-64.png"/>
  <HighResolutionIconUrl DefaultValue="https://cdn.maxxpm.com/logos/icon-128.png"/>
  <SupportUrl DefaultValue="https://maxxpm.com"/>
  <AppDomains>
    <AppDomain>https://localhost:3333</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.1"/>
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemEdit">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:3333/commands"/>
      </DesktopSettings>
    </Form>
  </FormSettings>
  <Permissions>ReadWriteMailbox</Permissions>

  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit" />
  </Rule>

  <DisableEntityHighlighting>false</DisableEntityHighlighting>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Requirements>
        <bt:Sets DefaultMinVersion="1.10">
          <bt:Set Name="Mailbox"/>
        </bt:Sets>
      </Requirements>
      <Hosts>
        <Host xsi:type="MailHost">
          <Runtimes>
            <Runtime resid="WebViewRuntime.Url">
              <Override type="javascript" resid="JSRuntime.Url" />
            </Runtime>
          </Runtimes>
          <DesktopFormFactor>
            <ExtensionPoint xsi:type="LaunchEvent">
              <LaunchEvents>
                <LaunchEvent Type="OnNewMessageCompose" FunctionName="onMessageComposeHandler" />
              </LaunchEvents>
              <SourceLocation resid="WebViewRuntime.Url"/>
            </ExtensionPoint>
          </DesktopFormFactor>
        </Host>
      </Hosts>
      <Resources>
        <bt:Urls>
          <bt:Url id="WebViewRuntime.Url" DefaultValue="https://localhost:3333/commands"/>
          <bt:Url id="JSRuntime.Url" DefaultValue="https://localhost:3333/assets/launchevent.js"/>
        </bt:Urls>
      </Resources>
    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>
```
HTML File
```<!-- Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT License. -->

<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=Edge" />

  <!-- Office JavaScript API -->
  <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
  <script type="text/javascript" src="/assets/launchevent.js"></script>
</head>

<body>

</body>
</html>
```
JS File
```let mailboxItem;

Office.onReady(() => {
  // If needed, Office.js is ready to be called
  mailboxItem = Office.context.mailbox.item;
});

function onMessageComposeHandler(e) {
  if (mailboxItem.itemType === "message") {
    mailboxItem.getComposeTypeAsync((type) => {
      if (type.value.coercionType === "html") {
        mailboxItem.from.getAsync((result) => {
          const email = result.value.emailAddress;
          // eslint-disable-next-line no-undef
          fetch(`/email-signature/${email}`, {
            method: "GET",
            headers: {
              SIGNATURE_STATE: "MY_SIGNATURE_STATE",
            },
          })
            .then((res) => {
              res.json().then((data) => {
                mailboxItem.body.setSignatureAsync(data.signature, {
                  coercionType: "html",
                });
              });
            })
            .catch((err) => console.log(err));
        });
      } else {
        console.log(type.value.coercionType);
      }
    });
  } else {
    console.log(mailboxItem.itemType);
  }
}
```

## Context

I am trying to create an add-in to add a signature to email messages.

## Useful logs

Runtime Logs when a new message is composed.
> 7/19/2022 15:38:01	Verbose	Runtime	[Console] [Log] Platform Bundle - Office exists!		
7/19/2022 15:38:01	Verbose	Runtime	[Console] [Log] Platform Bundle - Office.actions exists!		
7/19/2022 15:38:01	Verbose	Runtime	[Console] [Log] Platform Bundle - Office.actions.associate exists!		
7/19/2022 15:38:01	Verbose	Runtime	[Console] [Log] Outlook Batch JS loaded!		
7/19/2022 15:38:01	Verbose	Runtime	[Console] [Log] Outlook LaunchEvent JS loaded!		
7/19/2022 15:38:01	Verbose	Runtime	[Console] [Log] `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.		
7/19/2022 15:38:01	Verbose	Runtime	[Console] [Log] `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.		
7/19/2022 15:38:01	Verbose	Runtime	[Console] [Log] InvokeMailboxCreateOM was invoked!["{\"hostVersion\":\"16.0.15330.20264\", \"itemType\":4, \"permissionLevel\":2, \"userEmailAddress\":\"\", \"userDisplayName\":\"\", \"userProfileType\":\"office365\", \"userTimeZone\":\"Mountain Standard Time\", \"conversationId\":null, \"ewsUrl\":\"https://outlook.office365.com/EWS/Exchange.asmx\", \"restUrl\":\"https://outlook.office.com/api\", \"itemNumber\":1073741833, \"roamingSettings\":\"{}\", \"extensionPointType\":8, \"enableBetaAPIs\":false, \"displayLanguage\":\"en-US\", \"contentLanguage\":\"en-US\", \"officeVersion\":\"16.0.15330.20264\", \"requirementSets\":\"{\\\"Mailbox\\\":\\\"1.12\\\",\\\"OutlookTelemetry\\\":\\\"1.2\\\"}\", \"isFromSharedFolder\":false, \"shouldRunNewCodeForFlags\":1}"]		
7/19/2022 15:38:01	Verbose	Runtime	[Console] [Log] SDX Control is ready!		

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
I don't see any calls to Office.actions.associate in the code snippets you provided. That is required for Desktop Outlook. Can you try that? You can read more about it here: https://docs.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#implement-event-handling

**Comment by maxxpm-ben** [comment]
It appears that was the problem. Thanks!
