### ISSUE TITLE
Office Js providing wrong attachment ID while dragging and dropping email from shared mailbox to own mailbox in Outlook Client

### ISSUE THREAD

**Issue by sumitjain-rsi** [OfficeDev/office-js#2719]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
Office Js is providing the wrong attachment id when user drag and drop any email from shared mailbox to his own mailbox. It is happening only in outlook desktop client.it may be happening due to id cache in client. When application check on browser it provides the correct attachment id. 

Due to this bug our Add-in functionality is not working as expected.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2206 Build 16.0.15330.20260) 64-bit 
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome
 
## Expected behavior

Office Js should provide us the correct attachment id. which match to exchange api.

## Current behavior

It provides the old attachment id which was assigned on shared mail box

## Steps to reproduce

1.  Drag any email from Shared mailbox folder to own mailbox folder
2. run Office Js in add-in to check the attachment id
3. run same addin in browser outlook to check attachment id

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by sumitjain-rsi** [comment]
[OutlookTestSharedMailbox.zip](https://github.com/OfficeDev/office-js/files/9347674/OutlookTestSharedMailbox.zip)
attached is the test add-in application to reproduce the issue. it is the sample application that created thru VS2022 template.

**Comment by exextoc** [comment]
Apologies for the delay in responding.
We are actively investigating this issue and will get back to you shortly with our findings.

**Comment by sumitjain-rsi** [comment]
any update on the issue
