### ISSUE TITLE
Word Add-in breaks the undo button behavior 

### ISSUE THREAD

**Issue by AhmadSukkar98** [OfficeDev/office-js#2720]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected behavior
Undo button works even while I am using the Add-in

## Current behavior
Nothing happen when you press on an active undo button while the add-in is open

## Steps to reproduce
1. Open the Add-in in a word document
2. Write something in the document
3. Edit the written text
4. The Undo button gets active
5. Try to Undo the changes by pressing the button
6. Nothing will happen!

## Link to live example(s)
1. Here is a clean add-in that tries to expand the current selection range on selectionChange
2. [add-in sample](https://github.com/AhmadSukkar98/WordIssueWeirdUndoButtonBehavior)
3.  [Recorded screen video](https://drive.google.com/file/d/1FToShYE1ftze_YNnP2m2IruSDFcecgtP/view?usp=sharing)

# Provide additional details
1. Make sure to add office  `handlerAsync` in the add-in on `DocumentSelectionChanged`
2. In the handler callback tries to get the current selection range and use  `expandToOrNullObject`
4. It seems that using `expandToOrNullObject` is introducing the issue
5. please take a look at the provided sample 

## Your Environment
* Platform:  Office on the web
* Host: Word
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome

## Context
We want to allow our users to undo the actions performed by our taskpane add-in

**Comment by xiruatms** [comment]
Thanks for reporting this.

To make further steps on investigating details, will you please help to share a screen recording of your testing steps? That'll be greatly helpful.

**Comment by AhmadSukkar98** [comment]
@xiruatms  Hi,
Sure, here is a screen recorded video demonstrating the issue
[Video](https://drive.google.com/file/d/1FToShYE1ftze_YNnP2m2IruSDFcecgtP/view?usp=sharing)

Thank you in Advance.

**Comment by JinghuiMS** [comment]
@AhmadSukkar98   
Thanks for reporting the issue. It's actually not right behavior and it has been put on our backlog 6353463. We will let you know when there is update. Thanks!
