### ISSUE TITLE
Office.context.mailbox.item.removeAttachmentAsync() is not recieving response all the time.

### ISSUE THREAD

**Issue by debangshui2chain** [OfficeDev/office-js#2721]
Office.context.mailbox.item.removeAttachmentAsync() is not recieving response all the time.

Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Web, outlook desktop
* Host : Outlook
* Office version number: 16.63
* Operating System: mac & windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
whenever we detach a file using Office.context.mailbox.item.removeAttachmentAsync() it returns a response which we are not getting everytime. It should return that everytime.
And also attach a file attachment response status in outlook desktop app ui like outlook web so that user gets to know when file attachment is successful.

**Comment by exextoc** [comment]
We are not able to repro this. Can you let us know the scenario when you face this problem. It will be helpful, if you can provide us a video of the issue.
