### ISSUE TITLE
OfficeJS Word add-in (on the web) support for Office.StartupBehavior.load

### ISSUE THREAD

**Issue by repl-minatee-p** [OfficeDev/office-js#2722]
I am developing a word add-in which should be loaded on document open and it should support both desktop and web apps.

When I am trying to use 'Office.addin.setStartupBehavior(Office.StartupBehavior.load)' for office word on the web then getting RichApi InvalidRequest error as mentioned below.

RichApi.Error: InvalidRequest
at new n (word-web-16.00.js:25:309056)
at i.processRequestExecutorResponseMessage (word-web-16.00.js:25:373222)
at word-web-16.00.js:25:371285

## Environment Details :
* Platform :  Office on the web
* Host : Word
* Office version number: 16.0.15518.41016
* Browser (if using Office on the web): Google Chrome (Version 103.0.5060.134)
 
## Expected behavior
Word add-in should be loaded on document open without any error.

## Current behavior
Below error is thrown and add-in is not loaded on document open.
RichApi.Error: InvalidRequest
at new n (word-web-16.00.js:25:309056)
at i.processRequestExecutorResponseMessage (word-web-16.00.js:25:373222)
at word-web-16.00.js:25:371285

## Steps to reproduce
1. Call Office.addin.setStartupBehavior(Office.StartupBehavior.load) api.

## Context
As part of our product's requirement, we need to develop a word add-in which should be loaded on document open and it should support both desktop and web apps. But due to this issue I am not able to proceed with my add-in development work.

## Useful logs

- [RichApi.Error: InvalidRequest
at new n (word-web-16.00.js:25:309056)
at i.processRequestExecutorResponseMessage (word-web-16.00.js:25:373222)
at word-web-16.00.js:25:371285 ] Console errors
- [ 
![image](https://user-images.githubusercontent.com/107394673/180414318-164ca262-7ee8-4afc-ad70-8d0bbf5b1c33.png)
] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by xiruatms** [comment]
Thanks for reporting this.

Unfortunately, I can't repro this with my environment. Are you still encountering this exception consistently? If possible, @repl-minatee-p , will you please share your codes snippet? A screen record of the issue would be much helpful.

We can investigate deeper if there are more information.

**Comment by JinghuiMS** [comment]
The same issue with https://stackoverflow.com/questions/73054441/officejs-word-add-in-support-for-office-startupbehavior-load

**Comment by repl-minatee-p** [comment]
I freshly created a project using 'yo office' and tried again. It seems to be working. So, I am closing the issue.

**Comment by JinghuiMS** [comment]
Cool~ Glad to see you unblocked yourself!
