### ISSUE TITLE
RecipientsChangedEvent is triggered when switching between menu items

### ISSUE THREAD

**Issue by maartendebal** [OfficeDev/office-js#2724]
The RecipientsChangedEvent is triggered when clicking on tracking af using the Scheduling Assistant and adding a recipient.

## Your Environment

* Platform: PC Desktop
* Host: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2206 Build 16.0.15330.20260) 64-bit
* Operating System: Windows 10 Pro 21H2 19044.1826
 
## Expected behavior
Event only triggers when a recipient has been added, not when changing menu items.

## Current behavior
Event is triggered on every menu item click after adding a recipient.

## Steps to reproduce
1. Setup event listener
2. Go to scheduling assistant and add recipient
3. Go to tracking

## Context
In a certain part of our add-in workflow it's not allowed to add recipients and I block it using the event, while also informing the user. The issue here is that the user if informed of the blocking when clicking menu items even though the user didn't add another recipient.

**Comment by ztcddsb** [comment]
Thanks for reporting this issue regarding RecipientsChangedEventArgs. It has been put on our backlog. We unfortunately have no timelines to share at this point 

Internal tracking id: Office: 5221404
