### ISSUE TITLE
After following Custom Runtime setup tutorial, `Excel` is no longer defined; other unreliabilities in shared runtime

### ISSUE THREAD

**Issue by yuanagain** [OfficeDev/office-js#2727]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi! After following the tutorial [at docs.microsoft.com](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial), any calls to the `Excel` namespace throw errors, i.e.

```
TypeError: undefined is not an object (evaluating 'Excel.run')
```

## Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: OS X, MS Excel Office 365 
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1.1
* Operating System: OS X
* Browser (if using Office on the web): Built-in Edge
 
## Expected behavior
This functionality was previously working before implementing the shared runtime. This function (run from the task pane) would report the currently selected range.

## Current behavior
Any runs to `Excel.run(...)` fail: 

```
TypeError: undefined is not an object (evaluating 'Excel.run')
```
![Screen Shot 2022-07-25 at 8 15 25 PM](https://user-images.githubusercontent.com/6503523/180896376-ad1c239d-7294-4aee-8e1c-e6af751b6160.png)

## Steps to reproduce

1. Generate a custom functions Excel plugin using the yeoman generator
2. Add in a React component, i.e.
```tsx
import App from "./App";
import * as React from "react";
import * as ReactDOM from "react-dom";
import * as ReactDOMClient from 'react-dom/client';

/* global document, Office, module, require */

let isOfficeInitialized = false;
const title = "...";
const container = document.getElementById("container")
const root = ReactDOMClient.createRoot(container);

const render = (Component) => {  
  root.render(
      <Component title={title} isOfficeInitialized={isOfficeInitialized} />
  )
};

/* Render application after Office initializes */
Office.onReady(() => {
  isOfficeInitialized = true;
  render(App);
});

if ((module as any).hot) {
  (module as any).hot.accept("./App", () => {
    const NextApp = require("./App").default;
    render(NextApp);
  });
}
```

`taskpane.html`
```
<!doctype html>
<html lang="en" data-framework="typescript">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ShorthandAI Task Pane Add-in</title>

    <!-- Office JavaScript API -->
    <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
    <script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/custom-functions-runtime.js" type="text/javascript"></script>
    <!-- For more information on Fluent UI, visit https://developer.microsoft.com/fluentui#/. -->
    <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/11.0.0/css/fabric.min.css"/>

    <!-- Template styles -->
    <link href="taskpane.css" rel="stylesheet" type="text/css" />
</head>

<body class="ms-font-m ms-Fabric">
    <div id="container"></div>
</body>

</html>
```

4. Follow Shared Runtime setup tutorial [at docs.microsoft.com](https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial)

## Link to live example(s)

N/A

## Context
I am trying to 1) get the address and contents of the user-selected range and 2) manipulate named values.

## Useful logs, screenshots, other notes

It's worth noting that refreshing the taskpane now results in non-deterministic behavior. Oftentimes it will come up blank and the React components neither render nor log. Reloading manually a few times results in eventually coming across a "working" reload. Note that when it succeeds a few errors are thrown.

![Screen Shot 2022-07-25 at 8 15 42 PM](https://user-images.githubusercontent.com/6503523/180896866-fcff9b30-ba54-4f7c-b947-b9ea707f76f1.png)

Sometimes the Office.js runtime complains:
![Screen Shot 2022-07-25 at 8 14 40 PM](https://user-images.githubusercontent.com/6503523/180896869-48ba8db6-5328-401b-9ba9-db697e6aa36d.png)

![Screen Shot 2022-07-25 at 8 15 34 PM](https://user-images.githubusercontent.com/6503523/180896871-02778c4f-67d5-46f2-8d4d-264b5327668c.png)
![Screen Shot 2022-07-25 at 8 15 25 PM](https://user-images.githubusercontent.com/6503523/180896872-a5804ae6-f877-40b2-8e5f-18524035abd7.png)

Thanks for your help!

**Comment by JinghuiMS** [comment]
@madhavagrawal17  This issue is related to shared runtime, could you please help take a look. Thanks!
