### ISSUE TITLE
Outlook add-in sso for MSA user in OWA failed with  "13012 API is not supported in this platform"

### ISSUE THREAD

**Issue by msyezhong** [OfficeDev/office-js#2729]
Outlook add-in sso for MSA user in OWA failed with  "13012 API is not supported in this platform".

Environment:
OWA version 20220715009.12

With the same manifest and get token code, it works for my aad account, but fails for my msa account. I do not set forMSGraphAccess. Can anyone tell me the reason and how to fix it?

Appreciate it a lot for your help in advance.

**Comment by exextoc** [comment]
Hello @msyezhong, we currently do not support add-in SSO for MSA accounts (Outlook.com or Gmail mailbox), and the error you are seeing is the expected response for this scenario. 

You can find more information on this here : [getAccessToken API Documentation](https://docs.microsoft.com/en-us/javascript/api/office/office.auth?view=common-js-preview#office-office-auth-getaccesstokenasync-member:~:text=Important%3A%20In%20Outlook%2C%20this%20API%20isn%27t%20supported%20if%20the%20add%2Din%20is%20loaded%20in%20an%20Outlook.com%20or%20Gmail%20mailbox.)

**Comment by msyezhong** [comment]
@exextoc Thanks for your reply.
Three more questions, 

1. The add-in SSO for MSA account is not supported for Outlook add-in, or all office add-in. 
2. Do you have plan to support it?
3. If the SSO is not support, it means that we need to let user manually sign in again in our add-in?

**Comment by mattgeim** [comment]
Hi @msyezhong, 

> 1. The add-in SSO for MSA account is not supported for Outlook add-in, or all office add-in.

MSA users should work in the Outlook desktop clients that have SSO support, but they are not supported in OWA at this time. MSA is supported for Office add-ins. 

> 2. Do you have plan to support it?

At this time we do not have any plans to share around support for MSA account support for SSO in OWA.

> 3. If the SSO is not support, it means that we need to let user manually sign in again in our add-in?

You should use a fallback method, such as the dialog API and MSAL, and enable that for any time SSO may not be available in a client or some other issue occurs.  The documentation for SSO contains more information on this, available [here.](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-with-office-dialog-api)

Please feel free to re-open if there are any additional issues that weren't addressed - thanks!
