### ISSUE TITLE
A Bug happens when save  custom properties.

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#273]
## Expected Behavior
When close the document, save the changes custom properties.
But it doesn't.

## Current Behavior
Desktop Office.

## Steps to Reproduce, or Live Example
1、Save current document to local folder.
2、Click add-in button by office-js, Saved a custom property to Document CustomProperties(Not change other anything).
3、Close the current document, And there is no any prompt(directly closed)
4、Reopen the document，the aboved custom property didn't saved.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: __PC desktop____
* Host [Excel, Word, PowerPoint, etc.]: __Word____
* Office version number: __Office 2016____
* Operating System: __Windows____
* Browser (if using Office Online): __-____

**Comment by dmahugh** [comment]
I'm not able to reproduce this behavior. When I follow the steps as shown below, I get prompted to save the changes, and when I save the changes and then re-open the document the custom property has been saved.
![repro-failed-issue-273](https://user-images.githubusercontent.com/1130262/48084224-0045d080-e1ac-11e8-8c9c-e675bfd58d14.png)

**Comment by hengchengfei** [comment]
I had record the video。
The question has been existed.

[https://www.chengfeisoft.com/dfzq-office/help/sample.mp4](https://www.chengfeisoft.com/dfzq-office/help/sample.mp4)

**Comment by dmahugh** [comment]
Thanks for recording the video, @hengchengfei . I have re-opened the issue and will look into this further.
