### ISSUE TITLE
Loading HTML body from task-pane breaks output of getAttachmentsAsync

### ISSUE THREAD

**Issue by barclayadam** [OfficeDev/office-js#2730]
# Provide required information needed to triage your issue

If adding a signature via event-based activation with an embedded image attachment, then subsequently loading the HTML body in the task-pane, the attachment is "replaced" by a 0-length image with the wrong name.

## Your Environment

* Platform: PC Desktop
* Host: Office
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2208 Build 16.0.15519.20000) 64-bit 
* Operating System: Windows 11
 
## Expected behavior
Reading the HTML body does not modify the list of attachments.

## Current behavior / steps to reproduce
We set a signature with an embedded image in event-based activation script:

````typescript
function setSignatureWithEmbeddedImage() {
    Office.context.mailbox.item.addFileAttachmentFromBase64Async(
        'iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==',
        'redDot.png',
        {
            isInline: true,
        },
        () => {
            Office.context.mailbox.item.body.setSignatureAsync(`<img src="cid:redDot.png" />`,
                {
                    coercionType: 'html',
                });
        },
    );
}

Office.onReady(() => {});

Office.actions.associate('onMessageComposeHandler', () => setSignatureWithEmbeddedImage());
````

From within the taskpane if we list attachments, read the HTML body, and then re-list the attachments that "redDot.png" image is replaced in the list with a 0-length `image002.png` image:

````typescript
// Task pane load
Office.context.mailbox.item.getAttachmentsAsync((r) => {
        console.log(r.value);

        Office.context.mailbox.item.body.getAsync("html", () => {
            console.log('HTML loaded');

            Office.context.mailbox.item.getAttachmentsAsync((r) => {
                console.log(r.value);
            })
        });
    });
````

Output:

![image](https://user-images.githubusercontent.com/973909/181215166-fa29f4ef-188c-4066-967b-c4a33d41d159.png)

## Link to live example(s)

I have been unable to replicate this in the Script Lab environment, not sure if it's me not figuring out how event-based activation works there (the examples for event-based activation don't appear to actually register event handlers?)

## Context

This issue has been discovered during the investigation of another bug that appears to be removing existing attachments when forwarding an email using our add-in. Still investigating but curious if could be caused by a common issue to handling of attachments.

Separately this affects us as when a signature is changed we may wish to remove the existing embedded images we have added but we cannot as we will not have the correct reference (i.e. we store that we have added image with id 2, but when reading the HTML that is being changed to 3 and removing therefore fails).

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Thank you for the post. We are currently investigating this issue.

**Comment by exextoc** [comment]
This behavior happens when Outlook saves the file to disk whenever saving the document. The `image001.png` is the name of the local file saved to disk. What scenario is this impacting for you?

**Comment by barclayadam** [comment]
We add attachments and then may need to, at a later time in the lifecycle of composing an error, remove that attachment. We store the name and id of the attachment as it is added, but both of those values change meaning we have no way of removing the attachment.

Primarily, this issue is therefore that the id changes, not the name

**Comment by exextoc** [comment]
This is caused by the underlying way that Word renders the inline image and email body when getBody is called. If your main concern is not being able to remove the attachment when removing the signature, you can use the workaround of adding the inline base64 image through html like the following:
```
Office.context.mailbox.item.body.setSignatureAsync("<img src='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==' alt'Red dot' />",
                {
                    coercionType: 'html',
                });
```
Then you can just remove the signature and the image will be removed as well and no attachment will remain on the email item.
