### ISSUE TITLE
🐛 Cannot install functions if a repeating matrix argument is marked as required

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#2732]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

If an argument is simultaneously **repeating**, **matrix** and **optional: false**, add-in fails to install the custom functions.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: evergreen
* Operating System: Windows 11
* Browser (if using Office on the web): evergreen Chrome
 
## Expected behavior

- Addin installs custom functions successfully
- The first of the arguments in the Intellisense is marked as required
- The other arguments are marked as optional
- Excel controls that at least one argument is specified

```
CONTOSO.ANSWER(Argument1, [Argument2], [Argument3], ...)
```

## Current behavior

Add-in fails to install the custom functions altogether.
There is no reasonable troubleshooting message for developer 

(BTW, the latter is a related general problem for us, could we also ask to direct those errors into the console so we could understand what was the offending function? It takes a lot of trial-and-error to understand what caused the functions to suddenly top loading)

## Steps to reproduce

1. Use https://github.com/VelixoSolutions/optional-repeating-matrix-with-address-bug
2. build the project
3. Start the dev server 
4. In the `dist/functions.json`, add an explicit `optional: false` to the argument definition. 
5. **I want to emphasize that this is a valid configuration according to the documentation**: I just found no way to do it with autogeneration of 
metadata. We use manual metadata assembly in our project due to localization needs.
6. Open Excel online and sideload the manifest.

## Context

Cannot achieve consistency with our legacy COM-based add-in, migration to the modern framework hampered by this issue.

**Comment by JHJ-MS** [comment]
Hi @wh1t3cAt1k , if the argument is simultaneously repeating, **number**, and optional: false, will the custom functions fail to install? 
If it will, I think this may cause by repeating parameters by default is optional and cannot change to not optional. Otherwise, we don't know how many repetitions are appropriate. 

If it won't, It should be a bug.

**Comment by wh1t3cAt1k** [comment]
@JHJ-MS it's quite clear in my view, that the behaviour should be the same as we have in the COM-based add-in: Excel would check that at least the first of the repeating arguments is specified (and display it as non-optional in Intellisense), and the rest of repetitions are displayed as optional.

Argument1, [Argument2], ...

I can check the number case later today

**Comment by wh1t3cAt1k** [comment]
Still relevant

**Comment by wh1t3cAt1k** [comment]
@JinghuiMS @JHJ-MS the bug reproduces even for non-matrix arguments, so I will reformulate the bug title.

```
{
    "functions": [
        {
            "description": "Returns 42",
            "id": "ANSWER",
            "name": "ANSWER",
            "options": {
                "requiresAddress": true
            },
            "parameters": [
                {
                    "description": "Repeating argument.",
                    "name": "Argument",
                    "repeating": true,
                    "type": "number",
                    "optional": false
                }
            ],
            "result": {
                "type": "number"
            }
        }
    ]
}
```

**Result:**

![image](https://user-images.githubusercontent.com/5159662/193563515-1852adc9-cf6d-431c-a754-c2d9b9b2ddb3.png)

**Expected result:**

The behaviour should be the same as we have in the COM-based add-in: Excel would check that at least the first of the repeating arguments is specified (and display it as non-optional in Intellisense), and the rest of repetitions are displayed as optional.

_**Argument1**, [Argument2], ..._

**Comment by JHJ-MS** [comment]
Hi @wh1t3cAt1k, the non-optional repeating parameter is not supported for Custom Functions now.  To achieve your goal, you can append an additional non-optional argument. Besides, you can go to [Microsoft 365 Developer Platform Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) to request a new feature. 
Thanks for your reporting again.

**Comment by wh1t3cAt1k** [comment]
@JHJ-MS @JinghuiMS @RuizhiSunMS @Wenjun-Gong please reopen this. The workaround proposed (adding another argument) is not working for us because we need to maintain 100% function-level compatibility with our legacy XLL add-in.
