### ISSUE TITLE
Range.getPrecedents() throws a "requested resource doesn't exist" if the cell has no precedents

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#2733]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Excel Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: latest
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome evergreen
 
## Steps to reproduce

1. Select a single cell that does not depend on any other cell.
2. Using Office.JS, do:

```
const activeCell = context.workbook.getActiveCell();

activeCell.load({
    address: true,
    formulas: true,
});

await context.sync();

const precedents = activeCell.getPrecedents();

await context.sync();
```

## Expected behavior

Precedents is returned as `isNullObject === true`.

## Current behavior

```
RichApi.Error: The requested resource doesn't exist.
    at new n (excel-web-16.00.js:25:308992)
    at i.processRequestExecutorResponseMessage (excel-web-16.00.js:25:373158)
```

The error is non-descriptive and provides little insight about the nature of the error.

## Potential workarounds

Currently the try/catch is the only workaround, however our developers are still confused by this error in the console.

I would change the behaviour as outlined above, or introduce a `getPrecedentsOrNullObject()` method in the API.

**Comment by guliums** [comment]
Hi @wh1t3cAt1k , thanks for reporting the issue. For this API, "ItemNotFound" error is by design if there is no precedents. It is align with other APIs like Range.find() or .getItem(). And the workaround is to use try catch to detect such type of error. For getPrecedentsOrNullObject(), You may go to [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) to request a new feature for that. New feature request will be considered when we go through our planning process. Thanks for your support!

**Comment by wh1t3cAt1k** [comment]
Doesn't it have poor performance implications to always rely on exception handling?

Both `Range.find()` and `Range.getItem()` have the `...orNullObject` counterpart, but not this method.

I'm surprised that we need to file a whole feature request and collect votes for something that looks like a very minor change that remedies a valid (though minor too) deficiency in the API design.

**Comment by guliums** [comment]
Hi @wh1t3cAt1k , sorry for inconvenience. Your point makes sense. Currently both getPrecedents and getDependents APIs don't have corresponding *orNullObject APIs. I have created backlog (tracked as 6351772 internally) to add .orNullObject for getPrecedents and getDependents APIs.

**Comment by Wenjun-Gong** [comment]
similar as the behavior in #2268. Track that internally as a group.
