### ISSUE TITLE
There is no way to avoid recalculations / updates with Application.suspend...UntilNextSync when trying to avoid payload size limit

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#2734]
This feels like a design limitation in Office.js that I feel needs be addressed since it results in a poorer user experience when working with large datasets.

[This piece of documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/performance#suspend-screen-updating) states:

> Don't call `suspendScreenUpdatingUntilNextSync` repeatedly (such as in a loop). Repeated calls will cause the Excel window to flicker.

At the same time, Excel Online has a payload size limitation that causes `context.sync()` to fail if it has accumulated too big a changeset against the current workbook.

Same applies to `Application.suspendApiCalculationUntilNextSync()`.

This produces a dilemma: to avoid the payload size limit, we'll have to call `context.sync()` intermittently when processing a large dataset, however doing so will result in unnecessary recalculations and screen updates (flicker).

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: latest
* Operating System: Windows 11 
* Browser (if using Office on the web): Chrome
 
## Expected behavior

There is a way to avoid flicker and unnecessary recalculations when processing a large dataset.

Can we have something similar to on-off methods like in VBA? 

```
try {
    context.application.screenUpdating = false;
    context.application.calculationSuspended = false;

    ...
} finally {
    context.application.screenUpdating = true;
    context.application.calculationSuspended = true;
}
```

Or alternatively:

```
    // Will only revert as soon as Excel.run() finishes.
    // -
    context.application.suspendScreenUpdatingUntilExcelRunFinishes();
    context.application.suspendApiCalculationUntilExcelRunFinishes();
```

## Current behavior

No way to avoid flicker / recalculations.

## Steps to reproduce

Using Office.JS, for rows from 1 to 100000 (pick a greater value if not repro) in a workbook, do:

```
context.application.suspendApiCalculationUntilNextSync();
context.application.suspendScreenUpdatingUntilNextSync();

for (let index = 1; index < 100000; index++) {
    const cell = work.getRangeByIndexes(rowIndex, 1, 1, 1);
    cell.values = [['42']];
}

await context.sync();
```

Afterwards, to a `context.sync()` - you will see a RichApi.Error.

If, inside the loop, you do a `context.sync()` every 100-1000 rows for example, it solves the payload size limit but produces visual flicker, even if you call `suspendScreenUpdatingUntilNextSync` again.

**Comment by JinghuiMS** [comment]
Thanks for reporting this issue. I tried it on Excel Win32 and Wac platform by using below queries. I didn't see the flicker and richapi.error. Could you provide the repro video to help us better understand your scenarios? Please let us know if I have any misunderstanding. Thanks.
```
async function run() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    for (let index = 1; index < 100000; index++) {
      const cell = sheet.getRangeByIndexes(index, 1, 1, 1);
      cell.values = [['42']];

      await context.sync();
    }
    await context.sync();

  });
}
```

**Comment by wh1t3cAt1k** [comment]
@JinghuiMS if you removed the inner context.sync() you would definitely see a RichApi.Error because request payloads are limited in size, especially in Excel Online as mentioned in the ticket description.

I am talking about the conceptual problem here: 

- on the one hand, you **have** to sync() regularly to avoid hitting the request payload limit.
- on the other hand, as soon as you sync(), it **will** re-enable ScreenUpdating (and user will see screen updates prematurely!) and API calculation will happen. This is simply because of how `suspend...UntilNextSync` methods are designed.

There is simply no way to **both** a) break down request payload into smaller chunks **and** b) only re-enable calculation / screen updating **once** at the very end of our long-running operation. 

This is possible in the VBA and it is quite a basic scenario, therefore we kindly request to support it: please refer to the "Expected behaviour" section in the original description.

Thanks a lot for your help! This is sorely needed, as we are one of those companies that put Excel limits to the test!

**Comment by JinghuiMS** [comment]
For new feature request, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.

**Comment by wh1t3cAt1k** [comment]
Note that this can be more easily worked around if this is implemented (also submitted by our company):

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/abstract-away-the-5mb-api-request-limit-when-doing-excel-interop/idi-p/3629289

**Comment by wh1t3cAt1k** [comment]
We have submitted the idea specifically for this issue: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/support-permanent-application-screenupdating-setter-instead-of/idi-p/3666900#M1434

**Comment by JinghuiMS** [comment]
Closing this issue because it appears to be new feature ask, but please let us know if you have further questions or feel it needs to be re-opened.

**Comment by wh1t3cAt1k** [comment]
@JinghuiMS we just had a complaint about the screen flicker in a piece of a long-operation logic that necessarily needs to do a lot of `sync()` calls.

There is no way we could disable `screenUpdating` until the end of `Excel.run`, not the next sync(), which would completely solve our situation.

Is it super technically difficult to expose a new method in the API since you already have `suspendScreenUpdatingUntilNextSync()`? I would imagine it would reuse the same infrastructure, but postpone the "reversion" to updating screen until the end of Excel.run().

**Comment by JinghuiMS** [comment]
Thanks for reaching us again.
Add feature crew @donlvMSFT for more insights.

**Comment by donlvMSFT** [comment]
Thanks, we'll review this request and update later.

**Comment by eqinox76** [comment]
No idea why this ticket does not get more upvotes. The requirement to do so many `sync()` calls which are really slow (3000 cells with simple numbers take 500ms-1s) and to do it single threaded is making bigger data imports painfully slow.
The flickering is not helping the user experience at all.
I also can not find the promised alternative {API](https://stackoverflow.com/a/51737030) to make faster data imports.

**Comment by wh1t3cAt1k** [comment]
Hi @eqinox76 , you seem to be talking about an adjacent issue with the `.sync()` payload limitation. I completely agree. For that one, please take time to vote for [this idea](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/abstract-away-the-5mb-api-request-limit-when-doing-excel-interop/idi-p/3629289) and get everyone you know to vote for it.

**Comment by wh1t3cAt1k** [comment]
@donlvMSFT @JinghuiMS

I just wanted to revisit this and let you know that it's still very much relevant and produces annoying UX.

I noticed that `context.runtime.enableEvents` has already been exposed for some time: it should be really easy to have the same for `screenUpdating` since it is easily available for VBA and the host API supports it?

Not "until the next sync" but imperatively switch it on and off just like you can do in VBA. That would solve the problem with our long-running object model operations.

**Comment by donlvMSFT** [comment]
Hi @wh1t3cAt1k , thanks for revisit this. We also reviewed the feature request on community, thanks for raise that request. 

After careful consideration, for this `context.application.screenUpdating` and `context.application.calculationSuspended` feature request, we don't have plan to support in the short term because of other higher priorities.

We'll review these requests in next planning cycle, and we recommend you to upvote the Tech Community Ideas item, which will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.
