### ISSUE TITLE
getSharedPropertiesAsync() is undefined in outlook desktop in windows

### ISSUE THREAD

**Issue by somenathmaji** [OfficeDev/office-js#2735]
The user can't use our addin in a shared mailbox in outlook desktop in windows 10. They are using exchange online. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook 32 bit
* Office version number: Version 2205 Build 16.0.15225.20292
* Operating System: Windows 10
* Browser (if using Office on the web): No
 
## Expected behavior
The API should return true when a shared mailbox is in context.

## Current behavior
The `getSharedPropertiesAsync()` API is returning false in a shared mailbox.

## Steps to reproduce

1. Open any outlook addin
2. Open the console in inspect window
3. Run `Office.context.mailbox.hasOwnProperty("getSharedPropertiesAsync")` which returns false on a shared mailbox.

## Context
The user is not able to use the addin in a shared mailbox.

## Useful logs
<img width="553" alt="Screenshot 2022-07-28 at 7 05 29 PM" src="https://user-images.githubusercontent.com/10449421/181518523-43f0678d-d195-4c6b-8eaa-794ca04567e4.png">

**Comment by exextoc** [comment]
According to our [documentation](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-preview#outlook-office-messageread-getsharedpropertiesasync-member(1)), the `getSharedPropertiesAsync` API is a method on the `Office.context.mailbox.item` object, as opposed to the `Office.context.mailbox` object.

**Comment by somenathmaji** [comment]
We might have missed it. Thank you.

**Comment by somenathmaji** [comment]
We ran the proper command this time but got the following error -
![Screenshot 2022-08-03 at 8 57 55 PM](https://user-images.githubusercontent.com/10449421/182647513-621c36aa-1196-4283-8600-13a8a4c1749e.png)

`Office.context.mailbox.item` is undefined in a shared mailbox.
![Screenshot 2022-08-03 at 8 57 08 PM](https://user-images.githubusercontent.com/10449421/182647382-ccbf32d0-fe88-4218-905b-f3c0920a8843.png)

When we checked the shared mailbox email id, it's showing the user's personal mailbox's email id.
Going to reopen this ticket, could you please suggest any solution here?

**Comment by somenathmaji** [comment]
@exextoc Could you please look into this once?

**Comment by somenathmaji** [comment]
@exextoc Could you please provide some input here?

**Comment by somenathmaji** [comment]
Hi Team, could you please look into this?

**Comment by somenathmaji** [comment]
Hi Team, any update?

**Comment by somenathmaji** [comment]
Hi Team,

Could we please have an update?

Thanks

**Comment by samantharamon** [comment]
Hi @somenathmaji,

Apologies for missing your messages after this issue was reopened. Let me look into this further and I'll get back to you.

**Comment by samantharamon** [comment]
Thanks for your patience, @somenathmaji. To confirm, does the user still have the appropriate permissions to the shared mailbox? Once they've verified this, could they try removing and re-adding the mailbox to see if that makes a difference?

Please also note the [shared mailbox scenario limitations when in the Message Compose mode](https://docs.microsoft.com/office/dev/add-ins/outlook/delegate-access?tabs=windows#limitations).
