### ISSUE TITLE
PivotField - Set Number Format

### ISSUE THREAD

**Issue by jnSWPC** [OfficeDev/office-js#2737]
## Post how-to questions about your code on Microsoft Q&A
Hello I am looking to set number format on a Pivot Table field. I dont see any api for this in https://docs.microsoft.com/en-us/javascript/api/excel/excel.pivotfield?view=excel-js-1.14

Could you please let me know if this is supported and if so how i can set this?

Thanks

**Comment by JinghuiMS** [comment]
Thanks for reporting this issue.
Confirmed with Api owner, there's no setNumberFormat API on PivotTable. Could you try to use `range.numberFormat` to unblock yourself?  Please refer to https://docs.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#excel-excel-range-numberformat-member
