### ISSUE TITLE
Outlook Office Js addin randomly missing from the ribbon

### ISSUE THREAD

**Issue by ArjunSureshKumar92** [OfficeDev/office-js#2739]
In outlook desktop, we have recently noticed our addin (looks like all addins) are not loading in the ribbon section. This is not permanent. When we open the profile again, sometimes its there and we cannot find any pattern to this behavior.

Adding screenshots of the same.

From the image, you can see the addin taskpane opens with our addin "Emailgistics". However, the addin does not show up in the ribbon.

Previously, when we opened the profile, the addin was present in the ribbon, we clicked on it to open the task pane, and also pinned the addin. We think this is why the addin task pane opened up as soon as we selected an email.

The issue seems to be isolated with the ribbon. Any help will be much appreciated.

Also adding the outlook desktop version.

![image](https://user-images.githubusercontent.com/35875176/181770317-077674fa-6a29-4ddb-b031-574822a7003b.png)

![1](https://user-images.githubusercontent.com/35875176/181769962-ca961e13-2f78-49d0-8381-d736f82e8d45.png)

**Comment by Adrian-MSFT** [comment]
Hi @ArjunSureshKumar92 

Thank you for bringing this to our attention. We are aware of this and currently investigating it.

**Comment by Adrian-MSFT** [comment]
Hi @ArjunSureshKumar92 

We have seen reports about this and we identified a root cause for this and we rolled out a fix.
You should not see this problem anymore, can you please confirm?

**Comment by ArjunSureshKumar92** [comment]
@Adrian-MSFT 

We are still having the issue. We still haven't found a pattern and it seems random.

**Comment by Adrian-MSFT** [comment]
Hi @ArjunSureshKumar92 ,

What is your current outlook version?

**Comment by ArjunSureshKumar92** [comment]
@Adrian-MSFT 
<img width="734" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/35875176/215106262-d084597e-eed4-42d8-8e26-bebed0a3bd13.png">

**Comment by Adrian-MSFT** [comment]
@ArjunSureshKumar92 Can you confirm the following info:

When this happens -
      1. All add-ins are missing or just the Emailgistics add-in?
      2. What happens if you click the store button?
      3. Is your manifest still in the %localappdata% WEF folder?
      4. Are there any changes to the Emailgistics manifest before this happens?

If you have a video or more screenshots of anything else that may help, they can be added as well.

**Comment by ArjunSureshKumar92** [comment]
> When this happens - 1. All add-ins are missing or just the Emailgistics add-in? 2. What happens if you click the store button? 3. Is your manifest still in the %localappdata% WEF folder? 4. Are there any changes to the Emailgistics manifest before this happens?
> 
> If you have a video or more screenshots of anything else that may help, they can be added as well.

We will have to wait till the issue happens again before we can answer 1,2 and 3.
For the 4th case: No there is no change made to the manifest

**Comment by exextoc** [comment]
Closing this due to no response. If issue persists, please provide information requested
