### ISSUE TITLE
Saving custom properties and setting category with REST API results in conflicting e-mails

### ISSUE THREAD

**Issue by fkranenburg** [OfficeDev/office-js#274]
E-mails are internally changed with new versions when two seperate API's are used inside a single action in the add-in

## Expected Behavior
When using `Office.context.mailbox.item.loadCustomPropertiesAsync` and `saveAsync` along with the [Outlook REST API](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/mail-rest-operations) to set a category in the e-mail should never create a new version of the current e-mail (like a conflict or something)

## Current Behavior
We are using code to set custom properties and we use the REST API to add a category to an e-mail message. But since a short period we receive nummerous issues that the processed e-mails no longer contain the labels and have been 'changed' by the system, so there are multiple versions of the e-mail.
We found out this only happens on Outlook 2016 Desktop clients (with Exchange 2016 and Office 365 as backend server). On the web this works fine accross multiple browsers.

## Steps to Reproduce, or Live Example
I posted a question on stackoverflow that contains a reproducable example add-in that will make the current e-mail corrupt: [question on StackOverflow](https://stackoverflow.com/questions/52870810/adding-a-category-and-updating-custom-properties-results-in-a-complely-broken-e)

## Context
We use this in our CRM system and since like a month ago tickets from our clients where filled in that this was happening. There was no code change at our side. At first we couldn't reproduce but now we can, so it probably could lie in an update in Exchange 2016 server or something.

## Your Environment
* Platform : PC Desktop
* Host : Outlook 2016 desktop client (Office 365 and some local Exchange 2016 servers)
* Office version number: 2016
* Operating System: Windows

## Useful logs
We do not have any logs. After the code is finished we see the following message (in Dutch) in the e-mail:

![image](https://user-images.githubusercontent.com/5680394/47152850-25969b80-d2de-11e8-9003-b030db4236aa.png)

**Comment by dmahugh** [comment]
@exextoc can you take a look at this?

**Comment by exextoc** [comment]
The issue you are observing may be related to inconsistent item state. Changes to an item via EWS/ REST (MakeEwsRequestAsync, or via a backend call), are updated directly in the exchange server. Changes made to an item using the Office.js API go to the client first and these changes, when using Outlook Desktop in Cached Mode, this means that are not synced to the exchange server immediately. Instead the server copy of the item gets updated when Outlook Desktop sync's with exchange. So an  item can get in an inconsistent state if it is updated using office.js and REST/ EWS before Outlook client gets a chance to sync its state. And when the sync happens, sometimes, exchange resolves the conflict by overwriting the client copy so the client items changes can be lost. 
 
To avoid this problem, it is recommended that all changes to the same item be made either via REST/EWS or through the Office.Js API's. Mixing the two can result in conflicts. If this is not possible, then we have seen partners following the pattern of not making the changes via REST/EWS until they have detected the change that was made from the client. 
 
One approach to solve this would be

1.     Make the call CustomProperties, but also include a "timestamp" or GUID as part of the change.
2.     Send the call to a backend to make the EWS/Rest Call, along with the timestamp/GUID
3.     On the backend do not make changes to the item until that timestamp/GUID is there. 
 
We understand this is not ideal and we are trying to move as many server side API's to the Office.JS API suite as possible. Please help us understand your scenario, of what you are trying to accomplish via REST or EWS. We also encourage you to request this feature at our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins).

**Comment by fkranenburg** [comment]
Our scenario is as follows: We created a Outlook add-in so our users can archive a existing e-mail inside our CRM application. After this is done we needed a way to let the user 'know' the mail is already archived. We did this by adding a category to the e-mail. For as far as we know adding a category is currently only possible to use the Office 365 REST api.

Then our users needed to know at what location the e-mail is already archived in our application. For this we save some meta data in the e-mail itself. This meta data contains some info for the CRM application so we can find the previous mail instantly. For as far as we know this is only possible using the Office.js functionalitly (using Office.context.mailbox.item.loadCustomPropertiesAsync, updating and saving)

So after setting a category on the processed e-mail, we add the needed meta data on the e-mail is needed to make it all work.

For now, to workaround this problem (which was not happing a few weeks ago...!), we do not save the meta data in the e-mail anymore. Instead we save it in the browser storage. And this is far from ideal, but working. The given workaround would work if we had some kind of check if the category we added in the first call was indeed added and synched to the client. But unfortunatly I did not find a way to read out the data with only the Office.js functions.

We do not change the e-mail in the EWS backend, we only use the Office 365 API and the Office.js functionality combined.

Could you please explain why these problems did not happen before, did the Office 365 REST api not directly change the underlying e-mail before or where 'conflicting versions' merged in some way on the server before?

**Comment by exextoc** [comment]
This behavior has existed for some time now. It's possible that you're hitting this case now if Cached Mode was recently turned on for Outlook.
