### ISSUE TITLE
Inconsistent behaviour of xmlPart.getNodesAsync xpath on different platforms

### ISSUE THREAD

**Issue by richie5um** [OfficeDev/office-js#2741]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

My xPath may be wrong, but I've noticed inconsistent behaviour of getNodesAsync.

Works on MacWord, but not on OnlineWord (returns empty array of nodes):
* `xmlPart.getNodesAsync("*/*", async (result) => {`

Works on OnlineWord, but not on MacWord (returns empty array of nodes):
* `xmlPart.getNodesAsync("*", async (result) => {`

Works on both:
* `xmlPart.getNodesAsync("//*", async (result) => {`

As most of the OfficeJS examples use `"*/*"`, then you should probably fix this.

```
async function getCustomJsonById(id) {
  if (typeof Word === "undefined") {
    return Promise.reject();
  }

  return Word.run(async (ctx) => {
    id = `{${id}}`;

    const promise = new Promise((resolve, reject) => {
      Office.context.document.customXmlParts.getByIdAsync(id, async function(result) {
        if (result.status !== "succeeded" || result.value === undefined) {
          return reject(result);
        }

        const xmlPart = result.value;

        xmlPart.getNodesAsync("//*", async (result) => {
          if (result.status !== "succeeded") {
            return reject(result);
          }

          console.log(result);
          return resolve(result);        
        });
      });
    });

    return promise;
  }).catch((err) => {
    console.log("OfficeService-Error: " + JSON.stringify(err));
  });
}
```

**Comment by yatibawri1** [comment]
https://github.com/OfficeDev/office-js/labels/Area%3A%20Word

**Comment by JinghuiMS** [comment]
Thanks for reporting this issue. We can repro it locally, and it has been put on our backlog<Bug#6387343> for internal track. We will keep track of this issue and let you know if there are any updates.
