### ISSUE TITLE
Updates to properties of content controls get lost

### ISSUE THREAD

**Issue by dhoelzl** [OfficeDev/office-js#2742]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
Updates to properties of a content control get unexpectedly lost when closing a saved document.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: https://office.com / Tested on 1st of August 2022
* Operating System: Windows (Version 21H2, Build 19044.1826)
* Browser (if using Office on the web): Google Chrome 103.0.5060.134 (Official Build) (64-Bit)
 
## Expected behavior
Updates to properties of a content control should reliably be persisted with the document.

## Current behavior
Updates to properties of a content control get unexpectedly lost when closing and re-opening a saved document.

## Steps to reproduce
1. ) Create a new blank Word document on https://office.com by using Google Chrome or Mirosoft Edge (current version)
2. ) In the context of an Add-In execute the following in the browser console:

```JavaScript
Word.run(async (context) => {
  const selectionRange = context.document.getSelection();
  selectionRange.clear();
  const cc = selectionRange.insertContentControl();
  cc.tag = "TESTTAG";
  cc.title = "TESTTITLE";
  await context.sync();
  console.log("CONTENT CONTROL ID: " + cc.id);
});
```

This script outputs the ID of a newly created content control. Remember that ID for later use.

3. ) Enter some text into the document to ensure the changes were saved.
4. ) Wait until all changes are automatically saved and close the document.
5. ) Re-Open the document and verify via the text that all changes were saved.
6. ) In the context of an Add-In execute the following in the browser console (**replace Content-Control-ID with the ID from the first script**):

```JavaScript
Word.run(async (context) => {
  const cc = context.document.contentControls.getByIdOrNullObject(Content-Control-ID);
  cc.load("title,tag");
  await context.sync();
  console.log("CONTENT CONTROL BEFORE: TAG: " + cc.tag + ", TITLE: " + cc.title);
  cc.tag += ", CHANGED";
  cc.title += ", CHANGED";
  await context.sync();
  console.log("CONTENT CONTROL AFTER: TAG: " + cc.tag + ", TITLE: " + cc.title);
});
```

This should extend the tag and title of the content script with ", CHANGED". The output should be

CONTENT CONTROL BEFORE: TAG: TESTTAG, TITLE: TESTTITLE
CONTENT CONTROL AFTER: TAG: TESTTAG, CHANGED, TITLE: TESTTITLE, CHANGED

7.) Add some additional text to the document to ensure the changes were saved
8.) Wait for all changes to be saved, close the document, re-open it and verify your manual text that saving was successful
9.) Re-Execute step 6.) 7.) and 8.) The output should be

CONTENT CONTROL BEFORE: TAG: TESTTAG, CHANGED, TITLE: TESTTITLE, CHANGED
CONTENT CONTROL AFTER: TAG: TESTTAG, CHANGED, CHANGED, TITLE: TESTTITLE, CHANGED, CHANGED

10.) Re-Execute step 6.) 7.) and 8.) The output should be

CONTENT CONTROL BEFORE: TAG: TESTTAG, CHANGED, CHANGED, TITLE: TESTTITLE, CHANGED, CHANGED
CONTENT CONTROL AFTER: TAG: TESTTAG, CHANGED, CHANGED, CHANGED, TITLE: TESTTITLE, CHANGED, CHANGED, CHANGED

but unfortunately it is (missing the last changes):

CONTENT CONTROL BEFORE: TAG: TESTTAG, CHANGED, TITLE: TESTTITLE, CHANGED
CONTENT CONTROL AFTER: TAG: TESTTAG, CHANGED, CHANGED, TITLE: TESTTITLE, CHANGED, CHANGED

Clicking into the content control to see it's title reflects the missing changes.

11.) Repeat 6.) 7.) and 8.) arbitrary times, the tag/title will mostly revert to a previous state.
12.) In some cases the additional changes are already lost on step 9.)

Side-Node: The length-limit for the title that Word will display is 64 UTF16-units. This reproduction should never hit that limit, apart from that the tag and storing the title itself are not affected by that limit. The problem occurs far before hitting that limit anyway.

# Provide additional details
The Problem does not occur on Word for the Mac.
I have also seen that changes to the tag or title of a content control (and maybe other properties) are unexpectedly rejected even without closing and re-opening the document e.g. after running insertFileFromBase64 on a content control. I need to investigate further to create a reproduction scenario for that.

## Context
Our solution which builds mainly on the usage of content controls does not work reliable in Office for the web, currently we can only use it in Office for the Mac. I have not tested it on Office for Windows. I do not know any workaround for that issue.

## Useful logs
There are no specific error logs for that issue.

**Comment by JinghuiMS** [comment]
Thanks for reporting this issue. It has been put on our backlog<Bug#5627879> for internal track. We will keep track of this issue and let you know if there are any updates.
