### ISSUE TITLE
Support for Keyboard shortcuts in custom contextual tab.

### ISSUE THREAD

**Issue by nvazhayil** [OfficeDev/office-js#2743]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Currently, when we press ALT on the keyboard and move to the custom context tab, we see that the buttons within the context tab are assigned shortcuts numbered from 1 to 9. 

It would be helpful if user defined keyboard shortcuts can be assigned to each button. 

I would suggest having a key in the JSON structure passed to Office.ribbon.requestCreateControls API. 
Currently, each control has the following attributes, **type, id, actionId, enabled, label, superTip and icon**. we can add another attribute for each control which defines the shortcut key.

**Comment by davidchesnut** [comment]
Looks like a request so moving to office-js repo.

**Comment by JinghuiMS** [comment]
@madhavagrawal17  
Could you give your insights on this issue? it should be related to shared runtime. Thanks!
