### ISSUE TITLE
Redistribute VBA 7.1 ? 

### ISSUE THREAD

**Issue by xauat001** [OfficeDev/office-js#2745]
Hello everyone, I have the same problem as in the following link:

https://github.com/OfficeDev/office-js/issues/2566

Is there anyone could help me to get the latest VBA SDK?

**Comment by yatibawri1** [comment]
Based on the link that you shared, may I know if you tried contacting the contact mentioned in the thread? 

For the VBA SDK, you could connect Yaqi by [Yaqi.Yang@microsoft.com](mailto:Yaqi.Yang@microsoft.com) directly, he would send you the updated SDK. Thank you!

**Comment by xauat001** [comment]
> Based on the link that you shared, may I know if you tried contacting the contact mentioned in the thread?
> 
> For the VBA SDK, you could connect Yaqi by [Yaqi.Yang@microsoft.com](mailto:Yaqi.Yang@microsoft.com) directly, he would send you the updated SDK. Thank you!

It's been a few months since the linked issue was posted so I'm not sure if I should contact Yaqi, I have sent the email to Yaqi yesterday but I haven't receive reply yet, I'll continue to wait a few days, thank you.

**Comment by xauat001** [comment]
@yaqiyang hi Yaqi, could you send the VBA SDK 7.1 for me please?

**Comment by yaqiyang** [comment]
We only provide updated VBA SDK packages to our existing licensees. If you are a licensee, please e-mail me at yaqi.yang@microsoft.com directly from your work e-mail and give me the name of your company that has signed our VBA license agreement. Once it is verified, I will give access to your work e-mail address.

**Comment by xauat001** [comment]
> We only provide updated VBA SDK packages to our existing licensees. If you are a licensee, please e-mail me at [yaqi.yang@microsoft.com](mailto:yaqi.yang@microsoft.com) directly from your work e-mail and give me the name of your company that has signed our VBA license agreement. Once it is verified, I will give access to your work e-mail address.

Thank you Yaqi, I'll contact you with work email ASAP.

**Comment by xauat001** [comment]
@yaqiyang hi Yaqi, I have sent the mail to you, but I tried to send email to outlook email address using work email, the email have been treated as spam, I'm afraid that you didn't see the mail, so could you check your junk mail folder if you have not seen the mail please?
