### ISSUE TITLE
How can I call the `Notification` APIs methods in an outlook add-in?

### ISSUE THREAD

**Issue by p6l-richard** [OfficeDev/office-js#2747]
## Problem
I've tried using the `Notification.requestPermission()` API method in my outlook  add-in, but the method call doesn't trigger the usual notification dialog.

Is the [Notification API](https://developer.mozilla.org/en-US/docs/Web/API/notification) not supported in outlook's in-app browsers?

I've tried on macOS & the web app in Chrome. I would've definitely expected the latter to work.

## Context
![image](https://user-images.githubusercontent.com/18185649/182655478-61f562d4-7d35-485c-9260-9e3308ca6126.png)

**Comment by exextoc** [comment]
@p6l-richard webview2 doesn't support push notification as far as I know.

**Comment by exextoc** [comment]
An add-in is just a webpage embedded in Outlook, so you may be able to send data to it through websockets or long polling outside of a standard request. However, this is not a supported use case scenario.
