### ISSUE TITLE
What's the recommended way to send push notifications to an outlook add-in from a web server?

### ISSUE THREAD

**Issue by p6l-richard** [OfficeDev/office-js#2748]
## Problem

I can't seem to find a reference a suggested way to implement sending notifications from a web server to an outlook add-in.

I've looked on:
- the officeJS docs, which have a deprecated entry about notifications [rest api v2.0](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/notify-rest-operations), pointing to the [Microsoft Graph](https://docs.microsoft.com/en-us/graph/notifications-concept-overview), which again is deprecated (but without pointing to any up to date version)
- stackoverflow, but the questions were either [unanswered](https://stackoverflow.com/questions/50276462/can-an-outlook-js-add-in-receive-push-notifications-from-an-external-server-usin), or, [answering the question](https://stackoverflow.com/questions/41435061/outlook-365-keeping-specific-events-in-sync-with-external-system?rq=1) with the deprecated notifications api
- the officejs Q&A forum, where someone [pointed out](https://docs.microsoft.com/en-us/answers/questions/266097/push-notification-practices.html) the Azure Notifications Hub service, but only linked to an android example; but the [docs state that it's primarily made to send messages to mobile devices](https://docs.microsoft.com/en-us/azure/notification-hubs/) officejs add-ins as a tutorial or reference

Could you help me understand what's the best way to implement push notifications from web server -> outlook add-in?

## Context
- I personally would like to use Firebase Cloud Messaging, which depends on the [Push API](https://www.w3.org/TR/push-api/) under the hood. Is the Push API supported?
- WebSockets could also work, but here again I wasn't able to find something before working away on an implementation

**Comment by exextoc** [comment]
An add-in is just a webpage embedded in Outlook, so you may be able to send data to it through websockets or long polling outside of a standard request. However, this is not a currently supported use case scenario.
