### ISSUE TITLE
Troubleshoot Dialog Rendering

### ISSUE THREAD

**Issue by nrakochy** [OfficeDev/office-js#275]
## Expected Behavior
View developer console on the Dialog window. If this is not possible, how do I troubleshoot why a view would render correctly in the TaskPane but not in the Dialog?

## Current Behavior
I am working on an add-in that is failing to load scripts via the Dialog API.

The template from the HTML renders correctly in the Dialog. If I render the template in the main TaskPane, both the HTML and the scripts execute correctly.

I can see the console logs in the TaskPane (from the correctly rendered template), but the Dialog seems to be a bit of a black box. There's no logs, network, or DOM info that I can see. Is there a way to enable the Safari console for the Dialog?

Here is a [SO question](https://stackoverflow.com/questions/52878500/how-does-one-enable-the-developer-console-in-outlook-add-in-for-the-dialog-api) that reports this issue.

## Context
This is a blocker that is preventing me from further development at work.

## Your Environment

* Platform: Mac
* Host: Outlook 
* Office version number: Outlook 16.18
* Operating System: macOS 10.13.6 (High Sierra)

**Comment by nrakochy** [comment]
Adding gif of Dev Tool inspector inside the Dialog (gif only gets 10fps, but flashes much faster in real-time). I have no iFrame logic, so this is simply `Office.context.ui.displayDialogAsync`: 


![dialog_frame_inspect_10fps](https://user-images.githubusercontent.com/3740177/47303891-c80a9380-d5ea-11e8-8774-c0059b45b4a3.gif)

**Comment by danielgwilson** [comment]
Hi @nrakochy, sorry for the delay in response - this has actually come up previously  (#290), and the core cause of the issue is being investigated.

As a workaround, could you try the following?
1. Resize the dialog such that it's a very small window.
2. Choose "Inspect Element" which opens in a new window.
3. Resize the dialog to its original size.
4. Use the inspector as required.

**Comment by nrakochy** [comment]
Thanks for the note. I was pulled on to another project and have not had a chance to revisit. Will test this shortly.
