### ISSUE TITLE
makeEwsRequestAsync fails in OWA (WasProxySuccessfull: false)

### ISSUE THREAD

**Issue by milankonir** [OfficeDev/office-js#2750]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 20220721048.03 (collected from diagnostics API)
* Operating System: Windows 10
* Browser (if using Office on the web): Microsoft Edge 102.0.1245.62
 
## Expected behavior

The `makeEwsRequestAsync` request should succeed.

## Current behavior

The `makeEwsRequestAsync` request fails with "The remote server returned an error: (403) Forbidden."

## Steps to reproduce

1. Perform any request via `makeEwsRequestAsync`

## Link to live example(s)

# Provide additional details

So far, this is only affecting one of our customers. The `makeEwsRequestAsync` works for them in Windows desktop client, the problem only happens in OWA.

The `makeEwsRequestAsync` requirements are met:
- Add-in has ReadWrite permission
- OAuthAuthentication is enabled

When inspecting network logs, we can see auth token being added to the EWS proxy request, yet it fails with 403 anyway.

![image](https://user-images.githubusercontent.com/72383088/182847372-93e8a154-c4bc-4326-b001-4595a3197022.png)

![image](https://user-images.githubusercontent.com/72383088/182848157-d0b060d9-e7fd-4827-bc74-9af412b20072.png)

This fails for any payload, an example payload:

```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
  xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
  xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">
  <soap:Header>
    <t:RequestServerVersion Version="Exchange2013"/>
  </soap:Header>
  <soap:Body>
    <GetItem
      xmlns="http://schemas.microsoft.com/exchange/services/2006/messages"
      xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
      <ItemShape>
        <t:BaseShape>IdOnly</t:BaseShape>
        <t:AdditionalProperties>
      <t:FieldURI FieldURI="item:Body" /><t:FieldURI FieldURI="item:Attachments" />
      </t:AdditionalProperties>
      </ItemShape>
      <ItemIds>
        <t:ItemId Id="AAMkAGFhOGE1YTY0LTJhZDctNDQ3MS04NjJkLTg0YjBlZTYyZTgzOQBGAAAAAAAICmkmn4mMT4fNXXkyjY6uBwAOlPM053FpTaoydUTsee+IAAAAysHUAABoku2X53N4R7qnTgcWHcdsAAOcc5y/AAA="/>
      </ItemIds>
    </GetItem>
  </soap:Body>
</soap:Envelope>
```

## Context

We realize, that this is likely an environmental problem / Exchange setup problem, but the error message does not tell us much. It's also perplexing that it works in desktop client, but not in OWA.

Could you please advise on what might be wrong?

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
We are not able to reproduce this at our end .We need some more details to debug it further.
1)Is it constant repro for the customer where it is failing?
2)From when it started failing ??
3)Can you please share a repro video of the issue ??

**Comment by milankonir** [comment]
1. It's a constant repro, the `makeEwsRequestAsync` fails 100%
2. It has never worked for them
3. What would you like to see in the video (e.g. the OWA network log)?

**Comment by exextoc** [comment]
@milankonir: Yes, could you please share a video showing the repro steps and the network log.

**Comment by milankonir** [comment]
@exextoc The full network log contains PII / tokens which is not something that is possible to post into a public issue tracker.  I can anonymise failing `ExecuteEwsProxy` request, are there any request information (e.g. cookies / ids) that would be important to share?

**Comment by exextoc** [comment]
@milankonir Please share the repro video.

**Comment by milankonir** [comment]
@exextoc We have got back in touch with the customer and they claim that they cannot consistently reproduce anymore. We can keep this closed and we will get back in touch if anything changes.

Thank you for the support.
