### ISSUE TITLE
[Outlook Onsend addin] Office.context.mailbox.item.location.getAsync() is not providing entered location when Appointment or meeting composed through OWA

### ISSUE THREAD

**Issue by Premsagar-lab** [OfficeDev/office-js#2751]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
Meeting location is retrieved through office js api Office.context.mailbox.item.body.getAsync(). 
It works perfectly for stored location but when user enters any location which is not saved previously then this api returns blank or empty location. It works perfectly on MS Outlook for mac. Issue is only seen in OWA.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __Office on the Web____
* Host [Excel, Word, PowerPoint, etc.]: __Outlook____
* Office version number: __16.61____
* Operating System: ___MacOS___
* Browser (if using Office on the web): __Safari, Chrome____
 
## Expected behavior

Location should be returned by the api.

## Current behavior

Blank or empty location is returned.

## Steps to reproduce

1. Open OWA in safari. Login to mailbox and compose a meeting.
2. Enter any text for location field 
3. Click on send.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

Ours is a DLP application which monitors text being sent out of Organisation. since, we dont receive proper location, we are not able to detect it and protect user data.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
We are not able to repro this issue can you please share a repro video for further debugging?

**Comment by Premsagar-lab** [comment]
@exextoc: Please check this video:
https://user-images.githubusercontent.com/67500503/183603459-5ca0d9ec-277f-4ace-9dab-0c7ed322220a.mov

**Comment by exextoc** [comment]
Hey @Premsagar-lab , we are able to reproduce this issue, and are working on it. This issue occurs when the location is left unresolved- it should not happen when the location is resolved correctly. Nonetheless, we are working on fixing it. However, there are no timelines we can share at this point.
