### ISSUE TITLE
Calls to Office.context.mailbox.addHandlerAsync() resulting in OSF.DDA.Error code=5000 'The operation is not supported'

### ISSUE THREAD

**Issue by carlosb1504** [OfficeDev/office-js#2757]
Calls to Office.context.mailbox.addHandlerAsync() in order to register an event handler resulting in OSF.DDA.Error code=5000 'The operation is not supported' on Outlook for Windows only. OWA and Mac Outlook seem to be unaffected.

We are currently using this to subscribe to the `Office.EventType.ItemChanged` event.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ![image](https://user-images.githubusercontent.com/47693383/183632725-22601fd1-5724-4a29-b543-ccca79b1a54c.png)
* Operating System: Win10
* Browser (if using Office on the web): ______
 
## Expected behavior
mailbox event handler should be registered without error

## Current behavior
message below is observed in the console
![image](https://user-images.githubusercontent.com/47693383/183632853-6bd6b583-e474-478c-9e18-a1b028acab02.png)

## Steps to reproduce
Load an add-in which subscribes to the mailbox event described.
Observe the error when this is attempted.

## Context

Currently rendering our taskpane completely broken for Windows users on affected Outlook versions.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by teejay001** [comment]
Hi,

Facing the same issue this morning even after upgrading to the latest version.

![image](https://user-images.githubusercontent.com/99417649/183634262-0c0310ee-cc3e-4b0d-92f7-e8f86495e50e.png)

**Comment by JuaneloJuanelo** [comment]
@carlosb1504   we might think we have a repro here...can you please confirm in what context does this happen?  is this happening when subscribing to the event when you pop a compose or a read item? (this should not happen on the explorer view)

**Comment by JuaneloJuanelo** [comment]
we verified offline that this is due to a recent "bug fix" we shipped and are in the process of rolling back. this will be fixed in a few days. for now you can safely remove that check from your add-in to solve the problem immediately.
