### ISSUE TITLE
Word Online can't open new document from base64 string

### ISSUE THREAD

**Issue by jentayo1994** [OfficeDev/office-js#276]
## Current Behavior
When trying to open new document from base64 string, Sharepoint return 405 status code and information about missing  'Access-Control-Allow-Origin' header in request.
Note: It worked fine few days ago.

## Steps to Reproduce, or Live Example
Run next snippet with base64 encoded document:
```javascript
Word.run(function (context) {
   return context.sync().then(function () {
      var wordDocument = context.application.createDocument(base64EncodedDocument);
      if (wordDocument) {
         wordDocument.open();
      }
   }).then(context.sync);
});
```
## Context
Our add-in need open document template generated on back-end.

## Your Environment
* Platform: Office Online
* Host: Word
* Browser: All browsers

## Useful logs
![image](https://user-images.githubusercontent.com/17315327/47222577-c9a44380-d3bf-11e8-9580-2838291e695d.png)

**Comment by andschleicher** [comment]
I've been observing this same issue with my Office js project as well. This functionality was working on the 17th but I got the above error on the 18th without a code deployment between the two days.

**Comment by dgrudenic** [comment]
Experiencing same thing it stopped working in office online.

**Comment by XuanZhouMSFT** [comment]
Thanks for your reporting. We are in the process of investigating and fixing. Tracking internally with 88864157

**Comment by XuanZhouMSFT** [comment]
The issue has been fixed. You can try it now.

**Comment by jentayo1994** [comment]
Thanks. Now it works fine.
