### ISSUE TITLE
Word Add-Ins API: Search base on the page number

### ISSUE THREAD

**Issue by meisammofidi** [OfficeDev/office-js#2761]
## Microsoft 365 Developer Platform Ideas Forum

We are developing a Word add-Ins, in which we are searching words in document. 

Possibility:
Search either the entire document or selected context by below codes
`const searchResults = context.document.body.search('my word', { matchCase: false, matchWholeWord: true });
`
`const searchResults = context.document.getSelection().search('my word', { matchCase: false, matchWholeWord: true });`

Impossibility (New Idea):
Any way to search based on the word page numbers. For instance, search 'my Word' at page 1 to 10 rather than the entire document or forcing user to select required text or paragraphs by dragging mouse.

Please let me know how I can do it if that option already exists. Because I couldn't find any reference or document as solution

**Comment by jipyua** [comment]
Currently, search by pages is not supported. but you can try to just search inside some scoped object, such as search inside table for section.
