### ISSUE TITLE
displayDialogAsync with displayInIframe: true fails with escaped line breaks in query string of dialog URL

### ISSUE THREAD

**Issue by groh-f** [OfficeDev/office-js#2762]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: any
* Operating System: any
* Browser (if using Office on the web): reproduced with Chrome, assumed: any

## Expected behavior
Dialog should be shown without issues

## Current behavior
Excel dialog API throws with internal error 5001.

## Steps to reproduce
See attachment displayDialogAsyncRegression.yaml

## Link to live example(s)
See attachment displayDialogAsyncRegression.yaml
[displayDialogAsyncRegression.zip](https://github.com/OfficeDev/office-js/files/9302611/displayDialogAsyncRegression.zip)

# Provide additional details
displayDialogAsyncRegression.yaml should be self explanatory

## Context
The issue blocks us from sending texts with line breaks via URL query string to a dialog URL. This worked before and is thus a regression.

## Useful logs

No Logs. We started to observe this issue as of July 28th. Maybe this helps you to find the change that brought in this regression. The issue only occurs in Excel on the Web. All works well in Excel PC desktop.

**Comment by JinghuiMS** [comment]
Thanks for raising question!
@Rick-Kirkham could you help involve current dialogAPI area expert into this thread? Thanks in advance!

**Comment by groh-f** [comment]
Hallo @JinghuiMS ,
Is there any update on this issue?

**Comment by Rick-Kirkham** [comment]
@massonj Who is the current engineer for the dialog APIs?

**Comment by groh-f** [comment]
Hello everybody,

any updates? It's been almost 2 months

Best regards

**Comment by iotataru** [comment]
I believe this got fixed a while ago

**Comment by groh-f** [comment]
Yes seems like it 
Thanks I going to close the issue now
