### ISSUE TITLE
Word Add-Ins API: Display the desired word on right click menu dynamically like spell & grammar check at MS Word

### ISSUE THREAD

**Issue by meisammofidi** [OfficeDev/office-js#2763]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Microsoft 365 Developer Platform Ideas Forum

I am developing a task pane Word Add-Ins which finds the desired words in word document. What I am trying to do is to give an ability to user by right clicking on the given word be able to see the word on menu as you can see in picture below. All other items in sub menu will fetch from API dynamically to be replace by selected word ( Same as what we have it in spell check in Word). I am almost sure that it is impossible through the Web Add-ins unless you give me some references. I am Just wondering how I can implement it. Please help and give me some references.

![rightClickMenu](https://user-images.githubusercontent.com/44708695/184001653-eeb1933e-8bcd-4b25-96b7-5acb97b480d4.JPG)

**Comment by JinghuiMS** [comment]
@preethikakiru  Do you have any insights on it? Thanks!

**Comment by meisammofidi** [comment]
> Do you have any insights on it? Thanks!

@preethikakiru Any idea please?
