### ISSUE TITLE
Office.context.mailbox.item.recurrence.getAsync always returns null in web clients

### ISSUE THREAD

**Issue by Artsiom-L** [OfficeDev/office-js#2764]
## Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 
* - osfweb version: 16.0.15201.10000 
* - office-js-api version: 20220404.2
* Operating System: Win 10 (21H1 OS Build 19043.1826)
* Browser (if using Office on the web): Chrome (v 104.0.5112.81 64-bit), Edge (v 104.0.1293.47 64-bit), Firefox (v 103.0.2 64-bit)
 
## Expected behavior
When using the Office.context.mailbox.item.recurrence.getAsync I expected to get the recurrence of the event

## Current behavior
The returning value of the recurrence pattern is null

## Steps to reproduce

1. Create an appointment with recurring pattern (E.g. Occurs every Monday and Wednesday until some date) and save it
2. Open any occurrence in edit series mode (Edit -> All events in the series)
3. Run provided script to obtain the recurrence pattern

## Link to live example(s)

https://gist.github.com/ArtsiomLysianok/65dd3d89546bedfc5e2b72e3c21010c5

## Useful logs

![image](https://user-images.githubusercontent.com/24548451/184115235-edd9ed30-658f-4cc4-ad1c-f620039c5135.png)

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding the recurrence API. It has been put on our backlog. We unfortunately have no timelines to share at this point

 
Internal tracking id: Office: 167618

**Comment by pivotgroup** [comment]
This still appears to be causing issues.

When first opening the add-in pane, **Office.context.mailbox.item.recurrence.getAsync** returns null for a variety of the recurrence rules. I haven't figured out the pattern, however it appears it is NOT null if its a simply weekly recurrence and for basically every custom pattern I tried, the result of that call is null, which makes it impossible for me to determine if I'm dealing with a series task or not.

If, once I have the event open, I update the recurrence properties for the event, **Office.context.mailbox.item.recurrence.getAsync** then returns the proper response.

![Screen Shot 2022-09-15 at 4 54 56 PM](https://user-images.githubusercontent.com/8634047/190515711-3f49fb42-d38a-41a6-980f-15f5447e2e81.jpg)
