### ISSUE TITLE
[Outlook] Allow setting bodyType to HTML

### ISSUE THREAD

**Issue by claell** [OfficeDev/office-js#2767]
I'll create a mirror issue for https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/allow-setting-bodytype-to-html-in-outlook-from-add-in/idi-p/3596975 here, as that forum seems to be pretty much dead right now (almost no reaction, no tasks being worked on).

Coming from https://stackoverflow.com/questions/68318423/how-to-change-coercion-type-of-email-body-to-html-from-text-using-outlook-add-in. There, it is linked to this community, to request the feature.

I want to add functionality to my Add-in for changing the bodyType to HTML. Unfortunately, that doesn't seem to be supported right now, at least not when the question on stackoverflow was posted.

**Comment by JuaneloJuanelo** [comment]
Effectively changing the body type is not supported on the API. You can identify what the body type the user chose and then insert either plain text or html accordingly.

**Comment by claell** [comment]
@JuaneloJuanelo Exactly. This issue is a request to support setting the body type on the API 😃

**Comment by exextoc** [comment]
@claell, thanks for bringing this up. We don't provide timelines for feature requests, however, we do consider these feature requests during our planning process. Thanks.

**Comment by claell** [comment]
Yes, what feedback is needed from me?

**Comment by exextoc** [comment]
@claell since this is a feature request, we don't provide timelines for them. We will consider this request and all others when we go through our next planning cycle. Thanks.

**Comment by claell** [comment]
@exextoc I didn't ask for a timeline, did I?

Great that you consider this. But why do you close it, then?

**Comment by nmetnikUMT** [comment]
Any update on this?  Setting the message body CoercionType is a must in a project I'm working on.  Being that this is almost 2 years old I'm assuming it's not going to change but I'm hopeful.  Is there an API roadmap available?
