### ISSUE TITLE
[Excel] List validation rule type API broken

### ISSUE THREAD

**Issue by 3dot1four** [OfficeDev/office-js#277]
Original Post: https://github.com/OfficeDev/office-js-docs-pr/issues/492

I am trying below code to have a list data validation and its giving error. I also made sure to have data in 'nameSourceRange' but it did not help. Please respond ASAP.

```
var sheet = context.workbook.worksheets.getActiveWorksheet();
var range = sheet.getRange("B2:C5");  
var nameSourceRange = context.workbook.worksheets.getItem("Sheet1").getRange("A1:A3");

range.dataValidation.rule = {
    list: {
        inCellDropDown: true,
        source: nameSourceRange
    }
};
await context.sync();
```

 
Error
InvalidArgument: The argument is invalid or missing or has an incorrect format.
```
{
    "code": "InvalidArgument",
    "message": "The argument is invalid or missing or has an incorrect format.",
    "errorLocation": "ListDataValidation.source",
    "statement": "dataValidation.rule=...;",
    "surroundingStatements": [
        "...",
        "// Instantiate {range}",
        "var worksheet=worksheets.getItem(...);",
        "var range1=worksheet.getRange(...);",
        "// Instantiate {range1}",
        "var dataValidation=range.dataValidation;",
        "// &gt;&gt;&gt;&gt;&gt;",
        "dataValidation.rule=...;",
        "// &lt;&lt;&lt;&lt;&lt;"
    ],
    "fullStatements": [
        "Please enable config.extendedErrorLogging to see full statements."
    ]
}        

```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e12c8da9-16ef-b641-aa8a-b5dd37b93d63
* Version Independent ID: e8264f34-086a-65be-d91d-3405159c7bcb
* Content: [Add data validation to Excel ranges](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-data-validation#list-validation-rule-type)
* Content Source: [docs/excel/excel-add-ins-data-validation.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-data-validation.md)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by lumine2008** [comment]
Hi @rohitrewa , based on sample code, we are not be able to repro this issue, so Could you please share a gist to us to repro and locate the issue? Thanks.
![image](https://user-images.githubusercontent.com/26398035/76534610-adbda800-64b4-11ea-89d6-be2d202e4c74.png)

**Comment by keyur32** [comment]
@3dot1four - does this still repro for you? If it does, please reactivate with a gist provided.
