### ISSUE TITLE
[Outlook Add-In] Custom providers for Outlook Places Service

### ISSUE THREAD

**Issue by mvelbaum** [OfficeDev/office-js#2771]
Currently, when creating a meeting OWA and mobile Outlook both use the Bing Maps API to query for public locations. I would like to have the ability to use a different 3rd party map API for public locations lookup. Is this already possible?

**Comment by JuaneloJuanelo** [comment]
Hello this is a great idea but unfortunately this is not supported but I suggest you add a new feature request [here ]. Thank you. (https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)
