### ISSUE TITLE
Office Excel JS - Find and replace

### ISSUE THREAD

**Issue by tqdo** [OfficeDev/office-js#2772]
I just wonder whether we can find and replace using Office Excel JS? I have read through the [doc](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/) but it does not mention about this functionality.

**Comment by JinghuiMS** [comment]
@tqdo 
Thanks for reaching us.
For find, you can use range.find API, please refer to https://docs.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#excel-excel-range-find-member(1) 
For replace, you can use worksheet.replaceall API, please refer to https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheet?view=excel-js-preview#excel-excel-worksheet-replaceall-member(1)
