### ISSUE TITLE
Bottom border DOES NOT show for all cells in the web, but DO show correctly in desktop

### ISSUE THREAD

**Issue by majoy** [OfficeDev/office-js#2774]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hello, 

I have attached a xlsx file that has the issue which happens only on Excel Web. As you can see from the attached image, Current Assets which is made up of 2 merged cells starts on row 27 but shows a blank bottom border. However, if you open the file in Excel Desktop the bottom border does show

The reason I've created a bug under this project is because the report on the file was generated with a custom add-on that uses officejs apis. If this is not the correct project to file this bug under I do apologize in advance.

## Environment
* Platform: Web
* Host: Excel
* Office version number: 365
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
The bottom border for Current Assets should show on Excel web, just like it does when you open the file in Excel Desktop 365

## Current behavior
On excel web, Current Assets doesn't show a bottom border

## Steps to reproduce
1. Open the attached xlsx file in Excel Web 
[border-not-showing-in-web.xlsx](https://github.com/OfficeDev/office-js/files/9339215/border-not-showing-in-web.xlsx)

2. Locate row 27 and notice the Current Asset's bottom border is missing as shown in this image
![border-not-showing-on-web](https://user-images.githubusercontent.com/3093032/184699290-f8c6fe60-757f-4d09-9206-2c3ffac89e4b.PNG)

**Comment by honxmsft** [comment]
Can you provide the script to create this file template? Or can you provide a minimal script to repro this situation?

**Comment by majoy** [comment]
Hi @honxmsft,

Here are the repro steps:

1. Open the following xlsx file in Excel Web:
[happy-path-report.xlsx](https://github.com/OfficeDev/office-js/files/9397835/happy-path-report.xlsx)
2. Open Script Labs, click Import, and paste the following url to the yaml file 
https://gist.github.com/majoy/c148eb7d9f6a80183e25e811c715660d#file-missing-border-excel-yaml
3. Click Import to import the yaml file then click the Run button to load the script
4. Click the Run button in the task pane to execute the custom script that inserts blank rows and notice how the bottom border doesn't show up in Excel Web

**Comment by majoy** [comment]
@honxmsft if you have trouble importing the yaml file in Excel web the workaround, once you open the happy-path-report.xlsx file, is to:
1. Open Script Labs,
2. Click the New Snippet button
3. Replace js with the following script
[gist-script](https://gist.github.com/majoy/8681036bbd4788c74bbebfe3da63f3d8)

**Comment by honxmsft** [comment]
@majoy We have created an internal bug 6505755 to track this issue.

For this scenario, you can call border API manually to workaround

```ts
let reportRange = sheet.getRange("A27:A28"); // the range in your example
reportRange.format.borders.getItem(Excel.BorderIndex.edgeBottom).color = '#000000' // set color
```

**Comment by majoy** [comment]
@honxmsft thanks for the replay. if i understand correctly the "workaround" you're proposing would be to force a redraw of the bottom borders for each of these parent "nodes" that can show up when using our addon. without knowing how to identify this issue programmatically, we'd be forced to redraw bottom borders for all parent nodes as the user uses our addon to update the report in real-time. this is unfortunately a nontrivial task for the type of reports we're generating through our addon so we'd like to avoid this extra complexity if possible.
