### ISSUE TITLE
I'm trying to open word document from a file path and insert footer into opened document using Office Add-ins for Word.

### ISSUE THREAD

**Issue by Amulyakr** [OfficeDev/office-js#2778]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Assume I have a word document open with taskpane having button to open document from given destination(local file path) then insert footer into newly opened document.As I'm new to this, I don't how to begin with.

**Comment by GavinGu07** [comment]
Currently the feature: **_open word document from a file path_**, you requested, is not a part of the product. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum]( https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. 

Thanks,
Microsoft 365 Developer Platform team ​
