### ISSUE TITLE
Outlook for Mac - no recipients returned in the compose mode

### ISSUE THREAD

**Issue by dmitry-semenov** [OfficeDev/office-js#278]
## Expected Behavior
`Office.context.mailbox.item.to.getAsync(console.log)` should print array of email recipients

## Current Behavior

`Office.context.mailbox.item.to.getAsync(console.log)` returns empty array as a value in despite of having multiple recipients in the email
```
AsyncResult {value: [], status: "succeeded"}
```
## Steps to Reproduce, or Live Example
  1. Open Outlook for Mac compose window
  2. Type recipients
  3. Open web inspector
  4. `Office.context.mailbox.item.saveAsync(console.log)` //save item just in case
  5. `Office.context.mailbox.item.to.getAsync(console.log)` //try to get recipients 

## Context

The issue is reproducable on my dev machine, we started receiving customer reports with the same issue last week. As we use recipients to preprocess email we're relying on this API a lot.

## Your Environment

* Platform: Mac Desktop
* Host: Outlook
* Office version number: 16.18 (181014)
* Operating System: macOS High Sierra 10.13.6

## Useful logs
![](http://screenshots.client-demo-site.net/scn-20181022-172241-hfwy9.png)

**Comment by macOutlookExtensibility** [comment]
Thanks for raising it. It got fixed and available in InsiderFast build. Should hit production by mid of November.
