### ISSUE TITLE
Hosted Excel Add-In does not run custom functions

### ISSUE THREAD

**Issue by yuanagain** [OfficeDev/office-js#2781]
Custom functions run when hosted locally, but do not run in the add-in when content is built and hosted.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.64
* Operating System: OS X 12.4
 
## Expected behavior

I expected to have the same functionality regardless of host. In particular, formula `=SH.GET("dev444")` should return a number or an error message.

## Current behavior

Using custom formulas implemented in the add-in result in a `#BUSY` error.

## Steps to reproduce

Install the plugin in dev mode:
```
$ office-addin-debugging start manifest.xml desktop
```

## Link to live example(s)

Manifest with hosted content

https://gist.github.com/yuanagain/2a4d68e9c77baac2def6836027a5e1aa

Manifest with content hosted at localhost

https://gist.github.com/yuanagain/2a358f5eafeebaf0b19e4994e0a7f568

# Provide additional details

Deployed content at https://excelsh.web.app/

## Context

I am unable to publish this plugin now

## Useful logs

<img width="1002" alt="Screen Shot 2022-08-18 at 11 55 01 AM" src="https://user-images.githubusercontent.com/6503523/185440016-4808b724-b00d-4378-8687-52aed5ff9795.png">

<img width="216" alt="Screen Shot 2022-08-18 at 11 54 29 AM" src="https://user-images.githubusercontent.com/6503523/185439902-87c38a64-de74-412e-9498-07c7317a7bc9.png">

**Comment by JHJ-MS** [comment]
Hi @yuanagain , here is troubleshooting guidance for dealing with #BUSY error,
[troubleshooting guidance ](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-troubleshooting)

Besides, could you please have a try:
1. Does the hosted Excel Addin-in work if it do not contain Custom Functions?
2. Does any JS API call in your hosted Excel Addin works?

**Comment by yuanagain** [comment]
> troubleshooting guidance

Hi @JHJ-MS, I believe I've used the steps the docs suggest for debugging custom functions running in the shared runtime; I've confirmed that `functions.json`; see below and above. There are simply no logs (from the custom functions).

To answer your questions:

1) The non-custom function features (i.e. the taskpane) work just fine.
2) Yes; the taskpane is able to read the selected range and modify cell values.

<img width="911" alt="Screen Shot 2022-08-22 at 9 25 11 AM" src="https://user-images.githubusercontent.com/6503523/185971308-4fdeb10b-7449-44e3-ab57-e9b31c66a7d7.png">

**Comment by JHJ-MS** [comment]
Hi @yuanagain, from your screenshot, the functions.js has been downloaded successfully but the functions.json hasn't been downloaded. This is strange because both of them should be downloaded.

1. Could you check whether your Shared Runtime config is correct following this [doc](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime)?
2. Could you check whether the basic custom function like add(num1,num2) works? 
3. Could you check whether the below custom function works? If your custom function includes a web request,  does it works if you follow this way to write your function?
```
/**
 * Gets the star count for a given org/user and repo. Try =GETSTARCOUNT("officedev","office-js")
 * @customfunction
 * @return Number of stars.
 */
function getStarCount() {
  //You can change this URL to any web request you want to work with.
  const url = "https://api.github.com/repos/officeDev/office-js";
  const response = await fetch(url);

  //Expect that status code is in 200-299 range
  if (!response.ok) {
    throw new Error(response.statusText);
  }
  const jsonResponse = await response.json();
  return jsonResponse.watchers_count;
}
```

**Comment by yuanagain** [comment]
> Hi @yuanagain, from your screenshot, the functions.js has been downloaded successfully but the functions.json hasn't been downloaded. This is strange because both of them should be downloaded.
> 
> 1. Could you check whether your Shared Runtime config is correct following this [doc](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime)?
> 2. Could you check whether the basic custom function like add(num1,num2) works?
> 3. Could you check whether the below custom function works? If your custom function includes a web request,  does it works if you follow this way to write your function?
> 
> ```
> /**
>  * Gets the star count for a given org/user and repo. Try =GETSTARCOUNT("officedev","office-js")
>  * @customfunction
>  * @return Number of stars.
>  */
> function getStarCount() {
>   //You can change this URL to any web request you want to work with.
>   const url = "https://api.github.com/repos/officeDev/office-js";
>   const response = await fetch(url);
> 
>   //Expect that status code is in 200-299 range
>   if (!response.ok) {
>     throw new Error(response.statusText);
>   }
>   const jsonResponse = await response.json();
>   return jsonResponse.watchers_count;
> }
> ```

Hi @JHJ-MS, thanks for the quick reply:

1. That's indeed the guide I used. I checked again and my `manifest.xml` and webpack config again and they're consistent with what's described in the guide.

2. Basic functions (I have one that generates a random number and doesn't require network access) do not work.

3. the function you provided does not work--see (2).

What is the expected behavior? What is the recommended workflow by which to test whether the deployed and hosted plugin will behave as desired when installed, i.e. what's the equivalent to AppCenter of Testflight?

**Comment by JHJ-MS** [comment]
Hi @yuanagain , since the #BUSY! is shown, it means your Custom Function has been registered and recognized successfully but hit some issues when executed. You can right-click your add-in task pane and click the "Inspect", search your function's name and add a breakpoint on it, to debug whether some errors occurred on the client-side.
