### ISSUE TITLE
A11y focus problems when running plugin in Excel Web

### ISSUE THREAD

**Issue by pvsleeper** [OfficeDev/office-js#2782]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

There appears to be a couple of focus related A11y issues when running a plugin via Excel web.

1. When pressing the ESC key while focus is on any input, the focus jumps to the first input element in the plugin.
2. When using Tab to cycle over all the input elements on the form, a the radio button group is not being honored. Pressing Tab sets focus to all the individual radio button elements, even if they are in the same group. Because they are in the same group, they should act as a single control and you should not be able to focus on the individual options using the TAB key.

**Both these behaviors are only evident in the Web version**. 
When using desktop Excel, the focus behaves correctly. 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: Windows
* Browser (if using Office on the web): Tested in both Chrome and Edge
 
## Expected behavior

- When pressing ESC, focus should not be moved to the first input element
- Tab should not move focus from one radio button to another that are in the same group, it should act as a single control.

## Current behavior
- Focus moves to first element when pressing ESC
- User can set focus to radio buttons in the same group using TAB

## Steps to reproduce
Create a plugin that contains the following HTML:
```
  <form>
        First Line: <input type="text" />
        <br />
        Second Line: <input type="text" />
        <br />
        Third Line: <input type="text" />
        <br />
        <fieldset>
            <legend>Multiple Radio Buttons in single group:</legend>
            <div>
                <input type="radio" id="option1" name="group" value="option1" checked>
                <label for="option1">Option 1</label>
            </div>

            <div>
                <input type="radio" id="option2" name="group" value="option2">
                <label for="option2">Option 2</label>
            </div>

            <div>
                <input type="radio" id="option3" name="group" value="option3">
                <label for="option3">Option 3</label>
            </div>
        </fieldset>
    </form>
```
To replicate issue number 1 : Set focus to the input element on the **Third line** and then press the ESC key. The focus incorrectly moves to the input element on **First Line**

To replicate issue number 2 : Set focus to the input element on the **First line**. Press the Tab key three times to so that the first radio button has focus. Now press TAB again - focus incorrectly moves to the second Radio button. 

(You can look at the expected behavior by opening a page with the same HTML in a browser window by itself - not as a plugin via Excel - and observe the different behavior)

## Context
We have very strict A11y requirements and these issues have been highlighted by our A11y compliance team.

**Comment by JinghuiMS** [comment]
Thanks for reporting this issue. It has been put on our backlog<Bug#6445750> for internal track. We will keep track of this issue and let you know if there are any updates.
