### ISSUE TITLE
Im trying to automatically show taskpane on opening document.I followed https://docs.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document. But its not working as expected. On opening document taskpane is not opening.

### ISSUE THREAD

**Issue by Amulyakr** [OfficeDev/office-js#2783]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.64
* Operating System: Bigsur

 ## Steps

In manifest.xml
Action xsi:type="ShowTaskpane">
            <TaskpaneId>Office.AutoShowTaskpaneWithDocument</TaskpaneId>
            <SourceLocation resid="Taskpane.Url"/>
</Action>

In index.js file added 

Office.initialize = function () {
  Office.context.document.settings.set("Office.AutoShowTaskpaneWithDocument", true);
  Office.context.document.settings.saveAsync();
};

On launching word application and then opening new document will not open taskpane.

**Comment by GavinGu07** [comment]
Thanks @Amulyakr for reaching us.
Task panes can't be automatically opened in new documents. You can launch your add-in to see the task pane and save the document. Then reopen the document, and you may see the auto-open task pane.
