### ISSUE TITLE
Ribbon button images are not loaded

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#2784]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi,

I have an issue with the images that I use for the buttons in the ribbon which are not being loaded.
I tried to return Cache-control: public, but still no way to fix it.
This are the response headers that I return for the images: 
```
accept-ranges: bytes
access-control-allow-origin: *
cache-control: public,max-age=86400
content-length: 1122
content-type: image/png
date: Fri, 19 Aug 2022 09:40:07 GMT
etag: "095e5ccb87d867901:0"
last-modified: Fri, 26 Jun 2022 13:07:30 GMT
server: Microsoft-IIS/10.0
x-powered-by: ASP.NET
```

Do you know what can I do to fix the issue and have the images loaded?
Thanks

**Comment by JinghuiMS** [comment]
Thanks for reaching us. Can I know which App(Word, PPT, Excel) and platform(Desktop, Excel Online, Mac or iOS) you are seeing this error? If you can provide a repro video, that will be helpful for us to better understand your scenario.

**Comment by dpopaext** [comment]
Hi,

It is on powerpoint and it happens on windows server. 
I tried to clear cache. Delete addin cache. Nothing works.
Just open the addin with office-addin-debugging and the problem is there. Howerver, same addin works on windows 10 pro or windows 10 arm beta

**Comment by JinghuiMS** [comment]
Route to the owner team to better handle it.
