### ISSUE TITLE
Inserted shapes not reflected in body of message nor returned as an attachment.

### ISSUE THREAD

**Issue by teejay001** [OfficeDev/office-js#2788]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC, Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2207
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome
 
## Expected behavior

The inserted shapes should be returned within the body of the message item Or as an attachment of the message item.

## Current behavior

The inserted shapes are not returned as an attachment nor within the body of the message

## Steps to reproduce

1. Create a new email on Outlook desktop
2. Insert some shapes with embedder text (Add Text) 
![image](https://user-images.githubusercontent.com/99417649/186193000-bea35bad-b420-4063-8387-e5fbe3d130a9.png)
3. Office.context.mailbox.item.getAttachmentsAsync returns no attachments for the message item
4. Office.context.mailbox.item.body.getAsync does not return the shapes in the message item body

## Context

Business requirement (Analysis every information being sent) cannot be meet.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Hello @teejay001, thank you for reaching out. I'm currently unable to reproduce this issue on my end. After attaching the image and adding text, I see an attachment added when calling mailbox.item.getAttachmentsAsync:

`{"value":[{"id":"0","name":"image001.png","size":0,"attachmentType":"file","isInline":true}],"status":"succeeded"}`

and the image "<v:rect id=\"Rectangle_x0020_1\"" is present in the returned HTML body when calling mailbox.item.body.getAsync.

Is this issue reproducible on Win32 and web Outlook?

**Comment by mikey8808** [comment]
Hi - can we reopen this ?
