### ISSUE TITLE
Setting MAPI Extended Properties on an outgoing message using office-js

### ISSUE THREAD

**Issue by carlosb1504** [OfficeDev/office-js#2789]
We have a use case whereby a third party mailflow middleware mandates us setting a collection of MAPI Extended properties over which we have little control. We currently do a Graph API PATCH Operation upon the message during an `ItemSend` event handler in order to achieve this, before allowing the message to be sent.

This works fine in an add-in when run in OWA and we can observe the MAPI Extended Property having been set in the Sent Item, but in Outlook Desktop on Windows the change is ineffective and our extended properties cannot be observed in the sent item, presumably this is due to the nature of Outlook Desktop on Windows running in cached mode by default. We are, it seems in effect, patching the online copy of the message, then immediately sending the locally cached version and losing our patched changes.

Is there any way that we can set these custom properties client side using the JS API on the outgoing message and avoid this problem, or any potential workaround that you (or anyone reading) might be able to suggest? Many thanks

**Comment by JuaneloJuanelo** [comment]
Hey @carlosb1504  thanks for asking this.  Yes, the properties that you are setting before the email is sent are overridden when the message itself actually arrives.

Couple of questions:
1. Did you tried to use our customProperties API? why is this not working for your scenario? (see code  sample [here](https://gist.github.com/JuaneloJuanelo/0f4c12f5456d70a02671d2dbdf556d3d), remember to call saveAsync after setting the customProp)
2. Is it an option to use InternetHeaders for this?

**Comment by carlosb1504** [comment]
Hey. We are having to work within the constraints of an existing 3rd party mailflow solution which is why we are having to set these very specific MAPI properties at specific addresses.

We do use customProperties for other scenarios and I am investigating with the 3rd party whether that or a couple of other alternatives I've suggested will be viable in the longer term, but this will require a bespoke process for our use case which may have cost implications if we cannot reliably set the required properties using Office.JS.

I appreciate that these MAPI properties are considered legacy. Are we saying that there isn't a way using the JS API to work around this issue currently?

Cheers

**Comment by JuaneloJuanelo** [comment]
Unfortunately, not with the JS API, we don't provide a MAPI property accessor. I wonder if you can solve the problem with a server-side process. You could create a customProperty via Office.js with the values you need to then server side [after the message is received] identify the tagged customProperty and create a the MAPI extended property you need.  that might work depending on how the 3rd Party solution works.
