### ISSUE TITLE
Issue with displayNewMessageForm receipents list as Array of strings

### ISSUE THREAD

**Issue by paronne** [OfficeDev/office-js#279]
Hi, i am trying to use the displayNewMessageForm, however i have an issue with the Recepients parameters. If i try pass the recepients as an Array of Strings i always get the following error:

## Expected Behavior

```
Office.context.mailbox.displayNewMessageForm(
{
toRecipients: Office.context.mailbox.item.to, // Copy the To line from current item
ccRecipients: ['sam@contoso.com'],
subject: 'Outlook add-ins are cool!',
htmlBody: 'Hello World!
'
});
```
should open a new message with the given params.

## Current Behavior
Instead i get the error.

Sys.ArgumentTypeException: Object cannot be converted to the required type.
Parameter name: ccRecipients

From the sample code above everything works fine if i remove the ccRecipients.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office 365
* Operating System: Windows 10

**Comment by exextoc** [comment]
I used your code as is:
Office.context.mailbox.displayNewMessageForm(
{
toRecipients: Office.context.mailbox.item.to, // Copy the To line from current item
ccRecipients: ['sam@contoso.com'],
subject: 'Outlook add-ins are cool!',
htmlBody: 'Hello World!'
});

in Outlook desktop and Outlook on web, and the new message form opens fine. to help isolate this issue: 
Have you tried this in Office online?
Are you using office.js from https://appsforoffice.microsoft.com/lib/1/hosted/Office.js
Could you provide build version of Outlook? https://support.office.com/en-us/article/What-version-of-Outlook-do-I-have-b3a9568c-edb5-42b9-9825-d48d82b2257c

**Comment by paronne** [comment]
Hi, thanks for the quick reply.

Tested also in the Office Online version on Chrome, same result in Online version too.
What is interesting is that using ccRecipients = Office.context.mailbox.item.to works just fine instead.
Tried to use [{"displayName": "Sam", "emailAddress": "sam@contoso.com"}], it goes into error as well.

The Desktop Outlook build version is: 16.0.10827.20181 64-bit.

Regards,
Paolo

**Comment by exextoc** [comment]
Thanks for confirming the outlook build version. Could you also verify if you are using office.js from  https://appsforoffice.microsoft.com/lib/1/hosted/Office.js? 

I can confirm that  ccRecipients = Office.context.mailbox.item.to works, and [{"displayName": "Sam", "emailAddress": "sam@contoso.com"}] does not. This API accepts array of string  ['sam@contoso.com'] and the object type that is returned from Office.context.mailbox.item.to, and nothing else.

I have looked a bit more and confirm that the check is looking for array. The API throws if Object.getType(['sam@contoso.com']) !== Array evaluates to true. If you can try to run this in the console, it might give us some idea if there are other JS overwrites that interferes with the type check.

In case it matters, could you try ccRecipients: new Array("sam@contoso.com"), ?  As I comented before, I have tried your original code and it works as is. At this point I am suggesting different things to help us understand this issue better.

**Comment by paronne** [comment]
Hi, thanks again for your reply.
I indeed use the office.js version you suggested. Thanks to your detail response i was able to find the root cause of the issue. I am running the functions within an Iframe, the check Object.getType(['sam@contoso.com']) !== Array returns true within the Iframe since the Array prototype would be different from the parent window prototype (where the office.js is loaded).
I think i know how to resolve it now, i can close the issue.
Thanks again for your help.
