### ISSUE TITLE
PowerPoint - Manage pane layout does not work in web version of PPT

### ISSUE THREAD

**Issue by sashakar** [OfficeDev/office-js#2790]
I would expect that in the web version of PowerPoint 365, I would be able to manage pane layout such as moving or resizing task panes the same way I could in the desktop version of PowerPoint. However I am unable to resize the task pane in the web.

## Expected Behavior

I would expect to be able to resize the PPT task pane in web because 1) I can resize the task pane of PPT in the desktop version and 2) I can resize the task pane of the web version of other MSFT apps like Excel. The behavior is very inconsistent.

## Current Behavior

Web version of PPT does not provide ability to manage pane layout at all.

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

We use the task pane to launch an add-in for our product in Microsoft applications. Since there is limited real estate in a task pane to display information, the ability to resize the task pane especially in a browser affects the user experience and usability of our add-in.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

I have tested this on Google Chrome specifically.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by JinghuiMS** [comment]
Thanks for reaching us. 
Could you try again? It should be possible to resize now.

**Comment by JinghuiMS** [comment]
@sashakar Can you resize your taskpane on PPT online now?

**Comment by sashakar** [comment]
@JinghuiMS I tested that I can successfully resize the task pane on web PPT. Thanks so much! You can close this track.

**Comment by JinghuiMS** [comment]
Thanks for reporting again. If you run into this problem again and feel this issue needs to be re-opened, please let us know.
