### ISSUE TITLE
OSF.DDA.Error 5001 when calling Office.auth.getAccessToken() on Outlook Email web

### ISSUE THREAD

**Issue by repl-mohan-krishna** [OfficeDev/office-js#2793]
We are developing Taskpane add-in for outlook email. when we calling getAccesToken method, sometimes i'm getting 5001 error.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: outlook
* Office version number: ______
* Operating System: windows 10
* Browser (if using Office on the web): chrome
 
## Expected behavior
Office.auth.getAccessToken() should return a Promise which resolves to the access token.

## Current behavior
Office.auth.getAccessToken() returns a Promise which rejects with the error:
{
   "name":"Internal Error",
   "message":"An internal error has occurred.",
   "code":5001
}

## Useful logs

![Screenshot (140)](https://user-images.githubusercontent.com/86103151/186373052-c3e94261-cde3-4351-aeba-5affdaee454d.png)

**Comment by exextoc** [comment]
Can you confirm if there's any dialog already open through the addin while calling getAccessToken?

**Comment by repl-mohan-krishna** [comment]
No. pre authorization already done by admin through Microsoft 365 admin center. it won't show any dialog while calling getAccesToken method

**Comment by exextoc** [comment]
Can you share a code snippet where you are calling getAccessToken?

**Comment by repl-mohan-krishna** [comment]
![image](https://user-images.githubusercontent.com/86103151/186648052-1ac54c9f-c437-403b-a53e-8d6b0f8f9bda.png)

Both values (allowSignIn,allowConsent ) are false always as user is already preauthorized at admin center((https://admin.microsoft.com).

**Comment by exextoc** [comment]
We have not been able to reproduce the issue with the given snippet. Can you share a manifest and test credentials for your add-in to OutlookExtensibility@M365x27035562.onmicrosoft.com if your add-in is publicly hosted so that we can investigate further?

**Comment by vyvo2412** [comment]
I also got this error OSF.DDA.Error Code: 5001 when I tried to use Office.context.mailbox.displayAppointmentFormAsync(). Any recs on this error?
