### ISSUE TITLE
Coloring the font of a selection Range is coloring all the paragraph in word Add-in

### ISSUE THREAD

**Issue by AhmadSukkar98** [OfficeDev/office-js#2795]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected behavior
When we color the font of a selection range only the selected range is colored and nothing else.

## Current behavior
coloring the font of a selection range will color the text starting from our selection till the end of the paragraph

## Steps to reproduce
1. Open the Add-in in a word document
2. Make sure the document is empty
3. Press ctrl+a  and then the Delete button to make sure it's cleared
4. Write the following text: `1234567890`
5. Select `456`
6. press the run button in the Add-in which should change the font color of the selected text to orange
7. `4567890` will be colored!

## Link to live example(s)
1. Here is a clean add-in that tries to color the font of a selection range into orange
2. [add-in sample](https://github.com/AhmadSukkar98/WordIssueWrongColoringSelectionBehavior-)
3.  [Recorded screen video](https://drive.google.com/file/d/1sYKDWPF73W4yG2eajSPQhcnupi6zI-AI/view?usp=sharing)

# Provide additional details
1. We get the current selection using `context.document.getSelection()`
2. Change the font color with ` selection.font.color = "#FFA500"`
4. Then we run `await context.sync();`
5. please take a look at the provided sample 

## Your Environment
* Platform:  Office on the web
* Host: Word
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome

## Context
We want to allow our users to color the font of a certain selected range

**Comment by JinghuiMS** [comment]
@AhmadSukkar98 
Thanks for reporting this issue. It's definitely not right to have this error. It has been put on our backlog<Bug#6541704> for internal track. We will keep track of this issue and let you know if there are any updates.
