### ISSUE TITLE
[ppt] retrieve text while editing the content of a textbox

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#2796]
Hello

In powerpoint: 
- when I click on a textbox, I am able to retrieve the text content of it with the code_1. This is the output I get:
> 25/08/2022 15:38:54     Verbose Runtime [Console] [Log] "{\"value\":\"Transcribe audio\\r\\n\",\"status\":\"succeeded\"}"
- however when I click inside the text box (to edit the text), the same code_1 gives me an empty value.  This is the output I get:
> 25/08/2022 15:38:56     Verbose Runtime [Console] [Log] "{\"value\":\"\",\"status\":\"succeeded\"}"

Is there a way to retrieve the text content of a text box while editing its content ?
Thanks

code_1 is:
>  await Office.context.document.getSelectedDataAsync(
      Office.CoercionType.Text,
      async (asyncResult) => {
          console.log(JSON.stringify(asyncResult))
      }

**Comment by JinghuiMS** [comment]
Thanks for reaching us. 
GetSelectedDataAsync API is for getting the data contained in the **current selection** in the document. If you select the textbox, it will return the whole content of textbox. If you click into textbox, your current selection is a cursor, so it will return an empty value. You can select the text you need first, then call getSelectedDataAsync API to unblock your self. You can refer to: https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=common-js-preview#office-office-document-getselecteddataasync-member(1)

**Comment by ghost** [comment]
hello great,
that is a good tip. 
would it be possible, when you are inside the selection, to retrieve the parent shape (to retrieve the text in this parent ship) ?
thanks

**Comment by JinghuiMS** [comment]
@jsoto-gladia 
You could try getParentShape() API. Please refer to
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest

**Comment by ghost** [comment]
great thanks. let me try this out

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.

**Comment by JinghuiMS** [comment]
Closing this issue because it appears to be resolved, but please let us know if you have further questions or feel it needs to be re-opened.

**Comment by ghost** [comment]
yes thnaks
