### ISSUE TITLE
[ppt] retrieve shapes data points

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#2799]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hello 
Is it possible to retrieve the data points that create a shape?
Thanks
Jonathan

For example, if I create a new rectangle shape, I would like to retrieve the four data points that
constitute it. (top-left, top-right, bottom-left and bottom-right). The following code gives me a deeper look at the content 
of the shape object. But I am not able to find what I want...
`await PowerPoint.run(async (context) => {
    const sheet = context.presentation.slides.getItemAt(0);
    const shapes = sheet.shapes;

    shapes.load('items');
    await context.sync();
    shapes.items.forEach(function (shape) {
      const shapeKeys = Object.keys(shape);
      console.log(shapeKeys);
      for (const idx in shapeKeys) {
        const key = shapeKeys[idx];
        console.log(key + ':' + shape[key]);
      }
    });
    await context.sync();
});`

This is the output:
`
25/08/2022 23:02:37     Verbose Runtime [Console] [Log] "m_contextBase:[object Object]"
25/08/2022 23:02:37     Verbose Runtime [Console] [Log] "m_objectPath:[object Object]"
25/08/2022 23:02:37     Verbose Runtime [Console] [Log] "m_context:[object Object]"
25/08/2022 23:02:37     Verbose Runtime [Console] [Log] "m_isNull:false"
25/08/2022 23:02:37     Verbose Runtime [Console] [Log] "_H:104.375039370079"
25/08/2022 23:02:37     Verbose Runtime [Console] [Log] "_I:2"
25/08/2022 23:02:37     Verbose Runtime [Console] [Log] "_L:66"
25/08/2022 23:02:37     Verbose Runtime [Console] [Log] "_N:Title 1"
25/08/2022 23:02:37     Verbose Runtime [Console] [Log] "_To:28.75"
25/08/2022 23:02:37     Verbose Runtime [Console] [Log] "_Ty:GeometricShape"
25/08/2022 23:02:37     Verbose Runtime [Console] [Log] "_W:828"
`

**Comment by ghost** [comment]
I see an object m_trackedObjects. is it of any interest ?

**Comment by ghost** [comment]
I also see shape['m_context']['_customData'] but it is only a string whose value is IterativeExecutor...

**Comment by JinghuiMS** [comment]
Add @ononder expert on PPT JS API to better handle it.

**Comment by ghost** [comment]
hello @ononder any news on this ?

**Comment by ghost** [comment]
hello, any news on this ?

**Comment by ononder** [comment]
Unfortunately, this is currently not possible with the available PowerPoint OfficeJs API.

**Comment by ghost** [comment]
any plan to support it ? if yes, any timeline  ?
