### ISSUE TITLE
How to handle slide changed event

### ISSUE THREAD

**Issue by scemis** [OfficeDev/office-js#28]
I need the same functionality from office.js as it was in vba to handle slide changing events.
for ex: Application.SlideShowNextSlide Event (PowerPoint)

https://msdn.microsoft.com/en-us/vba/powerpoint-vba/articles/application-slideshownextslide-event-powerpoint

PLease, could you help with that?

**Comment by sumurthy** [comment]
This event is not currently supported for PowerPoint. This may be taken up in the future; however no firm dates to share at this point.

**Comment by scemis** [comment]
Thanks for your reply.

Is there way to get current slide info during slide show process (active
view mode: read)

Thanks in advance.
