### ISSUE TITLE
[Excel Online] [Side loading] Add-In infra show strange behavior

### ISSUE THREAD

**Issue by 3dot1four** [OfficeDev/office-js#280]
Hi Team,

We are developing an Add-In for Excel and are facing issue with Side loading in Excel online. We are not sure if this behavior will continue even after App goes is prod.

Repro and Behavior 
1. Side load an Add-In pointing to [https://sdxvisio.azurewebsites.net/index.html](https://sdxvisio.azurewebsites.net/index.html)
2. Wait for 10 seconds after page loads.
3. You will see Add-In crashing with a reload button
4. Click reload
5. You will see page loaded again.
6. Wait for some time. Add-In will crash with a start button on it.
7. Press start it will work from now.

Screenshots: [https://testtestvize3vol-my.sharepoint.com/:i:/g/personal/visiodvaddinadmin_testtestvize3vol_onmicrosoft_com/EZg6k9jkU7ZIgT4mWdPWmscBihrJCVh1PdJwaG_riT4Okw?e=2sPmKq](https://testtestvize3vol-my.sharepoint.com/:i:/g/personal/visiodvaddinadmin_testtestvize3vol_onmicrosoft_com/EZg6k9jkU7ZIgT4mWdPWmscBihrJCVh1PdJwaG_riT4Okw?e=2sPmKq)

**Comment by 3dot1four** [comment]
Update: Having a unused office.js dependency in app fixes this issue but why do Add-In is forces to have Office.js dependency to run Online?

**Comment by keyur32** [comment]
Old issue, as it seems to have resolved. Addins I believe are required to have a depdency for Office.js so it can be properly initialized. Please reactive if otherwise.
