### ISSUE TITLE
Expose "pendingSave" event for all products/platforms

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#2801]
I realize that submitting feature requests is not something we typically do on Github, but this is a major limitation of the Office.js library that I believe should be addressed immediately.

Please see the feature request here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/expose-quot-save-quot-event-in-office-js-across-platforms/idi-p/3610495#M1310

I'd be more than happy to discuss our use cases across different products and why this is such a concern when it comes to data encryption.

**Comment by JinghuiMS** [comment]
Thanks for reaching us.
New Feature requests on https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform are considered when we go through our planning process.
