### ISSUE TITLE
SharedRuntime 1.1 does not support UNDO

### ISSUE THREAD

**Issue by YasharHeydari** [OfficeDev/office-js#2802]
# Provide required information needed to triage your issue
Hello,
     In Browser Runtime mode UNDO clears out. Once a Custom Function is called, the UNDO history is gone and no more UNDO is available. Changes will have undo support until next call to Custom Function again! 
    Video is provided
Thankyou

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (16.0.14326.20782) 64-bit 
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome / Edge
 
## Expected behavior

    UNDO Stack not cleared after Function Call! 

## Current behavior

    Stack Gets cleared and we cannot undo previous changes! 

    
## Steps to reproduce

1. Create a Simple Function in SharedRuntime 1.1 mode
2. Add data to Cells Then call the function  ( Custom Function) 
3. Undo is not available! 

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context
[2022-08-19 14-58-51.zip](https://github.com/OfficeDev/office-js/files/9435599/2022-08-19.14-58-51.zip)

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 
[manifest.zip](https://github.com/OfficeDev/office-js/files/9435651/manifest.zip)

**Comment by prasadhpshenoy** [comment]
Is there any update on this?? 
We are encountering the same issue and its really annoying..
Appreciate quick response on this.

**Comment by madhavagrawal17** [comment]
Can you provide me details on what APIs you are calling inside the Custom Functions? Can you also try a simple add Custom Function to see if UNDO is working or not ?

**Comment by YasharHeydari** [comment]
Hi @madhavagrawal17, 
    Thanks for response. I've tested with a very simple add custom function. When it's  Shared Runtime, calling the custom function causes the UNDO stack wipe out and it won't work on previous actions. In other words UNDO stack is cleared on each Custom Function call.

**Comment by madhavagrawal17** [comment]
@JinghuiMS, could you please look into this issue. It seems it is happening for simple Custom Functions, so it is not related to Shared Runtime.

**Comment by YasharHeydari** [comment]
@madhavagrawal17 & @JinghuiMS 
  Thanks for working on this. Just to make it clear, it is related to shared runtime, as when I change it to Custom Function Runtime ( JS Only ) the problem mitigates drastically and Undo stack gets cleared just when the Task Pane is opened. But when I change the Runtime to Shared Runtime, every function call clears the Undo stack. 
I will share both repos by the end of the day with videos  of each showing how they behave.

**Comment by YasharHeydari** [comment]
Hi again, 
   As promised, below I've provided the code repos and the videos of running each of those Custom Functions (Add function) on my Windows 10 machine:

This is the **SharedRuntime Repo** and Video: 
https://github.com/YasharHeydari/CF_SharedRuntime 
[AddMethod_SharedRuntime.zip](https://github.com/OfficeDev/office-js/files/9530759/AddMethod_SharedRuntime.zip)

This is the **Custom Function Repo** and Video: 
https://github.com/YasharHeydari/CF_CustomFunctionRuntime
[AddMethodCustomFunctionRuntime.zip](https://github.com/OfficeDev/office-js/files/9530763/AddMethodCustomFunctionRuntime.zip)

**STEPS**

1. Get The Repo
2. npm i
3. npm run build
4. npm start
5. Add Values in cells 
6. add Formula calling the cumstom function =CONTOSO.ADD(x,y)
7. Add other values to other cells
8. Try UNDO 
8.1. in SharedRuntime the undo will go back until last function cell
8.2. in CustomFunctionRuntime the undo will work just fine. 

These to Repos are basically the same just the manifest.xml in them differ for Shared vs CustomFunction Runtime.

>

**Comment by madhavagrawal17** [comment]
@YasharHeydari, thank you for providing all the information. I am able to see the issue locally and I checked with our internal team. It seems we run Shared Runtime on WebView and currently, we are working on implementing the Undo stack feature for API for WebView. Currently, there is no solution for it but soon this feature will be released fully in production, and this will be fixed.

**Comment by YasharHeydari** [comment]
Thanks for the update and looking forward to having the fix soon.

**Comment by prasadhpshenoy** [comment]
Thanks the update Madhav. This would be a great relief for all our clients who are encountering the UNDO issue. 
Do you have a tentative timeline on when this would be released??

**Comment by jeremy-msft** [comment]
We don't currently have a timeline for undo support in the Office JS APIs. To provide more context to @madhavagrawal17's comment, we are investigating feasibility across different parts of the platform and will enable support once we can ensure it will be safe, reliable, and performant for each subset of the APIs.  If we discover that's not possible in certain scenarios, we'll be sure to clearly document the limitations of undo; however, we cannot commit to a specific scope of undo support at this time.

**Comment by YasharHeydari** [comment]
Thank you Jeremy for the update, 
    I was thinking about this last few days and we've been struggling on these for quite a time now. I was wondering if it's possible for you to provide a little bit more of context around what happens to Undo stack upon a function call ? Out of curiosity, is that a technical decision originally to clear the Undo stack or there have be defects so it's decided later to prevent conflicts? And I was just wondering how the Runtime Model of the add-in  ( JS Only vs Browser ( Shared) ) is actually affect this?   Because I was suspecting that session conflicts between add-in and excel itself may be the root-cause of this. 
    Also do you think it's something that someone can try to fix on a fork ?

**Comment by prasadhpshenoy** [comment]
Jeremy and Madhav, 
Is there any update on this??

**Comment by jeremy-msft** [comment]
The undo stack currently gets cleared whenever API calls are made using a shared runtime to prevent unexpected conflicts that could arise, so the behavior you are seeing is as expected.  Unfortunately, I don't have any additional updates to share on future changes or timelines.

**Comment by prasadhpshenoy** [comment]
Hi @JinghuiMS 
I was about to ask for an update since we didn't receive anything post Sept 27, but I noticed that you have removed `Needs:attention` label.  Not sure what that means. I really hope it doesn't mean this is going to be deprioritized. 
 
It is a major blocker for us. 
We are working on migrating our functionalities from legacy VSTO add-in to the more modern and MSFT recommended office 365 add-in. But if UNDO functionality is not working it can be showstopper for us. 
I really appreciate your understanding on this.

**Comment by jeremy-msft** [comment]
Hi @prasadhpshenoy, the `Needs: attention` label corresponds to `Waiting on Microsoft to provide feedback`, so it's just status cleanup rather than indicating a deprioritization.  

This item is still on our backlog and my earlier [response](https://github.com/OfficeDev/office-js/issues/2802#issuecomment-1244132075) still reflects the latest status.  We understand the importance here and while we continue to look into this, I do want to set the right expectations that this is not something that can be readily solved given the considerations I noted in that update.

**Comment by prasadhpshenoy** [comment]
Hi,
Is there any update on this or do you have a tentative date for a fix on this?

**Comment by hdwatts** [comment]
Hey @madhavagrawal17, do you have any update on the timing for this fix? This is a blocker for us.

**Comment by gmichaud** [comment]
(There are 3 GitHub issues tracking this: #2543 #3317 and #2802 -- there's a considerable number of comments from users requesting this, hopefully the total volume of feedback is taken into account while prioritizing this enhancement!)

**Comment by M00d5** [comment]
Bumping this so it can get looked at. As mentioned above by other users, this is also a major block for us. Its been over a year ..

**Comment by M00d5** [comment]
> @YasharHeydari, thank you for providing all the information. I am able to see the issue locally and I checked with our internal team. It seems we run Shared Runtime on WebView and currently, we are working on implementing the Undo stack feature for API for WebView. Currently, there is no solution for it but soon this feature will be released fully in production, and this will be fixed.

@madhavagrawal17 , thanks for your update in 2022. Has there been any progress to get this to production ?

**Comment by gmichaud** [comment]
Update: https://github.com/OfficeDev/office-js/issues/3317#issuecomment-1855922312

**Comment by prasadhpshenoy** [comment]
Hi @jeremy-msft and @madhavagrawal17 
I was wondering if there is any update on this?

**Comment by M00d5** [comment]
hello @prasadhpshenoy - I have colleagues where it is working and where it is not. For me it is not working but I have witnessed it working. Please check the info box that Microsoft updated today. 


![image](https://github.com/OfficeDev/office-js/assets/34275194/2135a9b6-b239-4fee-8113-8eafdf8f0ba1)

**Comment by grangeryy** [comment]
@prasadhpshenoy, hope it helps. For custom function, the undo support on Windows/Mac was recently 100% supported on Current Channel starting from build 17003.15021. And for Monthly Enterprise Channel, it will be supported starting from build 17231.20236 (expected available in March). This improvement works for normal custom functions and streaming functions. 

But please note that undo supports for Excel JavaScript APIs and custom functions that call Excel writing JavaScript APIs are not included, as we don't encourage this type of use pattern, details see [Limitations of calling Excel JavaScript APIs through a custom function](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/call-excel-apis-from-custom-function#limitations-of-calling-excel-javascript-apis-through-a-custom-function).
