### ISSUE TITLE
transparent icon leaves white box (Win desktop only)

### ISSUE THREAD

**Issue by Alex0cean** [OfficeDev/office-js#2803]
# Provide required information needed to triage your issue
We are using a fully transparent icon in front of the texts in the dropdown menu. You see that there is a white box now in front of the text (only Windows desktop). 
Works fine in Excel Online and Mac.

![image](https://user-images.githubusercontent.com/80747078/187161217-d53803b8-1714-4ace-92cc-c60d3bd23ba9.png)

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: only Windows desktop (works fine in Excel Online and Mac desktop)
* Host [Excel, Word, PowerPoint, etc.]: Excel

**Comment by JinghuiMS** [comment]
@Alex0cean 
Thanks for reaching us.
Is the task you’re trying to accomplish is a new feature in the new add-in, or an existing feature in the old version?

**Comment by Alex0cean** [comment]
Thanks for your response @JinghuiMS ,

we've been using the transparent icon since a while - and it works in all other platforms as expected, but not in Win Desktop.

**Comment by yuc014** [comment]
Hi @Alex0cean, sorry I'm not familiar with icon part.
But I found this may help you: https://docs.microsoft.com/en-us/office/dev/add-ins/design/add-in-icons-monoline#color
![image](https://user-images.githubusercontent.com/87364252/187395254-24faa8ba-b20b-49c4-98f3-904a919ebc97.png)
Seem you should try Background Fill (250,250,250)?

**Comment by Alex0cean** [comment]
Thanks @JinghuiMS ,
but what if you change the Office theme? We wanted to be independent of that, that's why wanted to have a TRANSPARENT icon  (which works in some platforms) ....

**Comment by Alex0cean** [comment]
Hi @JinghuiMS , I do not suspect this is an OfficeJS bug, but rather Excel general ... but Yawei Zhu asked me to open a ticket and you guys can forward ...

**Comment by JinghuiMS** [comment]
@yuc014 any updates?

**Comment by yuc014** [comment]
Hi @Alex0cean, I consulted design team, they recommend use SVG icons without background to make it transparent and follow with theme.

**Comment by Alex0cean** [comment]
Thanks for your reply @yuc014 .
But if we reference svg files in the manifest, it does not show. See https://stackoverflow.com/questions/51304877/office-plugin-wont-show-up-in-local-desktop-version-of-excel-manifest-issue .

**Comment by yuc014** [comment]
Hi @Alex0cean 
Sorry to hear that solution not work, I take a study with current Add-ins, and I found some of them use transparent icon like yours.
For example:
![image](https://user-images.githubusercontent.com/87364252/188534794-7ab4cb78-a1ad-42b1-ab09-0385ea6665e9.png)
And I try to get its manifest to see how it set the icon.
```
<Item id="Solver.Welcome">
<Label resid="Solver.Welcome.Label"/>
<Supertip>
<Title resid="Solver.Welcome.Label"/>
<Description resid="Solver.Welcome.Tooltip"/>
</Supertip>
<Icon>
<bt:Image size="16" resid="Solver.Empty_16x16"/>
<bt:Image size="32" resid="Solver.Empty_32x32"/>
<bt:Image size="80" resid="Solver.Empty_80x80"/>
</Icon>
<Action xsi:type="ExecuteFunction">
<FunctionName>common.welcomeScreen</FunctionName>
</Action>
</Item>
```
As you see, they use `Solver.Empty_16x16`, `Solver.Empty_32x32` and `Solver.Empty_80x80` which may also meet your requirement.
And the link of them:
```
<bt:Image id="Solver.Empty_16x16" DefaultValue="https://analytic-solver.net/v21.5/solver/webaddins/Solver/Pages/assets/images/16x16_Empty Icon.png"/>
<bt:Image id="Solver.Empty_32x32" DefaultValue="https://analytic-solver.net/v21.5/solver/webaddins/Solver/Pages/assets/images/32x32_Empty Icon.png"/>
<bt:Image id="Solver.Empty_80x80" DefaultValue="https://analytic-solver.net/v21.5/solver/webaddins/Solver/Pages/assets/images/80x80_Empty Icon.png"/>
```
Please try to download them via the link and see whether work for you. Thanks.

**Comment by Alex0cean** [comment]
Thanks @yuc014 , this helped. I close the ticket.
