### ISSUE TITLE
SharePoint app catalog deployment with `VersionOverrides` tag

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#2805]
Hi,

I've read here: https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish#sharepoint-app-catalog-deployment 
that if I want to publish my add-in via sharepoint app catalog I should not have an add-in which defines VersionOverrides in the manifest file. But because I need a ribbon, functions file I need to define that tag.

Is there any way I could be able to have a manifest file with ribbon declarations, images for the buttons and a functions file, but without the VersionOverrides?

I want to make the deployment in sharepoint app catalog, but I still want to have the ribbon declarations and the function file.

This is an Excel add-in.

**Comment by MingjiaLiu1995** [comment]
Hi, thanks for the question. We recommend [Centralized Deployment](https://docs.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide) if you are developing an add-in for organization. If you want to test your add-in, you could use [share a folder](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins). Please let us know if you have other concerns.

**Comment by danielpdev** [comment]
ok, thank you @MingjiaLiu1995
Btw, are there any issues if we publish our add-in to AppSource and use preview apis?

**Comment by JinghuiMS** [comment]
@danielpdev  We don’t allow the use of preview CDN reference on the store, we do have a policy of only allow add-ins using the public production CDN. (see screen shot below)
![image](https://user-images.githubusercontent.com/56814588/189039546-c735a414-1a3c-4565-9422-825c1f8730e8.png)

**Comment by danielpdev** [comment]
@JinghuiMS  and if we have the preview apis loaded from our domain and not from the CDN, it is accepted?
We need the preview apis for things that are not yet available in the stable version.

**Comment by JinghuiMS** [comment]
@danielpdev 
Our PM @wangyun-microsoft  will answer your question. Thanks!

**Comment by danielpdev** [comment]
Thank you @JinghuiMS, we need this ASAP.
Btw, is there a subscribe channel or something that we can get notified when a new version of preview/stable apis are going to be release? We need to be sure that there are no breaking changes.

**Comment by JinghuiMS** [comment]
@wangyun-microsoft  Please help answer this question. Thanks!

**Comment by wangyun-microsoft** [comment]
Currently, you need to use production CDN for your published add-ins. Please join the [community calls](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins-community-call) to get latest information about APIs. You could also join our [green panel](https://ux.microsoft.com/Panel/WordAddinDeveloper?utm_campaign=github&utm_source=github&utm_medium=url) where we periodically send email updates for our partners.
