### ISSUE TITLE
PowerPoint: Create presentation using a presentation with size 37.50 MB or bigger fails

### ISSUE THREAD

**Issue by FranCerrada** [OfficeDev/office-js#2806]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Is there any limitation on the size of the presentations that can be used to create a new presentation on PowerPoint Web Add-in using the `createPresentation` method?

Every time I try to create a presentation whose size is 37.50 MB or bigger I get the following error:
```
powerpoint-web-16.00.js:26 Uncaught (in promise) RichApi.Error: An internal error has occurred.
    at new n (powerpoint-web-16.00.js:26:304039)
    at o (powerpoint-web-16.00.js:26:547867)
    at OSF.DDA.issueAsyncResult (powerpoint-web-16.00.js:26:69957)
    at Object.onComplete (powerpoint-web-16.00.js:26:82149)
    at Object.callback (powerpoint-web-16.00.js:26:127396)
    at v (powerpoint-web-16.00.js:26:115957)
```
I cannot find anything in the documentation about this limitation, but if I remove some text from the failing one so the final size is 37.49MB it works. It has also nothing to do with the content of the presentation itself since it fails for any presentation of this size.

I am able to reproduce it by creating a new Add-in that just reads a file and tries to make a presentation using it.

## Your Environment
Platform: Office Online
Host: PowerPoint
Operating System: Windows 10
Browser: Chrome
 
## Expected behavior
A new presentation is created.

## Current behavior
Creation fails.

## Steps to reproduce
Invoke the `PowerPoint.createPresentation()` with the data of a presentation whose size is 37.50MB or bigger. 

## Context
Size limitation when creating a new presentation using the PowerPoint API.

**Comment by JinghuiMS** [comment]
@ononder Do you know whether this has size limitation?

**Comment by ononder** [comment]
I believe there is a limit of 50MB, but that is the transport size, and base64 encoding conversion loses bytes, so 
50 MB = 50x1024x1024  = 52428800 bytes transport can hold 52428800 x 6 / 8 = 39321600 bytes of base64 encoded file data, which is equal to 39321600 / (1024 * 1024) = 37.5 MB.

As far as I know this affects PowerPoint Online only, not desktop endpoints.

**Comment by FranCerrada** [comment]
Thanks for the answer, this explains the issue. Do you know if there is a plan on changing this in the near future, also if this information is available anywhere on the PowerPoint API documentation? 
We got some customers complaining about it and would be great to have an official answer we could use to explain the root cause.

**Comment by FranCerrada** [comment]
By the way, with "this affects PowerPoint Online only" I guess this also includes PowerPoint for Mac as it uses the same Javascript API, right?
