### ISSUE TITLE
Office.context.document.getTaskFieldAsync returns wrong result for Summary, Milestone, Active in Project

### ISSUE THREAD

**Issue by JBoman32768** [OfficeDev/office-js#2807]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When executing [getTaskFieldAsync](https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=word-js-preview#office-office-document-gettaskfieldasync-member(2)) with the the following parameters, **false** is always returned even when the result should be **true**:
 - [`Office.ProjectTaskFields.Active`](https://support.microsoft.com/en-us/office/active-task-field-81769c1e-6b4b-4014-bad4-21471fdaa99e)
 - [`Office.ProjectTaskFields.Milestone`](https://support.microsoft.com/en-us/office/milestone-task-field-b3bf8a34-4453-4cb4-9fc8-0ae5ef0b4c25)
 - [`Office.ProjectTaskFields.Summary`](https://support.microsoft.com/en-us/office/summary-task-field-faaa9c5b-2d78-4ddc-b701-4a2170d2a2a0)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop 
* Host [Excel, Word, PowerPoint, etc.]: Project 
* Office version number: Version 2207 (Build 15427.20210 Click-to-Run)
* Operating System: Windows 11
* Browser (if using Office on the web): Edge Webview 2
 
## Expected behavior
[getTaskFieldAsync](https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=word-js-preview#office-office-document-gettaskfieldasync-member(2)) returns correct true/false values as per the Task ID parameter.

## Current behavior
**false** is always returned.

## Steps to reproduce

1. Create Project add-in using yeoman template
2. Change button action to:
```
Office.context.document.getTaskFieldAsync(taskIdOfSummaryTask, Office.ProjectTaskFields.Summary, (result) => {
            console.log(result.value.fieldValue);
});
```
3. Note that **false** is always returned even for task Id's that correlate to summary tasks.

## Context

The context is trying to read task information from Project Desktop

**Comment by JBoman32768** [comment]
"Not planned" isn't probably a good resolution for this one.  I logged this via Microsoft Support case #32728393 and the bug in Project was corrected 👍

**Comment by gergzk** [comment]
Thanks @JBoman32768
