### ISSUE TITLE
Word Online Inconsistently Loading Add-In

### ISSUE THREAD

**Issue by andschleicher** [OfficeDev/office-js#281]
The Add-In that has been applied to my account through the Microsoft 365 Admin Center Add-Ins page only loads about 20% of the time when I open a new Word Online document.

## Expected Behavior
The Add-In to always be available and enabled when a new Word Online document is opened.

## Current Behavior
When I click on the 'New blank document' button at https://www.office.com/launch/word a new Word Online document opens as expected. However, most of the time the Add-In that has been enabled for my account does not load and when it does, there is a several second delay before the tab at the top for the Add-In is added to the banner.

When the Add-In does fail to load, I can force it to load by performing the following steps:
  1. Click on the Insert tab in the top banner
  2. Click on Office Add-ins
  3. Click on the Admin Managed tab if it isn't already selected
  4. Click on the Refresh button

Once the Refresh button has been pressed, the Add-In appears as expected in the banner which implies that it was already added, but Word Online failed to load it.

## Steps to Reproduce, or Live Example
  1. Upload an Add-In to https://admin.microsoft.com/AdminPortal/Home#/Settings/ServicesAndAddIns and apply it to your O365 account
  2. In Word Online, enable the Add-In via the Admin Managed tab of the Add-ins popup
  3. Click on the 'New blank document' button at https://www.office.com/launch/word
  4. The Add-In only loads about 20% of the time

I found that I experience the same behavior with the example Auto-open Add-In so I've attached that manifest file as an example. The one thing to note is that this manifest creates a button in the home tab rather than adding a new tab to the banner, but the same failure to load is experienced. Due to limitations from GitHub, the Add-In has been attached as a txt file rather than an xml.
[Auto Open Manifest.txt](https://github.com/OfficeDev/office-js/files/2515327/Auto.Open.Manifest.txt)

## Context
The Add-In will be used concurrently while updating most documents so it should load automatically for every Word Online document so that the user doesn't have to perform the steps above that force it to load.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Word Online
* Office version number: ______
* Operating System: Windows 10
* Browser (if using Office Online): Firefox 63.0

## Useful logs
There are no difference in the console logs between when the Add-In appears as expected and when it fails to load.

**Comment by abhijeetnarvekar** [comment]
I have also experienced this issue when add-in is deployed via centralized deployment.

**Comment by andschleicher** [comment]
This issue appears to have been resolved as we are no longer experiencing issues with the Add-In failing to be loaded automatically
