### ISSUE TITLE
Office JS add-ins for Word / Excel / PowerPoint - Insert tag automatically into document

### ISSUE THREAD

**Issue by MajuMadhusudanan** [OfficeDev/office-js#2812]
Hi,

 

I would like to insert a tag in body part of the document or footer of the document when user opens document from a directory. We are into enterprise content management software and stores document and manages it. 

 

There is a use case with word / excel / PowerPoint apps. When user downloads a document from store to local directory and opens its from directory, we want to insert a tag into the body part of the document or footer of the document. This use case is common in document management system. Basically the tag indicates a unique identifier with supporting information about the document.

 

Is there anyway to insert a tag when user open a document? Any events or callback support it?

**Comment by jipyua** [comment]
hi, do you must insert a "tag" into the body part of the document which is someplace together with the paragraphs? Can you insert as some setting which is not visible from UI but you can get and set them freely? Please refer here for details: https://docs.microsoft.com/en-us/javascript/api/office/office.settings?view=common-js-preview

If you need events to notify the document open, I am afraid so far there is no such event across WXP JavaScript API. We track Office Add-in feature requests on the Ideas Forum: https://aka.ms/m365dev-suggestions. please feel free to add one for this request.
