### ISSUE TITLE
Outlook 365 for Mobile app - Compose window support for Office JS add-ins

### ISSUE THREAD

**Issue by MajuMadhusudanan** [OfficeDev/office-js#2813]
Hi,

We are exploring the new Office JS add-ons model for Outlook for mobile apps and wanted to integrate our product with iOS/Android apps. While exploring the new Office JS model, we didn't see any way to integrate the product with compose window. Task-pane or commandBar way of integration is missing for compose window. 

Compose window task-pane or commandBar integration is common use case among iOS/Android users. While composing emails, the following use cases are common in industry:

1. Users want to insert documents or attach emails from 3rd part repository or storage or from content management software. 
2. When user sends an email, they want to keep a copy of the email in the repository also

Currently these use cases are not possible with add-in model. But it is supported in desktop version as well as web version of add-ins. Without these use cases support, users wont adapt our solutions. So this is required for more user adaptability. 

Any plans to add compose window support for add-ins (Outlook for mobile apps) ??

**Comment by exextoc** [comment]
Currently the feature: MessageComposeCommandSurface for mobile, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by MajuMadhusudanan** [comment]
Added as a feature request in [Tech Community Page](http://aka.ms/M365dev-suggestions) page.

**Comment by exextoc** [comment]
Thank you for creating the feature request. We would be prioritizing among the feature requests received based on the impact.
