### ISSUE TITLE
How to disable excel shortcuts when add-ins run.

### ISSUE THREAD

**Issue by knight-baron** [OfficeDev/office-js#2814]
## How to disable excel shortcuts when add-ins run.

When the user presses Ctrl + Alt + F9, excel calculates all worksheets in all open workbooks, regardless of whether they have changed since the last calculation. 
But if our add-in is running I don't want this shortcut(Ctrl + Alt + F9) to work how can I do it?

Can I turn off this shortcut via Office.js?

**Comment by ruijiaMS** [comment]
Hi, @knight-baron,

Ctrl + Alt + F9 would trigger all cells recalculation in all open workbooks forcibly, some details could be found in https://docs.microsoft.com/en-us/office/client-developer/excel/excel-recalculation?source=docs#all-open-workbooks-tree-rebuild-and-forced-calculation

There are many keyboard shortcuts that are already in use by Office, like Ctrl + Alt + F9, and customer could not modify it directly. However, you can add customize keyboard shortcuts to your Office Add-ins, here is the official doc about how to add them into your project. What's more, you can make a choice while conflict happen. https://docs.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts

**Comment by knight-baron** [comment]
That means I can't turn off this hotkey. But can I use this key for another action instead?

**Comment by ruijiaMS** [comment]
This is a key which defined by Office, so I think you cannot use it for another action instead or it can be seen as current api does not support your assumption. The better way to fix your problem is avoiding triggering such a key in your add-in behaviour/logic or you can post a feature request~

**Comment by knight-baron** [comment]
Thank you for the answers.
