### ISSUE TITLE
Exce

### ISSUE THREAD

**Issue by harri-rajala-koivu-solutions** [OfficeDev/office-js#2817]
## Post how-to questions about your code on Microsoft Q&A

We have several forums where you can ask the developer community questions about your code. Try one of the following forums to ask technical questions about:
- [Developing Office Add-ins for Word, Excel, PowerPoint, Outlook, Project, Visio, and OneNote](https://docs.microsoft.com/answers/topics/office-addins-dev.html)
- [Access programming in Office](https://docs.microsoft.com/answers/topics/office-access-dev.html)
- [Developing COM or VSTO Add-ins for Office](https://docs.microsoft.com/answers/topics/office-vsto-com-dev.html)
- [Office JavaScript API](https://docs.microsoft.com/answers/topics/office-js-dev.html)
- [SharePoint and OneDrive development](https://docs.microsoft.com/answers/topics/sharepoint-dev.html)
- [Deploying and publishing Office or SharePoint apps to AppSource](https://docs.microsoft.com/answers/topics/microsoft-365-apps-publishing-dev.html)

For additional information about JavaScript programming, see the [JavaScript at Microsoft](https://docs.microsoft.com/javascript/) community hub.

**Comment by MingjiaLiu1995** [comment]
Hi, thanks for the comment! I'm closing this issue because there seem no potential bugs or documentation errors need to solve. Please let us know if you have other concerns. Thanks!
