### ISSUE TITLE
Excel.createWorkbook blocks VBA macros.

### ISSUE THREAD

**Issue by harri-rajala-koivu-solutions** [OfficeDev/office-js#2818]
Our Excel add-in allows users to upload and download Excel files. 

For upload, we use Office.context.document.getFileAsync method to upload the current workbook to our server (file is stored in Google Cloud Storage).

For download, we first download an excel file from Google Cloud Storage using a signed URL and convert that to a base64 string. After that, we open a new workbook using Excel.createWorkbook(excelFileAsBase64) method.

Both upload and download work ok, except in one case. If a user has added VBA macros, then after download, we see the following error, and macros are blocked.

> SECURITY RISK: Microsoft has blocked Macros from running because the source of this file is untrusted.

Is there anything we can do to allow our add-in to create a new workbook (using Excel.createWorkbook method) with VBA macros enabled?

**Comment by JinghuiMS** [comment]
@yaweizhu-henson  Could you help answer this question? Thanks!

**Comment by grangeryy** [comment]
@harri-rajala-koivu-solutions this behavior is expected as Office will block macros downloading from the internet by default for security reasons. Details can be found in [this blog](https://techcommunity.microsoft.com/t5/microsoft-365-blog/helping-users-stay-safe-blocking-internet-macros-by-default-in/ba-p/3071805/page/2#comments).

To unblock macros, you may find some solutions in below two articles:
For admins: [allow VBA macros to run in files you trust](https://docs.microsoft.com/en-us/DeployOffice/security/internet-macros-blocked#steps-to-take-to-allow-vba-macros-to-run-in-files-that-you-trust)
For end users: [unblock macros if you're sure the files are safe.](https://support.microsoft.com/en-us/topic/a-potentially-dangerous-macro-has-been-blocked-0952faa0-37e7-4316-b61d-5b5ed6024216)

If the warning shows while using this createWorkbook API for a new created file, you can first save the file with above certain  solution adopted and then reopen the file.

**Comment by harri-rajala-koivu-solutions** [comment]
You said:

> you can first save the file with above certain solution adopted and then reopen the file.

But how can I do that from the add-in using the OfficeJS library?

I don't want that the end user needs to handle or manually save/open any Excel files. Our add-in should do everything for our customers. I want that the only thing that the end user needs to do is to click the button inside our add-in and after that user will see a new Excel workbook (with VBA macros enabled). No "Save As" dialogs or anything. 

That's why you have Office.context.document.getFileAsync and Excel.createWorkbook functions. With those methods, it is possible to save and open files without the end user handling any files. And, as I said, it works fine if the workbook does not have any VBA macros. Now I want it works the same also for the workbook that contains VBA macros.

**Comment by harri-rajala-koivu-solutions** [comment]
@grangeryy 
Please read my previous comment and give your opinion.

**Comment by grangeryy** [comment]
From security perspective, we need to keep blocking these macros by default to make sure customers are in safe state. May I know more details about in which cases you need to create a new workbook with macros enabled using Excel.createWorkbook? Any better suggestion @yaweizhu-henson ?

**Comment by harri-rajala-koivu-solutions** [comment]
@grangeryy @yaweizhu-henson 
Our add-in does not need, use or create VBA macros. But users can add VBA macros if they want. We provide "Save to Cloud" and "Open from Cloud" functions, which should work even if the user adds VBA macros. 

Can you at least change Excel.createWorkbook so that it disables VBA macros, showing the warning 
_"File contains VBA macros which are disabled by default. Do you want to enable macros?"_ 
and then the user can enable macros if wanted. 

Now the problem is that VBA macros are entirely blocked, and the user cannot enable macros.

**Comment by grangeryy** [comment]
@harri-rajala-koivu-solutions, thanks for the additional information and it's helpful to us to know that creating workbook with macros are not the "must" step for you add-in. Agree we could provide a better UI experience to improve the case so customers can know about the things he/she needs to deal with if creating new workbook with macros. We'll discuss internally and do some investigations first. THX!

**Comment by harri-rajala-koivu-solutions** [comment]
@grangeryy @JinghuiMS @yaweizhu-henson 
Do you have any updates? 
Are you going to make changes related to this issue? 
If yes, what and when?

**Comment by grangeryy** [comment]
Hi @harri-rajala-koivu-solutions, after some initial investigation, we found this ask is not a common case for customers but requires large effort to implement to do Office security related changes.  We've added this requirement into the backlog to track in long-term.

**Comment by donlvMSFT** [comment]
I'd like to close this issue due to current status, please raise a new one or reactive if there're further questions. Thanks!
