### ISSUE TITLE
Outlook for Windows: recipientType is incorrect for Personal Contacts

### ISSUE THREAD

**Issue by htryggva** [OfficeDev/office-js#2819]
When calling `Office.context.mailbox.item.to.getAsync()`, the `recipientType` is set to `'user'` for contacts in the address book (Personal Contacts) even if they have @gmail.com or @outlook.com domains or even an account from another Microsoft 365 tenant. This makes it impossible to differentiate between users in the same tenant and personal contacts. 

**Note that this is inconsistent with Outlook for the Web, which behaves as expected!**

## Your Environment

* Platform: PC desktop
* Host : Outlook
* Office version number: Version 2207 (Build 15427.20210)
* Operating System: Windows
 
## Expected behavior
`recipientType` should be `'externalUser'` when the recipient is not a member of the Azure AD tenant, regardless of Personal Contacts.

**Note that Outlook for the Web returns the expected value!**

## Current behavior
`recipientType` seems to be `'user'` when the recipient is in the Personal Contacts of the user. But this is inconsistent with Outlook for the Web.

## Steps to reproduce
1. Open Outlook for Windows
2. Open a Microsoft 365 Mailbox
3. Add any external recipient to personal contacts
   - for example @gmail or @hotmail address or another Microsoft 365 Mailbox
4. Create a new email
5. Add the contact to the 'To' recipients
6. Open ScriptLab and add a call to `Office.context.mailbox.item.to.getAsync(console.log)`.
7. Notice in the console that recipientType is set to 'user' => expected value should be 'externalUser'

## Context
Our product determines if the scope of the email is Internal or External be evaluating the recipentType of all the recipients. If the API returns incorrect or inconsistent results, then we cannot rely on it.

**Comment by htryggva** [comment]
Hi @JuaneloJuanelo. We are reporting this because we have a customer that is blocked from using the Internal/External scoping feature in our Mail Signature because of this issue. Any chance you can have someone look at this? It's possibly related to #2238. Regards from Switzerland!

**Comment by exextoc** [comment]
We are planning to adjust this in a future build of Outlook, so that Contacts resolved from the Personal Address Book return as type "Other". 

This build will be updated with the fixed build numbers, once the change is made.

**Comment by timwan03** [comment]
Updating that the builds AFTER 16.0.15813.10000 will have the fix. (Note that this build number will NOT match the official Monthly Release build #'s). But any release after 15813 will have it.

**Comment by timwan10** [comment]
Every build after and including: 16.0.15813.10000 will have this change in it. Note that this build # will not match exactly with the final monthly release build number, but every build after 15813 should have this change.
