### ISSUE TITLE
[Important]Need events for Office Web versions of Word and Excel

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#282]
## Expected Behavior
The following list of events found on the client version of Word and Excel would aid in development of apps that work the same as current client addin apps work.

Excel Open Event
Excel Close Event
Excel BeforeClose Event
Workbook activate event

Word Open Event
Word Close Event
Word beforeClose event
Document activate event

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ___PC desktop___
* Host [Excel, Word, PowerPoint, etc.]: ___Excel,Word___
* Office version number: __Office2016 and later____
* Operating System: __Windows____
* Browser (if using Office Online): ______

**Comment by dmahugh** [comment]
Thanks for the feedback, @hengchengfei. I've passed this on to the engineering team.

Watch for updates on the [Excel requirement sets](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-api-requirement-sets
) and [Word requirement sets](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/word-api-requirement-sets) documentation pages.
