### ISSUE TITLE
`Office.context.ui.openBrowserWindow` does not work for Office URI schemes

### ISSUE THREAD

**Issue by hbnrmx** [OfficeDev/office-js#2820]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.61.1 (22052000)
* Operating System: MacOS
* Browser (if using Office on the web): -
 
## Expected behavior

Invoking `Office.context.ui.openBrowserWindow` with a custom protocol (e.g. Office URI scheme link) should work.

## Current behavior

custom protocols are not supported. Is there another way to open files via their url?

## Steps to reproduce

1. open a sidepane app in macOS
2. Invoke `Office.context.ui.openBrowserWindow('ms-excel:ofe|u|https://some.link.to/a/workbook.xlsx')`

# Provide additional details

Follow up from #2700

## Context

We use office uri scheme links to allow the user to open a workbook / presentation / document in its respective Desktop App. Support for this or a different way to open documents by url would be greatly appreciated. Thank you!

**Comment by JinghuiMS** [comment]
@jargil This issue is a follow-up from https://github.com/OfficeDev/office-js/issues/2700. Could you share more? Thanks!

**Comment by jargil** [comment]
@hbnrmx - the openBrowserWindow API is meant to open a browser window, e.g. Edge. If you want to open something else, try calling, for example window.open('ms-excel:ofe|u|https://some.link.to/a/workbook.xlsx').
