### ISSUE TITLE
Outlook displayNewAppointmentForm displays incorrect date (2032)

### ISSUE THREAD

**Issue by luketowell** [OfficeDev/office-js#2821]
I am currently attempting to create a new appointment form using the `displayNewAppointmentForm` method. I have used the example provided as part of the OfficeAPI documentation however a completely different date is being displayed in the created Appointment.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.64
* Operating System: Monterey
* Browser (if using Office on the web): N/A
 
## Expected behavior
I would expect that the date fields of the appointment would be populated with the correct date e.g. new Date() and new Date() + 1 hour.

```
const createMeeting = () => {
    const now = new Date();
    const end = new Date();
    end.setHours(now.getHours() + 1);
    const start = Office.context.mailbox.convertToLocalClientTime(now);
    const endUtc = Office.context.mailbox.convertToLocalClientTime(end);

    console.log(`start: ${JSON.stringify(start)}`);
    console.log(`end:`, endUtc);
    console.log(`start UTC client time : `, Office.context.mailbox.convertToUtcClientTime(start));
    console.log(`end UTC client time : `, Office.context.mailbox.convertToUtcClientTime(endUtc));
    Office.context.mailbox.displayNewAppointmentForm({
      subject: 'new appointment',
      body: generateBody({ meetingUrl: 'https://www.google.com' }),
      start: Office.context.mailbox.convertToUtcClientTime(start),
      end: Office.context.mailbox.convertToUtcClientTime(endUtc),
      requiredAttendees: [],
      optionalAttendees: [],
      location: 'online appointment',
      resources: [],
    });
  };
```

## Current behavior
The date is populated with the date of 18/11/2032 and a time of 04:23 to 04:23

<img width="920" alt="Screenshot 2022-09-07 at 16 28 03" src="https://user-images.githubusercontent.com/29888913/188922977-b41d159f-9a8b-4cd8-9903-567038cf63da.png">

## Steps to reproduce

1. You can recreate using this example available [here](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-preview#outlook-office-mailbox-displaynewappointmentform-member(1))
2. You can also recreate using this code snippet:
`Office.context.mailbox.displayNewAppointmentForm({ } as Office.AppointmentForm);`

# Provide additional details

1. This bug has already been documented in this [issue](https://github.com/OfficeDev/office-js/issues/2393) however it has been stagnant since February.

## Context
I am currently attempting to create an outlook plugin which will enable customers to create appointment invitations for potential clients and team members.

## Useful logs
These logs display the dates that are being correctly generated and passed into the `displayNewAppointmentForm` however they are not being displayed.

<img width="740" alt="Screenshot 2022-09-07 at 16 28 22" src="https://user-images.githubusercontent.com/29888913/188924764-4ffc3c8a-a096-48ce-bf67-ff04b1e1c1cb.png">

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding displayNewAppointmentForm. It has been put on our backlog. We, unfortunately, have no timelines to share at this point 
 
Internal tracking id: Office: 6624834

**Comment by exextoc** [comment]
This issue has been fixed.
