### ISSUE TITLE
How to get ListObjects of one WorkSheet in office-js?

### ISSUE THREAD

**Issue by cysnet** [OfficeDev/office-js#2823]
I could get ListObjects of one WorkSheet in VSTO. But how to get ListObjects in office-js?

VSTO Code as below:
```
Worksheet worksheet = (Worksheet)obj;
var objects = worksheet.ListObjects;
```

**Comment by JinghuiMS** [comment]
@cysnet 
Thanks for reaching us.
We don't support worksheet.ListObjects currently. BTW, you can use `context.workbook.tables.getItem(tableName) ` please refer to https://docs.microsoft.com/en-us/javascript/api/excel/excel.tablecollection?view=excel-js-preview#excel-excel-tablecollection-getitem-member(1). If this API can't unblock your scenario, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.

**Comment by cysnet** [comment]
Hi @JinghuiMS , thanks for you reponse! do you mean that I can get the same information as listobjects in VSTO via `context.workbook.tables.getItem(tableName)` in officejs?

**Comment by JinghuiMS** [comment]
The APIs supported by officejs are all in this document: https://docs.microsoft.com/en-us/javascript/api/excel/excel.tablecollection?view=excel-js-preview#excel-excel-tablecollection-getitem-member(1). Please check it as you needed.

**Comment by cysnet** [comment]
> The APIs supported by officejs are all in this document: https://docs.microsoft.com/en-us/javascript/api/excel/excel.tablecollection?view=excel-js-preview#excel-excel-tablecollection-getitem-member(1). Please check it as you needed.

Hi @JinghuiMS , another similar question, how to find objects in office-js that have the same functionality as XMLMaps in VSTO

VSTO code as below,
```
var maprs = excelApp.ActiveWorkbook.XmlMaps;
```

**Comment by JinghuiMS** [comment]
I afraid we don't have the similar api, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.
