### ISSUE TITLE
Setting and getting `Range.numberFormat` for a date format gives inconsistent results in Excel in Office for the web

### ISSUE THREAD

**Issue by Rinzwind** [OfficeDev/office-js#2824]
The Script Lab snippet included below gives different results, depending on which user account I use, in Excel in Office for the web. Using one account, the result is as expected:

<img width="351" alt="1" src="https://user-images.githubusercontent.com/1611248/189134200-732f6844-c75f-4567-ad34-8257d6b8b70a.png">

Using another account, the result is as follows, note the difference w.r.t. the `numberFormat` in the second column, and the `text` in the first column:

<img width="350" alt="2" src="https://user-images.githubusercontent.com/1611248/189134264-e20c4e35-5156-4cc5-bebd-8f2a3d433041.png">

Presumably, this is related to a difference in some localization setting between the two accounts. But as the snippet uses `numberFormat`, and not `numberFormatLocal`, is it not the case that the results should still be the same?

**Version info:** Office for the web using Chrome 105.0.5195.102 on macOS 11.6.8

**Script Lab Snippet:**
```
name: Date Range.numberFormat Issue Example
description: ''
host: EXCEL
api_set: {}
script:
  content: |
    Excel.run(async (context) => {
      const worksheet = context.workbook.worksheets.getActiveWorksheet();
      const range = worksheet.getRange("A1:C1");
      (range.numberFormat as any) = [["dd/mm/yyyy", "dd-mm-yyyy", "dd.mm.yyyy"]];
      (range.values as any) = 401800;
      await context.sync();
      range.load(["numberFormat", "text"]);
      await context.sync();
      console.log('numberFormat', range.numberFormat[0]);
      console.log('text', range.text[0]);
    });
  language: typescript
template:
  content: ''
  language: html
style:
  content: ''
  language: css
libraries: |
  https://appsforoffice.microsoft.com/lib/1/hosted/office.js
  @types/office-js

  core-js@2.4.1/client/core.min.js
  @types/core-js
```

**Comment by JinghuiMS** [comment]
@Rinzwind 
Thanks for reaching us.
I can't repo the issue as your second dialog shown, It's definitely not right to have this error, could you provide more information about these two accounts to help us repro it? Such as the locale info of your PC, the locale info of your online file.

**Comment by Rinzwind** [comment]
Thank you for confirming it’s unexpected behavior. I tried the snippet again using just the first account, while changing the locale setting of the file. When it is set to “Dutch (Belgium)”, I get the expected result:

<img width="500" src="https://user-images.githubusercontent.com/1611248/189846441-74a9271a-5d40-41a6-890e-3b0907fe0938.png">

When I change the locale setting of the file to “Dutch (standard)”, I get the unexpected result:

<img width="500" src="https://user-images.githubusercontent.com/1611248/189846507-844fa1c7-ac57-45de-82fa-acb315b3ef67.png">

The locale settings of the account are as follows, I didn’t change these:

<img width="500" src="https://user-images.githubusercontent.com/1611248/189846558-219773b3-9407-40e4-8be1-a1a880831b36.png">

**Comment by JinghuiMS** [comment]
Thanks for providing the information. I can repro this issue locally when change the regional setting from "Dutch (Belgium)" to "Dutch (Netherlands)". It has been put on our backlog<ADO#6671653> for internal track. We will keep track of this issue and let you know if there are any updates.

**Comment by ruijiaMS** [comment]
Hi @Rinzwind,
can you please have a try with this numberFormatLocal api? Excel provides this api which represents Excel's number format code for the given range, based on the language settings of the user.
```
async function run() {
  await Excel.run(async (context) => {
    const worksheet = context.workbook.worksheets.getActiveWorksheet();
    const range = worksheet.getRange("A1:C1");
    (range.numberFormatLocal as any) = [["dd/mm/yyyy", "dd-mm-yyyy", "dd.mm.yyyy"]];
    (range.values as any) = 401800;
    await context.sync();
    range.load(["numberFormat", "text", "numberFormatLocal"]);
    await context.sync();
    console.log("numberFormatLocal", range.numberFormatLocal);
    //console.log("numberFormat", range.numberFormat[0]);
    console.log("text", range.text[0]);
  });
}
```
a reference here: https://learn.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#excel-excel-range-numberformatlocal-member
Hope this helped!

**Comment by XuanZhouMSFT** [comment]
Thanks for reporting this issue. After careful consideration, our team has decided to not fix this issue in the short term. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.
