### ISSUE TITLE
What is corresponding method for VBA Table.AllowAutoFit For Word

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/office-js#2825]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

In Word Desktop version, I can disable Word auto fit by vba like below:

```
Sub DisableResizeTableCells()
    Dim meekouTable As Table
    Set meekouTable = Selection.Tables(1)
    meekouTable.AllowAutoFit = False
    meekouTable.Rows.HeightRule = wdRowHeightExactly
    meekouTable.Rows.Height = CentimetersToPoints(5)
End Sub

```
How to achieve the same function through Office Javascript Word api?

**Comment by richard6094** [comment]
Hi Edward! Your issue has been under our investigation.

**Comment by JinghuiMS** [comment]
@Edward-Zhou 
Thanks for reaching us.
Currently, we support autoFitWindow() API, please refer to [autoFitWindow()](https://docs.microsoft.com/en-us/javascript/api/word/word.table?view=word-js-preview#word-word-table-autofitwindow-member(1))
If this API can't meet your requirement, we we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.
