### ISSUE TITLE
Unable to call /replyAll API method with callback token from Outlook for Android

### ISSUE THREAD

**Issue by onestep** [OfficeDev/office-js#2828]
Token retrieved with `getCallbackTokenAsync()` on Outlook for Android is not accepted by REST API /replyAll method.

## Environment
* Platform: Outlook for Android
* Host: Outlook
* Operating System: Android
 
## Expected behavior
According to [OfficeJS documentation](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-preview#outlook-office-mailbox-getcallbacktokenasync-member(1)) callback token should have the `mail.send` scope, and therefore be sufficient to send a reply.

## Current behavior
When trying to call https://outlook.office365.com/api/v2.0/messages/_id_/replyAll with token retrieved using `getCallbackTokenAsync()` on Outlook for Android, we are getting the response with status code 403 and the following payload:
```{"error":{"code":"ErrorAccessDenied","message":"The api you are trying to access does not support item scoped OAuth."}}```

## Steps to reproduce
1. On Outlook for Android use `Office.context.mailbox.getCallbackTokenAsync()` to get a token;
2. Use this token to call https://outlook.office365.com/api/v2.0/messages/_id_/replyAll with some comment;
3. Observe the aforementioned error.

Please note that token retrieved from Office365 with `isRest: true` works fine with /replyAll endpoint.

## Context
We need to send a reply to the selected message from our add-in on mobile platforms, where `displayReplyAllForm` is not supported.

**Comment by exextoc** [comment]
Hi @onestep, thanks for reporting the issue. From the description, we are unclear about the use case and the working status of the API.

Can you please be more elaborate on the problem and the use case so that we can understand the problem better?

**Comment by onestep** [comment]
Works fine when token is requested with `isRest: true` on Android, closing.
