### ISSUE TITLE
clear() fails on the web

### ISSUE THREAD

**Issue by benjamin-almarza** [OfficeDev/office-js#2829]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: Windows 10 Pro for Workstations 21H2
* Browser (if using Office on the web): Chrome Version 105.0.5195.102 (Official Build) (64-bit)
 
## Expected behavior

We expect to be able to clean all the content of file in web.

## Current behavior

Cleaning the content in a document produces an error. "RichApi.Error: The action isn’t supported by Word in a browse"

## Steps to reproduce

In the addin, in the web context run the following code:

```js
await Word.run(function (context) {
  var sections = context.document.sections;
  sections.load();
  return context
    .sync()
    .then(() => {
      context.sync();

      sections.items.forEach(function (section) {
        section.body.clear();
        section.getHeader(Word.HeaderFooterType.primary).clear();
        section.getHeader(Word.HeaderFooterType.evenPages).clear();
        section.getHeader(Word.HeaderFooterType.firstPage).clear();

        section.getFooter(Word.HeaderFooterType.primary).clear();
        section.getFooter(Word.HeaderFooterType.evenPages).clear();
        section.getFooter(Word.HeaderFooterType.firstPage).clear();
      });
      
       return context.sync();
    })
    .catch(function (error) {
      if (error instanceof window.OfficeExtension.Error) {
        console.log("Debug info: " + JSON.stringify(error.debugInfo));
      }
    });
});
```

This throw an error in web.

In Desktop, it cleans the document without any problem.

We also tried with:

```js
context.document.body.clear();
```
And we have exactly the same behaviour, failing in web and working in desktop.

## Context

We have a library of documents,  the user should be able to choose a document from the web and replace the content of the current document. To do that we first erase the content of the document, then we pull the content from the web and then we insert it

For doing that we rely on erasing everything from the document and that doesn't work on the web. 

In the documentation, it doesn't say anything about this functionality not working on the web. [body.clear documentation](https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#word-word-body-clear-member(1))

## Useful logs

- [ ] Console errors

```
Uncaught (in promise) RichApi.Error: The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information.
    at new n (word-web-16.00.js:25:324636)
    at o.processRequestExecutorResponseMessage (word-web-16.00.js:25:388802)
    at word-web-16.00.js:25:386865
n @ word-web-16.00.js:25
o.processRequestExecutorResponseMessage @ word-web-16.00.js:25
(anonymous) @ word-web-16.00.js:25
Promise.then (async)
o.sync @ word-web-16.00.js:25
(anonymous) @ SimpleTest.tsx:12
Promise.then (async)
(anonymous) @ SimpleTest.tsx:11
(anonymous) @ word-web-16.00.js:25
Promise.then (async)
o._runCommon @ word-web-16.00.js:25
o._runBatchCommon @ word-web-16.00.js:25
o._runBatch @ word-web-16.00.js:25
e.run @ word-web-16.00.js:25
(anonymous) @ SimpleTest.tsx:6
step @ ShowHideContentControlTest.tsx:33
(anonymous) @ ShowHideContentControlTest.tsx:33
(anonymous) @ ShowHideContentControlTest.tsx:33
initializePromise @ es6-promise.js:437
Promise @ es6-promise.js:865
__webpack_modules__../test/components/items/SimpleTest.tsx.__awaiter @ ShowHideContentControlTest.tsx:33
onSubmitFunction @ SimpleTest.tsx:5
(anonymous) @ Button.js:107
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:306
executeDispatch @ react-dom.development.js:389
executeDispatchesInOrder @ react-dom.development.js:414
executeDispatchesAndRelease @ react-dom.development.js:3278
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:3287
forEachAccumulated @ react-dom.development.js:3259
runEventsInBatch @ react-dom.development.js:3304
runExtractedPluginEventsInBatch @ react-dom.development.js:3514
handleTopLevel @ react-dom.development.js:3558
batchedEventUpdates$1 @ react-dom.development.js:21871
batchedEventUpdates @ react-dom.development.js:795
dispatchEventForLegacyPluginEventSystem @ react-dom.development.js:3568
attemptToDispatchEvent @ react-dom.development.js:4267
dispatchEvent @ react-dom.development.js:4189
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
discreteUpdates$1 @ react-dom.development.js:21887
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
Show 12 more frames

```

**Comment by xiruatms** [comment]
@benjamin-almarza , thanks for reporting this to us.

But unfortunately, I can't repro this in my local environment. If possible, will you please share your documents (without sensitive data inside) so that I can take a try?

**Comment by benjamin-almarza** [comment]
Hi, I just tested and you are right it works in an empty file

In the gif you can see how it cleaned a newly created file, but it failed to clean our file:

![Animation](https://user-images.githubusercontent.com/51302934/189848073-579b8de8-83bf-48f9-b32b-ad3cbe08454f.gif)


Please use this file to test:
[file_example.docx](https://github.com/OfficeDev/office-js/files/9554814/file_example.docx)

**Comment by xiruatms** [comment]
@benjamin-almarza , thanks for providing the sample file. I can repro it now.

According to the investigation, it should be a by-design behavior. I can learn from the sample file that, there're multiple content controls in the file, and most of them are marked as "Content control cannot be deleted" as shown in the following screenshot

![image](https://user-images.githubusercontent.com/40648203/190062934-490cc659-7895-41bf-80c8-56765fa81acb.png)

In this case, when you call *.clear() API to try to clear contents containing those content controls, there will be a NotAllowed Exception thrown. This is an expected result.

I've taken a try to uncheck "Content control cannot be deleted", body.clear() works.

Please help to take a try and let me know whether it works in your case.

**Comment by benjamin-almarza** [comment]
I will try removing those "no delete" from the content controls and check if I can clean the document.

**Comment by benjamin-almarza** [comment]
We did the change you suggested and now we set all the contentControls to "cannotDelete" to false before deleting.

```js
await Word.run(function (context) {
  const sections = context.document.sections;
  context.load(sections, "tag");

  const contentControls = context.document.contentControls;
  context.load(contentControls, "tag");
  await context.sync();

  const contentControlCollection = contentControls.items.filter((item) => !item.isNullObject);

  contentControlCollection.forEach((contentControl) => {
    contentControl.cannotDelete = false;
  });

  await context.sync();
  console.log(`length: ${contentControls.items.length}`);
  sections.items.forEach(function (section) {
    section.body.clear();

    [Word.HeaderFooterType.primary, Word.HeaderFooterType.evenPages, Word.HeaderFooterType.firstPage].forEach(
      (headerFooterType) => {
        section.getHeader(headerFooterType).clear();
        section.getFooter(headerFooterType).clear();
      }
    );
  });

  await context.sync();
});
```
We tested in files with some content control as cannotdelete, and the script is able to remove that lock. It works fine both in desktop and web but not in all files. 
[success_file.docx](https://github.com/OfficeDev/office-js/files/9571400/success_file.docx)

For example, if we run that script in this file it fails: 
[fail_file.docx](https://github.com/OfficeDev/office-js/files/9571294/fail_file.docx)

I figured it out that in that file the length of contentControls is zero. The console.log returns "length: 0". 
In the success case it returns "length: 148". 

For some reason in "fail_file.docx" it cannot list the content controls.

**Comment by xiruatms** [comment]
@benjamin-almarza , thanks for taking such a try.

For your questions regarding the current failure, that's a little different. As I checked in [fail_file.docx](https://github.com/OfficeDev/office-js/files/9571294/fail_file.docx), there're multiple PlainText contentcontrols.  But as specified here: https://docs.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview
    **Currently, only rich text content controls are supported.**

In this case, you can't list those PlainText content controls with API Document.ContentControls. That's why "length:0" was returned.

**Comment by benjamin-almarza** [comment]
Ok, thanks you very much
