### ISSUE TITLE
Lacking documentation of Add-In <-> Word Client communication

### ISSUE THREAD

**Issue by phlppnhllngr** [OfficeDev/office-js#283]
As I understand, the Add-In runs in an embedded Internet Explorer. Normally Browsers are sandboxed and can't communicate with desktop applications. Looking at the source code, it seems to me that the WebExtensions API is being used. Googling that API only brings up Firefox and Chrome though. I feel the documentation should share a few details about how the communication between Browser and Host-Client works.

**Comment by sancarn** [comment]
This has been well documented before in numerous other articles outside of the office add-in environment. In short though:

* Internet explorer can be used as an ActiveX control to any Win32 application. 
* Via the Internet Explorer COM API, you can access the `document` and `document.parentWindow` objects which relate directly to the `document` and `window` objects within JavaScript.
* If Internet Explorer has a registered javascript function e.g.
```js
function registerKey(key,value){
   window[key]=value;
}
```
Then a host application can register it's own functions to the Internet Explorer's JavaScript environment:
```cpp
ie.document.parentWindow.registerKey("myCoolFunction",*myCoolFunction)
```

----

However I doubt office uses the Internet Explorer interface to be honest. The IE interface is virtually deprecated. I assume they use the new [WinRT WebView control](https://blogs.windows.com/msedgedev/2018/05/09/modern-webview-winforms-wpf-apps/) as this is multiplatform and builds of Microsoft Edge.

If so, I suspect it uses the [`AddWebAllowedObject()` method](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.webview.addweballowedobject) of the WebView class to register back-forward communication between an Office C# and JavaScript

Bare in mind though that these are all hypothesis and I do not represent Microsoft. But the information should be sufficient for building your own similar application if wanted.
