### ISSUE TITLE
Table selection not working properly in Word office-js

### ISSUE THREAD

**Issue by jimmydevine** [OfficeDev/office-js#2835]
Using Script Lab 1.5.0.0 from within Microsoft® Word for Microsoft 365 MSO (Version 2205 Build 16.0.15225.20394) 64-bit.

Select Basic API call (JavaScript) from the sample list

```
HTML:
<section class="ms-font-m">
    This sample executes a code snippet that prints the selected text to the console. Make sure to enter and select text before clicking "Print selection".
</section>
<button id="run" class="ms-Button">
    <span class="ms-Button-label">Print selection</span>
</button>

JavaScript:
$("#run").click(() => tryCatch(run));

function run() {
  return Word.run(function(context) {
    var range = context.document.getSelection();
    range.font.color = "red";
    range.load("text");

    return context.sync().then(function() {
      console.log('The selected text was "' + range.text + '".');
    });
  });
}

/** Default helper for invoking an action and handling errors. */
function tryCatch(callback) {
  Promise.resolve()
    .then(callback)
    .catch(function(error) {
      // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
      console.error(error);
    });
}
```

If I create a multi-row table and try to select multiple rows from within that table, choosing "Print selection" only prints the bottom row selected, independent of the row selection order.  If my selection includes content outside of the table, I see the full content of the selection within the table as well as the selection outside the table (as expected).

I would expect selections which only include rows within the table to print all rows selected in the table, not just the bottom row.

**Comment by jipyua** [comment]
hi @jimmydevine Thanks for reporting this. Unfortunately, this is a known by-design issue. This is because in Word if you select a table column, actually it's a discontinues selection, each of the table cell in this column is a standalone selection part. Most probably we need to provide a new API called something like document.getSelections() to return a range collection for this kind of discontinues selection. Also, we track this kind of API request on our [Microsoft 365 Developer Platform Ideas Forum]( https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. Thanks.

**Comment by jimmydevine** [comment]
@jipyua does this apply if you select entire rows?  I did find posts in the issues list that spoke to columns but since I was selecting rows that did not seem to apply.  I see that if I try to select only specific columns and move my selection beyond the table (which is the working scenario), it does force the selection to be full row selection, so perhaps selections that include both table and non-table content are a special case (or rather, perhaps the table only selection is a special case).

**Comment by jipyua** [comment]
if you select entire rows, then it's a continuous selection and you can get all the content of your selection. When table-related content is selected, inspect your selection from left to right, if some cells are not selected, then it's a discontinuous selection.

**Comment by jimmydevine** [comment]
OK, this is the scenario that I'm calling out then as I am selecting entire rows but I only get back the content for the last row

![image](https://user-images.githubusercontent.com/19355989/191068288-a5ebf64d-40ab-496e-90e5-5d9d05ace674.png)
