### ISSUE TITLE
Excel Addin crashes when search text with CTRL F in Office dialog API

### ISSUE THREAD

**Issue by gustavo-torr3s** [OfficeDev/office-js#2836]
* Platform: PC
* Host: Excel
* Office version number: 2208 build 15601.20148
* Operating System: Windows 11 Pro 21H2 22000.856
 
## Expected behavior
Search for texts without crashes after closing an office dialog window

## Current behavior
Searching for texts causes crashes and reloads and random clicks after the dialog windows is closed

## Steps to reproduce
1. Open office dialog
2. Open the search (CTRL F) and search any text
3. Close the office dialog

## Link to live example:
In this example, I used the Excel Power Automate... use any add-in (ao inves  de suplements) that  implements
[Video](https://drive.google.com/file/d/1UlurcRYI7g_g_vyY975gh9NeN6gfisZ0/view?usp=sharing)

**Comment by Dengshan2018** [comment]
@gustavo-torr3s , are you still reproing the issue?

**Comment by Dengshan2018** [comment]
Close as Not Repro.
