### ISSUE TITLE
How to keep the mouse cursor in the default state?

### ISSUE THREAD

**Issue by woai3c** [OfficeDev/office-js#2837]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When I listen to the change of slide index, the mouse cursor will keep rotating because I keep calling `Office. context.document GetSelectedDataAsync()` Method. Is there a way to stop the mouse cursor change.

![demo](https://user-images.githubusercontent.com/22117876/190320290-b4e806d2-a27e-4068-8d1c-138a24e73ad2.gif)

This is the complete code:
```ts
import eventBus from '@/utils/EventBus';
import { getSelectedSlideIndex } from './fileUtils';

let timer: NodeJS.Timeout;
export function monitorSlideChange() {
  if (timer) return;
  timer = setInterval(() => {
    getSelectedSlideIndex().then((index) => eventBus.emit('slideChange', index));
  }, 500);
}

export function stop() {
  clearInterval(timer);
}
```

**Comment by xuruiyao-msft** [comment]
@woai3c would you please provide more code details about how the "Office. context.document GetSelectedDataAsync()" is used in this case?
How does the method getSelectedSlideIndex implemented?

**Comment by woai3c** [comment]
> getSelectedSlideIndex

@xuruiyao-msft ok, this is `getSelectedSlideIndex()` code:
```js
export function getSelectedSlideIndex() {
  return new Promise<number>((resolve, reject) => {
    Office.context.document.getSelectedDataAsync(
      Office.CoercionType.SlideRange,
      (asyncResult: Office.AsyncResult<SelectedSlides>) => {
        try {
          if (asyncResult.status === Office.AsyncResultStatus.Failed) {
            reject(asyncResult.error.message);
          } else {
            // 索引是从 1 开始的，但是数组访问是从 0 开始的，所以要减 1
            resolve(asyncResult.value.slides[0].index - 1);
          }
        } catch (error) {
          reject(error);
        }
      }
    );
  });
}
```

**Comment by xuruiyao-msft** [comment]
@woai3c Hi I don't find any errors in the Code about the APIs. The mouse cursor changing is by design.

**Comment by woai3c** [comment]
> @woai3c Hi I don't find any errors in the Code about the APIs. The mouse cursor changing is by design.

Thank you for your replay! Are there any methods to change the mouse cursor or prohibit the mouse cursor from changing?

**Comment by rwambacq** [comment]
@xuruiyao-msft @JinghuiMS I'm running into this issue as well.
I'm creating an add-in that listens to changes in the document context with `Office.context.document.getSelectedDataAsync` and `Office.context.document.getFilePropertiesAsync`. These both change the cursor to a loading state on Office applications on Windows.
Using the add-in right now makes it very difficult to work with any Office application.
This behaviour doesn't happen on Office applications on MacOS or on Office for the web, it would be nice if this were consistent on all platforms.

**Comment by FredericTorrekens** [comment]
@xuruiyao-msft @JinghuiMS @michelleranmsft I am encountering this cursor issue aswel. It is identical to @rwambacq's issue. Any feedback on his comment would help me aswel.

**Comment by CaptainTammy** [comment]
@xuruiyao-msft @JinghuiMS @michelleranmsft 
I know this case is closed but, I am encountering this cursor issue as well. Have anyone found a workaround or a way to prohibit the spinning wheel (waiting cursor)? 
It is identical to @rwambacq's issue, but it only keeps spinning in Powerpoint and Outlook and not for Word or Excel. The only way to get rid of the wait cursor is quitting Powerpoint.

> @woai3c Hi I don't find any errors in the Code about the APIs. The mouse cursor changing is by design.

Can it be there is a problem releasing the wait cursor at some point?
