### ISSUE TITLE
How to create an email from a function file

### ISSUE THREAD

**Issue by JanTrichter** [OfficeDev/office-js#2838]
Hello there,
I have a project in which I spawn a dialog from a function file when clicking a ribbon:
```js
/**
 * This function bootstraps the dialog window on ribbon click
 */
function action() {
  let dialog;

  let param = getParam(window, "param");
  Office.context.ui.displayDialogAsync(
    `${process.env.HOST}dialog.html?param=${param}`,
    {
      height: 90,
      width: 50,
    },
    function (asyncResult) {
      dialog = asyncResult.value;
      dialog.addEventHandler(Office.EventType.DialogMessageReceived, sendEmail);
    }
  );
}
```

I complete a multi-step form with several fetches to endpoints in the dialog and send the data from the forms via `Office.context.ui.messageParent(JSON.stringify(emailDetails));` back to the function file. The function file which then calls the `sendEmail` function which should compose a new email. At least that's the plan.

The Problem is that As soon as I click the Ribbon, the asyncResult completes and nothing happens. I also have no way to debug this since `console.log` doesn't work here.

Any idea how I can send data from my dialog to a function file which will then compose an email with the information send down from the dialog?

**Comment by Rick-Kirkham** [comment]
For debugging function commands, see https://docs.microsoft.com/office/dev/add-ins/testing/debug-add-ins-overview#special-cases
