### ISSUE TITLE
Bug that prevents document from updating after inserting OpenXML using JS api in Office Online in cloud storage partner program

### ISSUE THREAD

**Issue by stowellt** [OfficeDev/office-js#2840]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web from cloud storage partner program
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.15714.41022
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Inserting OpenXML should show the newly inserted content

## Current behavior
The OpenXML is inserted, but nothing appears in the UI until I refresh the page

## Steps to reproduce
1. use the insertOoxml() function to insert an image
2. No image appears in the content until the page is reloaded

## Context
In November 2017, Tom Jebo gave an answer as to why when using the Office JS api to insert OpenXML into a document in Office Online, nothing appears until the page is reloaded:

https://social.msdn.microsoft.com/Forums/en-US/671a4649-8566-4413-8eb9-dcd016635583/document-not-visually-updating-when-inserting-openxml-into-office-online-word-document?forum=os_office

Here is a portion of the answer:

"The current design of InsertOoxml() in Officejs is that it only detects changes in hosts that support Cobalt. This is why the rendering does not change immediately when after the call to this API. After the auto-save functionality (subsequent Putfile) engages the wopi host, the new data will be rendered but if another edit from the UI occurs, this will preempt the InsertOoxml() edit which will be lost. The Officejs team has logged this as a bug and will consider whether to include this as a design change in a future update."

There are no PutFile Wopi requests made until after the user reloads the browser, so the autosave functionality doesn't show the updated document at any point until the user reloads the page.

**Comment by aeturneus** [comment]
@JinghuiMS any update on this one or prospect of resolution? Is there a bug # assigned?

**Comment by xiruatms** [comment]
@aeturneus , thanks for checking. We do have experts actively working on this. A PR was sent out for review, no blocking issues. We'll follow necessary internal process and move forward asap.

**Comment by xiruatms** [comment]
@aeturneus , we've pushed the latest version to production, will you please help to check whether it's working for you now?

**Comment by stowellt** [comment]
I just tested this using script lab to insert some OpenXML. It seemed to work once, but when I tried a second time I saw this loading popup and eventually it timed out:
![image](https://github.com/OfficeDev/office-js/assets/19392630/c3a93ef4-2ae4-4836-b153-ae6ef7ee2356)

Eventually there was the error: "API Call Failed: The call took too long to execute."

**Comment by xiruatms** [comment]
@stowellt , thanks for taking a try. will you please share more details about the verification? What OOXml are you using? what environment are you verifying (Sharepoint, OneDrive, WOPI...)? That'll help us to understand your case.

**Comment by stowellt** [comment]
I'm using the WOPI environment. I used this sample XML code:

`<pkg:package xmlns:pkg="http://schemas.microsoft.com/office/2006/xmlPackage">
  <pkg:part pkg:name="/_rels/.rels" pkg:contentType="application/vnd.openxmlformats-package.relationships+xml" pkg:padding="512">
    <pkg:xmlData>
      <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
        <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>
      </Relationships>
    </pkg:xmlData>
  </pkg:part>
  <pkg:part pkg:name="/word/document.xml" pkg:contentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml">
    <pkg:xmlData>
      <w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" >
        <w:body>
          <w:p>
            <w:pPr>
              <w:spacing w:before="360" w:after="0" w:line="480" w:lineRule="auto"/>
              <w:rPr>
                <w:color w:val="70AD47" w:themeColor="accent6"/>
                <w:sz w:val="28"/>
              </w:rPr>
            </w:pPr>
            <w:r>
              <w:rPr>
                <w:color w:val="70AD47" w:themeColor="accent6"/>
                <w:sz w:val="28"/>
              </w:rPr>
              <w:t>This text has formatting directly applied to achieve its font size, color, line spacing, and paragraph spacing.</w:t>
            </w:r>
          </w:p>
        </w:body>
      </w:document>
    </pkg:xmlData>
  </pkg:part>
</pkg:package>`

**Comment by xiruatms** [comment]
@stowellt , thanks for the details. I've taken a try with your XML code, but didn't repro the issue you mentioned. It works well in my testing environment. Are you still encountering this consistently? Will you please share the whole code snippet you used? If possible, can you grant me the access to your WOPI environment?

To protect the sensitive information, you can submit the WOPI Url, username/password here: https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR9NvrlmrippKsMvh4kTM325URVZMWjYyQTVOTVNLTUo5VzFRTTcyNU1RSy4u

**Comment by stowellt** [comment]
Sorry for the delay, please re-open this issue as I'm still seeing the error. Here are the following steps to replicate in my WOPI environment:

- I used Script Lab running locally (clone from Github then run "npm run start" in a terminal)
- Go to the URL in the form  (also I saved the username and password in the form provided)
- On the Home > Add-ins menu click "+ More Add-ins"
- Click ADMIN MANAGED
- Click "Upload My Add-in"
-  Click "Browse"
- select script-lab\manifests\script-lab-react-localhost.xml
- Next Click the "Code" button
- Paste the following code:
[script lab code sample.txt](https://github.com/user-attachments/files/15916104/script.lab.code.sample.txt)
- Click "Run", then click the Run button in the add-in
- In both the fast food and production environments I see a "Waiting" modal, then either nothing happens, or it times out

**Comment by xiruatms** [comment]
Thanks, @stowellt . I confirm I can repro your issue there. My further question is that: is this happen with any document (Or a newly created document)? I can't repro with other WOPI instance, that's why I'm asking whether this is a common case in your WOPI instance.  It seems a different issue from the original one. Feel free to create another GitHub issue so that we can track more efficiently.

**Comment by aeturneus** [comment]
@xiruatms we're also seeing insertOoxml fail in WOPI, again, after it was working for a while. The error message is:

`Uncaught (in promise) RichApi.Error: The action isn't supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information.
    at new n (word-web-16.00.js:25:340817)
    at o.processRequestExecutorResponseMessage (word-web-16.00.js:25:405264)
    at word-web-16.00.js:25:403327
    at async t.default.unlockContentControls (taskpane.js:393:427752)`

The full statement is:

`{
    "code": "NotAllowed",
    "message": "The action isn't supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information.",
    "errorLocation": "Body.insertOoxml",
    "statement": "var insertOoxml = body.insertOoxml(...);",
    "surroundingStatements": [
        "var root = context.root;",
        "var body = root.body;",
        "// Instantiate {body}",
        "// >>>>>",
        "var insertOoxml = body.insertOoxml(...);",
        "// <<<<<",
        "// Instantiate {insertOoxml}"
    ],
    "fullStatements": [
        "Please enable config.extendedErrorLogging to see full statements."
    ]
}`

The same code works fine in desktop, but fails in WOPI when running with our add-in.

**Comment by stowellt** [comment]
@xiruatms Yes this happens with any document in our WOPI environment. I'm not sure what could be different from my WOPI environment vs the one you are using. Maybe there is something different in the checkFileInfo response that could be making a difference?

**Comment by stowellt** [comment]
I created a new issue here https://github.com/OfficeDev/office-js/issues/4660
