### ISSUE TITLE
getAttachmentContentAsync() fails with internal server error 5001

### ISSUE THREAD

**Issue by sumitmodi01** [OfficeDev/office-js#2842]
# Provide required information needed to triage your issue
getAttachmentContentAsync() call fails intermittently with 5001 error in new outlook UI.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac BigSur 11.4 Outlook App
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook version 16.64 (22081401) New UI
* Operating System: Mac OSX BigSur 11.4

 
## Expected behavior

There should not be any error while calling Office.js api

## Current behavior

getAttachmentContentAsync() fails intermittently with Internal server error 5001. This happens  mostly when we send email with attachments in popped up compose window.

## Steps to reproduce

1. Open outlook app in New UI mode.
2. Compose a new email in popped out window
3. Fill to, cc, body and add attachments

## Context

In our outlook addin, we fetch composed email details and analyse it before sending. Due to attachment api failures, we are not able to analyse attachments and our business use case impacts.

## Useful logs

- [ ] Console errors : {"name":"Internal Error","message":"An internal error has occurred.","code":5001}

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@sumitmodi-lab  We are unable to repro the issue at our end. Can you please share the add-in manifest to OutlookExtensibility@M365x27035562.onmicrosoft.com so that we can debug it better?

And , what is the type of attachment that you have inserted?

**Comment by sumitmodi01** [comment]
I have shared our manifest file over OutlookExtensibility@M365x27035562.onmicrosoft.com
We are also not able to repro this issue now, but want to understand, in what circumstances, this issue may occur and what's the best way to handle this type of issue.

Type of attachment we used was docx file (size ~ 40kb)

**Comment by exextoc** [comment]
You can generate diagnostics log and send us the incident id:
1. Start Outlook on Mac
2. Reproduce the issue
3. Select Collect Diagnostics menu in Help menu
4. Please copy the diagnostics code generated & forward it

**Comment by sumitmodi01** [comment]
Please find below the diagnostic code:
CN9CDQGP

**Comment by exextoc** [comment]
@sumitmodi-lab were you able to repro the issue and the logs are taken after the issue was reproduced?

**Comment by sumitmodi01** [comment]
Yes, issue is reproducible on one of my mac machine, seen same internal server error.

**Comment by exextoc** [comment]
@sumitmodi-lab we are having trouble reproducing this issue. Could you help us understand: 
* How frequently does this reproduce for you?
* Can you please record a video of this happening and share it with us? 
* Alternatively, could you help us by collecting diagnostic logs immediately after the issue occurs. The logs shared do not seem to reflect any issues, so capturing it again may help.

**Comment by sumitmodi01** [comment]
@exextoc I am not able to repro the issue now. My outlook version is upgraded 16.66.
I was consistently able to repro the issue with Outlook 16.64 on mac.

Also, can you please let us know how to handle these types of error.  Doing retry works in such scenarios? 
Our business use case fails if we are unable to get composed message info like subject, body, attachments.

**Comment by exextoc** [comment]
Thank you for communicating on the issue. Unfortunately, we could not repro the error at our end and would need more information to comment on this. Do keep us posted if you face this issue again.

**Comment by Premsagar-lab** [comment]
@exextoc Please reopen this ticket as it is still happening in customer prod environment.
