### ISSUE TITLE
Token for EWS calls in hybrid setups

### ISSUE THREAD

**Issue by plamenbotev** [OfficeDev/office-js#2844]
Hello I have a follow up question to the discussion in https://github.com/OfficeDev/office-js/issues/2740
We have tried to use EWS tokens in our backend obtained from `Office.context.mailbox.getCallbackTokenAsync`.
However we need to be able to work on all messages in the user mailbox and the token, even with permission for ReadWriteMailbox is item scoped. 
We have done some tests with obtaining token using Oauth2 - https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth
My question is will the token for EWS obtained using the method outlined in the above article work on hybrid setups?

Best Regards,
Plamen

**Comment by exextoc** [comment]
Bug 3284720<https://o365exchange.visualstudio.com/DefaultCollection/O365%20Core/_workitems/edit/3284720>: GitHub: Token for EWS calls in hybrid setups #2844

(created manually)

Sachin

**Comment by ztcdsb** [comment]
Hi @plamenbotev, the token should work on hybrid setups. Please let us know if you noticing any issues and we can start from there.
