### ISSUE TITLE
requestCreateControls fails silently in case of invalid JSON schema

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#2847]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I used your example of Contoso add-in https://learn.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs and while playing around with it, replaced "ExecuteFunction" action type with "ExecuteAction" by mistake.

Actual result: no error in console. It just silently fails on `requestCreateControls`, and then a cryptic error is logged upon `requestUpdate` saying that the tab ID is not found.

Expected result: the `requestCreateControls` method should log an error in case the schema data is incorrect. Otherwise this hinders debugging and produces poor dev experience.

**Comment by JinghuiMS** [comment]
@preethikakiru Please help redirect this context menu related issue to correct Eng team for triage. Thanks.

**Comment by wh1t3cAt1k** [comment]
Hey @JinghuiMS @preethikakiru , this has been stuck for a while... Is there any news?

**Comment by wh1t3cAt1k** [comment]
@preethikakiru has there been an update to this?
