### ISSUE TITLE
How to find objects in office-js that have the same functionality as XMLMaps in VSTO

### ISSUE THREAD

**Issue by cysnet** [OfficeDev/office-js#2848]
how to find objects in office-js that have the same functionality as XMLMaps in VSTO.

VSTO code as below:

```
var maps = excelApp.ActiveWorkbook.XmlMaps;
```

**Comment by michelleranmsft** [comment]
Hi @cysnet, thanks for your question! We use Github issues to report bugs with our product or documentation, so for general programming questions, we suggest you go to [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/office-js-dev.html) and see if your question has already been asked or ask a new question. 

Thanks, 
Microsoft 365 Developer Platform team
