### ISSUE TITLE
Unable to get the itemId of the item you are replying/forwarding to in compose mode?

### ISSUE THREAD

**Issue by jlara005** [OfficeDev/office-js#2849]
Hi all,

Is there a way to get the itemId of the item you are replying/forwarding to in compose mode using the Office-JS library? I want to be able to get the itemid of the email or meeting invite that I am replying/forwarding.

V/r,
JP

**Comment by michelleranmsft** [comment]
Hi @jlara005, thanks for your question! We use Github issues to report bugs with our product or documentation, so for general programming questions, we suggest you go to [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/office-js-dev.html) and see if your question has already been asked or ask a new question. 

Thanks, 
Microsoft 365 Developer Platform team
