### ISSUE TITLE
[Excel Online]: synchronous custom functions not working

### ISSUE THREAD

**Issue by ThorstenHans** [OfficeDev/office-js#285]
I've created a new Office Add-in to build a set of custom functions for Excel Online. After sideloading the Add-In to Excel Online I can successfully execute each *async* custom function, but if I try to execute a *sync* functions, Excel Online just prints `#VALUE!` 

I'm using Excel Online as part of Office 365 with build number `16.0.11025.35050` 

Here the implementation of my function:

```
function add(first, second){
 return first + second;
}
```
and here the function mapping:

```
{
    "id": "ADD",
    "name": "ADD",
    "description": "Add two numbers",
    "helpUrl": "http://www.contoso.com",
    "result": {
        "type": "number",
        "dimensionality": "scalar"
    },
    "parameters": [
        {
            "name": "first",
            "description": "first number to add",
            "type": "number",
            "dimensionality": "scalar"
        },
        {
            "name": "second",
            "description": "second number to add",
            "type": "number",
            "dimensionality": "scalar"
        }
    ]
}
```

Unfortunately, the browser's console doesn't give any insights or errors.

**Comment by keyur32** [comment]
Hey @ThorstenHans, I am having trouble repro'ing on my demo account or on Office Online, it maybe I'm not yet on the latest but a few questions to help debug:

a) Can you put a console.log statement and in the add function, and see if that is getting outputted?
b) Does it work if you return the result via a Promise?
c) Likewise, can you try the same function in Excel Online using the ScriptLab add-in (https://aka.ms/trycustomfunctions) and see if that works for you there?

thanks, last if you're having issues, can you

**Comment by ThorstenHans** [comment]
Hey @keyur32 ,

😄 `console.log` was my first intention to see if the custom function was invoked or not. But the browser console doesn't show the custom logs. 

Will try *b* and *c* on Monday

**Comment by Zlatkovsky** [comment]
@ThorstenHans , `console.log` should be able to show up in the F12 tools.  You can also try the `debugger;` statement (with the F12 tools open) to ensure that your code is executing in the first place.
See https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/custom-functions-best-practices.md#debugging for more info

**Comment by ThorstenHans** [comment]
I know that it should but it actually doesn't :D

**Comment by dmahugh** [comment]
Hey Thorsten, just to verify - do you have the CustomFunctionMappings line in your JavaScript code that maps to your function? I.e., this line:

`CustomFunctionMappings.ADD = add;`

**Comment by ThorstenHans** [comment]
@dmahugh sorry for the delay.

Yes the Mapping is defined

**Comment by dmahugh** [comment]
@ThorstenHans are you still experiencing this issue? Sorry for the delay, just noticed this one is still open.

**Comment by keyur32** [comment]
Hi there  I'm closing this issue. We no longer have to declare functions are synchronous/asynchronous. Please refer to https://aka.ms/customfunctions for more information. Thanks!!
