### ISSUE TITLE
[PowerPointApi] changing Textbox wrapWord to true but it does not update on the slide

### ISSUE THREAD

**Issue by Refinitiv-365** [OfficeDev/office-js#2854]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Textbox does not wrap word after set to true

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: 16.0.15709.40505
* Operating System: Windows 10 Pro 20H2 Build 19042.1706
* Browser (if using Office on the web): Microsoft Edge Version 105.0.1343.33 (Official build) (64-bit).
 
## Expected behavior
After set textbox wordWrap to true and sync. textbox update and wrap on PowerPoint

## Current behavior
After set textbox wordWrap to true and sync. It does not update and wrap on PowerPoint
On the left side bar it already wrap to new line, but on the center column it still show line by line
![image](https://user-images.githubusercontent.com/98725157/191407203-c96685cf-c7cd-4c07-8034-0e6450622016.png)

## Steps to reproduce

1. Create Textbox with long text and wordwrap if false
2. call context.sync()
3. Change the Textbox wordwrap to true
4. call context.sync() again
5. Observe Textbox

## Context
I set wordwrap to false to get textbox width 
if width is overflow to outside, set textbox width to current slide width and wrap word to new line

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by JinghuiMS** [comment]
@ononder  Do you have any ideas? Thanks!

**Comment by Lars800** [comment]
Any updates on this?
