### ISSUE TITLE
[PowerPoint] set font in text box

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#2855]
I would like to set the font when addin a new text box in power point.
Is it possible ?

I think it is not since the font property of textRange is readonly cf [readonly font: PowerPoint.ShapeFont;](https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.textrange?view=powerpoint-js-preview#powerpoint-powerpoint-textrange-font-member)

<img width="491" alt="image" src="https://user-images.githubusercontent.com/102920976/191433508-f1c0d422-94a9-4977-80c3-ffbbcd4af67c.png">

**Comment by michelleranmsft** [comment]
Hi @jsoto-gladia, thanks for your question! We use Github issues to report bugs with our product or documentation, so for general programming questions, we suggest you go to [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/office-js-dev.html) and see if your question has already been asked or ask a new question. 

Thanks, 
Microsoft 365 Developer Platform team
