### ISSUE TITLE
[Outlook] CPU usage is too high in outlook for mac(new UI)

### ISSUE THREAD

**Issue by Howard-Song** [OfficeDev/office-js#2856]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:   Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook for mac(new UI) 
* Office version number: 16.65(22091101)
* Operating System:  MacOs Monterey 12.2.1
* Browser (if using Office on the web): ______
 
## Expected behavior

When use setInterval to monitor recipient change and email body change, the CPU usage of outlook client needs to be stable in low percent, and should not affect outlook add-in.

## Current behavior

I set a loop in outlook add-in to get to/cc/bcc/email body in every 300ms(Just to get recipient change and email body change). When the loop start, the CPU of outlook client raise to 80%. After stop the loop, the CPU of outlook client stay below 10%. You can see in the following picture, this will case the add-in became slowness to use.
## Steps to reproduce

1. Here are my test code in script lab, running in to outlook for mac(new UI)
```javascript
$("#run").click(loop);

function loop(){
  window.Office.context.mailbox.item.body.getAsync('html', (result) => {
    console.log(1,result)
    window.Office.context.mailbox.item.to.getAsync((result) => {
      console.log(2,result)
      window.Office.context.mailbox.item.cc.getAsync((result) => {
        console.log(3,result)
        window.Office.context.mailbox.item.bcc.getAsync((result) => {
          console.log(4,result)
          setTimeout(()=>loop(),300)
        })

      })

    })
  })
}

```
2. Open the activity monitor will see the CPU raise to 90%:

## Context

We want to monitor the recipient change and email body change, so that can check the status to give user the correct information.
## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
<img width="962" alt="Screen Shot 2022-09-21 at 17 08 10" src="https://user-images.githubusercontent.com/28775661/191471320-a49e83e2-eb81-45e3-b527-87bfa34c035d.png">
<img width="967" alt="Screen Shot 2022-09-21 at 17 11 13" src="https://user-images.githubusercontent.com/28775661/191471407-98dab74b-4f78-4dc3-86c6-a285fd0c87cf.png">

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Howard-Song** [comment]
Another point:
When I just get body in loop, the CPU usage become 60%-70%.
```javascript
$("#run").click(loop);
function loop() {
  window.Office.context.mailbox.item.body.getAsync("html", (result) => {
    console.log(4, result);
    setTimeout(() => loop(), 300);
  });
}
```
![Screen Shot 2022-09-22 at 10 17 53](https://user-images.githubusercontent.com/28775661/191644091-ed545b3e-4f9d-4a71-add7-1484189d4380.png)
And only get recipient in loop, the CPU usage will below 10%.
```javascript
$("#run").click(loop);
function loop() {
 window.Office.context.mailbox.item.to.getAsync((result) => {
      console.log(2,result)
      window.Office.context.mailbox.item.cc.getAsync((result) => {
        console.log(3,result)
        window.Office.context.mailbox.item.bcc.getAsync((result) => {
          console.log(4,result)
          setTimeout(()=>loop(),300)
        })
      })
    })
}
```
![image](https://user-images.githubusercontent.com/28775661/191644471-c1d11cdd-108e-418f-80ab-bc49730bfe15.png)
It looks like get body will case high CPU usage on outlook for mac(new UI), so is there another way to get body change?

**Comment by exextoc** [comment]
Thanks @JesseHeisenberg for reporting this issue. We are looking into this.

Meanwhile, I wanted to check if you explored using addHandlerAsync() API to register for events such as ItemChanged, RecipientsChanged events. This may be suitable for use case to execute some code whenever recipients change. Let us know if you are looking for any such event triggers. 

Docs: 
(1) https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-1.5&preserve-view=true#outlook-office-mailbox-addhandlerasync-member(1)
(2) https://learn.microsoft.com/en-us/javascript/api/office/office.eventtype?view=common-js-preview

**Comment by Howard-Song** [comment]
Hi @exextoc, I have added some event to monitor such as `attachmentChange`/`itemChange`. But I think there are no other way to get `bodyChange`, so as the sample code above, If I continue to use loop to get bodyChange, the CPU usage issue is still affect normal use.
By the way, thanks for your help.

**Comment by exextoc** [comment]
Yes, currently there is no event for "bodyChange". Can you please tell us your use-case for "bodyChange"? It will help us learn from your scenario and suggest other APIs or plan for improving our API support.

By the way, we are looking into original CPU usage high issue. We don't have any update on this yet. We will keep you posted.

**Comment by Howard-Song** [comment]
@exextoc We may want to handle the links which insert by our add-in, so that when user removed these link in email body, we will remove the inserted status in add-in. So we need to achieve body change event through get body method in every 300 ms.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding high CPU usage. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: [6764176]

**Comment by exextoc** [comment]
Thanks for reporting the issue regarding high CPU usage. According to Microsoft's perspective, the API functions as designed and the use case reported by you is not what the API is designed to handle. Unfortunately, we will not be able to assist you with the same. We will look into improving this experience in our future releases.

Meanwhile, you can avoid using 'body.getAsync()' in loop to circumvent this issue. We request you to also raise a feature request of "bodyChange" by mentioning your use-case for it from our Tech Community Page. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by Howard-Song** [comment]
Hi @exextoc, sorry for the late, it will still cause CPU usage high issue even I called 'body.getAsync()' once and avoid use it in loop. At this moment, user will also get stuck(5s or longer) when using Outlook(not just add-in). Can you find the root cause of this issue? And it just happened in Outlook for Mac. We hope our product can keep the same behavior in all platform, and I hope we can build Office-JS better.

**Comment by exextoc** [comment]
We are not able to repro the issue when we call body.getAsync() only once. Can you please help with the code snippet with what you are trying?

**Comment by Howard-Song** [comment]
Sorry for that, I can't reproduce now. Looks like something changed, but I really get stuck when call body.getAsync() only once. Now it just take 200-400ms and can not affect CPU usage. Hope there will be a bodyChange event to replace the loop in the future. Thanks for your help.
