### ISSUE TITLE
[Outlook] Clicks on the Add-in menu buttons are not working

### ISSUE THREAD

**Issue by dmitry-semenov** [OfficeDev/office-js#2857]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook Web and Desktop
* Office version number: 
![image](https://user-images.githubusercontent.com/17027799/191506809-3ccfc87b-17b8-4434-bd2d-e795469932b8.png)
* Operating System: Mac
* Browser (if using Office on the web): 
![image](https://user-images.githubusercontent.com/17027799/191506871-63e3a749-7d6c-4dfc-9349-aa50f1d124b8.png)

 
## Expected behavior

When we click on the Salesloft add-in through the toolbar or the app launcher we should see the following menu of options.
![image](https://user-images.githubusercontent.com/17027799/191507250-8d8ac680-1abc-4118-9313-a8dc6dcebbfb.png)

## Current behavior

When we click on the SalesLoft add-in either from the quick access toolbar or the app launcher nothing happens.

### Scenario 1: Email

1. Go to Outlook on Chrome/Web or desktop.
2. Create a new email.
3. Complete the To line, subject, and body.
4. Click on the SalesLoft App via the toolbar or the app launcher.  
5. The Salesloft menu is not displayed.

### Scenario 2: Calendar Invite

1. Go to Outlook on Chrome/Web or desktop.
2. Go to Calendar.
3. Select a Calendar invite.
4. Click on Reply all
5. Complete the To line, subject, and body.
6. Click on the Salesloft App via the tool bar or the app launcher.  
7. The Salesloft menu is not displayed.

## Link to live example(s)

https://user-images.githubusercontent.com/17027799/191513383-bebed5c8-02e5-4b75-84c2-8337c392dabe.mp4

# Provide additional details

1. There's just one organisation that reported this issue
2. ______
3. ______

## Context

Unable to use Salesloft on Outlook consistently.
The behavior is inconsistent. Sometimes the add-in works but most of the time it doesn’t.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
(1) Addins menu not working from Get-Apps:  We had this issue few weeks back but we fixed this and fix is already rolled out. Can you hard-refresh in browser and re-test this?

(2) When addin is pinned on Ribbon and sub-menu is not opening: We are able to reproduce this issue. We will get back to you shortly on this once.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding add-in sub-menu not opening from Ribbon. It has been put on our backlog. We unfortunately have no timelines to share at this point 

Internal tracking id: Office: [172142]

**Comment by exextoc** [comment]
The fix is deployed 100%. Please let us know if the issue persists.

**Comment by dmitry-semenov** [comment]
Looks resolved, thank you!
