### ISSUE TITLE
The text of command is splited to newline in add-in

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#286]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
I want to show the text in  one line as follows in Excel Online.
But in Excel Desktop,The text shows innormal.

for example:
Excel Desktop:
  **下载估
  值模型**

Excel Online
   **下载估值模型**

 
<img width="777" alt="1" src="https://user-images.githubusercontent.com/3182964/47638964-15fb3a80-db9b-11e8-8325-257ff4880c40.png">
<img width="591" alt="2" src="https://user-images.githubusercontent.com/3182964/47638965-15fb3a80-db9b-11e8-9bb9-7ed44b63a050.png">

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ___PC Desktop &  Office Online___
* Host [Excel, Word, PowerPoint, etc.]: ___Excel___
* Office version number: __16.0.10827.20118____
* Operating System: ___Windows___
* Browser (if using Office Online): __Firefox____

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lumine2008** [comment]
I can repro this  issue.  I created a bug 3180498 to track this issue.

**Comment by lliu113** [comment]
@hengchengfei - know it's been awhile but wanted to provide a quick update. This bug is still in our backlog, there are some underlying shared office code that may be causing this issue and we don't currently have an ETA but we are working on it. Thanks!

**Comment by hengchengfei** [comment]
almost 3 years~~~
