### ISSUE TITLE
AppointmentRead item.location is not returning data when using web version of Outlook

### ISSUE THREAD

**Issue by npw1990** [OfficeDev/office-js#2860]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
When viewing an event in AppointmentRead mode, the location is not being returned properly

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 365
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
When I am on an event with a location set, the value of Office.context.mailbox.item.location should return a valid value

## Current behavior
When I am on an event with a location set, the value of Office.context.mailbox.item.location is undefined

## Steps to reproduce
1. Open an event in AppointmentRead mode which has a location
2. Go to browser console and enter Office.context.mailbox.item.location
3. Hit enter
4. See that the value is undefined, instead of returning the event's location

# Provide additional details
This is not happening on Windows or Mac desktop versions of Outlook

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding 'location in AppointmentRead'. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: [172317]
