### ISSUE TITLE
Outlook on Mac with the classic/old UI returns null for the recipientType property (to, cc, bcc)

### ISSUE THREAD

**Issue by eugene-plutoflume** [OfficeDev/office-js#2862]
# Provide required information needed to triage your issue
In an Outlook add-in for compose mode, specifically in the `ItemSend` event handler, we use the following methods to extract some data of recipients:

```
Office.context.mailbox.item.to.getAsync(callback)
Office.context.mailbox.item.cc.getAsync(callback)
Office.context.mailbox.item.bcc.getAsync(callback)   
```

The `recipientType` property should return one of the [Office.MailboxEnums.RecipientType](https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailboxenums.recipienttype?view=outlook-js-preview#fields) values. But on Mac with Outlook Version 16.65 (22091101) with the old/classic UI the property gives `null` which is unexpected. At the same time Outlook with the new UI works well and returns valid results.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac 
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.65 (22091101) with the old UI
* Operating System: Mac OS 12.6 Monterey
* Browser (if using Office on the web): n/a
 
## Expected behavior

The `recipientType` property of the `Office.EmailAddressDetails` interface should return one of the [Office.MailboxEnums.RecipientType](https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailboxenums.recipienttype?view=outlook-js-preview#fields) values.

## Current behavior

The `recipientType` property of the `Office.EmailAddressDetails` interface returns `null`. 

## Steps to reproduce

1. Create an Outlook add-in for the compose mode with an `ItemSend` event handler.
2. In the event handler you may try to get `to`, `cc` or `bcc` property values represented by the `Office.EmailAddressDetails` interface with the `recipientType` property value using the [getAsync](https://learn.microsoft.com/en-us/javascript/api/outlook/office.recipients?view=outlook-js-preview#outlook-office-recipients-getasync-member(2)) method with a callback.
3. Create a new email and then send it from Outlook with a classic UI on Mac.  
4. Observe that in Outlook with the classic (old) UI the `recipientType` property returns `null` while the new Mac UI gives correct values.

## Context

There is no way to distinguish a recipient type in Outlook with the classic UI on Mac.

**Comment by exextoc** [comment]
Thank you for sharing this issue. As a workaround, users can switch to the [New Outlook for Mac](https://support.microsoft.com/en-gb/office/the-new-outlook-for-mac-6283be54-e74d-434e-babb-b70cefc77439?ui=en-us&rs=en-gb&ad=gb) experience which works as expected. We are not prioritizing this fix on classic Mac UI; please reopen the issue in case the workaround does not solve your scenario.

**Comment by eugene-plutoflume** [comment]
@exextoc thank you for confirming the issue. But we would like to support the classic Mac UI because we can't ask users to switch over. Please let us know whether the issue is going to be fixed and the timeframe required for that.

**Comment by exextoc** [comment]
We understand the concern but in this particular instance we will not be able to prioritize it as moving to new UI is our recommended solution.
