### ISSUE TITLE
Outlook Launch Event: fetch(url) TypeError: Network request failed

### ISSUE THREAD

**Issue by LSDerekTardiff** [OfficeDev/office-js#2866]
Hello I am having issues with using fetch during my Outlook Launch Event.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2208 
* Operating System: Windows 10
 
## Expected behavior
When making a fetch(url) request in the windows javascript runtime the request succeeds and I am able to do something with the response. As mentioned here https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#requesting-external-data this should be possible?

## Current behavior
The fetch(url) request does not succeed and after around 45 seconds the error "TypeError: Network request failed" is thrown.
Relevant Log Messages for sample code:
```
9/23/2022 16:30:42      Verbose Runtime [Console] [Log] RunLaunchEventHandlerFunctionWithData was invoked with funcName = onAppointmentAttendeesChangedHandler
9/23/2022 16:30:42      Verbose Runtime [Console] [Log] MailboxHostExecuteApi invoked!
9/23/2022 16:30:42      Verbose Runtime [Console] [Log] Start
9/23/2022 16:30:42      Verbose Runtime [Console] [Log] RunLaunchEventHandlerFunctionWithData was invoked with funcName = onAttendeesChanged
9/23/2022 16:30:42      Verbose Runtime [Console] [Log] Event completed message sent to host!
...
9/23/2022 16:31:25      Verbose Runtime [Console] [Log] err TypeError: Network request failed
9/23/2022 16:31:25      Verbose Runtime [Console] [Log] End
9/23/2022 16:31:25      Verbose Runtime [Console] [Log] Event completed message sent to host!

```

## Steps to reproduce

Relevant Manifest Details:
```
<Host xsi:type="MailHost">
          <Runtimes>
            <Runtime resid="webViewRunTime">
              <Override type="javascript" resid="jsRunTime"/>
            </Runtime>
          </Runtimes>
          <DesktopFormFactor>
            <FunctionFile resid="functionFile" />
            <ExtensionPoint xsi:type="AppointmentOrganizerCommandSurface">
              <OfficeTab id="TabDefault">
                <Group id="meetingGroup">
                  <!-- excluded -->
                  <Control xsi:type="Button" id="addMeetingButton">
                    <!-- excluded -->
                    <Action xsi:type="ExecuteFunction">
                      <FunctionName>onAttendeesChanged</FunctionName>
                    </Action>
                  </Control>
                </Group>
              </OfficeTab>
            </ExtensionPoint>
            <ExtensionPoint xsi:type="LaunchEvent">
              <LaunchEvents>
                <LaunchEvent Type="OnAppointmentTimeChanged" FunctionName="onTimeChanged" />
                <LaunchEvent Type="OnAppointmentAttendeesChanged" FunctionName="onAttendeesChanged"/>
              </LaunchEvents>
              <SourceLocation resid="webViewRunTime"/>
            </ExtensionPoint>
          </DesktopFormFactor>
        </Host>
     <!-- excluded -->
<Resources>
        <!-- excluded -->
        <bt:Urls>
          <bt:Url id="functionFile" DefaultValue="https://localhost:44371/Office/FunctionFile"/>
          <bt:Url id="settingsUrl" DefaultValue="https://localhost:44371/Office/Settings"/>
          <bt:Url id="webViewRunTime" DefaultValue="https://localhost:44371/Office/FunctionFile"/>
          <bt:Url id="jsRunTime" DefaultValue="https://localhost:44371/Scripts/ts/FunctionFile.js"/>
        </bt:Urls>
        <!-- excluded -->
      </Resources>
```
Relevant typescript code.
```
Office.actions.associate("onAttendeesChanged", onAttendeesChangedHandler)

async function onAttendeesChangedHandler(event: Office.AddinCommands.Event) {
    console.log("Start");
    try {
        const response = await fetch("https://localhost:44371/api/ping"); // ping endpoint, returns json ping message
        const text = await response.text();
        console.log("text " + text);
        Office.context.mailbox.item.notificationMessages.addAsync("text",
            {
                type: Office.MailboxEnums.ItemNotificationMessageType.ErrorMessage,
                message: text
            }, null);
    } catch (err) {
        console.log("err " + err);
    }
    console.log("End");

    event?.completed({ allowEvent: true });
}
```

1. Open Meeting, Click add in button to execute onAttendeesChangedHandler function.
2. Observe ping response displayed in notification messages as expected.
3. Add a participant to trigger the OnAppointmentAttendeesChanged event.
4. After around 45s, Observe logs to see error.

# Provide additional details
- Add-in and API are hosted on the same origin (https://localhost:44371)
- Similar results occurs when using a xmlhttprequest instead

## Context
- The plan for our integration was to use the fetch to update our meeting record in our database with an API call when the attendees list is updated. This sample is just a simple request to try getting the fetch working with no luck.

## Useful logs
Logs again from above
```
9/23/2022 16:30:42      Verbose Runtime [Console] [Log] RunLaunchEventHandlerFunctionWithData was invoked with funcName = onAppointmentAttendeesChangedHandler
9/23/2022 16:30:42      Verbose Runtime [Console] [Log] MailboxHostExecuteApi invoked!
9/23/2022 16:30:42      Verbose Runtime [Console] [Log] Start
9/23/2022 16:30:42      Verbose Runtime [Console] [Log] RunLaunchEventHandlerFunctionWithData was invoked with funcName = onAttendeesChanged
9/23/2022 16:30:42      Verbose Runtime [Console] [Log] Event completed message sent to host!
...
9/23/2022 16:31:25      Verbose Runtime [Console] [Log] err TypeError: Network request failed
9/23/2022 16:31:25      Verbose Runtime [Console] [Log] End
9/23/2022 16:31:25      Verbose Runtime [Console] [Log] Event completed message sent to host!

```

Let me know if there are any additional details I can provide or if anything is unclear thanks!

**Comment by weidezhong-msft** [comment]
When you host the JS files on localhost, make sure to enable direct debugging, otherwise the resource on localhost is not reachable and will result in a networking failure. [https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/debug-autolaunch](url)

**Comment by avisheknand** [comment]
Thanks @weidezhong-msft ... i had similar issue with Outlook launch event add-in and the information you shared above solved my issue.

**Comment by hapalacios** [comment]
@avisheknand , @weidezhong-msft  could you share an example how did you setup your debugger and .well-know folder to be able to debug the launch event handlers? I am trying to fetch GET or POST endpoints after pressing Send but not luck reaching the endpoint or debugging the handler. I explain my issue here with more details. https://github.com/OfficeDev/office-js/issues/2999

**Comment by ShivIfour** [comment]
I'm still facing this issue. Is this issue resolved?

**Comment by teejay001** [comment]
Hi @exextoc,

This is still an issue for most so not sure why we have closed this down. In all launch event triggers, we can not make fetch API call. Please could you give any update on this. At the least acknowledge the issue persist and keep the ticket open of link it to any relevant/related/similar issue.

cheers

**Comment by Discolai** [comment]
I am posting my solution to this issue here in cases someone finds it helpful

Our application was using relative URLs in fetch calls. According to the documentation on [requesting external data](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#request-external-data), relative URLs are not supported in a JavaScript-only runtime. Absolute URLs must be used instead.
