### ISSUE TITLE
addin does not start in Office Enterprise environment

### ISSUE THREAD

**Issue by rogozind** [OfficeDev/office-js#2868]
We have an add-in in MS Store called "Verity RMS for Office". It works well for all our clients. One customer cannot get it running and gets that dreadful "This add-in seems to be having problems. Click Restart to try restarting it again."

We have enabled the log and I see this:
```
9/22/2022 17:56:04	Medium	Web Add-In Runtime Logging Session Started			
9/22/2022 17:56:04	Monitorable	Manifest	Extension point list has no supported extension points for this client		
9/22/2022 17:56:04	Monitorable	Manifest	Issue encountered while parsing manifest, add-in ID : f438b4e6-2b49-466f-9a91-b75f473eba96, Location : Error at element "VersionOverrides" : Manifest override with unsupported requirements or no supported extension points ignored: http://schemas.microsoft.com/office/taskpaneappversionoverrides, VersionOverridesV1_0, Line=54, CharPosition=5
```		

They found out that if they enable compatibility mode for WebView2 to be Windows 8 it works:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/10505245/192288089-ecdae3a5-b1e0-4ad5-886c-9649b94d93ef.png">

They tried on a Pro Office version and it works as well (w/o compatibility mode):
<img width="523" alt="image" src="https://user-images.githubusercontent.com/10505245/192287640-7afacf40-50d4-4dc4-ab22-1152bd903622.png">

Something in the Enterprise version is preventing addin to run (Configured to prevent?) I am at a loss what can it be. 

They are on Windows 10.

Any ideas are appreciated.

**Comment by gingerjia** [comment]
@rogozind , thanks very much for reporting the issue! 
For the failure you posted above is for "add-in ID : f438b4e6-2b49-466f-9a91-b75f473eba96", seems it's not same as "Verity RMS for Office" add-in Id. Could you help to double confirm it?
And for the webview2 compatibility issue, could you help to get the detail diagnostic log to help us further investigate the root cause? Here is how to get the log for reference: https://learn.microsoft.com/en-us/microsoft-365/troubleshoot/diagnostic-logs/collect-office-diagnostic-logs. Thanks very much for help!

**Comment by rogozind** [comment]
Good catch on the addin ID. No wonder I was puzzled by the message. You are correct.
Thanks for log info. We will work with the customer to collect the data and maybe we learn something from that.

**Comment by rogozind** [comment]
The client has attached the logs.
They also tried Wikipedia addin and that did not work either. So it is definitely something in their environment.
Let me see fi you find anything in the logs.

[App1664544362179424900_BF4895A0-FB7E-4968-89B5-6BE99F66CF77.zip](https://github.com/OfficeDev/office-js/files/9685170/App1664544362179424900_BF4895A0-FB7E-4968-89B5-6BE99F66CF77.zip)

**Comment by rogozind** [comment]
The client has found a solution based on this article: https://learn.microsoft.com/en-us/answers/questions/693068/webview2-compatibility-issue.html

Registry Key : [HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\WebView2]
"RendererCodeIntegrityEnabled"=dword:00000000

Feel free to close this ticket.

That being said, we have seen this "cannot load add-in" message a lot and it is always a pain to debug. Please add some additional logging to report actual issue.
