### ISSUE TITLE
Outlook item.saveAsync is not returning item ID in the callback function

### ISSUE THREAD

**Issue by gummybuns** [OfficeDev/office-js#2869]
# Provide required information needed to triage your issue
According to the [documentation](https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview&preserve-view=true#outlook-office-messagecompose-saveasync-member(2)):

> When invoked, this method saves the current message as a draft and returns the item id via the callback function

However we are encountering situations where a successful result is returned but the `value` is not the id of the item. It appears to be an empty string.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.65.911.0
* Operating System: Mac  OSX 10.15.7
* Browser (if using Office on the web): N/A
 
## Expected behavior
A call to `Office.context.mailbox.item.saveAsync()` should include an itemID when the `status` is `Office.AsyncResultStatus.Succeeded`

## Current behavior
We are getting an empty string in the call despite the status suggesting it succeeded

## Steps to reproduce
I do not have the exact steps to reproduce, i only have the error captured from one of our customers.

## Link to live example(s)
N/A

# Provide additional details
Here is our implementation of the `saveAsync` method to convert it to a promise:

```typescript
const save = (): Promise<string> =>
  new Promise((resolve, reject) => {
    Office.context.mailbox.item.saveAsync(
      ({ diagnostics, error, status, value }) => {
        if (status === Office.AsyncResultStatus.Succeeded) {
          resolve(value);
        } else {
          reject(error);
        }
      },
    );
  });
```

Despite the fact that we are getting a status `Office.AsyncResultStatus.Succeeded` the `value` is coming back as an empty string
## Context
We save the item to get the id which is then passed to the backend for some more processing.

## Useful logs
```
User Agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)

Browser:
Apple Mail
Version:
605.1.15

OfficeJS Supported Version
1.11
```

**Comment by exextoc** [comment]
We need repro steps or a repro video to understand the issue better. Kindly provide that.
