### ISSUE TITLE
Sidebar Fails Initial Load

### ISSUE THREAD

**Issue by andschleicher** [OfficeDev/office-js#287]
## Expected Behavior
When one of the buttons for a custom Add-In is clicked, the sidebar should load immediately with the correct content.

## Current Behavior
The first time a button for a custom Add-In is clicked on, the sidebar opens as expected but none of the content loads. If the same button is clicked again, another version of the sidebar opens and the content loads as expected. This issue only occurs the first time an Add-In button is clicked you open a new instance of the application and all subsequent usages work as expected.

## Steps to Reproduce, or Live Example
This is occurring for every custom Add-In that I've tested and it is not occurring for the default Wikipedia Add-In. Also, the issue appears to have been introduced with build 10827.20181 as I did not experience the issue with build 10827.20150, and I started seeing the issue as soon as I updated.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Word/Excel/PowerPoint
* Office version number: Version 1809, Build 10827.20181
* Operating System: Windows 10

**Comment by kbrandl** [comment]
@andschleicher I'm unable to reproduce the issue that you've described. Are you still having this problem?

**Comment by andschleicher** [comment]
@kbrandl I am no longer experiencing this issue after updating the version of my desktop version of Word.
