### ISSUE TITLE
Web add-In: how to download base64 encoded content in outlook on mac 2021?

### ISSUE THREAD

**Issue by xeras** [OfficeDev/office-js#2870]
I want to implement a web add-in feature to download base64 encoded data. This works for OWA and windows client, but does not work in outlook on mac 2021.

Can you explain how to download any base64 encoded data in outlook on mac 2021?

### FileSaver.js

```
<IconButton
  iconProps={{ iconName: 'Download' }}
  onClick={() => {
    FileSaver.saveAs(data, filename);
  }}
/>
```

Works on windows and OWA, but not in outlook on mac.

### Object URL with Link

```
<a href={URL.createObjectURL(blobObject)} download={filename}>download</a>
```

Works on windows and OWA, but not in outlook on mac.

### Data URL with Link

```
<a href={`data:;base64,${data}`} download={filename}>download</a>
```

Works on windows and OWA, but not in outlook on mac.

### openBrowserWindow

I also tried to open a browser windown containing a data url

```
Office.context.ui.openBrowserWindow(`data:;base64,${data}`)
```
or a url created by `URL.createObjectURL()`

```
Office.context.ui.openBrowserWindow(`blob:https://localhost:3000/<uuid>`)
```

`URL.createObjectURL()` should not work, because if the use defined an other default browser than safari, this link is invalid.

Additionally `openBrowserWindow()` only works with urls starting with `http://` or `https://`. URLs starting with `data:` or `blob:` are not recognized and does not open a new new browser window.

**Comment by yjoshi-msft** [comment]
Hi Xeras,

Would request you to post this on tack Overflow and tag it with office-js.
https://stackoverflow.com/questions/tagged/office-js
