### ISSUE TITLE
Excel worksheet protection prevents users from grouping/ungrouping rows and columns

### ISSUE THREAD

**Issue by resong** [OfficeDev/office-js#2871]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

It is a common use case for our Excel add-in to protect worksheets but permit users to group/ungroup rows or columns.

In the C# API, a `UserInterfaceOnly` property could be passed as an option to allow the user to do this without impacting anything else. This property is not available in the [JS API](https://learn.microsoft.com/en-us/javascript/api/excel/excel.worksheetprotectionoptions?view=excel-js-preview), only `allowFormatRows` and `allowFormatColumns` are available, but these also allow users to change height/width of cells and hide/show columns or rows. 

Is there another way to achieve the same behaviour, similar to the `UserInterfaceOnly` option?

**Comment by gingerjia** [comment]
@resong , thanks very much for reporting the issue! Sorry that currently we didn't have such API to support this operation. Could you help to fill a request for it in https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform? Then our PM will help to triage the requirement accordingly. Thanks again!

**Comment by resong** [comment]
@gingerjia I had initially posted this issue as a feature request -- is there another place I should post my request?

**Comment by gingerjia** [comment]
> @gingerjia I had initially posted this issue as a feature request -- is there another place I should post my request?

Hi @resong, please help to post a feature request in https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform. Thanks very much! :)

**Comment by resong** [comment]
Thanks, I've posted my request here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/equivalent-of-userinterfaceonly-worksheet-protection-option-for/idi-p/3641774#M1375
