### ISSUE TITLE
word-win32-16.01 throwing InvalidArgument exception at location - Range.insertFileFromBase64

### ISSUE THREAD

**Issue by jindaldheeraj** [OfficeDev/office-js#2879]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi Team,

We have developed a word Addin to configure the templates. This Addin has capability to edit already existing templates by pulling them from repository and rendering them on MS word and to do so we are passing the byte stream to insertFileFromBase64(myBase64, "replace") to get the template document rendered.

Error: {"description":"InvalidArgument","name":"RichApi.Error","code":"InvalidArgument","traceMessages":[],"innerError":null,"debugInfo":{"code":"InvalidArgument","message":"InvalidArgument","errorLocation":"Range.insertFileFromBase64"},"httpStatusCode":400,"stack":"InvalidArgument: InvalidArgument\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:307762)\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:236859)\n   at I (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:236835)\n   at D (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:236708)\n   at h (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:235204)"}

This Addin was working fine and the error started popping up recently.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __PC Desktop____
* Host [Excel, Word, PowerPoint, etc.]: __Word____
* Office version number: _Word 2016 (16.0.5317.1000)_MSO 16.0.5361.1000____
* Operating System: ___Windows 10 Enterprise___
* Browser (if using Office on the web): ______
 
## Expected behavior
Templates should rendered without any error.

## Current behavior
Template documents are not getting rendered on Word

## Steps to reproduce

1. _Pass Base64 array to insertFileFromBase64 as - insertFileFromBase64(myBase64, "replace") _____
2. _Bytes should get rendered to corresponding document on word_____
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [x] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by jindaldheeraj** [comment]
Hi Team,

Did you get chance to review the above reported issue.

Regards,
Dheeraj Jindal

**Comment by lindalu-MSFT** [comment]
@jindaldheeraj Hi, we don't triage on the weekends. I've tagged the appropriate SMEs who can investigate this issue. They should get back to you in 72 hours or less.

**Comment by jindaldheeraj** [comment]
Hi Team,

Do we have any update on the reported issue. This is started occurring recently and there were some office updates which got installed on the system. There is no way to uninstall them as uninstalling them is again reinstalling them.

Regards,
Dheeraj Jindal

**Comment by jipyua** [comment]
hi @jindaldheeraj does this error happens for all the API calls or just some of them? This InsertFileFromBase64() API accepts two arguments, the first one is a base64 string, the second one is the insert location. Would you please help confirm which one of them is reporting the error? BTW, can you also try to call the same API in the ScriptLab add-in (a public add-in in the Office Store) and see whether you can repro still?

**Comment by jindaldheeraj** [comment]
Hi @jipyua - This is happening for InsertFileFromBase64(). We are passing two parameters - base64 string and second as replace. We don't know for which parameter it is throwing the error. Also, we tried replacing the "replace" with "start", still same error. Also, the Addin is working on my local machine but not on other set of users machine.

There are some office updates which were applied in mid September on the machines where issue is getting reported.

Regards,
Dheeraj Jindal

**Comment by jipyua** [comment]
@jindaldheeraj I mean on other set of user's machine, does the call to InsertFileFromBase64 fails every time or just for some specific base64 strings?  Same case as on your machine, this API is also working fine on our machine. We need to get more information in order to reproduce this. Would you please try to get the user's base64 string and see whether it works or not on your machine and sent it to use if not working?

**Comment by jindaldheeraj** [comment]
Hi @jipyua - Yes call to InsertFileFromBase64 fails every time for all the base64 string and they are using MS Office Standard 16 version - 16.0.5317.1000 MSO (16.0.5361.1000)

On my local I am using Office 365 where Script Lab addin is getting loaded successful whereas on MS Word 16 Standard machine it is displaying message - "Script Lab no longer supports the Internet Explorer 11 Browser or embedded browser control". Please upgrade to a supported version of Microsoft 365 or open office on the web in a supported browser"
[base64_Sample.txt](https://github.com/OfficeDev/office-js/files/9738571/base64_Sample.txt)

**Comment by jindaldheeraj** [comment]
Hi Team,

Did you get chance to review the details which I have provided. Please let me know in case you need any further details.

Regards,
Dheeraj Jindal

**Comment by jipyua** [comment]
hi @jindaldheeraj  we are still investigating the root cause and will get back to you when we have some findings, thanks.

**Comment by jipyua** [comment]
hi @jindaldheeraj we are now working on how to resolve this issue, considering the fix and deployment may take some time to roll out, another way to mitigate this issue is to reference an old office.js/word-win32-16.01.js. Feel free to have a try.

**Comment by jindaldheeraj** [comment]
Thanks a lot jipyua!!

Would wait for your response once the issue is fixed.

Regards,
Dheeraj Jindal
