### ISSUE TITLE
How to set add-in works only in Windows Desktop.

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#288]
## Expected Behavior
I want my add-in will be work in Windows-only,Will not work in Online or Mac and Ipad.

How can I edit the manifest?

<img width="769" alt="1" src="https://user-images.githubusercontent.com/3182964/47689552-5606ff80-dc25-11e8-828d-bb62269b8648.png">

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: __PC desktop____
* Host [Excel, Word, PowerPoint, etc.]: ___Excel & Word___
* Office version number: __Office 2016____
* Operating System: __Windows____
* Browser (if using Office Online): ___IE___

**Comment by JuaneloJuanelo** [comment]
I am not sure why you want to do that, can you share more details? 
there is no way of targeting a specific platform with the manifest. what you can do is to show an error in those platforms that your add-in is not supported. (you can use office.context.diagnostics.platform to find out what platform you are and then potentially provide a page with information on the platforms you dont support)
