### ISSUE TITLE
Using CoercionType.XmlSvg, certain complex svg renders incorrect in PowerPoint

### ISSUE THREAD

**Issue by lynneosmith** [OfficeDev/office-js#2881]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Our addin renders content into the powerpoint slide. We have successfully rendered many svgs, but ran across a complex one today that renders incorrectly/incompletely in Powerpoint . We are using setSelectedDataAsync with the CoercionType.XmlSvg to render.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop and Web
* Host: PowerPoint
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
I expect the svg to render in the powerpoint slide.

## Current behavior
Instead, I get an image rendered that is partially correct, but part of the svg is missing and is blank.
I have tried rendering this svg in other online svg viewers and it renders correctly.

Our code:
return new Promise((resolve, reject) => {
    Office.context.document.setSelectedDataAsync(
      svgString,
      {
        coercionType: Office.CoercionType.XmlSvg,
        imageLeft: left,
        imageTop: top,
        imageWidth: width,
        imageHeight: height,
      },
      function (asyncResult) {
        if (asyncResult.status === Office.AsyncResultStatus.Failed) {
          console.error(
            `Unable to insert graph: ${asyncResult.error.message} (${asyncResult.error.code})`
          );
          reject(asyncResult.error);
        } else {
          resolve();
        }
      }
    );
  });

## Steps to reproduce

I have attached the svg.
If you try to render it in Scriptlab, it should render, but I just get errors. No image is rendered at all. You can use the ScriptLab sample to insert svg and change the svg to this one and you will see that it gets errors.

## Context
Our addin inserts content into the document for the user to represent content in our pane. When that content renders incorrectly, it could suggest misleading data to the user.

## Useful logs
![incorrectsvg](https://user-images.githubusercontent.com/57771416/193684040-3ac78bf3-84e0-4f77-bd8a-0b6423583fae.JPG)
![correctsvg](https://user-images.githubusercontent.com/57771416/193684058-645e8b8d-e758-464d-b386-4d1c1cc75599.JPG)
![spineplot](https://user-images.githubusercontent.com/57771416/193682298-c00f0080-6b0e-4479-9866-62b9fa7f9d5c.svg)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by jipyua** [comment]
@lynneosmith thanks for reporting this. In your attached snapshot, I can only save it as jpg but not svg. Would you please attach a zip file containing the .svg file as well as the xmlsvg string in txt file? Also would you please try to directly insert the svg file from PowerPoint UI and does it render correctly?

**Comment by lynneosmith** [comment]
[spineplot_issue.zip](https://github.com/OfficeDev/office-js/files/9766284/spineplot_issue.zip)

**Comment by lynneosmith** [comment]
@jipyua I just attached a zip file with the xml in a text file and the svg. Hope this helps!

**Comment by jipyua** [comment]
@lynneosmith thanks for sharing the files. I tried to directly insert the SVG file from PPT rich client UI Insert->Pictures and it also repros your issue. So this is a PPT product related issue instead of an API one and I am afraid this channel will not be a good place to discuss this. I would suggest to submit from the PowerPoint in-app feedback channel (for Windows: File -> Feedback) to report this issue to Microsoft. Thanks.
