### ISSUE TITLE
Failed to load resource: net::ERR_CONTENT_DECODING_FAILED office script

### ISSUE THREAD

**Issue by GMolini** [OfficeDev/office-js#2884]
Im developing a vue 2.0 app addin for outlook. Right now, its on just on development mode so Im sideloading the addin.
A very weird bug is happening today. I have several mailboxes inside outlook, and one of them cant load the addin (again it was working fine until recently)

The failure it gives is this:

```
Failed to load resource: net::ERR_CONTENT_DECODING_FAILED outlook_strings.js:1 
```

The problem is this part in my `index.html`
```
 <script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js" ></script>
```
If I change that src to `https://appsforoffice.microsoft.com/lib/beta/hosted/office.js` it actually works and loads the addin. Whats driving me crazy is that the error only happens on ONE mailbox. If I open the same addin on another mailbox, it works fine and that script loads correctly.

Any idea what might be happening? How do I ensure that the office.js is loaded correctly?

**Comment by exextoc** [comment]
Please answer some questions below for us to understand the issue better :
1. Is the repro consistent for that user?
2. Where do you see the issue happening (Web / Windows client / Mac client / Mobile ) ?
3. Do you see any error in the console when this happens?

**Comment by GMolini** [comment]
1. Is the repro consistent for that user?
Since yesterday yes, it happens all the time and has not stopped happening.

2. Where do you see the issue happening (Web / Windows client / Mac client / Mobile ) ?
Windows client. On the web it loads fine.

3. Do you see any error in the console when this happens?
The error in the console is the one I mentioned above
![image](https://user-images.githubusercontent.com/1327783/194355787-8c62b3f3-035b-4fca-aaab-28b9656f3112.png)

**Comment by Adrian-MSFT** [comment]
Hi @GMolini can you please provide your windows client version?

**Comment by GMolini** [comment]
Windows: 10 Education, Version 10.0.19044 Build 19044
Outlook: Version 2209. Build 15629.20156

**Comment by Adrian-MSFT** [comment]
Hi @GMolini - It may be caused by a temporary issue with the CDN. Please find this post for reference as well as a way to load this offline instead of using the CDN: https://stackoverflow.com/questions/71337900/failed-to-load-resource-neterr-content-decoding-failed-office-js

**Comment by ndreisg** [comment]
Hi there.

One of our customers recently reported this error. 
The solution to load the library offline instead of using the CDN is not satisfying since this would mean that users would not get the newest version of the API until the Add-In is updated by us.
Please reopen.

![ContentDecodingFailed](https://user-images.githubusercontent.com/6780383/226872334-f1526168-d7b8-421c-91c5-e59ad4b8304b.JPG)

**Comment by theRiley** [comment]
A small number of our users are experiencing this same issue. So far nothing found online has worked. According to documentation, I need the Office.js CDN in order to submit our Add-In to AppSource. Can you please reopen to help find a solution?

**Comment by ndreisg** [comment]
@theRiley The customer who initially reported the issue to me now reported that it was solved by repairing the Office installation.
(which doesn't mean that this shouldn't be fixed btw)
