### ISSUE TITLE
CustomFunctions.Error ignores custom error message for some error codes

### ISSUE THREAD

**Issue by tj-aew** [OfficeDev/office-js#2885]
When you throw a `CustomFunctions.Error` using `CustomFunctions.ErrorCode.invalidNumber` as the `code`, any `message` you include is ignored and Excel just shows the generic message instead ("There is a problem with a number used in the formula.").

After we got hit by this, we found [the documentation](https://learn.microsoft.com/en-us/javascript/api/custom-functions-runtime/customfunctions.error?view=excel-js-preview#constructors) does say "Custom messages are only available with certain error codes." but that's far from specific (what codes?), and in any case, it doesn't seem to make sense to ignore the message provided by the developer in favor of a generic message. Far preferable to accept the custom message.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2207 Build 16.0.15427.20248) 64-bit 
* Operating System: Windows 10
* Browser (if using Office on the web): Edge
 
## Expected behavior

That the provided message would override the default.

## Current behavior

The default message appears instead.

## Steps to reproduce

1. Have a custom function throw `CustomFunctions.Error` like this:
   ```js
   throw new CustomFunctions.Error(
       CustomFunctions.ErrorCode.invalidNumber,
       `Custom message here`
   );
   ```
2. Run it
3. Observe that the custom message is ignored

## Context

We've taken the time to provide more useful, specific messages to help our users. It's unfortunate they aren't being displayed. We realize we could use one of the other error codes instead (`invalidValue` uses the message provided), but #NUM! is appropriate for some of our functions (other than this issue).

**Comment by tj-aew** [comment]
I should note that this is in those situations where the custom function **does** get called (so: **not** a custom function where the type of the parameter is `number` and so Excel knows it's invalid and doesn't even call the custom function). (That said, it'd be great to have an option to opt out of that so we could do all the validation at once, rather than giving the user piecemeal feedback.)

**Comment by rundongmsft** [comment]
Hi @tj-aew, Custom messages are only available with these two codes: `CustomFunctions.ErrorCode.notAvailable` and `CustomFunctions.ErrorCode.invalidValue`. `CustomFunctions.ErrorCode.invalidNumber` does not currently support custom messages.

**Comment by tj-aew** [comment]
@rundongmsft - Thanks for letting me know which ones work. But the point is that they all should accept custom messages.

**Comment by rundongmsft** [comment]
Hi @tj-aew, currently custom error messages are not available with error codes except `notAvailable` and `invalidValue`. Let all error codes support custom messages should be a new feature request. 
We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). You can add this request there. Feature requests are considered when we go through our planning process.

**Comment by tj-aew** [comment]
@rundongmsft  - Thanks, I've posted there although I have to say that as a developer outside Microsoft using this API, there's no impression that suggestions there are even heard, much less acted upon.
