### ISSUE TITLE
SendMode is not validated correctly when uploading custom app in MS Admin Center

### ISSUE THREAD

**Issue by idr-raas** [OfficeDev/office-js#2889]
## Article URL

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough#configure-the-manifest

## Issue

 when i try to upload this manifest to MS Admin Center/Integrated Apps/Upload Custom App it gives back the following error in the network tab of dev console. However, same file is validated on desktop and functions correctly when sideloaded

{
    "appDetail": null,
    "returnedWorkloads": null,
    "errorMessage": "[\"XML Schema Validation Error. Error found during XML Schema validation.\",\"XML Schema Violation. Your manifest does not adhere to the current set of XML schema definitions for Office Add-in manifests.\"] Error Response : , Error Message : , Response Headers : {\r\n  \"X-Frame-Options\": [\r\n    \"SAMEORIGIN\"\r\n  ],\r\n  \"X-DEPLOYMENT-ID\": [\r\n    \"a722d27b47d94b198c572f8a917b8a85\"\r\n  ],\r\n  \"x-ms-correlation-id\": [\r\n    \"47d34c81-fdb0-404c-8c21-6ed31b1b4d45\"\r\n  ],\r\n  \"X-AspNet-Version\": [\r\n    \"4.0.30319\"\r\n  ],\r\n  \"x-as-routekeyapplicationendpointlist\": [\r\n    \"indportal.office.com\"\r\n  ],\r\n  \"x-as-routekey\": [\r\n    \"ind\"\r\n  ],\r\n  \"X-Powered-By\": [\r\n    \"ASP.NET\"\r\n  ],\r\n  \"X-Content-Type-Options\": [\r\n    \"nosniff\"\r\n  ],\r\n  \"X-UA-Compatible\": [\r\n    \"IE=Edge\"\r\n  ]\r\n}",
    "statusCode": "WxpoFailedManifestValidationError",
    "statusCodeCategory": "WXPO"
}

**Comment by AlexJerabek** [comment]
Thank you for reporting this @idr-raas.

@samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi @idr-raas,

I'm also getting an "Invalid manifest file" error when I attempt to upload the Smart Alerts walkthrough manifest file. I'll look into this further and will let you know what I find.

**Comment by idr-raas** [comment]
I think schema validation has a problem. It is stating schema violation without providing any reason. Could it be the correct schema definitions are not updated on servers for the manifest to be properly validated

**Comment by exextoc** [comment]
We are able to reproduce this issue. We are working on priority to resolve this issue.

**Comment by sys0601** [comment]
Could we get an update on this please?

Smart Alerts was one of the exciting new features for Outlook presented in several Office Addin community calls by Juan Balmori and others. We have invested a lot of resources in converting some applications to take advantage of this new feature. 

However the solution is impractical if admins are unable to deploy it to users.

Please solve this quickly.

**Comment by vamv86** [comment]
I would like to know if the conclusion is that it is not possible to generate a manifest for the OnMessageSend event?

since I execute "npm run validate -- -p" and it says that everything is ok but when I load the manifest in Microsoft 365 admin center this fails.

**Comment by avisheknand** [comment]
Hi,

i have same issue as well. @exextoc , any updates on this would be appreciated :)

**Comment by develsecudos** [comment]
Hi OfficeDev,

beeing able to configure the SendMode in combination with using Events, is one of our core features.

Now for 'MS Admin Center' we are forced to drop the sendMode, hence our Events make less sense.
Or we can tell our customers to avoid 'MS Admin Center' and use sideloading.

Please fix this issue!
Thanks

**Comment by idr-raas** [comment]
It's been too long and still waiting for the fix.

Currently, I am using PS script to deploy the plugin to users while hosting the plugin online.
For anyone who wants to go through the hassle and is in urgency may use the following PS commands

//Connect to EXO
Connect-ExchangeOnline -UserPrincipalName $UPN

new-app -mailbox $mailboxID -url $manifestURL

In case you would like to know how many users have the plugin installed for future you may use the following:
Get-Mailbox -RecipientTypeDetails UserMailbox | % { if ((Get-App {PLUGIN-UUID} -Mailbox $_.PrimarySmtpAddress -ErrorAction SilentlyContinue).Enabled) { $_ | select Name,PrimarySmtpAddress} }

**Comment by develsecudos** [comment]
Hi,

has this issue been resolved ?

We cannot reproduce it anymore.

The Validation accepts:
SendMode="SoftBlock"
SendMode="PromptUser "
SendMode="Block"

We are going to get rid of our workarounds, hoping this doesn't change again.

Regards
develsecudos

**Comment by idr-raas** [comment]
I have tested it out and it seems that issue is resolved. Manifest file is being validated correctly.

While no fix or update has been made via the official channel, yet based on the favorable outcome, I am happy to close this ticket out.

May reopen if the issue surfaces again.

Thank you. :)
