### ISSUE TITLE
Outlook desktop (new Mac OS X UI): addFileAttachmentFromBase64Async throws code: 5001, message: "An internal error has occurred." in pinned add-in

### ISSUE THREAD

**Issue by guzman-rc** [OfficeDev/office-js#2890]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
In an Outlook add-in (**new Mac UI preview**) for compose mode, we are using the **addFileAttachmentFromBase64Async** method to add attachments. In Outlook desktop "new Mac UI preview", the "Internal Error" occurs if the add-in's pane is pinned.

**In Mac Outlook desktop "Classic UI" this method work correctly.**
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft Outlook for Office 365 MSO version 16.65 (22091101)
* Operating System: Monterey (v.12.6)
 
## Steps to reproduce

1. Install MetaClean for Outlook from Microsoft App Source (https://appsource.microsoft.com/en-us/product/office/WA200003633)
2. Start Outlook and select new Mac UI for Outlook.
3. Create a new email in Outlook desktop.
4. Click "**_MetaClean for Metadata_**" button.
5. Click on the add-in’s pane and select a file to attach.
6. The code that causes the error is (See Screenshots from Web Inspector):

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. In Mac Outlook desktop "Classic UI" this AddIn work correctly.

## Context

This bug is causing complaints from our customers.

## Useful logs

- [ ] Screenshots from Web Inspector
Enable new Mac UI preview:
![150651424-53b4b1af-c8ca-42f3-bcc7-3bd9b3625b78](https://user-images.githubusercontent.com/96702862/194553921-accef989-e0e2-434a-96ba-cc4f563c9229.png)

Error returned by addFileAttachmentFromBase64Async method:
![150651429-3a6fcd03-ed4c-44ef-abc0-ef92606a2184](https://user-images.githubusercontent.com/96702862/194554263-2602a4fc-d392-4b35-bf89-29215b6892b2.png)

**Comment by exextoc** [comment]
We have a repro of this issue and are working on it. We unfortunately have no timelines to share at this point
