### ISSUE TITLE
Mail Signature: duplicate signature when re-open Appointment/Event on Outlook

### ISSUE THREAD

**Issue by hxltinh** [OfficeDev/office-js#2892]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.65 (Mac), Window (Version 2209 Build 16.0.15629.20152)
* Operating System: Window, MacOs
 
## Expected behavior
It should only update one signature when re-open Appointment/Event

## Current behavior
duplicate signature when re-open Appointment/Event

## Steps to reproduce
	
1. create an appointment/event
2. insert html signature
3. insert attendee, send appointment/event
4. open appointment/event
5. insert html signature again

## Link to live example(s)

1. scriptlab gist: https://gist.github.com/hxltinh/ad489d4cfd504ea06eda85592296ef8d

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding duplicate signature. It has been put on our backlog. We unfortunately have no timelines to share at this point. Internal tracking id: 6872058

**Comment by AkhileshShah-MS** [comment]
Closing the issue as product owner is tracking the issue on backlog.

**Comment by gostritm** [comment]
Hi @exextoc, just wanted to check in and see if there have been any updates on this issue.
