### ISSUE TITLE
Excel: NamedItemCollection. addFormulaLocal fails on large formula

### ISSUE THREAD

**Issue by timnudecision** [OfficeDev/office-js#2895]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
I am generating excel functions in my add-in; I want to make them available to user as a named function.  I am using addFormulaLocal for that purpose.

I can enter one of these formulas into the Advanced Formula Environment and that works well.  using addFormulaLocal fails with the messages in the useful logs section below.

## Your Environment

* Platform MacOS ARM64 and Win11 in a Parallels VM
* Host Mac Excel version 16.67
* Office 365 preview channel
* Operating System: Win11 and MacOS
* Browser n/a
 
## Expected behavior
addFormulaLocal to complete without error, 
Formula should show as a named item, 
formula should function properly when used in the spreadsheet.

## Current behavior
addFormulaLocal fails with diagnostics shown below

## Steps to reproduce
1. run the gist below in Excel ScriptLab.  Click the "Does not work" button and observe the console output.
2. paste the excel code in the attached file into the Advanced Formula Environment and observe that it works

## Link to live example(s)
https://gist.github.com/timnudecision/e360c0599657c443ad1acdeaa71ee414

# Provide additional details

## Context
I generate a lengthy LAMDA and I want to make it a named item function.

## Useful logs
Error: InvalidArgument: The argument is invalid or missing or has an incorrect format.
src/taskpane/taskpane.ts:1765
Debug info: {"code":"InvalidArgument","message":"The argument is invalid or missing or has an incorrect format.","errorLocation":"NamedItemCollection.addFormulaLocal","statement":"var addFormulaLocal = names.addFormulaLocal(...);","surroundingStatements":["var workbook = context.workbook;","var names = workbook.names;","var name = names.getItem(...);","name.delete();","// >>>>>","var addFormulaLocal = names.addFormulaLocal(...);","// <<<<<"],"fullStatements":["Please enable config.extendedErrorLogging to see full statements."]}
[my formula.txt](https://github.com/OfficeDev/office-js/files/9759692/my.formula.txt)

**Comment by honxmsft** [comment]
Hi @timnudecision, I've tried to validate the formula in gist.

It seems you need to remove the semicolon `;` at the end.

```ts
 context.workbook.names.addFormulaLocal("fy", 
          "=LAMBDA(Age, Years, LET(hits, MAKEARRAY(3,  1,  LAMBDA(r,c, IF(c=1,SWITCH(r,1, AND(AND(Years >= 15, Years < 30)),2, AND(Age >= 45),3, AND(TRUE))))),outs, MAKEARRAY(3,2,LAMBDA(r,c,SWITCH(r,1, SWITCH(c,1,true,2,3),2, SWITCH(c,1,true,2,4),3, SWITCH(c,1,false,2,5)))),results, FILTER(outs, hits),results))", 
         "works");
```

You can try with the script above.

**Comment by timnudecision** [comment]
Thanks for the quick work.

I have an interesting report.  Removing the semicolon resolves the issue on Windows, but not Mac.  Perhaps the Mac code lags the Windows in this case?

**Comment by AkhileshShah-MS** [comment]
Thanks for reaching out to us. 
@guliums could you please help with the issue? 
Thanks!
