### ISSUE TITLE
IPAD Excel 2.65.1 version possible issue with event handler

### ISSUE THREAD

**Issue by roby100s** [OfficeDev/office-js#2896]
I developed an addin on Windows within the JS office framework and the target environment is IPAD.
I  have an event handler managing on change data in a table, but on the Excel 2,65.1 on IPAD the event handler is not invoked any more while it was working with previous Excel releases and it's still working on Windows and Office on the web from the Safari browser on IPAD.
I would like to know if an issue has been already identified with the Excel 2.65.1 for IPAD event handler.
Thanks in advance

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Development platform Windows , Office JS framework, target IPAD
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2.65.1
* Operating System: IPADOS 15.7
* Browser (if using Office on the web): Safari
 
## Expected behavior
The event handler should be activated when a change occurs in a worksheet on the addin sideloaded into the IPAD

## Current behavior
I am experiencing an issue with the event handler on data changed in a worksheet table on the IPAD with Excel 2.65.1. With this  Excel IPAD version (2.65.1) it seems that the event handler is not called any more while it was working with the previous versions.
On Windows, Excel on the Web on IPAD browser (Safari) everything is working fine except with this IPAD Excel version and the issue is also that I can't revert back to a previous IPAD version :(

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ghost** [comment]
Thank you for letting us know about this issue. We will take a look shortly. Thanks.

**Comment by roby100s** [comment]
Unfortunately, even with the new IPAD Excel version 2.67.2 , the issue with the Event Handler not triggered is still present.
This feature is quite critical for the project and we are facing a significant delay, please can you let us know at least a tentative schedule for the solution ?

**Comment by roby100s** [comment]
I confirm that the EventHandler issue on IPAD is still not solved on the new release 2.68  !!

**Comment by rdf1923** [comment]
Is there any news regarding the investigation of this issue ??
Thanks in advance for any feedback.

**Comment by jipyua** [comment]
hi @roby100s @rdf1923, for this issue I tried on the latest ipad excel version 2.84.1 and use the following code to add a table on changed event. The data changed event is working fine for me. Would you please have a try again and if you can still hit this, would you please share your code or workbook and some detailed repro steps? thanks.

    async function bindTable() {
      await Excel.run(async (context) => {
        let table = context.workbook.tables.getItem("MyTable");
        table.onChanged.add(onChange);
        await context.sync();
        console.log("A handler has been registered for the onChanged event");
      })
    }
    async function onChange(event) {
      await Excel.run(async (context) => {
        console.log("Handler for table onChanged event has been triggered. Data changed address:" + event.address)
      })
    }

**Comment by XuanZhouMSFT** [comment]
We appreciate your feedback and the details you provided about this issue. However, we have tried to reproduce the issue on our end and we were not able to do so. Therefore, we have decided to close this issue for now, but we will keep an eye on it and re-open it if you encounter any issue in the future.
