### ISSUE TITLE
Add OnAppoinmentSend event to Office.EventType for handle send event

### ISSUE THREAD

**Issue by aqewd** [OfficeDev/office-js#2897]
# Add OnAppoinmentSend event to Office.EventType for handle send event

I want to handle `OnAppoinmentSend `event from taskpane in `AppointmentOrganizerCommandSurface` for synchronous request to my Service with custom data from taskpane. I can't use LaunchEvent because I need a taskpane for handle custom data. Or is there any other way to solve my problem?

# Your Environment

- Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Office on the Web
- Host [Excel, Word, PowerPoint, etc.]: Outlook
- Office version number: Outlook Web, Micrisoft Office Professional Plus 2019
- Operating System: Windows 11

# Link to live example(s)
![case](https://user-images.githubusercontent.com/63068601/195657337-70a997f3-1d56-44e5-82b9-7e6b5aa4aa8a.gif)

# Steps to reproduce

1. Open calendar tab
2. Click `New Event`/`New Meeting`/`New Appoinment` button
3. Change some meeting details
4. Click `Save`/`Save & Close`/`Send`
5. Handle this event

**Comment by AkhileshShah-MS** [comment]
Thanks for reaching out to us! 
@exextoc could you please help with this issue? 
Thanks!

**Comment by exextoc** [comment]
As per for description above it looks like you are trying to save custom data before handling OnAppoinmentSend event . You can achieve it via [Session Data ](https://learn.microsoft.com/en-us/javascript/api/outlook/office.sessiondata?view=outlook-js-preview) . After saving the custom data in session data ,you can read it while listening to AutoRun event OnAppoinmentSend

**Comment by aqewd** [comment]
Thanks a lot, that's how I did it.
