### ISSUE TITLE
Body.getHtml() does not return all HTML classes

### ISSUE THREAD

**Issue by mkm17** [OfficeDev/office-js#2898]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.15810.41017
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Body.getHtml() should return data with classes used in web like:  _SpellingErrorV2Themed_. 

## Current behavior
The function returns HTML data without all classes shown on the editor

## Steps to reproduce
1. Write text with a spelling error
2. Inspect the editor with the browser inspector (get source 1)
4. Invoke the Body.getHtml() function and get source 2)
5. Compare source 1 and source 2

## Context
Some time ago, I have created a test extension for the MS Word application that counts a number of incorrect words provided in the editor. Previously, an HTML class for spelling errors was returned by using the getHtml function. Two weeks ago, I noticed that the class is not returned by the function anymore. 

I can see in the documentation that the function returns _the formatting will be close, but not exact_, so the effect presented nowadays is correct. Still, I am wondering if there is any possibility to get a similar HTML presented in the editor as it was done before.

Thank you in advance.

**Comment by RuizhiSunMS** [comment]
We have caught the problem and are investigating.

**Comment by mkm17** [comment]
@RuizhiSunMS thank you for checking. If there will be a need to provide more info, I am eager to provide the requested details

**Comment by mkm17** [comment]
@RuizhiSunMS Hi, I was wondering if you need any further information from me to resolve the issue.

**Comment by RuizhiSunMS** [comment]
Another colleague from other team created a bug to track this issue since this one is not owned by us indeed. I realize that he has closed that bug. I'd contact him for further information.

**Comment by RuizhiSunMS** [comment]
Sorry to reply so late. 
In fact, we found another problem while investigating your issue and that found invoked a fix from another team. We are still investigating because we need to wait for their fix's release.

**Comment by mkm17** [comment]
@RuizhiSunMS Thank you for the response. I will wait for further information.

**Comment by RuizhiSunMS** [comment]
We create a work item #7010550 to track this issue. Share this info for that we can't give exact timeline.

**Comment by mkm17** [comment]
Dear @RuizhiSunMS, is there any update on the issue?

**Comment by RuizhiSunMS** [comment]
@mkm17 sorry for so late update. After having discussion with @xiruatms, I can share that, usually we would add one or several specific classes into the function's supported class list. And if the user does have such requirement, please submit your request in this channel, stackoverflow channel or https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and give details of the class you want. Our pms and engs would go through those channels and generate work items.
If you want to have a new request, I'd like to close this issue on Feb 18th. Thx.

**Comment by mkm17** [comment]
Hi @RuizhiSunMS, After some time I have managed to resolve this issue with some bypasses. Thank you for still having me in the loop. From my perspective, you can close this issue.

**Comment by RuizhiSunMS** [comment]
Thx @mkm17 , nice to hear that the issue doesn't block you anymore. Thanks for using our products and welcome to submit issues if you encounter any problems.
