### ISSUE TITLE
Stability issues on Excel Online (but not Excel for Mac): internal error

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#2899]
Dear Office.js team, could I please ask you to review one session from telemetry to help us get more insight into what's going on?

The session ID is 8c8e43eb-0337-41e4-98ce-d792bbde60bd.

On one report that returned several thousand errors from cells, one of our company, @gmichaud (but not me for whatever reason), is able to consistently receive a "crash message box" with "sorry, something went wrong".

![image](https://user-images.githubusercontent.com/5159662/196158671-6003e9e7-a537-4b2c-8cb6-8ce5404bef87.png)

After some point of time, all Excel.run object model interactions simply stop working.

![image](https://user-images.githubusercontent.com/5159662/196158777-56925e0f-7ce1-4357-a86a-6d642656d0ea.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: latest
* Operating System: Mac
* Browser (if using Office on the web): Edge latest on the Mac
 
The "crash" is consistent in 100% of the cases, and it disappears if we fix all those cells that return an Excel.Error instead of a result. (there may be be several thousand of those).

At the same time it never happens on Excel for Mac desktop.

**Comment by SiruiSun-MSFT** [comment]
Hi Pavel Kabir, 
As of now, we are still locating the exact reason. Can you provide a few more session ids, and provide us with the time (PST time zone) of this session? This will be of great help to our investigation. Thanks~

**Comment by wh1t3cAt1k** [comment]
@SiruiSun-MSFT we identified the root cause in our code that led to the crash box, so that you can better reproduce it and improve messaging / behaviour around the error.

This call:

```
Office.addin.setStartupBehavior(Office.StartupBehavior.load);
```

Was not **await**ed in our code (we have since enabled the linter rule to catch floating promises).

And _sometimes_ (race condition) subsequent interactions with Excel failed with an internal error.

Things that were happening while the call was not awaited:

- We used `Office.context.document.settings.refreshAsync()` / `get` / `set` / `saveAsync`
- We invoked `Excel.run` and searched for a workbook with a particular name

Each of the above two operation types could result in an internal error if `setStartupBehavior` was not awaited.

**Expected result**:

* Better error messaging
* alternatively, more resilient object model calls that will internally await for startup behaviour changes

**Comment by SiruiSun-MSFT** [comment]
@wh1t3cAt1k Sorry for the slow response. And thanks for your investigation and feedback. That's really useful for us. We will discuss this issue with our PM to do more optimization. Thanks!

**Comment by SiruiSun-MSFT** [comment]
Hi @wh1t3cAt1k , we open a new task to track this ask(https://office.visualstudio.com/OC/_workitems/edit/7214821). And since we track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please also add your request there. Feature requests on are considered when we go through our planning process. Thanks, Microsoft 365 Developer Platform team
