### ISSUE TITLE
Web Inspector doesn't work for Dialogs

### ISSUE THREAD

**Issue by htryggva** [OfficeDev/office-js#290]
Being able to use the Web Inspector for add-in panes is fantastic but it unfortunately doesn't seem to work for dialogs opened using the Office.context.ui.displayDialogAsync method.

Whenever I right click on the dialog and click 'Inspect Element', the bottom of the dialog starts flickering.

**Comment by htryggva** [comment]
Thanks @Reezaali. I can verify that the workaround works for me 👍

**Comment by JuaneloJuanelo** [comment]
@Reezaali  can you please add the bug number you are referring to?

**Comment by Reezaali** [comment]
@JuaneloJuanelo - here you go.
[https://office.visualstudio.com/DefaultCollection/OC/OEP/_workitems/edit/2420400](https://office.visualstudio.com/DefaultCollection/OC/OEP/_workitems/edit/2420400)

**Comment by kbrandl** [comment]
@JuaneloJuanelo are you able to provide any input on this issue? (Please let me know if this should be directed to someone else.)

**Comment by danielgwilson** [comment]
@kbrandl this _may be fixed_ in the most recent build - I'll confirm.

**Comment by kbrandl** [comment]
@danielgwilson thanks for this info! I've assigned this bug to you (instead of Juan), and we look forward to hearing what you find out. Thanks again!

**Comment by Reezaali** [comment]
@htryggva this issue has been resolved. If you still experience this issue, trying updating Office. I added a note to the documentation in this [PR](https://github.com/OfficeDev/office-js-docs-pr/pull/922). Thank you!

**Comment by kbrandl** [comment]
Closing this issue now, since the bug has been resolved and the doc updates have been submitted for publication ([PR 922](https://github.com/OfficeDev/office-js-docs-pr/pull/922) in OfficeDev/office-js-docs-pr).

**Comment by htryggva** [comment]
@Reezaali I can verify that the issue is resolved on my side too. Thanks a lot!
