### ISSUE TITLE
Office add-in appear in web excel document

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#2900]
Hello,

Before making the add-in available we have to add the following in the manifest to prevent the add-in for being loaded in Excel Web:
`<Set Name="OpenBrowserWindowApi" MinVersion="1.1"/>`

```
  <Requirements>
      <Sets DefaultMinVersion="1.1">
          <Set Name="SharedRuntime" MinVersion="1.1"/>
          <Set Name="OpenBrowserWindowApi" MinVersion="1.1"/>
      </Sets>
  </Requirements>
```

1. Make add-in available for the whole organization
2. Install add-in locally on Excel Desktop
3. Create & save an Excel document in the cloud with add-in loaded. 
4. Open document in Excel Web
5. **Add-in gets loaded( I see the ribbon and everything) but it is not working**

**Not OK**: When I open the document in Excel Web I expect that my add-in will not be available at all because as it says in the manifest `OpenBrowserWindowApi` should be available for the client.
Excel Web does not support `OpenBrowserWindowApi` and it should not even load the add-in as the manifest states it as a requirement.

Not sure how to prevent the add-in from being loaded when we are in Excel Web. Can you please give me another alternatives?

**Comment by AkhileshShah-MS** [comment]
Thanks for reaching out to us. 
@yaweizhu-henson could you please help the customer with this request? 
Thanks!

**Comment by danielpdev** [comment]
ok, I found out what the issue is: 
if I make a call to `Office.addin.setStartupBehavior(Office.StartupBehavior.load)`. Next time I open excel document Excel Web/ Excel Desktop, the add-in will be by default loaded, which is not desired because the requirements in the manifest should prevent this.

any ideas or alternatives to `Office.addin.setStartupBehavior(Office.StartupBehavior.load)` or fixing the main issue ?

**Comment by danielpdev** [comment]
Hi @yaweizhu-henson, do you know if this is a bug or something?

**Comment by danielpdev** [comment]
@RuizhiSunMS  so this is a bug?

**Comment by donlvMSFT** [comment]
Hi @danielpdev , sorry for the late response. We noticed that there might be some settings conflict in your case. 

Does this problem still occur now? If it still occurs, we will open an internal bug to track this issue. Or you can provide the scale of affected users, it will help us re-prioritize this problem. 

Thanks for your patience!
