### ISSUE TITLE
OnNewMessageCompose event not triggered by Quick Steps action

### ISSUE THREAD

**Issue by JackTheDane** [OfficeDev/office-js#2902]
When composing an email using an action triggered via Quick Steps, any `OnNewMessageCompose` is not triggered

## Your Environment

* Platform: PC desktop
* Host: Outlook
* Office version number: 2210
* Operating System: Windows 10
 
## Expected behavior
`OnNewMessageCompose` should trigger the same when a new message is composed, whether from Quick Steps or the "New Email" button in Outlook.

## Current behavior
The `OnNewMessageCompose` event only triggers when using the "New Email" button, but not when composing a new message / reply / forward via a Quick Steps action.

## Steps to reproduce
1. Install a Web Add-in that uses `OnNewMessageCompose` (I used the official `set-outlook-signature` sample)
2. Create a Quick Steps action to create, forward, or reply to a mail
3. Use the Quick Steps action to compose an email. You should see no result from the event.

## Link to live example
I was able to reproduce the issue using the live manifest from the official `set-outlook-signature` sample ([Link](https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/outlook-set-signature/manifest.xml))

Here is a demo of the issue, first showing the event working with "New Email", then showing it not triggering for Quick Steps:
![OnNewMessageComposeError](https://user-images.githubusercontent.com/35668734/196632667-535d3777-ccb9-412a-a0fd-03a652dc70b0.gif)

## Context
We are trying to set signatures using the `OnNewMessageCompose`, but are having mixed results, as users that use Quick Steps aren't getting their signatures set automatically.

## Useful logs
Looking at the logs for the event, there is no sign of the `OnNewMessageCompose` being registered or activated when composing from Quick Steps.

## Other remarks
It is worth noting that using the `OnMessageCompose` event introduced in requirement set 1.12, the behaviour is as expected and it works with Quick Steps.

However, according to documentation, this should only be the case if the composed message is a draft, which it should not be.

**Comment by AkhileshShah-MS** [comment]
Thanks for reaching out to us. 
@exextoc could you please help customer with this request? 
Thanks!

**Comment by exextoc** [comment]
@JackTheDane, sorry for the delay in responding. We are able to reproduce this issue and we have placed it in our backlog. Unfortunately, we have no timelines to share at this point.

Internal tracking id: Office: 5896103

**Comment by exextoc** [comment]
@JackTheDane, we have fixed this issue and the fix should be available in build 16.0.16201.10000 or later.
When an updated build is available depends on the release channel a customer is on.
