### ISSUE TITLE
Office add-in issue content control Word and table Powerpoint

### ISSUE THREAD

**Issue by ChienHo** [OfficeDev/office-js#2905]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We encountered a few bugs that we want to bring to your attention and see if there are any plans to address these in the near future? They are currently affecting a few enactments we are working on with our Domo Add-ins.
1. Content control loses it’s content after browser refresh: [Content-control-issue.zip](https://github.com/OfficeDev/office-js/files/9831539/Content-control-issue.zip)
2. These two MS errors are preventing our team to refresh tables inserted into PPT:
  a> [1-delete-slide-with-table.webm](https://user-images.githubusercontent.com/30323038/196990411-ea237565-1318-49bc-be57-8cff6dd0c401.webm)
  b> Cannot select slides  => [2-goToSlideById-bug.webm](https://user-images.githubusercontent.com/30323038/196990559-4f90514d-8144-45bd-b5e0-3a48122b181c.webm) I believe this was fixed in the preview api only

Please let us know if you need additional information and next steps to address these issues.

**Comment by ElizabethSamuel-MSFT** [comment]
@ChienHo Thanks for letting us know about these issues.

@RuizhiSunMS Can you take a look?

Thanks.

**Comment by RuizhiSunMS** [comment]
As for Point 1 about Content Control, our colleague eng has ack and is investigating.
And for Point 2, @ononder please take a look?

**Comment by xuruiyao-msft** [comment]
@ChienHo  could you please provide the code about how you insert the content control with the image? Thanks.

**Comment by ChienHo** [comment]
@xuruiyao-msft , here's the code: https://gist.github.com/ChienHo/4a177cb823f8b10072e1f51901cba6bb

**Comment by jipyua** [comment]
hi, for the first issue "Content control loses it’s content after browser refresh: [Content-control-issue.zip](https://github.com/OfficeDev/office-js/files/9831539/Content-control-issue.zip)". You mentioned that "after browser refresh", do you see this issue on word desktop or word online?

**Comment by ChienHo** [comment]
@jipyua , It happens on word online.

**Comment by RuizhiSunMS** [comment]
@ChienHo My colleague tried but failed to reproduce it. Can you share some other information like platform, versions or others special.

**Comment by ChienHo** [comment]
Here is a simpler example that can reproduce the issue more consistently. After browser refresh, the title and table get outside of the content control.

$("#run").click(() => tryCatch(run));

async function run() {
  await Word.run(async (context) => {
    const selectionRange = context.document.getSelection();
    const paragraph = selectionRange.insertParagraph("", "Before");
    await context.sync()
    const cc = paragraph.insertContentControl();
    cc.tag = "tag";
    await context.sync()
    cc.insertHtml("<p>test</p><table><tr><td>test</td></tr></table>", "End");
    await context.sync();
  });
}

async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}

**Comment by ChienHo** [comment]
@RuizhiSunMS ,  I'm using Chrome Version 107.0.5304.107 (Official Build) (64-bit) on Windows 10 Pro 21H2

**Comment by ChienHo** [comment]
@RuizhiSunMS

**Comment by xiruatms** [comment]
@ChienHo , the contentcontrol issue should be fixed now, will you please take a try?
