### ISSUE TITLE
[Outlook] Office-js need a default timeout setting to release queue

### ISSUE THREAD

**Issue by Howard-Song** [OfficeDev/office-js#2906]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___
* Host [Excel, Word, PowerPoint, etc.]: ___Outlook___
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior

In our add-in, I set a local queue to let Office-JS API will called one by one, and set the timeout to 30s. I expected if every Office-JS api have a timeout setting to release the no response API(which are timeout in 30s or other time) from queue.

## Current behavior

If API have no response in 30s, my add-in will start the next API call. And I have a loop function which will send about 8 request in 300ms, and each loop will wait the previous loop is finished. So when some API call timeout in 30s, and the Office queue is full filled with 50 API calls. This error will come out:
```javascript
{"name":"API Call Failed",\"message":"Wait until the previous call completes.","code":5100}
```
## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Currently the feature you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by Howard-Song** [comment]
@exextoc Thank you, will post in to the [Tech Community Page](http://aka.ms/M365dev-suggestions).
