### ISSUE TITLE
contentControl (insertHTML) broken after re-opening document

### ISSUE THREAD

**Issue by anna-feliz** [OfficeDev/office-js#2907]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

In my office js app for Word, sometimes a content control looses connection, so I cannot see the content control any longer, and then the document is broken for inserting new content controls of that type. I am not able to delete the broken content control, and I am not able to insert text into the broken content control. The broken content control is not visible in the document, but it exists, since it is not a null object. In short, after the content control is broken I am forced to start a new document, because the one I work with will no longer function. I am using the contentControl.insertHtml. 

The content control sometimes disappears / breaks after I close and re-open the document - not every time. Sometimes the content control is still there, but it has moved to be outside of the paragraph I inserted inside of it. 

Has anybody else encountered this issue?

Is it possible to do anything at all after a content control has been broken? Is it possible to remove it in some manual way? Or remove the entire list of a certain type of content control?

Here is a long example explaining what happens after a broken content control:

```
const example = context.document.contentControls
  .getByTag("example")
  .getFirstOrNullObject();
context.sync();

if (!example.isNullObject) {
  console.log("Example: ", example);
  // This logs meaning that the first object with tag "example" is not a null object, 
  // so it exists somehow. 
  // Logs: "Example: n {m_contextBase: n, m_objectPath: t, m_context: n, _IsTracked: true}"

  example.insertHtml("Example text in existing content control", Word.InsertLocation.replace);
  context.sync();
  // This breaks and the rest of the code does not continue. 
  // But, if I remove this, and we continue anyways this happens: 

  example.delete(false);
  context.sync();
  console.log("Deleted"); // This is not logged meaning that it breaks on deleting the content control
}

 // What if I insert a new content control of the same type?
 const range = context.document.getSelection();
 const contentControl = range.insertContentControl();
 contentControl.title = "Example";
 contentControl.tag = "example;
 contentControl.appearance = Word.ContentControlAppearance.boundingBox;
 contentControl.insertHtml("Example in new content control", Word.InsertLocation.replace);
 contentControl.color = "lightSkyBlue";
 await context.sync();
     
 const html = contentControl.getHtml();
 await context.sync();
 console.log("html", html.value); // This is logged with the correct value
```

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac Office on the web using chrome
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Web
* Operating System: Mac OS 
* Browser (if using Office on the web): Chrome
 
## Expected behavior
The content control to be where it was before closing the document. 

## Current behavior

The content control sometimes disappears completely, sometimes it moves so it surrounds only part of the paragraph I inserted into it, and sometimes it moves so it is located right below the paragraph it was supposed to surround. 

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

## Context

I am creating a bibliography, that has to be able to be updated accordingly.

**Comment by RuizhiSunMS** [comment]
@anna-feliz Thanks for reporting this issue. Our Eng has reproduced the issue. Then the ADO #7010550 is created to track this issue. 
Will update here if new information comes in but we can't provide a timeline now.

**Comment by anna-feliz** [comment]
This is definitely a bug. I have tried the following piece of code with insertText, and another example with insertOoxml, and then it has no issues. 
```  
  const click = () => {
    return Word.run(async (context) => {
      let cc = context.document.contentControls.getByTag("test").getFirstOrNullObject();
      await context.sync();
      if (cc.isNullObject) {
        const range = context.document.getSelection();
        cc = range.insertContentControl();
        cc.title = "Test Box";
        cc.tag = "test";
        cc.appearance = Word.ContentControlAppearance.boundingBox;
        cc.color = "lightSkyBlue";
        await context.sync();
      }

      cc.insertHtml(
        "<h2>An Unordered HTML List</h2><ul>  <li>Coffee</li>  <li>Tea</li>  <li>Milk</li></ul>  <h2>An Ordered HTML List</h2><ol>  <li>Coffee</li>  <li>Tea</li>  <li>Milk</li></ol>",
        Word.InsertLocation.replace
      );
      await context.sync();
    });
  };
```
This is directly after inserting the piece of html-code: 
<img width="724" alt="bild" src="https://user-images.githubusercontent.com/5991226/198541950-04dd4de6-9579-4585-addf-0d9aa21900a0.png">

If I reload the document (In chrome browser) the following happens: 
<img width="690" alt="bild" src="https://user-images.githubusercontent.com/5991226/198542320-6f7d9dfe-a088-4c4b-8341-998c9ea62adc.png">

Please fix this as quickly as possible. Or can you please suggest me another path forward? I want to use if for inserting a bibliography, that will automatically reload as the document is updated. The bibliography is using a lot of styled text. Is it better to use insertText or insertOoxml? I Prefer using insertHtml as it is so convenient, but it is not working so. 

Thank you for your time, and good luck!!!
Have a wonderful day!
