### ISSUE TITLE
Word | Fetching creationDate of copied comments in OfficeJS returning "1899-11-30T00:00:00.000Z"

### ISSUE THREAD

**Issue by rutvik95** [OfficeDev/office-js#2908]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
The creationDate on comments copied from another document is returning "1899-11-30T00:00:00.000Z" in OfficeJS.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2209 Build 16.0.15629.20200) 64-bit 
* Operating System: Windows 11
* Browser (if using Office on the web): NA
 
## Expected behavior
Ideally, the creationDate returned should be the date on which the comment was actually created in the old document. 
In Word -> Review-> Show Comments, the creationDate is showing correctly.

## Current behavior

When a paragraph, which has comments, is copied to a new word file, and the Word API is used to fetch comments from the new document, the creationDate for such copied comments is returning "1899-11-30T00:00:00.000Z".
In Word -> Review-> Show Comments, the creationDate is showing correctly.

## Steps to reproduce
1) Copy a paragraph with comments into a new document
2) When OfficeJS is used to fetch comments on the new document, the creationDate of the copied comments is returned as "1899-11-30T00:00:00.000Z"

## Link to live example(s)

1. [Link to Script](https://gist.githubusercontent.com/rutvik95/252ea1b91a72eb3084e3968604cdda9e/raw/c9c9d4311692b9d7b111aacb6defc39cf77011ee/Fetch%2520Comments.WORD.yaml)

# Provide additional details

NA

## Context

We are trying to filter comments in a document based on the creation date.

## Useful logs

- [ ] Console errors - NA
- [ ] Screenshots -NA 
- [ ] Test file (if only happens on a particular file) -NA

**Comment by xuruiyao-msft** [comment]
@rutvik95 
1, Would you please describe how to copy the paragraph into a new file? By Office-JS API or manually?
2, The 'link to script' in 'Link to live examples' part only includes the APIs of getComments and comment's items. I cannot reproduce the issue using the provided script. Would you please double check if the script is correct?
Thanks for reporting the issue. I will keep close eye on this issue until it fixed. Feel free to provide more details about the issue.

**Comment by rutvik95** [comment]
> @rutvik95 1, Would you please describe how to copy the paragraph into a new file? By Office-JS API or manually? 2, The 'link to script' in 'Link to live examples' part only includes the APIs of getComments and comment's items. I cannot reproduce the issue using the provided script. Would you please double check if the script is correct? Thanks for reporting the issue. I will keep close eye on this issue until it fixed. Feel free to provide more details about the issue.

@xuruiyao-msft  

Thank you for your response. 

1. The paragraph was manually copied.
2. The linked script had worked for me. However, it seems there is some other action or other variable, in addition to copying the paragraph with comments, which may be causing the issue that I haven't been able to figure out yet. 

On another note, in the documents where it is occurring, the comments.xml file seems to be showing the correct date and time although Office-JS isn't. 

Below is the link to the test document: [Link](https://1drv.ms/w/s!AjHtzfrdaTpOif5oj-kieEaB3EQJvA?e=mIb4I7).

EDIT 1: In the test document, the script ([in the original post](https://gist.githubusercontent.com/rutvik95/252ea1b91a72eb3084e3968604cdda9e/raw/c9c9d4311692b9d7b111aacb6defc39cf77011ee/Fetch%2520Comments.WORD.yaml)) returns the creationDate as "1899-11-30T00:00:00.000Z"

EDIT 2: Tag and quote earlier comment

**Comment by xuruiyao-msft** [comment]
@rutvik95 Would you please attach the word document but not put the link. Sorry that I cannot login to the Link. It would be better for me to download the file and open it on PC desktop.

**Comment by rutvik95** [comment]
> @rutvik95 Would you please attach the word document but not put the link. Sorry that I cannot login to the Link. It would be better for me to download the file and open it on PC desktop.

@xuruiyao-msft  Sorry, the link must have expired. That's why it's asking for a login.

I have attached the file for your ease of access.

[TestFile.docx](https://github.com/OfficeDev/office-js/files/9906360/TestFile.docx)

**Comment by xuruiyao-msft** [comment]
@rutvik95 Thanks. I open the document and the date of the existing comments are normal, but the script lab shows the Dates of all the comments are "1899-11-30T00:00:00.000Z". 
But I append a new paragraph into the existing document, copy the paragraph to append at the tail. The new added comments' date is normal too.
Is this issue existing in this doc only? Could you reproduce it on a new document?

**Comment by rutvik95** [comment]
> @rutvik95 Thanks. I open the document and the date of the existing comments are normal, but the script lab shows the Dates of all the comments are "1899-11-30T00:00:00.000Z". 
> But I append a new paragraph into the existing document, copy the paragraph to append at the tail. The new added comments' date is normal too.
> Is this issue existing in this doc only? Could you reproduce it on a new document?

@xuruiyao-msft 
So I think I've figured out the issue. 
It seems to have nothing to do with copying comments. 

Comments created in Office 2013 (That's the only version I have apart from 365) are showing the date as "1899-11-30..." In OfficeJS. Since I don't have any other version of office, I am unable to confirm if the issue persists on comments created in office 2016 or 2019.


Should I close this issue and open a new one or update this issue?

**Comment by xuruiyao-msft** [comment]
@rutvik95 I will open a work item to track the issue. If there's any progress, I will update to you

**Comment by rutvik95** [comment]
> @rutvik95 I will open a work item to track the issue. If there's any progress, I will update to you

@xuruiyao-msft Thank you!

If it helps, the comment.xml file in the document, more particularly the w:date attribute, shows the correct timestamp for the comments.
