### ISSUE TITLE
How to support Edge legacy?

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#2909]
Now,I submit office addin to Office Store,and don't pass.

### Validation Failure:
![error](https://user-images.githubusercontent.com/3182964/197468399-d92c0922-b657-4c77-8cc6-a44efc3ef3bc.png)

### In Webview2 Runtime,it is OK!
![webview2](https://user-images.githubusercontent.com/3182964/197468512-55a90482-c17d-40da-9677-aaf741d2d5a4.png)
![webview22](https://user-images.githubusercontent.com/3182964/197468519-eeb257bf-bbb9-4595-9f74-fbf3815f6512.png)
![webview222](https://user-images.githubusercontent.com/3182964/197468522-e37bdea2-22e3-4f2a-8719-729e947f9f2f.png)

### When webview2 uninstalled,it is NG!
![webview1](https://user-images.githubusercontent.com/3182964/197468736-bc086acc-cb3f-4165-bbe1-02befd1dedcc.png)
![webview11](https://user-images.githubusercontent.com/3182964/197468740-86f52c82-91dc-4677-83ea-081c23d68e5a.png)
![webview111](https://user-images.githubusercontent.com/3182964/197468743-6185e223-5054-4d1c-8d09-b877755f204a.png)

Question1:
I installed Microsoft Edge DevTools Preview, Why Office.js error happens?

Question2:
how to debug the error in development?

**Comment by RuizhiSunMS** [comment]
Looks it's 'edge' related, @croicu suppose you might help it?

**Comment by hengchengfei** [comment]
I want to add error Handling in WebView1 or Edge Legacy.

How to detect if user is using  WebView1 or Edge Legacy? 

IE detect as follows:

### index.html
```html
    <div id="ieErrorWrapper" style="visibility: hidden">
      <div id="ieErrorText">
        <p>
          CFST Data no longer supports the Internet Explorer 11 browser or
          embedded browser control. Please upgrade to a
          <a
            href="https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins"
            target="_blank"
            >supported version</a
          >
          of Microsoft 365 or open Office on the web in a
          <a
            href="https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins"
            target="_blank"
            >supported browser</a
          >.
        </p>
      </div>
    </div>

  <script>
    var isIE = window.ActiveXObject !== undefined;

    // If currently in IE, replace the loading indicator with the ieErrorWrapper
    // which directs users to update their version of Office, or move to another browser
    if (isIE) {
      url = window.location;
      document.getElementById("ieErrorWrapper").style.visibility = "visible";
      document.getElementById("loading").style.visibility = "hidden";
    } else {
      document.getElementById("ieErrorWrapper").style.visibility = "hidden";
      document.getElementById("loading").style.visibility = "visible";
    }
  </script>
```

**Comment by Rick-Kirkham** [comment]
@hengchengfei Have you see this article? [Debug add-ins using developer tools in Microsoft Edge Legacy](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-devtools-edge-legacy)

**Comment by hengchengfei** [comment]
@Rick-Kirkham 

I had saw the link,it is OK.

```index.html
 <script>
    var isEdgeLegacy = false;
    const userAgent = navigator.userAgent;
    if (!!userAgent && userAgent.includes("Edge")) {
      isEdgeLegacy = true;
    }

    var isIE = window.ActiveXObject !== undefined;

    // If currently in IE, replace the loading indicator with the ieErrorWrapper
    // which directs users to update their version of Office, or move to another browser
    if (isIE || isEdgeLegacy) {
      url = window.location;
      document.getElementById("ieErrorWrapper").style.visibility = "visible";
      document.getElementById("loading").style.visibility = "hidden";
    } else {
      document.getElementById("ieErrorWrapper").style.visibility = "hidden";
      document.getElementById("loading").style.visibility = "visible";
    }
  </script>
```

**Comment by RuizhiSunMS** [comment]
Close this issue since the customer looks get the answer.
