### ISSUE TITLE
The title of dialog windows shows the target page URL on Windows

### ISSUE THREAD

**Issue by eugene-plutoflume** [OfficeDev/office-js#2911]
# Provide required information needed to triage your issue
Dialog boxes contain an URL of the target page in Outlook for Windows (desktop). All other platforms displays the `ProviderName` field from the add-in manifest.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.15629.20200
* Operating System: Windows x64
* Browser (if using Office on the web): Edge (Chromium) used in Outlook for desktop
 
## Expected behavior

On all platforms except Windows (Outlook desktop) the title string displays the `ProviderName` value from the manifest file. But in Outlook for desktop we get a `ProviderName` value concatenated with the page URL.

## Current behavior

In Outlook for Windows desktop we get a `ProviderName` value concatenated with the page URL. The result string is used for the title bar of dialog windows created by the `Office.context.ui.displayDialogAsync` method.

## Steps to reproduce

1. Use the `Office.context.ui.displayDialogAsync` method for displaying a dialog window in Outlook.
2. Deploy your add-in to any web server.
3. Use the production manifest to install/sideload the add-in.
4. In Outlook for Windows (desktop) the title contains the URL of the target HTML page.

# Provide additional details

![image](https://user-images.githubusercontent.com/32734640/197641669-44439235-459d-4f63-b3a6-522a54e388ca.png)

## Context

We would like to get a consistent behavior and UX across all platforms.

## Useful logs

- [ ] Console errors
- [X] Screenshots
- [ ] Test file (if only happens on a particular file)

Thanks

**Comment by Adrian-MSFT** [comment]
Hi @eugene-plutoflume,

We do not hide the url because this is a necessary security feature in order to keep the user informed of where the dialog was navigated.

**Comment by eugene-plutoflume** [comment]
Hi @Adrian-MSFT ,

Why do you let the url be displayed on Windows only? On the Mac OS we don't see the url, nor in web browsers.

**Comment by Adrian-MSFT** [comment]
Hi @eugene-plutoflume,

The original design was to expose the URL in the right click menu, but this does not work in Leagcy Edge or Anaheim, so it was moved to the title for these instances. We do have a backlog item to redesign this, however, I unfortunately have no timelines to provide on when that would be completed.

**Comment by abcdummy** [comment]
@Adrian-MSFT  As you have closed this issue, do we have any configuration to not show the address bar? 
or any update on backlog item?

**Comment by monika8093** [comment]
@Adrian-MSFT  I am trying to implement same web addin feature for my outlook. It working fine in web browser but in desktop outlook url is getting exposed to all the users which is not correct can you please help if we can fix this issue. I am using office.context.ui.displayDialogAsync() method to open the popup.
