### ISSUE TITLE
Outlook: Register the online-meeting template for Contoso

### ISSUE THREAD

**Issue by linsmac** [OfficeDev/office-js#2912]
Can you register the online-meeting template for our Contoso?
 "<br>" +
  '<a href="https://contoso.com/meeting?id=123456789" target="_blank">Join Contoso meeting</a>' +
  "<br><br>" +
  "Phone Dial-in: +1(123)456-7890" +
  "<br><br>" +
  "Meeting ID: 123 456 789" +
  "<br><br>" +
  "Want to test your video connection?" +
  "<br><br>" +
  '<a href="https://contoso.com/testmeeting" target="_blank">Join test meeting</a>' +
  "<br><br>"

Thanks.

**Comment by exextoc** [comment]
Can you please explain in details what are you trying to do here.
These are few questions i have
1)Are you trying to build a Meeting Addin??
2)Are you trying to add above text in event body??
3)If you are implementing an Addin can you please explain more in detail about your addin what it does
