### ISSUE TITLE
'OfficeRuntime.auth.getAccessToken' is not working in Safari

### ISSUE THREAD

**Issue by repl-minatee-p** [OfficeDev/office-js#2913]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am developing a word add-in which will run in all supported platforms such as Windows, Mac and all browsers.
But 'OfficeRuntime.auth.getAccessToken' throws 'Refused to display' error in Safari. Error screenshot is attached.
If I uncheck the 'Prevent cross-site tracking' option then it works, but we can't go with this work-around as it's going to be a public add-in.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: ______
* Operating System: MacOS Big Sur
* Browser (if using Office on the web): Safari version 14.0.3
 
## Expected behavior
It should return the access token.

## Current behavior
It's throwing 'Refused to display' error.

## Steps to reproduce

1. Use 'OfficeRuntime.auth.getAccessToken' to get the access token.
2. Open the add-in in Safari browser.
3. You can see the error in console.

## Useful logs

- [x] Console errors
![officejs_sso_safari_error](https://user-images.githubusercontent.com/107394673/197703899-02d240ae-1971-4cf7-b654-53db4c4f4363.jpg)

- [ ] Screenshots

- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuizhiSunMS** [comment]
This is a common API. @mattgeim I realized you handled another issue about this API once, can you please take a look?

**Comment by mattgeim** [comment]
This is related to tracking prevention in browsers - you can find information related to tracking prevention and how to address it in your add-in in our docs here:  https://learn.microsoft.com/en-us/office/dev/add-ins/develop/itp-and-third-party-cookies

**Comment by repl-minatee-p** [comment]
Sure, I will go through this doc. But we are also developing an outlook email add-in and in that case we don't see the same issue in safari browser. We are seeing this issue only for word/excel/powerpoint add-ins. And we are using the same 'OfficeRuntime.auth.getAccessToken' api in both the cases.
Why does this api work without any issue in outlook but not in word/excel/powerpoint ?
