### ISSUE TITLE
Style "Heading 1" at last paragraph missing after calling insertOoxml or setSelectedDataAsync

### ISSUE THREAD

**Issue by xchen9090** [OfficeDev/office-js#2914]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Our application converts a word document to OOXML and then inserted into another word document by using InsertOoxml() or setSelectedDataAsync() Javascript method. If the last paragraph has "Heading 1" style, it loses its style after it is inserted. I tried a few other styles and it works fine. It only occurs to the last paragraph. If we hit "Enter" and start the new paragraph and save the first document, the "Heading 1" style can be retained after it is inserted.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: ___Office 365 Apps for enterprise en-us__
* Host [Excel, Word, PowerPoint, etc.]: ___Word___
* Office version number: ___16.0.14931.20764___
* Operating System: __Windows 10 Enterprise, Version 21H1_____
* Browser (if using Office on the web): ______
 
## Expected behavior
After the Ooxml is inserted into the new word document, we should see the last paragraph with "Heading 1" style

## Current behavior
The last paragraph does not have style.

## Steps to reproduce
1. insertOoxml code we used:            
context.document.body
             .insertOoxml(ooxmlData, "Replace");
2. setSelectedDataAsync code we used:
Office.context.document.setSelectedDataAsync(ooxmlData, 
		{ coercionType: 'ooxml' },
		function(result) { deferred.resolve(result);}
	);
ooxmlData can be downloaded here https://docs.google.com/document/d/1z143v_ksg9S7l9nBXegU1tFFpUgwAnlNS6BIVckWiCM/edit?usp=sharing
The word doc after the ooxmlData is inserted can be downloaded here
https://docs.google.com/document/d/1QnJpRnL-_FgQwYqnKxs9_JMM4bnzF96KN5UI21chFYo/edit?usp=sharing

**Comment by RuizhiSunMS** [comment]
@xchen9090 Thanks for reporting the issue.
Our designed behavior is to clear any styles if no empty paragraph accompanied with the content when using that api. Then if you said that all styles would be cleared in this scenario, that's it. 
However, your case seems to be the 'heading 1' is the only invalid style when insert without empty paragraph.
Please make sure these details which can help our ENG to troubleshoot.
Thanks.

**Comment by xchen9090** [comment]
I just double checked. If the last paragraph uses "Intense References" style, it works fine. The problem is only on "Heading 1" style.

**Comment by xchen9090** [comment]
"Our designed behavior is to clear any styles if no empty paragraph accompanied with the content when using that api. "
- Do you mean by design the style should be removed for the last paragraph? For "Heading 1" style, it works as designed. The "Intense References" style is a bug that it retains the style?

**Comment by RuizhiSunMS** [comment]
@xuruiyao-msft

**Comment by jipyua** [comment]
Thanks for reporting this, after confirming inside team this sounds like a new request, we will open an internal bug to track this issue. thanks.
