### ISSUE TITLE
Outlook - Manage pane layout does not work in web version of Outlook

### ISSUE THREAD

**Issue by sashakar** [OfficeDev/office-js#2917]
# Provide required information needed to triage your issue
I would expect that in the web version of Outlook 365, I would be able to manage pane layout such as moving or resizing task panes the same way I could in the desktop version of Outlook. However I am unable to resize the task pane in the web.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior

I would expect to be able to resize the Outlook task pane in web because 1) I can resize the task pane of Outlook in the desktop version and 2) I can resize the task pane of the web version of other MSFT apps like PPT and Excel. The behavior is very inconsistent.

## Current behavior

Web version of Outlook does not provide ability to manage pane layout at all.

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

We use the task pane to launch an add-in for our product in Microsoft applications. Since there is limited real estate in a task pane to display information, the ability to resize the task pane especially in a browser affects the user experience and usability of our add-in.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Currently resizing of taskpane in Outlook Web is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
