### ISSUE TITLE
How to add a button into the appoinment summary

### ISSUE THREAD

**Issue by luketowell** [OfficeDev/office-js#2919]
Apologies if this is not the correct format but I have looked through the forums and blogs available online and I am unable to find any documentation for how to resolve my issue.

I am currently working on an add-in which allows a user to authenticate and create meeting sessions which is working as expected. We would now like to add a join meeting button to the meeting summary which pops up when the user selects the meeting from their calendar. 

<img width="476" alt="Screenshot 2022-10-26 at 09 11 16" src="https://user-images.githubusercontent.com/29888913/197971167-d8827502-270a-437e-9c55-db9dda06a32f.png">

Please can you let me know which part of the Outlook Javascript API will help me with editing and updating the meeting summary?

**Comment by exextoc** [comment]
The Join button is only supported in Outlook on the web, Mac, Android, and iOS. If you only see a meeting link, but don't see the Join button in a supported client, it may be that the online-meeting template for your service isn't registered on our servers. See the [Register your online-meeting template](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting?tabs=non-mobile#register-your-online-meeting-template) section for details.
