### ISSUE TITLE
Core Properties open xml package part is missing

### ISSUE THREAD

**Issue by serjant** [OfficeDev/office-js#292]
As long as Office JS converts the HTML into OOXML incorrectly in add-in when you set the content using **context.document.body.insertHtml()** function, I decided to write my own HTML to OOXML converter in order to set the document content using **context.document.body.insetOoxml()** function instead and to have almost similar HTML rendering in the Word content pane using OOXML format. After finishing editing the content, I want to send back the OOXML document from Word back to the server and to parse it back to HTML, so I fetch OOXML using **context.document.body.getOoxml()** function, but it transpires that the core properties open xml package part is missing inside the fetched OOXML raw value. The same thing happens when I try to get the core properties part using 
```js
Office.context.document.customXmlParts("http://schemas.openxmlformats.org/package/2006/metadata/core-properties", <Callback>)
```
 it contains dummy data instead of my actual real data. 
I thought that the issue could be in the wrong OOXML format and I had not set the Relation - but I double checked that I have set the Relation to core properties part - I constructed the docx package from OOXML and edited it directly using Word and then saved it locally. When I unpacked the this saved docx file - my core properties were still there with the same initial properties data.

## Expected Behavior
The core properties open xml package part should persist during document editing and can be retrieved inside the raw OOXML value or via 
```js
Office.context.document.customXmlParts("http://schemas.openxmlformats.org/package/2006/metadata/core-properties")
```

## Steps to Reproduce, or Live Example

1. Add relation of core.xml which will contain the core properties definitions

```xml
<pkg:part pkg:contentType='application/vnd.openxmlformats-package.relationships+xml'
            pkg:name='/_rels/.rels'>
    <pkg:xmlData>
      <Relationships xmlns='http://schemas.openxmlformats.org/package/2006/relationships'>
        <Relationship Id='rId3'
                      Target='docProps/app.xml'
                      Type='http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties'/>
        <Relationship Id='rId2'
                      Target='docProps/core.xml'
                      Type='http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties'/>
        <Relationship Id='rId1'
                      Target='word/document.xml'
                 Type='http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument'/>
      </Relationships>
    </pkg:xmlData>
  </pkg:part>
```

2. Inside the OOXML package set the predefined core properties in the core properties open xml package part:

```xml
<pkg:part pkg:contentType='application/vnd.openxmlformats-package.core-properties+xml'
          pkg:name='/docProps/core.xml'>
    <pkg:xmlData>
        <cp:coreProperties
                xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"
                xmlns:dc="http://purl.org/dc/elements/1.1/"
                xmlns:dcterms="http://purl.org/dc/terms/"
                xmlns:dcmitype="http://purl.org/dc/dcmitype/"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
            <dc:title>Core Document Properties</dc:title>
            <dc:subject>Core document properties</dc:subject>
            <dc:creator>David Baum</dc:creator>
            <cp:keywords>word; open xml; dublin core; microsoft office</cp:keywords>
            <dc:description>
                Core Document Properties Description
            </dc:description>
            <cp:lastModifiedBy>David Baum</cp:lastModifiedBy>
            <cp:revision>2</cp:revision>
            <dcterms:created xsi:type="dcterms:W3CDTF">2018-10-06T06:03:36Z</dcterms:created>
            <dcterms:modified xsi:type="dcterms:W3CDTF">2018-10-15T06:09:18Z</dcterms:modified>
            <cp:category>analysis</cp:category>
        </cp:coreProperties>
    </pkg:xmlData>
</pkg:part>
```

3. Construct the OOXML ([the file example](https://github.com/OfficeDev/office-js/files/2553626/ooxml.txt), initialize the Office in the add-in, and set the content:

```js
Word.run(async (context) => {
    let body = context.document.body;
    body.clear();
    body.insertOoxml(OOXML_VALUE, Word.InsertLocation.replace);
    await context.sync();
});
```

4. Try to load the OOXML back and print the raw value in the console:

```js
let documentBody = context.document.body;
let ooxml = documentBody.getOoxml();
await context.sync();
```

Examine the output - it does not contain the package part of type application/vnd.openxmlformats-package.core-properties+xml

5. Try to load the package part using the another API method Office.context.document.customXmlParts.getByNamespaceAsync("http://schemas.openxmlformats.org/package/2006/metadata/core-properties",  <Callback>) and output the subject node value from the core properties part:

```js
let xmlParts = Office.context.document.customXmlParts;
xmlParts.getByNamespaceAsync("http://schemas.openxmlformats.org/package/2006/metadata/core-properties", function (eventArgs) {
        let xmlParts = eventArgs.value;
      
        if(xmlParts.length > 0) {
            xmlParts[0].getNodesAsync('*/*', function (nodeResults) {
                for (let i = 0; i < nodeResults.value.length; i++) {
                    let node = nodeResults.value[i];
                    if(node.baseName == 'subject') {
                        console.log(node.nodeType + " " + node);

                        node.getTextAsync({asyncContext: "StateNormal"}, function (getTextAsyncResult) {
                            console.log("Text of the subject element = " + getTextAsyncResult.value);
                        });
                        break;
                    }
                }
            });
        }
    }
)
```

It turns out that nor the subject value is set neither the value is equal to one from the initial OOXML. The same thing with author and dates tag values. Why should Office JS API set its own data which does not make any sense?
 
## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]:  iMac Pro (2017)
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.20 (181031)
* Operating System: Mac OS version 10.14.2. Beta

**Comment by serjant** [comment]
Any news on that bug?

**Comment by kbrandl** [comment]
@JuaneloJuanelo are you able to provide any update on this issue?

**Comment by pziff** [comment]
@JuaneloJuanelo @kbrandl this is a pretty significant issue as it pertains to a key standard and should be used by virtually any add-in connecting Word to another system.  I see many other seemingly more minor issues getting more attention.  How can we escalate and get this resolved?

**Comment by JuaneloJuanelo** [comment]
ok, sorry for the late reply on this.
There are many issues that are been discussed on this thread.

1. There is no method on the API to convert from HTML to OOXML. you can get document content as HTML or OOXML and insert content as OOXML as well.  I am imagining that you want to keep 100 % fidelity and if that's the case, yes OOXML will be your best bet.  BTW Many kudos for making that project that's an amazing and complicated effort.

2.  if you want to get the entire file I dont recommend you to use document.getOOXML. I would rather get an entire copy of the docx using the getFIleAsync method (and then upload it to a server who can among other things get the OOXML using the OOXML SDK.

3.  If for whatever reason you still want to keep your logic to solve this problem, there are a few adjustments you can do. For instance, you are not using the right code to get the XML PArts. 

THis is the right code to use:  (just tried it and for no means returns dummy data. 
```
Office.context.document.customXmlParts.getByNamespaceAsync("http://schemas.openxmlformats.org/package/2006/metadata/core-properties",function(result){
    
    result.value[0].getXmlAsync(function(result){
      console.log(result.value);
    });
  });
```

Please try the code and let us know outcomes.

**Comment by serjant** [comment]
If you have ever read my detailed issue, you should have had a clear comprehensive picture - we had never tried to convert the HTML into OOXML - we set the plain OOXML and then extract it directly using Office JS API - Office.context.document.customXmlParts.getByNamespaceAsync (are you sure you followed my report?) method returns the empty core entities, please check my initial post
