### ISSUE TITLE
Wrong page size reported by getOoxml from paragraph

### ISSUE THREAD

**Issue by Stigjb** [OfficeDev/office-js#2920]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I use `getOoxml` to find out the document's page size. In some situations, the resulting OOXML reports a page size that is wrong. For example, when the document is non-empty and I call `getOoxml` on the first paragraph in the document body.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2209 Build 16.0.15629.20200) 64-biters 
* Operating System: Windows 10 Pro
 
## Expected behavior

The OOXML returned by `getOoxml` should reflect the actual page size settings in the document via `w:body > w:sectPr > w:pgSz`

## Current behavior

The page size values reported by OOXML from the document body's first paragraph differs based on the content of the document, even though the page size settings in Word have not been touched.

## Steps to reproduce

I've created this snippet in Script lab to print the OOXML page size element to the console.

https://gist.github.com/Stigjb/424d3180ab1d8f2389a123c905bc2f00

Open a blank document and change the page size for the document to something different than the default. I have used A3 when reproducing it myself. Run the snippet in Script lab, and it prints a pgSz with dimensions 16838x23811 (A3).
Return to the document and press Enter to insert a new, empty paragraph. The document now contains two empty paragraphs. Run the snippet in Script lab, and it prints a pgSz with dimensions 12240x15840 (US Letter).

# Provide additional details

I seem to have found a workaround by using the last paragraph in the body instead of the first. I have not yet had to deal with documents with several sections with different page sizes, so I don't know yet if the workaround is robust to that.

## Context

I'm creating an add-in to insert certain elements in a document that fit the page size. When the reported page size is wrong, the inserted elements do not fit the page.

**Comment by ghost** [comment]
Thank you for letting us know about this issue. We will take a look shortly. Thanks.

**Comment by RuizhiSunMS** [comment]
@xuruiyao-msft

**Comment by jipyua** [comment]
Thanks for reporting this, this sounds like an API bug, we will open an internal bug to track the investigation and fix.
