### ISSUE TITLE
Excel pivot table field bug when user renames the pivot field

### ISSUE THREAD

**Issue by SharonCKC** [OfficeDev/office-js#2923]
# When a pivot field is renamed by the user, there is no way to get the pivot items of the field
`Excel.RowColumnPivotHierarchy.getItem(pivotField.id).fields.getItem(pivotField.id).items.items` fails.

## Your Environment
* Platform: PC/Mac/Online
* Host: Excel
 
## Steps to reproduce
Given a pivot table "PivotTable1" containing only one row field named "ZIP", run this code:
```
return Excel.run(async (context) => {
      const hierarchies = context.workbook.pivotTables.getItem("PivotTable1").rowHierarchies.load("items");
      await context.sync();
      console.log("List of hierarchy IDs: " + hierarchies.items.map(i => i.id).join(", "));
      const hierarchy = context.workbook.pivotTables.getItem("PivotTable1").rowHierarchies.getItem("ZIP");
      await context.sync().catch(e => console.log(e.debugInfo));
      console.log("Hierarchy:" + hierarchy.id);

      hierarchy.load("fields");
      await context.sync().catch(e => console.log(e.debugInfo));
      console.log("List of field IDs: " + hierarchy.fields.items.map(i => i.id).join(", "));
      const field = hierarchy.fields.getItem("ZIP");
      await context.sync().catch(e => console.log(e.debugInfo));
      console.log("Field:" + field.id);
      field.load("items/items");
      await context.sync().catch(e => console.log(e));
      console.log("Pivot item count: " + field.items.items.length);
})
```

Everything works fine. The console result:

> [Log] List of hierarchy IDs: ZIP 
> [Log] Hierarchy:ZIP 
> [Log] List of field IDs: ZIP 
> [Log] Field:ZIP 
> [Log] Pivot item count: 3735 

Now rename "ZIP" pivot field to "ZIP2". The code doesn't work anymore:

> [Log] List of hierarchy IDs: ZIP
> [Log] Object
> code: "ItemNotFound"
> errorLocation: "RowColumnPivotHierarchyCollection.getItem"
> fullStatements: ["Please enable config.extendedErrorLogging to see full statements."] (1)
> message: "The requested resource doesn't exist."
> statement: "var rowHierarchie = rowHierarchies.getItem(...);"
> surroundingStatements: Array (7)
> 0 "var workbook = context.workbook;"
> 1 "var pivotTables = workbook.pivotTables;"
> 2 "var pivotTable = pivotTables.getItem(...);"
> 3 "var rowHierarchies = pivotTable.rowHierarchies;"
> 4 "// >>>>>"
> 5 "var rowHierarchie = rowHierarchies.getItem(...);"
> 6 "// <<<<<"

- This error occurs with both `columnHierarchies` and `rowHierarchies`. 
- Changing RowColumnPivotHierarchyCollection.getItem("ZIP") to RowColumnPivotHierarchyCollection.getItem("ZIP2") and changing PivotFieldCollection.getItem("ZIP") to PivotFieldCollection.getItem("ZIP2") doesn't work.

 
## Context
The ID of a pivot field does not change when the user renames the field, which is as expected.  However, trying to obtain the pivot field by its ID and the field's pivot items results in an error only when the user has renamed the field.

**Comment by yuc014** [comment]
@SharonCKC Thanks for reporting this issue.
It has been put on our backlog<Bug#7030980> for internal track. We will keep track of this issue and let you know if there are any updates.

**Comment by SharonCKC** [comment]
@yuc014 thank you for the update. Would you have any rough idea of timing for the fix?

**Comment by yuc014** [comment]
Hi @SharonCKC, we already had a plan for this quarter, sorry I cannot guarantee the time for fix.
Could you give me more details about this issue? For example, how many customers are impact, then maybe I could highlight this bug and raise its priority.

**Comment by SharonCKC** [comment]
@yuc014 Pivot tables is a new feature we will introduce in a few weeks. It would be awkward to have to tell customers that they cannot rename their pivot table's fields, otherwise weird things happen. Any chance the fix can make it in next quarter?

**Comment by yuc014** [comment]
@SharonCKC Thanks for reply, already highlight this workitem to partner team, will update when have progress.

**Comment by RuizhiSunMS** [comment]
@SharonCKC Partner team released a fix on this recently. Please check after updating and share the information.
And feel free to reopen this if the update doesn't work as expected.
The same with #2926

**Comment by SharonCKC** [comment]
@RuizhiSunMS neither of the two issues are fixed on my side. Tried on Excel Online in Chrome, and Excel for Mac.

**Comment by SharonCKC** [comment]
Office.js still cannot access the pivot items of the field when a pivot field is renamed by the user. Is there any update on this?

**Comment by dingjin-ms** [comment]
@SharonCKC Sorry for the late response, but this problem should have been fixed after build 16.0.16009.10000. Please let us know if the problem still occurs.

**Comment by SharonCKC** [comment]
Hi @dingjin-ms, thank you for your reply and for providing the build number.  We can confirm the fix in Online and Mac.  In Windows, we are still experiencing errors, but we are currently on an older build, so we will confirm the fix after the next update.

**Comment by SharonCKC** [comment]
Confirmed this bug is fixed in Windows.  Appreciate the work from the MS team!
