### ISSUE TITLE
Drag content from a TaskPane to a cell in Excel

### ISSUE THREAD

**Issue by marindedic** [OfficeDev/office-js#2924]
I am trying to figure out a way to drag an element (for example text), from the TaskPane to an Excel cell. However, I can't seem to find any documentation about that. Is that feature not supported without making workarounds? The only example I found was the wiki add-in: https://learn.microsoft.com/en-us/answers/storage/attachments/110013-drag-n-drop.gif

**Comment by yuc014** [comment]
Hi @marindedic,

I tried the wiki add-in you mentioned, and looks like it only works on desktop. And I find many add-ins could do drag-and-drop on Excel desktop only if the text is selectable, see below video:

https://user-images.githubusercontent.com/87364252/198535443-a9d1a997-c80f-4c2c-8fcf-ca605ecfd0b0.mp4

So did you test your add-in on excel online? 

By searching lots of docs I find drag-and-drop is not officially support now. So, if this is your add-in's core feature you should think about how it runs both for desktop and online.

Workaround:
Add a button next to your text, to set the text value to the active cell. Like wiki did.

And I also suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.

**Comment by marindedic** [comment]
> Hi @marindedic,
> 
> I tried the wiki add-in you mentioned, and looks like it only works on desktop. And I find many add-ins could do drag-and-drop on Excel desktop only if the text is selectable, see below video:
> 
>  dragNdrop.mp4 
> So did you test your add-in on excel online?
> 
> By searching lots of docs I find drag-and-drop is not officially support now. So, if this is your add-in's core feature you should think about how it runs both for desktop and online.
> 
> Workaround: Add a button next to your text, to set the text value to the active cell. Like wiki did.
> 
> And I also suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.

Thanks for the reply. I have found the exact question I was looking for on the MTC: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/support-drag-and-drop-to-from-officejs-addins/idi-p/3017629 but it doesn't have a solution.
