### ISSUE TITLE
Pivot table Office.js bugs cause Excel to crash

### ISSUE THREAD

**Issue by SharonCKC** [OfficeDev/office-js#2926]
We have been seeing a lot of crashes with the Office.js pivot table API for Excel.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC, Mac, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
 
## Expected behavior
At the very least, it should not crash Excel. Ideally, it should throw a specific pivot table error message.

## Current behavior
Either Excel desktop app crashes, or the browser tab becomes unresponsive and an error message `An internal error has occurred` can be seen just before that. 

## Steps to reproduce
There are many scenarios that cause this. Some examples below:
1. Have a pivot table with a row field and a Values/data field and grand totals shown. Call `Excel.PivotLayout.getDataBodyRange()` to get all the cell data in the pivot table. Call `Excel.PivotLayout.getPivotItems(Excel.PivotAxis.row, cell)` for each cell of the getDataBodyRange() results.  Excel crashes when it reaches the grand totals of the pivot table.
2. Have an empty pivot table with just a column field but no Values/data field. Call `Excel.PivotLayout.getDataBodyRange()`. Excel crashes.
3. Have a pivot table with a row field and a Values/data field. Call `Excel.PivotLayout.getPivotItems(Excel.PivotAxis.column, cell)` on any cell of the pivot table that was obtained using `Excel.PivotLayout.getDataBodyRange()`. Excel crashes instead of throwing an error warning of missing fields.
4. Have a pivot table with a column field and a Values/data field. Call `Excel.PivotLayout.getPivotItems(Excel.PivotAxis.row, cell)` on any cell of the pivot table that was obtained using `Excel.PivotLayout.getDataBodyRange()`. Excel crashes instead of throwing an error warning of missing fields.

**Comment by yuc014** [comment]
Hi @SharonCKC, thanks for reaching us.
I tried your step but not repro on my machine, see below video as an example (for scenario 2):

https://user-images.githubusercontent.com/87364252/199202382-7c57079b-b383-476f-a64d-326da45da4d3.mp4

If you could reproduce it steadily, could you give me a example.xlsx and a code snip? Then I can investigate it.

Thanks.

**Comment by SharonCKC** [comment]
Please use this workbook [Examples.xlsx](https://github.com/OfficeDev/office-js/files/9921357/Examples.xlsx), and the code below for each worksheet:

Example1:
```
return Excel.run(async (context) => {
      const pivotLayout = context.workbook.pivotTables.getItem("PivotTable1").layout;
      const dataRange = pivotLayout.getDataBodyRange();
      dataRange.load("rowCount, columnCount");
      await context.sync();
      const pivotItemsByRow = [];
      for (let i = 0; i < dataRange.rowCount; i++) {
        for (let j = 0; j < dataRange.columnCount; j++) {
          const cell = dataRange.getCell(i, j);
          const pivotItems = pivotLayout.getPivotItems(Excel.PivotAxis.row, cell);
          pivotItems.load("items");
          pivotItemsByRow.push(pivotItems);
        }
      }
      await context.sync();
      console.log(pivotItemsByRow);
})
```

Example2:
```
return Excel.run(async (context) => {
      const pivotLayout = context.workbook.pivotTables.getItem("PivotTable2").layout;
      const pivotItems = pivotLayout.getPivotItems(Excel.PivotAxis.column, "Example2!I2");
      pivotItems.load("items");
      await context.sync();
      console.log(pivotItems);
})
```

Example3:
```
return Excel.run(async (context) => {
      const pivotLayout = context.workbook.pivotTables.getItem("PivotTable3").layout;
      const pivotItems = pivotLayout.getPivotItems(Excel.PivotAxis.row, "Example3!H4");
      pivotItems.load("items");
      await context.sync();
      console.log(pivotItems);
})
```

Example4:
```
return Excel.run(async (context) => {
      const pivotLayout = context.workbook.pivotTables.getItem("PivotTable4").layout;
      const dataHierarchy = pivotLayout.getDataHierarchy("Example4!I2");
      await context.sync();
      console.log(dataHierarchy);
})
```

**Comment by yuc014** [comment]
@SharonCKC Thanks for your detail reply, I can repro it now.
It has been put on our backlog<Bug#7072918> for internal track. We will keep track of this issue and let you know if there are any updates.
