### ISSUE TITLE
Charts are incorrectly drawn in Excel for the web, but correctly in desktop Excel

### ISSUE THREAD

**Issue by EdwinStraver** [OfficeDev/office-js#2929]
I created a chart with the code:

var chart = ctx.workbook.worksheets.getActiveWorksheet().charts.add("XYScatter", range, "auto");

In desktop Excel, this works perfectly:
![image](https://user-images.githubusercontent.com/27964706/198702379-c522006f-fac6-497a-b29f-8fd0d14a9856.png)

But in Excel for the web, this results in:
![image](https://user-images.githubusercontent.com/27964706/198702482-84585532-f3f2-4b79-9566-efd23f60dd01.png)

This seems to have changed fairly recently.

**Comment by EdwinStraver** [comment]
Note: if I switch "auto", to "columns", it works ok.

**Comment by yuc014** [comment]
Hi @EdwinStraver 
I tried your repro step but it not repro on my excel online, see below video:

https://user-images.githubusercontent.com/87364252/198972312-46cb015c-3a16-4681-b641-c9d15038015a.mp4

And my gist: https://gist.github.com/yuc014/5c17e9a201040a8d93df3c540a39475d

If you still can repro, could you share a code snip? Thanks.
