### ISSUE TITLE
[Word] Incorrect paragraph collection items of selected table cells

### ISSUE THREAD

**Issue by david-on-github** [OfficeDev/office-js#293]
Subset selections of tables in Word don't properly retrieve the paragraphs in the currently selected cells.

Using the Word API, selecting a table or subset of table cells in Word doesn't return the correct objects in range selection. It returns either an incorrect paragraph collection with only the paragraph items within the **last row** of the currently selected cells.

Using the Common API we can workaround by either:

- Using the Document getSelectedDataAsync method to derive the range dimensions of the selected cells by comparing range values to the parent table, to then select the proper paragraphs. However, this is not accurate. 
- Get accurate information about the selected cells by first inserting a content control on the table to "name it", and creating a binding from that control to then register a selection change event on the binding. However, we would not like to create and manage content controls with attached bindings to all tables in user's document to know the user's currently selected cell's paragraph items.

## Expected Behavior
I would expect the current range selection to return the accurate objects within the current selection.

## Current Behavior
Using the Word API selecting only the contents of a table or subset of table cells without any additional preceding or proceeding elements returns the only the contents of the last row in the selection.

## Steps to Reproduce, or Live Example
* Link to live example: https://gist.github.com/david-on-github/a09c92f4894f05d257a7879987bccf8b

## Your Environment

* Platform: PC
* Host: Word
* Office version number: 1809
* Operating System: Windows 10 Pro N
* Browser (if using Office Online): Chrome Version 70.0.3538.77 (Official Build) (64-bit)

## Useful logs
![](https://i.stack.imgur.com/JkhsY.png)

**Comment by JuaneloJuanelo** [comment]
Hello! thanks for reporting this. Can you please include a script lab yaml? (please see https://aka.ms/scriptlab) i am not able to restore your code, it seems you are missing a few libraries.
thanks!!

**Comment by david-on-github** [comment]
Thanks for looking,
https://gist.github.com/david-on-github/a09c92f4894f05d257a7879987bccf8b

**Comment by JuaneloJuanelo** [comment]
update: the issue we have here is that the API currently does not support discontinuous range selection. This is exactly what happens when you partially select data in a table. This is something we will add in the future to the API, no ETA at this point.
