### ISSUE TITLE
How to get add-in version at runtime through OfficeJS API ?

### ISSUE THREAD

**Issue by repl-minatee-p** [OfficeDev/office-js#2930]
I need to fetch the "Version" property value from the add-in's manifest file. I see that add-in displays its version when we click on "Security Info" but I am not able to find a way to get this information through OfficeJS api in my javascript.

Is there a way to get the add-in version or access the security infos programmatically ?

**Comment by RuizhiSunMS** [comment]
Hi @repl-minatee-p , thanks for reporting.
In common, this channel has a standard forum for customer to provide more information. We strongly suggest you fill them then we may can get valuable hints from them.
And as for your issue itself, as far as I know there is no such one in Excel JS APIs( and I think there should be none in Common APIs neither.). If you want a new feature, here we suggest you submit feature request on https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform. Feature requests on it are considered when we go through our planning process.

**Comment by repl-minatee-p** [comment]
Thanks @RuizhiSunMS for your response. I will post it in other forums to know if there is any indirect way to achieve it.
