### ISSUE TITLE
Streaming function returns #VALUE when argument is entity data type

### ISSUE THREAD

**Issue by demyte** [OfficeDev/office-js#2931]
# Provide required information needed to triage your issue

Using two of the samples in Script Lab as the bases for this reproduction the steps below show that when an entity value is passed to a streaming function the function always returns #VALUE!

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: WEB
* Host [Excel, Word, PowerPoint, etc.]: EXCEL
* Office version number: N/A
* Operating System: Windows
* Browser (if using Office on the web): Edge/Chrome latest
 
## Expected behavior

The function fires and the entity is passed in correctly.

## Current behavior

The cell returns #VALUE!
![image](https://user-images.githubusercontent.com/48166/198918547-c31f333d-5487-478e-be81-fe505856dcce.png)
![image](https://user-images.githubusercontent.com/48166/198918637-4da5d721-0202-41f8-913d-a4dc576eb08c.png)

Notes:
- The metadata looks correct as it is saying the type is "any" and the "allowCustomDataForDataTypeAny" is true
- You will see that nothing is written to the console as the function never fires.  

## Steps to reproduce

Firstly use the sample "Data types: Create entity cards from data in a table" to create a worksheet with a table of data and a column of entity types. 
  - ![image](https://user-images.githubusercontent.com/48166/198918363-4bc3ae91-7579-423d-bbe4-477b0866b122.png)

Then load [this gist](https://gist.github.com/demyte/2771f88abd175daf454c533fce4320f8) which is a minor amendment of the script lab sample "Streaming function"

Create a column at the end of the data and add this formula in with an argument for the amount being the entity cell from the table

Note:  I have also replicated it using the formula in [this sample]( https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-batching) 

## Link to live example(s)

As per steps to reproduce

# Provide additional details

N/A

## Context

This is stated as working as per the documentation here: [link](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-data-types-concepts#input-an-entity-value)
![image](https://user-images.githubusercontent.com/48166/198919186-42092d87-c052-4b1d-9b31-43fc0fcbe911.png)

## Useful logs

N/A

**Comment by demyte** [comment]
Hi @RuizhiSunMS - any movement on this issue?  Do you need anything more from me?

**Comment by RuizhiSunMS** [comment]
Hi @demyte ,
Our colleague tried but found no problem. Then it looks we need more information.
I wonder have you ever tried the sample code about stream function on the ScriptLab? First of all, we want to make sure the basic functionality works.
And #2932 is also reported by you and these two issues are similar.

**Comment by demyte** [comment]
@RuizhiSunMS I would be interested to understand the test that was performed by your colleague to come to that conclusion.

The example I posted is a copy of the script lab example with a minor change to show the issue.

I did it this way to keep it as close to vanilla as possible and still show the issue.

**Comment by demyte** [comment]
@RuizhiSunMS here is a video of it failing

https://user-images.githubusercontent.com/48166/201550277-1270104d-7fb0-4fb5-bdfc-f06aef526256.mp4

**Comment by demyte** [comment]
@RuizhiSunMS as per the discussion and workaround provided by @jiju-MS, in #2932, it looks like if I take the same approach to start treating things as Ranges (i.e. using `[][]` as their type), then I can get this issue resolved with the following change (as updated in [the gist](https://gist.github.com/demyte/2771f88abd175daf454c533fce4320f8))

![image](https://user-images.githubusercontent.com/48166/202040757-a1535593-f88d-4bd8-b7e3-99dc5e4102a7.png)

**Comment by RuizhiSunMS** [comment]
Close this issue together with #2932. 
Feel free to re-open the issue if the error appears.
