### ISSUE TITLE
Streaming function - after initial invocation - when F2 and Enter is used on it - it returns #VALUE!

### ISSUE THREAD

**Issue by demyte** [OfficeDev/office-js#2932]
# Provide required information needed to triage your issue

As details and per steps detailed below.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: WEB
* Host [Excel, Word, PowerPoint, etc.]: EXCEL
* Office version number: N/A
* Operating System: WINDOWS
* Browser (if using Office on the web): Edge/Chrome Latest
 
## Expected behavior

The entity is returned, just like it was on the intial calculation

## Current behavior

#VALUE! is returned

## Steps to reproduce

Using [this gist](https://gist.github.com/demyte/4c6282df8172b7b68a06e677d8a3cf6b)

- Register the functions using script lab
- In one cell put this: `=SCRIPTLAB.CUSTOMFUNCTIONSANDENTITYTYPES.ENTITYASSTREAM(1,3)`
- In another cell put this: `=SCRIPTLAB.CUSTOMFUNCTIONSANDENTITYTYPES.ENTITYNOSTREAM(1,3)`
- Once they have calculated they should show an entity with the cell text as "Numbers": ![image](https://user-images.githubusercontent.com/48166/198926903-155a8b1f-5c05-4855-b351-bfcf5b726a5b.png)
- On the cell that is using the formula `ENTITYASSTREAM` press F2 and enter
- This now makes the cell show #VALUE! ![image](https://user-images.githubusercontent.com/48166/198926989-9170b940-30ac-4c0b-b5ef-6ae4d54ec248.png)
- Doing the same on the cell with the formula `ENTITYNOSTREAM` works fine

## Link to live example(s)

As per the gist in steps to reproduce

# Provide additional details

 
N/A

## Context

This should always return the current result of the invocation 

## Useful logs

N/A

**Comment by demyte** [comment]
Hi @RuizhiSunMS - any movement on this issue?  Do you need anything more from me?

**Comment by demyte** [comment]
@RuizhiSunMS as per my comment on #2931

**Comment by demyte** [comment]
@RuizhiSunMS Here is a video demonstrating this failing


https://user-images.githubusercontent.com/48166/201549520-b5985e34-e247-4b4f-b285-a6c61f3d779c.mp4

**Comment by jiju-MS** [comment]
Hey, @demyte, thanks for reporting this issue and providing the details, our engineer is looking into it, could you please try this gist: 
https://gist.github.com/jiju-MS/7575d11e1b1781133bfa9768b39ce10a
on your environment and see whether it works for you?

Thanks!

**Comment by demyte** [comment]
Hi @jiju-MS, 

Yes, it looks like the very liberal use of `[][]` kicks them into gear when they are a streaming function.

(just to note, that breaks the non streaming function in that example because of line 186 - but thats not imporatant).

Is this mentioned somewhere in the doco that streaming functions need to assume the result is a 2D array (i asusme an Excel Range like thing)

I also note for #2931 this liberal use of `[][]` gets that issue resolved by making the argument that is being passed in that could either be an entity or a value be `any[][]`.  (I'll comment over there about this)

Thanks!

**Comment by jiju-MS** [comment]
Glad to know it working for you. we will provide some samples for these scenarios to help.

**Comment by RuizhiSunMS** [comment]
Close this bug since the workaround has been provided. 
Feel free to reopen if the error appears again.
