### ISSUE TITLE
When writing a large amount of data to Excel table, promise resolution of Excel.run occurs before data rendering complete.

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#2934]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2209 Build 1569.20208
* Operating System: Windows 10
* Browser (if using Office on the web): N/A
 
## Expected behavior

I have an Excel.run function that writes a large amount of data to an Excel table, 400k+ rows by 36 columns (The add-in also needs to handle even larger datasets up to 1 million rows by 50+ columns). That is followed by a then function that updates the UI based on the data rendering being complete. I would expect the then function to run after all data is rendered in the table but the function runs 15+ seconds before the data is visible in Excel. This leads to confusion for my users who think the data retrieval failed because the add-in looks as if the data retrieval is complete but there is no data in Excel.

## Current behavior

The Excel.run function executes and the then function fires, this updates the UI but there is no data in the Excel sheet for 15+ seconds. What I would desire is for the then function to not execute until the data is completed rendering in the Excel sheet.

## Steps to reproduce

1. Create a table to hold the data.
2. Set the number format of the columns in the table
3. Expand the table to the size of the data (We do this so that the number format gets set for all the cells in the table but we only had to specify the number format for a single row.)
4. Write the data to the table. (We have experimented with multiple ways to write all the data to the table and writing the data in 1000 row batches looks to be more efficient than writing all rows at once.)
5. Watch the add-in, a message will appear indicating all report data has been written but the data in the Excel table will not render for multiple seconds.

## Link to live example(s)

Here is a link to a github project with a working example, https://github.com/AlgaeBread/Large-Data-Test

# Provide additional details

1. Open and run the project. (It is based on the tutorial to setup your first Excel project using yo office.)
2. Click Create table to create the table to hold the report data.
3. Click Populate Table to write the data to the Excel sheet.
4. In the add-in, text will be added below the buttons that says "Completed writing report data." when the then method is called after the Excel.run function to write the data.
5. Note the text appears then several seconds later the Excel sheet starts to populate with the data.

## Context

This add-in retrieves reporting data from an external system and displays it in an Excel table. While the retrieval is processing, the report displays a retrieving animation to inform the user the report is running. Because of the order of events in this issue, the retrieval animation ends before the data is visible to the user which leads them to believe the retrieval potentially failed. We need a reliable event for when the data is completed rendering so we can update the UI at the proper time. If this could be solved by writing the data to the table in a more efficient way, we would also be open to that solution.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuizhiSunMS** [comment]
Hi @AlgaeBread , thanks for reporting.
One suggestion is to use await in excel.run(... reportTable.resize. Since you do use await in another place, I'm curious why you didn't do it

**Comment by ghost** [comment]
Excel.Table.resize() does not return a promise, so it cannot be await-ed. Is the resize of the table the expensive operation causing the delay in rendering?

**Comment by RuizhiSunMS** [comment]
My bad. I should make it clearer since my last reply is ambiguous. 
Not use await before resize function, it's to use like await excel.run(.....
Paste changed code here towards line 117 to line 140 in app.tsx
```
    writeReportData = async (totalColumnsEndString: string) => {  
    let rowCount = this.data.length;  
    await Excel.run({ delayForCellEdit: true }, async (context: Excel.RequestContext): Promise<any> => {  
      const tableBodyLastRowIndex: number = 1 + rowCount;  
      let reportTable: Excel.Table = context.workbook.worksheets.getActiveWorksheet().tables.getItemAt(0);  
      reportTable.resize(reportTable.worksheet.getRange(`A1:${totalColumnsEndString}${tableBodyLastRowIndex}`)); 

 

      const bite: number = 1000;
      for (let i = 0; i < rowCount; i += bite) {
        const rowData: string[][] = this.data.splice(0, bite);
        const tableRow: Excel.Range = reportTable.worksheet.getRange(
          `A${i + 2}:${totalColumnsEndString}${i + rowData.length + 1}`
        );
        tableRow.values = rowData;
        tableRow.untrack();

 

        await context.sync();
      }

 

      // Format table
      reportTable.getHeaderRowRange().format.autofitColumns();
      await context.sync();
      this.setState({ writeDataCompleteMessage: "Completed writing report data." });
    });
  };
```
Hope it could help.

**Comment by ghost** [comment]
Good call. Looks like I just missed awaiting the correct promise, I did some refactoring and now my UI is updating as expected. 
I have an additional question regarding the performance of the table load. Is that the most efficient? Are there ways I could refactor it to make it faster? Do I need to log an additional issue to ask those questions?

**Comment by RuizhiSunMS** [comment]
Maybe loading by batch could be a choice.
And usually, we suggest you submit questions as your additional ones in stackoverflow with related tags.
