### ISSUE TITLE
[Outlook] Body.setAsync will break signature IMG on exchange on-premise

### ISSUE THREAD

**Issue by Howard-Song** [OfficeDev/office-js#2936]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **Exchange on-premise for web**
* Host [Excel, Word, PowerPoint, etc.]: **Outlook**
* Office version number: **16.0.8004.1000**
* Operating System: **Mac OS**
* Browser (if using Office on the web): **Chrome**
 
## Expected behavior

Body.setAsync will not lost the src of signature img elements.

## Current behavior

After insert a IMG signature in email body, src of IMG element in signature will lost while using this code to reset body.
```javascript
Office.context.mailbox.item.body.getAsync('html',(result)=>{
    Office.context.mailbox.item.body.setAsync(result.value,{ coercionType: Office.CoercionType.Html },console.log)
})
```

## Steps to reproduce

1. Create new message in Exchange on-premise for web(16.0.8004.1000)
2. Insert signature with IMG in email body
3. Get email body and set the same body use body.setAsync

## Context

I test in https://outlook.office.com it's work well, only can reproduce in  Exchange on-premise for web(16.0.8004.1000)
## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)
There are no error return by Office-JS api. just some screenshots with the IMG src for reference:
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/28775661/199200030-cc0e6c71-fe95-4a44-a2bd-b0ffad0be25b.png">
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/28775661/199200270-931c251a-8b7b-4a75-95fc-a5563811972f.png">

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ElizabethSamuel-MSFT** [comment]
@JesseHeisenberg Thanks for letting us know about this.

@exextoc Can you take a look?

Thanks.

**Comment by exextoc** [comment]
Hey @JesseHeisenberg ,

It took us some time to dig into this issue, but we need some further help from you. Can you please confirm your Exchange Server version so that we can accurately reproduce this issue? You can check your Exchange Server version from the documentation [here](https://learn.microsoft.com/en-us/exchange/new-features/build-numbers-and-release-dates?view=exchserver-2019).

**Comment by Howard-Song** [comment]
Hi @exextoc ,
Sorry for give the wrong version before, I have just notice the version in  `Office.context` is not the real version of outlook, and it should be in `Office.context.mailbox`,
![image](https://user-images.githubusercontent.com/28775661/200983677-38bd2090-09e3-450b-98fe-7d820dcf5bd6.png)
![image](https://user-images.githubusercontent.com/28775661/200984194-cc6e9f37-5236-46f2-9e75-54a0cf2d7fde.png)

It seems this version is in the list that you provide, looks like I'm using **Outlook Exchange on-premise 2019(15.2.986.5)**  Final thing is I use chrome to visit this environment. Please let me know if you want to get more information, thank you. 
![image](https://user-images.githubusercontent.com/28775661/200983792-0b48d547-e5b0-4c6f-ba1a-72a4d2e96979.png)

**Comment by exextoc** [comment]
We are able to repro the issue on mentioned exchange server 2019 CU12 on OWA. Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point
Internal tracking id: 3167946

**Comment by cluB-Watermelon** [comment]
Is there any update on this issue? We are facing the same problem
