### ISSUE TITLE
OWA - Edit this and all following throws unhandled error

### ISSUE THREAD

**Issue by thoffmann-fms** [OfficeDev/office-js#2938]
# Provide required information needed to triage your issue

- Create a daily recurring event M-F, invite an Exchange Resource, Send. 
-  Wait for the resource to accept the event.  
- Right-click on Tuesday and Edit This and all following events.  Change the end time, click Send.  
-  Error message displayed, clicking details throws another unhandled exception. 
-  See screenshot below.

```
Uncaught (in promise) Error: Couldn't save event
```
and clicking the Details link in error popup:
```
owa.24102.js:2 
        
       Uncaught (in promise) Error: [fetchFullCalendarEvent] Action source:FullComposeInEditMode_SendEventErrorNotification with response code: ErrorItemNotFound and error: [getCalendarEventService] request failed. Message: The occurrence couldn't be found., Item not found., ResponseCode: ErrorItemNotFound, ResponseClass: Error
    at ke (owa.CalendarBoot.js:2:261636)
    at async qe (owa.24102.js:2:46822)
    at async ze (owa.24102.js:2:46084)
[outlook.office.com-1667318786029.log](https://github.com/OfficeDev/office-js/files/9912069/outlook.office.com-1667318786029.log)

    at async Xe (owa.24102.js:2:49094)
```

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ____OWA__
* Host [Excel, Word, PowerPoint, etc.]: _____Outlook_
* Office version number: ______
* Operating System: __Win 10____
* Browser (if using Office on the web): Edge
 
## Expected behavior
Series altered.

## Current behavior

Event Action Failed popup message.

## Steps to reproduce
Create a daily recurring event M-F, invite an Exchange Resource, Send.   Wait for the resource to accept the event.  Right-click on Tuesday and Edit This and all following events.  Change the end time, click Send.   Error message displayed, clicking details throws another unhandled exception.  See screenshot below.

## Link to live example(s)
n/a

# Provide additional details

1. ______
2. ______
3. ______

## Context

Unable to use Edit this and following feature.

## Useful logs

![image](https://user-images.githubusercontent.com/28546239/199279844-11c4185f-9f38-4478-9cab-b5eeb10eb44e.png)
![image](https://user-images.githubusercontent.com/28546239/199281538-bacc3f2b-be50-46d7-a1a2-29418824f646.png)

After initial Send
![image](https://user-images.githubusercontent.com/28546239/199282398-6d6cd5fa-71e8-4919-bc05-758243589065.png)

Edit this and all following, send: Tuesday shows "Draft", W-F are now gone for the organizer. Refresh the Room calendar and T-F are missing.
![image](https://user-images.githubusercontent.com/28546239/199282513-b1b45d60-c7aa-4f44-9830-6e6aef5f3818.png)
![image](https://user-images.githubusercontent.com/28546239/199282745-7d15860e-0570-48a5-86e3-375d1c5ec7eb.png)

Click More Details and nothing happens other than the Console showing the 2nd uncaught exception, ErrorItemNotFound.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ElizabethSamuel-MSFT** [comment]
@thoffmann-fms Thanks for letting us know about this.

@exextoc Can you take a look?

Thanks.

**Comment by Oleg-O** [comment]
Closing this here as it doesn't seem to be related to office.js. I've alerted the right team, but in future please use app feedback to submit app issue reports as described in our [documentation](https://support.microsoft.com/en-us/office/how-do-i-give-feedback-on-microsoft-office-2b102d44-b43f-4dd2-9ff4-23cf144cfb11#platform=Office_for_the_web).

**Comment by thoffmann-fms** [comment]
What is the "right team"?

**Comment by Oleg-O** [comment]
The team that owns the scenario you described, the OWA Calendar team. Or at least that seemed like a good starting point for this investigation. Thanks for reporting this issue!
