### ISSUE TITLE
Add-in is not auto loading.

### ISSUE THREAD

**Issue by vinay-sattur** [OfficeDev/office-js#2939]
Add-in is not auto loading in production environment. It was working fine till yesterday(31st Oct 2022) but from today morning its not working. No changes/deployments are done from our end.

## Expected Behavior
Add-in is expected to auto load.

## Current Behavior
Add-in is not auto loading.

## Steps to Reproduce, or Live Example
1) Login to following account
https://newconnect.mheducation.com
username: Msft@student.com
password: Msft12345
2) Once login, select "Excel" assignment.
3) Click on continue.
4) In the first question of the assignment, click button "Open Excel in new tab".

## Context
The add-in not auto loading issue is causing confusion for our customers(students and instructors). We are starting to get report from our customers that our application is not working.

## Your Environment

* Platform: Office Online
* Host : Excel

**Comment by RuizhiSunMS** [comment]
Hi @vinay-sattur Thanks for reporting this issue. We also have got similar issue from another source and still focus on it. Will update if we make progress.

**Comment by RuizhiSunMS** [comment]
@vinay-sattur 
Our colleagues said the issue should be ok now, please take a check.

**Comment by vinay-sattur** [comment]
> @vinay-sattur Our colleagues said the issue should be ok now, please take a check.

Thank you @RuizhiSunMS . I verified it and its working, add-in is auto loading now.
