### ISSUE TITLE
Excel - Deleting rows doesn't trigger onChanged event of table

### ISSUE THREAD

**Issue by kreja** [OfficeDev/office-js#294]
## Expected Behavior
Trigger the onChanged event when delete rows in table

## Current Behavior
I deleted some rows in the table which has been registered a onChanged handler, but nothing happened, the onChanged handler is not triggered.

## Steps to Reproduce, or Live Example
Changing the value of some cells does triggered the handler, while deleting rows not.
![excel](https://user-images.githubusercontent.com/7478555/48187039-dc81b680-e374-11e8-9f79-96ba72068f15.gif)

snippet: [Script Lab](https://gist.github.com/a7c2b0fd648c7613e2aa47e7e5b05d75), you can run this snippet to easily reproduce

## Context
I'm writing an data analysis add-in, so I need to know the change of the table, so that I can do the analysis in real-time.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ___Mac___
* Host [Excel, Word, PowerPoint, etc.]: ___Excel___
* Office version number: ___16.16.3(181015)___
* Operating System: __macOs 10.13.1____

**Comment by jipyua** [comment]
Hey, this is a known issue and we have gave a fix to it. Currently we haven't enable this fix yet, will enable it soon. Thanks for reporting!

**Comment by kbrandl** [comment]
@jipyua or @JuaneloJuanelo are you able to provide any update on this issue?

**Comment by JuaneloJuanelo** [comment]
@tutieu  and or @jipyua  is this fix deployed? do we have a bug?

**Comment by grangeryy** [comment]
This issue has been fixed. So close the issue.

**Comment by alaaet** [comment]
What was the fix? 
the same issue seems to still exist.
