### ISSUE TITLE
Showstopping bug in Excel Online that breaks all add-ins

### ISSUE THREAD

**Issue by taralex77** [OfficeDev/office-js#2940]
Starting October 31st, 2022 (Halloween Special): 
Any Excel spreadsheet open in Excel Online gets stripped of settings saved in it before. This renders useless all plug-ins that use _Office.context.document.settings.set(key, value)_.

## Expected Behavior
Settings saved by Excel add-ins in the property bag of an Excel spreadsheet should be retained on reopening the spreadsheet in Excel Online.

## Current Behavior
Any settings saved by an Excel add-in when open in Excel Online get deleted the next time the document is opened.
This functionality works correctly in Excel for Mac and Excel for Windows (all desktop versions of Excel).

## Steps to Reproduce, or Live Example

1. Side-load the following add-in to Excel Online: https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/office-add-in-save-custom-settings
2. Use 'create setting' button to create a setting in the Property Bag. 
3. Read it back using the 'Get setting' button to make sure it was stored: <p><img width="359" alt="Screenshot 2022-11-02 at 01 09 36" src="https://user-images.githubusercontent.com/7379093/199366121-4c974d6c-6daa-4f24-902c-d8da16e8dc11.png"></p>
4. Reload the browser page
5. Use 'Get setting' button to retieve the saved property by name:
6. It returns null: <p><img width="369" alt="Screenshot 2022-11-02 at 01 10 08" src="https://user-images.githubusercontent.com/7379093/199366195-35d034a2-1751-4199-b4e4-25ab3313c1a3.png"></p>

* Additional details:
For all spreadsheets containing add-in settings, if you open a spreadsheet in Excel Online, it automatically removes the 'webextensions' folder from the file deleting all the settings saved there.
Before opening the spreadsheet in Excel Online:
![folders_before](https://user-images.githubusercontent.com/7379093/199367914-4bc6d501-e36b-41f5-8130-83f974cbdd48.png)
After opening the spreadsheet in Excel Online:
![folders_after](https://user-images.githubusercontent.com/7379093/199367940-79d64a5b-5022-4896-9f6f-7d3075633e4d.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: current
* Operating System: MacOS
* Browser (if using Office Online): Chrome

**Comment by Biktop** [comment]
I've tried several plugins from the market and it seems that they also loose their settings after refreshing page in the browser as it was described in the issue.

**Comment by XiLiuRoy** [comment]
HI @Biktop , we also experience similar issues that after a refresh/hard-refresh, the context.workbook.bindings are gone, by reading through your case, it seems lots of persisted data to workbook have gone after Oct 31st.
The issue we had is here https://github.com/OfficeDev/office-js/issues/2935

**Comment by pvsleeper** [comment]
Best bit is, if its the same issue as https://github.com/OfficeDev/office-js/issues/2935 - which also started as part of the Halloween Special, then the data is GONE. 
I wrote some bindings to a sheet and then had a look at the backing xml and found the bindings in there. Then I refreshed Excel, loaded my add-in and my add-in couldn't find the bindings anymore. Downloaded the Excel file again, and had a look at the backing xml and the bindings that were there before has been **DELETED**.

**Comment by taralex77** [comment]
Looks like this issue has been fixed. Can anyone confirm?

**Comment by pvsleeper** [comment]
Yes, appears to be retaining it from yesterday. Anyone knows if there is a way to retrieve the deleted data?

**Comment by taralex77** [comment]
The only way to do it is to restore a previous version of the document from Version History.

**Comment by pvsleeper** [comment]
Oh geez… gonna be fun explaining that one to customers.

Does anyone know if this was a bug due to an update to the api or Excel that caused this issue? And is there somewhere where we can see if/when new versions of either had been released? (To assist with troubleshooting in the future - spend almost an entire day going through merged PR’s in our codebase trying to see what bug we’ve added that could be deleting all our stuff)

**Comment by taralex77** [comment]
Not clear. Looks like they quietly fixed it and will now make it look like it never happened.

**Comment by RuizhiSunMS** [comment]
Hi All,
Since we can't track it for some reasons, this issue will be closed. 
Please feel free to reopen it if occurs again.
Thanks
