### ISSUE TITLE
Change the Series's Color and Name of Chart brought some unexpected problems.

### ISSUE THREAD

**Issue by laysrain** [OfficeDev/office-js#2941]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___PC___
* Host [Excel, Word, PowerPoint, etc.]: ___Excel___
* Office version number: ___1.1___
* Operating System: ___Win10___
* Browser (if using Office on the web): ______
 
## Expected behavior

I want to change the series's color and name of use the excel api.
## Current behavior

1.When I change the series's color and name, then save the workbook, it lose the names of series when reopen it.
2.The points can not be changed the color of LineMarkers chartType, it seems look like api does not work. 

## Steps to reproduce

1. ___Use the create chart api to create a chart___
2. ___Get the series of chart, api like chart.series.getItemAt(0) to change the prop name and color___
3. __It was normal at first,  save it, But when I open it again, it's name gone__

## Link to live example(s)

1. ___var series0 = nchart.series.getItemAt(0); series0.name = 'New Name'___
2. ___var nPoint = series.points.getItemAt(i); nPoint.format.fill.setSolidColor(color); It dose not work___
3. ______

# Provide additional details

1. ___var series0 = nchart.series.getItemAt(0); series0.name = 'New Name'___
2. ___var nPoint = series.points.getItemAt(0); nPoint.format.fill.setSolidColor('#4472C4');___
3. ______

## Context

I want to make more beautiful diagrams to show the client some advertising data.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by donlvMSFT** [comment]
Hi @laysrain ,

About the Fill.Color for the points, the Line with Markers chart type does not support the fill color. You may get the InvalidOperation error when trying to do this.

And for the 2 questions about save seriesName and point.color not work, I tried on my local machine but unfortunately couldn't repro. Could you share more information? Like:
1. The Office desktop version, you could find in File->Account.
2. The chart type and any other script?
3. Do you save to local place or online place like OneDrive?

That would help a lot to identify the issue, thanks.

**Comment by laysrain** [comment]
Hello @donlvMSFT,
May I ask what version the office.js is?
What is the current stable version?

**Comment by donlvMSFT** [comment]
Hi @laysrain ,
The office.js have 2 versions, [prod version](https://appsforoffice.microsoft.com/lib/1/hosted/office.js) and [debug version](https://appsforoffice.microsoft.com/lib/beta/hosted/office.js), you could refer to https://learn.microsoft.com/en-us/office/dev/add-ins/develop/understanding-the-javascript-api-for-office for more information.
