### ISSUE TITLE
OfficeRuntime.auth.getAccessToken() gets stuck in event-based activation Outlook Addin (Outlook Windows)

### ISSUE THREAD

**Issue by avisheknand** [OfficeDev/office-js#2942]
# Provide required information needed to triage your issue

When running event based addin (smart alert on OnMessageSend) SSO OfficeRuntime.auth.getAccessToken() gets stuck. I have encounted this on Outlook for Windows... it works fine on Outlook on web

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office 365 2110 Build 16.0.15726.20068
* Operating System: Windows 11
* Browser (if using Office on the web): ______
 
## Expected behavior

I have used the article (https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/use-sso-in-event-based-activation) to implement SSO. SSO works fine on the Outlook for Web however does not work fine on Outlook for windows. The getaccesstoken line never returns any sso token.. it gets stuck there.. also no error is returned.

## Steps to reproduce

1. Build an add-in using https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest

2.) On the onMessageSendHandler handler in launchevent.js modify/replace the code:

`
async function onMessageSendHandler(event) {

    let ssoToken = await OfficeRuntime.auth.getAccessToken();

   let message =  "This application subscription is not activate \n\nYou can activate the free 14 day trial (credit card NOT 
   required) to get started.\n\nClick Don’t Send and click the Settings button on the Ribbon.";
    event. Completed({ allowEvent: false, errorMessage: message});

}
`

## Context
i need to get hold of the accesstoken so i can make a call to my web API's to validate the user info

**Comment by ElizabethSamuel-MSFT** [comment]
@avisheknand Thanks for raising this issue.

@exextoc Can you take a look?

Thanks.

**Comment by exextoc** [comment]
@avisheknand, can you setup runtime logging and look at the log file to see what error is being returned? Here's a link to setup runtime logging: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging#runtime-logging-on-windows

**Comment by avisheknand** [comment]
@exextoc , thank you. i have set up the runtime logging... the issue was not with SSO. The issue seem to be that if we use "await " in launch event function.. the event. complete() method does not work at all on Outlook desktop. The pop up message shows that Addin is taking longer then expected and nothing happens until time out.

Below is a sample code that can be used to create the issue:

`Office.actions.associate("onMessageSendHandler", onMessageSendHandler);

async function onMessageSendHandler(event) {
    console.log(await test());
    event.completed({ allowEvent: false, errorMessage: "Hello world" });

}


async function test() {
    return "Test";
}
`

Here is an video which shows the issue: https://standss-my.sharepoint.com/:v:/p/nanda/EU0SKDfjiFhElPR8fX0480IBQgUndLUNK88bNc_iNkxDVw?e=L8skag

**Comment by avisheknand** [comment]
@exextoc , any help on the above would be appreciated

**Comment by exextoc** [comment]
This is a limitation of the JavaScript engine that is used to execute your add-in's code. Currently, it supports up to ECMAScript 2016. The await keyword was introduced by ECMAScript 2017, so it is not supported. Can you avoid using it and also ensure that you are only using syntax supported up to ECMAScript 2016? We are working to update our documentations to reflect this.

**Comment by avisheknand** [comment]
@exextoc ,  i am facing another issue which seem to be related to SSO.

I have now hosted the event based add-in (OnMessageSend) on our azure app service.

When using the add-in from Outlook desktop client to send out email i can see the runtime logging states "SSO failed with "5001" error code.	

There is no error shown on OWA and it works fine there. We also have taskpane which checks for SSO and it works fine. The only problem i see is when SSO is performed from Outlook Desktop on OnMessageSend event.	
"
[log.txt](https://github.com/OfficeDev/office-js/files/10129148/log.txt)

`function getUserInfo(apiUrl, options) {

    return new Office.Promise(function (resolve, reject) {

        try {

            // throw new MockSSOError("13003");
            // if (options === undefined) options = { allowSignInPrompt: true, allowConsentPrompt: true};
            console.log("going to get ssotoken");

            OfficeRuntime.auth.getAccessToken().then(function (result) {
                console.log("getAccessToken: " + result)
                getUserInfoUsingToken(apiUrl, result)
                    .then(function (value) {
                        return resolve(value);
                    }
                    );

            },
                function (error) {
                    console.log("error: " + error);
                    fallBackActionForSSO();
                }
            );

        }
        catch (exception) {
            console.log("exception: " + exception);
            if (exception.code) {

                switch (exception.code) {

                    case 13001:
                        // No one is signed into Office. If the add-in cannot be effectively used when no one 
                        // is logged into Office, then the first call of getAccessToken should pass the 
                        // `allowSignInPrompt: true` option.
                        console.error("Client side error 13001: No one is signed into Office. Sign in to office.");
                        break;
                    case 13002:
                        // The user aborted the consent prompt. If the add-in cannot be effectively used when consent
                        // has not been granted, then the first call of getAccessToken should pass the `allowConsentPrompt: true` option.
                        console.error("Client side error 13002: You can use many of the add-ins functions even though you have not granted consent. If you want to grant consent, Contact your Office 365 Admin.");
                        break;
                    case 13006:
                        // Only seen in Office on the web.
                        console.error("Client side error 13006: Office on the web is experiencing a problem. Please sign out of Office, close the browser, and then start again.");
                        break;
                    case 13008:
                        // Only seen in Office on the web.
                        console.error("Client side error 13008: Office is still working on the last operation. When it completes, try this operation again.");
                        break;
                    case 13010:
                        // Only seen in Office on the web.
                        console.error("Client side error 13010: Follow the instructions to change your browser's zone configuration.");
                        break;
                    default:
                        // For all other errors, including 13000, 13003, 13005, 13007, 13012, and 50001, fall back
                        // to non-SSO sign-in.
                        fallBackActionForSSO();

                        break;
                }
            }
            else {
                console.error("EXCEPTION " + JSON.stringify(exception));
                return JSON.stringify(exception);
            }
        }

    });
         
}`

![image](https://user-images.githubusercontent.com/80862413/204964121-fa94de3b-fcad-4670-bec9-7f8ec38c2a36.png)

**Comment by avisheknand** [comment]
@exextoc ,  i am facing another issue which seem to be related to SSO.

I have now hosted the event based add-in (OnMessageSendon our azure app service.

When using the add-in from Outlook desktop client i can see the runtime logging states "SSO failed with "5001" error code.		
"
[log.txt](https://github.com/OfficeDev/office-js/files/10129148/log.txt)

`function getUserInfo(apiUrl, options) {

    return new Office.Promise(function (resolve, reject) {

        try {

            // throw new MockSSOError("13003");
            // if (options === undefined) options = { allowSignInPrompt: true, allowConsentPrompt: true};
            console.log("going to get ssotoken");

            OfficeRuntime.auth.getAccessToken().then(function (result) {
                console.log("getAccessToken: " + result)
                getUserInfoUsingToken(apiUrl, result)
                    .then(function (value) {
                        return resolve(value);
                    }
                    );

            },
                function (error) {
                    console.log("error: " + error);
                    fallBackActionForSSO();
                }
            );

        }
        catch (exception) {
            console.log("exception: " + exception);
            if (exception.code) {

                switch (exception.code) {

                    case 13001:
                        // No one is signed into Office. If the add-in cannot be effectively used when no one 
                        // is logged into Office, then the first call of getAccessToken should pass the 
                        // `allowSignInPrompt: true` option.
                        console.error("Client side error 13001: No one is signed into Office. Sign in to office.");
                        break;
                    case 13002:
                        // The user aborted the consent prompt. If the add-in cannot be effectively used when consent
                        // has not been granted, then the first call of getAccessToken should pass the `allowConsentPrompt: true` option.
                        console.error("Client side error 13002: You can use many of the add-ins functions even though you have not granted consent. If you want to grant consent, Contact your Office 365 Admin.");
                        break;
                    case 13006:
                        // Only seen in Office on the web.
                        console.error("Client side error 13006: Office on the web is experiencing a problem. Please sign out of Office, close the browser, and then start again.");
                        break;
                    case 13008:
                        // Only seen in Office on the web.
                        console.error("Client side error 13008: Office is still working on the last operation. When it completes, try this operation again.");
                        break;
                    case 13010:
                        // Only seen in Office on the web.
                        console.error("Client side error 13010: Follow the instructions to change your browser's zone configuration.");
                        break;
                    default:
                        // For all other errors, including 13000, 13003, 13005, 13007, 13012, and 50001, fall back
                        // to non-SSO sign-in.
                        fallBackActionForSSO();

                        break;
                }
            }
            else {
                console.error("EXCEPTION " + JSON.stringify(exception));
                return JSON.stringify(exception);
            }
        }

    });
         
}`

![image](https://user-images.githubusercontent.com/80862413/204964121-fa94de3b-fcad-4670-bec9-7f8ec38c2a36.png)

**Comment by exextoc** [comment]
@avisheknand, can you open another issue for this so that we can track them separately?

**Comment by kinkoazc** [comment]
@avisheknand Did you manage to find a solution to the 5001 issue, on Outlook for Desktop? I'm currently experiencing the same issue(5001 error when calling from the event activation handlers-only if the same method wasn't called from the task pane for example, in which case the event activation call starts working as expected-). If not, I can open a separate ticket for this.
