### ISSUE TITLE
Office.js initialization fails on Outlook Android

### ISSUE THREAD

**Issue by sznorbert07** [OfficeDev/office-js#2943]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mobile
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 1.1
* Operating System: Android 12
* Browser (if using Office on the web): ______
 
## Expected behavior

Office.js gets initialized and the `Office.initialize` method is being called on Android as well.

## Current behavior

Office.js is not initialized and the Add-in is not loaded. The issue occurs very often, but there is a case when it works.
Only Android is affected.

## Context

We are developing an Outlook Add-in which works on every platform but on Android. On Android we can't start the Add-in because the Office.js initialization fails.
We are developing the Add-in using Angular 9.
Based on the documentation, bootstrapping the app is done correctly by inserting the Office.js <script> tag in the head and defining the Office.initialize callback. It doesn't work with the `Office.onReady()` method either.

index.html
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    ...
    <script
      src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js"
      type="text/javascript"
    ></script>
    ...
  </head>

  <body>
    <app-root> </app-root>
  </body>
</html>
```

main.ts
```ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

Office.initialize = function() {
  if (environment.production) {
    enableProdMode();
  }

  platformBrowserDynamic()
    .bootstrapModule(AppModule)
    .catch(err => console.log(err));
};
```

## Useful logs

- [x] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

```
Error: Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.
    at https://appsforoffice.microsoft.com/lib/1/hosted/Office.js:76:29442
    at c (https://appsforoffice.microsoft.com/lib/1/hosted/Office.js:76:4250)
```

**Comment by exextoc** [comment]
Hi @sznorbert07, could you please share the manifest file of the add-in you're developing and code-snippet so that we can repro the issue at our end?

**Comment by sznorbert07** [comment]
Hi @exextoc. Thanks for the reply. Is there a way I can send the manifest to you privately?

**Comment by exextoc** [comment]
Hi @sznorbert07, you can share the files here: OutlookExtensibility@M365x27035562.onmicrosoft.com

**Comment by sznorbert07** [comment]
Hi @exextoc, I sent the manifest file to the email.

**Comment by exextoc** [comment]
Hi @sznorbert07, thanks for sharing the file. We are able to repro the issue. Could you please share the following so that we can investigate further"
- The code snippet where you are initializing the office.js
- You have mentioned that "The issue occurs very often, but there is a case when it works". Could you please share that use case?

**Comment by sznorbert07** [comment]
- I have inserted the relevant codes into the original request: https://github.com/OfficeDev/office-js/issues/2943#issue-1432737974
  If you need other code details, please specify them.
- Its totally random whether it works or not, but I have noticed it works after closing and reopening the add-in for the 3rd or 4th times. When I open the add-in on the first Outlook start, it almost never works.

**Comment by exextoc** [comment]
@sznorbert07: 

We are able to unable to repro the issue with your error statement - "Error: Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page."


Whereas when we tried launching the add-in with the manifest shared, the add-in gets launched and we are able to see few API invocations getting triggered and handled successfully [Apis will get invoked only after the office.js has been initialised successfully]  and then a blank screen.

 

Can you please share a repro video so that we can confirm that we both are on the same page and it will help us to debug better?"

**Comment by sznorbert07** [comment]
Hi @exextoc,
Thank you for your response. It turned out that theres actually two issues. One that you mentioned, which resulted blank page. It was actually a mistake in our code, but I have fixed it.

The other one was the Office.js initialization. Originally I was using ngrok tunnel (tunneling to localhost) to test the add-in on mobile, and it turned out that the ngrok was downloading the build files (main.js, etc...) very slow, hence the `Office.initialize` method definition only occured after it timed out.

What is the timeout limit to initialize the Office.js?
Is there any solution to overcome this case?

**Comment by exextoc** [comment]
Hi @sznorbert07 
Office.initialize is the legacy way of initializing an add-in. OfficeJS will poll several times the user’s script trying to find an Office.initialize definition, if we cannot find a definition after 10s, OfficeJS will timeout failing to initialize the add-in. Office.initialize can only be defined once and will only be called once as soon as the user’s script defines it. 
The recommended way of initializing office js is by Office.onReady.

For more information, please go through the doc at https://learn.microsoft.com/en-us/office/dev/add-ins/develop/initialize-add-in

**Comment by sznorbert07** [comment]
Hi @exextoc 
Sorry for the late response and thanks for your help.

I have managed to solve the issue by setting a function for the `Office.initialize` property in the *src/index.html* and then do the Angular initialization using the `Office.onReady()` method in *src/main.ts*.
With this approach the office-js initialization will probably never time out, since the index.html file is a lot smaller and downloaded faster than the main.js, vendor.js and such files that Angular creates.

*src/index.html*
```html
<html>
  <head>...</head>
  <body>
    <script>
        Office.initialize = function () {
            console.log(new Date() + ': Office initialized - first');
        };
    </script>
  </body>
</html>
```

*src/main.ts*
```ts

Office.onReady(() => {
  console.log(new Date() + ': Office initialized - second');

  platformBrowserDynamic()
    .bootstrapModule(AppModule)
    .catch(err => console.log(err));
}
```

I think it would be great to mention the following in https://learn.microsoft.com/en-us/office/dev/add-ins/develop/initialize-add-in
> OfficeJS will poll several times the user’s script trying to find an Office.initialize definition, if we cannot find a definition after 10s, OfficeJS will timeout failing to initialize the add-in.
