### ISSUE TITLE
Content control inside text box not accessible via API

### ISSUE THREAD

**Issue by Stigjb** [OfficeDev/office-js#2945]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2209 Build 16.0.15629.20200) 64-biters
* Operating System: Windows 10 Pro

## Expected behavior

When using the `contentControls` attribute of a body, paragraph, etc., I expect all content controls in the range to be in the collection.

## Current behavior

If there is a content control in a text box, it is not returned as part of the content control collection.

## Steps to reproduce

In the live example linked below, click "Setup" and then "Run". There is a content control in the document, and you can interact with it in Word, but the `contentControls.getFirst` call throws an error saying the item cannot be found.

## Link to live example(s)

<https://gist.github.com/Stigjb/1bee771196718ced7cad3510ebb1b840>

**Comment by ghost** [comment]
Thank you for letting us know about this issue. We will take a look shortly. Thanks.

**Comment by jipyua** [comment]
hi, thanks for reporting this, this is currently a known design behavior to not return content controls inside textbox. As TextBox is also generally not supported by JavaScript API. If you think this feature is useful to you, please feel free to post an item in the [Microsoft 365 Developer Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)
