### ISSUE TITLE
Parent content control is also deleted if the child content control is deleted

### ISSUE THREAD

**Issue by AlinCatalinPreda** [OfficeDev/office-js#2946]
# Provide required information needed to triage your issue

I created a word document which has two content controls, one is the parent and the other one is the child content control.
The parent content control contains the child content control and nothing else, while the child content control is the one who contains all the paragraphs. (Note that if the parent content control contains a paragraph, which in turn contains the child content control, the issue is not reproducible anymore)

When deleting the child content control with its content, the parent content control is also deleted.
I have attached a gist reproducing this issue: [https://gist.github.com/AlinCatalinPreda/e73ba056afb67f8f99bfb48fce3eb2d9](url)

Here is an example of the document.xml that reproduces the issue (from 2CC.docx): 

```
<w:sdt>
	<w:sdtPr>
		<w:alias w:val="parent"/>
		<w:tag w:val="parent"/>
		<w:id w:val="1566366705"/>
		<w:placeholder>
			<w:docPart w:val="9E92825E88EA488188B3A9FA8D7A63D4"/>
		</w:placeholder>
	</w:sdtPr>
	<w:sdtContent>
		<w:sdt>
			------> child content control which has the paragraphs
		</w:sdt>
	</w:sdtContent>
</w:sdt>
```

Here is an example of the document.xml which does NOT reproduce the issue (from 2CCParentHasParagraph.docx):

````
<w:sdt>
	<w:sdtPr>
		<w:alias w:val="parent"/>
		<w:tag w:val="parent"/>
		<w:id w:val="558290717"/>
		<w:placeholder>
			<w:docPart w:val="DefaultPlaceholder_-1854013440"/>
		</w:placeholder>
	</w:sdtPr>
	<w:sdtContent>
		<w:p w14:paraId="41C53527" w14:textId="433D2223" w:rsidR="00D04580" w:rsidRPr="00683CED" w:rsidRDefault="00683CED" w:rsidP="00683CED">
			<w:sdt>
                              --------------->child content control which contains the run
			</w:sdt>
		</w:p>
	</w:sdtContent>
</w:sdt>
```` 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2202 (Microsoft Word for Microsoft 365 MSO (Version 2202 Build 16.0.14931.20764) 64-bit )
* Operating System: Windows 10 Pro build 19044.2130
* Browser (if using Office on the web): ______
 
## Expected behavior
When deleting the child content control, the parent content control should not be deleted.

## Current behavior
When deleting the child content control, the parent content control is also deleted.

## Steps to reproduce

1. Open the word document attached (2CC.docx) 
with the two content controls.
2. Import the gist: [https://gist.github.com/AlinCatalinPreda/e73ba056afb67f8f99bfb48fce3eb2d9](url) and press Run
3. The parent content control is also deleted.

## Link to live example(s)

1 .Gist : https://gist.github.com/AlinCatalinPreda/e73ba056afb67f8f99bfb48fce3eb2d9

# Provide additional details

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [
[2CC.docx](https://github.com/OfficeDev/office-js/files/9930534/2CC.docx)
[2CCParentHasParagraph.docx](https://github.com/OfficeDev/office-js/files/9930535/2CCParentHasParagraph.docx)
 ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by jipyua** [comment]
hi, thanks for reporting this. This sounds like a bug and we will start investigating on our side to see how to give a fix. BTW, may I know what's the scenario for your case that you need another nested parent content control to just contain another child content control without any other content?

**Comment by AlinCatalinPreda** [comment]
@jipyua We are using content controls to wrap a certain word content in order to build a navigation to that certain word content. For example, we might have this hierarchy:
Section 1 
  ---Section 1.1
     ------Word 1.1.1

What will happen with the content controls is the following:
Word 1.1.1 will have the whole word content inside a content control. Afterwards, we are detecting that Section 1.1 is his parent, so we are going to wrap that content control with another one, corresponding to Section 1.1. Same for Section 1.

This is **highly critical** for how we do things with our Word Addin, since we will have a functionality to Move certain word content to other parts of the document, so trying to delete the content control with its contents from one place will lead to this current issue that I have mentioned.

**Comment by jipyua** [comment]
Thanks for the confirmation! This bug has been fixed internally. When the patch is released through Office monthly update, you will be able to pick it.

**Comment by AlinCatalinPreda** [comment]
1. I have found another instance in which the parent content control has other content besides the child content control which will be deleted, and the parent will also get deleted. Here is the gist link and the document reproducing the issue: https://gist.github.com/AlinCatalinPreda/0676b2ce01d6dc328a72f4584c16f71e 
[ParentGetsDeleted.docx](https://github.com/OfficeDev/office-js/files/10042487/ParentGetsDeleted.docx)


2. Another instance in which the parent content control again has other content besides the child content control, and also the parent content control has the property set to "cannot delete the content control". When I try to delete the child content control, I will receive an exception. 
Marking the parent content control as being able to be deleted will solve this issue AND it will not delete the parent content control as in the case of the first issue mentioned with [ParentGetsDeleted.docx]. The parent content control will still be present after the child gets deleted. 
But the parent not being able to be deleted should not influence the child deletion process.
Here is the document reproducing this issue: 
[ChildCannotBeDeleted.docx](https://github.com/OfficeDev/office-js/files/10042569/ChildCannotBeDeleted.docx)

I don't know if these two scenarios will be fixed by the solution provided for the initial issue raised by this ticket, so I would ask if you could please check if it will also solve them.

**Comment by jipyua** [comment]
hi, thanks for providing further information, both issues will be fixed.

**Comment by AlinCatalinPreda** [comment]
Hello, I have found a similar scenario and I would kindly ask you to also please check if this will be fixed by the initial solution provided.
In this case, the parent content control cannot be deleted (with keeping its content) if there are child content controls that have the "cannot delete" property set to true.
Here are the gist and document reproducing the issue:
https://gist.github.com/AlinCatalinPreda/273ee0758804a6c746ef5ee98c509e37 
[ParentCannotBeDeleted.docx](https://github.com/OfficeDev/office-js/files/10103288/ParentCannotBeDeleted.docx)

**Comment by jipyua** [comment]
I confirmed that the above one is a separate issue and we will log one item in our backlog to track this. thanks.

**Comment by jipyua** [comment]
hi @AlinCatalinPreda all the mentioned issues in this thread are fixed, please feel free to try the fix after the code change is deployed together with Office updates in the Office M365 channel. thanks.

**Comment by AlinCatalinPreda** [comment]
Hello. I tested the fixes in the new version, 1.1.83, but they don't seem to be solved. Are the fixes not released yet?

**Comment by AlinCatalinPreda** [comment]
@jipyua Any updates on this?

**Comment by jipyua** [comment]
@AlinCatalinPreda  if you are on Word windows version and the version number greater than 16.0.16026.20146, you will be able to try the fix.

**Comment by AlinCatalinPreda** [comment]
Tried on that version and the fix worked. Thank you for your help!
