### ISSUE TITLE
OnSmart Alert Message inside Outlook on Web does not render message correctly with new lines 

### ISSUE THREAD

**Issue by avisheknand** [OfficeDev/office-js#2949]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook on web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Win 11
* Browser (if using Office on the web): Microsoft edge, Google Chrome
 
## Expected behavior

We are trying to show message which has sentences with new lines. When message shows on Outlook on Desktop it shows as expected, correctly rendered with new lines. When the same message is shown on Outlook on web, the message shows in a single line and it does not look good, new line seem to be discarded while shown on OWA

Below is the code that we are using

`
function onMessageSendHandler(event) {

  let message =  "This application subscription is not activate \n\nYou can activate the free 14 day trial (credit card NOT required) to get started.\n\nClick Don’t Send and click the Settings button on the Ribbon.";
    event.completed({ allowEvent: false, errorMessage: message});
}
`

## Current behavior

On the Outlook on web, the smart alert message does not render as expected. It shows the message in a single long line as shown below
![image](https://user-images.githubusercontent.com/80862413/200195311-1d27407d-b898-4e32-aec5-e974836c2242.png)

While on Outlook on desktop it shows as expected:
![image](https://user-images.githubusercontent.com/80862413/200195329-ac20f300-b3e8-4d7b-949c-91d1cfb12fe5.png)

## Steps to reproduce

1.) Build an add-in for smart alert using this https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest
2.) On the onMessageSendHandler handler in launchevent.js modify/replace the code:

`function onMessageSendHandler(event) {

  let message =  "This application subscription is not activate \n\nYou can activate the free 14 day trial (credit card NOT required) to get started.\n\nClick Don’t Send and click the Settings button on the Ribbon.";
    event.completed({ allowEvent: false, errorMessage: message});
}`

**Comment by KelBowen** [comment]
@JuaneloJuanelo @ajays-msft  can you please review this?

**Comment by avisheknand** [comment]
@ajays-msft following up on the above issue... any guidance would be appreciated

**Comment by exextoc** [comment]
Hey @avisheknand ,

Thank you for reporting this issue. We have tracked it in our backlog and will pick it up to be fixed. However we have no timelines to share at this point.

Internal Tracking ID: 3180201

**Comment by avisheknand** [comment]
Thanks @exextoc
