### ISSUE TITLE
getComposeTypeAsync throws on appointments

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#2950]
The getComposeTypeAsync method used within an appointment throws with a message 'mailboxItem.getComposeTypeAsync is not a function.'

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web, PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2210 Build 16.0.15726.20070) 64-bit
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
getComposeTypeAsync should return successfully when used in context of appointments.

## Current behavior
getComposeTypeAsync throws an error in appointments.

## Steps to reproduce
1. Create and open an appointment
2. Open Script Lab
3. Run following code
```
 Office.context.mailbox.item.getComposeTypeAsync(result =>{
    console.log(result);
  });
```
4. Observe the error in console.

# Provide additional details

## Context
We are adding different signatures based on if the appointment is plaintext or html. As the API does not
return the CoercionType in an appoitment we don't know which type of signature we should insert.

## Useful logs
![image](https://user-images.githubusercontent.com/6338132/200313629-cd06d32d-4786-4cf7-80b3-5f784b76f57e.png)

**Comment by exextoc** [comment]
Hey @barisbikmaz ,

`getComposeTypeAsync` API is available only in Message Compose mode and is not applicable to Appointment Read mode. You can refer to the documentation [here](https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#outlook-office-messagecompose-getcomposetypeasync-member(1)).

**Comment by Adrian-MSFT** [comment]
Hi @barisbikmaz ,

As an addition, if you would like to check if the item body is in html or plain text, you can use the `Office.context.mailbox.item.body.getTypeAsync` API.
