### ISSUE TITLE
Pproblems creating dev account

### ISSUE THREAD

**Issue by walkermeira** [OfficeDev/office-js#2951]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I can't create an dev account because a bug is happening.

The system don't send me a SMS, but my phone number is right. I tried in many ways, but it persists.

Can somebody help me?

![thumbnail_image](https://user-images.githubusercontent.com/117661895/200342539-3fb366f0-dbca-4fda-9c95-b59ade0cfcfb.png)

**Comment by KelBowen** [comment]
We actively monitor and act against suspicious activities to protect customers and Microsoft platforms from fraud, account compromises, and other malicious activity. Our actions vary from preventing users from joining our program to disabling subscriptions. In this case, the phone number you provided did not pass our verification checks.
