### ISSUE TITLE
Update PivotTable DataSource with the Office Excel JavaScript API

### ISSUE THREAD

**Issue by anton-advasoftware** [OfficeDev/office-js#2953]
It was possible to change an existing pivot table's data source when developing an Excel COM [add-in](https://stackoverflow.com/a/9764063/4664207) and when using [VBA](https://answers.microsoft.com/en-us/msoffice/forum/all/change-pivot-table-data-source-through-vba/073b0e3b-1a9c-4d7d-bdfc-fc892040f7b6), but currently that does not seem to be possible in the JavaScript API. 
 
It would be helpful to add this functionality to the JavaScript API because currently you can only set the PivotTable data source when [creating](https://docs.microsoft.com/en-us/javascript/api/excel/excel.pivottable?view=excel-js-preview#excel-excel-pivottable-getdatasourcestring-member(1)) a new pivot table.  It's common for Excel users to change a pivot table's data source, so it would be helpful to support it programmatically in the JavaScript API.

Link to Ideas Forum: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/update-pivottable-datasource-with-the-office-excel-javascript/idi-p/3565018

**Comment by KelBowen** [comment]
Thank you for this feature request and for posting it to the Ideas forum. (I upvoted your idea there.) We track feature requests on the Ideas area so closing this here. Please check back there and encourage friends to upvote your idea.
