### ISSUE TITLE
Using DialogAPI displayDialogAsync( ... ); causes document to lose focus

### ISSUE THREAD

**Issue by DxDen1004** [OfficeDev/office-js#2954]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

**General Information**
While developing an Outlook Web Add-In, if using `await Office.context.ui.displayDialogAsync(args)`, the document loses focus preventing the usage of all `navigator.clipboard` methods and properties. 

Attempting to perform any operation that requires the usage of `navigator.clipboard` results in `DOMException: Document is not focused.`, other methods and properties of the `navigator` interface may not work as well, though they were not thorougly tested.

**Environment**
PC: Dell Latitude 5580
Host: Outlook Web
Outlook Mailbox Requirement Set: 1.10
OS: Windows 10 Enterprise 19044.2130
Browser: Any browser 
 
**Expected behavior**
When opening a **modal** popup using DialogAPI with
`Office.context.ui.displayDialogAsync(url, {displayInIframe: true})`
by setting the `displayInIframe` option to true, the appearing modal dialog should not prevent focusing `document` therefore allowing the proper usage of the `navigator` interface. 

**Current behavior**
When opening a **modal** popup using DialogAPI with
`Office.context.ui.displayDialogAsync(url, {displayInIframe: true})`
by setting the `displayInIframe` option to true, the `document` loses focus preventing any usage of the `navigator.clipboard` interface.
Attempting to perform any operation by calling said interface will result in a `DOMException: Document is not focused.` exception.

**Steps to reproduce**
Open a modal popup by using `Office.context.ui.displayDialogAsync(url, {displayInIframe: true})`, where `url` points to a page where one of the `navigator.clipboard` methods is called, i.e. `navigator.clipboard.writeText(str)`. You will see a `DOMException: document is not focused` exception that prevents the further execution of the code.

**Context**
The final objective here is to open a modal dialog on the user click. The html page opened by the dialog shall write some information onto the user's clipboard using the `navigator.clipboard` interface and display information about the copied data.

**Comment by exextoc** [comment]
Hey @DxDen1004 ,

We are looking into this issue and will keep you posted.

**Comment by DxDen1004** [comment]
Hello @exextoc ,

Thank you for investigating the issue. While developing and testing I realized that the issue also occurs when the `displayInIframe` property is set to `false` or not specified. 

Also, using the deprecated expression `document.execCommand('copy');` does not work either.

Could I ask you if there is any workaround that you may suggest we can try in the meantime to achieve the final result?

Thank you again.

**Comment by exextoc** [comment]
Hey @DxDen1004 ,

Thanks for reproducing this issue. We have added it to our backlog. However, we have no timelines to share at this point.

Internal Tracking ID: 179694

**Comment by DxDen1004** [comment]
Hello @exextoc and @samantharamon,

I apologize for bothering you again, but two months have passed, could you please provide some updates about this issue?

Thank you again, have a nice day.

**Comment by DxDen1004** [comment]
Hello,

just checking here once in a while to see if anything moves. Still nothing I see.

Any news?

Thanks.
