### ISSUE TITLE
[Outlook] New OWA UI - How to open add-in during compose?

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#2955]
It appears there was a new update to the OWA UI that is being rolled out to some accounts. With this new UI, I am unsure of how to open add-ins during composing of a new message. Our QA team has spent some time trying to find the button to open the add-in that previously existed, but they are not seeing it (see screenshot below). They did ensure that the add-in is installed and we know that is has previously worked just fine in Compose view (so we do not believe to be manifest related -- considering we don't see the option to open ANY add-ins).

## Your Environment
OWA (Chrome)
 
## Expected behavior
The user should have an easy way to open an add-in

## Current behavior
There does not appear to be any way to open an add-in when composing an email

![image](https://user-images.githubusercontent.com/7740624/200584883-ec1d2a05-9e96-4a1c-9625-33fb88aa7f15.png)

## Steps to reproduce
On an account that has the new OWA UI (seems to be being rolled out to a subset of users), create a new message and then attempt to open an add-in that is installed.

**Comment by cody-lettau** [comment]
@exextoc we're hoping we are just not seeing something obvious here. I realize it's likely not a bug with Office.js, but any help in pointing us in the right direction would be great. Or talking to the OWA UI team and asking them to roll this back until it's fixed.

**Comment by liamtim** [comment]
@exextoc Same issue here. No access to add-ins from new compose as of today.

**Comment by cody-lettau** [comment]
This is a pretty big issue for our users who have seen their UI updated to this latest rollout. Can we please get an update?

**Comment by Oleg-O** [comment]
Thanks for reporting!

I see the screenshot above is on "Home" ribbon tab. When I start new mail, I expect the ribbon to switch to "Message" ribbon tab, and this is normally where I expect to find the add-ins. Two questions:

1. did you switch manually to "Home" ribbon tab, or did you land on "Home" ribbon tab without any action in the ribbon?
2. if you switch to "Message" ribbon tab, do you see the add-ins?

Let us know!

**Comment by liamtim** [comment]
Add-ins are not available within any tab (including the "Message" tab) when in new compose mode on the latest OWA release.

**Comment by Oleg-O** [comment]
We've made some changes in the service that we hope should mitigate this issue. Can you please let us know if this is resolved now? You may need to refresh OWA a couple of times (F5).

**Comment by cody-lettau** [comment]
@Oleg-O is there a way to disable these auto updates to the UI for certain accounts? We run end-to-end tests using Playwright and these constant changes cause major headaches...and especially when only certain accounts get the updates and others do not. Or do you have any recommendations as to how we can implement our e2e tests in a more reliable way to deal with these rollouts that only affect certain accounts and not others (we use multiple accounts for our tests, so some get the changes and others do not).

**Comment by ruiconti** [comment]
@cody-lettau sorry to sidetrack your latest message but I am investigating this issue and want to understand it better.

If you navigate to "Settings" > "Mail" > "Customize Actions", do you have any add-ins that are selected here (within the black-stroke square below) that do not show up on the ribbon (the new UI surface)? 

![image](https://user-images.githubusercontent.com/1834568/201128172-9f0d7471-6163-4301-9cff-4f1c4ef77132.png)

**Comment by cody-lettau** [comment]
I know we did when we reported this issue. We had our add-in checked and it was not showing up anywhere during the compose. It did show up when reading messages.

I have the team confirming with the specific accounts if they are able to open the add-in during compose now that updates have been pushed out by the Outlook team.

**Comment by cody-lettau** [comment]
It does appear for me when I check our add-in. But I'm not sure my account is on this new update that was rolled out or not.

**Comment by liamtim** [comment]
Is there a means to view which version of OWA a user is running? It's making things extremely difficult for us as it appears new UI is rolled out via canary deployments, and I can't find a way to 

a) Check version numbers of OWA clients
b) Opt out of automatic updates
c) Roll back to prior versions

**Comment by ruiconti** [comment]
@cody-lettau do you see a bottom toolbar in compose? 

![image](https://user-images.githubusercontent.com/1834568/201134273-48b84c62-4751-4846-8d88-7de7b2ff6f14.png)

**Comment by ruiconti** [comment]
@cody-lettau Can you also confirm if you the add-in that you have checked on settings and weren't able to see on the new UI surface had both `ReadCommand` and `ComposeCommand` capabilities?

**Comment by cody-lettau** [comment]
@ruiconti I do see the toolbar at the bottom on my personal account -- I never saw the Send button move above the compose pane:
![image](https://user-images.githubusercontent.com/7740624/201136031-3ad98ee2-eda0-46d1-a59a-6fe8646ddbd6.png)

I am positive that we have both ```MessageReadCommandSurface``` and ```MessageComposeCommandSurface``` capabilities defined in the manifest.

My QA team who reported this on one of their e2e test accounts sent this to me this morning for that same account that I shared the original screenshot from when opening this bug:
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/7740624/201136404-a9ef0283-c65d-423c-821b-f8c41d1e828e.png">

So it appears their UI was updated and the toolbar is now below the compose pane again and they are able to see our add-in now (note this account does not have the add-in added as a custom action in this screenshot, so we go to the 3 dots and it is listed in the menu that opens).

**Comment by ruiconti** [comment]
@cody-lettau, I want to personally thank you for initially reporting the issue so we could find it and mitigate it early. And also for clarifying and providing more relevant info timely. That helped me identify the issue and we should have a forward fix soon enough.

I am also sorry that you are going through the bumps of this rollout, that is definitely not the experience we want to provide for Outlook users.

**Comment by cody-lettau** [comment]
@ruiconti glad to help out where we can!

**Comment by liamtim** [comment]
Is this fix live on production for all users?

**Comment by ruiconti** [comment]
Yes @liamtim, it rolled out to all live production builds.
