### ISSUE TITLE
SSO with https://localhost:8080 - makeGraphApiCall

### ISSUE THREAD

**Issue by OfficeAddins** [OfficeDev/office-js#2957]
# Provide required information needed to triage your issue

## Your Environment
* Platform: Windows 11
* Host: Word
* Office version number: Version 2210 Build 16.0.15726.20070 - 64-bit 
* Browser: Edge Version 107.0.1418.35 (Official build) (64-bit)
 
## Expected behaviour
This should return a valid response
`let response = await makeGraphApiCall(bootstrapToken);`

## Current behaviour
The following GET request is failing
GET https://localhost:8080/getuserdata?_=1667946086004

## Steps to reproduce
A detailed step-by-step of how to reproduce plus source code can be found here:
https://github.com/OfficeAddins/word-javascript-sso

## Context
I am able to use the Yeoman Generator to create a working https://localhost SSO sample

**Comment by RuizhiSunMS** [comment]
@mattgeim Looks SSO related.

**Comment by OfficeAddins** [comment]
Just to confirm that this is nothing to do with the Yeoman Generator project/template.
The context is when you add "office-addin-sso" to an existing project.

When I am signed into Word with an Office 365 Admin account, this is the error message:
`"Failed to load resource: the server responded with a status of 404 (Not Found)"`

when this line runs:
`let response = await makeGraphApiCall(bootstrapToken);`

GET https://localhost:8080/getuserdata?_=1667946086004

**Comment by OfficeAddins** [comment]
Q - If you add/install the "office-addin-sso" package to an existing project and add a .ENV file to that project.
Will this information, be used/imported automatically by the "office-addin-sso" package when you build the project?

Q - Do you have to include an .ENV file in order for the "office-addin-sso" package to work?

Q - Does the .ENV file have to be copied to your 'dist' folder?

**Comment by davidchesnut** [comment]
If you are creating an add-in that you plan to deploy to production, we don't recommend using the office-addin-sso package. It's primarily for trying out and learning SSO. I recommend starting with the Node.js sample at https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Office-Add-in-NodeJS-SSO. It has all the code you need to configure SSO in a production add-in.

To get the office-addin-sso package working, @millerds provided the following information. "The encapsulation made in office-addin-sso requires you to side load using the start command of the office-addin-sso package which also requires package.json to have a dev-server script with the webpack command.  This will start the secondary server (essentially the middle-tier being served off a secondary localhost port) that the call you are trying to make is looking for."

Cheers,
David

**Comment by OfficeAddins** [comment]
Thank you for clarifying that the "office-addin-sso" package is only for learning SSO and not for production.
Let me take a closer look at the Node.js sample 👍

**Comment by OfficeAddins** [comment]
Thank you for the link to the Office-Add-in-NodeJS-SSO.

Q - Could you explain the difference between '@azure/msal-node' and '@azure/msal-browser'
Can a taskpane app work with both

Q - Does the .ENV file have to be copied to your 'dist' folder
Are there any links on where to put the secret when you release to production

many thanks, Russell

**Comment by davidchesnut** [comment]
Hi Russell,

- msal-node is the library to use in Node.js servers such as express. In the sample, it enables the OBO flow to get the Graph token.
- msal-browser is the library to use in JavaScript clients (your task pane). In the sample it enables fallback auth when SSO fails.

A good way to see all the MSAL libraries and scenarios they get used in is to check out the [Microsoft identity code samples](https://learn.microsoft.com/azure/active-directory/develop/sample-v2-code). Check out the **Auth libraries** column in the table.

If you create a dist through something like webpack then yes, you need to include the .ENV (at least for testing purposes). It provides key information when the Node server starts. For deployment you should put the client secret into something like Azure key vault to keep it secure.

**Comment by OfficeAddins** [comment]
Thank you so much David, for the quick reply

**Comment by davidchesnut** [comment]
Sounds good, will close for now. Thanks!
