### ISSUE TITLE
Can no longer create new message using ms-outlook URI from task pane in Outlook on iOS

### ISSUE THREAD

**Issue by neville-jones** [OfficeDev/office-js#2958]
## Your Environment

* Platform: iOS
* Host: Outlook
* Office version number: 4.2243.1
* Operating System: iOS 15.7.1
 
## Expected behavior
User of add-in opens the add-in on Outlook Mobile (Android or iOS) and uses the add-ins **Create Message** button to create a new message in Outlook Mobile; the new message pops up in front of the add-in and has focus allowing the user to specify the recipients and body before clicking the send icon.

## Current behavior
In Outlook Mobile on iOS nothing obvious happens - no new message window appears.

(In Outlook Mobile on Android a new message window appears as expected.)

## Steps to reproduce
Have made a simplified add-in to reproduce the behaviour (see next section for details of side-loading that add-in). When using that simplified add-in, the steps to reproduce are:
1. open Outlook on iOS
2. open an existing message in the user's inbox
3. click the three ellipsis under the received time to bring up the list of add-ins, select the add-in with title "URI"
4. when the dialog "Outlook Mobile URI Test" is shown, tap the first link in the list. This form of ms-outlook URI has worked in the past, but nothing happens now.

Repeating the same in Outlook Mobile on Android, and for step 4 tapping the second link in the list (the one appropriate for Android) works as expected.

## Link to live example(s)
Have created a simple add-in to demonstrate the problem.
1. In Outlook on the Web, sideload the simplified add-in using manifest URL of [https://gray-cliff-0c2bff610.2.azurestaticapps.net/manifest.xml](https://gray-cliff-0c2bff610.2.azurestaticapps.net/manifest.xml)
2. we have observed Outlook Mobile needs to be restarted for it to detect that a new add-in is available

## Context
One feature of our add-in is its ability to help create a new email message on the mobile device with a very specific subject line syntax so we had used the ms-outlook URI scheme to create the message for the end-user (by calling the window.open method from the add-in's javascript).

## Additional information
We understand this may not be strictly an issue with the office-js library - if so, please assist us with lodging this as an issue with the Outlook Mobile team.

**Comment by exextoc** [comment]
Hey @neville-jones ,

Thank you for reporting this issue. We have added this to our backlog and will have a look at it. However, we have no timelines to share at this point.

Internal Tracking ID: 7125323

**Comment by exextoc** [comment]
We are still working on the said capabilities and they are currently not available for public consumption.

**Comment by neville-jones** [comment]
Tested on iOS 15.7.3 and Outlook 4.2304.1 and issue still present.

**Comment by neville-jones** [comment]
Tested on iOS 15.7.3 and Outlook 4.2306.0 and issue still present.

**Comment by neville-jones** [comment]
Tested on iOS 15.7.3 and Outlook 4.2309.3 and issue still present.

**Comment by exextoc** [comment]
@neville-jones As notified before, this issue is in our backlog. However, we have no timelines to share at this point.
