### ISSUE TITLE
Outlook: Register the online-meeting template for Feishu meeting

### ISSUE THREAD

**Issue by shaodowm** [OfficeDev/office-js#2959]
Can you register the online-meeting template for our feishu meeting service?

Thanks.

**Comment by exextoc** [comment]
Hey @shaodowm , please refer to the instructions [here](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting?tabs=non-mobile#register-your-online-meeting-template) about how to add your template. You need to provide the regex that needs to be parsed for the meeting.

Also share the add-in that is in app store for which this online meeting pattern needs to be registered.
