### ISSUE TITLE
Excel Application suspends when use Dialog  in excel 

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#296]
## Expected Behavior
When I open dialog from taskpanel firstly, and closed after input some info, that is OK.
But when I open dialog secondly,the Excel Application had been suspended.

<img width="1327" alt="1" src="https://user-images.githubusercontent.com/3182964/48344931-7fa63900-e6b1-11e8-9535-6f29d3e671da.png">

## Current Behavior

 Excel Application  suspended.

## Steps to Reproduce, or Live Example

* Link to live example: ___https://github.com/hengchengfei/officejs-excel-dialog___

* Additional details:
  1. ___https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/excel-tutorial-open-dialog___

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ___PC desktop___
* Host [Excel, Word, PowerPoint, etc.]: ___Excel___
* Office version number: ___16.0.11001.20064___
* Operating System: ___Windows 10___

**Comment by kbrandl** [comment]
@hengchengfei I'm unable to repro the issue that you've described. Are you still having this problem?

**Comment by kbrandl** [comment]
@hengchengfei I'm closing this GitHub issue due to lack of response. If you're still having this problem, please comment on this issue so that we can re-open this issue and engage with you to investigate. Thanks!
