### ISSUE TITLE
How to capture iframe open and close event

### ISSUE THREAD

**Issue by CG49071** [OfficeDev/office-js#2961]
We are using custom outlook addin which opens our application inside the iframe. Do we have provision for capturing iframe open and close events. We need this data to analytics purpose to capture how long addin was used.

**Comment by exextoc** [comment]
You can use the iframe [beforeunload](https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event) properties to help capture the time when the iframe is unloaded. Does that work for you?
