### ISSUE TITLE
Word DocumentSelectionChanged not firing for several scenarios

### ISSUE THREAD

**Issue by evaneaston** [OfficeDev/office-js#2964]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2210 (Build 15726.20174)
* Operating System: Windows 11
* Browser (if using Office on the web): n.a.
 
## Expected behavior

`Office.context.document.addHandlerAsync(Office.EventType.DocumentSelectionChanged, ...)` doesn't reliably fire events for all selection changes.

## Steps to reproduce

I've created a repo that can help demonstrate the problem

1. clone repo at https://github.com/evaneaston/office-js-issue-DocumentSelectionChanged
2. npm install
3. npm run start
4. ensure the Show Task pane add in opens
5. type some text into the body of the document
6. paste an image in after
7.  use mouse or keyboard to select various parts of the text and image.  the task pane will log whenever the selection changed event is fired
8. clear selection (Esc), click right in front of image, press Shift+Right Arrow.  Notice that the selection doesn't change.  If you press Shift+Right Arrow a second time, the doc selection changed event is finally fired.
9.  clear selection, from the Insert tab, add a Picture (from local computer or web).  When the image is added click off and on it.  Noticed that the doc selection changed evens is not triggered.

Essentially, all this repo does is listen for `DocumentSelectionChanged` and add a timestamped log to the task pane so you don't have to go launching dev tools.

```
const now = () => new Date().toISOString().replace(/^.*?T/, "").replace(/\..*/, "");

export async function selectionChanged(_event: Office.DocumentSelectionChangedEventArgs) {
  addToLog(`${now()}: selection changed`);
}

Office.onReady(() => {
  OfficeExtension.config.extendedErrorLogging = true;
  Office.context.document.addHandlerAsync(Office.EventType.DocumentSelectionChanged, selectionChanged, () => {});
  render(TaskPane); 
});
```

## Link to live example(s)

n.a.

## Context

It doesn't seem like there's a bullet proof mechanism for listening to the document selection and determining when an image is selected.  There are corner cases where an image is selected, but no event is fired.

## Useful logs
- [ ] Console errors
- [X] Screenshots
   * https://github.com/evaneaston/office-js-issue-DocumentSelectionChanged/blob/main/Screen%20Recording.gif
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by jipyua** [comment]
hi, thanks for reporting this. From the gif and my local testing, seems the event is always fired. can you share more information about at exactly what cases it's not fired?

**Comment by evaneaston** [comment]
I was concerned that it wouldn't be abundantly clear what's happening in the gif because of no audio. 

I updated my repo to include more explicit instructions to reproduce and it includes [an updated screen recording](https://github.com/evaneaston/office-js-issue-DocumentSelectionChanged/blob/main/Screen%20Recording%202.gif) where, I hope, it's a little clearer that, when the selection/caret is directly in front of the image, that clicking the image or selecting it with **Shift+RightArrow** does not trigger an event.

**Comment by jipyua** [comment]
thanks for providing more detailed videos, we have logged a bug internally and will triage accordingly.
