### ISSUE TITLE
OWA: Office.context.mailbox.item.loadCustomPropertiesAsync set property will create a draft event, and can not cancel after discard this event

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#2965]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

code segment
```
function setCustomInfo () {
    Office.context.mailbox.item.loadCustomPropertiesAsync((result) => {
        console.log(result);
        let customProps = result.value;
        customProps.set("demo", 'test');
        customProps.saveAsync((asyncResult) => {
            console.log(asyncResult);
        })
    })
}

function removeCustomInfo () {
    Office.context.mailbox.item.loadCustomPropertiesAsync((result) => {
        console.log(result);
        let customProps = result.value;
        customProps.remove("demo");
        customProps.saveAsync((asyncResult) => {
            console.log(asyncResult);
        })
    })
}

function getCustomInfo () {
    Office.context.mailbox.item.loadCustomPropertiesAsync((result) => {
        console.log(result);
    });
}
```
after call setCustomInfo, in owa will create a draft event. after discard this draft event, it can't be drafted.
![add-in issue 1](https://user-images.githubusercontent.com/1878089/201307096-d077ea60-0697-410c-a0a9-053bfddbb420.gif)

**Comment by samantharamon** [comment]
Thank you for reporting this, @hello-chenchen.

@exextoc, is this something you can assist with?

**Comment by exextoc** [comment]
Apologies for late reply @hello-chenchen. We missed looking at this issue.

1. We are able to reproduce the scenario as shown by you in the GIF. Thanks for sharing GIF :-)
2. The dialog shown by Outlook Web App (OWA) client when closing the event in both your scenarios are different. In cases where add-in is not being used, OWA is showing "Discard Event" dialog. In cases where add-in is being used (and event gets saved as draft), OWA is showing "Discard changes" dialog box. So, when we answer "Yes" to "Discard changes", OWA is expected to discard any unsaved changes and not discard the event completely.
3. Why is draft getting created? To save custom properties safely, when customProperties.saveAsync() API is being called from addin, event gets created in backend and hence you see "draft" being created on calendar as well. 
4. Are you expecting different behavior from OWA in such cases when "close" (x mark) is clicked? Are you expecting different behavior for any of our customProperties APIs in such cases? 
5. For your add-in use case, does such "draft" event create problem in add-in usability? Can you please explain that use-case?
