### ISSUE TITLE
Insert file to the footer of section instead of header

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#2966]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___PC desktop___
* Host [Excel, Word, PowerPoint, etc.]: __Word____
* Office version number: ___Microsoft® Word 2019MSO (版本 2202 Build 16.0.14931.20764) 64 位___
* Operating System: ___Windows___
* Browser (if using Office on the web): ___Edge___
 
## Expected behavior

Insert file to the footer of section.
## Current behavior
I want to insert file to the footer instead of header.
 
## Code
```ts
  await Word.run(async (context) => {
    const sections = context.document.sections;
    sections.load("items");
    await context.sync();

    sections.items[sections.items.length - 1].getFooter("FirstPage").insertFileFromBase64(base64, "End");

    await context.sync();
  }).catch((e) => {
    console.log(e);
  });
```

[base64.txt](https://github.com/OfficeDev/office-js/files/9990611/base64.txt)
![1](https://user-images.githubusercontent.com/3182964/201352363-512c9884-e129-4867-b3d6-418c9c3cf575.png)

**Comment by jipyua** [comment]
hi, I think you should use "Primary" instead of "FirstPage" to get the header/footer if your header/footer doesn't have special settings compare to other pages.

**Comment by hengchengfei** [comment]
@jipyua 
I tried “Primary”、“FirstPage”、“EvenPages”,But doesn't work!

There is no special settings.

[test.docx](https://github.com/OfficeDev/office-js/files/10000208/test.docx)

**Comment by jipyua** [comment]
would you please change your code to sections.items[sections.items.length - 1].getFooter("Primary").insertText("base64", "End"); to confirm whether it's the insertFileFromBase64 issue or footer issue?

**Comment by hengchengfei** [comment]
@jipyua 

I tried by follow attach files.

[Test.docx](https://github.com/OfficeDev/office-js/files/10009979/Test.docx)
[base64.docx](https://github.com/OfficeDev/office-js/files/10009980/base64.docx)
![1](https://user-images.githubusercontent.com/3182964/201847935-0f680d9d-362a-41fb-bb6a-2bdb798feac7.png)

**Comment by jipyua** [comment]
Thanks, providing the Base64.docx file help clear the confusions. This is because your base64 file contains a text box, if you try a simple base64 file which just contains plain text, you will find that the content is inserted just to the footer.

If from UI, you tried to insert a text box to footer, you will find that you can both access the text box from header/footer and not just to footer. So this behavior is by design from UI and API also has similar behavior.
