### ISSUE TITLE
Is there any plan for Taskpane widths to be adjustable by `RequestedWidth`?

### ISSUE THREAD

**Issue by sureshjoshi** [OfficeDev/office-js#2968]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

The default 320-350px Taskpane width is very limited, especially with progressively wider monitors and laptop screens. 

Is there some way this default could be increased (even to as little as 480px), or perhaps the default taskpane width depends on the width of the user's screen, or perhaps `RequestedWidth` could be a valid manifest entry for Taskpanes?

Having to make notes in the documentation, or on-screen notes to the user, that they can widen their add-in taskpane makes for poor user experience unfortunately.

**Comment by hengchengfei** [comment]
+1

**Comment by RuizhiSunMS** [comment]
@ElizabethSamuel-MSFT Do you have any idea about who can help this?

**Comment by ElizabethSamuel-MSFT** [comment]
Adding @preethikakiru and @Rick-Kirkham - Any ideas who may be able to help with this?

**Comment by Rick-Kirkham** [comment]
@preethikakiru would know about future plans for providing this option.
