### ISSUE TITLE
Bindings Created from `setDataAsync` in Word Online Do Not Work As Expected

### ISSUE THREAD

**Issue by gkarmelich** [OfficeDev/office-js#2969]
# Provide required information needed to triage your issue

Bindings created and updated in Word Online do not work as expected. If a binding is created in a Word Online document and the document is saved, the downloaded document does not retain the binding when opened in the desktop Word version. The binding is also broken if re-opened in Word Online at a later time. 

## Your Environment

* Platform: **Office Online**
* Host: **Word**
* Office version number: **Build 16.0.15902.41009**
* Operating System: **Windows 10**
* Browser: **Chrome (107.0.5304.107)**
 
## Expected behavior

The expected behavior is that bindings created in Word Online persist across all Word platforms.

## Current behavior

Currently, bindings created that are not on their own line break after leaving the Word online session. This only happens in Word Online, and not when bindings are created/updated using `setDataAsync` in either Word Desktop for PC or Word Desktop for Mac.

## Steps to reproduce

1. Create and update a binding in Word online by using the following code example:
```
  async setBindingValueForBindingIdTest(binding) {
    return new Promise( resolve => {
      binding.setDataAsync('Name', { coercionType: 'text' },
        async asyncResult => {
         resolve(asyncResult);
      });
    });
  }
```
2. Insert the binding once on its own line
3. Insert the biding a second time, but sharing a line with text that is not part of the binding
4. Save the Word document.
5. Open it on Word Desktop or Word Online again. You will notice that the binding created in Step 3 is broken. However, the binding created in Step 2 works as expected.

## Context

Our team discovered this issue as of November 10, 2022 , but we are unsure of when the bug may have surfaced. It is a large vulnerability for our user base, so we appreciate getting this investigated as soon as possible.

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Here is a screenshot from Word Online. You can see that the `Name` binding is active.

![word-online](https://user-images.githubusercontent.com/32963798/201648131-d66510c7-2ed7-4b84-814c-436bcc38c90c.PNG)

However, after downgliding this copy and opening on Word Desktop, the binding is no longer active. Note that the second binding, where `Name` is on its own line, works as expected.

![word-desktop](https://user-images.githubusercontent.com/32963798/201648394-7fcd65ae-8aae-468c-8377-4c0b2433bd80.PNG)

**Comment by samantharamon** [comment]
Thank you for reporting this, @gkarmelich.

@wangyun-microsoft, could you please assist with this?

**Comment by RuizhiSunMS** [comment]
@gkarmelich Thanks for your reporting. After some investigation, our colleagues confirmed this issue is a bug. We have put this into our backlog list with an ID #7233198.
Any update will be put here if achievement is got but sorry that we can't provide a timeline now.

**Comment by gkarmelich** [comment]
@RuizhiSunMS Do you have an update on this issue? Our customers are experiencing this issue and it would be great to be able to provide them with a timeline.

**Comment by jingxuan0109** [comment]
@gkarmelich We already had a fix. It is now under a flight and will generally open it ring by ring. Sorry I cannot tell you the exact date it will open 100% on production. Once it is on production 100%, I will update it to you. Thanks.

**Comment by jingxuan0109** [comment]
@gkarmelich  The fix has been deployed to production 100%. Could you double confirm on your side?

**Comment by gkarmelich** [comment]
@jingxuan0109 confirming this is fixed.

**Comment by jingxuan0109** [comment]
Thank you~
