### ISSUE TITLE
In Chart Object the chartType is coming as null for waterfall and radarfilled charts.

### ISSUE THREAD

**Issue by Shashank-Deol** [OfficeDev/office-js#2971]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

In Chart Object the chartType is coming as null for waterfall and radarfilled charts.
This might be happening with other charts as well.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior
chartType should return "Waterfall" or "RadarFilled" for Waterfall and Radarfilled charts.

## Current behavior
In Chart Object the chartType is coming as null for waterfall and radarfilled charts.

**Comment by donlvMSFT** [comment]
Hi @Shashank-Deol , 

currently ChartType is not supported for some kinds of chart in some cases. It would happens on Map, Treemap, Sunburst, Histogram, Radarfilled, Box&Wisker, Waterfall, Funnel Chart types. 
We already have a internal task to track this issue (#2261355).

Thanks,
Dongqi

**Comment by sndurkin** [comment]
@gergzk since this is closed, is there any workaround for this gap? Even using private APIs?
