### ISSUE TITLE
Unable to use add-ins on workbook that save from Excel on Windows

### ISSUE THREAD

**Issue by Refinitiv-365** [OfficeDev/office-js#2973]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

when I use custom functions on Excel on Windows and save a workbook then close and open it again on Excel Online.
The custom function does not work and the task pane show warning "This Add-ins is not available in Office on the web".
The add-ins work on Excel Online when creating a new workbook or workbook saved by Excel Online
![image-2022-11-14-15-07-42-529](https://user-images.githubusercontent.com/98725157/201903397-93c8aee7-19be-40d0-b4c4-bfdaf8d73cbf.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft Office 365 Version 2210 Build 16.0.15726.20070 64-bit
* Operating System: Windows 10 Version 20H2 Build 19042.1706
* Browser (if using Office on the web): Microsoft Edge
 
## Expected behavior
Add-ins should work on workbooks with custom functions that save from Excel on Windows

## Current behavior
Add-ins are not able to run on workbooks with custom functions that save from Excel on Windows

## Steps to reproduce
1. Create add-ins following https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows
2. Add support shared runtime following https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial
3. npm run dev-server
4. Create a new workbook on Excel on Windows and sideload add-ins https://learn.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins
5. Add formula "=CONTOSO.INCREMENT(2)"
6. Waiting formula to show results
7. Save a workbook and Close Excel on Windows
8. Open the workbook on Excel Online
9. Manual sideload add-in with the same manifest file as Excel on Windows https://learn.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins
10. Formula struck at #BUSY and When click "Show Taskpane" the taskpane shows up with a warning.

**Comment by RuizhiSunMS** [comment]
Hi @Refinitiv-365, thanks for reporting this.
One thing I want to make sure is: how is the addin without custom functions? Does the addin without custom functions still have this error? This may help us to locate target area.
Thanks

**Comment by Refinitiv-365** [comment]
Hi @RuizhiSunMS .

The workbook without any formulas, it's working normally.
