### ISSUE TITLE
Wrong recipient type in Outlook web (response for a meeting)

### ISSUE THREAD

**Issue by mimaj-oaw** [OfficeDev/office-js#2975]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook web, Outlook PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2110 (Build 14527.20234)
* Operating System: Windows
* Browser (if using Office on the web): Chrome Version 107.0.5304.107 (Official Build) (64-bit)
 
## Expected behavior

Recipient type (Outlook web) should be "user" instead of "other". 
Recipient type should be the same in Outlook web as in Outlook PC desktop

## Current behavior

The recipientType of a user within the same organization is different on different hosts within the reply message of an appointment.
- User (On PC Desktop)
- Other (On Office on the web)

## Steps to reproduce

- Use main tenant to create appointment.
- Invite internal user for the appointment.
- Log in as internal user.
- Go into the appointment.
- Reply for the appintment.

## Link to live example(s)
https://gist.github.com/mimaj-oaw/c8a13fae8025a6545fa052c4ee4a92ec

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding recipient type on OWA. It has been put on our backlog. We unfortunately have no timelines to share at this point
Internal tracking id: 3204347
