### ISSUE TITLE
#value! message instead of arguments type in Function Argument box

### ISSUE THREAD

**Issue by maxym2020** [OfficeDev/office-js#2977]
I'm building an Excel add-in with Custom Functions. This function has a description with types for every argument. To create a functions.json file I use YO generator provided by Microsoft. Everything works fine until some COM add-in is installed. In that case, the Function Arguments box shows the wrong argument types.

## Expected Behavior

![correct behavior](https://user-images.githubusercontent.com/112814186/202202530-076b3a1a-7d56-4fb5-9618-451c14a91760.jpg)

There shouldn't "#VALUE!" message  instead of arg type in the Function Arguments box

## Current Behavior

 "#VALUE!" text instead of arg type
![wrong behavior](https://user-images.githubusercontent.com/112814186/202202898-b9d5c46d-75cb-4edb-bcf9-8aaed62d5186.jpg)

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. Create simples add-in for Excel with shared state using YO generator.
  2. Create simplest custom function with  args for Excel add-in.
  3. Install any Excel COM add-in on your computer

## Your Environment

* Platform : PC desktop
* Host: Excel 
* Office version number: 16.0.14332.20412
* Operating System: win 10 pro 19043.2130
* Browser (if using Office Online): any

**Comment by samantharamon** [comment]
Thanks for reporting this, @maxym2020.

@yaweizhu-henson, is this something you can assist with?

**Comment by donlvMSFT** [comment]
Hi @maxym2020 , thanks for report this issue, I'm trying to repro but seems it works well with the first party com add-ins.
![image](https://user-images.githubusercontent.com/42738188/202402130-e01c50cf-1788-411d-8b51-151b0b74b7d9.png)
Could you share which com add-in you are using to reproduce? That could be really helpful.

**Comment by maxym2020** [comment]
Of course. 
I took it here: https://www.asap-utilities.com/download-asap-utilities.php
ASAP utilities. Home & student version

P.S. I confirm that everything is ok with "pre-added" com addins. ( I tried to turn on Pivot one)

**Comment by donlvMSFT** [comment]
Hi @maxym2020 , I tried on latest Office CC version, seems this issue is not happened, What's your channel? We could double confirm on that version.

**Comment by maxym2020** [comment]
@donlvMSFT What do you mean "channel"? To speak live?

**Comment by RuizhiSunMS** [comment]
@maxym2020 see the last line 'Microsoft Current Channel (OuterRing)', you can get this by 'File -> Account'
![image](https://user-images.githubusercontent.com/97079392/203462030-ee5dbb16-0492-4a7b-b529-d3d18398005f.png)

**Comment by maxym2020** [comment]
No third line there
![image](https://user-images.githubusercontent.com/112814186/203523260-f2f3757f-1b5f-476a-98c0-f7b8c1bd293e.png)

**Comment by maxym2020** [comment]
@RuizhiSunMS 
Hi!
New updates.
I tried to create  a new excel add-in using this official  [manual](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview)
After that, I added help url to function description: 
`Add two numbers
@helpUrl https://somesite.com`

Everything was OK. 
But then I installed ASAP utils add-in. 
And the help url became broken. 
And the type of arguments for the LOG  function was marked as NUMBER
![Screenshot 2022-11-24 191241](https://user-images.githubusercontent.com/112814186/203838186-d3d6c92a-2cbe-4ff0-838c-76304211511c.jpg)
![Screenshot 2022-11-24 191210](https://user-images.githubusercontent.com/112814186/203838200-bc999d54-8953-49bd-b8d8-324b522c137a.jpg)

**Comment by maxym2020** [comment]
@yaweizhu-henson @donlvMSFT  What kind of data can I provide to help with this issue?

**Comment by donlvMSFT** [comment]
Hi @maxym2020 , we're still trying to repro the issue, but from our environment, couldn't get same result. Do you know which channel or subscription of Office are you in?

**Comment by maxym2020** [comment]
No, I don't know. The channel row is empty. 
And I have some corporate subscription.

**Comment by donlvMSFT** [comment]
Hi, sorry for the late response. We'd like to combine this issue with https://github.com/OfficeDev/office-js/issues/3352. We already opened an internal bug to track this issue: #8009934. Or you can provide the scale of affected users, it will help us re-prioritize this problem. Thanks for your patience!

**Comment by JEGUOCEAN** [comment]
Hi everyone
![image](https://github.com/OfficeDev/office-js/assets/146344096/e523182b-4ab8-4cb4-8d43-64280882dcda)
I was able to reproduce with scriptlab just following the steps I proposed => on first workbook it is ok, on second not, when you reopen function wizard it shows error.
It is not the same issue than https://github.com/OfficeDev/office-js/issues/3352. because there is no link with COM addin.

**Comment by lucadom** [comment]
Same problem here.
Any updates about this issue?

**Comment by maxym2020** [comment]
We still experience this issue. No changes at all.

вт, 27 серп. 2024 р. о 09:23 Luca Dominici ***@***.***> пише:

**Comment by XuanZhouMSFT** [comment]
@maxym2020 @JEGUOCEAN @lucadom Thanks for reporting this issue. We already release a fix which is in monthly production with version for Win32 >= 16.0.17926 and MAC >= 16.89. Please help to check whether this still repro on your side. Thanks so much.

**Comment by lucadom** [comment]
Hi @XuanZhouMSFT , i can still reproduce the issue, but the more i see it, the more i think  we should combine it with #3352, as one of your colleagues suggested last year.
I am also following the other mentioned issue, hoping that the fix you are working on will provide a solution for both.
