### ISSUE TITLE
invalid argument on body.insertOoxml in Word 2016 (16.0.5366.1000)

### ISSUE THREAD

**Issue by bkonic** [OfficeDev/office-js#2978]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Extracting the body with getOoxml() and then inserting it again with body.insertOoxml fails with  Rich.api error "invalid argument"

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC 
* Host [Excel, Word, PowerPoint, etc.]: Word 2016 Desktop MSO 16.0.5366.1000
* Office version number: 2016
* Operating System: Windows 10 
* Browser (if using Office on the web): N/A
 
## Expected behavior
I expect the code below to complete without errors and the document to remain unchanged (since the same body is inserted)

## Current behavior
Fails with error: message: InvalidArgument, name: RichApi.Error, httpStatusCode: 400

## Steps to reproduce
execute the following lines in an add-in in Word 2016:
    var body = context.document.body;
    var body_ooxml = body.getOoxml();
    await context.sync();
    var body_ooxml_value = body_ooxml.value;
    body.insertOoxml(body_ooxml_value, Word.InsertLocation.replace);
    await context.sync();

We also tried several other combinations regarding the second argument of body.insertOoxml ("start","end") etc.. All failed in Word 2016

## Context
We have a Word Add-in that removes sensitive data automatically - including hyperlinks . Since Word js 1.1 does not support `methods` to change hyperlinks, we aim to change the Ooxml by removing all hyperlinks and write it back. (removing the hyperlinks is omitted from the code sample) This works in Word for M365 (Version 2210 Build 16.0.15726.20188) 64-bit -  but NOT in Word 2016. Word 2016 should support Word Api js 1.1 (requirements set) and hence all of the code above should work.

## Useful logs
see screenshot of console log 

![bug](https://user-images.githubusercontent.com/58952705/202265973-a92ac971-50ef-4f20-b0c9-222226a40c93.PNG)

**Comment by jipyua** [comment]
Thanks for reporting this, this is a known issue and has been fixed internally. Once the fix is deployed, you should be able to pick it.

**Comment by bkonic** [comment]
Thank you, when can I expect the fix to be deployed?

**Comment by jipyua** [comment]
In order to make sure the quality, there is some internal process to let the changes go through different channels, it may take some time but we will try to deploy it as soon as possible. thanks for your patience.

**Comment by bkonic** [comment]
I made some additional tests and found out that the issue only occurs in the latest release (1.1.83_custom.0).
With Version 1.1.82 there is no exception when executing insertooxml.
(Although there is another issue with version 1.1.82 : #2991 )
