### ISSUE TITLE
Word API in Search method not working on Other regions 

### ISSUE THREAD

**Issue by Alpesh-Chaudhari** [OfficeDev/office-js#2980]
Hello Team,
I am using Word API  for developing word add-in. I have used search method for searching all number from the word document. When I am using Slovenian(Slovenia) region then this method throw error and if I am using English(United States) then search method working fine.

# My Environment

* Platform : PC desktop
* Host: Word
* Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2210 Build 16.0.15726.20188) 64-bit 
* Operating System: Windows 10 pro

 #Snippet :
 ```
var Prange = context.document.getSelection();
  context.load(Prange, 'text');
 await context.sync();
 var searchResults = Prange.search('[0-9,.]{1,}', { matchWildcards: true });
 context.load(searchResults, 'text,font');
 await context.sync();
```

#Console Error :

Debug info: {"code":"GeneralException","message":"GeneralException","errorLocation":"","statement":"_Search2.load([\"text\",\"font\"]);","surroundingStatements":["var v = context.root._getObjectByReferenceId(\"01D!00000010\") /* originally getSelection() */;","var _Search2 = v._Search2(...);","// Instantiate {_Search2}","// >>>>>","_Search2.load([\"text\",\"font\"]);","// <<<<<","var contentControls = v.contentControls;","// Instantiate {contentControls}","contentControls.load();"],"fullStatements":["var v = context.root._getObjectByReferenceId(\"01D!00000010\") /* originally getSelection() */;","var _Search2 = v._Search2(\"[0-9,.]{1,}\", 4);","// Instantiate {_Search2}","_Search2.load([\"text\",\"font\"]);","var contentControls = v.contentControls;","// Instantiate {contentControls}","contentControls.load();"]}

#When region is English (United States) :
<img width="956" alt="SS" src="https://user-images.githubusercontent.com/63895336/202447849-0297d8bb-21fc-4f5c-8f4e-3b6208ea44f1.PNG">

#When region is Slovenian(Slovenia) :
<img width="960" alt="SS1" src="https://user-images.githubusercontent.com/63895336/202448018-5ea3d2a5-688f-45a3-93ec-b1426dd84896.PNG">

Is there any solution is there ?

Please provide any solution for this issue .

**Comment by samantharamon** [comment]
Thank you for reporting this, @Alpesh-Chaudhari.

@wangyun-microsoft, could you please assist with this?

**Comment by xuruiyao-msft** [comment]
@Alpesh-Chaudhari  I cannot reproduce the issue.  Would you please upgrade your word version to latest and try it again? Thanks!

**Comment by GavinGu07** [comment]
Thanks for reporting this. We have reproduced your issue. It seems like a bug and we will start investigating on our side to see how to give a fix.

**Comment by jipyua** [comment]
@Alpesh-Chaudhari  this issue has been fixed and will be rolled out gradually, it should be available in next month's update, please update your M365 Office to the latest version and have a try. thanks.
