### ISSUE TITLE
Word crashes after contentControl.getHtml in Word Online

### ISSUE THREAD

**Issue by kgeorgiou1234** [OfficeDev/office-js#2982]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

In word online, if you have a list of content controls, you use getHtml, if you then try to set the content again, the word online crashes after some time (even if you don't do anything after the last modification of the content control)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: Windows
* Browser (if using Office on the web): Edge
 
## Current behavior
Content control to be able to have consecutive executions between setting the html and retrieving the html without any issues.

## Steps to reproduce
1.	Open a new Word document online
2.	Run the script from ‘Script Lab’
3.	Click on the following buttons consecutively (no need to wait for the saving to be completed)
        a.	Setup
        b.	Insert
        c.	Modify content controls
4.	Wait for the saving to be completed and then click ‘Get content control’s HTML’
5.	Wait for the saving to be completed (if any) and then click ‘Modify content controls’ and wait.
6.	The page mode should switch from ‘Editing’ to ‘Viewing’ after a while and a notification shown that the changes cannot be saved automatically OR to reload to not lose your changes.
Note: Wait time could be about a minute.
![image](https://user-images.githubusercontent.com/107611022/202715690-ab076f43-ab9b-4e4f-9f38-aa6dc00d615e.png)

![image](https://user-images.githubusercontent.com/107611022/202715710-3e191884-2ae9-41d6-bd79-e413749e2738.png)

## Link to live example(s)

Script lap snippet  [Script Lab - Snippet.txt](https://github.com/OfficeDev/office-js/files/10041630/Script.Lab.-.Snippet.txt)

## Context
The word add-in is for manipulating content control. The content will be set from the back end, updated by the users and saved back to the DB. Then the users can again retrieve the data from the backend and continue in this pattern.

## Useful logs

- [ x ] Screenshots
- [ x ] Test file (if only happens on a particular file)

**Comment by xiruatms** [comment]
Thanks for reporting this. I've tried to repro this issue based on your steps. Unfortunately, I can't repro it.

Will you please help to clarify more for me?
1.  Does this happen all the time? Or just intermittently?
2.  Why are you mentioning that getHtml might be the reason of crashes? According to your steps, there're other operations/steps after getHtml.
3.  Do you notice any exceptions/errors from the console of Developer Tools?
4. Will you please help to provide a screen recorder? That will help much for us to understand your issue.

**Comment by kgeorgiou1234** [comment]
1. Yes it happens every time we execute the specific order of steps
2. The only step after getHtml is to set the HTML. If this step is executed multiple times, there are no errors even if you wait for some time. As soon as you call getHtml and then set the content control's html again, if you wait for about a minute, then you get the crash.
3. No other exceptions in the console.
4. You will need to wait for a minute after the last step and must be done in the browser. Please note that we also have sensitivity labels enabled, not sure if this is affecting the functionality. Video added

[Demo issue with console logs.zip](https://github.com/OfficeDev/office-js/files/10055631/Demo.issue.with.console.logs.zip)

**Comment by kgeorgiou1234** [comment]
[Screen recording.zip](https://github.com/OfficeDev/office-js/files/10055647/Screen.recording.zip)

**Comment by kgeorgiou1234** [comment]
@xiruatms any update on this?

**Comment by kgeorgiou1234** [comment]
More tests on different accounts and machines are done using this script. The issue is reproducible only when sensitivity labels are enabled. 
Waiting your feedback on this. Thank you.

**Comment by jingxuan0109** [comment]
@kgeorgiou1234 Sorry for the late response. Thanks for your reporting. After some investigation, we confirmed this issue is a bug. We have put this into our backlog list with an ID #7242237.
Any update will be put here if achievement is got but sorry that we can't provide a timeline now.
