### ISSUE TITLE
getAttachmentsAsync return inline attachments after delay.

### ISSUE THREAD

**Issue by AlexSanin** [OfficeDev/office-js#2984]
## Environment: 
Platform [PC desktop, Mac, iOS, Office on the web]: Outlook PC desktop
Host [Excel, Word, PowerPoint, etc.]: Outlook
Office version number: 2110 (Build 14527.20234)
Operating System: macOs Ventura 13.0.
## Expected Behaviour: 
call 
`const item = Office.context.mailbox.item`
`const options = { asyncContext: { currentItem: item } }`
`const inlineAttachments = new Promise( (resolve) => item.getAttachmentsAsync(options. (result) =>  resolve(result.value)) `
will return inline images for an email in compose mode.
## Current Behaviour:  
I am trying to get inline images in message compose mode in the Outlook application. 
I call
`const item = Office.context.mailbox.item`
`const options = { asyncContext: { currentItem: item } }`
`const inlineAttachments = new Promise( (resolve) => item.getAttachmentsAsync(options. (result) =>  resolve(result.value))` in the add-in. 
This will return an empty array. In case I wait a couple of seconds and call it again I will return an array with inline items.
The question is: why this delay happened? Is it by design?

**Comment by zhngx1** [comment]
Hi [AlexSanin](https://github.com/AlexSanin), in your last line of code, it should be a comma after the options, and there is a missing ) at the end of line.
`const inlineAttachments = new Promise( (resolve) => item.getAttachmentsAsync(options, (result) => resolve(result.value)))`

But I presume that's not the issue here. Have you tried to call .then on the inlineAttachments to get the result? Or if you try the code below does it give you any result?
`item.getAttachmentsAsync(options, (result) => console.log(result.value))`

**Comment by AlexSanin** [comment]
> Hi [AlexSanin](https://github.com/AlexSanin), in your last line of code, it should be a comma after the options, and there is a missing ) at the end of line. `const inlineAttachments = new Promise( (resolve) => item.getAttachmentsAsync(options, (result) => resolve(result.value)))`
> 
> But I presume that's not the issue here. Have you tried to call .then on the inlineAttachments to get the result? Or if you try the code below does it give you any result? `item.getAttachmentsAsync(options, (result) => console.log(result.value))`

this didn't work, the response was always the same {status: succeed} but no items still.

**Comment by zhngx1** [comment]
Hi @AlexSanin, are you working on mac or windows? Are you running a VM?

**Comment by AlexSanin** [comment]
@zhngx1 Hello, sorry for the late response. I have tried on both mac and windows. The result stays the same.

**Comment by zhngx1** [comment]
@AlexSanin No worries. How did you insert the inline image, did you use the API to insert the image or did you manually do copy + paste to insert the image?

**Comment by AlexSanin** [comment]
> @AlexSanin No worries. How did you insert the inline image, did you use the API to insert the image or did you manually do copy + paste to insert the image?

If I understood you correctly, the user adds image manually inside Outlook. Then inside my add-in I call Microsoft JS API and get them.

**Comment by zhngx1** [comment]
Thanks @AlexSanin for catching the issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.
Internal tracking id: Office: [7580376]

**Comment by JuaneloJuanelo** [comment]
Alex to add more comments here, the reason why you need to wait a bit for this to work is that maybe the item has not YET been saved (as draft). one thing you can try in the meantime to get the attachments is to save the item programmatically (item.save) if tis super critical for you to get the latest.

**Comment by JuaneloJuanelo** [comment]
issue is on the backlog and workaround presented, closing issue.
