### ISSUE TITLE
Powerpoint Add-In fails to load on desktop but not web saying "We can't load this add-in because we couldn't connect to the catalog"

### ISSUE THREAD

**Issue by mattlindsay26** [OfficeDev/office-js#2985]
# Provide required information needed to triage your issue
My Add-In (Peargrin) works in Excel & Powerpoint using the same manifest. It works just fine in Excel. In Powerpoint, it loads just fine on web but does not load on desktop (see screenshot). Clicking "See Details" brings me to this [link](https://appsource.microsoft.com/en-us/product/office/WA200004586?src=office&corrid=360af446-7fa9-6b00-b618-d11e371708db&omexanonuid=&referralurl=&ClientSessionId=9dd49741-03a7-4973-a979-e1cb293ca73a). I went through support (Case #:32915959), they were able to reproduce the issue but not resolve it and I was directed here.

## Your Environment
This issue occurs for **all of our users on all platforms** - have reproduced on Mac & Windows. Support was able to reproduce on Mac. I will include my specs if that helps.

* Platform [PC desktop, Mac, iOS, Office on the web]: MacBook Air (Retina, 13-inch, 2020)
* Host [Excel, Word, PowerPoint, etc.]: Powerpoint
* Office version number: 16.66.1 (22101101)
* Operating System: Mac OS 10.15.3
* Browser (if using Office on the web): -
 
## Expected behavior
I expect that when adding the add-in from AppSource that it will load properly from the catalog on desktop and web.

## Current behavior

The add-in fails to load saying: "We can't load this add-in because we couldn't connect to the catalog"

## Steps to reproduce

1. Go to AppSource on Powerpoint Desktop (Insert -> Get Add-Ins)
2. Search "Peargrin" and click "Get it now" -> "Open in Powerpoint"
3. A Powerpoint presentation will launch. It will attempt to load the Add-In with the failure message: "We can't load this add-in because we couldn't connect to the catalog". Clicking "See Details" will bring you to the AppSource page.

# Provide additional details

1. It works fine on Web - the only issue is on desktop.
2. This is NOT a security issue. This happens for all users on all devices on all networks. There has been no recent change to anyone's security policy. All users are able to load the Excel Add-In which uses the same manifest.

## Context
Our Add-In drives value from linking Powerpoint & Excel. This is a critical, blocking error.

<img width="1440" alt="Screen Shot 2022-11-21 at 6 35 37 PM" src="https://user-images.githubusercontent.com/16980079/203179300-6c448e75-780b-447e-bfb1-43c5af4fe442.png">

**Comment by mattlindsay26** [comment]
Please let me know if there is any additional information I can provide to accelerate the process.

**Comment by davidchesnut** [comment]
Hi @mattlindsay26, thanks for letting us know about this issue. I can repro this as well. @wangyun-microsoft can you please help on this issue to determine why this is happening?
Thanks!

**Comment by mattlindsay26** [comment]
@wangyun-microsoft , please let me know if there is anything I can do to help. Do we have any expected timeline?

**Comment by davidchesnut** [comment]
Hi @mattlindsay26, I'll ping @wengyun-microsoft again. 

BTW: I noticed something strange. It seems to work with Excel (or at least the task pane opens but it indicates it is not supported.) Same thing in a browser. The add-in appears on the menu for Excel, but not for PowerPoint. You might double-check the manifest file to be sure there isn't something confusing the PowerPoint/Word/Excel requirements.

**Comment by wangyun-microsoft** [comment]
Hi @mattlindsay26,

Thanks for reporting this. We could reproduce the error you found. Is it possible to share a manifest file for us to further investigate?

**Comment by mattlindsay26** [comment]
The manifest is below.

When I run `office-addin-manifest validate manifest.xml` it says "The manifest is valid."

Please let me know if you see an issue! I will look myself now.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="TaskPaneApp">
  <Id>7de7719c-63af-4a23-b6da-18737d639b9b</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Peargrin</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Peargrin"/>
  <Description DefaultValue="Work fast and confident with Peargrin."/>
  <IconUrl DefaultValue="https://peargrin-excel.herokuapp.com/assets/peargrin-32x32.png"/>
  <HighResolutionIconUrl DefaultValue="https://peargrin-excel.herokuapp.com/assets/peargrin-64x64.png"/>
  <SupportUrl DefaultValue="https://www.peargrin.com/contact"/>
  <AppDomains>
    <AppDomain>https://www.peargrin.com</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Workbook"/>
    <Host Name="Presentation"/>
  </Hosts>
  <DefaultSettings>
    <SourceLocation DefaultValue="https://peargrin-excel.herokuapp.com/taskpane.html"/>
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Hosts>
      <Host xsi:type="Workbook">
        <DesktopFormFactor>
          <GetStarted>
            <Title resid="GetStarted.Title"/>
            <Description resid="GetStarted.Description"/>
            <LearnMoreUrl resid="GetStarted.LearnMoreUrl"/>
          </GetStarted>
          <!-- <FunctionFile resid="Commands.Url"/> -->
          <ExtensionPoint xsi:type="PrimaryCommandSurface">
            <OfficeTab id="TabHome">
              <Group id="CommandsGroup">
                <Label resid="CommandsGroup.Label"/>
                <Icon>
                  <bt:Image size="16" resid="Icon.16x16"/>
                  <bt:Image size="32" resid="Icon.32x32"/>
                  <bt:Image size="80" resid="Icon.80x80"/>
                </Icon>
                <Control xsi:type="Button" id="TaskpaneButton">
                  <Label resid="TaskpaneButton.Label"/>
                  <Supertip>
                    <Title resid="TaskpaneButton.Label"/>
                    <Description resid="TaskpaneButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <TaskpaneId>ButtonId1</TaskpaneId>
                    <SourceLocation resid="Taskpane.Url"/>
                  </Action>
                </Control>
              </Group>
            </OfficeTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>
    <Resources>
      <bt:Images>
        <bt:Image id="Icon.16x16" DefaultValue="https://peargrin-excel.herokuapp.com/assets/peargrin-16x16.png"/>
        <bt:Image id="Icon.32x32" DefaultValue="https://peargrin-excel.herokuapp.com/assets/peargrin-32x32.png"/>
        <bt:Image id="Icon.80x80" DefaultValue="https://peargrin-excel.herokuapp.com/assets/peargrin-64x64.png"/>
      </bt:Images>
      <bt:Urls>
        <bt:Url id="Taskpane.Url" DefaultValue="https://peargrin-excel.herokuapp.com/taskpane.html"/>
        <bt:Url id="GetStarted.LearnMoreUrl" DefaultValue="https://www.peargrin.com"/>
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="GetStarted.Title" DefaultValue="Work fast and confident with Peargrin!"/>
        <bt:String id="TaskpaneButton.Label" DefaultValue="Peargrin"/>
        <bt:String id="CommandsGroup.Label" DefaultValue="Peargrin"/>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="GetStarted.Description" DefaultValue="Work fast and confident with Peargrin!"/>
        <bt:String id="TaskpaneButton.Tooltip" DefaultValue="Click to launch Peargrin."/>
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>

```

**Comment by davidchesnut** [comment]
If you are supporting multiple hosts (PowerPoint+Excel) you need a Host section for each host. Here's an [example manifest setting up for Word, PowerPoint, and Excel](https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/auth/Office-Add-in-NodeJS-SSO/Complete/manifest/manifest_local.xml). You'll want to pattern after the `<Host xsi:type="Presentation">` section.

**Comment by mattlindsay26** [comment]
Will make that change. Thank you.

Do you have any perspective why it worked for Powerpoint Web? Or how I could better utilize `office-addin-manifest validate` to catch errors like this earlier?

**Comment by davidchesnut** [comment]
I'm not sure why it would behave differently, and there may still be an additional issue to catch that @wangyun-microsoft can check on. Although I did notice the button does not appear on the Home tab when in PowerPoint on the web, which is most likely because the PowerPoint section is missing.

The manifest validator is good at catching syntactic schema errors, but not the more semantic things like ensuring a section is there based on another setting, or that the ID's have corresponding values in the resources section. So really it's good to do basic UI testing on all the platforms like you are doing.

**Comment by mattlindsay26** [comment]
Appreciate it, I'm eager to see what @wangyun-microsoft finds

**Comment by wangyun-microsoft** [comment]
I agree with Dave. Please add <Host xsi:type="Presentation"> section under <Hosts> to your manifest. I added the section below to your manifest and it worked. 

```
<Host xsi:type="Presentation">
        <DesktopFormFactor>
          <GetStarted>
            <Title resid="GetStarted.Title"/>
            <Description resid="GetStarted.Description"/>
            <LearnMoreUrl resid="GetStarted.LearnMoreUrl"/>
          </GetStarted>
          <!-- <FunctionFile resid="Commands.Url"/> -->
          <ExtensionPoint xsi:type="PrimaryCommandSurface">
            <OfficeTab id="TabHome">
              <Group id="CommandsGroup">
                <Label resid="CommandsGroup.Label"/>
                <Icon>
                  <bt:Image size="16" resid="Icon.16x16"/>
                  <bt:Image size="32" resid="Icon.32x32"/>
                  <bt:Image size="80" resid="Icon.80x80"/>
                </Icon>
                <Control xsi:type="Button" id="TaskpaneButton">
                  <Label resid="TaskpaneButton.Label"/>
                  <Supertip>
                    <Title resid="TaskpaneButton.Label"/>
                    <Description resid="TaskpaneButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <TaskpaneId>ButtonId1</TaskpaneId>
                    <SourceLocation resid="Taskpane.Url"/>
                  </Action>
                </Control>
              </Group>
            </OfficeTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>

```

**Comment by mattlindsay26** [comment]
Thanks for looking into this. Just make sure we're on the same page: by "it worked" do you mean that the button appears on the home tab in Powerpoint? Or that the "We can't load this add-in because we couldn't connect to the catalog" no longer occurs?

**Comment by wangyun-microsoft** [comment]
@mattlindsay26 I used side load for a test. The task pane can show your log on page and "We can't load this add-in because we couldn't connect to the catalog" no longer occurs.

**Comment by mattlindsay26** [comment]
Hey team! Following up here - after updating the manifest.xml to add a 'Host' section for Powerpoint and resubmitting my Add-In to AppSource, everything works as expected.

I do not know if changing the manifest or re-submitting corrected the issue. The original error message is definitely unclear but my issue is resolved. If you encounter this issue in the future, double check your add-in and consider re-submitting your Add-In to AppSource.
