### ISSUE TITLE
Outlook Desktop (Windows): addFileAttachmentFromBase64Async throws code: 9000, message: "Los datos adjuntos no se pueden agregar porque son demasiado grandes.", name: "AttachmentSizeExceeded" in pinned add-in

### ISSUE THREAD

**Issue by guzman-rc** [OfficeDev/office-js#2987]
When I attach files larger than 15MB the error described above occurs if the add-in's pane is pinned.

**This error only occurs in Outlook desktop for Windows**, desktop Outlook for Mac OS X and Outlook Web work correctly for files larger than 15MB.

When I attach a **file larger than 25 MB the error occurs in all Outlook versions** (Windows, Mac OS X and OWA). 

Attached are screenshots of the errors and files for testing.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Microsoft® Outlook® para Microsoft 365 MSO
* Office version number: Microsoft® Outlook® para Microsoft 365 MSO (versión 2210 compilación 16.0.15726.20188) de 64 bits 
* Operating System: Windows 10 Pro 22H2
* Browser (if using Office on the web): 
 
## Steps to reproduce

1. Install the Add-In:
https://appsource.microsoft.com/es-es/product/office/WA200003633
2. Create a new email in Outlook desktop.
3. Click "Attach by MetaClean" button.
4. Click on the add-in’s pane and select sample file "Test_15MB.docx" to attach.
5. Perform the same test for the file Test_25MB.docx.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [x] Screenshots:

**Error 15 MB File:**
![Error_File_15MB_Addin](https://user-images.githubusercontent.com/96702862/203410413-24e80b06-1d26-489c-a3b5-d11596b3ec0c.png)

![Error_File_15MB](https://user-images.githubusercontent.com/96702862/203409524-8cc2c1ca-2912-48df-ad17-2d6edd91bc62.png)

**Error 25 MB file**
![Error_File_25MB](https://user-images.githubusercontent.com/96702862/203411220-080fee5f-0f31-43c8-8b37-1f120bc3cb40.png)

- [x] Test files:
[Test_15MB.docx](https://github.com/OfficeDev/office-js/files/10070611/Test_15MB.docx)
[Test_25MB.docx](https://github.com/OfficeDev/office-js/files/10070614/Test_25MB.docx)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by guzman-rc** [comment]
**Error produced for 15Mb files in Outlook desktop for Windows:**

![Error_15MB_1](https://user-images.githubusercontent.com/96702862/203621962-33faab47-880e-4f1d-a907-d9edf23b051c.PNG)

**Detail of the error from the debug console:**

![Error_15MB_2](https://user-images.githubusercontent.com/96702862/203621958-08477398-cf1c-4298-b3f7-d32d4df9ffc6.PNG)

**Detail of the error from the debug console for files larger than 20 Mb. This error occurs in all versions of Outlook (Windows, Mac and OWA):**

![Error_25MB_1](https://user-images.githubusercontent.com/96702862/203621954-6a1aa946-6fed-451d-ac9c-2b86da5d402e.PNG)

**Comment by davidchesnut** [comment]
Hi @guzman-rc, thanks for letting us know about this issue. @exextoc team, can you help out? Thanks!

**Comment by ztcdsb** [comment]
Hi @guzman-rc , as the message states, the size of the String exceed the top limit.
The limit is not limited by size of the file but the number of characters in the String, in this case 27892122. You may want to use addFileAttachmentAsync() when your attachment exceed the limit.

I will create a story to add more detail in our API as well.

**Comment by guzman-rc** [comment]
Hi ztcdsb,

**addFileAttachmentAsync(uri, attachmentName, [options], [callback])** requires a URL to send the file.

can I use the URL.createObjectURL(file) method to get the URL of the file?

I have used it this way and I get the **errorCode: 9007**, see screenshot:

![blobAsURL](https://user-images.githubusercontent.com/96702862/206145116-c596254c-baa3-4c33-914e-6a0f96322a22.PNG)

**Comment by timwan10** [comment]
addFileAttachmentAsync only takes in a string that is a URL. i.e. "https://contso.com/myfile.jpg" 

In your code what is the value that is returned from URL.createObjectURL(file) ? And why do you need it? Can you just manually set a string to the URL where the file is located?

**Comment by guzman-rc** [comment]
The value it returns is of this type (see screenshot):

blob:https://www.adarsus.com/5fe12e25-8f2c-47fb-a71d-c821999f2395

![ObjectToURL](https://user-images.githubusercontent.com/96702862/206925919-a60df174-a532-45ac-91a3-ac315d2da233.PNG)

If I put that URL --> blob:https://www.adarsus.com/5fe12e25-8f2c-47fb-a71d-c821999f2395 in a browser the file opens without any problems.

MetaClean for Outlook processes metadata from office files (Microsoft Office, OpenOffice, PDF, etc.)

If a user attaches a CSV file, MetaClean for Outlook will not process it and simply attaches the file.

The only way to attach a file is to upload it to a server and provide the URL?

The URL returned by the URL.createObjectURL(file) instruction should be valid as the file loads perfectly in the browser.

**Comment by timwan10** [comment]
Outlook Win32 will need the URL without the "blob:" in front of it. 

If your file is over the limit of the Base64 encoding function, then this is the only way to add the attachment.

**Comment by guzman-rc** [comment]
Remove **blob:** from the result of the instruction URL.createObjectURL(file) gives error.

This solution is not valid.

**Comment by ztcdsb** [comment]
@guzman-rc What error message do you get?
