### ISSUE TITLE
Still able to open another workbook while modal dialog is open on PC desktop

### ISSUE THREAD

**Issue by meggoww** [OfficeDev/office-js#2988]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2212 Build 16.0.15917.20000 (Beta Channel)
* Operating System: Windows 10 Pro
 
## Expected behavior
User should not be able to open another workbook while a modal dialog is open by right clicking on Excel on the task bar and selecting any other workbook that is not yet opened

## Current behavior
When working on a workbook and a modal dialog window is opened, we are still able to open another workbook by right-clicking on Excel in the task bar and selecting another workbook other than the one currently opened. Once other workbook is opened, the modal dialog gets hidden behind the newly opened workbook, and we are not able to interact with the new workbook because the modal dialog is still open. In order to close the dialog, we can resize the newly opened workbook so that we can view the modal dialog again and be able to close it, thus enabling us to interact with the Excel main application again.

## Steps to reproduce
1. Side-load the manifest file provided for trying out the modal dialog window on Excel
```
<?xml version="1.0" encoding="utf-8"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="TaskPaneApp">
  <Id>23455847-DA7C-4A3A-B11D-8EFCF6994C40</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Microsoft</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Modal Dialog Sample">
  </DisplayName>
  <AppDomains>
    <AppDomain>https://kepengtestapp.azurewebsites.net/</AppDomain>
    <AppDomain>https://pkkj.github.io/</AppDomain>
  </AppDomains>
  <Description DefaultValue="Modal Dialog Sample">
  </Description>
  <IconUrl DefaultValue="https://kepengtestapp.azurewebsites.net/images/handcart.png"/>
  <Capabilities>
    <Capability Name="Workbook" />
    <Capability Name="Document" />
    <Capability Name="Project" />
    <Capability Name="Presentation" />
    <Capability Name="Mailbox" />
  </Capabilities>
  <DefaultSettings>
 	<SourceLocation DefaultValue="https://kepengtestapp.azurewebsites.net/pages/modaldialog-sample-taskpane.html">
    </SourceLocation>
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>
</OfficeApp>
```
3. Click 'launchModalDialog' on the add-in
4. Navigate to the Task Bar and right click on the Excel icon
5. Click on any other suggested workbook on the menu. Workbook will open and will block the first workbook and the modal dialog from view.
6. Resize the second workbook window and close the modal dialog in order to interact with Excel main application again

# Provide additional details
- **We were able to access the modal dialog feature by enrolling in the Office Beta Channel**
 - We already have an ongoing e-mail thread about this feature with Ruoying LIang, Yawei Zhu, and Wenjun Gong.
- We do not encounter this bug when using the feature on Mac (when right-clicking on Excel in Taskbar all buttons that allow the opening of another workbook is disabled)

## Context
We need a functional modal dialog for use in PC Desktop and Mac for our officeJS add-in to be released to Production

## Useful logs
![2_new_excel_window](https://user-images.githubusercontent.com/118897701/203554878-53f72612-f4f2-4bf6-8af5-000c638d3e26.gif)

**Comment by RuizhiSunMS** [comment]
@Rick-Kirkham our colleague said it should be related with dialog api, do you know the contact?

**Comment by Rick-Kirkham** [comment]
Try Kejing Peng or Dan Tataru

**Comment by EunicePMV** [comment]
Hi @RuizhiSunMS and @Rick-Kirkham, can we reopen this issue? We’d like to request a feature for modal dialogs, since we have scenarios where it’s important for the worksheet to be non-interactive.

We're the same team who originally submitted this gh ticket, and we would like to ask if its possible to push the work done in the beta channel to production, including the fix for the bug discovered in Mac.

**Comment by Rick-Kirkham** [comment]
@EunicePMV I see that you've already created a request at M365 Ideas: [Modal Dialogs](https://techcommunity.microsoft.com/idea/microsoft365developerplatform/modal-dialogs/4462204). 

I will ask internally if there are any plans to revive this idea.

**Comment by Rick-Kirkham** [comment]
@EunicePMV I'm sorry to have to report that Microsoft does not plan to resume development on a modal dialog for Office add-ins.
