### ISSUE TITLE
Outlook Add-In installed from the Store immediately disappears

### ISSUE THREAD

**Issue by dmitry-semenov** [OfficeDev/office-js#2989]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook Office365
* Office version number: 
![image](https://user-images.githubusercontent.com/17027799/203522112-c064da5b-0be0-4c9c-9754-b837ca4c8c24.png)

* Operating System: Ventura MacOS
* Browser (if using Office on the web): Safari (latest), but on browser-based outlook, everything works fine.
 
## Expected behavior

After an extension has been installed, it should remain in place.

## Current behavior

When a user installs an extension from the store and then reopens the store, the extension is not shown as installed.

## Steps to reproduce

1. Install add-in
2. Close `Office Add-ins` window
3. Open `Office Add-ins` again, the add-in is no longer listed as installed

# Provide additional details

1. Only one user has reported this issue, other people in the same organization have not encountered it.

## Useful logs
https://user-images.githubusercontent.com/17027799/203581122-b4d3b14e-333a-45a9-be67-35818a0e1de5.mp4

**Comment by davidchesnut** [comment]
Hi @dmitry-semenov, thanks for reporting this issue. @exextoc can you help out on this issue? Thanks!

**Comment by exextoc** [comment]
@dmitry-semenov Is the add-in available in overflow menu? If so, does the add-in work on clicking on it? Can you also share the logs

**Comment by dmitry-semenov** [comment]
@exextoc which logs are you asking about?

**Comment by exextoc** [comment]
Can you share diagnostics log? Also, is the add-in visible in overflow menu and does the add-in work on click?

**Comment by exextoc** [comment]
Closing the issue due to inactivity.
