### ISSUE TITLE
Numbering gets changed on getooxml/insertooxml in Word 2016 (16.0.5366.1000)

### ISSUE THREAD

**Issue by bkonic** [OfficeDev/office-js#2991]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# getooxml and insertooxml (without changing the content) changes list numberings from small letters (a,b,c) to numbers

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:Windows 10
* Host [Excel, Word, PowerPoint, etc.]:Word 2016 MSO 16.0.5366.1000 32 Bit
* Office version number:Office Professional 2016
* Operating System: Windows 10
* Browser (if using Office on the web):N/A
 
## Expected behavior
List numbering should remain the same as before. Hence: If list numbering was small letters (a,b,c) it should remain a,b,c and NOT change to (1,2,3).

## Current behavior
Any list numbering like (a,b,c) or (i,ii,iii) will be changed to the standard (1,2,3) when running the code (see below)

## Steps to reproduce

1. Open new word document
2. Add 2 or 3 lines (like "Item 1, Item 2")
3. Select text and apply a list numbering like (a,b,c)
4. Run the code below (in an add-in /Script lab does not work in Word 2016)

  var body = context.document.body;
   var body_ooxml = body.getOoxml();
   await context.sync();
   var body_ooxml_value = body_ooxml.value;
   body.insertOoxml(body_ooxml_value, Word.InsertLocation.replace);
   await context.sync();

## Link to live example(s)
- script lab does not run in Word 2016, since it uses IE11

# Provide additional details
Runs without any issues in Word for M365.
Issue only occurs in Word 2016
Tried the following versions of Office-js:
- 1.1.83_custom (has another bug that throws an exception on insertooxml)
- 1.1.82 : NOK
- 1.1.73 : NOK (Just to check if it might be a new issue)

## Context
Our application is a solution for customers to remove sensitive information from their documents.
we need to be able to manipulate OOXML since the API has no according methods in Word API JS 1.1 . 

## Useful logs
See screenshots, especially nr. 4 shows how it looks after the code

![bug_numbering_1](https://user-images.githubusercontent.com/58952705/203784010-8fb673ab-fb50-4d41-80ba-3bc9aaa4432c.PNG)
![bug_numbering_2](https://user-images.githubusercontent.com/58952705/203784005-dced8570-cab2-4037-bf09-911a1a0ce2c8.PNG)
![bug_numbering_3](https://user-images.githubusercontent.com/58952705/203784007-5121832f-491e-4ff3-b33a-ca503c7c11d4.PNG)

![bug_numbering_4](https://user-images.githubusercontent.com/58952705/203783960-7ec97eb3-ced9-442f-8768-6bcc8515b8f6.PNG)

**Comment by bkonic** [comment]
@RuizhiSunMS : Do you have an update? Have you been able to reproduce it? The issue is quite pressing and there is no workaround. Thx!

**Comment by xuruiyao-msft** [comment]
@bkonic Hi I tried on the latest word version, the Code snippets works well. The list number format keeps the same with original small letters (a,b,c).
Seems like this issue could only be reproduced on Word 2016 but the script lab cannot be launched on this version. I will try my best to reproduce the issue. Any update I will sync with you! Thanks for your reporting.

**Comment by bkonic** [comment]
@xuruiyao-msft Yes, it works in the latest word version, but not on Word 2016 MSO (as I already established in the bug report). 
And yes: Sadly, script lab does not work in word 2016 MSO.
You need to sideload a custom add-in to be able to reproduce the issue in Word 2016.
Maybe the attached files can help...

I made some further tests and found out that the issue is with getooxml: The numbering part is omitted when executing body.getooxml.  (I will attach the extracts to this comment. ) When executing insertooxml the API seems to try to recreate the numbering which leads to an overwrite of numbering.xml.  This seems to be a bug and I do not see a workaround.

**I attached the following files in the zip:**
- W0.docx : The document with a simple numbering with lower letters
- X1_16.xml : Result of getooxml on W0.docx in Word 2016 MSO
- X1_365.xml: Result of getooxml on W0.docx in Word 365 (latest version)
-> if you compare x1_16.xml and x1_365.xml you can already see that the numbering is missing in X1_16.xml.

- X2_16.xml : Result of getooxml on W0.docx in Word 2016 MSO AFTER insertooxml was executed.
- X2_365.xml : Result of getooxml on W0.docx in Word 365 AFTER insertooxml was executed.
- W1_16.docx: Saved document after code above was executed on W0.docx in Word 2016 MSO.
- W1_365.docx: Saved document after code above was executed on W0.docx in Word 365.
- numbering_16.xml: Extract of numbering.xml from word package of W1_16.docx. 
- numbering_365.xml: Extract of numbering.xml from word package of W1_365.docx. 

I hope this helps to identify the bug and fix it. Thx!
[Bug_getooxml.zip](https://github.com/OfficeDev/office-js/files/10121348/Bug_getooxml.zip)

**Comment by bkonic** [comment]
@xuruiyao-msft  @RuizhiSunMS  : Do you have an update? The bug is still there and there is no workaround for us. Most of our customers are still using Word 2016 MSO, so I would highly appreciate if this could be fixed.

**Comment by bkonic** [comment]
@RuizhiSunMS @xuruiyao-msft  @Rick-Kirkham Can you please confirm that this is a bug? And if possible, please tell me when we can expect a fix? Right now, it is not possible to use the OOXML-Api (insertOoxml) in Word 2016 MSO without unpredictable changes to the numbering of the text.

**Comment by bkonic** [comment]
@xuruiyao-msft : is there any progress? Thx.
