### ISSUE TITLE
SmartAlerts - Import TS Modules

### ISSUE THREAD

**Issue by MorrisPenasso** [OfficeDev/office-js#2996]
Hi,

i use smart alerts for my addin but i have a problem: i would like to call/import my modules from typescript files into launchevent.js. I see on documentation that is not possible. How can i do?

Thanks

**Comment by RuizhiSunMS** [comment]
@MorrisPenasso Thanks for reporting your question. In fact, we highly recommend you to complete the basic information table(one can find it when creating new bug). That basic information would help us to triage the problem and troubleshoot.
And if it's a programming question indeed, Microsoft Q&A may be a better place for you.

**Comment by MorrisPenasso** [comment]
Ok thanks. I try to post my question at Microsoft Q&A site.
