### ISSUE TITLE
mailbox.item.body.getAsync return SCRIPT1014: Invalid character

### ISSUE THREAD

**Issue by mvpkenlin** [OfficeDev/office-js#300]
I developed outlook addin with this office js. All codes are working until today. Someone has invalid character in mail body and then the office js just fail into error. 

I run in F12 Debugger, and found the error is SCRIPT1014: Invalid character on outlook-win32-16.02.debug.js (7877, 13). 

and my code looks like this,

```
try {
    Office.context.mailbox.item.body.getAsync('text', function (result) {
        if (result.status == Office.AsyncResultStatus.Succeeded) {
            do_something...
        else {
            do_something_else...
        }
} catch (error) {
    catch_Error_handling...
}
```

But the try block is just leaving directly before the error throws to debugger. 

How can i fix it?

**Comment by dmahugh** [comment]
@exextoc can you take a look at this one?

**Comment by timwan03** [comment]
This is on Outlook Desktop and not Outlook Web Access? What's the Version Number of Outlook Desktop (something like 2016, 16.0.1111.XXXXX) (File->Office Account). 

Can you provide a copy of the e-mail that is producing this error?

**Comment by exextoc** [comment]
This is on Outlook Desktop and not Outlook Web Access? What's the Version Number of Outlook Desktop (something like 2016, 16.0.1111.XXXXX) (File->Office Account).

Can you provide a copy of the e-mail that is producing this error?

**Comment by mvpkenlin** [comment]
@exextoc It is outlook Desktop, Microsoft Office 365 ProPlus, Version 16.0.11001.20097, 32-bit. 

May I have your email so that I could forward you the problem email? But actually, you could test with those chars, the original email contains these chars and body.getAsync throw error. By removing them from email and reply to myself again, body.getAsync fired without any problem. 

name of ʥ׿̗˼/span>1993˾.
, DENMARK³ ݿ˼/span>DK-3150ŵ‹󽖼/span>119H
mark to ʥ׿̗˹˾, to avoid 

I think these char was corrupted by some email client but it keep in the loop of the email so I cannot just ask the addin user to search and remove them manually before running the addin.

**Comment by exextoc** [comment]
Copying and pasting the characters doesn't seem to reproduce the issue. (likely copying/pasting the characters into Outlook "Fixes" the issue). Is there anyway you can upload the .msg file with the bad characters? Or reproduce the issue in a smaller email without any sensitive information that we could take a look at?

**Comment by mvpkenlin** [comment]
@exextoc Sure, here it is. I tested this email is generating the script error.

[SampleEmail.zip](https://github.com/OfficeDev/office-js/files/2618065/SampleEmail.zip)

**Comment by exextoc** [comment]
I've repro'ed the problem, and put the bug on a backlog. There is no timetable for when it will be addressed. On your side, I don't think you can fix the code. I did notice that if you get the text of the body as HTML, then it comes back correctly, but I'm not sure if that solves your problem.

**Comment by mvpkenlin** [comment]
@exextoc getting as HTML body cannot fit into my system. We are indexing the mail body text. I am sorry. Please let me know by updating this issue after fixed by your team. Thanks a lot.

**Comment by mvpkenlin** [comment]
@exextoc Is there a way like "try catch" and so it won't stop my js executation?

**Comment by mvpkenlin** [comment]
@exextoc by the way, I also have another problem found when executing outlook Add-in, but I think that it is more on the Outlook team, but noone from their team read/found it. Am I posted to incorrect website?

https://stackoverflow.com/questions/52960506/how-to-disable-pinned-taskpane-when-clicked-mailitem-from-archive-folder

**Comment by timwan03** [comment]
Do you have more information on how this e-mail got into this state? Is this a common problem? Or is it just one e-mail thread that is causing this issue? (i.e. is there a product out there that is causing emails with invalid characters in them, or if you have some way to reproduce the creation of the email)

**Comment by exextoc** [comment]
Do you have more information on how this e-mail got into this state? Is this a common problem? Or is it just one e-mail thread that is causing this issue? (i.e. is there a product out there that is causing emails with invalid characters in them, or if you have some way to reproduce the creation of the email)
