### ISSUE TITLE
Word: Word.Range InsertBookmark gives an error on the web if bookmark name starts with an underscore or includes uppercase character

### ISSUE THREAD

**Issue by lynneosmith** [OfficeDev/office-js#3003]
Word Javascript API 1.4 says:
insertBookmark(name)
Inserts a bookmark on the range. If a bookmark of the same name exists somewhere, it is deleted first.
Parameters
name
string
Required. The bookmark name, which is case-insensitive. If the name starts with an underscore character, the bookmark is an hidden one.

If I insert a bookmark on Word web that starts with an underscore or contains an uppercase character, we get an InvalidArgument exception:  "The argument you provided is not valid. Check the OfficeExtension.Error.debugInfo for more information."

## Your Environment

* Platform: Office on the web
* Host: Word
* Office version number: API Word 1.4
* Operating System: windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
I expect the hidden bookmark to be inserted. This works fine on the desktop version of Word and on the Web it will only work if I do not use a hidden bookmark name. I also expect uppercase characters to work, though i can work around that if needed, but cannot work around hidden bookmarks failing. I get an exception currently if there is an underscore at the beginning or if there is an uppercase character present.

## Current behavior
If I insert content on the web and then insert a bookmark for the range of content I inserted, I get an exception that says that I used an invalid parameter to the word.Range  insertBookmark API (when I preface the string with an _). If I do not use a string that starts with an underscore and is entirely lowercase, it works. But... I need to be able to use hidden bookmarks so that our users don't see the bookmarks we have added.  I get an exception currently if there is an underscore at the beginning or if there is an uppercase character present.

## Steps to reproduce
I can reproduce this in ScriptLab.
Run the following content in ScriptLab:

async function insertTable() {
   await Word.run(async (context) => {
     const curRange = context.document.getSelection();
     const table = curRange.insertTable(4, 3, Word.InsertLocation.after);
     table.load("items");
     await context.sync();

    const mycell = table.getCell(1, 1);
    mycell.value = "Hello";
    table.select();

    const tableRange = table.getRange();
    tableRange.insertBookmark("_firstbookmark");
   // tableRange.insertBookmark("FIRSTbookmark); ---> fails
  // tableRange.insertBookmark("_firstbookmark); ---> fails

   // tableRange.insertBookmark("firstbookmark); ---> succeeds

    
  });

If you run the above content in ScriptLab for Word on the Web, you will see the following:

n {name: "RichApi.Error", code: "InvalidArgument", traceMessages: Array[0], innerError: null, debugInfo: Object…}
name: "RichApi.Error"
code: "InvalidArgument"
traceMessages: Array[0]
innerError: null
debugInfo: Object
code: "InvalidArgument"
message: "The argument you provided is not valid. Check the OfficeExtension.Error.debugInfo for more information."
toString: function toString()
errorLocation: "Range.insertBookmark"
statement: "range.insertBookmark(...);"
surroundingStatements: Array[9]
0: "..."
1: "// Instantiate {cell}"
2: "cell.value = ...;"
3: "v.select();"
4: "var range = v.getRange();"
5: "// Instantiate {range}"
6: "// >>>>>"
7: "range.insertBookmark(...);"
8: "// <<<<<"
fullStatements: Array[1]
httpStatusCode: 400
data: undefined

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context
We are trying to add support for Word to our product suite. We use a task pane to insert, update and remove content to the Word document. We use bookmarks to track our content and we are using hidden bookmarks successfully on the desktop product but the api is not working to insert a hidden bookmark in word on the web even though the documentation says this should work.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuizhiSunMS** [comment]
@lynneosmith 
Thanks for reporting. Our colleagues confirm this issue as a bug and has put it into our backlog list with an ado id #7231386.
Although we can't give out a timeline of fixing, we will update here if any achievement is got.

**Comment by jingxuan0109** [comment]
@lynneosmith the fix of this issue has been deployed to production. Could you please try your scenario? Thank you for letting us know about this issue.

**Comment by lynneosmith** [comment]
@jingxuan0109 I have verified that this fix resolves the problem for us. Thank you!

**Comment by jingxuan0109** [comment]
Thank you @lynneosmith for double confirm. I will close this issue. @penglongzhaochina @RuizhiSunMS FYI.
