### ISSUE TITLE
Problem trying to debug the taskpane

### ISSUE THREAD

**Issue by victore** [OfficeDev/office-js#3005]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [Y ] I am running the latest version of Node and the tools
- [Y ] I checked the documentation and found no answer
- [ Y] I checked to make sure that this issue has not already been filed

# Expected behavior

Please describe the behavior you were expecting

I'm trying to see de "inspect element" on the taskpane so I can see the console in OSX using office 365 but I can't. I tried the steps described in https://learn.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac

Any idea? 

NPM 8.19.3

# Current behavior
When Right-click the add-in the Inspect Element option doesn't appears.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Initalize the add-in by running the commands: npm run dev-server & npm start.
2. executed the command: defaults write com.microsoft.Excel OfficeWebAddinDeveloperExtras -bool true
3. 

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOS Ventura (13.0)
* Node version: v18.11.0
* Office version: 16.67 (22111300) with an Office 365 subscription
* Tool version:

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by davidchesnut** [comment]
Hi @victore,

Can you try clearing the Office cache **after** running the terminal command to enable the developer extras?
1. Stop the node server.
2. Close Excel.
3. Clear the Office cache.
4. Restart the node server.

Thanks!
David

**Comment by RuizhiSunMS** [comment]
@victore I've reached this issue out to the owner team but looks they don't have access to this channel. This is the reply they gave 'we need to know if they installed Office from office.com, or if they are using the Mac App Store to install/update Office. We disable the debug feature when installed from the Mac App Store, regardless of version.'
Please check it.

**Comment by victore** [comment]
Yes @davidchesnut I've tried those steps.

Thank you @RuizhiSunMS! That was the problem. I just installed Excel from office.com, and now I can debug the requests and know what its going on.

**Comment by Rick-Kirkham** [comment]
I have updated the document.  https://learn.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac
