### ISSUE TITLE
[Outlook][OWA] Cannot read properties of null (reading '_appName')

### ISSUE THREAD

**Issue by milankonir** [OfficeDev/office-js#3007]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: macOS Ventura 13.0
* Browser (if using Office on the web): Google Chrome 108.0.5359.71 (Official Build) (x86_64)
 
## Expected behavior

Dialog opened from function should not crash

## Current behavior

Calling `Office.onReady()` inside a dialog opened from function with the `displayInIframe: false` option will fail with following error:

```
outlook-web-16.01.js:20 Uncaught TypeError: Cannot read properties of null (reading '_appName')
    at d (outlook-web-16.01.js:20:124851)
    at OSF.InitializationHelper.getAppContext (outlook-web-16.01.js:20:126690)
    at D (office.js:76:26049)
    at s (office.js:76:27917)
    at c (office.js:76:4168)
```

![image](https://user-images.githubusercontent.com/72383088/204834412-72aa0a40-0809-4df2-bdd0-b2d2c6106586.png)

## Steps to reproduce

1. Install this sample add-in https://github.com/milankonir/command-dialog-addin
2. Invoke the Command dialog Add-in (the only available option)
3. Look into dev tools console of the opened dialog and observe the crash

## Link to live example(s)

1. The sample add-in with repro https://github.com/milankonir/command-dialog-addin
2. Repro video: https://share.getcloudapp.com/llugZKlG

# Provide additional details

This has been reported twice in the past in #2218 and #2587, hopefully this repro will be sufficient for you

## Context

We need to be able to open dialogs from function files and we need to be able to do so with the `displayInIframe: false` option to be able to redirect to 3rd party origins.

## Useful logs

- [x] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by davidchesnut** [comment]
Hi @milankonir, thanks for letting us know about this issue. @exextoc can you please help resolve this issue? Thanks!

**Comment by exextoc** [comment]
Thanks for reporting. This issue has been put in our backlog but unfortunately we donot have any timelines to share.
Internal tracking ID: 182284

**Comment by johnkreagan** [comment]
+1 we also just hit this issue and are trying to find a workaround.

**Comment by exextoc** [comment]
Hey @milankonir, @johnkreagan 

We are not able to reproduce the issue on our end. 
Is it still a repro?

**Comment by milankonir** [comment]
@exextoc I can no longer repro with the sample add-in nor our production one, but we are still seeing some errors coming in via our telemetry - will continue monitoring it.

**Comment by johnkreagan** [comment]
@exextoc - thanks for the response. We are also no longer able to reproduce the issue and can now open non iframe dialogs from a ribbon function. We will follow up if we have more info.

**Comment by exextoc** [comment]
@milankonir Can you please create a separate github bug for the error coming via telemetry ??

**Comment by milankonir** [comment]
@exextoc Feel free to close this one as the telemetry is few and far between. I'll open a new ticket if the situation changes or we get a better understanding on what is failing.

**Comment by markon1** [comment]
we're having the same issue for various clients, our `onMessageSendHandler` doesn't trigger because of this and breaks our whole app...
