### ISSUE TITLE
Shared runtime for Outlook addins

### ISSUE THREAD

**Issue by Suntechnick** [OfficeDev/office-js#3008]
We are developing the Outlook based taskpane addin and due to its nature it would be more convenient (and makes more sense) if we had a possibility to toggle taskpane opening/closing via shared runtime API.

Unfortunately, as of now, there is no shared runtime support for Outlook based addins. Are there any plans for providing it for Outlook?

Thanks.

**Comment by davidchesnut** [comment]
Hi @Suntechnick, thanks for this suggestion. We track all feature suggestions at https://aka.ms/m365dev-suggestions. So you might create a request there. In the meantime, @exextoc is there anything to add to this suggestion? Thanks!

**Comment by exextoc** [comment]
Yes, feature request can be submitted at https://aka.ms/m365dev-suggestions

**Comment by Oleg-O** [comment]
Nothing more to add. I see this was added as [a Tech Community idea](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/shared-runtime-for-outlook-addins/idi-p/3688614) already, great!
