### ISSUE TITLE
Notifications of type InsightMessage won't display actions on some platforms

### ISSUE THREAD

**Issue by fedeisas** [OfficeDev/office-js#3009]
The following snippet produces two different notifications on different platforms even though they both support [API set: Mailbox 1.10](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets).

```js
Office.context.mailbox.item.notificationMessages.replaceAsync(
  'my_notification',
  {
    type: Office.MailboxEnums.ItemNotificationMessageType.InsightMessage,
    message: "Please create your signature",
    icon: "Icon.80x80",
    actions: [
      {
        actionText: "Create signature",
        actionType: Office.MailboxEnums.ActionType.ShowTaskPane,
        commandId: "msgComposeOpenTaskPane",
        contextData: null,
      },
    ],
  }
);
```

## Your Environment
* Platform: PC Desktop
* Host: Outlook
* Office version number: Microsoft 365 MSO (Version 2210 Build 16.0.15726.20188) 64-bit
* Operating System: Windows 11 Version 22H2
 
## Expected behavior
Notification should display the action.

<img width="503" alt="image" src="https://user-images.githubusercontent.com/251675/204916707-991f2323-258b-4bb8-ac87-83f44e70f230.png">

## Current behavior
Notification gets displayed without the action.

<img width="486" alt="image" src="https://user-images.githubusercontent.com/251675/204916806-9b2b8f33-cac4-45cc-b1e1-27a5c2d82225.png">

**Comment by davidchesnut** [comment]
Hi @fedeisas, thanks for letting us know about this issue. @exextoc can you please help resolve this issue? Thanks!

**Comment by timwan10** [comment]
There appears to be in bug in one of the platforms (I'm not sure which one), but can investigate further. 

Instead of contextData: null 

either remove contextData Entirely or do 

`"contextData" : "{}"`

The null contextData is causing Win32 to reject the entire actions object. Either both platforms should reject, or both should accept, (I will have to take it up with the product team)

**Comment by fedeisas** [comment]
@davidchesnut @timwan10 thanks! I guess I just copied [this example](https://learn.microsoft.com/en-us/javascript/api/outlook/office.notificationmessageaction?view=outlook-js-preview) and replaced the `JSON.stringify` with `null`.

**Comment by tstrader** [comment]
Having a similar issue on Outlook Mac and Outlook Web.  I have tried null, {}, "{}" for the value of contextData as well as omitting it entirely and none of them seem to produce an action button.  On Outlook Mac it shows the notification, but without the action button.  On Outlook Web, it doesn't show the notification at all.

**Comment by timwan10** [comment]
@tstrader  Will forward the issue to Mac/Web teams. Please provide a snippet of your code and test it in Script Lab.

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog(Tracking Id: 3234605). We unfortunately have no timelines to share at this point.

**Comment by devnomanaslam** [comment]
<img width="879" height="216" alt="Image" src="https://github.com/user-attachments/assets/daa6e8f4-fba9-4db8-9cb2-ea9304170820" />

Commands.js file's code:

`/*
 * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
 * See LICENSE in the project root for license information.
 */

/* global Office */

Office.onReady((info) => {
  if (Office.context.requirements.isSetSupported("Mailbox", "1.10")) {
    console.log("Mailbox 1.10 or higher is supported");
  } else {
    console.warn("Mailbox 1.10 or higher is NOT supported");
  } // If needed, Office.js is ready to be called.
});

/**
 * Shows a notification when the add-in command is executed.
 * @param event {Office.AddinCommands.Event}
 */
function action(event) {
  const id = "notificationId"; // Unique identifier for the notification
  const itemId = Office.context.mailbox.item.itemId;
  const details = {
    type: Office.MailboxEnums.ItemNotificationMessageType.InsightMessage,
    message: "This is an insight notification.",
    icon: "Icon.80x80",
    actions: [
      {
        actionText: "Open Task Pane",
        actionType: Office.MailboxEnums.ActionType.ShowTaskPane,
        commandId: "ActionButton", // Using the command ID from your manifest
      },
    ],
  };

  Office.context.mailbox.item.notificationMessages.addAsync(id, details, handleResult);

  // Be sure to indicate when the add-in command function is complete.
  event.completed();
}

/**
 * Handles the result of the notification message operation
 * @param {Office.AsyncResult} result - The result of the async operation
 */
function handleResult(result) {
  if (result.status === Office.AsyncResultStatus.Failed) {
    console.error("Failed to add notification message:", result.error.message);
  } else {
    console.log("Notification message added successfully");
  }
}

// Register the function with Office.
Office.actions.associate("action", action);
`
