### ISSUE TITLE
Non-Prod is not loading Excel Online Add-in ToolPak for us, even though the handshake is successful (yesterday - today Prod too!)

### ISSUE THREAD

**Issue by awhittlecengage** [OfficeDev/office-js#3012]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

host_install_addins is no longer adding the ToolPak in Online Excel.
Yesterday is was only MSFT non-prod that had the issue, MSFT prod was working fine.
Today both MSFT prod and non-prod no longer load ToolPak in Online Excel.
**Possibly a credentials issue.**

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Build: 16.0.15928.42302
* Operating System: Mac OS
* Browser (if using Office on the web): Chrome, FireFox, Safari
 
## Expected behavior
When adding the sc paramater to the url listed below, we previously saw ToolPak load as an add on to Online Excel.

## Current behavior
We still add the same value for the sc parameter, but earlier this week ToolPak was no longer seen as an add on to Online Excel.  At that time this was only for our lower environments (Our Prod was fine.)
However, today our Prod environment also no longer works - it did yesterday.

## Steps to reproduce
1.  Click on link below
2. Top Right, click the 3 dots to open menu
3. ToolPak option is no longer seen (below Editing/Clear)

## Link to live example(s)
Going to prod, we see the toolpak loads (- well it worked yesterday BUT NOW THIS FAILS TO LOAD TOOLPAK TOO):
https://excel.officeapps.live.com/x/_layouts/xlviewerinternal.aspx?edit=1&ui=en-us&rs=en-us&WOPISrc=https%3A%2F%2Fwopi.cengage.com%2Fservices%2Fv1%2Fspreadsheet%2Fwopi%2Ffiles%2F1aj7k2ptv%21gp8e%211gj4l9o5n%21kiug%21t&access_token=0000lb3uqwwz-00002u4-0&sftc=1&sc=https://cxp.cengage.com&host_install_addins=%5B%7B%22addinId%22%3A%22wa104379190%22%2C%22type%22%3A%22TaskPaneApp%22%7D%5D

But when we go to non-prod, we **do not** see the toolpak load: 
https://ffc-excel.officeapps.live.com/x/_layouts/xlviewerinternal.aspx?edit=1&ui=en-us&rs=en-us&WOPISrc=https%3A%2F%2Fwopi-test.cengage.com%2Fservices%2Fv1%2Fspreadsheet%2Fwopi%2Ffiles%2F1aj7k2ptv%21gp8e%211gj4lko95%219koj%21t&access_token=0000lb3uyn15-00002u4-0&sftc=1&sc=https://dev-trunk-cxp.cengage.info&host_install_addins=%5B%7B%22addinId%22%3A%22wa104379190%22%2C%22type%22%3A%22TaskPaneApp%22%7D%5D

It is the exact same call just to different MSFT environments and different access tokens.

# Provide additional details
The beginning of the week it only affected calls to https://ffc-excel.officeapps.live.com/
Today it also affected calls to https://excel.officeapps.live.com/
Was there a release to Prod today or last night, that was put on non-prod beginning of this week or end of last week that could have caused this?
Or is there an issue with our token or our domain that we are sending in the **sc** parameter?
**It looks to us there is an issue with our credentials.**

## Context
It affects our users as it is now in Production.  We are an education company and students can no longer do their homework.

## Useful logs

- [ ] Console errors
GET https://excel.officeapps.live.com/x/_layouts/AddinServiceHandler.ashx?actio…lnbr%217ohr%21t&access_token=0000lb5na7h8%2D00002u4%2D0&access_token_ttl=0 403 MicrosoftAjaxDS.js:1

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by atuszyn** [comment]
Today I did notice that in production, I am getting a 403 on this call:  

curl ‘https://excel.officeapps.live.com/x/_layouts/AddinServiceHandler.ashx?action=laststoreupdate&app=1&lc=en-US&WOPIsrc=https%3A%2F%2Fwopi%2Ecengage%2Ecom%2Fservices%2Fv1%2Fspreadsheet%2Fwopi%2Ffiles%2F1aj7k2ptv%21gp8e%211gj78aqde%2199md%21t&access_token=0000lb5al21r%2D00002u4%2D0&access_token_ttl=0’ \
  -H ‘authority: [excel.officeapps.live.com](http://excel.officeapps.live.com/)’ \
  -H ‘accept: */*’ \
  -H ‘accept-language: en-US,en;q=0.9,es;q=0.8,fr;q=0.7’ \
  -H ‘cookie: PageLoadSkeletonState=%7B%22IsEnabled%22%3Atrue%2C%22Options%22%3A3136%7D; ExcelIsPreviousSessionSimplifiedRibbonOn=false; ExcelIsSimplifiedRibbonOn=false; timeZoneId=America%2FDetroit; MUID=0489BC58CD9864840D24ADB5C998602E; PUS10-Excel-ARRAffinity=899a14c4f8cb497b6bc9baae47b8932f83e0b237b2d1a7e783816ccd9fb5173c; PUS1-Excel-ARRAffinity=418120474fa549db0656cfb869955f3c869ac9a11a0db371040781bdf0c7f942; PUS1-ARRAffinity=7e94336d24128ac70bd85b534761bcf2b22ab8420470f8cf84085dd154ba9a6b’ \
  -H ‘haep: 1’ \
  -H ‘referer: https://excel.officeapps.live.com/x/_layouts/xlviewerinternal.aspx?edit=1&ui=en-us&rs=en-us&WOPISrc=https%3A%2F%2Fwopi.cengage.com%2Fservices%2Fv1%2Fspreadsheet%2Fwopi%2Ffiles%2F1aj7k2ptv%21gp8e%211gj78aqde%2199md%21t&access_token=0000lb5al21r-00002u4-0&sftc=1&sc=https://c-cxp.cengage.com&host_install_addins=%5B%7B%22addinId%22%3A%22wa104379190%22%2C%22type%22%3A%22TaskPaneApp%22%7D%5D’ \
  -H ‘sec-ch-ua: “Google Chrome”;v=“107", “Chromium”;v=“107", “Not=A?Brand”;v=“24"’ \
  -H ‘sec-ch-ua-mobile: ?0’ \
  -H ‘sec-ch-ua-platform: “macOS”’ \
  -H ‘sec-fetch-dest: empty’ \
  -H ‘sec-fetch-mode: cors’ \
  -H ‘sec-fetch-site: same-origin’ \
  -H ‘user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36’ \
  -H ‘x-key: F3A3BU4yc9F8slqWtXFTVxeoP5+DqAip5bKczDE/Nvk=,638055090250971862’ \
  -H ‘x-officeversion: 16.0.15928.42302’ \
  -H ‘x-requested-with: XMLHttpRequest’ \
  -H ‘x-usersessionid: cfa59d51-17d6-411d-be22-6bf35c45de9a’ \
  -H ‘x-usertype: WOPI’ \
  -H ‘x-waccluster: PUS10’ \
  -H ‘x-xhr: 1’ \
  --compressed

Not sure if we were getting a similar failure in the non-production environments yesterday or not.

**Comment by awhittlecengage** [comment]
It is the same error in our non-production environments.
GET https://ffc-excel.officeapps.live.com/x/_layouts/AddinServiceHandler.ashx?action=laststoreupdate&app=1&lc=en-US&WOPIsrc=https%3A%2F%2Fwopi%2Dtest%2Ecengage%2Ecom%2Fservices%2Fv1%2Fspreadsheet%2Fwopi%2Ffiles%2F1aj7k2ptv%21gp8e%211gj7tdt2v%21fp9e%21t&access_token=0000lb5nr72j%2D00002u4%2D0&access_token_ttl=0 403 MicrosoftAjaxDS.js:1

**Comment by RuizhiSunMS** [comment]
Not Excel API related. Has reached out to guys who own the area.

**Comment by RuizhiSunMS** [comment]
re-assign myself temporarily to wait for heidi and justin.

**Comment by atuszyn** [comment]
Re: Additional details requested above:

The beginning of the week it only affected calls to https://ffc-excel.officeapps.live.com/
Today it also affected calls to https://excel.officeapps.live.com/
Was there a release to Prod today or last night, that was put on non-prod beginning of this week or end of last week that could have caused this? **NO prod release.  Nor prod deploys were reverted to the production version and still had the issues**
Or is there an issue with our token or our domain that we are sending in the sc parameter? **sc parameter value was not changed**
It looks to us there is an issue with our credentials.

**Comment by Wenjun-Gong** [comment]
Our ENG had a fix for this problem. Per Alex, this issue has been mitigated. Please re-open if the problem shows up again.
