### ISSUE TITLE
Office.Dialog.close does not close the dialog window on Outlook for Mac

### ISSUE THREAD

**Issue by t4rzsan** [OfficeDev/office-js#3015]
Our Outlook add-in opens a dialog with the `Office.context.ui.displayDialogAsync` function.  But when we try to close the dialog with [`Office.Dialog.close`](https://learn.microsoft.com/en-us/javascript/api/office/office.dialog?view=common-js-preview#office-office-dialog-close-member(1)), the dialog is not closed.  This only happens on Outlook for Mac.  It does work as expected on Outlook for Windows and on Outlook for web.

It used to work for Mac as well.  I am not sure when it stopped working.

# Provide required information needed to triage your issue

## Your Environment
* Platform: Mac 
* Host: Outlook Microsoft 365
* Office version number: Outlook 16.68 (22120101)
* Operating System: Ventura 13.1
 
## Expected behavior
[`Office.Dialog.close`](https://learn.microsoft.com/en-us/javascript/api/office/office.dialog?view=common-js-preview#office-office-dialog-close-member(1)) is supposed to close the dialog.

## Steps to reproduce
This simple and not very useful example works as expected, i.e. the popped up dialog is closed immediately:
```javascript
Office.context.ui.displayDialogAsync(fullUrl,
    { height: 40, width: 40, displayInIframe: true }, function (asyncResult) {
        asyncResult.value.close();
    });
```
However, the code sample below only works in Outlook for Windows and in OWA.  It does not work in Outlook for Mac, i.e. the dialog remains open after calling `globalDialog.close`.  The function `processMessageTest` is called, but `globalDialog.close()` has no effect:
```javascript
let globalDialog;

function processMessageTest(args) {
    // processMessageTest is called on Mac, but globalDialog.close() does nothing.
    globalDialog.close();
}

function showDialog() {
    let url = 'https://...';
    Office.context.ui.displayDialogAsync(url,
        { height: 40, width: 40, displayInIframe: true }, function (asyncResult) {
            globalDialog = asyncResult.value;
            globalDialog.addEventHandler(Office.EventType.DialogMessageReceived, processMessageTest);
        });
}
```

**Comment by pkkj** [comment]
Hi t4rzsan,

I have done a quick test in my local machine and I verify that the code is working in both Win32 and Mac. I could not find any problem.

I also create a quick demo add-in with your code and you could try to play with it in your local machine:

Please read the source code of the manifest and add-in's main [page](https://kepengtestapp.azurewebsites.net/pages/dialog-publictest-taskpane.html) before you side load this sample [Manifest](https://kepengtestapp.azurewebsites.net/manifest/AzureOutlookPublicTest.xml)

Thanks,
-Kejing

**Comment by t4rzsan** [comment]
Hi Kejing,

Thank you. I will take a look as soon as I am back on my Mac. 

Thanks,
Jakob

**Comment by t4rzsan** [comment]
Hello Kejing,

I tried your example and it works perfectly.  We have come to the conclusion that there is something else in the JavaScript of our add-in that is acting up.  The error is on our end.

I am closing this ticket.  Thanks for your help.

-Jakob
