### ISSUE TITLE
How to proactively determine the JS runtime in office add-in

### ISSUE THREAD

**Issue by prasadhpshenoy** [OfficeDev/office-js#3016]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Summary

We have a client who has an office 365 E5 license and Microsoft OEM license. For some reason he is not able to execute Custom Functions. I know that custom functions need an Excel runtime environment (Browser) to be Edge for supporting all the latest features, but when we checked his machine it was showing Excel runtime as IE 11. Am a little surprised with this as he has webview installed on his machine. Based on my understanding, if Webview is installed it should default the runtime to Edge. (Please correct me if my understanding isn't right on this). 
Below is the exact version of excel the client is using : "Version 2210 Build 16.0.15726.20188".
Apart from this, based on the documentation I also understand that Licensing plays a vital role to decide whether the runtime has be Edge or IE. 
I was wondering if there a programmatic way to determine why is excel choosing IE over Edge?? This would help us to let the user know why certain things are not working on their machine and how can they make it work. It would help us a lot with the proactive approach.

**Comment by prasadhpshenoy** [comment]
[This](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11#determine-at-runtime-if-the-add-in-is-running-in-internet-explorer) article helps to a certain extent.
Is there a way to determine the exact reason for add-in to run on IE 11 (It could be license or webview or anything else).. If we can do that programmatically we can display it to the end user and suggest corrective actions for the same.

**Comment by prasadhpshenoy** [comment]
Do we have any update on this?

**Comment by prasadhpshenoy** [comment]
Appreciate an update on this.

**Comment by YasharHeydari** [comment]
I have a similar situation, where while Excel version is > 2021  and WebView2 is installed on Windows (and license doesn't matter), IE 11 is selected as the embedded engine for running Office add-in instead of Edge (chromium-based). I'm not sure how I can change this or make sure that my add-in clients will always end-up with similar configuration when specified combination provided in [this chart](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) exists?
