### ISSUE TITLE
can not start with Office.js in PowerPoint 2016 add-in

### ISSUE THREAD

**Issue by stevenChen2022** [OfficeDev/office-js#3017]
API version: PowerPointApi 1.1
Office version: 16.0.11001.20097 32bit

I test my add-in. it works in office 2021 which uses Edge as the browser. However, it fails when I switch to office 2016(16.0.11001.20097 32bit) which takes IE11.

the code is straightforward --- adding a new slide to the presentation.
![image](https://user-images.githubusercontent.com/101428928/205763493-fd353e3d-ca33-4c50-812e-51cc4165cf38.png)

and the console looks:
![image](https://user-images.githubusercontent.com/101428928/205763892-d8b0d92c-5450-41cc-8658-7af1ad1fbd0a.png)

![image](https://user-images.githubusercontent.com/101428928/205763844-c78bbe42-d101-46af-b5fd-e9958f66b943.png)

**Comment by Rick-Kirkham** [comment]
The [SlideCollection.add](https://learn.microsoft.com/javascript/api/powerpoint/powerpoint.slidecollection?view=powerpoint-js-preview#powerpoint-powerpoint-slidecollection-add-member(1)) method requires PowerPoint Requirement Set 1.3, which is not supported on the Office 2016 build you are using. See [PowerPoint Requirement Sets](https://learn.microsoft.com/javascript/api/requirement-sets/powerpoint/powerpoint-api-requirement-sets?view=powerpoint-js-preview).

I'll close this issue, but you can still add comments and we will see them.
