### ISSUE TITLE
insertInlinePictureFromBase64 doesn't support svg format.

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#3018]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___PC desktop___
* Host [Excel, Word, PowerPoint, etc.]: ___Word___
* Office version number: __Microsoft® Word 2019MSO (版本 2202 Build 16.0.14931.20806) 64 位____
* Operating System: __Windows____
* Browser (if using Office on the web): __Edge____
 
## Expected behavior

Support svg format

## Current behavior

If insert a svg image base64, broken image showed
![1](https://user-images.githubusercontent.com/3182964/205779926-d00651db-8602-4268-9271-267a3cf55306.png)

**Comment by RuizhiSunMS** [comment]
@hengchengfei Thanks for the reporting.
I want to make sure that you can't insert .svg file into neither word desktop nor word online, right?

**Comment by jipyua** [comment]
thanks for reporting this, we will log an item in our backlog to track this.

**Comment by hengchengfei** [comment]
？

**Comment by jipyua** [comment]
Would you please provide me your svg in a zip file? I tried some svg and they are working fine on 2019.

**Comment by hengchengfei** [comment]
@jipyua 
[svg-base64.txt](https://github.com/OfficeDev/office-js/files/10295804/svg-base64.txt)
![chart](https://user-images.githubusercontent.com/3182964/209356770-fbb55376-4475-4d20-9241-2bd7ccf45d10.svg)


```js
const base64 = "PD94bWwgdmVyc2lvbj0iMS4wIiBzdGFuZGFsb25lPSJubyI/PjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+PHN2ZyB0PSIxNjcxODA3NDI0MjEzIiBjbGFzcz0iaWNvbiIgdmlld0JveD0iMCAwIDEwMjQgMTAyNCIgdmVyc2lvbj0iMS4xIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHAtaWQ9IjI3MTAiIHdpZHRoPSI1MDAiIGhlaWdodD0iNTAwIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayI+PHBhdGggZD0iTTY0IDQ0OGgyNTZ2NTEySDY0VjQ0OHogbTY0MC0xOTJoMjU2djcwNEg3MDRWMjU2ek0zODQgNjRoMjU2djg5NkgzODRWNjR6IiBwLWlkPSIyNzExIiBmaWxsPSIjZDgxZTA2Ij48L3BhdGg+PC9zdmc+";
  Word.run(async (context) => {
    const range = context.document.getSelection();
    range.insertInlinePictureFromBase64(base64, "Replace");
    await context.sync();
  }).catch((e) => {
    $.myAlert(e);
  });
```

**Comment by hengchengfei** [comment]
?

**Comment by hengchengfei** [comment]
?

**Comment by hengchengfei** [comment]
@jipyua
