### ISSUE TITLE
context.sync error RichApi.Error: Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again.

### ISSUE THREAD

**Issue by Denwah** [OfficeDev/office-js#3020]
# Provide required information needed to triage your issue
Addin runs when no workbook cell is in edit mode, however the following code throws the above exception:
`var cell:Excel.Range = context.workbook.getActiveCell();`
`const selectedRange: Excel.Range = context.workbook.getSelectedRange();`
`selectedRange.load();`
`await context.sync();`

NOTE: It seems any action on the workbook through the API causes this exception

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Web Client
* Operating System: Windows 10 Enterprise
* Browser (if using Office on the web): Edge Version 107.0.1418.62 (Official build) (64-bit)
 
## Expected behavior
Expect to have a range object returned representing the selected range. 

## Current behavior
Throws the following exception:
RichApi.Error: Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again.

## Steps to reproduce
1. Create a context object
2. set a variable to the selected range
3. load the variable
4. sync the context

## Context
This is happening while trying to debug the office addin through the web browser. Does not appear to have affected the Excel Desktop version. This is stopping me being able to modify my addin as I cannot use the API while in the web client and debugging

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuizhiSunMS** [comment]
@Denwah Thanks for reporting,
Looks similar with #3021, have replied in that issue, please update there to collect our information.

**Comment by RuizhiSunMS** [comment]
@Denwah Looks that issue doesn't bother you anymore in #3021 . We'll close this issue and feel free to reopen it whenever you find it again.
Thanks
