### ISSUE TITLE
Excel Add-in-  Error: InvalidOperationInCellEditMode: Excel is in cell-editing mode.

### ISSUE THREAD

**Issue by SangeethaPoyyaparambil** [OfficeDev/office-js#3021]
Error: InvalidOperationInCellEditMode: Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again.

It's breaking all excel add-in apps in production.
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Office 365
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome, Edge, All browsers
 
## Expected behavior
On the excel add-in function call, it should read excel sheet data and return it

## Current behavior
Error: InvalidOperationInCellEditMode: Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again.

On calling 
   var sheet = context.workbook.worksheets.getItem(sheetname);
   var selection = sheet.getUsedRange();
selection.load("rowCount, columnCount, values");
   context.sync()

This issue is happening in all our Excel add-in applications even if we don't edit at all. All applications were working till last week. We noticed this issue yesterday. 

## Steps to reproduce
if you have excel add-in call for
Excel.run(function (context) {
                var sheet = context.workbook.worksheets.getItem("sheetname");
                var selection = sheet.getUsedRange();

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

Severely affected. Production web application users are unable to use the excel online with excel-add-in

## Useful logs

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by bushraHavi** [comment]
I am facing the same issue. It was working fine till last week.

**Comment by PravallikaPokala** [comment]
I am facing the same issue as @SangeethaPoyyaparambil .
That was working fine last week, but now it states the following on sync:
RichApi.Error: Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again.
Is anyone investigating this?

**Comment by RuizhiSunMS** [comment]
Looks similar with #3019 and #3020, I've reached out to on-call eng to take a look.

**Comment by theboyknowsclass** [comment]
we are also having this issue - seemed to occur late yesterday

**Comment by semy** [comment]
All productive apps no longer work

**Comment by semy** [comment]
Is there a temporary hotfix we can apply in the meantime?

**Comment by RuizhiSunMS** [comment]
Hi All, our eng and I both failed to repro. 
As for me, I selected some cells then executed the following code in scriptlab, everything worked fine.
```
$("#run").click(() => tryCatch(run));

async function run() {
  await Excel.run(async (context) => {
    const range = context.workbook.getSelectedRange();
    range.format.fill.color = "red";
    range.load("address,rowCount, columnCount, values");
    await context.sync();

    console.log(`The range address was "${range.address}". and "${range.rowCount}"`);
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}
```
Does this problem only happen in debugging addin or also happen in scriptlab? I didn't try in debugging an add-in since I don't have any.

**Comment by semy** [comment]
@RuizhiSunMS The problem we have is with the web Excel version. Yesterday it worked and we did not make any changes.

**Comment by SangeethaPoyyaparambil** [comment]
@RuizhiSunMS ,
https://github.com/OfficeDev/office-js/issues/856
For this same issue, they have mentioned they have found the root cause. So this issue exists, not for just us and for many users.
We are not testing in Scriptlab, our application is already in production, it's web version of excel. We didnt make any code change .

**Comment by SharonCKC** [comment]
@RuizhiSunMS we also have this issue in production. It looks fine on Excel Desktop, but the error occurred in all browsers on Excel Online (Chrome, Firefox, Safari). Our add-in has multiple task panes. The one with the TaskpaneId `Office.AutoShowTaskpaneWithDocument` is fine, but all other task panes throw the error.

**Comment by Denwah** [comment]
Any update on when this may be fixed?

**Comment by gingerjia** [comment]
@Denwah the issue has been mitigated, could you help to double confirm from your side? If it still repro, please let us know. Thanks very much and apologize for the impact!

**Comment by Denwah** [comment]
All looks good on my side. Thanks for fix

**Comment by PravallikaPokala** [comment]
Thankyou @gingerjia for fix. All looks fine.

**Comment by RuizhiSunMS** [comment]
Close this issue since this issue is mitigated now. Feel free to reopen if it blocks you again.

**Comment by SangeethaPoyyaparambil** [comment]
Thank you @gingerjia, for investigating and fixing it.

**Comment by YasharHeydari** [comment]
Hi, 
   I'm not sure how this is closed. I have the very same issue. When I click on a cell to enter edit mode and then I click on task pane, on which we have a button that will run  commands to set the cell value, I still get the same 
  "InvalidOperationInCellEditMode error: Excel is in cell-editing mode" error! Shouldn't clicking on task pane make the excel exit from cell-editing mode?

**Comment by gingerjia** [comment]
@YasharHeydari, thanks for reporting the issue! The issue you report isn't same as the above resolved one. Above was for getting the error message even users are not edit-mode. And it has been solved. 
For your request, clicking on task pane make the excel exit from cell-editing mode automatically wasn't support yet. Could you help to submit a new request in the https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform then our PM will triage it accordingly? Thanks again for helping improve our add-in capability!
