### ISSUE TITLE
Outllok add-in : CORS error coming while fetching message content using Outlook REST API

### ISSUE THREAD

**Issue by gs-achandrakamal** [OfficeDev/office-js#3023]
# Provide required information needed to triage your issue
While trying to fetch email content using Outlook REST API approach,  users are facing CORS error. 
In the above this [documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api)), it is mentioned that CORS issue comes for On-premise based servers. But they have confirmed that they are on Office 365 with exchange server version as 2016, 15.1.2507.16. 
 
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: MAC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Exchange Server version: 2016, 15.1.2507.16
* Operating System: Mac OS Ventura 13.01
* Browser (if using Office on the web): Chrome and Safari
 
## Expected behavior

REST endpoint should have worked as per the documentation. 

## Current behavior

Fails to get message content from server due to CORS error

## Steps to reproduce

1. Got access token from Office.context.mailbox.getCallbackTokenAsync({isRest: true}
2. Got item's rest id
3. Hit Office.context.mailbox.restUrl + '/v2.0/me/messages/' + itemId using access token
4. Getting CORS error after hitting, please refer screenshot.

## Context

This is happening for all users belonging to one of our client. It was mentioned that they are utilising a third party vendor to use Outlook

## Useful logs

- <img width="1119" alt="Screenshot 2022-12-05 at 5 21 31 PM" src="https://user-images.githubusercontent.com/72736097/206107539-5aa86dcb-af1b-4a4a-b117-f5c434168487.png">

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
We are unable to reproduce the issue with the steps you mentioned. The below code snippet works fine for us.
```
const ewsId = Office.context.mailbox.item.itemId;
const restId = Office.context.mailbox.convertToRestId(ewsId, Office.MailboxEnums.RestVersion.v2_0);
var url = Office.context.mailbox.restUrl + '/v2.0/me/messages/' + restId;

Office.context.mailbox.getCallbackTokenAsync(function(result) {
    if (result.status !== Office.AsyncResultStatus.Succeeded) {
      console.error(`Token retrieval failed with message: ${result.error.message}`);
    } else {
        fetch(url, { 
            method: 'GET', 
            headers: new Headers({
                'Authorization': 'Bearer ' + result.value,
                'Content-Type': 'application/x-www-form-urlencoded'
            })
        }).then(function(serverPromise) {console.log(serverPromise);});
    }
});
```
Could you provide us with the following details?
1. Is the issue consistently reproducible or does it occur occasionally?
2. Are you using Outlook client on Mac or Outlook on Web?
3. If using Outlook client on Mac, what is the version?
4. Can you try running the above script in your add-in and see if it gives the same error?
6. If yes, would you be able to provide us with a test account where the issue is reproducible and sample script where error is seen?
