### ISSUE TITLE
Office.context.mailbox.item.from.getAsync() failing with error codes 5000, 5001 and 5005

### ISSUE THREAD

**Issue by gs-achandrakamal** [OfficeDev/office-js#3024]
# Provide required information needed to triage your issue

For few of our users, Office.context.mailbox.item.from.getAsync() fails with  following error codes:

-  5000 : The operation is not supported.
-  5001 : An internal error has occurred.
-  5005 : Operation failed because the data is not current on the server.

## Your Environment

Several logs have been received for multiple users. Following are the environment details for one of our user getting code 5000.
* Platform [PC desktop, Mac, iOS, Office on the web]: MAC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Exchange Server version: 2016, 15.1.2507.16
* Operating System: Mac OS Ventura 13.01
* Browser (if using Office on the web): Chrome and Safari
 
## Expected behavior

"From-address" information should have been fetched successfully.

## Current behavior

It fails with above error codes.

## Steps to reproduce
Happens while using Using Office.context.mailbox.item.from.getAsync() callback 

## Context

Getting sender's information is required for using one of our key features while composing.

## Useful logs

<img width="1247" alt="Screenshot 2022-12-05 at 8 30 23 AM" src="https://user-images.githubusercontent.com/72736097/206095741-aaf810a5-42a8-49ee-a6e4-7823937361bd.png">
Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Could you please provide more details on the following?

1. Is this issue reproducible consistently?
2. Can you generate a diagnostics ID from the Outlook Client where the issue is reproducible?
     Steps: Close outlook and restart it.
                 Click on Help->Collect Diagnostics
                 Provide us with the incident ID

**Comment by gs-achandrakamal** [comment]
Error code 5000 is happening every time for the users facing this. We have scheduled calls with them. Accordingly, we'll provide the Diagnostic Ids

**Comment by exextoc** [comment]
@gs-achandrakamal Keeping it in Needs: authors feedback, change it back after sharing the diagnostic id.

**Comment by gs-achandrakamal** [comment]
Sure, thanks

**Comment by gs-achandrakamal** [comment]
The Incident ID is XA6J692P

**Comment by exextoc** [comment]
@gs-achandrakamal 
We are checking the logs in the meantime could you please share the repro steps and sample code, it will help us reproduce locally.

**Comment by exextoc** [comment]
1. Can you please share a 'test account' from your tenant with us on this email id: OutlookExtensibility@M365x27035562.onmicrosoft.com ?
2. In your "Outlook Mac" client, are you seeing "First Name Last Name" for user or you directly see user's email address in "From" field? Can you please share screenshot of this if possible? Thanks

**Comment by gs-achandrakamal** [comment]
Hi, 
Sorry we couldn't hear from our user, so couldn't update. We can't share a test account as it's not reproducible there. Attaching from address screenshot shared from the user where 5000 is being reproduced. Looks like only email address(without first and last name) is shown in from address field
Diagnostic Id : 92XPVA4
<img width="823" alt="Screenshot 2023-02-21 at 2 32 30 PM" src="https://user-images.githubusercontent.com/72736097/220299962-af6cbd57-b8f8-4a86-adef-7bcec364d0dd.png">

**Comment by exextoc** [comment]
Hey @gs-achandrakamal ,

We need to follow up for this. Can you please run an add-in which logs or outputs `Office.context.mailbox.userProfile.displayName` and tell us if it comes null for the user for whom this issue is reproducible?

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
