### ISSUE TITLE
Location not updated when updating an recurring series item

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#3027]
When I update an item of a recurring serie, if I delete or change location and then open my add-in the `enhancedLocation.getAsync` function return old location.

## Your Environment

* Platform : PC Desktop
* Host : Outlook Desktop
* Office version number:  Version 2209 Build 16.0.15629.20200
* Operating System: Windows 10 Pro Build 19044.2130
 
## Expected behavior
When I edit the location of an item from a recurring serie and open an add-in, enhanced location contains the location before update.

## Current behavior
At add-in startup call to `enhancedLocation.getAsync` should return the updated location

## Steps to reproduce
1. create a recurring serie with  meeting room "room1" as location
2. open an item and delete location
3. open add-in.  `enhancedLocation.getAsync` contains room1. It should return an empty array

# Provide additional details
If we replace the location room 1 by room2 `enhancedLocation.getAsync` returns [room1, room2] 
Sometime a modal appears with a message "do you want to update"
If we click "Ok" the meeting is saved and  `enhancedLocation.getAsync` seems to be correct
If we click "Cancel" old meeting room is returned even if location field is empty

## Context
If there is a room selected, my addin is supposed to display informations about the room else it must display a room list selector.
With this issue the addin display a room information panel without room selected.

**Comment by timwan10** [comment]
I'm currently not able to repro this. Can you be more specific on your instructions. Specifically, when you close/open an item, and if you are editing the individual item or the entire series? (for what it's worth I tried what I believe to be all combinations of these, but I couldn't repro either...but perhaps I missed something) Also where are you opening the add-in, on the same account / instance of outlook that created the add-in? or on the machine of an attendee of the meeting? 

Are the locations actually resolved locations? or just strings?

Can you also check to see if you have Shared Calendar Improvements turned on or off? (In Account Settings->Change->More Settings->Advanced)

![image](https://user-images.githubusercontent.com/17890744/206333061-583a9c81-9a22-4bcf-bb6d-f5403ef1aa80.png)

**Comment by ghost** [comment]
Thank you @RuizhiSunMS 
my issue is on an individual item from recurring event

but I created a simple test project to show you the issue and I don't reproduce it. It means that it's a problem in my addin.
 I should have started with that, sorry for the inconvenience.
