### ISSUE TITLE
How do I detect if Excel is open or closed?

### ISSUE THREAD

**Issue by knight-baron** [OfficeDev/office-js#3029]
## How do I detect if Excel is open or closed?

I created an add-in from Office.js but I can't find any document about excel close events. Is it possible I can detect when the user closes Excel I want to run some logic before the user closes Excel

**Comment by Rick-Kirkham** [comment]
I'm afraid that there is no way to handle the event of Excel closing in an add-in. It's an interesting idea. Please suggest it at [Microsoft 365 Developer Platform  Ideas](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). 

In the meantime, see if your clean-up logic can be run when the add-in starts up on a given document.
