### ISSUE TITLE
Cannot redefine context property

### ISSUE THREAD

**Issue by RoelVB** [OfficeDev/office-js#303]
When trying to load Office.js I get the message:
`Kan de niet-configureerbare eigenschap context niet opnieuw definiëren
outlook-win32-16.02.debug.js (646,17)`
Which would translate to something like:
`Cannot redefine non-configurable context property `

## Steps to Reproduce
To give a complete picture. I'm actually hosting an Outlook add-in in Sharepoint Online as an SPFx webpart. When trying the add-in using the Sharepoint online workbench everything is fine. When I publish te webpart on a page I get this message.

So I would think that Office.js conflicts with something on Sharepoint, but I'm unable to find what it is. At first I thought it would be `window.Office.context`, but this doesn't exist until Office.js gets loaded.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.02
* Operating System: Windows 10

**Comment by Zlatkovsky** [comment]
Just as a guess:  are you sure you aren't including two copies of Office.js accidentally?  (Two separate script references to it?)

**Comment by RoelVB** [comment]
Thanks you for your reply. Unfortunately that's not the case.

**Comment by exextoc** [comment]
It's hard to guess what is happening here, without being able to debug it. Maybe systematically remove script references until the error goes away and try to figure out what may be causing the conflict?

**Comment by kbrandl** [comment]
@RoelVB were you able to successfully troubleshoot this problem by using to the technique that @exextoc suggested earlier in this thread?  Are you still having this problem?

**Comment by RoelVB** [comment]
Sorry. I didn't have time to test his yet. Not completely sure how I could test this best. I'll start by adding some logs in the startup of the webpart. Maybe somehow it gets triggered twice.

It did check if `window.Office` exists when my webparts isn't loaded into the page. It doesn't, it gets created when te webpart loads.

**Comment by exextoc** [comment]
@RoelVB let us know when you have more information.

**Comment by RoelVB** [comment]
I did some testing. The `office.js` file is actually loaded twice. But this only happens in Internet Explorer.

Internet Explorer:
![officejs](https://user-images.githubusercontent.com/10999128/50297372-eff86500-047c-11e9-9443-981ef32726b1.png)

Chromium:
![officejs2](https://user-images.githubusercontent.com/10999128/50297407-06062580-047d-11e9-8dde-61d4d9ff61db.png)

**Comment by RoelVB** [comment]
I've posted an issue on the SPFx side: https://github.com/SharePoint/sp-dev-docs/issues/3160

A work around could be, stopping Office-js from throwing an error when it's already loaded. When it's already loaded it shouldn't try to load again.
