### ISSUE TITLE
[Outlook] Calls to get item details (body, attachments, recipients) and REST API calls to get message slow on weekends/holidays

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#3031]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
Calls to get item details (body, attachments, recipients) and REST API calls to get message slow on weekends/holidays. My guess would be it's likely related to the REST API call being made to obtain the message (````${restUrl}/v2.0/users/${currentUser}/messages/${restId}````).

## Expected behavior
I would expect NOT to see a roughly 75% decrease in performance on weekends/holidays.

## Current behavior
![image](https://user-images.githubusercontent.com/7740624/206747012-79310ef0-4416-4a4a-9af1-fa812fafcf94.png)
In this chart, you can see that the handling that fetches all the email details (body, attachments, recipients) and also may make a call to the REST API (/message) is far slower on the weekend and holidays (every spike on this chart is Sat/Sun + any holidays).

## Steps to reproduce
Analyze metrics for obtaining the item details and retrieving the message from the REST API over the weekends compared to weekdays. 

## Context
Obviously this type of performance degradation is not ideal at any time.

## Useful logs
See screenshot above

**Comment by cody-lettau** [comment]
@gergzk why are we closing bugs that are not fixed (even if they aren't planned to be fixed at this time)?

**Comment by gergzk** [comment]
@cody-lettau - we are retooling our internal processes to better track bugs. However, part of that is keeping the set of issues to a manageable level. A lot of the issues we're bulk closing became irrelevant or have been fixed but the issue didn't get closed on this side. We are using inactivity as the sort order here and observing feedback from customers.
