### ISSUE TITLE
Placing large image in Word Online not working

### ISSUE THREAD

**Issue by A-Glazer** [OfficeDev/office-js#3033]
I am trying to place a large jpg image (size 17.15 MB) in Word Online. The code appears that the image was placed successfully, but it doesn't place the image in the document and there are no error messages. It is working properly in Word Desktop.

```
let options = {coercionType: Office.CoercionType.Image};
Office.context.document.setSelectedDataAsync(base64, options, function(obj){
  console.log('obj', obj)
  context.sync().then(function(){
    console.log('complete')
  }, function(err){
    if(err){console.log('failed')}
  });
});
```
obj is returning:
```
status: "succeeded"
value: {}
```
The code places properly for a smaller image and on Desktop. Is there another way to check if the image placed properly or an error message?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 1.0.0
* Operating System: Windows (also an issue on iOS)
* Browser (if using Office on the web): Chrome
 
## Expected behavior

The image should place properly, like it does on Word Desktop. If it doesn't place since it is too big, there should be an error message. Currently the status is `succeeded`.

## Current behavior

1. The image doesn't place.
2. `context.sync()` is succeeding and marking that the image was placed properly. 

## Steps to reproduce

1. Open the add-in in Word Web
2. Convert this image to Base64: https://drive.google.com/file/d/1pURAUDF7kLbb_udE4a114mso8HSMXoZT/view?usp=sharing
3. Place in Word Web using the code above.
4. `Context.sync()` will return it has succeeded, even when it doesn't place properly.

## Link to live example(s)

# Provide additional details

## Useful logs

See code above
- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 

I would be happy to continue this discussion offline with more examples. What is your email address?

**Comment by RuizhiSunMS** [comment]
@A-Glazer Thanks for the reporting. I realize this should be the second time you submitted the issue and the first one was on stackoverflow. We planned to paste one of my colleague's email address but this action seems Ineligible.
Since you have uploaded the image, I'd forward this to that colleague.

**Comment by RuizhiSunMS** [comment]
Our eng has confirm this as a bug and put it into our back log list with an ID of #7360586.
Sorry that we can't provide a timeline now but will update here if achievement is got.

**Comment by A-Glazer** [comment]
Hi, any update on this issue?

**Comment by xiruatms** [comment]
@A-Glazer , will you please give it one more try to confirm whether the issue is still there?

**Comment by A-Glazer** [comment]
@xiruatms Yes, I am still seeing the issue.

**Comment by xiruatms** [comment]
@A-Glazer , thanks for reporting this. Due to consideration on network/performance/storage and so on, there has to be some limitations on the size of base64 string used in this APIs regarding different usages. Currently, it should be less than 19MB for images.
