### ISSUE TITLE
Different behavior of Excel.Chart prop "name" at Excel online and on desktop

### ISSUE THREAD

**Issue by irynakaban** [OfficeDev/office-js#3034]
We need to be able to distinguish between charts created by us and those created by a user simply using Excel. According to the documentation, we found that the property "name" that is in Excel.Chart is perfect for us. However, we faced the problem that on the desktop, when copying or moving a chart, the name is preserved, but online it does not work ([link to video](https://drive.google.com/file/d/1XlxOWUOSap5P_ZojLD2SWAOTWd7LPdVA/view?usp=share_link)). It looks like a bug. Please look into this issue and confirm if it is a bug.
Also, please tell me if there is any better way to distinguish the chart we created, even in case of copying or moving to another page.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.15930.42301
* Operating System: Mac OS
* Browser (if using Office on the web): Mozilla Firefox
 
## Expected behavior
Property "name" in Excel.Chart in Excel on the web save when user copy or move chart.

## Current behavior
Property "name" in Excel.Chart in Excel on the web does not save when user copy or move chart. Instead, a standard name is replaced, for example Chart 1.

## Steps to reproduce

1. Create chart from taskpane with name.
2. Try to copy, or cut and paste chart.

## Link to live example(s)

1. [Video](https://drive.google.com/file/d/1XlxOWUOSap5P_ZojLD2SWAOTWd7LPdVA/view?usp=share_link)
2. [Excel](https://1drv.ms/x/s!AhbpLV1keI0piWcKsERSjfU-CGtW?e=vWto70)
3. [Code for ScriptLab](https://gist.github.com/irynakaban/5bd9b39ebd113316a5217fddfc51359e)

**Comment by donlvMSFT** [comment]
Hi @irynakaban, 

Thanks for reaching out to us for this issue. Currently, the name generation on desktop and online is not the same, we will confirm whether this behavior would get changed in the future. 

And for your scenario, a workaround would be use Shape.altText in this chart scenario. One chart object would have a corresponding shape project with same ID, I have a quick sample code you could try: [ChartAltText](https://gist.github.com/donlvMSFT/cc55005e2b86c50e3af563060356dd5a )

Hope this could help you.

Thanks,
Dongqi

**Comment by irynakaban** [comment]
Hi @donlvMSFT, thanks for the solution you described. 

I will expand my question a little bit, because it seems that this option does not suit us. We need to distinguish all charts that are added from the taskpane. Including copies of these charts. That is, if a user added a chart from the taskpane, then made a copy of it — we need to know that it is also our chart. In the case when a user transfers a chart to another sheet, as far as I found, the chart id changes. That is, it is impossible to bind to the id. What should we do in this case? 

Perhaps the chart or series has some hidden from the user property where we can save the data that this chart belongs to our taskpane?

**Comment by donlvMSFT** [comment]
Hi @irynakaban, what I mentioned in the sample code is to use Shape.altTextDescription to identify the Chart. the altText won't be changed after copy the chart, could you take a try?

**Comment by irynakaban** [comment]
Hi, @donlvMSFT!

Oh, I see what you mean. I was able to do it. It was just not immediately clear that chart is a shape. But now I have already understood it. Thank you very much for your help.

**Comment by RuizhiSunMS** [comment]
Close the issue since the workaround is accepted. Please feel free to reopen it if you still have the problem.
