### ISSUE TITLE
Excel column width not set to the correct number of pixels

### ISSUE THREAD

**Issue by TheMagnificent11** [OfficeDev/office-js#3036]
Excel columns get formatted to the wrong width when setting the width to a specific number of pixels via `format.columnWidth`.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: NA (web)
* Operating System: NA (web)
* Browser (if using Office on the web): Chrome and Edge
 
## Expected behavior
When using `format.columnWidth` to set the width on an `Excel.Range` object, you would expect the number of pixels specified to be what is displayed when the column is resized.

## Current behavior
Currently, if you set a column to have a width of 40 pixels, it displays as 53 (see attached video).

https://user-images.githubusercontent.com/5241102/207183704-8abe4c6a-eade-4b83-84dd-cc64cf494c98.mp4

## Steps to reproduce
1. Add the "Script Lab" Office Add-In to Excel.
2. Paste the following script into the script editor.
```js
$("#run").click(() => tryCatch(run));

async function run() {
  await Excel.run(async (context) => {
    const range = context.workbook.getSelectedRange();
    const column = range.getColumn(0);
    column.format.columnWidth = 40;
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}
```
3. Run the script and view the column width of the resized column

**Comment by RuizhiSunMS** [comment]
@TheMagnificent11, thanks for the reporting and sorry for the late response since our team is encountering health issues. Will handle this issue as soon as our engs are back.

**Comment by yuc014** [comment]
Hi @TheMagnificent11,

After reading the source code of columnWidth, it doesn't use pixel as its units. Actually it uses "point" as unit to set and read column width. 

If you just load the default column width, it also shows different value as you get in UI.
```
UI pixel: 64
column.format.columnWidth: 48
```
Since the actual width that you see on the screen varies, depending on the width of the font defined for the Normal style of your workbook. So I guess api use its unique measurement to ensure the width work in different style.

Plus, a potential workaround, I notice there is a relationship in pixel width and api's column width.
`0.75*UI pixel = columnWidth` Hope this could unblock you.

ref: https://learn.microsoft.com/en-us/office/troubleshoot/excel/determine-column-widths

**Comment by TheMagnificent11** [comment]
Thanks for the response @yuc014, that makes sense.

However, it would be good if the documentation has a reference to that link for future releases of OfficeJS.

![image](https://user-images.githubusercontent.com/5241102/208830409-89b43724-835a-4070-badd-72267835fb8c.png)

**Comment by yuc014** [comment]
@TheMagnificent11 Good suggestion.

**Comment by TheMagnificent11** [comment]
@yuc014 do you need me to submit a PR with the link in the documentation comment?

**Comment by lindalu-MSFT** [comment]
@TheMagnificent11 yes please submit a PR where you think the link will improve the documentation! You can @ me and I'll review. Thanks, Linda

**Comment by TheMagnificent11** [comment]
> @TheMagnificent11 yes please submit a PR where you think the link will improve the documentation! You can @ me and I'll review. Thanks, Linda

@lindalu-MSFT what branch should I branch off to create my PR?

The default branch (`release`)?

Also, does this repository contain the source code for OfficeJS, or is it just the minified distributable JavaScript?

**Comment by lindalu-MSFT** [comment]
@TheMagnificent11 Yes just go to the default branch and edit to make changes. You'll be prompted to name your branch to create the PR. Then @ me in that PR.

**Comment by TheMagnificent11** [comment]
@lindalu-MSFT this Git repo only appears to have minified JavaScript...I can't find the actual source files 🤷 

It seems like the change needs to be made in another repo and then the build output of that repo is published here.

**Comment by lindalu-MSFT** [comment]
@TheMagnificent11 Yes, I think you're right. Sigh. I was thinking you wanted to update the Learn topic [here ](https://learn.microsoft.com/en-us/office/troubleshoot/excel/determine-column-widths)but see it's already referenced. Hopefully, people can find using search!

**Comment by TheMagnificent11** [comment]
Yeah, I guess people can find it using seach.

The issue is that when you use web Excel, you understand that there's two different units of width measurement; characters and pixels.

The code comment for this width property in OfficeJS doesn't tell you whether it's characters or pixels.

My understanding from reading that article is that the width property isn't characters or pixels, it's some other calculation (similar to REM in CSS).

And yes, a developer should eventually find that documentation after using the width property and then wondering why it hasn't been set correctly.

Then, they might use Script Lab and think it's a bug.

I did these two steps and then raised this GitHub issue.

I guess a more insightful developer would Google and find the article that explains the issue.

All of this is avoided if the article is linked in JS doc; the developer navigates to the type definition and sees the link above the property and all this confusion is avoided.
