### ISSUE TITLE
cannot correlate inlinePictures with the <img> body elements; especially when ink drawings are present

### ISSUE THREAD

**Issue by rogozind** [OfficeDev/office-js#3039]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am not sure if this is a bug, feature request or a how-to question so I start with a bug report.

We need to be able to correlate body.inlinePictures with <img> tags found in the body. There seems to be no ID returned in the inline picture element which can reference back the src attribute of the img tag. (is there a feature request to add something?) Up until now we just assumed that the list of <img> tags matches the order of inlinePictures elements returned and it worked quite well. 

Today we discovered that ink objects are represented by <img> tags too in the HTML. Yet they are completely missing from the list of inlinePictures (bug?). So our algorithm breaks and now we see no way to reconstruct the document from HTML and the list of inline pictures.

Please advise. Can we have the SRC ID included in teh InlinePicture object? Or can we make inlinePictures match the <img> tag list a ll times (in other words include al possible images like ink? )

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___Any___
* Host [Excel, Word, PowerPoint, etc.]: ___Word___
* Office version number: ___16.67___
* Operating System: __MacOS____
* Browser (if using Office on the web): ___Chrome___
 
## Expected behavior
Either include INK objects in the list of inlinePictures or have an ID on the image to correlate back to the IMG tag (preferable)

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuizhiSunMS** [comment]
@rogozind, please confirm the application is the Word, right?

**Comment by rogozind** [comment]
correct, Word.

**Comment by xiaoyuMS** [comment]
Hi, @rogozind 

According to my test, only the ink object inserted by Word Web can be retrieved on Word Web. Otherwise, the ink object can't be retrieved. We need more investigation to see if it is by design or a bug.

For the correlation between inline pictures and the 'src' attribute of html image tags, currently we don't provide such an API. @RuizhiSunMS, it should be a feature request.

**Comment by rogozind** [comment]
Hi @xiaoyuMS 

I found this description in Body object:

> inlinePictures | Gets the collection of InlinePicture objects in the body. The collection does not include floating images.

Maybe "floating images" are those ink objects?

Even if it is by design it makes it impossible to tie images back to the HTML structure. Please expose SRC attribute.

**Comment by xiaoyuMS** [comment]
Thanks for your finding @rogozind 

Currently the ink object by default is inline in Word Web. On Desktop, the ink object by default is floating, and we can change its layout to inline. On Word Web, we can detect the inline ink object while we can't do so on Desktop. We will open a bug for this inconsistent behavior.

For the request to add the SRC attribute, we would like to suggest you go to [Microsoft365DeveloperPlatform](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.

**Comment by rogozind** [comment]
I did not find anything relevant there. There is a request to expose floating images separately from inlinePictures. But nothing about src attribute. So I made a new one: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/expose-src-attribute-in-inline-pictures/idi-p/3702132#M1522

**Comment by RuizhiSunMS** [comment]
@rogozind 
ACK. Our PM will take it into consideration when make plan for the new quarter.
