### ISSUE TITLE
Office.context.mailbox.item.getAttachmentContentAsync return differs depending on platform for Outlook

### ISSUE THREAD

**Issue by feannyn** [OfficeDev/office-js#3043]
Office.context.mailbox.item.getAttachmentContentAsync call is made and the result.value.content is different depending on what platform the user is on. Specifically, Outlook windows returns a value that is different from what is returned on Outlook Mac and OWA. I have seen this in my testing with .msg file types, but I'm guessing there may be others where the attachment content is not correctly formatted/encoded on Windows desktop in a similar fashion to other platforms

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Cloud PC Windows365
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: (Version 2211 Build 16.0.15831.20098) 32-bit 
* Operating System: Windows 11 Enterprise
* Browser (if using Office on the web): --
 
## Expected behavior
Office.context.mailbox.item.getAttachmentContentAsync result.value.content should return the same value across all platforms; the issue seems to only happen with .msg file types.

## Current behavior

Specifically, Outlook windows returns a value that is different from what is returned on Outlook Mac and OWA when making a call to Office.context.mailbox.item.getAttachmentContentAsync.

## Steps to reproduce

1. Make a call to Office.context.mailbox.item.getAttachmentContentAsync on Windows Outlook. Access the result.value.content.
2. Access the result.value.content.
3. This value is different from what is seen in Outlook Mac and OWA.

## Link to live example(s)
1. ______
2. ______
3. ______

# Provide additional details
1. ______
2. ______
3. ______

## Context
We are unable to utilize .msg files within our Add-in on send with Outlook windows because the value returned is different from what is returned on the other platforms; OWA, Outlook Mac.

We have video recordings that detail what is going on. The data being returned on the getAttachmentsContentAsync call differs on Outlook Windows from Outlook Max and OWA. This can be seen on the `DataAsText` property in the file object.

## Useful logs
We have a video recording of this issue but they are too large to attach onto this bug report. Please provide an email that we can send this to. 

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ztcdsb** [comment]
@feannyn Can you test this again and let us know if you can still repro it?
I compared result.value.content between Win32 and OWA, and their value are the same(or maybe it was fixed already).

If you still seeing the issue, please upload the video to a private repository on GitHub and then at-mention exextoc or my GitHub account so that we can access the data/information securely.

**Comment by feannyn** [comment]
Hello, So this system is win64 not 32. I have attached an image from System->About->Device Specifications.
<img width="534" alt="Screenshot 2023-01-05 at 9 52 09 AM" src="https://user-images.githubusercontent.com/17707848/210808552-457ecabc-ccb8-415b-b662-cbbb78cc29c3.png">

**Comment by ztcdsb** [comment]
@feannyn My apologies, for Win32 that I am referring to desktop  version of Outlook. 
In the environment above, you listed that you are running 32 bit version Outlook on a 64 bit system, is that correct?
It will be really helpful if you can follow the steps in my comment above and mention exextoc so that we can better understand the problem.
