### ISSUE TITLE
Can i get the link that link to comment?

### ISSUE THREAD

**Issue by ruhchjdbdbhccjjc** [OfficeDev/office-js#3045]
There are new replycomments in web office(like excel and word,),
I can get the link that link to comment by a button with link_to_comment text ,but i can't find any api 
about this.
Can we get the comment link ?

**Comment by wamaina** [comment]
Thank you for reaching out! It would be great if we could get some additional understanding of the scenario you have and what information you need to achieve it successfully. Could you provide an example of what you are hoping to achieve?

**Comment by ruhchjdbdbhccjjc** [comment]
Thanks!     Sorry about so later!
![image](https://user-images.githubusercontent.com/76729215/208239333-cfa2a260-f972-456d-a78d-dcddd9b6f8c6.png)
Just get the share link for comment.

**Comment by RuizhiSunMS** [comment]
Hi @wamaina, our eng did some investigations and confirmed we don't have such api now.
For new feature request, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.
