### ISSUE TITLE
Excel custom functions return #NAME when used in embedView

### ISSUE THREAD

**Issue by davidelsey** [OfficeDev/office-js#3046]
Using an embeddable link to an Excel document (created using File> Share > Embed and enabling "Let people type into cells ") results in all custom functions returning #NAME? after a user enters new values.

# Provide required information needed to triage your issue

## Your Environment
* Platform : Office on the web
* Host : Excel
* Office version number: n/a
* Operating System: Windows 11
* Browser : Edge 108.0.1462.46
 
## Expected behavior
For an authenticated user who has the add-in installed, custom functions behave in "embed view" identically as they do in the Excel web client.

## Current behavior
The document renders perfectly in embedView until such time as any cell is edited - after which, all custom functions return #NAME?

## Steps to reproduce
1. Create a new Excel workbook in the Office web client.
2. Register any custom function via the samples in Script Lab. 
3. Add the custom function to a cell on the worksheet.
4. Create an embedLink via File > Share > Embed  and enable "Let people type into cells".
5. Copy the URL from the src value in the "Embed Code"
6. Browse to the URL.
7. Type any value into any cell.
8. Note that all instances of all custom functions resolve immediately to #NAME?

# Provide additional details
Given that the document viewer at https://xxxxx-my.sharepoint.com/:x:/r/personal/xxxxxx/_layouts/15/Doc.aspx? renders custom functions correctly with querystring param "action=default", I'd hope that "action=embedView" would work also.

## Context
We have an Excel add-in with multiple custom functions which interact with external apis.  Users should be able to manipulate ephemeral worksheets in an embedded view of a workbook and have the custom functions fire without having to see (or have access to) the entire Excel chrome (ribbon, toolbars etc).  
Alternately, if there were a way to hide all Excel chrome in the default viewer, this might be an acceptable workaround.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/1235003/207804266-c4285d1a-3f79-47ad-a955-06cba653a318.png">
<img width="722" alt="image" src="https://user-images.githubusercontent.com/1235003/207804565-350ada53-43d7-481f-97e3-5d85e5558c16.png">
<img width="516" alt="image" src="https://user-images.githubusercontent.com/1235003/207804795-fb875448-b525-4158-bdc7-c9848904e5fd.png">

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuizhiSunMS** [comment]
@davidelsey, thanks for the reporting and sorry for the late response since our team is encountering health issues. Will handle this issue as soon as our engs are back.

**Comment by davidelsey** [comment]
Hi @RuizhiSunMS, any chance of an update on this issue?  Do you need more information?

Cheers, 

Dave.

**Comment by davidelsey** [comment]
Hi @RuizhiSunMS , can I please get an update on this issue?

Cheers, 

Dave.

**Comment by davidelsey** [comment]
Hi @yaweizhu-henson , @RuizhiSunMS can I get an update on this please?

Cheers, 

Dave.

**Comment by yaweizhu-henson** [comment]
Hi @davidelsey , sorry for the late response. I will double check with our engineer internaly and get back to you ASAP.

**Comment by RuizhiSunMS** [comment]
@rundongmsft Please take a look.
And @penglongzhaochina please monitor this issue.

**Comment by yaweizhu-henson** [comment]
Hi @davidelsey , I just got the answer from our engineer.
Simply put, because the embed view does not support add-in, the custom function will display #NAME.
Since custom function rely on add-in's support, so custom function might not be able to function well in embed view. 
Hope this can solve your question.
Thanks!

**Comment by donlvMSFT** [comment]
I'd like to close this issue due to current status, please raise a new one or reactive if there're further questions. Thanks!
