### ISSUE TITLE
Retrieve office license type

### ISSUE THREAD

**Issue by cerinaMarin** [OfficeDev/office-js#3047]
Hello,

While developing Excel add-in I encounter the issue of task pane starting with IE11 and not with Webview.
I found the reason why in this article: https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

If users task pane starts in IE11 I would like to notify them to install a Webview2 runtime so they can get full experience of add-in.
For easier troubleshooting..
I found the way to retrieve host, version and platform using for example `console.log(Office.context.diagnostics)`.
However I would like also.. if possible.. to retrieve license type (if it is a perpetual license or volume license or the office 365 subscription) of users' Office.
Is there a way to retrieve a license type?

Thanks

**Comment by prasadhpshenoy** [comment]
This is blocking me as well.. Information on this can be super helpful to proceed.

**Comment by yuc014** [comment]
Hi @cerinaMarin @prasadhpshenoy,

Fortunately I did find an api can get the license info: `console.log(Office.context.license)`.

Hope this is what you looking for :)

ref: https://learn.microsoft.com/en-us/javascript/api/office/office.context?view=excel-js-preview#office-office-context-license-member

**Comment by cerinaMarin** [comment]
Hi @yuc014. Thanks for the comment, but unfortunately `console.log(Office.context.license)` doesn't give me much. I cannot get any information about license with it. 
Here is what I get: 
![image](https://user-images.githubusercontent.com/58341645/208894014-9e68017e-6791-4ddc-8aab-36778e037e09.png)

**Comment by yuc014** [comment]
Hi @cerinaMarin ,

Sorry, I just see this api is for internal use only. So, get the info of user license is not supported for developers. 

For new feature request, I normally suggest go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. But I'm not sure if user license info belongs to user privacy, we are very careful about the privacy part. 

By the way, I'm curious about your using scenario.

**Comment by cerinaMarin** [comment]
Hey @yuc014, I hope I can explain better what my scenario is.
On this link https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins there is a table with list of browsers used by add-in. Browsers depend of Office version, retail or volume license or installed webview.
So if user browser is IE11 (which has its own limitations and my add-in won't be presented fully), by getting type of the license I would troubleshoot easier what license user has and I could notify him with some kind of pop-up or modal to install newer version of Office, or get retail license to get all functions my add-in offers.

**Comment by yuc014** [comment]
@cerinaMarin Ok I see, I would recommend you raise a feature request here https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform to take a try.
