### ISSUE TITLE
`OnNewMessageCompose` LaunchEvent cannot invoke `displayDialogAsync`

### ISSUE THREAD

**Issue by hbnrmx** [OfficeDev/office-js#3049]
## Your Environment

* Platform: Mac
* Host: Outlook
* Office version number: Outlook for Mac 16.68 (22121100)
* Operating System: macOS
 
## Expected behavior
In Outlook for Mac I would like to open a dialog via `displayDialogAsync` as triggered by a LaunchEvent (`OnNewMessageCompose`)

## Current behavior
The window flickers on screen very shortly or doesn't display at all. It seems as though the callback to `displayDialogAsync` is never invoked, so there is neither an asyncResult.error, nor an asyncResult.value

## Steps to reproduce
1. Build addin from https://github.com/hbnrmx/repro
2. Sideload manifest in Outlook for Mac
3. Click on "New Message"
4. This should trigger the `OnNewMessageComposeEvent` and thus open a dialog 
(see full repro and code snippets below.)

## Link to live example(s)

Full repro at https://github.com/hbnrmx/repro

most relevant code snippets:

launchevent.js
```js
/* eslint-disable no-undef */

function onNewMessageComposeHandler(event) {
  console.log("openDialog was invoked.");

  Office.context.ui.displayDialogAsync("https://www.google.com", { asyncContext: event }, (asyncResult) => {
    console.log("this code is never reached");
    console.log("this code is never reached");
    console.log("this code is never reached");
    console.log(asyncResult);
  });
}

// IMPORTANT: To ensure your add-in is supported in the Outlook client on Windows, remember to map the event handler name specified in the manifest's LaunchEvent element to its JavaScript counterpart.
// 1st parameter: FunctionName of LaunchEvent in the manifest; 2nd parameter: Its implementation in this .js file.
if (Office.context.platform === Office.PlatformType.PC || Office.context.platform == null) {
  Office.actions.associate("onNewMessageComposeHandler", onNewMessageComposeHandler);
}

```

from manifest.xml:
```xml
<!-- Event-based activation happens in a lightweight runtime.-->
<Runtimes>
  <!-- HTML file including reference to or inline JavaScript event handlers.
      This is used by Outlook on the web and Outlook on the new Mac UI. -->
  <Runtime resid="WebViewRuntime.Url">
    <!-- JavaScript file containing event handlers. This is used by Outlook on Windows. -->
    <Override type="javascript" resid="JSRuntime.Url"/>
  </Runtime>
</Runtimes>
```

```xml
<ExtensionPoint xsi:type="LaunchEvent">
  <LaunchEvents>
    <LaunchEvent Type="OnNewMessageCompose" FunctionName="onNewMessageComposeHandler"/>
  </LaunchEvents>
  <!-- Identifies the runtime to be used (also referenced by the Runtime element). -->
  <SourceLocation resid="WebViewRuntime.Url"/>
</ExtensionPoint>
```

```xml
<bt:Urls>
  <bt:Url id="Commands.Url" DefaultValue="https://localhost:3000/commands.html" />
  <bt:Url id="Taskpane.Url" DefaultValue="https://localhost:3000/taskpane.html" />
  <bt:Url id="WebViewRuntime.Url" DefaultValue="https://localhost:3000/commands.html" />
  <!-- Entry needed for Outlook on Windows. -->
  <bt:Url id="JSRuntime.Url" DefaultValue="https://localhost:3000/launchevent.js" />
</bt:Urls>
```

## Context
On first startup of Outlook, my company would like to generate a custom email signature based on the users preferences (decided on by the user in a custom "Get Started" dialog). Thank you!

## Useful logs
No response from `displayDialogAsync`

**Comment by avisheknand** [comment]
@hbnrmx , i think there are limitation on event based addin and one of them is opening dialogs. Read this article : https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest#event-based-activation-behavior-and-limitations

**Comment by exextoc** [comment]
@hbnrmx, as @avisheknand pointed out, the `displayDialogAsync` API is not supported for Event-Based Add-ins. We track Outlook add-in feature requests on our [Tech Community Page](https://aka.ms/M365dev-suggestions). Please submit a request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
