### ISSUE TITLE
How can I access to microphone in office add-in ?

### ISSUE THREAD

**Issue by akshayd3v** [OfficeDev/office-js#3051]
I want to publish a add in which uses microphone access but is there microphone access feature available for Ms office

**Comment by keyur32** [comment]
Thanks for your question, however this forum is for issues with our product or documentation, not for programming questions about your code. We suggest you go to [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/office-js-dev.html) <change tag if appropriate> and see if your question has already been asked or ask a new question. 

Thanks, Microsoft 365 Developer Platform team
