### ISSUE TITLE
User has IE11 User Agent when expecting Edge

### ISSUE THREAD

**Issue by gummybuns** [OfficeDev/office-js#3053]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
A user of our Add-in has an internal browser of IE11 although according to the [OfficeJS Documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins) the user _should_ be using Edge (Chrome Based)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2102 (Build 13801.21004)
* Operating System: Windows 10.0.19044
 
## Expected behavior
The user should be running the add-in using Edge as the internal browser

## Current behavior
According to our debugging logs, the user has `Trident` is in the user agent string [which can identify IE11 as the browser](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11?tabs=ie#determine-the-browser-the-add-in-is-running-in-at-runtime).

## Steps to reproduce
It seems to be something specific to the user's environment.

## Link to live example(s)
N/A
If there is a way to privately share a screen recording we can provide our support call.

# Provide additional details
N/A

## Context
User's organization is accusing our product of being buggy with poor performance. We officially do not support versions that use IE11.

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Here is a screenshot of the Outlook Version
<img width="457" alt="Screen Shot 2022-12-20 at 12 41 29 PM" src="https://user-images.githubusercontent.com/47437711/208735752-c042f362-48c8-441d-a477-2a39ca8dcc87.png">

Here is a screenshot of the OS Version.
Note - in this screenshot you can see that Edge is installed on the computer (it is pinned in the Taskbar at the bottom)
![image-20221122-202408](https://user-images.githubusercontent.com/47437711/208736115-39dc03be-3556-49a4-8b51-0a491adcb984.png)

Here is a screenshot of our add-in. We have a debugging view that spits out everything that gets logged to the console. Highlighted in red is the user agent string
<img width="358" alt="Screen Shot 2022-12-20 at 12 42 41 PM" src="https://user-images.githubusercontent.com/47437711/208736225-9892976f-2fe7-4abf-a1a8-6a739785ae9f.png">

Here is a [link to our manifest](https://addin.grooveapp.com/manifest.xml). It does not include the `<Runtimes>` tag.

**Comment by gummybuns** [comment]
> On Windows versions prior to Windows 11, the WebView2 control must be installed so that Office can embed it. It's installed with Microsoft 365, Version 2101 or later, but it isn't automatically installed with Microsoft Edge. If you have an earlier version of Microsoft 365, use the instructions for installing the control at [Microsoft Edge WebView2 / Embed web content ... with Microsoft Edge WebView2](https://developer.microsoft.com/microsoft-edge/webview2/). On Microsoft 365 builds before 16.0.14326.xxxxx, you must also create the registry key HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\WEF\Win32WebView2 and set its value to dword:00000001.

This is the case I have not yet verified. Is this suggesting that if the registry key is missing it will fall back to IE11?

**Comment by keyur32** [comment]
Hi there, thanks for the report, assigning to @croicu for input to ensure you have the configuration to use WebView2.
