### ISSUE TITLE
Word: Insert with inserthtml and bookmark the range -getBookmarkRange does not return the entire range (web)

### ISSUE THREAD

**Issue by lynneosmith** [OfficeDev/office-js#3054]
Using the Word client, user insertHtml to insert simple HTML. This returns a range. Bookmark this range. Then, access the bookmark by using getBookmarkRange. It returns a bookmarked area that is one character short. This works correctly on desktop Word. Works incorrectly on the web client for Word. This means if I delete the range returned from getBookmarkRange, it is leaving behind a character that was added with insertHTML and that was in the original range I bookmarked.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
If I insertText and then bookmark the returned range and check it's length... and then use getBookmarkRange to access that range later by using it's bookmark name and check that length, they are the same.
If I insertHTML and then bookmark the returned range and check it's length... and then use getBookmarkRange to access that range later by using it's bookmark name and check that length, it is one character short. As a result, when I delete that range and that bookmark, it leaves behind characters in the document that I originally inserted with insertHTML. I would expect getBookmarkRange to return to me the same range, the same length, that I bookmarked originially.

## Current behavior
If I insertHTML and then bookmark the returned range and check it's length... and then use getBookmarkRange to access that range later by using it's bookmark name and check that length, it is one character short. As a result, when I delete that range and that bookmark, it leaves behind characters in the document that I originally inserted with insertHTML. I would expect getBookmarkRange to return to me the same range, the same length, that I bookmarked originially.

I expect getBookmarkRange to return the range that I bookmarked... and the length should be the same. This works correctly on desktop.

## Steps to reproduce
Using Scriptlab, insert the following content behind a button. I replaced the text in your addPreStyledFormattedText() sample.
Start with an EMPTY document on Word on the web.

async function addPreStyledFormattedText() {
  await Word.run(async (context) => {
    const myrange = context.document.getSelection();
    const tableHtml: string = '<strong>This is text inserted with body.insertHtml()</strong>';
    const sentence = myrange.insertHtml(tableHtml, Word.InsertLocation.replace);
    await context.sync();

    // Check the length of the range that was returned from insertHTML.
    sentence.load(['text', 'text/length']);
    await context.sync();
    console.error('Range text is:', sentence.text);
    console.error('Range length after insertion is:', sentence.text.length);
    // Bookmark it.
    sentence.insertBookmark('mybookmark');
    await context.sync();

    // Find the range we just added using it's bookmark and check the length of the range
    // that is returned. It will be one character shorter than the range we bookmarked! This works
    // correctly on desktop Word.
    const newRange: Word.Range = context.document.getBookmarkRangeOrNullObject('mybookmark');
    newRange.load(['text', 'text/length']);
    await context.sync();
    console.error('Range text after get from bookmark is:', sentence.text);
    console.error('Range after get from bookmark:', newRange.text.length)
  
  });
}

**Look at your output in the console:**
This is text inserted with body.insertHtml()
Range length after insertion is:
45

Range text after get from bookmark is:
This is text inserted with body.insertHtml()
Range after get from bookmark:
44

## Context
We are trying to insert report content into the Word document at various positions. We then bookmark the content. When the report content in our app is updated, we use the bookmark to locate the corresponding content in the Word document and update it. Since the bookmark length is not consistent between insertion and accessing it later, then our ability to manipulate content inline is Word does not work well and is not suitable for our customers. This all works smoothly in Word desktop.

Range text is:
This is text inserted with body.insertHtml()
Range length after insertion is:
45

Range text after get from bookmark is:
This is text inserted with body.insertHtml()
Range after get from bookmark:
44

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by jingxuan0109** [comment]
@lynneosmith the fix of this issue has been deployed to production. Could you please try your scenario? Thank you for letting us know about this issue.

**Comment by lynneosmith** [comment]
@jingxuan0109 I verified this is working correctly on Word on the web now. Thank you!

**Comment by jingxuan0109** [comment]
Thank you @lynneosmith for double confirm. I will close this issue. @penglongzhaochina @RuizhiSunMS FYI.
