### ISSUE TITLE
[Outlook for Mac] Get wrong signature src when using makeEwsRequestAsync

### ISSUE THREAD

**Issue by Howard-Song** [OfficeDev/office-js#3055]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **Mac**
* Host [Excel, Word, PowerPoint, etc.]: **Outlook**
* Office version number: **16.68**
* Operating System:  **Mac OS 12.2.1**
* Browser (if using Office on the web): ______
 
## Expected behavior

Get signature src as inline attachment, when using `makeEwsRequestAsync` to get email item
![image](https://user-images.githubusercontent.com/28775661/208800531-564d4774-723b-42c8-a9b5-5c690c8bfda8.png)

## Current behavior

**Sometimes**, the signature in email body will return the local cache path, and no inline attachment. It's not easy to reproduce, but I have met this in script lab many times. Please take a look, we need to get real email body from ews to handle inline attachment.
![image](https://user-images.githubusercontent.com/28775661/208800413-72ff3e41-bc22-4695-a2f0-65699ff5c2e8.png)

## Steps to reproduce

1. Create a new message
2. Insert a signature which includes a picture
3. Open script lab and run the following code:
```javascript
$("#run").click(() => getItem());

async function getItem() {
Office.context.mailbox.item.saveAsync(result=>{
  const emailTemplate = `<?xml version="1.0" encoding="utf-8"?>
			<soap:Envelope xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
				xmlns:xsd="https://www.w3.org/2001/XMLSchema"
				xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
				xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
				<soap:Header>
					<RequestServerVersion Version="Exchange2007_SP1" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" soap:mustUnderstand="0" />
				</soap:Header>
				<soap:Body>
					<GetItem xmlns="http://schemas.microsoft.com/exchange/services/2006/messages">
						<ItemShape>
							<t:BaseShape>AllProperties</t:BaseShape>
						</ItemShape>
						<ItemIds><t:ItemId Id="${result.value}"/></ItemIds>
					</GetItem>
				</soap:Body>
			</soap:Envelope>`;
  Office.context.mailbox.makeEwsRequestAsync(emailTemplate,(result)=>{
    console.log(result.value)
  })
});
  
}
```

**Comment by exextoc** [comment]
@JesseHeisenberg We are unable to reproduce the issue on our end. Can you please be more specific with the repro steps, on what condition are you facing the issue? 

And a short video of the issue can be very helpful in debugging.

**Comment by Howard-Song** [comment]
@exextoc I am currently unable to reproduce the same, if this happens, what could be the reason? How can we prevent similar problems?

**Comment by exextoc** [comment]
Thank you for reporting the issue. It would be difficult to root cause it without repro. Please reopen the ticket with clear repro steps if you face the issue again.

**Comment by Howard-Song** [comment]
Hi @exextoc, I find a stable way to reproduce this issue. After get email body and use body.setAsync to reset body, the image in email body and get from **EWS** will be changed to local cache path. Please reopen this issue, and take a look. Thanks for your help.

**Version:**
![image](https://user-images.githubusercontent.com/28775661/210720920-00e807e5-aae6-4786-9c29-f984a64e5e52.png)

**Step:**
1. Insert a signature in email body(signature has image)
2. Run this code in script lab

```
Office.context.mailbox.item.body.getAsync('html',res=>{
    Office.context.mailbox.item.body.setAsync(res.value,{ coercionType: 'html' },result=>{
			Office.context.mailbox.item.saveAsync(result=>{
				const emailTemplate = `<?xml version="1.0" encoding="utf-8"?>
						<soap:Envelope xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
							xmlns:xsd="https://www.w3.org/2001/XMLSchema"
							xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
							xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
							<soap:Header>
								<RequestServerVersion Version="Exchange2007_SP1" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" soap:mustUnderstand="0" />
							</soap:Header>
							<soap:Body>
								<GetItem xmlns="http://schemas.microsoft.com/exchange/services/2006/messages">
									<ItemShape>
										<t:BaseShape>AllProperties</t:BaseShape>
									</ItemShape>
									<ItemIds><t:ItemId Id="${result.value}"/></ItemIds>
								</GetItem>
							</soap:Body>
						</soap:Envelope>`;
				Office.context.mailbox.makeEwsRequestAsync(emailTemplate,(result)=>{
					console.log(result.value)
				})
			});
	})
})

``` 
![image](https://user-images.githubusercontent.com/28775661/210720305-4ffbf543-0a57-4d76-b744-7fbc3dbcbef8.png)

**Comment by Howard-Song** [comment]
Hi @exextoc, can we reopen this issue? I find a stable way to reproduce this issue, please take a look.

**Comment by ajays-msft** [comment]
This forum is limited to supporting office-js apis. For any ews specific queries, please get help from the forum as that is mentioned in the EWS documentation https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/start-using-web-services-in-exchange
https://social.technet.microsoft.com/Forums/en-US/home?forum=exchangesvrdevelopment
