### ISSUE TITLE
[Excel]How to change the transparency of the chart?

### ISSUE THREAD

**Issue by laysrain** [OfficeDev/office-js#3056]
## Post how-to questions about your code on Microsoft Q&A

How can i change the transparency of chart, The chartType like Area, RadarFilled ?
I can not find the right Api of excel.

**Comment by yuc014** [comment]
Hi @laysrain,

To my knowledge, transparency is not support yet. For new feature request, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.
