### ISSUE TITLE
displayDialogAsync do not work with SPA on mobile

### ISSUE THREAD

**Issue by r4m** [OfficeDev/office-js#3057]
I've a single page application in React in which I've set the following route `https://localhost:3000/#/auth-start?client_id=xxx&redirect_url=yyy ` to be passed to the `Office.context.ui.displayDialogAsync` method as the start address.

It works fine on web, but it fails instead on Outlook mobile giving a `Cannot GET /&action=displayDialog` error.

To test on mobile the localhost:3000 had been replaced with an ngrok url.

## Your Environment
* Platform: Android on Samsung S9+
* Host: Outlook
* Office version number: 4.2247.1
* Operating System: Android G965FXXUHFVG4
 
## Expected behavior
Being able to go through a login flow on Android even in the context of a React application that it is using HashRouting, invoking `Office.context.ui.displayDialogAsync` in the way it can handle hashed urls. 

## Current behavior
On mobile the url provided to `Office.context.ui.displayDialogAsync` is not interpreted correctly, when instead on Outlook for Mac it works nice.

## Steps to reproduce
1. Provide to `Office.context.ui.displayDialogAsync` a url with an hashpath, e.g. `https://localhost:3000/#/login`
2. It should return a `Cannot GET /&action=displayDialog` error

**Comment by exextoc** [comment]
@r4m Thanks for reporting the issue. Can you please share the manifest file and a code snippet on how you are invoking the displayDialogAsync API? If it's private, please send the details to "OutlookExtensibility@M365x27035562.onmicrosoft.com".

**Comment by r4m** [comment]
Sure, I send you the details privately to OutlookExtensibility@M365x27035562.onmicrosoft.com

**Comment by exextoc** [comment]
@r4m We are able to open the URL with a hash[#], and we are unable to repro the issue stated on our end. Can you please share a small video of the bug, so that we can make sure we are on the same page?

And kindly refer -  https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-best-practices#best-practices-for-using-the-office-dialog-api-in-an-spa

**Comment by r4m** [comment]
@exextoc with the workaround of adding a static page as reported in the best practices it worked nicely, thanks.
