### ISSUE TITLE
Excel Addin can not display all my addin

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#3058]
My client said ,She has both plug-ins installed(pacvue, pacvue commerce), but whenever she logs in, sometimes it will show the Pacvue Commerce plug-in, and sometimes it will show the pacvue plug-in.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __PC desktop____
* Host [Excel, Word, PowerPoint, etc.]: _excel_____
* Office version number: ___office 365___
* Operating System: __win 10____
* Browser (if using Office on the web): ______
 
![image](https://user-images.githubusercontent.com/3963826/208917938-36677b4f-3c9a-4342-8421-163646c6d539.png)
![image](https://user-images.githubusercontent.com/3963826/208917971-bbc4dcbe-00e9-4849-a2b8-14f55519a845.png)

**Comment by keyur32** [comment]
Hi there, thank you for logging this issue. 

I believe we will need more information from the customer. Are you able to ask the customer to file a support ticket through their organization? This will allow our support engineers to collect logs from their machine securely so we can determine what is causing the add-ins to load differently.

Also, can you indicate how those add-ins where installed? Where both installed by their admin or manually through the store?

**Comment by dinglicoding** [comment]
@keyur32  thanks,  i will let my customer try it, those add-ins installed from excel office add-ins store

**Comment by keyur32** [comment]
Thank you for following up with Customer through their support channel so we can collect feedback, as this will allow us to investigate our customers are having.

**Comment by keyur32** [comment]
Please re-activate this issue if you still need further assistance here. Thank you!
