### ISSUE TITLE
Webview2 caching prevents enterprise deployment of office addin upgrades

### ISSUE THREAD

**Issue by tanyajenkin21** [OfficeDev/office-js#3059]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Word, Powerpoint
* Office version number: Office 2021 LTSC MSO 16.0.14332.20431 64-bit
* Operating System: Windows 10 Enterprise
* Browser (if using Office on the web): n/a - WebView2
 
## Expected behavior
When our office add-in code is updated on our server, we expect the enterprise users to be accessing the updated code automatically.

## Current behavior
WebView2 caches the previous version of the code.   There is no group policy option to prevent this.  It requires a brute force edit of the registry, or manual removal of local app data, or repeat manual resetting of a Trust Center setting which does not persist.

## Steps to reproduce
1.  Load locally-served add-in into desktop Word, close Word.
2.  Upgrade the add-in code on the local server.
3.  Reopen Word and reopen the add-in.  The old cached code will be running.

# Provide additional details
The relevant Trust Center setting is on the Trusted Web Add-in Catalogs page: 'Next time Office starts, clear all previously-started web add-ins cache.'  However this is automatically cleared after each time it is exercised, i.e. if Word detects a previously loaded add-in and this option is ticked set, then the WebView2 cache is cleared but this option is also unset, rather than persisting for next time.

## Context
This issue means every user has to navigate to and reset the Trust Center setting every time the add-in code is updated.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuizhiSunMS** [comment]
Has forward the issue to others. Please wait for their investigation.
