### ISSUE TITLE
Getting error code 9057 when saving settings

### ISSUE THREAD

**Issue by thomasdarde** [OfficeDev/office-js#3060]
When updating user's settings via Office.context.roamingSettings.set
I get this weird error on some Outlook Desktop up to date software.
can't update settings {"status":"failed","error":{"name":"Internal Error","message":"An internal error has occurred.","code":9057}} 

I can't find any documentation

**Comment by exextoc** [comment]
@thomasdarde Thanks for reporting the issue. Can you please be more specific on which platform [with version details] are you facing this issue and repro steps if possible? It would help us to debug better.

**Comment by thomasdarde** [comment]
It happens on the client's computer so hard to give much more details.
Is error code 9057 registered somewhere ? Or I'm mistaken and it's not originating from the addin ?

**Comment by exextoc** [comment]
@thomasdarde 
1. Error 9057 is not published in our public docs. We will update our docs with this and other error code descriptions. 
2. Error code 9057 means that roaming settings size exceeded its limit. Can you please tell us what is the size of roaming setting which we are trying to save? As per our [docs](https://learn.microsoft.com/en-us/javascript/api/outlook/office.roamingsettings?view=outlook-js-preview), 32KB size of roaming settings is allowed.

**Comment by lindalu-MSFT** [comment]
@exextoc @thomasdarde I updated the error codes doc with error discription. We'll review and merge after the holiday break! Thanks, Linda

**Comment by thomasdarde** [comment]
Thanks ! I hope you all have a nice break ,
The issue we have is that once the 32kb limit is "full" we can't delete it's content.
Is there a method call to list or erase any settings linked to one application  ?

**Comment by exextoc** [comment]
It should be possible to erase any settings with [remove API](https://learn.microsoft.com/en-us/javascript/api/outlook/office.roamingsettings?view=outlook-js-preview#outlook-office-roamingsettings-remove-member(1)). Can you please try using that in your add-in?

**Comment by thomasdarde** [comment]
Remove API takes a string as paramater.
So we need to know before hand the name of the setting we want to remove.
Is their a way to list existing settings ?

**Comment by thomasdarde** [comment]
Hi, any update on this? Is their a way to list existing settings ?

**Comment by JuaneloJuanelo** [comment]
There is no way to enumerate your roamingSettings, You could have one tracking the names you used previously.
You are getting that error when you set a setting so you should have that info when getting the error to remove it or replace it with a less large value.

**Comment by thomasdarde** [comment]
Thanks @JuaneloJuanelo , but the settings all share the same memory isn't it ?
If we have a setting "nameunknown" using the whole memory, then when we won't be able to create "setting1" . Neither to delete the "nameunknown" (as we don't know it's name) a `clearAllSetting` would help ! 
(and we did what you suggest but a bit too late for our first users)
