### ISSUE TITLE
Smart Alerts (onMessageSend) not working in Outlook Web

### ISSUE THREAD

**Issue by Francisco-Vios** [OfficeDev/office-js#3063]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hello, I am using Smart Alerts to send additional information in the body of the email at the time of sending. I managed to get it to work in Outlook on the desktop (Windows 10), but when I switch to Outlook Web (modern Outlook UI) the Smart Alert (onMessageSend) is not triggered.

**Comment by erayc-msft** [comment]
Hello - thanks for your question.  Can you confirm which version of Exchange you using?  Thanks!

**Comment by Francisco-Vios** [comment]
@erayc-msft Microsoft Exchange Server 2016

**Comment by avisheknand** [comment]
Hi,

I am also having similar issue, the smart alert (onMessageSend) event works on Desktop for Outlook but DOES NOT work on OWA. We are using Microsoft 365 Exchange.

We already have an [Addin](https://appsource.microsoft.com/en-us/product/office/wa200004967?tab=overview) out there live for users which will affect them now.

Can you please give some priority to this.

**Comment by JuaneloJuanelo** [comment]
> art alert (onMessageSend) event works on Desktop for Outlook but DOES NOT work on OWA. We are using Microsoft 365 Exchange.

@Francisco-Vios  Smart alerts are NOT supported in Exchange on Prem,

**Comment by Francisco-Vios** [comment]
@JuaneloJuanelo @erayc-msft Hello, I have access to two Outlook accounts, one with a subscription and one without a subscription, in Outlook Desktop the add-in works in both accounts, but when I switch to Outlook Web it only works in the account with a subscription. How can I check the Exchange version in Outlook Web?

**Comment by exextoc** [comment]
There is no direct way to check the exchange version in Outlook web. To check whether it's onPrem, can you please share the response of the GetExtensibilityContext call from the network trace and also the URL with which you are trying to access the Outlook Web?

**Comment by Francisco-Vios** [comment]
Follow link with response of the `GetExtensibilityContext` call from the network: https://github.com/Francisco-Vios/add-in-Outlook/blob/main/GetExtensibilityContext.json

The Outlook web access URL used is: https://outlook.live.com/mail/0/

**Comment by avisheknand** [comment]
Hi,

I am using Exchange online with MS 365 E3 plan for our normal company account and MS 365 E5 plan for our developer account. The smart alert onMessageSend is not working on any of the accounts OWA. It works on Desktop only.

I have made an video from my normal account. Here is the [Video](https://standss-my.sharepoint.com/:v:/p/nanda/EXlcAk3dEIhGpb_8DfG254AB2FdbN2x8TyvNveOFW29Uow?e=lBolFZ)

**Comment by exextoc** [comment]
Hey @avisheknand, @Francisco-Vios 

- Was this working previously and stopped working recently?

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding Smart Alerts (onMessageSend/onAppointmentSend) not working in Outlook Web. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: [186305]

**Comment by Francisco-Vios** [comment]
@exextoc It's the first time I'm developing an add-in for Outlook.

**Comment by avisheknand** [comment]
@exextoc , yes it was working previously ( later December and early Jan) ... any updates on the issue would be appreciated
