### ISSUE TITLE
portal.office.com, page App permissions does not work

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#3067]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

For some reason, we cannot revoke permissions, the [https://portal.office.com/account/?ref=MeControl#apps](https://portal.office.com/account/?ref=MeControl#apps) page does not work, we have checked it with different Microsoft accounts from different tenants. Could you please check it on your side?

Also, could you please point me to the right place for submitting such bugs?

## Your Environment
* Platform: PC desktop & Mac
* Host: ______
* Office version number: ______
* Operating System: Windows 10 22H2 & macOS Ventura Version 13.1
* Browser (if using Office on the web): Chrome, Edge, Safari
 
## Current behavior
The page opens, infinite "Please wait" is shown, please see the screenshot below.

![image](https://user-images.githubusercontent.com/28924916/210517012-609fee36-2990-4db6-9af6-3b1fcdf7722f.png)

**Comment by penglongzhaochina** [comment]
hi @DmitryKostochko, You submitted the issue in a wrong channel. This channel is not for the portal.office.com.

**Comment by DmitryKostochko** [comment]
hi @penglongzhaochina.
Thank you, I know that this channel is not for portal.office.com, but I cannot find any suitable channel to submit this bug. Could you please point me to such support channel?

Also, if it is not a problem for you - could you please try to open the App permissions page on your side. Does it work for you? The point is that we tried opening it from different locations and different organizations - it does not work in all cases, it seems to be a global problem.

**Comment by eugene-plutoflume** [comment]
> hi @penglongzhaochina. Thank you, I know that this channel is not for portal.office.com, but I cannot find any suitable channel to submit this bug. Could you please point me to such support channel?
> 
> Also, if it is not a problem for you - could you please try to open the App permissions page on your side. Does it work for you? The point is that we tried opening it from different locations and different organizations - it does not work in all cases, it seems to be a global problem.

You may also try posting this to [StackOverflow ](https://stackoverflow.com/) or [SuperUser](https://superuser.com/) web sites where MS employees are presented.

**Comment by christophhapple** [comment]
Hi @penglongzhaochina 

I'm also having the same problem and would love to be pointed in a more useful direction.

Seems like there should be a more official route to take than Stackoverflow or SuperUser

**Comment by penglongzhaochina** [comment]
Hi , I will send a email internally to clarify who is the owner of this issue. Thanks.

**Comment by michens** [comment]
Is this still an issue?

**Comment by DmitryKostochko** [comment]
@michens, it seems the issue is fixed, thank you.
