### ISSUE TITLE
Disable App Feedback Popup

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js#3068]
Hi, we have noticed a change that MS seems to be adding a 'feedback' popup overlay in our addin taskpane - is it possible to disable this (via cookie, local storage etc), it's interfering with our automated end to end tests.

**Comment by AlexJerabek** [comment]
Thanks for reporting this @theboyknowsclass.

@Wenjun-Gong, could you please help find someone to investigate this issue?

**Comment by Wenjun-Gong** [comment]
Hi @theboyknowsclass , which Office app did you see this popup? Could you share the popup screenshot to help us isolate the issue? Thanks.

**Comment by nkkinariwala** [comment]
Hello @theboyknowsclass - can you please provide more details as Wenjun asked?
