### ISSUE TITLE
[Outlook] No notification found to remove later when added on Mac desktop using OnCompose command

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#3069]
We are adding a notification to the compose window using the OnCompose hook to notify a user of not being authenticated. After they open the add-in and authenticate, we want to remove the notification using the same key we used to create the notification.

This works fine in OWA. But on Mac desktop, an error is thrown when ```Office.context.mailbox.item.notificationMessages.removeAsync``` is called and it says no notification with that key exists.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
 
## Expected behavior
Similar to how it works in OWA, we should be able to successfully remove the notification that was added during the OnCompose hook handling at a later time.

## Steps to reproduce

(On Outlook for Mac desktop)
1. Setup an OnCompose hook and add a notification to the message using ```Office.context.mailbox.item.notificationMessages.addAsync```
2. In a Compose add-in, attempt to remove that same notification (same key) using ```Office.context.mailbox.item.notificationMessages.removeAsync```

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding notification APIs not working with AuotRun events in Outlook for Mac. We are able to reproduce the issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: [7472003]

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 16.73.23042200 or later. When an updated build is available depends on the release channel a customer is on.
