### ISSUE TITLE
"This Add-In could not be loaded with your version of office." but should be supported.

### ISSUE THREAD

**Issue by ndeeH** [OfficeDev/office-js#307]
We have a content Add-In for PowerPoint in the office store which should work with Office 2016.

Customers with Office 2016 Professional Plus (16.0.4549….) reported that they see this error:
`"This Add-In could not be loaded with your version of office. Visit the office store to find out which version..." (translated from german).`
![image](https://user-images.githubusercontent.com/11518242/49009454-e8d98200-f170-11e8-88ab-2287f39394d3.png)

The manifest only has a requirement for DialogApi:
```
  <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="DialogApi" />
    </Sets>
  </Requirements>

```
_Any ideas what causes this error on startup. 
Why should the Office 2016 Version not be supported (they updated to the latest version - no success.)_

TIA, Andi

**Comment by mvpkenlin** [comment]
it is a Task Pane App or Content App?
Mind to post more on your manifest?

**Comment by mvpkenlin** [comment]
You can find the supported version of Office here, 
https://docs.microsoft.com/zh-tw/office/dev/add-ins/reference/requirement-sets/dialog-api-requirement-sets?view=office-js

if you said, version 16.0.4549...... does not work, is it a C2R installes rather than MSI install? for C2R installs, you need 16.0.6741.... or above

![image](https://user-images.githubusercontent.com/20411183/49129128-689a5480-f309-11e8-868b-02db728d5838.png)

**Comment by ndeeH** [comment]
@mvpkenlin 
> it is a Task Pane App or Content App?

**It is a powerpoint content app**

> Mind to post more on your manifest?
```
<OfficeApp>

  <!-- private -->

  <Hosts>
    <Host Name="Presentation" />
  </Hosts>
  <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="DialogApi" />
    </Sets>
  </Requirements>
  <DefaultSettings>
    <SourceLocation DefaultValue="https://<my url>" />
    <RequestedWidth>800</RequestedWidth>
    <RequestedHeight>450</RequestedHeight>
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>
</OfficeApp>
```

**Comment by ndeeH** [comment]
@mvpkenlin 
It is a **MSI installation** - so **16.0.4549** is higher than required **16.0.4390** - so it should work - but it does not!

![image](https://user-images.githubusercontent.com/11518242/49154907-ed8d6a00-f319-11e8-96e0-fa5791d81b5b.png)

**Comment by kbrandl** [comment]
@JuaneloJuanelo are you able to provide any input about this issue? (Please let me know if this should be directed to someone else.)

**Comment by ndeeH** [comment]
@JuaneloJuanelo FYI - our customer is wondering why our [add in](https://appsource.microsoft.com/de-de/product/office/WA104381814?tab=Overview) is not available though the version of Powerpoint (16.0.4549 MSI) should support it.
If you need more information let me know...

**Comment by ndeeH** [comment]
@JuaneloJuanelo @kbrandl Any new information for us or what to test at the customer site?

**Comment by JuaneloJuanelo** [comment]
@danielgwilson need to verify that Dialog API works on 2016 MSI on PPT.

**Comment by sumurthy** [comment]
The PR is under review: https://github.com/OfficeDev/Office-Js-Requirement-Sets/pull/43/files

**Comment by sumurthy** [comment]
@lliu113 - could we address this? Seems like we made an attempt at this but got closed before we fixed the issue. https://github.com/OfficeDev/Office-Js-Requirement-Sets/pull/64/files

**Comment by lliu113** [comment]
@ndeeH  - I know this is historic, are you still seeing this problem with your users?

**Comment by lliu113** [comment]
@ndeeH  - I'm going to close this for now, please reactivate if you're still able to repro this.
