### ISSUE TITLE
Word Office on Web crashing inserting HTML with office.js

### ISSUE THREAD

**Issue by NordicLight** [OfficeDev/office-js#3070]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Inserting the attached html file works fine in Word Mac (platform Mac) but crashes online (platform OfficeOnline). We have not tested on Windows but we make the assumption that Windows is also ok. In general working with html seems very solid on Mac but very shaky online...

The attached file is a the text string in preview
context.document.body.insertHtml(preview, Word.InsertLocation.end);
 await context.sync();

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac (is ok), Office on the web is crashing
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.67
* Operating System: Monterey
* Browser (if using Office on the web): Tested with both Chrome and Safari
* Office.js version
    <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
 
## Expected behavior
Office on web should work as Office on Mac e.g. not crahsing

## Current behavior
Office.js crashes inserting the text 

## Steps to reproduce
1. Create a office.js word addon
2. Read the file as a text string
3. Add to your html document in html as above (Office web)

## Context
We are writing a office.js add-on that populates Jira information into Word documents

**Error Image**
<img width="465" alt="Screenshot 2023-01-05 at 00 04 04" src="https://user-images.githubusercontent.com/9700899/210668409-50a2b66f-6e45-4342-ace1-bceb83ebdcb9.png">

**Html file available at**
[https://jpdf-resources.s3.eu-west-1.amazonaws.com/error/word-error-online.html](url)

**Comment by jingxuan0109** [comment]
Thank you for letting us know this issue. I am just wondering whether this happens every time. I cannot reproduce this bug. All I meet is that after running insert html, it always on saving status and no crash dialog popup. I am just wondering whether you can provide more information like, sessionID(under file button->about), code or a video.

**Comment by NordicLight** [comment]
Thank you for the replay! The problem happens every time with the provided template and below you find the code on your request. Is there any other information I should provide?

    onClick = async (item: any) => {
        return Word.run(async (context) => {
            try {
                this.state.showProgress = true;
                this.setState(this.state);

                var isCompanyTemplate = true;
                if(this.state.selectKey == "store"){
                    isCompanyTemplate = false;
                }

                //load template
                var template = await Rest.getTemplate(item, isCompanyTemplate);

                //clear document
                context.document.body.clear();
                await context.sync();

                //insert template
                context.document.body.insertHtml(template, Word.InsertLocation.end);
                
                await context.sync();
                Global.TemplateRestore = "";
                
            } catch (err) {
                this.showErrorMessage(err, 1);
            }
            this.state.showProgress = false;
            this.setState(this.state);
        });
    }

**Comment by eunzycjlqt7911** [comment]
I can also reproduced this issue, it happens once the html includes table content
