### ISSUE TITLE
Break links in excel custom functions

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#3072]
Hi,

Is there a way to use break link (Data -> Edit links -> Break link) for a custom excel formula?

Thanks

**Comment by donlvMSFT** [comment]
Thanks for letting us know this issue. 

However, currently, the feature: Break links in excel custom functions, you requested, is not a part of the product. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests are considered when we go through our planning process. 

Thanks, Microsoft 365 Developer Platform team
