### ISSUE TITLE
CustomFunction HelpURL from fx dialog points to "COUNT" function manual

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#3073]
Hi,

I've seen there is an issue when I have a helpURL set for a custom function and if you open the helpURL from the fx wizard and search for the custom function and then click on helpURL.

- It should point you to the helpURL of the custom function, but instead it will navigate you to the `COUNT` function manual

It works perfectly if I just go to Formulas-Insert formula and click on helpURL.

Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: Excel
Office version number: 2206 (Build 15330.20266)
Operating System: Windows 10 
Browser (if using Office on the web): ______

**Comment by erayc-msft** [comment]
Hello - thank you for reporting this issue regarding Custom Functions.  Can you provide additional information on your environment and detailed steps to reproduce?  That will help us better confirm the places that are showing the wrong helpUrl.  

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Steps to reproduce
1. ______
2. ______
3. ______
