### ISSUE TITLE
Word on Web leaves part of bookmarked table in document when delete range from getBookmarkRangeOrNullObject 

### ISSUE THREAD

**Issue by lynneosmith** [OfficeDev/office-js#3074]
Using the API to insert a table, then get the table range and insert a bookmark for it. Then use getBookmarkRangeOrNullObject to find the bookmarked range and delete it. On Word on the Web, empty cells of a table are left behind. Works perfectly on desktop.
If you select the range returned from getBookmarkRangeOrNullObject, you can see that the ranged includes the entire table as expected.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
If I get a bookmarked range and then do range.delete(), I expect the entire range to be deleted on Word on the web the same way that it is on the desktop. I do not expect empty table cells to be left behind.

## Current behavior
Empty table cells are left behind in the document.

## Steps to reproduce
Reproduce in ScriptLab.
Replace the code in the "Create and access a table" sample , the "insertTable() function" with the following:
async function insertTable() {
  await Word.run(async (context) => {
    // Use a two-dimensional array to hold the initial table values.
    const data = [
      ["Tokyo", "Beijing", "Seattle"],
      ["Apple", "Orange", "Pineapple"],
      ["One", "Two", "Three"]
    ];
    const table = context.document.body.insertTable(3, 3, "Start", data);
    await context.sync();

    const range = table.getRange();
    range.insertBookmark('mybookmark');
    await context.sync();

    // Find the bookmarked range by using the bookmark name.
    const refRange: Word.Range = context.document.getBookmarkRangeOrNullObject("mybookmark");
    await context.sync();
     
    // If you select the range here, you will see the entire table selected, so the bookmark returned the full table.
    // refRange.select();

    // After this delete, Word on the Web leaves table cells around and does not delete the entire table. Word on desktop 
    // correctly deletes the entire table.
    refRange.delete();
    context.document.deleteBookmark("mybookmark");
    await context.sync();
  });
}

IF YOU CHANGE THE ABOVE CODE TO THE FOLLOWING CODE, YOU WILL SEE THAT THE RANGE CAN BE DELETED IF THE BOOKMARK IS NOT USED TO FIND IT.
async function insertTable() {
  await Word.run(async (context) => {
    // Use a two-dimensional array to hold the initial table values.
    const data = [
      ["Tokyo", "Beijing", "Seattle"],
      ["Apple", "Orange", "Pineapple"],
      ["One", "Two", "Three"]
    ];
    const table = context.document.body.insertTable(3, 3, "Start", data);
    await context.sync();

    const range = table.getRange();
    range.insertBookmark('mybookmark');
    await context.sync();

    // NOTE: If you delete the range at this point, it will correctly delete the entire table. 
    range.delete();
    await context.sync();
  });
}

## Context
We are trying to insert report content, which includes tables, from our pane into the Word document. We then track the content with bookmarks. If the user wants to update the report content (Table) later, then we need to be able to find the table in the document again by the bookmark name and update the table with the changes in our report content. Inserting and updating content is the purpose of our application so that users can take our content into the Microsoft Office products. We have to be able to track the content so we can correctly update it and we use bookmarks to do that.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by penglongzhaochina** [comment]
Hi, @lynneosmith  I have created work item 7471112 to track that issue internally.

**Comment by jingxuan0109** [comment]
@lynneosmith the fix of this issue has been deployed to production. Could you please try your scenario? Thank you for letting us know about this issue.

**Comment by lynneosmith** [comment]
I have verified that your fix resolves the problem for us. Thank you!

**Comment by jingxuan0109** [comment]
Thank you @lynneosmith for double confirm. I will close this issue. @penglongzhaochina FYI.
