### ISSUE TITLE
messageParent and sendMessage domain check

### ISSUE THREAD

**Issue by dm-shlandii** [OfficeDev/office-js#308]
Hi, 

There is rather strange condition in a loop which checks the current 'allowed domains'. i.e.
https://github.com/OfficeDev/office-js/blob/bdcaa766e570a4c91d1889e7dd5d84e9ff88db58/dist/outlook-web-16.01.debug.js#L8201

```
                        for(var i = 0; i < appDomains.length && appDomains[i].indexOf("://") !== -1; i++)
                            window.opener.postMessage(message,appDomains[i])
```
So on first occurrence which don't match the condition  'appDomains[i].indexOf("://") !== -1' - it will exit the loop. So the message would not be without any logging, etc.

## Expected Behavior
Either log the error about allowed domain not found or just skip the domains which don't have ";//" 

## Current Behavior
Stops on first item which don't match. 

## Steps to Reproduce, or Live Example
In add-in manifest have, for example:
```
  <AppDomains>
    <AppDomain>AppDomain1</AppDomain>
    <AppDomain>https://localhost:3000</AppDomain>
    <AppDomain>AppDomain3</AppDomain>
  </AppDomains>
```
create a dialog with Dialog api and do a sendParent call.

**Comment by exextoc** [comment]
The AppDomains should be in the format of https://<your url>, as we only support navigating to https domains. 

https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-1

**Comment by markb-trustifi** [comment]
This issue should be reopened, It is a bug.
I have these domains:
```js
<AppDomains>
   <AppDomain>https://login.windows.net</AppDomain>
   <AppDomain>https://login.microsoftonline.com</AppDomain>
</AppDomains>
```
But domains that appear in appDomains array are different and are not related to manifest.
The loop condition is built incorrect. If the first item in an array is evaluated as **false** then the loop breaks out and doesn't check for next items.

**Comment by exextoc** [comment]
Thank you for reporting the bug. We are looking into it.
