### ISSUE TITLE
Cannot insert file from base64 for cannotDelete content control

### ISSUE THREAD

**Issue by tranhuyentran23** [OfficeDev/office-js#3080]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Your Environment

* Platform: Office Online
* Host: Word
* Office version number: 16.0.14413.41001
* Operating System: Windows 10
* Browser: Chrome
 
## Expected behavior
cannotDelete content control will be inserted successfully by insertFileFromBase64 method

## Current behavior
cannotDelete content control cannot be inserted by insertFileFromBase64 method
but it is still working well with insertText and insertHtml method

## Steps to reproduce
1. Create a new document
2. Run the attached Script lab
3. Click Create cannotDelete content control
4. Click insertFileFromBase64
5. Observe an error is thrown

![image](https://user-images.githubusercontent.com/89008454/211715413-f4cf7942-292b-4d7a-912a-07f07a9e8de2.png)

6. Click insertHtml or insertText -> data can be inserted successfully 

## Link to live example(s)
![chrome_f7tlFEvPtv](https://user-images.githubusercontent.com/89008454/211714732-6b0b3f68-8987-4fc0-bbbf-4667fcabe43f.gif)

Script Lab: https://gist.github.com/tranhuyentran23/2de43ae587c3e4b6b27fcdf342b909f9

**Comment by AlexJerabek** [comment]
Hi @tranhuyentran23,

Thank you for reporting this issue. @wangyun-microsoft, could you please investigate this?

**Comment by penglongzhaochina** [comment]
Hi, @tranhuyentran23  We have created work item to track that issue internally.
