### ISSUE TITLE
Dialog API (displayDialogAsync) does not work in Outlook event-based Add-In

### ISSUE THREAD

**Issue by guzman-rc** [OfficeDev/office-js#3085]
We are developing a feature that removes sensitive information from attachments using the event: **OnMessageAttachmentsChanged**

We need to display a modal window while processing files but Dialog API (displayDialogAsync) does not work.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Mac and Outlook on the Web.
* Host [Excel, Word, PowerPoint, etc.]: Outlook.
* Office version number: Microsoft 365.
* Operating System: Windows 10/11 and Mac Ventura 13.0.1
* Browser (if using Office on the web): Edge and Chrome
 
## Expected behavior
Open a dialog window by using:
Office.context.ui.displayDialogAsync('https://myDomain/myDialog.html', {height: 30, width: 20, displayInIframe: true});

## Current behavior
Dialog API does not work.

## Steps to reproduce

1. https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins

## Link to live example(s)

# Provide additional details

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by AlexJerabek** [comment]
Hi @guzman-rc,

Thanks for reporting this issue. @exextoc, could you please investigate?

**Comment by guzman-rc** [comment]
Hi Alex,

Is there any news on this issue?

**Comment by exextoc** [comment]
@guzman-rc, the `displayDialogAsync` API is not supported for Event-Based Add-ins. This is documented online here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest#event-based-activation-behavior-and-limitations. Displaying a modal dialog after a user has added an attachment could be intrusive. A less intrusive solution would be to add a [Notification Message](https://learn.microsoft.com/en-us/javascript/api/outlook/office.notificationmessages?view=outlook-js-preview) of type `InsightMessage` to inform the user to take an action. Upon clicking on the Notification Message, it will open a taskpane to guide the user to perform the needed steps.

**Comment by guzman-rc** [comment]
Hi,

Notification messages have **low visibility** and in many cases these notifications would not be seen by the user.

Is there a way to display a modal window to show notifications to the user?

Thanks,

**Comment by exextoc** [comment]
@guzman-rc, there isn't a way to show a modal dialog for Event-Based Add-ins. We track Outlook add-in feature requests on our [Tech Community Page](https://aka.ms/M365dev-suggestions). Please submit a request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
