### ISSUE TITLE
Performance downgrade in context.sync() Office Online when inserting big slides

### ISSUE THREAD

**Issue by FranCerrada** [OfficeDev/office-js#3087]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We have identified a substantial performance downgrade on the `context.sync` when inserting a new slide in PowerPoint Online when comparing the same behavior to Office for Windows. 

For a 27MB slide that needs to be downloaded and inserted into a new presentation using a PowerPoint Web Add-in, the download time takes around 1 to 2 seconds but the context synchronization takes up to 10 seconds. 
Doing the same operation in PowerPoint for Windows, using the same Web Add-in, the total insertion time takes up to 4 seconds.

In summary, inserting a 27MB slide into a presentation takes:

- Office Online: 1 second to download, **10 seconds to insert (sync)**.
- Office for Windows: 1 second to download, **3 seconds to insert(sync)**.

By testing with different slide sizes we've come to the conclusion that the performance is heavily impacted by the size, reaching a level that cannot be considered acceptable for our customers.

We would like, if possible, to get a technical explanation on why this has such a delay. Also, is this performance downgrade a known issue that is going to be addressed eventually?

## Your Environment
Platform: Office Online
Host: PowerPoint
Operating System: Windows 10
Browser: Chrome
 
## Expected behavior
Slide insertion in PowerPoint Online will perform well for medium/big-size slides, at least similar to what we can see in PowerPoint for Windows.

## Current behavior
The insertion time is unacceptable,

## Steps to reproduce
Try to insert a big-size slide into a presentation in PowerPoint Online.

## Context

Slide insertion using the PowerPoint JS API

**Comment by AlexJerabek** [comment]
Thanks for reporting this @FranCerrada.

@ononder, could you please investigate?
