### ISSUE TITLE
Office.context.mailbox.item.conversationId and itemId sporadically returns incorrect value

### ISSUE THREAD

**Issue by fmcgough** [OfficeDev/office-js#3093]
Opening a new issue for this as we have had more users raising this issue since #2557 was closed.

#### Description from previous issue:
We have an Outlook add-in to allow our customers to store conversations in a CRM system. This works by sending a conversation ID from the add-in to our API, which then queries the Microsoft graph API for messages matching the conversation ID. However for a small proportion of these requests, no messages are returned from the graph API.

We have recently added some additional error reporting around this scenario, recording the value of `Office.context.mailbox.item.conversationId` and `Office.context.mailbox.item.itemId`. There seem to be a couple of different things going on here - for one user, the message IDs can be used to retrieve an item from their inbox, but the conversation ID reported in the response differs from the value of `Office.context.mailbox.item.conversationId`. For another user, the graph API returns a 404 response for the message ID indicating that it belongs to a different mailbox altogether.

I haven't been able to reproduce this issue locally in my environment.

## Your Environment

* Platform: PC, Mac, web, iOS
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows, Mac, iOS
* Browser (if using Office on the web): Chrome, Edge
 
## Expected behavior

A GET request to the graph API using the conversation ID reported by `Office.context.mailbox.item.conversationId` returns at least one message.
`https://graph.microsoft.com/v1.0/me/messages?$filter=conversationId eq 'xxxxx'`

## Current behavior

In a small number of cases, 0 messages are returned.

## Additional information

We have another user now reporting that they are encountering this error for **every** conversation they try to store. This is different from the inconsistent errors reported by other users. They report that: 
- It keeps happening for new/recent messages as well as for existing ones, and that the error occurs consistently even when they re-try hours or days later
- Our error reporting shows that they are using a variety of different clients including Windows desktop, OWA and iOS
- The error occurs for messages in the Sent folder as well as for inbox messages
- It occurs regardless of whether Focus Inbox is enabled or not
- The user didn't know what we meant by "inbox rules" so it sounds like they aren't using them.

**Comment by fmcgough** [comment]
We have another user reporting the same issue, they also report that:

- It is happening on all emails, new/recent and existing
- The error persists when trying hours/days later
- Same error message for all platforms
- The error is encountered from both Inbox and Sent folder
- It occurs regardless of whether Focus Inbox is enabled
- No rules are set up on this email profile.

**Comment by ztcdsb** [comment]
Hi @fmcgough, Thanks for spending time and gathering more information for us. This kind of problem is hard to track down and it will be helpful if you can provide as much detail as possible.

1. I am assuming you're using convertToRestId JS API to convert the EWS IDs (returned from  itemId and conversationId JS APIs) to REST IDs before using them with Graph - could you please confirm that you are using it?

2. Can you provide a code snippet that does the job for retrieving conversations?

**Comment by fmcgough** [comment]
Hi @ztcdsb,

1. We are converting the ids to REST id format on the server side rather than in the add-in itself, using the following logic (in Scala):
```scala
  def convertIdToRestId(id: String): String = {
    if (id == null) {
      null
    } else {
      id.replaceAll("/", "-").replaceAll("\\+", "_")
    }
  }
```
I am fairly sure that this isn't the source of the issue, since we see conversation IDs in our error reporting that don't contain any of these characters. I inserted the following snippet into the add-in and stepped through with a browser debugger to confirm:
```javascript
    const restId = Office.context.mailbox.convertToRestId(
      conversationId,
      Office.MailboxEnums.RestVersion.v2_0
    );
    console.log(`Conversation id: ${conversationId}, rest id: ${restId}`);
```
If this turns out to be what's causing the problem I'll feel pretty silly...

2. This is the snippet we use to build a request to check if we can retrieve the conversations from the graph API (again in Scala):
```scala
      graphClient
        .me()
        .messages()
        .buildRequest(
          Query.filter(conversationFilter(conversationId), notDraftFilter),
          Query.select("id"),
          Query.limit(1),
          Header.prefer()
        )
        .get()
```
This comes out with a URL like the following (id is from my account):
```
12:15:31.752 TRACE [microsoft-graph] [32j2qypywq5br] [1] Starting to send request, URL https://graph.microsoft.com/v1.0/me/messages?%24filter=conversationId%20eq%20%27AAQkAGEwYmE3YzU1LTYxZGQtNDVmYi1iYjVjLWRkMDk0N2JjNzgxZgAQAKhRVD5t7lxNoDVwNyOdJdg%3D%27%20and%20isDraft%20ne%20true&%24select=id&%24top=1
```
We check that the response list is non-empty, and throw an exception if it is.

**Comment by ztcdsb** [comment]
@fmcgough Thanks for the information. 
Can you share with us the impact of this issue(how many users have been affected)?
If multiple users are impacted, are they all from the same company?

**Comment by fmcgough** [comment]
We have had 132 users affected by this error since we started monitoring it properly, across 91 different organisations.

**Comment by fmcgough** [comment]
Another user has reported encountering this error, bringing the total to 134. They report that:

- It happens with existing and new messages
- They encountered the error yesterday and still happening this morning
- Error is on Desktop Outlook (they don’t use the app version)
- Both Inbox and in subfolders
- Focused Inbox is not enabled
- Not using inbox rules

**Comment by ztcdsb** [comment]
@fmcgough Thanks for reporting this issue. We are actively working on reproduce it internally. Please also keep us posted if you or the customer figured out a way to consistently reproduce the issue. We unfortunately have no timelines to share at this point.
Internal tracking id: Office: 7665526

**Comment by ztcdsb** [comment]
We started a internal testing for 4 months and we are not able to repro it. Since we don't have a consistent way to report it, I will close the ticker for now, Please keep us posted if you have more findings

**Comment by Ken-Mok** [comment]
I have the same issue and here is some example...
when i retrieve conversationId from Office.context.mailbox.item.conversationId, it will return "AAQkAGYzYWQ4ZWRhLTBiNWEtNGJlOS1hMzgxLTA5MGQxMmRkOGJlMgAQAHttc85d2URirUO4F+4+Ys8="
however, the same message from graph API : "conversationId": "AAQkAGYzYWQ4ZWRhLTBiNWEtNGJlOS1hMzgxLTA5MGQxMmRkOGJlMgAQAHttc85d2URirUO4F_4_Ys8="

if we use the conversationId from Office.context.mailbox.item will return
{
    "error": {
        "code": "ErrorInvalidIdMalformed",
        "message": "Id is malformed."
    }
}

**Comment by zachhutchins** [comment]
The conversation Id is **base64 encoded**, the odd thing is that they pad the actual id with bytes, from what I can see ids are broken down by the following

* Prefix of 4 bytes (likely metadata) 
* 36 bytes (UUID) 
* Postfix of x bytes, 

I feel better at guessing the prefix length given they have to also decode this, but with no documentation I have no solid proof.

This is very odd; my guess is the 4 bytes correspond to some Enums which they only use a byte a piece for. The postfix could be anything under the sun. 

I have not found ANY documentation related to decoding functionality or what the bytes mean. I hope someone does and links to this. 

EDIT

After researching this more, although the uuid being inside that is interesting it does not matter. The graph api uses REST API Id formatting where Office JS uses EWS format. Office JS Api offers a function to convert EWS to Rest and Rest to EWS.

* Office.context.mailbox.convertToRestId, 
* Office.context.mailbox.convertToEwsId
