### ISSUE TITLE
Synchronizatino of Settings across different AddIn clients with refreshAsync

### ISSUE THREAD

**Issue by zinnen** [OfficeDev/office-js#3094]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

I have created a project via Yeoman with code in React that increments a counter via a button, displays it, and stores the value in the settings. With another button I can update the settings and update the current value of the counter to the state. The code works for one instance of the addin. If a second instance increases the counter and the value in the settings, the new value is not read out in the first instance using refreshAsync. Only on restart of the first instance the current value is read, but not at runtime using refreshAsync. When saving (saveAsync), the PowerPoint 365 document does not go into "saved", but remains in "being saved" status.

## Your Environment
* Platform Office on the web
* PowerPoint
* Office version number: Does 365 have a version number? 
* Windows and Mac
* Chrome and Safari

"dependencies": {
    "@fluentui/react": "^8.52.3",
    "core-js": "^3.9.1",
    "es6-promise": "^4.2.8",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "regenerator-runtime": "^0.13.7"
  },
  "devDependencies": {
    "@babel/core": "^7.13.10",
    "@babel/plugin-proposal-class-properties": "^7.3.0",
    "@babel/preset-env": "^7.6.3",
    "@babel/preset-react": "^7.6.3",
    "@types/es6-collections": "^0.5.29",
    "@types/office-js": "^1.0.256",
    "@types/office-runtime": "^1.0.23",
    "@types/react": "^17.0.39",
    "@types/react-dom": "^17.0.11",
    "@types/react-hot-loader": "^4.1.1",
    "@types/webpack": "^4.4.34",
    "@types/webpack-dev-server": "^4.1.0",
    "acorn": "^8.5.0",
    "babel-loader": "^8.2.2",
    "babel-polyfill": "^6.26.0",
    "copy-webpack-plugin": "^9.0.1",
    "eslint-plugin-office-addins": "^2.1.3",
    "eslint-plugin-react": "^7.28.0",
    "file-loader": "^6.2.0",
    "find-process": "^1.4.4",
    "html-loader": "^4.1.0",
    "html-webpack-plugin": "^5.5.0",
    "less": "^3.10.3",
    "less-loader": "^10.0.1",
    "office-addin-cli": "^1.5.3",
    "office-addin-debugging": "^4.6.7",
    "office-addin-dev-certs": "^1.9.3",
    "office-addin-lint": "^2.2.3",
    "office-addin-manifest": "^1.10.4",
    "office-addin-prettier-config": "^1.2.0",
    "os-browserify": "^0.3.0",
    "postcss-loader": "^4.0.0",
    "process": "^0.11.10",
    "react-hot-loader": "^4.12.6",
    "source-map-loader": "^3.0.0",
    "ts-loader": "^9.4.1",
    "typescript": "^4.7.4",
    "webpack": "^5.73.0",
    "webpack-cli": "^4.8.0",
    "webpack-dev-server": "4.7.4"
  },
 
## Expected behavior
I would expect that the settings can be synchronized across different AddIn instances. On restart of the second instance the current value is read, but not at runtime after using refreshAsync without restart. 

## Current behavior

After increasing the counter (Settings) in one instance and reading the value in the other instance (refreshAsync), the new value is not displayed. 

## Steps to reproduce

Create new React project with Yeoman. Add App.js (see attachment, please rename to App.js). Load the AddIn in two different instances of a browser (e.g. Chrome). Increase the counter in one instance. Load the new value in the other instance. The outdated value is now displayed here. 

## Link to live example(s)

[App.txt](https://github.com/OfficeDev/office-js/files/10435569/App.txt)

# Provide additional details
See sample code. 

## Context
AddIn should be used for collaboration of people. Changes made by one person should be displayed to the other person. 

## Useful logs
N/A

**Comment by jipyua** [comment]
Thank you for reporting this issue regarding ppt online api, we are now able to repro it and have opened an internal bug 7564486 to track the fix. We unfortunately have no timelines to share at this point.

**Comment by zinnen** [comment]
Another observation to consider as part of the code update and testing: Be a document with context saved in PowerPoint 365. When adding the AddIn (Insert->Add Ins->Open Manifest) with the mentioned presentation open, the context is not loaded. If you close the browser and re-open the presentation and the AddIn again, the context is loaded correctly.
