### ISSUE TITLE
Unable to open new document in separate tab in Word Online

### ISSUE THREAD

**Issue by mumarniaz** [OfficeDev/office-js#3096]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I'm working on office App for Word using Office.js and I have a taskpane on which there is a button which on click will open up a new document in a new window (new tab in case of word online). This works fine on Word desktop but somehow it is not working as expected in word online. When i try to run the same code snippet to create a new document in Word online, it is suppose to open it in a separate tab. The very strange behavior was first time it opens fine means a blank new document opened in separate tab but if on a separate tab when I open my taskpane again and click the same button to create a new document it always open it in existing tab, it never go to open it in a new tab. The document name changes which I can see from tab title but it open in same tab. Below is the sample code snippet i'm calling on click of button:

```
private openNewDocument = (title: string) => {
    Word.run(async (context) => {
      var doc = context.application.createDocument();
      await context.sync();
      doc.open();
      await context.sync();
    });
  }
```

## Your Environment
* Platform: Office on the web
* Host: Word
* Office version number: 16.0.16110.41012
* Operating System: Windows 11 Pro 21H2 22000.739
* Browser: Chrome/Edge
 
## Expected behavior
When i click on button to create document, it should open it a new document in a separate tab.

## Current behavior
It first time open a document in separate tab but then it never open in separate tab. It always open in current tab

## Steps to reproduce
1. Create a button on a taskpane.
2. On click of that button, call the above code
3. It will open a new blank document in a separate tab
4. Now in a separate tab new window, open the taskpane and click on that button again.
5. You will see it not open a new document in separate tab instead it refreshes the current tab and open new doc in the same tab.

## Context
As it works fine for desktop but not for Word online, it has a very bad impression on customers. Customer can see it is saying open document in separate window but it won't open it.

**Comment by penglongzhaochina** [comment]
hi @mumarniaz  could you please share your gist so that I can investigate it?

**Comment by mumarniaz** [comment]
@penglongzhaochina I have modified this sample for your testing. If you click on open document button from taskpane, you will see it open a new doc in a new tab first time and if you click it again, it always open the new document in existing open tab.

https://gist.github.com/mumarniaz/1b3e34e30e19756c1eef6e92bd23e781

**Comment by mumarniaz** [comment]
@penglongzhaochina any update on this ? It is important for us as our Enterprise customers using it.

**Comment by penglongzhaochina** [comment]
Hi @mumarniaz , sorry for late. This week is the chinese new year. I extracted some spare time to investigate it. From the application.CreateDocument() definition, we can see that the application.CreateDocument() return "Word.DocumentCreated". And the api set of "Word.DocumentCreated" class's all property and method is WordApiHiddenDocument 1.3 or WordApiHiddenDocument1.4. And WordApiHiddenDocument 1.3 or WordApiHiddenDocument1.4 is desktop only. So application.createDocument() is not supported in the word online. list some useful link:

https://learn.microsoft.com/en-us/javascript/api/word/word.application?view=word-js-preview#word-word-application-createdocument-member(1)
https://learn.microsoft.com/en-us/javascript/api/word/word.documentcreated?view=word-js-preview
https://learn.microsoft.com/en-us/javascript/api/requirement-sets/word/word-api-requirement-sets?view=powerpoint-js-preview

**Comment by mumarniaz** [comment]
@penglongzhaochina Thans for your response. 

If it is not supported, then why above code work it creates a new document in a separate tab. Just only the case is if you click on the same button again it will reload the new doc in same tab. So if you say it is not supported, then why on first place it creates and open in a tab. Have you tried the gist sample ?

**Comment by penglongzhaochina** [comment]
hi @mumarniaz, I tried you gists in word online. when I click the button the add-in throwed error. 
![image](https://user-images.githubusercontent.com/106959323/215722577-5148273c-bfe6-4d68-b510-5e93195fa315.png)

**Comment by mumarniaz** [comment]
@penglongzhaochina I'm not sure why it doesn't work for you. Can you just try running the above code in some sample ? BTW i have recorded a vide to elaborate my point. Please have a look
https://www.loom.com/share/b59d75cd20fe42f895962a9958063a9d

**Comment by penglongzhaochina** [comment]
Hi @mumarniaz We have different behavior due to some like browser or env problems. I'm the owner of this api. This api is not implemented in the word online(as the document said). So you can do nothing even if you can open a new document. Thanks a lot.
