### ISSUE TITLE
Child Content Control is ignored in OOXML

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#3098]
# Provide required information needed to triage your issue
I want to get the OOXML of a Word Content Control which has a child Content Control.

## Your Environment

* Platform: Office on the web
* Host : Word
* Operating System: Windows
* Browser (if using Office on the web): Edge (109.0.1518.55) / Chrome (109.0.5414.75)
 
## Expected behavior
When I try to get the ooxml of a Content Content which has a child Content Control, I expect that the child Content Control is included in the ooxml.

## Current behavior
The child content control is not in the ooxml;

## Steps to reproduce
1. Create a Content Control with Child Content Control
2. Get the ooxml of the parent Content Control
3. Observe that the ooxml has no content control in it.

## Link to live example(s)

[Gist Example](https://gist.github.com/barisbikmaz/c170e1946b72bb95d0a3067d23a04a76)

# Provide additional details
- This is working in Office for PC and Mac.

## Context
We have an addin which stores the content of a content control in an external file.

**Comment by wangyun-microsoft** [comment]
@barisbikmaz Thanks for reporting this. Can I know your use case here? Do you want to manage the child content control or you just want to get the ooxml?

**Comment by barisbikmaz** [comment]
@wangyun-microsoft I want to get the ooxml. I store the ooxml in an external file. This file can be inserted into other word documents. 
Imagine it like a user saves ooxml snippets which can also contain sometimes content controls. He can insert these "snippets" in other documents.

**Comment by wangyun-microsoft** [comment]
@barisbikmaz Is this still an issue for you?

**Comment by barisbikmaz** [comment]
@wangyun-microsoft The issue still exists but it is a minor issue for us, because it happens only if the Content Controls are created with APIs in Word Online. When the Content Controls are created in Windows, Word Online returns the correct ooxml.

**Comment by xiruatms** [comment]
Thanks, @barisbikmaz . We're still working on this embedded contentcontrol ( contentcontrol inside another content control). We don't have a promised timeline yet. Hope the workaround works well for you.
