### ISSUE TITLE
getOoxml() returns whole Content Control when it contains only an image

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#3099]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
I am getting the whole Content Control ooxml if it has only an image in it.

## Your Environment
* Platform : Office on the web
* Host : Word
* Operating System: Windows
* Browser: Chrome
 
## Expected behavior
When I read the ooxml of a Content Control with an image, it should not contain the whole Content Control.

## Current behavior
When I read the ooxml of a Content Control with an image, it contains the whole Content Control.

## Steps to reproduce
1. Use the gist example below with ScriptLab
2. Click Setup: This creates a Content Control with an image in it
4. Read the ooxml of the Content Control
5. Observe that the ooxml contains the whole Content Control

## Link to live example(s)
[Gist Example](https://gist.github.com/barisbikmaz/643509ee3acb9a4efbbf009cf9252f12)

# Provide additional details
Works in Windows and Mac. Not working in Office Online

## Context
We have an addin which stores the content of a Content Control in an external source. This should only contain the content of the Content Control.

**Comment by penglongzhaochina** [comment]
Hi @barisbikmaz , I compared the word wac result and the word win32 result by using xml comparision. They are almost the same. And they all get the whole content control which showed in the below picture.  So what do you mean "Works in Windows and Mac. Not working in Office Online"? Could you please share more details about this? 
<img width="921" alt="image" src="https://user-images.githubusercontent.com/106959323/213609100-b7567a4f-a0d9-4e97-bef3-8f77fe4f180c.png">

**Comment by barisbikmaz** [comment]
Hi @penglongzhaochina,
Ah yeah thanks. Sorry I used the wrong API (contentControl.getOoxml() instead of contentControl.getRange('Content).getOoxml()). 
I've now adapted my gist code.

**Comment by penglongzhaochina** [comment]
<img width="962" alt="image" src="https://user-images.githubusercontent.com/106959323/213657998-cee7a89f-283b-4baf-99f2-0a996dff9285.png">
Hi @barisbikmaz I repro this issue. I have created a work item 7508995 to track this issue internally.
