### ISSUE TITLE
Search method has a limit of 256 characters.

### ISSUE THREAD

**Issue by heydanhey** [OfficeDev/office-js#31]
Using the javascript api, I'm searching for a sentence in a Word document. If the sentence is over 256 characters, I get an `invalid argument` error.

Is there anyway to search a document with a string that's over 256 characters?

Thanks!

**Comment by JuaneloJuanelo** [comment]
https://officespdev.uservoice.com/ please add this to uservoice.
this is a limitation in Word, but there is a documented workaround here
https://stackoverflow.com/questions/50911606/body-search-issue-in-word-desktop/51159442#51159442
