### ISSUE TITLE
Content Controls not getting deleted

### ISSUE THREAD

**Issue by mattblackdev** [OfficeDev/office-js#310]
Using ```ContentControl.delete(true)``` api does not delete the content control in some cases.

## Expected Behavior

The content control should  be removed during the next ```context.sync()``` call.

## Current Behavior

Our add-in inserts parent content controls for tables in a document. After the document has been saved and reopened, if the add-in attempts to delete the content controls, they don't get deleted. It seems to occur when there are multiple tables in the document, each (but not all) with their own parent content control.

## Steps to Reproduce, or Live Example

We are still working on a reproduction of this issue. For now, we believe it goes something like this:
1.
```
// Word.run() pseudo
for (table in tableCollection.items) {
  cc = table.insertContentControl()
  cc.title = something
  cc.tag = something
}
context.sync()
```
2. Save, close and reopen the document
4.
```
allContentControlsInDocument.forEach(cc => cc.delete(true)
context.sync()
```

## Context

We use content controls to allow the user to identify reference tables that our add-in should validate. We collect a list of potential tables based off column headings, wrap each one with a content control having a tag "Reference Table" and present the list to the user. The user can click on any of them in our add-in UI to say "this is not a reference table" and the add-in will change the content control's tag to "Non-Reference Table" and set its visibility to hidden. If the user clicks one in error, our add-in also provides the option to remove these content controls and start the process over.

When the content controls cannot be successfully removed, we have a problem.

## Your Environment

* Platform: PC Desktop, Mac
* Office version number: 16.*
* Operating System: Windows 10, macOS High Sierra, macOS Mojave

## Useful logs

I'll update this when we have a solid reproduction

**Comment by kbrandl** [comment]
@mattblackdev are you still having this problem? If so, please provide repro steps here so that we can investigate. Thanks!

**Comment by mattblackdev** [comment]
@kbrandl We now believe Track Changes is the root cause of the issue. We've isolated it to documents that have track changes turned on. Once we accept changes on a document, we can then delete content controls through Office.js.

**Comment by JuaneloJuanelo** [comment]
I am not able to repro this issue, i just tried with multiple tables, with tracked changes on and off and still not able to repro. i can delete all Content controls. 
closing for the moment unless @mattblackdev  can share a detailed repro.

**Comment by mattblackdev** [comment]
Yep, understood. I’ll see if I can put cycles into it. We’ve been asking users to accept changes before running our tool and haven’t had any more reports.

Thanks,
Matt
