### ISSUE TITLE
Get request address of a streaming function invocation?

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#3100]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi,

Is there a possibility to get the function invocation of a streaming function?

From what I've seen on docs there is no possibility to have both `'stream': true` and `'requireAddress': true`
```
   {
      "id": "INCREMENTVALUE",
      "name": "INCREMENTVALUE",
      "description": "Count up from zero",
      "helpUrl": "http://www.contoso.com/help",
      "result": {
        "dimensionality": "scalar"
      },
      "parameters": [
        {
          "name": "increment",
          "description": "the number to be added each time",
          "type": "number",
          "dimensionality": "scalar"
        }
      ],
      "options": {
        "stream": true,
        "cancelable": true
      }
    }

```
Docs: 
`
f true, your custom function can access the address of the cell that invoked it. The address property of the [invocation parameter](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-parameter-options#invocation-parameter) contains the address of the cell that invoked your custom function. A function can't use both the stream and requiresAddress properties.
`

**Comment by celluj34** [comment]
This would solve so many problem we're having right now. At the very least, it would make some of our logic much, much simpler.
