### ISSUE TITLE
"Office.context.mailbox" is "undefined" invoking call from custom outlook add-ins

### ISSUE THREAD

**Issue by harshkumardubey** [OfficeDev/office-js#3103]
## Expected behavior
I should be able to access Office.context.mailbox.

## Current behavior
Office.context.mailbox is "undefined" invoking call from custom outlook add-in.

## Steps to reproduce

1. Generate manifest for custom outlook add-in.
2. Install manifest in two different outlook domain e.g. abc.com and xyz.com
3. In abc.com outlook mail when call is invoked from outlook to external system able to access Office.context.mailbox in external system but when call is invoked from xyz.com outlook mail to the same external system Office.context.mailbox is undefined in external system. same custom add-ins is installed in both outlook domain.

**Comment by exextoc** [comment]
Can you provide the following details:
1. Can you provided a sample code for your addin?
2. How are the 2 domains (abc.com and xyz.com related to your addin?)
3. Can you provide a reference to your manifest?
