### ISSUE TITLE
Autofill for password field not working in Excel desktop

### ISSUE THREAD

**Issue by christian-sap** [OfficeDev/office-js#3105]
For one of our customers the autofill feature for password fields does not work in Excel desktop platform.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: latest semi-annual enterprise channel
* Operating System: Windows
 
## Expected behavior
The autofill feature should also work for Edge WebView2 in Excel desktop.
It works fine in the normal Edge browser (outside of Excel), see screenshots below. One is from Excel desktop and one is from the browser.

## Current behavior
The autofill feature does not work.

## Steps to reproduce
Only reproducible for one of our customers
1. Launch our add-in
2. Logon to a "SAP Analytics Cloud" system
3. A dialog is opened that redirects the user to the IDP
4. The password field is not autofilled 

## Context
Commonly offered browser features should be available in Edge WebView2 runtime as well.

## Useful logs
- [ ] Console errors
- [X ] Screenshots
- [ ] Test file (if only happens on a particular file)

![excelLogin](https://user-images.githubusercontent.com/79985386/213728432-b3bbec55-5f0c-4ba5-90f1-ed78eeacf32c.jpg)
![browserLogin](https://user-images.githubusercontent.com/79985386/213728440-770f1809-bd3a-4058-97d0-12bed38e0622.jpg)

**Comment by gingerjia** [comment]
@christian-sap, thanks for reporting the issue! There is an API that under previewing should meet your requirement. Here is the doc link:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2settings.ispasswordautofillenabled?view=webview2-dotnet-1.0.865-prerelease 
Please let us know if have any more issues. Thanks!

**Comment by christian-sap** [comment]
Hi @gingerjia, you posted a link to a dotnet API but I'm an Office Add-in developer. 
My question is why the runtime of the add-in does not enable the autofill feature. As an add-in developer I have no control over your add-in runtime.

**Comment by gingerjia** [comment]
@christian-sap sorry about the confuse info. We have contact the webview2 owner to follow up the details. If any progress, we will update here. Thanks!

**Comment by shaun-pendrigh** [comment]
I am having the same issue. Is there any update on this?

**Comment by shanshanzheng-dev** [comment]
Hi @XuanZhouMSFT, Is there any update for this? Thanks.

**Comment by 4tti** [comment]
oh no 😨

**Comment by ddanehl** [comment]
We are also facing the same issue.

**Comment by shanshanzheng-dev** [comment]
Hi @shaun-pendrigh @ddanehl Thanks for reaching out this issue. We don't support IsPasswordAutofillEnabled of webview2 for now per security reason. We value your feedback and will consider it in our future feature reviews.‌

**Comment by ddanehl** [comment]
> Hi @shaun-pendrigh @ddanehl Thanks for reaching out this issue. We don't support IsPasswordAutofillEnabled of webview2 for now per security reason. We value your feedback and will consider it in our future feature reviews.‌

Hey, i think you are talking about the dotnet API, but we have a Office.JS Add-in for Excel which has a login form in the Task-pane. 
In Excel for Web it asks the user if he wants to remember/store the credentials by using the browsers password manager.
In Excel Desktop, this is not working. e.g. API's like https://developer.mozilla.org/en-US/docs/Web/API/PasswordCredential#browser_compatibility are also not working, although they are supported already by Chrome/Edge.

**Comment by shanshanzheng-dev** [comment]
Hi @ddanehl, Sorry for slow response. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.   We value your feedback. Thanks. https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
