### ISSUE TITLE
GeneralException error when inserting HTML into a focussed content control

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#311]
## Expected Behavior
Clear content control and replace its content by html.

## Current Behavior
A general exception is thrown.

## Steps to Reproduce, or Live Example
[Gist Repo](https://gist.github.com/barisbikmaz/73843453eeb22c31bc916d264c2442ee)

**Additional details:**

1. Create 2 rich content controls in an empty document.
2. Click on the second content control so that it is focussed. The 'click or tap...' text must be selected.
3. Click on "Run" on my gist repo example
4. Observe the error in the console.

## Context
We are trying to replace the content of a content control. Sometimes when a user works in a document he can select a content control. Then we are unable to replace its content.

## Your Environment
* Platform : PC 
* Host : Word
* Office version number: 1811 (Build 11029.20070)
* Operating System: Win

**Comment by kbrandl** [comment]
@barisbikmaz sorry to hear that you're having trouble.

@JuaneloJuanelo are you able to provide any input on this issue? (Please let me know if this should be directed to someone else.)

**Comment by JuaneloJuanelo** [comment]
@barisbikmaz  i was able to repro the issue. BUT I think you not need to clear the content controls in this case. The insertLocation "replace" semantic (second parameter in the insertHtml method) was designed to replace the entire content of the content control with whatever supplied HTML. 
I wonder why are you clearing the content controls before inserting the HTML? Given that you are using "replace" there is no need for this and you can enable your scenario immediately.

given that this is a simple and clear and preferred way of doing this we will not solve this issue with high priority.

**Comment by barisbikmaz** [comment]
Hi @JuaneloJuanelo, sorry for the late response :-)
I used clear before replace because of #129
