### ISSUE TITLE
Changing Background Color of Content Add-In

### ISSUE THREAD

**Issue by cornflakeboy** [OfficeDev/office-js#3111]
Hey there,

I would like to change the background color of a content add-in to be transparent and found no way to do it. Is there anything I missed?

My goal is to build an Excel content add-in that can be layered above existing content to augment it.
I would very much appreciate your help...

**Comment by penglongzhaochina** [comment]
@cornflakeboy Thanks for reaching us. 
For new feature request, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.

**Comment by cornflakeboy** [comment]
Thanks. I posted it here to come to know whether this is really a feature request. So currently there is no way to customize the background color of content add-ins and I should post a feature request?

**Comment by jipinshi** [comment]
@cornflakeboy, confirming that there is need to let some cell values as argument of the content addin, currently has no way to add transparent effect. Guess you can read the cell values out by api and show in content addin to achieve similar effect.

**Comment by XuanZhouMSFT** [comment]
Thanks for waiting and help posted the feature request. After careful consideration, our team has decided to not do this feature in short term. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.
