### ISSUE TITLE
Outlook on-line meeting - appointment provider peristance

### ISSUE THREAD

**Issue by greggiewalker** [OfficeDev/office-js#3114]
What is the approriate way to handle editing an existing on-line meeting with a custom on-line meeting provider in Outlook mobile (tested with IOS) as it defaults back to Microsoft Teams on edit of the meeting?

Or is this behaviour a bug or working as designed?

The meeting provider whilst not enabled, selects to Teams meeting (O365 admin controlled default) and not the specific on-line meeting type for this meeting.

**Comment by nancy-wang** [comment]
Thanks for your question @greggiewalker ! This forum is for issues with our product or documentation, not for programming questions about your code. We suggest you go to [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/office-js-dev.html) and see if your question has already been asked or ask a new question. 

Thanks, Microsoft 365 Developer Platform team
