### ISSUE TITLE
Outlook: Register the online-meeting template for PexTV

### ISSUE THREAD

**Issue by gregwalker-pexip** [OfficeDev/office-js#3115]
Could you please register the on-line meeting template for our PexTV service?

`'<p><br><a href="https://cdn.pexip.com/pextv/join/?conf=123456789&d=something.com" title="sip:123456789&d=something.com" target="_blank">Join PexTV Appointment</a></p><br>';`

Thanks
Greg (Work Account)

**Comment by gregwalker-pexip** [comment]
Is there any eta for this to be actioned as keen to have it progressed?

Thanking you in advance,
Greg

**Comment by nancy-wang** [comment]
Sorry for the delayed response here @gregwalker-pexip ! I've tagged @exextoc to take a look into this and we'll get back to you as soon as we're able.

**Comment by exextoc** [comment]
Thanks for placing the request. As a process, we add new partners once every semester. We recently completed the activity for this semester and would expect to pick this up latest by Sept 2023.

**Comment by gregwalker-pexip** [comment]
Hi Guys,

WOW - That timeline is a bit far out and somewhat loose to consider it within a business process such as a project delivery.
Be nice it those service times was documented.
Are  there any alternatives such as raising a service request ticket in official channels to progress?

Regards,

Greg

**Comment by exextoc** [comment]
@gregwalker-pexip We understand your concern. However, we had standardised the process to once every semester. We hope to improve the process soon, but can only promise the Sept 2023 timeline as of now. To connect with us directly please reach out to OutlookExtensibility@M365x27035562.onmicrosoft.com. Our team will connect you with the relevant point of contact.

**Comment by gregwalker-pexip** [comment]
As the item has not been completed can the case be left open subject to Sept'23 timeframe as per above.

Thanks

Greg
