### ISSUE TITLE
DisplayName is disappeared when Runtime is set

### ISSUE THREAD

**Issue by yauheni-p** [OfficeDev/office-js#3116]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I have a PowerPoint Add-in (I work with web version). There is a manifest file. It contains a tag

`<DisplayName DefaultValue="Office App"/>`

The taskpane has a header as expected:

![image](https://user-images.githubusercontent.com/45207703/215423217-06c21873-5be4-4c9d-ad62-e6608ff6808e.png)

Everything works fine until I add

```
<Runtimes>
    <Runtime resid="Defaults.Url" lifetime="long" />
</Runtimes>
```
With this tag, my taskpane does not contain the header anymore:

![image](https://user-images.githubusercontent.com/45207703/215423396-1ac0e85c-7da3-47cd-9d60-1353e2cbb696.png)

This tag is required, because Enable and Disable Add-in Commands programmatically possible only with shared runtime.
Manifest file checked, it does not contain errors.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Web
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: ______
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
That would be nice if a header would not disappear

## Current behavior
The header is disappeared

## Steps to reproduce
N/A

## Link to live example(s)
N/A

# Provide additional details
N/A

**Comment by nancy-wang** [comment]
Thanks for reporting this issue @yauheni-p ! Tagging @wangyun-microsoft who may be able to help here.
