### ISSUE TITLE
Outlook JS Plugin - Custom display message onmessagesend

### ISSUE THREAD

**Issue by rdmbarroso** [OfficeDev/office-js#3118]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hello,

I'm currently developing an Office plugin using the OnMessageSend and SmartAlerts events for Outlook that will perform a few simple checks before the email is being sent.

the plugin is working and the validations as well,  however, i have this on a taskpane and i would like to display a custom message when the user clicks on the send button. Is this even possible to do? I've been reading the documentation and checking examples but so far no luck.

**Comment by nancy-wang** [comment]
Thanks for your question @rdmbarroso! This forum is for issues with our product or documentation, not for programming questions about your code. We suggest you go to [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/office-js-dev.html) and see if your question has already been asked or ask a new question. 

Thanks, Microsoft 365 Developer Platform team
