### ISSUE TITLE
Excel Evaluate Formula (F9) doesn't work on custom functions 

### ISSUE THREAD

**Issue by YasharHeydari** [OfficeDev/office-js#3119]
[Enter feedback here]

When using excel, clients create formulas that may contain custom function calls. When the combination of formulas doesn't work, they want to evaluate the formula step by step to find the issue. What they do is to select a part of formula and press F9. 

Selecting the custom function part of the formula ( e.g. Contoso.Add(1, 2) ) instead of showing the value 3, shows #Value! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be179784-5839-3e8f-c131-1f4d89808b03
* Version Independent ID: 69bca101-91a2-3a5e-5177-493723504354
* Content: [Debug Office Add-ins on a Mac - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/debug-office-add-ins-on-ipad-and-mac)
* Content Source: [docs/testing/debug-office-add-ins-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/debug-office-add-ins-on-ipad-and-mac.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @YasharHeydari,

Thanks for reporting this. Since this seems like either product feedback or a bug, I'm going to transfer this issue to the [office-js repo](https://github.com/OfficeDev/office-js). There, the right folks can diagnose this.

**Comment by YasharHeydari** [comment]
Thank you Alex, 
    I should've done that in the first place.

**Comment by nancy-wang** [comment]
Thanks @YasharHeydari and @AlexJerabek ! Tagging @grangeryy and @yaweizhu-henson to take a look into this issue.

**Comment by dorkster100** [comment]
Also calculate sheet and calculate workbook not working for me.

**Comment by ilex-sgangwani** [comment]
Has there been a solution for this or can someone share the link where this feature / bug request has been moved to?

**Comment by YasharHeydari** [comment]
Any updates on this?

**Comment by donlvMSFT** [comment]
Thanks for letting us know this issue.

However, currently, the feature: evaluate custom function, you requested, is not a part of the product. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests are considered when we go through our planning process. 

Thanks, Microsoft 365 Developer Platform team
