### ISSUE TITLE
Error while retrieving trackedObjects and ranges - only on Word Online

### ISSUE THREAD

**Issue by ClaroJack** [OfficeDev/office-js#312]
## Expected Behavior
Should move the caret to the next sentence and also highlight next sentence. 

## Current Behavior
Currently fails and gives error code. **GeneralException: Cannot read property 'xT' of null**, when trying on Word Online but works fine on Word on Desktop.

## Steps to Reproduce, or Live Example
```
function moveCaret(currentSentence) {
        Word.run(firstSentence, function (context) {
            firstSentence.load();
            return context.sync().then(function () {
                contextSentences = firstSentence.items[0].getRange()
                    .expandTo(context.document.body.paragraphs.getLast().getRange("end"))
                    .getTextRanges([".", "!", "?"]);
                context.load(contextSentences);
                return context.sync().then(function () {
                    context.document.body.font.color = noHighlight;
                    contextSentences.items[currentSentence].select("start");
                    contextSentences.items[currentSentence].font.color = highlightColour;
                    context.sync();
                })
            })
        }).catch(errorHandler);
    }
```

```
function play() {
        if (useWebSpeech) {
            window.speechSynthesis.cancel();
        }
        else {
            // If server is being used, pause DOM audio playback.
            audioOutput.pause();
        }
        Word.run(function (context) {
            // Retrieve the currently selected sentene.
            firstSentence = context.document.getSelection().getTextRanges([".", "!", "?"]);
            // To access the paragraphs properties, it needs to be loaded within the context.
            context.load(firstSentence);
            context.trackedObjects.add(firstSentence);
            firstSentence.track();
            // Retrieve the sentences within the paragraph.
            return context.sync().then(function () {
                documentSentences = firstSentence.items[0].getRange()
                    .expandTo(context.document.body.paragraphs.getLast().getRange("end"))
                    .getTextRanges([".", "!", "?"]);
                // Load sentences into the trackedObjects, allows the use of the sentences outside of context.
                context.load(documentSentences);
                context.trackedObjects.add(documentSentences);
                documentSentences.track();
                return context.sync(documentSentences).then(function () {
                    removeHighlight()
                    documentSentences.items[0].select("start");
                    documentSentences.items[0].font.color = highlightColour;
                });
            })
        }).then(function () {
            isDestroyed = false;
            currentSentence = 0;
            // Recursive call onend, stops when current sentence count exceeds amount of sentences.
            incrementSentence(currentSentence);
        })
            .catch(errorHandler);
    }
```

## Context
I am trying to save the range so that the caret moves to the next sentence after the current range. Currently works fine on Word on Windows, but doesn't work on Word Online (gives GeneralException: Cannot read property 'xT' of null)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop, Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Latest
* Operating System: Windows 10
* Browser (if using Office Online): Chrome

## Useful logs
GeneralException: Cannot read property 'xT' of null

**Comment by JuaneloJuanelo** [comment]
@ClaroJack  Thanks for reporting this. since you have a few not included methods on these sample code, would you mind creating a https://aka.ms/scriptlab snippet, so we can quickly debug what's going on? .

**Comment by ClaroJack** [comment]
@JuaneloJuanelo Thank you for the quick response! Here is a simple snippet which uses the cross Word.run context functionality that I am trying to utilize. The snippet works fine in Word for Windows but gives an error on Word Online.

https://gist.github.com/ClaroJack/6f4909a1e82451d882b32e8fe4ccfd94

**Comment by ClaroJack** [comment]
@JuaneloJuanelo Any update on this?

**Comment by JuaneloJuanelo** [comment]
thanks for sharing the code snippet @ClaroJack ! I was able to repro the issue, its an interesting one and definitely we'll investigate why this is going on.  We are tracking internally with  2737457

That been said, I want to share another snippet with you ([on this gist for scriptlab](https://gist.github.com/JuaneloJuanelo/05dcde2ab360b1cb7dcec22f7a729a3a)) . Its a relatively similar example, but ultimately using ranges in different contexts, which is what you want to achieve. ON this scenario i am actually searching for the text "Word" so make sure to add some relevant instances to try it. the idea is that i am filling a combo box with each instance and then I can select one specific one to bold it (from the combo) . Can you please try this approach? oh and dont forget to flush the tracked object! :)

**Comment by kbrandl** [comment]
Please ignore the previous message from **msftbot**. The **Needs: author feedback** label was incorrectly applied to this issue; I've removed that label and this issue is no longer marked as stale.

**Comment by weshi** [comment]
Reopen as this is not marked as stale now.
