### ISSUE TITLE
Powerpoint getSelectedDataAsync

### ISSUE THREAD

**Issue by zohaibr** [OfficeDev/office-js#3120]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

 Powerpoint getSelectedDataAsync only returns the index of the first selected slide. 

## Your Environment
Office 365 Web (Powerpoint Web)
Browser: Chrome Version 109.0.5414.119 (arm64)

 ## Expected behavior
Calling Office.context.document.getSelectedDataAsync(Office.CoercionType.SlideRange should return an array of all selected slides.

## Current behavior
Currently only returning the metadata for the first slide only.

<img width="1867" alt="Screenshot 2023-01-31 at 1 01 07 PM" src="https://user-images.githubusercontent.com/872132/215844803-41d0b1fd-c1af-42ec-935d-78763e8e0397.png">

## Steps to reproduce
Select multiple slides in Powerpoint Web and run the following code in ScriptLab (Get slide metadata)

```
$("#get-slide-metadata").click(getSlideMetadata);

function getSlideMetadata() {
  Office.context.document.getSelectedDataAsync(Office.CoercionType.SlideRange, function(asyncResult) {
    if (asyncResult.status === Office.AsyncResultStatus.Failed) {
      console.error(asyncResult.error.message);
    } else {
      console.log(JSON.stringify(asyncResult.value, null, 4));
    }
  });
}
```

## Context
We cannot return the index of all the selected slides.

**Comment by nancy-wang** [comment]
Thanks for reporting this issue @zohaibr ! Tagging @wangyun-microsoft who may be able to help here.

**Comment by jipyua** [comment]
Thanks for reporting this, we can repro this on PowerPoint online, we have opened an item 7823520 to track this internally, we unfortunately have no timelines to share at this point.
