### ISSUE TITLE
Outlook on the Web: recipientType is incorrect for Personal Contacts

### ISSUE THREAD

**Issue by tranhuyentran23** [OfficeDev/office-js#3122]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When adding @gmail.com account or an account from another Microsoft 365 tenant to Personal Contacts
then calling `Office.context.mailbox.item.to.getAsync()`, `recipientType` is set to `user` instead of `externalUser`

**Note that this is inconsistent with Outlook for Windows**

## Your Environment

* Platform: Web
* Host: Outlook
* Operating System: Windows 10
* Browser: Chrome
 
## Expected behavior
`recipientType` should be `externalUser` if an account added to Personal Contacts (as Outlook for Windows).

## Current behavior
 `recipientType` is set to `user`

## Steps to reproduce

1. Access Outlook Online
2. Add any external recipient to Personal contacts for example @gmail or @Hotmail address or Microsoft 365 with a different tenant
3. Create a new email
4. Add the contact to the 'To' recipients
5. Open ScriptLab and add a call to `Office.context.mailbox.item.to.getAsync(console.log)`.

Notice in the console that recipientType is set to 'user' => expected value should be 'externalUser'

<img width="553" alt="Untitled" src="https://user-images.githubusercontent.com/89008454/215973969-bbdbfbf1-a3e4-427c-b050-cd47a4589e91.png">

**Comment by nancy-wang** [comment]
Thanks for reporting this issue @tranhuyentran23 ! Tagging @exextoc to take a look.

**Comment by exextoc** [comment]
@tranhuyentran23 - Thanks for reporting the issue, although we are not able to reproduce the same on our end. Could you please share a repro video including the step of adding personal contact so that we can further investigate the issue. Thanks!

**Comment by tranhuyentran23** [comment]
Hi @exextoc , I recorded all steps that I added a contact to personal contact then get `recipientType` of this contact

![chrome_jQtydtdGGi](https://user-images.githubusercontent.com/89008454/217749696-11eb3bcd-7438-45f6-bca7-77c13570849f.gif)

Let me know if you need any other information. Thanks!

**Comment by exextoc** [comment]
Thanks for sharing the video. We are able to repro this issue now. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: 190494
