### ISSUE TITLE
Changing until-date in recurring meeting causes mailboxItem.recurrence.getAsync() to stop working due to unhandled exception

### ISSUE THREAD

**Issue by johnbergvall** [OfficeDev/office-js#3125]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

If you change the until-date of an existing meeting-serie mailboxItem.recurrence.getAsync() stops working until closing the edit meeting-dialog or change meeting start date/time.

## Expected Behavior

* The recurring series is updated with new until-date and calls to mailboxItem.recurrence.getAsync() keeps working

## Current Behavior

* owa.CalendarBoot.js throws an unhandled exception and mailboxItem.recurrence.getAsync() stops triggering success/error-callback until dialog is closed or start date/time is changed
* There are no visible information for customers to know that something is wrong due to the missing callbacks

## Steps to Reproduce, or Live Example

* Create recurring series. Save/Send + close meeting dialog
* Edit meeting series. Change "until"-date of recurring rule and leave everything else the same
* Press save. 
* No further calls to mailboxItem.recurrence.getAsync() triggers callback, but instead raises an unhandled exception in owa.CalendarBoot.js until start date/time is changed or dialog is closed
* Reproduced over multiple tenants and computers. Some Office 365 environments seem to work though.

## Context

This bug causes these problems:

* Customers cannot change until-date of their meeting series and use Outlook-addin to use that information in external systems
* Customer cannot use addin at all after until-date is changed due to never resolving promises if any path awaits for mailboxItem.recurrence.getAsync()

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: owamail/20230120008.13 
* Operating System: Linux + Windows
* Browser (if using Office Online): Firefox + Chrome

## Useful logs

```js

        switch (e.__type) {   // <--- Call stack 1  Source of error. e does not contain __type. e.__typename is already EndDateRecurrence

/* local variable:      
      e: {
EndDate:  ... 
StartDate:  ...
__typename: "EndDateRecurrence
// Note: missing __type
}
*/  
          case r.II:
            return {
              __typename: 'EndDateRecurrence',
              ...e
            };
          case r.gK:
            return {
              __typename: 'NoEndRecurrence',
              ...e
            };
          case r.RZ:
            return {
              __typename: 'NumberedRecurrence',
              ...e
            }
        }
        throw new Error(`unhandled recurrence range ${ e.__type }`)
      }
      function i(e) {
      
/* local variables */
e: {
RecurrencePattern: ...
RecurrenceRange: {
EndDate: ...
StartDate: ...
__typename: "RecurrenceType"
// Note: missing __type
}
        return {
          __typename: 'RecurrenceType',
          RecurrencePattern: a(e.RecurrencePattern),
          RecurrenceRange: o(e.RecurrenceRange)    // <--- Call stack 2. source of error: e.RecurrenceRange does not contain __type, but have __typename 'EndDateRecurrence'
        }
      }
      


```

Traceback:

```
// https://res.cdn.office.net/owamail/20230120008.13/scripts/owa.CalendarBoot.js:formatted

Uncaught (in promise) Error: unhandled recurrence range undefined
    o owa.CalendarBoot.js:42471
    i owa.CalendarBoot.js:42477
    a owa.15729.js:2
    j owa.15729.js:2
    Rt owa.15729.js:2
    Bt owa.15729.js:2
    _ owa.15729.js:2
    invoke owa.15729.js:2
    f owa.15729.js:2
    p owa.15729.js:2
    setInterval handler*I owa.15729.js:2
    x owa.15729.js:2
    x owa.15729.js:2
    createServiceEndPoint owa.15729.js:2
    t owa.15729.js:2
    L owa.15729.js:2
    a owa.15729.js:2
    _i owa.ven.extframework.js:2
    $a owa.ven.extframework.js:2
    Kl owa.ven.extframework.js:2
    Tu owa.ven.extframework.js:2
    Cu owa.ven.extframework.js:2
    Ou owa.ven.extframework.js:2
    gu owa.ven.extframework.js:2
    Yo owa.ven.extframework.js:2
    unstable_runWithPriority owa.20529.js:2
    Ko owa.ven.extframework.js:2
    Yo owa.ven.extframework.js:2
    Qo owa.ven.extframework.js:2
    Mu owa.ven.extframework.js:2
    unstable_runWithPriority owa.20529.js:2
    Ko owa.ven.extframework.js:2
    Iu owa.ven.extframework.js:2
    De owa.ven.extframework.js:2
    Yt owa.ven.extframework.js:2

```

**Comment by nancy-wang** [comment]
Thanks for letting us know about this issue @johnbergvall ! Tagging @exextoc to take a look into the issue.
