### ISSUE TITLE
On a Mac, Office.context.mailbox.item.body.getAsync() return is missing the div tag pair that wraps the email headers of the original email in an email reply

### ISSUE THREAD

**Issue by junhuiluosalesforce** [OfficeDev/office-js#3127]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __macOS, Ventura 13.1, probably other macOS versions too____
* Host [Excel, Word, PowerPoint, etc.]: ___Microsoft Outlook for Mac Version 16.69.1 (23011802), Microsoft 365 Subscription___
* Office version number: ___Version 16.69.1 (23011802)___
* Operating System: ____Ventura 13.1__
* Browser (if using Office on the web): ______
 
## Expected behavior

Our use case is to use Office.context.mailbox.item.body.getAsync() to retrieve the original email text in compose mode, insert some image tag into the retrieved email body then replace the original email body with the additional image tag.

When a user replies to an email in Outlook desktop app on Mac (and Windows and with OWA), a visual horizontal line is rendered and seen in the reply compose window. Once the reply email is sent, one can see in the result email that the horizontal line is rendered by a pair of div tags that wraps around the email headers of the original email, similar to the following when the reply was sent from Outlook desktop app on Mac or Windows:

&lt;div style=&#39;border:none;border-top:solid [#E1E1E1](javascript:void(0);) 1.0pt;padding:3.0pt 0in 0in 0in&#39;&gt;
...Original email headers omitted here...
&lt;/div&gt;
or this:
&lt;div style=&quot;border:none;border-top:solid [#B5C4DF](javascript:void(0);) 1.0pt;padding:3.0pt 0in 0in 0in&quot;&gt;
...Original email headers omitted here...
&lt;/div&gt;
(If the reply was sent from OWA, &lt;hr tabindex=&quot;-1&quot; style=&quot;display:inline-block; width:98%&quot;&gt; is seen between the reply text and original email.)

If I use Office.context.mailbox.item.body.getAsync(
  "html",
  { asyncContext: "This is passed to the callback" },
  function callback(result) {
    console.log(result.status + " email body is " + result.value)
  });
to retrieve the reply text from Outlook desktop app on *Windows* OS, the above div tag pair is seen. So after I add an additional image tag to the retrieved email body the horizontal line continues to be rendered.

## Current behavior

If I use the same Office.context.mailbox.item.body.getAsync() to retrieve the reply email body on *Mac* OS, the above mentioned &lt;div&gt; tag pair that renders the visual horizontal line is not returned. So if I replace the original email body with so retrieved text, even without *any* modification, the visual horizontal line will be gone from the reply compose window. And also gone for good if the resulting email was sent.

Note that on Mac, Office.context.mailbox.item.body.getAsync() does not return the div tag pair even when the horizontal line is visible in the compose window after the user hits the Reply or Reply All button. Despite that, the div tag will be present in the Sent folder of the sender and Inbox of the recipient after the email is sent.

## Steps to reproduce

1. ______userA sends an email to userB.
2. ______userB opens the email in Outlook desktop app on a Mac.
3. ______userB hits the Reply button and type some reply text above the original userA email.
4. Use the above office.js code to retrieve the reply body. Note that the div tag is missing even though the visual horizontal line is visible in the compose window.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

We use office.js API to retrieve the email body, add some image tag to the email body, then replace the original email body.
## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @junhuiluosalesforce. Connecting you with @exextoc who may be able to help.

**Comment by exextoc** [comment]
Hi @junhuiluosalesforce, we don't have a solid repro of this issue on our end. Could you please share a video showing steps you are following so that we can investigate this issue further. Thanks!

**Comment by junhuiluosalesforce** [comment]
Hello @exextoc https://www.loom.com/share/4840cc2e7b944bd0b83830e5360cf0e0 is a screen recording for the issue. Thank you for looking into this!

**Comment by exextoc** [comment]
Hey @junhuiluosalesforce ,

Sorry for the late response. We do notice that while this is the case, we have an anchor tag that reads `<a name="_MailOriginal">` which is always present between the current email and the previous ones. This can help you differenciate between the mails. Does this work for you?

**Comment by exextoc** [comment]
Hey @junhuiluosalesforce ,

Sorry for the late response. This indeed is the behaviour as you mentioned. Thanks for reporting this issue, we are tracking this issue in our backlog. However, we have no timelines to share at this point.

If you need a separator to tell the current and previous email apart, this anchor tag `<a name="_MailOriginal">` seems to be a workaround. Does that help?

**Comment by junhuiluosalesforce** [comment]
@exextoc Thank you for confirming the API behavior. Our end users' want is the preservation of the original "look and feel" of the email body. Since we are not getting the HTML that renders the horizontal line, we are not able to preserve the "look".

**Comment by exextoc** [comment]
@junhuiluosalesforce Unfortunately we do not have a workaround for preserving the line at this point.
