### ISSUE TITLE
Office.js Library Breaks Angular Routing

### ISSUE THREAD

**Issue by breadberry-prime** [OfficeDev/office-js#3128]
## Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac & Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
When adding the office.js library to a Blank Angular Application it should still work without any issues. 

## Current behavior
When adding the office.js library to any Angular application it breaks the routing.

## Steps to reproduce
1. create a new angular app using` ng new OfficeJsIssue`
2. add   `<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>` to the index.html
3. routing is broken

## Link to live example(s)
1. https://beta-outlook.web.app/
https://user-images.githubusercontent.com/75136042/216819619-4a8b9820-a136-4394-9088-438ce73a295b.mov

## Context
This issue has affected me as I am trying to create a new Angular application that utilizes the office.js library to integrate with Outlook. However, when I add the library it breaks the routing, which makes it difficult to continue developing the application.

**Comment by rutvik95** [comment]
Have a look at #2808

**Comment by breadberry-prime** [comment]
> Have a look at #2808

Thank you! Was there any progress since August 2022?
