### ISSUE TITLE
Large list of entities with a sub-entities gets stuck on #BUSY in Excel Web

### ISSUE THREAD

**Issue by thordurk91** [OfficeDev/office-js#3129]
Trying to output a large list of entities with subentities hangs the web version of Excel.

## Expected Behavior
The list of entities to be returned.

## Current Behavior
Hangs on #BUSY cell status not returning any data, edgecases have had the tab run out of RAM, but hard to reproduce.

## Steps to Reproduce, or Live Example
Sample script lab gist: https://gist.github.com/thordurk91/698b841e06e0a05a0c2dcc620b0193f7

* Additional details:
Run the function used to mimic the behaviour ( I stripped the product search example to produce similar data ): 
1. =SCRIPTLAB.DATATYPESCUSTOMFUNCTIONS.PRODUCTSEARCH()
2. Watch it hang on #BUSY.

There is a sliced 10 commented code that outputs the data, as it works with fewer entities.
Developemental sample that is running into this issue is returning 2000 entities with most users having potentially thousands of items.

## Context
Outputting a list of the users relevant entities. 
They can reference each other as an entity "location" can be inside another entity, so at least one nested entity is needed in the entity.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: Windows 10
* Browser (if using Office Online): Chrome

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by jiju-MS** [comment]
Hey, thordurk91, if this issue only happened when you are using Excel online, you may hit the payload limit as below doc: https://learn.microsoft.com/en-us/office/dev/add-ins/excel/performance#payload-size-limit-best-practices

If there is any way you can change the code logic to reduce the payload or let user using multiple custom function formulars to get data instead of returning all data in one time, you may avoid such issue. 

Thanks!

**Comment by thordurk91** [comment]
Hey, jiju-MS. Thanks for the reply.

The payload in questions can be in extremely varying sizes depending on the users data.
I've created a stripped down version that supports more items, with a support function returning detailed information with nested entities for each stripped entity.
But there will be users that have the capability of hitting that limit even with a stripped version, causing a "#BUSY" results with no indication to the user of hitting that limit, since the CF code actually returns the object with no visibile error. Which is my biggest issue with this, that it get's stuck.

Paging the function has UX approach issues, since it requires the users to know their page count beforehand, doing the per-page build themselves and combining the results by hand in the end.
Reducing the matrix elemental gained from the data being an entity and thereby reducing the call into a overly complicated table data dump, which is what elementary google sheet versions for similar datasets do.
That approach has little flexibility for the cases when the pagecount changes as the data can be different page size each day, requiring the user to have in-depth knowledge of more advanced excel cell manipulation/outputting. Increasing the burden of knowledge for the data extraction and reducing it's usability to users with less technical knowledge of excel.

Either the framework should be capable of batching the CF return data that exceeds the payload limit, or in the very least throw the user a visible error that it has hit this limit, so the user can be guided how to advance in such cases of too big data sets for a single CF return. Eliminating the technical burden for vast majority of users.

**Comment by jiju-MS** [comment]
Thanks for the details and suggestions, thordurk91. We now have more understanding about the limitations for large payload scenario, especially when using entities, and how painful to control user's behavior and educate them about size limitation knowledge. 

Paging is one of the solutions we recommend, but as you mentioned it also has some limitations, so we are looking into some solutions including refinement of framework and error handling.
