### ISSUE TITLE
SearchOptions Wildcards

### ISSUE THREAD

**Issue by nunocv** [OfficeDev/office-js#313]
Article: https://github.com/OfficeDev/office-js-docs/blob/master/reference/word/searchoptions.md

Issue: Certain symbols/text not being captured or recognized by the search method from the body object with the wildcard option.
@ is not captured, even like this [@]
\t is not captured, even like this [\t], while \r is captured.
! is not captured, even like this [!].

If this symbols/text could be captured, It would be great!

**Comment by JuaneloJuanelo** [comment]
the \r \t are literal or are actual line breaks/tabs in the document?
can you attach a sample doc?

**Comment by JuaneloJuanelo** [comment]
@fergiemcdowall  I would not say that regular expressions are supported in searchOptions. We have a simple wilcard search as of now.

**Comment by JuaneloJuanelo** [comment]
Regular expression search is currently not supported in the API. please add a request in our uservoice channel. https://officespdev.uservoice.com/
