### ISSUE TITLE
Excel is loading at all.

### ISSUE THREAD

**Issue by vinay-sattur** [OfficeDev/office-js#3131]
Excel online is not loading

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* nonprod environment.

Because of this issue testing and development is blocked for us.

**Comment by penglongzhaochina** [comment]
Hi @vinay-sattur  is you issue about excel add-in? Could you share more details about this issue?
