### ISSUE TITLE
Module is not valid ExtensionPoint

### ISSUE THREAD

**Issue by vloput** [OfficeDev/office-js#3135]
## Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows 11
 
## Expected behavior
`<ExtensionPoint />` with `xsi:type="Module"` should be validated.

## Current behavior
`office-addin-manifest validate` task returns errors:

```
Validation Information: 
Acceptance Test Completed: Acceptance test service has finished checking provided add-in.

Error #1: 
Package Type Not Identified: We could not recognize any supported add-in type 

Error #2: 
Wrong Package: Your package does not match submission type.

The manifest is not valid.
```

## Steps to reproduce

1. Add an `<ExtensionPoint />` with `xsi:type="Module"`
2. Run `office-addin-manifest validate`

## Context
Are modules still supported in Office.js? I see an [example manifest in the docs](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/extension-module-outlook-add-ins#example), but seems like it's a little outdated.
If yes, how can I use it?
Thank you.

**Comment by vloput** [comment]
Attaching a part of the manifest:

```
<Hosts>
  <Host xsi:type="MailHost">
    <DesktopFormFactor>
      <FunctionFile resid="Commands.Url"/>
      <ExtensionPoint xsi:type="Module">
        <Label resid="Extension.Label" />

        <CustomTab id="idTab">
          <Group id="idGroup">
            <Label resid="Extension.Label" />

            <Control xsi:type="Button" id="reviewProjects">
              <Label resid="Extension.Label" />
              <Supertip>
                <Title resid="Extension.Label" />
                <Description resid="Extension.Label" />
              </Supertip>
              <Icon>
                <bt:Image size="16" resid="Icon.16x16"/>
                <bt:Image size="32" resid="Icon.32x32"/>
                <bt:Image size="80" resid="Icon.80x80"/>
              </Icon>
              <Action xsi:type="ExecuteFunction">
                <FunctionName>action</FunctionName>
              </Action>
            </Control>
          </Group>
        </CustomTab>
      </ExtensionPoint>
    </DesktopFormFactor>
  </Host>
</Hosts>
```

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @vloput. Connecting you with @samantharamon who may be able to help.

**Comment by samantharamon** [comment]
Hi @vloput. Thanks for reaching out. I've created a work item on our backlog to review our Module extension documentation and sample to see where we can update information.

I updated your manifest snippet per the example in [Module extension Outlook add-ins](https://learn.microsoft.com/office/dev/add-ins/outlook/extension-module-outlook-add-ins#example). I'm able to validate the manifest without any errors. Let me know if this works for you.

```xml
<Hosts>
  <Host xsi:type="MailHost">
    <DesktopFormFactor>
      <FunctionFile resid="Commands.Url"/>
      <ExtensionPoint xsi:type="Module">
        <!-- A SourceLocation element must be included as a child element of the
        ExtensionPoint element if its xsi:type property is set to Module.
        See https://learn.microsoft.com/javascript/api/manifest/sourcelocation for
        information on the file to reference. -->
        <SourceLocation resid="residExtensionPointUrl" />
        <Label resid="Extension.Label" />
        <!-- The CustomTab element must be added as a child element of the
        CommandSurface element for module add-ins. -->
        <CommandSurface>
          <CustomTab id="idTab">
            <Group id="idGroup">
              <Label resid="Extension.Label" />
              <Control xsi:type="Button" id="reviewProjects">
                <Label resid="Extension.Label" />
                <Supertip>
                  <Title resid="Extension.Label" />
                  <Description resid="Extension.Label" />
                </Supertip>
                <Icon>
                  <bt:Image size="16" resid="Icon.16x16"/>
                  <bt:Image size="32" resid="Icon.32x32"/>
                  <bt:Image size="80" resid="Icon.80x80"/>
                </Icon>
                <Action xsi:type="ExecuteFunction">
                  <FunctionName>action</FunctionName>
                </Action>
              </Control>
            </Group>
            <!-- A Label element is a required child element of the CustomTab element.
            See https://learn.microsoft.com/javascript/api/manifest/customtab. -->
            <Label resid="residCustomeTabLabel"/>
          </CustomTab>
        </CommandSurface>
      </ExtensionPoint>
    </DesktopFormFactor>
  </Host>
</Hosts>
```

**Comment by vloput** [comment]
Hi @samantharamon. Thank you for your response.
I've tried your manifest and I've got the same error messages. Is it possible, that your packages are older? I've installed the latest version a few days ago.

Also, I don't see 'Module' as a valid ExtensionPoint type [in the schema](https://learn.microsoft.com/en-us/openspecs/office_file_formats/ms-owemxml/578d8214-2657-4e6a-8485-25899e772fac). It includes only 'MessageReadCommandSurface', 'MessageComposeCommandSurface', 'AppointmentOrganizerCommandSurface', 'AppointmentAttendeeCommandSurface'. Maybe I'm looking at the wrong schema though.

**Comment by samantharamon** [comment]
Thanks for giving that a go, @vloput. I'm running the current versions (npm 9.4.2, generator-office 1.9.2). I know you've installed the latest versions a few days ago, but do these match what you have?

`Module` appears in the [mailappversionoverrides/1.1 schema](https://learn.microsoft.com/openspecs/office_file_formats/ms-owemxml/8e722c85-eb78-438c-94a4-edac7e9c533a). By any chance, do you have `VersionOverridesV1_1` in your manifest?

```xml
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides"
                    xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1"
                      xsi:type="VersionOverridesV1_1">
      <!-- Begin override of existing elements -->
      <Description resid="residVersionOverrideDesc" />
      <Requirements>
        <bt:Sets DefaultMinVersion="1.3">
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>
      <!-- End override of existing elements -->
      <Hosts>
        <Host xsi:type="MailHost">
        ...
```

**Comment by vloput** [comment]
@samantharamon, you're right, I've had only `VersionOverridesV1_0`. After adding a nested `VersionOverridesV1_1` the manifest was validated successfully and the module appeared in Outlook. Thanks a lot for your help!

**Comment by samantharamon** [comment]
No worries! I'm glad to hear that worked and you're now able to see the module in Outlook. I'll go ahead and close this issue, but if you need further assistance, please don't hesitate to open a new GitHub issue.
