### ISSUE TITLE
Excel Range Top and Left values not correctly reported.

### ISSUE THREAD

**Issue by osorvillo** [OfficeDev/office-js#3136]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
We are working with images in Excel that are needed to be placed specifically adjacent to a cell (range) that is selected. The function uses the Top and Left attributes of the selected cell to place the image(s). We are experiencing an incorrect placement of the image (shape) when the Row heights or Column widths are not the default of Excel and are subsequently affected by the Windows Scale ratio. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: _PC Desktop_____
* Host [Excel, Word, PowerPoint, etc.]: _Excel_____
* Office version number: _2202_____
* Operating System: _Windows_____
* Browser (if using Office on the web): Edge______
 
## Expected behavior

The values reported by the Office.JS for a range's Top and Left should be correct.
## Current behavior

The Top and Left attributes of the Range object are not accurate.
## Steps to reproduce

1. _Create a function that will report the Top and Left attributes of the selected range (single cell) and set those values to variables_____
2. _Change the default Height and Width of the Worksheet to a number that is NOT a modulus of the default height or width_____
3. _Create a shape object and place it using the Top and Left retrieved from the above function. Do this at rows 5, 10, 20, 50, 100, 250, etc._____
The result is affected by the Row heght, column width and windows display scale.
## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

the images we place have significance to our users and are directly related to the data adjacent to where the user placed the image. When the image is not correctly placed, the affect could be significantly negative as the second, third, fourth, etc person opens the Excel document, reviews the content and derives meaning from the images. When they are incorrectly placed the wrong meaning or action could be taken.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @osorvillo. Connecting you @RuizhiSunMS with who may be able to help.
