### ISSUE TITLE
Cannot modify property of content control that is in same paragraph with another content control

### ISSUE THREAD

**Issue by tranhuyentran23** [OfficeDev/office-js#3137]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Inserting some content into a content control that is in the same paragraph with another content control
then modify a property of the content control, an error was thrown

**Note that this issue just happen when content controls are in same paragraph and using method insertFileFromBase64 or insertOoxml to insert content (it working well with insertText or insertHtml)**

## Your Environment
* Platform: Office Online
* Host: Word
* Office version number: 16.0.14413.41001
* Operating System: Windows 10
* Browser: Chrome
 
## Expected behavior
After inserting content into a content control (which is the same paragraph with another one), a property can be modified successfully

## Current behavior
After inserting content into a content control (which is the same paragraph with another one), an error was thrown when modifying a property

## Steps to reproduce
1. Create a new document
2. Run the attached Script lab
3. Click 'Insert 2 content control in the same paragraph' 
4. Click 'Insert Content'
(This step will insert a content into the second content control then modify a property of this content control)

Notice in the console, an error was thrown

![case1-fail](https://user-images.githubusercontent.com/89008454/217433564-e4eaa27a-cd1e-4c05-aeaf-cff2c3b3a1ae.gif)

Note that this issue will not happen if we insert content controls in different paragraph

![case1-pass](https://user-images.githubusercontent.com/89008454/217433690-dd7f262f-bd84-40d7-a9e2-0da51365d5ee.gif)

Script Lab: https://gist.github.com/dad98c10c3f68d137db5cf250597ee09

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @tranhuyentran23. Connecting you with @wangyun-microsoft who may be able to help.
