### ISSUE TITLE
List content controls return incorrect values after inserting a content into content control that has another content control inside

### ISSUE THREAD

**Issue by tranhuyentran23** [OfficeDev/office-js#3139]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Inserting some content (a file has a content control inside) into a content control (has a content control inside) that is in the same paragraph with another content control
`context.document.contentControls.items` return more items than expected

## Your Environment
* Platform: Office Online
* Host: Word
* Office version number: 16.0.14413.41001
* Operating System: Windows 10
* Browser: Chrome
 
## Expected behavior
After inserting some content (a file has content control inside) into a content control (has a content control inside) that is in the same paragraph with another one, `context.document.contentControls.items` should return correct values

## Current behavior
After inserting some content (a file has content control inside) into a content control (has a content control inside) that is in the same paragraph with another one, `context.document.contentControls.items` return more items than expected

## Steps to reproduce
1. Create a new document
2. Run the attached Script lab
3. Click 'Insert 2 content control in the same paragraph' 
4. Click 'Insert Nested Content Control' 
   (This step will insert a content control into the second content control)

6. Click 'Insert Content'
   (This step will insert a file has a content control inside into the second content control)

8. Click 'Count of content controls'

Notice in the console, the count of content control was 4 (but expected is 3)

![case2-fail](https://user-images.githubusercontent.com/89008454/217704718-5a40d319-cd5a-4dac-9bec-fca523f4772b.gif)

Note that `context.document.contentControls.items` return correct values if we insert content controls in a different paragraph

![case2-pass](https://user-images.githubusercontent.com/89008454/217704740-5caaf7bf-a25c-403e-83e4-819e0a16340e.gif)

Script Lab: https://gist.github.com/tranhuyentran23/3601c71b5e2a0a7c198bbea9caa2c4a4

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @tranhuyentran23. Connecting you with @wangyun-microsoft who may be able to help.
