### ISSUE TITLE
Errors processing 10-12 page document in Office 365 @office-js

### ISSUE THREAD

**Issue by AlexYovenko** [OfficeDev/office-js#314]
Word online almost always broken after manipulating  with big documents.

Code example:
Word.run(function (context) {
  let foundItems: Word.RangeCollection = context.document.body.search("and", { matchCase: false, matchWholeWord: false }).load('items/NoPropertiesNeeded');
    return context.sync().then(function () {
      for (var i = 0; i < foundItems.items.length; i++) {
        foundItems.items[i].insertText('replaced', 'Replace');
      }
    });
  }).catch(function (error) {
    console.log(error);
  });
It works, but when word online try to autosave changes,I get next error: 

“POST https://word-edit.officeapps.live.com/we/OneNote.ashx 500 (Internal Server Error)” and then I need to reload page.

It works perfect in Desktop Word
[Document20.docx](https://github.com/OfficeDev/office-js-docs/files/1136275/Document20.docx)

#office-js

**Comment by JuaneloJuanelo** [comment]
i just tried the sample code to replace with a 100+ page document. It was slow but all the code got successfully executed. Did not get any errors.

**Comment by docu-bill** [comment]
> i just tried the sample code to replace with a 100+ page document. It was slow but all the code got successfully executed. Did not get any errors.

Did you try it with the example document?

**Comment by Yuchao9145** [comment]
Issue still happening, it happens randomly from time to time
