### ISSUE TITLE
When normal routing is enabled in an Angular 15 application, the OfficeJS library causes an infinite redirect loop. Hash based routing works.

### ISSUE THREAD

**Issue by roldengarm** [OfficeDev/office-js#3147]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Windows
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2301
* Operating System: Windows 11
 
## Expected behavior
I can use normal routing in an Office Addin based on Angular 15.

## Current behavior
I've got an almost empty Angular app configured as Office Addin. Once I import the Angular Routing module without any routes, upon reloading it gets into a redirect loop. It keeps adding /# at the end of the URL. Within a couple of seconds the URL is:

http://localhost:4200/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/... and growing.

When I enable hash based routing, it does not occur. However, I need normal (path based) routing.

## Steps to reproduce
1. Create an Angular app and add the OfficeJS libraries in the index.html
2. Configure the manifest.xml and specify e.g. localhost:4200 as URL
3. Add `RouterModule.forRoot([])` to the root app module imports

## Context
Trying to enable normal routing in an Angular based Office Add-in.
I want to use MSAL as well, but hashes in redirect URL's are not supported. Therefore I need to be able to use normal routing, without having to reside to hacks.

## Useful logs
There are no logs.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by xuruiyao-msft** [comment]
@roldengarm  Thank you for reporting this issue. Did you configure the redirect settings in configuration files or auth guard service?

**Comment by roldengarm** [comment]
Nope, I did not configure any redirect or auth guard. Once I add `RouterModule.forRoot()` the redirect happens.

I also noticed the following related issues:
https://github.com/OfficeDev/office-js/issues/1198
https://github.com/OfficeDev/office-js/issues/1344
https://github.com/OfficeDev/office-js/issues/429

Can you please fix this?

**Comment by callvm** [comment]
Any fixes for this? I just added office-js to Angular via the script tag below, and am facing the same issue of having hashes in my URL and repeating links i.e. http://localhost:4200/login#/login

**Comment by roldengarm** [comment]
@callvm I've got a working workaround. In your index.html, load the Office JS script like this:

```
<script>
      // this late load is required due to bug in office-js causing a routing loop
      // https://github.com/OfficeDev/office-js/issues/1198
      // https://github.com/OfficeDev/office-js/issues/1344
      // https://github.com/OfficeDev/office-js/issues/429
      let replaceState = window.history.replaceState;
      let pushState = window.history.pushState;
      var head = document.getElementsByTagName('head')[0];
      var script = document.createElement('script');
    </script>
    <script
      type="text/javascript"
      src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"
    ></script>
    <script>
      Office.onReady().then(() => {
        console.log('Office is ready!');
        window.history.replaceState = replaceState;
        window.history.pushState = pushState;
      });
    </script>
```
