### ISSUE TITLE
insertOoxml seems to ignore provided tab stops if only 1 parapgraph is inserted

### ISSUE THREAD

**Issue by entonio** [OfficeDev/office-js#3149]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I'm writing an Office Add-in, and trying to insert a paragraph using `insertOoxml`. I'm defining the custom tab stops for the paragraph, but they seem to be ignored by Word. The paragraph is inserted, it begins with a tab and ends with a tab just as requested, but the tabs' positions and character are simply ignored. The paragraph will use whatever tab stop definitions were there at the insertion point, or none if there were none. The issue apparently goes away if the provided OOXML contains more than one paragraph.

## Your Environment
* Platform: PC
* Host: Word
* Office version number: 2016, 2021
* Operating System: Windows
 
## Expected behavior
The document shows the provided tab stops.

## Current behavior
The inserted paragraph adopts the same tab stops that were at the insertion point, if any.

## Steps to reproduce
1. Run the following example:

```xml
export async function run() {
  return Word.run(async (context) => {

    const xml = `
<pkg:package xmlns:pkg='http://schemas.microsoft.com/office/2006/xmlPackage'>
    <pkg:part pkg:name='/_rels/.rels' pkg:contentType='application/vnd.openxmlformats-package.relationships+xml' pkg:padding='512'>
        <pkg:xmlData>
            <Relationships xmlns='http://schemas.openxmlformats.org/package/2006/relationships'>
                <Relationship Id='rId1' Type='http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument' Target='word/document.xml'/>
            </Relationships>
        </pkg:xmlData>
    </pkg:part>
    <pkg:part pkg:name='/word/document.xml' pkg:contentType='application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml'>
        <pkg:xmlData>
            <w:document xmlns:w='http://schemas.openxmlformats.org/wordprocessingml/2006/main' >
                <w:body>
                    <w:p>
                        <w:pPr>
                            <w:tabs>
                                <w:tab w:val="left" w:leader="underscore" w:pos="851"/>
                                <w:tab w:val="right" w:leader="underscore" w:pos="7880"/>
                            </w:tabs>
                        </w:pPr>
                        <w:r>
                            <w:rPr>
                                <w:color w:val="FF66D9"/>
                            </w:rPr>
                            <w:tab/>
                        </w:r>
                        <w:r>
                            <w:t xml:space="preserve">Hello </w:t>
                        </w:r>
                        <w:r>
                            <w:rPr>
                                <w:b/>
                            </w:rPr>
                            <w:t>World</w:t>
                        </w:r>
                        <w:r>
                            <w:t>!</w:t>
                        </w:r>
                        <w:r>
                            <w:rPr>
                                <w:color w:val="D9FF66"/>
                            </w:rPr>
                            <w:tab/>
                        </w:r>
                    </w:p>
                </w:body>
            </w:document>
        </pkg:xmlData>
    </pkg:part>
</pkg:package>
`
    context.document.body.insertOoxml(xml, Word.InsertLocation.replace)
    await context.sync()
  });
}
```

2. Notice that all elements are inserted except for the tab stops;
3. Add an empty `<w:p/>` after `</w:p>` and run again;
4. Notice that the tab stops are now inserted.

**Comment by xuruiyao-msft** [comment]
@entonio Thank you for reporting this issue.
![image](https://user-images.githubusercontent.com/5762929/220425589-056e6842-760d-4a10-9067-4bd7b8059d18.png)
I insert the xml in a new created document in Word 2021, and the tab is inserted successfully. The pink tab is at the start position before 'Hello' and the green tab is after the '!' at the end position of the paragraph.
Is it as expected? Would you please help describe the expected details?

**Comment by entonio** [comment]
@xuruiyao-msft thanks for your reply.

As I've mentioned in the OP, the `<w:tab/>` inside `<w:r>` are inserted, it's the tab stop definitions inside `<w:tabs>` that are ignored. In your picture, the first tab should be an underscore going from 0 to 1.5 cm (851 twips), and the second one should be also an underscore, but going from `!` to 13.9 cm (7880 twips).

If you edit the XML and add the second, empty `<w:p/>` I've mentioned, you'll probably see the expected outcome.

**Comment by xuruiyao-msft** [comment]
@entonio Thanks for your explanation. After the empty <w:p/>added, the tab stop are inserted as what you defined.
![image](https://user-images.githubusercontent.com/5762929/220860648-2f16be7b-e702-4023-a6f2-8679edfff6f0.png)

We create a work item 7632223 to track this issue. Once there's any update, we will sync with you. Thank you for reporting this issue.

**Comment by entonio** [comment]
I'm confused by the 'not planned' resolution. This is not a feature request, it's a bug, and imo a serious one. The only way for people not to be affected by it is if they're not making much use of the whole plugin API.
An internal work item has been mentioned, is that what was shelved? Or was it inactivity here? Or is this a wontfix by another name?
