### ISSUE TITLE
getFilePropertiesAsync inconsistent behavior

### ISSUE THREAD

**Issue by darkocolak** [OfficeDev/office-js#315]
Hi, 
Issue is described here:
https://stackoverflow.com/questions/44718678/officejs-calls-fail-with-7000-permission-denied-for-new-file

Mind that this happens both for new files and for opened files in online apps.
Most of the errors occur when working on PowerPoint presentations where I cannot retrieve file properties in the addin almost always.

What can be the cause of this? Is file not ready to be opened? If not how can we make it?

**Comment by draconnus** [comment]
We gave up on the feature back then. 
Maybe we can try it out soon again. I'll try to report back.

**Comment by kbrandl** [comment]
Thank you for the update, and once again, apologies for the lack of response on our part. The Office.js API and platform has evolved a lot since this issue was opened; I'll attempt to repro this issue and will report back here with my findings.

**Comment by JuaneloJuanelo** [comment]
i just tried the methods on Excel, Word and PPT Online and this is no longer a repro. Issue solved!
