### ISSUE TITLE
Unable to get property 'addEventHandler' of undefined or null reference

### ISSUE THREAD

**Issue by ihor-chepurnyi** [OfficeDev/office-js#3150]
# Provide required information needed to triage your issue
We have a function to open a dialog. We call `displayDialogAsync` function with a callback. In callback we want to add custom event handler, but we get the following error `Unable to get property 'addEventHandler' of undefined or null reference` when customer opens a dialog. We use the following code:

```ts
export const openModal = () => (
  dispatch: Dispatch<unknown, unknown>
): void => {
  Office.context.ui.displayDialogAsync(
    `our-api-endpoint`,
    {
      displayInIframe: true,
    },
    (result): void => {
      const dialog: Office.Dialog = result.value

      // here we get that error, dialog variable is undefined
      dialog.addEventHandler( 
        Office.EventType.DialogMessageReceived,
        closeModal(dialog, dispatch)
      )
    }
  )
}
```
**Note: we get this error only on the specific office version - `16.0.5257.1000`. As a result customers see just blank window**

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.5257.1000
* Operating System: Windows 10.0
* Browser (if using Office on the web): ______
 
## Expected behavior

Dialog opens without error and `const dialog: Office.Dialog` shouldn’t have a value - `undefined`

## Current behavior

Dialog opens without a content and in console we see the following error - `TypeError Unable to get property 'addEventHandler' of undefined or null reference`

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

Customers on the office version - `16.0.5257.1000` see blank modal window without a content.

## Useful logs

- [x] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Stacktrace from the console:
```
TypeError Unable to get property 'addEventHandler' of undefined or null reference 
    actions/insertAvailability.ts:93:6 Anonymous function
    https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.01.js:11:49504 OSF.DDA.issueAsyncResult
    https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.01.js:11:62166 i
    https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.01.js:11:67154 OSF.DDA.SafeArray.Delegate._onException
    https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.01.js:11:71687 OSF.DDA.SafeArray.Delegate.registerEventAsync
    https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.01.js:11:62774 Anonymous function
    https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.01.js:11:87195 value
    actions/insertAvailability.ts:80:2 Anonymous function
    ../node_modules/redux-thunk/es/index.js:7:8 Anonymous function
    bugsnag-config.js:43:2 Anonymous function
```

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@ihor-chepurnyi, looking at your code snippet, it seems you are using the `value` of the `result` without checking for any errors. Can you stringify `result` or `result.error` and share it here, assuming there's an error?
