### ISSUE TITLE
Unable to load add-in from App store

### ISSUE THREAD

**Issue by gelicas** [OfficeDev/office-js#3152]
This error `Add-in Error We couldn't connect to the 'Office Store' catalog server for this add-in.` is shown when user tries to access the add-in.

![image](https://user-images.githubusercontent.com/35692003/218936933-be3221f2-f16c-4580-8c4e-ba8f5bd8d823.png)

Steps to reproduce:
1. Open new excel file
2. Download our app from app-store (FactSet for Excel)

Also tried removing and re-adding the add-in from the store but the same error persists.

**Update**:
- There hasn't been any recent update on the manifest since last year, and it seems this issue is only occurring for some users based on their region. 

- This error does not appear if we are connected in US and AU using VPN but it does appear for certain regions such as PH, HK, and IN as well.

**Comment by Wenjun-Gong** [comment]
@penglongzhaochina , please help to take a look. I can repro on Excel Online.

**Comment by penglongzhaochina** [comment]
***@***.*** ***@***.***> to take a look.

Thanks,
Penglong

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by wh1t3cAt1k** [comment]
The issue affects us and it's **bad**, there is no workaround it seems unless you insert the add-in from a desktop Excel instance.

See video below using our "Velixo" add-in from the store:

https://www.loom.com/share/32d3b56e6e8443d7b4cd1e8bfafe5f81

I want to plead with you guys to fix it urgently.

**Comment by Wenjun-Gong** [comment]
Our engineers are actively working on the fix right now. Please stay tuned.

**Comment by Wenjun-Gong** [comment]
Hi all, the fix is rolling out right now. Please verify in a few hours to see whether the problem still exists. Thanks.

**Comment by EdwinStraver** [comment]
We see mixed results; some users see the issue resolved; others still have the problem.

**Comment by HPLewis9** [comment]
I am still experiencing the issue and I have started to receive reports from our clients.

**Comment by mattgeim** [comment]
As of now the fix is still rolling out and we are actively working on finalizing it. I will update this issue when it has completed the process.

**Comment by mattgeim** [comment]
The fix should be fully deployed at this point - please note that caches may need to be cleared / sessions restarted.  I will leave this issue open for now and close it tomorrow assuming no additional issues are reported.

**Comment by gelicas** [comment]
Observed the same scenario with us, where some of my team can access the add-in without the error while some users cannot, re-tried it after a couple of hours and the issue seems to have been working on my end now. 

Confirming that we no longer experience the add-in error.
 
Thanks @Wenjun-Gong and @mattgeim!

**Comment by mattgeim** [comment]
Please feel free to reopen this issue if additional problems arise. Thanks!
