### ISSUE TITLE
Why no Store tab in Office Add-ins on MacOS?

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#3153]
Hi,

I want to install an Office Add-in from Microsoft store, but I can't see the Store tab under Office Addins. Photo attached.
<img width="882" alt="Screenshot 2023-02-15 at 13 42 24" src="https://user-images.githubusercontent.com/3756051/219018579-d892a0f9-380f-42aa-aff6-f07c444d7225.png">

Does anybody know how to see the store tab?

Thanks,
Daniel

**Comment by mattgeim** [comment]
Hi @danielpdev, is there any additional information you can share, such as if this is new behavior or a change that wasn't expected? Are you developing an application or is this looking for help on using the insertion dialog to access the store?  Has a tenant administrator disabled this experience possibly? 

You can find information on the various settings available to control access to add-ins here:  https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/privacy-and-security#optional-connected-experiences 

thanks!
