### ISSUE TITLE
Capture Appointment Click Event

### ISSUE THREAD

**Issue by purplemaestro** [OfficeDev/office-js#3154]
I am currently working on Office JS based Outlook Addin where my main purpose is to capture Appoinment Item click event and from that click I will open up the Taskpane.

I have also checked this link provided by microsoft: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest in which they have provided very few event based activation events.

But I am still wondering if there is a way to achieve it.

I tried several things like Office.context.mailbox.addHandlerAsync inside the launchevent.js file and this is the error message I am getting: Cannot read properties of undefined (reading 'addHandlerAsync')

**Comment by exextoc** [comment]
It appears your scenario is about selecting an appointment / event on the calendar surface and then opening up a taskpane to view/interact with the selected appointment / event. If that is accurate, this behavior is not supported by the product. Outlook add-in feature requests are tracked on our Tech Community page (https://aka.ms/M365dev-suggestions). Please submit a request there and choose the appropriate label(s). Feature requests are considered when we go through our planning process.

**Comment by purplemaestro** [comment]
thank you so much for your response.  🙏

**Comment by purplemaestro** [comment]
> It appears your scenario is about selecting an appointment / event on the calendar surface and then opening up a taskpane to view/interact with the selected appointment / event. If that is accurate, this behavior is not supported by the product. Outlook add-in feature requests are tracked on our Tech Community page (https://aka.ms/M365dev-suggestions). Please submit a request there and choose the appropriate label(s). Feature requests are considered when we go through our planning process.


thank you so much for your response. 🙏
