### ISSUE TITLE
Notification messages can't be made persistent in Outlook

### ISSUE THREAD

**Issue by eugene-plutoflume** [OfficeDev/office-js#3155]
# Provide required information needed to triage your issue
The [persistent](https://learn.microsoft.com/en-us/javascript/api/outlook/office.notificationmessagedetails?view=outlook-js-preview#outlook-office-notificationmessagedetails-persistent-member) property of the [Office.NotificationMessageDetails](https://learn.microsoft.com/en-us/javascript/api/outlook/office.notificationmessagedetails?view=outlook-js-preview) interface
specifies if the message should be persistent. It is only applicable when type is `InformationalMessage`. If true, the message remains until removed by this add-in or dismissed by the user. But that is not true, sounds like a bug. Please confirm that.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft Outlook for Microsoft 365 MSO (Version 2301 Build 16.0.16026.20196) 64-bit 
* Operating System: Windows
* Browser (if using Office on the web): Edge (based on Chromium)
 
## Expected behavior

The notification message should remain visible for the Outlook item when the selection is changed in Outlook or items are opened.

## Current behavior

In Outlook on the web the notification message is vanished as soon as the selection is changed. In Outlook for a PC desktop the notification item is preserved only when item re-selected once. Any further openings vanish the notification message. 

## Steps to reproduce

1. In a compose mode your add-in adds a persistent notification message (`InformationalMessage`) 
2. Close the composed message and select any other item in Outlook.
3. Find the composed item where a notification message was added and select it in the Explorer window or open in the inspector window. 
4. In OWA you will not find the persistent notification item, on a PC desktop the item may be displayed once and then removed before any other views.

## Context
Sounds like on the PC desktop the behavior corresponds to error notifications where the message persists until the user sees it once. In OWA it doesn't work at all.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding persistent notification messages. It has been put on our backlog. We, unfortunately, have no timelines to share at this point 
 
Internal tracking id: Office: 3402248

**Comment by exextoc** [comment]
@eugene-plutoflume  Could you please try emptying the Cache and performing a hard refresh, to see if this resolves the issue?

**Comment by Paul-Morton-Hyland** [comment]
We are also seeing this defect and would like the notification to remain persistent. do we know when this will be resolved?

**Comment by gonfalon** [comment]
Also ran into this issue while developing an add-in. We were counting on the functionality.
