### ISSUE TITLE
Word: startNewList always generates an empty list item

### ISSUE THREAD

**Issue by roldengarm** [OfficeDev/office-js#3156]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I'm trying to add a bullet point list to the document, but it always adds an empty list item which I'm unable to delete.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office Desktop Windows. 
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16026.20146
* Operating System: Windows 11
* Browser (if using Office on the web): n/a
 
## Expected behavior
To have a bullet point list without empty items.
I![image](https://user-images.githubusercontent.com/37638588/219117770-f2895379-f52a-4dbb-af87-e70b674f525b.png)

## Current behavior
An empty item in the list,.

![image](https://user-images.githubusercontent.com/37638588/219117728-ca644845-52ad-4bd8-89a4-b2965a34a53e.png)

## Steps to reproduce
Use below code:
```
await Word.run(async (context) => {
      const paragraphs = context.document.body.paragraphs;
      paragraphs.load('$none');

      await context.sync();

      // Start new list using the second paragraph.
      const list = paragraphs.items[1].startNewList();
      list.load('$none');

      await context.sync();

      // To add new items to the list, use Start or End on the insertLocation parameter.
      list.insertParagraph('New list item at the start of the list', 'Start');
      list.insertParagraph('New list item at the end of the list', 'End');

      await context.sync();
    });
```

## Context
I'm trying to add a bullet point list to the document without empty items.

**Comment by xuruiyao-msft** [comment]
@roldengarm Hi, is the paragraphs.items[1] a empty paragraph which means there is no characters in this paragraph but only one Carriage return? 
If yes, then the "paragraphs.items[1].startNewList()" would generate a list with a bold bullet bot before the empty paragraph. If you insert new paragraphs at start and end  of the empty paragraph (empty list item), then the new paragraphs are inserted to generate two extra list item around the empty list item. This is by design and is expected behavior. 

Would you please try this piece of code:


```
const list = paragraphs.items[1].startNewList();   
list.load('$none');    
await context.sync();     
paragraphs.items[1].**insertText**("New list item at the start of the list", "End");    // insert text on the paragraph of the list using 
                                                                                                                                  //"End" parameter it will write text on 
                                                                                                                                 // the existing list
paragraphs.items[1].list.insertParagraph('New list item at the end of the list', 'End');
await context.sync();
```

It would behave like what you expect.

If any further question, feel free to let me know. Thanks for reporting this issue.

**Comment by roldengarm** [comment]
@penglongzhaochina awesome, thank you. That indeed solved the problem!
Would be great though to add this to the documentation, especially with your example code.

**Comment by penglongzhaochina** [comment]
@roldengarm  you are welcome. Will do. Thanks!
