### ISSUE TITLE
Office.addin.showAsTaskpane() often shows gray screen

### ISSUE THREAD

**Issue by sclarke500** [OfficeDev/office-js#3157]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Overview
A Word add in using shared runtime makes the showAsTaskpane call.  About half of the time Word opens the panel, but displays a gray screen.  Resizing the taskpane or Word window results in screen displaying properly.

Possible related issue https://github.com/OfficeDev/office-js/issues/2538 (*but* is Excel and does not seem to be occasional)

## Environment
PC Desktop
Word 2019 MSO (Version 2208 Build 16.0.15601.20280) 32-bit
Windows 11
 
## Expected behavior
Taskpane should display properly

## Current behavior
Taskpane opens but shows an empty gray screen that does not respond to mouse clicks (ie right-click does nothing)
Resizing the taskpane or resizing the Word window itself causes taskpane to display properly. 

### On doc open we often see:
![Image1](https://user-images.githubusercontent.com/6739206/219139468-8004bfbe-ec46-4c12-88dd-862a63825577.png)

### After window resize:
![Screenshot_4](https://user-images.githubusercontent.com/6739206/219138882-566f4361-cfa6-4bf0-89a8-3c1d3115db2e.png)

## Steps to reproduce
1. Create a Word Addin using shared runtime;
2. In the Office.onReady call set the startup behavior to load;
3. In the onReady call also call showAsTaskpane();
4. Open addin in a document & save the document;
5. Open the document and the taskpane will display. Approx 50% of the time it will display as a gray screen.

minimal repo that reproduces issue:
https://github.com/sclarke500/hello-world-addin

## Context
In my use case I want to conditionally display the taskpane on document open, rather than setting it to always open.  Example conditions are whether certain features are available, or the data linked to the document has changed.

**Comment by EdwinStraver** [comment]
Yes, I see this behavior extremely frequent in my Excel taskpane as well.

Edwin

**Comment by EdwinStraver** [comment]
P.S. i think this is the exact same issue as #3101
