### ISSUE TITLE
Image sizing works differently between Excel for web and Excel for Windows

### ISSUE THREAD

**Issue by timbarclay** [OfficeDev/office-js#3162]
# Provide required information needed to triage your issue

Images placed using the office js API react differently when resized between Excel on the web and Excel for Windows. The specifics of the difference seem to have to do with what happens if you resize the row that the image is sitting in. On Excel on Windows, if you set the height and width of an image and then resize a row, the image retains the width and height it was set to. However on Excel on the web, if you set the height and width of an image and then resize a row, the image gets resized further based on the row.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

If you place an image and then set its height and width, I would expect the image to retain the set height and width regardless of whether the cells under it get resized. Moreover, I would expect this behaviour to be the same between Excel on Windows and Excel on the web.

This is the code that adds the image and sets its size as well as the height of the row under it.

```typescript
const sheet = context.workbook.worksheets.getActiveWorksheet();

const shape = sheet.shapes.addImage(logo.data);
shape.height = 200;
shape.width = 300;

const range = sheet.getRange("A1");
range.format.rowHeight = 210;

await context.sync();
```

## Current behavior

On the web, the image appears to end up the height that the image was set to plus the height that the cell was set to. On Windows it behaves as I would expect.

On Excel for Windows, it looks like this
![image native](https://user-images.githubusercontent.com/6851865/220166422-e1668220-5120-4ec2-8956-e2e929730994.png)

On Excel on the web, it looks like this
![image web](https://user-images.githubusercontent.com/6851865/220166451-ea43516c-4dda-4a26-a18c-9acaed36df5c.png)

## Steps to reproduce

1. Clone [this reproduction repo](https://github.com/timbarclay/excel-image-size-repro), `npm install`
2. run it on the web (`npm run start:web`) and click the Run button in the add-in
3. run it on Windows (`npm run start`) and click the Run button in the add-in

## Context

This makes it difficult to add images and style them in a way that works consistently between Excel on different platforms. A workaround seems to be to set the row height first and then add the image afterwards.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by dingjin-ms** [comment]
Hi @timbarclay , thank you for reporting the issue and sorry for any inconvenience. We could easily repro the problem based on your description and opened a bug #7628039 internally to track the issue. 

As you describe, you could try to change the row height (below script might be working) and unblock yourself first while we are fixing the issue. And please let us know if it's still blocking you.
```
async function run() {
  await Excel.run(async (context) => {
    // Add image
    const sheet = context.workbook.worksheets.getActiveWorksheet();

    const shape = sheet.shapes.addImage(logo.data);
    shape.height = 200;
    shape.width = 300;

    const range = sheet.getRange("A1");
    range.format.rowHeight = 210;

    await context.sync();

    sheet.getRange("A1").format.autofitRows();

    await context.sync();
  });
}
```

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.

**Comment by dingjin-ms** [comment]
Hi @timbarclay, we have just checked in the fix, and the fix will work online in less than a month. Thank you again for your reporting!
