### ISSUE TITLE
makeEwsRequestAsync fails when the response is >1mb

### ISSUE THREAD

**Issue by liamtim** [OfficeDev/office-js#3163]
# Provide required information needed to triage your issue

Our application allows our customers to create responsive HTML emails (in the form of company wide newsletters) & deliver them to their intended recipients via our Office 365 Web Add-in. After sending, we provide them with analytics to determine the success of their email. 

The recipients are typically Distribution lists, Dynamic Distribution lists, Office 365 groups or mail enabled security groups which are placed in the "To" field. 

The analytics we provide include:
- Number of recipients
- Open %
- Click through %

During the sending process, in order to calculate the number of recipients included in the "To" field, we use the [ExpandDL EWS function](https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/expanddl-operation). This allows us to capture the number of recipients nested within the DL(s) the user included in the "To" field. 

As we are dealing with enterprise organizations, the number of recipients nested within these lists can range from a few thousand, to tens of thousands. As a result, our customers often hit the (seemingly arbitrary) 1mb response limit as outlined in #289. 

In order to bypass this limitation, we had provided our customers with the option of creating a utility account & running this EWS call outside of the add-in (on our server) which would asynchronously occur once the email is sent. This relied on Basic Auth, which was deprecated by Microsoft EOY 2022. 

We can not build a Microsoft Graph Solution because Graph can not query Dynamic Distribution lists. (Seemingly another limitation). 

## Your Environment

* Platform: PC desktop, Mac, Office on the web
* Host: Outlook
* Office version number: N/A (All versions effected)
* Operating System: N/A (All OS versions effected)
* Browser: N/A All browser versions effected
 
## Expected behavior
We expect a valid response when making the EWS call.

<details><summary>Sample Successful Response</summary>
<p>

<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header>
        <h:ServerVersionInfo xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" MajorVersion="15"
            MinorVersion="20" MajorBuildNumber="6086" MinorBuildNumber="21" Version="V2018_01_08" />
    </s:Header>
    <s:Body>
        <m:ExpandDLResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
            <m:ResponseMessages>
                <m:ExpandDLResponseMessage ResponseClass="Success">
                    <m:ResponseCode>NoError</m:ResponseCode>
                    <m:DLExpansion TotalItemsInView="70" IncludesLastItemInRange="true">
                        <t:Mailbox>
                            <t:Name>John Smith</t:Name>
                            <t:EmailAddress>john@domain.ca</t:EmailAddress>
                            <t:RoutingType>SMTP</t:RoutingType>
                            <t:MailboxType>Mailbox</t:MailboxType>
                        </t:Mailbox>
                    </m:DLExpansion>
                </m:ExpandDLResponseMessage>
            </m:ResponseMessages>
        </m:ExpandDLResponse>
    </s:Body>
</s:Envelope>

</p>
</details>

## Current behavior

When a DL is queried and the response exceeds 1mb, we receive the following:
`'{"status":"failed","error":{"name":"GenericResponseError","message":"Response exceeds 1 MB size limit. Please modify your EWS request.","code":9020}}'`

## Steps to reproduce
1. Perform Office.context.mailbox.makeEwsRequestAsync against an object that results in the response being >1mb.

## Context
This limitation effects most large enterprise customers who we support with their Internal Communication strategy. Increasing this limit would allow our add-in to function as intended.

**Comment by exextoc** [comment]
Thanks for reporting this issue. We are working on increasing the Office.context.mailbox.makeEwsRequestAsync API response limit. Unfortunately, we do not have a timeline to share. We will update this thread and [documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/limits-for-activation-and-javascript-api-for-outlook-add-ins#:~:text=Exchange%20Web%20Services-%2c1%20MB%20number%20of%20characters%2c-Mailbox.makeEwsRequestAsync%20method) once this feature is available.

Internal Tracking ID:3441592

**Comment by liamtim** [comment]
Hi @exextoc - Wondering if you have an update to share here?

**Comment by exextoc** [comment]
Thank you for raising the issue. We are working on this. Unfortunately, we don't have any timelines to share with you at the moment.

**Comment by liamtim** [comment]
Hey @exextoc. Wondering if there are any updates here?

**Comment by exextoc** [comment]
Hey @liamtim ,

This issue has been fixed and verified for both Outlook for Web and Outlook for MacOS. Can you please confirm the same for us? Do get back to us if this issue still persists for you.

**Comment by liamtim** [comment]
@exextoc That's exciting! 

What is the new limit, if any?

Here's the result of my testing, from a request that previously returned:
`'{"status":"failed","error":{"name":"GenericResponseError","message":"Response exceeds 1 MB size limit. Please modify your EWS request.","code":9020}}'`

- OWA: Success ✔️
- Outlook on Windows new UI: Success ✔️ 
- Outlook on Windows Old UI: Success ✔️
- Outlook on Mac New UI: Failure ❌ response: `“{\“name\“:\“AccessRestricted\“,\“message\“:\“Internal protocol error: ‘-2147467259’.\“,\“code\“:9017}”`
- Outlook on Mac Old UI: Failure  ❌ response:
![Screenshot 2023-05-11 at 17 02 31](https://github.com/OfficeDev/office-js/assets/44294661/6194f517-2f54-41e1-8edb-97761a96badf)

**Comment by exextoc** [comment]
Hey,

Sorry about the haste, the fix for Outlook for Mac will be available from Build 16.73.23042601. You can either try out the build from insiders, or wait for this build to reach production. The new limit for requests is 5 MB.

**Comment by liamtim** [comment]
@exextoc Thank you for clarifying. I will test Outlook for Mac using the insider build. Which Outlook for Windows build/channel is the fix available on?

**Comment by exextoc** [comment]
Hi @liamtim, could you please help us understand what you mean by Windows build/channel. Looking at your earlier comment, it seems like you got a Success response from both Windows Old and New UI?

**Comment by liamtim** [comment]
@exextoc We have many customers who will be positively impacted by this change. I would like to be able to specify which version of Outlook in Windows they will need to be running in order to benefit from the change implemented by Microsoft. 

1. For OWA, I presume all versions now support the change.
2. For Mac, I can advise that build 16.73 and above (only available on New UI) will have the change available
3. I'm unsure of which Windows builds have included the fix, particularly because you did not mention Windows in your [initial comment.  ](https://github.com/OfficeDev/office-js/issues/3163#issuecomment-1543812130)

**Comment by exextoc** [comment]
Hi @liamtim, sorry for the delay. The fix should be available in win32 in a build 16.0.16224.* and beyond. Thanks!

**Comment by exextoc** [comment]
@liamtim To answer your previous question "What is the new limit, if any?" : The new limit is 5MB.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.

**Comment by liamtim** [comment]
@exextoc We still have a problem where some of our larger customers can not use our product due to to this limitation. Can the 5mb limit be further increased to accommodate.

Alternatively, we will need Microsoft Graph API to support querying Dynamic DLs to ensure products continue to work as intended.

**Comment by vikaslokhande1** [comment]
@exextoc , My outlook version is 16.83 but still not able to send mail more than 1 mb
