### ISSUE TITLE
No unload event when closing the taskpane

### ISSUE THREAD

**Issue by egloff** [OfficeDev/office-js#3167]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

The JavaScript window events "beforeunload" and "unload" seem only to be triggered when a 'Hard Refresh' (Ctrl-F5) is triggered but not when the taskpane is closed. Is this a bug or by design?

And if this is by design, how can we be notified in the add-in when a taskpane is closed (we need this for session handling/cleanup) in our Word and Outlook Add-In?

## Your Environment
* Platform: PC desktop
* Host: Word
* Office version number: Microsoft Word for Microsoft 365 MSO (Version 2210 Build 16.0.15726.20188)
* Operating System: Windows 10
* Browser (if using Office on the web): -
 
## Expected behavior
We expect the events to be triggered when closing the takspane (same as we close a tab or a browser-window).

## Current behavior
We only get the event when the taskpane is reloaded.

## Steps to reproduce
You can use the following Gist in ScriptLab which adds the text "beforeunload-event" and "unload-event" to the current document if the event is triggered in the add-in: https://gist.github.com/egloff/31f5ac416bce1815b481c9b18775fb34

## Context
We use this event to trigger the cleanup of session-data in our backend-servers.

**Comment by parlato-vooma** [comment]
Why is this issue closed? We've run into a similar issue. We're using Intercom's JS SDK in our add-ins and we've noticed that  in-app notification sounds still play after the user closes the add-in pane entirely. So there are two issues:

(1) Connections (websockets) that should be closed are still open after the add-in is closed
(2) There is no event that we can hook into to clean up / shutdown the Intercom integration (the issue mentioned in the original post above)

Is there really no plan to address this?

**Comment by jimbarrett33** [comment]
Ditto. Why is this closed? Seems like a very reasonable request. And there is no way the VSTO add-in type did not know when they were being closed. So, in the interest of VSTO parity, this should be addressed.

**Comment by thekingofspain** [comment]
Same request, need this to manage the deletion of content that was uploaded to an external system via the soon to be destroyed taskpane.

**Comment by RuizhiSunMS** [comment]
Hi @egloff , @jimbarrett33 @thekingofspain and @parlato-vooma , looks like your issue here is more like a feature request, we suggest you look for the same request or submit your own request on our dev community https://techcommunity.microsoft.com/category/microsoft365/ideas/microsoft365developerplatform. Our pm will review the list and convert requests with enough votes into real work items.
Thx.
