### ISSUE TITLE
MacOS - Office.AppointmentCompose.saveEventAsync loses Recurrence

### ISSUE THREAD

**Issue by thoffmann-fms** [OfficeDev/office-js#3169]
MacOS Outlook16.7 (New). Create a daily recurring meeting. Run an add-in that calls Office.context.mailbox.item.recurrence, then calls saveEvent, and then calls Office.context.mailbox.item.recurrence again. The first call returns Daily recurrence data, the last call returns null.  Close the add-in. Note the UI still shows the meeting as being recurring. Click Save.  Only a single day event is created.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.70
* Operating System: 13.2.1
* Browser (if using Office on the web): n/a
 
## Expected behavior
Recurrence data should not disappear.

## Current behavior
Recurrence data is lost and a non-recurring meeting is created by Outlook.

## Steps to reproduce

1. Create a daily recurring meeting
2. Open an Add-In
3. Invoke Office.context.mailbox.item.recurrence.getAsync(). Note the response shows a daily response
4. Invoke item.SaveAsync()
5. Invoke Office.context.mailbox.item.recurrence.getAsync(). Note the response is null.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details
Snippet to get occurrence data:
```
      let recurrence: Office.Recurrence = null;
      if (Office.context.mailbox.item.recurrence === null) {
        DebugLog(kDebugWho, caller + ", item.recurrence is null");
        SetEventOccurrenceMode(OccurrenceMode.None, null);
        resolve();
        return;
      }

      DebugLog(kDebugWho, "SetupRecurrenceDataAsync: check recurrence.getAsync from " + caller);
      if (typeof Office.context.mailbox.item.recurrence.getAsync === "undefined") {
        DebugLog(kDebugWho, "SetupRecurrenceDataAsync: use recurrence");
        recurrence = Office.context.mailbox.item.recurrence;
      } else {
        DebugLog(kDebugWho, "SetupRecurrenceDataAsync: use recurrence.getAsync from " + caller);
        recurrence = await GetOutlookStructureAsync("recurrence", Office.context.mailbox.item.recurrence);
        if (recurrence === null) {
          DebugLog(kDebugWho, "SetupRecurrenceDataAsync: no recurrence from " + caller);
          // No recurrence
          resolve();
          return;
        }
      }
```
Save event:
```
export const SaveEventAsync = (evt: Office.AppointmentCompose): Promise<string> => {
  const who: string = "SaveEventAsync";
  return new Promise<string>(async (resolve, reject) => {
    try {
      evt.saveAsync({}, (asyncResult: Office.AsyncResult<string>) => {
        resolve(asyncResult.value);
      });
    } catch (e) {
      DebugLogError(who, "Catch " + e.message);
      resolve(undefined);
    }
  });
};
```

## Useful logs

- [X] Console errors
```
~11:41:33 AM; GetOutlookStructure recurrence recurrence
  Start
~11:41:33 AM; GetOutlookStructure recurrence recurrence
  {"recurrenceType":"daily","recurrenceProperties":{"interval":1},"recurrenceTimeZone":{"name":"Eastern Standard Time","offset":-300},"seriesTime":{"startYear":2023,"startMonth":2,"startDay":21,"endYear":2023,"endMonth":2,"endDay":24,"startTimeMinutes":810,"durationMinutes":30}}
~11:41:35 AM; RecurrenceOperations
  SetupRecurrenceDataAsync: after SaveEvent
~11:41:35 AM; RecurrenceOperations
  SetupRecurrenceDataAsync: check recurrence.getAsync from after SaveEvent
~11:41:35 AM; RecurrenceOperations
  SetupRecurrenceDataAsync: use recurrence.getAsync from after SaveEvent
~11:41:35 AM; GetOutlookStructure recurrence recurrence
  Start
~11:41:35 AM; GetOutlookStructure recurrence recurrence
  null
~11:41:35 AM; RecurrenceOperations
  SetupRecurrenceDataAsync: no recurrence from after SaveEvent
```
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@thoffmann-fms We tried this scenario and it's working as expected. Can you once try following code snippets instead to get recurrence and save item 
```
//Save an item async
Office.context.mailbox.item.saveAsync
(
	function(asyncResult)
	{
		console.log(JSON.stringify(asyncResult));
	}
);

// Get recurrence type of item
function myCallback(asyncResult)
{
  var recurrence = asyncResult.value;
  if (recurrence == null)
   {
    console.log("Non-Recurring Meeting");
	  return;
   }
  console.log("Type:" + recurrence.recurrenceType);
}
```

**Comment by exextoc** [comment]
Please ignore the previous comment. We are able to reproduce the issue. 
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office : 7664303

**Comment by exextoc** [comment]
The fix is checked in and should be available in build 16.73 (23040700) onwards.

**Comment by thoffmann-fms** [comment]
Thank you, I'll check this week to see if I have access to that release.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
