### ISSUE TITLE
CustomXMLPart operations don't appear to be relaying events properly?

### ISSUE THREAD

**Issue by sancarn** [OfficeDev/office-js#317]
I have a VBA class containing the following code:

```vb
Public WithEvents part as CustomXMLPart
Private Sub Class_Initialize
  set part = wb.CustomXMLParts.SelectByNamespace("someNamespace")(1)
end sub
Private Sub part_NodeAfterInsert(ByVal NewNode As Office.CustomXMLNode, ByVal InUndoRedo As Boolean)
    debug.print "NodeInserted"
end sub
Private Sub part_NodeAfterReplace(ByVal OldNode As Office.CustomXMLNode, ByVal NewNode As Office.CustomXMLNode, ByVal InUndoRedo As Boolean)
    debug.print "NodeReplaced"
end sub
```

In OfficeJS I have something akin to this:

```js
async function setXML() {
    return await Excel.run(async (context) => {
        var elements = context.workbook.customXmlParts.getByNamespace("someNamespace");
        elements.load("values");
        await context.sync();

        //Get XML
        const customXmlPart : Excel.CustomXmlPart = elements.items[0];
        const xmlBlob = customXmlPart.getXml();
        await context.sync();

        //Extract XML data
        console.log(xmlBlob.value);
        var xml = jQuery.parseXML(xmlBlob.value);

        //Handle xml
        xml = processXML(xml)  //removes an existing node, adds a new node

        //Set newXML data
        var sXML = (new XMLSerializer()).serializeToString(xml);
        customXmlPart.setXml(sXML);
        await context.sync();
        return
    });
}
```

So it turns out that `part_NodeAfterReplace` and `part_NodeAfterInsert` is never called...? I can clarify that the xml data is being changed though. I assume this is a bug?

**Comment by JuaneloJuanelo** [comment]
in this case you are replacing the entire part, not a node, so those are not expected to be triggered.  IN Excel XML part support is limited to replacing the entire part, there is no node-level access.

Also in JS API we still dont have such events in Excel (we do in Word, though).

please add such requests on user voice so we consider them as additions in the future. https://officespdev.uservoice.com/
thanks!

**Comment by sancarn** [comment]
Hi Juan,

> in this case you are replacing the entire part, not a node

Is it possible to replace/add a single node from JavaScript? As far as I am aware there is only `getXML()` and `setXML()` functions, correct? I.E. is there a work around I can use such that the events are raised?

Thanks
