### ISSUE TITLE
How to paste drawing canvas with images into a smaller one to be resized automatically

### ISSUE THREAD

**Issue by kkokah** [OfficeDev/office-js#3170]
Hello, this is our first question here, please advise if this is the right place to post our question.

We're trying to achive a built-in functionality that Word does using Office-JS but were wondering if it's possible.

We have two drawing canvases, one is larger, contains several images and shapes. And the other one is smaller and is empty. 

In Word, we can go to the large drawing canvas, press CTRL+A to select all contents inside the canvas, then go to the other smaller drawing canvas and simply paste it and everything will be resized automatically.

We're trying to automate this process but it doesn't give us the same result. Using Office-JS API, we get the OOXML of the canvas, then we use context.document.body.insertOoxml to insert that OOXML into the new canvas, the contents are inserted but it doesn't do the resize automatically to fit the smaller canvas. 

Is there any other way to accomplish that? 

Thank you.

**Comment by kkokah** [comment]
Update: Here's what we've tried so far but with no result. 
```
 // Get all paragraphs 
 let xmlContent;
 xmlContent = doc.body.getOoxml();
 await context.sync();

 const parser = new DOMParser();
 let xml: Document = parser.parseFromString(xmlContent.value, 'application/xhtml+xml');
 const paragraphs = xml.getElementsByTagName('w:p');

for (let i = 0; i <= paragraphs.length - 1; i++) {
  if (paragraphs[i].getElementsByTagName('w:sdtPr').length > 0
    && paragraphs[i].getElementsByTagName('w:sdtPr')[0].getElementsByTagName('w:id')[0].getAttributeNode("w:val").value === '1234306') {
    targetCanvasParagraph = paragraphs[i + 1];
 }

let drawings = targetCanvasParagraph.getElementsByTagName('w:drawing');
let factor = 1.724156661532341;
for (let i = 0; i < drawings.length; i++) {
let positionH = drawings.item(i).getElementsByTagName('wp:positionH')[0];
if (positionH) {
  let posOffsetH = positionH.getElementsByTagName('wp:posOffset')[0];
  posOffsetH.textContent = (Math.trunc(Number(posOffsetH.textContent) / factor)).toString();
}

let positionV = drawings.item(i).getElementsByTagName('wp:positionV')[0];
if(positionV){
  let posOffsetV = positionV.getElementsByTagName('wp:posOffset')[0];
  posOffsetV.textContent = (Math.trunc(Number(posOffsetV.textContent) / factor)).toString();
}
}
```

**Comment by wangyun-microsoft** [comment]
Thanks for posting. We will review this and get back to you.

**Comment by kkokah** [comment]
Hello, just following up if there's an update on this issue? Thank you

**Comment by jipyua** [comment]
hi @kkokah I am afraid so far there is no good way to do this. But one direction worth having a try: can you try to get the size of the first and second canvases and then when inserting images to the smaller canvas, also set the smaller canvas size to a bigger value or directly set it as the same size of the first canvas?

**Comment by kkokah** [comment]
No worries thanks for your reply we'll try that out
