### ISSUE TITLE
A way to add a shortcut from a code? replaceShortcuts support only actions with shortcuts defined in manifest.xml.

### ISSUE THREAD

**Issue by alexuaua** [OfficeDev/office-js#3174]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I was looking for a way to define custom shortcuts but giving a user ability to select shortcuts user wants to use. Using a shortcuts JSON file provides ability to define shortcuts, but there is no way to disable a shortcut. I supposed Office.actions.replaceShortcuts would provide a way to register a shortcut – because of this line:

> Use the [Office.actions.replaceShortcuts](https://learn.microsoft.com/en-us/javascript/api/office/office.actions#office-office-actions-replaceshortcuts-member) method to assign a user's custom keyboard combinations to your add-ins actions. 

But this gives an error. For example:
`Office.actions.replaceShortcuts({'ASSOCIATEDACTION': "Ctrl+E"})`
gives "RichApi.Error: The argument is invalid or missing or has an incorrect format."

As I understand, I'm getting the error because this API method only allows to customize pre-defined shortcut. 
>The method takes a parameter of type {[actionId:string]: string|null}, where the actionIds are a subset of the action IDs that must be defined in the add-in's extended manifest JSON.

Is there a way to add a custom shortcut from a code? I can define a shortcut and then ignore it in the associated action code, but this prevents a user from using the shortcut for another add-in, action or macro.

**Comment by alison-mk** [comment]
Hi @alexuaua, thank you for submitting and apologies for the delay. Have you consulted the [Add custom keyboard shortcuts to your Office Add-ins](https://learn.microsoft.com/office/dev/add-ins/design/keyboard-shortcuts) documentation article? 

Alison
