### ISSUE TITLE
After closing dialog it is not possible to directly open addin again after closing

### ISSUE THREAD

**Issue by mrrokiton** [OfficeDev/office-js#3175]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: MacOs 12.6.1
* Browser (if using Office on the web): Chrome 109.0.5414.119
 
## Expected behavior
It is possible to open addin again without refreshing page or opening another addin.

## Current behavior
It is not possible to open addin again.

## Steps to reproduce
1. Install addin which allows to open dialog from sidepanel
2. Open dialog
3. Close dialog
4. Close sidepanel addin
5. Open sidepanel addin again

## Link to live example(s)

1.

https://user-images.githubusercontent.com/48177456/221176618-7775fd14-e9dc-4337-a11b-abdcf1f142d0.mov

# Provide additional details

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by donlvMSFT** [comment]
Hi @mrrokiton , thanks for reporting this, I saw you opened a dialog and then close, does this issue only happened after close a pop out dialog? 
I tried Script Lab and other add-ins in store, but couldn't repro this simply. Could you share with us any simple repro step?
