### ISSUE TITLE
Paragraph Start and End ranges are incorrectly retrieved if it is situated inside a content control

### ISSUE THREAD

**Issue by AlinCatalinPreda** [OfficeDev/office-js#3176]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
I created a word document which has a content control, and that content control has a paragraph inside it.
If I try to retrieve the paragraph RangeLocation.start or RangeLocation.end, they will get incorrectly retrieved:
-Paragraph Rangelocation.start will be situated before the content control start tag
-Paragraph RangeLocation.end will be situated after the content control start tag

Comparing the Content control RangeLocation.start with the Paragraph RangeLocation.start will result in saying that Content Control RangeLocation.start is situated after Paragraph RangeLocation.start, which is not correct, it should be situated before it.

Also, comparing the Content control RangeLocation.end with the Paragraph RangeLocation.end will result in saying that Content Control RangeLocation.end is situated after Paragraph RangeLocation.end, which is not correct, it should be situated after it.

This can also be seen when we are retrieving the paragraph RangeLocation.whole or RangeLocation.content, if we are selecting that range, we can see that the content control is also selected.
Or just selecting the paragraph on its own, the content control will still be selected.

Similarly, if we are trying to delete that paragraph, the content control will be deleted together with it, which should not be the case, the content control should still exist after the paragraph gets deleted.

All these issues are seeming to happen because of how the paragraph RangeLocation.start and RangeLocation.end are incorrectly retrieved.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2301 (build 16026.20146) - Current Channel
* Operating System: Windows 10 Pro build 19044.2604
* Browser (if using Office on the web): ______
 
## Expected behavior

Paragraph RangeLocation.start should be situated after the content control RangeLocation.start
Paragraph.RangeLocation.end should be situated before the content control RangeLocation.end

## Current behavior

Paragraph RangeLocation.start is situated before the content control RangeLocation.start
Paragraph.RangeLocation.end is situated after the content control RangeLocation.end

## Steps to reproduce

1. Open the Word document attached (ParagraphInsideCC.docx)
2. Import the gist: https://gist.github.com/AlinCatalinPreda/3c2dc06346e158e90f568ceccd5fb82c
3. Observe the console logs, the wrong selections and the fact that the content control got deleted as well.

## Link to live example(s)

1. Gist: https://gist.github.com/AlinCatalinPreda/3c2dc06346e158e90f568ceccd5fb82c
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [
- 
[ParagraphInsideCC.docx](https://github.com/OfficeDev/office-js/files/10825110/ParagraphInsideCC.docx)

-  ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Searion** [comment]
Thank you @AlinCatalinPreda .
After some investigation, we tent to think it is not a bug but by design. contentcontrol.Paragraphs API can get the paragraph where it is in. To get the start of content control, contentcontrol.getRange() is the best way.

**Comment by AlinCatalinPreda** [comment]
The paragraph is contained inside the Content Control. I am quite sure this is not how it should be, since I have reported a similar issue here: https://github.com/OfficeDev/office-js/issues/2946 where the child content control `RangeLocation.before` would be situated before the parent content control `RangeLocation.start`, even though comparing the two ranges should result in a `LocationRelation.equal`. That issue was fixed eventually.

Please observe the XML. Paragraph XML is contained inside <w:sdt> XML. It just does not feel logical that when I try to get the paragraph of the content control, and perform some operations on it, I get the mentioned behavior in this issue:
- I retrieve the paragraph, and I want to insert some content before that paragraph. I would expect that content to be inserted between the Content Control RangeLocation.start and the Paragraph RangeLocation.start, but instead it is inserted before the Content Control Start Tag
- Same logic for trying to insert content after the paragraph, I would expect it to be inserted between the paragraph RangeLocation.end and the Content Control RangeLocation.end, instead it is inserted after the Content Control End Tag.
- I try to delete the paragraph, it also deletes the content control because of the wrong selection.

`	<w:body>
		<w:sdt>
			<w:sdtPr>
				<w:alias w:val="parent"/>
				<w:tag w:val="parent"/>
				<w:id w:val="436801717"/>
				<w:placeholder>
					<w:docPart w:val="DefaultPlaceholder_-1854013440"/>
				</w:placeholder>
			</w:sdtPr>
			<w:sdtContent>
				<w:p w14:paraId="57E17C00" w14:textId="5F229047" w:rsidR="00D04580" w:rsidRPr="008F7557" w:rsidRDefault="008F7557" w:rsidP="008D7B32">
					<w:r>
						<w:t>Line</w:t>
					</w:r>
					<w:r w:rsidR="008D7B32">
						<w:t>1</w:t>
					</w:r>
				</w:p>
			</w:sdtContent>
		</w:sdt>
		<w:sectPr w:rsidR="00D04580" w:rsidRPr="008F7557" w:rsidSect="005D2925">
			<w:pgSz w:w="12240" w:h="15840"/>
			<w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440" w:header="720" w:footer="720" w:gutter="0"/>
			<w:cols w:space="720"/>
			<w:docGrid w:linePitch="360"/>
		</w:sectPr>
	</w:body>`
