### ISSUE TITLE
Equivalent add-ins - extend custom functions with XLL user-defined functions

### ISSUE THREAD

**Issue by adim1973** [OfficeDev/office-js#3177]
Hi there,

We developed both an XLL add-in and an Office add-in, which are exposing UDFs/custom functions. Some of our users use both add-ins on the same computer, the XLL one in Excel desktop and the Office add-in in Excel online. We found [this](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/make-office-add-in-compatible-with-existing-com-add-in) Microsoft article on how to "make your Office Add-in compatible with an existing COM add-in" and [this one](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/make-custom-functions-compatible-with-xll-udf) on how to "Extend custom functions with XLL user-defined functions".

There are a couple of warnings in the articles which seem to be deal breakers for this approach though:
1. "After you specify an equivalent COM add-in for your Office Add-in, Office stops processing updates for your Office Add-in. To acquire the latest updates for the Office Add-in, the user must first uninstall the COM add-in."
2. "If an Excel JavaScript API add-in declares its custom functions to be compatible with an XLL add-in, changing the manifest at a later time could break a user's workbook because it will change the file format."

Regarding no. 1, it kind of makes sense to no longer receive updates on the Office add-in, if the users wants to use the XLL one, but in our case, with users using both add-ins, this is a bummer. My question here is: if the Office add-in codebase gets updated (not the manifest file, just the published code), wouldn't the users receive these updates?
Regarding no. 2, that warning is vague: any change in the manifest file could break the user's workbook? I usually just increase the version number in the manifest, will this break the workbooks? Or adding another button in ribbon, can this break the workbooks?

Thank you for your time,
Adrian

**Comment by adim1973** [comment]
Hello @yaweizhu-henson ,

Any updates on this?

**Comment by yaweizhu-henson** [comment]
Hi @adim1973 sorry for late response.
I will double confirm with our engineer about the status and get back to you as fast as possible.

**Comment by rundongmsft** [comment]
HI @adim1973, here are the answers:

1. _if the Office add-in codebase gets updated (not the manifest file, just the published code), wouldn't the users receive these updates?_
If "Office add-in codebase gets updated" in your description refers to update “function.js” or "taskpane.js", then the user will receive the update.
2.  _any change in the manifest file could break the user's workbook? I usually just increase the version number in the manifest, will this break the workbooks? Or adding another button in ribbon, can this break the workbooks?_
Change the version number or add a button won't break the user's workbook. The changes mentioned in the document refer to the changes related to "specify a COM add-in or an XLL add-in as equivalents in an Excel JavaScript API add-in manifest file".

**Comment by adim1973** [comment]
Hi @rundongmsft ,

Thank you, this is very helpful, but we have the following problem:
- our XLL add-in is deployed as **ArtemisSheets-AddIn-packed32.xll** for users that have Excel 32 bit and **ArtemisSheets-AddIn-packed64.xll** for users that have Excel 64 bit, so I added two XLL <EquivalentAddin> entries in my manifest file (see below).

```
	<EquivalentAddins>
		<EquivalentAddin>
		  <ProgId>ArtemisSheets.ExcelAddIn</ProgId>
		  <Type>COM</Type>
		</EquivalentAddin>
		<EquivalentAddin>
		  <FileName>ArtemisSheets-AddIn-packed64.xll</FileName>
		  <Type>XLL</Type>
		</EquivalentAddin>
		<EquivalentAddin>
		  <FileName>ArtemisSheets-AddIn-packed32.xll</FileName>
		  <Type>XLL</Type>
		</EquivalentAddin>
	</EquivalentAddins>
```

With this configuration, the Office add-in is loaded though and I can see two "Artemis Sheets" custom tabs in Excel ribbon, one added by the XLL and one added by the Office add-in.
- if I keep only one XLL <EquivalentAddin> entry in the manifest file, then it works fine (only the XLL custom tab is visible in the ribbon), but I don't know what XLL will the users have on their computers, depending on their Excel bitness.

What is the recommended solution in this case?

**Comment by rundongmsft** [comment]
Hi @adim1973, the Equivalent add-ins are not supported on this scenario (Identify and adapt the bitness of Excel). If keeping two configurations at the same manifest will affect the normal use, I suggest that you could release two xll add-ins with different bitness xll file configuration.

**Comment by donlvMSFT** [comment]
Hi, I'd like to close this issue due to current status, please raise a new one or reactive if there're further questions. Thanks!
