### ISSUE TITLE
Get the reference style (R1C1 or A1) of Excel formulas

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#3181]
When we develop Excel add-ins by JavaScript API, we need to determine if the user is currently on R1C1 or A1-notation mode to display their formulas.

Is there any JavaScript API to do so?

Otherwise, does anyone have a reliable way to obtain this information? If possible, we don't want to write to the workbook.

**Comment by alison-mk** [comment]
Hi @chengtie, thank you for submitting this issue! I've assigned it to the engineering team who will be able to provide you with more information. 

Cheers,
Alison

**Comment by yuc014** [comment]
Hi @chengtie,

As far as I know, there is no js api can do this.

For new feature request, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.

Thank you.
