### ISSUE TITLE
Unable to set the file name for newly created the Excel file - Excel.createWorkbook()

### ISSUE THREAD

**Issue by solancer** [OfficeDev/office-js#3184]
Unable to set the file name for newly created the Excel file. I don't see any info on how to set the name for the Excel.createWorkbook() function which only accepts a base64 xlsx payload. The file opens up with a name called **Book 1**.

How can I set the file name for the same?

`  Excel.run(function (context) {
      Excel.createWorkbook(file);
      return context.sync();
  });`

**Comment by solancer** [comment]
@penglongzhaochina Is there something we could do about this issue

**Comment by penglongzhaochina** [comment]
Hi @solancer  Sorry for late. We will get back to you once we have some progress.

**Comment by dingjin-ms** [comment]
Hi @solancer , sorry we currently not support this scenario. But you could consider raise this problem as a new feature request. Thank you!

For new feature request, we would like to suggest you go to [request forum]( https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.

**Comment by XuanZhouMSFT** [comment]
Thanks for waiting. After careful consideration, our team has decided to not do this feature in short term. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.
