### ISSUE TITLE
Outlook: the `ItemSend` event is not fired for web add-ins (in conjunctions with COM add-ins)

### ISSUE THREAD

**Issue by eugene-plutoflume** [OfficeDev/office-js#3185]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
The `ItemSend` event is available for both types of Office add-ins - COM and Web add-ins. But the way when they are fired is different. Office web add-ins don't fire the event after the first try of sending the email.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft Outlook for Microsoft 365 MSO (Version 2301 Build 16.0.16026.20196) 64-bit 
* Operating System: Windows 10 x64
 
## Expected behavior

The on send feature of web add-ins (the `ItemSend` event) should work every time the user clicks the `Send` button in Outlook.

## Current behavior

In cases when COM add-ins cancel the process in the `ItemSend` event handler by setting the e.Cancel property to `true` web add-ins stop firing the on-send events until the Outlook item is closed and then re-opened anew. 

## Steps to reproduce

1. Create a sample COM add-in (VSTO) for Outlook with an `ItemSend` event handler. You can use the following code in the event handler:

```C#
        private void OutlookApplication_ItemSend(object Item, ref bool Cancel)
        {
            DialogResult dr = MessageBox.Show("Do you want to send the email?", 
                "Sample COM add-in", 
                MessageBoxButtons.YesNo,
                MessageBoxIcon.Question, 
                MessageBoxDefaultButton.Button1);

            if (dr == DialogResult.No)
            {
                Cancel = true;
            }
        }
```
3. Register your sample COM add-in with any Office web add-in which has the `ItemSend` event handler as well.
4. Try to send any email. The web add-in fires the `onSend` event which should not be canceled. Then your COM add-in fires the `ItemSend` event which should be canceled. 
5. Next time when an item is submitted (by clicking the `Send` button) your web add-in doesn't fire the `onSend` event. While the COM add-in continues firing the `ItemSend` event, no matter how many times the Send button is clicked.

## Context

The messages in Outlook are not processed by web add-ins because the `ItemSend` event is not fired (unlike for COM add-ins). For example, after canceling the event in a COM add-in (which is called last) the user may edit the email and then re-submit it anew. The web add-in will skip the `ItemSend` event in that case.

Thank you!

**Comment by alison-mk** [comment]
Hi @eugene-plutoflume, thank you for submitting this issue! I've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by exextoc** [comment]
In general, it is not recommended/supported to use Web Add-ins and COM Add-ins together, as interactions between the two are not guaranteed. (i.e. a Web Add-in could be verifying a subject/body of an email, and a COM add-in can come in afterward and change the subject/body) 

Note that if you install multiple *web* add-ins and one of the Web Add-ins cancels the send, then all Web Add-ins we be re-run again. 

That being said, this specific scenario could be fixed. A bug has been opened for the product team to consider. (it may not be fixed) 

Do you have an idea of the business impact/# of users currently impacted by this?

Internal Id: 7679374

**Comment by eugene-plutoflume** [comment]
>  it is not recommended/supported to use Web Add-ins and COM Add-ins together, as interactions between the two are not guaranteed. (i.e. a Web Add-in could be verifying a subject/body of an email, and a COM add-in can come in afterward and change the subject/body)

The workflow described with a possible subject change is acceptable because the web add-in have already verified the email. The difference is that the job of a web add-in was completed and other details depend on the machine configuration. 

We can make our [Office Add-in compatible with an existing COM add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/make-office-add-in-compatible-with-existing-com-add-in). But that is only for our add-in or any known (ProgID).

@exextoc COM add-ins are not under our control. Users may have various COM add-ins installed on the machine.

> Do you have an idea of the business impact/# of users currently impacted by this?

Outlook items are not checked by web add-ins and can be sent without processing which is very sensitive for us. The `ItemSend` functionality is vanished in applications with COM add-ins.

> A bug has been opened for the product team to consider. (it may not be fixed)

That is a possible backdoor. So, I hope it will be fixed soon.

**Comment by kishoresriram** [comment]
Hi @eugene-plutoflume , @exextoc - Is there any update or work around on this as we are facing the same issue. It would be great if you could provide an update, please

**Comment by BhargavRushi** [comment]
Hi @eugene-plutoflume, @exextoc. Any update or work around on this issue. Please let us know if there is any development in resolving this issue.

**Comment by kishoresriram** [comment]
Hello @exextoc @alison-mk @eugene-plutoflume @yinaa , Greetings. I am facing the exact same issue. I have tried using smart alerts as well but of no avail. It would be great if you could provide any update or pointer to work around/solve this.
Please let me know if any additional information is required. Thanks in advance.

**Comment by BhargavRushi** [comment]
Hii @alison-mk @exextoc @eugene-plutoflume @yinaa, I am trying to develop a addin which will trigger when click on send. I have tried ItemSend event and OnMessageSend with smart alert. But in both I am facing the same issue. Could you please provide me a alternate to resolve this issue.
