### ISSUE TITLE
Cant add comment on range 

### ISSUE THREAD

**Issue by arjun0722** [OfficeDev/office-js#3187]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [ ] I am running the latest version of Node and the tools
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

# Expected behavior

Please describe the behavior you were expecting

# Current behavior

Please provide information about the failure. What is the current behavior? If it is not a bug, please submit your idea to the [Microsoft Tech Community Ideas forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform), so that it gets added to our feature roadmap.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* Node version:
* Office version:
* Tool version:

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by arjun0722** [comment]
i was talking about this :-

export const addCommentToSelectedCells = async () => {
  try {
 await Excel.run(async (context) => {
  // Get the selected range
  const range = context.workbook.getSelectedRange();

  // Add a comment to the range
  const comment = range.comments.add("This is a comment!");

  // Load the comment and execute the request
  await context.sync();

  console.log(`Comment added to range ${range.address}: ${comment.text}`);
})
  } catch (error) {
    console.error(error);
  }
};

**Comment by arjun0722** [comment]
RichApi.Error: This operation is not implemented.
    at new n (excel-win32-16.01.js:25:242353)
    at i.processRequestExecutorResponseMessage (excel-win32-16.01.js:25:306519)
    at excel-win32-16.01.js:25:304582

**Comment by arjun0722** [comment]
await Excel.run(async (context) => {
    // Add a comment to A2 on the "MyWorksheet" worksheet.
    let comments = context.workbook.comments;

    // Note that an InvalidArgument error will be thrown if multiple cells passed to `Comment.add`.
    comments.add("Sheet1!A2", "TODO: add data.");
    await context.sync();
});


even getting same issue with this code . that operation is not implemented

**Comment by millerds** [comment]
For your first code example you are trying to get the comment property on the "range" which doesn't have a comments property.  According to https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-comments page the comments are tracked on the workbook or worksheet objects.  One top of that the address cell Address argument must refer to a single cell.  If you want comment multiple cells you would have to iterate over them.

For the second example, if I take that code and place it in the "run" function of a new project created with 'yo office' it works fine (note the reference to the workbook object for the comments collection).  If you are getting an error with this then we need to know more about your project and environment (note the question in the issue template you are not answering).

**Comment by arjun0722** [comment]
@millerds 
see i am creating a new project with yo office , select Office Addin Taskpane project with typescript then now i am implementing this code in run function see ,
Office.onReady((info) => {
  if (info.host === Office.HostType.Excel) {
    document.getElementById("sideload-msg").style.display = "none";
    document.getElementById("app-body").style.display = "flex";
    document.getElementById("run").onclick = run;
  }
});

export async function run() {
  try {
    await Excel.run(async (context) => {
      // Add a comment to A2 on the "MyWorksheet" worksheet.
      let comments = context.workbook.comments;

      // Note that an InvalidArgument error will be thrown if multiple cells passed to `Comment.add`.
      comments.add("Sheet1!A2", "TODO: add data.");
      await context.sync();
    });
  } catch (error) {
    console.error(error);
  }
}

this still giving me this error
RichApi.Error: This operation is not implemented.
    at new n (excel-win32-16.01.js:25:242353)
    at i.processRequestExecutorResponseMessage (excel-win32-16.01.js:25:306519)
    at excel-win32-16.01.js:25:304582
    
    
    i am using this version 2108 excel build 14332.20400
    
![image](https://user-images.githubusercontent.com/103129373/221098013-7a1d35f1-7712-4677-9fad-e46057c3d890.png)

**Comment by arjun0722** [comment]
is there neccessary to get a proper license to used this add delete comment functionality and more ? if yes , so what kind of license should i get ?

**Comment by millerds** [comment]
The API itself doesn't depend on license so much as version.  The version you have should support that API as far as I can tell.  I think well have to forward this to the office-js team to get some further insight.

**Comment by yuc014** [comment]
Hi @arjun0722,

In your code, should be:
```
const sheet = context.workbook.worksheets.getItem("Comments");

sheet.comments.add("A2", "TODO: add data.");
```
Or
```
const selectedRange = context.workbook.getSelectedRange();

context.workbook.comments.add(selectedRange, "TODO: add headers here.");
```

Please see this gist for how to use Comment api: https://gist.github.com/yuc014/e41193ea954a90e4e06f9201b6ed5341

And reference: https://learn.microsoft.com/en-us/javascript/api/excel/excel.comment?view=excel-js-preview
