### ISSUE TITLE
Info Icon on Mac Task Pane Apps

### ISSUE THREAD

**Issue by BenjaminRichardson** [OfficeDev/office-js#319]
My issue is related to the info icon that appears whenever the task pane is active on OSX. It is in a really annoying place for the task pane app I'm working on, blocking the main menu option. Due to consistencies with other platforms moving this menu icon is not an option. Frustratingly this info box appears in different places on Windows, Mac, and iPad. Is there any plan to allow us to change the location of this icon in our add-in/manifest file? (if there already is a way could you point me to the documentation?)

**Comment by kbrandl** [comment]
@BenjaminRichardson apologies for the slow response on this. I'm transferring this issue to the [OfficeDev/office-js](https://github.com/OfficeDev/office-js) repo, where it's more likely to be seen by members of the product team.

**Comment by JuaneloJuanelo** [comment]
this is not an issue with the Javascript API. @BenjaminRichardson  please add/upvote this request in our uservoice channel. thanks! https://officespdev.uservoice.com/
