### ISSUE TITLE
Word field.result is not giving a valid range

### ISSUE THREAD

**Issue by libjosep** [OfficeDev/office-js#3194]
I have a document with two fields. `context.document.body.fields` is listing them. When I try to access the range of the field using `field.result`, it is not giving a range. When I try using VBA, it is giving the range. Below is the VBA code that I am trying.
`

    Sub ListAllFieldsInDoc()

        ActiveDocument.Fields(1).Result.Select

    End Sub
`

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 23.01
* Operating System: Windows 11
 
## Expected behavior

When I access field objects result property, it should be a valid range object.

## Current behavior

Currently I am getting an empty object when I try to access fields result property

## Steps to reproduce

1. Open the attached test file (FieldsTest.docx) in Word
2. Run the scriptlab snippet attached
3. Click on the "Show Fields" button in the scriptlab run panel. It should select the first field in the document.

## Link to live example(s)

1. Script Lab - https://gist.github.com/libjosep/fe83766f2fc58dfa168109057a0df9e4

# Provide additional details

## Useful logs

- [x] Test file (if only happens on a particular file)
- [ ] Console errors
- [ ] Screenshots

[FieldsTest.docx](https://github.com/OfficeDev/office-js/files/10860831/FieldsTest.docx)

**Comment by penglongzhaochina** [comment]
Hi @libjosep your usage is not correct. the fields(fieldcollection object) don't have "code" or "result" property. The field have those two proppery. So could you please try below code:
`var field1 = fields.items[0];
      field1.load(["code", "result"]);
      var range1 = field1.result;
      range1.load();
      //console.log(JSON.stringify(field1.result));
      range1.select();`

**Comment by libjosep** [comment]
Hi @penglongzhaochina 
`
const fields = context.document.body.fields.load("items");
        await context.sync();
        if (fields.items.length === 0) {
          console.log("No fields in this document.");
        } else {
          fields.load(["code", "result"]);
          await context.sync();
          fields.items[0].result.select()
        }
`

This is the code I am trying in the script lab sample. As per your suggestion, I tried the following code as well, but it is not selecting the range.
`
    
    const fields = context.document.body.fields.load("items");

    await context.sync();

    if (fields.items.length === 0) {
      console.log("No fields in this document.");
    } else {
      var field1 = fields.items[0]; 
      field1.load(["code", "result"]); 
      var range1 = field1.result; 
      range1.load(); //
      await context.sync();
      console.log(JSON.stringify(field1.result)); 
      range1.select();
    }

`

**Comment by penglongzhaochina** [comment]
Hi @libjosep I took a video to show my code and action. The selection works for me.

https://user-images.githubusercontent.com/106959323/222374003-6c32f4ab-9004-4e5d-a615-6d196dc8e763.mp4

And this feature is an old feature. Not updated for a long time.

**Comment by libjosep** [comment]
@penglongzhaochina Please try with the attached file (FieldsTest.docx).

**Comment by jipyua** [comment]
hi, thanks for reporting this, this is because for your two Expression fields in the document, they just don't have result or empty result. Thus the field.Result is returning an empty one, at this case please check whether the range is null or empty do determine whether it has a result.

**Comment by libjosep** [comment]
@jipyua I have a requirement to select the area between these kind of fields. I was able to do this with Interop API's (like the VBA mentioned in the bug description) for the same document. Can I achieve the same using Office.js? To be more precise, I want to achieve what the following VBA does in the same document.

```
Sub FieldSelectionTest()

    Set myRange = ActiveDocument.Fields(1).Result
    myRange.SetRange Start:=myRange.End, _
    End:=ActiveDocument.Fields(2).Result.End
    
    myRange.Select

End Sub
```

**Comment by jipyua** [comment]
This sounds like a valid request, thanks for letting us know, I will open an internal work item to track this request.

**Comment by libjosep** [comment]
Thank you @jipyua

**Comment by GavinGu07** [comment]
Hi @libjosep, the update has been checked in and should be available no later than early July. You can have a try at that time and feel free to give us any feedback!

**Comment by libjosep** [comment]
Thank you @GavinGu07
