### ISSUE TITLE
Errors when using the `Dialog API` in Office add-ins 

### ISSUE THREAD

**Issue by eugene-plutoflume** [OfficeDev/office-js#3198]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

The `Office.UI` interface provides objects and methods that you can use to create and manipulate UI components, such as dialog boxes, in your Office Add-ins. To open the dialog window you can use the [displayDialogAsync](https://learn.microsoft.com/en-us/javascript/api/office/office.ui?view=common-js-preview#office-office-ui-displaydialogasync-member(1)) method which provides a callback to handle the dialog creation attempt. If successful, the `AsyncResult.value` is a `Dialog` object. But it doesn't provide any callback or property to know when the dialog is closed for sure. And if your add-in tries to display another dialog window right after the previous is closed you may get various errors in the code. For example, take a look at the recent post related to Excel, see [Excel Add-in Dialog open gives ""An internal error has occurred." error](https://stackoverflow.com/questions/75415846/excel-add-in-dialog-open-gives-an-internal-error-has-occurred-error/75452494?noredirect=1#comment133161316_75452494). In Outlook I see a bit different picture, but the problem is the same - instead of displaying a new dialog box we got errors in the code.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: any 
* Host [Excel, Word, PowerPoint, etc.]: Outlook, Excel ...
* Office version number: any
* Operating System: any
* Browser (if using Office on the web): any
 
## Expected behavior

It would be great to know when exactly the dialog window is closed, so it is safe to display a new one.

## Current behavior

The process is non-deterministic. We must use a delay before display a new dialog window to a user, and the amount of time we need to wait is unknown. 

## Steps to reproduce

1. Use the [displayDialogAsync](https://learn.microsoft.com/en-us/javascript/api/office/office.ui?view=common-js-preview#office-office-ui-displaydialogasync-member(1)) method to display a dialog box.
2. At some point call the `Close` method to close it.
3. Right after that try to display another dialog window.

## Context

In Outlook we had to display a progress window to prevent users from changing emails, but as soon as we close the progress window a new dialog window cannot be displayed. The workaround described in the [Open another dialog immediately after closing one](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-best-practices#open-another-dialog-immediately-after-closing-one) section doesn't work after a single try:

```
function openFirstDialog() {
  Office.context.ui.displayDialogAsync("https://MyDomain/firstDialog.html", { width: 50, height: 50},
     (result) => {
      if(result.status === Office.AsyncResultStatus.Succeeded) {
        const dialog = result.value;
        dialog.close();
        openSecondDialog();
      }
      else {
         // Handle errors
      }
    }
  );
}
 
function openSecondDialog() {
  Office.context.ui.displayDialogAsync("https://MyDomain/secondDialog.html", { width: 50, height: 50},
    (result) => {
      if(result.status === Office.AsyncResultStatus.Failed) {
        if (result.error.code === 12007) {
          openSecondDialog(); // Recursive call
        }
        else {
         // Handle other errors
        }
      }
    }
  );
}
```

The Office JS runtime doesn't let you try multiple times unfortunately. So, we had to use the `setTimeout` function:

```
function openFirstDialog() {
  Office.context.ui.displayDialogAsync("https://MyDomain/firstDialog.html", { width: 50, height: 50},
     (result) => {
      if(result.status === Office.AsyncResultStatus.Succeeded) {
        const dialog = result.value;
        dialog.close();
        setTimeout(() => { 
          Office.context.ui.displayDialogAsync("https://MyDomain/secondDialog.html", { width: 50, height: 50},
             (result) => { /* callback body */ }
          );
        }, 1000);
      }
      else {
         // Handle errors
      }
    }
  );
}
```

if we use more time to wait - the user may be able to change the email, if we try to use less time to wait - we may get an error in the code and the dialog box will never be displayed.  

So, I think the most reliable solution is to provide a callback to let the add-in know that a dialog box is closed and now it is SAFE to display another one. 

Thank you!

**Comment by alison-mk** [comment]
Hi @eugene-plutoflume, thank you for submitting this issue! I've assigned it to @yatibawri1 who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by yatibawri1** [comment]
@Dengshan2018 would you be able to look into this issue
