### ISSUE TITLE
Web Word Bookmark does not work on image if user adds wrapping and no way to access pictures that are not inlined

### ISSUE THREAD

**Issue by lynneosmith** [OfficeDev/office-js#3199]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We insert a graph as an inline picture and bookmark the range. Then, the user uses Word's picture menu to add wrapping to the image, which makes it no longer be an inlined image. On Word web, the range that includes the bookmark no longer exists. 
In addition, there is no other way to get to pictures that are not inlined in the document that i can find.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: ______
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
I would expect that even if the picture is now inlined, searching for the bookmarked range should still return me the range that I bookmarked. In addition, I would ideally like a way to get to pictures that are not inlined if possible.

## Current behavior
If I add an inlined picture and bookmark the range and then access the bookmark name, I am able to find the inlined picture from the range returned.
If I add an inlined picture and bookmark the range and THEN use the Word Picture menu to change the wrapping on the picture I inserted... and then try to access the bookmark name, the bookmark name can not be found and I am not able to find the range i bookmarked nor do i have a way to find a picture that is not inlined.

## Steps to reproduce
I was able to reproduce this behavior in ScriptLab: 
1: Replace insertImage and getImage in your inline picture example
2: On web or desktop Word, insert the image, then get the image. All will work. The width and height will display in the console.
3: On web Word, insert the image. Use the Picture menu to change the wrapping on the image. Then get the image using the other button and the getImage method. The bookmark will return an item not found error instead of returning you the valid range that you previously bookmarked.
4: Note that I could find no other way to find access to an image that is no longer inlined. I did not see a collection off the document or the body. I thought I might could work around this by setting an altTitle on the image and then getting the collection of images in the document and looking for a match, but that doesn't work since I couldn't find access to the images that are not inlined.

// Inserts an image anchored to the last paragraph.
  await Word.run(async (context) => {
    const myGraph = context.document.body.paragraphs
      .getLast()
      .insertParagraph("", "After")
      .insertInlinePictureFromBase64(base64Image, "End");

    await context.sync();
    const graphRange: Word.Range = myGraph.getRange();
    graphRange.select();
    graphRange.insertBookmark("mybookmark");
    await context.sync();
  });
}

async function getImage() {
  // Get the first image in the document.
  await Word.run(async (context) => {
    // This should find the bookmarked content and look for an inline picture within the range.
    const range = context.document.getBookmarkRange("mybookmark");
    await context.sync();

    const firstPicture = range.inlinePictures.getFirst();
    firstPicture.load("width, height");
    await context.sync();

    console.log(`Image dimensions: ${firstPicture.width} x ${firstPicture.height}`);
    
    await context.sync();
  });
}

## Context
Our application inserts report contain, which often is images into the document. We bookmark them to track them and then as the report updates, we keep the images in the document updated for the user. Not having access to get back to the range with a bookmark or a tab to an un-inlined image completely breaks the functionality of our product. One of it's most valuable features is that we have the ability to update content. I am able to work around this on desktop, since it does at least give me the bookmarked range.  I need to to work on the web as well. Ideally, we also want to be able to get to the image that is no longer inlined  so that we can check it's width/height and other properties to maintain when we update the image.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by xiaoyuMS** [comment]
Hi @lynneosmith,

I can repro the issue. It is inconsistent behavior between Word Web and Desktop.

On Word Web, when you bookmark **only the inline picture**, the bookmark will be deleted after we change the text wrapping of the inline picture. 
On the Desktop, the bookmark will be kept.

I have created a Bug #VSO7663230 to track this internally. 

For the request to **retrieve the non-inline picture**, I would like to suggest you go to [Microsoft365DeveloperPlatform](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) and see if your question has already been asked or ask a new request. Feature requests on it are considered when we go through our planning process.
