### ISSUE TITLE
Word for Mac search method character limit

### ISSUE THREAD

**Issue by asifmai** [OfficeDev/office-js#320]
Searching in the document using paragraph.search() executes without any error, but on Word for Mac throws error of invalidArgument

## Expected Behavior
Should be able to search without errors on Word for Mac, since the search string has characters less than 255

## Current Behavior
Throws error of Paragraph.search(), invalidArguments

## Steps to Reproduce, or Live Example
         paras.items.forEach(function(para){
            if (para.text.length > 100){
                // Do some regex searches on paragraph text and return the search terms
                var searchTerms = findAllCasesComplete(para.text);
                var searchTermsAround = findAllCasesCompleteAround(para.text);
                if (searchTerms.length > 0){
                    for (let index = 0; index < searchTerms.length; index++) {
                        rangeCollects.push(para.search(searchTerms[index]));
                    }
                }
                if (searchTermsAround.length > 0){
                    for (let index = 0; index < searchTermsAround.length; index++) {
                        rangeCollectsAround.push(para.search(searchTermsAround[index]))   
                    }
                }
            }
        })

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.16.4
* Operating System: MacOS high Sierra 10.13.6
* Browser (if using Office Online):

**Comment by JuaneloJuanelo** [comment]
Yes this is a known issue an a limitation of Word itself. You cannot perform such search from the UI. We will increment capacity when the feature is available in the product.

**Comment by RXminuS** [comment]
Maybe add it to the documentation though. Just spent hours banging my head against the wall, to only rediscover this arbitrary limit.
