### ISSUE TITLE
Word - GeneralException when retrieving Cell Index of vertically merged table cells

### ISSUE THREAD

**Issue by y365-andrew** [OfficeDev/office-js#3200]
It appears that when I try to retrieve the cellIndex property of a merged table cell OfficeJS throws a 'GeneralException' error. The only way I've found to handle this error is to call context.sync() in a loop (I know it's not recommended) with it's own try catch block. 

If I'm trying to get all the table cells in a document with their row and cell index properties I cannot do that with a global cells.load call because it will always fail where there is one table with merged cells in the document. Interestingly, the crash seems to be isolated to cells which are merged vertically.

In general there doesn't seem to be a way to currently tell where merged cells are and which rows/columns they are merged across, I've handled this so far by making assumptions based on the overall number of rows and columns in the table.

## My Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2212
* Operating System: Windows 11
* Browser (if using Office on the web): Edge
 
## Expected behavior
I would expect that at minimum the cellIndex property either just not load or be null, just something so that the whole context.sync doesn't crash when there are vertically merged table cells. 

Best case, It'd be amazing to have a way to tell where a cell is merged and across which rows/columns to make handling of tabular information much better within Word.

## Current behavior
Currently, any call attempting to load the cell Index for a table with a vertically merged cell will throw a GeneralException error. This includes where I am trying to load all tables in a document. eg. context.document.body.paragraphs.load('items/parentTableCellOrNullObject/cellIndex')

## Steps to reproduce

1. Create a document with a table and merge two cells vertically (across the rows), eg: 
![image](https://user-images.githubusercontent.com/60287381/223011243-0eb28eea-fbd3-4f3a-8917-81aecd7636a3.png)
2. Get all the document paragraphs: const paras = context.document.body.paragraphs
3. Try to load the cellIndex on all cells: paras.load("items/parentTableCellOrNullObject/cellIndex")
4. Run a context sync and watch it throw an error

## Link to live example(s)
1. https://gist.github.com/y365-andrew/58bdff6f6d197de3d00f0b587c2f3221

## Context
I am using OfficeJS to create a web-ready version of a document with very specific publishing requirements. This involves extracting data from tables in the document and using them for various purposes. Whilst technically I could probably build an OOXML parser to fill the void I dont think the whole context sync should fail thus I thought it worth logging an issue.

## Useful logs
This is the error:
![image](https://user-images.githubusercontent.com/60287381/223012608-82ef5b7a-7478-4144-a08b-c0d8ce75e334.png)

Please let me know if you need any additional info.

**Comment by GavinGu07** [comment]
Hi @y365-andrew, thanks for reporting this issue. 

In fact, there are two paragraphs in the merged cell in your case, and the second paragraph's parent table cell is a 'child table cell', which has no index, so it would throw exceptions when you try to load the cell index in the 4th cell.

Telling where a cell is merged is not a part of the product. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum]( https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process.

**Comment by y365-andrew** [comment]
Hi [GavinGu07](https://github.com/GavinGu07), thanks for your quick response!! 

So I can sort of see how that makes sense however I do have a question as to the best-practice for handling this particular error. 
I've just done a little test by logging out the tableNestingLevel of each paragraph and they all show up as being 1. So is there any way for me to handle this error without running a context.sync for each table cell? Furthermore, if I retrieve the  parentTable for each paragraph it appears to be the same for all the cells including the merged cells. I am just trying to minimise the number of context.sync() calls for a table but if it is not possible to detect without checking each cell I can certainly do that.

Thanks!!

**Comment by GavinGu07** [comment]
Hi @y365-andrew, sorry for the late response. Actually, if you want the table cell index and row index, you can load from table properties. For example:
```
const body = context.document.body;
const table = body.insertTable(3, 4, Word.InsertLocation.start);
table.mergeCells(0, 0, 1, 0);
const p = table.load("rows/items/cells/items/cellIndex");
await context.sync();
for (let i = 0; i < p.rows.items.length; i++){
  for (let j = 0; j < p.rows.items[i].cells.items.length; j++) {
    console.log(p.rows.items[i].cells.items[j].cellIndex);
  }
}
```
This can avoid the 'child table cell' issue. I hope it can help.

**Comment by y365-andrew** [comment]
Hi [GavinGu07](https://github.com/GavinGu07), 

Thanks heaps for the response!! I will give that solution a go! 

Cheers!
Andrew
