### ISSUE TITLE
Add in Bar ignoring Rule in Manifest

### ISSUE THREAD

**Issue by mazer-rakham** [OfficeDev/office-js#3201]
Provide required information needed to triage your issue
Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: 
**PC Desktop Windows 11**
Host [Excel, Word, PowerPoint, etc.]:
**Outlook desktop**
Office version number: 
**2109**
Operating System:
 **windows 11**
Browser (if using Office on the web):
 **I am not using**
Expected behavior 
**The Custom Outlook plugin action buttons only show when the item looked at is a appointment**
Current behavior 
**Custom plugin buttons show all the time**
Steps to reproduce 
**run yo office, change the <Rule> at the top to only shoe one or the other and then run "npm run dev-server" and upload your manifest**

Outlook Manifest file is ignoring rules.
Per this documentation:
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/activation-rules

![image](https://user-images.githubusercontent.com/11220261/223522985-cabd109a-d28c-4809-87c6-fa7cb8580668.png)

If I am reading an appointment the Icon should now show up. And Visa Versa, but Icons are showing up no matter what message item is selected. 

![image](https://user-images.githubusercontent.com/11220261/223523256-bd69fda1-3187-4d3e-8f9a-4c8477bb929f.png)

Newest version of yo office generator.

**Comment by alison-mk** [comment]
Hi @mazer-rakham, thank you for submitting an issue. To help resolve your concern, can you use the following template to provide more information?


# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior


## Current behavior



## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)



1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context



## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by mazer-rakham** [comment]
@alison-mk updated the original post

**Comment by alison-mk** [comment]
Hi @mazer-rakham, thank you for the additional information. I've assigned this issue to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by zhngx1** [comment]
Hi @mazer-rakham the rules you added for add-in bar are deprecated. But I presume what you are trying to do is to show the add-in icon in the ribbon only for appointments, right?
![image](https://user-images.githubusercontent.com/117226789/224832948-f054d49a-10e8-42af-bafa-8555b3593ed5.png)

**Comment by mazer-rakham** [comment]
@zhngx1 yes that is correct, those Rules were the ones that I got from the Documentation, do you have updated Documentation? Thank you!

**Comment by zhngx1** [comment]
For the ribbon button to only show when you are in appointment, you will need to to have **AppointmentAttendeeCommandSurface**/**AppointmentOrganizerCommandSurface** instead of **MessageReadCommandSurface**/**MessageComposeCommandSurface** for your **ExtensionPoint** element.
The link to the documentation is: https://learn.microsoft.com/en-us/javascript/api/manifest/extensionpoint?view=outlook-js-preview#appointmentorganizercommandsurface

**Comment by mazer-rakham** [comment]
@zhngx1 thank you for this!

**Comment by mazer-rakham** [comment]
So we have tested this @zhngx1 and @alison-mk  this does not seem to work, the custom plugin buttons are still showing on mail and visa versa. What we are trying to accomplish is 2 manifests that show based on what view you are on. In the Inbox view, we only want the button for manifest a showing, for the Calendar view we only want the button for manifest b showing. Is this possible? 

The problem we are facing is that when you are in the inbox view you can see both emails and appointments all mixed together. So if the user is clicking through his inbox if it is an email we want one set of buttons to show up but if the item he clicks is an appointment item then we want a different set of buttons to show. 

 

The extension point "MessageReadCommandSurface" seems to apply to both appointments and emails when in that view. We have tried using the ruleset in the manifest so it would not include appointments.
`<Rule xsi:type="RuleCollection" Mode="Or">

    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"/>

  </Rule>`
  

 

Yet, even though we set that ruleset the buttons from the manifest in that extension point will show for both appointment items and regular emails. We are surprised that there is not an ability to have the buttons act differently based on the item type when viewing via the inbox view. We are wondering if you have a solution or if this is a flaw in the system that you all are planning on fixing?

**Comment by zhngx1** [comment]
Hi @mazer-rakham ,

I tested using both AppointmentAttendeeCommandSurface/AppointmentOrganizerCommandSurface and MessageReadCommandSurface/MessageComposeCommandSurface in the manifest and it seemed to accomplish what you were trying to do --> having tow sets of buttons for messages and appointments.

You will need to have 2 sets of ExtensionPoint for it to work.
```
<ExtensionPoint xsi:type="AppointmentOrganizerCommandSurface">
  <OfficeTab id="TabDefault">
        <-- OfficeTab Definition -->
  </OfficeTab>
</ExtensionPoint>
<ExtensionPoint xsi:type="MessageReadCommandSurface">
  <OfficeTab id="TabDefault">
        <-- OfficeTab Definition -->
  </OfficeTab>
</ExtensionPoint>
```

Also, as I mentioned before, the rulesets are deprecated and they were not meant for the tasks you are working on here.

**Comment by mazer-rakham** [comment]
ok @zhngx1 I will have my developer attempt this today and report back to you.

**Comment by mazer-rakham** [comment]
@zhngx1 this is still not working as described above. Following your instructions, this I can get the button to show when in th Calendar view and double clicking.  
![image](https://user-images.githubusercontent.com/11220261/227937477-76185d50-2c4e-4034-ac83-94464375bf12.png)



But in the regular inbox view, in an appointment confirmation, this the button does not show up:

![image](https://user-images.githubusercontent.com/11220261/227937899-6bc4593d-7f50-49b4-ab12-036ec4fba192.png)

**Comment by mazer-rakham** [comment]
Also @zhngx1 what about in the main outlook calendar? What about just showing on highlights?
![image](https://user-images.githubusercontent.com/11220261/227979045-e3dadd9c-83bf-488e-863a-d68fc66a002d.png)

**Comment by mazer-rakham** [comment]
Bump @zhngx1

**Comment by zhngx1** [comment]
@mazer-rakham add-ins are not supported in the main outlook calendar view. In the regular inbox view, in an appointment confirmation, it's treated as message so it will show add-ins with MessageReadCommandSurface.
