### ISSUE TITLE
Unable to remove Pivot table when that workbook is not active

### ISSUE THREAD

**Issue by konlawat-kalikanon-lseg** [OfficeDev/office-js#3202]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: version 2302 (Build 16130.20218) Current Channel
* Operating System: Windows 10
 
## Expected behavior
After Excel.createWorkbook execute. Remove all of the Pivot Table on that workbook should be successful. 

## Current behavior
After Excel.createWorkbook execute. Start remove Pivot Table but got an error try to remove Pivot Table.

## Steps to reproduce

1. Create a copy of exist workbook from base64string using `Excel.createWorkbook(base64String)`
2. New workbook is open and active workbook move to the new workbook.
3. Stay active on the new workbook.
4. Start remove pivot table and got an error.

## Context
If we switch back to the workbook that taskpane is on before start removing Pivot Table everything working fine.

## Useful logs

![image](https://user-images.githubusercontent.com/127272554/223611858-2ae454c0-9930-4619-b2b4-b8f78df6b340.png)

## Link to live example(s)
* [Git](https://github.com/konlawat-kalikanon-lseg/Office-Addin-TaskPane-Angular/blob/master/src/taskpane/app/excel.app.component.ts)
* [Book2.xlsx](https://github.com/OfficeDev/office-js/files/10928398/Book2.xlsx)

**Comment by yuc014** [comment]
Hi @konlawat-kalikanon-lseg,

I have followed your repro steps but cannot repro your issue. Could you share a gist or code snip? Thanks.

**Comment by konlawat-kalikanon-lseg** [comment]
Hi @yuc014 I already updated the original post. Could you use that exel file and code. If you click **Run>** you should able to reproduce my issue.
![image](https://user-images.githubusercontent.com/127272554/223937941-72300572-177b-421d-baf8-2b938fae20b0.png)

**Comment by yuc014** [comment]
Hi @konlawat-kalikanon-lseg ,
See below video, still not repro...

https://user-images.githubusercontent.com/87364252/224985472-191fcd19-242e-4b6d-9674-c5b10c59deb3.mp4

My excel desktop version: Version 2212 Build 16.0.15926.15010

**Comment by konlawat-kalikanon-lseg** [comment]
Hi, I'm still can reproduce it on my device. Here more error log.
![image](https://user-images.githubusercontent.com/127272554/226244010-82154493-65c1-4990-a185-8835dba8cc2a.png)

**Comment by YueLi-MSFT** [comment]
@konlawat-kalikanon-lseg Hi, thanks for wating a long time. Please see the below video, we still not repro... When I click "Run" will create a new workbook with the Pivot Table and old workbook will remove the Pivot Table.

https://github.com/OfficeDev/office-js/assets/95617492/4add2563-e94d-4d6d-964f-22dff7e9943c

**Comment by YueLi-MSFT** [comment]
We appreciate your feedback and the details you provided about this issue. However, we have tried to reproduce the issue on our end, and we were not able to do so. Therefore, we have decided to close this issue for now, but we will keep an eye on it and re-open it if you encounter any issue in the future.
