### ISSUE TITLE
Unable to use predefined, culture-dependent formats in FNVs? 

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#3206]
Formatted number cell values support specifying a custom format: https://learn.microsoft.com/en-us/javascript/api/excel/excel.formattednumbercellvalue?view=excel-js-preview

## Expected behavior

It should also be possible to specify one of the predefined formats, like "Date", because the date formatting is different for every user depending on the culture settings.

## Current behavior

Only hard-coded format string can be used.

## Context

We are outputting tables of data as a spilling range from a custom function. Some columns are dates, so we would like to format them as such without the user having to manually format a column of numbers (which are in reality dates).

However, using a hard-coded format like MM/DD/YYYY will not apply to users in Europe who use DD/MM/YYYY.

Is there an easy workaround for this issue? Can we query the actual "Date" format for the user via the Office.js API?

**Comment by alison-mk** [comment]
Hi @wh1t3cAt1k, thank you for submitting this issue! I've assigned it to @yaweizhu-henson who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by wh1t3cAt1k** [comment]
Hi @yaweizhu-henson @alison-mk , when could we expect an update on this?

**Comment by yaweizhu-henson** [comment]
Hi @wh1t3cAt1k  Sorry for the late response. We had some internal discussion about your requirement. Here is a possible workaround method for you.
https://learn.microsoft.com/en-us/javascript/api/office/office.context?view=common-js-preview#office-office-context-contentlanguage-member
This is a API that you can do different action based on end users system language. Maybe you can use language setting to distinguish user from Europe and North America. 
Hope this can meeting your expectatin. Thanks!

**Comment by wh1t3cAt1k** [comment]
Thanks @yaweizhu-henson . For now we have opted to "ISO-like" `yyyy-MM-dd` representation that will work well across cultures.

For now we can close this.
