### ISSUE TITLE
Outlook Online, New Outlook on Mac, the ribbon button label and icon are wrong in the read mode add-in 

### ISSUE THREAD

**Issue by jacifkusto** [OfficeDev/office-js#3208]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We are developing an Outlook add-in for compose and read modes. In Outlook Online and New Outlook for Mac, the button for read mode has wrong label and icon. The issue doesn't affect Outlook Desktop on Windows and old Outlook for Mac.

## Your Environment
* Platform: Mac, Office on the web
* Host: Outlook
* Office version number: Outlook for Mac 16.69.1 (23011802)
* Operating System: macOS Ventura 13.2.1
* Browser (if using Office on the web): Chrome 110.0.5481.177 
 
## Expected behavior
The button has the correct label and icon.

## Current behavior
The button has incorrect label and icon.

## Steps to reproduce
1. Open Outlook on the web in any browser.
2. Select any message in Inbox.
3. Click the Get Add-ins button.
4. Go to My Add-ins -> Custom Add-ins section.
5. Add a custom add-in using the following manifest: https://online-addins.ablebits.com/testaddin/manifest2.xml
7. In the preview pane click the add-ins button.
8. Note that the button label and icon are wrong. According to the add-in manifest the icon should be red (not green) and the label should be "Test Addin READ" (not "Test Addin 2")

## Link to live example(s)
You can use our test add-in:
https://online-addins.ablebits.com/testaddin/manifest2.xml
I've also attached screenshots and the add-in source files.

<img width="789" alt="Screenshot 2023-03-09 at 14 28 00" src="https://user-images.githubusercontent.com/44617947/224052536-a057c740-27c9-4426-a56a-3e7d3ce31c5b.png">
<img width="1376" alt="Screenshot 2023-03-09 at 14 24 32" src="https://user-images.githubusercontent.com/44617947/224052547-25d6fae5-02d8-4193-9ad5-a38c7010a03a.png">
<img width="814" alt="Screenshot 2023-03-09 at 14 21 41" src="https://user-images.githubusercontent.com/44617947/224052550-f2b81f6f-248e-4edc-8207-040d089a17b4.png">

**Comment by alison-mk** [comment]
Hi @jacifkusto, thank you for submitting this issue! I've assigned it to the engineering team who will be able to provide you with more information or help resolve the issue. 

Cheers,
Alison

**Comment by exextoc** [comment]
@jacifkusto Thanks for reporting this issue. We have put this in our backlog but unfortunately, we do not have any timelines to share at this point.

Internal tracking id - 196390(outlook online), 7697926(New outlook Mac)

**Comment by jacifkusto** [comment]
@gergzk Please reopen the issue because it's still reproducible and we're waiting for the fix.

**Comment by megharai13** [comment]
@jacifkusto Thank you for reporting this issue. It is a known gap in the New Outlook platform since we currently do not show any apps in the read ribbon. There is an ongoing effort to move the apps to the read ribbon, which should reach production by the end of this calendar year. Post that, we will consider your ask as a new feature request to make the behaviour more consistent with Classic Outlook. Unfortunately, we have no timelines to share at this point. For now, the default is to display the add-in title and icon on New Outlook.
