### ISSUE TITLE
Parsing beyond column Z does not work in Excel Online problem type

### ISSUE THREAD

**Issue by kjeancengage** [OfficeDev/office-js#3209]
We are trying to parse data from CXP to a solution spreadsheet for columns AA and AB. However, values are not sent from Geyser to Column AA, values from the AB column are sent to the AA column, and after Column AA in other columns, no data is being transferred. Our team has reviewed and it seems like a bug on the MSFT side rather than content authoring.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Excel for Web 16.0.16309.42300
* Operating System: Win
* Browser (if using Office on the web): Chrome
 
## Expected behavior
I should be able to parse data to cells in columns AA, AB, etc. in a 1-1 fashion.

## Current behavior
Values from the AB column are sent to the AA column, and after Column AA in other columns, no data is being transferred. 

## Steps to reproduce
within the spreadsheet solution code for the CXP item, write:

"Z5": 111,
"AB5": 222,
"AC5": 333,

You'll see that Z5 shows "1", AA5 (not AB5) shows "222" and AC5 shows nothing. 

![screenshot](https://user-images.githubusercontent.com/127422063/224080370-a796f409-b0f7-43d3-8618-7f8dea0ba4b2.png)

## Context
We currently cannot support wide algorithmic problems because of this issue, which is a requirement for true Data Analytics activities.

**Comment by yuc014** [comment]
Hi @kjeancengage,

I tried excel js api on excel online, but did not repro your issue, see below video:

https://user-images.githubusercontent.com/87364252/224487287-d444d46d-a090-40b5-a194-6c154a526d60.mp4

If you still see this issue, please give more details about repro step, thanks!

**Comment by kjeancengage** [comment]
Thanks for passing this along. I decided to tinker a bit more, and it looks like the code on our end isn’t parsing properly:

                AB2 > AA2
                BB2 > AB2
                CB2 > AC2

***@***.***

I am routing this to my internal team to investigate if the issue is on our end. Stay tuned!

~Kasie

From: YunfanChen-MS ***@***.***>
Sent: Saturday, March 11, 2023 8:28 AM
To: OfficeDev/office-js ***@***.***>
Cc: Jean, Kasie ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OfficeDev/office-js] Parsing beyond column Z does not work in Excel Online problem type (Issue #3209)


Hi @kjeancengage<https://urldefense.com/v3/__https:/github.com/kjeancengage__;!!MXVguWEtGgZw!LaMd5LLD-DDkr417O5rjOOOjruNgpGlxAxra28iNoH1fnIOCxxBDpmUrePswVcblPr1qCvBkktJHj1IO3yY4txSR4g$>,

I tried excel js api on excel online, but did not repro your issue, see below video:

https://user-images.githubusercontent.com/87364252/224487287-d444d46d-a090-40b5-a194-6c154a526d60.mp4<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/87364252/224487287-d444d46d-a090-40b5-a194-6c154a526d60.mp4__;!!MXVguWEtGgZw!LaMd5LLD-DDkr417O5rjOOOjruNgpGlxAxra28iNoH1fnIOCxxBDpmUrePswVcblPr1qCvBkktJHj1IO3ybrELS2jg$>

If you still see this issue, please give more details about repro step, thanks!

**Comment by kjeancengage** [comment]
Note that our internal team is still investigating the root cause of this issue. Stay tuned!

**Comment by shanshanzheng-dev** [comment]
Hi @kjeancengage, Hope you have a good day. Has this issue been solved? We value your feedback. Thanks.

**Comment by kjeancengage** [comment]
I believe we solved the parsing issue on our end, but my memory isn't 100% on that. Either way, I don't believe there's anything for the MSFT to do at this time because the problems are working as is.
