### ISSUE TITLE
Pop-up is getting blocked when calling displayNewMessageFormAsync

### ISSUE THREAD

**Issue by petercsonka** [OfficeDev/office-js#3213]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
In an Outlook web Add-in I'm calling the `displayNewMessageFormAsync` method of the Office JS API to display a new form for e-mail creation and filling the e-mail's to filled with the given e-mail address. However on Safari and Firefox if I don't allow pop-ups, these browser will block the opening of this new form. On the other side in Chrome it opens the new form without explicitly allowing pop-ups in the browser.

**My Code:**
```
  private addRecipientToNewMail(recipient: string): void {
    this.mailbox.displayNewMessageFormAsync({ toRecipients: [recipient] },
    (result: Office.AsyncResult<void>) => {
      if (result.status === Office.AsyncResultStatus.Failed) {
        console.log(result.error);
      }
    });
  }
```

It's interesting if I call the `displayNewMessageFormAsync` method with a `parameters` argument where I set the `htmlBody` property, then on Firefox the new form will be displayed without allowing pop-ups explicitly, code example:

```
this.mailbox.displayNewMessageFormAsync({ htmlBody: `<h1>Test</h1>` }, 
(result: Office.AsyncResult<void>) => {
  if (result.status === Office.AsyncResultStatus.Failed) {
	console.log(result.error);
  }
});
```

I would like to have a solution for this issue where the new e-mail form can be opened directly without having to enable pop-ups manually in the browser.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Latest web app
* Browser (if using Office on the web): Firefox (Version 110.0.1) and Safari (Version 15.6.1 (15613.3.9.1.16))

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: 196034
