### ISSUE TITLE
insertFileFromBase64 resulting in RichApi error in Office Online

### ISSUE THREAD

**Issue by A-Glazer** [OfficeDev/office-js#3216]
I am trying to insert a docx file using Word Online using `insertFileFromBase64`. This used to be working fine, but now when I call context.sync() it results in a RichApi error. (It is working properly in Web Desktop)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Microsoft 365
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

The document should insert correctly with no RichApi Error.

## Current behavior

I am trying to insert a docx file using Word Online using `insertFileFromBase64`. This used to be working fine, but now when I call context.sync() it results in a RichApi error. 

Here is the code I'm using: 
```
context.document.getSelection().insertFileFromBase64(base64, "After");
await context.sync();
```

The file is inserted correctly (sometimes after a long delay), but then a RichApi error appears. Every files seems to have a different RichApi error.

Docx document is 348.15 KB:
```
RichApi.Error: ooxmlIsMalformated
    at new n (word-web-16.00.js:25:330018)
    at o.processRequestExecutorResponseMessage (word-web-16.00.js:25:394184)
    at word-web-16.00.js:25:392247
```

Docx document is 19.28 KB, 366.46 KB and 260.44 KB:
```
RichApi.Error: Cannot read properties of null (reading 'message')
    at new n (word-web-16.00.js:25:330018)
    at o.processRequestExecutorResponseMessage (word-web-16.00.js:25:394184)
    at word-web-16.00.js:25:392247
```

Docx document is 3.54 MB and 17.05 MB:
```
RichApi.Error: forceSaveFailed
    at new n (word-web-16.00.js:25:330018)
    at o.processRequestExecutorResponseMessage (word-web-16.00.js:25:394184)
    at word-web-16.00.js:25:392247
```
The docx documents that are 60.66 KB and 71.11 KB inserted without an error.

## Steps to reproduce

1. Open Word on Web
2. Try inserting a big file using `context.document.getSelection().insertFileFromBase64(base64, "After");` or `context.document.body.insertFileFromBase64(base64, "End");`
3. Put a breakpoint after `context.sync` and see what error appears. Try other files for different errors.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. Please note that this is a regressive issue. It was working fine a week ago with no RichApi errors.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by xiruatms** [comment]
Hi, thanks for reporting this. I'm trying to repro this locally. Just want to confirm with you:
1. Are these exceptions encountered consistently or just intermittently?
2. If possible, can you share some sample docx you tried to insert (but failed) with us please? That will be much helpful for us to continue investigation.

**Comment by A-Glazer** [comment]
The issues are intermittent. I never know which documents will fail, but there are always a few that will fail. I've attached 2 examples that fail with `forceSaveFailed` . (Note: they have been saved and the document I'm inserting into has also been saved). 

Document203.docx, Document1 (4).docx:
```
RichApi.Error: forceSaveFailed
    at new n (word-web-16.00.js:25:330018)
    at o.processRequestExecutorResponseMessage (word-web-16.00.js:25:394184)
    at word-web-16.00.js:25:392247
```
[Document203.docx](https://github.com/OfficeDev/office-js/files/11010496/Document203.docx)
[Document1 (4).docx](https://github.com/OfficeDev/office-js/files/11010511/Document1.4.docx)

**Comment by A-Glazer** [comment]
Hi, Have you had a chance to look into this issue?

**Comment by lamotik** [comment]
Hi! 
We are getting same error in Word Online. Are there any updates, @xiruatms ?
@A-Glazer did you have a chance to find an alternative solution?

**Comment by A-Glazer** [comment]
@lamotik Unfortunately I have not found an alternative solution.

**Comment by knopmickael** [comment]
@A-Glazer, I also got a problem like yours, when i insertFromFileB64 into the own Word Document object, it throws:

"RichApi.Error: Can't find the inserted content. Please refresh the page for the result."

It also takes at least one minute to finish the insertion and display the error, even though the file used is only 10KB

'Course when I reload the Word online window, the file is there, but... this is killing the usability

**Comment by xiaoyuMS** [comment]
Hi @knopmickael  @A-Glazer , the fix has been deployed to production, please have a try. The full deployment may take another 1-2 days.

**Comment by knopmickael** [comment]
Did it stop working recently? Im getting a kind of timeout using the importAsBase64 method again, the same: "Cant find the inserted content, refresh the page for result"

Curiously, some base64 strings are imported fine, and others are throwing this error out

But sure, if you restart the page, the content is correctly there

**Comment by xiruatms** [comment]
@knopmickael, given lots of limitations (network delay, server latency and so on), there had to be a timeout setting. It's an expected behavior to refresh the page if you got the error message.

**Comment by scarlet2131** [comment]
hi @knopmickael, did this work for you , i have been recently getting this issue there is problem with only one file of mine, not sure whts the problem

**Comment by knopmickael** [comment]
hey @scarlet2131, since i remember, it has worked properly the last time i touched it - i could be wrong but the problem i was facing was about the number of the docx pages (already fixed btw) - if it had only 1 page it never finishes the importage, otherwise, 2+ pages use to did well
