### ISSUE TITLE
can not load side loaded excel add in from local web server

### ISSUE THREAD

**Issue by oldoldman** [OfficeDev/office-js#3217]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.16130.20258
* Operating System: Windows 11
* Browser (if using Office on the web): NA
 
## Expected behavior
the add in should be loaded

## Current behavior
I'm hosting the assets (pictures, html pages, java script etc. ) of the add in on a local web server. The add in is loaded : it showed the welcome dialog 
<img width="264" alt="image" src="https://user-images.githubusercontent.com/13962657/224973904-894f2140-4665-40e1-bd4f-b37ef01cec9e.png">
and the menu bar also loaded
<img width="129" alt="image" src="https://user-images.githubusercontent.com/13962657/224974031-a896bdcb-7e05-4141-a9fd-3cb29bc5f52b.png">
But there is an error, which prevent me to access the further functionalities of the add in.
<img width="273" alt="image" src="https://user-images.githubusercontent.com/13962657/224974339-47fcec1a-cb03-4184-b819-f0817a68fafc.png">
I've fixed this problem before in this [issue](https://github.com/OfficeDev/office-js/issues/2421), but this time it does not work. Please help, many thanks.

**Comment by gingerjia** [comment]
@oldoldman Thanks very much for reporting the issue! Can you help to share more info about your add-in to help us identify the root cause? Such as the add-in's manifest. From current info, we cannot repro the issue. Thanks!

**Comment by oldoldman** [comment]
the manifest is
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp
    xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
    xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides" 
  	xsi:type="TaskPaneApp">
    <Id>775091B3-E24A-4CF4-A65B-26976FDA4F3C</Id>
    <Version>1.0.0.0</Version>
    <ProviderName>yushang.me</ProviderName>
    <DefaultLocale>en-US</DefaultLocale>
    <DisplayName DefaultValue="e-Business Analytic Suite">
        <Override Locale="zh-CN" Value="电子商务分析套件"/>
    </DisplayName>
    <Description DefaultValue="e-Business Analytic Suite Connector">
        <Override Locale="zh-CN" Value="电子商务分析套件连接器"/>
    </Description>
    <IconUrl DefaultValue="https://ebi.local.com/assets/ebi-32.png"/>
    <HighResolutionIconUrl DefaultValue="https://ebi.local.com/assets/ebi-80.png"/>
    <SupportUrl DefaultValue="http://www.yushang.me"/>
    <AppDomains>
        <AppDomain>http://yuhang.me</AppDomain>
    </AppDomains>
    <Hosts>
        <Host Name="Workbook"/>
    </Hosts>
    <Requirements>
        <Sets DefaultMinVersion="1.1">
            <Set Name="CustomFunctionsRuntime" MinVersion="1.1"/>
            <Set Name="SharedRuntime" MinVersion="1.1"/>
        </Sets>
    </Requirements>
    <DefaultSettings>
        <SourceLocation DefaultValue="https://ebi.local.com"/>
    </DefaultSettings>
    <Permissions>ReadWriteDocument</Permissions>
    <VersionOverrides
        xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" 
  		xsi:type="VersionOverridesV1_0">
        <Hosts>
            <Host xsi:type="Workbook">
                <Runtimes>
                    <Runtime resid="shared_runtime_html_url" liefetime="long"/>
                </Runtimes>
                <AllFormFactors>
                    <ExtensionPoint xsi:type="CustomFunctions">
                        <Script>
                            <SourceLocation resid="functions_js_url"/>
                        </Script>
                        <Page>
                            <SourceLocation resid="functions_html_url"/>
                            
                        </Page>
                        <Metadata>
                            <SourceLocation resid="functions_json_url"/>
                        </Metadata>
                        <Namespace resid="functions_namespace"/>
                    </ExtensionPoint>
                </AllFormFactors>
                <DesktopFormFactor>
                    <GetStarted>
                        <Title resid="getstarted_title"/>
                        <Description resid="getstarted_description"/>
                        <LearnMoreUrl resid="getstarted_learnmore_html_url"/>
                    </GetStarted>
                    <FunctionFile resid="commands_html_url"/>
                    
                    <ExtensionPoint xsi:type="PrimaryCommandSurface">
                        <CustomTab id="MainTab">
                            <Group id="System">
                                <Label resid="system_label"/>
                                <Icon>
                                    <bt:Image size="16" resid="icon_16"/>
                                    <bt:Image size="32" resid="icon_32"/>
                                    <bt:Image size="80" resid="icon_80"/>
                                </Icon>
                                <Control xsi:type="Button" id="Login">
                                    <Label resid="login_label"/>
                                    <Supertip>
                                        <Title resid="login_supertiptitle"/>
                                        <Description resid="login_supertiptext"/>
                                    </Supertip>
                                    <Icon>
                                        <bt:Image size="16" resid="login_16"/>
                                        <bt:Image size="32" resid="login_32"/>
                                        <bt:Image size="80" resid="login_80"/>
                                    </Icon>
                                    <Action xsi:type="ExecuteFunction">
                                        <FunctionName>login</FunctionName>
                                    </Action>
                                </Control>
                                <Control xsi:type="Button" id="Resp">
                                    <Label resid="resp_label"/>
                                    <Supertip>
                                        <Title resid="resp_supertiptitle"/>
                                        <Description resid="resp_supertiptext"/>
                                    </Supertip>
                                    <Icon>
                                        <bt:Image size="16" resid="resp_16"/>
                                        <bt:Image size="32" resid="resp_32"/>
                                        <bt:Image size="80" resid="resp_80"/>
                                    </Icon>
                                    <Action xsi:type="ExecuteFunction">
                                        <FunctionName>changeresp</FunctionName>
                                    </Action>
                                    <Enabled>false</Enabled>
                                </Control>
                            </Group>
                            <Group id="Help">
                                <Label resid="help_label"/>
                                <Icon>
                                    <bt:Image size="16" resid="icon_16"/>
                                    <bt:Image size="32" resid="icon_32"/>
                                    <bt:Image size="80" resid="icon_80"/>
                                </Icon>
                                <Control xsi:type="Button" id="tutor">
                                    <Label resid="tutor_label"/>
                                    <Supertip>
                                        <Title resid="tutor_supertiptitle"/>
                                        <Description resid="tutor_supertiptext"/>
                                    </Supertip>
                                    <Icon>
                                        <bt:Image size="16" resid="tutor_16"/>
                                        <bt:Image size="32" resid="tutor_32"/>
                                        <bt:Image size="80" resid="tutor_80"/>
                                    </Icon>
                                    <Action xsi:type="ExecuteFunction">
                                        <FunctionName>ebi_help</FunctionName>
                                    </Action>
                                </Control>
                            </Group>
                            <Label resid="ebi_label"/>
                        </CustomTab>
                    </ExtensionPoint>
                </DesktopFormFactor>
            </Host>
        </Hosts>
        <Resources>
            <bt:Images>
                <bt:Image id="icon_16" DefaultValue="https://ebi.local.com/assets/ebi-16.png"/>
                <bt:Image id="icon_32" DefaultValue="https://ebi.local.com/assets/ebi-32.png"/>
                <bt:Image id="icon_80" DefaultValue="https://ebi.local.com/assets/ebi-80.png"/>
                <bt:Image id="login_16" DefaultValue="https://ebi.local.com/assets/login-16.png"/>
                <bt:Image id="login_32" DefaultValue="https://ebi.local.com/assets/login-32.png"/>
                <bt:Image id="login_80" DefaultValue="https://ebi.local.com/assets/login-80.png"/>
                <bt:Image id="resp_16" DefaultValue="https://ebi.local.com/assets/resp-16.png"/>
                <bt:Image id="resp_32" DefaultValue="https://ebi.local.com/assets/resp-32.png"/>
                <bt:Image id="resp_80" DefaultValue="https://ebi.local.com/assets/resp-80.png"/>
                <bt:Image id="tutor_16" DefaultValue="https://ebi.local.com/assets/tutor-16.png"/>
                <bt:Image id="tutor_32" DefaultValue="https://ebi.local.com/assets/tutor-32.png"/>
                <bt:Image id="tutor_80" DefaultValue="https://ebi.local.com/assets/tutor-80.png"/>
            </bt:Images>
            <bt:Urls>
                <bt:Url id="getstarted_learnmore_html_url" DefaultValue="http://blog.yushang.me"/>
                <bt:Url id="functions_html_url" DefaultValue="https://ebi.local.com/functions.html"/>
                <bt:Url id="functions_js_url" DefaultValue="https://ebi.local.com/apiset/functions.js"/>
                <bt:Url id="functions_json_url" DefaultValue="https://ebi.local.com/apiset/functions.en.json">
                	<Override Locale="zh-CN" Value="https://ebi.local.com/apiset/functions.zh.json"/>
                </bt:Url>
                <bt:Url id="commands_html_url" DefaultValue="https://ebi.local.com/commands.html"/>
                <bt:Url id="shared_runtime_html_url" DefaultValue="https://ebi.local.com/commands.html"/>
            </bt:Urls>
            <bt:ShortStrings>
                <bt:String id="getstarted_title" DefaultValue="Exploring e-Business Analytic Suite">
                    <Override Locale="zh-CN" Value="开始使用"/>
                </bt:String>
                <bt:String id="ebi_label" DefaultValue="e-Business Analytic Suite">
                    <Override Locale="zh-CN" Value="电子商务分析套件"/>
                </bt:String>
                <bt:String id="system_label" DefaultValue="System">
                    <Override Locale="zh-CN" Value="系统"/>
                </bt:String>
                <bt:String id="help_label" DefaultValue="Misc">
                    <Override Locale="zh-CN" Value="帮助"/>
                </bt:String>
                <bt:String id="tutor_label" DefaultValue="Tutorial">
                    <Override Locale="zh-CN" Value="使用教程"/>
                </bt:String>
                <bt:String id="tutor_supertiptitle" DefaultValue="Tutorial">
                    <Override Locale="zh-CN" Value="使用教程"/>
                </bt:String>
                <bt:String id="login_label" DefaultValue="Login">
                    <Override Locale="zh-CN" Value="登录"/>
                </bt:String>
                <bt:String id="login_title" DefaultValue="Login">
                    <Override Locale="zh-CN" Value="登录"/>
                </bt:String>
                <bt:String id="login_supertiptitle" DefaultValue="e-Business Analytic Suite">
                    <Override Locale="zh-CN" Value="电子商务分析套件"/>
                </bt:String>
                <bt:String id="resp_label" DefaultValue="Change Responsibility">
                    <Override Locale="zh-CN" Value="切换职责"/>
                </bt:String>
                <bt:String id="resp_title" DefaultValue="Change Responsibility">
                    <Override Locale="zh-CN" Value="切换职责"/>
                </bt:String>
                <bt:String id="resp_supertiptitle" DefaultValue="Change Responsibility">
                    <Override Locale="zh-CN" Value="切换职责"/>
                </bt:String>
                <bt:String id="functions_namespace" DefaultValue="EBI"/>
            </bt:ShortStrings>
            <bt:LongStrings>
                <bt:String id="getstarted_description" DefaultValue="Oracle e-Business Analytic Suite">
                    <Override Locale="zh-CN" Value="分析，发掘数据价值，洞悉企业运营情况"/>
                </bt:String>
                <bt:String id="login_supertiptext" DefaultValue="Log into e-Business Analytic Suite">
                    <Override Locale="zh-CN" Value="登录电子商务分析套件"/>
                </bt:String>
                <bt:String id="resp_supertiptext" DefaultValue="Switch to another responsibility">
                    <Override Locale="zh-CN" Value="切换职责"/>
                </bt:String>
                <bt:String id="tutor_supertiptext" DefaultValue="Learning how to use">
                    <Override Locale="zh-CN" Value="使用教程"/>
                </bt:String>
            </bt:LongStrings>
        </Resources>
    </VersionOverrides>
</OfficeApp>`

**Comment by gingerjia** [comment]
Thanks @oldoldman ! Two things need to modify for your mainfest:
1. AppDomains need to be https, cannot be http
<img width="271" alt="image" src="https://user-images.githubusercontent.com/62282034/226224008-234328e0-155a-4020-ab48-c45afade51d0.png">


2. CustomerFuntion runtime is also kind of sharedRuntime, so only keep one setting is ok:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/62282034/226224166-1189a0d2-c0b0-4b2c-8f25-1f45b082a437.png">

Please let us know if still met the failure issue. Thanks!

**Comment by oldoldman** [comment]
unfortunately, it does not work. I found that Excel never visit the local web server at all.

**Comment by oldoldman** [comment]
I finally found that my ssl certificate is expired. after renewing the certificate, the add in works fine. thank you guys.
