### ISSUE TITLE
Add-In is disabled while the reading pane is off

### ISSUE THREAD

**Issue by dona-maria-george** [OfficeDev/office-js#3225]
![Screenshot 2023-03-17 153458](https://user-images.githubusercontent.com/47345238/225878566-d86afcf0-1f4c-48fe-9aad-24580ee1da3d.png)
Addin is not getting enabled while the reading pane is off. We are unable to get Office.mailItem using office.js when the reading pane is off and an email is selected. It only becomes enabled when the reading pane is on and the user opens the entire email conversation.

**Comment by Oleg-O** [comment]
Currently the feature: supporting add-ins when reading pane is OFF, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
