### ISSUE TITLE
Is there a method to monitor newly received emails in Outlook that should be monitored by our add-in without a sidepanel?

### ISSUE THREAD

**Issue by KishanVaishnani** [OfficeDev/office-js#3229]
Hello

The Microsft Outlook Add-in was something I was working on.

My Client needs to keep track of fresh emails and take certain actions based on them.

I mentioned the paper.,

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest

https://learn.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&tabs=javascript

But I was unable to discover a solution.

Please provide some guidance on how to proceed.

Thanks.

**Comment by Oleg-O** [comment]
The requirement is not very clear; what emails (all emails, emails having certain attributes, content or recipients?) and what actions? If those actions could be done via Graph API, the 2nd link you included could be a good direction to explore further, but it would require a backend service calling Graph, subscribing to new email events and applying those actions via Graph API. 

On the office.js side, you could have a pinned task pane that would allow the user to take those actions from add-in taskpane UI, would that work? If you're asking about triggering your add-in automatically for incoming emails, we don't have a mechanism to do that from office.js. But it's not super clear if that's what you're asking for, which emails to trigger for and what kind of actions you want to enable (is current office.js API sufficient to facilitate those actions?).

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please clarify and submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by KishanVaishnani** [comment]
Hello @Oleg-O 

Thank you for valuable reply.

Yes, On the office.js side, I wan to develop a mechanism and which triggers for every incoming emails to inbox. Based on the incoming emails I want to perform some action via office.js side (using code)

Can this michanism possible with office.js addin javascript development?

Eighter anyway, using taskpane Ui OR some event-based if possible (without taskpane Ui user interactions)

I hope you cleared with my requirement

Thanks.

**Comment by Oleg-O** [comment]
office.js currently operates on email that is displayed in the reading pane. If you have a pinned taskpane, every time user reads new email, the add-in will get "item changed" event and you can run your code against that new email, without taskpane UI user interaction. If you want to be able to run your code without user reading the email, that is currently not possible with client-side office.js API approach. Feel free to add a request for such capability on [Tech Community Page](http://aka.ms/M365dev-suggestions). You may be able to achieve a solution via Graph subscriptions though, with a backend approach.
