### ISSUE TITLE
excel-online(office-api): add-in not working when you re-add it from store

### ISSUE THREAD

**Issue by fds-rpg** [OfficeDev/office-js#3230]
When add-in is added from store, it works normally, however when it is removed and re-added, the app would not work anymore.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows 10
* Browser (if using Office on the web): Google Chrome
 
## Expected behavior
the add-in from store works normally.

## Current behavior
When add-in is added from store, it works normally when you interact with the taskpane, however when it is removed and re-added, the app would not work anymore. The only workaround to fix this issue is to reload the page. 
The current action type we are using in our manifest is `ExecuteFunction`. We also do not have any actions that automatically opens the taskpane
![store-add-in-issue](https://user-images.githubusercontent.com/105926601/226238497-5a3071fd-9e3d-4f55-8a95-565329b333dd.gif)

## Steps to reproduce
1. Open Excel web, then click "Office add-ins" on Insert Tab from tab list
2. Add FactSet for Excel (Early Access) from store
3. Click the FactSet tab and click "Insert Formula" ribbon button and interact with the taskpane
4. Close the taskpane and remove the FactSet add-in from "Office add-ins"
5. Add FactSet for Excel (Early Access) from store again, and click "Insert Formula" ribbon button
6. Notice that the app does not display in the taskpane and the taskpane only displays a blank, nothing happens when you click the ribbon buttons as well
7. Workaround: reload the page and the add-in will run properly.

**Comment by m-hellesen** [comment]
Hey there, thanks for reporting. This is by design and we would require the session to be refreshed as we don't consider it a standard scenario to remove and reinstall add ins in the same web session.
