### ISSUE TITLE
Currently, the onSend event is not firing in Outlook on the web.

### ISSUE THREAD

**Issue by t-miyake** [OfficeDev/office-js#3231]
# Provide required information needed to triage your issue

In some tenants (I have confirmed the issue in multiple tenants), the onSend event in Outlook on the web has completely stopped firing. As a result, all add-ins that rely on the onSend event are rendered unusable.

## Your Environment

* Platform: Office on the web
* Host : Outlook on the web
* Browser : I have tested in the latest versions of Google Chrome, Microsoft Edge, as well as their respective beta and dev versions.
 
## Expected behavior

The onSend event is fired when an email is sent.

## Current behavior

The onSend event does not fire at all when sending mail.

## Steps to reproduce

 It's very simple: send an email using Outlook on the web.

## Link to live example(s)

I have created a very simple sample. Here's the code:
```Javascript
'use strict';

Office.onReady().then(function () {
    console.log('onReady');
});

function messageOnSent(event) {
    console.log('messageOnSent');
    console.log('Platform: ' + Office.context.diagnostics.platform);
    console.log('HostName: ' + Office.context.mailbox.diagnostics.hostName);
    console.log('HostVersion: ' + Office.context.mailbox.diagnostics.hostVersion);

    event.completed({
        allowEvent: true
    });
}
```

Here's the manifest file:
(Using this manifest file, you can get the simple add-in up and running.)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xsi:type="MailApp">

  <Id>E2654AB1-1352-4DB4-ABA8-5ABDEC9B9174</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Noraneko Inc.</ProviderName>
  <DefaultLocale>ja-JP</DefaultLocale>
  <DisplayName DefaultValue="Onsend" />
  <Description DefaultValue="Onsend" />
  <IconUrl DefaultValue="https://outlook.addin.app/onsend/images/icon64.png" />
  <HighResolutionIconUrl DefaultValue="https://outlook.addin.app/onsend/images/icon128.png" />
  <SupportUrl DefaultValue="https://www.noraneko.co.jp/" />

  <AppDomains>
    <AppDomain>https://outlook.addin.app</AppDomain>
  </AppDomains>

  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.3" />
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemEdit">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://outlook.addin.app/onsend/function.tml" />
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteMailbox</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit" />
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>

  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Requirements>
        <bt:Sets DefaultMinVersion="1.8">
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>
      <Hosts>
        <Host xsi:type="MailHost">
          <DesktopFormFactor>
            <FunctionFile resid="function" />
            <ExtensionPoint xsi:type="Events">
              <Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="messageOnSent" />
            </ExtensionPoint>
          </DesktopFormFactor>
        </Host>
      </Hosts>
      <Resources>
        <bt:Images>
          <bt:Image id="icon16" DefaultValue="https://outlook.addin.app/onsend/images/icon16.png" />
          <bt:Image id="icon32" DefaultValue="https://outlook.addin.app/onsend/images/icon32.png" />
          <bt:Image id="icon64" DefaultValue="https://outlook.addin.app/onsend/images/icon64.png" />
          <bt:Image id="icon80" DefaultValue="https://outlook.addin.app/onsend/images/icon80.png" />
        </bt:Images>
        <bt:Urls>
          <bt:Url id="function" DefaultValue="https://outlook.addin.app/onsend/function.html" />
        </bt:Urls>
      </Resources>
    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>
```

If you run this sample add-in in a tenant where the issue is not occurring, the following message will appear in the browser console:

```
onReady
messageOnSent
Platform: OfficeOnline
HostName: OutlookWebApp
HostVersion: 20230310007.16
```

In the tenant where the issue is occurring, nothing is output to the console.
Of course, none of the other onSend add-ins are executing either.

# Provide additional details

## Useful logs

The onSend event is firing correctly in **HostVersion: 20230310007.16**, so i believe there may be an issue with versions newer than this.

Note that onSend add-ins continue to work correctly in version 2302 (16130.20306) of Windows Outlook (Apps for enterprise).

**Comment by Oleg-O** [comment]
Thanks for reporting this issue regarding OnSend event in OWA. We'll look into this as soon as possible.

Internal tracking id: 3484173

**Comment by exextoc** [comment]
We are not able to repro the issue at our end. Can please help us with the non-working test account. Also, if you can provide the build number where the add-in is not working, it will be helpful.

**Comment by t-miyake** [comment]
Thanks for your response.

In the tenant where this problem is occurring, even the simple sample add-in above will not work because the onSend event is not firing.

For the two tenants I have identified as having the problem, nothing is output to the console when the above sample add-in is enabled, as shown below.
(Other onSend add-ins that have been working fine do not work as well.)

Neither tenant has made any configuration changes and suddenly the problem occurs.
(This problem only occurs with Outlook on the web.)
(The same problem occurs even after changing browsers, PCs, and user accounts.)

■Tenants with problems
Tenant A (our company)
https://user-images.githubusercontent.com/9583126/226466293-66ee4265-05d3-4cff-bb59-497ae2e352a9.mp4

Tenant B (our customer)
Two add-ins are enabled: the onSend add-in that has been used in the past and this sample. Currently, both are not working.
https://user-images.githubusercontent.com/9583126/226466354-23c649d3-7200-441c-971f-de8804cbb9d4.mp4

■Tenant without problem
Tenant C 
https://user-images.githubusercontent.com/9583126/226466384-826c6c86-39b0-4c0a-b7e2-886b1434cd8b.mp4


How do I know the Outlook on the web build number of the tenant with the problem?
I would like to provide as much information as possible, so please let us know how to get the information I need.

**Comment by alexm-plutoflume** [comment]
We are also seeing this behavior with our ItemSend Add-in. We are unsure if it's all users/customers or specific users. It was working internally yesterday for some users and others not. Now today it seems like it's not working for any users internally. It appears to not be launching at all in OWA.

Our Add-in also utilizes LaunchEvents, we can see that these are not being triggered either in OWA.

It is working fine in Mac & Windows.

**Comment by neville-jones** [comment]
We have a report of this from one of our customers in Australia that our on-send addin is not firing in OWA.

**Comment by t-miyake** [comment]
Our customers are reporting an increasing number of tenants and users experiencing issues with our add-in. 
As we have not made any changes to the add-in, i believe the issue is related to Outlook on the web. 
We kindly request prompt investigation and resolution of the issue.

**Comment by bluebasher** [comment]
We are also seeing the exact same issue as described above at our customers and they can not use our Add-in at all.
It seems something is broken with the event based activation.

@Oleg-O I saw you removed the `Needs: triage` label and added `Needs: attention`. Does this mean someone is actively looking into the issue? If not, can this please be prioritized since our customers can not even use our product because of this.

**Comment by exextoc** [comment]
@t-miyake Thank you for reporting the issue. We are able to repro it. We also want to highlight that this issue is only impacting users in Targeted Release, not Standard Release (learn more here: [Set up the Standard or Targeted release options - Microsoft 365 admin | Microsoft Learn](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fmicrosoft-365%2Fadmin%2Fmanage%2Frelease-options-in-office-365%3Fview%3Do365-worldwide&data=05%7C01%7Cnikitamittal%40microsoft.com%7Cc6da7d64ef71453cc0ae08db2b6fa187%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638151530723008808%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4A5caLhbmTb80Vxvj6Z1dKY3FzhqmM%2B3NBrMP5emNMA%3D&reserved=0)). We will update the thread once we have more updates on the fix.

**Comment by t-miyake** [comment]
@exextoc Thank you for your response.

I did not check enough about Targeted Release and Standard Release. I will now confirm that there is no problem in the Standard Release environment, just to be sure.

Will this problem be fixed when the Standard Release is released? Also, will the problem be fixed in the Targeted Release?

**Comment by exextoc** [comment]
The standard release will not have this problem. We are working to identify and fix the issue. Update will be provided here once the issue has been resolved.

**Comment by exextoc** [comment]
The issue should be resolved now. Please let us know if you are still able to repro the same.

**Comment by t-miyake** [comment]
@exextoc Thanks!
I have confirmed that the problem does not occur.

**Comment by t-miyake** [comment]
@exextoc I have confirmed that this issue was resolved last month.

However, it seems that the same problem is now occurring again, only for users on the Targeted Release. 
It appears that no OnSend add-ins are being executed when sending emails.

Could you please check this issue again?

**Comment by exextoc** [comment]
@t-miyake Thanks for reporting this issue. We are looking into it.

**Comment by exextoc** [comment]
@t-miyake We recently made a fix from our end and the issue should be resolved now. Please let us know if you are still able to repro the same.

**Comment by t-miyake** [comment]
@exextoc Thank you very much.
I have confirmed that the OnSend add-in works correctly on the Targeted Release users.

However, it appears that changes to Custom Addins are not applied to Targeted Release users.

If a Targeted Release user deletes an OnSend add-in from Get add-ins > My add-ins > Custom Addins, and then adds another OnSend add-in, only the deleted OnSend add-in will still work.
*Of course, i have tried clearing the browser cache and signing out user.

This is not related to this Issue, so I will check it again and make another Issue if necessary.

**Comment by t-ariyoshi30907** [comment]
@exextoc
Both I and the users around me are experiencing similar issues, and we are making inquiries on other issues as well. 

https://github.com/OfficeDev/office-js/issues/3501

Given the similarity in the problem and the situation, I believe it might be the same incident.

As we have not made any changes to the add-in, i believe the issue is related to Outlook on the web.
We kindly request prompt investigation and resolution of the issue.

**Comment by exextoc** [comment]
We are currently seeing a delay of up to four hours in installation and the add-in being available. If you are still facing issue and delay is more than four hours please let us know.

**Comment by t-ariyoshi30907** [comment]
@exextoc 

Thank you for your response.
Please provide more details about that matter.

Which one of the following is correct?
1. It's a temporary issue and will be improved.
2. Due to a specification change, delays of up to 4 hours will continue in the future.

**Comment by exextoc** [comment]
Hi @t-ariyoshi30907 , this is a temporary issue and will be resolved. But unfortunately we do not have a timeline to share at this time. Thanks.

**Comment by stefansson30952** [comment]
Is this still an issue in either standard or targeted releases?

My company is running into issues.

**Comment by exextoc** [comment]
@stefansson30952 This issue is already closed, please file a new issue with details of your addin, platform and use case.
