### ISSUE TITLE
Category doesn't get applied on on-premise exchange server

### ISSUE THREAD

**Issue by somenathmaji** [OfficeDev/office-js#3232]
# Provide required information needed to triage your issue
We have a customer who are on on-premise server. We use REST API to apply category to a message.
## Your Environment

* Platform : PC desktop
* Host : Outlook
* Office version number: version 2301 build 16.0.16026.20002
* Operating System: Windows
 
## Expected behavior
Category should be applied.

## Current behavior
Category doesn't get applied and we get the following error -

## Steps to reproduce

1. We should be on an on-premise servers
2. Use REST API to apply category
3. We get an error

## Context

Applying a category is a core feature of our app. This allows users to visualize and track messages (failed or success).
In this scenario, we are not able to apply category.

## Useful logs
![Screenshot 2023-03-20 at 11 59 12 AM](https://user-images.githubusercontent.com/10449421/226263774-d13147b9-9551-46ad-a1bc-1910b4421d6d.png)

We want to know if this can be mitigated and if there is any workaround.
Is this related to - https://techcommunity.microsoft.com/t5/exchange-team-blog/the-end-of-the-rest-api-for-on-premises-mailboxes-preview/ba-p/3221219
We will add other details once we get it from the user.

**Comment by Oleg-O** [comment]
What kind of app is this? How do you obtain the token that is used to make the REST call? There is office.js JavaScript [API to manage categories](https://learn.microsoft.com/en-us/javascript/api/outlook/office.categories?view=outlook-js-preview), could that be used in your app instead?

**Comment by somenathmaji** [comment]
@Oleg-O This is an Outlook Office addin. We get the REST token using `getCallbackTokenAsync()` with `{isRest: true}`. We tried to use the OfficeJS API to apply category on an on-premise server but it didn't work properly in the past.
Is there any other way to support it on an on-premise servers?

**Comment by somenathmaji** [comment]
Can we get an update please?

**Comment by somenathmaji** [comment]
Is there any update?

**Comment by ztcdsb** [comment]
@somenathmaji Does the customer use a hybrid server or just on-promise server only? REST is only supported with hybrid configuration and it will be deprecated in a few weeks.
Please try with office.js JavaScript [API to manage categories](https://learn.microsoft.com/en-us/javascript/api/outlook/office.categories?view=outlook-js-preview) and let us know if that works for you

**Comment by somenathmaji** [comment]
@ztcdsb Thanks for replying. We will check this and get back to you.
