### ISSUE TITLE
Location not updated on most recent calendar item when updating an recurring calendar

### ISSUE THREAD

**Issue by lawrence1403** [OfficeDev/office-js#3233]
Location not updated on most recent calendar item when updating an recurring calendar items

## Your Environment

Platform : PC Desktop, Office on the web
Host : Outlook Desktop
Office version number: Version 2302 Build 16.0.16130.2098
Operating System: Windows 10 Business 22H2 19045.2604

## Expected behavior
When I edit the location of calendar item from a recurring, all the recurring calendar items should have the new location updated, including the most recent one

## Current behavior

1. On calendar name "Events", create a recurring calendar items with meeting room "small boardroom" set as location, and add recipients.
2. Open the recurring calendar item (entire series) and change the location to "large boardroom" (one hour before the most recent calendar item)
3. On recipients and "Events"calendar, it's still showing up as "small boardroom" as location on the most recent calendar item 

## Useful logs

- [
![Screenshot 2023-03-20 144037](https://user-images.githubusercontent.com/127821240/226265450-5bf801ff-855e-4c8b-a289-211cc0464766.jpg)
 ] Screenshots

**Comment by timwan10** [comment]
Is this question about Office.Js APIs or Outlook / OWA behavior in general? 

I tried your repro both ways, in Outlook Desktop Win32. And couldn't repro your changes. 

I used the following code to set the location: 

Office.context.mailbox.item.location.setAsync("New Room");

Can you share the code you used? 

On my calendar, I went to the instances of the appointment and they were indeed updated with "New Room" Where are you seeing it NOT updated? 

I did not test this on OWA... are you only seeing this on the OWA?

**Comment by lawrence1403** [comment]
Hi,

I tried again and unfortunately I was not able to reprocuce the same error this time. 

Thanks for your help.
