### ISSUE TITLE
Custom Functions which return errors require two executions to complete in Excel Online

### ISSUE THREAD

**Issue by zpfaltersack** [OfficeDev/office-js#3234]
# Provide required information needed to triage your issue
I have some custom functions that under various conditions may return a #N/A. In Excel Online, when this happens the function requires being executed twice in order to complete. After the first execution the cell shows #BUSY and stays there indefinitely (my function handler is never even invoked), and after the second execution my function handler is actually invoked.

This does not happen in Excel Desktop. Additionally, this behavior is only exhibited when a function returns or throws a CustomFunctions.Error. When the function executes without error it will continue to recalc correctly. It's only when an error is returned that it requires two calculations to actually trigger the function handler.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: any
* Operating System: Windows
* Browser (if using Office on the web): confirmed in Chrome and Edge
 
## Expected behavior

The function shouldn't get stuck in #BUSY just because the previous execution resulted in an error.

## Current behavior

The function requires two calculations to execute the function handler after previously returning an error result.

This does not happen if the calculation is triggered programmatically. This only happens if the user edits the cell which causes a recalc to occur. 

## Steps to reproduce

I'm honestly not sure. I haven't seen it happen in a new project but it happens consistently in my application.
Here is a session ID where I've generated the error several times: 351de201-5376-4871-9ace-662cba297b4d
I don't have any insight into the issue so I'm unable to dig any deeper and am hoping for some diagnostic support.

## Context

We have some functions that resolve dynamic dependencies and external actions can cause them to error. This is by design and a part of our workflow, but it is really impactful that fixing the external dependency does not reliably allow us to calculate the function and show the user they resolved their error.

**Comment by ghost** [comment]
Thank you for letting us know about this issue. We will take a look shortly. Thanks.
