### ISSUE TITLE
Word: Displaced Bookmarks

### ISSUE THREAD

**Issue by handofthecode** [OfficeDev/office-js#3235]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

MacOS Word 16.70 - Office.js

I'm curious why when I try to insert this xml (attached, so you can try it), the bookmark (w:name= \"TEST\") gets moved so that BookmarkStart (moved outside and before content control) and BookmarkEnd (moved after paragraph), both get moved and no longer have the same parent nodes? They also get this property added, which indicates that they have been displaced: w:displacedByCustomXml= \"next\".

I just wonder why this is happening. It seems like this is valid ooxml.
Here are screenshots as well.

**BEFORE:**
<img width="708" alt="before insert" src="https://user-images.githubusercontent.com/20215308/226425159-78cf0233-9fb5-4eb1-ae77-502bfb709b00.png">

**AFTER:**
<img width="708" alt="after insert" src="https://user-images.githubusercontent.com/20215308/226425253-aa7d1e82-d7d4-41bc-b8d5-4673ea2fc502.png">

You can repro by `body.insertOoxml` ing the following xml:
https://gist.github.com/handofthecode/e808cd4943c1ec4185e08435db9329d3

**Comment by jipyua** [comment]
thanks for reporting this, can you share your original word document of the attached xml? Also can you try to copy the content in the document and paste it to another word document to check whether you see the same displace?
