### ISSUE TITLE
Outlook add-in REST API : Getting 404 and 403 while fetching message content

### ISSUE THREAD

**Issue by gs-achandrakamal** [OfficeDev/office-js#3236]
# Provide required information needed to triage your issue
Multiple users are getting 404 and 403 while trying fetch message content using Outlook REST API.
## Your Environment

We are yet to confirm other environment configuration  as multiple users are facing it
* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior

Message content should be fetched properly if proper rest url, item's restId and accessToken is used 

## Current behavior

404 : We are getting "Invalid MailboxItemId" error with following message "Item <messageId> doesn't belong to the targeted mailbox <id>"
403 : For other set of users, we get code "ErrorAccessDenied" along with message : "Access is denied. Check credentials and try again."

## Steps to reproduce

1. Got accessToken successfully using Office.context.mailbox.getCallbackTokenAsync
2. Got Item's REST Id as described [here](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api#example-1)
3. Getting 404 or 403 while fetching the content using access token with "Item <messageId> doesn't belong to the targeted mailbox <id>" or "Access is denied" message respectively.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by zhngx1** [comment]
Can you provide your Outlook version and if you are on windows/mac? Were you running the same code as in the link you provided?

**Comment by gs-achandrakamal** [comment]
Yes, I can confirm on using the same code to get REST Id.One of the user facing this in on windows. Please refer to the attached screenshot.



<img width="669" alt="Screenshot 2023-03-30 at 3 41 39 PM" src="https://user-images.githubusercontent.com/72736097/228805639-b9f665ef-06a5-40ed-b417-cbb7b853ef2b.png">

**Comment by gs-achandrakamal** [comment]
We are also seeing multiple occurrences of  users getting 403 with error code : "ErrorAccessDenied" and message : "Access is denied. Check credentials and try again."
Attaching version Screenshots for one of the users.As per her, it is happening only on the desktop version.
Any help would be appreciated.

P.S. : Also modifying original issue by adding 403 case

![image-20230329-142642](https://user-images.githubusercontent.com/72736097/228809810-af547f7f-7a55-4d1f-853c-141d8836ea7a.png)


<img width="1118" alt="Screenshot 2023-03-30 at 4 17 07 PM" src="https://user-images.githubusercontent.com/72736097/228813292-c09fb8fd-5067-4dca-b670-71e1542587d6.png">

**Comment by zhngx1** [comment]
Can you make sure that the access token and the item and resturl are for the same mailbox? Based on the error message, it seems that item does not belong to the mailbox or the access token is invalid.

**Comment by gs-achandrakamal** [comment]
As per our logs, REST Url seems to be correct(have also attached one screenshot in above comment). Access token and REST Id is taken as exactly as mentioned in the [documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/use-rest-api#example-1).

**Comment by zhngx1** [comment]
1. Does the issue happen all the time, or you see the error occasionally? 
2. Do you use on-premises Exchange deployments? Client-side requests using AJAX or similar libraries fail because CORS isn't supported in that server setup.
3. Can you test the same code in Script Lab and see if it still gives you the same error? https://learn.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab

**Comment by gs-achandrakamal** [comment]
It's regarding one of the users facing 403.
1. Does the issue happen all the time, or you see the error occasionally? => Yes, it's happening all the time for the user facing 403 on Outlook desktop for every email. On Outlook web app, it is confirmed that things work successfully
2. They don't seem to be using on-premise and are not getting CORS error. Also rest url is starting with  "outlook.office.com" which shouldn't give CORS error.
3. As it's happening on customer's system and not reproducible for us , it doesn't seem to be feasible to have scriptLab setup. However we ran the regular devtool and got the mentioned error.

**Comment by zhngx1** [comment]
Since we cannot reproduce the issue, is it ok to ask your customer to install ScriptLab and run the sample "get the message using Rest" as ScriptLab is free and publicly available?

**Comment by gs-achandrakamal** [comment]
Sure, we will check with them with the suggested sample if they are okay with the setup. Please let us know if any other snippet or log needs to be checked.

**Comment by zhngx1** [comment]
@gs-achandrakamal Is there any update on the result of the testing using ScriptLab?

**Comment by gs-achandrakamal** [comment]
No, user mentioned that she would get confirmation from their IT team for running ScriptLab. Haven't heard back after that.
We still are seeing logs for multiple users happening intermittently.  Do you think migrating to Graph API can make a difference ?

**Comment by zhngx1** [comment]
Yes, migrating to Graph API is definitely an option. You should use Microsoft Graph whenever possible. However, in this scenario, it is important for your customers to confirm that if their IT team is blocking/restricting any Rest calls.
