### ISSUE TITLE
How to add fields to a document programatically?

### ISSUE THREAD

**Issue by libjosep** [OfficeDev/office-js#3237]
I am looking for a way to insert a field at a particular position in the document. I don't see a way to insert field. Is it supported in office.js?

**Comment by Oleg-O** [comment]
Is this for an add-in for Word?

**Comment by libjosep** [comment]
Closing this since there is a preview API (https://learn.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview#word-word-range-insertfield-member(1)) available.
