### ISSUE TITLE
Event not valid in schema using Visual Studio

### ISSUE THREAD

**Issue by Will-Blackburn** [OfficeDev/office-js#324]
Using the &lt;ExtensionPoint xsi:type="Events"&gt; results in an error:

This is an invalid xsi:type 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1:Events'

The open GitHub item is on the example code, which fails as well:

https://github.com/OfficeDev/Outlook-Add-in-On-Send

**Comment by Will-Blackburn** [comment]
Just to add I'd only seen it in Visual Studio 2017 and had not tried to deploy the manifest file as @mhzer had the issue deploying so I'd made the assumption it was related and I would also get the same error.

**Comment by kbrandl** [comment]
@exextoc can you provide an update on this issue (per recent customer inquiries earlier in this thread)?

**Comment by Harkole** [comment]
Apologies it's rather busy at the moment so I've not had chance to attempt the work around in Visual Studio but as @mhzer has stated it's more about getting it accepted in Office365 for the clients to work with it

Edit, sorry posted from my personal account, this is @Will-Blackburn

**Comment by exextoc** [comment]
@kbrandl we have engaged the right team to address this issue. We are waiting for an update from that team.

**Comment by kbrandl** [comment]
@exextoc thanks for the update. We'll look forward to you adding additional info to this thread when you hear back from that team.

**Comment by Will-Blackburn** [comment]
@dmahugh / @exextoc / @kbrandl Any update news please? The fix pending label was applied late January but nothing else seems to have happened.

We have a product that is all but ready to release but awaiting the validation schema. Could some one please let us know if this is going to release soon (next few weeks) or if it's something that we could still be waiting for in 6 months time?

It's been a quarter of a year since this issue was opened and we still don't know when/what to expect with the fix. I'm really getting pressure from the directors to get something done about it so we can bring our product to the clients that are pushing us for a release

**Comment by mhzer** [comment]
I would also appreciate an update on this issue.

**Comment by exextoc** [comment]
Please note that there are two different issues described in this thread (that happen to show the same error). Sorry for the confusion.

The schema that Visual Studio uses to validate add-ins is not up-to-date, and I don't have an update on that issue at this time.

The second issue was that On Send add-ins could not be installed via Centralized Deployment. The fix for this second issue has been deployed, and On Send add-ins can now be installed via Centralized Deployment.

As a workaround for the Visual Studio validation error, since the add-in manifest is also validated when it is installed, I would recommended installing the add-in as an alternative way to validate its schema. There is actually additional manifest validation beyond what is possible with an XML schema that runs when the add-in is installed, so I would highly recommend testing via this route.

**Comment by Will-Blackburn** [comment]
@exextoc thank you for the update, I've updated the title to reflect the issue outstanding more accurately

**Comment by exextoc** [comment]
OnSend Event is only supported in VS2019 and not in VS2017.

**Comment by arieljake-bluescape** [comment]
@exextoc does VS2019 include Visual Studio Code Version 1.32.3 (1.32.3)?

**Comment by exextoc** [comment]
No, VS2019 does not include Visual Studio Code Version 1.32.3

**Comment by sonalpandit03** [comment]
Using the statement <ExtensionPoint xsi:type="LaunchEvent"> I am getting an error:

This is an invalid xsi:type 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1:LaunchEvent'.	

I have tried an example of adding an "OnNewMessageCompose" event from Microsoft docs for Outlook add-in.

Please tell me why is not working in Visual Studio and if there is any workaround for it.

**Comment by RAJDriver** [comment]
Also having this issue in VIsual Studio with "This is an invalid xsi:type 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1:LaunchEvent'."

**Comment by millerds** [comment]
It's possible that the version of Visual Studio has outdated add-in manifest validation schemas (they can get updated faster then VS is patched).  If you get validation errors for the manifest, your first troubleshooting step should be to replace one or more of these files with the latest versions. For detailed instructions, see [Manifest schema validation errors in Visual Studio projects](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-development-errors#manifest-schema-validation-errors-in-visual-studio-projects).
