### ISSUE TITLE
word-win32-16.01.js #

### ISSUE THREAD

**Issue by LeonardoB23** [OfficeDev/office-js#3242]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# I want to put auto-generated content controls in a table below the headers and gives "An internal error has occurred"

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Steps to reproduce

let controlContent;

async function createContentControlsToTable(control) {
	await Word.run(async (context) => {

		const contentControl = context.document.getSelection();
	
		contentControl.tag = control;
		contentControl.title = control.toUpperCase();
		contentControl.subtype = "RichTextTableCell";
		contentControl.placeholderText = "Text ";		
		contentControl.appearance = "Tags";
		contentControl.font.color = "#000000";
		contentControl.font.bold = false;		
		controlContent = contentControl;
	});

	return controlContent;
}

async function createTable(arrayParams) {	
	await Word.run( async function(context) {		
		var table = new Office.TableData();
		
		let array = arrayParams;
		let arrayText = [];

		for (var i = 0; i < array.length; i++) {
			const contentControl = await createContentControlsToTable(array[i]);
			arrayText.push(contentControl);
			console.log(arrayText);
		}
		
		table.headers = [array];
		table.rows = [arrayText];
		// Insert the table into the Word document
		Office.context.document.setSelectedDataAsync(table, { coercionType: 'table' }, function(result) {
			console.log(table);
			arrays = [];
			arrayToTable = [];
			if (result.status === Office.AsyncResultStatus.Failed) {
				console.error(result.error.message);
			}
		});

		return context.sync();
	});
}

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by penglongzhaochina** [comment]
Hi @LeonardoB23  Which platform? word desktop or word online?

**Comment by Searion** [comment]
Thanks for reporting this issue. In steps to reproduce, context.document.getSelection() returns a Range but not a ContentControl. I think it may be the reason of the error?

**Comment by LeonardoB23** [comment]
So, how i put the contentControl auto-generated in the table, because I save them in a array, then insert them in the table.
All cells have the same tag.
