### ISSUE TITLE
Outlook: Register the online-meeting template for Wire

### ISSUE THREAD

**Issue by Veki301** [OfficeDev/office-js#3246]
Can you register the online meeting template for Wire service (still under development). Also if you don't mind me asking, the template will be using dynamically assigned join links, do you require some different notation in this template in that case? Thank you.

```
<div>
    <p>Vedran Ivanković is inviting you to join this meeting in Wire.</p>
    <p>Join meeting in Wire <a href="https://wire-account-staging.zinfra.io/conversation-join/?key=1Qh_zllgz9JGgco5IuE0&code=yk7mhUBWF2fZ_jJlsNeL">https://wire-account-staging.zinfra.io/conversation-join/?key=1Qh_zllgz9JGgco5IuE0&code=yk7mhUBWF2fZ_jJlsNeL</a></p>
    <p><a href="https://wire.com/en/download/">Download Wire</a></p>
    <p><a href="">Get Wire add-in for Outlook</a></p>
  </div>
```

**Comment by yjoshi-msft** [comment]
Hi Veki301, 
Thanks for placing the request. As a process, we add new partners once every semester. We recently completed the activity for this semester and would expect to pick this up latest by Sept 2023.
