### ISSUE TITLE
The problem with the Russian language is in the add-in.

### ISSUE THREAD

**Issue by Fernosty** [OfficeDev/office-js#3247]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2301 16.0.16026.20214
* Operating System: Windows 11
* Browser (if using Office on the web): ______
 
## Expected behavior
Adding several buttons to the panel with the correct description in Russian.

## Current behavior
Descriptions in Russian have incomprehensible characters that clearly indicate a problem with encoding.
If suggesting a change/improvement, explain the difference from current behavior

## Steps to reproduce

1. Adding descriptions in Russian in the xml manifest file
2. Adding an add-in to Outlook
3. Re-visit Outlook several times and there is a problem with encoding (Everything works correctly when you add it for the first time)

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [x] [Screenshots](https://drive.google.com/file/d/1ts3hblQejecnMoCV_DMM4fBgbJzcWjmf/view?usp=sharing)
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Oleg-O** [comment]
Is it possible to share the manifest file, or at least the relevant portion of it here? I wasn't able to reproduce this so far.

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
