### ISSUE TITLE
Office.context.mailbox.item.(to,cc,bcc) :  Alias email recipients type always is external user.

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#3248]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: All
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2302 Build 16.0.16130.20298
* Operating System: Windows 
* Browser (if using Office on the web):  Chrome
 
## Expected behavior
should return internal

## Current behavior
always return external for all platforms and browsers

## Steps to reproduce

1. open scriptlab and select sample : Get and set to (Message Compose)
2. console.log with recipientType from user
3. see the result always is external

## Context
- we should get correct recipients type to compose our email to target users

## Useful logs
Windows: 
![windows](https://user-images.githubusercontent.com/13063615/227421604-5083cbf7-6746-4b5e-a5cb-30b0804c8984.png)

Browser
![web](https://user-images.githubusercontent.com/13063615/227422565-25c10974-88e2-45d3-a178-e1e2126ccf2b.png)

Mac:
<img width="911" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/13063615/227478632-eb11ece4-fb64-4c1a-b8b2-ef95b8dc170f.png">

**Comment by exextoc** [comment]
There are several ways a user can enter the email-id in the To field  like from address-book, Contacts, typed in etc. Can you please let us know how you are entering the email address .It will be more helpful if you can share a repro video

**Comment by jasonhieu1905** [comment]
@exextoc : we normally copy and paste the value from here into the recipient:

![image](https://user-images.githubusercontent.com/13063615/228592171-d41a698a-a8c3-45f0-8237-40965b666f83.png)

We do not see the suggestion about Alias when click To/Cc/Bcc, hope that helps.

**Comment by exextoc** [comment]
We are not able to repro this issue. To investigate it further can you please share a repro video with us??

**Comment by jasonhieu1905** [comment]
@exextoc : I attached the gif.
In this scenario, I chose 2 users (both are same domain). The first one is email, the second I entered the alias address. You can see it returns **externalUser** recipientType for the Alias address.

![chrome_zpiHw10lbM](https://user-images.githubusercontent.com/13063615/229019341-56b34247-ae12-47dc-af38-45130e3de556.gif)

Note that I could not select alias from here
![image](https://user-images.githubusercontent.com/13063615/229019499-bad71e86-cdf4-4e15-a9e4-213916be3cdc.png)

**Comment by exextoc** [comment]
@jasonhieu1905 Thank you for reporting this issue. However, this is an expected behavior. The recipientType value should be ExternalUser unless the value is resolved by Outlook. Please refer the following documentation: [https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailboxenums.recipienttype?view=outlook-js-preview](https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailboxenums.recipienttype?view=outlook-js-preview)

Currently, our documentation calls out this behavior only for Win32. We would be updating it to call out that the behavior is true for other platforms as well.
