### ISSUE TITLE
Office.context.mailbox.item.(to,cc,bcc) : Dynamic distribution list recipientType should be 'distributionList'

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#3249]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: All
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2302 Build 16.0.16130.20298
* Operating System: Windows 
* Browser (if using Office on the web):  Chrome
 
## Expected behavior
should be distributionList in all platforms and environments.

## Current behavior
Recipient type :
- Web: distributionList
- App: other

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/13063615/227485538-8f438647-2e82-40ee-8ed4-0739f2da8320.png">

![distribution](https://user-images.githubusercontent.com/13063615/227483703-94b96e59-2615-4d03-9875-82391c7a60dc.png)

## Steps to reproduce

1. create new email, enter dynamic distribution list
2. open scriptlab and select sample : Get and set to (Message Compose)
3. console.log with recipientType from user
4. see the result is different between web and app

## Context
- we should get correct recipients type to compose our email to target users

**Comment by timwan10** [comment]
Can you provide some details on the severity and scenario you are trying to accomplish? What do you do with the recipient once you know it's a dynamic distribution list? (are you trying to get who is in the list?)

**Comment by jasonhieu1905** [comment]
@timwan10 : We had an addin to insert the signature into outlook. Before that, we need to know our target audiences and context so that we can prepare correct signatures. Hope that helps.

**Comment by timwan10** [comment]
The product team has put this on the backlog, and it should be fixed in an upcoming build of Outlook. (assuming there aren't any issues) I will update with the fix build number once that information is available.

Internal Tracking id:  7822410

**Comment by timwan10** [comment]
This should be fixed in build 16.0.16529.10000 and later. (This build should be rolled out to Monthly Channels in about a month, and then other delayed channels as they update on their normal cadence).

**Comment by jasonhieu1905** [comment]
@timwan10 : thanks for the help, it's working now as expected in the mentioned environments. 😃
