### ISSUE TITLE
MacOS Excel sheet name can still be renamed after protection

### ISSUE THREAD

**Issue by kreja** [OfficeDev/office-js#325]
## Expected Behavior
Can't rename the sheet after protection.

## Current Behavior
sheets still can be renamed after setting protection

## Steps to Reproduce, or Live Example

* steps:
  1. set protection of sheet
  2. change sheet name
  3. shouldn't be successful but actually succeed

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: __MacOs: 10.13.6____
* Host [Excel, Word, PowerPoint, etc.]: ___Excel___
* Office version number: ___16.16.4___
* Operating System: ___MacOs___

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

![image](https://user-images.githubusercontent.com/7478555/49624133-41c7d680-fa0b-11e8-8366-8f636b15a657.png)

Seems windows is ok: https://stackoverflow.com/a/53623609/4004884

**Comment by kbrandl** [comment]
@kreja thanks for reaching out and sorry to hear that you've run into this problem. Can you please update this issue to add the code that you're using to protect the workbook (so that we're able to repro this problem, exactly as you're experiencing it)?

**Comment by kreja** [comment]
@kbrandl https://gist.github.com/95ac89f2757aa1efb42e4c548b7a0dd3  you can run this snippet in Script Lab

**Comment by JuaneloJuanelo** [comment]
@kreja  worksheet protection does NOT protect changing the sheet name, not even by using the UI directly. If you want that you need to protect the workbook.
  context.workbook.protection.protect();

please confirm so we can close this issue.

**Comment by kreja** [comment]
@JuaneloJuanelo You're right! Protecting the workbook does work. But it also stops users from creating new sheets which doesn't satisfy my requirement. 😞

**Comment by JuaneloJuanelo** [comment]
I know but this is just how Excel protection works.  

I am not sure about your scenario, but if you are preventing users from  renaming sheets, sounds like you also should be controlling sheet creation, so your add-in can unprotect-create sheet-protect as needed.
