### ISSUE TITLE
Inconsistency regarding a Shape's 'width' property (positive or negative?)

### ISSUE THREAD

**Issue by BBX999** [OfficeDev/office-js#3251]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

In the main documentation for the PowerPoint.Shape class [here](https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.shape?view=powerpoint-js-preview#powerpoint-powerpoint-shape-width-member) it says that Shape.width must be a positive value (throws an exception if negative).

However, over [here](https://learn.microsoft.com/en-us/office/dev/add-ins/powerpoint/shapes#lines), when discussing working with Lines, which are a type of Shape, it says that the width can have a negative value (which makes sense if the line is going backwards, basically has an ending X or Y lower than its origin X / Y).

I ran into this because even when a line's width is negative, when you access it via Shape.width, it comes back as positive, thereby making it impossible for me to determine the endpoint of a line.

Is there someone where I should submit an issue regarding the request for Shape.width to RETURN a negative value if it is a negative value, such as in the case of a line?

Thank you!

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @BBX999. I'll transfer this issue to the office-js repo where bugs are tracked and assign this to someone on the PowerPoint API feature crew.

**Comment by BBX999** [comment]
Thanks Alex! Should I close this issue here then?
