### ISSUE TITLE
Excel.Worksheet onVisibilityChanged Event no longer exists?

### ISSUE THREAD

**Issue by sharaseem** [OfficeDev/office-js#3254]
# I was using worksheet.onVisibilityChanged event for detecting visibility change of worksheet. But now the events is showing as undefined on calling and the worksheet object is not longer showing that event. Microsoft documentation still shows the event usage
https://learn.microsoft.com/en-us/javascript/api/excel/excel.worksheet?view=excel-js-preview#excel-excel-worksheet-onvisibilitychanged-member
Please let me know whether it is removed ,if removed alternative way of using the same.

Thanks

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number :Microsoft® Excel® for Microsoft 365 MSO (Version 2303 Build 16.0.16227.20202) 64-bit
* Operating System: Windows 11 Enterprise
* Browser (if using Office on the web): 
 
## Expected behavior
 worksheet.onVisibilityChanged event was available previosuly and now showing unavailable in the object

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by YueLi-MSFT** [comment]
@sharaseem Hi Sharaseem, thanks for your waiting so long. I have successfully run it on my side, and everything is functioning as expected. Could you please test the event again on your end. If you do, it would be very helpful if you could share your gist with me so I can investigate further. Thank you!

**Comment by YueLi-MSFT** [comment]
We appreciate your feedback and the details you provided about this issue. However, we have tried to reproduce the issue on our end and we were not able to do so. Therefore, we have decided to close this issue for now, but we will keep an eye on it and re-open it if you encounter any issue in the future.
