### ISSUE TITLE
Pin task pane in Outlook "New Email" window does not work as expected

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/office-js#3255]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

In Microsoft Outlook on the desktop (probably others but haven't tried) if you pin a task pane while creating a new email the pin icon appears to have worked

BUT

Next time you go to create a new email the task pane is missing

Internal reference 5570

**Comment by Oleg-O** [comment]
What version of Outlook are you experiencing this issue with? Does this consistently reproduce for you? Is this impacting one user or multiple users?

**Comment by catmanjan** [comment]
@Oleg-O here is the version

It is consistently reproducible for all users

The strange thing is when I open the task pane the pin icon appears "pinned" so it is clearly remembering that I pinned it, but it isn't showing up in New Emails

![image](https://user-images.githubusercontent.com/137350/228082615-1dad14ac-ef81-4683-9074-02186f3e190e.png)

**Comment by ndeleuze** [comment]
@catmanjan what OS are you on?

**Comment by catmanjan** [comment]
@ndeleuze Windows 11 enterprise

**Comment by ndeleuze** [comment]
@catmanjan Would you be able to confirm that your OS version is 22H2?

**Comment by catmanjan** [comment]
@ndeleuze can you tell from this?

![image](https://user-images.githubusercontent.com/137350/228671901-d184b821-7644-461c-82bc-7ce24396562d.png)

**Comment by ndeleuze** [comment]
@catmanjan If you go to Settings -> System -> About (or type About Your PC in the start menu) you should see Edition and Version under Windows specifications

**Comment by catmanjan** [comment]
@ndeleuze 
![image](https://user-images.githubusercontent.com/137350/228677045-82622eaf-024a-497f-b2d3-2a15778aa7e2.png)

**Comment by ndeleuze** [comment]
@catmanjan I'm having some trouble reproducing this issue with the same OS and Outlook version. Does this happen for all pinnable add-ins or just for a specific add-in?

**Comment by catmanjan** [comment]
@ndeleuze all pinnable add-ins have the issue

**Comment by catmanjan** [comment]
@ndeleuze note that its only when composing a new message in a new window

**Comment by ndeleuze** [comment]
@catmanjan Would you be able to record and share a video of the issue you're seeing?

**Comment by catmanjan** [comment]
[screen-recorder-thu-mar-30-2023-11-09-56.webm](https://user-images.githubusercontent.com/137350/228695538-811665f1-aaeb-4e5f-b81d-689847c123d9.webm)

**Comment by ndeleuze** [comment]
@catmanjan 

Thanks for reporting this issue regarding Custom Tab Add-in Pinning. It has been put on our backlog. We unfortunately have no timelines to share at this point.

 

Internal tracking id: Office: 7753489

**Comment by ndeleuze** [comment]
@catmanjan A workaround for this issue is to remove the custom tab from your add-in. As a note, custom tab add-ins are not currently supported in Outlook for Mac. Documentation can be found [here](https://learn.microsoft.com/en-us/javascript/api/manifest/customtab?view=powerpoint-js-preview).

**Comment by catmanjan** [comment]
Okay thanks, any idea when this will be fixed for add ins with custom tabs? @ndeleuze

**Comment by ndeleuze** [comment]
@catmanjan we are having discussions with the team, but currently don't have a timeline for when this issue will be resolved.
