### ISSUE TITLE
Outlook REST API call ends with 403 response code when auth with callback token from OfficeJs on IOS

### ISSUE THREAD

**Issue by yuwu9145** [OfficeDev/office-js#3257]
# Provide required information needed to triage your issue
Callback Token works fine for desktop clients.

However, for Microsoft Outlook on IOS, the callback token is invalid and REST API request ends with 403 if using the token to auth.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: IOS
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook (4.2234.2)
* Operating System: IOS 14.7
 
## Expected behavior

Callback Token should work for IOS outlook in the same way as in desktop outlook

## Current behavior

403

## Steps to reproduce

1. use o365 account;
2. on IOS with MS Outlook version 4.2234.2 сall OfficeJs getCallbackTokenAsync, handle callback with the token;
3. Make REST API call https://outlook.office365.com/api/v2.0/me/messages/[your ItemId] with the token;

## Context

Our add-in cannot fetch email body file and serve client

Maybe related to https://github.com/OfficeDev/office-js/issues/1737

**Comment by yuwu9145** [comment]
It has been a week, any update?

**Comment by exextoc** [comment]
Thanks for reporting this issue. However, we are not able to reproduce this issue. Can you please share sample code with which this issue reproduces?

**Comment by yuwu9145** [comment]
Sure, in our app, we grab ews token via this code:

```js
Office.context.mailbox.getCallbackTokenAsync(
      { isRest: true },
      (asyncResult: Office.AsyncResult<string>) => {
        if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
          // Cache the result from the server.
          resolve(asyncResult.value); // ews token
        } 
      }
    )
```

Then we use this token to hit restfulUrl returned from `Office.context.mailbox.restUrl` https://outlook.office365.com/api/v2.0/me/messages/[messageId].

Result:

- Works for desktop/web outlook
- But for Iphone IOS environment, that endpoint returns 403

**Comment by exextoc** [comment]
The code you shared looks fine. We are not able to reproduce the issue with that. For further investigation, can you share the test account where this repros, to this email id- OutlookExtensibility@M365x27035562.onmicrosoft.com?

**Comment by yuwu9145** [comment]
I got some information that could be important, the cause is probably `Office.context.mailbox.convertToRestId`.


## On web version (working):

```js
this.emailId = Office.context.mailbox.convertToRestId(
          outlookItem.itemId,
          Office.MailboxEnums.RestVersion.v1_0
        );

// returns AAMkADUxNGI2YmVjLTE5MTktNDg1Ni05OWU0LTJhYmNjNzlhMzAxMABGAAAAAAC9MlF_mCK3RoKlFo-eIjgCBwCxxMczl_TfQaEKFGnQmiAAAAAAAAEMAACxxMczl_TfQaEKFGnQmiAAAAQ0bbHVAAA=
```





```json
{
  ...
  "appctx": "{\"oid\":\"xxx\",\"smtp\":\"xxx\",\"upn\":\"xxx\",\"scope\":\"ParentItemId:AAMkADUxNGI2YmVjLTE5MTktNDg1Ni05OWU0LTJhYmNjNzlhMzAxMABGAAAAAAC9MlF+mCK3RoKlFo/eIjgCBwCxxMczl+TfQaEKFGnQmiAAAAAAAAEMAACxxMczl+TfQaEKFGnQmiAAAAQ0bbHVAAA=\"}",
  "happ": "owa"
}
```

## For IOS which is broken:

`Office.context.mailbox.convertToRestId` doesn't work and `ParentItemId` in token scope returns a different value


```js
this.emailId = Office.context.mailbox.convertToRestId(
          outlookItem.itemId,
          Office.MailboxEnums.RestVersion.v1_0
        );

// returns undefined
```

```json
{
 ...,
  "appctx": "{\"oid\":\"xxx\",\"smtp\":\"xxx\",\"upn\":\"xxx\",\"scope\":\"ParentItemId:AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0AscTHM5fk30GhChRp0JogAAAENHDpUwAA\"}",
  "happ": "API"
}
```

**Comment by yuwu9145** [comment]
I think I found the cause, according to the [doc](https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-1.5&preserve-view=true#outlook-office-mailbox-converttorestid-member(1)),

![image](https://user-images.githubusercontent.com/5698884/231033557-768b3482-69bc-4851-88ae-2c9c969760a8.png)
