### ISSUE TITLE
[Outlook Mobile] Office.context.mailbox.item.body.getAsync is not working on Xiaomi Mi8

### ISSUE THREAD

**Issue by kharenzze** [OfficeDev/office-js#326]
I need to use Office.context.mailbox.item.body.getAsync in order to get the content of an email, but the callback is never called. I've tried with several emails, just to ensure the problem is not related to the content. I've never noticed this problem on desktop, iPhone/iPad or different Android devices. 

## Expected Behavior
The callback method I pass as an argument should be executed, as described [here](https://docs.microsoft.com/en-us/javascript/api/office/office.asyncresult?view=office-js)

## Current Behavior
The callback is never called. 

## Steps to Reproduce, or Live Example
It's easy to reproduce. When Office.js is initialized, call the function. As mentioned above, it's working fine on other devices but this one.

## Your Environment

* Host: Outlook Mobile
* Office version number: 1.1

Device Info:
* Xiaomi Mi 8
* MIUI version: MIUI Global 10.0.3.0
* Android version: 8.1.0

## Useful logs
It's quite difficult to debug, since I cannot easily attach a debugger.

**Comment by saurabhtripathi-iitd** [comment]
Thanks for reporting it.

Our team will work on it.

Thanks,
Outlook Mobile

**Comment by anilreddyr7** [comment]
I'm facing the same issue with one of my android devices. 
Device Info:
Lenovo K5 Note
Android Version:6.0

I need to use Office.context.mailbox.item.body.getAsync in order to get the content of an email, but the callback is never called. Is this the bug from Office Js?

**Comment by satrip** [comment]
This was an issue from Android client side. We have fixed it and will be in production by second week of January.

**Comment by anilreddyr7** [comment]
> This was an issue from Android client side. We have fixed it and will be in production by second week of January.

Cool. Thanks.

**Comment by SWei1234** [comment]
Office.context.mailbox.item.body.getAsync not work in windows and mac outlook client. it will be blocked so that never run the then part.

**Comment by anilreddyr7** [comment]
What does that mean? Get Async doesn't work in windows and mac client? How to get email body in this case?

**Comment by SWei1234** [comment]
> What does that mean? Get Async doesn't work in windows and mac client? How to get email body in this case?

My Code Like:
Office.context.mailbox.item.body.getAsync("html", {coercionType: Office.CoercionType.Html}, function (result) {
//bla bla bla
console.log("test test test");
});
But I can't get "test test test" shown in console. 
This problem happened in both windows (outlook 2019 preview version) and mac outlook 2016.  
 Only in excuteFunction it happened . Code above works well on both browser and outlook sidebar.

**Comment by Navega** [comment]
> > What does that mean? Get Async doesn't work in windows and mac client? How to get email body in this case?
> 
> My Code Like:
> Office.context.mailbox.item.body.getAsync("html", {coercionType: Office.CoercionType.Html}, function (result) {
> //bla bla bla
> console.log("test test test");
> });
> But I can't get "test test test" shown in console.
> This problem happened in both windows (outlook 2019 preview version) and mac outlook 2016.
> Only in excuteFunction it happened . Code above works well on both browser and outlook sidebar.

It is working fine for us. I think that you should rewrite the call to that function, check [getAsync](https://docs.microsoft.com/es-es/javascript/api/outlook_1_5/office.body?view=office-js#getasync-coerciontype--options--callback-) to verify the arguments that you use.

Try with:

```
Office.context.mailbox.item.body.getAsync(Office.CoercionType.Html, function (result) {
    //bla bla bla  
    console.log("test test test");  
});
```

The 1st parameter must be the [CoercionType enum](https://docs.microsoft.com/en-us/javascript/api/office/office.coerciontype?view=office-js).

**Comment by SWei1234** [comment]
> > > What does that mean? Get Async doesn't work in windows and mac client? How to get email body in this case?
> > 
> > 
> > My Code Like:
> > Office.context.mailbox.item.body.getAsync("html", {coercionType: Office.CoercionType.Html}, function (result) {
> > //bla bla bla
> > console.log("test test test");
> > });
> > But I can't get "test test test" shown in console.
> > This problem happened in both windows (outlook 2019 preview version) and mac outlook 2016.
> > Only in excuteFunction it happened . Code above works well on both browser and outlook sidebar.
> 
> It is working fine for us. I think that you should rewrite the call to that function, check [getAsync](https://docs.microsoft.com/es-es/javascript/api/outlook_1_5/office.body?view=office-js#getasync-coerciontype--options--callback-) to verify the arguments that you use.
> 
> Try with:
> 
> ```
> Office.context.mailbox.item.body.getAsync(Office.CoercionType.Html, function (result) {
>     //bla bla bla  
>     console.log("test test test");  
> });
> ```
> The 1st parameter must be the [CoercionType enum](https://docs.microsoft.com/en-us/javascript/api/office/office.coerciontype?view=office-js).

really appreciate your reply. But it still doesn't work....

**Comment by exextoc** [comment]
Closing since the fix for the body.getAsync in Android issue was deployed in January per the comment above.

@SWei1234 if you still need help with the API on other platforms, please open a new issue. Thanks!

**Comment by I369697** [comment]
var body;
Office.context.mailbox.item.body.getAsync(Office.CoercionType.Text, function (result) {
    if (result.status !== Office.AsyncResultStatus.Succeeded) {
        body= result.error;
    } else {
        body= result.value;
    }
});

document.getElementById("item-body").innerHTML = "<b>Body:</b> <br/>" + body;

Why body empty at the first call, and have the result only in the second call?

**Comment by Oleg-O** [comment]
Ali, there is a bug in this code - on line 3, "asyncResult" is undefined, I believe you want to say "result" instead. Also, for any new inquiry it would be best to open a new issue on GitHub and include all the standard information about product platform and version, etc.

**Comment by I369697** [comment]
Ah, this error has been created when I copied the code and changed it, it's not the problem I am facing.
I have added the code here just because it's a related thing hoping to get a fast solution.

**Comment by Oleg-O** [comment]
ok if you are still having issues with body.getAsync API, please create a new GitHub issue and provide system, client version information and detailed repro steps and correct code, as usual. Thanks!
