### ISSUE TITLE
Hyperlinked Image in Word has weird behavior 

### ISSUE THREAD

**Issue by nhayeslucid** [OfficeDev/office-js#3261]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Inserting an image to Word with a hyperlink attached and clicking outside the image causes the hyperlink to be clicked

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Office on the web
* Operating System: Linux/MacOS/Windows
* Browser (if using Office on the web): Chrome, Firefox
 
## Expected behavior
When inserting an image to Word that has a hyperlink, you can click outside the image to unselect the image and start typing or whatnot.

## Current behavior
After inserting the image, if you click anywhere else (like on the right sidebar, outside of the document) it opens the hyperlink. Note that this is **ONLY** for images that have the maximum width of the document (we usually insert a larger image, then Word automatically resizes it to fit and then it causes the issue. Smaller images that don't get resized don't have this problem).

## Steps to reproduce

1. Insert a larger image on a new Word document (we use `insertInlinePictureFromBase64`, make sure that the image gets resized) and attach a hyperlink
2. Click outside the image (usually on the right sidebar, outside of the document, will trigger it)

## Link to live example(s)

1. Here is a GIST of an easy way to replicate the bug: https://gist.github.com/nhayeslucid/1797d9ca4599fab3fc5a757a826743c4

# Provide additional details

1. If the image is resized to be smaller, the bug no longer happens. It's only if it is the maximum size.

## Useful logs

![microsoft-image-bug](https://user-images.githubusercontent.com/103464945/228676496-989e0097-626a-44d8-b523-1f8f629a4e20.gif)

**Comment by penglongzhaochina** [comment]
Hi @nhayeslucid  I repro you issue. Thanks for your reporting. I have created a work item #7471112 to track it internally. I will let you know once we have some progress.
