### ISSUE TITLE
The setSignatureAsync method adds 1-2 empty lines before the signature

### ISSUE THREAD

**Issue by jacifkusto** [OfficeDev/office-js#3262]
We are developing an Outlook add-in for compose mode. In Outlook Online, Outlook Desktop for Mac and Outlook Desktop on Windows,  the setSignatureAsync method adds 1-2 empty lines before the signature. 

## Your Environment

* Platform: Office Desktop on Windows, Office on the web
* Host: Outlook
* Office version number: Outlook Desktop on Windows 2302 (Build 16130.20306), Outlook Desktop for Mac 16.70 (23021201)
* Operating System: macOS Ventura 13.2.1
* Browser (if using Office on the web): Chrome 111.0.5563.64
 
## Expected behavior
There are no empty lines before the signature after setting the signature using the setSignatureAsync method.

## Current behavior
In Outlook Desktop on Windows there is an empty line before the signature.
In Outlook Online  there are two empty lines before the signature.
There is no empty lines in Outlook for Mac, everything works as exprected.

## Steps to reproduce
Here is the code you can use to reproduce the issue:
` Office.context.mailbox.item.body.setSelectedDataAsync('<p>Regards,</p>', { coercionType: Office.CoercionType.Html }, (result) => {
          Office.context.mailbox.item.body.setSignatureAsync('FirstName LastName', { coercionType: Office.CoercionType.Html }, (result2) => {
          });
        });`

## Link to live example(s)
<img width="228" alt="Screenshot 2023-03-30 at 12 18 14" src="https://user-images.githubusercontent.com/44617947/228808766-55fe3afb-841c-4647-87c9-0c0a00d4f0a7.png">
<img width="226" alt="Screenshot 2023-03-30 at 12 27 11" src="https://user-images.githubusercontent.com/44617947/228808773-f500cd88-ed0e-4e07-b1d1-8e7f31c575ff.png">

**Comment by jacifkusto** [comment]
I'm still able to reproduce the issue. Is it already fixed?

**Comment by exextoc** [comment]
@jacifkusto In general, we want to have 2 empty lines before the signature in all versions of Outlook. Mac fixed it in 23021402 and Win32 and OWA already have it. 
I am not able to reproduce with the code you provided, I also tried with multiple version of Outlook, they all behalf as expected(inters 2 empty lines before the signature). I suggest you to update Outlook to latest version and try it again

**Comment by jacifkusto** [comment]
@exextoc Thank you! In my opinion, 2 empty lines before the signature are superfluous, 1 is enough. Could you please document this behavior so that we could point our users to that official document?
