### ISSUE TITLE
[Excel][Mac] Weird UI behaviour of a custom function's repeating argument

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#3263]
## Summary

On Mac, repeating arguments in the tooltip start appearing much earlier (as the user types in first several arguments) than on Windows, and they are not numbered.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.71
* Operating System: Mac Ventura
 
## Current behavior

![image](https://user-images.githubusercontent.com/5159662/228832045-121e6a9a-83bd-440e-9d78-54932cecacdc.png)

- Repeating arguments are not numbered.
- For unknown reason, additional un-numbered arguments start appearing much earlier than on Windows, while the user enters previous ones. On the screenshot above, the user is still typing one of the first arguments, **but already three repeating arguments appeared in the tooltip**.

Actual behaviour demo (zipped MP4): [Enter WRITEBACKBUDGET formula video.zip](https://github.com/OfficeDev/office-js/files/11111298/Enter.WRITEBACKBUDGET.formula.video.zip)

## Expected behavior

Behaviour should be like on Windows:

![image](https://user-images.githubusercontent.com/5159662/228830998-93b2f346-878c-4828-a3c2-32b14b4dfdff.png)

- The repeating arguments in the tooltip should be numbered: AmountPeriod1, AmountPeriod2...
- Additional repeating arguments should start appearing **only as soon as the user reaches the first of the repeating argument**. The additional arguments shouldn't start appearing while the user enters any of the previous arguments.

Expected behaviour demo (from Windows):

https://user-images.githubusercontent.com/5159662/228831342-5fee356b-f08c-495b-a6c2-1cf4642f123d.mov

## Steps to reproduce

You can use **Velixo** [add-in from the store](https://appsource.microsoft.com/en-us/product/office/wa200002311?tab=overview&exp=ubp8), and the custom function =WRITEBACKBUDGET() to replicate the behaviour.

## Context

We are trying to achieve consistency across platforms.

Not that in contrast to custom functions, for predefined functions on Mac the repeating arguments are numbered: 

![image](https://user-images.githubusercontent.com/5159662/228833489-1f329994-3b16-4a33-8dce-fba403faa482.png)

I could not find a good predefined function to compare the "early appearance" behaviour, but at least in MAXIFS the second instance of repeating argument does not show until you start typing the first one.

**Comment by XuanZhouMSFT** [comment]
Thanks for reporting this issue. After careful consideration, our team has decided to not fix this issue in the short term. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.

**Comment by wh1t3cAt1k** [comment]
@XuanZhouMSFT I understand this will not be fixed in the short term, but I don't feel it's a feature request, the behaviour sounds like a bug. 

Even if it's low priority, I would like to keep it open if possible, because we have an internal item too tracking the inconsistency between the legacy COM add-in and the Office.js behaviour.

Do you think we could keep this open for a while?
