### ISSUE TITLE
Attachment Reminder launches twice when using ItemSend add-in

### ISSUE THREAD

**Issue by abdumanas-plutoflume** [OfficeDev/office-js#3264]
# Provide required information needed to triage your issue
If the email contains an "attachment" keyword but no attachments, Outlook displays Attachment Reminder that the user may have forgotten to attach a file. If the user proceeds to not add attachment and then click on "Send anyway" the ItemSend add-in starts processing. But once the ItemSend add-in releases the email, Attachment Reminder is displayed again.

This seems to happen when sending Drafts or replying to emails but not when a new message is sent.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: version 2212  Build 16.0.15928.20278) 64-bit
* Operating System: Windows
* Browser (if using Office on the web): ______
 
## Expected behavior

Attachment Reminder should not launch again after the ItemSend add-in releases the email

## Current behavior

Attachment Reminder is launched again after the ItemSend add-in releases the email

## Steps to reproduce

1. Sideload an ItemSend add-in
2. Select a draft mail
3. Add "attachment" to the body but don't add any attachments.
4. Send the email
5. Attachment Reminder is displayed 
6. Click "Send anyways"
7. Add-in processes and releases the email
8. Attachment Reminder is displayed again

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Oleg-O** [comment]
We have fixed the bug and the fix should be available in build 16.0.16308.10000 or later. When an updated build is available depends on the release channel a customer is on.
[Outlook Add-ins Engineering Team]
