### ISSUE TITLE
How to find the manifest file of an added add-in in Excel Online

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#3265]
I would like to know, after adding an Excel add-in in Excel Online, whether it's possible to check its manifest file somewhere (e.g., in Dev Tools).

Thank you.

**Comment by grangeryy** [comment]
@chengtie is this for end user to find manifest for the inserted add-in or you want to check as add-in developer (owner of this add-in)?

**Comment by chengtie** [comment]
> @chengtie is this for end user to find manifest for the inserted add-in or you want to check as add-in developer (owner of this add-in)?

I'm asking the case where the end user wants to find the manifest for the inserted add-in.

**Comment by SiruiSun-MSFT** [comment]
@chengtie, if you want to get the manifest of an Add-in, maybe you should get its WA ID first. 

You can get this information through Dev Tool to catch entitlements in the file "EwaDSOpt.agave.js", which is shown as the picture below:
![image](https://user-images.githubusercontent.com/86719968/229731341-2733f267-2cf0-4c5e-ae5c-95fdb375c1d6.png)
Also, we have a simple way to get this detail in add-in store：
![image](https://user-images.githubusercontent.com/86719968/229731660-0a70890d-895f-4313-a74e-3ec6be524284.png)
The detail page's link contains the WA ID.
![image](https://user-images.githubusercontent.com/86719968/229731858-2b3c08c1-1403-4c09-8643-d0f326dad4c6.png)

After you get the WA ID, you can check its manifest through this link： https://store.office.com/app/download?assetid=WA104178141.

Hope the above information will be helpful! Thanks!

**Comment by chengtie** [comment]
> @chengtie, if you want to get the manifest of an Add-in, maybe you should get its WA ID first.
> 
> You can get this information through Dev Tool to catch entitlements in the file "EwaDSOpt.agave.js", which is shown as the picture below: ![image](https://user-images.githubusercontent.com/86719968/229731341-2733f267-2cf0-4c5e-ae5c-95fdb375c1d6.png) Also, we have a simple way to get this detail in add-in store： ![image](https://user-images.githubusercontent.com/86719968/229731660-0a70890d-895f-4313-a74e-3ec6be524284.png) The detail page's link contains the WA ID. ![image](https://user-images.githubusercontent.com/86719968/229731858-2b3c08c1-1403-4c09-8643-d0f326dad4c6.png)
> 
> After you get the WA ID, you can check its manifest through this link： https://store.office.com/app/download?assetid=WA104178141.
> 
> Hope the above information will be helpful! Thanks!

Great, it works, thank you.

**Comment by SiruiSun-MSFT** [comment]
Thanks! Will close this issue as is resolved!
