### ISSUE TITLE
Can't ctrl+click hyperlinked image on Desktop Word

### ISSUE THREAD

**Issue by nhayeslucid** [OfficeDev/office-js#3268]
When you have a selected image and then try to `ctrl+click` it to open the link, nothing happens. Hovering over the image when `ctrl` is held down shows the icon for opening a hyperlink, but once you click nothing happens.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop (possibly Mac too)
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2302 (16130.20332) ((this also happens on Word 2016))
* Operating System: Windows
* Browser (if using Office on the web): N/A
 
## Expected behavior

When `ctrl+click`ing on an already selected image, it should open the hyperlink.

## Current behavior

When `ctrl+click`ing on an already selected image, nothing happens.

## Steps to reproduce

1. Insert an image with a hyperlink
2. Select the image
3. Try `ctrl+click`ing on the image

## Link to live example(s)

1. Here is a gist of setting up the image insertion: https://gist.github.com/nhayeslucid/78f2779162a18ef39e2f3d6fd687fc06

# Provide additional details

1. Make sure you can normally `ctrl+click` on an image that you don't have selected. Once you do that, you can then select the image and then try again.

## Context

We're trying to create an addon that inserts images that have hyperlinks, but some customers are getting confused why they can't open a link. We have to tell them to unselect the image and try again.

## Useful logs

https://user-images.githubusercontent.com/103464945/229176449-c167905c-35fb-4cb5-aec1-33d1c810c03d.mp4

**Comment by penglongzhaochina** [comment]
Hi @nhayeslucid I not repro you issue in the word destop(version 2303 Build 16227.20204). It jumps to google when I ctrl+click the insert image. So could you please update your word and retry? Thanks.

**Comment by nhayeslucid** [comment]
Hi @penglongzhaochina, I tested this again in Word Desktop on version 2303 Build 16227.20212 and still ran into the same issue.

Keep in mind you first need to just click on the image (with a normal left click) and THEN try ctrl+click. So the whole process looks like this:
1. Insert an image using the script
2. Select the image by left clicking
3. Try to follow the hyperlink by holding down ctrl and then left clicking

You should be able to see this in the video attached above as well.

Let me know if you are still not seeing the issue.

**Comment by jipyua** [comment]
hi @nhayeslucid thanks for reaching out and I can reproduce the "problem". But actually this "issue" is not related to Word JavaScript API. If you manually insert an image in word and set a hyperlink to it, it also behaves the same. I am afraid this is so far a by-designed behavior of Word Desktop. If you do have strong feedback on this, feel free to send it to Word by clicking the "Help Improve Office" button at the upper right corner in a Word document. Thanks again.

**Comment by nhayeslucid** [comment]
Hi @jipyua! Thanks for letting me know the "issue" is by-design. I'll make sure to let my team know. Have a great day!
