### ISSUE TITLE
Word Add-in icon moves and opens blank task pane

### ISSUE THREAD

**Issue by mattblackdev** [OfficeDev/office-js#327]
Not sure if this is the appropriate place for this, please advise. [Also posted on stackoverflow.](https://stackoverflow.com/questions/53729975/office-js-word-add-in-how-to-manage-test-prod-versions-of-an-add-in-manifest)

## Summary
For some users, clicking our add-in icon on the ribbon will open a blank task pane. The icon appears to shift to the far right of the ribbon and clicking it again opens a second task pane that correctly loads the add-in, with the 1st still visible and still blank.

## Context
We suspect we are causing conflicts in the cache and are looking for advice on properly managing the manifests of a test version and a production version. So far, we have kept the 2 manifests exactly the same except for the URLs which point to different ports on a single server.

The users reporting this are mostly but not only our testers who had previously side-loaded the development version of the add-in manifest and have since installed the production version from the "ADMIN MANAGED" company store. 

## Reproduction
We can repeat the behaviour on a Windows machine that had also previously side-loaded the add-in. First, we close Word and delete the "wef" folder. This effectively removes the Company store installed add-in icon from the ribbon once Word is restarted. Then, install the add-in from the company store. Immediately in the currently opened document the add-in icon appears on the ribbon and when clicked will open a single correctly functioning task pane. However, once Word is restarted again the issue is back and the behavior described above occurs.

## Your Environment

* Platform: PC desktop
* Host: Word
* Office version number: Word version 1808 (Build 10730.20155 Click-to-Run)
* Operating System: Windows 10

### Add-in ribbon icon initial position
![add-in-ribbon-icon-initial-position](https://user-images.githubusercontent.com/5210361/49818903-034f5600-fd42-11e8-9d6c-bbe699d36720.png)

### First click, icon shifts right and opens blank task pane
![add-in-icon-shift-and-blank-task-pane](https://user-images.githubusercontent.com/5210361/49818927-0ea28180-fd42-11e8-93bf-6a3837484c05.png)

### 2nd click opens 2nd task pane and correctly loads add-in
![second-task-pane](https://user-images.githubusercontent.com/5210361/49818933-12360880-fd42-11e8-9626-387dfa5ec6bf.png)

**Comment by JuaneloJuanelo** [comment]
knwn issue tracked internally with   2737165

This is effectively an issue of having the same add-in installed from multiple (independent) add-in catalogs (i.e. centralized deploymeny and store and/or centralized deployment/file share etc.)
and yes this should only happen to the universe of users who are in such conditions. At the time of shipping the feature this was considered an edge case. we are analyzing telemetry to understand the frequency of this issue.
for now, we recommend you to avoid such conditions and advise your users to keep the manifest from Centralized deployment only.
Also make sure to not deploy this add-in to your dev team, on centralized deployment you can target specific users or groups to avoid such condition.

**Comment by mattblackdev** [comment]
@JuaneloJuanelo thanks! That is encouraging. Is there a known work around for the users who are already in this condition? We've tried deleting the "wef" folder.

**Comment by mattblackdev** [comment]
@JuaneloJuanelo we have sent a blast email to all our users asking them if they are experiencing this issue. So far we have 29 respondents who have never sideloaded and only installed through central deployment. 

Since this Issue is closed now and likely out of scope anyway, we'll start a premier ticket with Microsoft for support on this. However, I thought you might want to know, given this evidence, there may be a different root cause to this issue than having installed from multiple catalogs.

If you're willing to help us expedite, is there _any_ known workaround for this? We have tried deleting  related registry items and every bit of cache-like files we could find. Is there anything else we can try? We're wondering where else is Word or Office hanging on to these Add-Ins?

**Comment by JuaneloJuanelo** [comment]
@mattblackdev  i am re-opening the issue, based on your feedback, and sorry most of the team including me out on vacation. Can you please provide more details about your support case? what's the latest on this? is this still impacting your customers?

**Comment by mattblackdev** [comment]
@JuaneloJuanelo Thanks for re-opening!

Out of 134 original users emailed, 36 users responded. Of those 36, 35 have the issue and only one does not.
 
Those 36 are all on Windows. I cannot say whether they are on Win 7 or Win 10 but I would assume most are on Win 10.
 
Of those 35 with the problem, only 3 or 4 did a side-load before installing from the company store.

As for the premier ticket, I don't have info on it yet but I'll report back as soon as I do.

This issue is still occuring. In fact, as I was typing the above we received an email from a new user reporting the issue: 

> 
![image](https://user-images.githubusercontent.com/5210361/50909076-10bb3700-13f9-11e9-91a3-8477f8e9cc10.png)

**Comment by JuaneloJuanelo** [comment]
excellent we are opening an incident to help you fix this. 
i need more details from you (offline)
thanks!

**Comment by JuaneloJuanelo** [comment]
@mattblackdev  ping we need your help to repro the issue, can you please ping me? thanks! also it will be great to have the manifests and the link your add-in in the store...

**Comment by dmahugh** [comment]
Closing this issue because @JuaneloJuanelo has taken it offline to work on a fix. Thanks @mattblackdev for reporting the issue and providing so much information!

**Comment by mattblackdev** [comment]
@JuaneloJuanelo what's the latest on this?

**Comment by JuaneloJuanelo** [comment]
@mattblackdev  a fix was deployed late last week, can you give it a try now and see if the fix is applied? thanks!

**Comment by JuaneloJuanelo** [comment]
@mattblackdev  the fix was released! can you please update your clients and report back and confirm?
thanks!

**Comment by mattblackdev** [comment]
@JuaneloJuanelo we haven't seen our environment get the update yet, but we are checking every other day. Will report back ASAP.

**Comment by JuaneloJuanelo** [comment]
this issue is fixed now! (offline confirmation from @mattblackdev

**Comment by ogomez92** [comment]
We are getting blank task pane errors with our Add-in as well, so far more than 10 users.
