### ISSUE TITLE
Add-in with black icon cannot be seen in dark theme

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/office-js#3273]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Our add-in has a black icon, but when a user is in dark theme the icon cannot be seen as its black on dark gray.

What is the solution? Can we provide an alt icon for dark theme? If so, how?

**Comment by trigurl** [comment]
Hello, we currently do no have a way to allow for an alternate icon however that work is on our todo list - just that we don't currently have a timeline for this work at the moment.

Can you try having your icon with a transparent background as a work around for now?  Otherwise, having a white in the border or background as a temporary work around. 

Thanks Angela

**Comment by catmanjan** [comment]
@trigurl I tried adding a white outline to the icon but the problem is that the desktop version of Office is adjusting the color but the web one is not

These are the same icon:

![image](https://user-images.githubusercontent.com/137350/229963862-a3d312db-f7e1-4370-90dc-68c03a9e51a0.png)

**Comment by trigurl** [comment]
Is your background transparent?  I have this icon and when I go to dark mode on Win32 desktop it looks like this:

I created the icon using Paint 3D, updated the Canvas to use a transparent background then drew a black circle. 

![image](https://user-images.githubusercontent.com/62981524/230208052-3f069a64-8918-4dc4-84ff-a1e65016a44a.png)

**Comment by catmanjan** [comment]
@trigurl yes, we are seeing the same behaviour as you on the desktop, but office in the browser dark mode doesn’t have the same smarts built into it it seems?

**Comment by trigurl** [comment]
I just tried this on Word online and I get this (same icon)

![image](https://user-images.githubusercontent.com/62981524/230220800-82e0f02c-96d9-422c-8f08-0c161bda1468.png)

**Comment by trigurl** [comment]
Thanks Catmanjan, looks like Online behavior is different, we will need to add this to our investigation/bug list.
