### ISSUE TITLE
RichApi.Error: ItemNotFound in Office for Mac but works on the web when working with Range

### ISSUE THREAD

**Issue by jozefcipa** [OfficeDev/office-js#3275]
I have this code, which just simply listens for selection events and once a text is selected, it searches for `"foo"` and appends `"bar"` after it. 
The code works just fine in the browser but throws weird `RichApi.Error: ItemNotFound ` error in the Word.

```javascript
Word.run(async (context: Word.RequestContext) => {
      Office.context.document.addHandlerAsync(Office.EventType.DocumentSelectionChanged, content => {
        content.document.getSelectedDataAsync(Office.CoercionType.Text, async (result: Office.AsyncResult<string>) => {
          const selection = context.document.getSelection()

          const searchResult = selection.search('foo')
          searchResult.load('items')
          searchResult.track()
          await context.sync()

          console.log(searchResult.items)

          searchResult.items[0]?.insertText('bar', Word.InsertLocation.after)
          searchResult.untrack()
          await context.sync()
        })
      })
    })
```

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac / Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.71
* Operating System: macOS Ventura 13.0
* Browser (if using Office on the web): Chrome
 
## Expected behavior
It should append the text without problems.

## Current behavior
It fails with `ItemNotFound` error, it looks like if the Range was stale, or the reference is lost 🤔 

<img width="998" alt="image" src="https://user-images.githubusercontent.com/11503453/229764809-796833dd-7daf-41c0-9325-8c54166ba0c8.png">

**Comment by jozefcipa** [comment]
Any update on this @penglongzhaochina please?

**Comment by YijunMS** [comment]
I haven't figured out the root cause of this issue yet. However, there may be a way to unblock yourself:
```
 const searchResult = selection.search('foo');
 const result1 = searchResult.getFirstOrNullObject()
 if (result1) {
      result1.insertText('bar', Word.InsertLocation.after)
 }
 await context.sync()
```

The point is to avoid the context.sync before you insert text. I will update once I figure out why the original code doesn't work.

**Comment by jozefcipa** [comment]
@YijunMS Well the problem actually is that I need to get the content first, in order to perform an action on it, depending on the value. I just posted a simple demo to explain the situation, but basically what I really want to do is get the selected text, split it word by word, iterate through all the words (each word is a `Word.Range` instance) and if the condition applies, add some text before the specific word. That means I need to get the words first before proceeding, so `context.sync()` would be needed.
The problem is that these little word ranges are not working when I split the search result.

**Comment by xuruiyao-msft** [comment]
Hi @jozefcipa , I test the snippet code on Mac desktop.
There's no "ItemNotFound" error. The console log is empty array [] or a item list.
 But I find that searchResult.items[0]?.insertText('bar', Word.InsertLocation.after) in this snippet code cannot work and without 
throwing any error message.

**Comment by xuruiyao-msft** [comment]
@jozefcipa Thanks for reporting this issue. After adding the catch clause I can reproduce this issue. We've created work item 7806060 to track it. Once there's any progress, we'll sync with you.

**Comment by jipyua** [comment]
hi, I think your writing is not that correct, especially it mixed the common API and rich api context. I think the following way will make it both work for Mac and online. please have a try. Thanks. (note that I didn't use the insertText method as it will change selection and repeatly call insertText() )

async function addEvent() {
  Office.context.document.addHandlerAsync(Office.EventType.DocumentSelectionChanged, myHandler);
}
async function myHandler() {
  Word.run(async (context: Word.RequestContext) => {
    const selection = context.document.getSelection();
    const searchResult = selection.search("foo");
    searchResult.load("items");
    await context.sync();
    console.log(searchResult.items.length);
    searchResult.items[0]?.select();//insertText('bar', Word.InsertLocation.after);
    await context.sync();
  });
}
