### ISSUE TITLE
🔥🐛 Excel for Mac: "error installing functions" only when add-in is deployed centrally

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#3277]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac OS Ventura 13.2.1 (22D68)
* Host [Excel, Word, PowerPoint, etc.]: Excel for Mac
* Office version number: 16.71 
 
## Expected behavior

The add-in successfully installs the custom functions when deployed centrally.

## Current behavior

<img width="237" alt="image" src="https://user-images.githubusercontent.com/5159662/229798535-1453c2d7-05ba-4288-816c-bbb52bd2a8a7.png">

The function =ACCOUNTNAME() is not available in the pop-up.

## Steps to reproduce

1. Install the Velixo add-in **directly** from the store in the Insert -> Addins menu (without centralised deployment).
2. Observe the function is **available** in the dropdown.
3. Remove the add-in, CTRL+Q quit Excel.
4. In the admin center, deploy add-in **using the "from the store"** option, and select "just for me":
5. Open Microsoft Excel, refresh add-ins, try to insert:

<img width="566" alt="image" src="https://user-images.githubusercontent.com/5159662/229799701-31681644-1d95-4647-859a-83cb427a4297.png">

6. Try typing =ACCOUNTNAME, the function is not there.

## Context

The issue may become a showstopper for people using centralised deployment.

Device ID: 64832662-F890-5BD5-A5D4-4054B80A8331

cc @Wenjun-Gong @gmichaud

[Internal Velixo tracking item](https://3.basecamp.com/3496385/buckets/16689259/card_tables/cards/7160318676)

**Comment by wh1t3cAt1k** [comment]
@Wenjun-Gong @penglongzhaochina any news on this? IMO it's a pretty bad issue which deserves prompt action...

**Comment by wh1t3cAt1k** [comment]
Hi, has there been an update on this? It's been over a month.

**Comment by zhenhuangMSFT** [comment]
Sorry for missing out. This is definitely not right. May I ask if the issue still persists?

**Comment by wh1t3cAt1k** [comment]
Cannot be replicated with central deployment "just for me" and Excel for Mac version 16.82.

Thank you, I believe it has been fixed somewhere along the way.
