### ISSUE TITLE
[Add-In Outlook] Fetch request inside OnAppointmentSend event

### ISSUE THREAD

**Issue by FloV22** [OfficeDev/office-js#3278]
# Provide required information needed to triage your issue

## Your Environment

* Windows
 
## Expected behavior
**OnAppointmentSend** event is triggered and fetch request on another domain succeed

## Current behavior
When making a fetch request in the event onAppointmentSend, the request fails.
It is the only case where this request fails. The same request when triggered by a user action works fine.

## Steps to reproduce
1. Define a manifest with a LaunchEvent on AppointmentSend
`<LaunchEvent Type="OnAppointmentSend" FunctionName="onSendMeeting"/>`
2. Define in the manifest a Js file which will be executed
 `<bt:Url id="JSRuntime.Url" DefaultValue="https://local.r2d2.bzh:3000/add-in/8080/dist/index/bundle-windows.js" />`
3. In the js file try to make a fetch request located on another domain (the fetch request answers with the correct CORS headers)
4. the fetch request fails, the server does not have any informations.

# Provide additional details

1. The fetch request works in the outlook web
2. The same fetch request works when executing inside an "Action" like below
```xml
         <Action xsi:type="ExecuteFunction">
            <FunctionName>createMeeting</FunctionName>
        </Action>

```
3. The request works also well on the same domain.

## Context
We would like to notify our server that all change has been done in the current meeting by using the onAppointmentSend event. And we want to give our customer the possibility to select the desire server in a dropdown. The add-in is located on a server and we want to post informations to another server when the customer has made all his actions.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Adrian-MSFT** [comment]
Hi @FloV22 -
For security reasons, fetch requests to another domain require a well-known resource to be setup. This is the same resource used for SSO.
Instructions are here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/use-sso-in-event-based-activation#list-allowed-add-ins-with-a-well-known-uri

I will get the documentation clarified for this.

**Comment by FloV22** [comment]
Thank you for your feedback.

I have created a .well-known folder at the root of the domain I try to fetch. However I still have the issue.
Where should I put the _microsoft-officeaddins-allowed.json_. Is it at the root of the server where my add-in is hosted or is it at the root of the server that i try to fetch ?

**Comment by Adrian-MSFT** [comment]
Hi @FloV22, The location you specified seems correct. Do you have the Domain added to AppDomains element in your manifest file? https://learn.microsoft.com/en-us/javascript/api/manifest/appdomains?view=powerpoint-js-preview

If that doesn't succeed, can you switch to using XMLHttpRequest to get more useful error messages?

**Comment by FloV22** [comment]
Yes the AppDomains element contains the correct configuration of the domains.

When switching to XMLHttpRequest I get the following error message: "The request does not meet conditions for security policy of SOP (same-origin policy) or simple CORS (cross-origin resource sharing)"

We have the following headers returned for CORS:

- Access-Control-Allow-Origin: *domain-name*
- Access-Control-Allow-Credentials: true
- Access-Control-Allow-Headers: Authorization, Content-Type, Accept, Accept-Encoding, Accept-Language, Connection, Host, Referer, Origin, User-Agent, Cache-Control, Keep-Alive, X-Requested-With, If-Modified-Since, X-keycloak-realm, X-visitor-secret
- Access-Control-Expose-Headers: Request-Id, X-Metadata-Id, X-Applied-Filters, X-Metadata-Tags, X-metadata-matched-count, X-metadata-matched-ids

Is there something missing ? This CORS headers works well on all our use-case. Is there something specific for outlook add-ins ?
And I also have deployed the microsoft-officeaddins-allowed.json file in the well-known of the server.

**Comment by Adrian-MSFT** [comment]
> Hi @FloV22, The location you specified seems correct. Do you have the Domain added to AppDomains element in your manifest file? https://learn.microsoft.com/en-us/javascript/api/manifest/appdomains?view=powerpoint-js-preview
> 
> If that doesn't succeed, can you switch to using XMLHttpRequest to get more useful error messages?

Hi @FloV22, apologies, I misspoke in my earlier message - The correct location for your microsoft-officeaddins-allowed.json file is NOT the root of server you are trying to fetch. The location for this should be: (add-in server root)/.well-known/microsoft-officeaddins-allowed.json

**Comment by FloV22** [comment]
It now works. Thank you for your feedback.
It will be better if you can update the documentation with the previous informations.

**Comment by ilbrando** [comment]
@FloV22 I'm struggling to make a fetch or XMLHttpRequest work from my event activated handler on Windows. I can make the handler code run, but when I make an async call (like fetch().then(...) or XMLHttpRequest send with onreadystatechange event handler set) it appears that my code terminates at once and the request is not made - let alone waiting for the response - and no exceptions is thrown (at least not cached) and I never get to calling event.completed.
Can you please share how you make a request in your code?
PS I have no trouble making it work in Outlook for web.

**Comment by FloV22** [comment]
I used the same code in windows and in the browser. However in order to make the request works you have to host a file located in a well-known folder at the root of your add-in server.

```
example: htttps://<domain>/.well-kown/microsoft-officeaddins-allowed.json

Response:
{
  allowed: [
    "https://<domain>/<path-to-js-file-use-by-windows-add-in>"
  ]
}
```

While the microsoft-officeaddins-allowed.json file is not hosted at this specific location and with this name, requests will fail and the error message is not really relevant...

**Comment by ilbrando** [comment]
Thank you
I have also these settings, but the call to fetch has no effect. I don't see it in my backend and no errors are thrown. At that point in my code I only (as a test) call event.completed with allowEvent: false and an errorMessage, yet still the mail is send and the message is not shown. 
I should say my use case is OnMessageSend with SendMode="Block".

I know async/await is not supposed to work, so I have tried with fetch().then().catch() and also with new XMLHttpRequest and onreadystatechange event handler.
How do you call the backend?
