### ISSUE TITLE
Add-in description not showing?

### ISSUE THREAD

**Issue by neptunel** [OfficeDev/office-js#3281]
**Question**
I'm trying to create an email add-in on Outlook. When a user creates a New Event, add-in should populate the meeting location with the meeting link and add a body to the email for join settings. Just like Zoom and BlueJeans add-ins. I'm following [this tutorial ](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting?tabs=non-mobile) exactly. When I create an  Outlook add-in following [quick start](https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial) and using Yeoman, I'm able to start and use the add-in from my localhost. However, when I tried the same thing and exactly followed the [tutorial](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting?tabs=non-mobile) , I'm getting this error in Desktop App:
<img width="1184" alt="Screenshot 2023-04-04 at 6 28 39 PM" src="https://user-images.githubusercontent.com/63646687/229958304-794fcc41-e824-4752-ac51-f91b98f75ff5.png">
On Web, Add-in takes a bit to load and gives the error below:
![Screenshot 2023-04-04 at 6 31 42 PM](https://user-images.githubusercontent.com/63646687/229958425-f0ba3378-b784-497a-a7d7-a91b0ac1c6e3.png)
When I tried to get to the localhost:3000 I'm not able to get any resource on the browser:
![Screenshot 2023-04-04 at 6 34 34 PM](https://user-images.githubusercontent.com/63646687/229958672-abb3da85-dfed-47ca-9883-a07f0c89408f.png)

Also, `npm run start` doesn't work for me it gives this error:
<img width="545" alt="Screenshot 2023-04-04 at 6 36 15 PM" src="https://user-images.githubusercontent.com/63646687/229958790-69fc4a42-5d96-40ab-b9a8-525226d1d691.png">

That's why I'm using `npm run dev-server` to start my add-in. How can I fix this issue? Please help! 
Thank you!

**Comment by neptunel** [comment]
Hi @exextoc, @AlexJerabek, is this a MacOS-related problem? I didn't see this error message in the [docs](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting). Does localhost need to be accessible when I run `npm run dev-server`?

**Comment by exextoc** [comment]
We are not able to repro the issue at our end. Can you please share the test Add-in created? Also, can you please confirm if you have updated the manifest URL's to point to localhost instead of contoso.

**Comment by neptunel** [comment]
I updated the localhost in manifest instead of Contoso, the issue occurs when I try [ this tutorial ](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting?tabs=non-mobile), it updates the event body in Web but not in the Desktop. Do you know why it happens? And this is the [code](https://github.com/neptunel/OutlookPlugin/tree/main) I'm using. Thanks.

**Comment by neptunel** [comment]
For more context, this is how it looks when I run the add-in in the desktop app (Mac x86, it doesn't load forever, like it used to but instead it doesn't  populate the event body either):

https://user-images.githubusercontent.com/63646687/231900948-f3502ace-eb42-4dd5-b8b4-9b482a694e1e.mov

VS in the web client (it works successfully):

https://user-images.githubusercontent.com/63646687/231901114-827db604-8850-4a42-9beb-b893f36ec44f.mov

Do you know why this is happening? Is there a tool that I can debug which parts give errors in the desktop app?

**Comment by neptunel** [comment]
Hi again, I was able to solve the previous problem. I think for desktop app, after each update I need to remove and reload the add-in. This time, I'm having another problem even though I added a description in my `manifest.xml` like:
`<Description DefaultValue="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."/>` with less than 260 characters (this is the max character limit when I run the `npm run validate` I've first gotten an error about exceeding the limit.), I can install and use my add-in successfully however I can't see the description of  the add-in either in the desktop or web. How can I fix this problem?

<img width="679" alt="Screenshot 2023-04-16 at 4 21 13 PM" src="https://user-images.githubusercontent.com/63646687/232349090-4f04d749-e0a0-4aba-b5ae-0a4f02336ab2.png">

**Comment by exextoc** [comment]
Hey @neptunel 

We are not able to reproduce the issue from our end. 
Can you please help us with a sample add-in, where you see the behavior ?
Also, does it not come for your add-in or for all side-loaded add-ins?

**Comment by neptunel** [comment]
Hello, 
I wasn't able to see the Description for each sample add-in I created, either running on localhost or deployed. For instance, I'm using [this URL](https://dolbyio-outlook-add-in.netlify.app/) to install the add-in in my workspace and I'm not able see the description as in the screenshot in my previous comment. I tried to add other custom add-ins via URL, and I can see the description for them. But Dolby.io Video Call and My Office Add-in are the ones I created using Yeoman, I shared the manifest.xml for Dolby.io Video Call. I can't see the description in any of them. Why do you think this is happening?
<img width="744" alt="Screenshot 2023-04-18 at 2 28 06 PM" src="https://user-images.githubusercontent.com/63646687/232909284-52035c7d-baf5-4806-8aed-012764725129.png">

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding the description field. It has been put on our backlog. We, unfortunately, have no timelines to share at this point

Internal tracking id: 204188

**Comment by exextoc** [comment]
Hi @neptunel 
Upon checking the manifest file, we could confirm that the description you have set in the base manifest is being overriden by the version overrides after that.

The line **Description resid="residDescription"** is present in the versionOverrides node. The **residDescription** value needs to be present in the **LongStrings** while it is currently present in the **ShortStrings** node. Kindly add it in the **LongStrings** node to make it work.

Or, if you don't want the description to be overwritten by the version overrides, remove the line **Description resid="residDescription"** from the VersionOverrides node and the description in the base manifest will start to show up.
