### ISSUE TITLE
Word Online: body.paragraps collection doesn't update

### ISSUE THREAD

**Issue by vasily-z** [OfficeDev/office-js#3284]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When using Word JS API to insert some new paragraphs in Word Online, `body.paragraphs` collection does not update after `context.sync()` calls. So it is not possible to get references to new paragraphs through `body.paragraphs` collection.

## Your Environment

* Platform: Office on the web
* Host:  Word
* Office version number: 16.0.16403.41005
* Operating System: Windows 11
* Browser (if using Office on the web): Edge 111.0.1661.62 
 
## Expected behavior
It is expected that each time after `context.sync()` all paragraphs from the document could be obtained from `body.paragraphs` collection. This way it works in Word desktop.

## Current behavior

Currently in Word online always returns initial paragraph's collection within `Word.run(...)`. Calls of `context.sync()` update other Word objects, but not the paragraphs collection.

## Steps to reproduce
Here is the code to reproduce the issue.
```javascript
async function run() {
  await Word.run(async (context) => {
    var pars = context.document.body.paragraphs.load("items");
    await context.sync();
    // Returns "1", as the document has only one empty paragraph
    console.log(pars.items.length);
    // Insert three new paragraphs. Now there are 4 in the document
    ["Cat", "Dog", "Mouse"].forEach(p => context.document.body.insertParagraph(p,"End"));
    
    pars = context.document.body.paragraphs.load("items");
    await context.sync();
    //But I still get 1 in the console window!
    console.log(pars.items.length);
    //New paragraphs are unchanged when we iterate over them
    pars.items.forEach(p => p.set({lineSpacing: 40, leftIndent: 10 }))
    await context.sync();
  })
}
```

## Link to live example(s)

[ScriptLab gist](https://gist.github.com/vasily-z/7039918a65fc52fe5d8b2df1160b6f7d)

**Comment by xiaoyuMS** [comment]
@vasily-z Thanks for reporting this.

It is a known issue that the behavior of collection objects is different between platforms. We have created VSTO #7780057 for internal tracking.

Now on Word Online, we need to get the paragraph collection from the body again to synchronize the latest status.
