### ISSUE TITLE
OWA Add-in ribbon menu is hidden behind Apps menu

### ISSUE THREAD

**Issue by tallen1114** [OfficeDev/office-js#3285]
# Provide required information needed to triage your issue
When clicking on an Add-in from the Apps list, the menu pops up behind the Apps list. Sometimes it's entirely hidden behind and users can't interact with it at all. Sometimes it's partially visible, but users cannot read the whole title for each option. This is happening for our Add-in as well as others that use a similar menu.
<img width="544" alt="Screenshot 2023-04-06 at 3 33 04 PM" src="https://user-images.githubusercontent.com/46459359/230481500-ecddacb1-6260-48a5-8d7e-ec8e79daeffe.png">

Not just our add-in:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/46459359/230482185-2e2e4e7c-98da-4cb9-953b-e46625a43fab.png">

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.71.2 (23032500)
* Operating System: Mac and PC
* Browser (if using Office on the web): Edge, Chrome, and Safari
 
## Expected behavior

The menu should pop up in front of the Apps list so you can actually interact with it

## Current behavior

The menu pops up behind the Apps list and is either partially or completely hidden

## Steps to reproduce

1. Click on the "Apps" item in the ribbon
2. Click on the Yesware Add-in (or any add-in that loads a menu upon clicking the add-in, such as Jira for Outlook)
3. Try to interact with the menu

## Context

Some users can work around this issue by adding the add-in under "Message Surface" in "Customize actions" so that they can access it directly without going through the Apps button. But not all users have the ability to customize that, so they are unable to use the add-in efficiently.

**Comment by exextoc** [comment]
Thank you for reporting the issue. We are able to repro it and are working on fixing this . We will get back with timelines once we have more details.

**Comment by exextoc** [comment]
@tallen1114 We have fixed the bug and the fix should be available now. Thanks for your patience.

**Comment by tallen1114** [comment]
Thank you! This is working for us now 🎉
