### ISSUE TITLE
Outlook does not load any addins in certain circumstances

### ISSUE THREAD

**Issue by Suntechnick** [OfficeDev/office-js#3289]
Steps to reproduce:
1. On Windows, open the Outlook Desktop and install any addin which can be used on the compose screen (e.g., Polls by Microsoft addin)
2. Close the Outlook Desktop
3. In File Explorer, on any suitable file do Right Click -> Send to -> Mail recipient
4. Outlook opens a compose screen which doesn't load installed addins

Is that intentional or is it a bug? I was unable to find any information for this workflow.

**Comment by ztcdsb** [comment]
Hi @Suntechnick 
Thanks for reporting the issue. It has been put on our backlog. We unfortunately have no timelines to share at this point
Internal tracking id: Office: [3543374]
