### ISSUE TITLE
[Word] Expose TrackRevision via API

### ISSUE THREAD

**Issue by rvanlaak** [OfficeDev/office-js#329]
## Expected Behavior

Allow reading and modifying the `Document.TrackRevisions` setting.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.office.interop.word._document.trackrevisions?redirectedfrom=MSDN&view=word-pia#Microsoft_Office_Interop_Word__Document_TrackRevisions

## Current Behavior

TrackRevision status (and related) is unaccessible and can not be changed.

## Context

Without being able to (temporary) disable track revisions, replacing/updating OOXML (e.g. for adding comment on selection) will always mark the whole text as a new revision.

Without this setting being accessible we also can not warn our users that they should enable it.

### Scenario

* open document, enable track changes
* select text, and run code that puts a comment on text (e.g. using scriptlab)
* text that itself has not been changed is seen as revision

In normal version of Word this scenario does not mark the selection as revision.

## Your Environment
* Platform: All
* Host: Word
* Office version number: 365
* Operating System: Windows
* Browser (if using Office Online): N/A

## Useful logs

![image](https://user-images.githubusercontent.com/2707563/49865017-13c80500-fe04-11e8-9b93-340dcd7f4283.png)

**Comment by JuaneloJuanelo** [comment]
this is a known issue, currently tracked in our backlog. No solid ETA as of now. On top of this the feature is still not available in Word Online.

please up vote this one in our user voice channel https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/13649829-add-change-tracking-api

**Comment by rvanlaak** [comment]
Hi @JuaneloJuanelo can you elaborate on this a bit more? We would actually mark this as a bug.

Aside of the setting being accessible, when modifying the OOXML directly this should not add a track-change, as we did not add a revision to the OOXML. 

The result is that the exact same text is seen as removed and then inserted again.

Best would be to have a parameter/option for the call to not let Word mark it as a revision.

**Comment by rvanlaak** [comment]
To be clear about what behavior is meant: using [`Office.context.document.setSelectedDataAsync`](https://docs.microsoft.com/en-us/javascript/api/office/office.document?view=office-js#setselecteddataasync-data--options--callback-) adds a track-change when the selected text itself was not modified.

@JuaneloJuanelo although solely working with the text selection OOXML (using `getSelectedDataAsync`) is preferred, we are exploring the option to use the `Office.context.document.getFileAsync` to modify the content of the whole file instead.

The question is; will writing the whole file also add a track-change `w:ins` and `w:del`? If so, that method also would not solve this unwanted behavior.

**Comment by rvanlaak** [comment]
@JuaneloJuanelo `getFileAsync` does not have a setter `setFileAsync` counterpart. How can we write Word files? 

We want to disable the "track changes" setting, run our command, and restore the "track changes" setting. So more specific; how can we write the `word/settings.xml` file?

/cc @danielgwilson

**Comment by rvanlaak** [comment]
@JuaneloJuanelo @danielgwilson @kbrandl

Some help would be appreciated. No updates are getting posted on Uservoice:

* https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/13496982-create-word-comments-via-office-api
* https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/15055839-wrapping-ooxml-apis-needed-insertcomment-insert

**Comment by serjant** [comment]
Likewise when I set `w:trackRevisions` tag with `w:val="true"` in the `settings.xml` part of the OOXML you still omit and drop this tag - I have checked it via Script Lab. That does not make sense at all

**Comment by paolocaminiti** [comment]
Any update?

We need tracking changes apis as well. For us is impossible to port native plugins in full to 365 without this.

Also all uservoice links are invalid now. Is this being "tracked" anywhere else?
