### ISSUE TITLE
Unable to open add-ins for excel and outlook at the same time

### ISSUE THREAD

**Issue by ramakrishna0505** [OfficeDev/office-js#3292]
We have a customer reporting issue saying they are unable to use our excel and outlook add-ins at the same time. We are seeing an error saying "The add-in could not be started. Please restart all Office applications and try again."
When the add-ins are loaded individually they work as expected. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows 10 (Version 10.0.19044)
* Host [Excel, Word, PowerPoint, etc.]: Excel (16.0.16130.20186), Outlook (16.0.16227.20202)
 
## Expected behavior

Both add-ins should work at the same time.

## Current behavior

Only one add-in loads properly at a time.

## Steps to reproduce

1. Open Excel, load "CloudExtend Analytics for NetSuite"
2. Open Outlook, load "CloudExtend Outlook for NetSuite"

**Comment by ruijiaMS** [comment]
Hi @ramakrishna0505,
Thanks for letting us know this issue! Could you please help your customer to check if he ever switched language?
After switch language, all office apps need to be restarted to use add-ins.

**Comment by ramakrishna0505** [comment]
> Hi @ramakrishna0505, Thanks for letting us know this issue! Could you please help your customer to check if he ever switched language? After switch language, all office apps need to be restarted to use add-ins.

Thanks for the response @ruijiaMS. Our customer has not switched languages. Please let us know if you need further information.

**Comment by ruijiaMS** [comment]
Hi @ramakrishna0505,
We can not repro this issue both for latest production and given version locally. Is this issue stably repro in your customer side? like after restarting. And can they please provide a repro video which can help us know the exact scenario. It will be great helpful for us if having more information.

**Comment by ramakrishna0505** [comment]
Hi @ruijiaMS We will ask our customer to restart and check if it is still reproducible. Is there an email to which we can forward the video?

**Comment by ruijiaMS** [comment]
Hi @ramakrishna0505,
Thanks for your help!
You can publish the repro video on any open website where we can visit, like YouTube, I think.

**Comment by Oleg-O** [comment]
I am from Windows Outlook Add-ins side, and I am also unable to reproduce this issue. It's surprising that it does not work at the same time and is expected to work. Yes, a video would be helpful, especially if it can include both working and non-working case.

**Comment by ramakrishna0505** [comment]
Hi @ruijiaMS Unfortunately the recording may contain customer senstive information hence it is not possible for us to publish on any open website. Could you please provide us with an email id so that we can send it ?

Also, just a general update. This issue is not specific to only our add-ins, it happens to all add-ins for our customer.

**Comment by ruijiaMS** [comment]
Hi @ramakrishna0505 
Sorry for the delay here. Can you provide your recording via the Feedback, which is an official way, in Excel? And please add a keyword specific like "CloudExtendForNetSuite" into the title to easy track.
https://support.microsoft.com/en-us/office/how-do-i-give-feedback-on-microsoft-365-2b102d44-b43f-4dd2-9ff4-23cf144cfb11

**Comment by ramakrishna0505** [comment]
Hello @JinghuiMS @ruijiaMS I was unable to upload a recording in the feedback link provided. However I have given feedback as suggested. Here is the link `https://feedbackportal.microsoft.com/feedback/idea/f15a9a01-d0b9-4526-521e-639c0855a001?isPrivate=true`

**Comment by ramakrishna0505** [comment]
Hello, any update on this? @JinghuiMS @ruijiaMS

**Comment by ruijiaMS** [comment]
@ramakrishna0505 I can not open this link, is there any other available way for you to upload the repro video?

**Comment by ruijiaMS** [comment]
Hi @ramakrishna0505 
thanks for your recording, and we have raised an internal bug #8005303 to investigate this issue, any update will be post here!

**Comment by ramakrishna0505** [comment]
Hi @ruijiaMS , can I get an update for the bug please?

**Comment by ramakrishna0505** [comment]
Hi @ruijiaMS could we please get an update?

**Comment by ruijiaMS** [comment]
@ramakrishna0505 The team will review this work item in our backlog regularly.  They unfortunately have no timelines to share at this point. I will post it here if there is any update

**Comment by ramakrishna0505** [comment]
Hi @ruijiaMS @JinghuiMS could we please get an update?

**Comment by SiruiSun-MSFT** [comment]
Hi @ramakrishna0505, I'm sorry that you are still blocked by this issue. To help us re-prioritize this bug, we want to check some details with you. 

Could you provide us with the scale of affected users? Or it is hit by only one customer?  Also, we would like to know the frequency of this issue happening. And does this error occur on every add-in installed?

Meanwhile, the video may not be enough to help us investigate this bug. Could you give us a file or steps to repro this situation? So that we could debug deeply to find the root cause.

Thanks for your patience!

**Comment by ramakrishna0505** [comment]
Hi @SiruiSun-MSFT at present we have 2 affected users and the issue is consistent, happens every time. We tried to open non CloudExtend apps, one in Outlook and other in Excel and are able to repro this issue.

Steps:
1. Open Outlook and load any add-in (add-in loads fine).
2. Open Excel and load any add-in (add-in does not load, shows error instead).
3. Repeat steps 1 & 2 vice-versa i.e, Open Excel and load any add-in then Open Outlook and load any add-in (able to repro the issue in this case as well).

However, when we tried to open "CloudExtend Outlook for NetSuite" and a non CloudExtend app in Outlook itself, both apps loaded fine. 

Please let me know if any further information is needed.

**Comment by SiruiSun-MSFT** [comment]
Hi @ramakrishna0505, I've tried the steps you shared above. However, I still cannot repro the issue you reported. I would like to know whether the steps can help us repro on everyone's environment. If it is only for the two users' machines, this may be not enough for us to find the root cause.

**Comment by ramakrishna0505** [comment]
Closing this as customer's issue is now resolved after reinstalling Office apps. Thank you for your help @SiruiSun-MSFT @ruijiaMS @Oleg-O
