### ISSUE TITLE
Outlook: Implement MailItem.Send()

### ISSUE THREAD

**Issue by jorgk3** [OfficeDev/office-js#3294]
We've posted this to the Microsoft 365 Developer Platform Ideas Forum [here](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/implement-mailitem-send/idi-p/3772625), but it's unclear whether suggestions made there are actually considered.

So repeating the request here briefly:
We're trying to port our Outlook COM/VSTO add-in to the Outlook JS API. Our add-in currently uses MailItem.Send() to send an e-mail message. Unless we've missed something, there is no Outlook JS API to send messages. Please consider implementing one.

**Comment by eugene-plutoflume** [comment]
Consider using MS Graph or EWS for such tasks. The JavaScript API doesn't provide all the features available for COM add-ins, but you may implement most of the things using EWS or Graph API.

**Comment by jorgk3** [comment]
Thanks for the comment. Some other tickets in this repo talk about the REST API, but that's going to be deprecated. Since support for COM add-ins is eventually going to be dropped, we're looking to port our rather large COM add-in to something else. The JS API appears to be attractive since it will cover OL desktop and OL web. So how does MS Graph or EWS integrate with the new add-in JS API? Any pointers to documentation, worked examples, etc. would be greatly appreciated.

EDIT: OK, https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/?view=powerpoint-js-preview has a link called "Use Microsoft Graph to extend your add-in's capabilities", but that appears to by a misnomer since it simply directs to https://learn.microsoft.com/en-us/graph/overview with no hint to add-in integration. As I see it, EWS, MS Graph, OWA, ActiveSync, MAPI, etc. are all protocols to talk to an Exchange server, but I didn't see a hint as to how the JS API supports them. Please excuse the ignorance.

EDIT 2: OK, here it is: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/web-services. SendItem is supported. The funny thing is the text at https://github.com/davecra/easyEWS (quote): "Microsoft official guidance at this point is to no longer use EWS, but rather to use the REST API's". Right now, it's the opposite, REST will be deprecated and EWS is the go again.

**Comment by exextoc** [comment]
Currently the feature you requested, is not supported. Feature requests on [Tech Community](https://aka.ms/M365dev-suggestions) are considered, when we go through our planning process. We will let you know when we have a timeline to share for this. Thank you.

**Comment by jorgk3** [comment]
Thank you for the answer. I guess the requested feature can be achieved via EWS as suggested earlier on.

**Comment by slabereemsft** [comment]
Closing since this is a feature request which was redirected and a workaround was provided.

**Comment by jorgk3** [comment]
We managed to implement sending using EWS, however, we'd also like to remove the currently compose message from the the UI since sending already happened via EWS. Can that be done? Also see https://github.com/OfficeDev/office-js/issues/3295#issuecomment-1516721178.

EDIT: OK, you can `save(Async)/close` the mail item, that will pull it down from the UI. Maybe delete the saved draft later with EWS.

**Comment by jorgk3** [comment]
Using EWS (and implementing deleting the unwanted saved draft with the REST API since EWS can't delete) ran into a 1 MB sending limit:
https://github.com/OfficeDev/office-js/issues/3490
