### ISSUE TITLE
Outlook: JS API to control the MIME structure of a message being sent

### ISSUE THREAD

**Issue by jorgk3** [OfficeDev/office-js#3295]
We've posted this to the Microsoft 365 Developer Platform Ideas Forum [here](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/implement-outlook-js-api-to-control-the-mime-structure-of-a/idi-p/3772645), but it's unclear whether suggestions made there are actually considered.

So repeating the request here briefly:
We're trying to port our Outlook COM/VSTO add-in to the Outlook JS API. Our add-on currently creates S/MIME messages and takes advantage of the fact that MAPI properties of MailItem can be set, for example MapiProperty.PidTagMessageClass can be set to "IPM.Note.SMIME.MultipartSigned".
There are APIs to set body and attachments of an item (body.getAsync, body.setAsync, addFileAttachmentFromBase64Async, removeAttachmentAsync), but there doesn't appear to be APIs to manipulate the MIME structure of a message.

More details and related requests at the [forum link](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/implement-outlook-js-api-to-control-the-mime-structure-of-a/idi-p/3772645) mentioned above.

**Comment by exextoc** [comment]
Currently the feature you requested, is not supported. Feature requests on [Tech Community](https://aka.ms/M365dev-suggestions) are considered, when we go through our planning process. We will let you know when we have a timeline to share for this. Thank you.

**Comment by jorgk3** [comment]
Thank you for the answer. I guess the requested feature (or similar) can be achieved via EWS as suggested in https://github.com/OfficeDev/office-js/issues/3294.

**Comment by jorgk3** [comment]
> Thank you for the answer. I guess the requested feature (or similar) can be achieved via EWS as suggested in #3294.

So since there is no API to modify the overall MIME structure of the mail item, we followed the the ["on send" feature](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=windows) to suppress sending the message altogether (`event.completed({ allowEvent: false });`) and we send one in the desired format using EWS. However, the in the user interface, the "draft message" remains open.

Do you have any suggestion on how to remove the message currently being composed from the UI? @eugene-plutoflume ?

EDIT: OK, you can `save(Async)/close` the mail item, that will pull it down from the UI. Maybe delete the saved draft later with EWS.
