### ISSUE TITLE
getCallbackTokenAsync throws Error

### ISSUE THREAD

**Issue by JGrant-Mastrin** [OfficeDev/office-js#3299]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac iOS
* Host [Excel, Word, PowerPoint, etc.]: Outlook for Mac (new UI)
* Office version number: 16.72
* Operating System: macOS
* Browser (if using Office on the web): N/A

 
## Expected behavior
Can acquire callback token

## Current behavior
The call fails with internal protocol error:

message: Internal protocol error: '-2147467259'.

## Steps to reproduce
Cannot reproduce as this only affects some users

## Link to live example(s)
N/A

# Provide additional details
I believe this is related to this issue here that has been closed: https://github.com/OfficeDev/office-js/issues/2277 

## Context
This issue renders our add-in useless for affected users

## Useful logs
N/A

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by slabereemsft** [comment]
Assigned to Outlook based on related bug (2277) being handled by them.

**Comment by exextoc** [comment]
Thanks for reporting this issue. We have already fixed this bug and the fix is being rolled out. It should be available for everyone by next week

**Comment by liamtim** [comment]
@exextoc Was this ever resolved?

**Comment by exextoc** [comment]
@liamtim Yes this has been resolved. The fix should be available for everyone now.
Thanks!

**Comment by liamtim** [comment]
@exextoc Which version of Outlook for Mac includes the fix? I've reported as similar issue in #3386. Is this also resolved?

**Comment by exextoc** [comment]
@liamtim This issue regarding getCallbackTokenAsync should have been fixed in the older builds as well and update shouldn't be required and for #3386, that seems to be a different issue and the corresponding ticket has been updated.
