### ISSUE TITLE
GetFileAsync() API doesn't yet work on Windows Office 2016 MSI build

### ISSUE THREAD

**Issue by sumurthy** [OfficeDev/office-js#33]
getFileAsync() allows add-ins to get base64 encoded version of the file. This API was added to Windows monthly channel build recently. However, it doesn't yet work on Office 2016 MSI build. 
Ask: add this API support for Excel 2016 MSI build as well.

**Comment by JuaneloJuanelo** [comment]
we are no backporting to MSI. 2019 will include it.

**Comment by ajay71082** [comment]
Currently i'm getting following error while using getFileAsync method with Excel2016
Please help on this
![image](https://user-images.githubusercontent.com/10616848/60498075-cc537a00-9c6a-11e9-8bf8-5d2b3aaf86a7.png)
