### ISSUE TITLE
RecipientType in outlook Office.context.mailbox.item is not consistent

### ISSUE THREAD

**Issue by twinVectr** [OfficeDev/office-js#330]
Initialized outlook in office-js-API, the recipientType on the item is not consistent always. 

The API response has RecipientType = "user" for distribution item and RecipientType = "distributionList" for user item or sometimes "other".

Why is this inconsistency?

![screen shot 2018-08-30 at 2 31 11 pm](https://user-images.githubusercontent.com/17032110/44871657-6ae50800-ac61-11e8-870b-c840cd93445b.png)

reference: Office.MailboxEnums.RecipientType

**Comment by macOutlookExtensibility** [comment]
Hi, Fix is in progress. will update the thread once it gets checked in.

**Comment by kbrandl** [comment]
@macOutlookExtensibility any update on the status of this issue and deployment of the corresponding fix?

**Comment by bhatnagarsaddy** [comment]
@AlexJerabek Hi Alex, Did you find any resolution for this issue? I am getting similar inconsistency for "Office.context.mailbox.Item.start" property

**Comment by AlexJerabek** [comment]
I'll ping @macOutlookExtensibility again and try to track down some answers internally.

**Comment by sergez** [comment]
The same issue reproduced in Outlook 2016 Online with CU 13.

The behavior is the following:
1/ when we open existing meeting with distribution list added - recipientType == 'other'
2/ when select the distribution list from the "People" dropdown - recipientType == 'user'
3/ when select the distribution list from the "People" dropdown by clicking "+" sign in the field - recipientType == 'distributionList' (as expected)

![image](https://user-images.githubusercontent.com/164393/60093009-04c9f400-9751-11e9-874e-06e154555d41.png)

**Comment by neprasad-microsoft** [comment]
This issue has been fixed as confirmed in https://github.com/OfficeDev/office-js/issues/1909 and https://github.com/OfficeDev/office-js/issues/1873 . Marking this as closed
