### ISSUE TITLE
insertFileFromBase64 fails with error "Cannot read properties of null (reading 'message')"

### ISSUE THREAD

**Issue by miikka-laakso-dh** [OfficeDev/office-js#3300]
# Provide required information needed to triage your issue
Word Online insertFileFromBase64 API returns error "Cannot read properties of null (reading 'message')", but if you wait for awhile (or do other operations) content appears in some time to document surface. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Browser (if using Office on the web): Chrome
 
## Expected behavior
insertFileFromBase64 doesn't fail

## Current behavior
insertFileFromBase64 fails with message `"Cannot read properties of null (reading 'message')"`

```
[ERROR]: Error:
{
    "stack": "RichApi.Error: Cannot read properties of null (reading 'message')\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:330439)\n    at o.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:394605)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:392668",
    "message": "Cannot read properties of null (reading 'message')",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "Cannot read properties of null (reading 'message')",
        "statement": "var insertFileFromBase64 = selection.insertFileFromBase64(...);",
        "surroundingStatements": [
            "var root = context.root;",
            "var selection = root.getSelection();",
            "// Instantiate {selection}",
            "var insertText = selection.insertText(...);",
            "// Instantiate {insertText}",
            "// >>>>>",
            "var insertFileFromBase64 = selection.insertFileFromBase64(...);",
            "// <<<<<",
            "// Instantiate {insertFileFromBase64}"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
`}`
```

## Steps to reproduce

1. Open following script in Script Lab (https://gist.github.com/miikka-laakso-dh/7c07609f7d572348d7bd3a608441c29a)
2. Run the script

## Context

We use `insertFileFromBase64` to insert existing (partial) content to active document. Public API should not break.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by veysby** [comment]
Looks like a duplicate for #3040

**Comment by miikka-laakso-dh** [comment]
Any update on the matter? #3040 has been open almost 5 months already. What's the timeframe for the fix?

**Comment by xiruatms** [comment]
Thanks for checking.

We're fully aware of this issue. Multiple teams are involved discussing the root cause & solution options. Given the complex, I can't promise any timeline on it now. Thanks for your patience.

**Comment by miikka-laakso-dh** [comment]
Any update for this regression, why this isn't fixed?

**Comment by xiruatms** [comment]
@miikka-laakso-dh , thanks for your patience. The fix is now on production. Will you please take a try to see whether it works for you?
