### ISSUE TITLE
Office.actions.associate works in Excel Online but not Excel Desktop

### ISSUE THREAD

**Issue by OfficeAddins** [OfficeDev/office-js#3301]
# Provide required information needed to triage your issue

## Your Environment
Platform: Windows 11
Host: Excel
Office version number: Version 2303 Build 16227.20280 - 64-bit
Browser: Edge Version 112.0.1722.48 (Official build) (64-bit)

## Expected behaviour
When the add-in loads an additional button is displayed on the Home tab.
When you press this button, the currently selected cells should be shaded yellow.
This should work in Excel Online and Excel Desktop.

## Current behaviour
This works as expected in Excel Online.
but in Excel Desktop nothing happens when you press the button.

## Steps to reproduce
The source code has been uploaded here
https://github.com/OfficeAddins/commands

**Comment by OfficeAddins** [comment]
The commands.js file had the following syntax, the button only works in Excel Online.
**Office.onReady = function (reason) { 
}**


When you change the syntax to the following, the button now works in both Excel Desktop and Excel Online.
**Office.onReady( function (reason) {
})**

**Comment by donlvMSFT** [comment]
Hi @OfficeAddins , I tried the add-in you attached but seems works well on my environment (both online and desktop). We'll do more investigation and confirm.

**Comment by OfficeAddins** [comment]
Hi, the add-in/source code in github does work now because I changed the syntax of the onReady call:

I guess the question is now why does the following syntax work in Excel Online ??
**Office.onReady = function (reason) {
}**

**Comment by pkkj** [comment]
Hi @OfficeAddins , 

Based on the Office Add-in [documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/initialize-add-in), only Office.onReady(callback) is supported. Another approach is to use Office.initialize = function() {}. Therefore, **Office.onReady = function (reason)** is not supported.

Generally speaking, in Add-in Command (ribbon button action), Office.initialize or Office.onReady is used as a signal to notify Office that "add-in's JavaScript code is ready", so it's safe to invoke the action defined by Office.actions.associate().

Thanks.
