### ISSUE TITLE
[Outlook 2016]Outlook web add-in grey out after install some COM add-in

### ISSUE THREAD

**Issue by Howard-Song** [OfficeDev/office-js#3302]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **PC desktop**
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.5387.1000 MSO(16.0.5366.1000)
* Operating System: Windows 10
* Browser (if using Office on the web): ______
 
## Expected behavior

Can use both COM add-in and web add-in

## Current behavior

On Outlook 2016 for windows, when user have installed `Advent APXOutlookSync` or `Exclaimer Email Alias Manager Outlook Add-in`, create a new message compose wii not be able to use web add-in(Like ). And user can normally use in Message reply/Appointment/Message draft.
<img width="286" alt="image" src="https://user-images.githubusercontent.com/28775661/232710992-36cb3351-ee48-4278-9803-1dec20270d16.png">

Outlook 2019/365 for windows and outlook for web works well

## Steps to reproduce

1. Install COM add-in: `Advent APXOutlookSync` or `Exclaimer Email Alias Manager Outlook Add-in`
2. Open outlook 2016 to create new message

## Context

I saw a related issue: https://github.com/OfficeDev/outlook-dev-docs/issues/307, and it answered on 2018, but I still can reproduce this on outlook 2016. But it work well on Outlook 2016, can I fix this issue through install some patch on outlook 2016?

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Hi @Howard-Song, apologies for the late follow-up on this. This should be fixed in Outlook 2019, so you would need to upgrade to that or the C2R version of Outlook. Additionally, some COM add-ins can cause compatibility issues with Web add-ins if they are using custom forms, which Web Add-ins do not support.

For Outlook 2016 updates, you can reference this link: https://learn.microsoft.com/en-us/officeupdates/outlook-updates-msi
