### ISSUE TITLE
Detection of forward and reply event

### ISSUE THREAD

**Issue by Aidar-Frontend-Developer** [OfficeDev/office-js#3303]
How I can detect forward and reply event, to avoid additional request, or collect forwarding emails?

**Comment by exextoc** [comment]
You can use the [getComposeTypeAsync](https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#outlook-office-messagecompose-getcomposetypeasync-member(1)) API for the same. This API specifies the type of message compose which can be either new, reply or forward. You can leverage the same accordingly.
