### ISSUE TITLE
How to get document id value

### ISSUE THREAD

**Issue by arma78** [OfficeDev/office-js#3304]
Hi there,
I am trying to get Document ID Value but when I calling context.document.properties.customProperties; I get only the document _dlc_DocIdItemGuid guid value.
Thank you.

    function getCustomPropertyValue() {
        Word.run(function (context) {
            var customDocProps = context.document.properties.customProperties;
            // first, load custom properties object
            context.load(customDocProps);
            return context.sync()
                .then(function () {
                    
                    customPropertiesArray = [];
                    var obj;
                    var termParts;
                    var termLabel;
                    var termSubstingLabel;
                  
                    for (var i = 0; i < customDocProps.items.length; i++) { 

![Test1](https://user-images.githubusercontent.com/37850817/232824538-bfdda34b-c42f-47ad-8d25-9727ced83e7f.png)

**Comment by ghost** [comment]
Thank you for letting us know about this issue. We will take a look shortly. Thanks.

**Comment by xiruatms** [comment]
@arma78 , thanks for reporting this.

If I don't misunderstand, you want to retrieve "Document ID Value" with APIs, correct? How is your document assigned with such a "Document ID Value" please? Why do you try to retrieve with customProperties?

According to my understanding, this "Document ID Value" is assigned by host server (sharepoint, onedrive or else). The implementation might be different. 

In my test cases, files on sharepoint were used. The "Document ID Value" is assigned and stored in the document as a customxmlpart. Then, I can get it back with https://learn.microsoft.com/en-us/javascript/api/word/word.customxmlpart?view=word-js-preview

Will you please help to confirm how "Document ID Value" is generated & how it is stored?

Please correct me if I have any misunderstanding here.

**Comment by arma78** [comment]
@xiruatms 
Thank you for your response. it is the feature in SP activated on site level


![image](https://user-images.githubusercontent.com/37850817/233004487-e3c9e466-1d40-44b2-8034-733ecb7b0af0.png)

![image](https://user-images.githubusercontent.com/37850817/233005550-2fea9cf8-343f-4830-8331-06ed24f782d8.png)

**Comment by xiruatms** [comment]
@arma78 , thanks for your confirmation.

If that's the case (generated on SP, sharepoint?), I assume the "Document ID Value" is stored in the customxmlpart of the document.

You can try to : 1) download the document locally; 2) unzip the document; 3) Check the xml files in folder:"customxml".

You may find how "Document ID Value" is stored and then you can retrieve the "Document ID Value" with https://learn.microsoft.com/en-us/javascript/api/word/word.customxmlpart?view=word-js-preview

**Comment by arma78** [comment]
Got it Thank you @xiruatms.


<xsd:element name="_dlc_DocId" ma:index="30" nillable="true" ma:displayName="Document ID Value" ma:description="The value of the document ID assigned to this item." ma:indexed="true" ma:internalName="_dlc_DocId" ma:readOnly="true">
<xsd:simpleType>
<xsd:restriction base="dms:Text"/>
</xsd:simpleType>
</xsd:element>
<xsd:element name="_dlc_DocIdUrl" ma:index="31" nillable="true" ma:displayName="Document ID" ma:description="Permanent link to this

**Comment by JinghuiMS** [comment]
Closing this issue because it appears to be resolved, but please let us know if you have further questions or feel it needs to be re-opened.

**Comment by arma78** [comment]
Thanks for the support.
Yeah, this works in Word but not for PowerPoint.

 function getDocumentID() {
        const XML_NS = 'http://schemas.microsoft.com/office/2006/metadata/properties'
        Office.context.document.customXmlParts.getByNamespaceAsync(XML_NS, (result) => {
            if (result.status !== Office.AsyncResultStatus.Succeeded) return

            const part = result.value[0]
            part.getNodesAsync('*/documentManagement/*', (result) => {
                if (result.status !== Office.AsyncResultStatus.Succeeded) return
                result.value.forEach((node) => {
                    if (node.baseName === "_dlc_DocId") {
                        node.getXmlAsync(result => {
                            if (result.status === Office.AsyncResultStatus.Succeeded) {
                                var res = result.value;
                                documentID = res.substring(res.lastIndexOf('">') + 2, res.lastIndexOf("</"));
                                console.log(documentID);
                            } else {
                                console.error('failed to set node text', result.error)
                                showNotification("Error:", e);
                            }
                        })

                    }

                })
            })
        })
    }
