### ISSUE TITLE
Can a OneNote taskpane support SSO?

### ISSUE THREAD

**Issue by Admiral-Skye** [OfficeDev/office-js#3305]
I have tried creating a new taskpane and including a **WebApplicationInfo** element in the manifest using the same credentials as my Word/Excel/PPT add-in and set the taskpane to load the same url. 

When I open the taskpane in onenote after uploading the add-in manually I see the following error in the console:
`TypeError: Office.auth is undefined`

However as far as I can tell from the doco here: https://learn.microsoft.com/en-us/javascript/api/office/office.auth?view=common-js this should be available to me?

I would like my taskpane to be able to use the same authentication mechanisms for OneNote as the other office apps.

**Comment by slabereemsft** [comment]
Hi Admiral-Skye,

The OneNote team prefers that issues be opened here - https://github.com/OneNoteDev/OneNoteApi.

Thanks!
-Sean

**Comment by Admiral-Skye** [comment]
@slabereemsft I see, I feel like this is an Office-js issue, however ill submit a ticket over there, thank you

**Comment by slabereemsft** [comment]
Thank you!
