### ISSUE TITLE
Office.context.mailbox.item?.body.getAsync fails frequently in Outlook for Mac

### ISSUE THREAD

**Issue by abdumanas-plutoflume** [OfficeDev/office-js#3306]
# Provide required information needed to triage your issue
In Outlook for Mac, the `Office.js` API to retrieve email body, both as `text` and `html`, fails frequently. The error code and message extracted from the error are below:
```
errorCode: 5001, 
errorMessage: An internal error has occurred., 
errorName: Internal Error, 
```

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.62.611.0
* Operating System: Mac OS X 10.15.7
* Browser (if using Office on the web): ______
 
## Expected behavior

The `Office.js` API should be reliable in all platforms.

## Current behavior

The `Office.js` API to retrieve email body is unreliable in Outlook for Mac.

## Steps to reproduce

1. Create an onSend event handler which invokes `Office.context.mailbox.item?.body.getAsync`
2. Run it in an Outlook for Mac version specified above.

## Context

The frequent failure of the API has caused our add-in to fail multiple times.

## Useful logs

- [x] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by eugene-plutoflume** [comment]
A similar issue has been fixed last year. I guess you still get the same issue, see https://github.com/OfficeDev/office-js/issues/2386

**Comment by exextoc** [comment]
Hey @abdumanas-plutoflume 

We are not able to reproduce the issue.
Can you please help us with a sample add-in where the issue is reproducible?
