### ISSUE TITLE
Multiple instance of Excel and add-in fails when tabbing between Excel

### ISSUE THREAD

**Issue by batch08** [OfficeDev/office-js#3307]
We have an Excel add-in that creates and populates a sheet with large number of rows, while that is processing we open another and do the same procedure using a different data filter values. While we do this, the moment the first one finishes, if you are active in the second workbook, the add-in throws an error for the first one in the second workbook.

## Expected Behavior
Add-ins should process their data to their respective Excel instance.

## Current Behavior
Add-in throws an error to whichever Excel instance that is active that is not executed by the add-in in first instance of Excel.

## Context
Processing data that takes long prompts users to open another Excel and multi-task while waiting for the first one to finish.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number:  Version 2304 (Build 16327.20134 Click-to-Run)
* Operating System:  W11

**Comment by donlvMSFT** [comment]
Hi @batch08 , thanks for reporting this issue. 

I want to confirm that 1. Does your add-in use Shared runtime? 2. Could you share any example could repro this issue? 
That would really help us to locate the root cause.

**Comment by batch08** [comment]
Hi @donlvMSFT, the add-in does not use the Shared runtime I believe. Unfortunately, I don't have a public copy that can be used as an example to repro the issue. Is there a way to reach out to you and discuss this privately?

**Comment by batch08** [comment]
I just found a similar open issue: https://github.com/OfficeDev/office-js/issues/3048
and also here: https://stackoverflow.com/questions/61244373/office-js-addin-having-problems-in-multiple-opened-excel
