### ISSUE TITLE
Inserting image via setSelectedDataAsync disables undo button

### ISSUE THREAD

**Issue by A-Glazer** [OfficeDev/office-js#3308]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Current behavior
When inserting an image into PowerPoint Web using setSelectedDataAsync, the undo button is disabled and the action cannot be undone. 

## Expected behavior
When inserting an image using setSelectedDataAsync, the action should be able to be undone.

## Your Environment
* Platform: Office on the Web
* Host: PowerPoint
* Office version number: Office365
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Steps to reproduce
- Open a new PowerPoint web file
- Insert a base64 jpg image using this function:
```
function insertImage(base64){
  Office.context.document.setSelectedDataAsync(base64, coercionType: Office.CoercionType.Image)
}
```
Try to undo the action by pressing CTRL+Z or clicking the undo button. Notice that the button is disabled.

## Context
If a user mistakenly places an image, the action should be able to be undone.

**Comment by jipyua** [comment]
Thanks for reporting this issue, I can repro it locally though seems it's not quite stable. Sometimes the undo works for me. It has been put on our backlog with bug ID 7823509. We unfortunately have no timelines to share at this point.
