### ISSUE TITLE
The getSelectedDataAsync(Office.CoercionType.XmlSvg) in PowerPoint returns "undefined" instead of expected xml string.

### ISSUE THREAD

**Issue by ThomasHeron** [OfficeDev/office-js#3309]
## Your Environment
Windows 11 Pro, Version; 22H2, Experience; Windows Feature Experience Pack 1000.22640.1000.0
Microsoft 365
 
## Expected behavior
I expect the getSelectedDataAsync(Office.CoercionType.XmlSvg) to return an xml string that I can use in the corresponding "set" function as a basic copy / paste function.

## Current behavior
The function returns only "undefined" with the error description that the coercion type is not supported.

## Steps to reproduce
I made a gist that you can import to ScriptLab and that should reproduce this exact issue; https://gist.github.com/ThomasHeron/038f463c41e095d1da11a4f3c56c0c0c

## Link to live example(s)
https://gist.github.com/ThomasHeron/038f463c41e095d1da11a4f3c56c0c0c

# Provide additional details
The coercion type "text" works just as expected, but with the coercion type XmlSvg only "undefined" comes back

## Context
I'm building an addin for PowerPoint where some copy/paste operations should be part of it. I would of course much rather have a copy / paste possibility that gives the complete set of shape features (not just the svg) but as this is what we have at the moment I will work with that. If there is not even this possibility to do copy / paste operations of shapes, my addin cannot use the Office-js development approach.

## Useful logs
Here is the error message from ScriptLab:
![image](https://user-images.githubusercontent.com/86823836/233564239-4912097a-e1f4-4394-a421-97a7a0afe2b9.png)

**Comment by jipyua** [comment]
Thanks for reporting this issue, I can repro it locally. It has been put on our backlog with bug ID 7823481. We unfortunately have no timelines to share at this point.

**Comment by eyren5000GIT** [comment]
@jipyua I am still running into this issue. Is there any updates on the timeline? This funtionality is quite crucial for my client project. 
Best regards

**Comment by jipyua** [comment]
hi @eyren5000GIT I am sorry for the late reply. We confirmed that this XmlSvg coercion type is not yet supported by PowerPoint platform. There are some mistakes on our documentation which we will correct soon. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum]( https://aka.ms/m365dev-suggestions). Please add your request there if you still wants this functionality. Thanks for your understanding.
