### ISSUE TITLE
Can't get mailbox item properties on Android Outlook app

### ISSUE THREAD

**Issue by mrik23** [OfficeDev/office-js#331]
Is there any different requirements for the Outlook app for Android?

I can retrieve item properties correctly in browser (IE, Chrome) and iOS app, but it doesn't work in the Android app.

The only property working on Android seems to be Office.context.mailbox.item.internetMessageId, the following properties are not retrieved in Android Outlook.

Office.context.mailbox.item.subject
Office.context.mailbox.item.sender.emailAddress
Office.context.mailbox.item.from.emailAddress
Office.context.mailbox.item.body

**Comment by satrip** [comment]
Hi Team,

I have got root cause of issue. I will work on it towards fixing it.

-Saurabh Tripathi

**Comment by ElizabethSamuel-MSFT** [comment]
@satrip: Can you provide an update? Thanks.

**Comment by kbrandl** [comment]
@satrip or @exextoc any update on the status of this issue and deployment of the corresponding fix?

**Comment by satrip** [comment]
@kbrandl It is fixed and working in latest production build.

**Comment by kbrandl** [comment]
@satrip thank you for the confirmation; I'll close this issue since the fix has been deployed.
