### ISSUE TITLE
Outlook Web Add-In Presents Domain Trust Dialog to Users in OWA

### ISSUE THREAD

**Issue by BernieEllis** [OfficeDev/office-js#3310]
# Provide required information needed to triage your issue

We have an Outlook web add-in that implements the OnMessageSend event (Requirement set 1.12) deployed via M365 Admin center centralized deployment that is presenting users with the following prompt:

_"embedded page at FQDNofWebAppService says"

"The domain EXO-OWA-FQDN is acting as Microsoft Office and can run Office add-ins, which may access your personal data. If you trust the domain to run as Office and access your data, click OK to continue."_

If the user clicks OK, the add-in performs as expected; however, if the user clicks Cancel they see the following message in the taskpane:

_"This add-in has been disabled to keep you safe. To continue using the add-in, validate that this item is hosted in a trusted domain or open it in the Office desktop app."_

It appears that we only see this in OWA, not Outlook desktop as the last part of the message suggests.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Exchange Online and this is via OWA
* Operating System: Windows 10 (21H2) or Server 2016
* Browser (if using Office on the web): Edge & Chrome
 
## Expected behavior

I'm expecting to be able to, as the tenant/global admin, to be able to trust the add-in (Similar to how global admins grant consent to apps to avoid users faced with consent prompts) such that users aren't presented with the prompt. Is this possible?

I tried updating the AppDomains property of the manifest to include the OWA FQDN, but am still seeing this popup. I didn't include the FQDN of the app service instance it's being hosted out of because that's already specified in the sourcelocation property.

## Current behavior

Instead of the expected behavior mentioned above, users are prompted as mentioned in the summary above. The prompt makes it sound like the add-in isn't safe, when it's already been vetted by admins.

## Steps to reproduce

1. The prompt appears when either launching the taskpane of the add-in or after hitting send on a message.

## Link to live example(s)

1. Unfortunately, I'm not able to provide a live example publicly.

## Context

My customer is trying to enforce compliance on messages as they are being sent, so it's imperative that we're able to leverage an OnSend event add-in.

**Comment by slabereemsft** [comment]
Hi BernieEllis,

Is the instance of OWA being run from a Microsoft domain? E.g. outlook.office365.com or a custom domain?

**Comment by BernieEllis** [comment]
Hi Sean, it's being run from a Microsoft domain, just in a sovereign cloud instance.

________________________________

**Comment by slabereemsft** [comment]
Hi BernieEllis,

That's likely the cause.  Depending on which sovereign instance you are using, you're going to need to use an Office.JS for that environment.

https://learn.microsoft.com/en-us/office/dev/add-ins/publish/government-cloud-guidance

**Comment by BernieEllis** [comment]
Hmm, makes sense, and made me rethink my first response to you.

So, at first we were using the cloud specific OfficeJS endpoint, and this was working fine with OWA but we began self-hosting because we were being referred to ajax.aspnetcdn.com in Outlook desktop which is not accesible to clients in the environment. So, yes, in the current configuration we're hosting OfficeJS in a custom domain as a workaround.

Thanks much Sean for the response on this. We'll work with the appropriate Microsoft team to make updates to OfficeJS in this environment.

________________________________

**Comment by slabereemsft** [comment]
Great.  If the team with Microsoft has questions about the specific environment which don't belong on a public thread, have them reach out to me (Sean Laberee) and I can connect them with the right folks.
