### ISSUE TITLE
Remove &quot; from tooltip for pinnable addins

### ISSUE THREAD

**Issue by Chris2011** [OfficeDev/office-js#3313]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Expected behavior
When I hover the pin icon for a pinnable addin, it should not tries to render the quotes.

# Current behavior
On Mac with Chrome, when I hover the pin icon of an addin for example my own or the default "Viva Insights" addin, you can see that the tooltip tries to render the quotes but it escapes them so it will look like Pin `&quot;Viva Insights&quot;` This error not happens in Chrome for Windows or on the Desktop client of outlook. Just Chrome for MacOS

This error has nothing todo in general with this repo but I didn't know where I can put this instead.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Use a mac and open Chrome
2. Open Outlook and select an E-Mail
3. Make sure you have some addins which are pinnable (For example Viva Insights)
4. Open the addin and hover the pin icon and wait until the tooltip appears
5. See the HTML entities for quotes.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOS Monterey 12.2.1 (Macbook Air (M1 2020) with latest Chrome
* Node version: - 
* Office version: Office 365 Online

## Failure Logs
No errors

![image](https://user-images.githubusercontent.com/795658/160104020-ce9ba542-cd9c-45cf-b6d0-64bf39af7362.png)

**Comment by Chris2011** [comment]
Or is there smth that I can do in my manifest file to prevent this?

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding a localization rendering error. It has been put on our backlog. We unfortunately have no timelines to share at this point. Internal tracking id: 3140659

**Comment by AlexJerabek** [comment]
Since this is a product issue, not a template one, I'm transferring the issue to the [office-js repo](https://github.com/OfficeDev/office-js).
