### ISSUE TITLE
With multiple mailboxes added to Outlook, SSO does not work for non-default mailboxes

### ISSUE THREAD

**Issue by Iso5786** [OfficeDev/office-js#3314]
# Expected behavior

By implementing the provided example (https://github.com/OfficeDev/Office-Addin-Taskpane-SSO/blob/master/src/helpers/fallbackauthdialog.ts) I expect that if a user has several mailboxes added to her Outlook instance, that the correct user of the selected mailbox is authenticated.
In my case the default mailbox is from ru.nl, and second and third from outlook.com.

I also tried to add logic to set the active account to the currently selected one by passing the account via a URL param to the fallback auth dialog.

Here my complete fallbackauthdialog ts file:
```js
import {
  AccountInfo,
  Configuration,
  PublicClientApplication,
  RedirectRequest
} from '@azure/msal-browser'

const msalConfig: Configuration = {
  auth: {
    clientId: '...'
  },
  cache: {
    cacheLocation: 'localStorage', // Needed to avoid "User login is required" error.
    storeAuthStateInCookie: true // Recommended to avoid certain IE/Edge issues.
  }
}

const loginRequest: RedirectRequest = {
  scopes: [
    'Mail.ReadBasic',
    'Mail.Read',
    'Mail.ReadWrite',
    'Mail.Send',
    'openid',
    'profile',
    'offline_access'
  ]
}

const publicClientApp: PublicClientApplication = new PublicClientApplication(
  msalConfig
)

Office.onReady(async () => {
  if (Office.context.ui.messageParent) {
    publicClientApp
      .handleRedirectPromise()
      .then(handleResponse)
      .catch((error) => {
        console.log(error)
        Office.context.ui.messageParent(
          JSON.stringify({ status: 'failure', result: error })
        )
      })

    const urlParams = new URLSearchParams(window.location.search)
    const currentAccountMail = urlParams.get('currentAccountMail')
    localStorage.setItem('authCurrentMail', currentAccountMail)

    const allAccountsurrentAccount: AccountInfo[] =
      publicClientApp.getAllAccounts()
    const accountObj: AccountInfo = allAccountsurrentAccount.find((acc) =>
      findMyAcc(acc, currentAccountMail)
    )
    publicClientApp.setActiveAccount(accountObj)

    // The very first time the add-in runs on a developer's computer, msal.js hasn't yet
    // stored login data in localStorage. So a direct call of acquireTokenRedirect
    // causes the error "User login is required". Once the user is logged in successfully
    // the first time, msal data in localStorage will prevent this error from ever hap-
    // pening again; but the error must be blocked here, so that the user can login
    // successfully the first time. To do that, call loginRedirect first instead of
    // acquireTokenRedirect.
    if (localStorage.getItem('loggedIn') === 'yes') {
      publicClientApp.acquireTokenRedirect(loginRequest)
    } else {
      // This will login the user and then the (response.tokenType === "id_token")
      // path in authCallback below will run, which sets localStorage.loggedIn to "yes"
      // and then the dialog is redirected back to this script, so the
      // acquireTokenRedirect above runs.
      publicClientApp.loginRedirect(loginRequest)
    }
  }
})

function handleResponse(response) {
  if (response.tokenType === 'id_token') {
    setAuthLog('LoggedIn')
    localStorage.setItem('loggedIn', 'yes')
  } else {
    setAuthLog('token type is:' + response.tokenType)
    Office.context.ui.messageParent(
      JSON.stringify({
        status: 'success',
        result: response
      })
    )
  }
}

function setAuthLog(message: string) {
  localStorage.setItem(
    'authLog',
    new Date() + ': ' + message + ', ' + localStorage.getItem('authLog')
  )
}

function findMyAcc(user: AccountInfo, currentAccountMail: string) {
  return user.username.toLowerCase() === currentAccountMail.toLowerCase()
}
```

# Current behavior

Automatically, a token is requested for the user of the default mailbox (in my case of the domain ru.nl), and not the user of the mailbox  currently selected.
Hence, subsequently calling the Graph API fails with the message: 
`The user account which was used to submit this request does not have the right to send mail on behalf of the specified sending account., Cannot submit message`

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Add several mailboxes to Outlook
2. Clone our project https://github.com/encryption4all/postguard-outlook-addon and use branch `beta_ux`
4. Use my provided code which adds `setActiveAccount` 
5. Try to send a mail with the non-default mailbox.

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* Node version: 16.13.1
* Office version: Office 2019
* Tool version: "@azure/msal-browser": "2.30.0"

## Failure Logs

error: {code: 'ErrorSendAsDenied', message: 'The user account which was used to submit th…ied sending account., Cannot submit message.'}

**Comment by AlexJerabek** [comment]
Transferring this issue to the [office-js repo](https://github.com/OfficeDev/office-js) since it is a product issue, not a template issue.

**Comment by exextoc** [comment]
It seems the issue has already been addressed in a separate thread:  https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5537. The suggested action was to track the accounts or fetch them using getAllAccounts and pass the corresponding account to MSAL JS through setActiveAccount. 

Closing this. Please raise a new issue if this does not solve it for you.
