### ISSUE TITLE
Cant set comment in selected range 

### ISSUE THREAD

**Issue by arjun0722** [OfficeDev/office-js#3315]
# Prerequisites

Please answer the following questions before submitting an issue. 
**YOU MAY DELETE THE PREREQUISITES SECTION.**
- [ ] I am running the latest version of Node and the tools
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed

# Expected behavior

Please describe the behavior you were expecting

# Current behavior

Please provide information about the failure. What is the current behavior? If it is not a bug, please submit your idea to the [Microsoft Tech Community Ideas forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform), so that it gets added to our feature roadmap.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* Node version:
* Office version:
* Tool version:

## Failure Logs

Please include any relevant log snippets, screenshots or code samples here.

**Comment by arjun0722** [comment]
export const addCommentToSelectedCells = async () => {
try {
await Excel.run(async (context) => {
// Get the selected range
const range = context.workbook.getSelectedRange();

// Add a comment to the range
const comment = range.comments.add("This is a comment!");

// Load the comment and execute the request
await context.sync();

console.log(Comment added to range ${range.address}: ${comment.text});
})
} catch (error) {
console.error(error);
}
};

**Comment by arjun0722** [comment]
RichApi.Error: This operation is not implemented.
    at new n (excel-win32-16.01.js:25:242353)
    at i.processRequestExecutorResponseMessage (excel-win32-16.01.js:25:306519)
    at excel-win32-16.01.js:25:304582

**Comment by arjun0722** [comment]
await Excel.run(async (context) => {
    // Add a comment to A2 on the "MyWorksheet" worksheet.
    let comments = context.workbook.comments;

    // Note that an InvalidArgument error will be thrown if multiple cells passed to `Comment.add`.
    comments.add("Sheet1!A2", "TODO: add data.");
    await context.sync();
});


even getting same issue with this code . that operation is not implemented

**Comment by AlexJerabek** [comment]
Hi @arjun0722,
I'm sorry you're having issues with the Office JS APIs. Could you please confirm your version of Excel (and what platform you're on)? Comment APIs were introduced in ExcelApi 1.10. so older versions of Excel wouldn't support them. Check the requirement set table here: https://learn.microsoft.com/en-us/javascript/api/requirement-sets/excel/excel-api-requirement-sets?view=excel-js-preview.

I'm also going to transfer this issue to the [office-js repo](https://github.com/OfficeDev/office-js), since this is unrelated to the React template.

**Comment by dingjin-ms** [comment]
AlexJerabek is totally right, @arjun0722 please directly at me to follow up if you are still having problems after you check the Excel version. Thank you for your reporting!
