### ISSUE TITLE
Bindings are removed in DOCX files generated by DOTX templates (only in Office 365)

### ISSUE THREAD

**Issue by sebasthuis** [OfficeDev/office-js#332]
**Please see update at bottom of post.**

After an update of Office 365 from build 1803 to 1811 the Office.select method does not work anymore in generated documents (.docx) from a template (.dotx). This means that Office.select _does_ return the bindings in Office 2019, 2016 and earlier builds of Office 365. Additionally the method _does_ return the binding in documents that were not created by a template or when the template document itself is opened. 

## Expected Behavior
The function below should return the bindings class.

```
function getBinding() {
    return Office.select("bindings#MyBinding")
}
```

## Current Behavior
The code above does not return the binding. I am still further examining what exactly goes wrong. However I am not able to reproduce it on my development machine (do not have access to an Office 365 license) and debugging with F12Chooser does not result into any valuable insights (i.e. no error messages).

## Steps to Reproduce (only works in build 1811 of _Office 365_)

1. Create a template (.dotx) file that contains a binding.
2. Create a simple add-in that selects the previously mentioned binding with the Office.select method.
3. Double click template to generate document (.docx) file and open the add-in.
4. Execute Office.select method.

## Context
We have developed a Word add-in for a client of ours. A large part of the add-in consists of templates (.dotx) files that automatically open taskpanes in the generated .docx file. These taskpanes allow the user to interact with the template. For the sake of simplicity you could just imagine that the taskpanes contain a number of textfields, that update bindings (rich-text controls) in the document (In reality a lot more is automated). In the past year this has worked correctly at our client. The user opens up a template, a new .docx file is generated and a taskpane opens automatically allowing the user to work with the document.

## Your Environment
* Platform: Surface Book, Windows 10, Office 365
* Host [Excel, Word, PowerPoint, etc.]: Word 365
* Office version number: 16.0.11029.20045 (build 1811)
* Operating System: 16299.785 (build 1709)

## Update
After some more research I came to the conclusion that this is most likely not a bug in Office.js but rather in Word itself. Certain information is added to the webextensions file in the OOXML of the document when a binding is created. These entries with information about the bindings should be transferred to the generated .docx file when a template .dotx file is opened. This does not happen in the newest version of Word 365. All bindings are removed from the document. Therefore Office.js is not able to locate these bindings. 

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<we:webextension 
    xmlns:we="http://schemas.microsoft.com/office/webextensions/webextension/2010/11" id="{<removed>}">
    <we:reference id="<removed>" version="<removed>" store="<removed>" storeType="<removed>"/>
    <we:alternateReferences/>
    <we:properties/>
    <we:bindings>
        <!-- this get removed -->
        <we:binding id="BindingIdExample" type="text" appref="28855083"/>
    </we:bindings>
    <we:snapshot 
        xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"/>
</we:webextension>
```

This is a huge problem for us, since I do not know how to work around this bug. Any advice would be appreciated, but I am aware that this is not the place to discuss this.

**Comment by kbrandl** [comment]
@ThePillowPrince thanks for reporting this problem, and for providing the detailed update as well. 

@JuaneloJuanelo is there someone on the Word product team that we can hand-off this issue to (if it is indeed a problem with Word itself, as @ThePillowPrince suggests)?

**Comment by sebasthuis** [comment]
@kbrandl : Thank you for your response. 
@JuaneloJuanelo : Is there any status update on this issue?

**Comment by JuaneloJuanelo** [comment]
@ThePillowPrince    i tried this in a recent build and i am not able to repro.. is this still an issue?

**Comment by JuaneloJuanelo** [comment]
no longer repro.
