### ISSUE TITLE
[Excel API] Programatically disable excel edit mode or ability to exit edit mode

### ISSUE THREAD

**Issue by miranda18** [OfficeDev/office-js#3323]
Hello! 

This feature request is related to the issue that other users seem to be facing as well. Please find the encountered error below:
> "RichApi.Error: Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again."

**Related bugs:** 
	• https://github.com/OfficeDev/office-js/issues/856 
	• https://github.com/OfficeDev/office-js/issues/792
	• https://github.com/OfficeDev/office-js/issues/791

## **Our add-in scenario:** 

1. A user presses a button to load data into the sheet 
2. Sheet creation begins
3. Data populates into the sheet 
4. Sheet creation ends
5. User is able to edit desired cells

## **Where the issue/error is being faced:**

1. A user presses a button to load data into the sheet
2. During sheet creation, the user either:   
     - Spam clicks in the sheet -> edit mode gets enabled
     - Clicks into the sheet and begins to type -> edit mode gets enabled  
4. Sheet creation immediately fails 
5. User receives error 

*_Note:  Our sheet creation takes time as we are making multiple excel API calls._ 
##
**Hoping for any of the following solutions:**

1. Temporarily disable edit mode in the sheet to reduce the chance of encountering the edit mode error, which would allow us to run our sheet creation tasks without accidental/intentional user interruption.
2. Detect if user is in edit mode. If they are, programmatically exit edit mode for the user, so they do not encounter this error, or receive a prompt/message to exit edit mode in order to continue with the action they attempted. 

Currently I have found that someone has opened a feature request similar to the above: 
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/improving-excel-add-in-api-failures-when-in-celleditmode/idi-p/3201549 

Any feedback would be greatly appreciated. Thank you in advance!

**Comment by damacisaac** [comment]
Facing the same issue. We also have sheet creation events that take time, and background tasks that run periodically, both of which fail if the user is in cell editing mode. As @miranda18 suggested, being able to detect cell editing mode so that we can notify the user of the issue could be helpful. 

Also it seems like there are many API calls that could be enabled while cell-editing mode is active, particularly ones that are read-only.

@JinghuiMS is there any update on this?

**Comment by HugoAlbertoNieto** [comment]
I'm also having the same issue as @miranda18 and @damacisaac. @JinghuiMS is there any update or may be a suggested workaround for this?

**Comment by shanshanzheng-dev** [comment]
Hi @HugoAlbertoNieto could you please give us some repro steps or repro video? Thanks.

**Comment by damacisaac** [comment]
@shanshanzheng-dev there's a clear repro in the issue description. Can you use that? It's very easy to repro based on the examples given by myself and @miranda18.

**Comment by shanshanzheng-dev** [comment]
@damacisaac Thanks, we'll take a look and report back if we have a suggestion for you.

**Comment by andrewtsybulia** [comment]
We face the same issue

**Comment by duane-j-wagner** [comment]
How about this for a proposed solution: Treat add-in js as being run by a different user with the same permissions as the current user.  It could have 'add-in' appended to the name.  This would allow the add-in to make changes while the other user is in edit mode, as it the add-in was running on a new instance of Excel.  This would also allow for clear review of add-in changes, adding comments, or even reverting the changes.

**Comment by damacisaac** [comment]
@shanshanzheng-dev I may be off but I feel this issue is serious and severely limits the ability of addins to work correctly. Has there been any progress on this issue?

**Comment by adrianwu8516** [comment]
Hi @duane-j-wagner, @damacisaac, @miranda18 

Thank you for reporting this issue and suggesting this feature. While it is on our backlog, we do not currently have an active plan to implement it. We prioritize features based on community interest, as reflected by votes in our technical forums. Please consider voting for this feature in the forum to help us triage its importance relative to other requests.
[https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/improving-excel-add-in-api-failures-when-in-celleditmode/idi-p/3201549](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/improving-excel-add-in-api-failures-when-in-celleditmode/idi-p/3201549)

While it's on the backlog, we would recommend designing a process to wait for the user to exit edit mode and fire the action with { delayForCellEdit: true }, it's not a perfect solution but could be a potential way to unblock the current problem. 

Please let me know if this does not work for your scenario, thanks!

**Comment by eqan** [comment]
Still facing the issue but for word if anyone has found some solution lemme know

**Comment by DarshanCrestlk** [comment]
Still facing the same issue in the Desktop Version. If anyone has found the solution, let us know

**Comment by gdevillele** [comment]
still facing the same issue in Excel desktop. Please do something about it.
