### ISSUE TITLE
Office.initialize will not fire, if the subject contains UTF-8 characters

### ISSUE THREAD

**Issue by xTNTx666** [OfficeDev/office-js#3326]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Outlook Office.initialize will not be executed if the subject contains UTF-8 characters. Such as \u001C or \u001A. A Json parse error occurs in the callback where the e-mail is loaded. This doesn't happen on the web

## Your Environment
Microsoft® Outlook® für Microsoft 365 MSO (Version 2303 Build 16.0.16227.20202) 64 Bit 
 
## Expected behavior
Office.initialize called and Item Change Event triggert like in the Web-Version 

## Current behavior
Nothing will happend and Nothing load.
If the task pane was loaded from another mail, the Item Change event is not triggered.

## Steps to reproduce
Try to Load a task pane with a mail that have an non ASCII character

## Useful logs
SyntaxError: Bad control character in string literal in JSON at position 121
    at JSON.parse (<anonymous>)
    at I (outlook-win32-16.02.js:20:192818)
    at E (outlook-win32-16.02.js:20:191066)
    at outlook-win32-16.02.js:20:194899
    at Object.agaveResponseCallback (<anonymous>:1:8715)
    at window.agaveHostCallback (<anonymous>:1:11147)
    at <anonymous>:1:8

shortet Payload:
[0,[[1,1],"{\"hostVersion\":\"16.0.16227.20280\", \"itemType\":1, \"subject\":\"WG: Urgent instructions required \u001A Hallo\"

**Comment by zhngx1** [comment]
Thanks for reporting this issue regarding subject contains these UTF-8 characters. It has been put on our backlog. We unfortunately have no timelines to share at this point.

 
Internal tracking id: Office: 7861413
