### ISSUE TITLE
Cannot insert Ooxml in Word Online

### ISSUE THREAD

**Issue by Mukhammadsaid19** [OfficeDev/office-js#3327]
# Cannot insert OOXML in Word Online: `ooxmlIsMalformed` exception

## Your Environment

* Platform: Office on the web
* Host: Word
* Office version number: 16.0.16426.41003
* Operating System: Windows, Mac
* Browser (if using Office on the web): Google Chrome
 
## Expected behavior
When I try to use `insertOoxml()` with valid ooxml string it has to insert the ooxml to the document.

## Current behavior
Currently, `insertOoxml()` doesn't work as expected. Even if we try to get the document's current ooxml, and then use this ooxml to replace the document's ooxml (i.e. idempotent operation), it throws `ooxmlIsMalformed` exception.

## Steps to reproduce

Try to run this snippet on Word Web:

```
return Word.run(async (context) => {
      const body = context.document.body;
      const bodyOOXML = body.getOoxml();
      await context.sync();

      // Queue a command to replaceOOXML
      body.insertOoxml(bodyOOXML.value, "Replace");
      await context.sync();
    });
```

It throws `RichApi.Error: ooxmlIsMalformated`

## Context

I am trying to perform a transliteration of the document from one writing script to another (Latin/Cyrillic). During the process I replace all the text inside the text tags in xml, and then replace the document's body with the modified ooxml using `insertOoxml()`. It perfectly works on Word Windows or Mac; however it fails on the Web version.

**Comment by LyingLin0808** [comment]
@Mukhammadsaid19 Did you encounter this issue by triggering the function two or more times continuously? If so, you can have a try that refreshing the browser after triggering the function.
