### ISSUE TITLE
OfficeRuntime on custom function on PROD

### ISSUE THREAD

**Issue by CarlosVieir** [OfficeDev/office-js#3328]
## How to use the OfficeRuntime API on PROD environment.

I'm working on a excel add-in using custom function where the function use a OfficeRuntime.auth.getAccessToken() to fetch the token. The excel add-in is deploy in k8s cluster and the manifest is publish on SharePoint.

### Error I'm getting:
`
TypeError: Cannot read properties of undefined (reading 'getAccessToken')
`

### Question
What is the process to PROD that allow the use of OfficeRuntime API?

**Comment by yjoshi-msft** [comment]
Hi CarlosVieir,

Thank you for reaching out. Github posts are focused on reporting potential bugs or errors in our documentation.
You should try posting this query on - https://stackoverflow.com/questions/tagged/office-js
Hope this helps.
