### ISSUE TITLE
Office.EventType.DialogMessageReceived Event not getting triggered

### ISSUE THREAD

**Issue by gs-skujala** [OfficeDev/office-js#3329]
# Provide required information needed to triage your issue
Office.EventType.DialogMessageReceived Event will not trigger on outlook web application. We use this event to login into the Outlook Add-in. This event is triggered as expected in outlook desktop app but not being triggered in browser outlook app

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): Chrome Version 112.0.5615.138 (Office Build) (64-bit)
 
## Expected behavior
We use this API 'Office.context.ui.displayDialogAsync' to open a new window and once the window is closed, we expect Office.EventType.DialogMessageReceived to be triggered as it is working in Desktop outlook app but not being triggered when outlook is opened on browser

## Current behavior
Currently the Office.EventType.DialogMessageReceived Event is not being triggered

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

When we trigger Office.context.ui.displayDialogAsync API to open a new window, it would be better if it returned an instance of the window so we can keep track of the window/tab and also helps us to have workarounds if incase we face these kind of problems in future

## Useful logs

- [0] Console errors
- [0] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Thanks for reaching out. From the description, 

1. It looks like you are expecting DialogMessageReceived to be triggered when the dialog is closed. Is our understanding correct?
2. If yes, then “DialogEventReceived” should be intercepted instead.
 

DialogMessageReceived is an event that is triggered when a dialog box sends a message to its parent. This event is supported by the UI.displayDialogAsync method in Office Add-ins.
When you use this method to display a dialog box in your add-in, you can register an event handler for the DialogMessageReceived event. This allows you to receive messages from the dialog box and take appropriate action based on the message.
 
DialogEventReceived is an event that is triggered when a dialog box has been closed or otherwise unloaded. This event is supported by the UI.displayDialogAsync method in Office Add-ins.
 
 For more info, https://learn.microsoft.com/en-us/javascript/api/office/office.dialog?view=common-js-preview

**Comment by gs-skujala** [comment]
We are expecting to DialogMessageReceived to be triggered when we receive any message from the new URL that we opened

Let me explain you the flow,

### Event Listener
```
Office.context.ui.displayDialogAsync(URL, { height, width, callback: (result)=>{
        if (result.status === Office.AsyncResultStatus.Succeeded){
            const dialog = result.value;
            dialog.addEventHandler(Office.EventType.DialogMessageReceived, (evt) => {
                // evt.message       
            })
        }
    }
})
```
### URL - Page opened in new tab

- It loads **office.js** script & it also generates some data
- This page indents to send back this data to the Add in by using below snippet

```Office.context.ui.messageParent(data);```

This code is working fine for most of the users but fails for 1 particular user and that too in browser outlook only. Desktop outlook Add in works fine as expected.

I want to know what we can do to fix this situation from office JS side. Is there any workarounds we could use? or Do you think there could be any better approach?

**Comment by exextoc** [comment]
@gs-skujala Can you please share your manifest file to "OutlookExtensibility@M365x27035562.onmicrosoft.com" so that we can try to repro the issue? And a short video of the bug will help us better debug the problem.

**Comment by exextoc** [comment]
Closing this since there's no further response. Please do re-open the thread incase something needs to be added

**Comment by BryanCB1** [comment]
Hi hi have the same issue here, our implementación is the next one;

 window.Handler.dialog.addEventHandler(Office.EventType.DialogMessageReceived, function(event) {
                        var message = JSON.parse(event.message);
                        window.Handler.handleChildMessage(asyncResult.value, message.type, message.payload);
                    });
                    
this works fine in desktop, web and iOS app, but not in Android app
