### ISSUE TITLE
Cannot get messages and contacts from Outlook REST API

### ISSUE THREAD

**Issue by markb-trustifi** [OfficeDev/office-js#333]
I'm using office-js version: 16.0.10831.10000 on Mac
The problems exist in both Outlook client and browser.

I can query for specific email item:
```js
Office.context.mailbox.getCallbackTokenAsync({isRest: true}, result => {
$http({
method: 'GET',
url: Office.context.mailbox.restUrl + '/v2.0/me/messages/' + restItemId,
headers: {'Authorization': 'Bearer ' + result.value}}).then(function (result) {
...
});
});
```

But when I ty to get a full email collection I get this error:
```js
{
    "error": {
        "code": "ErrorAccessDenied",
        "message": "The api you are trying to access does not support item scoped OAuth."
    }
}
```

Another issue there is with contacts collection after retrieving token from Office.context.mailbox.getUserIdentityTokenAsync.
```js
{
    "error": {
        "code": "InvalidAudience",
        "message": "The audience claim value is invalid 'https://mydomain.herokuapp.com/#/mailbox'.",
        "innerError": {
            "requestId": "792ad1dd-cd5f-47c9-a0d6-01a1e1c297a1",
            "date": "2018-12-17T14:59:54"
        }
    }
}
```

My manifest has permissions:
```js
<Permissions>ReadWriteMailbox</Permissions>
<Rule xsi:type="RuleCollection" Mode="Or">
        <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit" />
        <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
</Rule>
```

But after decoding the token in https://jwt.io/ it shows version: ExIdTok.V1
(getCallbackTokenAsync shows Exchange.Callback.V1)

I think there should be V2 because of the mailbox level permissions

It looks like it is the same bug as here:

https://stackoverflow.com/questions/42420073/cant-add-attachment-to-message-in-outlook-add-in-using-outlook-rest-api

**Comment by markb-trustifi** [comment]
crossposted to:
https://social.msdn.microsoft.com/Forums/en-US/bfb8bbd0-8ddf-424c-8469-a6fdd73c00ea/cannot-get-messages-and-contacts-by-outlook-rest-api?forum=outlookdev

**Comment by exextoc** [comment]
You would need to call getCallbackTokenAsync with the isRest parameter set to true to get appropriate tokens

**Comment by markb-trustifi** [comment]
> You would need to call getCallbackTokenAsync with the isRest parameter set to true to get appropriate tokens

1. I just mistyped my question, I always used it with rest=true.
2. getCallbackTokenAsync works only for read-email window and only to read/write item properties.

**Comment by exextoc** [comment]
getCallbackTokenAsync should show Exchange.Callback.V2 and not V1 when isRest is passed as true. Could you share your outlook build number you are testing this from on MAC? It might be worth testing this API on a windows outlook client too, are you able to reproduce the issue there as well or does that work as expected?

**Comment by markb-trustifi** [comment]
Now `getCallbackTokenAsync` returns:
ver: Exchange.Callback.V2
scp: Mail.ReadWrite Mail.Send Calendars.ReadWrite Contacts.ReadWrite
aud: https://outlook.office365.com

and returns another error for https://outlook.office365.com/api/v2.0/contacts (or messages):
```js
{
    "error": {
        "code": "RequestBroker--ParseUri",
        "message": "Resource not found for the segment 'contacts'."
    }
}
```

On the other hand the `getUserIdentityTokenAsync` returns token with:
ver: ExIdTok.V1
aud: https://mydomain/#/mailbox

window location is https://mydomain/#/login
error message: The audience claim value is invalid

The result from Outlook client (version is 16.20 (181208)) and from browser with https://outlook.office.com is the same.

**Comment by exextoc** [comment]
Your request url is malformed: change it to https://outlook.office365.com/api/v2.0/me/contacts and it should work. You should use the token returned by getCallbackTokenAsync and not the UserIdentityToken for the REST call. That should fix your issue.

**Comment by markb-trustifi** [comment]
Yes, now I see, thank you for pointing it.
Unfortunately it doesn't solve my problem. I want to get the list of contacts from the compose window but `getCallbackTokenAsync` works only in read-message window:
```js
error: {
   code: 9029
   message: "The token can't be retrieved until the item is saved."
   name: "CanOnlyGetTokenForSavedItem"
}
```

**Comment by exextoc** [comment]
In compose-mode, you have to first save the message and then call getCallbackTokenAsync(). Based on this, below sample code should work:

```
//Save an item async
Office.context.mailbox.item.saveAsync
(
	function(asyncResult)
	{
		showMessage(JSON.stringify(asyncResult));
		
		// Get a callback token
		Office.context.mailbox.getCallbackTokenAsync(
			function (asyncResult)
			{
				showMessage(JSON.stringify(asyncResult));
			}
		);
	}
);
```

**Comment by markb-trustifi** [comment]
Is there a way to receive such token directly via http request?
or use `getUserIdentityTokenAsync` instead of it for querying Contacts API?

**Comment by exextoc** [comment]
getCallbackTokenAsync is the most direct way for addin to get a REST token. there's no direct http request to get a REST token.  To be clear, getUserIdentityTokenAsync provides user identity, but does not provide access to any APIs.  Please take a look at https://docs.microsoft.com/en-us/outlook/add-ins/authentication for more details or options

**Comment by markb-trustifi** [comment]
The solution is found. 
Instead of office-js methods we can use the standard OAuth2 REST API:
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow
