### ISSUE TITLE
Outlook Add-in to show pop up box when user tries to 'send' an email

### ISSUE THREAD

**Issue by gs-skujala** [OfficeDev/office-js#3331]
We have following requirement,
- Is there any Office.js event that gets triggered when user tries to send an email (clicks on 'send')
- Can we show a popup box in middle of the screen and confirm whether or not to send the email?

If it is not possible to stop an email from sending or trigger an event when trying to send an email, is there any way to show a popup in middle of the screen 
We have this requirement for both desktop outlook Add-in & browser outlook Add-in

<img width="1405" alt="Screenshot 2023-05-03 at 7 16 04 PM" src="https://user-images.githubusercontent.com/61771998/235934616-5e4d2518-b654-471e-87ce-32819a023232.png">

**Comment by exextoc** [comment]
@gs-skujala  Thanks for reaching out. Kindly refer to the onSend feature https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=classic and let us know if it meets your requirements.

**Comment by exextoc** [comment]
Closing this since there's no further response. Please do re-open the thread incase something needs to be added
