### ISSUE TITLE
displayDialogAsync yields error 12004 even if (sourceLocation) domains are same.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#3337]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office On The WEB
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: M365 
* Operating System: MAC
* Browser (if using Office on the web): Chrome 

## Expected behavior-

displayDialogAsync() should work correctly if sourceURL and dialog URL are of the same domain.

## Current behavior

displayDialogAsync() should work correctly if sourceURL and dialog URL are of the same domain.

## Steps to reproduce

NOTE : This does not happen in all M365 accounts. Currently, I have an M365 account/domain that can reproduce this.
1. Create an addin manifest that has different sourceLocations for Mailbox 1.1, (overridesv1_0) Mailbox 1.4 and (overridesv1_1) Mailbox 1.5. 
2. Once you have the said addin manifest setup, install the said manifest in an environment supporting Mailbox 1.5.
3. In your addin, invoke displayDialogAsync() and open a URL under the domain of Mailbox 1.5.
4. Open OWA and ensure that the Mailbox 1.5 is the one executed.
5. Run your addin allowing it to call displayDialogAsync().
6. displayDialogAsync() fails with ERROR 12004 
`error: OSF.DDA.Error 
code: 12004
message: "The domain of the URL is not included in the AppDomains element in the manifest, and is not subdomain of source location."
name: "Display Dialog Error"`

## Link to live example(s)

As I have said, this does not happen in all M365 domains. If needed, we can discuss on how we can test this in our test domain.

# Provide additional details

I tested by setting the sourceLocation of Mailbox1.1 into the same domain as the opened URL of displayDialogAsync(). And the error was resolved. In theory, Mailbox1.1 sourceLocation should not be a point of reference for displayDialogAsync() running in a Mailbox 1.5 environment, correct? Or should sourceLocation be the same for all three Mailbox 1.1, (overridesv1_0) 1.4 and (overridesv1_1) 1.5?

Also this bug did not occur before, our addin was working and behaving correctly. I don't think there were any major changes in our mail configuration as well.

## Context

This is currently making our addin not behave according to our customer provided specs.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@glr0221  Can you please share your manifest file to "OutlookExtensibility@M365x27035562.onmicrosoft.com" so that we can debug the issue better?

**Comment by glr0221** [comment]
@exextoc Thank you for the prompt response. I will be sending you the manifest once I get clearance from our InfoSec team. Thank you very much.

**Comment by glr0221** [comment]
@exextoc I have sent you a copy of a working manifest for our addin. Thank you.

**Comment by stefanoslig** [comment]
Hello! We have the same issue! As @glr0221  mentioned it doesn't happen on every M365 account

**Comment by exextoc** [comment]
Hey @glr0221 ,

Apologies for the delay in response. We received and were able to install the add-in, however- we are unsure as to when the add-in triggers the displayDialogAsync. Could you walk us through the steps to trigger the dialog.

Also looking at the manifest, it seems that `AppDomains` is indeed not defined. can you see if adding the endpoint domain of the dialog API call to the manifest indeed fixes it?

**Comment by glr0221** [comment]
Hello @exextoc,

Thanks for the response. 

To get the dialog triggered, you have to open an email in your inbox and then click on the button. Once successful, the dialog should show itself at the end of the process.

I have not tried adding appdomains yet. But changing sourcelocation for Mailbox 1.1 fixed our issue initially. 

What is interesting though is that today (May 17, 2023), all our addins are now working correctly.  @stefanoslig is your environment fixed as well? 

I will check with other affected domains and update this ticket later. 

Thanks again.

**Comment by glr0221** [comment]
@exextoc As of May 31, 2023, this issue has again resurfaced. Can we please reopen this ticket? I don't know what changed in the past 14 days (was already working correctly last May 17, 2023) which triggered the issue.

Moreover, when was AppDomains::AppDomain added? Was this a part of the original XML-Schema? 

Thank you.

**Comment by exextoc** [comment]
@glr0221 Yes, AppDomain has been a part of original XML-Schema. Can you please verify if adding the endpoint domain of the dialog API call to the manifest fixes it?

**Comment by glr0221** [comment]
@exextoc I will try this and get back to you with the results as soon as I can.

The part I would like to understand is, even if the addin is operating or using the 'VersionOverridesV1_0' attributes in the manifest, which has a declared sourceLocation similar to the async dialog, why is the addin still failing to load the display dialog because the sourceLocation under the 'FormSettings' attribute set is different? 

For the past years, we have had no issue of this at all. This started around started about a month ago, and then was fixed 2 weeks ago and now it has resurfaced. What has caused the change in behavior all of a sudden? 

Thank you very much.

**Comment by glr0221** [comment]
@exextoc 

I have tested the 'AppDomains::AppDomain' solution. I placed it as a direct child of 'OfficeApp', underneath 'SupportUrl' attribute and above the 'Hosts' attribute. I followed your[ schema documentation here](https://learn.microsoft.com/en-us/openspecs/office_file_formats/ms-owemxml/00e4ee5d-2eb8-47f2-9008-8beb6ff45189). 

The updated manifest looks like this : 

```
  <IconUrl DefaultValue="https://domain1.com/128.png" />
  <HighResolutionIconUrl DefaultValue="https://domain1.com/128.png"/>
  <SupportUrl DefaultValue="https://support.domain1.com />
  <AppDomains>
    <AppDomain>"domain2.com"</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  ...
  ...
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://domain1.com/Home.html"/>
        <RequestedHeight>100</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
```
As shown above, source location is at domain1.com and appdomain is set to domain2.com. Also, please note that, although not shown, VersionOverridesV1_0 and VersionOverridesV1_1, have their source location pointed to domain2.com as well. Is the manifest I created incorrect?

I have tried different values (formats) for the AppDomain element.  I have tried the following : 
1. domain2.com
2. https://domain2.com/
3. https://domain2.com

Again, even with appdomain value set, the displayDialogAsync() still yields an error 12004. Thank you for taking time to investigate this.

**Comment by exextoc** [comment]
Hi @glr0221,
We are trying to reproduce this issue on our end. The add-in sent by you on the email does not launch a display dialog for us. Could you give us a sample code snippet of how you are invoking the API . Are you using the displayInIframe parameter and if so what is the value of this param?

**Comment by glr0221** [comment]
@exextoc Thanks for your update and for testing. I can actually see the emails you have forwarded. 

If you are not seeing a dialog, a few seconds after you click the button, then that means that your environment can reproduce the bug. Some of our test domains could not reproduce this issue as our addin and display dialog work as designed. In your current configuration, the dialog is expected to show for around 10 seconds a few moments after you click the button. The code behind the dialog is something like this : 

` Office.context.ui.displayDialogAsync(url, { height: xx, width: yy, displayInIframe: true }, this.dialogCallback.bind(this))
`

I cannot talk much of the code on this github post, but I can send you some details via email. Can I use this email : OutlookExtensibility@M365x27035562.onmicrosoft.com to send you some details?

Currently the workaround I have is to change the SourceLocation in line 38 of the manifest. I make this value equal to the sourceURL for Version_OverridesvV1_1 at line 197. And this fixed it for me. However, adding appdomains does not work as well. 

Please note that it is only starting around May that this bug started happening. Got fixed around mid-May and now has resurfaced. We have not changed any code nor configurations in our server. 

Let me know if you need any more assistance. Thank you again for taking time to check this out.

**Comment by exextoc** [comment]
@glr0221 we tried it today and the dialog seems to launch properly with a manifest having AppDomains configured. Could you try it on your end too?
We are also investigating on our end that why it stopped working in between. We have opened a backlog bug for this (internal tracking id - 3605425) . We unfortunately have no timelines to share at this point.

**Comment by glr0221** [comment]
@exextoc I might have written the appdomains incorrectly. Can you please send me a copy of your updated manifest via the email address I sent the original manifest with? I would appreciate it greatly. Thank you again.

**Comment by exextoc** [comment]
Hi @glr0221 
We have sent you the updated manifest used by us.

**Comment by glr0221** [comment]
@exextoc Thank you for all the support. I have tested your modified manifest as well. I also confirm that your updated manifest fixes the dialog issue in my environment. I think my tests failed because of some domain issue. The domain I tested with may have been faulty.

Also theoretically, if the SourceLocation was the same as the dialog's url-domain, then I don't need to have the appdomain values correct? 

Thanks again.

**Comment by exextoc** [comment]
Yes, listing the same domain as the one specified in the SourceLocation has no effect. You can find the details at [AppDomain](https://learn.microsoft.com/en-us/javascript/api/manifest/appdomain?view=powerpoint-js-preview)

**Comment by glr0221** [comment]
You are awesome @exextoc .

Thank you. Closing this ticket.

**Comment by ilbrando** [comment]
I am suddenly experiencing this problem. It worked yesterday, and I'm pretty sure I haven't made any changes. I'm experiencing the problem in my dev environment, running on localhost. The taskpane is hosted at https://localhost:3000/save-mail.html and the dialog at https://localhost:3000/search-matter-dialog.html.
My manifest file:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
           xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0"
           xsi:type="MailApp">
  <Id>4bd92469-902f-4e49-8e0c-816ade27aa70</Id>
  <Version>2.0.0.0</Version>
  <ProviderName>Unik System Design A/S</ProviderName>
  <DefaultLocale>da-DK</DefaultLocale>
  <DisplayName DefaultValue="Advosys Addin 2.0" />
  <Description DefaultValue="Advosys Addin 2.0" />
  <IconUrl DefaultValue="https://localhost:3000/assets/app-64.png" />
  <HighResolutionIconUrl DefaultValue="https://localhost:3000/assets/app-128.png" />
  <SupportUrl DefaultValue="https://unik.dk/kontakt-support/" />
  <AppDomains>
    <AppDomain>https://tit-apiman-shared-d.azure-api.net</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox"
           MinVersion="1.1" />
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:3000" />
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
  <Permissions>ReadWriteItem</Permissions>
  <Rule xsi:type="RuleCollection"
        Mode="Or">
    <Rule xsi:type="ItemIs"
          ItemType="Message"
          FormType="Read" />
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides"
                    xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1"
                      xsi:type="VersionOverridesV1_1">
      <Requirements>
        <bt:Sets DefaultMinVersion="1.12">
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>
      <Hosts>
        <Host xsi:type="MailHost">
          <Runtimes>
            <!-- Eventhandler, used by Outlook web and Outlook Mac -->
            <Runtime resid="webViewRuntime.Url">
              <!-- Used by Outlook Windows -->
              <Override type="javascript"
                        resid="javascriptRuntime.Url" />
            </Runtime>
          </Runtimes>
          <DesktopFormFactor>
            <ExtensionPoint xsi:type="MessageReadCommandSurface">
              <OfficeTab id="TabDefault">
                <Group id="msgReadGroup">
                  <Label resid="GroupLabel" />
                  <Control xsi:type="Button"
                           id="save-mail">
                    <Label resid="save-mail.Label" />
                    <Supertip>
                      <Title resid="save-mail.Label" />
                      <Description resid="save-mail.Tooltip" />
                    </Supertip>
                    <Icon>
                      <bt:Image size="16"
                                resid="save-mail.16x16" />
                      <bt:Image size="32"
                                resid="save-mail.32x32" />
                      <bt:Image size="80"
                                resid="save-mail.80x80" />
                    </Icon>
                    <Action xsi:type="ShowTaskpane">
                      <SourceLocation resid="save-mail.Url" />
                      <SupportsPinning>true</SupportsPinning>
                    </Action>
                  </Control>
                </Group>
              </OfficeTab>
            </ExtensionPoint>
            <ExtensionPoint xsi:type="MessageComposeCommandSurface">
              <OfficeTab id="TabDefault">
                <Group id="msgComposeGroup">
                  <Label resid="GroupLabel" />
                  <Control xsi:type="Button"
                           id="send-mail">
                    <Label resid="send-mail.Label" />
                    <Supertip>
                      <Title resid="send-mail.Label" />
                      <Description resid="send-mail.Tooltip" />
                    </Supertip>
                    <Icon>
                      <bt:Image size="16"
                                resid="send-mail.16x16" />
                      <bt:Image size="32"
                                resid="send-mail.32x32" />
                      <bt:Image size="80"
                                resid="send-mail.80x80" />
                    </Icon>
                    <Action xsi:type="ShowTaskpane">
                      <SourceLocation resid="send-mail.Url" />
                      <SupportsPinning>true</SupportsPinning>
                    </Action>
                  </Control>
                </Group>
              </OfficeTab>
            </ExtensionPoint>
            <ExtensionPoint xsi:type="LaunchEvent">
              <LaunchEvents>
                <LaunchEvent Type="OnMessageSend"
                             FunctionName="mailSendEventHandler"
                             SendMode="Block" />
              </LaunchEvents>
              <SourceLocation resid="webViewRuntime.Url" />
            </ExtensionPoint>
          </DesktopFormFactor>
        </Host>
      </Hosts>
      <Resources>
        <bt:Images>
          <bt:Image id="save-mail.16x16"
                    DefaultValue="https://localhost:3000/assets/taskpane-16.png" />
          <bt:Image id="save-mail.32x32"
                    DefaultValue="https://localhost:3000/assets/taskpane-32.png" />
          <bt:Image id="save-mail.80x80"
                    DefaultValue="https://localhost:3000/assets/taskpane-80.png" />
          <bt:Image id="send-mail.16x16"
                    DefaultValue="https://localhost:3000/assets/taskpane-16.png" />
          <bt:Image id="send-mail.32x32"
                    DefaultValue="https://localhost:3000/assets/taskpane-32.png" />
          <bt:Image id="send-mail.80x80"
                    DefaultValue="https://localhost:3000/assets/taskpane-80.png" />
        </bt:Images>
        <bt:Urls>
          <bt:Url id="save-mail.Url"
                  DefaultValue="https://localhost:3000/save-mail.html?tenant=78627e58-e0c4-49ff-92f7-a25a5c2614ef" />
          <bt:Url id="send-mail.Url"
                  DefaultValue="https://localhost:3000/send-mail.html?tenant=78627e58-e0c4-49ff-92f7-a25a5c2614ef" />
          <bt:Url id="webViewRuntime.Url"
                  DefaultValue="https://localhost:3000/event-handler.html?tenant=78627e58-e0c4-49ff-92f7-a25a5c2614ef" />
          <bt:Url id="javascriptRuntime.Url"
                  DefaultValue="https://localhost:3000/event-handler-os-windows.js" />
        </bt:Urls>
        <bt:ShortStrings>
          <bt:String id="GroupLabel"
                     DefaultValue="Advosys Addin 2.0" />
          <bt:String id="save-mail.Label"
                     DefaultValue="Advosys">
            <bt:Override Locale="en"
                         Value="Advosys" />
          </bt:String>
          <bt:String id="send-mail.Label"
                     DefaultValue="Advosys">
            <bt:Override Locale="en"
                         Value="Advosys" />
          </bt:String>
        </bt:ShortStrings>
        <bt:LongStrings>
          <bt:String id="save-mail.Tooltip"
                     DefaultValue="Gem mails på sag eller stamkort.">
            <bt:Override Locale="en"
                         Value="Save mails on a matter or an entity." />
          </bt:String>
          <bt:String id="send-mail.Tooltip"
                     DefaultValue="Anvend data og funktioner fra Advosys">
            <bt:Override Locale="en"
                         Value="Use data and functionality from Advosys." />
          </bt:String>
        </bt:LongStrings>
      </Resources>
      <WebApplicationInfo>
        <Id>22bdb923-e8f2-4344-907b-5f0976768b01</Id>
        <Resource>api://localhost:3000/22bdb923-e8f2-4344-907b-5f0976768b01</Resource>
        <Scopes>
          <Scope>User.Read</Scope>
          <Scope>profile</Scope>
          <Scope>openid</Scope>
        </Scopes>
      </WebApplicationInfo>
    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>
```

**Comment by ilbrando** [comment]
The problem has been solved for me now. A bit wierd. I added localhost to AppDomain though this shuldn't be nessecary and it didn't help, but when I removed it again it suddenly worked.

**Comment by ilbrando** [comment]
It appears that if I add `https://localhost:3000` to the AppDomain element it works, though the documentation states this isn't necessary. 
By the way, adding addins from files seems to have been removed from the UI. You have to navigate to this URL: ` 
https://aka.ms/olksideload`. Is this intentional?

**Comment by dhruv857** [comment]
I can confirm, for web I had to add `https://localhost:3000` to make it work on Outlook Web. on both linux and windows. However, it works on Windows native outlook app without adding localhost domain.
