### ISSUE TITLE
Dialog not displaying data sent from taskpane unless messageParent is used in dialog

### ISSUE THREAD

**Issue by 2jjk** [OfficeDev/office-js#3339]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: 1.1
* Operating System: Windows
* Browser (if using Office on the web): None
 
## Expected behavior

When I press the button that triggers process() function in taskpane.js, a dialog box should open and data is immediately shown.

## Current behavior

Data is not shown unless I call Office.context.ui.messageParent("loaded"); in Office.onReady in dialog.js, but that means two calls to messageParent. I don't understand why that allows it to display the data. 

## Link to live example(s)

1. In taskpane.js:
```
export async function process() {
  // API fetch call
  // ...

  const result = await response.json();

  Office.context.ui.displayDialogAsync(
    "https://localhost:3000/test.html",
    {
      height: 70,
      width: 80,
      displayInIframe: true,
    },
    (asyncResult) => {
      if (asyncResult.status == Office.AsyncResultStatus.Succeeded) {
        dialog = asyncResult.value;
        dialog.addEventHandler(Office.EventType.DialogMessageReceived, async (args) => {
          dialog.messageChild(JSON.stringify(result)); // send to dialog
          document.getElementById("presentations").innerHTML = args.message;
	  
	  // logic to insert slide

        });
      }
    }
  );
}
```
2. In dialog.js:
```
Office.onReady((info) => {
  Office.context.ui.addHandlerAsync(
    Office.EventType.DialogParentMessageReceived,
    onMessageFromParent,
    onRegisterMessageComplete
  );

  // Office.context.ui.messageParent("loaded"); // WORKS IF I USE THIS BUT WHY?
});

async function onMessageFromParent(arg) {
  const result = JSON.parse(arg.message);

  // logic to create table element and populate with data from result
}

function use() {
    // logic to get, from generated table above, the selected cells (select checkbox)
    // the selected are sent as an array of strings back to the taskpane

    Office.context.ui.messageParent(JSON.stringify(presentations));
}
```

# Provide additional details

1. process() function in taskpane.js is triggered by a button in the taskpane
2. onMessageFromParent(arg) function in dialog.js receives data sent by process() and created some HTML components (table, etc.) in the dialog
3. use() function in dialog.js is triggered by a button in the dialog, which uses the table created in step 2.

**Comment by 2jjk** [comment]
**Quick update**: I also tried having `dialog.messageChild(JSON.stringify(result));` outside the dialog event handler, but I couldn't send anything either. As soon as I open the dialog, I want the data sent from the taskpane to immediately show in the dialog.

**Comment by pkkj** [comment]
Hi @2jjk

Without the `Office.context.ui.messageParent("loaded");`, you are calling messageParent() from `function use()`. But in your prototype we could not identify where the `presentations` is defined. Would you like to make sure that this is executed without exception?

Thanks,
-Kejing
