### ISSUE TITLE
Excel link highligthing in comments

### ISSUE THREAD

**Issue by eqinox76** [OfficeDev/office-js#3341]
Manually added comments transform urls into clickable links. Like
![image](https://user-images.githubusercontent.com/5861557/237008575-1ea852a7-be78-49fa-bf07-73cc14b8b99f.png)
But when doing the same steps via the office-js library the link is not created.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2304
* Operating System: Win 11
 
## Expected behavior
Comments created via office-js create a clickable link.

## Current behavior
A comment with the text `www.google.com` is created.

## Steps to reproduce
```typescript
await Excel.run(async (context: any) => {
    const item = context.workbook.comments.getItemByCell('Sheet1!A1');
    item.content = 'www.google.com';
    await context.sync();
});
```

# Provide additional details
https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-comments does not document any special steps to get clickable links.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by JinghuiMS** [comment]
You can set a hyperlink for an Excel comment using the Excel JavaScript API by setting the commentRichContent property of the Comment object. Here's an example:

Excel.run(function (context) {
    // Get the active worksheet
    var sheet = context.workbook.worksheets.getActiveWorksheet();

    // Get the first cell in the worksheet
    var cell = sheet.getCell(0, 0);

    // Add a comment to the cell
    var comment = cell.addComment("This is a comment.");

    // Set a hyperlink for the comment
    comment.commentRichContent = [
        {
            type: "text",
            text: "Click here to go to Google.",
        },
        {
            type: "hyperlink",
            text: "Google",
            hyperlink: "https://www.google.com",
        },
    ];

    // Synchronize the changes with the workbook
    return context.sync();
}).catch(function (error) {
    console.log(error);
});

**Comment by eqinox76** [comment]
Hey @JinghuiMS ,
many thanks for your time. Sadly i cannot run your code example.
I get this error message:` cell.addComment is not a function`

When i change the code to 
```
          Excel.run((context: any) => {
            // Get the active worksheet
            let sheet = context.workbook.worksheets.getActiveWorksheet();

            // Get the first cell in the worksheet
            const cell = sheet.getRangeByIndexes(0, 0, 1, 1);

            // Add a comment to the cell
            let comment = sheet.comments.add(cell, 'This is a comment.');

            // Set a hyperlink for the comment
            comment.commentRichContent = [
              {
                type: 'text',
                text: 'Click here to go to Google.',
              },
              {
                type: 'hyperlink',
                text: 'Google',
                hyperlink: 'https://www.google.com',
              },
            ];

            // Synchronize the changes with the workbook
            return context.sync();
          })
```
The comment gets created but it only shows `This is a comment` without any links.

I couldn't get the richContent part into any comment. And i cannot find the possibility in the [documentation](https://learn.microsoft.com/en-us/javascript/api/excel/excel.commentreplycollection?view=excel-js-preview#excel-excel-commentreplycollection-add-member(2))

Could please have a look what is going wrong?

Much appreciated!

**Comment by JinghuiMS** [comment]
Thanks for reporting your issue.  
The last reply got from our bot (in beta), sorry for not being able to solve your issue, delete it to prevent misunderstandings from those who come later. After I double checked, setting hyperlinks in comments is temporarily not supported on Excel. I'd like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.

**Comment by eqinox76** [comment]
Thanks for clearing that up.
