### ISSUE TITLE
Required Domains to be Added in Frame-Ancestors

### ISSUE THREAD

**Issue by gelicas** [OfficeDev/office-js#3342]
## Post how-to questions about your code on Microsoft Q&A

Hi all, 

We have an officejs add-in where we recently added CSP headers to allow iframing to specific domains only by implementing frame-ancestors.

Currently here is a list of our whitelisted domains for the add-in, I just wanted to confirm if we are already able to cover all possible instances and or if we missed out a domain?

          "https://*.officeapps.live.com",
          "https://*.sharepoint.com",
          "https://*.companynamesample.com",
          "https://onedrive.live.com"

Apologies if I posted in the wrong channel, used the wrong tags, or if this is a duplicate question. Would greatly appreciate it if you could give me an answer to this or redirect me to the accurate QA page.

Thanks in advance!

**Comment by gelicas** [comment]
Just to add more context into this our add-in application is used in Excel web, and we're planning to release this also in PC/MAC in the future

**Comment by gelicas** [comment]
Hi @yaweizhu-henson  and @donlvMSFT was hoping to get an update regarding this. Thanks!

**Comment by donlvMSFT** [comment]
Hi @gelicas ,

Thanks for reaching us. I would like to confirm that these domains are listed in add-in manifest `AppDomains` section?

If yes, please refer to [AppDomain element](https://learn.microsoft.com/en-us/javascript/api/manifest/appdomain?view=excel-js-preview), It mentions 
Specifying a domain in an `AppDomain` isn't necessary for Office on the web or to open a resource in an IFrame, nor it is necessary for opening a resource in a dialog opened with the [Dialog API](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins).

Hope this could help.

**Comment by gelicas** [comment]
Hi @donlvMSFT thanks for replying! these domains are actually defined in frameAncestors and not in the add-in manifest AppDomains section. Reason for this is we added CSP headers to our application, specifically the allowed frame-ancestors so I just wanted to confirm the list of domains for an excel add-in to see if we are already able to cover all possible instances.

I got this list https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide before but it seems some of the links here are not needed to be added to our frameAncestors list (e.g., links for  outlook, skype, etc.)

**Comment by gelicas** [comment]
Hi again @donlvMSFT just wanted to follow up on this, thanks!

**Comment by donlvMSFT** [comment]
Hi @gelicas , sorry I couldn't give much commit but from my view, the list looks fine.
Maybe you could move forward and in case you meet any issues later, we could then look into them.

**Comment by donlvMSFT** [comment]
I'd like to close this issue due to current status, please raise a new one or reactive if there're further questions.

**Comment by nikitamedidar** [comment]
Hi @gelicas, were you able to release the excel web add-in on MS store with the domains you mentioned? I'm currently facing a frame-ancestor issue with web add-in and wanted to know if there are any more domains to be added. Thanks!

**Comment by valse** [comment]
Hi @gelicas I'm dealing with the same issue... what is your Frame Ancestor domain list? Thanks!
