### ISSUE TITLE
[EXCEL] Multi sheet selection

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#3343]
Hi,

Is there a way to find out which worksheets are the selected?

For example:
1. Create a workbook with 5 worksheets
2. Hold Ctrl key and click on each of worksheets.

I've tried some workaround:
1. `onActivated` and `onDeactivated`, but they only fire if the actual worksheet is shown
2. `onSelectionChanged` does not seem to be working

Thanks

**Comment by gingerjia** [comment]
Thanks @danielpdev for reporting the issue! Currently we have no API supports this function. Could you help to submit a new request in the https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform then our PM will triage it accordingly? Thanks again for helping improve our add-in capability!

**Comment by XuanZhouMSFT** [comment]
Thanks for waiting and help posted the feature request. After careful consideration, our team has decided to not do this feature in short term. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.
