### ISSUE TITLE
[Outlook Deeplink] Deeplink creation is totally down

### ISSUE THREAD

**Issue by IQbrod** [OfficeDev/office-js#3345]
# Provide required information needed to triage your issue
Any deeplink lands to an infinite loading page

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop + Office Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook Web
* Office version number: -
* Operating System: Win7
* Browser (if using Office on the web): Chrome Latest
 
## Expected behavior
Any deeplink like https://outlook.office.com/calendar/0/deeplink/compose?rru=addevent&path=%2Fcalendar%2Faction%2Fcompose&subject=DanielPeter should trigger a new event in calendar

## Current behavior
An infinite loading of outlook logo is shown, one can't create event through deeplink

## Steps to reproduce
1. Click [here](https://outlook.office.com/calendar/0/deeplink/compose?rru=addevent&path=%2Fcalendar%2Faction%2Fcompose&subject=DanielPeter)

## Link to live example(s)

# Provide additional details

## Context
Clients can't create events in their calendars

## Useful logs
```
caught (in promise) TypeError: Cannot read properties of undefined (reading 'options')
    at compose?rru=addevent&path=%2Fcalendar%2Faction%2Fcompose&subject=DanielPeter:2:282636
    at compose?rru=addevent&path=%2Fcalendar%2Faction%2Fcompose&subject=DanielPeter:2:283778
    at compose?rru=addevent&path=%2Fcalendar%2Faction%2Fcompose&subject=DanielPeter:2:283782
    at compose?rru=addevent&path=%2Fcalendar%2Faction%2Fcompose&subject=DanielPeter:2:283822
```

**Comment by exextoc** [comment]
Hey @IQbrod ,

This particular github repository is only for queries about Outlook add-ins, and this seems related to deeplinks in Outlook. We are trying to connect you to the best possible place to post this question, meanwhile you can try to submit this using [Feedback for OWA.](https://support.microsoft.com/en-us/office/how-do-i-give-feedback-on-microsoft-365-2b102d44-b43f-4dd2-9ff4-23cf144cfb11#platform=Office_for_the_web)

**Comment by IQbrod** [comment]
Reported the problem on given link

**Comment by IQbrod** [comment]
For people looking for a solution, Microsoft did switch the way of creating deeplink by replacing "0/deeplink" by "action" like : 
> Before : https://outlook.office.com/calendar/0/deeplink/compose?rru=addevent&path=%2Fcalendar%2Faction%2Fcompose&subject=DanielPeter 
  
> After : https://outlook.office.com/calendar/action/compose?rru=addevent&path=%2Fcalendar%2Faction%2Fcompose&subject=DanielPeter

**Comment by IQbrod** [comment]
Source : https://techcommunity.microsoft.com/t5/outlook/https-outlook-office-com-calendar-0-deeplink-compose-fails-to/m-p/3816442

**Comment by Adnilson** [comment]
Just for anyone here that is using markup/styling in the description you'll have to add a 0:

https://outlook.office.com/calendar/0/action/compose?rru=addevent&path=%2Fcalendar%2Faction%2Fcompose&subject=DanielPeter
