### ISSUE TITLE
Excel add-in throws AccessDenied error during runtime.

### ISSUE THREAD

**Issue by jeffycai** [OfficeDev/office-js#3347]
I am testing the displayDialogAsync function of office.js using the official repository example provided at https://github.com/OfficeDev/Office-Add-in-Dialog-API-Simple-Example/. I added some testing code to dialog.html and encountered an AccessDenied error when running it. Below are some screenshots, could you please take a look and help me identify the cause of this error?

`    <script>

        Office.onReady(async (info) => {
            debugger

            if (info.host === Office.HostType.Excel) {
                try {
                    await Excel.run(async context => {
                        debugger
                        const sheets = context.workbook.worksheets
                        sheets.load('items'); await context.sync()
                        let range = sheets.items[0].getUsedRange()

                        let A1 = range.getCell(0, 0)
                        A1.values = [["TESTING"]]
                    })
                } catch (error) {
                    //OfficeHelpers.UI.notify(error);
                    //OfficeHelpers.Utilities.log(error);
                    //await this.append_message("Something went wrong: " + error)
                    console.log("Debug info: " + JSON.stringify(error.debugInfo));
                }
            }

        });
    </script>`

Your Environment
Platform: PC Desktop
Host: Excel
Office version number: Microsoft® Excel® LTSCMSO (Version 2304 Build 16.0.16327.20200) 64
Operating System: Windows 10 Professional
Browser (if using Office on the web): 

Expected behavior
Could you please provide the specific error messages? Without the error messages, it's difficult for me to accurately translate the sentence.

Current behavior
ActionIndex：1
Code： "AccessDenied"
HttpStatusCode：403
位置： "Workbook.worksheets"
信息："无法执行请求的操作。"

Because of the sensitivity requirement, now when opening an Excel document, this warning appears:
image

If a debugger is attached, this error is shown in the console:

Error: Uncaught (in promise): AccessDenied: You don't have sufficient permissions for this action.
RichApi.Error: You don't have sufficient permissions for this action.
    at new RuntimeError (appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.debug.js:10710:36)
    at RequestContext.ClientRequestContext.processRequestExecutorResponseMessage (appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.debug.js:13967:24)
    at appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.debug.js:13888:43
    at ZoneDelegate.invoke (:3000/polyfills.js:377:30)
    at Object.onInvoke (:3000/vendor.js:68991:33)
    at ZoneDelegate.invoke (:3000/polyfills.js:376:36)
    at Zone.run (:3000/polyfills.js:136:47)
    at :3000/polyfills.js:870:40
    at ZoneDelegate.invokeTask (:3000/polyfills.js:412:35)
    at Object.onInvokeTask (:3000/vendor.js:68969:33)
    at resolvePromise (:3000/polyfills.js:811:39)
    at :3000/polyfills.js:718:21
    at rejected (:3000/vendor.js:141247:89)
    at ZoneDelegate.invoke (:3000/polyfills.js:377:30)
    at Object.onInvoke (:3000/vendor.js:68991:33)
    at ZoneDelegate.invoke (:3000/polyfills.js:376:36)
    at Zone.run (:3000/polyfills.js:136:47)
    at :3000/polyfills.js:870:40
    at ZoneDelegate.invokeTask (:3000/polyfills.js:412:35)
    at Object.onInvokeTask (:3000/vendor.js:68969:33)
It looks like the issue it's because the add-in is configured to open automatically and it doesn't wait until the sensitivity label is selected.

I'm using [Office.onReady](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/initialize-add-in) to delay initialization of functionality until Office is ready. But even if I delay this initialization and select the Sensitivity label before, it still doesn't work.

Reloading the add-in doesn't solve it either.

The only way to make it work is to close the add-in and then load it again from the ribbon.

I'm using version 1.1 of office.js, but I also tried with the latest beta version

https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
https://appsforoffice.microsoft.com/lib/beta/hosted/office.js

Is there a different way to delay the opening or initialization of the add-in to wait until the Sensitivity label is selected?

**Comment by ghost** [comment]
Thank you for letting us know about this issue. We will take a look shortly. Thanks.

**Comment by Rick-Kirkham** [comment]
Most Office.js APIs cannot be called in the dialog. Note this line from [Dialog API](https://learn.microsoft.com/office/dev/add-ins/develop/dialog-api-in-office-add-ins):

"The messageParent function is one of only two Office JS APIs that can be called in the dialog box. The other JS API that can be called in the dialog box is Office.context.requirements.isSetSupported."

**Comment by jeffycai** [comment]
@Rick-Kirkham Thank you for the document you provided. By the way, if I need to access other APIs in a pop-up window, besides communicating with the parent window, are there any other simple ways?
