### ISSUE TITLE
 Outlook add in can not close

### ISSUE THREAD

**Issue by Sivanyan** [OfficeDev/office-js#3348]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Outlook add in dialog can not close

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac, PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: all
* Operating System: window, ios
* Browser (if using Office on the web): chrome
 
## Expected behavior
open outlook add in on domain: example.com -> login flow start -> login success domain moved to subdomain: sub.example.com -> close dialog -> link added to calendar event body

## Current behavior
open outlook add in on domain: example.com -> login flow start -> login success domain moved to subdomain: sub.example.com -> dialog not closed and get stuck-> link doesn't added to calendar event body -> getting the following error: 

Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://sub.example.com/') does not match the recipient window's origin ('https://example.com/').

## Link to live example(s)
https://www.loom.com/share/fa83d07f7b4944f3b1c0d3839bacb7c6

# Provide additional details
The add-in is unable to complete its task and becomes stuck.
We try to add the subdomain to the manifest file:
    <AppDomains>
        <AppDomain>https://example.com/</AppDomain>
        <AppDomain>https://sub.example.com/</AppDomain>
    </AppDomains>
and still get the same error.
How can we close the dialog and complete the dialog job with the url including the subdomain ?

## Context
Users can not use the add in 

## Useful logs
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://sub.example.com/') does not match the recipient window's origin ('https://example.com/').

Thank you

**Comment by exextoc** [comment]
Hey @Sivanyan ,

Please refer to this document for [Cross domain messaging](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#cross-domain-messaging-to-the-host-runtime) between dialog and host. You should be able to use `targetOrigin ` property to resolve your issue.

Calling event.completed() after receiving the dialog event should help you terminate the add-in execution.

**Comment by Sivanyan** [comment]
@exextoc  Hey, 
Thank you for the quick response, I used targetOrigin  property and it is work great for window outlook platform but when I check it on Outlook for mac (outlook desktop on mac version: 16.72.3) I still facing the same problem. Is there other property to use for this platform ? 
this how I use it:


 `    Office.context.ui.messageParent(
            JSON.stringify({ status: 'ok', domain: domain, userId: userId, companyId: companyId }),
            { targetOrigin: 'https://example.com' }
        );`

        
In addition, I found this issue: https://github.com/OfficeDev/office-js/issues/2484

Any updates? 
Or is there a workaround I can implement in my add-in? There are customers who are waiting for the fix.  
Thanks

**Comment by exextoc** [comment]
Hi @Sivanyan, could you please confirm for which platform you're facing still facing the issue? From the [video ](https://www.loom.com/share/fa83d07f7b4944f3b1c0d3839bacb7c6) you had shared earlier it seems like you're using Outlook on Web (OWA). Is the issue related to OWA or Outlook client running on Mac?

**Comment by Sivanyan** [comment]
@exextoc right now the issue is only on Mac desktop (video was taken before using targetOrigin)

**Comment by exextoc** [comment]
Hi @Sivanyan, thanks for confirming. We are not able to repro this issue at our end. Could you please share a sample manifest that we can use to repro the issue? You can email us at this address: OutlookExtensibility@M365x27035562.onmicrosoft.com

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding display dialog. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 3615151
