### ISSUE TITLE
Get AllDayEvent and Private flags from Office.context.mailbox.item (Outlook)

### ISSUE THREAD

**Issue by rodrigoguariento** [OfficeDev/office-js#335]
I'm building an add-in for Outlook and here is a doubt: is it possible to get **AllDayEvent** and **Private** flags from Office.context.mailbox.item or somewhere else of an appointment? I haven't saw nothing related in this documentation. Thanks!

* Platform: PC desktop (test), Linux Ubuntu (dev), Office Online (test)
* Host: Outlook
* Office version number: Office 365 ProPlus v1803 build 9126.2336, and Web (office.com)
* Operating System: Windows 10 Pro 
* Browser (if using Office Online): Google Chrome 71.0.3578.98 64bits

**Comment by exextoc** [comment]
Currently the feature: Get Allday Event/ Private flag, you requested, is not a part of the product. We track Outlook add-in feature requests on our [user-voice](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins) page. Please add your request there. Feature requests on user-voice are considered when we go through our planning process. 

Meanwhile you could use the appointment's item Id to get this information by making a rest request:
Office.context.mailbox.restUrl + '/v2.0/me/events/' + itemId.

Make sure to convert the itemId into restId first by using convertToRestId function

**Comment by rodrigoguariento** [comment]
Thanks by alternative. Do you mean that I need to get this itemId from callback.value of item.saveAsync? If I try getting item.itemId (at least in my scenario), this one returns always undefined.

**Comment by exextoc** [comment]
Depends on the scenario, for meetings/appointments, if you are the organizer, you will have to call item.saveAsync and use the itemId returned there compared to a meeting on which you are an attendee where you can directly access item.itemId.
