### ISSUE TITLE
Excel custom functions calculation issues, sometimes showing #CALC! and quite often crashing while recalculating reports

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js#3351]
# Provide required information needed to triage your issue
Our customers started reporting that Excel is having issues with custom functions calculations.
- In some complex reports it started to show sometimes #CALC! issue. When investigating the #CALC! comes IMMEDIATELY after calculation being triggered. Sometimes it is resolved with Ctrl+Alt+Shift+F9, but 
- quite frequently excel will crash with our add-in while recalculating the reports via sheet.Calculate(true) api within Office.js, sometimes crash with Ctrl+Alt+Shift+F9

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number:
-- Excel® for Microsoft 365 MSO (Version 2301 Build 16.0.16026.20214) 64-bit
-- Office365 enterprise semi-annual
-- Office Professional Plus 2021 LTSC (version 2108, Build 14332.20481)
-- Office Professional Plus 2021 LTSC (version 2108, Build 14332.20493)
* Operating System: Windows
 
## Expected behavior

Calculation should be reliable and it should not cause crash. NEVER.

## Current behavior

With certain reports excel is crashing. For some customers Ctrl+Alt+Shift+F9 is somehow working but for others it causes crashes as well + #CALC! should not appear.

## Steps to reproduce

With customer reports, we can eventually provide more logs/dumps + set up debug session

# Provide additional details

We are using non-volatile functions and we are using worksheet.calculate(true) to force their recalculation via custom button (as per recommendation from MS).

## Context

Office web add-ins are sand boxed (at least it was told us so some time ago) and so it should not cause excel crashes.

## Useful logs

Error log: 
[AppCrash_EXCEL.EXE_75a6bb6546ee7c0fbd846a62f764552b699ede4_00000000_d4effc27-3ad4-41d2-84db-7a7d8cc40c05.zip](https://github.com/OfficeDev/office-js/files/11449327/AppCrash_EXCEL.EXE_75a6bb6546ee7c0fbd846a62f764552b699ede4_00000000_d4effc27-3ad4-41d2-84db-7a7d8cc40c05.zip)

**Comment by rundongmsft** [comment]
Hi @4tti, from the log files you provided, I was not able to reproduce the issue or find some key clues. Could you please provide a sample file with the complex report? It would be nice to have a video attached so that I can understand your scenario and repro steps.

**Comment by 4tti** [comment]
@rundongmsft of course, though I am not sure I'll be able to do that today.
And thanks a lot in advance!

Edit: will try tomorrow, sorry :(

**Comment by 4tti** [comment]
@rundongmsft  this is just screenshot from VS:
![image](https://github.com/OfficeDev/office-js/assets/19533927/1f88b17b-7b87-443d-96f4-fe123a5a941f)
I have crash dump if you want (need some location where to upload it)

Edit: recording https://www.screencast.com/t/YeXxaVwthrty

What I am calling is Ctrl+Alt+Shift+F9, first attempt succeeds, second causes crash (in this case). However, it behaves differently on customer environments, etc.

Notice the #CALC! errors - it is remnant from last calculation, it is hard to reproduce but when it happens, for some reason some of custom functions are not triggered at all and immediately show #CALC! error resulting to pollute many cells which depend on those with #CALC! errors....

**Comment by 4tti** [comment]
Can we get some attention to this issue please?
@rundongmsft @JinghuiMS

**Comment by jiju-MS** [comment]
hey, @4tti, from your call stack it seems like something wrong happened with excel calc caused crash, not directly related to custom function, is there any repro steps that we can follow? From our general test on Custom function by using Ctrl+Alt+Shift+F9 or worksheet.calculate(true), no issue or crash have been found.

**Comment by rundongmsft** [comment]
Hi @4tti, from the video you provided, I think that some functions or combination of functions triggered the crash when calculating. But I cannot analyze the root cause. I tried the same steps with sample CFs locally and didn't meet any crash. So, could you please provide me the files in the video and an account to log in to the add-in? So that I can reproduce your issue locally and analyze the root cause. 
In addition, perhaps some data is sensitive, maybe you can simplify this file. I believe there is a minimum data/function set, which does not depend on add-in login and specific data, to reproduce this issue.

**Comment by 4tti** [comment]
Hello @rundongmsft, unfortunately it is not that easy.

1. we don't have the addin on store so I need to prepare some environment for public access
2. the #CALC! errors are not that easily reproducable
3. Crashes happen just on some environment, so even if I give you access it does not mean you'll reproduce.

I can check users where it happens and maybe they will be willing to have some session with us (me and you) if it is somehow feasible. Or is it not realistic?

**Comment by 4tti** [comment]
@rundongmsft can you please let me know?
This is not stale...

**Comment by 4tti** [comment]
@rundongmsft we need feedback ASAP!
We are able to reproduce on one of our environments so it would be beneficial to have a call together, ideally with someone who can debug remotely or get some more details during that session.
Thanks a lot in advance!

@JinghuiMS FYI

**Comment by ZYUN-MSFT** [comment]
Summary the update here:

We already have E-Mail & Teams Thread with customer for detail re-pro enviroment. And we're carried out the investigation on this. We will update the information here once we got update.

Thanks.

**Comment by 4tti** [comment]
Just for anyone facing similar issues, as a possible workaround/temp solution, you can disable multi-threaded calculation:
![image](https://github.com/OfficeDev/office-js/assets/19533927/1c422e6f-5ead-4887-a1da-6319e57c5fd9)

**Comment by 4tti** [comment]
@rundongmsft, @jiju-MS, @ZYUN-MSFT  JFYI the crash is not reproducible anymore, good job there.

However, we still face the "#CALC!" errors + **new intermittent issue** with not showing "#BUSY" in the cells while using Ctrl+Alt+Shift+F9.

The "#CALC!" error happens only with custom calculation when we trigger sheet by sheet calculation or when just calculating single sheet (as per recommendation from MS in the past). It does not happen with Ctrl+Alt+Shift+F9

MS Excel Beta Channel Version 2403 (Build 16.0.17419.20000)

**Comment by mmfernand** [comment]
@rundongmsft @jiju-MS @ZYUN-MSFT there are instances when clicking the Ctrl Shift Alt F9 to recalculate but it does not calculate. As you can see in the screenshot, it has the 'Calculate' message in the status bar, but it does not execute the Execute Functions.
<img width="604" alt="NewScreenshot 2024-03-05 160654" src="https://github.com/OfficeDev/office-js/assets/161710805/fc0132db-4dbf-4d7e-953e-dda285de4a0f">

**Comment by rundongmsft** [comment]
Hi @4tti and @mmfernand, regarding the new issue you've mentioned, to keep our issue tracking clear and effective, it'd be great if you could open a new issue for it. This way, we can better track the situation and keep the discussions focused.

**Comment by mmfernand** [comment]
Hi @rundongmsft noted. I will create new issue for this. Please check https://github.com/OfficeDev/office-js/issues/4214

**Comment by 4tti** [comment]
@rundongmsft nevertheless please still don't close this issue because of the #CALC! errors appearing. It seems that it was not still fixed. Of course it might be error 'Function has failed. This function performs an asynchronous operation but has unexpectedly failed. Try again later.' from https://support.microsoft.com/en-us/office/how-to-correct-a-calc-error-d6ee03c5-daf6-426a-8df5-4b284730ab1b (other suggested reasons should not apply unless there is some deeper issue within calc engine of excel). But then we need explanation for questions like:

1. As it does not trigger anything from our Add-in (it is just instantly shown) how can we prevent this to appear?
2. When and why does it happen (as it seems rather excel's calculation engine issue)?

**Comment by 4tti** [comment]
We are no longer able to reproduce the #CALC error.
Thanks a lot!!
