### ISSUE TITLE
Unable to create a contentControl on a footnote in Word online version

### ISSUE THREAD

**Issue by docu-bill** [OfficeDev/office-js#3355]
I am having problems creating content controls even when the whole document is created on the word online version. 

See this gist: https://gist.github.com/docu-bill/6238eddac3c7555a439ee07c5aa4fd8d

Load an addin with this taskpane.ts and click run you will see that the content control cannot be created on the footnote. This works correctly in the desktop app

## Your Environment

* Platform: Office on the web
* Host: Word
* Office version number: not sure guess it is not relevant as it is an online issue as of now
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome and Edger
 
## Expected behavior
Adding the content control on the footnote should wrap the footnote in a content control as it does in the desktop version of Word

## Current behavior
insertingContentControl causes a GeneralException on sync()

## Steps to reproduce

1. Create a new typescript addin with `yo office`
2. Relpace taskpane.ts with the gist above
3. Run addin and console will show an error

## Link to live example
This [Script Lab Gist](https://gist.github.com/docu-bill/3777dc855ea3084e6b3c7c2a4ca4217e) demonstrates the problem

No data is needed problem occurs from a blank document

## Context
I want to prevent the user from changing the added footnote

**Comment by docu-bill** [comment]
I also have trouble adding contentControls to paragraphs in Tables in Word online see [Script Lab Gist here](https://gist.github.com/docu-bill/28ebf0baccbe81fc20303e37f837c6fa)

**Comment by penglongzhaochina** [comment]
Thanks for reporting this issue.  

It has been put on our backlog<Bug#7897412> for internal track. We will keep track of this issue and let you know if there are any updates.

**Comment by penglongzhaochina** [comment]
Hi @docu-bill , Thanks for reporting this issue. After the investigation, it's by design. It's a feature gap between win32 and wac. Insert a contentcontrol in the footnote is not supported in the word online.

**Comment by docu-bill** [comment]
OK I will add another issue regarding adding content controls in tables?
