### ISSUE TITLE
Unable to use to officeJS npm package instead of cdn one

### ISSUE THREAD

**Issue by wail-hammani** [OfficeDev/office-js#3358]
## My Environment
- Platform: Desktop
- OS: Windows 10 OS
- Host : Office Word 2016
- Browser : IE11, Brave(Chromium)

 ## Expected behaviour 
I expected that the application starts using the officeJS Api that i installed from npm

## Current Behaviour
the application is not launching and give this error : 
"Uncaught Office Web Extension script library file name should be office.js or office.debug.js."
 
## Steps to reproduce
1. npm i @microsoft/office-js
2. make a copy of @microsoft/office-js/dist to somewhere in the project directory
3. reference the office.js file that you copied using a <script> tag

## Context
Hi everyone, i'am developping a word addin in react with yoeman generator under word 2016 and since i work in a corporate, we are always behind proxies so i tried to use the office JS Library offered by npm and followed exactlly what the documentation says.
- I installed the package with npm install @microsoft/office-js.
- copied the content of the dist file to a local directory
- then referenced the office.js file in the html root file inside <scrypt> tag.

when i start the application i get an error saying that the library script name must be office.js or office.debug.js .
i believe that the issue is that webpack is changing the name of the file and giving it a hash name so the browser doesn't find any file named office.js
 i tried to add a configuration to my webpack   and added the office.js file as an entry but still not working.
i have tried with externals like said here : https://stackoverflow.com/questions/33915826/exclude-module-from-webpack-minification and still don't have any good results

**Comment by hengchengfei** [comment]
+1

**Comment by wangyun-microsoft** [comment]
@jipyua can you take a look?

**Comment by fujinilsu** [comment]
This issue still persists a year later. 
Could someone please fix it? 🙏

**Comment by jipyua** [comment]
hi @nirneu, sorry for the late response, this is not a bug, but instead should because the webpack config renamed the office.js and generated a randome name for it. Please change your webpack configure and this should be resolved.

**Comment by MonMon2016** [comment]
@jipyua  How to change your webpack configure? Tks

**Comment by MonMon2016** [comment]
module: {
      rules: [
        {
          test: /office\.js$/,
          generator: {
            filename: "office.js",
          },
        },
      ],
    },
ERROR in Conflict: Multiple assets emit different content to the same filename office.js. Original source assets/office-js/dist/office.js
