### ISSUE TITLE
Table selection does not work as expected

### ISSUE THREAD

**Issue by docu-bill** [OfficeDev/office-js#3359]
# Provide required information needed to triage your issue
If the user makes a selection in a table, then only the last row of that selection is captured by 
`context.document.getSelection()`

## Your Environment

* Platform: PC desktop, Office on the web
* Host: Word
* Office version number: not sure ... the latest
* Operating System: Windows
* Browser (if using Office on the web): Chrome and Edge
 
## Expected behavior
If a selection includes more than one row, all rows should be returned by the getSelection() method

## Current behavior

If the user selects cells from more than a single row (either a single column or multiple columns) then the paragraphs contained in the selection only include the last row selected. 

For example if the user selects cells ("0,0", "0,1", "1,0", "1,1") only the paragraphs from cells "1,0", "1,1" will be found

## Steps to reproduce

1. Open [Script Lab Gist](https://gist.github.com/docu-bill/0c733aa7575b57901cc8d48f4effb60d)
2. Click setup to create an empty table make a selection of more than one row or make your own empty table
3. You can select two cells above another two, a whole column or the whole table. The found cells will not agree with expectations

## Link to live example(s)

1. [Script Lab Gist](https://gist.github.com/docu-bill/0c733aa7575b57901cc8d48f4effb60d)

# Provide additional details

## Context

I am trying to enter data into selected cells in bulk, to save the user time.  Once I can find the TableCell object (or the paragraphs contained) I can enter in the cells as desired.

My current work arround would be to ask the user to select only cells from single rows

## Useful logs

This is a screen shot of the log with the whole table selected... only 4 cells found
<img width="865" alt="image" src="https://github.com/OfficeDev/office-js/assets/131843506/466e9913-8b2d-4f8a-b5de-af15eeaa6cd2">

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by xiaoyuMS** [comment]
Hi @docu-bill 
This is a by-design behavior for getSelection(). We don't support discontinuous selection. The selection of columns is regarded as a discontinuous one. E.g., These two selections are in the same way:
<img width="422" alt="image" src="https://github.com/OfficeDev/office-js/assets/90585978/16bb71b9-97be-4e07-ab10-31e900a97a5c">
<img width="411" alt="image" src="https://github.com/OfficeDev/office-js/assets/90585978/a2c52366-ad02-4849-960f-cb17b775608a">


We do support getting the selection of multiple WHOLE rows. To make the row selection, please put the cursor at the left (and outside) of the table to select one or multiple rows. In this way, you can get multiple rows.

**Comment by docu-bill** [comment]
Thank you selecting by rows works
