### ISSUE TITLE
How to get appointment recurrence info

### ISSUE THREAD

**Issue by rodrigoguariento** [OfficeDev/office-js#336]
I'm using Office 365 Enterprise E3 Developer. Is there a way (or alternative) for we get/set recurrence info from an appointment in my office-js project? Thanks.

- Platform: PC desktop (test), Linux Ubuntu (dev), Office Online (test)
- Host: Outlook
- Office version number: Office 365 ProPlus v1803 build 9126.2336, and Web (office.com)
- Operating System: Windows 10 Pro
- Browser (if using Office Online): Google Chrome 71.0.3578.98 64bits

**Comment by exextoc** [comment]
Are you trying to connect against an O365 exchange account?

**Comment by rodrigoguariento** [comment]
I have no sure, I've created an account into [Office Developer Program](https://developer.microsoft.com/en-us/office/dev-program) and my project is being made with Office 365 from there. I started my project with **yo office** (npm generator-office). It will make difference? I thought that it was related to office js API version.

**Comment by exextoc** [comment]
If the account was set up using the developer program, it would be a test Office365 account. You could use REST to achieve this but in more recent Office clients(which you could get by updating yours), we have an office js API to get the recurrence object. I would look at the documentation [here](https://docs.microsoft.com/en-us/javascript/api/outlook_1_7/office.recurrence?view=office-js) as a starting point
