### ISSUE TITLE
Search does not work properly in Word online, if using `matchWholeWord`

### ISSUE THREAD

**Issue by gion-andri** [OfficeDev/office-js#3360]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
In Word online, the `context.document.body.search` API (and also the related search APIs on paragraphs, ranges,...) doesn't work if `matchWholeWord` is set to true in [SearchOptions](https://dev.office.com/reference/add-ins/word/searchoptions) and the search term contains special characters (i.e. "à"). It works in Windows Word and macOS Word application though.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.16510.41005
* Operating System: macOS
* Browser (if using Office on the web): Chrome, Firefox
 
## Expected behavior

`context.document.body.search` should find words containing special characters even when `matchWholeWord` is set to true.

## Current behavior

`context.document.body.search` does not find words containing special characters when `matchWholeWord` is set to true.

## Steps to reproduce

1. Load this Gist in Script Lab in Word online: `https://gist.githubusercontent.com/gion-andri/45bedd2e91f90f10b0e016736ee9c81a/raw/d96f260409316c1c69a918dabebc22895c1e6e02/Search.WORD.yaml` in an empty document
2. Set up the content with the `Setup`button
3. click `Search special character` does not find "documentà" on the web, while it works on Word for desktop.

## Link to live example(s)

1. Script Lab: `https://gist.githubusercontent.com/gion-andri/45bedd2e91f90f10b0e016736ee9c81a/raw/d96f260409316c1c69a918dabebc22895c1e6e02/Search.WORD.yaml`

## Context

We are trying to find text positions in a document. We can't find them in Word online, as it does not work with words containing special characters. For non-english-users, that's a common use case.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by xiaoyuMS** [comment]
Hi @gion-andri 
Thanks for reporting this! It is a bug that also happens on Word Web find feature. 
![image](https://github.com/OfficeDev/office-js/assets/90585978/e3ca5b4d-2db3-49db-a12f-6bdff7ea032d)

An internal bug has been created VSO#7903643.
