### ISSUE TITLE
User mailbox converted to a shared mailbox doesn't work properly

### ISSUE THREAD

**Issue by somenathmaji** [OfficeDev/office-js#3361]
`Office.context.mailbox.item`  returns undefined on a shared mailbox which is converted from user mailbox.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2302
* Operating System: Windows 11
* Browser (if using Office on the web): N/A
 
## Expected behaviour
The OfficeJS APIs should return a valid object on `Office.context.mailbox.item` instead of undefined.

## Current behaviour
The OfficeJS API returns undefined on `Office.context.mailbox.item`.

## Steps to reproduce
1. Convert a user mailbox to a shared mailbox using `convert to shared mailbox` option which is available in M365 admin portal.
2. Open this mailbox in outlook (desktop or web)
3. Try `Office.context.mailbox.item` in console which returns undefined

## Context
We have customers who are using this option to convert an user mailbox to shared mailbox but getting above error. Is there any solution to properly convert an user mailbox to a shared mailbox?

The OfficeJS APIs should return a valid object on `Office.context.mailbox.item` instead of undefined. We tried with a new shared mailbox which is not converted from an user mailbox and on that shared mailbox OfficeJS is returning a valid object on `Office.context.mailbox.item`.

## Useful logs

- [ ] Console errors
![Screenshot 2023-05-16 at 3 20 49 PM](https://github.com/OfficeDev/office-js/assets/10449421/f401f3ec-91f4-49a8-ad30-c1c7943770fa)
- [ ] Screenshots
![Screenshot 2023-05-16 at 3 21 13 PM](https://github.com/OfficeDev/office-js/assets/10449421/f357d43a-c156-4331-a695-131ba2012dbb)

**Comment by exextoc** [comment]
Hi @somenathmaji, sorry for the delay. We are looking into the issue but not able to repro same yet. Will keep you posted. Thanks!

**Comment by exextoc** [comment]
Hi @somenathmaji, we don't have a solid repro at this point. Could you please provide a video of the steps you are following to repro this scenario? This will help us greatly in debugging. Thanks!

**Comment by somenathmaji** [comment]
@exextoc We couldn't reproduce this issue on our end. We have a customer and they are facing this issue in one of their shared mailbox which was converted from user mailbox.
Furthermore, we asked them to convert a test user mailbox to shared mailbox but they are not able to reproduce it in this mailbox.
Is there any other way the customer can escalate their issue with one of their shared mailbox?
