### ISSUE TITLE
Smart Alert transpiled with webpack not functional on Outlook desktop 

### ISSUE THREAD

**Issue by teejay001** [OfficeDev/office-js#3364]
Having followed the instruction to create an Add-In which use smart alert, I updated the code to inject the new launchevent.js file via webpack rather than copying the file directly into the dist folder. The app does not work on outlook desktop but works fine on OWA

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2304 (Build 16327.20248)
* Operating System: Windows 10
 
## Expected behavior
The Add-In should work as it does on OWA. There should be an alert to notify user that the attachment is missing from email message.

## Current behavior
The Add-In notification keeps spinning until it times out.

## Steps to reproduce
The steps to reproduce the issue has been listed here: https://github.com/teejay001/SmartAlert_Webpack/blob/main/Steps.txt

## Link to live example(s)

The repo contains the necessary code: https://github.com/teejay001/SmartAlert_Webpack/tree/main

# Provide additional details

The dist folder contains all the necessary resource to get the Add-In to function properly as seen on OWA.

## Context
Same business logic which would be applied on OWA cannot be applied on outlook desktop

## Useful logs
![image](https://github.com/OfficeDev/office-js/assets/99417649/efc323f7-9516-421a-bb24-caad0a211fe0)

**Comment by teejay001** [comment]
Hi @exextoc , any updates on this issue please? Thanks

**Comment by jlara005** [comment]
I am also having this same issue. This needs to work with the transpiled file @exextoc.

**Comment by millerds** [comment]
As noted on the help page https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest "Outlook on Windows uses a JavaScript file, while Outlook on the web and on the new Mac UI use an HTML file that can reference the same JavaScript file." which indicates that the two cases are using different runtimes to execute the JavaScript. 

Webpack injects a bunch of extra JavaScript into the file when it's served up and the runtime used in the desktop client doesn't support some of the code injected there.  You can see this extra code by comparing what is output into the dist folder by web pack vs. what is in the original js file.  By using the copy plugin in webpack we avoid the extra code injection.

**Comment by teejay001** [comment]
Thanks @millerds .

For anyone facing similar challenges, try using rollup for bundling. It's got it's own huddles but definitely an option going forward.
