### ISSUE TITLE
under some circumstances NamedItem.delete() is not working - office online only

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js#3365]
Hi, we have a multistage process that performs a number of actions... changes to custom XML properties, Range.clear(), and NamedItem.delete()

in our desktop applications - Windows and Mac - this works correctly.

online, everything works except the final NamedItem.delete().  I still see the named range in the online dropdown...

this disappears when reloading the document

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by JinghuiMS** [comment]
Thanks for reaching us. 
Could you provide repro video/gist/file with us for better understanding your scenario?
