### ISSUE TITLE
Outlook for Windows, Outlook for Mac: setSelectedDataAsync inserts text using the default font, size and color

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#3366]
# Provide required information needed to triage your issue
We are developing an Outlook add-in for compose mode and using the setSelectedDataAsync method to insert text into a message body. If the user selects a non-default font for composing an email, the setSelectedDataAsync method inserts text with the default (Calibri (Body) 11pt) font settings.

## Your Environment
* Platform: PC desktop, Mac
* Host: Outlook for Windows, Outlook for Mac
* Office version number: Outlook for Windows Version 2304 (Build 16327.20248 Click-to-Run), Outlook for Mac 16.71.2 (23032500)
* Operating System: Windows 10 Version 22H2, macOS Ventura 13.3.1
* Browser: ______
 
## Expected behavior
If the inserted text does not contain any HTML styles, setSelectedDataAsync shall insert text based on the style of the current paragraph where the cursor is placed.

## Steps to reproduce
1. Create a new message in Outlook for Windows or Outlook for Mac.
2. Enter some text to the body, select the text and change its font setting, say to Arial 20pt red.
3. Place the cursor in the middle of the entered text.
4. Open the add-in’s pane and execute the following code:

```
      Office.context.mailbox.item.body.setSelectedDataAsync(
        'text',
        { coercionType: 'html' },
        function (asyncResult) { console.log('done', asyncResult); }
      );

```
I have attached screenshots, please have a look.

# Provide additional details
In Outlook Online everything works normally. Also, this behavior has recently changed in Outlook for Windows and Outlook for Mac. In earlier desktop versions, it worked correctly.

## Useful logs
- [ x ] Screenshots
![image](https://github.com/OfficeDev/office-js/assets/28924916/e3b21ad0-f613-4c0a-9552-22dc5e13db56)

**Comment by Adrian-MSFT** [comment]
Hi @DmitryKostochko, If you would like to add text formatted to the existing text, you can do so using the Text coercion type

**Comment by DmitryKostochko** [comment]
@Adrian-MSFT, please test the code above in Outlook Online. The method works correctly there. Moreover, the method worked properly in Outlook Desktop a while ago, but now it applies the default Calibri font for some reason. Please check and fix this bug in Outlook for Windows and Outlook for Mac. Thank you.

**Comment by Adrian-MSFT** [comment]
Hi @DmitryKostochko , Can you provide what versions of Outlook for Windows kept the formatting with the above code? I was not able to keep the formatting in any of the older versions I tested

**Comment by DmitryKostochko** [comment]
@Adrian-MSFT, unfortunately, I don't have an exact version number.

**Comment by Adrian-MSFT** [comment]
Hi @DmitryKostochko , I was not able to reproduce this piece of code working on any of the older versions of outlook I tried. Additionally, we have documentation here ([Office.MessageCompose interface - Office Add-ins | Microsoft Learn](https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#outlook-office-messagecompose-setselecteddataasync-member(1))) stating that when inserting HTML, the content will be applied with the default style in the Outlook desktop client. We recommend you to upvote or create a new [Tech Community](http://aka.ms/M365dev-suggestions) item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue we will re-activate as needed.
