### ISSUE TITLE
Unable to add contentControl inside a table in Word online

### ISSUE THREAD

**Issue by docu-bill** [OfficeDev/office-js#3367]
In my add-in I create content inside a table cell and add a content control around it so I can find it later. This works well in the desktop app but does not work in Word online.

## Your Environment

* Platform: Word on the web
* Host: Word
* Office version number: online
* Operating System: Windows
* Browser (if using Office on the web): Chrome and Edge
 
## Expected behavior

I would expect the online to work as the desktop app does where I can add a content control to content inside a table cell

## Current behavior
A general error is thrown when I try to add a content control

## Steps to reproduce
1. Create a table
2. Place cursor in one of the cells
3. Insert some text and capture the Range
4. call insertContentControl on the Range

## Link to live example(s)
See [Script Lab Gist here](https://gist.github.com/docu-bill/28ebf0baccbe81fc20303e37f837c6fa)

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by docu-bill** [comment]
This problem goes away if the user selects the whole cell not part of the contents... but I do not understand how this changes the outcome as I get the paragraph as: 
`const paragraph: Word.Paragraph = context.document.getSelection().paragraphs.getFirst()`
Shouldnt the same paragraph be returned whether the user selects the whole cell or just clicks in a cell?

**Comment by xiaoyuMS** [comment]
Hi @docu-bill 
Thanks for reporting this~ It is the same paragraph but the Word Web checks the selection when inserting content control. The two ways you mentioned are different selections: the first is an insert point inside the table cell and the second is a whole table cell. We support selecting the whole table cell.

I have created a work item for internal tracking VSO#7907868.

As a workaround, could you try the code like:
```
const paragraph = context.document.getSelection().paragraphs.getFirst();
paragraph.select();
paragraph.insertContentControl();
```

**Comment by docu-bill** [comment]
Thankyou this workaround works for me now
