### ISSUE TITLE
How to select grouping row position (e.g. top/bottom) 

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js#3368]
Excel (desktop) has the options here ->

![image](https://github.com/OfficeDev/office-js/assets/2139941/02ba640d-886d-40d8-b831-8341d6b278c0)

is there an API to adjust whether the 'group' row for an outline is at the top / bottom. (or left / right for columns)

## Microsoft 365 Developer Platform Ideas Forum

We're moving away from UserVoice feedback sites on a product-by-product basis throughout the 2021 calendar year. Later in 2021, we will leverage a 1st party solution for customer feedback. Meanwhile, please post feature requests and suggestions at the [Microsoft 365 Developer Platform Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). 

For more information, see [UserVoice pages](https://support.microsoft.com/topic/uservoice-pages-430e1a78-e016-472a-a10f-dc2a3df3450a).

**Comment by jipinshi** [comment]
Sorry, no such API supported the asking function. All supported group related function are documented here: https://learn.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#excel-excel-range-group-member(1)

**Comment by theboyknowsclass** [comment]
can this be added as a feature request... we need to be able to change this programatically?

**Comment by jipinshi** [comment]
You can add the feature request here https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform, it will be prototized
