### ISSUE TITLE
[Word] ContentControl remove keepContent parameter not respected

### ISSUE THREAD

**Issue by rvanlaak** [OfficeDev/office-js#337]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
Thank you for your understanding and continued feedback.

## Expected Behavior

ContentControl should get removed, and content should get preserved.

## Current Behavior

ContentControl does not get removed, and stays preserved.

## Steps to Reproduce, or Live Example

```js
Word.run(async (context) =>
{
    const serviceNameRange = context.document.getSelection();
    const cc = serviceNameRange.insertContentControl();

    let ooxml = cc.getOoxml();

    await context.sync();

    cc.insertOoxml(ooxml.value, "Replace");
    cc.delete(true);

    return context.sync();
})
.catch((error) =>
{
    console.log("Error: " + error + JSON.stringify(error.debugInfo));
});
```

## Context

When running above script from an addin, the content control is not deleted. The `keepContent` with value `true` is not respected. No exception is thrown.

* https://docs.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=office-js#delete-keepcontent-

## Your Environment

* Platform PC desktop
* Host Word
* Office version number: 365
* Operating System: Win
* Browser (if using Office Online): ______

## Useful logs

![image](https://user-images.githubusercontent.com/2707563/50215070-3c12af00-0382-11e9-9d67-2a83201bf766.png)

**Comment by rvanlaak** [comment]
Any update on this bug report?

**Comment by calbrecht** [comment]
You should try `cc["delete"](true);` instead of `cc.delete(true);`
--edit My guess is, that is because `delete` is a [reserved keyword](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/ttyab5c8(v=vs.100)) however, it is unclear to me why this only breaks in chrome and edge 49, and also why it does not function but also not error.
