### ISSUE TITLE
"Shared Folder" option no longer appears after Office update

### ISSUE THREAD

**Issue by javierb13** [OfficeDev/office-js#3370]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2303 (Build 16227.20318) this was pushed out by IT but my Excel says Microsoft Excel for Microsoft 365 MSO (Version 2303 Build 16.0.16227.20202) 32-bit
* Operating System: Windows 10 Enterprise
* Browser (if using Office on the web): ______
 
## Expected behavior
I was expecting for the Shared Folder to still be available to side load Excel applications for local development.

## Current behavior
In Excel Desktop, the Shared Folder (Insert Tab -> Get Add-in's) has completely disappeared after IT pushed out an Microsoft 365 update. I still see the Admin Managed Section though.

# Provide additional details
Over the last few days developers at my company have started losing access to the side loaded apps that we were developing. I noticed that I did not have the same issues and was able to still access those side loaded apps from our Network Share. I still had access to "Shared Folder" but the others no longer were able to find the options when trying to add the Excel Add-in. Turns out I did not get the update that was pushed from IT yet. The version I had (that was working) was Version 2302 Build 16.0.16130.20374. I then received the update to Version 2303 Build 16.0.16227.20202 and lost the option to use/add the network share via "Shared Folder".

## Context
We can no longer side load apps and continue development easily. The developers aren't Office 365 Admins and we have a lengthy approval process to get any manifests into the Admin Shared section just for new development. IT is telling us its because of the recent office update that helps to reduce malware with office Add-ins. I'm not sure if that is true or if IT accidentally disabled the feature. Hoping someone can guide me down a path.

## Useful logs
Image below is the Shared Folder tab that has disappeared
![image](https://github.com/OfficeDev/office-js/assets/6811247/1caa1f1d-d7c2-4451-bec0-cb05ccbba359)

Image below was after the Office update was pushed to my machine. Shared Folder no longer visible
![image](https://github.com/OfficeDev/office-js/assets/6811247/34b98275-aac5-4b66-95a1-725d2f0e15c3)

**Comment by javierb13** [comment]
@JinghuiMS was wondering if this was looked at yet or am i missing something? thanks

**Comment by XuanZhouMSFT** [comment]
Hi @javierb13, Thanks for the waiting. I tried it locally and couldn't repro this simply. Could you help tp share with us any simple repro step if you still have the issue?

**Comment by GabrielHangor** [comment]
@javierb13 Any luck fixing this?

**Comment by javierb13** [comment]
Yeap, it ended up being an update Microsoft did that disabled the feature by default. There are some features the office 365 admin can enable. I cant remember exactly but theres a place for the Trusted Catalog locations. We needed to add the network share path in there. Once we added that, the feature appeared in excel again.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
