### ISSUE TITLE
Outlook add-in for an online-meeting provider

### ISSUE THREAD

**Issue by Sivanyan** [OfficeDev/office-js#3371]
## Post how-to questions about your code on Microsoft Q&A
Our Outlook add-in adds a URL meeting to the event calendar's body. 
In addition, we would like to add our provider to this list:
<img width="309" alt="image" src="https://github.com/OfficeDev/office-js/assets/105422195/d74096d6-a7d5-4135-847a-f4e553608242">

First I followed this guide: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting?tabs=non-mobile#implement-adding-online-meeting-details

1.  According to the instructions here, we will see the provider in the list I presented above? 
2. I expected to see this toggle change to:
3.  <img width="241" alt="image" src="https://github.com/OfficeDev/office-js/assets/105422195/542c6350-014f-402b-937e-5e9348be783e">
after following the instructions in the guide I mentioned, but it didn't change, 

<img width="200" alt="image" src="https://github.com/OfficeDev/office-js/assets/105422195/1f099f4f-c764-4f1e-a752-edad1815332e">

how can it be changed?

**Comment by exextoc** [comment]
@Sivanyan Sorry for the delay. We are analysing the best course of action internally and will keep you posted as soon as we have an update.

**Comment by yjoshi-msft** [comment]
Hello @Sivanyan ,
Thank you for reaching out. Wanted to understand which platform/device you were testing this on. Please do share the details

Additional clarifications - 
1. Following the steps in the link show your add-in on the appointment compose surface
2. Meeting toggle is currently available only on mobile devices
3. Add online meetings to all meetings is currently a limited feature and the feasibility of more add-ins being added to it is currently under analysis
