### ISSUE TITLE
Outlook addin sendmail not blocking after 2 times.

### ISSUE THREAD

**Issue by mkondadg** [OfficeDev/office-js#3373]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:  Ventura 13.2
* Host [Excel, Word, PowerPoint, etc.]:  Outlook
* Office version number: 16.73
* Operating System: MacOS

 
## Expected behavior

Block should happen irrespective of how many times sendmail is clicked.

**Steps to reproduce the issue**

Deployed addin from sample : 
https://github.com/OfficeDev/Outlook-Add-in-On-Send/tree/master/outlook-add-in-on-send

modified app.js in zip file to block for every send mail (attached modified file)
[app.js.zip](https://github.com/OfficeDev/office-js/files/11513296/app.js.zip)

Send mail blocked - 1st try
Send mail blocked - 2nd try
Send mail NOT blocked - 3rd try

demo:

https://github.com/OfficeDev/office-js/assets/62250655/d39f867f-9b91-4494-99d4-f3d12c5d38e7

**Comment by mkondadg** [comment]
Observed that addin callback function is not called by Outlook.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding block on-send addins. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 3633762

**Comment by exextoc** [comment]
@mkondadg Fix for this issue has been made and is live. Can you please verify if the issue still exists for you? Thanks for your patience!

**Comment by mkondadg** [comment]
@exextoc I tested a few times and it seems to be working.
We will do a bit load testing and let you know again.

Thanks for the quick turnaround.
