### ISSUE TITLE
Encrypted mails cause add-ins to fail for OWA/New Outlook

### ISSUE THREAD

**Issue by exclaimer-support** [OfficeDev/office-js#3374]
Issue
When you reply to an Encrypted mail in OWA or New Outlook mode, Add-in will either not open or not load.
This apples to ALL Add-in's
It would seem that Encrypted mails stop Add-ins from loading.

Reproduction Steps:

Make sure you have a Client Side signature configured along with the Add-in deployed. 
Log into OWA or use Outlook in New Mode.

Send an Encrypted Mail.
Click Reply to the received Encrypted Mail 
Click any Add-in, the side panel will not open (or if the Add-in had been previously opened, it will Open but cannot load)

Attempt to open any other Add-in within OWA or Outlook New Mode. 
The Add-in will not load.

**Comment by exextoc** [comment]
Hi @exclaimer-support, we currently do not support add-ins for IRM emails on OWA. We would take this as a feature request. We track Outlook add-in feature requests on our Tech Community Page. Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process. Github Label: “Type: product feature request” [aka.ms/M365dev-suggestions](https://aka.ms/M365dev-suggestions)
