### ISSUE TITLE
Correct way to detect the browsers that we don't support (IE11 and Microsoft Edge Legacy)

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#3375]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hello,

We have an Office add-in. A part of our visitors (in particular who have Office 2019) keep seeing a blank page when opening the add-in.

By following [this thread](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11?tabs=ie), we have added the following code to the page that our primary button launches.

```
render() {
    const versionProblem = 
      <div>This add-in won't run in your version of Office. 
      Please upgrade to either one-time purchase Office 2021 or to a Microsoft 365 account.
      You could also try Office Online.
      </div>

    console.log('Browser in use, navigator.userAgent.indexOf("Trident")', navigator.userAgent.indexOf("Trident"));
    console.log('Browser in use, navigator.userAgent.indexOf("Edge")', navigator.userAgent.indexOf("Edge"));

    if (navigator.userAgent.indexOf("Trident") !== -1) {
      // https://github.com/OfficeDev/office-js/issues/2463#issuecomment-1082662125
      console.log("Browser in use, IE11 is the browser in use.")
      return versionProblem
    } else if (navigator.userAgent.indexOf("Edge") !== -1) {
      console.log("Browser in use, Microsoft Edge Legacy is the browser in use.")
      return versionProblem
    }
    ... ...
    ... ...
```

However, this did not solve the problem. A user just showed me that he had a blank page, and I asked him to click on "inspect" and search for "browser" under "console", here is what he saw:

![7b9dc5d6-e7a9-4504-b680-2bc6961d9d0a](https://github.com/OfficeDev/office-js/assets/774409/1dc0ef91-7f52-4ab6-8971-72d791918ea1)

This shows that the conditions in the code cannot rule out all the browsers that we don't support. I'm wondering if this method proposed by the learn.microsoft.com is exhaustive. Does anyone know what's the correct way to detect the browsers that we don't support (IE11 and Microsoft Edge Legacy)?

**Comment by mrebuffet** [comment]
Hi @chengtie, 

We also have an add-in and are going through the same exercise at the moment, and we were planning to implement a similar technique. 
We also looked at this documentation: https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins#microsoft-365-subscription-versions-of-office-on-windows to check if the Outlook client version can use Webview2 or not and therefore run our add-in on Windows. 

Would you please be able to share the full value returned by `navigator.userAgent` from the browser of your user that cannot run your add-in? 
Also I think it might help the Office team if you could get the value of `Office.context.diagnostics`

Thanks
