### ISSUE TITLE
document.getElementById is not working on Mac outlook

### ISSUE THREAD

**Issue by zjmchoi** [OfficeDev/office-js#3376]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Currently, I am developing an Outlook Add-in.
1. Goal:
   - The goal is to work with same code in both Outlook Web (chrome, edge, safari) and Outlook Application (Mac, Window), except Outlook mobile..
   - I have a Microsoft 365 account and use Javascript. (not jQuery)
2. Scenario:
   (1) Using "Office.context.mailbox.item.body.setAsync(‘test’, ….)", I write the following text in mail body.
         -> const test = `<div id=“test”><p><strong>hello world</strong></p></div>`;
   (2) Using "Office.context.mailbox.item.body.getAsync(“html”, ….)", I am trying to edit the text ("hello world") written in the mail body.
         (a) bodyStr = asyncResult.value;
         (b) const parser = new DOMParser();
         (c) const document = parser.parseFromString(bodyStr, 'text/html');
         (d) const testElement = document.getElementById(‘test’); <— do not get only in Mac Outlook.
3. Issue:
    * Currently, this test does not work only in Mac Outlook.
4. Version:
    (1) Microsoft Outlook for mac: version 16.73 (23051401)
    (2) Mac OS: Ventura (13.2.1), 
    (3) MacBook Pro (apple M1 Pro)

**Comment by exextoc** [comment]
@zjmchoi Thank you for raising this issue. The fix for this issue will be checked in soon. This change would be going in with some other bigger fixes in the editor behavior on Outlook Mac and will take a couple of months to be available.

**Comment by thad0ctor** [comment]
Why was this closed without resolution?  This functionality is critical for add-ins that insert text but need to revise the inserted text

closed this as [not planned]
