### ISSUE TITLE
Outlook add-in to capture cancel/delete meet event

### ISSUE THREAD

**Issue by wsmPanda** [OfficeDev/office-js#3377]
Is there any way we can capture the cancel meet event in outlook add-in Office js API

And cancel to send should be an action for Send Message, but OnMessageSend also can't capture it.

**Comment by exextoc** [comment]
@wsmPanda Can you share more details on what do you mean by "cancel meet event" and "cancel to send" to understand your requirements clearly? Is it possible to share screenshots of scenarios you are mentioning?

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
