### ISSUE TITLE
Custom ribbon is not working on the first click but requires users to click twice.

### ISSUE THREAD

**Issue by shaun-pendrigh** [OfficeDev/office-js#3378]
I found this issue (https://github.com/OfficeDev/office-js/issues/1029) and commented there but it is closed so creating a new issue.

I am running a shared runtime and have a taskpane as well as some other command buttons. If I open the taskpane first, then everything works as expected. However if I click one of the command buttons first, that only seems to trigger initializing the Add-In. The command action does not run. If I click a second time then the command action executes.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2304 Build 16.0.16327.20200) 64-bit
* Operating System: Windows 11
* Browser (if using Office on the web): N/A
 
## Expected behavior
When clicking a command bar toolbar button the action should run on the first click.

## Current behavior
Clicking a command bar button as the first interaction with the add-in does nothing, but only seems to trigger initializing the Add-In. The command action is not executed.

## Steps to reproduce

1. With an Add-in that has a taskpane and a command bar button, click the open taskpane button first, taskpane should open
2. Click the command bar button, action executes.
3. Start the Add-In again, this time click the command bar button first, nothing seems to happen, the action is not executed.
4. Click the command bar button again, the action is executed.

## Link to live example(s)
1. Should be reproducible in any Add-in

# Provide additional details
1. ______
2. ______
3. ______

## Context
It is very confusing for the Add-In users if they sometimes need to click the toolbar button twice before anything happens. Please can you confirm if this is a bug or if I am missing something about how this is supposed to operate. Thanks

**Comment by trigurl** [comment]
Hi just to clarify so that I can repro, you have an Add-in that is SharedRuntime that has at least 2 buttons in the Ribbon?  One button will launch a taskpane and the other is an ExecuteAction that does something?

Thanks Angela

**Comment by shaun-pendrigh** [comment]
@trigurl, thanks yes that is correct. I have not tried recreating this situation in a yo office template yet. But I can clearly see from my application that the action is not called on the first click by adding some logging.

**Comment by trigurl** [comment]
Hmm, I just tried this out and it's working fine for me. 

Can you try the following things:
1) https://devblogs.microsoft.com/microsoft365dev/announcing-changes-to-office-add-ins-executefunction-commands/ 
2) Also verify that your function calls event.complete() when it is finished, important for ExecuteAction.

If none of this address your issue, you might need to send me a simplified version of your manifest with the 2 buttons. Strip out any privacy and corporate information.  You can fill in the URLs with dummy data.  I just want to see the structure of what you have.

**Comment by shaun-pendrigh** [comment]
Thanks Angela. I will review and if I cannot resolve the issue I will create a simple example where the issue can be reproduced. This may take some time as I have some other project commitments but I will respond. Thanks.

**Comment by shaun-pendrigh** [comment]
@trigurl I have created a yo office example (Excel Custom Functions using a Shared Runtime) and added a command bar button to the manifest and added some code to execute. In this example the code does run after some time. It takes a while seemingly for the embedded browser to load the html page but after that the code does execute. On my PC one has to wait for about 8 seconds.

In my application the action never executes. I am still not sure why. My application is very different using a node server and being structured very differently to the yo office webpack based example.

I will continue to try and narrow it down, thanks for your help. I guess we can close this issue?

**Comment by shaun-pendrigh** [comment]
Actually if we can keep this open for another while, I will try and create a simple example using a node server and see if I can reproduce the issue. Thanks

**Comment by shaun-pendrigh** [comment]
Cannot recreate reliably so closing.

**Comment by nickamckenna** [comment]
I can reliably repeat this and I have created a new bug report https://github.com/OfficeDev/office-js/issues/5176 with a very simple demo project.
