### ISSUE TITLE
Please make it possible to add dynamic items to Ribbon Control

### ISSUE THREAD

**Issue by YekaterinaBindyuk** [OfficeDev/office-js#3379]
Please make it possible to add dynamic items to Ribbon Control. 
Office.ribbon.requestUpdate currently can only be used to enable/disable buttons and change visibility of tabs. It would be very helpful if we could also use it add items to a control or change its labels.

**Comment by akshayta23** [comment]
Hi @YekaterinaBindyuk - Can you please share more details about the feature request such as the platform and specific issues faced? Additionally, for new feature requests, please submit it here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

**Comment by larsschenk** [comment]
> Hi @YekaterinaBindyuk - Can you please share more details about the feature request such as the platform and specific issues faced? Additionally, for new feature requests, please submit it here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

The feature request was perfectly clear. All platforms affected. Specific issue faced is like it was written: "Office.ribbon.requestUpdate currently can only be used to enable/disable buttons and change visibility of tabs. It would be very helpful if we could also use it add items to a control or change its labels."
