### ISSUE TITLE
[Word] image dissapears when adding contentcontrol

### ISSUE THREAD

**Issue by rvanlaak** [OfficeDev/office-js#338]
Image gets hidden when content control is added to it, and `insertOoxml` thereafter is called with it's own ooxml value.

## Expected Behavior

Image should have a `contentcontrol` and stay on the same place, as when the line `cc.insertOoxml(ooxml.value, "Replace");` gets commented out.

## Current Behavior

Image dissapeared, changing image layout option shows it again.

## Steps to Reproduce, or Live Example

Select image and let following script run

```js
Word.run(async (context) =>
{
    const selection = context.document.getSelection();
    const cc = selection.insertContentControl();

    let ooxml = cc.getOoxml();

    await context.sync();

    cc.insertOoxml(ooxml.value, "Replace");

    return context.sync();
})
.catch((error) =>
{
    console.log("Error: " + error + JSON.stringify(error.debugInfo));
});
```

## Context

When opening Word document with image and text, and selecting the image, the above script lets the image get hidden.

## Your Environment

* Platform PC desktop
* Host Word
* Office version number: 365
* Operating System: Win 10
* Browser (if using Office Online): ______

## Useful logs

![bug-contentcontrol-image](https://user-images.githubusercontent.com/2707563/50215858-7da45980-0384-11e9-9f1c-658094554cea.gif)

**Comment by JuaneloJuanelo** [comment]
I was able to repro and will lookin into it. seems tobe that the OOXML gets beyond the image.
THere is a workaround: did you tried wrapping the selected image ? this code should work 


```
async function run() {
    await Word.run(async (context) => {
        var cc = context.document.getSelection().inlinePictures.getFirst().insertContentControl();
        let image = cc.inlinePictures.getFirst().getBase64ImageSrc();

        await context.sync();

        cc.insertInlinePictureFromBase64(image.value, "replace");
       
        await context.sync();
    });
}
```

**Comment by rvanlaak** [comment]
"replace" is not an option for us, because our users always work with track-changes enabled. As result of that, the image gets seen as removed and inserted.

So, as long as programmatically enabling/disabling track-changes is not possible via the API, using the workaround is not a solution. Meaning, this bug does not have a workaround.

**Comment by rvanlaak** [comment]
Any update on this bug report?

**Comment by ElizabethSamuel-MSFT** [comment]
@JuaneloJuanelo Can you provide an update for this? Thanks.

**Comment by JuaneloJuanelo** [comment]
> Any update on this bug report?

I got the "replace" option  from your code :).  Say we fix the positioning issue, you will have the same problem with your code if track changes is active, you are ultimately replacing an image.  My post gives an alternative to select an replacing an Image within a content control and its by design that this will be reflected in track changes. 

if you can adjust your  scenario and snippet so  that does not include replace we can provide further assistance.

**Comment by rvanlaak** [comment]
The use-case in the issue as demonstrated via the snippet isn't a real world use-case, but narrows down the bug to the minimum required code.

As this issue was reported in december 2018 it seems there isn't any development in Office JS for Word. This is unfortunate, as it means we can not rely on it. Because of that we moved on.

**Comment by JuaneloJuanelo** [comment]
The main gap on this issue is to include the track changes API  in word.js. Since this is already in our backlog, this issue will be closed.
