### ISSUE TITLE
Custom Streaming Function (Excel) - Invocations not firing with quick changes

### ISSUE THREAD

**Issue by jjwoma** [OfficeDev/office-js#3383]
I have a use case where one of my custom formulas fires an API POST to write data to our backend database.

With this formula, if an auto send formula parameter is set to true, the formula execution will directly invoke the API call. If the parameter is set to false, we hold the value and send later, with a button click. For the deferred calls we utilize the invocation's setResult() method to keep itself current - so this is a streaming function.

We are finding that if we have a large number of these formulas in a sheet, and we set the parameters to one value, and quickly set the parameters back to the original value our backend data gets out of sync. This is because Excel fires the invocation for the first change, but does not trigger the reverting back invocation and seemingly uses its own cached results.

In this scenario, our backend API is only called for the first wave of changes, and is never called on the second wave (the reverting back) of changes.

Simple Example: where the first excel argument/parameter is the value to send to the database, and the second parameter is the auto send flag)

- Existing/original state of the formula with its parameter values:
`custom_function("value 1",true)`

- First wave of changes:
`custom_function("value 2, true)`

- Second wave (reverting) of changes:
`custom_function("value 1, true)`

It should be noted that doing this scenario with just one formula, the process works as expected because both executions seem to fire new invocations. It is only when I have a sheet that has the 1,000 formulas linked to one another in a cascading fashion does Excel not fire distinct invocations and instead seems to use its own cached value to get back to the reverted values (the reversion happens immediately, and console logs prove that the second invocation is never fired).

Given this behavior, it seems like there should be a way for me to tell the particular invocation(s) to not use a cached value and/or force it to fire unique invocations on every change.

**Comment by Rick-Kirkham** [comment]
This is a problem with the platform rather than the documentation for the platform, so I'm going to try and transfer it to the office-js repo.
