### ISSUE TITLE
9020  An internal error has occured while Office.context.mailbox.item.body.getAsync(Office.CoercionType.Text, (result) => {..}) 

### ISSUE THREAD

**Issue by ANovitsky** [OfficeDev/office-js#3384]
The code work well in Outlook for Desktop and for Outlook Web, but doesn't work for Windows Mail App (option is New Outlook).

Script is https://appsforoffice.microsoft.com/lib/1/hosted/Office.js

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Windows Mail App (option is New Outlook)
* Operating System: Windows
 
## Expected behavior
Get the body

## Current behavior
Office.context.mailbox.item.body.getAsync(Office.CoercionType.Text, (result) => {..})
Get an error  

## Steps to reproduce
1. Open any email
2. Open the plugin panel 
3. Try call Office.context.mailbox.item.body.getAsync

**Comment by exextoc** [comment]
@ANovitsky Thanks for reaching out. We cannot repro this on our end. Can you please help us with the following information:
1) Can you please elaborate the error details you are receiving?
2) Are you facing this issue both while reading and composing a new mail?
3) Can you repro this consistently? If possible, can you please share a video of repro?
