### ISSUE TITLE
makeEwsRequestAsync resulting in "Internal protocol error"

### ISSUE THREAD

**Issue by liamtim** [OfficeDev/office-js#3386]
# Provide required information needed to triage your issue

We have an Outlook Web Add-in that has a function which "Counts" the number of recipients present in the "To" field of a draft. (including DL memberships etc). 

Our add-in has been live for several years without issue, however we are now experiencing unexpected behaviour on Outlook for Mac "New UI"

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.73.1
 
## Expected behavior
The function is called with the payload below, and an expanded DL is returned

## Current behavior

**We are calling this function:**
`Office.context.mailbox.makeEwsRequestAsync`

**And passing it this soap payload:**
`<?xml version=\"1.0\" encoding=\"utf-8\"?><soap:Envelope xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"               xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"               xmlns:m=\"http://schemas.microsoft.com/exchange/services/2006/messages\"               xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\"               xmlns:t=\"http://schemas.microsoft.com/exchange/services/2006/types\">   <soap:Header>       <RequestServerVersion Version=\"Exchange2013\" xmlns=\"http://schemas.microsoft.com/exchange/services/2006/types\" soap:mustUnderstand=\"0\" />   </soap:Header>   <soap:Body><m:ExpandDL>    <m:Mailbox>        <t:EmailAddress>[users@domain.ca](mailto:users@domain.ca)</t:EmailAddress>    </m:Mailbox></m:ExpandDL></soap:Body></soap:Envelope>`

**And receiving this error in response:**

`"{\"status\":\"failed\",\"error\":{\"name\":\"AccessRestricted\",\"message\":\"Internal protocol error: '-2147467259'.\",\"code\":9017}}"`

Please note, the distribution list we are using has been redacted from the soap payload

## Steps to reproduce

1. Switch your "From" address to a delegate mailbox
2. Include a Distribution list in the "to" field
3. Call the function outlined above

## Context
Customers who update to Outlook for Mac new UI can not use our platform. 
Switching back to Old UI works as expected
Outlook on Windows Works as expected
OWA works as expected

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@liamtim Thanks for reaching out.
For Shared folders, makeEwsRequestAsync is deprecated for MAC and is on path of depreciation for Owa as well. It is advised to make HTTP requests to the appropriate Microsoft Graph API endpoints to perform operations similar to makeEwsRequestAsync().

For configuring the add-in to call Graph APIs: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/authorize-to-microsoft-graph
Possible HTTP request for DL expansion can look something like:
"GET https://graph.microsoft.com/v1.0/groups/?$filter=mail+eq+'DL@example.com'&$expand=members"

Thanks!

**Comment by liamtim** [comment]
@exextoc We are able to migrate to Graph API for expansion, however it appears that Graph API does not support the expansion of Dynamic Distribution List (even when created on Exchange Online). 

How can this scenario be dealt with? Will Graph API have the ability to query these types of lists in the future?
