### ISSUE TITLE
fully support of customUI?

### ISSUE THREAD

**Issue by oldoldman** [OfficeDev/office-js#3389]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi guys,
How about fully support of the functionalities of office com addon ```customUI```(http://schemas.microsoft.com/office/2009/07/customui)? For example, I would like the functionality of imageMso and ribbon controls of checkBox/splitButton/gallery etc. these are all absent from office-js add in. Many thanks!

**Comment by akshayta23** [comment]
@oldoldman Can you please provide more details about the feature request? The link shared above isn't working as expected.

**Comment by oldoldman** [comment]
> @oldoldman Can you please provide more details about the feature request? The link shared above isn't working as expected.

the link is just the xml namespace for Office custom UI which I'm using as an eyecatcher. Yon can refer to [this](https://learn.microsoft.com/en-us/openspecs/office_standards/ms-customui/31f152d6-2a5d-4b50-a867-9dbc6d01aa43) and [this ](https://learn.microsoft.com/en-us/openspecs/office_standards/ms-customui2/bad56c21-7b15-41bc-af32-8b5afe6e922e)document for details. 
custom UI is the mechanism used by Office com addon to tailor the Office command bar which I want available in Office-js.

**Comment by akshayta23** [comment]
@oldoldman Request you to submit new feature requests here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
