### ISSUE TITLE
APIs to react to cell hovering

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#3397]
Hello,

I understand that there are several event listeners in Excel JavaScript API. For instance, `Office.EventType.DocumentSelectionChanged` is about the change of selection.

I would like to know if there is any APIs or way to react to hovering over a cell. For instance, when the user hovers over a cell, an event is triggered.

Thank you

**Comment by SiruiSun-MSFT** [comment]
Hi @chengtie, 
The feature: APIs to react to cell hovering, as you requested, is not a part of the product. We provide several APIs to track selection change (onSelectionChanged Event) of Workbook, Worksheet, Table, Binding... Here is the sample link: https://learn.microsoft.com/en-us/javascript/api/excel/excel.workbook?view=excel-js-preview#excel-excel-workbook-onselectionchanged-member. 
If these APIs cannot meet your request, we track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests are considered when we go through our planning process. Thanks for letting us know this issue!
