### ISSUE TITLE
Every addin with a sidebar is not loading at all on OWA

### ISSUE THREAD

**Issue by daneshd** [OfficeDev/office-js#3399]
# Provide required information needed to triage your issue

On OWA when composing a new email, every addin that should be opening a sidebar is not working at all. Clicking on any addin from OWA results in nothing happening. The sidebar does not open and nothing appears to happen. There is no issue with Outlook on Desktop for Mac/PC, it's only occurring with OWA. It is happening in every browser we try. The [Polls addin](https://appsource.microsoft.com/en-us/product/office/wa200000114?tab=overview&exp=ubp8) isn't even loading when we try either.

My company has an addin we have built and published to app source so we have several customers in other companies using our addin. This issue is widespread amongst our entire customer base. We've received recordings from our customers trying clicking on **any** addin and none of them are working. Just to reiterate, it's not isolated to our addin. Several of my colleagues are able to reproduce this issue as well.

We observed that it was working on Chrome `Version 113.0.5672.92 (Official Build) (64-bit)` but after updating to version 114, it stopped working. We suspect this has something to do with the problem we're seeing.

I have tried making issues with the Office Admin Portal and Support Desk services but have had no luck. If this is not the correct place to report this problem, please can you direct me to where I should report it? 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: OWA
* Operating System: Windows and Mac (tested on both)
* Browser (if using Office on the web): All browsers 
    * Chrome: `114.0.5735.90/91` on Windows and `114.0.5735.90` on Mac
    * Edge: `Version 113.0.1774.57 (Official build) (64-bit)`
    * Firefox: `113.0.2 (64-bit)`
 
## Expected behavior

Clicking on any addin loads the addin's sidebar.

## Current behavior

Clicking on any addin does not load the sidebar. Nothing happens when you click the button. There are no network requests in web dev tools, there's nothing being triggered. 

## Steps to reproduce

1. Click on any addin that loads the sidebar
1. Observe it does not open the sidebar 

## Link to live example(s)

- [Here is a screen recording](https://drive.google.com/file/d/1-TC7-393VGtEXG7DFEaC5jRuYuAtjSTa/view?usp=drive_link) of me attempting to load multiple addins on Edge.
- I have my web dev console open and switch between the Network and Console tabs
- Please ignore the errors of the `localhost` requests, those are from my local addin that I installed and the server is not running
- However, as you can see, I've clicked on several addins such as Polls, Salesforce, Hubspot and none of them work. I clicked several times as well. 
- There are no network requests being triggered and there are no console logs/errors either

## Context

1. This is widespread amongst my organization and amongst other companies that use our addin
1. One of my colleagues was able to use the addin on Chrome version 113 but then updated to Chrome version 114 and it stopped working. Chrome released this yesterday/today (May 31/June 1, 2023)
2. We've only been testing addins while composing new emails, I'm not sure if that might be part of the problem 
3. All these addins (including our own) work perfectly fine on Outlook for Desktop on Windows and Mac

## Useful logs

- [x] Console errors
- [x] [Screen recording here](https://drive.google.com/file/d/1-TC7-393VGtEXG7DFEaC5jRuYuAtjSTa/view?usp=drive_link)
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@daneshd Thanks for reporting the issue. We are able to repro and are looking into this. Meanwhile, we have observed that if we open any mail once before trying to compose a new mail in a new session, then the taskpane add-ins work as expected while composing. Can you please confirm if this holds true for you as well?
Also, can you please help us with following information: 
1) OWA version that you are observing this issue on? 
2) Are the add-ins working fine when reading a mail for you?
3) Are you on first release channel or Prod?

**Comment by daneshd** [comment]
@exextoc opening a mail and then going to compose worked for me! I noticed it was only an inbox mail. I tried one from deleted/archived and that didn't work at first.

1. How do I check my OWA version? Apologies, I've never had to do this and googling hasn't given me instructions
2. I didn't have an add-in that is available in the reading pane. I've added one but we've been seeing it takes ~3 hours for it to load in OWA (it loads immediately on Outlook Desktop though)
3. I don't have admin access to check that but I imagine our company is using whatever the default version is. Is there a way for me to check as a non-admin?

**Comment by carlosb1504** [comment]
Also seeing this issue from this morning. Would appreciate an update on when we can expect a fix.

Can confirm that browsing an inbox message prior to opening a new mail does resolve the problem.

On Current Channel

**Comment by cody-lettau** [comment]
We are also seeing this.

**Comment by Howard-Song** [comment]
Also meet this issue, open a mail then new compose can load add-in.

**Comment by exextoc** [comment]
@Howard-Song , @cody-lettau , @carlosb1504 , the concerned team is looking into it with priority. We will let you know as soon as we have a fix.
@daneshd 
For finding outlook web version and channel - append view-source: to your outlook web url in the address bar. For example: view-source:https://outlook.office.com/mail/ .
In the source , search for "meta name=scriptVer" . This will give the version. 
"meta name=physicalRing" and "meta name=environment" will give the ring and channel.

**Comment by daneshd** [comment]
@exextoc 

```xml
<meta name=scriptVer content=20230526012.09>
<meta name=physicalRing content=WW>
<meta name=environment content=Prod>
```

**Comment by exextoc** [comment]
@daneshd , @cody-lettau , @carlosb1504 , @Howard-Song ,
We have fixed this issue and it is being rolled out. It should be available latest by tomorrow. In case you still face this issue, then please clear your cache and do a hard refresh and try again.

**Comment by exextoc** [comment]
Closing this issue as fixed.
