### ISSUE TITLE
Error 13008, function getAccessTokenAsync  still running

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#340]
getAccessTokenAsync runs for the first time, but on a slow connection/when it gets spammed the function keeps running without receiving a response. The second time getAccessTokenAsync is supposed to run, it does not run again, because a token has already been requested for and I get the error message shown below.

The error message:
![image](https://user-images.githubusercontent.com/11733366/50230082-392cb400-03ac-11e9-9c14-2a616a7d9125.png)

The error name says "A token has already been requested for this add-in." and message says "The function has failed, because a token has been requested for this add-in."

The way I have found to fix this is by refreshing the add-in completely, not only by reloading the frame. I would prefer if there is a method to fix this problem, instead of refreshing it.

**Comment by keyur32** [comment]
@niteshgolchha85  can you take a look to see if this is still an issue. It may need an update from the author as well.

**Comment by niteshgolchha85** [comment]
@lokkwanfoo Can you confirm if you are able to repro the issue consistently? 13012 would probably mean that AAD is still in the process of providing an access token and when you requested again, it rejects the call as it is still processing the first request. This seems unusual and I'd like to know if you're able to repro the issue consistently. Also, can you provide your environment details?
