### ISSUE TITLE
Excel showing "Something went wrong" error repeatedly when loading a worksheet with Custom Functions

### ISSUE THREAD

**Issue by bermylle** [OfficeDev/office-js#3400]
# Provide required information needed to triage your issue
Our clients have been encountering an issue that disrupts their ability to load spreadsheets. This issue shows a recurring "Sorry, Something Went Wrong" error dialog, making the users to repeatedly reload the page in order to proceed. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.16528.42305 (Excel Web)
* Operating System: Windows 10
* Browser (if using Office on the web): Google Chrome and Edge
 
## Expected behavior

When opening a worksheet with custom function, the expected behavior is to proceed without any interruptions. Users should be able to view their spreadsheets.

## Current behavior

There is an error dialog showing "Sorry, something went wrong" repeatedly. The file cannot be loaded and is stuck on a loop of "Sorry, something went wrong" dialog error.

## Steps to reproduce

1. Register a Script Lab custom function. (Streaming function can replicate the issue easier compared to other custom functions)
2. Insert custom function formula to worksheet
3. Reload the page
4. The error dialog will show

![something-went-wrong-error-gif](https://github.com/OfficeDev/office-js/assets/50631121/487dc42c-cf2a-49dd-9a16-54e4ad7155d0)

![something-went-wrong-error](https://github.com/OfficeDev/office-js/assets/50631121/f7a8811b-b66d-49a2-8964-b16bbe8ade6d)

## Context

This issue is critical for the clients since they're now experiencing it on their spreadsheets. This is the first time we've experienced this issue.

**Comment by gelicas** [comment]
Hi @jiju-MS , just wanted to know if we have any updates on this as we are still actively experiencing this issue. Thank you!
![image](https://github.com/OfficeDev/office-js/assets/35692003/c72e6854-3266-416a-9e03-f5caec13719e)

**Comment by bermylle** [comment]
Filed a new issue regarding this one. -> https://github.com/OfficeDev/office-js/issues/3416

**Comment by grangeryy** [comment]
@gelicas does [#3416](https://github.com/OfficeDev/office-js/issues/3416) resolve this issue?
