### ISSUE TITLE
Office.context.mailbox.item.notificationMessages.addAsync - Wrong icon in Windows Outlook and Mac Outlook

### ISSUE THREAD

**Issue by thoffmann-fms** [OfficeDev/office-js#3401]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When using Office.MailboxEnums.ItemNotificationMessageType.ErrorMessage to display a notification, Windows Outlook show an (i) icon, Mac shows a Triangle icon, whereas OWA show the more correct (x) icon.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows, OWA, Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2304 Build 16.0.16327.20302) 64-bit
* Operating System: Win Server 2002
* Browser (if using Office on the web): Edge
 
## Expected behavior
ErrorMessage type should show an error icon, not an Information icon, and be consistent across platforms. Mac seems to be showing a Warning icon?

## Current behavior
Windows:
![image](https://github.com/OfficeDev/office-js/assets/28546239/b26d1310-3c6d-44bd-8c1d-c373e054193e)

OWA (and "New Outlook" on Windows)
![image](https://github.com/OfficeDev/office-js/assets/28546239/3157c85d-af9e-4ad0-845b-0e61afa7ba68)

Mac:
![image](https://github.com/OfficeDev/office-js/assets/28546239/5e70376a-8ca5-4cc8-bcb7-dec152d4ce7a)

## Steps to reproduce
Run an add-in and execute the code below.

## Link to live example(s)
```
          const msg: Office.NotificationMessageDetails = {
            type: Office.MailboxEnums.ItemNotificationMessageType.ErrorMessage,
            message: preLoadTranslate("db.5364"),
          };
          await Office.context.mailbox.item.notificationMessages.addAsync("accessToken", msg);
```

# Provide additional details

## Context
Testing some new code.

## Useful logs

- [ ] Console errors
- [X] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Oleg-O** [comment]
Thanks for reporting this issue regarding these icons. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: 7979296 (Windows) and 7979321 (Mac)
