### ISSUE TITLE
Missing bibliography API

### ISSUE THREAD

**Issue by Asguho** [OfficeDev/office-js#3402]
As an avid user of Word for academic and professional writing, I often rely on the insertion of properly formatted citations and bibliographies. While Word currently offers citation management features, such as the ability to create and manage citations using the built-in referencing tools, I believe the inclusion of a Bibliography API to programmatically add sources would greatly enhance the user experience and streamline the process of managing citations and bibliographic references.

The API is already implemented in VBA and C#: https://learn.microsoft.com/en-us/dotnet/api/microsoft.office.tools.word.documentbase.bibliography

**Comment by radiachkik** [comment]
Hey @michelleranmsft  @wangyun-microsoft ,

are there any news on that topic?

We would also be very interested in the js bibliography API to use within a Word extension. 😄

**Comment by jseddon2** [comment]
I'm also very interested in a bibliography API in Office.js.  I tried using the custom xml parts but encountered the same issue as #2937 .  Are there any alternative solutions?  Is there any plan for the bibliography and citation sources functionality to be enabled in the web version of Word?

**Comment by radiachkik** [comment]
Also, to be more precise, we are especially interested in setting the sources / references masterlist. Using the recently added fields API we can already manage citations, but we would love to be able to programmatically mutate the masterlist.

Or is there already a way to do this right now?

**Comment by YbJerry** [comment]
Hello @jseddon2 @radiachkik @Asguho, I meet this problem few years ago. As Microsoft wouldn't implement bibliography API recently, I will show you my solution. If you want to write a plugin of bibliography, I recommend you to use [CSL](https://citationstyles.org/) and refer these two projects [JabRef-Word-Addin](https://github.com/JabRef/JabRef-Word-Addin) and [citeproc-js](https://github.com/Juris-M/citeproc-js). Citeproc is a tool for managing [CSL](https://citationstyles.org/) and citeproc-js is its JavaScript implement. This library is old and if you want to use TypeScript, you should import [citeproc-types](https://www.npmjs.com/package/citeproc-types?activeTab=readme). And JabRef showed a way to save all the bibliography in the Control.

Maybe you are a Rust programmer and want to use WASM to do same thing, but do not to use [citeproc-rs](https://github.com/zotero/citeproc-rs). I have tried Rust implement, and it has bad support to some CSL styles such as Chinese bibliography style. But you can read its [document](https://github.com/zotero/citeproc-rs/tree/master/crates/wasm) to understand how citeproc works. Citeproc-rs really have a better document than citeproc-js.

Hope these experience can help you.

**Comment by jseddon2** [comment]
Thank you for sharing @YbJerry .  Please can I just check, do those solutions integrate with the Word bibliography feature or is the data maintained separately?

**Comment by YbJerry** [comment]
> Thank you for sharing @YbJerry . Please can I just check, do those solutions integrate with the Word bibliography feature or is the data maintained separately?

No, this solution doesn't use Word bibliography feature. You should manage all the bibliography by yourself. So if users open the document without your Addin, they can only review all the bibliography in the document but can't modify it. CSL is a universal solution used by many reference software, and I think it is also the solution used by Mendeley.

**Comment by wangyun-microsoft** [comment]
Hi @Asguho, thanks for submitting this request. We don't have any recent plans to implement related APIs. However, as mentioned above, a lot of citation management developers leverage content control or Fields for citations. Is it something that can help you to proceed with your add-in development? Thanks.
