### ISSUE TITLE
Localization issue: autofitColumns does not work with Bold format for Office on the web when using different display language

### ISSUE THREAD

**Issue by XiLiuRoy** [OfficeDev/office-js#3404]
# Provide required information needed to triage your issue
When using display language other than English and applying **BOLD** to a text , calling autofitColumns does not resize the column width to contain the **BOLD** text.

## Your Environment

Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
Host [Excel, Word, PowerPoint, etc.]: Excel
Office version number: all
Operating System: Windows 10 Enterprise
Browser (if using Office on the web): Chrome, Edge, Firefox
 
## Expected behavior

The column width should be resized to cover the **BOLD** text.

## Current behavior

The column width is resized to cover the non-bold text instead of the **BOLD** text.

## Steps to reproduce

1. Open Office on the web
2. Go to settings and change display language and preferred language to Chinese.
3. Create a new Excel workbook and put in some long English text in a cell.
4. Apply Bold format to the text entered at step 3.
5. Double click on the column line to trigger a resize or using script lab to call autofitColumns OfficeJS API.
6. Observe the result on Excel and notice the width is not changed to cover whole bold text.

## Link to live example(s)

1. Open the github code link https://github.com/XiLiuRoy/officeJsResizeIssue/blob/main/scriptLab.js
2. Copy the first section to script lab Script Tab
3. Copy the second section to scripit lab HTML tab

## Context

This issue has impacted our customers as their reports' format are incorrect, customer reports are normally large reports and at the moment, there is no way for customer to workaround, unless they took off their formatting, which is not ideal as they do need to highlight to see which row or column they need to analyze.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ruijiaMS** [comment]
Hi @XiLiuRoy,
Thanks for letting us know this issue. We raise an internal bug #8025669 to investigate this issue, any update will be post here. Thanks!

**Comment by SiruiSun-MSFT** [comment]
Hi @XiLiuRoy, could you please provide the scale of affected customers, which will help us prioritize this task. Thanks for your patience!
