### ISSUE TITLE
ContentControl Event not triggering every time

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#3405]
Hello Team,
I am using Word API for developing word add-in. 

My Environment
Platform : PC desktop
Host: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2304 Build 16.0.16327.20200) 64-bit
Operating System: Windows 10 pro

When I use this snippet :

```
async function bindEnterEvent(context, contentControls) {
    for (var i = 0; i < contentControls.length; i++) {
        contentControls[i].onEnter.add(contentControlSelected);
        contentControls[i].track();
    }
    await context.sync();
}

```
I am able to generate onEnter Event, but when i again click on the same content Control second time event is not triggering.

It only triggers when i click outside of the content Control and click again in content Control.

I want it to be triggered every time when i click on content control.

**Comment by Jayshiv-IRIS** [comment]
Hi @wangyun-microsoft,
I am  currently blocked by this issue.
Could you please give me a status on this so I can plan accordingly.
Thanks for your help.

**Comment by wangyun-microsoft** [comment]
@Jayshiv1408Dev  Thanks for submitting this entry. Can you please describe your use case here?

**Comment by Jayshiv-IRIS** [comment]
@wangyun-microsoft  Thanks for quick response,
I am binding contentControl event from the above snippet, and i am able to trigger onEnter event when i click on the contentControl.
In that event I am highlighting the contentControl content by changing its highlight color.
When I again click on the same contentControl the event is is not triggering
For triggering event second time I need to click outside of the contentControl,and again when I click on contentControl I am able to trigger an event.
When I click the same contentControl second time then I am removing its background color just like select-deselect functionality.
The only thing is bothering me is that I have to click outside of the contentControl to trigger event second time.

**Comment by xuruiyao-msft** [comment]
Hi @Jayshiv1408Dev, thank you for reaching out to us. 
This is by design:
If you again click on the same content control, the onEntered event will not be triggered. 
Only clicking the outside and then clicking the content control or clicking the different content control, the onEntered event can be triggered.
If you have any other questions, feel free to contact us again. Thank you very much!!!

**Comment by Jayshiv-IRIS** [comment]
Hi @xuruiyao-msft
 Thanks for your response.
Actually I want functionality like click event on content Control.
I want it to be triggered everytime when I click on the content control, and I don't have to click outside of the content control to trigger the event.
How can I achieve this?.Can you please suggest something.

**Comment by xuruiyao-msft** [comment]
Hi @Jayshiv1408Dev ,
Would you please have a try for onSelectionChanged
Here's the sample code:
https://learn.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview#word-word-contentcontrol-onselectionchanged-member
If the selection is changed, which means the cursor moves to different range, even if the cursor is inside the content control, the  onSelectionChanged will be triggered. But if the cursor is outside the content control or it click the same position or choose the same range, the onSelectionChanged cannot be triggered. 

Hope it could handle the scenario for your case. Thanks again for your feedback.
