### ISSUE TITLE
Taskpane Add-in is not displayed in Outlook Web App (OWA)

### ISSUE THREAD

**Issue by guzman-rc** [OfficeDev/office-js#3408]
Taskpane Add-in is not displayed in OWA

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Mac, OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft 365
* Operating System: Windows and Mac OS X
* Browser (if using Office on the web): Chrome, Edge, Safari
 
## Expected behavior

When the user clicks on the Addin icon (ribbon buttons), the taskpane should be displayed.

## Current behavior

The taskpane is only displayed **if the user has previously read or edited an email**.

## Steps to reproduce

1. Log in to OWA
2. Click on the "new email" button.
3. In the ribbon buttons, click on the addin button "**Pools**".
4. Taskpane is not displayed.

![Captura de pantalla 2023-06-07 a las 18 27 32](https://github.com/OfficeDev/office-js/assets/96702862/e6f9680a-daa9-4815-94c9-cd264904ef83)

5. If you read a message and then click on the "Pools" addin button the Taskpane will display

## Link to live example(s)

1. You can try with the Addin "**Pools**" installed by default.

## Context

Users are reporting issues due to the taskpane not displaying.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Hi @guzman-rc 
Thanks for reporting this issue. This is already being tracked here - https://github.com/OfficeDev/office-js/issues/3399 and further updates will be provided there. 
We have fixed this issue and it is being rolled out. It should be available latest by tomorrow. In case you still face this issue, then please clear your cache and do a hard refresh and try again.
