### ISSUE TITLE
how to update office for mac addins runtime(Safari WebKit version: 1.0.0.0)

### ISSUE THREAD

**Issue by heimen-zc** [OfficeDev/office-js#3411]
I developed an add-in in Excel for Mac, and when I added a login feature, I received a prompt saying that the browser version was too low. However, my locally installed Safari had no issues. I was wondering how I could upgrade the WKWebView version of Excel runtime to avoid this problem.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___Mac___
* Host [Excel, Word, PowerPoint, etc.]: ___Excel___
* Office version number: __16.73(23051401)____
* Operating System: __Mac OS____
* Browser (if using Office on the web): ___Excel App___
 
## Expected behavior

how to update wkwebview version? or if i can reset user-agent to a higher version
## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ruijiaMS** [comment]
Hi @heimen-zc,
Thanks for letting us know this issue, could you please add a screenshot which can help us understand the full text in the error prompt?
