### ISSUE TITLE
Need to add custom icon from mapi property in mailbox from outlook web add-in office.js

### ISSUE THREAD

**Issue by Rajnish-Asite** [OfficeDev/office-js#3413]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows, OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2305 Build 16.0.16501.20074) 64-bit 
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Green tick icon should be displayed on outlook mailbox item from outlook web add-in office.js.

![image](https://github.com/OfficeDev/office-js/assets/135962980/82af92ba-6e03-4710-a26a-d163504bf66f)

## Current behavior
We need to show Green tick icon in mailbox item as we are showing from VSTO Pluging using below code-
`mailItem.PropertyAccessor.SetProperty("http://schemas.microsoft.com/mapi/proptag/0x10800003", 312)`

Now we need to set Green tick in mailbox item from web add-in So we tried custom properties as well as single extended value property to set on mailItem but still we are not able to show Green tick.

## Steps to reproduce

1. First we tried to add custom property as below
```
Office.context.mailbox.item.loadCustomPropertiesAsync((result) => {
    console.log(result);
    let customProps = result.value;
    customProps.set("http://schemas.microsoft.com/mapi/proptag/0x10800003", 312);
    customProps.saveAsync((asyncResult) => {
        console.log(asyncResult);
    })
});
```
2. Second We tried with updateMessage reqeust from graph api to modify/add `singleValueExtendedProperties` in mailItem
```
async updateMessage(itemId) {
    try {
      const accessToken = await this.getMicrosoftAccessToken();
      return await fetch('/me/messages/'+ itemId , {
        method: 'PATCH',
        headers: {
          'content-type': 'application/json',
          authorization: `Bearer ${accessToken}`
        },
        body: JSON.stringify({
          singleValueExtendedProperties: [
            {
               "id":"String {e7abc95f-cf74-4d45-880c-04a779a6541b} Name 0x10800003",
               "value": "312"
            }
          ]
        })
      }).then(res => res.json());
    } catch (e) {
      console.log(e);
    }
 }
```
## Context

We have developed web add-in to save emails directly on our Cloud So after saving email we are showing green tick on that saved mail item for user better experience. So this Green tick is very important feature for us. 

Please do needful asap.

**Comment by exextoc** [comment]
Hi @Rajnish-Asite 
Currently the feature to add a custom icon to outlook mailbox items is not there. We track Outlook add-in feature requests on our [Tech Community Page](https://aka.ms/M365dev-suggestions).Please add your request there and select appropriate labels. Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by Rajnish-Asite** [comment]
@exextoc  New Feature request has been raised on your [Tech Community Page](http://aka.ms/M365dev-suggestions) as given below-
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-a-custom-icon-to-outlook-mailbox-items-from-outlook-web-add/idi-p/3856477
