### ISSUE TITLE
Excel Online - Recalculate tooltip causing "Sorry, Something Went Wrong" error 

### ISSUE THREAD

**Issue by bermylle** [OfficeDev/office-js#3416]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Excel 
* Office version number: 16.0.16605.42304 (Web)
* Operating System: Windows 10
* Browser (if using Office on the web): Edge, Google Chrome, Firefox, and Opera
 
## Expected behavior

Hovering cursor on the refresh tooltip should not cause an error.

## Current behavior

Hovering cursor on the refresh tooltip causes "Sorry, Something Went Wrong" error 

![bugg](https://github.com/OfficeDev/office-js/assets/50631121/e7b3467b-4108-4f3e-b3ce-753bd386c3df)

## Steps to reproduce

1. Register a Streaming Custom Function (Make sure to delay the setResult operation) 
![image](https://github.com/OfficeDev/office-js/assets/50631121/9233d39d-aa34-495a-ad64-cebdc223b4bf)
2. Insert a Custom Function Formula (Note: The bug will not occur until the first page reload)
3. Reload the page
4. Open Script Lab
5. Wait for the inserted formula to show the recalculate tooltip
6. Hover the cursor on the tooltip
7. The error dialog will show

Note: Attached here is the streaming function used to reproduce the bug

## Context
This issue is critical for the clients since they're now experiencing it on their spreadsheets. This is the first time we've experienced this issue.

[Streaming_function_bug_reproducer.txt](https://github.com/OfficeDev/office-js/files/11705206/Streaming_function_bug_reproducer.txt)

**Comment by ruijiaMS** [comment]
Hi @bermylle,

Thanks for letting us know this issue, and we have opened an internal ticket #7994160 to track the problem. We will post updates here!

**Comment by bermylle** [comment]
Thanks! @ruijiaMS

**Comment by bermylle** [comment]
Hello @ruijiaMS!

Any updates regarding the issue? Thank you!

**Comment by penglongzhaochina** [comment]
Hi @bermylle ,

The fix has been released to production, I will close this issue. Please contact me if you have any other questions. Thanks.
