### ISSUE TITLE
Insert image using PowerPoint Shapes Api

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js#3417]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Hi, is there any way to add an image **via the Shapes Api,** i can see i can add geometric shapes, but can't set a background or anything to a svg or png.

## Post how-to questions about your code on Microsoft Q&A

We have several forums where you can ask the developer community questions about your code. Try one of the following forums to ask technical questions about:
- [Developing Office Add-ins for Word, Excel, PowerPoint, Outlook, Project, Visio, and OneNote](https://docs.microsoft.com/answers/topics/office-addins-dev.html)
- [Access programming in Office](https://docs.microsoft.com/answers/topics/office-access-dev.html)
- [Developing COM or VSTO Add-ins for Office](https://docs.microsoft.com/answers/topics/office-vsto-com-dev.html)
- [Office JavaScript API](https://docs.microsoft.com/answers/topics/office-js-dev.html)
- [SharePoint and OneDrive development](https://docs.microsoft.com/answers/topics/sharepoint-dev.html)
- [Deploying and publishing Office or SharePoint apps to AppSource](https://docs.microsoft.com/answers/topics/microsoft-365-apps-publishing-dev.html)

For additional information about JavaScript programming, see the [JavaScript at Microsoft](https://docs.microsoft.com/javascript/) community hub.

**Comment by HarryPitsillides** [comment]
How is inserting an Image to a shape which is vital functionality not planned? How does Microsoft expects us to move from VSTO when something as basic as this is missing?

**Comment by anmirza** [comment]
There is no way to insert a texture or picture inside the geometrical shape in the documentation. Is there any update on it?
