### ISSUE TITLE
Problems to sideload Vue in Outlook

### ISSUE THREAD

**Issue by TuringJest** [OfficeDev/office-js#3419]
Having sideloaded multiple kinds of JS apps in Excel using vue/quasar etc. I'm not able to do the same in Outlook.
I can get the demo from the docs to run and that's it. Modifying the demo to mount a Vue app will result in a blank taskpane.  
Serving a Vue app loading the office script on the expected port with tls will result in a blank taskpane and an empty body tag. No errors just an empty body.

I have tested the exact same add-in with the same setup but using an excel manifest and it will sideload into excel (web/mac) without problems. 

Is there something special about Outlook?

**Comment by paul-sudo** [comment]
Hello, maybe I can help you. In Outlook HTTPS must be used, also when using Localhost. For the certificates you can use this library [office-addin-dev-certs](https://www.npmjs.com/package/office-addin-dev-certs) 

Example Webpack:
```
const fs = require("fs");
const path = require("path");
const homedir = require("os").homedir();
const { defineConfig } = require('@vue/cli-service');

module.exports = defineConfig({
  devServer: {
    https: {
	    key: fs.readFileSync(
		    path.resolve(`${homedir}/.office-addin-dev-certs/localhost.key`)
	    ),
	    cert: fs.readFileSync(
		    path.resolve(`${homedir}/.office-addin-dev-certs/localhost.crt`)
	    ),
	    ca: fs.readFileSync(
		    path.resolve(`${homedir}/.office-addin-dev-certs/ca.crt`)
	    )
    }
  },
});
```

Example vite:
```
import { defineConfig } from 'vite';
import fs from 'fs';
import path from 'path';
import os from 'os';

const homedir = os.homedir();

// https://vitejs.dev/config/
export default defineConfig({
	server: {
		https: {
			key: fs.readFileSync(
				path.resolve(`${homedir}/.office-addin-dev-certs/localhost.key`)
			),
			cert: fs.readFileSync(
				path.resolve(`${homedir}/.office-addin-dev-certs/localhost.crt`)
			),
			ca: fs.readFileSync(
				path.resolve(`${homedir}/.office-addin-dev-certs/ca.crt`)
			)
		},
	}
});
```

**Comment by TuringJest** [comment]
@paul-sudo I'm using Vite's devserver with self signed certificates (Vite dev option 'https: true'), as far as I know the add-in will not connect at all if there is a TLS problem and just be blank. But will try to use the office certificates as you suggest to see if it makes a difference. Will report back a bit later.

Btw do you have a working Vue setup? Perhaps you could make a gist? 
Thank you

**Comment by TuringJest** [comment]
@paul-sudo it was the certificates! Didn't suspect it because Excel just recently also required URLs with "https" in the manifest (or at least to sideload it in the web version?) and it worked fine with the certificates from Vite (for web and the macOS app). Probably only Outlook actually checks them. 
Not sure what is wrong with Vite's TLS but it works now. Thx!
