### ISSUE TITLE
How to detect event Save and it's callback of Outlook add-in

### ISSUE THREAD

**Issue by rodrigoguariento** [OfficeDev/office-js#342]
I built an Outlook Add-in, but I'd like to save my Add-in data when the end user click on Save button (of new Appointment/Calendar). Is it possible do get this event? 

If yes, my Add-in would call an API to validate some data and if there is some error, I would like to cancel the Save and alert the end user about why). How to do that?

- Platform: PC desktop (test), Linux Ubuntu (dev), Outlook
- Host: Outlook
- Office version number: Outlook Office 365 ProPlus v1803 build 9126.2336, and Outlook 365 Web (office.com)
- Operating System: Windows 10 Pro
- Browser (if using Office Online): Google Chrome 71.0.3578.98 64bits

**Comment by exextoc** [comment]
Currently the feature: Events for when save is called, you requested, is not a part of the product. We track Outlook add-in feature requests on our[ user-voice](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins) page. Please add your request there. Feature requests on user-voice are considered when we go through our planning process.

**Comment by rodrigoguariento** [comment]
Thank you!
