### ISSUE TITLE
Unable to Enable/Disable contextual Sub Menu Items

### ISSUE THREAD

**Issue by shekar233** [OfficeDev/office-js#3422]
Enable/Disable Multiple Contextual Menu Items on right click
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop 
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2202 Build 16.0.14931.20988) 32-bit 
* Operating System: Windows 10 Enterprise
* Browser (if using Office on the web): ______
 
## Expected behavior
I want to enable/disable the Sub-Menu Items based on the worksheet or a specific cell within a sheet. 
i.e. Right Click --> Contextual Menu --> Sub-Menu1
                                                           --> Sub-Menu2

I want to Enable/Disable the Sub-Menu1 or Sub-Menu 2 based on which worksheet the user is working on or based on a particular cell/cell range the user right clicks on.

## Current behavior
Current office documentation doesn't mention anything on how contextual menus can be enabled/disabled.

The Office.ribbon.requestUpdate(input: RibbonUpdaterData) supports only disabling/enabling the buttons on the ribbon of a Contextual Tab.

## Steps to reproduce

1. Add the ExtenstionPoint tag with type as ContextMenu in the manifest file, and the following code ore similar.
```
<ExtensionPoint xsi:type="ContextMenu">
                      <OfficeMenu id="ContextMenuCell">
                        <Control xsi:type="Menu" id="Menu">
                                            <Label resid="Dropdown.Label" />
                                            <Supertip>
                                                <Title resid="Dropdown.Label" />
                                                <Description resid="Dropdown.Tooltip" />
                                            </Supertip>
                                            
                                            <Items>
                                                <Item id="Menu.Item1">
                                                    <Label resid="Item1.Label"/>
                                                    <Supertip>
                                                        <Title resid="Item1.Label" />
                                                        <Description resid="Item1.Tooltip" />
                                                    </Supertip>
                                                    
                                                <Action xsi:type="ExecuteFunction">
                                                    <FunctionName>SubMenu1</FunctionName>
                                                </Action>
                                           <Enabled>false</Enabled>
                                                </Item>
                                                <Item id="Menu.Item2">
                                                <Label resid="Item2.Label"/>
                                                <Supertip>
                                                    <Title resid="Item2.Label" />
                                                    <Description resid="Item2.Tooltip" />
                                                </Supertip>
                                                
                                           <Action xsi:type="ExecuteFunction">
                                                <FunctionName>SubMenu2</FunctionName>
                                            </Action>
                                            </Item>
                            
                                            </Items>
                                        </Control>
                      </OfficeMenu>
                  </ExtensionPoint>
```
2. Then add the following code in the action's assigned method
```
async function SubMenu1(args) {
  console.log("SignOff 1 started");
  Office.ribbon.requestUpdate({
    tabs: [
        {
            id: 'ContextMenuCell',
            controls: [
                {
                    id: 'Menu.Item1',
                    enabled: true
                }
            ]
        }
    ]
});
  args.completed();
}
Office.actions.associate("SubMenu1", SubMenu1);
```
4. ______

## Link to live example(s)

1. ______
2. ______
4. ______

# Provide additional details
When the above code is executed I get the following error

```
Uncaught (in promise) RichApi.Error: ControlIdNotFound
    at new n (excel-win32-16.01.js:25:257638)
    at i.processRequestExecutorResponseMessage (excel-win32-16.01.js:25:321804)
    at excel-win32-16.01.js:25:319867
```

## Context
I want to enable/disable these submenus based on different business requirements i.e. based on worksheet or based on cell or cell range etc. As shown in the attached image, I want to enable/disable Sub-Menu 1 or Sub-Menu 2 based on the active worksheet or active cell.

A better explanation of my requirement is posted in the following stackoverfow link.
[Enable/Disable Contextual Sub Menu Items](https://stackoverflow.com/questions/76433902/excel-office-js-enable-disable-multiple-context-menu-items-on-right-click/76434030?noredirect=1#comment134812250_76434030)

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
<img width="229" alt="Contextual-SubMenu" src="https://github.com/OfficeDev/office-js/assets/16794512/8f778b51-3ebf-4002-b218-c5e02a486875">

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ShivharakhYadav** [comment]
I have the same issue with Contextual Menu Items

**Comment by Rick-Kirkham** [comment]
I'm trying to find who to assign this to.

**Comment by trigurl** [comment]
Hello, enable/disable is not supported on the right click context menu at the moment.

**Comment by Shukla-Dev** [comment]
Is this issue is FIxed ?

**Comment by rgold5950** [comment]
Also experiencing this issue. Can you please recommend a workaround?

**Comment by NataliaKravcheniaTR** [comment]
I have the same issue with context menu button/items.

**Comment by EsterBergen** [comment]
Hi @NataliaKravcheniaTR . @rgold5950 , and @Shukla-Dev - Currently you can only enable/disable ribbon buttons and not sub menu items. This would be a new feature. Please make a feature request here [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. Thanks for highlighting this!

**Comment by NataliaKravcheniaTR** [comment]
@EsterBergen Could you update the documentation that this functionality is only available in ribbon?
https://learn.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands

**Comment by EsterBergen** [comment]
Great point. @samantharamon  Can you have a look?

**Comment by samantharamon** [comment]
Thanks for the suggestion, @NataliaKravcheniaTR. Changes to the article have been merged (see [PR#4838](https://github.com/OfficeDev/office-js-docs-pr/pull/4838)). These updates will be published by the end of today.

**Comment by linderholm** [comment]
We noticed our ContextMenu items suddenly respecting this <Enabled> property. Something must've changed very recently. Dug around but all I could find referencing this change is in this https://github.com/OfficeDev/office-js-docs-pr/pull/4999/
where the line 
```
> - Programmatically enabling or disabling [context menus](interface-elements.md#add-in-commands) isn't supported. Only ribbon buttons, menus, and tabs are supported.
```
had been removed. Could you provide some clarity @samantharamon ?

**Comment by EsterBergen** [comment]
Adding @adrianwu8516

**Comment by adrianwu8516** [comment]
Hi @linderholm, 

Yes, this is a new capability! It's still rolled out since this Jan and you can check the minimum supported version here: 
Win32: 16.0.18526.20144
MacOS: 16.94.209.0(16.94.25020927)

We will make an announcement in the community call and update the support documentation soon. Thank you for staying tuned for our feature release! Hope this feature could be helpful for your scenario.
