### ISSUE TITLE
When using `insertWorksheetsFromBase64` method and XML has `Office.AutoShowTaskpaneWithDocument` a new blank addin sideload window opens

### ISSUE THREAD

**Issue by ajanssen-vena** [OfficeDev/office-js#3423]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: mac
* Host [Excel, Word, PowerPoint, etc.]: excel
* Office version number: ______
* Operating System: macOs
* Browser (if using Office on the web): safari inside sideload addin
 
## Expected behavior
When calling `insertWorksheetsFromBase64` and `Office.AutoShowTaskpaneWithDocument` is present in the XML a new grey add-in window should not open.

## Current behavior
We call `insertWorksheetsFromBase64` and a new side load add-in window opens.

## Steps to reproduce
1. Create a file to be used as the file string for `insertWorksheetsFromBase64`
2. File should have Office.AutoShowTaskpaneWithDocument property set to true
3. Call `insertWorksheetsFromBase64`
4. Observe new add-in window opens.

## Context
Our team is currently creating functionality to copy data from one workbook to another. We insert a temporary sheet in a workbook  from another excel file so that we can make use of the copyFrom method. When we insert the sheet a new grey add-in window appears. The operation is successful but strange unexpected behaviour from calling `insertWorksheetsFromBase64`

<img width="346" alt="Screen Shot 2023-06-12 at 12 17 41 PM" src="https://github.com/OfficeDev/office-js/assets/133040267/a7a0eae5-337b-4d2d-b3d6-33bdb5f61c3d">

**Comment by SiruiSun-MSFT** [comment]
Hi @ajanssen-vena, sorry for the late response. Could you provide your sample gist code as well as the sample add-in to us? It could speed us up in finding the root cause. Thanks in advance!
