### ISSUE TITLE
Office.context.mailbox.getSelectedItemsAsync is not available

### ISSUE THREAD

**Issue by deviluncle** [OfficeDev/office-js#3424]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web_
* Host [Excel, Word, PowerPoint, etc.]: outlook
* Office version number: modern Outlook UI
* Operating System: windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

I want to get the information of multiple selected emails through [This](https://learn.microsoft.com/zh-cn/office/dev/add-ins/outlook/item-multi-select) tutorial

## Current behavior

If I set <bt:Sets DefaultMinVersion="1.13"> as in the tutorial, then my add-in program is not visible directly. If it is set to 1.3, the add-in is visible, but getSelectedItemsAsync will report an error: Uncaught Sys.FeatureNotEnabled: The feature getSelectedItemsAsync, is only enabled on the beta api endpoint, 
![6676f51e-3814-4bde-a7fb-69270a4e44b2](https://github.com/OfficeDev/office-js/assets/29850196/85388a9e-5015-42bd-a14f-5fd55465dcfd)
![eb6307ff-92f7-44c8-bac4-a8b4a7f0f857](https://github.com/OfficeDev/office-js/assets/29850196/6346abc3-2377-4819-9ebf-a649cfe7d1ba)
It is written on the official website that it supports 1.13, why is it printed out as false in the code shown in the attached picture?

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.
Internal tracking id: 3690004

**Comment by exextoc** [comment]
@deviluncle We have fixed this issue. Could you please verify it?
