### ISSUE TITLE
Unable to add/Delete columns in non-uniform tables. 

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#3425]
Hello Team,

We are using office.js(word API) for developing word add-in.

My Environment
Platform : PC desktop
Host: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2304 Build 16.0.16327.20200) 64-bit
Operating System: Windows 10 pro

When i use this snippet.
URL : https://learn.microsoft.com/en-us/javascript/api/word/word.table?view=word-js-preview#word-word-table-addcolumns-member(1)
Functions :
addColumns(1,2)
deleteColumns(1,3)

 I have encountered while attempting to add or delete columns in a non-uniform table. Unfortunately, I have been facing errors, and the operations do not seem to work as intended. It is worth noting that these operations are successful when applied to uniform tables.

As a result, I am currently unable to add or delete columns in tables that do not adhere to a uniform structure. This limitation hampers my ability to manipulate tables in a flexible manner. I understand the importance of being able to perform these actions on any type of table, as it provides greater control and adaptability in managing data.

Thanks..!!

**Comment by Searion** [comment]
Thanks for reporting this issue regarding table API. This sounds like a bug and we are investigating it. It has been put on our backlog. We unfortunately have no timelines to share at this point. ​

**Comment by Jayshiv-IRIS** [comment]
Is there Any Update on this?

**Comment by jipyua** [comment]
hi @Jayshiv1408Dev thanks for reporting this, according to the API documentation, this API is now only "This is applicable to uniform tables.". Asking support on non-uniform tables is a kind of new feature request, we track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum]( https://aka.ms/m365dev-suggestions). Please add your request there. thanks.
