### ISSUE TITLE
Outlook event based activation not working with typescript/webpack in Outlook for Windows

### ISSUE THREAD

**Issue by ilbrando** [OfficeDev/office-js#3426]
I have a typescript project build with webpack. It contains both tastpanes and an `OnMessageSend` event handler. I can't get the event handler to work (be called) when used in Outlook for Windows.

It might be because of the way webpack bundles the files into a single JS file, because if I include a simple JS file (which is only copied by webpack) and it contains a function in global scope, I can get it to be called. But I need a bundle of several files.

As far as I can see, webpack is wrapping the code in an anonymous function which is called, but maybe Outlook is loading the JS file in some special way which doesn't handle this?

I am setting the handler function in `globalThis.myHandler = myHandler` which works in the browser.
I am also setting `Office.actions.associate("myHandler", myHandler)` but this has no effect or is never invoked.

Could you provide an example of how to accomplish this with multiple typescript files and webpack?

# Provide required information needed to triage your issue

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2304 Build 16327.20248
* Operating System: Windows 11
* Browser (if using Office on the web): ______
 
## Expected behavior
I expected the handle to be invoked.

## Current behavior
The handler is not invoked.

## Steps to reproduce
I was hoping you could change your example to have the event handler implemented in a typescript file (which uses other files packages) and is bundlede with webpack instead of just a simple JS file.

## Context
This is a deal breaker for me because out addin is supposed to work both in Outlook in the browser and in Outlook for Windows.

**Comment by Iniyan-M** [comment]
@ilbrando I'm also facing this same issue in mac. Have you tried the same in mac before?

**Comment by ilbrando** [comment]
> @ilbrando I'm also facing this same issue in mac. Have you tried the same in mac before?

I haven’t tried it on Mac. I wouldn’t expect the problem to be in that environment because I believe it uses the same technology as on the web, but I’m not sure.

**Comment by exextoc** [comment]
For Windows Outlook, the event-based JavaScript file is executed in a custom sandboxed process instead of an embedded browser. The custom sandboxed process is only compatible with JavaScript up to ECMAScript 2016. Also, there is no DOM or BOM available in this environment. My suspicion is that the webpack bundle contains some syntax that is not compatible with the sandboxed process, which results in a failure to load the bundle, thus no execution of your handlers.

Can you check whether your webpack config targets ECMAScript 2016 or older?

**Comment by ilbrando** [comment]
I think you are right about that. I realized in another issue that I couldn't use the spread ("...") operator in the javascript for the event handler. For now I have switched to pure javascript for this part of the code, but I will try to setup a different webpack config for building this part when I have time fore it.

**Comment by exextoc** [comment]
@ilbrando, thanks for the update.
I will close this post for now and we can create another post if you encounter issues after using the different webpack config.
