### ISSUE TITLE
How to subscribe to the event in the Task pane about user clicking on the Excel workbook 'Save' or 'Save as' button 

### ISSUE THREAD

**Issue by stenly311** [OfficeDev/office-js#3428]
## How to subscribe to the event in the Task pane about the user clicking on the Excel workbook 'Save' or 'Save as' button  
I am trying to do some post-processing after a user clicks on the Save or Save as button in Excel Workbook but struggling to find any way how to subscribe to these events.
Any idea?

Thank you, M.

**Comment by donlvMSFT** [comment]
Hi @stenly311 ,

Thanks for letting us know this issue. However, currently, the feature: Workbook onSave/onSaveAs event, you requested, is not a part of the product. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests are considered when we go through our planning process. 

Thanks, Microsoft 365 Developer Platform team

**Comment by stenly311** [comment]
Hi @donlvMSFT thanks for your reply. I have raised the a new feature suggestion as advised. 

Please upvote here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/new-excel-workbook-save-amp-save-as-events-to-subscribe-in-task/idi-p/3848770#M1826

Thank you, Martin.
