### ISSUE TITLE
Make Dialog boxes when converting JavaScript Office add-ins to installable add-ins

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#3429]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We have a JavaScript Office add-in. We are making an installable and executable add-in on top of it by VSTO and [WebView2](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/win32). Most features work directly without any problem. But it seems that Office dialog API does not work.

For instance, we have the following code in our add-in, which works well in JavaScript Office add-in.

```
Office.context.ui.displayDialogAsync(
  `https://www.ourfrontend.com/auth/google`,
  { height: 90, width: 60 },
  asyncResult => {
    const dialog = asyncResult.value;
    dialog.addEventHandler(
      Office.EventType.DialogMessageReceived,
      //tslint:disable-next-line:no-any
      async (arg: any) => {
        if (arg.message === 'getUser') {
          const token = await getSignTokenLocal();                  
          resolve(payloadFromToken(token));
        }
        if (arg.message == 'close') {
          dialog.close();
        }
      },
    );
  },
);
```

However, when converting to VSTO, the same code raises an error: `Error: TypeError: Cannot read properties of undefined (reading 'displayDialogAsync')`.

Dialog boxes are important elements in add-ins. Could you tell me what we can do in this case?

**Comment by slabereemsft** [comment]
Hi Chengtie,

You have a very interesting architecture for your add-in from what I can gather. Unfortunately, hosting a web add-in in a non-Microsoft host isn't a supported scenario. Can you help me understand the problem that you're trying to solve that requires you to go beyond web add-ins?

**Comment by chengtie** [comment]
Hello,

We would like to build an installable and executable desktop add-in, which have advantages in some cases:
- Users in some countries like China may have difficulties in entering Microsoft Office Store
- A part of users need to install WebView2 to use our add-ins. If they go to the store, it's complicated to ask them to install WebView2. But we could bundle the installation of WebViews2 and the installation of the desktop add-in together.
- Some companies may don't allow employees to go to Microsoft Office Store.

As we have already this JavaScript add-in, we would like to use maximum the existing code to build the desktop add-in. With regards to dialog boxes or similar controls, what we would like to realize is

1. Clicking on a button in the taskpane could launch a window outside the taskpane, and we could navigate to certain pages in the window.
2. After manipulations on the window, it triggers a callback to the taskpane.

Do you have any idea how to achieve this?

> Hi Chengtie,
> 
> You have a very interesting architecture for your add-in from what I can gather. Unfortunately, hosting a web add-in in a non-Microsoft host isn't a supported scenario. Can you help me understand the problem that you're trying to solve that requires you to go beyond web add-ins?
