### ISSUE TITLE
Is userProfile trusted to identify the end user?

### ISSUE THREAD

**Issue by rodrigoguariento** [OfficeDev/office-js#343]
I would like to know if is necessary to create some authentication to identify an Add-in user? I was thinking to get user info from Office.context.mailbox.userProfile, because (in my mind) who is using Outlook 365 or higher presumably already have made his/her authentication. 

Is Office.context.mailbox.userProfile trusted to identify some user in my back-end? Or do I need to create an SSO?

- Platform: PC desktop (test), Linux Ubuntu (dev), Outlook
- Host: Outlook
- Office version number: Outlook Office 365 ProPlus v1803 build 9126.2336, and Outlook 365 Web (office.com)
- Operating System: Windows 10 Pro
- Browser (if using Office Online): Google Chrome 71.0.3578.98 64bits

**Comment by exextoc** [comment]
I would read the documentation here as a good starting point for authentication and when you may need it - [link](https://docs.microsoft.com/en-us/outlook/add-ins/authentication)

**Comment by rodrigoguariento** [comment]
Thank you!
