### ISSUE TITLE
Unable to access variable in another javascript on Windows outlook using addin

### ISSUE THREAD

**Issue by mkondadg** [OfficeDev/office-js#3430]
Testing the Addin on windows & Mac, accessing a variable defined in another javascript doesnt work on windows.
Same works on Mac.

We create this variable in another script as it is customizable and it is created on the fly.
We cannot hardcode or replace in the larger file (dg-outlook-addin.js)

## Your Environment
PC desktop, Mac 
Outlook
MS 365 (Version 2208 - Build 15601.20660) Windows (Windows 10 Enterprise 21H2, 19044.2006)
MS 365 (16.74 - 23061100) - Mac Ventura 13.4

 
## Expected behavior
Able to use the variable from another script on Windows and Mac

## Current behavior
Addin JS is not able access variable on windows and gets hung.
Same works on Mac

Deploy addin  using manifest_45.xml and host the files on localhost or remote
Send mail
Now mail gets hung with below prompt

![sendmail error1](https://github.com/OfficeDev/office-js/assets/62250655/8c0e63d8-33c1-4ebb-b555-ea06daea7a4e)

Attached manifest and js/html files used

[sendmail_customvar_1.zip](https://github.com/OfficeDev/office-js/files/11760445/sendmail_customvar_1.zip)

Log from the outlook application.
[log.txt](https://github.com/OfficeDev/office-js/files/11760438/log.txt)

Below log can be seen in log.txt
**evaluate mail-801**
But another log after accessing variable cannot be seen.
**evaluate mail-802**

**Comment by Oleg-O** [comment]
This is as designed. On Windows, event-based activation is executed in a [JavaScript-only runtime](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtimes#javascript-only-runtime) which has better performance characteristics but also has certain [behavior and limitations](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest#event-based-activation-behavior-and-limitations). In other words, the HTML file in this case is not used at all, and the code in dg-outlook-addin.js is loaded directly into the runtime. The runtime is not even aware of existence of the other JS file (wipport.js). Note, imports are also not supported, therefore, to make this work you'll need to bundle the two JS files together in dg-outlook-addin.js. Hope this helps.
