### ISSUE TITLE
OfficeJS : Context menus text are not visible when right click on Word 365 but show on Desktop App

### ISSUE THREAD

**Issue by ChienHo** [OfficeDev/office-js#3431]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue
I using manifest to add context menu text of Office add-ins, it can show on desktop app but not visible on Word 365
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Browser (if using Office on the web): Edge
 
## Expected behavior

Connext menu should show when click right in text highlighted
## Current behavior
Connext menu are not visible when click right in text highlighted.

## Useful logs

- [ ] Screenshots

![image](https://github.com/OfficeDev/office-js/assets/30323038/3f4838d6-6d7b-4cdf-a9f4-0c434f5503b5)

![image](https://github.com/OfficeDev/office-js/assets/30323038/1523c85f-4300-405c-961b-47dbf2c86e56)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by trigurl** [comment]
Hi, can you give this sample manifest a try and tell me if you see the "Wikipedia Menu" showing up in your right click menu in Word Win32 and Online.

**Comment by trigurl** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="TaskPaneApp">
	<Id>669a52a9-957a-4579-809f-df1a11a64752</Id>
	<Version>1.0.0.0</Version>
	<ProviderName>Microsoft</ProviderName>
	<DefaultLocale>en-US</DefaultLocale>
	<DisplayName DefaultValue="Wikipedia in Context Menu"/>
	<Description DefaultValue="Wikipedia in Context Menu"/>
	<IconUrl DefaultValue="https://fa000000110.resources.office.net/f7024bdc-7caf-4ca8-807d-2908f09640d6/1.0.0.1/en-us_web/apps/wikipedia/images/wikipedia_32x32.png" />
	<AppDomains>
		<AppDomain>AppDomain1</AppDomain>
	</AppDomains>
	<Hosts>
		<Host Name="Document"/>
	</Hosts>
	<DefaultSettings>
		<SourceLocation DefaultValue="https://fa000000110.resources.office.net/f7024bdc-7caf-4ca8-807d-2908f09640d6/1.0.0.1/en-us_web/apps/wikipedia/Wikipedia_dev.html" />
	</DefaultSettings>
	<Permissions>ReadWriteDocument</Permissions>
	<VersionOverrides xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
	<Description resid="residToolTip" />
	<Requirements>
		<bt:Sets DefaultMinVersion="1.1">
			<bt:Set Name="Settings" />
		</bt:Sets>
	</Requirements>
	<Hosts>
		<Host xsi:type="Document">
			<DesktopFormFactor>
				<FunctionFile resid="residDesktopFuncUrl" />
				<ExtensionPoint xsi:type="ContextMenu">
					<OfficeMenu id="ContextMenuText">
						<Control xsi:type="Menu" id="myMenuID">
							<Label resid="residLabel" />
							<Supertip>
								<Title resid="residLabel" />
								<Description resid="residToolTip" />
							</Supertip>
							<Icon>
								<bt:Image size="16" resid="icon1_16x16" />
								<bt:Image size="32" resid="icon1_32x32" />
								<bt:Image size="80" resid="icon1_80x80" />
							</Icon>
							<Items>
								<Item id="myMenuItemID">
									<Label resid="residLabel2"/>
									<Supertip>
										<Title resid="residLabel2" />
										<Description resid="residToolTip" />
									</Supertip>
									<Icon>
										<bt:Image size="16" resid="icon1_16x16" />
										<bt:Image size="32" resid="icon1_32x32" />
										<bt:Image size="80" resid="icon1_80x80" />
									</Icon>
									<Action xsi:type="ShowTaskpane">
										<SourceLocation resid="residUnitConverterUrl" />
									</Action>
								</Item>
							</Items>
						</Control>
					</OfficeMenu>
				</ExtensionPoint>
			</DesktopFormFactor>
		</Host>
	</Hosts>
	<Resources>
	<bt:Images>
		<bt:Image id="icon1_16x16" DefaultValue="https://fa000000110.resources.office.net/f7024bdc-7caf-4ca8-807d-2908f09640d6/1.0.0.1/en-us_web/apps/wikipedia/images/wikipedia_32x32.png"></bt:Image>
		<bt:Image id="icon1_32x32" DefaultValue="https://fa000000110.resources.office.net/f7024bdc-7caf-4ca8-807d-2908f09640d6/1.0.0.1/en-us_web/apps/wikipedia/images/wikipedia_32x32.png"></bt:Image>
		<bt:Image id="icon1_80x80" DefaultValue="https://fa000000110.resources.office.net/f7024bdc-7caf-4ca8-807d-2908f09640d6/1.0.0.1/en-us_web/apps/wikipedia/images/wikipedia_32x32.png"></bt:Image>
	</bt:Images>
	<bt:Urls>
		<bt:Url id="residDesktopFuncUrl" DefaultValue="https://fa000000110.resources.office.net/f7024bdc-7caf-4ca8-807d-2908f09640d6/1.0.0.1/en-us_web/apps/wikipedia/Wikipedia_dev.html"></bt:Url>
		<bt:Url id="residUnitConverterUrl" DefaultValue="https://fa000000110.resources.office.net/f7024bdc-7caf-4ca8-807d-2908f09640d6/1.0.0.1/en-us_web/apps/wikipedia/Wikipedia_dev.html"></bt:Url>
	</bt:Urls>
	<bt:ShortStrings>
		<bt:String id="residLabel" DefaultValue="Wikipedia Menu"></bt:String>
		<bt:String id="residLabel2" DefaultValue="Wikipedia Button"></bt:String>
	</bt:ShortStrings>
	<bt:LongStrings>
		<bt:String id="residToolTip" DefaultValue="Wikipedia Tooltip"></bt:String>
	</bt:LongStrings>
	</Resources>
</VersionOverrides>
</OfficeApp>
`

**Comment by ChienHo** [comment]
yep, I tried it can show on Desktop app but still invisible on office 365.
![image](https://github.com/OfficeDev/office-js/assets/30323038/2a9e4196-cf84-4d28-b68e-3d0a54762d0c)
![image](https://github.com/OfficeDev/office-js/assets/30323038/2e8ca635-ac48-4453-b193-6e307ab1d918)

**Comment by trigurl** [comment]
OK, thanks for checking.  I will need to follow up with my coworkers in the morning.

**Comment by ChienHo** [comment]
Yes, thanks for the quick response
