### ISSUE TITLE
Using document.insertFileFromBase64 causing issue in header/footer alignment and Data Movement issue in document.

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#3433]
Hello Team,
I am using Word API for developing word add-in. I have used document.insertFileFromBase64 method for opening existing document  that time I found header footer alignment  issue and data movement issue

My Environment
Platform : PC desktop
Host: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2304 Build 16.0.16327.20200) 64-bit
Operating System: Windows 10 pro
Here is my snippest
 ```
context.document.insertFileFromBase64(data, "Replace", {
                            importTheme: true,
                            importStyles: true,
                            importParagraphSpacing: true,
                            importPageColor: true,
                            importChangeTrackingMode: true
                        });
```
Here is my document 
[Original doc.docx](https://github.com/OfficeDev/office-js/files/11766286/Original.doc.docx)
Error Image
<img width="706" alt="Error" src="https://github.com/OfficeDev/office-js/assets/133626379/18d9a52d-5892-46f4-84ec-cbd477478918">

Original
<img width="960" alt="Original" src="https://github.com/OfficeDev/office-js/assets/133626379/0a3c7fd0-b6b3-43f9-ba6e-f28f50931a65">

1)In Footer page number  Text and Page number is in same line but when I open  it using this method that time page no goes to next line(Reason: As per my observation Footer Content Font-size  is changed )
2)In Original image as you can see there is  content  in last line is move to next page so I faced data movement issue also.

**Comment by Searion** [comment]
@Jayshiv1408Dev Thanks for reporting this issue regarding insertfilefrombase64. We have tried this document on several machines and still cannot repro it. Could you please provide more information like screen recording so we can better positioning problem to help you.

**Comment by Jayshiv-IRIS** [comment]
Hi @Searion  ,
Thanks for your response
https://github.com/OfficeDev/office-js/assets/133626379/1e87297c-908b-41df-947e-e00f4f9fc32d

As you can see in this video 
First 20 Seconds I have original document and after that I click on open section where  I called insertFileFromBase64 this method (code snippets given in my main thread) .
where you can see 176 PageNo position getting disturbed (It is on every page I reocorded only one page).

**Comment by Searion** [comment]
Thanks. There seems be a same reason between this and https://github.com/OfficeDev/office-js/issues/3357. If the target document has header/footer styles, they cannot be imported correctly and remain target styles. We will track and fix it.

**Comment by Searion** [comment]
Hi @Jayshiv1408Dev,
The few issues you reported are very helpful for us to improve this API. We are also interested in your usage scenarios. Could you please share contact information for further discussion, it will also help us understand your needs in the first place and make improvements.  You can find me at haigangxi@microsoft.com.
 Thanks.

**Comment by Jayshiv-IRIS** [comment]
Hii @Searion,
Please check I already send my detail on  haigangxi@microsoft.com.

**Comment by Searion** [comment]
@Jayshiv1408Dev Sorry for the late response. I confirmed that this is truely the same issue as https://github.com/OfficeDev/office-js/issues/3357. We have already fixed and deployed it. Please update to the latest m365 version and have a try. Thanks.
