### ISSUE TITLE
PictureContentControl: insert an image with Word.Range.insertInlinePictureFromBase64(base64File, 'Replace') does not work for WordOnline

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#3434]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Laptop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Word Online
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
- it should work like Word for Windows 
- it should work like RichText content control

## Current behavior
- Exception on Word Online: The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information

## Steps to reproduce

1. Create RichText content control and Picture content control
2. insert image into content control using Word.Range.insertInlinePictureFromBase64 api
3. see the exception on Picture Content Control

## Link to live example(s)
```
await Word.run(async (context) => {
    const range = context.document.getSelection();
    range.insertInlinePictureFromBase64(base64Image, "Replace");
    await context.sync();
  });

```
# Provide additional details
Live example

![chrome_fhqOrQDEWn](https://github.com/OfficeDev/office-js/assets/13063615/3d68238b-7d57-43d2-a592-58993a6876b7)

## Useful logs
[ERROR]: Error:
{
    "stack": "RichApi.Error: The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information.\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:330083)\n    at o.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:394249)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:392312",
    "message": "The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information.",
    "name": "RichApi.Error",
    "code": "NotAllowed",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "NotAllowed",
        "message": "The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information.",
        "errorLocation": "Range.insertInlinePictureFromBase64",
        "statement": "var insertInlinePictureFromBase64 = selection.insertInlinePictureFromBase64(...);",
        "surroundingStatements": [
            "var root = context.root;",
            "var selection = root.getSelection();",
            "// Instantiate {selection}",
            "// >>>>>",
            "var insertInlinePictureFromBase64 = selection.insertInlinePictureFromBase64(...);",
            "// <<<<<",
            "// Instantiate {insertInlinePictureFromBase64}"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}
Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by jingxuan0109** [comment]
Thank you for reaching us. The picture content control is not supported on word online yet so that it returns notallowed. We would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.
