### ISSUE TITLE
OnAppointmentSend - Event is not triggered if there are no attendees

### ISSUE THREAD

**Issue by thoffmann-fms** [OfficeDev/office-js#3437]
We have OnAppointmentSend configured and it works fine when there is at least one Required attendee, but when the "Save" button is clicked, no event happens.  

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: All of the above
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2305 Build 16.0.16501.20074) 64-bit 
* Operating System: Win 10
* Browser (if using Office on the web): Edge Canary
 
## Expected behavior
The OnAppointmentSend event should fire for both Save and Send.  Both are logically the same, the user is completing their interaction with the calendar event and we may need to process some attribute values.

## Current behavior
Nothing happens if Save is clicked. Only when Send is clicked does the event trigger.

## Steps to reproduce
Add-In configured for OnAppointmentSend Smart Alert processing.  Create a calendar event.  Update the Location field with something other than an Exchange Resource. Click the Save button.

## Context
We need to have this event fired for both Save and Send since our Add-In may have done some work in our back-end systems related to the calendar event for the person creating a meeting for themselves (e.g. no other attendees). While we may have a Subscription enabled for the person's calendar and eventually will receive a Webhook notification, the UX is poor since error(s) will not be detected  until several minutes later when the Webhook is processed and the user receives an e-mail vs having the error surfaced at the time the Save button is clicked.

## Useful logs
n/a

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by zhngx1** [comment]
Thanks for reporting this issue. The OnAppointmentSend not firing for Save is by design. We recommend you to upvote or create a new [Tech Community](http://aka.ms/M365dev-suggestions) item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue we will re-activate as needed.
