### ISSUE TITLE
Cross origin domain's set cookie is not work in shared browser runtime of custom function

### ISSUE THREAD

**Issue by Emiya0306** [OfficeDev/office-js#3438]
# Cross origin Top-Level domain's cookie is not work in shared browser runtime of custom function

## Your Environment

* Platform: MacOS and PC desktop
* Host: Excel
* Office version number: 16.74 (23061100) and 16.0.16501.20074
* Operating System: MacOS Monterey and Win 10
* Browser (if using Office on the web): Safari and Edge
 
## Expected behavior

- I have a Top-Level domain `.company.io`, two Sub-Level domain `product.company.io` and `add-ins.company.io`.
- SourceLocation in mainfest is 'https://add-ins.company.io', so the page in taskpanel is 'https://add-ins.company.io'.
- Taskpanel page `add-ins.company.io` will post login request to the server `product.company.io`.
- The server `product.company.io` will return the login reponse and set cookie, which domain is `.company.io`.
- So, Taskpanel page `add-ins.company.io` is logged in and the cookie is set successfully.

These actions should work in taskpanel and custom function shared runtime both.

## Current behavior

The cookie which domain is `.company.io` is worked in taskpanel, but failed in custom function shared runtime.
In my opinion, if custom function is shared runtime with taskpanel, their behavior should be the same.

**In fact, if the login server and add-ins server's domains are the same, the cookie can be set successfully.** So I think if there is not cross origin, the cookie is work. But it is not good idea for my system. 😭 

# Provide additional details

```xml
<!-- mainfest.xml -->
<OfficeApp>
  ...
  <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="ExcelApi" MinVersion="1.1"/>
      <Set Name="SharedRuntime" MinVersion="1.1"/>
    </Sets>
  </Requirements>
  ...
  <DefaultSettings>
    <SourceLocation DefaultValue="https://add-ins.company.io"/>
  </DefaultSettings>
  ...
  <VersionOverrides>
    <Host xsi:type="Workbook">
      <Runtimes>
        <Runtime resid="Taskpane.Url" lifetime="long"/>
      </Runtimes>
      <AllFormFactors>
        <ExtensionPoint xsi:type="CustomFunctions">
          <Script>
            <SourceLocation resid="Functions.Script.Url"/>
          </Script>
          <Page>
            <SourceLocation resid="Taskpane.Url"/>
          </Page>
          <Metadata>
            <SourceLocation resid="Functions.Metadata.Url"/>
          </Metadata>
          <Namespace resid="Functions.Namespace"/>
        </ExtensionPoint>
      </AllFormFactors>
      ...
    </Hosts>
    <Resources>
      ...
      <bt:Urls>
        <bt:Url id="Taskpane.Url" DefaultValue="https://add-ins.company.io"/>
        <bt:Url id="Functions.Script.Url" DefaultValue="https://add-ins.company.io/static/js/functions.js"/>
        <bt:Url id="Functions.Metadata.Url" DefaultValue="https://add-ins.company.io/static/js/functions.json"/>
      </bt:Urls>
      ...
    </Resources>
  </VersionOverrides>
</OfficeApp>
```

## 1. Only failed in custom function
<img width="1037" alt="login request" src="https://github.com/OfficeDev/office-js/assets/12878132/ef5d69f2-b7a3-4b6d-8340-1e0534e76e79">
Pic 1. Login success and product.company.io set-cookie

<img width="1037" alt="request logged in api" src="https://github.com/OfficeDev/office-js/assets/12878132/7dbfb780-48b0-4b20-b1f9-522a951bdbce">
Pic 2. If request logged in api, lost the cookie and failed in 401

## 2. Success in task panel and failed in custom function

<img width="912" alt="6916870654771_" src="https://github.com/OfficeDev/office-js/assets/12878132/8297c991-9505-4acd-b83c-3690c5c0912f">

<img width="850" alt="image" src="https://github.com/OfficeDev/office-js/assets/12878132/0fb68130-aaf5-4ace-b8d2-41372fe51079">

## 3. If the domains are the same, the cookie work well. But it is not good idea for me.

<img width="1387" alt="711687070682_ pic" src="https://github.com/OfficeDev/office-js/assets/12878132/27d0fafd-079f-4455-8f4c-26e4b814e91a">

<img width="1406" alt="731687071576_ pic" src="https://github.com/OfficeDev/office-js/assets/12878132/8e3e5547-770c-4da5-891b-95a6b2735dd4">

## Useful logs

- [x] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by SiruiSun-MSFT** [comment]
Thanks for waiting! We assume that the CF add-in with shared runtime should not have this problem. Could you use CF to try to call the Excel JS API to verify whether the shared runtime configuration is successful? If yes, perhaps we need to have a deeper understanding of your scenario and then provide a more detailed response.

**Comment by SiruiSun-MSFT** [comment]
Thanks for reporting this issue. After careful consideration, our team has decided to not fix this issue in the short term. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.
Thanks again!
