### ISSUE TITLE
Office.context.mailbox.userProfile always returns user profile of primary account in a multi-account setup in Outlook Desktop client

### ISSUE THREAD

**Issue by ottD** [OfficeDev/office-js#3439]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

# Office.context.mailbox.userProfile always returns user profile of primary account in a multi-account setup in Outlook Desktop client
In a multi-account setup in the new Outlook Desktop client, `Office.context.mailbox.userProfile` always returns the user profile of the primary account regardless of the actual account where the selected email(s) reside(s) when called in Message Read mode with a mail message selected. This occurs when the primary account is an `outlook.com` account and the account where the message is selected and the task pane add-in invoked on is a different Microsoft 365 account. 

## Your Environment

* Platform: PC Desktop
* Host: Outlook Desktop client (New Outlook)
* Office version number: 2304 (16327.20248)
* Operating System: Windows 11 22H2 (OS Build 22621.1848)
 
## Expected behavior

When invoked in a Message Read context, I expected `Office.context.mailbox.userProfile` to return the userProfile of the user associated with the account that contains the currently selected mail item and not the primary account user profile unless the selected mail item belongs to the primary account. 

## Current behavior

When invoked in a Message Read context and having a multi-account setup, with the primary account being an `outlook.com` account, `Office.context.mailbox.userProfile` always returns the userProfile of the user associated with the `outlook.com` account even if the currently selected mail item belongs to a different Microsoft 365 account. 

## Steps to reproduce

1. Setup the new Outlook Desktop client with at least one `outlook.com` account and one Microsoft 365 account
2. Ensure the `outlook.com` account is the primary account
3. Install Script Lab for Outlook
4. Select an email in the Inbox of the Microsoft 365 account and invoke the Script Lab for Outlook add-in
5. Run the following script that invokes `Office.context.mailbox.userProfile` 
```typescript
$("#run").click(run);

function run() {
  const userProfile = Office.context.mailbox.userProfile;
  const item = Office.context.mailbox.item;
  console.log(`Hello ${userProfile.displayName} (${userProfile.emailAddress})`);
  console.log(`AccountType:  ${userProfile.accountType}`);
  console.log(`Email subject: ${item.subject}`);
}
```
6. Observe the script output 

## Link to live example(s)

Script Lab script
https://gist.github.com/ottD/316cf2186b3943ecf861cd695bd9949e

## Context

I'm trying to get the userID associated with the account that the currently selected mail item belongs to. The below snippet works as expected with the legacy Outlook and OWA but not in the new Outlook with multiple accounts as described above. 

```typescript
/**
 *  Retrieve the user id (SMTP address) of the delegated or shared mailbox.
 *  If the mailbox is not shared, the user id of the primary mailbox is returned.         
 */
export async function getMailboxUserId(): Promise<string> {
    return new Promise((resolve, reject) => {
        if (Office.context.mailbox.item.getSharedPropertiesAsync) {
            // In Windows, Mac, and the web client, this indicates a shared item so use SharedProperties properties to get targetMailbox
            Office.context.mailbox.item.getSharedPropertiesAsync(
                function (asyncResult) {
                    if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
                        console.error(`Getting shared properties failed with error: ${asyncResult.error.message}`);
                        return reject(asyncResult.error);
                    } else {
                        return resolve(asyncResult.value.targetMailbox);
                    }
                });
        } else {
            // non-shared item: return user id of primary mailbox user
            return resolve(Office.context.mailbox.userProfile.emailAddress);
        }
    });
}
```

## Useful logs

- [x] Screenshots
<img width="1910" alt="image" src="https://github.com/OfficeDev/office-js/assets/33263347/dbfd7cd0-e4b8-477a-8e93-99c72bbcd089">

**Comment by exextoc** [comment]
Thank you for reporting the issue. We are able to repro it and will update the thread once we have more details on the timelines.

**Comment by Gaurav-Dhyani** [comment]
Still facing the same issue on the latest outlook for windows as well as mac.
