### ISSUE TITLE
chinese charactor support

### ISSUE THREAD

**Issue by dirtyluke** [OfficeDev/office-js#344]
hi there 
when i try to give a name to a series on a line chart in an excel file and the name was in chinese , after i run the code the name was garbled
here is part of the code
`let newSeries = chart.series.add("振华");`
and i got `æ¯å`

**Comment by kbrandl** [comment]
@dirtyluke Thanks for reaching out and sorry to hear that you've run into this problem. Issues in this GitHub repository (**OfficeDev/office-js-docs**) are intended for engaging with the product team about the Office JavaScript API open specifications.  Therefore I'm transferring this issue to the **OfficeDev/office-js** repository, which members of the product team monitor for customer-reported API issues such as this.

**Comment by lumine2008** [comment]
@dirtyluke, would you please try the following code, it works for me to add chinese characters 
let newSeries = seriesCollection.series.add("振华");


full code can be found at here:
async function addSeries() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getItem("Sample");

    let seriesCollection = sheet.charts.getItemAt(0);
    let rangeSelection = sheet.getRange("C2:C7");
    let xRangeSelection = sheet.getRange("A1:A7");

    // Add a series.
    let newSeries = seriesCollection.series.add("振华");

    newSeries.setValues(rangeSelection);
    newSeries.setXAxisValues(xRangeSelection);

    await context.sync();
  });
}

please let me know if you have follow up questions, thanks

**Comment by lumine2008** [comment]
this is the screenshot for the demo
![image](https://user-images.githubusercontent.com/26398035/51881596-c6552680-23b6-11e9-89b3-e5f73c2bf05f.png)

**Comment by lumine2008** [comment]
@dirtyluke which platform are you experiencing this issue?

**Comment by lumine2008** [comment]
i am closing this issue, please reactive if you have additional question about it
