### ISSUE TITLE
Not able to open web add-in after selecting multiple emails in New Outlook 

### ISSUE THREAD

**Issue by Rajnish-Asite** [OfficeDev/office-js#3441]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows, OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 1.2023.607.100 (Production)
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Web add-in should be activated after selecting multiple emails in new outlook.

## Current behavior
Web add-in is activated after selecting multiple emails in old outlook as attached below-
![Screenshot 2023-06-20 112020](https://github.com/OfficeDev/office-js/assets/135962980/2717490a-72ba-4fb7-a9c9-4fe8979690fd)

But in new outlook there is no option to open web add-in after selecting multiple emails as attached below-
![image](https://github.com/OfficeDev/office-js/assets/135962980/0c1d164f-5d5b-445c-a9e3-fee8241babb1)

## Steps to reproduce

1. Switch to New Outlook
2. Select Multiple emails

## Context

As VSTO Plugin is no longer supported in new outlook So we are expanding our web add-in features So we are trying to save multiple emails from web add-in and it is supported in old outlook as per given in below document
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select
But it is not supported in new outlook as we are trying to achieve this but web add-in option is not available after selecting multiple emails from new outlook.

Please do needful asap.

**Comment by exextoc** [comment]
We are not able to repro this issue. Can you please share manifest being used.

**Comment by Rajnish-Asite** [comment]
Hi @exextoc Please refer below manifest file for check multiple selection in new outlook and old outlook both-

[manifest-qa.zip](https://github.com/OfficeDev/office-js/files/11829297/manifest-qa.zip)

**Comment by exextoc** [comment]
@Rajnish-Asite Thanks for reporting this issue. We can repro the issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 214862

**Comment by Rajnish-Asite** [comment]
@exextoc Thanks for updating us. We are looking forward to have this feature enabled in New outlook asap.

**Comment by nhdang1998** [comment]
Hi, I'm very interested in this topic as well

**Comment by exextoc** [comment]
This issue has been fixed. Closing.
