### ISSUE TITLE
Can we open Outlook web add-in task pane using Event Based Actiavation

### ISSUE THREAD

**Issue by Rajnish-Asite** [OfficeDev/office-js#3445]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows, OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2305 Build 16.0.16501.20074) 64-bit 
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Outlook web add-in should be open automatically when we send new email.

## Current behavior

We have tried Event base activation to open web add-in when sending new email but outlook web add-in is not opened.

## Steps to reproduce

We are using https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest#smart-alerts-feature-behavior-and-scenarios document to activate Event based activation but it is showing soft Alert instead of opening outlook web add-in as below-
![image](https://github.com/OfficeDev/office-js/assets/135962980/f2359e6a-c4ea-4bed-b8fa-3321ab89c451)

Please do needful asap.

**Comment by exextoc** [comment]
@Rajnish-Asite Opening taskpane from event based activation is not supported. Can you share the manifest being used here and code snippet of how you are trying to open the add-in.

**Comment by Rajnish-Asite** [comment]
@exextoc thanks for your answer But I just want to know that is there any way from which we can open outlook web add-in task pane functionally?

**Comment by exextoc** [comment]
Currently this is not supported by add-ins framework. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

Github Label: “Type: product feature request”
https://aka.ms/M365dev-suggestions

**Comment by Rajnish-Asite** [comment]
@exextoc Thanks for the update. New Feature request has been raised on your [Tech Community Page](http://aka.ms/M365dev-suggestions) as given below- 
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/autoopen-outlook-web-add-in-task-pane-functionally/idi-p/3856447

**Comment by fomin-grigorich** [comment]
@Rajnish-Asite Hello! Is there any progress on the feature to open add-in programmatically or any new autoOpen features relates to this issue? I'm looking for functionality to autoOpen add-in panel when "OnNewMessageCompose" event is firing. Are you requesting something similar?

**Comment by Rajnish-Asite** [comment]
Hi @fomin-grigorich I need to open web add-in when Launch Event "OnMessageSend" is fired.

As per previous comment of @exextoc right now there is no any functionality supported from which we can open outlook web add-in programmatically. I am also waiting for this feature.

Please also let me know if you get anything update on this.

Thanks.

**Comment by himanshuhashtag** [comment]
Is there any update from Microsoft regarding this issue?

**Comment by Rajnish-Asite** [comment]
@himanshuhashtag No we don't get any update yet.

**Comment by himanshuhashtag** [comment]
> @himanshuhashtag No we don't get any update yet.

Thank you so much for quick response.

**Comment by fomin-grigorich** [comment]
@Rajnish-Asite @himanshuhashtag As workaround we used PINNABLE ADD-IN functionality. Maybe it can be useful for you as well. https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/pinnable-taskpane?tabs=xmlmanifest

**Comment by Rajnish-Asite** [comment]
> @Rajnish-Asite @himanshuhashtag As workaround we used PINNABLE ADD-IN functionality. Maybe it can be useful for you as well. https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/pinnable-taskpane?tabs=xmlmanifest

@fomin-grigorich Thanks for your suggestion but we don't want to open add-in everytime using Pin functionality. That's why we can not prefer Pin functionality.

FYI @himanshuhashtag

**Comment by himanshuhashtag** [comment]
> @Rajnish-Asite @himanshuhashtag As workaround we used PINNABLE ADD-IN functionality. Maybe it can be useful for you as well. https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/pinnable-taskpane?tabs=xmlmanifest

Actually I want to open task pane automatically on just opening the mail.

**Comment by Sophie1142** [comment]
> Actually I want to open task pane automatically on just opening the mail.

Upvote on this.

**Comment by devnomanaslam** [comment]
Hi, just checking in to see if there are any updates on this.

**Comment by strtob** [comment]
Same here—any updates? We urgently need the functionality!
