### ISSUE TITLE
Can we get outlook change Notifications from web add-in in background without opening web add-in task pane

### ISSUE THREAD

**Issue by Rajnish-Asite** [OfficeDev/office-js#3446]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows, OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2305 Build 16.0.16501.20074) 64-bit
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Change Notifications should get in background process in web add-in using runtime javascript.

## Current behavior

We preferred below document to implement outlook web add-in change notifications from webhook
https://learn.microsoft.com/en-us/graph/change-notifications-delivery-webhooks?tabs=http

We also received notifications but we only received notifications if web add-in task pane is opened. We should get notifications in background as well.

## Context

We have a functionality to save emails directly on cloud using created rules So when new emails comes in outlook it will automatically save to our cloud. We have developed this functionality in VSTO But now we need to implement same in web add-in So We need to listen outlook notifications from web add-in in background.

Please do needful asap.

**Comment by exextoc** [comment]
At present, web add-ins can be activated either by direct user interaction with the UI or by indirect interaction with mail or event via LaunchEvents. The supported launch events include those listed at https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest#supported-events. 
However you can raise a new feature request on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

Github Label: “Type: product feature request”
https://aka.ms/M365dev-suggestions

**Comment by Rajnish-Asite** [comment]
@exextoc thanks for the update but we do not have any LaunchEvents listed in which we can get outlook change notifications from web add-in. So yes I will raise new request on Community page.

Thanks for the update.

**Comment by Rajnish-Asite** [comment]
@exextoc Some one has already create same feature request So I also commented in the same and the link is given below-
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/outlook-add-ins-can-we-have-a-new-event-that-trigger-if-any-new/idc-p/3856453/highlight/true#M1845

Thanks.
