### ISSUE TITLE
New Outlook View is not supporting our application in Web Addin. 

### ISSUE THREAD

**Issue by CG49071** [OfficeDev/office-js#3447]
Our application does not support in Outlook Web browser. In similar way, it is not working on the New Outlook View. Can you please provide any documentation related to the changes in Web Addin.

**Comment by exextoc** [comment]
Please mention details of issue being faced. Is the add-in not launching? Please provide a screenshot or repro video if possible.

**Comment by CG49071** [comment]
We are not supporting our application in Add-in when Office.context.diagnostics.platform==='OfficeOnline' (https://learn.microsoft.com/en-us/javascript/api/office/office.platformtype?view=excel-js-preview). Due to security policy, our application support in Dekstop Add-in only, does not open in iframe in Web browser Add-in and we are getting same platform Office.context.diagnostics.platform when we are opening our application in Add-in from New Outlook View.

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 213914

**Comment by CG49071** [comment]
1. UKG Outlook Integration Plugin works only on the Outlook Desktop. Due to security reasons, our application does not open in iframe so it is not supported on Outlook web version.
2. UKG does not support its application in Outlook Web when Office.context.diagnostics.platform==='OfficeOnline' (https://learn.microsoft.com/en-us/javascript/api/office/office.platformtype?view=excel-js-preview).
3. New Outlook Add-in seems to be similar like Outlook Web that's is why Customer is unable to open our application in New Add-in. We investigated and found that new Outlook Add-in also have Office.context.diagnostics.platform==='OfficeOnline' . 
4. It is expected that our customers should be able to continue using the Add-in released to them on desktop version earlier. We need to discuss further to find the resolution to continue usage of our Add-in desktop version with new feature enabled

**Comment by CG49071** [comment]
Is there any update on this ticket?

**Comment by JuaneloJuanelo** [comment]
This is actually by design. The New outlook is basically Outlook Web Client with a win32 frame. So if your add-in does NOT work in Outlook for the Web it will NOT work in the new Outlook.

The solution here is that you need to support Outlook on the Web.

**Comment by exextoc** [comment]
If you want to differentiate between Outlook Web and New Outlook please use API office.context.mailbox.diagnostics, hostName under diagnostics will return "OneOutlook" for New Outlook.
