### ISSUE TITLE
Integrated Apps Centralized Deployment not working for users in Outlook desktop

### ISSUE THREAD

**Issue by ArjunSureshKumar92** [OfficeDev/office-js#3448]
We have been using Centralized Deployment option to provide our outlook addin to customers for some time. However, recently we have noticed the app deployment taking longer to show up for users.

From testing last week, we have noticed the addin doesnt show up in outlook for users even after waiting for more than 4 days. In the past, the max delay we had noticed was close to 6 hours but we are concerned its no longer a delay issue, but rather a bug with the deployment.

Attaching related screenshots:

![image](https://github.com/OfficeDev/office-js/assets/35875176/beb1cf36-d99e-42c3-a21f-a56e1250fb01)

This addin was deployed last Friday. It is a simple custom app for outlook. And is only assigned for one user: Abs.

![image](https://github.com/OfficeDev/office-js/assets/35875176/d3f50359-d4d2-40ac-a842-1e7e626dab7d)

Outlook desktop screenshot for the user Abs.

 

No addin in the ribbon and also it is not showing up in the "Admin-managed" section.

![image](https://github.com/OfficeDev/office-js/assets/35875176/b328b691-4b46-4bd8-82c9-64f5c3a7137b)
![image](https://github.com/OfficeDev/office-js/assets/35875176/958dc99b-edb7-41a3-8156-259962e49ece)

**Comment by exextoc** [comment]
Can you confirm if this issue also occurs with the new Outlook desktop and Outlook Web versions?

**Comment by ArjunSureshKumar92** [comment]
Yes the issue exists in both.

**Comment by exextoc** [comment]
Can you please help with the organization domain and the user's alias?
Also, can you please share the fiddler trace for the affected user, if possible? Launch fiddler -> Relaunch Outlook Web -> Click on Get-AddIns button -> Stop capturing fiddler trace and share the fiddler.
