### ISSUE TITLE
[Office.js] Office.context.mailbox.item.body.getAsync is not working  on Lenovo K5 Note

### ISSUE THREAD

**Issue by anilreddyr7** [OfficeDev/office-js#345]
I'm facing the same issue with one of my android devices. 
Device Info:
Lenovo K5 Note
Android Version:6.0

I need to use Office.context.mailbox.item.body.getAsync in order to get the content of an email, but the callback is never called. It is working fine in desktop outlook client, webapp and even mobile web browser as well. It is an issue with mobile android outlook client. Is this the bug from Office Js?

_Originally posted by @anilreddyr7 in https://github.com/OfficeDev/office-js/issue_comments#issuecomment-450107384_

**Comment by kbrandl** [comment]
@anilreddyr7 sorry to hear that you've run into this problem. @exextoc are you able to provide any feedback about this issue?

**Comment by exextoc** [comment]
This was an issue impacting body.getAsync on Android that was fixed in January per #326
