### ISSUE TITLE
Word Add-in: How to programatically enable 'Different First Page' setting from the ribbon using Office Add-in js?

### ISSUE THREAD

**Issue by VelinGeorgiev** [OfficeDev/office-js#3450]
## How to programatically enable 'Different First Page' setting from the ribbon using Office Add-in js?

I am using the Office Add-in js version 1.4, but I cant seem to find a way to automatically enable the 'Different First Page' setting.

Expected: To be an API to change this setting.
Actual: All my attempts failed.

![image](https://github.com/OfficeDev/office-js/assets/1049476/14a4b5c6-a029-4b11-993b-288c5cc4fb8f)

I have tried setting the `<w:titlePg/>` and part of the section XML using ooxml with no success.

When I execute  Office.context.document.setSelectedDataAsync(...<w:titlePg/>...) this tag gets removed during the XML parsing therefore never saved with the document. 

Is there a different way to enable this setting?

**Comment by jipyua** [comment]
Thanks for reaching out. For now there is an API to get the header of the first page: context.document.sections.getFirst().getHeader(Word.HeaderFooterType.firstPage).insertText("sample", "Start"); But there isn't an existing API yet to enable the "Different First Page" setting. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum]( https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests are considered when we go through our planning process. Thanks.

**Comment by VelinGeorgiev** [comment]
This is so unfortunate as it will not allow to fully automate the process of inserting different headers (using `.getFirst().getHeader(Word.HeaderFooterType.firstPage).insertText("sample", "Start")`) then opting in for the 'Different First Page' to visualize the changes to the user. 

Instead the user will have to preform extra manual action or the Word template has to have the 'Different First Page' setting pre-selected, and many clients won't opt for both options mentioned above. 

Adding a feature request to the [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions) is a great idea, but enterprises and businesses would not normally go to vote there. 

I guess I will have to leave with the fact that the office add-ins don't offer rich apis.

Thanks for your response @jipyua !

**Comment by pki89** [comment]
any chance this will be added in the future @jipyua?
