### ISSUE TITLE
Outlook Event-based Activation - CORS broken for Windows/Mac, works for OWA

### ISSUE THREAD

**Issue by thoffmann-fms** [OfficeDev/office-js#3452]
I'm developing  OnAppointmentSend.  It all works fine in OWA, but Windows Outlook and MacOS Outlook both fail the Fetch processing with `<pre>Cannot POST /token</pre>`

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:  PC desktop, Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2305 Build 16.0.16501.20074) 64-bit 
* Operating System: Windows 10
* Browser (if using Office on the web): Any
 
## Expected behavior
fetch should work

## Current behavior
Windows fails the Fetch. Buried in the run-time it attempts to parse JSON and instead receives this HTML and then throws a generic error back to the calling code. Mac is hard to debug so I'm not positive of that failure there but it looks like it's getting a similar non-JSON response.
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /token</pre>
</body>
</html>
```

## Steps to reproduce
Code snippet from launchevent.js. Run from OWA everything is fine.

I've tried explicitly adding "mode: 'cors'" but to no effect.

launchevent.js comes from https://localhost:3000 (nodes.js)
hostUrl is http://localhost:51413 (IIS Express)

```
  const body =
    "username=" +
    FixURIComponent(who) +
    "&password=" +
    FixURIComponent(userToken) +
    "&scope=https%3A%2F%2Fxxx.xxx&grant_type=password";
  try {
    const tokenResult = await fetch(hostUrl + "/token", {
      method: "POST",
      body: body,
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
    });

    const tokenJson = await tokenResult.json();
    oAuthToken = tokenJson.access_token;
```

## Context
Makes it basically impossible to develop OnAppointmentSend code.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Oleg-O** [comment]
To enable CORS for an Event-Based add-in, you should add a well-known resource. Documentation for that is here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/use-sso-in-event-based-activation (the same file is used for SSO and to enable CORS). We have an item in our backlog to improve documentation for Event-Based add-ins to make that clear.

Also, it's best to use an "http**S**://" hostUrl (as opposed to "http://").

**Comment by thoffmann-fms** [comment]
I don't need/use SSO. I'm getting a OAuth token for our API which uses its own authentication.
p.s. This ticket is an unintentional repeat of https://github.com/OfficeDev/office-js/issues/3451.  I'll look into that JSON file to see if that helps.  Also, using HTTP only for dev work, IIS Express HTTPS isn't always simple and can cause cert errors in some client stacks.

**Comment by Oleg-O** [comment]
Sounds good. To clarify, SSO is not a requirement for CORS, both just use the same well-known resource which is needed if you use either. Let us know if this solves the issue for you!

**Comment by ilbrando** [comment]
@thoffmann-fms  Did .well-known solve the issue? I'm struggling with something similar (see #3457). I can't get fetch to work and I have tried with .well-known.
By the way does `async/await` work in your event handler? I didn't know it was supported:
From the [documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest#check-manifest-and-javascript-requirements):
![image](https://github.com/OfficeDev/office-js/assets/11632690/54b83f94-4c60-4850-8a9c-ef16a483137c)

**Comment by Oleg-O** [comment]
@thoffmann-fms I'm closing this since you're following up on #3451 .
