### ISSUE TITLE
Excel Addin: How to get the copied ranges from clipboard

### ISSUE THREAD

**Issue by svasile8** [OfficeDev/office-js#3454]
I want to add actions on copy and paste actions on ranges and i didn't found any way to get the copied ranges from clipboard. Also, it seems that there are no events for CTRL+C and CTRL+V actions.

Expected: To have events for CTRL+C and CTRL+C actions.
Actual: Didn't find any.

There is any way to achieve this with officejs?

**Comment by dingjin-ms** [comment]
Hi @svasile8 , sorry for the late response and thank you for raising the problem.

Unfortunately, we do not support get copied range or related events for now. For range copy actions, we only support copying and pasting by the API (seen in [doc)](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-ranges-cut-copy-paste). And the events we support are all listed [here](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-events).

In a word, these two asks are new feature requests. And we would like to suggest you to our forum to raise a new ticket: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform. Our PM team would go through the feature requests regularly, choose to pick up and do the planning.
