### ISSUE TITLE
Using Document.insertFileFromBase64 () method to Open Word Document Bullet Number getting reset

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#3455]
Hello Team,
I am using Word API for developing word add-in. I have used document.insertFileFromBase64 method for opening existing document that time I found that Bullet number getting reset.

My Environment
Platform : PC desktop
Host: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2304 Build 16.0.16327.20200) 64-bit
Operating System: Windows 10 pro
Here is my snippest

```
context.document.insertFileFromBase64(data, "Replace", {
                           importTheme: true,
                           importStyles: true,
                           importParagraphSpacing: true,
                           importPageColor: true,
                           importChangeTrackingMode: true
                       });
```
Here is my source file
[sourcefile.docx](https://github.com/OfficeDev/office-js/files/11815912/sourcefile.docx)
Here is my Output file(which I open using  insertFileFromBase64() )
[error.docx](https://github.com/OfficeDev/office-js/files/11815938/error.docx)

Image:
<img width="677" alt="BulletNo_error" src="https://github.com/OfficeDev/office-js/assets/133626379/64caecb8-e555-48cf-a6de-67f54c3b40b1">
<img width="673" alt="BulletNo_Original" src="https://github.com/OfficeDev/office-js/assets/133626379/8fd8efda-f081-46b4-8366-fd941eb905bc">

**Comment by Searion** [comment]
Thanks for reporting this issue. However, we cannot repro it. Could you please provide more information like screen recording or the target document before you insert the file?
