### ISSUE TITLE
In Outlook add-in OnMessageSend event I can't call fetch in Outlook for Windows

### ISSUE THREAD

**Issue by ilbrando** [OfficeDev/office-js#3457]
NOTE! I only experience this in Outlook for Windows not in Outlook for web.

I'm trying to call fetch from a OnMessageSend event handler but can't make it work. Nothing happens and as far as I can tell no exceptions are thrown. 

# Provide required information needed to triage your issue

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® til Microsoft 365 MSO (Version 2305 Build 16.0.16501.20074) 64-bit 
* Operating System: Windows 11
* Browser (if using Office on the web): ______
 
## Expected behavior
I expected fetch to call my backend or at least throw an error.

## Current behavior
Nothing happens.

## Steps to reproduce
I can't share my own project, but I can reproduce the problem by creating [this project](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest) from the documentation.

And then replace the code in `onMessageSendHandler` with this:

```javascript
fetch("https://www.microsoft.com", { method: "GET" })
  .then((response) => {
    event.completed({ allowEvent: false, errorMessage: `TEST ${response.ok}` });
  })
  .catch((error) => {
    event.completed({ allowEvent: false, errorMessage: `ERROR ${error}` });
  });
```
I know there can be some CORS issues and in my own project I have taken that into account by including the backend URL in AppDomains in the manifest file and providing af .wellknown/microsoft-officeaddins-allowed.json endpoint/file. But I think I at least should have some error if CORS is an issue.

I have also tried to replace `fetch` with `XMLHttpRequest` in order to see if that would return some usefull error, but it didn't.

**Comment by timwan10** [comment]
This seems somewhat similar to: https://github.com/OfficeDev/office-js/issues/3452

Though it appears in that issue they are getting the actual error. (could it be you are also getting the same error but due to the error not coming through as JSON, it's not being reported to you?) 

The solution would be the wellknown file, but it sounds like you are already using that. Is it possible there is an error in that file?

**Comment by ilbrando** [comment]
Yes it looks similar, but I have the ./well-known file.

![image](https://github.com/OfficeDev/office-js/assets/11632690/6fbc7efb-cd50-4174-9e1f-acf03c285c78)

```json
{
  "allowed": [
    "https://localhost:3000/event-handler-os-windows.js"
  ]
}
```
And I have tested that it is returned when I enter the URL for it in the browser.

I still find it strange that I get no errors at all.

**Comment by ilbrando** [comment]
Hi @exextoc
Are there any news regarding this? It must be a very common use case to call some backend. I would really appreciate an example of how it is supposed to be done.

**Comment by ilbrando** [comment]
I have managed to get it to work. I switched to `XMLHttpRequest` because `fetch` failed without any errors (it appears as nothing happened). With `XMLHttpRequest` I found that I was missing a `Content-Type` header.

**Comment by ilbrando** [comment]
Apparently I ran into som more issues which are not that easy to figure out.
Outlook is very sensitive to "bad" javascript and gives no information about any errors.
It turned out that when I somewhere in the javascript file used the spread (`...`) operator, nothing worked. Even when is was in a code block that wasn't used/called. I don't understand why this is not supported because as far as I know it is an ES6 feature.
It would be nice if Outlook is more explicit in showing such errors.

**Comment by timwan10** [comment]
Have you already tried: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging

many errors are reported through runtime logging, and it can be helpful. (though this should NOT be turned on for production environments as it will affect performance). But to help catch issues, it can sometimes catch the "bad" javascript issues.
