### ISSUE TITLE
callback function is not called in dialog on Office.context.ui.addHandlerAsync

### ISSUE THREAD

**Issue by yokotaso** [OfficeDev/office-js#3458]
# Provide required information needed to triage your issue
I open Office.Dialog in Office-Addin Same-Origin, then redirect to cross domain site.
At redirected web site, I install Office.js, and write like bellow code:

```javascript
Office.onReady(() => {
    Office.context.ui.addHandlerAsync(Office.EventType.DialogParentMessageReceived, 
    (r) => console.log(r),
   (r) =>  console.log(r)
);
});
```
But, any log is not displayed. I tested above code with Same-Origin Page,
I confirm bellow log.

```
{
    "status": "succeeded"
}
```

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: version 2305 Build 16.0.16501.20074
* Operating System: Windows11
* Browser (if using Office on the web): ______
 
## Expected behavior

According to document, Office.Dialog.messageChild is able to send message to dialog 
ofwhich site is cross domain from Office-addin host.
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#cross-domain-messaging-to-the-dialog-runtime

There are no ways to confirm output of Office.Dialog.messageChild on cross-domain.

## Current behavior

Failed to register `Office.EventType.DialogParentMessageReceived` with `Office.context.ui.addHandlerAsync`

## Steps to reproduce

1. Call Office.context.ui.displayDialogAsync
2. Open Same-Site page in Dialog
3. Redirect to Cross-SIte page
4. At Cross-Site page, load office.js and execute bellow code:
```javascript
Office.onReady(() => {
    Office.context.ui.addHandlerAsync(Office.EventType.DialogParentMessageReceived, 
    (r) => console.log(r),
   (r) =>  console.log(r)
);
});
```

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ndeleuze** [comment]
@yokotaso do you have each domain defined in the AppDomains element of the Add-in manifest?

More detail [here](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/xml-manifest-overview?tabs=tabid-1#specify-safe-domains-with-the-appdomains-element)

**Comment by ilbrando** [comment]
I am experiencing the same issue and it appears that the handler is never registered - messages to the dialog aren't received.
This works in the web version and in some versions (environments) with the Windows version, but not all. I'm not able to pinpoint exactly what the difference in environments can be the cause of this. it works on my own PC Windows 11/Outlook 2311, but not on our hosting environment Windows 10/Outlook 2310.
