### ISSUE TITLE
Office.EventType.AttachmentsChanged is not triggered after removing file in the previous email

### ISSUE THREAD

**Issue by manaunl** [OfficeDev/office-js#3459]
# Provide required information needed to triage your issue
I am using event-based activation to react when the user attached or remove a file to an email. The problem that I encounter that after the user removes the file, next time they compose a new email the `AttachmentsChanged` is not triggered

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: MacOS Ventura 13.4
* Browser (if using Office on the web): Chrome Version 114.0.5735.133 (Official Build) (x86_64)
 
## Expected behavior

`Office.EventType.AttachmentsChanged` is triggered on attaching a file

## Current behavior

`Office.EventType.AttachmentsChanged` is not triggered on attaching a file

## Steps to reproduce

1. Compose new email
2. Click on the button "Attach file" and select one of the Suggested files or one from your machine
4. Check that `Office.EventType.AttachmentsChanged` event is triggered
5. Remove attachment
6. Send email
7. (Do not reload the page) Compose new email
8. Click on the button "Attach file" and select one of the Suggested files or one from your machine
9. Check that `Office.EventType.AttachmentsChanged` event is **not** triggered

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@manaunl We are unable to repro the issue. Can you please share code snippet for event handler function or manifest?

**Comment by manaunl** [comment]
Here is the part on the manifest we are using to activate add-in based in the events: 
```
<ExtensionPoint xsi:type="LaunchEvent">
   <LaunchEvents>
      <LaunchEvent Type="OnMessageCompose" FunctionName="onMessageComposeHandler"/>
      <LaunchEvent Type="OnMessageAttachmentsChanged" FunctionName="onMessageAttachmentsChangedHandler" />
      <LaunchEvent Type="OnMessageRecipientsChanged" FunctionName="onMessageRecipientsChangedHandler" /> 
   </LaunchEvents>
   <SourceLocation resid="eventBasedActivationUrl"/>
</ExtensionPoint>
```

The url to activate:
```
<Resources>
....
   <bt:Urls>
      <bt:Url id="eventBasedActivationUrl" DefaultValue="https://localhost:3000/v6/index.html#/entry/event"></bt:Url>
       ....
   </bt:Urls>
....
```

Here is the part on the manifest we are using to activate add-in based in the events: 
```
Office.actions.associate('onMessageAttachmentsChangedHandler', event => {
   console.log('onMessageAttachmentsChangedHandler');
});
```

In out case after the steps I described the onMessageAttachmentsChangedHandler is not triggered.

**Comment by exextoc** [comment]
@manaunl Please add event.completed() in handler code and try again.

**Comment by manaunl** [comment]
I tried to add event.completed() for each for the handler that we have, but none of them is completed after I call this function. 
But we use this function for onItemSend action and for it works perfectly fine for it.

**Comment by exextoc** [comment]
@manaunl Could you please confirm the platforms in which you are able to repro the issue? Is it OWA or MAC as the repro steps include "(Do not reload the page) Compose new email" which is specific to OWA?

**Comment by manaunl** [comment]
We are using the add-in for outlook 365 on web in Chrome browser, the operating system is Mac

**Comment by exextoc** [comment]
@manaunl Thanks for reporting this issue We are able to repro the issue. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

Internal tracking id: Eg: Office: 216121

**Comment by shighosh-msft** [comment]
After further investigation, we have found that the Event is successfully getting fired for the set of steps that you shared for this issue.

If you are still experiencing this problem, we recommend trying the latest OWA build to see if the issue has been resolved. If you encounter any further difficulties, please don’t hesitate to reach out, and we’ll be happy to assist.
