### ISSUE TITLE
Outlook OWA not showing add-ins in ribbon

### ISSUE THREAD

**Issue by williamkolega** [OfficeDev/office-js#3464]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: n/a
* Operating System: n/a
* Browser (if using Office on the web): any
 
## Expected behavior

Add-ins should show

## Current behavior

![image](https://github.com/OfficeDev/office-js/assets/137816589/eceb6db5-e25b-49b8-8828-2a143ac463a1)
no add-ins showing in ribbon

## Steps to reproduce

1. have any add-in
2. compose new event on OWA

## Link to live example(s)

1. ______
3. ______
4. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by williamkolega** [comment]
looks like its working now.  Was there an outage?  Many of our customers observed the same behavior

**Comment by williamkolega** [comment]
not working again for several customers

**Comment by LSDerekTardiff** [comment]
Ill add that they also seem to be missing on the preview Outlook client for windows.

**Comment by exextoc** [comment]
Thanks for reporting this issue. We can repro the issue and are working on the fix. We unfortunately have no timelines to share at this point. 

As workaround you can try this on OWA-

- If you are creating new event from Calendar surface- OWA calendar > Refresh > Addin should start showing up.
- If you are creating new event from Mail surface-  Go to OWA Calendar > Refresh > Move back to OWA Mail and then create new event > Addin should show up now

**Comment by exextoc** [comment]
@williamkolega We have fixed this issue. Please confirm if it is working for you or not.
