### ISSUE TITLE
accountType attribute reporting "enterprise" for Office 365 account

### ISSUE THREAD

**Issue by tobiasviehweger** [OfficeDev/office-js#3465]
# Provide required information needed to triage your issue
We have a customer on Office 365, that has a user profile accountType value of "enterprise" (which indicates that the mailbox is located onpremise - which is not the case). Unfortunately we use this attribute to determine if Office 365 only features should be available and this is therefore not working correctly.

It might be possible that the customer was onPrem at some point, but migrated to Office 365 - is it possible this is a missing migration step to tell the mailboxes they are now Office 365? Any information what exactly determines the value of this attribute?

See also #2634

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.16501.20196
* Operating System: Windows 10
* Browser: Edge WebView2 114.0.1823.43
 
## Expected behavior
accountType says "office365"

## Current behavior
accountType says "enterprise"

## Steps to reproduce
Not reproducible on our side

**Comment by Adrian-MSFT** [comment]
Hi @tobiasviehweger,

Can you have the user do `ctrl+shift+right click > Connection Status...` on the outlook icon in the system tray? This should bring up a dialog with a table. The table should have a "Server name" column. Can you confirm if the value from this column has an outlook office365 url (https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide)?

Please do NOT share a screenshot of that dialog or send any mailbox IDs here.

**Comment by tobiasviehweger** [comment]
Will do that, thanks!

**Comment by tobiasviehweger** [comment]
Hi @Adrian-MSFT - All the values have an Office 365 endpoint. Redacted/cropped screenshot:
![image](https://github.com/OfficeDev/office-js/assets/2111803/a44f54c2-c649-4974-a62a-7be2dd317df3)

**Comment by Adrian-MSFT** [comment]
Hi @tobiasviehweger ,

1. Do you have any other users that have migrated to office365 that are also impacted, or is this only a single user experiencing this issue? If multiple users, how many users are impacted by this?
2. Can you have the user create a new Outlook profile `File > Account Settings > Manage Profiles > Show Profiles > Add` with their same email address and check the accountType value again from the new profile plase?

**Comment by tobiasviehweger** [comment]
@Adrian-MSFT
1. It seems that all users from this customer org are affected. For this customer that wouldn't be more than a 10-20 users.
2. From first tests this seems to fix the issue, though it's still a somewhat unfortunate and complicated workaround for non-technical users..

**Comment by Adrian-MSFT** [comment]
Hi @tobiasviehweger ,

Thanks for answering my questions. After careful consideration, our team has decided to not fix this issue in the short term. We recommend you to upvote or create a new [Tech Community](http://aka.ms/M365dev-suggestions) item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue we will re-activate as needed.
