### ISSUE TITLE
Unable to side load office add in in Mac

### ISSUE THREAD

**Issue by PreethiVuchuru27916** [OfficeDev/office-js#3467]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.74.1
* Operating System: Mac OS Ventura 13.2
* Browser (if using Office on the web): Desktop
 
## Expected behavior
Add-in should be side loaded

## Current behavior
Add-in is not automatically sideloaded

## Steps to reproduce

1. npm install -g yo generator-office
2. yo office
3. npm run start:desktop:outlook

Get error like

Debugging is being started...
App type: desktop
Starting the dev server... (webpack serve --mode development)
The dev server is running on port 3000. Process id: 97373
Sideloading the Office Add-in...
Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in. 
Error: Sideload to the Outlook app is not supported.

<img width="1039" alt="image" src="https://github.com/OfficeDev/office-js/assets/46867529/b4628a1e-c1f5-4a6b-878c-1243896a51f5">

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

Internal tracking id: Eg: Office: 8086201

**Comment by exextoc** [comment]
@PreethiVuchuru27916 This functionality is currently supported only on Outlook Windows. The error you are seeing on Mac is by design.

**Comment by veris-kamaraj** [comment]
@PreethiVuchuru27916 did you find any solution

**Comment by gangstabob** [comment]
@PreethiVuchuru27916 
Dear Preethi,
Do you have any updates?

**Comment by ihales** [comment]
If it's helpful (and for future readers), I was able to sideload an extension into Outlook on Mac by following [these](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=mac#tabpanel_1_mac) instructions.
