### ISSUE TITLE
excel online addin  |  Tooltip <Supertip> not work on Excel online

### ISSUE THREAD

**Issue by AngelaTangChouGit** [OfficeDev/office-js#3468]
excel online addin  |  Tooltip <Supertip> not work on Excel online
followed https://learn.microsoft.com/en-us/javascript/api/manifest/supertip?view=powerpoint-js-preview, https://learn.microsoft.com/en-us/javascript/api/manifest/control-button?view=common-js-preview to set tooltip, and found it is not working on Excel online

## Your Environment

Excel online
 
## Expected behavior

Excel client works well -- we can see the tooltip when hover on the button
![image](https://github.com/OfficeDev/office-js/assets/138115027/4825e355-5af9-4ddc-bf61-36be9b980f3e)
No tooltip on Excel online
![image](https://github.com/OfficeDev/office-js/assets/138115027/99daed72-1549-419b-8002-eb69b1266169)

using the sample code in https://learn.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-code-samples, can reproduce the issue.

## Current behavior

excel online addin  |  Tooltip <Supertip> not work on Excel online

## Steps to reproduce

followed https://learn.microsoft.com/en-us/javascript/api/manifest/supertip?view=powerpoint-js-preview, https://learn.microsoft.com/en-us/javascript/api/manifest/control-button?view=common-js-preview to set tooltip

## Link to live example(s)

using the sample code in https://learn.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-code-samples, can reproduce the issue.

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by yuc014** [comment]
Hi @AngelaTangChouGit ,
I can repro your issue, I created an internal work item #8075545 to track it.

**Comment by AngelaTangChouGit** [comment]
Thank you Yunfan！

Best Regards,

Angela Tang
Support Escalation Engineer
APGC Office & PRC SP Support Team
Phone: +86 (21) 5263 7604 Email: ***@***.******@***.***>
Working Hours: 9:00AM-6:00PM Mon-Fri, UTC+8:00
Need help outside of my working hours? Please call the Premier hotline number<https://support.microsoft.com/en-us/help/4051701/global-customer-service-phone-numbers> with the case ID provided.

[Image result for microsoft logo]

If you have any feedback about my work, please let either me or my manager Amanda Luo know at ***@***.******@***.***>
Did you know? You can submit your O365 service and support feedback from the admin portal<http://aka.ms/o365satisfaction> by viewing support service requests.

**Comment by 4tti** [comment]
Is there any update to this issue?

**Comment by XuanZhouMSFT** [comment]
Thanks for waiting. The supertip feature is only supported in Office desktop clients and not supported in online environment. For more information, please refer to https://learn.microsoft.com/en-us/javascript/api/manifest/supertip?view=common-js-preview.
We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process.
