### ISSUE TITLE
OWA: Office.context.mailbox.addHandlerAsync is giving status as failed for when add-in is reloaded

### ISSUE THREAD

**Issue by anilreddyr7** [OfficeDev/office-js#347]
Office.context.mailbox.addHandlerAsync is giving status as failed.

When add-in is loaded initially, i'm able to see addhandlerasync is working fine. Event is registered properly and selection change event is getting fired. If I try to remove handle using removehandlerAsync and add again with addHandlerAsync, it should work as it does for initial one.

When I try to remove existing handler in one scenario and trying to attach again with addhandlerasync, then it is failing with failure status.

Error is attached.

![addhandlerasync](https://user-images.githubusercontent.com/25030206/50534157-cc10df80-0b5e-11e9-8788-8a72a8e1b5f5.JPG)

**Comment by exextoc** [comment]
Can you please share the sample code for the same? Also are you trying this for thick client or Outlook web client?

**Comment by anilreddyr7** [comment]
> Can you please share the sample code for the same? Also are you trying this for thick client or Outlook web client?

I'm facing issue on Outlook Web Client. It is working fine on thick client.

Office.initialize = function (reason) {
  $(document).ready(function () {
    Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, loadNewItem, function (result) {
 **//Here I'm getting above error**
      if (result.status === Office.AsyncResultStatus.Failed) {
        // Handle error
      }
    });
  });
};

function loadNewItem(eventArgs) {
  // custom code
  
};

**Comment by exextoc** [comment]
I tried this sample code and it works for me
Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, loadNewItem, function (result) {
 if (result.status === Office.AsyncResultStatus.Failed) {
  console.log("event error");
 }
 else
  {
    console.log("event registered");
  }
});

function loadNewItem(eventArgs) {
	console.log("event changed");
	};
Can you try the same and see if it works for you?
Also which are platform and browser are you facing this?

**Comment by anilreddyr7** [comment]
> I tried this sample code and it works for me
> Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, loadNewItem, function (result) {
> if (result.status === Office.AsyncResultStatus.Failed) {
> console.log("event error");
> }
> else
> {
> console.log("event registered");
> }
> });
> 
> function loadNewItem(eventArgs) {
> console.log("event changed");
> };
> Can you try the same and see if it works for you?
> Also which are platform and browser are you facing this?

Can you do this attach addHandlerAsync  event handler on Dom ready and reload the same frame again using right click.  You can see this error. Window reload is causing this issue.

**Comment by exextoc** [comment]
Calling addHandlerAsync before and after reload currently doesn't work in Outlook Web Access. It is unknown when this would be fixed. Right now the recommended work around is to not call "window.location.reload" or similar commands. It would also help to understand your scenario and why window.reload is necessary.

**Comment by anilreddyr7** [comment]
@kbrandl As we know this is product BUG on outlook web access. Can we get any update on this issue when it will be fixed?

**Comment by anilreddyr7** [comment]
> Calling addHandlerAsync before and after reload currently doesn't work in Outlook Web Access. It is unknown when this would be fixed. Right now the recommended work around is to not call "window.location.reload" or similar commands. It would also help to understand your scenario and why window.reload is necessary.

window.reload is necessary as we deal with multi document model to load multiple objects on screen.

**Comment by kbrandl** [comment]
@anilreddyr7 apologies for the delay on this. Given that this is beyond my area of expertise, I don't personally have insight into timelines for addressing this issue -- @exextoc will need to provide that feedback.

@exextoc can you please provide an update as to the status of this issue (and timeline for fixing, if known)?

**Comment by JuaneloJuanelo** [comment]
issue is tracked internally with 971375

**Comment by anilreddyr7** [comment]
> issue is tracked internally with 971375

Thanks for the update. Do we have any timeline for this issue? @JuaneloJuanelo It is very helpful for us to know the time line for this fix. One of our customers were expecting this and it is priority for us.

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by anilreddyr7** [comment]
Thanks for the update. Can you let me know the process that we need to do to follow to make the item as priority for you? @exextoc

**Comment by anilreddyr7** [comment]
> Thanks for the update. Can you let me know the process that we need to do to follow to make the item as priority for you? @exextoc

Hi Guys, Can you respond to my last query?

**Comment by JefCurtis** [comment]
@exextoc We are also experiencing this same problem. Has there been any progress on a fix for this? Is there anything I can do to help prioritize this issue? 

@anilreddyr7 Did you manage to find a workaround for this? We are on a tight timeline and this bug threw a wrench in the works over here.

**Comment by anilreddyr7** [comment]
> @exextoc We are also experiencing this same problem. Has there been any progress on a fix for this? Is there anything I can do to help prioritize this issue?
> 
> @anilreddyr7 Did you manage to find a workaround for this? We are on a tight timeline and this bug threw a wrench in the works over here.

We are not doing any work around. One thing is that we should try to avoid window.reload in your application scripts.

**Comment by exextoc** [comment]
Thanks for writing to us. Unfortunately we don't have an ETA for fix as of now. We will pick this item as soon as we can.

**Comment by exextoc** [comment]
Thanks for your patience. A fix for this issue has been deployed.
