### ISSUE TITLE
Event Office.EventType.ItemChanged not firing always

### ISSUE THREAD

**Issue by hmuris** [OfficeDev/office-js#3470]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I'm developing a Taskpane Addin and among other things I need to react when selected item in Outlook is changed. I achieved this using this code:
`Office.context.mailbox.addHandlerAsync(
  Office.EventType.ItemChanged,
  this.itemChangeHandler.bind(this)
);`

This is working except when in the inbox is meeting. When the item is a response to meeting, event gets fired (itemClass is then IPM.Schedule.Meeting.Resp... or IPM.Schedule.Meeting.Canceled) and I can react accordingly. (red does not work, green does)
![image](https://github.com/OfficeDev/office-js/assets/5045824/7518508e-52fa-4ec9-a338-0e17b8d8e607)

This event is also not fired when the email is encrypted.
![image](https://github.com/OfficeDev/office-js/assets/5045824/47ea26e1-35c6-44ed-b7d7-e6cbb89b7705)

In order to reproduce this issue, Taskpane needs to be activated on regular email, then pinned, and then switch to invalid item.

I tried to react later by checking Office.context.mailbox.item, but when one of these invalid items get clicked, it does not get changed. So, Office.context.mailbox.item has the value of the last valid item. 
This means that the user is executing Addin actions on not active item.

**Comment by hmuris** [comment]
Just to remind you that I'm waiting

**Comment by hmuris** [comment]
I wonder, what does this Needs: attention mean? Is it something that you are working on and will be part of some future release, or it needs to be more investigated?

**Comment by zhngx1** [comment]
Is this on Outlook web, windows or mac? If on windows or mac, can you provide the version number of your client?

**Comment by zhngx1** [comment]
Needs: attention is to track that we haven't responded to the post yet.

**Comment by hmuris** [comment]
This is Outlook web. 
Add-in is opened on normal e-mail, then pinned, and then one of not supported items is clicked.

**Comment by exextoc** [comment]
Currently itemChangedEvent for meeting invites is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](![image](https://github.com/OfficeDev/office-js/assets/28549921/93302be8-b0ed-42c8-a1ee-bb56afc0a64a)). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

Also since Add-ins are not supported for encrypted emails, itemChangedEvent also won't work.

**Comment by hmuris** [comment]
I understand that it is not supported, I also don't need it supported, that is not my request. 
The problem is that taskpane add-in can be pinned, and when such item is clicked, add-in doesn't get any idea about the change, meaning it has old context, meaning user actions are executed on wrong context.
This bug can be solved in few different ways, one of them being, even if the add-in is pinned, when item that is not supported is clicked, add-in is closed.
Other solution could be to let developers react to this event...

**Comment by exextoc** [comment]
Thank you for the clarification.Thanks for reporting this issue regarding itemChangedEvent. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: [1377899]
