### ISSUE TITLE
Outlook browser and one-outlook login prompt does not support darkmode 

### ISSUE THREAD

**Issue by AmitaiBitonHarmonie** [OfficeDev/office-js#3472]
Hi, My company develop a new product for Outlook Add-in (Outlook desktop, one-outlook, outlook browser). 
Our app supports Dark mode but in the browser or one-outlook,
There is some prompt that you gays displaying as part of the login process and this dialog does not support dark mode, see the image below!

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/109221185/a526c8c5-01a7-48c8-9776-b23e7400e287)

Right now we not support dark mode in one outlook because of this issue.

**Comment by Rick-Kirkham** [comment]
@AmitaiBitonHarmonie We use the issues in this repo to track problems with the documentation. I am transferring this issue to a more appropriate repo.

**Comment by exextoc** [comment]
@AmitaiBitonHarmonie Thanks for reporting this. Can you please be more specific on the repro steps? Additionally, could you specify the platform or device on which you are experiencing this problem?

**Comment by AmitaiBitonHarmonie** [comment]
We are developing outlook adding using React and ts also we use MUI to apply the theme, The bug is that you are page does not detect that im in Dark

**Comment by exextoc** [comment]
@AmitaiBitonHarmonie  Outlook add-ins do not support dark mode currently. If you need this feature, kindly file a feature request, at https://aka.ms/M365dev-suggestions .
