### ISSUE TITLE
Excel in the web version does not reassign the Command key to Ctrl

### ISSUE THREAD

**Issue by irynakaban** [OfficeDev/office-js#3473]
The documentation for custom shortcuts (https://learn.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts) says that:

- For Macs, we also support the Command modifier key.
- For Macs, Alt is mapped to the Option key. For Windows, Command is mapped to the Ctrl key.

However, if you specify a combination in the shortcuts.json file that uses the Command key, when using Office on the web and having a Windows operating system, this key is not replaced by Ctrl.

However, if you use the Option key, it is replaced by Alt.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.16625.42305
* Operating System: PC
* Browser (if using Office on the web): Google Chrome
 
## Expected behavior

When you use a combination that contains the Command key, it is replaced in Office on the web with the corresponding Windows key Ctrl.

## Current behavior

When you use a combination that contains the Command key, it is not replaced in Office on the web by the Windows key Ctrl.

## Steps to reproduce

1. Use an example from the documentation (https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/excel-keyboard-shortcuts).
2. Replace the keyboard shortcut for the OPENTASKPANE action with Command+Shift+F in file _src/shortcuts.json_.
3. After launching the add-in in the browser, the console will display a list of shortcuts used. There you can see that the Command key has not changed to Ctrl. And the keyboard shortcut doesn't work.

# Provide additional details
If you add a combination in the same example that uses the Option key, it will be replaced with Alt when using Windows.
If you add a combination in the same example that uses the Alt key, it will be replaced with Option when using Mac OS.

## Context

We need to create shortcuts for Excel on the Web when the user uses the Command key on Mac OS and the Ctrl key on Windows.

**Comment by ZYUN-MSFT** [comment]
Hi @irynakaban thanks for reaching us.

We are still investigating this issue with internal teams.\
We will keep tracking this issue and let you know if there are any updates.

**Comment by irynakaban** [comment]
Hi @ZYUN-MSFT are there any updates?

**Comment by ZYUN-MSFT** [comment]
Hi @irynakaban ,

Thanks for your patience.

Our engineering team is still investgating this issue and [#3494](https://github.com/OfficeDev/office-js/issues/3494).\
I will contact more frequently with them and update here once we have a conclusion.

Thanks again for your support.

**Comment by ZYUN-MSFT** [comment]
Hi @irynakaban ,

We find that this is an issue, and I will update the internal tracking BUG ID here later. (But we don't have an ETA yet)

Thanks.

**Comment by ZYUN-MSFT** [comment]
> Hi @irynakaban ,
> 
> We find that this is an issue, and I will update the internal tracking BUG ID here later. (But we don't have an ETA yet)
> 
> Thanks.

Internal BUG 8159127 is created for tracking this issue.

Once we got update we will back to this thread.

Thanks.

**Comment by irynakaban** [comment]
Thank you very much! I'll be waiting for updates.

**Comment by ZYUN-MSFT** [comment]
Fix is done and wait for deploy.

**Comment by leybal** [comment]
Hi @ZYUN-MSFT
We're really looking forward to the deploy. But it doesn't seem to have been done yet. Can you text us a date for the deployment, or an approximate timeline?

**Comment by ZYUN-MSFT** [comment]
Hi @leybal ,

I will check the deploy progress and update here tomorrow.

Thanks for your patience.

**Comment by ZYUN-MSFT** [comment]
Hi @leybal ,

The deploy have been deployed partically to production. It will reach production 100% in these days.

Thanks.

**Comment by ZYUN-MSFT** [comment]
Hi @leybal ,

The fix has been deployed to production 100 today, please check it when you have time.

Thanks.

**Comment by leybal** [comment]
@ZYUN-MSFT It works. Thanks.
