### ISSUE TITLE
How to deploy web add-in in diff diff regions on Microsoft Store

### ISSUE THREAD

**Issue by Rajnish-Asite** [OfficeDev/office-js#3474]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows, OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2305 Build 16.0.16501.20074) 64-bit
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

Web add-in need to deploy on Microsoft Store in diff-diff regions.

## Current behavior

We have our application deployed on so many clouds like UK, UAE, US So We need to deploy our web add-in in many regions.
But we do not found anything like regions wise deployment of web add-in on Microsoft Store. 
Right now if we deploy our web add-in and if we will change anything then it will shown in every regions.

We need to differentiate our web add-in region wise So that if we don't want to release web add-in in UAE and only need to release our web add-in in UK then Right now we do not have this option.

Please do needful asap.

**Comment by exextoc** [comment]
@Rajnish-Asite Unfortunately we don't support the deployment of add-ins location-wise. However if possible you can create groups of users (location-wise) and then assign add-ins to those groups.

Refer to the doc: https://learn.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide .

If you need the location-wise deployment and wish to file a feature request, please use the below link: https://aka.ms/M365dev-suggestions
