### ISSUE TITLE
How to create table in Power point using   JavaScript API for PowerPoint (office js).

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#3475]
Hello Team,
I am using Powerpoint API for developing  add-in. I have  data in Array and JSON format. I want to create table using that data and after that I want to read that data from table so that I can change later.
I couldn't find any events for creating table in Power point using JavaScript API for PowerPoint.
 
My Environment
Platform : PC desktop
Host: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2304 Build 16.0.16327.20200) 64-bit
Operating System: Windows 10 pro

**Comment by xuruiyao-msft** [comment]
@Jayshiv1408Dev Currently the feature: insert/modify table into powerpoint, you requested, is not a part of the product. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum]( https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. Thanks, Microsoft 365 Developer Platform team

**Comment by shermaro91** [comment]
Hi, Is there any update on this ? I guess lots of developers has raise this concern that they want table api in powerpoint.
