### ISSUE TITLE
Unable to load cell "shadingColor" of if created by Word application in Word Online

### ISSUE THREAD

**Issue by docu-bill** [OfficeDev/office-js#3479]
If a table with no background color is created using the Word desktop application, if an add-in on Word Online trys to load the shadingColor of a cell the addin throws an error: 

"code":"GeneralException","message":"Cannot read properties of null (reading 'toUpperCase')"

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC ( desktop to web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Microsoft 365
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome and Edge
 
## Expected behavior

The addin should behave the same or be able to try and catch the error before sync so that the shadingColor could be set to white or something that does not cause the crash

## Current behavior

I get an error I cannot work around

## Steps to reproduce
To reproduce:
* Create a new document and add a table using word desktop  application
* Check that the table cells have "No Color" for their cell shading
* try to load and sync "shadingColor" of a TableCell

## Link to live example(s)

1. [Script Lab Example](https://gist.github.com/docu-bill/cd24a148a8e23a8c7e84e7cce734a53a)

# Provide additional details

1. ______
2. ______
3. ______

## Context

We are trying to create an addin the our customers can use with their existing documents seamlessly

If there is a work around that 

## Useful logs

- [ ] Console errors: 

Error getting shadingColor {"code":"GeneralException","message":"Cannot read properties of null (reading 'toUpperCase')","errorLocation":"TableCell.shadingColor","statement":"v.load([\"shadingColor\"]);","surroundingStatements":["var v = context.root._getObjectByReferenceId(\"{dc9b2ed6-3155-4cd7-8180-6a9c7a8acbb3}{60}\");","// >>>>>","v.load([\"shadingColor\"]);","// <<<<<"],"fullStatements":["Please enable config.extendedErrorLogging to see full statements."]}

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by YijunMS** [comment]
Thanks for reporting this issue.

It has been put on our backlog<Bug#8081010> for internal track. We will keep track of this issue and let you know if there are any updates.

**Comment by docu-bill** [comment]
Is there an ETA on this bug fix?  Will it be back ported to API version 1.3?

**Comment by YijunMS** [comment]
We are managing our resources and scheduling the fixing of this issue but there hasn't been a specific time for now. We will notify you in this thread once the fixing is on its way. Sorry for the inconvenience.

BTW, the fixing should take effect on all versions containing this API. Please let me know if I didn't understand your last question correctly.

**Comment by docu-bill** [comment]
Is there any way you can give me an idea.  Is it 1 week 1 month 1 year 5 years maybe never.  This causes a really annoying bug and I need to know if I need to choose another technology.

**Comment by YijunMS** [comment]
The fixing is under deployment process now. If no further issue is found, it should be able to reach all customers in about a week or two.

**Comment by docu-bill** [comment]
Thank you

**Comment by YijunMS** [comment]
@docu-bill Thanks for your patience. The fixing should be available now.
