### ISSUE TITLE
Custom functions add-in environment has CORS request failure

### ISSUE THREAD

**Issue by evantrimboli** [OfficeDev/office-js#348]
I'm trying to execute a CORS `XmlHttpRequest`, however the request fails when running in the custom function environment. I'm able to run the request successfully in Chrome and IE11 if I run it directly in the browser. For example, I navigate to
`https://localhost:3000/functions.html` and then open the console and call `CustomFunctionMappings.MyFn(params).then(function(r) { console.log(r); });` This provides the correct result in browser, so it leads me to believe it's not a server issue.

## Expected Behavior
The request should hit the server and return the data.

## Current Behavior
An error is thrown:
"The request does not meet conditions for security policy of SOP (same-origin policy) or simple CORS (cross-origin resource sharing)."

## Steps to Reproduce, or Live Example
I can't provide a live test case, however here is what the request looks like:
```
const xhr = new XMLHttpRequest();
xhr.open('GET', `https://localhost:44399/path/to/the/thing`, true);
xhr.setRequestHeader('Access-Control-Allow-Origin', '*');
xhr.setRequestHeader('Authorization', 'Basic ' + base64.encode(userName + ':' + password));
xhr.onreadystatechange = () => {
  if (xhr.readyState === 4) {
    const text = xhr.responseText;
    let json = '';
    try {
      json = JSON.parse(text);
      resolve(json);
    } catch (e) {
      resolve(['BAD' + xhr.responseText]);
    }
  }
};
xhr.send();
```

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel Custom Functions
* Office version number: Version 1901, Build 11220.20008 (Insider Program)
* Operating System: Windows 10

## Useful logs
N/A

**Comment by keyur32** [comment]
Hi @evantrimboli,

Custom Functions currently only support simple CORS, so you may hitting that issue.

Can you try either of the following?

a) check the origin policy on your server?  I may be wrong, but I don't think you can set the policy as part of our http request (as it would by pass the security restriction).

b) We only support same origin (SOP), and simple methods/headers (Simple Cors) for cross origins. For cross origins, unfortunately "content-type": “application/json” doesn’t belong to simple headers according to definition, therefore blocked. A workaround is to pass “application/text” for json if one knows the destination is safe

**Comment by evantrimboli** [comment]
a) You're right, I didn't need to set the header on the client. As I said in my OP, I can make a CORS request to the server from other browser environments, so it's not a server issue.
b) The problem appears to be the authorization header, if I remove that it actually hits the server end point.

Is supporting anything like this on your roadmap? It makes it difficult to make CORS requests with such a limited amount of options.

**Comment by keyur32** [comment]
Hey @evantrimboli, sorry, super delayed. Yes, we have this in our roadmap to address! Stay tuned to our channels, we'll likely talk about this on our community call during the next few months: https://aka.ms/officeaddinscommunitycall.

thanks!

**Comment by keyur32** [comment]
Marking this issue as closed for now. thanks.

**Comment by benj-spectory** [comment]
Hi, 
i'm having the same issue...
@evantrimboli did you manage to make it work?

**Comment by evantrimboli** [comment]
No, I didn't really pursue this much. I know that the environment has moved on to something Edge based now, so perhaps in newer versions it has been resolved.

**Comment by benj-spectory** [comment]
@evantrimboli as far as i tried, it does not work...
@keyur32 do you have any idea\workaround that might work?
