### ISSUE TITLE
OWA Outlook add-ion task panes have no access to clipboard API

### ISSUE THREAD

**Issue by barclayadam** [OfficeDev/office-js#3480]
# Provide required information needed to triage your issue

## Your Environment

* Platform: OWA
* Host: Outlook
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome
 
## Expected behavior

`await navigator.clipboard.writeText('My Text');` should copy to the clipboard. This works OK in the native Windows Outlook client, so parity between platforms seems sensible.

## Current behavior
An error:

`Uncaught (in promise) DOMException: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.`

## Steps to reproduce
1. From an add-in's task pane react to a button press with the above code snippet

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@barclayadam Thanks for reaching out. Clipboard API is not supported in OWA

If you need this API support and wish to file a feature request, please use the below link: https://aka.ms/M365dev-suggestions

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.

**Comment by tobiasbueschel** [comment]
This would also be great to have for PowerPoint and other Office application running in the web version!
