### ISSUE TITLE
[Word Add-in] How to automatically append text on Word Document open?

### ISSUE THREAD

**Issue by VelinGeorgiev** [OfficeDev/office-js#3481]
### Description

I followed this article saying it is possible to [Run code in your Office Add-in when the document opens](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/run-code-on-document-open), but I am unable to append text in the document body when user initially opens the document. I am only able to append text in the document body after add-in interaction from the user, so (the next time the document opens, the document ready logic kicks in).

Additionally, I configured the adding to use [Shared runtime](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/common/shared-runtime-requirement-sets?view=powerpoint-js-preview) as the above article suggests.

### Steps to Reproduce, or Live Example:

You can have a look and run the following sample:
- [https://github.com/VelinGeorgiev/office-addin-onready](https://github.com/VelinGeorgiev/office-addin-onready)
- I configured the Office.onReady as well as the .setStartupBehavior(Office.StartupBehavior.load) per the official documents.
 ````
Office.onReady(() => {
  Office.addin.setStartupBehavior(Office.StartupBehavior.load);
...
 ````
- [https://github.com/VelinGeorgiev/office-addin-onready/blob/main/src/taskpane/index.js](https://github.com/VelinGeorgiev/office-addin-onready/blob/main/src/taskpane/index.js)
- I have configured the manifest to use Shared Runtime as per the documents above to satisfy the official documents requirement:
- [https://github.com/VelinGeorgiev/office-addin-onready/blob/main/manifest.xml](https://github.com/VelinGeorgiev/office-addin-onready/blob/main/manifest.xml)

### Expected: 
When a user initially opens a document, the add-in code runs automatically and updates the document body with new text.

### Actual:
When a user initially opens a document, nothing happens. No code from the add-in is executed. `Office.onReady` nor `Office.initialize` is triggered on the initial document open. The user has to manually click the add-in ribbon controls to enable the code to run the next time the document is opened. 

### Additional
- I am loading the `Office.addin.setStartupBehavior(Office.StartupBehavior.load);` on the wrong place?
- Is there a different approach to allow a fully automated behaviour on document open with the Office JavaScript add-in framework without the need for the user to interact with the add-in initially?
- Is there a manifest definition node that can set up the behaviour in advance ahead of the add-in `Office.onReady` lifecycle event trigger?

### Your Environment
Microsoft Word Online

**Comment by ZYUN-MSFT** [comment]
Hi @VelinGeorgiev , thanks for reaching us.

Currently, automatically start up add-in with new Word Document created is not supported.\
The doc [Run code in your Office Add-in when the document opens](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/run-code-on-document-open) is sepecific for add-in autorun within the same Word document re-open.

We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). You can request this new feature there. Feature requests on are considered when we go through our planning process.

Thanks.

**Comment by VelinGeorgiev** [comment]
Why @ZYUN-MSFT, then, is the official document title is

> Run code in your Office Add-in when the document opens

rather than 

> Run code in your Office Add-in when the document **RE-OPENS** :)

Furthermore, there isn't a single note within the documents about this specific behaviour.  

This is misleading and discouraging and causes architects like me to plan the wrong paths for the clients, then have to explain the documents are written in a "marketing" fashion, but actually, this is not how it works.

Anyways, thanks for your quick response.

**Comment by ZYUN-MSFT** [comment]
Hi @VelinGeorgiev , we are sorry for the confusing and unpleasant caused by our document.\
We will continue work with doc team to optimize and improve the quality of our official documents.

Finally, thank you again for your support of Office Addin.
