### ISSUE TITLE
Get attachment content id

### ISSUE THREAD

**Issue by hmuris** [OfficeDev/office-js#3482]
As described in the issue [here](https://github.com/OfficeDev/office-js/issues/1823), I also need to get attachment CID. I have an email with inline attachments, and all the information are there, including attachment (data, mime type...) but there is no link between body and the inline attachment. Is there any way, without using Graph of EWS, to get this information using office.js?

**Comment by hmuris** [comment]
Shouldn't at least triage find place for this question? I read that within 72 hours it should.

**Comment by AkhileshShah-MS** [comment]
Thanks for reaching out @hmuris! 
I have triaged this issue to @exextoc to help further. Could you please look into this issue? 
Thanks!

**Comment by hmuris** [comment]
Hello, is there any plan for this topic, any reaction?

**Comment by sebammon** [comment]
@AkhileshShah-MS Is there any update on this issue? I am currently facing a similar issue. Our requirement is to match the inline attachments that we get from the `attachments` property on the item, with the attachments' cids in the HTML body of the email.

Is there any way to do this?

**Comment by exextoc** [comment]
Currently the feature to get attachment cid, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

Github Label: “Type: product feature request”
https://aka.ms/M365dev-suggestions
	

[Outlook Add-ins Engineering Team]

**Comment by hmuris** [comment]
@sebammon there is way. What I tested and it is working is to use Microsoft Graph and call `'/me/messages/' + id + '/attachments'`. This returns attachments including the content id. 
Other way, what I did not yet try is to use `Office.context.mailbox.makeEwsRequestAsync(...)` and request attachments this way.

**Comment by exextoc** [comment]
@hmuris Glad that you found a solution of the problem using Graph API. Closing the issue.
