### ISSUE TITLE
Add-in without internet connection

### ISSUE THREAD

**Issue by ip-space** [OfficeDev/office-js#3487]
## Your Environment
- About add-in: Shared add-in , webview2
- Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Office version number: Office 21( 2305 Build 16.0.16501.20074 ) and Office 365 (2305 Build 16.0.16501.20074)
- Operating System: Windows 10
- Browser (if using Office on the web): n/a

## Current behavior
Our add-in uses CDN to get office api.  By the address  https://appsforoffice.microsoft.com/lib/1/hosted/office.js.
Receiving api works correctly if pc has an internet connection, i.e. files are downloaded and cached. After that pc disconnected from internet and add-in works correctly few days. But after few days add-in stop working because there is no api files any more (see  additional details ).

Сache is not cleared manually or automatically.

## Expected behavior
Add-in works if office api is loaded once.  The add-in does not attempt to download a new version of the API if there is no connection.

Are there any recommended code in this case? Or it should be  non-CDN?

## Steps to reproduce
To emulate behavior:
1. Turn off internet connection
2. Clear cache
3.  Insert shared add-in
4.  Result: Task pane is never opened and it is never connected to localhost

# Provide additional details
Add-in raise such exceptions:
![image](https://github.com/OfficeDev/office-js/assets/11005459/875e0718-7387-4008-819c-98676b4bfbc9)

**Comment by ZYUN-MSFT** [comment]
Hi @ip-space , thanks for reaching us.

The Office Add-in is supposed to be used under internet connected enviroment. The internet disconnected enviroment is not supported for Office Add-in, which is also not the situation we aim to support.

Thanks.

**Comment by ip-space** [comment]
Hi @ZYUN-MSFT, thank you for information. Issue is closed
