### ISSUE TITLE
makeEwsRequestAsync for sending a message has a size limit of 1 MB

### ISSUE THREAD

**Issue by jorgk3** [OfficeDev/office-js#3490]
- Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web accessed from PC desktop
- Host [Excel, Word, PowerPoint, etc.]: Outlook
- Office version number: The one deployed at Office.com
- Operating System: Window 10
- Browser (if using Office on the web): Edge

This code fails when called with more than 1 MB of data:
```
function sendMimeMessageViaEWS(mBox, mimeText) {
  return new Promise((resolve) => {
    let requestXML =
      `<?xml version="1.0"?>
      <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
                  xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
                  xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
        <s:Header>
          <t:TimeZoneContext>
            <t:TimeZoneDefinition Id="UTC"/>
          </t:TimeZoneContext>
        </s:Header>
        <s:Body>
          <m:CreateItem MessageDisposition="SendAndSaveCopy">
            <m:Items>
              <t:Message>
                <t:MimeContent>${btoa(mimeText)}</t:MimeContent>
                <t:IsDeliveryReceiptRequested>false</t:IsDeliveryReceiptRequested>
              </t:Message>
            </m:Items>
          </m:CreateItem>
        </s:Body>
      </s:Envelope>`;
    mBox.makeEwsRequestAsync(requestXML, (result) => resolve(result));
  });
```

Here's a screenshot of the error message from the browser console:

![index](https://github.com/OfficeDev/office-js/assets/8466558/be7ac9f4-7ca7-45cc-a22d-6afd79b66bd8)

I'm filing this as a bug since an API with a 1 MB size limit to send an e-mail is not really usable. Please increase the size limit so some standard maximum size for e-mail, something around 50 MB perhaps.

BTW, we're using EWS since the OL JS API doesn't have an API to send messages.

**Comment by yjoshi-msft** [comment]
Hi jorgk3,

Thank you for reaching out. I understand your concern, however we use this channel to track potential bugs or errors in our documentation. As this is a feature request, I recommend you raise the request here - https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
