### ISSUE TITLE
makeEwsRequestAsync for retrieving MIME text of a message has a size limit of 4 MB

### ISSUE THREAD

**Issue by jorgk3** [OfficeDev/office-js#3491]
- Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web accessed from PC desktop
- Host [Excel, Word, PowerPoint, etc.]: Outlook
- Office version number: The one deployed at Office.com
- Operating System: Window 10
- Browser (if using Office on the web): Edge

This code fails when called with more than 4 MB of data:

```
function getMimeMessageViaEWS(mBox, mItem) {
  return new Promise((resolve) => {
    // Note that not specifying the RequestServerVersion will lead to an error:
    // The EWS Id is in EwsLegacyId format which is not supported by the Exchange version
    // specified by your request. Please use the ConvertId method to convert the Id from EwsId
    // to EwsLegacyId format.
    let requestXML =
      `<?xml version="1.0"?>
      <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
                  xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
                  xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
        <s:Header>
          <RequestServerVersion Version="Exchange2013" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" />
        </s:Header>
        <s:Body>
          <m:GetItem>
            <m:ItemShape>
              <t:BaseShape>IdOnly</t:BaseShape>
              <t:IncludeMimeContent>true</t:IncludeMimeContent>
            </m:ItemShape>
            <m:ItemIds>
              <t:ItemId Id="${mItem.itemId}" />
            </m:ItemIds>
          </m:GetItem>
        </s:Body>
      </s:Envelope>`;
    mBox.makeEwsRequestAsync(requestXML, (result) => resolve(result));
  });
}
```

This returns "failed" if the message to be retrieved is larger than about 4 MB.

I'm filing this as a bug since an API with a 4 MB size limit to retrieve an e-mail is not really usable. Please increase the size limit to some standard maximum size for e-mail, something around 50 MB perhaps.

BTW, we're using EWS since the OL JS API doesn't have an API to get the MIME text of a message.

**Comment by yjoshi-msft** [comment]
Hi jorgk3,

Thank you for reaching out. I understand your concern, however we use this channel to track potential bugs or errors in our documentation. As this is a feature request, I recommend you raise the request here - https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
