### ISSUE TITLE
 How to achieve user authentication and obtain access token in a Word add-in running in Microsoft Teams desktop app?

### ISSUE THREAD

**Issue by SAgnihotri200895** [OfficeDev/office-js#3495]
##  How to achieve user authentication and obtain access token in a Word add-in running in Microsoft Teams desktop app?

I'm currently working on a Word add-in that runs within the Microsoft Teams desktop app. Our goal is to implement single sign-on (SSO) by obtaining a user access token, which we can then use to call a secured Azure Function API. However, we're facing difficulties in acquiring the token when opening a document in the Teams desktop app and running our Word add-in.

We're aware that the getAccessToken function does not support this scenario. Therefore, we're looking for a workaround to achieve user authentication and obtain the necessary access token. Any guidance or suggestions would be greatly appreciated.

**Comment by yjoshi-msft** [comment]
Hi SAgnihotri200895,
Thank you for your query. We appreciate your input. However, GitHub issues are specifically for reporting potential bugs or errors in our documentation. For general discussions or feature requests, we recommend exploring Stackoverflow (https://stackoverflow.com/questions/tagged/microsoft-teams)
