### ISSUE TITLE
Issues with Office.bindings.addFromPromptAsync

### ISSUE THREAD

**Issue by SharonCKC** [OfficeDev/office-js#3497]
## Your Environment
* Platform: PC desktop, Office on the web
* Host: Excel

## Current behavior

On PC:
- Select a cell next to a table's row, then open prompt. Select another cell inside the table (must be in the same row). Observe that prompt is showing a cell address such as `Table1[@Column4]`. Click OK. Observe the error.
![image](https://github.com/OfficeDev/office-js/assets/113057307/9e6237a0-84a3-40e6-ab9a-76b4a7955f0f)

In browser:
- Prompt doesn't allow the user to select cells while prompt is open. Prompt textbox does not update with new cell selection. No dotted-line border appears when trying to select cells.  User must type the cell address to change the selection.
![image](https://github.com/OfficeDev/office-js/assets/113057307/9e73f0b1-4362-48c4-b322-dd2101a8376a)

## Steps to reproduce
Run the following:
```
Office.context.document.bindings.addFromPromptAsync(Office.BindingType.Matrix, { id: "myBinding" }, async (asyncResult) => {
        if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
          const binding = context.workbook.bindings.getItem("myBinding");
          const range = binding.getRange().load("address");
          await context.sync();
          console.log(range.address);
        }
});
```

## Context
We want to use `addFromPromptAsync()` because we need a cell range selection interface. For example, when creating a table or a pivot table in Excel, the dialog asks for an input cell range, and a dotted-line border is shown to indicate the user's "temporary" selection. We need a similar UI to ask for input range.

**Comment by ZYUN-MSFT** [comment]
Hi @SharonCKC , thanks for reporting this issue.

This issue has been put on our backlog, and an internal BUG#8101837 is created for tracking this.\
We will keep tracking this issue and let you konow if there are any updates.

Thanks.

**Comment by XuanZhouMSFT** [comment]
Thanks for reporting this issue. After careful consideration, our team has decided to not fix this issue in the short term. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.
