### ISSUE TITLE
Office.EventType.RecipientsChanged won't fire after changing messages in a pinned add-in

### ISSUE THREAD

**Issue by nbreath** [OfficeDev/office-js#3498]
I'm using the `office-js` to develop a Outlook `add-in`. The event `Office.EventType.RecipientsChanged` works fine when I'm in a draft the first time, but if I `pin` the `add-in` and change to another draft it stops firing. Occurs in the Outlook Mac desktop app, in `web` works normally, I haven't tested in a Windows desktop.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 16.70 (23021201)
* Operating System: MacOs Ventura
* Browser (if using Office on the web): n/a
 
## Expected behavior
The listener keeps working between compose/draft messages when the `add-in` is pinned.

## Current behavior
I added two listeners `Office.EventType.RecipientsChanged` and `Office.EventType.ItemChanged` to update the list of emails a users is using when composing a draft.
I open a draft and pin the `add-in` and both the `Office.EventType.ItemChanged` and `Office.EventType.RecipientsChanged` works fine but when I change to a second draft `Office.EventType.RecipientsChanged` stops working and will remain not firing unless I close the pinned add-in and open it again. `Office.EventType.ItemChanged` works fine always.

```js
const { item } = Office.context.mailbox;
item.addHandlerAsync(Office.EventType.RecipientsChanged, clearAndSetEmails);
Office.context.mailbox.addHandlerAsync(
    Office.EventType.ItemChanged,
    clearAndSetEmails
  );
````

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. https://github.com/OfficeDev/office-js/assets/5169917/0f492969-6c35-4e8d-bd81-9524a08fa7dd
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by zhngx1** [comment]
The behavior on Mac and Windows is as expected since the RecipientsChanged event is actually on the item and the ItemChanged event is on the mailbox level. When item has been switched, we expect the add-in to re-register the RecipientsChange to have it work. You can do so by register the event in the handler passed to the addHandlerAsync function for itemChanged event.

```
Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, () => {
  Office.context.mailbox.item.addHandlerAsync(Office.EventType.RecipientsChanged, (eventArgs) => {
     // your code
    }, asyncResult => {
      if (asyncResult.status === Office.AsyncResultStatus.Failed) {
        console.log(asyncResult.error.message);
        return;
      }
  
      console.log("Event handler added.");
    });
}, asyncResult => {
    if (asyncResult.status === Office.AsyncResultStatus.Failed) {
      console.log(asyncResult.error.message);
      return;
    }

    console.log("Event handler added.");
  });
```

**Comment by nbreath** [comment]
Thanks @zhngx1, I updated how the listeners works and now they're working fine.

**Comment by exextoc** [comment]
closing issue, since it has been answered.
