### ISSUE TITLE
 For IOS, Office.context.mailbox.item.itemId returns undefined for appointment read

### ISSUE THREAD

**Issue by YmaRivaEngine** [OfficeDev/office-js#3499]
We have a outlook addin for Outlook on the IOS, it works fine for emails, however, we found an Office interface is not available
Office.context.mailbox.item.itemId returns undefined for appointment read
it works good on android for same code, same manifest and same meetings, we can see the same interface returns the item id as expected. 
we have use Office.context.mailbox.item.getItemIdAsync as fallback, it returns undefined as well. 

* Platform:IOS
* Host: Outlook
* Office version number: 4.2324.0
* Operating System: IOS: 15.7.7 and above
* Browser (if using Office on the web): N/A
 
## Expected behavior
Office.context.mailbox.item.itemId should return id for appointment read
Office.context.mailbox.item.getItemIdAsync  should retrun id for appoinment compose
## Current behavior
Office.context.mailbox.item.itemId return undefined for appointment read in IOS meetings

## Steps to reproduce

1. side load a sample manifest that avaiable for mobile meetings like contoso.manifest.xml
2. have a script contains a function that returns id for appoinment using Office.context.mailbox.item.itemId ex, getItemId();
3. run getItemId();

## Link to live example(s)
N/A

# Provide additional details

sample code :
`  const itemId = Office.context.mailbox.item.itemId;
        if (itemId) {          
            callback(itemId);
           return;
        }
        if (Office.context.mailbox.item.getItemIdAsync) {
            Office.context.mailbox.item.getItemIdAsync((result) => {
                if (result.status === Office.AsyncResultStatus.Succeeded) {
                    callback(result.value);
                }
                else {
                    callback("");
                }
            });
        } 
        callback("");`

## Context
Our customers want to be able to log their Appointments to their CRM on mobile, however they are unable to use the function for IOS device 

## Useful logs

- [X] Console errors
- [X] Screenshots

![ItemId](https://github.com/OfficeDev/office-js/assets/139180033/2c311c11-c571-42ae-ba78-0a7e35cfda61)

Please let us know if there are any additional info needed, Thanks

**Comment by CurtisRiva** [comment]
@exextoc , any updates?

**Comment by ndeleuze** [comment]
@YmaRivaEngine do you know if this is also reproducible for Windows or Web Outlook?

**Comment by YmaRivaEngine** [comment]
@ndeleuze,  it works as expected for other platform, just not for Outlook App on IOS (no issue on Outlook App on Android too)

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding itemId on appointment read It has been put on our backlog. We unfortunately have no timelines to share at this point.
Internal tracking id: Office: 3763361

**Comment by exextoc** [comment]
We have fixed the bug and the fix should be available in build 4.2333.0 (22159717) or later.
