### ISSUE TITLE
PowerPoint Online access to slide show window

### ISSUE THREAD

**Issue by scemis** [OfficeDev/office-js#35]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

**Office.context.document.getActiveViewAsync** function always return 'edit' even when I run presentation slide show. Happens only in browser. (Desktop version works fine).

Presentation opens in new window for slide show:
(ex: https://powerpoint.officeapps.live.com/p/PowerPointFrame.aspx?PowerPointView=SlideShowView)

Is there way to connect and get context/events from that slide show window?

Thanks in advance.

**Comment by lindalu-MSFT** [comment]
@scemis Hi, and thanks for reporting this! I'm the PM who has been assigned to track down old issues and see if they still need to be assigned. Can you confirm that this still happens when you run presentation slide show? And also, if so, please report the repro steps. Thanks for your help!

**Comment by scemis** [comment]
Thanks for your final reply.
I just test my add-in with latest office.js
https://appsforoffice.microsoft.com/lib/1/hosted/office.js

And I found no changes regarding my problem.
So still no difference between modes (always **edit**)

Below you can find a code example:

Office.context.document.getActiveViewAsync(function (asyncResult) {
            console.log('ActiveView mode: ' + asyncResult.value);
 });

// result: ActiveView mode: edit

Please, let me know if you have any questions.

**Comment by scemis** [comment]
Thanks for your final reply.
I just test my add-in with latest office.js
https://appsforoffice.microsoft.com/lib/1/hosted/office.js

And I found no changes regarding my problem.
So still no difference between modes (always **edit**)

Below you can find a code example:

Office.context.document.getActiveViewAsync(function (asyncResult) {
            console.log('ActiveView mode: ' + asyncResult.value);
 });

// result: ActiveView mode: edit

Please, let me know if you have any questions.

**Comment by ElizabethSamuel-MSFT** [comment]
@JuaneloJuanelo Can you help get this directed appropriately? Thanks.

**Comment by scemis** [comment]
@JuaneloJuanelo Do we have any progress here? Please let me know if I can help anyhow. Thanks.

**Comment by gordonmleigh** [comment]
I have the same issue. The reproduction is simple; `getActiveViewAsync` always returns `edit` and the handler for `Office.EventType.ActiveViewChanged` doesn't fire when you start presenting.

**Comment by gordonmleigh** [comment]
@JuaneloJuanelo @ElizabethSamuel-MSFT @lindalu-MSFT is anyone looking at this?

**Comment by lindalu-MSFT** [comment]
@mscaitlina Can you help us assign this to the correct person?

**Comment by lindalu-MSFT** [comment]
Note: This is a browser issue. Works as expected in desktop. Is this is the backlog?

**Comment by donlvMSFT** [comment]
@scemis , thanks for reporting the issue. I did some quick repro but the API works well with my test content add-in (In below). 
So I would like to get more clear about your scenario during following questions.
1. Do you use Content Add-in or Taskpane Add-in?
2. If it's Content Add-in, could you share your add-in for us to repro?
3. If it's Taskpane Add-in, could you share with us the add-in and how you trigger the API during presenting mode?

Thanks for your information, that will be very helpful.


Here is the [add-in manifest file](https://github.com/donlvMSFT/officejs-goToById/blob/master/PowerPointWebAddIn1.xml) I use, inner `Find Mode` button the code is 
```javascript
Office.context.document.getActiveViewAsync(function (asyncResult) {
    console.log('ActiveView mode: ' + asyncResult.value);
});
```

**Comment by jipinshi** [comment]
@scemis , can you specify which kind of addin do you use here? Content addin or taskpane addin? Can you share the manifest you used? I tried with scriptlab which is a taskpane addin which cannot be executed when in slide show mode.

**Comment by scemis** [comment]
Do you need this?
<hostitem:hostItem hostitem:baseType="Microsoft.Office.Tools.AddInBase"
hostitem:namespace="TalkDeck.VSTO.PowerPointAddIn" hostitem:className=
"ThisAddIn" hostitem:identifier="ThisAddIn" hostitem:primaryCookie="AddIn"
hostitem:master="true" hostitem:factoryType="Microsoft.Office.Tools.Factory"
 hostitem:startupIndex="0" xmlns:hostitem="
http://schemas.microsoft.com/2004/VisualStudio/Tools/Applications/HostItem.xsd
">
  <hostitem:hostObject hostitem:name="Application" hostitem:identifier=
"Application" hostitem:type=
"Microsoft.Office.Interop.PowerPoint.Application" hostitem:cookie=
"Application" hostitem:modifier="Internal" />
  <hostitem:hostControl hostitem:name="CustomTaskPanes" hostitem:identifier=
"CustomTaskPanes" hostitem:type=
"Microsoft.Office.Tools.CustomTaskPaneCollection" hostitem:primaryCookie=
"CustomTaskPanes" hostitem:modifier="Internal" />
</hostitem:hostItem>

**Comment by lumine2008** [comment]
A bug (5021004) is created to track this issue.

**Comment by CaptainTammy** [comment]
@gingerjia @ElizabethSamuel-MSFT @lindalu-MSFT 
Is there any progress expected on this in the near future? We have the same problem for our TaskPane-App that we would need to know when we are in edit or read (edit or presenting) mode. We are also stuck for getting our app submitted as we can not proceed without the web version working. We have also posted an issue about this [#2756](https://github.com/OfficeDev/office-js/issues/2756)

Example: [here](https://github.com/OfficeDev/office-js/issues/2756#issuecomment-1250916322)

**Comment by ElizabethSamuel-MSFT** [comment]
@jipinshi Any update on this? Thanks.

**Comment by gingerjia** [comment]
Hi @ElizabethSamuel-MSFT seems @Jipyua addressed the issue in thread https://github.com/OfficeDev/office-js/issues/2756. Thanks!
