### ISSUE TITLE
Anchor tags not working in Outlook android.

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#350]
I'm trying to view/download a PDF/Docx file on click of anchor tag in Outlook web add-in (Android).

## Expected Behavior
It should be able to download or view a PDF/docx file. 

## Current Behavior
Click on the link from web add-in and this fails to load. I even tried with displayDialogAsync and this just loads a blank window.

This link works fine with iPad/iPhone/MAC/Windows but not in Android Outlook wed add-in.

In Android Outlook web add-in the txt file download works fine via link.

## Steps to Reproduce, or Live Example
I'm using Outlook Android application [V2.2.257(293)]

 Steps to reproduce : 
1. Any anchor tag with proper href. 

    Use the below and open it in your outlook add-in Android.

    <a href="http://iiswc.org/iiswc2012/sample.doc" target="_blank" rel="noopener noreferrer" data- 
     auth="NotApplicable"><span style="font-size: 8.5pt; font-family: Verdana, sans-serif, serif, EmojiFont; 
     color: rgb(25, 118, 210); background: white;">SampleDOC</span></a>

2. Click on the link from web add-in and this fails to load.

## Context

The same links works in other in iPhone,MAC,iPad & windows but not in Android. This is leading to inconsistent behavior. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Android . No issue found in other platforms
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 1.5
* Operating System: Android (5-9)
* Browser (if using Office Online): ______

Is there any other way to implement links other than using anchor tags ?

As per this <a href="https://stackoverflow.com/questions/46016470/outlook-addin-window-open" target="_blank" rel="noopener noreferrer" data-auth="NotApplicable"><span style="font-size: 8.5pt; font-family: Verdana, sans-serif, serif, EmojiFont; color: rgb(25, 118, 210); background: white;">link</span></a> window.open is not supported in Outlook web add-in.

Any help is appreciated.

**Comment by kbrandl** [comment]
@AnushKatari sorry to hear that you've run into this problem. @exextoc can you please look into this?

**Comment by exextoc** [comment]
Hi, thanks for reporting this bug, and sorry for the delay in getting back to you. We are able to reproduce this issue, and have added it to our backlog. However, we do not have any timelines to share at this point.
