### ISSUE TITLE
Contect developer of old COM Addin model

### ISSUE THREAD

**Issue by lutz** [OfficeDev/office-js#3502]
Hello community,

i know it is not the right place but mybe someone has an idea for this. I try to find out how i can send microsoft a bug in the old COM Addin model (COM, VSTO, Word VBA/C#) which is very annoying.

I know the com model is not more the prefered to create addins but there are a lot of customer who use this.

Maybe someone from the js developer team has an idea.

Best regards

**Comment by qinliuMSFT** [comment]
Hi @lutz , please refer to this [Get Support](https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide) documents to ask for help if you are an admin for a business subscription. Or you could directly click "Help improve Office?" button which is below the Close button in Office applications to report a problem. 
![image](https://github.com/OfficeDev/office-js/assets/73509856/26b1bb69-2121-4a15-8354-612f425c8a03)

All of those approach will submit your issue to the support team or the product team.

**Comment by qinliuMSFT** [comment]
Hi @lutz , please refer to this [Get Support](https://learn.microsoft.com/en-us/microsoft-365/admin/get-help-support?view=o365-worldwide) documents to ask for help if you are an admin for a business subscription. Or you could directly click "Help improve Office?" button which is below the Close button in Office applications to report a problem. 

All of those approach will submit your issue to the support team or the product team.
