### ISSUE TITLE
Outlook add-in mac can't get occurrence event original start time, when call restful api

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#3507]
when we open occurrence event and call: https://outlook.office365.com/api/v2.0/me/events/xxxx/?$select=originalStart&v=0.23824974855078218
we got block request.
In Mac old outlook UI it happened 100%
![image](https://github.com/OfficeDev/office-js/assets/1878089/3e564447-bb4d-483a-91f5-8211d0d78d36)

In Mac new outlook UI it offen happened after create recurrence meeting, and then edit this occurrence event immediately, maybe in 1-10 seconds.
![image](https://github.com/OfficeDev/office-js/assets/1878089/23027f55-9a95-4f6f-b792-0ff6f95049b5)

**Comment by exextoc** [comment]
We are not able to repro the issue at our end, can you please share the code snippet which you trying? Thanks.

**Comment by hello-chenchen** [comment]
you can try this one:

```
 function getItemId () {
    return new Office.Promise(function (resolve) {
        if (Office.context.requirements.isSetSupported('Mailbox', '1.8')) {
            Office.context.mailbox.item.getItemIdAsync(function(result) {
                if(Office.AsyncResultStatus.Succeeded == result.status) {
                    console.log('test get item id: ', result.value);
                    resolve(result.value);
                }
            });
        }
    });
};

function convertToRestId (itemId) {
    if (Office.context.requirements.isSetSupported('Mailbox', '1.3')) {
        return Office.context.mailbox.convertToRestId(itemId, Office.MailboxEnums.RestVersion.v2_0);
    }
}

function getRestUrl () {
    if (Office.context.requirements.isSetSupported('Mailbox', '1.5')) {
        return Office.context.mailbox.restUrl;
    }
}


function getOriginalStartTime () {
    getItemId().then(function (itemId) {
            if (Office.context.requirements.isSetSupported('Mailbox', '1.5')) {
                Office.context.mailbox.getCallbackTokenAsync({ isRest: true }, function (result) {
                    var token = result.value;
                    var restId = convertToRestId(itemId);
                    var filterString = "?$select=originalStart";
                    var baseUrl = getRestUrl();
                    var getMessageUrl = baseUrl + '/v2.0/me/events/' + restId + filterString;
                    var authHeader = 'Bearer ' + token;
                    console.log('getCallbackTokenAsync: ', result, restId, getMessageUrl, authHeader);

                    var xhr = new XMLHttpRequest();
                    xhr.onreadystatechange = function() {
                        if (xhr.readyState === 4 && xhr.status === 200) {
                            var response = xhr.responseText;
                            console.log(response);
                        }
                    };
                    xhr.open('GET', getMessageUrl, true);
                    xhr.setRequestHeader('Content-Type', 'application/json');
                    xhr.setRequestHeader('Authorization', authHeader);
                    xhr.send();
                });
            }
    });
}

getOriginalStartTime()
```

**Comment by hello-chenchen** [comment]
you need edit occurrence event, and excute the demo code in add-in
Mac Old UI:
<img width="2560" alt="image" src="https://github.com/OfficeDev/office-js/assets/1878089/95a95a01-9770-4069-9809-2cac2f03c82c">
Mac New UI:
<img width="2560" alt="image" src="https://github.com/OfficeDev/office-js/assets/1878089/c5f0af7c-64c1-43d7-b4fd-6c85e5d33509">

**Comment by exextoc** [comment]
Hey @hello-chenchen 

To resolve the issue you're facing, we kindly request you to switch to the new UI. This change will help resolve your issue. To move to the new UI, turn on the toggle on the top right of Outlook.

**Comment by aigolang** [comment]
When we calling OfficeJs getCallbackTokenAsync which provides scoped token, after decode the access token, we can find:
In Old Outlook for Mac: "happ": "EWS".
In New Outlook for Mac: "happ": "OutlookService".

In the Outlook Add-in manifest, we can find Permissions "ReadWriteItem" which does not support EWS, only "ReadWriteMailbox" support EWS. So for Old Outlook for Mac, we need to change "ReadWriteItem" to "ReadWriteMailbox" in the manifest. ("ReadWriteItem" will only work for New Outlook for Mac.)
<OfficeApp>
...
  <Permissions>ReadWriteMailbox</Permissions>
...
</OfficeApp>

Reference:
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/manifests?tabs=xmlmanifest#permissions

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
