### ISSUE TITLE
Mac new outlook UI sometimes can't get serise id, or event item id

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#3508]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

1. on the first create recurrence meeting, and immediate, edit this occurrence event, sometimes we can’t get Office.context.mailbox.item.seriesId. in this case, customer can see update button in occurrence, if we update, the whole recurrence meeting will be changed.
![image](https://github.com/OfficeDev/office-js/assets/1878089/1be8bd7e-46d9-4a27-87a6-626dbbd2f89c)

2. sometimes, we can get Office.context.mailbox.item.seriesId, but can’t get event item id. in this case, customer will see the seem problem. they can’t edit this occurrence event.
![image](https://github.com/OfficeDev/office-js/assets/1878089/fb6dbce8-d914-4876-9d33-0fd03d4c26ae)

**Comment by exextoc** [comment]
For the first issue reported here, we are able to repro the issue, can you please confirm if this happens only when the occurrence is opened immediately after recurrence is created?

For the second issue mentioned, does this also happen when the occurrence is opened immediately and what is the error you see in this case?

**Comment by hello-chenchen** [comment]
1. yes, i only can reproduce in this case.
2. in our code, if we can't get event item id(only null result return from api, you can get it from my screenshot). we can't use the event id to call outlook restful api to get the occurrence original start time

**Comment by exextoc** [comment]
Thank you for the clarification and also for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: [8120989]
