### ISSUE TITLE
Open a new document from a template in a Word add-in

### ISSUE THREAD

**Issue by JxEngel** [OfficeDev/office-js#3512]
Hello, we are developing an Angular Word office add-in. It seems a simple task, but we are getting stuck programmatically calling a sharepoint link to a template and opening a new document in the current desktop Word window. Is this functionality implemented? We have not been successful to find any documentation or examples of doing this. We did come across office uri's. We were unable to implement this to open a document from a template. We also have seen something about creating documents from a base64 string but do not understand how to take a sharepoint link and make it a base64 string for the "context.application.createDocument" method. Any help you can provide would be amazing! 
Thanks, Josh

**Comment by samantharamon** [comment]
Thanks for reaching out, @JxEngel.

@wangyun-microsoft, could you please assist with this query when you get a chance?

**Comment by ZYUN-MSFT** [comment]
Hi @JxEngel , Thanks for reaching us. 

For _open a new documents from a template in a Word add-in (API)_ is current not support.

For this new feature ask, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.

Thanks for your support.

**Comment by wangyun-microsoft** [comment]
@JxEngel Can I know more about your scenario here. Do you want to automatically create a document with template, or you could manually create a document, and import the template into the new document by add-in?
