### ISSUE TITLE
How to use in a NodeJS project

### ISSUE THREAD

**Issue by SiNONiMiTY** [OfficeDev/office-js#3513]
Are there any guides on how to use this directly on a NodeJS project via importing?

Wanted to use the Office APIs but the resources on how to do it is very limited.

**Comment by samantharamon** [comment]
Thanks for your question, @SiNONiMiTY. For guidance with developing Office Add-ins, see the [Beginner's Guide to Office Add-ins](https://learn.microsoft.com/office/dev/add-ins/overview/learning-path-beginner). This article provides links to our quick starts that use Node.js and Visual Studio Code (see our [Excel quick start](https://learn.microsoft.com/office/dev/add-ins/quickstarts/excel-quickstart-jquery), for example).

Please note that this forum is for issues with our product or documentation, not for programming questions about your code. For guidance, we suggest you go to [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/office-js-dev.html) and see if your question has already been asked or ask a new question.

Thanks,
Microsoft 365 Developer Platform team
