### ISSUE TITLE
Access contacts in the people section of Outlook 

### ISSUE THREAD

**Issue by abhinovpankaj** [OfficeDev/office-js#3514]
## Microsoft 365 Developer Platform Ideas Forum

Currently, there is no support to work with Contacts in a Outlook web add-in.
Neither can I add a button in Contacts ribbon nor I have a way to get the selected contact(s).

**Comment by timwan10** [comment]
A Contact extension point you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

The only way to currently access Contacts on the Exchange account, would be in a Calendar/Mail Add-in, and use Graph/REST or EWS to access the contact information from the server.
