### ISSUE TITLE
Screen size in window object gives incorrect width and height

### ISSUE THREAD

**Issue by elemen7s** [OfficeDev/office-js#3515]
I have an event based Outlook addin with an ItemSend Event. When the user clicks on the Send button, I need to open a dialog using the displayDialogAsync. Since this only accepts a percentage for width/height I am calculating the ideal percentage based on the screen size for my content to fit without any scroll bars or extra space.

This works fine on Outlook Web but is not working fine for Outlook Windows. 

This issue is reproducible when you have 2 screens with different resolutions and the dialog is opened on the screen which is not the main display. For example a laptop screen and an external screen.

The width/height retrieved from any of the below parameters are of the main display set in Windows Display settings and not where the compose window or even the main outlook window is opened.

- window.screen.height / window.screen.width
- window.screen.availHeight / window.screen.availWidth

Other parameters such as window.innerHeight or window.outerHeight gives much worse numbers which doesn't even make sense (getting 80 or 118 in some of the fields on a 4k screen)

XML manifest ItemSend event 
`<ExtensionPoint xsi:type="Events">
     <Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="onItemSendHandler" />
</ExtensionPoint>`

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2305 (Build 16501.20242)
* Operating System: Windows 11
 
## Expected behavior
Expected behaviour is for any of the parameters of window object to give the correct width/height depending where the compose window is opened and ultimately where the dialog will be opened.

## Current behavior
The parameters of windows object are giving the width/height of the main display set in Microsoft Windows display settings.

## Steps to reproduce

1. Create an event based addin with ItemSend event
2. Call any of the parameters of the window object

**Comment by elemen7s** [comment]
@exextoc Any update please on this?

**Comment by timwan10** [comment]
There isn't really a good solution here. For the ItemSend Event or really any "ExecuteFunction" "UIless" action. The Webview that runs your add-in is created in a hidden window that doesn't move around with the active window, and it can easily be on a different monitor than the actual dialog. The % input to dialog is intended to somewhat mitigate this issue, by allowing you to adjust the size of the dialog to adjust to the size of the screen. 

I can see how this would not work if you have some fixed size objects that you don't want to scroll. Suggestions for added support/features should go to the Tech Community Page: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

With the label "product feature request"
