### ISSUE TITLE
All file formats that do not support Office add-ins (Word, Excel, Power Point)

### ISSUE THREAD

**Issue by deviluncle** [OfficeDev/office-js#3518]
## Post how-to questions about your code on Microsoft Q&A

Please tell me all file formats that are not supported by Office add-ins (Word, Excel, Power Point).

From Office365 (Excel, Word, PowerPoint) add-in, create an Office add-in that saves the file being edited by our SaaS.

Depending on the file format, there may be a phenomenon that the add-in is invalid and unavailable.

■Content of consultation

In the Office file format of the following documents
Please tell me which file formats are supported/not supported by Office Add-Ins (Word, Excel, Power Point).
https://learn.microsoft.com/ja-jp/deployoffice/compat/office-file-format-reference

I have consulted about this question before, and Microsoft replied that the commonly used formats are basically supported, but after confirming that the doc format, xls format, and ppt format should not support add-ons, open the files of these three formats, and the add-in column is grayed out. unavailable state. So please check again.

**Comment by samantharamon** [comment]
Thanks for reaching out, @deviluncle.

@wangyun-microsoft or @ZYUN-MSFT, would you be able to assist with this query?

**Comment by wangyun-microsoft** [comment]
@deviluncle, the recommended formats are docx, pptx and xlsx. Can you let us know what other file formats are you looking for?

**Comment by deviluncle** [comment]
> @deviluncle, the recommended formats are docx, pptx and xlsx. Can you let us know what other file formats are you looking for?
Thank you for your reply, I want to know whether the files in .xls, .ppt, .doc format are supported

**Comment by ZYUN-MSFT** [comment]
Hi @deviluncle ,

The .xls .ppt .doc format are not supported. Please use .xlsx .pptx .docx file format.

Thanks.
