### ISSUE TITLE
Microsoft Single Sign On no longer working in Add-in in Excel online

### ISSUE THREAD

**Issue by cidev5** [OfficeDev/office-js#3520]
Users of our add-in were previously able to log-in to our app in Excel online using the Microsoft identity provider.

As of Thursday we are receiving reports that this is no longer working. I have tested this myself and am seeing the same. Please see the below screenshot for what is happening. It appears an X-Frame-Options header set to DENY has been added to the login page we need our users to login through.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Browser (if using Office on the web): All browsers
 

![MicrosoftTeams-image (14)](https://github.com/OfficeDev/office-js/assets/22505624/53f041a3-5fec-44ad-92bb-b9260de2f389)

**Comment by ghost** [comment]
Thank you for letting us know about this issue. We will take a look shortly. Thanks.

**Comment by ZYUN-MSFT** [comment]
Hi @cidev5 , thanks for reaching us.

Would you please help to provided the more detail repro steps? That's would be help a lot.

Thanks.

**Comment by cidev5** [comment]
@ZYUN-MSFT 

Repro steps:

1. Create a taskpane add-in.
2. Taskpane should redirect to the page https://login.microsoft.com
3. Add add-in in Excel for web
4. Launch Add-in taskpane
5. Confirm issue happens per my screenshot

Note that this issue ONLY exists in Excel for web. It does not happen in Excel for Desktop.

**Comment by ZYUN-MSFT** [comment]
Hi @cidev5 ,

Could you please provided the add-in you described? Then we could install it and take investigation more effective.

Thanks.

**Comment by cidev5** [comment]
@ZYUN-MSFT ,

Is there a way for us to communicate off this thread? Our add-in is not intended for general public use and I don't feel comfortable providing that information here.

**Comment by ZYUN-MSFT** [comment]
Hi @cidev5 ,

My working EMail is zyun@microsoft.com\
We can start a new thread with EMail about this.

Thanks.

**Comment by ZYUN-MSFT** [comment]
Hi @cidev5 ,

I got some reply from our engineering team, please check that whether it will be helpful.

> Interactive login (AFAIK) has never been supported inside of iframes due to ESTS’ security posture of embed rejection as a click-jacking preventative measure.
>
> The customer needs to perform a pop-up-based auth or use prompt=none in their request. From the limited set of console output in the issue, it looks like they’re attempting to perform a full page redirect in an iframe, which is a no-go.
>
> I suspect the customer tested their add-in on desktop only, which could explain differing behavior (e.g., app is top-level in webview, 3P cookies enabled, or otherwise).

Thanks.
