### ISSUE TITLE
When converting DOC format to HTML, some styles such as images and background colors lost.

### ISSUE THREAD

**Issue by lunarpang** [OfficeDev/office-js#3525]
I am a product manager from the WeChat team and I am interested in using your Word to HTML conversion capability. 
When I open a DOCX file in Word and then save it as an HTML file, all the styles are preserved, and the images are also included.
But, when i use Cloudmersive it lose images and styles.The guideline i use as believe
https://learn.microsoft.com/en-us/connectors/cloudmersiveconvert/

My usage will be very high. Do you charge for your service? If so, what are the fees like? I am looking forward to your reply and excited to work with you.

My office is located in Beijing, China.If it's convenient, could you please provide your contact information?

**Comment by samantharamon** [comment]
Thanks for reaching out, @lunarpang.

I'm connecting you with @wangyun-microsoft for further assistance.

**Comment by wangyun-microsoft** [comment]
Hi @lunarpang, can you fill this form so that we could have a talk?
https://forms.office.com/r/wAdsep7pU4
Thanks.

**Comment by lunarpang** [comment]
done，waiting for your reply.

**Comment by lunarpang** [comment]
hi，
I've filled the form two days ago. My work email is ***@***.***, thx















At 2023-07-19 16:17:10, "Wang Yun" ***@***.***> wrote:

Hi @lunarpang, can you fill this form so that we could have a talk?
https://forms.office.com/r/wAdsep7pU4
Thanks.

**Comment by wangyun-microsoft** [comment]
@lunarpang  I've sent you an email asking for a meeting. Thanks.

**Comment by lunarpang** [comment]
@samantharamon @wangyun-microsoft I'm looking forward to cooperate with Microsoft. I hope the messages in the group can be replied to more promptly.
<img width="783" alt="截屏2023-07-28 17 30 05" src="https://github.com/OfficeDev/office-js/assets/127950313/64122dcc-909b-49a7-8705-05ebc0d72deb">
<img width="827" alt="截屏2023-07-28 17 29 52" src="https://github.com/OfficeDev/office-js/assets/127950313/507224a3-da8d-49b8-b969-ac6f355d8476">

**Comment by wangyun-microsoft** [comment]
@lunarpang We understand that you are waiting for an answer here. However, your question is related to cloudmersive, not Office JavaScript add-in. Please submit your request to Power Platform here: 
https://learn.microsoft.com/en-us/power-platform/admin/get-help-support
https://powerusers.microsoft.com/t5/Forums/ct-p/FL_Comm_Forums

Thanks.
