### ISSUE TITLE
Office.context.document.getFileAsync() not working in Excel on iPad

### ISSUE THREAD

**Issue by s137** [OfficeDev/office-js#3526]
Unfortunately the office-js function I'm using in my office add-in to retrieve the document/sheet as a binary file `Office.context.document.getFileAsync(...)` on the iPad does only work in Word and Powerpoint, but not Excel. Can you tell me why this is and if there is any alternative solution to getting the file in Excel on iPad.  If not is it somehow possible to exclude only Excel on iPad as a target of the AddIn, but not Excel on other Platforms like Windows?

![excel2](https://github.com/OfficeDev/office-js/assets/9917413/0efd7305-3ffc-4e5e-8a2b-ed8d4de3a324)

see also: [https://learn.microsoft.com/en-us/javascript/api/office/office.document?view=excel-js-1.17#office-office-document-getfileasync-member(1)](https://learn.microsoft.com/de-de/javascript/api/office/office.document?view=excel-js-1.17#office-office-document-getfileasync-member(1))

Thanks in advance for your help.

**Comment by s137** [comment]
In the Issue [#757](https://github.com/OfficeDev/office-js/issues/757#issuecomment-541555685) @hungvnguyen-kms described the same problem, but there was no solution or alternative given.

**Comment by samantharamon** [comment]
Thanks for reaching out, @s137.

@ZYUN-MSFT, could you please assist with this when you get a chance?

**Comment by ZYUN-MSFT** [comment]
Hi @s137 ,

We'are still investigating this issue. We'll update here once we got the conclusion.

Thanks.

**Comment by s137** [comment]
Hello @ZYUN-MSFT, 

Do you maybe have an update on the issue? If necessary I can gladly provide additional information. Just tell me if you need anything else. 

Thanks.

**Comment by SiruiSun-MSFT** [comment]
Hi @s137, Sorry for the late response. I'm afraid this method you ask is not supported for the iOS platform, as the doc said. For your second question, maybe you could leverage the runtime check method, which means using Office.context.platform to check the current platform. After that, you could add the different behavior you want. Here is the doc link: https://learn.microsoft.com/en-us/javascript/api/office/office.context?view=word-js-preview#office-office-context-platform-member. Hope this will help you!

**Comment by s137** [comment]
Hello @SiruiSun-MSFT,

Thanks for your reply! Unfortunately, that's really discouraging to hear, because it's not really understandable, why such a basic functionality as retrieving the file itself would work everywhere but excel on iPad. I still can't see any reason for this limitation, but I guess I'm going to have to live with it.

So as for the second question, do you see any alternative way of getting the file other than using this method, because without this functionality the add-in we are working on is basically useless on the iPad.

And if not, can I exclude ONLY the specific target of "excel on the iPad" (not excel on Android or Mac or Windows, but only on the iPad) from the marketplace offering? And if so, can you tell me how to do that?

Thank you very much in advance for your help with this.

**Comment by SiruiSun-MSFT** [comment]
Hi @s137, Maybe there isn't a better way to solve your problem as far as I know. Maybe you can submit a request here about this API support for the iOS platform [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Feature requests are considered when we go through our planning process. 

For your ask to exclude iOS platform, as I suggested before, we recommend you leverage the runtime check method. When the user opens your addin on the iPad Excel, the Office.context.platform could be aware of this and show the behavior as you designed in the code.

**Comment by s137** [comment]
Alright, thank you. I posted my feature request on the [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions)
