### ISSUE TITLE
Getting the from address for a forwarded meeting gets the "on behalf of" address only

### ISSUE THREAD

**Issue by barclayadam** [OfficeDev/office-js#3528]
We need to know the From address to generate the correct signatures for our customers. When forwarding a meeting invite the from address in the API (`Office.context.mailbox.item.from`) is returning the original sender of the invite. 

The behaviour is inconsistent between OWA and Windows Outlook.

## Your Environment
* Platform: PC Desktop
* Host: Outlook
* Office version number: 16.0.16628.20000
* Operating System: Windows 11
 
## Expected behavior
The From address returned by `from.getAsync` should be the user, not the original sender of the meeting invite

## Current behavior

On desktop only I get the "on behalf of" address:

![image](https://github.com/OfficeDev/office-js/assets/973909/6f8239ce-582d-4a1e-b765-add6ae0cd54c)

## Steps to reproduce
1. Send a meeting invite
2. Forward that meeting invite from the different receiving mailbox
3. Call `Office.context.mailbox.item.from.getAsync` and record that the returned value is `adam@cloutex.io` and not the expected `adbdevadmin@6c5gmw.onmicrosoft.com`

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Adrian-MSFT** [comment]
Thanks for reporting this issue regarding the fom.getAsync() API. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: 8181423
