### ISSUE TITLE
Word online addin -  range.style fails in Word Online - works in Client

### ISSUE THREAD

**Issue by abtrip** [OfficeDev/office-js#353]
When using the below code snippet in Word JS addin in Word online for a document containing customer style in below format , we get error
style name - 
ABC Head - Fails in Wrd online, Works in Word client  
Abc Head - Works in both Word online and Word client 

function Setstyle() {
        Word.run(function (context) {
            // Queue a command to get the current selection and then
            // create a proxy range object with the results.
            var range = context.document.getSelection();

            range.style = "ABC Head";  //fails
            //range.style = "Abc Head";  //works

            return context.sync();

            
        })
        .catch(errorHandler);
    }

## Expected Behavior
Even with ABC Head as the style name, it should work without error in both word online and client 

## Current Behavior
We are getting error when running the add-in

error - 
WordEditor.js:227 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
executeRequest @ WordEditor.js:227
MicrosoftAjax.js:5 OSF_Outil_getQueryStringParamValue: The parameter is not found.

## Steps to Reproduce, or Live Example
Create a basic Word JS add-in and use the below code on any button click to set style for a range in a document which contains that custom style which you are trying to set - try with both ABC Head and Abc Head to see the one failing and second working in Word online.

function Setstyle() {
        Word.run(function (context) {
            // Queue a command to get the current selection and then
            // create a proxy range object with the results.
            var range = context.document.getSelection();

            range.style = "ABC Head";  //fails
            //range.style = "Abc Head";  //works

            return context.sync();

            
        })
        .catch(errorHandler);
    }

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

Our style naming convention has been like this - ABC Head or XYZ test or TEST Style and because of this issue we are unable to use it

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______ windows 10 - 16.0.11214.33701
* Host [Excel, Word, PowerPoint, etc.]: _____ Word
* Office version number: ______Word online version 16.0.11214.33701
* Operating System: ______ Win 10 
* Browser (if using Office Online): ______ IE 11 and chrome 

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by kbrandl** [comment]
@abtrip thanks for reaching out and sorry to hear that you've run into this problem.

@JuaneloJuanelo are you able to provide any feedback about this issue?

**Comment by abtrip** [comment]
Hi all - i want to check back on this issue for your feedback and help

**Comment by abtrip** [comment]
A gentle check on this

**Comment by JuaneloJuanelo** [comment]
@abtrip  what is the literal style name you used when creating it? "ABC Style" or "Abc Style" or which one.

**Comment by JuaneloJuanelo** [comment]
I was able to repro this issue and i noticed that its not even working with any option in Online. its a bug and 
we are tracking with 2874167.

**Comment by JuaneloJuanelo** [comment]
issue was fixed and rolling out to prod, we will be able to validate soon.

**Comment by JuaneloJuanelo** [comment]
update: fix has still not propagated. we are still working on the fix. Assigning to @weshi  to track this properly.

**Comment by AbidRahman-MSFT** [comment]
This issue has been fixed in version 16.0.11329.1+ for Word. If you are still running across this problem, please open a new issue. Thanks.
