### ISSUE TITLE
Add in is not loading in excel online.

### ISSUE THREAD

**Issue by vinay-sattur** [OfficeDev/office-js#3532]
When the excel loads we are getting the error in the browser console as shown below,

Can't find Office Add-in from Microsoft AppSource given addin ID: WA200002270 (content market: en-US). Exception details: {}

* Platform [PC desktop, Mac, iOS, Office on the web]:  web
* Host [Excel, Word, PowerPoint, etc.]: Excel

 
## Expected behavior
Addin should auto load when the excel online loads.

## Current behavior
Addin is not auto loading. Getting the below error message.
Can't find Office Add-in from Microsoft AppSource given addin ID: WA200002270 (content market: en-US). Exception details: {}

# Provide additional details
Session ID: 90596c32-e4ec-4757-bf09-4649da5eb602
Build: 16.0.16717.42308

## Context
The addin is used for student assignments. This is a P1 issue for us.

**Comment by SiruiSun-MSFT** [comment]
Hi @vinay-sattur, thanks for reporting this issue. The office store may currently be unavailable due to some issues. We already have engineers doing emergency mitigation. If complete, we'll share the progress here. Sorry for bringing this blocking problem.

**Comment by SiruiSun-MSFT** [comment]
Hi @vinay-sattur, seems the issue I mentioned before has been mitigated. Could you please retry the loading and help us verify? Thanks for your patience!

**Comment by vinay-sattur** [comment]
Hi @SiruiSun-MSFT , Yes. The addin is loading fine now. Thank you for the quick resolution of the issue!

**Comment by BIPLAB82** [comment]
<img width="1664" alt="image" src="https://github.com/user-attachments/assets/0d64e636-70ce-4f7c-94c7-0fb50db28e45">
We are seeing this issue again
