### ISSUE TITLE
[Word Add-in] Do word add-ins work/load in iPhone and Android devices?

### ISSUE THREAD

**Issue by VelinGeorgiev** [OfficeDev/office-js#3533]
Do word add-ins work/load on iPhone and Android devices?

We currently have a Word Add-in deployed and working for Word in SharePoint as well as Word Desktop app, but it does not load from Word for iPhone as well as the Microsoft 365 app for iPhone.

I could not find any official documentation if Word add-ins work in mobile devices like iPad, iPhone (iOS) nor Android devices. 

Can you please point me to the right documentation? Thanks!

**Comment by Rick-Kirkham** [comment]
Word add-ins are supported on some versions of iPhone. See [Word API requirement sets](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/word/word-api-requirement-sets). They are not supported on Android.

**Comment by VelinGeorgiev** [comment]
Thanks for your quick response @Rick-Kirkham!

I do not see iPhone explicitly mentioned, but I see an explicit iPad mention. Does this mean it is supported only on iPad devices, or can I assume it will work on iPhone devices with the same required version of iOS? 

Our iPhone tests indicate the Word addin using [WordApi 1.4](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/word/word-api-1-4-requirement-set?view=word-js-preview) does not load at all when using iPhone 13 ios 16.6.
