### ISSUE TITLE
How do I log bugs for new Outlook?

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/office-js#3534]
There are bugs in new Outlook that are being logged with us because we offer an Outlook add in

How do I escalate these to Microsoft?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 930ce4fc-c8b8-f756-f03f-a716f1ef7883
* Version Independent ID: 753a2e38-9430-25bb-5409-b7eed9c88e47
* Content: [Build your first Outlook add-in - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator)
* Content Source: [docs/quickstarts/outlook-quickstart.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/quickstarts/outlook-quickstart.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
Hi @catmanjan, you may use this forum to report bugs if it is related to an Outlook web add-in. Thanks!
