### ISSUE TITLE
outlook add-in

### ISSUE THREAD

**Issue by OS-Lee** [OfficeDev/office-js#3538]
Followed the https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart-json-manifest to test outllook add-in.

The Sideloading will be using manifest.zip instead of manifest.xml now.

Sideloading the Office Add-in...
Manifest package saved to C:\Users\xxx\AppData\Local\Temp\manifest.zip
running: npx @microsoft/teamsfx-cli@2.0.2-alpha.4f379e6ab.0 m365 sideloading --file-path C:\Users\xxx\AppData\Local\Temp\manifest.zip

Suppose I host the 'web' project to a web server. How could sideloading the add-in for other users to test instead of local debugging only?

**Comment by exextoc** [comment]
If your add-in's web portion is hosted on a web server that is accessible to the other users, and this web server is referenced in the JSON manifest instead of localhost, the other users can sideload your add-in and it will work for them. Does that answer your question or did I misunderstand your question?

**Comment by OS-Lee** [comment]
> If your add-in's web portion is hosted on a web server that is accessible to the other users, and this web server is referenced in the JSON manifest instead of localhost, the other users can sideload your add-in and it will work for them. Does that answer your question or did I misunderstand your question?

But other users need to do this via command per my understanding as the new 'package' file is manifest.zip; any improvement plans?
```
npx @microsoft/teamsfx-cli m365 sideloading --file-path C:\xxx\manifest.zip
```

**Comment by exextoc** [comment]
Packages can be installed via the Store/Marketplace if they are published by the developer.
Does that satisfy your expectation of an improvement here?

**Comment by OS-Lee** [comment]
> Packages can be installed via the Store/Marketplace if they are published by the developer. Does that satisfy your expectation of an improvement here?

It's a zip file(manifest.zip). Could you pls guide how to install?

**Comment by exextoc** [comment]
As you mentioned earlier on, you can install it via command line:

`npx @microsoft/teamsfx-cli m365 sideloading --file-path C:\xxx\manifest.zip`

If you want instructions on publishing / deploying add-ins, this documentation can guide you:
https://learn.microsoft.com/en-us/office/dev/add-ins/publish/publish
