### ISSUE TITLE
Outlook Add-in on-send trigger not firing for some accounts

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#3539]
# Provide required information needed to triage your issue
We are seeing on some accounts (not all) that our add-in's on-send function is not being triggered. This is a major issue, as important processing, including encryption and blocking of messages with secure information is not running.

I'm glad to jump on a call and demonstrate what is happening and with what accounts we are seeing it with if helpful at all.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop (new UI) & Browser
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): Chrome
 
## Expected behavior
The on-send function is ALWAYS triggered for any account using the add-in

## Current behavior

The email is just being sent immediately without triggering the on-send function.

## Steps to reproduce

1. Setup an add-in that has an on-send function (not smart alert).
2. Send an email
3. See that the on-send function is not triggered (this is occurring in OWA and Windows Desktop New UI only it appears)

## Link to live example(s)

# Provide additional details

We only see this on a subset of accounts (different organizations/domains). We are seeing this with our @virtruoffice.com domain accounts, but not @virtrutest.biz. I do not know what the different between these organizations may be. It also just started happening within the past day or so. Previously, it was working as expected for all of our domains.

## Useful logs

There are no errors in the developer console in the browser, so I have nothing to go on. It does not appear to be an issue with the add-in or manifest, as it works fine for some domains.

**Comment by JuaneloJuanelo** [comment]
we are looking into this. @cody-lettau  can you please add more details on the build numbers you are experiencing this, also make sure there is no proxy service blocking the add-in pages? seems to be happening within a specific domain, so please check that the add-in is accessible, while we  investigate.

**Comment by cody-lettau** [comment]
Thanks for getting back to me. So I don't think it's anything being blocked by a proxy as we also have the add-in working just fine in compose and read mode (on the domain that the on-send function isn't triggering). They all point at the CDN where the resources are hosted.

Our manifest for production is here: https://cdn.virtru.com/outlookjs/manifest/VirtruForOutlook.xml
That said, I'm not sure if you will be able to just use it without a paid account. You can try by installing the add-in, composing a new message, opening the add-in and activating by email. Then enable encryption (toggle button in the add-in pane). Click send. And there should be a on-send function that is called that does the encryption and other checks. You would see a popup saying "Virtru is processing this message" if it is working and encryption was enabled.

Nothing has changed with the manifest or our add-in in the past day and I do not believe we made any changes to the O365 organization that we use for automated tests (where we are seeing this issue). Other organizations we use for development work just fine.

I'd be glad to jump on a call to show you as well if that is helpful. But there are no errors in the dev console after clicking send and the on-send function not being triggered. The add-in works fine in compose and read for the same account, so it's definitely installed and able to pull the resources from the CDN.

Please let me know if I can provide anything else to help the team debug this.

**Comment by cody-lettau** [comment]
As for build numbers, we are definitely seeing this in OWA for this specific organization. Is there a way to tell exactly what build that would be using (since I know sometimes these accounts get pre-releases and what not)?

For Windows Desktop, we reproduced using the new UI on Windows 11 (22621.1992) and Outlook version 2306 (build 16529.20182).

**Comment by JuaneloJuanelo** [comment]
update: we cannot repro this issue on the builds indicated. This means that is a specific organization issue.

**Comment by cody-lettau** [comment]
I appreciate the team looking into this quickly. Glad we have determined it's only related to a specific org issue. Hopefully we can get that figured out and customers don't have the same issue.

**Comment by t-miyake** [comment]
@JuaneloJuanelo We are experiencing the same problem with our customers.
At this time, there are only a few occurrences of this problem. Several tenants are experiencing the same issue with several users of those tenants.

It may be a problem with some organizations, but we cannot address this issue because the cause of the problem is unknown.
We would appreciate it if you could take some action as soon as possible.

Note that we have confirmed that this is occurring in the Standard release environment of Outlook on the web.

**Comment by t-miyake** [comment]
@JuaneloJuanelo 
Several of our clients have reported this problem.
This means that more and more tenants are experiencing this problem.

Since we and our customers have not changed anything and the problem is occuring, we think it is some kind of Outlook on the web side issue.

Please recheck the issue.

**Comment by cody-lettau** [comment]
@t-miyake we've also been able to reproduce on Outlook for Windows (New UI) -- just a heads up.

**Comment by cody-lettau** [comment]
@JuaneloJuanelo we are also seeing this issue with another organization today (not all accounts in org, but multiple).

**Comment by t-miyake** [comment]
Even though the impact is limited, it is a serious issue for our customers.
Please take urgent action.

**Comment by exextoc** [comment]
Hi @t-miyake, we have patched a fix for this issue. Please ask the affected users to hard refresh OWA to get the latest client build and that should resolve the issue. Please let us know in case the issue still persists. Thanks!

**Comment by t-miyake** [comment]
@exextoc Thanks!  I will promptly inform our customers about this. If there are any further issues, i will report back to you here.

**Comment by t-miyake** [comment]
@exextoc I have confirmed that the issue has been resolved for several of our customers. Currently, we have not received any reports of the problem from our customers. Thanks!

**Comment by cody-lettau** [comment]
@exextoc this can be closed out thanks to the quick work by you and the team! Thank you for jumping on this so quickly.
