### ISSUE TITLE
the request cookie in windows Excel is wrong

### ISSUE THREAD

**Issue by kreja** [OfficeDev/office-js#354]
## Expected Behavior

I'm writing an excel add-in. It works fine in MacOS(though has some login questions), but when using it in Windows, there is a cookie problem.

## Current Behavior

The cookie in the request header has only one field, so the request can't get the right response
 
![](https://img.alicdn.com/tfs/TB1HvXez9zqK1RjSZFpXXakSXXa-2678-868.png)
![](https://img.alicdn.com/tfs/TB1RaVgz3HqK1RjSZJnXXbNLpXa-620-76.png)

Actually, when I print the `document.cookie` in F12 tool, there are many fields in cookie:

![](https://img.alicdn.com/tfs/TB1B50cz7voK1RjSZPfXXXPKFXa-620-35.png)

## Steps to Reproduce, or Live Example

I'm sorry I don't have a live example, it‘s a private add-in and is very difficult to mock.
But I can provide some clues:
- We use SSO, but not using Microsoft accounts, its our own SSO
- The request to the login page can carry right cookie so it redirected me to the page
- The page document responsed Set-Cookie: emplld=xxx, and then the requests on this page can only carry the cookie emplld=xxx, so I can't get the right response
- However, when I print document.cookie in console, it was not only emplld=xxx but had many fields

## Context

MacOs is ok, windows has the problem, so my users can't use it on windows now.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ___Windows___
* Host [Excel, Word, PowerPoint, etc.]: ___Excel___
* Office version number: ___Excel Version: 16.0.4738.1000___
* Operating System: ______
* Browser (if using Office Online): ______

**Comment by kbrandl** [comment]
@kreja thanks for reaching out and sorry to hear that you've run into this problem. 

@JuaneloJuanelo are you able to provide any feedback about this issue?

**Comment by kreja** [comment]
Do you have any ideas? I'm stuck by this issue.

**Comment by kreja** [comment]
waiting for your reply...

**Comment by JuaneloJuanelo** [comment]
@niteshgolchha85  i wonder if you can provide guidance on this case? thanks!

**Comment by kreja** [comment]
Seems to be the backend problem. Close this issue.
