### ISSUE TITLE
[Question] [Word] How to insert a floating element?

### ISSUE THREAD

**Issue by callvm** [OfficeDev/office-js#3542]
We have a use-case in our plugin where we need to insert a textbox-like element to a Word document. It's important that this element can be dragged around freely by the user without moving other elements on the document. We have tried to add a textbox, but it doesn't seem like this is possible with the package at the moment.

For the meantime, we have added a table, and inserted the information we need inside this table. However, when the user moves the table, it moves all the other elements around the page. They also aren't able to place the table near the bottom of the page for example, as this sends it to the next page.

We also explored using an image, but again, the package only allows inserting inline images, so dragging the image around moves other elements on the document.

Has anyone been able to insert any kind of "floating" element with the package, that can be dragged around freely without disturbing other elements? We'd also need to query the document at a later stage, to get a list of all these elements we insert. We're currently able to do that with the table.

Please close this issue if it's not appropriate to post here.

Any assistance would be greatly appreciated.

**Comment by ZYUN-MSFT** [comment]
Hi @callvm ,

Thanks for reaching us. For dev question and discussion, we recommand exploring or posting on our StackOverlow https://stackoverflow.com/questions/tagged/office-js

Thanks.

**Comment by callvm** [comment]
Thanks @ZYUN-MSFT , I've had a look on SO and there are no questions related to the issue I'm having. I've also posted a question here (https://learn.microsoft.com/en-us/answers/tags/255/javascript-api). Are there any other resources I can try?

**Comment by ZYUN-MSFT** [comment]
Hi @callvm ,

Please create a new post on StackOverflow with questions tagged [office-js].

Thanks.

**Comment by callvm** [comment]
I found the solution by inserting OOXML. I'm now able to insert a textbox into a document from OfficeJS. SO question with solution linked: https://stackoverflow.com/questions/76849947/how-to-insert-a-floating-element-in-word-using-office-js/76859020#76859020
