### ISSUE TITLE
[Outlook] Allow to add attachments to certain positions in attachments list

### ISSUE THREAD

**Issue by Suntechnick** [OfficeDev/office-js#3543]
Currently, `addFileAttachmentAsBase64Async` API adds the file to the end of attachment list in mailbox.

In our addin, our workflow looks like this:
* Get attachments from mailbox
* Possibly, remove some attachments
* Do some manipulations with removed files
* Attach manipulated result files to mailbox (currently adds to the end of the attachment list)

This leads to situations where resulting attachments list order if different to how it was initially, which is not ideal for us.

Providing the option to insert attachment to certain position in the list would allow us to fix this issue.

**Comment by davidchesnut** [comment]
Hi @Suntechnick, thanks for posting this feature request. Can you please post it to our feature suggestions list at https://aka.ms/m365dev-suggestions where we track feature suggestions? 

Thank you!
David
