### ISSUE TITLE
[Outlook] In Outlook internetHeaders.setAsync API lowercases the provided header name

### ISSUE THREAD

**Issue by Suntechnick** [OfficeDev/office-js#3544]
In Outlook `internetHeaders.setAsync` API lowercases the provided header name. We want to name the headers according to our conventions so current behavior is not desired for us, so we would like to know if there is a way to prevent this.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: -
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: -
* Browser (if using Office on the web): -
 
## Expected behavior
Header name in `internetHeaders.setAsync` API should not be modified.

## Current behavior
Header name in `internetHeaders.setAsync` API is always in lowercase.

## Steps to reproduce
1. Using the `internetHeaders.setAsync` API, set the header with name "MyCustomHeader"
2. Send the email and check the custom header name (as of now, it will be modified to "mycustomheader")

**Comment by Oleg-O** [comment]
Per MIME standards (RFC822 and other RFCs), internet headers are expected to be interpreted in a case-insensitive manner. They are also not expected to be visible to end-users - only to MIME handling software. I guess, my follow-up question here is what is the scenario where (and why) this is important?

This API indeed has the behavior you described. We'd be reluctant to change it as there is non-zero risk of breaking existing flows involving software that may not follow MIME RFCs precisely. Therefore, this would effectively be a new feature request. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by Suntechnick** [comment]
Thank you for your detailed answer.
We'll discuss this topic among our team with the information you provided.
