### ISSUE TITLE
unable to add custom mail header with folding (RFC 5322)

### ISSUE THREAD

**Issue by Arikael** [OfficeDev/office-js#3546]
# Provide required information needed to triage your issue
I'm currently unable to add custom headers which are longer than 998 charachtes but conform to RFC 5322 (folding).

**Header to add**
```
my-type="urn:my:test:which:is:longer:than:998:1:0";
 my-param*0="PG1iOadpbmRpbmdJbmZvcm1hdGlvbiB4bWxuczp4c2k9Imh0dH";
 my-param*1="A6Ly93d3cudzMub3JnLzIwMDEvWE1MU2NoZW1hLWluc3RhbmNl";
 my-param*2="IiB4bWxdfgg4c2Q9Imh0dHA6Ly93d3cudzMub3JnLzIwMDEvWE";
 my-param*3="1MU2NoZW1hIiB4bWxuczpkcz0iaHR0cDovL3d3dy53My5vcmcv";
 my-param*4="MjAwMC8wOS94bWxkc2lnIyIgeG1sbnM6eG1pbWU9Imh0dHA6Ly";
 my-param*5="93d3cudzMub3JnLzIwMDUvMDUveG1sbWltZSIgeG1sbnM6bWI9";
 my-param*6="InVybjpuYXR934dfgfdhZzo0Nzc4OmJpbmRpbmdpbmZvcm1hdG";
 my-param*7="lvbjoxOjAiPjxtYjpNZXRhZGF0YUJpbmRpbmdDb250YWluZXI+";
 my-param*8="PG1iOk1ldGFkYXRhQmluZGluZz48bWI6TWV0YWRhdGE+PHNsYW";
 my-param*9="I6b3JpZ2luYXRvckNvbmZpZGVudGlhbGl0eUxhYmVsIHhtbG5z";
 my-param*10="OnNsYWI9InVybjpuYXRvOnN0YW5hZzo0Nzc0OmNvbmZpZGVudG";
 my-param*11="lhbGl0eW1ldGdfgfdgfdagfdaggTowIj48c2xhYjpDb25maWRl";
 my-param*12="lhbGl0eW1ldGdfgfdgfdagfdaggTowIj48c2xhYjpDb25maWRl";
 my-param*13="lhbGl0eW1ldGdfgfdgfdagfdaggTowIj48c2xhYjpDb25maWRl";
 my-param*14="lhbGl0eW1ldGdfgfdgfdagfdaggTowIj48c2xhYjpDb25maWRl";
 my-param*15="lh1sdffW1ldGFkYXRhbGFiZWw6MTowIj48c2xhYjpDb25maWRl";
```

**code which adds the header**
```
export async function addHeader(data) {
 let result = false
 const item = Office.context.mailbox.item
 await item.internetHeaders.setAsync({
        "my-header": data
  }, function (asyncResult) {
        console.log('got result')
        console.log(asyncResult.status)
        result  = asyncResult.status === Office.AsyncResultStatus.Suceeded
   })
}
```
there are multiple issues
- office.js has a fixed header limit of 998 (which is basically fine for a normal header) but it just checks for the length and ignores header folding.
- I tried to remove this check, but then the call to outlook itself (I assume) fails.
on outlook 2016 I get the error 2006 on MS 365 I don't get anything.

## Your Environment

* Platform: PC
* Host: Outlook
* Office version number: MS 365 (Version 2306 Build 16.0.16529.20164), Outlook 2016, outlook.office365.com
* Operating System: Windows 11
* Browser: MsEdge
 
## Expected behavior
I expect the header to be added successfully.

## Current behavior
The header is not added.

## Steps to reproduce
1. get the example below
2. click button "run"
3. adding of header will fail.

## Link to live example(s)
https://gist.github.com/Arikael/b88dd54074988f0b9a64e46fdcf7d913

## Context
I try to add a complex/long header with folding which adheres to RFC 5322

**EDIT**
Added outlook.office365.com as another version

**Comment by Arikael** [comment]
just an observation (maybe it helps where to look or not)
Doing it from a VSTO Addon works without any issue, so Outlook itself seems capable to do that

**Comment by exextoc** [comment]
@Arikael  Can you share details on the scenario where you need header longer than 998 characters? As a workaround can you set different headers each being maximum of 998 characters?

**Comment by Arikael** [comment]
We need to add labels according to [RFC 7444](https://www.rfc-editor.org/rfc/rfc7444.html)
And while this is not an  Internet Standards Track specification, RFC 5322 (2.2.3) is.

I don't think using multiple headers would work, because then it would be different headers instead of one folded one.
And the receivers (outside of our company and influence which use the same principle) would be unable to correctly read it because they expect everything in one header.

**Comment by exextoc** [comment]
@Arikael Currently the feature to add internet header with folding, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by Equinox89x** [comment]
I am in the same boat. For a company project I'm required to apply folding to one of my headers, but this is currently not possible because of the limitation in the API.
