### ISSUE TITLE
[Outlook] Outlook desktop is unable to get attachment content, if email was created by Right click -> Send to -> Mail recipient

### ISSUE THREAD

**Issue by Suntechnick** [OfficeDev/office-js#3547]
We are developing the on-send addin which gets mailbox attachments content via `getAttachmentContentAsync` API. This works as expected in every case except for Outlook desktop if the email was created via selecting the file in file system -> right click -> send to -> mail recipient.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft Outlook for Microsoft 365 MSO (Version 2306 Build 16.0.16529.20164) 64-bit
* Operating System: Windows
* Browser (if using Office on the web): -
 
## Expected behavior
Should be able to get attachment content

## Current behavior
Getting attachment content fails with an error
![getAttachmentContentasync](https://github.com/OfficeDev/office-js/assets/30172623/b6b50e14-8a41-45d5-90ea-bb04f0ab7999)

## Steps to reproduce
On-send addin is required.
1. Have Outlook Desktop open and running in the background
2. In file system, select a file -> right click -> send to -> mail recipient
3. New Outlook email is created, fill the required email data and press "Send"
4. While addin is processing the on-send event, try to get attachment content via `getAttachmentContentAsync` API

## Context
It is worth to mention that this issue does not always happen. I was able to reproduce it on my machine in the past (that's when I took a screenshot which is attached to this ticket in "current behavior" section), but now everything works fine for me. Still, some people from my team consistently facing this issue.

**Comment by ztcdsb** [comment]
@Suntechnick Can you let us know the impact of this issue and the version of Outlook that people on your team that still able to consistently repro it?
I would suggest to upgrade Outlook to the latest version and see if the issue still persist.

**Comment by Suntechnick** [comment]
We rechecked this issue on our end and confirm that the issue does not replicate anymore.
Thank you.
