### ISSUE TITLE
Event based add-in - OnAppointmentSend not triggering handler in Outlook windows

### ISSUE THREAD

**Issue by iamjanit** [OfficeDev/office-js#3549]
We are trying to use event based activation feature for our outlook add-in , using the OnAppointmentSend event works perfectly in Outlook OWA but nothing happens in Outlook for windows
# Provide required information needed to triage your issue

Environment Details:
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Microsoft® Outlook® for Microsoft 365 MSO (Version 2306 Build 16.0.16529.20164) 64-bit
* Office version number: 
* Operating System: Windows 11 Pro (10.0.22621 Build 22621)
* Browser (if using Office on the web): None
 
## Expected behavior
Clicking on appointment's send button should trigger the event handler registered for onAppointmentSend event type in the launchevent.js file.

## Current behavior
Add-in is stuck on the pop-up stating that the add-in is taking longer than expected with spinner spinning and eventually gets timed out with the same pop up saying the same.

## Steps to reproduce
1. Create a new appointment in outlook for windows
2. Add an attendee
3. Click on send button 

# Additional details
We are using Outlook add-in created via Visual studio template, and it uses jquery for add-in logic and views. The same add-in works perfectly in Outlook OWA and even works if we switch outlook for windows into preview mode (Try the new outlook).The launchevent.js file: 
![image](https://github.com/OfficeDev/office-js/assets/111116573/b76c1bbb-b441-41fb-a8f2-ff1355364615)

## Useful logs
![image](https://github.com/OfficeDev/office-js/assets/111116573/24a98785-85b7-4f9c-bc34-ec062fa01b34)
![image](https://github.com/OfficeDev/office-js/assets/111116573/5a57e17b-a92f-408c-9d9d-95224f0d62df)

**Comment by iamjanit** [comment]
Also to mention, if we switch outlook native to the preview mode that is switch on the "Try the new outlook button", then in there these events work just fine.

**Comment by anurag-jaiswal-eptura** [comment]
@exextoc Could you please share any update/timeline for fixing this bug ?

**Comment by janit-eptura** [comment]
@exextoc any update on this ?

**Comment by anurag-jaiswal-eptura** [comment]
@exextoc  Could you help to know tentative date for fix of this issue or any progress on it?

**Comment by ndeleuze** [comment]
@iamjanit Thank you for reaching out with this issue.

When sending the appointment, do you see the "appointment sent" log output, or is the onAppointmentSendHandler not reached at all?

For additional information on the Smart Alerts feature, please see this documentation: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest

**Comment by janit-eptura** [comment]
Hi @ndeleuze, the onAppointmentSendHandler is never reached and no logs are displayed in the console either.

**Comment by ndeleuze** [comment]
@janit-eptura thank you for your response. Can you confirm that the JavaScript file containing the event handlers is correctly referenced within the manifest? (In the <Runtimes> element for XML manifest or "code" object for unified manifest (preview).

I'm also wondering if the launch events were working before or if you have been trying to get them to work from the beginning?

Here is a link to more documentation for the prerequisites to enable launch events in your add-in: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest#check-manifest-and-javascript-requirements

**Comment by janit-eptura** [comment]
@ndeleuze the launch events work perfectly on outlook OWA and the same manifest works perfectly fine if I switch the outlook native(outlook for windows) to the preview mode , but it just doesn't work in the regular non preview mode of the outlook native.

**Comment by ndeleuze** [comment]
@janit-eptura the new preview version of Outlook runs the same experience as OWA from a native Windows shell, so "new" Outlook and OWA should behave the same. Did your launch event add-in work with the "old" version of Outlook and is now not working?

Here is some more documentation on developing add-ins for the new Outlook experience: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/one-outlook#supported-scenarios-in-outlook-web-add-ins
