### ISSUE TITLE
How do I open a document from a template in SharePoint through Word JavaScript in a task pane?

### ISSUE THREAD

**Issue by edgarmaus** [OfficeDev/office-js#3550]
I am trying to open a SharePoint template as a document through a Word task pane using Word JavaScript. I am able to access the "webUrl" property of the file through the site's drive item collection. I need to convert this url into an object and convert it into a base64 string to pass to "context.application.createDocument(base64Document)" method. I am able to create the base64 string and open a document when using the HTMLInputElement "file" object. Searches refer to the "file" object as a type of Blob but this doesn't help in getting an equivalent object from the url. How do I correctly call SharePoint through the Graph API, get a drive item, and open the template as a file through JavaScript in the task pane.

**Comment by ZYUN-MSFT** [comment]
Hi @edgarmaus ,

Thanks for reaching us. In my understanding, what you are trying to do is _Open a exist document through Word JS API_.\
But unfortunatly, this feature is not supported by now. 

We would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform for asking a new feature. Feature requests on it are considered when we go through our planning process.

Thanks.

**Comment by edgarmaus** [comment]
Yun,

            Thanks for the quick response. I am trying to open a new document through a template stored in SharePoint. For example, selecting New in backstage allows me to pick a template on which to base a new document. I want to do the same thing in Word JavaScript with a SharePoint template.

Ed Maus
Software Developer, BEC Legal Systems<http://www.beclegal.com/>
E ***@***.******@***.***>  O 513.948.1500  W beclegal.com<http://beclegal.com/>

***@***.***<https://www.beclegal.com/bec-event/iltacon-2023/>

BEC Legal Software Product Overview<https://www.beclegal.com/video/bec-legal-software-product-overview/>

**Comment by ZYUN-MSFT** [comment]
Hi @edgarmaus,

Thanks for the confirming. Word JS API doesn't support your scenario for now, please feel free to ask new feature at https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform.

Thanks for your support of Office Addins.

> Refer to https://github.com/OfficeDev/office-js/issues/3512
