### ISSUE TITLE
[Outlook] getAttachmentContentAsync does not yield an error if network connection was disabled

### ISSUE THREAD

**Issue by Suntechnick** [OfficeDev/office-js#3553]
`getAttachmentContentAsync` does not yield an error if network connection was disabled

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
If network connection was disabled during the `getAttachmentContentAsync` call, it should yield an error as a result

## Current behavior
If network connection was disabled during the `getAttachmentContentAsync` call, it hangs without yielding anything

## Steps to reproduce
1. Call the `getAttachmentContentAsync` from Outlook addin
2. Disable network connection during the call above (e.g., by using the Chrome devtools)

## Context
Since the call stays unresolved, we are unable to properly handle this error which impacts our product's UX

**Comment by exextoc** [comment]
Currently behaviour of the API is not defined in this scenario. We track Outlook add-in feature requests on our  [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process. 

As a workaround you can try to add a timeout on the Add-in side and show the error accordingly.
