### ISSUE TITLE
RichApi.Error: There was an internal error while processing the request

### ISSUE THREAD

**Issue by ShivIfour** [OfficeDev/office-js#3554]
I have developed an Excel Javascript plugin using the React framework.

The add-in workflow is simple.

Request data from Ui using APIs Passing entities' column names and authorized API keys Start writing data into an active Excel sheet by pulling the button.

Steps to reproduce

Open the Excel file
Select the criteria for pulling data
Open another Excel file
Again Select the criteria for pulling data
Pull the data at a time with a button click.
Problem : The table got printed only in one Excel sheet only. In another Excel sheet, I got the below error.

**RichApi.Error: There was an internal error while processing the request. at new n (excel-win32-16.01.js:25:259407) at i.processRequestExecutorResponseMessage (excel-win32-16.01.js:25:323853) at excel-win32-16.01.js:25:321916**

I had tried below code:

````
try {
    var i = 0;
    // these data are coming from APIs
    var allCompanies = [12, 32, 33, 43, 45, 66, 12, 32, 10, 12, 21, 90];
    allCompanies.forEach(async _company => {
      // calling APIs for each _docs and writing data for that companies
      await fetchData(_company).then(async (responseRows) => {
        await Excel.run(async (context) => {
          let sheet = context.workbook.worksheets.getActiveWorksheet();
          sheet.load(["name"]);
          await context.sync();
          for (let i = 0; i < responseRows.length; i++) {
            // data operations into Exel sheet
            // creating table, table header, applying Css
            // writting value to each cells
          }
          sheet.getUsedRange().format.autofitColumns();
          sheet.getUsedRange().format.autofitRows();
          await context.sync();
        });
      });
    });
  } catch (error) {
    console.log("error on appending data into excel " + error);
  }
````

Can anyone guide me on this issue?

**Comment by ghost** [comment]
Thank you for letting us know about this issue. We will take a look shortly. Thanks.

**Comment by ZYUN-MSFT** [comment]
Hi @ShivIfour ,

Thanks for reaching us.
We'd want to know that, do you use Win32 or Excel Online?

And if possible, please share more detail repro steps and the minimal repro code with ScriptLab:
![image](https://github.com/OfficeDev/office-js/assets/122421505/cc2813bc-c2f8-4c98-aa55-937812345662)
This would be helpful for us to locate the issue.

Thanks.
