### ISSUE TITLE
Network request failed when fetching from event based add-ins in Outlook Desktop

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js#3557]
Environment: Outlook Desktop version 2303/2304, Windows 10

For one specific customer, we are seeing very strange behavior. _It is very important to notice that it works as expected for all the others, so issues in the manifest, or the js bundle file should not be taken into account._
For the first 24 hours of usage, the fetch requests made from the automatic events are not working. The request is made against a public Shared Access Signature, so CORS should not play a role in it. The fetch response is "Network request failed", while fiddler doesn't register any request.
During this whole time, requests made from the Taskpane are working as supposed. 

I'm not sure if this is a bug in Office.js, an issue within the code, or an environment limitation/problem. At this point, with the troubleshooting limitations of the event-based add-ins, I don't want to exclude anything. Do you have any ideas about what could happen or how to get more information?

**Comment by TLeiter** [comment]
@bogdanst24 we have the exact same issue, did you find a way to fix it ?

**Comment by bogdanst24** [comment]
It was caused by their internal configuration. They were running a proxy that was not automatically registering the allowed URLs for the first 24 hours, or until a manual restart of the service
