### ISSUE TITLE
Compatibility of Word Add-ins with iPad Word App

### ISSUE THREAD

**Issue by SAgnihotri200895** [OfficeDev/office-js#3559]
##  Compatibility of Word Add-ins with iPad Word App
I have been testing Word add-ins on an iPad (iOS 16.6) using the latest Word app from the Apple Store (version 2.75). However, the add-ins do not appear to be showing up as expected.

According to the [Office JS Word API 1.1 documentation](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/word/word-api-requirement-sets?view=word-js-preview#requirement-set-availability), it requires a minimum version of 1.18 for Office apps. With the latest version available on the Apple Store being 2.75, it seems plausible that the add-ins may not be compatible with newer releases, potentially causing them not to appear on the iPad.

Is there something I might be overlooking in terms of configuration or compatibility? Could there be any known issues with Word add-ins and the iPad Word app?

Any feedback, clarifications, or suggestions to make Word add-ins work seamlessly with the iPad Word app would be highly appreciated.

**Attached is my manifest just for reference(IDs , webapp URLs intentionally changed or removed)**
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp
	xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
	xmlns:ov="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="TaskPaneApp">
	<Id>GUID</Id>
	<Version>1.0.0.0</Version>
	<ProviderName>Contotose</ProviderName>
	<DefaultLocale>en-US</DefaultLocale>
	<DisplayName DefaultValue="Testing"/>
	<Description DefaultValue="Testing purpose"/>
	<IconUrl DefaultValue="https://.azuaturewebsites.net/assets/icon-32.png"/>
	<HighResolutionIconUrl DefaultValue=".azurewebsites.net/assets/icon-64.png"/>
	<SupportUrl DefaultValue=".azurewebsites.net/help"/>
	<AppDomains>
		<AppDomain>.azurewebsites.net</AppDomain>
	</AppDomains>
	<Hosts>
		<Host Name="Document"/>
		
	</Hosts>
	<Requirements>
		<Sets DefaultMinVersion="1.1">
			<Set Name="SharedRuntime" MinVersion="1.1"/>
		</Sets>
	</Requirements>
	<DefaultSettings>
		<SourceLocation DefaultValue=".azurewebsites.net/taskpane.html"/>
	</DefaultSettings>
	<Permissions>ReadWriteDocument</Permissions>
	<VersionOverrides
		xmlns="http://schemas.microsoft.com/office/taskpaneappversionoverrides" xsi:type="VersionOverridesV1_0">
		<Hosts>
			<Host xsi:type="Document">
				<Runtimes>
					<Runtime resid="Taskpane.Url" lifetime="long" />
				</Runtimes>
				<DesktopFormFactor>
					<GetStarted>
						<Title resid="Contoso.GetStarted.Title"/>
						<Description resid="Contoso.GetStarted.Description"/>
						<LearnMoreUrl resid="Contoso.GetStarted.LearnMoreUrl"/>
					</GetStarted>
					<FunctionFile resid="Taskpane.Url"/>
					<ExtensionPoint xsi:type="PrimaryCommandSurface">
						<OfficeTab id="TabHome">
							<Group id="Contoso.Group1">
								<!-- Label for your group. resid must point to a ShortString resource. -->
								<Label resid="Contoso.Group1Label" />
								<!-- Icons. Required sizes 16,32,80, optional 20, 24, 40, 48, 64. Strongly recommended to provide all sizes for great UX. -->
								<!-- Use PNG icons. All URLs on the resources section must use HTTPS. -->
								<Icon>
									<bt:Image size="16" resid="Contoso.tpicon_16x16" />
									<bt:Image size="32" resid="Contoso.tpicon_32x32" />
									<bt:Image size="80" resid="Contoso.tpicon_80x80" />
								</Icon>
								<Control xsi:type="Button" id="TaskpaneButton">
									<Label resid="TaskpaneButton.Label"/>
									<Supertip>
										<Title resid="TaskpaneButton.Label"/>
										<Description resid="TaskpaneButton.Tooltip"/>
									</Supertip>
									<Icon>
										<bt:Image size="16" resid="Contoso.tpicon_16x16" />
										<bt:Image size="32" resid="Contoso.tpicon_32x32" />
										<bt:Image size="80" resid="Contoso.tpicon_80x80" />
									</Icon>
									<Action xsi:type="ShowTaskpane">
										<TaskpaneId>Office.AutoShowTaskpaneWithDocument</TaskpaneId>
										<SourceLocation resid="Taskpane.Url"/>
									</Action>
								</Control>
								<Control xsi:type="Menu" id="Contoso.Menu">
									<Label resid="Contoso.Menu.Label" />
									<Supertip>
										<Title resid="Contoso.Menu.Label" />
										<Description resid="Contoso.Menu.Tooltip" />
									</Supertip>
									<Icon>
										<bt:Image size="16" resid="Contoso.tpicon_16x16" />
										<bt:Image size="32" resid="Contoso.tpicon_32x32" />
										<bt:Image size="80" resid="Contoso.tpicon_80x80" />
									</Icon>
									<Items>
										<Item id="Test1">
											<Label resid="Contoso.Item1.Label"/>
											<Supertip>
												<Title resid="Contoso.Item1.Label" />
												<Description resid="Contoso.Item1.Tooltip" />
											</Supertip>
											<Icon>
												<bt:Image size="16" resid="Contoso.tpicon_16x16" />
												<bt:Image size="32" resid="Contoso.tpicon_32x32" />
												<bt:Image size="80" resid="Contoso.tpicon_80x80" />
											</Icon>
											<!-- <Action xsi:type="ShowTaskpane"><TaskpaneId>ButtonId1</TaskpaneId><SourceLocation resid="Contoso.Taskpane.Url" /></Action> -->
											<Action xsi:type="ExecuteFunction">
												<FunctionName>writeValue</FunctionName>
											</Action>
										</Item>
										<Item id="Test2">
											<Label resid="Contoso.Item2.Label"/>
											<Supertip>
												<Title resid="Contoso.Item2.Label" />
												<Description resid="Contoso.Item3.Tooltip" />
											</Supertip>
											<Icon>
												<bt:Image size="16" resid="Contoso.tpicon_16x16" />
												<bt:Image size="32" resid="Contoso.tpicon_32x32" />
												<bt:Image size="80" resid="Contoso.tpicon_80x80" />
											</Icon>
											
											<Action xsi:type="ExecuteFunction">
												<FunctionName>writeValue</FunctionName>
											</Action>
										</Item>
										<Supertip><Title resid="Contoso.Item8.Label" /><Description resid="Contoso.Item8.Tooltip" /></Supertip><Icon><bt:Image size="16" resid="Contoso.tpicon_16x16" /><bt:Image size="32" resid="Contoso.tpicon_32x32" /><bt:Image size="80" resid="Contoso.tpicon_80x80" /></Icon><Action xsi:type="ExecuteFunction"><FunctionName>writeValue</FunctionName></Action></Item> -->
									</Items>
								</Control>
							</Group>
						</OfficeTab>
					</ExtensionPoint>
				</DesktopFormFactor>
			</Host>
		</Hosts>
		<Resources>
			<bt:Images>
				<bt:Image id="Contoso.tpicon_16x16" DefaultValue=".azurewebsites.net/assets/icon-16.png" />				<bt:Image id="Contoso.tpicon_32x32" DefaultValue=".azurewebsites.net/assets/icon-32.png" />
				<bt:Image id="Contoso.tpicon_80x80" DefaultValue=".azurewebsites.net/assets/icon-80.png" />
			</bt:Images>
			<bt:Urls>
				<bt:Url id="Commands.Url" DefaultValue=".azurewebsites.net/commands.html" />
				<bt:Url id="Taskpane.Url" DefaultValue=".azurewebsites.net/taskpane.html" />
				<bt:Url id="Contoso.GetStarted.LearnMoreUrl" DefaultValue="https://go.microsoft.com/fwlink/?LinkId=276812" />
			</bt:Urls>
			<bt:ShortStrings>
				<bt:String id="TaskpaneButton.Label" DefaultValue="Insert Testing" />
				<bt:String id="Contoso.WriteValueButton.Label" DefaultValue="Show task pane" />
				<bt:String id="Contoso.Item1.Label" DefaultValue="Test1" />
				<bt:String id="Contoso.Item2.Label" DefaultValue="Test2" />
				
				
				<bt:String id="Contoso.Menu.Label" DefaultValue=" Testing" />
				<bt:String id="Contoso.Group1Label" DefaultValue="Testing" />
				<bt:String id="Contoso.GetStarted.Title" DefaultValue="Get started with your sample add-in!" />
			</bt:ShortStrings>
			<bt:LongStrings>
				<bt:String id="TaskpaneButton.Tooltip" DefaultValue="Choose to  insert" />
				<bt:String id="Contoso.Item1.Tooltip" DefaultValue="Choose to show template" />
				<bt:String id="Contoso.Item2.Tooltip" DefaultValue="Choose to show template" />
				
						<bt:String id="Contoso.Menu.Tooltip" DefaultValue="Show the dropdown menu" />
				<bt:String id="Contoso.WriteValueButton.Tooltip" DefaultValue="Choose to write value to document" />
				<bt:String id="Contoso.GetStarted.Description" DefaultValue="Your sample add-in loaded succesfully. Go to the HOME tab and choose the 'Show task pane' button to get started." />
			</bt:LongStrings>
		</Resources>
		<WebApplicationInfo>
			<Id></Id>
			<Resource></Resource>
			<Scopes>
				<Scope>profile</Scope>
				<Scope>openid</Scope>
			</Scopes>
		</WebApplicationInfo>
	</VersionOverrides>
</OfficeApp>

```

**Comment by jipyua** [comment]
hi, thanks for reaching out. Would you please confirm have your addin submitted to the store and may I know your addin name?

**Comment by SAgnihotri200895** [comment]
@jipyua  its centrally deployed in our tenant through Mircrosoft365 Admin center . Also, we don't see any options available in iPad' word app to insert add -in from office store as well.

**Comment by jipyua** [comment]
If it's a store addin and working fine on iPad, then it can be shown in the iPad addin store. please try to use the following way to insert addins on iPad from store.
![image](https://github.com/OfficeDev/office-js/assets/22437953/dd1c355d-3c03-4fac-ac95-4ea9a45873cf)

**Comment by SAgnihotri200895** [comment]
@jipyua , We are deploying our add-in in the organization [using Microsoft's admin center and integrated apps](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide#deploy-an-office-add-in-using-the-admin-center). Could you confirm if its mandatory that add-ins need to be published to the Office Store for them to be usable on iPad devices.

**Comment by SAgnihotri200895** [comment]
> @jipyua , We are deploying our add-in in the organization [using Microsoft's admin center and integrated apps](https://learn.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide#deploy-an-office-add-in-using-the-admin-center). Could you confirm if its mandatory that add-ins need to be published to the Office Store for them to be usable on iPad devices.

@jipyua  can you please confirm  if its mandatory that add-ins need to be published to the Office Store for them to be usable on iPad devices.

**Comment by jipyua** [comment]
@SAgnihotri200895 for now central deployment is not supported on iOS Word, I am afraid you need to publish it to store in order to be used by your users.

**Comment by SAgnihotri200895** [comment]
> @SAgnihotri200895 for now central deployment is not supported on iOS Word, I am afraid you need to publish it to store in order to be used by your users.

Thanks for the confirmation, I will raise another issue, to get this updated in article so that people can make informed decision.

**Comment by sbolofsson** [comment]
Hi @jipyua, @AlexJerabek, can you please confirm which Office applications on **iPad** support deployment through Microsoft Admin Center > Integrated Apps?

Based on our experiments, it seems that:
* Outlook: Supported
* Word: Not supported
* Excel: Not supported
* PowerPoint: Not supported

Please, can you:
1) Confirm if this is correct?
2) Link to the relevant documentation?

@AlexJerabek, I am sorry to say, but the updates you made to the documentation in this PR: https://github.com/OfficeDev/office-js-docs-pr/pull/4137/files , which are published here: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/office-versions-and-requirement-sets#deployment , are super vague: 
* "_How your add-in is deployed can affect your add-in's availability on the various platforms and clients._" ...

It's basically just another way of saying:
* "_How you deploy may or may not work"_

If deploying through Integrated Apps are not supported in all Office applications on all platforms, then please outline it clearly somewhere?

**Comment by sbolofsson** [comment]
@jipyua , @AlexJerabek , is it basically this article which says that deployment is not supported on iPad?

https://learn.microsoft.com/en-us/microsoft-365/admin/manage/office-addins?view=o365-worldwide#office-requirements

Quote:

> For Word, Excel, and PowerPoint add-ins, your users must be using one of the following versions:
> 
> * On a Windows device, Version 1704 or later of Microsoft 365 Business licenses (Business Basic, Business Standard, Business Premium), Office 365 Enterprise licenses (E1/E3/E5/F3), or Microsoft 365 Enterprise licenses (E3/E5/F3).
> * On a Mac, Version 15.34 or later.
> 
> For Outlook, your users must be using one of the following versions:
> * Version 1701 or later of Microsoft 365 Business licenses (Business Basic, Business Standard, Business Premium), Office 365 Enterprise licenses (E1/E3/E5/F3), or Microsoft 365 Enterprise licenses (E3/E5/F3).
> * Version 1808 or later of Office Professional Plus 2019 or Office Standard 2019.
> * Version 16.0.4494.1000 or later of Office Professional Plus 2016 (MSI) or Office Standard 2016 (MSI).
> * Version 15.0.4937.1000 or later of Office Professional Plus 2013 (MSI) or Office Standard 2013 (MSI).
> * Version 16.0.9318.1000 or later of Office 2016 for Mac.
> * Version 2.75.0 or later of Outlook mobile for iOS.
> * Version 2.2.145 or later of Outlook mobile for Android.

It is a bit unclear that Outlook on iPad should support deployment through Integrated Apps based on the quoted text. But based on our testing it seems to be the case.

**Comment by AlexJerabek** [comment]
Hi @sbolofsson,

Thanks for the question. 

As your internal testing concludes, Outlook add-ins are supported by Integrated App deployment on iPad. The iOS line in the quoted text includes iPads. For a more detailed breakdown of device support, see [Client requirements: Browser support for Office web clients and SharePoint](https://learn.microsoft.com/office/dev/add-ins/concepts/requirements-for-running-office-add-ins#client-requirements-non-windows-smartphone-and-tablet). We'll take the note to make the iPad support more obvious (cc @samantharamon).

> It's basically just another way of saying:
> - "How you deploy may or may not work" 

I realize the text in that section is vague. The page that's quoted from is broadly applicable to all Office Add-ins. Unfortunately, publishing depends on the Office application, the type of deployment, the Office version (and whether it's volume-licensed), the platform, and the manifest type. I appreciate your frustration and would welcome any suggestions you have to better organize the information (in particular, where and when you would expect to find specific details).

**Comment by sbolofsson** [comment]
So just to be entirely clear. Deployment to Word, PowerPoint and Excel on iPad is not supported through Integrated Apps?

If that is true, then I would very much appreciate that to be added explicitly to this section: https://learn.microsoft.com/en-us/microsoft-365/admin/manage/office-addins?view=o365-worldwide#office-requirements

For example something like this:

![Image](https://github.com/user-attachments/assets/1515d51f-b339-4e23-9237-3414c70a0052)

**Comment by AlexJerabek** [comment]
> So just to be entirely clear. Deployment to Word, PowerPoint and Excel on iPad is not supported through Integrated Apps?

Yes, that is what the current documentation says. I will verify internally in case that functionality has been added without updating the docs.

**Comment by AlexJerabek** [comment]
Hi @sbolofsson,

I have confirmed internally that that integrated apps for Excel, Word, and PowerPoint are not supported on the iPad. I'll update the page you linked to make that clearer.

Please let us know if you have further questions or issues.
