### ISSUE TITLE
RichApi.Error: The requested resource doesn't exist.

### ISSUE THREAD

**Issue by joerg-sap** [OfficeDev/office-js#3560]
# Provide required information needed to triage your issue
We have an issue in productive addin and can reproduce it in script lab addin.
Retrieving style alignment properties / loading styles results in an richapi.error with the requested resource doesn't exist

## Your Environment
Windows Microsoft® Excel® for Microsoft 365 MSO (Version 2302 Build 16.0.16130.20586) 32-bit 
 
## Expected behavior
retrieving style alignment properties

## Current behavior
rich api error is shown

## Steps to reproduce
1. use scribtlab addin
2. try to get style alignment properties

![Screenshot 2023-08-02 113530](https://github.com/OfficeDev/office-js/assets/141227104/ddd8a77c-a534-4044-afa2-960e855b4986)

**Comment by joerg-sap** [comment]
for our productive case we are trying to load     const styles = context.workbook.styles;
    styles.load('items/name');
    await context.sync(); 
    and get the same error

**Comment by ZYUN-MSFT** [comment]
Hi @joerg-sap ,

Thanks for reaching us. Please provide the repro code by share a gist in ScriptLab, which would be helpful for us to locate the issue:

![image](https://github.com/OfficeDev/office-js/assets/122421505/3fe2ca5e-ee51-4a61-ae0f-d831091bd5be)


Thanks.

**Comment by joerg-sap** [comment]
i used exactly your coding https://gist.github.com/joerg-sap/74b4e9c624308b66e8795c3c2b66c84b

**Comment by joerg-sap** [comment]
<img width="571" alt="image" src="https://github.com/OfficeDev/office-js/assets/141227104/270d5044-f61d-482f-bd89-d71e7c1c82a3">
thats the result

**Comment by ZYUN-MSFT** [comment]
Hi @joerg-sap , are you using the 32bit Win32 Version Excel?

**Comment by joerg-sap** [comment]
Hi @ZYUN-MSFT 
yes exactly i switched to it cause our customer is on it.
You can find the version in my first message

**Comment by ZYUN-MSFT** [comment]
Hi @joerg-sap ,

We try the version Build 16.0.16130.20586 of 32bits but we still can repro the error.\
Could you please check the activation status or change the excel host and have a try?

Thanks.

**Comment by joerg-sap** [comment]
Hi @ZYUN-MSFT,
with activation status you mean if my excel has a valid software key/ the software is activated?
And with changing the excel host you want me to try it on another pc?

Best Regards
Joerg

**Comment by ZYUN-MSFT** [comment]
Hi @joerg-sap ,

Yes, please check the software is activated or not. And you can try the same excel version on another PC to test if the issue is there too.

Thanks.

**Comment by ZYUN-MSFT** [comment]
Hi @joerg-sap ,

Does this issue happens on another PC with the same Excel version? This information may help us to locate the issue.

Thanks.

**Comment by joerg-sap** [comment]
@ZYUN-MSFT if i use the workbook from the other pc yes

**Comment by ZYUN-MSFT** [comment]
> @ZYUN-MSFT if i use the workbook from the other pc yes

Hi @joerg-sap , Really sorry that I don't understand this. 

Are you means that using a Excel file from other machine but run script on the previous issued machine?

---

Since we can't repro the issue with the 16.0.16130.20586 32 bits Excel. If it is possible, could you please use another machine (not the machine which occur the issue) and install the same Excel Version to veify?

Thanks.

**Comment by joerg-sap** [comment]
Hi @ZYUN-MSFT im using the workbook from the issued machine and opened it on another machine 
Best Regards
Joerg

**Comment by ZYUN-MSFT** [comment]
Hi @joerg-sap ,

Thanks for the confirm. Could you please share the issued Excel File with us for investigation?
If it's not suitable to share here, my working E-Mail is zyun@microsoft.com

Thanks.

**Comment by ZYUN-MSFT** [comment]
Hi @joerg-sap ,

An internal BUG 8209811 is created for tracking this issue. We will back to this thread if we got updated.

Thanks.

**Comment by ZYUN-MSFT** [comment]
Hi @joerg-sap ,

Our engineer team have triaged this issue. For this issue, we can only repro by the Excel file you provided, but we can not repro on any other excel files. If you can provided the steps of how to re-create the repro file, that would be helpful a lot.

We'd also like to know that what's the business impact of this issue in your scenario. With this information we can re-priority our workitem.

And you can try the workaound of getItem steps by steps:
```
let styles = context.workbook.styles;
let style = styles.getItemAt(0);
style.load("name");
await context.sync();
console.log(style.name);
```

And last, thanks for your support of Office Addin.

**Comment by joerg-sap** [comment]
Hi @ZYUN-MSFT ,

our customer gets that issue every time he creates a new workbook.
The business case is that he can’t use our addin as it seems like his workbook never has an excel context.

Best Regards
Joerg
