### ISSUE TITLE
Using the `customXmlPart.setXml` method causes an Insert, Load & Delete event to fire

### ISSUE THREAD

**Issue by mburbea** [OfficeDev/office-js#3564]

**Comment by ZYUN-MSFT** [comment]
Hi @mburbea , thanks for reaching us.

We are still investigating this issue. And we will back here once we got update.

Thanks.

**Comment by ZYUN-MSFT** [comment]
Hi @mburbea ,

For the `setXml` api, it will actually create a new XML part and delete the old XML part to complete the `set` process. So the `setXml` triggerd `load` `add` `delete` three events is the expected behavior.

We'd want to know that do you have any workaround for your working scenario?

Thanks.

**Comment by mburbea** [comment]
I currently just have a LoadXML and save a const guid for the xmlns, and send all messages from officeJS with that xmlns.
```vb
    const m_ns As String = "03020100-0504-0706-0809-0a0b0c0d0e0f"
    Private Sub parts_PartAfterLoad(ByVal part As Office.CustomXMLPart)
        If (part.NamespaceURI = m_ns) Then
              Dim root as  CustomXMLNode: root = part.DocumentElement
              Select Case root.BaseName
                    Case "SomeMsg"
                            HandleSomeMsg   root
                    Case "OtherMsg"
                            HandleOtherMsg root
              End Select
        End If
    End Sub
```
That said, on the officeJS side, I can keep using the same `CustomXmlPart` id over and over agian. It seems that the old part gets deleted, and the inserted part changes it's ID to that of the old one.

**Comment by donlvMSFT** [comment]
Hi @mburbea ,

Actually the insert->delete happens inner officeJS API execution, so from PROD perspective, the CustomXmlPart Id won't be same at any point.

So you use the Load event for this id won't hurt anything, is only `_PartAfterLoad` event fit your scenario?
