### ISSUE TITLE
context.sync() taking progressively more time to run

### ISSUE THREAD

**Issue by adarshsosale** [OfficeDev/office-js#3565]
Context sync is taking progressively more time on each execution when content controls are added to a document

## Your Environment
* Platform : MacOS
* Host: MS Word
* Office version number: Microsoft Word for Mac 16.75 (23070901)
* Operating System: MacOS Ventura
 
 I have a Word taskpane plugin generated using yeoman generator (React and JS).  I'm trying to add content controls with unique UIDs to every paragraph (so that the server knows which paragraph needs to be edited) and this is my code.
 
 
        useEffect(() => {
          const startTime = new Date(); // Capture start time
        
          Word.run(async (context) => {
            console.log("getParagraphs function");
        
            const paragraphs = context.document.body.paragraphs;
            paragraphs.load('items');
      
            await context.sync();
      
            for (let p = 0; p < paragraphs.items.length; p++) {
              paragraphs.items[p].load(["text", "contentControls"]);
            }
        
            await context.sync();
        
            const BATCH_SIZE = 10; // Adjust this number based on your testing
      
            for (let p = 0; p < paragraphs.items.length; p += BATCH_SIZE) {
              for (let i = p; i < Math.min(p + BATCH_SIZE, paragraphs.items.length); i++) {
                const paragraph = paragraphs.items[i];
                const paragraphUid = `{%uid-${i}}`;
      
                if (hasContentControlWithUid(paragraph, paragraphUid)) {
                  continue;
                }
                if (paragraph.text.trim() !== "") {
                  const range = paragraph.getRange("Whole");
                  const contentControl = range.insertContentControl();
                  console.log("INSERT CONTENT CONTROL NOW")
                  contentControl.tag = paragraphUid;
                  contentControl.cannotEdit = false;
                  contentControl.appearance = "Hidden";
                }
              }
              // IMPORTANT: Call sync immediately to commit the changes.
              await context.sync();
            }
        
            // Load the HTML of all paragraphs, then sync.
            console.log("loadDocumentContent function");
            let content = "";
            const htmlRequests = [];
            const uids = [];
        
            for (let p = 0; p < paragraphs.items.length; p++) {
              const paragraph = paragraphs.items[p];
              const paragraphUid = `{%uid-${p}}`;
        
              if (paragraph.text.trim() !== "") {
                const range = paragraph.getRange("Whole");
                const htmlRequest = range.getHtml();
                htmlRequests.push(htmlRequest);
                uids.push(paragraphUid); // Storing UIDs for later use
              }
            }
        
            const contentSyncStart = new Date();
            await context.sync();  // This content sync takes more and more time on every execution
            const contentSyncEnd = new Date();
            console.log("Execution Time for CONTENT SYNC: ", contentSyncEnd - contentSyncStart, "ms"); 
        
            const forLoopStart = new Date();
            for (let i = 0; i < htmlRequests.length; i++) {
              const paragraphHtml = htmlRequests[i].value;
              content += `${uids[i]}${paragraphHtml}`; // Using stored UIDs
            }      
            const forLoopEnd = new Date();
            console.log("Execution Time for FOR LOOP: ", forLoopEnd - forLoopStart, "ms");
        
            console.log("CONTENT", content);
            const endTime = new Date(); // Capture start time
            console.log("Execution Time: ", endTime - startTime, "ms");
            const url = `${process.env.BASE_PATH}/api/v1/get_document`;
            const payload = {
              document_body: content,
            };
            const response = await axios.post(url, payload);
            addTextToContentControls()
            setReviewSuggestions(response.data);
            setIsLoading(false);
          });
        }, []);
        
        const hasContentControlWithUid = (paragraph, uid) => {
          const contentControls = paragraph.contentControls;
        
          for (let c = 0; c < contentControls.items.length; c++) {
            if (contentControls.items[c].tag === uid) {
              return true;
            }
          }
          return false;
        };
 
So the issue is this snippet takes 6-10 seconds for a document with 85 paragraphs on the first run. On subsequent runs, it keeps increasing with NO modifications to the document - I have verified to ensure that no duplicate content controls are added. After a few runs, the run time for the context.sync() goes into minutes even! This could possibly point to a memory leak in the office code.

What I've tried so far, to no avail- 
1. Reloading the app
2. Quitting and restarting Word completely takes the execution time back to the original 5-7 seconds
3. I'm on the latest office.js version so no need to update
4. Tried it on several different documents of varying lengths. The execution time always keeps increasing!
5. Tried various batch sizes and also without batching, issue persists
6. Giving it almost an hour between subsequent executions. I'm quite sure that I'm not running into rate limits since the volume of the paragraphs are quite low

**Comment by adarshsosale** [comment]
I tried running the taskpane plugin on Windows and it works fine. This issue happens only on Word for MacOS.

**Comment by ZYUN-MSFT** [comment]
Hi @adarshsosale ,

We are still investigating this issue. And we will back here once we got update.

Thanks.

**Comment by JHJ-MS** [comment]
Hi @adarshsosale ,
I tried it on Mac, it seems the most time-consuming operation is the API call `const htmlRequest = range.getHtml();`

If you delete the two line 
```
 const htmlRequest = range.getHtml();
 htmlRequests.push(htmlRequest);
```
and the following lines using the htmlRequest, will the issue go away? 

However, The time cost on my side is around 8S to 10S, (about 30 CCs, tried 20 times), I didn't see a big time cost increase on my Mac after re-click.

Would you please take try to replace the following code line
`const htmlRequest = range.getHtml();`
with the following code 
```
range.load("text");
await context.sync();
const htmlRequest = range.text;
```
and re-run some times, will the issue go away？ If it will. Is this possible to be a workaround for you addin'?

**Comment by adarshsosale** [comment]
Yes, this fix reduced the load times quite significantly! However, it produces far simpler HTML without the font information! Is there any recommended way to separately perform a 1 time operation to get the font styles to be applied globally? If there is, then this approach is suitable for my needs. Thank you!

**Comment by JHJ-MS** [comment]
We can use font.bold/font.color/... to get font styles [Word.Font](https://learn.microsoft.com/en-us/javascript/api/word/word.font?view=word-js-preview)  . We can get font objects from the body/paragraph/range obj. 

for your case, maybe you can add the following code lines and the range indicates each paragraph's range.
```
{
const fontBold = range.font.bold;
const fontColor = range.font.color;
...
}
```

The only thing is , if I remember it clearly, if the range contains mixed font color/bold,,,, (e.g some fonts in the range are red, some fonts in the range are yellow), then it will return a mixed enum or something like it. Then you can not get the exact font color.
