### ISSUE TITLE
How to identify the right support for event-based Outlook Desktop add-ins

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js#3569]
Environment: Outlook Web Add-ins, Outlook for Windows
Context: event-based add-ins

**Context and problem**
Recently, in the javascript runtime for the event-based add-in in Outlook, I have changed the usage of Promise.All to Promise.AllSettled. All tests were working and for the other 3 production environments where we tested everything was alright. After releasing it to all, we immediately found out it was not working for many of the customers, and the cause was " [TypeError: Object doesn't support property or method 'allSettled']". The code is written in Typescript and transpiled to js (correctly).

According to the different online sources (documentation), the JS file for the Outlook desktop is running in the native rendering engine (browser emulator). Promise.allSettled comes with ECMAScript 2020, which should be available on the WebView2 runtimes (newer ones at least).

Either way, looking at different customers with the same user agent detected (Edg/115.0.1901.188), for some it worked, and for some, it didn't. And the Outlook version also doesn't seem to be relevant (all at least 2304). Recent Windows build versions.

**Question**
What is exactly the environment in which the JS file is running and how can we identify exactly the version, features, and limitations? What could make it not support features such as Promise.AllSettled?

Also, as I understand, NodeJS is only involved when debugging an add-in.

Please correct me if I understood anything wrong. Ideally, we could be able to check all dependencies in code, and if not, at least to know exactly what to look at.

**Comment by avisheknand** [comment]
Hello @bogdanst24 , please note that it is recommended for Event based addins to limit your js code to ECMAScript 2016 . The Windows Desktop Outlook js runtime supports till ECMAScript 2016 . Please see here: [EventBased JS and Runtimes](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest#check-manifest-and-javascript-requirements)

**Comment by bogdanst24** [comment]
Thank you, I can see that, but why ECMAScript 2020 is supported in some environments and not in others when Office and Edge versions seem to be identical? I'm trying to figure out exactly all the dependencies I have to look for so that I know (e.g.) how to properly test anything.

**Comment by zhngx1** [comment]
Thank you for your post @bogdanst24. Please be aware that the JavaScript code of event-based add-ins that run in Outlook on Windows only supports [ECMAScript 2016](https://262.ecma-international.org/7.0/). There are other variables (other than Office and Edge versions) that will affect the support of ECMAScript 2020 so you will sometimes see it working. But we only officially support ECMAScript 2016.

**Comment by bogdanst24** [comment]
Thank you for the reply @zhngx1! The limitation around the ECMAScript 2016 is clear. **It is exactly about those variables I am asking about.**  And that is because, in 5 different environments, we were not able to make it not work. I need to know what exactly I have to disable or downgrade. Without having an environment with the specifications meeting the exact minimum requirements, we can't trust our testing. ECMAScript 2016 might be one thing, but similar to this there might be others, and testing for days and then hearing from customers it doesn't work on their computers is not a way to go.

**Comment by zhngx1** [comment]
For Outlook event-based add-ins we use a special JavaScript runtime and we only support up to ECMAScript 2016. For more information, you can read here: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtimes

If you find anything that we officially support that works for you but not your customers, please create an issue for us and we will take a look at it.
