### ISSUE TITLE
context.sync hangs

### ISSUE THREAD

**Issue by seho-dev** [OfficeDev/office-js#3571]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by seho-dev** [comment]
![image](https://github.com/OfficeDev/office-js/assets/35763284/ffd01a72-0216-4903-a534-7fc98f97f586)

**Comment by seho-dev** [comment]
The kernel is ie11, and when context.sync is called, the code hangs indefinitely, causing subsequent logic not to execute

**Comment by seho-dev** [comment]
![image](https://github.com/OfficeDev/office-js/assets/35763284/68ec9b5b-996b-4498-92df-6ffc5edd07ff)

**Comment by seho-dev** [comment]
It's worth noting that I'm using office 2016 enhanced, which is bulk activated and registered, and on top of the windows 10 platform, using a word document that is simple enough to have even a few lines of text;

None of my tests on other machines reproduced the issue, neither mac nor office 365

**Comment by JHJ-MS** [comment]
Would you please try adding a `return` before the `context.sync().then()`
