### ISSUE TITLE
 Office.context.ui

### ISSUE THREAD

**Issue by Ratneshkushwaha** [OfficeDev/office-js#3572]
# Office.initialize time not getting Office.context.ui method
## Outlook Web
Office.initialize time not getting Office.context.ui method
* Platform [PC desktop, Mac, iOS, Office on the web]
* Host [Excel, Word, PowerPoint,Outlook etc.]
* Office version number:Web
* Operating System: Win 10
* Browser (if using Office on the web):Chrome
 
## Expected behavior
I want open Outlook Dialog 

## Current behavior
 Office.initialize time not getting Office.context.ui method
Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
We are not able to reproduce this issue on our side. Could you please provide following details?

-  Is this issue occurring only on Outlook Web and does it work on other Platforms / other browsers / OS version?
-  Please share the code snippet with which issue can be reproduced
