### ISSUE TITLE
Office.context without mailbox attribute in some SharedMailboxes

### ISSUE THREAD

**Issue by johannesrutkies** [OfficeDev/office-js#3575]
# Provide required information needed to triage your issue
We have a customer on Microsoft 365 having multiple SharedMailboxes. 
In some of these SharedMailboxes Office.context consistently has no mailbox attribute while in other SharedMailboxes with equal configuration the mailbox attribute is correctly filled. This only affects the Outlook client and the mailbox attribute is correctly filled in Outlook on the web.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.16501.20272
* Operating System: Windows 10
* Browser (if using Office on the web): ------
 
## Expected behavior

Office.context.mailbox contains the mailbox

## Current behavior

Office.context.mailbox is undefined

## Steps to reproduce

Not reproducible on our side

## Useful logs

![image](https://github.com/OfficeDev/office-js/assets/59468981/e06ff94d-f3b4-4349-be1f-15d17c267e33)

**Comment by exextoc** [comment]
@johannesrutkies, I have contacted you offline (as DebraB) to setup a debugging session. Once we understand what is going on, we can circle back to this post with our findings. Thanks.

**Comment by benjaminyasoon** [comment]
Hi there, 
we received an email from DebraB. I did respond. However, not sure if you received it.

Unfortunately, we can’t reproduce this on our site but it is affecting one of our customers.

We are located in Germany and maybe it would be best if we meet up around 5 p.m./5:30 p.m. together with our customer, that would be for your timezone 8:00 a.m. or 8:30. A.m. Wich days would fit you best to meet up next week? Maybe you can offer a couple of days. I would afterwards check if our customer has time on these timeslots.

We would be happy to hear back from you!

Best regards,
Benjamin

**Comment by exextoc** [comment]
@benjaminyasoon, thanks for responding to the email.
I just responded to the email. I'm available for a debugging session any day next week.
Feel free to send me an appointment. Thanks.

**Comment by benjaminyasoon** [comment]
@exextoc just send you over an invite to Debra for next Thursday 24th. Would be happy if you could confirm the invite :)

**Comment by benjaminyasoon** [comment]
@exextoc Hi there, could you please confirm the invite or receiving of the email invitation and the Teams Call for Thursday 24th at 8:00 a.m.?

**Comment by exextoc** [comment]
@benjaminyasoon, I haven't received an invitation for a Teams call for Thursday 24th at 8:00am PST in my Inbox. I just checked the DebraB account again. However, I'm available on Thursday 24th at 8:00am PST so I will look out for a post from you or a meeting request in the DebraB account.

Just for clarification, DebraB does not have Teams access, so please share the meeting details over email and I will connect as a guest. Sorry for not clarifying that earlier.

**Comment by benjaminyasoon** [comment]
@exextoc Hi there,
we are waiting on the call, could you join us via the teams meetings link I send you via email?

**Comment by exextoc** [comment]
Hmm...I don't have any email from you, so that's why I haven't joined the call. Can you just share it here?

**Comment by benjaminyasoon** [comment]
@exextoc Could you use this link please to join?

https://teams.microsoft.com/l/meetup-join/19:meeting_ZjU1MDVmOWEtZGY4YS00OWY5LWE3ZjYtNTM2NTJlYjBkOTBj@thread.v2/0?context=%7B%22Tid%22:%220e7219f7-4c4d-47e7-b98a-7b9b9de02b80%22,%22Oid%22:%22a654439a-fe39-48bb-9cc1-a2809f689974%22%7D

**Comment by exextoc** [comment]
Let me connect now.

**Comment by kwame-ansong** [comment]
Had an offline connection with the customer.
This appears to be a one-off situation that has not been reproduced.
@johannesrutkies closing this for now, however, if this re-appears in other Shared Mailboxes, please let us know.
Thanks.

**Comment by exextoc** [comment]
Had an offline connection with the customer.
This appears to be a one-off situation that has not been reproduced.
@johannesrutkies, closing this for now, however, if this re-appears in other Shared Mailboxes, please let us know.
Thanks.
