### ISSUE TITLE
AddFileAttachmentFromBase64Async hangs indefinitely on Outlook Online

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js#3576]
Environment: Outlook Online (any), both Standard and Targeted release channels.
Browser: Any
 
When triggered from the `OnNewMessageCompose` event, the AddFileAttachmentFromBase64Async  function does never resolve. It is hanging forever, there is no callback from the function, and no error is thrown. This only happens when more than one attachment is resolved in a Promise.All and it can only be reproduced on new messages. The same function when triggered by `OnMessageRecipientsChanged` works. 
A short message "File cannot be attached. Please try later" is displayed for a very short time.

This stopped working suddenly. In the console there are only error messages related to `eu-office.events.data...` and XHR failed to load many times -> probably unrelated.
e.g.:
```
POST https://eu-office.events.data.microsoft.com/OneCollector/1.0/?cors=true&content-type=application/x-json-stream&w=0 net::ERR_CONNECTION_TIMED_OUT
```
_____

I don't know how to mimic the event-based actions on Script Lab. This is how the code would look like (simplified a lot):

```
Office.actions.associate( 'onMessageCompose' (event: Office.AddinCommands.Event) => void onMessageComposeHandler(event));

function onMessageComposeHandler (event) {
  return doStuff().catch(...).finally(....);
}

function doStuff() {
   ........
   await Promise.all(
        inlineAttachments.map((attachment) => addInlineAttachment(attachment))
    );
   .......
}

function addInlineAttachment({
  name,
  base64Content,
}: Base64EncodedResource) {
  return new Promise<string>((resolve, reject) => {
    const { mailbox } = Office.context;
    const mailItem = mailbox.item;
    if (!mailItem) {
      reject(new Error('Unable to add inline attachment: No mailbox item'));
      return;
    }

    mailItem.body.getAsync(Office.CoercionType.Html, (bodyResult) => {
      if (bodyResult.status !== Office.AsyncResultStatus.Succeeded) {
        reject(
          new Error('Unable to add inline attachment: Body not available')
        );
      }

      const options = { isInline: true, asyncContext: bodyResult.value };
      mailItem.addFileAttachmentFromBase64Async(
        base64Content,
        name,
        options,
       (callback) => {
           // NOTE: at this point, starting with the second attachment, there is no callback.
           ....
           resolve(callback.value);
           ....
       }
      );
    });
  });
}

```

Running the entire code twice seems to solve the issue. The result for the first promise is always pending, while the second one fulfilled
```
function onMessageComposeHandler (event) {
  const r1 = doStuff().catch(...).finally(....);
  const r2 = doStuff().catch(...).finally(....);
  
  console.log("FIRST RESULT:", r1);
  console.log("SECOND RESULT:", r1);
}

```

![image](https://github.com/OfficeDev/office-js/assets/65173226/21868518-7728-445b-9acd-77a2c18bc12f)

**Comment by barclayadam** [comment]
We have been investigating this too as we have seen it with our customers. At first, it looked like it may have been specific to some images but we now have 2 confirmed cases of problems adding attachments as base64 in OWA.

With permission, I have grabbed a problematic set of images from a customer and created a reproduction at https://outlook.signature365.com/owaimageembedfailmanifest.xml

That add-in has 2 embedded images. It tries to add both of them but 1 always fails:

![image](https://github.com/OfficeDev/office-js/assets/973909/ab7c0cda-71c2-4d4d-9f19-f13d7fbba90d)

We have verified this fails in `Microsoft Edge v115.0.1901.200` and `Google Chrome 115.0.5790.170`

I attempted to perform some debugging of this issue but found that if I added a breakpoint to stop execution before images are embedded, they **will** be successfully inserted, suggesting a race condition is potentially happening.

**Comment by barclayadam** [comment]
In addition we *very* briefly see an error message pop up in the info bar area above the email that reads roughly:

"Files could be not attached. Please try again later"

**Comment by exextoc** [comment]
Hi @bogdanst24 , @barclayadam 
Thanks for reporting this issue regarding attachments. It has been put on our backlog. We unfortunately have no timelines to share at this point
 
Internal tracking id: Office: 3848932

**Comment by exextoc** [comment]
We have fixed the bug, and the issue is available on all the builds in Outlook Web.

**Comment by bogdanst24** [comment]
Thank you, I can confirm the fix
