### ISSUE TITLE
After the custom meeting Location is removed，reentry，Custom locations still exist

### ISSUE THREAD

**Issue by supermanklk** [OfficeDev/office-js#3578]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac OS(new version - 版本16.75.2 (23072301))
* Host [Excel, Word, PowerPoint, etc.]:  Outlook

 
## Expected behavior
After the custom meeting Location is removed, the meeting enters the meeting again, and the custom location does not appear

再次进入
## Current behavior

Add a custom meeting location, and then remove the custom meeting location. At this moment, the interface is displayed normally, save it. When you enter the meeting again, the custom meeting location still exists

ps：To trigger the condition, edit the status, you must have previously set up a valid meeting room，As shown below
<img width="964" alt="image" src="https://github.com/OfficeDev/office-js/assets/28639384/e0798928-504b-4f5d-9db2-358bc5f7ba7b">

## Steps to reproduce
1、Get current Meeting room Location  = Office.context.mailbox.item.enhancedLocation.getAsync((result) => {console.log(result)})

log:  Obtained a conference room location

<img width="409" alt="image" src="https://github.com/OfficeDev/office-js/assets/28639384/dd93d990-ce68-436f-a002-cfa845a24c92">

2、Add a custom meeting location 
3、Remove the custom meeting location
4、Get current Meeting room Location  = Office.context.mailbox.item.enhancedLocation.getAsync((result) => {console.log(result)}) Result：The result is the same as what was returned in the first step
5、Save（Send）
6、Edit the meeting again and go to Discover that the custom location still exists

<img width="747" alt="image" src="https://github.com/OfficeDev/office-js/assets/28639384/4902aab6-0764-4ac6-af72-9d6de74a5ed2">

This issue is similar to office-js/issues/3338，Did it cause a new defect?

**Comment by exextoc** [comment]
@supermanklk  Are you performing Step 2 and 3 using Add-in API or manually from the Outlook UI ?

**Comment by supermanklk** [comment]
> @supermanklk Are you performing Step 2 and 3 using Add-in API or manually from the Outlook UI ?

Add-in APl

**Comment by exextoc** [comment]
@supermanklk  Thanks for confirming. 
We are able to repro this issue. We are currently working on the fix and this thread will be updated once the fix is available.

**Comment by supermanklk** [comment]
> We are able to repro this issue. We are currently working on the fix and this thread will be updated once the fix is available.

I am very sorry to hear that. When is it expected to be repaired and put online?

**Comment by exextoc** [comment]
Hi @supermanklk , the fix should be available in the next Insiders Beta Channel release(16.77.23081601+). Or if you are not on Insiders then you can wait for the Outlook September Release(16.77.*) for the fix to be available. You can use these steps to enroll in Insiders - https://insider.microsoft365.com/en-in/join/Mac
