### ISSUE TITLE
Addin is not loading in compose mode of the new outlook in Windows

### ISSUE THREAD

**Issue by somenathmaji** [OfficeDev/office-js#3579]
# Addin is not loading in compose mode of the new outlook in Windows

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2307 Build 16.0.16626.20170
* Operating System: Windows 11 Pro 22H2 (22621.2134)
* Browser (if using Office on the web): N/A
 
## Expected behavior

The Addin should load without any issues.

## Current behavior

The Addin doesn't load at all.
## Steps to reproduce

1. Switch to new outlook in windows
2. Compose a message in a popup window
3. Open the addin
4. The addin doesn't load

## Link to live example(s)

1. [Video and screenshots](https://celigodev-my.sharepoint.com/:f:/g/personal/somenath_cloudextend_dev/EtAvF8ZbryRNvBWBzbZgejoBMCaSvD343qRSZ9xDYSjlfQ?e=Ehhh4h)

# Provide additional details

1. It can be reproducible using scriptlab for outlook's run taskpane
2. You have to use the compose mode in a popup window

## Context

This is critical to our customers as they use compose mode a lot. For now we have asked them to switch back to old outlook app.

**Comment by somenathmaji** [comment]
Any updates on this?

**Comment by exextoc** [comment]
Hi @somenathmaji , we tried reproducing this on our end with new outlook but are unable to do so. Could you share the version of the new Outlook UI? You can get that by going to Help->Diagnostics in the new UI.

**Comment by somenathmaji** [comment]
This is the version of new outlook UI -
![Screenshot 2023-08-17 at 10 40 50 AM](https://github.com/OfficeDev/office-js/assets/10449421/3ab357b8-9799-4d96-aca6-0a3926991b3a)

**Comment by somenathmaji** [comment]
Any update on this?

**Comment by exextoc** [comment]
Hi @somenathmaji , 
Thanks for reporting this issue. This took some time to repro because it happens only for a few add-ins.
It has been put on our backlog. We unfortunately have no timelines to share at this point
 
Internal tracking id: Office: 3859828

Could you also send your manifest on outlookextensibility@m365x27035562.onmicrosoft.com so that we can debug this on 2 add-ins (Script lab and your add-in)

**Comment by somenathmaji** [comment]
@exextoc You can install the addin from the app source. The addin name is `CloudExtend Outlook for NetSuite`

**Comment by exextoc** [comment]
This issue is fixed, and the fix will be available in build 20231016071 or later. Please verify and let us know if you are still facing the issue.
