### ISSUE TITLE
Word Add-In: BindingSelectionChanged event does not gets called after binding value is updated 

### ISSUE THREAD

**Issue by zakhan4** [OfficeDev/office-js#358]
I'm working on Office JS Word Add-in with React and TypeScript. I created bindings and attach event handlers of BindingSelectionChanged and BindingDataChanged to it from Task Pane. And the callback functions are called just fine whenever the binding value is updated or selected.

Then I had a use case where I needed to update the binding values when clicking on the button from the menu bar. So I created a function in the Function-file where I fetched the bindings and updated it's values and it worked fine. But after having the binding values updated from the function file the callback function for BindingSelectionChanged event stopped getting called in the Task Pane, however the callback function for BindingDataChanged still works fine.

## Expected Behavior
For BindingSelectionChanged event handler to still get called on the selection of the binding value in Word as long as the Task Pane is open, even after the binding value is updated from outside the Task Pane Code.

## Current Behavior
On the selection of the binding value in Word, event handler for BindingSelectionChanged is not triggered after that binding value is changed from outside the Task Pane Code

## Steps to Reproduce, or Live Example
[Github Repo Example Link](https://github.com/zakhan4/test_addin)

After cloning and installing dependencies from the above link, and starting the project, follow these steps to reproduce the error:
  1. Click on 'Show Taskpane' button in Home Tab form Word Ribbon
  2. Click on 'Run' button from Task Pane. This will create a binding with Id '1'
  3. You can click on the created binding value in word, and you will see 'Binding Selected' msg inside Taskpane. Also you can update the binding value manually and you will be able to see 'Binding Value Updated' msg now inside TaskPane.
  4. Now click on 'Update Binding Value' from the home tab, while the TaskPane is still open. This will update our previously created binding with id '1', and you will see 'Binding Value Updated' msg in TaskPane, but now if you select the binding value, you will not see 'Binding Selected' msg, and this is our problem.

## Context
Trying to update all binded values in a document by clicking on the 'Refresh' button from the Menu Bar

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office 365 Windows Desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 1811 (Build 11029.20079)
* Operating System: Windows 10
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by zakhan4** [comment]
It would be great to have an update on this please, or if you have any questions regarding the issue. Thanks!

**Comment by JuaneloJuanelo** [comment]
@zakhan4  please provide a script lab snippet with a repro and we can investigate faster. thanks!

**Comment by zakhan4** [comment]
@JuaneloJuanelo since the error happens when I update binding values after clicking on the button on the Word Ribbon, I don't think I will be able to reproduce the same error using Script Lab, since there is no way to configure the Function File in Script Lab, or is there?

**Comment by zakhan4** [comment]
@JuaneloJuanelo I have created a github repo to reproduce the error I'm getting. Here is the link to the repo: https://github.com/zakhan4/test_addin. I have used yoeman generator to generate this project.

I have also updated the steps to reproduce in the original question. Please have a look and let me know if you have any questions!

**Comment by JuaneloJuanelo** [comment]
ok sorry for the tremendous delay. i have a repro.. we are investigating what's going on....

**Comment by JuaneloJuanelo** [comment]
after further investigation, we can confirm this is a bug.
we are tracking with 3438730 internally. 
Thanks @zakhan4  for reporting this! hopefully we can fix it soon. 
Assigning to @tutieu to follow up.

**Comment by grangeryy** [comment]
This bug is fixed so close it.
