### ISSUE TITLE
EXCEL: NamedItem losts it's reference after copying source workbook into current workbook via insertWorksheetsFromBase64

### ISSUE THREAD

**Issue by doantumai** [OfficeDev/office-js#3583]
### Current Behavior:
After loading template.xlsx file to current workbook via insertWorksheetsFromBase64:

```
const startIndex = sheetsString?.indexOf("base64,");
const externalWorkbook: string = sheetsString ? sheetsString.substring(startIndex ? startIndex + 7 : 7) : "";
const workbook = context.workbook;

workbook.insertWorksheetsFromBase64(externalWorkbook);
```

the namedItem from the source workbook is not correctly referenced. Excel returns it's formula as so **=#REF!$[Location]** (see pictures below). After that I try to load another workbook. The namedItem from the old workbook is still accessible in this new workbook

![Screenshot 2023-08-15 at 09 30 13](https://github.com/OfficeDev/office-js/assets/80953718/e24cf6bc-8858-4602-880a-b87153965b0d)

### Expected Behavior

- Excel recognizes the reference defined in the template.xlsx file and returns **=Table1!$[Location]** in the formula (see pictures below).
- namedItem should only be accessible/visible for that current workbook. After loading a new workbook, the namedItem should not be loaded. 

![Screenshot 2023-08-15 at 09 30 00](https://github.com/OfficeDev/office-js/assets/80953718/6d06f695-6015-4569-aacc-a82cffe66d1a)

### Environment
Platform [PC desktop, Mac, iOS, Office Online]: Mac desktop
Host [Excel, Word, PowerPoint, etc.]: Excel
Office version number: Excel for Mac version 16.75.2 (23071901)
Operating System: MacOS
Browser (if using Office Online): N/A

**Comment by doantumai** [comment]
@ZYUN-MSFT @donlvMSFT Hi guys, any updates on this issue?

**Comment by donlvMSFT** [comment]
Hi @doantumai ,

Thanks for reporting and sorry for the late reply, I tried on my Mac environment, but couldn't reproduce the issue.
![MicrosoftTeams-image (2)](https://github.com/OfficeDev/office-js/assets/42738188/49855be3-ed85-4ec6-8d78-01169ed5bfc4)

Could you share if any special contents in the inserted document? If you could share any repro steps, that would help us a lot.

Thanks,

**Comment by doantumai** [comment]
Hi @donlvMSFT Thank you so much for your reply. 

There is no special content in my inserted template. The namedItem is **sometimes** shown correctly. 

![Screenshot 2023-08-29 at 09 42 10](https://github.com/OfficeDev/office-js/assets/80953718/55f2ce47-05d0-4499-9574-4c511481596c)

In the picture above, you can see my add in. I have 2 "services" on the right side: My Team and Auto Update. 
If I start the add in and open Auto Update on the first time, the reference in the B2 cell from the template get recognized and is shown correctly in the 'Name Manager'. The namedItem has the scope 'Workbook'.

![Screenshot 2023-08-29 at 09 50 09](https://github.com/OfficeDev/office-js/assets/80953718/7a18c4a1-2638-4481-a50f-b01cb56d136d)

If I then open My Team service, that means the myteam.xlsx template will be loaded to current workbook via insertWorksheetsFromBase64. Before inserting, all the old sheets in the Auto Update service will be deleted. The namedItem is still to be found and it losts its reference.

![Screenshot 2023-08-29 at 09 54 23](https://github.com/OfficeDev/office-js/assets/80953718/83b2e6ce-14cc-43c2-8036-51d7175367e2)

The namedItem is still to be found in this service, maybe because it's still the same workbook. After that I open the Auto Update service again and still get #REF. I expect the reference to be loaded again.
I guess that was because of the workbook scope, the sheet got deleted so there is no reference to be found. But this problem does not occur in my C# Excel version. I tested that with the same backend, same templates and everything works fine.

Do you have any ideas on this issue? I'm expecting the reference to be loaded/ recognized correctly after reopening the service/ reloading the template.xlsx. (changing the template is the last solution that we want to use. My team prefers to have frontend changes rather than backend).

Many thanks

**Comment by doantumai** [comment]
@donlvMSFT I manage to solve this problem. Before copying new workbook into currentWorkbook, I need to delete the namedItem with '#REF' in its formula. And then after loading new workbook, namedItem's visible should be set to true. 

Thank you so much
