### ISSUE TITLE
Word: Missing API for setting style tab stops.

### ISSUE THREAD

**Issue by adomasven** [OfficeDev/office-js#3585]
With the COM addin API it is possible to set paragraph tab stops for a style. There is no equivalent JS API.

**Comment by YijunMS** [comment]
@adomasven Thanks for reaching us. 

For new feature request, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.

**Comment by adomasven** [comment]
Thanks, I'll submit a request there.

EDIT: For anyone looking in the future [here is the link to the Idea](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/word-js-paragraphformat-add-a-tabstops-api/idi-p/3901770)

**Comment by pki89** [comment]
if I am not mistake, this has not (yet) been resolved.
any way to back the OPs feature request?

does anyone know of a workaround?

**Comment by eaallen** [comment]
Still does **not** look like tab stops are supported
