### ISSUE TITLE
Inconsistency: dialog appears mac desktop, doesn't appear in office for web

### ISSUE THREAD

**Issue by justmars** [OfficeDev/office-js#3586]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac, office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.75
* Operating System: Mac
* Browser (if using Office on the web): Edge
 
## Expected behavior

Using same manifest.xml file with a server running on `https://localhost:8000`, sideloading it manually into both Mac and office on the web should display the dialog. If a popup-blocker is present in the browser for office on the web, prevents the dialog from appearing, the user should first click on `allow` for the dialog window to appear.

When using the following code on Mac, the dialog appears with the contents of `<targetUrl>`:

```js
 Office.onReady((info) => {
    if (info.host === Office.HostType.Word) {
      Office.context.ui.displayDialogAsync(
        <targetUrl>,
        { height: 50, width: 30 }, // size of the dialog box
        function (asyncResult) {
          console.log(JSON.stringify(asyncResult));
          if (asyncResult.status === Office.AsyncResultStatus.Failed) {
            console.log(
              (asyncResult.error.code = ": " + asyncResult.error.message)
            );
         } else {
         console.log("Display dialog separate window")
         }
     }
     ...
```

## Current behavior

In contrast, when using office on the web, what happens is the following

1. The button that should reveal the dialog is clicked.

<img width="318" alt="Screenshot 2023-08-15 at 7 36 11 PM" src="https://github.com/OfficeDev/office-js/assets/39538958/e39e38b1-b5f4-4d0a-8bce-40764cb6dcc8">

2. The button contains an event listener that the runs the same function above re: `Office.context.ui.displayDialogAsync`. On clicking, this blurred image of the window appears:

<img width="327" alt="Screenshot 2023-08-15 at 7 40 29 PM" src="https://github.com/OfficeDev/office-js/assets/39538958/7653d556-e007-4fab-b044-4075b8936a1d">

3. The image itself seems already problematic. But on clicking on the Allow button, the following lines appear in the console per the function above:

```console
{"value":{},"status":"succeeded"}
Display dialog separate window
```

4. No dialog appears. What occurs (based on the image) is that the dialog prompt done within the taskpane hence the blurred image.

I tried searching the issues and it seems related to #3356 and #2979. It suffers from the same missing `value` of the `AsyncResult` object described in #1246.

**Comment by YijunMS** [comment]
@justmars Thanks for reaching us.

For office on the web, I tried to reproduce this issue in Script Lab. https://gist.github.com/YijunMS/c73f86e3caea6ab4af3616c30c565a86

The behavior looks right from my side:
![image](https://github.com/OfficeDev/office-js/assets/112541209/8807bdaf-283c-4667-bd5c-9b5890467853)
![image](https://github.com/OfficeDev/office-js/assets/112541209/27cab600-609a-4c12-9a97-4121c5f44eda)

I think you could try to start a local server and host your dialog html there. Then use the example above to see if Script Lab can load it correctly.

**Comment by justmars** [comment]
Hi @YijunMS , thank you for taking the time to replicate. 

I've tried side-loading a "Scriptlab based" add-in with the following steps:

1. I run the local server at `https://localhost:8000`
2. I update the manifest file to reflect this state

```xml
  <AppDomains>
    <AppDomain>https://localhost:8000</AppDomain>
  </AppDomains>
```
3. I visit office.com, create a new doc, upload the _manifest.xml_
4. I ensure ScriptLab is installed as an add-on and run the script to open the prospective url (with the same domain as `AppDomain`), `https://localhost:8000/account/login` :

<img width="495" alt="Screenshot 2023-08-18 at 11 18 07 AM" src="https://github.com/OfficeDev/office-js/assets/39538958/3c08ce49-51cf-4698-b160-2a5140c19033">

5. When I run the script, I now get an error claiming that the domains are different. This is markedly different from the example I previously described where I was getting a _succeeded_ status.

<img width="459" alt="Screenshot 2023-08-18 at 11 19 21 AM" src="https://github.com/OfficeDev/office-js/assets/39538958/78ce18a1-5b02-4553-b8b5-2e9f4cbab8e5">

6. Curiously, if I follow your example and change the prospective url from localhost:`8000`/account/login to localhost:`3000`/account/login, this results:

<img width="362" alt="Screenshot 2023-08-18 at 11 24 12 AM" src="https://github.com/OfficeDev/office-js/assets/39538958/e9c053bf-9f75-4830-95d9-de0b671491e9">
<img width="472" alt="Screenshot 2023-08-18 at 11 24 50 AM" src="https://github.com/OfficeDev/office-js/assets/39538958/7d6f0eaa-7387-477e-833b-e7bb3fed7edc">
<img width="1125" alt="Screenshot 2023-08-18 at 11 25 16 AM" src="https://github.com/OfficeDev/office-js/assets/39538958/f6a5919b-4164-4696-b155-3869cbdd864e">

I'm not running anything on port 3000 per `lsof -i tcp:3000` and the manifest's AppDomain is limited to the port 8000.

**Comment by justmars** [comment]
The scriptlab-based solution however still doesn't replicate the problem whereby a `localhost:8000` manifest is uploaded as an add-in and then when a dialog is invoked, a brief (empty) window appears but vanishes immediately without showing an error message, and the value of the AsyncResult is empty.

**Comment by YijunMS** [comment]
@justmars Based on those behaviors, I think it is good to check if your add-in can load a very simple HTML page (like a "Hello Word"). Then we can see if this problem has relation to your environment, or it is related to the page you are going to load.

**Comment by justmars** [comment]
Will do @YijunMS .

As an experiment, I tried running the server at `localhost:3000`. 

It seems to me like Script Lab only works with this local port. 

I updated the `manifest.xml` for the Word application in MacOS to reflect the new `localhost:3000`.

On side-loading in _MacOS Word_, the html file was able to load properly. The following GET request is sent and processed:

`GET /accounts/login/?_host_Info=Word$Mac$16.01$en-US$telemetry$isDialog$$0 HTTP/1.1" 200`

Notably the _MacOS Word_ invocation uses the same dialog method in Script Lab (_Office for Web_):

```js
async function run() {
  Office.context.ui.displayDialogAsync(
        "https://localhost:3000/accounts/login",
        { height: 50, width: 30 },
        function (asyncResult) {
          console.log(JSON.stringify(asyncResult));
          if (asyncResult.status === Office.AsyncResultStatus.Failed) {
            console.log(
              (asyncResult.error.code = ": " + asyncResult.error.message)
            );
          } else {
            console.log("Display dialog separate window")
          }
        }
      )
    }
```

The result is the error described re: disappearing dialog:

![scriptlab](https://github.com/OfficeDev/office-js/assets/39538958/58d18e33-0eb3-4e6d-ad24-74d995ada24b)

**Comment by YijunMS** [comment]
@justmars I forgot to mention that my Word Online runs on Edge browser on Windows 11, not sure if this would make a difference. Have you tried this scenario in a different browser or OS?

For your last example, is the login page a simple html file or your original file?

**Comment by justmars** [comment]
@YijunMS I just tried a simple html page (Edge Browser on MacOS Ventura)

```html
<!-- test.html -->
<html>
<h1>hello world</h1>
<h2>this is a test</h2>
</html>
```

I'm using a Django application to serve the resources:

```py
# views.py
class TestPage(TemplateView):
    template_name = "pages/test.html"
```

```py
# urls.py
app_name = "pages"
urlpatterns: list[URLPattern] = [
    path("test", TestPage.as_view(), name="test"),
]
```

In the `taskpane.html` file, I have the following script tag:
```js
<script>
    async function openDialog(result) {
      console.log(JSON.stringify(result));
      if (result.status === Office.AsyncResultStatus.Succeeded) {
        const dialog = result.value;
        dialog.addEventHandler(
          Office.EventType.DialogMessageReceived,
          (arg) => {
            dialog.close();
            if (arg.message === "true") {
              window.location.replace(`{% url 'test:success' %}`); // redirect taskpane
            }
          }
        );
      }
    }
    document.getElementById("taskpane-start").addEventListener("click", () => {
      const url = `{{request.scheme}}://{{request.get_host}}{% url 'pages:test' %}`
      Office.context.ui.displayDialogAsync(url, { height: 50, width: 30 }, openDialog);
    })
  </script>
```

In MacOS Word, I get the expected dialog:

<img width="901" alt="Screenshot 2023-08-18 at 4 41 00 PM" src="https://github.com/OfficeDev/office-js/assets/39538958/9ef01a69-6824-4a89-91cb-dac4c8a2a4f0">

Using this same setup in script lab (the url will evaluate to `localhost:3000/test`), I also get the expected dialog:

<img width="1035" alt="Screenshot 2023-08-18 at 4 47 14 PM" src="https://github.com/OfficeDev/office-js/assets/39538958/7497fd45-a3e4-4501-b336-2408b1547380">

So it appears that the contents of the html file that is loaded into the dialog matters. May I know if this is a documented issue and what restraints there are on the resources that ought to be loaded in the dialog?

**Comment by justmars** [comment]
I've tried a simpler `about.html` page which contains jinja template variables like so

```jinja
{% extends "base.html" %}

{% block content %}
  <h1>About</h1>
  <article>
    Hello there!
    <footer>
      <a href="{% url 'pages:contact' %}">Say Hi</a>
    </footer>
  </article>
{% endblock content %}
```

And the result is the same error described in https://github.com/OfficeDev/office-js/issues/3586#issuecomment-1683557634

**Comment by YijunMS** [comment]
@justmars Glad to find the cause.

I tried to find some documents about this API (https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-best-practices), however, you might already read it before.

My colleague will find the owners and experts of dialog API and transfer this issue to them. They would be able to take a deeper look into this issue.

**Comment by justmars** [comment]
Thank you for helping isolate where the problem emanates @YijunMS. And yes I've gone through the documentation, thank you.

Since the code works on MacOS but doesn't on Office for Web, I'd very much appreciate an explanation as to the inconsistency in effect.

**Comment by justmars** [comment]
> @justmars Glad to find the cause.
> 
> I tried to find some documents about this API (https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-best-practices), however, you might already read it before.
> 
> My colleague will find the owners and experts of dialog API and transfer this issue to them. They would be able to take a deeper look into this issue.

Hello @YijunMS , have the experts of the dialog API gone through the issue?

**Comment by justmars** [comment]
Some further updates on the issue:

1. Sometimes able to load the dialog only under a single working condition. The loaded dialog URL `Office.context.ui.displayDialogAsync("https://localhost:3000/accounts/login"...)` **cannot** contain a reference to the `<script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js" type="text/javascript"></script>` (_otherwise the dialog opens and closes immediately_). However sometimes the url appears in another tab rather than in the dialog. I have a suspicion this has to do with `<AppDomains>` in the manifest.
2. Assuming the dialog appears, this enables me to show the login screen and even handle oAuth2 on the non-iframe dialog popup. It looks like this:

    <img width="875" alt="Screenshot 2023-09-13 at 2 24 00 PM" src="https://github.com/OfficeDev/office-js/assets/39538958/2e0f390e-dfa3-49d6-b877-c980b3e7a854">
3. However, on log-in / redirect, I need to communicate back with the parent taskpane and thus need the reference OfficeJS script. Assuming the following html in the dialog url, `Office.onReady` fails:
    ```html
    <html>
      <head>
        <script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
      </head>
      <h1>hello world</h1>
    </html>
    <script>
      Office.onReady().then(() => Office.context.ui.messageParent("true"))
    </script>
    ```
4. I get a `Uncaught Sys.ArgumentNullException: Sys.ArgumentNullException: Value cannot be null.` error referred to in [my comment](https://github.com/OfficeDev/office-js/issues/1824#issuecomment-1715785828) in #1824 
6. Curiously, the same code in MacOS Word works but in Office Online, fails.
7. Seems related to this [Stackoverflow question](https://stackoverflow.com/questions/29294751/office365-app-for-excel-web-value-cannot-be-null-parameter-name-conversation) (over 8 years ago) and this appears to be a recurring issue based on #2167

**Comment by ZYUN-MSFT** [comment]
Hi @justmars ,

I'm re-direct this to the right owner team, we will back here when we got the update.

Thanks.

**Comment by justmars** [comment]
Hi @ZYUN-MSFT , I've discovered the cause. 

`officejs` wasn't being initialized in the dialog for office online because the url contained a response header: `Cross-Origin-Opener-Policy: same-origin-allow-popups`. 

Removing `Cross-Origin-Opener-Policy` as a header enabled the officejs script to load and thus the dialog. 

With MacOS as the platform, this wasn't a problem however. It's only when the platform is web that the response header should be absent.

Thank you for getting back to me though.
