### ISSUE TITLE
Get "RichApi.Error: ItemNotFound" when call range.select() for search results in trackable paragraphs 

### ISSUE THREAD

**Issue by NataliaKravcheniaTR** [OfficeDev/office-js#3589]
Get "RichApi.Error: ItemNotFound" when call range.select() for search results in trackable paragraphs 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2302 Build 16.0.16130.20684) 64-bit 
* Operating System: Windows 10
 
## Expected behavior
Search text should be selected

## Current behavior
Search text shouldn't selected.  "RichApi.Error: ItemNotFound" occurs

## Steps to reproduce
1. Open ScriptLab
2. Import this snippet URL ---> (https://gist.github.com/NataliaKravcheniaTR/e421b3ab069028ea6fd7dc45fbc6c366)
3. Click 'Setup' and 'Basic Search' button

# Provide additional details
The issue is not reproducible in Word Online

## Useful logs
```
 {name: "RichApi.Error", code: "ItemNotFound", traceMessages: Array[0], innerError: null, debugInfo: Object…}
name: "RichApi.Error"
code: "ItemNotFound"
traceMessages: Array[0]
innerError: null
debugInfo: Object
code: "ItemNotFound"
message: "ItemNotFound"
toString: function toString()
errorLocation: "RangeCollection.getItem"
statement: "var _Search2Item = _Search2.getItem(...);"
surroundingStatements: Array[6]
0: "var v = context.root._getObjectByReferenceId("01E!00002343");"
1: "var _Search2 = v._Search2(...);"
2: "// >>>>>"
3: "var _Search2Item = _Search2.getItem(...);"
4: "// <<<<<"
5: "_Search2Item.select();"
fullStatements: Array[1]
httpStatusCode: 404

```

**Comment by Searion** [comment]
Thanks for reporting this issue. The basicSearch function should be surround by await Word.run(paragraphs, async (context) => {xxx});. This context will be same as trackedParagraph.context in this case and there will be no error.

**Comment by NataliaKravcheniaTR** [comment]
@Searion Thank you! It works!
