### ISSUE TITLE
Error 5001 on getAccessTokenAsync - Outlook for web 'New experience' 

### ISSUE THREAD

**Issue by justdevelopment** [OfficeDev/office-js#359]
When opening an add-in which uses the Office SSO (Office.context.auth.getAccessTokenAsync) the new Experience in Outlook for web returns an 5001 Internal Server error. 
Regular Outlook for web and up to date desktop versions of Outlook work correctly. 

![image](https://user-images.githubusercontent.com/23448165/50834266-dfd4f680-1353-11e9-9b03-2b22e790cc0a.png)

I'm unsure where to report this issue, hopefully this is the right place. Otherwise please redirect me :)

**Comment by niteshgolchha85** [comment]
SSO is not yet supported on the new Outlook for Web version. I am expecting this to be supported in preview by the end of current month.
