### ISSUE TITLE
Loading items inside Content Controls does not work after recent Word for Mac update

### ISSUE THREAD

**Issue by greatescape95** [OfficeDev/office-js#3593]
From Office Version 16.76 released on August 15th 2023 (2 days ago) there is an issue with loading items of `Word.ContentControlCollection` class when calling the `load` method.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Version 16.76 (23081101)
* Operating System: Mac OS Ventura (but can occur on other Mac OS having this Office version)
 
## Expected behavior
Items loaded using `Word.ContentControlCollection.load('items')` should be loaded normally like in previous Office versions

## Current behavior
Currently the `Word.ContentControlCollection.load('items')` load operation fails.

## Steps to reproduce
Using `Word.ContentControlCollection.load('items')` anywhere in the word add in app in Office 16.76.

## Link to live example(s)

Minimum reproducable version of a Script Lab snippet:
https://gist.github.com/greatescape95/23f67df0d5b71c84990019f83004497b

# Provide additional details
The Script Lab snippet provided is basically the snippet for the content control basics example where only lines 40 and 41 have been edited as follows:
```
evenContentControls.load('items');
oddContentControls.load('items');
```
The key thing to notice here is that it seems the loading of content control items is failing if `'items'` is used as an argument. Hack that seems to be working is using `'item'` instead, but we are not sure is that a way to go, as we can't find any documentation about it.

## Context
This issue is a blocker for us as it is preventing fetching content control data in our application which is heavily leaning on content control api. Please help us as our add-in is practically unusable in all the newly updated Words on Mac OS!

## Useful logs

This is a screenshot of the error in the console when we are trying to load items from Content Control Collection. 
<img width="863" alt="image" src="https://github.com/OfficeDev/office-js/assets/11823934/361f41cc-f6f0-444e-aad4-c7f15f32f4c9">

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by greatescape95** [comment]
This is probably related to other issue related to Content Controls and newest mac OS update from couple of days ago (16.76) reported here: https://github.com/OfficeDev/office-js/issues/3587. It seems something has been broken with Content Control Api in the latest release. Please help us as we have a production running add-in which is currently not working for all the users using this Mac OS version.

**Comment by ZYUN-MSFT** [comment]
Hi all, this issue should be fixed now. If you still have the error, please update to the newest version of Office and retry, thanks.
