### ISSUE TITLE
Custom Excel Addin stopped working

### ISSUE THREAD

**Issue by Vic2rii** [OfficeDev/office-js#3596]
Excel Custom functions stopped working. 

Built a JavaScript Excel Custom Functions using a Shared Runtime, and it had been running fine for over a year. But yesterday it stopped working and we cannot figure out why. No change was made to the project recently.

The add In is being hosted on a Azure Static web app and is linked to one of our Function apps to provide the API's being used to retrieve data. 

From the little debugging we have been able to do, The network tab does not show a request being made to the API to retrieve any data when a custom function is called. The cell in which the function was called just shows "#Value". We can confirm that the API being called works and that nothing has changed on our side with the Add In code or the API itself. We are unsure of how to proceed with this issue.

<img width="778" alt="image" src="https://github.com/OfficeDev/office-js-docs-pr/assets/89276181/7ceca77e-bad7-49ee-b701-1d89aac3fcbe">

Not sure if this it the right place to ask this question, but wanted to try anyway and hopefully get some pointers in the right direction.

**Comment by davidchesnut** [comment]
Hi @Vic2rii, thanks for letting us know about this issue. @kkmanwilliam could you please help with this issue?

Thanks,
David

**Comment by Vic2rii** [comment]
UPDATE: Issue has been resolved 

We were able to get the Add-in working again by updating some dependencies. Not exactly sure which of them broke the application, but I will give a list below of what was updated.

-  "node": ">=14 <17"
- "npm": ">=6 <9" 
-  "babel-loader": "^8.2.2"
-  "custom-functions-metadata-plugin": "^1.4.4"
-  "eslint-plugin-office-addins": "^2.1.3"
-  "office-addin-cli": "^1.5.3"
-  "office-addin-debugging": "^4.6.3",
-  "office-addin-dev-certs": "^1.9.3",
-  "office-addin-lint": "^2.2.3",
-  "office-addin-manifest": "^1.10.4",
-  "webpack": "^5.73.0",
-  "webpack-cli": "^4.8.0",
-  "webpack-dev-server": "4.7.4"

**Comment by XuanZhouMSFT** [comment]
Really appreciate for the information and glad to hear that it's already back.
Close the issue and please feel free to leave comments if you have any concerns.
