### ISSUE TITLE
Word Online has issue with insert order inside a content control

### ISSUE THREAD

**Issue by lightman76** [OfficeDev/office-js#3599]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Build: 16.0.16816.41004
* Operating System: macOS
* Browser (if using Office on the web): Chrome
 
## Expected behavior

Expect that Word Online should insert the paragraphs in the order of the calls when calling 
`contentControl.insertParagraph("my text...", Word.InsertLocation.end) `
multiple times.  The same code works as expected in Desktop Word (MacOS and Windows). See screenshot from [MacOS desktop Word](https://scrible-maintenance.s3.us-west-2.amazonaws.com/office-test1/BugExample-Word-on-macOS.png).

## Current behavior

Paragraphs are inserted in reverse order. See screenshot from [Word Online](https://scrible-maintenance.s3.us-west-2.amazonaws.com/office-test1/BugExample-Word-online.png).

## Steps to reproduce

1. Using OfficeJS, append two paragraphs to the end of the document and then insert the content control into the first one (the need to insert the second paragraph is a separate bug I'll try to reproduce in an example and file later).  
2. Call context.sync
3. Insert several paragraphs into the content control using insert location of "End"
4. Call context.sync
The paragraphs in Word online show up in the reverse order of insertion, where as on Desktop Word they appear in the inserted order.

## Link to live example(s)

I set up a simple add-in for Word to show the example before I saw these instructions for ScriptLab.  I've quickly made a script lab version [here](https://gist.github.com/lightman76/a7951df773301b057112f8a1d452e23d)
Running this will insert a content control in the document as described above with paragraphs which contain the numeric order in which they were inserted.  In Word Online, they're reversed from the Desktop Word order.

If you want to see the add-in, the source can be found in [GitHub](https://github.com/lightman76/word-add-issue) and the add-in manifest can be found [here](https://scrible-maintenance.s3.us-west-2.amazonaws.com/office-test1/bug-example-manifest.xml)

Sideload this add-in and add it to a document and launch it (opens a sidebar).  Click the `Insert Entries` button in the sidebar and the content control will be created if it doesn't exist and then have 4 entries inserted.

# Provide additional details

None required

## Context

My company has an add-on, Scrible Writer, which manages in-text citations and bibliographies which is used in education.  We use a content control for the bibliography to avoid users accidentally adding content in the bibliography since that area of the document gets refreshed periodically.  Teachers aren't amused if the bibliography is in reverse alphabetical order.

## Useful logs

- [ ] Console errors
- [x] Screenshots
  - [Expected output from Desktop Word](https://scrible-maintenance.s3.us-west-2.amazonaws.com/office-test1/BugExample-Word-on-macOS.png)
  - [Incorrect output from Word Online](https://scrible-maintenance.s3.us-west-2.amazonaws.com/office-test1/BugExample-Word-online.png)
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by YijunMS** [comment]
Hi @lightman76, thanks for reporting this issue to us. Work item(8237881) is created to track the progress of the this question. Once there's any update, we'll sync with you. Thanks again for reaching out to us.

**Comment by xiruatms** [comment]
@lightman76 , thanks for reporting this. There's no promised timeline regarding this yet. If you have more information for us to review the priority, that'll be great.

**Comment by lightman76** [comment]
Sorry - what feedback do you need from me?

The ScriptLab example still demonstrates the issue showing that the content is inserted into the content control in reverse order in Word Online.

**Comment by xiruatms** [comment]
@lightman76 , thanks for your patience. The fix should be now on production, will yo please help to take a try?

**Comment by lightman76** [comment]
Confirming that the fix works for the simplified ScriptLab example.  In my real world add-on I'm now getting an error inserting the second paragraph which does not occur in desktop Word.  Will investigate and let you know if it appears to be related to this issue.

**Comment by xiruatms** [comment]
@lightman76 , are there any found? I will close this issue. But feel free to raise another one if you identified anything unexpected.
