### ISSUE TITLE
Title of dialog does not change when user navigates to new page

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js#36]
## Expected Behavior
When a user opens a dialog with our Dialog API, the dialog’s title is the of the form:
      Add-in Name [- page title from <title> tag]
If there is no text in the page’s <title></title> tag, then only the Add-in Name appears. 
When the dialog redirects or is navigated to a page that has a non-blank <title></title> tag, then the part of the dialog name to the right of the hyphen should change to match the new page's title.

## Current Behavior
The part after the hyphen stays the same, so the name of the first page that was opened (if it had a non-blank <title></title> tag) remains there as long as the dialog is open.

## Steps to Reproduce, or Live Example
Clone this repo: https://github.com/OfficeDev/Office-Add-in-Dialog-API-Simple-Example
Open it in Visual Studio.

Open Dialog.html and change it's title to <title>My first dialog</title>.
Add the following in the <body> tag: <div>This page is titled My first dialog</div>
Copy Dialog.html to OtherPage.html.
Open OtherPage.html and change it's title to <title>OtherPage</title>.
Add the following in the <body> tag: <div>This page is titled OtherPage</div>

Open Dialog.html again and change the single line of code in the one() method to:
window.location = "OtherPage.html";

Run the add-in with F5.
Press the **Dialog from Taskpane** button.
Press the **Pick a number (popup)** button. Notice that the dialog title ends with "My first dialog".
Press the "1" button on the dialog. Notice that you are routed to the OtherPage, but the dialog title does not change.

## Context
This was reported by customer: https://github.com/OfficeDev/office-js-docs/issues/1227

## Your Environment

* Platform PC desktop
* Host Word
* Office version number: 1712, 8822
* Operating System: win

**Comment by lliu113** [comment]
@Rick-Kirkham  - closing this bug as we've migrated to showing the domain in the title. Please reactivate if this is still an issue. 
Thanks!
