### ISSUE TITLE
[New Outlook on Windows] Links inside add-in open in new Outlook window instead of default browser

### ISSUE THREAD

**Issue by manufz** [OfficeDev/office-js#3602]
## Your Environment
New Outlook on Windows (preview) client v1.2023.807.100
 
## Expected behavior
Links should open in default browser where the user is generally working, authenticated, etc.

## Current behavior
When clicking on an (external) link in Outlook task pane add-in the site is opened in a new Outlook window instead of the default browser. This wasn't previously the case (like two weeks ago) and also does not work like this in the current ("old") Outlook client.

Example of an add-in with an embedded bing.com link:
![image](https://github.com/OfficeDev/office-js/assets/30493494/704534d5-a4b9-44c9-b654-96d63834e0a3)

## Steps to reproduce
Create a Outlook task pane add-in with an embedded link (e.g. window.open('https://bing.com') or window.open('https://bing.com', '_blank'))

**Comment by exextoc** [comment]
Thanks for reporting the issue. It has been put in our backlog. Unfortunately, we do not have any timelines to share at this point
Internal tracking id - 224390

**Comment by haseeblinq** [comment]
any updates on this issue?
