### ISSUE TITLE
Apply sensitivity label to outgoing emails

### ISSUE THREAD

**Issue by ravster** [OfficeDev/office-js#3603]
# Provide required information needed to triage your issue

Our application allows our customers to create responsive HTML emails (in the form of company wide newsletters) & deliver them to their intended recipients via our Office 365 Web Add-in. After sending, we provide them with analytics to determine the success of their email.

We want to send email with sensitivity-labels, but can't find information on how to do that using the MS-Graph API v1.0.  We found this [documentation](https://learn.microsoft.com/en-us/javascript/api/outlook/office.sensitivitylabel?view=outlook-js-preview) that allows outlook-JS to identify which sensitivity-label has been selected by the user, and [this doc](https://learn.microsoft.com/en-us/graph/api/security-sensitivitylabel-evaluateapplication?view=graph-rest-beta&tabs=http) that may help us with applying a sensitivity-label on an outgoing email in the beta API.

We'd like clarification on:
- Can we apply a sensitivity-label using the latest production version (1.0) of MS-Graph-API? If yes, please point us to the right documentation for that.
- If no, will this be possible using the beta version of ms-graph? When will that be available for production usage, and what is the correct doc for that feature?

## Your Environment
Should work on outlook desktop (windows and mac), as well as on the outlook.com website

## Expected behavior

We can add a sensitivity-label to an outgoing email using the MS Graph API.

## Current behavior

We don't know how to add a sensitivity-label to an outgoing email, using the MS-Graph API.

**Comment by Adrian-MSFT** [comment]
Hi @ravster, the outlook-JS documentation you provided also allows you to set a sensitivity label using our office js API https://learn.microsoft.com/en-us/javascript/api/outlook/office.sensitivitylabel?view=outlook-js-preview#outlook-office-sensitivitylabel-setasync-member(2)

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sensitivity-label

Or are you looking for ms-graph functionality specifically, without the use of office js?

**Comment by timminss** [comment]
Hi @Adrian-MSFT , thanks a lot for your response. I have played around with the OfficeJS API, and it looks like we can indeed retrieve (and apply) Sensitivity Labels via our addin.

We would like to:

1. Create a new email.
2. Apply a sensitivity label (via the Office JS API).
3. Save the email as a draft.
4. (Later) Send the draft email via the Graph API.

Steps 1 through 3 are working as expected - thanks for your link to the documentation in your response. However, once the email is sent via Graph, the sensitivity label previously applied does not appear to be retained.

Are there any additional steps we need to take to ensure that a sensitivity label applied to a draft is retained when sent via the Graph API?

Thanks again for your help

**Comment by ravster** [comment]
@Adrian-MSFT Hey, sorry about the slow response. I am specifically looking for ms-graph functionality for this. This is because we use ms-graph for the actual sending of the emails.

**Comment by Adrian-MSFT** [comment]
Thank you for your patience, I reached out to the graph team. They have no timelines available to give about beta APIs being added to production, however, you can keep an eye on the [Graph changelog](https://developer.microsoft.com/en-us/graph/changelog/).
