### ISSUE TITLE
Fetch request error in Outlook add-in for event-based activation

### ISSUE THREAD

**Issue by zjmchoi** [OfficeDev/office-js#3606]
# Provide required information needed to triage your issue
 In Outlook add-in for event-based activation, an error occurs when requesting to our server using the Fetch API.
 
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number:  Microsoft 365 MSO(version 2307 build 16.0.16626.20170) 32bit
* Operating System: Window 10 Pro (64bit)
* Browser (if using Office on the web): MS Edge (on window)
 
## Expected behavior

In Outlook on the web (chrome, edge) and app (window, mac), 
1. create new event for calendar.
2. press "send" button
3. At this point, send the any version information to our server using Fetch API,
4. This request  should succeed.

## Current behavior

Fetch request results:
1. window
    (1) web (chrome): ok
    (2) web (edge): nok
    (3) app: nok
8. mac
   (1) web (chrome): ok
   (2) app : ok

## Steps to reproduce

1. ______
9. ______
10. ______

## Link to live example(s)

1. ______
5. ______
6. ______

# Provide additional details

1. ______
2. ______
5. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
  
  [Test Code]

  let requestAPI = homeServerUrl + "/apis/space/version/"; <-- // this is example api, not real api.
  fetch(requestAPI, {
    method: "PUT",
    headers: {
      "Content-Type": "application/json",
      "Authorization": "Bearer " + accessToken
    },
    body: JSON.stringify(body)
  }).then((response) => {
    if (response.ok) {
      // Allow send
      event.completed({allowEvent: true});
      return;
    } else {
      response.json().then(result => {
        event.completed({allowEvent: false, errorMessage: "response error."});
        return;
      });
    }
  }).catch(error => {
    event.completed({allowEvent: false, errorMessage: "request error."});  
    return;
  });

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@zjmchoi We are not able to repro this issue. Could you please provide more details- 
1.  What is the error being thrown
2.  If possible can you please share a sample manifest which can be used to reproduce this issue

**Comment by zjmchoi** [comment]
1. What is the error being thrown
    -> In window outlook app, 
         event.completed({allowEvent: false, errorMessage: "request error."}); <-- An error occurs here.
         return;
         
        and also, in window outlook app, I don't know how to check the logs.

2. If possible can you please share a sample manifest which can be used to reproduce this issue.
    -> [manifest.zip](https://github.com/OfficeDev/office-js/files/12407221/manifest.zip)

  By default, is it right that the fetch operation should work fine without platform dependency?

**Comment by exextoc** [comment]
@zjmchoi The manifest shared does not work. Could you please let us know are you facing this in old outlook or new Outlook app? Also is the issue present in outlook web as well?
In case there are errors related to same origin browser policy the following doc can be referred for workarounds - https://learn.microsoft.com/en-us/office/dev/add-ins/develop/addressing-same-origin-policy-limitations

**Comment by zjmchoi** [comment]
Hi MSFT,

Fetch request results:

1 window os
(1) web (chrome): ok
(2) web (edge): nok
(3) app (old): nok
2. mac os
(1) web (chrome): ok
(2) app : ok

Basically, I know that we can use Fetch in an event based activation structure without platform dependency.

However, looking at the test results above, I think there is a platform dependency.

I wonder what it is.

If not, I have to analyze more the reason of the problem.

Thanks.

**Comment by exextoc** [comment]
@zjmchoi There is no platform dependency, and we are not able to repro the issue while using fetch api. It'd be helpful if you could share error details using edge dev tools.

**Comment by zjmchoi** [comment]
OK. I will do more testing based on your comments.
If the problem continues, I will open this issue again.
Please close this issue.
