### ISSUE TITLE
[Bug]RichApi.Error: NotImplemented

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#3607]
when execute the codes as follows,error happens:
```js
Word.run(async (context) => {
const document = context.document;
let controls = document.contentControls;
controls.load("items, id");//error

return context
          .sync()
          .then(() => {
                context.document.load(["contentControls"]);//error
          .then(context.sync)
......
```

```js
word-win32-16.01.js:25  Uncaught (in promise) RichApi.Error: NotImplemented
    at new n (word-win32-16.01.js:25:246592)
    at i.processRequestExecutorResponseMessage (word-win32-16.01.js:25:310758)
    at word-win32-16.01.js:25:308821
```

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __PC desktop____
* Host [Excel, Word, PowerPoint, etc.]: __Word____
* Office version number: __Microsoft® Word 适用于 Microsoft 365MSO (版本 2308 Build 16.0.16731.20052) 32 位____
* Operating System: ___Windows___
* Browser (if using Office on the web): ___Edge___
 
## Expected behavior

Load properties normally!

## Current behavior

Queues up a command to load the specified properties of the object,js error happens!

## Steps to reproduce

1. __Office 365 __16731.XXX Version__
2. __controls.load("items,id");__or context.document.load(["contentControls"]);_

## Link to live example(s)

1. ___https://learn.microsoft.com/en-us/javascript/api/word/word.document?view=word-js-preview#word-word-document-load-member(2)___ 
 
 
## Useful logs

![1](https://github.com/OfficeDev/office-js/assets/3182964/46e00209-adcb-417a-8437-56b0b5211b44)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ZYUN-MSFT** [comment]
Hi @hengchengfei ,

Are you using the Preview Channel of Office?

Thanks.

**Comment by hengchengfei** [comment]
@ZYUN-MSFT 
![1](https://github.com/OfficeDev/office-js/assets/3182964/ed5f9421-31f8-4d8a-80d5-3184d892d1f0)

**Comment by ZYUN-MSFT** [comment]
Hi @hengchengfei ,

Thanks for confirming, this is a known issue for preview channel of Win32 Office.\
Please update your office to version 16.0.16731.20094 and try your code again.

Thanks.

**Comment by hengchengfei** [comment]
Hi @ZYUN-MSFT 

Thanks for your reply.

I upgrade office to 16731.20094，but it still doesn't work，the same error happens.

![1](https://github.com/OfficeDev/office-js/assets/3182964/f699d7a5-cfa4-4951-b09b-da9f98c74a6d)

**Comment by dhoelzl** [comment]
I have the same issue on Word for Mac, Version 16.76 (23081101).
OfficeJS used: https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js



```JavaScript
await Word.run(async (context) => {
  try {
    let cc = context.document.contentControls; cc.load("items"); await context.sync(); console.log(cc.items);
  } catch (e) {
    console.error("ERROR", e, e.debugInfo);
  }
});
```

```
[Error] ERROR (2)
NotImplemented: NotImplemented
Object

code: "NotImplemented"

errorLocation: "ContentControl.checkboxContentControl"

fullStatements: ["var root = context.root;", "var contentControls = root.contentControls;", "// Instantiate {contentControls}", "contentControls.load([\"*\"]);"] (4)

message: "NotImplemented"

statement: "contentControls.load([\"*\"]);"

surroundingStatements: ["var root = context.root;", "var contentControls = root.contentControls;", "// Instantiate {contentControls}", "// >>>>>", "contentControls.load([\"*\"]);", "// <<<<<"] (6)

toString: function()

Object Prototyp
	Konsolenauswertung (Konsolenauswertung 3:10)
```

It does not occur if there are no rich text content controls in the document.

**Comment by sergiosagu** [comment]
Hi @hengchengfei, @dhoelzl,

As mentioned above, this is a known issue and we're working on releasing the patch as soon as possible.

Nevertheless, may I suggest you to try a workaround until the patch is released? The issue is caused by the load method() when trying to load one or more content controls as a whole (all their properties), if you try to load only the properties that you need then it should work. For example:

replace:
```
controls.load("items, id");
await context.sync();
```

with just:
```
controls.load("id");
await context.sync();
```

or with multiple properties as you need them, e.g.:
```
contentControls.load({
  id: true,
  type: true,
  text: true
});
await context.sync();
```

And if you need to access to a particular content control or to iterate the collection of content controls, you could use the approach described here https://learn.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview#word-word-contentcontrol-load-member(1)

**Comment by dhoelzl** [comment]
Thanks for your response. I've just found the right bug tracker for this:

https://github.com/OfficeDev/office-js/issues/3587

**Comment by hengchengfei** [comment]
@sergiosagu 
Thanks!

I tried the follow code,but doesn't work.
```js
context.document.load("contentControls");
```

**Comment by sergiosagu** [comment]
@hengchengfei , I'm afraid that that will still try to load all content controls at once with all their properties. You may try the following approach:

```javascript
  // get all the content controls
  const contentControls = context.document.getContentControls(); 

  // e.g. load only specific properties from content controls (to be used later) 
  contentControls.load({ 
    id: true, 
    type: true, 
    text: true 
  }); 
  await context.sync(); 

  // e.g. use all or a subset of the specifically loaded properties 
  contentControls.items.forEach((contentControl) => { 
    console.log([ 
      `id: ${contentControl.id}`,  
      `type: ${contentControl.type}`, 
      `text: ${contentControl.text}` 
      ].join("\n")); 
  }); 
```

I hope that helps!

**Comment by hengchengfei** [comment]
@sergiosagu 
Thank you for reply。

I want to reload all contentcontrols and get the latest content controls.
if don't reload,the value of **oldContentControls** will equal to **newContentControls** 

```js
Word.run(async (context) => {
   const oldContentControls = context.document.getContentControls(); 

    //delete a content control or add a content control
   xContentControl.delete();
   await context.sync(); 

    //reload all content controls
   context.document.load("contentControls");
   await context.sync(); 
 
   const newContentControls = context.document.getContentControls();  
})
```

**Comment by sergiosagu** [comment]
@hengchengfei , thank you for the follow up.
Interesting, I thought that after
```javascript
   xContentControl.delete();
   await context.sync(); 
```
the `context.sync()` itself would refresh the context in such a way that your `newContentControls` would be the updated version. But I'm not that familiar with that part.
In any case, the original issue throwing `RichApi.Error: NotImplemented` it's solved and all the latest released builds should contain the fix, did you try updating it?

**Comment by hengchengfei** [comment]
@sergiosagu 
I had updated the Office Version to latest，and problem had been resolved.

thank you!
