### ISSUE TITLE
Calling load on Word.Comment class to get replies causes RichApi.Error: Cannot read properties of null (reading 'Ra') in Office for Web

### ISSUE THREAD

**Issue by sumanth-spotdraft** [OfficeDev/office-js#3608]
# Provide required information needed to triage your issue
When calling `load("replies")` on `Word.Comment` class in an Office add-in in a browser using Office for web causes an error for comments that are added to bullets, headers, tables, etc. 

Note: This is not an issue when we try to retrieve comments and their replies when it is added to the text that is _NOT_ part of some formatting like bullets, headers, footers etc.

```js
RichApi.Error: Cannot read properties of null (reading 'Ra')
    at new n (word-web-16.00.js:25:333265)
    at o.processRequestExecutorResponseMessage (word-web-16.00.js:25:397711)
    at word-web-16.00.js:25:395774
    at _ZoneDelegate.invoke (zone.js:409:30)
    at Object.onInvoke (core.mjs:26250:33)
    at _ZoneDelegate.invoke (zone.js:408:56)
    at Zone.run (zone.js:169:47)
    at zone.js:1326:38
    at _ZoneDelegate.invokeTask (zone.js:443:35)
    at Object.onInvokeTask (core.mjs:26237:33)
```
Example code snippet:

```js
    async getCommentsAndReplies() {
    await Word.run(
     
      async (context) => { 
        const collection = context.document.body.getComments();
        collection.load(`${CommentLoadOptions.items}`);

        await context.sync();
        const comments = collection.items;

        for (let i = 0; i < comments.length; i++) {
          const comment = comments[i];
          try {
            comment.load(
              `replies`
            );
            await comment.context.sync();
          } catch (ex) {
            console.error(ex);
          }
        }
      }
    )
  }
```

When exactly the same code is executed in a native Office application (e.g. in a current version of Word 365 for Mac) it works as expected.

The script is included by

`<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>`

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
* Operating System: macOS Ventura
* Browser (if using Office on the web): Chrome, Arc, Firefox
 
## Expected behavior

Should be able to load replies from comment class objects when the comment is added to text that is part of bullets, tables, headers, footers etc
## Current behavior
calling load("replies") on Comment class crashes for certain comments

## Steps to reproduce

- Create a simple OfficeJS-Add-In with a task pane
- Run the Add-In in a web browser / Office for the web on office.com
- Add comments to text that is part of bullets, or add a comment to a table and then add replies to it.
- Execute the sample code mentioned above to retrieve comments and their replies

## Context
We are not able to render the replies to the comments added to list items, tables, headers, footers etc in our task pane UI

## Useful logs

- [x] Console errors
```js
RichApi.Error: Cannot read properties of null (reading 'Ra')
    at new n (word-web-16.00.js:25:333265)
    at o.processRequestExecutorResponseMessage (word-web-16.00.js:25:397711)
    at word-web-16.00.js:25:395774
    at _ZoneDelegate.invoke (zone.js:409:30)
    at Object.onInvoke (core.mjs:26250:33)
    at _ZoneDelegate.invoke (zone.js:408:56)
    at Zone.run (zone.js:169:47)
    at zone.js:1326:38
    at _ZoneDelegate.invokeTask (zone.js:443:35)
    at Object.onInvokeTask (core.mjs:26237:33)
```

**Comment by xiruatms** [comment]
Thanks for reporting this. I confirm I can repro it. There's an internal workitem #8257478 to track this.

**Comment by xiruatms** [comment]
@sumanth-spotdraft , the fix should be pushed to production now. Will you please take a try and confirm whether it's working for you now? Thanks
