### ISSUE TITLE
promptBeforeOpen: false setting for Office.context.ui.displayDialogAsync not work for outlook online

### ISSUE THREAD

**Issue by jarodchen** [OfficeDev/office-js#361]
## Expected Behavior
if we set promptBeforeOpen: false, displayDialogAsync will not pop a confirm window.

## Current Behavior
displayDialogAsync always pop a confirm window, ignore the setting of promptBeforeOpen

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: outlook
* Office version number: office 365
* Operating System: windows 10
* Browser (if using Office Online): chrome, edge

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by danielgwilson** [comment]
Hey! Sorry to hear you're running into an issue here—can you post your Office version number? It's in the About section of the File menu:

![wac_build](https://user-images.githubusercontent.com/11265967/51130581-27d79b80-17e2-11e9-8007-006bf3d486c7.jpg)

**Comment by exextoc** [comment]
Thanks for reporting the issue, Jarod. We've confirmed that the parameter does not work currently for Outlook Web, and are looking into it further.

**Comment by exextoc** [comment]
We have resolved this issue and the fix will be deployed soon.
