### ISSUE TITLE
Sometimes the onsend add-in does not execute.

### ISSUE THREAD

**Issue by t-ariyoshi30907** [OfficeDev/office-js#3610]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2302 (build 16.0.16130.20378)
* Operating System: Windows OS
* Browser (if using Office on the web): Google Chrome

## Expected behavior

1. Create an email.
2. Click "Send."
3. Execute the "displayDialogAsync" function of the Dialog API.
4. The dialog is displayed.

## Current behavior

1. Create an email.
2. Click "Send."
3. Execute the "displayDialogAsync" function of the Dialog API.
4. The dialog does not appear.

## Steps to reproduce

1. Access the following URL.
　https://drive.google.com/file/d/1Xrc-HuBLSjBAwDmU7y7Pbi7amwegbPDY/view?usp=share_link
2. Download "sample.zip" and place it in your desired location.
3. Launch the command prompt and navigate to the corresponding directory.
4. Run "npm install".
5. Run "npm run dev-server".
6. Upload "manifest.xml" in Outlook on the web to install the add-in. (The XML file is stored in sample.zip)
7. Create and send an email.

## Link to live example(s)

I am storing the related videos at the following URL.

- related videos
https://drive.google.com/file/d/1DliU7_cjXuCRcanzyJW5l4CK902FSiMF/view?usp=drive_link

We have received feedback from customer requesting improvements.
Please investigate and make necessary improvements.

**Comment by exextoc** [comment]
Thanks for reaching out. We were unable to repro the issue even with the addin provided here. Is this a consistent repro. Can you please check and share if there are any errors in the console when the addin does not run.

**Comment by t-ariyoshi30907** [comment]
@exextoc 
No, it doesn't necessarily mean that a problem will occur. There are times when it occurs and times when it doesn't.

Here's the console log when the add-in is executed:

- When the add-in is executed
https://drive.google.com/file/d/10jnA8Gq93we4FaSwrxR7Hn2TvZXZBQQJ/view?usp=drive_link

- When the add-in is not executed
- https://drive.google.com/file/d/1ePlUYK48XYoiwP25AJnJ2vdGAA7Od6jL/view?usp=drive_link

I will also share the network log for when the add-in is not executed. Please take a look and let me know.

- NetWork log
https://drive.google.com/file/d/1QxCoxn30oWc5NGngCNX70TkbznlTXGt4/view?usp=drive_link

**Comment by exextoc** [comment]
[t-ariyoshi30907](https://github.com/t-ariyoshi30907) The OnMessageSend event is available through the event-based activation feature. From event based activation, displayDialogAsync is not supported. Please refer the doc below for set of API that are blocked from event based activation.
[Configure your Outlook add-in for event-based activation - Office Add-ins | Microsoft Learn](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest#event-based-activation-behavior-and-limitations)

**Comment by t-ariyoshi30907** [comment]
@exextoc 
I'm not using the onMessageSend event of API set 1.12. What I'm using is the ItemSend event. Is it the onMessageSend event that is not supported?

**Comment by exextoc** [comment]
@t-ariyoshi30907 Thanks for the clarification. 
Could you please list down the exact step that always reproduces the problem. We were unable to repro the issue with the addin provided and steps given.

**Comment by t-ariyoshi30907** [comment]
@exextoc 
I'm sorry. I don't know how to intentionally cause the issue.
However, it occurs about once every ten times. Could you please conduct an investigation?
If there is any necessary information for the investigation, I will collect it.

**Comment by exextoc** [comment]
@t-ariyoshi30907 We accepted the issue for further investigation. Internal triage id: OWA: [229304]

Unfortunately there are no timelines as to when this bug will be fixed. But we will update when the fix is available.

**Comment by t-ariyoshi30907** [comment]
@exextoc 
Thank you for your reply. I hope this problem will be resolved. I appreciate your continued attention.

**Comment by t-ariyoshi30907** [comment]
@exextoc 
After conducting the test once again today, there is a new error message appearing in the console, and it displays a clear error. Can you use this error as a hint to make improvements to the program? I will share the reproduction video once again for your reference.

https://drive.google.com/file/d/1uGxQtRtgiGAOIbk9j_JcFUXplYX3DG1T/view?usp=drive_link

**Comment by exextoc** [comment]
@t-ariyoshi30907 It'd be helpful if you could share a test account user name/password on this email - OutlookExtensibility@M365x53858506.onmicrosoft.com. This will help us in repro and further investigation
