### ISSUE TITLE
Field.result.insertHtml() inserts HTML outside of field.

### ISSUE THREAD

**Issue by adomasven** [OfficeDev/office-js#3613]
Testing with Word Online.

This works as expected and produces a field with text "Test Field" and code "ADDIN test":
```js
await Word.run(async (context) => {
	const selection = context.document.getSelection().getRange();
	const field = selection.insertField('Replace', 'Addin');
	field.code = `ADDIN test`;
	field.result.insertText("Test Field", "Replace"); // OK
	await context.sync();
});
```

This does not work and removes the field leaving plain text "Test Field". Any attempt to interact with the field post `sync()` call results in an error.
```js
await Word.run(async (context) => {
	const selection = context.document.getSelection().getRange();
	const field = selection.insertField('Replace', 'Addin');
	field.code = `ADDIN test`;
	field.result.insertHtml("Test Field", "Replace"); // Removes field
	await context.sync();
});
```

If we use a different operation instead of `Replace`, we get a field with "Test Field" and some "Test HTML" outside of field.
```js
await Word.run(async (context) => {
	const selection = context.document.getSelection().getRange();
	const field = selection.insertField('Replace', 'Addin');
	field.code = `ADDIN test`;
	field.result.insertText("Test Field", "Replace");
	field.result.insertHtml("Test HTML, "End");
	await context.sync();
});
```

**Comment by xiruatms** [comment]
Hi, @adomasven , thanks for reporting this. Currently, field.result.insertHtml() is not fully supported yet. As a mitigation, if you want to add some richtext to field.result, you may take a try with following solution:

```typescript
  await Word.run(async (context) => {
    const selection = context.document.getSelection().getRange();
    const field = selection.insertField('Replace', 'Addin');
    field.code = `ADDIN test`;
    let range = field.result.insertText("Test Field", "Replace"); // OK
    range.font.bold = true;
    await context.sync();
  });
```

**Comment by adomasven** [comment]
Is there a timeline for when this will be supported? This is a blocking bug for our Zotero plugin.

**Comment by xiruatms** [comment]
Thanks for the checking. This requirement is in our backlog, we're working on it.

**Comment by YijunMS** [comment]
Hi @adomasven, we deployed a fix recently, which should partially solve this issue.
For field.result.insertHtml at "Start"/"End", the issue should be fixed in most cases.
For field.result.insertHtml at "Replace", we haven't fixed it. As a workaround, you may first clear the content in the field (for example, call field.result.insertText("", "Replace")), then call field.result.insertHtml at "Start" or "End".

Please let us know if this can solve the problem.

**Comment by adomasven** [comment]
Inserting HTML into a field now works, but causes errors if you try to continue working with the field https://github.com/OfficeDev/office-js/issues/4388

**Comment by YijunMS** [comment]
@adomasven Thanks for reaching us, lets continue the discussion in the other thread.

**Comment by xiruatms** [comment]
Close the issue given it fixes the major requirement. Will track in another issue as #4388
