### ISSUE TITLE
addFileAttachmentAsync never returns a success or failure

### ISSUE THREAD

**Issue by varunrathi1** [OfficeDev/office-js#3614]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook mail 
* Office version number: 
* Operating System: Windows 10
* Browser (if using Office on the web):Chrome
 
## Expected behavior

Office.context.mailbox.item.addFileAttachmentAsync should return either success or a failure object so that the object may be resolved
## Current behavior

The solution never returns a response(either success or failure) and the code ends up waiting indefinitely. This issue is intermittent and can be observed when files are uploaded in bulk or a large file (> 20 MB ) is uploaded in networks having high latency.  

Note: A similar issue has been raised with the ID #1130. 
Link:  https://github.com/OfficeDev/office-js/issues/1130 

## Link to live example(s)

# Provide additional details

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Thanks for reporting the issue. It is present in our backlog but unfortunately, we don't have any timelines to share.
Internal Tracking Id- 84990
