### ISSUE TITLE
Error in desktop Outlook with OnMessageCompose event-based activation

### ISSUE THREAD

**Issue by manaunl** [OfficeDev/office-js#3616]
# Summary
We're utilizing the `OnMessageCompose` event for event-based activation in our add-in manifest. While the add-in functions seamlessly in browsers like Chrome, an error is encountered when composing a new message in the desktop version of Outlook. 

Notably, this issue is unique to the `OnMessageCompose` event. We've integrated various other EBA events such as `OnMessageAttachmentsChanged` and `OnMessageRecipientsChanged`. In scenarios excluding the `OnMessageCompose` event from the manifest, the add-in behaves as expected.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: office-js 1.13, Microsoft Outlook for Microsoft 365 MSO (Version 2307 Build 16.0.16626.20170) 64-bit 
* Operating System: Windows 10 Enterprise, 22H2, build 19045.3324
* Browser (if using Office on the web): ______
 
## Expected behavior

Add-in is successfully loaded without errors

## Current behavior

Task pane with add-in is open with the error: "We can't start this add-in because it isn't set up properly"
![Screenshot 2023-08-23 at 16 28 25](https://github.com/OfficeDev/office-js/assets/1925146/a8684f87-78ba-4df5-8eb8-d56ae537bfe3)

## Steps to reproduce

1. Open Outlook desktop application 
2. Compose new message

# Provide additional details

Sample manifest code:
```
....
<Hosts>
 <Host xsi:type="MailHost">
 <Runtimes>
   <Runtime resid="eventBasedActivationUrl"></Runtime>
  </Runtimes>
....
<!-- Event-based activation -->
 <ExtensionPoint xsi:type="LaunchEvent">
  <LaunchEvents>
   ...
   <LaunchEvent Type="OnMessageCompose" FunctionName="onMessageComposeHandler"/>
  </LaunchEvents>
  <SourceLocation resid="eventBasedActivationUrl"/>
 </ExtensionPoint>
....
<Resources>
...
 <bt:Urls>
 ....
  <bt:Url id="eventBasedActivationUrl" DefaultValue="https://example.com"></bt:Url>
 </bt:Urls>
....
```

## Context

This bug is particularly concerning as it impedes the message sending function when users compose messages in desktop Outlook. This is a critical issue for us since our clients utilizes both the web and desktop versions of Outlook. Their workflow is severely disrupted in the desktop version due to this error.

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
Regarding your manifest, does the `eventBasedActivationUrl` resource point to a JavaScript file or an HTML file?

**Comment by manaunl** [comment]
The `eventBasedActivationUrl` point to an HTML file which is a SPA.
```
<bt:Url id="eventBasedActivationUrl" DefaultValue="https://example.com/index.html#/entry/point"></bt:Url>
```

**Comment by manaunl** [comment]
@exextoc Do you mind to share any updates about this issue? Can you reproduce it? Is there any workaround you can provide?

**Comment by exextoc** [comment]
@manaunl - Are you seeing this issue in Outlook Web or Mac / iOS/Android? Or is this specific to Old Outlook on Windows?

**Comment by manaunl** [comment]
@exextoc This issue occurs on the desktop version of outlook. What do you mean by Old Outlook? 
The version of the Outlook where we have this issue is 'Microsoft Outlook for Microsoft 365 MSO (Version 2307 Build 16.0.16626.20170) 64-bit'

**Comment by geoffreyreemer** [comment]
Hi. Experiencing the same issue with our M365 add-in that has almost an identical set-up. @exextoc, is there a workaround or solution we could share with our customers, or an ETA on when this could be looked into? Thank you...

**Comment by exextoc** [comment]
@manaunl, per our documentation, you need an override for the Runtime to support Windows Outlook.
This override should point to a JavaScript file, not an HTML file.

Please see the **Configure the manifest** section of our documentation for further information:
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest#configure-the-manifest

@geoffreyreemer it is unclear whether your issue is exactly the same or a separate one. However, if your manifest is also missing the Runtime override, that could be the reason why. If not, please open a separate issue so that we can handle that separately.

**Comment by manaunl** [comment]
@exextoc thanks, very much appreciate, it works for me

**Comment by geoffreyreemer** [comment]
@exextoc Yes, works for me as well. Guess we overlooked the small print ;-). Have a great weekend!
