### ISSUE TITLE
Field.code does not persist if text and code are set multiple times.

### ISSUE THREAD

**Issue by adomasven** [OfficeDev/office-js#3617]
Word Online

If you insert and modify a field multiple times in the same Word.run call, only the initial field.code set is persisted, and it reverts if you replace the text of the field multiple times in subsequent Word.run calls.

```js
await Word.run(async (context) => {
	const selection = context.document.getSelection().getRange();
	const field = selection.insertField('Replace', 'Addin');
	field.code = `ADDIN test`;
	field.result.insertText("Test", "Replace");
	await context.sync();
	field.code = `ADDIN different`;
	// field.result.insertText("Test2", "Replace");
	await context.sync();
});
await Word.run(async (context) => {
	const fields = context.document.body.fields;
	fields.load('items');
	await context.sync();
	const field = fields.items[0];
	field.load('code');
	await context.sync();
	console.log(`Field code should be "ADDIN different": ${field.code}`)
});
```

The code above logs `Field code should be "ADDIN different": ADDIN different`. However, if you uncomment the commented out line, it will log `Field code should be "ADDIN different": ADDIN test`, i.e. doesn't persist the line `field.code = "ADDIN different"`. Make sure the cursor is placed before any other fields in the document!

**Comment by adomasven** [comment]
Hi, @xiruatms are you able to reproduce this?

**Comment by xiruatms** [comment]
@adomasven , thanks for reporting this. I confirm I can reproduce this, and I've created an internal work item #8316221 to track it.

**Comment by adomasven** [comment]
This appears to now be fixed. Thanks!
