### ISSUE TITLE
Setting negative style.paragraphFormat.firstLineIndent for hanging indent breaks Word Online

### ISSUE THREAD

**Issue by adomasven** [OfficeDev/office-js#3619]
Word Online

Per [ParagraphFormat.firstLineIndent](https://learn.microsoft.com/en-us/javascript/api/word/word.paragraphformat?view=word-js-preview#word-word-paragraphformat-firstlineindent-member) documentation, setting the number to a negative one sets a hanging indent. A positive number works, but if I set a negative number, it breaks Word Online with a prompt to reload:

![image](https://github.com/OfficeDev/office-js/assets/5899315/b6f9b07b-d52f-4d14-bc36-34c59800d1e8)

Sample code:

```js
await Word.run(async (context) => {
	const styles = context.document.getStyles();
	let style = styles.getByNameOrNullObject("Normal");
	style.load();
	await context.sync();
	style.paragraphFormat.firstLineIndent = -36;
	await context.sync();
});
```

**Comment by adomasven** [comment]
Note that you can set a hanging indent from Word Online paragraph style configuration dialog, so this is not a matter of lack of Word Online editor support.

**Comment by xiaoyuMS** [comment]
Hi @adomasven , thanks for reaching us.

I have created an internal bug 8277669. If there are any updates, we will come back to you.

**Comment by adomasven** [comment]
Appears to be fixed.
