### ISSUE TITLE
How can I show my Outlook add-in in my Outlook for Android?

### ISSUE THREAD

**Issue by rodrigoguariento** [OfficeDev/office-js#362]
Does anyone know how to configure my manifest.xml to show my Outlook Add-in in my Outlook for Android? My ExtensionPoint (xsi:type) was set for Desktop with AppointmentOrganizerCommandSurface.

At this moment my Add-in is working fine at PC, online, etc. except in my Outlook for Android. I'm not getting to see the button at some "OfficeTab".

Thanks!

Here is a snippet of my manifest.xml:

  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Description resid="myAppBookingGroup" />
    <Requirements>
      <bt:Sets DefaultMinVersion="1.6">
        <bt:Set Name="Mailbox" />
      </bt:Sets>
    </Requirements>
    <Hosts>
      <Host xsi:type="MailHost">

        <DesktopFormFactor>
          <FunctionFile resid="functionFile" />

          <ExtensionPoint xsi:type="AppointmentOrganizerCommandSurface">
            <OfficeTab id="TabDefault">
              <Group id="myAppBookingGroup">
                <Label resid="myAppGroupLabel" />
                <Control xsi:type="Button" id="btnBookSpace">
                  <Label resid="btnBookSpaceLabel" />
                  <Supertip>
                    <Title resid="btnMouseOverBookSpaceTitle" />
                    <Description resid="btnMouseOverBookSpaceDesc" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="icon16" />
                    <bt:Image size="32" resid="icon32" />
                    <bt:Image size="80" resid="icon80" />
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="bookingSpaceUrl" />
                  </Action>
                </Control>
              </Group>
            </OfficeTab>
          </ExtensionPoint>

        </DesktopFormFactor>

**Comment by exextoc** [comment]
Hi Rodrigo,

You need to add a MobileFormFactor node in the VersionOverrides v1.1 section. Please take a look here for more details:

[https://docs.microsoft.com/en-us/outlook/add-ins/add-mobile-support](https://docs.microsoft.com/en-us/outlook/add-ins/add-mobile-support)

**Comment by rodrigoguariento** [comment]
Cool, 

I wrote the following, it works but at Outlook Mobile for Android, no one icon is displayed. What I made wrong?

        <MobileFormFactor>
          <FunctionFile resid="residUILessFunctionFileUrl" />
          <ExtensionPoint xsi:type="MobileMessageReadCommandSurface">
            <Group id="mobileMsgRead">
              <Label resid="myAppGroupLabel" />
              <Control xsi:type="MobileButton" id="TaskPaneBtn">
                <Label resid="btnBookSpaceLabel" />
                <Icon xsi:type="bt:MobileIconList">
                  <bt:Image size="25" scale="1" resid="mob25" />
                  <bt:Image size="25" scale="2" resid="mob25" />
                  <bt:Image size="25" scale="3" resid="mob25" />

                  <bt:Image size="32" scale="1" resid="mob32" />
                  <bt:Image size="32" scale="2" resid="mob32" />
                  <bt:Image size="32" scale="3" resid="mob32" />

                  <bt:Image size="48" scale="1" resid="mob48" />
                  <bt:Image size="48" scale="2" resid="mob48" />
                  <bt:Image size="48" scale="3" resid="mob48" />
                </Icon>
                <Action xsi:type="ShowTaskpane">
                  <SourceLocation resid="bookingSpaceUrl" />
                </Action>
              </Control>
            </Group>
          </ExtensionPoint>
        </MobileFormFactor>

**Comment by rodrigoguariento** [comment]
Solved by myself! Thank you all.

See: [https://github.com/OfficeDev/outlook-add-in-command-demo/blob/master/command-demo-manifest.xml](https://github.com/OfficeDev/outlook-add-in-command-demo/blob/master/command-demo-manifest.xml)
