### ISSUE TITLE
Multiline ADDIN fields in Word Online are broken

### ISSUE THREAD

**Issue by adomasven** [OfficeDev/office-js#3621]
Word Online

If you insert a multiline ADDIN field into Word Online it is impossible to remove it, or set a paragraph style (greyed out button) for it.

```js
await Word.run(async (context) => {
	const selection = context.document.getSelection().getRange();
	const field = selection.insertField('Replace', 'Addin');
	field.code = `ADDIN test`;
	field.result.insertText("Test\nTest 2nd line", "Replace");
	await context.sync();
});
```

The contents of the field are still editable in the editor, so if you remove the newline symbol, it becomes removable and you can apply a paragraph style to it.

This is also reproducible by inserting a single-line field, then putting the cursor inside it and pressing Enter/Return on the keyboard.

**Comment by xiruatms** [comment]
@adomasven , thanks for reporting this. We're still working on supporting ADDIn fields with multilines, removing and setting styles are both in progress. They will be rolled out to production soon.

**Comment by adomasven** [comment]
You can now remove a multiline field in Word Online, but setting paragraph style either via WordJS or the Word Online editor still doesn't work.

**Comment by xiruatms** [comment]
@adomasven , the fix is now pushing to production, will you please take a try whether it's working for you now？
