### ISSUE TITLE
Office.MessageCompose method getSharedPropertiesAsync does not return owner property

### ISSUE THREAD

**Issue by manaunl** [OfficeDev/office-js#3622]
# Provide required information needed to triage your issue
Office.MessageCompose method getSharedPropertiesAsync does not return owner property, see [documentation](https://learn.microsoft.com/en-us/javascript/api/outlook/office.sharedproperties?view=outlook-js-preview#outlook-office-sharedproperties-owner-member) 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 1.8
* Operating System: macOs
* Browser (if using Office on the web): Chrome
 
## Expected behavior

Method [getSharedPropertiesAsync](https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#outlook-office-messagecompose-getsharedpropertiesasync-member(2)) should return `owner` property

## Current behavior

Method [getSharedPropertiesAsync](https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#outlook-office-messagecompose-getsharedpropertiesasync-member(2)) does not return `owner` property

<img width="1138" alt="Screenshot 2023-08-29 at 17 16 59" src="https://github.com/OfficeDev/office-js/assets/1925146/1c563837-affe-47db-a891-170fbeff7461">

## Steps to reproduce

1. Open a shared mailbox
2. Try to trigger the method `getSharedPropertiesAsync` and see the result
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

This issue affects our customers, they are not able to send messages using shared mailboxes. Please fix this ASAP.

## Useful logs

- [x] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by manaunl** [comment]
@exextoc This issue is a major problem for our customers who use shared mailboxes with an add-in. We request an urgent fix to this issue.

**Comment by exextoc** [comment]
This issue is fixed. Closing, please reopen if you still see the problem.
