### ISSUE TITLE
RichApi.Error ApiNotFound is thrown after calling shapes.load('items');

### ISSUE THREAD

**Issue by paweloo** [OfficeDev/office-js#3624]
# Provide required information needed to triage your issue
This issue is reproducible on PowerPoint for Web. 
After calling `shapes.load('items');` and `await context.sync();`, `RichApi.Error ApiNotFound` is thrown.
I did not encounter any issues with these requests earlier and I did not make any changes in my code, so this behaviour must be caused by some PowerPoint update.

This can be also reproduced in the Script Lab by choosing 'Get, set, load, and save shapes', then running the script and clicking 'Create Shapes' and 'Select first two shapes on the slide'.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: 16.0.16826.40503
* Operating System: Mac OS Ventura
* Browser (if using Office on the web): Google Chrome 116
 
## Expected behavior

Calling `shapes.load('items');` and `await context.sync();` should not throw an Rich API error.

## Current behavior

Calling `shapes.load('items');` and `await context.sync();` throws an Rich API error.

## Steps to reproduce

1. Open Script Lab in PowerPoint for Web
2. Choose 'Get, set, load, and save shapes' script
3. Select 'Create Shapes'
4. Select 'Select first two shapes on the slide'.
Error is thrown
<img width="339" alt="Screenshot 2023-08-29 at 17 39 52" src="https://github.com/OfficeDev/office-js/assets/31667799/cefe9420-a60b-4b3a-a11a-e45a360fb27d">

## Context

It seriously affects my app as it is not able to get data about added images on the slide, therefore I'm not able to track objects added to the slide

## Useful logs

- [ ] Console errors
- [X] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ghaskins99** [comment]
Hello, I get the same `RichApi.Error: ApiNotFound`, but when calling `slide.load("shapes")` with `await context.sync()`.

Please advise if I should create a separate Issue for this.

Note that all of the below works as expected on PowerPoint for Mac `16.76.1 (23082301)`

## Environment
Office on the web, PowerPoint, build 16.0.16827.40519
MacOS Ventura 13.5
Chrome 116.0.5845.140


## Expected behaviour
calling `slide.load("shapes")` should not error

## Current behaviour
it throws the `RichApi.Error: ApiNotFound`

## Steps to reproduce
1. create a ppt addin, with react, have a button that when clicked runs the entirety of the code below:

```ts
// Minimal sample of the code that runs up until error, rewritten into one function
export const testLoadShapeCollection = async () => {
    OfficeExtension.config.extendedErrorLogging = true;

    const currentSlideIdx = await new Promise<number>((resolve, reject) => {
        Office.context.document.getSelectedDataAsync(
            Office.CoercionType.SlideRange,
            (asyncResult: Office.AsyncResult<{ slides: { id: number; title: string; index: number }[] }>) => {
                try {
                    if (asyncResult.status === Office.AsyncResultStatus.Failed) {
                        reject(asyncResult.error.message);
                    } else {
                        resolve(asyncResult.value.slides[0].index - 1);
                    }
                } catch (err) {
                    reject(err);
                }
            },
        );
    });

    console.log('CURRENT SLIDE IDX', currentSlideIdx); // result -> 0

    await PowerPoint.run(async (context) => {
        try {
            const slides = context.presentation.slides;
            slides.load('items');
            await context.sync();
            const slide = slides.items[currentSlideIdx];
            slide.load('shapes'); // supposedly the offending line
            await context.sync(); // 98:13 (see console error) is the start of this line
            const shapes = slide.shapes;
            shapes.load('items');
            await context.sync();
            
            // doesn't matter what we do here, since we never get here :) 
            console.log(JSON.stringify(shapes, null, 2));
        } catch (error) {
            console.log(JSON.stringify(error, null, 2));
            throw error;
        }
    });
};
```
2. See the error below: 
  - Error thrown:
```
Uncaught (in promise) RichApi.Error: ApiNotFound                      powerpoint-web-16.00.js:26 
    at new n (powerpoint-web-16.00.js:26:312973)
    at i.processRequestExecutorResponseMessage (powerpoint-web-16.00.js:26:377589)
    at powerpoint-web-16.00.js:26:375651
    at async helpers.ts:98:13
    at async testLoadShapeCollection (helpers.ts:91:5)
 ```
 
   - Error object logged:
```json
{
  "name": "RichApi.Error",
  "code": "ApiNotFound",
  "traceMessages": [],
  "innerError": null,
  "debugInfo": {
    "code": "ApiNotFound",
    "message": "ApiNotFound",
    "errorLocation": "Shape.zorderPosition",
    "statement": "slide.load([\"shapes\"]);",
    "surroundingStatements": [
      "var root = context.root;",
      "var slides = root.slides;",
      "var slide = slides.getItem(...) /* originally getItem(...) */;",
      "// >>>>>",
      "slide.load([\"shapes\"]);",
      "// <<<<<"
    ],
    "fullStatements": [
      "var root = context.root;",
      "var slides = root.slides;",
      "var slide = slides.getItem(\"258#4261546900\") /* originally getItem(\"258#4261546900\") */;",
      "slide.load([\"shapes\"]);"
    ]
  },
  "httpStatusCode": 500
}
```
 
 ## Context
 This blocks our app from fully functioning, since after adding an object we would like to add tags to it and track other properties, handle selection, etc.
 
 ## Useful logs
- [x] Console errors
- [x] Code sample

**Comment by paweloo** [comment]
@ghaskins99 Hi, I'm pretty sure that this is the same root cause. I'm not sure if opening new issue will make things faster, I guess we'll just have to wait for Microsoft to respond to this one.

**Comment by paweloo** [comment]
@ghaskins99 It looks like this issue is resolved, seems to be working again in 16.0.16830.40518. Please confirm if that's the case and I'll close this ticket

**Comment by ghaskins99** [comment]
@paweloo looks like I don't get this RichApi.Error anymore either 👍 

Once, I got 

```
RichApi.Error: The property 'items' is not available. Before reading the property's value, call the load method on the containing object and call "context.sync()" on the associated request context.
    at new n (powerpoint-web-16.00.js:26:312973)
    at n.createPropertyNotLoadedException (powerpoint-web-16.00.js:26:415375)
    at n.throwIfNotLoaded (powerpoint-web-16.00.js:26:415118)
    at n.get [as items] (powerpoint-web-16.00.js:26:647456)
    at main.d408f75c64428952.js:1:1517662
    at async J (main.d408f75c64428952.js:1:1522262)
    at async Array.<anonymous> (9218.5891b00b7e69935d.js:1:4972)
```

when the corresponding code it's complaining about is:
```
return PowerPoint.run(async function (context) {
        const selected = context.presentation.getSelectedShapes();
        selected.load('items');
        await context.sync();

        const shape = selected.items[0];
```

so that's kind of weird ..., but that's not this issue! (and it only happened once)

**Comment by EsterBergen** [comment]
@ghaskins99  and @paweloo - Wanted to check in and see if you're still experiencing the issue in the original post.

**Comment by ghaskins99** [comment]
@EsterBergen it seems to continue to be functioning correctly since the last update posted here!

**Comment by EsterBergen** [comment]
Ok excellent! Will mark this as closed then. Thank you @ghaskins99!
