### ISSUE TITLE
Taskpane Outlook add-in shows blank page and opens new Edge window on open

### ISSUE THREAD

**Issue by sebammon** [OfficeDev/office-js#3627]
## Problem description

We developed a task-pane outlook add-in for a client, however the add-in is not loading at all.

When the user clicks on the add-in button in the ribbon, the right task-pane opens but it shows a blank page in the task-pane in the outlook application. Additionally, it opens an MS Edge window with the address of the `SourceLocation`: `https://cdn.domain.com/add-in/example/taskpane.html?_host_Info=Outlook$Win32$16.02$en-US$$$$0`.

I've inspected the developer tools in the outlook application; there are no (error or info) logs - they are empty, no network requests are made, and no HTML is rendered - it's blank `<head></head><body></body>` tags. This seems strange to me.

However, the add-in works perfectly in the Outlook Web Client for that same user. It also works perfectly for other people _outside of the organization_ on Windows and Mac.

My suspicions is that some setting must be missing from the manifest, or some settings needs to be enabled for the organization, but I am simply have no idea.

The affected user has the following Environment:
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2302 Build 16.0.16130 64-bit
* Operating System: Windows 11
* Browser (if using Office on the web): Edge
 
## Expected behavior

I expect the add-in to load in the desktop application as it does in the web application.

## Current behavior

As described above, the add-in shows a blank page in the task-pane and opens an Edge window with the source location URL.

## Steps to reproduce

I am currently unable to reproduce the issue, but would greatly appreciate any assistance in analyzing the issue further.

For your info, the manifest can be seen below:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
           xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xsi:type="MailApp">
    <Id>....</Id>
    <Version>1.0.0.0</Version>
    <ProviderName>name</ProviderName>
    <DefaultLocale>en-US</DefaultLocale>
    <DisplayName DefaultValue="name"/>
    <Description DefaultValue="..."/>
    <IconUrl DefaultValue="https://cdn.domain.com/add-in/example/assets/icon-64.png"/>
    <HighResolutionIconUrl DefaultValue="https://cdn.domain.com/add-in/example/assets/icon-128.png"/>
    <SupportUrl DefaultValue="https://domain.com"/>
    <AppDomains>
        <AppDomain>https://sub.domain.com</AppDomain>
    </AppDomains>
    <Hosts>
        <Host Name="Mailbox"/>
    </Hosts>
    <Requirements>
        <Sets>
            <Set Name="Mailbox" MinVersion="1.8"/>
        </Sets>
    </Requirements>
    <FormSettings>
        <Form xsi:type="ItemRead">
            <DesktopSettings>
                <SourceLocation DefaultValue="https://cdn.domain.com/add-in/example/taskpane.html"/>
                <RequestedHeight>250</RequestedHeight>
            </DesktopSettings>
        </Form>
    </FormSettings>
    <Permissions>ReadWriteMailbox</Permissions>
    <Rule xsi:type="RuleCollection" Mode="Or">
        <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"/>
    </Rule>
    <DisableEntityHighlighting>false</DisableEntityHighlighting>
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides"
                      xsi:type="VersionOverridesV1_0">
        <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1"
                          xsi:type="VersionOverridesV1_1">
            <Requirements>
                <bt:Sets DefaultMinVersion="1.8">
                    <bt:Set Name="Mailbox"/>
                </bt:Sets>
            </Requirements>
            <Hosts>
                <Host xsi:type="MailHost">
                    <DesktopFormFactor>
                        <ExtensionPoint xsi:type="MessageReadCommandSurface">
                            <OfficeTab id="TabDefault">
                                <Group id="msgReadGroup">
                                    <Label resid="GroupLabel"/>
                                    <Control xsi:type="Button" id="msgReadOpenPaneButton">
                                        <Label resid="TaskpaneButton.Label"/>
                                        <Supertip>
                                            <Title resid="TaskpaneButton.Label"/>
                                            <Description resid="TaskpaneButton.Tooltip"/>
                                        </Supertip>
                                        <Icon>
                                            <bt:Image size="16" resid="Icon.16x16"/>
                                            <bt:Image size="32" resid="Icon.32x32"/>
                                            <bt:Image size="80" resid="Icon.80x80"/>
                                        </Icon>
                                        <Action xsi:type="ShowTaskpane">
                                            <SourceLocation resid="Taskpane.Url"/>
                                            <SupportsPinning>true</SupportsPinning>
                                        </Action>
                                    </Control>
                                </Group>
                            </OfficeTab>
                        </ExtensionPoint>
                    </DesktopFormFactor>
                </Host>
            </Hosts>
            <Resources>
                <bt:Images>
                    <bt:Image id="Icon.16x16" DefaultValue="https://cdn.domain.com/add-in/example/assets/icon-16.png"/>
                    <bt:Image id="Icon.32x32" DefaultValue="https://cdn.domain.com/add-in/example/assets/icon-32.png"/>
                    <bt:Image id="Icon.80x80" DefaultValue="https://cdn.domain.com/add-in/example/assets/icon-80.png"/>
                </bt:Images>
                <bt:Urls>
                    <bt:Url id="Taskpane.Url" DefaultValue="https://cdn.domain.com/add-in/example/taskpane.html"/>
                </bt:Urls>
                <bt:ShortStrings>
                    <bt:String id="GroupLabel" DefaultValue="name"/>
                    <bt:String id="TaskpaneButton.Label" DefaultValue="..."/>
                </bt:ShortStrings>
                <bt:LongStrings>
                    <bt:String id="TaskpaneButton.Tooltip"
                               DefaultValue="..."/>
                </bt:LongStrings>
            </Resources>
        </VersionOverrides>
    </VersionOverrides>
</OfficeApp>
```

**Comment by Adrian-MSFT** [comment]
Hi @sebammon ,

Is this reproducible in any other versions of Outlook? How many users are affected? I wasn't able to reproduce this issue, so any more info would help.

**Comment by manuelsidler** [comment]
I have the same problem with Outlook on Windows (Version 2308, Build 16731.20234). The add-in works fine on Outlook for Mac and Web.

@sebammon did you find the problem?

**Comment by manuelsidler** [comment]
We were able to solve the issue. It was a misconfiguration on our web server. The web server redirected our source location to http://domain/index.html, which, in turn, shifted to https://domain/index.html. A workaround for that misconfiguration was adding a trailing slash to the source location in the manifest (https://domain/ instead of https://domain).

I am trying to understand why Outlook on Windows behaves differently than Mac and Web.

**Comment by sebammon** [comment]
@Adrian-MSFT, only a handful of users were affected.

@manuelsidler and @Adrian-MSFT in our case the issue seems to have been related to a VPN / Firewall problem. The same users who reported the issue were able to use our add-in on their home network, but not on the corporate network.

**Comment by Adrian-MSFT** [comment]
Hi @sebammon, Thanks for letting me know. It sounds like a solution to the VPN/firewall problem was found from your side, so I will close this.
