### ISSUE TITLE
outlook web: displayMessageFormAsync destroys item object

### ISSUE THREAD

**Issue by DNSVGR** [OfficeDev/office-js#3628]
# Provide required information needed to triage your issue

We are developing an add-in for compose mode. Some of its features require to open items from the current mailbox. But we are having an issue with displayMessageFormAsync. It corrupts an item object of the current mail item.

## Your Environment

* Platform: Office on the web
* Host: Outlook
* Office version number: ______
* Operating System: Windows 10 Version 22H2, mac os ventura 13.5
* Browser (if using Office on the web): Edge Version 116.0.1938.62
 
## Expected behavior
The item object should contain valid information about the current mail even after calling displayMessageFormAsync.

## Current behavior
After calling displayMessageFormAsync on the current mail item and restarting the add-in, this field is undefined.

## Steps to reproduce
1. Sign in to Outlook Online using Edge.
2. Select a mail.
3. Open add-in and execute the code below: 
```
const id = Office.context.mailbox.item.itemId;
Office.context.mailbox.displayMessageFormAsync(id, (result => {
    console.log(result)
}));
```
5. Close the addin and open it again
6. Execute this peace of code
```
const id = Office.context.mailbox.item.itemId;
console.log(id);
```
7. the error is thrown:
`Uncaught TypeError: Cannot read properties of undefined (reading 'itemId')`

Also it can be usefull to mention that you can open any addin after step 5 and it would have the same problem.

## Link to live example(s)

# Provide additional details
After step 3 some methods stop working. For example calling displayMessageFormAsync again or getSelectedItemsAsync results with status 'faild'.
This method works great in desktop versions of Outlook.

If you need any additional information, please let me know.

**Comment by exextoc** [comment]
@DNSVGR We tried reproducing this issue. After step 3 a pop up window opens up with the selected mail. At step 5, it is not clear which window do you close. Please clearly capture all the steps to help us reproduce the issue.

**Comment by DNSVGR** [comment]
ok.
1. sign in to outlook using edge
2. select a mail
3. open add-in and execute the code from original post(step 3)
4. close the window that was opened after previous step(pop up window)
5. Close the addin and open it again
6. try to execute code from step 6 of my previous post
7. the error is thrown

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point
Internal tracking id: Office: 3916333

**Comment by exextoc** [comment]
We have fixed this bug and the fix should be available in latest Outlook Web.
