### ISSUE TITLE
Roaming settings get lost after refresh although they were saved

### ISSUE THREAD

**Issue by rbsdc** [OfficeDev/office-js#3629]
When setting the RoamingSettings, saving them, and then refreshing the page, the saved RoamingSettings get lost. 

## Your Environment
host: Outlook
version: 16.0.16626.20170
platform: PC
 
## Expected behavior
The roaming settings should be correctly loaded after a refresh.

## Current behavior
The roaming settings get lost after a refresh.

## Steps to reproduce
The standard "My Templates" Addin can also reproduce this issue.
1. Open the "My Templates" taskpane
2. Click on "+ Template" to create a new template
3. Give it a name and text.
4. Click on "Save"
5. Refresh the Page (either via context menu or F5) - the new template is now vanished.
6. Close the taskpane via the x-Button at the top-right corner
7. Reopen the "My Templates" taskpane
8. The previously saved template is now visible
9. Delete the template
10. Create a new template with the same name but different text
11. Save
12. Refresh - the old template reappears

## Link to live example(s)
See a gif example:
[https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGJtdjlmdXJ5cmlmdjVlZGNtN28zbWtqb2t2c2lqbjF4bGcwaGxhYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NduJ0H9YgwIa9yYKXu/giphy.gif](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOGJtdjlmdXJ5cmlmdjVlZGNtN28zbWtqb2t2c2lqbjF4bGcwaGxhYyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/NduJ0H9YgwIa9yYKXu/giphy.gif)

## Context
In the addin I am developing, this behavior is even worse: when 1. save settings 2. close taskpane 3. open taskpane, then it works as expected. However, if 1. save settings 2. refresh  3. close taskpane 4. open taskpane , then the saved settings are lost (or are in the previous state before saving).

**Comment by zhngx1** [comment]
@rbsdc, this is actually by design. Follow the link to our documentation: https://learn.microsoft.com/en-us/javascript/api/outlook/office.roamingsettings?view=outlook-js-preview#remarks

The RoamingSettings object is initialized from the persisted storage only when the add-in is first loaded. For task panes, this means that it's only initialized when the task pane first opens. If the task pane navigates to another page or reloads the current page, the in-memory object is reset to its initial values, even if your add-in has persisted changes. The persisted changes will not be available until the task pane (or item in the case of UI-less add-ins) is closed and reopened.

When set and saved through Outlook on Windows or Mac, these settings are reflected in Outlook on the web only after a browser refresh.

**Comment by rbsdc** [comment]
@zhngx1 Thank you. But to be honest, this is clearly a design flaw that should be addressed. If the user hits F5 in any add-in using the RoamingSettings, this will lead to highly inconsistent and unexpected behavior. 

Furthermore, as I describe in my comment in the "Context" section, the RoamingSettings get *actually* lost after a refresh, at least in some circumstances. This is not covered by your reply or the documentation you referred to.

**Comment by timwan10** [comment]
A work item has been opened to address this and put on the backlog. 

Behind the scenes, what is happening is that the roamingSettings are loaded at first when the add-in is loaded. When you do a save, the new settings ARE saved to the client/server. 

However if the page is refreshed, then the settings from the initial load are reloaded. This makes it appear as if the settings have been lost. At this point, if you closed and reOPENED, the add-in then we would hit the client/server for the settings again, and you would see the saved settings. 

This isn't great however, as after the refresh, you have no idea if you are looking at updated settings or not, and could even overwrite the settings that you had already saved. 

For this reason, the workaround right now is to avoid refreshing the page until a fix can be implemented.

The fix has been put in the backlog, but I don't have a time table to share.

**Comment by JMMM77** [comment]
@rbsdc have you managed to find a consistent way of saving and getting the roaming settings after they have been saved or found an alternative to this? I am experiencing the same issues where one of my add-ins isn't able to retrieve any roaming settings it saved even though it was able to get it before refresh, while another add in I have is sometimes able to retain it.

**Comment by rbsdc** [comment]
> @rbsdc have you managed to find a consistent way of saving and getting the roaming settings after they have been saved or found an alternative to this? I am experiencing the same issues where one of my add-ins isn't able to retrieve any roaming settings it saved even though it was able to get it before refresh, while another add in I have is sometimes able to retain it.

Presently, the only way to handle this problem, it seems, is to warn the user in the manual that there might be some inconsistent behavior when refreshing the add-in.

**Comment by rbsdc** [comment]
@JMMM77 Presently, the only way to handle this problem, it seems, is to warn the user in the manual that there might be some inconsistent behavior when refreshing the add-in.

**Comment by timwan10** [comment]
This issue should be fixed in Win32 versions of OLD outlook (not new outlook). In build 16.0.17126.20132. 

there is no update on when this issue will be fixed with other versions of Outlook.
