### ISSUE TITLE
Script Lab Add-In Loading Error in New Outlook for Desktop

### ISSUE THREAD

**Issue by Scratchu** [OfficeDev/office-js#3631]
Script Lab Add-In Loading Error in New Outlook for Desktop

Platform: Outlook for Desktop

Version: 1.2023.727.100

Description:
I am actively using the Script Lab Add-In with Outlook. While the add-in functions correctly in the classic Outlook Desktop, I am facing an issue with the New Outlook for Desktop.

Steps to Reproduce:

1. Open New Outlook for Desktop.
2. Launch the Script Lab Add-In.
3. Attempt to run any Sample using the 'Run' button (in order to run the code snippet).

Expected Result:
The sample should run without any hitches.

Actual Result:
Upon clicking 'Run', it starts to load, taking approximately 1 minute, and then results in an error (as shown below).

![Screenshot 2023-08-07 172358](https://github.com/OfficeDev/script-lab/assets/141650016/1b3290be-6434-49bc-8396-6c13beb855bb)

Additional Information:

This issue seems exclusive to the New Outlook for Desktop.
No similar issues noted when using the classic Outlook Desktop version.
Is there a known resolution for this or any troubleshooting steps you would recommend?

**Comment by ElizabethSamuel-MSFT** [comment]
@Scratchu Thanks for letting us know about this. I'm going to transfer this issue to the office-js product repo for the Outlook add-ins engineering team to investigate.

**Comment by exextoc** [comment]
@Scratchu We are not able to reproduce this in our setup. We are able to open code editor and also able to run the default script available in the addin. 
Could you collect and share the following:
1. Client version, you can get it via
View -> settings -> General ->About outlook
2. Network logs from boot till repro.
3. console trace of time when you launch addin.
4. Add the steps that you do before launching the addin,

**Comment by exextoc** [comment]
@Scratchu - Can you please confirm the repro steps? Want to understand if you are seeing when the mail is in the reading pane, or if the mail window is opened as a new window outside the reading pane (projection poput window)
