### ISSUE TITLE
Fail to open external Link correctly defined in "helpurl" property for custom function

### ISSUE THREAD

**Issue by Michaellu1983** [OfficeDev/office-js#3634]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:  Office on the web
* Host [Excel, Word, PowerPoint, etc.]:  Excel Online
* Office version number:  16.0.16821.42303
* Operating System:  Windows 11
* Browser (if using Office on the web):  Chrome 116.0.5845.141 (Official Build) (64-bit)
 
## Expected behavior

The help url is shown in the pop up dialog.

## Current behavior

The help document fail to open correct web site when we try to open the help in excel online. Only a pop up dialog says,  "Sorry, the page you're looking for can't be found. "

## Steps to reproduce

1.  Click "Home" tab and click "Add-ins" button, then click "More Add-ins"
2.  Click "Upload My Add-in" and select the excel addin manifest file
3.  Click "Formula" tab and click "Insert Function" and select a custom function, click the hyperlink "Learn more"

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- ![image](https://github.com/OfficeDev/office-js/assets/143773213/be840fe0-743c-45ed-8066-bf7c3599ab62)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Michaellu1983** [comment]
We follow the MS document to provide help information by setting "helpurl" in functions.json. We test the excel addin in Excel desktop, the help document can be opened in chrome.  
I attach a example in the functions.ts below.  
```
/**
 * Summary Report
 * @customfunction
 * @param formula String
 * @param cellRefs String Array
 * @return String to display
 * @helpurl https://docs.infor.com/qanda/2023.x/en-us/qaaddin/default.html?helpcontent=tea1689687038825.html
 */
function QNA_SR(formula: string, cellRefs: Array<string>): any {
  return getDisplayValue(formula);
}
```

**Comment by Michaellu1983** [comment]
@Rick-Kirkham The issue has been raised over 2 weeks.  Is there any plan to fix or anything need I provide with ?

**Comment by ZYUN-MSFT** [comment]
Hi @Michaellu1983 ,

Sorry for the late reply, I'm re-directing issue this to the right owner team. We will contact you when we need more information to provieded. And we will update here once we got the feed back.

Thanks for your patience.

**Comment by rundongmsft** [comment]
Hi @Michaellu1983, thanks for reporting this issue. And the issue has been confirmed and tracked as ADO#8369458 in our backlog.

**Comment by Michaellu1983** [comment]
@rundongmsft Hi,  Can you tell me something about the progress of the issue ?

**Comment by theangkko** [comment]
As I recall, this used to work well.
It stopped working at some point last year (in 2023), and I've been watching the issue list and waiting, expecting it to be fixed soon, but it still doesn't seem to be working.

If the way it works has changed, I'd like to see an update to the documentation about it.


![image](https://github.com/OfficeDev/office-js/assets/75212211/d0ec3c24-900b-40e9-8e4b-899f74abf43f)

<img width="604" alt="image" src="https://github.com/OfficeDev/office-js/assets/75212211/21d711d0-790c-4a19-a5f3-db481caaaf89">

<img width="713" alt="image" src="https://github.com/OfficeDev/office-js/assets/75212211/2b05c0f5-7037-41bd-9e5c-b89522d2d3af">




<br/><br/><br/>
https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json-autogeneration

![image](https://github.com/OfficeDev/office-js/assets/75212211/b4e7770b-889d-4f9d-9e24-14037dce0049)

**Comment by rundongmsft** [comment]
We have identified this issue as a regression. We are already formulating a plan to address and fix it.

**Comment by udayaskumar** [comment]
Hi, any update on this issue. We are trying to publish our add-in office store and its been rejected with one of the reason of help pages are missing and we have been facing same issues of "Sorry, the page you’re looking for can’t be found.". I could see in network traffic, help page url being picked in HelpId parameter. 
Any info on this would be helpful.  Thanks in advance.

**Comment by SiruiSun-MSFT** [comment]
Hi @udayaskumar, Thanks for your waiting here! However, we are still active working on the issue, which is not a simple bug level fix and may take somehow longer time. We will back to you ASAP when we get this issue fixed. Please stay tuned. Thanks for your patience!

**Comment by XuanZhouMSFT** [comment]
Hi @Michaellu1983 @theangkko @udayaskumar, Thanks for the waiting. We already released a fix for the help link in latest production environment. Please have a try and let us know if you still have problems
