### ISSUE TITLE
Custom plugin task pane header is not displaying complete text in Web Addin

### ISSUE THREAD

**Issue by Tarunsharmaukg** [OfficeDev/office-js#3636]
Our application name is not showing properly in task pane header is trimmed by Outlook in Web Addin. 
Is there a way to show the complete text in the header?
![image](https://github.com/OfficeDev/office-js/assets/121292370/4c2b2c18-7cfa-42ec-a854-5978ee554e70)

**Comment by Rick-Kirkham** [comment]
The default width of a task pane will show only 30 characters. The rest will be truncated. I don't think there is any way for the add-in developer to control this.

**Comment by Tarunsharmaukg** [comment]
Is there any option to add tooltip adjacent to pin icon in the task pane? or
Could we wrap the text instead of truncate it? or
Do we have some options to open task pane with maximum width?

**Comment by millerds** [comment]
Currently this is not supported in Outlook.  We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
