### ISSUE TITLE
Add-in taking a long time to load

### ISSUE THREAD

**Issue by sami-romdhana** [OfficeDev/office-js#3637]
Some users in our company are experiencing problems using the Outlook Desktop client and trying to use add-ins while composing new emails. Whereas the new Outlook client and the web client load them perfectly, the old client takes a very long time (1 minute or more) to load the content, if it ever manages to do so. Any add-ins do load if they can be launched from the inbox view.
 
This manifests as a white pane, with a central spinner adorned with a "Loading..." label.

This happens for our add-in as well as any other Office.js add-in.

UPDATE: It seems that some form of error in one of our add-ins produces the time delay. We have yet to investigate the cause but it doesn't seem normal that one add-in can halt every other add-in in Outlook.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook ("old" version)
* Office version number: various versions and channels, on my computer it happens using 2309 16.0.16827.20000 Beta Channel
* Operating System: Windows 10 or 11
 
## Expected behavior

Add-ins load

## Current behavior

Add-ins and their panes do not load or do so after an extensive wait (minimum 40s)

## Steps to reproduce

1. Open "old" Outlook (add-ins do work in the new version or online)
2. Open a new draft email
3. Open the taskpane an add-in OR wait for "on compose" events

## Context

All our colleagues are using our add-in for signatures within Outlook and they either can't or are faced with extreme delays. Most of them are resorting to copy and pasting from old emails.

## Useful logs

![image](https://github.com/OfficeDev/office-js/assets/64911368/71651a95-df4a-44b4-80c0-79eca3376cca)

**Comment by ndeleuze** [comment]
@sami-romdhana thank you for reaching out with this issue.

To clarify, you have one add-in that takes an extended amount of time to load from the taskpane due to some error on your end. But other add-in are also having issues loading from the taskpane on new compose messages. And this seems to only happen for the Outlook desktop client. Is that correct?

Does the add-in that is experiencing the loading delay use event-based actions? Like OnNewMessageCompose?

**Comment by sami-romdhana** [comment]
Hello @ndeleuze 

Yes, that is correct, all affected add-ins use the OnNewMessageCompose event. They don't seem affected when they can be opened manually in some other window than the "new message" one.

**Comment by ndeleuze** [comment]
@sami-romdhana when the add-in experiencing long load times is removed, are the other event-based add-ins loading as expected?

**Comment by sami-romdhana** [comment]
@ndeleuze Yes

**Comment by ndeleuze** [comment]
@sami-romdhana If one add-in is not loading correctly then it blocks the shared queue for the other add-ins to load. Do you have any clues as to what is causing the blocking add-in from loading? Is this new event-based functionality that you are trying to add?

**Comment by omar-pk** [comment]
We are experiencing this same issue when using event based activation for onNewMessageCompose or onMessageCompose. Even if they are hooked up to empty functions, or just a function that calls event.completed, simply having them exist in the manifest causes the issue. Removing these events from the manifest fixes the issue.

I am thinking it might relate to how runtimes are configured, I am working to find a solution this week - if I have any updates I will share here.

**Comment by sami-romdhana** [comment]
@ndeleuze In our case, what hangs the queue is using JavaScript features that are unsupported by the Hermes engine fork underneath or just plain syntax failures. Simple example: creating a class inheriting EventTarget.

**Comment by ndeleuze** [comment]
@sami-romdhana it sounds like you have found the issue that is causing the add-in to not load correctly, which blocks the shared queue for the other add-ins to load.

I will proceed to close this post if you don't have other questions/concerns.
