### ISSUE TITLE
OnMessageSend being blocked on Windows but not on web

### ISSUE THREAD

**Issue by Jonas-PRF** [OfficeDev/office-js#3639]
When developing the add-in for Outlook on Windows the OnMessageSend eventhandler handles the event properly and the mail is sent. This behaviour is the same for the Mac client and OWA (even in production). However, when the application is installed, the event times-out on Windows.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **PC desktop**
* Host [Excel, Word, PowerPoint, etc.]: **Outlook**
* Office version number: **2209**
* Operating System: **Windows 11 22621.2134**
 
## Expected behavior

1. The event times-out on both Mac and on Windows
2. The event is correctly handled by both clients

## Current behavior

The event only times-out on Windows clients.

## Steps to reproduce

1. [The manifest](https://gist.github.com/Jonas-PRF/b0fe3e8e8666467083bda263940b5d22)
2. [The launchevent for Mac + web](https://gist.github.com/Jonas-PRF/7812f6c44f46eec1736c89ac6f499e5c)
3. [The launchevent for Windows](https://gist.github.com/Jonas-PRF/b3b902f6b27e52b64075a55994309048)

## Context

We are unable to distribute our developed add-in with the help of a storelisting or a shareable link.

## Useful logs

![Schermafbeelding 2023-09-05 130925](https://github.com/OfficeDev/office-js/assets/144120822/f4bfcb0b-8937-4113-ad28-9b5b10a7752a)
![Schermafbeelding 2023-09-05 131013](https://github.com/OfficeDev/office-js/assets/144120822/26ae21f6-5190-48d8-a9f9-e1ab79ec1e82)

**Comment by ndeleuze** [comment]
@Jonas-PRF Thanks you for reaching out with this issue.

Just to clarify, when you sideload the add-in the OnMessageSend event handler handles the event properly and the mail is sent, but when installing the add-in through the store the add-in times out. Is this correct, of does sideloading the add-in still create this issue?

**Comment by Jonas-PRF** [comment]
@ndeleuze 
When I sideload the add-in for the development it works. From the moment I build the add-in it stops working. It's the same when I sideload it or install it through the store.

**Comment by ndeleuze** [comment]
@Jonas-PRF are you able to see any of your console logs from onMessageSendHandler when installing through the store?

Here is a guide for runtime logging: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging
