### ISSUE TITLE
getActiveparagraphOrNull() always returns null

### ISSUE THREAD

**Issue by stephenb159** [OfficeDev/office-js#364]
I am unable to make getActiveparagraphOrNull() (in the application class) EVER return a paragraph type other than null?
I am thinking this may be a bug in the API, but wanted to check to see if there was something wrong. I have no problem getting the active section, page, or outline. Take this code snippet:

function currentparagraph(){
OneNote.run(function (context) {
    var paragraph = context.application.getActiveParagraphOrNull();
    console.log(paragraph);
return context.sync()
});
}

The object returned in the console always has IsNull set to true. I cannot figure why it will not pick up on the current paragraph. Any thoughts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09eae46f-d010-f411-9ba5-29136c5a8aff
* Version Independent ID: e249e694-e8d8-8b05-8cf1-c51244fba453
* Content: [OneNote.Application class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/onenote/onenote.application?view=office-js)
* Content Source: [docs/docs-ref-autogen/onenote/onenote.application.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/onenote/onenote.application.yml)
* Product: **office 365**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
tracked using 2800061in the OneNote project of Azure DevOps, not the OC project.

**Comment by stephenb159** [comment]
Thank you for looking into this, and please keep me updated. Being able to access the active paragraph is critical to my development workflow.

**Comment by Rick-Kirkham** [comment]
pinged Ryan McMinn and Gary Neitzke

**Comment by Rick-Kirkham** [comment]
This is still a bug.

**Comment by Rick-Kirkham** [comment]
The bug has been set to "won't fix". The description for the method has been marked "Deprecated". This should appear in the reference article and the intellisense in the near future.

**Comment by YutongLi291** [comment]
I'm still having this problem. The method is still not marked as Deprecated on the Office-js reference and it still appears in intellisense. Is there any alternatives to getting the current paragraph/selection then?
