### ISSUE TITLE
body.setAsync behaving differently in OWA vs Outlook for Desktop in terms of coercion to HTML of plain text message

### ISSUE THREAD

**Issue by kinkoazc** [OfficeDev/office-js#3642]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop/OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2309 Build 16.0.16827.20000) 64-bit 
* Operating System: Edition	Windows 10 Pro Version	21H1 OS build	19043.2364 Experience	Windows Feature Experience Pack 120.2212.4190.0
* Browser (if using Office on the web): Chrome
 
## Expected behavior

Behavior should be consistent between the two e-mail clients.

## Current behavior

On OWA, the plain text message doesn't get coerced to HTML like it does in Outlook for Desktop when setting HTML body content with HTML coercion type.

## Steps to reproduce

1. In OWA/Outlook for Desktop start composing a plain text type message(by switching the format to Plain text).
2. Using Script Lab, load & run the following script https://gist.github.com/kinkoazc/a7e949052eb535ce50b6ff7b1c19073f and try setting some HTML content as the body.
3. While in Outlook for Desktop the plain text message type gets coerced to HTML(and the set HTML content renders as HTML), in OWA it shows as plain text(in a plain text message).

## Link to live example(s)

https://gist.github.com/kinkoazc/a7e949052eb535ce50b6ff7b1c19073f

# Provide additional details

## Context

Trying to coerce a plain text message to HTML type, before setting additional HTML content.

**Comment by exextoc** [comment]
@kinkoazc - I am able to repro this issue, but curious to know one thing.
Any specific reason you want to convert to plain text and change as html via setAsync? New Mac Outlook for example doesn't have plain text option when composing email.
I am trying to understand your scenario so I can help you better.

**Comment by kinkoazc** [comment]
@exextoc Trying to convert the existing plain text message to HTML format, so that later I can append HTML code to the message.

**Comment by exextoc** [comment]
@kinkoazc Currently there is no supported way to set the coercion type of an email body. What you are seeing in Outlook Desktop and Outlook Web is inconsistent and we have noted down the same and will fix in future versions, but if you switch to "New Outlook", the behavior will be similar to OWA.

It is always a good idea to check the format by calling getTypeAsync before setting the body in desired format.
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/insert-data-in-the-body#insert-data-at-the-beginning-of-the-item-body

We track Outlook add-in feature requests on our [Tech Community Page](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

Looks like there is already a similar request.
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/allow-setting-bodytype-to-html-in-outlook-from-add-in/idi-p/3596975
