### ISSUE TITLE
Worksheet nameAfter different than address of active range

### ISSUE THREAD

**Issue by danielpdev** [OfficeDev/office-js#3643]
Hi,

There is a fundamental issue with handling worksheet name change and address of a particular range.
How to reproduce:
1. Open Excel with an add-in 
2. Add handlers for worksheet name changed		context.workbook.worksheets.onNameChanged.add(this.onWorksheetsNameChanged.bind(this))
3. Add handler for selection change 
activeWorksheet.onSelectionChanged.add(() => {});
4. Rename from Sheet1 to ev1 

> you get on name changed the worksheet name as the string "ev1" -> Ok

5. Click on cell A1 

> you get address of A1 like "'ev1'!A1"  -> NOK as the worksheet name that was changed does not contain any quotes (')

From what I noticed if I add a number in the worksheet name I get the active range address as with quotes,("'activerange'!A1") if I don't add a number all is good.

**Comment by donlvMSFT** [comment]
Hi @danielpdev ,

Thanks for reporting this. I try to follow the repro steps, but seems I couldn't get the full string of the address with worksheet name, could you help review my snippet? If you could share any sample code to repro, that would be really helpful.

https://gist.github.com/donlvMSFT/ebd597e8068e48c81ae13dd29373f114

Thanks,
