### ISSUE TITLE
Office on the web in the Edge, Firefox, or Safari browser, the dialog box and task pane don't share the same Local Storage

### ISSUE THREAD

**Issue by tiwarigaurav** [OfficeDev/office-js#3647]
In the Outlook web add-in the Task Pane and Dialog Box do not share the same Local Storage. This makes it impossible to use the MSAL.JS acquireTokenSilent method when developing add-ins to work with Graph API (without the need for a back-end implementation/middleware).

In short - "Office Add-In + React + MSAL.JS + Graph API" will not work cross platform and cross browsers in real world scenarios.

**Environment**
* Platform: PC desktop, Mac, Cross Platform
* Host: Outlook desktop app
* Office version number: Office 365
* Operating System: Windows
* Browser (if using Office on the web): Edge, Safari
 
**Expected behavior**
When using the Office dialog api to open a webpage in a pop-up window for Authentication/Authorization using MSAL.JS - I would expect to store the Auth details in Local Storage and access it from the Task Pane window (acquireTokenSilent).
I am aware of the messageParent/child method - but this is not feasible with MSAL implementation as the refresh token is saved in the local storage ONLY.

**Current behavior**
The local storage is not shared between the task pane and dialog box - this forces the user to login again via the dialog box as soon as the access token expires (every 1 hour). This is not workable in production systems

**Steps to reproduce**
1. Create a new Outlook web add-in using Yoeman
2. Add MSAL.JS implementation to login the user and get access token for Graph API - [reference implementation](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Office-Add-in-Microsoft-Graph-React)
3. Wait for the access token to expire (about 1 hour)

**Provide additional details**
1. Create a new Outlook web add-in using Yoeman (REACT + Typescript)
2. Install azure/msal-browser v2x
3. In the app.tsx file add the following code on button click 
```
const dialogLoginUrl: string = location.protocol + '//' + location.hostname + (location.port ? ':' + location.port : '') + '/login.html';

await Office.context.ui.displayDialogAsync(
  dialogLoginUrl,
  {height: 40, width: 30},
  (result) => {
      if (result.status === Office.AsyncResultStatus.Failed) {
      }
      else {
          loginDialog = result.value;
          loginDialog.addEventHandler(Office.EventType.DialogMessageReceived, this.processLoginMessage);
      }
  }
);

processLoginMessage = async (args: { message: string; origin: string; }) => {
  let messageFromDialog = JSON.parse(args.message);
  if (messageFromDialog.status === 'success') {
    loginDialog.close();
    console.log(messageFromDialog.result.accessToken);    
  }
  else {
    // Something went wrong with authentication or the authorization of the web application.
    loginDialog.close();
  }
}
```
4. Add login.html page and login.ts file. In the login.ts file add the following code: 
```
import { PublicClientApplication } from "@azure/msal-browser";

(() => {
    Office.initialize = () => {
        let msalInstance = new PublicClientApplication({
            auth: {
            authority: "https://login.microsoftonline.com/organizations/",
            clientId: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"
            },
            cache: {
            cacheLocation: "localStorage",
            storeAuthStateInCookie: true,
            },
        });

        const authParamsGraph = {
            scopes: ["https://graph.microsoft.com/.default"]
        };
         msalInstance.handleRedirectPromise()
        .then(async (response) => {
            if (response) {
                Office.context.ui.messageParent(JSON.stringify({ status: 'success', result : response }));
            } else {
                msalInstance.loginRedirect(authParamsGraph);
            }
        })
        .catch(() => {
            console.log('failure');
        });
    };
})();
```
5. EVERYTHING WORKS TILL HERE
6. Now, in the app.tsx file add the following code that runs when the access token expires (the logic is irrelevant here)
```
    let msalInstance: PublicClientApplication = new PublicClientApplication({
      auth: {
      authority: "https://login.microsoftonline.com/organizations/",
      clientId: "26431e25-8afe-44de-8ff3-43c6e89e8d86",
      navigateToLoginRequestUrl: false
      },
      cache: {
      cacheLocation: "localStorage",
      storeAuthStateInCookie: true,
      },
    });
    const authParamsGraph = {
      account: messageFromDialog.result.account,
      scopes: ["https://graph.microsoft.com/.default"]
    };

    // I get an error here
    let spResp = await msalInstance.acquireTokenSilent(authParamsGraph);
    console.log(spResp);
```
7. Since the local storage is not shared we get an error in **Outlook Desktop App running in Windows**
**Exception has occurred: ClientAuthError: token_refresh_required: Cannot return token from cache because it must be refreshed. This may be due to one of the following reasons: forceRefresh parameter is set to true, claims have been requested, there is no cached access token or it is expired.**

**Context**
We are trying to build a simple Office Add In that interacts with Graph API. Having a backend implementation is an overkill for the use case

**Comment by Rick-Kirkham** [comment]
Have you tried passing the [displayInIFrame](https://learn.microsoft.com/en-us/javascript/api/office/office.dialogoptions?view=common-js-preview#office-office-dialogoptions-displayiniframe-member) option in the call to `displayDialogAsync`? Maybe LocalStorage is shared if the dialog and taskpane are in the same JavaScript runtime.

Another question: I'm not familiara with MSAL, but is there no way to pull the RefreshToken out of LocalStorage and pass it to the task pane with `messageParent`?

**Comment by tiwarigaurav** [comment]
> Have you tried passing the [displayInIFrame](https://learn.microsoft.com/en-us/javascript/api/office/office.dialogoptions?view=common-js-preview#office-office-dialogoptions-displayiniframe-member) option in the call to displayDialogAsync? Maybe LocalStorage is shared if the dialog and taskpane are in the same JavaScript runtime.

As per MS documentation "This setting is only applicable in Office on the web, and is ignored by other platforms." The whole idea of building Web Add-Ins using Office.JS is for them to be cross-platform, cross-browser compatible. So, this does not solve the purpose.

> Another question: I'm not familiara with MSAL, but is there no way to pull the RefreshToken out of LocalStorage and pass it to the task pane with messageParent?

This is not supported with MSAL.JS.

**Comment by exextoc** [comment]
@tiwarigaurav For security reasons, this is not supported and it is by design. As you mentioned there are alternate ways to achieve this, and request you to follow the same. You can submit your feedback for a feature request at the following url.
[Microsoft 365 Developer Platform Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform).

**Comment by ccfontes** [comment]
Sorry, late bumper.
May I know the security reasons? Thank you.
