### ISSUE TITLE
Addin/APIs failing for IOS / Android 

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#3648]
# Provide required information needed to triage your issue
Outlook addin works for all platforms except for Outlook on IOS and Android.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: IOS and Android Outlook
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: NA
* Operating System: IOS / Android
* Browser (if using Office on the web): NA
 
## Expected behavior

All Outlook platforms web  and clients, should make the addin run correctly.

## Current behavior

Currently we have one customer where our addin is not working correctly on all mobile platforms. (IOS and Android)
Browser tests and Outlook-Desktop tests are working correctly.

## Steps to reproduce

Cannot create a set of reproduction tests.
I can ask our customer to directly work with your team if needed.

## Link to live example(s)
None

# Provide additional details
None

## Context

This has been going on for a while. I think there is something wrong with their configuration (probably allow/block lists) for the mobile environment.

I would like to ask assistance if there are settings in the EWS/M365 server that we need to enable to allow the use of REST APIs in Mobile outlook.

I apologize in advance if this is not the right venue for this. I just thought to file it here just in case other users are experiencing this issue as well. 

## Useful logs
None

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@glr0221 - Thank you for reaching out. Can you be more specific about "add-in not working"? 
Need additional info like:
1) Which api is not working as exepected?
2) What scenario are you trying to achieve with add-in?
3) Scriptlab sample for the code that is not working?
4) Outlook version of iOS/Android?

**Comment by glr0221** [comment]
Thank you very much @exextoc.

My apologies for being vague. Our addin is a reporting button. When our addin is opened, users can click a button to report an email to their infosec/admins.

For one of our clients, our reporting addin works correctly for Outlook OWA, Outlook-client MAC and Outlook-client Windows. The addin loads/opens correctly and when the button is clicked, the email is reported correctly to their admins.

For the same customer however, they can open and load our addin in their mobile outlook (IOS/Android), but when they click the button, it fails during the execution of the first REST-API. This API call is the following :

`https://outlook.office365.com/api/v2.0/me/messages/<MESSAGE_ID>?$select=InternetMessageHeaders`

Since (1) this very same addin (code and REST-APIs) works in our customer's other outlook-clients and (2) this addin also works for mobile and non-mobile Outlook for all our other customers, my best logical hunch is that there is something in our customer's environment disallowing REST-APIs (token and execution) from executing properly.

Which api is not working as expected?
- REST APIs are not working for mobile. It is highly likely that the user environment is not configured to support REST/EWS/Addins for mobile.
What scenario are you trying to achieve with add-in?
- We want our addin to successfully run REST-APIs in mobile. 
Scriptlab sample for the code that is not working?
- Unfortunately, none. 
Outlook version of iOS/Android?
- I am assuming this will be the latest build.

Conversely, would you know of any EXCHANGE/M365 server configuration that can effectively disable/enable EXCHANGE/REST APIs for mobile only? I really believe this is a configuration issue. But I don't have any idea what server setting can affect mobile REST/EWS usage.

**Comment by exextoc** [comment]
Can you please share the powerlift logs and the manifest for the add-in you are seeing the issue with.
