### ISSUE TITLE
Excel Javascript API Add-in: how to set worksheet's zoom level

### ISSUE THREAD

**Issue by doantumai** [OfficeDev/office-js#3649]
Hi,

I'm trying to find out  how to set the worksheet's zoom level. The only relevant zoom attribute that I found is worksheet.pageLayout.zoom (relevant docs https://learn.microsoft.com/en-us/javascript/api/excel/excel.pagelayout?view=excel-js-preview#excel-excel-pagelayout-zoom-member) but it only change the worksheet's **print zoom options**, not the worksheet view itself. 

Is there any way to adjust the worksheet's zoom level in Javascript? 

Many thanks

**Comment by donlvMSFT** [comment]
Hi @doantumai , thanks for reporting the issue.

However, Excel APIs currently doesn't support change the zoom level for worksheet. 

We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there or vote for the similar ones. Feature requests are considered when we go through our planning process.

Thanks.

**Comment by doantumai** [comment]
Hi @donlvMSFT ,

Thank you so much for your reply. I'll then close this issue.
