### ISSUE TITLE
Deleting a very hidden worksheet

### ISSUE THREAD

**Issue by dcruceanu** [OfficeDev/office-js#365]
Hello,

I'm trying to delete a worksheet whom visibility is very hidden.

This piece of code
var hiddenSheet = context.workbook.worksheets.getItem('HiddenSheet');
hiddenSheet.delete();

Crashes into: 
GeneralException: There was an internal error while processing the request.

I'm getting the office library using the NPM package for Office.js which is a copy of what gets published to the official "evergreen" Office.js CDN, at https://appsforoffice.microsoft.com/lib/1/hosted/office.js.

* Platform: Mac
* Host: Excel
* Office version number: 16.2

**Comment by JuaneloJuanelo** [comment]
thanks for reporting this we are investigating this issue.

**Comment by JuaneloJuanelo** [comment]
@dcruceanu This behavior is by design. The reason why we even have veryHiddenSheet is precisely to prevent the user from accidentally deleting it. so if you want to delete a very hidden you need to change its visibility to either hidden or visible and then delete it. 

something like

```
async function deleteIt() {
  await Excel.run(async (context) => {
    context.workbook.worksheets.getItem("my sheet").visibility = Excel.SheetVisibility.hidden;
    context.workbook.worksheets.getItem("my sheet").delete();
    await context.sync();
  });
```
so that's what you need to do.

**Comment by JuaneloJuanelo** [comment]
@AlexJerabek  we probably need to document this behavior https://docs.microsoft.com/en-us/javascript/api/excel/excel.worksheet?view=office-js#delete--

that method will fail if a worksheet is very hidden.

**Comment by AlexJerabek** [comment]
The documentation changes have been made [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33108) and [here](https://github.com/OfficeDev/office-js-docs-pr/pull/754). Those changes will be made live next update cycle.
