### ISSUE TITLE
Outlook for Mac Old UI getComposeTypeAsync call does not return a value

### ISSUE THREAD

**Issue by chris-truong** [OfficeDev/office-js#3652]
# Provide required information needed to triage your issue
https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailboxenums.composetype?view=outlook-js-1.11
Office.context.mailbox.item.getComposeTypeAsync call does not successfully return a value or type when called within Outlook for Mac Old Version. This call does work within Outlook for Mac New Version and Outlook for Web Application. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook for Mac (Old UI Version)
* Office version number: Outlook for Mac Old UI Version 16.76.2
* Operating System: Ventura 13.5
* Browser (if using Office on the web): N/A
 
## Expected behavior

Office.context.mailbox.item.getComposeTypeAsync call should successfully return the compose type enum.

## Current behavior

There is no value returned in the api listed.

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

Our outlook add-in app relies on the compose type to have certain behaviors based on this value, ex. if the user is in 'reply' mode or 'newMail' mode, there would be different behaviors.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@chris-truong - Thank you for reporting the issue. At this point, no active development is happening in old mac outlook version, and we are suggesting all users to move to new outlook. 
As you mentioned, this issue is no repro in new outlook. We suggest you move to new version.
