### ISSUE TITLE
The context.document.body.insertFileFromBase64 function crashes when inserting word file with content controls (TextBox, Activex Controls)

### ISSUE THREAD

**Issue by JesusMNA** [OfficeDev/office-js#3653]
The context.document.body.insertFileFromBase64 function fails to insert a file in Word for Windows Desktop, when the document contains content controls

## Your Environment

* Platform: PC desktop
* Host: Word
* Office version number: Version 2308 Build 16.0.16731.20052
* Operating System: Windows
* Browser (if using Office on the web): NA
 
## Expected behavior

It is expected that when inserting the content, no errors will occur.

## Current behavior

The following error occurs when inserting the content:

![image](https://github.com/OfficeDev/office-js/assets/96563142/2c5e9f4e-7775-4418-aba8-968000e636eb)

## Steps to reproduce

1. Execute context.document.body.insertFileFromBase64() sending the content of the document-base64.txt file (link below)

https://drive.google.com/drive/folders/1MknALP5LYzDa7Df29TxAV3XBIqQxEfrT?usp=sharing

# Provide additional details

1. From the Mac operating system if it loads correctly

## Context

We are building an add-in that contains a word course, so we need these types of elements to be able to be used correctly in the templates so that the students can learn how to use them correctly

**Comment by jipyua** [comment]
Thanks for reporting this. We did some investigation and found that the error is because the form field in the signature area. 

This is a form activeX control field and has potential security risks. We disabled the insertion of this field from another base64 document. We suggest replacing this form field in the signature part with other features such as content control. Please have a try. Thanks.

**Comment by slabereemsft** [comment]
@AlexJerabek - Can we update the documentation for this Word API to acknowledge that there are restrictions in the file contents which can be inserted? 

https://learn.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#word-word-body-insertfilefrombase64-member(1)

**Comment by AlexJerabek** [comment]
@slabereemsft, Sure! Tagging @ElizabethSamuel-MSFT to coordinate.

**Comment by ElizabethSamuel-MSFT** [comment]
The changes made in the [DefinitelyTyped PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66838) should be published in the reference documentation later today.

**Comment by ElizabethSamuel-MSFT** [comment]
The documentation changes are now live. @JesusMNA, thanks again for raising this issue.
