### ISSUE TITLE
OnSend event not triggered when sending email copied to shared mailbox draft

### ISSUE THREAD

**Issue by t-miyake** [OfficeDev/office-js#3654]
# Provide required information needed to triage your issue
If I copy an email from a draft in my own mailbox to a draft in a shared mailbox, the OnSend event is not triggered when that email is sent.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook for Windows and New Outlook for Windows
* Office version number  
  * I have confirmed that this problem occurs in the following versions.  
    * Outlook for Windows
      * Outlook for Microsoft 365 MSO (Version 2308 Build 16.0.16731.20052) 64-bit

    * New Outlook for Windows  
      * Microsoft Outlook Version 1.2023.831.400 (Production).
      * Client Version is 20230904003.11 .

## Expected behavior

The expected behavior would be that such an operation would trigger the OnSend event.

## Current behavior

That operation does not trigger the OnSend event.

## Steps to reproduce

1. Create a new email and save it to a draft.
2. Drag and drop the email created in step 1 and move it to a draft in the shared mailbox.
3. Send the email moved in step 2.

## Link to live example(s)

I have created a very simple sample.
Once this add-in is loaded, the email transmission is always canceled.

```javascript
'use strict';

Office.onReady().then(function () {
    console.log('onReady');
});

function messageOnSent(event) {
    event.completed({
        allowEvent: true
    });
}
```

Here's the manifest file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xsi:type="MailApp">

  <Id>5ce92042-2088-4033-94e5-00e043d3b728</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Noraneko Inc.</ProviderName>
  <DefaultLocale>ja-JP</DefaultLocale>
  <DisplayName DefaultValue="Onsend blocker" />
  <Description DefaultValue="Onsend blocker" />
  <IconUrl DefaultValue="https://outlook.addin.app/onsendblock/images/icon64.png" />
  <HighResolutionIconUrl DefaultValue="https://outlook.addin.app/onsendblock/images/icon128.png" />
  <SupportUrl DefaultValue="https://www.noraneko.co.jp/" />

  <AppDomains>
    <AppDomain>https://outlook.addin.app</AppDomain>
  </AppDomains>

  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.3" />
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemEdit">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://outlook.addin.app/onsendblock/function.html" />
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteMailbox</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit" />
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>

  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Requirements>
        <bt:Sets DefaultMinVersion="1.8">
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>
      <Hosts>
        <Host xsi:type="MailHost">
          <DesktopFormFactor>
            <FunctionFile resid="function" />
            <ExtensionPoint xsi:type="Events">
              <Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="messageOnSent" />
            </ExtensionPoint>
          </DesktopFormFactor>
        </Host>
      </Hosts>
      <Resources>
        <bt:Images>
          <bt:Image id="icon16" DefaultValue="https://outlook.addin.app/onsendblock/images/icon16.png" />
          <bt:Image id="icon32" DefaultValue="https://outlook.addin.app/onsendblock/images/icon32.png" />
          <bt:Image id="icon64" DefaultValue="https://outlook.addin.app/onsendblock/images/icon64.png" />
          <bt:Image id="icon80" DefaultValue="https://outlook.addin.app/onsendblock/images/icon80.png" />
        </bt:Images>
        <bt:Urls>
          <bt:Url id="function" DefaultValue="https://outlook.addin.app/onsendblock/function.html" />
        </bt:Urls>
      </Resources>
    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>
```

The actual execution is shown below.

When the Onsend event is triggered  
https://github.com/OfficeDev/office-js/assets/9583126/c9d9c964-806a-426d-b75c-008769d214e1

When the Onsend event is not triggered (this issue)  
https://github.com/OfficeDev/office-js/assets/9583126/b76eb06a-9bc6-4fba-b48c-60a54d959110

## Context

The above operation still triggers the Application.ItemSend event in the VSTO add-in.
I think the OnSend event should be triggered the same way as in the VSTO Add-In.

**Comment by exextoc** [comment]
@t-miyake - Looks like the manifest does not specify shared mailbox support. Here is the guidance to support add-ins on shared mailbox.
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=windows%2Cxmlmanifest

**Comment by t-miyake** [comment]
@exextoc 
Thank you for your response.
As you pointed out, the manifest file was the cause.
I apologize for the oversight.
I will close this issue.
