### ISSUE TITLE
Outlook Mac Thick Client : Outlook Web Addin is bypassing on Email send  when changing Sensitivity of a composed mail in MaC Outlook thick client 

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#3660]
If we change the sensitivity of the composed email and try to send it , then Outlook WebAddin  is not picking up the email content and the mail is getting sent out , completely bypassing the outlook web Addin .

Same code base is working fine for Windows Outlook Thick Client + Windows Outlook Web + MaC Outlook Web version  

Reproducible Platform : Mac Outlook Thick Client
Outlook Version : Microsoft Outlook 16.77.1 (23091703)
MAC OS version -   macOS Ventura 13.5.1

**Comment by exextoc** [comment]
@geetamshukla Thank you for reaching out. Can you please provide additional details which will help us debug the issue? If you can point to the sample code in [script lab](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab), we will investigate further.

Also need additional details like: Mac Outlook Version, New Mac Outlook / Old Mac Outlook?

**Comment by exextoc** [comment]
Please also provide screenshots or video of the repro.

**Comment by geetamshukla** [comment]
@exextoc  Because of security restriction I can not share the code snippet or video . Is  there any way I can setup a meeting and show the demo .

**Comment by exextoc** [comment]
Are the other add-ins enabled for you in this case? Can you try to open any taskpane add-in? What is the sensitivity label you have set?

**Comment by geetamshukla** [comment]
> Are the other add-ins enabled for you in this case? Can you try to open any taskpane add-in? What is the sensitivity label you have set?

other Addin are not working for same ..and Taskpane Addin are not visible in MAC thick client (separate issue has been reported for the same .  https://github.com/OfficeDev/office-js/issues/3986 )

**Comment by ajays-msft** [comment]
Is this Legacy mac outlook or new mac outlook? When this issue was originally posted, Add-in support was not present for IRM emails in Mac. The support was added in Nov'23.

And, can you please explain what you mean by "bypassing security"?
