### ISSUE TITLE
Outlook Mac Thick Client : Top Cross button of Office Modal Window not working. 

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#3661]
The Outlook WebAddin UI components are getting rendered inside the modal window of generated by Office JS.
 The modal window has a cross button for closing it, on the right top hand corner, which comes inbuilt with the window.
If the user is clicking on the cross button on Mac outlook thick client then the particular email template is getting stuck 
and Send button is getting disabled, with the message "Outlook WebAddin is  running" in a loop.

Same code base is working fine for Windows Outlook Thick Client + Windows Outlook Web + MaC Outlook Web version

**Comment by exextoc** [comment]
@geetamshukla Thank you for reaching out. Can you please provide additional details which will help us debug the issue? If you can point to the sample code in [script lab](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab), we will investigate further.
Please also provide screenshots or video of the repro.

Also need additional details like: Mac Outlook Version, New Mac Outlook / Old Mac Outlook?

**Comment by geetamshukla** [comment]
@exextoc  Because of security restriction I can not share the code snippet or video . Is  there any way I can setup a meeting and show the demo .

**Comment by exextoc** [comment]
Which window are you talking about? Is it add-in taskpane window? What kind of add-in it is? Is it takpane or taskpane and onSend both? Also do you have event.completed getting called in onSend add-in? Can you please share the exact repro steps and what you are trying to achieve?

**Comment by geetamshukla** [comment]
> Which window are you talking about? Is it add-in taskpane window? What kind of add-in it is? Is it takpane or taskpane and onSend both? Also do you have event.completed getting called in onSend add-in? Can you please share the exact repro steps and what you are trying to achieve?

OnSend Event we are showing Office Js popup .In MAC Thick Client(Microsoft Outlook 16.77.1 (23091703) the office Js Popup close button is not working properly and If the user is clicking on the cross button on **_MAC Thick Client(Microsoft Outlook 16.77.1 (23091703)_** then the particular email template is getting stuck
and Send button is getting disabled, with the message "Outlook WebAddin is running" in a loop.

**Comment by exextoc** [comment]
@geetamshukla From what I understand you are trying to show a display dialog using [displayDialogAsync](https://learn.microsoft.com/en-us/javascript/api/office/office.ui?view=common-js-preview#office-office-ui-displaydialogasync-member(1)) from an On-send Addin. [Here](https://github.com/OfficeDev/Outlook-Add-in-On-Send) is a sample On-send Addin . You can try to run this Addin and update the code to show display dialog and check if that works for you.  Please ensure that you are calling event.completed with allowEvent argument as mentioned [here](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=classic#:~:text=To%20signal%20that%20the%20add%2Din%20has%20finished%20processing%20the%20ItemSend%20event%20triggered%20by%20the%20send%20operation%2C%20call%20the%20event.completed(%7BallowEvent%3ABoolean%7D)%20method.%20The%20allowEvent%20property%20is%20a%20Boolean.%20If%20set%20to%20true%2C%20send%20is%20allowed.%20If%20set%20to%20false%2C%20the%20email%20message%20is%20blocked%20from%20sending.). 
More details on Dialog API and it's usage can be found in [Use the Office dialog API in Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins).

**Comment by geetamshukla** [comment]
> Addin

@exextoc  we are using event.completed with allowEvent argument as motioned in MS doc but its not working in thick client . 
<img width="793" alt="image" src="https://github.com/OfficeDev/office-js/assets/142812553/1767663c-24af-4306-9e84-9bdbfce307fe">

**Comment by soumyamondal-accenture** [comment]
@exextoc please check the code provided from @geetamshukla and give you comments

**Comment by exextoc** [comment]
@geetamshukla  @soumyamondal-accenture   Is event.completed getting called when User clicks on Top Cross Button?
As only partial code is shared, we cannot confirm how add-in handles this case.
Please find the sample code here https://github.com/OfficeDev/Office-Add-in-Dialog-API-Simple-Example/blob/master/SimpleDialogSampleWeb/DialogHelper.js where close button click scenario is getting handled.

To learn more about this, please refer https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-handle-errors-events
