### ISSUE TITLE
Outlook Mac Thick Client : Validated Attachments in the Outlook Web Addin popup are not getting downloaded .

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#3662]
We have developed an Outlook-Web Addin which  facilitates the user to download the validated attachments by clicking on the attachment icons avilable on  the Outlook-Web Addin Office Modal Window and view the contents that were flagged or incorrect according to the configurations, so that they can make necessary changes before sending out the email.
In MaC outlook thick client The attachments are not getting downloaded, even after clicking multiple times. 

Same code base is working fine for Windows Outlook Thick Client + Windows Outlook Web + MaC Outlook Web version

**Comment by exextoc** [comment]
@geetamshukla Thank you for reaching out. Can you please provide additional details which will help us debug the issue? If you can point to the sample code in [script lab](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab), we will investigate further.

Also need additional details like: Mac Outlook Version, New Mac Outlook / Old Mac Outlook?

**Comment by exextoc** [comment]
Please also provide screenshots or video of the repro.

**Comment by geetamshukla** [comment]
@exextoc  Because of security restriction I can not share the code snippet or video . Is  there any way I can setup a meeting and show the demo .

**Comment by exextoc** [comment]
Can you please tell which API are you using for downloading the attachments and what is the error you are seeing? Do you see any error in the console?

**Comment by geetamshukla** [comment]
@exextoc  we are using Exchange web service to get the attachment content  and then binding the attachment content as Blob object in Model popup . 

For starter we tried to download the file with hardcoded png but that also does not work in MAC Thick Client(Microsoft Outlook 16.77.1 (23091703) 

using saveAs from "file-saver"  to download file in Office Model popup . 

below is code to trigger a download in office js popup . This download is not happening in **MAC Thick Client(Microsoft Outlook 16.77.1 (23091703)** 

import * as React from 'react';
import {saveAs} from "file-saver"


const Anchorclick=():void=>{
{
saveAs(
    "https://localhost:3000/assets/evt-32.png",
    "example.png"
  );
}

const FileDownload=():any=>{
    return(
        <div onClick={Anchorclick}  style={{
            borderRadius:25,
            height: 45,
            width: 150,
            display:"flex",
            justifyContent:'center',
            alignItems:'center',
            backgroundColor:"#3349FF",
            padding:"0 10px"}}>
            <p style={{color:"white",        
            }}>Click to download</p>
        </div>
    )
}
export default FileDownload

**Comment by t-ariyoshi30907** [comment]
@exextoc 
I'm also facing the same issue.
I've created a dedicated sample add-in. Would you be able to test it on Outlook for Mac to confirm its functionality?

**Environment:**
- OS: Macbook Pro Monterey (ver. 12.2.1)
- Platform: Outlook for Mac (New UI ver. 16.58 (22021501))

**Reproduction Steps:**
1. Access the following URL.
https://drive.google.com/file/d/1E0M8UDeOiUyxB_iiWU6P3MYC5aADmBc_/view?usp=drive_link
2. Download "downloadSample.zip" and place it in your desired location.
3. Launch the "Terminal" and navigate to the corresponding directory.
4. Run "npm install".
5. Run "npm run dev-server".
6. Upload "manifest.xml" in Outlook to install the add-in. (The XML file is stored in sample.zip)
7. Create and send an email.
8. Click on "Download Textfile" in the dialog.

Just like @geetamshukla, the file isn't getting downloaded on Outlook for Mac. However, when I run this add-in on outlook for Windows ＆ outlook on the web, the file does get downloaded. Why is it not working correctly on Outlook for Mac? Please let me know if there are any best practices for integrating this program with Outlook for Mac.

**Comment by exextoc** [comment]
@geetamshukla  This issues looks similar to https://github.com/OfficeDev/office-js/issues/3 . Could you please try the workaround suggested here https://github.com/OfficeDev/office-js/issues/3#issuecomment-688251989 and see if it resolves the issue?

**Comment by geetamshukla** [comment]
> Can you please tell which API are you using for downloading the attachments and what is the error you are seeing? Do you see any error in the console?

We are not using any API to download the attachment .   refer below code which we r using ..we r juzz trying to download a hardcoded image using file-saver and that only is not working 

For starter we tried to download the file with hardcoded png but that also does not work in MAC Thick Client(Microsoft Outlook 16.77.1 (23091703)

using saveAs from "file-saver" to download file in Office Model popup .

below is code to trigger a download in office js popup . This download is not happening in MAC Thick Client(Microsoft Outlook 16.77.1 (23091703)

import * as React from 'react';
import {saveAs} from "file-saver"

const Anchorclick=():void=>{
{
saveAs(
"https://localhost:3000/assets/evt-32.png",
"example.png"
);
}

const FileDownload=():any=>{
return(
<div onClick={Anchorclick} style={{
borderRadius:25,
height: 45,
width: 150,
display:"flex",
justifyContent:'center',
alignItems:'center',
backgroundColor:"#3349FF",
padding:"0 10px"}}>
<p style={{color:"white",
}}>Click to download



)
}
export default FileDownload

**Comment by geetamshukla** [comment]
@exextoc  re-open this issue as still there is no solution

**Comment by exextoc** [comment]
@geetamshukla  This is a known issue, and we are blocked by a [WebKit bug](https://bugs.webkit.org/show_bug.cgi? id=174076).  The workaround here is to call Office.context.ui.openBrowserWindow(URL); with a URL that you own and from there once the full browser opens, create your blob object and get the browser to download the file.
Office.context.ui.openBrowserWindow(url) should be available in office-js-api version: 20200812.3 or later in macOS.
