### ISSUE TITLE
OWA Bug for OnAppointmentOrganizer and OnAppointmentSend

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#3667]
when not disable cache, load js resource from memory cache, the OnAppointmentOrganizer and OnAppointmentSend will not excuted often.
<img width="686" alt="image" src="https://github.com/OfficeDev/office-js/assets/1878089/88e0cb39-3885-47b1-a5dc-abdd9f41f2ba">

**Comment by slabereemsft** [comment]
Hello-chenchen,

Thanks for reporting this issue.  I'm not sure if there's going to be enough detail for our engineering team to engage on this bug.  Can you provide a few more repro steps to help us understand what is going on?

**Comment by hello-chenchen** [comment]
@slabereemsft hello, yes. I just follow event based document to implement OnAppointmentSend and OnAppointmentOrganizer. And install the manifest. Then I try it in owa.
You just need open a new event or an update event. And then wait a moment. I write some console log in  OnAppointmentOrganizer. So when I open event, the log will print to console. But I found in sometimes, when I try to open event, the log not printed. Maybe 50% can printed. But if I disable cache. It will be 100%.

**Comment by exextoc** [comment]
@hello-chenchen Can you please provide sample code that you are using?

**Comment by hello-chenchen** [comment]
@exextoc  @slabereemsft , in fact, It happened a lot last night, but it hasn't happened today. It's really weird.

<img width="905" alt="image" src="https://github.com/OfficeDev/office-js/assets/1878089/9c3cfd58-a376-45e1-bd7c-d31b043901be">

```
var self = window;
async function OnAppointmentOrganizerFunc (event) {
    console.log('Start OnAppointmentOrganizerFunc: ', event);
    exitFunction(event);
    return;
}

function exitFunction (event) {
    Office.context.mailbox.item.subject.getAsync({ asyncContext: event }, function (asyncResult) {
      asyncResult.asyncContext.completed({ allowEvent: true });
    });
  }

async function OnAppointmentSendFunc (event) {
    console.log('Start OnAppointmentSendFunc: ', event);
    exitFunction(event);
    return;
}

if (Office && Office.context && (Office.context.platform === Office.PlatformType.PC || Office.context.platform == null)) {
    Office.actions.associate("OnAppointmentOrganizerFunc", OnAppointmentOrganizerFunc);
    Office.actions.associate("OnAppointmentSendFunc", OnAppointmentSendFunc);
  } else {
    Office.initialize = () => {
      // ZoomLog4js = new ZoomLog4js();
      self.OnAppointmentOrganizerFunc = OnAppointmentOrganizerFunc;
      self.OnAppointmentSendFunc = OnAppointmentSendFunc;
    }
  }
```

**Comment by hello-chenchen** [comment]
@slabereemsft @exextoc , does the event-based excuted, is related with some verify with network api? cause, i find the problem happened in different computer at the same time. but this problem will block send action if they use OnAppointmentSend. if this problem not be fixed, this problem will become a very serious problem.

**Comment by exextoc** [comment]
@hello-chenchen Can you please elaborate further? There is no network call from outlook during appointmentsend, unless the add-in code is trying to do any network operation.

Is it possible for you to send repro steps and point to the add-in manifest that I can sideload and validate what you are seeing?

**Comment by hello-chenchen** [comment]
hi @exextoc , please reopen this issue. our customer still can reproduce this problem. the reproduce step is too sample, just click send.
![on send problem -1](https://github.com/OfficeDev/office-js/assets/1878089/c2cdbfcc-858c-42d2-8ada-423f468ee3c1)

**Comment by hyigit-adelcon** [comment]
I am having a similar problem. In the classic Outlook application the OnAppointmentSend event is triggered without any problem. However, it does not work in the Web or the new Desktop version.

**Comment by exextoc** [comment]
@hello-chenchen  In our testing, cache doesn't impact the event trigger. The event compose opens a new window, so the console log will also move to the devtool of new window. Can you make sure that you are checking the right devtool window for console log.

**Comment by hello-chenchen** [comment]
hi @exextoc , yes, i can confirm, in fact recentlly, i can still reproduce this problem in my owa. and the screenshot is enough i think. cause, OnAppointmentOrganizer event will always call this url: https://zoom.us/office365/onsend?et= and you can see it in the screenshot. So, the first time click send owa not call onsend?et= url, but the second time click, it send this url automaticially. this is the screenshot shows on it.

**Comment by exextoc** [comment]
Can you please confirm if other launch events are working fine, and issue is with onAppointmentOrganizer and onAppointmentSend. Does the same URL work fine for other launch events or some other setup?

**Comment by hello-chenchen** [comment]
hi @exextoc , OnAppointmentTimeChanged, OnAppointmentRecurrenceChanged, OnAppointmentAttendeesChanged these api also not worked. and when i meet this question, my console report this error. hope it can help you.
[outlook.office.com-1700212806472.log](https://github.com/OfficeDev/office-js/files/13389879/outlook.office.com-1700212806472.log)

<img width="936" alt="image" src="https://github.com/OfficeDev/office-js/assets/1878089/45c58569-370f-4424-881b-6911218ac889">

**Comment by exextoc** [comment]
Can you also check if launch events on mail surface is working fine. We still don't have a repro for appointment. Would it be possible to share some manifest which can be used to repro this issue?

**Comment by hello-chenchen** [comment]
hi @exextoc , sorry, for the manifest, i can't share here. do you have some way for us to share some sensitive file? or maybe you can contact nikitamittal@microsoft.com, who also tracking this issue, and we send the internal manifest file for him.

**Comment by exextoc** [comment]
@hello-chenchen Can you share a basic addin code with console logs for us so that we can host and sideload to repro this? If yes, please share a zip file to OutlookExtensibility@M365x53858506.onmicrosoft.com.

**Comment by hello-chenchen** [comment]
hi @exextoc , i send the manifest to the email. i think there is no need send the basic addin code. cause it didn't call the url in manifest. so don't need the test code.

**Comment by ajays-msft** [comment]
@hello-chenchen - Is the issue happening only in dev environment (when dev tools is open), or always?

**Comment by hello-chenchen** [comment]
hi @ajays-msft @exextoc , thanks for your help. recently, it's not happened. it's intermittently and doesn’t block the customers. so we will close this issue.
