### ISSUE TITLE
Double clicking the 'Allow' button on the dialog consent form in Word Online launches two dialogs

### ISSUE THREAD

**Issue by csgmike** [OfficeDev/office-js#367]
## Expected Behavior
Only one dialog should be launched regardless of single/double click

## Current Behavior
When doble clicking the 'Allow' button, two dialogs are shown

## Steps to Reproduce
1. Load the 'Script Lab' addin in Word Online
2. Launch the 'Code' taskpane
3. Click the hamburger in the top left of the panel until you have the code view
4. Click the user login button in the top right of the task pane
5. Double click the 'Allow' button: two auth windows are launched

![image](https://user-images.githubusercontent.com/35249588/51662441-c63bdc00-1fee-11e9-8473-730fd3a3535e.png)

## Context
Some of our users are double clicking - this is confusing them.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Noticed in Word (but I presume all)
* Office version number: Online
* Operating System: Windows 10 Enterprise 1803 17134.523
* Browser (if using Office Online): All

## Useful logs

- [X] Screenshots
- [ ] Console errors
- [ ] Test file (if only happens on a particular file)

**Comment by Edward-Zhou** [comment]
For dialog, it is reasonable, it should redirect to login windows in the word task pane instead of opening a new window tab.

**Comment by danielgwilson** [comment]
Hi, this is something you can prevent by checking whether a dialog is already open before opening a new one.

I have an example here:
https://github.com/danielgwilson/github-office-add-in/blob/master/src/functions/getTokenViaDialog.ts

```typescript
let _dialogOpen = false;

/**
 * Function retrieves a cached token or opens a dialog box if there is no saved token. Note that this is not a sufficient example of authentication but is intended to show the capabilities of the Dialog object.
 */
export function getTokenViaDialog(): Promise<string> {
  return new Promise(function(resolve, reject) {
    if (_dialogOpen) {
```

It's admittedly not a great idea to track `_dialogOpen` as a global constant, but this is the gist of what you'd need to do to prevent the double click issue.

**Comment by csgmike** [comment]
@danielgwilson I don't think this is an acceptable solution to the issue. This should be something that the framework provides as it affects any addin using the dialog API.

It should not be up to every developer to implement this in their code. Please re-open.
