### ISSUE TITLE
Excel getting  corrupted  if there is an external link set (insertWorksheetsFromBase64(base64File, options))

### ISSUE THREAD

**Issue by shermaro91** [OfficeDev/office-js#3671]
Hi Team,

I have excel Add-in in which I have excel upload option. On Upload I am saving excel to my server.
Now, when I am trying to open the excel using insertWorksheetsFromBase64(base64File, options) method my file is getting corrupted.
This scenario comes when there is any external link/queries/data connection  attached to Excel.
Please assist how we can come through from this?
Is there any method using which we can identify the external Links?
Is there any method using which we can disable or update the link path?

My Environment
Platform : PC desktop
Host: Excel
Office version number: Microsoft® Excel for Microsoft 365 MSO (Version 2308 Build 16.0.16731.20052) 64-bit
Operating System: Windows 10 pro
![Screenshot 2023-09-12 201453](https://github.com/OfficeDev/office-js/assets/61821139/c4fe0bd2-7c52-4d42-bb14-3d2f31b310b9)

**Comment by penglongzhaochina** [comment]
Hi shermaro91,
I created a workbook named book1 which contains the external link. In the Book2 I uploaded the book1 to base64 and insert it to the book2 by using insertWorksheetsFromBase64. It works well. Please correct me if I have some misunderstanding.  Could you please share your workbook and the step to reproduce?

**Comment by shermaro91** [comment]
Hi @penglongzhaochina ,
issue is coming when there are externalLinks and pivot tables are there in Workbook.

**Comment by penglongzhaochina** [comment]
Hi @shermaro91 ,

I still can't reproduce your issue by using the pivot tables or external links. Could you please share your document which have this issue?
