### ISSUE TITLE
Mac Word: Unable to send XHR to http localhost

### ISSUE THREAD

**Issue by adomasven** [OfficeDev/office-js#3674]
> office-js bot:
Internal issue 9038229 has been created.

Testing with Word for Mac, attempting to send an XHR to a server running on localhost without SSL results in an error message (from debug console):

```
XMLHttpRequest cannot load http://127.0.0.1:23119/document/execCommand due to access control checks.
```

XHR to http localhost works without issues with Word Online.
This issue was closed By Design

**Comment by jargil** [comment]
@adomasven - I tried this locally and I can reproduce the same difference when trying to do a XHR against localhost from Edge vs Safari. When you say "works without issues with Word Online", are you testing in Safari or a different browser?

This document specifies which WebView controls are used by Office on the different OS platforms:
https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins#non-windows-platforms

As you can see, on Mac, we use a WebKit based WebView control, so any limitations that are established by Safari will apply. For instance, Safari does not support locally delivered mixed resources, per https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#loading_locally_delivered_mixed-resources. This aligns with what I'm seeing locally.

If you could validate directly on Safari, and get it working, you'd likely be able to get the same working when running directly in Office for Mac. However, if it works directly in Safari, but not when running in Office for Mac, then please reactivate this issue with sample code and steps to reproduce.

**Comment by adomasven** [comment]
This is a huge blocker for the Zotero plugin on Word for Mac.

We have been working with the Word JS API team to convert our existing Word for Mac and Word for Windows plugins into a single plugin (which would also work for Word Online, and eventually be enhanched to work with iOS and Android versions of Word). From the beginning of these discussions we have communicated our requirement for the ability to talk to the local Zotero app. Currently the only way to do that with the Word JS API is via HTTP requests. We are able to work around this on Safari, because the Zotero app also includes the Zotero Safari plugin (Zotero Connector), which we can use to route HTTP requests around the localhost mixed content limitations on Safari.

On the other hand, being unable to communicate to local apps either via HTTP or some other means on Word for Mac is a huge blocker for us. Moreover, we are aware there are other extension vendors converting to Word JS API that also need to communicate to locally running software, so they will also be blocked by this.

Having said that, the WebKit team has actually been discussing about [not treating localhost as mixed content](https://bugs.webkit.org/show_bug.cgi?id=171934) for a long time (also see related bugs). They will eventually allow communication to localhost from https:// origins, but the implementation has been getting stuck due to disagreements on how to best proceed, as well as lack of motivation to get it done sooner.

If someone with the institutional weight of Microsoft weighed in on that issue, it may be possible to get it resolved and allow localhost communication from WebKit, and in turn from Word for Mac. On the other hand, if it's not possible to push through the changes required in WebKit, Word for Mac either needs to work around this WebKit limitation by overriding XHR behaviour, or provide an alternative API to communicate to local applications.

I hope this issue can be reopened and addressed in a more nuanced way.
