### ISSUE TITLE
Outlook: Unable to remove sideloaded add in

### ISSUE THREAD

**Issue by JMMM77** [OfficeDev/office-js#3676]
# Provide required information needed to triage your issue
Sometimes I am unable to remove a sideloaded manifest from the classic Outlook on Windows client as the remove button is greyed out. The add-in is able to be removed from the new (preview) Outlook on Windows client.

Only by removing the add-in using the new Outlook on Windows and still using the new version does the add-in no longer affect emails, however, the add-in is still installed on the old Outlook client even when the cache is cleared. I have to wait a few hours for the add-in to be removed from the old client. Also, sideloading an add-in with the same ID does not override the manifest.

So if I want to test a specific feature of the add-in I have to wait for the add-in to be removed.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook® for Microsoft 365 MSO (Version 2308 Build 16.0.16731.20182) 64-bit 
* Operating System: Windows 10 (Colleague is also affected but uses Windows 11)
* Browser (if using Office on the web): _____ 
 
## Expected behavior

The remove button on the new, old Outlook for Windows and OWA is able to be accessed and once the add-in is removed from one of these clients, the changes are reflected across all instantly.

## Current behavior

The classic Outlook on Windows, add-in has the remove button greyed out. 
![image](https://github.com/OfficeDev/office-js/assets/91952323/c92ad464-f941-40e1-b154-37d890f7e845)

In the new Outlook on Windows, the remove button is available but changes are not reflected in the classic Outlook client or OWA until after a few hours.

## Steps to reproduce

Was unable to reproduce consistently but by installing the add-in and using it for a bit I was unable to remove it afterwards.
1. Download the manifest.xml file from: [https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-set-signature](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-set-signature)
2. Side-load the manifest file using the classic Outlook on Windows client

![image](https://github.com/OfficeDev/office-js/assets/91952323/24c252d4-ad31-4ecf-a342-e5c22579d676)

3.  Create a new email, click on the Set My Signature button in the ribbon, and wait for the task pane to load
4. Restart Outlook
5. Check the Get Add-ins and see if the add-in is unable to be removed

## Link to live example(s)

# Provide additional details

1. A colleague with Windows 11 is also experiencing this issue
2. Also noticed similar GitHub issues:
   - https://github.com/OfficeDev/office-js/issues/3605
   - https://github.com/OfficeDev/office-js-docs-pr/issues/1137
3. Created VM with new Office install and saw that I was still unable to remove the add-ins from the classic Outlook app
4. I have tried clearing `%LOCALAPPDATA%\Microsoft\Office\16.0\Wef` and `%localappdata%\Microsoft\Outlook\HubAppFileCache` but it still did not resolve the issue

## Context

As the add-in is not removed from the classic outlook client I have to remove the sideloaded add-in using the new Outlook Client and then wait until the next day before I can try testing on the classic outlook on Windows client.

**Comment by avisheknand** [comment]
Hello,

I was facing this similar issue last week. Had to remove the side load add-in from the OWA, since Outlook on desktop greyed out the remove option. It took around 24 hours to remove from the Outlook desktop after removing from OWA

**Comment by bas-eenhoorn** [comment]
They changed some things, and now they are removed after like at least a day. Its sooo annoying, it worked perfectly. You could remove an addin and it would remove right away. Now you cant even install addins without searching 15 minutes to find the upload screen you screenshot. You have to go to Outlook Desktop, then File, then Info, then Manage Add-Ins, and it will open a web browser with that screen. You cant open that screen from the website itself.

I dont know what they did, but they royally messed it up. Like, it worked perfectly. Now they, for whatever blasphemous reason, remove the upload button, and literally break the delete add-in functionality?

Why do ruin things that work properly lol. Sorry, i needed to rant.

**Comment by gbl-Time** [comment]
I experience the samme issue when installing/uninstalling Outlook office add-in using manifest file. 

The add-in somestimes takes a long time to install/appear in both Outlook desktop as well as Outlook webmail. 

Also, when removing the add-in it takes an unknown amount of hours before the add-in is actually removed. 

Months ago I did not have this problem. Now I do.

**Comment by rajjha-msft** [comment]
Hey @gbl-Time 

Is the issue still a repro for you ?

**Comment by gbl-Time** [comment]
Hey @rajjha-msft 

Yes, we still experience this as a problem. In fact we also see that even when using the "Intergrated Apps" from the Portal, it sometimes takes many hours to add or remove. 

We also see cases where the Office AddIn versions for the same user are different between Desktop New Outlook and Outlook Webmail.

**Comment by ndeleuze** [comment]
@gbl-Time just to confirm, are you still experiencing long install / uninstall time when sideloading an add-in?

For the other issues you have mentioned, please open separate forum posts to address these.

**Comment by gbl-Time** [comment]
Still experience long deployment times, yes. 

Have already created separate forum post: 

https://github.com/OfficeDev/office-js/issues/4171

**Comment by cody-lettau** [comment]
Yes, we continually see 24-72+ hours for deployment/update of add-ins. This is absolutely unacceptable from a developer experience standpoint.

When will this be fixed? @exextoc @davidchesnut

**Comment by ndeleuze** [comment]
I see that this original post is quite old (September 2013), and the original experience mentioned in this post no longer exists for classic Outlook. I will close this case for now.

I also see that @gbl-Time has opened a separate post which has been closed.

@cody-lettau would you be able to open your own post with details describing your specific situation? The more information and suggestions that we get from our customers the stronger case we have during our planning discussions to prioritize. Thank you!
