### ISSUE TITLE
Outlook: Unable to use smart alerts on locally hosted add-in

### ISSUE THREAD

**Issue by JMMM77** [OfficeDev/office-js#3677]
# Provide required information needed to triage your issue
Around a week ago, on the classic Outlook for Windows, when sideloading an add-in with the manifest pointing to a locally hosted add-in, the smart alerts fail to start and delays other add-ins smart alerts from working such as onNewMessageCompose. However, add-ins pointing to files hosted on GitHub work.

This is not an issue for OWA and the new(preview) Outlook for Windows.

Example: [https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-set-signature](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-set-signature)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook® for Microsoft 365 MSO (Version 2308 Build 16.0.16731.20182) 64-bit
* Operating System: Windows 10 (Colleague is also affected but uses Windows 11)
* Browser (if using Office on the web): ______
 
## Expected behavior

Notification is displayed when creating a new email due to the onNewMessageCompose event.

## Current behavior

Add-ins task pane loads for a few minutes and then the notification for the add-in pointing to the files hosted on GitHub is then displayed.

## Steps to reproduce

1. Clone the repo: [https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-set-signature](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-set-signature)
2. Run npm install and then npm start in the Samples/outlook-set-signature directory
3. Create a new email and confirm no notification is displayed and when trying to load the taskpane it loads for a few minutes
4. Remove the add-in and sideload the manifest.xml file located in Samples/outlook-set-signature
5. Create a new email and confirm that a notification is displayed on message compose and the task pane opens within seconds

## Link to live example(s)

# Provide additional details

1. Similar GitHub Issues:
   - https://github.com/OfficeDev/office-js/issues/3395
   - https://github.com/OfficeDev/office-js/issues/2760
2. I have tried clearing %LOCALAPPDATA%\Microsoft\Office\16.0\Wef and %localappdata%\Microsoft\Outlook\HubAppFileCache but it still did not resolve the issue
4. Tried another locally hosted add-in which had the same issue
5. A colleague with Windows 11 is also experiencing this issue
6. The logs generated by "Outlook show The server for this resource is unavailable." and in Event Viewer there is a Error "We're sorry, we couldn't access Office Add-ins signature sample. Make sure you have a network connection. If the problem continues, please try again later."
7. Running the add-in using npm run start: `npm run start:unified` also did not work.
8. TaskPane works as expected but smart alerts do not seem to run.
9. I also ran the add-in in a free linux based app service with the built files of the add-in and the add-in worked as expected.
## Context

When I was developing an Outlook add-in locally that used smart alerts it seemed to stop working, and when I tried going back to a version that was working, it was still not working

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by millerds** [comment]
The npm start command of the project points to the manifest-localhost.xml file of the repo.  This manifest looks for a locally hosted server to get the content from while the manifest.xml file is pointing to the statically hosted files on github.  So the two cases will behave differently.  Note that "start:unified" also depends on the localhost server running in order to work (as well as a current build of office 365 subscription))

I'm a little confused about step 3 of the reproduction steps . . . Is the taskpane taking time to load, but loading successfully, or is failing to load after taking some time?  Are you seeing the local webpack server starting up when running 'npm start'?  Can you also clarify what notification you are expecting when creating a new email (Note that the sample you are pointing to is a signature sample and not a smart alert sample)?

**Comment by JMMM77** [comment]
Hi Millerds,

I have progressed my add in quite a bit since then by developing in OWA and the new Outlook client. So it's slightly different now but I still have the same issue where it does not on the classic Outlook.

I have also raised a ticket with Microsoft directly and they mentioned something to do with security on the classic Outlook is preventing the add in from working but I'm working with them to try and figure it out.

The task pane is stuck on the loading screen then after a while something seems to time out and then the task pane gets displayed but neither the notification or the smart alerts work as in the notifications do not get displayed and the validation (activated on send) does not seem to get ran as the message I sent on the error message did not display but rather an issue with connecting to the add in.

When I run npm start I do see the webpack terminal start and it displays the url of where the application is hosted. I have also deployed the add in to a static web app in Azure creating a separate manifest-azure.xml file which points to a static web app.

Also I have changed the notification of my add in to be displayed onnewmessagecompose and should say something like Open Protective Marking which would then open the task pane, but this is not displayed. I have also added validation on on messages end which as mentioned before does not seem to be updated.

**Comment by millerds** [comment]
If I understand correctly you're add-in actually has 3 parts to it . . . a taskpane, a smart alert, and a notification . . . and none of them work when trying to run the add-in using a local webpack dev server to host the content.  What happens if you try to open the taskpane page in the browser using the localhost URL (something like https://localhost:3000/taskpane.html . . . but your port and file name)?

**Comment by JMMM77** [comment]
Hi Millerds,

Details for my addin:
- Smart Alerts "OnMessageCompose" to add a notification to the top of the email, similar to: https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-set-signature
- Taskpane with a select box and button to set a value on internet headers. It gets the values for the Select box from a json file.
- Smart Alerts "OnMessageSend" to prevent the user from sending an email if they have not selected an option from the taskpane and once they have selected and they try to send again it will update the subject and body with what was set in the json file

The smart alerts does not seem to work because the notification does not get displayed when creating a new email and when sending an email it seems to time out as the add in is supposedly unavailable. I have added the screenshots below.

The add in loads successfully in the browser, taskpane.html is configured to only display the add in if it is from the Outlook client, i.e. OWA, Classic, and New.

Classic Outlook, Taskpane finally loads after a few minutes, notification is still not displayed at all:
![image](https://github.com/OfficeDev/office-js/assets/91952323/4f1206eb-b3a6-4ccd-8137-abc4f7d9d363)

Classic Outlook, failing on send:
![image](https://github.com/OfficeDev/office-js/assets/91952323/dbb183e6-0062-4e03-9bd3-dbed502c4416)

New Outlook, expected result:
![image](https://github.com/OfficeDev/office-js/assets/91952323/0e895316-cc7f-4a1d-b258-eb31e8c9f56a)

In Browser: taskpane.html
![image](https://github.com/OfficeDev/office-js/assets/91952323/fa7d3b1f-b8eb-48d7-98d8-f3da1ca33eed)

In Browser: commands.html
![image](https://github.com/OfficeDev/office-js/assets/91952323/7a657fee-79f2-4fb6-9b2e-f2ac1d28873d)

Please let me know if there is anything else you would like me to test.

**Comment by JMMM77** [comment]
I reverted back to an earlier release to when my add in was working and have been slowly adding in the features from the existing add in and noticed when importing functions from the newly created classification.js file located ./src/classifcation/classifcation.js into either the taskpane.js or launchevents.js file using the below command.

`import {getClassificationHTMLDescriptionByName, getNoClassificationSelectedHTML, getClassificationNamesFromFile} from "../classification/classification.js"`

Below is my file structure (ignore the index.html file as this was needed when deploying to be hosted elsewhere)
![image](https://github.com/OfficeDev/office-js/assets/91952323/067eb129-c56c-4992-bbcf-0303c8bd3ffb)

The add in worked on the new Outlook Client but started having the issue discussed above on the classic Outlook.

I am currently looking for examples or documentation where other people have tried to export functions from a local js file and were able to import it into the taskpane.js and launchevents.js file.

**Comment by millerds** [comment]
That suggests there is something in the classification.js file that is breaking the taskpane.js or launchevents.js file.

Cases where I've seen this usually involve some syntax in the file or in an imported module (imported by classification.js) that is incompatible with the hosting of the add-in.  In the case of smart alerts (and launch events in general . . . which is what your onMessageCompose call technically is) it's using an older js runtime that doesn't support some modern syntax and when it encounters that syntax the load of the js crashes (I know this can happen with webpack injects some code at runtime that isn't compatible with the launch event js runtime).  These can be tricky to figure out since it happens when loading the js by a background process.

One way to narrow this down is similar to what you've already started doing.  Comment out all of classification.js (including import statements) except the method declarations that are being imported.  Once you verify that works you can start uncommenting chunks of code until you figure out the offending parts.

**Comment by JMMM77** [comment]
Hi Millerds,

I have managed to find what is causing the old Outlook to fail.

In my launchevents.js file I changed the markingLevels constant to get its values from the classification.js file. What is odd is that I do the same thing in the taskpane.js file and there didn't appear to be an issue (unless it was cached). I have attached the add in I am working on but you still need to run `npm install` and then `npm run start`.

All the function I am importing into launchevents.js does is gets a value from a json object and returns the string array.

Do you have any thoughts on why it might be failing when importing it into launchevents.js?

launchevent.js
```
// Swapping the markingLevels with the below line will cause the add-in to fail to load
// import {getClassificationNamesFromFile} from "../classification/classification.js"
// const markingLevels = getClassificationNamesFromFile()

const markingLevels = ["Unclassified","Official","Official-Sensitive"]
```

taskpane.js
```
import {getClassificationHTMLDescriptionByName, getNoClassificationSelectedHTML, getClassificationNamesFromFile} from "../classification/classification.js"

const protectiveMarkingSelect = document.getElementById("protective-marking");
const protectiveMarkingSelectButton = document.getElementById("protective-marking-button");
const protectiveMarkingDescription = document.getElementById("marking-message");
const selectedClassificationMessage = document.getElementById("protective-marking-current")
let protectiveMarkingCurrentDescription = document.getElementById("protective-marking-default");
let loggerDiv = document.getElementById("logger-div")

let currentMarking = ""
let markingLevels = getClassificationNamesFromFile()
```

[outlook-2-4-1.zip](https://github.com/OfficeDev/office-js/files/13228421/outlook-2-4-1.zip)

**Comment by millerds** [comment]
The difference between the task pane and the launch events cases is how the code is executed.  The task pane uses WebView2 while the launch events use a js runtime that it a bit leaner.  The js runtime doesn't support all the more modern syntax that WebView2 does.  

When you import the classification.js file the runtime has to parse that file to get the part that you are interested in and that file includes syntax that isn't supported in the js runtime and so the loading fails, and the event handlers can't run.  While I can't remember off the top of my head what all syntax isn't supported, I am fairly certain that the arrow function '=>' you are using in you foreach calls in that file is not supported (I've encountered this problem myself).  You'll have to switch that to a regular function expression (i.e. '() => {}' becomes 'function () {}')

**Comment by JMMM77** [comment]
Hi Millerds,

I tried changing the launchevents and classification.js file to use function () {} instead of () => {} but it still failed.

I am going try and do another test where I am only importing a string constant from a different file into the launchevents.js file to test whether or not it is the import that is causing the add in to fail but it may take some time as my Outlook has somewhere cached the add in and clearing local cache has not removed it.

I will also have a look and see if I can find anything else that is modern and may not be supported by the js runtime.

If you have any other things you would recommend testing please let me know.

**Comment by millerds** [comment]
It looks like there is a limitation that I wasn't aware of.  The launch event code has to be self-contained . . . meaning a single file.  So the import statement by itself it what is breaking your event.  You could use a bundling tool (like webpack) to create a single file from multiple (and polyfill/traspile syntax to be compatible with the js runtime) if you want to keep you code in separate files . . . but that is just for your convenience.

Here is some further documentation that might help you out:
- Runtimes Info: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtimes
- Supported script version (ECMAScript2016): https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest#check-manifest-and-javascript-requirements
- Live debug the event based add-in: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/debug-autolaunch?tabs=windows
- Runtime Logging: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging

**Comment by JMMM77** [comment]
Hi Millerds,

I have bundled the launchevents code with the classifications code in my Vue project using Vite and have managed to get the notification working, so I am finally going in the right direction.

However, I now have an issue where it seems that accessing the values property from the asyncResult from Office.context.mailbox.item.internetHeaders gets stuck on processing, I am able to access the status property but not the values property.

The add in still works on Outlook for Web so I assume its going to be like the case you mentioned earlier how it uses a leaner version of JavaScript and some options are not available.

I am testing different ways for how the generated code gets created and hopefully I will be able to resolve the issue. i.e. remove arrow functions.

**Comment by JMMM77** [comment]
Hi Millerds,

I think I have fixed it now, it appears to have been a combination of a missing null reference check when reading the callback of Office.context.mailbox.item.internetHeaders (which was resolved by adding a null reference check on the values of the AsyncResult), and the internet headers that were being read and passed through having a different case to how they were set (set the internet-header names as lowercase instead of Pascal case), and importing from another file (resolved by bundling the files into one file)

Thanks for your help on this issue.

I just wish there was an easy way to test the launchevents for Outlook for windows since testing it on Outlook on the web behaves differently.
