### ISSUE TITLE
Issues with Outlook for Windows and Office JS after changes are made to the email by the Graph API

### ISSUE THREAD

**Issue by elegault** [OfficeDev/office-js#3678]
# Provide required information needed to triage your issue

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2306, Build 16529.20182 C2R Current Channel and 2310, Build 16830.20002 C2R Beta Channel
* Operating System: Windows 11
* Browser (if using Office on the web): N/A
 
## Expected behavior
- Calls to Office.context.mailbox.item.categories.getAsync() should detect new categories added by the Graph API to the same email
- User should be able to remove that same category using the Outlook UI (e.g. via the Color Categories dialog)

## Current behavior
- Office.context.mailbox.item.categories.getAsync() does not see the new categories
- The Color Categories dialog and the message list in the containing folder continues to show the category that was removed by the user

## Steps to reproduce
1. Select an email without any categories in Outlook for Windows
2. Open the Script Lab add-in and run the "Endpoint URLs and item IDs" code snippet
3. Copy the REST item ID for use in step 6 below
4. Open the Script Lab editor add-in load the "Work with item categories" code snippet
5. Click the "Get categories" button to verify that Office JS sees no categories on the item
6. Open Graph Explorer and issue a PATCH request to https://graph.microsoft.com/v1.0/me/messages/{your message Id from step 3} with the following in the request body (after replacing the text in the braces with a valid category):
```` JSON
{
    "categories": [
        "{any category in your Master Category list}",
    ]
}
````
7. Switch back to Outlook
8. Click the "Get categories" button again. Note that no categories are returned (even after a significant delay).
9. Click the Home tab -> Tags -> Categorize -> All Categories... Ribbon menu item to display the Color Categories dialog. Note that the category added by the Graph PATCH request is correctly visible. 
10. Deselect the same category to remove it and click the OK button.
11. Reopen the Color Categories dialog.
12. Note that the category that was just removed is still visible.

## Link to live example(s)
1. [https://www.screencast.com/t/diriQZtEr](https://www.screencast.com/t/diriQZtEr)

# Provide additional details
1. This behavior (and the steps to reproduce below) does not occur in Outlook Online; only with Outlook for Windows.

## Context
An alternative would be to use Office JS only to set the categories and not Graph. However, this requires additional permissions in the add-in manifest (ReadWriteMailbox) and categories can only be added if they are in the Master Categories list. Graph allows adding categories that aren't in the Master Categories list, and this can be desirable for "one-off" categories (like unique Ids) that we do not want to pollute the user's list with as over time this can amount to several hundred.

**Comment by ztcdsb** [comment]
@elegault This feels like by design, because the reading pane hasn't been refreshed yet.
If you force a refresh by switching to a different item and switching back, add-ins are able to retrieve the category on the item.

This is unfortunate that our API is limited by Outlook's behavior. 

Is this a blocker towards your Add-ins? If so, can you share more details about your users' scenarios?

**Comment by elegault** [comment]
@ztcdsb Is it a blocker? No, but it is a hole where users cannot see changes to an item in the UI elements that should be getting updated. And as I stated in the Context section, we have to use Graph because of the limitations in Office JS. If Office JS can allow for one-off Categories to be added, then this issue wouldn't exist and we wouldn't need to use Graph.

The exact scenario is for using an add-in to upload an email with or without attachments and creating an association with that email with a user selected record in a LOB database. This association is reflected by stamping the email with metadata using categories (e.g. record ids) so the user can see in the message list which record(s) the emails were associated with. Any changes to those categories that the add-in makes should be reflected in Outlook's category UIs, but that is lost if we are forced to use Graph.

**Comment by ztcdsb** [comment]
@elegault Office API only matches the capability of Outlook and Outlook doesn't allows one-off Categories as far as I know.
This is will considered as a new feature request.

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by elegault** [comment]
@ztcdsb You sure can add a category without it being in the Master Categories list using the Outlook for Windows UI, MAPI/OOM and Graph!
