### ISSUE TITLE
Office.context.document.removeHandlerAsync unexpected behavior during development with live-reload

### ISSUE THREAD

**Issue by carruthe** [OfficeDev/office-js#368]
Hi,

Thanks for a great product!  I have an issue to report:

I am currently developing an Excel Add-in.  I created the add-in using the Facebook create-react-app package from NPM and built from there.  One of the great things about that framework is that it uses the WebPack live reload feature, so whenever I make a change to my code, it is automatically recompiled and the add-in reloads itself automatically (without having to close and reopen the Excel document).  This has worked very well, but I noticed that my  `DocumentSelectionChanged` event was being called multiple times for each time the event was called.  Each time the page was live-reloaded, the callback repeat count would increase by one.  

I figured out that it was because I was using an anonymous lambda function as the callback, so the Office JS framework was seeing it as a new callback each time, which makes sense.  However, in the documentation for `Office.context.document.removeHandlerAsync`, it says that if you don't specify a handler to remove, it will remove all handlers for that event.  I tried this, shown in the code below.  The idea is to remove any old handlers, then in the callback to that async call, add the fresh handler back.  

```
        // Remove all old handlers by sending an empty options object
        Office.context.document.removeHandlerAsync(Office.EventType.DocumentSelectionChanged, { }, (result) => {
            if (result.status === Office.AsyncResultStatus.Succeeded) {
                // It always succeeds
               // Add the fresh callback back
                Office.context.document.addHandlerAsync(Office.EventType.DocumentSelectionChanged, (eventArgs) => { this.onExcelSelectionChanged(eventArgs) });
            }
            else {
                console.log("Failed to remove all old DocumentSelectionChanged handlers! " + result.error)
            }
        })
```

This did not seem to have any effect, and the multiple-callback chain remains.  Is it because every time the add-in is live-reloaded, a new global `Office` object is created, and it can't see the callbacks added from the previous Office objects?

I thought it might have to do with the lambda functions, but I tried some vanilla global functions, and it behaved the same.

This is likely only a development issue, but it can be pretty annoying when the program slows to a crawl after a bunch of live-reloads.

Nick

**Comment by serjant** [comment]
I also encountered this issue lately and it still persists

**Comment by grangeryy** [comment]
Hi, @serjant and @RXminuS, does this issue still reproduce to you?

**Comment by grangeryy** [comment]
Close this since no more update. We can reopen if it still persists.
