### ISSUE TITLE
Roaming Settings are sometimes saved, sometimes gone after a refresh, or gone after some time without doing anything, or sometimes exists only in Desktop and not Online, and dont always work in Shared Mailboxes

### ISSUE THREAD

**Issue by bas-eenhoorn** [OfficeDev/office-js#3684]
#### Good day :)

We are implementing Roaming Settings in Outlook in combination with Event Based Activation and Shared Mailboxes.
But it seems Roaming Settings are sometimes saved, but sometimes gone for no reason after a refresh or just gone after some time without doing anything.

## Your Environment
Platform: Online/browser, Desktop.
Host: Outlook

## Expected behavior
I want to attach Roaming Settings to a mailbox.

For example, when setting SetName=123 for mailbox bas-eenhoorn@myemail.com, i want to retrieve that setting from wherever environment i retrieve SetName from that mailbox.

And when setting SetName=ABC for shared mailbox shared-company-box@ourdomain.com, i want to retrieve that setting from wherever environment i retrieve SetName from that shared mailbox.

## Current behavior
I set a simple setting for testing, and read that setting after a reload, the next day, and in other environments.

So I execute this code in our Add-In.

Office.context.roamingSettings.set('test-desktop', 'Value 123');
Office.context.roamingSettings.saveAsync();

Then I reload the addin. Here is where things are not working consistently. I can not seem to find a pattern, but what happened is this:
- Most of the times, the settings are gone after the refresh. I am sure that they are gone.
- Other times the roaming setting is saved. 
- But, this works inconsistently. Because sometimes the setting persists until the next day, but randomly that day, the setting may be deleted.
- And sometimes the setting can be read in my Outlook Online environment, but sometimes they dont in the browser, while still existing in the Desktop App (and im sure ive refreshed my browser to reload the RoamingSettings object).

## Steps to reproduce
Set a RoamingSetting in an addin, in the Desktop App, save it, and read it from the browser, or after a refresh.

I can write some actual test sets, but it just is too inconsistent (for us at least) to precisely write some steps.

## Context
- How has this issue affected you? What are you trying to accomplish?
We use Event-Based activation to automatically insert email signatures when creating a new email. But in a Shared Mailbox environment, people are getting other peoples' signature, because of a roaming setting we have stored in the shared mailbox (a simple "credential"/userId, to retrieve a signature from our server), which returns the wrong signature because the stored userId is not always the current user in shared mailbox.

**Comment by exextoc** [comment]
Can you help us understand if you are seeing the issues in consumer accounts or enterprise accounts?

**Comment by bas-eenhoorn** [comment]
With enterprise vs consumer, do you mean our organisation vs default @hotmail.com accounts? If so, we only use it in our organisation. And the shared mailbox is also in our organisation.

And this is the version of Outlook we use:
![image](https://github.com/OfficeDev/office-js/assets/98084438/300f6769-c4db-4655-935d-4bd282a62b11)

**Comment by exextoc** [comment]
Thanks for reporting this issue. It is in our backlog and we'll be working on it but unfortunately we donot have any timelines to share at this point.

**Comment by bas-eenhoorn** [comment]
Ok. Does that mean that you determined that it _is_ indeed a bug, and a fix will need to be implemented? Because then I know what I can tell our customers who need a feature that depends on this.

**Comment by exextoc** [comment]
Yes we are working on the fix

**Comment by bas-eenhoorn** [comment]
Oh ok. Thank you for informing!

**Comment by exextoc** [comment]
We have fixed the bug, please clear the cache and refresh the browser to test again.

**Comment by bchenhs** [comment]
Hi @exextoc We just started seeing this issue on the webapp yesterday. It persisted after clearing cache and cookies.

The roaming settings persisted when we only reloaded the add-in, but the settings are gone after reloading the main outlook.office.com page.

**Comment by bas-eenhoorn** [comment]
Im sorry, i only now see the comment. I will try if it works next monday when i have time!
