### ISSUE TITLE
Word content control can't clear

### ISSUE THREAD

**Issue by ChienHo** [OfficeDev/office-js#3685]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.16914.41010
* Operating System: Windows 10 Pro version 21H2
* Browser (if using Office on the web): Chrome Version 116.0.5845.188 (Official Build) (64-bit)
 
## Expected behavior
Our add-in uses Content Control to keep track of inserted content.
We create CC using this function
https://learn.microsoft.com/en-us/javascript/api/word/word.paragraph?view=word-js-preview#word-word-paragraph-insertcontentcontrol-member(1)
After some time there are some CC that can not be cleared. 
For security reasons we can't provide the sample file yet. Please take a look at the screencast.
Looks like the CC is out of bound.
Expected behavior: CC can be cleared.

## Current behavior
CC can not be cleared. OfficeJS shows an error
{
"name":"RichApi.Error",
"code":"NotAllowed",
"traceMessages":[

],
"innerError":null,
"debugInfo":{
"code":"NotAllowed",
"message":"The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information.",
"errorLocation":"ContentControl.clear",
"statement":"v.clear();",
"surroundingStatements":[
"var v = context.root._getObjectByReferenceId(\"{ddf193aa-b91b-42f4-afb9-23a242fb468b}{210}\") /* originally getItem(...) */;",
"// >>>>>",
"v.clear();",
"// <<<<<"
],
"fullStatements":[
"var v = context.root._getObjectByReferenceId(\"{ddf193aa-b91b-42f4-afb9-23a242fb468b}{210}\") /* originally getItem(-788654684) */;",
"v.clear();"
]
},
"httpStatusCode":500
}

## Steps to reproduce
We will provide sample file as soon as possible. For now please review the attached screencast to see if you find anything.

## Link to live example(s)
https://gist.github.com/ChienHo/7b905f2d66e95045a78981f55ff0b4fc.js

![clearCC](https://github.com/OfficeDev/office-js/assets/30323038/b4b2c834-7196-47c9-9cd8-9e1530f0a4ce)

## Context
Our add-in function needs the CC to be cleared. This issue prevents out add-in from functioning.

## Useful logs
{
"name":"RichApi.Error",
"code":"NotAllowed",
"traceMessages":[

],
"innerError":null,
"debugInfo":{
"code":"NotAllowed",
"message":"The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information.",
"errorLocation":"ContentControl.clear",
"statement":"v.clear();",
"surroundingStatements":[
"var v = context.root._getObjectByReferenceId(\"{ddf193aa-b91b-42f4-afb9-23a242fb468b}{210}\") /* originally getItem(...) */;",
"// >>>>>",
"v.clear();",
"// <<<<<"
],
"fullStatements":[
"var v = context.root._getObjectByReferenceId(\"{ddf193aa-b91b-42f4-afb9-23a242fb468b}{210}\") /* originally getItem(-788654684) */;",
"v.clear();"
]
},
"httpStatusCode":500
}

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by xiruatms** [comment]
Thanks for reporting this. Considering there're some by-default scenarios in which content control can't be cleared (that's also why this expected exception was designed to be thrown from this API), I need to fully understand your case to see whether it's an expected scenarios or unexpected one. That'll be much helpful if you can provide us with your sample document.
