### ISSUE TITLE
Outlook Add-In: Location Persistence in Required Attendees

### ISSUE THREAD

**Issue by ekmatrix** [OfficeDev/office-js#3686]
When using the add-in to clear a location field in an event, the location field in Outlook behaves as expected, getting cleared as intended. However, an issue arises concerning the requiredAttendees field. Despite clearing the location, it persists in the requiredAttendees field, resulting in inconsistencies within event details and causing user frustration.

## Your Environment
* Platform: Mac and Windows
* Host: Outlook on desktop, working in OWA
 
## Expected behavior
When using the add-in to clear the location in an event, it would clear the location field and remove it from the requiredAttendees field, resulting in a consistent event.

## Current behavior
While the location field in Outlook is cleared as expected, the location persists in the requiredAttendees field.

## Steps to reproduce
1. Open Outlook and navigate to the event for which you want to clear the location.
2. Use the Outlook Add-In to clear the location field in the event.
3. Observe that the location field in the event is correctly cleared.
4. Check the requiredAttendees field, and note that the location persists there despite clearing it from the location field.

**Comment by exextoc** [comment]
What do mean by "Use the Outlook Add-In to clear the location field in the event."? Do you mean setAsync with empty location "".
Can you share the code snippet for the same.

**Comment by ekmatrix** [comment]
Indeed, as you mentioned, we clear the location field in the event with an empty string "" as follows:

```typescript
const setLocation = async (roomId) => {
      isLocationUpdate.current = true;
      appItem.location = [roomId];
      await mailboxService.setBookingLocation(appItem.location);
      setAppItem(appItem);
};
```

We have:

```typescript
async setBookingLocation(bookingLocations) {
    this.resetLocation()
    .then(() => {
      let appointmentLocations = [];
      bookingLocations.forEach(locid => {
        let location = this.toEnhancedLocation(locid.trim());
        appointmentLocations.push(location);
      });
      let item = Office.context.mailbox.item;
      item.enhancedLocation.addAsync(appointmentLocations);
    });
};

toEnhancedLocation(locationid) {
    return {
      "id": locationid,
      type: Office.MailboxEnums.LocationType.Room
    };
  };

async resetLocation(): Promise<void> {
    let item = Office.context.mailbox.item;
    let existingLocations = [];
    item.enhancedLocation.getAsync(locations => {
      locations.value.forEach(loc => {
        existingLocations.push(loc.locationIdentifier);
      });
      item.enhancedLocation.removeAsync(existingLocations);
    });
};
```

We have also attempted to explicitly clear the requiredAttendees field after the location is cleared. However, this is also not working on desktop (Windows and Mac). On desktop platforms, the location persists in the requiredAttendees field, whereas in OWA, everything works as expected.

**Comment by exextoc** [comment]
We are not able to repro this at our end, removing the location from location field will not remove it from recipients' field, that's expected but when it is removed from recipient field, it should work. Can you please share a video showcasing your scenario, it can help us understand better.

**Comment by ekmatrix** [comment]
Upon further examination, I would like to highlight that the issue persists in our current version (Version 2309, Build 16.0.16827.20130). It appears that switching to the "new Outlook" resolves the problem, but unfortunately, this alternative is impractical for us as not all users run the new UI.

To provide additional context, here is the piece of code we have been using in an attempt to explicitly clear the requiredAttendees field:

```Typescript
  async removeRequiredAttendeesLocation(){
    let item = Office.context.mailbox.item;
    return item.requiredAttendees.getAsync((res) => {
      if(res && res.value){
        let attendees = res.value;
        let index = attendees.findIndex(attendee => attendee.emailAddress === item.location);
        if(index > -1) {
          attendees.splice(index, 1);
          return item.requiredAttendees.setAsync(attendees, ()=>{});
        }
      };
    });
  }
```

https://github.com/OfficeDev/office-js/assets/145109141/73689c2e-94e9-48f7-b2d4-315db99cff1b

**Comment by exextoc** [comment]
Can you share on what versions of Outlook are you facing this issue on Outlook for MAC and Windows?
Also can you try running following code sample from [Script Lab](https://appsource.microsoft.com/en-us/product/office/wa200001603?tab=overview). First Add Locations and then Remove Locations and check if  location is being removed from recipients or not?
<img width="786" alt="ScriptLabSample" src="https://github.com/OfficeDev/office-js/assets/28549921/46fe775c-4529-4893-b366-6bfe0b712df5">

<img width="345" alt="RunCodeTaskpane" src="https://github.com/OfficeDev/office-js/assets/28549921/616bc3c5-2925-45e6-bba9-9ee23ce0d9f2">

For more details on how to run Script Lab samples check [Explore Office JavaScript API using Script Lab](https://learn.microsoft.com/en-us/office/dev/add-ins/overview/explore-with-script-lab)
