### ISSUE TITLE
When opening a taskpane in Outlook for Windows the taskpane doesn't get focus

### ISSUE THREAD

**Issue by ilbrando** [OfficeDev/office-js#3687]
# Provide required information needed to triage your issue

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2308 build 16731.20170
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome
 
## Expected behavior
When opening a taskpane for `MessageReadCommandSurface` in an email, I would expect the taskpane to recieve focus as it does in the web browser version of Outlook.

## Current behavior
The taskpane doesn't recieve focus in Outlook for Windows.

## Steps to reproduce
1. Open an email
2. Open/activate a taskpane

## Context
Our customers typically pins the taskpane and want to interact with each time they open an email. When using Outlook for Windows this requires them to use the mouse.

**Comment by samantharamon** [comment]
Hi @ilbrando,

Thanks for reporting this. I'll investigate this further and get back to you with more information.

**Comment by samantharamon** [comment]
Thanks for your patience, @ilbrando.

I tried to reproduce this using the Script Lab Outlook add-in in Outlook on Windows (same version you specified) by opening the task pane from a message in the Reading Pane and in a separate window, but I'm able to tab through the elements/objects in the task pane. With the add-in you're testing, are there any dialogs that appear after you select the add-in button from the ribbon, but before the task pane appears? If possible, are you able to also share a video of what you're experiencing?
