### ISSUE TITLE
Addin not present!

### ISSUE THREAD

**Issue by cliplicht** [OfficeDev/office-js#369]
Platform: Mac OSX Mojave (latest)
Product: Outlook
Version: 16.22.0 (19012002)

I loaded the add-in over the manifest.xml into Outlook via the Store button. The add-in is also shown in the Store UI but no CustomTab is shown in Outlook!

on the Windows platform the add-in works fine!

Issue encountered while completing this quick start: https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code

**Comment by markdon** [comment]
The name for this issue could be improved. This has been answered on [StackOverflow](https://stackoverflow.com/users/7968093/mac-outlook-extensibility) so _could_ be closed if that is going to be the end of it.

However it does seem like an issue to me that Outlook on Mac fails to show any of the buttons that are supposed to be in a Custom Tab. Outlook on web shows buttons from all Custom Tabs collapsed into one list of of buttons (This is two custom tabs with two buttons each):
![Custom Tab buttons in Outlook on web](https://user-images.githubusercontent.com/9063681/73038361-4452ed00-3ea6-11ea-800a-f5120e6b96b4.png)

**Comment by exextoc** [comment]
@cliplicht In Outlook on Mac, the CustomTab element is not available so you'll have to use OfficeTab instead https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/customtab
