### ISSUE TITLE
Office Outlook Network Cache

### ISSUE THREAD

**Issue by jonshuang** [OfficeDev/office-js#3690]
Hi, we have developed an Outlook web add-in. It seems to be permanently adding to and caching the network requests files in the `/Users/*user*/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/WebKit/NetworkCache/Version 16/Records/**/Resource` folder. 

Some users have over 3 GB in that folder. Is there a way we can clear this programmatically or without manually going to the folder and deleting it? I've looked in Outlook settings and could not find a way to clear this in the app.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook 16.76.2 (23082700)
* Operating System: Ventura 13.5.2
* Browser (if using Office on the web): N/A
 
## Expected behavior
We've looked at the article: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#clear-the-office-cache-on-mac and it says the cache should be cleared by reloading the add-in but that does not seem to be the case. 

## Current behavior
On each load, it adds new files and about 22mb to the folder without deleting anything. I have files very old in this folder (dating from since i've installed the add-in).

## Steps to reproduce

1. Load an add-in
2. See that there's files added to the `/Users/*user*/Library/Containers/com.microsoft.Outlook/Data/Library/Caches/WebKit/NetworkCache/Version 16/Records/**/Resource` folder (network files)
3. Verify that re-loading the addon does not delete anything, but adds to it

**Comment by besiler** [comment]
Hi @jonshuang , I'm from the Outlook add-ins team and wanted to follow up on this issue. Are you still experiencing the issue or did you find a solution?
