### ISSUE TITLE
Calling `getReviewedText` navigates document to the changes

### ISSUE THREAD

**Issue by JDuligall** [OfficeDev/office-js#3691]
When calling `getReviewedText` on a `Word.Range` the document will be scrolled to show the changes. This is undesirable because we want to extract all the `Original` and `Current` text from the document, without the view jumping around.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.77
* Operating System: Ventura 13.5 (22G74)
* Browser (if using Office on the web): N/A
 
## Expected behavior
Reviewed text is returned without scrolling the document.

## Current behavior
When reviewed text is called, the document is scrolled to the changes that are being returned. The document view should not change.

## Steps to reproduce
1. Open this file: [getReviewedText_scroll_example.docx](https://github.com/OfficeDev/office-js/files/12641304/getReviewedText_scroll_example.docx)
2. Run the following code snippet:
```
  await Word.run(async (context) => {
    const body = context.document.body;

    const range = body.getRange(Word.RangeLocation.whole)

    const reviewedText = range.getReviewedText(Word.ChangeTrackingVersion.original)

    await context.sync();

    console.log(reviewedText)
  });
```
3. Notice the document is scrolled to the 3rd page which includes the changes.

## Context
Our users are confused and think the software is buggy if the scroll view changes unexpectedly without their input.

**Comment by JHJ-MS** [comment]
Hi @JDuligall, thanks for helping us find this issue, and sorry for the inconvenience it provided.  I could reproduce this issue. I also found this behavior is different from Word online. I have opened an internal work item #8353434 to track it. Thanks.

**Comment by ghost** [comment]
Any updates on this? We rely heavily on getReviewedText for our add-in that facilitates working with redline changes, and it's extremely disorienting to have the document jump around constantly as we pull this data.

**Comment by zhenhuangMSFT** [comment]
Hi @rally-chad, I am sorry to notify you that there is still no update yet. We plan the work item based on the priority. We will be glad to help prioritize this work-item if you provide more business justification details. Thanks!

**Comment by hiemanshu** [comment]
We're facing the issue as well with our word add-in. We use a `DocumentSelectionChanged` event to call the `getReviewedText` to get the latest version of the change, and populate a search field in our addin, to allow the user to search an online repo for that text, calling `getReviewedText`, causes the document to scroll to the next change, which could be many pages below, breaking our users core workflows

**Comment by ghost** [comment]
Yeah this is a huge problem/blocker for us.

Our add-in helps the user respond to redlines made by a third party by using generative AI to summarize changes. To gather these changes, we iterate through paragraphs on app start and content change, using `getReviewedText` to get original and current text. As a consequence, the document rapidly jumps around.

I've explored work-arounds like using `getTrackedChanges` to assemble our own previous/current text, but this seems difficult (maybe impossible) as a `TrackedChange` of type Deleted doesn't give us the original text.

**Comment by hiemanshu** [comment]
We managed to work around the issue, by getting text back as Ooxml, and parsing that.

```
const parseOoxmlText = (ooxml: string) => {
  const parser = new DOMParser()
  const ooxmlDoc = parser.parseFromString(ooxml, "text/xml")

  const textBlocks = Array.from(ooxmlDoc.getElementsByTagName("w:t"))

  let extractedText = ""

  textBlocks.forEach((textBlock) => {
    extractedText = `${extractedText + textBlock.innerHTML}\n`
  })

  return extractedText
}

const loadWordTextSelection = () => {
  Word.run(async (context) => {
    const range = context.document.getSelection()
    range.load(["isEmpty", "text"])
    await context.sync()

    if (range.isEmpty) return

    const reviewedTextXml = range.getOoxml()
    await context.sync()

    const reviewedText = parseOoxmlText(reviewedTextXml.value)
    if (reviewedText.length) {
      searchText.value = reviewedText
      // flag our text as selected from the document (for event tracking)
      searchTextSource.value = "selected in document"
    }
  })
}
```

**Comment by ghost** [comment]
I tried a similar OOXML workaround and even though I was able to construct the original and current text from it, it's not feasible for us due to the performance cost of syncing the OOXML.

We operate on `Word.Paragraphs`, and some of our test documents can be like 50+ pages, 800+ paragraphs. We can load and process everything in < 5 seconds using `getReviewedText`, but that jumps to over 5 minutes (!) when syncing OOXML for each paragraph. 

I tried to avoid syncing for each by using `getTrackedChanges` to detect which paragraphs were worth doing OOXML loading/parsing in a second pass, which drops the time down a bit, but this scroll bug also seems to happen when calling `getTrackedChanges` so that's not an option for us either. :(

**Comment by jipyua** [comment]
hi @JDuligall @hiemanshu  thanks for reporting this issue and sorry for the late response, it takes some time for us to investigate and fix the root cause. Now the bug has been fixed and in the process of deployment. It should be available early next month together with June monthly update. thanks.

**Comment by hiemanshu** [comment]
> hi @JDuligall @hiemanshu thanks for reporting this issue and sorry for the late response, it takes some time for us to investigate and fix the root cause. Now the bug has been fixed and in the process of deployment. It should be available early next month together with June monthly update. thanks.

Thanks for the update @jipyua. Glad to see it's getting fixed!
