### ISSUE TITLE
ReOpen: Office APIs failing with internal error 5001

### ISSUE THREAD

**Issue by vikramsw** [OfficeDev/office-js#3694]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: MS Outlook
* Office version number: _ outlook version 16.77 and New UI mode._____
* Operating System: _____MacOS 12 and 13_
* Browser (if using Office on the web): _Not Applicable_____
 
## Expected behavior

Office APIs do not randomly fail with internal errors
``
## Current behavior

Office API calls randomly fail with

code: 5001
name: Internal Error
message: An internal error has occurred.

1. In the outlook classic mode issue is not seen. 
2. Issue is with only attachments
3. Inline text in the message body is getting monitored.
4. Issue seems specific to outlook version 16.77 and New UI mode.

## Steps to reproduce

 Getting this error 5001 in getAttachmentContentAsync() call. Its intermittent issue.

Setup details:
macOS Monterey 12.6.6.
Outlook version 16.77 
Outlook New UI

Error string :
{"name":"Internal Error","message":"An internal error has occurred.","code":5001}

Steps to Repro:

Make sure outlook addin is loaded.
compose a mail item in popped up window
Add message body, to , cc lists and add an attachment

## Link to live example(s)

# Provide additional details

## Context

Issue affects the functionality of Symantec's DLP Outlook Addin.
In absence of Access to the Attachments, The Symantec DLP Agent is unable to run Detection on the message and can't detect sensitive content.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by vikramsw** [comment]
Please note that this issue is related to:
https://github.com/OfficeDev/office-js/issues/2386

**Comment by ikexq** [comment]
It may also be related this one:

https://github.com/OfficeDev/office-js/issues/2658

 I am able to repro the issue with the same project available on that ticket (macOS w/ the same version of Outlook).

**Comment by exextoc** [comment]
Can you please share the diagnostics ID to help us understand the issue better. You can follow below steps:
Open Outlook Mac
Repro the issue.
Collect diagnostics data by Clicking on "Help" -> "Collect Diagnostics" 
Share diagnostics ID

**Comment by ikexq** [comment]
Looks like the issue was fixed for us with build 16.77.1 that was released yesterday. Tried to repro with that build, and was unable to.

**Comment by exextoc** [comment]
Thanks for confirming, Issue is fixed.
