### ISSUE TITLE
Issue while setting logBase of a horizontal bar chart

### ISSUE THREAD

**Issue by SanjitKumarr** [OfficeDev/office-js#3695]
# Provide required information needed to triage your issue
When trying to set log base value of an valueAxis in Chart. Excel Api is throwing error.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:  Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Beta
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

Excel Api should set values of log base provided.
## Current behavior

When I'm trying to set logBase value of a valueAxis for horizontal bar chart. Excel API throws error : RichApi.Error: This operation is not permitted for the current object.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by SanjitKumarr** [comment]
Code to reproduce the issue : `  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getItem("Sample");
    let chart = sheet.charts.getItemAt(0);
    let axis = chart.axes.valueAxis;
    axis.logBase = 50;
    await context.sync();
  });`

**Comment by dingjin-ms** [comment]
Hi @SanjitKumarr , thank you for raising the problem! We have opened an internal bug item #8368546 to track this issue. We'll let you know when we have progress on the investigation.

**Comment by joshuawwright** [comment]
@dingjin-ms I have the same issue using logBase on Excel Online. The problem does not occur for me on Windows.

**Comment by penglongzhaochina** [comment]
Hi @joshuawwright  @SanjitKumarr , We have a workaround here:
You can set the axis.scaleType to "Logarithmic" before you set the axis.logBase.
This is the gists: https://gist.github.com/penglongzhaochina/b08285ab477ad5b7a89fc21f35d2955a

I hope that this can unblock you.
Thanks.

**Comment by XuanZhouMSFT** [comment]
Hi @joshuawwright @SanjitKumarr, thanks for reporting this issue and your patience. Now the bug should have been fixed and deployed, you should be able to try the latest fix. Please feel free to close this case or let us know other feedbacks. Thanks.

**Comment by joshuawwright** [comment]
@XuanZhouMSFT Thanks so much for the update and for fixing the issue!
