### ISSUE TITLE
Partner Center- Marketplace Access

### ISSUE THREAD

**Issue by CMiCIntegration** [OfficeDev/office-js#3696]
## Post how-to questions about your code on Microsoft Q&A

How do I give my team access to a Marketplace dashboard when registering my product(An Outlook Add-In)? Can multiple users have access to view the published report from Microsoft?

**Comment by besiler** [comment]
Hi @CMiCIntegration , I'm from the Outlook add-ins team. Are you still having this issue? If so, I have some followup questions for you:

Is the Marketplace dashboard a dashboard within Partner Center (https://partner.microsoft.com/dashboard/home)? I'm trying to figure out which dashboard this is specifically to see if there's a way to get access for multiple users.
