### ISSUE TITLE
Recommended way of Implementing WEBSSO in my new Outlook Add-In

### ISSUE THREAD

**Issue by CMiCIntegration** [OfficeDev/office-js#3697]
## Post how-to questions about your code on Microsoft Q&A

I'm trying to implement WEBSSO in my new Add-In but experiencing some issues with getting the session cookies from the dialogue box(webpage) into my add-in. How do I manage this?

**Comment by timwan10** [comment]
displayDialogAsync has ways to send data back to the main add-in: 

https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins

Office.context.ui.messageParent
