### ISSUE TITLE
Why the page shows become big to normal?

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#37]
**Question 1:**
   When shows taskpanel or dialog, the html page size become big to normal.
 
![screen](https://user-images.githubusercontent.com/3182964/33316163-eef66944-d46d-11e7-8b7e-666eb887608b.gif)

**Question 2:**
   JS Warning dailog shows.
   
   <img width="275" alt="5" src="https://user-images.githubusercontent.com/3182964/33316152-e22fcbba-d46d-11e7-8fdd-c094b8a2b241.png">

**Environment**
<img width="762" alt="2" src="https://user-images.githubusercontent.com/3182964/33316215-23da65a2-d46e-11e7-98a1-f784b30b5bab.png">

**Comment by hongbo-miao** [comment]
Hi @hengchengfei what do you mean "become big to normal"? I didn't see any size change in GIF.

**Comment by hengchengfei** [comment]
@Hongbo-Miao 
yes

https://user-images.githubusercontent.com/3182964/33316163-eef66944-d46d-11e7-8b7e-666eb887608b.gif

**Comment by JuaneloJuanelo** [comment]
still we dont see any significant size increase, but anyways if this is still an issue please let us know.
