### ISSUE TITLE
Add Recipient to Appointment in Compose Throws Error

### ISSUE THREAD

**Issue by nrakochy** [OfficeDev/office-js#370]
Setting the recipients via the office.js api is throwing an error.

## Expected Behavior
The array passed to the API should correctly set the recipients.

## Current Behavior
Both `setAsync` and `addAsync` are throwing `Sys.ArgumentException: Sys.ArgumentException: Value does not fall within the expected range.` when receiving array of email addresses to set, which I have tried on these attributes in Compose mode on a new Outlook Appointment- 
```
var ITEM = Office.context.mailbox.item
ITEM.requiredAttendees
ITEM.optionalAttendees
ITEM.bcc
ITEM.cc
```
with these as params on with all variations - 
```
[{emailAddress: 'test@example.com', displayName: 'Test Name'}]
['test@example.com']
```

It would appear that `line 8046` from `outlook-mac-16.00.js`
```
if (Array.isInstanceOfType(n))
```
within this block
```
 setAddHelper: function(n, t, i) {
            window.OSF.DDA.OutlookAppOm._throwOnOutOfRange$i(n.length, 0, 100, "recipients");
            var h = r.CommonParameters.parse(t, !1);
            var e = [];
            if (Array.isInstanceOfType(n))
                for (var u = 0; u < n.length; u++)
                    if (String.isInstanceOfType(n[u])) {
                        r.ComposeRecipient._throwOnInvalidDisplayNameOrEmail$p(n[u], n[u]);
                        e[u] = r.ComposeRecipient._createEmailDictionaryForHost$p(n[u], n[u])
                    } else if (r.EmailAddressDetails.isInstanceOfType(n[u])) {
                        var f = n[u];
                        r.ComposeRecipient._throwOnInvalidDisplayNameOrEmail$p(f.displayName, f.emailAddress);
                        e[u] = r.ComposeRecipient._createEmailDictionaryForHost$p(f.emailAddress, f.displayName)
                    } else if (Object.isInstanceOfType(n[u])) {
                        var c = n[u];
                        var o = c.emailAddress;
                        var s = c.displayName;
                        r.ComposeRecipient._throwOnInvalidDisplayNameOrEmail$p(s, o);
                        e[u] = r.ComposeRecipient._createEmailDictionaryForHost$p(o, s)
                    } else
                        throw Error.argument("recipients");
                    }
            else
                throw Error.argument("recipients");
            var l = this;
            window.OSF.DDA.OutlookAppOm._instance$p._standardInvokeHostMethod$i$0(i ? 21 : 22, {
                recipientField: this._type$p$0,
                recipientArray: e
            }, function(n) {
                return n
            }, h._asyncContext$p$0, h._callback$p$0)
        }
```
is throwing the error. That said, `Array.isArray(arr)` is returning true before going into the library (though this may be unrelated, I don't know)

## Steps to Reproduce, or Live Example
```
var arr = [{emailAddress: 'test@example.com', displayName: 'Test Name'}]
Office.context.mailbox.item.requiredAttendees.addAsync(arr)
```
Cf. [docs for requiredAttendees](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/preview-requirement-set/office.context.mailbox.item.md#requiredattendees-arrayemailaddressdetailsrecipients)

## Context
Ideally,  I would like to have a hook into SEND event, so that I can set params when the invite is sent.

* [Since that is not an option in Office.js at the moment on Windows and Mac](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/10964871-add-itemsend-event-so-add-in-can-cancel-email),  I am planning to set an email address that can handle incoming data via the [FunctionFile](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/functionfile), thus the need to `addAsync` on recipients, though I am certainly open to suggestions on best practice here / other APIs that might be better suited for configuring app data without needing the click.

## Your Environment

* Platform: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.21
* Operating System: MacOS High Sierra (10.13.6)

---

**Comment by nrakochy** [comment]
Is this the correct forum for bug reports? Where should I report issues?

**Comment by nrakochy** [comment]
Added a [StackOverflow question](https://stackoverflow.com/q/54680835/3100284) where I will happily award points...

**Comment by macOutlookExtensibility** [comment]
Verified on latest version 16.23 and working fine. Could you please update to latest version and try.

**Comment by nrakochy** [comment]
I added screenshots to the Stackoverflow issue which show `line 8046` throwing an exception on the array

**Comment by nrakochy** [comment]
Caused by iFrame `window` conflict.
