### ISSUE TITLE
Office.context.ui undefined in mobile dialog

### ISSUE THREAD

**Issue by AlexandrNetsvetov** [OfficeDev/office-js#3700]
I have a dialog that is displayed via `displayDialogAsync` which redirects the user off to an authentication server. Once they have authenticated, they are redirected back to the app where some processing is done before trying to call `Office.context.ui.messageParent()` is used to communicate the auth result back to the parent app and close the dialog.
That works for me on desktop application and on the web version but this fails on mobile as `Office.context` is an empty object so `ui` is undefined.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Android Outlook app
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 4.2334.0 (42334808)
* Operating System: Android
* Browser (if using Office on the web): -
 
## Expected behavior
Office.context.ui should be initalized correctly on mobile version inside a dialog window.

## Current behavior
When the app is loaded, we are seeing warnings of `Warning: Office.js is loaded outside of Office client`. After that I can't work with `Office.context` because is empty.
I think this is happening because add-in was opened inside outlook application but dialog window opened as browser tab.

## Context
This is preventing us from completing an authentication flow on mobile devices.

### Add-in opens into Outlook app
![mobile-login-app](https://github.com/OfficeDev/office-js/assets/137889240/845465ba-2dff-444a-b8ee-441721d60b1f)

### Context is undefined after redirect from third part service on a dialog page.
![ui-undefined1](https://github.com/OfficeDev/office-js/assets/137889240/8ac3eaac-57ef-4ecd-81df-6b1a5759c730)

### Office error
![error1](https://github.com/OfficeDev/office-js/assets/137889240/32af3be4-be61-4fdf-b623-7a181187b89a)

**Comment by docharrod85** [comment]
My team is experiencing a very similar issue here on the mobile application. We are able to launch the dialog, but it seems we cannot communicate back to the parent script. The authentication flow works perfectly in the browser based version. Had suspicion of cross domain messaging being the problem, so we tried specifying * as the target origin and still had no luck on mobile.

**Comment by AlexandrNetsvetov** [comment]
> My team is experiencing a very similar issue here on the mobile application. We are able to launch the dialog, but it seems we cannot communicate back to the parent script. The authentication flow works perfectly in the browser based version. Had suspicion of cross domain messaging being the problem, so we tried specifying * as the target origin and still had no luck on mobile.

Yep, looks like the same problem.

**Comment by docharrod85** [comment]
@AlexandrNetsvetov we had some luck today so I wanted to share in case it may help you. 

In our hosted add in package we reference 

<script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js" type="text/javascript"></script>

Following that, it seems the messageParent was working fine for us. 

In addition, before calling messageParent, be sure the UI is in the respective add-in domain. We found cross domain messaging failed completely in mobile dialog. We managed to get our flow to succeed like this. 

1. Open a page with a shared domain of the addin and have it immediately redirect to our Auth page.

2. Once successful, we redirect from our auth UX back to another page within the add in domain. This url contains an auth param.

3. Finally, we are able to leverage messageParent to return the authentication info to the app. 

Maybe this will help you out.

**Comment by AlexandrNetsvetov** [comment]
@docharrod85 Thanks for advice, I'll test it and I'll give you response here.

**Comment by exextoc** [comment]
@AlexandrNetsvetov  Are you still facing the issue ?

**Comment by AlexandrNetsvetov** [comment]
@exextoc We have some problems with our environment and I can't test it now.
I hope to check it on next week.
