### ISSUE TITLE
[Outlook add-in] getCallbackTokenAsync failing for multiple clients

### ISSUE THREAD

**Issue by truchonh** [OfficeDev/office-js#3703]
# Provide required information needed to triage your issue
This method throws those errors bellow consistently (the exact error differs from users to users)
- `[InternalServerError] The Exchange server returned an error. Please look at the diagnostics object for more information.`
  -> diagnostics object does not have extra information other than the clientRequestId
- `[HTTPRequestFailure]  The request has failed. Please look at the diagnostics object for the HTTP error code.`
  -> diagnostics object has the property `HTTPCode: 403`
 
## Your Environment

* Platform: PC desktop for both clients
* Host: Outlook
* Office version number: Unknown, but the JS api shows version 1.12 and 1.13 for each clients. I assume a fairly recent version of Outlook
* Operating System: Windows 10
* Browser (if using Office on the web): -
 
## Expected behavior

We expect the method to either return a more understandable error or the requested callbackToken.

## Current behavior

The method getCallbackTokenAsync throws an exception.

## Steps to reproduce

1. Opening the add-in with an email from the inbox opened
2. Waiting for the init event of Officejs
3. calling getCallbackTokenAsync 

## Link to live example(s)

1. ______
4. ______
5. ______

# Provide additional details

The add-in has `ReadItem` permission requirement and all other OfficeJs calls with the same permission level are successful, so I do not believe the issue is related to wrongly configured permissions on the add-in side. Additionnaly, most of our clients are able to use the add-in without issues. Only a select few have issues with this method. 

Also, I'm not sure if this is related, but the method getUserIdentityTokenAsync also fails in the same ways for the same users, but our code can fallback to an other way to identify users, so it is not of immediate concern to us.

## Context

I am aware of mentions of EWS connectivity issues that were resolved this year in Exchange (https://techcommunity.microsoft.com/t5/exchange-team-blog/released-february-2023-exchange-server-security-updates/ba-p/3741058, https://techcommunity.microsoft.com/t5/exchange-team-blog/released-march-2023-exchange-server-security-updates/ba-p/3764224). We have not confirmed yet if those clients have on-premise Exchange and if they are up to date.

## Useful logs

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Adrian-MSFT** [comment]
Hi @truchonh,

Can you please provide an outlook version for which this is failing? This would help us try to reproduce the issue on our end more effectively.

Also, how many users are affected by this?
Are these users on-prem or not?
Any additional info you may have would help us narrow this down.

**Comment by truchonh** [comment]
Hello @Adrian-MSFT, thanks for taking the time to look into this.

I can identify 8 different users. Only one has the HTTPRequestFailure error, and the other 7 have the InternalServerError. 

From logs, I can see the version number of the Edge webview (117.0.2045) as well as a "_host_Info" (Outlook$Win32$16.02$fr-FR$$$$0).

I also have those ClientRequestIds that are attached to the diagnostic object in the failed request. Can I do anything with those ?

Additionally, one of those users either had the HTTPRequestFailure mentionned above, or often a more generic NetworkError in the same situation. Because of that user, we implemented a retry mechanism for Officejs api calls in case the issue comes from network instability, but this did not change the frequency at which those errors occurred.

I know it is not much information, but it's all I have available. Any general advice on how to resolve issues with the Office-js api is welcomed. As the add-in is calling Exchange servers we do not have access to, it is very difficult to identify how to solve problems that occur on a single client's infrastructure only.

**Comment by truchonh** [comment]
@Adrian-MSFT One of our affected users has Outlook version 2302 build 16130.20810.

**Comment by truchonh** [comment]
@Adrian-MSFT  The other user reporting the issue has Outlook version 2310.

In total, about 1/10 of all users has experienced OfficeJs errors that we could not recover from. The vast majority are vague `Internal Error` with code 5010, but those two cases described in this issue were a bit more specific, so I was hoping we could get help.

Thank you.

**Comment by Adrian-MSFT** [comment]
Hi @truchonh can you share a minimal code snippet that reproduces the issue? I'm not able to repro this in version 16130.20810, but I can try again with your code snippet.

In your original post, you mention "Platform: PC desktop for both clients". What 2 clients do you mean?
