### ISSUE TITLE
Method getAccessToken does not work when implementing SSO in Event-Based Activation in Outlook

### ISSUE THREAD

**Issue by bas-eenhoorn** [OfficeDev/office-js#3706]
Hello. We are using Event-Based Activation (EBA) in Outlook in combination with Single Sign-On. 

We insert a signature when creating a new mail. We do this by signing in on our server and requesting the users email signature.

This works correctly in Office Online (web). But when requesting an access token using the getAccessToken method, the 'then' or 'catch' method is never invoked.

## Your Environment
* Platform: PC desktop (does not work), Web (works correctly)
* Host: Outlook
 

## Expected behavior
I expect an access token to be returned, or at least an error to be thrown.

## Current behavior
The method getAccessToken does never invoke the promise. No AccessToken is returned, and we cant catch an error, as no error seems to be thrown. A try catch around the code also does not catch the method.

## Steps to reproduce
1. Set up an Outlook Add-In for Event-Based Activation.
2. Bind the "onMessageComposeHandler" event.
3. In the handler, use the code below.
4. The then-callback , nor the error handler, will never be invoked (on Desktop).
```
OfficeRuntime.auth.getAccessToken({ forMSGraphAccess: true }).then(function (token) {
    _log('getAccessToken.then: ' + token);
}).catch(function (e) {
    _log('getAccessToken.catch', e);
});
```

# Additional details
- Ive tried all variants, but none seem to work. OfficeRuntime.auth.getAccessToken / Office.auth.getAccessTokenAsync / Office.context.auth.getAccessTokenAsync.
- Ive tried with and without options parameters: { forMSGraphAccess: true }
- We have well known domains specified on our server: "/.well-known/microsoft-officeaddins-allowed.json"
```
{
  "allowed": [
    "https://eformity.net/Scripts/Office/Outlook/eformity.office.outlook.js",
    "https://staging.eformity.net/Scripts/Office/Outlook/eformity.office.outlook.js"
  ]
}
```

**Comment by Oleg-O** [comment]
Have you been able to make it work?
