### ISSUE TITLE
Office.context.mailbox.displayNewMessageForm does not open new message form if user has received an email

### ISSUE THREAD

**Issue by ambachtelijk** [OfficeDev/office-js#371]
The `displayNewMessageForm` endpoint of the Outlook API does not open a new message form if the user has received an e-mail after the task pane plugin from which the action is triggered has initialized.

## Expected Behavior
When `Office.context.mailbox.displayNewMessageForm` is called in Outlook from a task pane with valid parameters, it should always open a new message form, regardless of the state of the user's inbox.

## Current Behavior
When `Office.context.mailbox.displayNewMessageForm` is called in Outlook from a task pane with valid parameters, it will not open a new message form if the user has received an e-mail after the task pane plugin was initialized. No error or exception is thrown, and the diagnostic output of `Office.context.mailbox.diagnostics` is identical to the working scenario where aforementioned action was triggered when the user's mailbox has not changed its state since the task pane initialization. 

## Steps to Reproduce, or Live Example
  1. Create a standard boiler plate plugin as described at https://docs.microsoft.com/en-us/outlook/add-ins/quick-start
  2. Make sure that the `ShowTaskpane` action is included in de plugin's manifest file.
  3. Add a link or button 'Open new message form' to the task pane code that dispatches the following action: `Office.context.mailbox.displayNewMessageForm([]);`
  4. Go to the user's inbox folder in Outlook.
  5. Open the task pane plugin in Outlook, and *make sure it has been pinned*, so that it will not reload in between the following steps.
  6. Verify that the button created in step 3 is working, by clicking it. A new message form should be opened. Close the new message form afterwards.
  7. From the `Home` ribbon, click the `New Email` button and send an email to yourself. 
  8. Wait for the e-mail to be fetched by Outlook and that it is displayed in the Inbox pane. 
  9. Single-click on the e-mail in the inbox pane, so that it will be displayed in the reading pane.
  10. Click again on the button created in step 3, and verify that the new message pane will _not_ open this time.

This screenshot illustrates the state of Outlook after step 10.
![image](https://user-images.githubusercontent.com/3234834/52111164-26400d00-2603-11e9-898a-0f273426a715.png)

## Context
I am developing a CRM plugin for Outlook in which the user is given the option to compose and send an e-mail with prefilled parameters, such as recipients, subject, etc.. However, since the newMessageForm endpoint only works as long as the mailbox state has remained unchanged, the 'compose e-mail' functionality can effectively only be used after a reload of the plugin.

## Your Environment

* Platform: PC
* Host: Outlook 365
* Office version number: Office 365 MSO 16.0.11126.20192 64-bit
* Operating System: Windows 10 Pro

## Useful logs
- No errors are thrown, and the diagnostics output of `Office.context.mailbox.diagnostics` is identical to the working scenario.
```
{
  "_data$p$0": {
    "_data$p$0": {
      "hostVersion": "16.0.11126.20266",
      "itemType": 1,
      "subject": "",
      "normalizedSubject": "",
      "itemClass": "IPM.Note",
      "dateTimeCreated": 1549007770095,
      "dateTimeModified": 1549007770399,
      "permissionLevel": 2,
      "isItemLess": false,
      "id": "AQMkADAwATM0MDAAMS1mYmE0LTIxNDEtMDACLTAwCgBGAAAD6YuAa8RSJUymdTnvF54FcgcA3TJXChZv+kyaPhxDnnOe7QAAAgEMAAAA3TJXChZv+kyaPhxDnnOe7QACLU9BBwAAAA==",
      "ewsUrl": "https://outlook.office365.com/EWS/Exchange.asmx",
      "restUrl": "https://outlook.office.com/api",
      "attachments": null,
      "isFromSharedFolder": false,
      "shouldRunNewCodeForFlags": 1,
      "entities": {
        "Addresses": null,
        "Contacts": null,
        "EmailAddresses": null,
        "MeetingSuggestions": null,
        "PhoneNumbers": null,
        "TaskSuggestions": null,
        "Urls": null,
        "IsLegacyEntityExtraction": false
      },
      "filteredEntities": null,
      "selectedEntities": {
        "Addresses": null,
        "Contacts": null,
        "EmailAddresses": null,
        "MeetingSuggestions": null,
        "PhoneNumbers": null,
        "TaskSuggestions": null,
        "Urls": null,
        "IsLegacyEntityExtraction": false
      },
      "conversationId": "AQQkADAwATM0MDAAMS1mYmE0LTIxNDEtMDACLTAwCgAQADv6/g6+UULOjq3/0GpfXEw=",
      "internetMessageId": "<AM6PR07MB483406A37BD40302504D4ED7CB920@AM6PR07MB4834.eurprd07.prod.outlook.com>",
      "dateTimeSent": 1549007767000,
      "userEmailAddress": "xxx@outlook.com",
      "userDisplayName": "xxx@outlook.com",
      "userProfileType": "outlookCom",
      "userTimeZone": "W. Europe Standard Time",
      "to": [
        {
          "address": "xxx@outlook.com",
          "name": "xxx",
          "recipientType": 3
        }
      ],
      "cc": null,
      "sender": {
        "address": "xxx@outlook.com",
        "name": "xxx",
        "recipientType": -1
      },
      "regExMatches": null,
      "selectedRegExMatches": null,
      "from": {
        "address": "xxx@outlook.com",
        "name": "xxx",
        "recipientType": -1
      },
      "itemNumber": 26,
      "error": false
    },
    "_permissionLevel$p$0": 3
  },
  "_appName$p$0": 8
}
```

**Comment by exextoc** [comment]
@ehmPlankje Have you tried to hookup ItemChanged event? For pinned add-in, this event will be triggered every time when item changed. Please find related articles [here](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.5/office.context.mailbox?view=office-js#addhandlerasynceventtype-handler-options-callback).

**Comment by ambachtelijk** [comment]
> @ehmPlankje Have you tried to hookup ItemChanged event? For pinned add-in, this event will be triggered every time when item changed. Please find related articles [here](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.5/office.context.mailbox?view=office-js#addhandlerasynceventtype-handler-options-callback).

Thank you for your feedback, @exextoc! I have added a blank event listener to my `Office.initialize` callback, as such:
```
Office.initialize = () => {
    Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, () => {});
};
```

Strangely enough, this resolves present issue. However, I do not quite understand why an event listener is required in this scenario, since the `displayNewMessageForm()` call in present issue is not triggered asynchronously. Perhaps you could provide me with a little more context why an async event listener would resolve this scenario?

**Comment by exextoc** [comment]
When an addin is pinned we need to inform it about an item switch that happened by registering to an ItemChangedEvent. This is a mandatory requirement for all Pinned Addins in order for the APIs to continue functioning properly. If you do not register for the event it might cause your APIs to be cancelled. This is by design.
