### ISSUE TITLE
Office.MessageCompose method getSharedPropertiesAsync does not return owner property

### ISSUE THREAD

**Issue by MehakFatima24** [OfficeDev/office-js#3713]
# Provide required information needed to triage your issue
Office.MessageCompose method getSharedPropertiesAsync does not return owner property, see [documentation](https://learn.microsoft.com/en-us/javascript/api/outlook/office.sharedproperties?view=outlook-js-preview#outlook-office-sharedproperties-owner-member)

## Your Environment

- Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
- Host [Excel, Word, PowerPoint, etc.]: Outlook
- Office version number: 1.8
- Operating System: macOs
- Browser (if using Office on the web): Chrome

 
## Expected behavior
Method [getSharedPropertiesAsync](https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#outlook-office-messagecompose-getsharedpropertiesasync-member(2)) should return owner property

## Current behavior

Method [getSharedPropertiesAsync](https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#outlook-office-messagecompose-getsharedpropertiesasync-member(2)) does not return owner property

![Screenshot 2023-09-27 at 01 07 16](https://github.com/OfficeDev/office-js/assets/30459298/ce4b7e23-02a3-4238-bcda-54bdfa3f7f00)

## Steps to reproduce

1. Open a shared mailbox
2. Try to trigger the method getSharedPropertiesAsync and see the result

## Context

This issue was reported and fixed earlier as well but this is again popping up, here's the link to previous [issue](https://github.com/OfficeDev/office-js/issues/3622)

Our customers are currently facing a serious problem—they can't send messages through shared mailboxes. It's causing them a lot of frustration and inconvenience. We need to address this issue urgently to ensure their needs are met promptly.

## Useful logs

- [ ] Console errors
- [ ]  #Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by DivyaPatidar** [comment]
Thanks for reporting, we are aware of this issue. The fix for this is already being rolled out and should be available by the end of next week to all users.
