### ISSUE TITLE
In certain operations, it is not possible to retrieve file information.

### ISSUE THREAD

**Issue by t-ariyoshi30907** [OfficeDev/office-js#3716]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2302 (build 16.0.16130.20378)
* Operating System: Windows OS
* Browser (if using Office on the web): Google Chrome

## Expected behavior

1. Compose an email.
2. Click on "Insert" in the taskbar.
3. Click on the menu item "Pictures."
4. Select an image.
5. Save the email to the Drafts folder.
6. Close Outlook on the web.
7. Open Outlook on the web and open the email in the Drafts folder.
8. Click the "Send" button.
9. In the console, file information is displayed.

## Current behavior

1. Compose an email.
2. Click on "Insert" in the taskbar.
3. Click on the menu item "Pictures."
4. Select an image.
5. Save the email to the Drafts folder.
6. Close Outlook on the web.
7. Open Outlook on the web and open the email in the Drafts folder.
8. Click the "Send" button.
9. The console does not display file information; instead, it shows the predefined text, "not a picture."

## Steps to reproduce

1. Access the following URL.
https://drive.google.com/drive/folders/1osz1DOUfTX_yhvvDyN1IehV-3C1JxGEo?usp=drive_link
2. Download "sample.zip" and place it in your desired location.
3. Launch the command prompt and navigate to the corresponding directory.
4. Run "npm install".
5. Run "npm run dev-server".
6. Upload "manifest.xml" in Outlook on the web to install the add-in. (The XML file is stored in sample.zip)
7. Compose an email.
8. Click on "Insert" in the taskbar.
9. Click on the menu item "Pictures."
10. Select an image.
11. Save the email to the Drafts folder.
12. Close Outlook on the web.
13. Open Outlook on the web and open the email in the Drafts folder.
14. Click the "Send" button.

## Link to live example(s)

I am storing the related videos at the following URL.

- related videos
https://drive.google.com/file/d/1EZAkGcvQ6Qz64UBqVdQ3q7BJIyyIiFvH/view?usp=drive_link

We have received feedback from customer requesting improvements.
Please investigate and make necessary improvements.

**Comment by exextoc** [comment]
The add-in provided is incomplete. Please check the folders in `/src`, they're empty.
