### ISSUE TITLE
Outlook signatures with inline images disables the attachment auto-detection

### ISSUE THREAD

**Issue by t4rzsan** [OfficeDev/office-js#3718]
# Provide required information needed to triage your issue
Outlook has built-in detection of missing attachments.  When inserting signatures from an add-in with `setSignatureAsync` that has inline images in it, the detection of missing attachments does not work, i.e. Outlook considers the inline images to be attachments.  

## Your Environment

* Platform: PC desktop (attached videos are from Outlook One)
* Host: Outlook
* Office version number: Microsoft 365 MSO (Version 2308 Build 16.0.16731.20182) 64-bit 
* Operating System: Windows
 
## Expected behavior
If you manually create a signature in Outlook settings with images in it, the missing attachment detection still works.  The attached video "Attachment from Outlook.mp4" shows, how Outlook still pops up a warning for missing attachment, even though the signature contains an inline image.

Add-ins should behave in a similar way, i.e. Outlook should not consider inline images in signatures as attachments and it should pop up a warning when there are no attachments besides the images in the signature.  

## Current behavior

The video "Attachment from add-in.mp4" shows what happens, when the signature is inserted by an add-in.  Outlook does not show a warning when the message is sent.

## Steps to reproduce
This is add-in code used for the video:
```javascript
function insertDefaultSignature(eventObj) {
    const mailItem = Office.context.mailbox.item;
    const base64String =
        "iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAMAAADVRocKAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAnUExURQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN0S+bUAAAAMdFJOUwAQIDBAUI+fr7/P7yEupu8AAAAJcEhZcwAADsMAAA7DAcdvqGQAAAF8SURBVGhD7dfLdoMwDEVR6Cspzf9/b20QYOthS5Zn0Z2kVdY6O2WULrFYLBaLxd5ur4mDZD14b8ogWS/dtxV+dmx9ysA2QUj9TQRWv5D7HyKwuIW9n0vc8tkpHP0W4BOg3wQ8wtlvA+PC1e8Ao8Ld7wFjQtHvAiNC2e8DdqHqKwCrUPc1gE1AfRVgEXBfB+gF0lcCWoH2tYBOYPpqQCNwfT3QF9i+AegJfN8CtAWhbwJagtS3AbIg9o2AJMh9M5C+SVGBvx6zAfmT0r+Bv8JMwP4kyFPir+cswF5KL3WLv14zAFBCLf56Tw9cparFX4upgaJUtPhrOS1QlY5W+vWTXrGgBFB/b72ev3/0igUdQPppP/nfowfKUUEFcP207y/yxKmgAYQ+PywoAFOfCH3A2MdCFzD3kdADBvq10AGG+pXQBgb7pdAEhvuF0AIc/VtoAK7+JciAs38KIuDugyAC/v4hiMCE/i7IwLRBsh68N2WQjMVisVgs9i5bln8LGScNcCrONQAAAABJRU5ErkJggg==";

    // Get the current body of the message or appointment.
    mailItem.body.getAsync(Office.CoercionType.Html, (bodyResult) => {
        console.log(bodyResult);

        const options = { isInline: true };
        mailItem.addFileAttachmentFromBase64Async(base64String, "sample.png", options, (attachResult) => {
            console.log(attachResult);

            if (attachResult.status === Office.AsyncResultStatus.Succeeded) {
                const signature = `<p>Signature from add-in</p><p><img src="cid:sample.png"></p>`;
                mailItem.body.setSignatureAsync(signature, { coercionType: Office.CoercionType.Html }, (setResult) => {
                    console.log(setResult);
                });
            }
        });
    });
}

Office.actions.associate("insertDefaultSignature", insertDefaultSignature);
```
The manifest is set up with `OnNewMessageCompose` event:
```xml
<ExtensionPoint xsi:type="LaunchEvent">
    <LaunchEvents>
        <LaunchEvent Type="OnNewMessageCompose" FunctionName="insertDefaultSignature" />
    </LaunchEvents>
    <SourceLocation resid="Autorun" />
</ExtensionPoint>
```

# Provide additional details
I have attached two videos that show the difference between a signature coming from the add-in and a signature manually created in Outlook.

## Context
A client reported this to us when using our add-in, so apparently this is not the expected behaviour for normal daily users.

https://github.com/OfficeDev/office-js/assets/19477948/17c03957-2be0-4c94-8488-d0ba5a74e3e9
https://github.com/OfficeDev/office-js/assets/19477948/2b4c120f-30ac-4c3b-9b6d-a5f0871f9b19

**Comment by ShadowAnonymous** [comment]
Just a question did your addin is working on Outlook Mac because i can't add inline image with your code in this version but working on PC and Outlook Online ?

**Comment by t4rzsan** [comment]
@ShadowAnonymous Sorry, I did not try the test sample on Mac.

**Comment by millerds** [comment]
This is because in order to include the image in the signature the add-in is required to call the API to add an attachment and we aren't distinguishing it from any other attachment.  This is a divergence from the native signature implementation and one that we will consider fixing.

Internal references: 8443790
