### ISSUE TITLE
The DiplayDialogAsync API fails to launch correctly.

### ISSUE THREAD

**Issue by t-ariyoshi30907** [OfficeDev/office-js#3720]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2302 (build 16.0.16731.20182)
* Operating System: Windows OS

## Expected behavior

1. Compose an email.
2. Click the "Send" button.
3. The "DiplayDialogAsync" method is executed, and a dialog is displayed
4. The dialog displays the content of the index.html file.

## Current behavior

1. Compose an email.
2. Click the "Send" button.
3. The "DiplayDialogAsync" method is executed, and a dialog is displayed
4. the dialog does not display the content of the HTML file.

## Steps to reproduce

1. Access the following URL.　https://drive.google.com/file/d/1Xrc-HuBLSjBAwDmU7y7Pbi7amwegbPDY/view?usp=share_link
2. Download "sample.zip" and place it in your desired location.
3. Launch the command prompt and navigate to the corresponding directory.
4. Run "npm install".
5. Run "npm run dev-server".
6. Open Outlook for windows.
7. Upload "manifest.xml" in Outlook to install the add-in. (The XML file is stored in sample.zip)
8. Compose an email.
9. Click the "Send" button.

Furthermore, I will describe the characteristics of this issue as follows:

This problem may not occur depending on the build version of Outlook.
After checking with multiple customers, it has been observed that this issue commonly occurs with version "2308(16.0.16731.20182)"
In my company, everyone is using Outlook with the version "2307 (16.0.16626.20198)," and we haven't experienced the same issue at all.
Additionally, it doesn't seem to happen consistently every time.

## Link to live example(s)

I will share an image when a problem occurs.

![displayDialogAsync API](https://github.com/OfficeDev/office-js/assets/106288213/a46574f8-2458-491c-a56d-30e314418fed)

We have received feedback from customer requesting improvements.
Please investigate and make necessary improvements.

**Comment by timwan10** [comment]
Based on your image...the Dialog is showing up...but it's empty?

What version of windows are you using? (10 or 11?) 

Also is this "Old" Outlook or "New" Outlook: 

![image](https://github.com/OfficeDev/office-js/assets/17890744/10f01183-1746-4cda-9280-c0b003425618)

**Comment by t-ariyoshi30907** [comment]
@timwan10 
Yes, it's empty. It occurs sometimes and sometimes it doesn't.
In some cases, the message "sample is working on your request." is displayed and the dialog does not appear.
This issue is occurring with "Old" Outlook on Windows 10.
https://drive.google.com/file/d/1v7peobbw6LKvMqz2zAL3G9Lwreqt9Vz6/view?usp=drive_link

**Comment by t-ariyoshi30907** [comment]
@timwan10 
I have a question.
There is an incident in the Microsoft Management Center for Exchange Online.
Is there any connection between this issue and the incident?
incident name: Users may intermittently be unable to access their mailboxes when using any Exchange Online connection method
incident No. EX678864

**Comment by timwan10** [comment]
I don't think the incident is related. Do you have a screenshot of when it is working for comparison?

Approximately how intermittent is the issue? (90% of the time? 10%, etc?)

Also when the dialog does pop up and doesn't load is it possible to refresh it with a right click?

![image](https://github.com/OfficeDev/office-js/assets/17890744/1c63a6ff-a7c8-4d7f-b5d6-c1ab749751b6)

**Comment by t-ariyoshi30907** [comment]
@timwan10 
I will share a screenshot of when it works correctly. To protect privacy, I will provide it with a mosaic.
https://drive.google.com/file/d/1YyXXxSUPC5XPLbMBKMj96JIjYiygjFoX/view?usp=share_link

The "Send" button is displayed on the dialog, and clicking the button sends the email. The issue occurs with a frequency of approximately 20% of the time. We are currently checking if a "refresh" will improve the situation and will report back once the confirmation is made.

**Comment by t-ariyoshi30907** [comment]
@timwan10 
When you right-clicking on the dialog does not elicit any response. If there is any additional information needed for the investigation, please provide instructions.

**Comment by t-ariyoshi30907** [comment]
@timwan10 @exextoc 
I apologize for the frequent messages. Could you please provide a response regarding this issue? Additionally, have there been any similar reports from other developers? Many users are facing difficulties, and we would appreciate your assistance in resolving this.

**Comment by timwan10** [comment]
I've contacted the product team that owns this area. 

There aren't any issues currently reported about the dialog from other developers...which could indicate that this is an intermittent problem with your dialog code...or a problem that just hasn't been hit by other developers yet. 

Of note, it could be that some users are hitting a problem contacting your webpage when the dialog loads. (but I would have assumed the "refresh" would have attempted another load). You could try running fiddler, and then reproducing the problem. to See if your web files are being loaded from the server, or if they are retuning http errors. 

Is there anything on your dialog page that can cause the page to load blank? (a race condition?) I.e. if you can reproduce the issue, you may try instead loading a page with a very simple dialog (like just a flat HTML page) and see if you can still reproduce the problem with the simple page.

**Comment by t-ariyoshi30907** [comment]
@timwan10 
The issue I am currently investigating appears to be closely similar to the following ticket:
https://github.com/OfficeDev/office-js/issues/3782

The sample program provided in this ticket is built with a very limited set of features. We deployed it to an Azure Blob Storage server for testing, but the problem still occurred. We used the "SetupProd_Assisted" provided by Microsoft to capture Fiddler trace logs. We initiated the recording and collected the logs by clicking the "Send" button right after starting the recording. Could you please analyze these logs for us?
https://drive.google.com/file/d/18BSY-coOvlnEN3dh8BPxYAYumje9e_mi/view?usp=drive_link

**Comment by t-ariyoshi30907** [comment]
Here is the password required to access the Fiddler trace logs:
Password: sampleTest

**Comment by croicu** [comment]
@t-ariyoshi30907 If you open Edge DevTools by right clicking in the dialog and select Inspect, do you see any exception in the console window?

<img width="620" alt="image" src="https://github.com/OfficeDev/office-js/assets/24237909/45ce6716-dd84-492e-bf30-43285d4ba8ac">

**Comment by t-ariyoshi30907** [comment]
@croicu 
As a prerequisite, when this issue occurs, right-clicking does not trigger any response on the dialog. After waiting for about 10 seconds and when popup.html is displayed on the screen, right-clicking again will finally display the menu.
Furthermore, after popup.html is displayed on the screen and I checked the console logs, there was no information related to exceptions being output. Is there an alternative approach to check for exceptions?

**Comment by croicu** [comment]
@t-ariyoshi30907 for some reason I cannot run the add-in from sample.zip. After step #5 from your repro I am getting the following error:

<img width="894" alt="image" src="https://github.com/OfficeDev/office-js/assets/24237909/c41a6c90-bb12-475d-ba4c-aabff7b741c4">

After this the add-in keeps spinning indefinitely:

<img width="452" alt="image" src="https://github.com/OfficeDev/office-js/assets/24237909/1ab61715-a80e-4567-a386-8459c4defd14">

And the browser is blocked on the response when navigating to https://localhost:3000/index.html.

<img width="682" alt="image" src="https://github.com/OfficeDev/office-js/assets/24237909/8dbad32e-186b-4886-b0aa-0f4feecb83ca">

**Comment by t-ariyoshi30907** [comment]
@croicu 
I understand that you're experiencing an error. To assist you in testing, I have deployed the source code to my cloud storage server with the same program configuration and set up a verification environment. I will share a dedicated manifest file with you. Additionally, the source code deployed to the cloud server is stored in the same location as the manifest file, so feel free to use it for investigation as needed.
https://drive.google.com/file/d/1Q87ee9mfbeqTwMEU-jCzMFadkZ5H_hbr/view?usp=drive_link

Please install the add-in and follow the steps below to test:

**Steps to reproduce:**
1. Install the add-in by uploading "manifest.xml" in Outlook for Windows (Old). (The XML file is stored in "sample-Add-in(dev).zip")
2. Click on "New Email."
3. With the email composition window open, wait for 30 minutes or more.
4. Click the "Send" button.
I appreciate your cooperation with this matter.

**Comment by croicu** [comment]
@t-ariyoshi30907 I cannot repro it locally (I see the dialog with two buttons).

One question: what is the version of msedgewebview2.exe process child of Outlook.exe?

You can enable the diagnostic logs on the customer machine by following the steps here: https://learn.microsoft.com/en-us/microsoft-365/troubleshoot/diagnostic-logs/collect-office-diagnostic-logs

The chrome of the dialog is a different from what I am seeing on my box:

<img width="605" alt="image" src="https://github.com/OfficeDev/office-js/assets/24237909/d8667328-2045-4b90-88e1-708b6a24d6ec">

**Comment by t-ariyoshi30907** [comment]
@croicu 
Thank you for investigating.
Like you, I am also unable to reproduce the issue when performing the same steps in my local environment.. On the other hand, the issue occurs when deploying the same source code to an online storage service. I believe the version of webview2 is "119.0.2151.44." I have attached a screenshot.
![webview2_version](https://github.com/OfficeDev/office-js/assets/106288213/81c8a8c8-0be1-4435-9ec7-4703dd7af04c)
If this is not the information you are looking for, please provide detailed instructions on how to check the version of msedgewebview2.exe again.
Additionally, I have read the documentation and collected the diagnostic logs for you. 
https://drive.google.com/file/d/1zgnnIhMJ88YVP33vVu1LgrRUIVvmoTGB/view?usp=drive_link
I started recording before launching Outlook and intentionally triggered the issue with the shortest workflow. Could you please check the log information when you have a moment? I appreciate your assistance.

**Comment by t-ariyoshi30907** [comment]
@croicu 
I apologize for the frequent postings. I provided additional information; have you had a chance to review it? I would appreciate an update on the latest investigation status.
