### ISSUE TITLE
After switching to Entra Domain Services getAccessToken returns error 13007 in the web

### ISSUE THREAD

**Issue by catmanjan** [OfficeDev/office-js#3722]
We recently swapped to Entra Domain Services, which may be unrelated, but we noticed that our app now returns a 13007 error when calling getAccessToken, but only in the web - this was working before.

getAccessToken works fine in Word on the desktop

Any ideas on how to fix this? Very little information on 13007 as it seems to be a catch all

![image](https://github.com/OfficeDev/office-js/assets/137350/797193db-595d-418d-9649-2b10874b47f5)

**Comment by xiruatms** [comment]
Thanks for reporting this.

Please refer here https://learn.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins#13007 for the details.

**Comment by catmanjan** [comment]
I had seen this but neither of those suggestions helped

Let me know what information you need to diagnose our issue

**Comment by penglongzhaochina** [comment]
@mattgeim  Hi matt, could you please take a look at this SSO issue?

**Comment by davidchesnut** [comment]
Hi @catmanjan,

If you are using event-based activation, can you also check that the well-known URI list is up to date (especially if you made any domain changes). See [article on SSO with event-based activation](https://learn.microsoft.com/office/dev/add-ins/outlook/use-sso-in-event-based-activation#list-allowed-add-ins-in-a-well-known-uri).

Another thing to check is to run a fiddler trace when you call getAccessToken. There will be a call made to Microsoft identity (Azure AD) to request the token, and if there is an error you will see more detail in the error response from Azure AD. That would help us trace what is happening.

Thanks!
David

**Comment by catmanjan** [comment]
@davidchesnut I used fiddler and extracted this error:

{"error":"invalid_grant","error_description":"AADSTS700084: The refresh token was issued to a single page app (SPA), and therefore has a fixed, limited lifetime of 1.00:00:00, which cannot be extended. It is now expired and a new sign in request must be sent by the SPA to the sign in page. The token was issued on 2023-09-20T01:22:07.6416282Z. Trace ID: 5aa36644-a90f-47d0-af93-b4d9c0e35b00 Correlation ID: 02c9134d-5c48-441e-b32f-fc02a3e89ed8 Timestamp: 2023-11-01 01:02:25Z","error_codes":[700084],"timestamp":"2023-11-01 01:02:25Z","trace_id":"5aa36644-a90f-47d0-af93-b4d9c0e35b00","correlation_id":"02c9134d-5c48-441e-b32f-fc02a3e89ed8","error_uri":"https://login.microsoftonline.com/error?code=700084","suberror":"bad_token"}


My understanding was that getAccessToken handles token refreshes for us - is there some other boilerplate we need to paste in?

**Comment by catmanjan** [comment]
@davidchesnut I tried resetting my browser and now I get a new error - when the getAccessToken call happens now I see a request to GET https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize

with the response:

HTTP/1.1 302 Found
Cache-Control: no-store, no-cache
Pragma: no-cache
Content-Type: text/html; charset=utf-8
Expires: -1
Location: https://oauth.online.office.com/oa/WacOAuth.aspx#error=login_required&error_description=AADSTS50058%3a+A+silent+sign-in+request+was+sent+but+no+user+is+signed+in.+The+cookies+used+to+represent+the+user%27s+session+were+not+sent+in+the+request+to+Azure+AD.+This+can+happen+if+the+user+is+using+Internet+Explorer+or+Edge%2c+and+the+web+app+sending+the+silent+sign-in+request+is+in+different+IE+security+zone+than+the+Azure+AD+endpoint+(login.microsoftonline.com).+Trace+ID%3a+84a08d9d-f0ab-4405-af0d-e4a166066400+Correlation+ID%3a+ecfb22fd-c2f3-4fd7-b2fc-5527662f3958+Timestamp%3a+2023-11-01+01%3a10%3a15Z&error_uri=https%3a%2f%2flogin.microsoftonline.com%2ferror%3fcode%3d50058&state=eyJpZCI6Ijc1ZTI1ODhkLTJhZGQtNDkwOC05YTJmLWUyNDJiMjY1ZTBmNyIsIm1ldGEiOnsiaW50ZXJhY3Rpb25UeXBlIjoic2lsZW50In19

**Comment by catmanjan** [comment]
Bump

**Comment by catmanjan** [comment]
The exact same integration works in Outlook but not Word BTW

**Comment by davidchesnut** [comment]
Hi @catmanjan, so sorry for dropping this thread. I'm taking a look now. This looks like something in the browser is interfering with the auth flow. Is the browser configured to block cookies? Does this behavior also occur in other browsers, or in private viewing modes? Thanks!

**Comment by davidchesnut** [comment]
@catmanjan Also, can you also please confirm that you granted client id ea5a67f6-b6f3-4338-b240-c655ddc3cc8e as an authorized client application in your Microsoft Azure app registration. It will be under the "Expose an API" section. Thanks!

**Comment by catmanjan** [comment]
@davidchesnut the issue happens in all browsers (Chrome, Edge, Firefox) whether or not its in private viewing modes - cookies are allowed in all browser and I can reproduce it on multiple machines - it never happens in the Office clients though

I have checked and that client ID is there

![image](https://github.com/OfficeDev/office-js/assets/137350/a5d78665-e634-4355-93a1-1c7f1f236395)

**Comment by davidchesnut** [comment]
Thanks. Also curious if you are able to just simply sign in to Office on the web as a regular user (no add-ins or SSO). Does the sign in work as expected? I'm still investigating with SSO and identify folks on my end. Thanks!

**Comment by davidchesnut** [comment]
Hi @catmanjan,
Given this works on desktop, and Outlook, I'm curious if there is a load timing issue. Is it possible for your call to getAccessToken() to run before Office.OnReady() occurs? Thanks!

**Comment by catmanjan** [comment]
@davidchesnut I modified my code as such, but the issue still occurs:

```
        console.log("***calling Office.onReady");
        await Office.onReady();
        console.log("***calling getAccessToken");
        let options = { allowSignInPrompt: true, allowConsentPrompt: true, forMSGraphAccess: false }
        let bootstrapToken = await Office.auth.getAccessToken(options);
        console.log("***doneski");
```

(The final console.log is never reached)

**Comment by codexeon** [comment]
I am not able to repro on my end, but the more recent error you shared looks like third-party cookies being blocked in the browser. Some more diagnostic information may be required if you have already ruled out that third-party cookies are enabled in your browser.

- Does the request to https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize contain any cookies in the request header.
  - Does the login_hint parameter match your UPN/email address?
  - Could you share the client-request-id parameter and timestamp for additional log lookup?
  - Updated error response from 302 redirect.
- Is your account a member of the tenant, or is this a guest scenario?
- You mention it worked in Outlook, is this Outlook Web or Outlook Desktop? Is it the same app registration that works in Outlook?
- Is your AAD application single tenant or multi tenant?
- Is this an Office Store add-in we could try or do you have a repro manifest you could share?
- I see screenshots of your application id URI, but could you share it in text format if it is publicly accessible so that we could see if it is a problem with the app registration.

**Comment by catmanjan** [comment]
@codexeon it looks like this has fixed itself in 2024... we've made no changes to the app but now when a user open it they get this pop up - following sign in causes the integration to start working, so, yay?

![image](https://github.com/OfficeDev/office-js/assets/137350/ec311c3e-d337-4c05-a1d4-d2d00416d42d)

**Comment by davidchesnut** [comment]
In case this might be related there is a blog post about working around 3rd party cookie blocking. [Using device state for an improved SSO experience on browsers with blocked third-party cookies](https://devblogs.microsoft.com/identity/managed-devices-for-blocked-third-party-cookies/)
