### ISSUE TITLE
Getting Internal error when run range.valuesAsJson on cell containing CustomFunction.Error

### ISSUE THREAD

**Issue by didu9898** [OfficeDev/office-js#3723]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2307 (build: 16626.20208)
* Operating System: Windows
* Browser (if using Office on the web): ---
 
## Expected behavior
range.valuesAsJson should behave correctly for CustomFunction.error.

## Current behavior
I have a cell containing CustomFunction.error and when I run the following code, I am getting following error:
`[ERROR]: Error:
{
    "stack": "RichApi.Error: There was an internal error while processing the request.\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:261587)\n    at o.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:326033)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:324096",
    "message": "There was an internal error while processing the request.",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "There was an internal error while processing the request.",
        "errorLocation": "",
        "statement": "selectedRange.load([\"valuesAsJson\"]);",
        "surroundingStatements": [
            "var workbook = context.workbook;",
            "var selectedRange = workbook.getSelectedRange();",
            "// Instantiate {selectedRange}",
            "// >>>>>",
            "selectedRange.load([\"valuesAsJson\"]);",
            "// <<<<<"
        ],
        "fullStatements": [
            "var workbook = context.workbook;",
            "var selectedRange = workbook.getSelectedRange();",
            "// Instantiate {selectedRange}",
            "selectedRange.load([\"valuesAsJson\"]);"
        ]
    },
    "httpStatusCode": 500
}`

## Steps to reproduce
This error is simple to reproduce
1. Insert any error value using CustomFunction.Error.
2. Run following code:
```
OfficeExtension.config.extendedErrorLogging = true;
const range = context.workbook.getSelectedRange();
range.load("valuesAsJson");
await context.sync();
console.log(`The range valuesAsJson was "${range.valuesAsJson}".`)
```
## Useful logs
![image](https://github.com/OfficeDev/office-js/assets/105494296/9ad464b9-7092-4116-8a5c-81e0cf169c67)
![image](https://github.com/OfficeDev/office-js/assets/105494296/75885a2a-b1be-4a25-8e87-b15e41357a3c)

**Comment by ruijiaMS** [comment]
Hi @didu9898,
Thanks for letting us know this issue. I have a try with your repro steps:
1, code in ScriptLab
![image](https://github.com/OfficeDev/office-js/assets/113165331/c0d7ac6c-ef65-4dd5-86ae-c87c9facf9cb)
2, insert a custom function with wrong input parameter like no parameters.
![image](https://github.com/OfficeDev/office-js/assets/113165331/a351b08d-eb58-424e-a53a-bd2d6446649f)

While from the log, it does not hit this error.
![image](https://github.com/OfficeDev/office-js/assets/113165331/29d04232-6863-4128-a075-4303b854352b)

Could you please have a try with latest version of Excel and provide more information like which function are you using or could you please have a try with another station to avoid impacting by noise?

**Comment by penglongzhaochina** [comment]
[like]  Penglong Zhao reacted to your message:
________________________________

**Comment by jgamboavx** [comment]
@ruijiaMS 

> Insert a custom function with wrong input parameter like no parameters

The issue is not reproducible with a custom function with wrong input parameters because in such cases the custom function will not actually execute and `CustomFunctions.Error` won't have been returned.

As detailed by @didu9898 in the original post, the issue is reproducible if the custom function returns `CustomFunctions.Error`.
Then, if you try to load `valuesAsJson`, the RichApi error will be thrown.

Reproduced with version:
![image](https://github.com/OfficeDev/office-js/assets/122270839/7a554cdb-f097-4d82-b1dc-dea794be4c02)

**Comment by ruijiaMS** [comment]
@jgamboavx 
Thanks for letting us know this issue, we raise a new internal bug 8759628 to track the progress, any update will post here!

**Comment by penglongzhaochina** [comment]
hi @didu9898 
Do you know how can we make a cell to be the "#N/A"by using custom function?  Please share with me if you are convenient.

**Comment by XuanZhouMSFT** [comment]
Hi @didu9898 Thanks for the waiting. We already released a fix and it already reached to production. Please update the version to >16.0.17928.xxxxx to have a test. Please let us know if you still have problems.
