### ISSUE TITLE
Add-in stops working when switching to new outlook desktop (windows)

### ISSUE THREAD

**Issue by gstjepan** [OfficeDev/office-js#3725]
# Provide required information needed to triage your issue
I created an taskpane add-in from https://github.com/OfficeDev/Office-Addin-TaskPane.git.
The add-in works on current Outlook Desktop (Windows and Mac) and using office online (web browser), however it doesn't load when switching Outlook Desktop (Windows) to **new** version. I can't find the error details anywhere. I tried enabling different logging for Outlook, but I just see the generic error in the UI `Add-in Error Something went wrong and we couldn't start this add-in. Please try again later or contact your system administrator.`

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __PC desktop____
* Host [Excel, Word, PowerPoint, etc.]: __Outlook____
* Office version number: ___1.2023.920.900 (Client Version is 20230922005.11)___
* Operating System: ___Windows___
* Browser (if using Office on the web): ______
 
## Expected behavior

I expect my add-in to load and render a form in taskpane.

## Current behavior

I get an error  `Add-in Error Something went wrong and we couldn't start this add-in. Please try again later or contact your system administrator.`

## Steps to reproduce

1. ______Have a working add-in
2. ______Switch Outlook Desktop (Windows) to new version
3. ______Try and open the add-in in meeting taskpane

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

The add-in is used in the company to capture metadata for meetings to provide sales management with custom reporting.
The add-in was a great success and is now spreading across the company so I need to get it working on new version of Outlook.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
![image](https://github.com/OfficeDev/office-js/assets/84336486/9953c08e-aeb8-4bea-97bd-cd52f4aad3a2)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Does this happen for all the add-ins on your account or only for this add-in? Is it possible for you to share the Addin Manifest so that we can try to repro at our end?

**Comment by gstjepan** [comment]
> Does this happen for all the add-ins on your account or only for this add-in? Is it possible for you to share the Addin Manifest so that we can try to repro at our end?

This is the only custom add-in I have. Viva insights work fine so I'm sure I need to change something, but the error is hidden. Are there any logs I could enable to see what the issue is when this happens?
[manifest.zip](https://github.com/OfficeDev/office-js/files/12817958/manifest.zip)

**Comment by exextoc** [comment]
@gstjepan  Thank you for sharing the manifest. this add-in works fine on our end. Can you share the Outlook version number where you see this issue?

**Comment by gstjepan** [comment]
@exextoc 
![image](https://github.com/OfficeDev/office-js/assets/84336486/3f5ba6c9-002b-4873-b3d9-de0e6d513603)

**Comment by exextoc** [comment]
With the given version also the addin works fine for us. Can you try installing other addins or maifests to the account and check if they show the same error. Also, does it work on clicking retry?

**Comment by gstjepan** [comment]
It doesn't work when clicking retry and I tried it with a colleague as well on his account with the same result.
Is there any additional logging I can enable to see what the actual error is? I'm thinking now it could be something specific with the company settings....

**Comment by gstjepan** [comment]
@exextoc I tested with a few more colleagues and it works for them so the issue remains on the original 2 accounts used to test the add-in. I guess something got cached somewhere. I emptied all cache I could find on Google, even removed my account from Outlook, any idea what to try next?

**Comment by exextoc** [comment]
Can you try re-installing the addin?

**Comment by gstjepan** [comment]
I did, removed it, installed it through "old" version of Outlook and switched to "New", removed it then installed it through "new" version of Outlook, same with installing for web outlook. I'm going to close this for now and hope the issue resolves itself when "new" version becomes the current/only version. Thank for you help with debugging.

**Comment by TamilSekar12** [comment]
getting the same error for me. Any solution to fix this?

**Comment by exextoc** [comment]
@TamilSekar12 As the issue was closed by original poster, could you please create a new issue with all the required details to reproduce the issue?
