### ISSUE TITLE
[Word.Document.addStyle] does not allow name with space.

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#3728]
- Word allows to create style's name with spacing but the API does not
![image](https://github.com/OfficeDev/office-js/assets/13063615/4d9ab16e-2be9-494e-86c9-6acd5ec979e6)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number:  Version 2309 Build 16.0.16827.20130
* Operating System: Windows 11
* Browser (if using Office on the web): ______
 
## Expected behavior
- Can add the style's name with space

## Current behavior
![image](https://github.com/OfficeDev/office-js/assets/13063615/7719ded7-4b76-4893-aa42-c1d58a9c9082)

## Link to live example(s)
- Open Manage styles example in the scriptlab
- input name with spacing then click add style

**Comment by GavinGu07** [comment]
Hi @jasonhieu1905 

Thanks for reporting this issue. It has been put in our backlog: [Bug 8420590](https://office.visualstudio.com/OC/_workitems/edit/8420590): [Word API] Document.addStyle does not allow name with space.

**Comment by jipyua** [comment]
hi @jasonhieu1905 , thanks for reporting this issue, now it has been fixed and deploye to latest Microsoft365 current channel, please feel free to update your office version and have a try.
