### ISSUE TITLE
Word Online: Cannot read properties of undefined (reading 'bodyForegroundColor')

### ISSUE THREAD

**Issue by NataliaKravcheniaTR** [OfficeDev/office-js#3732]
# Provide required information needed to triage your issue
Office.context.officeTheme.bodyForegroundColor throw 'Cannot read properties of undefined (reading 'bodyForegroundColor')' error
Rely on documentation Office.context.officeTheme should be supported:
https://learn.microsoft.com/en-us/javascript/api/office/office.officetheme?view=common-js-preview

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Office.context.officeTheme.bodyForegroundColor should return result

## Current behavior
throws 'Cannot read properties of undefined (reading 'bodyForegroundColor')' error

## Steps to reproduce
https://gist.github.com/NataliaKravcheniaTR/c3dd186d37c9169911230dbf10ac56e1

# Provide additional details
The issue was not reproduced yesterday.

## Useful logs
TypeError {}
message: "Cannot read properties of undefined (reading 'bodyForegroundColor')"
stack: "TypeError: Cannot read properties of undefined (reading 'bodyForegroundColor') at https://script-lab-runner.azureedge.net/?backButton=true:43:56 at Microsoft.Office.WebExtension.onReadyInternal (https://appsforoffice.microsoft.com/lib/1/hosted/office.js:76:22992) at Microsoft.Office.WebExtension.onReady (https://appsforoffice.microsoft.com/lib/1/hosted/office.js:76:23495) at https://script-lab-runner.azureedge.net/?backButton=true:42:20 at step (https://script-lab-runner.azureedge.net/?backButton=true:33:23) at Object.next (https://script-lab-runner.azureedge.net/?backButton=true:14:53) at https://script-lab-runner.azureedge.net/?backButton=true:8:71 at new Promise (<anonymous>) at __awaiter (https://script-lab-runner.azureedge.net/?backButton=true:4:12) at setup (https://script-lab-runner.azureedge.net/?backButton=true:40:12)"

**Comment by xiruatms** [comment]
Thanks for reporting this. Unfortunately, I can't reproduce this issue. I noticed that you can't reproduce it either, correct? Let me know if you can consistently reproduce it.

Thanks a lot~

**Comment by NataliaKravcheniaTR** [comment]
@xiruatms I'm still able to reproduce it
![image](https://github.com/OfficeDev/office-js/assets/67966577/ce43f15b-ac39-4390-8ec6-b29aeb3a00b0)

**Comment by xiruatms** [comment]
@NataliaKravcheniaTR , Will you please provide me with the sample document you used to reproduce this issue?

**Comment by NataliaKravcheniaTR** [comment]
![image](https://github.com/OfficeDev/office-js/assets/67966577/1e105db8-630a-4626-a99e-6772f141390f)
It's reproducing in new document
I use SharePoint.

**Comment by torrinworx** [comment]
Can confirm this issue, I'm seeing `Office.context.officeTheme` as completely undefined. Had to remove all references to it for my application to work. It was working about a couple weeks back.

**Comment by xiruatms** [comment]
Thanks for your confirmation. I've managed to reproduce the issue. It's now being carefully taken care of. I will update here if there're any progress.

**Comment by xiruatms** [comment]
hi @NataliaKravcheniaTR , a fix should be pushed to the production. Will you please take a try with it and help to confirm whether it's working now?

**Comment by NataliaKravcheniaTR** [comment]
Verified on my side. The issue is not reproducible.
