### ISSUE TITLE
Simple CORS mechanism does not allow Content-Type: application/json

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#3733]
Any special reason why the CORS mechanism does not allow the use of 'Content-Type: Application/JSON' ? 
Any chance that this content-type is allowed in the future? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 193780ba-aa43-dc5c-fc28-adc96a0fdeda
* Version Independent ID: da41da2b-207e-e976-3491-61672d1e3493
* Content: [Configure your Outlook add-in for event-based activation - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch?tabs=xmlmanifest)
* Content Source: [docs/outlook/autolaunch.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/autolaunch.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@glr0221 Thanks for your questions.

@exextoc / @samantharamon : Can you advise and update the docs if needed?

Thanks.

**Comment by samantharamon** [comment]
Hi @glr0221,

Apologies for the delayed response. We're looking into this and will reach out once we get clarification on support for this Content-Type.

**Comment by samantharamon** [comment]
Hi @glr0221,

Thanks for your patience. After testing this further, we confirmed that the `application/json` content type is supported when making an XMLHttpRequest in an Outlook on Windows event-based add-in. I will update our documentation to reflect this.

**Comment by glr0221** [comment]
Thank you @samantharamon . I was not able to update this ticket but yes, it is working as expected now.

**Comment by samantharamon** [comment]
No worries, @glr0221! I created PR [#4374](https://github.com/OfficeDev/office-js-docs-pr/pull/4374) to update our documentation. Please note that once the changes are merged, this issue will automatically close. However, if you need additional assistance, please don't hesitate to create a new GitHub issue.
