### ISSUE TITLE
vue-router and office-js doesn't work together

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#3735]
if I don't use vue-router,it's OK.

Error:
```js
const router = createRouter({
  history: createWebHashHistory(),
  routes,
});

```
![1](https://github.com/OfficeDev/office-js/assets/3182964/41842a2e-061c-4a4b-9e85-bcb5d25372f2)

**Comment by Isaac96SM** [comment]
same issue here, any news?

**Comment by ifreeman6** [comment]
Replace the createWebHashHistory as createMemoryHistory, I solve it successfully.

**Comment by xiruatms** [comment]
@hengchengfei , will you please take a try with the solution from @ifreeman6 ?
