### ISSUE TITLE
Shared runtime error

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#3737]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___PC desktop___
* Host [Excel, Word, PowerPoint, etc.]: __Word____
* Office version number: __Microsoft® Word 2019MSO (版本 2309 Build 16.0.16827.20130) 64 位____
* Operating System: ___Windows___
* Browser (if using Office on the web): ___Edge___

```js
  Office.addin.hide();
```

```js
Uncaught runtime errors:
×
ERROR
UnexpectedError
RichApi.Error: UnexpectedError
    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:265825)
    at o.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:330271)
    at https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:328334
```

**Comment by hengchengfei** [comment]
+1

**Comment by xiruatms** [comment]
@hengchengfei , thanks for reporting this. Will you please provide more information about this? Are you still encountering this?  How to repro it? A complete code snippet or sample addin will help us with further investigation.
