### ISSUE TITLE
Office.ribbon.requestUpdate error

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-js#3738]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __Office on the web____
* Host [Excel, Word, PowerPoint, etc.]: ___Word___
* Office version number: __Microsoft® Word 2019MSO (版本 2309 Build 16.0.16827.20130) 64 位____
* Operating System: __Windows____
* Browser (if using Office on the web): __Edge____

RibbonApi=1.1

```js
  Office.ribbon.requestUpdate({
    tabs: [
      {
        id: "DFZQ.Tab1",
        groups: [
          {
            id: "Word.Group.Download",
            controls: [
              {
                id: "DownloadReport",
                enabled: false,
              },
            ],
          },
        ],
      },
    ],
  });
```
```javascript
WordDownloadView.vue:62  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'requestUpdate')
    at eval (WordDownloadView.vue:62:1)
    at step (tslib.es6.mjs:147:1)
    at Object.eval [as next] (tslib.es6.mjs:128:1)
    at eval (tslib.es6.mjs:121:1)
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.mjs:117:1)
    at donwload (WordDownloadView.vue:59:1)
    at callWithErrorHandling (runtime-core.esm-bundler.js:158:1)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:1)
    at emit (runtime-core.esm-bundler.js:664:1)
```

**Comment by penglongzhaochina** [comment]
Hi @hengchengfei ,

I'm confused by your description,
From the Platform [PC desktop, Mac, iOS, Office on the web] line, you said that it is a desktop issue,
From the Browser (if using Office on the web), you said it is a word web issue.

So could you please correct it?
Please fill the Platform [PC desktop, Mac, iOS, Office on the web] line with "Office on the web" if it is a web issue.
Please don't fill the Browser (if using Office on the web) line if it is a Desktop issue.

The same to your other GitHub issue.
Thanks.

**Comment by hengchengfei** [comment]
@penglongzhaochina 

I've changed.

I thought that to develop Office add-in through office-js on PC, I would choose pc desktop

**Comment by xiruatms** [comment]
@hengchengfei , is the issue still here please?
