### ISSUE TITLE
How to Remove Add-in information from a workbook

### ISSUE THREAD

**Issue by bhattikashif** [OfficeDev/office-js#3740]
I have developed an Excel Add-in which uses task pane, custom functions and shared runtime. I have embedded Add-in information in workbook using Office.addin.setStartupBehavior(Office.StartupBehavior.load) so that next time user opens it, add-in starts. If I don't set this behavior, then #NAME? appears against cells having custom functions and Excel embeds _xldudf_ at start of function name.

When users share this workbook with other users who don't have access to Add-in, an error message of you don't have permissions appears. Now I want to remove Add-in information so that users don't get this error message every time they open this workbook. So I asked user to go to Info=> Inspect Document => Remove All Taskpane Add-ins. Now real problem comes, because many users have some protected sheets in workbook due to which other users cannot remove add-in. 

Is there any shorter way to remove add-in (manually or programmatically) while not sharing password or without removing protection?

**Comment by SiruiSun-MSFT** [comment]
Hi @bhattikashif, sorry for the late response. We would like to know what is the purpose of sharing your custom functions? Is it sharing value or sharing function for users to use?

**Comment by bhattikashif** [comment]
@SiruiMSFT, If I get your question, the basic purpose of sharing documents
is to share values returned by custom functions.

**Comment by SiruiSun-MSFT** [comment]
Sorry for the late reply. As far as I know, according to the feature design of CF, a document containing CF will automatically open the related add-in. 
Therefore, if the user does not have permission to add-in, and the purpose is to share the calculation results, perhaps the API can be used to convert all formula values into values, remove all add-ins as the method you mention above, and then share the file.

**Comment by bhattikashif** [comment]
@SiruiSun-MSFT , If I use the option to remove all Taskpane add-ins, then it works as required (i.e. it shows values previously saved) so as per your statement then this should not work then. 

All I want is to remove Inspect=>All Taskpane Add-in=> Remove to work without removing protection from sheet as it solves my problem.

**Comment by SiruiSun-MSFT** [comment]
Sorry, my words may not be clear. 
As far as I know, there is no way to delete all add-ins without turning on protection, because this will change some content or properties of the sheet.
Our suggestion is that if you want users to avoid such problems, you may be able to complete the calculation of the formula and store it as a value in the file when the document is unprotected. Then remove the add-in information, add protection, and then share it with users.
