### ISSUE TITLE
REST requests fail in Outlook for Desktop

### ISSUE THREAD

**Issue by kinkoazc** [OfficeDev/office-js#3741]
## Your Environment

* Platform: PC desktop
* Host: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2311 Build 16.0.16926.20000) 64-bit
* Operating System: Windows 10
* Browser: N/A
 
## Expected behavior
HTTPS requests should work on event-based activated scripts.

## Current behavior
Fetch requests fail with:
```
TypeError: Cannot read properties of null (reading 'sendRequest')
Object.p [as error]
foundation.win32.bundle:17:1838
Object.<anonymous>
[...]
```

## Steps to reproduce
1. Make a REST request in one of the event-based activated scripts.

## Context
I've tried with both GET and POST methods, application/json and application/x-www-form-urlencoded(like here https://github.com/OfficeDev/office-js/issues/558), same result. It works in OWA. POST used to work in Outlook for Desktop as well, until recently. What could cause this?

**Comment by exextoc** [comment]
Is it new outlook for desktop app or the old one?

**Comment by kinkoazc** [comment]
The old one.

**Comment by ndeleuze** [comment]
@kinkoazc just to confirm, you haven't made any changes to the way you are making the REST request from your event-based activated script and it started failing, correct?

I'm also wondering if you would be able to share the event based script where you are making the REST request?

**Comment by kinkoazc** [comment]
@ndeleuze The only change that was made around that time was enabling CORS protection on the backend server. I've tested this locally(by disabling it in the local backend) and the issue is still there.
The event based script is rather complex. But to summarize the call stack of this particular event:
-a compose event is triggered;
-I ask for the bootstrap token(via `OfficeRuntime.auth.getAccessToken`);
-I try to exchange said bootstrap token using a `POST` endpoint of our backend(this is where the issue appears).

**Comment by ndeleuze** [comment]
@kinkoazc after having the backend serber enable CORS, did you follow [these instructions](https://www.bing.com/ck/a?!&&p=c8f683635cbf335aJmltdHM9MTcwMTIxNjAwMCZpZ3VpZD0wNzc3MjE2Yi0xYjg3LTZiM2UtMGQ4YS0zMGNhMWFhMDZhMDkmaW5zaWQ9NTQ5Mg&ptn=3&ver=2&hsh=3&fclid=0777216b-1b87-6b3e-0d8a-30ca1aa06a09&psq=enabling+cors+for+outlook+add-in&u=a1aHR0cHM6Ly9sZWFybi5taWNyb3NvZnQuY29tL2VuLXVzL29mZmljZS9kZXYvYWRkLWlucy9vdXRsb29rL3VzZS1zc28taW4tZXZlbnQtYmFzZWQtYWN0aXZhdGlvbiM6fjp0ZXh0PVRvJTIwZW5hYmxlJTIwc2luZ2xlJTIwc2lnbi1vbiUyMCUyOFNTTyUyOSUyMGluJTIweW91ciUyMGV2ZW50LWJhc2VkLEphdmFTY3JpcHQlMjBmaWxlcyUyQyUyMHRoYXQlMjBzdXBwb3J0JTIwU1NPJTIwb3IlMjBDT1JTJTIwcmVxdWVzdHMu&ntb=1) for enabling CORS for your Add-in?

I'm wondering if this would work after enabling CORS for the Add-in.

**Comment by kinkoazc** [comment]
@ndeleuze Yes, I have. Not sure what was the issue in this reported case, but at a later attempt to debug the problem I got a relevant error logged, which came down to `localStorage` being used instead of `roamingSettings`. Currently I can't reproduce the initial problem. Thank you for the support!
