### ISSUE TITLE
How to remove add-in that's shown in Outlook, but not online

### ISSUE THREAD

**Issue by Lesturb** [OfficeDev/office-js#3743]
I'm reaching out to seek assistance with a perplexing issue related to Outlook add-ins (not admin installed, but user installed). I'm providing this description to eliminate ambiguity and streamline troubleshooting.

**Issue Overview:**

I've been conducting tests on various platforms, including Mac, Windows, and OWA. I've been installing and removing add-ins using manifest.xml files, but I can't pinpoint a specific pattern to reproduce the issue. However, I noticed that the problem emerged after I tried "OUTLOOK ONE" at the top right, which I hadn't experienced before, before OUTLOOK ONE was there, I never had any issues like this, and always took the same steps in the past.

**Here's what I observed:**

I've been installing and removing add-ins through manifest.xml files without issues.
After enabling "OUTLOOK ONE," I started encountering this problem.
Can't remove the add-in through conventional way https://aka.ms/olksideload because it's not there, but showing in Outlook.

**Problem Details:**

At one point, I installed a manifest.xml file and subsequently uninstalled it. Strangely, this action resulted in having the add-ins installed through manifest.xml, and I've been unable to remove them by any conventional means like https://aka.ms/olksideload.

**Unusual Behavior:**

When I visit https://aka.ms/olksideload to check my add-ins, it shows that nothing is installed or enabled. However, these add-ins are still visible within the Outlook application (Microsoft® Outlook® for Microsoft 365 MSO, Version 2309, Build 16.0.16827.20130, 64-bit).

**Additional Testing:**

**To rule out caching issues, I attempted to replicate the problem on a fresh Windows system with Office 365. Even on a clean installation, upon logging in, the same add-in is visible within Outlook but remains absent from https://aka.ms/olksideload.**

**Request for Help:**

My straightforward question is: How can I remove an add-in that is visible in Outlook but doesn't appear within https://aka.ms/olksideload?

I'm seeking guidance, steps, or insights to resolve this enigmatic issue. Your assistance is greatly appreciated.

Environment Information:

    Microsoft 365 MSO Version: 2309
    Build: 16.0.16827.20130
    Platform: Windows 64-bit

Thank you for your support in resolving this matter.

**Comment by bas-eenhoorn** [comment]
Its very simple: it just takes a while. Could be 10 minutes. Could be 4 hours. But it definitely is caching.

I think the caching is not local, and is cached on their server. It has to I think, otherwise how can they cache the addin between browser and desktop etc. But thats why a clean install does not work. Its still cached on their servers

**Comment by Lesturb** [comment]
Thanks for the response but I don't agree. It's been a month, I think that's a bit extreme to test the patience. For the rest I agree with your answer, it must be cached on their side, but not being removed for some reason.

In the following I also mention the issues, but feel no support because they ask for reproduction, which can't be found.. Then I want to know how to clear that cache, because the issue started arising since outlook one and switching back (probably, assumption)

https://github.com/OfficeDev/office-js/issues/3743#issuecomment-1697550678

**Comment by bas-eenhoorn** [comment]
A month? Oh well im sorry for making assumptions then. I guess its an actual bug. Its just that ive seen quite some people asking why the addin wont be removed, and it was always a timing issue. Until now....

Have you tried to use (for testing) a different manifest ID? So Outlook thinks its a new app. Does the same problem occur when using this new manifest? Not saying thats the solution, but maybe you can reproduce it and make a screen recording to show them? Issues like these are always hell to reproduce. Good luck though

**Comment by exextoc** [comment]
Thanks for reaching out. Need a little help to rule out possibilities here. Do you see addins inside the flyout which opens after clicking this icon 
![image](https://github.com/OfficeDev/office-js/assets/28549921/10062a51-758c-45d0-9059-7129cbfdc0a3)
in the affected account?

**Comment by Lesturb** [comment]
@bas-eenhoorn I tried that, and it always keeps the last manifest "stuck" so far I can see.

@exextoc It all started when that icon / Outlook one came and when I click on it I now see several apps, including my manifest, that is different result than before because before our app did not show there.

Because I now saw the app, I decided to again click on "Add apps" which had no option to do something with our app under manage apps.

![image](https://github.com/OfficeDev/office-js/assets/6918780/7d334b6c-d482-4111-8fef-59917b978e4d)

Somehow on the system I did above actions the add-in is now gone, unsure if it's because I messed with the toggle of outlook one, command line actions, or because of clicking the "apps" like asked again.

On my mac system and the clean install system that I mentioned the add-in is still present. If I disable "New Outlook" on the mac the add-in also goes away. When switching back it's also back.

I will now just wait 24 hours and see if the other ones go away before we follow this up? Or if you have ideas I can test please tell me so.

**Comment by exextoc** [comment]
Thanks for reporting the issue. We have this issue in our backlog. We are working towards it but unfortunately, we do not have any timelines to share at this point.
Internal tracking id- 235452
