### ISSUE TITLE
Implement event listeners for NamedItemCollection and NamedItem

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#3744]
### Issue 1
There are currency no event listeners when a defined named item is created inside Excel.

### Workaround
We are currently solving this by fetching NamedItemCollection.items and comparing it against the named items we have stored in application memory every 8 seconds. 

### Problem
Poor performance, if the user edits a cell or open any other dialog the JS execution is stopped and in some edge cases problems occur.

### Proposed solution
Implement an onAdd, onRemove event listener for Excel.NamedItemCollection to notify any newly defined name being created.

-----
### Issue 2
There are currently also no way to detect when an existing defined name is being edited (in the case of renaming a defined name or modifying the cell range).

### Workaround
We are solving the issue as stated above.

### Risk
Same risks as above

### Proposed Solution
Implement an onDataChange event listener for Excel.NamedItem to notify any previously defined names being modified. 

This event listener should have at least the below data in the arguments:
1. type of the NamedItem
2. value of the NamedItem
3. scope of the NamedItem

**Comment by jeremy-msft** [comment]
Hi @BoramSpark, thanks for your feedback. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process.
