### ISSUE TITLE
Outlook API how to display Forward Form from a MessageRead

### ISSUE THREAD

**Issue by ilbrando** [OfficeDev/office-js#3746]
I can display a reply form using the [displayReplyForm ](https://learn.microsoft.com/en-us/javascript/api/outlook/office.replyformattachment?view=outlook-js-preview) function, but the API seems to be missing a forward counterpart. As far as I can understand it is somewhat possible to achieve this using `displayReplyForm` but then I have to include attachments myself, and I struggle to figure out how that is done.

The [AttachmentDetails](https://learn.microsoft.com/en-us/javascript/api/outlook/office.attachmentdetails?view=outlook-js-preview) from the `MessageRead` object doesn't seem to be easily converted to a [ReplyFormAttachment](https://learn.microsoft.com/en-us/javascript/api/outlook/office.replyformattachment?view=outlook-js-preview) object.

**Comment by ilbrando** [comment]
Also the user expects the subject to be updated with "Fw:" (in the right language). I feel this is a responsibility for Outlook.

**Comment by Oleg-O** [comment]
Currently the feature: displayForwardForm API, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
