### ISSUE TITLE
Outlook on the web randomly stopped loading custom add-ins

### ISSUE THREAD

**Issue by SimonDania** [OfficeDev/office-js#3749]
## Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Online
* Operating System: Windows 11
* Browser (if using Office on the web): Google Chrome
 
## Expected behavior
The add-in gets loaded in and is visible when composing mails.

## Current behavior
I have been using some custom add-ins that I have sideloaded in Outlook on the web using https://outlook.office.com/mail/inclientstore.

They were working just fine without any issues, but for the past week or so they suddenly stopped loading for no apparent reason. There are no errors to be seen in the log either regarding add-ins.

The add-ins still load as expected in Outlook 365 without any problems.

What can I look for? Is anyone else experiencing the same issues?

# Provide additional details
I tried following the guide for setting up a new custom add-in with the yeoman generator, and even that add-in does not appear when I sideload it in Outlook. It works just fine in the client.

## Context
We have some customers that are not able to use our product anymore because of this issue.

**Comment by exextoc** [comment]
Can you please confirm if you have this apps 
![image](https://github.com/OfficeDev/office-js/assets/28549921/bdfe35af-051b-41d6-991b-e43637be3c4b)
 button or not when you open any mail.

**Comment by SimonDania** [comment]
I do have it:
<img width="421" alt="image" src="https://github.com/OfficeDev/office-js/assets/85676333/85ac3c20-e360-4f87-b1df-213381b1c090">

Add-ins I install from AppSource work just fine. It's only apps that I sideload that don't appear.

**Comment by exextoc** [comment]
Can you try a hard refresh / clear cache and see if sideloaded add-ins appear? There is a recent roll-out which has happened to fix this issue.

**Comment by SimonDania** [comment]
I have tried clearing the cache / deleting application data in the browser as well as doing a hard refresh, but unfortunately it doesn't seem to make a difference.
I have also tried in the Edge browser as well as in incognito, but none of it made a difference, unfortunately.

We did have some issues with the client as well, but those issues got resolved yesterday after what I believe happens to be the roll-out you are referring to :-)

**Comment by carlosb1504** [comment]
Same issue as https://github.com/OfficeDev/office-js/issues/3745? Not just affecting sideloaded add-ins but admin-deployed too. Affecting us internally and our customers too.

**Comment by exextoc** [comment]
@SimonDania We have a fix getting rolled out currently and expected to be in prod by tomorrow. In case the issue persists tomorrow please post here.

**Comment by SimonDania** [comment]
@exextoc Perfect, thank you. 
I will check tomorrow.

**Comment by avisheknand** [comment]
Some of our accounts seem to have Get-addin button, some of them has the App button (where custom addin does not show). Will wait for a day to see if it reverts back

**Comment by SimonDania** [comment]
@exextoc I don't know if it's too early to chip in, but it still doesn't seem to work.
I have tried doing a hard refresh as well as clearing all cache and application data in my browser.

**Comment by SimonDania** [comment]
I have cleared my cache this morning and tried again, but unfortunately it seems like it still doesn't work.

**Comment by carlosb1504** [comment]
We also have customers not able to see our add-in in their OWA environments which is causing a high number of complaints. Any updates please @exextoc ?

Thanks

**Comment by SimonDania** [comment]
Parts of the add-in seem to work now in Outlook on the web.
The `OnNewMessageCompose` event correctly fires and the add-in is loaded.

However, it seems the `OnMessageRecipientsChanged` does not fire at the moment.
I'll give it a couple of days and check again.

**Comment by frnode** [comment]
> Parts of the add-in seem to work now in Outlook on the web. The "OnNewMessageCompose" event correctly fires and the add-in is loaded.
> 
> However, it seems the "OnRecipientsChanged" does not fire at the moment. I'll give it a couple of days and check again.

I don't know if this can help you, but there are certain events that are not functional in Outlook on the web, see my report: https://github.com/OfficeDev/office-js/issues/3721

Maybe it's related. The events I reported are not firing.

**Comment by frnode** [comment]
> Parts of the add-in seem to work now in Outlook on the web. The "OnNewMessageCompose" event correctly fires and the add-in is loaded.
> 
> However, it seems the "OnRecipientsChanged" does not fire at the moment. I'll give it a couple of days and check again.

We have just done a test on our side, `OnMessageRecipientsChanged` is not triggered on the OWA (nor on Outlook Windows.). By it is functional on the New Outlook (Windows).
Did you use the `OnMessageRecipientsChanged` trigger in your LaunchEvent?

`<LaunchEvent Type="OnMessageRecipientsChanged" FunctionName="onMessageRecipientsChangedHandler"/>`

**Comment by SimonDania** [comment]
@frnode Yeah, it is `OnMessageRecipientsChanged` that we use. Sorry for the mistake!
It has started working for some people internally at our company.

**Comment by exextoc** [comment]
@frnode  @SimonDania 
Are you still facing the issue for Outlook on the Web. If so, can you provide following details about the add-in.

- When was the add-in installed and how?
- Can you try re-installing the add-in, do a hard refresh and see if the add-in appears or not?

**Comment by SimonDania** [comment]
@exextoc The add-in appears and the event `OnNewMessageCompose` fires as expected.
However, the event `OnMessageRecipientsChanged` does not fire, so that part still doesn't work.

We can't seem to get the `OnNewMessageCompose` event to fire on mobile either.

**Comment by SimonDania** [comment]
Update: `OnMessageRecipientsChanged` works for us as well now.
We haven't made any changes in the meantime, so I assume Microsoft solved it in their end.

I am closing this thread as we are no longer facing issues.
