### ISSUE TITLE
Cannot save Custom Properties on Calendar Event in new Outlook

### ISSUE THREAD

**Issue by robraytaylor** [OfficeDev/office-js#375]
Cannot save Custom Properties on Calendar Event in new Outlook

## Expected Behavior
In the current version of outlook (not new) we can load and save custom properties using the following API call in Office JS ; 
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.7/office.context.mailbox.item#loadcustompropertiesasynccallback-usercontext

## Current Behavior
In the new version of outlook we can not save custom properties using the Office JS API mentioned above. They can be loaded however.

## Steps to Reproduce, or Live Example
Here is an example of the code we are using to load / save custom properties.
`    async setCustomPropertyAsync(key, value) {  
        return await new Promise((resolve, reject) => {  
            this._office365Client.context.mailbox.item.loadCustomPropertiesAsync(  
                result => {   
                    try {  
                        if (result.error || !result.value) reject(result.error);  
                        else {  
                            result.value.set(key, value);  
                            result.value.saveAsync(saveResult => {  
                                if (saveResult.error) reject(saveResult.error);  
                                else resolve(saveResult.value)  
                            });  
                        }  
                    } catch (error) {  
                        reject(error);  
                    }  
            });  
        });  
    }`

## Context
We have an outlook add in which relies on loading/saving custom properties against calendar events which no longer works in Outlook Online when "The new Outlook" is checked. This will cause us to have to ask customers to disable this.

## Your Environment
* Platform  Office Online
* Host Outlook
* Browser (if using Office Online): Chrome

## Useful logs

- [x] Console errors
[outlook.office.com-1549467401481.log](https://github.com/OfficeDev/office-js/files/2837008/outlook.office.com-1549467401481.log)
- [x] Request as Fetch from Network tab
`fetch("https://outlook.office.com/owa/service.svc?action=SaveExtensionCustomProperties&n=37&EP=1&app=Calendar", {"credentials":"include","headers":{"accept":"*/*","accept-language":"en-GB,en-US;q=0.9,en;q=0.8","action":"SaveExtensionCustomProperties","content-type":"application/json; charset=utf-8","ms-cv":"6m1sp3QLJvK9Qau1G9oxgI.44","x-owa-canary":"8eN_PZ9yVkyX3zPchdMG0RD9U_NGjNYYNLVjHZTI5qlNoiEistsTKYQSiSom999lsO_AWs6Ajh4.","x-owa-correlationid":"ba74673f-4743-00e7-164d-30d7abd903ba","x-owa-urlpostdata":"%7B%22request%22%3A%7B%22__type%22%3A%22SaveExtensionCustomPropertiesParameters%3A%23Exchange%22%2C%22ExtensionId%22%3A%22d696a29b-e3f0-4f5b-be48-b8b4f7657b3e%22%2C%22ItemId%22%3Anull%2C%22CustomProperties%22%3A%22%7B%5C%22gmsoPasscode%5C%22%3A%5C%22867951720%5C%22%7D%22%7D%7D","x-req-source":"Calendar"},"referrerPolicy":"no-referrer","body":null,"method":"POST","mode":"cors"});`

**Comment by JosephJShort** [comment]
More useful logs
------------------

The server responds with a 500 and the following text:
`{"Body":{"ErrorCode":500,"ExceptionName":"ErrorInvalidIdEmptyException","FaultMessage":"Id must be non-empty.","IsTransient":false,"ResponseCode":"ErrorInternalServerError"}}`

The request payload is a URL-encoded JSON blob inside the `x-owa-urlpostdata` header.
`{"request":{"__type":"SaveExtensionCustomPropertiesParameters:#Exchange","ExtensionId":"d696a29b-e3f0-4f5b-be48-b8b4f7657b3e","ItemId":null,"CustomProperties":"{\"gmsoPasscode\":\"867951720\"}"}}`

It appears that Office.js is not populating the `ItemId` property correctly, and this is causing an error on `outlook.office.com/owa/service.svc`.

**Comment by exextoc** [comment]
Thanks for reporting the issue. We've confirmed that save custom properties not working currently for new Outlook Web, and are looking into it further.

**Comment by exextoc** [comment]
Can you please try this again now?

**Comment by robraytaylor** [comment]
Hiya, Yep it is working now. Thankyou.
