### ISSUE TITLE
The Outlook add-in does not load correctly in Outlook 2019 volume license

### ISSUE THREAD

**Issue by dat-vt** [OfficeDev/office-js#3750]
Greetings, Office Dev Team,

We are currently in the process of developing a custom Outlook add-in for internal use. Our add-in includes a feature where, upon clicking the action button, a dialog is triggered to confirm a specific function. Once confirmed, the dialog should close, and the associated event should be marked as completed.

## Our Environment
* Platform: PC Desktop
* Host: Outlook
* Office version number: 10402.20023
* Operating System: Windows 10 Enterprise LTSC (Version 10.0.17763)
 
## Expected behavior
- Our add-in includes a feature where, upon clicking the action button, a dialog is triggered to confirm a specific function. Once confirmed, the dialog should close, and the associated event should be marked as completed.
- Our Outlook add-in functions as expected in the following environments:
  - Outlook web app
  - Outlook mac
  - Outlook Window app (Office 2019 retail (build 16731.20234))

## Current behavior
- We encountered an issue when attempting to use our custom add-in in the Office 2019 volume license version (build 10402.20023). When clicking the action button, an alert message appears, and the add-in seems to hang at the following message:
> [add-in name] is working on your [add-in name] request

- In some cases, an additional alert message appears:
> Sorry, you couldn’t access [add-in name]. Please check your internet connection. If it still fails, please try again.

## Steps to reproduce
1. Install the add-in through a manifest file
2. Click the Outlook add-in

## Provide additional details
We have attempted to troubleshoot this error using IEChooser, but we were unable to access the Outlook add-in's HTML.

## File
[outlook-add-in.zip](https://github.com/OfficeDev/office-js/files/12881971/outlook-add-in.zip)

---
Could you investigate this issue? We've provided our relevant files for your reference.

Thank you for your assistance.

**Comment by millerds** [comment]
Sorry for the delayed response.

The code in your zip file is using getAllInternetHeadersAsync API which was introduced in API set 1.8 (https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/internet-headers#purpose-of-the-internet-headers-apis), but Office 2019 volume license only supports up to set 1.7 (https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets?view=common-js-preview&tabs=jsonmanifest#outlook-client-support).  You can't use it if you want to support Office 2019 volume license.
