### ISSUE TITLE
Not able to sideload unified manifest on new outlook for outlook windows using teams toolkit

### ISSUE THREAD

**Issue by rohanbharadwaj1994** [OfficeDev/office-js#3752]
# Provide required information needed to triage your issue
I am trying to sideload my app (which is a unified manifest for Outlook and teams) using teams toolkit. It is getting sideloaded for classic outlook on windows desktop but when i try to switch on to new outlook, my add-in doesn't get sideloaded or i am not even seeing the entry point as well in the new outlook.

<img width="719" alt="Screenshot 2023-10-13 at 2 31 25 AM" src="https://github.com/OfficeDev/office-js/assets/143542256/03ad48e9-39a6-4c77-8159-c5efc8cafb62">
<img width="550" alt="Screenshot 2023-10-13 at 2 31 49 AM" src="https://github.com/OfficeDev/office-js/assets/143542256/46c74de4-16d6-4b2b-b52b-0d6ab751b45a">

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows
* Browser (if using Office on the web): N/A
 
## Expected behavior
Add-in should sideload in the new outlook

## Current behavior
Add-in is not able to sideload in the new outlook for outlook desktop, but able to sideload in outlook classic for outlook desktop

## Steps to reproduce
1.) Create a unified manifest for Outlook and teams app
2.) Using teams toolkit, run and debug on outlook windows (Chromium edge)
3.) It will open up outlook desktop.
4.) Toggle to new outlook and see that your add in is not getting loaded in the message read tab 

Can you help here ?

**Comment by rohanbharadwaj1994** [comment]
@exextoc can you please help on this

**Comment by ankushgup2a** [comment]
Getting the same issue @exextoc .. pls help. @rohanbharadwaj1994 : were you able to solve this ?

**Comment by ndeleuze** [comment]
@rohanbharadwaj1994 Just to clarify, does the Add-in ever appear on the ribbon in the new Outlook, even after a few hours? Or can you only see it in the old Outlook?

**Comment by rohanbharadwaj1994** [comment]
@ndeleuze Nope, I cannot see the add-in on the ribbon in the new Outlook.
But when I switch to old Outlook, I can see it in the ribbon.
Also, to clarify in the inbox for a new outlook, there's no place for an add-in in the ribbon. Instead, it appears in the message's mail more options as per above screenshot but it is not showing in the new outlook when sideloading via Teams toolkit or office-debugging tool

**Comment by exextoc** [comment]
@rohanbharadwaj1994 - In new outlook, add-ins don't show up in the ribbon for read surface. You can find them at the following location in the email similar to OWA.

![image](https://github.com/OfficeDev/office-js/assets/28549921/c4dd1e63-963d-4096-a86e-f7475c733556)

**Comment by rohanbharadwaj1994** [comment]
@exextoc That I know but it's not showing up there also when we trying to sideload via teams toolkit either by using unified manifest or normal XML manifest.
Add-in is getting sideloaded and showing up in new outlook onluy when i upload the XML manifest manually.

**Comment by exextoc** [comment]
@rohanbharadwaj1994 Can you please share the manifest?

**Comment by rohanbharadwaj1994** [comment]
[manifest.json](https://github.com/OfficeDev/office-js/files/13185960/manifest.json)

**Comment by rohanbharadwaj1994** [comment]
@exextoc Here's the manifest file.
Please note that this is unified manifest for office with outlook capabilities and is under preview and will only work for outlook desktop

**Comment by rohanbharadwaj1994** [comment]
@exextoc can you help on this ?

**Comment by exextoc** [comment]
@rohanbharadwaj1994 It takes some time for addin to sync and show up in new outlook. The max sync time is 4 hours. Can you confirm if the addin does not show up after 4 hours?

**Comment by rohanbharadwaj1994** [comment]
@exextoc No it's not been showing even after 4 hours

**Comment by exextoc** [comment]
Can you please capture log for the user and send it over to `user0@a830edad9050849w1IYcOvTMcAr.onmicrosoft.com` ?
You can use fiddler to do the same. Please start recording as soon as the outlook session starts.

Please share a trace for OWA where its working, and new Outlook where it's not.
