### ISSUE TITLE
On-Send Event triggers twice on new Outlook for Mac

### ISSUE THREAD

**Issue by avisheknand** [OfficeDev/office-js#3753]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: __Outlook____
* Office version number: ___16.78(23100802)___
* Operating System: ___macos ventura___
* Browser (if using Office on the web): __new Outlook for Mac____
 
## Expected behavior

On-Send event should fire once and email should send.

## Current behavior

On-Send event triggers twice when sending out email on the new Outlook for Mac. If revert back to legacy, in legacy it fires once.
## Steps to reproduce

1. Update Outlook for Mac to 16.78 (23100802)
2. Switch to New Outlook
3. Ensure to have a app that uses On-Send
4. Send Email. The On-Send fires twice for the addin

**Comment by exextoc** [comment]
@avisheknand  Is the add-in updating the body of the e-mail during the first run?

Please generate the Incident ID from New Outlook App by following steps and share it with us. 
1. Restart Outlook
2. Repro the issue mentioned above
3. Click on Help->Collect Diagnostics
4. Copy the Incident ID generated

**Comment by avisheknand** [comment]
@exextoc , the incident id is QJTMEYZV

**Comment by exextoc** [comment]
@avisheknand from the logs it appears add-in is trying to set the recipient on the email just before event.completed. Can you confirm if this async call completes before invoking event.completed?
If not, please update the add-in code to call event.completed after all async API calls are completed by Add-in.

If the issue still occurs, please share the add-in manifest will us, so that we can repro the issue.

**Comment by John-Dawson** [comment]
For what it's worth, this happened to me; the cause was that the App was deployed twice: via Office Admin and also sideloaded

**Comment by avisheknand** [comment]
@exextoc , you were right!. We were not waiting for recipients setasync  and were calling the event.complete . It was not creating any issues on any other platform apart from New Outlook for Mac... interesting. We have fixed this and it seem to be working now without any issues. Thanks so much!!!!!!

**Comment by avisheknand** [comment]
@exextoc ,  i am facing same issue again. The Onsend event triggers twice, i have checked that the event.completed is called after the set recipients callback is successful. It was working fine after we fixed the addin for a while and it started to appear again. The add-in is not installed twice.

Here is the new incident id is EXY59ZBX. Any help will be appreciated.

**Comment by avisheknand** [comment]
@exextoc ,  i am facing same issue again. The Onsend event triggers twice, i have checked that the event.completed is called after the set recipients callback is successful. It was working fine after we fixed the addin for a while and it started to appear again. The add-in is not installed twice.

Here is the new incident id is EXY59ZBX. Any help will be appericated.

**Comment by rajjha-msft** [comment]
Hey @avisheknand 

It is not a repro for us. 
- Can you please create a sample add-in and attach which can be used to reproduce the issue?
- Also, when you say OnSend event is it ItemSend or the new Smart alerts ?
