### ISSUE TITLE
How to differentiate Between Legacy Outlook on Mac and New Outlook for Mac

### ISSUE THREAD

**Issue by avisheknand** [OfficeDev/office-js#3754]
I would like to know if there is a way to differentiate Between Legacy Outlook for Mac and with New Outlook for Mac using Office.js API?

As for Windows, the Classic Outlook for Windows and New Outlook for Windows can be differentiated by the Office.context.mailbox.diagnostics property, where the Classic Outlook returns "outlook" and New Outlook returns "oneoutlook".

Is there any way to do for MAC??

**Comment by exextoc** [comment]
@avisheknand  Could you please let us know in which scenario the Add-in needs to differentiate between Legacy Outlook and New Outlook for Mac?

**Comment by avisheknand** [comment]
@exextoc ,The add-in needs to perform attachment scanning. Attachment information is retrieved via the Microsoft Graph API. In Legacy Outlook, the attachment takes some time to sync on the server, whereas in the New Outlook for Mac, the attachment is immediately available on the server. Therefore, we would like to support attachment scanning in the New Outlook for Mac and bypass Legacy Outlook for Mac, which we understand is limited by caching and item syncing

**Comment by CurtisRiva** [comment]
@exextoc , 
I second this.  We need to be able to identify Outlook classic vs New Outlook on Mac due to some bahvioural differences between the two.

**Comment by exextoc** [comment]
Currently there is no way to differentiate between Old and New Mac Outlook via Office.js api. 

One thing you could potentially do is to check for api set support. That is not an official solution, but see if it works for you. Old Outlook doesn't support api set 1.9 and above.

**Comment by avisheknand** [comment]
@exextoc, thank you for the suggestion. Ideally if a value is added to the Office.context.mailbox.diagnostics in office.js Api will be appreciated. It will ease the life's of developers to differentiate ENV's

**Comment by exextoc** [comment]
@avisheknand  We track Outlook add-in feature requests and suggestions on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by smaramwbc** [comment]
any news on that?
