### ISSUE TITLE
Custom outlook office js addin cannot install using url

### ISSUE THREAD

**Issue by ArjunSureshKumar92** [OfficeDev/office-js#3757]
Recently we have noticed, the option to add a custom outlook addin (office js) using a URL is not longer working. The option is greyed out for some reason. 

Screenshot attached below:
![image](https://github.com/OfficeDev/office-js/assets/35875176/5996c6c6-5f8a-4f5e-a93a-fcae6f1ecef2)

**Comment by truchonh** [comment]
Can confirm, same issue for our org. On Office 365, from OWA, using the url given from the documentation (https://aka.ms/olksideload), the add from URL button is disabled.

**Comment by Raphael-Lvy** [comment]
Same issue here, the URL button is disabled on Outlook web. Tried on Chrome, Firefox, Safari and Edge

**Comment by avisheknand** [comment]
Same issue here, Add from URL is not enabled on OWA. Latest updates seem to have caused this issue

**Comment by t-miyake** [comment]
Same issue here!

**Comment by clavx** [comment]
There seems to have been a specification change, see https://github.com/OfficeDev/office-js/issues/3745#issuecomment-1761194542

**Comment by zhngx1** [comment]
The Add from URL option is no longer available to sideload a custom Outlook add-in. As a workaround, open the URL in your preferred browser to download the manifest file, then use the Add from File option to sideload the add-in. 
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=windows#outlook-2016-or-later
