### ISSUE TITLE
Office Web Addin : API first hit is always failing in Outlook Web Plugin .On every API call it gives a network error but if we reload the window then API call is successful 

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#3760]
Office Web Addin : API first hit is always failing in Outlook Web Plugin .On every API call it gives a network error but if we reload the window then API call is successful 

Reproducible Platform : Mac Outlook Thick Client
Outlook Version : Microsoft Outlook 16.77.1 (23091703)
MAC OS version -   macOS Ventura 13.5.1

**Comment by exextoc** [comment]
@geetamshukla  Please share the following details with us

- Are you referring to a Task Pane add-in? It would be great if you share the exact steps.
- Do you see any error in the console during the first run?
- Please share the Incident ID from Outlook Mac 
    1.  Re-launch Outlook
    2. Repro the issue 
    3. Navigate to Help->Collect Diagnostics and share the Incident ID generated.
