### ISSUE TITLE
MessageReadCommandSurface not working in outlook web

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#3762]
[MessageReadCommandSurface not working in outlook web]

MessageReadCommandSurface. When I run the add in, it works well in the Outlook desktop app on Windows and I see the button in the ribbon as expected, however the add in and button does not appear when I log in to Outlook web. I can see that the add in is installed though.
 
Is the MessageReadCommandSurface extension point supported in Outlook web? 
 
As a side note, the MessageComposeCommandSurface extension point seems to work fine.

**Comment by exextoc** [comment]
Add-in on MessageReadCommandSurface should populate when you click on the Apps button.
<img width="641" alt="image" src="https://github.com/OfficeDev/office-js/assets/28549921/6b768cc1-9dfc-48e8-9c4f-37f0ab22aff9">


<img width="265" alt="image" src="https://github.com/OfficeDev/office-js/assets/28549921/a0255ff4-1ded-43cb-b746-198329200dfb">
 
Is the Add-in not populating in the Apps flyout? Do you see any other add-ins in the flyout?
