### ISSUE TITLE
loadCustomPropertiesAsync does not immediately appear in Graph API

### ISSUE THREAD

**Issue by ttuyen1529** [OfficeDev/office-js#3763]
I used loadCustomPropertiesAsync to load custom properties of an item in user calendar then save it into this item.
Then in back-end of our system, there is subscription to hear change notification of a room's calendar when user send the meeting request to this room's calendar
But when back-end receive the push notification from Graph API, we use IcalUID from that notification to query back to the user's calendar to load custom properties using ID on manifest file of our add-in using expand and filter of OData in Graph API

But about 40% we miss that information since the log showing that Graph API return null value

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on Windows 11
* Host [Excel, Word, PowerPoint, etc.]: Outlook

Why can this happen since I thought that item in user calendar always created first

**Comment by millerds** [comment]
If I understand the high-level scenario correctly you are using an add-in to save some properties that the back-end system (not an add-in) is trying to retrieve via Graph API.  Is that correct?

I'm a little confused on the details of how loadCustomPropertiesAsync is used.  Are you using it in an add-in to get some properties that you are storing somewhere else?  If so where are you storing it?

**Comment by ttuyen1529** [comment]
Hi @millerds 
I only use this function in Appointment compose mode and will mark this Appointment was handle by our add-in for this meeting
So when back-end receive notifications for changes on calendar of some rooms, back-end will someway track back to organizer's calendar to see if this meeting was handle or not

**Comment by ttuyen1529** [comment]
And I can confirm that this function works since we always see the value saved, but Graph API sometimes miss it by the time we need for it

**Comment by millerds** [comment]
That doesn't sound like a problem of the loadCustomPropertiesAsync API, but rather a timing issue between running the add-in to "mark this Appointment was handle by our add-in" (what does that mean?) and the event firing that the back-end it looking for.  These don't sound like operations that are going to be synchronous.  What happens if you back-end waits a bit before trying to read (giving the add-in time to finish operating)?

**Comment by ttuyen1529** [comment]
Hi @millerds
Not much to mentioned the flow but the back-end only get the custom properties when that meeting request was sent to receipt email in this case is room mailbox because we use subscription API from Graph to listen change on this room's calendar

**Comment by millerds** [comment]
So if the add-in is always succeeding to "mark this Appointment was handle by our add-in" (again . . . I'm not sure how that is accomplished) and the meeting gets sent, then that doesn't sound like a problem with loadCustomPropertiesAsync (which is only reading and not writing) or other office.js APIs.

**Comment by ttuyen1529** [comment]
Yes, but as the title, I do not know exactly how long or how many times I need to try when call Graph API to get this custom property. Then that is my problem

**Comment by millerds** [comment]
This is the office.js API for add-ins.  If you're having trouble with a Graph API on the back-end that is different.
