### ISSUE TITLE
Unable to access localStorage in outlook add-in (manifest file) in chrome browser in office 365 online

### ISSUE THREAD

**Issue by ZabeehUllah** [OfficeDev/office-js#3765]
**System Overview**
I have two web apps (salesX and workbench) and one outlook add-in. All of them have a unified login and are hosted on the same domain. When I log into a single one of them, I can login into other two as well because I can access localStorage of the logged in app and get access to the token.

**Environment**
- Platform: PC desktop, Mac, Cross Platform
- Host: Outlook add-in
- Office version number: Office 365
- Operating System: Windows
- Browser (if using Office on the web): Chrome, Edge, Safari

 **Expected behavior**
If I log into salesX webapp, for instance. Now, If I visit worbench webapp, it should be logged in. Similarly, if I open outlook add-in, it should be logged in too.

**Current behavior**
Currently, when I log into any of the web app, and visits the other web app it is logged in. However, my outlook add-in isn't logged in. When I view it's localStorage, it's empty, there is NO TOKEN present there. However, if I log into add-in my web apps are logged out and vice versa.

**Steps to reproduce**
Workbench link: [https://xiqworkbench.xiqonline.com/](https://xiqworkbench.xiqonline.com/campaigns)
SalesX link: https://salesx.xiqonline.com/
Link to my manifest file: https://drive.google.com/file/d/1Dn7cazLKnEr3X8ztvqaEPme0eVTN8aJi/view?usp=share_link

**Comment by exextoc** [comment]
Does this issue repro if the add-in login page is loaded separately in the browser or only when the add-in loaded via Task Pane?

**Comment by ZabeehUllah** [comment]
When add-in login page is loaded in the task pane. Basically, in the task pane I am loading my website in an iframe. The website in that iframe has the same domain as my other two webapps.

**Comment by ZabeehUllah** [comment]
@exextoc I am still waiting for the response. A quick response would be appreciated regarding the above issue. Thank you.

**Comment by exextoc** [comment]
Are you seeing this issue in OWA only, or does it repro in other platforms (Desktop Outlook / Mac)?

**Comment by ZabeehUllah** [comment]
The issue is produced in OWA.

**Comment by exextoc** [comment]
@ZabeehUllah - Unfortunately this is a limitation of the product. You will not be able to share localstorage between iframes.

**Comment by ZabeehUllah** [comment]
Firstly, this issue have been reproduced recently. Previously, my web app loaded in the iframe in outlook addin could access local storage of salesx and workbench app. It used to login after signing in to any of the orher two apps. Secondly, I am using single iframe, in the addin, not multiple iframes. 
Kindly give me a little detail regarding the issue or heads up in the right direction to solve this issue.

**Comment by exextoc** [comment]
@ZabeehUllah Thank you for confirming that this used to work before and stopped working recently. I installed the add-in, but was not sure how to repro what you are seeing.

![image](https://github.com/OfficeDev/office-js/assets/28549921/a1d3eb2e-0397-4678-9997-14ce314f4125)

Can you please either share the repro video?

**Comment by ZabeehUllah** [comment]
@exextoc I have add the video below. I have followed following steps in the video.

Step1:
Login into salesX web app using sso (unified login)
https://salesx.xiqonline.com/

Step2:
Visited workbench web app and refreshed it. It logged in to because of unified login. It accessed csrf token from localStorage placed by salesX.
[https://xiqworkbench.xiqonline.com/](https://xiqworkbench.xiqonline.com/campaigns)

Step3:
Visited office add in. Reloaded the iframe, but it didn't log in. There was no csrf token in localStorage, although it is hosted on the same parent domain as the other two.

Intended Flow:
The web app in outlook addin iframe should be logged in too if any of the web app is logged in and vice versa. It was working fine previously.

Confusion:
Why is there no token in Addin web app localStorage?

**Comment by ZabeehUllah** [comment]
@exextoc I have uploaded the video as per your request. Please let me know about your findings regarding the issue. Thank You!

**Comment by exextoc** [comment]
@ZabeehUllah Don't see any repro video link in the previous comment, can you re-share. Also answer the following questions to help understand the problem:
1. Date or version where this was working in OWA.
2. Does it work in Outlook Desktop and Mac outlook client?
