### ISSUE TITLE
newdoc.open() fails in test environment

### ISSUE THREAD

**Issue by isawek** [OfficeDev/office-js#377]
I created a Word Add in to filter some documents from sharepoint and open it in Word.
It works fine in my dev environment but when we test it in our test environment it fails with an General Exception on newDoc.open();
 
i recognized that it works when my code looks like the following example:

```
private _openDocumentWithPlaceholder(fileToOpen) {
	Word.run(async context => {
		let newDoc = await context.application.createDocument(fileToOpen);

		//Here is some magic
		...
		
		if (this.state.cancelOpening || errorOccured) {
			this.setState({selectedTemplate: undefined, isProcessing: false});
			return;
		} else {
			newDoc.open();
			this._reload();
		}

		context.sync();
		}).catch(e => {
			console.log(e);
		});
	}
}
```

but when i try to load properties or f.e. run context.sync() after calling `newDoc.properties.customProperties.getItem('test');` my code fails at newDoc.open();

**Comment by isawek** [comment]
My thinking is, that every context.sync() before calling newDoc.open() crashes the newDoc.open() in the test environment but i don´t have an idea why

**Comment by JuaneloJuanelo** [comment]
@isawek  its not clear from your code when are you trying to get the properties. Is this before calling newDoc.Open()? FYI after you call Open() on the new document we are blocking any operations so you need to do it before. Also note that modifying the document is not an operation supported across platforms. 

finally here is a sample showing how you can get the document (that snippet shows create and insertion of document, please focus on the creation methods ) 
 https://gist.github.com/JuaneloJuanelo/0d8c5fbad8ca2147c88843daad891a4e

you can restore it on script lab.

**Comment by isawek** [comment]
I try to get the properties at this Point (//Here is some magic...).

i tried to build it with contentControls but there is the same problem in our test environment. I have to load the contentControls and sync the context before open the document but if i do this the document wont get opened.

` let newDoc = await context.application.createDocument(fileToOpen);`

**Comment by isawek** [comment]
I try to get the properties at this Point (//Here is some magic...). And the doc doesnt open if i do a load and sync before opening.

i tried to build it with contentControls but there is the same problem in our test environment. I have to load the contentControls and sync the context before open the document but if i do this the document wont get opened.

```
let newDoc = await context.application.createDocument(fileToOpen);

let cControls = newDoc.contentControls;
context.load(cControls);
await context.sync();

let currentControl = cControls.getByTitle('myTagTitle');
context.load(currentControl);
await context.sync();

//get first control and replace its content
let contr = currentControl.getFirst();
context.load(contr);
await context.sync();

contr.insertText('newValue', 'Replace');
await context.sync();
```
