### ISSUE TITLE
[Mac] Unable to access Office.context.ui object in dialog window

### ISSUE THREAD

**Issue by splinter** [OfficeDev/office-js#378]
We are initiating an SAML SSO flow in a dialog window that is opened via an Outlook plugin. The login
flow completes but we are not able to call the messageParent method on the Mac Outlook 2016 client.The 
Office.context.ui object is not available when debugging the issue.

This behaviour is only present on the Mac Outlook 2016 Desktop Client, I have tested the following scenarios:
  - Outlook Live on Firefox,Chrome and Safari (Both on Mac and Windows)
  - Windows Outlook 2016 Desktop client
  - Mac Outlook 2016 Desktop Client (16.21) (190117) - Fails

## Expected Behavior
The Office.context.ui object should be available to the execution context in the dialog window.

## Current Behavior
The Office.context.ui is undefined when accessed from the dialog window 

## Steps to Reproduce, or Live Example
- Open a dialog window using Office.context.ui.displayDialogAsync
- Attempt to post a message to the host using Office.context.ui.messageParent

*Additional details:*
- The dialog window performs a redirect to our API (different domain) which generates the script which calls the dialog API
- The API domain is added to the list of app domains in the manifest

## Context
We are trying to authenticate the user via a SAML SSO flow in a dialog window.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac Outlook 2016 Desktop Client (16.21) (190117) 
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Mac Outlook 2016 Desktop Client (16.21) (190117) 
* Operating System: Mac
* Browser (if using Office Online): N/A

## Useful logs
N/A

**Comment by markb-trustifi** [comment]
Hi.
Are you calling `messageParent` from inside `Office.initialize = function (reason) {...}` ?

**Comment by splinter** [comment]
I am using the Office.onReady method to register a callback within which I am calling Office.context.ui.messageParent.

**Comment by JSteunou** [comment]
Hi @markb-trustifi , I have exactly the same bug on OSX 10.13 Mac PowerPoint 16.22 (190211)

On the `Dialog`, after the auth is complete, I'm inside a `initialize`, `Office.context.isDialog` is `false`, object `Office.context.ui` is present, but `messageParent` is `undefined`

No error with web office.

**Comment by markb-trustifi** [comment]
You can try to solve this issue the way that I did:
https://github.com/OfficeDev/office-js/issues/382#issuecomment-463261231

**Comment by JSteunou** [comment]
I could give it a try thanks. I though you re a member of the OfficeDev team, sorry to ping you like that.

**Comment by JSteunou** [comment]
@markb-trustifi using native `postMessage` is indeed simpler and have the advantage to work at least

**Comment by JSteunou** [comment]
@dmahugh why closing this issue? I do not see any new release, fix commit, or explanation... This bug is real and still present.

**Comment by dmahugh** [comment]
My mistake, @JSteunou - I saw your last comment and thought it was working, but I've read both threads and understand now. I'll re-open the issue.

@exextoc or @danielgwilson, can you comment on this dialog API issue?

**Comment by markb-trustifi** [comment]
Please check if you have this code in outlook manifest:
```
<AppDomains>
   <AppDomain>https://login.windows.net</AppDomain>
   <AppDomain>https://login.microsoftonline.com</AppDomain>
</AppDomains>
```

**Comment by splinter** [comment]
> Please check if you have this code in outlook manifest:
> 
> ```
> <AppDomains>
>    <AppDomain>https://login.windows.net</AppDomain>
>    <AppDomain>https://login.microsoftonline.com</AppDomain>
> </AppDomains>
> ```

Why do we need to allow the MS login domains?

**Comment by splinter** [comment]
@dmahugh I think we should we mark this as an open bug.

**Comment by markb-trustifi** [comment]
> Why do we need to allow the MS login domains?

I'm using outlook dialogs to login to Microsoft Exchange server. If you intend to login to different target (SAML SSO) you have to add to manifest other urls.

**Comment by splinter** [comment]
@markb-trustifi Got it

However, this does not answer the original question/issue.

**Comment by m-pd** [comment]
I'm seeing this issue too with Outlook for Mac Version 16.16.12 (190715). This is a big problem.

This is the value of **Office.context** in the dialog window:

```
{
  "contentLanguage": "en-US",
  "displayLanguage": "en-US",
  "touchEnabled": false,
  "commerceAllowed": true,
  "host": "Outlook",
  "platform": "Mac",
  "isDialog": true,
  "diagnostics": {
    "host": "Outlook",
    "version": "16.16.715.12",
    "platform": "Mac"
  },
  "license": { "value": "" },
  "ui": {},
  "auth": {},
  "requirements": { "_setMap": { "_sets": { "dialogapi": 1.1 } } },
  "roamingSettings": { "_rawData$p$0": {} }
}

```

**Comment by og1sha** [comment]
I am experiencing same issue, do you have some updates on this?

**Comment by exextoc** [comment]
We are not able to reproduce the issue (Office.context.ui undefined). Could you paste a code snippet that reproduces the issue?

**Comment by tuwrraphael** [comment]
I had a similar problem, and found the problem in my case:

In Outlook Desktop 2016 Windows, I used the `displayDialogAsync` and then in my open dialog box the `Office.context.ui.messageParent` was undefined:
`Object doesn't support property or method 'messageParent'`

I debugged and found out that similar to what @JSteunou described, my `Office.context.isDialog` is `false`.

While debugging deeper into office.js, I found out that it detects whether to be a dialog or not by parsing the `window.location.search` where the `displayDialogAsync` added a `_host_Info` parameter automatically.

Now my problem was that I used angular to create the office add in, let the angular router create the url for the `displayDialogAsync`. The router included all query parameters of the task pane as well, therefore the url of my dialog box contained **two  `_host_Info` parameters**, where only one claimed to be a Dialog, which confused the office.js naturally.

So be sure to have no `_host_Info` query parameter in your url to `displayDialogAsync`!

It works in Outlook Web because there, the original task pane iframe does not contain a  `_host_Info`.

Hope this helps somebody 😅

**Comment by ghost** [comment]
thanks a lot @tuwrraphael ! Definitively, I think you have the good solution.
I had an addon which worked with a Dialog on Outlook Online but I wasn't able to use `messageParent` on the Window Outlook client.
The dialog url was built from `window.href` used in my addon panel. This url contains a `_host_Info`. As soon as I removed this parameter it worked!

**Comment by jasonleehodges** [comment]
> I had a similar problem, and found the problem in my case:
> 
> In Outlook Desktop 2016 Windows, I used the `displayDialogAsync` and then in my open dialog box the `Office.context.ui.messageParent` was undefined: `Object doesn't support property or method 'messageParent'`
> 
> I debugged and found out that similar to what @JSteunou described, my `Office.context.isDialog` is `false`.
> 
> While debugging deeper into office.js, I found out that it detects whether to be a dialog or not by parsing the `window.location.search` where the `displayDialogAsync` added a `_host_Info` parameter automatically.
> 
> Now my problem was that I used angular to create the office add in, let the angular router create the url for the `displayDialogAsync`. The router included all query parameters of the task pane as well, therefore the url of my dialog box contained **two `_host_Info` parameters**, where only one claimed to be a Dialog, which confused the office.js naturally.
> 
> So be sure to have no `_host_Info` query parameter in your url to `displayDialogAsync`!
> 
> It works in Outlook Web because there, the original task pane iframe does not contain a `_host_Info`.
> 
> Hope this helps somebody 😅

Thank you so much for doing this leg work! It really helped me.
