### ISSUE TITLE
Outlook for Windows: Add-in execution takes a long time on ItemSend event of On-Send feature

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#3782]
# Provide required information needed to triage your issue

The add-in sometimes takes a long time to execute after clicking the Send button.
After receiving an inquiry from a customer, we investigated the issue and were able to reproduce it by clicking the Send button after 30 minutes or more had elapsed while the New Email screen was open.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Monthly Enterprise Channel Version 2308 (Build 16731.20316)
* Operating System: Windows 10
* Browser (if using Office on the web): -
 
## Expected behavior

Add-ins take less time to run

## Current behavior

Add-ins take longer than 10 seconds to run

## Steps to reproduce

1. Display the "New Email" screen
2. Click the Send button after 30 minutes or more has elapsed

The code simply opens a dialog.
``` ts
function action(event: Office.AddinCommands.Event) {
  Office.context.ui.displayDialogAsync(
    location.origin + "/taskpane.html",
    { displayInIframe: true, height: 50, width: 80 },
    (result) => {
      dlg = result.value;
      dlg.addEventHandler(Office.EventType.DialogEventReceived, () => {
        dlg.close();
        event.completed({ allowEvent: false });
      });
      dlg.addEventHandler(Office.EventType.DialogMessageReceived, () => {
        dlg.close();
        event.completed({ allowEvent: true });
      });
    }
  );
}
```

https://github.com/OfficeDev/office-js/assets/58804032/f0d2570f-4114-41fd-af9b-09506eee1c4d

In the dialog screen with nothing displayed, _host_info was not added and the right-click menu could not be displayed.

# Provide additional details

After confirming the above reproduction procedure, we found that the issue occurred at the timing of the change from **Get Add-ins** to **All Apps**.
The following table summarizes the issue.

| Channel | Version | Build | Button | Issue |
| ----- | ----- | ----- | ----- | ----- |
| Current | Version 2309 | Build 16827.20130, 16827.20166 | All Apps ![All Apps](https://github.com/OfficeDev/office-js/assets/58804032/62d8008d-2fa1-483e-9603-ed6d51c44e48) | ? |
| Current | Version 2308 | Build 16731.20170, 16731.20234 | All Apps | Affected |
| Current | Version 2307 | Build 16626.20132, 16626.20134, 16626.20170 | All Apps | Affected |
| Current | Version 2306 | Build 16529.20182 | Get Add-Ins ![Get Add-Ins](https://github.com/OfficeDev/office-js/assets/58804032/c3a5dc79-c61e-4ce3-9102-9686927a19cf) | - |
| Monthly Enterprise | Version 2308 | Build 16731.20316 | All Apps | Affected |
| Monthly Enterprise | Version 2307 | Build 16626.20208, 16626.20222 | Get Add-Ins | - |

## Context

Our research has not been able to reproduce this issue with Version 2309, but we have received inquiries from customers that they are also experiencing this issue with Version 2309 (Build 16827.20166).

Is the Microsoft team aware of this issue and has it already been addressed?

If it has been addressed, what steps can be taken to help customers who are still affected?
Also, what steps can be taken to help investigate the cause of this issue?

Since the icon was changed to All Apps, we have received a number of inquiries regarding the slow execution of add-ins and the sending of emails without the `ItemSend` event being executed.
While we are still unable to reproduce the event of emails being sent without the `ItemSend` event being executed, we can reproduce the event of add-ins being executed slowly, so we would appreciate your immediate attention to this issue.

**Comment by neville-jones** [comment]
This seems slightly similar to an issue one of our customers is reporting with our Outlook add-in which uses the `ItemSend` event to show a dialog. 

We are yet to reproduce the issue like you have here, but for some of their users the dialog can take a very significant time to render. The problem seems to have coincided with the release of the WebView2 runtime version 118.0.2088.46 - https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#10208841

The users that are affected do have multiple monitors and yesterday we found that making sure each monitor was set to 100% scaling fixed the issue. The WebView2 update did have some changes related to DPI scaling.

I just wanted to mention our findings in case it is related to the issue you have observed. It may be worth looking into the WebView2 runtime on each of your test platforms. 

Our users have Outlook on Windows version 2308 build 16.0.16731.20310 64-bit and now WebView2 runtime 118.0.2088.61

**Comment by t-ariyoshi30907** [comment]
@exextoc @neville-jones
The same issue is occurring in my environment as well.
It's happening on the same platform as @clavx , and the reproduction steps are also identical.
This problem is significantly affecting the users' work.Please investigate and fix it as soon as possible.

**Comment by clavx** [comment]
@neville-jones , thanks for sharing the information.

I'm testing in a virtual environment. Due to the remote connection to that environment, scaling and layout could not be changed.

I tried to reproduce the issue with WebView2 117.0.2045.60. As a result, I was able to reproduce the issue, so I think there is some other issue.
I also tried the latest version of Outlook that had been released. As a result, I could not reproduce this issue as well as Version 2309.

The version of WebView2 was 118.0.2088.46 when summarized in the previous table.
The following table summarizes the additional confirmation.

|WebView2 version|Outlook version|Issue|
|-----|-----|-----|
|118.0.2088.61|Current Channel Version 2310 (Build 16924.20106)|-|
|118.0.2088.61|Monthly Enterprise Channel Version 2308 (Build 16731.20316)|Affected|
|117.0.2045.60|Monthly Enterprise Channel Version 2308 (Build 16731.20316)|Affected|

If I could understand what is happening from the Outlook log, the investigation would become much easier...

**Comment by ioxFR** [comment]
Hello,

Got same issues on MSO versions, continue to work on outlook on web and new outlook in my side.
Users on windows 10 & 11 affected.
I already opened a Microsoft support ticket for that, keep you updated if i get more informations

Thanks

**Comment by ioxFR** [comment]
Hello,

Got same issues on MSO versions, continue to work on outlook on web and new outlook in my side.
Users on windows 10 & 11 affected.
I already openned

**Comment by t-ariyoshi30907** [comment]
@exextoc (@ioxFR )

Both my customers and I are currently using Outlook on the web temporarily because this issue is occurring with the old Outlook. However, I need to explain to my customers why this problem is happening and when it will be resolved. Could you please provide the latest information regarding this issue?

**Comment by t-ariyoshi30907** [comment]
@exextoc 
Following the report from @clavx , I also conducted testing on the current channel of Microsoft 365 (2309: build 16.0.16827.20166). As a result, I was unable to reproduce this issue. Based on this outcome, it appears that the problem occurring in the version 2308 environment may have been resolved through the update.

I cannot make a definitive judgment on whether this hypothesis is correct or not, and I cannot guide the customer without further information. Can you provide any insights?

**Comment by neville-jones** [comment]
My customer's issue was probably not due to WebView2 either - despite adjusting scaling to 100% for all monitors on one workstation rectified the issue for that user, it did not help others. 

One user tested updating from Monthly Enterprise Channel version 2308 to Current Channel version 2310 Build 16924.20124 and now reports no delays with the showing a rendered dialog at the ItemSend event.

**Comment by t-ariyoshi30907** [comment]
@neville-jones 
Thank you for providing the information.
@clavx @ioxFR 
Based on everyone's and my research, I believe that the issue can be resolved through a program update without any doubt. Have there been any instances of the issue recurring after switching to versions 2309 or 2310?

**Comment by neville-jones** [comment]
My customer has confirmed that the update to version 2309 in Monthly Enterprise Channel has rectified the issue for their users.

**Comment by clavx** [comment]
I have also confirmed that the issue has been resolved at version 2309 in our test environment.

- Monthly Enterprise Channel
  - Version 2309 (Build 16827.20278): resolved
  - Version 2308 (Build 16731.20398): still affected

Any information you can provide to help us explain this issue to our users would be appreciated.
