### ISSUE TITLE
Error Occurs in Word.Style.set(paragraphFormat) When lineSpacing is Set to 0

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#3787]
An exception is thrown: InvalidArgument: ParagraphFormat.lineSpacing ...

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: (Version 2302 Build 16.0.16130.20806) 64-bit 
* Operating System: Windows 
* Browser (if using Office on the web): ______
 
## Expected behavior
- Provide more context how to update these properties

## Current behavior
- lineSpacing has a type of number, like other properties, but an exception is thrown when setting value is 0,  other properties do not throw this exception.
## Link to live example(s)
https://gist.github.com/jasonhieu1905/a8b4c9d9cc594d87c076e6a9f6b86853

## Context
-The user can set any value for these properties when using Word. We are not sure about updating these properties when using the API.

## Useful logs
Successfully the paragraph format of the 'Normal' style.

[ERROR]: Error:
{
    "stack": "RichApi.Error: InvalidArgument\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:265984)\n    at i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:330430)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:328493",
    "message": "InvalidArgument",
    "name": "RichApi.Error",
    "code": "InvalidArgument",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "InvalidArgument",
        "message": "InvalidArgument",
        "errorLocation": "ParagraphFormat.lineSpacing",
        "statement": "paragraphFormat.lineSpacing = ...;",
        "surroundingStatements": [
            "var v = context.root._getObjectByReferenceId(\"027!00000541\");",
            "var paragraphFormat = v.paragraphFormat;",
            "// Instantiate {paragraphFormat}",
            "// >>>>>",
            "paragraphFormat.lineSpacing = ...;",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 400
}

**Comment by Searion** [comment]
@jasonhieu1905 Thanks for reporting. This behavior is same as UI. Paragraph line spacing cannot be 0. 
![image](https://github.com/OfficeDev/office-js/assets/33591311/8e41b3f6-ebf0-4416-8faf-7eac05327415)

**Comment by jasonhieu1905** [comment]
@Searion : this is the value I'm getting from this API: https://learn.microsoft.com/en-us/javascript/api/word/word.application?view=word-js-preview#word-word-application-retrievestylesfrombase64-member(1)

![image](https://github.com/OfficeDev/office-js/assets/13063615/0a95a43e-786c-48b7-9b22-62ddcdc7435b)

**Comment by yilin4** [comment]
@jasonhieu1905 ParagraphFormat.lineSpacing api corresponds to UI lineSpacing's exactly setter. It doesn't have the full functionality of UI lineSpacing setter. You can have a try with UI lineSpacing's exactly setter to see its value limitation. Thank you.

**Comment by barisbikmaz** [comment]
@yilin4 assume you have a style with paragraph linespacing 1. Now I want to reset the linespacing of this style with the style API. How can I do this?

**Comment by yilin4** [comment]
@barisbikmaz Do you mean to reset the style' linespacing to single? Because the single line spacing equals to exactly 12, you can set the value to 12.

**Comment by barisbikmaz** [comment]
Maybe to understand the use case. We have a word document which defines some styles (Assume a corporate styles document). We download this document and want to apply its styles to the current document. The style API returns a style named "Title" with linespacing: 0.
When the current document already has the same style we want to override its properties. So the current document has also a style called "Title" but with a linespacing = 20.  I can't apply linespacing 0. So what should I do?

**Comment by yilin4** [comment]
@barisbikmaz I have understood what you said. This should be a bug.  It has been put on our backlog<Bug#8486440> for internal track. We will keep track of this issue and let you know if there are any updates.
