### ISSUE TITLE
Office.context.mailbox.item.loadCustomPropertiesAsync returning empty response on Window Outlook Native

### ISSUE THREAD

**Issue by BalveerEptura** [OfficeDev/office-js#3789]
->Create recurring meeting and save custom properties through addin (Office.context.mailbox.item.saveAsync())
->Open existing recurring meeting as single instance Update time of meeting and save the meeting. 
->Again open same instance as single instance 
->Open addin ,Now run the below code in console to fetch Custom Properties: Office.context.mailbox.item.loadCustomPropertiesAsync(function (asyncResCusProp) { console.log(asyncResCusProp.value);}); Response : empty response

![image](https://github.com/OfficeDev/office-js/assets/138432042/a0c738b9-fc67-411e-b797-2d13aead1987)

Note: if you open same meeting instance in owa(browser), Custom Properties is being fetched properly

**Comment by exextoc** [comment]
@BalveerEptura Please follow the template while creating Github issue, it helps identify correct platform. Are you seeing this issue in Windows desktop client or New Outlook in Windows? Share the client version as well.

**Comment by BalveerEptura** [comment]
@exextoc , we are using  Windows desktop client(old outlook) version : Microsoft® Outlook® for Microsoft 365 MSO (Version 2308 Build 16.0.16731.20310) 64-bit

**Comment by ndeleuze** [comment]
This is a known limitation, but the following workaround exists:
- After the exception is created, get a webhook with the series ID of the parent series.
- Retrieve the custom properties using the series ID.
- Set the properties on the exception item.
