### ISSUE TITLE
Event-based plugin do not load to localdata folder

### ISSUE THREAD

**Issue by ttuyen1529** [OfficeDev/office-js#3796]
Is there any specific for deployment event-based add-in with send mode is Prompt?
I see in our testing environment the bundle file is not load to localData folder on Outlook for Windows
New Outlook and OWA is working fine

**Comment by ttuyen1529** [comment]
Any news or action on this?

**Comment by ndeleuze** [comment]
@ttuyen1529 just to clarify, which bundle file are you referring to?

**Comment by ttuyen1529** [comment]
> @ttuyen1529 just to clarify, which bundle file are you referring to?

I assume that we all know when Outlook load event-based add-in to local machine, it renamed to bundle.js file. That is the file that I mentioned @ndeleuze

**Comment by ndeleuze** [comment]
@ttuyen1529 would you be able to provide your manifest?
