### ISSUE TITLE
Critical: Event-based add-ins not starting in Outlook Desktop

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js#3797]
## Provide required information needed to triage your issue
Automatic events are not working on Outlook Desktop for Windows (old/classic one). `OnMessageCompose` and `onMessageRecipientsChanged` are not triggered. 

Also, the task pane is loading very slowly(~1 minute), with no errors or requests failing (traced with fiddler).

The issues were first reported yesterday 16:00 UTC and got critical this morning (UTC). The issue is seen on both the Standard release and Targeted release channels.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: ___PC Desktop___
* Host [Excel, Word, PowerPoint, etc.]: ___Outlook___
* Office version number: ___Verified in versions from Version 2302 Build 16.0.16130.20684 to Version 2310 Build 16.0.16924.20054___
* Operating System: ___Windows___

Logs:
```
31-Oct-23 11:03:56	Verbose	Runtime	[Console] [Log] MailboxHostExecuteApi invoked!		
31-Oct-23 11:03:56	Verbose	Runtime	[Console] [Log] MailboxHostExecuteApi invoked!		
31-Oct-23 11:03:56	Verbose	Runtime	[Console] [Log] MailboxHostExecuteApi invoked!		
31-Oct-23 11:04:02	Verbose	Runtime	[Console] [Log] Platform Bundle - Office exists!		
31-Oct-23 11:04:02	Verbose	Runtime	[Console] [Log] Platform Bundle - Office.actions exists!		
31-Oct-23 11:04:02	Verbose	Runtime	[Console] [Log] Platform Bundle - Office.actions.associate exists!		
31-Oct-23 11:04:02	Verbose	Runtime	[Console] [Log] Outlook Batch JS loaded!		
31-Oct-23 11:04:02	Verbose	Runtime	[Console] [Log] Outlook LaunchEvent JS loaded!		
```

In the event viewer, ~2 minutes after a new message is created, the following error can be seen:
```
We're sorry, we couldn't access [Add-in name]. Make sure you have a network connection. If the problem continues, please try again later. 
Add-In ID : [Add-in ID] 
Error code : 2147943860
```

## Steps to reproduce
Can be reproduced with the basic
```
console.log('[Internal]: Start initialization');
void Office.onReady(() => { });
Office.actions.associate('onMessageCompose', (event) => console.log(event.source.id));
Office.actions.associate('onMessageRecipientsChanged', (event) => console.log(event.source.id));
```

**Comment by bogdanst24** [comment]
@exextoc please have a look

**Comment by MarvinPogoda** [comment]
Hey @bogdanst24,
we are experiencing this issue,too. 

Did you find a solution for your problem?

**Comment by bogdanst24** [comment]
It was related to an imported method not supported by ecmascript 2016. And the tests with the basic functions were not valid because of caching
