### ISSUE TITLE
Excel add-in Custom Functions failing to register on one single PC

### ISSUE THREAD

**Issue by DarranShepherd** [OfficeDev/office-js#3798]
We have an internal Excel add-in that we have developed that comprises of a task pane and a couple of custom functions, deployed as an admin managed add-in through Office365. It works on all machines throughout the organisation except for one. 

On this one machine, the task pane appears to run successfully, but the custom function shows `#NAME?` in the cell. The status bar of Excel shows "Error installing functions".

The Office Runtime Log shows this data. I cannot find any reference to failure of the add in installation with further debugging suggestions.
```
10/23/2023 15:22:51	Medium	Web Add-In Runtime Logging Session Started			
10/23/2023 15:22:51	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin]		
10/23/2023 15:22:51	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
10/23/2023 15:22:51	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=BankBI.SELECTION		
10/23/2023 15:22:51	Verbose	CustomFunctions	[Metadata] [Parsing] [Begin] Function		
10/23/2023 15:22:51	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success] Function=BankBI.REPORTDATE		
10/23/2023 15:22:51	Medium	CustomFunctions	[Metadata] [Parsing] [End] [Success]		
10/23/2023 15:22:51	Verbose	CustomFunctions	[Installation] [Addin] [Begin] Solution=1d66bcee-2492-4935-b7c4-2a8da0618a10, Version=1.1.0.0		
10/23/2023 15:22:51	Unexpected	CustomFunctions	[Installation] [Addin] [End] [Failure] Solution=1d66bcee-2492-4935-b7c4-2a8da0618a10, Version=1.1.0.0	
```

This persists after multiple attempts to clear the Office cache, Ctrl-F5 refresh, attached debugger > clear cache, log out and back in to Office365 account.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2310 (Build 16924.20106 Click-to-Run)
* Operating System: Windows 11 Pro 22H2
* Browser (if using Office on the web): N/A
 
## Expected behavior
Custom functions should execute. They do on all other computers.

## Current behavior
"Error installing functions" message and `#NAME?` in cells using one of the custom functions.

**Comment by demyte** [comment]
We are having this exact same issue on one single PC.

![image](https://github.com/OfficeDev/office-js/assets/48166/0e9117f0-515d-4920-906c-8c2c2eed2268)

@penglongzhaochina Is there any more detailed logging we can get as to what has caused the `Unexpected` error.

The addin is deployed, in this instance, as an Admin Managed addin from the users M365 tenant and other users in that tenant are using the addin with no issues.

The following has been attempted (and failed):
- We have gone through the "Next time office starts, clear all previously-started web add-ins cache" dance many times.
- We have removed it from the registry under `HKCU:\Software\Microsoft\Office\16.0\WEF\TrustedCatalogs\{<guid>}` and reloaded Excel
- IT has removed the user from the addin and waited for it to uninstall from their Excel and then added it back in a bit later
- IT has re-installed Office.

Please let us know how to futher diagnose or solve this issue.

**Comment by rundongmsft** [comment]
Hi @DarranShepherd and @demyte, this is a known issue, we have an internal bug item 8549174 to track this. We will inform you when any updates, thanks.

**Comment by demyte** [comment]
@rundongmsft Can I please ask for more infomration on this and a workaround etc..

I have a very frustrated customer who needs more than "Microsoft knows about it and will tell us when there is any update"

Surely there is some way to resolve this for one user of our addin?

**Comment by eqinox76** [comment]
Migth be the same issue as #3843. Maybe the same workaround works for you.

**Comment by demyte** [comment]
@eqinox76 Many thanks for linking that - we will try it out.

**Comment by demyte** [comment]
@eqinox76 that worked for us in this case - thanks so much for pointing me in that direction! 👍

**Comment by penglongzhaochina** [comment]
Hi all, We have fixed this issue, could you please verify this issue? Remember to clear the wef cache before you try it.

**Comment by DarranShepherd** [comment]
@penglongzhaochina  Verified. Many thanks for fixing and letting us know. We have a very happy colleague now.
