### ISSUE TITLE
Need worksheet codename that persists across sessions

### ISSUE THREAD

**Issue by FastExcel** [OfficeDev/office-js#38]
Why don't we have a read-only worksheet codename that persists across sessions (like VBA)? The VBA codename is unique within a workbook and a workbook is unique within a session. 
Without this JS code is vulnerable to the user changing worksheet name, and the ID property is only valid within a session so is not very useful.
In fact it would be even better to actually use the VBA Codename - it must be stored in the file structure somewhere - then it would make migrating VBA stuff to JS easier.

**Comment by MarcinusX** [comment]
@FastExcel Did you manage to workaround missing codename in office-js?

**Comment by FastExcel** [comment]
I don’t think the API supports this yet?

**Comment by MarcinusX** [comment]
From what I know, it doesn't.

**Comment by ElizabethSamuel-MSFT** [comment]
@tutieu, @lumine2008: Does the API now support this feature? Thanks.

**Comment by keyur32** [comment]
Hey @FastExcel , this is a bit of an older issue, but I don't think this is currently planned yet. For feature requests, please log a request on our  uservoice site so others can upvote and we can prioritize this properly here: https://officespdev.uservoice.com. 

Thanks.
