### ISSUE TITLE
Excel is taking long time to load while opening it using office js. 

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#3803]
My Environment
Platform : PC desktop
Host: Excel
Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2309 Build 16.0.16827.20166) 64-bit
Operating System: Windows 10 pro

Hi team I am opening excel using office js. Excel is opening using bytes and it's take long time to load in excel.
I am attaching file for that can you please provide some information why it's happening.

Excel is loaded succefully but it takeing 10-15 min for this document. and await context.sync(); taking that time and sometime excel also goes in not responding state.

    var options = {
                sheetNamesToInsert: [], // Insert all the worksheets from the source workbook.
                positionType: Excel.WorksheetPositionType.end
            };
            // Insert the new worksheets into the current workbook.
            workbook.insertWorksheetsFromBase64(replaceexcelconfirmdialog.Base64Data, options);  //replaceexcelconfirmdialog.Base64Data in that I get my file bytes
            context.load(workbook.worksheets);
            await context.sync();

[https://irisindiacloud-my.sharepoint.com/:x:/r/personal/jayshiv_patel_irisbusiness_com/Documents/SharedFile/[TestingLatest.xlsx](https://irisindiacloud-my.sharepoint.com/:x:/r/personal/jayshiv_patel_irisbusiness_com/Documents/SharedFile/TestingLatest.xlsx?d=w286480440ac74a7084c95d72d78cd1dc&csf=1&web=1&e=X8pJjk)?d=w286480440ac74a7084c95d72d78cd1dc&csf=1&web=1&e=X8pJjk](url)

**Comment by shermaro91** [comment]
@penglongzhaochina  Any update on this?

**Comment by penglongzhaochina** [comment]
Could you please give us the full base64 path so that we can reproduce your issue?

**Comment by Jayshiv-IRIS** [comment]
Hii @penglongzhaochina, 
I Already attached Link for that file.
Please provide me your Email Id so I can share document on that
Thanks.

**Comment by penglongzhaochina** [comment]
Sorry, I can't open this link from my side, it looks like a personal link. And I also want to ask that how big your file? Thanks!

**Comment by Jayshiv-IRIS** [comment]
@penglongzhaochina Thanks.
That's reason I ask for your Email Id and my file size  is just  5858 KB(5.8 MB).
Here is my file
[TestingLatest.xlsx](https://github.com/OfficeDev/office-js/files/13292762/TestingLatest.xlsx)

**Comment by Jayshiv-IRIS** [comment]
Hi @penglongzhaochina  is there any updates on this I already Shared document and it's effecting our work .

**Comment by penglongzhaochina** [comment]
Thanks, @Jayshiv1408Dev , could you give me your impact of this issue? like how many customers have been affected? What's the number of your add-in MAUP? This helps us prioritize our work. We will let you know once we have some progress.

**Comment by Jayshiv-IRIS** [comment]
Thanks, @penglongzhaochina ,
More than 5000+ customer  are affecting because of this.
[Addin](https://appsource.microsoft.com/en-us/product/office/WA200005496?tab=Overview)
This is our add-ins.

**Comment by penglongzhaochina** [comment]
When I copy the base64 of your file to the scriptlab, it will throw error like this,
<img width="333" alt="image" src="https://github.com/OfficeDev/office-js/assets/106959323/fe1a1a36-d272-4179-9d55-495b12f0d062">

**Comment by penglongzhaochina** [comment]
hi @Jayshiv1408Dev  
this is because there are too many sheets in the workbook, in total 103 and the sheets needs to be inserted 1 by 1, so it's time consuming,Thanks!

**Comment by Jayshiv-IRIS** [comment]
Hi @penglongzhaochina
Thanks for your response.
I uploaded one workbook which have 150 sheets and it's take less than 1 min to load.
In between I found that workbook which taking a time to load have larger amount of Named Range(custom).So there is a chance because of that it taking time to load.
 
[150tab.xlsx](https://github.com/OfficeDev/office-js/files/13483796/150tab.xlsx)

**Comment by penglongzhaochina** [comment]
Yes, I think you are right. We also make some experiments. In your workbook, it takes a little bit long time to load when I just insert the sheet named "J2". It been inserted soon when I copied the "J2" content to another empty workbook. I wish that this can help you. Thanks.

**Comment by Jayshiv-IRIS** [comment]
Sorry . But I didn't get it.
Can you please elaborate.
How can it improve loading time.

**Comment by penglongzhaochina** [comment]
It take short time to load when I copied the content to a new empty workbook, which means your workbook includes a lot of extra things besides real content from cell.
