### ISSUE TITLE
Outlook - Add-in Pane in Shared Mailbox shows "Loading..." message after add-in is loaded/rendered

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#3804]
The add-in pane shows "Loading..." even after the add-in has been rendered/loaded into the Pane. This appears to only be happening in **Shared Mailboxes** on Windows Desktop.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2310 Build 16.0.16924.20054 (64-bit)
* Operating System: Windows 
* Browser (if using Office on the web): N/A
 
## Expected behavior
The "Loading..." message is removed after the add-in has been loaded/rendered.

## Current behavior
The "Loading..." message is never removed from the pane.

## Steps to reproduce
1. On Windows Desktop in the Outlook Client, open a Read Message Add-in Pane
2. See the "Loading..." (blue) text
3. The add-in will load completely and render. Yet you will still see the "Loading..." message overlayed on top of it (see screenshots)

## Link to live example(s)
![image](https://github.com/OfficeDev/office-js/assets/7740624/be216588-7e9a-447d-b6a3-3eaee5bcccf4)
![image](https://github.com/OfficeDev/office-js/assets/7740624/314c458d-eaa4-4890-8e80-48360a7d1481)

**Comment by laurence-splendr** [comment]
Just started having the same issue with our Add-In. Never happened before - any luck with this @cody-lettau?

**Comment by ndeleuze** [comment]
@cody-lettau what exactly triggers the "Loading..." text for your Add-in? I am trying to reproduce this for shared mailboxes but want to make sure I'm reproducing this issue in the same way. Thank you.

**Comment by Ch-Webb-Cegedim** [comment]
@cody-lettau Was a solution for this issue ever found? We're having the same issue with our own Office Add-in.

**Comment by Ch-Webb-Cegedim** [comment]
To anyone else stuck on this - this appears to have been a dev-only issue. Once we moved our add-in into a production environment, the loading spinner disappeared.
