### ISSUE TITLE
Outlook Web Addin certificate issue while building artifacts in docker image for the Outlook WebAddIn React UI application. (Containerization)  

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#3806]
We have used “npx office-addin-dev-certs install --machine” in MS-hosted agent and able to build artifacts on Windows-latest and Ubuntu-latest agents.

Our goal is building a docker image for the WebAddIn React UI application. (Containerization)  
We have configured a pipeline that has a Build Docker Image task, where we are performing the NPM tasks to build the artifact. There, we have tried command “npx office-addin-dev-certs install --machine” to install the certificates but it is failing as it is not supporting while building the image . 
refer below image for more information 

![image](https://github.com/OfficeDev/office-js/assets/142812553/2a133fac-9ae1-4127-accf-95e493b4f79b)

Also, we have tried skipping the step to install the certificates but as a final step to start the application and Docker container, we need to trigger “npm start” command that again looks for the certificate to install. We need to keep this command to start the docker container as soon as it gets deployed onto the Kubernetes cluster. 

refer below image for more information 

![image](https://github.com/OfficeDev/office-js/assets/142812553/0a6e9489-bbc2-4dea-aa52-31d77640759b)

**Comment by soumyamondal-accenture** [comment]
@exotec can you please check the code provide by @geetamshukla  and provide suggestions.

**Comment by soumyamondal-accenture** [comment]
can you please provide the status of the item.

**Comment by exextoc** [comment]
This issue regarding failure in package office-addin-dev-certs from https://github.com/OfficeDev/Office-Addin-Scripts. Please create issue in the same repo. Un-tagging from Outlook.

**Comment by amolkhanorkar** [comment]
> This issue regarding failure in package office-addin-dev-certs from https://github.com/OfficeDev/Office-Addin-Scripts. Please create issue in the same repo. Un-tagging from Outlook.

@exextoc  - We have opened the another issue here, https://github.com/OfficeDev/office-js/issues/3810 . Please check and provide us the status.

thanks :)
