### ISSUE TITLE
getActiveCell returns InvalidArgument

### ISSUE THREAD

**Issue by mjrforce** [OfficeDev/office-js#381]
Running the[ sample code](https://docs.microsoft.com/en-us/javascript/api/excel/excel.workbook?view=office-js#getactivecell--) produces the following error:

InvalidArgument: The argument is invalid or missing or has an incorrect format.

## Expected Behavior
The selected cell should be returned

## Steps to Reproduce, or Live Example
name: Basic API call (TypeScript)
description: Performs a basic Excel API call using TypeScript.
host: EXCEL
api_set: {}
script:
  content: |
    $("#run").click(() => tryCatch(run));

    async function run() {
      await Excel.run(async (context) => {

        let myWorkbook = context.workbook;
        let activeCell = myWorkbook.getActiveCell();
        activeCell.load("address");

        await context.sync();

        console.log("The active cell is " + activeCell.address);
      });
    }

    /** Default helper for invoking an action and handling errors. */
    async function tryCatch(callback) {
      try {
        await callback();
      } catch (error) {
        OfficeHelpers.UI.notify(error);
        OfficeHelpers.Utilities.log(error);
      }
    }
  language: typescript
template:
  content: |-
    <section class="ms-font-m">
        <p class="ms-font-m">This sample demonstrates basic Excel API calls.</p>
    </section>

    <section class="samples ms-font-m">
        <h3>Try it out</h3>
        <p class="ms-font-m">Select some cells in the worksheet, then press <b>Highlight selected range</b>.</p>
        <button id="run" class="ms-Button">
            <span class="ms-Button-label">Highlight selected range</span>
        </button>
    </section>
  language: html
style:
  content: |-
    section.samples {
        margin-top: 20px;
    }

    section.samples .ms-Button, section.setup .ms-Button {
        display: block;
        margin-bottom: 5px;
        margin-left: 20px;
        min-width: 80px;
    }
  language: css
libraries: |
  https://appsforoffice.microsoft.com/lib/1/hosted/office.js
  @types/office-js

  office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
  office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

  core-js@2.4.1/client/core.min.js
  @types/core-js

  @microsoft/office-js-helpers@0.7.4/dist/office.helpers.min.js
  @microsoft/office-js-helpers@0.7.4/dist/office.helpers.d.ts

  jquery@3.1.1
  @types/jquery@3.3.1

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 
* Operating System: Windows 10
* Browser (if using Office Online): n/a

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

 {
    "code": "InvalidArgument",
    "message": "The argument is invalid or missing or has an incorrect format.",
    "errorLocation": ""
}

**Comment by weshi** [comment]
I cannot reproduce this issue. What version/build of Excel are you using when you see this issue?

**Comment by lumine2008** [comment]
Hello @mjrforce,  it would be helpful if you could share us more information to repro this issue.
