### ISSUE TITLE
Even after uninstalling the Outlook Web add-in via "uninstalling the web add-in" through sideloading, the web add-in continues to appear in the thick client (old Outlook).

### ISSUE THREAD

**Issue by SubhashRoy044** [OfficeDev/office-js#3811]
# Provide required information needed to triage your issue
Even after uninstalling the Outlook Web add-in via "uninstalling the web add-in" through sideloading, the web add-in continues to appear in the thick client (old Outlook).

Details about office web Add-in :- My office Add-in is based on email send event we are opeing dialog to do few activites before sending mail.

## Your Environment

* Platform [PC desktop and Office on the web]: PC desktop 
* Office version number: Version 2308 and build 16731.2 
* Operating System: Window 11
* Browser (if using Office on the web): it is removing 
  
## Expected behavior

1. When we remove the office Web Add-In it should remove from outlook Desktop as well.
## Current behavior
When we remove the office Web Add-In it is not remove from outlook Desktop as well.

## Steps to reproduce

1. When we remove the Web Add-in via sideload.
3. Go to Outlook in browser  and open the new mail and send button then Web Add-in dialog is not appears.It is removed from the Browser (using Office on the web)
4. Go to Outlook thick client (outlook desktop) and open the new mail and send button then Web Add-in dialog appears, however Web add-in is already removed .

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

This issue is impacting the testing and development of office web add-in since it is not remove .
Users is getting Web add-In after it is removed from outlook .

Is there a way to completely remove the add-in from Outlook Desktop once it has been uninstalled via sideloading? 
What steps are required for users to remove the Outlook add-in? 
Is this the expected behavior? Is there time duration it will remove.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by millerds** [comment]
What is the process you are using to remove the add-in?
When opening Outlook do use see as "Add-ins" button or an "All Apps" button in the ribbon?

**Comment by SubhashRoy044** [comment]
Bug Title: Web Add-in persists in Outlook Desktop after removal via sideload.

Bug Description: After removing the Web Add-in via sideload, the add-in still appears in the Outlook desktop client when opening a new mail and clicking the send button. However, the removal is successful in Outlook Web.

Steps to Reproduce:

Sideload Web Add-in:
a. Open Outlook desktop.
b. Sideload the Web Add-in manifest manually.
c. Verify that the add-in is successfully loaded in Outlook desktop.

Remove Web Add-in:
a. Remove the add-in manifest from sideload using sideload manully.
b. Confirm the removal by checking the sideloaded add-ins.

Open New Mail in Outlook Desktop:
a. Create a new email in Outlook desktop.
b. Click on the send button.

Unexpected Add-in Appearance:
a. Note the appearance of the Web Add-in dialog/model with a URL.
b. Confirm that the removed add-in is still reflected in the Outlook desktop client.

Verify Removal in Outlook Web:
a. Open Outlook Web.
b. Confirm that the Web Add-in is successfully removed and not visible in the Outlook Web client.

Expected Result:
The Web Add-in should be completely removed from both Outlook desktop and Outlook Web after following the removal steps via sideload.

Actual Result:
The Web Add-in persists in the Outlook desktop client, even after successful removal via sideload. The removal is successful in Outlook Web.

**Comment by SubhashRoy044** [comment]
**Process to Remove the Add-in:**

I am using the Outlook desktop client, the removal process typically involves going to the "Add-ins" or "Apps" section within Outlook settings.
Navigate to the "Manage Add-ins" or a similar option.
Find the installed add-in in the list and select the option to remove or uninstall it.


**Outlook Ribbon:**

When opening Outlook do use see as "Add-ins" button or an "All Apps" button in the ribbon? Yes

**Comment by millerds** [comment]
Which button do you see . . . "Add-ins" or "All Apps"?  
If you were to wait for a few hours and restart Outlook is the add-in still there?

**Comment by SubhashRoy044** [comment]
Which button do you see . . . "Add-ins" or "All Apps"? --- **We see button/icon for office  Web Add-in Ribbon of outlook desktop ..**
If you were to wait for a few hours and restart Outlook is the add-in still there? **Yes, after wait few hours  it is not getting removed . Also after restart outlook add-in is not removed .**

**Comment by millerds** [comment]
I'm still not sure which of these two buttons you are seeing (thing behave a little differently depending on which one is currently active):
![AddinsButton](https://github.com/OfficeDev/office-js/assets/10135066/3ffe3c2d-548c-4d91-b892-c8609173f49f)
![AllAppsButton](https://github.com/OfficeDev/office-js/assets/10135066/c84311a1-2e56-4c70-8aa2-1e2e1ef9cbb2)

**Comment by SubhashRoy044** [comment]
Here ,
<img width="91" alt="image" src="https://github.com/OfficeDev/office-js/assets/150111732/825a16e1-e07d-4d3e-94af-88a26cc94d19">
"Get Add-in" button we are using . The first option in shared image .

**Comment by millerds** [comment]
Can you update you version of Outlook to a current build and try it again.

There have been some changes to the way sideloading works and we are working through some of the issues.  You should be getting the second button and there wouldn't be a sideloading option from there.  When you see that new button you can go to aka.ms/olksideload in order to sideload or you have to use some of our developer tools for sideloading (which are currently more consistent).

**Comment by millerds** [comment]
There have been some improvement in the service that manages these.  Please open a new issue if you have more problems.
