### ISSUE TITLE
The changes(UI+features) made to the Outlook Web add-in via sideloading ("installing the web add-in") are not reflected in Outlook Desktop (both old and new versions)

### ISSUE THREAD

**Issue by SubhashRoy044** [OfficeDev/office-js#3812]
# Provide required information needed to triage your issue

## Description
The changes(UI+features)  made to the Outlook Web add-in via sideloading ("installing the web add-in") are not reflected in Outlook Desktop (both old and new versions). There is descrepency in UI and features  .

## Details about Office Web Add-in
My office Add-in is based on the email send event. We open a dialog to perform a few activities before sending an email.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop - Outlook Desktop (both old and new versions)
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: Version 2308 and build 16731.2
* Operating System: Window 11
* Browser (if using Office on the web): Yes
 
## Expected behavior

When we made changes (UI+features)  the office Web Add-In and deploy via sideload it should reflect the latest chnages in outlook (both old and new versions).

 All the latest (UI+features)  are reflecteing in outlook web but not in outlook desktop (both old and new versions).

## Current behavior

The changes (UI+features)  the office Web Add-In is not reflecting the latest changes in outlook (both old and new versions).

## Steps to reproduce

1. Add the Web Add-in via sideload with latest changes (UI+features).
2. Go to Outlook in browser(outlook Web) and open outlook new mail and send button then Web Add-in dialog is appears and latest changes (UI+features)  are reflecteing .
3. Go to Outlook thick client (both old and new versions) and open outlook new mail and send button then Web Add-in dialog appears and (UI+features)  are not reflecteing .

Note :- All the latest (UI+features)  are reflecteing in outlook web but not in outlook desktop (both old and new versions).

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@SubhashRoy044 Can you give a small sample and steps that we can use to reproduce this issue?
Are you seeing the problem both in outlook old client and new Outlook? Can you share the outlook version where it's not working.

**Comment by SubhashRoy044** [comment]
### Steps to Deploy and Verify UI Changes in Outlook Add-in:

#### Step 1:
- Add UI changes such as "Add one button test" in the Modal Pops triggered by the email send event.

#### Step 2:
- Deploy the code changes to the hosted DNS maintained in the manifest.

#### Step 3:
- Navigate to [Myemail.accenture.com](https://Myemail.accenture.com).
- Go to My Addin -> Add Manifest.

#### Step 4:
- Open Myemail.
- Draft a new email.
- Click on the send button.
- A modal dialog will open.
- Verify that the "button test" is visible, reflecting the deployed UI changes.

#### Step 5:
- Open Outlook Desktop.
- Draft a new email.
- Click on the send button.
- A modal dialog will open.
- Confirm that the "button test" is not visible, indicating that the new UI changes are not reflecting.

#### Step 6:
- Open Outlook Desktop (New version by enabling the toggle button).
- Draft a new email.
- Click on the send button.
- A modal dialog will open.
- Ensure that the "button test" is not visible, indicating that the new UI changes are not reflecting in the new version.

**Comment by exextoc** [comment]
We are not able to repro the issue at our end. Can you please share a repro video with us to understand the issue better.

**Comment by SubhashRoy044** [comment]
I have added vedio for OWA , outlook desktop old version and outlook desktop new version (try new outlook).
All three places UI is not consistence .
[ui not reflecting in new outlook.zip](https://github.com/OfficeDev/office-js/files/13391843/ui.not.reflecting.in.new.outlook.zip)

**Comment by exextoc** [comment]
Hi @SubhashRoy044 , Is this admin installed add-in or installed by users directly? Are you in PPE environment?

**Comment by SubhashRoy044** [comment]
> Hi @SubhashRoy044 , Is this admin installed add-in or installed by users directly? Are you in PPE environment?

It is installed by user directly .Yes, i am in stage enviroment .

**Comment by SubhashRoy044** [comment]
It is installed by user directly .Yes, i am in stage/PPE enviroment .

**Comment by exextoc** [comment]
Can you please capture log for the user and send it over to `user0@a830edad9050849w1IYcOvTMcAr.onmicrosoft.com` ? 
You can use fiddler to do the same. Please start recording as soon as the outlook session starts. 

Please share a trace for OWA where its working, and new Outlook where it's not.

**Comment by exextoc** [comment]
Hi @SubhashRoy044, could you please confirm if you have shared the logs?
