### ISSUE TITLE
How can I address the data communication problem between the task pane and the dialog box in my Outlook add-in?

### ISSUE THREAD

**Issue by ZabeehUllah** [OfficeDev/office-js#3815]
**Description:**
I'm developing a Microsoft Outlook add-in, and I'm facing two issues:

1. Dialog Box Not Closing After Sign-In:

   My add-in loads inside the task pane, which opens a dialog box for signing in to a Microsoft account.
   After successfully signing in, the dialog box doesn't close as expected.

2. Data Communication Issue:

   I'm sending data from the parent task pane to the dialog box using the provided methods, but the dialog box doesn't 
   seem to receive the data correctly.

**Here's a my code:**

Taskpane code where I open my dialoge box
``Office.context.ui.displayDialogAsync(popupUrl, dialogOptions, (result) => {
  const dialog = result.value;
  const messageToDialog = JSON.stringify({
    isDialog: localStorage.getItem('isDialog'),
    companySsoId: companyDomainId,
  });`
  dialog.messageChild(messageToDialog);
});``

Dialogue box code
`` Office.onReady((info) => {
    console.log('Data 3: ', info);
    if (info.isOfficeInitialized) {
      Office.context.ui.addHandlerAsync(Office.EventType.DialogParentMessageReceived, (arg) => {
        console.log('Data 4: ');
        try {
          const messageFromParent = JSON.parse(arg.getArgs().message);
          console.log('Received message from parent: ', messageFromParent);
          // Handle the message from the task pane as needed.
        } catch (error) {
          console.error('Error parsing the message from parent:', error);
        }
      });
    }
  }); ``
  
Note: Data 3 is logged but Data 4 is **NOT** logged to the console. My code runs the rest of the dialoge box but it doesn't enter **Office.context.ui.addHandlerAsync** block.

**Comment by exextoc** [comment]
@ZabeehUllah Is there any office API that is failing in your case?

**Comment by ZabeehUllah** [comment]
@exextoc No office API is failing. I think it's because of the fact that dialog box is opened in a different domain than that of the task pane.
However, for cross-domain communication I have added **{ targetOrigin: '*' }** to  messageParent. Here is my updated code for sending message to the task pane from dialog box.


```
  Office.initialize = () => {
    console.log('Office initialized');
    const data = JSON.stringify({
      ping: 'SignInSuccessful',
      code: myParam,
    });
    Office.context.ui.messageParent(data, { targetOrigin: '*' });
  };
```
This is how I am handling it in the task pane.

    Office.context.ui.displayDialogAsync(popupUrl, dialogOptions, (result) => {
      const dialog = result.value;
      dialog.addEventHandler(Office.EventType.DialogMessageReceived, (arg) => {
        console.log('arg: ', arg);
        if (arg.message === 'IAmReady') {
          console.log('message: ', arg.message);
          dialog.messageChild(messageToDialog);
        }
        if (JSON.parse(arg.message).ping === 'SignInSuccessful') {
          console.log('message: ', arg.message);
          setIsLoading(false);
          dialog.close();
          siginAfterSso(companyDomainId);
        }
      });
    });

**Comment by ZabeehUllah** [comment]
@exextoc Can I get some insight into this issue please?

**Comment by exextoc** [comment]
@ZabeehUllah Follow the guidelines in the link below to send message from display dialog to parent page. https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#send-information-from-the-dialog-box-to-the-host-page
