### ISSUE TITLE
Outlook (OfficeJS) add-in gets stuck if email headers contain ETX control character

### ISSUE THREAD

**Issue by atsopuronen** [OfficeDev/office-js#3816]
It appears that (at least) `ETX` control character in header content causes problems for Outlook add-ins. It is possible other control characters may also cause similar issues.

## Your Environment
We have tested a message with an `ETX` control character in the _Subject_ in OWA, Mac Outlook and Windows Outlook. Of these, only Windows Outlook exhibited problems.

The Windows Outlook version tested and found to be affected was **Microsoft® Outlook® for Microsoft 365 MSO (Version 2310 Build 16.0.16924.20054) 64-bit**.
 

## Current behavior
What happens when trying to invoke an Outlook Add-in on an affected message is that OfficeJS's `Office.onReady` function is **never executed**. We haven't been able to observe any specific errors due to difficulty of Outlook debugging.

## Expected behavior
Control characters shouldn't cause issues.

## Steps to reproduce
We are able to reproduce the issue with both our production add-in as well as MHA ([Message Header Analyzer](https://appsource.microsoft.com/en-us/product/office/wa104005406?tab=overview)) add-in. If needed, we can also provide a simple Outlook add-in that was used to investigate the situation.

The attached ZIP file contains an eml. It can be used to reproduce the issue.
[outlook-addin-issue.eml.zip](https://github.com/OfficeDev/office-js/files/13279146/outlook-addin-issue.eml.zip)

Full plaintext content of the sample .eml is as follows:

```
Sent:	Tuesday, 7 November 2023 11.04
To:	you@localhost
Subject:	=?iso-8859-1?Q?Special Character ETX (03) =03?=

Import this file into an Outlook mailbox.
Then use the Windows Desktop Outlook (NOT "New Outlook").
Attempt to run an add-in that uses Office JS.
Office.onReady function will never be called.
```

# Provide additional details
Removing `ETX` control character from Subject header resolves the issue.

## Context
Our Outlook add-in is used for reporting suspicious emails (phishing etc.). Malicious actors will likely take advantage of this shortcoming if it's not fixed somehow.

## Useful logs
n/a

**Comment by hoxteppo** [comment]
The issue still exists. Do you have any updates on this?

**Comment by atsopuronen** [comment]
Any updates?

**Comment by ztcdsb** [comment]
@atsopuronen I am not able to repro the issue. 
Can you please share a testing add-in with detailed repro steps or a video record for the issue. It will help us investigate the issue. 

Also, is the issue also happens to the latest version of Outlook?

**Comment by hoxteppo** [comment]
@ztcdsb You can use [Message Header Analyzer](https://appsource.microsoft.com/en-us/product/office/wa104005406?tab=overview) add-in. Add-in does not load the headers but keeps loading. The repro steps are mentioned under the "Steps to reproduce" section. This issue still occurs with Outlook destkop version.

**Comment by ztcdsb** [comment]
@hoxteppo @atsopuronen please advice if I did it wrong. 
I import the email attached and load header with Message Header Analyzer add-in. Below is what I get:
![image](https://github.com/OfficeDev/office-js/assets/11720560/87c187cb-e8d4-4ac0-ad16-c9130687cbf5)

**Comment by hoxteppo** [comment]
@ztcdsb It looks like the issue is gone now. I cannot reproduce the issue anymore. You can close the ticket.
