### ISSUE TITLE
Excel addin - Taskpane not displaying properly

### ISSUE THREAD

**Issue by DJay921** [OfficeDev/office-js#3817]
I was trying to run my custom Taskpane Excel add-in after a few days and noted that the certificates had expired, and the app wasn't running. So I did a` npx office-addin-dev-certs install` which resolved, however now I notice that the Taskpane is no longer displaying properly (with a dark background, and distorted when dragged). Please see screenshot.
<img width="437" alt="ISSUE-ADDIN-DISPLAY3" src="https://github.com/OfficeDev/office-js/assets/14841097/d29a62a4-7482-458b-8cec-928830010f9b">

<br>

1. **Please note**: When I open the app and load the `https://localhost:3000` in the browser it loads up properly without this issue.
2. I also tried [clearing the cache for Office](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache) multiple times but didn't fix it. 
3. I have not made any edits to the code as well so I'm not sure how this occurred. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Office 2021

* Operating System: Windows 11
* Browser (if using Office on the web): Issue not faced when app opened on Browser

**Comment by DJay921** [comment]
Surprisingly, if I set a background-color to my body tag, this issue goes away.

**Comment by JesseWayneJames** [comment]
I am having a similar issue developing a microsoft word addin with typescript/react. Same environment as original poster except for windows 10.

**Comment by penglongzhaochina** [comment]
hi @DipanshuJuneja,
still happened there?

**Comment by shanshanzheng-dev** [comment]
Hi @DipanshuJuneja Hope you have a good day, are you still repro this issue? Thanks.

**Comment by rgold5950** [comment]
I also had this issue. I'm not sure what causes it but the only way I was able to fix it is by adding a background color to the taskpane as specified above. I think this might be a bug where Excel doesn't allow transparent taskpane background.
