### ISSUE TITLE
Outlook doesnt trigger Addin callback for Encrypted mails

### ISSUE THREAD

**Issue by mkondadg** [OfficeDev/office-js#3819]
Sending an mail with different options in new Outlook UI and found out that when we encrypt the mail as below and send the mail, addin callback is not called at all.
Is this not-supported or officially documented somewhere ?

## Your Environment
* Windows desktop
* Outlook
* You have Microsoft Outlook Version 1.2023.1018.300 (Production).
  Client Version is 20231027003.07 .
* Windows 10 Enterprise 21H2 19044.2006
 
## Expected behavior
JS Addin callback is called

## Current behavior
JS Addin callback is NOT called

## Steps to reproduce
1. Click Home -> New mail -> Mail
2. Click Options -> Set permissions on this item
3. Click "Encrypt"
(Please refer to attached image)

## Context
This doesnt help for our addin to miss a javascript callback when such an email is sent.

![encrypt_mail_not_supported_3](https://github.com/OfficeDev/office-js/assets/62250655/e1e58136-605b-4934-b79c-de4ab6dc1602)

**Comment by exextoc** [comment]
Outlook addins are not available for encrypted mails. It is captured here. https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-add-ins-overview#mailbox-items-available-to-add-ins

**Comment by mkondadg** [comment]
thanks for the update.
Is there a plan to support it later ?

**Comment by exextoc** [comment]
Please refer to https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-add-ins-overview#mailbox-items-available-to-add-ins to see how add-ins can be used on encrypted email.
