### ISSUE TITLE
Outlook: Current user username

### ISSUE THREAD

**Issue by Aidam1** [OfficeDev/office-js#3821]
We have received information about changes to tokens that are returned from `getCallbackTokenAsync`.
https://devblogs.microsoft.com/microsoft365dev/important-announcement-update-to-exchange-callback-tokens-for-outlook-add-ins/

We are currently relying on getting username from this method:
```
const accessTokenRes = await new Promise<Office.AsyncResult<string>>((res) => {
    Office.context.mailbox.getCallbackTokenAsync(res);
});
const parts = accessTokenRes.value.split(".");
const token = JSON.parse(atob(parts[1])) as { appctx: string };
const appCtx = JSON.parse(token.appctx) as { upn: string };
const username = appCtx.upn;
```

We are using this username in MSAL as `loginHint`. Also, we check if the username logged into MSAL is the same as the one using Outlook.

Is there any other way to get username, or otherwise satisfy these use cases?

**Comment by exextoc** [comment]
@Aidam1 You can get user related information from [user profile](https://learn.microsoft.com/en-us/javascript/api/outlook/office.userprofile?view=outlook-js-preview#outlook-office-userprofile-emailaddress-member).

**Comment by Simmik15** [comment]
what are the other ways to fetch email id from token?

**Comment by Aidam1** [comment]
I have noticed that `upn` has already been removed. 

> @Aidam1 You can get user related information from [user profile](https://learn.microsoft.com/en-us/javascript/api/outlook/office.userprofile?view=outlook-js-preview#outlook-office-userprofile-emailaddress-member).

@exextoc The information from user profile are not sufficient, since emailAddress might not equal username in MSAL, therefore I can't use it as loginHint. Is there some other way to get username?
