### ISSUE TITLE
When a delegate user has opened an appointment, calls to Office.context.mailbox.item.itemId return incorrect event ids.

### ISSUE THREAD

**Issue by darrylriva** [OfficeDev/office-js#3827]
Outlook-on-the-web:
Suppose a Microsoft office user (called the 'Boss') has created an appointment. The appointment can be a single appointment or a series with a few instances.
Next suppose another user who is a delegate to the Boss has opened the Boss's appointment. Again, it can be a single appointment, a series master, or an instance of a series. Then when the Office add-in for the appointment executes the following javascript:
	`var id = Office.context.mailbox.item.itemId `
this query returns an *incorrect* id.

Note that when the Boss makes the same call to
	`var id = Office.context.mailbox.item.itemId`
this query returns the *correct* id.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook-on-the-web
* Office version number: NA - Microsoft 365 Admin Center
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome, Edge, Firefox
 
## Expected behavior

The javascript call to Office.context.mailbox.item.itemId returns the correct itemId for a delegate in an appointment.

## Current behavior
![ScriptLab Screenshot for GetItemIdAndDisplayInfo](https://github.com/OfficeDev/office-js/assets/126609625/cd5276fc-f413-4261-a27c-214c0988f1e7)

For delegate in appointment organized by the Boss (single, series master, or series instance), when the delegate's add-in makes javascript call
	`var id = Office.context.mailbox.item.itemId`
this query returns an *incorrect* id.

## Steps to reproduce

1. Boss signs in to Outlook-on-the-web and creates and sends an appointment to an attendee.
2. Boss opens the appointment and the add-in calls 'var id = Office.context.mailbox.item.itemId'.
3. Copy this appointment id.
4. Delegate signs in to office using Outlook-on-the-web and opens the Boss's appointment.
5. The add-in calls var `id = Office.context.mailbox.item.itemId`.
6. Copy this delegate version of the appointment id.
7. Compare the Boss's version of the appointment id with delegate's version. Note that they are *different*.

## Link to live example(s)

Public gist for ScripLab script to display itemId and appointment info
'GetItemIdAndDisplayInfo'
https://gist.github.com/darrylriva/51996fcfe201be15431d3a1014ee166d
1. Use the ScriptLab script to get the ids returned by call to 'Office.context.mailbox.item.itemId'.
2. Boss loads the script and clicks the button 'Get the itemId & information about it'.
3. Copy the itemId displayed in console.  See screenshot.
4. Delegate loads the script and clicks the button 'Get the itemId & information about it'.
3. Copy the itemId displayed in console.  Note that the two ids are different. The Boss's id is correct.

## Context

Our add-in uses the appointment id to fetch and update properties on the appoinment using Microsoft graph calls. When the delegate wants to get a Boss's appointment, a graph call is made like:
	`https://graph.microsoft.com/v1.0/users/ {Boss email address} /events/ {appointmentId}`

These calls fail when the id is incorrect.

Note that when the delegate is using OutlookDesktop (thick client) in Windows rather than Outlook-on-the-web, the appointment id is got using the office javascript call:
	`Office.context.mailbox.item.getItemIdAsync()`
This call does return the *correct* id to the delegate.

## Useful logs

- [x] Screenshots

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Thanks for reporting the bug for the itemID property different in delegate scenario for Outlook Web. It has been put on our backlog. We unfortunately have no timelines to share at this point.
Internal tracking id: [4097028]

**Comment by arpitsangwanmsft** [comment]
Hey @darrylriva!
There is a slight difference in UX where the appointment opens in compose mode by default for organizer in desktop clients vs web/mac clients where appointment can be opened in appointment read mode.

The appointmentId returned by  `Office.context.mailbox.item.itemId` when using delegate mailbox is connected to delegate mailbox's instance of appointment and is correct.
To fetch subsequent appointment details, graph calls can be made like this:
`https://graph.microsoft.com/v1.0/users/ {Delegate email address} /events/ {appointmentId}`
Returned appointmentId for delegate mailbox works with the above call.

Please make sure to use `Delegate email Address` when using Id from `delegate's mailbox` and `Boss email Address` when using id from `boss's mailbox` while making a call to the endpoint.
Thanks!

**Comment by darrylriva** [comment]
@arpitsangwanmsft - thank you. We will try as you suggested.
