### ISSUE TITLE
Outlook 16x16 icon not reflecting for toolbar in Outlook Web

### ISSUE THREAD

**Issue by dhwanilchokshi** [OfficeDev/office-js#3828]
We are trying to change the icon on the toolbar for Outlook Web to showcase a monoline icon, while the add-in itself should showcase our product icon. We realized that changing the <IconUrl> in the manifest.xml is the only way to change the icons, but it will update both the toolbar AND add-in icon to the same icon. 

We were told to replace the 16x16 icon in <Resources> to monoline, and it would accurately reflect in the toolbar, but seems it doesn't seem to take effect. 

To better illustrate our issue:
![icon-issue](https://github.com/OfficeDev/office-js/assets/24537480/ede79895-0ac9-4643-86a8-130c56bb0f45)

On the left, we have the toolbar icon (which we are trying to change to monoline icon). On the right, we have the add-in icon, which we are trying to keep the same.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook Web/Monarch
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows 11
* Browser (if using Office on the web): Edge
 
## Expected behavior
The toolbar icon for add-in should take the 16x16 icon from <Resources>, and reflect on the toolbar ribbon on the Outlook Web.

## Current behavior
The toolbar icon does not change to the monoline icon unless the <IconUrl> is updated. But updating the <IconUrl> updates both the toolbar AND the add-in icon.

## Steps to reproduce
Have a different icon in <Resources> for the 16x16 and <IconUrl>. Try to see whether they reflect correctly.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context
We are trying to have different icons for the toolbar in Outlook Web (as shown above) and the add-in icon.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by jasonxian-msft** [comment]
Adding on to the issue, within the manifest.xml, we tried to update the `<Resources><bt:images><bt:Image id="Icon.16x16">` hoping that would allow us to see a different icon on the email ribbon. But just changing that line didn't give the expected result. It seems the only way to change the 16x16 icon right now is to change the `IconUrl`, which isn't desired because it will change all the icons (not just the ribbon icon).

**Comment by exextoc** [comment]
@dhwanilchokshi Can you please share the document which you have followed and where it is mentioned that we can have different add-in icons for toolbar and add-in.

**Comment by dhwanilchokshi** [comment]
@exextoc We were mainly using the manifest reference (https://learn.microsoft.com/en-us/javascript/api/manifest?view=common-js-preview) and also have been talking to the outlook add-in team. They told us to file a bug for this item since it isn't (or may not be) possible today.

**Comment by exextoc** [comment]
Currently the feature, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
