### ISSUE TITLE
Error: InvalidRibbonDefinition when Disabling Ribbon Items in Word Web Add-in using Office.js and Angular

### ISSUE THREAD

**Issue by AbhishekKatariya9** [OfficeDev/office-js#3829]
I'm working on a Word Web Add-in using Office.js and Angular, and I'm trying to programmatically enable and disable ribbon items within my add-in. According to the Microsoft Office Add-ins documentation, I should be able to use the Office.ribbon.requestUpdate method to update ribbon elements. Ref: [documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands)

`Office.ribbon.requestUpdate({
      tabs: [
        {
          id: 'TabCustom',
          groups: [
            {
              id: 'TabGroup2',
              controls: [
                {
                  id: 'DataverseBtn',
                  enabled: false,
                },
              ],
            },
          ],
        },
      ],
    });`
while executing above code I'm getting the error:
`Error: Uncaught (in promise): InvalidRibbonDefinition: InvalidRibbonDefinition
RichApi.Error: InvalidRibbonDefinition`

I've verified that the IDs in my code match the IDs in the manifest file. What could be causing this "InvalidRibbonDefinition" error, and how can I resolve it?

Office.js Version: CDN "https://appsforoffice.microsoft.com/lib/1/hosted/office.js" Angular Version: 16.2.0

Thank you for your assistance.

Ribbon button should be enable or disabled programmatically.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 5c7b653d-1bd6-a032-2046-6d6a2ad2b203
* Version Independent ID: 7165a66d-bc9a-dce9-91c4-7c1209d1324e
* Content: [Enable and Disable Add-in Commands - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands)
* Content Source: [docs/design/disable-add-in-commands.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/design/disable-add-in-commands.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by alison-mk** [comment]
Hi @AbhishekKatariya9, thank you for submitting this issue. @Rick-Kirkham could you take a look at this ribbon question, or reassign it if someone else is a better fit?

**Comment by Rick-Kirkham** [comment]
Not really a documentation issue. Moving to office-js.

**Comment by Rick-Kirkham** [comment]
@AbhishekKatariya9 You have a lot of logically unnecessary commas in the object you are passing. Get rid of those and see if that fixes it.

**Comment by Rick-Kirkham** [comment]
@AbhishekKatariya9 What platform are you testing on? Windows, Mac, or on the web?

**Comment by AbhishekKatariya9** [comment]
I will try removing unnecessary commas and will get back to you.

Edit: ( getting same error even after removing commas)
I am using Windows ( windows 10, Office 365 v18.23 )

**Comment by Rick-Kirkham** [comment]
@AbhishekKatariya9 It turns out that our documentation was in error. Disabling ribbon items is not supported in Word. We are correcting the documentation and the corrected version should be published on March 5th. Sorry we had to bring you this bad news. I will close this issue now, but you can still add comments and we will see them.

**Comment by Hendryshi** [comment]
Hi, I want to know if this issue is corrected now ? As I got the same error when developping word office addIn in angular project

**Comment by Tofahat-teva** [comment]
@Rick-Kirkham Hi, I am also facing the same issue while developing a Word Office Add-in in an Angular project. Has this issue been resolved?
