### ISSUE TITLE
Outlook doesn't switch Message view to Compose view

### ISSUE THREAD

**Issue by markb-trustifi** [OfficeDev/office-js#383]
After refreshing the add-in page the add-in remains in Message view and doesn't switch to Compose view.

## Expected Behavior
Compose view should appear

## Current Behavior
Doesn't work only in browser with old UI.
Message view appears

## Steps to Reproduce, or Live Example
Keep old Outlook UI.
Movie: https://streamable.com/bwhrr

- create new email
- pin taskpane
- click **Discard** - very important!
- open sent email
- pin taskpane
- create new email again

The add-in remains in Message view and doesn't switch to Compose view.
The `Office.context.mailbox.item.internetMessageId` remains equal to the last selected email

## Your Environment
* Platform: Office Online
* Host: Outlook
* Office version number: 16.0.11215.10000
* Operating System: MacOs, Windows
* Browser (if using Office Online): Chrome

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding Compose view switch issue. We are able to repro this issue with old-OWA. It has been put on our backlog. We unfortunately have no timelines to share at this point. 

Note that this issue does not happen with new-OWA. If possible, you can switch to new OWA to resolve this issue immediately.
