### ISSUE TITLE
When a user creates Outlook groups in contacts, I am unable to fetch the email IDs present in contacts via the EWS SOAP API request for Outlook desktop.

### ISSUE THREAD

**Issue by SubhashRoy044** [OfficeDev/office-js#3832]
# Provide required information needed to triage your issue
When a user creates Outlook groups in contacts, I am encountering an issue where I am unable to fetch the email IDs present in contacts via the EWS SOAP API request for Outlook desktop

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2308 and build 16731.2
* Operating System: Window

 
## Expected behavior

When a user creates Outlook groups in contacts, I am able to fetch the email IDs present in contacts via the EWS SOAP API request for Outlook desktop and outlook web both platform.

## Current behavior

When a user creates Outlook groups in contacts, I am able to fetch the email IDs present in contacts via the EWS SOAP API request for  outlook web but not in outlook desktop.

It should work for both.

## Steps to reproduce

1.Add the Web Add-in via sideload with "extraction code of EWS SOAP API request" via installing manifest.
2. Go to Outlook in browser(outlook Web) and open outlook new mail -> Add contact group in to ,CC -> and send button then Web Add-in dialog is appears and able to extarct email ids present in contacts group. .
3.Go to Outlook thick client (both old) and open outlook new mail -> Add contact group in to ,CC -> and send button then Web Add-in dialog is appears and unable to extarct email ids present in contacts group .

## Link to live example(s)

Code -
 export const new2='<?xml version="1.0" encoding="utf-8"?>'+
'<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">'+
  '<soap:Header>'+
    '<t:RequestServerVersion Version="Exchange2016" />'+
  '</soap:Header>'+
  '<soap:Body>'+
    '<m:ExpandDL>'+
     '<m:Mailbox>'+
        '<t:ItemId  Id="{ItemId}" />'+
      '</m:Mailbox>'+
    '</m:ExpandDL>'+
  '</soap:Body>'+
'</soap:Envelope>';

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Adrian-MSFT** [comment]
Hi @SubhashRoy044 , this sounds like a server sync issue. Are you able to retrieve the contacts group info via the EWS request after waiting some time?

**Comment by SubhashRoy044** [comment]
No, after waiting for sometime also we are not able to retrieve contact group info in Outlook desktop however we are able to get in Outlook web-addin in browser.

**Comment by Adrian-MSFT** [comment]
Hi @SubhashRoy044 apologies on the long delay here - Are you still experiencing this issue?
