### ISSUE TITLE
Missing Send Event When Forwarding Meeting Invite in Outlook Web Add-in for Desktop and Web

### ISSUE THREAD

**Issue by SubhashRoy044** [OfficeDev/office-js#3833]
# Provide required information needed to triage your issue
Overview:
My office Add-in relies on the email send event, triggering a dialog for pre-send activities. However, in both Outlook Desktop and Outlook Web, we are encountering an issue when forwarding a meeting invite.

Issue:
The expected dialog/model for the send event does not appear when users attempt to forward a meeting invite from the calendar. This prevents the necessary call to our event and inhibits the execution of required actions before sending.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook desktop and outlook web
* Office version number: Version 2308 and build 16731.2
* Operating System: _Windows

 
## Expected behavior

The Send event dialog/model should consistently appear when forwarding a meeting invite in both Outlook Desktop and Outlook Web, allowing our Add-in to execute the necessary pre-send activities.

## Current behavior

Upon investigation, it seems that the event triggered when forwarding a meeting invite is distinct from the standard email/invite send event. We are currently unable to identify and capture this specific event.

## Steps to reproduce

Steps to Reproduce:

1. Open Outlook Desktop or Outlook Web.
2. Navigate to the calendar and select a meeting invite.
3. Click "Forward" to initiate the forwarding process.
4. Observe that the Send event dialog/model does not appear as expected.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ndeleuze** [comment]
@SubhashRoy044 does this issue happen when using the New Windows Outlook or the Old Windows Outlook, or both?

**Comment by SubhashRoy044** [comment]
It is Happening in both , New Windows Outlook and the Old Windows Outlook. Also in Outlook Web Add-in in browser.
My office Add-in relies on the email send event, triggering a dialog for pre-send activities. However, in both Outlook Desktop and Outlook Web, we are encountering an issue when forwarding a meeting invite.
Below are the three senario we are facing issue and steps to reproduce.

**In Case of OWA in browser:-**
Steps to reproduce : 
1. from inbox choose one meeting invite
2. open the meeting invite
3. click on forward.
4. enter random mail id in the recipient section.
5. click send.
<img width="391" alt="image" src="https://github.com/OfficeDev/office-js/assets/150111732/a24a3716-8a3f-4ae0-ab89-77cd70235c2a">



**In case of OWA in browser  (from Task Pane)**
Steps to reproduce : 
1.open outlook in browser.
2.click on the calendar icon on top right.
3.Click on new event and click send.
<img width="225" alt="image" src="https://github.com/OfficeDev/office-js/assets/150111732/38152434-ea24-4288-93d3-576ed799e9f4">

**In case of OWA in Desktop (for Older version )**
steps to reproduce : 

1. from inbox choose one meeting invite and right click on meeting invite and click on forward.
2. enter random mail id in the recipient section.
3. click on close.
4. after clicking on close mail then one pop up will come like below and  in pop up click on yes.
<img width="330" alt="image" src="https://github.com/OfficeDev/office-js/assets/150111732/dafa4736-7a9c-4bea-ac44-625f53ab6549">

**Comment by ndeleuze** [comment]
Thanks for reporting this issue regarding the OnSend event not triggering for meeting forward. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: 8587471

**Comment by exextoc** [comment]
For outlook web this issue is being tracked by [bug](https://github.com/OfficeDev/office-js/issues/3808)
