### ISSUE TITLE
Missing Send Event When Proposing New Time in Meeting Invite - Outlook Web Add-in for Desktop and Web

### ISSUE THREAD

**Issue by SubhashRoy044** [OfficeDev/office-js#3834]
# Provide required information needed to triage your issue
My office Add-in relies on the email send event to trigger a dialog for pre-send activities. However, in both Outlook Desktop and Outlook Web, we are experiencing an issue when proposing a new time in a meeting invite.

The expected dialog/model for the send event does not appear when users attempt to propose a new time in a meeting invite. This absence prevents the necessary call to our event and inhibits the execution of required actions before sending.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior

The Send event dialog/model should consistently appear when proposing a new time in a meeting invite in both Outlook Desktop and Outlook Web, allowing our Add-in to execute the necessary pre-send activities.

## Current behavior

Upon investigation, it appears that the event triggered when proposing a new time in a meeting invite is send event is not triggering . We are currently unable to identify and capture this specific event.
## Steps to reproduce

1. Open Outlook Desktop or Outlook Web.
2. Navigate to the calendar and select a meeting invite.
3. Click ""Propose New Time"" to initiate the forwarding process.
4. Observe that the Send event dialog/model does not appear as expected.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by VarshaJumanal** [comment]
@exextoc Could you please let us know if there has been any progress on this?

**Comment by ndeleuze** [comment]
@SubhashRoy044 does this issue happen when using the New Windows Outlook or the Old Windows Outlook, or both?

**Comment by SubhashRoy044** [comment]
It is Happening in both , New Windows Outlook and the Old Windows Outlook. Also in Outlook Web Add-in in browser.

**Comment by ndeleuze** [comment]
@SubhashRoy044 is this dialog displayed successfully when a new meeting invite is created and sent? Also, are you using the custom properties API in your OnSend event?

**Comment by exextoc** [comment]
looks related to #3833

**Comment by ndeleuze** [comment]
@SubhashRoy044 would you be able to provide more details on the repro steps for the Old Outlook and include some screenshots in possible?

**Comment by SubhashRoy044** [comment]
> looks related to #3833

Yes. It is similary .

**Comment by ndeleuze** [comment]
@SubhashRoy044 I am not able to reproduce this in Old Outlook Desktop when sending a meeting update with new times. Can you confirm that this repros in Outlook Win32 (Old Outlook) and provide repro steps and screenshots?
