### ISSUE TITLE
Message Analyzer Addin Stops Reporting Header Details

### ISSUE THREAD

**Issue by TMapes82** [OfficeDev/office-js#3840]
# Tried to uninstall and reinstall the addin

## Your Environment

* Platform: PC 
* Host:  Outlook
* Office version number: Client Version is 20231110003.07 .
* Operating System:  Windows 11 Enterprise Build 10.0.22621

 
## Expected behavior
Should report the headers in detail

## Current behavior
Just provides the subject of the message

## Steps to reproduce

1.  Install Message Analyzer addin for Outlook from market place
2.  Open a Message
3.  Click the Message Analyzer button

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context
Security review of messages to confirm the sender is legitament 

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Hi @TMapes82 ,

I am unable to repro this. Is this happening on all emails or only specific emails?
Additionally, can a different add-in successfully retrieve the information on an email that Message Analyzer fails?
