### ISSUE TITLE
How to remove add-in information from Excel workbook programatically

### ISSUE THREAD

**Issue by bhattikashif** [OfficeDev/office-js#3844]
[Enter feedback here]

[Documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document#:%7E:text=For%20example%2C%20a%20student%20who%20uses%20a%20dictionary%20add%2Din%20in%20a%20Word%20document%20might%20not%20want%20their%20classmates%20or%20teachers%20to%20be%20prompted%20to%20install%20that%20add%2Din%20when%20they%20open%20the%20document.:~:text=For%20example%2C%20a%20student%20who%20uses%20a%20dictionary%20add%2Din%20in%20a%20Word%20document%20might%20not%20want%20their%20classmates%20or%20teachers%20to%20be%20prompted%20to%20install%20that%20add%2Din%20when%20they%20open%20the%20document.) says that we can when we need to share our document with someone and don't want to add-in information in it, we can do so. But I have searched it everywhere and found no way to so do in case of Excel Add-in. I have tried code in Word sample linked at this page, but still Add-in appears to load and show error that you don't have access to Add-in.

So is there any way that my add-in does not save any link/reference/traces in workbook or at least does not show error taskpane
![Capture](https://github.com/OfficeDev/office-js-docs-pr/assets/103940975/5f86f453-6a48-4668-8238-66222c349720)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: eb729902-e88a-02f7-2f4c-7c5f86a3e87a
* Version Independent ID: d6aab83f-2c52-8517-bc78-3189feb9e361
* Content: [Automatically open a task pane with a document - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document)
* Content Source: [docs/develop/automatically-open-a-task-pane-with-a-document.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/automatically-open-a-task-pane-with-a-document.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @bhattikashif,

Thanks for raising this issue. Just to clarify, are you embedding your add-in in the workbook, as described in the auto-open article? Or is this happening with some admin-deployed add-in?

**Comment by bhattikashif** [comment]
I am not embedding my add-in in the workbook (my code does not have references to Office.context.document), if there is any other way to embed it implicitly, then I am unaware of it.

Even when I tried to remove it using Office.context.document.settings.remove('Office.AutoShowTaskpaneWithDocument');  or Office.context.document.settings.set('Office.AutoShowTaskpaneWithDocument', false); 
but same behavior persists.

Yes it is happening with Admin deployed add-in and users are getting this error 
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/103940975/cd7339f0-c85a-4bb4-bbcf-8950c0e9cc60)

**Comment by AlexJerabek** [comment]
Thanks for clarifying. This seems like a product issue, so I'll transfer this from the docs to the [office-js repo](https://github.com/OfficeDev/office-js). There, members of the product team can debug this and figure out why your users are seeing this issue with an admin-deployed add-in.

**Comment by SiruiSun-MSFT** [comment]
Hi @bhattikashif, I'm afraid you can't delete add-in information programmatically. I want to know if you can accept manual deletion. If you can, maybe try: 

Go to Info=> Inspect Document => Remove All Taskpane Add-ins.

It is worth noting that before the deletion operation, please ensure that there is no use or dependence on the Add-in function in the document to prevent the deletion from being completed.

Hope it will help you out. Thanks!
