### ISSUE TITLE
Outlook Mac Thick Client : Validated Attachments in the Outlook Web Addin popup are not getting downloaded . 

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#3848]
My service incorporates the functionality to display a dialog using `displayDialogAsync()` and to list and download individual attachments with dedicated download links. While this feature works correctly in Outlook for Windows and Outlook on the web, performing the same operation in Outlook for Mac does not trigger any action when clicking the download link.

Although there have been reports of a similar issue in  [3662](https://github.com/OfficeDev/office-js/issues/3662), there is currently no effective solution identified. Since there are instructions from @exextoc  within issue in [#3824](https://github.com/OfficeDev/office-js/issues/3824#issuecomment-1811706066) , a new ticket will be created.

**Comment by mailchecktool-admin** [comment]
@exextoc 
I am facing the same problem as here. Called Office.context.ui.openBrowserWindow(URL); as a solution to the above problem,
I tried to open the browser using the URL I own but it does not work.
Specifically,
After creating the BLOB object
const fileURL = window.URL.createObjectURL(blob)
window.open(fileURL)
was changed to
After creating the BLOB object
const fileURL = window.URL.createObjectURL(blob)
Office.context.ui.openBrowserWindow(fileURL)
but Office.context.ui.openBrowserWindow() could not open the BLOB object URL.
Can't Office.context.ui.openBrowserWindow() open BLOB object URLs directly?

**Comment by exextoc** [comment]
@mailchecktool-admin can you paste the format of the URL here. Is it file://*?

**Comment by mailchecktool-admin** [comment]
@exextoc 
I created a URL for a very simple text file. The sample code is as follows:
```
const blob = new Blob(["Hello, blob!"], {type: 'text/plain'});
const fileURL = URL.createObjectURL(blob);
console.info(fileURL);
Office.context.ui.openBrowserWindow(fileURL);
console.info("window.open is done");
```
Is this source code incorrect? If so, what changes should be made to the source code to make it work correctly? Please provide specific guidance on how to write the source code, as I will provide the source code for a sample add-in.
https://drive.google.com/file/d/1et0uKHX_2e8R4UVtCif9KiaevDyG9tG4/view?usp=drive_link

**Comment by mailchecktool-admin** [comment]
The reproduction steps are as follows.

1. Download "downloadSample(window.open).zip" and place it in your desired location.
2. Launch the command prompt and navigate to the corresponding directory.
3. Run "npm install".
4. Run "npm run dev-server".
5. Upload "manifest.xml" in Outlook on the web to install the add-in. (The XML file is stored in downloadSample(window.open).zip)
6. Create and send an email.
7. click "download TextFile" button.

**Comment by exextoc** [comment]
Closing this issue. This is getting tracked under: https://github.com/OfficeDev/office-js/issues/3662

**Comment by mailchecktool-admin** [comment]
@exextoc 
I understand that we are going to close this ticket.

However, I have one question. Regarding the #3662 ticket, I don't believe you have provided any guidance or responses regarding a solution. I provided you with information about a sample add-in the other day, but I haven't received any feedback on the investigation results conducted with that add-in. Could you please provide a response?

**Comment by exextoc** [comment]
@mailchecktool-admin  We have responded to your question here https://github.com/OfficeDev/office-js/issues/3#issuecomment-1851918799
