### ISSUE TITLE
Powerpoint Api

### ISSUE THREAD

**Issue by faludigabor** [OfficeDev/office-js#385]
Hi , 

I would need more information on the powerpoint office.js api . 

We'd like to convert an existing vsto app to office.js. in that ,we manipulate objects on slides all of them potentially. Identify objects move them , colour them etc. I dont beleive this is feasible via office.js. Can you ellaborate  ?

We would need to target windows/mac .

Tx,
gabor

**Comment by JuaneloJuanelo** [comment]
Thanks @faludigabor this site is enabled to track existing features. The right place for this request is our [user voice channel. ](https://officespdev.uservoice.com/)please make sure to add an entry there )or up-vote an existing one. thanks!
