### ISSUE TITLE
[Excel Web/PC/MAC] - Manifest file Support Url Issue

### ISSUE THREAD

**Issue by miguellandrito** [OfficeDev/office-js#3850]
# Provide required information needed to triage your issue
We are trying to upload our manifest file to AppSource, but the support url requirement is resulting in an error even though the site is accessible to the public and can be accessed by anyone. And the url complies with the requirements provided in the documentation: [AppSource FAQ](https://learn.microsoft.com/en-us/partner-center/marketplace/appsource-submission-faq)

![image](https://github.com/OfficeDev/office-js/assets/43631923/ec333d1f-7830-445b-a3a8-9e07d11fcd53)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC/Mac/Web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: latest
* Operating System: Windows 10
* Browser (if using Office on the web): Edge, Google Chrome, Firefox, and Opera
 
## Expected behavior

- Since https://www.factset.com/support-numbers/ is a valid support url, we are hoping to address this issue and be able to upload the manifest file into AppSource.

## Current behavior

- As seen in the image above, we are not able to upload the manifest file due to the support url error.
- We have also tried out different urls (factset external links) using the `office-addin-manifest validate` command and have also resulted in an error

## Steps to reproduce

1. use https://www.factset.com/support-numbers/ as supportUrl
2. use `npx office-addin-manifest validate -p <manifest_path>`
3. should result in supportUrl Error same as image above.

## Link to live example(s)

1. N/A

# Provide additional details

1. N/A

## Context

- We are trying to release the add-in for PC/MAC users but due to the error caused by the support url, we are unable to do so. This is the first time we've encountered the issue. 

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by smieszkowsk** [comment]
Hi @miguellandrito, we are facing the same issue. We uploaded the manifest in the past successfully but now all of the sudden we are getting this error when we try to upload.
Did you manage to solve the issue or found any workaround? 

@jargil @penglongzhaochina can you help with this please?

**Comment by shanshanzheng-dev** [comment]
Hi @smieszkowsk, seem like this issue has a workaround on https://github.com/OfficeDev/office-js/issues/4413. Hope it's helpful. Please comment if you still need assistance and we'll re-open the issue. Thanks.
