### ISSUE TITLE
Meeting Invite Send Event Not Triggered for DL Group Emails in outlook desktop

### ISSUE THREAD

**Issue by SubhashRoy044** [OfficeDev/office-js#3852]
# Provide required information needed to triage your issue
My office Add-in is based on the email send event. We open a dialog to perform a few activities before sending an email.

When sending a meeting invite from a DL (Distribution List) group mail in Outlook, the Expected Value in Dialog (pop-up) is not appearing, and the mail is bypassing since send event is not triggering .

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: outlook desktop
* Office version number: Version 2308 and build 16731.2
* Operating System:  Window 11

 
## Expected behavior

Need to  perform few activities before sending email .Also The Dialog ( pop-up) is should shown, and send event is should triggere.
## Current behavior

 Without  perform any activities email sent.Also The Dialog ( pop-up) is not shown, and send event is not triggered .

## Steps to reproduce

1. Open Outlook and navigate to the DL domain group.
2. Click on "New Item" to create a meeting invite.
3. Note that the DL domain ID is already present in the recipient section.
4. Add any random email IDs in the recipient section.
5. Click on "Send."
6. Send Event is not triggering and email is sent without dialog withou any activites.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by timwan10** [comment]
Web Add-ins are not supported in groups.

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-add-ins-overview#mailbox-items-available-to-add-ins
