### ISSUE TITLE
Can't use window.open in Office add-ins

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#3853]
# Provide required information needed to triage your issue

## Your Environment

* Platform : PC desktop, Outlook on the web
* Host : Outlook
* Office version number: 2108
* Operating System: windows
* Browser (if using Office on the web): Microsoft edge

## Current behavior
In my company, we sell an add-in that uses the "displayDialogAsync()" method to show a dialog and check emails. Over the past two years, we have encountered numerous unexpected behaviors with the "displayDialogAsync()" method. As a result, we are considering replacing it with the more common JavaScript method, "window.open()". Upon testing the replacement method, "window.open()", we have confirmed that it works smoothly.

However, when using the "postMessage()" method, we are experiencing unexpected behavior on some platforms. While Google Chrome behaves as expected, on Microsoft Edge and Outlook on Windows, the "window.addEventListener" does not seem to function as intended.

## Steps to reproduce
Below is the actual code
//parent
let dialog = window.open('URL')
if (dialog) {
  window.addEventListener('message', () => {
    dialog.onload = () => {
      dialog.postMessage('sampleText', window.location.origin)
    }
  })
}

**Comment by mailchecktool-admin** [comment]
Debugging shows that the window.addEventListener event is not recognized in the desktop outlook environment and the window.open event does not actually work.
Due to the nature of the service, we need to transfer email data between parent files and child files. We are currently exploring methods to facilitate this data exchange. Are there any solutions to address this issue? Alternatively, are there any methods other than using "window.open()", "postMessage()" that could serve as an alternative to displayDialogAsync()?

**Comment by mailchecktool-admin** [comment]
The reproduction steps are as follows.
1. Download "downloadSample.zip" and place it in your desired location.
2. Launch the command prompt and navigate to the corresponding directory.
3. Run "npm install".
4. Run "npm run dev-server".
5. Upload "manifest.xml" in Outlook on the web to install the add-in. (The XML file is stored in sample.zip)
6. Create and send an email.
7. click "download TextFile" button.

**Comment by mailchecktool-admin** [comment]
@exextoc 
Could you please confirm the above content? It is a crucial issue for our service, and we would appreciate any insights or suggestions for addressing the challenges. We understand you are busy, but we would be grateful for your confirmation. Thank you very much.

**Comment by zhngx1** [comment]
The open, postMessage, addEventListener methods should be supported. Can you help provide a barebone repro so I can test your scenario?

**Comment by mailchecktool-admin** [comment]
Sorry, this report was not accurate. There is no problem if you close here.
However, as I continued my investigation, I found another issue, so I would appreciate your response.
Scenarios are also available.
⇒https://github.com/OfficeDev/office-js/issues/3906

**Comment by zhngx1** [comment]
Thank you! I will close this post.
