### ISSUE TITLE
Is it possible to use Office.js without CDN?

### ISSUE THREAD

**Issue by dejandujak** [OfficeDev/office-js#3857]
### Discussed in https://github.com/OfficeDev/office-js/discussions/3856

<div type='discussions-op-text'>

<sup>Originally posted by **dejandujak** November 23, 2023</sup>
Hi all,

Currently I am working on soluition for the client where we have ON-PREMISE Microsoft Exchange Server 2019 and Outlook Add-in hosted in IIS on other server. Our solution is getting attachments as information objects and doing someting with them. Everything works well when we have CDN. But Location where Outlook Add-in is located  has only connection to Exchange and NOT
 to Internet. Because of the firewall there is no outbound connection to CDN only to Exchange. We were trying to download all files but no luck. Is there any other solution for this challenge? 

All help is welcome. 

![Outlook Issue 2023-11-23_09-48-08](https://github.com/OfficeDev/office-js/assets/8484052/92bc573e-2289-4b17-96ef-9204259b3168)
</div>

**Comment by exextoc** [comment]
Hi @dejandujak , please refer to the npm package for office-js- https://www.npmjs.com/package/@microsoft/office-js . This should solve your problem. You can get the office-js from here and serve it from a location of your choosing.

**Comment by dejandujak** [comment]
This is exactly what we did. Downloaded office-js to be part of our solution. But based on what I see is that Outlook Add-In will not work with offline-js files. Is this something that will be changed in the future? You can image that ON-PREMISE environment with high security level will not allow connection to 3rd party tools/scripts. That is the reason we need to host all files on our side. Will Microsoft bring changes in this direction because this is very important for such Organizations. Market we can approach is huge but aligned with their policies. If Only other solution is VSTO, which does not support WEB and is Legacy. Please let me know. Right now we are hopeless.

**Comment by exextoc** [comment]
Hey @dejandujak 

You can host office-js files locally and it should work fine, following the doc :https://www.npmjs.com/package/@microsoft/office-js. 
What are the challenges you face when you try out in a local setup ?
Also, what do you mean by offline-js files ?

**Comment by mark-office** [comment]
Dear Team,

I’m currently implementing an Outlook add-in using Office.js for an environment without internet connectivity. As suggested in the thread and per the guidance on the [@microsoft/office-js NPM package](https://www.npmjs.com/package/@microsoft/office-js), I've followed the approach to host Office.js locally to support offline scenarios.

However, I’ve encountered an issue where Office.js still tries to load the following script from the internet:
https://ajax.aspnetcdn.com/ajax/3.5/MicrosoftAjax.js

This dependency causes the add-in to fail in our offline environment.

Could you please advise:

- Is there a supported way to also host and reference MicrosoftAjax.js locally?
- Are there any configuration steps to ensure Office.js does not attempt to load external dependencies?
- Alternatively, is there a bundle that includes all required dependencies?

Any help or guidance on how to fully support offline usage would be greatly appreciated.

**Comment by dejandujak** [comment]
Hi Mark,

Yes, it is possible—our developers have successfully implemented this. I will ask them to share the guidelines with you shortly. Please note that a few elements in the library need to be modified manually.

To the best of my knowledge, this setup works in our solution where the Outlook Add-in is fully installed within an on-premise Exchange environment operating offline. You can also email me on dejan.dujak@elanwave.com

**Comment by mark-office** [comment]
Hi dejan,

Thank you so much for your reply! It’s fantastic to hear that you’ve managed to solve this issue and have the add-in working in a completely offline environment.

I’m very grateful for your support and would love to learn more about the implementation steps or guidelines you followed to achieve this.

Looking forward to your insights.

Thanks, 
Mark

**Comment by dejandujak** [comment]
Hi Mark,

Can you please contact me on dejan.dujak@elanwave.com via email I can send your our solution. 

Kind regards,
Dejan
