### ISSUE TITLE
It's not possible to access `TableRow` items per index.

### ISSUE THREAD

**Issue by timbicker** [OfficeDev/office-js#3858]
It's not possible to access `TableRow` items per index.
 
The following code fails:
```
    const firstTable = context.document.body.tables.getFirst();
    await context.sync();
    firstTable.load("rows/items");
    await context.sync();
    const firstRow = firstTable.rows.items[0];
    firstRow.load("cells/items")
    await context.sync();
```

Error:
```
name: "RichApi.Error"
 code: "ItemNotFound"
 traceMessages: Array[0]
 innerError: null
▶debugInfo: Object
 code: "ItemNotFound"
 message: "ItemNotFound"
 toString: function toString()
 errorLocation: "TableRowCollection.getItem"
 statement: "var row = rows.getItem(...);"
▶surroundingStatements: Array[6]
 0: "var v = context.root._getObjectByReferenceId("02F!00000689");"
 1: "var rows = v.rows;"
 2: "// >>>>>"
 3: "var row = rows.getItem(...);"
 4: "// <<<<<"
 5: "row.load(["cells/items"]);"
▶fullStatements: Array[1]
 httpStatusCode: 404
 data: undefined
```

## Example & reproduce with Script Lab
[Example Gist](https://gist.github.com/timbicker/a212ca6e9975ab55e75dcb6315a13326)
You can create the table and then click "Get cell content".

**Comment by jipyua** [comment]
hi @timbicker thanks for letting us know this error, it sounds like there are some errors with the original code, please comment the first "await context.sync()" and it will be working. The refined code is somthing like below:

    const firstTable = context.document.body.tables.getFirst();
    //await context.sync();
    firstTable.load("rows/items");
    await context.sync();
    const firstRow = firstTable.rows.items[0];
    firstRow.load("cells/items")
    await context.sync();
