### ISSUE TITLE
Office.context.mailbox.getSelectedItemsAsync returns invalid item ids when selecting multiple messages in a conversation 

### ISSUE THREAD

**Issue by ottD** [OfficeDev/office-js#3859]
# `Office.context.mailbox.getSelectedItemsAsync` returns invalid item ids when selecting multiple messages in a conversation 
In Outlook on the web (and new Outlook Desktop), `Office.context.mailbox.getSelectedItemsAsync` returns different item ids for the selected items when multiple items in a conversation are selected compared to selecting a single message within a conversation. This behaviour does not occur in the legacy Outlook Desktop. 

## Your Environment

* Platform:  new Outlook Desktop, Outlook on the web
* Host : Outlook
* Office version number: Microsoft Outlook Version 1.2023.1114.100 
* Operating System: Windows 11
* Browser: Edge, Chrome
 
## Expected behavior

I'd expect `Office.context.mailbox.getSelectedItemsAsync` to return an array of `Office.SelectedItemDetails` with the correct EWS ids for the selected messages regardless whether these messages are in a conversation or not. 

## Current behavior
The EWS ids contained in `Office.SelectedItemDetails[] `returned from `Office.context.mailbox.getSelectedItemsAsync`  are different for the same items depending on whether one or multiple messages in a conversation are selected. 

## Steps to reproduce

1. Enable conversation grouping in Outlook on the web
2. Invoke Outlook add-in and select a single message  in a conversation. Note that correct EWS id is returned.
3. Select multiple messages in a conversation and note that instead of the correct EWS id, the selected items have an id of the following format: `<{GUID}@{id.emailprovider.com}>`

## Link to live example(s)
See attached outlook add-in: 
[item_multi_select_repro.zip](https://github.com/OfficeDev/office-js/files/13454803/item_multi_select_repro.zip)

I'm unable to provide a Script Lab link due to Script Lab being broken in OWA (see https://github.com/OfficeDev/script-lab/issues/1037 ) 

## Context

I'm trying to build an Outlook add-in that processes the selected items using their ids. The EWS ids are converted to REST ids for further processing with Graph after using [convertToRestId](https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-preview#outlook-office-mailbox-converttorestid-member(1)). This fails if the returned ids are not valid EWS ids. 

## Useful logs

[x] Screenshots

Correct item id is returned when conversation header is selected: 
<img width="512" alt="header" src="https://github.com/OfficeDev/office-js/assets/33263347/f78bd373-2ce5-4405-970b-e82da4151e34">

Correct item id is returned when first message is selected: 
<img width="534" alt="fw test email" src="https://github.com/OfficeDev/office-js/assets/33263347/729cc5e4-c644-48ca-9242-e99d00b547bc">

Correct item id is returned when second message is selected: 
<img width="528" alt="test email" src="https://github.com/OfficeDev/office-js/assets/33263347/62553400-358c-4eaf-ba36-30f3d40cae16">

Different item ids are returned when both messages in the conversation are selected:
<img width="541" alt="issue" src="https://github.com/OfficeDev/office-js/assets/33263347/a9bacdf4-a116-485e-9531-539a8f5572cb">

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding multi-select on OWA. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office [4128080]

**Comment by elegault** [comment]
I'm perplexed how you are even able to process multiple messages - it is broken for myself and others, although in issue #3800 I am seeing a slightly different problem than the poster.

**Comment by CameronDwyer** [comment]
I'm also struggling with this issue and inconsistent handling of selection.

**Comment by exextoc** [comment]
This issue has been fixed. Please reopen if you are still getting this issue in latest OWA.

**Comment by ottD** [comment]
This issue has re-appeared in the latest OWA (and new Outlook). When selecting multiple emails in a conversation, `Office.context.mailbox.getSelectedItemsAsync` returns empty ids for the selected emails. The reproduction steps are the same as described initially.

When selecting a single email in a conversation `Office.context.mailbox.getSelectedItemsAsync` returns the expected data:
<img width="845" alt="image" src="https://github.com/OfficeDev/office-js/assets/33263347/e7ca04f3-24c3-48aa-8306-fd2893b6b0d7">

When selecting two emails in a conversation `Office.context.mailbox.getSelectedItemsAsync`  returns empty ids and no subjects:
<img width="584" alt="image" src="https://github.com/OfficeDev/office-js/assets/33263347/88973857-05e8-443f-b0db-24843e1a5db4">
