### ISSUE TITLE
Outlook compose event lost if window popped out too quickly

### ISSUE THREAD

**Issue by barclayadam** [OfficeDev/office-js#3861]
# Provide required information needed to triage your issue

Event-based activation add-ins are not triggered if you pop-out the compose window too quickly (i.e. before the add-in has started running or completed it's work)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows
* Browser (if using Office on the web): Chrome v119
 
## Expected behavior

Event-based activation add-ins can run if the window is popped out

## Current behavior

The event is lost / not triggered due to this race condition. The add-in itself does continue to work with other events, such as recipient changed events

## Steps to reproduce

1. Install an add-in that registers for onCompose event handler
2. Open a new email in OWA
3. Quickly click the pop-out button to create a new window
4. Observe that the add-in does not run / cannot complete

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
Can you share a repro video, it's not a repro for us ?
Also, how consistent is the repro, does it happen always ?

**Comment by barclayadam** [comment]
Hopefully, the below can give you a better understanding of what we are seeing. You can see that a signature is always added if we let the window sit, but if we pop-out the window no signature will be inserted.

This is pretty much 100% reproducible for us, at least using our add-in.

https://github.com/OfficeDev/office-js/assets/973909/7d0a2d64-6d82-430e-abaa-2747c4390f7c

**Comment by ajays-msft** [comment]
@barclayadam - Are you using OnNewMessageCompose or OnMessageCompose?

**Comment by barclayadam** [comment]
We are using OnNewMessageCompose. 

Our manifest is available at https://outlook.signature365.com/manifest.xml

**Comment by ajays-msft** [comment]
@barclayadam - When you popout, do you consider it a new message or a message that was once created, and then re-opened? Can you try using the OnMessageCompose instead?

There are few reasons I think this may have happened.
1) Message was popped out before the addins are initialized in the first compose window
2) Message was popped out after addin is initialized, but before the addin can complete handling on the compose event.

Either way, seems like a timing issue.

**Comment by barclayadam** [comment]
I was not even aware there was an `OnMessageCompose` event :) It does not quite fit our purpose, although I could try it if necessary.

If events have not triggered yet, which is what I believe is happening here from our logs, I would still consider the pop-out as a new message as nothing has yet happened.

From an add-in POV there is no way of knowing the details as this is a UI function and should not be affecting the underlying model, so I would expect one of two things to happen:

 - The window is popped out **before** the add-in is started: Run the add-in event handlers once popped out
 - The window is popped out **during** the add-in event handler: Give it time to run to completion

**Comment by exextoc** [comment]
@barclayadam on OWA, OnMessageCompose will be triggered on creating a new mail and when the mail is popped out.
Pease try this out and let us know if this can be used by your Add-in.
