### ISSUE TITLE
Outlook: Using setSignatureApi with "Resend This Message" functionality duplicates the signature

### ISSUE THREAD

**Issue by barclayadam** [OfficeDev/office-js#3862]
# Provide required information needed to triage your issue

If an add-in uses the setSignatureAsync method in a message compose event it will be triggered when attempting to resend a message using Outlook menu and duplicate, instead of replacing the signature:

![image](https://github.com/OfficeDev/office-js/assets/973909/8a714d8b-fbfb-479d-b22e-653aebe2a7c3)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.16827.20278
* Operating System: Windows
 
## Expected behavior
That setSignatureAsync will override the existing signature, as if we are still composing the same message. We cannot replicate Outlook duplicating the signature using native signatures, although assumption here is that natively Outlook simply does not trigger the "insert signature" functionality.

If Outlook's APIs will not support this feature, is there a method of identifying that the add-in is being run in this "Resend This Message" mode?

## Current behavior
Signatures are duplicated.

## Steps to reproduce

1. call SetSignatureAsync in a message compose add-in
2. Create and send an email with the sig inserted
3. "Resend This Message"
4. Note duplicated signature

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ztcdsb** [comment]
@barclayadam Thanks for reporting the issue. Unfortunately I am not able to repro it with steps above. 

It will be helpful if you can offers a video record as well as the a sample sig add-in.

**Comment by ztcdsb** [comment]
Thanks for reporting this issue. After careful consideration, our team has decided to not fix this issue in the short term. We recommend you to upvote or create a new [Tech Community](http://aka.ms/M365dev-suggestions) item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue we will re-activate as needed.
