### ISSUE TITLE
Can an Office Add-in be displayed in multiple Office tabs?

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#3863]
I want to display my add-in in multiple Office tabs. [Link to Microsoft Docs](https://learn.microsoft.com/en-us/javascript/api/manifest/officetab?view=common-js-preview)

Is it possible to do that?

For example, display the add-in in TabDesign and TabHome.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: [Word, PowerPoint]
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior
Addin can be shown in multiple Office Tab

## Link to live example(s)
expect manifest to work:
```
<ExtensionPoint xsi:type="PrimaryCommandSurface">
      <OfficeTab id="TabHome">
         <Group id="MyGroupHome">
                ...
         </Group>
      </OfficeTab>
      <OfficeTab id="TabDesign">
          <Group id="MyGroupDesign">
                ...
         </Group>
      </OfficeTab>
</ExtensionPoint>
```

or
```
<ExtensionPoint xsi:type="PrimaryCommandSurface">
      <OfficeTab id="TabHome">
            <Group id="MyGroupHome">
                ...
         </Group>
      </OfficeTab>
</ExtensionPoint>
<ExtensionPoint xsi:type="PrimaryCommandSurface">
      <OfficeTab id="TabDesign">
        <Group id="MyGroupDesign">
                ...
         </Group>
      </OfficeTab>
</ExtensionPoint>
```

**Comment by Rick-Kirkham** [comment]
@jasonhieu1905 Thanks for your interest in Office Add-ins. We use the issues in this repo to report and track probable bugs in the platform. Programming questions like yours should be made on either StackOverflow (tag it "office-js") or [M365 Q&A](https://learn.microsoft.com/en-us/answers/questions/) (tag it "office-addins-dev"). Before you do that, however, try both of your suggested manifests and see if it works.

**Comment by jasonhieu1905** [comment]
@Rick-Kirkham: I've tried both but does not working for me, there is no mentioned here the limitation of the OfficeTab with extension point, can you please check?
https://learn.microsoft.com/en-us/javascript/api/manifest/officetab?view=common-js-preview

**Comment by jasonhieu1905** [comment]
@Rick-Kirkham : work for me when doing centralized deployment. closed the question.
