### ISSUE TITLE
Addin not loading in new outlook client

### ISSUE THREAD

**Issue by jdamen** [OfficeDev/office-js#3865]
I've created an outlook addin that works fine with the classic outlook / 365 email clients. However, it doesn't load  in the "new"outlook client.

## Your Environment

* Platform PC desktop
* Outlook version number: Microsoft Outlook Version 1.2023.1114.100 (Production). / Client Version is 20231117004.10 .
* Operating System: Win11 Home

## Expected behavior
The the classic outlook, the addin works fine: (in Dutch.. btw)
![image](https://github.com/OfficeDev/office-js/assets/10115705/1cf15340-a7c9-486b-9a22-97ecb3a89a60)
the panel pops up and works as expected
![image](https://github.com/OfficeDev/office-js/assets/10115705/967e069c-a185-4707-a2fc-3da9b85fc766)

## Current behavior
In the new outlook email client, the addin should open when click on the action 
![image](https://github.com/OfficeDev/office-js/assets/10115705/dbb09cfb-c0ca-40b6-9e13-6b8d40ef36da)

but we get:
![image](https://github.com/OfficeDev/office-js/assets/10115705/8c6eb0cb-c608-43ae-a749-8b53ce16cbce)

# Provide additional details
1. The manifest is attached. [outlook-manifest.zip](https://github.com/OfficeDev/office-js/files/13480571/outlook-manifest.zip)

What goes wrong ? And how can I see details of the error ?

Regards,
Johan Damen

**Comment by exextoc** [comment]
Thanks for reporting this issue. We are able to repro this and it has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: 246451

**Comment by DivyaPatidar** [comment]
@jdamen Looks like add-in is not loading because of the `X-Frame-Options` being set to `same-origin` by the website at 'https://www.digitalworkmate.com/'.  To address this issue, you may refer to the guidelines on [Addressing same-origin policy limitations in Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/addressing-same-origin-policy-limitations).
