### ISSUE TITLE
Appending Document one by one with bytes(base64) using document.insertFileFromBase64 Formatting(Alignment ,Spacing etc.) getting distrubed.

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#3867]
Hello Team,
I am using Word API for developing word add-in. I have used document.insertFileFromBase64 method for opening existing document that time I found Formatting issue.

My Environment
Platform : PC desktop
Host: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2304 Build 16.0.16327.20200) 64-bit
Operating System: Windows 10 pro

I have 6 document if I open them using bytes individual then it's opening correctly and formatting also getting proper.
But I want to it open in one word document for that I am appending document one by one using document.insertFileFromBase64 method Here is my Code snippest:-
Basically I am merging documents one by one using bytes I am sending bytes in this function .

var isFirstTime  =0;
async function ReplaceWordDocumentForWordPreview(data) {
    var startIndex = -1;
    data = this.result;
    startIndex = data.indexOf("base64,");
    var mybase64 = data.substr(startIndex + 7, data.length);
    await Word.run(async function (context) {
        if (isFirstTime  == 0) { // first document will  replace current data and other will added at end in else
            context.document.insertFileFromBase64(mybase64, "Replace", {
                importTheme: true,
                importStyles: true,
                importParagraphSpacing: true,
                importPageColor: true,
                importChangeTrackingMode: true
            });
            await context.sync();
            isFirstTime = 1;
        }
        else {
            context.document.insertFileFromBase64(mybase64, "End", {
                importTheme: true,
                importStyles: true,
                importParagraphSpacing: true,
                importPageColor: true,
                importChangeTrackingMode: true
            });
            await context.sync();
        }
    });
}

As per my observation first document is uploaded that time its output is proper but after all section is append after that its formatting is getting change. Because of that code behaviour.(Context.sync() is appling formatting to whole documents.)

Here is my source documents
[sec1.docx](https://github.com/OfficeDev/office-js/files/13486199/sec1.docx)
[sec2.docx](https://github.com/OfficeDev/office-js/files/13486201/sec2.docx)
[sec3.docx](https://github.com/OfficeDev/office-js/files/13486202/sec3.docx)
[sec4.docx](https://github.com/OfficeDev/office-js/files/13486205/sec4.docx)
[sec5.docx](https://github.com/OfficeDev/office-js/files/13486206/sec5.docx)
[sec6.docx](https://github.com/OfficeDev/office-js/files/13486208/sec6.docx)

OutputFile
[output.docx](https://github.com/OfficeDev/office-js/files/13486225/output.docx)

Expected Output
<img width="931" alt="Err" src="https://github.com/OfficeDev/office-js/assets/133626379/98d04be2-63cc-41e0-a8c2-39ec3c629da7">

**Comment by Jayshiv-IRIS** [comment]
Hi team,
Is there anything Update about this?

**Comment by zhenhuangMSFT** [comment]
@Jayshiv1408Dev Sorry for the delay. @jipyua is looking into this.

**Comment by jipyua** [comment]
hi @Jayshiv1408Dev, thanks for reaching out and reporting this. I noticed that you are using all the import options as true, this will use the document level formatting of the source document each time you call document.insertFileFromBase64() API. So if the 6 documents have different following settings, then only the last document's following setting will be applied. Note that in the target doucment, we can only have one copy of the following settings. Would you please check whether this is the case that the 6 documents have different following settings?

importTheme: true,
importStyles: true,
importParagraphSpacing: true,
importPageColor: true,
importChangeTrackingMode: true

**Comment by Jayshiv-IRIS** [comment]
Yes we have Different Following settings. So in this  case what we can do? For  retaining each document formatting.

**Comment by jipyua** [comment]
hi @Jayshiv1408Dev  sorry for the late response. You can't maintain 6 copies of different theme/styles/pagecolor... settings in 1 final document. You can decide which of the 6 settings is you want to keep and only pass "true" to import that one to target document and pass "false" for others.
