### ISSUE TITLE
How to set the Summary Grouping position for a Worksheet in Office-js

### ISSUE THREAD

**Issue by theboyknowsclass** [OfficeDev/office-js#3868]
## Post how-to questions about your code on Microsoft Q&A

How do i to set the Summary Grouping position for a Worksheet in Office-js?

this doesn't seem to be available in the API?

We have several forums where you can ask the developer community questions about your code. Try one of the following forums to ask technical questions about:
- [Developing Office Add-ins for Word, Excel, PowerPoint, Outlook, Project, Visio, and OneNote](https://docs.microsoft.com/answers/topics/office-addins-dev.html)
- [Access programming in Office](https://docs.microsoft.com/answers/topics/office-access-dev.html)
- [Developing COM or VSTO Add-ins for Office](https://docs.microsoft.com/answers/topics/office-vsto-com-dev.html)
- [Office JavaScript API](https://docs.microsoft.com/answers/topics/office-js-dev.html)
- [SharePoint and OneDrive development](https://docs.microsoft.com/answers/topics/sharepoint-dev.html)
- [Deploying and publishing Office or SharePoint apps to AppSource](https://docs.microsoft.com/answers/topics/microsoft-365-apps-publishing-dev.html)

For additional information about JavaScript programming, see the [JavaScript at Microsoft](https://docs.microsoft.com/javascript/) community hub.

**Comment by exextoc** [comment]
Hey @theboyknowsclass 

Can you elaborate more on your question ? What is your target platform ?
