### ISSUE TITLE
Issue while inserting HTML on OWA with empty body

### ISSUE THREAD

**Issue by marcoartaviaq** [OfficeDev/office-js#387]
When I try to insert HTML while composing an email on OWA, using the setSelectedDataAsync, the HTML does not inserts on the email if the email body is empty

## Expected Behavior
The custom HTML being inserted on the email

## Current Behavior
The HTML is not being inserted if the email has an empty body. If we write anything on the email body, the custom html is inserted just right.

This happens only on OWA. In outlook for Mac or Windows works fine.

* Additional details:
  
  1. Insert HTML data with the Office.context.mailbox.item.body.setAsync() method
  2. On OWA

## Context
I try to insert a link inside the email, but in OWA if the body is empty the link is not inserted, and our clients get lost

## Your Environment
* Platform
  Office online
* Host
  Outlook
* Browser
  Chrome

**Comment by exextoc** [comment]
@marcoartaviaq I tried with both the APIs you have mentioned in the post and am able to insert HTML data. Can you please provide the exact code you have used here ?
