### ISSUE TITLE
Excel Web Addin. When opening up an excel sheet with addin formulas already in it, the formulas get corrupted unless we manually reload the addin.

### ISSUE THREAD

**Issue by sk1136** [OfficeDev/office-js#3872]
## Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: One Drive
* Host [Excel, Word, PowerPoint, etc.]: Excel 365
* Office version number: Latest
* Operating System: Windows 10 and Windows 11
* Browser (if using Office on the web): N/A
 
## Expected behavior
When the excel opens up, the web addin should load and run the formulas. 

## Current behavior
Instead the formulas are corrupted and aren't fixed until we manually reload the addin. We have to do this every time we reopen the excel file from One Drive. This is unusable for our users with this workflow.

Proper formula name: ABC.GET_PB_OPT_ORDER_ANALYSIS()
Corrupted name: BloombergUI.xla!_xldudf_ABC_GET_PB_OPT_ORDER_ANALYSIS()

## Steps to reproduce
1. Create custom functions with your web addin
2. Save the excel sheet in one drive
3. Reopen the file. Formulas should be corrupted

## Link to live example(s)
1. Can't provide live access. This is proprietary code.
2. 
# Provide additional details

## Context
The users can't use our web addin if they need to manual reload the addin everytime we reopen excel file.

## Useful logs
None

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by sk1136** [comment]
we are referring to custom functions (functions.ts) when we say formulas.

**Comment by donlvMSFT** [comment]
Hi @sk1136 , I think you are mentioning the same issue you reported in #2051 . 

We have created an internal task 8561517 to follow-up. Will update here once we got any progress.

**Comment by donlvMSFT** [comment]
Hi, 

The fix already released to CC(preview) version, please check if you are on Insider and Office version >=16.0.17126.20064. 
With this fix, you should install the add-in once again, and after that, reopen the file should not see .xla(m)!_xldudf_.
If you have the correct version, please help validate the behavior.

Thanks.

**Comment by sk1136** [comment]
hi @donlvMSFT  thank you. we will get the insiders version tomorrow, happy to test it.
Any ETA on when this will be rolled out in production.

**Comment by XuanZhouMSFT** [comment]
@sk1136 Thanks for the waiting. The fix should already in production for several months.
I will close this issue now. Please let us know if still have the problem and we will reopen it.
