### ISSUE TITLE
No supported Office Products. Problem with validating the manifest.xml

### ISSUE THREAD

**Issue by hmuris** [OfficeDev/office-js#3873]
Hello, 

We are building an Outlook addin, and now we are facing the problem of publishing this addin over the Office admin page.
Here is a similar if not the same problem described in SharePoint addin development.
[SharePoint bug](https://github.com/SharePoint/sp-dev-docs/issues/5125)

This is what we get when we try to add the addin over the Office admin page.
![image](https://github.com/OfficeDev/office-js/assets/5045824/99d6cff2-b8d5-4b72-9f5f-3c437aed59d7)

If I try to validate the manifest using the office-addin-manifest, `npx office-addin-manifest validate manifest.xml` I get this result:
![image](https://github.com/OfficeDev/office-js/assets/5045824/c2bafac4-8a2a-4be6-8138-b916b8e8bce1)

Imporant to mention is if same addin is added directly to the user mailbox over the Add Add-ins button everything is working just fine. Lately is this button gone, but we have found in some article that this window is still available over [this link](https://aka.ms/olksideload) 

Here is my manifest.

Please advise what to do.

**Comment by exextoc** [comment]
Hey @hmuris 

In the manifest, Host Name should be made to Mailbox rather than MailHost. It was throwing an error due to the same. 

```
<Hosts>
    <Host Name="MailBox"/>
</Hosts>
```

**Comment by hmuris** [comment]
That was it. Thank you.
![image](https://github.com/OfficeDev/office-js/assets/5045824/9330ac1e-83fb-4dee-b9f8-68d456758123)
