### ISSUE TITLE
Cannot change visibility of Excel range name to false

### ISSUE THREAD

**Issue by jkpieterse** [OfficeDev/office-js#3878]
Using script lab on Windows 10 desktop Excel 365 app (current channel, updated).

I am trying to work with Excel range names. Most of this I got working, but there is one thing that I cannot get to work: set visibility of a name to false (the visibility of the name itself, not of the range it points to!):

```
let namedItem = context.workbook.names.getItemOrNullObject("test");
namedItem.visible = false;
await context.sync();

```
After running the above snippet (no errors), the name "test" remains visible. What gives???

If a name is hidden (using VBA, ActiveWorkbook.Names("test").Visible = False), I can use office-js to set the visible property to true and it indeed makes that name visible again. Why can’t I do the other way around?

Another oddity is that you can hide a name immediately after creating it:

```
let nameName = "OtherTest";
let refersTo = "=1";
namedItem = context.workbook.names.add(nameName, refersTo);
await context.sync();
if (!namedItem.isNullObject) {
  namedItem.visible = false;
  await context.sync();
  }
```
So why can't I do that using the first code snippet?

I have a private gist with the code to repro this, please get in touch so I might share it with the team.

**Comment by jkpieterse** [comment]
Cross-posted: Same issue also mentioned here:
https://stackoverflow.com/questions/77571887/cannot-change-visibility-of-excel-range-name-to-false

**Comment by penglongzhaochina** [comment]
Hi @jkpieterse , I can't repro your issue.

I created a namedRange which is "data" from Ribbon-> Formulas-> NameManager
![image](https://github.com/OfficeDev/office-js/assets/106959323/a49e8c5c-e543-42ca-afec-a9c29f5ea57f)
After I run your first snippet the "data" NamedRange just gone.
![image](https://github.com/OfficeDev/office-js/assets/106959323/7638bcde-6be6-4ea0-afa0-2735ba821dfb)
![image](https://github.com/OfficeDev/office-js/assets/106959323/5271d1d4-40e4-44b0-bebe-14f81dc5ac0c)

**Comment by XuanZhouMSFT** [comment]
Close this issue as stale.
Please feel free to leave comments if you have any updated information or concerns.
