### ISSUE TITLE
[Word] Ranges have no shading and highlight colours are a lacking alternative

### ISSUE THREAD

**Issue by RXminuS** [OfficeDev/office-js#388]
I would like to be able to set the background color of a piece of text by using Range.set({style: ...}). However, the only option available is highlightColor. Which is inconsistent between platforms, in Office online the full RGB spectrum is supported...but on Desktop only 12 colors are supported and my RGB shades are thus clipped.

This could be solved if we were allowed to set a shadingColor instead which does seem to support full RGB.

## Expected Behavior
Allow background color of a Range to be set to any RGB value using 
```js
Range.set({style: {highlightColor: "#00FF00"}})
```

## Current Behavior
Colors are clipped to the available highlight colors on certain platforms.
![image](https://user-images.githubusercontent.com/3949285/52786687-d11ce600-305b-11e9-9512-a7109495df29.png)

## Steps to Reproduce, or Live Example
Try setting a range highlight color.

## Context
We're trying to highlight some important data points in a document by using several colors. The problem is that setting a text color doesn't always show since some of the points we want to highlight are just whitespace.

**Comment by dmahugh** [comment]
Thanks for the feedback, @RXminuS . As you noted, this isn't supported presently, but you can submit a feature request on [User Voice](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback) and others will be able to upvote it there. The engineering team looks to User Voice voting to help prioritize new features, so that's the best place to submit feature requests.

**Comment by RXminuS** [comment]
But then isn't it a bug? Because right now you take in an RGB value but really it should be one of the predefined color value names.

**Comment by RXminuS** [comment]
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/17326312-support-custom-colors-for-highlightcolor-in-word
