### ISSUE TITLE
New Teams Addin does not appear in Old Outlook

### ISSUE THREAD

**Issue by FPFrank01** [OfficeDev/office-js#3880]
# Provide required information needed to triage your issue

We have a dilemma with users who decided to use the new Teams but still prefer the older Outlook. The Teams Meeting addin does not appear in the ribbon.
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2310
* Operating System: W10P
* Browser (if using Office on the web): n/a
 
## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by zhngx1** [comment]
Thanks for reporting the issue. Do you have a more detailed repro steps?
