### ISSUE TITLE
code doesn't really reflect what gets published to the evergreen CDN - data types (valuesAsJson) not working

### ISSUE THREAD

**Issue by eElor** [OfficeDev/office-js#3881]
# Provide required information needed to triage your issue

from the repo description:

> The NPM package for Office.js is a copy of what gets published to the official "evergreen" Office.js CDN, at https://appsforoffice.microsoft.com/lib/1/hosted/office.js.

This seems not to be completely true. E. g. 
- https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js **1.4MB**, while npm version **1.3MB** (@microsoft/office-js
1.1.89).

Using the npm version leads to missing functionality. I was especially struggling to get data types working in excel with the npm version of the js code. Exchanging the above mentioned js file with the one from the CDN solved my problem.

This is however not a good workaround, since the add-in should be also consumed by other systems (e. g. office 64 bit) and since installing the application in different systems (dev, test, prod) would require exchanging the named file every time. Additionally, there might be other functionality missing, which I'm not aware of.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: laptop, Windows 10 Enterprise
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2309 Build 16.0.16827.20278) 32-bit 
* Operating System: windows, wsl 2
* Browser (if using Office on the web): ms edge
 
## Expected behavior

Add-ins should work the same way as if pulling the js code from the cdn.

## Current behavior

Missing functionality, specially when working with data types. E. g. getting "valuesAsJson" leads to an undefined result. After exchanging the file mentioned above, the same add-in code returns the expeted "valuesAsJson" result

## Steps to reproduce

- Install office-js with npm (npm i @microsoft/office-js) 
- Create an add-in, e. g. by pulling a copy of code from tutorial or script lab.
- Crate objects using valuesAsJson - e. g. following the data type tutorial from microsoft (cards)
- Note that the add-in won't work, since code for working with data type entites is missing
- Exchange the excel-win32-16.01.js within the node module (@microsoft/office-js/dist/excel-win32-16.01.js) with the one from the CDN: https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js
- Try running the same add-in. This time, valuesAsJson will work as expected

```javascript
Excel.run(async (ctx) => {
// .... 
  const table = ctx.workbook.tables.getItem(tableName);
  const x = table.columns.getItem(colname).getDataBodyRange()
  x.load("valuesAsJson");

  await ctx.sync();
  console.log(colv.valuesAsJson)
// ....
})
```

## Link to live example(s)

https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-data-types-entity-card

https://github.com/OfficeDev/Office-Add-in-samples

## Context

I would like to work with excel data types and set objects and their attributes in single cells.

**Comment by donlvMSFT** [comment]
Hi @eElor ,

I tried using the same code with `yo office` tool generating an Add-in and it seems works fine with the Office.js. Also, I tried the Script Lab sample directly, it works. Do you have validated using these?

I think you are working on Win32, could you clear the cache and take another try? [Clear cache](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#clear-the-office-cache-on-windows)

**Comment by eElor** [comment]
Hi @donlvMSFT,

thank for looking at the ticket :)

> [...] could you clear the cache and take another try? [Clear cache](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#clear-the-office-cache-on-windows)

Clearing the cache has no effect on the problem.

> I think you are working on Win32

Correct. In our company we have developed tools with VBA that are not compatible with Win64. For the moment, we'll have to stick to Win32.

> I tried using the same code with yo office tool generating an Add-in and it seems works fine with the Office.js. Also, I tried the Script Lab sample directly, it works. Do you have validated using these?

I've already ran many examples using `yo office` and  script lab. They all work fine on my system, too. The problem is encountered when **not using the CDN**, i. e. adding following line to the html:

```html
<!-- my html file, e. g. index.html -->
<!-- ... -->
<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
<!-- ... -->
```

but using the files from npm hosted on this repo, i. e.

```sh
# terminal; run within project root
npm install @microsoft/office-js --save
```

```html
<!-- my html file, e. g. index.html -->
<!-- ... -->
<script src="/path-to-my-local-assets/office-js/office.js"></script>
<!-- ... -->
```

The problem is resolved when using the CDN version of `excel-win32-16.01.js` (e. g. `curl`ing it into the npm directory where this repo was downloaded (`node_modules/@microsoft/office-js/...`).

As mentioned above, the content of the two files (cdn vs npm versions) seem not to be the same:

> https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js 1.4MB, while npm version 1.3MB (@microsoft/office-js
1.1.89).

It doesn't make sense for me to diff both files, but the difference in size and functionality speak for in favor of it.

The examples provided above ( Link to live example(s) ) were only added to test working code (which uses the CDN). May I ask you to exchange the CDN with the npm link as mentioned above and in the [README](https://github.com/OfficeDev/office-js/blob/release/README.md) of this repo and confirm that the code you tested is still working in your system? This means removing any script containing cdn links (`<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>`) and exclusively using the npm repo files. If the code still works on your system, and since I suppose you use the 64 bit version, it is possible that the only file that might not be reflecting the evergreen version is the 32 bit version (`excel-win32-16.01.js`).

**Comment by eElor** [comment]
Hi @donlvMSFT, hi @penglongzhaochina, 
may I ask, if you found time to have a look at my last comment? Were you able to correctly use `valuesAsJson` employing the npm files exclusively?
Best regards

**Comment by eElor** [comment]
Hello again Hi @donlvMSFT and @penglongzhaochina,
today I just tested my application on excel web. The same problem is present when working with `valuesAsJson` using the npm files.
Again, with `https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js` `valuesAsJson` is available on the respective objects while with `<...>/assets/node_modules/@microsoft/office-js/dist/excel-web-16.00.js` it is not. The file size also differs among the two with 1.4 MB against 1.5 MB, respectively. 
The problem seems not to be due to the excel version, but due to missing code in the npm scripts. May I ask you to forward this issue to one of MS developers compiling/bundling the npm assets, so they include the missing code? Thank you in advance.

**Comment by donlvMSFT** [comment]
Hi @eElor , thanks for the more details, we're working with internal team, will update back here if find anything.

**Comment by donlvMSFT** [comment]
Hi @eElor , we 're revisit this issue and as new npm versions already released, could you help confirm whether you're still hitting this?

**Comment by donlvMSFT** [comment]
Based on our validation, this issue should no longer exist in latest npm versions, so close this thread.
