### ISSUE TITLE
Incoming/outgoing message identification

### ISSUE THREAD

**Issue by kbrilla** [OfficeDev/office-js#3883]
I'm trying to find a way to identify incoming/outgoing messages. They both open ReadMessage taskpane but I could not find a clean way to distinguish between them other than by sender's email.
But this does not work if message is send to yourself for any reason. 

Only even more dirty hack provided in https://learn.microsoft.com/en-us/answers/questions/436533/office-js-outlook-how-to-check-if-email-is-incomin

What is proper way to do it?

**Comment by exextoc** [comment]
Below is an example of how to achieve that using Outlook APIs.

```
let item = Office.context.mailbox.item;
let userEmail = Office.context.mailbox.userProfile.emailAddress;

if (item.sender.emailAddress === userEmail) {
    if (item.to.some(recipient => recipient.emailAddress === userEmail)) {
        console.log('This is an email the user sent to themselves:', item.subject);
    } else {
        console.log('This is an outgoing message:', item.subject);
    }
} else {
    console.log('This is an incoming message:', item.subject);
}

```
In this code, we first check if the email is from the user. If it is, we then check if the user is also a recipient of the email. If they are, we log that the email is one the user sent to themselves. If they're not, we log that the email is outgoing. If the email is not from the user, we log that it is incoming.

**Comment by kbrilla** [comment]
Not exacly, this is the dirty workaround I was talking about that does not work.
We still does not know if the message is from 'incoming' or 'outgoing' folder. Both will print: 'This is an email the user sent to themselves:' 
Look: 
1. we have one message with label `send` in folder `send`: (Wysłane is polish for sent')
<img width="94" alt="image" src="https://github.com/OfficeDev/office-js/assets/22288449/3af27116-b473-4a06-a636-f580b396dd59">
 and method prints: `This is an email the user sent to themselves`

2. we have the same message but after reciving with `incoming` label in folder `incoming`: (Skrzynka odbiorcza is polish for recived messages') 

<img width="112" alt="image" src="https://github.com/OfficeDev/office-js/assets/22288449/9fae8eed-8107-4fce-a16e-db87f7332e92">
and method prints: `This is an email the user sent to themselves`

So both of them are recognized as message to yourself but does not say if it is in 'Sent' or 'Recived';
<img width="200" alt="image" src="https://github.com/OfficeDev/office-js/assets/22288449/02b28f3e-019a-47b6-ae57-f4e40fa1039b">

**Comment by ajays-msft** [comment]
You can try using graph API to get the email by Id, and check for receivedDateTime or sentDateTime. Hope this helps. You can adjust your logic accordingly.

https://learn.microsoft.com/en-us/graph/api/message-get?view=graph-rest-1.0&tabs=javascript
