### ISSUE TITLE
How to distinguish between delegated mailbox and shared mailbox using Office JS APIs or MS Graph APIs?

### ISSUE THREAD

**Issue by diksha22002414** [OfficeDev/office-js#3884]
We are developing an Office Add-in and need to identify the type of mailbox being accessed by the add-in, specifically distinguishing between delegated and shared mailboxes. Currently, we use the following Office JavaScript API code snippet: 
```
Office.context.mailbox.item.getSharedPropertiesAsync(function (result) {
          if (result.status === Office.AsyncResultStatus.Succeeded) {
            // Access shared properties from result.value
            console.log(result.value);
          } else {
            // Handle error
            console.error(result.error.message);
          }
        });

response {{delegatePermissions: 63, owner: <shared mailbox email id>, targetRestUrl: "https://outlook.office.com/api", targetMailbox: <shared mailbox email id>}}
```

This approach helps us identify whether the mailbox is a shared/delegated mailbox or personal mailbox. However, we want to know if there are similar methods or properties in the Office JavaScript API or Microsoft Graph API that allow us to distinguish between delegated and shared mailboxes.

**Comment by ajays-msft** [comment]
The parentFolderId for delegate mailbox will be same as the user's own mailbox parentFolderId. For shared mailbox, the folderid will be a different one. You can use MS graph api and adjust your logic accoordingly.

https://learn.microsoft.com/en-us/graph/api/user-list-mailfolders?view=graph-rest-1.0&tabs=http

**Comment by diksha22002414** [comment]
Thank you for your response. We will verify this solution on our systems and get back to you ASAP if we have any questions regarding the same.

**Comment by diksha22002414** [comment]
Hi. I have verified this with my Graph APIs. I verified it with
GET https://graph.microsoft.com/v1.0/users/<delegatedmailboxid>/mailFolders/inbox the parentfolderID for this response is different from that of parentFolderID of GET https://graph.microsoft.com/v1.0/me/mailFolders/inbox 

As you had mentioned the parentFolderid for the shared mailbox and personal mailbox are different. Please let me know if there is anything else that I can check. Or is there any other way to get this distinction.

**Comment by ajays-msft** [comment]
@diksha22002414 - 

Thank you for the confirmation.

As a guidance, this forum is limited to support office js issues for outlook, and if you have additional queries related to Microsoft Graph, please feel free to get help from Microsoft 365 developer portal.
