### ISSUE TITLE
Add styles from docx file to Word Online get error thrown.

### ISSUE THREAD

**Issue by hxltinh** [OfficeDev/office-js#3885]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Word on Web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Web
* Operating System: Web
* Browser (if using Office on the web): Chrome, Safari, Edge, Firefox
 
## Expected behavior
get styles from source docx file always get style item has has nameLocal = 'Table Normal'.
it should not throw any error over style that has nameLocal = 'Table Normal' or a solution to prevent this.

## Current behavior
- Create a document with Word on Windows
- It will include the "Table Normal" style
- Open Word for Office Online
- Try to create the "Table Normal" style with the style APIs
- it will crash

## Steps to reproduce

1. Open Word on Web
2. Create a document,
3. Open Gist Example in ScriptLab
4. run the script to create "Table Normal" style
5. Observe the error
6. e.g "Table Normalx" works

## Link to live example(s)

1. [link 1](https://gist.github.com/hxltinh/074c40c6cc5aa26e4cad9723e8b4b5f1)
2. ______
3. ______

# Provide additional details

1. check getByNameOrNullObject with style item has nameLocal = 'Table Normal'  return null object. Not sure how this nameLocal is so special.
2. ______
3. ______

## Useful logs

- [ x] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by yilin4** [comment]
@hxltinh This is consistent with the word online UI, because you can't add a table style on the word online, so it's not supported to do so using API.

**Comment by hxltinh** [comment]
@yilin4 do we have an official solution to prevent this from using API? for example: checking if this style is supported by Word Online version? Currently it causes a lot of trouble for us.

**Comment by yilin4** [comment]
@hxltinh Now, for the word online version, only paragraph style and character style can be added. I think you can first check if the style type is character or paragraph, or the style can't be added.

**Comment by hxltinh** [comment]
@yilin4 As you see, even if you change the style type to Paragraph or Character, error still happens.
![Screenshot 2023-12-12 at 16 24 56](https://github.com/OfficeDev/office-js/assets/8114730/9b9868c1-32b2-4a25-b3ba-df1d14522dc8)
![Screenshot 2023-12-12 at 16 39 12](https://github.com/OfficeDev/office-js/assets/8114730/449d975d-f077-4f4d-861b-06e77c55284c)

**Comment by yilin4** [comment]
@hxltinh Sorry to response late. There is a style named "Normal Table" using the same wordId with the style you want to add "Table Normal". So it will work for you to change the style's name. Thank you!
