### ISSUE TITLE
Error getting EWS token

### ISSUE THREAD

**Issue by plamenbotev** [OfficeDev/office-js#3886]
Hello,

I am getting a random error when I try to fetch an EWS token in a shared folder and also in ordinary inbox using the below code:
`Office.context.mailbox.getCallbackTokenAsync({isRest: false}, (res) => {
         console.log(res);
});`

I get a token or the following error:
`name: "GenericTokenError", message: "An internal error has occurred.", code: 9018`

This was working fine a few hours ago for an addin that is globally distributed. Is there any change or a regression that could have caused this?

Best Regards,
Plamen

**Comment by plamenbotev** [comment]
Something that I have noticed is that I can not obtain any token using Office.context.mailbox.getCallbackTokenAsync.
I am noticing, that the issue is observed only on new deployment of the manifest. It is a bit strange, that some users are able to obtain tokens for specific mailboxes but not able to do the same for others.
For example at the moment I am not able to obtain a token for my development mailbox.

**Comment by ajays-msft** [comment]
How did you deploy the manifest?

**Comment by plamenbotev** [comment]
Using global deployment in the admin center.

**Comment by ajays-msft** [comment]
@plamenbotev - The issue is fixed now.

**Comment by prasath-pc** [comment]
I am facing the same problem

**Comment by ivaylomitrev** [comment]
Hi all,

I am also reproducing this today when I was not reproducing it yesterday. Have any changes been made recently to lead to this?
