### ISSUE TITLE
contentControl Delete error because office.js issue.

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js#3887]
I appreciated for contentControl but I am facing a issue when I deleting contentControl this is deleting contentControl only gives error when I was deleting contentControl when contentControl is inside another contentControl for example

`1st contentControl`
   `2nd is inside 1st`
     `3rd is inside second` 
 now `second` is inside `first` and deleting successfully and `third` is inside `second` but when I am trying to delete `third` that was gives error 
 `generalException = "GeneralException`
 
 
![Error Image](https://github.com/OfficeDev/office-js-docs-reference/assets/134502135/657a4471-4bd9-413a-a98e-c877bd737951)

     
this is my code for deleting contentControl with its tag.

`

    async function deleteContentControlByTag(tagToDelete) {
       try {
              await Word.run(async (context) => {
              const contentControls = context.document.contentControls;
              context.load(contentControls, 'items');

              await context.sync();

               // Find the content control with the specified tag
              const contentControl = contentControls.items.find(cc => cc.tag === tagToDelete);

                if (contentControl) {
                  contentControl.delete();
                   await context.sync();
                  console.log('Content Control deleted.');
                } else {
                   console.log('No content control found with the specified tag.');
                 }
            });
         } catch (error) {
           console.error('Error:', error);
       }
     }

     // Call the function to delete the Content Control with the specified tag
    const tagToDelete = 'f4022b4f-f104-4e13-a86c-1f0cc359fbb7';
    deleteContentControlByTag(tagToDelete);

`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 18b63cfd-c1ea-baed-f96f-b14664b384c5
* Version Independent ID: 52aaa0e2-be99-c2e7-3042-fb652420613e
* Content: [Word.ContentControl class - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.contentcontrol.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.contentcontrol.yml)
* Service: **word**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @junaid042,

To summarize, you have three content controls (1, 2, and 3). They are nested in each other like this:
1
>2
>> 3

Is that correct?

When you delete content control 2, does content control 3 stay? Or is it also deleted? 

I am also surprised that your call to [ContextControl.delete](https://learn.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview#word-word-contentcontrol-delete-member(1)) doesn't take a boolean. That `keepContent` parameter isn't optional.

**Comment by junaid042** [comment]
Hi @AlexJerabek 
when I am deleting 2nd contentControl 3rd automatically deleted because 3rd is inside 2nd and I am deleting contentControl and its content. but when deleting 3rd it's mean only 3rd will deleting but that gives error `generalException = "GeneralException`

**Comment by AlexJerabek** [comment]
Okay, so to rephrase this for my own understanding, deleting a content control nested three-layers deep causes an exception to be thrown? Is that correct? 

I'll transfer this issue to the product repo so the bug can be properly investigated.

**Comment by junaid042** [comment]
@AlexJerabek and @penglongzhaochina  please see video for better idea 💡

[ContentControl Error details Video link](https://drive.google.com/file/d/181Q0NAeO21O3lKSykqZYsnzL_Uo_owyC/view?usp=sharing)

**Comment by penglongzhaochina** [comment]
Hi @junaid042 , which platform you met this issue? Desktop or online?

**Comment by junaid042** [comment]
hi @penglongzhaochina I am facing this issue on Desktop, online Word is not good at all not supported lot of functionalities.

**Comment by jipyua** [comment]
hi @junaid042, from the demo video I can't clearly see which one is content contorl and the nested relationship with each other. I prepard a document here with 3 nested content contorls: 
[nested content control.docx](https://github.com/OfficeDev/office-js/files/13608178/nested.content.control.docx)
and then I use the following code in Script Lab to delete them and it's working correctly. (I delete them in reverse order so that the innermost will be deleted first). Can you use this document and scriptlab to describe the issue you hit? Thanks in advance.

 await Word.run(async (context) => {

    var controls = context.document.body.contentControls;
    controls.load();
    await context.sync();
    controls.items[2].delete(false);
    controls.items[1].delete(false);
    controls.items[0].delete(false);
   
    await context.sync();
  }).catch((error) => {
    console.error(error);
  });

**Comment by junaid042** [comment]
thanks you @jipyua 
I used in script lab this is working as @AlexJerabek said **That `keepContent` parameter isn't optional** in my code I am not  using `keepContent` parameter but it works for 1st and 2nd CC Now this is fixed with `keepContent` parameter.

thanks @AlexJerabek , @penglongzhaochina and @jipyua Great work. actually I am a student I don't have experience a lot.

**Comment by junaid042** [comment]
I have this [issue](https://github.com/OfficeDev/office-js/issues/3904) .  dialog parameter issue some one said me on [Stackoverflow](https://stackoverflow.com/q/77473149/22905514) to not use parameter use error number in parameter but this is not a fix.  Can you @jipyua @AlexJerabek check this issue is that possible to fix it.

**Comment by junaid042** [comment]
@jipyua I have one more question if I delete first I don't want to 2nd and 3rd in first deleted not need to delete 2nd and 3rd which are in side first ,I mean delete first but not delete inside first 2nd and 3rd.

**Comment by jipyua** [comment]
@junaid042 then I think you can pass the keepContent parameter with true. feel free to have a try. BTW, seems this post can be closed, if you have separate questions, feel free to open separate tickets.

**Comment by junaid042** [comment]
thanks @yinaa
