### ISSUE TITLE
[PowerPoint] How to know when the presentation is in presentation mode (fullscreen)?

### ISSUE THREAD

**Issue by JSteunou** [OfficeDev/office-js#389]
Cannot find any way reading the API doc, but I can see that the *Web viewer* add-in (from Microsoft Corporation) as a different footer between edition mode & presentation mode, so I'm guessing it is possible to detect it.

Is there a class, an event, something?

**Comment by JSteunou** [comment]
Sorry to bother, I think I have found it in `getActiveViewAsync`, is that right?

**Comment by JuaneloJuanelo** [comment]
yes. you can subscribe to the event when there is a switch between design and presentation mode.
