### ISSUE TITLE
Outlook Web Add-in: How to get the attachment of the original email when reply?

### ISSUE THREAD

**Issue by kiethqa051197** [OfficeDev/office-js#3891]
When replying to emails, the attachment of the original email is not attached to the compose like forward mode, so I can't receive the attachment

**Comment by LuyiH** [comment]
Hi @kiethqa051197 , looks like this is not a question to Office add-in, please kindly post this question to [Microsoft Q&A ](https://review.learn.microsoft.com/en-us/answers/questions/ask/)
