### ISSUE TITLE
Outlook on Windows: HttpOnly cookie set in a dialog is not available in taskpane context after closing the dialog

### ISSUE THREAD

**Issue by kdeclerck** [OfficeDev/office-js#3896]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2311 (Build 17029.20068)
* Operating System: Windows 11

## Expected behavior
I expect HttpOnly cookies that are set in a dialog (via displayDialogAsync) to be accessible in the taskpane context which opened the dialog.

## Current behavior
The cookie is definitely set in the dialog context. After closing the dialog, I don't see the cookie in the taskpane context on Outlook Windows. It does seem to work for me on Mac/Web.

## Steps to reproduce

1.  Open a dialog in a taskpane context (https://app.com)
2.  In the dialog, do a request to https://server.app.com. 
3.  The request should return a Set-Cookie header. The cookie in this case is on server.app.com, SameSite=None, Secure=True.
4.  Use messageParent to close the dialog.
5.  In the taskpane context do a call to https://server.app.com and the cookie is not sent with the request.

Is this a known issue? Why doesn't seem to work on Windows when it does work on Web/Mac? Any ideas?

**Comment by zhngx1** [comment]
Thanks for reporting this, I will try to repro and get back to you.

**Comment by zhngx1** [comment]
Is your addin on the same domain as https://app.com? What request do you send to https://server.app.com? Can you provide more details of your repro?
