### ISSUE TITLE
Word Online Throwing ooxmlIsMalformated For Suggested Deletions

### ISSUE THREAD

**Issue by mike2151** [OfficeDev/office-js#3898]
Calling `.getOoxml()` on any range with a suggested deletion (a suggestion that deletes text) throws `RichApi.Error: ooxmlIsMalformated` only in Word Online

This behavior is not replicated on native Word applications nor is it replicated calling `.getOoxml()` on a range with a suggested addition/no suggested deletion

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.17207.41003
* Operating System: Mac
* Browser (if using Office on the web): Chrome
 
## Expected behavior

Getting the Ooxml (via `.getOoxml()`) of a Word.Range/Word.Paragraph with a suggested deletion should not throw 

## Current behavior

Calling `.getOoxml()` on a Word.Range/Word.Paragraph with a suggested deletion throws `RichApi.Error: ooxmlIsMalformated`

## Steps to reproduce

1. Load a document in which the first (or any paragraph) has a suggested deletion
2. Run: 
```
await Word.run(async (context) => {
    let ooxml = context.document.body.paragraphs.getFirst().getOoxml();
    await context.sync();
});
```

Observe error

3. Run step 2 on a document whose text/first paragraph does NOT have a suggested deletion

Observe no error

## Link to live example(s)

Steps to reproduce are above

# Provide additional details

## Context

Many functions rely on `.getOoxml()`; unblocking this issue would bring significant benefits

## Useful logs

Trace:
```
RichApi.Error: ooxmlIsMalformated
at new n (word-web-16.00.js:25:337152)
at o.processRequestExecutorResponseMessage (word-web-16.00.js:25:401598)
at word-web-16.00.js:25:399661
```

**Comment by xiruatms** [comment]
@mike2151 , thanks for reporting this.

Unfortunately, I didn't reproduce this issue, see the following screenshot for details:
![image](https://github.com/OfficeDev/office-js/assets/40648203/94f2892f-0bda-4e4f-83cd-a9f916321c17)

Did I miss anything here?

**Comment by mike2151** [comment]
Hey @xiruatms, by suggestion, I meant a deleted suggestion as follows (like how "world" is suggested to be deleted in review mode):
<img width="1488" alt="image" src="https://github.com/OfficeDev/office-js/assets/9808200/1154c61d-c778-49d6-8034-ee3a4dd86852">

Script Lab Code:
```
$("#run").click(() => tryCatch(run));

async function run() {
  await Word.run(async (context) => {
    await Word.run(async (context) => {
      let ooxml = context.document.body.paragraphs.getFirst().getOoxml();
      await context.sync();
    });
  });
}

async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    console.error(error);
  }
}
```

**Comment by xiruatms** [comment]
Thanks @mike2151 .

I assume this "world" is not suggested to be deleted but is a tracked "deleted" change.   I think the "Track Changes" feature (which can be found in "Review") is enabled in your case. Correct? If that's the case, I confirm I can repro it: getooxml failed if there're "deleted" tracked changes.  I've created an internal work item to track it: VSO #8589351.

**Comment by mike2151** [comment]
That's correct. Thanks for clarifying the terminology!

**Comment by mike2151** [comment]
Hey @xiruatms, wanted to follow up here and see if there were any updates. This bug makes using ooxml in Word Online quite unusable. Thank you!

**Comment by greysteil** [comment]
@xiruatms any progress on this?

**Comment by xiruatms** [comment]
@greysteil @mike2151 , we have updated. I can see it works for me now, will you please help to confirm on your side? Thanks.
![image](https://github.com/OfficeDev/office-js/assets/40648203/a6e111ee-c811-4a2e-ac44-3eccc199caf6)

**Comment by greysteil** [comment]
Confirmed that's it's working on our end - thanks for fixing this!
