### ISSUE TITLE
[Word] How to reliably create ranges in a document?

### ISSUE THREAD

**Issue by RXminuS** [OfficeDev/office-js#390]
We need to select a specific piece of text in a document. We know the offset in the paragraph, as well as the text before, inside and after. We tried the following approaches non of which allows us to reliably create a Range that we can call `select()` on.

**Attempt 1. Search for the matching text**
This leaves us to disambiguate between potential multiple matches (for instance if the matched word is "the"). However there is no way of extracting the offset of a Range object wrt the current paragraph only `Range.compareLocationWith` but the definition of `Word.LocationRelation` object is not enough to determine if the match is actually the one we mean. The only workaround (which isn't pretty) is to first search in our own "before" text and count which n-th match it's supposed to be...ugh!

**Attempt 2. Search for a Wildcard - Offset**
Then we had the brialliant idea of abusing Wildcard searches! You can call `Word.Paragraph.search` using the following (if the match starts at character <START_OFFSET> and ends at character <END_OFFSET>).
```js
const startRange = paragraph.search("?{<START_OFFSET>}", {
                matchWildcards: true
              }).getFirstOrNullObject();
const endRange = paragraph.search("?{<END_OFFSET>}", {
                matchWildcards: true
              }).getFirstOrNullObject();
const finalRange = startRange
                  .getRange("End")
                  .expandToOrNullObject(endRange.getRange("End"));
```
Hooray! Or so we thought. First problem is that for some reason wildcards only support up to {255} 🤯. Ok, easy workaround with the following function:
```js
// produces a string like "?{255}?{255}??? for n=513"
const createNCharWildcard = (n: number): string => {
  const full = "?{255}";
  const remainder = `?{${n % 255}}`;
  return full.repeat(n / 255).concat(remainder);
};
```
Yay...oh wait! As it turns out the matching also doesn't work if there is a link or a cross-reference in the text that is partially covered by the range. For instance the following text wouldn't match with a start offset of `56` (to match the word MATCH)

> This is text with a [link](#) in it and here we want a MATCH!
This seems like a dead end.

**Attempt 3. Search for a Wildcard - Character Skipping**
Maybe we can abuse the search like this?
```js
const startMatch = startParagraph
              .search("*", {
                matchWildcards: true
              })
              .load({
                select: "items",
                skip: <START_OFFSET>
                top: 1
              });
```
Now if we call startMatch.items[0] (after a sync ofcourse) we have the n-th character in the paragraph! Great, finally! However...this method is SOOOO SLOW. For only a few maches in a normal sized document this can take over 30 seconds?!?!

As you can imagine; at this point I'm extremely frustrated. I get that offsets into text aren't a reliable way of editing the text and that you had to come up with the `Range` object; but the API for creating and interacting with Ranges just isn't sufficient for this (common?) usecase.

Is there a "workaround" that we are missing, or can we extend the API somehow?

**Comment by JuaneloJuanelo** [comment]
i am assuming its possible for you  to  get, within the paragraph of interest, the number of spaces before the text-you-want-to-select and after such text ?

because you can range-split a paragraph by spaces  (using [range.split](https://docs.microsoft.com/en-us/javascript/api/word/word.range?view=office-js#split-delimiters--multiparagraphs--trimdelimiters--trimspacing-)) and then traverse the collection until you find your text of interest. 

that method returns an array of ranges and then you can basically use range.ExpandTo().select() to select the text you want.

**Comment by RXminuS** [comment]
Thanks @JuaneloJuanelo; I tried it but it's equally slow as Option 3, especially in Office Online.

**Comment by JuaneloJuanelo** [comment]
can you send a sample paragraph ? i would love to replicate the perf issue in our end.

**Comment by RXminuS** [comment]
The performance problems come forward just by having about 20-30 paragraphs. Adding to the problem is that the performance is extremely platform and Office version dependent. MacOS seems to be the slowest, but different versions of Word for Windows also have different performance.

So to replicate the issue, just generate some Lore Ipsum document and try to create ranges for about 100 words in it.

Another reason your method is quite slow is that it requires loading the text for all the split ranges; which with the other methods is not required. And also the method seems to join multiple consecutive spaces which offsets the character count.

Either way, it just doesn't feel like a very idiomatic API...especially since the old VSTO API is much more expressive.

**Comment by RXminuS** [comment]
Is there any way we can enable a trace in the OfficeJS API that I can send? Then I'll make some platform snapshots for you.

**Comment by JuaneloJuanelo** [comment]
@RXminuS  i was not able to repro this. I think it requires a more concrete sample to measure the perf. Assinging to @weshi  for follow up.

**Comment by weshi** [comment]
Please reactive this if it can still reproduces.

**Comment by JensMadsen** [comment]
We face very similar problems

**Comment by JensMadsen** [comment]
@RXminuS did you find a performant and reliable solution?

**Comment by ndvbd** [comment]
Same issue here. Why there is no constructor to create Range like in: 
https://developer.mozilla.org/en-US/docs/Web/API/Document/createRange
We need the ability to traverse the elements in the body so we can create our own custom range (based on startPosition and endPosition) and not based on .search()

**Comment by ndvbd** [comment]
Same problem here. Please open this issue. Also see this question here: https://stackoverflow.com/questions/44916485/create-custom-range-in-word-javascript-api-office-js
