### ISSUE TITLE
Office Word Add-in SSO Works Locally via manifest but Throws Error 13012 When Accessed via AppSource

### ISSUE THREAD

**Issue by Anya1304** [OfficeDev/office-js#3902]
The add-in works fine when launched using a local manifest file, but we encounter some error when accessing it via AppSource.

## Your Environment
* Platform: PC desktop
* Host: Word
* Office version number: Office 365 Version 2311 Build 17029.20068
* Operating System: Windows 11
 
## Expected behavior
To log in users into an add-in installed from AppSource via SSO

## Current behavior
If the add-in is launched via a local manifest file, single sign-on (SSO) works without problems. However, when accessing the same add-in through AppSource, we hit the error message “13012. The API is not supported on this platform."

We have re-deployed the app to our organization multiple times through the admin center, but this has not resolved the issue. The error persists in the accounts of various organizations, as well as in private accounts. For some accounts (including my Microsoft developer account until I redeploy it to the appropriate organization), SSO worked fine.

All necessary permissions are granted for this application on the Azure AD Enterprise application page.

The following code is used for SSO login:

`OfficeRuntime.auth.getAccessToken({ allowSignInPrompt: true, forMSGraphAccess: true });`

![image](https://github.com/OfficeDev/office-js/assets/55894856/af0b82c4-cec7-41ae-ad31-0e5d907ba92a)
![image](https://github.com/OfficeDev/office-js/assets/55894856/02633f64-b9b5-466f-871b-b3dbb09f3a3f)

**Comment by lamotik** [comment]
We have same problem

**Comment by kdeshpande-methodcrm** [comment]
@Anya1304 Was this resolved for you? I am still getting the same error
