### ISSUE TITLE
Missing right-click menu in add-in Task Pane with the New Outlook

### ISSUE THREAD

**Issue by elegault** [OfficeDev/office-js#3903]
We cannot use Edge DevTools with the New Outlook as there is no way to open it for the add-in's activated Task Pane. I'm not sure if this ever worked? Using CTRL+SHIFT+I and F12 also doesn't work. This is occurring in both 1.2023.1129.100 (Production) and 1.2023.712.100 (Production).

**Comment by exextoc** [comment]
Please run olk.exe --devtools from command prompt and check if this resolves the issue.

**Comment by elegault** [comment]
@exextoc It does indeed work!! Thanks! I note that the right-click menu capability still isn't there (although not needed with this command) - so did it ever work or is it hidden by design?

**Comment by elegault** [comment]
FYI, I'm proposing some suggested edits to the debugging section in the new Outlook for Windows article to surface this capability - see https://github.com/OfficeDev/office-js-docs-pr/pull/4320.

**Comment by exextoc** [comment]
Thank you @elegault. The PR have been merged. Closing the github issue.
