### ISSUE TITLE
fix Dialog height and width with parameter

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js#3904]
I am using office dialog and sending data to dialog by parameter and I am using height and width `15` because I need a small dialog when I pass a parameter then its width automatically increase to 30. when I am not using parameters then its works in 15 width.
`  

     function ErrorMesage(Errmessage) {
         let ErrorMesagedialog; // Declare as global variable.
         Office.context.ui.displayDialogAsync('https://localhost:44333/ErrorMessage/Error.html?error=' + Errmessage, { height: 15, width: 15
     },
     
      function (asyncResult) {
             ErrorMesagedialog = asyncResult.value
             ErrorMesagedialog.addEventHandler(Office.EventType.DialogMessageReceived, processMessage);
        }
    );
    function processMessage(arg) {
        ErrorMesagedialog.close();
    }
    }`

you can see this in screenshot
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/134502135/81332c96-c13a-44ad-a5d1-c9a25491119e)

this is showing full parameter as title but after `30` width not showing full title and showing like some title text and dots like title... 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a714626a-058a-789e-6add-5e9dfb21fd1f
* Version Independent ID: 1b88a28c-fc36-4518-2808-7246f08d9753
* Content: [Use the Office dialog API in your Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins)
* Content Source: [docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/dialog-api-in-office-add-ins.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by pinverso** [comment]
@junaid042 , What Office product are you using in which this dialog truncation occurs?

**Comment by junaid042** [comment]
@pinverso 
I am using this 
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/134502135/99abc65f-fe02-4efc-9e37-ab8e74f64117)

**Comment by junaid042** [comment]
@pinverso ??

**Comment by Wenjun-Gong** [comment]
@EsterBergen could you help to take a look? Looks like an issue on dialog UI. Thanks.

**Comment by junaid042** [comment]
@Wenjun-Gong yes this is dialog UI issues and this is working currently in web but not in desktop windows system

**Comment by junaid042** [comment]
@Wenjun-Gong, @EsterBergen Any update on this issue?

**Comment by EsterBergen** [comment]
@junaid042 - Thanks for submitting this feedback! I'm looking into it now and will have an update shortly.

**Comment by junaid042** [comment]
@EsterBergen thanks for your time, office dialog is working perfectly on web but on desktops its width not working good with parameter

**Comment by EsterBergen** [comment]
@junaid042 - Thanks again for raising this. This is a known issue with the Dialog on Win32 as the width is resized to fit the length of the URL. 
I created a bug (8671226) to track the issue and will give updates as available.

**Comment by EsterBergen** [comment]
Hi @junaid042 - Upon further investigation, we learned that the over-ride of the length in Win32 is by design. This is  security measure to prevent spoofing attempts. This holds true on web as well, when the dialog displayed inline. For the dialog that is displayed in a separate window on web, we rely on the browser to do the right thing. They have their own approach to handling spoofed address bars, for example the lock icon in edge.

Please let us know if there are any other questions!

**Comment by junaid042** [comment]
Hi @EsterBergen, @samantharamon and @Wenjun-Gong Please take a look at this issue [Dialog issues on Outlook Web](https://github.com/OfficeDev/office-js/issues/4100) this is very important for me. thanks in advance!
