### ISSUE TITLE
Office.onReady is not executed in a dialog that uses the window.open method

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#3906]
## Your Environment
*Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
*Host [Excel, Word, PowerPoint, etc.]: Outlook
*Operating System: Win 10
*Outlook Version: 2311

I was developing using displayDialogAsync from the Office library, but it affects the operating environment, so I would like to develop using the window.open method instead.
When I try to run Office.onReady() inside a popup opened with window.open it doesn't run,It runs on chrome and edge.
Why doesn't it only run in the desktop environment?

[Attach code sample and execution environment](https://github.com/mailchecktool-admin/Office-addin-sample/tree/main/src)
In the above sample created, the window.open method is executed from index.js under the sendHook folder and the contents under the popup folder are expanded.
It seems to me that windows opened with window.open are considered to be running outside of the Office host application and may prevent the Office.onReady method from executing successfully, what do you think?

If you can debug, please refer to the following operating environment.
Node: v18.16.0

procedure
npm install⇒npm run dev-server
Also sideload manifest.xml in the directory

**Comment by mailchecktool-admin** [comment]
@exextoc 
Are you reviewing the contents of this ticket? The other day, I created a reproducible development environment and shared it with you. I hope you can investigate based on this information.

**Comment by ztcdsb** [comment]
@mailchecktool-admin Your are right, the opened window is not considered as part of the add-in, so we don't run OfficeJs in there.
The correct solution here is to use displayDialogAsync because that will open up a window that is part of the add-in.

**Comment by mailchecktool-admin** [comment]
@ztcdsb 
Thank you for your response.

Currently, we are providing an add-in for misdelivery prevention using the `displayDialogAsync` method. The add-in utilizes the Office Add-ins API to retrieve data for "To," "Subject," "Attachments," and "Body," displaying them in a list on the dialog. Users can perform self-checks using checkboxes. However, since its introduction two years ago, we have been experiencing continuous issues, impacting approximately 10,000 users each time. The issues are as follows:

Case 1: The dialog remains in a waiting state without launching (occurred twice in the past).
Case 2: The dialog is displayed in an empty state (occurred twice in the past).

Therefore, instead of using `displayDialogAsync()`, we are considering replacing it with a commonly used program to prevent future occurrences of the same problems. Based on my investigation, I believe that using JavaScript's `window.open()` and `postMessage()` could serve as alternative methods. As you mentioned, the windows opened with `window.open()` are currently not considered part of the add-in.

Is it possible for you to update and support `window.open()` and `postMessage()` to address this issue? Your cooperation in ensuring that no further disruptions occur would be greatly appreciated.

**Comment by ztcdsb** [comment]
There will be security concerns to support window.open() and postMessage() 

But I highly suggest you to submit a feature request to bring up PM's attention.

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
