### ISSUE TITLE
Outlook event based AddIns: REST requests fail in old Outlook desktop

### ISSUE THREAD

**Issue by koller-patrick** [OfficeDev/office-js#3907]
## Your Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2311 Build 16.0.17029.20028) 64-bit 
* Operating System: Windows 11 Enterprise (10.0.22621 Build 22621)
* Browser: N/A
 
## Expected behavior
HTTPS REST requests should work in event based add ins for the old Outlook desktop client, as they work in the new Outlook desktop client. I tried using fetch and XHR but both did not work.

## Current behavior
Fetch requests fail, with the following error message: `TypeError: Network request failed`
XHR requests fail as well, with the following error message: 
```json
{
  "UNSENT": 0,
  "OPENED": 1,
  "HEADERS_RECEIVED": 2,
  "LOADING": 3,
  "DONE": 4,
  "readyState": 4,
  "status": 0,
  "timeout": 0,
  "withCredentials": true,
  "upload": {},
  "_aborted": false,
  "_hasError": true,
  "_method": "GET",
  "_perfKey": "network_XMLHttpRequest_https://localhost:5010/api/xxx",
  "_response": "\u0001",
  "_url": "https://localhost:5010/api/xxx",
  "_timedOut": false,
  "_trackingName": "unknown",
  "_incrementalEvents": false,
  "_performanceLogger": {
    "_timespans": {
      "network_XMLHttpRequest_https://localhost:5010/api/xxx": {
        "startTime": 1702374911080
      }
    },
    "_extras": {},
    "_points": {},
    "_pointExtras": {},
    "_closed": false
  },
  "_requestId": null,
  "_headers": {},
  "_responseType": "",
  "_sent": true,
  "_lowerCaseResponseHeaders": {},
  "_subscriptions": []
}
```

## Steps to reproduce
Create a event based office.js Outlook AddIn that is triggered by the `OnNewMessageCompose` event. In the triggered function make a REST API request. Here are the code snippets I used:

* Manifest.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="MailApp">
   <Id>9A2C1150-B9CD-4500-B94D-03F60CE69100</Id>
   <Version>1.0</Version>
   <ProviderName>ProviderName</ProviderName>
   <DefaultLocale>en-us</DefaultLocale>
   <DisplayName DefaultValue="DisplayName"/>
   <Description DefaultValue="Description"/>
   <IconUrl DefaultValue="https://localhost:5010/web/icon-40x40.png"/>
   <HighResolutionIconUrl DefaultValue="https://localhost:5010/web/icon-76x76.png"/>
   <SupportUrl DefaultValue="https://www.support.com"/>
   <AppDomains>
       <AppDomain>https://localhost:5010</AppDomain>
   </AppDomains>
   <Hosts>
       <Host Name="Mailbox"/>
   </Hosts>
   <Requirements>
       <Sets DefaultMinVersion="1.11">
           <Set Name="Mailbox"/>
       </Sets>
   </Requirements>
   <FormSettings>
       <Form xsi:type="ItemRead">
           <DesktopSettings>
               <SourceLocation DefaultValue="https://localhost:5010/web/Outlook.html"/>
               <RequestedHeight>450</RequestedHeight>
           </DesktopSettings>
       </Form>
       <Form xsi:type="ItemEdit">
           <DesktopSettings>
               <SourceLocation DefaultValue="https://localhost:5010/web/Outlook.html"/>
           </DesktopSettings>
       </Form>
   </FormSettings>
   <Permissions>ReadWriteMailbox</Permissions>
   <Rule xsi:type="RuleCollection" Mode="Or">
       <Rule xsi:type="ItemIs" ItemType="Message" FormType="Edit"/>
       <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"/>
   </Rule>
   <DisableEntityHighlighting>true</DisableEntityHighlighting>
   <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
       <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
           <Description resid="GetStarted.Description"/>
           <Requirements>
               <bt:Sets DefaultMinVersion="1.11">
                   <bt:Set Name="Mailbox"/>
               </bt:Sets>
           </Requirements>
           <Hosts>
               <Host xsi:type="MailHost">
                   <Runtimes>
                       <Runtime resid="Autorun.Url">
                           <Override type="javascript" resid="JsRuntime.Url"/>
                       </Runtime>
                   </Runtimes>
                   <DesktopFormFactor>
                       <ExtensionPoint xsi:type="MessageReadCommandSurface">
                           <OfficeTab id="TabDefault">
                               <Group id="msgReadDemoGroup">
                                   <Label resid="CommandsGroup.Label"/>
                                   <Control xsi:type="Button" id="msgReadOpenPaneButton">
                                       <Label resid="TaskpaneButton.Label"/>
                                       <Supertip>
                                           <Title resid="TaskpaneButton.Label"/>
                                           <Description resid="TaskpaneButton.Tooltip"/>
                                       </Supertip>
                                       <Icon>
                                           <bt:Image size="16" resid="Icon.16x16"/>
                                           <bt:Image size="32" resid="Icon.32x32"/>
                                           <bt:Image size="80" resid="Icon.80x80"/>
                                       </Icon>
                                       <Action xsi:type="ShowTaskpane">
                                           <SourceLocation resid="Taskpane.Url"/>
                                           <SupportsPinning>true</SupportsPinning>
                                       </Action>
                                   </Control>
                               </Group>
                           </OfficeTab>
                       </ExtensionPoint>
                       <ExtensionPoint xsi:type="MessageComposeCommandSurface">
                           <OfficeTab id="TabDefault">
                               <Group id="MessageCommandsGroup">
                                   <Label resid="CommandsGroup.Label"/>
                                   <Control xsi:type="Button" id="MessageTaskpaneButton">
                                       <Label resid="TaskpaneButton.Label"/>
                                       <Supertip>
                                           <Title resid="TaskpaneButton.Label"/>
                                           <Description resid="TaskpaneButton.Tooltip"/>
                                       </Supertip>
                                       <Icon>
                                           <bt:Image size="16" resid="Icon.16x16"/>
                                           <bt:Image size="32" resid="Icon.32x32"/>
                                           <bt:Image size="80" resid="Icon.80x80"/>
                                       </Icon>
                                       <Action xsi:type="ShowTaskpane">
                                           <SourceLocation resid="Taskpane.Url"/>
                                           <SupportsPinning>true</SupportsPinning>
                                       </Action>
                                   </Control>
                               </Group>
                           </OfficeTab>
                       </ExtensionPoint>

                       <ExtensionPoint xsi:type="LaunchEvent">
                           <LaunchEvents>
                               <LaunchEvent Type="OnNewMessageCompose" FunctionName="onNewMessageComposeHandler"/>
                           </LaunchEvents>
                           <SourceLocation resid="Autorun.Url"/>
                       </ExtensionPoint>
                   </DesktopFormFactor>
               </Host>
           </Hosts>
           <Resources>
               <bt:Images>
                   <bt:Image id="Icon.16x16" DefaultValue="https://localhost:5010/web/favicon-16x16.png"/>
                   <bt:Image id="Icon.32x32" DefaultValue="https://localhost:5010/web/favicon-32x32.png"/>
                   <bt:Image id="Icon.80x80" DefaultValue="https://localhost:5010/web/favicon-96x96.png"/>
               </bt:Images>
               <bt:Urls>
                   <bt:Url id="Taskpane.Url" DefaultValue="https://localhost:5010/web/Outlook.html"/>
                   <bt:Url id="Autorun.Url" DefaultValue="https://localhost:5010/web/Autorun.html"/>
                   <bt:Url id="JsRuntime.Url" DefaultValue="https://localhost:5010/web/Autorun.js"/>
               </bt:Urls>
               <bt:ShortStrings>
                   <bt:String id="GetStarted.Title" DefaultValue="GetStarted"/>
                   <bt:String id="CommandsGroup.Label" DefaultValue="CommandsGroup"/>
                   <bt:String id="TaskpaneButton.Label" DefaultValue="TaskpaneButton"/>
               </bt:ShortStrings>
               <bt:LongStrings>
                   <bt:String id="GetStarted.Description" DefaultValue="Description"/>
                   <bt:String id="TaskpaneButton.Tooltip" DefaultValue="Click to open the web addin"/>
               </bt:LongStrings>
           </Resources>
       </VersionOverrides>
   </VersionOverrides>
</OfficeApp>
```

* Autorun.html
```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
        <title></title>
        <script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js" type="text/javascript"></script>
        <script src="./Autorun.js" type="text/javascript"></script>
    </head>
    <body>
        <!-- NOTE: The body is empty on purpose. Since this is invoked via a button, there is no UI to render. -->
    </body>
</html>
```

* Autorun.js
```js
function onNewMessageComposeHandler() {
    // use either fetch or XHR
    const options = {
        method: "GET",
    };

    fetch("https://localhost:5010/api/xxx", options)
        .then(async (response) => {
            const responseText = await response.text();
            Office.context.mailbox.item.body.setAsync(
                responseText,
                {
                    coercionType: "html",
                },
                function (asyncResult) {
                    if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
                        console.error(JSON.stringify(asyncResult.error));
                    }
                }
            );
        })
        .catch((error) => {
            Office.context.mailbox.item.body.setAsync(
                "catch: " + error,
                {
                    coercionType: "html",
                },
                function (asyncResult) {
                    if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
                        console.error(JSON.stringify(asyncResult.error));
                    }
                }
            );
        });

    
    const xhr = new XMLHttpRequest();
    const url = "https://localhost:5010/api/xxx";

    xhr.open("GET", url, true);

	// does not work either, when setting headers
    //xhr.setRequestHeader("Accept", "application/json");
    //xhr.setRequestHeader("Content-Type", "application/json");

    xhr.onreadystatechange = function () {
        if (xhr.readyState === 4 && xhr.status === 200) {
            Office.context.mailbox.item.body.setAsync(
                xhr.responseText,
                {
                    coercionType: "html",
                },
                function (asyncResult) {
                    if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
                        console.error(JSON.stringify(asyncResult.error));
                    }
                }
            );
        } else {
            // Handle errors or other status codes here
            console.error("Error:", xhr.status, xhr.statusText);
            Office.context.mailbox.item.body.setAsync(
                "Error: " + JSON.stringify(xhr),
                {
                    coercionType: "html",
                },
                function (asyncResult) {
                    if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
                        console.error(JSON.stringify(asyncResult.error));
                    }
                }
            );
        }
    };

    // Send the request
    xhr.send();
}

if (Office.context.platform === Office.PlatformType.PC || Office.context.platform === null) {
    Office.actions.associate("onNewMessageComposeHandler", onNewMessageComposeHandler);
}
```

## Context
* I added the javascript file to the allowed add-ins in a well-known URI list as described here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/use-sso-in-event-based-activation#list-allowed-add-ins-in-a-well-known-uri
* I enabled CORS on the backend server as well.

**Comment by ndeleuze** [comment]
@koller-patrick your onNewMessageComposeHandler should take an event object which needs to be completed to signal to the Outlook client that the add-in has completed processing the event. Please see the following documentation as a reference for this: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/on-new-compose-events-walkthrough?tabs=xmlmanifest#implement-event-handling

**Comment by koller-patrick** [comment]
> @koller-patrick your onNewMessageComposeHandler should take an event object which needs to be completed to signal to the Outlook client that the add-in has completed processing the event. Please see the following documentation as a reference for this: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/on-new-compose-events-walkthrough?tabs=xmlmanifest#implement-event-handling

I have tried this and unfortunately I am still experiencing the same behavior as described in the bug description.

**Comment by Flyingdot** [comment]
@koller-patrick have you found a solution for this? I'm facing the same issue, all works fine on Mac, Web and new Win-Outlook, but it keeps failing in the old Desktop app on Windows with "Network request failed".

**Comment by ndeleuze** [comment]
@koller-patrick & @Flyingdot do you both have direct debugging enabled so that the resource on localhost is reachable?

**Comment by martinguenther** [comment]
1) Be sure to have the well-known URI list the add-in, as described in https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/use-sso-in-event-based-activation#list-allowed-add-ins-in-a-well-known-uri. 
So if the `JSRuntime.Url` is `https://localhost:3000/launchevent.js`, then the file must be located at `https://localhost:3000/.well-known/microsoft-officeaddins-allowed.json`. You must be able to open it from a browser when the dev server is running. The content in my case looks like this:
```
{
    "allowed": [
        "https://localhost:3000/launchevent.js"
    ]
}
``` 

2) The JavaScript-only runtime of Outlook (classic) on Windows sends a preflight request. Be sure that CORS is configured for the API you are querying **_AND_** that it returns the required CORS response headers.

This was the issue in my specific case. With Fiddler I inspected the request which Outlook sent to the API and found that the CORS response headers where missing - despite CORS being configured.

> When CORS is enabled with the appropriate policy, ASP.NET Core generally responds to CORS preflight requests automatically.

**Preflight request sent by Outlook**
```
OPTIONS https://myapi.xy/abc/ HTTP/1.1
Access-Control-Request-Method: POST
Accept-Encoding: gzip, deflate
Origin: https://localhost:3000/
Access-Control-Request-Headers: Content-Length, Content-Type
Sec-Fetch-Mode: CORS
Accept: */*
User-Agent: Microsoft Office/16.0 (Windows NT 10.0;  16.0.17328; Pro)
Host: myapi.xy
Content-Length: 0
Connection: Keep-Alive
Cache-Control: no-cache
```

**Response _without_ CORS headers**

```
HTTP/1.1 204 No Content
Server: Microsoft-IIS/10.0
Date: Tue, 26 Mar 2024 15:52:00 GMT
```

My CORS config listed `https://localhost:3000` as allowed origin. So what was wrong?

I noticed that Outlook was sending `Origin: https://localhost:3000/` (see the trailing slash), which turned out to be the reason. Only after adding `https://localhost:3000/` to the config 

```
var  MyAllowSpecificOrigins = "_myAllowSpecificOrigins";

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddCors(options =>
{
    options.AddPolicy(name: MyAllowSpecificOrigins,
                      policy  =>
                      {
                          policy.WithOrigins("http://example.com",
                                              "https://localhost:3000",
                                              "https://localhost:3000/");
                      });
});
```

the preflight was answered properly

**Response _with_ CORS headers**
```
HTTP/1.1 204 No Content
Date: Wed, 27 Mar 2024 14:22:07 GMT
Server: Microsoft-IIS/10.0
Access-Control-Allow-Headers: Content-Length,Content-Type
Access-Control-Allow-Methods: POST
Access-Control-Allow-Origin: https://localhost:3000/
Vary: Origin
```

which solved the `Network request failed` issue finally.

If any of the parts 1) or 2) are missing, the `Network request failed` error occurs. This is reproducible.

Side note: Microsoft's "Enable CORS" documentation (https://learn.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-8.0#cors-with-named-policy-and-middleware
) states that:

> The specified URL must not contain a trailing slash (/). If the URL terminates with /, the comparison returns false and no header is returned.

But Outlook does exactly that.... Or is it an issue with my dev server config....?

**Comment by Flyingdot** [comment]
@ndeleuze That was a crucial tip, thank you. I ignored direct debugging because according to the docs it is related to attaching a debugger. It was not clear to me, that it also enables usage of Fiddler etc.

With a working fiddler, I was able to see that the OPTIONS request was handled correctly:

```http
OPTIONS https://off... HTTP/2
access-control-request-method: POST
accept-encoding: gzip, deflate
origin: https://localhost:5173/
access-control-request-headers: authorization, Content-Length, Content-Type
sec-fetch-mode: CORS
accept: */*
user-agent: Microsoft Office/16.0 (Windows NT 10.0;  16.0.17425; Pro)
content-length: 0
cache-control: no-cache
host: off...

HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Referrer-Policy: strict-origin-when-cross-origin
Feature-Policy: camera 'self'; microphone 'none'; geolocation 'none'; fullscreen *
Permissions-Policy: camera=(self), microphone=(), geolocation=(), fullscreen=(self)
Server: Jetty
Date: Thu, 28 Mar 2024 12:53:41 GMT
Access-Control-Allow-Origin: https://localhost:5173/
Access-Control-Allow-Methods: GET, POST, PUT
Access-Control-Allow-Headers: Authorization
Cache-Control: no-store
Content-Length: 0
```

However, the subsequent POST request is not sent. Instead it fails with "Network request failed". 
The runtime log:
```	
3/28/2024 15:28:30	Verbose	Runtime	[Console] [Log] MailboxHostExecuteApi invoked!		
3/28/2024 15:28:30	Verbose	Runtime	[Console] [Log] error on send: Error: upload-error: Network request failed		
3/28/2024 15:28:30	Verbose	Runtime	[Console] [Log] LaunchEventObj.completed was invoked: 5		
3/28/2024 15:28:30	Unexpected	Runtime	[Error] [Log] console.error: error on send: Error: upload-error: Network request failed
Object.p [as error]
foundation.win32.bundle:55:1846
<unknown>
C:\Users\dani\AppData\Local\Microsoft\Office\16.0\Wef\{AAE23042-84FD-4F53-BC84-20D8F2997A4B}\JxcQhYS4DXszAJdiks+X0g==\Javascript\89ca397d-15a9-4619-9e3a-363057b68df8_1.0.0.0_en-US\bundle.js:210:57
u
foundation.win32.bundle:68:156
<unknown>
    at foundation.win32.bundle:68:868
<unknown>
    at foundation.win32.bundle:74:1662
k
foundation.win32.bundle:74:497
w
foundation.win32.bundle:74:887
t.callReactNativeMicrotasks [as _reactNativeMicrotasksCallback]
foundation.win32.bundle:74:3057
t.value
foundation.win32.bundle:35:2844
<unknown>
    at foundation.win32.bundle:35:938
		
3/28/2024 15:28:30	Verbose	Runtime	[Console] [Log] Event completed message sent to host!		
```

This happens in Outlook 2403 17425.20124. When I use the updated version 2404 17521.20000 it works. The newer version does not send the trailing slash in the origin header. So I modified the OPTIONS request in Fiddler to remove the trailing slash, but it is still failing with "Network request failed", although the requests/responses are now exactly the same as in the new version.

**Comment by Flyingdot** [comment]
any updates?

**Comment by martinguenther** [comment]
As mentioned in my last comment, I got the REST request to work in "old Outlook" on localhost by setting up the `.well-known` URI. But, when moving the Add-In to production, it stops working. It works on all other platforms, except "old Outlook".
Using Fiddler I can see, that Outlook loads the JS file from the server as specified in the XML.
`<bt:Url id="JSRuntime.Url" DefaultValue="https://app.xyz.com/prod/launchevent.js"/>`

![image](https://github.com/OfficeDev/office-js/assets/7925181/3a252195-9df4-4a7a-8063-1c4ffdab8b55)

Further I see the `.well-known` URI being requested from Outlook. The file exists and it lists the `launchevent.js`. (Just as it did on my dev machine with https://localhost:3000)

![image](https://github.com/OfficeDev/office-js/assets/7925181/a92c5823-5c3e-42f8-ae14-572d51ff17d3)

But any subsequent REST request using `fetch("https://api.xyz.com/")` (I tried different URLs) fails with `Network request failed`. Even more, I don't even see the request in Fiddler. So Outlook is not even sending it.

The URIs are correct. I double checked them X times. Why does it work when the Add-In is being served from localhost but not from production server? Any ideas on this? What am I missing?

Outlook Version is 2403 (Build 17425.20146).

**Comment by Dustnclay** [comment]
Having the same issue here.
I can read the logs, Direct debugging enabled, Posts working on all other clients, URI set up, Cors set up, GETs work but as soon as I try to POST I get 'Network Request Failed'.

**Comment by martinguenther** [comment]
@Dustnclay All of my issues where related to some CORS issues in the end. Did you inspect the requests with a tool like Fiddler to see what is going on? And are you 100% sure, that the CORS requests are being answered as supposed?

**Comment by ndeleuze** [comment]
@koller-patrick are you still experiencing this issue? Have you inspected the requests as suggested by @martinguenther above? If this issue is not a bug on the Outlook side and is instead a CORS configuration issue, then this thread should be closed.

**Comment by fedeisas** [comment]
@ndeleuze I'm facing this same issue running Windows 10 and Outlook 2205 15225.20288

My requests fail after 20 seconds, and I see on my RuntimeLogging:
```
[TypeError: Network request failed]
```

Requests are `GET` with `Accept: application/json` to a URL with a query-string.

My servers respond to CORS with:
```
HTTP/1.1 204 No Content
Connection: keep-alive
Cache-Control: no-cache, private
access-control-allow-origin: https://my.subdomain.origin.com
vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
access-control-allow-methods: GET
access-control-allow-headers: Content-Type, Authorization, Etag, Content-Length, Accept
access-control-max-age: 10
```

My API domain is declared on the manifest `AppDomains`.
I've tried proxying my API through the Origin domain and different combinations of domains.
I've tried fetch, then every polyfill I could find, then `XMLHttpRequest`.

I don't even see the outgoing requests to my API on Fiddler.

All other modern clients work just fine (iOS, Android, Windows Desktop modern clients, OWA, Mac).

Can you specify under which conditions Outlook's events runtime won't event fire requests?

Thanks a lot.

**Comment by martinguenther** [comment]
@fedeisas Are you in a test or production environment? 

From which URLs does Outlook load these two resources? Can you see those requests in Fiddler?

![image](https://github.com/user-attachments/assets/e30f1476-f3a0-42e8-8adc-a9613ef69048)

Also see my [previous comment](https://github.com/OfficeDev/office-js/issues/3907#issuecomment-2023138415) and check the trailing slash issue. Look exactly at the preflight request Outlook is sending, and verify that CORS response is correct.

![image](https://github.com/user-attachments/assets/0a5be32d-fd1c-4f7d-b56e-bf89e59b4a19)
 
A trailing slash can make a big difference, as I have experienced myself. Hope this helps.

**Comment by fedeisas** [comment]
@martinguenther we deploy our add-in on AWS Amplify.

For our production environment, we have a subdomain `office-add-in.domain.com`.
For our PRs we get `pr-123.something.amplifyapp.com`.

The API to support our add-in is hosted elsewhere and served on another `subdomain.domain.com`.
I've also tried proxying `/api/*` on the add-in to our backend to avoid CORS at all, but still fails on old Outlooks.

Thanks for the CORS suggestion.

I read about it a couple days ago so I duplicated my allowed_origins on my backend:
```
https://pr-*.something.amplifyapp.com
https://pr-*.something.amplifyapp.com/
https://office-add-in.domain.com
https://office-add-in.domain.com/
```

As for the fetch, I'm sending `Accept: application/json` and I need to parse the JSON as an object for my add-in functionality. I've noticed `JSON.parse` support is also a bit buggy on this version of Outlook.

I was also using `btoa` to base64 encode a payload before sending to the server and it seems to be not available on some platforms. I guess I need to improve my _polyfilling_ game.

What puzzles me is that I don't even see the `OPTIONS` request on Fiddle. Could it be that Outlook has cached that OPTIONS response thus preventing the request? If so, why does it takes ~21 seconds to throw `Network request failed`?

---

Update:
I managed to capture an OPTIONS request. I assume closing the laptop for a few hours helped. First request this morning did:

```
OPTIONS /s/office-bundle?some=params HTTP/1.1
Accept: */*
Origin: https://pr-354.edited.amplifyapp.com
Access-Control-Request-Method: GET
Access-Control-Request-Headers: accept, x-edited-telemetry
Accept-Encoding: gzip, deflate
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; Touch; rv:11.0) like Gecko
Host: api.edited.com
Content-Length: 0
Connection: Keep-Alive
Cache-Control: no-cache


HTTP/1.1 204 No Content
Date: Thu, 01 Aug 2024 19:16:53 GMT
Connection: keep-alive
Cache-Control: no-cache, private
access-control-allow-origin: https://pr-354.edited.amplifyapp.com
vary: Origin, Access-Control-Request-Headers, Access-Control-Request-Method
access-control-allow-methods: GET
access-control-allow-headers: accept, x-edited-telemetry
access-control-max-age: 10
apigw-requestid: b1_N1hfUCYcEJ1w=
CF-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=edited"}],"group":"cf-nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Server: cloudflare
CF-RAY: 8ac82a44ebe41e7b-EZE
alt-svc: h3=":443"; ma=86400
```

I did the OPTIONS requests, then did the GET request, everything worked but just ONCE.
All subsequent requests throw `Network request failed`.

**Comment by martinguenther** [comment]
@fedeisas That's really strange... Why does it work once, and then not... hard to tell what's going on...

1) You did not mention `.well-known/microsoft-officeaddins-allowed.json`. Did you check that? The URL of the script which serves the launch event JS code must be specified in that file. If not, the script is not allowed to send requests and you get `Network request failed`.

2) Does it work in debug mode - when the JS is served from localhost?

**Comment by fedeisas** [comment]
@martinguenther yes! It's totally confusing that it doesn't always fails.
1. I do have a `.well-known/microsoft-officeaddins-allowed.json` file where I declare my `autorun.js`.
2. No, that's why I directly do Win10 testing with a deployed branch :-(

**Comment by fedeisas** [comment]
@exextoc any suggestions? Thanks 🙏🏼

**Comment by Discolai** [comment]
@fedeisas I encountered a similar error

Our application was using relative URLs in fetch calls. According to the documentation on [requesting external data](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#request-external-data), relative URLs are not supported in a JavaScript-only runtime. Absolute URLs must be used instead.

**Comment by Sirius902** [comment]
I'm also experiencing this issue, even when just doing a simple fetch to the Microsoft Graph API. It's worth noting that I'm also doing this within a launch event same as OP.

For me, the below fetch call results in `TypeError: Network request failed` when the addin is not hosted on localhost. However, when the JS is served from localhost in debug mode it does work. I do also have a `.well-known/microsoft-officeaddins-allowed.json` file containing the URL to the script that does the fetch. I have verified that in production builds the URL matches the URL the JS file is hosted from in production.
```js
fetch("https://graph.microsoft.com/v1.0/me", {
  headers: {
    Authorization: "Bearer test",
  },
});
```

**Comment by ndeleuze** [comment]
The original reporter is no longer active, and this post is getting a bit confusing and possibly discussing different issues. I'd like to close this post and have anyone who's still having issues please open individual posts with clear details so we can address them directly. Thank you for your understanding.
