### ISSUE TITLE
Outlook getCallbackTokenAsync fails when selecting multiple items (Office on the web)

### ISSUE THREAD

**Issue by manuelsidler** [OfficeDev/office-js#3909]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office 365
* Operating System: macOS Sonoma 14.2
* Browser (if using Office on the web): Edge for Mac (Version 120.0.2210.61 (Official build) (arm64))
 
## Expected behavior
When selecting multiple items and calling `Office.context.mailbox.getCallbackTokenAsync`, it should return the access token.

## Current behavior
When running the add-in on Outlook on the web, selecting multiple items and calling `Office.context.mailbox.getCallbackTokenAsync` throws an error:
<img width="567" alt="image" src="https://github.com/OfficeDev/office-js/assets/802015/505112f1-e808-4891-a367-737a44d969f1">

## Steps to reproduce
1. Clone the example GH repo to reproduce the issue (see link below)
2. Run the add-in with `npm install` and `npm run dev-server`
3. Side load the add-in on Outlook on the web
4. Select multiple items
5. Open the add-in
6. Click the _Get access token_ button
7. Open the developer tools
8. The console contains the error (see screenshot above)

The same steps on Outlook for Mac work fine.

## Link to live example(s)
- GitHub Repo with example to reproduce: https://github.com/manuelsidler/outlook-addin-multiselect

## Context
We need the access token to set custom properties on the selected items via REST API.

**Comment by manuelsidler** [comment]
@exextoc the error seems to be fixed:
![image](https://github.com/OfficeDev/office-js/assets/802015/96aa9855-51d5-4138-8afb-db95e74f4b4c)

**Comment by exextoc** [comment]
@manuelsidler  Thank you for confirming. Closing the issue.
