### ISSUE TITLE
Enable track changes having issue on Online word.

### ISSUE THREAD

**Issue by maxwellfargoseCactus** [OfficeDev/office-js#3913]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Word]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 

## Current output in online word 
![image](https://github.com/OfficeDev/office-js/assets/49706940/a163ee10-3a75-43d0-bea0-cecfcbeff37f)
## Expected  output
![image](https://github.com/OfficeDev/office-js/assets/49706940/b2a0f790-548c-4600-b3de-e08102c44030)

## Current behavior
For native Word all working properly along with track changes enabled. 
For online Word if I enable track changes then its adds text at the wrong position but without track changes everything is working well.

## Steps to reproduce
enable track changes on the online word.
First Running code with sentence1 and suggestions1 and then sentence2 and suggestions2

## text 
With Documents  you will be able to write high-level academic quality manuscripts. While you are typing, suggestions will start to flow in and suggest spelling and grammar for your academic manuscript - you just have to accept or reject these!

## Code 

 sentence 1 = With Document you will be able to write high-level academic quality manuscripts.
sentence 2 = While you are typing, suggestions will start to flow in and suggest spelling and grammar for your academic manuscript - you just have to accept or reject these!

Suggestions 1=[{start: 13 , end :13, replacement: ","},{start: 40, end :67, replacement: "high-quality academic"}]
Suggestions 2=[{start: 22 , end :22, replacement: "your "}]

Word.run<void>(async (context) => {
        const selectedRanges = await getSentenceRanges({ context, sentence });
        selectedRanges[0]?.select();
        await context.sync();

        const searchOptions = {
          ignorePunct: true,
          ignoreSpace: false,
          matchCase: false,
          matchPrefix: false,
          matchSuffix: false,
          matchWholeWord: false,
          matchWildcards: true,
        };

        const ranges = context.document.getSelection().search('?', searchOptions);
        ranges.load('expand')
        ranges.load('items');
      
        await ranges.context.sync();

        if (ranges.items.length === 0) {
          return Promise.reject(
            `Unable to find any sentence in the document matching "${sentence}"`,
          );
        }

        for (let i = 0; i < sortSuggestions.length; i++) {
          const suggestion = sortSuggestions[i];
          if (!suggestion) {
            return;
          }
          const suggestionStartPoint = suggestion.start;
          const SuggestionEndPoint = suggestion.end;

          const wordSuggestionStartRange =
            suggestionStartPoint === SuggestionEndPoint
              ? ranges.items[suggestionStartPoint - 1]
              : ranges.items[suggestionStartPoint];
          const wordSuggestionEndRange = ranges.items[SuggestionEndPoint - 1];

          if (
            suggestion &&
            wordSuggestionStartRange &&
            wordSuggestionEndRange
          ) {
            const targetSuggestionRange = wordSuggestionStartRange.expandTo(
              wordSuggestionEndRange,
            );
            await context.sync();
            if (targetSuggestionRange) {
              targetSuggestionRange.load('text');
              targetSuggestionRange.load();
            
              const ooxml = targetSuggestionRange.getOoxml();
              await context.sync();
              console.log(
                'Text of targetSuggestionRange:',
                targetSuggestionRange.text,
              );
              const updatedOoxml = applySuggestionToOOXML(xmlParser.parseXml(ooxml.value), [
                suggestion,
              ]);
              targetSuggestionRange.insertOoxml(
                updatedOoxml,
                suggestionStartPoint === SuggestionEndPoint
                  ? Word.InsertLocation.end
                  : Word.InsertLocation.replace,
              );
              await context.sync();
            }
          }
        }
        return  await context.sync();
      }

export function applySuggestionToOOXML(
  ooxmlDocument: XMLDocument,
  suggestion: Pick<BaseSuggestion, 'start' | 'end' | 'replacement'>,
): XMLDocument {
  xmlParser.forEachNode(
    {
      context: ooxmlDocument,
      xpath: '(//w:body/w:p//w:t|//w:body/w:p//w:delText)',
    },
    (node, last) => {
      const textContent = node.textContent;
      if (!textContent) {
        return;
      }
      const { updatedFragment } = applySuggestionToSentenceFragmentWord({
        fragment: textContent,
        suggestion: suggestion,
      });
      if (updatedFragment !== updatedFragment.trim() && isElement(node)) {
        node.setAttribute('xml:space', 'preserve');
      }
      node.textContent = last ? updatedFragment : '';
    },
  );
  return ooxmlDocument;
}

export function applySuggestionToSentenceFragmentWord({
  fragment,
  suggestion,
}: {
  fragment: string;
  suggestion: Pick<BaseSuggestion, 'start' | 'end' | 'replacement'>;
}): {
  updatedFragment: string;
} {
  const suggestionType = getSuggestionType(suggestion);

  if (suggestionType === 'insert') {
    return { updatedFragment: `${suggestion.replacement}` };
  }
  if (suggestionType === 'delete') {
    return { updatedFragment: fragment.replace(fragment, ' ') };
  }
  if (suggestionType === 'replace') {
    return {
      updatedFragment: `${fragment.replace(fragment, suggestion.replacement)}`,
    };
  }
  return {
    updatedFragment: fragment,
  };
}

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by YijunMS** [comment]
@maxwellfargoseCactus Thanks for reaching us. I am trying to reproduce the issue. Could you provide the 3 **updatedOoxml** strings?

**Comment by maxwellfargoseCactus** [comment]
@YijunMS  FYI

[updatedOoxml.docx](https://github.com/OfficeDev/office-js/files/13672041/updatedOoxml.docx)
[updatedOoxml 2.docx](https://github.com/OfficeDev/office-js/files/13672042/updatedOoxml.2.docx)
[updatedOoxml  3.docx](https://github.com/OfficeDev/office-js/files/13672044/updatedOoxml.3.docx)

**Comment by YijunMS** [comment]
@maxwellfargoseCactus I tried to reproduce this scenario. Since I used ScriptLab, I run the related code for the two sentences separately, which worked fine. My assumption is that in your scenario, the selectedRange for the second sentence was not updated after you made changes to the first sentence. Would you try to reacquire the selectedRange for the second sentence after you made changes to the first sentence to see if it can resolve this problem?
