### ISSUE TITLE
Outlook on Mac, When setting the start and end, it intermittently doesn't work.

### ISSUE THREAD

**Issue by JongHwaPark** [OfficeDev/office-js#3915]
# Provide required information needed to triage your issue
I developed a feature in the Outlook add-in where pressing a button should set the start and end, but it's not working intermittently.
~~~
Office.context.mailbox.item.start.setAsync(startDate, (result) => {
  if (result.status === Office.AsyncResultStatus.Succeeded) {
    Office.context.mailbox.item.end.setAsync(endDate);
  }
});
~~~

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]:   Outlook add-in
* Office version number: 16.79.2
* Operating System: Mac Ventura 13.6
* Browser (if using Office on the web):  
 
## Expected behavior

Set start and end date

## Current behavior

When the button is pressed and the logic runs, intermittently the 'start' content blinks and reverts back to the previous content before the change.

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by exextoc** [comment]
@JongHwaPark Can you try following code snippet and see if it works for you 

  ```
const start = new Date(); // Represents current date and time.
  start.setDate(start.getDate() + 1); // Add 2 days to current date.
  Office.context.mailbox.item.start.setAsync(start, (result) => {
    if (result.status !== Office.AsyncResultStatus.Succeeded) {
      console.error(`Action failed with message ${result.error.message}`);
      return;
    }
    console.log(`Successfully set start date and time to ${start}`);

    const end = new Date(); // Set end to current start date and time.
    end.setDate(end.getDate() + 2); // Set end as 1 day later than start date.
    Office.context.mailbox.item.end.setAsync(end, (result) => {
      if (result.status !== Office.AsyncResultStatus.Succeeded) {
        console.error(`Set end date failed with message ${result.error.message}`);
        return;
      }
      console.log(`Successfully set end date and time to ${end}`);
    });
  });
```

**Comment by JongHwaPark** [comment]
Thank you for your response. I resolved the issue a different way. It seemed there was an intermittent issue due to a conflict between the function setting the end date and Outlook's behavior of automatically adjusting the end date when the new date was earlier than the existing one. So, I resolved it by not setting the end date when the new date was earlier than the Outlook date. This seems to have significantly reduced the occurrence of the previously mentioned issue.

**Comment by exextoc** [comment]
In this scenario it looks like both Addin and Outlook are trying to update the end time simultaneously which is resulting in end time set by your Addin being overwritten. May be you can try using [AppointmentTimeChanged](https://learn.microsoft.com/en-us/javascript/api/office/office.eventtype?view=common-js-preview#:~:text=raised%20in%20PowerPoint.-,AppointmentTimeChanged,-Occurs%20when%20any) event handler and update the end time again.
