### ISSUE TITLE
Insert function dialogue in Excel Online does not work properly with custom functions

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#3916]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.17207.42303
* Operating System: Windows
* Browser (if using Office on the web): Chrome Version 120.0.6099.71 (Official Build) (64-bit)
 
## Steps to reproduce

- Install the Velixo add-in from the store.
- Open a new blank workbook and click the Vx button on the ribbon so that the add-in runtime starts.
- Click "Fx" button in the formula bar so that Insert function appears.
- Search for SI.TURNOVER:

![image](https://github.com/OfficeDev/office-js/assets/5159662/03137d37-3b34-49ba-888a-5e5a062b83d7)

Note that the function signature displays correctly at this stage.

- Click Next, and observe that there are two ConnectionName arguments (incorrect, there is only one in the function signature) and no other arguments displayed.

![image](https://github.com/OfficeDev/office-js/assets/5159662/c5d7a2a3-9d00-4165-aa60-21046543e23a)

## Expected result

- Proper behaviour of the Insert function window and evaluation of the arguments + preview of the results.

cc @gmichaud who observed it previously.
cc @JuliaKassina @LiubovKabir from our QA team to follow the issue.

## Context

Our product is near-unusable in Excel Online because our function signatures are complex and need proper help. However, neither IntelliSense nor Insert Function dialogue work properly there.

**Comment by rundongmsft** [comment]
Hi @wh1t3cAt1k, thanks for your report. We reproduced this issue, and an internal bug 8618073 was created to track it.

**Comment by crcastle** [comment]
@rundongmsft Any update on this? I also noticed the issue, and it is confusing to users of custom functions I provide with an add-in. The issue is creating additional support burden I'm having to help with.

**Comment by zpfaltersack** [comment]
@rundongmsft I've also been experiencing this. It hasn't been too much of an issue but we're looking to add some more complicated functions that would really benefit from this context being shown to users. Do you happen to have any updates on when that internal bug is expected to be resolved? Thanks!

**Comment by lucadom** [comment]
Same problem here.
Any updates about this issue?

**Comment by wh1t3cAt1k** [comment]
I confirm the following behaviour on 16.0.18110.42307:

<img width="940" alt="image" src="https://github.com/user-attachments/assets/39adca29-542b-4e23-aa86-f486acfb07ac">

The only deficiency is that the function result is displayed as #CALC, however, as per my understanding it is the issue with all custom functions at the moment, so I believe this bug can be closed!
