### ISSUE TITLE
Enable/Disable buttons not working

### ISSUE THREAD

**Issue by srchaitanya** [OfficeDev/office-js#3917]
# Provide required information needed to triage your issue
I am following the example given at this page: https://learn.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands
And am trying to enable/disable buttons (that are added via manifest.xml) on a custom tab programmatically by sending a JSON blob to the method: Office.ribbon.requestUpdate.
But it does not seem to work.  And I see the following error in the console.
_RibbonApiNotAvailable: The API you are trying to use is not available. It may be available in a different scenario_

I have tried the same thing with a custom tab that is created via Office.ribbon.requestCreateControls method and it works.
Is this by design or a defect?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop and Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2302 Build 16.0.16130.20806) 32-bit  for desktop
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome
 
## Expected behavior
The button should get enabled 

## Current behavior
The buttons do not get enabled.

**Comment by srchaitanya** [comment]
Hi Team. Any update on the above issue.

**Comment by srchaitanya** [comment]
I have tested the condition: Office.context.requirements.isSetSupported("RibbonApi","1.1") and it returned true.

**Comment by trigurl** [comment]
Can you please share the following:
1) Base manifest file for your add-in, it should have the initial buttons for your add-ins in the Office Ribbon when the add-in is installed.
2) The javascript and html files - you can just have the snippet of code that can repro the exact issue you are seeing.

**Comment by srchaitanya** [comment]
My apologies, I could not reproduce the issue and most probably it could have been a workspace issue. Closing the defect.
