### ISSUE TITLE
Add-in does not start immediately after Outlook startup

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#3918]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook on the web
* Microsoft® Outlook® for Microsoft 365 MSO (version 2306 build 16.0.16529.20100) 64-bit
* Operating System: Windows OS
* Browser (if using Office on the web):Google Chrome , Microsoft Edge

## Summary
No add-ins are applied immediately after startup in Outlook in the web.
I have checked the network logs and they confirm that no add-ins are being called.
 
## Expected behavior

1.Install the Office add-in to Outlook on the Web.
2.Launch Outlook on the Web.
3.Immediately after startup, go to the "Drafts" folder.
4.Specify the recipient and click the "Send" button.
5.The Office add-in will start and a sample display will appear.
6.Click "close(true)" in the sample display.
7.An email will be sent.

## Current behavior

1.Install the Office add-in to Outlook on the Web.
2.Launch Outlook on the Web.
3.Immediately after startup, go to the "Drafts" folder.
4.Specify the recipient and click the "Send" button.
5.The Office add-in does not start, An email will be sent.

## Steps to reproduce

1.Upload "manifest.xml" to Outlook on the web and install the add-in (the XML file is stored in sample.zip)
2.Open a command prompt and navigate to the corresponding directory.
3.Run "npm install".
4.Run "npm run dev-server".
5.Install the Office add-in to Outlook on the Web.
6.Launch Outlook on the Web.
7.Immediately after startup, go to the "Drafts" folder.
8.Specify the recipient and click the "Send" button.
9.The Office add-in will start and a sample display will appear.
10.Click "close(true)" in the sample display.
11.An email will be sent.

## Remarks
* Occurs only immediately after startup
* Node version is v18.16.0

## Link to live example(s)

I am storing the sample add-in.
* sample add-in program
  https://github.com/mailchecktool-admin/Office-addin-sample/tree/main/src

**Comment by exextoc** [comment]
@mailchecktool-admin This is by design as add-in might have not loaded by the time you clicked "Send" button. If you need the add-in user to run on-send add-ins mandatorily, the mailbox policy must have the OnSendAddinsEnabled flag set to true. This will ensure that send is blocked until add-in loads.
Please refer https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=modern for more details.
