### ISSUE TITLE
Script lab for Outlook doesn't load scripts on Outlook Online

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js#3919]
# Provide required information needed to triage your issue
The Script Lab for Outlook does not work as expected on Outlook Online-based mail clients. The issue was first opened in OfficeDev/script-lab, and we were asked to move it here. See: [OfficeDev issue](https://github.com/OfficeDev/script-lab/issues/1037)

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: New Outlook for Windows, Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Any
* Operating System: Browser
* Browser (if using Office on the web): Any
 
## Expected behavior
Choosing a script to run from the script editor, would load the script in the runner and actually run it

## Current behavior
The script is never run. "No snippet to run" message displayed
![image](https://github.com/OfficeDev/office-js/assets/65173226/a677aca6-e834-4515-bc6e-3e0d1790b337)

**Comment by WernerSt1** [comment]
I have the same problem. It works with the Outlook client. It does not work with the web client!

**Comment by exextoc** [comment]
@bogdanst24 This is not an Outlook Office JS issue. We handle only issues related to the Office JS for Outlook. Closing this. Please add you comment to the issue created for Script Lab. https://github.com/OfficeDev/script-lab/issues/1037
