### ISSUE TITLE
Add-in Approval Experience Error in WOPI Office Online Requires Reloading

### ISSUE THREAD

**Issue by aeturneus** [OfficeDev/office-js#3920]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 
* Operating System: MacOS
* Browser (if using Office on the web): Chrome
 
## Expected behavior

When opening a document in our WOPI add-in for the first time, the user is presented with an add-in approval screen in the task pane. The user expects the add-in to load normally in the taskpane after user grants approval by clicking "Allow and Continue".

## Current behavior

After clicking "Allow and Continue", the task pane closes and an error message is displayed saying "Sorry, something went wrong. Could you please try that again?"

Clicking "OK" causes the error message to disappear, but the taskpane remains closed and the add-in does not load. 

Reloading the page causes the add-in to load in the TaskPane and display correctly. This issue only occurs on add-in authorization, so appears to be connected to the approval experience. 

## Steps to reproduce

1. Open a document in Word WOPI Office Online with add-in enabled
2. Click "Approve and Continue" when asked for consent to run the add-in
3. Error message will be displayed

## Context
This error affects users onboarding into our WOPI editing environment for the first time, and requires us to tell users to reload the browser after authorizing the add-in in order to access the features of our application. It's a bad onboarding experience.

## Useful logs

- [ ] Console errors
- [ X] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 
![image](https://github.com/OfficeDev/office-js/assets/877362/d9c2a4d0-bdab-46b2-a207-173c2cb16576)
![image](https://github.com/OfficeDev/office-js/assets/877362/70e7c739-e335-42a9-bb66-9ca3309f0f94)
![image](https://github.com/OfficeDev/office-js/assets/877362/169ec3f3-de10-49d3-84c0-1b1525314e89)

**Comment by nickamckenna** [comment]
We have this exact same problem too!

**Comment by YijunMS** [comment]
@aeturneus Thanks for reaching us.
I created a local WOPI environment and added the add-in **Divorcepath Pro Tools** from store (is this the correct add-in to load?). Then it opens with the following page 
![image](https://github.com/OfficeDev/office-js/assets/112541209/a9c2306a-a686-4e33-8e62-e0aea4a9b765)
It didn't ask me to approve. My Word Online version is 16.0.17202.30000.

Have you tried to load other add-ins in your environment? Would them ask for the approval as well?

**Comment by whekin** [comment]
@YijunMS The error only happens on the wopi instance in the web right after clicking "Allow and Continue"

**Comment by whekin** [comment]
@YijunMS When add-in windows shows with the consent this error happens in the console:

Request to /gatedserviceextension.aspx?fromAR=3&corr=7396f1d6-c818-2a92-f7dd-7f30d4912d90 came back with the status code: 
WordEditorDS.box4.dll3.js:1299 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'contentWindow')
    at https://res-1.cdn.office.net/officeonline/we/s/h455A15AD7396897E_App_Scripts/WordEditorDS.box4.dll3.js:1299:449

Source modules:
    https://res-1.cdn.office.net/officeonline/we/s/h455A15AD7396897E_App_Scripts/WordEditorDS.box4.dll3.js 455a15ad7396897e6f59a52dcf0c0527a1be647065e0038331781b0d591971ea
    
![image](https://github.com/OfficeDev/office-js/assets/39103584/271b7473-064e-444e-b576-99b302da995e)

**Comment by aeturneus** [comment]
@YijunMS Yes the approval experience only happens when accessing WOPI on our production or testing domains.

I can provide you with test credentials so you can see for yourself.

URL: https://www.divorcepath.com/app/sign-in

`email: csppverify1@microsoft.com pw: WopiTest123`

After sign-in, click on the WOPI Test client (at the top of the list), then click the "Documents" tab, and click on the first document to access the testing Word WOPI environment.

**Comment by YijunMS** [comment]
@aeturneus I tried to login to your WOPI environment, but the account or password may be incorrect.

For the "Allow and Continue" page, is this page part of your add-in? In what cases will it show? 
![image](https://github.com/OfficeDev/office-js/assets/112541209/31f1b2d9-f352-482d-8b68-5a00ac7a393b)

For the request to /gatedserviceextension.aspx, I saw it in my own WOPI environment, and it failed as well. I will do some investigation in this aspect.

Besides reloading the whole page, will it work by just reopening the add-in taskpane?

**Comment by aeturneus** [comment]
@yijunMS the "Allow and Continue" page is not part of our add-in. We understand that this page is shown to anyone who tries to use an add-in from the Office Store (not just our add-in) within the WOPI environment, and that clicking "Allow and Continue" causes the same error for everyone (for example, users of @nickamcknenna's many apps)

@nickamckenna and I have observed many users posting about this within the WOPI development community.

**Comment by aeturneus** [comment]
@YijunMS regarding your questions:

1. Log-in isn't required to reproduce this issue, however we have updated and confirmed the credentials so it should work now.
2. Reloading the page works, however clicking "show taskpane" without reloading first does not work and raises the same error.

**Comment by aeturneus** [comment]
@jargil @YijunMS let us know if any more info needed!

**Comment by YijunMS** [comment]
@aeturneus I logged in to your website but there is no WOPI Test client.

**Comment by aeturneus** [comment]
@YijunMS added WOPI test client again - although it’s not client specific, any document in the documents tab.

**Comment by YijunMS** [comment]
@aeturneus We have opened an internal bug (#8632038) to track this issue and engineers are doing the investigation. Thanks for reaching us.

**Comment by YijunMS** [comment]
@aeturneus Hi, we have deployed a fix which may solve this problem. Would you make a test to see if it really works?

**Comment by aeturneus** [comment]
@YijunMS your fix has resolved this issue - thank you for this!
