### ISSUE TITLE
Office.auth.getAccessToken no longer works on New Outlook Desktop

### ISSUE THREAD

**Issue by sami-romdhana** [OfficeDev/office-js#3921]
We're trying to get a bootstrap token through `Office.auth.getAccessToken` but can no longer do so.

We've had this problem on our production add-in, as well as the staging add-in and our locally hosted add-in.

## Your Environment

* Platform : Desktop
* Operating System: Windows 11
* Host : New Outlook
* Microsoft Outlook Version: 1.2023.1207.400 (Production)
* Client Version: 20231201002.07

We don't have this problem on Old Outlook Desktop or on Outlook Web.

We don't have this problem on New Outlook Desktop 1.2023.516.100
 
## Expected behavior

Getting a bootstrap token

## Current behavior

We're currently trying to get an auth token by using the following parameters:

```js
Office.auth.getAccessToken({
  forMSGraphAccess: false,
});
```

This fails with the following error:

```json
{
  "code": 13006,
  "message": "An unexpected error occurred in the client.",
  "name": "Error occurred in the authentication request from Office."
}
```

But using the following parameters we're getting a different error:

```js
Office.auth.getAccessToken({
  forMSGraphAccess: false,
  allowSignInPrompt: true,
  allowConsentPrompt: true,
});
```

![image](https://github.com/OfficeDev/office-js/assets/64911368/5ca3432d-7be1-4c26-893e-26c9e34b2455)
![image](https://github.com/OfficeDev/office-js/assets/64911368/696374d9-9caa-490b-9945-86a3c65ff189)

## Steps to reproduce

1. Using an SSO-enabled add-in [(following these instructions)](https://learn.microsoft.com/fr-fr/office/dev/add-ins/outlook/authenticate-a-user-with-an-sso-token)  
    * In our Azure app registration, we have used the recommended client ID for all Office platforms
2. Try to get a bootstrap token using `Office.auth.getAccessToken`

## Link to live example(s)

Minimal reproducible example provided for convenience [here](https://github.com/sami-romdhana/mre-outlook-auth)

Use `npm run certificates` if local development certificates are not yet installed, then run `npm start` (tested on Windows)

## Context

Our users are blocked from using our add-in since it relies on authentication to then fetch further data

It seems that [we're not alone in encountering this issue](https://stackoverflow.com/questions/77656916/getaccesstoken-fails-in-outlook-plugin-with-error-13006)

**Comment by spinit-jlin** [comment]
We had the same problem after the last Outlook Desktop update. When we added the Client Id from the error message as a pre-authorized client in the App registration (Expose an API) it worked again. 

The new version of Outlook is probably not a part of the old catch-all id **ea5a67f6-b6f3-4338-b240-c655ddc3cc8e** 

![image](https://github.com/OfficeDev/office-js/assets/446768/4f8b9b0b-a79d-433c-8eeb-7751c31a5c51)

**Comment by exextoc** [comment]
@sami-romdhana, this issue has been fixed in the latest version. Please check and let us know if it still reproduces for you.

**Comment by sami-romdhana** [comment]
@exextoc The issue looks fixed on our end, thank you
