### ISSUE TITLE
The OnMessageRecipientsChanged Add-in action doesn't trigger an event on the compose window in OWA

### ISSUE THREAD

**Issue by vadym-vereshchaka** [OfficeDev/office-js#3927]
# Provide required information needed to triage your issue

We use the Outlook Add-in that updates an email signature when an email recipient is changed during email composing.
It worked fine in both Desktop Outlook and Outlook Web App, but recently it has stopped working in OWA, however, it still works correctly in Desktop Outlook.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2310
* Operating System: Windows
* Browser (if using Office on the web): Chrome - Version 119
 
## Expected behavior

Add-in updates an email signature in the compose window when the recipient is changed in both OWA and Desktop Outlook

## Current behavior

Add-in doesn't update an email signature in the compose window when the recipient is changed in OWA

## Steps to reproduce

1. Install an Outlook Add-in that updates an email signature in the compose window based on the recipients list.
2. Change the recipients' list to trigger a signature update.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding OnMessageRecipientsChanged. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: 4180843

**Comment by mmanjaree-msft** [comment]
@vadym-vereshchaka Could you please check if issue is resolved, and you do not have 5 or more launch event addins running at the same time? Currently, there is a limit of 5 [Configure your Outlook add-in for event-based activation - Office Add-ins | Microsoft Learn](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#event-based-activation-behavior-and-limitations). This could be a reason for the issue mentioned above. Otherwise, we are not able to repro the issue where event is not triggered.

**Comment by vadym-vereshchaka** [comment]
Thanks for the answer, I left only one add-in, but unfortunately, we still observe different behaviour on the Desktop Outlook and OWA when updating the list of recipients. To reproduce it with an add-in we use requires the user to be subscribed to the email signature service, which makes this add-in not easy to use from any account. 
We will try to implement the sample Addin with the issue described and provide it to you for reproduction, but it will take some time.

**Comment by mmanjaree-msft** [comment]
@vadym-vereshchaka  Sample addin would be really helpful. Please reopen the issue once addin is available to share.

**Comment by vadym-vereshchaka** [comment]
Just FYI: The problem isn't reproduced anymore at the latest OWA.
