### ISSUE TITLE
Updates the styles of the current document with the Styles from another document passed in as a Base64-encoded string?

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js#3928]
is that possible Updates the styles of the current document with the Styles from another document passed in as a Base64-encoded string?
In this documentation first example changing the text of file with base64 text. I want to change its styles is that Possible. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1d1d8c75-ea38-aed8-73ba-fbf27bb6118d
* Version Independent ID: 802e07cc-4610-6184-bed4-5f4ec499cd47
* Content: [Word.DocumentCreated class - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/word/word.documentcreated?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.documentcreated.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.documentcreated.yml)
* Service: **word**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by ElizabethSamuel-MSFT** [comment]
@junaid042 Thanks for reaching out about this. I'll take a look and get back to you as soon as possible.

**Comment by junaid042** [comment]
@ElizabethSamuel-MSFT any update or holidays on your side if holidays then please don't worries and enjoy.

**Comment by ElizabethSamuel-MSFT** [comment]
@junaid042 I'm transferring this to the product repo so the team can investigate this.

**Comment by penglongzhaochina** [comment]
Hi @junaid042 ,

Please try this API: retrieveStylesFromBase64(base64File)
This is the doc: https://learn.microsoft.com/en-us/javascript/api/word/word.application?view=word-js-preview#word-word-application-retrievestylesfrombase64-member(1)

Thanks.

**Comment by junaid042** [comment]
Hi @penglongzhaochina  as you shared  API: `retrieveStylesFromBase64(base64File)` this is getting styles from `base64` and give us but I want my `base64` document will be imported to my opened document. is that possible to import styles to my current document from another document `base64`?

**Comment by junaid042** [comment]
Hi @penglongzhaochina  thank you for your sport I have done this using your idea and some my effort.

first I am getting styles using your idea API: `retrieveStylesFromBase64(base64File)` then `importStylesFromJson(retrievedStyles.value);`

       const retrievedStyles = context.application.retrieveStylesFromBase64(externalDocument);
       await context.sync();
       console.log("Styles from the other document:", retrievedStyles.value);
       const styles = context.document.importStylesFromJson(retrievedStyles.value);
       await context.sync();
       console.log("Styles imported from JSON:");
       console.log(styles)

**Comment by junaid042** [comment]
Thanks all @Rick-Kirkham @ElizabethSamuel-MSFT @ElizabethSamuel-MSFT @penglongzhaochina for help!
