### ISSUE TITLE
Web Outlook Add-in Sideload Install Takes > 4 hours to appear

### ISSUE THREAD

**Issue by barrettpyke** [OfficeDev/office-js#3930]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **Office on the web**
* Host [Excel, Word, PowerPoint, etc.]: **Outlook**
* Browser (if using Office on the web): **Chrome**
 
## Expected behavior
Outlook Add-Ins sideloaded in the web should be installed and useable within a timely manner.

## Current behavior
Outlook Add-Ins sideloaded in the web take longer than the 4 hours outlined in the office-js documentation to be installed and be ready for use. 

## Steps to reproduce
1. Download this repo, https://github.com/OfficeDev/Office-Add-in-samples/tree/main.
2. Navigate https://aka.ms/olksideload in your browser.
3. Click "My Add-Ins".
4. Scroll to the bottom and select "Add a Custom Add-in" and then select "From a File...".
5. Locate the repo on your local machine you downloaded in step one and add the manifest from Office-Add-in-samples-main > Samples > hello-world > outlook-hello-world > manifest.xml.
6. Wait for the Add-in to be available for use.

## Context

This severely impacts the ability to develop Outlook Add-ins and test them in the web.
This also affects our clients who use the Outlook Add-in from installing it and using it immediately.
Before the change was made to remove URL based sideloading, manifests added through the file option or the URL option would be installed immediately and be available for use.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by manaunl** [comment]
I have the same problem. Can we please fix this ASAP! It is not possible to do any development with such environment.

**Comment by avisheknand** [comment]
i was facing same problem. What I have noticed is after sideloading the add-in, clear the browser cache, refresh the browser... the add-in starts to work.

**Comment by exextoc** [comment]
@barrettpyke , @manaunl Could you please try clearing your browser's cache to see if the issue persists? If the problem remains, could you let me know how long it takes for the add-in to appear?

**Comment by barrettpyke** [comment]
@exextoc I have performed the steps above of sideloading add-in, clearing cache, and refreshing browser in Chrome. The add-in has not appeared yet but will keep and eye on it and let you know how long it takes.

**Comment by barrettpyke** [comment]
I found that 1/2 times I attempted this the add-in loaded, the time it did not took around 4 hours. Understand that this is expected but is there a timeline on when add-ins will be able to be sideloaded without the wait or the additional step of clearing the browser cache?

**Comment by jlara005** [comment]
I am currently testing "smart alerts" which require manifest changes and having to wait hours for each small change (because I'm not sure if it's setup right) is ridiculous! Even removals seem to take 4 hours.

**Comment by exextoc** [comment]
Hi, can you collect the network logs (using Fiddler/Browser Dev Tools) and share it with us at OutlookExtensibility@M365x53858506.onmicrosoft.com .  Please update this post when the logs are shared.

Steps to collect logs:

1. Open incognito window and Devtools.
2. Login to mail in incognito window and monitor the network logs.
3. Select a mail item.
4. Check if you see startupdata and GetExtensibilityContext in network logs.
5. Sideload the given add-in.
6. Collect the logs.

**Comment by manaunl** [comment]
I have sent an email with the logs. 

I want to emphasize this one more time. Developing add-ins is complicated and inefficient when you can not add or remove them without waiting 4 hours.
