### ISSUE TITLE
Unable to Easily Uninstall Outlook Add-Ins in the Web version

### ISSUE THREAD

**Issue by barrettpyke** [OfficeDev/office-js#3931]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Browser (if using Office on the web): Chrome
 
## Expected behavior
We should be able to uninstall Outlook Add-ins in the web version without navigating to https://aka.ms/olksideload

## Current behavior
The only way to uninstall an Outlook Add-In in the web version is to navigate to https://aka.ms/olksideload

## Steps to reproduce

1. Navigate to outlook.office365.com.
2. Login to your Mailbox.
3. Click a mailbox item.
4. Click Apps in the quick action message surface.
5. Click Add Apps.
6. Search for Backstop Solutions.
7. Click the Add-in in the search results.
8. Click Install.
9. Click Manage Your Apps in the left corner.
10. Click the ellipses next to the Backstop Solutions Add-In.

## Context
This affects our customers because there's no easy way for them to uninstall our Add-in. The only way is to navigate to a hidden UI through the https://aka.ms/olksideload link. This is not a user friendly suggestion.

**Comment by exextoc** [comment]
@barrettpyke We understand your concern. As mentioned in the [blog](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdevblogs.microsoft.com%2Fmicrosoft365dev%2Fupdates-to-how-to-install-and-use-add-ins-and-apps-in-outlook-for-windows-and-outlook-on-the-web%2F&data=05%7C01%7Ckeverit%40microsoft.com%7Ccc2c15bb9e804ecafbc008dbf1059859%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638368778648988536%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9dy7sUoiQZecCmVq9rQlOXLXOhw9zvcZtiG9GU7mTrc%3D&reserved=0), though the updated Store improves the Office Add-ins and apps browsing experience, it doesn’t yet support the installation or removal of a custom add-in, as was available in the previous Add-ins for Outlook dialog. Long term, we are planning to bring this functionality into the new store. In the meantime, we recommend using the direct link to the dialog as a workaround.

**Comment by barrettpyke** [comment]
@exextoc Understood, do you have a timeline on when that might be added?

**Comment by exextoc** [comment]
@barrettpyke Unfortunately we don't have any timelines to share at this point.
