### ISSUE TITLE
Unable to insert nested lists using `insertHtml` on Word for Web 

### ISSUE THREAD

**Issue by monominia** [OfficeDev/office-js#3933]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:  Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 
* Operating System: Both on Windows and Mac OS
* Browser (if using Office on the web): **Chrome** Version 120.0.6099.109 (Official Build) (64-bit)
 
## Expected behavior
When calling `insertHtml` with argument like `<ul><li>Milk</li><ul><li>Blue cheese</li></ul></ul>`, I'm expecting a result like [this in MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul).

## Current behavior
It rendered a flat list, no matter how many layers the input has.
![Screenshot 2023-12-18 100755](https://github.com/OfficeDev/office-js/assets/13508893/f5413266-617b-42c4-b031-c7a89488d8ce)

## Steps to reproduce
1. Download this public gist [link](https://gist.github.com/monominia/92dbf5553e5305a1d53450c335bdd28b)
2. Import it inside Script Lab
3. Click the `Insert the content control` button.

## Link to live example(s)

1. Live example in Script Lab: [link](https://seismic-my.sharepoint.com/:w:/p/jqi/EQ3olTtSPY9BlnM3W9kD5PUBM1_MKZPNB4gPsZVJLwn8Aw?e=gQRc1n)

## Context

We're building a Word add-in, which allowed the users to edit inside the Content Control field and then use the add-in to save what they typed in as a rich text field inside our service. (50,000 MAU)

## Useful logs

- [ ] Console errors
- [x] Screenshots
![Screenshot 2023-12-18 101940](https://github.com/OfficeDev/office-js/assets/13508893/c407304f-7a83-4066-bdf3-cf360a11c5c1)

- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by yilin4** [comment]
@monominia It works in our inner ring, and I need more time to know about when it will roll out to production. I will update to you if there is anything found. Thank you~
![image](https://github.com/OfficeDev/office-js/assets/107384367/93e6dfcd-c5ab-4982-a7b9-47718c3ed84f)

**Comment by monominia** [comment]
Hey @yilin4 , it still doesn't work in production. 
If you checked the code of my gist file, you can see the `html` I tried to insert is like:
`
    <ul>
      <li>Milk</li>
      <li>
        Cheese
        <ul>
          <li>Blue cheese</li>
          <li>Feta</li>
        </ul>
      </li>
    </ul>
    <ol>
      <li>Milk</li>
      <li>
        Cheese
      </li>
    </ol>
`
So, when an ordered list is the neighbor of an un-ordered list, the current API also doesn't work. Do I need to file another issue for this? Or we can use this one to track it?

Happy New Year!

**Comment by yilin4** [comment]
@monominia It still needs more time to work in production. It will be better to file another issue. Thank you! Happy New Year!

**Comment by monominia** [comment]
I just checked this, and it get fixed!!! But [this issue](https://github.com/OfficeDev/office-js/issues/3967) still exist. Anyway, thanks team!
