### ISSUE TITLE
Exchange 2019 problem with manifest validation SupportsMultiSelect

### ISSUE THREAD

**Issue by milczuk** [OfficeDev/office-js#3935]
When uploading my addin's manifest to Exchange 2019 I get the error below.
Do we need a separate manifest for exchange 2019?
Is it possible to support multi select using Outlook 365 and Exchange 2019?

Error displayed:

> This app can't be installed. The manifest file doesn't conform to the schema definition. The element 'Action' in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1' has invalid child element 'SupportsMultiSelect' in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1'. List of possible elements expected: 'SupportsNoItemContext' in namespace 'http://schemas.microsoft.com/office/mailappversionoverrides/1.1'...

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34daad03-0e48-d846-0c52-9ce4cedd4462
* Version Independent ID: 34daad03-0e48-d846-0c52-9ce4cedd4462
* Content: [Activate your Outlook add-in on multiple messages - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select)
* Content Source: [docs/outlook/item-multi-select.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/item-multi-select.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by zhngx1** [comment]
The next cumulative update of exchange 2019 will have the support for multiselect. I will close this issue for now. Feel free to reopen if you still have any issue once the new cumulative update for exchange 2019 is out.
