### ISSUE TITLE
EWS request delivers different attachment ids (on every call) then Office.context.mailbox.item.attachments

### ISSUE THREAD

**Issue by hmuris** [OfficeDev/office-js#3937]
Hi,

Office.context.mailbox.item.attachments is delivering list of attachments. This list does not contain cid nor the data of the attachment. In order to get the attachment data, it is necessary to call `getAttachmentContentAsync` on the item (this does not work, another [ticket](https://github.com/OfficeDev/office-js/issues/3897)). In order to get cid of the attachments that are inline, we need to perform EWS call using `Office.context.mailbox.makeEwsRequestAsync(reqData, callback)`. 
Until recently this method returned attachments with same attachment id and it was possible to associate them with attachments acquired over Office.context.mailbox.item.attachments. 
Currently this method delivers attachments with different ids.
Not just this, the ids are different by every call.
reqData:
![image](https://github.com/OfficeDev/office-js/assets/5045824/941d4d9c-0ac0-4fed-9647-4afbbc073151)

**Comment by hmuris** [comment]
Just to say, this functionality is extremely important for our addin. The problem is there for two weeks or so.

**Comment by hmuris** [comment]
This behavior is different, from mail to mail. For some mails result is always the same, and ids are same like in item.attachments, but for some mails ids are always different.

**Comment by exextoc** [comment]
Hi @hmuris, could you let us know the Outlook client (web, Mac, Windows, Monarch) and the version of Outlook where you are seeing this issue?

**Comment by hmuris** [comment]
I'm having this issue in web, Outlook in Microsoft 365.

**Comment by exextoc** [comment]
Hi @hmuris 
For getting the attachment, you need to use the GetAttachment request, not the GetItem request. This is explained here - 
https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/getattachment-operation?redirectedfrom=MSDN . Could you try this and see if it works for you.

**Comment by hmuris** [comment]
This is unfortunately not working. Here is my request:
![image](https://github.com/OfficeDev/office-js/assets/5045824/b3c93a76-498d-41cc-b3e9-28968973fe00)
I'm getting: 'The request is invalid.' code 9020.
I thought that message id would also be required in the request, but it is not there in the [article](https://learn.microsoft.com/en-us/exchange/client-developer/web-service-reference/getattachment-operation?redirectedfrom=MSDN) you have sent, so I also didn't try to include it somewhere.

**Comment by ndeleuze** [comment]
@hmuris I just want to confirm that you are only seeing this issue in Outlook on the web and not classic Outlook desktop (different from new Outlook desktop).

**Comment by mmrosekgi** [comment]
> @hmuris I just want to confirm that you are only seeing this issue in Outlook on the web and not classic Outlook desktop (different from new Outlook desktop).

@ndeleuze 
Hi, coworker here.
Yes, we are only working with Outlook on the Web at the moment. So we don't know if the issue would arise in the desktop version.

**Comment by exextoc** [comment]
@hmuris Could you try the following request format:
```
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
               xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
               xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header>
    <t:RequestServerVersion Version="Exchange2010_SP1" />
  </soap:Header>
  <soap:Body>
    <m:GetAttachment>
      <m:AttachmentIds>
        <t:AttachmentId Id="<ID>" />
      </m:AttachmentIds>
    </m:GetAttachment>
  </soap:Body>
</soap:Envelope>
```

**Comment by hmuris** [comment]
@exextoc It is still not working. Different message, but still:
![image](https://github.com/OfficeDev/office-js/assets/5045824/d5baf98b-5714-4456-b37e-ed0a109fa7f8)

**Comment by ajays-msft** [comment]
@hmuris -For any ews specific queries, please get help from the forum as mentioned in the EWS documentation https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/start-using-web-services-in-exchange

https://social.technet.microsoft.com/Forums/en-US/home?forum=exchangesvrdevelopment
