### ISSUE TITLE
Publishing custom functions in this sample on AppSource

### ISSUE THREAD

**Issue by t-lm** [OfficeDev/office-js#3938]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

Hi there, 

Thanks for the great documentation and samples for Excel custom functions. 

However, I can't find any section regarding  publishing of the custom Excel function on AppSource (as part of an add-in). 
My custom functions work great locally but are not recognised on the published app. 

Thanks for help
T

**Comment by AlexJerabek** [comment]
Hi @t-lm,

Thanks for reporting this. I'm not sure what part of the process would be different for custom functions. I'm going to transfer this issue to the [office-js repo](https://github.com/OfficeDev/office-js) where someone in the feature crew can assist you.

**Comment by MiaofeiWang** [comment]
Hi @t-lm , thanks for reporting this. The process of publishing add-ins to with custom functions to AppSource is same with those w/o custom functions: https://learn.microsoft.com/en-us/partner-center/marketplace/submit-to-appsource-via-partner-center. If your add-in has been published, would you please provide more details (for example, your add-in id, your custom functions' JSON metadata, error UI, etc.) so that we can further figure out the root cause?

**Comment by MiaofeiWang** [comment]
Hi @t-lm , may I know if your issue is resolved? Please let us know if we can provide any help.

**Comment by t-lm** [comment]
Hi Miaofei,

Thanks, we are good now. Managed to complete publication of custom functions with the indications here: https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/publish/publish-add-in-vs-code.md#using-visual-studio-code-to-publish

Maybe they should be integrated in the Excel Custom functions documentation?

Thanks anyway
Cheers
T


Le 9 janv. 2024 à 04:09, Miaofei Wang ***@***.***> a écrit :



Hi @t-lm<https://github.com/t-lm> , may I know if your issue is resolved? Please let us know if we can provide any help.

**Comment by MiaofeiWang** [comment]
Glad to know you are unblocked. 
And thanks for the update suggestion. We will try to optimize the documentation for better experience.
