### ISSUE TITLE
Excelwebaddin with an office365 E3 developper license

### ISSUE THREAD

**Issue by RaoulRSV** [OfficeDev/office-js#3939]
**Question**

I have been developping Excel web complements with Visual Studio 2019 and 2022 for a while with no particular problems until I installed an office E3 developper license on my desktop without changing anything else.

Since then, no complement works properly even the basic template supplied by the Visual Studio application (either 2019 or 2022): no icons in the command bar, nothing appears on the taskpane from html, break points on javascript not effective.

This applies also to Blazor web addins

Only webcomplements from Visual Studio Code work properly.

What did I miss ?

**Comment by AlexJerabek** [comment]
Hi @RaoulRSV,

Thanks for reporting this. I'm going to transfer this issue to the [office-js repo ](https://github.com/OfficeDev/office-js) where the feature crew can investigate.

**Comment by davidchesnut** [comment]
Hi @RaoulRSV, we're looking into this issue. It looks like a workaround for now is to run Visual Studio in admin mode. Can you confirm if this works for you as well? Thanks!

**Comment by RaoulRSV** [comment]
Hi @davidchesnut. Thanks very much for your answer; I was quite desesperate.
I can now run Excelwebaddin and BlazorAddin template with all functionalities seeming ok (I have not tested all).

However : no breakpoint available, be it in JS for Excelwebaddin and  in JS and C#  for BlazorAddin 
        and : error message when closing the application saying "failure of debug adaptator launching" (it's a translation from french). Note that previously breakpoints were effective for JS in both application and not effective for C# in BlazorAddin (see a previous issue I posted few months ago)

**Comment by RaoulRSV** [comment]
@davidchesnut @AlexJerabek. Using the proposed workaround, the console.log() instruction are not effective. Therefore it looks like a **run without debug** (ctrl+ F5) : no breakpoint in JS and JS console.log() instruction ineffective, while it provides the coded functionnalities.

**Comment by RaoulRSV** [comment]
@davidchesnut @penglongzhaochina. How is it possible to know whether Office 2021 is a correct alternative to office 365 concerning this issue ?

**Comment by RaoulRSV** [comment]
@davidchesnut @penglongzhaochina. How is it possible to now whether Office 2021 is a correct alternative to office 365 concerning this issue ?

**Comment by RaoulRSV** [comment]
@davidchesnut @penglongzhaochina. How is it possible to now whether Office 2021 is a correct alternative to office 365 concerning this issue ?

**Comment by davidchesnut** [comment]
Hi @RaoulRSV, we're working to fix the issue. For now you might have to use the dev tools to debug. When your task pane opens there is an arrow in the upper right corner (the personality menu). There's an option to Attach Debugger and then you can debug using the browser dev tools. 

For Blazor CS debugging be sure you have followed the [debug config steps here](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/blazor-add-in/excel-blazor-add-in#debugging). However I don't know if the debugging will work until this issue is resolved.

Hope this helps,
David

**Comment by RaoulRSV** [comment]
@davidchesnut @aafvstam , thanks for the attention you're paying to this issue. I am looking forward to this fix.

Sincerly

**Comment by davidchesnut** [comment]
Hi @RaoulRSV, looks like this is fixed so you should be able to debug normally now in Visual Studio.

**Comment by RaoulRSV** [comment]
@davidchesnut. Thanks very much for your help. I will try the fix
