### ISSUE TITLE
All browser except Firefox get error when adding large content to CustomXMLParts

### ISSUE THREAD

**Issue by hxltinh** [OfficeDev/office-js#394]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior

Adding large content to CustomXMLParts should work fine 

## Current Behavior

Adding large content triggers error, and content could not be Added.

## Steps to Reproduce, or Live Example

* Link to live example: ______ [bug reproduction link](https://github.com/hxltinh/office-js-bug-customxmlparts)

## Context

We need to store images base64 content to CustomXMLPart

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online(Word, Excel)
* Operating System: Window, Mac
* Browser (if using Office Online): Chrome, Safari, IE11, Edge (Firefox working fine)

## Useful logs

- [x] Console errors

**Comment by JuaneloJuanelo** [comment]
@hxltinh  can you please provide the XML part you are tryin to insert?
is not clear in what in what platforms you are trying this.... is this on Word ONline, Excel Online? )you mention firefox so I am assuming online)

**Comment by hxltinh** [comment]
@JuaneloJuanelo word, excel are working ok, it happens only in Office Online, that's why we would like to have it fixed on Office Online.
My repo should explain very well this bug. Just try on Chrome to see how it works (app/index.html for quick view).
`<root xmlns="${xmlns}"><item>${loadedBase64Image}</item></root>`
I will update my issue to make thing clearer, hope it helps.

**Comment by JuaneloJuanelo** [comment]
@hxltinh quick question: what is the size of the XML you are trying to insert?

**Comment by hxltinh** [comment]
@JuaneloJuanelo It's about form 700KB to 30MB and further. Hope it helps

**Comment by JuaneloJuanelo** [comment]
@weshi  should be able to investigate further... specially interesting that it works in Firefox.
anyways in online i think there is a limit on what we support, something we would have to document.

**Comment by JuaneloJuanelo** [comment]
@AlexJerabek  just a quick note to document this once @weshi  finishes the investigation. thanks.

**Comment by AlexJerabek** [comment]
Thanks @JuaneloJuanelo. @weshi, please let me know when you have the requested information and I'll transfer the issue to the office-js-docs-pr repo.

**Comment by AlexJerabek** [comment]
@weshi, Do you have any updates on the investigation?

**Comment by kbrandl** [comment]
Please ignore the previous message from **msftbot**. The **Needs: author feedback** label was incorrectly applied to this issue; I've removed that label and this issue is no longer marked as stale.

**Comment by AlexJerabek** [comment]
Pinging @weshi for updates. Until the investigation is completed and there is information for the doc update, I'm going to un-assign myself from this issue. Please reassign me once progress has been made.

**Comment by weshi** [comment]
There is size limit for Office Online. What's the size of the content you are trying to add?

**Comment by hxltinh** [comment]
@weshi we meet this problem when adding  base 64 image content, even larger than 30MB.

**Comment by lindalu-MSFT** [comment]
@weshi What are the size limitations for Office online? We need to have the doc team add this info. Please let me know how to follow up with this issue.
