### ISSUE TITLE
Issue with getRange in a context that contains overloaded range

### ISSUE THREAD

**Issue by jieyuy** [OfficeDev/office-js#3940]
# I encountered an issue that getRange not working when the context contains overloaded range.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Version 16.80
* Operating System: OS Ventura
 
## Expected behavior
See below is the code I ran on script lab. I would expect it can work, but it actually only worked when I don't pass `range` into `await Word.run(range, async (context) `

```
async function insertContentControls() {
  // Traverses each paragraph of the document and wraps a content control on each with either a even or odd tags.
  const range = await Word.run(async (context) => {
    OfficeExtension.config.extendedErrorLogging = true;
    let paragraphs = context.document.body.paragraphs;
    paragraphs.load("$none"); // Don't need any properties; just wrap each paragraph with a content control.

    await context.sync();

    const range = paragraphs.items[0].getRange(Word.RangeLocation.start).expandTo(paragraphs.items[0].getRange(Word.RangeLocation.end));
    await context.sync();
    return range;
  });
  await insertHelper(range);
}

async function insertHelper(existingRange: Word.Range) {
  return await Word.run(existingRange, async (context) => {

    await context.sync();
    let paragraphs = context.document.body.paragraphs;
    paragraphs.load("items");
    await context.sync();
    const newRange = paragraphs.items[0].getRange(Word.RangeLocation.whole);
    const cc = newRange.insertContentControl();
    cc.title = "Content controls inserted:";
    cc.track();
    cc.select();
    await context.sync();
  });
}
```

## Current behavior
It will raise richApi error "ItemNotFound" when run to `const newRange = paragraphs.items[0].getRange(Word.RangeLocation.whole);` line. 
And it doesn't have issue with `paragraphs.load("items");`
## Steps to reproduce
See above code block, it should be reproduced if you run it on scriptLab

## Link to live example(s)
See above

## Context

So we need to create range under the same context, so that we can do other things, such as get overlapping range, that's why we overload a `range` into `Word.run`, but then it causes other method not working.

## Useful logs
`[ERROR]: Error:
{
    "message": "ItemNotFound",
    "name": "RichApi.Error",
    "code": "ItemNotFound",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "ItemNotFound",
        "message": "ItemNotFound",
        "errorLocation": "ParagraphCollection.getItem",
        "statement": "var paragraph = paragraphs.getItem(...) /* originally getItem(...) */;",
        "surroundingStatements": [
            "var root = context.root;",
            "var body = root.body /* originally body */;",
            "var paragraphs = body.paragraphs /* originally paragraphs */;",
            "// >>>>>",
            "var paragraph = paragraphs.getItem(...) /* originally getItem(...) */;",
            "// <<<<<",
            "var range = paragraph.getRange(...);",
            "// Instantiate {range}",
            "var insertContentControl = range.insertContentControl();",
            "// Instantiate {insertContentControl}",
            "insertContentControl.title = ...;",
            "..."
        ],
        "fullStatements": [
            "var root = context.root;",
            "var body = root.body /* originally body */;",
            "var paragraphs = body.paragraphs /* originally paragraphs */;",
            "var paragraph = paragraphs.getItem(0) /* originally getItem(0) */;",
            "var range = paragraph.getRange(\"Whole\");",
            "// Instantiate {range}",
            "var insertContentControl = range.insertContentControl();",
            "// Instantiate {insertContentControl}",
            "insertContentControl.title = \"Content controls inserted:\";",
            "insertContentControl.select();"
        ]
    },
    "httpStatusCode": 404,
    "line": 25,
    "column": 280598,
    "sourceURL": "https://appsforoffice.microsoft.com/lib/1/hosted/word-mac-16.00.js",
    "stack": "n@https://appsforoffice.microsoft.com/lib/1/hosted/word-mac-16.00.js:25:280598\n@https://appsforoffice.microsoft.com/lib/1/hosted/word-mac-16.00.js:25:345058\n@https://appsforoffice.microsoft.com/lib/1/hosted/word-mac-16.00.js:25:343140"
}`

**Comment by JHJ-MS** [comment]
It seems something is wrong with the paragraphs.items[0]. I have created an internal bug #8612669 in backlog.
Try paragraphs.getFirst() as a workaround,
```
async function insertContentControls() {
  // Traverses each paragraph of the document and wraps a content control on each with either a even or odd tags.
  const range = await Word.run(async (context) => {
    OfficeExtension.config.extendedErrorLogging = true;
    let paragraphs = context.document.body.paragraphs;
    paragraphs.load("$none"); // Don't need any properties; just wrap each paragraph with a content control.

    await context.sync();

    //const range = paragraphs.getFirst().getRange();
    const range = paragraphs.getFirst().getRange();
    await context.sync();
    return range;
  });
  

  let test = "test";
  await insertHelper(range,test);
}

async function insertHelper(existingRange: Word.Range,test) {
  return await Word.run(existingRange, async (context) => {

    await context.sync();
    let paragraphs = context.document.body.paragraphs;
    paragraphs.load("items");
    await context.sync();
    console.log(paragraphs.items.length);
    
    const newRange = paragraphs.getFirst().getRange();
    const cc = newRange.insertContentControl();
    cc.title = "Content controls inserted:";
    cc.track();
    await context.sync();
    
    const intersectionRange = newRange.intersectWith(existingRange);
    newRange.select();
    await context.sync();
  });
}
```

**Comment by jieyuy** [comment]
> It seems something is wrong with the paragraphs.items[0]. I have created an internal bug #8612669 in backlog. Try paragraphs.getFirst() as a workaround,
> 
> ```
> async function insertContentControls() {
>   // Traverses each paragraph of the document and wraps a content control on each with either a even or odd tags.
>   const range = await Word.run(async (context) => {
>     OfficeExtension.config.extendedErrorLogging = true;
>     let paragraphs = context.document.body.paragraphs;
>     paragraphs.load("$none"); // Don't need any properties; just wrap each paragraph with a content control.
> 
>     await context.sync();
> 
>     //const range = paragraphs.getFirst().getRange();
>     const range = paragraphs.getFirst().getRange();
>     await context.sync();
>     return range;
>   });
>   
> 
>   let test = "test";
>   await insertHelper(range,test);
> }
> 
> async function insertHelper(existingRange: Word.Range,test) {
>   return await Word.run(existingRange, async (context) => {
> 
>     await context.sync();
>     let paragraphs = context.document.body.paragraphs;
>     paragraphs.load("items");
>     await context.sync();
>     console.log(paragraphs.items.length);
>     
>     const newRange = paragraphs.getFirst().getRange();
>     const cc = newRange.insertContentControl();
>     cc.title = "Content controls inserted:";
>     cc.track();
>     await context.sync();
>     
>     const intersectionRange = newRange.intersectWith(existingRange);
>     newRange.select();
>     await context.sync();
>   });
> }
> ```

Thanks for the quick response. We use `paragraphs.items[i]` iteratively, so `getFirst()` doesn't work for us.

**Comment by JHJ-MS** [comment]
Hi @jieyuy , could you try using getNext() to do the iteration

**Comment by jipyua** [comment]
hi @jieyuy You can make the following changes "paragraphs.track()" to track the paragraph collection because in order to access the passed in existingRange object, we need to track it so that it can be located by the API pipeline.

```
async function insertContentControls() {
  // Traverses each paragraph of the document and wraps a content control on each with either a even or odd tags.
  const range = await Word.run(async (context) => {
    //OfficeExtension.config.extendedErrorLogging = true;
    let paragraphs = context.document.body.paragraphs;
    paragraphs.load("$none"); // Don't need any properties; just wrap each paragraph with a content control.

    await context.sync();
    paragraphs.track();  // add this call to track the paragraph collection.
    const range = paragraphs.items[0].getRange(Word.RangeLocation.start).expandTo(paragraphs.items[0].getRange(Word.RangeLocation.end));
    
    await context.sync();
   
    return range;
  });
  
  await insertHelper(range);
}
```
