### ISSUE TITLE
Outlook Add-in : RecurrenceProperties data is incorrect

### ISSUE THREAD

**Issue by JongHwaPark** [OfficeDev/office-js#3941]
I have 2 Issues

###  1. recurrenceProperties is incorrect on Mac App
The recurring schedule is set from April 30, 2024, to October 1, 2024, for the last day of each month
recurrenceProperties data of Outlook Web is correct,
but Outlook on Mac is incorrect

###  2. seriesTime is incorrect on Web
When I set recurring schedule like from April 30, 2024, for the following 3 months, every month on Map
Web's seriesTime is incorrect

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]:  Outlook Add-in
* Office version number: App version :  16.80 ( 23121017 )
* Operating System: Mac Ventura 13.6
* Browser (if using Office on the web): Chrome
 
###  1. recurrenceProperties is incorrect on Mac App
Outlook Add-in On Web
```
{
    recurrenceProperties:{
        dayOfWeek: "day", // This is correct, It works on Outlook Web 
        interval: 1,
        weekNumber: "last"
    },
    recurrenceTimeZone: {
        name: "Korea Standard Time",
        offset: 540
    },
    recurrenceType: "monthly",
    seriesTime: {
        durationMinutes: 30,
        endDay: 1,
        endMonth: 10,
        endYear: 2024,
        startDay: 30,
        startMonth: 4,
        startTimeMinutes: 480,
        startYear: 2024
    }
}
```

###  2. seriesTime is incorrect on Web
```
{
    recurrenceProperties:{
        dayOfWeek: "weebday",
        interval: 1,
        weekNumber: "last"
    },
    recurrenceTimeZone: {
        name: "Korea Standard Time",
        offset: 540
    },
    recurrenceType: "monthly",
    seriesTime: {
        durationMinutes: 30,
        endDay: 28,  // It works on Mac app
        endMonth: 6,
        endYear: 2024,
        startDay: 30,
        startMonth: 4,
        startTimeMinutes: 480,
        startYear: 2024
    }
}
```

###  1. recurrenceProperties is incorrect on Mac App
Outlook app Add-in On Mac
```
{
    recurrenceProperties:{
        dayOfWeek: "sun", // This is incorrect, It's not working on Outlook Mac App, I think It should be 'day'
        interval: 1,
        weekNumber: "last"
    },
    recurrenceTimeZone: {
        name: "Korea Standard Time",
        offset: 540
    },
    recurrenceType: "monthly",
    seriesTime: {
        durationMinutes: 30,
        endDay: 1,
        endMonth: 10,
        endYear: 2024,
        startDay: 30,
        startMonth: 4,
        startTimeMinutes: 480,
        startYear: 2024
    }
}
```

###  2. seriesTime is incorrect on Web
```
{
    recurrenceProperties:{
        dayOfWeek: "weebday",
        interval: 1,
        weekNumber: "last"
    },
    recurrenceTimeZone: {
        name: "Korea Standard Time",
        offset: 540
    },
    recurrenceType: "monthly",
    seriesTime: {
        durationMinutes: 30,
        endDay: 0,  // end date is empty
        endMonth: 0,
        endYear: 0,
        startDay: 30,
        startMonth: 4,
        startTimeMinutes: 480,
        startYear: 2024
    }
}
```

**Comment by JongHwaPark** [comment]
I need some feedback!

**Comment by exextoc** [comment]
@JongHwaPark 
Thanks for reaching out. We have been able to repro the issue in outlook for mac and the issue is put to our backlog but unfortunately we don't have any timelines to share. Internal tracking id - 8624441

We were not able to repro the issue in outlook web Requesting you to please hsare a video if possible for web.
