### ISSUE TITLE
How to get details of selected items (multi select) from exchange 2019?

### ISSUE THREAD

**Issue by milczuk** [OfficeDev/office-js#3943]
When using using SupportsNoItemContext in the manifest and listening on 
I'm trying to support multi select but for Outlook 365 while working with on prem Exchange 2019 server.
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select
Using SupportsNoItemContext in the manifest in combination with listening to selection change events and 
 [Office.context.mailbox.getSelectedItemsAsync]( https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-preview#outlook-office-mailbox-getselecteditemsasync-member(1) ) I can get the list of selected items.
Now I'd like to get something more from the server but the token we get for ews seems to be only usable for single item.
I'm using [Office.context.mailbox.getCallbackTokenAsync](https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-1.13&preserve-view=true#outlook-office-mailbox-getcallbacktokenasync-member(1))({isRest:false},...)

Is this setup supported?
If it's not supported are there any plans for support of such combination (Outlook 365 with on prem exchange 2019)?
Am I doing something wrong?

**Comment by milczuk** [comment]
just to clarify I am able to use EWS on my backend with the token but only for one of the items from the selection
The token contains the ID of the message. If I parse the EWS token I get something like:
```
typ : JWT
alg : RS256
x5t : CcSsEXv4fxfP7uWhkQToNYbcoT0





nameid       : 7f0f121e-7dba-428b-b37f-6035270e48b4@mydomain.com
ver          : Exchange.Callback.V1
appctxsender : https://mydomain.com/app/office/webaddins/outlook/mail/index.html@mydomain.com
appctx       : {"smtp":"Michael@mydomain.com","scope":"ParentItemId:AAMkAGYyNjA5OTk2LTVkYzUtNGNiNC04YTMzLWI4ZmNhN2Q5NTk4
               NQBGAAAAAACy0XZAsH2DRLSd949UIImXBwB3zMpxpWg2TZnDD7/WitggAAAAAAEJAAB3zMpxpWg2TZnDD7/WitggAAANFPA4AAA="}
iss          : 00000002-0000-0ff1-ce00-000000000000@mydomain.com
aud          : 00000002-0000-0ff1-ce00-000000000000/dc1.mydomain.com@mydomain.com
exp          : 1703173841
nbf          : 1703173541
```

so I'm guessing that is why I get access denied errors on all other items. Would it be possible to get the token for all selected items to get details of multiple selected items at once? or at least to be able to specify the itemId when requesting the callback token so that it is in the scope?

**Comment by Oleg-O** [comment]
If you declare ReadItem or ReadWriteItem permission in the add-in manifest, you'd get the item-scoped callback token. For callback token API to give you a token that can be used to access other items, you would need to request ReadWriteMailbox permission in your add-in manifest. Note, however, that in this case you'd need to specify "isRest=true" parameter in the API when you get the token and use REST API to access items - we never supported non-item-scoped EWS callback tokens.

If for some reason you must use EWS, another option is to access the items from the client using makeEwsRequestAsync API.
