### ISSUE TITLE
OnMessageSend event doesnt get called with calendar item forward/cancel

### ISSUE THREAD

**Issue by mkondadg** [OfficeDev/office-js#3944]
Using new outlook UI. Deploy an outlook addin.
When an existing calendar meeting is forwarded / cancelled, the addin javascript callback function is NOT called.

## Your Environment

    Windows desktop
    Outlook
    You have Microsoft Outlook Version 1.2023.1018.300 (Production).
    Client Version is 20231027003.07 .
    Windows 10 Enterprise 21H2 19044.2006

 
## Expected behavior
when an existing calendar meeting is forwarded / cancelled, the addin javascript callback function is called.

## Current behavior
when an existing calendar meeting is forwarded / cancelled, the addin javascript callback function is NOT called.

## Steps to reproduce

1. Click "New mail" -> "Event"
2. Add email address to "Invite attendees" and "Send" the email to send to invites
3. Go to "Calendar" and right click on meeting. Click "Forward" and add new email id
4. Click "Send"

## Context
If this is not supported, we have a DLP egress usecase where user can send confidential info in forward / cancel invites.

**Comment by ajays-msft** [comment]
Related to : #3258
