### ISSUE TITLE
Addin not working if Outlook App has multiple accounts

### ISSUE THREAD

**Issue by mkondadg** [OfficeDev/office-js#3945]
Secondary account in Outlook app doesnt trigger addin or its callback.

## Your Environment
Windows desktop
Outlook
You have Microsoft Outlook Version 1.2023.1018.300 (Production).
Client Version is 20231027003.07 .
Windows 10 Enterprise 21H2 19044.2006
 
## Expected behavior
Secondary account in Outlook app calls addin function callback.

## Current behavior
Secondary account in Outlook app calls addin function callback. Only primary account addin is triggered for its callback.

## Steps to reproduce
1. Add 2 accounts from View -> View Settings -> Accounts -> Add account
2. Deploy addin for 2 accounts with OnMessageSend event.
3. Send mail using account-1. Addin is triggered and its javascript function is called.
4. Send mail using account-2. Addin is NOT triggered and its javascript function is NOT called.

## Context
In DLP usecase, even if the account has addin deployed, sendmail will not trigger addin causing egress.

**Comment by ajays-msft** [comment]
Are you using Old outlook or New Outlook?
![image](https://github.com/OfficeDev/office-js/assets/75355666/4d7ef579-7bce-45a2-bfd3-453877ea46f7)

**Comment by mkondadg** [comment]
@ajays-msft It is New Outlook

**Comment by ajays-msft** [comment]
@mkondadg - Currently New Outlook only supports Add-ins on primary account. You can leave your feedback here w.r.t addins on New Outlook here:
https://techcommunity.microsoft.com/t5/outlook-blog/add-ins-in-the-new-outlook-for-windows/ba-p/3954388
