### ISSUE TITLE
Office.context.mailbox.Item.start giving wrong value in Outlook for Mac

### ISSUE THREAD

**Issue by bhatnagarsaddy** [OfficeDev/office-js#395]
I am fetching the start date of Meeting recurrence in outlook WebAddin using office.js API 
 "Office.context.mailbox.item.Start".

**I am getting wrong start date value in case of "Outlook App for Mac".**

The value is showing up correctly everywhere else : 

1. Outlook App for window 
2. Outlook webApp 
3. O365 
4. Outlook WebApp in Safari.

**For an instance,** If there is a meeting recurrence which is set up for 09/20/2018 to 03/20/2019

If I open any single meeting of that recurrence (let us say 12/25/2018), Below are the results for Start Date :

1.  Outlook App for window : 12/25/2018
2. Outlook webApp : 12/25/2018
3. O365 : 12/25/2018
4. Outlook WebApp in Safari : 12/25/2018
5. **_Outlook App for Mac : 09/20/2018_**

**Comment by bhatnagarsaddy** [comment]
@macOutlookExtensibility can you please provide any input on this issue? 
If there's any other property which can be used or any other work around to fix this issue?

**Comment by bhatnagarsaddy** [comment]
@kbrandl  Is there any other team or dedicated group who can help me in this issue?

**Comment by kbrandl** [comment]
@bhatnagarsaddy @macOutlookExtensibility is the proper owner for this particular issue. @macOutlookExtensibility can you please assist?

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by bconners1005** [comment]
@macOutlookExtensibility @exextoc 
Pinging this old thread as this was put into Backlog a few months ago.  Has there been any momentum on this particular issue?  It impacts a large enough subset of users for a plug-in that we'd just like to make sure we have a spotlight every once and awhile so we can adequately update our user base.

**Comment by lindalu-MSFT** [comment]
@macOutlookExtensibility  Do we have an internal bug number to track this issue?

**Comment by exextoc** [comment]
The issue is not there in New Outlook for Mac which is in production now. If you see the problem there, you can reopen the issue.
