### ISSUE TITLE
Some Range highlight colors are not saved

### ISSUE THREAD

**Issue by alexmalcoci** [OfficeDev/office-js#3950]
# Provide required information needed to triage your issue
Some highlight colors are not saved when applied to ranges inserted with `insertText`. When applying the highlighting manually, all colors are saved.

Using the following snippet, insert a few highlighted ranges in the doc:
```js
await Word.run(async (context) => {
  var selection = context.document.getSelection();

  for (var color of [
    // these are saved
    "Black",
    "Blue", 
    "Gray", 
    "Green", 
    "Lime", 
    "Olive", 
    "Purple", 
    "Red", 
    "Teal", 
    "Yellow",

    // these are not saved
    "DarkBlue",
    "DarkRed", 
    "LightGray",
    "Pink", 
    "Turquoise", 
  ]) {
    var textRange = selection.insertText("test", Word.InsertLocation.before);
    textRange.set({
      font: {
        highlightColor: color
      }
    });
  }

  await context.sync();
});
```

This is the result, as expected:
![image](https://github.com/OfficeDev/office-js/assets/34559371/a565883c-cc5c-4658-8356-4104dd1be181)

Next, reload the page. Notice how the last 5 ranges lose their highlight colors
![image](https://github.com/OfficeDev/office-js/assets/34559371/f5bbd36a-9e00-46da-a077-a53b630d9c40)

The docs [here](https://learn.microsoft.com/en-us/javascript/api/word/word.font?view=word-js-preview#word-word-font-highlightcolor-member) mention that the supported standard colors for highlight are `"Yellow", "Lime", "Turquoise", "Pink", "Blue", "Red", "DarkBlue", "Teal", "Green", "Purple", "DarkRed", "Olive", "Gray", "LightGray", and "Black"`. Out of these, only 5 are having this issue `"DarkBlue",
      "DarkRed", 
      "LightGray",
      "Pink", 
      "Turquoise"`, as seen above.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.17213.41019
* Operating System: MacOS Sonoma 14.1.2 (23B92)
* Browser (if using Office on the web): Chrome 120.0.6099.62
 
## Expected behavior

All standard colors should save properly when applied as highlighting on a range

## Current behavior

Some highlighted colors are lost after reloading the page.

## Steps to reproduce

1. Run the code above in a word addin
2. Refresh page

## Link to live example(s)

1. [Gist](https://gist.github.com/alexmalcoci/5a47d0bf9f58242157ee4b5a72a1d917)

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by alexmalcoci** [comment]
@penglongzhaochina @yilin4 Any updates on this?

**Comment by yilin4** [comment]
@alexmalcoci Thanks for reporting this issue.  It has been put on our backlog<Bug#8657817> for internal track. We will keep track of this issue and let you know if there are any updates.

**Comment by alexmalcoci** [comment]
@yilin4 Is it possible to get this prioritized? Seems like an easy enough fix and it would unblock us. The number of supported highlight colors is small enough as is, but this bug takes away a whole third of that list.

**Comment by yilin4** [comment]
@alexmalcoci Could you estimate the user base and the revenue from your new add-in? So, we can better escalate this case and priories it.

**Comment by alexmalcoci** [comment]
@yilin4 Around 70,000 users with $30 million in revenue.

**Comment by alexmalcoci** [comment]
@yilin4 Any updates on this? Now the DarkGreen has stopped being saved too.

**Comment by yilin4** [comment]
@alexmalcoci Sorry for responding late. I have found a workaround for you. You can set the color by the RGB number, for example, the "DarkBlue" is "# 000080". It can work well.

**Comment by alexmalcoci** [comment]
@yilin4 Thank you, this seems to work. Can you confirm that DarkRed is `#800000` and DarkGreen is `#008000`?

**Comment by yilin4** [comment]
@alexmalcoci Yes, they are.

**Comment by alexmalcoci** [comment]
@yilin4 Can you tell me the exact cause of this bug? In another part of the application I am inserting highlighted text on the backend using Apache POI. Then when I load the document in the Word Online editor, I don't see the highlighting, even though the markup is there. I do see the highlighting if I switch to view mode in Word Online or open the document with the desktop version of Word. What's interesting is that if I add the highlighting from the Word Online UI, it works consistently all the time for all colors. What does highlighting from the UI do that I'm not doing programmatically? What's the difference?

**Comment by yilin4** [comment]
@alexmalcoci Through my investigating, I think this bug is caused the color name can't correspond to the right RGB number. I think a good way is to use the RGB number to change the highlight color in every place.

**Comment by alexmalcoci** [comment]
@yilin4  Has any progress been made on fixing the highlight colors bug? Even though the proposed workaround works for adding the color directly, if you set the colors outside of office js then load the document, you get all kind of bugs where some colors are visible and some are not, but only in edit mode. Can this issue please be escalated?

**Comment by yilin4** [comment]
@alexmalcoci I have investigated this issue, and found that the colors which are supported by the UI highlight can be supported well by API.  (all UI supported highlight colors are "#000000" "#0000FF" "#00FFFF" "#00FF00" "#FF00FF" "#FF0000" "#FFFF00" "#FFFFFF" "# 000080" "#008080" "#008000" "#800080" "#800000" "#808000" "#808080" "#C0C0C0") And recommending to use color code rather than color name to set the highlight color.
And I want to know if you just use the color in the list, this kind of issue still occurs "if you set the colors outside of office js then load the document, you get all kind of bugs where some colors are visible and some are not, but only in edit mode."
Thanks.
