### ISSUE TITLE
Dynamic Cell ID Assignment for Excel Worksheets: Maintaining Unique Identifiers during Row and Column Insertions

### ISSUE THREAD

**Issue by chetankotwal** [OfficeDev/office-js#3951]
My Environment
Platform : PC desktop
Host: Excel
Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2309 Build 16.0.16827.20166) 64-bit
Operating System: Windows 10 pro

Dear Team,

I'd like to express my gratitude for the prompt support, which has been invaluable for our business.

Currently, I'm working with a workbook containing over 115 worksheets, and I have several queries:

1) I need to assign unique IDs to specific sets of cells within a worksheet. It's essential that if I insert a row or column, the assigned ID should seamlessly move with the corresponding cell. For example, if cell B1 has an ID of "001," and I insert a column before column 1, the ID "001" should now be associated with cell B2.

2) The workbook takes considerable time to load with 115+ tabs in Excel desktop. Are there alternative methods to improve loading time?

3) I've noticed that using named ranges for certain cells becomes sluggish when the named range extends beyond 30,000 cells. Is there a way to optimize this and enhance Excel performance?

Your assistance in resolving these concerns is crucial for the efficiency of our operations. 
Thank you for your continued support.

**Comment by penglongzhaochina** [comment]
Hi @chetankotwal ,

For the question1, you can use "named range" to do that.
For the question2 and question3, 

Due to you have lots of sheets or named range, it be processed one by one. So it leads a low performance. You can try to reduce the number of sheets or named range to resolve this.
Thanks!

**Comment by chetankotwal** [comment]
Hi @penglongzhaochina ,
We are already using named range for point no 1. But due to this we are facing loading issue which is I mentioned in point no 3.
Is there any alterative or any other cell property which we can use??

**Comment by chetankotwal** [comment]
Hi @penglongzhaochina  is there any update?

**Comment by chetankotwal** [comment]
Hi @penglongzhaochina is there any update?

**Comment by penglongzhaochina** [comment]
> Hi @penglongzhaochina , We are already using named range for point no 1. But due to this we are facing loading issue which is I mentioned in point no 3. Is there any alterative or any other cell property which we can use??

Currently, no. 

For new feature request, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.
