### ISSUE TITLE
Addin not visible for m365 subscription and gmail user in outlook native app on mac due to that my marketplace offer got rejected

### ISSUE THREAD

**Issue by kamarajcalm** [OfficeDev/office-js#3954]
# Provide required information needed to triage your issue

## Your Environment

* Platform [Mac]:
* Host [outlook]:
* Office version number: 16.8(23121017)
* Operating System: Mac os
* Browser (if using Office on the web) : it works fine
* accounts not working : microsoft 365 subscription and gmail account
## Current behavior
The addin icon is not visible in the addin ribbon area but in browser it is showing and working properly 

## Steps to reproduce

1.Install my manifest file in the outlook native app with m365 subscription and gmail account 
2. In web it is working fine

here is my manifest file

https://gist.githubusercontent.com/kamarajcalm/bd92e1fef0c367c7dbd8ece8fe0dddf0/raw/3fca6f76055683fc4cc4ec33030548666df93b22/manifest.xml
do correct me if i need change anything on my manifest file or what is the reason . my outlook addin is for outlook calendar event

**Comment by veris-kamaraj** [comment]
can any one help me on this

**Comment by exextoc** [comment]
@kamarajcalm We are trying to reproduce this. In the meantime, it would help if you could share a repro video of your scenario.

**Comment by kamarajcalm** [comment]
@exextoc https://drive.google.com/file/d/1b_jtxnmfj2iuz5dAgTZV-LxvJuH3pWpE/view you can see on this video after adding manifest file it not appearing on native app but appearing on outlook web . please let me know if you need more information

**Comment by ajays-msft** [comment]
@kamarajcalm - Please update the Host section in manifest, something like:
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">

    <Hosts>

      <Host xsi:type="MailHost"/>

Host section details
https://learn.microsoft.com/en-us/javascript/api/manifest/host?view=common-js-preview#child-elements

As per documentation:
The values of child elements in the inner VersionOverrides override the values of the same-named elements in the parent VersionOverrides and the grandparent OfficeApp element.
Sample :https://learn.microsoft.com/en-us/office/dev/add-ins/develop/xml-manifest-overview?tabs=tabid-3#manifest-v11-xml-file-examples-and-schemas


Alternatively, you can also remove the Hosts section.

**Comment by kamarajcalm** [comment]
@ajays-msft Thanks for the help our app is live now
