### ISSUE TITLE
Outlook Add-in: Repeated User Reauthentication Prompt after Inactivity (9-10 days)

### ISSUE THREAD

**Issue by ZabeehUllah** [OfficeDev/office-js#3956]
# Issue Overview
Users are consistently prompted to reauthenticate upon re-opening Outlook adddin (desktop only) after an extended period of inactivity (approximately 10 days). This reauthentication prompt occurs without any prior logout API call or notification, causing disruption and inconvenience to users.

## Environment
* Platform :PC desktop, Mac
* Host: Outlook
* Office version number: ______
* Operating System: Windows, MacOS
 
## Expected behavior
The add-in should maintain user sessions or implement a token refresh mechanism to prevent frequent reauthentication prompts, and user shouldn't logout after long periods of inactivity, enhancing user experience and workflow continuity.

## Current behavior
The user is logged out form his account (inside outlook add-in) after inactivity for about 9-10 days

## Steps to reproduce
1. Open Outlook.
2. Use the add-in regularly for several days.
3. Leave the add-in inactive for approximately 10 days.
4. Reopen Outlook and notice the prompt for reauthentication without any prior logout action.

# Provide additional details
1. Add-in manifest file link (https://drive.google.com/file/d/1Dn7cazLKnEr3X8ztvqaEPme0eVTN8aJi/view?usp=sharing)

## Useful logs
![usman](https://github.com/OfficeDev/office-js/assets/22549491/1c40c33f-af03-4204-b3b8-6554bdc21f70)

 Recently, our logs captured an instance where a user, logged in at **2023-12-15 17:27:04**, was abruptly redirected to the login page upon accessing the add-in again on **2023-12-28 21:05:43**, without any preceding logout API call logged in between.
 
 I used this query to access the above logs in my DB
 
` SELECT * FROM user_apps_activities WHERE username = "usheikh@xiqinc.com" AND devicetype = "outlook" AND (eventname = "log_in" OR eventname = "user_logout") ORDER BY id DESC;`

**Comment by exextoc** [comment]
@ZabeehUllah What type of authentication is being used and which addin apis are being used for it?

**Comment by ZabeehUllah** [comment]
@exextoc We are using token based (JWT) authentication. In case of based SSO login authentication we are using SAML based authentication. For sso we are using  Office.context.ui.displayDialogAsync (Office Dialog API). In normal flow we are using REST APIs; using bearer for authentication

**Comment by exextoc** [comment]
@ZabeehUllah What do you mean by 'reauthenticate upon re-opening Outlook adddin'? Who is authenticating user here, is it addin backend? Can you describe the complete flow. Is the problem observed in OWA or its only Windows Desktop and Mac Clients only?

**Comment by ZabeehUllah** [comment]
@exextoc If user opens add-in after 9-10 days, login page is shown to the user. Although the user hasn't logged out himself neither has the cookie reached its expiration time or any token is expired. It's like the outlook looses the context of add-in after long period of inactivity.

**Comment by exextoc** [comment]
@ZabeehUllah Can you share the login page pic that you see after 9-10 days. Also help us by answering the following:
1. Who is authenticating user here, is it addin backend? 
2. Can you describe the complete flow. 
3. Is the problem observed in OWA or other clients like Windows Desktop and Mac Clients also show the same issue?

**Comment by ZabeehUllah** [comment]
@exextoc I have added the login screen below.
1) We are using our own backend for authentication.
2) The flow is that user signs in the outlook add in and after 9-10 days when user comes back and open the add in, the login screen appears, although the user hasn't logged out himself explicitly. It's like add in looses the context of add in and clears everything.
3) It's the issue with outlook app on desktop only

![logn](https://github.com/OfficeDev/office-js/assets/22549491/d80d6cf1-6e77-4faa-a64d-6bc2f13ac421)

**Comment by akagarwa-msft** [comment]
For fetching the token are you using getAccessTokenAsync API?

**Comment by ZabeehUllah** [comment]
No I am not using this API. After Dialog opens, I login with my microsoft credentials, which return a `token`, and I send that token to our backend, which authenticates our user to the app and user is logged in.

**Comment by akagarwa-msft** [comment]
That means it's not related to any of the js APIs. It's the way how you are storing the token and what's the expiry time for it.
