### ISSUE TITLE
Excel office add-in - document setting size limit - issues while persisting and retrieving data

### ISSUE THREAD

**Issue by DJay921** [OfficeDev/office-js#3957]
I want to save some JSON object (using JSON.stringify) to my document settings however I noticed that the settings can only hold around 1MB or so of data. I tried a few things but this always seems to be the issue and starts throwing a `_RichApi.Error: The argument is invalid or missing or has an incorrect format_`_. error when I save more than a few MB of data, even though from the saved size of the Excel file I can see the correct size which seems to incorporate the data (which in my case is around 12-15 MB of data). Is this understanding correct on the size limit? and is there any way I can use document settings to store more data?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __PC____
* Host [Excel, Word, PowerPoint, etc.]: ____Excel__
* Office version number: ___2021___
* Operating System: ___Windows 11___
 
## Expected behavior
The add-in seems to work without an issue if the document size is smaller, and I expected this to work the same way for 15-20 MB of data. 

## Current behavior
As mentioned above, it throws a Rich Api error without much relevant information on the size limit. 

## Steps to reproduce
I'm trying to save a JSON object after converting to string (using JSON.stringify) to my document settings. When I'm working with a document settings of around 333 KB - 1 MB this is working without any issue, however when the size of the JSON object exceeds a few MB or so, it throws this error 
<img width="446" alt="image" src="https://github.com/OfficeDev/office-js/assets/14841097/022fcd85-1c81-4e69-8fde-9a9d094da28f">

**Comment by DJay921** [comment]
If I use the common Office JS Api, I notice that the document setting saved I can access while the document is opened, however if I close and reopen the document, it wipes off the data and I see Null when I try to retrieve that particular setting. Just FYR, I'm using the CDN to load the Office JS api     `<script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>`

I had read that currently there is no limit on the settings size, which was earlier around 2 MB.

**Comment by SiruiSun-MSFT** [comment]
Hi @DipanshuJuneja, I'm afraid that you might hit the limitation of our JS API, which is 5MB at most. If you need to store information more than the limitaion, if would be better for you to break them up and store them each by each.
As for the NULL issue you mentioned above, I would like to know, whether the set operation has been executed successfully？Also does the save already finished？If setting and saving are both complete, you still cannot retrieve stored content, could you please provide a repro code to us, which will help us do more investigation.
Thanks for your patience!

**Comment by DJay921** [comment]
Hi @SiruiSun-MSFT, thank you for the response. Please see the below code and output screenshot which is working for saving the state and retrieving before closing document (around 11 MB). 
```
const saveCurrentSettings = async () => {
  console.log("calling save settings");
  window.Office.context.document.settings.set(
    "doc_state",
    "x".repeat(10 * 1024 * 1024)
  );

  window.Office.context.document.settings.saveAsync(function (asyncResult) {
    if (asyncResult.status == window.Office.AsyncResultStatus.Failed) {
      console.log(asyncResult.error.message, "SAVE FAILED");
    } else {
      console.log("Settings saved.");
      const doc =
        window.Office.context.document.settings.get("doc_state");
      console.log(doc);
    }
  });
};

const saveDocumentStateSnapshot = async (args) => {
  console.log("save document state button called, saveDocumentStateSnapshot");
  saveCurrentSettings();
  args.completed();
};

const getData = async (args) => {
  console.log("get data called");
  const doc = window.Office.context.document.settings.get("doc_state");
  console.log(doc);
  args.completed();
};

```
<img width="817" alt="image" src="https://github.com/OfficeDev/office-js/assets/14841097/36ae7f48-977f-4f2e-8c2b-5d44ce92d927">
But when I try to retrieve the data after reopening the document, I see Null as below SS
<img width="513" alt="image" src="https://github.com/OfficeDev/office-js/assets/14841097/d2ce9a42-8928-400a-9c9e-c35528e8cee4">

**Comment by SiruiSun-MSFT** [comment]
Hi @DipanshuJuneja, as I mentioned before, the setting argument over 10MB will hit some error due to the limitation. Thus the setting may not be executed successfully. That may be the reason why you cannot get the value after that. Could you repro the issue on a small argument?

**Comment by DJay921** [comment]
Hi @SiruiSun-MSFT, apologies if there was a confusion in what I meant by my earlier comment. What I meant was, for the higher size, a) If I use the Office common API to store document settings, it allows me to save and retrieve while working with the document but not retrieve after closing the document, however b) If I use the Excel Setting Collection class to store document settings, its throwing the RichAPI.Error and does not allow me to even save that data in the first place. 

I was expecting both these APIs to work similarly in behavior which was causing a little confusion. 

However, I understand that this is due to the Office JS size limitation which you described above for 5 MB, and your suggestion to break and store each by each worked for me. Thank you for the suggestion.
