### ISSUE TITLE
Strange background color behavior

### ISSUE THREAD

**Issue by jkpieterse** [OfficeDev/office-js#3959]
When I open my new Name Manager for Excel task-pane add-in (available in the Excel store), strange visual effects happen.

1. After opening the task-pane, the background of the "empty" areas is grey. If I minimize Excel and then alt-tab back to it, the same background is now white
2. If I drag the taskpane so it becomes floating and then resize the taskpane, the background starts showing vertical lines
3. After a minimize and alt+tab back, the taskpane appears white again.
4. Dragging the taskpane shows that the background actually isn't white, but transparent!

See attached video.

# Provide required information needed to triage your issue

## Your Environment
Microsoft Excel
16.0.17029.20108
Microsoft Windows 10 Pro 22H2 (64-bit Build 19045)
 
## Expected behavior
I expect the background color to stay the same!

## Current behavior

See above.

## Steps to reproduce

1. install my name manager from the store and open it
2. After opening the task-pane, the background of the "empty" areas is grey. If I minimize Excel and then alt-tab back to it, the same background is now white

Uploading Taskpane Issue.mp4…

3. If I drag the taskpane so it becomes floating and then resize the taskpane, the background starts showing vertical lines
4. After a minimize and alt+tab back, the taskpane appears white again.
5. Dragging the taskpane shows that the background actually isn't white, but transparent!

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by DJay921** [comment]
I had opened this issue https://github.com/OfficeDev/office-js/issues/3817. Not sure if this is the same issue, you can check if this resolves your issue by setting a background color to your body tag.

**Comment by zhenhuangMSFT** [comment]
@jkpieterse  Thanks for reporting the issue. I cannot repro this on my machine with a build version of 16.0.17231.20008. Could you please update to the latest version and let me know if the issue still persists? 
![image](https://github.com/OfficeDev/office-js/assets/91410047/79fa100f-f1b8-401a-8f86-d11bf0a3c906)

**Comment by jkpieterse** [comment]
@zhenhuangMSFT Thanks for responding. As it happens, I updated my css file yesterday, with precisely the solution suggested by @DipanshuJuneja. For me this issue is now resolved, but perhaps it would be a good idea to update the boilerplate css that is produced by yo Office with this fix?

**Comment by jkpieterse** [comment]
I've found a fix, but suggest to update the boilerplate css produced by yo Office.

**Comment by zhenhuangMSFT** [comment]
Thanks for your suggestion! I will talk to our experts.
