### ISSUE TITLE
In Outlook-Office365, Addin Icons fail to load  with some IE settings enabled.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#396]
@kbrandl sorry for the mention, but this is another issue we are experiencing right now with Outlook-Office365, with certain settings enabled for IE. Please let me know if this is the wrong channel to submit this issue and I will move it to the right channel. Thanks!

Currently, we are seeing issues with icons in Outlook Office365. Our Outlook office365 is not showing the right icons for any of our command button add-ins. The image below shows the issue we are seeing :
![outlook365missingicons](https://user-images.githubusercontent.com/3444844/52989627-406d4e00-343f-11e9-91ff-81b5a648c0e7.PNG)

After several tests and investigation, we have found out that this behaviour is actually caused by settings in IE (Internet Explorer). To reproduce this problem, one needs to do the following.

1. Delete all files in the Office WEF/resources in %localappdata% like the image below shows :
![outlook365wefresources](https://user-images.githubusercontent.com/3444844/52989721-b2459780-343f-11e9-9f23-2d643a1dd293.PNG)

2. Once all files are deleted, launch IE, click on the gear icon and then set it to delete browsing history.
 ![deletebrrowsinghistory](https://user-images.githubusercontent.com/3444844/52989767-ddc88200-343f-11e9-870a-887bb213f4c9.PNG)

3. Click on the "Advanced" tab of Internet options, check the box for "Do not save encrypted pages to disk" under security, and then click "apply".
![donotsaveencryptedfiles](https://user-images.githubusercontent.com/3444844/52989812-0d778a00-3440-11e9-85cc-c3fdf681518a.PNG)

4. Close all running instances of IE, and outlook365.
5. Launch Outlook365 and wait for some time for Outlook to load the icons for the add-ins.

Note, the **EXPECTED** behaviour is shown in the image below : 
![outlook365normaloperations](https://user-images.githubusercontent.com/3444844/52989883-6b0bd680-3440-11e9-9015-cbf7dbee7fce.PNG)

(related content in the docs: [Office Add-ins XML manifest](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?tabs=tabid-1))

**Comment by kbrandl** [comment]
@exextoc can you please investigate this issue?

**Comment by glr0221** [comment]
@kbrandl thank you so very much for responding to my inquiry.  @exextoc Thank you in advance for your support.

**Comment by exextoc** [comment]
I can repro the issue using your steps. I am investigating and checking with other product team members.

**Comment by exextoc** [comment]
This is a current limitation that icons used for addins must be cached. The IE setting applies system wide in Windows, instead of just IE and so the setting prevents the icons from being saved locally by Outlook. The workaround, as you found, is to disable "Do not save encrypted pages to disk".

**Comment by glr0221** [comment]
Thank you @kbrandl @exextoc. Is there any time frame for fixing this limitation?

**Comment by exextoc** [comment]
This is in our backlog. Currently, however, we do not currently have a timeline to share.
