### ISSUE TITLE
Cannot install add-in though it is allowed in the admin centre: "Office 365 has been configured to prevent individual acquisition and execution of Office Store Add-ins"

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#3961]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.17230.42306
* Operating System: Windows
* Browser (if using Office on the web): Chrome latest
 
## Expected behavior

Can use the [Velixo add-in](https://appsource.microsoft.com/en-us/product/office/wa200002311?tab=overview) from AppSource when the Office admin centre is configured to allow store-based add-ins.

## Current behavior

![image](https://github.com/OfficeDev/office-js/assets/5159662/c8a9e2bd-e7a1-44fb-a196-a50246890eff)

Even though in the Admin centre the setting is enabled:

![image](https://github.com/OfficeDev/office-js/assets/5159662/11a63b09-9e8f-4189-b5fc-de2bf9aef484)

The issue is sporadic and does not always replicate.

## Steps to reproduce

- Session ID: 0cd9e34b-bbb9-430c-86ca-0ee75b880f1a
- Link to the add-in: https://appsource.microsoft.com/en-us/product/office/wa200002311?tab=overview

The issue happened on a new workbook. Eventually we were able to load the add-in successfully in another tab.

cc @gmichaud

**Comment by zhenhuangMSFT** [comment]
@wh1t3cAt1k Thank you for reporting the issue and share the session id with us. Just to clarify, how did you get that error pop-up? By clicking the add-in flyout?

**Comment by LiubovKabir** [comment]
@zhenhuangMSFT the issue occurred when I clicked on the add-in icon in the Toolbar area. 
![image](https://github.com/OfficeDev/office-js/assets/1867964/89a247e8-2d55-43ad-9258-b3e9f12c67ae)

**Comment by wh1t3cAt1k** [comment]
Thanks @LiubovKabir, also important to note that it happened on a new workbook.

**Comment by zhenhuangMSFT** [comment]
Hi @LiubovKabir @wh1t3cAt1k , our log shows that the server responded with a disabled status which might be a transient issue that happens not long after the setting update is made. Could you let me know if you are still seeing this issue?

**Comment by gmichaud** [comment]
@zhenhuangMSFT I have also experienced the same issue a few weeks ago, but problem is gone. Add-in permissions/settings were not changed on our end.

**Comment by wh1t3cAt1k** [comment]
@zhenhuangMSFT it is most likely a server-side bug since we haven't touched these settings in a long, long time. But sporadically Excel reports that add-in installation is blocked even if it's not true.

Could it be a situation where the settings fail to be obtained from the back-end, but instead of showing a proper error, the host application simply assumes that add-in installation is forbidden?

**Comment by gmichaud** [comment]
Same thing happened to me yesterday. Closing browser completely and opening new excel workbook was the only way out. Refreshing the page or opening new tab was not enough to solve the issue.

**Comment by zhenhuangMSFT** [comment]
Hi @gmichaud, thanks for the update! Could you share us the Session ID with us next time you experience the issue? It is under `file` tab, `About` section.

**Comment by zhenhuangMSFT** [comment]
Please feel free to reopen if you encounter this again.

**Comment by wh1t3cAt1k** [comment]
@LiubovKabir are you still able to replicate this? Would you be able to provide a Session ID?

**Comment by xSloots** [comment]
This seems to be an issue at our company as well, but here store has been disabled, but velixio app has been allowed. But vanishes from a excel session with note addin store has been blocked. Upon several reboots it works again but then few days later same issue or some times directly after.

**Comment by gmichaud** [comment]
@xSloots I haven't seen the issue in a while -- thanks for chiming in, reach out to me directly if you have a Velixo issue I can help with.
