### ISSUE TITLE
Notification messages not showing up in old outlook thick client

### ISSUE THREAD

**Issue by VarshaJumanal** [OfficeDev/office-js#3962]
We used the below code to show the notification for our web add in. The same works on browser and new thick client but doesn't work for old thick client. 
## Current behavior
The notification doesn't appear. Attached the screenshot of notification appearing in browser and new thick client.

## Expected behavior
The notification should appear for all platforms(old/new thick client and browser)

## Steps to reproduce
const message = {
        type: Office.MailboxEnums.ItemNotificationMessageType.InsightMessage,
        message: "Email Validation Loaded.",
        icon: "Icon.80x80",
        //ispersistent:true,
        actions: [
          {
            actionText: "Validate Email",
            actionType: Office.MailboxEnums.ActionType.ShowTaskPane,
            commandId: "button",
            contextData: { a: "aValue", b: "bValue" }
          }
        ]
      };
      Office.context.mailbox.item.notificationMessages.replaceAsync("action", message);
 
<img width="448" alt="Notifications" src="https://github.com/OfficeDev/office-js/assets/152259032/c92bc860-cde1-49f4-a1bc-da3aaaede792">

**Comment by zhngx1** [comment]
Can you provide your build number for Outlook windows client?

**Comment by geetamshukla** [comment]
> Can you provide your build number for Outlook windows client?

<img width="568" alt="image" src="https://github.com/OfficeDev/office-js/assets/142812553/3cc5951d-26fb-4cf7-93cf-f30b20ddeec8">
[manifest.docx](https://github.com/OfficeDev/office-js/files/13889034/manifest.docx)


Please refer below screenshot from outlook client where the action link is not visible 
<img width="692" alt="image" src="https://github.com/OfficeDev/office-js/assets/142812553/0f3b4bd3-cc3c-425e-a20a-d4a4b384fe7f">

**Comment by geetamshukla** [comment]
> Can you provide your build number for Outlook windows client?

Any update on this issue . 

_**Even the default Addin created using office yo generator Task Pane add-in using the React framework is having this issue . 
The issue can be reproduced by creating office yo generator Task Pane add-in using the React framework and try loading the Manifest in Old Outlook thick client .The Newly created Addin will not show in Outlook Thick Client having office build 2311 .**_

https://github.com/OfficeDev/office-js/files/13888930/manifest.docx

**Comment by zhngx1** [comment]
Can you pass in a callback to see what error it returns? See method reference: https://learn.microsoft.com/en-us/javascript/api/outlook/office.notificationmessages?view=outlook-js-preview#outlook-office-notificationmessages-replaceasync-member(1)
