### ISSUE TITLE
Not able to import packages/libraries in launchevent.js file

### ISSUE THREAD

**Issue by VarshaJumanal** [OfficeDev/office-js#3963]
In order to reuse any function from another file or import a package to use in launchevent.js file, I want to be able to add import statements in launevent.js

Trying to use import statement like below:
for ex: import axios from 'axios'

## Current behavior
Import statements not working in launchevent.js where we have all handlers like onNewMessageComposeHandler, onMessageRecipientsChangedHandler etc

**Comment by Adrian-MSFT** [comment]
Hi @VarshaJumanal ,

What platform are you on?

On the Windows Outlook client, imports are not supported in the JS file used for launchevents, you would need to bundle all of your code into a single file: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#event-based-activation-behavior-and-limitations
