### ISSUE TITLE
How to get HTML of selection from Excel using office js.

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#3966]
My Environment
Platform : PC desktop
Host: Excel
Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2309 Build 16.0.16827.20166) 64-bit
Operating System: Windows 10 pro

Hi team ,
I want HTML from Excel.
If I select some range or I give namedRange to range and using that I want HTML for that range. Is there way to get HTML of selected Rang from excel.

**Comment by donlvMSFT** [comment]
Hi @Jayshiv1408Dev ,

Thank you for reporting! Sorry that there is no dedicated API yet.

We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). You could vote for existing ones or request a new feature there. Feature requests are considered when we go through our planning process. 

You could share more details about expected scenario so maybe we could get a workaround together?

Please let me know if you have any other questions. Thank you very much!
