### ISSUE TITLE
[Word] - Word for some reason delete content control of first column in Child table

### ISSUE THREAD

**Issue by ysobol** [OfficeDev/office-js#397]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

**Main reason:**
When user add new column for this specific Parent table , In this specific case, MS Word for some reason delete first content control of Child Table. On top of that MS Word delete it in some wrong way. 

**Steps:**
Create Template in Word Online
Add Parent Table with Any columns
Add new Row under Parent Table
Merge Cells in this row
Insert  Child table in this row
Download document from Online
Open It using Word Desktop

Delete Header Row of Child table using standard MS word tool
Right click on Parent Table >>> Insert New Column from right side

**!!! In this case Word for some reason delete content control of first column in Child table.**

**Comment by weshi** [comment]
@ysobol for the steps you listed, are they done by the Word JavaScript API, or you did it via the Word UI?

**Comment by dmashchenko** [comment]
Hi @weshi,
I'm the Engineering Manager of the MN Author team. See https://appsource.microsoft.com/en-us/product/office/WA104381471?tab=Overview
Yulia is one of our teammates.

I'm sure you can reproduce it manually, just using Word UI no coding is needed.
Please let me know if have some difficulties to reproduce it.
Thanks.

**Comment by kbrandl** [comment]
Please ignore the previous message from **msftbot**. The **Needs: author feedback** label was incorrectly applied to this issue; I've removed that label and this issue is no longer marked as stale.
