### ISSUE TITLE
Access to XMLHttpRequest at 'https://localhost:8000/lib/functions.json' from origin 'https://excel.officeapps.live.com' has been blocked by CORS policy

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#3970]
I'm trying to develop custom functions in Excel by JavaScript API. The environment is Mac OS and Excel Online (Chrome).

I follow the [tutorial](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-custom-functions-quickstart?tabs=excel-windows) and install the certificate by `npx office-addin-dev-certs install`. I can find and run the defined custom functions in Excel Online. We can see that `https://localhost:3000/dist/functions.json` is well loaded in Dev Tools.

Now, I want to add custom functions to one existing application of mine. I modify the manifest file by adding elements for custom functions, copy `functions.json` and `functions.js` to the `public/lib/` folder such that `https://localhost:8000/lib/functions.json` can be opened in a browser. Then I launch the application with the same certificate: `PORT=8000 HTTPS=true SSL_CRT_FILE=/Users/softtimur/.office-addin-dev-certs/localhost.crt SSL_KEY_FILE=/Users/softtimur/.office-addin-dev-certs/localhost.key ./node_modules/.bin/react-scripts start`. However, we can see that when loading `https://localhost:8000/lib/functions.json`, there is a CORS error and a red error icon on the left of the name `functions.json`; under the `Preview` and `Response` tabs, we see `Failed to load response data: No data found for resource with given identifier`.

[![enter image description here][1]][1]

Here are two screenshots with the working version on the left and the non-working version on the right:

[![enter image description here][2]][2]

[![enter image description here][3]][3]

Does anyone know what may be the reason why `https://localhost:8000/lib/functions.json` could not be well loaded?

  [1]: https://i.stack.imgur.com/ivbcm.png
  [2]: https://i.stack.imgur.com/6XzO8.png
  [3]: https://i.stack.imgur.com/Db7ex.png

**Comment by MiaofeiWang** [comment]
Hi @chengtie , May I know are you still experiencing this issue? If yes, I am considering if adding "Allow-Control-Allow-Origin" config in your webpack.config.js could resolve this error.

```JavaScript
devServer: {
    headers: {
        "Access-Control-Allow-Origin": "*",
    },
}
```
