### ISSUE TITLE
Implement custom Send  mail button in Task pane  for outlook addin usning office-js

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#3971]
We are developing office web Addin for outlook using event based (Smart  Alert)  .The Addin is generated using office yo generator Task Pane add-in using the React framework . 

We are showing the task pane on click of outlook Send using onSendHandler and using notification events . We want to send mail from taskpane custom send button once users acknowledges/ done some verification  . It seems the events/ properties are not available at present where I can code a custom send button  .  I don't want to call EWS /Graph API on click of custom send button . 
Is there any method/props available using which we can trigger the mail send . 

Current behavior: 
We are not  able to send mail from taskpane custom button without calling EWS /Graph API 

Expected behavior: 
We should we able to send mail from taskpane custom button without calling EWS /Graph API

**Comment by exextoc** [comment]
Currently we dont support any feature that enables addin to write send button functionality in task pane. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

Github Label: “Type: product feature request”
https://aka.ms/M365dev-suggestions
