### ISSUE TITLE
How to know if recipient got removed from mail. There is no explicit event like we have for attachment event.attachmentStatus=='added'

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#3972]
We are developing office web Addin for outlook using event based (Smart Alert) .The Addin is generated using office yo generator Task Pane add-in using the React framework . 

We are using OnMessageRecipientsChanged to validate recipient  and show the error message in taskpane using notification events as an when recipients are getting added/removed . 

OnMessageRecipientsChanged  triggers as an when we are adding /removing the recipients .There is no explicit event for recipient like we have for OnMessageAttachmentsChanged  event.attachmentStatus=='added' .

**Comment by exextoc** [comment]
At present the OnMessageRecipientsChanged has the following [RecipientsChangedEventArgs ](https://learn.microsoft.com/en-us/javascript/api/outlook/office.recipientschangedfields?view=outlook-js-preview).
Currently the events doesn't have details if recipients are getting added/removed. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

Github Label: “Type: product feature request”
https://aka.ms/M365dev-suggestions
