### ISSUE TITLE
We are storing user preferences in Outlook VSTO using MAPI .Is there any way we can transfer the  VSTO preference  to Outlook web Addin 

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#3973]
We are developing office web Addin for outlook using event based (Smart Alert) .The Addin is generated using office yo generator Task Pane add-in using the React framework .

We have an existing COM/VSTO addin where we have user preference stored . We want to reuse  those preference in WEB Addin . 
Is there any way we can retrieve COM/VSTO outlook storage data in offfice webAddin 

NameSpace nameSpace = this.app.GetNamespace("MAPI");
                Folder defaultFolder = nameSpace.Session.GetDefaultFolder(OlDefaultFolders.olFolderInbox) as Folder;
                StorageItem storage = defaultFolder.GetStorage("User_Personal_WhiteList_7B0BEAA1-FF96-418D-B63B-D0C623C36BE3", OlStorageIdentifierType.olIdentifyBySubject);
                if (storage.Size == 0)
                {
                    storage.UserProperties.Add("test", OlUserPropertyType.olKeywords, (object)Missing.Value, (object)Missing.Value);
                    storage.Save();
                }

**Comment by exextoc** [comment]
You can make calls against the server with Graph, and you should be able to retrieve your item. 

https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/office-365-rest-apis-for-mail-calendars-and-contacts

In general, it would be recommended you do this once, and then store it with the Add-in RoamingSettings, as that would avoid a Graph call every time you need to access it. Though this may not be possible if you still need to move settings back and forth. 

Also note that the Graph Call access the data on the *server* whereas, your VSTO Add-in will be accessing a local store of the message in Outlook Cached Mode. Hence updates to one, will not be reflected in the other until they have sync'ed.
