### ISSUE TITLE
Is the Auto Open Task Pane after installation feature available in Excel desktop? 

### ISSUE THREAD

**Issue by HugoAlbertoNieto** [OfficeDev/office-js#3975]
### Please, confirm whether the Auto Open Task Pane after installation feature is available in Excel desktop

I wanted to enhance the First Run Experience of my Excel addin by auto opening a task pane when the addin is first installed. My addin contains add-in commands, so the task pane will not open by default. I see there are two main articles in the documentation that are related to what I need:

https://learn.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-on-installation
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document

I will focus on the first one as I only need the task pane to open only when the addin is installed. The first document explains exactly what I need for my addin. It states that I should configure a default task pane as follows:

```
<Action xsi:type="ShowTaskpane">
    <TaskpaneId>Office.AutoShowTaskpaneWithDocument</TaskpaneId>
    <SourceLocation resid="Contoso.Taskpane.Url" />
</Action>
```

I did this and then I started testing in a local development environment using **Excel desktop in a Windows machine**. When I run `npm start`, an instance of Excel opens as usual and then the task pane automatically opens as well. So, everything is fine at this point.

However, when I sideload the addin using the manifest, the task pane will not open automatically. I went ahead and tested the same manifest in Excel online and Excel for Mac and in both cases the task pane opens automatically, so the issue seems to be present only in Excel desktop.

I know the first article also contains a note stating the following:
![image](https://github.com/OfficeDev/office-js/assets/53156762/95af3154-da35-4c17-985a-f388fbe4db9c)

But the fact that this works in a local development environment and it also works in Excel for Mac, makes me wonder.. So, is this feature still under development for Excel destop in Windows?

Thanks.

**Comment by zhenhuangMSFT** [comment]
@HugoAlbertoNieto Thanks for sharing your findings with us. The auto-launch feature is supported on web, desktop and mac now. Looks like the document needs some update. We are investigating on the inconsistency of auto-launch behavior with sideload.

**Comment by yuc014** [comment]
Hi @HugoAlbertoNieto,
There are many ways to sideload addins for different platforms. Currently, for sideload addin, we only support autolaunch "registered" type of addins. This is only supported by the latest version of MAC and Win32(not Semi-annual version).

1. For WXP Online
[Sideload Office Add-ins to Office on the web - Office Add-ins | Microsoft Learn](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing) (Should NOT autolaunch)

2. For WXP Desktop


- [Sideload Office Add-ins for testing from a network share - Office Add-ins | Microsoft Learn](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins)(Should NOT autolaunch)

	

- Registry way(Should autolaunch):
If your addin is generated by "yo office", then after you "Yarn start" your addin, you can see manifest is saved in your register editor. (Under the path Computer\HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Wef\Developer)
![MicrosoftTeams-image (8)](https://github.com/OfficeDev/office-js/assets/87364252/c492465b-8837-4e3e-88c5-0cb77d1743e5)
Then open WXP desktop, "Home"->"Add-ins"-> your sideload addin should under "Developer Add-ins".

3. For WXP Mac
	[Sideload Office Add-ins on Mac for testing - Office Add-ins | Microsoft Learn](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-mac)(Should autolaunch)
	
And as you said your sideload addin is working on Excel online and mac, can you give me your sideload steps for Excel online?
And for Excel desktop, you can see there is one way can work. If it still cannot work, please provide me your excel version, and a live recording is better.
Thanks.

**Comment by HugoAlbertoNieto** [comment]
Thanks @yuc014 @zhenhuangMSFT!

Here are my comments:

1. **For WXP Online (Should NOT autolaunch)**: Here are the steps I have used in Excel online:

- Open an incognito window in Chrome.
- Paste a URL of an Excel document in the address bar.
- Go to Home -> Get Addins -> Upload My Addin -> Browse. Then I browse to the manifest of the addin and I click on Load. The addin loads and the taskpane autolaunches. It is essentially the same process you mentioned above, but the UI is slightly different for me.

3. **For WXP Desktop**

- For WXP Desktop (Should NOT autolaunch): This is the method I have used to sideload the addin in Windows. Thanks for confirming that it should not autolaunch!

- Registry way (Should autolaunch): I was not aware of this way to sideload the addin. I have tried out and the task pane autolaunches correctly. The only minor issue is that the callout of the `<GetStarted>` node from the manifest does not show up.

4. **For WXP Mac (Should autolaunch)**: This is the method I have used to sideload the addin in Mac and it works fine.


Now my question is the following: Suppose that I submit my manifest for approval to the Microsoft Appstore and it gets approved, After that, a user finds my addin in the Microsoft Appstore and decides to install it in Windows Excel desktop using Home -> Add-ins -> Get Add-ins -> Add. Which behavior of the taskpane will this user see? Will the taskpane autolaunch for this user?

Thank you very much for your help!

**Comment by yuc014** [comment]
Hi @HugoAlbertoNieto,

Now, the autolaunch feature is supported through various approaches:

1. Registry: As demonstrated above for sideloading during the testing phase of add-ins under development.
2. In-Client Store: If your add-in is uploaded to the store, this approach supports autolaunch.
3. Central Deployment: Admins can deploy the add-in in Microsoft 365 admin center, and this approach supports autolaunch.
4. App Source: Users can install the add-in from [Microsoft AppSource](https://appsource.microsoft.com/en-us/marketplace), autolaunch is supported through this channel.
5. And more. 

> I submit my manifest for approval to the Microsoft Appstore and it gets approved, After that, a user finds my addin in the Microsoft Appstore and decides to install it in Windows Excel desktop using Home -> Add-ins -> Get Add-ins -> Add.

This belongs to type 2, autolaunch is supported.

**Comment by HugoAlbertoNieto** [comment]
Thanks @yuc014. I really appreciate your help. 
This should be all I need regarding with this topic right now.

I have created a new issue for a different topic, which hopefully you or someone from the team can help us with:

https://github.com/OfficeDev/office-js/issues/3987

 Thank you very much again!
