### ISSUE TITLE
why a style not working same on desktop and office web?

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js#3977]
this is very big issue for my add-in I am using a style that is working on office word desktop but not work same on office wed 

on desktop looking like this 

![image](https://github.com/OfficeDev/office-js-docs-reference/assets/134502135/79ef18d4-b6e1-4ce5-ae88-0c26b2990e2e)

on web 

![image](https://github.com/OfficeDev/office-js-docs-reference/assets/134502135/5911ab05-fdbf-405b-ae91-d02521f44923)

both images are the same document but a line not showing on web top side of table and bottom side of table this is very important for me

this is document [document llink](https://docs.google.com/document/d/1HtyevoZQei91vZuiG6TW6m4cGVrD0jI4/edit?usp=sharing&ouid=103615190750648517495&rtpof=true&sd=true)

please check this and fix it this is very important for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2bcd9deb-cbd4-9248-a87a-5af781f512c1
* Version Independent ID: e9376518-ec5c-d8e4-c04b-b5997bd42441
* Content: [Word.Style class - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/word/word.style?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.style.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.style.yml)
* Service: **word**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Hi @junaid042,

Let me transfer this to the office-js repo, where product issues are tracked.

**Comment by junaid042** [comment]
@AlexJerabek thanks for your time this is very important to me please fix this issue and I see this line is also showing on Google Doc only not showing on office web

**Comment by junaid042** [comment]
@zhenhuangMSFT any update

**Comment by junaid042** [comment]
any update @xiruatms

**Comment by xiruatms** [comment]
@junaid042 , thanks for reporting this.

Just want to confirm that how you created that document. I just downloaded that file and opened with Word Online, it should be working as following:

![image](https://github.com/OfficeDev/office-js/assets/40648203/d2e89710-481c-49fe-8d43-3b2b44e1ab3b)

That'll be great if you can share your codes snippet and/or the steps to repro this issue. Thanks.

**Comment by junaid042** [comment]
Hi @zhenhuangMSFT thanks for your time,
In your screenshot you're using office web or anything else  
I have not paid version of office 365 and simple I open this document in web office please see screenshot lines are not showing 

![image](https://github.com/OfficeDev/office-js/assets/134502135/0d6426ed-fa31-49db-956d-b8bbbae3b6f9)

this document design created with open xml

this is my open xml file you can create it on your side [ .xml file link](https://drive.google.com/file/d/1MwmqpUfpsHL70AC0PqKtruOTN9WnMkii/view?usp=sharing)

use this on your side

`   


         var Mapxml= "https://localhost:44337/Mapxml.xml";
         const myOOXMLRequest = new XMLHttpRequest();
         let myXML;
         myOOXMLRequest.open('GET', Mapxml, false);
         myOOXMLRequest.send();
          if (myOOXMLRequest.status === 200) {
              myXML = myOOXMLRequest.responseText;
         }
         
         await Word.run(async (context) => {
          const range = context.document.getSelection();
          range .insertOoxml(myXML , Word.InsertLocation.replace);
          })

`

**Comment by xiruatms** [comment]
@junaid042 , thanks for your reply.

But I'm not quite sure about your statement here: "I have not paid version of office 365 and simple I open this document in web office". What "web office" are your referring please?  

Following is another one for my personal account on onedrive.
![image](https://github.com/OfficeDev/office-js/assets/40648203/052dc44e-2bb3-4080-8a3a-34646c9d27fb)

Will you please share with me more details about "web office" you're using?

**Comment by junaid042** [comment]
Hi @zhenhuangMSFT and @xiruatms , Please check this document [Style error.docx](https://github.com/OfficeDev/office-js/files/13968674/Style.error.docx)
when you download document from my previous link its style are changed I don't how please check this thanks

**Comment by junaid042** [comment]
please take a look at this [Video link](https://drive.google.com/file/d/1NG5jjNRFbYVJEuLKJu6ystxGC2bI_CmT/view?usp=sharing)

**Comment by junaid042** [comment]
Hi @zhenhuangMSFT , @xiruatms 
any update

**Comment by junaid042** [comment]
@xiruatms @zhenhuangMSFT @AlexJerabek , this is very important for our add-in we have a big Product(add-in) and this is main design in our add-in, Please fix this issue on web word or please give me any update on this.

**Comment by xiruatms** [comment]
@junaid042 , thanks for your patience.

I've contacted multiple experts discussing your issue. Here're the current findings:

In your latest test document, it's identified that there's a customized style "BlockLine" used in the document as following screenshot shown.
![image](https://github.com/OfficeDev/office-js/assets/40648203/281c8307-fcef-44c4-b817-00eaf13debd8)

This can also be confirmed by xml you posted:
`<w:style w:type="paragraph" w:customStyle="1" w:styleId="BlockLine">
					<w:name w:val="Block Line"/>
					<w:basedOn w:val="Normal"/>
					<w:link w:val="BlockLineChar"/>
					<w:rsid w:val="000F12FE"/>
					<w:pPr>`

Unfortunately, customized paragraph styles with border settings are not supported on Word Online now. This is not an API limitation, but feature limitations.

**Comment by junaid042** [comment]
Hi @xiruatms thanks for reply. if you have any Idea to create style like that Block Line on style that works on web then please tell me thanks in advance.

**Comment by junaid042** [comment]
thanks Everyone for helping me
