### ISSUE TITLE
displayDialogAsync not opening in Outlook Android context

### ISSUE THREAD

**Issue by BryanCB1** [OfficeDev/office-js#3978]
Hello

We have a problem using the `displayDialogAsync` function in our plugin. What we are looking for on mobile devices is that our authentication window opens in the same context of the application and is not a browser window. This behavior works correctly on iOS devices but on Android devices this does not work correctly, in the same way on the web. and the desktop application works fine.

We are using the next library version script:
` <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
`

And we already checked and if the context is being obtained, the ui object does have the necessary elements, everything seems in order

Our implementation is executed listening to the click event in an html file, then the function that is in a js file is executed to trigger the dialog and perform the subsequent functions

Part of the html code:

`
                button.addEventListener("click", (event) => {
                    window.Handler.eventClickLogin()
                });
`

Part of the JS code:

`eventClickLogin: function(){
        Office.context.ui.displayDialogAsync(window.location.origin + window.Handler.oauthUrl + '?url=' + encodeURIComponent(dataUser.redirect), {
                height: 75,
                width: 30,
                promptBeforeOpen: false
            })
    }`

Finally we carry out a curious test, doing the test with a Wi-Fi network it works incorrectly, but when we do the test changing to mobile data everything works as we want.

https://github.com/OfficeDev/microsoft-teams-library-js/assets/153008575/5dd07f3b-3dac-4593-8bc0-683c907d4587

In the video, a couple of attempts are made connected to the Wi-Fi network and the behavior of displayDialogAsync is to open a browser tab, after that the Wi-Fi is turned off and one more execution is carried out, this time the displayDialogAsync function opens the url inside from a tab of the same plugin, that is the compartment we are looking for

We ask for your help to detect and solve this behavior

Greetings

**Comment by AlexJerabek** [comment]
Hi @BryanCB1,

This seems like a product issue, so I'm going to transfer it to the [office-js repo](https://github.com/OfficeDev/office-js). There, a member of the feature crew can help investigate.

**Comment by AlexJerabek** [comment]
@exextoc, could you please take a look?

**Comment by BryanCB1** [comment]
Hi

There is some update?

**Comment by ajays-msft** [comment]
@BryanCB1 - The behavior occurs when the add-in and URL you are opening in displaydialog are not in the same domain. Can you check if your router settings are configured to redirect the URL? I am not sure how to check that on your specific router, but that is one possibility why you are seeing a different behavior when connected to wifi vs cellular.

**Comment by BryanCB1** [comment]
The thing is that this has already been detected on several devices, from several users, not just a few, could there be another cause?

**Comment by ajays-msft** [comment]
@BryanCB1 - Can you please check network logs to see if the URLs are pointing to the same domain?

**Comment by BryanCB1** [comment]
My principal route is ms.clarodrive.com, the url that I use to authenticate and the one that I want to be displayed within the Android application points to www.clarodrive.com

Why does this work correctly on iOS devices but not on Android?

**Comment by rajjha-msft** [comment]
Hey @BryanCB1 

Can you please share logs for a working iOS device and non-working Android device? 
Also, if possible, please share the manifest, we will try to repro the issue at our end. 

Please send it over to: OutlookExtensibility@M365x53858506.onmicrosoft.com

**Comment by Gnecc** [comment]
Hi @rajjha-msft 

We are working to obtain the logs with our mobile teams. As soon as I have them ready, I will return to you with them.

**Comment by BryanCB1** [comment]
Hi @rajjha-msft 

We are working to obtain the logs with our mobile teams. As soon as I have them ready, I will return to you with them.

**Comment by BryanCB1** [comment]
Hi @rajjha-msft 

Is there a way to activate logs through your library?

https://appsforoffice.microsoft.com/lib/1/hosted/office.js

We are using this version, if so, which one could we update to?

**Comment by ajays-msft** [comment]
@BryanCB1 - To collect powerlift logs from Outlook mobile, you need to follow these steps:

- Open Outlook on your mobile device and go to Settings > Help & Feedback > Collect Diagnostics.
- Tap Start Logging and reproduce the issue you want to report.
- Tap Stop Logging and Upload Logs. You will see an incident ID that you can share with your support person.
- Please send an email with the incident ID and a description of the issue to your support person.


For more information, see [Outlook for iOS and Android in Exchange Online: FAQ](https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faqhttps://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-faq) 

Powerlift log collection is present in Outlook Mobile and Outlook Mac.

**Comment by BryanCB1** [comment]
Hi @ajays-msft 

Our incident id is G34Q8GR9

**Comment by BryanCB1** [comment]
Hi @ajays-msft 

there is some update?, is correct our report id?

**Comment by neprasad-microsoft** [comment]
Hi @BryanCB1, unfortunately the Powerlift logs do not capture the network logs and we were unable to verify the URL. 
Could you help with a few more queries -
1. Is this happening for the same tenant or different tenants? 
2. Can you give us the URL which you are opening in displayDialogAsync and the URLs under the AppDomain section in your manifest. 
3. If possible, please send us the manifest of your add-in to OutlookExtensibility@M365x53858506.onmicrosoft.com. This will help us in faster debugging.

**Comment by BryanCB1** [comment]
Thank you for your attention, we have sent the manifest to the indicated email

**Comment by neprasad-microsoft** [comment]
Hi @BryanCB1 
I see that the URL which opens on opening the dialog is http://test-portal.clarodrive.com/authorize? . Could you add this url to your AppDomain in manifest and then test if this issue still occurs?

**Comment by BryanCB1** [comment]
Hi @neprasad-microsoft 

We have tried what was requested by integrating a domain tag as follows
`<AppDomain> https://test-portal.clarodrive.com/authorize</AppDomain>`
and
`<AppDomain> http://test-portal.clarodrive.com/authorize</AppDomain>`

Unfortunately this didn't work either, this is happening in the same tennant and also in different tennants and the url we use is like the one we included in the last manifest we share with you.
`<AppDomain> https://test-portal.clarodrive.com</AppDomain>` 

This works without any problem on iOS devices with the same manifest.

**Comment by neprasad-microsoft** [comment]
Hi @BryanCB1 
Thanks for your patience. We think this is happening because of the extra space in the manifest. 
Please remove the space between "<AppDomain>" and "https" and let us know if this works.

**Comment by BryanCB1** [comment]
Hello team, this completely solves the issue, thank you very much
