### ISSUE TITLE
Error 13000, API for identity not supported

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#398]
I used the NodeJS SSO sample and continued to develop an application from there on out. In Word Online, the application works perfectly fine, but in the Word Client, no matter which version I use, I get error 13000 "API for identity is not supported for this add-in" when using the function getAccessTokenAsync even when I'm using the NodeJS SSO sample without any changes. 

I've tried 2016/2017/2018 versions of Word (Semi-annual, semi-annual targeted, monthly, Insider). Right now I am on version 1801 9001.2068 Insider and I still get the error, while the [documentation](https://docs.microsoft.com/nl-nl/office/dev/add-ins/reference/requirement-sets/identity-api-requirement-sets?view=office-js) says using an Insider version should suffice.

What seems to be the issue? I'm able to provide samples of my manifest/code if needed, but I'm not sure where the problem lies in the first place.

In the readme.md, it says I need at least version 8605.1000. Is this the Monthly-channel (targeted), Monthly, Semi-annual Channel (Targeted), Semi-annual Channel or Insider version? In the [list for Word versions](https://docs.microsoft.com/nl-nl/officeupdates/update-history-office365-proplus-by-date) and this [list for all Insider versions](https://support.office.com/en-ie/article/update-history-for-office-insider-for-windows-desktop-64bbb317-972a-4933-8b82-cc866f0b067c#InsiderLevel=Insider), I can't seem to find version 8605.1000 while I do need to know which version it is to be able to downgrade.

**Comment by Rick-Kirkham** [comment]
@niteshgolchha85 This customer is on the latest Insider build, but is getting 13000 "API for identity is not supported for this add-in".

**Comment by niteshgolchha85** [comment]
@lokkwanfoo The SSO API is in preview right now. All preview flights are disabled by default. I suspect that Office might not be able to get the latest flight state when the version changes so can you restart your office application after upgrading/downgrading and then try the SSO API?

**Comment by ghost** [comment]
@niteshgolchha85 @Rick-Kirkham I've just restarted my Office client, and I'm seeing a different error. I haven't changed anything in code, I'm purely calling getAccessTokenAsync.

![image](https://user-images.githubusercontent.com/11733366/53048234-95877f00-3494-11e9-93a3-b54c0982cb04.png)

Message meaning "There is an unexpected error in the server", name meaning "There is an error in the verificationprovider". 

Also are you telling me to downgrade, upgrade again and then try executing the function again?

**Comment by niteshgolchha85** [comment]
What I meant was that every time you change the version of Office, you might want to restart Office to update the cache.
The error code now is 13007, which leads me to believe that there is some issue with you App registration with AAD and/or your manifest:
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins

**Comment by ghost** [comment]
@niteshgolchha85 I'm using the exact same manifest for the Word client and Word Online. It works on Word Online as shown here:

![image](https://user-images.githubusercontent.com/11733366/53049606-c9b06f00-3497-11e9-881f-8e33cdf92cdc.png)

In the Word client, it doesn't. I've restarted multiple times.

I'm starting to think the issues lies here.

![image](https://user-images.githubusercontent.com/11733366/53050532-ce762280-3499-11e9-8ba0-658ba997535b.png)


I've only added the three ids provided in the tutorial. How do I find out what the app id is of the Word client?

**Comment by niteshgolchha85** [comment]
Word by itself does not have a client ID. All the IDs of Office applications are represented right now by a single ID you see above (Microsoft Office). There is plan to change this into separate IDs but that's for a separate conversation.

**Comment by ghost** [comment]
Could you tell me if it works in your Word client? And which version you are using?

**Comment by niteshgolchha85** [comment]
@lokkwanfoo Have you tried to repro the issue? @Alan1Mulhall This error seems to be coming from the OMEX server. Would you be able to investigate the root cause?

**Comment by ghost** [comment]
@niteshgolchha85 

I've just attempted to call getAccessTokenAsync and it seems to be working now :). I'm not sure what fixed it, but hopefully it can stay this way!

![image](https://user-images.githubusercontent.com/11733366/53224088-c1149000-3673-11e9-9d7d-6802424e3098.png)

Thank you!

**Comment by niteshgolchha85** [comment]
I'll be going ahead and closing this issue for now. Please re-open if the issue arises again. Thanks!
