### ISSUE TITLE
The name property of a namedItem object returns localized name

### ISSUE THREAD

**Issue by jkpieterse** [OfficeDev/office-js#3984]
# Provide required information needed to triage your issue
When Excel is set to a different language, the name property of some Excel-managed range names are localized

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Any
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: all version supporting office-js
* Operating System: Win 10
* Browser (if using Office on the web): Edge
 
## Expected behavior

Return English language name for range names like Print_Area, _FilterDatabase, Print_Titles, "Criteria", "Extract"

## Current behavior
The name property of Range names like Print_Area, _FilterDatabase, Print_Titles, "Criteria", "Extract" are returned in local language

in VBA, we have a NameLocal property which returns the localized name, the Name property returns the English name.

## Steps to reproduce

1. Open blank Excel file, set a print area
2. run this code snippet in Script lab: https://gist.github.com/jkpieterse/7c145cc7464b181c98007987b19f4c4d

## Link to live example(s)

1. Open blank Excel file, set a print area
2. run this code snippet in Script lab: https://gist.github.com/jkpieterse/7c145cc7464b181c98007987b19f4c4d

# Provide additional details

1. ______
2. ______
3. ______

## Context

I am trying to hide "system" names from the list of Range Names, but if my user is using e.g. Dutch Excel, my list shows system names when it shouldn't.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by donlvMSFT** [comment]
Hi @jkpieterse , 

Currently, we don't have such ability in Office JS, I created an internal task 8653845 to track this.
I'd also encourage you to add your request on our [Microsoft 365 Developer Platform Ideas Forum]( https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. 

Thanks, Microsoft 365 Developer Platform team
