### ISSUE TITLE
Outlook  Event Based WebAddin not loading in old/classic outlook 

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#3986]
we are developing office web Addin for outlook using event based (Smart  Alert)  .The Addin is generated using office yo generator Task Pane add-in using the React framework

We used  the notification (Office.MailboxEnums.ItemNotificationMessageType.InsightMessage) for our web add in and configured the same for OnMessageSend ,OnMessageRecipientsChanged ,OnNewMessageCompose events which is showing the task pane after performing certain validations  . The same works on browser and new thick client but doesn't work for old thick client and with below manifest the Addin is not loading in old thick client  . 

[manifest.docx](https://github.com/OfficeDev/office-js/files/13888930/manifest.docx)

<img width="568" alt="image" src="https://github.com/OfficeDev/office-js/assets/142812553/31865c53-e186-4267-abd8-3ca8bd9b05c2">

**_Even the default Addin created using office yo generator Task Pane add-in using the React framework is having this issue .
The issue can be reproduced by creating office yo generator Task Pane add-in using the React framework and try loading the Manifest in Old Outlook thick client .The Newly created Addin will not show in Outlook Thick Client having office build 2311 ._**

**Comment by geetamshukla** [comment]
@exextoc  @ajays-msft 

Any update on this issue ?? Its been 2 weeks and I have not heard back anything

**Comment by geetamshukla** [comment]
> Thank you for the input. Event based Add-ins/ Launch Events are not supported on old Outlook.

Can u pls share the document reference where this is mentioned exactly

**Comment by ajays-msft** [comment]
Please refer to this documentation for Min Outlook versions event based addins. Also, as a general guidance, Old Mac Outlook only supports upto [api-set 1.8](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/requirement-set-1.8/outlook-requirement-set-1.8?view=common-js-preview)

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch

**Comment by geetamshukla** [comment]
> Please refer to this documentation for Min Outlook versions event based addins. Also, as a general guidance, Old Mac Outlook only supports upto [api-set 1.8](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/requirement-set-1.8/outlook-requirement-set-1.8?view=common-js-preview)
> 
> https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch

which section in the given Doc explains that the event based Addins are not supported for Old Outlook version

**Comment by JuaneloJuanelo** [comment]
@ajays-msft  i think this is not asking about Mac is a windows build as per the screenshot above.

**Comment by zhngx1** [comment]
@geetamshukla Can you enable runtime logging to see what error is shown for your add-in? https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging

**Comment by timwan10** [comment]
Most likely a problem like this is because the old thick win32 client uses a JS engine to process the event, whereas the new thick and OWA uses a web browser. @zhngx1  comments usually helps out in debugging what may be wrong with your bundle.js. 

See also this documentation: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/troubleshoot-event-based-and-spam-reporting-add-ins#check-manifest-and-javascript-requirements

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/troubleshoot-event-based-and-spam-reporting-add-ins#check-manifest-and-javascript-requirements

People commonly hit the ECMA limitation, or script include limitation.

**Comment by geetamshukla** [comment]
> Most likely a problem like this is because the old thick win32 client uses a JS engine to process the event, whereas the new thick and OWA uses a web browser. @zhngx1 comments usually helps out in debugging what may be wrong with your bundle.js.
> 
> See also this documentation: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/troubleshoot-event-based-and-spam-reporting-add-ins#check-manifest-and-javascript-requirements
> 
> https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/troubleshoot-event-based-and-spam-reporting-add-ins#check-manifest-and-javascript-requirements
> 
> People commonly hit the ECMA limitation, or script include limitation.

In  OLD Outlook with below version ..I am not able to see addin  in old outlook hence even the  logging  also is not helping  

![image](https://github.com/OfficeDev/office-js/assets/142812553/28406068-af8d-42cf-92f1-817170f8f4f8)

**Comment by zhngx1** [comment]
Do you mean the add-in you created with events that doesn't show up in old Outlook client, or there is no add-in showing up in your old Outlook client?

**Comment by geetamshukla** [comment]
> Even the default Addin created using office yo generator Task Pane add-in using the React framework is having this issue .
> The issue can be reproduced by creating office yo generator Task Pane add-in using the React framework and try loading the Manifest in Old Outlook thick client .The Newly created Addin will not show in Outlook Thick Client having office build 2311 .
@zhngx1 
pls see above  issue desc where I have mentioned .. 

"Even the default Addin created using office yo generator Task Pane add-in using the React framework is having this issue .
The issue can be reproduced by creating office yo generator Task Pane add-in using the React framework and try loading the Manifest in Old Outlook thick client .The Newly created Addin will not show in Outlook Thick Client having office build 2311 ."

**Comment by zhngx1** [comment]
I will try to repro and get back to you.

**Comment by zhngx1** [comment]
Thanks for reporting this issue regarding `yo office addin React template not working`. It has been put on our backlog. We unfortunately have no timelines to share at this point 

 

Internal tracking id: Office: 8591450

**Comment by Rick-Kirkham** [comment]
@geetamshukla Add-ins created using the React option in Yo Office have a `<VersionOverrides>` (v 1_1) element nested inside a a  `<VersionOverrides>` (v 1_0) element. Just inside the top of the outer `<VersionOverrides>` there is a `<Hosts>` element. Deleting this `<Hosts>` element should enable the add-in to sideload in Old Outlook. 

See if this works for you and let us know.

**Comment by geetamshukla** [comment]
> @geetamshukla Add-ins created using the React option in Yo Office have a `<VersionOverrides>` (v 1_1) element nested inside a a `<VersionOverrides>` (v 1_0) element. Just inside the top of the outer `<VersionOverrides>` there is a `<Hosts>` element. Deleting this `<Hosts>` element should enable the add-in to sideload in Old Outlook.
> 
> See if this works for you and let us know.

Hi @Rick-Kirkham  ,
I have tried Deleting this `<Hosts>` element  but still the same issue .The Addin OnMessageSend ,OnMessageRecipientsChanged ,OnNewMessageCompose events are not working in thick client

**Comment by zhngx1** [comment]
@geetamshukla Can you confirm that if the yo office react template is working? I guess we are tracking 2 separate issues here.
1. Yo Office template
2. The Addin OnMessageSend ,OnMessageRecipientsChanged ,OnNewMessageCompose events

**Comment by geetamshukla** [comment]
> @geetamshukla Can you confirm that if the yo office react template is working? I guess we are tracking 2 separate issues here.
> 
> 1. Yo Office template
> 2. The Addin OnMessageSend ,OnMessageRecipientsChanged ,OnNewMessageCompose events

@zhngx1  **the office template is working in old thick client . I am able to launch the task pane, perform and action  from Ribbon 
but Addins OnMessageSend ,OnMessageRecipientsChanged ,OnNewMessageCompose events are not working in thick client** . 

I am able to see bundle.js available in below path which has code for these events but still in Outlook Old Thick client  these events are not working . Attaching the Manifest and launch event code 
[Manifest_and_Bundle.zip](https://github.com/OfficeDev/office-js/files/14533516/Manifest_and_Bundle.zip)

C:\Users\geetam.shukla\AppData\Local\Microsoft\Office\16.0\Wef\{F6EB27E0-79DD-4B7F-AE7F-5B947D94077D}\jZhKqt6OnvZA0B3UR2If9A==\Javascript\3c787aa5-3a06-479e-bb54-8acd1f6fef38_1.0.0.0_en-US  

I also enabled runtime logs using npx office-addin-dev-settings runtime-log --enable but donot see any error as such .Attaching the log for your reference. 


[OfficeAddins_1.log.txt](https://github.com/OfficeDev/office-js/files/14533513/OfficeAddins_1.log.txt)

**Comment by geetamshukla** [comment]
> > @geetamshukla Can you confirm that if the yo office react template is working? I guess we are tracking 2 separate issues here.
> > 
> > 1. Yo Office template
> > 2. The Addin OnMessageSend ,OnMessageRecipientsChanged ,OnNewMessageCompose events
> 
> @zhngx1 **the office template is working in old thick client . I am able to launch the task pane, perform and action from Ribbon but Addins OnMessageSend ,OnMessageRecipientsChanged ,OnNewMessageCompose events are not working in thick client** .
> 
> I am able to see bundle.js available in below path which has code for these events but still in Outlook Old Thick client these events are not working . Attaching the Manifest and launch event code [Manifest_and_Bundle.zip](https://github.com/OfficeDev/office-js/files/14533516/Manifest_and_Bundle.zip)
> 
> C:\Users\geetam.shukla\AppData\Local\Microsoft\Office\16.0\Wef{F6EB27E0-79DD-4B7F-AE7F-5B947D94077D}\jZhKqt6OnvZA0B3UR2If9A==\Javascript\3c787aa5-3a06-479e-bb54-8acd1f6fef38_1.0.0.0_en-US
> 
> I also enabled runtime logs using npx office-addin-dev-settings runtime-log --enable but donot see any error as such .Attaching the log for your reference.
> 
> [OfficeAddins_1.log.txt](https://github.com/OfficeDev/office-js/files/14533513/OfficeAddins_1.log.txt)

@zhngx1 is there any update on this issue ..did u checked the logs and file which I shared ?

**Comment by zhngx1** [comment]
Sorry I wasn't able to download your attachments. Can you reupload? They are giving me 404 errors.

**Comment by geetamshukla** [comment]
> Sorry I wasn't able to download your attachments. Can you reupload? They are giving me 404 errors.
@zhngx1 Reuploading the files 
[bundle.txt](https://github.com/OfficeDev/office-js/files/14583107/bundle.txt)
[launchevent.txt](https://github.com/OfficeDev/office-js/files/14583108/launchevent.txt)
[manifest.txt](https://github.com/OfficeDev/office-js/files/14583112/manifest.txt)
[OfficeAddins_1.txt](https://github.com/OfficeDev/office-js/files/14583118/OfficeAddins_1.txt)

**Comment by timwan10** [comment]
The bundle contains code that is non Ecma 2016 compliant. (Async is not supported)

```
const onMessageSend = async (event) => {
    debugger;
    event.completed({
        allowEvent: false,
        errorMessage: "Please review and verify the recipients.",
        commandId: "msgComposeOpenPaneButton",
        cancelLabel: "Verify",
      });

}
```

**Comment by geetamshukla** [comment]
> The bundle contains code that is non Ecma 2016 compliant. (Async is not supported)
> 
> ```
> const onMessageSend = async (event) => {
>     debugger;
>     event.completed({
>         allowEvent: false,
>         errorMessage: "Please review and verify the recipients.",
>         commandId: "msgComposeOpenPaneButton",
>         cancelLabel: "Verify",
>       });
> 
> }
> ```

@timwan10  
I have tried to run the add-in without async/await functionality and still facing same issue . Attached is the latest bundle file from wef folder . 

For me I can see the Addin for old thick client is loaded . I am able to launch the task pane, perform and action from Ribbon
**but Addins OnMessageSend ,OnMessageRecipientsChanged ,OnNewMessageCompose events are not working in thick client .**  
[bundle.txt](https://github.com/OfficeDev/office-js/files/14600094/bundle.txt)

I am using below outlook version 
![image](https://github.com/OfficeDev/office-js/assets/142812553/115b9e28-6693-4efa-9725-f5847a6a2f6e)

**Comment by zhngx1** [comment]
@geetamshukla I have tested with your onNewMessageCompose event code. You will need to change the asyncContext from eventObj to a different object. 

```
Office.context.mailbox.item.body.setSignatureAsync
 (  
     signature,  
     {  
         "coercionType": "html",  
         "asyncContext": {}
      },
      function (asyncResult) {
          asyncResult.asyncContext.completed({ "key00": "val00" });
      }
 );
```


I will have to debug more to figure out the issue with eventObj, but that should get you unblocked.
