### ISSUE TITLE
How to satisfy policy number 1120.3.2.7 Edge Anaheim when my addin requires the use of an office.js method that is not fully compatible with Excel online?

### ISSUE THREAD

**Issue by HugoAlbertoNieto** [OfficeDev/office-js#3987]
We have developed an Excel addin using office.js and we submitted it for approval to the AppSource. After a few days we received feedback which included the following issue:

**1120.3.2.7 Edge Anaheim The add-in did not pass compatibility tests for Edge**

They also included a comment stating that they received the following error when testing our addin in Excel online:

![image](https://github.com/OfficeDev/office-js/assets/53156762/eb2fad8a-b90e-4d0c-a859-eac2bca23710)

We want to solve this issue so that our add-in gets approved, but we are facing a challenge because the add-in uses an office.js method that is not fully compatible with Excel online.

Let me explain with more detail. The buttons of the task pane on the image insert a template on the active workbook. Each button sends a request to our server and then inserts the corresponding template using the `insertWorksheetsFromBase64` method. 

This works perfectly fine in Excel desktop and Mac, but it doesn't work in Excel online because the method doesn't support source worksheets with Chart or Comment elements and our templates contain those elements. This limitation of the `insertWorksheetsFromBase64` method is clearly stated in the documentation below:

https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-workbooks#insert-a-copy-of-an-existing-workbook-into-the-current-one

![image](https://github.com/OfficeDev/office-js/assets/53156762/71a28a6e-0484-4ccd-8bf2-1a6a7a18f72b)

Actually, we added the above error handling to our addin (it shows the message only when it runs in Excel online) because we were aware of this limitation of the method. So, our question is, **how can we satisfy the above requirement? Is there another method, we can use to insert a worksheet from server and that is fully compatible with Excel online?**

Any help would be really appreciated.

In case it is needed, here is the information of the request we sent to the AppSource:

Request ID: 101053
Request Title: Office add-in - Archer - Archer
Publisher Name: Archer
Offer Type: Office add-in
Product/Offer Name: Archer
Product/Offer ID: 1a0a6441-c57a-4ba7-8860-bd039da8633f
Policy Number Requiring Assistance: 1120.3.2.7 Edge Anaheim

Thanks!

**Comment by zhenhuangMSFT** [comment]
@AkhileshShah-MS Hi Akhilesh, could you help take a look at the developer's question?

**Comment by HugoAlbertoNieto** [comment]
Hi @AkhileshShah-MS @zhenhuangMSFT Are there any news on this issue?
We want to satisfy this requirement but the `insertWorksheetsFromBase64` method seems to be limited in our use case.

**Comment by Wenjun-Gong** [comment]
Hi @HugoAlbertoNieto , is the error message "Templates cannot be inserted in Excel online..." by design in your add-in UX?

If yes, did you try to explain your error handling experience to the validation team? They should be able to give it a pass if you have clear description for the behavior differences between Excel Online and desktop. Let us know if that does not work.

**Comment by HugoAlbertoNieto** [comment]
Thanks @Wenjun-Gong. Yes, the error message is included by design. As I said, the templates contain comments and charts, so we are aware that the `insertWorksheetsFromBase64` method will fail in Excel online. That's why we included this error message to let the user know that this specific feature will not work in Excel online (as I said, it works fine in Excel desktop and Mac).

In the next submission we will make sure to explain the issue to the validation team and I will make sure to update this issue accordingly. Thanks!

**Comment by Wenjun-Gong** [comment]
Thanks for the clarification @HugoAlbertoNieto. Please do include the explaination in your next submission. If the validation team reject for the same reason again, let us know then we will help out.

**Comment by HugoAlbertoNieto** [comment]
@Wenjun-Gong The validation team has approved our addin! We can close the issue now. Thank you very much for your help!
