### ISSUE TITLE
How can we get details of mailbox when multiple items are selected (shared mailboxes, delegated access)?

### ISSUE THREAD

**Issue by milczuk** [OfficeDev/office-js#3989]
Is there any way to know if we are in the context of shared mailbox when having multiple items selected?
On desktop outlook Office.context.mailbox.item is available
we can use Office.context.mailbox.item.getSharedPropertiesAsync
having shared properties I can build urls to get the details from ews using targetRestUrl from the response, and very important targetMailbox value
on OWA and Desktop New Outlook Office.context.mailbox.item it's undefined.
We can't tell if we are in context of shared mailbox or just standard mailbox, or if it's delegated scenario when we work in context of someone else's mailbox.
Would it be possible to keep Office.context.mailbox.item have details of at one of the selected items to get the maibox details in those scenarios?
Are there any plans for an API that would give us that information in multi select scenario?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 34daad03-0e48-d846-0c52-9ce4cedd4462
* Version Independent ID: 34daad03-0e48-d846-0c52-9ce4cedd4462
* Content: [Activate your Outlook add-in on multiple messages - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select)
* Content Source: [docs/outlook/item-multi-select.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/item-multi-select.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by milczuk** [comment]
More on that I've found a comment that worries me a bit:
https://github.com/OfficeDev/office-js/issues/3680#issuecomment-1732860872
When multiple emails are selected, it is expected that Office.context.mailbox.item will be null [...]
if it's null then there is no way for us to know the shared properties, no target mailbox address to build queries...

**Comment by thranejepsen94** [comment]
+1

**Comment by AlexJerabek** [comment]
Thanks for the questions. @samantharamon, could you please follow up?

**Comment by samantharamon** [comment]
@exextoc Could you please investigate this?

**Comment by exextoc** [comment]
When multiple emails are selected, it is expected that Office.context.mailbox.item will be null as there are multiple items selected. Getting getSharedPropertiesAsync when multiple items are selected is not supported at present. 
We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by mrebuffet** [comment]
We are also impacted by this issue. 
I have up-voted this [suggestion](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/outlook-addin-shared-mailboxes-support-improvement/idi-p/3947353)

I understand that this feature is currently unsupported but not having anything indicating that we are in the context of a shared mailbox makes it impossible to provide users with a message explaining that this feature is currently unsupported. 
Do you have any suggestion on how we could determine that we are in this scenario and inform our users? 

All the returned properties seem to be common to the entire mailbox object so perhaps exposing them under the mailbox like so `Office.context.mailbox.getSharedPropertiesAsync()` would help.

Many thanks

**Comment by CameronDwyer** [comment]
+1

**Comment by dangarkusha** [comment]
To confirm and reiterate, the issue with **multi-select** in a **shared mailbox** persists and is reproducible in all OWA clients. When more than one email is selected, Office.context.mailbox.item becomes null preventing access to the only means of retrieval of a shared mailbox identity via `Office.context.mailbox.item.getSharedPropertiesAsync()`.

![image](https://github.com/OfficeDev/office-js/assets/133253339/bcefcf4d-d375-418f-8cf9-92351b5b128a)

**We need a reliable way to retrieve the properties of the current mailbox.** 

+1 to the suggestion above to expose the method on the `mailbox `object instead of the `mailbox.item` object like this: 
- do this: `Office.context.mailbox.getSharedPropertiesAsync()`
- instead of this: `Office.context.mailbox.item.getSharedPropertiesAsync()`

PS:
This is not a "feature" - it's a bug!

**Comment by manuelsidler** [comment]
Any updates on this issue? It's a real show stopper for our add-in to support shared mailboxes.

**Comment by dangarkusha** [comment]
I've followed the link above and submitted this as a feature request on the Tech Community portal. You can support the request by upvoting it to help it gain visibility and traction.

Here is the link: [Outlook Add-in: Expose shared mailbox properties on the mailbox object in a multi-select scenario](https://techcommunity.microsoft.com/idea/microsoft365developerplatform/outlook-add-in-expose-shared-mailbox-properties-on-the-mailbox-object-in-a-multi/4303432)
