### ISSUE TITLE
Foreign characters stopped working when inserting signatures with OnNewMessageCompose event

### ISSUE THREAD

**Issue by SimonDania** [OfficeDev/office-js#3992]
# Provide required information needed to triage your issue
Foreign characters stopped working in the Outlook 365 client when inserting signatures with OnNewMessageCompose event.
It appears the issue is only present in the current channel.
If I roll back to the monthly channel, it still works as expected.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook 365 (Client)
* Office version number: 2312
* Operating System: Windows 10/11
* Browser (if using Office on the web): N/A
 
## Expected behavior

The foreign characters "Æ", "Ø" and "Å" are expected to be shown correctly.

## Current behavior

I open a new mail and the `OnNewMessageCompose` event is fired as expected. Afterwards my signature is inserted, but I get weird characters instead of the expected letters. If I fire the same event manually, the foreign characters are shown correctly.

## Steps to reproduce

1. Open Outlook Client
2. Start a new mail
3. When the signature is inserted through our add-in, the characters are broken.

## Context

The issue has been present ever since the current channel was updated in january.

## Useful logs

- [ ] Console errors
- [X] Screenshots
- [ ] Test file (if only happens on a particular file)

**How it looks:**
<img width="456" alt="image" src="https://github.com/OfficeDev/office-js/assets/85676333/85428a6d-2abb-45e4-a944-5aa5ab634bdc">

**How it is supposed to look:**
<img width="462" alt="image" src="https://github.com/OfficeDev/office-js/assets/85676333/04c7f648-e927-407a-a0f4-6cbced6c4083">

**Comment by kinkoazc** [comment]
This is a duplicate of https://github.com/OfficeDev/office-js/issues/3892.

**Comment by SimonDania** [comment]
> This is a duplicate of #3892.

**Comment by SimonDania** [comment]
> This is a duplicate of #3892.
