### ISSUE TITLE
Add-in does not launch in "New Outlook"

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#3996]
# Provide required information needed to triage your issue

## Your Environment

* Platform : PC desktop
* Host : Outlook
* Microsoft® Outlook® version : 1.2024.103.100
* Operating System: Windows OS
 
## Summary
Only the top level profile will launch the add-in when Outlook is changed to "New Outlook". 
Normally, the add-in should be activated in all profiles.

## Current behavior
If you have multiple profiles, the add-in will be activated only for the account that appears at the top level.
It will not be activated for all other profiles. 
The expected behavior for all profiles is as follows
1.Launch Outlook.
2.Install the Office add-in to Outlook.
3.Specify the recipient and click the "Send" button.
4.The Office add-in will start and a sample display will appear.
5.Click "close(true)" in the sample display.
6.An email will be sent.

## Steps to reproduce
1.Upload "manifest.xml" to Outlook on the web and install the add-in (the XML file is stored in sample.zip)
2.Open a command prompt and navigate to the corresponding directory.
3.Run "npm install".
4.Run "npm run dev-server".
5.Launch Outlook.
6.Change to "New Outlook.
7.Select a profile other than the one shown at the top.
8.Installs add-ins for selected accounts.
9.Compose and send an email.
10.The Office add-in will start and a sample display will appear.
11.Click "close(true)" in the sample display.
12.An email will be sent.

## Link to live example(s)

I am storing the sample add-in.
* sample add-in program
  https://github.com/mailchecktool-admin/Office-addin-sample/tree/main/src

**Comment by exextoc** [comment]
@mailchecktool-admin On new outlook Addin are available only for primary accounts. For addins on secondary accounts work is in progress. We unfortunately have no timelines to share at this point.

**Comment by teejay001** [comment]
@exextoc  This is still an issue and the ticket should not be closed.

**Comment by mailchecktool-admin** [comment]
It appears that this issue has not been resolved yet.
When do you plan to support add-ins for secondary accounts?

**Comment by rajjha-msft** [comment]
Hey @mailchecktool-admin 

Thank you for your inquiry about add-ins support on Multi account. We understand the importance of this feature to our customers and would like to assure you that it is currently under development. 
While we cannot provide an exact timeline for its release, rest assured that we are working diligently to bring this functionality to you as soon as possible. We appreciate your patience and understanding as we continue to improve our service to meet your needs.

**Comment by cody-lettau** [comment]
@exextoc what is the status of this? This is a major issue for users who have multiple accounts setup in their desktop client and need to use add-ins across the different accounts.
