### ISSUE TITLE
Is Google SSO available in Outlook add-in?

### ISSUE THREAD

**Issue by zjmchoi** [OfficeDev/office-js#3997]
I am developing an Outlook Add-in.
Following the guide described by MS, I added MS SSO feature.
And, I also want to add Google SSO feature.
I can't find any guide regarding this.
Please let me know how to solve it.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Mac, Outlook on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows, Mac
* Browser (if using Office on the web): Chrome
 
## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ajays-msft** [comment]
No. Outlook add-ins only support SSO with Microsoft 365 Tenancy.
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/authenticate-a-user-with-an-sso-token

**Comment by zjmchoi** [comment]
Thank you for answer.

According to the link below, it looks like this feature is possible through a third-party library or server.
Is it my misunderstanding?
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/auth-external-add-ins

**Comment by ajays-msft** [comment]
@zjmchoi - The link you pointed to is for for authorizing your addin with another Identity provider. SSO means, you login in Outlook, and same Outlook authentication can be inherited by the addin. Currently SSO flow is only supported for M365 tenancy.

**Comment by zjmchoi** [comment]
Yes. I would like to authenticate my outlook add-in through another identity provider (such as Google). (this is Google SSO, isn't it?)

After logging in to MS Outlook with MS account, is it really impossible to authenticate with Google for my outlook add-ins within it? (Actually, I think very few people do this.)

**Comment by exextoc** [comment]
It is possible to authenticate Outlook Add-in with any Identity provider. You will have to see the documentation for that identity provider to solve this problem.
