### ISSUE TITLE
Method Word.body.search() doesn't find matching texts in footnotes/endnotes

### ISSUE THREAD

**Issue by costashu** [OfficeDev/office-js#4]
Word documents have such a significant feature as footnotes/endnotes. In Word UI searching finds matching text in them, but method doesn't. To reproduce, use the attached document [footendnote.docx](https://github.com/OfficeDev/script-lab/files/1097705/footendnote.docx) and your sample Search (not using setup):
![image](https://user-images.githubusercontent.com/13196290/27988436-5fbe9fa2-642a-11e7-9882-384911cef93c.png)
PS. Also, the text of footnotes/endnotes is not returned by any other methods.

**Comment by JuaneloJuanelo** [comment]
foot notes are not supported currently on the API, please add user voice request here. https://officespdev.uservoice.com/

**Comment by JuaneloJuanelo** [comment]
this is a known gap in the API, actually in the backlog, so we will not keep this issue open indefinitely.
