### ISSUE TITLE
Cannot deploy SSO-enabled manifest in Office 365 via Centralized Deployment

### ISSUE THREAD

**Issue by sergiubucur** [OfficeDev/office-js#400]
At least since Feb 4th 2019 I cannot deploy an SSO-enabled Word Add-in manifest in the Office 365 admin portal using Centralized Deployment.

## Expected Behavior
The "Next" button on the permissions screen should not be disabled, allowing me to still deploy an SSO-enabled manifest.

## Current Behavior
The "Next" button on the permissions screen is disabled.

## Steps to Reproduce, or Live Example
1. Go to Office 365 admin portal > Settings > Services & Add-ins > Deploy Add-in
2. Upload an SSO-enabled manifest
3. Get the following screen where the "Next" button is disabled (I am using a Global Administrator account):
![screenshot](https://user-images.githubusercontent.com/7591380/53074812-66085f00-34f4-11e9-9c06-850b74e3951c.png)

## Context
I cannot deploy our Word Add-ins anymore since they're all dependent on the SSO feature.

**Comment by niteshgolchha85** [comment]
This is a known bug and @Alan1Mulhall is fixing this issue. @Alan1Mulhall can you throw some light on ETA for fix?

**Comment by sergiubucur** [comment]
This is now working as expected again. Thank you!

**Comment by niteshgolchha85** [comment]
I am closing this issue as per comments given above. @sergiubucur Please note that we do NOT recommend using SSO in production and such changes might occur in future as well.
