### ISSUE TITLE
Excel Addin deployment > No addins currently available

### ISSUE THREAD

**Issue by bcolas** [OfficeDev/office-js#4001]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® pour Microsoft 365 MSO (Version 2208 Build 16.0.15601.20526) 32 bits
* Operating System: Windows 10 22H2
* Browser (if using Office on the web): Edge Version 117.0.2045.60 (Version officielle) (64 bits)
 
## Expected behavior
After deployment in Office365 Admin, Addin appears in Admin Managed tab

## Current behavior
No Addin currenly available

## Steps to reproduce
1. Deploy the Excel plugin in Office365 Management Console following documentation : https://learn.microsoft.com/en-us/microsoft-365/admin/manage/office-addins?view=o365-worldwide
2. Launch Excel
3. Go to Insert > Addin > Admin Managed
4. "No add-in currently available"

**Comment by zhenhuangMSFT** [comment]
@bcolas thanks for reaching out to us. Admin deployment may be delayed sometimes. If you are still not seeing the deployed add-in, please try the following:
- please make sure that the user has been selected when adding users during the deployment. 
- please refresh the admin managed tab to force fetch the latest updates.

Could you try again and see if it works. If not, could you share the user's session Id to us for further investigation?

**Comment by bcolas** [comment]
@zhenhuangMSFT Here is some screen captures from our Office365 Management Console
![image](https://github.com/OfficeDev/office-js/assets/8590669/f3a6e7e3-6b12-4af9-bb31-b8df2cf48865)

![image](https://github.com/OfficeDev/office-js/assets/8590669/50bb09d5-e9dc-4b0a-90b8-fc952c1ff213)

![image](https://github.com/OfficeDev/office-js/assets/8590669/7be08694-9b26-43be-be9a-6039ab96862b)


As you can see, I am part of the users authorized on this addin
But still no addin available in my Excel

![image](https://github.com/OfficeDev/office-js/assets/8590669/ccf0c181-54c7-4d60-8a07-a4e67280be62)

**Comment by zhenhuangMSFT** [comment]
Hi @bcolas , did you follow instructions from this section? https://learn.microsoft.com/en-us/microsoft-365/admin/manage/office-addins?view=o365-worldwide#deploy-your-office-add-ins

Could you go to the admin portal and check the following setup?
![image](https://github.com/OfficeDev/office-js/assets/91410047/3c0d93f3-79c1-4703-a86b-05cda8e13773)

**Comment by bcolas** [comment]
Hi @zhenhuangMSFT 
We did follow instructions you mentioned.
Here is the screen capture you asked from our admin portal :
![image](https://github.com/OfficeDev/office-js/assets/8590669/b46b67aa-dee6-4e0e-a553-f126d16248f3)

**Comment by bcolas** [comment]
@zhenhuangMSFT Are there specific rights to give to standard users so they can see Admin Managed Addins in Excel ?
Going on our investigations, we noticed that only tenant administrators have access to the addin in Excel : no other users have access to addins in Excel.

**Comment by zhenhuangMSFT** [comment]
@bcolas could you check if the assigned users include the entire organization by clicking on each add-in item in the admin portal? 
![image](https://github.com/OfficeDev/office-js/assets/91410047/0739d69d-562a-42a3-ad2e-7aec33948e12)

**Comment by bcolas** [comment]
@zhenhuangMSFT After setting Entire organization and waiting 48 hours, addin does not appear in Admin Managed Addin
![image](https://github.com/OfficeDev/office-js/assets/8590669/3cd7a7c5-7910-4848-8c20-2d548c26f353)
![image](https://github.com/OfficeDev/office-js/assets/8590669/229e79c2-ec43-4634-acb3-e45de6638cb3)

![image](https://github.com/OfficeDev/office-js/assets/8590669/824e4445-133d-4b0a-acc4-78bfc42c6999)

Note that we are progressing : only tenant administrators can see the addin in their Excel in Admin Managed Addin

**Comment by zhenhuangMSFT** [comment]
Hi @bcolas , one possibility is that the deployment does not work for nested groups. Could you try to deploy to specific users and see if it works?

**Comment by bcolas** [comment]
@zhenhuangMSFT This is the setup that was done before
https://github.com/OfficeDev/office-js/issues/4001#issuecomment-1900918320

**Comment by zhenhuangMSFT** [comment]
@bcolas could you try to deploy to specific users that are not admin and see if they get the add-in?

**Comment by bcolas** [comment]
@zhenhuangMSFT my user is not admin and I cannot see the add-in in Excel

**Comment by bcolas** [comment]
@zhenhuangMSFT Based on microsoft support feedback, my issue seems to come from the fact that OfficeJS Addin cannot be deployed to an Exchange On-Prem Mailbox (https://learn.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-of-add-ins?view=o365-worldwide#before-you-begin)
The users for which the addin is shown have online mailboxes
Cannot understand why it depends on mail account and not on Office365 account

![image](https://github.com/OfficeDev/office-js/assets/8590669/c90ff132-f9db-43a3-9094-131ca69f8d77)

**Comment by zhenhuangMSFT** [comment]
Hey @AkhileshShah-MS, could you help customer understand the requirement imposed on On-Prem mailbox?

**Comment by shanshanzheng-dev** [comment]
Hi @bcolas, sorry for slow response. Hope you have a good day. Has this issue been solved? We value your feedback. Thanks.
