### ISSUE TITLE
Excel Windows Desktop crashing unexpectendly after loading a document property that contains json text.

### ISSUE THREAD

**Issue by georgehatg** [OfficeDev/office-js#4002]
The Excel is crashing nexpectendly after loading a document property that contains json text.
To reproduce the issue: 

1. Create an Excel file with some Custom Document Properties and add some JSON 
2. For your reference please download a sample file from here: 
[CrashingFile.zip](https://github.com/OfficeDev/office-js/files/13939114/CrashingFile.zip)
3. Now execute the following code in your addin to crash Excel: 

   Excel.run(async (context) => {
          const customDocProperties = context.workbook.properties.custom;
          customDocProperties.load(["key", "value"]);
          await context.sync(); // <-- Excel will crash here
    });

## Environment

* Platform: PC desktop
* Host: Excel
* Office version number: 2312
* Operating System: Windows
 
## Expected behavior
Excel should read the json text from the Custom Document Properties like how Excel Web works and must not crash just by reading some json from the document properties.

## Current behavior
Excel is crashing and restarting asking to go to Safe Mode.

Just fix this it looks like very high priority bug.

## Steps to reproduce

1. Create an Excel file with some Costum Document Properties and add some JSON 
2. For your reference please download a sample file from here: 
[CrashingFile.zip](https://github.com/OfficeDev/office-js/files/13939114/CrashingFile.zip)
3. Now execute the following code in your addin to crash Excel: 

`Excel.run(async (context) => {

      const customDocProperties = context.workbook.properties.custom;

      customDocProperties.load(["key", "value"]);

      await context.sync(); // <-- Excel will crash here

    });`

## Link to live example(s)

Use above Excel file.

**Comment by xai-msft** [comment]
Hi @georgehatg,

Thanks for reporting the issue. We are currently investigating. Internal tracking number: 8668512.

Thank you.

**Comment by penglongzhaochina** [comment]
Hi @georgehatg ,

your custom properties value are too long and complex. The last third value is "{"dateTime":"21-12-2023 10:30:00","timezone":2,"enableSSAO":true,"latitude":38.009476,"sunFlareEnabled":true,"compassShow":true,"highlightBorderColor":{"b":1,"r":1,"g":1},"shadowMapsEnabled":true,"sunLightEnabled":true,"gridEnabled":true,"enableBackfaceCul". It's too complicated. Have a workaround. You can delete your last one and three key-value, and excel will not crash. Or you can delete all your quotation marks in your value and then works, I hope this can unblock you. Thank you!

**Comment by georgehatg** [comment]
> Hi @georgehatg ,
> 
> your custom properties value are too long and complex. The last third value is "{"dateTime":"21-12-2023 10:30:00","timezone":2,"enableSSAO":true,"latitude":38.009476,"sunFlareEnabled":true,"compassShow":true,"highlightBorderColor":{"b":1,"r":1,"g":1},"shadowMapsEnabled":true,"sunLightEnabled":true,"gridEnabled":true,"enableBackfaceCul". It's too complicated. Have a workaround. You can delete your last one and three key-value, and excel will not crash. Or you can delete all your quotation marks in your value and then works, I hope this can unblock you. Thank you!

Too complicated for what? It is common json text it shouldn’t crash excel, arent you going to fix this?
Thanks

**Comment by penglongzhaochina** [comment]
Thanks for reporting this issue.  

It has been put on our backlog<Bug#8668512> for internal track. We will keep track of this issue and let you know if there are any updates.

**Comment by penglongzhaochina** [comment]
Hi @georgehatg ,

Your length of value exceed the 255 characters. larger values are automatically trimmed to 255 characters. This is the official doc to tell this: https://learn.microsoft.com/en-us/javascript/api/excel/excel.customproperty?view=excel-js-preview. 
![image](https://github.com/OfficeDev/office-js/assets/106959323/4e1f74e2-0d80-4f1f-9847-d2fb09d1bdaf)

We will fix the crash issue, and also your length will be trimmed to 255 characters.

Thanks!

**Comment by XuanZhouMSFT** [comment]
We have fixed the crash issue and it should be available in build 16.0.17830 and later. Please have a try.
If it still repro for you, we will re-active.
