### ISSUE TITLE
How to run code everytime the user opens any document?

### ISSUE THREAD

**Issue by HugoAlbertoNieto** [OfficeDev/office-js#4003]
I have followed these instructions:

In my Excel office.js addin I need to enable or disable certain ribbon buttons depending on the active worksheet. I have used the following code to add a handler that runs when the selection is changed:

`Office.context.document.addHandlerAsync(Office.EventType.DocumentSelectionChanged, enable_or_disable);`

I have added this code in the function that runs when the task pane opens. The `enable_or_disable` function executes the logic I need to enable or disable the buttons on the ribbon based on the active sheet.

This works fine, but now I would like this behavior to persist when the user opens any other workbook. **Is it possible to do it?** I have used this code in the `Office.initialize` event handler to set the startup behavior of the addin to `Load`:

`Office.addin.setStartupBehavior(Office.StartupBehavior.load);`

But when a new workbook is created, the above code doesn't run automatically. The user needs to interact with the addin by opening the task pane before the code actually runs..  

It seems like the `Office.addin.setStartupBehavior` is only set on the workbook level, meaning that it will only work on the specific workbook where it has been called from. 

Please, confirm if this is the intended behavior. If so, is there a way to actually run code everytime the user opens any document?

Thanks.

**Comment by Wenjun-Gong** [comment]
HI @HugoAlbertoNieto, the auto activation of your add-in with Office.initialize can only persist per document. There hasn't been a capability for an Excel add-in been enabled to activate on any document open. Would you mind share more details for you scenario which you expect turn code every time the user opens any document? We are happy to learn more, which will be helpful for us to prioritize this feature in the future. Thanks.

**Comment by HugoAlbertoNieto** [comment]
Hi @Wenjun-Gong. Thanks for your answer. Basically we have a VBA addin that is now being replaced by a modern JavaScript addin and we want to make the transition easier for our customers. Here is the scenario:

We have an Excel VBA COM Addin that is being used by some of our clients. We are now replacing the VBA addin with a modern JavaScript addin that we have created. Both addins have now the same functionality: they allow to insert some templates on the active workbook using buttons on the task pane (a userform in the VBA addin). Then the user can refresh the data from the templates using buttons on the ribbon. These ribbon buttons get enabled or disabled based on the worksheet that is active. It looks like this:

![2024-01-17-14-03-47](https://github.com/OfficeDev/office-js/assets/53156762/e4cab1e5-c5d1-4e2e-9b05-107c5420e852)

It works perfectly fine when the templates are inserted using the JavaScript addin. Now we want to provide an easy transition so that the users who use our VBA addin can start using our JavaScript addin. But when the user installs the JavaScript addin and opens a workbook that contains templates that were inserted using the VBA addin, the above functionality of enable or disable the ribbon buttons does not work right away. 

In order for that feature to work, the user needs to interact with the JavaScript addin by opening the task pane. After the user does that, the ribbon buttons get enabled or disabled correctly. So, we thought that it might be useful to be able to run a code everytime the user opens an Excel workbook that sets an event handler that runs when the user moves from one worksheet to another.

That way the feature to enable or disable the ribbon buttons will be working as soon as the user opens a workbook and the transition for the users who are currently using our VBA addin will be simpler. 

By now we will be working with our customers to let them know that they need to open the task pane so that the buttons get enabled or disabled properly. That being said, I think we can close this issue. Thanks again for your answer!
