### ISSUE TITLE
Adding a method comment in ExcelScript causes unexpected token error

### ISSUE THREAD

**Issue by Nulifier** [OfficeDev/office-js#4005]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2312
* Operating System: Windows 10
 
## Expected behavior

I expect that I should be able to add comments to class methods.

## Current behavior

Adding a comment to a class method in an ExcelScript causes an `Unexpected token 'this'` error (See reproduction below).

## Steps to reproduce

1. Create a script with the below content.
2. Try to run the script, you should receive a `Unexpected token 'this'` error.
3. Remove the comment on line 4.
4. Run the script again, it should execute properly.

## Example Script
```typescript
class Foo {
    range: ExcelScript.Range;

    // Comment
    bar() {
        return this.range.getValues();
    }
}

function main(workbook: ExcelScript.Workbook) {
    const foo = new Foo();
    foo.range = workbook.getActiveCell();
    console.log("Success");
}
```

# Provide additional details

* This only happens when use certain ExcelScript methods, I assume these ones cause the compiler to generate an asynchronous request.
* I did note that using ExcelScript objects in constructors was not allowed, but it seems to only be related to comments.

## Context
I can get the program to work without the comments, but it is useful to comment how the functions are expected to be used.

## Useful logs
With Comment:
![image](https://github.com/OfficeDev/office-js/assets/6885933/d388d15a-cee3-4be2-b128-8a0aaeff52ed)

Without Comment
![image](https://github.com/OfficeDev/office-js/assets/6885933/adf9d370-46e4-44bf-ac27-70c611235959)

**Comment by wandyezj** [comment]
Thank you @Nulifier for reporting this issue. Your repro was super helpful! 

It appears we have a super annoying bug in our infrastructure. 😞 

We have added this issue to our backlog.

## Workarounds

While we work on a fix, here are some unappealing workarounds.

- Skip adding comments before class methods that use Office Script APIs.
- Mark class methods in which you use Office Script APIs as `async`. (see example)


Example modified to mark method `bar` as `async`.

```typescript
class Foo {
    range: ExcelScript.Range;

    // Comment
    // MODIFY: mark as async
    async bar() {
        return this.range.getValues();
    }
}

// MODIFY: mark as async
async function main(workbook: ExcelScript.Workbook) {
    const foo = new Foo();
    foo.range = workbook.getActiveCell();

    // MODIFY: example call with async
    const values = await foo.bar();
    console.log(values);

    console.log("Success");
}


```

**Comment by Nulifier** [comment]
Thanks for the response! I can confirm that changing the methods to async does solve the issue but would still be better if it worked as expected.
