### ISSUE TITLE
Unable to navigate to any taskpane tab which is already in open state

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#4008]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: OfficeJS
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2310
* Operating System: 23H2
* Browser (if using Office on the web): Edge
 
## Expected behavior

Should be able to navigate to different taskpane tab by just click on task pane icon [highlighted in attached screenshot]

## Current behavior

Was able to navigate without any issues but the feature is blocked now and the only available option is by re-open the taskpane again from ribbon to navigate

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 

![Screenshot 2024-01-16 192234](https://github.com/OfficeDev/office-js/assets/86092713/50824666-a326-41e5-98cf-c61c77901b9c)

**Comment by zhenhuangMSFT** [comment]
Hi @Ifca1, thanks for reporting the issue. Do you know how did this feature get blocked? How to repro this? These information can help us better investigate into the issue.

**Comment by ghost** [comment]
Actually, this is a MS office issue, so closing the ticket
