### ISSUE TITLE
Recurrence support on Mac

### ISSUE THREAD

**Issue by nrakochy** [OfficeDev/office-js#401]
Is there any API which provides recurrence in Outlook for Mac?

## Expected Behavior
Ability to retrieve `recurrence` 

## Current Behavior
`getAsync` is returning an error object 
```
{name: "Internal Error", message: "An internal error has occurred.", code: 5001};
```

## Steps to Reproduce, or Live Example
```
Office.context.mailbox.item.recurrence.getAsync(function(result){
    console.log("FOUND RECURRENCE RESULT", result);
});
```

## Context
Integrating Outlook with a hotelling type of room scheduler - without recurrence, it is severely limited in capacity / value

Based on the conversation in [this StackOverflow thread](https://stackoverflow.com/a/51719378/3100284), it appeared that `recurrence` was supported. Indeed, I previously was able to return results correctly.

Now, I am only seeing an error. I am not sure if this is due to update in the Outlook client or the javascript api. Switching to the `beta` release also shows the same error. Were the `1.7 API requirement sets` disabled completely on Mac?

## Your Environment
* Platform: `Mac`
* Host: `Outlook`
* Office version number: `16.22`
* Operating System: `HighSierra (10.13)`

**Comment by nabil-nuvolo** [comment]
Hello! I am experiencing the same issue reported here

This was working in Mac Outlook `16.21` however is now broken in `16.22` -- is there a fix scheduled?

**Comment by nabil-nuvolo** [comment]
@kbrandl Is it possible to understand when this API will be fixed? Or can a workaround be provided?  Our product is not functional on Mac when handling recurring meetings due to this defect

Thanks!

**Comment by SureshGowthamS** [comment]
The `recurrence` API is part of `1.7 API requirement set` `Office.context.requirements.isSetSupported('Mailbox', 1.7)` returns `false` in Outlook for Mac, so I think the API is not supported yet. Check out [requirement set support](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#clients).

**Comment by nabil-nuvolo** [comment]
Hi @SureshGowthamS interestingly it was working in 16.21, perhaps you can try to verify. 

Is there any way to get recurrence information from a meeting item with the 1.6 API? This seems like a big gap

Thanks for your prompt response!

**Comment by SureshGowthamS** [comment]
You can try using EWS GetItem request, see if this helps
`<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"`
`    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"`
`    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" `
`    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">`
`  <soap:Header><t:RequestServerVersion Version="Exchange2010" /></soap:Header>`
`  <soap:Body>`
`    <m:GetItem>`
`      <m:ItemShape>`
`        <t:BaseShape>IdOnly</t:BaseShape>`
`        <t:AdditionalProperties>`
`          <t:FieldURI FieldURI="calendar:CalendarItemType" />`
`          <t:FieldURI FieldURI="calendar:Recurrence" />`
`        </t:AdditionalProperties>`
`      </m:ItemShape>`
`      <m:ItemIds>`
`        <t:ItemId Id="`<< substitute with Office.context.mailbox.item.itemId >>`" />`
`      </m:ItemIds>`
`    </m:GetItem>`
`  </soap:Body>`
`</soap:Envelope>`

[How to make EWS request from add-in](https://docs.microsoft.com/en-us/outlook/add-ins/web-services)
