### ISSUE TITLE
Content Control insertFileFromBase64 is not working in Wopi Office Online

### ISSUE THREAD

**Issue by SirDavenport** [OfficeDev/office-js#4012]
# Provide required information needed to triage your issue
We have a production microsoft WOPI environment, and have an addin that uses .insertFileFromBase64 to insert into a content control. In the Desktop version it works fine, but in the Wopi we see the spinner, but then nothing gets inserted and there is an error in the console.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC. Wopi. Hosted in AWS S3 through Cloudfront.
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 
![image](https://github.com/OfficeDev/office-js/assets/35716952/602ac33b-15ac-43bc-a502-ae46a716a220)

* Operating System: Windows
* Browser (if using Office on the web): Microsoft Edge
 
## Expected behavior
The file should insert into the content control with no issue like it does in the desktop version. Just a note, it does seem to insert the data in Word in Sharepoint, but the content control gets all screwy.
## Current behavior
We see the spinner briefly, but then nothing is inserted into the content control and there is an error in the console and sometimes it just says Waiting... and then nothing happens.
![image](https://github.com/OfficeDev/office-js/assets/35716952/53864df3-0bcf-4d0b-a43a-2c8a0c068120)

## Steps to reproduce

1. Create addin that has functionality to download a file to a blob, convert it to base64, and insert that into a contentcontrol using insertFileFromBase64(base64data, "Replace")
2. Use the addin
3. Notice that it doesn't insert.

## Link to live example(s)
Let me know and I can send a private message of the live example, but I'd rather not link it here.

**Comment by YijunMS** [comment]
@SirDavenport Thanks for reaching us. Could you provide more info about the behavior?

1. Will the content be displayed after you refresh the page?
2. Does it happen only on ContentControl.insertFileFromBase64? Is it the same for other insertFileFromBase64 Apis (for example, Body.insertFileFromBase64)?

**Comment by SirDavenport** [comment]
Howdy,
1. The content is not displayed when refreshing the page.
2. I'll have to get back to you on that.

**Comment by SirDavenport** [comment]
@YijunMS Hi, were you able to reproduce this issue?

**Comment by YijunMS** [comment]
@SirDavenport Hi, this is a known issue and the engineers are doing the investigation. Internal bug id: 8687479.

For what we have noticed, this failure may relate to some specific settings of WOPI environment. In our own WOPI test environment, the API works fine by default but may fail in some modes (for example, WOPI.EditLicensedUser).

**Comment by SirDavenport** [comment]
@YijunMS Thanks for the reply. If your WOPI environment does not have EditLicensedUser, how are updates even being made to the document?

**Comment by YijunMS** [comment]
@SirDavenport We could still edit the document in EditLicensedUser mode, but the Api didn't work in our environment.

**Comment by SirDavenport** [comment]
@YijunMS Okay, so you are confirming that there is a bug.

**Comment by YijunMS** [comment]
@SirDavenport Yes. The internal bug is 8687479.

**Comment by YijunMS** [comment]
@SirDavenport We have a fix rolling out and it should be available in two weeks. I will update here once it is available, and we may need your confirmation to see if it can solve this issue. Thanks.

**Comment by SirDavenport** [comment]
Thanks, @YijunMS. I look forward to testing the fix.

**Comment by YijunMS** [comment]
@SirDavenport Hi, the fix is deployed, please let me know if the issue is fixed.

**Comment by SirDavenport** [comment]
@YijunMS Howdy, it does seem to be working now. A little slow to respond at times, but it does insert using insertFileFromBase64. Thanks for the fix on this.
