### ISSUE TITLE
Email selection change events don't work correctly on Mac

### ISSUE THREAD

**Issue by VasilyIvanov** [OfficeDev/office-js#4013]
We are developing an Outlook add-in that should be able to work with multiple selected emails as documented [here](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select).
While testing with Outlook on Mac, we found some problems making not possible to work with multi-selection.
In particular, the add-in cannot be started if the user selects multiple emails. The `Office.EventType.SelectedItemsChanged` event is not fired at all. The `Office.EventType.ItemChanged` is fired when one email is selected but we cannot get the information about the selected item(s) because `Office.context.mailbox.item` is null and `Office.context.mailbox.getSelectedItemsAsync()` fails.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: **Mac**
* Host [Excel, Word, PowerPoint, etc.]: **Outlook**
* Office version number: **Outlook for Mac Version 16.80 (23121017)**
* Operating System: **macOS Monterey Version 12.7.2**
* Browser (if using Office on the web): **N/A**
 
## Expected behavior
- The add-in should start if multiple emails are initially selected.
- The `Office.EventType.SelectedItemsChanged` event should be fired on any email selection change.
- If one email is selected, `Office.context.mailbox.item` should contain that selected item details.
- If one or multiple emails are selected, the `Office.context.mailbox.getSelectedItemsAsync()` function should return the selected items details.
- The `Office.context.mailbox.getSelectedItemsAsync()` function should never fail.
- If the user pins the add-in and closes it, it should be pinned when started again.

## Current behavior
1.	When the app loads, it’s never pinned even if the user pinned it before. When unpinned, the app disappears on selection change. If pinned, it doesn’t. When pinned, the app could be closed by calling `Office.context.ui.closeContainer()`. Supported requirement set is 1.13. If we select multiple emails, Outlook doesn’t allow to start the add-in.
 
![image](https://github.com/OfficeDev/office-js/assets/59409548/eb5a861a-b24f-4b79-b57e-2c2b9b147afc)

2.	Pinned, subscribed to both `Office.EventType.ItemChanged` and `Office.EventType.SelectedItemsChanged` events.

![image](https://github.com/OfficeDev/office-js/assets/59409548/5bc27ac8-1fbf-4fe7-bd68-b9dba782413b)

•	Initially, `Office.context.mailbox.item` contains the selected email.

![image](https://github.com/OfficeDev/office-js/assets/59409548/fe592aa8-6a6a-42b6-a61a-161ad6a7a043)
 
•	The `Office.EventType.ItemChanged` event is fired when a single email is selected, `Office.context.mailbox.item` is always null.
•	When multiple emails are selected, the `Office.EventType.ItemChanged` event is not fired.
•	`Office.EventType.SelectedItemsChanged` is not fired at all.
•	If we try to get `Office.context.mailbox.getSelectedItemsAsync()`, it returns
 
![image](https://github.com/OfficeDev/office-js/assets/59409548/6ef2f68e-44e9-4c74-bbe8-99173382c8be)

until the selection is changed, after that if fails with 
 
![image](https://github.com/OfficeDev/office-js/assets/59409548/0f4caef8-6754-42bc-986a-0a44ac0dd187)

3.	Pinned, subscribed only to the `Office.EventType.ItemChanged` event.
•	Initially, `Office.context.mailbox.item` contains the selected email.
•	The `Office.EventType.ItemChanged` event is fired when a single email is selected, `Office.context.mailbox.item` is always null.
•	When multiple emails are selected, the `Office.EventType.ItemChanged` event is not fired.

4.	Pinned, subscribed only to the `Office.EventType. SelectedItemsChanged` event.
•	Initially, `Office.context.mailbox.item` contains the selected email.
•	`Office.EventType.SelectedItemsChanged` is not fired at all.
•	If we try to get `Office.context.mailbox.getSelectedItemsAsync()`, it returns a value initially (before selection change) and fails when the selection has been already changed.

## Steps to reproduce

1. Clone the [repo](https://github.com/VasilyIvanov/TestAddIn).
2. Install the manifest '_manifest.xml_' from the project root.
3. Start the project by `npm run dev-server`.
4. In Outlook select one multiple email.
5. Start the add-in, click the 'Run' link on it to manually run the `Office.context.mailbox.getSelectedItemsAsync()` function.
6. Try to select single and multiple emails and look at the console to identify the issues.

## Link to live example(s)

1. [Reproduction repo](https://github.com/VasilyIvanov/TestAddIn)

## Context

We would like to develop an add-in that will be able to support multiple selected emails.

## Useful logs

- [ ] Console errors
_See above._
- [ ] Screenshots
_See above._
- [ ] Test file (if only happens on a particular file)

Thank you for looking into th issue.

**Comment by ajays-msft** [comment]
@VasilyIvanov - Which folder are you in, when looking for new events from Multi-select? For example, on All Accounts, Saved Searches and On My computer folders, events specific to multi select won't be raised.

**Comment by VasilyIvanov** [comment]
@ajays-msft yes, I can confirm that the described issue occurred in the All Accounts folder.

If using select multiple is unsupported in this folder, then I have some further questions necessary for delivering a solution with an acceptable user experience:
1. Would it be possible to get a notification that the user is in the All Accounts folder? If we cannot detect this then we can only deliver unpredictable behaviour from the add-in.
2. Would it be possible to disable or close the add-in as soon as the user enters a state that is not currently supported (e.g. the All Accounts folder)?
3. The problem with the add-in not pinning correctly remains a critical issue and was unaddressed. With the current implementation the user can launch the add-in when 1 email is selected but the Office.context.mailbox.item becomes null when selecting another email in the pinned context and no events are raised when the user is selecting multiple emails. Therefore neither pinning or multi-select are supported within those folders. Also, the pinning state is not saved. If the add-in is closed, the user will have to pin it manually again.

**Comment by ajays-msft** [comment]
Thank you for the input. This is will considered as a new feature request.
We track Outlook add-in feature requests on our[Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by mrebuffet** [comment]
Link to upvote this feature request **"Either support multi-select events in All Accounts folder on Mac or automatically close the plugin"**
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/either-support-multi-select-events-in-all-accounts-folder-on-mac/idi-p/4042811
