### ISSUE TITLE
Access an API published through the Microsoft Entra application proxy

### ISSUE THREAD

**Issue by bhattikashif** [OfficeDev/office-js#4016]
I have developed a Excel Add-in using Office.js and JavaScript, it has task panes, custom functions and ribbon actions in it and uses Shared runtime and SSO is used for authentication. Now my client has moved his API from his server to Microsoft Entra application proxy, and given me URL which works when I tested on Entra Portal. But when I use same API url in my add-in, it gives me CORS error (I have tried everything in article https://learn.microsoft.com/en-us/entra/identity/app-proxy/application-proxy-understand-cors-issues but problem remains same). Now my guess is that I cannot use token get through OfficeRuntime.auth.getAccessToken with Proxy applications, but not sure about it. 

Can someone guide me or provide a sample add-in where I can use API published through Microsoft Entra application proxy.

**Comment by Wenjun-Gong** [comment]
Thanks for sharing this issue. We will take a look shortly. Assign to @zhenhuangMSFT to isolate the root reason.

**Comment by bhattikashif** [comment]
any update on it?

**Comment by zhenhuangMSFT** [comment]
@mattgeim could you share your findings with the developer? Thanks!

**Comment by bhattikashif** [comment]
its more than a month, and no comment at all. @mattgeim or anyone else who can guide me.

**Comment by zhenhuangMSFT** [comment]
Hi @bhattikashif, sorry for the delay. Could you share us the session id of the session in which you had a failed API call?
