### ISSUE TITLE
why outlook add-in is not working on desktop outlook?

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js#4017]
I created a outlook add-in using `yo office` in React Framework that is working on Outlook web but not working on desktop not showing up on desktop outlook I installed it again and again on desktop not working. when I install it successfully installed but when I close add-ins dialog and open it again the installed add-in not here its hide why? I have office LTSC Standard 2021 on desktop. 
please fix this issue, thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 15f43fe5-03e0-579c-165c-57e16b1a53ea
* Version Independent ID: 15f43fe5-03e0-579c-165c-57e16b1a53ea
* Content: [Create Office Add-in projects using the Yeoman Generator - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/yeoman-generator-overview)
* Content Source: [docs/develop/yeoman-generator-overview.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/yeoman-generator-overview.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by junaid042** [comment]
new manifest file which is created using `yo office` in react not working in desktop.
temporary fix: use old manifest.xml which is created in visual studio 2022 and change its url using new react manifest urls and use onld manifest file in new react add-in then its works for me in desktop outlook and web both

**Comment by exextoc** [comment]
Can you post a copy of the manifest that wasn't working?

**Comment by junaid042** [comment]
Hi @exextoc 
this is manifest.xml that isn't working on desktops outlook I sent it in a zip file because direct .xml file format is not supported here, please check this.
[manifest.zip](https://github.com/OfficeDev/office-js/files/13985627/manifest.zip)

**Comment by junaid042** [comment]
@exextoc  any update

**Comment by timwan10** [comment]
In your manifest in the VersionOverridesV1_0 section. There is an incomplete Hosts section. I deleted it. 
```
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Hosts>
      <Host xsi:type="MailHost"/>
    </Hosts>
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
```
So the version Overrides section now looks like: 

```
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">...
```

And it seems to work now. (note that there is only an Icon on the Message Compose Scenario in this manifest). (also note that you have to wait for you icon to download)

**Comment by junaid042** [comment]
Hi @exextoc , @timwan10 and @Wenjun-Gong 
why `yo office` creating incomplete manifest file. I tried this on multiple systems on all systems manifest is same created as default in React JS framework please fix this. 
default created manifest in React JS framework using `yo office` is only working on web outlook not working on desktops

**Comment by timwan10** [comment]
I can let the devX team know. For now I think the workaround is to manually modify the manifest file.

**Comment by timwan10** [comment]
Sorry for the delay here, this was indeed a bug introduced to the manifest file when it was being cleaned up and the <hosts> section was left there. 

I've opened an issue in that repo here: 

https://github.com/OfficeDev/Office-Addin-TaskPane-React/issues/142
