### ISSUE TITLE
Get preview / thumbnail / image of individual slides in PowerPoint using OfficeJS and Office Add-Ins (Web)

### ISSUE THREAD

**Issue by pg-dev0** [OfficeDev/office-js#4018]
We need to obtain image previews or thumbnails of each slide in an Office Add-In. We are currently developing a functionality using Office Add-Ins (PowerPoint), where users can open a PowerPoint presentation (hosted remotely) and click on the presentation to view all slides (with preview images) in the right panel of the Office Add-In. They should also be able to select a slide and insert it. We have searched through the Office Add-Ins documentation, but we could not find any method that can be used to generate thumbnail of the slides. We would greatly appreciate any assistance or alternative solutions to achieve this in Office Add-Ins.

**Comment by AlexJerabek** [comment]
Hi @pg-dev0,

You are correct that there is not a current mechanism to get a slide thumbnail from the JS APIs. I'm going to transfer this issue to the [product repo](https://github.com/OfficeDev/office-js) so the right folks can take a look at this feature request.

**Comment by AlexJerabek** [comment]
Tagging @EsterBergen to comment on any potential workarounds.

**Comment by EsterBergen** [comment]
HI @pg-dev0 - Thank you for raising this! We have heard the feedback/request and have two items in our backlog (8671262
 and  8671260. I will keep you posted as progress is made. Currently there is no work around for this scenario.

**Comment by EsterBergen** [comment]
@pg-dev0 - A follow up question for you. Are you looking to generate a thumbnail/image of an existing slide deck or the one the add-in is currently running in?

**Comment by Tjerkdb** [comment]
Without wanting to hijack the request: this also something we are really looking forward to for exactly the use case the author described.

For this to work for us both use cases could be relevant but being able to get slide images of a remote presentation makes it that much easier. But like I said. Being able to generate images for the current deck is also useful

**Comment by EsterBergen** [comment]
@Tjerkdb - thank you for this input!

**Comment by pg-dev0** [comment]
Hi @EsterBergen we are looking for capability to generate slide images of a remote deck. thanks!

**Comment by EsterBergen** [comment]
@pg-dev0 - thanks for the details! Is it safe to say that you're looking to do something similar to what the "Reuse Slides"feature does currently in PPT? (See Home Tab, Slides Section). 
<img width="205" alt="image" src="https://github.com/OfficeDev/office-js/assets/139180507/3bf74b01-ac64-48a8-b98e-8d77f06040c0">

**Comment by Tjerkdb** [comment]
Yes to a large extend. Although there might be some differences in implementation but the general usecase for us is to create a "slide library" with templates/slides to insert in your current presentation. These individual slides to insert have to be pulled form "template decks" on a remote location (e.g. onedrive). We want to create an interface with thumbnails/images of a slide so you can select these individual slides to insert.

**Comment by pg-dev0** [comment]
Yes, thanks!

**Comment by pg-dev0** [comment]
Hello 👋

Is there any update on this?

Thanks

**Comment by EsterBergen** [comment]
HI @pg-dev0  and @Tjerkdb - Thank you for your patience!
We recently released two APIs into preview that can help enable your scenario to export slides as presentations and generate thumbnails. 

exportAsBase64() and getImageAsBase64() are now in Insiders!


The following builds support the APIs:

Windows:  16.0.17628.20006 and beyond.

Web: Current release

Mac:16.85.242.0 

You should be able to access the APIs via the Beta reference ([https://appsforoffice.microsoft.com/lib/beta/hosted/office.js])
 

Here are more details: [PowerPoint.Slide class - Office Add-ins | Microsoft Learn](https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.slide?view=powerpoint-js-preview#powerpoint-powerpoint-slide-exportasbase64-member(1))

Let us know if this helps.

**Comment by flavianh** [comment]
Oh wow, right when I needed them!

**Comment by tobiasbueschel** [comment]
Hi @EsterBergen - the two APIs are definitely helpful, however, they only work with slides which are already inserted into the currently opened presentation. It would be fantastic if there is an API that would allow us to:

1. Load a remote PPTX file into memory
2. Generate thumbnails for each slide

Server-side there are various approaches using [pptx](https://python-pptx.readthedocs.io/en/latest/) and Libre Office for example. However, it would be great if this could also work client side.
