### ISSUE TITLE
Custom Function Entity Values Auto-Complete does not always work in Excel Online

### ISSUE THREAD

**Issue by zpfaltersack** [OfficeDev/office-js#4019]
# Provide required information needed to triage your issue
Custom functions can return ad-hoc entity data types. These data types may be referenced in cells and if the entity has properties on it, then excel will populate auto-complete dropdowns for the properties while typing. In Excel Online, if the auto-completed property _does not_ have any spaces in the name, then the auto-complete does not work correctly.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Let's say you have an entity shaped roughly like:

MyObject {
  Prop1: {
    Value: 25
  }
  Prop 2: {
    Value: 35
  }
}

NOTE: There is a space between 'Prop' and '2' that is important.

If this entity gets returned from a function that exists in cell C3, then in C4 you write the formula:
=C3.Prop

Then you will get 2 options that you can tab-complete: 'Prop1' and 'Prop 2'

If you select Prop1 then it will auto-complete as (scenario 1):
=C3.Prop1

and if you select 'Prop 2' then it will auto-complete as (scenario 2):
=C3.[Prop 2]

Now, in scenario 1, if you attempt to keep typing in order to select the 'Value' property, it will not be presented in auto-complete.
In scenario 2, the auto-complete 'Value' shows  up as expected.

I confirmed that in Excel Desktop, both scenarios correctly wrap the property in brackets ([]) and tab-complete works for both.
This is only a problem in Excel Online. I have not tried this in Excel for Mac.

## Current behavior
Auto-complete should work regardless of the name of the properties, just as it does in Excel Desktop.

## Steps to reproduce
See notes above.

## Context
We are hoping to take advantage of this pretty neat feature that's been somewhat recently added, but we cannot put it in front of our users if it does not behave consistently for all possible entity properties and differs between the online and desktop variants of Excel.

**Comment by ruijiaMS** [comment]
Hi @zpfaltersack,
Thanks for letting us know this issue! Could you please provide the repro javascript code which will be very helpful for us to investigate your issue.
You can also check some examples of Entity by searching the keyword of "entity" from ScriptLab -> Samples. And here is a reference about the EntityCellValue: https://learn.microsoft.com/en-us/javascript/api/excel/excel.entitycellvalue?view=excel-js-preview
