### ISSUE TITLE
Event-based activation in Outlook on mobile devices not working

### ISSUE THREAD

**Issue by vddgil** [OfficeDev/office-js#4022]
Event-based activation in Outlook on mobile devices not working. 
Our Addin is working perfectly well on Outlook desktop (mac and windows) and Outlook web, but it's not working on iOs and Android.

## Your Environment
* Platform: iOS
* Host: Outlook
* Office version number: 4.2401.0
* Operating System: iOs
 
## Expected behavior
The signature should be added to the email when creating a new email (working on all other platforms)

## Current behavior
The signature is not added

## Steps to reproduce
I can share our Addin manifest and code if you want to test.

**Comment by ajays-msft** [comment]
@vddgil - Event based activation for iOS is currently rolled out partially. We are closely monitoring the success of rollout, and if everything goes well, it will be available to 100% prod in iOS builds coming out in mid of Feb 2024.

**Comment by vddgil** [comment]
Hello @ajays-msft, 
I understand, but the thing is that my addin doesn't pass the publish process because "it doesn't work on mobile".
I have other addin with event base activation that are working on my iPhone so I presume I have a build that have the event base activation enabled.

**Comment by ajays-msft** [comment]
@vddgil - Can you please attach the manifest for further investigation?

**Comment by vddgil** [comment]
Hello @ajays-msft

Here is the manifest. Thanks  a lot !

[manifest.xml.zip](https://github.com/OfficeDev/office-js/files/14000745/manifest.xml.zip)

**Comment by exextoc** [comment]
Can you please send the test account where the Signature gets added to OutlookExtensibility@M365x53858506.onmicrosoft.com. Also try uninstalling the other Add-in you have mentioned here "I have other addin with event base activation that are working on my iPhone so I presume I have a build that have the event base activation enabled." and see if it helps.

**Comment by vddgil** [comment]
Hello @exextoc,
I created a signature for the email OutlookExtensibility@M365x53858506.onmicrosoft.com. I presume you want to run some tests with it. Regarding the other Add-in it was my last test (to try another addin with the same feature), but all my previous tests (without the additional addin) where unsuccessful :(

**Comment by vddgil** [comment]
Hello @exextoc ,
Did you have any change to test with the email provided?
Thanks in advance for your answer

**Comment by rajjha-msft** [comment]
Hey @vddgil 

Can you please share the details for the test account ?
Please send it over to : OutlookExtensibility@M365x53858506.onmicrosoft.com.

**Comment by vddgil** [comment]
Hey @rajjha-msft,

You should have received all the needed information.

Have a great day

**Comment by vddgil** [comment]
Hey @rajjha-msft, @exextoc,

Any news? We have customers waiting for the mobile version of our Add-in.
Please come back to us.

Have a great day

**Comment by rajjha-msft** [comment]
Hey @vddgil 

Add-in is running fine, but it seems like Add-in has a dependency on SSO to fetch the signature.
There is a call to `OfficeRuntime.auth.getAccessToken` which is being returned as undefined.

SSO is not supported on Mobile as of today, you can make use of NAA once it is out.

**Comment by vddgil** [comment]
Hello @rajjha-msft,
Thanks a lot for looking into it.
What do you mean by "you can make use of NAA once it is out".
Thanks for your response

**Comment by ajays-msft** [comment]
@vddgil - We are continuously working on improving the platform and as a part of this, investigating a security model that will also work on Mobile. 

There are no timelines for this, but for now there is no SSO support for add-ins on Mobile. 

We have created an internal tracking id for this and will update you when we have more information. Tracking id#4245902

**Comment by vddgil** [comment]
Ok, thanks a lot
Have a great day

**Comment by Usman1104** [comment]
> Hey [@vddgil](https://github.com/vddgil)
> 
> Can you please share the details for the test account ? Please send it over to : [OutlookExtensibility@M365x53858506.onmicrosoft.com](mailto:OutlookExtensibility@M365x53858506.onmicrosoft.com).

Can you help me also?
