### ISSUE TITLE
Windows-1250 encoded subject causes addins to not load in Windows Outlook clients.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#4027]
Addins like Translator or Message Header analyzer, crash (does not load) in Windows-Outlook clients. This happens when the email has a subject that is encoded with Windows-1250. OWA and MAC-Outlook do not have this behavior. 

A sample text of a Windows-1250 encoding is shown below : 
`Subject: =?windows-1250?Q?FW:_Twoja_przesyE=02ka_zostaE=02a_nadana?=
`
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop, Windows 10
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: , Office Version 2401 Build 17231.20008
* Operating System: Windows 10
* Browser (if using Office on the web): Browser does not have this issue.
 
## Expected behavior

The addins should not crash because of the Windows-1250 encoded subject.

## Current behavior

Currently, all addins that access the value of Office.mailbox.item.subject, which is encodeded in Windows-1250, will not load in Windows Outlook. And I am assuming it is crashing.

## Steps to reproduce

1. Export one email from your mailbox as an eml file.
2. Replace the eml file's subject with this : `Subject: =?windows-1250?Q?FW:_Twoja_przesyE=02ka_zostaE=02a_nadana?=`
3. Save the modified eml file.
4. Import the eml file back into outlook.
5. Open the imported eml file with windows-outlook client.
6. Click on either Message Header analyzer or Translator addin.
7. Addin will not load.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by glr0221** [comment]
@exextoc 
It seems like this is issue is not isolated to Windows-1250 characters. Addins in Windows-outlook-client crash when the subject of the email has undefined/unknown characters. An example of a subject (encoded in rfc-2047) with invalid characters is provided below : 

`Subject: =?UTF-8?B?n50e?=`

I think the crash happens when we use `Office.context.mailbox.item.subject` to get the subject.

I have tested with our addin, Message Header analyzer and Translator addins. All of which crashed or stuck in loading when processing the email with a subject that has invalid characters. Please take note that this happens only in Windows-outlook-clients. OWA, MAC-outlook and mobile are working fine. 

Thanks.

**Comment by Oleg-O** [comment]
I couldn't reproduce this so far. How exactly do you do step 4 (import)?

**Comment by glr0221** [comment]
Hello @Oleg-O ,

Thank you for checking on this. I just use outlook for mac to open the eml file. Once opened, I then import the message into my mailbox. I will try and look for a windows-1250 encoded sample for you and attach the sample with this ticket.

Thank you.

**Comment by glr0221** [comment]
@Oleg-O 

I re-tested this issue with Outlook build (BETA)  :

Microsoft® Outlook® for Microsoft 365 MSO (Version 2404 Build 16.0.17531.20000) 64-bit 

And I found that the bug is not reproducible anymore. I think it got fixed in one of the newer builds. 

We can close this now and thank you again.

**Comment by Oleg-O** [comment]
Great - thanks for letting me know!
