### ISSUE TITLE
Unavailability of INDIA to verify in Microsoft Developer Program

### ISSUE THREAD

**Issue by mridun-gupta** [OfficeDev/office-js#4033]
# Provide required information needed to triage your issue
I was trying to register for the Microsoft 365 Developer Program, and while verifying the number for the program application, the backend is not listing the +91 country code and India to choose and to proceed.

## Expected behavior

The backend should list +91 country code and India which I would have chosen to get enrolled in the program.

## Current behavior

It does not list the +91 country code and India at all.

## Steps to reproduce

1. Register for Microsoft 365 Developer Program
2. Choose in the country for the number verification

## Context

I was trying to register for Microsoft 365 Developer Program

## Useful logs

- [x] Screenshots
![image](https://github.com/OfficeDev/office-js/assets/91019667/f3c74531-736f-4099-b9bd-70613ce9397f) ![image](https://github.com/OfficeDev/office-js/assets/91019667/408a91bb-d58e-4827-ad30-36a38f5cde8c)

**Comment by mridun-gupta** [comment]
@Wenjun-Gong @KelBowen
Please assign someone to this issue ASAP, and ask them to look into this at the earliest (and share some update)

**Comment by MuhammadMuddassir408** [comment]
We are also not able to see Pakistan +92 in it. @mridun-gupta , @Wenjun-Gong @KelBowen

**Comment by mridun-gupta** [comment]
Thank you, @michelleranmsft, for assigning it to @KelBowen. However, could you please check if either @KelBowen is out of the office/offline or not a member of @OfficeDev on GitHub?

**Comment by niteshraj2310** [comment]
![Screenshot 2024-01-27 153328](https://github.com/OfficeDev/office-js/assets/54551557/3d8a53df-e3be-4809-a8ec-4ece5d2e936b)

Now getting this error while trying to sign up for sandbox on https://developer.microsoft.com , and also, I use the same number for my Microsoft account login, and it works well.

**Comment by mridun-gupta** [comment]
Correct @niteshraj2310, Issue already opened - https://github.com/OfficeDev/office-js/issues/4000

**Comment by mridun-gupta** [comment]
Issue Resolved!

**Comment by KelBowen** [comment]
We're sorry to hear that you are having issues joining the developer program.

Country-specific outages
We recently had some service issues and many countries were temporarily blocked from joining. India was one of the countries affected but should no longer be blocked. 

This issue has resolved but note the following: Geographic limitations. For technical and security reasons, the Microsoft 365 Developer Program only supports a subset of countries/regions listed here: [Microsoft 365 International Availability](https://www.microsoft.com/en-us/microsoft-365/business/international-availability). We review our supported country list regularly. If you are unable to sign up from your country or region, then it means we do not support it at this time.

Membership benefits
While you can still join the developer program, access to the free Microsoft 365 E5 subscription is currently paused for the short-term while we adjust the qualifications for that benefit. To stay apprised of changes, [please follow our blog](https://learn.microsoft.com/en-us/answers/questions/1510808/error-when-verifying-phone-number-for-e5-tenant).

**Comment by mridun-gupta** [comment]
Thank you, @KelBowen, for the update.

**Comment by KelBowen** [comment]
@mridun-gupta 
Technically, no countries are currently blocked but most customers cannot currently acquire a new tenant due to a different set of conditions.
We are piloting a new verification process now and hope to roll it out in the next two-three weeks on the site or sooner. After joining the program, this new process allows customers to request a tenant, go through a validation process, and then receive an invitation. We'll announce when this feature is available on the [blog](https://devblogs.microsoft.com/microsoft365dev/tag/microsoft-365-developer-program/).

**Comment by mridun-gupta** [comment]
Thank you for the update, @KelBowen.
