### ISSUE TITLE
Sometimes the whole page changes to be grey out after pressing Ctrl + A

### ISSUE THREAD

**Issue by monominia** [OfficeDev/office-js#4034]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: N/A
* Operating System: Windows 11
* Browser (if using Office on the web): Latest Chrome
 
## Expected behavior

The whole document page shouldn't get grayed out.

## Current behavior

Using keyboard, press Ctrl + A to select all typing at the left side of Word. Sometimes, the whole page suddenly changes to be grey out without recovering. Please see the attached video. The replicated percentage is about 30%.

## Steps to reproduce

1. Type in some characters inside the document page.
2. Press Ctrl + A to select all.
3. The whole page grayed out.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [x] Screenshots

https://github.com/OfficeDev/office-js/assets/13508893/b8ee9afd-0276-4524-a993-b44ca4747ead

- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by zhenhuangMSFT** [comment]
Hi @monominia, thanks for reporting the issue. Could you elaborate a bit more about how this is related to our office JS APIs? Thanks!

**Comment by monominia** [comment]
Hey @zhenhuangMSFT ! I've no idea whether it's related to JS APIs, so could you recommend us some other repos where I can fire up this issue ticket?

**Comment by zhenhuangMSFT** [comment]
Hi @monominia, I noticed that you were using an add-in in the video. Does this only happen after you interact with the add-in?

**Comment by monominia** [comment]
Hey @zhenhuangMSFT , yeah it only happens after we open the add-in and did some interactions.

**Comment by zhenhuangMSFT** [comment]
Hi @monominia , could you please let us know which add-in you used and what specific interactions you had with the add-in such that we could repro the issue and investigate the root cause. Looks like the add-in you launched in the video is not a public available add-in.

**Comment by monominia** [comment]
> Hi @monominia , could you please let us know which add-in you used and what specific interactions you had with the add-in such that we could repro the issue and investigate the root cause. Looks like the add-in you launched in the video is not a public available add-in.

Yeah, it's not a public repo, can I just share the dev manifest file with you guys and you'll be able to play with it locally.

**Comment by zhenhuangMSFT** [comment]
Hi @monominia, if the issue still persists, could you share us the manifest and the repro steps? Thanks!

**Comment by monominia** [comment]
Hey @zhenhuangMSFT , attached is our manifest file:
[manifest-dev.zip](https://github.com/OfficeDev/office-js/files/15095100/manifest-dev.zip)

Also, this is the screenshot of this problem. We don't have stable steps to re-produce it, but it really happened often.
![image-20240423-044752](https://github.com/OfficeDev/office-js/assets/13508893/a7ef85fb-a013-464c-8d8a-0beb48c18f52)

**Comment by shanshanzheng-dev** [comment]
Hi @monominia, I also tried repro but cannot. As you mentioned this cannot consistently repro, after careful consideration, our team has decided to not fix this issue in the short term. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.  Thanks.
