### ISSUE TITLE
[BUG] SSO doesn't work on macOS Sonoma - neither in App nor on the Web - OfficeRuntime.auth.getAccessToken() always returns 13006 Client Error

### ISSUE THREAD

**Issue by tuskar-dev** [OfficeDev/office-js#4035]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: macOS & Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.80 (23121017) & Web
* Operating System: macOS Sonoma 14.2.1
* Browser (if using Office on the web): 
    Chrome - Version 120.0.6099.234 (arm64)
    Firefox - 121.0.1 64bit
    
 
## Expected behavior
Return valid identity token from Microsoft

## Current behavior

Always returns 13006 error code - client error

## Steps to reproduce

Easiest way to reproduce is to run official complete SSO sample: 

`
git clone https://github.com/OfficeDev/Office-Add-in-samples sso && cd sso/Samples/auth/Office-Add-in-NodeJS-SSO/Completesso && npm install  && npm run configure-sso && npm run start`

This runs flawlessly on windows but on macOS it fails with 13006 error code which is not really helpful.
We tried doing everything that the documentation suggests but even after cache delete, hard restart etc. it always fails with 13006

## Link to live example(s)

Can't really share a scriptlab demo  as this example would need to be a verified addin in Azure.

# Provide additional details

None

## Context

We need to validate identity of our users against private domain and allow them to access internal services.

## Useful logs

This is only thing that error returns:
{
    "name": "Error occurred in the authentication request from Office.",
    "message": "An unexpected error occurred in the client.",
    "code": 13006
}

**Comment by exextoc** [comment]
Can you please share the network logs at this id OutlookExtensibility@M365x53858506.onmicrosoft.com

**Comment by tuskar-dev** [comment]
Sorry for the late reply - commenting just to let you know that enabling 2FA cleared this issue and everything worked as expected. Thank you
