### ISSUE TITLE
MessageCompose.setSelectedDataAsync always does not add to the email body in Outlook for Windows 

### ISSUE THREAD

**Issue by gs-skujala** [OfficeDev/office-js#4038]
When using MessageCompose.setSelectedDataAsync, text should be inserted to the body which is working as expected in Outlook Web, Outlook for MAC but it is failing always in Outlook for Windows

## Current Behaviour
- In the case of Outlook for MAC & Outlook web, body.setSelectedDataAsync always adds the data to email body with out any issues
- When we turn to Outlook for windows and try adding the same data into email body via **body.setSelectedDataAsync** method, it throws us an error with error code - '2006'

## Expected Behaviour
- For the same data, the **body.setSelectedDataAsync** method should add it to email body with out breaking

## Useful logs
We are always receiving this below error message and code from the callback argument which are as below
- error message: 'The format of the specified data object is invalid.'
- error code: '2006'

## Your Environment
* Platform [PC desktop]: Windows Laptop
* Host: Outlook
* Office version number: Microsoft 365 MSO (Version 2310, Build 16.0.169424.20054 | 64 Bit)
* Operating System: Windows NT 10.0; Win64

**Comment by millerds** [comment]
That error is usually an indication that the type of data being inserted doesn't match the type of the body.  Can you give a more specific sample of the code you are trying to run?

**Comment by gs-skujala** [comment]
Sure I can provide you a sample string that is failing to be inserted into the outlook body below txt file. 
This is a simple HTML content with basic styles.

[sampleTemplate.txt](https://github.com/OfficeDev/office-js/files/14108417/sampleTemplate.txt)

This issue is only observed in Outlook Desktop app but in Outlook for Web, it is being added into body perfectly fine.

**Comment by millerds** [comment]
I'm looking for an example of the add-in script code that you are trying to run . . . specifically the setSelectedDataAsync call and the data being sent to it . . . not html.

**Comment by gs-skujala** [comment]
Below is the code snippet we are using to add content into body
 
here `content` consist of simple text in HTML format which I shared you in my earlier response
& we are also adding `coercionType` with value `Html` in 2nd parameter

`Office.context.mailbox.item.body.setSelectedDataAsync(content, {`
`    coercionType: Office.CoercionType.Html`
`        },(result) => {`
`            if (result.status === Office.AsyncResultStatus.Succeeded){`
`                 // CONTINUE WITH USER AUTHENTICATION`
`            }`
`        })`

**Comment by millerds** [comment]
Thanks.  That helps me understand more what's going on.

Are you checking the body type before trying to insert (using getTypeAsync) or are you just trying to insert it?  Trying to insert as HTML into a plain text will with throw an error.

Also . . . have you tried a simpler HTML to insert and does that work?

**Comment by gs-skujala** [comment]
Seems like issue is resolved for the user by itself somehow. Without making any changes from our side.
Thanks Miller, will open this issue if we see this issue again.
