### ISSUE TITLE
Adding two custom functions referencing other workbook causes excel crash

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js#4039]
# Provide required information needed to triage your issue
When user uses combines (e.g. adding them) 2 custom functions which reference other workbook it will crash excel

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2311 Build 16.0.17029.20140, 64-bit 
* Operating System: W11
* Browser (if using Office on the web): x
 
## Expected behavior

Excel should not crash and it should calculate the value correctly

## Current behavior

Currently it will cause crash.

## Steps to reproduce

1. Create one workbook with values in A1 and A2 in Sheet1, e.g. 5 and 6, save that workbook to c:\1\scriptlab-test-crash.xlsx
2. Create second workbook, add scriptlab and let it register basic custom function (counting sphere volume SCRIPTLAB.BASICCUSTOMFUNCTION.SPHEREVOLUME).
3. Copy this formula to A1 and let it evaluate:
`=SCRIPTLAB.BASICCUSTOMFUNCTION.SPHEREVOLUME([scriptlab-test-crash.xlsx]Sheet1'!$A$1)+SCRIPTLAB.BASICCUSTOMFUNCTION.SPHEREVOLUME([scriptlab-test-crash.xlsx]Sheet1'!$A$2)

**Comment by rundongmsft** [comment]
Thanks @4tti for your report, we reproduced this crash and created internal bug item 8686846 to track it. Will let you know if any update.

**Comment by rundongmsft** [comment]
Hi @4tti, we have submitted a hotfix to resolve this crash issue. We will notify you as soon as it is released.

**Comment by zhenhuangMSFT** [comment]
Hi @4tti, does the fix work for you? If so, could you help close the issue? Thanks!

**Comment by 4tti** [comment]
Looks like it is fixed. Thanks!
