### ISSUE TITLE
Not able to debug Outlook Web add-in in new Outlook (Desktop)

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#4041]
we are developing office web Addin for outlook using event based (Smart Alert) .The Addin is generated using office yo generator Task Pane add-in using the React framework

when opening our Outlook Web add-in, we can use "Inspect" option (by performing right click from the mouse) in the web add-in taskpane (right side pan) as below in OWA version . 
![image](https://github.com/OfficeDev/office-js/assets/142812553/f479f427-d466-4166-a367-614107128b10)

When opening the same Outlook Web add-in in New Outlook (Desktop),

![image](https://github.com/OfficeDev/office-js/assets/142812553/9da8ec43-b300-4a9a-bda6-eb57a8ff1eed)

Our Outlook Web add-in not working in the New Outlook (Desktop) and throwing some error and this "Inspect" element is not showing when we will do right click in the web add-in taskpane (right side pan) and we are not able to debug our Outlook Web add-in regarding what error/exception occur in our Outlook add-in,

**Comment by ajays-msft** [comment]
@geetamshukla - You can start new outlook from command line with this command : "olk.exe --devtools" which will open dev tools.

**Comment by geetamshukla** [comment]
> @geetamshukla - You can start new outlook from command line with this command : "olk.exe --devtools" which will open dev tools.
 I have already tried that but its not working for Task pane Addin.

**Comment by ajays-msft** [comment]
@geetamshukla Did you launch the command from powershell window, or regular command line? Please try launching from powershell window.

**Comment by rajjha-msft** [comment]
Are you still facing the issue @geetamshukla ?

**Comment by geetamshukla** [comment]
> from comman

I am able to debug addin now in New Outlook ..Thanks
