### ISSUE TITLE
Issue with Outlook plugin working in Web

### ISSUE THREAD

**Issue by LTErtz** [OfficeDev/office-js#4043]
We have an outlook plugin that works fine in desktop, but is not working in the web (any browser). In web this error appears: 
![image](https://github.com/OfficeDev/office-js/assets/9950595/b7257a7c-8ea2-49d4-a2f7-61a9cb53815a). 
We see the following error in the network logs : net::ERR_BLOCKED_BY_RESPONSE. 
It seems that for some reason static content cannot be loaded. Is there any specific admin settings in outlook that should be enabled to allow for the plugin to work?
Thanks!

**Comment by exextoc** [comment]
Can you please share the details of the network call which is failing, also do you see any errors in console?
