### ISSUE TITLE
Addin is not available in the store.

### ISSUE THREAD

**Issue by vinay-sattur** [OfficeDev/office-js#4044]
# Provide required information needed to triage your issue
We have two addins the store. "WA200002196", "WA200002270" which were working fine till yesterday. But now we are getting an error saying,
"Can't find Office Add-in from Microsoft AppSource given addin ID: WA200002270 (content market: en-US). Exception details: {}"
"Can't find Office Add-in from Microsoft AppSource given addin ID: WA200002196 (content market: en-US). Exception details: {}"

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __Office on the web____
* Host [Excel, Word, PowerPoint, etc.]: ___Excel___
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior

The addins should auto load.

## Current behavior

The addins are not found.

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ___We are loading the Excel online using WOPI protocol and then the file should auto load the addin.
2. We are using "host_install_addins" while submitting the form to WOPI. 
3. The Addin are of type Taskpane.___

## Context

We are using the excel sheet to create accounting questions and students can attempt those questions. The application is integrated with the McGrawHill's Connect platform. There are tens and thousands of students are impacted because of this issue.

## Useful logs

Session id: 99392682-57f5-4936-b26d-ee75d86d1cc7
build: 16.0.17318.42309

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by AkhileshShah-MS** [comment]
Hey @vinay-sattur ! Thanks for reaching out to us for this issue. Is the issue limited to Excel on Web or its reproducing on other platforms as well? 
@akshayta23 Looks like the apps listed by customer are no longer available on AppSource. Could you please look into why they were removed.

**Comment by akshayta23** [comment]
Thanks for raising this issue. We have created an internal tracking item to investigate the issue. We will update you once the issue is resolved.

**Comment by vinay-sattur** [comment]
Hi @AkhileshShah-MS , @akshayta23 , We noticed that the js file "https://ajax.aspnetcdn.com/ajax/3.5/MicrosoftAjax.js" was not loading in our network, due to the IP(117.18.232.200) represented malicious behavior, was blocked at the firewall. After unblocking the IP addins are loading fine.
