### ISSUE TITLE
Missing web add-ins from ribbon in shared mailboxes on Outlook Online, but still having the event-based part functioning.

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js#4045]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Web
* Browser (if using Office on the web): Any
 
## Expected behavior

When using "Open another mailbox"  to open a shared mailbox in Outlook Online, the behavior for the web add-ins is consistent. It should either show and run the event-based web add-ins from the main default mailbox or not show and run them at all.

## Current behavior

Currently, it looks like no Web Add-in is displayed on the "More apps" or Ribbon's "Apps", but web add-ins with event-based actions from the originating mailbox (default one, the one that opened the shared mailbox) are run. This leads to a weird and unfortunate behavior. 

In our case, the roaming settings are set from the event-based add-in, through the task pane. The task pane can be triggered from:
- the ribbon
- a notification
As the ribbon is not visible, only the notification can be used. As the notification is shown only when there is nothing set in the roaming settings, once a user clicks the notification, accesses the pane, and sets the roaming settings, they will be there forever. A different user accessing the shared mailbox will:
- get the functionality based on the first user's roaming settings
- not be able to remove them without some developer skills

## Steps to reproduce

1. Open a shared mailbox using "Open another mailbox" functionality
2. Use a web add-in having both Task pane and event-based activation deployed centrally for the entire organization. The web add-in should set some roaming settings

Notify that:
- the web add-in is not visible in the Apps ribbon
- the runtime settings are shared for all users and can't be changed/removed

**Comment by rajjha-msft** [comment]
Hey @bogdanst24 

Can you please share the network logs over to: OutlookExtensibility@M365x53858506.onmicrosoft.com for further investigation?

**Comment by bogdanst24** [comment]
Thank you, shared the network logs

**Comment by rajjha-msft** [comment]
The mail we received from you is for a different issue. 
Please collect the logs for the issue #4045 and send it over to OutlookExtensibility@M365x53858506.onmicrosoft.com. 

Also, please use the **_Issue No - Issue Title_** as the subject.

**Comment by bogdanst24** [comment]
I have reshared the logs through a link now, as the attachment might have been too big for our policies. The network logs are for the correct issue and reproducing it.

**Comment by bogdanst24** [comment]
Were any changes made? I can't see the issue anymore, meaning that the web add-ins are not functioning at all in the shared mailbox now (when opened as another mailbox). 

The store is completely empty, the legacy in-client store doesn't allow installing any add-in, and deployment through the admin center targeting the shared mailbox doesn't do anything.

**Comment by rajjha-msft** [comment]
You should be able to install add-ins via legacy store using the URL : https://aka.ms/olksideload.

**Comment by bogdanst24** [comment]
I am aware of this hack and am using https://outlook.office.com/mail/inclientstore instead as that is accessible even on shared mailboxes. However, it looks like addins cannot be side-loaded in shared mailboxes.

I just found this [list of requirements](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=modern%2Cjsonmanifest#shared-mailboxes-1) for a web add-in to work in shared mailboxes, but something is not right. 

_What we have currently (deployed and used by customers:_
Manifest with ReadWriteItem permissions, no `SupportsSharedFolders` set, and event-based behavior alongside the task pane.

_Current behavior_
The web add-in is not visible in the shared mailbox as a deployed web add-in and cannot be accessed. **However, the event-based is still working just like I reported it initially with no option to open the task pane.** The task pane part is expected.

_Questions and issues_
1. In this scenario, on shared mailbox opened in a new tab and a manifest without `SupportSharedFolders` set, Is it supposed to run at all if the requirements described in the documentation are valid? The fact that the event-based part is still running looks like a bug.
2. Is this entire list of requirements correct for a web add-in to run in shared mailboxes opened in a new tab? Grabbing requirements from different articles:
- `SupportsSharedFolders` set to true in the manifest, just after the `DesktopFormFactor`, with both `VersionOverrides` registered
- The Web add-in has to be deployed centrally. Does not work when sideloaded.
- The Web add-in is deployed to both the user and the shared mailbox. It is not enough to have it deployed to the user only.

**Comment by ajays-msft** [comment]
Is this still an issue or does #4110 clarify your questions?

**Comment by bogdanst24** [comment]
Yes, this is still an issue

**Comment by ajays-msft** [comment]
Hi @bogdanst24 - Which specific point is the list is still an issue?

**Comment by bogdanst24** [comment]
It is the main point of this report. Web add-in deployed only to the user (not deployed to the shared mailbox), with:
- event-based activation on "OnNewMessageCompose"
- no SupportsSharedFolders set

Current behavior: the web add-in is not visible in the ribbon, but the event-based action is triggered.

**Comment by neprasad-microsoft** [comment]
Hi @bogdanst24 
Can you share your add-in manifest/AppSource link so that we can repro and debug the issue. You can share it on OutlookExtensibility@M365x53858506.onmicrosoft.com and mention the Issue Number and Title in the subject line.
