### ISSUE TITLE
Cannot read properties of undefined (reading 'register') when receiving message from parent in dialog 

### ISSUE THREAD

**Issue by DJay921** [OfficeDev/office-js#4046]
I'm unable to register the event to handle a dialog.messagechild which is giving me a `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'register')`

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2021
* Operating System: Windows 11
 

## Below is the example 
**Host page sending the data**
```
const sendToDialog = async (args) => {

  window.Office.context.ui.displayDialogAsync(
    "https://localhost:3000/mypage.html",
    { height: 60, width: 50 },
    function (asyncResult) {
      const dialog = asyncResult.value;
      dialog.messageChild(JSON.stringify({ HI: "Hi" }));
    }
  );
  args.completed();
};
```
**mypage.html (dialog)**
```
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>

</head>

<body>
  <div class="container">
      <input type="file" id="fileInput" />
  </div>
</body>

</html>

<script>

Office.onReady(function () {
  Office.context.ui.addHandlerAsync(
    Office.EventType.DialogParentMessageReceived,
      onMessageFromParent,
      onRegisterMessageComplete);
});

function onRegisterMessageComplete(asyncResult) {
  if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
    console.log(asyncResult.error.message);
  }
}

function onMessageFromParent(arg) {
  const messageFromParent = JSON.parse(arg.message);
  console.log(messageFromParent)
}
</script>
```
**Error screenshot**
<img width="470" alt="image" src="https://github.com/OfficeDev/office-js/assets/14841097/fd49d4f5-d510-4e02-8def-b40d497d9a13">

**Comment by DJay921** [comment]
Found another similar issue https://github.com/OfficeDev/office-js/issues/2372

**Comment by zhenhuangMSFT** [comment]
Hi @m-hellesen, could you please help take a look at this dialog API related issue? Thanks!

**Comment by mhelles** [comment]
Hi @DipanshuJuneja, what appears to be happening here is that the dialog is not set up yet when you are trying to register the handler, have you attemped to wait for the dialog to be ready before attaching? Here is a example from the other issue you linked: https://github.com/OfficeDev/office-js/issues/2372#issuecomment-1214564587

**Comment by DJay921** [comment]
Hi @mhelles yes thank you, I had tried the example and this had worked for me. I will close this issue since the original issue is still opened.
