### ISSUE TITLE
Link which allow to work with Outlook add-ins does not work for @outlook.com accounts 

### ISSUE THREAD

**Issue by OlegRomaniuck** [OfficeDev/office-js#4047]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: MAC
* Host [Excel, Word, PowerPoint, etc.]: Outlook office for web
* Office version number: last
* Operating System: Monterey 12.7
* Browser (if using Office on the web): Chrome 121
 
## Expected behavior

User some_user_name@outlook.com can open iframe which allow to it work Outlook add-ins install/remove by this link https://aka.ms/olksideload, which Microsoft recommend here => https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=web
## Current behavior

Sub-window ( iframe) does not open when authorised user try it open using this link https://aka.ms/olksideload
## Steps to reproduce

1.  Login as user some_user_name@outlook.com ( where some_user_name is your account) into Outlook web
2. Insert into search line this URL => https://aka.ms/olksideload
3. Nothing happen

## Context

This link https://aka.ms/olksideload is useful because for some our accounts install addin button was removed and we can not remove or reinstall adding
## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)
<img width="1399" alt="Screenshot 2024-01-24 at 18 03 01" src="https://github.com/OfficeDev/office-js/assets/11087838/0ac2db1c-5e22-4e87-b2c2-a5152124cd6f">

**Comment by exextoc** [comment]
After loading https://aka.ms/olksideload url, it takes some time to load the store iframe, can you share the repro video with us.
