### ISSUE TITLE
Latest JS and UI Changes are not reflecting in Outlook Web add-in (TaskPane) in new Outlook (Desktop) 

### ISSUE THREAD

**Issue by geetamshukla** [OfficeDev/office-js#4051]
we are developing office web Addin for outlook using event based (Smart Alert) .The Addin is generated using office yo generator Task Pane add-in using the React framework 

Latest JS and UI Changes are not reflecting in Outlook Web add-in (TaskPane) in new Outlook (Desktop)  even after 3-4 days and as We are unable to open devtools For Task pane Add-in in New Outlook ,we are unable to clear the cache . 

We tried clearing up below cache location in end users m/c still the issue is same . 

%LocalAppData%\Microsoft\Windows\INetCache\ 
C:\Users\<<UserName>>\AppData\Local\Microsoft\Office\16.0\Wef 
C:\Users\<<UserName>>\AppData\Local\Microsoft\Olk\cache 
C:\Users\<<UserName>>\AppData\Local\Microsoft\Olk\EBWebView
C:\Users\<<UserName>>\AppData\Local\Microsoft\Outlook\RoamCache 

Also ,We tried using Microsoft Edge DevTools Preview and tried changing the default broswer for New Outlook using below option 
npx office-addin-dev-settings webview "manifest.xml" edge-legacy   but still not able to see the debug targets in Microsoft Edge DevTools Preview . 

We even tried launching New Outlook using  olk.exe --devtools and opened edge devtools but still not able to see inspect option for Web Addin in New Outlook . 

PFB Outlook Version . 

<img width="960" alt="image" src="https://github.com/OfficeDev/office-js/assets/142812553/8435f77d-d768-4981-8993-eb496502ed58">

**Comment by ajays-msft** [comment]
@geetamshukla - Is your addin running locally, or is it deployed on a server?

**Comment by geetamshukla** [comment]
> @geetamshukla - Is your addin running locally, or is it deployed on a server?
@ajays-msft 
I have tried both option . Not able to see latest changes for New Outlook Thick Client

**Comment by ajays-msft** [comment]
@geetamshukla - In order for any changes related manifest of your locally developed addin , that was first deployed via "npm start" to also show up in New Outlook, you will need to explicitly install the manifest in Outlook on Web.

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/one-outlook#test-your-add-in-in-the-new-outlook-on-windows

What is the scenario you are trying to achieve? Can you please help me understand?

**Comment by rajjha-msft** [comment]
Hey @geetamshukla 

Are you still facing the issue ?

**Comment by geetamshukla** [comment]
> Hey @geetamshukla
> 
> Are you still facing the issue ?

yes ..for any new changes we are updating Manifest version and GUID still changes are not reflecting immediately  in end user's m/c

**Comment by rajjha-msft** [comment]
- Are these changes local or deployed through web ?
- How are you propagating the changes (CD / Sideloading the manifest) ?
- Does it work for OWA or any other client ?

**Comment by geetamshukla** [comment]
> * Are these changes local or deployed through web ?
> * How are you propagating the changes (CD / Sideloading the manifest) ?
> * Does it work for OWA or any other client ?

Are these changes local or deployed through web ?--> Post deployment /through web \
How are you propagating the changes (CD / Sideloading the manifest) ?--> Sideloading the manifest
Does it work for OWA or any other client --> it takes 8-24Hrs to reflect changes if we r not clearing up the cache explicitly ..

How the Manifest gets cached in OWA /Old Thick Client /New Thick Client  ?  As I have observed that even though we are changing the Manifest version + GUID  for each deployment .Still changes are not reflected immediately. We need to explicitly clear the cache to get latest changes which is not ideal for production scenarios .  We can not go and clear each users browser cache 

Also changing the Manifest version + GUID  for each deployment is not good  option  as when we are re-deploying the manifest it takes 24-48Hrs to push Addin to end user's m/c  .

**Comment by rajjha-msft** [comment]
When you say each deployment takes 24-48 hours, is it through CD ?

**Comment by geetamshukla** [comment]
> When you say each deployment takes 24-48 hours, is it through CD ?
@rajjha-msft 
No ,from CD we deploy changes to server within secs . 
Its when we are adding user to an AD group and we install/re-install the Manifest in exchange admin ..at that time the Addin takes 24-48hrs to reflect in end users m/c .
