### ISSUE TITLE
Installed Add-in does not display for user

### ISSUE THREAD

**Issue by OlegRomaniuck** [OfficeDev/office-js#4052]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Web Outlook
* Office version number: last
* Operating System: Monterey 12.7
* Browser (if using Office on the web): Chrome 121
 
## Expected behavior

The user is able to see the  installed add-in in Outlook "Apps"  sub-window and have access to it through "Apps" button. Please look into screenshots
## Current behavior

Add-in was installed by "from File" but it does not display for user in "Apps" 
## Steps to reproduce

1. Open  personal Outlook 
2. Go to add-ins manager iframe by this url https://aka.ms/olksideload
3. Remove add-in 
4. Install add-in using file manifest
5. Wait until add-in will be installed
6. Close iframe
7. Click on "Apps" button: just installed add-in does not display
8. Refresh page 
9. Click on "Apps" button: just installed add-in does not display

## Link to live example(s)

# Provide additional details

## Context

For the average user, it seems that the add-on was not installed, what makes them delusional
 I need install/remove add-in because I have different versions of it
## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)
<img width="378" alt="Screenshot 2024-01-25 at 12 23 10" src="https://github.com/OfficeDev/office-js/assets/11087838/8412fc65-92f8-4e7c-ba0b-4c8179fc97ab">
<img width="314" alt="Screenshot 2024-01-25 at 12 08 48" src="https://github.com/OfficeDev/office-js/assets/11087838/cb322b34-c082-4b89-8ee9-63701f528791">
<img width="964" alt="Screenshot 2024-01-25 at 12 12 55" src="https://github.com/OfficeDev/office-js/assets/11087838/15617252-4f84-435b-adc5-286a369f1dc9">

**Comment by exextoc** [comment]
Does the add-in take some time to appear or it never appears ?
