### ISSUE TITLE
Impossible to Open DevTools to Clear Browser Cache in New Outlook Anymore

### ISSUE THREAD

**Issue by XENOpz** [OfficeDev/office-js#4056]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: New Outlook
* Office version number: 1.2024.103.100
* Operating System: Windows 10
* Browser (if using Office on the web): N/A
 
## Expected behavior
I press F12. Dev Tools appears.

## Current behavior
You press F12. Nothing happens.

## Steps to reproduce
1. add config.json to %localappdata%\Microsoft\Olk\ containing the following text:
{
    "edgeDevTools":  "enabled"
}
2. Open new Outlook.
3. Press F12. Nothing.
4. (as per https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/one-outlook#debug-your-add-in): Sideload project onto the web.
5. Open cmd with admin rights
6. run olk.exe --devtools
7. New Outlook opens. No devtools.

## Context
It is impossible to clear browser cache and so every time an update is done to the addin it stops working for QA saying "Error: Failed to start platform. Reason: TypeError: Cannot read properties of undefined (reading 'dotnet.wasm') at Vt (blazor.webassembly.js:1:62226)"

**Comment by ajays-msft** [comment]
@XENOpz - Can you please try the command from powershell window?

**Comment by XENOpz** [comment]
> @XENOpz - Can you please try the command from powershell window?

I tried that just now. Dev tools did not appear.

**Comment by ajays-msft** [comment]
@XENOpz - Can you please delete the json file you added and try? That file is not required.

**Comment by XENOpz** [comment]
> @XENOpz - Can you please delete the json file you added and try? That file is not required.

Thank you, getting rid of the config file has made it work.

**Comment by MohamedMoussaTTW** [comment]
Why does this JSON file exist in the first place? It was blocking my devtools from working.
