### ISSUE TITLE
🐛 When an add-in wants to create a new workbook, the confirmation dialogue in Excel Online is completely empty

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#4057]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.17321.42305
* Operating System: Windows 11
* Browser (if using Office on the web): Edge

[Velixo internal issue tracker](
https://3.basecamp.com/3496385/buckets/16689259/card_tables/cards/6988991970)

## Steps to replicate

Request a new workbook creation from your add-in, e.g. using this ScriptLab sample.
https://gist.github.com/strangecamelcaselogin/e68e211d1b2d311385c0a80e40aea9e5
 
## Expected behavior

**No** confirmation dialogue ideally 😅
Or at least a normal confirmation dialogue!

## Current behavior

An empty confirmation dialogue with no text.

![image](https://github.com/OfficeDev/office-js/assets/5159662/f5a288e7-d28e-4d87-8369-43ff53d5140a)

![image](https://github.com/OfficeDev/office-js/assets/5159662/ebf44962-dbce-4da5-b0f9-198d9ae5246e)

## Context

The user starts crying and calling their mom because they don't understand what to do

**Comment by zhenhuangMSFT** [comment]
Sorry for the inconvenience this has caused. A fix is under deployment. Please expect it to be deployed in a few days.

**Comment by zhenhuangMSFT** [comment]
#4031 Similar issue here.

**Comment by wh1t3cAt1k** [comment]
![image](https://github.com/OfficeDev/office-js/assets/5159662/7ccd6fdb-0ae1-4bd2-b9ff-0b44b996fdfb)

It's fixed now - thank you!
