### ISSUE TITLE
Office Addin Not Isolated

### ISSUE THREAD

**Issue by deltreey** [OfficeDev/office-js#406]
## Expected Behavior
Doing actions in one Word document should NEVER affect another Word Document

## Current Behavior
When an addin scans a document for changes, it affects ALL open documents, including removing highlight and discarding your cursor even if you're working in an entirely different Word window (without the addin).

## Steps to Reproduce, or Live Example
<img src="https://imgur.com/gHUDWB7.gif"/>

Here I select and click highlight in one word document.  Holding down the highlight button in order to "time it perfectly" until the other word document's addin scans for changes.  When I release the highlight button after the scan, the OTHER document is highlighted--somewhere I didn't even click.

Note that my example addin scans the document every few seconds making this easy to reproduce.  I can provide code for a concise example Add-In that produces this issue, but I don't think it is necessary.  This is the key part of such code:

```
context.load(contentControls, 'tag,title');
    return context.sync().then(() => {
````

Notably, this does not appear to be an issue with Add-Ins specifically, but an issue with Word Isolation.  This is demonstrated by the functionality in this add-in, but it is probably in the core Office code.  That said, I had no idea where else to put this bug report, so here it is.

## Context
In the real world, we're producing an addin that needs to know when the document has changed and given the limited events, we have elected to scan tho document on an event loop (every 5 seconds) and this disorients and confuses the user in actual practice.

## Your Environment
* Platform Office 365
* Host Word
* Office version number: 1808 (Build 10730.20280 Click-to-Run)
* Operating System: Windows 10

**Comment by deltreey** [comment]
nearly a month.  Can I get a "we're looking into it" or something?

**Comment by deltreey** [comment]
just checking in...still an issue...seeing it perpetuate other problems now too...this sandboxing is kinda a big deal.

**Comment by JuaneloJuanelo** [comment]
sorry about the delay .... just to let you know in the next minutes we will provide an update i think i have seen this before.... stay tuned...

**Comment by JuaneloJuanelo** [comment]
ok @deltreey , after years of waiting (jk :) ) i have to say, i can NOT repro the issue. (not to mention sounds like an edge case, but we should also look into those 👍 )
I prepared a script lab [snippet for your so you c](https://gist.github.com/JuaneloJuanelo/9684a601fe515952a1b3e5b3cd5aebdd)an try it on your end. Btw if you are new to script lab go here: http://aka.ms/scriptlab


So please load it, run it, click setup (this will add 2 paragraphs with a content control ) then click "loop"...

that basically runs a loop reading the content controls in the document (as you suggested)... switch to a doc change formattings, what you expect happens. 

this is the code:

```
var cont = 0;
async function traverse() {
  await Word.run(async (context) => {
    for (let i = 0; i < 100; i++) {
      let ccs = context.document.body.contentControls;
      ccs.load();

      await context.sync();

      console.log(cont);
      cont++;

      await pause(300);
    }
  });
}

function pause(milliseconds) {
  return new Promise((resolve) => setTimeout(resolve, milliseconds));
}
```
please give it a try. let me know outcomes. also I recommend you to install the latest Office, can you share version number?

if the issue persists, please make sure to prepare me  script lab snippet so i can investigate further with the team, in the meatime i will tag this issue as "requires more info"

thanks and again, sorry about the delay...

**Comment by deltreey** [comment]
No, this is definitely still a problem @JuaneloJuanelo 
<img src="https://i.imgur.com/GL42Ii3.gif"/>

Here is an example of the code: https://github.com/deltreey/example-officejs-broken

This is most definitely reproducible.

**Comment by JuaneloJuanelo** [comment]
hello @deltreey  did you tried to repro the issue with the snippet i sent you?  do yo have a script lab snippet that repros the issue?

**Comment by deltreey** [comment]
The snippet you provided did not reproduce the issue.  I created a github repository with the full solution for you.  See the link above.

also, my gif provides the code for context

**Comment by JuaneloJuanelo** [comment]
yes and i think its effectively the same code (its constantly scanning the document for the content control collection) 
I am downloading your solution now, i am trying to scope the issue maybe this only happens when you are debugging a solution. Btw it will be preferable to have a script lab snippet reproing that way  is easier to share among the folks who are investigating this....

**Comment by deltreey** [comment]
the key difference is the `getOoxml()` call.  I don't know how to use scriptlab but I will look into it.

also, this is occuring in production for us.  it is certainly not a debugger issue.

**Comment by JuaneloJuanelo** [comment]
no worries i am restoring your script there... thanks  just stay tuned :)   i can repro when debugging in VS

**Comment by JuaneloJuanelo** [comment]
ok i have a repro!  scriptlab https://gist.github.com/JuaneloJuanelo/14ea55f09f80021aa29dfffd1ee7565f

we are investigating now, it seems is the OOMXL... tHANKS!!!!

tracking as a bug with code 3382332

**Comment by deltreey** [comment]
any word on progress here?

**Comment by JuaneloJuanelo** [comment]
This issue is now fixed. (Builds 16.0.12002.10000+)
