### ISSUE TITLE
Add-In Display Rendering Issue - Taskpane Add-in Double Offset Obscures Document in Word Online on iOS devices [iOS, Chrome]

### ISSUE THREAD

**Issue by aeturneus** [OfficeDev/office-js#4060]
# Provide required information needed to triage your issue

Opening a document in Word online with an add-in activated (e.g. in WOPI environment) causes a document rendering error. There is a display rendering issue in the document editor where the taskpane add-in is causing a wide, vertical, semi-transparent margin to appear across the document. This margin matches the width of the task pane and is obscuring the document, making the right portion of it unreadable. The margin starts from the top of the document and extends to the bottom, covering the majority of the editing space. It appears to be a z-index or overlay problem, where the presence of the add-in task pane is improperly influencing the layout of the document

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: iOS Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Current Office on the web
* Operating System: iOS
* Browser (if using Office on the web): Chrome
 
## Expected behavior

Expected the document to render using the full width of the document window, with the task pane alongside.

## Current behavior

The document does not render using the full width of the document window. It is obscured by a background margin on the right side that matches the width of the taskpane (appears to be a double offset issue, where the document is offset by twice the width of the add-in taskpane)

## Steps to reproduce

1. Open a document in office online in iOS Chrome on iPad
2. Enable the Divorcepath add-in
3. The document display should be obscured

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [x ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 
![IMG_0190](https://github.com/OfficeDev/office-js/assets/877362/5a1c72a6-05ac-4838-a518-43568b04282f)

**Comment by zhenhuangMSFT** [comment]
Hey @m-hellesen, could you take a look at this issue? Thanks!

**Comment by aeturneus** [comment]
@zhenhuangMSFT @m-hellesen issue seems to be resolved! Not able to reproduce this on the current builds.

**Comment by zhenhuangMSFT** [comment]
@aeturneus thanks for the update!
