### ISSUE TITLE
Excel Worksheet Change event doesnt get triggered in Web environment for Change in Data Validation Cells

### ISSUE THREAD

**Issue by harishbhaskaruni** [OfficeDev/office-js#4066]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______ Browser Environment - Chrome
* Host [Excel, Word, PowerPoint, etc.]: ______ Exce;
* Office version number: ______Online Excel (offcie.com)
* Operating System: ______ Windows
* Browser (if using Office on the web): ______Chrome
 
## Expected behavior
Excel Worksheet Change event should get triggered in Web environment for Change in Data Validation Cells

## Current behavior
Excel Worksheet Change event doesnt get triggered in Web environment for Change in Data Validation Cells

## Steps to reproduce

1. Create Data validation rule pointing the list to a range of cells say Test1, Test2, Test3 as values
2. Write a worksheet change handler
3. Change the value from Test1 to Test2 in the drodown for data validation cell
4. Worksheet change handler doesn't get called

## Link to live example(s)
[DataVlidation-WorksheetChangeEvent.txt](https://github.com/OfficeDev/office-js/files/14094207/DataVlidation-WorksheetChangeEvent.txt)

# Provide additional details

1. Attached code contains two buttons - 1. Create Data validation range which 
2. creates data validation list at B1 pointing the values of A1: A6
3. Second button "Register on change handler " registers the worksheet change handler 
4. Click the second button to register the sheet change handler
5. Change any cell value and observe that the cell changed address is printed in the console
6. CHange the dropdown value of B1 say from Test2 to Test3 or so and observe that the sheet change event doesnt get triggered and no information gets printed in the console.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by zhenhuangMSFT** [comment]
Hi @harishbhaskaruni, thanks for reporting the issue! We are actually aware of the issue and it is in our backlog. We will try to fix it  ASAP. Thanks for your understanding.

**Comment by jipyua** [comment]
hi @harishbhaskaruni thanks for reporting this issue and your patience. Now the bug should have been fixed and deployed, as long as with Excel online version >= 16.0.17706.42307, you should be able to try the latest fix. Please feel free to close this case or let us know other feedbacks. Thanks.
