### ISSUE TITLE
getTrackedChanges for Range object scrolls the page back and forth on every call 

### ISSUE THREAD

**Issue by isadovskiy-numatic** [OfficeDev/office-js#4067]
Calling `range.getTrackedChanges().load()` several times in a raw makes the page scrolled down to the location of the tracked changes and then back to the cursor position.

## Your Environment
* Platform: PC desktop
* Host: Word
* Office version number: Version 2312 Build 16.0.17126.20132 64-bit 
* Operating System: Windows 11 Pro

## Current behavior
Every time `range.getTrackedChanges().load()` is executed, it scrolls the page down to location of the given range and then scrolls back to the location of the cursor. 

## Expected behavior
When calling `range.getTrackedChanges().load()`, it should allow to obtain the tracked changes object without scrolling the page to the location of the given range. Page should not become blocked with scrolling. 

## Steps to reproduce
1. Obtain multiple ranges, contained tracked changes.
2. Execute `range.getTrackedChanges().load()` for each range in a cycle to obtain them all
3. Execute `context.sync()`
4. Observe the behavior: page is scrolled back and forth, down to every place, contained tracked changes.

# Provide additional details
````
                const paragraphs = context.document.body.paragraphs.load(['text']);
                await context.sync();

                paragraphs.items.forEach((paragraph) => {
                    paragraph.getTrackedChanges().load(['type']);
                });
                await context.sync();
````

## Context
This is actually a big problem. I have a list of ranges and need to obtain tracked changes for each one. As a result, while obtaining tracking changes, page is completely blocked for several seconds; it scrolling and flickering all the time, which makes this API completely unusable.

**Comment by isadovskiy-numatic** [comment]
Here is the video recording illustrated the problem (video starts from 5th second).

https://github.com/OfficeDev/office-js/assets/132096855/543a2367-e543-40c9-816b-8fdf5f893665

**Comment by jipyua** [comment]
Thank you @isadovskiy-numatic for reporting this issue. This is a known one for us and it's currenlty tracked by interal bug 8372078. We will give some update when we have some progress.

**Comment by shqyking** [comment]
Come across the same problem here. What's more, when I open document **A**, and call getTrackedChanges on document **B**(document B is created using context.application.createDocument), it also scrolls on document **A**. What even surprises me is that, the tracked changes in **document B** show up in **document A**!

I don't know if this is a known issue for you. If not, I can file a separate bug.

**Comment by greysteil** [comment]
I'm experiencing this too (`getTrackedChanges().load(..)` scrolling the page). It makes `getTrackedChanges` impossible to use whilst the maintaining a high quality user experience - hopefully there's an easy fix? 🤞

(I'd like to use `getTrackedChanges()` to get the range for a tracked change. There's no other way to do this (using `search` doesn't work if the user has configured their visible text not to show tracked changes.)

**Comment by jipyua** [comment]
hi @isadovskiy-numatic @shqyking @greysteil thanks for reporting this case, together with case https://github.com/OfficeDev/office-js/issues/3691, the issue has been fixed and rolled out, please update to the latest M365 version of Office and have a try. And also feel free to close this case if confirmed. @shqyking please file a separate bug if you are seeing other unexpected behavior. Thanks.

**Comment by greysteil** [comment]
Confirming this is fixed on M365 on both Mac and PC. Thanks @jipyua! Looking forward to using `getTrackedChanges`!
