### ISSUE TITLE
Outlook desktop app consistently disconnects from Exchange within a minute after office add-in is opened

### ISSUE THREAD

**Issue by junhuiluosalesforce** [OfficeDev/office-js#4068]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop______
* Host [Excel, Word, PowerPoint, etc.]: _Outlook_____
* Office version number: __Version 2310 (Build 16924.20150), Version 2312 (Build 17126.20132 Click-to-Run), Version 2401 (Build 17231.20182)____
* Operating System: __Windows 10 64 bit____
* Browser (if using Office on the web): _NA. Issue does not occur with Office on the web or with "Outlook for Windows" (the "Try the new Outlook" experience) on the same computers____
 We also confirmed that impacted Outlook desktop app uses Webview2 to render the office add-in.

## Expected behavior

Outlook desktop app and office add-in running in Outlook should stay connected with Office365

## Current behavior

Once the user opens the Salesforce (Outlook integration office add-in https://appsource.microsoft.com/en-us/product/office/WA104379334?src=office), within a minute Outlook desktop app *and* the office add-in both disconnect from Office 365, as seen in the Outlook main window status bar at the bottom of the Outlook window.
If the office add-in is not opened, Outlook desktop app stays connected to Office365.

## Steps to reproduce

1. _The issue is only reported by one of our (Salesforce's) customers. This customer can consistently reproduce the issue. We (Salesforce) cannot. This Salesforce customer opened a support case 2312140040005873 with Microsoft Support and Microsoft Support concluded that the issue is with the following log entry captured in Fiddler logs:
2. <?xml version="1.0"?>
<q:Envelope xmlns:ex12t="http://schemas.microsoft.com/exchange/services/2006/types"
xmlns:ex12m="http://schemas.microsoft.com/exchange/services/2006/messages"
xmlns:q="http://schemas.xmlsoap.org/soap/envelope/">
<q:Header>
<ex12t:RequestServerVersion Version="V2016_12_27"></ex12t:RequestServerVersion>
</q:Header>
<q:Body>
<ex12m:GetAppMarketplaceUrl>
<ex12m:ApiVersionSupported>1.13</ex12m:ApiVersionSupported>
<ex12m:SchemaVersionSupported>1.1</ex12m:SchemaVersionSupported>
</ex12m:GetAppMarketplaceUrl>
</q:Body>
</q:Envelope>
<?xml version="1.0" encoding="utf-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
<s:Body>
<s:Fault>
<faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">
a:ErrorAccessDenied</faultcode>
<faultstring xml:lang="en-US">The requested web method is unavailable to this caller or
application.</faultstring>
<detail>
<e:ResponseCode xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">
ErrorAccessDenied</e:ResponseCode>
<e:Message xmlns:e="http://schemas.microsoft.com/exchange/services/2006/errors">The
requested web method is unavailable to this caller or application.</e:Message>
</detail>
</s:Fault>
</s:Body>
</s:Envelope>

Microsoft Support said (in support case 2312140040005873) "Note: GetAppMarketPlaceUrl error is specific to add-in while connecting with that perticular add-in. The EWS is working fine as per the remote connectivity logs and fiddlers.".  But Salesforce code in the office add-in does not call GetAppMarketplaceUrl and it appears the call is made from the office.js framework and we do not know how to address the issue. Also Outlook app status bar clearly shows it is disconnected from Exchange.
<img width="2159" alt="Screenshot 2024-01-30 at 10 59 25 PM" src="https://github.com/OfficeDev/office-js/assets/124451278/8d5ed726-97d0-4f60-a478-62954da8ce1c">
3. 
4. _____
5. ______
6. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ X ] Screenshots: I am attaching a screenshot that shows Outlook desktop app itself would disconnect, within a minute, once the office add-in is opened.
- [ ] Test file (if only happens on a particular file)
Can you please retrieve the logs from Microsoft support case 2312140040005873 to see additional context? It is inaccessible to us.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by junhuiluosalesforce** [comment]
For context, I notice another reported issue here https://github.com/OfficeDev/office-js/issues/3178 also mentions calls to GetAppMarketplaceUrl.

**Comment by avisheknand** [comment]
I am not sure if this will solve the issue. We have encountered this before with COM-Addins , where Outlook gets disconnected. From our diagnosis, we encountered that Outlook Addin Viva insight was conflicting with the COM addin. Check if Viva insight is enabled inside outlook , try to remove and test if the SalesForce app works

**Comment by junhuiluosalesforce** [comment]
@avisheknand Thanks. The user does not have any other add-ins, including Viva insights.

**Comment by millerds** [comment]
When you say not any other add-ins does that include COM addins?

**Comment by junhuiluosalesforce** [comment]
@millerds Thank you very much for the clue. We were able to identify which COM based add-in was in conflict.

**Comment by junhuiluosalesforce** [comment]
Some COM based office add-in was causing this behavior.
