### ISSUE TITLE
Which Event trigeer while merge/unmerging cell/Row/column in excel officejs.

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#4069]
My Environment
Platform : PC desktop
Host: Excel
Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2309 Build 16.0.16827.20166) 64-bit
Operating System: Windows 10 pro

Hi Team,
Is there any event which is trigger when row/column/cell will merge/unmerge

I try onChange event but I didn't get any thing about merge/unmerge its return only "RangeEdited" as eventType.

**Comment by zhenhuangMSFT** [comment]
Hi @Jayshiv1408Dev, I suggest you asking questions on Stackoverflow tagged office-js where we have a lot of active developers willing to help.

**Comment by nikitamittal2501** [comment]
Hi @Jayshiv1408Dev 
Please raise your questions here: https://stackoverflow.com/questions/tagged/office-js. Thank you.

**Comment by Jayshiv-IRIS** [comment]
Hi team,
I already Raised my concern on stackoverflow , but I didn't get any response. Because of merge and unmerge problem I'm stuck.
Can you please provide me some guidance on this or any alternative solution for this. 
[My Ticket](https://stackoverflow.com/questions/77924803/which-event-trigeer-while-merge-unmerging-cell-row-column-in-excel-officejs)
