### ISSUE TITLE
adding Comment changes formatting

### ISSUE THREAD

**Issue by gajal123** [OfficeDev/office-js#407]
I have created a word addin for data annotation. It allows the customer to select a piece of data and enter a comment in the addin input box. It basically uses Javascript to add comments.xml package part, relationship and the comment reference in the word xml. Finally when i do setSelectedDataAsync, the comment adds fine but the numbering of elements changes.

The cause seems to be the pPr numPr which changes from 2 to 4 on running the setSelectedDataAsync function

    Office.context.document.setSelectedDataAsync(ooxml, { coercionType: Office.CoercionType.Ooxml }, function (asyncResult) {
                    if (asyncResult.status === "failed") {
                        showNotification("Action failed with error: " + asyncResult.error.message);
                    }
                });

The ooxml is fine and contains accurate pPr. The change happens after running this piece of code.

**Comment by JuaneloJuanelo** [comment]
@gajal123  can you please send us a code snippet to repro your issue? please use script lab (http://aka.ms/scriptlab
) for it. thanks!

**Comment by JuaneloJuanelo** [comment]
please follow this example to insert comments without corrupting your doc
https://gist.github.com/JuaneloJuanelo/4a704dd6f23f2523ffac4f97c89d05c0
