### ISSUE TITLE
Excel Addin custom function returns messy Chinese characters

### ISSUE THREAD

**Issue by LongyanWu** [OfficeDev/office-js#4070]
I am writing a excel add-in which includes several custom functions. The custom function fetch data from web API, and return an array with Chinese characters. However excel displays the result with messy characters.

The result from Web API is utf-8(which is correct), but the excel custom function seems decode the result as ascii.
![image](https://github.com/OfficeDev/office-js/assets/43000369/ba276b43-95b0-459f-972b-794080c6d431)

I appreciate it if anyone can provide some information.

**Comment by MiaofeiWang** [comment]
Hi @LongyanWu , with a simple web API, I am able to show Chinese characters returned by custom function correctly. Could you share the JS script of your function and the response object in debugger (https://learn.microsoft.com/en-us/office/dev/add-ins/testing/debug-with-vs-extension)? 

![CustomFunctionReturnChineseCharacters](https://github.com/OfficeDev/office-js/assets/28795134/a69b9683-bad8-4b24-8b28-88593f628500)

**Comment by LongyanWu** [comment]
[ChineseCharactorsVerify.zip](https://github.com/OfficeDev/office-js/files/14229594/ChineseCharactorsVerify.zip)

Attach zip file. It's created with command yo office, (custom functions with Shared Runtime). 

2 functions are added to functions.js
1. ChineseTexts  --- this one is working
2. Provinces --- this one fetch result from a web api, it's stuck.
<img width="370" alt="image" src="https://github.com/OfficeDev/office-js/assets/43000369/f28a4bc0-b59b-474d-b2f8-f4f425c91a4a">

In my project, custom function like#2 works, but returns messy characters.

**Comment by MiaofeiWang** [comment]
@LongyanWu Thanks for the code. The stuck seems to because CORS policy. After bypassing the CORS, I was able to get correct result with Chinese characters. 

<img width="381" alt="image" src="https://github.com/OfficeDev/office-js/assets/28795134/caaad2e0-e3a7-42fa-aad7-8cbfa3e21aaf">

Can you try again after bypassing the CORS policy (for example, using `cors` middleware in your code)?
