### ISSUE TITLE
Unhandled Promise rejection: 

### ISSUE THREAD

**Issue by Athinarapu-Akhila** [OfficeDev/office-js#4072]
![image](https://github.com/OfficeDev/office-js/assets/72911360/469584d7-ec35-4d4f-9d89-43891f5255e3)
I am getting this error in polyfills.js script file when clicking on each section (In word Doc Office-Addin) 
Can somebody help me to reproduce this error?

**Comment by nikitamittal2501** [comment]
Hi @Athinarapu-Akhila 
Can you please share the repro steps and the version where you are seeing this issue?

**Comment by Athinarapu-Akhila** [comment]
Firstly we store the word files in box.. If the user wants to make changes, they will launch this file through MS word. In the file we have different types of sections(tables, charts, ..In order to make the changes, when user clicking on inside the section i am getting this error.  Do u mean office version?

**Comment by nikitamittal2501** [comment]
Can you please share the following details - 
Platform: 
Office version number: 
Operating System:
