### ISSUE TITLE
Add-in task pane not opening in Outlook on the web

### ISSUE THREAD

**Issue by SimonDania** [OfficeDev/office-js#4075]
# Provide required information needed to triage your issue
When clicking our add-in in Outlook on the web, the task pane doesn't open anymore.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome
 
## Expected behavior

The task pane should open.

## Current behavior

We open a new mail and click the button for the add-in, but the task pane does not show up.
It works fine in the Outlook Client and in New Outlook.

## Context

This affects all of our customers.
We didn't change anything in our code or manifest, and it just randomly stopped working.

**Comment by rajjha-msft** [comment]
Hey @SimonDania 

- Can you attach a repro video with the console open?
- Also, please share the network logs over here: OutlookExtensibility@M365x53858506.onmicrosoft.com ?
- Is this s consistent repro, or happens sometimes?

**Comment by xmuntane** [comment]
Hi @SimonDania 

I’m running into the same issue you mentioned. Did you manage to figure it out? If you have any tips or a solution, that would be super helpful!

Thanks a lot!

**Comment by SimonDania** [comment]
Hi @xmuntane 
We fixed it by doing a minor change to the manifest file.
We changed "CustomTab" --> "OfficeTab"

**Comment by mobisw-msft** [comment]
Closing this issue since this has been fixed for @SimonDania . @xmuntane - please open a new Github issue if you're facing difficulties with Outlook add-ins.

**Comment by mobisw-msft** [comment]
@xmuntane  - please open a new Github issue if you're facing difficulties with Outlook add-ins.
