### ISSUE TITLE
Outlook Add-in pinning feature does not work on Outlook Web and Outlook for Windows (latest version)

### ISSUE THREAD

**Issue by Vignesh-02** [OfficeDev/office-js#4077]
Outlook pinning feature does not work on Outlook Web and Outlook for Windows (latest version)

# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___PC, Office on the Web___
* Host [Excel, Word, PowerPoint, etc.]: ____Outlook__
* Office version number: __20240119003.13 Client Version____
* Operating System: ___Windows___
* Browser (if using Office on the web): __Chrome (on Mac)____
 
## Expected behavior

I wanted to pin my custom-add in on Outlook on web and on the latest version of Outlook on Windows. I am able to pin my add-in on Outlook For Mac(latest version) and Outloon on Windows (version 2401). I am using my vigu1401@outlook.com account which has a Microsoft 365 subscription.

## Current behavior
I am not able to pin my add-in even when I have added the <SupportsPinning>true<SupportsPinning> tag in the manifest.xml file

## Steps to reproduce

For a store add-in named Priority Matrix too, I was not able to pin the add-in on Outlook on the web.
![Screenshot 2024-02-01 at 3 50 22 PM](https://github.com/OfficeDev/office-js/assets/63554046/cba9d1ac-19af-41f6-aa4e-ca17d3eaf0e0)
![Screenshot 2024-02-01 at 3 50 44 PM](https://github.com/OfficeDev/office-js/assets/63554046/c0d4f784-f858-40ff-ab2a-217fc4fd21b8)
![Screenshot 2024-02-01 at 3 50 50 PM](https://github.com/OfficeDev/office-js/assets/63554046/08225775-424b-4ccf-8701-1cc6329e95af)

1. ______
2. ______
3. ______

## Link to live example(s)

Manifest.xml 
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0" xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xsi:type="MailApp">
  <Id>86c64e2e-8665-4684-9d25-98c9287e283d</Id>
  <Version>1.1</Version>
  <ProviderName>Contoso</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Wise Sales"/>
  <Description DefaultValue="A template to get started."/>
  <IconUrl DefaultValue="https://outlook-addin-v9y9.onrender.com/assets/icon-64.png"/>
  <HighResolutionIconUrl DefaultValue="https://outlook-addin-v9y9.onrender.com/assets/icon-128.png"/>
  <SupportUrl DefaultValue="https://www.contoso.com/help"/>
  <AppDomains>
    <AppDomain>https://outlook-addin-v9y9.onrender.com</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Mailbox"/>
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.3"/>
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://outlook-addin-v9y9.onrender.com/taskpane.html"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
  <Permissions>ReadWriteItem</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"/>
  </Rule>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
        <Requirements>
            <bt:Sets DefaultMinVersion="1.13">
              <bt:Set Name="Mailbox"/>
            </bt:Sets>
        </Requirements>
        <Hosts>
            <Host xsi:type="MailHost">
                <DesktopFormFactor>

                <ExtensionPoint xsi:type="MessageComposeCommandSurface">
              <OfficeTab id="TabDefault">
                <Group id="msgComposeGroup">
                  <Label resid="GroupLabel"/>
                  <Control xsi:type="Button" id="msgComposeOpenPaneButton">
                    <Label resid="TaskpaneButton.Label"/>
                    <Supertip>
                      <Title resid="TaskpaneButton.Label"/>
                      <Description resid="TaskpaneButton.Tooltip"/>
                    </Supertip>
                    <Icon>
                      <bt:Image size="16" resid="Icon.16x16"/>
                      <bt:Image size="32" resid="Icon.32x32"/>
                      <bt:Image size="80" resid="Icon.80x80"/>
                    </Icon>
                    <Action xsi:type="ShowTaskpane">
                      <SourceLocation resid="Taskpane.Url"/>
                    </Action>
                  </Control>
                </Group>
              </OfficeTab>
           </ExtensionPoint>
                    
                    <ExtensionPoint xsi:type="MessageReadCommandSurface">
                        <OfficeTab id="TabDefault">
                            <Group id="msgReadGroup">
                                <Label resid="GroupLabel"/>
                                <Control xsi:type="Button" id="msgReadOpenPaneButton">
                                    <Label resid="TaskpaneButton.Label"/>
                                    <Supertip>
                                        <Title resid="TaskpaneButton.Label"/>
                                        <Description resid="TaskpaneButton.Tooltip"/>
                                    </Supertip>
                                    <Icon>
                                        <bt:Image size="16" resid="Icon.16x16"/>
                                        <bt:Image size="32" resid="Icon.32x32"/>
                                        <bt:Image size="80" resid="Icon.80x80"/>
                                    </Icon>
                                    <Action xsi:type="ShowTaskpane">
                                        <SourceLocation resid="Taskpane.Url"/>
                                            <SupportsPinning>true</SupportsPinning>
                                            
                                            

                                        
                                    </Action>
                                </Control>
                            </Group>
                        </OfficeTab>
                    </ExtensionPoint>

            
                </DesktopFormFactor>
            </Host>
        </Hosts>
<Resources>
        <bt:Images>
          <bt:Image id="Icon.16x16" DefaultValue="https://outlook-addin-v9y9.onrender.com/assets/icon-16.png"/>
          <bt:Image id="Icon.32x32" DefaultValue="https://outlook-addin-v9y9.onrender.com/assets/icon-32.png"/>
          <bt:Image id="Icon.80x80" DefaultValue="https://outlook-addin-v9y9.onrender.com/assets/icon-80.png"/>
        </bt:Images>
        <bt:Urls>
          <bt:Url id="Commands.Url" DefaultValue="https://outlook-addin-v9y9.onrender.com/commands.html"/>
          <bt:Url id="Taskpane.Url" DefaultValue="https://outlook-addin-v9y9.onrender.com/taskpane.html"/>
        </bt:Urls>
        <bt:ShortStrings>
          <bt:String id="GroupLabel" DefaultValue="Contoso Add-in"/>
          <bt:String id="TaskpaneButton.Label" DefaultValue="Show Taskpane"/>
        </bt:ShortStrings>
        <bt:LongStrings>
          <bt:String id="TaskpaneButton.Tooltip" DefaultValue="Opens a task pane."/>
          <bt:String id="ActionButton.Tooltip" DefaultValue="Perform an action when clicked."/>
        </bt:LongStrings>
      </Resources>
    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>`
1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Vignesh-02** [comment]
Link to the manifest.xml file https://outlook-addin-v9y9.onrender.com/manifest.xml

**Comment by rajjha-msft** [comment]
Hey @Vignesh-02 

Thanks for reporting this issue regarding the pinning feature. It has been put on our backlog. We unfortunately have no timelines to share at this point.
Internal tracking Id: 254479

**Comment by ajays-msft** [comment]
Thank you for the input. This is a new feature request.
We track Outlook add-in feature requests on our[Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
