### ISSUE TITLE
URGENT NEED for an API to insert comments into Word documents fast. 

### ISSUE THREAD

**Issue by LeszekNie** [OfficeDev/office-js#408]
## Expected Behavior
To be able to insert comments fast and easily by means of an API.

## Current Behavior
Currently, the only way to add comments to a Word document is by manipulating the OOXML structure. It works, but it is so painfully slow in Word Online that it gives a really bad user experience. Each OOXML change leads to the dialog “Loading...” staying on screen for at least 7 seconds. In comparison, it takes less than 2 seconds to insert a comment in the Word desktop application.

## Context
This is a **BLOCKER** for us. Our product Is about saving teachers time when they give feedback. If it takes almost 10 seconds to insert a comment from an add-in in Word Online, there is no longer a benefit to have premade comments, as it takes the same amount of time to write one from scratch. More and more of our customers require that our feedback tools support Word Online, but we can’t offer them the add-in before comment insertion is at least as fast in Word Online as in the Word desktop application.

## Your Environment

* Platform: Office Online
* Host: Word
* Operating System: Win/macOS
* Browser (if using Office Online): Google Chrome

**Comment by JuaneloJuanelo** [comment]
yes unfortunately on Word Online OOXML insertion is slow. Comments in Word is a known gap on the API and already on our backlog.

**Comment by ECoS-AppDev** [comment]
Is there any update on this feature?

**Comment by tutieu** [comment]
Sorry, there is no new update on this.  However, it is still on our active backlog at this time.

**Comment by wbecker** [comment]
6 months later - is there any update here?

**Comment by lizhecome** [comment]
1 year later - is there any update here?

**Comment by RuoyingLiang** [comment]
@lizhecome Thanks for the patient. We are working on the solution. Will update this thread once it's published.

**Comment by alexuribarri** [comment]
Is this closed because resolved and there's an easy way to add comments via API?

**Comment by RuoyingLiang** [comment]
The comments API just been released to beta in Word Online. The document will be updated in these days. Will update with the doc link after it's published.

**Comment by RuoyingLiang** [comment]
The comment API document [https://docs.microsoft.com/en-us/javascript/api/word/word.comment?branch=master&view=word-js-preview](url) . Welcome to try and share your feedback.
