### ISSUE TITLE
Addin button is not working in Outlook calendar web version and working fine in the app

### ISSUE THREAD

**Issue by adithyasai** [OfficeDev/office-js#4081]
The Addin button in the Outlook calendar web version is currently non-functional, despite its proper functionality until January 23, 2024. It's worth noting that there have been no modifications to the underlying codebase, and no deployments have taken place during this period. Interestingly, the same button operates seamlessly in the Outlook app.

In the provided image, the non-functional web version displays the Addin button as a dropdown menu, while the app version showcases a conventional, fully operational button. The discrepancy in appearance is noticeable, with the web version presenting an issue in contrast to the smooth functionality observed in the app.

**this is a critical issue as this is happening in Production environment for the customer**

## Your Environment

* Platform : Web outlook
* Host outlook 
* Office version number: 1.0.282
* Operating System: Windows
* Browser (if using Office on the web): Edge and chrome
 
## Expected behavior
It should be a button and should open a scheduling assistant on click

## Current behavior
its showing as a dropdown menu and no response on click

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by rajjha-msft** [comment]
Hey @adithyasai 

We are not able to repro the issue on our local environment. 

- Can you please share the network logs over here: [OutlookExtensibility@M365x53858506.onmicrosoft.com](mailto:OutlookExtensibility@M365x53858506.onmicrosoft.com)?
- If possible, please share a sample manifest which can be used to repro the issue.

**Comment by adithyasai** [comment]
hey @rajjha-msft i have shared it on email

**Comment by ajays-msft** [comment]
@adithyasai - I don't see the images attached in the gh issue. Are you talking about discrepancies between outlook web and outlook desktop? Is it not at all working, or it is a change in UX that you are observing?

**Comment by adithyasai** [comment]
hey @ajays-msft this is fixed now. we can close it
