### ISSUE TITLE
mailbox.item.internetHeaders is undefined

### ISSUE THREAD

**Issue by rbsdc** [OfficeDev/office-js#4084]
# Provide required information needed to triage your issue
When sending a teams appointment, then mailbox.item.internetHeaders is undefined in Compose mode. This is missing in the documentation. Or is it a bug?

## Your Environment

host: Outlook
version: 16.0.16626.20170
platform: PC

**Comment by millerds** [comment]
Can you explain what you are doing when "sending a teams appointment"?  Is this using Outlook or is this using Teams?

**Comment by millerds** [comment]
In order to help you we need to understand more details about what you are attempting to do.

**Comment by rbsdc** [comment]
Steps to reproduce:

- In the Outlook-Mail Web-Version (outlook.live.com) click on Calender
- Add a new Event
- Invite a person
- Click on  send

=> mailbox.item.internetHeaders is undefined

**Comment by millerds** [comment]
@rbsdc so is this only a problem online?

**Comment by rolait** [comment]
@millerds I did not test it in the client version, but since addons rely on the same office library the problem might also exist there.

**Comment by millerds** [comment]
The way the apis are handled are different between Win32 and OWA.  I will ask someone from OWA to help here.

**Comment by DivyaPatidar** [comment]
@rbsdc As mentioned in [docs](https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#outlook-office-messagecompose-internetheaders-member:~:text=%3A%20read%20item-,Applicable%20Outlook%20mode%3A%20Message%20Compose,-Important%3A%20The%20internet) internetHeaders is only supported for Message Compose mode and not in Appointment Organizer mode.

**Comment by rbsdc** [comment]
@DivyaPatidar Thank you for the answer! I am using the "MessageCompose" extension point in the manifest. Furthermore, I have an "Events" Extension point with an Event of the type "ItemSend".  This event was also triggered when sending an appointment, hence the error. In my manifest or else where I never explicitly mention the "Appointment Organizer" mode, which is why this was a bit confusing. Anyway, in the event handler I am now checking if it is an appointment item. If yes, I am skipping the handler.  Thank you again.

**Comment by DivyaPatidar** [comment]
@rbsdc You can also check [smart alerts](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=classic#:~:text=Smart%20Alerts%20is,feature%20as%20follows%3A) instead of ItemSend event, if you are developing a new add-in.

**Comment by rbsdc** [comment]
@DivyaPatidar thank you for the further hint! I tried smart alerts, but switched back to events, because there were problems with the TypeScript-integration (it did not work with smart alerts).
