### ISSUE TITLE
On-Send web addin does not load on new outlook when email is sent to group

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4085]
**Description -** 
On-Send web addin does not load on new outlook when email is sent to group

**Steps to Reproduce -** 

1. Open New Outlook.
2. On left pane, Select Groups from options.
3. Select any group. It will open group information panel.
4. Click on Send Mail button.
5. Compose the mail and click on Send button.

**Expected Result -** 

1. On-Send web addin should get loaded upon clicking on Send button.

**Actual Result -** 

1. On-Send web addin does not load even though send action is triggered.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: New Outlook
* Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
* Operating System: Windows11
* Browser (if using Office on the web): NA
 
## Link to live example(s)
[Group_Send_Mail.zip](https://github.com/OfficeDev/office-js/files/14135212/Group_Send_Mail.zip)

**Comment by rajjha-msft** [comment]
Thanks for reporting this issue regarding the Smart alerts feature. It has been put on our backlog. We unfortunately have no timelines to share at this point.
Internal tracking Id: 254540.

**Comment by sagar-sonawane9** [comment]
Please confirm above comment is applicable for On Send web add-in as well.

**Comment by rajjha-msft** [comment]
The issue is fixed and deployed from our end. Please reach out if the issue is still reproducible.
