### ISSUE TITLE
Unable to open another mailbox using owa

### ISSUE THREAD

**Issue by Medha-lab** [OfficeDev/office-js#4087]
**Issue Description-** 
Unable to open another mailbox using owa

**Steps To Reproduce -**
1. Login to outlook.com
2. Then click on profile and then click on open another mailbox
3. ![image-2024-01-09-12-33-06-598](https://github.com/OfficeDev/office-js/assets/158465158/e140be47-ed23-4702-a08f-a15fab71f2da)
4. Once click on Open another mailbox, provide details of new mailbox.

**Actual Result -**
Then getting below error and unable to open another mailbox
![image-2024-01-09-12-33-13-659](https://github.com/OfficeDev/office-js/assets/158465158/eefabe5f-2eef-4c0b-8abd-8b82377a1caf)

**Expected Result -**
Should able to open another mailbox.

Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: New outlook
* Office version number: You have Microsoft Outlook Version 1.2024.124.100 (Production). Client Version is 20240119003.16 .
* Operating System: win 11
* Browser: Chrome, Edge , Firefox

**Link to live example(s)**
[Owa_OpenAnotherMailbox.zip](https://github.com/OfficeDev/office-js/files/14135546/Owa_OpenAnotherMailbox.zip)

**Comment by ajays-msft** [comment]
@Medha-lab - This is not add-in related issue.  Please refer to this article for guidance and further follow-ups. 

https://support.microsoft.com/en-us/office/access-another-person-s-mailbox-a909ad30-e413-40b5-a487-0ea70b763081
