### ISSUE TITLE
Inconsistently Observed boxes for multiple icons and button on new outlook

### ISSUE THREAD

**Issue by Medha-lab** [OfficeDev/office-js#4088]
**Issue Description-**
Inconsistently Observed boxes for multiple icons and button on new outlook

**Steps To Reproduce -**
1. Launch new outlook.
2. Compose new event

**Actual Result -**
Inconsistently Observed boxes for multiple icons and button on  new outlook

**Expected Result** -
Should not get boxes for multiple icons and button on new outlook

**Environment**
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: New outlook
* Office version number: You have Microsoft Outlook Version 1.2024.124.100 (Production). Client Version is 20240119003.16 .
* Operating System: win 11
* Browser - N/A

**Link to live example(s)**
https://github.com/OfficeDev/office-js/assets/158465158/5dd291a8-8c0a-4702-a680-134fc9cd402c

**Comment by rajjha-msft** [comment]
Hey @Medha-lab 

Is the issue consistently happening, or happened once?

**Comment by Medha-lab** [comment]
> Hey @Medha-lab
> 
> Is the issue consistently happening, or happened once?

@rajjha-msft 
This is not consistent and no specific steps but observed many times , 3/10 times.

**Comment by ajays-msft** [comment]
@Medha-lab - Thank you for your feedback, but this forum is limited to answering issues related to office.js.

If you have any specific feedback about Outlook app itself, please feel free to use the Help-Feedback option and provide the feedback.
