### ISSUE TITLE
ContentControl creation failing silently in Word Online

### ISSUE THREAD

**Issue by lightman76** [OfficeDev/office-js#409]
## Expected Behavior

With the snippet of code provided in gist linked below, I expect a page break to be added to the end of the document, the "Works Cited" title paragraph to be added below that, and then a ContentControl to be added below that, and finally another paragraph below the content control.

## Current Behavior

The code works fine in desktop Word (Office 365) on Mac.  In Word Online however, after it appends the "Works Cited" paragraph, nothing else happens to the document, even though the code executes without throwing any errors and the sync then callback fires as if everything worked.

## Steps to Reproduce, or Live Example

* Link to live example: https://gist.github.com/lightman76/d2a745fd3ac2ccfa683c76f7f5aca015#file-content-control-creation-failure-yaml
Create a new document in Word Online and load the above Gist into Script Lab, run it and click the Run button

## Context

My company has a tool which helps students with research and writing, part of which includes keeping their Works Cited/Bibliography up to date.  We create the works cited page and use a ContentControl for the actual contents of the bibliography so we can track where that content is and to lock it down so users don't accidentally make changes there that get overwritten when we update the bibliography when they've added or removed a source.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: ______
* Operating System: OSX 10.14.3
* Browser (if using Office Online): Chrome 72.0.3626.109

## Useful logs

- [ ] Console errors
  - The console only shows the "Sync Completed" method as if the sync had run without issue.  No errors are given

**Comment by JingjingHan123** [comment]
I tried your code on Word Online and found two issues: 
1. Cannot insert content control. 
2. Cannot change the place holder text of the context control.

For #1, it is a known issue when inserting the content control **after** the **last** paragraph. You can update the code as below to make it works on all platforms.
```
...
var pageTitleParagraph = endOfBodyRange.insertParagraph('Works Cited', Word.InsertLocation.after);
pageTitleParagraph.alignment = Word.Alignment.centered;

// ++++++++Insert an empty paragraph at end of the document+++++++++
endOfBodyRange = doc.body.getRange(Word.RangeLocation.end);
var emptyParagraph = endOfBodyRange.insertParagraph('', Word.InsertLocation.after);

var bibRange = pageTitleParagraph.getRange(Word.RangeLocation.after);
var bibContentControl = bibRange.insertContentControl();
...
```

For #2, it is not allowed on Word Online. You will get below error message.
message: "The action isn’t supported in Word Online. Check the OfficeExtension.Error.debugInfo for more information."

**Comment by lightman76** [comment]
Thank you for that work around!  That got me going again.
