### ISSUE TITLE
On-Send web addin does not load on new outlook when email is sent with 'Do Not Forward' option.

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4090]
**Description -**
On-Send web addin does not load on new outlook when email is sent with 'Do Not Forward' option.

**Steps to Reproduce -**

1. Open New Outlook.
2. Click on New Mail.
3. Compose the mail.
4. Go to Options, Select Do Not Forward option.
5. Click on Send button.

**Expected Result -**
1. On-Send web addin should get loaded upon clicking on Send button.

**Actual Result -**
1. On-Send web addin does not load even though send action is triggered.

**Your Environment**
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Link to live example(s)**
[Do_Not_Forward_Email.zip](https://github.com/OfficeDev/office-js/files/14136005/Do_Not_Forward_Email.zip)

**Comment by samantharamon** [comment]
Thanks for reporting this, @Sagar-lab1.

@exextoc could you please investigate this?

**Comment by rajjha-msft** [comment]
Thanks for reporting this issue regarding the Smart alerts feature. It has been put on our backlog. We unfortunately have no timelines to share at this point.
Internal tracking Id: 254533.

**Comment by rajjha-msft** [comment]
The issue is fixed and deployed from our end. Please reach out if the issue is still reproducible.
