### ISSUE TITLE
On-Send web addin does not load on new outlook when meeting invite is cancellation is sent.

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4091]
**Description -**
On-Send web addin does not load on new outlook when meeting invite is cancellation is sent.

**Steps to Reproduce -**

1. Open New Outlook.
2. Click on Calender on left pane.
3. Create a meeting invite and click on Send. (On-Send web addin loading here.)
4. Select the same meeting invite and cancel it with note.

**Expected Result -**
1. When meeting invite cancellation is sent, On-Send web addin should get loaded.

**Actual Result -**
1. On-Send web addin does not load even though send action is triggered when meeting invite cancellation is sent.

**Your Environment**
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Link to live example(s)**
[Meeting_Cancel.zip](https://github.com/OfficeDev/office-js/files/14136475/Meeting_Cancel.zip)

**Comment by rajjha-msft** [comment]
Currently we do not support add-ins on meeting invite cancellation.

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
