### ISSUE TITLE
Outlook iOS Add-in - unable to update status of add-in

### ISSUE THREAD

**Issue by Aidam1** [OfficeDev/office-js#4096]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: iOS
* Host [Excel, Word, PowerPoint, etc.]: Outlook
 
## Current behavior
One of our clients is unable to add Outlook Add-in to his Outlook for iOS. The message he gets after he attempts to add it :
```
Something went wrong
We're sorry, we were unable to update status of "{Add-in name}" for the account "{email address}". Pleas...
```

The client is able to add and use the add-in on Office on the Web and Desktop platforms. The add-in is working for other clients in Outlook iOS correctly.

What is the reason for this error? Is it some account setting that prevents adding add-in to Outlook iOS?

**Comment by rajjha-msft** [comment]
Hey @Aidam1 

- What add-in are you trying to install ? Is it available in store ?
- Also, is the issue happening for a specific add-in or all add-ins ?

**Comment by Aidam1** [comment]
Hey @rajjha-msft 
> * What add-in are you trying to install ? Is it available in store ?

eWay-CRM Online, it is available in store.
> * Also, is the issue happening for a specific add-in or all add-ins ?

This is happening only for this add-in, all others work correctly.

**Comment by neprasad-microsoft** [comment]
Hi @Aidam1 
When you say one client - do you mean only one user? Or is it all users in a tenant?

Can you also send us Diagnostic Logs for this issue. 
Steps to collect Diagostic Logs
1. Open Outlook iOS
2. Reproduce the issue.
3. Go to Settings -> Help and Feedback -> Collect Diagnostics -> Restart Diagnostics Collection
4. Send the Incident ID generated
