### ISSUE TITLE
File chooser dialog can only be shown with a user activation "inserting InlinePicture on Web Word"

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js#4098]
I am inserting Inline Picture in word my functionality is working on web but on web facing this error 
`File chooser dialog can only be shown with a user activation`

**Important :** this is working on taskpane only not working from ribbon button click on web version of word.

`

          let fileInput;
          document.addEventListener("DOMContentLoaded", function () {
          // Create a file input element and hide it
          fileInput = document.createElement("input");
          fileInput.type = "file";
          fileInput.accept = "image/*";
          fileInput.style.display = "none";

         // Add the file input element to the document body
         document.body.appendChild(fileInput);

        // Define an event listener for when a file is selected
        fileInput.addEventListener("change", function (event) {
          handleSelectedFile(event);
          });
        });

     async function handleSelectedFile(event) {
          const file = event.target.files[0];

          if (file) {
           const reader = new FileReader();
            reader.onload = async function (e) {
            const base64String = e.target.result.split(",")[1];

               if (base64String) {
                   await Word.run(async (context) => {
                       const cursorPosition = context.document.getSelection();
                       cursorPosition.insertInlinePictureFromBase64(base64String, Word.InsertLocation.replace);
                       await context.sync();
                     });
                }
           };
           reader.readAsDataURL(file);
        }
      }

     function openFileInput() {
         fileInput.click();
     }

`

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b4bb846b-76eb-24a6-6f68-22ffa94a81b1
* Version Independent ID: e82c3831-5e1a-f0d5-f45b-0d4a2301cb73
* Content: [Word.InlinePicture class - Office Add-ins](https://learn.microsoft.com/en-us/javascript/api/word/word.inlinepicture?view=word-js-preview)
* Content Source: [docs/docs-ref-autogen/word/word/word.inlinepicture.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/word/word/word.inlinepicture.yml)
* Service: **word**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by junaid042** [comment]
@wangyun-microsoft  any update why file chooser not working from ribbon on web.

**Comment by junaid042** [comment]
Hi @michelleranmsft any update

**Comment by AlexJerabek** [comment]
Hi @junaid042,
Let me move this issue to the right repo and see if we can get some traction.

**Comment by xiruatms** [comment]
@junaid042 , thanks for reporting this.

I still need more information from you: "Important : this is working on taskpane only not working from ribbon button click on web version of word." 

Are you mentioning that it's not working from addin commands?
Can you isolate the issue out of your codes and try to repro in scriptlab?
Can you help to take a screen record of your isssue so that I can understand more clearly?

Thanks a lot.

**Comment by junaid042** [comment]
Hi @xiruatms 
Yes it is not working from commands this is the [File chooser issue video link](https://drive.google.com/file/d/1dDI4IluU0KwZDNB79-QgGQ1HZgtPnoFf/view?usp=sharing) please take a look on it thanks

**Comment by junaid042** [comment]
@xiruatms 
this is my code that I am trying in my commands file [Script Lab Gist](https://gist.github.com/junaid042/31db1b9c9200dbd4980b96c6ca19e90b)

**Comment by junaid042** [comment]
@wangyun-microsoft  , @xiruatms any update?

**Comment by junaid042** [comment]
@wangyun-microsoft any update

**Comment by xiruatms** [comment]
@junaid042 , thanks for your patience. We're still investigating. Be noted, most of our colleagues are on vacation during Feb 10th ~ Feb 17th for Chinese New Year Holiday. Response might be slow. We'll get back to you as soon as possible.

**Comment by junaid042** [comment]
Hi @xiruatms any update? this is important for our product please fix this, thanks

**Comment by xiruatms** [comment]
Hi, @junaid042 . Thanks for your patience.

According to my investigation, this error is not an Office JS one, but is limited by the browser: Most modern browsers restrict the JavaScript interactions not started by the user, to avoid annoying pages and make XSS a bit more difficult.  This is one of the use case. That is, the file chooser dialog can't be triggered with API call directly:
 function openFileInput() {
     fileInput.click();
 }

I'm thinking a mitigation for your references:

when you click the ribbon button, you can call dialog api https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins to pop up a dialog, and assign the file chooser there.

Let me know whether this mitigation works.

**Comment by junaid042** [comment]
Hi @xiruatms its mean we can't open file chooser directly from ribbon button
