### ISSUE TITLE
Issue on opening document after context loads and context synchs

### ISSUE THREAD

**Issue by DomRoth** [OfficeDev/office-js#410]
## Expected Behavior
I have a base64 Document and replace its ContentControls values and then open the document.

## Current Behavior
In my dev envirronment with Word as desktop version and hosting the Add-In on localhost everything works fine. But when hosting it on another tenant on azure and using any Word, the document.open() crashes with an GeneralException. I first try to replace placeholders with custom properties and fields that references the property. There i had the same issue and i had to mark everything and press F9 to refresh the values so i changed to content Controls.

## Steps to Reproduce, or Live Example
I recognized that i can open the documents on the other tenant, after removing all context.load(someValue) and context.synch() calls from my code before calling document.open()

this is my code for contentControls replacement:

```
private async _openDocumentWithPlaceholder(fileToOpen) {
    let cControlKeyValues = this.state.placeholder;
    let errorOccured = false;

    await Word.run(async (context) => {
      let newDoc = await context.application.createDocument(fileToOpen);

      let cControls = newDoc.contentControls;
      cControls.load();
      await context.sync();

      for (let i = 0; i < cControlKeyValues.length; i++) {
        const cControlKeyValue = cControlKeyValues[i];

        try {
          //try to load controls by Title
          let currentControls = cControls.getByTitle(cControlKeyValue.key);
          currentControls.load();
          await context.sync();

          //try to load controls by Tag if controls by title not exists
          if (currentControls.items.length === 0) {
            currentControls = cControls.getByTag(cControlKeyValue.key);
            currentControls.load();
            await context.sync();
          }

          //if controls by tag or title does not exists, an error
          if (currentControls.items.length === 0) {
            errorOccured = true;
            continue;
          }

          //get first control and replace its content
          let firstControl = currentControls.getFirst();
          firstControl.insertText(cControlKeyValue.value, 'Replace');
          await context.sync();

        } catch (ex) {
          errorOccured = true;
          console.log(ex);
        }
      }

      //return if an error occured
      if (errorOccured) {
        this.setState({selectedTemplate: undefined, isProcessing: false});
        return;
      }

      newDoc.open();
      context.sync();
      this.setState({selectedTemplate: undefined, isProcessing: false});
    });
  }
```

## Context
I use the SSO function, load the document templates from SharePoint via Graph API and then replace the placeholders with the users input an then open the document.
I have different Manifests for lokal and tenant version. 

pls help :)

**Comment by JuaneloJuanelo** [comment]
@DomRoth  can you send me the URL of the Office.js library you are using?

**Comment by JuaneloJuanelo** [comment]
@DomRoth  we need more information to diagnose this issue, please provide
1. you using office.js from what CDN?
2. what office version you are experiencing this?

btw this is a scenario who is not supported in PRODUCTION, because it will not work on all platforms.

Assigning to @weshi to follow up.

**Comment by hengchengfei** [comment]
@DomRoth @JuaneloJuanelo 

Can't operate document before opening "newDoc.open();"
