### ISSUE TITLE
Why Office Dialog not Opening in Outlook Web From ribbon button?

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js#4100]
On web outlook dialog is not opening from ribbon button because dialog permission small popup is not showing. on side panel that is working. How can I open dialog from ribbon button in web outlook? please help! 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a714626a-058a-789e-6add-5e9dfb21fd1f
* Version Independent ID: 1b88a28c-fc36-4518-2808-7246f08d9753
* Content: [Use the Office dialog API in your Office Add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins)
* Content Source: [docs/develop/dialog-api-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/develop/dialog-api-in-office-add-ins.md)
* Service: **microsoft-365**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by junaid042** [comment]
Hi @samantharamon and @exextoc Please take a look and fix this this is important for us to open office dialog from Ribbon button in outlook Web.

**Comment by rajjha-msft** [comment]
Hey @junaid042 

- Are you working on a vanity domain ?
- Was it working before ?
- Do you see the prompt for taskpane add-ins ?

**Comment by junaid042** [comment]
Hi @rajjha-msft 
Was it working before ?  => **not working** 

Do you see the prompt for taskpane add-ins ? => **yes**

![image](https://github.com/OfficeDev/office-js/assets/134502135/e96862bb-5d88-4b74-8b99-5ad4b840a8a2)

**Comment by rajjha-msft** [comment]
Do you see this prompt for taskpane ?

**Comment by junaid042** [comment]
@exextoc @rajjha-msft now its working thanks you very much guy's for your help
