### ISSUE TITLE
CustomTab not working in Outlook on the web

### ISSUE THREAD

**Issue by SimonDania** [OfficeDev/office-js#4103]
# Provide required information needed to triage your issue
When using our cloud add-in in Outlook on the web, the extensionpoint "MessageComposeCommandSurface" does not work.
Currently only "MessageReadCommandSurface" works for us.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome
 
## Expected behavior

 I expect the task pane to open when I click on the add-in button.

## Current behavior

Currently the task pane only opens if I add an ExtensionPoint for the "MessageReadCommandSurface" instead.
It was working just fine until about a week ago where it stopped working without us making any changes.

**Comment by rajjha-msft** [comment]
Hey @SimonDania 

- Do you see any error in the console ?
- Also, does it work correctly for read surface ?

**Comment by SimonDania** [comment]
Hi @rajjha-msft 

* We get a 500 internal server error from "service.svc":
<img width="961" alt="image" src="https://github.com/OfficeDev/office-js/assets/85676333/29c0c9e4-5c6b-4d25-a39d-1466786876b7">

* It works as intended for the read surface

**Comment by SimonDania** [comment]
I have done some further digging and it seems to be related to CustomTab in the "MessageComposeCommandSurface" ExtensionPoint.

If I change it to OfficeTab instead, it works just fine.

**Comment by rajjha-msft** [comment]
The previous error was being encountered while saving custom properties. 
Probably the add-in was saving some custom properties. 

If you want us to investigate more on the issue, please share a sample manifest here : OutlookExtensibility@M365x53858506.onmicrosoft.com.

Also, if the issue is resolved, you can close the issue.

**Comment by SimonDania** [comment]
Hi @rajjha-msft 

I have sent the manifest to the email you have provided.

Let me know if you have any questions regarding the issue.

**Comment by rajjha-msft** [comment]
Thank you for reporting this issue. We have tracked it in our backlog and will pick it up to be fixed. However, we have no timelines to share at this point.

Internal Tracking ID: 255947

**Comment by SimonDania** [comment]
@rajjha-msft Thank you - make sure to reach out if you need anything else.

**Comment by salaman** [comment]
@SimonDania apologies for the delay here -- does this still repro for you? I believe this is fixed now.

**Comment by SimonDania** [comment]
@salaman It seems to be fixed, so I will close the issue.

**Comment by SimonDania** [comment]
@salaman It seems to be fixed, so I will close the issue.
