### ISSUE TITLE
get add-ins button not showing on outlook web

### ISSUE THREAD

**Issue by nadeemAshfaq** [OfficeDev/office-js#4107]
in my outlook web get add-ins are not showing 
![Screenshot 2024-02-07 155933](https://github.com/OfficeDev/office-js/assets/123717307/ac624a32-ff38-4486-bd7b-f2a8615dd95b)
![Screenshot 2024-02-07 161024](https://github.com/OfficeDev/office-js/assets/123717307/a777b8b5-e0ca-4000-b654-adaed15c65b3)

**Comment by nadeemAshfaq** [comment]
using outlook.com account

**Comment by SimonDania** [comment]
If you can't find the "Get Add-ins"-button, try this url instead:
[https://aka.ms/olksideload](https://aka.ms/olksideload)

**Comment by rajjha-msft** [comment]
This is by design. 
You can visit https://aka.ms/olksideload as mentioned above to use the InClient store.

**Comment by nadeemAshfaq** [comment]
> If you can't find the "Get Add-ins"-button, try this url instead: https://aka.ms/olksideload

solved thanks

**Comment by nadeemAshfaq** [comment]
solved thanks all
