### ISSUE TITLE
Dev Plan?

### ISSUE THREAD

**Issue by Jarch09** [OfficeDev/office-js#411]
Apologies if I missed it, but is there a published dev plan somewhere?

Would love to see the roadmap for expansion / improvement of Office.js functionality. I use Office.js for word and Powerpoint addins... in particular, I find that the PowerPoint API lags behind some of the others (e.g., Excel). Is there a plan in place to continue developing these APIs?

Thank you!

**Comment by JuaneloJuanelo** [comment]
The team is focused on Excel and Outlook at the moment and this information can be found (eventually) in our open spec site. https://github.com/OfficeDev/office-js-docs/tree/ExcelJs_OpenSpec

**Comment by Jarch09** [comment]
Why is this issue closed? You didn't answer my question.

Understand the team's focused on Excel & Outlook at the moment - do you plan to spend more time / resources on the other APIs in the future? If so, when? 

It's hard to invest time using / building with these tools if they're going to receive minimal support going forward

**Comment by JuaneloJuanelo** [comment]
Sorry I thought I answered the question. let me add a bit more details. 
Word and PPT additions are on our backlog, but we don't have a clear ETA for its delivery at this point.
In the URL indicated you will get updates about this.
