### ISSUE TITLE
Clarifications on SupportsSharedFolders

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js#4110]
**Article URL**
https://learn.microsoft.com/en-us/javascript/api/manifest/supportssharedfolders?view=common-js-preview

**Describe the problem**
_Before reporting on the officejs, I'm trying my luck here as the documentation might be wrong._
I'm trying to figure out how the Outlook Web Add-ins are supposed to work about shared mailboxes. There are 2 main ways to access a shared mailbox. First, add a shared folder/mailbox into the main mailbox and second, open the shared mailbox  from "Open another mailbox" option. Based on the article linked above, I would expect the following:
- By default, web add-ins are not loading in any of the 2 contexts (folder or mailbox) as the `SupportsSharedFolders` property is by default false.
- When deploying a manifest with `SupportsSharedFolders` set to true, the web add-in is loaded in both contexts.

What is currently happening:
- Regardless of the `SupportsSharedFolders` property, the web add-in is accessible and it works in shared folders inside a mailbox that has the web add-in
- Regardless of the `SupportsSharedFolders` property, the web add-in simply doesn't work or cannot be distributed to the shared mailbox when opened as another mailbox.

Also, in this article https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=windows%2Cxmlmanifest#configure-the-manifest it is written that Shared Mailboxes scenarios are requiring `ReadWriteMailbox` permissions. However, under the permissions article https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/understanding-outlook-add-in-permissions#readwrite-item-permission there is no mention about the shared mailboxes requiring `ReadWriteMailbox` instead of `ReadWriteItem`. The only mention of the shared mailboxes is around the note that says that `SupportsSharedFolders` is required. However, changing it to `ReadWriteMailbox` doesn't change anything.

What is the correct behavior? is the documentation wrong, or is it a bug?

Everything above is from Outlook Online, Chrome.

**Comment by AlexJerabek** [comment]
Thanks for raising this question @bogdanst24.

@samantharamon, can you please investigate?

**Comment by samantharamon** [comment]
Hi @bogdanst24,

I've confirmed that what's documented is expected behavior for shared mailboxes in Outlook on the web. I'll transfer this issue to the office-js repository for further investigation.

@exextoc could you please investigate this?

**Comment by mmanjaree-msft** [comment]
@bogdanst24  Is the addin installed to both user account and shared mailbox? Could you please check the behavior according to this https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=modern%2Cjsonmanifest#shared-mailboxes-1

Also, ReadWriteMailbox permission is required for making rest calls. The read/write mailbox permission is the highest level of permission. In addition to what the read/write item permission supports, the token provided by mailbox.getCallbackTokenAsync provides access to use Exchange Web Services (EWS) operations or Outlook REST APIs.

**Comment by ajays-msft** [comment]
@bogdanst24 - In order for add-in to show up in SharedMailbox,

1) Open in Another Mailbox flow - 
   a) Installed in SharedMailbox, 
   b) Installed in User Mailbox (user who is accessing the shared mailbox), and 
   c) SupportSharedFolders = true

2) In User Mailbox flow, "Add Shared Folder or Mailbox" -
   a) Installed in User Mailbox
   b) SupportSharedFolders = true

**Comment by bogdanst24** [comment]
> Is the addin installed to both user account and shared mailbox? Could you please check the behavior according to this https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=modern%2Cjsonmanifest#shared-mailboxes-1

You are right, it wasn't deployed to both. The fact that the event-based part is running on the shared mailbox without having it deployed to both, created the questions.

> Also, ReadWriteMailbox permission is required for making rest calls. The read/write mailbox permission is the highest level of permission. In addition to what the read/write item permission supports, the token provided by mailbox.getCallbackTokenAsync provides access to use Exchange Web Services (EWS) operations or Outlook REST APIs.

Is this written anywhere in the documentation? From what I can see, it is not a strict requirement for the shared mailbox, as not all scenarios require the EWS or Outlook REST Api.

> In order for add-in to show up in SharedMailbox,
Open in Another Mailbox flow -
a) Installed in SharedMailbox,
b) Installed in User Mailbox (user who is accessing the shared mailbox), and
c) SupportSharedFolders = true
In User Mailbox flow, "Add Shared Folder or Mailbox" -
a) Installed in User Mailbox
b) SupportSharedFolders = true

Thank you, this makes sense. However, there are a few points:
- Still works in User Mailbox without setting SupportSharedFolders to true
- Documentation also requires ReadWriteMailbox permissions

**Comment by ajays-msft** [comment]
@bogdanst24 - Will take a note and update the documentation. @samantharamon - FYI

Regarding this- 
`Still works in User Mailbox without setting SupportSharedFolders to true`
If SupportSharedFolders=false , add-in should not show up in User Mailbox flow when you are looking at an email in the Shared Folder. 

For compose, or sent items though, the behavior is different. In a Shared Folder scenario like above, any new email Composed or Sent from User Mailbox are treated as belonging to User Mailbox and not SharedMailbox. So, add-ins will show up even if SupportSharedFolders=false.

`Documentation also requires ReadWriteMailbox permissions`
My understanding is that ReadWriteMailbox is only needed if you want to call EWS apis, otherwise not needed. Are you noticing that add-ins in sharemailbox are mandating ReadWriteMailbox?

**Comment by bogdanst24** [comment]
It looks fine on a new (third/fourth) thorough read of the documentation. I was probably getting confused by the structure and had to build my matrix for support to get them all.
