### ISSUE TITLE
Office.context.mailbox.item.body.getAsync() with TextCoercion produces inconsistent results for hyperlinks across platforms

### ISSUE THREAD

**Issue by sangaman** [OfficeDev/office-js#4111]
`Office.context.mailbox.item.body.getAsync()` with `TextCoercion` produces inconsistent results for hyperlinks across platforms.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC, Mac, and Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft Outlook Version 1.2024.124.100 on Windows, Microsoft Outlook Version 16.81.2 on Mac
* Operating System: Windows & Mac
* Browser (if using Office on the web): Chrome Version 121.0.6167.139
 
## Expected behavior
`Office.context.mailbox.item.body.getAsync()` with `TextCoercion` should produce consistent, preferably identical, results across platforms.

## Current behavior
Desktop versions of Outlook on both Mac & Windows return email bodies as plain text, whereas Web versions return email bodies as text with HTML tags for hyperlinks. For example, an email addressed that's hyperlinked with a `mailto` in the email like [user@server.com](mailto:user@server.com) will return `user@server.com` on desktop clients and `user@server.com <mailto:user@server.com>` on web clients.

## Steps to reproduce
1. Open an email with hyperlinks and on a desktop client and read the content of the body using a plugin.
2. Open the same email on a web client and read the content of the body using a plugin.
3. Observe that the content is different between desktop and web where hyperlinks are concerned.

## Context
We are trying to build a plugin that reads and validates the body of received emails. To ensure consistent functionality of the plugin, we need the Office API to be consistent as well.

**Comment by rajjha-msft** [comment]
Hey @sangaman 

We're not able to repro the issue at our end. 
Can you please attach the code you're using and the response you get ?

**Comment by sangaman** [comment]
> Hey @sangaman
> 
> We're not able to repro the issue at our end. Can you please attach the code you're using and the response you get ?

To be clear, are you not able to reproduce the value with the tags added for links (as we observe on desktop clients), or the value without any tags (as we observe on web clients)?

**Comment by neprasad-microsoft** [comment]
Hi @sangaman 
 We are seeing different behavior than what you have mentioned. We are seeing that Mac and Windows are displaying the links with tags whereas OWA is not. Is that what you are saying?

Also, as @rajjha-msft mentioned it would help if you can paste the following things here for all the platforms you tested -
Platform :
API call:
Response:

This will help us verify that we are testing the correct thing. Thanks :) .

**Comment by sangaman** [comment]
> We are seeing different behavior than what you have mentioned. We are seeing that Mac and Windows are displaying the links with tags whereas OWA is not. Is that what you are saying?

@neprasad-microsoft Yes, this is exactly what I see and what the issue is for us. Why would these have different behavior? It seems to me that this API should behave consistently across platforms. FWIW I think that text coercion should not insert html/xml tags for links, and therefore the web behavior makes more sense.

Platform:  PC, Mac, and Web - we have tested this on all platforms, PC & Mac have tags and Web does not.
API call: `Office.context.mailbox.item.body.getAsync()`
Response: PC & Mac have link tags (such as `<mail and Web does not.

**Comment by neprasad-microsoft** [comment]
Hi @sangaman,
We went through the issue, and we understand your request for a code change based on your specific needs. However, we regret to inform you that we cannot implement this change at the moment because our products are built on a complex and robust technology that supports a wide range of scenarios and use cases across different platforms (Win32, Mac, Web). 
This difference in behaviour is because of different underlying technology in all 3 platforms. Making a code change for one scenario could potentially break other scenarios and compromise the quality and performance of our products on all platforms. Moreover, it would be costly and time-consuming for our team to test and deploy such a change.
 
We hope you understand our limitations and constraints. We value your business and we strive to provide you with the best possible solutions. We will keep your request in mind for future updates and enhancements. Please let us know if you have any other questions or concerns. We are always happy to help

**Comment by sangaman** [comment]
@neprasad-microsoft I understand there are differences in the underlying platforms.

However, I came across an issue in this repo that describes the same problem - #1248. That issue actually describes other inconsistent behavior besides just the tags for links. We've also seen inconsistent behavior with linebreak, white space being added to the end of lines, and how bullet points are handled. And HTML coercion gives totally different results as well.

That issue is tagged as being in the backlog, but has had no action since 2020. Is there any intention to ever deal with that issue?

If it's not feasible to change `body.getAsync()` - would it be possible to add a different function or coercion type that *does* produce consistent results across OWA and desktop clients? That way it wouldn't break backwards compatibility.

**Comment by neprasad-microsoft** [comment]
Hi @sangaman 
Thanks for your suggestion, but this would be a new feature request which is not tracked on this forum. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by sangaman** [comment]
OK thanks, I created a [feature request](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/mailbox-item-body-getasync-coerciontype-with-consistent-results/idi-p/4063477) on the Tech Community Page. Should we close this issue then? Do you know if there's still any plans to fix #1248 (which is the same issue) or should that be closed as well?

**Comment by neprasad-microsoft** [comment]
Yes, please close these issues. Thanks :) .

**Comment by sangaman** [comment]
Closing this issue as it will not be fixed. Please note that I am not the owner of #1248 and therefore cannot close it, but it sounds like that will never be fixed either unfortunately.
