### ISSUE TITLE
Problems identifying users that are using add-ins

### ISSUE THREAD

**Issue by tomaskukk** [OfficeDev/office-js#4115]
### What Has Changed

Recently, there was a change made to the callback tokens. Although the [blog post](https://devblogs.microsoft.com/microsoft365dev/important-announcement-update-to-exchange-callback-tokens-for-outlook-add-ins/) did not specify what changes occurred, we have observed that one significant alteration is the removal of the UPN (User Principal Name) field from the token. The new callback tokens now only provide the user's SMTP address.

### Why This Is Important

Some organizations prefer to use the user's UPN to identify their users. Previously, we relied on this field to identify users for our service. However, with this change, it appears that we can no longer use the UPN for user identification.

### The Problem

With the UPN now omitted from the callback token, there is no way to securely fetch the user's UPN and pass it to our service. This seems feasible for organizations that support the REST API, as we can retrieve the information using the REST callback token from the `https://outlook.office365.com/api/v2.0/me/people` endpoint. However, for on-premise organizations with only EWS support, fetching the user's UPN appears impossible using the EWS callback token.

### Question

Is there any method to reliably fetch the user's UPN in all scenarios, regardless of the organization's mailbox configuration (fully on-premise, EWS support only)? I am aware that it is possible to do this on the client side using the `ResolveNames` operation, but since the request must occur on the client, it cannot be securely passed to our server. 

### Notes
The primary way of identifying the user for us is the suggested way to use [the Exchange identity token](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/authenticate-a-user-with-an-identity-token). The UPN based authentication is only used before we have the identity token based id configured for the user.

**Comment by rajjha-msft** [comment]
Hey @tomaskukk 

It is not recommended to parse the token from `**getCallbackTokenAsync**`. 
Please use the JS Api `**Office.context.mailbox.userProfile.emailAddress**` to identify the users. 
Or you can use `**getUseridentityToken**` Api, which can be used for the same.

**Comment by tomaskukk** [comment]
Hey @rajjha-msft,

> Please use the JS API `Office.context.mailbox.userProfile.emailAddress` to identify the users.

Utilizing this API for user identification and forwarding this information to our server presents a security concern, as there's no guarantee against request forgery. Moreover, this approach does not meet our requirements since it provides the SMTP address, not the UPN, which is essential for our use case.

> Or you can use the `getUseridentityToken` API, which can be used for the same purpose.

The `getUseridentityToken` API falls short of our needs as well; it neither provides the user's UPN nor the SMTP address. Our challenge lies in linking a user based on their UPN, which is crucial for us to link the constructed user ID from the `getUseridentityToken` to a user.

I'm not a fan of parsing the `getCallbackTokenAsync` either, but there isn't a reliable method to fetch the user's UPN with the tokens provided by the Office add-in client. It would be beneficial if this limitation could be addressed, considering some organizations' preference for using UPN over SMTP addresses.

**Comment by rajjha-msft** [comment]
Hey @tomaskukk 

You'll be able to uniquely identify a user if you use a combination of the `msexchuid` and `amurl` properties for `getUserIdentityToken` as mentioned here https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/authenticate-a-user-with-an-identity-token#generate-a-unique-id.
