### ISSUE TITLE
No inserting SVG support for PowerPoint in iOS

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#412]
## Expected Behavior
The PowerPoint app for iOS should support inserting SVG files. 

## Current Behavior
When trying to insert an SVG an error occurs:
**"The specified coercion type is not supported"**
Although the requirements set supports ImageCoercion 1.2

## Steps to Reproduce, or Live Example
[Gist Repo](https://gist.github.com/barisbikmaz/73526f81e1425845fc199506ff871429
)

## Context
We show users svg files depending on the requiremets set. Currently PowerPoint on iOS says it supports inserting SVG but errors after trying to insert.

## Your Environment

* Platform: iOS
* Host: PowerPoint

## Useful logs
Error:
```
{
    "name": "Invalid Coercion Type",
    "message": "The specified coercion type is not supported.",
    "code": 1000
}
```

**Comment by JuaneloJuanelo** [comment]
imageCoercion is not the same as the SVG coercion. Team is aware of gap and on pipeline.

**Comment by JuaneloJuanelo** [comment]
Hey Baris I noticed that in your code you are not checking of the ImageCoercion 1.2 is supported can you please confirm ? In iOS it should return false. (Use office.context.requirements.isSetSupported ) 

Thanks

**Comment by barisbikmaz** [comment]
Hi @JuaneloJuanelo thanks. I've updated my gist sample. Yes PowerPoint for iOS returns true for the check isSetSupported('ImageCoercion', 1.2).

**Comment by keyur32** [comment]
@JuaneloJuanelo  - you were the last one to comment on this. Is there an update here? thanks.

**Comment by barisbikmaz** [comment]
This is still an issue. Any updates on this ?

**Comment by JuaneloJuanelo** [comment]
yes its still an issue in iOS. so to clarify where we are:  right now the team is working to fix the issue that the requirement set is not supported in iOS. we are tacking with bug 3468656.

**Comment by JuaneloJuanelo** [comment]
update the fix to the requirement set is coming on the October Update for iOS. (should start rolling out in the next couple of weeks.

@barisbikmaz  please add support for PPT iOS in our u[servoice channel.](https://officespdev.uservoice.com/) thanks!

**Comment by robertmuehsig** [comment]
Is this really fixed? We are seeing the same issue. 
Our code works on Windows, Web & mac, but fails on iPad.
