### ISSUE TITLE
OnSend limitations are not necessary

### ISSUE THREAD

**Issue by lawal-aw** [OfficeDev/office-js#4120]
The limitations set on OnSend defeats the purpose of having the feature in the first place. There are use cases, where a user needs email content to reformatted or appended to. Why not rather have permissions and warning instead of Microsoft restricting the feature. Let the users assess the risk and decide by themselves.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9e12d688-9620-e8f2-871d-922ec98008b5
* Version Independent ID: a8b409f3-44f7-97e5-d722-cbf04edc0653
* Content: [On-send feature for Outlook add-ins - Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=windows#limitations)
* Content Source: [docs/outlook/outlook-on-send-addins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/outlook/outlook-on-send-addins.md)
* Service: **outlook**
* Sub-service: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by millerds** [comment]
Can you clarify specifically which limitations you feel are getting in the way and the scenario you are trying to accomplish?
