### ISSUE TITLE
[Outlook Addin] Access "FromChanged" event in Task Pane

### ISSUE THREAD

**Issue by J0hnRoger** [OfficeDev/office-js#4122]
Hello,

**Environment:**
Outlook 
OfficeJS Version: 1.13

With the new event `OnMessageFromChanged` [you introduced in the 1.13](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/requirement-set-1.13/outlook-requirement-set-1.13?view=common-js-preview#:~:text=OnMessageFromChanged), We can now react to the changes of the From field and it works perfectly 👍 

However, I also need to react to these changes in the Task Pane of my add-in.  

For me, it's the exact same behaviour than the previous Office.Event:  `
Office.context.mailbox.item.addHandlerAsync(Office.EventType.RecipientsChanged, () => {
      onRecipientChanged();
    });`

So, do you plan to release an eventType for catching this behaviour in the taskpane -  `Office.EventType.FromChanged` ? 

Can you give me visibility on the release date ?

If it's not planned, could you provide feedback and a workaround for responding to this event in the taskpane? We are exploring the idea of using SessionData, accessible by both the command and the taskpane

Have a nice day

**Comment by samantharamon** [comment]
Hi @J0hnRoger,

Thanks for reaching out. It's great to hear that your add-in is now able to respond to changes to the From field. Let me follow up on your query.

**Comment by ztcdsb** [comment]
Hi @J0hnRoger 
When OnMessageFromChanged is triggered, it will force kill add-ins in current account and load add-ins in target account, meaning the task pane will be gone when user trigger the event. 

It would be helpful if you can provider further details about your specific user case

**Comment by ricardoleonhart** [comment]
@ztcdsb 
>When OnMessageFromChanged is triggered, it will force kill add-ins in current account and load add-ins in target account, meaning the task pane will be gone when user trigger the event.

Strange, I tested in my environment by switching to another Exchange user but the taskpane is still there. I can see the event is being triggered based on console logs though. Is this a bug? Or could it be because I sideloaded the addin?

Btw, I tested on outlook.office.com in Chrome and this is my event handler, just in case

```
async function onMessageFromChangedHandler(event: Office.AddinCommands.Event) {
  console.log(event);
  console.log("Hello");
}

Office.actions.associate("onMessageFromChangedHandler", onMessageFromChangedHandler);
```

**Comment by markb-trustifi** [comment]
> When OnMessageFromChanged is triggered, it will force kill add-ins in current account and load add-ins in target account, meaning the task pane will be gone when user trigger the event.

When changing FROM to shared account an add-on remains still without reloading.
Just adding `Office.actions.associate("onMessageFromChangedHandler", handler)` is not enough. For catching this event you have also to configure manifest.xml and place this event handler into the separate JS file. It cannot be located in the main angular code.
All these makes using this event inconvenient.
