### ISSUE TITLE
How to call an office js function from VBA code?

### ISSUE THREAD

**Issue by HugoAlbertoNieto** [OfficeDev/office-js#4123]
We have created an Office addin using office.js. The addin works correctly but we woulld like to see if it is possible to **call one of the addin functions from VBA**. See below the details of our scenario.

The Office addin we created is intended to replace a previous VBA addin. Besides the VBA addin, we have used an additional VBA file that we call _underwriting model_ that was so far calling the VBA addin. This underwriting model VBA code only runs on our server, and our clients do not need to run this. 

Calling the **VBA addin from the underwriting model was not an issue** because both were created with VBA code. But now we would like to use the same underwriting model to call the new Office addin functions. We found a promising approach using the code from this repository:

https://github.com/sancarn/VbaJsBridge

The approach consists in setting a custom xml part in the workbook using VBA. That custom xml part includes information about the function that we want to run from the Office addin. Then the `setInterval` method is used in JavaScript to read the custom xml parts of the workbook and once it founds the one that comes from VBA, it will process it adequately to run the function we want to run.

Although the idea is great, we haven't been able to get it work, so we wanted to ask if there is another alternative to call an Office addin function from VBA.

Any guidance around this would be highly appreciated. Thanks!

**Comment by zhenhuangMSFT** [comment]
Hi @HugoAlbertoNieto, I am afraid there is no such support. I will update here if I find something.

**Comment by bhattikashif** [comment]
Hi @HugoAlbertoNieto , If your JS function is parameter less, you can register shortcut keys against your JS function and then trigger your JS function using Application.SendKeys function from VBA. But if this function requires parameters then you will need a similar approach as you have referenced to share data between VBA and JS.

**Comment by HugoAlbertoNieto** [comment]
Thanks @bhattikashif. My function requires parameters. We ended up deciding to mantain both, the VBA and the JavaScript addins at the moment. Thanks!

**Comment by bhattikashif** [comment]
Now just a week after this I got the same requirement for calling JS function from VBA code. @zhenhuangMSFT is there any chance of introducing this functionality in near future/current year?

**Comment by HugoAlbertoNieto** [comment]
@bhattikashif I would suggest you to to give a try to the JsBridge repository. After a week of research, the closest I was to make it work, was using that code.

**Comment by zhenhuangMSFT** [comment]
Hi @bhattikashif , unfortunately there will be no plan for introducing such capability officially in the short term.

**Comment by sancarn** [comment]
@HugoAlbertoNieto Glad to see something of mine was of use 😅
