### ISSUE TITLE
[Outlook Deeplink] Breaks email subaddressing by handling "%2B" as space

### ISSUE THREAD

**Issue by matuskosut** [OfficeDev/office-js#4127]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: latest (browser)
* Operating System: MacOS
* Browser (if using Office on the web): Chrome 121.0.6167.139
 
## Expected behavior

Expecting to be able to use deeplink to format an email to subaddressed email (contains %2B = '+').

On technical level expecting for `%2B` to be replace with `+` (not with space).

## Current behavior

The target email address gets misrepresented. Subaddressing symbol from URI `%2B` gets replace with space ` ` symbol, which makes target address (TO) invalid. User is not able to send email.

## Steps to reproduce

1. open url: https://outlook.office.com/mail/deeplink/compose?to=support%2Bproduct-request%40example.com&subject=Test&body=testing
2. check To address, expecting the address to be highlighted as red, because `%2B` was incorrectly replaced with ` `

![outlook](https://github.com/OfficeDev/office-js/assets/10776269/58e514f4-9d77-46eb-bdc7-5522b74d9f40)

## Link to live example(s)

1. https://outlook.office.com/mail/deeplink/compose?to=support%2Bproduct-request%40example.com&subject=Test&body=testing

# Provide additional details

Looks like URI parameters are decoded at least twice (`%2B` -> `+` -> ` `).

## Context

The problematic part is that plus symbol can be used as space (alt. to %20), but when encoded %2B it should always turn out as `+`.

- https://datatracker.ietf.org/doc/html/rfc5233#section-1
- https://learn.microsoft.com/en-us/exchange/recipients-in-exchange-online/plus-addressing-in-exchange-online

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by neprasad-microsoft** [comment]
Hi @matuskosut 
This forum is limited to office-js related queries. For Exchange specific queries and support please post your questions here - https://learn.microsoft.com/en-us/answers/tags/342/office-exchange-server-management . 
You can also explore the options at https://support.microsoft.com/home/contact

**Comment by matuskosut** [comment]
Hi @neprasad-microsoft , could you advice on what would be the best place to report bug in this API endpoint https://outlook.office.com/mail/deeplink/compose ?

I am not managing an exchange server, I am just a user of web based service. Does that still fit into the link you placed?

**Comment by neprasad-microsoft** [comment]
Hi @matuskosut 
Apologies for the confusion. Since you posted the Exchange Link for Plus Addressing, we suggested the Exchange Support link for you. If you are not using Exchange then, you can use the other link - https://support.microsoft.com/home/contact
Also, there is a Microsoft Q&A platform which can be used for asking questions - https://learn.microsoft.com/en-us/answers/
