### ISSUE TITLE
What to do when your Dev subscription expires

### ISSUE THREAD

**Issue by fedeisas** [OfficeDev/office-js#4128]
I don't know if this is the right channel, but I've tried others (email & phone support) and failed.

A few months ago (18 to be exact), I signed up for a Microsoft 365 Developer Subscription and used that to integrate my app: SCIM & Add-Ins. 

That subscription is now expired (it seems to be a date automatically when I signed up), and I'm stuck: I can't reactivate that subscription nor create another dev subscription (to get a new tenant). I don't mind losing the data, but I do mind not being able to iterate and develop my software using that sandbox.

<img width="1379" alt="image" src="https://github.com/OfficeDev/office-js/assets/251675/7d422e8a-f7e0-4bec-9db3-459fa2b11af2">

**Comment by lindalu-MSFT** [comment]
@KelBowen Can you answer this one?

**Comment by lindalu-MSFT** [comment]
@fedeisas Kelly can answer to your specific question if you can "reactivate" your previous account or how to unblock you getting a new tenant.

Meanwhile, I thought I'd share some context what the current state of the Microsoft 365 developer program is. We're going through a transition right now.

**What's happening? Limited distribution of the Microsoft 365 E5 developer subscription**
 
At this time, we're limiting automated access to the Microsoft 365 developer tenant subscription to developers and/or organizations with active subscriptions to Visual Studio Enterprise. Additionally, current Microsoft Partner Network (MPN) members, active Premier or Unified support customers, and active members of our Microsoft MVP program can fill out a form to receive access to a developer tenant subscription.  We're evaluating options that will allow us to resume the provisioning of developer tenants to the wider Microsoft 365 Developer community. We'll post news and updates about the availability of the Microsoft 365 E5 developer subscription’s availability from time to time here in our blog(https://devblogs.microsoft.com/microsoft365dev/tag/microsoft-365-developer-program/).
 
If you do not currently qualify for a developer subscription, you can purchase a Microsoft 365 plan(https://www.microsoft.com/en-us/microsoft-365) and configure it for development.  We encourage you to join the program, regardless, so you can receive additional benefits and communication for the latest tools and guidance for your development. We'll continue to refine the eligibility criteria for access to this benefit.

More info: https://devblogs.microsoft.com/microsoft365dev/stay-ahead-of-the-game-with-the-latest-updates-to-the-microsoft-365-developer-program/

**Comment by fedeisas** [comment]
@lindalu-MSFT, thank you so much for your thorough answer. I'm willing to get a subscription for this.

Exploring the [Visual Studio pricing page](https://visualstudio.microsoft.com/vs/pricing/?tab=business) is not 100% clear to me which subscription I need to get access to a developer tenant subscription.

Thanks!

**Comment by lindalu-MSFT** [comment]
@fedeisas Here's the wiki article [Join the Microsoft 365 Developer Program as a Visual Studio subscriber](https://learn.microsoft.com/en-us/office/developer-program/join-with-visual-studio?source=recommendations) and then the details how to [activate your subscription to the dev program](https://learn.microsoft.com/en-us/visualstudio/subscriptions/vs-m365#how-to-activate) and get your tenant.

I 100% recommend going this route then you simply don't have to worry about getting cut off again. Plus, there are other benefits.

**Comment by fedeisas** [comment]
Thanks @lindalu-MSFT.

Is there a cap on the number of developer subscriptions per account?
Do I need to delete my expired one to create a new one?
Is it instantaneous? If I recall correctly, I read somewhere about a 60-day cooldown period.

It would be super helpful if someone (maybe @KelBowen) could extend my current developer subscription until the new process is fully transitioned.

**Comment by fedeisas** [comment]
I ended up getting a Professional subscription and got a new tenant environment. Thanks.

**Comment by lindalu-MSFT** [comment]
Yay! Happy coding!

**Comment by dktoa** [comment]
I have the same issue - how to renew Microsoft 365 Developer subscription?
