### ISSUE TITLE
Regarding appointmentResponse

### ISSUE THREAD

**Issue by danjyoung** [OfficeDev/office-js#413]
The main issue is that appointmentResponse is not returning responses. It's returns undefined. It's is documented as returning MailboxEnums.ResponseType.

I'm also pointing out potential issues the the sample code on the documentation page this issue was reported from.

> Gets the response that an attendee returned for an appointment. This property applies to only an attendee of an appointment, as represented by the optionalAttendees or requiredAttendees property. This property returns undefined in other scenarios.

> var requiredAttendees = Office.context.mailbox.item.requiredAttendees;
> console.log("There are " + requiredAttendees.length + " required attendees.")
> requiredAttendees.forEach(function (requiredAttendee) {
>     console.log("Attendee " + requiredAttendee.displayName + ": " + requiredAttendee.appointmentResponse);
> });

Are these examples correct? I don't see them calling getAsync. The examples do not work for me. Additionally, following the pattern of calling getAsync, I still can't access appointmentResponse.

Code sample:
```
let item = Office.context.mailbox.item,
  requiredAttendees, optionalAttendees, totalAttendees = 0;

if (item.itemType === Office.MailboxEnums.ItemType.Appointment) {
  requiredAttendees = item.requiredAttendees;
  optionalAttendees = item.optionalAttendees;

  if (requiredAttendees) {
    requiredAttendees.getAsync((asyncResult) => {
      console.log(asyncResult.value);
      if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
        totalAttendees += asyncResult.value.length;
        for (let i = 0; i < asyncResult.value.length; i++) {
          console.log(asyncResult.value[i].displayName + ' | ' +
            asyncResult.value[i].appointmentResponse + ' | ' +
            asyncResult.value[i].recipientType + ' | ' +
            asyncResult.value[i].emailAddress);
        }
      }
    });
  }
}
```

Question on stackoverflow for additional details:
https://stackoverflow.com/questions/54837540/is-it-possible-to-retrieve-appointment-responses-from-attendees

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 936b8688-01b5-481e-527d-780cc7c2ced1
* Version Independent ID: 87e09cec-d2c4-bcf0-b990-a24a81e917b9
* Content: [Office.EmailAddressDetails interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook_1_5/office.emailaddressdetails?view=office-js#appointmentresponse)
* Content Source: [docs/docs-ref-autogen/outlook_1_5/office.emailaddressdetails.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook_1_5/office.emailaddressdetails.yml)
* Product: **outlook**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
@danjyoung I tried following code and now I am able to get number of attendees who accepted/declined/gave no response. Can you Please try this once and let us know whether it helps-

var requiredAttendees = Office.context.mailbox.item.requiredAttendees;
console.log("There are " + requiredAttendees.length + " required attendees.")
var accepted=0;
var declined=0;
var none=0;
requiredAttendees.forEach(function (requiredAttendee) {
if(requiredAttendee.appointmentResponse == 'none')
	none++;
if(requiredAttendee.appointmentResponse == 'accepted')
	accepted++;
if(requiredAttendee.appointmentResponse == 'declined')
	declined++;

console.log("Attendee " + requiredAttendee.displayName + ": " + requiredAttendee.appointmentResponse);
});

console.log("No Response or Accepted but selected do not send response:" + none);
console.log("Accepted:" + accepted);
console.log("Declined:" + declined);
