### ISSUE TITLE
User are blocked from sending emails in OnSend Event Activation

### ISSUE THREAD

**Issue by pavelstudeny** [OfficeDev/office-js#4132]
# OnSend on classic Outlook broken since the January semi-annual release
Since January 9, about 2% of classic Outlook for Windows users are blocked from sending emails. After hitting Send, Outlook is blocked trying to execute an add-in OnSend handler. This happens in 100% of cases to the affected users. Does not happen in New Outlook for Windows.

## Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: classic Outlook
* Office version number: 16.0.16731.20504
* Operating System: Windows 10 Enterprise
* Browser (if using Office on the web): n/a
 
## Expected behavior
OnSend is executed

## Current behavior
After a users hits Send, Outlook displays the "<add-in> is working on your request." notification, but the add-in is not executed and sending is blocked.
![working_on_your_request](https://github.com/OfficeDev/office-js/assets/8670912/ba46028e-7d94-4164-b84a-e487a34dd2e6)

**Comment by neprasad-microsoft** [comment]
Hi @pavelstudeny 
Could you please test the behaviour on some other platform (Outlook Web/Mac) and let us know if it happens there also?
Also, if this is a store add-in then please send us the store link. If not, then please share the manifest on OutlookExtensibility@M365x53858506.onmicrosoft.com.

**Comment by pavelstudeny** [comment]
This stops happening when the affected users switch from classic Outlook to New Outlook or OWA. Furthermore, I'm not aware that Mac users would affected. This seems to be specific to classic Outlook for Windows.

Additionally, we don't see this happening to 98% of other classic Outlook users with seemingly the same configuration (Outlook version, Windows version).

So far, we cannot tell whether
1. the JS engine doesn't instantiate for the users
2. Office JS doesn't load
3. or the add-in OnSend handler doesn't evaluate

It's difficult to diagnose this with the users who don't even have admin rights.

The add-in manifest is available at https://addin.outreach.io/ .

**Comment by ajays-msft** [comment]
@JuaneloJuanelo - FYI

**Comment by pavelstudeny** [comment]
We have verified with one of the affected users that clearing the cache at %LOCALAPPDATA%\Microsoft\Office\16.0\Wef resolves the issue. What might have affected the cache behavior:
- The cache was fairly big
- Might be related to updates of the add-in assets (e.g. could the OnSend handler be removed from the cache and not downloaded again?) I observe that occasionally, some other assets such as add-in ribbon icons are not displayed in classic Outlook

**Comment by ztcdsb** [comment]
It could happen if the user get a bad version of bundle.js. Please let us know if clearing the cache resolve the issue for all affected users.

**Comment by pavelstudeny** [comment]
It did help a few. I should have the info next week if it helped everybody.

**Comment by pavelstudeny** [comment]
@ztcdsb I have updates from the users - this is marked as completed so if a fix is on the way, at least for the record:

Clearing the cache helps all the affected users. Some of the users had issues with other add-ins and it helped with those as well.

**Comment by pavelstudeny** [comment]
@ztcdsb more updates: this is still not fixed and users have to clear the cache to keep their add-ins operational. Per the report, they need to do this for multiple add-ins.

**Comment by ztcdsb** [comment]
@pavelstudeny This should be fixed once the user clear cache and restart add-in, it will download latest bundle file.
Can you ask user to confirm if bundle.js is downloaded?

bundle.js is per add-in basis, it locates in a directory with unique GUID and Base64 encoding.
The highlighted part is the add-in ID
For example:
%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\{A1D477E9-63F7-4857-AEC1-7864F9BBB6C1}\SWslFPVB6+BoZ3BWunn15w==\Javascript\ **a213afbb-806e-2d05-bbaf-ef3384d30022_1.1.0.0_en-US**
