### ISSUE TITLE
Is there a way from the Office/Outlook Js API to determine if user has selected to edit the selected event, all events, or this event and all after?

### ISSUE THREAD

**Issue by darrenatdinner** [OfficeDev/office-js#4134]
I have a Outlook Web Add-in that I am developing to be used for Outlook on the Web, but there is a scenario that I need to handle. When a user creates a recurring event then saves it or sends it, they have the ability to edit the event/appointment after the fact(ignore the fact that Meeting and Appointments are the same online :/).

My issue is when the user goes to edit the meeting they have the ability to choose "This Event", "All Events In The Series", and "This and All Following Events".

The following are the three scenarios that I need to handle.

1. Know that the user has selected the single event. I use the fact that the event is an occurrence of the event to interpret this as the user editing a single occurrence or exception.
2. Know that the user has selected all occurrences of the meeting/appointment. That's easy, I'm able to see that the item selected is the Master event.
3. Know when the user has selected this and all following. This is where my problem is, there's no obvious way to know that the user has selected this option. When the user selects this option the UI displays "You're editing this and all following events in the series." but there seems to be no way to know that this is happening from the JS Api. The JS API has access to the recurrence object, which for my purposes is useless because it details the recurrence patter and not the recurrence details related to the selected event. I cant get the data from a graph query because technically the action the user is taking is totally client side, hence looking up the Graph Id gives you a reference only to the occurrence.

I'm kind of stumped, I don't see a way in the current(not preview) JS Api to interpret this specific scenario. It also doesn't help that this functionality isn't available on the desktop version.

Ive tried to use the pass the Id to our Web Api that has access to the MS Graph API with additional processing, but I only get the single occurrence. This makes sense in a way, being that you selected a specific entry to edit. The problem with this is that only the JS API has knowledge of the intention of the user, so one would assume that selecting edit on an event doesn't save data, but reads it for the user to then edit and somehow on save/send Outlook then propagates it to future events.

**Comment by akagarwa-msft** [comment]
Currently the feature, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
