### ISSUE TITLE
Outlook Mobile app not inserting signature

### ISSUE THREAD

**Issue by MrDaleQ** [OfficeDev/office-js#4136]
Our add-in software inserts a signature into a composed email. For some clients the add-in shows as installed and active to the user, but the signature is not inserted into the composed email

## Your Environment
* Platform: iOS
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 4.2404.0
* Operating System: iOS
 
## Expected behavior
Signature to be inserted when composing an email.

## Current behavior
When opening a new email within Outlook mobile and waiting 120 seconds no signature is inserted. (Signature is inserted correctly on Outlook Desktop).

## Steps to reproduce
Open Outlook Mobile. Create new email. Signature is not inserted.

## Useful logs
Powerlift Logs
Incident ID: GS2YCAF5

**Comment by neprasad-microsoft** [comment]
Hi @MrDaleQ 
Could you help us with a few queries:
1. Is this happening only on iOS? 
2. Was this working in the past and it stopped working or is it a new change?
3. Is this add-in on Store? If so, can you send us the link so that we can debug on our side? If it is a custom add-in, please send the manifest on OutlookExtensibility@M365x53858506.onmicrosoft.com. 
4. Please restart the log collection and just reproduce the issue and generate a powerlift again.

**Comment by MrDaleQ** [comment]
Hi @neprasad-microsoft 

Thanks for your reply here.

1 - Yes, we are only seeing this behaviour on iOS currently
2 - The add-in has only just been deployed by the customer. We have other customers where the add-in is working without issue.

v4.2404.0 (Not experiencing the issue)
v4.2347.1 (experiencing the issue)
v4.2404.0 (Not experiencing the issue)
v4.2404.0 (experiencing the issue)


3 - The add-in is available on AppSource but in this customers case is deployed as an integrated app from the 365 admin centre. https://appsource.microsoft.com/en-gb/product/office/wa200005237?tab=overview

4. I will ask the customer to regenerate the powerlift.

**Comment by ajays-msft** [comment]
@MrDaleQ - Waiting for logs for further analysis.

**Comment by neprasad-microsoft** [comment]
@MrDaleQ One more question. Are you using quick reply (the Reply which comes as a small textbox at the bottom of the email)? In that case, the signature will not get added in the reply window but will be appended while send. Please verify if the signature is present in the sent email/received email.

**Comment by MrDaleQ** [comment]
@neprasad-microsoft 

Thanks for the response here - just to confirm, the add-in does not use the internal signature functionality - the add-in is called by the on-compose event from Outlook and the signature is inserted directly to the email body using the Set-Signature command.

The issue is occurring when using the full "new email" option from within Outlook mobile.

As is, we have received an update from the customer that the feature is now working correctly for all users who were experiencing the issue - we have made no changes to the add-in to trigger this. I assume that if the add-in is listed in the "connected apps and add-ins" feature this should then be live, and there should not be a delay to this becoming active?

**Comment by neprasad-microsoft** [comment]
Hi @MrDaleQ 
For admin deployed add-ins there is some delay till the add-in is deployed to all the users. This might be the reason for this issue.
