### ISSUE TITLE
Navigator.storage (OPFS) access

### ISSUE THREAD

**Issue by chfaft** [OfficeDev/office-js#4137]
We are about to create an Outlook Add-In that should be able to encrypt large files before uploading and optionally be able to decrypt them after downloading. The technology in charge is Navigator.storage (OPFS) which allows to save files on the local filesystem which allows us to use the local harddrive as intermediate memory before and after the encryption/decryption. As the JavaScript engine in Outlook runs in a sandbox, we have not found a way so far to do this operation in the Outlook and web context. 

Do you see any chance to use this feature in another way or does any plan exist to intercept uploads and downloads for AddIns?

**Comment by ajays-msft** [comment]
@chfaft - If I understand correctly, you need an office-js event to know before an attachment is uploaded, and after attachment is uploaded. Is that right?

**Comment by chfaft** [comment]
Hi @ajays-msft - Thanks for your reply. We actually need to modify the content of files before the upload and after the download. The files can theoretically be much bigger than the memory of the user. Therefore we currently use OPFS to save them temporary, which seems to be not available in the Outlook-JS-Sandbox. This process happens completely independend of the Outlook attachments, so it does not have anything to do with Outlook attachments events. The problem so far is that we get a code snippet like this not running:

`
  navigator.storage.getDirectory().then((directory) => {
    console.log("Directory", directory)
  }).catch((e) => {
    console.error("Navigator Storage Error: ", e)
  })
`

**Comment by ajays-msft** [comment]
@chfaft - Will it help if you have an event before attachment is added, and in the event office-js gives a link to file, you then upload the file to the server, encrypt there and add it back to the email?
Similar approach you could potentially have for downloads.

This is not a feature we have currently, but I want to understand if that will help you.

**Comment by chfaft** [comment]
@ajays-msft - Thanks for your message! Your suggestion would simplify things, but we really need to have this action done on client side for security reasons. Encryption on server side is unfortunately no option in this case.

**Comment by zhngx1** [comment]
@chfaft Are you having issue with windows Outlook client or Outlook web? What is the error you see for your code snippet with the navigator.storage?

**Comment by chfaft** [comment]
@zhngx1 It turned out that the File API is a possible approach to deal with this issue, as it allows the interception of file uploads in the way we would need. We have not done our tests with really big files yet, but as for now this way seems to be a suitable approach for our needs.

**Comment by ajays-msft** [comment]
This forum is limited to supporting office-js apis. Since this is out of scope of office js, closing it.
