### ISSUE TITLE
Email Id's Having International Characters when tried to save using SetAsync are getting removed.

### ISSUE THREAD

**Issue by RaveendraReshma** [OfficeDev/office-js#4139]
1. We are developing office web Addin for outlook using event based (Smart Alert) .The Addin is generated using office yo generator Task Pane add-in using the React framework.
2. We are getting the recipient data [ to/cc/bcc ] using Office.context.mailbox.item and we are rendering the same recipients onto the taskpane.
3. But when we are trying the overwrite the recipients[containing international characters] from taskpane component to To/Cc/Bcc fields the recipients are getting removed.

## Your Environment

* Platform : Office on the web
* Host : Outlook [OWA]
* Office version number :  Version 2311 Build 16.0.17029.20140
* Operating System: Windows
* Browser (if using Office on the web): Chrome & Edge
 
## Expected behavior
The recipients containing international characters should also get overwritten on to To/Cc/Bcc fields.

## Current behavior
when we are trying the overwrite the recipients[containing international characters] from taskpane component to To/Cc/Bcc fields the recipients are getting removed.

## Steps to reproduce

1. Add any recipients containing international characters in To/Cc/Bcc fields and click on send and it will open the taskpane.
(eg: john.doe@gmail.com, jöhn.doe@gmail.com, jane.doe@gmail.com, jãne.doe@gmail.com)
<img width="638" alt="image" src="https://github.com/OfficeDev/office-js/assets/145095553/d6fab35b-2151-4ca5-a5bc-f9312573961d">

2. Render the same recipients onto the taskpane.
<img width="235" alt="image" src="https://github.com/OfficeDev/office-js/assets/145095553/af423453-937e-48a8-aeaa-ab3291ba7533">

3. Try to overwrite the same id's from taskpane to Outlook To/Cc/Bcc fields using 
[ we have a send button in taskpane using which we are overwriting the recipients from taskpane to Outlook To/Cc/Bcc fields. ] 

Office.context.mailbox.item.to.setAsync([...new Set(toArray)], function (result) {
          if (result.error) {
            console.log(result.error);
          } else {
            console.log("Recipients overwritten");
          }
        });
        
4. At this point when we try to overwrite the recipients from taskpane component to To/Cc/Bcc fields the recipients having international characters are getting removed.
<img width="643" alt="image" src="https://github.com/OfficeDev/office-js/assets/145095553/aa59ad5b-1da5-474b-b9a8-35a46cd8d318">

## Context

- Our requirement is to also send mail to recipients having international characters.
- International Characters list:
à ▪  á ▪  â ▪  ã ▪  ă ▪  ä ▪  ā ▪  å ▪  æ ▪  ć ▪  č ▪  ç ▪  è ▪  é ▪  ê ▪  ĕ ▪  ë ▪  ē ▪  ì ▪  í ▪  î ▪  ĭ ▪  ï ▪  ð ▪  ł ▪  ñ ▪  ò ▪  ó ▪  ô ▪  õ ▪  ö ▪  ő ▪  ø ▪  š ▪  ù ▪  ú ▪  û ▪  ü ▪  ű ▪  ý ▪  ÿ ▪  þ

À ▪  Á ▪  Â ▪  Ã ▪  Ă ▪  Ä ▪  Ā ▪  Å ▪  Æ ▪  Ć ▪  Č ▪  Ç ▪  È ▪  É ▪  Ê ▪  Ĕ ▪  Ë ▪  Ē ▪  Ì ▪  Í ▪  Î ▪  Ĭ ▪  Ï ▪  Ð ▪  Ł ▪  Ñ ▪  Ò ▪  Ó ▪  Ô ▪  Õ ▪  Ö ▪  Ő ▪  Ø ▪  Š ▪  Ù ▪  Ú ▪  Û ▪  Ü ▪  Ű ▪  Ý ▪  Þ ▪  ß.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by neprasad-microsoft** [comment]
Thanks for reporting this issue regarding special characters. It has been put on our backlog. We unfortunately have no timelines to share at this point. 
As a workaround, instead of using set, use addAsync (Office.context.mailbox.item.to.addAsync 
). In this case, only the new values will be added but the old ones will not disappear. 
But please note this will also not add any email ids which have special characters in them because of the current bug.
 
Internal tracking id: Office: [4345223]

**Comment by shighosh-msft** [comment]
This issue has been fixed. Thank you for raising the issue and helping us make the product better.
