### ISSUE TITLE
Office Add-ins - Admin Managed - Excel on the web - Error: Cannot connect to catalog

### ISSUE THREAD

**Issue by mhmostafa88** [OfficeDev/office-js#4145]
## My Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: __Office on the web____
* Host [Excel, Word, PowerPoint, etc.]: ___Excel___
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): __Google Chrome Version 121.0.6167.160 (Official Build) (arm64)____
 
## Expected behavior
We have deployed an Excel-Add in via the Microsoft 365 admin center -> Integrated apps.

These should be able to be seen when opening "Get Add-ins" in an Office-application -> Admin Managed.
I should either see the app that i deployed, or i should see "No add-ins currently available".

## Current behavior
We have an issue with seeing connecting the 'Admin Managed' tab. It shows the error "Cannot connect to catalog" when opening "Add-ins" in Excel Online.

## Steps to reproduce

1- deploy an app using this guidance https://learn.microsoft.com/en-us/microsoft-365/admin/manage/office-addins?view=o365-worldwide#deploy-your-office-add-ins (i have the xml file availabe for you if it will help for you to examine it).
2- go to "Get Add-ins" in an Office-application -> Admin Managed

## Link to live example(s)
This is the manifest xml file link
https://staging.app.mightydigits.com/excel-addin-app/manifest.xml

# Provide additional details
Tenant ID: dfc6459d-335f-40b9-a8b8-da963f5503f9
Affected user email alias.: budgetting@mightydigits.com
Time duration of the error (in the last 30 days): i believe i have never seen any other message given to me when i go to 'Admin Managed' tab.

## Context
We're trying to deploy an Excel Add-in for our organization.
The local development of the app is working properly, but we're unable to make it available through the centralized deployment of the admin center.
I tried re-deploying it again today after waiting for 20 hours.
<img width="1953" alt="image" src="https://github.com/OfficeDev/office-js/assets/71451021/d9d8bded-5bd2-43be-b4a0-fdd0f787fb4b">

**Comment by zhenhuangMSFT** [comment]
Hi @AkhileshShah-MS, could you please take a look? Thanks!

**Comment by AkhileshShah-MS** [comment]
Hi @mhmostafa88 Thanks for reaching out, and apologies for delay in response. Are you still facing the issue? If yes, can you please share a screenshot of message you are seeing when launching in-client store? 
@akshayta23 looks like some issue in connecting to store catalog. Can you please look into this?

**Comment by AkhileshShah-MS** [comment]
@mhmostafa88 Closing this issues due to no further update. Please feel free to raise another Issue if you face this in future.

**Comment by mjm1979-cpu** [comment]
@AkhileshShah-MS 
I am still getting exactly same issue. 

I have added my Add-in in Microsoft admin centre --> integrated app
I used to see the add-in under "Admin managed" tab. Recently I could not see it and it shows the error "Cannot connect to Catalog"

I am accessing Office 365 in Chrome. 
Chrome Version 133.0.6943.59 

O365 version: 16.0.18605.42301
