### ISSUE TITLE
Testing add-in on mobile

### ISSUE THREAD

**Issue by noamshark** [OfficeDev/office-js#4148]
We have checked the box to make our add-in available on iOS and Android, but every time we publish it, the certification team sends it back to us for fixes. The problem is that we can't test it on mobile before publishing, so we're unsure how to resolve the issues. How can we see and test our add-in on mobile before publishing it?

**Comment by manuelsidler** [comment]
You can sideload your add-in on mobile platforms:
* iPad (Word, Excel, PowerPoint): https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad
* iOS and Android (Outlook): https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-mobile-addins

**Comment by noamshark** [comment]
Thank you, the. issue is that we don't see the add-in icon in our mobile. When I click on Add-ins I don't see ours to add on mobile. I do see it on my Outlook web and desktop. @manuelsidler

**Comment by manuelsidler** [comment]
@noamshark did you add `MobileFormFactor` and the `MobileMessageReadCommandSurface` extension point to your manifest? Have you set a default min version of the Mailbox requirement set <= 1.5?

**Comment by noamshark** [comment]
Actually our add-in should show on compose and not reading mode. do you know anything about that? @manuelsidler

**Comment by noamshark** [comment]
As per your comment, yes we did add that. @manuelsidler

**Comment by manuelsidler** [comment]
@noamshark Only read mode and some exceptions are supported on mobile platforms:
> In general, only Message Read mode is supported at this time. That means MobileMessageReadCommandSurface is the only [ExtensionPoint](https://learn.microsoft.com/en-us/javascript/api/manifest/extensionpoint#mobilemessagereadcommandsurface) you should declare in the mobile section of your manifest.

Source: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-mobile-addins#whats-different-on-mobile

**Comment by besiler** [comment]
Closing this issue with the doc link provided by @manuelsidler. Thank you! 

@noamshark  please let us know if you have other questions. You can also request support for your use case in mobile using the feature request here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
