### ISSUE TITLE
categories.addAsync returns error in OnMessageSend event (Office on the web)

### ISSUE THREAD

**Issue by manuelsidler** [OfficeDev/office-js#4150]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: macOS 14.3.1
* Browser (if using Office on the web): Edge
 
## Expected behavior
When calling `Office.context.mailbox.item.categories.addAsync` inside an OnMessageSend event, I expect the category to be added.

## Current behavior
`Office.context.mailbox.item.categories.addAsync` returns the following error:
```json
{
    "name": "Host Error",
    "message": "The operation is not supported.",
    "code": 5000
}
```

The error occurs only in Office on the web. It works fine on Outlook for Mac.

## Steps to reproduce
1. Add LaunchEvent extension point to the manifest with the OnMessageSend event
2. Call `Office.context.mailbox.item.categories.addAsync` inside the event handler
3. Open Outlook in a web browser
4. Send an email

**Comment by ajays-msft** [comment]
@manuelsidler Setting categories in compose mode is not supported in Outlook Web. 
https://learn.microsoft.com/en-us/javascript/api/outlook/office.categories?view=outlook-js-1.8#outlook-office-categories-getasync-member(2)

If you think this support is essential, please feel free to create a feature request.
We track Outlook add-in feature requests on our[Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process

**Comment by manuelsidler** [comment]
@ajays-msft that's a bummer, but thank you for the information. I created a feature request on the Tech Community Page: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-support-for-item-category-management-in-outlook-on-the-web/idi-p/4067075#M2330
