### ISSUE TITLE
Signatures appear as attachments when sending outside of Outlook with an Add-in

### ISSUE THREAD

**Issue by victorcalarasu** [OfficeDev/office-js#4151]
# Provide required information needed to triage your issue
We have a custom add-in which does some validations and adds some headers on the email then sends the email to the recipients if everything passes the validations. We believe it could be something from the send function. Could it be something else?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows
* Browser (if using Office on the web): Chrome, Firefox, etc.
 
## Expected behavior

When adding a signature with pictures the signature images appear as attachments when sending to a gmail, yahoo address or any other mailing platform.

## Current behavior

The signatures appear as attachments when sending outside of Outlook, but in Outlook it looks alright (also sent folder etc.)

## Steps to reproduce

1. Add a signature with images
2. The add-in does the validations
3. Send the email via the add-in

## Link to live example(s)

This is how our send function looks, we don't really change anything about the email other than setting some headers and checking recipient numbers, attachment size, etc.
        axios.post(
            Office.context.mailbox.restUrl + `/v2.0/me/messages/${parsedId}/send`,
            {},
            {         
                headers: {
                Authorization: 'Bearer ' + authToken,
                'Content-Type': 'application/json'
                }
            }
            );

## Context

Is this issue known or could it be because of something we do in the code? Do you have any idea? Thanks for the help.
I can provide extra information if needed.

**Comment by ajays-msft** [comment]
@victorcalarasu - From what I see, you are doing some processing in rest URL. If you can isolate specific code you are using to set signature, I can help you further. 
Other things that could help is
1) Are you able to repro this in other platforms?
2) Clear sample code to repro the issue
3) Repro video / images

**Comment by victorcalarasu** [comment]
I don't use any code to send the signature, I set it manually in the email from Outlook. I cannot reproduce this on desktop, only on web. I can maybe make a recording if you think that would be helpful.

**Comment by DivyaPatidar** [comment]
@victorcalarasu From what I understand you are setting signature using [signature Office js api ](https://learn.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-preview#outlook-office-body-setsignatureasync-member(1)) and then sending mail from Add-in using REST Api. Can you try sending mail manually and see if this issue happens?
Also can you confirm if set signature using native Outlook signature instead of Office JS API, do you see same behaviour?

**Comment by victorcalarasu** [comment]
If I send the email manually the issue doesn't occur. I also set the signature manually, not through any code.

**Comment by mmanjaree-msft** [comment]
Is it possible to share a video fo the issue? @victorcalarasu

**Comment by victorcalarasu** [comment]
https://github.com/OfficeDev/office-js/assets/58118772/45242b68-4bce-4e87-9dcf-2eb5db579044

I made this recording showing all the code and doing the flow in which the signature gets recognised as an attachment when sent to gmail. A thing to note is that if I send via outlook (so to another outlook email address, this doesn't happen, it just shows the signatures and no attachments).

**Comment by shighosh-msft** [comment]
Hi @victorcalarasu, thanks for sharing the video. The signature is getting added manually and not by using the office-js signature api, the send part is also being done using Outlook Mail Rest API, could you please confirm where the office-js apis are involved here so that we can help resolve it?

**Comment by victorcalarasu** [comment]
It seems that the issue is somehow caused by the Outlook Mail Rest API, and I can see that that rest URL property is included in the office-js package. We're using this endpoint: Office.context.mailbox.restUrl + `/v2.0/me/messages/${parsedId}/send`

**Comment by shighosh-msft** [comment]
Hi @victorcalarasu, thanks for confirming, this forum is limited to supporting office-js apis. For Outlook Mail Rest API - please refer here: here:
[outlook-dev-docs/docs/rest/index.md at main · OfficeDev/outlook-dev-docs (github.com)](https://github.com/OfficeDev/outlook-dev-docs/blob/main/docs/rest/index.md)
