### ISSUE TITLE
sessionData.getAsync and sessionData.setAsync are undefined (Outlook on Windows)

### ISSUE THREAD

**Issue by manuelsidler** [OfficeDev/office-js#4154]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2401 Build 16.0.17231.20236
* Operating System: Windows 11
* Browser (if using Office on the web): -
 
## Expected behavior
When in compose mode, I'd expect `Office.context.mailbox.item.sessionData.getAsync` and `Office.context.mailbox.item.sessionData.setAsync` to work properly on Mac, Windows and Office on the web.

## Current behavior
On Outlook for Windows, `Office.context.mailbox.item.sessionData.getAsync` and other methods on `sessionData` are `undefined`:
_TypeError: Office.context.mailbox.item.sessionData.getAsync is not a function_

It works on Mac and Office on the web. It also worked on Outlook for Windows until a couple of days ago.

## Steps to reproduce
1. Add Message Compose extension point with a taskpane button to the manifest
2. Compose a new mail
3. Call `Office.context.mailbox.item.sessionData.getAsync` in your code
4. The error described above occures

## Link to live example(s)
You can also clone this GitHub repo to reproduce the bug on Outlook for Windows: https://github.com/manuelsidler/outlook-addin-multiselect
1. Sideload `manifest.xml`
2. Compose a new mail
3. Open the add-in (Contoso Add-In -> Show Taskpane)
4. Click on _Save Session Data_ or _Get Session Data_

**Comment by carlosb1504** [comment]
Also seeing this issue, Outlook Desktop only. Causing a customer problem in our Live environments. Any updates please?

**Comment by teejay001** [comment]
Hi @exextoc,

We are starting to get quite a few customers calling in and complaining about this. This is staring to look an an urgent fix. Any update please.

Cheers

**Comment by dmitriikashin-outreach** [comment]
We are having the same issue, `Office.context.mailbox.item.sessionData.setAsync is not a function`, Windows Classic client. 
It works fine on New windows client, and other web-based clients.

**Comment by Oleg-O** [comment]
Thanks all for reporting, we're working to mitigate this asap. Our internal tracking id is office:8774024.

**Comment by Oleg-O** [comment]
We've rolled out a change that should fix this and it should propagate to all users within a few hours.

**Comment by manuelsidler** [comment]
@Oleg-O unfortunately, I haven't got the update yet. Which version number should fix the issue?

**Comment by Oleg-O** [comment]
@manuelsidler this was a service change - we've updated office.js libraries on CDN. This should have resolved the issue for all users within hours and had resolved it for some users but oddly not for all - some users are reporting that they are not getting the fixed JS libraries even after hitting CTRL+F5 in the taskpane. We're trying to understand why.

**Comment by Oleg-O** [comment]
An update here. We've pushed another change to the office.js today and we're hoping this should have helped address this issue. Due to complexity of the content distribution system all up and various caching in place, it's a bit hard to estimate how quickly it'll get to everyone. We think it should start having effect by now. It would help if anyone affected could let us know if the issue is being resolved or not and without forcing refresh (ultimately we want to resolve it without asking everyone to force refresh).

**Comment by manuelsidler** [comment]
@Oleg-O the issue has been resolved for us without forcing refresh. Thanks!
