### ISSUE TITLE
Smart Alerts features does not work with site under Cloudflare with mTLS enable.

### ISSUE THREAD

**Issue by ttuyen1529** [OfficeDev/office-js#4157]
We had developed an Outlook add-in that implement SmartAlerts features to capture OnAppointmentSend event.
Everything works like a charm in dev and UAT environment, but when we move to production, we notice that the SmartAlerts features is not working on the production one.
After we take the support from Cloudflare, we see that the Outlook on Desktop (the old one) can not load the Javascript file to the local based on mTLS is turned on on this env.
And the log from Outlook runtime only show the resource for download is unavailable.
So what we can do for now? since turn off mTLS on Cloudflare is only work-arround for this case

**Comment by zhngx1** [comment]
Are you able to load office.js directly in the browser in your production environment?

**Comment by ttuyen1529** [comment]
Of course, yes. I also use the same header that I get from debugging proxy to use with Curl and it still works

**Comment by zhngx1** [comment]
Can you confirm with Cloudflare why accessing or downloading the JavaScript is blocked?
