### ISSUE TITLE
Office.context.platform issue in new oulook version on desktop

### ISSUE THREAD

**Issue by ZabeehUllah** [OfficeDev/office-js#4158]
## Issue Description
I want to access the platform type of outlook I am using, inside my add-in running in outlook. In older version I could know that I am currently using outlook on PC through this `Office?.context?.platform === 'PC'`;  and in case of outlook on the web through  `Office?.context?.platform === 'OfficeOnline'`. However in new outlook version  I am getting  `Office?.context?.platform === 'OfficeOnline'`, both in case of desktop outlook app and outlook running on the web. How can I know the platform type in case of newer outlook version in case of the desktop.

**Previous Outlook version (Desktop**): 16.0.17231.20236
**Current Outlook version (Desktop):** 0.0.0.0 

## Code implementation sample

```
if (Office?.context?.platform === 'PC') {
      authenticator.endpoints.add('PingOne', {
        clientId,
        baseUrl: popupUrl,
        authorizeUrl,
        redirectUrl,
        scope,
        responseType,
        extraQueryParameters,
      });
      authenticator
        .authenticate('PingOne', true)
        .then((token) => {
          const userData = {
            code: token.code.toString(),
            company_id: ssoData?.company_domain_id,
            email,
            appName: currentAppName(),
          };
          isExpiredToken(
            userData,
            API_URL_CALLBACK,
            history,
            {},
            null,
            null,
            null,
          );
        })
        .catch((error) => {
          // Handle failure
          console.log('token error:', error);
          setIsLoading(false);
        });
    } else {
      localStorage.setItem('dell-user', true);
      const tabRef = window.open(
        ssoData.idp_Request_url,
        '_blank',
        'width=800, height=800',
      );
      setPowerappWindow(tabRef);
      powerappWindowRef.current = tabRef;
    }
```
## Sample images of Office instance

1) Outlook Web app Office Instance `(https://outlook.office.com/mail/inbox/....)`
![officeWeb](https://github.com/OfficeDev/office-js/assets/22549491/de3ed0f4-ccc5-4172-b8b4-25938e503e6d)

2) Outlook Desktop app **previous** version
![oldDesktopOutlook](https://github.com/OfficeDev/office-js/assets/22549491/6a394c18-661f-4723-8af1-7c167f7e2c4e)

3)  New Desktop Outlook app
![newDesktopOutlook](https://github.com/OfficeDev/office-js/assets/22549491/3dc5065a-05a3-4d62-bd45-d355552e75c6)

4) Try new Outlook option
![newOutlookToggle](https://github.com/OfficeDev/office-js/assets/22549491/1c658410-8ce1-42da-869d-0d72e57e1cd7)

**Comment by ajays-msft** [comment]
@ZabeehUllah Please use Office.context.diagnostics.hostName

https://learn.microsoft.com/en-us/javascript/api/outlook/office.diagnostics?view=outlook-js-preview#outlook-office-diagnostics-hostname-member

**Comment by ZabeehUllah** [comment]
@ajays-msft There's no Diagnostics property directly attached to Office Instance. The above link says use `Office.context.diagnostics` and then add `hostName` to get string type of Outlook client. However, there is no `hostName` property either, it's just `Office.context.diagnostics.host` and it gives string 'Outlook' both in web and client version of outlook. I have attached the screenshots with my initial question.

**Comment by ajays-msft** [comment]
@ZabeehUllah - Please try Office.context.mailbox.diagnostics.hostName

Please let me know if this works for you.

**Comment by ZabeehUllah** [comment]
@ajays-msft Yeah, this `Office.context.mailbox.diagnostics.hostName` worked. Please do update it in the documents. Thank you so much for your help.

**Comment by ajays-msft** [comment]
@samantharamon - FYI

**Comment by samantharamon** [comment]
The behavior @ajays-msft provided is documented in [Office.context.mailbox.diagnostics](https://learn.microsoft.com/javascript/api/outlook/office.mailbox#outlook-office-mailbox-diagnostics-member). The note mentioned in Office.Diagnostics provides an alternative for acquiring similar information.
