### ISSUE TITLE
Insertion into Outlook Web and New Outlook desktop has wrong text alignment and missing icon

### ISSUE THREAD

**Issue by Gabriel2048** [OfficeDev/office-js#4159]
## Your Environment
* Platform: PC laptop
* Host: New Outlook and Web Outlook
* Office version number: Microsoft Outlook Version 1.2024.207.500 (Production). Client Version is 20240209002.12 .
* Operating System: Windows10 (version 22H2)
* Browser (if using Office on the web): Both Chrome & Microsoft Edge
 
## Expected behavior
HTML alignment is preserved when insertion is performed with `setSelectedDataAsync`. All icons (including svg) should be inserted.

## Current behavior
Alignment of text elements its wrong. Elements that are supposed to be aligned to the start (left) are centered. Svg element is not inserted.

## Steps to reproduce
1. Use the attached HTML file (in the zip file)
2. In new Outlook or Outlook Web insert it using `Office.context.mailbox.item.body.getTypeAsync`
3. Observe all inserted html is center aligned.
4. Observe the missing "X" (Twitter) icon at the bottom.

## Link to live example(s)
https://gist.github.com/Gabriel2048/41d5b7f2fadc8d982082d02c334db2b6

## Context
This is causing issues for the customers of our Addin, as HTML elements are inserted with unexpected issues.

## Useful logs
- [x] Screenshots
- [x] Test file (if only happens on a particular file)
On the left side we can see the original HTML, on the right side we see the inserted HTML within Outlook.
![Differences](https://github.com/OfficeDev/office-js/assets/60075087/e43b36df-64f5-47f2-b0a9-90fa62f53b82)
[OriginalHtml.zip](https://github.com/OfficeDev/office-js/files/14372877/OriginalHtml.zip)

**Comment by ajays-msft** [comment]
@Gabriel2048 - Each Outlook client has a specific wrapper built around rooster, so it maybe possible few HTML attributes work fine in some clients but not in all. 

As a general rule you should prefer CSS styles over HTML attributes.

You can try out this rooster editor to check different styles: https://microsoft.github.io/roosterjs/index.html#api/insertContent

**Comment by Gabriel2048** [comment]
@ajays-msft 
This ("few HTML attributes work") is not pointed out in any documentation and it makes the API unpredictable. Our expectancy is that any valid HTML file should work as expected. Changing from HTML attributes to CSS styling is not an option for us as we are generating the HTML using ASPOSE.

**Comment by ajays-msft** [comment]
@Gabriel2048 - Unfortunately, this is due to complexity of how each of the platforms are implemented.

**Comment by Gabriel2048** [comment]
@ajays-msft 
Does this means this bug will not get fixed and we should communicate to the customer facing this issue that this is an Outlook problem?

**Comment by mmanjaree-msft** [comment]
@Gabriel2048 Thanks for bringing this up. There are two things here firstly SVG is not supported, so please avoid using it with addin apis. There is a documentation gap which we will fix. Same for the alignment issue. Inline styles are not guaranteed to work inside mail editor and behavior might differ between platforms. We will update details of this as well in documentation.

**Comment by BenoitJimini** [comment]
@mmanjaree-msft  Any update on the documentation gap that you planned to fix 2 years ago?
