### ISSUE TITLE
[Excel]office add-ins change pivottable name error

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#416]
when change pivotTable.dataHierarchies  name , excel closed and nothing message throw.

the javascript i use

 <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js" type="text/javascript"></script>

    <script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js" type="text/javascript"></script>

    <script src="https://unpkg.com/core-js@2.4.1/client/core.min.js" type="text/javascript"></script>

my code belown

Excel.run(function (context) {

            const pivot = context.workbook.worksheets.getItem("WeeklyDataPivot").getRange("B20");

            context.workbook.worksheets.getItem("WeeklyDataPivot").pivotTables.add("SecondPivot", "weeklyDataTable", pivot);

            return context.sync().then(function () {
                const pivotTable = context.workbook.worksheets.getItem("WeeklyDataPivot").pivotTables.getItem("SecondPivot");
                return context.sync().then(function () {
                    pivotTable.rowHierarchies.add(pivotTable.hierarchies.getItem("ReportDate"));
                    pivotTable.dataHierarchies.add(pivotTable.hierarchies.getItem("Spends"));
                    pivotTable.dataHierarchies.add(pivotTable.hierarchies.getItem("sales"));
                    pivotTable.dataHierarchies.add(pivotTable.hierarchies.getItem("Spends_Prior"));
                    pivotTable.dataHierarchies.add(pivotTable.hierarchies.getItem("Sales_Prior"));
                    pivotTable.dataHierarchies.add(pivotTable.hierarchies.getItem("Impressions"));
                    pivotTable.dataHierarchies.add(pivotTable.hierarchies.getItem("Clicks"));
                    pivotTable.dataHierarchies.add(pivotTable.hierarchies.getItem("Clicks_Prior"));
                    pivotTable.dataHierarchies.add(pivotTable.hierarchies.getItem("Impr_Prior"));

                    pivotTable.dataHierarchies.load("no-properties-needed");
                    return context.sync().then(function () {
                        pivotTable.dataHierarchies.items[0].name = "Spends ";
                        pivotTable.dataHierarchies.items[1].name = "sales ";
                        pivotTable.dataHierarchies.items[2].name = "Spends_Prior ";
                        pivotTable.dataHierarchies.items[3].name = "Sales_Prior ";
                        pivotTable.dataHierarchies.items[4].name = "Impressions ";
                        pivotTable.dataHierarchies.items[5].name = "Clicks ";
                        pivotTable.dataHierarchies.items[6].name = "Clicks_Prior ";
                        pivotTable.dataHierarchies.items[7].name = "Impr_Prior ";

                        return context.sync();
                    });
                });
            });

        }).catch(function (error) {
            console.error(error);
        });

**Comment by JuaneloJuanelo** [comment]
@dinglicoding  i think this issue is fixed, i tried changing the datahierarchies and it seems to be working.

can you please: make sure Excel is updated with the latest release, try it again?

i have a script lab snippet you can probably reuse: https://gist.github.com/JuaneloJuanelo/1d2dd92496acbf53aea09c6ce38eb789

check our the addValues or the changeHierarchyNames() methods...

if you still see this issue please send me your office build number.
thanks!

**Comment by JuaneloJuanelo** [comment]
Issue is confirmed to be fixed.
