### ISSUE TITLE
Fetch all links from all shapes in a document efficiently

### ISSUE THREAD

**Issue by dhoelzl** [OfficeDev/office-js#4160]
Is there a possibility to efficiently fetch all links from all shapes in a document?

The links are stored in `/word/_rels/*.rels` package parts, e.g. `/word/_rels/document.xml.rels` for the main content in the form of

`<Relationship Id="*" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink" Target="<the link URL to be fetched>" TargetMode="External"/>`

The only way that I know how I can do this is by fetching the OOXML of the whole document via `context.document.body.getOoxml()` and then scanning it for the appropriate package parts and `Relationship` entries which is quite slow and inefficient especially on large documents.

Is there e.g. a possibility to directly access the contents of `/word/_rels/document.xml.rels`?

Accessing all hyperlink ranges of a document, e.g. via `context.document.body.getRange("Content").getHyperlinkRanges()` does not yield the links of shapes in a document.

Thank you and regards,
Dominik

**Comment by zhenhuangMSFT** [comment]
Hi @dhoelzl, thanks for raising the issue! Unfortunately it is not supported currently. You are encouraged to post your feature requests or upvote related requests on https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform.
