### ISSUE TITLE
Uncaught (in promise) TypeError: s.getAsync is not a function when calling Office.context.mailbox?.item?.sessionData?.getAsync

### ISSUE THREAD

**Issue by SethDG** [OfficeDev/office-js#4162]
# Provide required information needed to triage your issue

Yesterday, we received reports from our customers with this error:

`Uncaught (in promise) TypeError: s.getAsync is not a function`

That error was being thrown by this line of code:

```
		Office.context.mailbox?.item?.sessionData?.getAsync('enableLaunchEvent', function (res) {
			console.log(`[Launchevent] is${res.value ? '' : ' not'} enable.`)
		})
```

This code has been live and available in production and in use since January 30, 2023

But yesterday, we got our first reports of an error the morning of February 22, 2024.

So more than a year later, this code started throwing an error

The error was eventually resolved by adding an optional chaining (?.) operator after the getAsync, i.e.:

```
		Office.context.mailbox?.item?.sessionData?.getAsync?.('enableLaunchEvent', function (res) {
			console.log(`[Launchevent] is${res.value ? '' : ' not'} enable.`)
		})
```

I personally was never able to reproduce this error.  No one on my team was able to reproduce this error.  But many of our end users did.

Was there a change in Outlook or an issue in OfficeJS that could have caused this issue?

## User 1 Reported Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2311 (build 17029.20140 Click-to-run)
* Operating System: Windows 11
* Browser (if using Office on the web): N/A

## User 2 Reported Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook for Microsoft 365 MSO (Version 2402 Build 16.0.17328.20068) 64-bit
* Operating System: Windows 11
* Browser (if using Office on the web): N/A

## User 3 Reported Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2402 Build 17328.20004 Click-to-run)
* Operating System: Windows 11
* Browser (if using Office on the web): N/A
 
## Expected behavior

I would have expected a line of code that has worked without an error for over a year to continue to do so

## Current behavior

The line in question throws the error "getAsync is not a function" prior to us adding an optional chaining (?.) operator after the getAsync
Currently, there is no error

## Steps to reproduce

I don't currently have repro steps, but if you need me to try and come up with something, let me know

## Link to live example(s)

I don't have a link to a live example

# Provide additional details

## Context

* This caused an add-in to fail to run for many but unknown number of users.  It is currently working for them after the patch.
* My end users are asking for an RCA for the failure that was reported yesterday so I'm trying to understand the problem and be able to explain it to them
* Also, need to understand what happened so we know if there are any other potential issues we need to look for or things to avoid in the future

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by SethDG** [comment]
An interesting data point, but the team strongly believes is a red herring, a new version of our package was approved shortly before the initial problem was reported.  It's curious, but probably unrelated.  The package is here: https://partner.microsoft.com/en-us/dashboard/office/products/6d16e3ac-a76c-410b-9d12-cf56863df9c6/overview

**Comment by SethDG** [comment]
Additionally, before this code is run, there is a check done to make sure this code should be safe:

```
	get isSupportSessionData() {
		try {
			return officeoutlook.isSetSupported?.('Mailbox', '1.11') && !!officeoutlook.sessionData;
		} catch (error) {
			return false;
		}
	}
```

**Comment by Oleg-O** [comment]
I believe this is the same issue as https://github.com/OfficeDev/office-js/issues/4154.
