### ISSUE TITLE
Office.context.mailbox.item.addFileAttachmentFromBase64Async fails if base64 string is larger than 27892122 bytes

### ISSUE THREAD

**Issue by pabloglombovsky** [OfficeDev/office-js#4163]
Hello,
I am developing an office web addin for Outlook.
If I call addFileAttachmentFromBase64Async  and the base64 string is larger than 27892122 bytes then it fails.
It's the same in OWA or Outlook Desktop.
It's a hardcoded limit in this function: "function Cr(e)":
![image](https://github.com/OfficeDev/office-js/assets/83715814/11034ef9-9573-48ef-9b6b-03351715a284)

This is the error:
![image](https://github.com/OfficeDev/office-js/assets/83715814/0eaf362f-797b-4a24-9bd1-6a3d4366919c)

In my opinion Outlook should allow larger attachments... if you manually add a 20 MB file, you can do this. I think up to 35 MB it should be allowed (in fact you can add an attachment of any size now in Outlook).

If you use addfileattachmentasync then you don't have such limitation. Both functions should behave the same way.

Thanks

**Comment by ajays-msft** [comment]
Thank you for the input. This is will considered as a new feature request.
We track Outlook add-in feature requests on our[Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
