### ISSUE TITLE
Cannot sideload a plugin on Outlook For The Web

### ISSUE THREAD

**Issue by SmartArray** [OfficeDev/office-js#4165]
# Unable to sideload our Add-In, so we are unable to test it

## Your Environment
* Platform Mac + iOS, Office on the web
* Host: Outlook
* Office version number: Latest stable release + Cutting Edge 16.82.1 (24021813)
* Operating System: Mac OS Sonoma 14.2.1 (23C71)
* Browser (if using Office on the web): Version 121.0.2277.128 (Official build) (arm64)
 
## Expected behavior
A menu should exist that allows us to sideload an Add-In that we developed.

## Current behavior
After spending hours of searching for the right button mentioned in the docs, we are unable to sideload an Add-In that we developed in-house.

Neither with the secret URL that I found in a devlog (https://aka.ms/olksideload) nor the User Interface allow navigating to the install panel, as the ribbon for "Get Add-Ins" is simply empty.

When visiting the url https://aka.ms/olksideload it asks to sign-in, but nothing happens, it will just navigate the user to the inbox. Visiting it again also just shows the inbox.

We also tried the above mentioned Desktop Client of Office Outlook on Mac.  We could not find the button mentioned in the docs, however, Tools > Get Add-Ins navigated us to the correct window. It doesn't allow us to install the manifest, it exits with "Installation failed - Sorry, we can’t complete this operation right now. Please try again later"

We are unable to examine logs of any kind. The Mac OS app "Console" does not show anything relevant. 

Even with

```
defaults write com.microsoft.Outlook  CEFRuntimeLoggingFile -string /tmp/outlook.log
```

## Steps to reproduce
Visit https://aka.ms/olksideload

The install panel will not open.

## Link to live example(s)
-

# Provide additional details
-

## Context
We are trying to develop a useful Add-In for our customers for a video conferencing system similar to zoom.

## Useful logs
In the dev console of Edge I can see the following 404s (I doubt they are relevant, but still wanted to post them):

- 404 - https://outlook.live.com/imageB2/v1.0/users/msftpc%40microsoft.com/image/resize(width=120,height=120,allowResizeUp=true)
- 404 - https://outlook.live.com/imageB2/v1.0/users/azuredevops%40microsoft.com/image/resize(width=120,height=120,allowResizeUp=true)
-

**Comment by besiler** [comment]
@SmartArray thank you for the very detailed question! 

I want to confirm as a first step: have you waited a very, very long time after clicking https://aka.ms/olksideload for the sideload experience to load? The inbox may appear first, with the "Add-ins for Outlook" modal not showing up for some time. 

I just tried this and it worked: 
1. Opened https://aka.ms/olksideload in Edge
2. It SSO'd me in
3. The Outlook icon appeared
4. I waited a few minutes
5. The add-ins modal appeared

For the add-in failing to load on Mac, could you take a fiddler trace? That might help us figure out what's going on there

**Comment by SmartArray** [comment]
Thank you for the response @besiler 

How many minutes are we talking about? I am just testing it now and it behaves as you mentioned:
It SSOs me in, the outlook icon appears, the inbox shows but after a few minutes I still don't see the modal.

I found those in the console log:

```
[Info] Successfully preconnected to https://res.cdn.office.net/
[Error] Failed to load resource: the server responded with a status of 404 () (pwa.json, line 0)
[Error] Unrecognized Content-Security-Policy directive 'require-trusted-types-for'.

[Error] Refused to load https://js.monitor.azure.com/scripts/c/ms.shared.analytics.mectrl-3.gbl.min.js because it does not appear in the script-src directive of the Content Security Policy. (x2)
[Info] Successfully preconnected to https://res-1.cdn.office.net/
[Error] Unrecognized Content-Security-Policy directive 'require-trusted-types-for'. (x2)

[Error] Failed to load resource: the server responded with a status of 404 () (resize(width=120,height=120,allowResizeUp=true), line 0)
[Error] Unrecognized Content-Security-Policy directive 'require-trusted-types-for'.

> Selected Element
< <div class="h8rWN">…</div>
[Error] Failed to load resource: the server responded with a status of 404 () (meInlineBackCompat.min.js.map, line 0)
```

Not sure if the issue is related to the log statements?

What can I do to help you troubleshoot the issue?

I can indeed try to provide you a fiddler log by the end of this week!

**Comment by ajays-msft** [comment]
@SmartArray - The errors you pointed out from console are not related to the issue. I cannot repro this in multiple test accounts.

You should look at network logs and find if there are any errors in your setup. Look for any calls that contain *store*.

**Comment by SmartArray** [comment]
Did I miss something about how to enable this? What are the requirements to see the modal? Do I need a special account for that? Sorry for the stupid question.. I tried multiple accounts too

**Comment by ajays-msft** [comment]
@SmartArray - There are no special requirements. It just takes about 30 sec to show the store popout window. You can try using consumer account and see if it is coming for you. If it is not coming in enterprise account, likely the store is disabled by admin.
https://answers.microsoft.com/en-us/outlook_com/forum/all/disable-store-add-ins-in-outlook-owa/23f0b2cc-9c48-49b8-8a1c-9bb9dd1512f2
