### ISSUE TITLE
sessionData object is a function in 16.02 version of library

### ISSUE THREAD

**Issue by rcorrederalsi** [OfficeDev/office-js#4167]
**Article URL**
[Office.sessionData](https://learn.microsoft.com/en-us/javascript/api/outlook/office.sessiondata?view=outlook-js-preview)

**Describe the problem**
We're using sessionData object in our production and it seems that on version 16.02 of the library, it's not an object but a function.

**Screenshots**
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/48475564/9f46e3f8-082d-4789-a231-fdb12a90d8b7)
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/48475564/d38ca312-48d4-4a7e-bf76-e32668d44033)
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/48475564/ba5fad98-28c8-4db9-8d0c-4dfb070fdd74)

**Comment by AlexJerabek** [comment]
Hi @rcorrederalsi,

Thanks for reporting this issue. It appears to be a product bug. I'll transfer this issue to the [office-js repo](https://github.com/OfficeDev/office-js) where it can be investigated further by the product team.

**Comment by Oleg-O** [comment]
I believe this is the same issue as https://github.com/OfficeDev/office-js/issues/4154.
