### ISSUE TITLE
MS Word 2019 Task Pane Add-in using React fails to load in Windows Desktop, Office 2019.

### ISSUE THREAD

**Issue by sasif2280** [OfficeDev/office-js#4168]
# What happening.

**I have creacted a basic Add-in with the steps given in  https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator wih Yeoman generator with react. but Add-in could not loaded in  Windows Desktop, Office 2019.**
# Expected behaviour 

**The Add-in should load properly in word 2019**

# Steps to reproduce 

1. Generate MS Word TaskPane Add-in using Yeoman generator with react template.
2. Run npm start
3. Try to open Add-in in newly opened window of MS Word 2019 standard.

## Environment

* **Platform** PC desktop
* **Host Word**: 2019 standard
* **Office version number**: Microsoft word 2019 MSO (16.0.10407.20032) 64 bit
* **Operating System**: windows 10

## Link to live example(s)
here is github repo to see webpack and other configuration 
https://github.com/sasif2280/test_Addin

## Context
We have lots of users who uses old versions for MS Word they could not use our Legal Assist Addin.
We need to solve this issue for target users which impacting business.

## Useful logs
![image](https://github.com/OfficeDev/office-js/assets/61416943/8fdb0f9f-3557-47f6-9a7d-06e4cfab2598)
![image](https://github.com/OfficeDev/office-js/assets/61416943/08f19261-2626-4590-8fd8-96dd788cd74b)

**Comment by zhenhuangMSFT** [comment]
Hi @sasif2280, thanks for reporting the issue! Does this script work well on the latest builds?

**Comment by sasif2280** [comment]
Hi @zhenhuangMSFT what do you meant by latest build?

**Comment by zhenhuangMSFT** [comment]
Hi@sasif2280 , you mentioned that 

> We have lots of users who uses old versions for MS Word they could not use our Legal Assist Addin.

And the test add-in does not work on Word 2019. Did you try other builds that we release monthly or semi-annually?

**Comment by sasif2280** [comment]
I have tried this with word Microsoft® Word for Microsoft 365 MSO (Version 2308 Build 16.0.16731.20496) 64-bit 
it works fine also works on web.

**Comment by zhenhuangMSFT** [comment]
Thanks for the additional information provided. Did you try delete the node_module folder and npm install & run again? Could you tell us more about how the Legal Assist Addin cannot be used on older versions of Word? What is the add-in behavior?

**Comment by sasif2280** [comment]
Hi @zhenhuangMSFT 
yes i did delete the node_module folder and did npm install but still the same issue is there
and regarding how we found this issue...
one of our user who uses word 2019 raised a issue so we get to know about this issue.

**Comment by zhenhuangMSFT** [comment]
Hey @sasif2280, we had a regression recently and just got it fixed. Could you check if your issue still persists?

**Comment by sasif2280** [comment]
I the issue for me still persists...
![image](https://github.com/OfficeDev/office-js/assets/61416943/b7197aa8-353c-4336-9512-4ae302df2445)

**Comment by sasif2280** [comment]
Hi @zhenhuangMSFT do you have any update on this issue yet??

**Comment by shanshanzheng-dev** [comment]
Hi @sasif2280 We'll be looking into this issue and will report back if we have a suggestion for you. Thanks.

**Comment by shanshanzheng-dev** [comment]
Hi @sasif2280 We'e trying to repro this issue. In order to triage this issue, if possible, could you provide a trace file, such as error massage or log? Could you provide us your test add-in or repro video? Thanks.

**Comment by shanshanzheng-dev** [comment]
Hi @sasif2280, this is probably because we don't support Edge in Office 2019. To verify what version of the browser you are using you can click on the personality menu and chose Security Info. 
![image](https://github.com/OfficeDev/office-js/assets/125014206/53194de4-2c3d-48d8-a964-1657d36e74a1)
This will display the version of the runtime you are using:
![image](https://github.com/OfficeDev/office-js/assets/125014206/be682971-81f0-4344-8a73-9f2af712f993)
The issue is because Yeoman doesn't transpile the javascript for older versions of the runtime.

**Comment by sasif2280** [comment]
Hi @shanshanzheng-dev Thanks for the update 
in my case my office version is 
Microsoft word 2019 MSO (16.0.10407.20032) 64 bit which has **runTIme : ie  and webview (trident).**

**Comment by sasif2280** [comment]
> Hi @sasif2280 We'e trying to repro this issue. In order to triage this issue, if possible, could you provide a trace file, such as error massage or log? Could you provide us your test add-in or repro video? Thanks.

for test addin I have followed these steps 
you can refer  https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?tabs=yeomangenerator

**Comment by shanshanzheng-dev** [comment]
Hi @sasif2280 Your runTIme version is ie and webview (trident), right? I'm afraid that Yeoman doesn't transpile the javascript for this versions of the runtime. 
We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform), We value your feedback, Thanks.

**Comment by sasif2280** [comment]
@shanshanzheng-dev 
I have tried the steps to Support older Microsoft webviews and Office versions provided in documentation
here is link but still this is not work for me..  
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/support-ie-11?tabs=ie
I have tried the sample addin code for transpilation.

if you could please try to add those babel or polyfill configuration to this or any simple addin once and try to load addin again then it might be helpfull for me.  
Thank you.

**Comment by shanshanzheng-dev** [comment]
Hi, @sasif2280, in general we do transpile and polyfill the code in our generated projects to work with trident, but the fluent and react libraries had to be updated and the current libraries force the use of more current versions of ecma syntax standards that are not supported in trident.  You could install older versions of react and fluentui and make the project work, but that is not something we support out of the box. 
When you run 'yo office' you are presented with a list of template options.  Among those are the basic taskpane project and the react project.  The react template doesn't work in 2019, but the others should work just fine. That's to say, besides the second, other templates work fine.
![image](https://github.com/user-attachments/assets/f639330f-665f-4117-a3da-b9711d33a6dd)
 @Rick-Kirkham could you please help to confirm why the documentation is not working? Thanks.

**Comment by Rick-Kirkham** [comment]
The React project created by the Yeoman generator uses Fluent UI version 9, which is not compatible with the Trident webview control. If you need to support Office 2019, we recommend that you start by cloning the sample at: [Office-Add-ins-Fluent-React-version-8](https://github.com/OfficeDev/Office-Add-ins-Fluent-React-version-8). 

Our article at [Use Fluent UI React in Office Add-ins
](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/fluent-react-quickstart) has this information. I will also add it to the article [Excel QuickStart React](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-react).

**Comment by sasif2280** [comment]
@Rick-Kirkham @shanshanzheng-dev 
Thanks for the update I will try to follow suggested steps.
Hope for the best!!
