### ISSUE TITLE
unable to search sentence in word  with track changes enabled 

### ISSUE THREAD

**Issue by maxwellfargoseCactus** [OfficeDev/office-js#4170]
# Provide required information needed to triage your issue

I am trying to find the sentence in Word but am not finding it, as my track changes are enabled and some text has already been replaced.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___Mac___
* Host [Excel, Word, PowerPoint, etc.]: ______Word
* Office version number: __Latest____
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior

 need to find and highlight that text on word 

## Current behavior

<img width="587" alt="image" src="https://github.com/OfficeDev/office-js/assets/49706940/89927c77-1c8c-4a24-93e4-6705c5e113c0">

## Steps to reproduce

1.  Add sentence as :  For participants who were at higher risk of dysphagia, an oral intake plan was also provided.
2. then enable track changes with option **"Show all revision inline"** then replace 'For participants who were at higher risk of dysphagia, an' with 'An' and  then add ' for participants at a higher risk of dysphagia' at last after 'provided'

3. then try to find text. 
# Provide additional details

 const searchOptions = {
    ignorePunct: true,
    ignoreSpace: true,
    matchCase: false,
    matchPrefix: false,
    matchSuffix: false,
    matchWholeWord: false,
    matchWildcards: false,
  };
const sentence= "An oral intake plan was also provided for participants at a higher risk of dysphagia."
    const rangeCollection = context.document.body.search(
      sentence,
      searchOptions,
    );

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Searion** [comment]
Thanks for reaching us. This is by design. In trackChange mode, these contents are not really deleted.

**Comment by maxwellfargoseCactus** [comment]
In that case how to find particular string then ?

**Comment by Searion** [comment]
@maxwellfargoseCactus try this Api range.getReviewedText(changeTrackingVersion) and then you can get the content and search or modify.
