### ISSUE TITLE
How long does is take for an Office Web AddIn to be installed in user profiles when using Integrated Apps deployment? 

### ISSUE THREAD

**Issue by gbl-Time** [OfficeDev/office-js#4171]
Posting here - don't know where else to post. 

Can anybody explain what is to be expected in terms of time it takes before Office web AddIn's (in this case for Outlook) will be available for the end users? 

A while back we could manually sideload directly in the user's profile and this would take effect almost immediately. That changed completely and we have moved away from directly sideloading. 

Now we are deploying from "Integrated Apps" but it still takes an unknown amount of time before addin's are available. 

For example we uploaded a manifest file on 22nd of february at 13:00 for selected users and on 23rd of february at 13:00 still none of the users have the web addin added to their profiles. 

When uploading a manifest file it is stated that it can take up to 12 hours for the addin to be available but that is not what we experience. 

Thanks in advance for your thoughts and inputs.

**Comment by gbl-Time** [comment]
Further to this: 

Today tuesday 27th of february the Office Web AddIn has become available. Since it happened over the weekend I can't be sure how long time it actally took but certainly much more than 24 hours. 

Next observation/problem: 

I activated the Office Web AddIn and within a few hours it became active in Desktop Classic Outlook. 

However, the Office Web AddIn does not become active in Outlook Webmail at the same time. It also does not become active if I switch to Desktop New Outlook. Does anyone know why there's such a difference in time and how long it can take before Outlook Webmail and Desktop New Outlook are updated too?

**Comment by ajays-msft** [comment]
@gbl-Time Here is the documentation for further reference.

https://learn.microsoft.com/en-us/microsoft-365/admin/manage/office-addins?view=o365-worldwide#prepare-to-deploy-and-manage-office-add-ins-via-integrated-apps

**Comment by gbl-Time** [comment]
Thanks. 

When uploading manifest file through Integrated Apps the interface returns an up to 12 hour deployment time. Documentation elsewhere states 24 hours. In  our experience it takes longer. Plus, the delay in activating the addins in the actual user profiles in New Outlook and Outlook webmail. Quite confusing and challenging to schedule and plan deployment in large environments.

**Comment by ajays-msft** [comment]
@gbl-Time - Thank you. Will pass on the feedback to the product management team.

**Comment by gbl-Time** [comment]
@ajays-msft Thank you. I appreciate that.

**Comment by cody-lettau** [comment]
Yes - we see that at times it takes up to 72 hours. This is pretty frustrating from a deployment standpoint (especially for QA teams).
