### ISSUE TITLE
Outlook does not notify user about add-in update

### ISSUE THREAD

**Issue by ericvaladas** [OfficeDev/office-js#4173]
There is no prompt or notification in Outlook that the add-in has been updated after the add-in has been published to the store. We have updated our add-in twice now and both times there has been no notification. We can see the latest version in the store. 
Does this functionality require special configuration in our manifest.xml? Does support for the notification need to be implemented in our task pane code? 

## Your Environment
Outlook on Mac, iOS, Outlook on the web.
 
## Expected behavior
According to this [FAQ](https://learn.microsoft.com/en-us/partner-center/marketplace/appsource-submission-faq#what-happens-when-i-update-my-app-to-a-new-version-in-microsoft-appsource-) we expected a notification to appear in the task pane that prompts the user to update the add-in.

## Current behavior
No notification is shown.

## Steps to reproduce
1. Submit updated Outlook add-in for review
2. Get add-in approved
3. Publish add-in
4. Open add-in in Outlook
5. There is no indication of an update

# Provide additional details
- Our Outlook add-in is a task pane add-in created with the Yeoman generator
- We are updating the version in the manifest.xml for each update

## Context
Our users will not know that there is a new version or know how to update to the latest version.

**Comment by ajays-msft** [comment]
There is no mechanism currently available in Outlook to notify addin updates. 

However, we appreciate the input. This is will considered as a new feature request.
We track Outlook add-in feature requests on our[Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by jmasci** [comment]
@ajays-msft Thank you for the response. Perhaps the [Microsoft Office documentation](https://learn.microsoft.com/en-us/partner-center/marketplace/appsource-submission-faq#what-happens-when-i-update-my-app-to-a-new-version-in-microsoft-appsource-) could be updated to specify that Outlook is not included when it states the following:
> What happens when I update my app to a new version in Microsoft AppSource?
> …
> When an existing customer launches the updated app for the first time, a notification appears either in the task pane or the body of the document that prompts the user to update their app. When the user chooses Update, the latest version of the app launches.

Or is there something we misunderstood about the statement? Do you know if there is any documentation that covers Outlook specific updates?

**Comment by samantharamon** [comment]
@jmasci We're looking into this further internally, so that we can clarify notification behavior of add-in updates in Outlook. We'll update this thread once we update the documentation.

**Comment by samantharamon** [comment]
Thanks for your patience, @jmasci and @ericvaladas. We added a note to the article in https://github.com/MicrosoftDocs/partner-center-pr/pull/7488. The changes have now been merged, so you should see the updates in [Microsoft AppSource submission FAQ](https://learn.microsoft.com/partner-center/marketplace/appsource-submission-faq#what-happens-when-i-update-my-app-to-a-new-version-in-microsoft-appsource-) shortly. I'll go ahead and close this issue, but should you require further assistance, please don't hesitate to open a new issue on GitHub.
