### ISSUE TITLE
wanted to change page size, Margin and Orientation in word js addin

### ISSUE THREAD

**Issue by nadeemAshfaq** [OfficeDev/office-js#4174]
We develop Office.js addins for Word. In this process we have a need to be able to manipulate the following properties of my Word
Margins
Orientation (portrait)
Custom Page size

How can i find the APIs needed to achieve this?

**Comment by Searion** [comment]
Thanks for reaching us. There is no such api now to achieve this. 
For new feature request, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.

**Comment by nadeemAshfaq** [comment]
ok submitted request

**Comment by nadeemAshfaq** [comment]
waiting to get this feature from office team

**Comment by diogofcunha** [comment]
any news on this? Can it be done via ooxml?
