### ISSUE TITLE
item.body is not an instance of Body in Outlook on the Web

### ISSUE THREAD

**Issue by KurtLa** [OfficeDev/office-js#4175]
## Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web, Windows, Mac 16.83
Host: Outlook
Browser: Chrome 121.0.6167.160
 
## Expected behavior
I have all functions available for working with items.

## Current behavior
I do not have the functions available. 
For example: The item.body.prependAsync method call results in a TypeError, indicating that prependAsync is not a function. 

## Steps to reproduce
1. Open Outlook on the web (https://outlook.office365.com/ - https://aka.ms/olksideload).

2.  Add the AddIn
<img width="731" alt="image" src="https://github.com/OfficeDev/office-js/assets/9027932/b0a9fab2-33cb-4267-bc09-9cc05efdc17c">

3. Run it via the message menu
<img width="561" alt="image" src="https://github.com/OfficeDev/office-js/assets/9027932/c249e03b-d76b-4460-ac4b-093fc96f43a3">

4. Observe the error in the browser's console.

# Provide additional details
My HTML:
```
<!DOCTYPE html>
<html>

<head>
  <title>Addin test</title>
  <script src="https://appsforoffice.microsoft.com/lib/1/hosted/office.js"></script>
  <script>
    let item;

    Office.onReady((info) => {
      if (info.host === Office.HostType.Outlook) {
        item = Office.context.mailbox.item;
        console.log(item.body);
        item.body.prependAsync("text", function (asyncResult) {
          if (asyncResult.status === Office.AsyncResultStatus.Failed) {
            console.log("Action failed with error: " + asyncResult.error.message);
            return;
          }

          console.log(`"${'text'}" prepended to the body.`);
        });
      }
    });
  </script>
</head>

</html>
```

My Manifest.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp
  xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
  xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0"
  xsi:type="MailApp">


  <Id>7218ed19-90f5-4ad6-99e8-8d17ee2556</Id>
  <Version>1.0.0.0</Version>

  <Hosts>
    <Host Name="Mailbox" />
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.1" />
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="URL to HTML" />
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteItem</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read" />
  </Rule>
  <DisableEntityHighlighting>false</DisableEntityHighlighting>

  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides"
    xsi:type="VersionOverridesV1_0">
    <Requirements>
      <bt:Sets DefaultMinVersion="1.1">
        <bt:Set Name="Mailbox" />
      </bt:Sets>
    </Requirements>
    <Hosts>
      <Host xsi:type="MailHost">

        <DesktopFormFactor>
          <FunctionFile resid="Commands.Url" />

          <ExtensionPoint xsi:type="MessageReadCommandSurface">
            <OfficeTab id="TabDefault">
              <Group id="msgReadGroup">
                <Label resid="GroupLabel" />
                <Control xsi:type="Button" id="msgReadOpenPaneButton">
                  <Label resid="TaskpaneButton.Label" />
                  <Supertip>
                    <Title resid="TaskpaneButton.Label" />
                    <Description resid="TaskpaneButton.Tooltip" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16" />
                    <bt:Image size="32" resid="Icon.32x32" />
                    <bt:Image size="80" resid="Icon.80x80" />
                  </Icon>

                </Control>
              </Group>
            </OfficeTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>

    <Resources>
      <bt:Urls>
        <bt:Url id="Commands.Url" DefaultValue="URL to HTML" />
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="GroupLabel" DefaultValue="Name" />
        <bt:String id="TaskpaneButton.Label" DefaultValue="Action" />
      </bt:ShortStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>
```

## Context
The issue occurs when trying to use a function like item.body.prependAsync (and many other functions) in an Outlook add-in running on the web. Trying to develop an Outlook add-in compatible with both Outlook on the Web and Outlook 365 for Windows and Mac. The specific goal is to edit and modify certain things in the email.

## Useful logs
```
{type: undefined, getAsync: ƒ}
getAsync: ƒ wt(e)
type: undefined
[[Prototype]]: Object
```
```
Uncaught TypeError: item.body.prependAsync is not a function
    at URLtoHTML/html?et=:14:19 (...item.body.prependAsync("text", function (asyncResult)...)
    at appsforoffice.microsoft.com/lib/1/hosted/office.js:76:23268
    at t (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:22669)
    at appsforoffice.microsoft.com/lib/1/hosted/office.js:76:29316
    at c (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4168)
    at f.waitForFunction (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:4257)
    at e.j [as appReadyCallback] (appsforoffice.microsoft.com/lib/1/hosted/office.js:76:28650)
    at appsforoffice.microsoft.com/lib/1/hosted/outlook-web-16.01.js:20:339988
```

**Comment by ajays-msft** [comment]
@KurtLa This is expected. You are trying to modify the body in a MessageReadCommandSurface.
You need to modify the body in MessageComposeCommandSurface,

For more details as to how you can modify the mail item, see the example below

https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/outlook-tutorial

**Comment by KurtLa** [comment]
Hey @ajays-msft,
Thank you very much for taking the time.

There might be a misunderstanding on my part, but what I aim to achieve includes things like:

- Receiving an email
- clicking on my addin,
- then:
 highlighting certain words in yellow
 adding text fragments
 commenting on things
 etc.
 
For example i receive an email:

```
Hi,
please complete task xxx by Friday.
```

After clicking my addin:
```
Hi,
please complete task xxx by Friday.
-- AddIn Note: 4 tasks due by Friday. Click ([here] for accept) or ([here] for reject).
```

When I change it to MessageReadCommandSurface, I can only activate my addin in "Write new mail / reply / ..." scenarios.


Therefore, I need the ability to manipulate the visible body in the read window. I want to do this inline and not open a new window. My email example is quite basic, but a real-world email can be complex and longer. It doesn't need to be saved permanently, just make the changes on demand.

**Comment by ajays-msft** [comment]
@KurtLa 

Unfortunately this is not possible with the current office js capabilities. 

If you think this support is essential, please feel free to create a feature request.
We track Outlook add-in feature requests on ourTech Community Page. Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process
