### ISSUE TITLE
Swapping from Compose Mode back to Read Mode with a multi selection does not always resume pinned status of add-in

### ISSUE THREAD

**Issue by ashleygagregory** [OfficeDev/office-js#4176]
# Add-in pinned state is not resumed depending on whether a user has a multi selection + has pinned the add-in in a different context/mode

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Monarch + Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Monarch: 1.2024.207.500
* Operating System: Windows 11
* Browser (if using Office on the web): Edge
 
## Expected behavior
When swapping between mail items/selections in Read and Compose Mode, a pinned add-in should always resume it's pinned state.

## Current behavior
Add-in pinned status does **not** persist if you swap to a multi selection in Read Mode if you pinned the same add-in in Compose Mode. When you resume Read Mode you must reduce your selection back down to a single item for the pinned add-in to re-appear, and then you can increase your selection again.

## Steps to reproduce
1. Perform single selection in Read Mode, pin the add-in
1. Start a Compose Mode (new draft email)
2. Start the same add-in and pin it
3. Swap back to your single selection in Read Mode via the tab at the bottom of the screen, add-in pinned state is resumed as expected
4. Perform **multi select** in Read Mode, pin the add-in
5. Start a Compose Mode (new draft email)
6. Start the same add-in and pin it
7. Swap back to your multi selection in Read Mode via the tab at the bottom of the screen, add-in pinned state is **not** resumed
8. If you reduce your selection to 1 email here, the pinned add-in will re-appear, and you can increase your selection again.

## Link to live example(s)
Clone [this repo](https://github.com/ashleygagregory/TestAddIn) and run the add-in using npm + sideload the manifest. 
This is simply an add-in that reads email subjects from multiple items, has the `SupportsNoItemContext` + `SupportsPinning` + `SupportsMultiSelect` options present in Read Mode, and has the `SupportsPinning` option present in Compose Mode.

## Context
A user would expect an add-in to resume it's pinned status as per most other combinations of this scenario. The impact of this bug means the pinned add-in disappears for the user if they happened to pin it in Compose Mode AND they are swapping back to a selection of multiple emails.

**Comment by mmanjaree-msft** [comment]
Thank you for your feedback. We acknowledge the platform inconsistencies across Outlook desktop, web, and new Outlook. While we cannot prioritize an immediate fix, we are actively working towards more consistent experiences. Rest assured, we will address this in future planning cycles based on our product roadmap and goals.
