### ISSUE TITLE
how to increase the speed of  loading office.js

### ISSUE THREAD

**Issue by AlvinNiu** [OfficeDev/office-js#418]
My customer use Excel Add In  in China,but this is very slowly,because of the office.js.Can I improve the speed of loading office.js

**Comment by jargil** [comment]
@AlvinNiu - hey, could you please provide more details? For example, is your customer using Office's CDN for loading Office.js or are they using their own hosting/CDN? Is Office.js the only component that is slow when loading? Are they experiencing this while using Office for Windows, or which platform, or all?

**Comment by sumurthy** [comment]
@alvinniu is there an update to the question? Can you also help us quantify the response times you are seeing?

**Comment by jargil** [comment]
@AlvinNiu - closing as there's been no additional updates to our questions. Please re-activate if this still a question and if there's anything we can do to assist.
