### ISSUE TITLE
Unverified Publisher - How to resolve this issue to publish MS Word Add-In

### ISSUE THREAD

**Issue by celeritas78** [OfficeDev/office-js#4182]
Hi - 

I am trying to deploy MS Word Add-In and running into the issue of '1120.1.3 Unverified Publisher'. 

I did follow these steps and get a blue tick in from of the Publisher name in the App Registration portal. 

> Sign into the [App Registration portal](https://aka.ms/PublisherVerificationPreview) using [multifactor authentication](https://learn.microsoft.com/en-us/entra/identity/authentication/concept-mfa-licensing)
> Choose an app and select Branding & properties.
> Select Add Partner One ID to verify publisher and review the listed requirements.
> Enter your Partner One ID and select Verify and save.

Kindly let me know what needs to be done to resolve this issue. 

Product name:ID-Assist
Product ID:97a72627-8f7a-4307-8c29-731273d726a0
Status:Attention needed
Publisher name:ASTERIAL TECHNOLOGIES LLP

Display name
:
[ID-Assist]

Application (client) ID
:
a9fd5d0a-c10e-4d4a-a3d8-498406e80f67

Object ID
:
be9b850c-7727-4926-9129-20308cf81f5a

Directory (tenant) ID
:
875c09ed-63f5-4bce-b666-b46d10e19dc5

Thanks!

Sandeep Khomne 

<img width="747" alt="image" src="https://github.com/OfficeDev/office-js/assets/109657740/0817f046-f4fa-4472-8e75-5a7554fcfe54">

**Comment by zhenhuangMSFT** [comment]
Hi @celeritas78, thanks for reporting the issue! We will get back to you shortly.

**Comment by celeritas78** [comment]
> Hi @celeritas78, thanks for reporting the issue! We will get back to you shortly.

hi - any updates on this?

**Comment by zhenhuangMSFT** [comment]
Hey @celeritas78, our record shows that the publisher is in pass state. Do you still have any issues with this?

**Comment by celeritas78** [comment]
Yes, I can see the blue tick in front of the publisher in the app registration portal. However, in the certification report, this issue is still logged - Kindly suggest a resolution.

<img width="445" alt="image" src="https://github.com/OfficeDev/office-js/assets/109657740/7dbf7f48-02c7-4a8a-9cea-e582a966a88f">

**Comment by celeritas78** [comment]
Hi - Can you please get back on this?

**Comment by zhenhuangMSFT** [comment]
Hi @celeritas78, sorry for the delay. I have double confirmed with our validation team and there is nothing pending from our end. I would suggest reaching out directly to the site where you feel not right. Thanks for your understanding!
