### ISSUE TITLE
OnMessageCompose event doesn't call event handler in Old Windows Outlook

### ISSUE THREAD

**Issue by sangaman** [OfficeDev/office-js#4186]
# `OnMessageCompose` event doesn't call event handler in Old Windows Outlook

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2401 Build 16.0.17231.20236) 64-bit
* Operating System: Windows 11
 
## Expected behavior

`OnMessageCompose` event handler is called when composing a new message.

## Current behavior

`OnMessageCompose` event handler is not called when composing a new message.

## Steps to reproduce

1. Use Old Outlook with the version above on a Windows 11 PC
2. Specify a function in the add-in manifest to handle the `OnMessageCompose` event.
```xml
 <LaunchEvent Type="OnMessageCompose" FunctionName="onMessageComposeHandler"/>
```
3. Open a message to compose.
4. Observe that the event handler has not been called.

# Provide additional details

This behavior is only observed on old Windows Outlook, it works as expected on Mac and new Windows. This was working as of a couple of weeks ago and recently broke. The `OnNewMessageCompose` event also appears to be affected.

**Comment by timwan10** [comment]
Can you include your entire manifest, and the JS file? that repros the issue?

It is likely because Old Outlook uses a JS engine and not a webview for Launch Events you have incompatibilities. Have you enabled runtime logging and debugged the add-in to see if there are any issues?

**Comment by Robirob20** [comment]
I have the same problem, i can´t make the launchEvent work with onMessageCompose.

**Comment by strtob** [comment]
I have also the same problem - is ms working on that?

**Comment by jameschheng** [comment]
I am having the same problem on Windows and Mac.
