### ISSUE TITLE
[Excel] Chart dataRange Can Use PivotTable Data

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#419]
When I Create A Chart. 

 const sheet = context.workbook.worksheets.getItem("WeeklyDataPivot");
    const sheet1 = context.workbook.worksheets.getItem("Sample");
 const data= sheet.getRange("B18:B18");
const chart= sheet1.charts.add("Line",data,"Auto")
chart.setPosition("H1","N20");
chart.legend.position="Bottom";

chart.dataLabels.format.font.size=15;
chart.dataLabels.format.font.color="black";

await context.sync()

data is a pivotTable Cell,i found the chart's series display  all pivotTable Column HeaderName.
can i get the Specified two columns of PivotTable's Data?

thanks

**Comment by RuoyingLiang** [comment]
The PivotTable and PivotChart share the same layout. Changes to one affect the other, so they're always in sync, so a chart cannot only based on part of the PivotTable. If you want to only display specified two columns of PivotTable's data, you can filter the Pivot table to those two columns. Or you can have the data source in range or normal table and bind to specific columns.
