### ISSUE TITLE
`OnMessageFromChanged` not working for  send on behalf and shared inbox

### ISSUE THREAD

**Issue by andreyvcita** [OfficeDev/office-js#4193]
## Your Environment
* Platform Mac
* Host: Outlook
* Office version number: 16.82.1
* Operating System: mac os 13.5 
 
## Expected behavior

`OnMessageFromChanged` triggering  for delegated accounts

## Current behavior
if I change email from another account in`From:` `OnMessageFromChanged` triggered as expected but if I delegated email for 'send on behalf'  `OnMessageFromChanged` **NOT** triggered 
<img width="1547" alt="Screenshot 2024-02-29 at 12 59 15" src="https://github.com/OfficeDev/office-js/assets/61542122/37fd6757-261d-47b5-9231-d3de2dc13248">

## Manifest:

```
<ExtensionPoint xsi:type="LaunchEvent">
    <LaunchEvents>
         <LaunchEvent Type="OnNewMessageCompose" FunctionName="funcA" />
         <LaunchEvent Type="OnNewAppointmentOrganizer" FunctionName="funcA" />
         <LaunchEvent Type="OnMessageFromChanged" FunctionName="funcA" />
     </LaunchEvents>
     <SourceLocation resid="Autorun" />
</ExtensionPoint>
```

**Comment by ajays-msft** [comment]
@andreyvcita - Can you please collect logs and provide the incident id? Please collect logs while you are reproing the issue.

https://learn.microsoft.com/en-us/outlook/troubleshoot/diagnostic-logging/how-to-enable-logging-in-outlook-for-mac

**Comment by DivyaPatidar** [comment]
@andreyvcita Can you also confirm if you have enabled [SupportsSharedFolders](https://learn.microsoft.com/en-us/javascript/api/manifest/supportssharedfolders?view=common-js-preview&source=recommendations) in your manifest?

**Comment by andreyvcita** [comment]
@DivyaPatidar yes 
```
<DesktopFormFactor> 
  <SupportsSharedFolders>true</SupportsSharedFolders>
    <ExtensionPoint xsi:type="MessageComposeCommandSurface">
        ...
     </ExtensionPoint>


     <ExtensionPoint xsi:type="LaunchEvent">
        <LaunchEvents>
          <LaunchEvent Type="OnNewMessageCompose" FunctionName="func" />
          <LaunchEvent Type="OnNewAppointmentOrganizer" FunctionName="func" />
           <LaunchEvent Type="OnMessageFromChanged" FunctionName="func" />
         </LaunchEvents>
        <SourceLocation resid="id" />
     </ExtensionPoint>
</DesktopFormFactor>
```

**Comment by andreyvcita** [comment]
looks like it works after submitting to store but not working if I install add-in manually with manifest file
