### ISSUE TITLE
Limiting platforms in the manifest.xml of an outlook addin

### ISSUE THREAD

**Issue by carlosknowee** [OfficeDev/office-js#4194]
I would like to know how I can limit the manifest.xml of an Outlook addin so that it cannot be installed on Office for Mac until some platform-specific issues are resolved.

**Comment by ajays-msft** [comment]
@carlosknowee - There is currently no way to do it. You can alternatively check for platform within your addin, and provide appropriate message to user in the addin frame. 

You can use the combination of 
`Office.context.mailbox.diagnostics.hostName`  and `Office.context.mailbox.diagnostics.hostVersion` to detect that addin is running in Outlook Mac.

**Comment by carlosknowee** [comment]
Thank you for your response. I wanted to try to limit it so that the Addin could be published in AppSource until we find the solution to the other related issue: https://github.com/OfficeDev/office-js/issues/4196

**Comment by ajays-msft** [comment]
Thanks @carlosknowee. Closing the issue as the question is answered.
