### ISSUE TITLE
Excel Online - Deleting sheets doesn't always work

### ISSUE THREAD

**Issue by Danwakeem** [OfficeDev/office-js#42]
It seems that deleting sheets does not always work in Excel online. It is strange because the function I have posted here works 100% of the time on the desktop Excel client and only works intermittently on Office online. 

## Expected Behavior
I expected the worksheet.delete() function to always work when supplying a valid sheet when trying to delete a sheet online.

## Current Behavior
Calling worksheet.delete() works the first time you load the Excel online webpage (Not the task pane the entire page) then doesn't work again until you reload the entire Excel online page.

## Steps to Reproduce, or Live Example
I have a sample delete function deployed on AWS so here is a link to the [manifest file](https://s3.amazonaws.com/ks2-office-test/test-manifest.xml) that way someone can run this function and verify the bug... or let me know I am doing something wrong ;) 

* Additional details:
  1. Create a few sheets so they can be deleted after clicking the run button. (Or don't, I am creating a new sheet and deleting all the old sheets so it should remove the default sheet then create a new sheet)
  2. Load this manifest for the desktop client and it works fine
  3. Load this manifest in Office online and it only works the first time the page loads?

## Context

I am trying to build a report add-in for a client and we would like our run report button to remove all of the previous reports before creating the new report and they have accountants that use Excel online as their main driver.

## Your Environment

* Platform: Office Online, Mac, PC Desktop
* Host: Excel
* Office version number: Excel 2016 1705, and Excel Online
* Operating System: Windows 10, Windows 7, MacOS
* Browser (if using Office Online): Chrome, Edge, IE 11

## Useful logs

The only error I am getting in Office online is a generic one.
```
{
   "name":"OfficeExtension.Error",
   "code":"GeneralException",
   "message":"An internal error has occurred.",
   "traceMessages":[],
   "innerError":null,
   "debugInfo":{
      "code":"GeneralException",
      "message":"An internal error has occurred."
   }
}
```

**Comment by lindalu-MSFT** [comment]
@Danwakeem Hi, and thanks again for taking the time to report this issue. It's been a while and we believe this issue has been resolved. I'm going to go ahead and close this issue. If you feel it still persists and needs to be re-triaged, please open a new issue. Kind regards, linda
