### ISSUE TITLE
"onChanged" event does not trigger on cells filled by the list data validation in an Excel Worksheet

### ISSUE THREAD

**Issue by cyrelk** [OfficeDev/office-js#420]
When a user selects a value defined by a data validation list nothing happens ; the onChanged event is not triggered. The event is triggered if the user put the cursor in the entry box and press enter or (s)he deletes the new entry for example. All other modifications (new manual entries, modifications, deletions) do trigger this event.  

## Expected Behavior
Selecting a value in a cell from a list validation data should trigger the onChanged event.

## Current Behavior
Nothing happens and that's my problem :)

## Steps to Reproduce, or Live Example
Create a validation list from a source and assign this validation to a cell or a range , then select a value. I think that the onChanged event should be triggered. Deleting the value triggers this event. In fact any manual entry triggers the event.

## Context
Any cell with list validation in an Excel worksheet

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1902 build 11328.20146 
* Operating System: Windows10
* Browser (if using Office Online): N/A

## Useful logs
Nothing to show, no errors in the console, no warnings, , nothing.
- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by weshi** [comment]
Thanks for reporting this issue. We have verified and reproduced this issue. This is a bug and we have a fix for it. The roll out to production will take some time. Will update you once it's available.

**Comment by weshi** [comment]
This issue has already been fixed. Closing this issue. Thanks.
