### ISSUE TITLE
Outlook Desktop, setSelectedDataAsync inserts HTML and ignores font size

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#4202]
# Provide required information needed to triage your issue
In an Outlook add-in for compose mode, we use the item.body.setSelectedDataAsync() method to insert HTML in the body of an item. The setSelectedDataAsync() inserts 11pt text instead of 12pt.

## Your Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: Version 2401 (Build 17231.20236)
* Operating System: Version22H2 (Build 19045.4046)
* Browser (if using Office on the web):
 
## Expected behavior
The setSelectedDataAsync method shall insert HTML with the specified text size.

## Current behavior
The setSelectedDataAsync method ignores the style attribute and inserts text with a font size of 11pt.

## Steps to reproduce
1. Open the add-in's pane and execute the following code:
`Office.context.mailbox.item.setSelectedDataAsync("<p class=\"MsoNormal\"><span style=\"font-size: 12pt; font-family: 'Times New Roman', Times, serif;\">Must be Times New Roman, 12pt.</span></p>", { coercionType : "html" `})`

2. As you can see, the font family was applied, but the font size was ignored.

# Provide additional details
1. The issue is reproducible only in the classic Outlook desktop.

## Useful logs
- [ X ] Screenshots
![image](https://github.com/OfficeDev/office-js/assets/28924916/2c2d6262-7ee3-4390-87c9-c82f66ce5ee9)

**Comment by ztcdsb** [comment]
Thank you for the additional context. We are reaching out to the Microsoft Word team for additional guidance and awaiting their response. Internal tracking ID: 5401672

**Comment by DmitryKostochko** [comment]
Please reopen the case because the bug is still reproducible in Outlook version 2406 (Build 17726.20126).

**Comment by mygraddca** [comment]
Please reopen the case because the bug is still reproducible in Outlook version 2411 (Build 18227.20162).
