### ISSUE TITLE
Inline-styles ignored on Outlook Desktop (Mac and Windows)

### ISSUE THREAD

**Issue by stejura-sfdc** [OfficeDev/office-js#4203]
# Provide required information needed to triage your issue
When using `Office.context.mailbox.item.body.setAsync` method to insert HTML in the body of an item, inline-styles are ignored on Outlook Desktop (Mac and Windows) platform, but preserved in Outlook on the Web (OWA).

## Your Environment

* Platform: PC desktop, Mac
* Host: Outlook
* Office version number: 16.82.218.1 (24021813)
* Operating System: macOS Sonoma 14.3
* Browser: N/A
 
## Expected behavior
Inline-styles should be preserved and inserted as-is into the body of an item. The styles are preserved in Outlook on the Web (OWA), but not on the desktop clients (Outlook on Mac and Windows)

## Current behavior
`Office.context.mailbox.item.body.setAsync` ignores certain inline-styles like `height | width | display` from `anchor` tags (probably other tags too)

## Steps to reproduce
1. Open an add-in pane while composing a new email
2. Execute the following code via the platform's debug console
```
Office.context.mailbox.item.body.setAsync(`<a href="#" style="width:500px; height:100px; border:1px solid black; border-radius:4px; display: block; line-height: 100px; text-align: center; text-decoration: none;">Outlook for Mac</a>`, { coercionType: "html" });
```

## Link to live example(s)
Script Lab YAML: https://gist.github.com/stejura-sfdc/225df7a7938bdcc7edafaff9dc3728ed

# Provide additional details
The issue is only reproducible on Outlook for Mac and Windows.

## Useful logs
- [X] Screenshots

**Outlook for Mac**
<img width="581" alt="image" src="https://github.com/OfficeDev/office-js/assets/53920805/b5d72c3a-0bf3-48df-88c9-f942b929a76f">

**Outlook on the Web**
<img width="754" alt="image" src="https://github.com/OfficeDev/office-js/assets/53920805/7a5fb80f-382d-4062-8064-1672c2c3fe2e">

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ztcdsb** [comment]
Thank you for the additional context. We are reaching out to the Microsoft Word team for additional guidance and awaiting their response. Internal tracking ID: 5401672
