### ISSUE TITLE
CustomFunctions.Error: Office for Mac not supporting custom error messages?

### ISSUE THREAD

**Issue by jankrynauw** [OfficeDev/office-js#4205]
I'm testing throwing an error in a custom function, both registered using Script Lab:
```javascript
/**
 * Testing error message
 * @customfunction
 * @return
 */
async function testErrorMessage() {
  let error = new CustomFunctions.Error(
    CustomFunctions.ErrorCode.invalidValue,
    "My custom error message"
  );
  throw error;
}
```

The above is available as a gist: https://gist.github.com/jankrynauw/56e85aa73aea3bfd3fc2d9f4b707d6bb

Running the above in Office 365 Online within Script Lab I get the following as expected:
![Screenshot 2024-03-02 at 16 48 55](https://github.com/OfficeDev/office-js/assets/18016598/4579e963-56ab-4dab-a86a-aec2858ac7f7)

However, on Office for Mac I only get this: 
![Screenshot 2024-03-02 at 16 51 03](https://github.com/OfficeDev/office-js/assets/18016598/7187fd6d-c4b3-41cd-97ce-68b8984cae3a)

I have also tried the above using a local development environment (i.e. not Script Lab) and see the same issue.

Are custom error messages not supported for Office for Mac?

**Comment by ruijiaMS** [comment]
Hi @jankrynauw,
Thanks for letting us know this issue! For win32 and mac, the content, like "My custom error message", is a hover effect which means if you put your mouse on the yellow triangle on the left side of the cell, you can see the information. Is it your expectation? For excel online, there is a cardview to show the custom error message by populating.

**Comment by jankrynauw** [comment]
Hi @ruijiaMS, that is correct.  Both display the main cardview/popup, it is just the cardview on Office for Mac does not display the actual custom error message ('My custom error message' in the above example)

**Comment by ruijiaMS** [comment]
@jankrynauw The implementation of excel online differs from mac and win32, and there is a specific cardview for excel online, but the custom error message for mac and win32 is on the hover effect. If you would like to the populate the custom error on the cardview for mac and win32 excel, we would like to suggest you to raise a feature request via this helpful link https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform
