### ISSUE TITLE
XML Validation error

### ISSUE THREAD

**Issue by appDevLou** [OfficeDev/office-js#4206]
#Description of the problem
I am developing an Outlook add-in that provides a menu button via the context menu to activate a chatbot in Flowise that serves as an email assistant. The JavaScript/JSON code for the add-in has already been created. However, when I run `npm run validate` to validate the add-in package, I get package validation error messages indicating that the package type cannot be identified and the package does not match the submission type.

##Error messages
1 Packet type not identified: The acceptance test service could not recognise a supported add-in type.
2 Wrong package: My package does not match the submission type. The manifest is marked as invalid.

##Steps to reproduce
1. create a manifest only via yeoman and replace the xml code with mine.
2. execution of `npm run validate` to check package conformance.

##Expected behaviour
I expect the add-in package to be recognised as a valid Outlook add-in and the validation process to complete without error messages.

##Current behaviour
The validation process fails with the above error messages, indicating that the add-in package is not recognised as valid.

#Question
Does anyone have experience with fixing these types of validation errors when developing Outlook add-ins? Are there any specific manifest or package build requirements that I may have missed, especially related to add-ins that enable a chatbot via the context menu?

##Additional information
- The add-in is intended to activate a chatbot in Flowise via a menu button in the context menu.
- The code of the add-in includes both JavaScript and JSON configuration files.
- I have used the latest version of the Yeoman Office Add-In Generator.

Any help or insight into this issue would be extremely valuable. Many thanks in advance!

**Comment by herkulous** [comment]
my Code:
`
<Hosts>
    <Host Name="Mailbox"/>
  </Hosts>

  <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="Mailbox" MinVersion="1.1"/>
    </Sets>
  </Requirements>

  
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:8080/src/taskpane.html"/>
        <RequestedHeight>32</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteMailbox</Permissions>

  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="ReadOrEdit" />
    <Rule xsi:type="ItemIs" ItemType="Appointment" FormType="ReadOrEdit" />
  </Rule>
  <DisableEntityHighlighting>true</DisableEntityHighlighting>

  
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides"
                    xsi:type="VersionOverridesV1_1">
    <Hosts>
      <Host xsi:type="MailHost">
        <DesktopFormFactor>
          
          <ExtensionPoint xsi:type="MessageReadCommandSurface">
            <OfficeTab id="TabDefault">
              
              <Menu id="ContextMenuText">
                <Label resid="ContextMenuText.Label"/>
                <Control xsi:type="Button" id="SendToChatflowButton">
                  <Label resid="SendToChatflowButton.Label"/>
                  <Supertip>
                    <Title resid="SendToChatflowButton.Label"/>
                    <Description resid="SendToChatflowButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ExecuteFunction">
                    <FunctionName>sendTextToChatflow</FunctionName>
                  </Action>
                </Control>
              </Menu>
              
              <Control xsi:type="Button" id="showTaskPaneBtn">
                <Label resid="paneReadButtonLabel"/>
                <Supertip>
                  <Title resid="paneReadButtonLabel"/>
                  <Description resid="paneReadSuperTipDescription"/>
                </Supertip>
                <Icon>
                  <bt:Image size="16" resid="Icon.16x16"/>
                  <bt:Image size="32" resid="Icon.32x32"/>
                  <bt:Image size="80" resid="Icon.80x80"/>
                </Icon>
                <Action xsi:type="ShowTaskpane">
                  <SourceLocation resid="readTaskpaneUrl"/>
                </Action>
              </Control>
            </OfficeTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>
`

**Comment by appDevLou** [comment]
I cant post my code in here and dont know why..

**Comment by herkulous** [comment]
>  <Hosts>
    <Host Name="Mailbox"/>
  </Hosts>

  <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="Mailbox" MinVersion="1.1"/>
    </Sets>
  </Requirements>

  
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:8080/src/taskpane.html"/>
        <RequestedHeight>32</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteMailbox</Permissions>

  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="ReadOrEdit" />
    <Rule xsi:type="ItemIs" ItemType="Appointment" FormType="ReadOrEdit" />
  </Rule>
  <DisableEntityHighlighting>true</DisableEntityHighlighting>

  
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides"
                    xsi:type="VersionOverridesV1_1">
    <Hosts>
      <Host xsi:type="MailHost">
        <DesktopFormFactor>
          
          <ExtensionPoint xsi:type="MessageReadCommandSurface">
            <OfficeTab id="TabDefault">
              
              <Menu id="ContextMenuText">
                <Label resid="ContextMenuText.Label"/>
                <Control xsi:type="Button" id="SendToChatflowButton">
                  <Label resid="SendToChatflowButton.Label"/>
                  <Supertip>
                    <Title resid="SendToChatflowButton.Label"/>
                    <Description resid="SendToChatflowButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ExecuteFunction">
                    <FunctionName>sendTextToChatflow</FunctionName>
                  </Action>
                </Control>
              </Menu>
              
              <Control xsi:type="Button" id="showTaskPaneBtn">
                <Label resid="paneReadButtonLabel"/>
                <Supertip>
                  <Title resid="paneReadButtonLabel"/>
                  <Description resid="paneReadSuperTipDescription"/>
                </Supertip>
                <Icon>
                  <bt:Image size="16" resid="Icon.16x16"/>
                  <bt:Image size="32" resid="Icon.32x32"/>
                  <bt:Image size="80" resid="Icon.80x80"/>
                </Icon>
                <Action xsi:type="ShowTaskpane">
                  <SourceLocation resid="readTaskpaneUrl"/>
                </Action>
              </Control>
            </OfficeTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>

**Comment by herkulous** [comment]
![Uploading 2024-03-02 (4).png…]()

**Comment by appDevLou** [comment]
![2024-03-02 (4)](https://github.com/OfficeDev/office-js/assets/156189015/f67315a2-6a7a-4cbf-a801-b198249d7c94)

**Comment by appDevLou** [comment]
sorry didnt find another way to present the code

**Comment by Rick-Kirkham** [comment]
Add your complete manifest to your question. Put 3 backticks on the line just above it and 3 backticks on the line just below it. Like the following: 

\`\`\`
Your manifest here.
\`\`\`

**Comment by Rick-Kirkham** [comment]
One thing that's known to cause that message from the validator is having parameter on the icon URL. E.g. `https:\\mysite\myimage.png?whatever=something`

**Comment by appDevLou** [comment]
nice thx, that is a good clue.

```
<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
           xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.1"
           xsi:type="MailApp">

  <!-- Basic Settings -->
  <Id>example id</Id>
  <Version>1.0.0.1</Version>
  <ProviderName>Lou's Event Catering - Cheikh</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Herkulous" />
  <Description DefaultValue="Outlook add-in for advanced text processing with Flowise Chatflow"/>
  <IconUrl DefaultValue="https://localhost:8080/assets/herkulous-icon48.png"/>
  <HighResolutionIconUrl DefaultValue="https://localhost:8080/assets/herkulous-icon80.png"/>
  <SupportUrl DefaultValue="https://www.lous-catering.com/support/addin" />

  <!-- Hosts -->
  <Hosts>
    <Host Name="Mailbox"/>
  </Hosts>

  <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="Mailbox" MinVersion="1.1"/>
    </Sets>
  </Requirements>

  <!-- Desktop Form Factor -->
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:8080/src/taskpane.html"/>
        <RequestedHeight>32</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>

  <Permissions>ReadWriteMailbox</Permissions>

  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="ReadOrEdit" />
    <Rule xsi:type="ItemIs" ItemType="Appointment" FormType="ReadOrEdit" />
  </Rule>
  <DisableEntityHighlighting>true</DisableEntityHighlighting>

  <!-- Version Overrides -->
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides"
                    xsi:type="VersionOverridesV1_1">
    <Hosts>
      <Host xsi:type="MailHost">
        <DesktopFormFactor>
          <!-- Extension Point for Command Surface -->
          <ExtensionPoint xsi:type="MessageReadCommandSurface">
            <OfficeTab id="TabDefault">
              <!-- Context Menu for Text Selection -->
              <Menu id="ContextMenuText">
                <Label resid="ContextMenuText.Label"/>
                <Control xsi:type="Button" id="SendToChatflowButton">
                  <Label resid="SendToChatflowButton.Label"/>
                  <Supertip>
                    <Title resid="SendToChatflowButton.Label"/>
                    <Description resid="SendToChatflowButton.Tooltip"/>
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="Icon.16x16"/>
                    <bt:Image size="32" resid="Icon.32x32"/>
                    <bt:Image size="80" resid="Icon.80x80"/>
                  </Icon>
                  <Action xsi:type="ExecuteFunction">
                    <FunctionName>sendTextToChatflow</FunctionName>
                  </Action>
                </Control>
              </Menu>
              <!-- Task Pane Button -->
              <Control xsi:type="Button" id="showTaskPaneBtn">
                <Label resid="paneReadButtonLabel"/>
                <Supertip>
                  <Title resid="paneReadButtonLabel"/>
                  <Description resid="paneReadSuperTipDescription"/>
                </Supertip>
                <Icon>
                  <bt:Image size="16" resid="Icon.16x16"/>
                  <bt:Image size="32" resid="Icon.32x32"/>
                  <bt:Image size="80" resid="Icon.80x80"/>
                </Icon>
                <Action xsi:type="ShowTaskpane">
                  <SourceLocation resid="readTaskpaneUrl"/>
                </Action>
              </Control>
            </OfficeTab>
          </ExtensionPoint>
        </DesktopFormFactor>
      </Host>
    </Hosts>
    <Resources>
      <bt:Images>
        <bt:Image id="Icon.16x16" DefaultValue="https://localhost:8080/assets/herkulous-icon16.png"/>
        <bt:Image id="Icon.32x32" DefaultValue="https://localhost:8080/assets/herkulous-icon32.png"/>
        <bt:Image id="Icon.80x80" DefaultValue="https://localhost:8080/assets/herkulous-icon80.png"/>
      </bt:Images>
      <bt:Urls>
        <bt:Url id="functionFile" DefaultValue="https://localhost:8080/src/triggerChatflow.js"/>
        <bt:Url id="readTaskpaneUrl" DefaultValue="https://localhost:8080/src/Instruktionen.html"/>
      </bt:Urls>
      <bt:ShortStrings>
        <bt:String id="groupLabel" DefaultValue="Meine Add-In Gruppe"/>
        <bt:String id="paneReadButtonLabel" DefaultValue="Instruktionen anzeigen"/>
        <bt:String id="ContextMenuText.Label" DefaultValue="Textverarbeitung"/>
        <bt:String id="SendToChatflowButton.Label" DefaultValue="An Chatflow senden"/>
      </bt:ShortStrings>
      <bt:LongStrings>
        <bt:String id="paneReadSuperTipDescription" DefaultValue="Klicken Sie hier, um die Instruktionen zur Nutzung des Add-Ins anzuzeigen."/>
        <bt:String id="SendToChatflowButton.Tooltip" DefaultValue="Senden Sie den ausgewählten Text an Chatflow, um eine automatische Antwort zu generieren."/>
      </bt:LongStrings>
    </Resources>
  </VersionOverrides>
</OfficeApp>
```

**Comment by millerds** [comment]
Your VersionOverrides xmlns attribute doesn't match it's xsi:type. https://learn.microsoft.com/en-us/javascript/api/manifest/versionoverrides?view=common-js-preview
