### ISSUE TITLE
Behavior of duplicate namespace of custom functions from 2 add-ins

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#4207]
We are adding [custom functions in Excel by JavaScript API](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview) to our existing add-in available in the Microsoft Office Store. We are thinking of the namespace to use.

Here is the question we ask. Let's assume a user has already loaded an add-in to their Excel, which provides custom functions with a namespace `XXX`, what will happen if he loads another add-in which provides the same namespace? Will the two sets of functions be both available to the user?

Another close question. Let's assume a user has already loaded an add-in to their Excel, which provides a custom function named `YYY`, what will happen if he loads another add-in which provides also a custom function named `YYY`? Will the two `YYY` be both available to the user?

**Comment by AkhileshShah-MS** [comment]
Hi @chengtie  ! Thanks for reaching out to us.
Looping in @penglongzhaochina  to help with the issue.
Thanks!

**Comment by MiaofeiWang** [comment]
Hi @chengtie , Excel differentiates functions by id "NAMESPACE + FUNCTIONNAME". 
So for 2 different add-ins with the same namespace, 
- If none of functions of the 2nd add-in conflicts with the 1st one, both 2 add-ins could be installed successfully and work well.
- If there is function's name conflict, the 2nd add-in's functions will install fail. None of the 2nd add-in's functions works.
<img width="361" alt="image" src="https://github.com/OfficeDev/office-js/assets/28795134/25d5f007-9251-45bc-8511-46509c6bd30b">

Hope this information helps.

**Comment by chengtie** [comment]
> Hi @chengtie , Excel differentiates functions by id "NAMESPACE + FUNCTIONNAME". So for 2 different add-ins with the same namespace,
> 
> * If none of functions of the 2nd add-in conflicts with the 1st one, both 2 add-ins could be installed successfully and work well.
> * If there is function's name conflict, the 2nd add-in's functions will install fail. None of the 2nd add-in's functions works.
> 
> <img alt="image" width="361" src="https://private-user-images.githubusercontent.com/28795134/311683772-25d5f007-9251-45bc-8511-46509c6bd30b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzMTI5NzEsIm5iZiI6MTcxMDMxMjY3MSwicGF0aCI6Ii8yODc5NTEzNC8zMTE2ODM3NzItMjVkNWYwMDctOTI1MS00NWJjLTg1MTEtNDY1MDljNmJkMzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDA2NTExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NzdjNDkwNGMyZTVkZGM0MDUzNmVmMjI5NGM5ZTcwMDlmNGNlMWI2MGZmYTljMzk5MjA0NDRlZDllMWQ2MDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hLE8ZadOWvPOy9Ao_kz-gflMDIBptH1XSv56rBXYl10">
> Hope this information helps.

Thank you for the clarification.
