### ISSUE TITLE
Word API Field.updateResult() doesn't work when not executed from task pane add-in

### ISSUE THREAD

**Issue by AlexPeek01** [OfficeDev/office-js#4208]
## Your Environment
* Platform: Office on the web & PC desktop
* Host : Word
* Office version number: 2401 (Build 17231.20236)
* Operating System: Windows 11 Pro
* Browser (if using Office on the web): Chrome
 
## Expected behavior
When calling updateResult() on a field it should update the field to the current custom property value. This should happen regardless from how the function is triggered.

## Current behavior
[Field.updateResult()](https://learn.microsoft.com/en-us/javascript/api/word/word.field?view=word-js-preview#word-word-field-updateresult-member(1)) gets executed but doesn't actually update the field values. It doesn't throw an error, but simply does nothing when triggered from an _ExecuteFunction_ _Action_. When triggered from a _Task Pane_ it works perfectly.

## Steps to reproduce
1. Create an add-in with both a task pane action and an executeFunction action.
2. Create a Word document
3. Add a field to the document (Insert > Quick Parts > Field > DocProperty > {pick any prop that you will be able to update easily, I use Title for testing} )
![image](https://github.com/OfficeDev/office-js/assets/58164081/d9e00b97-803e-432a-b8ba-72172e636207)

5. Execute the following code snippet from both actions. (The task pane can be an empty web app, since the updateResult works when simply pasting the code in the dev tools console).

```js
async function updateAllFields(event) {
    await Word.run(async (context) => {
        // typically we would fetch the custom properties from the API and store them in the custom properties here, 
        // but for you to reproduce this simply rename the file since this will update the Title property that you added to your field.
        context.document.body.fields.load();
        await context.sync()

        var field = context.document.body.fields.getFirstOrNullObject();

        while (true) {
            context.document.body.fields.load();
            await context.sync()

            field.load(["code", "result", "type", "locked", "isNull"]);
            await context.sync();

            if (field.isNull) {
                break;
            }

            field.updateResult();
            field.select();
            context.sync();

            field = field.getNextOrNullObject();
        }
    });

    event.completed();
}
```

## Context
We are building an add-in that gets properties from an API and stores these in the `document.properties.customProperties`. These custom properties are then inserted into a document as a docProperty field. We now have a Ribbon buttons that fetches the up-to-date properties from the API and sets them correctly in the custom properties. However when I iterate over the field collection and call the field.updateResult function, it simply skips over without error and continues.

This behaviour is only when using an _Action_ with type _ExecuteFunction_. If I run the exact same code from a task pane add-in it does work as expected.

## Useful logs
I'd love to provide errors or logs, but I'm not getting any. Everything appears to execute successfully, but the field doesn't update.

**Comment by yilin4** [comment]
@AlexPeek01  https://github.com/OfficeDev/office-js/issues/4050 This issue is similar with yours, you can take a look for reference.
The current supported field type of online Word and desktop Word is like following:
![image](https://github.com/OfficeDev/office-js/assets/107384367/608c5d08-b343-47e2-ae72-0b559c35b437)
