### ISSUE TITLE
Outlook add-in strange behavior on Microsoft® Outlook® for Microsoft 365 MSO (Version 2402 Build 16.0.17328.20124) 64 bit

### ISSUE THREAD

**Issue by elenaaralla** [OfficeDev/office-js#4209]
The addin works fine on OL for MAC and OWA, but fails to send message on OL Desktop of one of my customer.
The strange behavior is that the function Office.context.mailbox.makeEwsRequestAsync()
return asyncResult.status = 'succeeded' in all situations, i.e. on OL for MAC, OWA and OL Desktop, but in the last case messages weren't sent and they remains in draft folder

No errors returned from Office.context.mailbox.makeEwsRequestAsync ()

This is the code in sendFunction.js
```

function Send(itemId, changeKey) {
    var request = '<?xml version="1.0" encoding="utf-8"?>' +
        '<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">' +
        '  <soap:Header><RequestServerVersion Version="Exchange2013" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" soap:mustUnderstand="0" /><X-BugFree-PEC-Auth xmlns="http://tempuri.org/">' + _settings.get("hPin") + '</X-BugFree-PEC-Auth></soap:Header>' +
        '  <soap:Body>' +
        '    <m:SendItem xmlns="https://schemas.microsoft.com/exchange/services/2006/messages" SaveItemToFolder = "true">' +
        '      <m:ItemIds>' +
        '       <t:ItemId Id="' + itemId + '" ChangeKey="' + changeKey + '" />' +
        '      </m:ItemIds>' +
        '       <m:SavedItemFolderId>' +
        '           <t:DistinguishedFolderId Id="sentitems" />' +
        '       </m:SavedItemFolderId>' +
        '    </m:SendItem>' +
        '  </soap:Body>' +
        '</soap:Envelope>';
    try {
        Office.context.mailbox.makeEwsRequestAsync(request, function (asyncResult) {
            if (asyncResult.status !== 'succeeded') {

                var err = asyncResult.error;
                var errMsg = err.name + " - " + err.message;
                console.log(errMsg);

                ShowError(asyncResult.status);
                ShowError("error" + errMsgr);
                return;
            }
            else {

                var xmlDoc = $.parseXML(asyncResult.value);
                $xml = $(xmlDoc)
                $result = $xml.find("m\\:ResponseCode");

                console.log("Message sent!");
                console.log("Send(): asyncResult.status:" + asyncResult.status + "; asyncResult.value:" + asyncResult.value);
                console.log("ResponseCode :" + $result.text()); 
     
                _item.close();
            }
        });
    } catch (err) {
         console.log(err);
    }
}

```

this is the result of async call:
`Message sent! 
Send(): asyncResult.status: succeeded; asyncResult.value:<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="15" MinorVersion="20" MajorBuildNumber="7339" MinorBuildNumber="35" Version="V2018_01_08" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/></s:Header><s:Body><m:SendItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:SendItemResponseMessage ResponseClass="Success"><m:ResponseCode>NoError</m:ResponseCode></m:SendItemResponseMessage></m:ResponseMessages></m:SendItemResponse></s:Body></s:Envelope>
ResponseCode :NoError
`

**Comment by elenaaralla** [comment]
Hi, 
the problem was that OL uses the **_cached mode_**, so the itemId and changeKey in the request were "undefined"!
Disabling the cache mode on OL do the trick.

Is there a way to detect if account has cached mode enabled?
Is there a way to force the synchronization of the message when it was "composed" before make the request of the changeKey?

Thank you,
Elena

**Comment by ndeleuze** [comment]
@elenaaralla there is no way to detect if an account is in cached mode, so whatever approach is taking should be mode-agnostic.

One potential workaround is to take the contents of the email, use makeEwsRequestAsync to create an item on the backend and send it, and then inform the user to discard the email in Outlook.

However, more context on your full scenario would be helpful in giving the best recommendation.
