### ISSUE TITLE
OfficeRuntime.auth.getAccessToken not working for spam addins.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#4211]
# Provide required information needed to triage your issue
I am currently testing the spam addin feature of Outlook. Unfortunately, when I use the OfficeRuntime.auth.getAccessToken() API, the program goes into a hanging state. It is possibly a crash.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:  PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2402 
* Operating System: Windows 10 x64
* Browser (if using Office on the web): NA
 
## Expected behavior

Expected : The spam addin should be able to get a native/bootstrap token. (This used to work a month ago.)

## Current behavior

Actual Behavior : Spam addin hangs and code does not proceed to the 'catch' flow. 

## Steps to reproduce

1. Follow the spam addin tutorial.
2. In the main body of the handler, add the following code : 
```
  OfficeRuntime.auth.getAccessToken().then(nativeToken => {
      console.log('hello success!')
  }).catch(error => {
      console.log('hello failure!')
  })
```
3. Run the code and place breakpoints in both success and catch flows.
4. Program crashes/hangs.

## Link to live example(s)

None

# Provide additional details

None 

## Context

This bug effectively disables GRAPH transactions (failure to do SSO) for our planned addin.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ztcdsb** [comment]
@glr0221 It will help us to diagnosis the issue if you can answer following question:

1. what is the version of Outlook
2. Have you registered your add-in with the Microsoft identity platform?
3. Have you configured a well-known URI?
4. If you have completed the aforementioned steps and are still experiencing the issue, could you please share your manifest/add-in with us?

**Comment by glr0221** [comment]
@ztcdsb Sorry for the missing details. Here are the additional information : 

1. what is the version of Outlook
Microsoft® Outlook® for Microsoft 365 MSO (Version 2403 Build 16.0.17425.20008) 64-bit 

3. Have you registered your add-in with the Microsoft identity platform?
Yes. If I convert my manifest to a non-spam (taskpane) addin with the same appid and all, GRAPH runs correctly.

5. Have you configured a well-known URI?
Yes. It has been configured correctly since the taskpane version of the addin works correctly.

7. If you have completed the aforementioned steps and are still experiencing the issue, could you please share your manifest/add-in with us?
Do you have an email address I can send it to? Thanks.

**Comment by ztcdsb** [comment]
@glr0221 Following our privacy guidelines, we recommend that the user uploads the add-in to a private Git repository and grants access to us(in this case, @ztcdsb).

**Comment by glr0221** [comment]
@ztcdsb closing this ticket since it seems to be a duplicate of https://github.com/OfficeDev/office-js/issues/4104. Thank you.
