### ISSUE TITLE
Excel custom functions calculation issues, clicking Ctrl Alt Shift F9 sometimes does not recalculate

### ISSUE THREAD

**Issue by mmfernand** [OfficeDev/office-js#4214]
There are instances when clicking the Ctrl+Alt+Shift+F9 to recalculate but it does not calculate. As you can see in the screenshot, it has the 'Calculate' message in the status bar, but it does not execute the Execute Functions.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number:  Excel® for Microsoft 365 MSO (Version 2403 Build 16.0.17425.20000 64-bit (Beta Channel) 
* Operating System: Windows 11

 
## Expected behavior
Using Ctrl Shift Alt F9 should always trigger recalculation

## Current behavior
Currently, there are instances when clicking Ctrl Alt Shift F9 does not recalculation.
If you check the screenshot provided, it does not call the ExecuteFunctions.

## Steps to reproduce
An excel file contains several workbooks. Upon opening the file, use Ctrl Alt Shift F9 to recalculate the workbooks.

## Useful logs
<img width="604" alt="image" src="https://github.com/OfficeDev/office-js/assets/161710805/789ba837-a471-49bc-86ec-4526303fd986">

**Comment by mmfernand** [comment]
My beta channel is now in Version 2404 (Build 16.0.17503.20000) and I cannot replicate the issue on the Ctrl+Alt+Shift+F9. It keeps recalculating each time I use that.

Hi @rundongmsft  @zhenhuangMSFT fyi.

**Comment by zhenhuangMSFT** [comment]
@mmfernand Thanks for letting us know! Please feel free to reach out to us if anything off. Thanks!
