### ISSUE TITLE
Spam-reporting Add Ins not appearing in the new Outlook

### ISSUE THREAD

**Issue by navmro** [OfficeDev/office-js#4218]
# Spam-reporting Add Ins not appearing in the new Outlook

I'm trying to develop an Phishing reporting plugin.
The plugin shows up on the old desktop Outlook, on the Office for the web but not on the new desktop Outlook.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number:  Microsoft Outlook Version 1.2024.223.300 (Production).  Client Version is 20240223002.14.
* Operating System: Windows 10 x64 22h2
* Browser (if using Office on the web): 
 
## Expected behavior

The plugin's "Report Spam Message" button should appear instead of the built-in "Report" button.

## Current behavior

The built-in "Report" button is present the new version of Outlook:
<img src="https://github.com/OfficeDev/office-js/assets/142206658/d9255626-032d-4ff5-8777-196c97b111a2" width=50% height=50%>

In Office on the web, the plugin's button correctly appears:
<img src="https://github.com/OfficeDev/office-js/assets/142206658/83680add-9dff-45f5-ab21-f206bfb45db9" width=50% height=50%>

In old desktop Outlook the plugin's button correctly appears:
<img src="https://github.com/OfficeDev/office-js/assets/142206658/d76a4281-2ae2-4f06-ba71-cba1e3911866" width=50% height=50%>

## Steps to reproduce

1.  Create a new Outlook plugin with "yo office"
2.  Follow the documentation from : https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/spam-reporting
3. `npm start`

I've made a small plugin to reproduce the issue which is empty except for the spam reporting.
https://github.com/navmro/antiphishing

## Useful logs

No logs were found in the EventViewer when the new Outlook is launched.
No error, or popup was visible in the new Outlook.

**Comment by navmro** [comment]
Hello, I've seen that the tag "Needs: Author feedback" was added. Do you need anything from me ?

**Comment by ajays-msft** [comment]
@navmro - Integrated Spam reporting addin support is in preview and is not generally available. Currently the timelines are being finalized and please watch out for public documentation for the release announcement.
Until then, you can continue to test your addin in OWA.
