### ISSUE TITLE
Exchange 2019 CU14 download domain error

### ISSUE THREAD

**Issue by mistaslay** [OfficeDev/office-js#4219]
What Broke It:

The basics were to create a new CNAME in your DNS for "download.<domain>.com" and then run a command to configure the URL to be used by exchange. Obviously I did something wrong or I missed something as I'm unable to view or download attachments from OWA at all now.

Symptoms and Behavior:

I am able to download attachments via Outlook without issue. I am able to see that there is an attachment in OWA and it displays accurately (meaning I'm able to tell name, file type, etc.) but neither preview nor "Save AS" work. When single clicking the attachment in OWA it tries to preview, which just opens an empty field to the left but when I click "Download", I'm redirected to
`https://download.<scrubbed>.com/owa/<Email address removed>/service.svc/s/GetFileAttachment?id=AAMkADllZjNhOGY5LTAwZmItNDExOS1hOTM5LTI4ZTBiOWQwZTBiNQBGAAAAAAApfftq7ny4R5DLFHM9RryKBwCyrzpAtRprQpofwfuKuXj8AAAAAAEMAACyrzpAtRprQpofwfuKuXj8AAEui%2BpQAAABEgAQAE4XUSUzR1VDs0QOKUbFlAk%3D&X-OWA-CANARY=Bo5169ua0ESvDNpAL2u3BhDu8h3VAtoIY1E_orjk_pjk0uRXz9fQ0eSFa9NwuMuGMIhZEn8Orp4.&token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Inc3RldnUW5zZngyYW9pMllDZ0UyNGZZc3dqSSJ9.eyJ2ZXIiOiJFeGNoYW5nZS5DYWxsYmFjay5WMSIsImFwcGN0eHNlbmRlciI6Ik93YURvd25sb2FkQHplZXNlcnZlci5jb20iLCJhcHBjdHgiOiJ7XCJtc2V4Y2hwcm90XCI6XCJvd2FcIixcInByaW1hcnlzaWRcIjpcIlMtMS01LTIxLTIyNTU3NTAyMjgtMTM2MjcwNDc1Ny00MjkyNzk5NzM5LTE2MDhcIixcInB1aWRcIjpudWxsLFwib2lkXCI6XCJcIixcInNjb3BlXCI6XCJPd2FEb3dubG9hZFwifSIsImlzcyI6IjAwMDAwMDAyLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMEB6ZWVzZXJ2ZXIuY29tIiwiYXVkIjoiMDAwMDAwMDItMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwL2Rvd25sb2FkLnplZXNlcnZlci5jb21AemVlc2VydmVyLmNvbSIsImV4cCI6MTY0Njk0NDk1NywibmJmIjoxNjQ2OTQ0MzU3fQ.X3xFuUexPl_W0Zl0-6NJ_rH7eANbbFmFYtvev_6q1bZIq-zaKZkjUUnT4qpVO9ydqYb-djkVpEowtpW2s81XdxJCoaX0Vnk-QqvlaZ5WKdcYgQbCnFoDcLiffG73T1nIesrljgSSVH3yomkuyCBkVQAJHlTL__HROLPQReeMlKDqskA6jlQQuTUrtsOpqSDV7m1LFebDjKmTuoS1R1WHn0a9usKMZqYQgLIKSZzX0sD0GA0re4EgNv-HMr1AMqdzTh8Sos2ZYijIooxu96ofeqd2yIiyVVnPUpAxizbVOby34vLdVKTU4bX0StlNZyWgOms_ShZDVXVFhfnR8GkwFw&owa=mail.<scrubbed>.com&isDocumentPreview=False`
which displays
Not Found
HTTP Error 404. The requested resource is not found.

Faced with the same problem as in Tibet 2020, only one user repeats this error, recreating the account and mailbox does not help, compared with identical accounts 0 difference
https://github.com/OfficeDev/office-js/issues/1119

The only thing that helped was the shutdown download domains

**Comment by ajays-msft** [comment]
@pwshnode 
This forum is limited to supporting office-js. For any OWA specific issues, please feel free to send the feedback from OWA directly using the Help-Feedback option. I am guessing it has something to do with Admin configuration, but please explore other documentation as well.
https://techcommunity.microsoft.com/t5/outlook-blog/conditional-access-in-outlook-on-the-web-for-exchange-online/ba-p/267069

No further action from office-js side, so closing the issue.
