### ISSUE TITLE
On a Windows OS desktop version of PPT, when the manifest file is added through Options | Trust Center | Trust Center Settings | Trusted add-in Catalogs, despite checking the "Show in Menu" option, on some systems, the new menu item does not appear unless we manually add the add-in through Home | Add-ins | Get add-ins

### ISSUE THREAD

**Issue by nikhilatsap** [OfficeDev/office-js#4223]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Powerpoint
* Office version number:  Office Desktop build 2308
* Operating System: Windows
* Browser (if using Office on the web): ______
 
## Expected behavior
On a Windows OS desktop version of PPT, when the manifest file is added through Options | Trust Center | Trust Center Settings | Trusted add-in Catalogs, and checking the "Show in Menu" option, after the application is restarted the add-in should appear in the Menu in the top section.

## Current behavior
On a Windows OS desktop version of PPT, when the manifest file is added through Options | Trust Center | Trust Center Settings | Trusted add-in Catalogs, despite checking the "Show in Menu" option, on some systems, the new menu item does not appear unless we manually add the add-in through Home | Add-ins | Get add-ins.

## Steps to reproduce

1. On a Windows OS desktop version of PPT, add an add-in  manifest file through Options | Trust Center | Trust Center Settings | Trusted add-in Catalogs and check the "Show in Menu" option
2. Close the Powerpoint application and open it again
3. Observe that the add-in is not showing in the Menu.(Issue)

# Provide additional details

1. ______
2. ______
3. ______

## Context

Since we are making an add-in for our clients, this makes it difficult for customers to add the add-in through manifest , because due to this the add-in doesn't directly show in the Menu and they have to do an extra step to load it, which impacts customer experience.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by AkhileshShah-MS** [comment]
Hi @nikhilatsap ! Thanks for reaching out. 
Looping in @EsterBergen to help with the issue. 
Thanks!

**Comment by EsterBergen** [comment]
We're investigating this bug and will provide a response when possible. Thanks for submitting!

**Comment by EsterBergen** [comment]
@nikhilatsap - Thanks again for raising this issue. It is by design that the user should go to "Add-ins" and then select the trust center loaded add-in to install. Once you do this, you will be able to see the add-in in the menu.

**Comment by nikhilatsap** [comment]
Thanks for the update. I am happy to accept it as a “behavior by design” if the behavior is consistent in all machines. But, what we find is that on some systems, the add-in appears immediately after adding it in the Trust Center, but on some systems, it requires an additional step of adding the add-in through “Home | Add-ins | Get add-ins” after adding it in the Trust Center

**Comment by EsterBergen** [comment]
Thanks @nikhilatsap - We were unable to reproduce the behavior reported on earlier builds. If you can report an issue in the app, that could allow us to investigate further. Thanks!
