### ISSUE TITLE
Two instances of Redux store are created while using redux toolkit and redux-persist library

### ISSUE THREAD

**Issue by ayush-sopori** [OfficeDev/office-js#4224]
## Your Environment
We have created an outlook AddIn using the office yo-man generator and using event based handlers to get hold of data available within that email. 
The intension is use the redux store across the application to flow data between the launchEvent.js file and the web components in the which are painted in task pane.
 
## Data Flow in application
We are calling an API to fetch the configurations in the messageEvent handler which is present in the launchEvent.js file and storing it the redux store. After that we are passing the data to component so that the validations could be performed and proper UI could be painted accordingly. (component should be re-rendered dynamically).

## Expected behavior
Only one instance of the store should be created and data should be updated in that single store only. 
**Note:** The data is being updated through components as well as through office Event handlers.  

## Current behavior
Two instances are created and data is getting updated in one store. This is cauing inconsistencies in the data updation and while trying to retrive the data we are not able to fetch the current updated store.  

**Store name** - Email Validation Tool 

Screenshot before the the taskpane was opened-
<img width="835" alt="image" src="https://github.com/OfficeDev/office-js/assets/149785597/59ed3e81-ff82-4ebf-ad97-e7abd0a98092">

Screenshot after opening the taskpane-
<img width="909" alt="image" src="https://github.com/OfficeDev/office-js/assets/149785597/3a003f4e-7383-4e9a-8e75-e1a041c1d48b">

**Comment by mmanjaree-msft** [comment]
@ayush-sopori  LaunchEvents and taskpane are different instances of addin. This could be a reason for two stores getting created. For persisting data we have custom properties and roaming settings apis which can be used as described here https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/metadata-for-an-outlook-add-in. Please let us know if these help.
