### ISSUE TITLE
Setting status codes > 299 leads to "add-in error", forcing the user to restart the add-in. This hinders good practices in setting correct status codes in responses. 

### ISSUE THREAD

**Issue by eElor** [OfficeDev/office-js#4227]
# Provide required information needed to triage your issue
Setting status codes > 299 in responses leads to "add-in error", forcing the user to restart the add-in. This hinders good practices in setting correct status codes in responses and confuses users.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 365 MSO (Version 2402 Build 16.0.17328.20124) 64-bit 
* Operating System: windows 11
* Backend serves both the html and assets for displaying most of the pages, but also acts as an API for fetches using javascript.
 
## Expected behavior

Office respects that the server developer has knowledge of web development and can set correct status codes without causing the impression that the add-in is broken on responses with status code > 299.

## Current behavior

Serving pages (not as SPA) with informative status codes higher than 299 lead to and "add-in error":

![image](https://github.com/OfficeDev/office-js/assets/39239890/c783fb99-4f8d-4939-bd5e-fa11d0f88791)

This gives the incorrect impression to the user that the add-in is broken and forces him/her to restart it, disrupting their workflow. 

Alternatives to prevent this are either setting up a SPA or always, but often incorrectly, setting a status code < 299. This enforces bad practices.

As shown in the image, a button for showing an add-in menu overlaps the &times; symbol for closing the popup and makes it even more difficult to ignore the warning.

![image](https://github.com/OfficeDev/office-js/assets/39239890/2db19ab4-9c53-4ff2-96af-5c26e1144940)

## Steps to reproduce

1. Set up a server that returns a page.
2. Set a status code higher than 299 (e. g. 400, simulating a bad request)
3. Open the add-in and request that page.
4. See the annoying pop-up: ![image](https://github.com/OfficeDev/office-js/assets/39239890/c783fb99-4f8d-4939-bd5e-fa11d0f88791)

## Context

Not being able to correctly set status codes that correspond to the logic context in the responses enforces bad practices. Forcing a developer to either set up an add-in as a SPA or always sending responses with status codes < 299 leads to bad practices, a bad developer experience and confused add-in users.

## Useful logs

- [-] Console errors
    - not relevant
    
- [x] Screenshots:
    - ![image](https://github.com/OfficeDev/office-js/assets/39239890/c783fb99-4f8d-4939-bd5e-fa11d0f88791)
    

This issue was closed Won't Fix

**Comment by zhenhuangMSFT** [comment]
Hi @eElor, thanks for your suggestion! We will open an item to track and discuss your suggestion.
