### ISSUE TITLE
Using 'state' as a query parameter breaks Excel Addin w/ Auth0

### ISSUE THREAD

**Issue by ADearingIntlFarming** [OfficeDev/office-js#4229]
# Provide required information needed to triage your issue
When using Auth0 to log in to our production Excel Addin, it spontaneously stopped working yesterday and showed a white screen. After investigation, I determined that if the query parameter `state` is in a callback url, the application breaks.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC, Office 365 Excel, Angular
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2401 Build 16.0.17231.20236) 64-bit 
* Operating System: Windows 11, but bug reproduces on Mac OS as well with multiple users
* Browser (if using Office on the web): N/A
 
## Expected behavior

User should be directed to the login page in the application

## Current behavior

Screen goes white and app freezes with out an error.

I did find a way to code around it in Angular:
```
Office.initialize = (reason) => {
	if (environment.production) {
		enableProdMode();
	}
        //this is the path where I am 'catching' the aut0 redirect
	if (window.location.search && window.location.pathname === '/auth-catch') { 
		// Store the query parameters if necessary
		const queryParams = window.location.search;
		localStorage.setItem(AUTH_REF, queryParams);
	  
		// Replace the current state with the same path but without query parameters
		const newPath = window.location.pathname;
		window.history.replaceState({}, '', newPath);
	  }
	platformBrowserDynamic()
		.bootstrapModule(AppModule)
		.catch((err) => console.error(err));
};
```

## Steps to reproduce

1. Make an Excel Addin with Angular
2. Direct that Angular application to a URL with the query parameter `state`
3. White screen

## Context

This caused an error-less production outage for all of our users with zero changes from our end. Very frustrating.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 

This issue was closed Fixed

**Comment by manaunl** [comment]
I have the same behaviour with Angular application in **Outlook**, but with the different query parameter name `code`. Also I can this parameter before the Angular app is started, but after I redirected to the different page with error `error_description=AADSTS50058%3a+A+silent+sign-in+request+was+sent+but+none+of+the+currently+signed+in+user(s)+match+the+requested+login+hint `

We did not make any changes to the application for months, but suddenly, since yesterday our users experience the error that they can not login, because of this issue. 

 **It is unacceptable, please fix this ASAP**

**Comment by wtravO** [comment]
Can confirm I'm having the same issue. Down in production yesterday and had to write an emergency work around for it. This, overtop of the other breaking change the other day mentioned in #4180 have GOT to get better.

**Comment by manaunl** [comment]
Hi @wtravO, can you share what workaround you implemented to avoid this problem?

**Comment by wtravO** [comment]
> Hi @wtravO, can you share what workaround you implemented to avoid this problem?

It's a bit hacky, but it works for our use case.
```typescript
import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

export const AUTH_REF = 'authRef'

Office.initialize = (reason) => {
	if (environment.production) {
		enableProdMode();
	}

	// fixes a bug where 'state' as a query parameter breaks Excel Addins
	// tried this first with a route guard, but angular wasn't fast enough to intercept Excel breaking
	// https://github.com/OfficeDev/office-js/issues/4229
	if (window.location.search && window.location.pathname === '/auth-catch') {
		// Store the query parameters if necessary
		const queryParams = window.location.search;
		localStorage.setItem(AUTH_REF, queryParams);

		// Replace the current state with the same path but without query parameters
		const newPath = window.location.pathname;
		window.history.replaceState({}, '', newPath);
	}
	platformBrowserDynamic()
		.bootstrapModule(AppModule)
		.catch((err) => console.error(err));
};

// This is part 2 of a fix for Office.js bug causing routing to break
// https://github.com/OfficeDev/office-js/issues/1198
Office.onReady().then(()=>{
Office.onReady().then(() => {
	window.history.pushState = (window as any).originalPushState;
	window.history.replaceState = (window as any).originalReplaceState;
});
```

**Comment by manaunl** [comment]
@zhenhuangMSFT **can you update on the progress ASAP**? It being 3 working days already with the issue that blocks the login.

**Comment by ADearingIntlFarming** [comment]
@manaunl if you look in the original ticket, I have coded a work around that you can use

**Comment by gergzk** [comment]
Hi all, 
This is likely due to a fix for people asking why pushState/replaceState is nulled out in office.js:
https://github.com/OfficeDev/office-js/pull/2808

A fix for that was deployed around March 6, but seems like it has this negative side effect. We'll be reverting the change since this is breaking deployed add-ins, and you'll see the update in the next office.js deployment.
