### ISSUE TITLE
Outlook add-in w/ Edge WebView random scaling issues

### ISSUE THREAD

**Issue by tobiasviehweger** [OfficeDev/office-js#423]
## Expected Behavior
Show the UI in a correctly scaled way.

## Current Behavior
Sometimes, the add-in is scaled incorrectly. My guess is this is related to a different scaling factor on my main and secondary monitor. This is Outlook running on my secondary screen (4k) with scaling factor 1.5 (150%). My main monitor is on my laptop (4k) with a scaling factor of 2.5 (250%). My guess is, it's (incorrectly) taking the scaling factor of the first display. 

## Steps to Reproduce, or Live Example
Does not happen everytime, but consistently. Happens in sidebar UI as well as dialog.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 1904 (16.0.11504.20000)
* Operating System: Windows Insider 19H1 (18353.1)

## Useful logs

![image](https://user-images.githubusercontent.com/2111803/54295432-4b854b00-45b3-11e9-85d2-6135090d4879.png)

**Comment by smaremanda** [comment]
Thanks for reporting this error. We believe this is indeed a bug / error in Edge webview. We are taking a deeper look into it. Will update this thread after our investigation.

**Comment by jargil** [comment]
Thanks for reporting this bug! Indeed this was a bug in our code involving multiple monitors with different scale factors, which I've addressed now.

**Comment by jargil** [comment]
@tobiasviehweger - could you please confirm if you're still seeing this problem with the latest Office build?

**Comment by tobiasviehweger** [comment]
@jargil I've not noticed it anymore I'd also consider this fixed! Thank you!
