### ISSUE TITLE
Outlook WebAddin is not getting loaded for external mail boxes.

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4230]
Description - 
When Outlook WebAddin is published through Office Admin Center for external users e.g. gmail,yahoomail,etc, Outlook WebAddin does not get loaded when logged to outlook through these external accounts.
(Note - Outlook WebAddin can not be published directly by selecting external users, we added external users to DLs and published WebAddin to DL)

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by DivyaPatidar** [comment]
@Sagar-lab1  Can you check if any other add-ins are getting loaded for those accounts? Is it possible for you to share Add-in manifest and network trace?

**Comment by sagar-sonawane9** [comment]
Sure will check if we can publish other web-addins, Meanwhile can you confirm that we can not add external user account to Active Users.
When we add external account to Active Users, It is displayed with #EXT# e.g. If we add "john_carton@gmail.com" under active user then display name is shown as "john_carton@gmail.com" , However email is displayed as "john_carton@gmail.com#EXT#@dlpwinqa.onmicrosoft.com".
Email is displayed as "john_carton@gmail.com" only if we add this user under contact.

**Comment by ajays-msft** [comment]
@Sagar-lab1 - New Outlook does supports addins only in Exchange Online accounts.
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/one-outlook

It is already documented, but we will work on explicitly calling out "no support for non-microsoft accounts" in the documentation. 

@samantharamon - FYI

**Comment by samantharamon** [comment]
@ajays-msft Created https://github.com/OfficeDev/office-js-docs-pr/pull/4471 to clarify this limitation in our documentation.

**Comment by ajays-msft** [comment]
[like]  Ajay Suri reacted to your message:
________________________________

**Comment by sagar-sonawane9** [comment]
Since office documentation ticket is created against this (https://github.com/OfficeDev/office-js-docs-pr/pull/4471) Any further action is expected from out side?

**Comment by shighosh-msft** [comment]
@Sagar-lab1: No, we have updated the docs already. Please let us know if you need any further clarification on this.
