### ISSUE TITLE
Not able to restrict outside organizational users to access Outlook client/OWA

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4232]
Description - 
As an 0365 Administrator, I want to restrict non-organizational users (e.g. Gmail, Yahoomail, etc) to access Outlook client as New Outlook does supports addins only in Exchange Online accounts.

We can restrict exchange online accounts with following steps - https://learn.microsoft.com/en-us/microsoft-365/admin/add-users/remove-former-employee-step-1?view=o365-worldwide#block-a-former-employees-access-to-email-exchange-online

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by ajays-msft** [comment]
@Sagar-lab1 This forum is limited to office-js related queries. For other queries and support please post your questions here - 
https://support.microsoft.com/home/contact
