### ISSUE TITLE
Not able to see any update option for New Outlook.

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4233]
Description - 
We are not able to see any update/disable update option for New Outlook.

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by mmanjaree-msft** [comment]
@Sagar-lab1  This forum is limited to office-js related queries. For other queries and support please post your questions here - 
https://support.microsoft.com/home/contact
