### ISSUE TITLE
we can not add external user account to Active Users.

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4236]
Description - 
we can not add external user account to Active Users.
When we add external account to Active Users, It is displayed with #EXT# e.g. If we add "john_carton@gmail.com" under active user then display name is shown as "john_carton@gmail.com" , However email is displayed as "john_carton@gmail.com#EXT#@dlpwinqa.onmicrosoft.com".
Email is displayed as "john_carton@gmail.com" only if we add this user under contact.

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by ajays-msft** [comment]
@Sagar-lab1 - This forum is limited to Outlook Addins specifically Office/js issues. For other queries and support please post your questions here - 
https://support.microsoft.com/home/contact
