### ISSUE TITLE
'Send on Behalf' settings does not reflect on New Outlook.

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4238]
Description - When user setup 'Send on Behalf' setting on 0365 admin center and tries to send mail on behalf of configured user by using New Outlook client, It gives permission error.

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by ajays-msft** [comment]
@Sagar-lab1 is this related to usage of office js api?

**Comment by ajays-msft** [comment]
This forum is limited to office/js issues. Please feel free to send your feedback directly from Outlook app, if there is any concern related to New Outlook.

**Comment by sagar-sonawane9** [comment]
New Outlook does not allow to send mail on behalf of someone
[send_on_behalf.zip](https://github.com/OfficeDev/office-js/files/14694057/send_on_behalf.zip)

**Comment by Oleg-O** [comment]
I re-iterate on what Ajay said above. This forum is limited to office/js issues. Please feel free to send your feedback directly from Outlook app, if there is any concern related to New Outlook.

**Comment by hserus79** [comment]
This doc page is helpful to configure send on behalf of...
https://support.microsoft.com/en-us/office/allow-messages-to-be-sent-on-your-behalf-when-sharing-a-folder-or-mailbox-afb79d6b-2967-43b9-a944-a6b953190af5
