### ISSUE TITLE
Outlook add-in w/ Edge WebView dialog sizing is wrong

### ISSUE THREAD

**Issue by tobiasviehweger** [OfficeDev/office-js#424]
## Expected Behavior
Correctly size dialogs.

## Current Behavior
Dialogs are not sized correctly (too tall, see screenshots).

## Steps to Reproduce, or Live Example
Open any dialog

## Your Environment

* Platform: PC Desktop
* Host: Outlook
* Office version number: 1904 (16.0.11504.20000)
* Operating System: Windows Insider 19H1 (18353.1)
* Browser (if using Office Online): Chrome

## Useful logs
Screenshot in Outlook Desktop:
![image](https://user-images.githubusercontent.com/2111803/54296320-f8ac9300-45b4-11e9-96c2-bdc35c3791cd.png)

Same dialog in Chrome (or any other browser):
![image](https://user-images.githubusercontent.com/2111803/54296355-0c57f980-45b5-11e9-8790-3e8f7fb2205a.png)

**Comment by smaremanda** [comment]
Thanks for reporting this error. We believe this is indeed a bug / error in Edge webview. We are taking a deeper look into it. Will update this thread after our investigation.

**Comment by jargil** [comment]
Indeed a bug in our code. I've fixed this in our side and should rollout soon.

**Comment by tobiasviehweger** [comment]
Just got the update and it's now working! (16.0.11617.20002)

**Comment by jargil** [comment]
Thanks for confirming @tobiasviehweger.
