### ISSUE TITLE
On Send web add-in is giving blank recipient name in return if mail is send to the contact list 

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4242]
Description - On Send web add-in is giving blank recipient name in return if mail is send to the contact list 

Steps to Reproduce -
1 - Create a contact list and send a mail to contact list.
2- Check in on send addin mailbox items recipient .

Expected Result -
1 - On send mailbox item should return correct recipient names.

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by mmanjaree-msft** [comment]
@Sagar-lab1 Can you please share a video of the issue.

**Comment by sagar-sonawane9** [comment]
Video - 

https://github.com/OfficeDev/office-js/assets/158541755/b27be6e2-9680-49a0-807d-469201ce1513

Screenshot -
![contact_list](https://github.com/OfficeDev/office-js/assets/158541755/6bf38bbf-8ebf-4d2b-a6bc-8af0ae197654)

**Comment by sagar-sonawane9** [comment]
This issue is closed as duplicate of https://github.com/OfficeDev/office-js/issues/4244, However both are different issues.
No resolution is mentioned on both the tickets.

**Comment by shighosh-msft** [comment]
@Sagar-lab1 could you please reupload the video repro video once more? It doesn't seem to play correctly.

**Comment by sagar-sonawane9** [comment]
Can you check now -

https://github.com/OfficeDev/office-js/assets/158541755/c3dd1f69-660a-49bd-be45-1aab0932eef7


![contact_list](https://github.com/OfficeDev/office-js/assets/158541755/2b0e66af-25f0-485f-a8a0-f170a9ceb2f6)

**Comment by shighosh-msft** [comment]
Hi @Sagar-lab1: Thanks for reuploading the video. Please share a sample add-in that we can use to repro this issue. Please do include the code snippet of the JS file you're invoking on the OnSend event. You can create a private github repo and share with @exextoc

**Comment by sagar-sonawane9** [comment]
Once a sample on-send addin is downloaded you can reproduce the issue at your end.
You need to make changes in manifest.xml where you need to provide the correct URL where you have hosted the sample add-in.
Below are two tags where you need to change the URL in manifest.xml

1. Under <FormSetting> Change value of SourceLocation. 
<SourceLocation DefaultValue="PUT YOUR HTTPS URL WHERE ADD_IN JS FILES ARE HOSTED LIKE => https://punedlp.abc.net/AddinFolder/commands.html"/> 

2. Under <Resources> tag change value of <Urls>
<bt:Url id="Commands.Url" DefaultValue="PUT YOUR HTTPS URL WHERE ADD_IN JS FILES ARE HOSTED LIKE => https://punedlp.abc.net/AddinFolder/commands.html"/>

Sample add-in logs all the information(like sender, recipient, subject, mail body) on the console so it's better to use outlook OWA for testing this though results are the same on thick outlook client application.

[SampleOnSendAddin.zip](https://github.com/OfficeDev/office-js/files/14834569/SampleOnSendAddin.zip)

**Comment by rkpathak** [comment]
@Sagar-lab1 For Contact list the item.to.getAsync returns: 
`[{"displayName":"test_list","recipientType":"distributionList"}]`
You can try the same with the following code:
`
Office.context.mailbox.item.to.getAsync(function (asyncResult) {
  if (asyncResult.status == "failed") {
    console.log("Action failed with error: " + asyncResult.error.message);
  }
  else {
    console.log("to: " + JSON.stringify(asyncResult.value));
  }
});
`
Please change your code to handle this case.

**Comment by sagar-sonawane9** [comment]
We have used item.to.getAsync() API as mentioned in above comments.
it gives response as [{"displayName":"test_list","recipientType":"distributionList"}]

But doesn’t give details about email addresses present in contact list.
Email addresses are returned as response if we send email to multiple separate recipients. 

We need to fetch email addresses of contacts present in contact list. 
Is there any alternate API available which can expand test_list details.

**Comment by akshayta23** [comment]
@rkpathak @shighosh-msft Can you help here?

**Comment by ajays-msft** [comment]
Thank you for the input. This is will considered as a new feature request.
We track Outlook add-in feature requests on our[Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by JuaneloJuanelo** [comment]
@Sagar-lab1 this is by design if you need to get the emails within the DL you should use the graph API to get the emails within it.
