### ISSUE TITLE
On Send web add-in is giving incorrect recipient name in return if mail is send to the contact.

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4244]
Description - On Send web add-in is giving incorrect recipient name in return if mail is send to the contact.

Steps to Reproduce -
1 - Create a contact list send a mail to contact.
2- Check in on send addin mailbox items recipient .

Expected Result -
1 - On send mailbox item should return correct recipient names.
2 - Recipient name coming as - 
/o=ExchangeLabs/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=d37d11828c084e269f71a0287828cda7-makarand_kh

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by mmanjaree-msft** [comment]
@Sagar-lab1 Can you please share a video of the issue.

**Comment by mmanjaree-msft** [comment]
Closing this as we are tracking the issue on https://github.com/OfficeDev/office-js/issues/4242

**Comment by Medha-lab** [comment]
Please find attached video herewith 

https://github.com/OfficeDev/office-js/assets/158465158/20c43ac1-5c98-462d-970e-a4ce9a36b355

**Comment by sagar-sonawane9** [comment]
This issue is closed as duplicate of https://github.com/OfficeDev/office-js/issues/4242, However both are different issues.
No resolution is mentioned on both the tickets.

**Comment by akagarwa-msft** [comment]
Thanks for reporting this issue regarding wrong recipient value being returned. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: 4411061

**Comment by shighosh-msft** [comment]
We have rolled out a fix. The same is available on client version 20240419007.04 or greater.
