### ISSUE TITLE
Performance issues with getSpecialCellsOrNullObject method

### ISSUE THREAD

**Issue by jkpieterse** [OfficeDev/office-js#4245]
# Provide required information needed to triage your issue

I have an add-in in the store called Flexfind. The tool aims to search in all of Excel’s objects. One of those objects is Data Validation cells. In the add-in, I have these lines of code:

  let rng = sht.getRange().getSpecialCellsOrNullObject(Excel.SpecialCellType.dataValidations);
  rng.load("areaCount,address");
  await context.sync();

The code runs into a very long loop as soon as it hits this line, because it thinks it has to process all gazillion cells of the sheet:
 
  await context.sync();
 
I can change the code to use the used range:
 
  let rng = sht.getUsedRange().getSpecialCellsOrNullObject(Excel.SpecialCellType.dataValidations);
  rng.load("areaCount,address");
  await context.sync();
 
which works. But unfortunately, now it doesn’t find any data validation cells outside of the used range.
 
I think this is a perf issue that should be solvable, as the VBA specialcells method is far superior here (almost instant).

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2401 Build 16.0.17231.20236) 32-bit 
* Operating System: Windows 10
* Browser (if using Office on the web): Edge
 
## Expected behavior

Quick response of the method

## Current behavior

The method runs on forever as it looks like it is trying to address all cells of the worksheet to find the right cells.
Since VBA is capable of doing this very quickly, I have no doubt this should also be possible in office-js

## Steps to reproduce

1. Open blank Excel file
2. Select column A, choose Data, Validation
3. Set a validation rule, like List and enter some items to choose from
4. Open Script lab and download this gist: https://gist.github.com/jkpieterse/02e5928b5ba282a80c8f4cbaf9d57e4e
5. Try to search for any of the items in the validation list.
6. Edit the code by changing the function "SearchInValidation" :
Replace this line:
  let rng = sht.getRange().getSpecialCellsOrNullObject(Excel.SpecialCellType.dataValidations);
with:
  let rng = sht.getUsedRange().getSpecialCellsOrNullObject(Excel.SpecialCellType.dataValidations);

Now you'll see the results are populated quickly, but it only finds the validation rule of cell A1.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

I am trying to search all cells containing validation rules (and other things, like Conditional formatting), including those outside of the usedrange.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by zhenhuangMSFT** [comment]
Hi @jkpieterse, thanks for reporting the issue! We are looking into it and will get back to you soon. Thanks for your patience!

**Comment by SiruiSun-MSFT** [comment]
Hi @jkpieterse, We tried to reproduce your problem by following your repro steps, but the gist you provided seems to have some problems and cannot be run directly. At the same time, we made a simple attempt using the gist below and did not reproduce the performance problem you mentioned.

_async function run() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    let rng = sheet.getRange().getSpecialCellsOrNullObject(Excel.SpecialCellType.dataValidations);
    rng.load("areaCount,address");
    await context.sync();
    console.log(rng.areaCount + rng.address);
  });
}_

Since the gist scenario you provided seems a bit complicated. We would like to know if you can make some simplifications and modifications  on it, which may help us locate the problem. Thanks for your patience!
