### ISSUE TITLE
Define a custom function with infinite numbers of parameters

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#4246]
Hello,

I would like to know if it's possible to define a custom function with infinite numbers of parameters (like the `SUM` function). If it's not possible, what do you suggest to do to define such a function?

Thank you

**Comment by MiaofeiWang** [comment]
The answer is yes. Please check the documentation: https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-parameter-options?tabs=javascript#repeating-parameters

**Comment by chengtie** [comment]
> The answer is yes. Please check the documentation: https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-parameter-options?tabs=javascript#repeating-parameters

Thank you. This is what I need.
