### ISSUE TITLE
Edge WebView: Performance issue with messageParent

### ISSUE THREAD

**Issue by tobiasviehweger** [OfficeDev/office-js#425]
## Expected Behavior
We are using Office.context.ui.messageParent(string) to send messages between a dialog and the ribbon functions handler (to access APIs not available in the dialog). Before upgrading to Edge WebView, this is working really well and the message is received almost instantly (expected behavior). This was working in IE before without issues!

## Current Behavior
With Edge WebView, the message is now taking (reproducible) much longer, around 3 seconds (!) per message from calling messageParent until the  "DialogMessageReceived" is received. Even worse, if you sent multiple messages in the same execution, it will swallow all but one, and that one will take 3 seconds * number of sent messages....

Chrome (< 1s)
![image](https://user-images.githubusercontent.com/2111803/54355668-f3edea80-4659-11e9-81e7-6419f79c84dc.png)

Outlook (9s)
![image](https://user-images.githubusercontent.com/2111803/54356779-b9d21800-465c-11e9-8147-32ad2f37f6b9.png)

## Steps to Reproduce, or Live Example
Example app: https://static-resources.yasoon.com/outlook-edge-messageparent-bug/manifest.xml

Repo: https://github.com/tobiasviehweger/outlook-edge-messageparent-bug

## Context
We are calling Office APIs that are not available from the dialog via messageParent. This works well until Edge WebView is came along :) This totally ruins performance & makes the app basically unusable (due to dropped messages as well).

## Your Environment
Platform: PC Desktop
Host: Outlook
Office version number: 1904 (16.0.11504.20000)
Operating System: Windows Insider 19H1 (18356.1)

**Comment by smaremanda** [comment]
Thanks for reporting this error. We are taking a deeper look into it. Will update this thread after our investigation.

**Comment by kbrandl** [comment]
(@jargil assigning this one to you, per Sudheer's request.)

**Comment by jargil** [comment]
Hey! @tobiasviehweger, thanks for reporting this one! Just like the others you reported, this indeed is a bug which I've just addressed and should be rolling out soon.

**Comment by tobiasviehweger** [comment]
Hey @jargil, so glad to hear that, thanks for being so responsive on this one - was a huge blocker for us :)
Any idea around which version number this is going to be fixed, so we can try testing?

Thanks!

**Comment by jargil** [comment]
I don't have a version number yet, but will update here once I have one.

**Comment by jargil** [comment]
Quick update: I'm still waiting for an Insiders build to be published with the fix. Any build after Office  16.0.11618.20000 should have the fix for this bug.

**Comment by tobiasviehweger** [comment]
I just updated to 16.0.11617.20002 and the issue seems to be fixed. Thanks so much! :)
