### ISSUE TITLE
Synchronization is slow

### ISSUE THREAD

**Issue by koukouza** [OfficeDev/office-js#4250]
Hello, I'm working on an add-in but when I modify something on the manifest I see that the sync is too slow, also if I delete it it remains visible on outlook for hours and hours how can I force the sync?

**Comment by AlexJerabek** [comment]
Hi @koukouza,

Thanks for reaching out. Have you tried [clearing the Office cache](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache)? That should make sure the most recent version of the manifest is uploaded.

**Comment by koukouza** [comment]
Hi @AlexJerabek.

Thank you for your prompt response. I have also tried your suggestion, but the synchronization is still slow. In addition, changes are sometimes visible on Outlook Web but not yet on Outlook Desktop, where they are neither modified nor synchronized. I don't understand the reason for these considerable delays, which can extend over several hours before the changes are perceptible.

**Comment by AlexJerabek** [comment]
Thanks @koukouza. I'm going to transfer this issue to the [office-js repo](https://github.com/OfficeDev/office-js). There, members of the Outlook extensibility team can investigate the issue.

**Comment by koukouza** [comment]
Perfect, Thank you @AlexJerabek 
I look forward to hearing from them.

**Comment by ajays-msft** [comment]
@koukouza - It is not clear from your post exactly what you are trying to do. You can modify the manifest and sideload, you can modify the manifest and redeploy using admin, you can modify the manifest in store and client will pickup new manifest etc.
Appreciate if you make it clear.

Secondly, which client as a problem, and what kind of problem each of them have is also not clear. 

Please provide clear repro steps, client details and version and what modifications are you doing to manifest etc. Then I will be able to assist you better.

**Comment by koukouza** [comment]
@ajays-msft 
I'm sorry I wasn't clear enough before. Let me explain in detail:

I developed an Outlook add-in following these steps: (https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator). When I run it locally, everything works without any problem. And, once deployed on an App service and added in Administrator => settings => Integrated applications", my extension appears perfectly in my admin center.

However, I'm experiencing the following problems:

- Once added to "Integrated Applications" using the manifest link: when I access Outlook (web or desktop version), I don't see it immediately. It takes several hours before it appears.
- Sometimes, even after several hours, I see it on Outlook web but not in the Outlook desktop application.
- After several hours or even a day, the add-in finally appears in my Outlook:
   * When I modify a JS, HTML or CSS file, I have to wait a few minutes or even an hour for the changes to take effect.
   * When I modify the manifest file, I have to wait several hours or even a day before seeing the update.
   
Changes I've made to the manifest: For example, changing the logo or the name of the add-in. 
Do these delays seem normal? You mentioned sideload, but I'm not sure what you mean by that.

**Comment by koukouza** [comment]
Hello @ajays-msft have you had time to look at my problem please?

**Comment by ajays-msft** [comment]
@koukouza - It is expected to take time for changes to reflect. Please find more info in the documentation below.

https://learn.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-faq?view=o365-worldwide#how-long-does-it-take-for-add-ins-to-show-up-for-all-users-
