### ISSUE TITLE
Version control and upgrading of custom functions of an add-in

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#4253]
Hello,

We have published several add-ins in the store. Now we plan to add custom functions to them. One critical thing we need to consider from the beginning is how to ensure the version control and future upgrading of these functions.

For instance, we release a function `XXX(aNumber)` in Version 1. We plan to add a string parameter `aString` before `aNumber` to the function (i.e., `XXX(aString, aNumber)`) in Version 2. How could we prevent this change from breaking the existing usage of `XXX(aNumber)` of existing users?

Do you have a conventional way to manage this?

Thank you

**Comment by grangeryy** [comment]
Hi @chengtie , thank you for the question! Currently, custom function doesn't support the same naming for different functions: [details about naming](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-naming#custom-functions-naming-guidelines). You may need to update the json file with another name for new one so the two functions won't get conflict.
