### ISSUE TITLE
New Outlook does not show add-ins button.

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4256]
Description - 
Earlier we used to get the get add-ins button, clicking on which we get to know add-ins added to outlook application.
Recently, New Outlook does not have this facility. 
In New Outlook world, How to check which add-ins are added to my user.

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by mmanjaree-msft** [comment]
@Sagar-lab1 Please refer to this document. https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing?tabs=windows-web#sideload-manually. In your preferred browser, go to https://aka.ms/olksideload. Outlook on the web opens, then the Add-Ins for Outlook dialog appears after a few seconds. Also take a look at this https://devblogs.microsoft.com/microsoft365dev/updates-to-how-to-install-and-use-add-ins-and-apps-in-outlook-for-windows-and-outlook-on-the-web/. Thanks
