### ISSUE TITLE
Outlook: add-in no longer pinned when switching between mailboxes on Outlook Web & new Outlook for Windows

### ISSUE THREAD

**Issue by kdeclerck** [OfficeDev/office-js#4259]
**How to reproduce:**
- Click on an email, open the add-in & pin it
- Switch to a mail in another mailbox where the add-in is not installed
- Switch back to a mail in the mailbox with add-in installed

**Seen behavior:**
The add-in no longer shows on Outlook Web and the new Outlook for Windows. It does still show on Mac & the old Outlook for Windows.

**Expected behavior:**
The add-in should keep showing & remain pinned in all versions of Outlook

**Comment by shighosh-msft** [comment]
Hi @kdeclerck, could you please share a repro video. This will help us understand your use-case better. Thanks!

**Comment by akagarwa-msft** [comment]
Thanks for reporting this issue regarding pinning in OWA. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: 4419693

**Comment by Swathy-Mothilal** [comment]
Hi @kdeclerck , could you please confirm if you're still experiencing the behavior? If so, please share a recording of the bug with us? We'd like to confirm it.
