### ISSUE TITLE
Missing cookie & localStorage support in Smart Alerts runtime

### ISSUE THREAD

**Issue by pavelstudeny** [OfficeDev/office-js#4261]
On the classic Outlook for Windows, add-ins using Smart Alerts are split between two runtimes: The side pane is executed in a Browser runtime, the Smart Alerts are executed in JavaScript-only runtime. This prevents the add-in parts from sharing data such as local settings in localStorage. Additionally, JavaScript-only runtime does not support cookies, making e.g. authentication against other services impossible.

We are aware that this behavior is [documented](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtimes). On the other hand, the other platforms (OWA, New Outlook for Windows and Outlook for Mac) are not affected by this issue. As the add-in platform cannot be predicted in advance, the behavior of classic Outlook for Windows limits the usefulness of Smart Alerts any ony platform. Is there a plan to close this gap?

## Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: 16.0.17328.20184
* Operating System: Windows
 
## Expected behavior

- Cookies and localStorage are supported on all platforms
- localStorage data is accessible from all parts of the add-in

**Comment by Flyingdot** [comment]
I fully support that. In our case, it was the lack of Blob support. Fortunately, we could adapt our API to Base64 - but we also had to program out the Base64 conversion, as atob/btob are also not supported. These are already elementary functions in 2024.

I understand the reasons why this runtime is used. However, it is challenging when such different requirements exist on various platforms.

**Comment by akshayta23** [comment]
@JuaneloJuanelo Can someone from the Win32 team look into this issue?

**Comment by timwan10** [comment]
I don't believe there is any plans to make localStorage work in the old Win32 runtime. Sharing data between the taskpane and smart alerts can be done via the session data apis: https://learn.microsoft.com/en-us/javascript/api/outlook/office.sessiondata?view=outlook-js-preview which should work in all platforms. 

Settings that should be persisted across sessions should be stored in RoamingSettings.

**Comment by pavelstudeny** [comment]
@timwan10 yes, we are aware of Office.RoamingSettings, Office.SessionData and OfficeRuntime.Storage. Thanks for trying to help, though!

**Comment by ajays-msft** [comment]
Thank you for the input. This is will considered as a new feature request.
We track Outlook add-in feature requests on our[Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
