### ISSUE TITLE
getCallbackTokenAsync failing for Outlook-windows.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#4265]
# Provide required information needed to triage your issue
Last March 14, 2024, we started receiving reports from multiple customers of our addin failing. Upon investigation, we found that the culprit was a failing call getCallbackTokenAsync().  This part of our addin code was never changed and was working properly.

And then sometime around March 15, 2024, the problem got resolved for some of our test environments and some of our customers. This issue only affected Outlook for Windows, legacy-look mode. OWA, mobile and the rest were working fine.

In light of the above, we would like to (ask if possible) if the good MS-team had an update which broke the API first and then another update that got it fixed for some environments. Basically, if it is possible, some description of the problem and the fix. We (and some of our customers) would like to know what broke the said API. Thank you very much.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Builds 2403, 2402 and others
* Operating System: Windows
* Browser (if using Office on the web): NA
 
## Expected behavior

getCallbackTokenAsync() should work and get either a REST-capable or EWS-capable token.

## Current behavior

Office.context.mailbox.getCallbackTokenAsync() was failing. And fiddler could not capture the error as it seemed like a non-network issue. Cannot debug on Outlook-for-windows either. OWA did not have an issue so debugging was impossible there.

## Steps to reproduce

This issue has been resolved for some environments.
For affected users, calling Office.context.mailbox.getCallbackTokenAsync() would fail.

## Link to live example(s)

NA

# Provide additional details

NA

## Context

This caused massive loss of service on our end, thus some information on what happened would be greatly appreciated.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by glr0221** [comment]
@exextoc I originally said that the issue has been resolved. But it seems that the problem persists still for some of our customers. I hope you can help us with this one. Thank you.

**Comment by bsjut** [comment]
@exextoc,  I can confirm that this issue persists in our tenant and is preventing i.e. the CodeTwo plugin for email signatures from loading and the Hubspot sales web addin from loading. CodeTwo has claimed that Microsoft is actively looking for a solution, but is unable to provide an incident id: https://status.codetwo.com/incidents/kjpz4ynd18tx

We have raised this as an incident through the Microsoft Admin portal, but this is getting closed as "No issue found". For us, no web add ins in PC outlook (classic outlook) are loading, including Microsoft owned add-ins.

**Comment by onestep** [comment]
Looks like we are having the same problem, but we are also getting `InternalServerError` with error code 9042 when trying to call `getUserIdentityTokenAsync`. I've previously added comments to the issue #3845, but this one looks more relevant.

**Comment by eleonardos** [comment]
We are facing the same problem with the `getUserIdentityTokenAsync` method for a lot of customers. It sometimes returns 9040, 9041 or 9042 error codes and sometimes doesn't fail, but returns an empty token without any error. The problem started on March 14 and is affecting more and more users.

**Comment by RikuRuokonen** [comment]
We are experiencing same problems. Error we got is `"Token retrieval is not supported for this user."`

 Based on some investigation, error's seem to originate from Edge-browsers.

**Comment by kbrilla** [comment]
Basicly we are having the same problem on Desktop Outlook Client for Windows machines. MacOS version works fine. Chrome OWA worsk fine. Edge OWA works as well. 

This is very **urgent** as all our customers lost ability to use our addin!

**Comment by HopiHope** [comment]
We had the same issue on one user (at least only one reported) with our internal addon. Also got error 9042 from the 14th of march to the 15th of march.

A colleague updated the license in outlook and suddenly it worked again! it seems to be a relative new button at the "File" page (have not noticed it before. i'm not using the new outlook version, so it could be somewhere else in the new outlook).

Of course i don't know if it's a solution for the problem in general but just give it a try!

Greetings,
Julian

**Comment by bsjut** [comment]
@HopiHope , I would attribute that to coincidence. I looked into it on a test machine and we don't see any change in web-add-in behavior

**Comment by timwan10** [comment]
This is an issue that is undergoing investigation, with urgency. We will provide updates as they come.

**Comment by bsjut** [comment]
This is managed as https://admin.microsoft.com/#/servicehealth/history/:/alerts/EX744850 and claims to have been resolved.

**Comment by kbrilla** [comment]
I can confirm, today all works fine so far.

**Comment by glr0221** [comment]
Thanks @bsjut and @kbrilla . I am going to ask some of our affected customers as well. Thanks again.

**Comment by bsjut** [comment]
@kbrilla , @timwan10 , I can confirm from my side that some add-ins are working (i.e. CodeTwo), but others are still not functioning  (i.e. Hubspot Sales) on classic Outlook PC, Current Channel, where as the web addi-ins work in New Outlook and Web.

**Comment by Oleg-O** [comment]
@bsjut the issue reported in this post has been confirmed resolved earlier this week. If anything is not working, please open a new post and describe symptoms, platforms, etc as usual, as much detail as possible. Thank you!

**Comment by msann86** [comment]
This issue has returned for me today:
`Office.context.mailbox.getCallbackTokenAsync((result) => { console.log(result); resolve(result.value); });`

Response via console.log:
```
{
    "status": "failed",
    "error": {
        "name": "InternalServerError",
        "message": "Der Exchange-Server hat einen Fehler zurückgegeben. Weitere Informationen finden Sie im Diagnoseobjekt.",
        "code": 9042
    },
    "diagnostics": {
        "ClientRequestId": "{E97DE5B5-FF55-411B-96D5-C2DBE0872F5E}",
        "ErrorText": "An internal server error occurred. The operation failed."
    }
}
```

**Comment by BastianKamp** [comment]
Slightly different error on same call here. With the new Outlook.

```js
{
  "status": "failed",
  "error": {
    "name": "GenericTokenError",
    "message": "Ein interner Fehler ist aufgetreten.",
    "code": 9018
  }
}

````

**Comment by gardiantnikhil** [comment]
Issue is happening for us as well in our outlook addins

**Comment by dipika-mandhare-ambit** [comment]
I am also facing same issue add-in not working for web and windows platform.

**Comment by msann86** [comment]
getCallbackTokenAsync() has been deprecated and seems to be replaced by OAuth.
Microsoft had presumably informed me about this earlier in a weekly email, but sadly, this crucial information was drowned in huge amounts of trash information.

These instructions helped me most:
https://learn.microsoft.com/de-de/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth
https://learn.microsoft.com/de-de/exchange/client-developer/exchange-web-services/how-to-authenticate-an-ews-application-by-using-oauth#code-samples

**Comment by kworksltd** [comment]
Our users have also started to get the InternalServerError with error code 9042 when trying to call getUserIdentityTokenAsync. This is not affecting all of them - even in the same organisation, one user gets the error but others don't. I have so far had two different businesses report the error in the last 2 days, when it was working just fine until that point and we have made no changes to the add-in for over 3 months.
