### ISSUE TITLE
Getting Empty Taskpane when manifest is installed for the first time via sideload option under custom-addins.

### ISSUE THREAD

**Issue by RaveendraReshma** [OfficeDev/office-js#4268]
1. We are developing office web Addin for outlook using event based (Smart Alert) .The Addin is generated using office yo generator Task Pane add-in using the React framework.
2. Given the user had installed the manifest file for the first time under custom-addins via sideload option and when user tries to open the taskpane he/she is getting the empty taskpane instead of main content of the taskpane.

## Your Environment

* Platform : Office on the web
* Host : Outlook [OWA]
* Office version number: Version 2311 Build 16.0.17029.20140
* Operating System: Windows
* Browser : Chrome & Edge
 
## Expected behavior
Once the user had installed the manifest file and tries to open the taskpane, he/she should get to see actual content of the taskpane instead of blank screen.

## Current behavior
Getting a blank screen instead of main content of the taskpane.

## Steps to reproduce

1. Install the latest manifest file via sideload under custom-addins in OWA[Chrome]
2. Add recipients in To/Cc/Bcc section and click on send which will open the taskpane.
3. Once the taskpane is opened the Screen is blank.
4. In console we are getting below error as shown in the below img. 
5. We have called Office.OnReady still getting an empty taskpane when the manifest file is installed for the first time. 

<img width="630" alt="image" src="https://github.com/OfficeDev/office-js/assets/145095553/6068d178-e510-4f72-b715-b84ead7b6f23">

6. This issue gets resolved once user reloads the page or tries to send out the mail second time.

## Context

1. Every time when user tries to install the manifest file for the first time he/she is getting empty taskpane which is not appropriate.
2. In this case user won't be able to understand the issue since the screen is blank.
3. Is there any way to inform the user to reload the page once this issue occurs.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ajays-msft** [comment]
@RaveendraReshma - Please follow the instructions here, and debug your addin.

https://learn.microsoft.com/en-us/office/dev/add-ins/testing/debug-initialize-onready
