### ISSUE TITLE
getUserIdentityTokenAsync asyncresult.status returns null value with succeded status

### ISSUE THREAD

**Issue by MrDaleQ** [OfficeDev/office-js#4269]
When calling getUserIdentityTokenAsync in Outlook Desktop 2402 (17328.20162) or later this returns a null value with succeded status in asyncresult.status

## Your Environment
* Platform: PC
* Host: Outlook
* Office version number: 365 - Version 2402 Build 16.0.17328.20162 / 20184 
* Operating System: Windows 11
 
![MicrosoftTeams-image](https://github.com/OfficeDev/office-js/assets/140503143/dde15f98-9273-426c-a81d-00e7a4c06f31)

## Expected behavior
With versions previous to 20162, this method correctly returns a user token. This still functions correctly in OWA / New Outlook

# Provide additional details
Recreating the user's profile in all circumstances appears to resolve the issue. We have seen this reported across small numbers of staff in multiple clients.

**Comment by MrDaleQ** [comment]
![MicrosoftTeams-image](https://github.com/OfficeDev/office-js/assets/140503143/97499def-cfce-46c7-88bb-a7d2b3eb065f)

**Comment by MrDaleQ** [comment]
Hi @exextoc 

I believe this has now been resolved by your teams, which is excellent.

Is there any information regarding if this was a client / server side issue or similar, as a number of customers are asking for additional information.

**Comment by Oleg-O** [comment]
I believe this is the same issue as #4265, this incident was a server-side issue (affecting not just add-ins) and reported via Service Health dashboard at https://admin.microsoft.com/#/servicehealth/history/:/alerts/EX744850.
