### ISSUE TITLE
Outlook web add-in does not work for schedule polls.

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4271]
Description -
We have developed the Outlook web add-in to read and act on the files/mail body when it is sent though Outlook (ItemSend event)
On Outlook mail/meeting, There is an option schedule polls, which sends (ItemSend) the  the data in form of a link however, for user it is shown as image in which data can be edited.
Since link is shared, Our add-in is not able to read/act on the data being send through Outlook.
Can we get the event through which we can read/act the file which is being send as a link.

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by shighosh-msft** [comment]
Hi @Sagar-lab1, could you please share the repro steps with more clarity? A repro video will also help debug this issue quicker. Thanks!

**Comment by ajays-msft** [comment]
@Sagar-lab1 - Are you referring itemsend in calendar invite or itemsend in mail that is created by polls?

**Comment by sagar-sonawane9** [comment]
In both the cases i.e. itemsend in calendar invite and itemsend in mail with schedule poll option the issue is observed.

**Comment by ajays-msft** [comment]
@Sagar-lab1 The actionable message is being created by the server. It is not yet created at the time email was sent. Hence the data is not available to another itemSend addin.
