### ISSUE TITLE
Critical issue for add-ins with "context.sync" in latest Excel channels

### ISSUE THREAD

**Issue by Alex0cean** [OfficeDev/office-js#4273]
Calls to context.sync do never return and also do not throw an error.

await Excel.run(async (context: Excel.RequestContext)
  await context.sync()

--> The promise in last line is neither resolved nor rejected.

## Your Environment
Our add-in can’t be used at all with this issue. More than 10.000 monthly business users are potentially affected.

The issue currently exists in these channels:
Current Channel: Version 2403 (Build 17425.20058) 
Current Channel Preview: Version 2403 (Build 17425.20070) 
Beta Channel: Version 2404 (Build 17512.20000)

Our add-in with the same coding currently runs fine in channels Semi Annual Enterprise and Monthly Enterprise.

As we have customers using the affected channels the issue must be fixed as soon as possible and also must not reach channels like Monthly Enterprise or Semi Annual Enterprise!
 

## Steps to reproduce
The issue can’t be reproduced easily within ScriptLab. I suspect that the usage of shared runtime might be important.
The add-in task pane starts with URL A and then redirects to URL B. The issue with context.sync only exists in the web app on URL B.
As explained above the same web app with the redirection from URL A to URL B runs fine in older Excel channel versions. It is not a coding issue in the add-in.

# Provide additional details --> error analysis
- There is no error thrown by context.sync
- There is no error on the Console 
- The runtime log (https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtime-logging) does not show any error
- The Windows Event Viewer does not show any error

**Comment by penglongzhaochina** [comment]
Hi @Alex0cean , This issue has been resolved by our partner team, please verify.

**Comment by Alex0cean** [comment]
@penglongzhaochina : yes, the issue has been solved. Thank you for the quick turnaround time !
Best,
Alex
