### ISSUE TITLE
await OfficeRuntime.auth.getAccessToken() hangs when there are multiple requests to get access token

### ISSUE THREAD

**Issue by varunrathi1910** [OfficeDev/office-js#4274]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Chrome - Outlook Add-in
* Office version number: ______
* Operating System: Windows
* Browser (if using Office on the web): Google Chrome
 
## Expected behavior

The getAccessToken request should complete and either a failure or success response should be returned
## Current behavior

If multiple requests, more than 5, are made to generate the access token. Some of the requests are never completed.
## Steps to reproduce

1. Write a for loop and call the function asynchronously multiple times.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by ajays-msft** [comment]
@varunrathi1910 - Can you please help understanding your scenario, and how you are using the token api? 
And if you call 5 times, are you getting the same token, everytime, or does it change for each call? 

Can you open devtools, and collect HAR files (network log) and send them across for further debugging? Please upload HAR files to a private github repo and give access to @exextoc .

**Comment by varunrathi1910** [comment]
Hi @ajays-msft,
We utilize the getAccessToken() method to retrieve the access token, which is important to various authentication flows in our application, such as fetching attachment details for emails.
 
Particularly, when multiple files are attached in the compose pane, we employ this method to fetch the access token which is then used in requests to process the attachments. We track attachments added or removed in the compose pane using a custom function attached to Office.EventType.AttachmentsChanged via Office.context.mailbox.item.addHandlerAsync. The custom function then processes the list of attachments  through map function.

The token value remains consistent across these operations.

Although I may not be able to provide network log files, I can offer an alternative script to assist in debugging. Here's the code:

Office.initialize = async function (reason) {
  try {
    console.log(`Office.initialize(): Huzzah!`);
	console.log("Custom js called");

	for(let i = 1; i <= 10; i++)
	{
		console.log("Starting iteration" + i)
		var l=await OfficeRuntime.auth.getAccessToken();
		console.log("Completed iteration : " + l)
		console.log("Completed iteration" + i)
	}
	console.log("Custom js finished");
  }
  catch(error){
	console.log("Initialisation Error is : " + error.message);
    console.error(`Office.initialize(): Error! ${error}`);
  }  
};

Steps to run the script : 

1. You can create an add-in that loads an html.
2. Within the HTML, call a .js script that contains the above code as well as the processing code.
3. Check the console logs and verify at what iteration does the code wait indefinitely for a response. This can be verified by the checking for the logs within the for loop.

Note that the error is intermittent and will halt at different iterations.

**Comment by shighosh-msft** [comment]
Hi @varunrathi1910, thanks for sharing the details. Although, it is not very clear why is it required for you to call getAccessToken() back to back (like you have shown in a loop) and not reuse the token obtained until it expires?

**Comment by varunrathi1910** [comment]
Hi @shighosh-msft,
We are calling the function whenever a file is added to the taskpane via Office.context.mailbox.item.addHandlerAsync and our function is called when Office.EventType.AttachmentsChanged is triggered. The issue occurs whenever multiple files are attached within the taskpane.

Since same values were returned every time from the function, we presumed that the token management, caching and expiry would be handled within the library and no additional network or API calls would be expected. So, calling the function directly would simplify the token consumption code.

Furthermore, I would like to know whether:
1. The caching and management of the token be handled by us
2. If the token management should not be handled by us, is this a bug within the library

**Comment by akagarwa-msft** [comment]
Hello @varunrathi1910 ,
Thanks for answering the query in detail. Your understanding is right regarding the management of token and caching. It is handled by the library and the token need not be cached by you. 
For the issue you have reported, we are not able to repro this issue at our end. Also, we have made some changes on how we handled multiple token call handling on our side, so request you to try again and see if the issue is resolve for you.

**Comment by varunrathi1910** [comment]
Hi @akagarwa-msft,
We have been unable to reproduce the issue at our end as well now. Could you let us know about the changes for handling multiple token calls or any specific measures taken to address the issue.

**Comment by rajjha-msft** [comment]
Hey @varunrathi1910 

No changes are required on your end for handling the calls. 
Changes have been made in the library itself so as to handle these scenarios more efficiently. 

Please feel free to close the issue if the original issue is resolved.

**Comment by varunrathi1910** [comment]
Hi @rajjha-msft,
Thank you for resolving the issue. I'll be closing the ticket.
