### ISSUE TITLE
Outlook for Mac: "event.completed()" closes popup opened in "ExecuteFunction" via "Office.context.ui.displayDialogAsync"

### ISSUE THREAD

**Issue by vyazadji** [OfficeDev/office-js#428]
Outlook for Mac: `event.completed()` closes popup opened via `ExecuteFunction` and `Office.context.ui.displayDialogAsync`

## Expected Behavior
When I call `event.completed()`, it doesn't close popup which I open via `Office.context.ui.displayDialogAsync`. 

## Current Behavior

Dialog closes immediately after calling `event.completed();`
### Note: 
- it worked in Mac Outlook till 16.21
- it works well in Windows Outlook with the approach described below
- it works well in web Outlook with the approach described below

## Steps to Reproduce, or Live Example

- calling it right after `Office.initialise() `
- open popup from the same domain 

In the manifest file:

``` 
<Action xsi:type="ExecuteFunction">
    <FunctionName>openDialog</FunctionName>
</Action>
```

Javascript: 
```
window.openDialog = function(event) {
  var callback = function(asyncResult) {
    event.completed();
  };
  Office.context.ui.displayDialogAsync("someURL", {}, callback);
};

```

## Context
In this popup I want to show something like live feed about events in my application. It should be opened a long time. 

## Your Environment

* Platform Mac
* Host [Excel, Word, PowerPoint, etc.]: Host Outlook client
* Office version number: 16.23
* Operating System: macOS Mojave 10.14.3

**Comment by kbrandl** [comment]
@vyazadji apologies for the slow response; looks like this issue was overlooked until now. Is this issue still present (i.e., do you still need assistance)? Thanks!

**Comment by vyazadji** [comment]
Hello @kbrandl. We changed our UI, and now we don't use popup. So this issue isn't actual for me now.  I don't know if it reproducible in the latest Mac Outlook.

**Comment by kbrandl** [comment]
@vyazadji thanks for the update!
