### ISSUE TITLE
SmartAlerts manifest doesn't work on mac.

### ISSUE THREAD

**Issue by DanilKorotenko** [OfficeDev/office-js#4283]
For more info:
https://github.com/DanilKorotenko/OutlookAddin_ItemSend_SmartAlerts

Manifest:
[manifest_smartAlerts.xml.zip](https://github.com/OfficeDev/office-js/files/14694983/manifest_smartAlerts.xml.zip)

### Description

SmartAlerts manifest doesn't work in Mac New Outlook.

### Hardware & Software

MacBook Air M1 2020
OS: macOs 14.2.1

Outlook: 
Microsoft® Outlook for Mac
Version 16.83.1 (24031813)

### Steps to reproduce

1. Open Mac New Outlook app.
2. Go to "Get Add-ins" -> "My Add-ins"
3. Install "manifest_smartAlerts.xml" from file.
4. Close window.
5. Select any message in inbox.
6. Try to find addin icon on toolbar.
7. Start composing new message.
8. Try to find addin icon on toolbar in composing mode.
9. Send message to any address.

Expected result:
1. On step 6, addin icon should be present on toolbar.
2. On step 8, addin icon should be present on toolbar.
3. On step 9, addin should block message.

**Comment by shighosh-msft** [comment]
Hi @DanilKorotenko, can you please confirm if the custom add-in is working in other platforms ie. Outlook Web and win32?

**Comment by DanilKorotenko** [comment]
I confirm that the manifest attached to this issue is working in Outlook Web.

![image](https://github.com/OfficeDev/office-js/assets/2341646/4d85e53e-d3de-4664-99d4-8ac49692caa7)

**Comment by akagarwa-msft** [comment]
Please capture the incident Id and share with us.

Steps to generate Diagnostics/incident ID:

Re-launch Outlook
Repro the issue mentioned
Click on Help->Collect Diagnostics
Share the ID generated.

**Comment by DanilKorotenko** [comment]
IncidentID:
VZF9PWR7

**Comment by DanilKorotenko** [comment]
I definitely did install the addin mentioned:
![image](https://github.com/OfficeDev/office-js/assets/2341646/97247505-85fc-40e6-8df3-9dc50c2929c7)

**Comment by rajjha-msft** [comment]
Thanks for reporting the issue around SmartAlerts feature in Mac. 
We have put it in our backlog, and currently don't have any timelines to share. 

Internal tracking id : 8885728

**Comment by DivyaPatidar** [comment]
@DanilKorotenko the [icon](https://danilkorotenko.github.io/OutlookAddin_ItemSend_SmartAlerts/sample.png) provided in your manifest exceeds the size limitation for [iconUrl](https://learn.microsoft.com/en-us/javascript/api/manifest/iconurl?view=common-js-preview) and [HighResolutionIconUrl](https://learn.microsoft.com/en-us/javascript/api/manifest/highresolutioniconurl?view=common-js-preview). Could you try reducing the size of the icon and check if the add-in appears in the ribbon?

**Comment by DanilKorotenko** [comment]
> @DanilKorotenko the [icon](https://danilkorotenko.github.io/OutlookAddin_ItemSend_SmartAlerts/sample.png) provided in your manifest exceeds the size limitation for [iconUrl](https://learn.microsoft.com/en-us/javascript/api/manifest/iconurl?view=common-js-preview) and [HighResolutionIconUrl](https://learn.microsoft.com/en-us/javascript/api/manifest/highresolutioniconurl?view=common-js-preview). Could you try reducing the size of the icon and check if the add-in appears in the ribbon?

I updated the icon. Result is the same.

MacBook Air M1 2020
macOS: Sequoia 15.0.1 (24A348)

Outlook:
Microsoft® Outlook for Mac
Version 16.91.1 (24111613)

**Comment by DivyaPatidar** [comment]
@DanilKorotenko Can you share the updated manifest with smaller icons? 
Can you also try to validate your manifest and see if there are any errors. For more details on how to validate, please refer to the [documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest)

**Comment by DanilKorotenko** [comment]
Off course I can share the updated manifest.
I have created a sample project for this issue:
https://github.com/DanilKorotenko/OutlookAddin_ItemSend_SmartAlerts

Here the updated manifest:
https://raw.githubusercontent.com/DanilKorotenko/OutlookAddin_ItemSend_SmartAlerts/refs/heads/main/manifest_smartAlerts.xml

**Comment by DanilKorotenko** [comment]
office-addin-manifest validate output:

```
Validation Information: 
Package Type Identified: Package of your add-in was parsed successfully.

Correct Package: Your package matches the submission type.

Valid Manifest Schema: Your manifest does adhere to the current set of XML schema definitions for Add-in manifests.

Manifest Version Correct Structure: The manifest version number has the correct structure for the platform that it supports.

Manifest Version Correct Value: The manifest version number is greater or equal to 1.0.

Manifest ID Valid Prefix: The product ID in the manifest has a valid prefix
  - Details: 36FD4DD0-050E-434D-96D6-6F8A82E3CBE9

Manifest ID Correct Structure: The structure of the product ID is correct.
  - Details: 36FD4DD0-050E-434D-96D6-6F8A82E3CBE9

Desktop Source Location Present: A desktop or default source location URL is found.

Secure Desktop Source Location: The manifest desktop source location URLs use HTTPS.

The manifest source location URLs are valid.: The manifest source location URLs are valid.

Supported Office Identified: Supported Office products were successfully determined.

Support URL Present: The manifest support URL is present.
  - Details: https://danilkorotenko.github.io/OutlookAddin_ItemSend_SmartAlerts

Valid Support URL structure: The manifest support URL has valid structure.

Autorun LaunchEvent Type validation was successful: Autorun LaunchEvent Type extracted from manifest is found to be valid.

Allowed send modes are present: Allowed send modes are present

Valid OnlineMeetingCommandSurface ExtensionPoint.: OnlineMeetingCommandSurface ExtensionPoint extracted from manifest is found to be valid.

Minimum Api requirement constraint for VersionOverrides is valid: Minimum Api requirement constraint for VersionOverrides is valid

Mailbox add-in not containing ItemSend event is valid.: Mailbox add-in not containing ItemSend event is valid.

High Resolution Icon Present: A high resolution icon element was expected and is present.
  - Details: https://danilkorotenko.github.io/OutlookAddin_ItemSend_SmartAlerts/sample_64x64.png

Supported High Resolution Icon URL File Extension: The manifest high resolution icon URL has a valid image file extension.
  - Details: png

Secure High Resolution Icon URL: The manifest high resolution icon URL uses HTTPS.
  - Details: https://danilkorotenko.github.io/OutlookAddin_ItemSend_SmartAlerts/sample_64x64.png

Icon Present: A icon element was expected and is present.
  - Details: https://danilkorotenko.github.io/OutlookAddin_ItemSend_SmartAlerts/sample_32x32.png

Supported Icon URL File Extension: The manifest icon URL has a valid image file extension.
  - Details: png

The manifest icon URL uses HTTPS.: Secure Icon URL
  - Details: https://danilkorotenko.github.io/OutlookAddin_ItemSend_SmartAlerts/sample_32x32.png

Acceptance Test Completed: Acceptance test service has finished checking provided add-in.


Based on the requirements specified in your manifest, your add-in can run on the following platforms; your add-in will be tested on these platforms when you submit it to the Office Store:
  - Outlook on Windows (Microsoft 365)
  - Outlook on Mac (Microsoft 365)
  - Outlook on the web
Important: This analysis is based on the requirements specified in your manifest and does not account for any runtime JavaScript calls within your add-in. For information about which API sets and features are supported on each platform, see Office Add-in host and platform availability. (https://docs.microsoft.com/office/dev/add-ins/overview/office-add-in-availability).

*This does not include mobile apps. You can opt-in to support mobile apps when you submit your add-in.

The manifest is valid.

```

**Comment by DivyaPatidar** [comment]
@DanilKorotenko Looks like having same resid for launch events and taskpane is causing issue. Please try this updated manifest, it should fix the issue.
[manifest_smartAlerts_working.xml.zip](https://github.com/user-attachments/files/17936474/manifest_smartAlerts_working.xml.zip)

**Comment by DanilKorotenko** [comment]
Yes, It works. Thank you.
This issue can be considered as resolved.
