### ISSUE TITLE
Office Version 2401 - Excel Addin takspane stuck and not loading in debug mode from Visual Studio 2022

### ISSUE THREAD

**Issue by jnSWPC** [OfficeDev/office-js#4285]
## Your Environment
Office/Excel: Microsoft® Excel® for Microsoft 365 MSO (Version 2401 Build 16.0.17231.20290) 64-bit 
Microsoft Visual Studio Professional 2022 (64-bit) - Version 17.9.4

## Expected behavior
Excel Add-In-> Visual Studio -> debug mode -> Taskpane loads. 

## Current behavior
Excel Add-In-> Visual Studio -> debug mode ->  Taskpane does NOT load. Stuck in gray/white screen
Works with older version of office  like  2312. Stopped working after office upgrade to version 2401

Appreciate any insights into this issue.

**Comment by samantharamon** [comment]
Hi @jnSWPC. Thanks for reporting this. Are you still experiencing this issue in your current Office version? If so, are you testing with the Excel Web Add-in template in Visual Studio or with your own customized add-in?
