### ISSUE TITLE
Office sometimes ignores no-cache meta tags

### ISSUE THREAD

**Issue by manuelsidler** [OfficeDev/office-js#4286]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel, Word, PowerPoint, Outlook
* Office version number: -
* Operating System: Windows, Mac
* Browser (if using Office on the web): -
 
## Expected behavior
When using no-cache Metatags in our index.html file, I'd expect Office to not cache the HTML file:
```html
<!doctype html>
<html lang="en">
    <head>
        ...
        <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
        <meta http-equiv="Pragma" content="no-cache">
        <meta http-equiv="Expires" content="0">
        ...
    </head>
    <body>
        ...
    </body>
</html>
```

## Current behavior
When updating our add-in, some users still see the old index.html file. _Right click -> Reload_ does load the current index.html. But when closing and opening the add-in, the old version appears again. Users have to explicitly clear the web cache. That's a very bad user experience.

As it doesn't happen all the time and for all users, how and when does Office cache the index.html file of an add-in and why does it ignore the no-cache meta tags in those cases?

The caching issue appears on Outlook for Windows as well as on Outlook for Mac.

**Comment by jimbarrett33** [comment]
FYI. This also occurs on Excel Clients. I believe Excel online is ok.

**Comment by Adrian-MSFT** [comment]
Hi @manuelsidler I'm unable to repro this. Can you provide a version number? Also, do you have any steps that consistently repros this?

**Comment by mrebuffet** [comment]
Hi we faced a similar issue a few weeks ago on Outlook for Mac and we solved it by adding an extra header `'Vary': '*'`
In our case it was caching URLs even if the query parameters were changing.

Our full list of headers to prevent caching on Outlook for Mac is: 
```ts
'Cache-Control': ['no-store', 'no-cache'],
'Pragma': 'no-cache',
'Expires': '-1',
'Vary': '*'
```

I hope this helps

**Comment by manuelsidler** [comment]
@Adrian-MSFT Unfortunately, we're not able to reproduce it consistently. It's been a while since a user reported a caching issue. I'll provide more information if it happens again.

@mrebuffet we'll give that a try, thank you!

**Comment by Adrian-MSFT** [comment]
Thanks for the update @manuelsidler. I will close this for now. If needed, please re-open the issue
