### ISSUE TITLE
Synchronizing excel files, Script Lab custom functions change their name (from Mac to Windows, or viceversa)

### ISSUE THREAD

**Issue by kuworking** [OfficeDev/office-js#4290]
If I use a custom function defined in Script Lab, invoking it as normal.

`=SCRIPTLAB.TK.SPECS(V21,X21,AB21,AF21,AH21)`

When I open the same excel file in another computer, the synced version changes the names and doesn't work.

`=_xldudf_SCRIPTLAB_TKFUNCTIONS_SPECS(V21,X21,AB21,AF21,AH21)`

I can only test it when having a Mac and a Windows computers in both sides (so maybe this only happens when changing OS?).

I imagine that this has been solved here 
https://stackoverflow.com/questions/76045459/office-excel-addin-custom-functions-are-not-being-called-on-the-windows-excel-ap

I reproduce the answer here:

_Good day!_

_After closely working with our engineering team please find the update. In the parsing of manifest, Runtimes will be parsed first, and its unique identifier is resid. In your manifest, the sharedruntime's resid is "Taskpane.Url"(). When Excel installs the Custom Function (this happens after Runtimes is parsed), it will read the resid in CustomFunctionExtensionPoint's page item, and then find the runtime corresponding to the resid in the parsed Runtimes. In your scenario, Excel cannot find a runtime with resid "Function.Page.Url", so it recognized your custom function as non-sharedruntime by default. By explaining this specific process, I want you to inform that in the parsing of manifest, Excel will match the custom function and runtime by resid , not the specific value of this resid in "<bt:Urls>" tag. This matching rule also applies to other resid. Please modify the resid from Functions.Page.Url to Taskpane.Url._

_If the issue still exists, please feel free to reply back to the email I will be happy to assist you further on the request._

**The problem is that with Script Lab, I do not have access to the manifest**. If I share it through a Gist, I neither see the manifest.

So, is there any workaround?

*I am using the desktop version of excel from an office365 subscription

//EDIT
This also happens when opening the excel from two different Windows-computer excels. What works in one Windows-excel with the custom function name `SCRIPTLAB.TK.SPECS()`, gets transcribed as `_xldudf_SCRIPTLAB_TKFUNCTIONS_SPECS()` in another Windows-excel, so it is not OS-related.

It looks like Script Lab custom-functions is only useful to test add-ins within one single excel app, but it is not useful to deploy those custom-functions in other excels.

Is it so? Or there is something I can do to solve this?

** I've forgotten to say that in all Excel instances I have copied the relevant code to the Script Lab, so all of them have the custom functions added and enabled, and they do work if I write a new formula with the correct name `SCRIPTLAB.TK.SPECS()`

**Comment by rundongmsft** [comment]
Hi @kuworking, I think "_xldudf_SCRIPTLAB_TKFUNCTIONS_SPECS" in your scenario is a by-design behavior. The root cause of "_xldudf_" in Script Lab is different from other add-ins. So, the solution in manifest is not related to Script Lab. "_xldudf_" means at this time Excel cannot recognize this Custom Function, because it is not registered. The particularity of Script Lab is that it **dynamically** registers the Custom Function (This is an experimental feature, it is unstable and has not been officially released). As the result, if you don't manually click "register" in Script Lab to register a Custom Function, the value of this Custom Function in a cell will show "_xldudf_".
