### ISSUE TITLE
Fetch the displayed string values of a range by JavaScript API

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#4291]
In Excel, a value can be displayed differently with different format. For instance, 45374 is displayed as `45374` when its format is `General`. 45374 is displayed as `23/03/2024` when its format is `m/d/yyyy` (a date).

The following code loads the property `values` and `numberFormat` of a range, we can see that when `numberFormat` is different, the display is different.

Now, I would like to get the displayed string values such as `45374`, `45374,00`, `45374,00 €`, `23/03/2024`, `samedi 23 mars 2024`, `00:00:00`. Does anyone know if there is any API to do so?

```
const address = 'Sheet1!A1:D6';
const context = new Excel.RequestContext();

const range = context.workbook.worksheets.getActiveWorksheet().getRange(address);
range.load(["values", "numberFormat"]);
await context.sync();

console.log("range.values", range.values);
console.log("range.numberFormat", range.numberFormat)
```

[![enter image description here][1]][1]

[![enter image description here][2]][2]

[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/qqXWz.png
  [2]: https://i.stack.imgur.com/RMJ8Q.png
  [3]: https://i.stack.imgur.com/RFeUx.png

**Comment by SiruiSun-MSFT** [comment]
Hi @chengtie, range.values will returen the basic value of each cell. If you want to get the display string, we would recommend you to use range.text API. Here is the reference link:https://learn.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#excel-excel-range-text-member. Hope this will help you out!
