### ISSUE TITLE
Office.context.mailbox.item.bcc.addAsync failing to visibly add an email address to an email, problem appears related to performance / timing, difficult to reproduce and sometimes works

### ISSUE THREAD

**Issue by SethDG** [OfficeDev/office-js#4296]
# Provide required information needed to triage your issue

- Our add-in uses a call to Office.context.mailbox.item.bcc.addAsync to add an additional recipient to an email
- This was working fine and visibly adding the recipient on Friday (2024-03-22)
- This was first identified as failing sometime today (2024-03-25) but it could have broken anytime after Friday
- Now what happens is the call is made and there is no error but the user is not visibly added to the email
- This currently has only been identified as happening in Outlook web.  We've seen the problem in Chrome and Firefox.  No reports of failures from users using Outlook desktop clients have been reported.
- The problem appears to be performance/timing related and is very difficult to reproduce and sometimes works.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Windows 11 & Mac
* Browser (if using Office on the web): Chrome & Firefox
 
## Expected behavior

We expect when calling Office.context.mailbox.item.bcc.addAsync that the new recipient is visibly present in the email

## Current behavior

Currently when calling Office.context.mailbox.item.bcc.addAsync there is no new recipient is visibly present in the email

## Steps to reproduce

1. Call Office.context.mailbox.item.bcc.addAsync
2. Visibly inspect the list of BCC recipients in your email
3. ______

## Link to live example(s)

I will begin working on an example asap, but didn't want to wait to get this bug created so it could be triaged.

# Provide additional details

tbd

## Useful logs

There are no console errors when this happens

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by bchenhs** [comment]
@exextoc We are seeing the same errors. Here are a couple of errors we are seeing in case it helps:

`setBCCRecipients failed - InsufficientItemPermissionsError: 9038`
`setBCCRecipients failed - InternalFormatError: 9002`

[Update]
- The errors seems to have reduced significantly since 11am EST. It will still be great to figure out what happened.

**Comment by SethDG** [comment]
is there anyway for us to know what changes were released between (2024-03-22) and (2024-03-25) ?

**Comment by SethDG** [comment]
We have a theory that the problem is resulting from an email address where the portion before the @ is longer than 64 characters and being rejected.  Could that be the case?

**Comment by SethDG** [comment]
We have modified our code to generate email addresses with shorter strings before the @ sign that are less than 64 characters and things appear to be working now

**Comment by rgmills** [comment]
We're experiencing the same issue. To add, we're seeing it on the new Outlook experience in Windows as well.

@JuaneloJuanelo - Any idea if this is something that will be resolved in Outlook or add-in developers needing to make changes across the board here?

**Comment by rkpathak** [comment]
@rgmills Please create a new issue with your environment details. The original issue was acknowledged to be resolved.
