### ISSUE TITLE
Office.context.mailbox.item.getComposeTypeAsync on Outlook mobile client for iOS seems not to work

### ISSUE THREAD

**Issue by FSchlegel-BMM** [OfficeDev/office-js#4299]
# Provide required information needed to triage your issue
It's in the context of the onMessageComposeHandler event.
When using the Office.context.mailbox.item.getComposeTypeAsync on Outlook mobile client for iOS to detect type in our Outlook
addin, nothing happens and the signature is not inserted.

With the same code on Outlook mobile client for Android, the signature is inserted and everything looks fine.

We have  the same issue with these methods:

- Office.context.mailbox.item.to.getAsync
- Office.context.mailbox.item.cc.getAsync

As specified on this [page](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-mobile-apis#supported-apis), getComposeTypeAsync may be supported both.

I haven't found information about the 2 others. Where can I find specifications about those?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: iOS
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 4.2408.1
* Operating System: iOS
* Browser (if using Office on the web): N/A
 
## Expected behavior

Office.context.mailbox.item.getComposeTypeAsync returns the type of message compose and the related signature is inserted.

## Current behavior

The signature is not inserted.

## Steps to reproduce

1. create a onMessageComposeHandler event
2. add code to insert a signature based on the compose type

## Context

We have an addin for Outlook. The addin is connected to the user account on the SaaS BoostMyMail.

The event onMessageComposeHandler retrieve a list of signatures from the platform and insert the appropriate version on the mail of the user.

We want to add mobile support for our addin. Android is supported in our dev version but we encounters issues for the iOS.

**Comment by fabienschlegel** [comment]
Hi,

After further investigation, the problem is on my side and comes from a misuse of the event.completed() method.

Asynchronous functions seem slower on iOS than on Android, and an event.completed() passed before the getComposeType method on iOS.

This is what I was able to deduce from my various tests.

The problem has now been solved.

Thanks for your work and support.
