### ISSUE TITLE
The Office.context.officeTheme property is undefined in Outlook 2016

### ISSUE THREAD

**Issue by eblancperso** [OfficeDev/office-js#43]
The property Office.context.officeTheme is undefined when used in the Outlook application: [Official documentation](https://dev.office.com/reference/add-ins/shared/office.context.officetheme). In Word, Excel and PowerPoint, the property is defined and I can access its children properties (bodyBackgroundColor, controlForegroundColor, etc...). I tried with both latest (1.1.0.13) and previous (1.1.0.12) versions of Office.JS but it doesn't work.

## Expected Behavior
The officeTheme property inside the context provides bodyBackgroundColor, controlForegroundColor, etc... in all applications

## Current Behavior
The officeTheme property inside the context is undefined in Outlook

## Steps to Reproduce, or Live Example
```
Office.initialize = function (reason) {
    $(document).ready(function () {

        // The "Office" object and its "context" property are valid but the "officeTheme" property is undefined.
        // This works in Word, Excel and PowerPoint but not in Outlook.
        if (!Office.context.officeTheme) {
            console.log("Office theme not loaded");
        }
    });
}
```

## Your Environment
PC desktop
Outlook 2016
Version 1711 Build. 8730.2127

**Comment by dmahugh** [comment]
Closing this old issue, which should be fixed in current builds. Apologies for the delayed response, and please let us know if the problem persists.
