### ISSUE TITLE
displayNewAppointmentForm fails on Outlook for windows to get latest saved Roaming settings.

### ISSUE THREAD

**Issue by neso613** [OfficeDev/office-js#430]
I am developing an Outlook for Windows Add-in using Office.js. I am using Office.context.mailbox.displayNewAppointmentForm() to open an Appointment window programmatically:
`Office.context.mailbox.displayNewAppointmentForm(
{
  location: '{Location}',
  subject: '{subject}',
  body: '{some text}'
});`

I have designed Setting window UI to take user data and save the data programmatically into Roaming Settings of Outlook and get that saved Roaming Settings using below line of code:
`var settings= Office.context.roamingSettings.get('key');`

I have defined 
`<Action xsi:type="ExecuteFunction">
                                <FunctionName>MyOwnAppointment</FunctionName>
                       </Action>`
into manifest.xml file.

In FunctionFile.js, I have defined MyOwnAppointment function as:
function MyOwnAppointment(event){
`var settings= Office.context.roamingSettings.get('key');
Office.context.mailbox.displayNewAppointmentForm(
{
  location: settings.data1,
  subject: settings.data2,
  start: settings.data3,
  end: settings.data4,
  body: '{some text}'
});
event.completed();
}
`
When I call MyOwnAppointment() using UI(addin command), an New Appointment is opened with the last saved setting (i.e. last roaming settings saved before outlook close). Settings is updated multiple times but MyOwnAppointment() does't reflect untill we restart Outlook.

## Expected Behavior
New Appointment is opened with latest saved Roaming Settings of same session. It should not need to restart the outlook to reflect settiings.

This is not an issue with Outlook for Mac.This issue is only with Outlook for Windows.

## Current Behavior
When I call MyOwnAppointment() using UI(addin command), an New Appointment is opened with the last saved setting (i.e. last roaming settings saved before outlook close). Settings is updated multiple times but MyOwnAppointment() does't reflect untill we restart Outlook.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Outlook for Windows
* Host [Excel, Word, PowerPoint, etc.]: Outlook

**Comment by exextoc** [comment]
This is a known limitation of the RoamingSettings API.

From the roaming settings [doc](https://docs.microsoft.com/en-us/javascript/api/outlook_1_7/office.roamingsettings?view=office-js): The RoamingSettings object is initialized from the persisted storage only when the add-in is first loaded. For task panes, this means that it is only initialized when the task pane first opens. If the task pane navigates to another page or reloads the current page, the in-memory object is reset to its initial values, even if your add-in has persisted changes. The persisted changes will not be available until the task pane is closed and reopened.

In the case of uiless commands, the RoamingSettings will only be available when the item is closed and re-opened.

**Comment by nehasoni3** [comment]
> This is a known limitation of the RoamingSettings API.
> 
> From the roaming settings [doc](https://docs.microsoft.com/en-us/javascript/api/outlook_1_7/office.roamingsettings?view=office-js): The RoamingSettings object is initialized from the persisted storage only when the add-in is first loaded. For task panes, this means that it is only initialized when the task pane first opens. If the task pane navigates to another page or reloads the current page, the in-memory object is reset to its initial values, even if your add-in has persisted changes. The persisted changes will not be available until the task pane is closed and reopened.
> 
> In the case of uiless commands, the RoamingSettings will only be available when the item is closed and re-opened.

Agree. But the same things works fine with Outlook for Mac.

**Comment by neso613** [comment]
Agree. But this same is working well as expected 
with Outlook for Mac.

**Comment by exextoc** [comment]
This is the expected behavior for RoamingSettings on the Outlook for Windows client. It is possible that this is only a limitation specific to Outlook for Windows and the Outlook Web App.

**Comment by neso613** [comment]
Can I expect that the fix of this limitation is made in future soon?

**Comment by exextoc** [comment]
This is a known bug and it is currently in our backlog. Unfortunately, there is no timeline at this time for when this might be fixed. A workaround is to close and re-open the mail item in order to retrieve the saved Roaming Settings.

**Comment by neso613** [comment]
OK.Thanks for replying and making it clear.

**Comment by kanaksony** [comment]
Hi, This is still not fixed an must remain open.

**Comment by exextoc** [comment]
The bug has been acknowledged & since we do not have concrete timelines, we are closing this issue. We have an internal bug number that is linked to this post. Whenever this is fixed, we will make sure to respond to this post with the build numbers that have the fix. Internal Bug#: 1053556

**Comment by asith-w** [comment]
any update ?
