### ISSUE TITLE
graph.microsoft.com/beta/users/[id]/usageRights throws 500 error about 30% of the time (I know it's beta but that is a lot of failures)

### ISSUE THREAD

**Issue by jimbarrett33** [OfficeDev/office-js#4304]
I have an app that calls graph.microsoft.com/beta/users/[id]/usageRights API and my logs show that it fails about 30% of the time. I know beta is unsupported but this seems like a lot of 500 Internal Server Errors, even for a beta. It's been happening since I started using the API approximately Aug 2023.

Asking/reporting this because if the usageRights API ever goes to the /1.0 endpoint it seems like something that should be addressed. (I hope usageRights goes to /1.0 at some point soon as it's been in beta for over 3 years.)

Also reporting this so other developers using the usageRights API can know what is happening if they don't know already/

Note that a certain percentage of the time a retry a couple seconds later (by the user) actually succeeds so it's not an issue with the API invocation signature or parameters.

I intend to put a retry for the 500's in code but still seems like a lot of 500 failures to deal with.

I have issued a support request but they are no help.

It is somewhat related to documentation because the following docs recommend using the usageRights API and the second doc linke below actually makes the statement "After the version is updated to V1, ISVs should upgrade from beta to V1 version when available."

I'm trying to help the technical team to address this issue before the API moves to the live 1.0 endpoint.

[Monetize your app through Microsoft Commercial Marketplace](https://learn.microsoft.com/en-us/partner-center/marketplace/monetize-addins-through-microsoft-commercial-marketplace#implement-license-management)

[ISV app license management for SaaS offers](https://learn.microsoft.com/en-us/partner-center/marketplace/isv-app-license-saas?branch=main#how-to-use-usagerights-api)

(Note: I was told to post this issue on office-js Github by someone at Microsoft so it would get some attention or at least elevated to the correct team at Microsoft. Thanks.)

## Your Environment
Add-in deployed via AppSource with server-side code that calls the usageRight endpoint with current user token using the OBO auth flow.
 
## Expected behavior
API shouldn't throw 500 errors that often, even for a beta endpoint.

## Current behavior
Throws 500 error with no additional 

## Steps to reproduce
- Possibly use graph explorer tool but I haven't seen the issue here
- an automated test that calls the usageRights API in a loop
- create an add-in with server code that calls the usageRights API for the current user

## Context
My add-in is live (and monetized) via AppSource so the impact is that I am losing customers.

## Useful logs
Attached are screen shots of Azure logs: 1) showing about 30% failure rate of the API over a 7 month period, 2) calls/timeline of a single failure
1) ![ms-graph-api-500-errors-7-months-logs-showing-errors](https://github.com/OfficeDev/office-js/assets/8396655/8d9cbf8a-552d-457b-928b-8229b9880a16)

2) ![ms-graph-api-500-errors-logs-picture](https://github.com/OfficeDev/office-js/assets/8396655/5220cffa-4ba3-443f-a752-8dea255a64aa)

**Comment by JuaneloJuanelo** [comment]
hello @jimbarrett33  unfortunately this is not the right place to report Grpah issues, please try this: https://learn.microsoft.com/en-us/answers/tags/161/ms-graph 

this git is related to mostly Office Web  Add-ins using Office.hs

**Comment by jimbarrett33** [comment]
@JuaneloJuanelo Thanks but that link is not helpful at all. I'm just trying to tell someone at Microsoft that the usageRights API is very broken. I have tried support requests, various GitHub issues, and StackOverflow. Not sure what else to do at this point but I could make the argument that deployment, and optional monetization, of add-in's falls under the Office Extensibility umbrella as it IS included in the office developer documentation: https://learn.microsoft.com/en-us/office/dev/add-ins/publish/publish
