### ISSUE TITLE
Error 2147467259 when requesting a token on Outlook iOS

### ISSUE THREAD

**Issue by thomasdarde** [OfficeDev/office-js#4305]
# Provide required information needed to triage your issue
We can't get an access token from Outlook iOS

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]:  iOS
* Host [Excel, Word, PowerPoint, etc.]: Outlook iOS
* Office version number: 4.2410
* Operating System: iOS (latest version)

 
## Expected behavior

This function should allow us to get an AccessToken
`Office.context.mailbox.getCallbackTokenAsync({ isRest: true },  (result) =>  {result.value})`

## Current behavior

We are getting an error code instead : 9017 AccessRestricted 2147467259

# Provide additional details
This code is executed from commands.js , with the exact same settings than our Application which is working fine on other platforms

## Context
We try to make our Addin iOS Compatible

**Comment by JuaneloJuanelo** [comment]
Hello @thomasdarde  thanks for reporting this issue we are currently investigating it.

**Comment by rajjha-msft** [comment]
Hey @thomasdarde

- On which surface the API is invoked or what is the type of extension point?
- What is the Add-in permission in the manifest?

**Comment by thomasdarde** [comment]
Hi @rajjha-msft 

These are the specific lines for Mobile

```
<MobileFormFactor>
            <!-- Configures event-based activation. -->
            <ExtensionPoint xsi:type="LaunchEvent">
              <LaunchEvents>
                <LaunchEvent Type="OnNewMessageCompose" FunctionName="onNewMessageComposeHandler"/>
              </LaunchEvents>
              <!-- Identifies the runtime to be used (also referenced by the Runtime element). -->
              <SourceLocation resid="WebViewRuntime.Url"/>
            </ExtensionPoint>
          </MobileFormFactor>
```

and the permissions are 

```
<Scopes>
          <Scope>User.Read</Scope>
          <Scope>profile</Scope>
          <Scope>openid</Scope>
          <Scope>email</Scope>
        </Scopes>
```

**Comment by ajays-msft** [comment]
@thomasdarde - Is this a consumer account or enterprise? If this is enterprise, is this a vanity domain? Did this api work previously for you on iOS? What is the behavior on Android?

**Comment by thomasdarde** [comment]
This is an enterprise account , the addin works on desktop for a lot of customers. Android and iOS are showing the same error message

**Comment by ajays-msft** [comment]
@thomasdarde - Are you seeing this issue recently and did it ever work before? Here is the list of supported apis in mobile

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-mobile-apis

**Comment by thomasdarde** [comment]
It never worked, the question would be : how do we get an authentication token on Mobile context ?

**Comment by thomasdarde** [comment]
Hi , any help on this issue ? (we have a solution but it would be nice to have the expected behaviour to authenticate a user on mobile)

**Comment by rkpathak** [comment]
This API was not implemented on Message Compose Surface as itemID is not available when OnMessageComposeEvent triggers add-in run. Fix for this is being rolled out. We will update this when its available world wide.

**Comment by thomasdarde** [comment]
Hi @rkpathak any update on this ?

**Comment by anjalitp** [comment]
@thomasdarde The fix has been rolled out to Production for versions >= 4.2408 on both Outlook iOS and Android.
