### ISSUE TITLE
[Word] Receiving null ID to `onAnnotationClicked` handler

### ISSUE THREAD

**Issue by greysteil** [OfficeDev/office-js#4307]
# Provide required information needed to triage your issue

When using a handler set up by `context.document.onAnnotationClicked.add(...)` I am receiving `null` IDs if my add-in has previously been closed and then re-opened on a document (after adding a handler before being closed).

The issue only occurs if a previous handler for annotations was set up. The first time I open my add-in on a doc the handler receives annotation events with IDs, as expected. If I don't close the add-in (via the task bar (x) - I'm not using a shared runtime) everything continues to work. However, if I then close and re-open my add-in (via the task bar (x)) my handler starts receiving null IDs after I re-add it.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.83 (24031120)
* Operating System: MacOS 14.3 (23D56)
* Browser (if using Office on the web): N/A
 
## Expected behavior

A handler added with `context.document.onAnnotationClicked.add(...)` should always receive the ID of the annotation that has been clicked.

## Current behavior

If the following steps are followed, a handler added with `context.document.onAnnotationClicked.add(...)` will receive only `null`:
* add a handler with `context.document.onAnnotationClicked.add(...)`
* close the taskpane (on an add-in not using a shared runtime)
* re-open the taskpane
* add another handler with `context.document.onAnnotationClicked.add(...)`
* annotate some text
* click on an annotation

## Steps to reproduce

See above

## Link to live example(s)

My code is private, but if you cannot replicate please ask and I can try to create an example

# Provide additional details

N/A

## Context

This issue makes `onAnnotationClicked` unreliable. I can't use this in my production app because users might experience non-interactive annotations, causing confusion.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by xuruiyao-msft** [comment]
@greysteil Thanks for reaching out to us. I can reproduce the issue following the detailed steps you provide. I've created the work item (8879387) to track the issue. If anything updated, we'll sync with you. Thanks again for reporting it to us.

**Comment by greysteil** [comment]
Great to hear you can replicate. You've tagged this with "Needs: author feedback" - does that mean you need more from me?

**Comment by jipyua** [comment]
hi @greysteil thanks for letting us know about this issue. We have fixed it internally and now it's in the process of rolling out. Normally on Word win32/mac you should be able to try the fixing in early June. Feel free to close this issue and let's know for any other topics. thanks.

**Comment by greysteil** [comment]
That's great news, thanks @jipyua. I'll close this and wait for the fix - it's good to know timelines.

https://github.com/OfficeDev/office-js/issues/4317 is the other issue I'd love to see resolved - that one's blocking me rolling out annotations to our customers. I'll do some extensive testing and se if I can isolate any other issues, too.

Thanks again! :octocat:
