### ISSUE TITLE
mcas with Outlook is blocking Add-in authentication flow | 

### ISSUE THREAD

**Issue by gs-skujala** [OfficeDev/office-js#4308]
### My Add-in authentication flow breaks for our client who are using outlook with MCAS.

Add-in opens a new tab so user can provide login credentials for authentication and the auth info is sent back to add in via Office.js events. But add-in does not receive any auth information from the new tab

Authentication flow:
1. In our Add-in taskpane.js, we navigate to new tab via 
    `return Office.context.ui.displayDialogAsync(url, {..., callback: ()=>{}});`
In Callback method, we register an event listener `Office.EventType.DialogMessageReceived` which is expected to trigger when authentication in the new tab is successful
2. In the new tab that is opened, it navigates to following URL after login process is done
`https://<my domain>.com.mcas.ms/<my version>/taskpane/loginsuccess.html?....`
This page is loaded with Office.js CDN & executes below script which will return the auth info back to Add in
`Office.context.ui.messageParent(...authInfo);`
FYI, we use `Office.onReady` for initialisation of script

Here we observed that the `DialogMessageReceived` event is never called so Add-in never gets auth info from success.html page

Our Add in URL is as below
`https://<my domain>.com.mcas.ms/<my version>/taskpane/taskpane-compose.html?et=&McasTsid=20000`

## Your Environment
* Platform: Mac, Office on the web
* Host: Outlook
* Office version number: all
* Operating System: Mac
* Browser: Safari, Chrome
 
## Expected behaviour 
Authentication behaviour should be completed
Which means, `DialogMessageReceived` event must be triggered once the auth info is shared from new tab via `messageParent`

## Current behaviour 
Authentication behaviour is not completed
Which means, `DialogMessageReceived` event is never triggered even though the `messageParent` method is triggered from new tab

# Provide additional details
1. Add-in URL: `https://<my domain>.com.mcas.ms/<my version>/taskpane/taskpane-compose.html?et=&McasTsid=20000`
2. new tab URL: `https://<my domain>.com.mcas.ms/<my version>/taskpane/loginsuccess.html?....`

**Comment by rajjha-msft** [comment]
Hey @gs-skujala 

- Can you provide a sample add-in which we can use to reproduce the same? It is not a repro for us. 
- Is this working fine of other platforms?
- Is this a regression which stated recently?
