### ISSUE TITLE
OnSend event triggers twice on New Outlook for Mac when setting recipients to the email using .saveasync

### ISSUE THREAD

**Issue by avisheknand** [OfficeDev/office-js#4311]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.83.2 (2024032318)
* Operating System: Mac OS Ventura
* Browser (if using Office on the web):
 
## Expected behavior
OnSend event should trigger only once and email should be sent out.

## Current behavior
OnSend event triggers twice on New Outlook for MAC . However, does not trigger twice on Legacy Outlook.

This is happening when you try to perform .SaveAsync for all recipients (TO, CC, BCC)

## Steps to reproduce
1.) Open New Outlook MAC
2.) Send Email with at **least 5 recipients** in the email , having a add-in installed that uses OnSend event,  and is updating/setting recipients in email via the event. The On-Send fires twice for the add-in

# Provide additional details
We have reported this [issue ](https://github.com/OfficeDev/office-js/issues/3753) last year. We were told to call event.completed after all async API calls are completed by Add-in.  We did verify , all async APIs calls are completed before the event, but issue still happens. From our investigation it seems like when we have the .SaveAsync for recipients it causes the issue. If we remove the code it works fine. The following are the code

![image](https://github.com/OfficeDev/office-js/assets/80862413/adcc0038-0e06-4b47-83d6-fb292de16377)
![image](https://github.com/OfficeDev/office-js/assets/80862413/17b5b85b-aedb-4aaa-a7a5-2481a77e3473)

I have also performed collect diagnosis on Outlook for Mac and the **incident Id is : SJQ3N93Y**

**Comment by rajjha-msft** [comment]
@avisheknand 

It is not a repro for us.

- Can you please create a sample add-in and attach which can be used to reproduce the issue?
- Also, when you say OnSend event is it ItemSend or the new Smart alerts ?
