### ISSUE TITLE
In new Outlook version Authentication not working

### ISSUE THREAD

**Issue by Ravi-Royal-143** [OfficeDev/office-js#4314]
![Screenshot 2024-03-29 204954](https://github.com/OfficeDev/office-js-docs-pr/assets/81796854/546f23b6-0077-413c-a056-5ee4fb3a4a0f)
This is the screenshot of newer outlook version & Web version, Cookie is not shared to the appropriate request, where the same code shares the Cookie to the API in the older (classic ) Outlook version. See below screenshot for reference. What is the requried changes on new version for sharing the cookie(token) to backend for authentication. 

![Screenshot 2024-03-29 205325](https://github.com/OfficeDev/office-js-docs-pr/assets/81796854/c72b34d4-48b5-4286-afe0-0ff3fdf1e17f)

**Comment by AlexJerabek** [comment]
Hi @Ravi-Royal-143,

Thank you for reporting this. This seems to be a product issue, so I'm going to transfer it to the [office-js repo](https://github.com/OfficeDev/office-js). There, members of the Outlook extensibility feature crew can take a look.

**Comment by rkpathak** [comment]
@Ravi-Royal-143 Please describe your use case. Are you using any office-js API, if yes add some code snippet that is calling the API and failure logs if any. Also share a repro video if possible.
