### ISSUE TITLE
Replace in content control using clear + insertParagraph at Start location

### ISSUE THREAD

**Issue by Trophalaxeur** [OfficeDev/office-js#4316]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: ______
* Operating System: linux
* Browser (if using Office on the web): Chrome
 
## Expected behavior

When i clear a content control and add a new text inside it (with location === start). I'm expecting to have the new text replacing the old one.
```
contentControl.clear();
contentControl.insertParagraph("11111", "Start");
```

(With a location set to End, it works fine)

## Current behavior

It got an error, the contentControl is cleared but the new text is not inserted. I have the following error in the console :
```
index.tsx:81 RichApi.Error: Cannot read properties of null (reading 'setValue')
    at new n (word-web-16.00.js:25:336110)
    at o.processRequestExecutorResponseMessage (word-web-16.00.js:25:400557)
    at word-web-16.00.js:25:398620
```

## Steps to reproduce

1. Setup
2. Insert Content control
3. modify Content control

## Link to live example(s)

https://gist.github.com/Trophalaxeur/98b12bef1eb528285acc94ae86ea6023
1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

I try to replace the content of a contentControl

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
- [ ] 
![image](https://github.com/OfficeDev/office-js/assets/6755684/4d774031-60ec-4319-9d2a-2d7b8db2f2ee)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by xiruatms** [comment]
@Trophalaxeur , thanks for reporting this, but I can't repro the issue you reported. Can you confirm whether this issue is still encountered? Or will you please share more details of your testing environment?

![image](https://github.com/OfficeDev/office-js/assets/40648203/7e228e74-5dc0-45d4-abf7-47760e775915)

**Comment by Trophalaxeur** [comment]
@xiruatms With this gist, it happened if i click twice on the "Modify content" button.
(i just retested it)

I made a Loom video if it could help

**Comment by xiruatms** [comment]
@Trophalaxeur , thanks for your patience. The fix is now on production. Will you please help to take one more try to see whether it works?
