### ISSUE TITLE
[Word API 1.7] MacOS: Batch delete annotations initial failure and 'ItemNotFound' error; annotation insertion delays. 

### ISSUE THREAD

**Issue by benDefinely** [OfficeDev/office-js#4319]
## Summary of the issue
I have modified the insert and delete functions from the 1.7 API update documentation GitHub code to create: 
 
1. a function to 'batch' insert multiple annotations into a Word Document based on a JSON file (with information about associated paragraph indexes, position in a paragraph, word length, and critique colour) and record each annotation ID when inserted. 
 
And
 
2. a function to 'batch delete' all annotations based on annotation IDs. 
 
We are currently experiencing difficulties with the delete function when attempting to remove all annotations from the document. The issue is that the first attempt to delete the annotations consistently fails: there is no error and none of the annotations are removed. If we press delete again then we encounter an `ItemNotFound` error during the 'context.sync()' process.
 
If we remove and re-insert all text and then run the same two functions, the delete function can always remove all annotations from the document.
 
## Environment
* Platform: Mac
* Host: Word
* Office version number: 16.83 (24031120)
* Operating System: macOS Sonoma Version 14.1.2
 
## Expected behaviour
Click ‘insert annotations’ -> all annotations inserted into the document within a reasonable time, plus save each annotation ID into a Set as it is inserted.
 
Click ‘delete annotations’ -> all annotations are removed from the document by annotation ID within reasonable time. 
 
## Current behaviour
Click ‘insert annotations’ -> all annotations inserted into the document, plus save each annotation ID into a Set as it is inserted (experience ~10 seconds of wait/lag for documents > 300 pages). 
 
Click ‘delete annotations’ (after first opening document) -> no annotations are removed from the document but there is no error.
 
Click ‘delete annotations’ (after first click) -> no annotations are removed from the document and `ItemNotFound` error.
 
Click ‘delete annotations’ (after removing and reinserting text) -> all annotations are removed from the document (experience ~10 seconds of wait/lag for documents > 300 pages). 
 
### 1. Insert Annotations
```
async function insertAnnotations(greenWords, redWords, annotationIds) {
    annotationIds.clear();
 
    await Word.run(async (context) => {
        context.document.onAnnotationInserted.add(function(eventArgs) {
            // Store the annotation IDs for deletion later
            eventArgs.ids.forEach(id => annotationIds.add(id));
 
        });
 
        const paragraphs = context.document.body.paragraphs;
        paragraphs.load('items');
        await context.sync();
   
        let paragraphCritiques = new Map();
        
        /* 
        we populate paragraphCritiques with a json file that has data on the paragraph 
        index, start position, length, and colour of each word we wish to annotate.
        We get paragraphCritiques = {paragraphIndex: [critique1, critique2, ...], ...}, 
        where critique = {start: number, length: number, colour: string}
        */
 
        paragraphs.items.forEach((paragraph, index) => {
            if (paragraphCritiques.has(index)) {
                const critiques = paragraphCritiques.get(index);
                let annotationSet = { critiques: critiques };
                try {
                    paragraph.insertAnnotations(annotationSet);
                } catch (error) {
                    console.error('Failed to insert annotations:', error);
                }
            }
        });
 
        await context.sync().then(() => {
            console.log("All annotations inserted.");
        }).catch(error => {
            console.error('Failed to insert annotations:', error);  
        });
 
    }).catch((error) => {
        console.error('Error:', error);
    });
}
```
### 2. Delete Annotations
```
async function deleteAnnotationsByIds(annotationIds) {
 
    await Word.run(async (context) => {
        await context.sync()
        for (let id of annotationIds) {
            try {
                const annotation = context.document.getAnnotationById(id);
                annotation.delete();
            } catch (error) {
                console.error(`Error deleting annotation with ID ${id}:`, error);
            }
        }
 
        await context.sync().then(() => {
            console.log("All annotations deleted.");
        }).catch(error => {
            console.error('Failed to delete annotations:', error);  
        });
 
    }).catch(error => {
       console.error('Error:', error);
    });
}
```
## Video snippet of error
https://github.com/OfficeDev/office-js/assets/154002494/1b85cf62-f192-40cb-9f63-789af5fd0734
 
## Context
This issue stops us from moving forward because we cannot be sure what is causing the function to fail when removing annotations.
 
The best solution would be to determine the visible range of the user (and therefore only annotate some small range of the document). Without this feature, we aim to insert and remove annotations from the whole document as efficiently as possible. Whenever the user begins to edit the document, we aim to remove all annotations and reinsert them when the user finishes editing. A key feature of Definely's product is the ability to identify and highlight definitions and references in a Word document (i.e., the current functionality of the Word plugin). The new 1.7 update that provides the annotation (underline) functionality is a huge step forward in accomplishing this goal in the Office App. 
 
## Useful logs
<img width="376" alt="ItemNotFound_Error" src="https://github.com/OfficeDev/office-js/assets/154002494/49b97455-a9fe-4f81-b0b2-1cc98e18cd3c">

## 1.7 API documentation GitHub code
https://raw.githubusercontent.com/OfficeDev/office-js-snippets/prod/samples/word/50-document/manage-annotations.yaml

**Comment by cbouzmsft** [comment]
I did not manage to replicate the issue using the code provided with my own document and set of annotations. Could you please provide a document and a set of annotations with which the issue occurs?

**Comment by jipyua** [comment]
@benDefinely  seems our side @cbouzmsft can't replicate the reported issue, would you please provide a document with annotations so that we can have a try?

**Comment by benDefinely** [comment]
Hi @cbouzmsft and @jipyua. Here is a test document and a set of annotations in a json file. 
[LMA_Critiques.json](https://github.com/OfficeDev/office-js/files/15074296/LMA_Critiques.json)
[LMA_Test.docx](https://github.com/OfficeDev/office-js/files/15074299/LMA_Test.docx)

The code is modified to extract the paragraph critiques directly from LMA_Critiques.json:

```
import $ from 'jquery';
var annotationIds = new Set();
import LMA_CritiqueObject  from 'path_to_src/src/taskpane/LMA_Critiques.json'

Office.onReady((info) => {
    if (info.host === Office.HostType.Word) {
        $("#insert-annotations").on("click", () => insertAnnotations(annotationIds));
        $("#delete-annotations").on("click", () => deleteAnnotationsByIds(annotationIds));
    }
});

async function insertAnnotations(annotationIds) {
    annotationIds.clear();
    await Word.run(async (context) => {
        context.document.onAnnotationInserted.add(function(eventArgs) {
            // Store the annotation IDs for deletion later
            eventArgs.ids.forEach(id => annotationIds.add(id));
        });

        const paragraphs = context.document.body.paragraphs;
        paragraphs.load('items');
        await context.sync();

        // Here we're not building paragraphCritiques, we're using the imported LMA_CritiqueObject.
        console.log(LMA_CritiqueObject);

        paragraphs.items.forEach((paragraph, index) => {
            const indexStr = String(index);
            if (indexStr in LMA_CritiqueObject) {
                const critiques = LMA_CritiqueObject[indexStr];
                let annotationSet = { critiques: critiques };
                try {
                    paragraph.insertAnnotations(annotationSet);
                } catch (error) {
                    console.error('Failed to insert annotations:', error);
                }
            }
        });

        await context.sync().then(() => {
            console.log("All annotations inserted.");
        }).catch(error => {
            console.error('Failed to insert annotations:', error);  
        });
    }).catch((error) => {
        console.error('Error:', error);
    });
}

async function deleteAnnotationsByIds(annotationIds) {
    await Word.run(async (context) => {
        await context.sync()
        for (const id of annotationIds) {
            try {
                const annotation = context.document.getAnnotationById(id);
                annotation.delete();
            } catch (error) {
                if (error instanceof OfficeExtension.Error && error.code === "ItemNotFound") {
                    console.log(`Annotation with ID ${id} does not exist.`);
                } else {
                    console.error(`Error deleting annotation with ID ${id}:`, error);
                }
            }
        }

        await context.sync()
        .then(() => {
            console.log("All annotations deleted.");
        })
        .catch(error => {
            console.error('Failed to delete annotations:', error);  
        });

    }).catch(error => {
        console.error('Error:', error);
    });
}
```

**Comment by benDefinely** [comment]
Hi @cbouzmsft and @jipyua. Did you manage to replicate the issue with the provided document and a set of annotations? Thanks.

**Comment by cbouzmsft** [comment]
There seems to be a bug in the code sample provided. In the deleteAnnotationsByIds function, the loop "for (const id of annotationIds)" seems to have no effect (it does not iterate over the elements).

I tried replacing it with forEach and it correctly iterates over the elements (and deletes the annotations).

    annotationIds.forEach((id, _) => {
      try {
        const annotation = context.document.getAnnotationById(id);
        annotation.delete();
      } catch (error) {
        if (error instanceof OfficeExtension.Error && error.code === "ItemNotFound") {
          console.log(`Annotation with ID ${id} does not exist.`);
        } else {
          console.error(`Error deleting annotation with ID ${id}:`, error);
        }
      }
    });

**Comment by benDefinely** [comment]
Thank you so much for your assistance on this issue, @cbouzmsft ! I missed that bug in the sample I provided, and I appreciate your help in finding it and resolving the error of deleting the annotations. I've conducted tests and can confirm that batch insert and delete annotations are functioning as expected. 

I also wanted to ask if there is a way to determine the user's visible range, with the goal of only inserting and deleting annotations within some sub-range of the whole document?

Again, thanks for your help!

**Comment by benDefinely** [comment]
Hi @cbouzmsft , I wanted to ask if you could explain in a bit more detail why the loop "for (const id of annotationIds)" worked when removing all the text and re-inserting it? I'm just curious as to how it managed to iterate over the elements then but not on the first attempt. Again, the new code is working perfectly - I'm just curious.

**Comment by cbouzmsft** [comment]
Regarding your first question regarding visible range, I am not aware. Regarding your second question, I have not investigated because it does not seem related to OfficeJS. If you want to investigate further, you should probably look at the implementation of enumeration in the Set class that is used.
