### ISSUE TITLE
Issue with folder upload when webkitdirectory enabeld in word add-in

### ISSUE THREAD

**Issue by aibek-draftwise** [OfficeDev/office-js#4322]
> office-js bot:
Internal issue 8980612 has been created.

# Provide required information needed to triage your issue
Word add-in does not allow users to select folders for upload when `webkitdirectory` and `directory` attributes of the input field are defined. Check it on Chrome, Edge, Safari, Edge browsers all are working fine except in add-in it does not work.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.71 (23031200)
* Operating System: Mac OS
* Browser (if using Office on the web): None (we are using office Word add-in)
 
## Expected behavior

Expected folder upload functionality to work

## Current behavior

No folder is being selectable, only files are selectable

## Steps to reproduce

We are using similar code in React:
```jsx
<input
          type="file"
          directory=""
          webkitdirectory=""
/>
```
Click onto the button and notice that folders are not selectable in add-in though in browser it is selectable.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

<img width="660" alt="upload folder err" src="https://github.com/OfficeDev/office-js/assets/127111525/0c35065b-9087-49bd-bfe4-0f762882b20a">

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 

This issue was closed Fixed

**Comment by shanshanzheng-dev** [comment]
Hi @aibek-draftwise, thanks for reporting the issue. if the issue still persists, could you share us the manifest and the repro steps? Thanks!

**Comment by shanshanzheng-dev** [comment]
Hi @croicu, I'm triaging this issue, seems like this is a add-in platform(webview) issue on Mac. Could you please help confirm this issue? Thanks.

**Comment by jargil** [comment]
We'll be looking into this problem, thanks for reporting! Can't share timelines, but will report back here if we end up rejecting or if we have a suggestion for you.

**Comment by aibek-draftwise** [comment]
Hi, can I please ask if there is any progress on this issue? We are still running into this problem.

**Comment by shanshanzheng-dev** [comment]
Hi @aibek-draftwise Sorry for slow response. We have fixed the bug and the fix should be available in build <[16.0.17728.41017](https://dev.azure.com/office/Office/_build/results?buildId=28712266)> or later. Depending on the release channel a customer is on, getting an updated build can take anywhere from 4-8 weeks, or longer if they are on the Semi-Annual Enterprise Channel.  Thanks.

**Comment by aibek-draftwise** [comment]
Hi @shanshanzheng-dev, thank you for your reply, that's awesome news! Could you please let me know how can I track the release of the patch? After clicking the link you have provided and authenticating, it seems I don't have an access.

**Comment by shanshanzheng-dev** [comment]
Hi @aibek-draftwise,let me update process for you when this fix works.
