### ISSUE TITLE
Office.context.mailbox.item.internetHeaders.setAsync throwing an error on replies

### ISSUE THREAD

**Issue by bei-zh** [OfficeDev/office-js#4326]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Office version number:Outlook for Microsoft 365 MSO (Version 2401 Build 16.0.17231.20236) 64-bit
* Operating System: Windows
 
## Expected behavior

Office.context.mailbox.item.internetHeaders.setAsync doesn't throw error in replies

## Current behavior

We're getting user reports of this issue but so far haven't been able to consistently reproduce the issue ourselves.

In our extension, we call Office.context.mailbox.item.internetHeaders.setAsync when the user opens a compose. This function is erroring fairly regularly when the user replies to an email. The user noted that it does not error as much when using the Web app, when composing a new email, or when using the pop-out window. Wondering if there's a reason this error seems to show up more in this specific reply scenario or if there's any additional handling we can add in our code to reduce this. Thanks!

**Comment by millerds** [comment]
Sorry for the delay in responding to this.  

@bei-zh can you tell me what the error is?  How many users are seeing it?

**Comment by millerds** [comment]
@bei-zh any comments?
