### ISSUE TITLE
Empty itemId on items of class IPM.Note.SMIME.MultipartSigned (Outlook, Mac)

### ISSUE THREAD

**Issue by manuelsidler** [OfficeDev/office-js#4330]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.83.3 (24033013)
* Operating System: macOS 14.4.1
* Browser (if using Office on the web): -
 
## Expected behavior
`Office.context.mailbox.item.itemId` has a valid value on all platforms and e-mails.

## Current behavior
On Outlook for Mac, we get an empty itemId on signed / encrypted e-mails (itemClass _IPM.Note.SMIME.MultipartSigned_)
<img width="458" alt="image" src="https://github.com/OfficeDev/office-js/assets/802015/1fa9bbc5-9cdd-403b-a951-674f1a8c8e10">

On Outlook for Windows and Outlook on the web the itemId has a valid value.

## Steps to reproduce
1. Clone the example GH repo to reproduce the issue (see link below)
2. Run the add-in with `npm install` and `npm run dev-server`
3. Side load the add-in on Outlook for Mac
4. Select a signed and/or encrypted mail
5. Open the add-in
6. The item class is _IPM.Note.SMIME.MultipartSigned_, but the ID is empty

## Link to live example(s)
- GitHub Repo with example to reproduce: https://github.com/manuelsidler/outlook-addin-playground

## Useful logs
Repro video:
https://github.com/OfficeDev/office-js/assets/802015/99ca2e21-e5c4-454e-9283-74631d44e16b

**Comment by rkpathak** [comment]
@manuelsidler Please give detailed steps to reproduce this issue. If possible record video while reproducing and share.

**Comment by manuelsidler** [comment]
@rkpathak I added a link to a sample repo, as well as detailed reproduction steps and a video recording.

**Comment by DivyaPatidar** [comment]
@manuelsidler Thank you for sharing detailed steps and repro video. The add-in you shared has <SupportsMultiSelect>true</SupportsMultiSelect> . Can you try removing that and then check if itemId is valid for SMIME and other items?

**Comment by manuelsidler** [comment]
@DivyaPatidar what do you mean by "The add-in you shared has true"?

**Comment by DivyaPatidar** [comment]
I mean SupportsMultiSelect is set to true. Github removed SupportsMultiSelect tags :
<img width="916" alt="Screenshot 2024-05-08 at 2 09 35 PM" src="https://github.com/OfficeDev/office-js/assets/20352028/552c42c7-0ac4-427f-8d5e-2b9098cfeeca">

**Comment by manuelsidler** [comment]
@DivyaPatidar I set _SupportsMultiSelect_ to `false`. Unfortunately, the `itemId` is still empty for signed mails:
<img width="1401" alt="image" src="https://github.com/OfficeDev/office-js/assets/802015/94bd4a4b-0ef0-405c-89d1-b8e786905fe4">

**Comment by manuelsidler** [comment]
@DivyaPatidar you can reproduce the issue with ScriptLab as well:
<img width="693" alt="image" src="https://github.com/OfficeDev/office-js/assets/802015/cd20c2fe-8582-4fb4-8f91-36252d053d33">
<img width="398" alt="image" src="https://github.com/OfficeDev/office-js/assets/802015/6866a69b-c9ca-4c14-8ed1-ee50058c805c">

**Comment by DivyaPatidar** [comment]
@manuelsidler We are unable to reproduce the issue on our side even with the add-ins provide. Could you please gather and send us the diagnostic logs that include the Outlook launch and issue repro?
[Collecting log files for Outlook Add‐ins issues](https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues#outlook-mac)

**Comment by manuelsidler** [comment]
@DivyaPatidar I tried to follow the instructions for collecting log files. Unfortunately, there is no _Help -> Collect Diagnostics_ menu in Outlook on Mac:
<img width="390" alt="image" src="https://github.com/OfficeDev/office-js/assets/802015/98179472-5682-47a3-ba76-3e2b06242a98">

I submitted an error via _Help -> Feedback -> Report a Problem_:
<img width="595" alt="image" src="https://github.com/OfficeDev/office-js/assets/802015/58dc18b0-5ab0-4e94-b0b6-13fa3c149d53">

After sending the feedback, I didn't not get any incident ID. Did you receive the problem report (manuel@snapdev.onmicrosoft.com)?

**Comment by mmanjaree-msft** [comment]
@manuelsidler Can you please share the log file https://learn.microsoft.com/en-us/outlook/troubleshoot/diagnostic-logging/how-to-enable-logging-in-outlook-for-mac#log-file-locations

**Comment by manuelsidler** [comment]
@mmanjaree-msft could you provide me an e-mail address to share the log files on a secure way?

**Comment by rajjha-msft** [comment]
@manuelsidler, please create a private repo and share access with us.

**Comment by manuelsidler** [comment]
@rajjha-msft I sent you an invitation

**Comment by anjalitp** [comment]
@manuelsidler  We have reproduced the issue with digitally signed emails that contain inline attachments. Can you confirm whether this issue occurs only with emails that have an inline attachment, or if it affects all IPM.Note.SMIME.MultipartSigned emails in general? 
Additionally, sharing network logs would be immensely helpful in confirming if the issue we are seeing is the same.

**Comment by manuelsidler** [comment]
@anjalitp it affects all emails with attachments (inline or not). I can confirm that I get the itemId when the signed email doesn't have any attachments.

**Comment by akagarwa-msft** [comment]
Can you please share the network logs to understand the issue better as we are not able to repro the issue on our end.

**Comment by manuelsidler** [comment]
@akagarwa-msft could you give me more details about the network logs you need? Which application should I use to collect them? Do you need a specific format?

**Comment by akagarwa-msft** [comment]
You can share the network logs using fiddler. proxyman.Har format is preferred.
