### ISSUE TITLE
Cannot remove completely a sideloaded add-in in development in Excel for Windows

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#4333]
I'm trying to debug a sideloaded add-in (with custom functions) in Excel for Windows. I have read this thread: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#clear-the-office-cache-on-windows.

1. I first loaded the add-in in Excel for Windows via "Shared Folder"
2. I checked `Select the checkbox Next time Office starts, clear all previously-started web add-ins cache.`.
3. I closed Excel
4. I cleared the browser data in Microsoft Edge.
5. I deleted the contents in `%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\` and `%userprofile%\AppData\Local\Packages\Microsoft.Win32WebViewHost_cw5n1h2txyewy\AC\#!123\INetCache\`.

But when I reopened Excel, I saw the add-in appeared again, and contents were generated in `%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\`. And we can see custom functions when writing formulas.

Does anyone know how to remove completely a sideloaded add-in?

**Comment by chengtie** [comment]
I think I have found the trick. We need to uncheck the box under `Show in Menu`

![Screenshot 2024-04-05 at 20 28 31](https://github.com/OfficeDev/office-js/assets/774409/79a79334-bea6-4db3-a507-4de9ed3be1ae)

**Comment by Rick-Kirkham** [comment]
Try this: [Add-in commands from old development add-ins stay on ribbon even after the cache is cleared](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-development-errors#add-in-commands-from-old-development-add-ins-stay-on-ribbon-even-after-the-cache-is-cleared)

**Comment by chengtie** [comment]
> Try this: [Add-in commands from old development add-ins stay on ribbon even after the cache is cleared](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-development-errors#add-in-commands-from-old-development-add-ins-stay-on-ribbon-even-after-the-cache-is-cleared)

Thank you. The key seems to be `be sure that the manifest for the add-in is removed from the shared folder.`; just adding postfix like `.old` does not work.
