### ISSUE TITLE
Wrong item class on signed / encrypted items (Outlook, Windows)

### ISSUE THREAD

**Issue by manuelsidler** [OfficeDev/office-js#4334]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2402 (Build 17328.20184)
* Operating System: Windows 11
* Browser (if using Office on the web): -
 
## Expected behavior
For signed / encrypted items, I'd expect the item class to be "IPM.Note.SMIME.MultipartSigned" on all platforms.

## Current behavior
Outlook for Windows returns "IPM.Note" for encrypted / signed mail items. Outlook for Mac and Outlook on the web both return "IPM.Note.SMIME.MultipartSigned".

## Steps to reproduce
1. Clone the example GH repo to reproduce the issue (see link below)
2. Run the add-in with npm install and npm run dev-server
3. Side load the add-in on Outlook for Windows
4. Select a signed and/or encrypted mail
5. Open the add-in
6. The item class should be _IPM.Note.SMIME.MultipartSigned_, but it's _IPM.Note_

## Link to live example(s)
- GitHub Repo with example to reproduce: https://github.com/manuelsidler/outlook-addin-playground

## Useful logs
Reproduction video:

https://github.com/OfficeDev/office-js/assets/802015/056e912f-87b4-4b5a-8bf8-cd82d269d059

**Comment by manuelsidler** [comment]
Added detailed reproduction steps and reproduction video

**Comment by millerds** [comment]
Thanks for reporting this issue regarding the Office.context.mailbox.item.itemClass api.  It has been put on our backlog.  We unfortunately have not timelines to share at this point.

Internal tracking id: 8966741

**Comment by millerds** [comment]
Baring and new issues, this should be fixed in build 16.0.18227.20000

**Comment by victoria-msft** [comment]
Hello @manuelsidler,

The fix that was implemented for has been reverted and the task to fix this issue has been put back on our backlog. We unfortunately have not timelines to share at this point.

Internal tracking id: 8966741
