### ISSUE TITLE
Cannot remove completely a sideloaded add-in in development in Excel Online

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#4337]
I'm trying to debug a sideloaded add-in (with custom functions) in Excel Online.

- In Excel Online, after uploading the XML file, I could run the sideloaded add-in. 
- I closed the browser and opened a new incognito window.
- In the new window, I went to Excel Online with the same account, I could see that the sideloaded add-in still appears.

Does anyone know how to remove completely a sideloaded add-in in Excel Online?

**Comment by erayc-msft** [comment]
Have you tried clearing your browser's cache?  

[**Remove a sideloaded add-in**](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing#remove-a-sideloaded-add-in)
To remove an add-in sideloaded to Office on the web, simply clear your browser's cache.  If you make changes to your add-in's manifest (for example, update file names of icons or text of add-in commands), you may need to [clear your browser's cache](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache) and then re-sideload the add-in using the updated manifest.  Doing so allows Office on the web to render the add-in as it's described by the updated manifest.

**Comment by chengtie** [comment]
@erayc-msft Thank you for the reply.

I thought cache data is sandboxed in every incognito window. However, I just learned that incognito windows share session data among them as long as at least one incognito window remains open.

I tried with only one incognito window, it seems that the problem does not exist.

We can close the issue.
