### ISSUE TITLE
Cannot make a http request from custom functions (which works in Excel Online) work in Excel for Windows

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#4338]
Solved.

The manifest should be like

```
<Runtimes>
  <Runtime resid="Taskpane2.Url" lifetime="long" />
</Runtimes>
...
<ExtensionPoint xsi:type="CustomFunctions">
  <Page>
    <SourceLocation resid="Taskpane2.Url"/>
  </Page>
  ...
</ExtensionPoint>
```

I wrongly put different `resid` in `Runtime` and `SourceLocation` of `Page`.

**Comment by Rick-Kirkham** [comment]
Custom functions on the web run in a full browser runtime, but custom functions on Windows will run in a JavaScript-only runtime. See [Runtimes in Office Add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/runtimes). But you can configure the add-in to use a shared runtime on Windows, in which case the custom functions in the add-in will use a browser runtime. See [Configure your add-in to use a shared runtime](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime).
