### ISSUE TITLE
Outlook AddIn Call Graph API, AppDomains not work

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/office-js#434]
I am following [office-js-helpers](https://github.com/OfficeDev/office-js-helpers) to enable SSO login, and then use the accesstoken to call Graph API.  

But, [Authentication](https://github.com/OfficeDev/office-js-helpers#authentication-1) will open the login windows in a new tab even I have added in manifest.xml 

    <AppDomain>https://login.windows.net</AppDomain>
    <AppDomain>https://login.microsoftonline.com</AppDomain>

Current Result.   
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/JFazt.png

## Expected Behavior
The Login Window will be redirected in the Outlook Addin Taskpane.

## Current Behavior
I received an prompt to open it in a new windows.

## Steps to Reproduce, or Live Example
Here is a demo [OutlookOneDriveGraphAddIn](https://github.com/Edward-Zhou/OutlookOneDriveGraphAddIn)

@casieber  @Zlatkovsky

**Comment by niteshgolchha85** [comment]
We will be deprecating use of office-js helpers soon so for now, please use Dialog API and let me know if you still see the same issue.

**Comment by niteshgolchha85** [comment]
Closing since there hasn't been any response from the issue poster. @Edward-Zhou Feel free to reopen the issue if the issue still persists.
