### ISSUE TITLE
Hide a custom function from intellisense of users

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#4340]
The custom functions of our add-in have `SAI` as name space. When users type `=SAI.` in a cell, all of our custom functions will be displayed.

It seems that we can hide a function (let's say SAI.OLDF) from intellisense while still keeping it work. So users will not see `SAI.OLDF` in the list of intellisense, but formulas having `SAI.OLDF` still function.

Does anyone know how to enable this?

Thank you

**Comment by MiaofeiWang** [comment]
Hi @chengtie, this feature is not supported yet. Could you share more about your scenario, in which you hope to hide such a function and at the same time keep it working?

As this is a new feature request, we would like to suggest you go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform and see if your question has already been asked or ask a new question. Feature requests on it are considered when we go through our planning process.
