### ISSUE TITLE
Taskpane close event - using cross icon [x] in the taskpane

### ISSUE THREAD

**Issue by RaveendraReshma** [OfficeDev/office-js#4341]
1. We are developing office web Add in for outlook using event based (Smart Alert) .The Add in is generated using office yo generator Task Pane add-in using the React framework.
2. Is there any event for cross icon [x] of the taskpane? Because we are having a cancel button in the taskpane by which we are able to handle the data removal. But with the cross icon we are not able to do the same because we did not find any event for cross icon.

## Your Environment

- Platform : Office on the web
- Host : Outlook [OWA] & New Outlook [Desktop]
- Office version number : Version 2311 Build 16.0.17029.20140
- Operating System : Windows
- Browser : Chrome & Edge

## Link to live example(s)

<img width="235" alt="image" src="https://github.com/OfficeDev/office-js/assets/145095553/d2e44914-63e2-4a68-8b1b-b266cbcb6bf7">

- is there any event for cross icon of the taskpane?

**Comment by ajays-msft** [comment]
Thank you for the input. This is will considered as a new feature request.
We track Outlook add-in feature requests on our[Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
