### ISSUE TITLE
How to debug Outlook add-in that is extremely slow to load in Outlook Desktop but fast to load in Outlook Web

### ISSUE THREAD

**Issue by SethDG** [OfficeDev/office-js#4342]
## Post how-to questions about your code on Microsoft Q&A

How to debug Outlook add-in that is extremely slow to load in Outlook Desktop but fast to load in Outlook Web?

No changes have been made to the add-in.  The problem appears to have started around 2024-04-05 Friday.  In the Outlook Desktop, we get a spinner as the add-in is loading but I can't right click and get the context menu so that I can select Inspect until after the add-in loads.

**Comment by SethDG** [comment]
Any suggestions or advice?

**Comment by Oleg-O** [comment]
What you describe in the linked post is likely a platform issue that an add-in developer may have a hard time debugging on their own. The best course of action in this case is to open a GitHub issue like you did.

In general, taskpane add-ins can be debugged via devtools (F12), and we have some documentation on debugging other add-ins where you can't use F12 tools: [function commands](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/debug-ui-less) and [launchevents add-ins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/debug-autolaunch?tabs=windows).
