### ISSUE TITLE
Time out to exec calling Office.context.mailbox.item.notificationMessages.getAllAsync

### ISSUE THREAD

**Issue by SethDG** [OfficeDev/office-js#4343]
# Provide required information needed to triage your issue

We are seeing the error:

Time out to exec

When attempting to make calls to Office.context.mailbox.item.notificationMessages.getAllAsync

This problem only happens on Outlook Desktop and not reproducible on Outlook Web.  I've only tried on Windows, have not attempted on Mac

This code hasn't changed and only started to fail around 2024-04-05 Friday

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2403 (Build 17425.20146)
* Operating System: Windows 11
* Browser (if using Office on the web): N/A
 
## Expected behavior

The method returns in a timely fashion and does not timeout

## Current behavior

Making calls to that method take a very long time, return no results and eventually error out with "Time out to exec"

## Steps to reproduce

1. Open up ScriptLab
2. Open Work with notification messages
3. Press Add an insight notification
4. Press Get notification
5. Press Replace notification
6. Press Get notification, it never returns a value

## Link to live example(s)

Can be reproduced using the using ScriptLab and the included Work with notification messages script.

# Provide additional details

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by SethDG** [comment]
Updated bug to include repro steps using ScriptLab

**Comment by SethDG** [comment]
I'm unable to try and test this scenario in the browser due to this issue https://github.com/OfficeDev/office-js/issues/4345

**Comment by ArjunSureshKumar92** [comment]
Noticing the same issue. We believe the issue started April 3rd, 2024.

Is there an ETA on a fix, or a potential workaround?

Thanks.

**Comment by Oleg-O** [comment]
I could reproduce this, thanks for the ScriptLab steps.

Thanks for reporting this issue regarding notificationMessages.getAllAsync API. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: 8904697

**Comment by SethDG** [comment]
this appears to be resolved now and this ticket can be closed

**Comment by millerds** [comment]
Fixes have been deployed.  Patches for some builds of Office (for launch events) from earlier this year will show up next month.
