### ISSUE TITLE
ScriptLab "No snippet to run" in browser but works on Desktop

### ISSUE THREAD

**Issue by SethDG** [OfficeDev/office-js#4345]
# Provide required information needed to triage your issue

I'm trying to run a ScriptLab snippet, specifically the provided notification snippet.

In Outlook Desktop, I am able to load the snippet and execute it

But in Outlook Web (I tried Chrome, Edge and Firefox), I can't get the snippet to load in the runner.  I'm stuck on the "No snippet to run
Please open the editor to select a snippet." message

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Windows
* Browser (if using Office on the web): Chrome, Edge, Firefox, latest versions
 
## Expected behavior

After selecting the provided Notification snippet in the ScriptLab code editor, I would expect to be able to run that snippet in ScriptLab

## Current behavior

After selecting the snippet, it just says "No snippet to run  Please open the editor to select a snippet."

But only in Outlook Web.  It works as expected on Outlook Desktop

## Steps to reproduce

1. Open your browser of choice, was able to repro in Chrome, Firefox, and Edge
2. Select ScriptLab - Code and select the notification snippet
3. Select ScriptLab - Run

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by SethDG** [comment]
Blocking Web testing of https://github.com/OfficeDev/office-js/issues/4343

**Comment by rkpathak** [comment]
@SethDG This is not an office-js issue. 
However there is a workaround for this. Please refer [Script lab no snippet workaround](https://github.com/OfficeDev/script-lab/issues/1037#issuecomment-1895318468)
Closing this.
