### ISSUE TITLE
Can we get API versioning?

### ISSUE THREAD

**Issue by peter-citeright** [OfficeDev/office-js#4346]
Because the API has a single version, whenever changes are released it immediately impacts our application. Sometimes the changes go unnoticed, but other times it effects the user experience especially when there are bugs or breaking changes. 

Can we get CDN versioning so we can decide to upgrade when we want/need. It seems odd that every other API has versioning, but for a core Microsoft API we don't.

**Comment by zhenhuangMSFT** [comment]
Hi @gergzk, do you have any insights?

**Comment by gergzk** [comment]
@peter-citeright - to clarify, are you asking for versioned copies of office.js and related files on cdn (eg: appsforoffice.microsoft.com/.../versionN/office.js), or a mechanism where an individual api has a version whose behavior is held constant?

We ask that feature requests go to https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform, can you make the clarified suggestion here? I'm going to close this copy of the issue.

Feel free to add a comment with the link to the idea on techcommunity.
