### ISSUE TITLE
Eliminar publicadores

### ISSUE THREAD

**Issue by GrupoOsk** [OfficeDev/office-js#4348]
Tenemos dados de alta 3 publicadores, uno está aceptado y validado, los otros dos no, queremos eliminarlos, pero no hay forma. ¿Cómo se pueden eliminar? No vemos ninguna opción para eliminarlos.

**Comment by erayc-msft** [comment]
Hello, thank you for opening an issue.  Could you provide some more information on where you are facing this issue?  Is this within the Partner Center experience?  Thanks.

**Comment by GrupoOsk** [comment]
> Hola, gracias por abrir un problema. ¿Podría proporcionar más información sobre dónde enfrenta este problema? ¿Está esto dentro de la experiencia del Centro de socios? Gracias.

En Partners: 
    https://partner.microsoft.com/es-es/dashboard/account/v3/organization/identity 

Me muestra 3 Publicadores y deseo eliminar 2 de ellos

**Comment by samantharamon** [comment]
Hi @GrupoOsk,

For assistance with removing items from the Microsoft Partner Center, please contact Support using the following steps.
1. In Partner Center, select the question mark icon from the top right corner of the page. This opens the Help + Support pane.
1. Select **Contact Support** from the bottom of the pane.

![image](https://github.com/OfficeDev/office-js/assets/15154970/fc048298-9483-49d8-96bc-b338f7683639)

I will go ahead and close this issue in this repository, but please don't hesitate to open a new issue if you need help with the Office Add-ins platform.
