### ISSUE TITLE
Icono por defecto en versión móvil de una extensión outlook

### ISSUE THREAD

**Issue by GrupoOsk** [OfficeDev/office-js#4349]
Se muestra un icono por defecto. En las pruebas que nos enviaron, y hemos podido probar, en la versión de móvil, aparecen los botones de la extensión en la bandeja de entrada, pero no el botón en redactar, y no en todas las versiones de mobile (como indicamos en el punto anterior), pero en la web y la de escritorio, el icono de los botones se muestra correctamente, ¿porqué no se muestra en los móviles? En el manifest.xml está indicado el mismo icono, y definido para la versión móvil como indica la documentación.

**Comment by ajays-msft** [comment]
@GrupoOsk - I had to use translator to understand the text above. It is translated as:

_A default icon is displayed. In the tests that were sent to us, and we have been able to test, in the mobile version, the buttons of the extension appear in the inbox, but not the button in compose, and not in all mobile versions (as we indicated in the previous point), but in the web and desktop, the icon of the buttons is displayed correctly,  Why isn't it displayed on mobile? The same icon is indicated in the manifest.xml, and defined for the mobile version as indicated_ 

Can you please explain more what you are looking for? And please include the following along with your reply.
1) Sample manifest
2) Sample code you used
3) Recording of the repro

**Comment by GrupoOsk** [comment]
We are making an extension for Outlook, in the web version (Outlook.live.com) and in the desktop application the icon is displayed perfectly in the buttons that we show, in the Outlook version of the app, the icon that is shown is an icon by default, instead of showing our icon. The xml is as follows:


`          <MobileFormFactor>
            <FunctionFile resid="Commands.Url"/>

            <ExtensionPoint xsi:type="MobileMessageReadCommandSurface">
                <Group id="mobileMsgRead">
                  <Label resid="GroupLabel"/>
                  <Control xsi:type="MobileButton" id="msgReadOpenPaneButton">
                    <Label resid="TaskpaneButton.Label"/>
                      <Icon xsi:type="bt:MobileIconList">
                        <bt:Image size="25" scale="1" resid="Icon.16x16"/>
                        <bt:Image size="25" scale="2" resid="Icon.16x16"/>
                        <bt:Image size="25" scale="3" resid="Icon.16x16"/>
                        <bt:Image size="32" scale="1" resid="Icon.32x32"/>
                        <bt:Image size="32" scale="2" resid="Icon.32x32"/>
                        <bt:Image size="32" scale="3" resid="Icon.32x32"/>
                        <bt:Image size="48" scale="1" resid="Icon.32x32"/>
                        <bt:Image size="48" scale="2" resid="Icon.32x32"/>
                        <bt:Image size="48" scale="3" resid="Icon.32x32"/>
                      </Icon>
                    <Action xsi:type="ShowTaskpane">
                      <SourceLocation resid="Taskpane.Url"/>
                    </Action>
                  </Control>
                  <Control xsi:type="MobileButton" id="ActionButton">
                    <Label resid="ActionButton.Label"/>
                      <Icon xsi:type="bt:MobileIconList">
                        <bt:Image size="25" scale="1" resid="Icon.16x16"/>
                        <bt:Image size="25" scale="2" resid="Icon.16x16"/>
                        <bt:Image size="25" scale="3" resid="Icon.16x16"/>
                        <bt:Image size="32" scale="1" resid="Icon.32x32"/>
                        <bt:Image size="32" scale="2" resid="Icon.32x32"/>
                        <bt:Image size="32" scale="3" resid="Icon.32x32"/>
                        <bt:Image size="48" scale="1" resid="Icon.32x32"/>
                        <bt:Image size="48" scale="2" resid="Icon.32x32"/>
                        <bt:Image size="48" scale="3" resid="Icon.32x32"/>
                      </Icon>
                    <Action xsi:type="ExecuteFunction">
                      <FunctionName>validaremail</FunctionName>
                    </Action>
                  </Control>
                </Group>
            </ExtensionPoint>

            <ExtensionPoint xsi:type="MobileMessageComposeCommandSurface">
                <Group id="msgComposeGroup">
                  <Label resid="EOPegarSello.Label" />
                  <Control xsi:type="MobileButton" id="EOPegarSello">
                    <Label resid="EOPegarSello.Label" />
                    <Icon xsi:type="bt:MobileIconList">
                        <bt:Image size="25" scale="1" resid="Icon.16x16"/>
                        <bt:Image size="25" scale="2" resid="Icon.16x16"/>
                        <bt:Image size="25" scale="3" resid="Icon.16x16"/>
                        <bt:Image size="32" scale="1" resid="Icon.32x32"/>
                        <bt:Image size="32" scale="2" resid="Icon.32x32"/>
                        <bt:Image size="32" scale="3" resid="Icon.32x32"/>
                        <bt:Image size="48" scale="1" resid="Icon.80x80"/>
                        <bt:Image size="48" scale="2" resid="Icon.80x80"/>
                        <bt:Image size="48" scale="3" resid="Icon.80x80"/>
                    </Icon>
                    <Action xsi:type="ExecuteFunction">
                      <FunctionName>prependHeaderOnSend</FunctionName>
                    </Action>
                  </Control>
                </Group>
            </ExtensionPoint>


          </MobileFormFactor>`

The resids are correct, as they load correctly in the web version

**Comment by rkpathak** [comment]
I understand that the icons are shown properly in OWA and Desktop outlook.  What do you mean by "Outlook version of the app" ?
Can you share a basic version of addin code where it can be reproduced. You can host it in a github repo and share. This will help us repro the problem on our end.

**Comment by GrupoOsk** [comment]
We have published an outline of the code, but removing all reference to the final code, we would be interested in knowing why the compose area button is not shown on Android or IOS. In addition to why the option button icons displayed in the mail area are not displayed correctly, showing a default icon. On the Web (outlook.onlive.com) they are displayed correctly.

https://github.com/GrupoOsk/https---www.Midominio.com-extension_esquema

**Comment by ajays-msft** [comment]
@GrupoOsk - I am wondering if the problem is in Android/iOS or Outlook.com or Desktop Outlook. Can you please share a video recording of the repro?

**Comment by GrupoOsk** [comment]
The problem is on Android, the button is not shown in the Android compose, and the ones that are shown on the screen of reading a received email, the icons  ini the buttons are a default icon. On IOS the same

**Comment by ajays-msft** [comment]
@GrupoOsk - ExtensionPoint xsi:type="MobileMessageComposeCommandSurface">
is not a supported extension point on Mobile. Only "LaunchEvent" extension point is supported on compose surface. Same issue will occur on iOS as well
