### ISSUE TITLE
Office.context.auth.getAccessTokenAsync throw Cannot read property 'Version' of null

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/office-js#435]
I am use `Office.context.auth.getAccessTokenAsync` to request accesstoken, but it throw error below:   

> Uncaught TypeError: Cannot read property 'Version' of null
    at Object.callback (outlook-web-16.01.js:16)
    at rt (outlook-web-16.01.js:16)

## Expected Behavior
Get the access token correctly.

## Steps to Reproduce, or Live Example
Demo:  

[OutlookOneDriveGraphAddIn](https://github.com/Edward-Zhou/OutlookOneDriveGraphAddIn)

**Comment by robballou** [comment]
I also get this error when using `Office.context.ui.messageParent` from a dialog iframe.

**Comment by dmahugh** [comment]
@exextoc - see the Outlook repro in [OutlookOneDriveGraphAddIn](https://github.com/Edward-Zhou/OutlookOneDriveGraphAddIn). Can you advise?

**Comment by exextoc** [comment]
@Edward-Zhou Can you please post a snippet of relevant code to reproduce the issue ?

**Comment by Edward-Zhou** [comment]
@exextoc  I have shared a reproducable project, what is your expected snippet? Maybe you could share us a working demo with `Office.context.auth.getAccessTokenAsync`.   

Or, is this your expected?  
```
function initializePane() {
        var username = Office.context.mailbox.userProfile.displayName;
        $("#username").text(username);
        saveAttachmentsWithPrompt(123);
        // First attempt to get an SSO token
        if (Office.context.auth !== undefined && Office.context.auth.getAccessTokenAsync !== undefined) {
            Office.context.auth.getAccessTokenAsync(function (result) {
                if (result.status === "succeeded") {
                    // No need to prompt user, use this token to call Web API
                    saveAttachmentsWithSSO(result.value, 1);
                } else if (result.error.code == 13007 || result.error.code == 13005) {
                    // These error codes indicate that we need to prompt for consent
                    Office.context.auth.getAccessTokenAsync({ forceConsent: true }, function (result) {
                        if (result.status === "succeeded") {
                            saveAttachmentsWithSSO(result.value, 1);
                        } else {
                            // Could not get SSO token, proceed with authentication prompt
                            saveAttachmentsWithPrompt(1);
                        }
                    });
                } else {
                    // Could not get SSO token, proceed with authentication prompt
                    saveAttachmentsWithPrompt(123);
                }
            });
        }
        else {
            // SSO not supported
            saveAttachmentsWithPrompt(1);
        }
    }
```

**Comment by exextoc** [comment]
We are unable to repro this issue. Snippet shared by you is correct. Issue could be with manifest.
Can you try overriding everything inside `<VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">`

Similar issue- https://stackoverflow.com/questions/48641465/uncaught-typeerror-cannot-read-property-version-of-null-in-outlook-web-16-01

**Comment by Edward-Zhou** [comment]
I already checked this link.  
Could you share us your working demo?

**Comment by exextoc** [comment]
Here is a working sample 

https://github.com/OfficeDev/outlook-add-in-attachments-demo
