### ISSUE TITLE
MS Word : Base64 string issue with image

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4352]
Please refer attached sample zip for add-in code.
[Uploading Addin.zip…]()

And import manifest.xml file from this zip. This will add command as 
![image](https://github.com/OfficeDev/office-js/assets/157671419/107ea65e-02c7-4bd3-a2e3-ef669abe543b)

Click on command and upload document 
[Document13.docx](https://github.com/OfficeDev/office-js/files/14934455/Document13.docx)

Now click on Save Document from TaskPane. This will download docx file. Generated document is corrupted. Can you please tell me what is missing in my save document operation?

Thanks in advance.

**Comment by samantharamon** [comment]
Hi @ishanig11. Thanks for reporting this.

@wangyun-microsoft, could you please investigate this?

**Comment by Searion** [comment]
@ishanig11 Thanks for reporting. I noticed that the Zip is not uploaded correctly. Could you please provide upload it again?
