### ISSUE TITLE
Validating an Outlook extension: Compose mode

### ISSUE THREAD

**Issue by GrupoOsk** [OfficeDev/office-js#4356]
I've been answered this from Microsoft, it's a button that has to appear in the compose an email to execute a function of its own, which is to paste a text in the body of the email when sending. They tell me the following:

**The add-in declares support for Outlook on Android but isn't working in the Outlook app on an Android phone. 
Issue: Add-in is not visible in Mobile compose mode. 
Note: Add-in is working fine in Mobile Read mode.
Kindly refer the attachment.
Verify Android Phone support and resubmit your offer.**

What do I need to change? In the <MobileFormFactor> tengo lo siguiente:
` <ExtensionPoint xsi:type="MobileMessageComposeCommandSurface">
                <Group id="msgComposeGroup">
                  <Label resid="EOPegarSello.Label" />
                  <Control xsi:type="MobileButton" id="EOPegarSello">
                    <Label resid="EOPegarSello.Label" />
                    <Icon xsi:type="bt:MobileIconList">
                        <bt:Image size="25" scale="1" resid="Icon.16x16"/>
                        <bt:Image size="25" scale="2" resid="Icon.16x16"/>
                        <bt:Image size="25" scale="3" resid="Icon.16x16"/>
                        <bt:Image size="32" scale="1" resid="Icon.32x32"/>
                        <bt:Image size="32" scale="2" resid="Icon.32x32"/>
                        <bt:Image size="32" scale="3" resid="Icon.32x32"/>
                        <bt:Image size="48" scale="1" resid="Icon.80x80"/>
                        <bt:Image size="48" scale="2" resid="Icon.80x80"/>
                        <bt:Image size="48" scale="3" resid="Icon.80x80"/>
                    </Icon>
                    <Action xsi:type="ExecuteFunction">
                      <FunctionName>prependHeaderOnSend</FunctionName>
                    </Action>
                  </Control>
                </Group>
            </ExtensionPoint>`

**Comment by ajays-msft** [comment]
@GrupoOsk 
ExtensionPoint xsi:type="MobileMessageComposeCommandSurface">
is not a supported extension point on Mobile. Only "LaunchEvent" extension point is supported on compose surface. Same issue will occur on iOS as well
