### ISSUE TITLE
Exceljs Custom Functions Dialog Doesn't Reload

### ISSUE THREAD

**Issue by sccrgoalie1** [OfficeDev/office-js#4358]
When using Exceljs custom functions.  The initial function dialog works fine and all parameters are shown.  If you click on a cell with an already existing formula the dialog does not show properly.  The addin is associated with a COM addin so I'm not sure if that plays into this issue.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2403 16.0.17425.20124
* Operating System: Windows 11
* Browser (if using Office on the web): Edge
 
## Expected behavior
The function parameters should reload properly

## Current behavior
Insert a custom function.  The dialog shows properly.

![image](https://github.com/OfficeDev/office-js/assets/2366790/f88878c6-2375-4b2c-a134-dc104b29e05e)

Click the function button from that same cell.

![image](https://github.com/OfficeDev/office-js/assets/2366790/fee97b88-0057-42e9-8292-c93267e3dba8)

The dialog then shows up blank

![image](https://github.com/OfficeDev/office-js/assets/2366790/05acf368-eadd-41eb-a820-8f1137a8f694)

## Link to live example(s)
Civic Connect Addin in the Office Store

## Context
This should reload the same parameters as the original dialog

**Comment by shanshanzheng-dev** [comment]
@m-hellesen Could you please take a look this issue? Thanks.

**Comment by penglongzhaochina** [comment]
hi @sccrgoalie1 
Are you specified equivalent in your manifest?

Thanks!

**Comment by sccrgoalie1** [comment]
@penglongzhaochina yes we have

**Comment by penglongzhaochina** [comment]
hi @sccrgoalie1 ，

Deleting the equivalent in the manifest can mitigate this issue temporarily. We are fixing this issue now. Will let you know once we have any progress.

**Comment by sccrgoalie1** [comment]
@penglongzhaochina OK, that's not an option for us, we will await the fix.

**Comment by RuizhiSunMS** [comment]
Hi @sccrgoalie1, we are working on issues with long-history and found this one. May I know that your case has been resolved or not? I tracked that our fix should have been released for some time.

**Comment by sccrgoalie1** [comment]
@RuizhiSunMS I’ll check it out when I’m back to the office Tuesday.

**Comment by sccrgoalie1** [comment]
Confirmed fixed.  Thanks!
