### ISSUE TITLE
[Word Online] Can't type text after contenControl 

### ISSUE THREAD

**Issue by rimadu** [OfficeDev/office-js#436]
After inserting a content control on an empty line, the user cannot type any text into the document until they press right arrow and enter. Content control takes full width of the document.

![full width content control](https://i.imgur.com/QpEMyvK.png)

## Expected Behavior
Be able to type text after inserted text (outside of content control)

## Steps to Reproduce, or Live Example
- Open an empty document or click enter and go to a new line
- Use script below to insert text
- Click the right arrow in the keyboard to go out of content control
- Try to type text, nothing happens, the text is not inserted

Steps can be reproduced on web office 365 on Chrome, Safari and Firefox.

```
Word.run(async (context) => {
    const selection = context.document.getSelection();
    const control = selection.insertContentControl();

    control.insertHtml('<b>Hello</b>', Word.InsertLocation.replace);
    control.select(Word.SelectionMode.end);

    return context.sync();
  });
```

**Comment by JuaneloJuanelo** [comment]
@rimadu  thanks for reporting this issue, i was able to repro it.  i created a [Script Lab Snippet](https://gist.github.com/JuaneloJuanelo/5310508e101f950cf4f044e8f5cf1837)

We are tracking internally with 3237296

**Comment by XiangGaoMSFT** [comment]
@rimadu thanks for reporting this issue. This issue has been fixed and you can test it now.
I'll close this issue. Please feel free to reopen it if you still have this issue.
