### ISSUE TITLE
On send event in outlook gives pop up/alert after 5 seconds . Is this time configurable ?

### ISSUE THREAD

**Issue by pza-dev-brcm** [OfficeDev/office-js#4362]
I have created add-in where handling on-send event with "OnMessageSend"
referring below help page.
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/onmessagesend-onappointmentsend-events?tabs=windows.

Issue:
If add-in processing takes time more than 5 seconds then pop-up message is displayed.
As per documentation: If the add-in runs for more than five seconds, but less than five minutes, the user is alerted that the add-in is taking longer than expected to process the message or appointment.

Can we modify this 5 second default value to say 15/20 seconds? What are the steps to do that?

In my case, add0in processing takes around 10 seconds. I dont want user to get that pop-up/alert until processing completes.

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by ajays-msft** [comment]
Thank you for the input. This is will considered as a new feature request.
We track Outlook add-in feature requests on our[Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
