### ISSUE TITLE
Help with changing the colour of the underlining of text

### ISSUE THREAD

**Issue by laitang2000** [OfficeDev/office-js#4364]
Hi, is there a way to change the colour of the underline so that it is different to the colour of the range using office.js?
It appears it is possible to do so in Word, but I cant find it in the sdk. Thanks

![image](https://github.com/OfficeDev/office-js/assets/10725544/c56057b3-2975-4e2c-b6ec-53a0fae684f4)

**Comment by samantharamon** [comment]
Hi @laitang2000,

Thanks for reaching out. Currently, you can only change the type of underline using the Office JS API, but not its color (see [Word.Interfaces.FontUpdateData](https://learn.microsoft.com/javascript/api/word/word.interfaces.fontupdatedata#word-word-interfaces-fontupdatedata-color-member)). If you'd like to have this functionality when implementing Word add-ins, please submit a feature request on the [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions).
