### ISSUE TITLE
Integrated spam-reporting add-in doing nothing in new Outlook

### ISSUE THREAD

**Issue by navmro** [OfficeDev/office-js#4366]
# Provide required information needed to triage your issue

Now that the feature for "integrated spam-reporting add-in" is also in preview for the new Outlook we're trying to have it work there. The plugin appears, but the button does nothing and no logs is generated.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: New Outlook
* Office version number: 1.2024.403.300 (Production). Client Version is 20240405002.12 .
* Operating System: Windows 10 22H2 19045.4291
* Browser: Chrome 123.0.6312.122
 
## Expected behavior

The email is moved to the junk folder.

The plugin is made using the exact "default" js code from the documentation:
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/spam-reporting

## Current behavior

When an email is selected, the button appears clickable, but nothing happens on click.

![image](https://github.com/OfficeDev/office-js/assets/142206658/4eb253c0-3051-4927-84a2-f841a8ee7a5a)

## Steps to reproduce
1. Create a new Outlook plugin with "yo office"
2. Follow the documentation from : https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/spam-reporting
3. `npm start`

I've made a small plugin to reproduce the issue which only contains the code from the documentation.
https://github.com/navmro/antiphishing

# Provide additional details

1. I've enabled "EnableBetaAPIsInJavaScript" to 1 in HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\16.0\Outlook\Options\WebExt\Developer
2. I've tried with the user or with the whole tenant in "targeted release" in the M365 console.
3. I've restarted my computer many time to make sure its not a problem on my end.

## Context

We're trying to replace our existing VSTO spam-reporting addin with a new one that would work in the new Outlook.

The new JS plugin works on the old outlook desktop app, but not in the new Outlook desktop app.

## Useful logs

The documentation mentions that errors go in the event viewer:
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/troubleshoot-event-based-and-spam-reporting-add-ins

It's unclear to me if this applies to both old outlook and new outlook, but nothing appears in the event viewer. When the new Outlook load or when the plugin's button is pressed.

I've also tried using the plugin on Outlook for the Web, even though it's not my targeted environment to see if in the browser's console there is an error. But no error linked to the plugin appears in the console, and the button does nothing when clicked (no animation even).

Here is the output of the errors in the console, in case I've missed something and they are linked:
![outlook_on_web_logs](https://github.com/OfficeDev/office-js/assets/142206658/f98da358-0f51-4476-8d42-5c715fa964c8)

I would gladly provide any additional information needed for triage or debugging.

**Comment by samantharamon** [comment]
Thank you for reporting this, @navmro. The team is currently investigating this issue. Are you able to run the sample in classic Outlook on Windows by any chance?

**Comment by navmro** [comment]
Yes, running the same code (https://github.com/navmro/antiphishing) on classic desktop Outlook works. I get the pop-up, and then the email is moved to the junk folder.
Or do you mean another sample ?

**Comment by ajays-msft** [comment]
@navmro The issue has been fixed, and will be available in prod by end of next week. Please check after 4/26 and re-open if this issue still persists.
