### ISSUE TITLE
'allow-top-navigation' or 'allow-top-navigation-by-user-activation' 

### ISSUE THREAD

**Issue by MarieLePanda** [OfficeDev/office-js#437]
No possible to call Graph API in OWA

## Expected Behavior
When I run an add-in, in Outlook Desktop who will use Graph API my taskpane display the login page to ask the constent of user. My expected behavior is to have the same thing in OWA with lastest navigator

## Current Behavior
Currently on OWA, if I try to connect my user to graph API, the following error is display on the console

Unsafe JavaScript attempt to initiate navigation for frame with origin 'https://outlook.office.com' from frame with URL 'https://login.microsoftonline.com/tenant.onmicrosoft.com/oauth2/authorize?response_type=id_token&client_id=clientId&redirect_uri=https%3A%2F%2Flocalhost%3A44379%2FMessageRead.html%3Fet%3D&state=5b874348-7558-4453-a436-d6e40a06f245&client-request-id=5671829d-bd42-43c7-bd12-ba7ef7df3879&x-client-SKU=Js&x-client-Ver=1.0.10&nonce=5106fd67-ccaf-4b68-a928-851609152821'. The frame attempting navigation of the top-level window is sandboxed, but the flag of 'allow-top-navigation' or 'allow-top-navigation-by-user-activation' is not set.

## Steps to Reproduce, or Live Example
Donwload the Outlook Add-in sample here https://github.com/OfficeDev/PnP-OfficeAddins/blob/master/Samples/Outlook.ConsumeGraphAPI/Outlook.AddInSample/Outlook.AddInSampleManifest/Outlook.AddInSample.xml and run it on OWa with the last version on Chrome

## Your Environment

* Platform : Office Online
* Host : OWA
* Office version number: N/A
* Operating System: N/A
* Browser (if using Office Online):Chrome Version 72.0.3626.121

## Useful logs
Unsafe JavaScript attempt to initiate navigation for frame with origin 'https://outlook.office.com' from frame with URL 'https://login.microsoftonline.com/tenant.onmicrosoft.com/oauth2/authorize?response_type=id_token&client_id=clientId&redirect_uri=https%3A%2F%2Flocalhost%3A44379%2FMessageRead.html%3Fet%3D&state=5b874348-7558-4453-a436-d6e40a06f245&client-request-id=5671829d-bd42-43c7-bd12-ba7ef7df3879&x-client-SKU=Js&x-client-Ver=1.0.10&nonce=5106fd67-ccaf-4b68-a928-851609152821'

**Comment by exextoc** [comment]
Which platform are you using: old-OWA or new-OWA (option which appears on right hand corner: Try the new outlook)?

**Comment by MarieLePanda** [comment]
Hello, same issue on the both, but after discussion with Graph Expert, it point me this documentation to maybe solve the issue https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#use-the-dialog-apis-in-an-authentication-flow
But if I'm correct, the issue must probably fix in adal.js in the method login https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Login-methods
This method look like call the login window, and so probably not correctly for OWA.

**Comment by exextoc** [comment]
Yes,For authentication flows, we recommend using the [Office.js Dialog API](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#use-the-dialog-apis-in-an-authentication-flow). The section of the documentation I linked to describes how to use the API to implement an authentication flow to call Graph Apis in OWA.

**Comment by MarieLePanda** [comment]
And so Adal.js ? useless ?

**Comment by exextoc** [comment]
Hey @MarieLePanda, the Adal.js authentication in the example they have sited would work for an independent page, but since the add-in is a sandboxed environment, Certain behaviours are restricted such as opening a popout, without using dialog APIs. You would have to use the Dialog API for authentication in your case.
