### ISSUE TITLE
internetHeaders.removeAsync not working when called from ItemSend email event in old outlook desktop

### ISSUE THREAD

**Issue by rtbEgress** [OfficeDev/office-js#4371]
# Provide required information needed to triage your issue

When calling the internetHeaders.removeAsync method during an ItemSend event, the header is not removed when using the old outlook client, and the header is still present on the sent email.

This is not the case for outlook on web.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2402 Build 16.0.17328.20282) 64-bit 
* Operating System: Windows 11
* Browser (if using Office on the web): ______
 
## Expected behavior

The headers should be removed from the email if the internetHeaders.removeAsync method is called.

## Current behavior

When calling the internetHeaders.removeAsync method during an ItemSend event, the header is not removed when using the old outlook client, and the header is still present on the sent email.

This is not the case for outlook on web.

## Steps to reproduce

1. Create an outlook web app with an ItemSend event
2. Get the mailbox item during the send event
3. Add a custom header with an arbitrary value
4. Remove the header you just added
5. Allow the message to send
6. Create a new email using the old outlook client with this addin enabled and send it.
7. Check the headers on the sent email, the header will not have been removed

## Context

Some of the headers are added as the email is composed by our addin. In some scenarios, checks happening when the user attempts to send require us to remove some of these headers. We are unable to provide a consistent experience for users across different clients, and cannot remove these headers which we need to.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by timwan10** [comment]
Does this happen for Mac as well? 

The internal implementation for this differs on OWA/New Outlook and Old Outlook. The Dev team needs to investigate further on this and it has been put on the backlog to investigate. 

Win32 Internal Ref #: 8915051

**Comment by ztcdsb** [comment]
@rtbEgress We are having trouble to repro this issue, Can you kindly offer some code snippet to help us investigate it.

**Comment by ztcdsb** [comment]
This issue is fixed and will be available in version 16.0.17722.10000
