### ISSUE TITLE
New group/ungroup `DataChangeType` for worksheet change events

### ISSUE THREAD

**Issue by spderosso** [OfficeDev/office-js#4372]
The supported worksheet change events are listed [here](https://learn.microsoft.com/en-us/javascript/api/excel/excel.datachangetype?view=excel-js-preview). I'd like to propose the addition of the following events: group/ungroup rows/columns.

Or is there another way of knowing when a user groups/ungroups rows or columns?

Thanks!

**Comment by dingjin-ms** [comment]
Hi @spderosso , thank you for raising the problem. 

We apologize for the inconvenience, but we do not support the scenario you mentioned at the moment. If you would like to request this feature, please post it on our [developer forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform), where our product managers will regularly review and prioritize the suggestions.
