### ISSUE TITLE
displayDialogAsync - host page receives error:12006 as soon as popup navigates to subdomain

### ISSUE THREAD

**Issue by cattermo** [OfficeDev/office-js#4376]
When using `displayDialogAsync` in office on the web, the host page receives `error:12006` as soon as the popup navigates to a different domain.

## Your Environment
* Platform: Office on the web
* Host: Excel, Word, PowerPoint
* Operating System: Tested both MacOS and Windows
* Browser: Tested Edge, Chrome, Firefox, Safari

## Expected behavior
Following this guide https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins it should be possible to open a popup window, from the host page by using `displayDialogAsync`, with the same domain, navigate to a different subdomain or domain, and then after coming back to the same domain, send a message to the host page.

## Current behavior
As soon as the popup window leaves the same domain and navigates to a different domain my host page gets a dialog event with `{error: 12006}` as if the user closed the popup window. After this happens there is no more communication from the popup window to the host page.

## Steps to reproduce
I have created a minimal Add-in that reproduces the problem here https://github.com/cattermo/officejs-reproduce-dialog-problem

## Link to live example(s)
If one does not bother to run anything locally, one can install the test version of our real app where I have added some things to really showcase the problem. Use this manifest: https://testbed-office-addin.scrive.com/public/manifest-testbed.xml
No account is needed since the bug happens before the user gets a chance to login.

## Context
I think this is a very common use case, to open a popup to do authentication flow (since most login pages does not allow iframing). I have no idea how to achieve this in a good way if the popup cannot tell the host page when authentication is done.

**Comment by shanshanzheng-dev** [comment]
@m-hellesen Could you help take a look this issue? Thanks.

**Comment by m-hellesen** [comment]
Thanks so much for the detailed information and for giving us a sample add in. Questions for you while I look into it, has this worked for you in the past? Have you taken a look at this portion of the docs about cross domain messaging? https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#cross-domain-messaging-to-the-dialog-runtime

**Comment by cattermo** [comment]
> Thanks so much for the detailed information and for giving us a sample add in. Questions for you while I look into it, has this worked for you in the past? Have you taken a look at this portion of the docs about cross domain messaging? https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#cross-domain-messaging-to-the-dialog-runtime

Hi!
Thank you for looking into this. I did a small rebuild of our Add-In in December last year, moving from iframe popup to popup window. Then this workflow was working (open popup window with own domain -> redirect to other domain -> redirect back to same domain -> pass message to host page). I had to turn off some security headers to make it work (crossOriginOpenerPolicy and crossOriginResourcePolicy) but then it worked. 

I'm not trying to message cross domain, I want to send the message after going back to same the same domain as the host page.

**Comment by jim22k** [comment]
@cattermo I have run into similar issues with Office Online. After redirecting and coming back to the same origin, it can't communicate with the add-in. I suspect it's due to losing the original `window.opener` reference -- not sure.

I found a solution which  involves never redirecting the dialog window. Instead, you pop open a second window and do the redirect flow there. You communicate with the original dialog window via BroadcastChannel.

https://github.com/jim22k/OfficeOnlineDialog/tree/main

**Comment by cattermo** [comment]
> @cattermo I have run into similar issues with Office Online. After redirecting and coming back to the same origin, it can't communicate with the add-in. I suspect it's due to losing the original `window.opener` reference -- not sure.
> 
> I found a solution which involves never redirecting the dialog window. Instead, you pop open a second window and do the redirect flow there. You communicate with the original dialog window via BroadcastChannel.
> 
> https://github.com/jim22k/OfficeOnlineDialog/tree/main

This sounds like a good workaround if the office-js team does not manage to solve the problem. Since it's possible to do this with a new popup window, office-js should be able to do it with its popup window...

@m-hellesen Are you still looking into the issue? Any progress?

**Comment by cattermo** [comment]
Please? Can someone have a look at this?

**Comment by m-hellesen** [comment]
Hey, I do have someone looking into this. Did the workaround unblock you for now?

**Comment by cattermo** [comment]
> Hey, I do have someone looking into this. Did the workaround unblock you for now?

Ok, great, thank you 🙇 . 
Since it used to work late last year I would rather not build a different solution that then have to be removed when the real one starts working again 😬

**Comment by yjz2021** [comment]
Hey @cattermo, I have been looking into the issue and it seems that the domain policy needs to be changed. Could you please verify if it works when the Cross-Origin-Opener-Policy header is not set to 'same-origin'. Let me know if this solves the issue. Thanks.

**Comment by cattermo** [comment]
> Hey @cattermo, I have been looking into the issue and it seems that the domain policy needs to be changed. Could you please verify if it works when the Cross-Origin-Opener-Policy header is not set to 'same-origin'. Let me know if this solves the issue. Thanks.

Sorry for late response, was bank holiday in Sweden.
Sadly setting `"Cross-Origin-Opener-Policy": "unsafe-none"` does not make any difference.

**Comment by cattermo** [comment]
Any progress on this?

**Comment by yjz2021** [comment]
Hi @cattermo, apologies for the delay. We've investigated and found that the manifest you provided no longer reproduces the host page receiving error:12006 issue. Could you please confirm if the issue is resolved for you? Thank you.

**Comment by cattermo** [comment]
> Hi @cattermo, apologies for the delay. We've investigated and found that the manifest you provided no longer reproduces the host page receiving error:12006 issue. Could you please confirm if the issue is resolved for you? Thank you.

The debugging code is now back for the manifest provided. The error is still the same. 
Feel free to also use the reproduction repository that I have created for you 🙏 
https://github.com/cattermo/officejs-reproduce-dialog-problem

**Comment by yjz2021** [comment]
Hi @cattermo, in your repository's index.js file at line 19, it attempts to redirect to 'https://google.com'. This action also sets the Cross-Origin-Opener-Policy, causing it to fail. When there are multiple redirections, it's essential to remove the Cross-Origin-Opener-Policy header from all responses or set them all to 'unsafe-none'. 
Could you please try replacing the URL with 'https://example.com' (which does not have such header), and let me know if it resolves the issue for you? Thanks.

**Comment by cattermo** [comment]
> Hi @cattermo, in your repository's index.js file at line 19, it attempts to redirect to 'https://google.com'. This action also sets the Cross-Origin-Opener-Policy, causing it to fail. When there are multiple redirections, it's essential to remove the Cross-Origin-Opener-Policy header from all responses or set them all to 'unsafe-none'. Could you please try replacing the URL with 'https://example.com' (which does not have such header), and let me know if it resolves the issue for you? Thanks.

Oh, that's the key to it!! The receiving link also needs to have a less strict value for that header. This is what happened in our "real" app as well. One of the disadvantages of using `helmetjs` as a standard. 

Thank you very much for finding it! 🙏
