### ISSUE TITLE
Getting change notification for drafted New Event

### ISSUE THREAD

**Issue by som-cloudextend** [OfficeDev/office-js#4381]
# We are getting change notification for default New Event event created by Outlook.

## Your Environment

* Platform: PC desktop, Mac
* Host: Outlook
* Office version number: Outlook desktop for mac 16.83.3
* Operating System: Windows 11, MacOS
* Browser (if using Office on the web): N/A
 
## Expected behavior

We shouldn't receive change notification for the initial event created by Outlook.

## Current behavior

We are getting a change notification every time someone trying to create an event. Outlook initially shows default values in the event create window. Title for initial event is New Event. User doesn't add any details to this event. Still Graph sends a change notification for it.

## Steps to reproduce

1. Create a subscription to events using Graph API
2. Create new event in outlook desktop but don't enter anything
3. We get a change notification for above event titled New Event

## Context

We don't expect a change notification for the default event created by Outlook as there's no user changes. We also can't skip processing this event in the listener because there could be legitimate event titled New Event created by user. This behaviour is seen only in desktop applications. In OWA we don't get any such change notification. Attached the event create screenshot and the event details.

## Useful logs

- [ ] Console errors
- [x] Screenshots
![Screenshot 2024-04-19 at 9 53 35 AM](https://github.com/OfficeDev/office-js/assets/155970058/0fadf691-0a0b-4bfa-ad77-dafca01dc465)
- [x] Test file (if only happens on a particular file)
[New Event.json](https://github.com/OfficeDev/office-js/files/15033146/New.Event.json)

**Comment by ajays-msft** [comment]
This forum is limited to supporting office-js apis. For any MS API Graph specific queries and support, please explore options available at [Microsoft Graph Dev Center | APIs and app development](https://developer.microsoft.com/en-us/graph)

**Comment by som-cloudextend** [comment]
Thanks, will raise this in other forum.
