### ISSUE TITLE
Unable to view permissions while deploying an add-in

### ISSUE THREAD

**Issue by varunrathi1910** [OfficeDev/office-js#4382]
Unable to view permissions while deploying an add-in. The issue is persistent across custom add-ins and add-ins from the store. Please refer to the below screenshot :  

![image](https://github.com/OfficeDev/office-js/assets/25360482/241c6b5f-b7cb-4947-a2a7-e36740859e7d)

Upon further debugging, we found that the below endpoint returns name and description as null for the scopes. Please refer the attached screenshot 

![image](https://github.com/OfficeDev/office-js/assets/25360482/54628b06-ced5-4bf8-b6b0-4df08b396bee)

**Comment by samantharamon** [comment]
Hi @varunrathi1910,

Thank you for reporting this issue. I'm following up on this internally for investigation.

**Comment by Nurou** [comment]
Hi @samantharamon, JFYI we're also experiencing this issue

**Comment by samantharamon** [comment]
Thanks for also reporting this, @Nurou. We're still following up on this with the team who supports this.

**Comment by samantharamon** [comment]
@AkhileshShah-MS, could you please investigate this issue further? Thanks!

**Comment by AkhileshShah-MS** [comment]
@Nurou @varunrathi1910 @samantharamon The issue has been resolved by team. Please try this again and let me know if any issues. Thanks!

**Comment by AkhileshShah-MS** [comment]
Closing this as the issue has been resolved, and no further comments from customer.
