### ISSUE TITLE
[WordJS] field.code set throws after field.result.insertHtml()

### ISSUE THREAD

**Issue by adomasven** [OfficeDev/office-js#4388]
Word Online

Trying to set field code after inserting html for the field result range throws an error.

```js
await Word.run(async (context) => {
	const selection = context.document.getSelection().getRange();
	const field = selection.insertField('Start', 'Addin');
	field.code = `ADDIN test`;
	// field.result.insertText("Test1", "Start");
	field.result.insertHtml("<b>Test1</b>", "Start");
	await context.sync();
	field.code = `ADDIN test1after`
	// Throws a GeneralException
	await context.sync();
});
```

If in the above code you call `field.result.insertText()` instead of `field.result.insertHtml()` no error is thrown.

**Comment by YijunMS** [comment]
Hi @adomasven , thanks for reaching us, I am investigating this issue and trying to find the solution. As a workaround, you may reacquire the field object instead of working on the same one to unblock yourself.

**Comment by adomasven** [comment]
How would I reacquire the fields? This error also occurs if you acquire existing fields from `context.document.body.fields`, or any other collection.

**Comment by YijunMS** [comment]
@adomasven I mean acquiring a new Field object after inserting Html instead of using the origin one, however, this may be hard if you have multiple fields in the document. I am working on the fix, and I will update once it starts to deploy.

**Comment by YijunMS** [comment]
@adomasven The fix is under deployment now. I will update once it is ready for test.

**Comment by YijunMS** [comment]
@adomasven The issue should be fixed. Please let me know if it still exists.

**Comment by adomasven** [comment]
Blocked by https://github.com/OfficeDev/office-js/issues/4854

**Comment by adomasven** [comment]
The test case above seems to pass.
