### ISSUE TITLE
How to unblock XML files in outlook?

### ISSUE THREAD

**Issue by nebojsaaa** [OfficeDev/office-js#4389]
<img width="168" alt="image" src="https://github.com/OfficeDev/office-js/assets/10420335/584fc618-6e5a-4463-9c1a-8d960feccd46">

**Comment by davidchesnut** [comment]
Hi @nebojsaaa, can you please provide some more context around this error? What steps lead up to this error appearing? Thanks!

**Comment by nebojsaaa** [comment]
Hi @davidchesnut , thanks for the reply. Basically, when i get XML files as attachment in inbox I cannot download them or preview the file. This is for version - **You have Microsoft Outlook Version 1.2024.417.100 (Production). Client Version is 20240412005.13 .**
In older version - **Microsoft® Outlook® for Microsoft 365 MSO (Version 2403 Build 16.0.17425.20176) 64-bit** works just fine

**Comment by davidchesnut** [comment]
Thanks @nebojsaaa, @exextoc can you please help with this issue? Thanks!

**Comment by davidchesnut** [comment]
Hi @nebojsaaa, we're unable to reproduce this error. If you can provide steps on how to reproduce this error we can look into it more. Thanks!
