### ISSUE TITLE
Formula Bar doesn't Update Automatically after changes In Excel Add-in

### ISSUE THREAD

**Issue by GuoGuitang** [OfficeDev/office-js#439]
Here I'm in an Excel Add-in, in a .xlsx file
In Range C3: C6 there are formulas that in the same type VLOOKUP

![image](https://user-images.githubusercontent.com/36781921/54730414-cbb73c00-4bc3-11e9-948c-7a8b307659d9.png)

And In `index.js` my code is
```
let data=[
  ["=INDEX(R2C11:R9C11,MATCH(R[0]C2,R2C10:R9C10,0))"],
  ["=INDEX(R2C11:R9C11,MATCH(R[0]C2,R2C10:R9C10,0))"],
  ["=INDEX(R2C11:R9C11,MATCH(R[0]C2,R2C10:R9C10,0))"],
  ["=INDEX(R2C11:R9C11,MATCH(R[0]C2,R2C10:R9C10,0))"],
]
range.formulasR1C1 = data;      // Here range is C3: C6
range.select();
return ctx.sync();
``` 
And before the code running above, the range C3: C6 is **selected** , looks like the first Pic shows.
So I expect after the code running, the formula in **Formula Bar could update itself
Automatically**
## Expected Behavior

![image](https://user-images.githubusercontent.com/36781921/54730464-189b1280-4bc4-11e9-9a26-9fea3317def5.png)

## Current Behavior

**But now,  Formula Bar doesn't Update Automatically after the formulas had been changed.**

![image](https://user-images.githubusercontent.com/36781921/54730414-cbb73c00-4bc3-11e9-948c-7a8b307659d9.png)

Only if I select another cell or range, and then, re-select the Range C3: C6, the formulas in Formula Bar shows the Right Formula.

So Can Anyone tell me what should I do?

**Comment by lumine2008** [comment]
@GuoGuitang , could you have a try to add context.sync(); before range.select()? please let me know if this is updated or not. thanks

**Comment by GuoGuitang** [comment]
@lumine2008 
> @GuoGuitang , could you have a try to add context.sync(); before range.select()? please let me know if this is updated or not. thanks

I have tried it, just like
```
let data=[
  ["=INDEX(R2C11:R9C11,MATCH(R[0]C2,R2C10:R9C10,0))"],
  ["=INDEX(R2C11:R9C11,MATCH(R[0]C2,R2C10:R9C10,0))"],
  ["=INDEX(R2C11:R9C11,MATCH(R[0]C2,R2C10:R9C10,0))"],
  ["=INDEX(R2C11:R9C11,MATCH(R[0]C2,R2C10:R9C10,0))"],
]
range.formulasR1C1 = data;      
await ctx.sync();                        
range.select();
return ctx.sync();
```
But it still didn't update the Formula Bar.

**Comment by kbrandl** [comment]
@GuoGuitang apologies for the lack of response to the information that you provided in your most recent comment. Are you still having this issue (do you still need help with this)?
