### ISSUE TITLE
Office.context.mailbox.item.getAttachmentContentAsync doesn't return correct base64 format for XML files

### ISSUE THREAD

**Issue by nebojsaaa** [OfficeDev/office-js#4390]
Version
You have Microsoft Outlook Version 1.2024.403.300 (Production).

Client Version is 20240412005.11 .
 
## Expected behavior

It should return correct base64 format for XML files

## Current behavior
When adding XML file through Office.context.mailbox.item.addFileAttachmentFromBase64Async and later on trying to get XML file with Office.context.mailbox.item.getAttachmentContentAsync instead of correct base64 format it returns: 

> `initial-scale=1,user-scalable=0"><metaname=googlevalue=notranslate><metaname=format-detectioncontent="telephone=no"><metaname=scriptVercontent=20240412005.13><metaname=hashedPathcontent=hashed-v1><metaname=physicalRingcontent=WW><metaname=environmentcontent=Prod><metaname=bootFlightscontent=localStorageOwaPrefix,fwk-analytics-addons,acctPersistenceSourceIdV2,dev-offlineMultiAccountDB,fwk-skipnavbardataonhosted,cal-widgets-upn-validation,auth-getAuthTokenV2,shellmultiorigin:394927,cal-perf-eventsinstartupdata:525492,fwk-skipnavbardataonhosted:503140,cal-perf-useassumeoffset:522141,disableofflinedataextractionnetworkdelay:553798,cal-perf-eventsinofflinestartupdata:549998,acct-add-account-e1-improvement:515788,auth-cachetokenformetaoshub:546381,cal-perf-eventsinstartupdatabyviewtype:542451><metaname=cdnUrlcontent=//res.cdn.office.net/><metaname=backupCdnUrlcontent=//res-h3.public.cdn.office.net/><metaname=cdnContainercontent=owamail/><metaname=devCdnUrlcontent=><metaname=ariaUrlcontent=><metaname=webServerForestcontent=eurprd03><metaname=webServerCliquecontent=CLEURPRD03DUB06><metaname=compactAriaUrlcontent=><metaname=wcssFrameUrlcontent=https://webshell.suite.office.com><metaname=wcssFrameUrlscontent={'DefaultUrl':'https://webshell.suite.office.com','WwdbUrl':'https://wwdb.webshell.suite.office.com','EudbUrl':'https://eudb.webshell.suite.office.com'}><metaname=scriptPathcontent=scripts/><metaname=owaIsAuthenticatedcontent={{IsAuthenticated}}><metaname=jsTimestampcontent=1713868550281><metaname=publicUrlcontent=https://outlook.office.com><metaname=aadAuthorityUrlcontent=https://login.microsoftonline.com/><metaname=businessCanonicalHostNamecontent=outlook.office365.com><linkrel=preconnecthref=//res.cdn.office.net/crossorigin=anonymous><linkrel="shortcuticon"href=/mail/favicon.icotype=image/x-icon><linkrel=apple-touch-iconhref=//res.cdn.office.net/assets/mail/pwa/v1/pngs/apple-touch-icon.png><noscript>JavaScriptmustbeenabled.</noscript><title>Outlook</title><style>@font-face{font-family:FabricMDL2Icons;src:url('//res.cdn.office.net/owamail/20240412005.13/resources/fonts/o365icons-mdl2.woff')format('woff');font-weight:400;font-style:normal}@font-face{font-family:office365icons;src:url('//res.cdn.office.net/owamail/20240412005.13/resources/fonts/office365icons.woff?')format('woff');font-weight:400;font-style:normal}#loadingScreen{position:fixed;top:0;bottom:0;left:0;right:0;background-color:#fff}#loadingLogo{position:fixed;top:calc(50vh-90px);left:calc(50vw-90px);width:180px;height:180px}#MSLogo{position:fixed;bottom:36px;left:calc(50vw-50px)}.dark#loadingScreen{background-color:#333}.darkNew#loadingScreen{background-color:#1f1f1f}</style><scriptnonce=Ed3DIoUwJ3vOTme41d6yMA==>try{!function(){if("localStorage"inwindow){vare=window.localStorage.getItem("UsersNormalizedTheme");e&&/\.dark$/.test(e)&&document.documentElement.classList.add("dark"),e&&/\.dark\.new$/.test(e)&&document.documentElement.classList.add("darkNew");vart=window.localStorage.getItem("PwaTheme");if(t){vara=document.getElementsByName("theme-color");a&&a.length&&a[0].setAttribute("content",t)}}}()}catch(e){}</script><scriptnonce=Ed3DIoUwJ3vOTme41d6yMA==>functionlogError(r,o,n,e,a,i){window.owaErrorHandler?window.owaErrorHandler(r,o,n,e,a,i):window.owaBackfilledErrors.push(arguments)}window.FabricConfig={fontBaseUrl:null},window.owaBackfilledErrors=[],window.onerror=logError,"onunhandledrejection"inwindow&&window.addEventListener("unhandledrejection",(function(r){varo=r&&r.reason||"[noreasongiven]";oinstanceofError?logError("UnhandledRejection:"+o,"",0,0,o):o.responseErrorMessage&&o.callstackAtRequest&&oinstanceofResponse?logError(o.responseErrorMessage,"",void0,void0,void0,o.callstackAtRequest):logError("UnhandledRejection:"+("string"==typeofo?o:JSON.stringify(o)))})),window.onload=function(){varr=self.location;!self.Owa&&r&&void0!==r.search&&-1==r.search.indexOf("gulp")&&-1==r.search.indexOf("branch")&&(-1==r.search.indexOf("bO=2")?r.search+=(r.search?"&":"?")+"bO=2":r.assign("/owa/auth/frowny.aspx?bret=fail&esrc=IndexPageIncomplete&app=Mail&bO=2"))}</script><linkintegrity="sha256-8GAEUZdcOGcrnOJWxdh/JCf2KalMbT2VCYVYg/35HNg="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.mail.runtime.ef1ab2ea.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-sEEnixVtd71VMBclDaVdhfHYcUFWwwyc4BAoot1uL+s="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.mailindex.5af6bd2f.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-KxD13ZVDGMNV6ASB7WylbLjO7ZXc9qcPHqvfykz8/38="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.929618.m.d77b62c7.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-Ux47soi0e5oKTITLiCDa3LN5krUU52S2mynddYwph1c="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.AppBoot.m.dd6d7241.css"as="style"crossorigin="anonymous"/><linkintegrity="sha256-T/ylu4Usv5lLmmG3JzgfDApmR4C28SwD6xaiatqgCAU="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.AppBoot.m.bd769da7.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-rHkciquAncOAi6VGKCrIeJ365i/ki5OKvUOCSBVbDd4="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.778996.m.bbcc0347.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-7Ov+VsxE6Co5LU1iYnUX+ItC2+gj4YmjczmM7Q/hcAA="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.407663.m.b2425e3e.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-/iQ5/ltcDeairMLLYdqzkUpfAbubouG+uq1W2QqgKvY="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.896847.m.3b825bb3.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-E9rgQKrg4l+ud4BU5z8HfTtDOiD1HYbUCSs04lN+Ueg="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.741001.m.cae45db0.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-BKJsZeHWx5U2VNqWmArtTzI8+ElqzB0+1adEw3E63RU="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.209952.m.31277333.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-382/NxV9twGZKDgcPbLFSLGB1oXhfUAzpxiy+KqaDUY="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.6014.m.1950f0f4.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-uGEu7/QdUu/V5aD0kjhu2wIs2J3HxZvFoHWWdKfHKAQ="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.112988.m.e6971702.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-eMGTwAD3FXswHZuBHzdtlFe8F20Yy9CdQrOvraJuT90="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.981965.m.f2da0c87.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-LNfLfw/WmDFRPHOzocL/Mrjwc+NLEk53JleHmDRXWXY="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.344475.m.5191e6cf.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-XFUa0dO+haMVLN8tWAnLY8dkSXDQIvYvIkpRYyK+sQE="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.147583.m.294f5cee.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-QAX4VuhL6j3J1OPVr6pF+W0UHR7rOIeOoPZfKjtFRHU="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.198802.m.36b8c220.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-4rohpeylY2dMHJ2a5NfOl/1Pzj053wTmiNiHuSxddxI="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.768966.m.7d9fce88.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-1RAyKkSfs6bKW7o43wkbXLuqkquVr5UA+PUDEMjiGdc="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.508748.m.8750d428.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-h7uOIrxpr1JABRqSP4t7AtpxpMb6oXcXCzSRHgQQh1Y="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.313380.m.8dfdc935.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-XC8A9g5TY0zkfdpDwooiSrGcniUI3dI8S8crfQ6PM/k="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.83624.m.8509d3b6.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-w2jzSDJUN2t20HnqxuFyDI5WWLhz50Rcz9fGiceDRss="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.939129.m.5cdb27ff.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-lHgGlW0L2CL3zANZC5qKT3bD6oDqoG0tLuiHgm+q3cY="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.709077.m.a2d6cefc.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-dYO9mNGnXs5Ip9N8QFZD6jeTr3s0oT/FyfE1h9gn/4s="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.728696.m.10e32392.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-OG70sLsG4snddac8R4sdNMdGLug5BYCKmvIbhP/OO04="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.716384.m.3cf2e6a0.js"as="script"crossorigin="anonymous"/><linkintegrity="sha256-v1hnjS27RDPhNtcxn7+Y75Z3yyvxBPTO7hTo3YeHydM="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.MailBoot.m.8dd86dc1.css"as="style"crossorigin="anonymous"/><linkintegrity="sha256-EvCno5aHC0m64qZOLRtH5BceQBjJyBnKSZBu7CFeQYU="rel="preload"href="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.MailBoot.m.af1778a9.js"as="script"crossorigin="anonymous"/><scriptintegrity="sha256-8GAEUZdcOGcrnOJWxdh/JCf2KalMbT2VCYVYg/35HNg="src="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.mail.runtime.ef1ab2ea.js"crossorigin="anonymous"></script><scriptintegrity="sha256-sEEnixVtd71VMBclDaVdhfHYcUFWwwyc4BAoot1uL+s="src="//res.cdn.office.net/owamail/hashed-v1/scripts/owa.mailindex.5af6bd2f.js"crossorigin="anonymous"></script></head><bodyrole=applicationclass="ms-font-sdisableTextSelectionms-Fabric--isFocusHidden"><divid=app></div><divid=loadingScreen><divid=loadingLogodir=ltr><style>:root{--s:180px;--envW:130px;--envH:71px;--calW:118px;--sqW:calc(var(--calW)/3);--sqH:37px;--calHH:20px;--calH:calc(var(--sqH)*3+var(--calHH));--calY:calc(var(--calH)+20px);--calYExt:calc(var(--calH)-80px);--calYOverExt:calc(var(--calH)-92px);--flapS:96px;--flapH:calc(0.55*var(--envH));--flapScaleY:calc(var(--flapH)/var(--flapWidth));--dur:5s}#container{width:var(--s);height:var(--s);animation:bouncevar(--dur)infinite}@keyframesbounce{0%,100%,12.5%,32.5%,76.1%{transform:translateY(0)}22.5%,86%{transform:translateY(7px)}}#logo{height:179px;width:130px;overflow:hidden;margin-top:-59px;margin-left:25px}#containerShadow{position:relative;top:120px;left:25px;width:var(--envW);height:var(--envH);border-radius:007px7px;box-shadow:rgba(0,0,0,.25)04px5px;animation:shadow-fadevar(--dur)infinite}@keyframesshadow-fade{0%,100%,21.2%,80%{opacity:0}47%,70%{opacity:1}}#flapContainer{width:var(--envW);margin-top:179px}#ef{width:var(--envW);height:var(--envH);border-radius:007px7px;overflow:hidden;margin-top:-41px}#ef>.l{width:287px;height:var(--envH);background:#28a8ea;transform:translate(-153px,-70px)rotate(28deg)}#ef>.r{width:287px;height:var(--envH);background:#1490df;transform:translate(-120px,63px)rotate(-28deg)}#eb{width:var(--envW);height:40px;background:#123b6d;margin-top:-70px}#cal{display:flex;flex-wrap:wrap;width:var(--calW);height:var(--calH);border-radius:7px;overflow:hidden;margin:0auto;margin-top:-306px;animation:cal-bouncevar(--dur)infinite;animation-timing-function:cubic-bezier(0,0.5,0,1);transform:translateY(var(--calYExt))scaleY(1)}@keyframescal-bounce{0%,100%,16.5%,76.1%{transform:translateY(var(--calY))scaleY(1)}28%{transform:translateY(var(--calYOverExt))scaleY(1)}31%{transform:translateY(var(--calYExt))scaleY(1.05)}33%{transform:translateY(var(--calYExt))scaleY(.96)}34%,68.5%{transform:translateY(var(--calYExt))scaleY(1)}68.5%{animation-timing-function:cubic-bezier(0.66,-0.16,1,-0.29)}}#cal>.t{width:var(--calW);height:calc(var(--calHH)+1px);margin-bottom:-1px;background:#0358a7}#cal>.r{display:flex;width:var(--calW);height:var(--sqH)}.s{width:var(--sqW);height:calc(var(--sqH)+1px)}.s1{background:#0078d4}.s2{background:#28a8ea}.s3{background:#50d9ff}.s4{background:#0364b8}.s5{background:#14447d}#openedFlap{width:var(--envW);height:107px;animation:opened-flap-swingvar(--dur)infinite;animation-timing-function:cubic-bezier(0.32,0,0.67,0);transform-origin:top;transform:translateY(-68px)rotate3d(1,0,0,-180deg)}@keyframesopened-flap-swing{0%,100%,14.5%,76%{transform:translateY(-68px)rotate3d(1,0,0,-90deg)}16.5%,74%{transform:translateY(-68px)rotate3d(1,0,0,-180deg)}}#closedFlap{width:var(--envW);animation:closed-flap-swingvar(--dur)infinite;animation-timing-function:cubic-bezier(0.32,0,0.67,0);transform-origin:top;transform:translateY(calc(-1*var(--envH)))rotate3d(1,0,0,90deg)}@keyframesclosed-flap-swing{0%,100%,77%,8.5%{transform:translateY(calc(-1*var(--envH)))rotate3d(1,0,0,0)}14.5%,76%{transform:translateY(calc(-1*var(--envH)))rotate3d(1,0,0,90deg)}}#fmask{width:var(--envW);height:107px;overflow:hidden}.flapTriangle{width:var(--flapS);height:var(--flapS);background:#50d9ff;margin:-48pxauto0auto;border-radius:7px;transform:scaleY(.6)rotate(45deg)}#openedFlap.flapTriangle{background:#123b6d}#closedFlap.flapTriangle{background:#50d9ff}</style><divid=container><divid=containerShadow></div><divid=logo><divid=flapContainer><divid=openedFlap><divid=fmask><divclass=flapTriangle></div></div></div><divid=cal><divclass=t></div><divclass=r><divclass="ss1"></div><divclass="ss2"></div><divclass="ss3"></div></div><divclass=r><divclass="ss4"></div><divclass="ss1"></div><divclass="ss2"></div></div><divclass=r><divclass="ss5"></div><divclass="ss4"></div><divclass="ss1"></div></div></div></div><divid=eb></div><divid=ef><divclass=r></div><divclass=l></div></div><divid=closedFlap><divid=fmask><divclass=flapTriangle></div></div></div></div></div></div><imgsrc=//res.cdn.office.net/assets/framework/microsoft.svgid=MSLogoalt=Microsoft></div></body></html>`

In older version of outlook (Version 2403 Build 16.0.17425.20176 64-bit ) this works fine, but in newer version it output code above

## Steps to reproduce

1. Open custom outlook add in
2. Add XML file trough Office.context.mailbox.item.addFileAttachmentFromBase64Async
3. Go to drafts and open draft message and call Office.context.mailbox.item.getAttachmentContentAsync with ID of base64 file

## Context
Worked fine a month ago

**Comment by anjalitp** [comment]
We are not able to repro the issue. Could you please share the script and a sample xml file with us?
