### ISSUE TITLE
Word DocumentSelectionChanged event not firing when selecting a comment in a Word document by clicking on the comment in the interface

### ISSUE THREAD

**Issue by iShtopoR** [OfficeDev/office-js#4394]
Version: Word Online.

I'm facing is that I'm using 

```
Office.context.document.addHandlerAsync(Office.EventType.DocumentSelectionChanged, (event: any) => { 
    console.log("event", event);
}); 
```

to track changes in the getSelection method in a Word document within my Add-in plugin. I aim to retrieve the content of a comment. However, when selecting a comment through the interface, the selection doesn't change, thus preventing me from accessing the comment's content.

```
const comments = context.document.getSelection().getComments();
comments.load("items");
await context.sync();
comments.items.forEach((comment: Word.Comment) => {
    console.log("Comment: ", comment.content);
});
```

![image](https://github.com/OfficeDev/office-js/assets/9057634/8bdb237d-acff-4614-9e5a-1c643fc3097a)

**Comment by xiruatms** [comment]
@iShtopoR, thanks for reporting this. After some internal investigation, this is currently a by-design behavior.  Comments are handled in a different way from the main body of the document. There's no recent plan to support this.
