### ISSUE TITLE
Missing property or function for retrieving folder of Office.context.mailbox.item

### ISSUE THREAD

**Issue by sandymane** [OfficeDev/office-js#4399]
We can't get the mailbox folder of the selected message in Outlook directly in office-js.

No property or function  described here allows us to find out this info : https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/preview-requirement-set/office.context.mailbox.item?view=common-js-preview 

I don't want to use Microsoft graph or EWS api to retrieve it.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook application and web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® pour Microsoft 365 MSO (Version 2311 Build 16.0.17029.20140) 
* Operating System: Windows 11 enterprise
* Browser (if using Office on the web): chrome
 
## Expected behavior
Use a property or a function in Office.context.mailbox.item to get the selected message's folder name

## Current behavior
No property or a function existing in Office.context.mailbox.item to get the selected message's folder name

**Comment by Oleg-O** [comment]
Currently the feature to retrieve item's folder via JS API, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
