### ISSUE TITLE
Roaming Settings not visible on Setting UI.

### ISSUE THREAD

**Issue by neso613** [OfficeDev/office-js#440]
I am developing Outlook web add-in. I have designed setting UI to get-set the user data.
This settings UI opens when roaming settings is empty.It works fine.
As per business logic I have to set the roaming setting before schedule the meeting/appointment. I can set the user data into roaming settings. 

But when I click the add-in command,
`<Action xsi:type="ExecuteFunction"><FunctionName>MySettings</FunctionName> </Action>`
 it shows no data in Setting UI.

## Expected Behavior
If roaming setting are there.It should display setting into Setting UI. If No settings is saved, it prompt to Setting UI and appointment/meeting is populated with saved settings. But when to open the Setting add-in command from ribbon, it shows saved data. 

## Current Behavior
 when I click the add-in command,
`<Action xsi:type="ExecuteFunction"><FunctionName>MySettings</FunctionName> </Action>`
 it shows no data in Setting UI.

## Your Environment
Platform [PC desktop, Mac, iOS, Office Online]: Outlook for Windows
Host [Excel, Word, PowerPoint, etc.]: Outlook

**Comment by exextoc** [comment]
Since you are using uiless commands, RoamingSettings is initialized from the persisted storage only when the item is opened. A workaround to access the persisted changes, is to close and re-open the item. We are aware of this bug and have added it to our backlog. Unfortunately, at this time, there is no timeline for when this bug will be fixed.

**Comment by neso613** [comment]
alright. Thanks for replying.

**Comment by kanaksony** [comment]
Hi, is there any timeline for this bug fix?

**Comment by exextoc** [comment]
The bug has been acknowledged & since we do not have concrete timelines, we are closing this issue. We have an internal bug number that is linked to this post. Whenever this is fixed, we will make sure to respond to this post with the build numbers that have the fix. Internal Bug#: 1056872
