### ISSUE TITLE
Windows Outlook classic UI support OnAppointmentSend and OnNewAppointmentOrganizer should be like ItemSend(Fully functional embedded browser)

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#4400]
<div>Currently,&nbsp;OnAppointmentSend and&nbsp;OnNewAppointmentOrganizer have so much limitation:&nbsp;<a data-cke-saved-href="https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#event-based-activation-behavior-and-limitations" href="https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#event-based-activation-behavior-and-limitations" target="_blank" style="color: rgba(48, 115, 173, 1)">https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#event-based-activation-behavior-and-limitations
</a></div><div><br></div>

<a data-cke-saved-href="https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/onmessagesend-onappointmentsend-events?tabs=windows#supported-clients-and-platforms" href="https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/onmessagesend-onappointmentsend-events?tabs=windows#supported-clients-and-platforms" target="_blank" style="color: rgba(48, 115, 173, 1)">https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/onmessagesend-onappointmentsend-events?tabs=windows#supported-clients-and-platforms
</a></div><div><br></div>
<div>Hope WIndows Outlook classic UI can support fully functional embedded browser.</div><div><br></div>

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2487.5">
</head>
<body>

Platform Limitation | Exchange On Premise Server | Fully functional embedded browser | cookie(login status can’t use with cookie) | localStorage(login token also can’t be used in localStorage) | MS SSO authentication(login status with SSO)
-- | -- | -- | -- | -- | --
Windows Outlook(classic UI event-base action: OnAppointmentSend) | ✓  Yes | ✖  No, a custom sandbox process that contains a react native control with a JavaScript engine | ✖  Not support | ✖ Not support and OfficeRuntime.localStorage And Office.context.roamingSettings Can’t save login token as your official document suggestion. | ✓  Yes workaround solution for not support cookie and localStorage for login status and token not work. use MS SSO auth to login. But there are some reasons why we don’t want use this solution. 1.✖the auth process is too slow to login, if every time need auth, it’s too slow and heavy. 2.✖ only support exchange online office365 license account. 3.✖ Not all account can enable SSO auth feature. it’s not work for full case.
Windows Outlook(classic UI on-send feature: ItemSend) | ✓  Yes | ✓  Yes | ✓  Yes | ✓  Yes | ✓  Yes
Windows Outlook(new UI) Version 2206 (Build 15330.20196) or later | ✖ N/A | ✓  Yes | ✓  Yes | ✓  Yes | ✓  Yes
Mac Outlook(classic UI) Version 16.65.827.0 or later | ✓  Yes | ✖ N/A | ✖ N/A | ✖ N/A | ✖ N/A
Mac Outlook(new UI) Version 16.65.827.0 or later | ✖ N/A | ✓ Yes | ✓  Yes | ✓  Yes | ✓  Yes
Web browser (modern UI) | ✖ N/A | ✓ Yes | ✓  Yes | ✓  Yes | ✓  Yes
iOS | ✖ N/A | ✖ N/A | ✖ N/A | ✖ N/A | ✖ N/A
Android | ✖ N/A | ✖ N/A | ✖ N/A | ✖ N/A | ✖ N/A

</body>
</html>

**Comment by davidchesnut** [comment]
Hi @hello-chenchen, thanks for letting us know about this request. @exextoc can you please take a look at this issue? Thanks!

**Comment by ztcdsb** [comment]
Currently the feature you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by hello-chenchen** [comment]
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/win-outlook-win32-support-onappointmentsend-and/idi-p/4189714#M2623

https://feedbackportal.microsoft.com/feedback/idea/867e188d-77fd-ee11-a73d-6045bd841c15

**Comment by hello-chenchen** [comment]
hi @ztcdsb  @exextoc , please reopen this ticket, i have post the request in [Tech Community Page](http://aka.ms/M365dev-suggestions), but it was closed.

**Comment by hello-chenchen** [comment]
CC @lindalu-MSFT @exextoc
