### ISSUE TITLE
Office library not loading for iOS 17.4

### ISSUE THREAD

**Issue by tallain-rivaengine** [OfficeDev/office-js#4402]
# Provide required information needed to triage your issue
Office.onReady and Office.initialize are unavailable for iOS 17.4 and above
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: iOS
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook 4.2412.0
* Operating System: iOS 17.4
* Browser (if using Office on the web): Safari
 
## Expected behavior

Calling Office.onReady or Office.initialize should load the OfficeJS library.
## Current behavior

When calling Office.onReady or Office.initialize in iOS environments that are using version 17.4 or above, the library is never loaded and no error messages are shown. Our application also hangs and we never finish the call to .onReady or .initialize.

## Steps to reproduce

1. With a mobile device running iOS 17.4 or above
2. Attempt to call Office.onReady or Office.initialize 
3. Library is not loaded

## Link to live example(s)

N/A

# Provide additional details

We have tried initializing Office with the Office.onReady and Office.initialize methods. The code snippets we have tried are below:

Office.onReady
```
RivaLogger.WriteTrace("Authorize", "Office.onReady", "Before Office.onReady");
Office.onReady(function () {
    // Office is ready.
    RivaLogger.WriteTrace("Authorize", "Office.onReady", "After Office.onReady");

    $(document).ready(function () {
        // The document is ready.
        RivaLogger.WriteTrace("Authorize", "$(document).ready", "After $(document).ready");
    });
});
```

Office.initialize
```
RivaLogger.WriteTrace("Authorize", "Office.initialize", "Before Office.initialize");
Office.initialize = function () {
    // Office is ready.
    RivaLogger.WriteTrace("Authorize", "Office.initialize", "After Office.initialize");

    $(document).ready(function () {
        // The document is ready.
        RivaLogger.WriteTrace("Authorize", "$(document).ready", "After $(document).ready");
    });
};
```
## Context

All we are trying to do is load the Office library. When we run the exact same code snippets with mobile devices using Android or iOS versions before 17.4, the library is loaded without issue. A summary of the iOS and Outlook versions we have tried is below:

| &nbsp;                | Outlook 4.2412.0 | Outlook 4.2413.0 | Outlook 4.2414.0 | Outlook 4.2415.0 |
| ----------------------| -----------------| -----------------| -----------------| -----------------|
| iOS Version 15        | YES              | YES              | YES              | YES              |
| iOS version 16        | YES              | YES              | YES              | YES              |
| iOS version 17.4      | NO               | NO               | NO               | NO               |
| iOS version 17.5beta2 | NO               | NO               | NO               | NO               |
| iOS version 17.5beta3 | NO               | NO               | NO               | NO               |

**Please note:** We have also tried enabling/disabling the 'Prevent Cross-Site Tracking' and the 'Block Pop-ups' options in the Safari browser, to no effect.
 
## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

I've attached two screenshots of our logging of the above two calls from the code snippets. You can see that we are getting the logs before we call .onReady or .initialize, but no logs occur afterwards.

Office.onReady
![iOS_onReady](https://github.com/OfficeDev/office-js/assets/127437131/28dd6947-3b86-46e0-aa7a-4578e47828a9)

Office.initialize
![iOS_initialize](https://github.com/OfficeDev/office-js/assets/127437131/c50afa08-9974-44bd-bf42-da8e6ca5a02a)

**Comment by neprasad-microsoft** [comment]
Hi @tallain-rivaengine 
We tried on iOS 17.4 with Outlook 4.2414 and were not able to reproduce the issue. Can you help us with the following queries for further debugging?

1. Are you able to run any other add-in? 

2. Please capture the logs and send it to us . Instructions on how to collect logs - https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues

3. Please add a try catch in office.initialize and print the error in catch and let us know the error.
Office.initialize = function (reason) {
  try {
    console.log(`Office.initialize(): Huzzah!`);
  }
  catch(ex){
    console.error(`Office.initialize(): Error! ${ex}`);
  }  
};

4. Is this add-in published? If not, can you share a manifest which we can use for testing?

**Comment by YmaRivaEngine** [comment]
> Hi @tallain-rivaengine We tried on iOS 17.4 with Outlook 4.2414 and were not able to reproduce the issue. Can you help us with the following queries for further debugging?
> 
> 1. Are you able to run any other add-in?
> 2. Please capture the logs and send it to us . Instructions on how to collect logs - https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues
> 3. Please add a try catch in office.initialize and print the error in catch and let us know the error.
>    Office.initialize = function (reason) {
>    try {
>    console.log(`Office.initialize(): Huzzah!`);
>    }
>    catch(ex){
>    console.error(`Office.initialize(): Error! ${ex}`);
>    }
>    };
> 4. Is this add-in published? If not, can you share a manifest which we can use for testing?

1. Are you able to run any other add-in?  Yes
2. Incident ID: EQS9NX52
3. copied the code, and there are no logs printed in the try and catch 
4. Yes, we are working on a sample manifest but we are afraid that cannot replicate easily 

I am not sure if this will help things clear, but to give some background and the usage.
we are using this as part of the graph non-Sso fallback flow for the mobile device 
Office.context.ui.displayDialogAsync(myloginUrl)
myloginUrl is an action method that gets the graph configuration on the server side and redirects the user to the MS AuthorizationRequestUrl, after the user inputs the credentials in the ms356 login prompt (hosted by the child dialog), it will redirect to a callback URL that contains the auth code, (the callback URL is configured in the Azure App Service), the callback URL will hit our action method, that rendering the view along with the auth result, inside of this view page, there is only the code that does Office initialization and Office.context.ui.messageParent(authResult)
we tried to remove Office.context.ui.messageParent(authResult), only keeping Office initialization and logs, as well as the test code, but it never hit the logs. And there is no exception in the parent or any events. 
This flow worked for 2 years but stopped after IOS was upgraded to 17.4. IOS 15 and all Android platforms work as before.
We came out with a workaround that set the auth result in the localstroge. but we found the diag. close() in parent won't close the diag, no exception or event was captured. And this is also happened only in IOS 17.4 and above.

**Comment by DivyaPatidar** [comment]
@YmaRivaEngine Can you try one of the [display dialog samples for Outlook](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#code-samples) and let us know if it works on iOS 17.4 for you?

**Comment by CurtisRiva** [comment]
Looks like there are some commonalities between this issue and others.  This ticket reported it as an iOS 17.4 issue, however looking at the other issues, it may be possible that Safari 17.4 is the culprit.

- #4438 
- #4439
- #4478

**Comment by emmasab** [comment]
Hi @CurtisRiva, does this repro on iOS 17.5 or Safari 17.5 ?

**Comment by GrumpyAL** [comment]
Hello,

I am having a similar problem on iOS 17.5 and 17.6.  When the Office Dialog API is used to redirect to login.microsoftonline.com, the page that microsoftonline redirects back to will not load Office (or at least office.initalize or office.onReady are never called.).

Let's say I have a dialog page (dialog.html).  This page loads Office.js and uses office.initalize.  Consider the following scenarios

- displayDialogAsync to open dialog.html directly: ✅
- displayDialogAsync to open some other page which redirects to dialog.html: ✅
- displayDialogAsync to open to login.microsoftonline.com which redirects with code after login to dialog.html: ❌

Now if you open safari on iOS and then paste in the login.microsoftonline.com URL directly when it redirects to dialog.html office.initalize is still called.  So it appears to be specific to the redirect from login and only when happening inside the Outlook client's browser.

Other scenarios also don't work, such as the method used in the dialog signon sample that uses ASP to do the following:

displayDialogAsync opens Login API which redirects to login.microsoftonline.com URL.
This URL redirects to Authorize ASP API which converts the code to a token and then displays a webpage that loads office. 

All of these scenarios work fine on Outlook for Android, Windows and OWA.  They also work on iOS 17.3.

I have used Fiddler  (on Windows) compared the RAW response of the calls to dialog.html to ensure no headers are getting added by the login page and they appear to be identical if opened directly or through the redirect from login.microsoftonline.com

I'm really not sure where to go with this or why the trip through login.microsoftonline.com would cause it to stop running init on newer iOS versions.
