### ISSUE TITLE
ExtendedOverrides is not a valid child element of OfficeApp

### ISSUE THREAD

**Issue by SamuelTrew** [OfficeDev/office-js#4405]
# Provide required information needed to triage your issue

ExtendedOverrides is not a valid child element of OfficeApp in the namespace of 'http://schemas.microsoft.com/office/appforoffice/1.1"

## Your Environment

* Platform: PC Host: Outlook

* Office version number: 1.13.1 Operating System: Windows 10

* Browser: Chrome

## Expected behavior 

I follow the steps outlined [here](https://github.com/OfficeDev/office-js-docs-pr/blob/1983a874eb2e89ba522aeffcb8e36d2f5c8d66ac/docs/develop/extended-overrides.nd) and I can add an <ExtendedOverrides> field to my manifest.xml.

## Current behavior

When I go to add it (or validate it), it fails. Validating gives the following error:

```
XML Schema Validation Error: Error found during XML Schema validation.

- Details: The element 'officeApp in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1' has invalid child element 'ExtendedOverrides' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1'. List of possible elements expected: any element in namespace 'http://www.w3.org/2000/09/xmldsige*. - Line: 100 Column: 4
```

## Steps to reproduce

1. Add <ExtendedOverrides> field below <VersionOverrides>

2. `npm run validate`

3. Should fail

# Provide additional details

My VersionOverrides of the following format:

```xml
<VersionOverrides xmlns=http://schemas.microsoft.com/office/mailappversionoverrides xsi:type="VersionOverridesV1_0">
  <VersionOverrides xmlns-http://schemas.microsoft.com/office/mailappversionoverrides/1.1 xsi: type="VersionOverridesV1_1">
   ... 
  </VersionOverrides>
</VersionOverrides>
```

with the ExtendedOverrides follows:

```xml
<VersionDverrides xmlns=http://schemas.microsoft.com/office/mailappversionoverrides xsi:type-"VersionOverridesV1_8">
  <VersionOverrides xmlns=http://schemas.microsoft.com/office/mailappversionoverrides/1.1 xsi:type="VersionOverridesV1_1">
   ... 
  </VersionOverrides>
</VersionOverrides> <ExtendedOverrides Url-"(APP_URL_OUTLOOK}/shortcuts.json"></ExtendedOverrides
```

## Context

I am trying to add keyboard shortcuts to my Outlook Add-in to open and close the taskpane, just as in the examples given.

## Useful logs

```
Error #1: XML Schema Validation Error: Error found during XL Schema validation.
 - Details: The element "OfficeApp' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1' has invalid child element 'ExtendedOverrides' in namespace 'http://schemas.microsoft.com/office/appforoffice/1.1'. List of possible elements expected: any element in namespace 'http://www.w3.org/2008/09/xmldsiga". 
- Line: 100 Column: 4

Error #2:

XML Schema Violation: Your manifest does not adhere to the current set of XML schema definitions for Office Add-in manifests. The manifest is not valid.
```

**Comment by neprasad-microsoft** [comment]
Hi @SamuelTrew 
Keyboard shortcuts are not supported on Outlook according to this doc -https://learn.microsoft.com/en-us/office/dev/add-ins/design/keyboard-shortcuts . It is only supported on Excel.

**Comment by SamuelTrew** [comment]
@neprasad-microsoft Ah missed that part, thank you.

Is there any plan to add support for them do you know?

Thank you.

**Comment by neprasad-microsoft** [comment]
Hi @SamuelTrew 
Unfortunately since this is a new feature, we cannot help you on this forum. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by SamuelTrew** [comment]
Thank you!

**Comment by denis-kalinin** [comment]
There is an ambiguity in the documentation. Although ExtendedOverride is [in the XML schema](https://learn.microsoft.com/en-us/openspecs/office_file_formats/ms-owemxml/00e4ee5d-2eb8-47f2-9008-8beb6ff45189), it is absent in [the Outlook manifest docs](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering#basic-mail-add-in-element-ordering).
