### ISSUE TITLE
GetAttachmentsAsync does not return the list of attachments in Outlook Online

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#4406]
# Provide required information needed to triage your issue
When using the method getAttachmentsAsync in Outlook Online, the list of the attached files are not listed. You always get an empty array. On Outlook for Windows the returned list is correct.

## Your Environment

* Platform: Office on the web
* Host: Outlook
* Operating System: Windows
* Browser: Edge
 
## Expected behavior
Office.context.mailbox.item.getAttachmentsAsync should return the list of attached files, also the inline ones.

## Current behavior
**Outlook Online**
An empty array is returned.
![image](https://github.com/OfficeDev/office-js/assets/6338132/1b2a003c-0b4e-4088-aad4-d8a56b81dfcf)

**Same call in Outlook for Windows**
![image](https://github.com/OfficeDev/office-js/assets/6338132/d5acdec5-45a2-44b0-8b3f-777038b2c813)

## Steps to reproduce
1. Open Outlook Online
2. Create a new mail
3. Attach a file to the mail
4. Open Script Lab
5. call Office.context.mailbox.item.getAttachmentsAsync(console.log) in DevTools or ScriptLab

## Context
I am working on a signature app which uses inline images. 
When switching a signature, which has new images, I want to delete existing inline image attachments.
But currently I can't see which attachments are attached to the mail.

**Comment by neprasad-microsoft** [comment]
Hi @barisbikmaz 
Can you tell us how you are attaching the file? If you are using an API please paste the API call here so that we can reproduce on our side.

**Comment by barisbikmaz** [comment]
@neprasad-microsoft Was on vacation, could therefore not reply.

I open Outlook Online and run following code to add an inline attachment:

`Office.context.mailbox.item.addFileAttachmentFromBase64Async('some-base64-image','myimage.png',{ isInline: true })`

To be sure that the image is attached, I insert a signature referencing this image.

`Office.context.mailbox.item.body.setSignatureAsync('Greetings<br/><img src="cid:myimage.png" />', { coercionType: 'html' });`

This works. But when I run

`Office.context.mailbox.item.getAttachmentsAsync(console.log)`

it does not return the inline attachment.

**Comment by mmanjaree-msft** [comment]
Thanks for reporting this issue. We have put this in our backlog but unfortunately we do not have any timelines to share at this point. 
Internal tracking id: 276714

**Comment by patilganesh-msft** [comment]
The issue has been fixed. The will fix be rolled out to world wide soon.
