### ISSUE TITLE
There is no event for drag and drop of email id in to cc or bcc section in outlook office add-in 

### ISSUE THREAD

**Issue by ASHISDEY1998** [OfficeDev/office-js#4407]
At the time of drag and drop the event was getting triggered twice. One is for source and one is for destination. What is happening is, that the destination event is stopping the source event in the middle before letting the recipient delete from the source. Due to this it's getting duplicated and stored in our storage twice. 

## Your Environment

Platform: Office on the web
Host: Outlook [OWA] & New Outlook [Desktop]
Office version number: Version 2311 Build 16.0.17029.20140
Operating System: Windows
Browser: Chrome & Edge
 
## Expected behaviour
there should be an event for drag and drop of recipients from one section to another section like from TO to CC . 

## Current behaviour
But currently, it's triggering onMessageRecepentChange twice one from drag and one for drop. but the drop event is overriding the drag event in the middle.

## Steps to reproduce

1. Add a repentant into the section
2. drag that to the cc/bcc section
3. There is no event to detect that it's a drag-and-drop event

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by neprasad-microsoft** [comment]
"What is happening is, that the destination event is stopping the source event in the middle before letting the recipient delete from the source." Is this happening in the add-in code ? Cause when we tried it with a test add-in both the events were successfully handled. 
As for the event for drag and drop which you have requested -  Currently this is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by ASHISDEY1998** [comment]
OK sure i will request a feature request for this thanks @neprasad-microsoft  for your suggestion.
