### ISSUE TITLE
Several customers get stuck installing our Powerpoint add-in

### ISSUE THREAD

**Issue by FilipStenbeck** [OfficeDev/office-js#4408]
# Provide required information needed to triage your issue
Several of our customers reports they are getting stuck when installing the plugin. After installation it hangs. It gets stuck in the "Validating" step We have not been able to reproduce this in our environment and we therefor believe this has to do with some settings in our customers environment.  Customers have reported that they see an error from the RichAPI "You don't have sufficient permissions for this action.

We have only got reports from this from customer using Windows but have not been able to reproduce the issue on our Windows PC reference computer. 
 
 Please see screenshots for more information
<img width="1248" alt="Screenshot 2024-04-29 at 10 21 10" src="https://github.com/OfficeDev/office-js/assets/3775432/9f1d14d2-8505-4fe5-8c27-b5c337a6a565">

<img width="1248" alt="Screenshot 2024-04-29 at 10 22 44" src="https://github.com/OfficeDev/office-js/assets/3775432/61a7a998-4f05-4514-a609-99a8938c1f37">

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop______
* Host [Excel, Word, PowerPoint, etc.]:Powerpoint
* Office version number: ?
* Operating System:Windows
 
## Expected behavior
We except the add-in to load. We understand that this is likely caused by settings in the Customers IT-environment, but would really appriciete if you have any ideas what could casue this and how we would be able to help the our customers get around this issue.

**Comment by ElizabethSamuel-MSFT** [comment]
@FilipStenbeck Thanks for raising this issue. Tagging @EsterBergen to triage.

Thanks.

**Comment by EsterBergen** [comment]
@FilipStenbeck - to confirm- is this for Mentimeter? 

Has your customer reported an issue yet when they see this error in PPT? They can find this option when they go to Help> Feedback> Report a problem. This will give us logs and more information on the issue.

![image](https://github.com/OfficeDev/office-js/assets/139180507/e9adebd1-b32f-4517-b44f-d3859548d192)

Another thing for the customer to check is to see if they have blocked Mentimeter for their organization. Can you have them check and see if the admin has Mentimeter listed as a "Blocked App" under Integrated Apps in the M365 Admin Center?
![image](https://github.com/OfficeDev/office-js/assets/139180507/29e7b36d-46cf-4a31-96cc-654699acecce)

**Comment by EsterBergen** [comment]
@FilipStenbeck - following up- did you get a chance to report the problem and confirm the addin is not blocked by admin?

**Comment by EsterBergen** [comment]
@FilipStenbeck - checking in to see if this is still an issue and if you had a chance to report it in app. Please let us know, otherwise, we'll close this!
