### ISSUE TITLE
Smart Alert Feature not working in Outlook Mac Thick Client on OnAppointmentSend events.

### ISSUE THREAD

**Issue by RaveendraReshma** [OfficeDev/office-js#4409]
# Provide required information needed to triage your issue
1) We are developing office web Addin for Outlook using event based (Smart Alert). The Addin is generated using Office Yo generator Task Pane add-in using the React framework.
2) We have Send Mode as "blocked" for  OnAppointmentSend events.
3) The issue appears Only in Outlook Mac Thick Client where, once the user clicks on Send, a dialog with message add in is blocking the send of this message with don't send button is shown.
4) Smart Alerts work fine in Safari browser. The issue only exists in Outlook Mac.

## Your Environment

1. Platform : MAC
2. Host : Outlook on MAC
3. Office version number : Version 16.84.1 (24042118)
4. Operating System : MacOs

## Expected behavior

1) When user clicks on send it should redirect to smart alert dialog, how ever its showing another dialog with message, add in is blocking the send of this message with don't send button.

## Current behavior

1) On click of send another dialog appears with message, add in is blocking the send of this message with don't send button.

## Steps to reproduce

1) Add recipients and click on Send.
2) Below dialog appears with the don't send button.
![image](https://github.com/OfficeDev/office-js/assets/145095553/6f6edb85-9e7e-41aa-bdfe-24930ea44d9d)

## Context

1) The issue is User will not be able to open the taskpane and will be shown a dialog with don't send button as shown below.
![image](https://github.com/OfficeDev/office-js/assets/145095553/dc158320-fa71-4df3-b7e7-5b740044706b)
2) And the same works fine in Outlook on web [Safari].

**Comment by RaveendraReshma** [comment]
To shorten the above,

Issue: Send button not displaying verify button popup and preventing smart alert task pane from opening
 
Issue Description:
Upon clicking on the "Send" button of Outlook, the expected behavior is to display a "Verify" button popup. However, the current behavior is showing a "Don't Send" popup instead, which prevents the smart alert task pane from opening.

Expected Behavior:
After clicking the "Send" button, a popup should appear prompting the user to verify the email address using the "Verify" button. Once verified, control should be transferred to the smart alert task pane.

**Comment by neprasad-microsoft** [comment]
Hi @RaveendraReshma 
Could you paste the event.completed code from your add-in here? Or if possible share it in a private repo and give exextoc access. 
Also, please reproduce the issue and collect logs. Steps to collect logs is captured here - https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues

**Comment by RaveendraReshma** [comment]
@neprasad-microsoft 

1. The incident id for mac - GMTD59HT

2. below is the event.completed code on onSendEvent

event.completed({
                allowEvent: false,
                errorMessage: "Please verify.",
                commandId: "appOrgTaskPaneButton",
                cancelLabel: "Verify",
      });
    }

**Comment by neprasad-microsoft** [comment]
Hi @RaveendraReshma 
We tried with this event.completed code and were still unable to repro this issue. Please share your manifest with us so that we can sideload the add-in and debug to see what the issue is.

**Comment by RaveendraReshma** [comment]
@neprasad-microsoft 

please find below the manifest file
[Manifest.txt](https://github.com/OfficeDev/office-js/files/15224660/Manifest.txt)

**Comment by DivyaPatidar** [comment]
@RaveendraReshma The manifest you provided has localhost URLs thus it won't work for us. Is it possible for you to share manifest with actual URLs or sample add-in code where this issue repros for you?

**Comment by RaveendraReshma** [comment]
@DivyaPatidar 

The smart alerts is now working for both the send events.
