### ISSUE TITLE
office.js callbacktoken for ews write operations.

### ISSUE THREAD

**Issue by garrit-schroeder** [OfficeDev/office-js#441]
Hello and thanks in advance.

Is it possible to use the token returned by getCallbackTokenAsync() for write operations in the ews api?

My scenario is:
I want to send the callbacktoken to a backendserver, which uses this token with the ews api to read the mail. Works great!
Put after that i want to move the mail into another folder. That does not work. I get the error message: 
The requested web method is unavailable to this caller or application.

Is there a way i can use the users oauth token to make mailbox write operations via the ews api?

**Comment by dmahugh** [comment]
@exextoc do you know whether the token can be used as described here?

**Comment by exextoc** [comment]
The EWS token is item scoped so write operation won't work. However calling the API with isRest = true will return a mailbox scoped token that only works with REST and can be used to write.

**Comment by exextoc** [comment]
Bug 1135821<https://o365exchange.visualstudio.com/959adb23-f323-4d52-8203-ff34e5cbeefa/_workitems/edit/1135821>: [OfficeDev/office-js] office.js callbacktoken for ews write operations. (#441)

Updated bug and github thread

Created using VSTS Outlook add-in<https://www.owiki.ms/wiki/VSTS_Add-In_for_Outlook>


Thanks
Sohail

**Comment by kbrandl** [comment]
Closing this issue, as the information provided by @exextoc seems to provide information that effectively addresses it. @garrit-schroeder if that's not the case (and you need further assistance), please comment here and we'll re-open the issue. Thanks!
