### ISSUE TITLE
PowerPoint add-in not displaying in Slide Show display

### ISSUE THREAD

**Issue by SPDoctor** [OfficeDev/office-js#4410]
Many users have reported that when they switch to Slide Show, the PowerPoint content add-in does not display. In some cases users report that the add-in was working in presentations up to some point in time, but that it then stopped working. Others specifically state that it won't work "with a projector" (which probably means it isn't working with external graphics display). Users report the problem persists despite re-installing the add-in.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Windows
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Office version number: multiple versions
* Operating System: Windows
* Browser (if using Office on the web): n/a
 
## Expected behavior
The content add-in is rendered in the Slide Show within the slide.

## Current behavior
A significant proportion of users are complaining that the add-in doesn't render in Slide Show on their systems, or that it used to work but no longer does.

## Steps to reproduce
1. Open PowerPoint
1. Install Breaktime add-in from the store.
1. Add to a slide (the timer is visible in the slide)
1. May need to ensure presenter mode enabled.
1. Switch to Slide Show (it may need to be external monitor to reproduce issue)
1. Note whether the add-in is visible in the slide show.

Note: We have been unable to reproduce in any of our development or test environments. The problem seems to be specific to the user's computer hardware and/or software configuration.

## Context
We are receiving several email/month with users requesting help with this problem. We are unable to reproduce it or provide helpful advice for them to resolve the issue.

**Comment by EsterBergen** [comment]
Can you please continue the conversation here. https://github.com/OfficeDev/office-js/issues/3466

I believe this is a duplicate bug to 3466
