### ISSUE TITLE
Unable to publish manifest file - support URL is not accessible

### ISSUE THREAD

**Issue by smieszkowsk** [OfficeDev/office-js#4413]
We have a problem with uploading a new manifest.xml to MS. We added a new value to AppDomains list but now we are getting validation error that our support URL is invalid (see screenshot). We use the same link for over 2 years and we didn't change anything in it during that period. This blocks us from uploading a new add-in version which contains an important bug fix. 
Please guide us how we can resolve this.

![image](https://github.com/OfficeDev/office-js/assets/124802676/389ac232-80c0-45ef-b381-87659c17c411)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, Mac, iOS, Office on web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: irrelevant
* Operating System: Windows 10/macOS
* Browser (if using Office on the web): -
 
## Expected behavior
We should be able to upload the manifest with no issues. We didn't change a link in any way so we don't see a reason why it is not accepted now.

## Current behavior
We are getting error message: "The manifest support URL is not accessible" even though it is.

## Steps to reproduce
Use https://spreadsheet-sync.app.intuit.com/one-intuit-help-system/oihs-panel as support URL and try to go though validation process (npx office-addin-manifest validate -p <manifest_path>)

## Link to live example(s)
-

# Provide additional details
-

## Context
-

## Useful logs
-

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by shanshanzheng-dev** [comment]
Hi @Rick-Kirkham Could you please help take a look this issue? Thanks.

**Comment by Rick-Kirkham** [comment]
Sorry, but this is not a documentation issue and I don't have the expertise to respond.

**Comment by smieszkowsk** [comment]
@shanshanzheng-dev any chance someone else can help with this please? Or is there any other way we can contact MS support?

**Comment by shanshanzheng-dev** [comment]
Hi @smieszkowsk, sorry for slow response. Could you please try to check following Microsoft article as reference with manifest.xml: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/add-in-manifests?tabs=xmlmanifest?
After development, you can try to check this article to validate your manifest if working fine or not https://learn.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest.
Thanks.

**Comment by smieszkowsk** [comment]
We are familiar with those articles, it is not the first time we upload the manifest. The issue is that that support url used to work in the past and now we're getting this error. Is there any way someone from MS could verify what is blocking this validation? We don't think anything has changed from our side so it's difficult for us to understand the issue. Thanks

**Comment by shanshanzheng-dev** [comment]
Hi @AkhileshShah-MS, seems this is a validation error when uploading a new manifest.xml to MS. Could you help to take a look this issue? Thanks.

**Comment by akshayta23** [comment]
We looked into the issue and it seems like HEAD is not enabled in your support URL. Please enable it and resubmit the manifest. Your manifest should pass the Package Acceptance check.

**Comment by smieszkowsk** [comment]
Is it really required to have HEAD enabled? Due to our internal policy we are unable to just enable HEAD requests.

**Comment by akshayta23** [comment]
Yes, you would need to enable HEAD since this is a requirement from the marketplace. We understand that this might be a difficult change, but our internal policies require this for all offers to proceed with the submission. The Package Acceptance response also covers this requirement. Please let us know if you have any other questions. 
![image](https://github.com/OfficeDev/office-js/assets/69890192/c9cb1a28-9564-49ae-8b60-2d63b55a47b5)

**Comment by smieszkowsk** [comment]
Thank you, I'm checking with my team how we can resolve this.

**Comment by shanshanzheng-dev** [comment]
Hi @smieszkowsk Hope you get this issue fixed. I'll close this issue. If you still need assistance and we'll re-open the issue. we value your feedback. Thanks.
