### ISSUE TITLE
Failed to install or load custom functions addin On microsoft 365 Web Production

### ISSUE THREAD

**Issue by jbqmGit** [OfficeDev/office-js#4418]
# Provide required information needed to triage your issue

## Your Environment

Platform [PC desktop, Mac, iOS, Office on the web]: PC, Mac, Web
Host [Excel, Word, PowerPoint, etc.]: Excel
Office version number: Office 2021 Version 2108, Office 365 Version 2401
Operating System: Windows 10, Mac OS
Browser (if using Office on the web): Chrome, Firefox, Edge
## Expected behavior

Custom Addin should load on web with all functions available and no errors.

## Current behavior

When installing the Quotestream active sheets addin on web, via add-in store,. The addin will load, but then fail to load when returning to the worksheet or creating a new worksheet with it automatically installing

We've tried https://learn.microsoft.com/en-us/office/dev/add-ins/develop/run-code-on-document-open
but after our latest production release, we still encounter issues.

## Steps to reproduce

1. Install the addin via Appstore on Web, shoulk work the first time
2. close the document on web, and then reopen it (or open a new document. Custom functions will report that they failed to load

## Link to live example(s)

1. ______ https://appsource.microsoft.com/en-us/product/office/WA200005380?tab=Overview
2. ______
3. ______

# Provide additional details

1. When using our Hosted cloudflare server to deploy our manifests for QA and UAT testing, we don't encounter this issue at all. but when we release this add-in to production, it fails to load these custom functions, and we have no information as to why we cannot run it.

## Context

Our add-in has not been properly loading for users, Microsoft 365 is our only option for users running very outdated versions of Excel(who do not want to upgrade), to have access to our addin

## Useful logs

Microsoft does not log this, they only display the error with no information.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by shanshanzheng-dev** [comment]
Hi @ruijiaMS Could you please help take a look this issue? Thanks.

**Comment by ruijiaMS** [comment]
Hi @jbqmGit,
Thanks for letting us know this issue. I cannot repro this issue locally for both re-opening the previous workbook or opening a new workbook and the Quotestream addin works well in my environment. Could you please provide a recording video for your issue and what error message it was saying when you are facing it?
