### ISSUE TITLE
Activating a new worksheet results in unexpected worksheet behavior

### ISSUE THREAD

**Issue by MakotoE** [OfficeDev/office-js#442]
## Expected Behavior
1. Run script which adds a new worksheet, then activates the new worksheet.
2. Typing using the keyboard adds letters to the currently selected cell.
3. Clicking outside the selected cell will exit edit mode. Moving the cursor does not highlight cells.

## Current Behavior
1. Run the script.
2. Typing using the keyboard adds letters to the currently selected cell.
3. Clicking outside the selected cell moves the cell to a new position. Moving the cursor (without dragging) highlights cells. Double clicking exits edit mode and returns the cell back to its normal position.

This isn't reproducible 100% of the time, so repeat once more if it didn't behave as described.

## Steps to Reproduce, or Live Example
This is a screen capture showing this behavior: https://1drv.ms/u/s!Ai_dcjybnKQ5ij9dRoDcr5Zl3Kpl

The script (Use Basic API Call (JavaScript) template in Script-Lab):

```javascript
$("#run").click(() => tryCatch(run));

function run() {
  return Excel.run(async (context) => {
    const worksheetToUse = context.workbook.worksheets.add();
    worksheetToUse.activate();
    await context.sync();
  });
}

/** Default helper for invoking an action and handling errors. */
function tryCatch(callback) {
  Promise.resolve()
    .then(callback)
    .catch(function(error) {
      // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
      console.error(error);
    });
}
```

This does not occur if the user clicks to change cell selection after step 1 and before step 2 in Current Behavior.

## Context
My add-in will create a new worksheet, switch to it, then add values to it. When the add-in finishes this task, the user should be able to use their keyboard to edit the currently selected cell.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.11519.31877
* Operating System: Debian GNU/Linux 9 (stretch) 64-bit
* Browser (if using Office Online): Firefox 66.0 (64-bit)

## Useful logs

- [ ] Console errors (None emitted during execution of script)
- [x] Screenshots (Screen capture linked above)
- [ ] Test file (if only happens on a particular file)

**Comment by lumine2008** [comment]
Thanks @MakotoE, I have tried in my side, looks it is not repro. 
I am using 16.0.11523.35900 in Chrome on windows 10.

**Comment by MakotoE** [comment]
Sorry, I don't have either Firefox or Chrome on my Windows machine, but I tried this on Chrome 73.0.3683.75 for Linux, and I couldn't reproduce it, which might mean that this is a **Firefox** specific problem. It could not be reproduced on Edge. Do press the "Highlight selected range" button twice as the first time does not exhibit the bugged behavior.

**Comment by MakotoE** [comment]
I just installed Firefox 66.0.1 on Windows 10 and reproduced the bug, which means this is not OS specific.

**Comment by kbrandl** [comment]
@MakotoE are you still having this problem?
