### ISSUE TITLE
Support drag and drop on OfficeJS addins Outlook

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js#4422]
when do they implement drag and drop functionality? Is the feature at least in the road map? Where I see the progress?

**Comment by ElizabethSamuel-MSFT** [comment]
@CodeCube0 Thanks for asking about this.

@m-hellesen Are you to correct person to look into this? If not, do advise ASAP so we can reassign.

Thanks.

**Comment by CodeCube0** [comment]
do you have any news? @ElizabethSamuel-MSFT @m-hellesen

**Comment by CodeCube0** [comment]
Is there any news? @ElizabethSamuel-MSFT @m-hellesen

**Comment by JuaneloJuanelo** [comment]
@CodeCube0  we have an item in our backlog to work on this. However, we want to understand in more detail what you need. questions for you:
1. whats your scenario? you are dragging items from outlook into the taskpane? other way around?
2.  what types of items are you dragging and what properties you are expecting to have for your scenario to work?
3. In what platform this is an issue? I.e. Win32 already supports drag and drop, are you targeting a specific platform?  what issues have you observed? 
thanks!

**Comment by CodeCube0** [comment]
From Outlook Web, it's not possible to discern which email is being dragged because while in Outlook Desktop, you're actually dragging a file, in Outlook Web, you're dragging an HTML tag. It would be useful to have the email ID or other parameters to download the email file or understand which email is being dragged.

**Comment by JuaneloJuanelo** [comment]
@CodeCube0    to clarify, you are dragging an Outlook email into the taskpane, right?. Can you please confirm this is working on Desktop? you should .. thanks!

**Comment by CodeCube0** [comment]
It works but only in the old outlook not in the new outlook

**Comment by CodeCube0** [comment]
Is there any news on this topic? @JuaneloJuanelo

**Comment by xuantien0404** [comment]
Hi @JuaneloJuanelo We have a same issue.
We develop a add-in on Outlook Web as well. And we want to drag an Outlook email into the taskpane. Then save this mail to our project. 
Do you have any update? Please let me know.

**Comment by xuantien0404** [comment]
Hi @CodeCube0,
Have you solved this issue yet?
