### ISSUE TITLE
How to upload powerpoint office addin manifest.xml in the Admin Center?

### ISSUE THREAD

**Issue by yamapi-t** [OfficeDev/office-js#4427]
For deployment in organisation, I want to upload `manifest.xml` file to Admin Portal.
According to the following site, I went to [settings] → [Integrated App], but the Add-ins page does not exist.

https://learn.microsoft.com/en-us/microsoft-365/admin/manage/manage-deployment-of-add-ins?view=o365-worldwide

I also tried to see if I could do it from [Integrated App] → [Upload custom apps], but the form was disabled with the app type option fixed to Teams.

Let me ask you the following two questions:

- My current authority is Application Administrator, do I need stronger authority? If so, what authority is needed?
- Could addin deployment be disabled by the organisation? If so, How can it be enabled?

**Comment by ElizabethSamuel-MSFT** [comment]
@yamapi-t Thanks for asking about this. Tagged @AkhileshShah-MS to take a look.

Thanks.

**Comment by AkhileshShah-MS** [comment]
Thanks for reaching out @yamapi-t ! 
Yes, you would require a Global Administrator role to upload and manage add-ins from Integrated Apps page. 
Please let me know if you face further issues with this.

**Comment by yamapi-t** [comment]
@AkhileshShah-MS 
Thanks for the reply.

I have added Global administrator, but still there is no add-in page in the [integrated app].
Also app type in the  [Upload custom apps] form is disabled with [Teams] and the office `manifest.xml` cannot be uploaded.

What should I do?

**Comment by AkhileshShah-MS** [comment]
@yamapi-t Does your tenant have an active exchange online license? Capability to upload xml manifest is available to Global Admins having exchange online license.

**Comment by yamapi-t** [comment]
@AkhileshShah-MS 
I checked and the current Microsoft plan is 'Microsoft 365 Apps for business' and does not have an exchange online license.
Let me further confirm the following points:

- Just to confirm, is it correct to say that Microsoft 365 Apps for business does not allow for deployment within an organisation?
- Can I publish to the Office Store even if I am using Microsoft 365 Apps for business?

**Comment by yamapi-t** [comment]
@AkhileshShah-MS Could you please confirm this?

**Comment by AkhileshShah-MS** [comment]
Hi @yamapi-t! You can find detailed description about supported licenses, admin roles and other prerequisites for app management in our documentation here - https://learn.microsoft.com/en-us/microsoft-365/admin/manage/office-addins?view=o365-worldwide. 
Please let me know if you have further questions around this and i'd be happy to address those. 
Thanks!

**Comment by yamapi-t** [comment]
@AkhileshShah-MS 
I think the document in the URL is about deployment within the organisation, is that correct?

I understand that Exchange Online is required for within-organisation deployments.
On the other hand, do I need Exchange Online for non-organisational deployments and releases to the public?

**Comment by AkhileshShah-MS** [comment]
Hi! @yamapi-t! Apologies for the delay in response here. 

No, an exchange license is not needed for releasing the add-in on public store or sharing the manifest with other customers. Exchange license is needed only for deploying in your own organization. 

Thanks!

**Comment by RuizhiSunMS** [comment]
Hi @yamapi-t, may I know that your case is resolved or not?
