### ISSUE TITLE
Outlook Add-in will not open in new Outlook for Windows

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#4429]
# Outlook add-in will not open for some users in new Outlook for Windows UI

The Outlook add-in that works in all other environments, including Outlook for Windows (not the new UI) will not open for some users when using the new UI.

It also does not appear to matter whether the add-in is deployed via side-loading or as an admin managed deployment.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft Outlook Version 1.2024.501.300 (Production) (Client Version is 20240419007.35)
* Operating System: Windows 11 Home (23H2 -- 22631.3447)
 
## Expected behavior
The add-in opens and loads like normal in the new Windows UI.

## Current behavior
The user will click to open our add-in via the Apps popup or a pinned action and the add-in does not open. It appears to do nothing at all.

See the video [here](https://drive.google.com/file/d/17ObRzmmrUhLJzPgLXMRxkPiOA0k77CTV/view?usp=sharing). Note that the user is clicking the add-in and it's doing nothing at all (the user does show that some other add-in does open fine).

## Steps to reproduce
I can provide our add-in's manifest if needed, but it is not a publicly available. It also does not happen for all users, so it's unknown if you would be able to reproduce the issue.

## Context
This is related to the bug filed [here](https://github.com/OfficeDev/office-js/issues/4395). We have some very large customers who are starting to see this as their users upgrade to using the new UI and we currently need to tell them to revert to the old UI.

## Useful logs
[outlook.office.com.har.zip](https://github.com/OfficeDev/office-js/files/15250899/outlook.office.com.har.zip)

A larger log set can be found [here](https://drive.google.com/file/d/1Sqde03yHaDfD35iE7vS6GfTQ6J2NLAsh/view?usp=sharing)

**Comment by mmanjaree-msft** [comment]
@cody-lettau We checked the logs, few of the calls we needed to investigate were missing can you please reshare another log with the following steps which will make sure we have all the required calls in the log-
Steps to capture-
Start capturing logs and launch owa or refresh the window in case its already launched
Wait for add-ins to appear and click on your add-in to open it. 

Can you please also check if you see any errors in console after you click on the add-in

**Comment by cody-lettau** [comment]
@mmanjaree-msft of course. Below you can find an image of the console logs and a link to the HAR file (pretty large).

![outlook issue](https://github.com/OfficeDev/office-js/assets/7740624/e0c633df-c3e2-4b24-8166-eba9edb2e40d)

[HAR File](https://drive.google.com/file/d/1rpiA3W-IegasN4YlHfW9GrWbkHNZspTK/view?usp=sharing)

**Comment by mmanjaree-msft** [comment]
Please share the har the way you did before. The new HAR File cannot be accessed without a sign in

**Comment by cody-lettau** [comment]
@mmanjaree-msft give it a try now - I updated the share permissions.

**Comment by mmanjaree-msft** [comment]
Thanks for sharing the logs. We are looking into the issue. Meanwhile, is your add-in having any event-based activation feature and is that working?

**Comment by cody-lettau** [comment]
Why is this auto closing when your team is looking into the issue? I am trying to get a user who can reproduce this to test the on-send activation still.

**Comment by cody-lettau** [comment]
So our "on-send" event activation is not being triggered either (note, we are not using smart alerts as of now).

**Comment by akagarwa-msft** [comment]
We are not able to repro the issue at our end. Can you please tell is the issue consistent? Also, can you please share a test account where the issue is reproable so that we can dig deep more on this.

**Comment by cody-lettau** [comment]
The issue is consistently reproducible for specific accounts. I can provide a test account. What email can I send that info to?

**Comment by akagarwa-msft** [comment]
We are looking into the issue from our end. Can you please validate the following:
1. Setting for the Customer:  Go to Settings > General > Privacy and data > Privacy settings. Check if "Optional Connected Experience" is turned ON for the user.
2. Is the customer enterprise or consumer?
3. Please follow the instructions here to capture logs from New Outlook.
[Collecting log files for Outlook Add-ins issues · OfficeDev/office-js Wiki (github.com)](https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues) . We are looking for one network call which is missing in the logs provided.

**Comment by cody-lettau** [comment]
Can we re-open this in the mean time? I'll work with my team to get answers to those questions.

**Comment by mobisw-msft** [comment]
Hey @cody-lettau ,

Have you collected the necessary logs?

**Comment by cody-lettau** [comment]
To answer the questions above:
1. ```Optional Connected Experience``` was disabled. Turning this on and restarting Outlook into the new Outlook UX did fix the issue.
2. Not 100% positive on the type of accounts -- likely Enterprise for sure, but unsure about Consumer
3. Did not collect because enabling Optional Connected Experiences fixed the issue.

Now the question would be why is this not enabled by default if it breaks add-ins from working int he new UI?

Is there any documentation for enabling this at an individual level, but ALSO at an entire organization level that we can provide our customers?

**Comment by shighosh-msft** [comment]
Hi @cody-lettau, thanks for confirming. Glad to know that the issue is fixed for you. The documentation related to this can be found here: https://learn.microsoft.com/en-us/deployoffice/privacy/optional-connected-experiences

The add-in related details are covered in this section:
![image](https://github.com/OfficeDev/office-js/assets/160569634/45df59a3-7a46-418b-8a98-ccd51e111c9c)

**Comment by piechoo** [comment]
Hello, I'm facing the same problem, even ms addins such as `share to teams` are not working - nothing happens after clicking addin. This problem occurs only on desktop Outlook New, in browser it works. The workaround to use addins is to toggle `Optional Connected Experience` - it is enabled in default in my case, however i have to toggle it to disabled and then to enabled to make addins work - and I have to do it after every restart of outlook.

**Comment by Mordvarg** [comment]
I have the exact same experience as @piechoo.

business client
Win10
everything updated.

**Comment by mmanjaree-msft** [comment]
@piechoo @Mordvarg Please open a new issue and share a repro video and a har file when you run into the issue
