### ISSUE TITLE
Microsoft Outlook v16.22.0.19021100 crashes on Outlook for Mac

### ISSUE THREAD

**Issue by neso613** [OfficeDev/office-js#443]
I'm developing Outlook Add-in. As per my requirement, I am opening an appointment with some text programmatically. Text can be added/removed on the click of some button. Text can be of different language like Chinese, German, Dutch, France, Spanish etc. When I open an appointment and add/remove text, outlook crashes again and again.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: ______ Mac
* Host [Excel, Word, PowerPoint, etc.]: ______ Outlook
* Office version number: ______ 16.22.0.19021100

## Useful logs
Microsoft Error Reporting log version: 2.0
Error Signature:
Exception: EXC_BAD_ACCESS
ExceptionEnumString: 1
Exception Code: KERN_NAME_EXISTS (0x0000700009a76d60)
Date/Time: 2019-03-23 16:00:41 +0000
Application Name: Microsoft Outlook
Application Bundle ID: com.microsoft.Outlook
Application Signature: OPIM
Application Bitness: x64
Application Version: 16.22.0.19021100
Crashed Module Name: OPF_Common.dylib
Crashed Module Version: 1.0.0.0
Crashed Module Offset: 0x0000000000005d45
Blame Module Name: OPF_Common.dylib
Blame Module Version: 1.0.0.0
UnsymbolicatedChecksum: BA89989B4B9BDA91C1195E7901B7757B
Blame Module Offset: 0x0000000000005d45
StackHash: abb54b1e505f6f15-dm_1_main
Application LCID: 1033
Extra app info: Reg=en Loc=0x0409
Build Type: Release
Crashed thread Stack Pointer: 0x_00007ffeeaf9aa98
Crashed thread: 0

Thread 0 crashed:
#  1  0x0000000106491d45 in  (OPF_Common.dylib + 0x0000000000005d45) 0x0000000000000000
#  2  0x00007fff7c502c8c in (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 0x000002D6 (libobjc.A.dylib + 0x000000000000ac8c) 0x0000000000000000
#  3  0x0000000104e355c7 in  (Microsoft Outlook + 0x00000000001d35c7) 0x00007ffeeaf9af10
#  4  0x0000000104d3199b in  (Microsoft Outlook + 0x00000000000cf99b) 0x00007ffeeaf9af90
#  5  0x0000000104d31a24 in  (Microsoft Outlook + 0x00000000000cfa24) 0x00007ffeeaf9afc0
#  6  0x00000001082a83d4 in  (mso99 + 0x0000000000a7e3d4) 0x00007ffeeaf9b000
#  7  0x00000001078eb426 in  (mso99 + 0x00000000000c1426) 0x00007ffeeaf9b020
#  8  0x000000010799537e in  (mso99 + 0x000000000016b37e) 0x00007ffeeaf9b060
#  9  0x000000010799512d in  (mso99 + 0x000000000016b12d) 0x00007ffeeaf9b0c0
# 10  0x000000010785a7ca in  (mso99 + 0x00000000000307ca) 0x00007ffeeaf9b100
# 11  0x000000010785a3fa in  (mso99 + 0x00000000000303fa) 0x00007ffeeaf9b170
# 12  0x00000001079935e9 in  (mso99 + 0x00000000001695e9) 0x00007ffeeaf9b1a0
# 13  0x0000000107993109 in  (mso99 + 0x0000000000169109) 0x00007ffeeaf9b200
# 14  0x0000000107992e97 in  (mso99 + 0x0000000000168e97) 0x00007ffeeaf9b2a0
# 15  0x0000000107992a17 in  (mso99 + 0x0000000000168a17) 0x00007ffeeaf9b2e0
# 16  0x0000000104dba961 in  (Microsoft Outlook + 0x0000000000158961) 0x00007ffeeaf9b390
# 17  0x00007fff5273b105 in ___NSFireDelayedPerform + 0x000001B1 (Foundation + 0x0000000000066105) 0x00007ffeeaf9b3c0
# 18  0x00007fff503aadfd in __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION_ + 0x00000014 (CoreFoundation + 0x000000000005adfd) 0x00007ffeeaf9b450
# 19  0x00007fff503aa9b0 in ___CFRunLoopDoTimer + 0x0000035B (CoreFoundation + 0x000000000005a9b0) 0x00007ffeeaf9b460
# 20  0x00007fff503aa4f0 in ___CFRunLoopDoTimers + 0x0000014D (CoreFoundation + 0x000000000005a4f0) 0x00007ffeeaf9c510
# 21  0x00007fff5038b737 in ___CFRunLoopRun + 0x00000880 (CoreFoundation + 0x000000000003b737) 0x00007ffeeaf9c570
# 22  0x00007fff5038ac64 in _CFRunLoopRunSpecific + 0x000001CF (CoreFoundation + 0x000000000003ac64) 0x00007ffeeaf9d260
# 23  0x00007fff4f621ab5 in _RunCurrentEventLoopInMode + 0x00000125 (HIToolbox + 0x000000000000aab5) 0x00007ffeeaf9d2f0
# 24  0x00007fff4f6217eb in _ReceiveNextEventCommon + 0x0000026A (HIToolbox + 0x000000000000a7eb) 0x00007ffeeaf9d340
# 25  0x00007fff4f621568 in __BlockUntilNextEventMatchingListInModeWithFilter + 0x00000040 (HIToolbox + 0x000000000000a568) 0x00007ffeeaf9d3c0
# 26  0x00007fff4d8dc363 in __DPSNextEvent + 0x000003E5 (AppKit + 0x000000000001b363) 0x00007ffeeaf9d3e0
# 27  0x00007fff4d8db102 in -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue + 0x00000552 (AppKit + 0x000000000001a102) 0x00007ffeeaf9d7f0
# 28  0x00007fff4d8d5165 in -[NSApplication run] + 0x000002BB (AppKit + 0x0000000000014165) 0x00007ffeeaf9da70
# 29  0x00007fff4d8c48a3 in _NSApplicationMain + 0x0000030C (AppKit + 0x00000000000038a3) 0x00007ffeeaf9db40
# 30  0x00007fff7d5dced9 in _start + 0x00000001 (libdyld.dylib + 0x0000000000016ed9) 0x00007ffeeaf9db90
x86_64 Thread State(64bit):
  _rax: 0x0000cfd75d82b870   _rbx: 0x000060000118a8e0   _rcx: 0x0100000000000000   _rdx:0x0040000000000000
  _rdi: 0x0000600001e8b870   _rsi: 0x00007fff4e4c788e   _rbp: 0x00007ffeeaf9aac0   _rsp:0x00007ffeeaf9aa98
  _r8: 0x00000000000000a9    _r9: 0x00000000000007fb    _r10: 0x000000010abd67c8   _r11:0x00007fe90ab11620
  _r12: 0xa3a3a3a3a3a3a3a3   _r13: 0x00007fe908805338   _r14: 0x00007fe908805338   _r15:0x00007fe908805000
  _rip: 0x0000000106491d45   _rflags: 0x0000000000010206   _cs: 0x000000000000002b   _fs:0x0000000000000000
  __gs: 0x0000000000000000  
Last C++ Exception for reference (may or may not be related to the root cause of the crashing thread):
#  1  0x0000000106569474 in  (mso20 + 0x0000000000022474) 0x0000000000000000
#  2  0x00000001066f22c3 in  (mso20 + 0x00000000001ab2c3) 0x0000000000000000
#  3  0x00000001066ccd06 in  (mso20 + 0x0000000000185d06) 0x0000000000000000
#  4  0x00000001066cca84 in  (mso20 + 0x0000000000185a84) 0x0000000000000000
#  5  0x00000001066c753a in  (mso20 + 0x000000000018053a) 0x0000000000000000
#  6  0x0000000106574803 in  (mso20 + 0x000000000002d803) 0x0000000000000000
#  7  0x00000001065747a6 in  (mso20 + 0x000000000002d7a6) 0x0000000000000000
#  8  0x000000010655b9d0 in  (mso20 + 0x00000000000149d0) 0x0000000000000000
#  9  0x0000000106552df4 in  (mso20 + 0x000000000000bdf4) 0x0000000000000000
# 10  0x00000001065497f2 in  (mso20 + 0x00000000000027f2) 0x0000000000000000
# 11  0x00000001069e3f7d in  (mso30 + 0x0000000000001f7d) 0x0000000000000000
# 12  0x00000001070c395d in  (mso40ui + 0x000000000000295d) 0x0000000000000000
# 13  0x000000010782c986 in  (mso99 + 0x0000000000002986) 0x0000000000000000
# 14  0x000000010782d946 in  (mso99 + 0x0000000000003946) 0x0000000000000000
# 15  0x000000010782d8c0 in  (mso99 + 0x00000000000038c0) 0x0000000000000000
# 16  0x000000010535e1fb in  (Microsoft Outlook + 0x00000000006fc1fb) 0x0000000000000000
# 17  0x0000000104c68040 in  (Microsoft Outlook + 0x0000000000006040) 0x0000000000000000
# 18  0x0000000104c67fd6 in  (Microsoft Outlook + 0x0000000000005fd6) 0x0000000000000000
# 19  0x0000000104c679d3 in  (Microsoft Outlook + 0x00000000000059d3) 0x0000000000000000
# 20  0x00007fff503ef632 in __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER_ + 0x0000000C (CoreFoundation + 0x000000000009f632) 0x0000000000000000
# 21  0x00007fff503ef5ac in ____CFXRegistrationPost_block_invoke + 0x0000003F (CoreFoundation + 0x000000000009f5ac) 0x0000000000000000
# 22  0x00007fff503ef4cd in __CFXRegistrationPost + 0x0000018E (CoreFoundation + 0x000000000009f4cd) 0x0000000000000000
# 23  0x00007fff503f7929 in ____CFXNotificationPost_block_invoke + 0x00000057 (CoreFoundation + 0x00000000000a7929) 0x0000000000000000
# 24  0x00007fff5035f0ca in -[_CFXNotificationRegistrar find:object:observer:enumerator + 0x00000661 (CoreFoundation + 0x000000000000f0ca) 0x0000000000000000
# 25  0x00007fff5035e48d in __CFXNotificationPost + 0x000002E6 (CoreFoundation + 0x000000000000e48d) 0x0000000000000000
# 26  0x00007fff526e6a7b in -[NSNotificationCenter postNotificationName:object:userInfo + 0x00000042 (Foundation + 0x0000000000011a7b) 0x0000000000000000
# 27  0x00007fff4d8d546d in -[NSApplication finishLaunching] + 0x00000154 (AppKit + 0x000000000001446d) 0x0000000000000000
# 28  0x000000010a632be0 in  (mbukernel + 0x000000000004bbe0) 0x0000000000000000
# 29  0x00007fff4d8d4fa7 in -[NSApplication run] + 0x000000FD (AppKit + 0x0000000000013fa7) 0x0000000000000000
# 30  0x00007fff4d8c48a3 in _NSApplicationMain + 0x0000030C (AppKit + 0x00000000000038a3) 0x0000000000000000

Thread 1:
#  1  0x00007fff7d71617a in _mach_msg_trap + 0x0000000A (libsystem_kernel.dylib + 0x000000000000117a) 0x0000000000000000
#  2  0x00007fff7d728745 in _task_suspend + 0x00000050 (libsystem_kernel.dylib + 0x0000000000013745) 0x0000000000000000
#  3  0x000000010a327494 in  (merp + 0x0000000000004494) 0x000070000ddec210
#  4  0x000000010a326cf6 in  (merp + 0x0000000000003cf6) 0x000070000ddece30
#  5  0x000000010a327e4c in  (merp + 0x0000000000004e4c) 0x000070000ddece50
#  6  0x00007fff7d7d0305 in __pthread_body + 0x0000007E (libsystem_pthread.dylib + 0x0000000000003305) 0x000070000ddecf10
#  7  0x00007fff7d7d326f in __pthread_start + 0x00000046 (libsystem_pthread.dylib + 0x000000000000626f) 0x000070000ddecf30
#  8  0x00007fff7d7cf415 in _thread_start + 0x0000000D (libsystem_pthread.dylib + 0x0000000000002415) 0x000070000ddecf50
x86_64 Thread State(64bit):
  _rax: 0x0000000000000000   _rbx: 0x0000000000000003   _rcx: 0x000070000ddec168   _rdx:0x0000000000000018
  _rdi: 0x000070000ddec1d8   _rsi: 0x0000000000000003   _rbp: 0x000070000ddec1c0   _rsp:0x000070000ddec168
  _r8: 0x0000000000039d0f    _r9: 0x0000000000000000    _r10: 0x000000000000002c   _r11:0x0000000000000206
  _r12: 0x0000000000000003   _r13: 0x000000000000002c   _r14: 0x000070000ddec1d8   _r15:0x0000000000000018
  _rip: 0x00007fff7d71617a   _rflags: 0x0000000000000206   _cs: 0x0000000000000007   _fs:0x0000000000000000
  __gs: 0x0000000000000000  
Thread 2:
#  1  0x00007fff7d7197de in ___psynch_cvwait + 0x0000000A (libsystem_kernel.dylib + 0x00000000000047de) 0x0000000000000000
#  2  0x000000010a62766c in  (mbukernel + 0x000000000004066c) 0x0000000000000000
#  3  0x000000010a627798 in  (mbukernel + 0x0000000000040798) 0x000070000e204b80
#  4  0x000000010a35def5 in  (WLMKernel + 0x000000000001aef5) 0x000070000e204bb0
#  5  0x000000010a353b54 in  (WLMKernel + 0x0000000000010b54) 0x000070000e204be0
#  6  0x000000010a35379d in  (WLMKernel + 0x000000000001079d) 0x000070000e204c70
#  7  0x000000010a353668 in  (WLMKernel + 0x0000000000010668) 0x000070000e204cc0
#  8  0x000000010a3618a7 in  (WLMKernel + 0x000000000001e8a7) 0x000070000e204d30
#  9  0x000000010662807a in  (mso20 + 0x00000000000e107a) 0x000070000e204d50
# 10  0x00000001065c5426 in  (mso20 + 0x000000000007e426) 0x000070000e204d80
# 11  0x00000001065c5044 in  (mso20 + 0x000000000007e044) 0x000070000e204da0
# 12  0x00000001065c4f6a in  (mso20 + 0x000000000007df6a) 0x000070000e204e20
# 13  0x000000010a359998 in  (WLMKernel + 0x0000000000016998) 0x000070000e204e40
# 14  0x00007fff7d58dd53 in __dispatch_call_block_and_release + 0x0000000C (libdispatch.dylib + 0x0000000000002d53) 0x000070000e204e70
# 15  0x00007fff7d58edcf in __dispatch_client_callout + 0x00000008 (libdispatch.dylib + 0x0000000000003dcf) 0x000070000e204e90
# 16  0x00007fff7d591240 in __dispatch_queue_override_invoke + 0x000002FF (libdispatch.dylib + 0x0000000000006240) 0x000070000e204eb0
# 17  0x00007fff7d59cd26 in __dispatch_root_queue_drain + 0x00000145 (libdispatch.dylib + 0x0000000000011d26) 0x000070000e204f10
# 18  0x00007fff7d59d4bd in __dispatch_worker_thread2 + 0x0000005A (libdispatch.dylib + 0x00000000000124bd) 0x000070000e204f80
# 19  0x00007fff7d7cf6dd in __pthread_wqthread + 0x0000026B (libsystem_pthread.dylib + 0x00000000000026dd) 0x000070000e204f90
# 20  0x00007fff7d7cf405 in _start_wqthread + 0x0000000D (libsystem_pthread.dylib + 0x0000000000002405) 0x000070000e204fd0
x86_64 Thread State(64bit):
  _rax: 0x0000000002000131   _rbx: 0x0000000000000002   _rcx: 0x000070000e204ac8   _rdx:0x0000000000000000
  _rdi: 0x00006000022ead10   _rsi: 0x0000000100000100   _rbp: 0x000070000e204b50   _rsp:0x000070000e204ac8
  _r8: 0x0000000000000000    _r9: 0x00000000000000a0    _r10: 0x0000000000000000   _r11:0x0000000000000202
  _r12: 0x00006000022ead10   _r13: 0x0000000000000016   _r14: 0x0000000100000100   _r15:0x000070000e205000
  _rip: 0x00007fff7d7197de   _rflags: 0x0000000000000202   _cs: 0x0000000000000007   _fs:0x0000000000000000
  __gs: 0x0000000000000000  
Thread 3:
#  1  0x00007fff7d7197de in ___psynch_cvwait + 0x0000000A (libsystem_kernel.dylib + 0x00000000000047de) 0x0000000000000000
#  2  0x000000010a6276b8 in  (mbukernel + 0x00000000000406b8) 0x0000000000000000
#  3  0x000000010a627798 in  (mbukernel + 0x0000000000040798) 0x000070000e287c80
#  4  0x000000010a35df16 in  (WLMKernel + 0x000000000001af16) 0x000070000e287cb0
#  5  0x000000010a353b40 in  (WLMKernel + 0x0000000000010b40) 0x000070000e287ce0
#  6  0x000000010a35379d in  (WLMKernel + 0x000000000001079d) 0x000070000e287d70
#  7  0x000000010a353668 in  (WLMKernel + 0x0000000000010668) 0x000070000e287dc0
#  8  0x000000010a3618a7 in  (WLMKernel + 0x000000000001e8a7) 0x000070000e287e30
#  9  0x00000001103c7aa3 in  (molc + 0x0000000000001aa3) 0x000070000e287e50
# 10  0x00000001103c785c in  (molc + 0x000000000000185c) 0x000070000e287e70
# 11  0x000000010a5e9bc2 in  (mbukernel + 0x0000000000002bc2) 0x000070000e287ee0
# 12  0x00007fff7d7d0305 in __pthread_body + 0x0000007E (libsystem_pthread.dylib + 0x0000000000003305) 0x000070000e287f10
# 13  0x00007fff7d7d326f in __pthread_start + 0x00000046 (libsystem_pthread.dylib + 0x000000000000626f) 0x000070000e287f30
# 14  0x00007fff7d7cf415 in _thread_start + 0x0000000D (libsystem_pthread.dylib + 0x0000000000002415) 0x000070000e287f50
x86_64 Thread State(64bit):
  _rax: 0x000000000000013c   _rbx: 0x0000000000000000   _rcx: 0x000070000e287bc8   _rdx:0x0000000000000000
  _rdi: 0x00006000022fc760   _rsi: 0x0000450100004600   _rbp: 0x000070000e287c50   _rsp:0x000070000e287bc8
  _r8: 0x0000000000000000    _r9: 0x00000000000000a0    _r10: 0x0000000000000000   _r11:0x0000000000000246
  _r12: 0x00006000022fc760   _r13: 0x0000000000000016   _r14: 0x0000450100004600   _r15:0x0000000000004600
  _rip: 0x00007fff7d7197de   _rflags: 0x0000000000000247   _cs: 0x0000000000000007   _fs:0x0000000000000000
  __gs: 0x0000000000000000  
Thread 4:
#  1  0x00007fff7d7197de in ___psynch_cvwait + 0x0000000A (libsystem_kernel.dylib + 0x00000000000047de) 0x0000000000000000
#  2  0x00007fff7acb1d01 in std::invalid_argument::~invalid_argument() + 0x00000031 (libc++.1.dylib + 0x0000000000007d01) 0x0000000000000000
#  3  0x0000000107f81804 in  (mso99 + 0x0000000000757804) 0x000070000e30ae40
#  4  0x000000010798c42e in  (mso99 + 0x000000000016242e) 0x000070000e30ae80
#  5  0x000000010a5e9bc2 in  (mbukernel + 0x0000000000002bc2) 0x000070000e30aee0
#  6  0x00007fff7d7d0305 in __pthread_body + 0x0000007E (libsystem_pthread.dylib + 0x0000000000003305) 0x000070000e30af10
#  7  0x00007fff7d7d326f in __pthread_start + 0x00000046 (libsystem_pthread.dylib + 0x000000000000626f) 0x000070000e30af30
#  8  0x00007fff7d7cf415 in _thread_start + 0x0000000D (libsystem_pthread.dylib + 0x0000000000002415) 0x000070000e30af50
x86_64 Thread State(64bit):
  _rax: 0x0000000002000131   _rbx: 0x0000000000000002   _rcx: 0x000070000e30ad98   _rdx:0x0000000000000000
  _rdi: 0x00000001090b2b08   _rsi: 0x0000000100000100   _rbp: 0x000070000e30ae20   _rsp:0x000070000e30ad98
  _r8: 0x0000000000000000    _r9: 0x00000000000000a0    _r10: 0x0000000000000000   _r11:0x0000000000000202
  _r12: 0x00000001090b2b08   _r13: 0x0000000000000016   _r14: 0x0000000100000100   _r15:0x000070000e30b000
  _rip: 0x00007fff7d7197de   _rflags: 0x0000000000000202   _cs: 0x0000000000000007   _fs:0x0000000000000000
  __gs: 0x0000000000000000  
Thread 5:
#  1  0x00007fff7d71617a in _mach_msg_trap + 0x0000000A (libsystem_kernel.dylib + 0x000000000000117a) 0x0000000000000000
#  2  0x00007fff5038bfde in ___CFRunLoopServiceMachPort + 0x00000151 (CoreFoundation + 0x000000000003bfde) 0x0000000000000000
#  3  0x00007fff5038b52d in ___CFRunLoopRun + 0x00000676 (CoreFoundation + 0x000000000003b52d) 0x000070000e38ce60
#  4  0x00007fff5038ac64 in _CFRunLoopRunSpecific + 0x000001CF (CoreFoundation + 0x000000000003ac64) 0x000070000e38db60
#  5  0x00007fff4f28bcc5 in -[__CoreSchedulingSetRunnable runForever] + 0x000000C3 (CFNetwork + 0x000000000004fcc5) 0x000070000e38dbf0
#  6  0x00007fff526e7104 in __NSThread__start_ + 0x000004C2 (Foundation + 0x0000000000012104) 0x000070000e38dca0
#  7  0x00007fff7d7d0305 in __pthread_body + 0x0000007E (libsystem_pthread.dylib + 0x0000000000003305) 0x000070000e38df10
#  8  0x00007fff7d7d326f in __pthread_start + 0x00000046 (libsystem_pthread.dylib + 0x000000000000626f) 0x000070000e38df30
#  9  0x00007fff7d7cf415 in _thread_start + 0x0000000D (libsystem_pthread.dylib + 0x0000000000002415) 0x000070000e38df50
x86_64 Thread State(64bit):
  _rax: 0x000000000100001f   _rbx: 0x0000000007000806   _rcx: 0x000070000e38cd88   _rdx:0x0000000000000000
  _rdi: 0x000070000e38cf30   _rsi: 0x0000000007000806   _rbp: 0x000070000e38cde0   _rsp:0x000070000e38cd88
  _r8: 0x000000000001390f    _r9: 0x00000000ffffffff    _r10: 0x0000000000000c00   _r11:0x0000000000000206
  _r12: 0x0000000007000806   _r13: 0x0000000000000c00   _r14: 0x000070000e38cf30   _r15:0x0000000000000000
  _rip: 0x00007fff7d71617a   _rflags: 0x0000000000000206   _cs: 0x0000000000000007   _fs:0x0000000000000000
  __gs: 0x0000000000000000  
Thread 6:
#  1  0x00007fff7d71d5aa in ___select + 0x0000000A (libsystem_kernel.dylib + 0x00000000000085aa) 0x0000000000000000
#  2  0x00007fff7d7d0305 in __pthread_body + 0x0000007E (libsystem_pthread.dylib + 0x0000000000003305) 0x0000000000000000
#  3  0x00007fff7d7d326f in __pthread_start + 0x00000046 (libsystem_pthread.dylib + 0x000000000000626f) 0x000070000e410f30
#  4  0x00007fff7d7cf415 in _thread_start + 0x0000000D (libsystem_pthread.dylib + 0x0000000000002415) 0x000070000e410f50
x86_64 Thread State(64bit):
  _rax: 0x000000000200005d   _rbx: 0x00007fffa8f00580   _rcx: 0x000070000e408b38   _rdx:0x00006000012d7410
  _rdi: 0x0000000000000080   _rsi: 0x00006000012d60d0   _rbp: 0x000070000e410f10   _rsp:0x000070000e408b38
  _r8: 0x0000000000000000    _r9: 0x0000000000000000    _r10: 0x0000000000000000   _r11:0x0000000000000246
  _r12: 0x000000000000000a   _r13: 0x00007fffa8dc5c30   _r14: 0x00006000012d60d0   _r15:0x0000000000000080
  _rip: 0x00007fff7d71d5aa   _rflags: 0x0000000000000246   _cs: 0x0000000000000007   _fs:0x0000000000000000
  __gs: 0x0000000000000000  
Thread 7:
#  1  0x00007fff7d71617a in _mach_msg_trap + 0x0000000A (libsystem_kernel.dylib + 0x000000000000117a) 0x0000000000000000
#  2  0x00007fff5038bfde in ___CFRunLoopServiceMachPort + 0x00000151 (CoreFoundation + 0x000000000003bfde) 0x0000000000000000
#  3  0x00007fff5038b52d in ___CFRunLoopRun + 0x00000676 (CoreFoundation + 0x000000000003b52d) 0x000070000dc62fa0
#  4  0x00007fff5038ac64 in _CFRunLoopRunSpecific + 0x000001CF (CoreFoundation + 0x000000000003ac64) 0x000070000dc63ca0
#  5  0x00007fff4d8e4f89 in __NSEventThread + 0x000000A0 (AppKit + 0x0000000000023f89) 0x000070000dc63d30
#  6  0x00007fff7d7d0305 in __pthread_body + 0x0000007E (libsystem_pthread.dylib + 0x0000000000003305) 0x000070000dc63f10
#  7  0x00007fff7d7d326f in __pthread_start + 0x00000046 (libsystem_pthread.dylib + 0x000000000000626f) 0x000070000dc63f30
#  8  0x00007fff7d7cf415 in _thread_start + 0x0000000D (libsystem_pthread.dylib + 0x0000000000002415) 0x000070000dc63f50
x86_64 Thread State(64bit):
  _rax: 0x0000000000000000   _rbx: 0x0000000007000806   _rcx: 0x000070000dc62ec8   _rdx:0x0000000000000000
  _rdi: 0x000070000dc63070   _rsi: 0x0000000007000806   _rbp: 0x000070000dc62f20   _rsp:0x000070000dc62ec8
  _r8: 0x0000000000001c23    _r9: 0x00000000ffffffff    _r10: 0x0000000000000c00   _r11:0x0000000000000206
  _r12: 0x0000000007000806   _r13: 0x0000000000000c00   _r14: 0x000070000dc63070   _r15:0x0000000000000000
  _rip: 0x00007fff7d71617a   _rflags: 0x0000000000000206   _cs: 0x0000000000000007   _fs:0x0000000000000000
  __gs: 0x0000000000000000  
Thread 8:
#  1  0x00007fff7d7197de in ___psynch_cvwait + 0x0000000A (libsystem_kernel.dylib + 0x00000000000047de) 0x0000000000000000
#  2  0x00007fff7acb1d01 in std::invalid_argument::~invalid_argument() + 0x00000031 (libc++.1.dylib + 0x0000000000007d01) 0x0000000000000000
#  3  0x000000010ee9aed2 in  (OutlookCore + 0x00000000002eaed2) 0x000070000e493260
#  4  0x000000010ee99fa5 in  (OutlookCore + 0x00000000002e9fa5) 0x000070000e4932a0
#  5  0x000000010ee9a1f3 in  (OutlookCore + 0x00000000002ea1f3) 0x000070000e4932f0
#  6  0x00000001054ebdb9 in  (Microsoft Outlook + 0x0000000000889db9) 0x000070000e493360
#  7  0x00000001054ed04b in  (Microsoft Outlook + 0x000000000088b04b) 0x000070000e493450
#  8  0x000000010ed479db in  (OutlookCore + 0x00000000001979db) 0x000070000e493820
#  9  0x000000010ed48382 in  (OutlookCore + 0x0000000000198382) 0x000070000e4938b0
# 10  0x000000010a359998 in  (WLMKernel + 0x0000000000016998) 0x000070000e4938e0
# 11  0x00007fff7d58dd53 in __dispatch_call_block_and_release + 0x0000000C (libdispatch.dylib + 0x0000000000002d53) 0x000070000e493910
# 12  0x00007fff7d58edcf in __dispatch_client_callout + 0x00000008 (libdispatch.dylib + 0x0000000000003dcf) 0x000070000e493930
# 13  0x00007fff7d595124 in __dispatch_lane_serial_drain + 0x0000026A (libdispatch.dylib + 0x000000000000a124) 0x000070000e493950
# 14  0x00007fff7d595bdc in __dispatch_lane_invoke + 0x00000184 (libdispatch.dylib + 0x000000000000abdc) 0x000070000e4939e0
# 15  0x00007fff7d59e090 in __dispatch_workloop_worker_thread + 0x0000025B (libdispatch.dylib + 0x0000000000013090) 0x000070000e493a50
# 16  0x00007fff7d7cf60b in __pthread_wqthread + 0x00000199 (libsystem_pthread.dylib + 0x000000000000260b) 0x000070000e493b00
# 17  0x00007fff7d7cf405 in _start_wqthread + 0x0000000D (libsystem_pthread.dylib + 0x0000000000002405) 0x000070000e493b40
x86_64 Thread State(64bit):
  _rax: 0x0000000002000131   _rbx: 0x0000000000000002   _rcx: 0x000070000e4931b8   _rdx:0x0000000000002d00
  _rdi: 0x00007fe90af68178   _rsi: 0x00002d0100002e00   _rbp: 0x000070000e493240   _rsp:0x000070000e4931b8
  _r8: 0x0000000000000000    _r9: 0x00000000000000a0    _r10: 0x0000000000000000   _r11:0x0000000000000202
  _r12: 0x00007fe90af68178   _r13: 0x0000000000000016   _r14: 0x00002d0100002e00   _r15:0x000070000e494000
  _rip: 0x00007fff7d7197de   _rflags: 0x0000000000000202   _cs: 0x0000000000000007   _fs:0x0000000000000000
  __gs: 0x0000000000000000  
Thread 9:
#  1  0x00007fff7d71617a in _mach_msg_trap + 0x0000000A (libsystem_kernel.dylib + 0x000000000000117a) 0x0000000000000000
#  2  0x000000010f8db21a in  (rpcrt4 + 0x000000000000421a) 0x0000000000000000
#  3  0x000000010f8db0a4 in  (rpcrt4 + 0x00000000000040a4) 0x000070000e7a5f00
#  4  0x00007fff7d7d0305 in __pthread_body + 0x0000007E (libsystem_pthread.dylib + 0x0000000000003305) 0x000070000e7a5f10
#  5  0x00007fff7d7d326f in __pthread_start + 0x00000046 (libsystem_pthread.dylib + 0x000000000000626f) 0x000070000e7a5f30
#  6  0x00007fff7d7cf415 in _thread_start + 0x0000000D (libsystem_pthread.dylib + 0x0000000000002415) 0x000070000e7a5f50
x86_64 Thread State(64bit):
  _rax: 0x000000000100001f   _rbx: 0x0000000000000006   _rcx: 0x000070000e7a5cd8   _rdx:0x0000000000000000
  _rdi: 0x000070000e7a5dc0   _rsi: 0x0000000000000006   _rbp: 0x000070000e7a5d30   _rsp:0x000070000e7a5cd8
  _r8: 0x000000000001572b    _r9: 0x0000000000000000    _r10: 0x0000000000000108   _r11:0x0000000000000206
  _r12: 0x0000000000000006   _r13: 0x0000000000000108   _r14: 0x000070000e7a5dc0   _r15:0x0000000000000000
  _rip: 0x00007fff7d71617a   _rflags: 0x0000000000000206   _cs: 0x0000000000000007   _fs:0x0000000000000000
  __gs: 0x0000000000000000  
Thread 10:
#  1  0x00007fff7d7197de in ___psynch_cvwait + 0x0000000A (libsystem_kernel.dylib + 0x00000000000047de) 0x0000000000000000
#  2  0x000000010a62766c in  (mbukernel + 0x000000000004066c) 0x0000000000000000
#  3  0x000000010a627798 in  (mbukernel + 0x0000000000040798) 0x000070000e8aba30
#  4  0x000000010a35def5 in  (WLMKernel + 0x000000000001aef5) 0x000070000e8aba60
#  5  0x000000010a353b54 in  (WLMKernel + 0x0000000000010b54) 0x000070000e8aba90
#  6  0x000000010a35379d in  (WLMKernel + 0x000000000001079d) 0x000070000e8abb20
#  7  0x000000010a353668 in  (WLMKernel + 0x0000000000010668) 0x000070000e8abb70
#  8  0x000000010a82ba11 in  (osf + 0x000000000019da11) 0x000070000e8abbe0
#  9  0x000000010a875a82 in  (osf + 0x00000000001e7a82) 0x000070000e8abc30
# 10  0x00000001065c5426 in  (mso20 + 0x000000000007e426) 0x000070000e8abc50
# 11  0x00000001065c5044 in  (mso20 + 0x000000000007e044) 0x000070000e8abc70
# 12  0x00000001065d7880 in  (mso20 + 0x0000000000090880) 0x000070000e8abcf0
# 13  0x0000000106628068 in  (mso20 + 0x00000000000e1068) 0x000070000e8abd50
# 14  0x00000001065c5426 in  (mso20 + 0x000000000007e426) 0x000070000e8abd80
# 15  0x00000001065c5044 in  (mso20 + 0x000000000007e044) 0x000070000e8abda0
# 16  0x00000001065c4f6a in  (mso20 + 0x000000000007df6a) 0x000070000e8abe20
# 17  0x000000010a359998 in  (WLMKernel + 0x0000000000016998) 0x000070000e8abe40
# 18  0x00007fff7d58dd53 in __dispatch_call_block_and_release + 0x0000000C (libdispatch.dylib + 0x0000000000002d53) 0x000070000e8abe70
# 19  0x00007fff7d58edcf in __dispatch_client_callout + 0x00000008 (libdispatch.dylib + 0x0000000000003dcf) 0x000070000e8abe90
# 20  0x00007fff7d591240 in __dispatch_queue_override_invoke + 0x000002FF (libdispatch.dylib + 0x0000000000006240) 0x000070000e8abeb0
# 21  0x00007f

**Comment by macOutlookExtensibility** [comment]
We are not able to reproduce this in the 16.22 (190211) build. How are you adding / removing text to the email body? Are you using the body.setAsync API?

**Comment by neso613** [comment]
> We are not able to reproduce this in the 16.22 (190211) build. How are you adding / removing text to the email body? Are you using the body.setAsync API?

Yes.

**Comment by macOutlookExtensibility** [comment]
Can you confirm that these are the steps to reproduce the issue?

1. Open a new appointment / meeting
2. Open an add-in and call setBody on it

and Outlook crashes? Is it consistent?

**Comment by neso613** [comment]
> Can you confirm that these are the steps to reproduce the issue?
> 
> 1. Open a new appointment / meeting
> 2. Open an add-in and call setBody on it
> 
> and Outlook crashes? Is it consistent?

Hi @macOutlookExtensibility 
Sorry  for late responding.


I was populating subject, location and body using setSubject, setLocation and setBody.

I have used this code to open appointment programtically
`location=setLoaction()
subject=setSubject()
bodyContent=setBody()
Office.context.mailbox.displayNewAppointmentForm(
      {
        start: UTCCorrectStartDate,
        end: UTCCorrectEndDate,
        location: location,
        subject: subject,
        body: bodyContent
      });`

**Comment by dmahugh** [comment]
Closed due to no response.
