### ISSUE TITLE
Not able to control New Outlook updates.

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4433]
Description -
New Outlook is getting updated on random periodic intervals. We need to have control to enable/disable the updates as that of Classic Outlook.

Steps to Reproduce -

1. Open New Outlook.
2. Check for New Outlook version.

Expected Result -

1. New Outlook updates should be controllable.

Actual Result -

1. New Outlook is getting updated on random periodic intervals

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.501.300 (Production) | Client Version 20240419007.29 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by DivyaPatidar** [comment]
This forum is limited to supporting office-js apis. For any New Outlook specific issues, please feel free to send the feedback from New Outlook directly using the Help ->Feedback option.
