### ISSUE TITLE
Not able to disable/reset suggested contacts.

### ISSUE THREAD

**Issue by sagar-sonawane9** [OfficeDev/office-js#4434]
Description -
Not able to disable/reset suggested contacts.

Steps to Reproduce -

1. Open New Outlook.
2. Configure a new mail and type recipient name.
3. Requirement is not to have suggestion after typing recipient name.

We tried the steps mentioned at "Turn off or reset your suggested contacts" but expected suggestions are not present. 
- https://support.microsoft.com/en-us/office/manage-suggested-recipients-in-the-to-cc-and-bcc-fields-in-outlook-dbe46e31-c098-4881-8cf7-66b037bce23e

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.501.300 (Production) | Client Version 20240419007.29 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by DivyaPatidar** [comment]
This forum is limited to supporting office-js apis. For any New Outlook specific issues, please feel free to send the feedback from New Outlook directly using the Help ->Feedback option.
