### ISSUE TITLE
Not contain Windows NT 10.0 in osList in function "shouldUseLocalStorageToPassMessage" so cannot execute Office.context.ui.messageParent

### ISSUE THREAD

**Issue by hirossyi73** [OfficeDev/office-js#444]
## Expected Behavior
We can close dialog using function "Office.context.ui.displayDialogAsync" and "Office.context.ui.messageParent" with IE11 and Windows10.

## Current Behavior
We cannot close dialog.
Because not contain "Windows NT 10.0" in function "shouldUseLocalStorageToPassMessage".

~~~
// ex. word-web-16.00.debug.js
function shouldUseLocalStorageToPassMessage() {
			try {
                                // Not contains "Windows NT 10.0"
				var osList=[
					"Windows NT 6.1",
                                       "Windows NT 6.2",
                                       "Windows NT 6.3"
				];
				var userAgent=window.navigator.userAgent;
				for (var i=0, len=osList.length; i < len; i++) {
					if (userAgent.indexOf(osList[i]) > -1) {
						return isInternetExplorer();
					}
				}
				return false;
			}
			catch (e) {
				logExceptionToBrowserConsole("Error happens in shouldUseLocalStorageToPassMessage.", e);
				return false;
			}
		}
~~~

Windows10 is "Windows NT 10.0", so this function is false.
And if "shouldUseLocalStorageToPassMessage" is false, function "messageParent" calls "window.opener.postMessage".
But IE11 is not supported postMessage in iframe, so I think we have to add "Windows NT 10.0" in osList.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: All
* Office version number: Newer Office Online
* Operating System: Only Windows10
* Browser (if using Office Online): Internet Explorer11

**Comment by danielgwilson** [comment]
Hi, we're looking into this—thanks for posting.

**Comment by lliu113** [comment]
@hirossyi73  - I'm closing this issue as it's historic, please reactivate if you are still seeing this. Thanks!
