### ISSUE TITLE
Formatting getting disturb while opening file using base64(Alignment,Font Colour,FontSize etc.)

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#4441]
My Environment
Platform : PC desktop
Host: Power Point
Office version number: Microsoft® PowerPoint® for Microsoft 365 MSO (Version 2404 Build 16.0.17531.20140) 64-bit
Operating System: Windows 11 pro

Hi Team,
Here is my code snippet which is I used to open PPT using base64.
 ```
 async function loadslide(mybase64) {
      try {
          await PowerPoint.run(async (context) => {
              context.presentation.load("slides");
              await context.sync();
              const slides = context.presentation.slides;
              const slideCount = slides.getCount();
              slides.load("items");
              await context.sync();
              slides.items.map((slide) => {
                  slide.delete();
              });
              await context.sync();
              context.presentation.insertSlidesFromBase64(mybase64);
              await context.sync();
              Loader("hide", translate('Addin_J_302'), "S");
 
          });
      } catch (e) {
          console.log("e", e);
      }
  }
```
After Opening my PPT file using code its alignment getting disturb I'm attaching file here for reference. 

[SamplePPT.zip](https://github.com/OfficeDev/office-js/files/15294585/SamplePPT.zip)

**Comment by Rick-Kirkham** [comment]
@Jayshiv1408Dev Please add details about what you mean when you say that the formatting is disturbed. It is a security risk to open a zip file, so I'm reluctant to do that. Could you add a screen shot of the disturbed formatting?

**Comment by Jayshiv-IRIS** [comment]
**Expected Output PPT1**
<img width="944" alt="ExpectedOP PPT1" src="https://github.com/OfficeDev/office-js/assets/133626379/e2cf5172-64fe-4379-85e6-aa8d50ddb704">
**Error output PPT1**
<img width="941" alt="ErrorFile PPT1" src="https://github.com/OfficeDev/office-js/assets/133626379/aca53707-27ae-47c9-a4a4-dcd713ac9d63">

**Expected output PPT2**
 
<img width="976" alt="ExpectedOP PPT2" src="https://github.com/OfficeDev/office-js/assets/133626379/42575bd4-3ebc-4f13-9b2d-e0f4ac177985">

**Error Output PPT2** 
<img width="705" alt="ErrorFilePPT2" src="https://github.com/OfficeDev/office-js/assets/133626379/85c4a0bf-cd27-4c0e-b68e-f99cb6093f61">

Expected output PPT3
<img width="917" alt="ExpectedOP PPT3" src="https://github.com/OfficeDev/office-js/assets/133626379/923b1d98-defa-459a-a4df-394a35534cb2">

Error output PPT3
<img width="812" alt="ErrorFile PPT3" src="https://github.com/OfficeDev/office-js/assets/133626379/a3f931bd-52d2-4397-bef0-ed745e228589">

Here Formatting means Font style ,alignment font color and size is getting distrub.

**Here is my source File For reference**
[PPT2.pptx](https://github.com/OfficeDev/office-js/files/15302990/PPT2.pptx)
[PPT3.pptx](https://github.com/OfficeDev/office-js/files/15302996/PPT3.pptx)
[PPT1.pptx](https://github.com/OfficeDev/office-js/files/15302988/PPT1.pptx)

**Comment by EsterBergen** [comment]
@Jayshiv1408Dev - Can you confirm how you're getting the original slides as base64? I think that may be the issue vs. the inserting part.

We recently released an api into preview that exports the slide as Base64. Can you try using that one to generate the Base 64 string?

https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.slide?view=powerpoint-js-preview#powerpoint-powerpoint-slide-exportasbase64-member(1)

**Comment by Jayshiv-IRIS** [comment]
@EsterBergen  
When I open this original files normally in powerpoint it's look perfectly but when I open using base64 it's causing issue.
As per your guidance I have to exported its by using exportAsBase64() method and use that bytes to load slides?
Am I correct?

**Comment by Jayshiv-IRIS** [comment]
can you please provide CDN for preview. I use beta version CDN but its throw exception at exportAsBase64().
May be I'm doing something wrong.
Can you please provide some demo for this.

**Comment by EsterBergen** [comment]
hi @Jayshiv1408Dev - As it's a preview API you'll need to refer to the Beta reference https://appsforoffice.microsoft.com/lib/beta/hosted/office.js

Try that and let us know if you still have an error.

Before using the preview API for exportAsBase64(), how were you converting your slides to base64?

**Comment by Jayshiv-IRIS** [comment]
Using C# File.ReadAllBytes("mypath"); I'm taking bytes from path and after that I'm using this code to convert byte into base64.
here my api response will pass in  GetPPTDataSuccess(res)
```
function GetPPTDataSuccess(res) {
    var Data = "";
    if (res) {
        Data = res[0];
         if (Data != null) {
            var bcontent = base64ToArrayBuffer(Data);
            var blob = new Blob([bcontent], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' });
            var file = new File([blob], 'test', { type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document" });
            var fr = new FileReader();
            fr.onload = ReplaceWordDocument;
            fr.readAsDataURL(file);
            ReplaceWordDocument(Data);
        } 
    }
}
  

async function ReplaceWordDocument(data) {
        if (this && this.result) {
            var startIndex = -1;
            var mybase64 = "";
                data = this.result;
                startIndex = data.indexOf("base64,");
                mybase64 = data.substr(startIndex + 7, data.length);
            if (officeview == "PowerPoint") {
                await loadslide(mybase64);
            }
           
        }
    }

async function loadslide(mybase64) {
     try {
         await PowerPoint.run(async (context) => {
             context.presentation.load("slides");
             await context.sync();
             const slides = context.presentation.slides;
             const slideCount = slides.getCount();
             slides.load("items");
             await context.sync();
             slides.items.map((slide) => {
                 slide.delete();
             });
             await context.sync();
             context.presentation.insertSlidesFromBase64(mybase64);
             await context.sync();
             Loader("hide", translate('Addin_J_302'), "S");

         });
     } catch (e) {
         console.log("e", e);
     }
 }

```

**Comment by Jayshiv-IRIS** [comment]
Is there any updates on this?

**Comment by EsterBergen** [comment]
> adAllBytes("mypath"); I'm taking bytes from path and after that I'm using this code to convert byte into base64.
> here my api response will pass in GetPPTDataSuccess(res)

Hi @Jayshiv1408Dev -were you able to try the preview API to see if the base64 generated provides the expected content?

**Comment by EsterBergen** [comment]
@Jayshiv1408Dev - Checking in on this. Please try the preview API. I suspect your method of exporting to Base64 does not have the correct formatting.

**Comment by pratikdevdas** [comment]
Whats the update on the issue?
