### ISSUE TITLE
Send Event on Mobile outlook web addin missing

### ISSUE THREAD

**Issue by Roshninair4** [OfficeDev/office-js#4442]
All external emails leaving the organization needs to go through custom office add-in on send event to monitor, encrypt, review and provide custom features to users. Not having a send event for mobile nullifies all of this.Can we please have send event on mobile enabled this year?

**Comment by mmanjaree-msft** [comment]
Thank you for the input. This will be considered as a new feature request. 

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.
