### ISSUE TITLE
Enable Send Events and Ribbon Controlsfor Mobile Outlook Client

### ISSUE THREAD

**Issue by Roshninair4** [OfficeDev/office-js#4443]
All external emails leaving the organization will have to have a custom office add-in on send event to monitor, encrypt, review and provide custom features to users as well. Not having a send event for mobile nullifies all of this.
More and more users are moving to mobile outlook and the ease for them to set up zoom meetings and custom smart meetings require ribbon controls to be enabled for the user

**Comment by mmanjaree-msft** [comment]
Thank you for the input. This will be considered as a new feature request. 

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.
