### ISSUE TITLE
Support for Onload event on outlook start on platforms(web/desktop/mac/mobile)

### ISSUE THREAD

**Issue by Roshninair4** [OfficeDev/office-js#4444]
On load events for office web add-ins are a must have when it comes to features like tagging emails which are external, custom sorting emails during load time and several other checks which happens during outlook load whcich can be discussed in detail once this use case is picked up by Microsoft dev.

**Comment by mmanjaree-msft** [comment]
Thank you for the input. This will be considered as a new feature request. 

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.

**Comment by Roshninair4** [comment]
I have added that to the feature request as well.

**Comment by mmanjaree-msft** [comment]
@Roshninair4 Thanks for the request submission. Your input would be considered during the planning process. Please close the issue as there is no action item on this.
