### ISSUE TITLE
JS add-in ribbon icons are rendering the default image on the classic Outlook for Windows

### ISSUE THREAD

**Issue by bchen-hs-eng** [OfficeDev/office-js#4446]
# Provide required information needed to triage your issue
On the classic Outlook for Windows, JS based add-in entries on the ribbon are showing the default images.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2404 (Build 17531.20140 Click-to-Run)
* Operating System: Windows 11
* Browser (if using Office on the web): ______
 
## Expected behavior
Add-ins icons are rendered based on manifest urls

## Current behavior
Add-in icons are rendering the default image

## Steps to reproduce
No special steps required

## Link to live example(s)
![Screenshot 2024-05-13 at 8 55 37 PM](https://github.com/OfficeDev/office-js/assets/168113738/37fa7281-e9a1-4e68-a2cf-c22d36df76dd)
![Screenshot 2024-05-13 at 8 54 12 PM](https://github.com/OfficeDev/office-js/assets/168113738/57e60326-6677-429b-be10-34491e742caa)

# Provide additional details
- This issue affects default Microsoft authored add-ins as well.

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Adrian-MSFT** [comment]
Hi @bchen-hs-eng. I'm unable to repro this. Does this also happen after clearing the WEF cache?
https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#manually

**Comment by bchen-hs-eng** [comment]
Hi @Adrian-MSFT Thanks for taking a look at this issue. Clearing the cache restored some of the add-in icons but not all. 

We have end users of our add-in reporting this as well, and this occurred after we updated our add-in icons in the manifest. Since this did not happen to all our users, we can assume the icon asset urls are correctly set in the manifest.

Is there a way to clear asset cache automatically when the add-in manifest is updated?

**Comment by jrgilman** [comment]
@Adrian-MSFT we are having a similar issue with our manifest and are unsure what to do - it's preventing us from submitting to Microsoft for the add-in store. The issue is in some places it shows the icon, and in others it doesn't even try on desktop:

![Screenshot 2024-09-10 115205](https://github.com/user-attachments/assets/bbc85492-7e89-472b-b087-8f85fceba6d6)

If I manually upload the add-in for use in Excel Online, it does work during testing:

![image](https://github.com/user-attachments/assets/c9643a8b-dd1b-4883-b0ef-8df404401977)

**Comment by Adrian-MSFT** [comment]
@bchen-hs-eng 
Thanks for reporting this issue regarding the default icon showing. It is on our backlog. We unfortunately have no timelines to share at this point 

Internal tracking id: Office: 9340791

**Comment by Adrian-MSFT** [comment]
@jrgilman 
Can you confirm that the icons in the manifest are supported file formats? https://learn.microsoft.com/en-us/javascript/api/manifest/image?view=common-js-preview

If they are supported extensions, it will be triaged under the same backlog item mentioned above.
