### ISSUE TITLE
How to manually delete the cache when using the “New Outlook"

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#4447]
## I don't know how to manually delete the cache when using the “New Outlook”.
Please let us know if the procedure is on the official documentation.
Is the method the same as the current Outlook?

**Comment by mmanjaree-msft** [comment]
This forum is limited to office-js related queries. For Exchange specific queries and support please post your questions here - https://learn.microsoft.com/en-us/answers/tags/342/office-exchange-server-management . 
You can also explore the options at https://support.microsoft.com/home/contact

**Comment by samantharamon** [comment]
Hi @mailchecktool-admin,

Before you post this question to another forum, are you looking to clear the Outlook cache to remove a sideloaded add-in by any chance? If so, the following articles may assist you further:

- [Sideload Outlook add-ins for testing](https://learn.microsoft.com/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing#remove-a-sideloaded-add-in)
- [Clear the Office cache](https://learn.microsoft.com/office/dev/add-ins/testing/clear-cache)

**Comment by mailchecktool-admin** [comment]
@samantharamon 
Thank you for your response.

However, there is an issue with the cache clearance method you provided. The add-in developed by our company is installed and used in customers' tenants through the Microsoft 365 admin center.

According to your suggested procedure, we would have to repeatedly remove and redeploy the add-in in the customer's environment with each deployment, which would negatively impact the customer.

Our goal is to find a recovery method that ensures the latest index.html is loaded.
Is there a way to clear the old cache data without removing and redeploying the add-in?

Additionally, I have another question. My add-in temporarily stores product policy information in local storage,
which is reused during various operations. for example) localStorage.setItem(); localStorage.getItem();
Since this local storage data might be related to the issues we're encountering, we would like to clear it.

In the case of Outlook for Windows, where is the local storage data saved within the Windows OS?

**Comment by mailchecktool-admin** [comment]
@samantharamon @exextoc 
It's been a while since my last post.
Could you please update me on the status of this ticket?
As this issue is affecting my client, I would appreciate your cooperation in resolving it.

**Comment by akagarwa-msft** [comment]
Cache in New Outlook can be cleared by: 

1. Close New Outlook and run the following command in terminal: olk.exe -devtools . This will open DevTools along with the Outlook App.
2. Manually clear the cache as mentioned here https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/reference#manually-clear-the-browser-cache
