### ISSUE TITLE
Status Update Request: Integration of 'OverriddenByRibbonApi' Feature in Outlook Add-ins

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js#4448]
Hi there,

I was wondering if there's any update on the integration of the "OverriddenByRibbonApi" feature in Outlook add-ins

**Comment by mmanjaree-msft** [comment]
Currently this is not part of Outlook addins but you can submit a new feature request. 

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.

**Comment by CodeCube0** [comment]
Got it, here's a more direct answer:

Thank you for the tip! I will go and put my request on the "Tech Community Page".

I would like to know if there is a dedicated page to check the progress of OfficeJS implementations. I would like to stay updated on this aspect.

Thanks again for the help! @mmanjaree-msft

**Comment by mmanjaree-msft** [comment]
A roadmap can be shared for any feature but that happens only after the feature goes through the planning process. you can ask for updates on this or check the latest documentations for any addition
