### ISSUE TITLE
NAA: Unable to initialize MSAL on Outlook for Windows in an Event handler

### ISSUE THREAD

**Issue by htryggva** [OfficeDev/office-js#4450]
An exception is thrown when initializing the MSAL library:
```
[BrowserAuthError: crypto_nonexistent: The crypto object or function is not available.]
  errorCode: 'crypto_nonexistent',
  errorMessage: 'The crypto object or function is not available.',
  subError: '',
  name: 'BrowserAuthError'
```

## Your Environment

* Platform: PC desktop
* Host: Outlook
* Office version number: Beta Channel Version 2406 Build 17630
* Operating System: Windows
 
## Expected behavior
The initialization and authenticating using NAA should be successful when running in an Event-based Activation scenario.

## Current behavior
An exception occurs.

## Steps to reproduce

1. Create an Outlook app with an LaunchEvent handler registered with the OnNewMessageCompose event.
2. Initialize NAA according to the documentation: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/enable-nested-app-authentication-in-your-add-in#initialize-the-public-client-application
3. Wrap the code in try/catch and log any errors
4. Run Outlook and create a new email
5. Use Runtime Logging to observe the exception:

```
[BrowserAuthError: crypto_nonexistent: The crypto object or function is not available.]
  errorCode: 'crypto_nonexistent',
  errorMessage: 'The crypto object or function is not available.',
  subError: '',
  name: 'BrowserAuthError'
```

## Context
We want to move our add-in over to the new auth model.

## Useful logs
`window.nestedAppAuthBridge` is undefined in this context. It is defined when running our add-in in the Taskpane.

**Comment by timwan10** [comment]
Support for NAA in Event Based Add-ins is not enabled yet. This feature is coming, but there is not a timeline to share right now. 

Internal Ref #: 8774618

**Comment by timwan10** [comment]
Assigning to mattgeim for documentation once this is enabled.

**Comment by manuelsidler** [comment]
@timwan10 @mattgeim  Will it be available when legacy Exchange callback tokens will be turned off in October 2024? Our event-based add-in is using the Outlook REST API.

**Comment by manuelsidler** [comment]
Screenshot from the last community call regarding NAA and event-based add-ins:
<img width="1280" alt="image" src="https://github.com/OfficeDev/office-js/assets/802015/ccc87a4a-ca74-467e-b2d5-1b337b19f057">

**Comment by fedeisas** [comment]
> Support for NAA in Event Based Add-ins is not enabled yet. This feature is coming, but there is not a timeline to share right now.
> 
> Internal Ref #: 8774618

@timwan10 do we have a timeline yet? Thanks!

**Comment by mattgeim** [comment]
@fedeisas  - event based add-ins should be testable in preview in the Beta channel now.

**Comment by cody-lettau** [comment]
How can we be getting this close to a deprecation of Exchange Web Service token usage and all of this is not yet available in GA for us to be developing and testing against on all platforms?

**Comment by glr0221** [comment]
@mattgeim I would just like to confirm that NAA-SSO is now usable in Event-based addins? How about NAA-SSO on spam addins? Thanks.

**Comment by manuelsidler** [comment]
@glr0221 I tried event-based addins with NAA on Windows and Mac, but I still have some issues. Maybe it's interesting for you as well #4764

**Comment by glr0221** [comment]
Thanks @manuelsidler . Tracking that ticket as well. Thanks again.
