### ISSUE TITLE
Office JS API for getting tenant id in case of managing sensitivity labels

### ISSUE THREAD

**Issue by pza-dev-brcm** [OfficeDev/office-js#4453]
We are working on outlook add-in where we are dealing with sensitivity labels.
We are able to fetch the GUID of the label applied to email also able to set the required label.

for business purpose we want to get the tenant id against which the labels are applied.

Do we have any Office JS API for fulfilling this requirement ?

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by mmanjaree-msft** [comment]
Thank you for the input. This will be considered as a new feature request. 

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.
