### ISSUE TITLE
Signature bookmark is lost in Outlook Desktop when new message is opened after recall

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js#4457]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2402 Build 16.0.17328.20282
* Operating System: Windows

## Expected behavior
When the new email window is opened, if a signature is already inserted, correctly detect it and have the setSignatureAsync API replace it.

## Current behavior

When the new window after a recall is opened, the already inserted signature through setSignatureAsync is ignored and a second signature is inserted when using again the setSignatureAsync.

## Steps to reproduce

1. Send an email containing an email signature and recall it in Outlook desktop
2. Choose the "Delete unread copies and replace with a new message" option. This will trigger the window to open with the editable recalled email.
3. Use any way (events, manual from taskpane) to insert again the signature. Instead of replacing it, it will add a new one.

# Provide additional details

This seems to happen in Outlook Desktop regardless of the method the signature was inserted. Probably the signature bookmark is lost, as properties are removed when sending the email. The issue can be reproduced also by using the native signature insertion. 
I know it is not only related to web add-ins, but they are affected by this Outlook bug and customers put the blame on the web add-ins. It would be great at least to receive information regarding the acknowledgement of the bug.

**Comment by mmanjaree-msft** [comment]
Is the issue happening with new Outlook and owa or classic outlook?

**Comment by bogdanst24** [comment]
Only classic Outlook. There is no such option on the recall on new Outlook/owa

**Comment by ztcdsb** [comment]
Thanks for reporting this issue regarding signature bookmark. It has been put on our backlog. We unfortunately have no timelines to share at this point 

Internal tracking id: Office: 9055165
