### ISSUE TITLE
How to do automated testing on an Office add-in

### ISSUE THREAD

**Issue by donpinkus** [OfficeDev/office-js#446]
Apologies for posting a `how-to` question to the repo. There's been a [StackOverflow question](https://stackoverflow.com/questions/40700540/automated-end-to-end-testing-for-office-add-in) open for this since 2016 without an answer.

## How do you do automated testing on an office add-in? 

For example, if you've built a plugin for Microsoft Word, how do you run tests that interact with Word's API? 

It's easy to mock responses from Word's API, and write unit tests for the rest of your code - but as soon as you need to mimic real usage we don't know how to test. (ie. someone interacting with the Word document, which will trigger a Word API event, that your code then deals with) 

I'm assuming we're not the only add-in that wants to do end-to-end testing / integration testing with the actual Microsoft product :P

**Comment by phlppnhllngr** [comment]
https://github.com/phlppnhllngr/office-addin-integration-testing

**Comment by dmahugh** [comment]
FYI, we're planning to build out some more detailed content around testing scenarios, as mentioned here: [https://github.com/OfficeDev/office-js-docs-pr/issues/584](https://github.com/OfficeDev/office-js-docs-pr/issues/584)
