### ISSUE TITLE
Add-in debugging is no longer available on the New Outlook for Windows

### ISSUE THREAD

**Issue by bchen-hs-eng** [OfficeDev/office-js#4464]
We are following [these steps](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/one-outlook#debug-your-add-in) to debug our add-in on the New Outlook for Windows but these is no longer a right-click context menu from the taskpane to invoke the inspector/debugger.

Is this related to the [on going taskpane rendering issue](https://github.com/OfficeDev/office-js/issues/4440)?

Thanks.

**Comment by mmanjaree-msft** [comment]
Is olk.exe --devtools not working for you?

**Comment by bchen-hs-eng** [comment]
The `olk.exe --devtools` appears to be working now.
