### ISSUE TITLE
How to get all the logs in the Outlook desktop??

### ISSUE THREAD

**Issue by Robirob20** [OfficeDev/office-js#4468]
I want to debug my add-in in Outlook desktop but i don´t know how to get all the errors and the logs.

**Comment by mmanjaree-msft** [comment]
Please refer to this https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues#outlook-mac

**Comment by Robirob20** [comment]
I don´t know if i am doing something wrong but it doesn´t work and i need to see why my launchEvent doesn´t work in the Outlook old version when i am doing OnNewMessageCompose

**Comment by mmanjaree-msft** [comment]
@Robirob20 Please refer to this doc for debugging you addin https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/one-outlook#debug-your-add-in if its new outlook desktop. For launchEvent issue, the followup will be on https://github.com/OfficeDev/office-js/issues/4469

**Comment by Robirob20** [comment]
The issue #4469 it´s mine and it´s for the old version of Outlook, i see that there are a lot of people with the same problem and i follow the same instructions that they follow to solve the problem but in my case I can´t solve it. So it would be helpfull to have the log to see what´s going on.

**Comment by anjalitp** [comment]
Please find the steps for debugging and troubleshooting event based activations on Outlook Desktop here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/troubleshoot-event-based-and-spam-reporting-add-ins
