### ISSUE TITLE
OnMessageRecipientsChanged is fired when previewing draft mails

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#4472]
# Provide required information needed to triage your issue
When I save an email and preview it in the draft mode the "OnMessageRecipientsChanged" is fired along with "OnMessageCompose"

## Your Environment
* Platform: PC
* Host : Outlook
* Office version number: 16.0.17531.20140
* Operating System: Windows 11
 
## Expected behavior
OnMessageRecipientsChanged should not be fired when previewing draft mails.

## Steps to reproduce
1. Create a new mail and save it so that it is stored in the drafts
2. Go to the draft folder and preview the draft in read mode
3. Observe in the logs that the event is fired

## Context
We are listening to this event to render a signature based on the recipients. We have unnecessary renderings.

## Useful logs
17.05.2024 16:12:11	Verbose	Runtime	[Console] [Log] Outlook LaunchEvent JS loaded!		
17.05.2024 16:12:12	Verbose	Runtime	[Console] [Log] InvokeMailboxCreateOM was invoked![", 
17.05.2024 16:12:12	Verbose	Runtime	[Console] [Log] SDX Control is ready!		
17.05.2024 16:12:12	Verbose	Runtime	[Console] [Log] MailboxHostExecuteApi invoked!		
17.05.2024 16:12:12	Verbose	Runtime	[Console] [Log] RunLaunchEventHandlerFunctionWithData was invoked with funcName = onMessageComposeHandler		
17.05.2024 16:12:12	Verbose	Runtime	[Console] [Log] RunLaunchEventHandlerFunctionWithData was invoked with funcName = OnMessageRecipientsChanged		
17.05.2024 16:12:12	Verbose	Runtime	[Console] [Log] RunLaunchEventHandlerFunctionWithData was invoked with funcName = onMessageRecipientsChangedHandler

**Comment by barisbikmaz** [comment]
I also realized that "onMessageRecipientsChanged" is also fired when replying to an email. That should also not happen and is inconsistent with the web version.

**Comment by ztcdsb** [comment]
@barisbikmaz We don't have a solid repro at this point, can you kindly offer more details about it? A sample add-in will be appreciated

**Comment by ztcdsb** [comment]
Thanks for reporting this issue regarding signature bookmark. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 9055353
