### ISSUE TITLE
Get thumbnail for word, excel and powerpoint file

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4473]
We want to get thumbnail for word, excel and powerpoint file. This will be required to present file icon.
Can you please help me to get this data?

Thanks

**Comment by Rick-Kirkham** [comment]
@slabereemsft Can you help this customer? Thanks.

**Comment by ishanig11** [comment]
@Rick-Kirkham  @slabereemsft  : Any update on query?

Thanks in advance,

**Comment by ishanig11** [comment]
@slabereemsft  @Rick-Kirkham : Any update on query?

**Comment by slabereemsft** [comment]
Given this is a request for WXP JavaScript API sending this to Wenjun.

Note: I'm not aware of any APIs that does this today so this sounds like a feature request.  I would suggest that there are a number of 3rd party JavaScript libraries that can transform Office files into images, etc that could be helpful.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 Thanks for reaching out. Unfortunately, there is no existing Office.JS API that can meet this requirement yet. You may file a feature request in our community forum: [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform). And if you like to talk with us for a deeper discussion for your use case and business impact, please leave your contact info in this form: https://forms.office.com/r/QayRq1FVEb, and we will follow up and schedule a short meeting to discuss.
