### ISSUE TITLE
RibbonApi 1.1 support

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4475]
Hi,

I am using latest Office 365 application online version. Below are version details.
![image](https://github.com/OfficeDev/office-js/assets/157671419/343b6dd0-d24b-489b-bb39-0836cd0957e9)
Also add below entry in manifest file:
![image](https://github.com/OfficeDev/office-js/assets/157671419/d76b221f-c9ab-4b15-beab-7552f66fe095)

I am using https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js office.js. 
But if I execute Office.context.requirements.isSetSupported("RibbonApi", "1.1") command from my addin, it returns false. 
Can you please tell me which setting  I am missing?

Thanks

**Comment by Rick-Kirkham** [comment]
Are you sure that you're working with a host that supports it? Check out the **Important!** note on this page: [RibbonApi Requirement Sets](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/common/ribbon-api-requirement-sets).

**Comment by ishanig11** [comment]
Yes. I am testing this one Office 365 online version and as per documents its supported.
[manifest.zip](https://github.com/OfficeDev/office-js/files/15366819/manifest.zip)
Attached manifest file also for reference.

**Comment by EsterBergen** [comment]
@ishanig11 - Are you seeing this error on a specific host? Like PowerPoint Online, Excel Online, or Word Online?

**Comment by ishanig11** [comment]
@EsterBergen I want to use add-in commands enable/disable functionality. But its not working as above value is coming as false.

**Comment by EsterBergen** [comment]
@ishanig11 - thanks again!  Do you want to use this on a specific program? Like Excel, PowerPoint, Word?

**Comment by ishanig11** [comment]
@EsterBergen : Yes I want to use it for Word, Excel & PowerPoint.  have created separate manifest file for Word, Excel & PowerPoint.

**Comment by EsterBergen** [comment]
Hi @ishanig11 - Thanks for clarifying! This should work already for Excel. Word and Powerpoint Online are not yet available and we're working to enable the Ribbon Api Set 1.1 in the upcoming months.

**Comment by ishanig11** [comment]
@EsterBergen : Thank you for the updates? Can you please tell me when will it be available in Word and Powerpoint?  We are planning to deploy our developed addin by mid of June.

**Comment by EsterBergen** [comment]
@ishanig11 - we don't have a sense of the release yet. It will most likely be after June. I will update this ticket once more clarity is available.

**Comment by ishanig11** [comment]
Sure. can I expect it around July end?

**Comment by EsterBergen** [comment]
@ishanig11 - Great news. This feature has begun rolling out to production on Word for Web. It should be available by july end, if not sooner. Please try and let us know if it works.

**Comment by ishanig11** [comment]
@EsterBergen  thanks for this updates. Really great news.
I will check next week once.

**Comment by ishanig11** [comment]
@EsterBergen : Its working fine.

**Comment by EsterBergen** [comment]
@ishanig11 - Glad it works!
