### ISSUE TITLE
Custom properties support in powerpoint

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4479]
Is there anyway to add custom properties to powerpoint?

we have developed add-in for MS-Word using custom properties and now need to deploy similar functionality to powerpoint. But not getting anyway to add custom properties to powerpoint. Can you please help me with solution for this?
This is really blocker.

Thanks in advance.

**Comment by manuelsidler** [comment]
@ishanig11 we're using presentation tags as a workaround for the missing custom properties: https://learn.microsoft.com/en-us/office/dev/add-ins/powerpoint/tagging-presentations-slides-shapes#set-custom-metadata-on-the-presentation

**Comment by EsterBergen** [comment]
Hi @ishanig11 - are you looking to add Custom XML Parts? https://learn.microsoft.com/en-us/javascript/api/word/word.customxmlpartcollection?view=word-js-preview

**Comment by ishanig11** [comment]
@manuelsidler Thank you for this.
@EsterBergen  : I want to use custom properties function not custom xml.

**Comment by EsterBergen** [comment]
@ishanig11 - Thanks for clarifying! Is this what you're referring to? https://learn.microsoft.com/en-us/office/open-xml/word/how-to-set-a-custom-property-in-a-word-processing-document?tabs=cs-0%2Ccs-1%2Ccs-2%2Ccs-3%2Ccs-4%2Ccs-5%2Ccs-6%2Ccs-7%2Ccs-8%2Ccs-9%2Ccs-10%2Ccs

**Comment by ishanig11** [comment]
@EsterBergen : Yes I am looking for same functionality in powerpoint.

**Comment by EsterBergen** [comment]
@ishanig11 - this would be a new feature. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process.

**Comment by manuelsidler** [comment]
Someone already opened a feature request last year: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-support-for-custom-properties-in-powerpoint-office-js-api/idi-p/3750808

**Comment by ishanig11** [comment]
@manuelsidler : Yes, I have seen it. But dont see any further updates on that link. Any update when this feature will be available?

**Comment by manuelsidler** [comment]
@ishanig11 I also tried to get some information during the monthly community call. Unfortunately, I've never received an answer about the roadmap.

**Comment by ishanig11** [comment]
@manuelsidler : Its really important for us to understand feature roadmap.  That help us to plan our product releases also.

**Comment by EsterBergen** [comment]
Hi @ishanig11  and @manuelsidler - I wanted to let you know that we recently released custom properties for PPT into preview. https://learn.microsoft.com/en-us/javascript/api/requirement-sets/powerpoint/powerpoint-preview-apis?view=common-js-preview

**Comment by manuelsidler** [comment]
@EsterBergen, thank you! I've already had a chance to play around with it, and everything worked as expected. Would you happen to have any plans yet for GA?

**Comment by ishanig11** [comment]
Thank you @EsterBergen  for this update.

**Comment by EsterBergen** [comment]
@manuelsidler - GA will be within the upcoming two months. We had a bit of delay with holiday freezes. Will post here once we are fully available.

**Comment by EsterBergen** [comment]
@ishanig11  and @manuelsidler - this was released recently in Req set 1.7. Can you check and see that it's working for you? https://learn.microsoft.com/en-us/javascript/api/requirement-sets/powerpoint/powerpoint-api-1-7-requirement-set?view=common-js-preview
