### ISSUE TITLE
getSelectedItemsAsync is not working properly in web browser

### ISSUE THREAD

**Issue by hmaheshwariAsite** [OfficeDev/office-js#4481]
Steps To Reproduce :

Select Multiple Items in uninterrupted order in outlook web version and try to open add in
Some times the getItemsSelectedAsync will give result as failed. 

But in Desktop Version the function is working fine even if we select multiple items in uninterrupted order or consecutive order

can you please look into this issue ?

Also is there any function so that we can get full email details and its attachments when we select multiple items similar to Office.context.mailbox.item ?

![Screenshot 2024-05-21 113900](https://github.com/OfficeDev/office-js/assets/170398481/05cce172-492d-46a5-90ed-a01b03246cd6)

**Comment by rajjha-msft** [comment]
Hey @hmaheshwariAsite 

It's not a repro at our end.
Can you share a video of the repro ?

**Comment by hmaheshwariAsite** [comment]
Please have a look @rajjha-msft 

https://github.com/OfficeDev/office-js/assets/170398481/b94d4130-cb12-498f-9bf1-c7dab5c1598e
https://github.com/OfficeDev/office-js/assets/170398481/dcfa0097-de7e-4ae5-a7df-0d2b0473ec37

**Comment by rajjha-msft** [comment]
Hey @hmaheshwariAsite 

Please help us understand the issue better 
- Is this a transient issue, happens once in a while or consistently happens ?
- Is this something which has started to happen recently ?
- Does this happen with all Multi Select / Contextfree add-ins ?

**Comment by codenovous-harsh** [comment]
Hello @rajjha-msft 
Yes this is an  Intermittent Issue when we change selected emails sometimes it works correctly , sometimes it is failed.
This was happening earlier also
Yes it happens with Multi select add in (at least in our add in it is happening) 
For Single email it works correctly as we use Office.context.mailbox.item but when we use getSelectedItemsAsync it works correctly in desktop version but in web browser it gets failed sometimes.

**Comment by hmaheshwariAsite** [comment]
Hello @rajjha-msft 
This is my id @bot608 

Just letting you know

**Comment by anjalitp** [comment]
@hmaheshwariAsite  We are able to repro this issue. Thanks for reporting this issue regarding getSelectedItemsAsync API on OWA. This has been added to our backlog. Unfortunately, we do not have a timeline to share at this point. 

Internal Tracking ID: 4604809

**Comment by hmaheshwariAsite** [comment]
@anjalitp Any updates on this Issue ?

**Comment by mobisw-msft** [comment]
@hmaheshwariAsite ,

We are unable to reproduce this issue any more, and this issue likely has been resolved. Can you confirm if you're still seeing this issue?
