### ISSUE TITLE
Slow response times from AmURL in ID tokens for 365

### ISSUE THREAD

**Issue by GrumpyAL** [OfficeDev/office-js#4485]
_Note: I understand these tokens are going away soon and there may be nothing to be done right now.  I also wasn't sure if this was the right place to ask so I apologize if not and ask if you could point me in the right direction._

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Any/NA
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: any/NA
* Operating System: Windows 11, Azure App Service, probably n/a
* Browser (if using Office on the web): n/a
 
## Expected behavior
With https://outlook.office365.com/autodiscover/metadata/json/1
When requesting the public key from the endpoint in the AMURL , the document is returned in a timely manner.

## Current behavior
With https://outlook.office365.com/autodiscover/metadata/json/1
When requesting the public key from the endpoint in the AMURL , the document sometimes takes over 1000ms to return.  Sometimes it's 40ms.

## Steps to reproduce
Simply use Postman or a browser to GET https://outlook.office365.com/autodiscover/metadata/json/1
Note the discrepancy in times to return.

## Context
We were looking at a customer's response times within AppInsights in an Azure webapp and noticed that our calls out to this endpoint were sometimes slow.  So we attempted it directly to make sure it wasn't something with the environment or application and noticed that sometimes it is very fast (<40ms) and other times it lags (>1000ms).  This doesn't appear to be a throttling behavior, the slow returns seem more random.

Just wondering if there's anything that can be looked at to reduce that variance.  I understand this probably isn't something the OfficeDev team controls but wasn't sure where to raise this so figured I would start here.

This variance leads to delays in our application because we have to wait for the public key to validate the token before we move on.

**Comment by Adrian-MSFT** [comment]
Closing, as this is not an issue specific to Outlook Add-ins
