### ISSUE TITLE
The onMessageRecipientsChangedHandler event does not get executed completely in Mac

### ISSUE THREAD

**Issue by RaveendraReshma** [OfficeDev/office-js#4489]
1. We are developing office web Addin for outlook using event based (Smart Alert) .The Addin is generated using office yo generator Task Pane add-in using the React framework.
2. We are getting the recipient data [ to/cc/bcc ] using Office.context.mailbox.item and we are rendering the same recipients onto the taskpane.
3. We have added the onMessageRecipientsChangedHandler event in the react component so when ever user adds any recipient the event gets triggered and the recipient gets painted onto the taskpane.
4. Issue that we are facing here is the event gets triggered but never completes its execution due to which the recipient rendering onto the taskpane is not happening. 
5. We are facing this issue only in Mac Thick Client and everything works fine in safari browser.

## Your Environment

- Platform : MAC
- Host : Outlook on MAC
- Office version number : Version 16.84.1 (24042118)
- Operating System : MacOs

## Expected behavior

- Event should get executed completely.

## Current behavior

- event stops executing mid way and never completes.

## Link to live example(s)

<img width="857" alt="mac" src="https://github.com/OfficeDev/office-js/assets/145095553/9774adf2-c5d7-4e5d-a272-47bff96583b3">

**Comment by RaveendraReshma** [comment]
The issue is quite related to below bug 

#4303

**Comment by rajjha-msft** [comment]
Hey @RaveendraReshma 

It's not.a repro form our end. 
Can you please share a sample add-in which we can use to repro the same?
