### ISSUE TITLE
chart support multiple YAxes

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#449]
hi

if office.js support multiple YAxes like the below chart?

![image](https://user-images.githubusercontent.com/3963826/55202446-6cc87700-5202-11e9-9c2a-80a9bab89fce.png)

thanks

**Comment by lumine2008** [comment]
Yes, Office.JS support YAxis. You can use ChartSeries.axisGroup = Excel.ChartAxisGroup.secondary to set a series to secondary axis. To get this axis, could use: Chart.axes.getItem(“Value”, “Secondary”);

**Comment by kbrandl** [comment]
Closing this issue, as it seems like the information provided by @lumine2008 effectively addresses it.
