### ISSUE TITLE
Menu option in Office Ribbon

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4490]
Hi, 

I am looking to add menu for add-in commands. Please refer image below:
![image](https://github.com/OfficeDev/office-js/assets/157671419/294b054f-bbd3-4066-8c51-0577d146c928)

Is there anyway to achieve this?

Thanks

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11, I found a reference: https://learn.microsoft.com/en-us/office/dev/add-ins/design/add-in-commands, hope it is helpful. Hi @m-hellesen, do you have any idea to achieve this? Thanks.

**Comment by ishanig11** [comment]
Thank you @shanshanzheng-dev . With above link I can add commands like 
![image](https://github.com/OfficeDev/office-js/assets/157671419/442f70eb-1b67-4855-89b8-281e94be22f3)
I have already implemented this through manifest file. I am looking someway to add commands as dropdown or menu using manifest file.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11, I found a codeSamples https://learn.microsoft.com/en-us/samples/officedev/pnp-officeaddins/excel-add-in-commands/, could you try this?

**Comment by ishanig11** [comment]
@shanshanzheng-dev : Thank you for sharing this code sample. I created controls similar as shown above example. 
Please refer ![image](https://github.com/OfficeDev/office-js/assets/157671419/4020ae93-4268-470f-9000-83bfe770b681) for control definition.

I am trying this on online office version. Kindly check and let me know what is missing.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11, I think this code is good, maybe you can try this steps to upload manifest:https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/office-add-in-commands/excel#run-the-sample-on-excel-on-the-web

**Comment by ishanig11** [comment]
@shanshanzheng-dev : yes, I have already uploaded manifest file. I did all these steps. I see all my commands in Excel ribbon but no dropdown.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11, I download that manifest from https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/office-add-in-commands/excel/manifest.xml, and upload this manifest from: 
![image](https://github.com/OfficeDev/office-js/assets/125014206/436e3d84-9f85-476e-85db-27070c0a1df9)
And then, I can see the dropdown menu:
![image](https://github.com/OfficeDev/office-js/assets/125014206/81dab832-6109-41c1-82d6-1008fffdcb86)
Or you can change this simple code to what you want？

**Comment by ishanig11** [comment]
It worked. Thank you.
Is this feature supported for Word, Powerpoint also? Also is it possible to show one command and then remaining commands as part of dropdown. Like 
![image](https://github.com/OfficeDev/office-js/assets/157671419/094b0276-3ae5-4c8d-a4cc-a99968d12d73)
Here if use click directly on Menu, Help gets executed and other command is as part of dropdown.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 I think it support word and powerpoint also. You can try https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/office-add-in-commands/word/manifest.xml and https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/office-add-in-commands/powerpoint/manifest.xml
But about commands as part of dropdown, I don't think so, I'll check with my team workers. If there're some updates, I'll confirm with you. Thanks.

**Comment by ishanig11** [comment]
Thank you. It worked. Is there anything for
![image](https://github.com/OfficeDev/office-js/assets/157671419/69e8accd-772a-4829-af8b-69942d8715bd)

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11, Sorry for slow response. About commands as part of dropdown, I think we can't do this, I'll check with my team workers. If there're some updates, I'll confirm with you. Thanks.

**Comment by EsterBergen** [comment]
@ishanig11 - can you help me understand the specific question? Are you looking to have an app command in the dropdown or something different?

> Thank you. It worked. Is there anything for ![image](https://private-user-images.githubusercontent.com/157671419/333951442-69e8accd-772a-4829-af8b-69942d8715bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxODU1MjcsIm5iZiI6MTcxNzE4NTIyNywicGF0aCI6Ii8xNTc2NzE0MTkvMzMzOTUxNDQyLTY5ZThhY2NkLTc3MmEtNDgyOS1hZjhiLTY5OTQyZDg3MTViZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMVQxOTUzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzY1MjFjMzY1ZmI0ZTJjYTBjOWVlMGFiNGM5OThmMGZiN2M4Y2U1ZGExMTJjYmEwYTkwNzJiOTlkYWNmYTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WsRxaPdcxeXy6mGuPxGVdwuYJ-HDMaHau1lpMXEhH_k)

**Comment by ishanig11** [comment]
@EsterBergen : Along with Dropdown, I am looking for options to how pre-populated data on commands like textbox as shown in image.

**Comment by EsterBergen** [comment]
HI @ishanig11 - This functionality is not currently supported.  We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. Thanks for highlighting this!
