### ISSUE TITLE
OnNewMessageCompose  not working on desktop 

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js#4496]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: _____PC desktop_
* Host [Excel, Word, PowerPoint, etc.]: _____Outlook_
* Office version number: _____Microsoft® Outlook® LTSC MSO (16.0.14332.20696) 64-bit_
* Operating System: _____Windows_
* Browser (if using Office on the web): ______
 
## Expected behavior

I am trying to add OnNewMessageCompose event this is working file on web outlook but not working on desktop outlook I want this will work on all platforms.

## Current behavior

I am trying to add OnNewMessageCompose event this is working file on web outlook but not working on desktop outlook.

## Link to live example(s)

1. ___this is my live [manifest ](https://github.com/aamirhusnain/chillisign/blob/main/manifest.xml)when I install this from desktop the add-in is not showing in desktop outlook same manifest working on web outlook___

## Useful logs

- [ ] work on desktop 

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by junaid042** [comment]
Hi @exextoc 

I have shared my online manifest please check it using this manifest my add-in is not showing on windows desktop but same on web working correctly

**Comment by junaid042** [comment]
Ohh! add-in is showing on read mode. In my manifest I am using ExtensionPoint  `MessageComposeCommandSurface

**Comment by junaid042** [comment]
Hi @exextoc any Update?

**Comment by timwan10** [comment]
There are a couple of things happening here. 

Your version is the 2021 LTSC version of Outlook. The Max version it supports is 1.9: [Link](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets?view=common-js-preview&tabs=jsonmanifest#requirement-sets-supported-by-exchange-servers-and-outlook-clients)

Launch Events need 1.10 to be supported: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch

In your manifest in version overrides you specified the min version as 1.10. 

So what is happening is your version of Outlook doesn't support 1.10, and is falling ALL the way back to the section described in: 

```
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://aamirhusnain.github.io/chillisign/taskpane.html"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
```

So you cannot use LaunchEvents in that version of office. If you want to support LaunchEvents in deskop, you will need to upgrade. 

If you would like to fail more gracefully in older versions of Outlook, you can either adjust the MinVersion from 1.10 to 1.9, and then the MessageComposeCommandSurface will start working. (but the LaunchEvents won't) 

You could instead specify a VersionOverrides 1.0 section with a lower min version, that will fall back on if 1.1 min version is not supported.
