### ISSUE TITLE
Outlook for Microsoft 365 MSO version 2403 doesn't show an addin when using requirement set 1.13

### ISSUE THREAD

**Issue by makkros** [OfficeDev/office-js#4501]
# Provide required information needed to triage your issue

## Your Environment

* Platform: PC desktop 
* Host: Microsoft® Outlook® for Microsoft 365 MSO (Version 2403 Build 16.0.17425.20236) 64 bit 
* Office version number: Microsoft 365 MSO
* Operating System: Windows 10/11
* Browser 
 
## Expected behavior

An Outlook web addin should appear on the ribbon when I select one or more emails

## Current behavior

 The addin is not shown by Outlook on the Ribbon when in the unified manifest we use "requirements.capabilities.minVersion" property to "1.13"

## Steps to reproduce

1. Upload the following manifest to the Teams Apps page 
`{
  "$schema": "https://developer.microsoft.com/json-schemas/teams/v1.17/MicrosoftTeams.schema.json",
  "manifestVersion": "1.17",
  "id": "${{CLIENT_ID}}",
  "version": "${{MANIFEST_VERSION}}",
  "name": {
    "short": "*** add-in",
    "full": "*** add-in"
  },
  "description": {
    "short": "*** add-in",
    "full": "****"
  },
  "icons": {
    "outline": "assets/outline.png",
    "color": "assets/color.png"
  },
  "accentColor": "#230201",
  "developer": {
    "name": "***",
    "websiteUrl": "***",
    "privacyUrl": "***",
    "termsOfUseUrl": "***"
  },
  "localizationInfo": {
    "defaultLanguageTag": "en-us",
    "additionalLanguages": []
  },
  "webApplicationInfo": {
    "id": "${{CLIENT_ID}}",
    "resource": "api://${{TAB_DOMAIN}}/${{CLIENT_ID}}"
  },
  "authorization": {
    "permissions": {
      "resourceSpecific": [
        {
          "name": "Mailbox.ReadWrite.User",
          "type": "Delegated"
        }
      ]
    }
  },
  "validDomains": ["${{TAB_DOMAIN}}", "${{TAB_DOMAIN}}/auth", "https://login.microsoftonline.com"],
  "extensions": [
    {
      "requirements": {
        "scopes": ["mail"]
      },
      "runtimes": [
        {
          "requirements": {
            "capabilities": [
              {
                "name": "Mailbox",
                "minVersion": "1.13"
              }
            ]
          },
          "id": "TaskPaneRuntime",
          "type": "general",
          "code": {
            "page": "${{TAB_ENDPOINT}}/taskpane.html"
          },
          "lifetime": "short",
          "actions": [
            {
              "id": "TaskPaneRuntimeShow",
              "type": "openPage",
              "view": "dashboard",
              "pinnable": true,
              "supportsNoItemContext": true,
              "multiselect": true
            }
          ]
        }
      ],
      "ribbons": [
        {
          "contexts": ["mailRead"],
          "tabs": [
            {
              "builtInTabId": "TabDefault",
              "groups": [
                {
                  "id": "msgReadGroup",
                  "label": "***",
                  "icons": [
                    {
                      "size": 16,
                      "url": "${{TAB_ENDPOINT}}/assets/icon-16.png"
                    },
                    {
                      "size": 32,
                      "url": "${{TAB_ENDPOINT}}/assets/icon-32.png"
                    },
                    {
                      "size": 80,
                      "url": "${{TAB_ENDPOINT}}/assets/icon-80.png"
                    }
                  ],
                  "controls": [
                    {
                      "id": "msgReadOpenPaneButton",
                      "type": "button",
                      "label": "*** add-in",
                      "icons": [
                        {
                          "size": 16,
                          "url": "${{TAB_ENDPOINT}}/assets/_logo_PNG.png"
                        },
                        {
                          "size": 32,
                          "url": "${{TAB_ENDPOINT}}/assets/_logo_PNG.png"
                        },
                        {
                          "size": 80,
                          "url": "${{TAB_ENDPOINT}}/assets/_logo_PNG.png"
                        }
                      ],
                      "supertip": {
                        "title": "*** add-in",
                        "description": "Opens a pane displaying all available document operations."
                      },
                      "actionId": "TaskPaneRuntimeShow"
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}`
3. Open Outlook client 

# Provide additional details

We have implemented a web addin using Outlook.js that shows in the task pane when an email is read. Now we need to use this addin also when multiple email are selected, so following the [Microsoft Documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select?tabs=jsonmanifest) we need to use the 1.13 requirement set. Unfortunately the addin is not shown by Outlook on the Ribbon when in the unified manifest we change the "requirements.capabilities.minVersion" property to "1.13", if we set the "requirements.capabilities.minVersion" property to 1.12, leaving all the rest of the manifest the same, the addin is shown again. It seems to be an incompatibility of the Outlook client, but it shouldn't, we are using the Microsoft® Outlook® for Microsoft 365 MSO (Version 2403 Build 16.0.17425.20236) 64 bit updated with the Monthly Enterprise Channel and from [here](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets?view=common-js-preview&tabs=jsonmanifest#version-support-for-requirement-sets-in-classic-outlook-on-windows) as per my understanding the 1.13 should be supported. Am I interpreting the version support table wrong? Or we are doing something wrong on the manifest?

**Comment by millerds** [comment]
Have you tried the same thing with an xml manifest?  The json manifest is preferred, but it would be helpful to know if there is a different in behavior between the two when there shouldn't be.

**Comment by millerds** [comment]
Thanks for reporting this issue.  We are working on the fix but cannot comment on the timeline.  It does work for XML manifests.  You could use that until we have a fix for the unified manifest.

Internal tracking Id: 9093312

**Comment by millerds** [comment]
Fix has been made and should be rolling out in the coming months to various channels.
