### ISSUE TITLE
Custom functions in error state do not get recalculated by Excel

### ISSUE THREAD

**Issue by gmichaud** [OfficeDev/office-js#4502]
# Provide required information needed to triage your issue
Excel does not reinvoke our custom functions on cells showing a #VALUE! error when you force a full recalculation of the workbook (using the Refresh button of our add-in ribbon or when doing CTRL-ALT-F9 in Excel).

This issue has been reported by many customers over the last year and we have not been able to isolate the issue until recently. This issue appears to happen in conjunction with an error initializing custom formulas, as described in #4487.

We were able to isolate this in a fairly simple file that I can share with Microsoft via a private link on request.

Demo from Windows: https://www.loom.com/share/ef9351ad9a3748bf9e9805f20dda1317
Demo from Mac: https://www.loom.com/share/652438c17cbc4bb89fe0b501ad14b812

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Issue replicated on Excel for Mac and Excel for Windows
* Host [Excel, Word, PowerPoint, etc.]: Mac 16.85, Windows Version 2404 Build 16.0.17531.20152) 64 bits  

## Expected behavior
All the formulas should recalculate when you hit the Refresh button or press CTRL-ALT-F9

## Current behavior
Only the first formula of the Data tab recalculates (column B); other columns show #VALUE! Eventually, if you leave Excel running in the background, the formula recalculates.

<img width="1290" alt="Screenshot 2024-05-25 at 5 15 29 PM" src="https://github.com/OfficeDev/office-js/assets/9433888/be702530-2e1f-45a1-b536-b19e37295a45">

Please note the warning message presented in the cell "A value used in the formula is of the wrong data type" -- this is very confusing to users as well.

## Steps to reproduce

1. Open file (please request via comments, I will share through secure link) -- notice that some columns will temporarily show a #NAME! error for all the cells that were previously in an error state
2. Go to add-in ribbon "Velixo"
3. Click Refresh All button -- cells in error state do not refresh

Doing "Calculate Sheet" on the affected sheets after step 3 seems to resolve it, but this is not an acceptable solution for customers with large workbooks -- they can't be expected to figure out on which sheets calculation failed. In some cases I've also seen these columns start calculating after a very long wait.

## Link to live example(s)
Demo from Windows: https://www.loom.com/share/ef9351ad9a3748bf9e9805f20dda1317
Demo from Mac: https://www.loom.com/share/652438c17cbc4bb89fe0b501ad14b812

# Provide additional details
This problem started occurring on that file following a failed loading of our add-in. I had to uninstall and reinstall the add-in for it to work in *any* workbook, however after that the file I had open when the issue first occurred was in this weird state. This seems similar to the issue described in #4487.
<img width="511" alt="Screenshot 2024-05-25 at 5 16 38 PM" src="https://github.com/OfficeDev/office-js/assets/9433888/0b5e0145-b9a0-435e-975c-e8632e8e8445">
<img width="736" alt="Screenshot 2024-05-25 at 5 16 43 PM" src="https://github.com/OfficeDev/office-js/assets/9433888/d8fe88ad-d35e-4cb0-ac83-2f8d21a001a2">

Note that we also opened the XML structure of a "good" and a "bad" file to compare, and the notable difference is the aca and ca attribute of the formula (note: our formulas can all return arrays, in case that matter):

<img width="1277" alt="Screenshot 2024-05-25 at 5 18 00 PM" src="https://github.com/OfficeDev/office-js/assets/9433888/3aee6ba7-f6b4-4cd1-801b-fc03e1cf5859">

**Comment by shanshanzheng-dev** [comment]
Hi @gmichaud, We're looking into this problem, thanks for reporting! we will report back here if we have an investigation. Thanks.

**Comment by wh1t3cAt1k** [comment]
[Velixo internal tracking item](https://3.basecamp.com/3496385/buckets/16689259/card_tables/cards/7448603990)

**Comment by wh1t3cAt1k** [comment]
Following our recent discussion, it seems like it is a false alarm produced by the file with complex calculation dependencies. @gmichaud would you be fine with closing this following Xuan Zhou's email explanation?

**Comment by tobz1000** [comment]
@wh1t3cAt1k would you mind sharing the email explanation here?
