### ISSUE TITLE
Add-in In Word is not working when opening second time

### ISSUE THREAD

**Issue by abhirammenni** [OfficeDev/office-js#4503]
When add-in is opened in MS word, it's loading as expected first time. When we reopen the same add-in, it's not loading. I don't see any console errors as well. On checking the Elements in Dev Tools, the elements which is rendering the Add-in itself hasn't loaded. 

When the page is reloaded, the behaviour is same. It loads for the first time and doesn't load from second time.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac (Using on we)
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: ______
* Operating System: Mac 
* Browser (if using Office on the web): Edge (Version 125.0.2535.67 (Official build) (x86_64))
 
## Expected behavior
Add-in Should open as expected

## Current behavior
When add-in is opened in MS word, it's loading as expected first time. When we reopen the same add-in, it's not loading.

## Steps to reproduce
1. Attaching the manifest with this.
2. Open word, add the attached Manifest.
3. Open the manifest (see the page loads). 
4. Close the manifest and reopen the manifest. The page doesn't load.

Attaching video reference as well.

[manifest-stage-updated.xml.zip](https://github.com/OfficeDev/office-js/files/15453011/manifest-stage-updated.xml.zip)
 
https://github.com/OfficeDev/office-js/assets/170700175/8ac3a1b8-08fa-4791-baeb-42e2ca2193ca

**Comment by shanshanzheng-dev** [comment]
Hi @abhirammenni, Thanks for report this issue. But when I try to repro this issue use manifest you report, I got a error, could you help to update a new manifest? Thanks.
![image](https://github.com/OfficeDev/office-js/assets/125014206/2082264b-8dbe-4b3b-a7b3-fdc357bcfb57)

**Comment by abhirammenni** [comment]
[word_second_load_test.xml.zip](https://github.com/OfficeDev/office-js/files/15455043/word_second_load_test.xml.zip)

Hi @shanshanzheng-dev, attaching new manifest, pls check with this.

**Comment by shanshanzheng-dev** [comment]
Hi @abhirammenni Thanks for provide this manifest. I can repro this issue. We'll be looking into this problem, and will report back here if we have a suggestion for you.

**Comment by xiruatms** [comment]
@abhirammenni , thanks for reporting this.

I've done as you mentioned. Just a little difference: if you wait for more seconds for the first time, you'll notice the following error:
![image](https://github.com/OfficeDev/office-js/assets/40648203/980b5d0a-4179-4d6c-9914-7208b6aa9299)

I assume that might be related to the configuration in manifest:

Usually, the lines will be something like this:
  <DefaultSettings>
    <SourceLocation DefaultValue="https://officedev.github.io/Office-Add-in-samples/Samples/office-add-in-commands/word/src/taskpane/taskpane.html"/>
  </DefaultSettings>

But in your manifest:
<DefaultSettings><SourceLocation DefaultValue="https://empabhi3.service-now.com/"/></DefaultSettings>

And the page was retrieved as following:
![image](https://github.com/OfficeDev/office-js/assets/40648203/778c4bf0-14d1-4e75-825c-e335fafba581)

Please help to confirm what you're expecting, and which manifest template you're using.

**Comment by abhirammenni** [comment]
@xiruatms I too can see the error after waiting a while. But in the first place, why is this error showing up.  If you check the Page that is loading, it's very simple & back. Curios to know why this error is showing up

**Comment by xiruatms** [comment]
@abhirammenni , I'm not quite sure whether it's simple & back. If possible, will you please get those complete html codes out and prepare a separate html file to take one more try? We might need to get to the root cause piece by piece.

![image](https://github.com/OfficeDev/office-js/assets/40648203/e9f8fdaa-9fc0-4bcc-80ba-9a4daa41d289)

**Comment by abhirammenni** [comment]
@xiruatms The page which is being loaded in the Add-in doesn't have any of these things. Below is the URL of the page. May be the styles and shadow root might be coming from your extensions. Below is the URL which is loaded in the Add-in and attaching it's HTML content as well. You can open this page in new tab and check. I didn't find any additional elements in the screenshot you attached.


<img width="1784" alt="Screenshot 2024-06-04 at 5 13 23 PM" src="https://github.com/OfficeDev/office-js/assets/170700175/044b53a6-2895-4919-b415-4a6ab2baa135">

**Comment by abhirammenni** [comment]
@xiruatms Any update on this?

**Comment by xiruatms** [comment]
@abhirammenni , sorry I can't repro this locally. Can you set up a sample demo project to repro this and share with me? That'll be helpful for me to understand your issue.

**Comment by abhirammenni** [comment]
[word_second_load_test_updated.xml.zip](https://github.com/user-attachments/files/16132237/word_second_load_test_updated.xml.zip)

@xiruatms @shanshanzheng-dev, I've created a new manifest by adding a new page. (https://abhirammenni.github.io/sample-repo/). This is just a HTML page. code - https://github.com/abhirammenni/sample-repo/blob/dev/index.html

Even with this page as well, we are facing the same issue.

**Comment by abhirammenni** [comment]
@xiruatms @shanshanzheng-dev Can you pls check the updated manifest and reopen the issue?

**Comment by xiruatms** [comment]
@abhirammenni , thanks for providing more details. I can repro now.

The key point here is: Office.Js need to be referenced and Office.onReady should be called. The reason is that: the addin was designed to use Office.js to implement some functionalities. Some pipeline needs to be set up when the addin was initialized so that Office Js apis can be called. 

In your case, you can add following codes to your html:
`   <head>
    
    <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
    <script type="text/javascript">
        Office.onReady((info) => {
            if (info.host === Office.HostType.Word) {
            //anything you need to set up.
            }
        });
    </script>
    </head>`
![image](https://github.com/OfficeDev/office-js/assets/40648203/84aee76c-8d2f-4ab0-aa32-322dfc58cf28)

 
Then, there should be no errors reported.

Furthermore, please refer to:
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/develop-overview
and there are lots of samples here:
https://github.com/OfficeDev/Office-Samples

**Comment by abhirammenni** [comment]
@shanshanzheng-dev 

In our main application, we do use office.js and use it on Office.onReady(). Just for reproducing the issue, I've setup a simple page. 

I've added office.js as you mentioned in this page. Even now I'm facing the error

**Comment by xiruatms** [comment]
@abhirammenni , will you please show me your latest codes and error?

**Comment by abhirammenni** [comment]
Code: https://github.com/abhirammenni/sample-repo/blob/dev/index.html

Issue: We are facing the same issue as above. 
-> On first load of manifest it is working fine.
->  From next loads, it take quite a bit of time and shows retry error as mentioned [here](https://github.com/OfficeDev/office-js/issues/4503#issuecomment-2134536244)

**Comment by xiruatms** [comment]
![image](https://github.com/OfficeDev/office-js/assets/40648203/dd056c3b-efa8-4fd5-b6ce-70a7a513b218)
@abhirammenni ,  please be noted with the codes you shared. There're <head> inside <head>....

**Comment by abhirammenni** [comment]
@xiruatms My bad. I just updated the code. Even now the issue is same

**Comment by xiruatms** [comment]
@abhirammenni , will you please clear the cache and take one more try? https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache

**Comment by abhirammenni** [comment]
@xiruatms  I'm using browser for testing. I tried clearing the cache and even tried in incognito as well. Still no luck...

**Comment by abhirammenni** [comment]
@xiruatms  @shanshanzheng-dev 

Any update on this?

**Comment by xiruatms** [comment]
@abhirammenni , thanks for your patience.

In your manifest, there's "TaskpaneId" missing in <Action>
![image](https://github.com/user-attachments/assets/6582dd76-9433-4ec7-908f-14a66f716db2)

please add one as following:
![image](https://github.com/user-attachments/assets/8916d7d1-61fe-459a-b01b-c9161820ba96)

clear the cache, re-sideload this manifest to see whether it works.

**Comment by xiruatms** [comment]
@abhirammenni, will you please confirm?

**Comment by abhirammenni** [comment]
@xiruatms, After adding the TaskpaneId, this is working as expected. Thanks for your help
