### ISSUE TITLE
Why I can not get the roaming settings from the dialog panel in Outlook for Mac??

### ISSUE THREAD

**Issue by Robirob20** [OfficeDev/office-js#4510]
# Provide required information needed to triage your issue
I am developing an add-in and I can not get the roaming settings from my dialog panel but i can get them from the taskpane.
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.85.1
* Operating System: Mac
 
## Expected behavior

I want to get the data stored in the roaming settings.
## Current behavior
I want to get the data stored in the roaming setting but I can only get it from the taskpane, when I want to get the same value in the modal window it returns ‘undefined’.

**Comment by anjalitp** [comment]
@Robirob20  This is expected.  Only two Office APIs can be called in the dialog box,

- [Office.context.ui.messageParent](https://learn.microsoft.com/en-us/javascript/api/office/office.ui#office-office-ui-messageparent-member(1))
- Office.context.requirements.isSetSupported (For more information, see [Specify Office applications and API requirements](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/specify-office-hosts-and-api-requirements).)

Please find the documentation on display dialog here https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-best-practices. 

However, your add-in can send messages from the [host page](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#open-a-dialog-box-from-a-host-page) to a dialog box using [Dialog.messageChild](https://learn.microsoft.com/en-us/javascript/api/office/office.dialog#office-office-dialog-messagechild-member(1)).
