### ISSUE TITLE
Fetch API throw a "Load failed" error

### ISSUE THREAD

**Issue by niquenen** [OfficeDev/office-js#4511]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.85 (24051214)
* Operating System: macOS 14.5 (23F79)
* Browser (if using Office on the web): n/a
 
## Expected behavior

Fetch text (or JSON) data and print the result with `console.log`.

## Current behavior

When using the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), an error is thrown with the following message: "Load Failed", from a [`TypeError`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError) object.

## Steps to reproduce

1. Open Excel.
2. Open Automate tab.
3. Create a new script.
4. Paste the following code.

   ```typescript
   async function main(workbook: ExcelScript.Workbook): Promise<void>
   {
       try {
           await fetch('https://google.com');
       }
       catch (error) {
           console.log(error);
       }
   }
   ```

Another example:

```typescript
async function main(workbook: ExcelScript.Workbook): Promise<void>
{
    try {
        // TypeError
        await fetch('https://example.com');
    }
    catch (error) {
        console.log(error);
    }
    try {
        // TypeError
        await fetch('https://google.com');
    }
    catch (error) {
        console.log(error);
    }
    try {
        // TypeError
        await fetch('https://github.com');
    }
    catch (error) {
        console.log(error);
    }
    try {
        await fetch('https://api.github.com');
    }
    catch (error) {
        console.log(error);
    }
}
```

## Link to live example(s)

None

# Provide additional details

None

## Context

Perform HTTP request to retrieve data. Base on an example from the documentation:

- [Use external fetch calls in Office Scripts](https://learn.microsoft.com/en-us/office/dev/scripts/resources/samples/external-fetch-calls)
- [Office Scripts sample scenario: Fetch and graph water-level data from NOAA](https://learn.microsoft.com/en-us/office/dev/scripts/resources/scenarios/noaa-data-fetch)

Are there any restrictions on domains? Example with the [GitHub API](https://api.github.com) and NOAA(https://www.noaa.gov) works, but [example.com](https://example.com) or [Google](https://google.com) failed.

## Useful logs

- [ ] ~~Console errors~~
- [x] Screenshots
- [ ] ~~Test file (if only happens on a particular file)~~

<img width="1514" alt="Screenshot 2024-05-28 at 17 51 22" src="https://github.com/OfficeDev/office-js/assets/7528452/88faba4b-e647-4034-be3a-9dc80979e63a">

<img width="1917" alt="Screenshot 2024-05-30 at 10 42 23" src="https://github.com/OfficeDev/office-js/assets/7528452/cffbc176-4f5f-4a1c-8722-ae51151b077e">

**Comment by shanshanzheng-dev** [comment]
Hi @niquenen We'll be looking into this problem, thanks for reporting! we will report back here if we have a suggestion for you.

**Comment by shanshanzheng-dev** [comment]
Hi @niquenen We'll be looking into this problem, thanks for reporting! we will report back here if we have a suggestion for you. Thanks.

**Comment by niquenen** [comment]
I try on Windows and a stack trace is displayed in the log.

- Platform [PC desktop, Mac, iOS, Office on the web]: Windows
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Office version number: Version 2405 Build 16.0.17628.20110 (64-bit)
- Operating System: Windows 11 Pro 23H2 Build 22631.3672
- Browser (if using Office on the web): n/a

<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://github.com/OfficeDev/office-js/assets/7528452/ffad7b9f-e467-43de-a1b2-ead3f4c8f3f0"/>
  <img width="1512" alt="Screenshot of Excel with a code editor" src="https://github.com/OfficeDev/office-js/assets/7528452/426bf2fb-77d6-46ad-9b04-0cccaad210e4"/>
</picture>

**Comment by shanshanzheng-dev** [comment]
Hi @niquenen Thanks for the detailed information. We have created a bug <#9029924> to triage this issue. Thanks.

**Comment by alan-artemest** [comment]
same issue here. Any suggestion on a workaround for it?

**Comment by shanshanzheng-dev** [comment]
Hi @niquenen @alan-artemest This appears to be an issue with the CORS policy of the target website.The workaround is to specify no-cors in the fetch request, e.g.:
async function main(workbook: ExcelScript.Workbook) {
    try {
      const response = await fetch("https://www.google.com", {
        mode: "no-cors"
      })
    }
    catch (error) {
        console.log(error);
    }
}
Could you try this workaround for it? Thanks.

**Comment by niquenen** [comment]
Hi @shanshanzheng-dev, I forgot to add no cors behaviour in the first message of this issue but the response is either empty (because this mode give an [opaque response](https://fetch.spec.whatwg.org/#concept-filtered-response-opaque)) or a type error is thrown.

### Google

```ts
async function main(
    workbook: ExcelScript.Workbook
): Promise<void> {
    try {
        const response = await fetch(
            'https://www.google.com',
            {mode: 'no-cors'}
        );
        console.log(response.status);
        console.log(await response.text());
    }
    catch (error) {
        console.log(error);
    }
}
```

<img width="1514" alt="Screenshot of Excel" src="https://github.com/user-attachments/assets/c46b8dcf-8b26-473f-9da2-4e45f2ac3027">

### Own service

```ts
async function main(workbook: ExcelScript.Workbook): Promise<void>
{
    try {
        const response = await fetch(
            'https://xxxxxxxxxxxxxxxxxxxxxxx.azurewebsites.net/version',
            {mode: 'no-cors'}
        );
        console.log(response.status);
        console.log(await response.json());
    }
    catch (error) {
        console.log(error);
    }
}
```

<img width="1514" alt="Screenshot of Excel" src="https://github.com/user-attachments/assets/3c7144d3-f5f8-4878-b399-0cd3242c49db">

Origin `*` is allowed on this Azure resource (see: [enable and configure CORS](https://learn.microsoft.com/en-us/azure/container-apps/cors?tabs=arm&pivots=azure-portal#enable-and-configure-cors)). The response can be retrieved, `await` is missing before the response in the screenshot.

<img width="1514" alt="Screenshot of Excel" src="https://github.com/user-attachments/assets/b90f9d2b-19ec-4a2e-9916-8ab6fbc3cf40">

**Comment by niquenen** [comment]
@shanshanzheng-dev, @alan-artemest,

You can find below a demo with [Cloudflare Workers](https://developers.cloudflare.com/workers/) to play with the CORS policy, based on [CORS header proxy](https://developers.cloudflare.com/workers/examples/cors-header-proxy/) example.

If an API can't be reach due to the CORS policy, a solution is to use a proxy to make the request and redirect the response.

### CORS (preflight only)

Editor mode in Cloudflare with log of a request.

![Editor mode on Cloudflare Worker](https://github.com/user-attachments/assets/98dbf822-4ab2-4e4b-a840-9d73e1a710a5)

From Excel with the Fetch API.

<img width="1624" alt="Excel Office Script" src="https://github.com/user-attachments/assets/ca5505c4-f971-472f-930d-940affe32536">

### CORS

Editor mode in Cloudflare with log of a request.

<img width="2672" alt="Editor mode on Cloudflare Worker" src="https://github.com/user-attachments/assets/6fe98f6a-5cb7-4d02-98cc-4346e15fd6f1">

From Excel with the Fetch API.

<img width="1624" alt="Excel Office Script" src="https://github.com/user-attachments/assets/def357b7-8510-4560-bc5c-05c0af10bf8c">

Source used for the demo:

```js
export default {
  async fetch(request) {
    const corsHeaders = {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET,HEAD,POST,OPTIONS',
      'Access-Control-Max-Age': '86400'
    };

    async function handleOptions(request) {
      if (
        request.headers.get('Origin') !== null
        && request.headers.get('Access-Control-Request-Method') !== null
        && request.headers.get('Access-Control-Request-Headers') !== null
      ) {
        // Handle CORS preflight requests.
        return new Response(
          null,
          {
            headers: {
              ...corsHeaders,
              'Access-Control-Allow-Headers': request.headers.get(
                'Access-Control-Request-Headers'
              )
            }
          }
        );
      }
      // Handle standard OPTIONS request.
      return new Response(
        null,
        {
          headers: {
            Allow: 'GET, HEAD, POST, OPTIONS'
          }
        }
      );
    }

    if (request.method === 'OPTIONS') {
      // Handle CORS preflight requests
      return handleOptions(request);
    }
    else if (
      request.method === 'GET'
      || request.method === 'HEAD'
      || request.method === 'POST'
    ) {
      return Response.json({foo: 0}, {headers: {...corsHeaders}});
    }
    return new Response(
      null,
      {
        status: 405,
        statusText: 'Method Not Allowed'
      }
    );
  }
};
```

**Comment by gergzk** [comment]
Hi @niquenen - the behavior you describe can be equally reproduced from a browser dev tools window in the console so I'm going to close this issue since it's not specific to Office Scripts, but just appears to be how the various services you are trying to reach are configured. For example, if you fetch the following urls:

fetch("https://jsonplaceholder.typicode.com/posts/1"); // works, you get back some json
fetch("https://google.com"); // TypeError
fetch("https://google.com", { mode: 'no-cors' }); // works, but no response data
fetch("https://www.google.com", { mode: 'no-cors' }); // works, you get back the google home page

**Comment by lamb-russell** [comment]
I'm having this same issue.  My backend api service is running locally with cors policy set to accept all requests yet i get this mysterious TypeError when i call form the Excel add-in.  I can call the API from a test harness javascript file on a dummy html page, curl, and in the browser.  It's only the Excel add in that gives me issues.
