### ISSUE TITLE
Could you provide me with more information on how to clear the cache for Office "new Outlook"?

### ISSUE THREAD

**Issue by t-ariyoshi30907** [OfficeDev/office-js#4513]
Hello,

I am creating and selling an Outlook JavaScript add-in. I have a question about the method for clearing the cache that is published on the following page:

After deploying a new program for the Office add-in to Azure Cloud Blob Storage, some HTML files did not update, causing malfunctions. As a result, we're looking for a way to clear the Office add-in cache.

On the following page, it's written that to manually clear the cache, you need to delete the following folder:

office-js-docs-pr/clear-cache.md at main · OfficeDev/office-js-docs-pr](https://github.com/OfficeDev/office-js-docs-pr/blob/main/docs/testing/clear-cache.md)

Deleting this folder ensured that the latest program was loaded in the traditional Outlook, resolving the issue. However, when testing it in the "new Outlook," the issue was not resolved.

Since no data is being added to the wef folder when running the add-in in the "new Outlook," we suspect that there might be other folders retaining the cache.

Could you please provide instructions on how to clear the Office add-in cache in the "new Outlook"?

**Comment by AlexJerabek** [comment]
Thanks for raising this issue @t-ariyoshi30907. You can manually remove Outlook add-ins by following these steps: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#manually-clear-the-cache-in-outlook. Removing the add-in then re-sideloading it should refresh all the files your add-in uses.

Please let me know if that fixes your issue.

**Comment by t-ariyoshi30907** [comment]
@AlexJerabek 
Thank you for your response.

However, there is an issue with the cache clearance method you provided. The add-in developed by our company is installed and used in customers' tenants through the Microsoft 365 admin center.

According to your suggested procedure, we would have to repeatedly remove and redeploy the add-in in the customer's environment with each deployment, which would negatively impact the customer.

Our goal is to find a recovery method that ensures the latest index.html is loaded.
Is there a way to clear the old cache data without removing and redeploying the add-in? 

Additionally, I have another question. My add-in temporarily stores product policy information in local storage, 
which is reused during various operations. for example) localStorage.setItem(); localStorage.getItem();
Since this local storage data might be related to the issues we're encountering, we would like to clear it.

In the case of Outlook for Windows, where is the local storage data saved within the Windows OS?

**Comment by AlexJerabek** [comment]
Ah, I didn't realize your add-in was deployed to customers. Let me tag @exextoc to investigate this issue from the product side.

**Comment by t-ariyoshi30907** [comment]
@AlexJerabek 
Thank you for your reply. I understand.

@exextoc 
In order to use the Office add-in with the new Outlook, this issue needs to be resolved.
I apologize for the inconvenience, but could you please look into it?

**Comment by t-ariyoshi30907** [comment]
@exextoc 
It's been a while since my last post.
Could you please update me on the status of this ticket?
As this issue is affecting my client, I would appreciate your cooperation in resolving it.

**Comment by akagarwa-msft** [comment]
Cache in New Outlook can be cleared by:

1. Close New Outlook and run the following command in terminal: olk.exe -devtools . This will open DevTools along with the Outlook App.
2. Manually clear the cache as mentioned here https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/reference#manually-clear-the-browser-cache
