### ISSUE TITLE
Clear current presentation

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4515]
We are using insertSlidesFromBase64 API to insert new presentation contents into context .
Before inserting this data, need to clear context presentation. looking for API similar to 
      context.document.body.clear(); in Word office.js support.

Can you please tell me way to do this similar for excel and powerpoint?

**Comment by EsterBergen** [comment]
@ishanig11 - there is no Clear context api in PPT. However you can select the shapes and delete them from the slide to clear in powerpoint. https://learn.microsoft.com/en-us/office/dev/add-ins/powerpoint/shapes

Here is how to clear cells and ranges in excel
https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-ranges-clear-delete

Let me know if this helps!

**Comment by ishanig11** [comment]
This is useful. But that will cause performance issues.

**Comment by EsterBergen** [comment]
You can also delete the slide and add a new blank slide if you're clearing the entire slide. https://learn.microsoft.com/en-us/office/dev/add-ins/powerpoint/add-slides

The ability to clear the slide in PPT would be a new feature request.  We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process.
