### ISSUE TITLE
Event trigger inside Outlook Addin when Outlook logout or close or addin close

### ISSUE THREAD

**Issue by iraviguggilam** [OfficeDev/office-js#4516]
We are using SSO for our ADDIN in outlook using OfficeRuntime JS. We created our own token using below steps.
step 1-> Read the Token from

`
OfficeRuntime.auth.getAccessToken({
	allowSignInPrompt: true,
})
`
step 2-> Passing the received token to our backend systems to get the new token from graph API's

step 3-> using the new token to validate the API( Application Backend API's) and renew it when it expire ( using refresh_token mechanism)

Problem is: When **Outlook Close / Addin Close / Outlook Signout** our new token ( generated by step 2) is active. So, looking for solution when **Outlook Close / Addin Close / Outlook Signout** any event trigger is available to get info inside Add-in.

**Comment by anjalitp** [comment]
Unfortunately, we do not support any events to be triggered on Outlook/ Add-in Close/ Outlook Signout. This will be considered as a new feature request.
We track Outlook add-in feature requests on our[Tech Community Page](https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Faka.ms%2FM365dev-suggestions&data=05%7C02%7CAnjali.T%40microsoft.com%7C5b4fed44194541572d9708dc80867da5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638526562347559952%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Mn1jMw%2FO5ZQzR14j0vbkJBBBWceAsPDmPiziqdnGw7M%3D&reserved=0). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
