### ISSUE TITLE
RichApi.Error: The operation failed because the source contains one or more unsupported features. Features currently unsupported on this platform are Comment, Slicer, Chart, and PivotTable. 

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4518]
We are using workbook.insertWorksheetsFromBase64 API to load excel contents. For some file getting error as :

RichApi.Error: The operation failed because the source contains one or more unsupported features. Features currently unsupported on this platform are Comment, Slicer, Chart, and PivotTable. 

Can you tell me when will this feature available? This is show stopper for us.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11, thanks for reporting this. Could you please provide us more detailed information? Such as code, manifest?

**Comment by ishanig11** [comment]
@shanshanzheng-dev : You can take any excel containing chart data. And try to load that excel using Office.js excel APIs. Excel will not load.

**Comment by shanshanzheng-dev** [comment]
Thanks @ishanig11,  I think this issue is same as https://github.com/OfficeDev/office-js/issues/4519, right? You need to load excel containing chart using chart api?

**Comment by ishanig11** [comment]
@shanshanzheng-dev : Right. Same as #4519.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11, Thanks for reporting this. We'll track your issue with https://github.com/OfficeDev/office-js/issues/4519 and we'll close this issue.
