### ISSUE TITLE
How to load Excel containing chart data using Office.js

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4519]
How to load Excel containing chart data using Office.js? workbook.insertWorksheetsFromBase64 API does not excel with chart data. Can you tell me if there is any other way to the same?

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11, I find some references: https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-charts, could you try this? Thanks.

**Comment by ishanig11** [comment]
@shanshanzheng-dev : Thank you for this link. But this link provides example of how to add chart data to excel. I am looking for API to load excel containing chart data to Online Excel using office.js.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11, thanks for reaching out. So far for Excel no direct API to load containing chart data,
 For any other new API requests, we track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there and we will triage accordingly. We value your feedback.

**Comment by ishanig11** [comment]
Is there anyway to expediate this request? As this will be blocker for our Add-in.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 Sorry, the only reference I can find is https://stackoverflow.com/questions/46146480/import-data-from-excel-and-use-in-chart-js, the answer said we can use chart.js.

**Comment by ishanig11** [comment]
@shanshanzheng-dev  but how can we combine with insert API of office.js with this chart.js? As we want to load excel in single shot.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11  We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.

**Comment by ishanig11** [comment]
@shanshanzheng-dev I dont have access to log new issue at tech community. What is process for the same?

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 You need to create an account and submit a feature request on https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform, we'll track this. Thanks.

**Comment by adrianwu8516** [comment]
Hi @ishanig11, as we saw the similar feature request post has been created in our tech community, we will close the issue.

We will keep monitor the voting numbers here -> https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/load-excel-containing-chart-data/idi-p/4160160

Thank you very much for your feature suggestion!
