### ISSUE TITLE
Set document name using office.js API

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4522]
Hi,

I am loading file in office active context application using API context.document.body.insertFileFromBase64.

After file load, want to set file name. Currently default filename get set. Refer below screenshot.
![image](https://github.com/OfficeDev/office-js/assets/157671419/59fd9171-bbbc-425d-8da0-b35ae9e4e11e)

Can you tell me how we can set file name to office applications like Word, Excel and Powerpoint?

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 May I know is this for online or desktop？

**Comment by jipyua** [comment]
hi @ishanig11 thanks for reaching out. So far for Word there is no direct API to set the file name, but if your document is a new file and hasn't be saved, then you can use the second parameter of document.save() API to provide and set a file name. See here for details: https://learn.microsoft.com/en-us/javascript/api/word/word.document?view=word-js-preview#word-word-document-save-member(1).

For any other new API requests, we track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum]( https://aka.ms/m365dev-suggestions). Please add your request there and we will triage accordingly. thanks.

**Comment by ishanig11** [comment]
@jipyua : I perform following steps:
1. Open blank document in online office
2. Load other document content into it using insertFileFromBase64 API
3. So in this case how I can change name of  document?

**Comment by ishanig11** [comment]
@jipyua : Any update on above question?

**Comment by jipyua** [comment]
@ishanig11 at this case, I am afraid so far there is no way to change the name. As mentioned earlier, that will be a new feature request. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there and we will triage accordingly. thanks.

**Comment by ishanig11** [comment]
This is really blocker feature.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 Sorry for that. We recommend you to upvote a Tech Community Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.   Thanks.
