### ISSUE TITLE
Outlook integrated spam-reporting add-in - MoreInfo tag has side effects

### ISSUE THREAD

**Issue by lmontand** [OfficeDev/office-js#4523]
# Provide required information needed to triage your issue
In the manifest file of an "integrated spam-reporting add-in", The `MoreInfo` tag has some side effects.
If not specified, the `PreProcessingDialog` and `PostProcessingDialog` `Description` texts are not displayed.
However, according to the [documentation](https://learn.microsoft.com/en-us/javascript/api/manifest/moreinfo?view=common-js-preview), it should only hide the `MoreInfoText` and `MoreInfoUrl`.

## Your Environment

* Platform: Outlook on the web (but seems to apply to all platforms)
* Host: Outlook on the web
* Office version number: -
* Operating System: Windows 11 23H2 22631.3593
* Browser (when using Office on the web): Firefox 126.0.1
 
## Expected behavior
If I do not specify the `MoreInfo` tag, I expect the `MoreInfoText` and `MoreInfoUrl` texts to be hidden, while having the `PreProcessingDialog` and `PostProcessingDialog` `Description` texts shown.

## Current behavior
When I do not specify the `MoreInfo` tag, the `PreProcessingDialog` and `PostProcessingDialog` `Description` texts are also hidden (in addition to `MoreInfoText` and `MoreInfoUrl` texts).

Dialogs with the `MoreInfo` tag:
![2024-05-29 14_34_44-Clipboard](https://github.com/OfficeDev/office-js/assets/43467580/7bfb5131-2564-4703-96cd-d785db6c0a71)
![2024-05-29 14_49_44-Clipboard](https://github.com/OfficeDev/office-js/assets/43467580/9f95d2ed-6832-48b2-9de6-1ebd5a59e402)

Dialogs without the `MoreInfo` tag:
![2024-05-29 14_51_48-Clipboard](https://github.com/OfficeDev/office-js/assets/43467580/4ea05a72-8ce1-4099-8c2b-3f1bb8e08940)
![2024-05-29 14_54_19-Clipboard](https://github.com/OfficeDev/office-js/assets/43467580/d7c67380-8cbd-4b2a-a2f5-6ef79f26a88f)

## Steps to reproduce

1. Deploy https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-spam-reporting
2. Remove the `MoreInfo` tag at https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/outlook-spam-reporting/manifest-localhost.xml#L92 and the related string (MoreInfo.Label) and url (MoreInfo.Url).
3. Open Outlook Desktop or Outlook Web (both platforms are affected)
4. Click on the plugin

## Context
We're trying to replace our existing VSTO spam-reporting addin with a new one that would work in the new Outlook

The new plugin works correctly, we do not want to display the `MoreInfo` texts, while still having the pre- and post-processing dialogs descriptions shown.

**Comment by anjalitp** [comment]
This issue has already been reported here https://github.com/OfficeDev/office-js/issues/4521 .
Please track the same for more updates. Closing this a duplicate.
