### ISSUE TITLE
In new outlook desktop , office.js doesn't contain the field "dateTimeSent" for mail. However it's available in Office on the web.

### ISSUE THREAD

**Issue by sachidanand-cloudextend** [OfficeDev/office-js#4524]
Hi Team, 
In new outlook desktop , Office.js doesn't contain the field "dateTimeSent" for mail. However it's available in Office on the web.

* Platform: Outlook For Mac
* Host : Outlook
* Office version number: Version 16.85.1
* Operating System: Mac
 
## Expected behavior
Office.js Mailbox object should contain the property "dateTimeSent" just like  office for web. The below object Mailbox["officeAppContext"].appOM.initialData.dateTimeSent;

## Current behavior
Mailbox["officeAppContext"].appOM.initialData   doesn't contain property "dateTimeSent".

## Steps to reproduce
We can just try to  read the details of the following object:
  Mailbox["officeAppContext"].appOM.initialData.

Could you please help us in resolving this issue.

**Comment by anjalitp** [comment]
The `Office.context.mailbox.initialData` is not designed for public use. It's an internal attribute, and your add-in should not depend on it.  Officially supported date properties provided by our API are:
- `Office.context.mailbox.item.dateTimeCreated`
- `Office.context.mailbox.item.dateTimeModified`

**Comment by sachidanand-cloudextend** [comment]
Hi Team, 
Thanks for the response. 
But `dateTimeCreated` and `dateTimeModified ` isn't the correct property to use,  when I have saved the mail as draft for sometime and send later.

Let's say , I have saved a mail as draft and kept it for one month , after one month when I send the mail, `dateTimeCreated` will be one month ago, but `dateTimeSent` would be today, so `dateTimeCreated` doesn't give us the correct date when mail was sent. 

For example: Today I saved a mail as draft and sent it after sometime. Here is the response from graph api. 
Please have a look at the properties `createdDateTime` and `sentDateTime`
<img width="527" alt="Screenshot 2024-05-30 at 11 54 11 AM" src="https://github.com/OfficeDev/office-js/assets/114073700/0b1e982e-137e-4c6c-80d8-690e0653dd9b">

**Comment by anjalitp** [comment]
@sachidanand-cloudextend  Currently, there isn't a direct API to retrieve the dateTimeSent property. However, you can utilize the Office.context.mailbox.makeEwsRequestAsync API as a workaround to obtain this information. Please refer the [documentation](https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-1.5&preserve-view=true#outlook-office-mailbox-makeewsrequestasync-member(1)) for more details on this API.

Also, we track Outlook add-in feature requests on our [Tech Community Page](https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Faka.ms%2FM365dev-suggestions&data=05%7C02%7CAnjali.T%40microsoft.com%7C49db3a7e1dd5448e105408dc80d69c09%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638526906512990022%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=WjWUy%2BjJrLLTKagSqGxY2QZ6446pfI5ciJ1%2FeKaK6LY%3D&reserved=0). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
