### ISSUE TITLE
Long time requires to load taskpane when sharedruntime is enabled

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4532]
I have enabled shared runtime for Add-in using following setting in manifest file.
		<Sets DefaultMinVersion="1.1">
			<Set Name="SharedRuntime" MinVersion="1.1"/>
		</Sets>

But after this, taskpane loading is taking time.

Can you tell me if need to pass any additional parameter to resolve this performance issue?

**Comment by slabereemsft** [comment]
Hi Ishanig11  - I'm not aware of anything off the top of my head that would be causing a performance issue.  We'll need more details on the scenario where it is happening.  The biggest questions to understand is whether the time is being spent loading the webpage (ie. where your javascript is running) vs whether native code is running where something is causing Office to take more time.  

Does the performance show up equally bad on Office on the Web/Office for Windows/Mac?
