### ISSUE TITLE
Question: Impact of EWS Retirement on Outlook Web Add-ins for Exchange Online

### ISSUE THREAD

**Issue by t-miyake** [OfficeDev/office-js#4533]
Please excuse me for posting a question instead of an issue.

It has been announced that Exchange Web Services in Exchange Online will be retired, and starting October 1, 2026, EWS requests from non-Microsoft apps to Exchange Online will be blocked.

Could you please confirm if this will also affect Office Web Add-ins for Outlook on the web? Specifically, does this mean that methods such as Office.context.mailbox.makeEwsRequestAsync will no longer be usable with Exchange Online after October 1, 2026?

I am asking here because I could not find any clear statements regarding this matter elsewhere.

Thank you for your assistance.

**Comment by akagarwa-msft** [comment]
Thanks for raising the concern. Deprecation of EWS will impact "Office.context.mailbox.makeEwsRequestAsync" and the way forward will be to use the Graph Token and the Graph API's.

**Comment by t-miyake** [comment]
@akagarwa-msft Thank you for the clarification!
I appreciate your prompt response and guidance on this matter.
