### ISSUE TITLE
Outlook on send web add-in doesn't get loaded on MAC Legacy Outlook client (Version 16.85.2 (24052614)) 

### ISSUE THREAD

**Issue by pza-dev-brcm** [OfficeDev/office-js#4535]
We are working on "outlook on send web add-in" where we are dealing with sensitivity labels.
We are using <Set Name="Mailbox" MinVersion="1.13" /> in manifest file as per sensitivity labels requirement.

This is working correctly on Windows Outlook Client, Windows OWA and MAC New Outlook mode and MAC OWA as well.

Strangely add-in is not getting loaded on MAC Legacy client application (Version 16.85.2 (24052614)).

As per Microsoft documentation for using sensitivity labels Version 16.77.816.0 or later is supported.
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sensitivity-label#supported-clients-and-platforms

Can you please confirm if mentioned version is supported ? 

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: Legacy Outlook
Office version number:
Microsoft® Outlook for Mac | Version 16.85.2 (24052614) | Licence: Microsoft 365 Subscription
Operating System: macOS Sonoma Version 14.4.1 (23E224)
Browser (if using Office on the web):N/A

**Comment by anjalitp** [comment]
@pza-dev-brcm Classic Outlook Mac only supports Add-ins up to API Requirement Set version 1.8.
Sensitivity label belongs to API Set 1.13 and is supported only in New Outlook Mac. 
The supported client details are documented[ here](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/outlook-api-requirement-sets?view=common-js-preview&tabs=jsonmanifest#outlook-client-support).

**Comment by pza-dev-brcm** [comment]
Hi @anjalitp,
Thank you for providing the information and the link for supported API requirement sets.

Do we have any timeline for supporting 1.13 in classic outlook mode ?

**Comment by akagarwa-msft** [comment]
There is no plan to support the API requirement set 1.9 or later on classic Outlook.
