### ISSUE TITLE
InternalError with Body#getAsync in launch event

### ISSUE THREAD

**Issue by Sirius902** [OfficeDev/office-js#4536]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2406 Build 16.0.17723.20000) 64-bit
* Operating System: Windows 11 Pro 22631.3593
* Browser (if using Office on the web): N/A
 
## Expected behavior
Calling `Office.context.mailbox.item.body.getAsync` inside a launch event should not fail on the second triggering of that event.

In the case of the example, the following output should be contained in the `OfficeAddins.log.txt` file after switching between two emails with the `CustomHeader` header.
```
5/31/2024 14:50:44	Verbose	Runtime	[Console] [Log] onMessageReadWithCustomHeader(): entered!		
5/31/2024 14:50:44	Verbose	Runtime	[Console] [Log] MailboxHostExecuteApi invoked!		
5/31/2024 14:50:44	Verbose	Runtime	[Console] [Log] RunLaunchEventHandlerFunctionWithData was invoked with funcName = onMessageReadWithCustomHeader		
5/31/2024 14:50:44	Verbose	Runtime	[Console] [Log] Body length: 1339		
5/31/2024 14:50:44	Verbose	Runtime	[Console] [Log] LaunchEventObj.completed was invoked: 18		
5/31/2024 14:50:44	Verbose	Runtime	[Console] [Log] Event completed message sent to host!
5/31/2024 14:50:46	Verbose	Runtime	[Console] [Log] onMessageReadWithCustomHeader(): entered!		
5/31/2024 14:50:46	Verbose	Runtime	[Console] [Log] MailboxHostExecuteApi invoked!		
5/31/2024 14:50:46	Verbose	Runtime	[Console] [Log] RunLaunchEventHandlerFunctionWithData was invoked with funcName = onMessageReadWithCustomHeader		
5/31/2024 14:50:46	Verbose	Runtime	[Console] [Log] Body length: 16803
5/31/2024 14:50:46	Verbose	Runtime	[Console] [Log] LaunchEventObj.completed was invoked: 18		
5/31/2024 14:50:46	Verbose	Runtime	[Console] [Log] Event completed message sent to host!
```

## Current behavior

When using the `OnMessageReadWithCustomHeader` launch event with a function that calls `Office.context.mailbox.item.body.getAsync` it will succeed upon the first triggering of the event but the second time it will fail with `InternalError` code `5001`.

In the case of the example, the following output is found in the `OfficeAddins.log.txt` file after switching between two emails with the `CustomHeader` header.
```
5/31/2024 14:50:44	Verbose	Runtime	[Console] [Log] onMessageReadWithCustomHeader(): entered!		
5/31/2024 14:50:44	Verbose	Runtime	[Console] [Log] MailboxHostExecuteApi invoked!		
5/31/2024 14:50:44	Verbose	Runtime	[Console] [Log] RunLaunchEventHandlerFunctionWithData was invoked with funcName = onMessageReadWithCustomHeader		
5/31/2024 14:50:44	Verbose	Runtime	[Console] [Log] Body length: 1339		
5/31/2024 14:50:44	Verbose	Runtime	[Console] [Log] LaunchEventObj.completed was invoked: 18		
5/31/2024 14:50:44	Verbose	Runtime	[Console] [Log] Event completed message sent to host!
5/31/2024 14:50:46	Verbose	Runtime	[Console] [Log] onMessageReadWithCustomHeader(): entered!		
5/31/2024 14:50:46	Verbose	Runtime	[Console] [Log] MailboxHostExecuteApi invoked!		
5/31/2024 14:50:46	Verbose	Runtime	[Console] [Log] RunLaunchEventHandlerFunctionWithData was invoked with funcName = onMessageReadWithCustomHeader		
...
5/31/2024 14:50:46	Verbose	Runtime	[Console] [Log] Failed to get body: name="InternalError", code="5001", message="The operation failed."		
5/31/2024 14:50:46	Verbose	Runtime	[Console] [Log] LaunchEventObj.completed was invoked: 18		
...
5/31/2024 14:50:46	Verbose	Runtime	[Console] [Log] Event completed message sent to host!
```

## Steps to reproduce

1. Switch to the Outlook Beta Channel.
2. Start with the `outlook-encrypt-attachments` sample at https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-encrypt-attachments.
3. Add the following launch event within the `LaunchEvents` tag inside `manifest-localhost.xml`, where `CustomHeader` is replaced with the desired custom header.
```xml
<LaunchEvent Type="OnMessageReadWithCustomHeader" HeaderName="CustomHeader" FunctionName="onMessageReadWithCustomHeader" />
```
4. Modify `commands.js` to contain the following handler for the declared launch event.
```js
function onMessageReadWithCustomHeader(event) {
  console.log(`onMessageReadWithCustomHeader(): entered!`);
  Office.context.mailbox.item.body.getAsync(Office.CoercionType.Html, function (asyncResult) {
    if (asyncResult.status === Office.AsyncResultStatus.Failed) {
      const err = asyncResult.error;
      console.error(`Failed to get body: name="${err.name}", code="${err.code}", message="${err.message}"`);
    } else {
      console.log(`Body length: ${asyncResult.value.length}`);
    }

    event.completed();
  });
}
Office.actions.associate("onMessageReadWithCustomHeader", onMessageReadWithCustomHeader);

```
5. Follow the instructions in the sample repo to sideload `manifest-localhost.xml`.
6. Enable runtime logging for Office Addins.
7. Switch between reading two emails that contain the custom header setup in step 3.
8. Observe the logged output from the addin in `%localappdata%\Temp\OfficeAddins.log.txt`.

## Context

This addin requires accessing the body of a message when the user reads one that has a particular custom header. Only being able to do this once isn't ideal.

**Comment by ztcdsb** [comment]
@Sirius902 Thanks for reporting the issue regarding AutoRunRead. The fix is on its way and will be available to test shortly.

**Comment by muhammadarmaghan** [comment]
### Environment
Windows **11 pro**
Outlook classic version: **Version 2507 Build 16.0.19029.20136 (64-bit)**
Current Channel: **Preview**
Mailbox version: **1.15**

### manifest.xml
```
<ExtensionPoint xsi:type="LaunchEvent">
  <LaunchEvents>
        <LaunchEvent Type="OnMessageReadWithCustomHeader" FunctionName="OnMessageReadWithCustomHeaderHandler"/>
  </LaunchEvents>
  <SourceLocation resid="commandsUrl"/>
</ExtensionPoint>
```

**Getting the following error when starting add-in**

```
--Error sideloading!--
Error: Error: Command failed: npx @microsoft/teamsapp-cli install --xml-path "C:\Users\think\OneDrive\Desktop\addin\manifest.xml" --interactive false

 Error: M365.PackageServiceError: Request failed with status code 400 (tracingId: 22fde8f866f550-b6851c2e106f0c1a-01) BadRequest: Sideloading rejected by Exchange
Error: Unable to start debugging.
Error: Unable to sideload the Office Add-in.

(×) Error: M365.PackageServiceError: Request failed with status code 400 (tracingId:22fde8f866f550-b6851c2e106f0c1a-01) BadRequest: Sideloading rejected by Exchange

```
