### ISSUE TITLE
displayMessageFormAsync opens msg in Outlook for web, but not in desktop app

### ISSUE THREAD

**Issue by ccfontes** [OfficeDev/office-js#4537]
Cannot open message in new window using `displayMessageFormAsync` in Outlook for desktop, but can do in the web version.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.85
* Operating System: macOS Sonoma 14.4.1
 
## Expected behavior
Should open message in new window using `displayMessageFormAsync` in Outlook for desktop, just like in the web version.

## Current behavior
When trying to open message in new window using `displayMessageFormAsync` in Outlook for desktop, no new window is opened, and no error is printed in the console.

## Steps to reproduce
1. Fetch message id using graph API
2. Convert message id to EWS format using the `convertToEwsId` method.
3. Open message using `displayMessageFormAsync` with the EWS message id as parameter.

This is the code I'm using:
```cljs
(defn open-email [itemId]
  (.displayMessageFormAsync
    js/Office.context.mailbox
    (.convertToEwsId js/Office.context.mailbox itemId js/Office.MailboxEnums.RestVersion.v2_0)
    (fn [result]
      (when-not (.-status result)
        (println "Failed to send email. Error: " (.-error result))))))
```
`itemId` is the `id` field of a message fetched using Graph API.
Message is an email.

Thanks! 🙇‍♂️

**Comment by akagarwa-msft** [comment]
Can you try your scenario with script lab Add-in sample? Also, what happens if you use displayMessageFormAsync API with the itemId fetched using itemId office js API? Does it work?

**Comment by ccfontes** [comment]
Tried the scenario using script lab Add-in, in Outlook for desktop. The same issue happens, but this time I logged the error correctly:
<img width="989" alt="Screenshot 2024-06-13 at 15 28 22" src="https://github.com/OfficeDev/office-js/assets/2167559/5ed4558f-480f-4fc0-8ac8-52536d52997a">

> Also, what happens if you use displayMessageFormAsync API with the itemId fetched using itemId office js API?

If you mean using this `Office.context.mailbox.item.itemId`, yes it works. Unfortunately in the problem scenario, the item Id does not necessarily correspond to the selected message in Outlook UI - it can be any message in all mailboxes.

Message id example in Outlook for desktop:
```
[Log] Rest item Id AAkALgAAAAAAHYQDEapmEc2byACqAC-EWg0AMhi5ULOYEUqlx5SG0i8znQAAfAaOggAA
[Log] EWS item Id  AAkALgAAAAAAHYQDEapmEc2byACqAC/EWg0AMhi5ULOYEUqlx5SG0i8znQAAfAaOggAA
```

A reminder that a window with the message is opened in Outlook web version, without issues.

**Comment by ccfontes** [comment]
Anyone able to reproduce this issue? Thanks.

**Comment by Swathy-Mothilal** [comment]
@ccfontes Unfortunately, we are unable to reproduce the issue. We can open the message using both EWS and REST IDs. Could you please share the manifest you are using when you experience the issue? This will help us debug more effectively

**Comment by ccfontes** [comment]
@Swathy-Mothilal, thank you for looking into this issue, and apologies for the frustration it might be causing.

Before considering sharing the manifest which features some sensitive data, could you please confirm that you tried to repro the issue using Mac + Outlook for Desktop? Thank you!

**Comment by Swathy-Mothilal** [comment]
@ccfontes Yes, we attempted to reproduce the issue on both Mac and Outlook for Desktop. Could you please share a lightweight manifest that only includes the issue, or upload the manifest to a private repository and grant us access? 
A repro video also would be really helpful.

**Comment by ccfontes** [comment]
@Swathy-Mothilal Thanks for your confirmation.

I'm confused by the request for a lightweight manifest that only includes the issue, as I have mentioned previously that I called `displayMessageFormAsync` from within script lab add-in in Outlook for Desktop (Mac), and failed. So the issue is unrelated to my specific app, including its manifest.

I will try again within script lab add-in, because it was a long time ago, and I may have missed something. Also will try the same in Office Web to be sure it's the right test. If the issue remains, I will show the snippet, and a demo video.
