### ISSUE TITLE
Word online create document page redirecting to outage.html

### ISSUE THREAD

**Issue by kalvenschraut** [OfficeDev/office-js#454]
## Expected Behavior
For a new document to be opened when createDocument().open() is called in word online.
My add-in works as intended in the download office 365 word application.

## Current Behavior
Receive a 302 redirect to a outage.html page. 

## Steps to Reproduce, or Live Example
run in word online
``` javascript
Word.run(context => {
    context.application.createDocument().open();
    return context.sync();
})
```
## Context
Unable to open new documents prevents my add-in from functioning in word online. My add-in allows users to download a template which is then filled out with data from my company's API. From my research createDocument() is the only method of loading a template and preserving the styling and headers/footers which is essential in my add-in.

## Your Environment
Chrome 73 using word in office online
## Useful logs
![2019-04-02 (2)](https://user-images.githubusercontent.com/30308012/55382375-1cdffd80-54eb-11e9-89a7-7b29455f75b4.png)

**Comment by jipyua** [comment]
I tried on http://onedrive.live.com, but this API is working perfectly. Could you please provide more information about your repro steps? On which site are you calling this API?

**Comment by kalvenschraut** [comment]
Looks like my login redirects me to my companies sharepoint site. https://rtvision-my.sharepoint.com

As for my repo setup it is a vuejs application built via webpack. Not much special going on there that I can think of, using core-js and babel to provide polyfills for supporting IE 11. Running the site off a webpack dev server on my local workstation on a specific port. The webpack dev server has https enabled with a valid cert.

**Comment by jipyua** [comment]
I can't log in to your site, Can you first try whether you can create new document from UI on your site. That's open a new word online document and click File->New, then choose a template to create a file.

**Comment by kalvenschraut** [comment]
The problem is definitely on our end somewhere I am going to have to talk with my system admin. I don't see file -> new, but I can create and save files from clicking "starting a new file" at https://www.office.com/launch/word?ui=en-US&rs=US&auth=2 part but not in word itself. I tried using my personal account for this and my add-in works great. 

Going to close this as it seems to not be a bug in the repo. Thanks pointing me in the right direction!
