### ISSUE TITLE
Debugging an add-in installed in the new Outlook on Windows desktop

### ISSUE THREAD

**Issue by jackdawHome** [OfficeDev/office-js#4541]
> Note: This repo is only for questions related to its samples. If you have questions about how to use office.js or the Office developer platform, please post your question on https://stackoverflow.com. Tag your question with office-js or outlook-web-addins

**Question**

I switch Windows desktop Outlook to the "New Outlook" mode. After that I could not debug my add-in using Visual Studio Code and Microsoft Edge WebView2 (Chromium-based). The manifest is sideloaded, dev server is started, Outlook is started, but debugger is not connected and after a while the following message is coming: "Cannot connect to the target at localhost:9229: Could not connect to debug target at http://localhost:9229/: could not find debuggable target". I downloaded Samples/outlook-set-signature progect and tried to run  "Outlook Desktop (Edge Chromium)" with the same result. Is it possible to use any tool other then Microsoft Edge DevTools to debug Outlook addin in the New Outlook?

**Comment by AlexJerabek** [comment]
@samantharamon, could you please investigate?

**Comment by nikitamittal2501** [comment]
@jackdawHome Glad that you are following the guideline as shared here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/one-outlook#debug-your-add-in

Did you close Outlook before running the cmdlet in command prompt?

**Comment by cut2run** [comment]
Maybe it wasn't clear what are we trying to ask. I will try to rephrase the question. We are able to [debug with Visual Studio Code](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/debug-desktop-using-edge-chromium) taskpane add-in running under standard Outlook desktop for Windows with the following launch configuration:

``` JSON
{
      "name": "Outlook Desktop (Edge Chromium)",
      "type": "pwa-msedge",
      "request": "attach",
      "useWebView": true,
      "port": 9229,
      "timeout": 600000,
      "webRoot": "${workspaceFolder}",
      "preLaunchTask": "Debug: Outlook Desktop",
      "postDebugTask": "Stop Debug"
    }
```
It works perfectly. We are able to [debug with VS Code event-based add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/debug-autolaunch?tabs=windows) as well with direct debugging configuration:
``` JSON
{
      "name": "Direct Debugging",
      "type": "node",
      "request": "attach",
      "port": 9223,
      "timeout": 600000,
      "trace": true
    }
```
When we switch to the new UI Outlook desktop for Windows we cannot debug the add-in from VS Code. We have tried multiple different configurations with no success. The question: is it possible to debug the add-in from VS Code running under new UI Outlook desktop for Windows? Would you share the launch configuration for it? If this is not possible, do you have a plan to add the ability to use IDE of choice?

Please be aware we read the [debug instructions that describe the use of devtools](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/one-outlook#debug-your-add-in) to debug desktop Outlook with new UI. This is not the matter of the question. We were able to debug it with devtools, we just would like to use IDE as for any other Outlook clients.

**Comment by akshayta23** [comment]
Thanks for the details @cut2run At present the recommended path is to debug using devtools for Outlook Desktop with the new UI. https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/one-outlook#debug-your-add-in 
We will keep the dev community updated once we have closed on the plan to allow the use of other IDEs for the New Outlook on Windows.
