### ISSUE TITLE
Recieving Empty Content  instead of base64 when trying to fetch attachment content using office js(Office.context.mailbox.item.getAttachmentContentAsync)

### ISSUE THREAD

**Issue by soumyamondal-accenture** [OfficeDev/office-js#4544]
We are developing an Outlook Addin using Smart Alert of Office JS, where We are trying to fetch base64 attachment content using athe attachment id as a user add's the attachment  to the compose window.
We notice we are getting content as blank instead of the proper base64 format.

![image](https://github.com/OfficeDev/office-js/assets/150261970/afbe1cbc-8a18-456a-a773-752cf50887c9)
we get the attachmen id using  getAttachmentsAsync which we feed to (Office.context.mailbox.item.getAttachmentContentAsync) for getting the attachment  content in base64 format, which we utilise down the line. 

Please let us know how to resolve the issue.

**Comment by akagarwa-msft** [comment]
We are not able to repro the issue at our end. Please mention:
1. Which platform you are facing the issue on?
2. What kind of attachment you are trying?
3. Can you share the repro steps and the video of the issue you are referring to.
