### ISSUE TITLE
Addin does not appear in admin managed tab for some users in excel online 

### ISSUE THREAD

**Issue by Nikodem98** [OfficeDev/office-js#4545]
Addin that is deployed using  integrated apps in admin center is not visible for some users on excel online in chrome, but every thing works well in incognito mode, other browsers or desktop version (Mac and windows).

**Comment by AlexJerabek** [comment]
Thanks for reporting this @Nikodem98.

@AkhileshShah-MS, could you please investigate?

**Comment by ajnavsun1806** [comment]
@Nikodem98 Please open an incident via customer support. We would require tenant details and fiddler trace to debug this issue further.

**Comment by AkhileshShah-MS** [comment]
Resolving this issue as it needs to be taken via other channel.
