### ISSUE TITLE
wrong attachment base64 content  getting fetched  via Office js (Office.context.mailbox.item.getAttachmentContentAsync)

### ISSUE THREAD

**Issue by soumyamondal-accenture** [OfficeDev/office-js#4546]
We are developing an outlook web addin using office js Smart alert template.
Lets assume i am adding 2 attachments to my mail draft ,  for the first attachment the content is getting extracted properly, for the second attachment the content fetched is  that of the first atatchment and the sizes are same, which is incorrect.
This behavior is not limited to count of 2 attachments or same file extenstions.
![image](https://github.com/OfficeDev/office-js/assets/150261970/e186ff9e-9a5a-450d-860d-b52dbb094749)
![image](https://github.com/OfficeDev/office-js/assets/150261970/49129da6-ebd9-4376-a87f-63d247632129)

We have concluded abive the issue by decoding  the base64 contents to theri respective file.

we get the attachment id using getAttachmentsAsync which we feed to (Office.context.mailbox.item.getAttachmentContentAsync) for getting the attachment content in base64 format, which we utilise down the line.

Please let us know how to resolve the issue.

**Comment by akagarwa-msft** [comment]
We are not able to repro the issue at our end. Please mention:
1. Which platform you are facing the issue on?
2. What kind of attachment you are trying?
3. Can you share the repro steps and the video of the issue you are referring to.
