### ISSUE TITLE
IOS Outlook not showing add-in button

### ISSUE THREAD

**Issue by enzo-billis** [OfficeDev/office-js#4548]
# Provide required information needed to triage your issue

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Iphone 12 Outlook 4.2420.0

## Expected behavior
Add-in should be visible and usable on Outlook application

## Current behavior
The button of the add-in is not visible even if the manifest has been installed. It's working nicely on Web.
![image](https://github.com/OfficeDev/office-js/assets/171045124/375d7c6b-c7f7-430c-a97b-05ed2d154678)
![image](https://github.com/OfficeDev/office-js/assets/171045124/efc987f0-d371-44fc-9bb5-cffb496c5f49)

I use an XML manifest that is working nice on web when installed manually. On the application it seem's installed but the action button to open le pane is not visible (look at the screen shot above). I've tried with an Outlook account and a Microsoft 365 account both with the same issue.

Also, I've followed this snippet to create my manifest: https://github.com/OfficeDev/outlook-add-in-command-demo/blob/master/command-demo-manifest.xml#L978

## Steps to reproduce
Install this manifest: https://gist.github.com/enzo-billis/077aeb5ac695df511db790fe78eedc86
Open you Outlook application on IOS
The Add-in is installed but not usable.

Thanks for time

**Comment by mobisw-msft** [comment]
Hey @enzo-billis ,

The manifest seems to point to icons that do not exist. Please replace the icons in the URL with valid icons which are in the format .bmp, .gif, .exif, .jpg, .png, and .tiff as mentioned [here](https://learn.microsoft.com/en-us/partner-center/marketplace-offers/create-effective-office-store-listings#create-an-icon-for-your-add-in)

We can confirm that the extensions are showing up when the icon files are replaced.

**Comment by enzo-billis** [comment]
Hello @mobisw-msft 
It's work ! Thanks for you help. 
Thanks again

**Comment by mobisw-msft** [comment]
Closing this thread since your query has been answered.
