### ISSUE TITLE
Unable to work with PowerPoint Shapes giving errors

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js#4551]
I am trying to use script lab in powerpoint desktop and it's giving me errors on desktop when I tried to do something With Shapes but on web it is working correctly Please check out what is issue with PowerPoint desktop shapes thanks

![image](https://github.com/OfficeDev/office-js/assets/134502135/a816cdc4-c3fb-461a-96c4-f7c82647cd26)

**Comment by akrantz** [comment]
@junaid042 I haven't seen this myself but would like to see if I can reproduce it. Can you share the steps you're doing with the code sample? Were there any changes to the code sample? 

Also, close and restart PowerPoint, reproduce the problem, then go to Help, Feedback and report the problem. That will provide more information that we can use to understand the issue.

![image](https://github.com/OfficeDev/office-js/assets/741153/a27b788b-9529-4b69-b64e-67fd397fe8a6)

**Comment by junaid042** [comment]
@akrantz I am using code from Script Lab add-in.

**Comment by akrantz** [comment]
@junaid042 That's good to know but I also need to know more about what you're doing in PowerPoint as well. Were you able to submit feedback?

**Comment by junaid042** [comment]
@akrantz @wamaina @EsterBergen this error was because of my PowerPoint version is not supported.

**Comment by EsterBergen** [comment]
@junaid042 - what ppt version are you currently running?

**Comment by junaid042** [comment]
@EsterBergen this version
![image](https://github.com/OfficeDev/office-js/assets/134502135/5a48d71b-8967-416d-a4b6-c62aaf8150fb)
