### ISSUE TITLE
footnote is not working in word

### ISSUE THREAD

**Issue by adeelumarit** [OfficeDev/office-js#4553]
I am trying to add footnote in word but its giving error
I am trying scriptlab sample but its giving error

![image](https://github.com/OfficeDev/office-js/assets/149220630/482f4d9d-04c5-44cc-9f7c-9355f68dbfc2)

  this is my code
         
           async function insertFootnote() {
              try {
               // Sets a footnote on the selected content.
                  await Word.run(async (context) => {
                  const text = "footnote content";
                  const footnote = context.document.getSelection().insertFootnote(text);
                  await context.sync();

                 console.log("Inserted footnote:", footnote);
                });
             } catch (error) {
                  console.error("Error inserting footnote:", error);
              }
          }

**Comment by adeelumarit** [comment]
Hi @shanshanzheng-dev is there any update?

**Comment by shanshanzheng-dev** [comment]
Hi @adeelumarit, Thanks for reporting. there is a code example for how to use footnote: https://learn.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#word-word-body-footnotes-member, you can try this: https://raw.githubusercontent.com/OfficeDev/office-js-snippets/prod/samples/word/50-document/manage-footnotes.yaml
It works on my side. Thanks.

**Comment by adeelumarit** [comment]
Hi @shanshanzheng-dev i have checked this is working on the web but not on desktop word addin
same code i have tried for web it works but not in desktop

**Comment by adeelumarit** [comment]
Hi @shanshanzheng-dev 

![image](https://github.com/OfficeDev/office-js/assets/149220630/34e9d94c-59fe-4bbd-97a1-a0fb165e3ad0)

geting this error while i try script lab on desktop but it is working on web

[ERROR]: Error:
{
    "stack": "RichApi.Error: NotImplemented\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:269007)\n    at i.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:333454)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:25:331517",
    "message": "NotImplemented",
    "name": "RichApi.Error",
    "code": "NotImplemented",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "NotImplemented",
        "message": "NotImplemented",
        "errorLocation": "Range.insertFootnote",
        "statement": "var insertFootnote = selection.insertFootnote(...);",
        "surroundingStatements": [
            "var root = context.root;",
            "var selection = root.getSelection();",
            "// Instantiate {selection}",
            "// >>>>>",
            "var insertFootnote = selection.insertFootnote(...);",
            "// <<<<<",
            "// Instantiate {insertFootnote}"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 400
}

**Comment by shanshanzheng-dev** [comment]
Hi @adeelumarit It still works on desktop from my side.
![image](https://github.com/OfficeDev/office-js/assets/125014206/0d1cef03-d9b2-455e-99e8-8bac7844a3f7)
This is my word version:
![image](https://github.com/OfficeDev/office-js/assets/125014206/d7e1bc50-9f69-4ec2-adb9-6e71bcc41baa)

**Comment by adeelumarit** [comment]
Hi @shanshanzheng-dev 
I have version 2108(14332.20706 click to run)
still getting same error

**Comment by jipyua** [comment]
hi @adeelumarit, thanks for letting us know this case. Footnote API is introduced in Word API requirement set 1.5 and the supported build number must be above Version 2302 (Build 16130.20332). Yours is showing a NotImplemented error which means the build doesn't cotain the API yet. Please update your office to latest M365 version and have a try. thanks.
