### ISSUE TITLE
Office.auth.getAccessToken doesn't respond to user switching accounts in Excel

### ISSUE THREAD

**Issue by CBullen2** [OfficeDev/office-js#4554]
My primary Windows account is a Microsoft personal one and I have an associated Work account that I can switch between. My Excel add-in needs to know who the user is so it can present account-specific information / access controls - my work account is allowed to access some data (through a server OBO flow) that my personal account is not.

When I start Excel, it starts as my personal account. If I open my add-in, it calls Office.auth.getAccessToken and gets the personal account token. If I then switch to my work account in the Excel title bar, the add-in continues to see me as my personal account (preventing access to my company data), until the cached token expires.

## Expected Behavior
When switching accounts in the Excel title bar, two things should happen:
1. The cached access token should be thrown away
2. A "User account changed" event should be raised on the Excel (or Office) application object that my add-in can respond to, so it knows to request a new token and validate the new user.

## Current Behavior
When switching accounts, nothing changes to alert the add-in; calls to Office.auth.getAccessToken() return the wrong user credentials.

## Steps to Reproduce, or Live Example
1. Create a new Microsoft personal account and log in to Windows with it
2. Add a link to a work account
4. Start Excel
5. Start an add-in that calls Office.auth.getAccessToken and shows the user Id
6. Switch between your accounts - note there's no event to tell the add-in about it
7. Refresh / reload the add-in - note that it still shows the old user Id, not the one you're logged in with

## Context
Trying to create an add-in that accesses sensitive company data, needing specific account validation (i.e. my work account). When I start Excel and switch accounts, I have to wait an hour for the token to expire before I can access the company data.

Any server processes relying on OBO flows act on behalf of the wrong user account.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2405
* Operating System: Windows 11
* Browser (if using Office Online): ______

**Comment by shanshanzheng-dev** [comment]
Hi @CBullen2, Thanks for reporting this issue. Currently we don't support Office.auth.getAccessToken() to switch account. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)
