### ISSUE TITLE
onMessageSendHandler event not firing

### ISSUE THREAD

**Issue by skunath** [OfficeDev/office-js#4556]
I have been trying to integrate onMessageSend handling into an addin and have been unable to ever see an event actually triggered. I've replicated the project as described in https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=jsonmanifest

I can get a compose event handler to work. But have had no luck with send events. Nothing appears to load or run for those.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): Firefox, Chrome, Safari
 
## Expected behavior
An alert would pop up when hitting onsend.

## Current behavior
Message sending is uninterrupted and no event is triggered. 

## Steps to reproduce

1. Create a new addin using yo
2. Follow the documentation here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=jsonmanifest
3. Install the manifest on an exchange instance
4. login with a user with the addin and watch

## Link to live example(s)

# Provide additional details
When installing the addin in exchange it does note that the add in should have an onsend event.

## Context
The office documentation is difficult to track through as much of it seems contradictory. I've tried to follow the documentation as best as I can and have had no luck.

**Comment by kumarshrey-msft** [comment]
Hi @skunath, apologies for the delayed response. Are you still facing this issue? If yes, can you please confirm whether you are trying a JSON-based manifest or an XML one? Additionally, can you share the add-in's manifest and handler function?
