### ISSUE TITLE
Add-in consent screen showing wrong name for the publisher

### ISSUE THREAD

**Issue by CBullen2** [OfficeDev/office-js#4557]
I am registered in Partner Center as a sole trader, so I have a Legal Entity name which is my own name and a Publisher Name which is my trading name. I've linked my MPNID to my app so it's a verified publisher. When I purchase an app from AppSource, it correctly shows my Publisher name (set as OfficeAddins.co.uk), but when asked to provide consent to use the application, the Legal Entity name is shown:

![Consent form showing my personal name, not my Publisher Name](https://github.com/OfficeDev/office-js/assets/171870002/f6cdf8db-804d-420f-aed6-a31006a3320e)

That's not the name that the application was purchased/obtained from!

Similarly, my personal name is shown when checking what I've consented to at microsoft.com/consent - that should show the Publisher name

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop and Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2405
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior
I expect the 'Verified Publisher' to show the Publisher Name that has been configured in Partner Center for the add-in, not the Legal Entity Name of the MPN Id.

## Current behavior
The consent popup and the microsoft.com/consent page shows the Legal Entity Name. It should show the add-in Publisher Name

## Steps to reproduce
1. Create a Partner Center account where the legal entity name and Publisher name are different
2. Create a new add-in and link it to that Partner Center account, so it's a verified publisher
3. Run the add-in to get the consent prompt
4. Note that the consent prompt shows the Legal Entity Name and not the Publisher Name
5. Accept the consent
6. Go to microsoft.com/consent
7. Note that the consent prompt shows the Legal Entity Name and not the Publisher Name

## Context
I am trying to get set up as a Sole Trader. My legal entity name is my own name. I trade as "Office Addins", see OfficeAddins.co.uk/About. Wherever a user interacts with my add-in, they should always see the name of "Office Addins". I do not want my personal name displayed on those screens and my users would not recognise that name as the entity they're doing business with.

**Comment by shanshanzheng-dev** [comment]
Hi @CBullen2 Thanks for reporting this issue. We'll be looking into this issue. we'll report back if we have a suggestion for you.

**Comment by akshayta23** [comment]
Hi @CBullen2 Thanks for the details provided. I am trying to repro this issue at my end but unable to. Can you please share a repro video/screenshots of where you're seeing the incorrect name, along with the add-in asset ID?

**Comment by CBullen2** [comment]
Sure. It looks like it's going wrong when the Partner Center details are copied into the Azure app registration to verify the publisher.

If you can see Azure application Id a3b34d78-52d9-419d-b374-85126e8a0781 (my dev app registration) in tenant eb5a08ee-d95b-45be-a9c6-5d3b92581b05, you'll see it's linked to my Partner Center account:

![Azure Publisher](https://github.com/OfficeDev/office-js/assets/171870002/10cb3b01-5743-4f9b-812b-a5d3ecf68906)

But at the time of linking my account, that was my Legal Entity Name, not my Publisher name. 

My Partner Center "Legal Info" tab had:
![Legal Info Details](https://github.com/OfficeDev/office-js/assets/171870002/48f72f3c-54f9-45dd-9ccf-ed15010e6ee4)

And my "Identifiers" tab showed:
![Identifiers](https://github.com/OfficeDev/office-js/assets/171870002/bd4d271e-d957-4e1d-9893-4fc1e0a2a44e)

When I checked my app in the commercial marketplace, it correctly showed my publisher name:
![Marketplace](https://github.com/OfficeDev/office-js/assets/171870002/c07e31e9-1bce-4d81-b758-753f190f85f9)

But when I'm asked to consent to the app accessing my details, it shows the same name (legal entity name) that's on the Azure page:
![Consent screen](https://github.com/OfficeDev/office-js/assets/171870002/755b0254-1e83-4796-97c7-4a3f3b29b0ac)

I've since changed all the Partner Center details, so the Legal Entity name and the Publisher name are now the same. I've refreshed the Partner Center verification for my production app registration (72c3c823-b9dd-4287-be1d-ae3d89281a54) and it has picked up the new name.

But if I remove consent to my (unrefreshed) dev app, and try to connect again, it still shows the old legal entity name as the verified publisher in the consent prompt - which tells me that the data is being copied from Partner Center into the Azure app registration and that's what's picking the wrong name to show as the publisher.

**Comment by akshayta23** [comment]
This seems to be an issue at the AppSource/Commercial Marketplace layer. Please re-assign to the right owner @shanshanzheng-dev

**Comment by shanshanzheng-dev** [comment]
Hi @CBullen2 This has been put on our backlog <ADO bug #9065232>. We unfortunately have no timelines to share at this point.

**Comment by shanshanzheng-dev** [comment]
Hi @CBullen2 Sorry for slow response. From my understanding, when you use same name and refresh the Partner Center verification can work around this error information, right?
