### ISSUE TITLE
Unable to get info from outlook on OnAppointmentSend event

### ISSUE THREAD

**Issue by aamirhusnain** [OfficeDev/office-js#4558]
my event is working but when I try to get info from Outlook then it gives the error and is not working.

![image](https://github.com/OfficeDev/office-js/assets/46522779/a5bf33f2-fea8-4e87-87c0-35a478c5ab7b)

          /*
           * Copyright (c) Microsoft Corporation. All rights reserved. Licensed under the MIT license.
          * See LICENSE in the project root for license information.
        */

        / global Office /

        Office.onReady(() => {
              // If needed, Office.js is ready to be called.
        });

        type Attendee = {
         email: string | null;
         name: string | null;
         type: 'required' | 'optional';
       };

        type AppointmentDetails = {
         attendees: Attendee[];
         start: Date;
         end: Date;
         isAllDay: boolean;
         timeZoneName: string;
         recurrence: any;
         location: string;
         description: string;
        };

      async function OnAppointmentSendHandler(event: Office.AddinCommands.Event) {
          console.log("event started");
          const fetchAppointmentDetails = async (): Promise<AppointmentDetails | null> => {
         if (Office.context.mailbox.item.itemType === Office.MailboxEnums.ItemType.Appointment) {
         const item = Office.context.mailbox.item as Office.AppointmentCompose;

         const getDescription = (): Promise<string> => {
           return new Promise((resolve, reject) => {
             item.body.getAsync(Office.CoercionType.Text, (result) => {
               if (result.status === Office.AsyncResultStatus.Succeeded) {
                   resolve(result.value);
                } else {
                   reject(result.error.message);
               }
             });
          });
        };

      const getAttendees = (): Promise<Attendee[]> => {
        return new Promise((resolve, reject) => {
          item.requiredAttendees.getAsync((result) => {
            if (result.status === Office.AsyncResultStatus.Succeeded) {
              const requiredAttendees: Attendee[] = result.value.map(attendee => ({
                email: attendee.emailAddress || null,
                name: attendee.displayName || null,
                type: 'required' as const
              }));

              item.optionalAttendees.getAsync((optResult) => {
                if (optResult.status === Office.AsyncResultStatus.Succeeded) {
                  const optionalAttendees: Attendee[] = optResult.value.map(attendee => ({
                    email: attendee.emailAddress || null,
                    name: attendee.displayName || null,
                    type: 'optional' as const
                  }));

                  resolve(requiredAttendees.concat(optionalAttendees));
                } else {
                  reject(optResult.error.message);
                }
              });
            } else {
              reject(result.error.message);
            }
          });
        });
      };

      const getStartTime = (): Promise<Date> => {
        return new Promise((resolve, reject) => {
          item.start.getAsync((result) => {
            if (result.status === Office.AsyncResultStatus.Succeeded) {
              resolve(result.value);
            } else {
              reject(result.error.message);
            }
          });
        });
      };

      const getEndTime = (): Promise<Date> => {
        return new Promise((resolve, reject) => {
          item.end.getAsync((result) => {
            if (result.status === Office.AsyncResultStatus.Succeeded) {
              resolve(result.value);
            } else {
              reject(result.error.message);
            }
          });
        });
      };

      const getAllDayStatus = (): Promise<boolean> => {
        return new Promise((resolve, reject) => {
          item.isAllDayEvent.getAsync((result) => {
            if (result.status === Office.AsyncResultStatus.Succeeded) {
              resolve(result.value);
            } else {
              reject(result.error.message);
            }
          });
        });
      };

      const getTimeZoneName = (date: Date): string => {
        const options = { timeZoneName: 'long' } as const;
        const formatter = new Intl.DateTimeFormat('en-US', options);
        const parts = formatter.formatToParts(date);
        const timeZoneName = parts.find(part => part.type === 'timeZoneName')?.value;
        return timeZoneName || 'UTC';
      };

      const getLocation = (): Promise<string> => {
        return new Promise((resolve, reject) => {
          item.location.getAsync((result) => {
            if (result.status === Office.AsyncResultStatus.Succeeded) {
              resolve(result.value);
            } else {
              reject(result.error.message);
            }
          });
        });
      };

      const getRecurrence = (): Promise<any> => {
        return new Promise((resolve, reject) => {
          item.recurrence.getAsync((result) => {
            if (result.status === Office.AsyncResultStatus.Succeeded) {
              resolve(result.value);
            } else {
              reject(result.error.message);
            }
          });
        });
      };

      try {
        const [description, attendees, start, end, isAllDay, location, recurrence] = await Promise.all([
          getDescription(),
          getAttendees(),
          getStartTime(),
          getEndTime(),
          getAllDayStatus(),
          getLocation(),
          getRecurrence()
        ]);

        const timeZoneName = getTimeZoneName(start);

        return {
          attendees,
          start,
          end,
          isAllDay,
          timeZoneName,
          recurrence,
          location,
          description
         };
       } catch (error) {
            console.error("Error fetching appointment details: ", error);
            return null;
         }
       } else {
         console.error("The item is not an appointment compose.");
         return null;
       }
     };

        try {
            const details = await fetchAppointmentDetails();

             if (details) {
                console.log('Description:', details.description);
                console.log('Start:', details.start.toString());
                console.log('End:', details.end.toString());
                console.log('All Day:', details.isAllDay ? 'Yes' : 'No');
                console.log('Time Zone:', details.timeZoneName);
                console.log('Location:', details.location);
                console.log('Attendees:', details.attendees);
                console.log('Recurrence:', details.recurrence);
               }
             } catch (error) {
                    console.error("Error in onMessageSendHandler:", error);
           }  finally {
            event.completed({ allowEvent: true });
           }
        }

        Office.actions.associate("OnAppointmentSendHandler", OnAppointmentSendHandler);

**Comment by aamirhusnain** [comment]
@exextoc I got the issue this wasn't working because of the `getAllDayStatus` and I know [isAllDayEvent is in preview for AppointmentCompose](https://github.com/OfficeDev/office-js-docs-reference/issues/1945#issuecomment-2147981996) and I am using (CDN) (https://appsforoffice.microsoft.com/lib/beta/hosted/office.js) and instead @types/office-js-preview

but I don't know what is the issue why this is not working in my commands.ts file

**Comment by mobisw-msft** [comment]
Hey @aamirhusnain , Can you please share your add-in manifest, or the manifest of an add-in where you can reproduce this issue? It would be even better if you could share a hosted instance of your add-in.

**Comment by aamirhusnain** [comment]
Hi @mobisw-msft my OnAppointmentSend is Triggered but I am unable get info from outlook

**Comment by aamirhusnain** [comment]
this is my manifest.xml


`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
  xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0" xsi:type="MailApp">
  <Id>66edc916-1e6b-4301-b932-1148946134cc</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Pre Registration</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Pre-registration"/>
  <Description DefaultValue="A template to get started Pre-registration Outlook Add-in."/>
  <IconUrl DefaultValue="https://localhost:3000/assets/icon-64.png"/>
  <HighResolutionIconUrl DefaultValue="https://localhost:3000/assets/icon-128.png"/>
  <SupportUrl DefaultValue="https://www.contoso.com/help"/>
  <AppDomains>
    <AppDomain>https://www.contoso.com</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Mailbox"/>
  </Hosts>
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.1"/>
    </Sets>
  </Requirements>
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://localhost:3000/taskpane.html"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
  <Permissions>ReadWriteItem</Permissions>
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"/>
  </Rule>
  <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
      <Requirements>
        <bt:Sets DefaultMinVersion="1.12">
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>
      <Hosts>
        <Host xsi:type="MailHost">
          
          <Runtimes>
            
            <Runtime resid="WebViewRuntime.Url">
              
              <Override type="javascript" resid="JSRuntime.Url"/>
            </Runtime>
          </Runtimes>
          <DesktopFormFactor>
            <FunctionFile resid="Commands.Url"/>
            <ExtensionPoint xsi:type="AppointmentOrganizerCommandSurface">
              <OfficeTab id="TabDefault">
                <Group id="msgComposeGroup">
                  <Label resid="GroupLabel"/>
                  <Control xsi:type="Button" id="msgComposeOpenPaneButton">
                    <Label resid="TaskpaneButton.Label"/>
                    <Supertip>
                      <Title resid="TaskpaneButton.Label"/>
                      <Description resid="TaskpaneButton.Tooltip"/>
                    </Supertip>
                    <Icon>
                      <bt:Image size="16" resid="Icon.16x16"/>
                      <bt:Image size="32" resid="Icon.32x32"/>
                      <bt:Image size="80" resid="Icon.80x80"/>
                    </Icon>
                    <Action xsi:type="ShowTaskpane">
                      <SourceLocation resid="Taskpane.Url"/>
                    </Action>
                  </Control>
                </Group>
              </OfficeTab>
            </ExtensionPoint>
            <ExtensionPoint xsi:type="LaunchEvent">
              <LaunchEvents>
                <LaunchEvent Type="OnAppointmentSend" FunctionName="onMessageSendHandler" />
              </LaunchEvents>
              <SourceLocation resid="WebViewRuntime.Url" />
            </ExtensionPoint>
          </DesktopFormFactor>
        </Host>
      </Hosts>
      <Resources>
        <bt:Images>
          <bt:Image id="Icon.16x16" DefaultValue="https://localhost:3000/assets/icon-16.png"/>
          <bt:Image id="Icon.32x32" DefaultValue="https://localhost:3000/assets/icon-32.png"/>
          <bt:Image id="Icon.80x80" DefaultValue="https://localhost:3000/assets/icon-80.png"/>
        </bt:Images>
        <bt:Urls>
          <bt:Url id="Commands.Url" DefaultValue="https://localhost:3000/commands.html"/>
          <bt:Url id="Taskpane.Url" DefaultValue="https://localhost:3000/taskpane.html"/>
          <bt:Url id="WebViewRuntime.Url" DefaultValue="https://localhost:3000/commands.html" />
          
          <bt:Url id="JSRuntime.Url" DefaultValue="https://localhost:3000/commands.ts"/>
        </bt:Urls>
        <bt:ShortStrings>
          <bt:String id="GroupLabel" DefaultValue=" "/>
          <bt:String id="TaskpaneButton.Label" DefaultValue="Pre-registration"/>
        </bt:ShortStrings>
        <bt:LongStrings>
          <bt:String id="TaskpaneButton.Tooltip" DefaultValue="Opens a task pane of Pre-registration outlook add-in."/>
          <bt:String id="ActionButton.Tooltip" DefaultValue="Perform an action when clicked."/>
        </bt:LongStrings>
      </Resources>
    </VersionOverrides>
  </VersionOverrides>
</OfficeApp>`

**Comment by mobisw-msft** [comment]
Hey @aamirhusnain ,

Since this add-in is locally hosted, we would need you to share your entire add-in (as a repository). Are you observing this only on Outlook Web, or on other platforms? Are you observing this only on Appointment Send, or can you observe this behaviour in Appointment Compose as well? Please use this bug template to frame your query, so that we can better help you:


# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior


## Current behavior



## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)



1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context



## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.
