### ISSUE TITLE
excel custom functions addin "Error loading functions" when adding the addin from admin center 

### ISSUE THREAD

**Issue by Nikodem98** [OfficeDev/office-js#4559]
Only one user has issues loading admin center deployed Addin with error "Error loading functions", it might be related to this user previously side loading older version of this addin with the same manifest id. This user has access to those old functions that load first 

it happens only on MacOs desktop application

Here are the logs that we get:
1. 10/06/2024 10:58:11 Medium  Web Add-In Runtime Logging Session Started          
2. 10/06/2024 10:58:11 Verbose CustomFunctions [Metadata] [Parsing] [Begin]        
3. 10/06/2024 10:58:11 Verbose CustomFunctions [Metadata] [Parsing] [Begin] Function       
4. 10/06/2024 10:58:11 Medium  CustomFunctions [Metadata] [Parsing] [End] [Success] Function=NG.GET.DATAPREP       
5. 10/06/2024 10:58:11 Verbose CustomFunctions [Metadata] [Parsing] [Begin] Function       
6. 10/06/2024 10:58:11 Medium  CustomFunctions [Metadata] [Parsing] [End] [Success] Function=NG.GET.FILE       
7. 10/06/2024 10:58:11 Verbose CustomFunctions [Metadata] [Parsing] [Begin] Function       
8. 10/06/2024 10:58:11 Medium  CustomFunctions [Metadata] [Parsing] [End] [Success] Function=NG.GET.TS     
9. 10/06/2024 10:58:11 Medium  CustomFunctions [Metadata] [Parsing] [End] [Success]        
10. 10/06/2024 10:58:11 Verbose CustomFunctions [Installation] [Functions] [Begin] Solution=1f0208ba-973c-47ef-8fa2-b5f59ec5e0cf, Workbook=Book1        
11. 10/06/2024 10:58:11 Verbose CustomFunctions [Registration] [Begin] Function=NG.GET.DATAPREP, Workbook=Book1     
12. 10/06/2024 10:58:11 Medium  CustomFunctions [Registration] [End] [Success] Function=NG.GET.DATAPREP, Workbook=Book1     
13. 10/06/2024 10:58:11 Verbose CustomFunctions [Registration] [Begin] Function=NG.GET.FILE, Workbook=Book1     
14. 10/06/2024 10:58:11 Medium  CustomFunctions [Registration] [End] [Success] Function=NG.GET.FILE, Workbook=Book1     
15. 10/06/2024 10:58:11 Verbose CustomFunctions [Registration] [Begin] Function=NG.GET.TS, Workbook=Book1       
16. 10/06/2024 10:58:11 Medium  CustomFunctions [Registration] [End] [Success] Function=NG.GET.TS, Workbook=Book1       
17. 10/06/2024 10:58:11 Medium  CustomFunctions [Installation] [Functions] [End] [Success] Solution=1f0208ba-973c-47ef-8fa2-b5f59ec5e0cf, Workbook=Book1        
18. 10/06/2024 10:58:46 Verbose CustomFunctions [Metadata] [Parsing] [Begin]        
19. 10/06/2024 10:58:46 Verbose CustomFunctions [Metadata] [Parsing] [Begin] Function       
20. 10/06/2024 10:58:46 Medium  CustomFunctions [Metadata] [Parsing] [End] [Success] Function=NG.DEV.GET.FILE       
21. 10/06/2024 10:58:46 Verbose CustomFunctions [Metadata] [Parsing] [Begin] Function       
22. 10/06/2024 10:58:46 Medium  CustomFunctions [Metadata] [Parsing] [End] [Success] Function=NG.DEV.GET.TS     
23. 10/06/2024 10:58:46 Medium  CustomFunctions [Metadata] [Parsing] [End] [Success]        
24. 10/06/2024 10:58:46 Verbose CustomFunctions [Metadata] [Parsing] [Begin]        
25. 10/06/2024 10:58:46 Verbose CustomFunctions [Metadata] [Parsing] [Begin] Function       
26. 10/06/2024 10:58:46 Medium  CustomFunctions [Metadata] [Parsing] [End] [Success] Function=NG.GET.FILE       
27. 10/06/2024 10:58:46 Verbose CustomFunctions [Metadata] [Parsing] [Begin] Function       
28. 10/06/2024 10:58:46 Medium  CustomFunctions [Metadata] [Parsing] [End] [Success] Function=NG.GET.TS     
29. 10/06/2024 10:58:46 Medium  CustomFunctions [Metadata] [Parsing] [End] [Success]        
30. 10/06/2024 10:58:46 Verbose CustomFunctions [Installation] [Addin] [Begin] Solution=8b0219e8-5d07-41cf-9514-5c883f1eb28a, Version=1.0.10.2      
31. 10/06/2024 10:58:46 Unexpected  CustomFunctions [Installation] [Addin] [End] [Failure] Solution=8b0219e8-5d07-41cf-9514-5c883f1eb28a, Version=1.0.10.2      
32. 10/06/2024 10:58:46 Verbose CustomFunctions [Installation] [Addin] [Begin] Solution=1f0208ba-973c-47ef-8fa2-b5f59ec5e0cf, Version=1.0.9.0       
33. 10/06/2024 10:58:46 Unexpected  CustomFunctions [Installation] [Addin] [End] [Failure] Solution=1f0208ba-973c-47ef-8fa2-b5f59ec5e0cf, Version=1.0.9.0       
34. 10/06/2024 10:58:50 Verbose CustomFunctions [Metadata] [Parsing] [Begin]        
35. 10/06/2024 10:58:50 Verbose CustomFunctions [Metadata] [Parsing] [Begin] Function       
36. 10/06/2024 10:58:50 Medium  CustomFunctions [Metadata] [Parsing] [End] [Success] Function=NG.DEV.GET.FILE       
37. 10/06/2024 10:58:50 Verbose CustomFunctions [Metadata] [Parsing] [Begin] Function       
38. 10/06/2024 10:58:50 Medium  CustomFunctions [Metadata] [Parsing] [End] [Success] Function=NG.DEV.GET.TS     
39. 10/06/2024 10:58:50 Medium  CustomFunctions [Metadata] [Parsing] [End] [Success]        
40. 10/06/2024 10:58:50 Verbose CustomFunctions [Installation] [Addin] [Begin] Solution=8b0219e8-5d07-41cf-9514-5c883f1eb28a, Version=1.0.10.2      
41. 10/06/2024 10:58:50 Unexpected  CustomFunctions [Installation] [Addin] [End] [Failure] Solution=8b0219e8-5d07-41cf-9514-5c883f1eb28a, Version=1.0.10.2

**Comment by shanshanzheng-dev** [comment]
Hi @Nikodem98 Thanks for reporting this issue, could you try to clear cache to see f it works? https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#clear-the-office-cache-on-mac

**Comment by Nikodem98** [comment]
Clearing cash didn’t work. Checked every single folder mention I that link and clearing web cash on that I icon didn’t work either

**Comment by XuanZhouMSFT** [comment]
Hi @Nikodem98, thanks for raising the issue.
From the description you mentioned that the customer seems to have both sideload and admin center who share the same add-in right? For the same CF add-in, we don't support to register them both at the same time. So we need to delete either of them.
From the log you provided, I assume the customer still want to install both of the add-ins? because I see several add-ins like "1f0208ba-973c-47ef-8fa2-b5f59ec5e0cf" and "8b0219e8-5d07-41cf-9514-5c883f1eb28a" and several "[Metadata] [Parsing] [End] [Success] Function=NG.GET.FILE", I guess that should be the problem to cause the installation fail. So we'd suggest to delete the deploy way of the addin for sideload or admin center to resolve the issue. And after that, also remember to clear the local cache(folder) and web cash.
