### ISSUE TITLE
Sideload doesn't work with content add-ins on mac

### ISSUE THREAD

**Issue by jglodde** [OfficeDev/office-js#456]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac

## Issue
While sideload for task pane add-ins works without problems, errors occur when using sideload for content add-ins.

PowerPoint isn't listing my sideloaded content add-in in the drop down menu.

Add-in Error:
This add-in is no longer available. If this add-in's manifest was removed, please restore it to its previous location and try again.

System:
macOS 10.14.3
PowerPoint for Mac Version 16.23

**Comment by ElizabethSamuel-MSFT** [comment]
@lliu113 Is there someone who can take a look at this content add-in issue? Thanks.

**Comment by lliu113** [comment]
@jglodde - apologies for the very late response to this. Are you still having issues side-loading your add-in?

**Comment by lliu113** [comment]
@jglodde - I'm going to close this issue now for. Please reactivate if you're still encountering this - thanks!
