### ISSUE TITLE
With reading pane hidden, spam addin hangs when reporting emails.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#4560]
# Provide required information needed to triage your issue
With reading pane or preview off, spam addin hangs when reporting emails.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows PC New Look Outlook
* Host [Excel, Word, PowerPoint, etc.]: New Look Outlook
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior

Spam addin should be able to process emails even if preview pane is not shown or even if the email is not opened. This is the behavior we see in the classic-look outlook.

## Current behavior

This is a bug. Spam addin hangs when processing an email that is not being previewed nor opened.

## Steps to reproduce

1. Download the sample code in : https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-spam-reporting
2. Sideload manifest.xml
3. Open Windows Outlook in new look outlook.
4. Ensure that the preview/reading pane is set to 'Hide Reading Pane'.
5. Select/Highlight/Check an email without opening it.
6. Click on the spam addin button.
7. Spam addin hangs.

## Link to live example(s)

NA

# Provide additional details

NA

## Context

Very bad user experience for all end users. Classic outlook works great. New look outlook causes a hang issue.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
None. 

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by glr0221** [comment]
@exextoc this is reproducible in the browser. Upon my investigation, it seems that the code is stuck in Office.onReady(). I hope this helps. Thanks.

**Comment by mobisw-msft** [comment]
@glr0221 ,

Thank you for reporting this issue regarding the Spam add-in hanging on Hidden reading pane. We have added this bug to our backlog. However, we have no timelines to share at this point.

Internal Tracking ID: 4655676

**Comment by kumarshrey-msft** [comment]
This issue has been fixed. Thank you for raising the issue and helping us make the product better. Please note that unlike in Classic Outlook, the spam reporting add-in is disabled when reading pane is hidden and no mail item is open in case of Outlook on the web, on Mac, and in new Outlook on Windows but works when the message to be reported is opened. You can refer to our ⁠[public docs](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/spam-reporting?tabs=jsonmanifest#review-feature-behavior-and-limitations) to know more about the same.
