### ISSUE TITLE
 New Outlook for Mac, the "Work Offline" feature does not block emails if the OnSend add-in is installed and configured after a restart of Outlook

### ISSUE THREAD

**Issue by avisheknand** [OfficeDev/office-js#4563]
# Provide required information needed to triage your issue

The new Outlook for Mac "Work Offline" feature does not block emails if the OnSend add-in is installed and configured, which is after restarting Outlook and remaining in Work Offline mode.

When a user switches to Work Offline mode and tries to send an email, the Send button is disabled. However, if the user restarts Outlook and sends the email, the Send button is enabled, allowing the email to be sent without performing the checks of the OnSend add-in, which should not be the case as stated below:
![image](https://github.com/OfficeDev/office-js/assets/80862413/c9f69715-48ca-4c94-bfb7-18fce78a50f7)

We have followed the documentation provided by Microsoft for [ onSend addins](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=windows)

We have enabled the _OnSendAddinEnabled_ flag on the tenant
![image](https://github.com/OfficeDev/office-js/assets/80862413/0cff25e2-0aaf-42f5-8cc5-9b5449ee56a7)

We have also set the settings key _OnSendAddinsWaitForLoad_ to true on Mac as shown below according to the [documentation ](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=unix)under that MAC tab in the article  :
![image](https://github.com/OfficeDev/office-js/assets/80862413/9ddc800c-20fc-4c6a-9122-835d5c8201ad)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: New Outlook Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.83.2 (24032318)
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior

We expect that if the user restarts Outlook and is still in Work Offline mode with the On Send add-in enabled, they should not be able to send the email, just like before the Outlook restart.
![image](https://github.com/OfficeDev/office-js/assets/80862413/779e66e2-73be-42db-932e-9cb5e199e086)

## Current behavior

When user first switched to Work Offline (in New Outlook for Mac), and works on a new email (or on a reply) then it is not possible to click Send.  The emails will be saved as drafts. This is good and as expected based on documentation.

If user then restarts Outlook and is still in offline mode, it is now possible to click Send on compose emails. The emails are saved to the Outbox and automatically get set out when the user switches back to Online mode. The protection provided by the addin is bypassed. This does not match what the documentation quoted above indicates.

## Steps to reproduce

1. Install a OnSend Addin 
2. Send Email, the OnSend Addin should trigger
3. Switch to Work Offline , compose an email to send, the Send Button is disabled
4. Quit Outlook, and re-launch again ( Restart), 
5. Compose email to Send, the send button is enabled and user is able to send the email without it been blocked ( Send button is not disabled).

**Comment by DivyaPatidar** [comment]
@avisheknand  OnSendAddinsWaitForLoad should not be set using defaults. As mentioned in [Doc](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=unix#:~:text=This%20setting%20or%20key%20is%20CFPreference%2Dcompatible%2C%20which%20means%20that%20it%20can%20be%20set%20by%20using%20enterprise%20management%20software%20for%20Mac%2C%20such%20as%20Jamf%20Pro.) you will need to set using enterprise management software for Mac, such as Jamf Pro. Once configured, the settings should be visible under System Settings -> Profile.
