### ISSUE TITLE
How to use workbox in Excel Addin

### ISSUE THREAD

**Issue by Edward-Zhou** [OfficeDev/office-js#4568]
I am trying to use [workbox](https://developer.chrome.com/docs/workbox/using-workbox-window) to add service work in Excel Addin.

But, I hit error below:

`InjectManifest has been called multiple times, perhaps due to running webpack in --watch mode. The precache manifest generated after the first call may be inaccurate! Please see https://github.com/GoogleChrome/workbox/issues/1790 for more information.`

I did not run webpack with `--watch`.

Is workbox supported in excel addin?

How to use workbox in excel addin to use service worker feature?

**Comment by shanshanzheng-dev** [comment]
Hi @Edward-Zhou I think workbox is for Chrome developers and not be supported in excel addin. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)
