### ISSUE TITLE
In a custom Spam reporting add-in, microsoft defender is not triggered

### ISSUE THREAD

**Issue by HugoLd** [OfficeDev/office-js#4570]
# Provide required information needed to triage your issue
When using an integrated Spam reporting add-in, microsoft defender doesn't trigger an event the same way it does when using the Built-in Spam feature.

## Your Environment
Outlook web(probably same in other environment)
 
## Expected behavior
When using the built-in spam reporting feature, when marking an email as phsihing, I receive an alert email from Microsoft Defender.
If the phishing is marked from an integrated reporting add-in, I should receive an event from Microsoft Defender as well.

## Current behavior
Defender event is not triggered when report is done in an integrated spam reporting add-in

## Steps to reproduce

1. Use an integrated spam reporting add-in such as the contoso example
2. Mark an email as phishing
3. See that no event is triggered

## Context
We had to implement a custom "phishing mailbox" retrieval and send the email from JS file while it would be better to have the same behaviour if user report if from the add-in or built-in tool.

**Comment by mobisw-msft** [comment]
Thank you for the input. This will be considered as a new feature request. 

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.
