### ISSUE TITLE
Get username of current user

### ISSUE THREAD

**Issue by Aidam1** [OfficeDev/office-js#4572]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: All platforms
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows 11
 
## Expected behavior
I'm able to get current user username, but there is no information about that in Office.js

## Current behavior
There is some information about user in [UserProfile ](https://learn.microsoft.com/en-us/javascript/api/outlook/office.userprofile?view=outlook-js-preview), but there is no username.

## Context
Since some APIs are not available on mobile (like getCallbackTokenAsync), we have to force users to also login to MSAL in order to get this info. Since this is very annoying to essentially login twice (once to our system, once to MSAL), we'd like to at least send username as loginHint to MSAL to help user with second login.

**Comment by mobisw-msft** [comment]
Hey @Aidam1 , we have the fields email address and display name available in userProfile. Does that fulfil the necessary requirements?
