### ISSUE TITLE
Outlook 365 add-in not loading on MAC/OS new Outlook app.

### ISSUE THREAD

**Issue by SE-Hubert** [OfficeDev/office-js#4574]
# Provide required information needed to triage your issue
We are currently developing an Office 365 addin for Outlook. We are currently testing the addin throughout all the working platforms. We encountered a problem when testing our addin on the new Outlook on MAC/OS. We did a centralized deployment through the "Microsoft 365 admin center > Settings > Integrated Apps > Upload custom apps > Office addin" and we were able to see and test the addin every where but on the new Outlook on MAC/OS we couldn't see it at first. So we tried side loading the addin manually through the "Get Addins > My add-ins > Add a custom addin > add from file", and it gets installed correctly with no validation error. Only to realize that when I close the "Get Addins" window , the addin disappears. Also in every other platform, we were able to see the addin under the "Admin-managed" tab, but we never see it.

After sideloading the addin manually:
<img width="943" alt="Before" src="https://github.com/OfficeDev/office-js/assets/172506013/37fb98db-9d18-4457-a137-94efd1b70e81">

After closing the "Get Addins" window a reopening it:
<img width="941" alt="After" src="https://github.com/OfficeDev/office-js/assets/172506013/9a150705-0a61-48b7-8cd0-d05bb6b0fe2e">

Also, it might be important to the issue, but our Add-in is an ItemSend addin and on this page: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=windows#limitations. It clearly says that we would be able to Sideloading the addin and the validation process should be okay, but we can't publish it directly to the Microsoft store.

We can also provide our Manifest.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.81
* Operating System: MAC/OS (Monterey, 12.7.2)
 
## Expected behavior

The expected behavior is to be able to see the addin when doing a centralized deployment or just be able to side load it manually.

## Current behavior

Addin not showing with every way I tried.

## Steps to reproduce

1. Create a simple ItemSend addin with requirements 1.13, taskpane on read and compose, dectected entity regex and launch event on the OnMessageAttachmentsChanged and OnMessageFromChanged events.
2. Then make sure it passes the validation and gets installed on any other platform
3. Finally, side load it in the MAC/OS new Outlook app.

# Provide additional details

We already made a StackOverflow post with more details: https://stackoverflow.com/questions/77794145/office-365-web-add-in-not-showing-on-outlook-for-mac

**Comment by mobisw-msft** [comment]
Hey @SE-Hubert ,

Can you please share the manifest with us, as well as the tenant information? (edit: addition) Does this add-in not show up only in Mac (as an admin managed add-in), or is this a behaviour you see across platforms?

**Comment by SE-Hubert** [comment]
Hi,

Of course here is the hosted link: https://office365.secure-exchanges.com/SecureExchanges.xml



From: mobisw-msft ***@***.***>
Sent: Thursday, June 13, 2024 8:24 AM
To: OfficeDev/office-js ***@***.***>
Cc: Hubert Laliberté ***@***.***>; Mention ***@***.***>
Subject: [PUBLIPOSTAGE] Re: [OfficeDev/office-js] Outlook 365 add-in not loading on MAC/OS new Outlook app. (Issue #4574)
Importance: Low


Hey @SE-Hubert<https://github.com/SE-Hubert> ,

Can you please share the manifest with us?

**Comment by SE-Hubert** [comment]
The add-in doesn't show up only on the Mac application as admin managed or as a side load.
If I access it on a web browser on a Mac, everything works accordingly. Its really only on the Mac application

**Comment by SE-Hubert** [comment]
From what I was able to debug, it may be link to the LauchEvents preventing my add-in to be shown correctly.

**Comment by 1TheMuffinMan** [comment]
From reading in another issue + my own experience the javascript engine used in the smart events (your UI-less function file) for Outlook on Windows or Mac is not a modern javascript engine. It's not clear exactly what its capabilities are, but it's pretty basic. I took a look at your function file and I see you're using `let` keyword. That is a feature of ES6? Doubt it's supported.

In Outlook on the web your UI-less function file gets run in the browser so you can use all the juicy features no problem.

It would be great to get a hold of some documentation of what the JS engine is capable of on the desktop versions so that we can write the source code in typescript and compile it to javascript that works. I fear that writing any real world code for this JS engine by hand will be too cumbersome.

**Comment by SE-Hubert** [comment]
The thing is that I was able to make it work on the Windows new Outlook application with no problems, its only on the Mac desktop app that its not working. Also, I was able to modify my addin so that it would show up on the Mac application, but I had to **remove** the **LaunchEvents** from the manifest and they provide crucial information for our add-in to work.

My guess is that its an error with the **LaunchEvents** on Mac.

**Comment by NickLWMP** [comment]
@SE-Hubert I should have clarified. Outlook NEW (for desktop) != to Classic Outlook Desktop. I would see if it works in one of the previous versions. I wonder if Outlook for Mac uses a similar approach to the classic desktop apps that have a limited javascript environment like I mentioned.

**Comment by shighosh-msft** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: 9108499

**Comment by NguyenHaAnhKiemZodinet** [comment]
Hi there, any updates on this ? We're facing the same issue now.

**Comment by SE-Hubert** [comment]
No updates on my side

**Comment by DivyaPatidar** [comment]
@SE-Hubert After investigating, we found that the your [manifest](https://office365.secure-exchanges.com/SecureExchanges.xml)  contains resid="lauchEvent", but lauchEvent is not defined. Replacing it with an already defined resid resolved the issue on our end. Could you try defining it and see if it resolves the issue for you?

Additionally, I attempted to validate this manifest and found that the validation is failing. Please try to validate your manifest and fix the issues. For more details on how to validate, please refer to the [documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest)

**Comment by SE-Hubert** [comment]
@DivyaPatidar  Sorry for the delay I was working on other projects.

I indeed had a wrong resid for the lauchEvent. I changed it and it seem to be detected on Macos. Furthermore, this add-in should never pass the validation process since its attached to the "ItemSend". 

Thanks a lot I think that the resId did indeed solve my issue !
