### ISSUE TITLE
Custom function handling of Entity Value is broken again

### ISSUE THREAD

**Issue by jim22k** [OfficeDev/office-js#4576]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC & Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 2407 (Build 17809.20000) & 16.87 (24061211)
* Operating System: Windows & Mac
 
## Expected behavior

1. Cell A2 contains [Entity Value data](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-data-types-entity-card)
2. My custom function accepts inputs of type `any[][][]`, including entity data
3. Cell B2 has function =MYFUNC(A2)
4. MYFUNC is called and produces a result

## Current behavior

When MYFUNC is called with normal input (number, string, range), it works fine.
When MYFUNC is called with Entity Value data, it returns #VALUE!. Logging statements within MYFUNC do not print to the console, indicating that MYFUNC is never called.

This is similar to #4466, but the broken state is less severe.

## Steps to reproduce

1. Create a custom function using a manual functions.json file
```
{
    "allowCustomDataForDataTypeAny": true,
    "allowErrorForDataTypeAny": true,
    "functions": [
        {
            "id": "MYFUNC",
            "name": "MYFUNC",
            "parameters": [
                {
                    "dimensionality": "matrix",
                    "name": "dependencies",
                    "repeating": true,
                    "type": "any",
                    "optional": true
                }
            ],
            "result": {}
        }
    ]
}
```
2. Write the function
```
export function myfunc(deps: any[][][]): number {
    console.log(`deps: ${JSON.stringify(deps)}`);
    return 15;
}
```
3. Put a `1` in cell A1
4. In cell B1, write `=MYFUNC(A1)`
5. Observe that the result is 15 in the grid
6. Observe that the DevTools console displays deps: [[[1]]]
7. Put `MSFT` in Cell A2
8. Click in cell A2, then Click Data -> Stocks
9. Cell A2 will change to an Entity Value data for Microsoft Corporation
10. In cell B2, write `=MYFUNC(A2)`
11. Observe that the result returns #VALUE!
12. Observe that the DevTools console doesn't display anything.

## Context

This may be related to #4466. The custom function call is the same, however the result is slightly different.

The issue is only when passing an Entity Value to a Custom Function parameter of type `any[][][]`.
Non-entity values are fine. And passing an Entity Value to a parameter of type `any[]` or `any[][]` is fine.
It appears to only affects `dimensionality: matrix, repeating: true, type: any` parameters.

Given that this was fixed in #4466 but resurfaced might indicate the need for a stronger unit test against regressions.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by shanshanzheng-dev** [comment]
Hi @jim22k Thanks for reporting this issue. we'll be looking into this issue and will report back if we have a suggestion for you.

**Comment by lucadom** [comment]
I have the same issue in the Office for the web platform since at least a couple of days.

**Comment by MiaofeiWang** [comment]
@jim22k Thanks for reporting this! We have mitigated the issue on Windows and Mac. In fact, not only `dimensionality: matrix`, it impacts all functions with `repeating: true, type: any`. And you are right that stronger tests are required and we are adding more to prevent from regressions. 

@lucadom For Excel on the web, we are on the process to mitigate the issue with top priority and will update in this thread as soon as possible.

**Comment by MiaofeiWang** [comment]
Hi @lucadom, this issue has been resolved for Excel on the web. Thank you again for helping us catch this issue!
