### ISSUE TITLE
Office.context.roamingSettings.get() size limit

### ISSUE THREAD

**Issue by GruberMarkus** [OfficeDev/office-js#4577]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: All
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: All current releases
* Operating System: Windows 11, Android 14, iOS 17
* Browser (if using Office on the web): Edge, Firefox
 
## Expected behavior
Please allow `Office.context.roamingSettings.get` to read settings bigger than 32 KB.
The documentation https://learn.microsoft.com/en-us/javascript/api/outlook/office.roamingsettings only mentions the 32 KB limit for `set`, but not for `get`.

## Current behavior
`Office.context.roamingSettings.get` fails when a setting is bigger than 32 KB. This is possible, when not using `Office.context.roamingSettings.set` to define a value but EWS or Extended MAPI.

## Steps to reproduce

1. Create and run an app, that creates a new roaming setting using `Office.context.roamingSettings.set` and `Office.context.roamingSettings.saveAsync`
2. Modify the roaming setting defined in step 1 using EWS or Extended MAPI. Update the setting to a value that is bigger than 32 KB.
3. Use the app created in step 1 to read the roaming setting using `Office.context.roamingSettings.get`. It will fail because the setting is bigger than 32 KB, although the limit should only apply to `set` according to documentation.

## Link to live example(s)

If needed, i can create sanitized and radically simplified sample code.

# Provide additional details

Not required.

## Context

We use a central on-prem service to put data in mailboxes of our users, which is later used by an Outlook add-in. The Outlook add-in only runs in situations where there is no connectivity to the corporate network, and the data can not be made available over the internet via a secured web service or something comparable.

## Useful logs

Please see the descriptions above.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by neprasad-microsoft** [comment]
Hi @GruberMarkus 
Thank you for the input. Since this needs changes on all platforms and is a behavior change, this will be considered as a new feature request. 

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.

**Comment by GruberMarkus** [comment]
I created a new request at the Tech Community Page as suggested, and will therefore close this GitHub issue.

Thanks for your support!
