### ISSUE TITLE
Word close API not working

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4578]
Hi,

I am using following code to close document from online Word.
 await Word.run(async (context) => {
   context.document.close();
   });

But document is not getting closed. Also I checked if environment support requirement set. Office.context.requirements.isSetSupported('WordApi', 1.5) , this value is true.

So it should work. Can you please tell me if I am missing anything,

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 Thanks for reporting this issue. This is a by-design behavior. There's no close action on Word Online. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)

**Comment by ishanig11** [comment]
As per documentation its available on WordApi 1.5 requirement set. And this is supported for online version also.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 Thanks for reaching out. I think you mean this documentation, right? https://learn.microsoft.com/en-us/javascript/api/word/word.document?view=word-js-preview#word-word-document-close-member(1)
For this close api, it only works on word desktop, it not work on word online. Sorry for the confusion.
Again, you can submit your request on Tech Community New Ideas item, we value your feedback. Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@ishanig11 We're updating the documentation to note that Word on the web isn't supported. That change should be live tomorrow (June 24) Pacific Time.

Thanks.
