### ISSUE TITLE
Excel close is not working

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4579]
I am using excel close API to close context document in online office excel.

  await Excel.run(async (context) => {
		context.workbook.close(Excel.CloseBehavior.skipSave);
	});

Above code is used for the same. But context workbook is not getting close.

I have already checked and environment is supported for requirement set.

Can you please let me know what is missing?

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 Thanks for reporting this issue. I run this code and context workbook is getting closed. Could you please try again? Thanks.
async function run() {
  await Excel.run(async (context) => {
    context.workbook.close(Excel.CloseBehavior.skipSave);
    await context.sync();
  });
}
![image](https://github.com/OfficeDev/office-js/assets/125014206/9f3c4faf-a82f-4265-a5e8-1a83d8df131b)

**Comment by ishanig11** [comment]
@shanshanzheng-dev : I am using similar code but for me no error no message. Also my action button is present under task pane.
Is it possible for you to share this sample application? And also video of behavior?

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11, I use script lab to run this code, you can check this video:

https://github.com/OfficeDev/office-js/assets/125014206/b14db71b-174e-4d61-ab5d-b00dfe8cfc74

**Comment by ishanig11** [comment]
I used same code from function getting called in executeFunction.  But not working.

**Comment by shanshanzheng-dev** [comment]
Is it on excel online?

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 This is my Excel online build number: 16.0.17809.42308. And this is my test code on script lab:
$("#run").on("click", () => tryCatch(run));

async function run() {
  await Excel.run(async (context) => {
    context.workbook.close(Excel.CloseBehavior.skipSave)

    await context.sync();
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}

**Comment by ishanig11** [comment]
Thank you @shanshanzheng-dev . It worked. But is there anyway to avoid that popup?

**Comment by shanshanzheng-dev** [comment]
do you meaning this below picture? I think this is by design and we can't avoid it.
![image](https://github.com/OfficeDev/office-js/assets/125014206/d5eebaaa-5576-458d-bbf9-bfdd3cb35053)

**Comment by ishanig11** [comment]
Yes, this dialog.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11, I'm afraid that we can't avoid this dialog, this is by design. Thanks.
