### ISSUE TITLE
Edge WebView: Anchor links open browser in the background

### ISSUE THREAD

**Issue by htryggva** [OfficeDev/office-js#458]
Anchor links with target="_blank" are opening Edge in the background.

## Expected Behavior
I would have expected the browser window to open in the foreground as it does with the current IE control.

## Steps to Reproduce, or Live Example
https://gist.github.com/htryggva/9b6d32274336830722ecd788012752a7

## Context
We have links in our add-in that should open an external web page (for documentation, roadmap, etc...). It's not so obvious to the user that clicking the link actually triggered an action.

## Your Environment
* Platform: PC desktop (with Edge WebView)
* Host: Word
* Office version number: 16.0.11527.20004
* Operating System: Windows 10 1903 (OS Build 18343.1)

**Comment by kbrandl** [comment]
(@jargil assigning this one to you, per Sudheer's request.)

**Comment by jargil** [comment]
Hey @htryggva, thanks for reporting this. I've addressed it in our side and should begin rolling out soon.

**Comment by jargil** [comment]
@htryggva - with any Office build including or after 16.0.11624.20000, could you please confirm that you're now seeing the right behavior?

**Comment by htryggva** [comment]
@jargil Just tried it on 16.0.11624.20000. I can confirm that the links are working as expected. Thanks :)

**Comment by jargil** [comment]
@htryggva - Thank you! I'll close this issue then.
