### ISSUE TITLE
Powperpoint close API

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4580]
Similar to Word close event as below
await Word.run(async (context) => {
  context.document.close();
});

looking for close API on Popwerpoint.

**Comment by ishanig11** [comment]
Any update?

**Comment by EsterBergen** [comment]
@ishanig11  - Does this documentation help? https://learn.microsoft.com/en-us/office/dev/add-ins/develop/get-the-whole-document-from-an-add-in-for-powerpoint-or-word?tabs=powerpoint

**Comment by ishanig11** [comment]
This API just closes file connection but does not close tab. I am looking for close API similar to Excel.

**Comment by EsterBergen** [comment]
@ishanig11 - are you looking to close the presentation?  Can you help me understand what you mean by tab in PPT?

**Comment by ishanig11** [comment]
@EsterBergen : yes I am looking to close context document. So for online its tab and for desktop its file.

**Comment by EsterBergen** [comment]
@ishanig11 - Thanks for these questions and clarification. This would be a new feature. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process.
