### ISSUE TITLE
Manifest file sideloads on Excel web but does not sideload on Mac or Windows os

### ISSUE THREAD

**Issue by GreyPool** [OfficeDev/office-js#4581]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.75
* Operating System: Mac
 
## Expected behavior
The manifest file should work the same on Excel web and Mac os, when we side load the add-in.

## Current behavior
When we sideload the manifest file on Mac, by copying the manifest file in the wef folder, the add-in does not appear on Excel. However, The same manifest file works without any issues when we sideload it on Excel web. We have attached the manifest file in text format. 

## Steps to reproduce

1. Copy the manifest file to /Users/<username>/Library/Containers/com.microsoft.Excel/Data/Documents/wef folder
2. Open Excel application
3. Addin should appear under Insert -> Addins

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by shanshanzheng-dev** [comment]
Hi @GreyPool Thanks for reporting this issue. Could you please provide us your manifest？Thanks.

**Comment by GreyPool** [comment]
Upon further inspection, we found that svg icons are not supported. When we replaced all the svg icons with png, the issue got resolved. You may close this.

**Comment by shanshanzheng-dev** [comment]
Hi @GreyPool So happy you get the resolution. In order to improve product experience, we'd like to know if you can get some error message to tell you that svg is not supported, and how you find the cause of the problem. We value your feedback. Thanks:)
