### ISSUE TITLE
Opening dialog in iframe for an Excel custom function handler fails on alternate invocations

### ISSUE THREAD

**Issue by tobz1000** [OfficeDev/office-js#4582]
# Provide required information needed to triage your issue

## Your Environment

* Platform: Office on the web
* Host: Excel
* Office version number: Build 16.0.17809.42308
* Operating System: Linux
* Browser: Firefox 126
 
## Expected behavior
Every time I invoke a custom function which opens a dialog in an iframe, the dialog open and display its contents correctly.

## Current behavior
On alternate invocations, the dialog will open but fail to display any contents.

## Steps to reproduce
1. Invoke a custom formula function for which the handler will call `Office.context.ui.displayDialogAsync` with the option `displayInIframe: true`. The dialog should display correctly.
2. Close the dialog.
3. Invoke the same formula again. The dialog container will open, but its contents will not be displayed.
4. Invoke the same formula for a third time. The dialog contents will once again be displayed correctly. And so on...

## ~~Link to live example(s)~~

# Provide additional details

## Context

Some similar raised issues are: #1014, #2838. Using information in #2838, I was able to come up with a workaround. Calling the following in the custom function handler, before invoking the dialog, prevents the issue:

```js
await new Excel.RequestContext().sync();
```

## Useful logs

When the error occurs, the following is printed to the console:

```
Uncaught Function ContextActivationManager_getAppContextAsync call failed. ErrorCode is -3, exception: [object Object]
```

Using dev tools, I can see that the actual value of `[object Object]` in the above log is:

```js
{ name: "Sys.ArgumentException", paramName: "contextId" }
```

**Comment by shanshanzheng-dev** [comment]
Hi @tobz1000 Thanks for reporting this issue. Seem like this issue occurs intermittently, right?  Could you please share us more details, such as code, which can help us to triage this issue better? Thanks

**Comment by tobz1000** [comment]
@shanshanzheng-dev

I'm unable to easily provide a reproduction repo right now. However, assuming you already have a functioning addin with custom functions, you should be able to reproduce by adding a custom function with the code:

```js
export async function bug(x) {
  Office.context.ui.displayDialogAsync(
    /* add an existing addin page's url here */,
    { displayInIframe: true }
  );
}
```

Adding the "sync" function call fixes the problem, e.g.:

```js
export async function bug(x) {
  await new Excel.RequestContext().sync();

  Office.context.ui.displayDialogAsync(
    /* add an existing addin page's url here */,
    { displayInIframe: true }
  );
}
```

> Seem like this issue occurs intermittently, right?

The pattern is very regular: the dialog content fails to load on every *other* invocation. I.E. the content loads successfully, then fails when next opened, then succeeds, then fails, etc.

**Comment by shanshanzheng-dev** [comment]
Hi @tobz1000 Thanks for this information, we'll be looking into this. Did the workaround unblock you for now? If possible, could you provide us with repro video that we'll help us investigate this better. Thanks

**Comment by tobz1000** [comment]
@shanshanzheng-dev an apology, my report was not fully correct. I thought I had reproduced this on Chrome and reported Chrome as the browser for simplicity - but now I can only reproduce on Firefox. I have updated the description.

Here is a quick reproduction on Firefox. You can see that the dialog contents loads on the 1st, 3rd, and 5th invocations. It fails to load on the 2nd, 4th, and 6th invocations.

[screencast.webm](https://github.com/OfficeDev/office-js/assets/1471978/4e8076a6-d88f-45ea-8e28-cc6cff61a718)

Here is the console log:

[console-export-2024-6-21_0-23-56.txt](https://github.com/user-attachments/files/15921032/console-export-2024-6-21_0-23-56.txt)

**Comment by tobz1000** [comment]
@shanshanzheng-dev 

> Did the workaround unblock you for now?

Yes, with the extra code above, I don't currently have a problem, thank you. Hopefully the workaround is useful to others too while this issue persists.

**Comment by shanshanzheng-dev** [comment]
Hi @tobz1000 Thank you very much for providing so much useful information that help us investigation. So glad you have a workaround to unblock you. That's so helpful for others. We'll report back if we have some updates. Thank you.

**Comment by RuizhiSunMS** [comment]
Close this case for the fix has been released. Please feel free to reopen it if wrong.
