### ISSUE TITLE
Outlook Add-in - Call to mailbox.getUserIdentityTokenAsync returning undefined token for only some Outlook accounts

### ISSUE THREAD

**Issue by prwillmann** [OfficeDev/office-js#4583]
I am working on a previously fully-functional Outlook Add-in that is having issues retrieving the ExchangeIdentityToken only for some Outlook accounts. This issue was first encountered on June 14th, 2024. However, our logs show that a similar error also occurred on March 18th, 2024, but disappeared shortly thereafter on March 19th.

## Your Environment
* Platform: Office on the web, Office 365
* Host: Outlook web, Outlook desktop app
* Office version number: Outlook for Mac 16.86 (in case when failure occurs on Outlook Desktop app)
* Operating System: Windows 11 Home, macOS
* Browser (if using Office on the web): Chrome, Edge, Firefox
 
## Expected behavior
All Outlook accounts are able to successfully retrieve an ExchangeIdentityToken upon calling: Office.context.mailbox.getUserIdentityTokenAsync()

Note that this is using: ExtensionPoint xsi:type="MessageReadCommandSurface" in the manifest.xml

## Current behavior
Some accounts (no discernable pattern) fail to retrieve the token and produce the following error response:
```
error: OSF.DDA.Error 
Code: 9018
message: "An internal error has occurred."
name: "GenericTokenError"
status: "failed"
value: undefined
```
All accounts tested thus far have been Personal Outlook accounts, ranging in age from newly created to 10+ years old. None have Inbox Sharing enabled. Some accounts successfully retrieve the above token, some do not.

## Steps to reproduce
1. Use a random Outlook test account
2. Initialize add-on with call to Office.context.mailbox.getUserIdentityTokenAsync()
3. Check (using web inspector or debugger) to see if a token has sent in the response.  

## Context
Some users of our Outlook add-in are getting an error when attempting to login to our service within the add-in, ultimately due to us not receiving (and therefore being unable to validate and authenticate) the ExchangeIdentityToken.

**Comment by illing2005** [comment]
We are facing the same issue.

Our investigation showed that it only fails for outlook.com and hotmail.com email addreses 
It works fine for email domains that are managed by MS nameservers

**Comment by illing2005** [comment]
I've created a simple add-in to reproduce this issue. It's based on the official "hello world" example. 
This demonstrates that this is a global issue and not specific to any setup:
https://github.com/illing2005/outlook-issue

**Comment by pylead** [comment]
This is a real issue and affects many of our users.
```
Internal protocol error: '-2147467259'.
```

**Comment by HDelipoyraz** [comment]
The Outlook REST endpoints will be fully decommissioned in March 2024.

![image](https://github.com/OfficeDev/office-js/assets/4434906/38906d71-f3e3-4524-8b11-809f95aa75a0)

https://learn.microsoft.com/en-us/outlook/rest/compare-graph

**Comment by leonardo-vivere** [comment]
Do we have any alternative/palliative solution to this problem?

**Comment by illing2005** [comment]
> The Outlook REST endpoints will be fully decommissioned in March 2024.
> 
> ![image](https://private-user-images.githubusercontent.com/4434906/342811213-38906d71-f3e3-4524-8b11-809f95aa75a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMzQ3NzksIm5iZiI6MTcxOTMzNDQ3OSwicGF0aCI6Ii80NDM0OTA2LzM0MjgxMTIxMy0zODkwNmQ3MS1mM2UzLTQ1MjQtOGIxMS04MDlmOTVhYTc1YTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjVUMTY1NDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGQwMjYxODEwODU4Y2JkNTY3ZTIyODA5OWY2Y2IzY2Q4NDA1NzRkYjU2MWI5YWE3NjFiMzcxMTEzODI5MzZmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3vH8xMCT9zAEpgCdPJya_YH43U6g0umD0kt2_OyN-qs)
> 
> https://learn.microsoft.com/en-us/outlook/rest/compare-graph

Yes, but `mailbox.getUserIdentityTokenAsync` is not using the REST API. It's something else

**Comment by vporras-vendasta** [comment]
We are facing the same issue , the way I was able to replicate this was by using a hotmail email or an email that can use outlook and gmail at the same time : 

When the add-in tries to run https://outlook.live.com/owa/0/service.svc?action=GetClientAccessToken the response is an internal error: 

```
   "Body": {
        "ResponseMessages": {
            "Items": [
                {
                    "__type": "GetClientAccessTokenResponseMessage:#Exchange",
                    "Token": null,
                    "MessageText": "An internal server error occurred. The operation failed., Unauthorized:Unauthorized",
                    "ResponseCode": "ErrorInternalServerError",
                    "ResponseClass": "Error"
                },
                {
                    "__type": "GetClientAccessTokenResponseMessage:#Exchange",
                    "Token": null,
                    "MessageText": "An internal server error occurred. The operation failed., Unauthorized:Unauthorized",
                    "ResponseCode": "ErrorInternalServerError",
                    "ResponseClass": "Error"
                }
            ]
        }
```

**Comment by Oleg-O** [comment]
Thank you for reporting, we are able to reproduce and are actively investigating. 
Internal tracking id: 4672643.

**Comment by Oleg-O** [comment]
This should be resolved. Please let us know how that looks for you now. Apologies for the disruption.

**Comment by illing2005** [comment]
Great news! Thanks @Oleg-O!
is there a way to escalate this quicker in case it comes up again?
Our production app was affected by this for more than 2 weeks now

**Comment by prwillmann** [comment]
Confirmed on all test accounts that the issue is no longer reproducible. Thanks @Oleg-O!

**Comment by Oleg-O** [comment]
> Great news! Thanks @Oleg-O! is there a way to escalate this quicker in case it comes up again? Our production app was affected by this for more than 2 weeks now

This would still be the way. We're considering improvements in our process to react to such reports faster.

**Comment by avibaitelman-litify** [comment]
Hey @Oleg-O,

Users are still reporting this error `Internal protocol error: '-2147467259'.` on desktop. Is there a specific release which includes the fix?

**Comment by shubhamGfacility** [comment]
This is still happening in office js version 1.1.107.  Is the fix already included in this release ?

**Comment by illing2005** [comment]
@shubhamGfacility, I don't think they will fix it. 
The API will be shut down in a couple of days

**Comment by ndking82** [comment]
OSF.DDA.Error {name: 'GenericTokenError', message: 'An internal error has occurred.', code: 9018

![Image](https://github.com/user-attachments/assets/a0557cf7-e2be-4e8a-86c6-238ca6fe2c2f)


Office.context.mailbox.getUserIdentityTokenAsync(function (asyncResult) {
                            if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
                                deferred.resolve(asyncResult.value);
                            } else {

**Comment by mcka** [comment]
Same issue it was working before and for two weeks getCallbackTokenAsync() fails

**Comment by elrapha** [comment]
I am getting this issue now also for Office.context.mailbox.getUserIdentityTokenAsync
My  Addin is running in the online client
