### ISSUE TITLE
Permission under manifest file

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4586]
Hi,

I have built office js plugin to read and write office files to one of server.
I dont want to give ReadWriteDocument permission to this add-in as this permission covers ReadAllDocument permission also. So client is hesitant to provide this permission.

Is there anyway by which we can just give Read & Write Document permission on context document?

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 Thanks for your question. I have found a reference for you: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins
https://learn.microsoft.com/en-us/javascript/api/manifest/permissions?view=common-js-preview
I think <Permissions> [Restricted | ReadDocument | ReadAllDocument | WriteDocument | ReadWriteDocument]</Permissions> is working.

**Comment by ishanig11** [comment]
we can define only one permission at a time. So how can I give read & write context document permission without using ReadWriteDocument (I dont want to use this permission)

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 Seem this is the only way to give ReadWriteDocument permission to add-in. please check this reference: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/requesting-permissions-for-api-use-in-content-and-task-pane-add-ins
