### ISSUE TITLE
Content copy pasted as table not being considered as body text using getAsync(Office.CoercionType.Text)

### ISSUE THREAD

**Issue by ayush-sopori** [OfficeDev/office-js#4587]
In the Outlook add-in, we use the Office.context.mailbox.item.body.getAsync() method to get the entire email body in the required format. As a user, if I paste an excel table data in the body section of the email, and use the coersion as Text, the getAsync methods returns the body content as empty, even though table data is present in email body.
We are able to get the email body only if the user added some data prior/after pasting in the body section. 

## Your Environment
Windows Chrome OWA
 
## Expected behavior
The Office.context.mailbox.item.body.getAsync() method should also consider copy pasted excel table data.

## Current behavior
The Office.context.mailbox.item.body.getAsync() method returns empty body if copy pasted table from excel is entered.

## Steps to reproduce
1. Compose a new email.
2. Copy table data from an excel (table form).
3. Paste the data in the body of the email, do not type any other data in body.
4. Call the Office.context.mailbox.item.body.getAsync(Office.CoercionType.Text) API
5. Observe that the results are coming a blank.

![Screenshot 2024-06-19 174116](https://github.com/OfficeDev/office-js/assets/149785597/fa6ecac8-c8bf-438c-ad71-a5ebb669dfcb)

**Comment by shighosh-msft** [comment]
Hi @ayush-sopori, thanks for providing detailed repro steps. Is there any specific requirement for which you are using CoercionType.Text? CoercionType.Html does fetch the body as expected.

**Comment by ayush-sopori** [comment]
We need to determine if the email body content is empty/blank, based on which we perform certain operations.
By using the Office.context.mailbox.item.body.getAsync(Office.CoercionType.Text), we get the current email body content and check the result text to know if any content is present or not.
Here is a snippet of the required functionality:
![f500e992-dc06-4300-9e82-44d824f1bb7b](https://github.com/OfficeDev/office-js/assets/149785597/b9749528-1cf4-4100-8d41-ff00bd5fdd19)

**Comment by mmanjaree-msft** [comment]
Thanks for reporting this issue. We have added this to our backlog but we donot have any timelined for the fix as of now.
Internal tracking id:  4678594

Workaround: For your use case can you try Html coercion type and traverse the html obtained by the get api , check for any text nodes using textContent or innerText properties to determine if body is empty

**Comment by gapat-gh-msft** [comment]
Public documentation about getAsync: https://learn.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-preview#outlook-office-body-getasync-member(1)
