### ISSUE TITLE
categories.addAsync is failing with operation not supported error in new outlook in windows

### ISSUE THREAD

**Issue by som-cloudextend** [OfficeDev/office-js#4588]
# categories.addAsync is failing to add category in message compose mode in new outlook in windows.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: new Outlook
* Office version number: 1.2024.612.100 (Client Version is 20240607002.20.)
* Operating System: Windows 11
* Browser (if using Office on the web): N/A
 
## Expected behavior

categories.addAsync should add category in message compose mode without any error. Categories are present in master category list. The categories.addAsync API works in message compose mode in old outlook in windows but not in new outlook.

## Current behavior

It's failing with the operation is not supported error.

## Steps to reproduce

1. Open new outlook in windows
2. Try to add category from master category list
3. It will fail with error

## Link to live example(s)

The sample snippet "work with item categories" can be used to test it in ScriptLab. Though ScriptLab also doesn't run properly in new outlook.

# Provide additional details

We are using this to apply category which works fine old outlook in windows.

> olItem.categories.addAsync(categoriesToAdd, {}, asyncResult => {
            if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
                this.logger.debug(
                    "Successfully assigned category to item."
                );
            } else {
                this.logger.error(
                    "Failed to assign category with error: " +
                        asyncResult.error.message
                );
            }
        });

![Screenshot 2024-06-20 at 1 08 08 PM](https://github.com/OfficeDev/office-js/assets/155970058/e483cf52-9f15-4cc1-b281-ad5e6b906a12)

Old outlook details:
version 2405 and build 17628.20144

## Context

Applying categories in an important feature we provide to our users. It helps them to organize and check automation statuses.
## Useful logs

- [x] Console errors
- [x] Screenshots

**Comment by som-cloudextend** [comment]
Any updates on this?

**Comment by akshayta23** [comment]
@som-cloudextend Thanks for raising this issue. We have added this feature request to our roadmap, but unfortunately, we do not have any ETAs/timelines to share yet. We are updating our public documentation with this information as well. Please raise this feature request on https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform to track the status of this item.

**Comment by prasath-cloudextend** [comment]
Any updates on this? Thanks
