### ISSUE TITLE
Way to turn off track changes from office documents

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4591]
Can you tell me how to turn off track changes before inserting data from another document?

**Comment by jeremy-msft** [comment]
Hi @ishanig11, please see the documentation for [Word.ChangeTrackingMode enum](https://learn.microsoft.com/en-us/javascript/api/word/word.changetrackingmode?view=word-js-preview), which includes a sample for how to get and set the change tracking mode.

**Comment by ishanig11** [comment]
I tried as 	context.document.changeTrackingMode = Word.ChangeTrackingMode.off;
but I am getting 	context.document.changeTrackingMode not available exeception.

**Comment by xiruatms** [comment]
@ishanig11 , thanks for reporting this. Will you please provide more information? Which platform are you using(Desktop?Word Online?)? What're the code you're using？ More details will help us understand your issues better.

**Comment by ishanig11** [comment]
I want to use it for word,excel,ppt online as well as desktop version of office 365.

I am calling above code before opening document usinginsrtfromBase64 API.

**Comment by xiruatms** [comment]
Be noted: this API is supported on Word (both Desktop and Online), but not Excel & PPT. On which application did you encountered such exception please?

**Comment by ishanig11** [comment]
On Word only.

**Comment by xiruatms** [comment]
If possible, will you please post your codes or screenshot here so that I can understand your issue? I can NOT repro it in my environment.

**Comment by ishanig11** [comment]
@xiruatms : can you share code which you are using? I will test with that code in my local environment.

**Comment by xiruatms** [comment]
Take a try with this please: https://gist.github.com/xiruatms/ba10a01e1de0cddde5fe88c9911c2232

**Comment by thelsevier** [comment]
@xiruatms you may need to load the property before changing it:

```
        document.load("changeTrackingMode");
        await context.sync();
        // now you can change it
        document.changeTrackingMode = ...
        await context.sync();
```
