### ISSUE TITLE
Create Presentation/Excel API

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4592]
I see there is API to createDocument but no such API for Powerpoint/Excel.

I dont want to use insertfromfile APIs. As these APIs are overwriting context document. Is there anyway to open ppt/excel using some API?

**Comment by jeremy-msft** [comment]
Please refer to the following APIs:
Excel: https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-workbooks#create-a-workbook
PowerPoint: https://learn.microsoft.com/en-us/javascript/api/powerpoint?view=powerpoint-js-1.1#powerpoint-powerpoint-createpresentation-function(1)

**Comment by ishanig11** [comment]
Yes.. Is there anything to open file directly? As with create APIs we can't provide file name due to this lots of document.XX..files are getting generated under user's default directory.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 I'm afraid there is no office JS API to open file directly. I thought if you have this file's url, you can use http request to open you file? 
But If you still want JS api to open your file, we recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed. [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform), Thanks!
