### ISSUE TITLE
Highlight custom tab on opening document

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4593]
Can you tell me how I can select custom ribbon tab after opening document rather that default home tab?

![image](https://github.com/OfficeDev/office-js/assets/157671419/4bf041b9-1ac5-4cf0-ae1f-43ac060b69b7)

**Comment by Rick-Kirkham** [comment]
See [Specify which tab has focus when the document opens](https://learn.microsoft.com/en-us/office/dev/add-ins/design/custom-tab-placement#specify-which-tab-has-focus-when-the-document-opens)

**Comment by ishanig11** [comment]
As per above image want to highlight "Contoso Data" tab. Means once document is opened, user should see all commands under this tab.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 could you get a solution for your question? Thanks.

**Comment by ishanig11** [comment]
No. As per link its telling position of tab. I don't want to change tab position. I want to highlight custom tab on document load.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 could you share your manifest?

**Comment by ishanig11** [comment]
[manifest.zip](https://github.com/user-attachments/files/16026727/manifest.zip)
You can refer this sample manifest file.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 Sorry, may I know your detail scenario? How do you want to highlight custom tab on document load? Or you want to auto open specified taskpane？
@m-hellesen could you help this customer if you have any insights? Thanks.

**Comment by ishanig11** [comment]
By default on document open , Home tab is opened. I want it as Contosa tab session is opened
![image](https://github.com/OfficeDev/office-js/assets/157671419/18bdc221-76e1-4acb-a92b-6e3a513cc8a1)

**Comment by shanshanzheng-dev** [comment]
@ishanig11 could you try this reference if it works: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document#implement-the-autoopen-feature

**Comment by ishanig11** [comment]
@shanshanzheng-dev : link you mentioned is to open taskpane automatically. My requirement is to highlight tab and then user can select required commands from that tab.

**Comment by ishanig11** [comment]
@shanshanzheng-dev : can you please check above comment?

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 We don't support highlight tab currently. We recommend you to submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microso](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) Thanks.
