### ISSUE TITLE
Taskpane Button Menu validation based on option with SupportsMultiSelect enabled

### ISSUE THREAD

**Issue by EmilioAlbertoE** [OfficeDev/office-js#4598]
## Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
Host [Excel, Word, PowerPoint, etc.]: Outlook
Office version number: -
Operating System: macOS 14.3, Windows 11
Browser (if using Office on the web): Edge, Chrome 

## Expected behavior
Just shown the option that supports multi-select as you defined in the manifest

## Current behavior
We have an add-in with two button controls and multi-select support. So in the manifest we add the  <SupportsMultiSelect>true</SupportsMultiSelect> tag to just provide to one option the support to multi-select , but we are getting the "more app" option and 2 options been shown

## Steps to reproduce
1. Sideload add-in
2. Select multiple items in Outlook on the web
3. The add-in appears

![54fbfe21-9cae-4303-b051-a5976d1dab63](https://github.com/OfficeDev/office-js/assets/151851988/a63c26ee-e307-4f39-9286-7e811d60c8d4)

4. case info option is visible even if  <SupportsMultiSelect>true</SupportsMultiSelect> tag is not set in the manifest

5. clicking that option will break the add-in

## Context
we want to provide the tag mail option to support multi-select , just that option , case info should not be shown if the user multiselect since we do not want to support that option at this moment 

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by EmilioAlbertoE** [comment]
this is the piece where we defined the buttons and the permissions on the manifest with the  SupportsMultiSelect tag

<Hosts>
      <Host xsi:type="MailHost">
        <DesktopFormFactor>
          
          <FunctionFile resid="functionFile" />


          
          <ExtensionPoint xsi:type="MessageReadCommandSurface">
            
            <OfficeTab id="TabDefault">
              
              <Group id="msgReadGroup">
                <Label resid="groupLabel" />
                
                <Control xsi:type="Button" id="readTagEmail">
                  <Label resid="tagEmailLabel" />
                  <Supertip>
                    <Title resid="paneReadSuperTipTitle" />
                    <Description resid="paneReadSuperTipDescription" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="tagMailIcon16" />
                    <bt:Image size="32" resid="tagMailIcon32" />
                    <bt:Image size="80" resid="tagMailIcon80" />
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="readTagMailPaneUrl" />
                    <SupportsPinning>true</SupportsPinning>
                    <SupportsMultiSelect>true</SupportsMultiSelect>
                  </Action>
                </Control>

                <Control xsi:type="Button" id="readCaseInfo">
                  <Label resid="caseInfoLabel" />
                  <Supertip>
                    <Title resid="paneReadSuperTipTitle" />
                    <Description resid="paneReadSuperTipDescription" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="caseInfoIcon16" />
                    <bt:Image size="32" resid="caseInfoIcon32" />
                    <bt:Image size="80" resid="caseInfoIcon80" />
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="readCaseInfoPaneUrl" />
                    <SupportsPinning>true</SupportsPinning>
                  </Action>
                </Control>
                
              </Group>
            </OfficeTab>
          </ExtensionPoint>
          


          
          <ExtensionPoint xsi:type="MessageComposeCommandSurface">
            <OfficeTab id="TabDefault">
              
              <Group id="mailComposeGroup">
                <Label resid="groupLabel" />
                
                <Control xsi:type="Button" id="composeTagEmail">
                  <Label resid="tagEmailLabel" />
                  <Supertip>
                    <Title resid="paneReadSuperTipTitle" />
                    <Description resid="paneReadSuperTipDescription" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="tagMailIcon16" />
                    <bt:Image size="32" resid="tagMailIcon32" />
                    <bt:Image size="80" resid="tagMailIcon80" />
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="composeTagMailPaneUrl" />
                    <SupportsPinning>true</SupportsPinning>
                  </Action>
                </Control>

                <Control xsi:type="Button" id="composeCaseInfo">
                  <Label resid="caseInfoLabel" />
                  <Supertip>
                    <Title resid="paneReadSuperTipTitle" />
                    <Description resid="paneReadSuperTipDescription" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="caseInfoIcon16" />
                    <bt:Image size="32" resid="caseInfoIcon32" />
                    <bt:Image size="80" resid="caseInfoIcon80" />
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="composeCaseInfoPaneUrl" />
                    <SupportsPinning>true</SupportsPinning>
                  </Action>
                </Control>
                
              </Group>
            </OfficeTab>
          </ExtensionPoint>


          
          <ExtensionPoint xsi:type="AppointmentOrganizerCommandSurface">
            <OfficeTab id="TabDefault">
              
              <Group id="aptReadGroup">
                <Label resid="groupLabel" />
                
                <Control xsi:type="Button" id="appointmentTag">
                  <Label resid="tagCalendarEventLabel" />
                  <Supertip>
                    <Title resid="paneReadSuperTipTitle" />
                    <Description resid="paneReadSuperTipDescription" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="tagMailIcon16" />
                    <bt:Image size="32" resid="tagMailIcon32" />
                    <bt:Image size="80" resid="tagMailIcon80" />
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="appointmentTagMailPaneUrl" />
                    <SupportsPinning>true</SupportsPinning>
                  </Action>
                </Control>

                
                
              </Group>
            </OfficeTab>
          </ExtensionPoint>

          <ExtensionPoint xsi:type="AppointmentAttendeeCommandSurface">
            <OfficeTab id="TabDefault">
              
              <Group id="aptAttendeeReadGroup">
                <Label resid="groupLabel" />
                
                <Control xsi:type="Button" id="appointmentTagFromAttendee">
                  <Label resid="tagCalendarEventLabel" />
                  <Supertip>
                    <Title resid="paneReadSuperTipTitle" />
                    <Description resid="paneReadSuperTipDescription" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="tagMailIcon16" />
                    <bt:Image size="32" resid="tagMailIcon32" />
                    <bt:Image size="80" resid="tagMailIcon80" />
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="appointmentTagMailPaneUrl" />
                    <SupportsPinning>true</SupportsPinning>
                  </Action>
                </Control>

                
                
              </Group>
            </OfficeTab>
          </ExtensionPoint>

        </DesktopFormFactor>


        <MobileFormFactor>
          <ExtensionPoint xsi:type="MobileMessageReadCommandSurface">
              <Group id="mobileMsgReadGroup">
                <Label resid="groupLabel" />
                <Control xsi:type="MobileButton" id="mobileReadTagEmail">
                  <Label resid="tagEmailLabel" />
                   <Icon xsi:type="bt:MobileIconList">
                    <bt:Image size="25" scale="1" resid="tagMailIcon32" />
                    <bt:Image size="25" scale="2" resid="tagMailIcon32" />
                    <bt:Image size="25" scale="3" resid="tagMailIcon32" />
                    <bt:Image size="32" scale="1" resid="tagMailIcon32" />
                    <bt:Image size="32" scale="2" resid="tagMailIcon32" />
                    <bt:Image size="32" scale="3" resid="tagMailIcon32" />
                    <bt:Image size="48" scale="1" resid="tagMailIcon32" />
                    <bt:Image size="48" scale="2" resid="tagMailIcon32" />
                    <bt:Image size="48" scale="3" resid="tagMailIcon32" />
                  </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="mobileReadTagMailPaneUrl" />
                    <SupportsPinning>true</SupportsPinning>
                  </Action>
                </Control>

                <Control xsi:type="MobileButton" id="mobileReadCaseInfo">
                  <Label resid="caseInfoLabel" />
                   <Icon xsi:type="bt:MobileIconList">
                      <bt:Image size="25" scale="1" resid="caseInfoIcon32" />
                      <bt:Image size="25" scale="2" resid="caseInfoIcon32" />
                      <bt:Image size="25" scale="3" resid="caseInfoIcon32" />
                      <bt:Image size="32" scale="1" resid="caseInfoIcon32" />
                      <bt:Image size="32" scale="2" resid="caseInfoIcon32" />
                      <bt:Image size="32" scale="3" resid="caseInfoIcon32" />
                      <bt:Image size="48" scale="1" resid="caseInfoIcon32" />
                      <bt:Image size="48" scale="2" resid="caseInfoIcon32" />
                      <bt:Image size="48" scale="3" resid="caseInfoIcon32" />
                    </Icon>
                  <Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="mobileReadCaseInfoPaneUrl" />
                    <SupportsPinning>true</SupportsPinning>
                  </Action>
                </Control>
              </Group>
          </ExtensionPoint>
        </MobileFormFactor>

      </Host>
    </Hosts>

**Comment by zhngx1** [comment]
Is it happening only on Outlook web? Does it happen on Outlook Desktop or Outlook Mac?

**Comment by EmilioAlbertoE** [comment]
yes it's only happening on Outlook web. 

Outlook desktop it's working as expected without issues.

**Comment by zhngx1** [comment]
Thanks for reporting this issue regarding Taskpane Button Menu validation based on option with SupportsMultiSelect enabled. It has been put on our backlog. We unfortunately have no timelines to share at this point 

 

Internal tracking id: Office: 9257860

**Comment by lunarwtr** [comment]
I am also facing this problem.  I'd like to also mention that opening a taskpane in general from a Multi Select button is flat out broken.  Any way this can be reprioritized since it was reported in June?

**Comment by mobisw-msft** [comment]
Hey all,

This issue has been fixed and is now available worldwide for all accounts. Folks can confirm the same.

**Comment by EmilioAlbertoE** [comment]
HI , I will doble check and report back, but thanks for all the effort , appreciate it!
