### ISSUE TITLE
[Word Online] TypeError: Cannot read property 'Element' of null (in WordEditor.js)

### ISSUE THREAD

**Issue by Foundasys** [OfficeDev/office-js#46]
When I search the Word Online template below called 'Simple resume' I get an error:
https://onedrive.live.com/embed?cid=F26A6E4F9EA8E142&resid=F26A6E4F9EA8E142%211229&authkey=AN_ljhP-Ylax418&em=2&wdStartOn=1

My code:
```
return Word.run(function(context) {
		var options = Word.SearchOptions.newObject(context);
		options.matchWildCards = true;

		var searchResults = context.document.body.search('[[]*[]]', options);
		context.load(searchResults, 'text');

		return context.sync().then(function() {
			console.log(JSON.stringify(searchResults.items));
		});
	})
	.catch(function(error) {
		console.log('Error: ' + JSON.stringify(error));
		if (error instanceof OfficeExtension.Error) {
			console.log('Debug info: ' + JSON.stringify(error.debugInfo));
		}
	});
}
```

Error:
WordEditor.js:3303 Uncaught (in promise) TypeError: Cannot read property 'Element' of null
at wac_QWa.Jm (WordEditor.js:3303)
at wac_hM.wG (WordEditor.js:3339)
at wac_iLa.Jt (WordEditor.js:2316)
at wac_bLa.Jt (WordEditor.js:2303)
at wac_8Ka.vFd (WordEditor.js:2293)
at wac_Dd.Zh (MicrosoftAjax.js:5)
at wac_Dd.Fe (WordEditor.js:250)
at wac_8Ka.wFd (WordEditor.js:2292)
at wac_Dd.Zh (MicrosoftAjax.js:5)
at wac_Dd.Fe (WordEditor.js:250)

My hunch:
It could have something to do with the search-text : '[[]*[]]'

**Comment by Kaidali** [comment]
Hi, thanks for telling us about this issue. But I tried with your code, it give me correct search results. 
So can you please provide more information about the error you got? Do you run this code with other functions? Thanks.

**Comment by Foundasys** [comment]
Hi, I'm running the code in Google Chrome and use Cloud9 IDE to code in.

I will try Visual studio code and see if the error persists.
When running (just the code and nothing else) the code I also get the correct results but then the error.

Google Chrome:
![image](https://user-images.githubusercontent.com/6333708/35638427-5ec0cc1c-06b7-11e8-9199-24cf5acb1337.png)

Edge:
![image](https://user-images.githubusercontent.com/6333708/35638914-ba835e56-06b8-11e8-9787-c6d6da709adb.png)

**Comment by Foundasys** [comment]
Just searching for the word 'the' for example results in no errors. Maybe it's the wildcard option?

```
/* global Office, Word, OfficeExtension */

'use strict';

(function() {

    console.clear();

    Office.initialize = function(reason) {

        function ready() {

            Word.run(function(context) {
                    var options = Word.SearchOptions.newObject(context);
                    options.matchWildCards = false;

                    var searchResults = context.document.body.search('the', options);
                    context.load(searchResults, 'text');

                    return context.sync().then(function() {
                        console.log(JSON.stringify(searchResults.items));
                    });
                })
                .catch(function(error) {
                    console.log('Error: ' + JSON.stringify(error));
                    if (error instanceof OfficeExtension.Error) {
                        console.log('Debug info: ' + JSON.stringify(error.debugInfo));
                    }
                });

        }

        if (document.readyState !== 'loading') {
            ready();
        }
        else {
            document.addEventListener('DOMContentLoaded', ready);
        }
    };
}());
```

**Comment by Foundasys** [comment]
Sorry for the delay but this is no longer an issue anymore. Search works fine now.
