### ISSUE TITLE
Excel freezes and crashes upon opening a specific file 

### ISSUE THREAD

**Issue by LiubovKabir** [OfficeDev/office-js#4600]
## Environment

* Platform : PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft® Excel® for Microsoft 365 MSO (Version 2406 Build 16.0.17726.20078) 64-bit  (Preview Channel)
* Operating System: EditionWindows 11 Pro Version	23H2 OS build	22631.3737
* Session ID 1B7BE41F-F2C5-49C0-8E2E-FC2DC679EA90

The issue does not reproduce on earlier Excel versions 
 
## Expected behavior
 File opened and it is possible to interact with it using Velixo add-in

## Current behavior
Excel freezes and crashes after several seconds when open a certain workbook

## Steps to reproduce
1. Download Excel workbook from [Velixo help website](https://helpacumatica.velixo.com/support/solutions/articles/153000020104-financial-demo-report-templates-acumatica#Download-this-sample-file)
![image](https://github.com/OfficeDev/office-js/assets/1867964/ad0f7705-8026-471e-b78a-0f4568f26766)

2. Open file.
3. Click Cancel in pop-ups (_Allow and Continue_ can be clicked as well - same result)
![image](https://github.com/OfficeDev/office-js/assets/1867964/814d4783-0cac-4586-99cc-7bb289e0d8df)

## Useful logs
![Excel crashes Rapid Byte](https://github.com/OfficeDev/office-js/assets/1867964/ec639f67-93b4-4565-90dc-25a6647c8238)

**Comment by shanshanzheng-dev** [comment]
Hi @LiubovKabir Thanks for reporting this issue and detail information. When I download this workbook, I can not repro this issue. Could you try to open this workbook again to see if it works? My Excel version is Microsoft® Excel® for Microsoft 365 MSO (Version 2406 Build 16.0.17726.20078) 64-bit. 

https://github.com/OfficeDev/office-js/assets/125014206/335eef1d-4b9e-482f-b699-feb4bd78606a
