### ISSUE TITLE
Outlook add-in is not opening for some users in new Outlook for Windows UI

### ISSUE THREAD

**Issue by gs-skujala** [OfficeDev/office-js#4602]
The Outlook add-in that works in all other environments, including Outlook for Windows (not the new UI) will not open for some users when using the new UI.

## Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC
Host [Excel, Word, PowerPoint, etc.]: Outlook
Office version number: Microsoft Outlook Version 1.2024.516.100 (Production) (Client Version is 20240510004.32)
Operating System: Windows 11 Home (23H2 -- 22631.3447)

## Expected behaviour
The add-in needs to open up on the right side and starts loading

## Current behaviour
When add-in is selected from any existing email or new composing email, the add-in does not open at all

## Steps to reproduce
- Open outlook desktop app
- Open any existing email
- select add-ins icon
- Click on add-in that you want to open 

I can provide our add-in's manifest if needed, but it is not a publicly available. It also does not happen for all users, so it's unknown if you would be able to reproduce the issue.

Please review the screen recording of the issue
https://github.com/OfficeDev/office-js/assets/61771998/bb9393b5-68cf-4d4b-abbd-6cb1756bfd66

I am attaching the network calls and console logs that I was able to fetch from our user
[GSAssistConsoleLogs.log](https://github.com/user-attachments/files/15973723/GSAssistConsoleLogs.log)
[GSAssistNW.zip](https://github.com/user-attachments/files/15973725/GSAssistNW.zip)

Since there were so many network calls we observed,
We cleared everything and again saved the calls and logs that occurred after we tried to open our Add in where are provided below.
[GSAssistConsoleLogs2.log](https://github.com/user-attachments/files/15973738/GSAssistConsoleLogs2.log)
[GSAssistNW2.har.zip](https://github.com/user-attachments/files/15973740/GSAssistNW2.har.zip)

**Comment by illing2005** [comment]
Could be related to this issue:
https://github.com/OfficeDev/office-js/issues/4583

Are you using `mailbox.getUserIdentityTokenAsync`?

**Comment by gs-skujala** [comment]
@illing2005 Our add-in assets and code does not even load in the first place so it can even execute the officeJS APIs.

We generally use `mailbox.getUserIdentityTokenAsync` method somewhere inside our code but since the add-in related JS files does not load to begin with, we do not think our issue is related to [4583](https://github.com/OfficeDev/office-js/issues/4583)

**Comment by Swathy-Mothilal** [comment]
@gs-skujala, can you confirm if the network logs are from the bug reproduction case? We are not seeing any indications of failure in them.

Also, could you confirm whether other add-ins are functioning correctly on your end and check if 'Optional Connected Experiences' is enabled? For more information, please refer to this link: https://learn.microsoft.com/en-us/deployoffice/privacy/optional-connected-experiences.

**Comment by gs-skujala** [comment]
@Swathy-Mothilal I can confirm that the logs and network calls are recorded from the user who is facing the issue.
Our user has confirmed that they are facing this issue for 2 out of 4 add-ins that they have installed.
I've requested the user to check 'Optional Connected Experiences' is enabled or not and I will update here as soon as I here from them.
