### ISSUE TITLE
Broken "Always remember my choice for this application" checkbox and "Open" button for Excel Add-in's warning dialog

### ISSUE THREAD

**Issue by peterle1906** [OfficeDev/office-js#4604]
## Summary
When attempting to open a non-http URL to trigger a desktop application using an Excel Add-in (e.g., "myapplication://"), a warning dialog pops up offering options to Open or Cancel the process, along with a checkbox for "Always remember my choice for this application."

![excelAddinError](https://github.com/OfficeDev/office-js/assets/170699917/dd8556b1-c2eb-4e26-b846-7cead5cddfb1)

**First bug**: After clicking the "Open" button, the external desktop application opens as expected. However, if another click action is performed within the Excel Add-in, the screen turns dark, rendering me unable to interact with any other items on the Add-in page. Refreshing the Add-in restores it to its normal state.

**Second bug**: The "Open" button functions as expected, opening the external desktop application. However, if I check the "Always remember my choice for this application" checkbox and click "Open", the application opens normally. Yet, when I try to open the desktop application again, no action occurs; the desktop application does not launch, and there is no error logging in the console. I have to remove the application registry from `HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\WEF\Protocols\myapplication` to reset the warning dialog and click "Open" to launch my desktop application again.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2404 (Build 17531.20190)
* Operating System: Window
 
## Expected behavior
- The Excel Add-in should open the external desktop application when I click "Open" in the warning dialog, and normal operations should resume afterward.
- When the "Always remember my choice for this application" checkbox is checked and "Open" is clicked, it should open the external desktop application. Subsequent attempts to open the application should proceed without displaying the warning dialog.

## Current behavior
- Clicking "Open" in the warning dialog opens the external application, but subsequent clicks within the Excel Add-in cause the entire task pane to turn dark and become unresponsive until the add-in is refreshed.
- After selecting "Always remember my choice for this application" and clicking "Open", the application opens as expected. However, attempting to open the application again results in no action, with no warning dialog or application launch.

## Steps to reproduce

**Bug 1: Broken Open button**
1. Create a button in the Excel Add-in to open an external desktop application, linking it to a non-http URL (e.g., myapplication://).
2. Click the button.
3. A warning dialog appears; click "Open".
4. Return to the Excel Add-in, click anywhere, and observe that the screen turns dark.

**Bug 2: Broken "Always remember my choice for this application" checkbox**
1. Follow the same steps to open the external desktop application.
2. Check the "Always remember my choice for this application" checkbox.
3. Click "Open".
4. The application opens as expected.
5. Attempt to open the application again from the Add-in; note that there is no dialog or action to open the application.

**Comment by shanshanzheng-dev** [comment]
Hi @peterle1906 Thanks for reporting this issue. Could you share your test manifest to help us investigate this issue better? Thanks.

**Comment by peterle1906** [comment]
Hi @shanshanzheng-dev, yes, here's the manifest file 
[https://github.com/peterle1906/file/blob/main/manifest-test.xml](url)

**Comment by shanshanzheng-dev** [comment]
Hi @peterle1906 Thanks for providing this manifest. this manifest works good on my side. I understand your concern. If possible, could you share your test code or your repro video? We're trying to repro your issue. Thanks.

**Comment by peterle1906** [comment]
https://github.com/OfficeDev/office-js/assets/170699917/9f2a5650-b3f3-4b7e-95da-392abc3998bf

I'm using Angular and I noticed that the dark screen didn't appear on any blank component, just wondering if this is a style conflict. 

Also for the link in the blank screen, the Excel addin crashed and my machine went into a frozen state after I spam click the button. I'm not sure if this is because of my machine or because the bug, but I think it's worth to mention that

For the code, it just html with 
`<a style="top: 50; left: 50;" href="onenote://">This is an a tag with href='onenote://'</a>
`

**Comment by shanshanzheng-dev** [comment]
Hi @peterle1906 Thanks for these detail information, we'll be looking into this issue. In order to help us investigate, could  
 share us that Active Workpapers(Loacl) manifest? Because use my test add-in, I can't repro your problem. We will come back if we have a suggestion for you. Thanks.

**Comment by peterle1906** [comment]
Hi @shanshanzheng-dev, it is the same manifest that I sent you previously, I just removed some of the generics like names and Id to keep confidential privacy. 

[https://github.com/peterle1906/file/blob/main/manifest-test.xml](https://github.com/OfficeDev/office-js/issues/url)

**Comment by shanshanzheng-dev** [comment]
Hi @peterle1906 Sorry, I try to use your manifest, but I get a error. 
![image](https://github.com/OfficeDev/office-js/assets/125014206/8e26e43d-8cb1-4cb3-a2c8-fdb3b181e189)

For test add-in, open warning dialog works good:

https://github.com/OfficeDev/office-js/assets/125014206/0ab206c6-d0ba-40c2-be00-77ee3d90cb7d

**Comment by peterle1906** [comment]
Hi @shanshanzheng-dev, I just verify this one with my colleagues and seems like we all have the same error, I will try to create a small demo and send you a github repository link to test it

**Comment by peterle1906** [comment]
Hi @shanshanzheng-dev, I have tested the bugs again on several machines and have observed some results:

1. The second bug, when click "Always remember my choice for this application", it will not open any external link, only happen on Excel add-in version `Microsoft® Excel® for Microsoft 365 MSO (Version 2404 Build 16.0.17531.20190) 64-bit`, which I believed is the latest version. I tested with a machine on version `Microsoft® Excel® for Microsoft 365 MSO (Version 2403 Build 16.0.17425.20236) 64-bit` and couldn't reproduce the error.
2. For the first bug where the screen turns dark, we have spotted that this error only happen inside modal components or attempt to open a modal components after the warning dialog appear

This is our modal service to open a modal, using Bootstrap NgbModal

```
export const OVERLAY_DATA = new InjectionToken<{}>('OverlayData');

export interface ModalResponse<T = any> {
  id?: string;
  action: 'Add' | 'Update' | 'Delete';
  model?: T | null;
}

type BeforeDismissAction = ReturnType<NgbModalOptions['beforeDismiss']>;

@Injectable({
  providedIn: 'root'
})
export class ModalService {

  overlayPortal: Portal<any>;

  private _openedModals: NgbModalRef[] = [];

  constructor(private readonly _ngbModal: NgbModal,
    private _injector: Injector) {
  }

  openModal<T>(content: any, id: string = null, params: any = {}, options?: NgbModalOptions, beforeDismissAction?: (component: T) => BeforeDismissAction): Promise<any> {
    const consolidatedOptions = { ...{ size: 'lg', backdrop: 'static' }, ...options };
    if (content.modalSize) consolidatedOptions.size = content.modalSize;
    const modalRef = this._ngbModal.open(content, {
      ...consolidatedOptions,
      beforeDismiss: consolidatedOptions.beforeDismiss ?? (beforeDismissAction ? (() => beforeDismissAction(modalRef.componentInstance)) : null),
    } as NgbModalOptions);

    this._openedModals.push(modalRef);
    merge([modalRef.closed, modalRef.dismiss]).pipe(take(1)).subscribe(() => this._openedModals = this._openedModals.filter(m => m !== modalRef));
    if (id) modalRef.componentInstance.id = id;
    if (params) modalRef.componentInstance.params = params;
    return modalRef.result;
  }
}
```

I hope this help, let me know if you need more information

**Comment by shanshanzheng-dev** [comment]
Hi @peterle1906 Thanks for these detail information, for the second bug, I saw there is a latest version, you can try if you can repro. 
![image](https://github.com/OfficeDev/office-js/assets/125014206/cbe964b1-4a06-4bc6-b2a6-a6a364399ede)
 https://learn.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date
For my excel version, I can't repro this. 
![image](https://github.com/OfficeDev/office-js/assets/125014206/0cfcf5bf-b517-4fd1-aed5-b44c7dd21b09)
for the first bug, we'll look into if this is a style conflict. Thanks.

**Comment by peterle1906** [comment]
Hi @shanshanzheng-dev, sorry for the late reply. I can confirm that updating to version 2406 solved the second bug for excel. But the first bug still exist

**Comment by shanshanzheng-dev** [comment]
Hi @peterle1906  Thanks, about the first bug, we'd like to confirm with you, that is a style conflict. We recommend you to submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)
