### ISSUE TITLE
How to dynamically switch between read-only and editing modes of documents through the Word JavaScript API

### ISSUE THREAD

**Issue by anybody-1** [OfficeDev/office-js#4605]
I have a requirement now that during interface requests, users cannot edit documents and can only preview them. Editing can only be done after the interface request is completed
so, i want to know how todo by word js api

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @anybody-1. Connecting you with @wangyun-microsoft  who may be able to help.

**Comment by anybody-1** [comment]
![image](https://github.com/OfficeDev/office-js/assets/34483918/d738d5d4-447f-4f26-bee7-02ce2972fcab)
Or please tell me how to dynamically switch modes in the graph using the Word JavaScript API

**Comment by stevefengjin** [comment]
@anybody-1 Thanks for reaching out. Unfortunately, there is no existing Word JavaScript API that can meet this requirement yet. You may file a feature request in our community forum, and I have found a similar request https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/discerning-whether-a-document-is-in-quot-editing-quot-quot/idi-p/3985966, although it is for detecting not setting, you could open a new request for setting. And if you like to talk with us for a deeper discussion for your use case and business impact, please leave your contact info in this form: https://forms.office.com/r/QayRq1FVEb, and we will follow up and schedule a short meeting to discuss.
