### ISSUE TITLE
Office.auth.getAccessToken not supported in Outlook add-ins

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js#4606]
I am developing an add-in for Outlook and have noticed that the Office.auth.getAccessToken method is not supported in this context. Below is the code I am using to obtain an access token for the Microsoft Graph API:

```
try {
    const accessToken = await Office.auth.getAccessToken({
        allowSignInPrompt: true,
        allowConsentPrompt: true,
        forMSGraphAccess: true,
    });
} catch (error) {
    console.log("Error obtaining token", error);
}
```

Issue:
I have discovered that Office.auth.getAccessToken is not supported in Outlook add-ins.

Questions:

- Why is the Office.auth.getAccessToken method not supported in Outlook add-ins?

- What is the recommended method to obtain an access token for Microsoft Graph within Outlook add-ins?

Thank you in advance for your help.

**Comment by ottD** [comment]
@CodeCube0 The recommended way to obtain an access token for Microsoft Graph in an Outlook add-in is using nested app authentication (currently still in preview): https://learn.microsoft.com/en-gb/office/dev/add-ins/develop/enable-nested-app-authentication-in-your-add-in

**Comment by CodeCube0** [comment]
Thanks for the advice, do you happen to know when a stable version will be released? @ottD

**Comment by ottD** [comment]
@CodeCube0 No, I don't know but it will be before October 2024 according to this blog post: https://devblogs.microsoft.com/microsoft365dev/new-nested-app-authentication-for-office-add-ins-legacy-exchange-tokens-off-by-default-in-october-2024/
