### ISSUE TITLE
The onMessageRecipientsChangedHandler event does not get executed completely in Mac

### ISSUE THREAD

**Issue by RaveendraReshma** [OfficeDev/office-js#4607]
1. We are developing office web Addin for outlook using event based (Smart Alert) .The Addin is generated using office yo generator Task Pane add-in using the React framework.
2. We are getting the recipient data [ to/cc/bcc ] using Office.context.mailbox.item and we are rendering the same recipients onto the taskpane.
3. We have added the onMessageRecipientsChangedHandler event in the react component so when ever user adds any recipient the event gets triggered and the recipient gets painted onto the taskpane.
4. Issue that we are facing here is the event gets triggered but never completes its execution due to which the recipient rendering onto the taskpane is not happening.
5. We are facing this issue only in Mac Thick Client and everything works fine in safari browser.

## Your Environment
- Platform : MAC
- Host : Outlook on MAC
- Office version number : Version 16.84.1 (24042118)
- Operating System : MacOs
 
## Expected behavior
Event should get executed completely.

## Current behavior
event stops executing mid way and never completes.

## Link to live example(s)
<img width="857" alt="img" src="https://github.com/OfficeDev/office-js/assets/145095553/2dbea0ab-8731-4095-9f23-48a9504d5442">

**Comment by mmanjaree-msft** [comment]
@RaveendraReshma Can you share the code snippet of your handler function. We are unable to repro this issue at our end.

**Comment by RaveendraReshma** [comment]
@mmanjaree-msft 

Below is the event in the launchevents.js file. Where we are fetching the recipients and storing it.
```
let runningMRCH = false;
const onMessageRecipientsChangedHandler = async(event) => {
    let taskpaneOpen = localStorage.getItem("TaskpaneOpen");
    if (!runningMRCH && (taskpaneOpen == null || taskpaneOpen == "N")) {
        runningMRCH = true;
        const itemId = await getItemId();
        let recipientsTo;
		let recipientsCc;
		let recipientsBcc
        try {
                if (event.changedRecipientFields.to) {
                    recipientsTo = await fetchRecipient(
                        Office.context.mailbox.item.to
                    );                  
                } else if (event.changedRecipientFields.cc) {
                    recipientsCc = await fetchRecipient(Office.context.mailbox.item.cc);                   
                }
                else {
                    recipientsBcc = await fetchRecipient(
                        Office.context.mailbox.item.bcc
                    );
                }
				let allRecipients = [
                    ...recipientsTo,
                    ...recipientsCc,
                    ...recipientsBcc,
                ];
				updateCombineRecipientArray(itemId, allRecipients);

            
        } catch (error) {
            store.dispatch(
                setErrorMessage(
                    `err`
                )
            );
        }
        runningMRCH = false;
    } else {        
    }
};
```

Below is the event in react component to keep track of recipients when user enters recipients while taskpane is open.

```
useEffect(() => {
    Office.onReady(async () => {
      let itmID = await getItemId();
      localStorage.setItem("currentItemId", JSON.stringify(itmID));
      await setItemId1(itmID);
      const itemType = Office.context.mailbox.item.itemType;

      if (itemType === Office.MailboxEnums.ItemType.Message) {
        Office.context.mailbox.item.addHandlerAsync(
          Office.EventType.RecipientsChanged,
          onMessageRecipientsChangedHandler1
        );
      } 
  }, []);
  
let runningMRCH1 = false;
  async function onMessageRecipientsChangedHandler1(event) {
    localStorage.setItem("TaskpaneOpen", "Y");
    if (!runningMRCH1) {
      runningMRCH1 = true;
      const itemType = Office.context.mailbox.item.itemType;
      if (itemType === Office.MailboxEnums.ItemType.Message) {
        const itemId = await getItemId();
        let combineList = getRecipientsForItemId(itemId);
        if (event.changedRecipientFields.to) {
          let recipientsTo = await fetchRecipient(
            Office.context.mailbox.item.to
          );         
        }
        else if (event.changedRecipientFields.cc) {
          let recipientsCc = await fetchRecipient(Office.context.mailbox.item.cc);         
        }
        else {
          let recipientsBcc = await fetchRecipient(
            Office.context.mailbox.item.bcc
          );         
        }
      } else {
      }
      runningMRCH1 = false;
    }
    localStorage.setItem("TaskpaneOpen", "N");
  }
```

So basically we are storing the recipients fetched in launchevents.js file and painting the recipient data onto taskpane and along with this we are also real time update feature where when user enters recipients while taskpane is open then, we are appending the recipients and updating the recipient data in the taskpane.

**Comment by RaveendraReshma** [comment]
@mmanjaree-msft 

Here when user adds any recipients while taskpane is open, the event from react component should trigger and complete its execution so the recipient list gets updated so the taskpane will have the updated data.

**Comment by rkpathak** [comment]
@RaveendraReshma What do you mean by "event gets triggered but never completes"?
The platform is responsible for calling Addin event handler code and its calling the enevnt handler as you mentioned.
Add-in launch-event handlers are expected to be short-running, lightweight, and as noninvasive as possible. Its addin event handler that is responsible for calling [event.completed](https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailboxevent#outlook-office-mailboxevent-completed-member(1)) method. 
You can find more details here. https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/autolaunch#event-based-activation-behavior-and-limitations
