### ISSUE TITLE
How to get image using Shape getAsImage for Dynamic Images

### ISSUE THREAD

**Issue by KaranLala** [OfficeDev/office-js#4611]
For dynamic images, i.e. images that change based on a formula, the getAsImage function doesn't work. The format of the image is 'UNKNOWN' and the API cannot retrieve the image. Is there a way to download the image from this shape, or access the original image that this shape is referencing based on its formula? 

To see how I implemented dynamic images, see this youtube video: [https://www.youtube.com/watch?v=PVo2jHeDrbA](https://www.youtube.com/watch?v=PVo2jHeDrbA)

**Comment by shanshanzheng-dev** [comment]
Hi @KaranLala, could you share your code about call getAsImage is not work? And could you please share us more detail scenario what you want, do you want to convert a shape to an image? Thanks.

**Comment by KaranLala** [comment]
Hey yes, the code for getAsImage is below. I've also attached a excel file with two images in sheet1. This code should be able to read the first image, on the left, but not the second image, on the right. The image on the right will have the format 'UNKNOWN', which this code filters out to avoid an error, however, if you try to use getAsImage on the image on the right, it will throw an error.

[sample-getAsImage-not-working.xlsx](https://github.com/user-attachments/files/16037456/sample-getAsImage-not-working.xlsx)



```
/**
 * Retrieves all images from a specified worksheet.
 * @param {string} worksheetName The name of the worksheet.
 * @returns {Promise<any[]>} A promise that resolves to the collection of images in the worksheet.
 */
export const getImagesFromWorksheet = async (worksheetName: string): Promise<any[]> => {

    try {
        return await Excel.run(async (context) => {
            const sheet = context.workbook.worksheets.getItem(worksheetName);
            const shapes = sheet.shapes
            shapes.load('items');
            await context.sync();

            let images = shapes.items.filter(i => i.type == 'Image');
            images.forEach(img => img.load('image/format'))
            await context.sync();

            images = images.filter(img => img.image.format != 'UNKNOWN') //filters out dynamic images, which don't seem to work with getAsImage
            images.forEach(img => img.getAsImage(img.image.format))

            let imageData = images
                                .map(i => ({
                                        type: i.type, 
                                        top: i.top, left: i.left, height: i.height, width: i.width, 
                                        name: i.name, 
                                        format: i.image.format,
                                        image: i.getAsImage(i.image.format)
                                }));
            await context.sync();
            
            return imageData.map(i => ({ ...i, image: i.image.value }))
        });
    } catch (error) {
        console.error("Error retrieving images: " + error);
        throw error;
    }
};

```

**Comment by SiruiSun-MSFT** [comment]
Hi @KaranLala, Thanks for your reporting here! However, this seems like a by-design behavior.

Currently, the parameter of shape.getAsImage(format) just supports four types: 

>  Excel.PictureFormat.BMP, Excel.PictureFormat.PNG, Excel.PictureFormat.JPEG, and Excel.PictureFormat.GIF (Link: https://learn.microsoft.com/en-us/javascript/api/excel/excel.shape?view=excel-js-preview#excel-excel-shape-getasimage-member(1)).

Since the dynamic shape's image format is not involved into our common category, which return the "UNKNOWN" format as you mentioned. When you use "images.forEach(img => img.getAsImage(img.image.format))" this line in your code, the parameter comes to be "UNKNOWN", which is not supported here.

To overcome this issue here, we would like to encourage you to use maybe "PNG/JPEG" here, which will return the image you want. 
![image](https://github.com/OfficeDev/office-js/assets/86719968/c8a21d30-bf46-4dfc-bc26-57b0b56282f1)

Thanks again!
