### ISSUE TITLE
Enable and Disable Add-in Commands for Word Add-in

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4612]
<Enable>False</Enable> setting works fine for Word Desktop but not for online Word.
Can you please tell me how to make it work for Online Word also?

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 you can leverage this reference: https://learn.microsoft.com/en-us/office/dev/add-ins/design/disable-add-in-commands

**Comment by ishanig11** [comment]
I am using references from same URL. It worked for all applications except Word online.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 could you share your the whole code, we'll try to repro your issue. Thanks.

**Comment by ishanig11** [comment]
Desktop Word image : command is disabled
![image](https://github.com/OfficeDev/office-js/assets/157671419/39f85cdf-f3b9-499a-b858-16692d9bb4b4)

Online Word image: command is not disabled
![image](https://github.com/OfficeDev/office-js/assets/157671419/829d7c84-3739-49b3-9833-213d1fbb5b5b)


Used same manifest file at both places. You can refer Enabled tag under manifest file.
[manifest.zip](https://github.com/user-attachments/files/16025211/manifest.zip)

**Comment by shanshanzheng-dev** [comment]
Thanks for providing this information, we'll take a look and will report back if we have a suggestion for you. Thanks.

**Comment by ishanig11** [comment]
@shanshanzheng-dev : Its working fine.. Nice to have this feature.
You can close this ticket
