### ISSUE TITLE
Custom function not working properly in Excel online

### ISSUE THREAD

**Issue by nadeemAshfaq** [OfficeDev/office-js#4613]
I have an Excel custom function that gets the whole column as a parameter that is working fine on the desktop but in Excel online it's not getting the whole column as a parameter I went through the office documentation but did not find any solution can anybody help me with this?

you can get all the details from here https://github.com/OfficeDev/Office-Addin-Scripts/issues/866

**Comment by shanshanzheng-dev** [comment]
Hi @nadeemAshfaq Thanks for reporting this issue, could you share us your code about this custom function? We're trying to repro your issue.

**Comment by nadeemAshfaq** [comment]
Hi @shanshanzheng-dev this is how my JSDoc written 
![image](https://github.com/OfficeDev/office-js/assets/123717307/fff4b98b-3b45-41b1-ad63-0d4fe28fe06e)
and when I run npm build this is how my JSON file looks like 
![image](https://github.com/OfficeDev/office-js/assets/123717307/100079b8-e5d2-44a7-a959-8c001bd118c4)
It works fine on the desktop and gets (A:A) as a parameter but when I try the same thing in Excel online it returns "#CALC!"

**Comment by shanshanzheng-dev** [comment]
Hi @nadeemAshfaq  could you please share your custom function?

**Comment by nadeemAshfaq** [comment]
Do you want me to share the whole code with you?

**Comment by shanshanzheng-dev** [comment]
Yes, if possible. Because we try to repro your issue and that helps us investigate root cause. Meanwhile, could you share your repro steps? Thanks.

**Comment by nadeemAshfaq** [comment]
> Yes, if possible. Because we try to repro your issue and that helps us investigate root cause. Meanwhile, could you share your repro steps? Thanks.

Sorry I cannot share my full code here I think I already provided the necessary information

**Comment by shanshanzheng-dev** [comment]
OK, Thanks. We'll be looking into this issue. We'll report back if we have an suggestion for you.

**Comment by nadeemAshfaq** [comment]
any update?

**Comment by XuanZhouMSFT** [comment]
@nadeemAshfaq Thanks for the waiting and reporting this issue. It has been put on our backlog #9120326. We will update once we have some progress.

**Comment by XuanZhouMSFT** [comment]
@nadeemAshfaq Currently, the custom function has a limitation in online that the max cells number for input parameter should be less or equal to 10000. So we'd like to suggest you split your inputs when you use it.

**Comment by nadeemAshfaq** [comment]
> @nadeemAshfaq Currently, the custom function has a limitation online that the max cell number for the input parameter should be less or equal to 10000. So we suggest you split your inputs when you use it.

Okay, thanks for this information. Is there any chance in the future that it takes (A: A)?

**Comment by XuanZhouMSFT** [comment]
Thanks for the good questions. The item to expand the limitation is in our backlog but no plan to fix it in the short term. We recommend you to upvote or submit a new [Tech Community New Ideas item](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform), this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.
