### ISSUE TITLE
Office.onReady() and Office.Initialize() get stuck/hangs intermittently in spam addins.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#4618]
# Provide required information needed to triage your issue
Spam addins hang because office.onready() and/or office.initialize() get stuck on loading.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC, WEB, Browser
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: NA
* Operating System: NA
* Browser (if using Office on the web): Chrome
 
## Expected behavior

Office.OnReady or Office.Initialize should work all the time under the right conditions.

## Current behavior

Both/Either of the APIs get stuck and the spam addin is left hanging.

## Steps to reproduce

Currently I don't have exact steps to reproduce.
However, it can be reproduced reliably in my environment in one of the emails I received.
I tried exporting the email as an msg file, imported it but could not repro using the imported msg file.

## Link to live example(s)

None

# Provide additional details

A video which shows this behavior will be provided via email. 
Thanks for understanding.

## Context

This makes the spam addin solution unreliable unfortunately.

## Useful logs

Again, a video which shows this behavior will be provided via email.  

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by mmanjaree-msft** [comment]
@glr0221 Can you please share any console logs you see for new outlook when you run into this issue. This will help us in out investigation. Also if possible any screenshot of the behavior you are seeing

**Comment by glr0221** [comment]
@mmanjaree-msft would be happy to help. How do I get the logs from the browser or new look outlook? Or are you referring to the browser's console logs? Thanks

**Comment by mmanjaree-msft** [comment]
@glr0221 Whenever and wherever this issue is encountered please share the browser console logs. To open devtools in new desktop outlook follow this https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/one-outlook#debug-your-add-in.

Also if possible please share your initialization code

**Comment by glr0221** [comment]
@mmanjaree-msft 

Thank you for your responses. As for the initialization code, I am using the same code as the spam addin sample : 

```
// Ensures the Office.js library is loaded.
Office.onReady(() => {
  /**
   * IMPORTANT: To ensure your add-in is supported in the classic Outlook client on Windows,
   * remember to map the event handler name specified in the manifest to its JavaScript counterpart.
   */
  if (Office.context.platform === Office.PlatformType.PC || Office.context.platform == null) {
    Office.actions.associate("onSpamReport", onSpamReport); }
});
```

As for the console logs, there was nothing in there. Except that a deprecated feature is used warning gets incremented each time the Office.onReady() is called. 

![image](https://github.com/OfficeDev/office-js/assets/3444844/4ec4e831-dcb5-44dd-9083-25257761952b)

I hope this helps.

**Comment by Swathy-Mothilal** [comment]
@glr0221 Unfortunately, we are unable to repro the issue on our end. Could you please share a repro video, logs and the manifest where you are experiencing the issue? This will help us debug more effectively.

Since you mentioned that you can repro the issue in one particular email, could you please try to repro it in other emails and let us know the results please?

**Comment by glr0221** [comment]
Hello Swathy. Unfortunately, it is the only email right now where this is happening. I have seen this happen before in other emails but could not reproduce with those emails any longer. This one email though can reproduce it 100% as of right now. We will be sending the video and other details to Microsoft directly as we are communicating via email with the spam addin team as well. Thank you.

**Comment by glr0221** [comment]
@Swathy-Mothilal @mmanjaree-msft 

I agree on closing this ticket. I have not reproduced this for quite some time now. I have lost track of the two email samples I had that could reproduce this issue 100%. What I remember though is that, these 2 emails where the bug could be reproed, were moved from inbox-to-deletedItems for so many times. That was the only clue I had. But right now, I could not reproduce it anymore.

Thank you very much.
