### ISSUE TITLE
Incorrect Font Color Returned by MS Office API

### ISSUE THREAD

**Issue by punyakrishna** [OfficeDev/office-js#4620]
**Description:**
When using the MS Office API to retrieve font color, the API returns the color as black (`#000000`) even though the actual color is white (`#FFFFFF`). This issue occurs consistently and affects the accuracy of the retrieved document styling.

**Environment:**
- **API version:** 1.1
- **Operating system:** Windows
 
**Expected behavior:**
The API should return the correct font color value, which in this case is white (`#FFFFFF`).

**Current behavior:**
The API incorrectly returns the font color as black (`#000000`).

**Steps to reproduce:**
1. Open the attached document in MS Office.
2. Note the font color of the text segment in the document is set to white (`#FFFFFF`).
3. Use the provided code to get the font color of the text.
4. Observe that the API returns black (`#000000`) instead of white (`#FFFFFF`).

**Document and Code:**
**Screenshot:**
![image](https://github.com/OfficeDev/office-js/assets/95617525/176ab892-c255-4284-b597-a52b84707690)

**Attached Document:**
[font-issue-doc-author-removed.docx](https://github.com/user-attachments/files/16028531/font-issue-doc-author-removed.docx)

**Code Snippet:**
```javascript
 $("#run").on("click", () => run());
async function loadFirstTableFontColors() {
  await Word.run(async (context) => {
    const documentTables: Word.TableCollection = context.document.body.tables.load();
    await context.sync();

    // Load font data from the first table
    const firstTable = documentTables.items[0];

    const firstTableRows: Word.TableRowCollection = firstTable.rows.load();
    await context.sync();

    let fontData = new Array(firstTableRows.items.length);

    for (let rowIndex = 0; rowIndex < firstTableRows.items.length; rowIndex++) {

      const firstTableRowCells: Word.TableCellCollection = firstTableRows.items[rowIndex].cells.load();
      await context.sync();

      fontData[rowIndex] = new Array(firstTableRowCells.items.length);

      for (let cellIndex = 0; cellIndex < firstTableRowCells.items.length; cellIndex++) {
        const cell = firstTableRowCells.items[cellIndex];

        cell.body.font.load();
        await context.sync();
        const cellFont = cell.body.font;

        await context.sync();

        fontData[rowIndex][cellIndex] = cellFont.color;
      }
    }
    console.log("First Table Font Colors:", fontData);
  });
}

function run() {
  loadFirstTableFontColors().catch((error) => {
    console.error("Error loading font colors:", error);
    if (error instanceof OfficeExtension.Error) {
      console.error('Debug info:', JSON.stringify(error.debugInfo));
    }
  });
}```

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @punyakrishna! Connecting you with @shanshanzheng-dev who may be able to help.

**Comment by shanshanzheng-dev** [comment]
Hi @isabela-dominguez, Thanks for reporting this issue. We'll be looking into this problem and we'll report back if we have a suggestion for you. Thanks.

**Comment by jipyua** [comment]
hi @isabela-dominguez thanks for letting us know about this. If you input some text in the following table cells as below, you can see that the text color is actually shown as black. As for the first row, in the ooxml level, the color is stored as  <w:color w:val="auto"/>, for rendering purpose compared with the background, it's shown as white from UI. And at this case, at API level we are all returning them as black. 

![image](https://github.com/OfficeDev/office-js/assets/22437953/e45acd45-f2b2-4e23-929c-f7ec4c4685eb)

**Comment by punyakrishna** [comment]
I found the solution with your assistance. The issue is now resolved. Thank you very much for your support!
