### ISSUE TITLE
Excel Add-in API functionality for storage, identity, and notes

### ISSUE THREAD

**Issue by DevonFulcher** [OfficeDev/office-js#4621]
We are developing an Excel Add-in in Javascript and want to understand the API better.

- Our application needs to store data in a way similar to [Google Sheets Properties Service](https://developers.google.com/apps-script/guides/properties). However, I have not been able to find a method that supports this in the API documentation. For instance, [Excel.CustomProperty only supports data up to 255 characters](https://learn.microsoft.com/en-us/javascript/api/excel/excel.customproperty?view=excel-js-1.17#excel-excel-customproperty-value-member). Is there a method for storing larger amounts of arbitrary data?

- Our application needs to behave differently based on which user is accessing the Add-in. However, I have not found a method for getting the user's identity, such as email or username. Is there a method for getting the user's identity without requiring that they login (i.e. we do not want to use SSO or Microsoft Graph)?

- Finally, we would like to request that [support for Notes](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/add-support-for-notes-to-office-js-api-for-excel/idi-p/4017916) be added to the API.

Thanks in advance for the help!

**Comment by isabela-dominguez** [comment]
Thank you for sharing this issue @DevonFulcher. This looks like a programming question; would you please be able to submit it to https://stackoverflow.com/questions/tagged/office-js ?

**Comment by DevonFulcher** [comment]
Thank you. I asked this question [here](https://stackoverflow.com/questions/78692645/excel-add-in-api-functionality-for-storage-identity-and-notes).

**Comment by shanshanzheng-dev** [comment]
Hi @DevonFulcher, Thanks for your questions. I'd like to provide you with answers:
1. Yes, we have the 255 limitation and no workaround in API side.
2. No, they have to use SSO and get the user's consent to get their "login".
3. The Note API is in our backlog and under implementation, but sorry we can't share the timeline.
Thanks.
