### ISSUE TITLE
Is there a way to read the format of individual characters in an Excel Cell?

### ISSUE THREAD

**Issue by KaranLala** [OfficeDev/office-js#4623]
In Excel, it is possible to format the text within each cell separately. For example if cell A1 has the text 
<img width="67" alt="fX1Ek" src="https://github.com/OfficeDev/office-js/assets/5331717/f76d2154-1243-4044-aab6-c6e434e0bdaf">

you can format it on individual characters like so
<img width="68" alt="Ckss3" src="https://github.com/OfficeDev/office-js/assets/5331717/ec1668b7-ca8c-497a-a39d-9c5009c57314">

However, when using the officeJS API, formatting is only returned on a cell level. Is it possible to get formatting on a character level?

See this stackoverflow question for more info: [Excel Formatting Question](https://stackoverflow.com/questions/56428428/formatting-individual-characters-in-a-cell-in-excel-using-office-js)

**Comment by adrianwu8516** [comment]
Hi @KaranLala , 

We do not currently support such operations at the API level, but it's in our backlog. 
It would be very helpful if you could help us upvote the feature request post in the technical forum so that we can better prioritize it. You can check this post below and see if it meets your expectations, or create a new post for a new feature request. Thank you very much for the suggestion. 

https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/richtext-support-excel-js-api/idi-p/3033874

**Comment by adrianwu8516** [comment]
Hi @KaranLala 

Thank you for your patience. The requested rich text support feature has been implemented and will be included in the upcoming Excel requirement set 1.18 release, scheduled for February 2025. In the meantime, you can already experiment with these capabilities in the beta build.

The following APIs will be available:

- `Excel.CellPropertiesInternal.TextRuns`
- `Excel.CellPropertiesLoadOptionsInternal.TextRuns`
- `Excel.RangeTextRun.Text`
- `Excel.RangeTextRun.Font`

For more details, please refer to the [official documentation](https://learn.microsoft.com/en-us/javascript/api/excel/excel.rangetextrun?view=excel-js-preview). Below is a sample code snippet that demonstrates how you can use rich text formatting in cells:

```javascript
(async () => {
  await Excel.run(async (context) => {
    var sheet = context.workbook.worksheets.getItem("TestSheet");
    const cellSrc = sheet.getRange("A1");
    const cellSrcTextRun: Excel.SettableCellProperties = {
      textRuns: [
        { text: "Sample", font: { bold: true, color: "#00B0F0", size: 14, italic: true } },
        { text: "1", font: { subscript: true } },
        { text: "String" },
        { text: "2", font: { superscript: true, color: "black", tintAndShade: 0.5 } },
      ],
    };

    cellSrc.clear(Excel.ClearApplyTo.all);
    cellSrc.setCellProperties([[cellSrcTextRun]]);
    await context.sync();

    const textRunCellProperty = cellSrc.getCellProperties({ textRuns: true });
    await context.sync();

    const cellTextRuns = textRunCellProperty.value[0][0].textRuns;
    console.log(JSON.stringify(cellTextRuns, undefined, "  "));
  });
})();
```

If you have any further questions or feedback, feel free to let us know!

**Comment by KaranLala** [comment]
This is great news! thank you for the update.

**Comment by aryannipane** [comment]
Hi, thanks for the updates!

I want to ask if there's a way to get the formatting (like bold, italic, color, font size) applied to individual characters within a cell using the Excel JavaScript API.

For example, if a single cell contains text with mixed formatting (e.g., "He**ll**o" where just "ll" is bold), is there a way to get the formatting details for each character or text range?

![Image](https://github.com/user-attachments/assets/d1d956c4-d751-4cb6-9bc0-c7019ff1ddea)

Appreciate any guidance on this!
