### ISSUE TITLE
How to access the currently displayed / rounded off value of a cell in Excel

### ISSUE THREAD

**Issue by DJay921** [OfficeDev/office-js#4625]
How can I access the currently displayed value of a given cell range but not the actual value of that cell? For example - see this below image, where I have not increased the width of the cell enough to display the actual value which is getting rounded off.

If I try to get the `Range `for this cell and access the `values `property, it gives back `12.001123`. I tried the `text `property as well from the documentation, but it gives back the `12.001123 `as well. I want to access the value that is showing up right now in the UI i.e. `12.00112` after the rounding off

![image](https://github.com/OfficeDev/office-js/assets/14841097/833acc16-7525-46a4-ada7-365f3f01b2c3)

**Comment by shanshanzheng-dev** [comment]
Hi, @DipanshuJuneja Thanks for reaching us. Could you provide more detail scenario? If you want to set values property, let it show up the rounding off value, just like this:
![image](https://github.com/OfficeDev/office-js/assets/125014206/4eca869a-3bdf-4541-88b5-44791cdaa882)
Or you want to set rounding off value use some JS API?

**Comment by DJay921** [comment]
Hi @shanshanzheng-dev thanks for your quick response on the query. I simply want to get/access the rounded off value through Office JS, in this case 12.00112, since the `values` property on the `Range` class gives back the actual 12.001123.

**Comment by shanshanzheng-dev** [comment]
Hi @DipanshuJuneja Thanks for confirming. Could you take a look this reference if it can meet your need: https://learn.microsoft.com/en-us/javascript/api/excel/excel.formattednumbercellvalue?view=excel-js-preview? And this is an example: https://raw.githubusercontent.com/OfficeDev/office-js-snippets/prod/samples/excel/20-data-types/data-types-formatted-number.yaml
