### ISSUE TITLE
First request to save custom properties always fails in New Outlook for Windows

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js#4628]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop - New Outlook
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: New Outlook
* Operating System: Windows
* Browser (if using Office on the web): New Outlook
 
## Expected behavior

When saving the custom properties (after setting them) for the first time in an event-based add-in (onMessageCompose), the properties are successfully saved

## Current behavior

When saved for the first time, the operation throws an internal error
![image](https://github.com/OfficeDev/office-js/assets/65173226/b1d69fef-0b39-4821-b74e-15c731d5a4b6)

The error comes after a failed post request to `https://outlook.office.com/owa/service.svc?action=SaveExtensionCustomProperties&app=Mail&n=1336`

![image](https://github.com/OfficeDev/office-js/assets/65173226/f210ee15-91f9-4116-bdf3-faeb662c48a7)

## Steps to reproduce

1. Use a manifest that has event-based activation. OnMessageCompose event
2. Have a set and saveAsync in the implementation

Example:
```
mailboxItem.loadCustomPropertiesAsync(
          asyncResultCallback(
            (result) => {
              result.set(this.settingName, newValue);
              result.saveAsync(asyncResultCallback(resolve, reject));
            },
            (error) => {
              owaLogEvent(
                'Unknown',
                `Unable to set CustomProperty "${this.settingName}"`,
                error,
              );
              resolve(undefined);
            },
          ),
        );
```

3. Open New Outlook for Windows
4. Create a new message so that the event is triggered

## Useful logs

- [x] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Swathy-Mothilal** [comment]
@bogdanst24 We are unable to reproduce the issue. Could you please provide a manifest and a video of  the issue so we can investigate it more effectively?

**Comment by bogdanst24** [comment]
Probably important to emphasize that it was working for a long time without issues.
I can reproduce it with this very basic add-in:

```
void Office.onReady(() => {});
Office.actions.associate(
  'onMessageComposeHandler',
  (event: Office.AddinCommands.Event) =>
    void onMessageComposeHandler(event),
);
```

```
export function onMessageComposeHandler(
  event: Office.AddinCommands.Event,
  contextParameters: WebAddInContextParameters,
) {
  Office.context.mailbox.item?.loadCustomPropertiesAsync((result) => {
    if (result.status === Office.AsyncResultStatus.Failed) {
      console.log('ERROR', result.error);
    }
    const allValues = result.value.get('test');
    console.log('allValues', allValues);

    result.value.set('test', 'testValue');
    result.value.saveAsync((result) => {
      console.log('saveAsync', result);
    });
  });
}
```

Result:
![image](https://github.com/OfficeDev/office-js/assets/65173226/924b08ec-9c75-497a-bfe7-e23cd308b009)


Relevant part in the manifest:
```
 <ExtensionPoint xsi:type="LaunchEvent">
              <LaunchEvents>
                <LaunchEvent Type="OnNewMessageCompose" FunctionName="onMessageComposeHandler" />
                ....
              </LaunchEvents>
</ExtensionPoint>
```

I can send the full manifest via email, but I find it useless as you won't be test with it.              

Later edit:
I can reproduce it also by using the simple code from the Script Lab (moving it into an event based one)

**Comment by bogdanst24** [comment]
Again, I can only reproduce it in the New Outlook for Windows.
![image](https://github.com/OfficeDev/office-js/assets/65173226/7ec196a0-5c45-4fb6-a2e9-e6c9437aa304)

**Comment by Swathy-Mothilal** [comment]
@bogdanst24 Based on the details that you have provided, we are still unable to repro the issue. Could you please share your manifest and a video of the issue to understand the issue better?

**Comment by bogdanst24** [comment]
Could you please share an email address I can send to?

**Comment by Swathy-Mothilal** [comment]
@bogdanst24 Please host your manifest in a private repo, and grant access to me!

**Comment by bogdanst24** [comment]
Done. You won't be able to log in, but that shouldn't matter as the issue is reproducible before that. Triggering a new email is enough. You should be able to see 3 Post requests ending up with 400 status code

![image](https://github.com/OfficeDev/office-js/assets/65173226/54bcfcec-1a24-4f3d-a372-c6557c793a40)

**Comment by Swathy-Mothilal** [comment]
@bogdanst24 We have been able to reproduce the issue. To better understand the problem, could you please confirm if subsequent requests after logging in or saving custom properties again are successful as this seems to be an auth problem.

**Comment by bogdanst24** [comment]
> To better understand the problem, could you please confirm if subsequent requests after logging in or saving custom properties again are successful

Yes, exactly. What you are seeing now being logged, are some operations we introduced as a workaround. Exactly because, as described also in the title of the issue, only the first one seems to fail. Or, it might be all operations for the first x seconds.

>  this seems to be an auth problem.

No specific authentication is performed. I think we have been seeing this error in our logs for a long time for some customers (~20%), but we were never able to reproduce it. Now, since 2-3 weeks ago, it is affecting everyone.

**Comment by Swathy-Mothilal** [comment]
@bogdanst24 Thanks for the clarification. It has been put on our backlog. We, unfortunately, have no timelines to share at this point.
Internal tracking id: Eg: Office: 4707994

**Comment by lmrodriguez78** [comment]
Hi.
We have been going over the same issue for the last days. 

Is there any workaround we could implement to tackle the issue while it is in progress?

In our case, we have an event based add-in. We set the value of a custom property when the user clicks on a command buttom. This property is used later to implement the logic when the message is sent. 


Thanks.

**Comment by bogdanst24** [comment]
We're doing a mock set and save right at the beginning. We've seen that this forces it to work in some cases, but not all. The problem is still happening and from what I can see on the logs, it got worse.

**Comment by lmrodriguez78** [comment]
Thanks @bogdanst24. We've implemented a retry mechanism with a one second delay between calls. Apparently it seems to work but let's see in the upcoming days.

**Comment by kumarshrey-msft** [comment]
This issue has been fixed. Thank you for raising the issue and helping us make the product better.
