### ISSUE TITLE
Cannot read properties of undefined (reading 'messageParent') After redirecting my html file on Web Outlook

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js#4629]
# After redirecting my html file getting `messageParent` error on web outlook

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: __web_Outlook__
* Host [Excel, Word, PowerPoint, etc.]: ___Outlook___
* Office version number: __Web__
* Operating System: ___Web___
* Browser (if using Office on the web): ___Chrome ___
 
## Expected behavior

working correctly on desktop Outlook but not working on Web 
I am trying to do SSO not with Microsoft I am opening office dialog for login After successfully login I am redirecting to my html file 
`https://localhost:3000/assets/redirect.html` and got the code `redirect.html?code=RIaDfTxLDxUvRWLZWNox0EcIeUz9FT` from login but when I am trying to send message `Office.context.ui.messageParent(code)` getting error `Cannot read properties of undefined (reading 'messageParent')`

## Current behavior

here's the full video of Current behavior [issue Loom video link ](https://www.loom.com/share/ed9147a25264406dab2294fcbc17772a?sid=6e219176-7437-44b9-bf55-de7cb8c28f01)

## Link to live example(s)

1. [__Loom Video__](https://www.loom.com/share/ed9147a25264406dab2294fcbc17772a?sid=6e219176-7437-44b9-bf55-de7cb8c28f01)

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by junaid042** [comment]
@exextoc can you please check this what's the issue?

**Comment by Swathy-Mothilal** [comment]
@junaid042 Could you please share your manifest link, so that we can repro the issue?

**Comment by junaid042** [comment]
HI @Swathy-Mothilal this is my [manifest ](https://drive.google.com/file/d/1Rh6HPE1GHC-G4JPcklIkmq7KsBNTa5Bt/view?usp=sharing)

**Comment by Swathy-Mothilal** [comment]
@junaid042 Kindly share a hosted manifest as the manifest shared above is pointing to localhost.

**Comment by junaid042** [comment]
Hi @Swathy-Mothilal This is the live [manifest ](https://github.com/junaid042/TitanFile/blob/main/manifest.xml)

**Comment by rkpathak** [comment]
@junaid042 The dialog box's domain should be the same as the domain of the host page. Which is not the case in your manifest. For details refer: 
https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#open-a-dialog-box-from-a-host-page

**Comment by junaid042** [comment]
@rkpathak if my login domain is not same then manifest app domain then dialog will not open. in my case dialog is opening and working correctly on desktop outlook but not on web you can see in the loom video that I have shared

**Comment by junaid042** [comment]
@rkpathak if my login domain is not same then manifest app domain then dialog will not open. in my case dialog is opening and working correctly on desktop outlook but not on web you can see in the loom video that I have shared

**Comment by rkpathak** [comment]
@junaid042 Can you try what is suggested in the documentation about the domain. Make it Display dialog part of the same domain and check.
