### ISSUE TITLE
Token B still valid when click on logout in Outlook

### ISSUE THREAD

**Issue by iraviguggilam** [OfficeDev/office-js#4633]
We are using **on_behalf_of** SSO process in outlook Addin. 
Token A generated using OfficeRuntime.auth. getAccessToken

`
let bootstrapToken = await OfficeRuntime.auth.getAccessToken({
  allowSignInPrompt: true,
});
`
Below is the reference for on_behalf_of flow

![protocols-oauth-on-behalf-of-flow](https://github.com/OfficeDev/office-js/assets/118201312/c0225957-a66f-4f1d-aa93-ea7724226f8e)

Issue is when User logout from outlook Token B( which is generated on top of Token A) is still valid.

**Comment by mattgeim** [comment]
@iraviguggilam -  Is your question about the access token your middle tier receives from Microsoft Entra when doing the token exchange for the token it gets from Office when calling getAccessToken, or something else?  If you are looking for more information on tokens on the Entra ID side, you can find relevant information that could help you here:  https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens

**Comment by iraviguggilam** [comment]
My Question is ( refer the image, shared earlier)
Token A has some expire time, as I generated the Token B will be valid or not. If Token A expires ???

**Comment by mattgeim** [comment]
This is a question for the Entra ID team on On-Behalf-of flows and token issuance/expiration.  You can find the options for doing so here: 

https://learn.microsoft.com/en-us/entra/identity-platform/developer-support-help-options

Feel  free to reopen this issue if I misunderstood your question.
