### ISSUE TITLE
Alternative Approaches to Implementing Pre-Send Email Functionality in Outlook Desktop

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js#4634]
Why is the “OnMessageSend” event not supported in Outlook desktop? The “ItemSend” event is too invasive. The “OnMessageSend” event is also invasive but its behavior is already improving. Isn't there some other way we can try?

**Comment by millerds** [comment]
Can you clarify what you are experiencing?  Outlook desktop and web both support OnMessageSend:

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/onmessagesend-onappointmentsend-events?tabs=windows

**Comment by CodeCube0** [comment]
While on Outlook Web the value of the id and message-id of the draft is maintained even after sending, on Outlook Desktop the id and message-id are also changed. @millerds

**Comment by AlexJerabek** [comment]
I'm going to move this issue from the documentation repo to the product repo (OfficeDev/office-js) where it can get better attention.

**Comment by zhngx1** [comment]
Is the issue about “OnMessageSend” not working or item id changing for drafts?
