### ISSUE TITLE
Is it possible to set an RGB color for a font highlight color?

### ISSUE THREAD

**Issue by hannaDefinely** [OfficeDev/office-js#4638]
# Summary of the issue
I'm trying to set the highlight color for a range font, but it seems that only the standard highlight colors are available for this purpose.  I see in the documentation that there is a limitation in Office for Windows Desktop:

> highlightColor - Specifies the highlight color. To set it, use a value either in the '#RRGGBB' format or the color name. To remove highlight color, set it to null. The returned highlight color can be in the '#RRGGBB' format, an empty string for mixed highlight colors, or null for no highlight color. Note: Only the default highlight colors are available in Office for Windows Desktop. These are "Yellow", "Lime", "Turquoise", "Pink", "Blue", "Red", "DarkBlue", "Teal", "Green", "Purple", "DarkRed", "Olive", "Gray", "LightGray", and "Black". When the add-in runs in Office for Windows Desktop, any other color is converted to the closest color when applied to the font.

What about the '#RRGGBB' format in Office for MacOS and Web? Is it possible to use it? Or are there any plans to improve this functionality for Office for Windows Desktop in a future release?

## Your Environment

* Platform: Windows (PC desktop)
* Host: Word
* Office version number: Version 2406 Build 16.0.17726.20078
* Operating System: Windows 10
 
## Expected behavior
It is possible to use the #RRGGBB format for a font highlight color in Office for Windows Desktop, MacOS, and Web.

## Current behavior
It is not possible to use the #RRGGBB format for a font highlight color in the Office for Windows desktop.

# Additional details and Context

It is possible to set the #RRGGBB format within the code, but this color will be converted to the nearest color when applied to the font, as mentioned in the documentation.
`range.font.highlightColor = '#90EE90'`

I would appreciate any feedback on this functionality, as this improvement will give us a big advantage in the area of highlighting. A key feature of the Definely's product is the ability to identify and highlight definitions and references in a Word document. 

Thanks in advance.

**Comment by EsterBergen** [comment]
hi @hannaDefinely - Thank you highlighting this! This would be a new feature. Please make a feature request here [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. Thanks for highlighting this!

**Comment by isadovskiy-numatic** [comment]
@hannaDefinely you can create new style with shading and apply it to your text range in order to achieve the similar results. 

https://learn.microsoft.com/en-us/javascript/api/word/word.shading?view=word-js-1.9

This will introduce a number of additional code but in general it works.

**Comment by dmytrokachurynets** [comment]
@isadovskiy-numatic When you say "you can create new style", do you mean creating that style manually in Word, or is there a way to define and save a custom style programmatically using Office.js?

**Comment by isadovskiy-numatic** [comment]
> [@isadovskiy-numatic](https://github.com/isadovskiy-numatic) When you say "you can create new style", do you mean creating that style manually in Word, or is there a way to define and save a custom style programmatically using Office.js?

@dmytrokachurynets Create programmatically via office.js API. I did it and this approach worked for me.

**Comment by dmytrokachurynets** [comment]
@isadovskiy-numatic  Could you show me a code example of how to create this new style programmatically? because I did not find such a possibility in the office.js api for word

**Comment by isadovskiy-numatic** [comment]
> [@isadovskiy-numatic](https://github.com/isadovskiy-numatic) Could you show me a code example of how to create this new style programmatically? because I did not find such a possibility in the office.js api for word

@dmytrokachurynets you can use to create a new style: https://learn.microsoft.com/en-us/javascript/api/word/word.document?view=word-js-1.9#word-word-document-addstyle-member(1) API for. Then configure the shading for: https://learn.microsoft.com/en-us/javascript/api/word/word.style?view=word-js-preview#word-word-style-shading-member. And then apply newly created style to the desired range: https://learn.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview#word-word-range-style-member
