### ISSUE TITLE
Word: Determine the visible range of the user.

### ISSUE THREAD

**Issue by hannaDefinely** [OfficeDev/office-js#4639]
# Summary of the issue
When working with a Word document, we need to define the visible area of the document (the area of the document that is visible to the user). This feature is necessary for several purposes, in particular to detect and assign annotations in the document, to highlight certain zones in the visible part of the document. Using the visible range will speed up the work of our application, because if we perform the above actions on the whole document at once, but not on the visible range, they will be quite heavy operations.

We have not found a way to define the visible area of the document. All the options we found are workarounds to achieve this goal.

## Your Environment
* Platform: Windows (PC desktop)
* Host: Word
* Office version number: Version 2406 Build 16.0.17726.20078
* Operating System: Windows 10
 
## Expected behavior
Possibility to determine the visible range of the user.

## Current behavior
One of the ways we found is to get a selected paragraph and then get n paragraphs at the top and n paragraphs at the bottom. But there is another issue, which is that a selected paragraph is a paragraph where the cursor is, but it may not be in the visible area.
`selectedParagraph = context.document.getSelection().paragraphs.getFirst();`

# Additional details and Context

The best solution would be to determine the visible range of the user (and therefore only annotate some small range of the document). Without this feature, we aim to insert and remove annotations from the whole document as efficiently as possible. Whenever the user begins to edit the document, we aim to remove all annotations and reinsert them when the user finishes editing. A key feature of Definely's product is the ability to identify and highlight definitions and references in a Word document (i.e., the current functionality of the Word plugin). The new 1.7 update that provides the annotation (underline) functionality is a huge step forward in accomplishing this goal in the Office App.

I would appreciate any details and comments on this, as this feature will give us a great advantage in the area of highlighting and annotating areas in the document.

**Comment by Searion** [comment]
@hannaDefinely Thanks for reaching out. Unfortunately, there is no existing API that can get the visible range. Could you please provide your contact and more information during this form link, then we will contact you later. https://forms.office.com/r/QayRq1FVEb

**Comment by stevefengjin** [comment]
@hannaDefinely thanks for providing the contact information, I will reach out and follow up on this.

**Comment by stevefengjin** [comment]
@hannaDefinely Hi, as we have put this into backlog and pending future prioritization, we will track the progress offline, and please let us know if you need further assistance on this ticket.
