### ISSUE TITLE
insertOoxml for Word does not work on WOPI host (CSPP)

### ISSUE THREAD

**Issue by aeturneus** [OfficeDev/office-js#4640]
We have created a Word add-in which works fine in desktop and O365, but fails in the WOPI word editor provided by CSPP (the Microsoft Cloud Storage Partner Program)

Issue previously reported here has returned: https://github.com/OfficeDev/office-js/issues/2893#issuecomment-2205963904

In our environment, these lines of code:

```
  public async applyDOMChanges() {
    const serializedDOM = this.serialize(this.dom);

    await Word.run(async (context) => {
      context.document.body.insertOoxml(serializedDOM, "Replace");

      await context.sync();
    });
  }
```

Result in this error:

```
{ "code": "NotAllowed", "message": "The action isn't supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information.", "errorLocation": "Body.insertOoxml", "statement": "var insertOoxml = body.insertOoxml(...);", "surroundingStatements": [ "var root = context.root;", "var body = root.body;", "// Instantiate {body}", "// >>>>>", "var insertOoxml = body.insertOoxml(...);", "// <<<<<", "// Instantiate {insertOoxml}" ], "fullStatements": [ "Please enable config.extendedErrorLogging to see full statements." ] }

```

## Your Environment

- Platform [PC desktop, Mac, iOS, Office on the web]: WOPI editor provided by CSPP
- Host [Excel, Word, PowerPoint, etc.]: Word
- Office version number: Build 20240627.8
- Operating System: Any
- Browser (if using Office on the web): Chrome
 
## Expected behavior
The Ooxml should be inserted as happens with desktop and O365.

## Current behavior
The text is not inserted and an error is logged in the console.

## Steps to reproduce

1. Use the sample code attached with the WOPI editor provided by CSPP (sample code provided by @nickmckenna) https://github.com/OfficeDev/office-js/files/9754057/Ooxml.Bug.Demo.zip
3. Click the "Insert OOXML" button
4. Note that text is not inserted
5. Note that the error appears in the console

## Link to live example(s)
1. download sample code attached
2. alternatively, use our production application test account (I will provide credentials if requested)

## Context
This bug prevents our production application from being used in WOPI, limiting our ability to deploy this tool to thousands of lawyers across Canada and the United States - it's a critical use case for us.

**Comment by aeturneus** [comment]
@xiruatms the insert OOXML function now works, sort of

However, numbering styles in the document do not work - when the insertion occurs, the numbering styles are not applied

Further, when the document is initially opened, no numbering is visible, and numbering only appears after any change is made to the document (e.g. inserting a space)

I don't know if these issues are related. However, I will open a new issue to better track these problems.

**Comment by aeturneus** [comment]
@xiruatms new issue posted here https://github.com/OfficeDev/office-js/issues/4698

**Comment by xiruatms** [comment]
@aeturneus , thanks for your confirmation. If the insert ooxml is working now, I'll close this issue. Our experts are working extensively on #4698
