### ISSUE TITLE
Outlook on the web has different values for attachments that can be retrieved with getAttachmentsAsync in certain situations.

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#4642]
# Provide required information needed to triage your issue

## Your Environment

* Platform : Outlook on the web
* Host : Outlook
* Operating System: Windows OS
* Browser (if using Office on the web): Chrome
 
## Summary
In Outlook on the web, if I insert an image into the body of an email, I can get the attachment with getAttachmentsAsync, but once I save it as a draft and then get it, it is not recognized as an attachment item.
Does a specific action change the format of attachments in the body of the email?

## Current behavior

1. Insert images within the body of an email in Outlook on the web.
2. Save as a draft.
3. Reloading.
4. Send the email you just saved from the draft.
At this time, if you check the value of the attachment retrieved by getAttachmentsAsync, you will find that the attachment cannot be retrieved.

**Comment by mailchecktool-admin** [comment]
I checked the value obtained by getAttachmentsAsync in the console, and it shows that the value is not included if it was sent from a draft.

【When first composing an email】
![スクリーンショット 2024-07-04 134443](https://github.com/OfficeDev/office-js/assets/139185387/c58d5392-94dd-41b4-b806-61705e8437ca)
↓
【After performing the above operation】
![スクリーンショット 2024-07-04 134356](https://github.com/OfficeDev/office-js/assets/139185387/2bc52174-d25f-426d-9ff2-908ecbc4ec24)

**Comment by Swathy-Mothilal** [comment]
@mailchecktool-admin could you please share a repro video and the manifest where you are encountering the issue? 
Additionally, just to clarify, are you using getAttachmentAsync only in the MessageCompose context as specified in the documentation at https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview&preserve-view=true#outlook-office-messagecompose-getattachmentsasync-member(1)

**Comment by Swathy-Mothilal** [comment]
@mailchecktool-admin  We noticed another GitHub post created at https://github.com/OfficeDev/office-js/issues/4643 regarding the same issue on a different platform by you. Could you please summarize on which platforms are experiencing this issue?

**Comment by mailchecktool-admin** [comment]
@Swathy-Mothilal 
This event is reproduced in Outlook on the web(chrome).
Although [#4643](https://github.com/OfficeDev/office-js/issues/4643) refers to the event in the Outlook client, the question is the same.

The question is : does the size, name, and retrieved value of an image inserted in the body of an email change when the drafts folder is moved or reloaded?
I have taken a screen recording of the event and am attaching it herewith.
The add-in I am developing starts when the mail is sent,
It is retrieved by getAttachmentsAsync from the contents of Office.context.mailbox.item.
The image that is checked in console.log is the image inserted in the body of the email.
When sending after reloading, the attachment file obtained by getAttachmentsAsync is empty even if the add-in is started.

Has a similar problem been reported elsewhere?

[ビデオ 7-04 18.15.zip](https://github.com/user-attachments/files/16096520/7-04.18.15.zip)

**Comment by Swathy-Mothilal** [comment]
@mailchecktool-admin In Outlook on the web the attachment identifier is valid only within the same session. A session is over when the user closes the app. For more info, please refer to https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-preview#outlook-office-messagecompose-getattachmentcontentasync-member(1).

**Comment by mailchecktool-admin** [comment]
@Swathy-Mothilal 
Sorry for the late reply.
I have read the documentation and understand the getAttachmentAsync specification.
However, I believe that users often close or pop out of the application, so if possible, I would like you to revise the specification so that getAttachmentAsync is enabled even outside of the same session.
Thank you in advance.

**Comment by rkpathak** [comment]
Currently we dont support this. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

Github Label: “Type: product feature request”
https://aka.ms/M365dev-suggestions
