### ISSUE TITLE
User is able to edit mail even if the outlook add-in is working on on-send(ItemSend) event

### ISSUE THREAD

**Issue by pza-dev-brcm** [OfficeDev/office-js#4645]
We are working on outlook add-in where we are handling on-send event.
When user sends email, add-in comes into the picture validate the details as per policy and decides whether action should be allowed or blocked.

In some cases if the add-in processing is taking time(around 10-15 seconds). User is able edit the email like adding new attachment or modifying earlier content while the add-in is processing email.

When add-in processing completes then the new updated email content is sent (and not the old one on which add-in actually done processing)

Ideally user should not edit the email if on-send add-in is processing.

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by guzman-rc** [comment]
The same thing happens to my users, we have an Addin that processes email attachments (using OnSend) and in some cases the Addin takes a long time to run (more than 30 seconds), even when the email has no attachments!

Our Addin (OnSend) is being used in more than 5000 clients and we are having a lot of problems because of the time it takes for the Addin to run.

**Comment by CodeCube0** [comment]
This OnSend event is also very invasive from reports from our customers

**Comment by Swathy-Mothilal** [comment]
@pza-dev-brcm Could you please confirm if you are using ItemSend or SmartAlert feature? It would be helpful if you can share a repro video and and the manifest with which you are experiencing the issue.

**Comment by guzman-rc** [comment]
We are using ItemSend

**Comment by pza-dev-brcm** [comment]
We are using ItemSend. Please find attached sample_Addin.xml. For security reasons not uploading complete xml and path. This issue can simply be reproducible. In the handler of ItemSend event function we can add sleep timer of 20/30 seconds and when user clicks on send button as we have added sleep timer for 30 seconds email is not sent untill 30 seconds lapse. 
In the meantime user can modify subject, mail body content.
[sample_addin.xml.zip](https://github.com/user-attachments/files/16101153/sample_addin.xml.zip)

**Comment by Swathy-Mothilal** [comment]
@pza-dev-brcm  We get xsi error while accessing your xml. Can you please host a light weight manifest where you can repro this issue and a repro video to a private repository and grant us access to it?
