### ISSUE TITLE
Addin OnSend (ItemSend) sometimes it takes a long time to run (more than 30 seconds). 

### ISSUE THREAD

**Issue by guzman-rc** [OfficeDev/office-js#4647]
We have developed an addin that removes metadata from attachments, this addin has been working for several years but lately some users complain that the addin takes a long time to run, even when the email has no attachments.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: New Outlook Windows
* Office version number: NA
* Operating System: Windows 11
* Browser (if using Office on the web): NA
 
## Expected behavior
The Addin, in normal conditions takes 1 second to process each attachment, when the email does not contain attachments it should not take any time because it does not perform any process.

## Current behavior
Users are complaining about the time it takes for the addin to run.

## Useful logs

- [X] Screenshots

Attached is a screenshot displaying that the email contains no attachments and the Addin message appears: 
**MetaClean for Outlook 365 está trabajando en su solicitud.**

![Captura](https://github.com/OfficeDev/office-js/assets/96702862/61a0de78-02b2-4547-aa43-df23bafc5c67)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by rkpathak** [comment]
@guzman-rc In our experiments event handlers get called right away. As handler could be doing multiple operations, can you zero in further and let us know which particular API that is causing delay?

**Comment by guzman-rc** [comment]
I am using:
<Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="itemSendHandler" />

https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=classic

**Comment by guzman-rc** [comment]
`<Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="itemSendHandler" />`

**Comment by rkpathak** [comment]
@guzman-rc Can you share a small addin with code, using which we could reproduce this issue?

**Comment by guzman-rc** [comment]
The delay is produced randomly.

**Comment by kumarshrey-msft** [comment]
Hi @guzman-rc, there can be multiple reasons behind the intermittent delays, for instance the connection to the actual add-in might be slow, can you repro this even if the add-in is hosted on localhost? Using tools like Fiddler, is it possible for you to narrow down the reason behind this slowness? We have been unable to repro this at our end so far.

**Comment by guzman-rc** [comment]
We will try to do what you propose and I will respond with the results.
