### ISSUE TITLE
Outlook add-in with SSO using NAA sample does not work

### ISSUE THREAD

**Issue by LiamWarnes** [OfficeDev/office-js#4648]
Hi,

I've just cloned the sample available at https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/auth/Outlook-Add-in-SSO-NAA/README.md to find that it does not work with the provided instructions. We are working with this sample in hopes of finding a suitable replace for the upcoming deprecation of exchange tokens.

In particular, the sample includes use of an unknown Office.auth.getAuthContext method on the Indentity API that does not seem to be available on the included version or in office-js-preview version.

![image](https://github.com/OfficeDev/office-js/assets/61216957/fcf1d2a9-fa32-46c5-99f0-87b9cefbf91a)

The method is used on line 73 of src/taskpane/authConfig.js and seems to be responsible for establishing an account prior to acquiring a token. To me, it would appear that this method is critical to the SSO metaphor for NAA.

During runtime, the method throws an exception when encountered

![image](https://github.com/OfficeDev/office-js/assets/61216957/d26e8380-356c-4ed7-8048-6cb97d0bc8dd)

Please can you review the sample and ensure that it is working with the provided README instructions.

**Comment by LiamWarnes** [comment]
ok i have managed to resolve it.

for anyone reading who may encounter similar issues; i was not properly enrolled in the Insider program to get the beta build of Outlook. This method **is available inside that build**.

I had trouble following the provided instructions of how to get the beta build from the related articles for joining the insider program. For anyone having the same troubles I can suggest following the instructions at https://www.msoutlook.info/question/office-365-for-business-office-insider-fast-builds to enable the beta channel as a group policy on your local machine - be careful where you place the admx/adml folders inside Windows\PolicyDefinitions folder as the folder structure already exists there.

you can then edit the group policy by searching **Edit group policy** and subscribing to the beta channel 

![image](https://github.com/OfficeDev/office-js/assets/61216957/86b06371-7f30-4ced-a780-7207b36d6c73)

follow this up by applying updates inside outlook by going to account -> check for updates. you should now be on the beta build

**Comment by cody-lettau** [comment]
@exextoc when can we expect this to be GA and available on all platforms? It does not seem like a viable approach to not have this available in GA at least a month or two before fully deprecating Exchange Web Service token usage.

Also, I'd like to request that documentation is made available that outlines how the following is accomplished that can be shared with customers:
```
Exchange Online blocks legacy Exchange [user identity tokens](https://learn.microsoft.com/office/dev/add-ins/outlook/authentication#exchange-user-identity-token) and [callback tokens](https://learn.microsoft.com/office/dev/add-ins/outlook/authentication#callback-tokens) in all tenants by default. Add-ins that haven’t adopted NAA and rely on legacy Exchange tokens will be unable to call EWS and Outlook REST unless admins opt into continued legacy token issuance.
```

Specifically, the part about opting into continued use of legacy token issuance.
