### ISSUE TITLE
Word: `search` can't find text in text boxes

### ISSUE THREAD

**Issue by greysteil** [OfficeDev/office-js#4650]
# Provide required information needed to triage your issue

In Word, text in text boxes (`w:txbxContent` in the OOXML) cannot be found using `search(...)` on a document's body or any of its ranges. This text _is_ findable when using Word manually (i.e., using the search bar).

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.86 (24060916)
* Operating System: Mac OS 14.3
* Browser (if using Office on the web): N/A
 
## Expected behavior
`search(...)` should behave the same via Office.js as it does when using the search bar in Word. It should find text inside text boxes.

## Current behavior
`search(...)` does not find any text within text boxes.

## Steps to reproduce

1. Add a text box to a document
2. Attempt to search for the text in the text box using `context.document.body.search(...)`
3. Observe that the text in the text box cannot be found

## Context

Our add-in includes two features that are negatively affected by this:
* We let users click links in our add-in to scroll to the relevant text in the document. These links do not work for text in text boxes, because `search(...)` is unable to find the text
* We let users insert tracked changes into their documents. This does not work for text in text boxes, because `search(...)` is unable to find the text and return a `Range` object for us to update

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by shanshanzheng-dev** [comment]
Hi @greysteil Thanks for reporting this issue, we'll be looking into this and will report back if we have a suggestion for you. Thanks.

**Comment by jipyua** [comment]
@greysteil thanks for reaching out, for the existing search api, generally we haven't provided support to content in text box yet. So this is so far a by-design behavior. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum]( https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. Thanks.

**Comment by greysteil** [comment]
Hi @jipyua, apologies for the slow reply - I was getting married(!).

>So this is so far a by-design behavior.

Drat, I thought you might say that. We'll implement some messaging for end users on our side explaining that we can't make changes to text in text boxes because it's not yet supported in Word's APIs. I'll open a feature request, too.

**Comment by greysteil** [comment]
For anyone coming to this issue later, the [feature request is here](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/word-search-for-text-in-text-boxes-in-officejs/idi-p/4192820#M2627).
