### ISSUE TITLE
spam-reporting add-in not showing on web Outlook 

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js#4652]
In documentation we can see spam-reporting add-in is Supported on Outlook on the web but it is not showing on my web and this is working correctly on my desktop

my [manifest](https://drive.google.com/file/d/1SOOisXNdjF2VsAwqOf8xxHFQo7VTS9P3/view?usp=sharing)

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/134502135/465267ca-7ae2-4612-92f0-037cf5b54693)

**Comment by junaid042** [comment]
manifest is installed but add-in is not showing

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/134502135/1173d662-8189-41a6-82b6-402f29f65652)
![image](https://github.com/OfficeDev/office-js-docs-pr/assets/134502135/f8918e86-bd94-4347-bbb6-d4a8875f7150)

**Comment by junaid042** [comment]
live [manifest ](https://github.com/junaid042/spam-reporting/blob/main/manifest.xml)

**Comment by junaid042** [comment]
on Desktop

![image](https://github.com/OfficeDev/office-js-docs-pr/assets/134502135/e468b077-8af3-4b8f-b7c6-355e2dc5c2aa)

**Comment by AlexJerabek** [comment]
Hi @junaid042,

Thanks for reporting this. Let me move the issue to the [product repo](https://github.com/OfficeDev/office-js) so the right people can investigate this platform support issue.

**Comment by rkpathak** [comment]
@junaid042 After installing the manifest, we do see the addin in OWA.
![Screenshot 2024-07-11 231216](https://github.com/OfficeDev/office-js/assets/3750499/44756c78-d232-42f3-a40f-a18ff6877dc0)

If you are still able to reproduce this, please capture the detailed steps required to reproduce this issue.
