### ISSUE TITLE
Trying to fetch attachment content using office js(Office.context.mailbox.item.getAttachmentContentAsync) 

### ISSUE THREAD

**Issue by riddhi-p-28** [OfficeDev/office-js#4655]
We are developing an outlook web addin using office js Smart alert template.
Trying to fetch attachment content using office js(Office.context.mailbox.item.getAttachmentContentAsync), we are encountering an internal office-js error (GetFileAttachmentId - 404), we are not getting the content.
![image](https://github.com/OfficeDev/office-js/assets/173268604/dfd15669-91f7-4335-a2ed-4cf934bdfe17)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
We should be able to fetch the attachment content in base64 format.

## Current behavior
Trying to fetch attachment content using office js(Office.context.mailbox.item.getAttachmentContentAsync), we are encountering an internal office-js error (GetFileAttachmentId - 404), we are not getting the content.

## Steps to reproduce

1. Compose a new email
2. Add recipients, subject and body
3. Click on the send button.
4. Once the task pane is shown, attach 7 attachments.

**Comment by rkpathak** [comment]
@riddhi-p-28 What do you mean by "ADd non allowed recipient"
Please add clear and minimal steps required to reproduce the issue.

**Comment by riddhi-p-28** [comment]
We have updated the steps to reproduce. Non- allowed recipient is just a term in our custom business logic, it is essentially just a recipient. The main issue is when we are trying to get the base64 content from office-js we are getting the 404 error as shown in the above attached image.

**Comment by kumarshrey-msft** [comment]
@riddhi-p-28 We are unable to reproduce this scenario, is it possible for you to share sample addin code/script lab code link that we can use to reproduce the issue?

**Comment by JuaneloJuanelo** [comment]
@riddhi-p-28  we need you to add some more detail on this issue. 
can you please share:

1. What type of attachment is this. [is this a PDF, Word Document, image?] please be very specific.
2. whats the size of the attachemnt.
3.  your flow: what do you mean by:  "click on send" and then "when the taskpane opens"   how is this taskpane open?  can you add more detail about what exactly you mean by this?
4. Also pelase clarify the platform, is this only happening in the Web? new outlook? windows?


the more detail you add the better.

thanks!

**Comment by riddhi-p-28** [comment]
PFB the required details:

1. What type of attachment is this. [is this a PDF, Word Document, image?] please be very specific.
    This issue is replicable with any format of attachment. However, for the above screenshot we used 7 PDF files. 
    
2. Whats the size of the attachment.
    The size of each pdf file attached was less than 1MB.
    
3. your flow: what do you mean by: "click on send" and then "when the taskpane opens" how is this taskpane open? can you add more detail about what exactly you mean by this?
   When user clicks on outlook send mail button, we are triggering the side pane. When the sidepane is triggered we are calling the getAttachmentContentAsync API, where this issue is happening.
   
4. Also pelase clarify the platform, is this only happening in the Web? new outlook? windows?
    We could replicate the issue on web and well as outlook desktop app. For the above screenshot, we have used outlook Web (Chrome)
    
 Pls note: The above issue is happening intermittently.

**Comment by neprasad-microsoft** [comment]
@riddhi-p-28 is it possible for you to share the sample add-in to help us debug faster. Also, please collect the logs and share it with us. https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues .
You can share it with us in a private Github repo and give access to exextoc.

**Comment by ovdixon** [comment]
Hi - I am encountering the same issue on send event. The error occurs on New Outlook (desktop), and Web Outlook works fine. The function `getAttachmentContentAsync` returns an empty string and in the network tab I can see a call to `
https://attachments.office.net/owa/odixon%40jord.com.au/service.svc/s/GetFileAttachment?id=` returning `404`.
