### ISSUE TITLE
How to enable Object Linking for Content Add-Ins?

### ISSUE THREAD

**Issue by cornflakeboy** [OfficeDev/office-js#4658]
Hi everyone,

Could anyone please tell me if content addins for Excel and Powerpoint support object linking? I can insert standard Excel charts via copy and paste as "Paste and Link Data". Can a similar insertion option also be activated for content addins? In my content addin I only have the options "Paste" and "Paste as Picture" and they behave exactly the same. My content addin is always pasted as a picture and does not update when you change the cell values in the original Excel file. I am especially interested in pasting a linked version of my Excel chart into PowerPoint.

I would appreciate your help so much...

**Comment by EsterBergen** [comment]
Hi @cornflakeboy- 
First off- that's a great alias/tag. Very creative!

I don't believe this functionality is currently available for Office.js Web Add-ins, but let's explore.

Can you help me understand a little but about the exact scenario here? Does your current content add-in display charts from excel and you're looking to be able to copy that object to a new slide to show the same chart?

**Comment by cornflakeboy** [comment]
Thank you very much 😅 and many thanks for your quick reply.
Our company built a content add-in to visualize excel data. It renders plain HTML inside the content add-in's DOM without using any API to create Excel Charts. We would like to copy our add-in and then paste it into a PowerPoint presentation so that the copy updates when changing the values in the original Excel file's cells.
Thank you very much for your commitment.
Best, Tim

**Comment by EsterBergen** [comment]
@cornflakeboy - Thanks again!

This functionality is not currently supported. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. Thanks for highlighting this!
