### ISSUE TITLE
#NAME Error Despite Following Instructions

### ISSUE THREAD

**Issue by haboutnnah** [OfficeDev/office-js#466]
## Expected Behavior

To be able to activate a defined function using a name.

## Current Behavior

I get a name error

## Steps to Reproduce, or Live Example

https://github.com/haboutnnah/excel-anime-addin

`npm run build` and `npm start` work perfectly.

When opening Excel, I get a message stating that the addons loaded properly.

The task pane functions. (How do you disable this feature entirely?)

However, when attempting to call any of the defined functions, using either CONTOSO or my defined ANIME as the prefix, nothing occurs, no Intellisense, etc.

~~Note, this works (sans cors funkiness) on web excel - it appears to be an issue with macOS excel~~ 

Nevermind, this doesn't work either. I tried on Windows as well - "one or more add-ins failed to install or load custom functions".

## Context

I'm trying to write an add-in to learn Office JS. 

The Add-in simply has a few functions, that should all translate to excel functions.

## Your Environment

Original:

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Excel 16.25
* Operating System: Mac OS 10.13.6

Second:

* Platform [PC desktop, Mac, iOS, Office Online]: Windows Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1904 Build 11601.20042 Click-to-Run Office Insider
* Operating System: Windows 10 1809

## Useful logs

[excel-js.log - The terminal dump in macos](https://github.com/OfficeDev/office-js/files/3054131/excel-js.log)
[debugadapter.txt - Windows real debug log](https://github.com/OfficeDev/Excel-Custom-Functions/files/3070345/debugadapter.txt)

**Comment by haboutnnah** [comment]
Note, this works (sans cors funkiness) on web excel - it appears to be an issue with macOS excel

**Comment by keyur32** [comment]
Hi, @haboutnnah, I had replied on your thread on the Excel-Custom-Functions Repo [here](https://github.com/OfficeDev/Excel-Custom-Functions/issues/136).

 If you have additional questions on this, please let me know as we'll need more info from you. Will close for now. thanks!
