### ISSUE TITLE
setSelectedDataAsync with coercionType OOXML shows loading panel and fails (in WOPI host)

### ISSUE THREAD

**Issue by stowellt** [OfficeDev/office-js#4660]
# Provide required information needed to triage your issue
I'm unable to insert any Open XML into a Word document in Office for the web on our WOPI host

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: WOPI Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Build 20240705.4
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
setSelectedDataAsync with coercionType OOXML should not time out or have errors

## Current behavior
a "waiting" loading panel appears and it either times out, or no graphic is inserted

## Steps to reproduce
- I used Script Lab running locally (clone from Github then run "npm run start" in a terminal)
- Go to the URL in the form (also I saved the username and password in the form provided) https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR9NvrlmrippKsMvh4kTM325URVZMWjYyQTVOTVNLTUo5VzFRTTcyNU1RSy4u
- On the Home > Add-ins menu click "+ More Add-ins"
- Click ADMIN MANAGED
- Click "Upload My Add-in"
- Click "Browse"
- select script-lab\manifests\script-lab-react-localhost.xml
- Next Click the "Code" button
- Paste the following code:
- [script lab code sample.txt](https://github.com/user-attachments/files/15916104/script.lab.code.sample.txt)
- Click "Run", then click the Run button in the add-in
- In both the fast food and production environments I see a "Waiting" modal, then either nothing happens, or it times out

## Link to live example(s)
The url and login credentials can be found at https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR9NvrlmrippKsMvh4kTM325URVZMWjYyQTVOTVNLTUo5VzFRTTcyNU1RSy4u

## Context
We are trying to insert document variables and because the current OfficeJS API doesn't support that we are trying to use raw Open XML. I had an earlier bug report here: https://github.com/OfficeDev/office-js/issues/2840

**Comment by xiruatms** [comment]
@stowellt , thanks for reporting this.

Just want to clarify something:
1. In your code snippet, there's something related to themecolor: <w:color w:val="70AD47" w:themeColor="accent6"/>
2. But if I getOoxml directly from your document, I noticed that the theme seems updated:
as the screenshot shows, the left is from your document, the right is from a standard document
![image](https://github.com/user-attachments/assets/42bc7fca-a6b9-4775-960b-b45dffdfa8e1)

can you help to confirm the theme updates is on purpose? How did you implement that please?

**Comment by stowellt** [comment]
Sorry for the delayed response. @xiruatms I didn't implement anything regarding the theme update, I just copied that sample open XML from an article on Microsoft.com at https://learn.microsoft.com/en-us/office/dev/add-ins/word/create-better-add-ins-for-word-with-office-open-xml#insert-document-content-at-the-selection
