### ISSUE TITLE
Unable to set recipient back to email if it has a Contact List using Office.context.mailbox.item.to.setAsync

### ISSUE THREAD

**Issue by avisheknand** [OfficeDev/office-js#4661]
Contact List does not have email address data. When you get recipients from the email  using the getasync method and try to set it back to the email it works fine unless you have a contact list in the email. An error occurs with 5010 code.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Classic Win Outlook
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2406 build 16.0.17726.20078
* Operating System: Windows 11
* Browser (if using Office on the web): ______
 
## Expected behavior

I would expect that what ever I have in my recipient collection from the get method, i should be able to set it back to the email even if it has a contact list 
## Current behavior

Unable to set recipient back to the email if it has contact list in its array object 

## Steps to reproduce

1.Create a contact list
2. Add a contact list to the email 
3. Use script lab to Get recipient and then set them back to email

https://github.com/OfficeDev/office-js/assets/80862413/bc2641a7-be3f-4fd5-8340-babeaa49403b

## Link to live example(s)
`
$("#get-to").on("click", getTo);
$("#set-to").on("click", setTo);

let _toRecipient;

function getTo() {
  _toRecipient = [];
  Office.context.mailbox.item.to.getAsync(function(asyncResult) {
    if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
      const msgTo = asyncResult.value;
      console.log("Message being sent to:");
      for (let i = 0; i < msgTo.length; i++) {
        _toRecipient.push(msgTo[i]);
        console.log(msgTo[i].displayName + " (" + msgTo[i].emailAddress + ")");
      }
    } else {
      console.error(asyncResult.error);
    }
  });
}

function setTo() {
  Office.context.mailbox.item.to.setAsync(_toRecipient, function(asyncResult) {
    if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
      console.log("Succeeded in setting To field.");
    } else {
      console.error(asyncResult.error);
    }
  });
}
`

## Context

We have an onSend Add-in which modifies the email recipients. If there is a contact list in the email, the add-in is not able to set the contact list back to the email again. We have a customer base of 900+ users, most of whom use contact lists to send emails.

**Comment by rkpathak** [comment]
@avisheknand When a contact list is part of the to list, the getAsync call returns an object e.g. {"displayName":"test_list","recipientType":"distributionList"}
For calling setAsync, distribution list is not a valid input. Please refer the documentation for details https://learn.microsoft.com/en-us/javascript/api/outlook/office.recipients?view=outlook-js-preview#outlook-office-recipients-setasync-member(1)
