### ISSUE TITLE
Excel Web: Add-in failed to install or load custom functions - on page refresh

### ISSUE THREAD

**Issue by anotherstarburst** [OfficeDev/office-js#4662]
# Provide required information needed to triage your issue

Our excel add-in installs 2 custom functions. After initial installation of our production add-in (published through the Microsoft Store) everything works fine in Excel Web. However when we reload the page we get the following error: 

> "one or more add-ins failed to install or load custom functions. Error installing functions."

Similarly, when using a totally fresh browser instance, and navigating to the same spreadsheet (after logging in with the same Microsoft account) we get the same error.

## Your Environment

Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
Host [Excel, Word, PowerPoint, etc.]: Excel
Office version number: n/a
Operating System: Mac OS 14.5
Browser (if using Office on the web): Chrome/126.0.6478.127 (arm64)
 
## Expected behavior
The custom functions should load without error each time a spreadsheet is opened.

## Current behavior

Everything works fine when you initially install the add-in. Evidently this has been the experience of the Microsoft add-in reviewers too.

If you refresh the page, or navigate to the same spreadsheet using the same Microsoft account in a brand new browser instance you are given the error "one or more add-ins failed to install or load custom functions. Error installing functions." 

In all instances the add-ins side panel continues to work fine.

## Steps to reproduce

1. Ensure you have no other add-ins installed
2. Install our add-in https://appsource.microsoft.com/en-us/product/office/WA200007157
3. Type in `=al` to see our custom functions have correctly registered - it should auto-complete
4. Refresh the page
5. See the error "one or more add-ins failed to install or load custom functions. Error installing functions." 

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. I see others have experienced similar issues https://github.com/OfficeDev/office-js/issues/2617 though it's not clear what was done to resolve them
2. I've tried changing from a 3-point to a 4-point versioning system  per https://github.com/OfficeDev/office-js/issues/2617#issuecomment-1451528282 - but the issue remains
3. Of course the development versions of this work fine across browser-refresh

## Context

Without this issue being fixed our add-in cannot be used by our customer and that makes both them and us sad.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by shanshanzheng-dev** [comment]
Hi @anotherstarburst Thanks for reporting this issue, I'm trying to repro your problem, but I can‘t login. Could you share us a test account to repro? 
BTW, could you share us which custom functions you install in your add-in?
Thanks.

**Comment by anotherstarburst** [comment]
Thanks for the quick input on this @shanshanzheng-dev . 

Login to our application shouldn't be necessary to repro - just a page refresh. In my own testing of this issue I don't log in to our app either. 

Two custom functions are installed, one named `EXTRACT` and another named `EXTRACTTABLE`. Full json available at https://storage.googleapis.com/alep-ai-add-in/1.0.2.0/functions.json

**Comment by anotherstarburst** [comment]
https://github.com/OfficeDev/office-js/assets/484487/e5d786ed-75ea-40e6-90d7-49becb549147

here's a video showing the issue

**Comment by shanshanzheng-dev** [comment]
Hi @anotherstarburst Thanks for provide this video. We'll be looking this issue, but sorry we can't share timeline. We'll report back if we have a suggestion for you. Thanks.

**Comment by shanshanzheng-dev** [comment]
Hi @anotherstarburst We try to repro your issue, but we found when we install the add-in, using the customer function and refresh, it'll trigger CF calc but the addin will crash. We can't see any error from our side, could you try to investigate why the add-in crash?
![image](https://github.com/user-attachments/assets/980099e4-ec67-46bb-8c9a-fab0694fa56c)
