### ISSUE TITLE
Office.context.mailbox.item.getConversationIndexAsync() and Office.context.mailbox.item.getItemClassAsync() failing for new Outlook client

### ISSUE THREAD

**Issue by teejay001** [OfficeDev/office-js#4664]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: New Outlook
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 1.0.401
* Operating System: Windows
* Browser (if using Office on the web): Not applicable
 
## Expected behavior

The conversationIndex should be returned correctly from the call.

## Current behavior

Office.context.mailbox.item.getConversationIndexAsync() fails with an error message below
![image](https://github.com/OfficeDev/office-js/assets/99417649/317f8c57-3d0d-4e49-bbbc-3d2555e76f0e)

## Steps to reproduce

1. Ensuring you are referencing the latest requirement set for outlook (1.14, https://learn.microsoft.com/en-us/javascript/api/requirement-sets/outlook/requirement-set-1.14/outlook-requirement-set-1.14?view=common-js-preview)
2. Make a call to get the conversationIndex as described n the document
3. conversationIndex is returned on all Windows client except the new Office Client

## Link to live example(s)

1. https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-1.14&preserve-view=true#outlook-office-messagecompose-getconversationindexasync-member(1)

# Provide additional details

1. The new outlook client being used is of the version below
![image](https://github.com/OfficeDev/office-js/assets/99417649/b54edc62-717d-4e42-889d-a2388187a6a4)

## Context

We cannot deploy as it is, business requirement is to know the conversationIndex reference for further processing.

## Useful logs

![image](https://github.com/OfficeDev/office-js/assets/99417649/b20bc257-f50d-4f5e-b792-5ab791dd3e94)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by teejay001** [comment]
Since both endpoint were introduced at the same time, perhaps it's the same issue affecting both. Office.context.mailbox.item.getItemClassAsync() also fails with the same error on new outlook client

**Comment by rkpathak** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

Internal tracking id: Office: [290513]

**Comment by Adrian-MSFT** [comment]
This issue should be resolved. Please let us know if you are still experiencing this issue
