### ISSUE TITLE
Word Addin: Return Focus to Document Body after Interaction with Taskpane

### ISSUE THREAD

**Issue by pki89** [OfficeDev/office-js#4665]
Hi, 

would be really great to have a way to return user focus back to the word document after user has interacted with the taskpane. Currently, user has to click in the document body again in order to continue their work (e.g. typing) in the document. This heavily impairs UX.

Also relates to this https://github.com/OfficeDev/office-js/issues/316 (which appears still not to be fixed).

Thanks a lot.

**Comment by shanshanzheng-dev** [comment]
Hi @pki89 Could you give us more information about this issue? seem that link your provide is blank. Thanks.

**Comment by pki89** [comment]
https://github.com/OfficeDev/office-js/issues/316

The issue is, that the user interacts with the taskpane, i.a by clicking some button, which e.g. insert a string into the word doc
user would the expect to be able to immediately resume their work in the word doc by continuing their typing. That is not the case, as the user first has to click the document body again to havethe focus/cursor there again.

Would be great to allow devs to choose to force refocus to the document 

Thanks a lot

**Comment by stevefengjin** [comment]
@pki89 thank you for bringing this to our attention. If you like to tell us more about your requirement about this feature, please leave your contact information in this form: https://forms.office.com/r/QayRq1FVEb

Or, we have received similar request in the past and you may upvote in the forum if you see it reflects your requirement:  https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/set-selection-and-focus-back-to-document-after-action-in-ms-word/idi-p/4065642

**Comment by SPEuricom** [comment]
I'm bumping this, because every "link" that is referenced is literally **DEAD**..

**Comment by myurtsev** [comment]
Bumping this, this should be working
