### ISSUE TITLE
insertWorksheetsFromBase64 does not load excel if it contains chart data

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4667]
insertWorksheetsFromBase64 API does not load excel if excel contains chart,pivot table data. API throws exception that this is not supported.

So we are planning to use Excel.createWorkbook to open new workbook. But with this API problem is that its opening in new tab and there is no way to get updated context so that our add-in thread can progress.

Can you please help me to solve this issue?

Thanks in advance.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11, Thanks for reporting issue, you can check this link: https://learn.microsoft.com/en-us/javascript/api/excel/excel.workbook?view=excel-js-preview#excel-excel-workbook-insertworksheetsfrombase64-member(1), when I insert chart or pivot table, I can use insertWorksheetsFromBase64 API to create a new sheet.

**Comment by ishanig11** [comment]
@shanshanzheng-dev : And what if your excel already contains chart? Are you able to load them?

**Comment by shanshanzheng-dev** [comment]
Yes, you can see this video, is that your want? If not, could you share your repro video? Thanks.

https://github.com/OfficeDev/office-js/assets/125014206/844244d7-b2e4-4baa-94d0-7cedbcad3cf0

**Comment by snehalghute** [comment]
can you try to load workbook directly? And also include pivot table.

**Comment by ishanig11** [comment]
can you try to load workbook directly? And also include pivot table.

**Comment by shanshanzheng-dev** [comment]
@ishanig11 the first table you can see is pivot table, what do you mean "load workbook directly"? could you share your code? Thanks.
