### ISSUE TITLE
[Regression] RuleCollection manifest field is ignored

### ISSUE THREAD

**Issue by kbrilla** [OfficeDev/office-js#4668]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 365 - 2308 compilation 16.0.16731.20542
* Operating System: Windows 10

## Expected behavior
RuleCollection is respected and for example
```
  <Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"/>
  </Rule>
```
When addin tab is pinned, and we select appointment, rule should close addin tab. 
This worked till last week or so
What's more tab is redirected to invalid url which causes addin to hang, and changing message does not fix it. 
User need to close and open tab again on correct message, which is very annoying for especially keybord focused users. 

## Current behavior
Addin tab stays open when pinned ignoring RuleCollection.

## Steps to reproduce
1. add this rule to manifets
```  
<Rule xsi:type="RuleCollection" Mode="Or">
    <Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"/>
  </Rule>
```
2. Select message, open addin tab, pin it
3. Select appointment

**Comment by kbrilla** [comment]
In Office Online addin tabs also started to act very weird at the same time 

//edit: typo

**Comment by rkpathak** [comment]
@kbrilla Can you share the steps that needs to be done to reproduce this issue. Or create a video of the repro and share. Is this issue see on Outlook Classic or on new Outlook?

**Comment by kbrilla** [comment]
Preatty sure #4690 gives is about the same issue - I'm out of office now so I cant create repro, will give one after vacation

**Comment by neprasad-microsoft** [comment]
Hi @kbrilla #4690 is related to add-ins staying pinned in module extension tab and we can repro it. But we are unable to repro it when switching to calendar. If that is what you mean, then please share your add-in and exact repro steps. 
Also, is this issue on new Outlook/Legacy Outlook/ Outlook on the web or all 3?
