### ISSUE TITLE
Office.context.ui.displayDialogAsync() does not work when promptBeforeOpen is set to true

### ISSUE THREAD

**Issue by afzal-hussain** [OfficeDev/office-js#467]
## Expected Behavior
If promptBeforeOpen is set to true in DialogOptions, then Office.context.ui.displayDialogAsync() to displays a pop-up (in case running under browser) to trigger the navigation and avoid the browser's pop-up blocker. If the user provides consent, then open the requested URL in a dialog.

## Current Behavior

If promptBeforeOpen is set to true in DialogOptions, then neither the prompt appears, nor the actual dialog opens. No errors are printed on console when using Office.com. If promptBeforeOpen is set to false, then the dialog opens (but blocked by browser pop-up blocker)  - as expected. 

This feature was working for us couple of weeks back, and then it stopped working. We are using the Office.js CDN. 

This issue could be a side effect of https://github.com/OfficeDev/office-js/issues/361, which touches similar items, and was recently published. 
## Steps to Reproduce, or Live Example
Should be quite easy to reproduce. For example, Google's "Hangouts Meet Add-in" has a similar functionality to display the login. Please install that plugin for Outlook, and then click on "Add a meeting" options. This should open the login dialog in case the user is not logged in. It was working before, now it does not work anymore.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Windows 10, outlook.office.com
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 1808 (Build 10730.20304 Click-to-Run)
* Operating System: Windows 10
* Browser (if using Office Online): Chrome 71

**Comment by exextoc** [comment]
Are you seeing this issue on other platforms (desktop / mac) and other browsers ?

**Comment by afzal-hussain** [comment]
Yes, I am able to reproduce the issue on the following combination:

1. Window 10 with Desktop Outlook 365 - Version 1903 (Build 11425.20202 Click-to-Run)
2. Windows 7 with Desktop Outlook 365 - Version 1808 (Build 10730.20304 Click-to-Run)
3. Mac with Desktop Office 2016
4. Office online (outlook.office.com) on the following combination
    - Windows10 + Chrome 73
    - Windows10 + MS Edge
    - Linux + Chrome 71

Please confirm if you can reproduce the issue, or need some further information.

**Comment by exextoc** [comment]
Can you please share relevant code snippet to repro the issue ?

**Comment by afzal-hussain** [comment]
I have attempted to create a minimal reproducible example. 

Below you can find my function-file.js for the Outlook add-in (originally was created using the Yeoman generator as described in https://docs.microsoft.com/en-us/outlook/add-ins/quick-start?tabs=visual-studio-code. Some modification from the generated file has been done as can be seen below in the code.

With the below code, I reproduced the problem in Linux + Office Online with Chrome 71 (the easiest combination for me to test). The problem goes away if I set the promptBeforeOpen = false with this combination.



````

function addMeetingAction(event){
    const options = {
        height: 30,
        width: 20,
        promptBeforeOpen: true,
    };

    Office.context.ui.displayDialogAsync('https://google.com',options , function (asyncResult){
        console.log("And the response from callback", asyncResult);
        if (asyncResult.status == Office.AsyncResultStatus.Failed) {
            console.log("Could not open login page", event);
        }
        else{
            console.log("Successfully opened")
        }
    });
}

//unless you add it in the window, Webpack removes this function as unused, and then Manifest file can never find it
window.addMeetingAction = addMeetingAction;

(() => {
  Office.initialize = (reason) => {
    console.log("Office has been successfully initialized. Reason = ",reason );
  };
})();

````


And here are the snippets from my manifest file
````
                    <Item id="apptComposeMenuItem1">
                      <Label resid="paneAddMeetingLabel" />
                      <Supertip>
                        <Title resid="paneAddMeetingSuperTipTitle" />
                        <Description resid="paneAddMeetingSuperTipDesc" />
                      </Supertip>
                      <Icon>
                        <bt:Image size="16" resid="addIcon16" />
                        <bt:Image size="32" resid="addIcon32" />
                        <bt:Image size="80" resid="addIcon80" />
                      </Icon>
                      <Action xsi:type="ExecuteFunction">
                        <FunctionName>addMeetingAction</FunctionName>
                      </Action>
                    </Item>

````

**Comment by tobiasviehweger** [comment]
We have the same issue, though we can only reproduce this in OWA (16.0.10908.10000). It happens already when you set "displayInIframe" to false (will default the prompt param to true). Dialog will not show and code will not continue (as if the actual prompt is just invisible).

This is bad! Our customers cannot login, please fix this soon.

Thanks!

//cc: @DarkLegend

**Comment by afzal-hussain** [comment]
Hi @exextoc,

Could you please confirm if you accept this as a bug? If yes, do you have any timeframe?

Thanks

**Comment by tobiasviehweger** [comment]
Yeah, any news would be appreciated - this is preventing showing the login popup for our app! This is huge issue....

**Comment by exextoc** [comment]
The url that is passed to the displayDialogAsync method must be in the same domain as the host page. So instead of google.com use the url from the same domain.
Or if its from the different domain try adding it in AppDomains section in the manifest.
Also,
1. Check if IE has blocked popup for you?
2. In console.log try to print JSON.stringify(asyncResult) And see what exact error you get.

**Comment by tobiasviehweger** [comment]
@exextoc Displaying ANY dialog with displayInIframe: false (even on the same domain) does not work in modern OWA currently (when called from a ribbon function). This is why I'm so persistent, it's a bad bug! It simply does not show the popup blocker workaround (the one that says "Allow Popup"), but get's stuck.

Here's a full repo:
https://static-resources.yasoon.com/owa-display-dialog-issue/manifest.xml

Code is here:
https://github.com/tobiasviehweger/owa-display-dialog-issue
https://github.com/tobiasviehweger/owa-display-dialog-issue/blob/master/ribbon-functions.js

Any feedback on this would be appreciated....

**Comment by tobiasviehweger** [comment]
Debugged a bit. The dialog is not shown because of this CSS class. Removing the display:none shows that it is currently in the DOM but not visible:
![image](https://user-images.githubusercontent.com/2111803/56790946-316f9700-6806-11e9-933c-0a88076e3214.png)

Toggling the display:none:
![image](https://user-images.githubusercontent.com/2111803/56791039-65e35300-6806-11e9-8dab-b485a49431a8.png)

**Comment by afzal-hussain** [comment]
I concurr with @tobiasviehweger. For the code snippet published in this ticket, I used google.com, but in real scenario, I am using a different URL (from same origin) from our DEV environment which is not available on the Internet.

1. The whole idea of promptBeforeOpen is to avoid popup blocker. So even if there is a popup blocker, it should not matter. Also this prompt dialog is not a popup, rather a DOM element in the current page which looks like a window. So popup blocker should not block it.
2. There are no errors passed in the asyncResult. The callback function is not even called. 

During debugging, I also had the same feeling as @tobiasviehweger - that the prompt is added to the DOM but for whatever reason remains hidden.

To me, this is a very clear bug which should be very easily reproducible. You must have some sample code / test code which tests this feature. Could you please try with your own code, and see if it works?

**Comment by exextoc** [comment]
We tried to repro this again in modern OWA using your code-snippet below:

```
function addMeetingAction(event){
    const options = {
        height: 30,
        width: 20,
        promptBeforeOpen: true,
    };

    Office.context.ui.displayDialogAsync('https://google.com',options , function (asyncResult){
        console.log("And the response from callback", asyncResult);
        if (asyncResult.status == Office.AsyncResultStatus.Failed) {
            console.log("Could not open login page", event);
        }
        else{
            console.log("Successfully opened")
        }
    });
}
```

It is not reproducible for us. Display dialog opens without any problem on Win10 + Chrome 73.

Do you have any special settings in Chrome? If yes, we would like to use those settings and try to repro the problem.

**Comment by tobiasviehweger** [comment]
@exextoc I don't have anything special in Chrome, I've turned off all blockers etc, still happening. Also can reproduce this in Edge (without any proxy, no corporate restrictions, all defaults). **Please note this only occurs if you call it from a ribbon function** directly, from a sidepane it works. See gif:
https://static-resources.yasoon.com/owa_display_dialog_issue.gif

Could you try my example from above please? I'm using the following:

Here's a full repo:
https://static-resources.yasoon.com/owa-display-dialog-issue/manifest.xml

Code is here:
https://github.com/tobiasviehweger/owa-display-dialog-issue
https://github.com/tobiasviehweger/owa-display-dialog-issue/blob/master/ribbon-functions.js

Thanks...

**Comment by exextoc** [comment]
@tobiasviehweger Thanks for sending the gif repro. We are looking into this issue and will provide update on this soon.

**Comment by exextoc** [comment]
@tobiasviehweger We are able to reproduce this issue using your addin. Thanks for providing the addin for repro purpose. We are actively looking into this, but don't have any timeline to provide on fix.

Apologies for taking long time to accept this as bug.

**Comment by afzal-hussain** [comment]
Great. Thanks @exextoc @tobiasviehweger :)

**Comment by exextoc** [comment]
@tobiasviehweger @afzal-hussain We investigated and found that this issue is fixed already and being slowly rolled out. Can you please check once again?

If this is not working, can you please let us know you build version for Outlook Web App? You can find that by doing "Inspect" -> Sources -> Expand ow2.res.office365.com -> Note down build version which is in the form like this: "owamail/20190502".

**Comment by afzal-hussain** [comment]
It is now working for me in my scenario. I have tested in the following combination
1. Office Online + Chrome (Linux) - Loaded build version was "owamail/2019042903.08"
2. Windows7 + Office 365 Desktop

Both worked for me. If it also works for @tobiasviehweger , then we can close the issue

Thanks @exextoc for the support

**Comment by tobiasviehweger** [comment]
@afzal-hussain yes, fixed for me as well, sorry for the delay! thanks!
