### ISSUE TITLE
Office.context.ui.displayDialogAsync redirecting to browser from desktop app

### ISSUE THREAD

**Issue by JayeshiFour** [OfficeDev/office-js#4670]
When some users attempt to log in, they are unexpectedly redirected to the Edge browser. The expected behavior is for the login process to occur on the same page using Office.context.ui.displayDialogAsync. This issue affects some users inconsistently, while the login works as intended for others.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Excel version number: 2404 Build 16.0.17531.20190 (32-bit)
* Operating System: Windows
* Browser (if using Office on the web): N/A
 
## Expected behavior
All users should experience the login process on the same page using the Office.context.ui.displayDialogAsync dialog.

## Current behavior
- Some users are redirected to the Edge browser during the login process.
- Other users experience the expected behavior with the login process occurring on the same page.

## Steps to reproduce

1. Implement login functionality to be triggered when the user clicks on the login ribbon.
2. After clicking on the login ribbon, open the task pane.
3. Initiate the login process using Office.context.ui.displayDialogAsync.
4. Observe the behavior: some users are redirected to the Edge browser, while others remain on the same page as expected.

# Provide additional details
1. The issue occurs inconsistently among different users.
2. No clear pattern has been identified regarding which users are affected.
3. The environment details, including browser versions and Office Add-in versions, may vary among users.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by shanshanzheng-dev** [comment]
Hi @JayeshiFour thanks for reporting this issue. If possible, could you provide us manifest, repro code or other detail message? Thanks.
