### ISSUE TITLE
Word Addin: how to retrieve characters / text prior to cursor location

### ISSUE THREAD

**Issue by pki89** [OfficeDev/office-js#4671]
I am struggling with finding a way on how to retrieve the text prior to the current cursor location (no selection made). Anyone any idea?

Thanks a lot.

Expecting:

Do you want to create a solution that ex|tends the functionality of Word? --> "x" 
Do you want to create a solution that |extends the functionality of Word? --> " " 
|Do you want to create a solution that extends the functionality of Word? --> "" 
Do you want to create a solution that extends the functionality of Word?| --> "?"

**Comment by ElizabethSamuel-MSFT** [comment]
@pki89 Thanks for asking about this. Here's one possibility for getting the behavior you're looking for:

```typescript
  await Word.run(async (context) => {
    // Get the beginning of the range at the cursor location then expand the range to the beginning of the document body.
    const range: Word.Range = context.document.getSelection().getRange(Word.RangeLocation.start).expandTo(context.document.body.getRange(Word.RangeLocation.start));
    range.font.color = "blue";
    range.load("text,isEmpty");
    await context.sync();

    console.log(`The text of the expanded range was "${range.text}".`);

    // If the range is empty, display the range text. Otherwise, display the last character of the range text.
    console.log(`The character before the cursor was "${range.isEmpty ? range.text : range.text[range.text.length - 1]}".`);
  });
```

I'm closing this but if the sample doesn't resolve your issue, let us know so we can reopen it.

Thanks.
