### ISSUE TITLE
Marketplace: error upload manifest.xml / error al subir el manifest.xml

### ISSUE THREAD

**Issue by GrupoOsk** [OfficeDev/office-js#4674]
We are making an add-on for Outlook, we wanted a button to appear in COMPOSE MAIL, but it did not appear on the mobile phone, it seems that you cannot add buttons to the compose interface on mobile phones. The solution that was proposed to me in this forum was to use LaunchEvents. What we want is for the email to add a header text when sending, the compelemto was corrected and the code works correctly, we tested it by attaching it to Outlook and it works OK. But when we want to upload the manifest.xml ccom oaquete for validation in the Marketplace Offers, it gives me the following error:

Error validating package acceptance: Mailbox add-in containing ItemSend event is invalid. Mailbox add-in containing ItemSend event is invalid. Error code: Mailbox add-in manifest contains ItemSend event in VersionOverrides which is not allowed.

I don't understand the reason, but the code works, but I can't upload it? How can I solve this, we have been trying to get the project out for a long time. We use itemSend, as directed by Microsoft Help, and it works, but I can't publish it.

Thank you

***********************
Marketplace: error subir un paquete

Estamos haciendo un complemento para Outlook, queríamos que apareciese un botón en REDACTAR, pero en el móvil no aparecía, según parece, no se puede añadir botones en la interfaz de redactar en moviles. La solución que se me propuso en este foro, fue la de usar LaunchEvents. Lo que queremos es que al enviar añada un texto de cabecera  los correos, el compelemto se corrigió y al código funciona correctamente, lo probamos adjuntando a Outlook y funciona OK. Pero cuando queremos subir el manifest.xml ccom oaquete para su validación en el  Ofertas de Marketplace, me indica el siguiente error:

Error al validar la aceptación del paquete: Mailbox add-in containing ItemSend event is invalid. Mailbox add-in containing ItemSend event is invalid. Código de error: Mailbox add-in manifest contains ItemSend event in VersionOverrides which is not allowed.

No entiendo cual es el motivo, pero el código funciona, pero no puedo subirlo? Como puedo solucionar esto, llebamos mucho tiempo intentando sacar el proyecto. Utilizamos itemSend, tal y como indica la ayuda de Microsoft, y funciona, pero no puedo publicarlo.

Gracias

**Comment by rkpathak** [comment]
@GrupoOsk You can't publish Outlook add-ins that use the on-send feature to [AppSource](https://appsource.microsoft.com/) Find the details and alternate options here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/outlook-on-send-addins?tabs=windows#limitations
