### ISSUE TITLE
OnMessageAttachmentsChanged event doesn't work if we use "Upload and share as one drive link" when attaching local file to email

### ISSUE THREAD

**Issue by pza-dev-brcm** [OfficeDev/office-js#4677]
We are using ItemSend event in outlook add-in where we monitor email content like subject, body, recipients, attachments and based on policy we decide whether to allow or block the email.
For optimisation, we are handling OnMessageAttachmentsChanged event too in add-in.
As a result, when user attaches any file to email we get callback and we do some processing as per business logic.

When we attach file from local disk having size > 5/10 MB we get option in outlook to attach this file as 
1. Attach as a copy
2. Upload and share as OneDrive link

Things works fine when we select "Attach as a copy option". 
But when we select "Upload and share as OneDrive link" option, we don't get callback in OnMessageAttachmentsChanged event handler.
Also, in ItemSend event if we use Office.context.mailbox.item.getAttachmentsAsync API we don't get any details if we had selected , "Upload and share as OneDrive link" option while attaching an attachment.

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): NA

**Comment by rkpathak** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Internal tracking id: Office: [290659]

**Comment by DivyaPatidar** [comment]
@pza-dev-brcm  This is by design, since when the user selects 'Upload to One Drive', the item is no longer an attachment. Instead it becomes a hyperlink or URL that routes to the file uploaded on OneDrive. Thus, this issue is not related to attachments, as the file is added to the email body via a URL.
