### ISSUE TITLE
context.trackedObjects.add seems to not working properly

### ISSUE THREAD

**Issue by Abacaxi-Nelson** [OfficeDev/office-js#4678]
# Provide required information needed to triage your issue
When using ```context.trackedObjects.add```, i am suppose to be able to reuse this object to insert text for instance. But it's not working 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: MAC
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: Version 16.86 (24060916)
* Operating System: MacOs Sonoma
 
## Expected behavior
When user select some text, i am storing it associated range

```
Word.run(async (context) => {
      const range = context.document.getSelection();
      range.load("text");

      //context.document.track()
      //context.trackedObjects.add(range)
      range.track()
      await context.sync();
      
```

Later, i am unable to use it again, no errors, but nothing appear

```
 await Word.run(async (context) => {
            const range = card.selectedText.range
            range.load("text"); // not sure its needed
            await context.sync(); // not sure its needed

            range.insertText("SOME TEXT", Word.InsertLocation.after);
            await context.sync();
        });
```

## Current behavior
Nothing, no errors

**Comment by shanshanzheng-dev** [comment]
Hi @Abacaxi-Nelson Thanks for reporting this issue, could you provide more detail information about your scenario or your repro video? I try to use this API, seem I can reuse this API again.
`$("#run").on("click", () => tryCatch(run));

async function run() {
  await Word.run(async (context) => {
    
  const range = context.document.getSelection();
  range.load("text");
  await context.sync();
  //context.document.track();
  //context.trackedObjects.add(range);
  range.insertText("SOME test", Word.InsertLocation.after);
  await context.sync();
  range.insertText("SOME test", Word.InsertLocation.after);
  await context.sync();
  //range.track();
  // context.sync();
  });
}

// Default helper for invoking an action and handling errors.
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}
`
