### ISSUE TITLE
Table.clearFilters() has inconsistent behavior

### ISSUE THREAD

**Issue by marianatuma** [OfficeDev/office-js#468]
I posted a question to SO earlier about this issue. You can see it [here](https://stackoverflow.com/questions/55459646/how-to-clear-filters-on-cell-within-range-but-not-within-a-table?noredirect=1#comment97865533_55459646).

I'm trying to delete rows from large files based on some criteria. One of these rows contains a filter, which I believe is what's causing the issue. At first, I was working only with ranges, as these files didn't contain any tables, but ranges do not seem to have any method to clear filters yet, so I resorted to converting the full range to a table and then calling `clearFilters()`, and then working with `TableRow`s. The conversion and `clearFilters()` call don't throw errors, but it seems that most times the filter isn't really removed, so during the deletion phase a GeneralException error is thrown. 

## Expected Behavior
`clearFilters()` should clear all filters in a table after syncing.

## Current Behavior
The function is inconsistent, removing filters some times, but not most of the time. Therefore, on row deletion, a GeneralException is usually thrown.

## Steps to Reproduce, or Live Example
https://gist.github.com/marianatuma/ae493ff6b7cdebc30d4771e95e003fd5

* Additional details:
You can replace `App.tsx` and add `Body.tsx` to the src folder of a yeoman-generated excel add in project. Then, run it on a file that has "Table Name" and a filter on cell A1.

## Context
We have some computer-generated excel spreadsheets that need to be cleaned and formatted. Cell A1 always contains a filter, and it is in a row that needs to be deleted. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Office 365 Business, version 1903 (Build 1145.20202 Click-to-Run)
* Operating System: Windows 10
* Browser (if using Office Online): N/A

**Comment by xiliangms** [comment]
It is hard to repro the issue with your project. Is it possible to have a standalone script that can be run in [scriptlab](https://github.com/OfficeDev/script-lab)?

**Comment by marianatuma** [comment]
Hi @xiliangms. Unfortunately I moved on from this issue by not using Tables and just sticking to Ranges. I think this issue can be closed.

**Comment by xiliangms** [comment]
Noted. Thanks for the notice @marianatuma.

**Comment by kbrandl** [comment]
Closing this issue per the comment from @marianatuma above.
