### ISSUE TITLE
context. document.insertFileFromBase64 not availabe in the latest npm package

### ISSUE THREAD

**Issue by vaishnavi29OT** [OfficeDev/office-js#4683]
## Post how-to questions about your code on Microsoft Q&A

We have several forums where you can ask the developer community questions about your code. Try one of the following forums to ask technical questions about:
- [Developing Office Add-ins for Word, Excel, PowerPoint, Outlook, Project, Visio, and OneNote](https://docs.microsoft.com/answers/topics/office-addins-dev.html)
- [Access programming in Office](https://docs.microsoft.com/answers/topics/office-access-dev.html)
- [Developing COM or VSTO Add-ins for Office](https://docs.microsoft.com/answers/topics/office-vsto-com-dev.html)
- [Office JavaScript API](https://docs.microsoft.com/answers/topics/office-js-dev.html)
- [SharePoint and OneDrive development](https://docs.microsoft.com/answers/topics/sharepoint-dev.html)
- [Deploying and publishing Office or SharePoint apps to AppSource](https://docs.microsoft.com/answers/topics/microsoft-365-apps-publishing-dev.html)

For additional information about JavaScript programming, see the [JavaScript at Microsoft](https://docs.microsoft.com/javascript/) community hub.

**Comment by AlexJerabek** [comment]
Hi @vaishnavi29OT,

Thank you for reporting this. I will assign this issue to @gergzk to make sure the npm package is updating and publishing correctly. However, we recommend not using the office-js npm package in your production add-in. Instead, please reference the version of the library hosted on the Office CDN. Instructions on how to do that are found on the page [Understanding the Office JavaScript API](https://learn.microsoft.com/office/dev/add-ins/develop/understanding-the-javascript-api-for-office).

**Comment by vaishnavi29OT** [comment]
Hi @AlexJerabek ,
This is the requirement from our customer to use npm package. With Office CDN context. document.insertFileFromBase64 API works fine but it is failing with local npm package, and we are on latest version of @microsoft/office-js:1.1.93.

**Comment by vaishnavi29OT** [comment]
Hi @AlexJerabek ,
Any update on this?

**Comment by AlexJerabek** [comment]
@gergzk or @cproscia?

**Comment by vaishnavi29OT** [comment]
Hi @AlexJerabek 
Any update on this?

**Comment by vaishnavi29OT** [comment]
Hi @AlexJerabek 
Any update on the issue

**Comment by AlexJerabek** [comment]
Hi @vaishnavi29OT,

I have reached out to @gergzk and @cproscia internally, but we still don't have an answer. They'll update this thread when they can.

**Comment by vaishnavi29OT** [comment]
Hi @AlexJerabek,
Any update on this?

**Comment by Mithun-KS** [comment]
Hi @AlexJerabek ,
We are dependent on npm module. It would be good if we get updated module which has Office JS related changes.

Thanks,
Mithun

**Comment by jonahkarpman** [comment]
Hi @Mithun-KS,

We apologize for the inconvenience, but we will no longer be supporting the office-js NPM package. Instead, we will focus on maintaining the Office CDN version of the library. This ensures you always have the most secure and up-to-date experience.

We recommend copying the necessary files directly from the CDN. Typically, you only need a few files, so there’s no need to download hundreds. Please reach out if you need any further assistance.
