### ISSUE TITLE
Styles stripped when using setSignatureAsync on Outlook Mobile

### ISSUE THREAD

**Issue by bogdanst24** [OfficeDev/office-js#4685]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mobile
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: mobile
* Browser (if using Office on the web): -
 
## Expected behavior

When using the setSignatureAsync function on Outlook Mobile (either iOS or Android), the used HTML is maintained in order to ensure consistency of the signature across devices. The same HTML should result in the same rendering regardless of the device the email is sent from or previewed on the recipient side (at least throughout Microsoft's products).

## Current behavior

Multiple CSS styles are either modified or removed when using the function on Outlook Mobile. `cellspacing` and `cellpadding` on table elements are completely removed, This causes the emails sent from Outlook Mobile and received on Outlook Desktop to render inconsistently and incorrectly, as Outlook Desktop requires the 2 properties to be set. Alternatives for the 2 properties are not working, as they are also modified upon email send. 

Original HTML to be inserted:
```
<table cellspacing="0" cellpadding="0" bgcolor="#05E560" width="615" height="130" role="presentation">
  <tr>
    <td width="615" height="130">Table text</td>
  </tr>
</table>
```
HTML after the email is sent:
```
<table width="615" height="130" style="background-color: rgb(5,229,96);">
    <tbody>
        <tr>
            <td width="615" height="130">Table text</td>
        </tr>
    </tbody>
</table>
```

**Comment by AlexJerabek** [comment]
Hi @bogdanst24,

Thanks for reporting this. @exextoc, could you please investigate?

**Comment by kumarshrey-msft** [comment]
@bogdanst24 Thanks for reporting this, it's a known issue that few HTML attributes are sanitized by Outlook Mobile's editor. In the meantime to get unblocked, can you try using CSS properties to achieve the desired style? The allowed HTML attributes and sanitized values of a few are documented [here](https://github.com/microsoft/roosterjs/blob/b373c89b1368b69ae1004624bad80f6100c05adb/packages/roosterjs-editor-dom/lib/htmlSanitizer/getAllowedValues.ts).

**Comment by bogdanst24** [comment]
There are known CSS alternatives for `cellspacing` (using border-collapse:collapse) and `cellpadding` (using padding:0 on <td>), but they do not work on Outlook Desktop :(.
A known issue as in a bug already in the backlog, or a known limitation?

**Comment by kumarshrey-msft** [comment]
We have noted your concern regarding CSS alternatives not working on Classic Outlook Desktop and are having internal discussion regarding the best developer experience here. However, the general guidance remains to prefer CSS over HTML attributes to avoid the editor sanitization which might happen across the other clients. 

In the meantime, for this immediate issue, can you try using [Office.Diagnostics](https://learn.microsoft.com/en-us/javascript/api/outlook/office.diagnostics?view=outlook-js-preview) to check for the platform and apply CSS or HTML attributes accordingly?

**Comment by bogdanst24** [comment]
We would prefer not to start doing that, as it looks like the rendering engines and in general email client products are continuously changing. Also, there are no official guidelines on what and how to change. Doing it based on findings from the internet and some local testing is not a good thing for an enterprise product.

**Comment by mobisw-msft** [comment]
Hey @bogdanst24 , we understand your issue. Unfortunately, after careful consideration, our team has decided to not fix this issue in the short term. We recommend you to upvote or create a new [Tech Community](http://aka.ms/M365dev-suggestions) item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue we will re-activate as needed.

Meanwhile we suggest using the workarounds that have been suggested. You can also try to raise an issue with the RoosterJS repo, since it's an open source repository for them to triage the same.
