### ISSUE TITLE
Mac OS - Outlook Desktop issue reading From Address when sending on behalf of another mailbox.

### ISSUE THREAD

**Issue by aantimengocom** [OfficeDev/office-js#4687]
We are now really close to releasing our newly re-written Office 365 Addin, and at the moment we are working on support for this Addin on MacOS 

I have hit a wall with MacOS and the Office.js api, it does things differently in MAC Outlook Desktop than on the other platforms (Windows Desktop, New Outlook, Online all works as expected). 

Scenario is.. 
1.	As a user, I wish to send an email from another mailbox (On Behalf of) – I select another From address in the Email Client
2.	This triggers an event – From Address is changed – I read the new From address and uses this for validation of settings the addin is performing
     a.	Works on Windows Classic, Windows New Outlook, Online Windows and Online Mac
     b.	Does NOT work on Mac Outlook Desktop.

The API I am using to get the From address is: 

**Office.context.mailbox.item.from.getAsync(**

In windows it results in a new Email address being the one selected .. 

On Mac OS Desktop – it is not changing the email address to the newly selected email address – it stays the same. 

Here is the expected change from the way we use it on Office Online version:
![image](https://github.com/user-attachments/assets/c5603fc5-5000-45ff-8362-bc28cdfbf80b)

Changing the From address:
![image](https://github.com/user-attachments/assets/91932e47-e2c2-457d-bdf0-2779c96fa1a1)

On Windows New Outlook Desktop:
![image](https://github.com/user-attachments/assets/9f001852-6dc7-48a9-8237-74e9819396a1)

Changing the From address:
![image](https://github.com/user-attachments/assets/fe7705ec-cd13-4bbe-a148-acef9b5d5952)

Now on MAC OS – Desktop Version :
![image](https://github.com/user-attachments/assets/140b8ecf-8b6e-4cfa-afee-f26e929bc9f5)

When changing the From address to ‘sikkerpost@dev1.timengodpg.com’ – the API of Office.js 
**Office.context.mailbox.item.from.getAsync(**
returns the ‘brugerb@dev1.timengodpg.com’ address – it does not pick up the real From address (On behalf of) which should be ‘sikkerpost@dev1.timengodpg.com’

![image](https://github.com/user-attachments/assets/07a4f304-965a-4e60-a93d-6607fb75c1ec)

I have tried all sorts of endpoints in the API to get the temail address I just selected in the From address but it keeps giving me the mailbox address of the original Sender .. 

Is there a fix for this somehow since our addin relies on this to work. Maybe a workaround api or just an explanation on why the behaivor is different accorss platforms.

**Comment by kumarshrey-msft** [comment]
@aantimengocom Can you share the code snippet of your handler function. We are unable to repro this issue at our end.
