### ISSUE TITLE
How to enable 'dont move or size with cells' property for Add-In

### ISSUE THREAD

**Issue by 3dot1four** [OfficeDev/office-js#469]
**Current behavior:**
On table insert due to cell resize Add-In moves and Resizes itself.

**Expectation:**
Add-In should not move or resize

**Catch:**
I can do that manually from 'Format Shape pane' by selecting 'Don't move or size with cells'. But I am not able to do it programmatically or through Manifest.

This really gives a very bad experience to the users.

PS: We don't want to remove autofit column and autoFit row

**Comment by kbrandl** [comment]
@rohitrewa apologies for the lack of response on this issue; seems that it was overlooked until now. Are you still having this problem? @lumine2008 are you able to provide feedback on this issue?

**Comment by lumine2008** [comment]
@3dot1four , please let us know if you can still repro this issue. thanks

**Comment by lumine2008** [comment]
I'm going to close this issue for now, please reactivate if you're still seeing this. If you can provide snippet/gist to help us test that would be extremely helpful. Thanks!
