### ISSUE TITLE
Issue with Displaying Drafts with Many Attachments in Outlook Web

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js#4696]
**Description:**

I am encountering an issue when using the Office.context.mailbox.displayMessageFormAsync function in Outlook Web. When I attempt to display a draft that contains many attachments, nothing is shown and no error message is returned. This behavior only occurs in Outlook Web.

**Issue Details:**

- **Function Used:** Office.context.mailbox.displayMessageFormAsync
- **Affected Environment:** Outlook Web

- Working Environments:

  - Old Outlook Client
  - New Outlook Client
- **Expected Behavior**: The draft should be displayed correctly, even if it contains many attachments.
- **Observed Behavior**: In Outlook Web, the draft is not displayed and no error message is returned.

**Steps to Reproduce the Issue:**
  - Create a draft with many attachments.
  - Use the Office.context.mailbox.displayMessageFormAsync function to display the draft in Outlook Web.
  - Observe that the draft is not displayed and no error is generated.
  - Repeat the same steps in the old and new Outlook Client, noting that the draft is displayed correctly in these environments.
**Impact:**
- This issue prevents users from correctly viewing drafts with many attachments in Outlook Web, causing difficulties in managing emails. The lack of an error message also makes it challenging to diagnose and resolve the problem.

**Resolution Request:**
Please investigate the cause of this issue and provide a solution that allows drafts with many attachments to be correctly displayed in Outlook Web, similar to how it works in the Outlook Client versions.

Thank you for your attention and assistance.

**Comment by kumarshrey-msft** [comment]
Hi @CodeCube0, as mentioned in our public [documentation](https://learn.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-preview#outlook-office-mailbox-displaymessageformasync-member(1)), in Outlook on the web, this method opens the specified form only if the body of the form is less than or equal to 32K characters. It is possible with multiple attachments you are exceeding this limit.

**Comment by CodeCube0** [comment]
ok thanks, is there a way around this issue? @kumarshrey-msft

**Comment by neprasad-microsoft** [comment]
Hi @CodeCube0 
Unfortunately, we do not have a workaround to provide at this time. We have added a work item to investigate this issue and provide a long-term fix.
Internal tracking ID: [4755801]

**Comment by CodeCube0** [comment]
Thank you @neprasad-microsoft @exextoc
