### ISSUE TITLE
Deleted attachment data is shown in the Office API getAttachmentsAsync request

### ISSUE THREAD

**Issue by riddhi-p-28** [OfficeDev/office-js#4699]
We are developing office web Add in for outlook using event based (Smart Alert) .The Add in is generated using office yo generator Task Pane add-in using the React framework.
We are getting  details of the deleted attachments as well when we are trying to call the office JS API getAttachmentsAsync API.

## Your Environment

* Platform : Office on the web
* Host : Outlook
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

There should only be latest files present in the response.

## Current behavior

There are two files in the getAttachmentsAsync response, even though the first file was deleted.

## Steps to reproduce

1. Compose a new email.
2. Attach an attachment say abc.pdf in the email, wait till it is successfully uploaded.
3. Now attach a new file say xyz.pdf in the same email, while the file xyz.pdf is in uploading state delete the file abc.pdf
4. Now when the attachment change handler fires ,it is bringing the data that has both the attachments even though the first one was deleted.

**Comment by kumarshrey-msft** [comment]
@riddhi-p-28 I am unable to repro this scenario, can you please share your handler function's code? 
A few queries: 
1) Are you able to reproduce this for all kinds of attachments?
2) What is the size of attachment you are trying to delete which incorrectly gets returned as part of the API?
