### ISSUE TITLE
Cross-platform issue. Word return an error when the user tries to modify table/table values 

### ISSUE THREAD

**Issue by aburtsev1** [OfficeDev/office-js#470]
**Description**

Hello, 

We have an application called “Model N Author” (available at MS Store) which uses Word API 1.3.

It is designed to work with O365 hence with both Word 2016 desktop and Word Online.
It allows users to create templates. Template it is word document docx which contains content controls created programmatically with our application. Content controls then get populated with data. 

**Case1. Word Desktop**. Word return an error when the user tries to Add a new row in the table (doc created in Online with the help of our app). 
 A user has a generated document with a table wrapped with content control and when a user tries _**to add the new row to the table / or delete a column**_ in the table and save (or autosave) an error is thrown.

**Preconditions**: 

1. Template with Mn Author Table was created in Online
2. TRACK CHANGES IS OFF IN TEMPLATE

**Steps**: 
1. Assemble a doc from a record.
2. Download it and open in Word Desktop. **_EXAMPLE OF DOC_** : 
[Example.docx](https://github.com/OfficeDev/office-js/files/3065057/Example.docx)
3. Try to add a Row/Column 
4. Insert any text in new row 
5. Try to Modify values in Tables 
6. Save using MS Word (not the Author save).

**Expected Results** : 
 User able to modify tables

**Actual Results** : 
Save return an error because user add new row/column inside the table
![Desktop error](https://user-images.githubusercontent.com/20722542/55900471-f51a2500-5bcf-11e9-80ef-46993928f966.png)

**Case2. Word Online**. Word return an error when the user tries to change values in the table of the doc(created in Desktop). 

When users try to redline a generated doc in Online version they face a weird error. Which seems to be Cross-platform. A user has a generated document with a table wrapped with content control and when a user tries to type something into a table cell and save (or autosave) an error is thrown.

**Preconditions**: 
1. Template created in Desktop (Win10, MS Word for Office 365 MSO (16.0.10730.20334) 64-bit )
There is a table with Content Controls created by our app 
2. TRACK CHANGES IS OFF IN TEMPLATE

**Steps**: 
1. Generate a doc from a record.
2. Download it and open in Word Online.  **_EXAMPLE OF DOC_** :  
[Issue in Online.docx](https://github.com/OfficeDev/office-js/files/3065070/Issue.in.Online.docx)
3. Try to Modify values in Tables 
4. Save using MS Word (not the Author save). 

**Expected Results** : 
AutoSave / Save works, user able to modify values in tables 
 
**Actual Results**: 
Word Online return an error 

![Online error](https://user-images.githubusercontent.com/20722542/55900483-f9ded900-5bcf-11e9-9fc8-d245170516a1.png)

We need to understand the rootcause of this issue, thanks in advance.

**Comment by JuaneloJuanelo** [comment]
@aburtsev1  thanks so much for reporting this. Its challenging to me, however, to diagnose what's going on, so i need further information from you: Also i recommend you to open 2 issues for the 2 problems you have.

1. Can you share the code you are using to create the table in your Case 1? ideally you can use script lab for it. 
2. is this the same code running in both rich client and online?

thanks!

**Comment by JuaneloJuanelo** [comment]
btw @aburtsev1  i just tried some code (see snippet here you can restore it in Script Lab or just see the code and play with it) https://gist.github.com/JuaneloJuanelo/779874386174a618a6dad3b66b58621b

i followed your repro steps. i created the table (wrapped with the cC) in Online, then opened the document in Windows and it worked perfectly.  I also tried it the other way around creating the document in Window with the table wrapped in a CC, then uploaded it to Online and  i was able to change the values.

thats why is super interesting to me to see the code you are using for this, and also encourage you to adjust the code to my version and see if that solves the problem on your end.

please give it a try!

**Comment by JuaneloJuanelo** [comment]
Closing due to 

1. no repro.
2. code sample provided
3.  and inactivity.

**Comment by aburtsev1** [comment]
@JuaneloJuanelo  Sorry for such long inactivity and thanks for your work on this issue. Our team will give feedback according to our priorities in the future.
