### ISSUE TITLE
How to Generate an Email with a Different ‘From’ Address in Office.js and Graph API

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js#4701]
Hello,

I am working on an Office add-in and need to generate an email with a ‘from’ address that is different from the one that initiated the add-in. I would like to know how to achieve this using both Office.js and Microsoft Graph API.

In my add-in, I am using Office.js to create and send emails. However, I am unable to set a different ‘from’ address. Is there a way to specify a different ‘from’ address using Office.js?

I am also exploring the use of Microsoft Graph API to send emails with a different ‘from’ address. My current attempt results in an error indicating that the ‘from’ property is not allowed. How can I correctly set a different ‘from’ address using Graph API?

Any guidance or examples on how to achieve this with either Office.js or Graph API would be greatly appreciated.

Thank you!

Feel free to adjust any details as needed.

**Comment by shanshanzheng-dev** [comment]
Hi @CodeCube0 Thanks for reaching us. You can try this reference: https://learn.microsoft.com/en-us/graph/outlook-send-mail-from-other-user. 
Hi @Rick-Kirkham, do you have any insights about this question? Thanks.
