### ISSUE TITLE
Office.context.mailbox.item properties are null in Desktop version for recurring events

### ISSUE THREAD

**Issue by ystvan** [OfficeDev/office-js#4703]
# Provide required information needed to triage your issue
An Outlook office web add-in has a pure JavaScript that works differently in Windows Desktop and Web for Outlook Calendar **Recurring** events that happens in the future. Single instances are never an issue.

```
 await Office.onReady();

 const item = Office.context.mailbox.item;
```

the `item` for web is

![image](https://github.com/user-attachments/assets/77076b42-7e63-4760-9b41-6935662250d7)

the same `item` for Desktop is (using olk.exe --devtools according to [source ](https://learn.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-devtools-edge-chromium#debug-a-task-pane-add-in-using-microsoft-edge-chromium-based-developer-tools)in Microsoft Learn)

![image](https://github.com/user-attachments/assets/5afb1d3d-4812-4795-9e3c-6f14d619139c)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop and Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft Outlook Version 1.2024.708.200 (Office 365)
* Operating System: Windows 11 Enterprise Version 23H2 OS Build 22631.3880
* Browser (if using Office on the web): Microsoft Edge for Business Version 126.0.2592.102 (Official build) (64-bit)
 
## Expected behavior

The `item `properties are not null for Desktop Version.

## Current behavior

Some properties are null of `item`

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by neprasad-microsoft** [comment]
Hi @ystvan 
We tried to repro this on Outlook on the Web/New Outlook and Legacy Outlook on Windows but could not reproduce this issue.
We tested by checking the Office.context.mailbox.item properties on a recurring event in the future. 
Could you share your add-in manifest?
Which property do you see as null?
On which platform do you see this issue - Legacy Outlook or New Outlook? 
Please collect the log files and share with us - https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues

You can share files in a private repo and give access to exextoc.

**Comment by ystvan** [comment]
Sure thing, before I share my manifest xml, is it OK to obfuscate some values like URLs?

**Comment by ystvan** [comment]
> Hi @ystvan We tried to repro this on Outlook on the Web/New Outlook and Legacy Outlook on Windows but could not reproduce this issue. We tested by checking the Office.context.mailbox.item properties on a recurring event in the future. Could you share your add-in manifest? Which property do you see as null? On which platform do you see this issue - Legacy Outlook or New Outlook? Please collect the log files and share with us - https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues
> 
> You can share files in a private repo and give access to exextoc.

<?xml version="1.0" encoding="UTF-8"?>
<OfficeApp
          xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
          xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0"
          xsi:type="MailApp">

	

	
	<Id>00000000-0000-0000-0000-000000000000</Id>

	
	<Version>2.0.0.2</Version>
	<ProviderName>Lorem ipsum</ProviderName>
	<DefaultLocale>en-US</DefaultLocale>
	
	<DisplayName DefaultValue="Lorem ipsum" />

	<Description DefaultValue="Lorem ipsum">
		<Override Locale="da-DK" Value="Lorem ipsum" />
		<Override Locale="de-DE" Value="Lorem ipsum" />
		<Override Locale="sv-SE" Value="Lorem ipsum" />
		<Override Locale="no-NO" Value="Lorem ipsum" />
	</Description>

	
	<IconUrl DefaultValue="https://lorem.ipsum.net/icon-64.png"/>
	<HighResolutionIconUrl DefaultValue="https://lorem.ipsum.net/icon-128.png"/>

	
	<SupportUrl DefaultValue="https://lorem.ipsum.net/" />

	
	<AppDomains>
		<AppDomain>https://lorem.ipsum.net/</AppDomain>
		<AppDomain>https://login.microsoftonline.com/</AppDomain>
		<AppDomain>https://login.microsoftonline.com/common</AppDomain>
		<AppDomain>https://login.microsoftonline.com/common/oauth2/</AppDomain>
		<AppDomain>https://login.microsoftonline.com/common/oauth2/v2.0/</AppDomain>
		<AppDomain>https://login.microsoftonline.com/common/oauth2/v2.0/authorize/</AppDomain>
	</AppDomains>
	

	<Hosts>
		<Host Name="Mailbox" />
	</Hosts>
	<Requirements>
		<Sets>
			<Set Name="Mailbox" MinVersion="1.1" />
		</Sets>
	</Requirements>
	<FormSettings>
		<Form xsi:type="ItemRead">
			<DesktopSettings>
				<SourceLocation DefaultValue="https://lorem.ipsum.net/"/>
				<RequestedHeight>250</RequestedHeight>
			</DesktopSettings>
		</Form>
	</FormSettings>

	<Permissions>ReadWriteItem</Permissions>
	<Rule xsi:type="RuleCollection" Mode="Or">
		<Rule xsi:type="ItemIs" ItemType="Message" FormType="Read"/>
		<Rule xsi:type="ItemIs" ItemType="Appointment" FormType="Read"/>
	</Rule>
	<DisableEntityHighlighting>false</DisableEntityHighlighting>

	<VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
		<VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">

			<Requirements>
				<bt:Sets DefaultMinVersion="1.3">
					<bt:Set Name="Mailbox" />
				</bt:Sets>
			</Requirements>
			<Hosts>
				<Host xsi:type="MailHost">

					<DesktopFormFactor>
						
						<ExtensionPoint xsi:type="AppointmentOrganizerCommandSurface">
							<OfficeTab id="TabDefault">
								<Group id="CategoriesGroupAppointmentOrganizer">
									<Label resid="CategoriesGroupLabel"/>
									<Control xsi:type="Button" id="AppointmentOrganizerSelectButton">
										<Label resid="SelectButtonLabel"/>
										<Supertip>
											<Title resid="SelectButtonLabel"/>
											<Description resid="SelectButtonDescription"/>
										</Supertip>
										<Icon>
											<bt:Image size="16" resid="icon16" />
											<bt:Image size="32" resid="icon32" />
											<bt:Image size="80" resid="icon80" />
										</Icon>
										<Action xsi:type="ShowTaskpane">
											<SourceLocation resid="showTaskpaneUrl"/>
										</Action>
									</Control>
								</Group>
							</OfficeTab>
						</ExtensionPoint>
						<ExtensionPoint xsi:type="AppointmentAttendeeCommandSurface">
							<OfficeTab id="TabDefault">
								<Group id="CategoriesGroupAttendeeOrganizer">
									<Label resid="CategoriesGroupLabel" />
									<Control xsi:type="Button" id="AppointmentAttendeeSelectButton">
										<Label resid="SelectButtonLabel" />
										<Supertip>
											<Title resid="SelectButtonLabel" />
											<Description resid="SelectButtonDescription" />
										</Supertip>
										<Icon>
											<bt:Image size="16" resid="icon16" />
											<bt:Image size="32" resid="icon32" />
											<bt:Image size="80" resid="icon80" />
										</Icon>
										<Action xsi:type="ShowTaskpane">
											<SourceLocation resid="showTaskpaneUrl" />
										</Action>
									</Control>
								</Group>
							</OfficeTab>
						</ExtensionPoint>
					</DesktopFormFactor>
				</Host>
			</Hosts>
			<Resources>
				<bt:Images>
					<bt:Image id="icon16" DefaultValue="https://lorem.ipsum.net/Icon-16.png"/>
					<bt:Image id="icon32" DefaultValue="https://lorem.ipsum.net/Icon-32.png"/>
					<bt:Image id="icon80" DefaultValue="https://lorem.ipsum.net/Icon-80.png"/>
				</bt:Images>
				<bt:Urls>
					<bt:Url id="showTaskpaneUrl" DefaultValue="https://lorem.ipsum.net/"/>
				</bt:Urls>
				<bt:ShortStrings>
					<bt:String id="CategoriesGroupLabel" DefaultValue="Lorem ipsum"/>
					<bt:String id="SelectButtonLabel" DefaultValue="Lorem ipsum">
						<bt:Override Locale="da-DK" Value="Lorem ipsum" />
						<bt:Override Locale="ge-GE" Value="Lorem ipsum" />
						<bt:Override Locale="sv-SE" Value="Lorem ipsum" />
						<bt:Override Locale="no-NO" Value="Lorem ipsum" />
					</bt:String>
				</bt:ShortStrings>
				<bt:LongStrings>
					<bt:String id="SelectButtonDescription" DefaultValue="Lorem ipsum">
						<bt:Override Locale="da-DK" Value="Lorem ipsum" />
						<bt:Override Locale="ge-GE" Value="Lorem ipsum" />
						<bt:Override Locale="sv-SE" Value="Lorem ipsum" />
						<bt:Override Locale="no-NO" Value="Lorem ipsum" />
					</bt:String>
				</bt:LongStrings>
			</Resources>
			<WebApplicationInfo>
				<Id>00000000-0000-0000-0000-000000000000</Id>
				<Resource>api://lorem.ipsum.net/00000000-0000-0000-0000-000000000000</Resource>
				<Scopes>
					<Scope>openid</Scope>
					<Scope>user.read</Scope>
					<Scope>calendars.read</Scope>
					<Scope>profile</Scope>
				</Scopes>
			</WebApplicationInfo>
		</VersionOverrides>
	</VersionOverrides>
</OfficeApp>

**Comment by ystvan** [comment]
` Which property do you see as null? `

everything is null, except two properties: itemType and seriesId

`On which platform do you see this issue - Legacy Outlook or New Outlook?`

New outlook

**Comment by ystvan** [comment]
@neprasad-microsoft @exextoc shared a repro https://github.com/ystvan/OutlookRepro

**Single event works** 

![image](https://github.com/user-attachments/assets/f7e3effb-b393-4407-a33a-1d5784c06ca5)

Recurring event from Outlook Web

![image](https://github.com/user-attachments/assets/741ab78a-1cb4-4680-a552-a98e57c0447a)


Recurring event from Outlook Windows Desktop (New not Legacy) 

Notice all the missing properties

# Repro steps

1. Create a recurring event for next week, daily occurrences running for 2 weeks
2. Open the web add in when selecting an occurrence
3. See debug point on `item `after `Office.onReady`

![image](https://github.com/user-attachments/assets/ce33c6b0-b527-47c4-8bfe-da643c9aea5c)

**Comment by neprasad-microsoft** [comment]
Hi @ystvan 
This is happening because in Monarch the item opens in edit mode and in OWA the item opens in Read mode. Both of these have different set of APIs and properties on item. This is expected behaviour.

**Comment by ystvan** [comment]
@neprasad-microsoft 
> This is happening because in Monarch the item opens in edit mode and in OWA the item ope

What is `Monarch`? Can I change the behaviour? Can I open in Monarch in `read mode`? Can you please point me to a documentation where can I read upon it?

**Comment by ystvan** [comment]
@neprasad-microsoft 
Is there any kind of `item ` in Monarch that holds the information I need

- item.itemId,
- item.subject,
- item.start,
- item.end,
- item.dateTimeCreated,
- item.dateTimeModified,
- item.location,
- item.organizer,
- item.itemType,
- item.seriesId,
- item.sensitivity

**Comment by neprasad-microsoft** [comment]
Hi @ystvan 
All of these will be available as async properties on the appointment compose surface - https://learn.microsoft.com/en-us/javascript/api/outlook/office.appointmentcompose 
For example to get the subject you can write something like this - 
`Office.context.mailbox.item.subject.getAsync((result) => {
  if (result.status !== Office.AsyncResultStatus.Succeeded) {
    console.error(`Action failed with message ${result.error.message}`);
    return;
  }
  console.log(`Subject: ${result.value}`);
});`
Copied from - https://learn.microsoft.com/en-us/javascript/api/outlook/office.appointmentcompose?view=outlook-js-preview#outlook-office-appointmentcompose-subject-member

**Comment by ystvan** [comment]
@neprasad-microsoft Appreciate the sources for the documentation. Thank you, it worked!
