### ISSUE TITLE
CRITICAL: No add-ins available in Outlook

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#4704]
# Provide required information needed to triage your issue
Add-ins are not being shown in the Apps modal. This is not add-in specific and appears to be impacting every add-in across every platform.

![image](https://github.com/user-attachments/assets/e2e8ad8d-ec1e-44ed-95c9-9da07520e610)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): ______
 
## Expected behavior
Installed add-ins are available across all platforms.

**Comment by neprasad-microsoft** [comment]
Thanks for reporting this issue @cody-lettau. We are investigating this bug.

**Comment by cody-lettau** [comment]
Is there any update on this? Add-ins with on-send triggers, although installed, are not being triggered. You also cannot open the add-in at all in Read or Compose.

This is a critical issue as add-ins may be performing security scanning before sending messages.

**Comment by JuaneloJuanelo** [comment]
Yes, we worked on an incident, this was a problem in the service that delivers add-ins. we expect the fix will be in PROD within the next 45 minutes.

**Comment by cody-lettau** [comment]
@JuaneloJuanelo I am seeing the add-ins on my accounts. If we continue to get reports, we'll follow back up. Thanks for the quick resolution here.

How can we ensure this doesn't happen again? This is a very concerning issue that puts many who believe they have specific add-ins running on every message in risk of workflows not being executed that may be protecting their data.

**Comment by JuaneloJuanelo** [comment]
Thanks for confirming the fix. I am glad the team was able to resolve this situation extremely fast and learn how to prevent similar situations in the future. We appreciate your partnership.
