### ISSUE TITLE
On-Send web addin does not load when new file is created from group

### ISSUE THREAD

**Issue by Medha-lab** [OfficeDev/office-js#4707]
Issue Description-
On-Send web addin does not load when new file is created from group

Steps to Reproduce -
1. Login to new outlook.
2. From left pane click on groups.
3. Select any group.
4. Click on new and create any file say Doc.
5. While creating file able to add sensitive text or sensitive label.

Actual Result:
On-Send web addin does not load when new file is created from group

Expected Result -
On-Send web addin should load when new file is created from group

Environment

    Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
    Host [Excel, Word, PowerPoint, etc.]: New outlook
    Office version number: You have Microsoft Outlook Version 1.2024.708.100 (Production). 
    Client Version is 20240712002.10
    webview2 version is 126.0.2592.113
    session id is 6fcbff88-ff45-7a4b-ac09-3494fe7b37da
    Operating System: win 11

**Comment by Medha-lab** [comment]
![image-2024-06-28-14-00-43-572](https://github.com/user-attachments/assets/632f0e3a-ea7e-4c8d-8422-b75adf5a8fe9)

**Comment by neprasad-microsoft** [comment]
Hi @Medha-lab 
OnSend add-ins are only supported when you send an email. From the screenshot it looks like you have created a new Word file. In this case, the add-in will not run. 
Could you send a screen recording of the issue you are facing, so that we can help you better. Thanks.

**Comment by Medha-lab** [comment]
I will update it today

**Comment by Medha-lab** [comment]
Please find attachment herewith -
https://github.com/user-attachments/assets/a58499bd-2852-473d-9b10-b681d7a66a9e

**Comment by dahuja10** [comment]
Hi @Medha-lab , as Neha mentioned outlook add-ins (including on send add-ins) activate when the user is composing or reading a message or appointment, but not other item types. In this scenario add-ins are not supposed to load.
