### ISSUE TITLE
Word web is freezing after executing body.clear()

### ISSUE THREAD

**Issue by didu9898** [OfficeDev/office-js#4708]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: ______
* Operating System: Win 11 Enterprise 
* Browser (if using Office on the web): Chrome & Edge
 
## Expected behavior
Word should not freeze

## Current behavior
1. Word is frozen after running the code below
2. body.clear() does not clear the document (even though it works on excel desktop)
3. After that, when the window is refreshed, the document is not loaded and is stuck on loading. I need to close the brower and then reopen the window

## Steps to reproduce
1. Go to word.new and create new document
2. Add any table (I selected "Table of contents" from insert menu
4.  Open ScriptLab and add the following code:

```
$("#run").on("click", () => tryCatch(run));

async function run() {
  await Word.run(async (context) => {
    // clear document after 5 seconds
    setTimeout(async () => {
      console.log("Triggered after 5 seconds");
      context.document.body.clear();
      await context.sync();
    }, 5000);
  });
}

async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    console.error(error);
  }
}

```
5. Run the script and click "Run" button. This script is supposed to clear the document after 5 seconds. (current behavior: it does not clear the table)
6. Try click any other menu or type anything in the document (current behavior: window is frozen)
7. Try refreshing the window (current behavior: window is not loaded and is stuck on loading)

## Link to live example(s)
1. https://github.com/user-attachments/assets/2be03965-d344-4b5a-bf4d-bc18b224ff49
As you can clearly see in the video, after getting console msg "Triggered after 5 seconds", I tried to click other menu buttons. The window is frozen. Also, I try to refresh the window after that, but it is stuck on loading and window is not loaded.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by YijunMS** [comment]
@didu9898 Thanks for reaching us. We created an internal bug (9195579) to track this issue. I will update here once there are any progress.

**Comment by didu9898** [comment]
@YijunMS thank you for the information. Can you please confirm if it was replicable on your end?

**Comment by YijunMS** [comment]
@didu9898 Yes, it is replicable on my side.

**Comment by didu9898** [comment]
```
const range = context.document.getSelection();
const pageRange = range.parentBody.getRange();
pageRange.delete();
```

Please note that instead of document.clear(), I used the above code and the issue still replicable i.e. word web is freezing.

**Comment by YijunMS** [comment]
@didu9898 We just deployed a fix. Could you check if the issue still exists?

**Comment by didu9898** [comment]
It is fixed now. The word is still freezing when the word contains content controls and I run clear(). I will investigate it and will reopen this ticket or create a new one. Thank you.
