### ISSUE TITLE
Closing Smart Alerts dialog does not open specified task pane in Outlook on web.

### ISSUE THREAD

**Issue by AyushJ09** [OfficeDev/office-js#4709]
# Provide required information needed to triage your issue
In web version of outlook, I configured Smart Alerts in my Outlook Add-in to check for attachments while composing an email. I assigned a task pane to the "Don't Send" button of the Smart Alert dialog but closing the dialog does not open specified task pane.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows 11
* Browser (if using Office on the web): Microsoft Edge
 
## Expected behavior
Closing the Smart Alerts dialog while composing an email in the web version of Outlook should open the specified task pane.

## Current behavior
I configured Smart Alerts in my Outlook Add-in to check for attachments while composing an email. I assigned a task pane to the "Don't Send" button of the Smart Alerts dialog. According to the documentation, closing the Smart Alerts dialog should open the specified task pane when the "Don't Send" button is assigned to a task pane. However, when I close the Smart Alerts dialog, the specified task pane does not open.

## Steps to reproduce
1. In web version of Outlook, Add-in is installed and configured with Smart Alerts. "Don't Send" button of alert dialog is assigned a specified task pane.  
2. Create an email with attachments.
3. Click on send button.
4. Smart alert dialog is appeared.
5. Click on close button of smart alerts dialog.
6. Dialog is closed but specified task pane is not opened.

**Comment by neprasad-microsoft** [comment]
Hi @AyushJ09 
Is this add-in available on store?
If not, can you share the manifest of your add-in to help us repro?
Does this add-in work as expected on other platforms( Legacy Outlook on Windows/New Outlook on Windows/Mac) ?

**Comment by AyushJ09** [comment]
Hello, Sorry for delayed reply.
This add-in is not available on store.
The Add-in is under development and can not share any file due to company policy.
But If you guys need manifest file to repro so for this I will create a new Add-in that will replicate this issue.
I will provide you repo link or codebase by today or tomorrow.
Thanks

**Comment by ajays-msft** [comment]
@AyushJ09 - Please share the manifest and sample code in a private github repo, and give access to @exextoc

**Comment by AyushJ09** [comment]
Hi, Please see the attached repository.
[Smart Alters Task pane Add-in](https://github.com/AyushJ09/Smart-Alters-Task-pane-Add-in.git)

**Comment by AyushJ09** [comment]
Once again, A quick overview about this issue. I only encountered this issue on Outlook on web.
According to documentation, "If you assign a task pane to the Don't Send button, closing the dialog also opens the specified task pane." but this does not work properly on Outlook on web. When I close the Smart Alters Dialog using close (X) button, task pane does not open. 

- This issue occurs on the web only, while Outlook desktop application works according to documentation.

See below screen shot of documentation. [Documentation Link](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest#override-the-send-mode-option-at-runtime-optional)
![Screenshot (376)](https://github.com/user-attachments/assets/e332dd16-5a5a-46a1-8d4b-c4bb598111ae)

**Comment by ndeleuze** [comment]
@AyushJ09 thank you for bringing this to our attention. The intended behavior was to have the close button (x) act as a simple cancel button without invoking the Taskpane. So, in reality, the documentation and behavior for Win32 was incorrect and the web version of Outlook had the correct behavior. This issue in Win32 has been fixed and the documentation has been updated: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/smart-alerts-onmessagesend-walkthrough?tabs=xmlmanifest#try-it-out

I will mark this issue as closed. Thank you again!
