### ISSUE TITLE
FileSaver.js does not work on Excel for Mac

### ISSUE THREAD

**Issue by MakotoE** [OfficeDev/office-js#471]
## Expected Behavior

When FileSaver.saveAs() is executed, a save file dialog appears.

## Current Behavior

Nothing happens after FileSaver.saveAs().

## Steps to Reproduce, or Live Example

* Link to live example: https://gist.github.com/MakotoE/a5e2b715e73ab245efec8c6e5874dcae

Running the test script should immediately show the save file dialog.

This issue is specific to Excel for Mac. I also experience the same issue on Excel for iPad, but they might have a different root cause, so it's probably better to try to solve the Mac issue first. Excel versions that do not exhibit this bug: Excel Online (on any OS or browser), Excel 2013 (Windows), Excel 2016 (Windows).

FileSaver.js: https://github.com/eligrey/FileSaver.js/

## Context

My add-in contains an option for exporting a converted file, but I will have to disable that option on the Mac due to this bug.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.23
* Operating System: macOS Mojave 10.14.4
* Browser (if using Office Online): ______

## Useful logs

- [x ] Console errors
No error is thrown.

- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by MakotoE** [comment]
I created a minimal example which does not use FileSaver: https://gist.github.com/MakotoE/b91ddfc877dfd0d9e8015c578882f6ee This uses FileReader, which is what filesaver is using for Safari.

This is an alternative method using createObjectURL: https://gist.github.com/MakotoE/573eea408187b4441d66e91f03858afb Like the other example, this works on Excel Online but not in Excel for Mac.

**Comment by kbrandl** [comment]
@MakotoE apologies for the lack of response on this issue; seems that it was overlooked until now. Are you still having this problem? @lumine2008 are you able to provide feedback on this issue?

**Comment by MakotoE** [comment]
Oh wow, this issue has been fixed at some point after I wrote this issue. Thanks Office team!

**Comment by kbrandl** [comment]
@MakotoE thanks for confirming (and for closing the issue)!

**Comment by he-yang** [comment]
> Oh wow, this issue has been fixed at some point after I wrote this issue. Thanks Office team!

@MakotoE I am experiencing the same issue, could you share how did you solved it ?
