### ISSUE TITLE
OnMessageAttachmentsChanged event doesn't get called for each attachment when multiple attachments added to email

### ISSUE THREAD

**Issue by pza-dev-brcm** [OfficeDev/office-js#4711]
We are using ItemSend event in outlook add-in where we monitor email content like subject, body, recipients, attachments and based on policy we decide whether to allow or block the email.

For optimisation, we are handling OnMessageAttachmentsChanged event too in add-in.
As a result, when user attaches any file to email we get callback and we do some processing as per business logic.

When we attach multiple files from local disk then callback handler doesn't get invoked for all the files which are attached.
For e.g if we are attaching 8 files at a time then attachment event handler gets called for 6/7 files.

Expected Result: for all the attached files OnMessageAttachmentsChanged event handler should get called 

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop as well as Office on the web
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.103.100 (Production) | Client Version 20240119003.15 .
Operating System: Windows11
Browser (if using Office on the web): Chrome

**Comment by neprasad-microsoft** [comment]
This issue is a known bug and is in our backlog.  Further updates on this will be tracked on the original issue - https://github.com/OfficeDev/office-js/issues/4646 .  Closing this as duplicate.
