### ISSUE TITLE
Outlook NAA GA questions: Enable SSO in an Office Add-in using nested app authentication (preview)

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#4712]
we notice [New Nested App Authentication for Office Add-ins: Legacy Exchange tokens off by default in October 2024](https://devblogs.microsoft.com/microsoft365dev/new-nested-app-authentication-for-office-add-ins-legacy-exchange-tokens-off-by-default-in-october-2024)  and [Enable SSO in an Office Add-in using nested app authentication (preview)](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/enable-nested-app-authentication-in-your-add-in). and we have a few question here:

What confuses me is that **acquireTokenSilent always needs to pop up an authorization window before returning the access token.** After reading the following article, I found that this seems to be inevitable. [https://learn.microsoft.com/en-us/entra/identity-platform/scenario-spa-acquire-token?tabs=javascript2](https://urldefense.proofpoint.com/v2/url?u=https-3A__learn.microsoft.com_en-2Dus_entra_identity-2Dplatform_scenario-2Dspa-2Dacquire-2Dtoken-3Ftabs-3Djavascript2&d=DwMGaQ&c=8lBT5Jra4Bm5rFhLVR7k1wx3__gIUgr523Abjhgq6Gg&r=zROIFWCYJLV3hX49Oy6Xt87hYpzk6YQKLvqr47b2D5o&m=z_EkyaNkB7RkH5q-dre7bXZbcpKzUj0mlQeJaKvakWqPm0_hpLp6kT9GySU6o7nO&s=Zjs38Vh1mTBe56IhLnPvMcaErMd3xXnk5AOm9ht5zhk&e=) So, my question is whether such a change is **must and always** be accompanied by the customer needing to receive a pop-up authorization window from time to time before being able to proceed.
 
If so, this seems to be a very different behavior for the smooth transition of customers (compared to getCallbackTokenAsync). I am very worried that it will confuse and cause customers to complain. By the way, in my side: **From a customer's perspective, I hope this pop-up window only appears when the IT admin authorizes it. It would be best if the user never needs to know about its existence.**

And here is my test result in different platform.

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2487.6">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'}
table.t1 {border-collapse: collapse}
td.td1 {border-style: solid; border-width: 1.0px 1.0px 1.0px 1.0px; border-color: #9a9a9a #9a9a9a #9a9a9a #9a9a9a; padding: 1.0px 5.0px 1.0px 5.0px}
</style>
</head>
<body>

Platform | Result
-- | --
Mac Outlook Old & New | Pop up for only first time
Win32 Outlook | Pop up every time
OWA on Chrome | Pop up for only first time in 24 hours
OWA on Edge/Safari | Error, not available pop up

</body>
</html>

And here is the gif recording:
Win32 Outlook:
![Win32Outlook1](https://github.com/user-attachments/assets/65cdfd9e-c17e-4277-aaef-01ea7939a4c9)

Mac Outlook:
![MacOutlook](https://github.com/user-attachments/assets/d1f6dbb8-3100-490f-bf84-4a575dc6f9b3)

OWA for chrome:
![OWA Chrome](https://github.com/user-attachments/assets/9608ed73-b5e4-4946-b785-b548fdd37f26)

OWA Edge:
![OWA Edge](https://github.com/user-attachments/assets/8e7a9462-e103-40e8-9ec6-6a789e29f843)

Here is the research code for getting original start time in an occurrence.

And the client id is what we used(28da465e-7729-4caa-a29b-0201166cc364) which is [Enable single sign-on (SSO) in an Office Add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins?tabs=jsonmanifest) what we used in addin manifest:
![image](https://github.com/user-attachments/assets/417f7999-8b8a-4573-882a-bf08f54bcd81)

Here is the APP owner’s configure:
![image](https://github.com/user-attachments/assets/6afbb9dd-3fbf-4193-9a02-7f90620a82fe)
![image](https://github.com/user-attachments/assets/77a5a10c-bc2b-4418-9cae-91561a2a2736)

Here is the APP admin user's configure:
![image](https://github.com/user-attachments/assets/6fcf56d8-fb2a-4fc6-81f1-6e4913962b48)

for the code segment:
```
async function getItemId() {
    return new Office.Promise(function (resolve) {
        if (Office.context.requirements.isSetSupported('Mailbox', '1.8')) {
            Office.context.mailbox.item.getItemIdAsync(function(result) {
                if(Office.AsyncResultStatus.Succeeded == result.status) {
                    resolve(result.value);
                } else {
                    resolve(null);
                }
            });
        }
        else {
            resolve(null);
        }
    });
};

async function getOriginalStartTime() {
    var resolve = null;
    try {
        const itemId = await getItemId();
        if (null === itemId) {
            resolve = null;
        } else {
            if (Office.context.requirements.isSetSupported('Mailbox', '1.5')) {
                setTimeout(() => {
                    console.log("waiting getCallbackTokenAsync timeout.");
                    resolve = null;
                }, 10000);
                // graph api
                const pca = await createNestablePublicClientApplication({
                    auth: {
                        clientId: "28da465e-7729-4caa-a29b-0201166cc364",
                        authority: "https://login.microsoftonline.com/common"
                    },
                });
                console.log('pca: ', pca, pca.getAllAccounts().length, JSON.stringify(pca.getAllAccounts()));
                // Specify minimum scopes needed for the access token.
                const tokenRequest = {
                    scopes: ["[User.Read](http://user.read/)", "openid", "profile", "[Calendars.Read](http://calendars.read/)"],
                };

                if (pca.getAllAccounts().length > 0) {
                    tokenRequest.account = pca.getAllAccounts()[0];
                }
                let accessToken = null;
                // TODO 1: Call acquireTokenSilent.
                try {
                    console.log("Trying to acquire token silently...");
                    const userAccount = await pca.acquireTokenSilent(tokenRequest);
                    console.log("Acquired token silently.");
                    accessToken = userAccount.accessToken;
                } catch (error) {
                    console.log(`Unable to acquire token silently: ${error}`);
                }

                // TODO 2: Call acquireTokenPopup.
                if (accessToken === null) {
                    // Acquire token silent failure. Send an interactive request via popup.
                    try {
                        console.log("Trying to acquire token interactively...");
                        const userAccount = await pca.acquireTokenPopup(tokenRequest);
                        console.log("Acquired token interactively.", userAccount);
                        accessToken = userAccount.accessToken;
                    } catch (popupError) {
                        // Acquire token interactive failure.
                        console.log(`Unable to acquire token interactively: ${popupError}`);
                    }
                }

                // TODO 3: Log error if token still null.
                if (accessToken === null) {
                    console.error(`Unable to acquire access token.`);
                    return;
                }

                console.log(`Access token: ${accessToken}`);
                var restId = self.convertToRestId(itemId);

                // for public graph replace PropertyId to id
                var filterString = "?$select=originalStart";
                var baseUrl = 'https://graph.microsoft.com/';
                if (0 === baseUrl.length || 0 === restId.length) {
                    console.log("exception :getRestUrl or restId failed");
                    resolve = null;
                }

                var getMessageUrl = baseUrl + '/v1.0/me/events/' + restId + filterString;
                var authHeader = { 'Authorization': 'Bearer ' + accessToken };
                resolve = await get(getMessageUrl)({}, authHeader);
            } else {
                resolve = null;
            }
        }

    } catch (error) {
        console.error('get original start time: ', error);
        resolve = null;
    }

    return new Office.Promise(function (res, rej) {
        if (resolve) {
            res(resolve);
        } else {
            rej({});
        }
    });
}
```

**Comment by codexeon** [comment]
based on your recording, it doesn't appear to be using broker based flow for Nested App Auth. There should not be a popup unless user or admin has not previously consented to the scopes you are requesting. Could you validate if you are testing in the Beta Channel with Windows/Mac, and provide the build number?

**Comment by hello-chenchen** [comment]
hi @codexeon , so much thanks for your reply. and as you can see, i pasted my code segment in above. and i was follow https://learn.microsoft.com/en-us/entra/identity-platform/scenario-spa-acquire-token?tabs=javascript2 and https://learn.microsoft.com/en-us/office/dev/add-ins/develop/enable-nested-app-authentication-in-your-add-in in the document. Do you mind paste your test code here, and give some suggestion. really thanks for it!

And my test environment is also stable build.
Mac version:
<img width="532" alt="image" src="https://github.com/user-attachments/assets/4965f6a0-d3b4-4ee5-bf2b-a2a2a2ad39e3">
Win32 version:
<img width="760" alt="image" src="https://github.com/user-attachments/assets/cfe5b68d-00d8-402a-bf09-d17b0014cea0">
OWA is always lastest i think.

**Comment by codexeon** [comment]
The Win32 build you are using likely does not have Nested App Auth support. It requires being in the preview channel as documented here: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/enable-nested-app-authentication-in-your-add-in. I would expect a build 16.0.17925.20000 or later if you were to update to the latest preview today. For Mac/OWA your NAA should have support in new Outlook, however. When you mention a popup only the first time, is it for sign-in or to consent to permissions? I would expect a popup required to consent to permissions, if you haven't previously in another session, but not for a sign-in. If you are seeing that popup window to login without consent on every endpoint, it is likely an issue in the add-in JavaScript. https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/auth/Outlook-Add-in-SSO-NAA/src/taskpane/authConfig.ts is our sample that shows how to get additional logging from msal-browser for further diagnostic (set enableDebugLogging to true). If you enable the logging, you should be looking for a message "Nested App Auth Bridge available: true" in console. If you see "Nested App Auth Bridge available: false", the host does not support Nested App Auth. If you don't see the message at all, msal-browser is not trying to use Nested App Auth.

**Comment by hello-chenchen** [comment]
hi @codexeon , thanks your reply. sorry to see it later. i use this example: https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/auth/Outlook-Add-in-SSO-NAA. And it works. but as you said, **I would expect a popup required to consent to permissions, if you haven't previously in another session, but not for a sign-in.** So, it will also popup a permission dialog, if haven't previously in another session right? if so, do you know if there is some way for not popup that dialog? cause, as you know for  Legacy Exchange tokens, there is no need popup dialog. it very silent for users. But, when we switch the NAA, if user must popup a dialog, i think that's too confuse for user. By the way, there is an admin consent on AAD app, But it still need the admin to consent also, not silent, do we have more silent way? https://learn.microsoft.com/en-us/entra/identity-platform/v2-admin-consent

**Comment by davidchesnut** [comment]
Hi @hello-chenchen,

The NAA will pop up a dialog if SSO won't work. For example, it needs user consent, or 2FA, or the Office client does not support NAA SSO. It does seem confusing that it can pop up a dialog even though you called acquireTokenSilent, but this is the by design behavior. Especially coming from Exchange token SSO behavior. You could follow up with the Microsoft identity team with suggestions for your scenario at https://learn.microsoft.com/entra/identity-platform/developer-support-help-options#share-your-product-ideas

There is an admin consent URI you can provide to tenant admins so they can consent to your add-in and avoid users having to see that dialog. https://learn.microsoft.com/entra/identity-platform/v2-admin-consent

You can also streamline admin consent by specifying the [WebApplicationInfo.id property](https://learn.microsoft.com/microsoftteams/platform/resources/schema/manifest-schema#webapplicationinfo) in the unified app manifest. Then admins can consent as part of the deployment UI. Unfortunately this won't work in the XML version of the schema. So don't use WebApplicationInfo with the scopes in the XML version as it may or may not work. It's not a supported manifest mechanism for NAA SSO. It's only for the OBO SSO flow.

Hope this helps,
David

**Comment by davidchesnut** [comment]
Hi @hello-chenchen,

A correction to my previous post. NAA will not pop up a dialog when calling acquireTokenSilent. There was a bug at one point where this would happen. Can you please let us know if you still see this behavior because it shouldn't be there now.

Thanks!
David
