### ISSUE TITLE
Issues sending mail in Outlook for Mac 16.87+

### ISSUE THREAD

**Issue by asavage13** [OfficeDev/office-js#4713]
# Provide required information needed to triage your issue

## Your Environment
Mac
Outlook
Version 16.87 (24071426)
MacOS Sonoma Version 14.5 (23F79)

## Expected behavior
You should be able to send an email using Microsoft Outlook, without the application crashing. Being able to send an email without major delays 

## Current behaviour
- When you have office-js based add-ins enabled seems to make this problem worse
- Outlook crashes and shuts down equalling to you not being able to reply to a message 
- Spinning wheel is visible for a very long time
- Messages in the thread flash continuously when the email is trying to send 

## Steps to reproduce
1. Reply to an email chain 
2. Send the email
3. Spinning wheel appears for a while
4. Messages flash as it tries to send
5. Email disappears 
6. Email goes into Outbox OR outlook crashes

# Provide additional details
Please see attachment for Microsoft Error Reporting Log

## Context

Can't not reply to a long email thread. Affecting us by not being able to reply to emails

## Useful logs
Links regarding the same issue
https://www.reddit.com/r/Office365/comments/1e9emw5/outlook_for_mac_1687_mail_going_into_outbox_and/
https://answers.microsoft.com/en-us/outlook_com/forum/all/outlook-error-code-3523/7a05a47a-68ad-4964-a66a-c752d6c37222 

[Microsoft Error Reporting log version.docx](https://github.com/user-attachments/files/16364323/Microsoft.Error.Reporting.log.version.docx)

**Comment by mmcnutt** [comment]
I have mac users in my organisation suffering from this too

**Comment by neprasad-microsoft** [comment]
Hi @asavage13, @mmcnutt 
This forum is limited to office-js related queries. For crash in Outlook Mac please use the "Contact Support" within Outlook for Mac - https://support.microsoft.com/en-us/office/contact-support-within-outlook-for-mac-d0410177-8e65-4487-93f7-206a3a3d71a8 .

**Comment by asavage13** [comment]
@neprasad-microsoft thank you for the reply. As mentioned in the steps it doesn't always crash, I'd say 5/10 times it will crash. The other times emails are sent to the outbox

**Comment by DivyaPatidar** [comment]
@asavage13  Even emails going to outbox is not related to Office JS APIs. Please raise a ticket with Outlook Mac via "Contact Support" within Outlook for Mac - https://support.microsoft.com/en-us/office/contact-support-within-outlook-for-mac-d0410177-8e65-4487-93f7-206a3a3d71a8 .
