### ISSUE TITLE
 RichApi.Error: GeneralException occurs when updating styles in HTML tables

### ISSUE THREAD

**Issue by hnyrxs2** [OfficeDev/office-js#4718]
related to issue https://github.com/OfficeDev/office-js/issues/4463
just want to verify if the upcoming fixes this august would include the fixes for the html tables where style is being set. below is the gist used

```
$("#run").on("click", () => tryCatch(run));

async function run() {
  await Word.run(async (context) => {

    const defaultStyle: Word.Interfaces.TableUpdateData = {
      styleBuiltIn: 'TableGrid',
      font: {
        size: 11
      }
    };

    const testData = [
      ["Name", "Age", "Occupation"],
      ["Alice", "30", "Engineer"],
      ["Bob", "24", "Designer"],
      ["Charlie", "28", "Teacher"]
    ];

    const ccContainer = context.document.getSelection().insertContentControl();
    const table = document.createElement('table');
    const tableBody = document.createElement('tbody');
    testData.forEach(function (rowData) {
      const row = document.createElement('tr');
      rowData.forEach(function (cellData) {
        const cell = document.createElement('td');
        cell.appendChild(document.createTextNode(cellData));
        row.appendChild(cell);
      });
      tableBody.appendChild(row);
    });
    table.appendChild(tableBody);
    const htmlTable = ccContainer.insertHtml(table.outerHTML, Word.InsertLocation.start);
    htmlTable.set(defaultStyle);
    await context.sync();
  });
}

async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    console.error(error);
  }
}


```

## Your Environment
* Platform: PC desktop and Office on the web
* Host: Word
* Office version number: Version 2405 (Build 17628.20188 Click-to-run)
* Operating System: Windows 11
* Browser (if using Office on the web): Microsoft edge
 
## Expected behavior
Upon rendering the HTML table, table style should be applied.

## Current behavior
Plain HTML style is applied, no table style is visible. General Exception is logged on the console

## Steps to reproduce
1. Use the gist above on scriptlab
2. run code
3. error is encountered, expected style is not seen.

## Context
This code gist is used to an add-in that enable users to create large tables of reports and should be customizable to their preferences.

## Useful logs
console error on the scriptlab
```
[ERROR]: Error:
{
    "stack": "RichApi.Error: The argument you provided is not valid. Check the OfficeExtension.Error.debugInfo for more information.\n    at new n (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:340405)\n    at o.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:404852)\n    at https://appsforoffice.microsoft.com/lib/1/hosted/word-web-16.00.js:25:402915",
    "message": "The argument you provided is not valid. Check the OfficeExtension.Error.debugInfo for more information.",
    "name": "RichApi.Error",
    "code": "InvalidArgument",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "InvalidArgument",
        "message": "The argument you provided is not valid. Check the OfficeExtension.Error.debugInfo for more information.",
        "errorLocation": "Range.styleBuiltIn",
        "statement": "insertHtml.styleBuiltIn = ...;",
        "surroundingStatements": [
            "...",
            "// Instantiate {selection}",
            "var insertContentControl = selection.insertContentControl();",
            "// Instantiate {insertContentControl}",
            "var insertHtml = insertContentControl.insertHtml(...);",
            "// Instantiate {insertHtml}",
            "// >>>>>",
            "insertHtml.styleBuiltIn = ...;",
            "// <<<<<",
            "var font = insertHtml.font;",
            "// Instantiate {font}",
            "font.size = ...;"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 400
}
```

**Comment by jipyua** [comment]
hi @hnyrxs2 this is a different issue with case #4463. If you add a sentence htmlTable.select() before htmlTable.set(defaultStyle); you will notice that there is a separate empty paragraph before the table. So apply "TableGrid" style to such as range is not correct, since this style can only apply to a whole table. As why there is an empty paragraph before the table, this is a behavior defined by Word itself which you can try by adding an empty content control and insert a table into it from UI. 

In order to work around this, I think you can try to get the table inside the content control by ccContainer.tables.getFirst().set(defaultStyle);

**Comment by hnyrxs2** [comment]
Hello @jipyua thanks for the input. your workaround works for the gist i provided but we shall investigate further to the actual implementation on our add-in. But our implementation before works perfectly, is there any changes in the word behavior that caused this?

**Comment by hnyrxs2** [comment]
Hello again @jipyua your work around works but it compromises the performance of the  add in as well as the whole MS word itself. It its taking minutes if i were to insert the table that would be 2 more pages, then the word crashes.

**Comment by jipyua** [comment]
hi @hnyrxs2, thanks for trying the solution. From the above root cause analysis of your original issue, I don't think we have made changes of the behavior. Is it that you are trying to apply other non-table style to the range in the past? That way it will be always working.

About the new crash issue you mentioned, would you please share more information, such as your table code so that I can try to repro at my side and investigate what's happening?

**Comment by 4tti** [comment]
Hello @jipyua, there was definitely behavior change. Before - like 3-4 months ago - our solution worked just fine, then we noticed that there was exactly same error as here in #4463 and that's why @hnyrxs2 raised it there and because there was not answer this thread was created.

Thanks a lot for your help!

You can test it yourself I guess with some old build, let' say half year ago or so.
Edit: let us find time when it was working fine...
Edit2: It was workin fine (based on our test cases) in May

**Comment by jipyua** [comment]
hi @4tti @hnyrxs2, thanks for providing further information, I tried the above code on a older build 16.0.17328.20514, but I still hit the same error. Could you please also have a try and explain more what's the behavior change you saw? Thanks.

**Comment by hnyrxs2** [comment]
hello @jipyua the only behavioral change we saw was the GeneralException thrown when updating html table style. Our original implementation of this was almost 2 years ago, and just recently around May when we are doing regression testing we noticed the failing functions with html table implementations without any changes made from these past months / year.

**Comment by jipyua** [comment]
hi @hnyrxs2 , we will open an internal item to investigate this and see what's happening. At the same time, I suggest you use the work around to unblock you. Since there is only 1 table in the content contorl, the perf should be ok, if you see other unexpected cases, please let us know.

**Comment by 4tti** [comment]
@jipyua  The performance is not ok. The performance went significantly down:

> but it compromises the performance of the add in as well as the whole MS word itself. It its **taking minutes if i were to insert the table that would be 2 more pages, then the word crashes.**

**Comment by 4tti** [comment]
Any update please? @jipyua 
Do you need something from us?

**Comment by jipyua** [comment]
hi @4tti we have created an internal item to track this issue and if we have some investigation findings, we will share to you. thanks.

**Comment by 4tti** [comment]
Thanks a lot @jipyua , once you have any update please let us know.

**Comment by 4tti** [comment]
@jipyua  any update please?

**Comment by jipyua** [comment]
hi @4tti sorry that this is a hard to track problem and we are still trying to figure out why the issue happens. Thanks for your patience and we will need some mroe time to investigate the root cause.

**Comment by 4tti** [comment]
Any update?

**Comment by jipyua** [comment]
hi @4tti We have fixed this bug internally and now it's under the validation and rollout process. The fix should be available at next M365 Office update which is around early December, please have a try at that time and let us know for any other feedbacks.. And also feel free to close this ticket. Thanks.

**Comment by 4tti** [comment]
We will check, thanks a lot!

**Comment by hnyrxs2** [comment]
Hello, please reopen this since same error encountered on Word Online using the same code snippet above.  Word desktop works fine. @jipyua @shanshanzheng-dev 

<img width="1911" height="955" alt="Image" src="https://github.com/user-attachments/assets/6924057f-f67e-4c72-a020-622e44a70748" />
