### ISSUE TITLE
when change ribbon button image. image still old

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#472]
hi

the ribbon button image is "ImageA.png", i change the image ,but the image name is still "ImageA.png". excel ribbon button image is still display old image. if i change the name of "ImageB.png" ,it's ok.

i think the excel is cache the image. how can i clear it.

thanks

**Comment by Rick-Kirkham** [comment]
To delete the cache, see these instructions: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#clear-the-office-cache

**Comment by dinglicoding** [comment]
my computer is windows 10,and excel is microsoft office home and student 2016 version 1903 (build 11425.20204 microsoft Store)

the folder %LOCALAPPDATA%\Microsoft have .but can not find office in this folder.

**Comment by Rick-Kirkham** [comment]
Hmmm. Try searching %LOCALAPPDATA%\Microsoft for "WEF".
