### ISSUE TITLE
How to deploy Excel Javascript Add-in with a custom function added parameters

### ISSUE THREAD

**Issue by shaun-pendrigh** [OfficeDev/office-js#4722]
I have a JavaScript Excel Add-in deployed in production, being used by a number of customers. The Add-in includes a custom function. I have added new optional parameters to the function but when I deploy this version Excel does not recognize the updated function.

What is the correct process to deploy this kind of change? It is a feature update that does not require a change to the manifest but I am not sure how to get Excel to recognize the updated function.

Clearing the Add-in cache or re-installing the Add-in will resolve the issue but I cannot expect my customers to do that.

**Comment by XuanZhouMSFT** [comment]
@shaun-pendrigh Thanks for the waiting. For caching things, we have an expiration time of 24 hours. After 24 hours we make a request and do respect the Cache headers and update the new JSON metadata.
So if you update your CF's metadata and can't wait the 24 hours to expire the cache, we'd like to suggest you update the manifest version also, it will also trigger a update for add-in all related resources.

**Comment by shaun-pendrigh** [comment]
@XuanZhouMSFT Thanks for the information
