### ISSUE TITLE
how to set Superscript/subscript/strike on specific text in cell in word using office js.

### ISSUE THREAD

**Issue by Jayshiv-IRIS** [OfficeDev/office-js#4723]
Based on my object I have inserting text in word table cell and applying content control After that in Some cell I want to set Superscript/subscript/strike on some specific characters in cell(not whole text). Example 21st Jan 2022 in that I inserted whole text in cell but I want to set 'st' as superscript using office-js. This Superscript/subscript/strike occurrence can be multiple in one cell. I have start-Index and End-Index for Superscript/subscript/strike character in my object.

Here is my code snippet After inserting text I want to give style Superscript/subscript/strike
```
async function UpdateValueInTableNew(selectedTbl, currentTblObject) {
    try {
        await Word.run(async function (context) {
            console.time("UpdateValueInTableNew");
            const docCC = context.document.contentControls;
            docCC.load("items");
            await context.sync();
            var findTbl = docCC.items.filter(a => a.tag == selectedTbl);//Content controlID of my table
            var table = findTbl[0].parentTable;
            context.load(table, 'rows/items/rowIndex,rowCount,rows/items/cells/items/body/font/superscript,rows/items/cells/items/body/contentControls/items/tag,rows/items/cells/items/body/contentControls/items/text,rows/items/cells/items/value,rows/items/cells/items/cellIndex,rows/items/cells/items/value,rows/items/cells/items/body/font');
            var ctrlTime
            await context.sync();
            var rows = table.rows;
            console.log(table);
            for (let ii = 0; ii < rows.items.length; ii++) {
                let row = rows.items[ii];
                for (let jj = 0; jj < (row.cells.items.length); jj++) {
                    let cell = row.cells.items[jj];
                    let cc = cell.body.contentControls.items;
                    let cellIndex = cell.cellIndex;
                    let rowIndex = row.rowIndex;
                    let data = null;
                    data = currentTblObject[ii][jj];
                    let ctrlList = cell.body.contentControls;
                    var ctrl;
                    for (let x = 0; x < ctrlList.length; x++) {
                        if (ctrlList[x].tag == data.Fact) {
                            ctrl = ctrlList[x];
                            break;
                        }
                    }

                    let cellBody = cell.body;
                    if (data) {
                            if (data.CellDisplayValue != "")
                            {
                                cellBody.insertText(data.CellDisplayValue.trim(), "Replace");
                                ctrl = cellBody.insertContentControl();
                                ctrl.tag = data.Fact;
                            }
                            else {
                                cellBody.clear();
                            }
                            
                        }
                    }                   
                }
            }
            await context.sync();
            return true;
        });
    }
    catch (ex) {       
       
        return false;

    }
}

```
here is my data object which look like this

```
string CellDisplayValue;
string Fact; //Content control ID
 List<Tuple<string,int,int>> Effects
```

in tuple first string type has "Sup","Sub","Strike" other 2 has start-Index and end Index

**Comment by shanshanzheng-dev** [comment]
Hi @Jayshiv1408Dev Thanks for reaching us. Could you please give us more detail info for your scenario about what you want to do or your issue? such as you want to use office API JS to set character 'st' as superscript/subscript/strike? May I know you want to implement on Word Online or Word desktop? Thanks.

**Comment by Jayshiv-IRIS** [comment]
Hi @shanshanzheng-dev, Thanks for your quick response.
Sorry for inconvenience I forget to add details.

My Environment
Platform : PC desktop
Host: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2404 Build 16.0.17531.20140) 64-bit
Operating System: Microsoft Windows 11 pro

 I'm taking value from excel and putting that into my word table.
In that some cell has superscript or subscript on some character so I want to give that style to particular character only.


```
word table cell has this text **21st Jan 2022**
supText="st"; 
 const searchResults = cell.body.search(supText, { ignoreSpace: true });
 context.load(searchResults);
 await context.sync();
 searchResults.items[0].font.superscript = true;
```

It's working fine until this kind of value is come
<img width="612" alt="image" src="https://github.com/user-attachments/assets/eb13fdaa-605d-43eb-bcf2-b03a9c4bdb91">

As given Image you can see 21st and 22nd January.
For this text when I used Below code Its giving me this kind of output.
I know I used 0 index that's why its happening.
Is there way I can Search text based on index Or I can get range base on start-index and length/endIndex
<img width="697" alt="image" src="https://github.com/user-attachments/assets/899c4ac4-8d52-4129-945b-a66c0893b120">

**Comment by Jayshiv-IRIS** [comment]
Hi @shanshanzheng-dev .
Is this okay or I am missing something.
If you need some other detail for this please let me know .
I'm stuck due to this can you please help.
Thanks.

**Comment by jipyua** [comment]
hi @Jayshiv1408Dev thanks for reaching out. After inspecting the questions mentioned above, I am afraid so far there is no existing API to get range based on start-index and length/endIndex. This will be a new feature ask, we track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum]( https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. Thanks,

**Comment by Jayshiv-IRIS** [comment]
@jipyua  Thanks,
 Is there other way I can achieve this.

**Comment by jipyua** [comment]
hi @Jayshiv1408Dev I am afraid so far there is no directly available APIs for your request, there is a split API here https://learn.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview#word-word-range-split-member(1) for spliting ranges, but please validate whether you can find suitable delimiters for your purposes. Thanks.

**Comment by Jayshiv-IRIS** [comment]
Thanks @jipyua  and @shanshanzheng-dev  for your help.
I'll check this api.

**Comment by jipyua** [comment]
hi @Jayshiv1408Dev, we'd like to understand more of your scenario about the missing JS API. Would ou please help fill out this form with your contact information as a means for us to further discuss. Thanks.
https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR9NvrlmrippKsMvh4kTM325URVZMWjYyQTVOTVNLTUo5VzFRTTcyNU1RSy4u
