### ISSUE TITLE
Add-ins continue to work after uninstallation

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#4724]
We are writing to report an issue with an Office add-in that utilizes ItemSend events. 
This add-in runs the ItemSend event and pops up every time an email is sent.
We have installed and then uninstalled this add-in, but the ItemSend event continues to run.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows
* Browser (if using Office on the web): Outlook on the web(edge)
 
## Expected behavior
Once the add-in is deleted, it will be removed from the add-in list screen and the ItemSend event should no longer work

## Current behavior
I have uninstalled the add-in but it continues to work.
The screen I checked from [https://aka.ms/olksideload] does not show any add-ins in either [Personal Add-ins] or [Administrator Managed]. (The name of the add-in is Mail Checker.)
![addinImage](https://github.com/user-attachments/assets/98a0d81b-8549-433c-b8c6-eb48753572ed)

However, when I checked the add-in list from the □ Add-ins button > [Add App], it was displayed.
![addinImage2](https://github.com/user-attachments/assets/91a66f33-2258-4483-8d1a-b7fa57415228)

I will share what I have tried regarding this issue.
1) Launch OWA in the incognito browser
2) Try on another PC terminal
3) Clear the cache
I have tried all of these and the add-ins are working even though they should have been deleted.

# Additional Information
This add-in is deployed for a specific user or group from the “Integrated Apps” in the Administration Center.
The deployment method is set to [Optional].

How do I completely remove an add-in?

**Comment by ajays-msft** [comment]
@mailchecktool-admin - It takes upto 24 hours for changes to be reflected when managing apps from admin center.
https://learn.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-faq?view=o365-worldwide&source=recommendations#how-long-does-it-take-for-add-ins-to-get-removed-for-all-users-----

**Comment by 1TheMuffinMan** [comment]
> @mailchecktool-admin - It takes upto 24 hours for changes to be reflected when managing apps from admin center. https://learn.microsoft.com/en-us/microsoft-365/admin/manage/centralized-deployment-faq?view=o365-worldwide&source=recommendations#how-long-does-it-take-for-add-ins-to-get-removed-for-all-users-----

That seems kind of crazy don't you think? A user can go to the store and install an add-in and it shows up immediately, but doing it through admin center takes hours? Do you guys have someone manually updating configurations by hand?

**Comment by mailchecktool-admin** [comment]
@ajays-msft @1TheMuffinMan 
It has been over a month since this user uninstalled.
I find it odd that it hasn't been updated.
Do you know how to completely remove the add-in?

**Comment by DivyaPatidar** [comment]
@mailchecktool-admin Do you see this addin deployed for particular user in admin centre? Can you try to redeploy for this user and remove it ?

**Comment by mailchecktool-admin** [comment]
@DivyaPatidar 
Yes. We have confirmed that it is deployed to the user.
I will try it!
