### ISSUE TITLE
Sideloaded Outlook Addin doesn't respond in desktop, works fine in browser

### ISSUE THREAD

**Issue by MatthewGlancy** [OfficeDev/office-js#4727]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC - Windows 10 / Office on Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook 1.2024.717.400 (Production)
* Operating System: Windows
* Browser (if using Office on the web): Chrome (where relevant)
 
## Expected behavior

After sideloading an app using `npm start` (from the yeoman generator).
When clicking on my addin in the 'Apps' menu when reading a message, I expect to see my actions being displayed and the option to click one.

![image](https://github.com/user-attachments/assets/d7fb5d20-96ff-4f78-a9f1-22807fa73ec4)

I have two actions registered, open a taskpane and perform an action.

## Current behavior

In Chrome on Office on the Web, my addin appears and when I click it, I can see my options are present:

![image](https://github.com/user-attachments/assets/de8e010d-8619-4fd4-9f45-16bb5219b5eb)

I can click either of these options and they both work perfectly well (in the browser).

However, in the Outlook Windows client, clicking 'Contoso Test' doesn't respond. The app tray disappears but I'm not presented with the options like I am in the browser. This basically renders the add-in useless as I can't actually perform any of the actions.

## Steps to reproduce

1. Run the yeoman generator `yo office`
Choose: Office Addin Task Pane Project
Choose: Javascript
Choose: Outlook
Choose: XML Manifest
2. `npm install`
3. `npm start`
4. Within Outlook for Windows, view a message and click into the Apps tray
5. Within the Apps tray, click the new plugin. For me here, I do not get any options.
6. Within Chrome, doing steps 4 and 5 results in my options being displayed and I am able to click them

## Link to live example(s)

This isn't a live add-in - I'm simply trying to sideload at the minute, but here is the [manifest.xml](https://gist.github.com/MatthewGlancy/4c2616d33bd544d6c166523f1f1fa731) that isn't working (although I have tried with 2 or 3 different manifests and none of them are working for me)

# Provide additional details

I haven't changed any of the code within the sample project that the yeoman generator has provided

## Context

I'm trying to test my addin in different environments before a proper release. I normally develop on a Mac, and the sideloading there (while forced to be manual) has been working perfectly well - however sideloading in Windows seems to be a problem and I don't want the final product to be broken for Windows users upon release.

I have an addin with features that is working fine on Mac and in the web, however coming to the Outlook for Windows client, the addin is not working as I would expect and so I've provided here just a minimum viable test scenario with the yeoman generator. Point being that I have tried a few different manifests and they seem to work in other environments, just not in Windows. The actual addin has email transformation functionality on send, and this part is not working either.

### Console errors
From `olk.exe --devtools` I see quite a few errors, but none of them seem to be related:

![image](https://github.com/user-attachments/assets/0b30c16d-e313-45b0-a419-713fccd2da96)

I get no new logs upon clicking the addin button either.

**Comment by MatthewGlancy** [comment]
Hey - any chance of an update on this one? We'd like to get our new Outlook plugin out soon as we can really. Thanks.

**Comment by sivachandran-msft** [comment]
Hi @MatthewGlancy , sorry for the delay in the response. We could understand that you are able to sideload your adding in Outlook web & Mac environment and facing issue in Windows. Are you using Classic outlook or New Outlook for testing this scenario? In case of new outlook, please follow the procedure in this [link ](https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues) & share the logs.

**Comment by MatthewGlancy** [comment]
Hey, thanks for the reply.

I've gotten round to testing back in Windows - this was all on new Outlook

Everything seems to be working fine again for me - I note the Outlook version has updated on my machine to 1.2024.807.101 (Production)
