### ISSUE TITLE
Outlook New Windows UI - issue with Office.context.mailbox.item.getItemIdAsync function

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#4728]
# Provide required information needed to triage your issue
When calling ```Office.context.mailbox.item.getItemIdAsync``` in the new Windows Outlook UI, the first time (if done shortly after composing a new message I believe), returns a message id that is not what is expected (i.e. something like ```clientid:{{guid}}```.

When called a second time, it returns what we would expect to see (an actual message id without the "clientid" prefix).

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows 10/11
* Browser (if using Office on the web): ______
 
## Expected behavior
The real message id is always returned when ```Office.context.mailbox.item.getItemIdAsync``` is called. This should never change on subsequent calls for the same message.

## Current behavior
The message id is changing on subsequent calls to ```Office.context.mailbox.item.getItemIdAsync```.

## Steps to reproduce
1. Compose a new message and open the add-in
2. Call ```Office.context.mailbox.item.getItemIdAsync``` and note the message id returned (looks something like ```clientid:{{guid}}```
3. Close the add-in.
4. Open the add-in and call ```Office.context.mailbox.item.getItemIdAsync``` again and note the new message id that is returned (looks more like what we'd expect -- ex: ```AAMkAGRjNjgzMzFkLTk4NDAtNDNhNC1iN2IwLTRlZDlkOTc5MDA2OQBGAAAAAACBRef0LyuDT6qtuGLHHQMtBwBUwWi/zK7oTKigK60c9jLNAAAAAAEPAABUwWi/zK7oTKigK60c9jLNAAGVU4hQAAA=```)

## Context
This is a major issue as data for a message is typically stored in local storage and mapped to the message id. If this changes, it leads to major issues.

**Comment by DivyaPatidar** [comment]
@cody-lettau Can you try adding a call to [Office.context.mailbox.item.saveAsync](https://learn.microsoft.com/en-us/javascript/api/outlook/office.messagecompose?view=outlook-js-1.4&preserve-view=true#outlook-office-messagecompose-saveasync-member(1)) before calling getItemIdAsync API and see if it fixes the issue?

**Comment by cody-lettau** [comment]
@DivyaPatidar we actually do already. Here is the function we are calling:
```
export const saveItem = (includeId) => new Promise((resolve, reject) => {
    try {
        Office.context.mailbox.item.saveAsync((saveResult) => {
            if (saveResult.status !== Constants.getAsyncResultSuccessStatus()) {
                console.error('Error saving mailbox item: ', saveResult.error);
                reject(new Error('Error saving mailbox item'));
                return;
            }

            if (!includeId) {
                resolve(saveResult.value);
                return;
            }

            Office.context.mailbox.item.getItemIdAsync(getItemResult => {
                if (getItemResult.status !== Constants.getAsyncResultSuccessStatus()) {
                    console.error('Error getting id for saved mailbox item (during save): ', getItemResult.error);
                    reject(new Error('Error getting id for saved mailbox item'));
                    return;
                }

                resolve(getItemResult.value);
            });
        });
    } catch (e) {
        console.log('Error saving mailbox item: ', e);
        reject(e);
    }
});
```

We found that if we call this twice, with a slight delay between the calls, we end up getting back what is expected (delay we have set is 250ms).

**Comment by cody-lettau** [comment]
But yes, I do think it is somehow related to the item not being saved and available. If you save it to a draft and then follow the same steps (but with the draft instead of a new message), it returns the expected message id right away.

That said, we don't see this same issue anywhere except with the new Windows UI.

**Comment by DivyaPatidar** [comment]
@cody-lettau This is same as #4657. Please followup #4657 for updates.
