### ISSUE TITLE
Excel api call AutofitColumn before converting to table result in incorrect width on XLO

### ISSUE THREAD

**Issue by wcx11** [OfficeDev/office-js#473]
Seems that it's an API bug in XLO. When call table.add() to convert a range to a table after autofitcolumns(), the header row of the table will have a wrong width. It looks like that the down arrow in header row were not considered in auto fit. 
The XLO api performs differently from button click:[Format->auto fit column width]->[Ctrl T].(button click results in correct format, and win32 api performs correctly, too)
## Expected Behavior

![image](https://user-images.githubusercontent.com/5551082/56012927-1b030f00-5d21-11e9-8552-c42e712ba69a.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/5551082/56012919-14749780-5d21-11e9-8a36-9d7dc3689259.png)

## Steps to Reproduce, or Live Example

* Link to live example: the script I used to test in script lab: _https://gist.github.com/wcx11/e90522165283d32f01f7460bd6ec1667_____
it behaves differently in xlo and win32.

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

It affects Excel Ideas' sample data insertion. We expected user experience as great as possible.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: __Office Online____
* Host [Excel, Word, PowerPoint, etc.]: __Excel____
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): _Chrome, IE, Edge_____

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by dmahugh** [comment]
@lumine2008 can you take a look at this issue?

**Comment by kbrandl** [comment]
@wcx11 apologies for the lack of response on this issue; seems that it was overlooked until now. Are you still having this problem? @lumine2008 are you able to provide feedback on this issue?

**Comment by lumine2008** [comment]
Hello @wcx11 , would you please validate this issue again, i cannot repro this issue anymore, please let us know if you still repro the issue. thanks.

**Comment by MandytMSFT** [comment]
@wcx11  our team somehow is revisiting this thread. I tried your scenario, i notice moving  range.format.autofitColumns() after table.add can resolve your issue. Is this workaround acceptable for you ?

**Comment by lumine2008** [comment]
Please reactivate if you still repro this issue
