### ISSUE TITLE
Add-ins don't work in Excel Online and Mac

### ISSUE THREAD

**Issue by irynakaban** [OfficeDev/office-js#4733]
# Provide required information needed to triage your issue
All add-ins doesn't work in Excel. Receive or endless loading, or error. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac, Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Online: 16.0.17924.42302, Mac: 16.87 (24071426)
* Operating System: Mac OS, Windows
* Browser (if using Office on the web): Chrome, Vivaldi, Edge
 
## Expected behavior

Add-ins work correctly.

## Current behavior

Receive or endless loading, or error. 

## Steps to reproduce

1. Open add-in store from excel.
2. Install ScriptLab from add-ins store.

## Link to live example(s)

1. [Link to video on google drive](https://drive.google.com/file/d/1jqYUwvAL5deszXeRWdbb0dhIAiFfbHDk/view?usp=sharing)

**Comment by gmichaud** [comment]
Same here -- https://appsforoffice.microsoft.com/lib/1/hosted/office.js is not loading from Canada (but is apparently fine from Portugal, according to other team members)

Problem is affecting other Office apps as well.

**Comment by gmichaud** [comment]
I tested with a service that loads the page from multiple locations. Results can be seen here: https://semonto.com/tools/website-reachability-check?test=a60f4a2e6c573f1

<img width="1307" alt="Screenshot 2024-07-30 at 9 32 37 AM" src="https://github.com/user-attachments/assets/25a9218d-4a20-4811-9b44-ef3b4c216ef8">

**Comment by alexm-plutoflume** [comment]
We are also having reports of our Outlook ItemSend Add-in hanging when trying to reach office.js

MSFT has reported service issues with M365, likely related?

https://x.com/MSFT365Status/status/1818267438435147865

Issue ID MO842351 in the admin center

**Comment by wh1t3cAt1k** [comment]
The issue seems to have been resolved by now.

https://semonto.com/tools/website-reachability-check?test=2d7e174246175b34292aff94725551bc6a80

**Comment by atsopuronen** [comment]
Same here with our Outlook add-in, multiple reports from our customers.

**Comment by hdwatts** [comment]
Issue was resolved but is now occurring again.

**Comment by hdwatts** [comment]
Looks like the issue has resolved itself again.

@shanshanzheng-dev What steps can we take to mitigate this issue should the CDN go down again? Is it safe for us to self host the office.js file as a backup?

**Comment by shanshanzheng-dev** [comment]
Thanks for reporting this issue. Yes, looks like the issue has resolved again. We've connected with our partner team to consider on future for a fallback mechanism and we'll also keep monitoring if it occur again. Thanks.

**Comment by bchen-hs-eng** [comment]
@shanshanzheng-dev We'd like to follow up on the fallback mechanism effort. Is this something your and the partner team will handle internally so it is transparent to us, or do we need to manually configure the fallback when loading the evergreen OfficeJS script?

**Comment by shanshanzheng-dev** [comment]
Thanks @bchen-hs-eng. 
Hi @gergzk We think it makes sense if customer manually configure the fallback when loading the evergreen OfficeJS script. Not sure if you have some good insights about the fallback mechanism, seem office.js deployment/CDN is out of our control.

**Comment by gergzk** [comment]
Per https://semonto.com/tools/website-reachability-check?test=2d7e174246175b34292aff94725551bc6a80 this is fine now, so I'll close with comments. 

Developers should not bundle office.js with their add-in.

If in the future this is observed again, a network trace of attempting to get the office.js file would be most useful, as well as a session id (eg: File -> Info, copy/paste session id)
