### ISSUE TITLE
Office.js accessibility: Can't find variable Office

### ISSUE THREAD

**Issue by dmitriikashin-outreach** [OfficeDev/office-js#4734]
- We are seeing significant increase in "Can't find variable Office" errors in our telemetry within last few hours, with customers reporting Outlook Add-in issues. Does Office.js have any accessibility issues at this moment?

**Comment by atsopuronen** [comment]
Yes, please refer to: https://github.com/OfficeDev/office-js/issues/4733

**Comment by Oleg-O** [comment]
Has this been resolved or are you still seeing this in your telemetry?

**Comment by cut2run** [comment]
Location based, the CDN for [Office.js](https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js) in Canada down from the morning. We have a lot of reports from our customers. None of the add-ons work, including Microsoft Viva Insights, Teams, etc. All of them are using recommended [Referencing the Office JavaScript API library](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/referencing-the-javascript-api-for-office-library-from-its-cdn).

**Comment by dmitriikashin-outreach** [comment]
@Oleg-O we don't see the issue anymore. It got resolved at ~ 10 PM, CEST, Jul 30.
