### ISSUE TITLE
Wrong icon displayed in far-right bar with multiple add-in windows

### ISSUE THREAD

**Issue by jim22k** [OfficeDev/office-js#4741]
In Windows version of Excel, when multiple add-ins are opened, they each display as an icon in the far right side of the window (not sure what the name of that side bar is). This is super helpful to switch between add-in windows.

The issue is that the icon displayed is the ribbon group icon, not the ribbon button icon. If an add-in has several buttons, they all show the same icon, making it difficult to distinguish. They each have a unique tooltip, but hovering and waiting for the tooltip is slow and less effective than showing the icon that is displayed in the ribbon.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2407 (Build 17830.20016)
* Operating System: Windows 11
 
## Expected behavior

A taskpane add-in has a ribbon _**group icon**_
```
<OfficeTab id="...">
  <Group id="...">
    <Icon>
      <bt:Image ...>
```
A taskpane add-in also has a ribbon _**button icon**_
```
    <Control xsi:type="button", id="...">
      <Icon>
        <bt:Image ...>
```
When these are different, I expect the _**ribbon button icon**_ to be displayed in the far-right panel.

The reason is if an add-in has multiple buttons, each with their own icon (all under the same ribbon group),
the group icon does not distinguish between the windows.

## Current behavior

Add-ins use the ribbon group icon instead of the button icon in the far-right panel.

## Steps to reproduce
1. Install AnacondaToolbox from AppSource
2. Expect "Anaconda" group on the Formula tab with two buttons -- Toolbox, Code
3. Click Code
4. Click Toolbox
5. View that far-right panel has two Anaconda icons, not the button icons

As a further example,
1. Install Script Lab
2. Click Code
3. Click Run
4. View that far-right panel has two ScriptLab icons, not the Code or Run button icon

This behavior is not consistent with built-in ribbon buttons in Excel. For example, clicking View -> Navigation shows the Navigation icon, not the "Show" group icon.

**Comment by shanshanzheng-dev** [comment]
Hi @jim22k We'll be looking into this problem, thanks for reporting! Can't share timelines, but will report back here if  if we have a suggestion for you.

**Comment by shanshanzheng-dev** [comment]
Hi @jim22k You define the icon we show and where. So you should be able to update the add in icon in the manifest to match icon in the ribbon, both ribbon buttons are also defined in the manifest.
FYI @m-hellesen

**Comment by jim22k** [comment]
Both ribbon buttons have their own icon, and each opens an independent add-in panel.
Is it possible for both panels to have a sidebar icon matching their ribbon button icon?

It seems that the sidebar icon is always the ribbon _**group**_ icon, which means it can only match one of the ribbon _**button**_ icons.

**Comment by shanshanzheng-dev** [comment]
About one sidebar icon matching their ribbon button icon, we recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)
Thanks.

**Comment by jimbarrett33** [comment]
It would be great if this issue can be re-opened and worked on by the Office team. In an add-in with it's own ribbon item with multiple commands/task panes there is no way for the user to distinguish which task pane is associated with which ribbon item.

@jim22k there is an existing community item for this. Please upvote and ask your colleagues to upvote :). It only has 7 votes right now and doubtful the office team will look at it (unfortunately). https://techcommunity.microsoft.com/idea/microsoft365developerplatform/allow-taskpane-iconstitles-that-are-different-than-the-addin-icontitle/3194628#M738
