### ISSUE TITLE
Blob support on older Outlook versions

### ISSUE THREAD

**Issue by fedeisas** [OfficeDev/office-js#4742]
Using `Blob` broke my add-in functionality for 10% of our user base. They were all using older Outlook versions.

```js
new Blob(["my string"]).size
```

I'd like to know more about the JS capabilities of older Outlook Desktop runtimes. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.15225.20288
* Operating System: Windows 10
* Browser (if using Office on the web): –
 
## Expected behavior

When my add-in uses `Blob` on the task pane or the commands runtime, it fails.

## Current behavior

I see an alert on my MessageCompose screen with `NativeBlobModule is available`.

The task pane doesn't load at all, and the command runtime also seems to stop.

# Provide additional details

When I checked [caniuse](https://caniuse.com/?search=Blob) it seems like `Blob` is supported from IE10 and Edge126.

**Comment by JunielKatarn** [comment]
Blob support for classic Outlook was introduced and gradually phased in this year.

Older version won't be able to use Blob unless the involved add-ins are WebView-based.

**Comment by Oleg-O** [comment]
@fedeisas have you been able to implement a solution or workaround for the affected users on older clients that don't support this yet?

**Comment by fedeisas** [comment]
@Oleg-O yes, we measure string size without relying on `Blob`.
