### ISSUE TITLE
Classic Outlook for Windows Launch Events & SSO 5001 when using query parameters

### ISSUE THREAD

**Issue by alexm-plutoflume** [OfficeDev/office-js#4744]
# Provide required information needed to triage your issue

In order to use SSO in LaunchEvents for Classic Outlook on Windows you need to host a file indicating the javascript files that will be calling the access token endpoints as outlined here https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/use-sso-in-event-based-activation#list-allowed-add-ins-in-a-well-known-uri

I'm finding that this file expects not only the file resource to match, but also any query parameters as well passed in through the manifest in the JS runtime override URL.

In requirement set 1.14, the JS runtime url was exposed in `Office.context.urls.javascriptRuntimeUrl` allowing custom data to be passed in through the URL to the Classic Windows runtime (see https://learn.microsoft.com/en-us/javascript/api/office/office.urls?view=common-js). But requiring that the `.well-known/microsoft-officeaddins-allowed.json` urls require the query parameters match exactly as well seems a bit counterproductive. We may have different custom values in the manifests being passed in, that means we would need to list every possible query parameter value combo in our `microsoft-officeaddins-allowed.json` file. 

I was wondering if this was intended or a bug?

## Your Environment
Classic Outlook for Windows Version 2406 Build 17726.20160
 
## Expected behavior
I would expect the `.well-known/microsoft-officeaddins-allowed.json` file to only require us to list the path of the javascript files **without** any additional query parameters.

## Current behavior
The getAccessToken call fails with a 5001 error if the file paths listed in `.well-known/microsoft-officeaddins-allowed.json` don't match exactly what is in the manifest for the JS runtime url **including** query parameters.

## Steps to reproduce

Use a simple Add-in that activates a launch event for Classic Windows in Outlook.

Your manifest should have something like this for the js runtime override
```
<Runtimes>
    <!-- HTML file including reference to or inline JavaScript event handlers.
         This is used by Outlook on the web and Outlook on the new Mac UI. -->
      <Runtime resid="residUILessFunctionFileUrl">
        <!-- JavaScript file containing event handlers. This is used by Outlook on Windows. -->
        <Override type="javascript" resid="JSRuntime.Url"/>
      </Runtime>
</Runtimes>

...
<bt:Url id="JSRuntime.Url" DefaultValue="https://addin.contoso.com/training.js?key1=value1&key2=value2" ></bt:Url>
```

Then in your `https://addin.contoso.com/.well-known/microsoft-officeaddins-allowed.json` file notice that SSO will only succeed if you have `https://wwww.contoso.com/training.js?key1=value1&key2=value2` as allowed, not `https://wwww.contoso.com/training.js`

## Context
We use SSO in our launch events and also pass custom data through our manifest urls as query parameters. Requiring the `.well-known/microsoft-officeaddins-allowed.json` to list the javascript file path including any query parameters seems counterproductive, as there could be a large combination of different query params and values.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Oleg-O** [comment]
Thanks for reporting! Great news, this should be fixed already starting build 16.0.17911.30850.
