### ISSUE TITLE
To load the word add in extension without a clicking extension when we open a  document on initial load  in word application is not supporting  [word add in react office js]

### ISSUE THREAD

**Issue by sudarsan-k** [OfficeDev/office-js#4746]
## Post how-to questions about your code on Microsoft Q&A

We have several forums where you can ask the developer community questions about your code. Try one of the following forums to ask technical questions about:
- [Developing Office Add-ins for Word, Excel, PowerPoint, Outlook, Project, Visio, and OneNote](https://docs.microsoft.com/answers/topics/office-addins-dev.html)
- [Access programming in Office](https://docs.microsoft.com/answers/topics/office-access-dev.html)
- [Developing COM or VSTO Add-ins for Office](https://docs.microsoft.com/answers/topics/office-vsto-com-dev.html)
- [Office JavaScript API](https://docs.microsoft.com/answers/topics/office-js-dev.html)
- [SharePoint and OneDrive development](https://docs.microsoft.com/answers/topics/sharepoint-dev.html)
- [Deploying and publishing Office or SharePoint apps to AppSource](https://docs.microsoft.com/answers/topics/microsoft-365-apps-publishing-dev.html)

For additional information about JavaScript programming, see the [JavaScript at Microsoft](https://docs.microsoft.com/javascript/) community hub.

**Comment by RuizhiSunMS** [comment]
Hi @DivyaPatidar , sorry for the late response. Looks our monitoring did some bads.
Anyway, is this case still blocking you? If yes, would you please share more information about your case, code, repro steps, office version for example? These would be helpful for us to locate root cause.
