### ISSUE TITLE
Will spam addins be supported on mobile and mac Outlook?

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#4747]
Hello Microsoft team,

I hope all is well with the team.
I just wanted to ask, since there is no mention of it in the docs, if mobile Outlook and mac Outlook will support spam addins as well? 

For mobile, is it already supported by following the event-based addins documentation for mobile?

Thank you and my apologies for these questions.

**Comment by AlexJerabek** [comment]
Hi @glr0221,

Let me tag @samantharamon to confirm, but I believe there is currently no timeline for supporting spam-reporting add-ins on mobile. The feature is currently in [preview on Mac](https://learn.microsoft.com/office/dev/add-ins/outlook/spam-reporting#preview-the-integrated-spam-reporting-feature-in-outlook-on-mac) and will be released when quality and usage bars are met.

**Comment by glr0221** [comment]
Thank you for your responses @AlexJerabek . 

While waiting for the confirmation whether it will be supported on mobile or not, I would like to ask more clarification on 'when quality and usage bars are met'. Does this mean that if they are not met, then it will never be released on Mac? Or it will still be released but at a later date even if the criteria are not met? I guess all I am hoping for is a timeline for this. 

Thank you and my apologies for a bit aggressive on the questions. We are really hoping that the spam addin works on all platforms. Thank you again.

**Comment by AlexJerabek** [comment]
Hi @glr0221,

I've asked the feature PM, @isabela-dominguez to share any available timeline and work with you to better understand your needs.

In general, if there is no public timeline, then the possibility does exist of something not being released. I realize this vague answer is not great and makes it hard to navigate business decisions.

**Comment by isabela-dominguez** [comment]
Hi @glr0221 thank you for your question. 

We are working on both mobile support for spam reporting and for enabling it in Mac further than preview. We unfortunately, don't have any public timelines to share right now. However, our priority is to enable spam reporting on all platforms, so we are aiming to have mobile and general availability Mac support "as soon as possible". We'll share with you all a timeline once available.

**Comment by glr0221** [comment]
Thank you for all your answers @isabela-dominguez @AlexJerabek. Thank you very much for understanding my sentiments and taking time to answer.
