### ISSUE TITLE
popup_window_error: Error opening popup window. This can happen if you are using IE or if popups are blocked in the browser.

### ISSUE THREAD

**Issue by gwsampso** [OfficeDev/office-js#4748]
## Your Environment
* Platform [PC desktop]
* Host [Excel]
* Operating System: Windows
* Browser: EDGE
 
We are developing an React Excel Web Add-in that uses SSO - specifcally  "@azure/msal-browser": "^3.20.0" and "@azure/msal-react": "^2.0.22",

It is a task pane that signs the user in to aquire a token to send to an API in other functions.

It works perfectly on most machines, the task pane loads, user clicks a button "sign in", a standard microsoft window pops up within excel and they follow the steps and a token for the backend is aquired.

Some people can use and develop the app

Other can't and get an error with the loginPopupin. 

Edge is the default browser for all users

Popups enabled

**Excel throws this error** 

_

> "Error during sign in: popup_window_error: Error opening popup window. This can happen if you are using IE or if popups are blocked in the browser."

_

**And an additional microsoft store alert pops up**

> **Get an app to open this 'about' link** 
Your PC doesn't have an app that can open this link. Try lloking for a compatible app in the Microsoft Store
Browse Microsoft Store

This is the working code but I dont think the issue is here rather in the excel setup of the individual machines

```
const signIn = async () => {
    try {
      const response = await msalInstance.loginPopup(loginRequest);
      setAccount(response.account);
      
      // Acquire token silently for the backend API
      const tokenResponse = await msalInstance.acquireTokenSilent({
        ...backendRequest,
        account: response.account
      });
      
      const accessToken = tokenResponse.accessToken;
      // You might want to save this token to use it later
      localStorage.setItem("accessToken", accessToken);
    } catch (error) {
      setError("Error during sign in: " + error.message);
    }
  };
```

![image](https://github.com/user-attachments/assets/a4a9408a-e4da-4e62-be89-23b4048b44d8)

 
Any suggestions please

Thanks

**Comment by shanshanzheng-dev** [comment]
@gwsampso Thanks for reporting this issue, could you share us your add-in manifest and repro steps? Thanks
