### ISSUE TITLE
makeEwsRequestAsync deprecation - Graph alternative for moving messages between mailboxes.

### ISSUE THREAD

**Issue by ovdixon** [OfficeDev/office-js#4749]
With Legacy Exchange tokens to be deprecated in October 2024, is there any Graph solution for moving a message between shared mailboxes?

 As I understand it, Graph `move` and `copy` operations are scoped to the users mailbox. Currently this is possible with `makeEwsRequestAsync` using the `CopyItem` method. I would consider this an essential Graph requirement, and the deprecation of such EWS methods would break a large suite of our Outlook add-ins.

**Comment by DivyaPatidar** [comment]
This forum is limited to supporting office-js apis. For any MS API Graph specific queries and support, please explore options available at [Microsoft Graph Dev Center | APIs and app development](https://developer.microsoft.com/en-us/graph)

**Comment by ovdixon** [comment]
Hi @DivyaPatidar ,

I have submitted a feature request in the Graph Dev Center. However, given the current backlog of issues, I cannot foresee that this could be implemented before October. Could you suggest any alternative solutions within the scope of `Office-js` ? Additionally, could you provide more information on how "admins opt into continued legacy token issuance" to prevent this deprecation from disrupting our entire suite of Office add-ins?
