### ISSUE TITLE
iPad cross site tracking issue

### ISSUE THREAD

**Issue by jordandev** [OfficeDev/office-js#475]
We have an add-in we are testing that uses OAuth to login from the add-in to our backend web services. This seems to fail in the Excel for iPad application because the embedded browser panel has a cookie policy that prevents cross site tracking on by default. This cookie policy would have to be changed on the WKWebView. I'm not sure where else to report this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 589820d2-9925-dc5e-76a7-83921a569137
* Version Independent ID: ab8bde36-096f-81f3-f4d1-9b25fc69e6ee
* Content: [Sideload Office Add-ins on iPad and Mac for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac#feedback)
* Content Source: [docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-an-office-add-in-on-ipad-and-mac.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by niteshgolchha85** [comment]
Closing this issue for now as this is expected behavior and there is a mitigation
