### ISSUE TITLE
Excel 2021 (retail perpetual license) does not support FNVs and range.valuesAsJson even though API level is declared as supported

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#4750]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Excel 2021 Retail Perpetual License (latest available version)
* Operating System: Windows 11
 
## Steps to reproduce

- Use 2021 Pro Plus Perpetual retail Excel version, latest version
- Use Script Lab
- Open the "Data types: Formatted numbers" snippet and run the following actions sequentially:

* Add worksheet
* Set formatted date (an error will be thrown)
* Log data types (an error will be thrown)

First error:

```
[ERROR]: Error:
{
    "stack": "RichApi.Error: There was an internal error while processing the request.\n at new n (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:265603)\n at o.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:330050)\n at https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:25:328113",
    "message": "There was an internal error while processing the request.",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "There was an internal error while processing the request.",
        "errorLocation": "Range.valuesAsJson",
        "statement": "range.valuesAsJson = ...;",
        "surroundingStatements": [
            "var workbook = context.workbook;",
            "var worksheets = workbook.worksheets;",
            "var itemOrNullObject = worksheets.getItemOrNullObject(...);",
            "var range = itemOrNullObject.getRange(...);",
            "// Instantiate {range}",
            "// >>>>>",
            "range.valuesAsJson = ...;",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "httpStatusCode": 500
}
```

Second error:

```
[ERROR]: TypeError: Cannot read properties of null (reading '0')
```

## Expected result

According to documentation: https://learn.microsoft.com/en-us/javascript/api/requirement-sets/excel/excel-api-requirement-sets?view=common-js-preview

<img width="1724" alt="image" src="https://github.com/user-attachments/assets/999047ec-6aa0-449d-b469-9cd4076e27b8">

The requirement set for `valuesAsJson` and formatted number values (returning data types with date formatting) should be supported in the latest version of retail perpetual license.

Moreover, when querying `Office.context.requirements.isSetSupported` we receive the following misleading results:

<img width="501" alt="image" src="https://github.com/user-attachments/assets/6c7334dc-2d71-42f6-8daf-49284fdbe172">

when in fact the desired functionality is not supported!

## Context

Some of our customers are on perpetual retail licenses and Velixo is not working properly for them due to utilisation of the requirement up to 1.16 inclusive.

@strangecamelcaselogin – please confirm the version of Excel 2021 that you tested this on.

## References

[Velixo internal tracking item](https://3.basecamp.com/3496385/buckets/16689259/card_tables/cards/7672061986)

**Comment by shanshanzheng-dev** [comment]
Hi @wh1t3cAt1k Thanks for reporting this issue. Could you provide your Excel version screenshot, because I try to run Data types: Formatted numbers code from my side, it works fine. This is my Excel version:
![image](https://github.com/user-attachments/assets/3cde8413-0c4a-41c0-8140-4b6f4fa4dbe5)

**Comment by strangecamelcaselogin** [comment]
@shanshanzheng-dev this is the version in which we experienced the issue:

<img width="541" alt="Screenshot 2024-08-02 at 09 51 18" src="https://github.com/user-attachments/assets/552a6833-f03e-4330-aa9b-abae70edba55">

And to add more details:

<img width="484" alt="Screenshot 2024-08-02 at 09 55 33" src="https://github.com/user-attachments/assets/321fc503-c815-47fc-9be2-763207601b02">

<img width="547" alt="Screenshot 2024-08-02 at 09 54 21" src="https://github.com/user-attachments/assets/c11d503d-6f6c-4dee-9e2a-f1362469da84">

It was installed a few days ago using this link (http://officecdn.microsoft.com/db/492350f6-3a01-4f97-b9c0-c7c6ddf67d60/media/en-US/ProPlus2021Retail.img) and updated using the built-in action.

**Comment by XuanZhouMSFT** [comment]
@wh1t3cAt1k @strangecamelcaselogin Thanks for the waiting. 
The API for valuesAsJson is not supported in retail perpetual license. Sorry about the document misleading you. We will have a follow up action to modify the document.
To give you a workaround to bypass the checking. We'd like to suggest you also use the CF1.4 requirement set to do the checking: https://learn.microsoft.com/en-us/javascript/api/requirement-sets/excel/custom-functions-requirement-sets?view=common-js-preview

**Comment by wh1t3cAt1k** [comment]
Thank you @XuanZhouMSFT. Please feel free to move this issue to the documentation project to be actioned there.
