### ISSUE TITLE
body.clear() not working for content controls

### ISSUE THREAD

**Issue by didu9898** [OfficeDev/office-js#4754]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): Chrome
 
## Expected behavior
body.clear() must work for content control.

## Current behavior
body.clear() is not clearing the document. This works in word desktop.

## Steps to reproduce

1. Add a control and add text inside
2. Run the following code in script lab

```
$("#run").on("click", () => tryCatch(run));
async function run() {
  await Word.run(async (context) => {
    context.document.body.clear();

    await context.sync();

    console.log('Body cleared');
  });
}

async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}
```

## Link to live example(s)
https://github.com/user-attachments/assets/a1ae9f01-b5c7-4ef6-a4e2-5ba6a116f1ac

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by shanshanzheng-dev** [comment]
Hi @didu9898 Thanks for reporting this issue. But I can't repro it from my side, may I know how do you insert content control ? 
I run "Content control basic" in the samples to insert a content control and can use body.clear()

https://github.com/user-attachments/assets/45301d2a-86c9-41f0-8c19-e166281aef0d
