### ISSUE TITLE
 Identifying Usage of New Outlook in Office-js Add-ins

### ISSUE THREAD

**Issue by manaunl** [OfficeDev/office-js#4756]
I am developing an Office-js add-in for Outlook and I need to implement some functionality that differs based on whether the user is using the new Outlook experience or the one in the browser.

Is there any way within the Office-js API to programmatically identify if the user is using the new Outlook? Any specific methods, properties, or workarounds would be greatly appreciated.

Thank you for your assistance!

**Comment by dahuja10** [comment]
Hi @manaunl, you can refer to following documentation for this - https://learn.microsoft.com/en-us/javascript/api/outlook/office.diagnostics?view=outlook-js-preview

Let us know if you need more help with this.
