### ISSUE TITLE
Not able to sideload outlook addin.  in macbook there is no option to add the manifest file

### ISSUE THREAD

**Issue by veris-kamaraj** [OfficeDev/office-js#4757]
outlook mac : 
Version 16.87.2 (24072822)

get add in button is navigating to https://appsource.microsoft.com/en-us/marketplace/apps?product=office%3Boutlook&page=1&src=office&corrid=ce7a9dd8-4f6f-55b4-1560-1526ba3661c6&omexanonuid=&referralurl=&ClientSessionId=eadd52a2-a4c3-42c2-b471-865ede8423df.   

There is no option to add manifest file
<img width="1680" alt="Screenshot 2024-08-06 at 3 58 06 PM" src="https://github.com/user-attachments/assets/7d76402f-31d4-4288-bad8-4bfc9377abad">
<img width="1680" alt="Screenshot 2024-08-06 at 4 00 03 PM" src="https://github.com/user-attachments/assets/9681f988-df0a-4873-9e5f-a6d707d5c0e2">

**Comment by dahuja10** [comment]
Hi, @veris-kamaraj - please refer this doc for sideloading the addin - https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing

**Comment by dahuja10** [comment]
Also, as mentioned in the doc - In Outlook on Mac, starting in Version 16.85 (24051214), the Get Add-ins button no longer opens the Add-Ins for Outlook dialog. Instead, it opens [AppSource](https://appsource.microsoft.com/marketplace/apps?product=office%3Boutlook&page=1&src=office) in your default browser.

**Comment by veris-kamaraj** [comment]
the document ui is not there in the new outlook that is the issue . can you
help me on this . i have attached the screenshot in the ticket itself

**Comment by DivyaPatidar** [comment]
@veris-kamaraj This is expected behaviour. Can you tell me where did you install the Outlook App from? 
Meanwhile you can sideload addin using  https://aka.ms/olksideload. For details check our documentation [here](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing#:~:text=In%20your%20preferred%20browser%2C%20go%20to%20https%3A//aka.ms/olksideload.%20Outlook%20on%20the%20web%20opens%2C%20then%20the%20Add%2DIns%20for%20Outlook%20dialog%20appears%20after%20a%20few%20seconds.)

**Comment by veris-kamaraj** [comment]
hi divya previously in mac we sideload the addin from manifest file now
there is no option to add the addin from manifest file when we click on
getAdd in button it is navigating to addin store no option to add the file
. adding the video for your reference .
 Screen Recording 2024-08-07 at 2.55.35 PM.mov
<https://drive.google.com/file/d/14ETYm663QuueqDlSat3wq8SfRekUqHI_/view?usp=drive_web>
please revert back if i am wrong on adding the manifest file

Thank you

**Comment by exextoc** [comment]
Hi @veris-kamaraj, we do not have access to this google drive, can you pls share the repro video here or create a private github repo and give access to exextoc.

**Comment by veris-kamaraj** [comment]
i have changed the access please check

**Comment by anjalitp** [comment]
@veris-kamaraj  Please confirm if Microsoft Outlook was originally installed from App Store.
 Also, could you please collect logs from Outlook Mac by following the steps mentioned here  https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues

**Comment by veris-kamaraj** [comment]
it is downloaded from the app store only

**Comment by anjalitp** [comment]
This is expected behaviour for Outlook versions installed from App Store. This was changed recently. Could you please uninstall the current version and install the latest version from https://learn.microsoft.com/en-us/officeupdates/update-history-office-for-mac and see if the issue resolves?

**Comment by veris-kamaraj** [comment]
my question is how you will add the custom manifest file for the add in it
is navigating to
https://appsource.microsoft.com/en-us/marketplace/apps?product=office%3Boutlook&page=1&src=office&corrid=b18ed3c6-d333-a606-6ac5-2399b2cb2889&omexanonuid=&referralurl=&ClientSessionId=3d75e4da-4d8a-42a4-bf8c-f83194e0399d
when i click on get add ins . you don`t support mac for outlook add in
development . in documentation you have mentioned some ui . that ui is not
exists in the current outlook app. due to this i am not able to develop
features into my existing app .please help me

**Comment by anjalitp** [comment]
@veris-kamaraj  If you install the Outlook Mac from Microsoft website  https://learn.microsoft.com/en-us/officeupdates/update-history-office-for-mac, Get Add-ins button should open the Store Page shown in below screenshot:
![image](https://github.com/user-attachments/assets/0f8206a4-3968-4434-80f1-27dd5f0251e5)


Other option is to install the add-in via Outlook Web by launching the url https://aka.ms/olksideload. This url should open up the same Store Page shown above, and add-in can be installed from My Add-ins -> Custom add-in section. After installing the add-in from Outlook Web, restart Outlook Mac for the add-in to show up.

**Comment by rhlarora84** [comment]
I am running into a similar issue. I created the basic setup using the yo tool and unified manifest. I could get into Outlook and sideload link to upload file. However the web outlook is looking for manifest.xml but will not allow loading manifest.json
