### ISSUE TITLE
The identity API is not supported for this add-in in online Word

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4759]
I have developed simple office addin using office manifest file. please refer attached manifest file
[manifest.zip](https://github.com/user-attachments/files/16510653/manifest.zip)

I have added below code as part of Add-in
  	try{
	const accessToken = await Office.auth.getAccessToken({
	allowSignInPrompt: true,
	allowConsentPrompt: true,
	forMSGraphAccess: true,
	});
	} catch (error) {
	console.log("Error obtaining token", error);
	}

but got error as "Error 13000, API for identity not supported " .

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 Yes. Currently we don't support Office.auth.getAccessToken() for identify. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) Thanks for reporting this.

**Comment by ishanig11** [comment]
How can I get user identity then? Basically using that I want to perform
file rename operation.

**Comment by stevefengjin** [comment]
@jipyua could you please look into this and provide assistance?

**Comment by ishanig11** [comment]
Any update on this?

**Comment by shanshanzheng-dev** [comment]
Hi @slabereemsft could you please help to take a look? Thanks.

**Comment by jargil** [comment]
@ishanig11 - have you seen our documentation for handling SSO errors? https://learn.microsoft.com/en-us/office/dev/add-ins/develop/troubleshoot-sso-in-office-add-ins#13000
I recommend following our guidance here too: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins?tabs=jsonmanifest

Your manifest does not have the WebApplicationInfo section.
