### ISSUE TITLE
[Outlook] `cursor` CSS styles are ignored in Mac taskpane

### ISSUE THREAD

**Issue by ShannonLCapper** [OfficeDev/office-js#476]
In the taskpane in Mac Outlook, elements with the `cursor` style (for example: `<div style='cursor: pointer;'>Hello</div>`) do not show that cursor style when hovered.

## Expected Behavior

I would expect that the `cursor` CSS style would be displayed accurately.

## Current Behavior

Hovering over any element with a `cursor` CSS style does not result in the mouse cursor displaying that style. It always displays the default style.

This bug does not repro in Windows Outlook 2013, Windows Outlook 2016, or OWA on any browser (including Safari). It also doesn't repro in a dialog opened by the plugin in Mac Outlook -- in a dialog, `cursor` CSS styles work correctly.

So far I've only tested this in a plugin running in the compose window in Outlook, so I do not know if it happens in other hosts.

## Steps to Reproduce, or Live Example

1. Open a taskpane on a compose window in Mac Outlook, pointed at the following HTML file:
```
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Office JavaScript API -->
    <script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js"></script>
</head>

<body>
    <div style='cursor: pointer;'>Your cursor should become a hand when you hover on me</div>
    <script>
        window.Office.initialize = function() {};
    </script>
</body>

</html>
```
Notice that the cursor does not become a pointer when hovering over the text in Mac, but it does in Windows and OWA. There also seems to be weird cursor behavior when moving the cursor off the text and out of the taskpane -- sometimes the cursor will become a pointer one it has left the taskpane
![cursor-example](https://user-images.githubusercontent.com/21230261/56072113-7b597700-5d48-11e9-8d6f-98338d3637bc.gif)

## Context

Cursor styles (especially `cursor: pointer`) give users clear indication of what UI elements are clickable or interactable.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.23.326.1
* Operating System: OSX High Sierra (10.13.6)

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding cursor CSS. We are able to reproduce this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by schachdavid** [comment]
Did you made any progress on this issue?

**Comment by gaelroustan** [comment]
I'm also interested in the status of this issue. Do you have any release plan?

**Comment by umar-khan** [comment]
We're seeing a similar issue in Excel.

## Current Behavior
On initial load, the cursor changes to `pointer` based on the CSS as expected.
However, if you move the mouse cursor out of the taskpane and then bring it back in, the cursor never changes from the default cursor.
If you then right-click inside the taskpane, the curor starts changing to `pointer` once again.

## Steps to Reproduce, or Live Example
I can reproduce this by creating a simple `div` element with inline style of `cursor: pointer`.

![cursor_bug](https://user-images.githubusercontent.com/4389490/67231148-c269a880-f40c-11e9-8aa9-49f7a311159a.gif)



## Context
It makes it much more difficult for users to find out which parts of the UI are interactable 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 16.30
* Operating System: macOS Catalina Version 10.15

**Comment by kbrandl** [comment]
Reassigning to @lliu113 (and unassigning @exextoc) since this seems to be a platform-wide, UI-related issue. @lliu113 are you able to provide any estimate as to when customers might expect this issue to be resolved? Thanks!

**Comment by lliu113** [comment]
@ShannonLCapper, @umar-khan  - apologies for the very late response to this. Is the pointer issue something you are still seeing?

**Comment by lindalu-MSFT** [comment]
@lliu113 Do we have a bug to track this internally?

**Comment by hellofantastic** [comment]
> @ShannonLCapper, @umar-khan - apologies for the very late response to this. Is the pointer issue something you are still seeing?

Can confirm its still an issue ... on Desktop 365 ....  web 365 is fine

**Comment by lliu113** [comment]
Internal tracking bug: 5014967

Reassigning over to Matt as this appears to be an add-in runtime issue

**Comment by hellofantastic** [comment]
Update, with out doing anything to my buttons... pointer just started appearing. Did a reload of add-in in outlook and seems to be sticking. Weird

**Comment by jargil** [comment]
This should be working as expected in any recent Office for Mac build.

**Comment by benpriebe** [comment]
This issue is appearing for me using an Excel task pane adding. I am running a recent Office for Mac build - 16.60 (22041000).

![image](https://user-images.githubusercontent.com/1300551/167510702-02985cd2-c33a-4158-8b90-b80915f3c70e.png)

The problem occurs when using a Shared Runtime with with a 'long' lifetime. 

![2022-05-10_08-30-09 (1)](https://user-images.githubusercontent.com/1300551/167510468-c5875da8-e6b5-4667-88d9-2ce9fae9dccc.gif)

Interestingly, if you hover the mouse pointer over the vertical scroll bar on the sheet the mouse cursor changes as expected for a brief period of time before disappearing again.

When I run the adding without a 'Shared Runtime' and 'short' lifetime. The cursor works as expected.

![2022-05-10_08-38-41 (1)](https://user-images.githubusercontent.com/1300551/167510559-d7d7c7d6-2d40-4f85-910c-bae6ec41c6df.gif)

**Your Environment**

Platform [PC desktop, Mac, iOS, Office Online]: Mac
Host [Excel, Word, PowerPoint, etc.]: Excel
Office version number: Version 16.60
Operating System: macOS Big Sur 11.6.5

**Comment by kamalprakhar** [comment]
We’re still able to reproduce this issue on the latest version of Excel for Mac, with all updates applied.
The cursor: pointer style is still ignored inside the task pane.
Is there any solution or workaround for this?
