### ISSUE TITLE
Addin sample not showing in new look outlook and browsers.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#4761]
Hello Microsoft team,

I hope all is well on your end.

I would just like to ask for some assistance on behalf of one of our customers. Their current problem is that the [spam addin sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/outlook-spam-reporting)  provided by Microsoft and our own spam addin do not show in OWA/browsers and in new look outlook. However, when they set the outlook client to classic look, the spam addin buttons are there.

Are there settings in the M365 platform that affect the show/hide behavior of the spam addin buttons? Why is it showing in classic look of outlook?

Thank you very much.

**Comment by AlexJerabek** [comment]
Hi @glr0221,

Thanks for reaching out.  @samantharamon, could you please investigate?

**Comment by samantharamon** [comment]
Hi @glr0221,

Thanks for reporting this. I'm unable to replicate this issue with our sample (ran from GitHub and from localhost). I'm not familiar with any settings in Microsoft 365 that would affect the visibility of the spam-reporting button. Let me clarify and investigate this further with the team (@exextoc).

**Comment by dahuja10** [comment]
Hi, @glr0221 can you provide with following information - 

1. Open OWA with enableTracing parameter like : "https://outlook.office.com/mail/inbox?enableTracing"
2. Get network from start of the OWA launch. You can follow the steps [here](https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues).
3. Also copy the console logs.

**Comment by glr0221** [comment]
Thanks for the responses @samantharamon @AlexJerabek @dahuja10 . Very much appreciated. I will ask for this data and get back to you as soon as I can. If possible, is there a safer way of sharing data (probably by email) without having to post the data here on github? Thank you.

**Comment by dahuja10** [comment]
sure @glr0221, you can create a private repo on github and give access to @exextoc .

**Comment by glr0221** [comment]
@dahuja10 @samantharamon @AlexJerabek 

Yesterday we got word from one of our customers that the spam addin now shows in new look outlook and OWA without them doing anything. They said that the buttons just showed up for them. So I really don't know what happened. 

One other customer has this issue, but we are waiting for more details. Thanks to all of you for your responses.

**Comment by sivachandran-msft** [comment]
@glr0221  Please share the details once you received it. Thanks.
