### ISSUE TITLE
IP Address Range Needed for Microsoft Office Add-in Validation Process

### ISSUE THREAD

**Issue by Seita-Hayashi** [OfficeDev/office-js#4762]
## Issue Description
We are developing a Microsoft Office Add-in and need to configure our Web Application Firewall (WAF) to allow access for the validation process during publication to the Office Add-in store.

## Current Situation
- Our web server is protected by a WAF that only allows access from our internal network.
- Microsoft needs to access resources on our web server during the Add-in validation process.
- We need to know the IP address range used by Microsoft for this purpose to configure our WAF accordingly.

## Specific Questions
1. What is the IP address range or ranges used by Microsoft when validating and accessing Office Add-in resources during the publication process?
2. Are these IP addresses static, or do they change? If they change, how frequently?
3. Is there an official Microsoft resource or documentation that lists these IP addresses for Add-in developers?
4. Do you have any recommendations for securely configuring our WAF to allow this necessary access while maintaining overall security?

## Additional Information
- We are unable to temporarily disable our WAF due to security policies.
- This information is crucial for us to ensure a smooth publication process while maintaining our server's security.

## Expected Outcome
Clear guidance on the IP ranges to whitelist in our WAF to allow Microsoft's validation process for our Office Add-in.

Thank you for your assistance in resolving this issue.

**Comment by shanshanzheng-dev** [comment]
@Seita-Hayashi Thanks for reaching us and sorry for slow response.
About IP address range, there is a reference about Microsoft IP ranges you can follow: https://learn.microsoft.com/en-us/microsoft-365/enterprise/urls-and-ip-address-ranges?view=o365-worldwide#microsoft-365-common-and-office-online
About how to develop and public, you can follow this reference: https://learn.microsoft.com/en-us/office/dev/add-ins/publish/publish
Hope it is helpful. Please let us know if you get a solution. Thanks.
