### ISSUE TITLE
NAA: Unable to acquire access token for event-based activation (onMessageSend)

### ISSUE THREAD

**Issue by manuelsidler** [OfficeDev/office-js#4764]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2408 Build 16.0.17928.20004 64-bit (Beta Channel)
* Operating System: Windows 11
* Browser (if using Office on the web): -
 
## Expected behavior
Acquiring an access token for event-based activation (onMessageSend) via NAA works the same as inside the taskpane.

## Current behavior
Acquiring an access token results in _ServerError_

Code snippet of the message send handler:
```typescript
createNestablePublicClientApplication({
    auth: {
        clientId: 'xxx',
        authority: 'https://login.microsoftonline.com/common'
    },
    system: {
        loggerOptions: {
            logLevel: LogLevel.Verbose,
            loggerCallback: (level: LogLevel, message: string) => {
                switch (level) {
                    case LogLevel.Error:
                        console.error(message)
                        return
                    case LogLevel.Info:
                        console.info(message)
                        return
                    case LogLevel.Verbose:
                        console.debug(message)
                        return
                    case LogLevel.Warning:
                        console.warn(message)
                        return
                }
            },
            piiLoggingEnabled: true
        }
    }
})
    .then((clientApp) => {
        const scopes = ['Mail.ReadWrite']
        const redirectUri = 'https://localhost:5173'
        const loginHint = Office.context.mailbox.userProfile.emailAddress

        const account = clientApp.getAccountByUsername(loginHint)
        const acquireTokenSilent = account
            ? clientApp.acquireTokenSilent({
                    scopes,
                    account,
                    redirectUri
                })
            : clientApp.ssoSilent({
                    loginHint,
                    scopes,
                    redirectUri
                })

        acquireTokenSilent
            .then((result) => console.log(result.accessToken))
            .catch((error) => {
                console.log('acquire token silently failed. Get by popup...')
                console.error(error)

                clientApp
                    .acquireTokenPopup({
                        scopes,
                        redirectUri
                    })
                    .then((popupResult) => console.log(popupResult.accessToken))
                    .catch((error) => {
                        console.log('acquire token by popup failed.')
                        console.error(error)
                    })
            })
    })
    .catch((error) => {
        console.error(error)
    })
```

## Steps to reproduce
1. Create an Outlook add-in with event-based activiation and onMessageSend handler
2. Use the snippet above to acquire an access token inside the message send handler

## Useful logs
```
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Info - Nested App Auth Bridge available: true		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Verbose - BrowserCrypto: modern crypto interface available		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Verbose - BrowserConfigurationAuthError: storage_not_supported: Given storage configuration option was not supported.		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Verbose - getAccount: No matching account found, returning null		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Verbose - setActiveAccount: No account passed, active account not set		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Verbose - getAccountByUsername: No matching account found, returning null		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Info - Emitting event: msal:acquireTokenStart		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Verbose - BrowserCacheManager.getAccountKeys - No account keys found		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Verbose - getAccount: No matching account found, returning null		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Verbose - No active account found, falling back to the host		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Error - Cached tokens are not found for the account, proceeding with silent token request.		
07/08/2024 15:00:04	Unexpected	Runtime	[Error] [Log] console.error: [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Error - Cached tokens are not found for the account, proceeding with silent token request.
Object.h [as error]
foundation.win32.bundle:57:1965
_Logger.loggerCallback [as localCallback]
C:\Users\manuel\AppData\Local\Microsoft\Office\16.0\Wef\{F3CA16E1-316B-44E6-B878-1D17DB9631EF}\a_tR7qffwhEaRODfyEFigA==\Javascript\89ca397d-15a9-4619-9e3a-363057b68df8_1.0.0.0_en-US\bundle.js:11446:24
_Logger.executeCallback
C:\Users\manuel\AppData\Local\Microsoft\Office\16.0\Wef\{F3CA16E1-316B-44E6-B878-1D17DB9631EF}\a_tR7qffwhEaRODfyEFigA==\Javascript\89ca397d-15a9-4619-9e3a-363057b68df8_1.0.0.0_en-US\bundle.js:2124:31
_Logger.logMessage
C:\Users\manuel\AppData\Local\Microsoft\Office\16.0\Wef\{F3CA16E1-316B-44E6-B878-1D17DB9631EF}\a_tR7qffwhEaRODfyEFigA==\Javascript\89ca397d-15a9-4619-9e3a-363057b68df8_1.0.0.0_en-US\bundle.js:2118:9
_Logger.error
C:\Users\manuel\AppData\Local\Microsoft\Office\16.0\Wef\{F3CA16E1-316B-44E6-B878-1D17DB9631EF}\a_tR7qffwhEaRODfyEFigA==\Javascript\89ca397d-15a9-4619-9e3a-363057b68df8_1.0.0.0_en-US\bundle.js:2130:9
_NestedAppAuthController.<anonymous>
C:\Users\manuel\AppData\Local\Microsoft\Office\16.0\Wef\{F3CA16E1-316B-44E6-B878-1D17DB9631EF}\a_tR7qffwhEaRODfyEFigA==\Javascript\89ca397d-15a9-4619-9e3a-363057b68df8_1.0.0.0_en-US\bundle.js:10664:33
Generator.next
<anonymous>:0:0
fulfilled
C:\Users\manuel\AppData\Local\Microsoft\Office\16.0\Wef\{F3CA16E1-316B-44E6-B878-1D17DB9631EF}\a_tR7qffwhEaRODfyEFigA==\Javascript\89ca397d-15a9-4619-9e3a-363057b68df8_1.0.0.0_en-US\bundle.js:25:21
		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Info - Emitting event: msal:acquireTokenFailure			
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Info - Emitting event: msal:acquireTokenFailure		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] acquire token silently failed. Get by popup...		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] { [ServerError]
  errorCode: '',
  errorMessage: '',
  subError: '',
  name: 'ServerError',
  errorNo: undefined,
  status: undefined }		
07/08/2024 15:00:04	Unexpected	Runtime	[Error] [Log] ServerError: 
_NestedAppAuthAdapter.fromBridgeError
C:\Users\manuel\AppData\Local\Microsoft\Office\16.0\Wef\{F3CA16E1-316B-44E6-B878-1D17DB9631EF}\a_tR7qffwhEaRODfyEFigA==\Javascript\89ca397d-15a9-4619-9e3a-363057b68df8_1.0.0.0_en-US\bundle.js:10475:17
_NestedAppAuthController.<anonymous>
C:\Users\manuel\AppData\Local\Microsoft\Office\16.0\Wef\{F3CA16E1-316B-44E6-B878-1D17DB9631EF}\a_tR7qffwhEaRODfyEFigA==\Javascript\89ca397d-15a9-4619-9e3a-363057b68df8_1.0.0.0_en-US\bundle.js:10640:48
Generator.throw
<anonymous>:0:0
rejected
C:\Users\manuel\AppData\Local\Microsoft\Office\16.0\Wef\{F3CA16E1-316B-44E6-B878-1D17DB9631EF}\a_tR7qffwhEaRODfyEFigA==\Javascript\89ca397d-15a9-4619-9e3a-363057b68df8_1.0.0.0_en-US\bundle.js:31:26
		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Info - Emitting event: msal:acquireTokenStart		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] [Wed, 07 Aug 2024 13:00:04 GMT] : [] : @azure/msal-browser@3.20.0 : Info - Emitting event: msal:acquireTokenFailure		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] acquire token by popup failed.		
07/08/2024 15:00:04	Verbose	Runtime	[Console] [Log] { [ServerError]
  errorCode: '',
  errorMessage: '',
  subError: '',
  name: 'ServerError',
  errorNo: undefined,
  status: undefined }		
07/08/2024 15:00:04	Unexpected	Runtime	[Error] [Log] ServerError: 
_NestedAppAuthAdapter.fromBridgeError
C:\Users\manuel\AppData\Local\Microsoft\Office\16.0\Wef\{F3CA16E1-316B-44E6-B878-1D17DB9631EF}\a_tR7qffwhEaRODfyEFigA==\Javascript\89ca397d-15a9-4619-9e3a-363057b68df8_1.0.0.0_en-US\bundle.js:10475:17
_NestedAppAuthController.<anonymous>
C:\Users\manuel\AppData\Local\Microsoft\Office\16.0\Wef\{F3CA16E1-316B-44E6-B878-1D17DB9631EF}\a_tR7qffwhEaRODfyEFigA==\Javascript\89ca397d-15a9-4619-9e3a-363057b68df8_1.0.0.0_en-US\bundle.js:10605:48
Generator.throw
<anonymous>:0:0
```

**Comment by dahuja10** [comment]
Hi @manuelsidler, thanks for reporting the issue. Can you please share the add-in in a private repo and give access to @exextoc. This way we will be able to investigate faster.

**Comment by manuelsidler** [comment]
@dahuja10 @exextoc I created a public GitHub repository to reproduce the issue: https://github.com/manuelsidler/outlook-naa-sample

There's also an issue when using NAA for event-based activation on the web and Mac:
```
Uncaught SyntaxError: Identifier 'Logger' has already been declared (at launchEvent.js:1:1)
```

It seems like a variable scope conflict between Officejs and azure/msal-browser.

**Comment by davidchesnut** [comment]
Hi @manuelsidler I want to mention there is a new NAA sample in PR that shows how to implement NAA in events. In particular you have to be careful how to configure webpack to avoid pulling in hot reload code when importing MSAL JS. https://github.com/OfficeDev/Office-Add-in-samples/pull/832 

Hoping this helps with the issues you are seeing!

**Comment by manuelsidler** [comment]
@davidchesnut I updated my sample repository (see comment above) based on your PR. Now I get the following error:

> 27/08/2024 15:48:10	Verbose	Runtime	[Console] [Log] { status: 'PERSISTENT_ERROR' }		
> 27/08/2024 15:48:10	Verbose	Runtime	[Console] [Log] [Tue, 27 Aug 2024 13:48:10 GMT] : [] : @azure/msal-browser@3.21.0 : Info - Could not initialize Nested App Auth bridge ([object Object])		
> 27/08/2024 15:48:10	Verbose	Runtime	[Console] [Log] [Tue, 27 Aug 2024 13:48:10 GMT] : [] : @azure/msal-browser@3.21.0 : Info - Nested App Auth Bridge available: false		
> 27/08/2024 15:48:10	Verbose	Runtime	[Console] [Log] [Tue, 27 Aug 2024 13:48:10 GMT] : [] : @azure/msal-browser@3.21.0 : Verbose - BrowserCrypto: modern crypto interface available		
> 27/08/2024 15:48:10	Verbose	Runtime	[Console] [Log] [Tue, 27 Aug 2024 13:48:10 GMT] : [] : @azure/msal-browser@3.21.0 : Verbose - BrowserConfigurationAuthError: storage_not_supported: Given storage configuration option was not supported.		
> 27/08/2024 15:48:10	Verbose	Runtime	[Console] [Log] [Tue, 27 Aug 2024 13:48:10 GMT] : [] : @azure/msal-browser@3.21.0 : Info - Emitting event: msal:initializeStart		
> 27/08/2024 15:48:10	Verbose	Runtime	[Console] [Log] [Tue, 27 Aug 2024 13:48:10 GMT] : [] : @azure/msal-browser@3.21.0 : Verbose - Claims-based caching is disabled. Clearing the previous cache with claims		
> 27/08/2024 15:48:10	Verbose	Runtime	[Console] [Log] [Tue, 27 Aug 2024 13:48:10 GMT] : [] : @azure/msal-browser@3.21.0 : Verbose - BrowserCacheManager.getTokenKeys - No token keys found		
> 27/08/2024 15:48:10	Verbose	Runtime	[Console] [Log] [Tue, 27 Aug 2024 13:48:10 GMT] : [] : @azure/msal-browser@3.21.0 : Info - Emitting event: msal:initializeEnd		
> 27/08/2024 15:48:10	Verbose	Runtime	[Console] [Log] Unable to get Graph access token: TypeError: Cannot read properties of undefined (reading 'hash')		
> Object.h [as error]
> foundation.win32.bundle:57:1965
> <unknown>
> C:\Users\manuel\AppData\Local\Microsoft\Office\16.0\Wef\{F3CA16E1-316B-44E6-B878-1D17DB9631EF}\a_tR7qffwhEaRODfyEFigA==\Javascript\21f402cd-0052-4c5f-b9ca-700b80899e89_1.0.0.0_en-US\bundle.js:11256:14
> Generator.throw
> <anonymous>:0:0
> rejected
> C:\Users\manuel\AppData\Local\Microsoft\Office\16.0\Wef\{F3CA16E1-316B-44E6-B878-1D17DB9631EF}\a_tR7qffwhEaRODfyEFigA==\Javascript\21f402cd-0052-4c5f-b9ca-700b80899e89_1.0.0.0_en-US\bundle.js:31:26

- Outlook Classic Beta Channel (Version 2409 Build 16.0.18015.20000 64-bit)
- msal-browser: 3.21.0

**Comment by manuelsidler** [comment]
@davidchesnut acquiring an access token via NAA in send event now works with beta channel version 16.0.18028.20004

**Comment by davidchesnut** [comment]
Glad it's all working! The sample is now published at https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Event-SSO-NAA. Closing this issue for now but let us know if you need help with anything else. Thanks!

**Comment by SaleemSiddiqi** [comment]
Reopening — the auto-suggested issue #4764 and the linked sample
(Outlook-Event-SSO-NAA) are for **event-based add-ins** (send/compose
event handlers), which is a different scenario from this report.

This issue is about an add-in that runs in the **mail read task pane**
(triggered by a ribbon button on a received email), not via an
event handler. The shared/lifecycle differences between event-based
and task pane add-ins are significant for NAA, so solutions for one
don't transfer to the other.

Additionally, both the Outlook-Event-SSO-NAA sample and the referenced
fix involve webpack-specific configuration. This add-in does not use
webpack — MSAL is loaded as a vendored static bundle (msal-browser.min.js)
via a <script> tag in the task pane HTML. So the webpack-related
guidance also does not apply.

The original report stands: NAA fails in the mail read task pane
on Outlook for Mac 16.108.503.3, with an empty ServerError from
fromBridgeError, and zero outbound network requests. All six
hypotheses tested in the original report were eliminated.

Requesting human triage.
