### ISSUE TITLE
Outlook NAA issue: "Something went wrong. [7q6cl]" Error

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#4767]
I am attempting to implement NAA within my Outlook Add-in and am running into an issue when attempting to acquire a token on Windows Desktop (I believe I'm using the Beta channel release).

It will open up the Token Popup, but I see an error stating "Something went wrong. [7q6cl]"
![image](https://github.com/user-attachments/assets/34ab3092-a500-49e2-a841-e6ed3e06ec48)

This works as expected in OWA after allowing popups in the browser.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft® Outlook® for Microsoft 365 MSO (Version 2408 Build 16.0.17928.20004) 64-bit
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome
 
## Expected behavior
I should be able to acquire a token using MSAL and NAA approached defined in the [example application](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-NAA) in Windows Desktop Outlook client.

## Current behavior

I receive the above error when attempting to obtain an access token.

It is occurring after calling the following line of code (popup opens with the error shown immediately). I have already allowed the permissions for my org when I tested in the browser the first time.:
```
const authResult = await this.pca.acquireTokenPopup(tokenRequest);
```

## Steps to reproduce

Deploy the example application (follow all instructions for setup of NAA) and attempt to obtain a token in Windows desktop client.

**Comment by cody-lettau** [comment]
I will note that I was surprised it worked in OWA, given it's been stated it only works in the Beta channel on Windows Desktop. I cannot find any information regarding the error code online.

**Comment by Yhuley** [comment]
@cody-lettau Hi, I'm having a similar issue with `this.pca.ssoSilent` on a Mac. After playing around with the `scopes` I send in the `tokenRequest`, I found that the scopes for shared mailboxes (`Mail.Read.Shared`, `Mail.ReadBasic.Shared`, `Mail.ReadWrite.Shared`) break it. Perhaps this is a reason for you too.

P.s. @exextoc Does this mean that `ssoSilent` does not work for shared mailboxes?

<img width="577" alt="Screenshot 2024-08-09 at 15 07 24" src="https://github.com/user-attachments/assets/c2f602ea-f075-43f2-a19c-3dbfc36271a7">

**Comment by cody-lettau** [comment]
For what I'm testing, I'm simply using ```Mail.Read``` scope right now. I will need to add additional scopes, as we too have the need to do the same in a shared mailbox.

This is for email activation -- we get a token and then are searching the last N messages to find a specific email with an activation link/code. We need the ability to do this in a primary mailbox, but also in a shared mailbox.

**Comment by Yhuley** [comment]
@cody-lettau are you using [this](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-NAA) sample for authentication? Maybe you missed `initialize` step? Because for me `acquireTokenSilent` works with shared mailbox scopes.

**Comment by cody-lettau** [comment]
@Yhuley we did follow that example, but we are calling ```initialize``` on the AccountManager (in ```authConfig```). I haven't tested with shared mailboxes yet. What is odd is that it works fine in OWA, just did not work on Windows Desktop. So I'd assume it's configured correctly and initialized given it's working on some platforms (OWA and Mac).

**Comment by cody-lettau** [comment]
To provide an update, I noticed that, even though it appears I'm in the "new ui", the toggle switch in the top-right corner does not reflect that.

![image](https://github.com/user-attachments/assets/ae4c8df2-622a-4b11-92e0-2f3fdc9e9602)

When I toggle this on, it does begin to work as expected.

This seems like a bug that needs to be fixed with Outlook and not specifically with NAA or office.js.

**Comment by Yhuley** [comment]
Hi @cody-lettau
Can you check it now with shared mailbox scopes (Mail.Read.Shared, Mail.ReadBasic.Shared, Mail.ReadWrite.Shared)? I'm curious will it work for you. Because for me It doesn't work in both - new and old views.

**Comment by davidchesnut** [comment]
Hi @cody-lettau just to confirm was it failing on new Outlook (as opposed to classic?) NAA isn't supported there yet but will be soon. thanks!

**Comment by adriencohen** [comment]
Hi @davidchesnut,

I'm still having the `7q6cl` error on Outlook new, isn't it supposed to be GA since the start of October ? I'm also a bit confused about why it's using the fallback if Outlook new doesn't supports it. 

Thanks!

**Comment by t4rzsan** [comment]
Hi [davidchesnut](https://github.com/davidchesnut),

We are getting the same error on New Outlook starting yesterday (at least that's when we discovered it).  It used to work on New Outlook and it is still working on iOS, Android and OWA.  We did not check macOS.

We are getting this error from `acquireTokenSilent`:

![image](https://github.com/user-attachments/assets/c3f8d897-d75e-4969-b935-609aa4c78185)

We then fall back to `acquireTokenPopup`, which gives us these:

![image](https://github.com/user-attachments/assets/9ecc18ed-2e1d-4e9e-bff9-b947e7c75f92)
![image](https://github.com/user-attachments/assets/c6252f1c-732b-4222-8d41-7e95a4c83891)

After that we fall back to old school `getAuthToken` which works.

The code looks like so.  We are not using any MS Graph tokens, only the `access_as_user` scope.

![image](https://github.com/user-attachments/assets/ca472bf1-41f3-44ca-b3fb-9b1c1ad6764c)

What are we missing, and why does it only fail on New Outlook and not on the other platforms?

Thanks

**Comment by marcus-atvero** [comment]
Just to say we are also getting this error, but just in Outlook for Windows (Classic and New).

I do have it working on tenant where I have admin rights, and there seemed to be a two stage app consent that appears on first run on this tenant, which I approve and then the app works fine on all platforms.

**Comment by marcus-atvero** [comment]
In case this helps someone else, my issue seemed to be that I'm getting a token to call an Entra protected Azure function.  This works fine on Mobile, Web and Mac, but on Windows classic and new I was getting the 7q6cl error.   

To fix it, I added an API permission for accessing my access_as_user scope, and granted admin consent. 

All works after this on all platforms

**Comment by t4rzsan** [comment]
Hello @marcus-atvero,

You are right.  Adding permission to access_as_user did the trick.  It is now working on New Outlook.  We still can't get classic working though, but we fall back to `getAccessToken` in that case.

Thank you for your feedback.

**Comment by marcus-atvero** [comment]
Hi @t4rzsan 

I'm finding the consents weird.   The approval when uploading the manifest doens't seem to consent to the access_as_user.  I had to go into the enterprise app reg and in Entra and re-approve it there (even though it showed as approved) and that seemed to do the trick for Classic and New.

**Comment by aigolang** [comment]
Hi @marcus-atvero , could you please tell me how do you add an API permission for accessing my access_as_user scope, and granted admin consent?
Do you mean in Azure portal -> Enterprise application? If yes, what application, and what permission?
Could you please tell me the steps details?

**Comment by marcus-atvero** [comment]
Hi @aigolang 

In Azure Portal, App Registration (not Enterprise Application),

Go to Expose an API

![Image](https://github.com/user-attachments/assets/15b8a13c-2592-4b93-ac4d-0d839239a6d7)

and then Add A Scope

![Image](https://github.com/user-attachments/assets/dcc3cce5-8d68-429e-b5dd-0bcc3b42c7dc)

and use access_as_user or whatever suits you for the name

then the scope is what you add to your manifest for access

Hope that makes sense!
