### ISSUE TITLE
Web Outlook provides improper attachment data if attachment is still uploading to the email

### ISSUE THREAD

**Issue by Suntechnick** [OfficeDev/office-js#4768]
# Web Outlook provides improper attachment data if the attachment is still uploading to the email

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome
 
To make it more clear when this issue occurs and why it is important for us, I'll describe how our add-in works. The add-in is the Outlook compose-mode taskpane add-in that somehow processes the attachments. To process the attachments, the add-in uses the `Office.context.mailbox.item.getAttachmentsAsync` API to get the attachments list and `Office.context.mailbox.item.getAttachmentContentAsync` API to get the attachment's content.

The issue occurs in Web Outlook if the add-in makes these Office API calls if the attachment is not fully uploaded to the email yet.
Steps to reproduce may look like this:
1. Have the taskpane add-in that calls the mentioned above Office APIs on its opening
2. Create a new email
3. Attach a file to the email
4. Open the taskpane while file is still being uploaded (easier to reproduce if the file is big or the user internet connection is slow)
5. Check the results of mentioned API calls

In that case, the results of these API calls may look something like this:
`getAttachmentsAsync` : 
![getAttachments1](https://github.com/user-attachments/assets/7b04329e-cd00-4b45-8e0f-65e0403e018e)
`getAttachmentContentAsync`: 
![getAttachmentContentAsync](https://github.com/user-attachments/assets/23f6fabd-7b72-45a7-9c03-2fd95a137fa6)

If we make the same calls for the same attachment after it was fully uploaded, we are getting different results:
`getAttachmentsAsync`:
![getAttachments2](https://github.com/user-attachments/assets/a6bfb962-c62c-4a1d-9168-e6fdb4d19ff0)
`getAttachmentContentAsync`:
![getAttachmentContentAsync2](https://github.com/user-attachments/assets/0afe2538-3bde-40f1-b279-2fe08084103c)

It makes sense that the attachment content is improper if the attachment was not uploaded yet, but neither `getAttachmentsAsync` or `getAttachmentContentAsync` results do not give any hints about this. Currently we can't find a way to determine whether the attachment was fully uploaded.

Sure, the workaround would be to wait until all the attachments are fully uploaded to the email, but we don't think that would be good for our customers. So, how can we address this issue?

**Comment by dahuja10** [comment]
Hi @Suntechnick, thanks for reporting this! Can you please share a sample add-in so that we can investigate faster. You can create a private repo and share access to @exextoc .

**Comment by Suntechnick** [comment]
[uploading-attachments-check.zip](https://github.com/user-attachments/files/16561978/uploading-attachments-check.zip)
The steps to reproduce are the same as in issue description. Check the console for the logs.

**Comment by anjalitp** [comment]
Thanks for reporting this issue regarding Attachment APIs. It has been added to our backlog. Unfortunately, we do not have a timeline to share at this point.

Internal Tracking ID: 4828663
Update: This is no longer tracked using the id above. It will be tracked via Tech community page ticket.

**Comment by ajays-msft** [comment]
Thank you for the input. This is will considered as a new feature request.
We track Outlook add-in feature requests on our[Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by Suntechnick** [comment]
Created the [ticket](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/ability-to-handle-attachment-content-properly-if-the-attachment/idi-p/4239943#M2697)
