### ISSUE TITLE
[Question] Is it safe to use `CustomFunctions.delayinitialization()`

### ISSUE THREAD

**Issue by hdwatts** [OfficeDev/office-js#4769]
We are transitioning our app from webpack to Vite, including our shared runtime add-in. This means that our main javascript bundle is now loaded as a script with a `type="module"` that does not block rendering while it loads.

Therefore, we've seen cases where the module containing our calls to associate CustomFunctions with our Javascript code has not loaded but the functions are still attempted to run. See below video where we attempt to run a custom function on a fresh workbook. There is a `#BUSY` delay while our add-in loads, but then the custom function runs prior to our custom functions registering, leading to a `#VALUE` error. Upon re-running the custom function, the modules have loaded and executed and it works.

https://github.com/user-attachments/assets/9ad0c0c6-7ae3-4366-b8f0-2c9a19b2f9da

---

While digging around, we found that adding a call to `CustomFunctions.delayInitialization()` in the HTML head section resolves this issue:

```html
<head>
	<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
	<script>
		CustomFunctions.delayInitialization()
	</script>
</head>
```

I can't find any documentation or information on this function, could someone on the Microsoft team let me know if this is a safe way to solve this issue?

**Comment by MiaofeiWang** [comment]
Hi @hdwatts , Using `CustomFunctions.delayInitialization()` can serve as a workaround for your scenario. However, please note that it is an internal API and has not been publicly released, so we cannot ensure its reliability.

If you would like to request this feature for public release, we recommend visiting [Microsoft 365 Developer Platform](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) to see if your question has already been addressed or to post a new one. Feature requests submitted there are considered during our planning process.
