### ISSUE TITLE
New Outlook - emails stuck in outlook at queued or draft status

### ISSUE THREAD

**Issue by mikey8808** [OfficeDev/office-js#4770]
# New Outlook - emails stuck in outlook at queued or draft status

## Your Environment

* Platform: New Outlook
* Office version number: 1.2024.725.400
* Operating System: Windows 10 Pro
 
## Expected behavior
In new Outlook, when an email has been successfully sent, they should be removed from the outbox when they have been sent successfully.

## Current behavior
In new Outlook, emails stay in the outbox even though they've been sent. They should be removed from the outbox when they have been sent successfully.

## Steps to reproduce
1. Send an email 
2. Email sent successfully to recipient
3. Go to outbox
4. Email stuck at "queued" or "draft" status.
5. Can't delete email

# Provide additional details
(https://answers.microsoft.com/en-us/outlook_com/forum/all/in-new-outlook-emails-stay-in-the-outbox-even/b5b94000-648a-42e6-b9b5-c973c568e276)

**Comment by Oleg-O** [comment]
Ummm... How is this related to office.js?

**Comment by mikey8808** [comment]
this issue only happens when an officejs add-in is present. when i don't have an add-in present, then the email does not get stuck in the outbox as "queued" or "drafts".

**Comment by dahuja10** [comment]
Hi @mikey8808 we will need some more information to investigate - 

1. Can you share which addin is causing this? It would be better if you can share the manifest also. 
2. How many users are affected?
3. Is it happening in outlook web also or only in new outlook?

**Comment by mikey8808** [comment]
works as expected now. emails disappear from the outbox when the email has been successfully sent.
