### ISSUE TITLE
context.application.createDocument works only first time

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4771]
I am using below code to open document in new tab. This code is working fine for first time. After that its opening document in tab which is previously opened. Can you check code and let me know what change I need to make to handle this issue?

export const openDocument = async (file) => {
  await Word.run(async (context) => {
    const response = await toBase64(file);
	var externalDoc = context.application.createDocument(response);
	externalDoc.open();	
	await context.sync();
	const builtInProperties = context.document.properties.customProperties;
	builtInProperties.load("*");
	await context.sync();
  });
};

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 Thanks for reporting this issue, I try this code to create document on word online, it works fine for each time. You can try this code: https://gist.github.com/shanshanzheng-dev/bf71a24597898b4f0cf4d52ab90306be

**Comment by ishanig11** [comment]
what is difference compared to my code which I wrote in react. I see un block is similar to what I used.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11, sorry, you use the code that I provided still hit a block? Could you share us your test document, the whole test code or repro video? Thanks. I'm not sure if I miss something, because I can create a new document every time when run this API. You can see this video:

https://github.com/user-attachments/assets/db594745-531e-4919-a29c-74dc40033a19

**Comment by ishanig11** [comment]
Please try this in online version. No issue with desktop.

**Comment by shanshanzheng-dev** [comment]
Yes, my video is word online.

**Comment by ishanig11** [comment]
If you see everytime tab is opening but its replacing document6 with document7 and so on..  we dont see them under new tabs.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 currently, this is our by-design behavior. But you can submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)
