### ISSUE TITLE
In Outlook, getAllInternetHeadersAsync works on an item in the Inbox, but not the sent folder

### ISSUE THREAD

**Issue by 1TheMuffinMan** [OfficeDev/office-js#4773]
I'm not quite sure if this is by design for the following reasons:
- https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/internet-headers#get-internet-headers-while-reading-a-message doesn't mention that it doesn't work on items in the sent folder
- The callback function to `getAllInternetHeadersAsync` returns a success status even when it returns an empty string for the value. If it's not supposed to work in the sent folder I think the status should be failed and the error property should be set.

Code:
```
  Office.mailbox.context.item?.getAllInternetHeadersAsync(asyncResult => {
      // In the sent folder
      // asyncResult.status === "success"
      // asyncResult.value === ""
  });
```

Inbox folder 👍 
![image](https://github.com/user-attachments/assets/753e8a58-3bf4-4ae4-bc9d-7beaa3e44532)

Sent folder 👎 
![image](https://github.com/user-attachments/assets/66200243-7648-4d88-bf3b-606b89556b88)

**Comment by sivachandran-msft** [comment]
Hi @1TheMuffinMan , thanks for your query.

The getAllInternetHeadersAsync API is giving the expected result. Try using the API for the emails which you have sent to others instead of the mails you sent to yourself. In case of mail sent to others, it is giving the internet header with expected information and in case of mail sent to yourself you will see empty values.

**Comment by martijnbrinkers** [comment]
> The getAllInternetHeadersAsync API is giving the expected result. Try using the API for the emails which you have sent to others instead of the mails you sent to yourself. In case of mail sent to others, it is giving the internet header with expected information and in case of mail sent to yourself you will see empty values.

Does not work for me. I tested this with Script Lab For Outlook. I can read the headers for received email but not for sent email (returns an empty string)

**Comment by michael-koch787** [comment]
Same issue for me. `getAllInternetHeadersAsync` just returns empty string on mails in the sent folder.
