### ISSUE TITLE
[PowerPoint] toJSON returns an empty object even though a property is loaded.

### ISSUE THREAD

**Issue by cobnett3** [OfficeDev/office-js#4775]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Browser (if using Office on the web): Chrome
 
## Expected behavior
`toJSON` should return a js object with properties loaded.

## Current behavior
`toJSON` returns an empty object even though a property (i.e. `id` in the code below) is loaded.

## Steps to reproduce

1. Use Script Lab and execute the following code.
```
// select a shape and click 'Run'
$("#run").on("click", run);

function run() {
  PowerPoint.run(async (context) => {
    const shapes = context.presentation.getSelectedShapes();
    shapes.load("items")
    await context.sync();
    const items = shapes.items;
    items.forEach((shape) => shape.load('id'));
    await context.sync();
    console.log(items[0].id); // 2 - the `id` property is loaded.
    console.log(JSON.stringify(items));  // expected: [{id: 2}] current: [{}]
  });
}
```

**Comment by EsterBergen** [comment]
@tsuga - This looks to be a bug. We are investigating and will create an item in our backlog. We'll provide updates here once available. Thanks!

**Comment by cobnett3** [comment]
@EsterBergen Thank you for picking this up. Is there any update?

**Comment by cobnett3** [comment]
@EsterBergen Is there any update?

**Comment by EsterBergen** [comment]
HI @tsuga - We don't have an update to share at this moment and will let you know here when more details are available. Thanks for your patience!

**Comment by EsterBergen** [comment]
@tsuga - Thanks again for reaching out, This is actually by design, 
@gergzk  can provide any follow-up to questions you may have here.

**Comment by cobnett3** [comment]
@EsterBergen Thank you for the update, but I'm afraid I don't get it. If this is by design, how can I use `PowerPoint.ShapeScopedCollection.toJSON`?

**Comment by gergzk** [comment]
@tsuga - the intent of the toJSON implementation is to override the JSON.stringify behavior to avoid throwing. The objects (eg: ShapeScopedCollection) have circular references and other non-stringifiy'able content.

**Comment by cobnett3** [comment]
@gergzk  Thank you for clarifying, but what you explained to me here does not align with what is written on the docs.

https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.shapescopedcollection?view=powerpoint-js-1.5

> [toJSON()](https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.shapescopedcollection?view=powerpoint-js-1.5#powerpoint-powerpoint-shapescopedcollection-tojson-member(1))
> Overrides the JavaScript toJSON() method in order to provide more useful output when an API object is passed to JSON.stringify(). (JSON.stringify, in turn, calls the toJSON method of the object that is passed to it.) Whereas the original PowerPoint.ShapeScopedCollection object is an API object, the toJSON method returns a plain JavaScript object (typed as PowerPoint.Interfaces.ShapeScopedCollectionData) that **contains an "items" array with shallow copies of any loaded properties** from the collection's items.

**Comment by gergzk** [comment]
@tsuga - Ah sorry, I skipped a step. The description of the toJSON you link is correct in general. Without a toJSON any attempt to stringify one of the office.js objects would throw, because they contain circular references. 

To cover up that behavior, the office.js toJSON are generally implemented to return {} (rather than throw). So, still not useful, but at least it doesn't blow up.
