### ISSUE TITLE
Do SharedRuntime 1.1 and ExcelApi 1.2 support ExcelApi 1.12?

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#4776]
We have published an Excel add-in, it has the following requirements in the current manifest:

```
    <Requirements>
        <Sets>
            <Set Name="ExcelApi" MinVersion="1.2" />
            <Set Name="SharedRuntime" MinVersion="1.1"/>
        </Sets>
    </Requirements>
```

Now, we plan to use [Range.getDirectPrecedents](https://learn.microsoft.com/en-us/javascript/api/excel/excel.range#excel-excel-range-getdirectprecedents-member(1)). We would like to know if and how we should modify the requirement block to support as large Excel versions as possible.

The tables of requirement set https://learn.microsoft.com/en-us/javascript/api/requirement-sets/excel/excel-api-requirement-sets?view=common-js-preview and https://learn.microsoft.com/en-us/javascript/api/requirement-sets/common/shared-runtime-requirement-sets?view=common-js-preview don't look very clear to me. I don't know if an Excel version that satisfies our current requirement block could always support ExcelApi 1.12, which is required by Range.getDirectPrecedents.

Could anyone help?

**Comment by penglongzhaochina** [comment]
Hi @chengtie ,

If the Office application or platform doesn't support the requirement sets or API methods that are specified in the Requirements element of the manifest, the add-in won't run in that application or platform, and it won't display in the list of add-ins that are shown in My Add-ins. One way is to modify your requirement set to support that API. Another way is to check for requirement support at runtime as described in the document, instead of defining requirement set support in the manifest.

**Comment by chengtie** [comment]
> Hi @chengtie ,
> 
> If the Office application or platform doesn't support the requirement sets or API methods that are specified in the Requirements element of the manifest, the add-in won't run in that application or platform, and it won't display in the list of add-ins that are shown in My Add-ins. One way is to modify your requirement set to support that API. Another way is to check for requirement support at runtime as described in the document, instead of defining requirement set support in the manifest.

Sorry, your reply did not answer my question.

Here are the extracted part from the requirement set.

Requirement set | Office on the web | Office on WindowsMicrosoft 365 subscriptionretail perpetual | Office on Windowsvolume-licensed perpetual | Office on Mac | Office on iPad
-- | -- | -- | -- | -- | --
ExcelApi 1.12 | Supported | Version 2008 (Build 13127.20408) | Office 2021: Version 2008 (Build 13127.20408) | 16.40 | 16.40
ExcelApi 1.2 | Supported | Version 1601 (Build 6741.2088) | Office 2019: Version 1601 (Build 6741.2088) | 15.22 | 15.0


Requirement set | Office on the web | Office on WindowsMicrosoft 365 subscriptionretail perpetual | Office on Windowsvolume-licensed perpetual | Office on Mac | Office on iPad
-- | -- | -- | -- | -- | --
SharedRuntime 1.1 | Excel, PowerPoint, Word: Supported | Excel: Version 2002 (Build 12527.20092)PowerPoint: Version 2102 (Build 13722.10000)Word: Version 2205 (Build 15202.10000) | Excel 2021: Version 2108 (Build 12527.20092)PowerPoint 2021: Version 2108 (13722.10000) | Excel: 16.35PowerPoint: 16.46.120.0Word: 16.61.401.0 | Not supported

Let's assume 

- `<Set Name="ExcelApi" MinVersion="1.2" />` and `<Set Name="SharedRuntime" MinVersion="1.1"/>` support the set A of Excel versions
- `<Set Name="ExcelApi" MinVersion="1.12" />` and `<Set Name="SharedRuntime" MinVersion="1.1"/>` support the set B of Excel versions.

My question is whether the set B is smaller than set A.

**Comment by penglongzhaochina** [comment]
Hi @chengtie ,
Sorry for the misunderstanding. I want to give a more clear explanation:
For the xml requirements which you mentioned, it's a version check for your office. If you specified MinVersion="1.2 and your office version  and platform meet the 1.12's requirement your add-in can be activated. it can't be activated if your platform and office version don't meet the requirements. This is a manifest check.
For runtime check, you can use "f (Office.context.requirements.isSetSupported('ExcelApi', '1.12')) {". After the manifest check passed we can say that you can use more apis by using the "1.12" than "1.2".

Contact me if you have any other questions.
