### ISSUE TITLE
Range.text returns null on some ranges on version 2407

### ISSUE THREAD

**Issue by jroycroft** [OfficeDev/office-js#4783]
# Provide required information needed to triage your issue
On a range of greater than 5 million cells, trying to get .text or .values returns null instead of an array of empty strings on version 2407. Version 2405 and below returns the expected values.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 16.87 (24071426)
* Operating System: Sonoma 14.4 (23E214)
* Browser (if using Office on the web): Safari

## Expected behavior

API returns an array of values

## Current behavior

API returns null

## Steps to reproduce

1. Create a sheet with a usedRange of greater than 5 million cells (as an example, A1:BZ64103)
2. Try to access usedRange.text or usedRange.values
3. Returns null

## Link to live example(s)

ScriptLab example: https://gist.github.com/jroycroft/7d268cf8552db0294f1d7bebac422984

# Provide additional details

This behaviour is different than on version 2405 and below of Excel, where these values would still be returned. On version 2407, we're getting null. I do see that there is documentation saying there's a cell limit https://learn.microsoft.com/en-us/office/dev/add-ins/concepts/resource-limits-and-performance-optimization#excel-add-ins so this may be expected behaviour, however this issue seems to only be occurring on the latest release version.

## Context

Need to read values that users of our addin have entered on the sheet

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by penglongzhaochina** [comment]
Thanks for reporting this issue.  

It has been put on our backlog<Bug#9258039> for internal track. We will keep track of this issue and let you know if there are any updates.

**Comment by XuanZhouMSFT** [comment]
Hi @jroycroft, thanks for the waiting. On all platforms, a range is limited to five million cells for get operations. The large range operation may result some bad behavior like hanging application, so we set the limitation for desktop also. Please refer to the document for some best practice: [https://learn.microsoft.com/en-us/office/dev/add-ins/excel/performance#payload-size-limit-best-practices](url). Please let me know if you have other concerns.

**Comment by logan-hcg** [comment]
@XuanZhouMSFT just ran into this.  While it is documented, shouldn't the API throw an error instead of just silently failing by returning `null` `text`/`values`?
