### ISSUE TITLE
Language Change not reflect in new outlook until restart

### ISSUE THREAD

**Issue by mujahidislam** [OfficeDev/office-js#4784]
# Language Change not reflect in new outlook until restart
In new outlook on windows, when language is changed the change is immediately reflected in the outlook panes unlike the classic one where restart is required. However, the taskpane add-in do not have any way to know the change in language. Please add changeLanguage event for add-in to listen to

## Your Environment

* Platform: PC
* Host: Outlook
* Office version number: Office 365
* Operating System: Windows 10
 
## Expected behavior
The change in language reflects in the add-in as well.

## Current behavior
The add-in doesn't get the new language, even the Office.context.displayLanguage returns the old language. This is so even after closing the add-in and open again. The new language is only detected by office js after restarting the outlook.

**Comment by sivachandran-msft** [comment]
Hi @mujahidislam, thanks for sharing your query. Can you please share your response for the following:

1. How did you changed the language? Is the language changed for the Windows entirely or specific to Outlook?
2. Whether are you able to see the language change in add-in taskpane after restart?

**Comment by mujahidislam** [comment]
hi @sivachandran-msft , 

How did you changed the language? Is the language changed for the Windows entirely or specific to Outlook? -- Option to change language in new outlook is available from 
> Settings -> General -> Language & Time

Whether are you able to see the language change in add-in taskpane after restart? -- Yes after restart the outlook, language change gets reflected in add-in as well. Basically  Office.context.displayLanguage returns the new language only after restart of outlook. This is even though Outlook itself reflects its labels in new language immediately without restart.

**Comment by anjalitp** [comment]
Thanks for reporting this issue regarding Office.context.displayLanguage . It has been put on our backlog. We unfortunately have no timelines to share at this point 

 

Internal tracking id: Office: 4839857

**Comment by patilganesh-msft** [comment]
Hi @mujahidislam, 

We recently checked and we can see the language change happening upon restarting the add-in. 
We also confirm that once we change the Outlook's language, restarting the add-in is must if we want to get the correct language reflected in Office.context.displayLanguage. 
Pl confirm your findings. Thank you.

**Comment by mujahidislam** [comment]
Confirm that addin receives the new language on restarting the addin, but would like to check if an event can be added for change in language so that addins can listen and update UI according to new language immediately.

**Comment by patilganesh-msft** [comment]
Hi @mujahidislam, as per the current design, all the local details are fetched at the load time of OWA/Monarch. Since language change is not a frequent activity, such details are not re-fetched. Hence, restarting the add-in will be the best possible solution. Thank you.

**Comment by mujahidislam** [comment]
Noted with thanks, but it does lead to a UX issue as base outlook language change immediately so it would have been ideal to have the mechanism to do the same for add-ins. Otherwise, different parts of outlook renders in different languages unless add-in is restarted.
