### ISSUE TITLE
setSelectedDataAsync() sets selection to empty if  replacing an `<img>` within a `<p>` tag

### ISSUE THREAD

**Issue by chambomango** [OfficeDev/office-js#4785]
## Your Environment

* Platform: Office on the web
* Host: Outlook
* Operating System: Windows
* Browser: Chrome
 
## Expected behavior

The `<img>` should get replaced with the data we send to setSelectedDataAsync().  In our case we tried setting the selected data to another `<img>` tag

## Current behavior

The `<img>` tag within the `<p>` tag gets replaced with an empty string, and the p tag converts to a `<div>`

## Steps to reproduce

1. Create an outlook 365 addin
2. Open 365 outlook online and set the body to
`<p class="pTagWrapper" style="margin:0">`
`<img src="https://picsum.photos/200/300" style="display:block" >`
`</p>` using setBody() or some equivalent
3. Click on the image
4. Call setSelectedDataAsync() via the addin and try setting to a different image, (or try to insert  anything).  Any image will cause the issue but I tested with `<img src="https://picsum.photos/id/237/200/300" alt="dog" width="500" height="600">`.  For the setSelectedDataAsync options I used `{ coercionType: Office.CoercionType.Html }`
5. Notice the selected image disappears without being replaced and notice the p tag was replaced with an empty div.  An `addRange()` warning appears in the console

## Context

We need this in order to set images inside p tags

## Screenshots
Before:
![image](https://github.com/user-attachments/assets/0e35758f-35ac-430e-9111-6f7dd881d19d)

After:
![image](https://github.com/user-attachments/assets/86a5660d-c0a6-4a0b-a367-3929c1c695ed)

## Useful logs

![image](https://github.com/user-attachments/assets/255c3e4d-457b-4a46-ae8b-6bc8f4c1eb52)

**Comment by sivachandran-msft** [comment]
Hi @chambomango , thanks for sharing the observations. We will investigate and get back on this.

**Comment by anjalitp** [comment]
We are not able to repro the issue. Could you please share a repro video? We would like to understand how the API is getting called after selecting the image.
