### ISSUE TITLE
Word.js creates a new document without rulers enabled

### ISSUE THREAD

**Issue by vlyamzin** [OfficeDev/office-js#479]
`context.application.createDocument().open()` method opens a new document without Ruler enabled. At the same time, 'Gridlines', 'Navigation Pane' and other Word features under the View tab keep their statuses.

## Expected Behavior
If the user turns on Ruler and opens a new document via` createDocument().open()` method, rulers must be enabled by default in the new document.

## Steps to Reproduce, or Live Example
* Link to live example: [https://gist.github.com/vlyamzin/374a6bd1ead9f15c83e5084a836f69bc](https://gist.github.com/vlyamzin/374a6bd1ead9f15c83e5084a836f69bc)

## Context
Our add-in provides the ability to create and enrich Word document with specific data. We have several .docx templates with styles, formatting, etc, converted to base64 format. Users have the ability to create a new note based on our template but after creation rulers disappear. Some of the users are not very experienced with Word and can't turn on this feature by themselves, so they asked us to enable rulers by default.

## Your Environment

* Platform: PC desktop
* Host: Word
* Office version number: Version 1808 (Build 10730.20304)
* Operating System: Microsoft Windows 10

## Useful logs

- [x] Screenshots
![1](https://user-images.githubusercontent.com/6349826/56129990-5b19fa00-5f8c-11e9-9ab1-e777008d2ad7.jpg)
![2](https://user-images.githubusercontent.com/6349826/56129997-5f461780-5f8c-11e9-9660-8687e9805fd4.jpg)

**Comment by dmahugh** [comment]
@JuaneloJuanelo do you know if it's possible to create a new document via the API with rulers enabled by default?

**Comment by JuaneloJuanelo** [comment]
good question for @tutieu

**Comment by weshi** [comment]
No, currently we don't have such JS API to control enable/disable the ruler.
