### ISSUE TITLE
getSelectedRanges.values is null if whole row/column is selected

### ISSUE THREAD

**Issue by didu9898** [OfficeDev/office-js#4792]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on web & desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): Chrome
 
## Expected behavior
getSelectedRanges.values should not be null if whole row/column is selected if there are non-empty cells

## Current behavior
If limited cells are selected, values is returned as array, if selected whole row/column, values = null even if there are non-empty cells

## Steps to reproduce
 ```
$("#run").on("click", () => tryCatch(run));

async function run() {
  await Excel.run(async (context) => {
      
    const rangeAreas = context.workbook.getSelectedRanges();
    rangeAreas.load('areas');
    await context.sync();
    rangeAreas.areas.items.map(async rangeArea => {
      rangeArea.load('values');
      await context.sync();
      console.log(rangeArea.values);
    });
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}
```

1. Fill a couple of cells in a row with any values
2. Select that whole row and click "Run" in script lab => output: values = null
3. Select 2-3 cells in the row => output : values as array

## Link to live example(s)

1. ______
4. ______
5. ______

# Provide additional details
1. ![image](https://github.com/user-attachments/assets/f8bd55b3-198c-4ef9-ab6f-adf90ea390cc)
2. ![image](https://github.com/user-attachments/assets/6a984784-883c-47c9-8cce-bc34517fcfa2)

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by XuanZhouMSFT** [comment]
Hi @didu9898, thanks for reporting the issue. Currently we have some limitation for large range operations. The large range operation may result in some bad behavior like hanging application, so we set the limitations for all platforms. Please refer to the document for introduction of the limitation and best practice: [https://learn.microsoft.com/en-us/office/dev/add-ins/excel/performance#payload-size-limit-best-practices](https://github.com/OfficeDev/office-js/issues/url). Please let me know if you have other concerns.

**Comment by wh1t3cAt1k** [comment]
@didu9898 could doing an intersection with the used range help in your scenario?
