### ISSUE TITLE
Cannot play video in Outlook on the web

### ISSUE THREAD

**Issue by matt-goldman** [OfficeDev/office-js#4795]
# Provide required information needed to triage your issue

I am trying to develop a first-run experience for my Outlook add-in, as per: https://learn.microsoft.com/en-us/office/dev/add-ins/design/first-run-experience-patterns

As part of this, I am trying to show a video in a dialog, as per: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-video

However, I am unable to get the video to load in the dialog.

Note that it _does_ work in Outlook on desktop.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Windows 11 Pro
* Browser (if using Office on the web): Edge
 
## Expected behavior

Video loads in the dialog.

## Current behavior

Video cannot play. Errors are displayed around `allow-presentation` flag. I have tried all sorts of things, including adding a `sandbox` attribute (with required flags), adding a CSP, using Vimeo instead of YouTube, using a locally hosted (small) `.mp4` file and a `video` tag, all to no avail.

Looks like either a bug or perhaps the docs should reflect that this feature is only available in Office desktop apps.

## Steps to reproduce

1. Create a new Office add-in, as per: https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart?tabs=yeomangenerator
2. Add the first-run experience, as per: https://learn.microsoft.com/en-us/office/dev/add-ins/tutorials/first-run-experience-tutorial
3. Add a "video placemat" as per: https://learn.microsoft.com/en-us/office/dev/add-ins/design/first-run-experience-patterns#video-placemat
4. Implement as per: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-video, and: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#open-a-dialog-box-from-a-host-page
5. Run the add-in (`npm start`)
6. Open the add-in in Outlook, see the FRE, click the video button, observe expected behaviour ✅
7. Sideload the add-in to Outlook web, open the add-in, see the FRE, click the video button, observe the error ❌

## Link to live example(s)

I don't have a live example, but I created a simple demo (as per steps above), which is available here: https://github.com/matt-goldman/outlook-video-demo

## Context

This is currently blocking me. My add-in failed certification for 4 specific reasons. One of these was absence of the first run experience. I have corrected the others, I would like to have this working before I re-submit.

## Useful logs

- [x] Console errors
```
Uncaught DOMException: Failed to construct 'PresentationRequest': The document is sandboxed and lacks the 'allow-presentation' flag.
    at W.initialize (https://www.gstatic.com/eureka/clank/127/cast_sender.js:87:87)
    at chrome.cast.initialize (https://www.gstatic.com/eureka/clank/127/cast_sender.js:99:137)
    at g.k.init (https://www.youtube.com/s/player/53afa3ce/player_ias.vflset/en_GB/remote.js:578:77)
    at Yub (https://www.youtube.com/s/player/53afa3ce/player_ias.vflset/en_GB/remote.js:249:40)
    at Oub (https://www.youtube.com/s/player/53afa3ce/player_ias.vflset/en_GB/remote.js:255:9)
    at Rub.d.disableCastApi.window.chrome.chrome.cast.chrome.cast.isAvailable.window.__onGCastApiAvailable (https://www.youtube.com/s/player/53afa3ce/player_ias.vflset/en_GB/remote.js:243:402)
    at chrome.cast.da (https://www.gstatic.com/eureka/clank/127/cast_sender.js:101:297)
```
- [x] Screenshots
![image](https://github.com/user-attachments/assets/e772a32a-bcf2-40f1-961d-218d32059767)

- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by rajjha-msft** [comment]
Hey @matt-goldman 

Thanks for reporting the issue. We have put it in our backlog. 
Unfortunately, we do not have any timelines to share at this moment. 

Internal tracking Id: 300061

**Comment by matt-goldman** [comment]
Thanks for the update @rajjha-msft

**Comment by arpitsangwanmsft** [comment]
Hey @matt-goldman! 
Thanks for your patience, can you please try this with the sample provided (https://github.com/matt-goldman/outlook-video-demo):

1) Add `localhost` (if the addin is locally hosted) or the domain of the fre-video.html page to the `appDomains` section in the manifest: 
![image](https://github.com/user-attachments/assets/ac51a835-2c67-4d6c-aa06-f50a3b6d2996)

2) Include office.js in the page (fre-video.html in this case) to be opened in dialog:
![image](https://github.com/user-attachments/assets/541d962b-3776-4609-b50e-08029b45d109)

This should resolve the video not loading issue. 
Thanks!

**Comment by matt-goldman** [comment]
Thanks @arpitsangwanmsft - I'll give this a go and let you know the results. Unfortunately I'm busy with documentation and won't get around to it until the end of the week - if you could forestall the automatic closure of this issue that would be awesome!
