### ISSUE TITLE
Word - Search and replace - ItemNotFound error

### ISSUE THREAD

**Issue by roldengarm** [OfficeDev/office-js#4796]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2407
* Operating System: Windows 11
* Browser (if using Office on the web): n/a
 
## Expected behavior
I can search for a text and replace all occurrences with another text.

## Current behavior
I'm getting an API error ItemNotFound.

## Steps to reproduce
```
 const searchResults = context.document.search('Original', {
    matchCase: false,
    matchWholeWord: false,
  });
  searchResults.load('items');
  await context.sync();

  for (let i = 0; i < searchResults.items.length; i++) {
    searchResults.items[i].insertText('Replacement',
      Word.InsertLocation.replace,
    );

    await context.sync();
  }
```
## Useful logs
![image](https://github.com/user-attachments/assets/d22630da-69ef-49b5-9aa3-abcead4913a4)

## Other
When I do NOT do a context.sync() before the replace, but use searchResults.getFirstOrNullObject() it works. However, that only gives me the first search result. I want to loop through all of them.
The context.sync() is needed to get the `items` property

**Comment by shanshanzheng-dev** [comment]
Hi @roldengarm Thanks for reaching us. Sorry, I can't repro this issue. When I run this code, it can replace original text. You can check this video. If you still hit this error, you can provide us more information. Thanks.

https://github.com/user-attachments/assets/bd53a5ce-a900-463d-adcd-ec0937d86315

**Comment by roldengarm** [comment]
Thanks @shanshanzheng-dev for trying. In a vanilla app it worked indeed.

The problem was that I ran it inside a .subscribe() of an Observable, and that the Word context object was created earlier. After wrapping the code inside the .subscribe() in a Word.run it works like excepted. Closing.
