### ISSUE TITLE
Outlook NAA: Something went wrong. [9zj08] ssoSilent fails when using shared mailbox scopes

### ISSUE THREAD

**Issue by Yhuley** [OfficeDev/office-js#4798]
I'm working on migration from SSO OBO flow to Nested App Authentication for my Outlook add-in and using [this](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-NAA) sample. What I've noticed `ssoSilent` method fails when I include shared mailboxes scopes (`Mail.Read.Shared`, `Mail.ReadBasic.Shared`, `Mail.ReadWrite.Shared`) to payload. Does it mean that NAA doesn't work with shared mailboxes?

![image](https://github.com/user-attachments/assets/79c359ef-3a4f-4701-8ec7-4d1b0bc09729)

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook (both Classic and New)
* Office version number: 16.89 (24081316)
![image](https://github.com/user-attachments/assets/a0434d54-4fb5-4f06-8efa-cc32801c4dfd)
* Operating System: macOS Ventura 13.0.1
 
## Expected behavior
`ssoSilent` should works with shared mailboxes scopes

## Current behavior
Fails with `Something went wrong. [9zj08]` error

## Steps to reproduce
Use [this sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-NAA) and try to call `ssoSilent` with next scopes:
`['openid',
  'profile',
  'User.Read',
  'Mail.Read',
  'Mail.ReadBasic',
  'Mail.ReadWrite',
  'Mail.Read.Shared',
  'Mail.ReadBasic.Shared',
  'Mail.ReadWrite.Shared']`

## Useful logs
The log I caught in `try catch`: {"errorCode":"","errorMessage":"","subError":"","name":"ServerError"}

**Comment by davidchesnut** [comment]
Hi @Yhuley,

Thanks for reporting this issue! It's possible you ran into a bug that we were tracking that is very similar to the behavior you saw. That bug was fixed and you shouldn't see the issue anymore. Can you please check to see if this is fixed for you now?

Thanks!
David

**Comment by Yhuley** [comment]
Hi @davidchesnut,

Just checked it, and unfortunately no the error remains the same

![image](https://github.com/user-attachments/assets/a773ccaf-f24b-44b1-8517-fe28528be775)

**Comment by codexeon** [comment]
This error usually indicates that a token was requested for more than one resource. I could not repro with the below code, but if you are including additional scopes that are not Graph it could be the root cause. Also the `email` scope could run into this issue. Could you provide the exact parameters you are passing?

```typescript
const popupRequestParams: PopupRequest = {
  scopes: ["Mail.Read.Shared", "Mail.ReadBasic.Shared", "Mail.ReadWrite.Shared"],
};
const result = await msalInstance.acquireTokenPopup(popupRequestParams);
```

**Comment by Yhuley** [comment]
@codexeon @davidchesnut  Here's my code which is mostly taken from [this sample](https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-NAA)

```typescript
import {
  AccountInfo,
  IPublicClientApplication,
  createNestablePublicClientApplication,
} from '@azure/msal-browser';
import { handleError } from '@utils-global';

export class AccountManager {
  private pca: IPublicClientApplication | undefined = undefined;

  private account: AccountInfo | undefined = undefined;

  private loginHint: string | undefined = undefined;

  // Initialize MSAL public client application.
  async initialize() {
    this.pca = await createNestablePublicClientApplication({
      auth: {
        clientId: process.env.AZURE_CLIENT_ID,
        authority: 'https://login.microsoftonline.com/common',
      },
    });

    // Initialize account by matching account known by Outlook with MSAL.js
    try {
      // @ts-ignore
      const authContext: AuthContext = await Office.auth.getAuthContext();
      const username = authContext.userPrincipalName;
      const { tenantId } = authContext;
      const localAccountId = authContext.userObjectId;
      this.loginHint = authContext.loginHint || authContext.userPrincipalName;
      const account = this.pca.getAccount({
        username,
        localAccountId,
        tenantId,
      });

      if (account) {
        this.account = account;
      }
    } catch (error) {
      // Unable to get account from Outlook
      handleError(error);
    }

    if (!this.loginHint) {
      const { accountType } = Office.context.mailbox.userProfile;
      this.loginHint =
        accountType === 'office365' || accountType === 'outlookCom'
          ? Office.context.mailbox.userProfile.emailAddress
          : '';
    }
  }

  // @ts-ignore
  async ssoGetUserIdentity(scopes: string[]) {
    if (this.pca === undefined) {
      throw new Error('AccountManager is not initialized!');
    }

    const tokenRequest = {
      scopes,
      loginHint: this.loginHint,
      account: this.account,
    };

    try {
      // acquireTokenSilent requires an active account. Check if one exists, otherwise use ssoSilent.
      const authResult = this.account
        ? await this.pca.acquireTokenSilent(tokenRequest)
        : await this.pca.ssoSilent(tokenRequest);
      this.account = authResult.account;

      return authResult;
    } catch (error) {
      handleError(error);
    }

    // Acquire token silent failure. Send an interactive request via popup.
    try {
      const authResult = await this.pca.acquireTokenPopup(tokenRequest);
      this.account = authResult.account;
      return authResult;
    } catch (error) {
      // Acquire token interactive failure.
      handleError(error);
    }
  }
}

``` 

here's how I use it

```typescript
  const authenticateWithNAA = async () => {
    try {
      const accountManager = new AccountManager();
      await accountManager.initialize();
      const { accessToken } = await accountManager.ssoGetUserIdentity(getAuthenticationScopes());

      return accessToken;
    } catch (error) {
      handleError(error);
    } 
  };
``` 
getAuthenticationScopes
```typescript
const regularScopes = [
  'openid',
  'profile',
  'User.Read',
  'Mail.Read',
  'Mail.ReadBasic',
  'Mail.ReadWrite',
];
const sharedMailboxScopes = ['Mail.Read.Shared', 'Mail.ReadBasic.Shared', 'Mail.ReadWrite.Shared'];

export const getAuthenticationScopes = (includeSharedMailboxScopes = false) =>
  includeSharedMailboxScopes ? [...regularScopes, ...sharedMailboxScopes] : regularScopes;

``` 

When I pass `true` to `getAuthenticationScopes` it includes shared mailbox scopes and makes `ssoSilent`
 fails.

**Comment by codexeon** [comment]
I tried your sample code with includeSharedMailboxScopes and could not repro the issue. A few suggestions to diagnose further:

- The mailbox scopes require admin consent. Does your account have admin permissions?
- Is there any unique conditional access policy deployed in your tenant for this user?
- Have you tried a different user or dev tenant (created at https://developer.microsoft.com/en-us/microsoft-365/dev-program) to see if they can repro.
- Does your user have a valid Exchange license, and can use the shared mailbox feature.
- If you swap out createStandardPublicClientApplication for createNestablePublicClientApplication can you still repro? createStandardPublicClientApplication will not use the brk-multihub reply URI, and you will need a valid SPA endpoint registered to test.
- Have you tried https://mail.office365.com/ to see if it can repro the same issue for you?
