### ISSUE TITLE
Range.select not working when chained (with 16.00 files)

### ISSUE THREAD

**Issue by ndreisg** [OfficeDev/office-js#480]
When using Office 2016 installed via MSI and not all updates installed (could reproduce it with 16.0.4266.1003), the Range.select function throws following exception when it is chained with promise.then:

```
Error at Range.select
AccessDenied: You cannot perform the requested operation.
 at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.00.debug.js:6771:6)
 at lib$es6$promise$$internal$$tryCatch (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.00.debug.js:7599:7)
 at lib$es6$promise$$internal$$invokeCallback (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.00.debug.js:7609:7)
 at lib$es6$promise$$internal$$publish (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.00.debug.js:7585:8)
 at lib$es6$promise$asap$$flush (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.00.debug.js:7404:7)
```

## Expected Behavior
Range should be selected.

## Current Behavior
Range is not selected and an exception is thrown.

## Steps to Reproduce, or Live Example
Minimal sample:
```
Excel.run(function (ctx) {
  var range = ctx.workbook.worksheets.getActiveWorksheet().getRange("A1:B2");
  range.values = [["1", "2"], ["3", "4"]];
  var promise = ctx.sync();
  // some other operations would be chained to the promise here
  return promise.then(function () {
    range.getCell(2, 0).select();
  });
}).catch(function (error) {
  console.log("Error: " + error.message);
  console.log("Stack: " + error.stack);
});
```

## Your Environment
* Platform: PC
* Host: Excel
* Office version number: 16.0.4266.1003
* Operating System: Windows

## Additional Info
The issue only occurs when office-js 16.00 files are loaded.
When 16.01 files are loaded it is working as expected.
So this could also be fixed with #138 
The issue does not occur with version 16.0.4738.1000 for example.

**Comment by Zlatkovsky** [comment]
Note:  FWIW, it might *not* be related to #138.  Instead, there might be the same root cause -- an old version of the Office host -- that manifests itself both in loading the 16.00 files AND having a bug wrt to `range.select`.  Personally, that would be my guess.

One way to rule out that relationship would be to simply force the loading of the 16.01 files (e.g., via a Fiddler redirect) and see whether it still fails.

@lumine2008 , FWIW, if you figure out how to get an old version of MSI Office 2016 installed, and esp. if you have a VM that you could just share with me, please email me.  I wanted a 2016 MSI machine to test something, so if you happen to create one, I'd happily use it for my experiment.

**Comment by ndreisg** [comment]
I could provide a Hyper-V VM with MSI Office 2016 (16.0.4266.1003) installed if you are interested.

**Comment by kbrandl** [comment]
@ndreisg did the feedback provided by @Zlatkovsky (re an old Office host being the root cause of this issue) unblock you, or are you still having problems with this? Thanks!

**Comment by ndreisg** [comment]
@kbrandl I am still facing this issue with a fresh MSI installation. 
@lumine2008 @Zlatkovsky I could provide an ISO if that helps (16.0.4266.1003)

**Comment by kbrandl** [comment]
@ndreisg thanks for confirming. @lumine2008 can you please resume investigation? Thanks!

**Comment by lumine2008** [comment]
@ndreisg , would you please help confirm whether this issue still repro? thanks.

**Comment by ndreisg** [comment]
Unfortunately I don't have the VM with the old MSI installation anymore.
I will try to setup a new system as soon as I find the time and will come back to you once I got results.

**Comment by lumine2008** [comment]
OK, Thanks, kindly reactivate this issue, when you have the environment. Thanks a lot.
