### ISSUE TITLE
copyFrom does not accept rangeAreas as inputs

### ISSUE THREAD

**Issue by nickpetri** [OfficeDev/office-js#4800]
Using the Excel Javascript API, I'd like to copy values and formatting from one `rangeAreas` object to another with equal dimensions. According to [the docs](https://learn.microsoft.com/en-us/javascript/api/excel/excel.rangeareas?view=excel-js-preview), `copyFrom` should work the same with `rangeAreas` as it does with ranges. But I'm getting an error:

```
RichApi.Error: The argument is invalid or missing or has an incorrect format.
```

I expect this to write values, formats, etc. from cells B8 & B10 to G8 & G10:

```
  await Excel.run(async (context) => {
    let s = context.workbook.worksheets.getActiveWorksheet();
    let sourceRanges = s.getRanges("B8, B10");
    let destinationRanges = s.getRanges("G8, G10");
    sourceRanges.format.fill.color = "pink"; // this DOES work, so sourceRanges is somewhat functional
    await context.sync();
    destinationRanges.copyFrom(sourceRanges); // RichApi.Error: The argument is invalid or missing or has an incorrect format.
    await context.sync();
  });
```

I am using MS365 v2407 and the [Excel JS API v1.16](https://learn.microsoft.com/en-us/javascript/api/excel?view=excel-js-1.16)

**Comment by XuanZhouMSFT** [comment]
@nickpetri thanks for reporting this issue. Currently the copyFrom API have the same limitation as UI behavior. From the UI, when you copy "B8, B10" to "G8, G10", it will also show the error like below. So we'd like to suggest you copy the range one by one if you only want to copy exactly the discontinue range to another discontinue range. Please let me know if you still have other questions.
![image](https://github.com/user-attachments/assets/bce83f8f-3eb0-4b58-b5c0-1cccbf3f89a8)

**Comment by nickpetri** [comment]
That makes sense - I would recommend updating the RangeAreas documentation to clarify. I find this misleading:

```
Copies cell data or formatting from the source range or RangeAreas to the current RangeAreas. The destination RangeAreas can be a different size than the source range or RangeAreas. The destination will be expanded automatically if it is smaller than the source.
```

**Comment by shanshanzheng-dev** [comment]
Thanks for advice. We'll discuss and create an internal task to follow up this action.
