### ISSUE TITLE
Outlook NAA: Migration path in code

### ISSUE THREAD

**Issue by manuelsidler** [OfficeDev/office-js#4802]
Based on the latest blog post about deprecating legacy Exchange Online tokens (https://devblogs.microsoft.com/microsoft365dev/updates-on-deprecating-legacy-exchange-online-tokens-for-outlook-add-ins/) we'll have three scenarios to support in our Outlook add-in:
- On-prem users
- M365 users with NAA support
- M365 users without NAA support

<img width="431" alt="image" src="https://github.com/user-attachments/assets/bb483572-5a70-44a1-8040-f1d031b9d9c1">

- Is my assumption of the scenarios and the flow correct?
- How can we check NAA support by code?
- What happens in event-based add-ins for M365 users, for which legacy tokens are deprecated but don't have NAA support yet?

Edit:
While fiddling around with NAA today, I found some answers (and more questions):
* There already seems to be a requirement set, which we can check for NAA support: `Office.context.requirements.isSetSupported('NestedAppAuth', '1.1')`. Is that the recommended way?
* `createNestablePublicClientApplication` has a fallback based on the doc: 
_creates NestedAppAuthController and passes it to the PublicClientApplication, falls back to StandardController if NestedAppAuthController is not available_.
So no need to fallback explicitly when NAA is not supported?
* `acquireTokenPopup` seems to work on hosts without NAA support (tested with new Outlook on Windows and classic Outlook [Current Channel]). Is a fallback to the login dialog still needed as stated in the NAA documentation?

**Comment by davidchesnut** [comment]
Hi @manuelsidler that flowchart is great! We're working on a sample that will show how to handle fallback scenarios, and can update this issue once it is ready in PR. The scenarios you point out are exactly what we are looking to show how to do. Thanks!

**Comment by manuelsidler** [comment]
@davidchesnut is there any timeline for when we can expect a sample to handle legacy scenarios?

**Comment by manuelsidler** [comment]
@davidchesnut @exextoc any updates?

**Comment by davidchesnut** [comment]
Hi @manuelsidler,

We published a sample showing how to fall back to trident here: https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-NAA-IE 

Check it out and let us know if this works for you.

Thanks!
David
