### ISSUE TITLE
Some add-in does not display for user in "Apps" 

### ISSUE THREAD

**Issue by OlegRomaniuck** [OfficeDev/office-js#4804]
# Provide required information needed to triage your issue

## Your Environment

* Platform [Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook for web
* Operating System: Mac
* Browser (if using Office on the web): Google chrome latest
 
## Expected behavior

User can find any add-in that is public
Example => 
<img width="1591" alt="Screenshot 2024-08-20 at 15 05 22" src="https://github.com/user-attachments/assets/1208e980-ab15-4935-b1d6-f55995adbd7c">
<img width="1712" alt="Screenshot 2024-08-20 at 15 06 11" src="https://github.com/user-attachments/assets/63444e58-c3b7-4230-9af1-dd4d62fc94d9">

## Current behavior

Some user can not find add-in in "Apps" tab
<img width="1484" alt="Screenshot 2024-08-20 at 15 13 33" src="https://github.com/user-attachments/assets/b7beddf9-0023-4347-8845-3e0f06102d8a">

## Steps to reproduce

1. Open Outlook for web  for example this link  => [Outlook web](https://outlook.office.com/mail/inbox)
2. Click on "More apps" button
3. Click on "add apps" button
4.  Type into search field word: Virtru
5. Wait result
Some screenshots for steps to reproduce => 
<img width="428" alt="Screenshot 2024-08-20 at 15 11 40" src="https://github.com/user-attachments/assets/48972a11-b55f-49b0-b597-e1f76cfbab11">

# Provide additional details

1. Some users can find add-in Virtru
2. For some users it does not display
3. All users are from the same domain

## Context

Can not find public add-in
## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by anjalitp** [comment]
1. Was the add-in deployed to the users via Admin center?
2. When was the add-in deployed?
3. Please collect logs by following the steps [here](https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues) and share it with us.
