### ISSUE TITLE
Excel desktop version refuses to load and parse CF metadata file bigger than 1MB

### ISSUE THREAD

**Issue by Yuri2b** [OfficeDev/office-js#4808]
# Provide required information needed to triage your issue
I am converting a VSTO Excel plugin to use the new JS API. The current plugin has 500+ UDFs that need to be converted into custom functions. I have created a functions.json CF metadata file and have run into the problem that the desktop version of Excel refuses to load this functions.json file if it exceeds 1 MB. The same build works in web version of Excel without issues.

## Your Environment

* Platform: PC Desktop
* Host: Excel
* Office version number: Excel for Microsoft 365 MSO (Version 2406 Build 16.0.17726.20078) 64-bit
* Operating System: Windows 11 Pro
 
## Expected behavior

Add-in should be loaded successfully even its CF metadata file is bigger than 1 MB

## Current behavior

Add-in loading failed with this error:
![355028567-1819b096-78c0-412a-b47d-0c84de906aab](https://github.com/user-attachments/assets/dddda8da-237c-42e3-8d56-8e72013a2901)

Looks like Excel doesn't even try to parse the CF metadata file if its size is bigger than 1 MB.
No `[Metadata] [Parsing] [Begin]` records appear in `OfficeAddins.log` file.

## Steps to reproduce

1. Create a new CF shared runtime project using the Yeoman template
2. Add some dummy functions to `src/functions/functions.ts`
3. Generate CF metadata file by the plugin or manually. Check that this file is bigger than 1 MB
4. Run the project in dev mode or build and side-load your add-in manually
5. Compare behavior in desktop and web version

# Provide additional details

More details and steps to reproduce here: https://github.com/OfficeDev/Excel-Custom-Functions/issues/422

**Comment by shanshanzheng-dev** [comment]
Hi @Yuri2b Thanks for reaching us. Just like https://github.com/OfficeDev/Excel-Custom-Functions/issues/422, Currently we have a size limitation for the metadata of 1MB. We did some test before and found that around 20k CF may hit the limitation. So we'd like to suggest you to help reducing some description in the metadata file may helps.  If we have any new updates, we'll report back. Thanks.
