### ISSUE TITLE
Unable to Test Edge WebView. Add-in is still using IE/Trident.

### ISSUE THREAD

**Issue by Andrew-AnalysisPlace** [OfficeDev/office-js#481]
I am interested in testing Edge WebView, but my Office.js Add-In continues to use IE/Trident.
I am using the versions suggested by Sudheer Maremanda in the April 10 Community Call:
-- Windows 10 Pro Version 1903 (Build 18362.53)
-- Office Version 1903   (Build 11425.20228 Click-to-Run) 16.0.11425.20214 32-bit
I have restarted my PC a couple times.

What else do I need to do to use Edge WebView?

## Expected Behavior
Add-in uses Edge WebView

## Current Behavior
Add-in still uses IE/Trident. I can confirm it is using IE/Trident by viewing the add-in UserAgent and by seeing IE open new processes in Task Manager and not Edge processes when I open add-ins.

## Your Environment
-- Windows 10 Pro Version 1903 (Build 18362.53)
-- Office Version 1903   (Build 11425.20228 Click-to-Run) 16.0.11425.20214 32-bit

**Comment by kbrandl** [comment]
@Andrew-AnalysisPlace thanks for reporting this issue and sorry to hear that you're having trouble. 

@jargil can you please help to unblock @Andrew-AnalysisPlace with being able to test his add-in with Edge WebView?

**Comment by jargil** [comment]
@Andrew-AnalysisPlace - you have all the right builds, could you please confirm that you've also joined the Office Insiders program? https://insider.office.com/en-us/join

**Comment by kbrandl** [comment]
Closing this issue, as I spoke with @Andrew-AnalysisPlace this morning and he's confirmed that he's now able to successfully test his add-in with Edge WebView. (Thanks for chiming in here, @jargil!)

**Comment by dinglicoding** [comment]
@kbrandl @Andrew-AnalysisPlace   hi  how to use edge webview? my add-in need too ,thanks

**Comment by kbrandl** [comment]
@dinglicoding this topic was discussed at length during the April 10th Office Add-ins community call. You can find a recording of that call, along with the corresponding PowerPoint deck, here: https://developer.microsoft.com/en-us/office/blogs/office-add-ins-community-call-april-10-2019.
