### ISSUE TITLE
Contextual tabs documentation doesn't mention undo limitation

### ISSUE THREAD

**Issue by SharonCKC** [OfficeDev/office-js#4814]
**Article URL**
https://learn.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs

**Describe the problem**
Nowhere in the documentation is it mentioned that using contextual tabs causes undo to become disabled for users. If we had known about this in advance, we would most likely not have implemented it.  I'd like the undo limitation to be documented at the very beginning of the article to help others who may be new to the API understand this serious limitation and what they would be getting into if they used this.

Specifically, `requestUpdate` causes undo to become disabled. https://learn.microsoft.com/en-us/office/dev/add-ins/design/contextual-tabs#specify-the-contexts-when-the-tab-will-be-visible-with-requestupdate

**Comment by AlexJerabek** [comment]
Hi @SharonCKC,

Thanks for flagging this. This might be a product issue, not intentional behavior. Let me tag @EsterBergen to take a look.

**Comment by EsterBergen** [comment]
Thanks @AlexJerabek . @SharonCKC - let me look into this and I'll get back here soon.

**Comment by SharonCKC** [comment]
@EsterBergen thank you, was there any update? If it is not a product bug, I strongly advise documenting this limitation for others like us.

**Comment by EsterBergen** [comment]
@SharonCKC - Thank you for following up. This is a bug and we are working on fixing it in the upcoming months. @AlexJerabek - can you look into updating the documentation until the bug resolves? Thanks!

**Comment by AlexJerabek** [comment]
Thanks @EsterBergen. I'll update the docs and move this issue to the product repo, so we can follow up with the product fix there.

**Comment by SharonCKC** [comment]
Thank you for the response, and for the doc update. Appreciate it very much.
