### ISSUE TITLE
Outlook add-in new authentication methods

### ISSUE THREAD

**Issue by e-vidyaraghavi** [OfficeDev/office-js#4819]
How to implement the outlook add-in authentication currently as the getUserIdentityAsync() is going to be deprecated? Currently, I tried using the OBO flow, OBO flow works for Organisational accounts but not for personal accounts. What should be the method for Personal accounts? Suggest the fallback method for OBO for existing add-ins

**Comment by davidchesnut** [comment]
Hi @e-vidyaraghavi,

Thanks for this question. Can you help me understand more about your scenario? What are you doing with the identity token when it is passed to your web API? Are there specific claims you need? We recommend moving to Nested App Authentication with MSAL. This will give you an access token that you can pass to your web API. I'm pretty sure we map over to that but I just need to understand the claims and usage your are looking for from the token.

Thanks! 
David

**Comment by e-vidyaraghavi** [comment]
Hey David,


Thanks for the follow up, We have completed the implementation of OBO
flow in our end for outlook add-in auhtnetication. We are facing some
issues in supporting the flow for personal (outlook.com) accounts and
exchange accounts.

For work accounts, We silently retrieved the token using the below snippet
as per the documentation for:
OfficeRuntime.auth.getAccessToken({ allowSignInPrompt: true,
allowConsentPrompt: true })

As mentioned in NAA doc and limitations, We need to implement SPA
authorization as a fallback when silent authorization fails. This involves
opening a popup and authorizing the user.

In this flow, We are able to retrieve the access_token. But when the user
switches mail and the addin is not pinned, the add-in reloads which makes
us lose the gained access_token. So we again open the popup to get the
access_token. This repetition can be inconvenient for users.

Is there any cache/storage like roaming settings for add-in to store the
access_token attained during the SPA authorization. Or is there any other
method instead of SPA as a fallback for unsupported platforms.
 MSAL.mov
<https://drive.google.com/file/d/18tkJwhX5FEjJyKiKiTGEHlPTcJJ7DTeM/view?usp=drive_web>


PFA, Each time addin is reloaded when the user switches to another mail and
popup is opened.


Regards,
Vidya Raghavi

**Comment by davidchesnut** [comment]
Hi Vidya,

Unfortunately I think that's going to be the behavior for MSAL as it won't be able to detect account changes when the add-in reloads in a new context. You could try using Nested App Authentication, and fall back to that from OBO. NAA will also use SSO to get the token of the signed-in user, so if they switch accounts I don't believe you'll see popups as long as they are signed in and consented to the scopes. You can find more info at [Enable SSO in an Office Add-in using nested app authentication](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/enable-nested-app-authentication-in-your-add-in).

Hope this helps,
David

**Comment by davidchesnut** [comment]
Hi @e-vidyaraghavi, I'll go ahead and close this issue, but please let us know if you have any additional questions. Thanks!

**Comment by e-vidyaraghavi** [comment]
I have another query, please check this too:

I have adopted the OfficeRuntime.auth.getAccessToken() method for getting the token. For validating the token, used server side code as suggested in this https://learn.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins?tabs=jsonmanifest#pass-the-access-token-to-server-side-code

The document says that the aud in the token will be the client-id of the app registered in Azure portal, but however I'm getting the Resource URI as given for the app in azure. Can you please confirm which one should we use to validate? the client-id or the resource URI

Note: Sometimes we get client-id, sometimes resource URI
