### ISSUE TITLE
Missing/undefined message body for all mailbox item messages whose sender are also a recipient. 

### ISSUE THREAD

**Issue by LBryan-BaS** [OfficeDev/office-js#4822]
## Summary
Getting the body of the current mailbox item in HTML via getAsync(), always results in an undefined value but only for messages where the sender is also one of the recipients.

```
  var body = Office.context.mailbox.item.body;
  var item = Office.context.mailbox.item;
  var attachments = Office.context.mailbox.item.attachments;
  
  body.getAsync(Office.CoercionType.Html, async function (asyncResult) {
  
      if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
  
        console.error(asyncResult.error.name + ": " + asyncResult.error.message);
  
      } else {
  
        let mailbody = asyncResult.value;
  }
  });
```

## Your Environment
Platform: Windows 11 Desktop PC
Host: Outlook Desktop and Web
Office version number: 2406 Build 17726.20206
Operating System: Windows 11
Browser: Edge Version 127.0.2651.105
 
## Expected behavior
body.getAsync() should provide the HTML message body of the currently selected message.

## Current behavior
body.getAsync() is currently broken with messages whose sender is also a recipient because is results in an undefined value for the message body but throws no exception.

## Steps to reproduce
1. In outlook web or desktop send an email to yourself or to a group in which you are included.
2. Open the email sent in step one.
3. Open an add-in written to capture the message body of the currently selected mailbox item:
```
Office.context.mailbox.item.body.getAsync(Office.CoercionType.Text, function(asyncResult) {
        if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
            console.log("Email body: " + asyncResult.value);
            asyncResult.value ?? console.error("Failed to get email body: body is undefined");
        } else {
            console.error("Failed to get email body: " + asyncResult.error.message);
        }
    });
}
```
5. Invoke the add-in the run.

**Comment by ndeleuze** [comment]
Hello @LBryan-BaS , thank you for reaching out with this issue.

I am currently unable to reproduce this in newer and older version for Desktop Outlook or the current version of Outlook for the web. I sent an email to myself and ran the provided code above (removing the asyncResult.value check for compilation and changing the CoercionType to CoercionType.Html). I am able to retrieve the Html body of my email.

It sounds like you are able to retrieve the body for emails in which you are not one of the recipients. Is that correct?

Could there be some other logic in your Add-in that is dependent on the recipients that could be causing this?
