### ISSUE TITLE
Addin deletion on browser close

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4823]
On my system, cache gets cleared on browser closure. So once "Cookies and Other Site data" get cleared out manually uploaded manifest file add-in also get deleted.

Is there anyway to  specify not to delete this manually added manifest add-in?

**Comment by Rick-Kirkham** [comment]
@emmasab Can you help find the answer to this customer's question?

**Comment by emmasab** [comment]
@ishanig11 I don't see any way of doing unless you disable clearing "Cookies and Other Site data" when the browser is closed. Manually uploaded add-in manifests are stored in that cache as sideloading is meant for development and ad-hoc testing.
