### ISSUE TITLE
Outlook Android hangs on pca = await createNestablePublicClientApplication(await getMsalConfig()) in launch event

### ISSUE THREAD

**Issue by GruberMarkus** [OfficeDev/office-js#4824]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Android
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 4.2432.0 (42432808)
* Operating System: Android
* Browser (if using Office on the web): -
 
## Expected behavior

launchEvent code behaves identically on Outlook for iOS and Outlook for Android.

## Current behavior

The launch event code reacts to onMessageSend. it works fine on iOS, but hangs on Android.

It is always the same line of code: pca = await createNestablePublicClientApplication(await getMsalConfig())

There is no error, the command just times out. The problem also exists without getMsalConfig, but providing the configuration as array.

The problem is not device specific, as multiple devices from differen OEMs behave identically.

## Steps to reproduce

1. Create an add-in for the launch event onMessageSend on mobile devices
2. Use the code pca = await createNestablePublicClientApplication(await getMsalConfig()); to initialize the public client application using NAA (Nested App Authentication)
3. The code works on iOS, but not on Android

## Link to live example(s)

I can provide a private repo, if required.

# Provide additional details

No additional details.

**Comment by rajjha-msft** [comment]
Hey @GruberMarkus 

It is not a repro for us. 
Can you please share a sample add-in which we can use to repro the issue ?

**Comment by GruberMarkus** [comment]
Yes, I can via a private repo. Please let me know which user I should grant permissions. The code may not be referenced here.

**Comment by davidchesnut** [comment]
Hi @GruberMarkus there is a known issue with @azure/msal-browser v 3.21.0 on Android. If you are using that version can you try 3.20.0 and see if the problem still exists? Thanks!

**Comment by ottD** [comment]
I encountered the same issue with NAA and @azure/msal-browser v 3.21.0 on Android and can confirm that downgrading to @azure/msal-browser v 3.20.0 resolves it 👍

**Comment by GruberMarkus** [comment]
Downgrading to 3.20.0 solved the problem immediately.

Thank you, @davidchesnut and @ottD!

Closing this issue.
