### ISSUE TITLE
Inconsistent setTimeout behavior when implementing concurrency protection

### ISSUE THREAD

**Issue by pepso** [OfficeDev/office-js#4826]
## Your Environment
* Platform: PC / Web
* Host: Outlook - New, and Web (Classic is fine)
* Office version number: Current-channel
* Operating System: Windows 11
* Browser: Chrome and Edge
 
## Expected behavior
Using setTimeout or setInterval is consistent across the Outlook versions and independent on where the code is executed from.

Using this code:
```
const startTime = new Date().getTime();
setTimeout(() => { console.log("setTimeout execution time (id):", ((new Date().getTime()) - startTime) + "ms"); }, 10);
```
should log "setTimeout execution time (id): 10". 

As we are working around browser/JS environment a 10-12ms range is obviously acceptable/expected. 

The output/execution time should be independent if the code is executed in Classic Outlook V8, Classic Outlook Taskpanel, New Outlook Launch Event, New Outlook Taskpanel, or in Web Outlook Launch Event or Web Outlook Taskpanel. 

If the time is not 100% consistent, then at least approximately around the same ballpark should be expected.

## Current behavior
Here's the execution times depending on how the code is executed:
Classic Outlook Launch Event  - About 10ms
Classic Outlook Taskpanel - About 10ms

New Outlook Office.onReady - About 900ms 
New Outlook Launch Event - Mostly around 800-900ms
New Outlook Taskpanel - About 10ms

Web Outlook onReady - About 900ms 
Web Outlook Launch Event - Anywhere between 70-900ms
Web Outlook Taskpanel - About 10ms

We are seeing 90x longer execution times depending on how the code is being executed.

## Steps to reproduce
Use above code snippet and wire it up to your chosen launch event action, command's onReady, or taskpanel's onReady and see the console logs.

# Provide additional details

Is there some artificial CPU cycle limit settings in play or is the browser just so overloaded with the New/Web Outlook code base that it doesn't have any available CPU cycles to handle the setTimeout, setInterval calls for the AddIn?

How on earth we are supposed to implement any concurrency protections to the Add-ins with this level of inconsistencies with the execution environment? 

The obvious answer how to handle these is to skip timeout/interval of the status checks and just stay in a `while (true) { statusCheck() }` loop, but that would obviously in normal circumstances load the CPU a lot more and seems like an amateurish approach. 

The constrain of 5 second launch event execution time in New Outlook and bad UX these random execution times might force us to that path unless there's a better solution somewhere or bug fix or performance improvement option?

Is there some plain old performance bugs in the code base as these measurements seems way out of hand for "just a bit loaded browser" as an explanation. We are talking about 90x longer timeout than we expect.

## Context
When implementing concurrency protection to the Add-in (i.e. multiple Launch Events being fired, parallel SSO token fetch error avoidance, long running fetch calls of <1s, AbortController.signal polyfill etc.), one often relies on setTimeout/setInterval to check for the processing statuses. 

We struggle to provide good UX because any concurrency check causes end user to wait for up to 1 second before we even start to execute the status check protected resources. 

The problem obviously compounds when you want to protect multiple resources and APIs like getSSOtoken (throws exceptions for parallel execution for example), long running network calls (0.5s-1s), and multi-action execution.

## Useful logs
Console logs for New Outlook:
```
setTimeout execution time (onReady): 937ms
setTimeout execution time (action): 899ms
setTimeout execution time (action): 904ms
setTimeout execution time (action): 955ms
setTimeout execution time (action): 317ms
setTimeout execution time (action): 997ms
setTimeout execution time (action): 609ms
setTimeout execution time (action): 786ms
setTimeout execution time (action): 893ms
setTimeout execution time (taskpanel): 11ms
setTimeout execution time (taskpanel): 10ms
setTimeout execution time (taskpanel): 11ms
setTimeout execution time (taskpanel): 10ms
setTimeout execution time (action): 117ms
setTimeout execution time (action): 412ms
setTimeout execution time (action): 884ms
setTimeout execution time (action): 883ms
```
Console logs for Web Outlook:
```
setTimeout execution time (onReady): 930ms
setTimeout execution time (action): 919ms
setTimeout execution time (action): 553ms
setTimeout execution time (action): 67ms
setTimeout execution time (action): 312ms
setTimeout execution time (action): 980ms
setTimeout execution time (action): 110ms
setTimeout execution time (action): 614ms
setTimeout execution time (taskpanel): 11ms
setTimeout execution time (taskpanel): 10ms
setTimeout execution time (taskpanel): 10ms
setTimeout execution time (taskpanel): 11ms
setTimeout execution time (action): 371ms
setTimeout execution time (action): 701ms
setTimeout execution time (action): 498ms
```

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by mobisw-msft** [comment]
Hey @pepso ,

Sorry for the delay. Thanks for reporting this issue. It seems that `setTimeout` has been known to be inconsistent in timing, regardless of outlook web add-ins. However, we have tracked an item in the backlog for this issue with `setTimeout` performance in LaunchEvents and Office.onReady. However, we have no timelines to share at this point.

Internal Tracking Id: 4867254
