### ISSUE TITLE
Excel Web unable to load any addins through the store.

### ISSUE THREAD

**Issue by thordurk91** [OfficeDev/office-js#4828]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office Web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Online Excel
* Operating System: Windows 10
* Browser (if using Office on the web): Chrome
* Account type: Free Office Account, non-subscription.
 
## Expected behavior
Addin to load

## Current behavior
500 error in console on https://euc-excel.officeapps.live.com/x/_layouts/AddinServiceHandler.ashx?action=getEntitlements&app=excel
![image](https://github.com/user-attachments/assets/f298fc7f-839d-45e9-b4fd-444a13a6dd9a)

## Steps to reproduce

1. Sign into a free office account
2. Load Eve online addin through addin store (Or any addin, i.e. GPT for Excel)
3. Error pops up, addin ribbon is visible in nav, error happens again if clicked, no sidebar shown.

## Link to live example(s)
N/A

# Provide additional details

1. Works when the account has a 365 subscription.

## Context
Unable to load the addin

## Useful logs

500 error on https://euc-excel.officeapps.live.com/x/_layouts/AddinServiceHandler.ashx?action=getEntitlements&app=excel...

- [X] Console errors
- [X] Screenshots

**Comment by shanshanzheng-dev** [comment]
Hi @thordurk91 Thanks for reporting this issue, we're looking into the root cause. Thanks for your patience.

**Comment by aplahore4** [comment]
I am also facing the same issue; I have reported [here](https://github.com/OfficeDev/office-js/issues/4825)

**Comment by shanshanzheng-dev** [comment]
Hi @aplahore4 sorry for this and thanks for reporting. We're investigating this root cause.

**Comment by shanshanzheng-dev** [comment]
Hi @thordurk91 @aplahore4 We have mitigated this issue, please try again if it works on your side. We value your feedback. Thanks.

**Comment by thordurk91** [comment]
@shanshanzheng-dev Looks good to me now! I've asked users to retry their installations. Thanks
