### ISSUE TITLE
Can't access outlook web add-in in shared mailbox when using the "Open another mailbox"

### ISSUE THREAD

**Issue by SE-Hubert** [OfficeDev/office-js#4832]
Some of our clients contacted us since they where not able to access the add-in when using the "Open another mailbox" and selecting their shared mailbox. The add-in is there and it seems to be working for some context (ItemSent event is triggered and the DetectedEntity part of the add-in using regular expression is also working), but when composing or reading a message when we click on the add-in button nothing happens, no errors or nothing.

Note: When I add the mailbox as a shared folder everything works correctly. Its only when using the "Open another mailbox" option.

So I'm wondering if its a bug or if its just not supported because it was working previously.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows
* Browser (if using Office on the web): Chrome, Edge and Firefox
 
## Expected behavior
When I click on my add-in in the shared mailbox opened with "Open another mailbox" I want my add-in to open and display the side panel defined in the xml

## Current behavior
When clicking on the add-in in the shared mailbox opened with "Open another mailbox" nothing happens.

## Steps to reproduce

1. Deploy the add-in that the given shared mailbox through https://admin.microsoft.com/#/Settings/IntegratedApps. Including the shared mailbox 
2. Login to outlook to a user that has full access to the shared mailbox
3. Open the shared mailbox using "Open another mailbox" button
4. Try to click on the add-in in the "Apps" section nothing happens

# Provide additional details
Here is our manifest: https://office365.secure-exchanges.com/SecureExchanges.xml

## Useful logs
Here are some screen shots of where nothing is happenning:

When clicking on our add-in or the templates add-in nothing happens:
![image](https://github.com/user-attachments/assets/761a82dd-4da6-422c-b2ce-21c38bea6c1d)

Also, the poll add-in right next to the Apps button works correctly, but when clicking the "Scheduling poll" button a side panel with an error appears:
![image](https://github.com/user-attachments/assets/2799b153-2fa2-4e00-b451-1283a966c903)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by andrew-at-acta** [comment]
Users of our add-in have reported the same issue.

**Comment by rajjha-msft** [comment]
Hey @SE-Hubert 

In Outlook on the web, if you open a shared mailbox in a separate browser tab or window using the Open another mailbox option, you may encounter issues when accessing add-ins from the mailbox. We recommend opening the mailbox in the same panel as your primary mailbox instead. This ensures that add-ins work as expected in your shared mailbox.

If you prefer to open the shared mailbox using the Open another mailbox option, we recommend deploying the add-in to both your primary user and shared mailboxes.

For more info, please visit : https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=web%2Cjsonmanifest

**Comment by SE-Hubert** [comment]
@rajjha-msft 

I understand, just to clarify our organization is small so I just deployed it to the entire organization, so my mailbox and the shared mailbox both have the add-in and I had this problem when using the open another mailbox. Our users are the one that reported the issue to us, so we should recommend to just add the shared mailbox directly in their current mailbox?

Also it was working correctly before, why did it stopped working now?

**Comment by andrew-at-acta** [comment]
> @rajjha-msft
> 
> I understand, just to clarify our organization is small so I just deployed it to the entire organization, so my mailbox and the shared mailbox both have the add-in and I had this problem when using the open another mailbox. Our users are the one that reported the issue to us, so we should recommend to just add the shared mailbox directly in their current mailbox?
> 
> Also it was working correctly before, why did it stopped working now?

I have had the same experience; deployed to both the individuals mailbox and shared mailbox. Was working as expected up until last Friday 08/23.

**Comment by SE-Hubert** [comment]
@rajjha-msft 

I don't really think the "by design" resolution is not appropriate since it was **working previously** and its not only one specific add-in that is targeted, but all add-ins. Event the default "My templates" add-in is not working when clicking on it.

Also other problems like the "Scheduling poll" that was working previously is not working anymore.

The only thing I could find is that I now have a new error in my console:
![image](https://github.com/user-attachments/assets/df5de7bc-0573-445d-9e49-cbd40f8f2f4b)

Could this error be related to the add-in controls?

**Comment by SE-Hubert** [comment]
I just saw that someone commented on the same problem in another issue: https://github.com/OfficeDev/office-js/issues/4829.

He said that everything started working again about an hour ago. I just did some tests, it seems to be working again now.

**Comment by akshayta23** [comment]
We’re pleased to inform you that we’ve recently enhanced the behavior of Outlook add-ins in shared mailbox scenarios when accessed via a new tab in Outlook on the web. These improvements are designed to deliver a more reliable and seamless experience when working with shared mailboxes on a new tab in Outlook web. For more details. please refer to our updated documentation - https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/delegate-access?tabs=windows%2Cjsonmanifest#add-ins-in-shared-mailbox-scenarios

**Comment by HichamFH** [comment]
Hello,

We are facing an issue with our custom Outlook add-in on shared mailboxes, specifically in Outlook on the web and also desktop version.

**Summary:**
- The add-in works correctly on personal mailboxes, on both Outlook Desktop and Outlook on the web.
- The add-in ribbon button does not appear at all on shared mailboxes in Outlook on the web, when the shared mailbox is opened via "Open another mailbox" (separate browser tab).

**Steps to reproduce:**
1. Sign in to Outlook on the web with a personal account that has Full Access permission on a shared mailbox.
2. Click the profile picture, then "Open another mailbox."
3. Enter the shared mailbox address, it opens in a new browser tab.
4. Open any message in Read mode.
5. The add-in button is missing from the ribbon (while it is present for the same user's personal mailbox).

We also tested in a private/incognito browser window to rule out caching, same result.

Console error captured when opening the shared mailbox tab:
Uncaught (in promise) Error: Error processing options response
    at owa.85166.m.f46b2c44.js:1:2861

<img width="1260" height="138" alt="Image" src="https://github.com/user-attachments/assets/ffd36b0c-9727-498f-8d89-07f9712d2fd8" />

**Manifest configuration:**
- Add-in only XML manifest
- Requirement set 1.13
- SupportsSharedFolders set to true

Could you please confirm if this is a known limitation or a bug, and whether there is a fix or workaround available?

Thank you.
Hicham.
