### ISSUE TITLE
Central Deployment (Integrated Apps) does not update the OOXML version when AutoShowTaskpaneWithDocument is configured 

### ISSUE THREAD

**Issue by rde-sdc** [OfficeDev/office-js#4838]
We deploy our add-in via Central Deployment (Integrated Apps) and have AutoShowTaskpaneWithDocument enabled on multiple excel files so that add-in auto launches when the document is opened.   To configure AutoShowTaskpaneWithDocument, the Version number is embedded into the OOXML (see bold text below) of the document in the webextension1.xml file ... when we update the manifest file in Integrated Apps (which requires us to update the manifest version number), the existing files does not load properly (specifcally, the Contextual Ribbon does not load).   In the debug logs (C:\Users\XXX\AppData\Local\Temp), it returns a "Shared Runtime ID is missing" error.   The only way to fix this is to open every excel file and update the OOXML to the new version.  We have 100s of excel files enabled with AutoShowTaskpaneWithDocument and need a better process of updating the local file's OOXML version when the manifest version changes.  

<we:webextension xmlns:we="http://schemas.microsoft.com/office/webextensions/webextension/2010/11" id="{XXXX}"><we:reference id="XXXXXX" **version="1.0.0.28"** store="EXCatalog" storeType="EXCatalog"/><we:alternateReferences/><we:properties><we:property name="Office.AutoShowTaskpaneWithDocument" value="true"/>

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Windows - Excel Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 2407 Build 16.0.17830.20056
* Operating System: Windows 11 Enterprise
* Browser (if using Office on the web): N/A (Desktop) 
* 
## Expected behavior
We expect the excel OOXML to update the version number when the add-in manifest version is updated. 

## Current behavior

Add-ins configured with AutoShowTaskpaneWithDocument do not load properly when the manifest file is updated in Integrated Apps because the version of the manifest file and the OOXML are not the same

## Steps to reproduce
1. enable AutoShowTaskpaneWithDocument in an Excel file using OOXML
2. update the manifest file via Integrated Apps (which will require you to update the version)
3. Add-in does not fully load properly.  
4. Contextual Ribbon does not load.

## Link to live example(s)
1. N/A

# Provide additional details

## Context
We have 100s of excel files enabled with AutoShowTaskpaneWithDocument and need a better process of update the OOXML version when the manifest version changes.  

## Useful logs
 "Shared Runtime ID is missing" error.  Contextual Ribbon does not load. 

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by shanshanzheng-dev** [comment]
Hi @rde-sdc Thanks for reaching us, we'll take a look and report back if we have a suggestion for you.

**Comment by gmichaud** [comment]
I also noticed the version number in our files doesn’t get incremented… following this issue

**Comment by AkhileshShah-MS** [comment]
Hey @rde-sdc Thanks for reaching out! 
Integrated Apps deployment only assigns the app to specific users and doesn't change configuration in any existing excel files. 
@shanshanzheng-dev Would your team be able to provide any script to change the configuration for multiple excel files?

**Comment by shanshanzheng-dev** [comment]
Hi @rde-sdc  @gmichaud Thanks, I'd like to check with you, the Central Deployment (Integrated Apps) is from store or just upload the manifest. this will help to continue investigation.

**Comment by rde-sdc** [comment]
@shanshanzheng-dev  We upload the manifest file.  But we can change it if it works the other way. Thanks for your help, let me know.

**Comment by shanshanzheng-dev** [comment]
Hi @rde-sdc Thanks for clarification. We need to discuss if there is a work around for you and will report back if we have a update. Thanks.

**Comment by rde-sdc** [comment]
@shanshanzheng-dev to give you a bit more idea on resolution, below is the current way we update the excel files via PowerShell ....  all our files on located on OneDrive, so would be nice to have a way to do it via the API.

<#######
	upgrade steps
	1. rename file extension to .zip
	2. Compress-Archive to replace webextension1.xml file (where the manifest version # is stored
	3. rename excel file back to .xlsx

########>
Dir *.xlsx | rename-item -newname { [io.path]::ChangeExtension($_.name, "zip") }  
Compress-Archive .\xl -DestinationPath .\excelFileWithAutoOpenOOXML.zip -Update   
Dir *.zip | rename-item -newname { [io.path]::ChangeExtension($_.name, "xlsx") }

**Comment by shanshanzheng-dev** [comment]
Hi @m-hellesen are you have some insights about this issue? Thanks.

**Comment by shanshanzheng-dev** [comment]
Hi @rde-sdc Glad that you have found a resolution. Based on our investigation, currently we don't support a process of updating the local file's OOXML version for all files when the manifest version change. 
We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)
Thanks.
