### ISSUE TITLE
From group we can upload sensitive file, in that case on send adding not get trigger, so sensitive file/folder/templates get uploaded

### ISSUE THREAD

**Issue by Medha-lab** [OfficeDev/office-js#4845]
Issue Description-
From group we can upload sensitive file, in that case on send adding not get trigger, so sensitive file/folder/templates get uploaded

 
Steps To Reproduce -
1.     Login to new outlook.
2.     From left pane click on groups.
3.     Select any group.
4.     Click on upload
5.     From upload sensitive file/folder/templates get uploaded

Actual Result -
From group we can upload sensitive file, in that case on send adding not get trigger, so sensitive file/folder/templates get uploaded
![image](https://github.com/user-attachments/assets/5d5aed9c-8486-4d70-9404-20fcba78ced0)

Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
Host [Excel, Word, PowerPoint, etc.]: New outlook
Office version number: You have Microsoft Outlook Version 1.2024.708.100 (Production). 
Client Version is 20240712002.10
webview2 version is 126.0.2592.113
session id is 6fcbff88-ff45-7a4b-ac09-3494fe7b37da
Operating System: win 11

**Comment by rajjha-msft** [comment]
Hey @Medha-lab 

OnSend is supposed to trigger when send button is clicked. 
Can you share a repro video of your scenario?

**Comment by Medha-lab** [comment]
I will attach video recording

**Comment by mobisw-msft** [comment]
Hey @Medha-lab ,

Sure. We will await the screen recording.

**Comment by Medha-lab** [comment]
https://github.com/user-attachments/assets/b5311caf-8796-4cfd-9c08-0dcace7d597d

**Comment by rkpathak** [comment]
@Medha-lab Here in this flow, you are uploading a file to one drive shared with the group. This is not same as sending mail with attachments.
