### ISSUE TITLE
Need more properties in RangeArea object like Excel.Range object

### ISSUE THREAD

**Issue by KishanVaishnani** [OfficeDev/office-js#4848]
When working with multiple Ranges to get the RangeArea object, there are limited properties such as [Excel Range](https://learn.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview).

For example, if I have fetched rows based on a special condition, such as a RangeArea object, and I want to hide those rows, the [Excel RangeArea](https://learn.microsoft.com/en-us/javascript/api/excel/excel.rangeareas?view=excel-js-preview) has limited properties to use. Unfortunately, I have to iterate through RangeArea and get a Range object for each area before setting the rowHidden property, which takes a long time to sync in Excel online. There are many use cases, but I cannot explain them all.

**Comment by XuanZhouMSFT** [comment]
Hi @KishanVaishnani, we recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)
