### ISSUE TITLE
Outlook add-in will work on SMTP inboxes in outlook or not?

### ISSUE THREAD

**Issue by junaid042** [OfficeDev/office-js#4850]
I have a outlook it is working on exchange server inboxes in outlook but I have no option to install add-in in SMTP server Inbox outlook add-in is supported SMTP inboxes or not?

**Comment by mobisw-msft** [comment]
Hey @junaid042 ,

Add-ins are not supported for non Exchange and Office 365 accounts, as mentioned in the documentation here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/add-in-requirements

![image](https://github.com/user-attachments/assets/0054e75e-02a1-4911-b8b8-f93db00808c0)

**Comment by junaid042** [comment]
@mobisw-msft We need a solution of the SMTP accounts any idea how can?

**Comment by mobisw-msft** [comment]
Thank you for the input. This will be considered as a new feature request. 

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.
