### ISSUE TITLE
Error is thrown when trying to save to custom properties during initialization in New Outlook for Windows.

### ISSUE THREAD

**Issue by ricardoleonhart** [OfficeDev/office-js#4851]
After my add-in is loaded, it will immediately load the custom properties, set a property and save it. If I open New Outlook for Windows and launch my add-in, the saving part will fail.

## Your Environment
* Platform: PC desktop
* Host: New Outlook for Windows
* Office version number: 2406 Build 16.0.17726.20206
* Operating System: Windows 11

**Additional info:**
* New Outlook for Windows Version: 1.2024.821.200 (Production)
* Client version number: 20240822057.09
 
## Expected behavior
Saving to custom properties is successfull upon initialization of add-in and custom properties.

## Current behavior
Saving to custom properties is **failing** after initialization of custom properties. 

## Steps to reproduce
1. Create a default React and Typescript Outlook add-in using Yeoman generator
2. Add these code to `src\taskpane\index.tsx` at line 15 (immediately after `Office.onReady`
```
  console.log("on ready");
  console.log("start loading custom props");
  const getCustomProperties = new Promise<Office.CustomProperties>((resolve, reject) => {
    Office?.context?.mailbox?.item?.loadCustomPropertiesAsync((result) => {
      if (result.status === Office.AsyncResultStatus.Failed) {
        console.log("failed to load custom properties");
        reject(result.error);
      }
      console.log("load successfully");
      resolve(result.value);
    });
  });

  const customProperties = await getCustomProperties;

  customProperties.set("test", "true");
  customProperties.saveAsync((asyncResult) => {
    console.log(asyncResult.status);
    if (asyncResult.status === Office.AsyncResultStatus.Failed) {
      console.error(asyncResult.error);
    }
  });
```
4. build (I use `pnpm build`)
5. Deploy the add-in dist files to server. 
6. Deploy the add-in manifest via Outlook admin
7. Open New Outlook for Windows via powershell command `olk.exe --devtools`
8. **Quickly** create a new message and launch the add-in
9. Observe the error in console logs.

## Context
My add-in needs to initialize and store the some data immediately in a persistent storage after it is loaded. AFAIK, custom properties is the best for this. This issue will cause my add-in to unable to perform its tasks because the initial data are not being set properly.

## Useful logs
Network log of the issue
![image](https://github.com/user-attachments/assets/d26748a6-43d3-498a-8e96-b92cba0ea021)

Console logs
![image](https://github.com/user-attachments/assets/da1b5d71-f8ea-48c0-9a36-344693a08e97)

**Comment by mobisw-msft** [comment]
Hey @ricardoleonhart ,

Is this issue only happening the first time an add-in tries to set Custom properties in a new session? More specifically, can you confirm if #4628 is the same as the issue that you are reporting?

**Comment by ricardoleonhart** [comment]
Hi @mobisw-msft , yes that seems to be the same issue. Thanks!

**Comment by rkpathak** [comment]
Marking as duplicate, please refer to the https://github.com/OfficeDev/office-js/issues/4628 for backlog updates.
