### ISSUE TITLE
[WordApi] range.insertField() throws "Sorry, this function isn't available."

### ISSUE THREAD

**Issue by adomasven** [OfficeDev/office-js#4854]
Word Online

Testing a development extension, attempting to insert a field.

```js
		await Word.run(async (context) => {
			const range = context.document.getSelection().getRange();
			range.insertField('Replace', 'Addin');
			await context.sync();
			// Throws RichApi.Error: Sorry, this function isn't available.
			// Perform a runtime check on the Office add-in to find out whether
			// the feature is supported by the host.
		});
```

**Comment by adomasven** [comment]
manifest.xml requirement set should be sufficient and worked with the below before.

```xml
  <Requirements>
    <Sets DefaultMinVersion="1.1">
      <Set Name="WordApi" MinVersion="1.5"/>
    </Sets>
  </Requirements> 
```

**Comment by shanshanzheng-dev** [comment]
Hi @adomasven Thanks for reporting this issue, we'll take a look and report back if we have a suggestion for you.

**Comment by shanshanzheng-dev** [comment]
Hi @adomasven About the usage of this API, you can check this reference: https://learn.microsoft.com/en-us/javascript/api/word/word.range?view=word-js-preview#word-word-range-insertfield-member(1)
Let me know if you still hit the error. If yes, could you share us your manifest? Thanks.

**Comment by adomasven** [comment]
https://github.com/zotero/zotero-word-js-integration/blob/main/manifest.xml

For the record I have been using the same manifest for the since last year to develop [this plugin](https://github.com/zotero/zotero-word-js-integration/tree/main) and inserting fields worked fine before. After reporting some bugs and receiving a response about them being fixed, I returned back to our code to test and found that it now fails with this error.

**Comment by shanshanzheng-dev** [comment]
Hi @adomasven Thanks for the detail, we'll take a look and report back if we have a suggestion for you.

**Comment by xiruatms** [comment]
@adomasven , thanks for reporting this. But unfortunately, I can't repro it. Can you help to share with us some screenshot, record or anything more? Can you repro this with ScriptLab?

**Comment by adomasven** [comment]
Here's the screencast of the error. I pushed some commits to our repository that include the function ran in the video.


https://github.com/user-attachments/assets/c1cf641a-8303-451d-ba31-798f2412f058

**Comment by xiruatms** [comment]
@adomasven , thanks for the details.

I have taken a try with your steps, it works as the screenshot shown:
![image](https://github.com/user-attachments/assets/d0bb1b1f-4ff2-47cc-8b13-14dac5f2c9fa)

May I know?
1) Did this work before?
2) What's the account you used to access the onedrive please? From the screencast, it seems the icon of "Sign in" was shown.

**Comment by adomasven** [comment]
> 1. Did this work before?

Yes. I last tested this code in April 2024 and it worked.

> 2. What's the account you used to access the onedrive please? From the screencast, it seems the icon of "Sign in" was shown.

It's my personal account. I recorded a screencast with a new Chrome profile to make sure anything in my main browser profile like extensions are not interfering. That profile is not signed in into my onedrive account, but the behaviour is the same if it is. I also just tested on Edge and it also doesn't work. The OS is Ubuntu Linux.

I also just tested in new documents and the behavior is the same.

**Comment by adomasven** [comment]
Any ideas on how to troubleshoot this further?

**Comment by xiruatms** [comment]
@adomasven , can you take a try with another account? And/or other documents?

**Comment by adomasven** [comment]
I created a new account and discovered that it works correctly. Why would my account not work? Is there some preference that I can change to fix this? Can I contact someone privately with my account information?

**Comment by adomasven** [comment]
@xiruatms any ideas on how to amend my primary account or what's caused this? We wouldn't want this to happen in production either.

**Comment by xiruatms** [comment]
@adomasven , I'm now trying to contact different teams on addressing your issue. Will get back to you if I got any updates. Thanks for your patience.

**Comment by adomasven** [comment]
Seems like this has resolved itself on my main account. Any idea what was the issue or how it was fixed?

**Comment by xiruatms** [comment]
Thanks for your confirmation. We've identified something unexpected, a fix was pushed to production. I will close this if you're fine with your main account now.

**Comment by adomasven** [comment]
Yes, it works fine now.
