### ISSUE TITLE
Word.Critique.popupOptions should be optional

### ISSUE THREAD

**Issue by shinji-morimitsu** [OfficeDev/office-js#4855]
Word.Critique.popupOptions was added on Word API v1.8,
On the other hands, other annotation options/methods were added on v1.7.
From the point of compatibility, I think popupOptions should be optional, right?

Actually, I want to use annotation only underline that triggers event without critique menu as v1.7 style.
Is the usage still allowed?

**Comment by AlexJerabek** [comment]
Hi @shinji-morimitsu,

Thanks for raising this. Let me transfer this issue to the office-js repo, where product issues are triaged.

**Comment by ElizabethSamuel-MSFT** [comment]
@shinji-morimitsu Thanks for asking about this. Yes, you should be able to create a critique without providing popupOptions. The documentation should reflect this the next time we publish. When that happens, I'll comment on this thread and close it.

Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@shinji-morimitsu The IntelliSense and the reference documentation have been updated so closing this.

Thanks again for your interest in Office Add-ins!

**Comment by shinji-morimitsu** [comment]
@ElizabethSamuel-MSFT 
Thanks for your support! I confirmed that @types/office-js is updated.
