### ISSUE TITLE
Cache remains when updating Office Add-ins

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#4856]
## Your Environment

* Platform : PC desktop
* Host : Outlook
* Microsoft® Outlook® version : 1.2024.103.100
* Operating System: Windows OS
 
## Issue

Hello,

We are developing a Vue application built with webpack. This is an Outlook add-in that displays a popup when sending an email using the ItemSend event. When we update new features using Microsoft Azure, sometimes the add-in is not properly updated after deployment. Specifically, it either remains on the old version or fails to load the updated configuration values.

Clearing the cache allows users to load the new version. According to the documentation, the caching methods work for most users, but for some users, it doesn't seem to work.

Is the cache issue something all add-in developers are experiencing? Are there any ways to prevent or mitigate this issue in advance?

This issue has a significant impact on users as we need to inform them to clear the cache every time.

**Comment by mobisw-msft** [comment]
Hey @mailchecktool-admin ,

This is unfortunately a web behaviour that is carried forward. Have you tried to implement [Cache Control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control) on your end to see if that fixes this issue?

**Comment by manuelsidler** [comment]
@mailchecktool-admin We also had some issues regarding the add-in cache (see #4286). Setting the meta tags helped, but  Office still rarely shows a cached version.
