### ISSUE TITLE
Add-ins are not loaded when "Share" feature is used from an Office application and Outlook is not running

### ISSUE THREAD

**Issue by MrDaleQ** [OfficeDev/office-js#4857]
An issue has been identified where Outlook does not load any add-ins when using the share function from an Office application when the Outlook application is closed.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2408 16.0.17928.20114
* Operating System: Windows 11
 
## Expected behavior
If the share function is used from an Office application when the Outlook app is closed, add-ins are loaded.

## Current behavior
With Outlook closed, using the share option from an office application does not load any Outlook add-ins.

## Steps to reproduce
Ensure all Outlook instances are closed.
Open Excel
Select File -> Share
Select the **Attach a copy instead** -> **Excel workbook** option
A new mail window is opened, no add-ins are loaded by Outlook.
Selecting the All Apps button shows that no add-ins are available.

## Link to live example(s)
Share button used with Outlook open loads add-ins:
![image](https://github.com/user-attachments/assets/8506c697-1f0f-4b59-ad30-f6bc7ed3e378)

Share button used with Outlook closed lists no add-ins / apps:
![image](https://github.com/user-attachments/assets/38b1cefd-7e9d-4f9f-8773-6b4d96224fdd)

**Comment by victoria-msft** [comment]
Currently, the feature you requested is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process. 

For more information about blocking this scenario and informing users to open Outlook first, please refer to this [documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/onmessagesend-onappointmentsend-events?tabs=windows#activate-smart-alerts-in-applications-that-use-simple-mapi).
