### ISSUE TITLE
Office.context.mailbox.item.saveAsync() returns a malformed Graph mail ID when invoked for the first time on an email item in Outlook on Windows (new UI)

### ISSUE THREAD

**Issue by cluB-Watermelon** [OfficeDev/office-js#4859]
Office.context.mailbox.item.saveAsync() returns a malformed Graph mail ID for the first time when a new email is being composed.

Steps to reproduce:
1. Open Outlook on Windows (new UI).
2. Compose a new email.
3. Open a taskpane add-in that internally invokes Office.context.mailbox.item.saveAsync() right after clicking on "New email".
4. The Graph mail ID returned is malformed (it looks something like this: "clientid:ea1a04f8-509e-...").

To that effect, if the mail gets saved to draft first (say, after adding an attachment), and then the above-mentioned add-in is invoked, a valid Graph mail ID is returned.

Platform: 
This behavior is observed in Outlook on Windows (new UI).
The taskpane add-in is running in compose mode.

Expected behaviour:
saveAsync() should ideally consistently return the same Graph mail ID

Current behavior:
When invoked for the first time, a malformed Graph mail ID is returned.

**Comment by cedomm** [comment]
I can confirm the issue, it seems to only be present in the new Outlook version, not in Outlook for the web. If the new e-mail has already been automatically saved by Outlook, then the `Office.context.mailbox.item.saveAsync()` call returns a valid mail ID, but if it has not, the call returns the aforementioned malformed ID which is unusable in Graph API calls.

**Comment by kumarshrey-msft** [comment]
Thanks for reporting this, it is a known issue, and the fix is being rolled out. We will update the thread post the fix reaches 100% prod.

**Comment by kumarshrey-msft** [comment]
This issue has been fixed. Thank you for raising the issue and helping us make the product better.
