### ISSUE TITLE
Word freezing for a while when reading document styles

### ISSUE THREAD

**Issue by RajChauhan-Dev** [OfficeDev/office-js#4861]
Platform : PC desktop
Host: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2404 Build 16.0.17531.20140) 64-bit
Operating System: Microsoft Windows 11 pro

Hi team,
We are working with stylized documents (some samples are attached below) and using the following code to load documents one after another in the same Word instance:

```
context.document.insertFileFromBase64(mybase64, "Replace", {
    importTheme: true,
    importStyles: true,
    importParagraphSpacing: true,
    importPageColor: true,
    importChangeTrackingMode: true
});
```

The style limit is being exceeded, and to resolve this, we used the following code to remove the styles. However, after calling context.sync(), Word becomes unresponsive and enters a "not responding" state. We tested this with various documents, and it consistently occurs when documents have 800-1000 or more styles, causing Word to freeze.

```
const styles = context.document.getStyles().load('items');
await context.sync();
for (let i = 0; i < styles.items.length; i++) {
    styles.items.forEach((style) => {
        if (!style.builtIn) {
            style.delete();
        }
    });
}
```

Please look into this issue and let us know if you have any questions. It is impacting our product, and we hope to receive a swift resolution from your end.

Thanks.
Here are some of the documents provided below:

[9d7e9f2f-8478-49b4-9407-7a3a0325505a.docx](https://github.com/user-attachments/files/16428172/9d7e9f2f-8478-49b4-9407-7a3a0325505a.docx)
[d2c49c7c-7339-4cec-8594-3ca4e394cc3d.docx](https://github.com/user-attachments/files/16428174/d2c49c7c-7339-4cec-8594-3ca4e394cc3d.docx)
[0b46b8bd-6491-4fb8-a55b-85342236c3d7.docx](https://github.com/user-attachments/files/16428175/0b46b8bd-6491-4fb8-a55b-85342236c3d7.docx)
[4e487f68-4ff7-493e-a52a-b7ccdb2305a8.docx](https://github.com/user-attachments/files/16428176/4e487f68-4ff7-493e-a52a-b7ccdb2305a8.docx)

**Comment by RajChauhan-Dev** [comment]
Hello team, 
Is there any update on this?

**Comment by RajChauhan-Dev** [comment]
Hello Team,
Is there any update on this?

**Comment by RuizhiSunMS** [comment]
@Raj-Dev1 , sorry for the late response. We found once we had a same case #4732 . That case has been inside our backlog with the track id of #9220118. Our colleagues are working on the investigation and other work. If any update, we will reply at that case considering consistency.
Thx.

**Comment by RajChauhan-Dev** [comment]
Thanks @RuizhiSunMS for your response.
Please keep us updated, this issue is pretty important for us to be fixed.

**Comment by RuizhiSunMS** [comment]
> Thanks @RuizhiSunMS for your response. Please keep us updated, this issue is pretty important for us to be fixed.

May I close this as 'dup' and focus on the original 4732?

**Comment by RajChauhan-Dev** [comment]
@RuizhiSunMS yes you can but please keep us updated, this issue is pretty important for us to be fixed.

**Comment by RuizhiSunMS** [comment]
> @RuizhiSunMS yes you can but please keep us updated, this issue is pretty important for us to be fixed.

Sure.
