### ISSUE TITLE
[Outlook on the Web] getAttachmentContentAsync hangs in certain sutuations 

### ISSUE THREAD

**Issue by Suntechnick** [OfficeDev/office-js#4868]
`getAttachmentContentAsync` call hangs and never provides the result of the call in certain cases. 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows
* Browser (if using Office on the web): Edge
 
## Expected behavior
`getAttachmentContentAsync` calls should never hang.

## Current behavior
As described in the title, in some cases `getAttachmentContentAsync` hangs infinitely.

## Steps to reproduce
1. Create an email with an attached file
2. Call the `getAttachmentContentAsync` on the attached file

# Provide additional details
Our client reported the issue with add-in not being able to process the attachments as expected. During the investigation, we could see that for our client the `getAttachmentContentAsync` call hanged infinitely.
Internally, we are unable to reproduce the issue on any of our local machines. It seems that this issue is only present for a specific client. 

## Useful logs
In the network tab we can see there are many `GetFileAttachment` requests and all of them have the 200 status. This looks suspicious considering that there's only one attachment in the email.
![Screenshot 2024-09-06 at 17 54 06](https://github.com/user-attachments/assets/634e9a87-92c9-41f9-9c30-f8360ef00d45)

**Comment by Suntechnick** [comment]
Our client continued with their troubleshooting and found another problem with the `getAttachmentContentAsync` API. The request resolves with the `"succeeded"` status, but the attachment content is just an empty string, which is not expected.
![image](https://github.com/user-attachments/assets/33c1599a-d154-44df-ba2d-80edea89a37f)

**Comment by kumarshrey-msft** [comment]
We are unable to reproduce this scenario at our end. A few queries: 

1. ⁠What type of attachment is this. (for example a PDF, Word Document, image etc.)
2. What is the size of the attachment for which this scenario is reproducible?
3. Is the item on which this API is being invoked encrypted?
4. Is Outlook Web the only platform on which the user is seeing this, or does it happen on New & Classic Windows Outlook as well?

**Comment by Suntechnick** [comment]
1. As you can see on the latest screenshot, the attachment is a Word file.
2. The size is around 1.1Mb
3. Not sure what this is and how it can be checked. Please, provide us some instructions for this.
4. Our client only using the Outlook on the Web and, unfortunately, using other platforms is not an option for them.

**Comment by jsiess77** [comment]
Hi, I am the client experiencing the problem.

1. Word Document (.docx)
2. 1147655 bytes
3. the file is not encrypted
4. I have no way to reproduce this issue in the local client as the web add-in we are implementing is only going to be used for Exchange online web access, web-based add-ins are blocked for native clients and New Outlook is also blocked in our organization.  

I will note that if I disable the web add-in we are troubleshooting from scanning the document, the attachment successfully sends.

**Comment by exextoc** [comment]
@Suntechnick We are not able to reproduce it on our end. Please list down steps that we can follow and reproduce the issue. Be elaborate, include all the steps involved that we can follow and reproduce the scenario.

**Comment by Suntechnick** [comment]
Out client is able to consistently reproduce the issue using the browser console and just running two API calls `getAttachmentsAsync` and `getAttachmentContentAsync`.

To be more specific, these are the steps taken:
1. Have the compose-mode taskpane add-in installed
2. Open compose mail screen, add an attachment
3. Open the taskpane
4. On the taskpane area, right click -> Inspect
5. On the browser console, make the `getAttachmentsAsync` call
6. Using the attachmentId from the previous call, use it to make the `getAttachmentContentAsync` call

As I stated earlier, we are unable to reproduce this issue among the development team and for us everything is working normally. Since the issue is only present for one specific client, is it possible that the cause could be related to something outside the add-in? (e.g., Exchange Server)

**Comment by jsiess77** [comment]
I've performed this procedure several times with various file types: pdf, docx, and xlsx either attached from Onedrive or attached from the local file system.  

Office.context.mailbox.item.getAttachmentsAsync((response) => console.log(response)) returned the id and Office.context.mailbox.item.getAttachmentContentAsync(attachmentId, (response) => console.log(response)) with attachmentId replaced by the id in either single or double quotes returns a status of "succeeded" with the content as ""

![image](https://github.com/user-attachments/assets/306d157b-f805-4d71-a6d7-3b783965783e)

**Comment by Swathy-Mothilal** [comment]
@Suntechnick Are you trying to invoke the API "getAttachmentContentAsync" and "getAttachmentsAsync" API concurrently for your use case?

In that case, there is a possibility that "getAttachmentContentAsync" is not waiting for the previous API "getAttachmentsAsync" to complete and fetch the content. Try to use some observable pattern and wait till the previous API completes and then invoke "getAttachmentContentAsync"?

**Comment by Suntechnick** [comment]
@Swathy-Mothilal we are making the `getAttachmentContentAsync` call after the `getAttachmentsAsync` call successfully completed and yielded the result containing attachments list.
As you can see on the screenshots from @jsiess77 , it's not an issue with async flow and `getAttachmentContentAsync` call resolves with empty attachment content, which is not expected.

**Comment by Swathy-Mothilal** [comment]
@Suntechnick Thanks for the info. Could you please share your add-in manifest and host the add-in in a private repository?Kindly Grant access to @exextoc
