### ISSUE TITLE
[excel] Ribbon Button Can use ExecuteFunction to get excel range cell

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#487]
hi

if i click the ribbon button. it's support get selected range of current sheet?

i found ribbon button can use ExecuteFunction ,and it can open dialog. but i found it can not Interaction with excel. it's really?

![image](https://user-images.githubusercontent.com/3963826/56843407-de174a80-68d2-11e9-802a-6fbc2fa45f04.png)

**Comment by tutieu** [comment]
The Execute function can call all Excel JaveScript APIs. You need to add functions to Function File which is defined in Manifest.  See

 https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-core-concepts to write an Excel Function and reference https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-ranges to get how to get select range.
