### ISSUE TITLE
OfficeRuntime.auth.getAccessToken works in outlook classic but throws error 13012 on outlook new and OWA

### ISSUE THREAD

**Issue by kdeshpande-methodcrm** [OfficeDev/office-js#4873]
# Provide required information needed to triage your issue
We have followed all the steps to register an outlook add-in mentioned here - https://learn.microsoft.com/en-us/office/dev/add-ins/develop/register-sso-add-in-aad-v2 and since we developed the add-in using dotnet, we referred the documentation here - https://learn.microsoft.com/en-us/office/dev/add-ins/develop/create-sso-office-add-ins-aspnet . Our add-in is sideloaded, so we are not passing forMSGraphAccess : true . Following is our code for reference, this is inside office.initialize - 

var _mailbox = Office.context.mailbox;
OfficeRuntime.auth.getAccessToken({ allowConsentPrompt: true, allowSignInPrompt: true })
  .then((successResult) => {
      // SSO token received successfully
  },
(failureResult) => {
  // throws 13012 for OWA and outlook new
    _mailbox.getUserIdentityTokenAsync(function (asyncResult) {
        // fallback implementation as suggested by MS
    });
});

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web, Outlook new
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft Outlook Version [1.2024.829.100], WebView2 Version is 128.0.2739.67
* Operating System: Windows
* Browser (if using Office on the web): Chrome, Firefox
 
## Expected behavior

Should fetch SSO token for outlook on web as well as outlook new

## Current behavior

OfficeRuntime.auth.getAccessToken throws error 13012 on outlook on the web and outlook new. Instead, it should fetch the SSO token similar to how it does in Outlook classic

## Steps to reproduce

Following is our code for reference, this is inside office.initialize - 

var _mailbox = Office.context.mailbox;
OfficeRuntime.auth.getAccessToken({ allowConsentPrompt: true, allowSignInPrompt: true })
  .then((successResult) => {
      // SSO token received successfully
  },
(failureResult) => {
  // throws 13012 for OWA and outlook new
    _mailbox.getUserIdentityTokenAsync(function (asyncResult) {
        // fallback implementation as suggested by MS
    });
});

## Context

We have to fallback on the classic way of getting accessToken from MS. As per MS, this will be turned off in October and we would not be able to use outlook add-in if that happens since our fallback will also be not working.

## Useful logs

- [ 
![image](https://github.com/user-attachments/assets/6fa1a132-307a-4cf7-951f-5a3eef55bcb4)
] Console errors

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by rkpathak** [comment]
@kdeshpande-methodcrm What kind of test account are you using to test this, is it Consumer or Business?

**Comment by kdeshpande-methodcrm** [comment]
@rkpathak I tested with Consumer accounts

**Comment by kdeshpande-methodcrm** [comment]
@rkpathak any update on this? Or is there any changes that we would need to do on our end?

**Comment by exextoc** [comment]
@kdeshpande-methodcrm getAccessToken/getAccessTokenAsync API is not supported for consumer accounts.
