### ISSUE TITLE
XLMiner Analysis Toolpak Not Loading in Excel Online

### ISSUE THREAD

**Issue by aaroncengage** [OfficeDev/office-js#4876]
# We are running WOPI as part of CSPP, delivering Excel Online to users in our platform.  The XLMiner Analysis Toolpak is available to all users that access Excel Online in our platform.  The ToolPak should be accessible under the 'Commands' section of the Toolbar (by clicking on the three dots shown the screenshots).  For some students/sessions, the XLMiner app is not loading and we cannot determine why as we cannot repro it on our own machines.  
![2024-09-04_12h24_44](https://github.com/user-attachments/assets/33f42e60-85ec-4a25-9188-18d35bc057b0)
![2024-09-04_12h24_36](https://github.com/user-attachments/assets/6fc0cb1d-c265-4b1f-a572-4798d6e25982)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: ___Office on the web___
* Host [Excel, Word, PowerPoint, etc.]: __Excel____
* Office version number: ___16.0.18103.42303___
* Operating System: ___Windows___
* Browser (if using Office on the web): _Chrome_____
 
## Expected behavior
Students should be able to access the XLMiner Analysis Toolpak from within the Ribbon.  

## Current behavior
The Toolpak does not load as an option to add to the Excel Online sheet.   Our own internal teams cannot repro this issue, as it seems to only be affecting certain student users.

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)
1. https://excel.officeapps.live.com/x/_layouts/xlviewerinternal.aspx?ui=en-us&rs=en-us&WOPISrc=https%3A%2F%2Fwopi.cengage.com%2Fservices%2Fv1%2Fspreadsheet%2Fwopi%2Ffiles%2F1ea94atil%21o7gg%211i6sp6hfq%21281j%21t&access_token=0000m0pqwdva-0bcif2q-1&sftc=1&sc=https://ng.cengage.com&host_install_addins=%5B%7B%22addinId%22%3A%22wa104379190%22%2C%22type%22%3A%22TaskPaneApp%22%7D%5D
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by shanshanzheng-dev** [comment]
Hi @aaroncengage Thanks for reporting this issue, we'll take a look and report back if we have a suggestion for you. Thanks.

**Comment by shanshanzheng-dev** [comment]
Hi @aaroncengage Thanks for reporting this  issue, seem this is a known issue and we have fixed it last week, https://github.com/OfficeDev/office-js/issues/4849. Could you try to re-install this add-in? if your users still repro this issue, could you share us a sessionId? Thanks a lot.
