### ISSUE TITLE
For custom functions on web version of excel does not show any help regarding parameters

### ISSUE THREAD

**Issue by vivek-insight** [OfficeDev/office-js#4878]
We have created custom functions for excel. When we add a new function on Excel desktop using the Excel Function Arguments window (fx) or write the formula in cell we are getting help regarding formulas parameters. But when we do same in Excel Web we are not getting any help regarding parameter. I am currently using manifest file reference from shared folder.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel Web (Chrome edge)
* Office version number: Office for web
* Operating System: Windows
* Browser (if using Office on the web): YES
 
## Expected behavior
Excel Web should display custom function parameters on Function Argument popup as shown in Excel desktop. 
![Excel_Desktoppopup](https://github.com/user-attachments/assets/838dd953-645d-4195-875a-464592df7682)

Or if this is not possible then at least we should get parameter help when writing formula on cell as we are getting in Excel desktop.
![Excel_desktop](https://github.com/user-attachments/assets/1aaf1c03-7e0e-4510-9b70-f9c8b8874c25)

## Current behavior
We are not getting help regarding formula parameters on Excel Web 
![Excel_WebPopup](https://github.com/user-attachments/assets/9d6b47c2-a5bc-433f-ba48-6d72decf03d7)
![Excel_web](https://github.com/user-attachments/assets/3991d730-0d45-472a-8746-3e927576c613)

## Steps to reproduce

1. Create and build the yo office custom function with reactjs.
2. Upload manifest file on excel web
3. Add custom function, now you can notice that we are not getting any help with parameters.

**Comment by shanshanzheng-dev** [comment]
Hi @vivek-insight Thanks for reporting this issue. could you share us your test code or manifest so that we can repro your issue? Thanks.

**Comment by vivek-insight** [comment]
Hi @shanshanzheng-dev please find attached manifest file
[manifest..zip](https://github.com/user-attachments/files/16988738/manifest.zip)

**Comment by shanshanzheng-dev** [comment]
Hi @vivek-insight Thanks, we'll take a look and report back if we have a suggestion for you.

**Comment by shanshanzheng-dev** [comment]
Hi @vivek-insight We're working on this feature. We'll update progress once it deploys to production. Thanks.

**Comment by XuanZhouMSFT** [comment]
Hi @vivek-insight, thanks for the waiting. The fixes should be available in build >= 16.0.18125.42302 in Excel online. Please have a try. Feel free to let us know whether it still repro on your side. Thanks so much.
