### ISSUE TITLE
[excel] in mac can not work ,but in windows it's fine

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#488]
hi

my excel add-in  in window,it's ok,but i install in mac. it's nothing data render in excel.

i use beta office.js, it's not support in mac?
https://appsforoffice.microsoft.com/lib/beta/hosted/office.js

my mac excel version.
![image](https://user-images.githubusercontent.com/3963826/56845597-6ce98e80-68f6-11e9-805a-19c6ba47f743.png)

**Comment by tutieu** [comment]
Please try the latest version of office.js 
https://appsforoffice.microsoft.com/lib/1/hosted/Office.js

Also the latest document to update the manifest:
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/update-your-javascript-api-for-office-and-manifest-schema-version

**Comment by dinglicoding** [comment]
@tutieu  thanks，but textbox only in beta of office.js.

**Comment by grangeryy** [comment]
Sorry for the inconvenience. currently, Beta office.js doesn’t support MAC.
