### ISSUE TITLE
attachment id coming in GUID format  via office js(Office.context.mailbox.item.getAttachmentsAsync)

### ISSUE THREAD

**Issue by soumyamondal-accenture** [OfficeDev/office-js#4881]
We are developing an web addin for Outlook platforms using Office js framework , wherein we extract the attachment content of a composed mail .
We try to fetch the metadata(attachment Id, name, size, type) of the attachments via Office.context.mailbox.item.getAttachmentsAsync but sometimes  the attachment id comes in GUID format.
If the attachment id is received in GUID format then the respective attchment base64 content is corrupted(wither blank or in html format).

## Environment
* Platform : OWA,new thick client.
* Host : Outlook
* Operating System:Windows 11,Mac
* Browser (if using Office on the web): Google chrome, iMicrosoft Edge
 
## Expected behavior
The attchment id extracted via should not be coming in GUID format.

## Current behavior
We try to fetch the metadata(attachment Id, name, size, type) of the attachments via Office.context.mailbox.item.getAttachmentsAsync but sometimes  the attachment id comes in GUID format.
If the attachment id is received in GUID format then the respective attchment base64 content is corrupted(wither blank or in html format).

## Steps to reproduce
Compose a new email
Add reipcients
Add subject and body
Click on send
Once the pane(generic taskpane of office js, we are using  custom react components) is displayed with contents attach more than 4 attachments(twice happened for excel files)

# Provide additional details
below is the snippet for extracting attachment metadata that we using:-
attachmentData=Office.context.mailbox.item// we are passing to the callback
export const fetchAttachments = async (attachmentData) => {
  return new Promise((resolve, reject) => {
    attachentData.getAttachmentsAsync(function (asyncResult) {
      /* Handle success or error.*/
      if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
        console.error("fetchAttachments:Failed to get attachments. " + JSON.stringify(asyncResult.error));
        reject(JSON.stringify(asyncResult.error));
      }

      resolve(asyncResult.value);
    });
  });
};

## Context

We are developing features where we plan to validate the attachments added as part of the  our addin, in order to achieve that we  need to extract the attachment content, but in this particular scenario when the attchment id comes as GUID, then the corresponding base64 content of the attchment is corrupted(either comes as html/empty/on decoding we find its not the actual attachment content).

## Useful logs

PFA for screenshots,
<img width="808" alt="Screenshot 2024-09-11 204332" src="https://github.com/user-attachments/assets/b2f48e70-5639-4010-b64b-d01d18e4a2c7">

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends. 
<img width="808" alt="Screenshot 2024-09-11 204332" src="https://github.com/user-attachments/assets/058f38b9-d1e9-4cdb-8f1e-05e7202df6fe">

**Comment by kumarshrey-msft** [comment]
Hi @soumyamondal-accenture, 
I was unable to repro the scenario at my end. Can you share the addin that we can side load for testing this scenario? You can create a private repo and share it with @exextoc
