### ISSUE TITLE
Enable browser extensions in Excel Desktop app (WebView2)

### ISSUE THREAD

**Issue by christian-sap** [OfficeDev/office-js#4884]
We use Redux in our add-in web app. For development and support the Redux dev tools browser extension (https://microsoftedge.microsoft.com/addons/detail/redux-devtools/nnkgneoiohoecpdiaponcejilbhhikei) is very useful.

Unfortunately when using dev tools in Windows Desktop (WebView2) my installed browser extensions are not shown.

Would be great to enable browser extensions in Excel Desktops WebView2.

**Comment by shanshanzheng-dev** [comment]
Hi @christian-sap Thanks for reaching us. we'll take a look and report back if we have a suggestion for you.

**Comment by emmasab** [comment]
@christian-sap Thank you for suggestion, please submit this feature request on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Suggestions on Tech Community will be considered when we go through our planning process.
