### ISSUE TITLE
Developing an Excel Add-in with a Timer that Accounts for Visibility Changes

### ISSUE THREAD

**Issue by TarviksTheDev** [OfficeDev/office-js#4885]
I am creating an Excel add-in using React and Office.js that tracks the amount of time a user spends working in an Excel sheet. I want the timer to pause when the Excel window is minimized or when the user switches to another window or tab, but it continues to run even when the Excel window is inactive.
**Steps to Reproduce:**

1. Build an Excel add-in with React that includes a timer that increments every second to track the time spent working in Excel.
2. Detect when the `document.visibilitychange event` occurs and pause the timer when the window is minimized or when the user switches to another window or tab.
3. Start the timer, open the add-in in Excel, and then minimize the Excel window or switch to another application/tab.

**Expected Behavior:**
The timer pauses when the Excel window is minimized or when the user switches to another application or tab, and resumes when Excel regains focus or becomes active again.

**Actual Behavior:**
The timer continues to run even when the Excel window is minimized or the user switches to another application. The `visibilitychange event` does not detect when the Excel window becomes inactive in the add-in context.

**Comment by duane-j-wagner** [comment]
Have you tried
`await context.workbook.worksheets.onActivated.add(
            this.onSheetActivated);`
and onSheetDeactivated?

**Comment by shanshanzheng-dev** [comment]
Hi @duane-j-wagner Thanks for your help. @TarviksTheDev could you try this? we'll also take a look and report back if we have a suggestion for you.

**Comment by TarviksTheDev** [comment]
Dear @duane-j-wagner  and @shanshanzheng-dev  ,

Thank you for your valuable time and assistance with my previous query regarding the timer functionality in my Excel add-in.

While I've successfully implemented the suggested solution using `context.workbook.worksheets.onActivated.add( this.onSheetActivated);` and `onSheetDeactivated`, I've encountered limitations in its effectiveness. The timer currently pauses only when switching between sheets within the same Excel workbook, but I need it to pause when the Excel window is minimized or when the user transitions to another application or tab.

I'm seeking alternative approaches or technologies that can accurately detect Excel's inactivity. I'm open to exploring different frameworks or solutions, as long as they provide a robust and reliable method for pausing the timer in these scenarios.

Thank you again for your continued support and expertise. I look forward to your insights and potential solutions.

**Comment by XuanZhouMSFT** [comment]
Hi @TarviksTheDev, thanks for waiting and reporting your scenarios. Unfortunately we don't have a perfect solution to unblock you right now. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)
