### ISSUE TITLE
Performance issue for Outlook Add-in

### ISSUE THREAD

**Issue by neso613** [OfficeDev/office-js#489]
Hi
I am developing Outlook web add-in. This add-in support multi language support like French,Dutch,German,Spanish etc. As per selected language, the UI content is converted into respective language. Also, Office.context.mailbox.displayNewAppointmentForm() used to create new appointment with saved settings. 

## Expected Behavior
New appointment should open rapidly.

## Your Environment
* Platform-- [PC desktop, Mac, Office Online]

## Useful logs
Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.

NOTE: I have tried Office.onReady() too. It do not solve the issue.

Looking for help.

**Comment by exextoc** [comment]
You have added "Expected Behavior" but it is not clear from your post what is "Current Behavior". Can you please describe what is the current behavior you are observing? Does the addin functionality work as expected but is it slow? Which platform you are seeing this slow performance?

**Comment by neso613** [comment]
> You have added "Expected Behavior" but it is not clear from your post what is "Current Behavior". Can you please describe what is the current behavior you are observing? Does the addin functionality work as expected but is it slow? Which platform you are seeing this slow performance?

Current Behavior->
Outlook add-in is very slow. When I clicked on any add-in command( add-in command have dropdown with 2 options say "Setting" and "Schedule Meeting"), it shows processing in outlook client and do not perform any action( do not show/open window).

I have used Vorlon for debugging. On vorlon, I have seen this error-
Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.

**Comment by exextoc** [comment]
Thanks for explaining the current behavior. Are you trying this in on Outlook Win32 or Outlook Web or Outlook Client on Mac platform?

**Comment by neso613** [comment]
> Thanks for explaining the current behavior. Are you trying this in on Outlook Win32 or Outlook Web or Outlook Client on Mac platform?

This is for all i.e. Outlook client for Mac, windows and OWA.

**Comment by exextoc** [comment]
Thanks for confirming that you are observing this behavior on all platforms. We are looking into this. 

1. Can you please share your addin code so that we can repro this exact scenario in-house? Since it is performance related issue, it is best to look at actual code without making any assumptions. We are able to use Office.context.mailbox.displayNewAppointmentForm() and form opens immediately without any delay in our internal test addin.

2. If you try using any other APIs (and remove displayNewAppointmentForm related code), do you still performance issue in your addin?

**Comment by neso613** [comment]
> Thanks for confirming that you are observing this behavior on all platforms. We are looking into this.
> 
> 1. Can you please share your addin code so that we can repro this exact scenario in-house? Since it is performance related issue, it is best to look at actual code without making any assumptions. We are able to use Office.context.mailbox.displayNewAppointmentForm() and form opens immediately without any delay in our internal test addin.
> 2. If you try using any other APIs (and remove displayNewAppointmentForm related code), do you still performance issue in your addin?

Can I privately share the code with you. Will you please share your email id.

**Comment by exextoc** [comment]
@nehasoni3 Sorry, we cannot share email-id. Is it possible for you to remove business logic and create a minimal add-in code for repro purpose and host it on github?

**Comment by nehasoni3** [comment]
> @nehasoni3 Sorry, we cannot share email-id. Is it possible for you to remove business logic and create a minimal add-in code for repro purpose and host it on github?

sure. I'll try to update the add-in code soon.
