### ISSUE TITLE
Office.context.mailbox.item.internetMessageId is empty

### ISSUE THREAD

**Issue by markb-trustifi** [OfficeDev/office-js#49]
## Current Behavior
When sending emails from Windows 7 Outlook 2013 and opening in the same Outlook the "Office.context.mailbox.item.internetMessageId" is empty.

When sending emails from Outlook Online and opening in Outlook 2013 on the same PC it is OK.
When sending emails from Outlook 2013 and opening in Outlook Online on the same PC it is OK.
When sending emails from any other outlook and opening in Windows 7 Outlook 2013 it is OK.
When sending emails from Windows 7 Outlook 2013 and opening in any other Outlook it is OK.

## Steps to Reproduce, or Live Example
Send email form Outlook 2013, Windows 7 and open it on the same Outlook version.
Validate field: Office.context.mailbox.item.internetMessageId

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2013
* Operating System: Windows 7

## Screenshot
![screen shot 2018-01-14 at 17 43 31](https://user-images.githubusercontent.com/29097494/34917687-7d9383ea-f952-11e7-85a8-bbdce8ea78c9.png)

**Comment by markb-trustifi** [comment]
The InternetMessageId exists when I retrieve it by Office REST API:
https://outlook.office365.com/api/v2.0/me/messages/{restItemId}?$select=InternetMessageId

**Comment by exextoc** [comment]
@markb-trustifi What version of Outlook 2013 are you using?

**Comment by exextoc** [comment]
Are running the add-in from the item in Sent Items, or from the received message in the Inbox (after sending a message to yourself)?
