### ISSUE TITLE
How to set the UTC corrected Date for inputing into function displayNewAppointmentForm() for Outlook add-in

### ISSUE THREAD

**Issue by neso613** [OfficeDev/office-js#490]
I am developing Outlook Web Add-in. I have used displayNewAppointmentForm() to create appintment programtically.  I have used this code--
` var start = new Date();
  var end = new Date();
  end.setHours(start.getHours() + 1);
Office.context.mailbox.displayNewAppointmentForm(
{
 start:start,
end:end
});`

this create time zone issue while scheduling appointment with overseas persons.

I have searched for this issue, found that start and end time should be UTC corrected.
For that, I have used this code
` var start = new Date();
  var end = new Date();
  end.setHours(start.getHours() + 1);
  var UTCCorrectStartDate = start.toUTCString()
  var UTCCorrectEndDate = end.toUTCString()
Office.context.mailbox.displayNewAppointmentForm(
{
 start:start,
end:end
})`

But then, it shows me some errorwhile debugging on Vorlon--
Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.

Please suggest me the right way to do this.

**Comment by exextoc** [comment]
@nehasoni3 We tried following code in OWA, it seems to be working fine for us.

```
var start = new Date();
var end = new Date();
end.setHours(start.getHours() + 1); 
var UTCCorrectStartDate = start.toUTCString();
var UTCCorrectEndDate = end.toUTCString();
Office.context.mailbox.displayNewAppointmentForm( { start:start, end:end });
```

Can you please tell us what happens when API is called? Any other error (on console) or popup seen?

**Comment by neso613** [comment]
> @nehasoni3 We tried following code in OWA, it seems to be working fine for us.
> 
> ```
> var start = new Date();
> var end = new Date();
> end.setHours(start.getHours() + 1); 
> var UTCCorrectStartDate = start.toUTCString();
> var UTCCorrectEndDate = end.toUTCString();
> Office.context.mailbox.displayNewAppointmentForm( { start:start, end:end });
> ```
> Can you please tell us what happens when API is called? Any other error (on console) or popup seen?

 Please confirm me, I should use `Office.context.mailbox.displayNewAppointmentForm( { start:start, end:end });` or `Office.context.mailbox.displayNewAppointmentForm( { start:UTCCorrectStartDate , end:UTCCorrectEndDate  });`


On console screen (vorlon), it shows--
Sys.ArgumentTypeException: Object cannot be converted to the required type. Parameter name: start
Sys.ArgumentTypeException: Sys.ArgumentTypeException: Object cannot be converted to the required type. Parameter name: start at window.OSF.DDA.OutlookAppOm.throwOnArgumentType (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:15:169260) at u.DDA.OutlookAppOm.prototype._displayNewAppointmentFormApi$p$0 (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:15:180713) at Anonymous function (https://ajax.aspnetcdn.com/ajax/3.5/MicrosoftAjax.js:5:298) at openScheduleMeeting (https://localhost:3000/function-file/function-file.js:343:5) at scheduleMeeting (https://localhost:3000/function-file/function-file.js:310:5) at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:15:141600)

**Comment by kanaksony** [comment]
Hello @Rick-Kirkham @exextoc Do we have any update on this? :)

**Comment by exextoc** [comment]
@nehasoni3 You should be using this code:

`Office.context.mailbox.displayNewAppointmentForm( { start:start, end:end })`

Please let us know if this is not working as expected. If expected behavior is not seen, please tell us what you are observing? Does the appointment form open?

**Comment by neso613** [comment]
> @nehasoni3 You should be using this code:
> 
> `Office.context.mailbox.displayNewAppointmentForm( { start:start, end:end })`
> 
> Please let us know if this is not working as expected. If expected behavior is not seen, please tell us what you are observing? Does the appointment form open?

It works!!
Everything works fine and expected.
Thank you for support.
