### ISSUE TITLE
How to tell the difference between a cell that has no color fill and a cell that has white color

### ISSUE THREAD

**Issue by SirDavenport** [OfficeDev/office-js#4900]
When you fill a cell with white in Excel, it is different than doing no fill. There doesn't seem to be a way to tell the difference when using officejs. They both have null for format.fill.pattern, and they both have #FFFFFF for format.fill.color. Is there a way to do this, or is this a bug?

**Comment by XuanZhouMSFT** [comment]
@SirDavenport Thanks for the waiting. You can try load the "tintAndShade" properties. Please refer to this document: https://learn.microsoft.com/en-us/javascript/api/excel/excel.rangefill?view=excel-js-preview#excel-excel-rangefill-tintandshade-member.
If you are setting "No Fill", you will get "null". And if you fill as white or other color, you will get a number.
Please let me know if it meet your requirements. Thanks
