### ISSUE TITLE
Office.context.mailbox.item.bcc.setAsync not working on older versions of Outlook Desktop for Windows

### ISSUE THREAD

**Issue by mariovelandiacm8** [OfficeDev/office-js#4902]
# Provide required information needed to triage your issue

When using an Outlook Add-in on Microsoft 365 version 16.0.13530.20424 or later, with Edge WebView2 installed on Windows 10, this function is not working properly

```js
// Add BCC if email doesn't exist in results.value
// result is the parameter returned by Office.context.mailbox.item.bcc.getAsync
// The result contains the current BCC recipients in result.value (an array of email objects)
result.value.push({ emailAddress: "foo@bar.com" });
Office.context.mailbox.item.bcc.setAsync(
  result.value,
  (asyncResult) => {
    if (asyncResult.status === Office.AsyncResultStatus.Failed) {
      console.error(
        'Failed to set BCC. Error: ' + asyncResult.error.message
      );
    } else {
      updateButtonText(); // Update button after adding
    }
  }
);
```

The add-in functions properly in Outlook for web browsers, Outlook for Mac Desktop, and the new Outlook for Windows Desktop.

These are the requirements used in the manifest:

```xml
<Hosts>
  <Host Name="Mailbox"/>
</Hosts>
<Requirements>
  <Sets>
    <Set Name="Mailbox" MinVersion="1.1"/>
  </Sets>
</Requirements>
...
<VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
  <Requirements>
    <bt:Sets DefaultMinVersion="1.3">
      <bt:Set Name="Mailbox"/>
    </bt:Sets>
  </Requirements>
  ...
</VersionOverrides>
```
I attempted to change the DefaultMinVersion to 1.1, but this is currently blocked by this [issue](https://github.com/OfficeDev/office-js/issues/4893)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Old Outlook Desktop for Windows
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.13530.20424 or later
* Operating System: Windows 10
* Browser (if using Office on the web): ______
 
## Expected behavior
The `Office.context.mailbox.item.bcc.setAsync(recipients, callback)` sets properly the bcc field in old Outlook for Desktop on Windows as it does on other platforms

## Current behavior
the callback function in 

```js 
Office.context.mailbox.item.bcc.setAsync(recipients, callback)
``` 
with the following signature:

```js
(asyncResult: Office.AsyncResult<void>) => void
```
is receiving an `asyncResult` object in the callback with the following structure:

```json
{
  asyncResult: OSF.DDA.AsyncResult,
  error: OSF.DDA.Error,
  code: 5001
}
```

## Steps to reproduce

1. Use the `Office.context.mailbox.item.bcc.setAsync` function in an Add-in for Outlook.
2. Use console.error for debugging.
3. Sideload the add-in into Outlook through web Outlook.
4. Use the old Outlook Desktop for Windows 10 (version 16.0.13530.20424 or later).
5. The console will show `Failed to set BCC. Error: An internal error has occurred`.

## Context

I'm trying to set a fixed BCC email when the user clicks on the button `Add BCC`. That button updates to `Remove BCC` if the fixed BCC email already exists in the BCC recipients list.

## Useful logs

- [ ] Console errors
- [x] Screenshots
    - Old Outlook Desktop for Windows 
![Console](https://github.com/user-attachments/assets/43b3b4c1-7482-40aa-94f1-b35106783067)
    - Outlook for Google Chrome on MacOS
  
 https://github.com/user-attachments/assets/d35e6abc-14f5-401f-ad8e-2900bf497966
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by Oleg-O** [comment]
Indeed, it appears that this does return 5001 error:

```
         result.value.push({ emailAddress: "foo@bar.com" });
```

But either of these work:

```
         result.value.push("foo@bar.com");
         result.value.push( {emailAddress:"foo@bar.com", displayName: "Foo Bar" } );
```

I believe this is expected - [the API](https://learn.microsoft.com/en-us/javascript/api/outlook/office.recipients?view=outlook-js-preview#outlook-office-recipients-setasync-member(2)) expects either a string which is interpreted as an SMTP address, or an EmailUser or EmailAddressDetails object with both emailAddress and displayName properties present.

Does this help?
