### ISSUE TITLE
Opening word document from dialog

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4905]
I have build dialog using office dialog API.

This dialog displays office documents. When user select any document, I want to open that in new tab.

I used API context.application.createDocument(fileContent) for the same. 
var doc = context.application.createDocument(fileContent) ;
doc.open();

but no tab gets opened.  I see above 2 lines get executed successfully. Same code works fine if I call it from taskpane.

**Comment by michelleranmsft** [comment]
Hi @ishanig11 - could you provide more detail on your environment, specifically (1) the host Office application and (2) platform that this issue is occurring on? This will help us find the right person to answer your question.

**Comment by ishanig11** [comment]
I am using online word.

**Comment by shanshanzheng-dev** [comment]
Hi @ishanig11 Based on this reference: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins, The messageParent function is one of only two Office JS APIs that can be called in the dialog box. The other JS API that can be called in the dialog box is Office.context.requirements.isSetSupported. So we don't support to context.application.createDocument(fileContent) on dialog. 
We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.    [Microsoft 365 Developer Platform - Microsoft Community Hub](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform)
