### ISSUE TITLE
Unable to Fetch Matching StoreID in Office JS Add-In

### ISSUE THREAD

**Issue by kvnsairaamreddy** [OfficeDev/office-js#4907]
We currently have an existing Outlook desktop COM add-in that we are rewriting using Office JS. In our old add-in, we store the StoreID along with other properties when a meeting or appointment is created in Outlook. This StoreID is critical for our business logic.

However, in our new add-in using Office JS, we are unable to fetch an ID that matches the StoreID from the old add-in. We need to either fetch the same StoreID or find a way to map to it appropriately.

### Attempted Approaches
  Using EWS to Fetch StoreID:
  
  We have used the GetItem and GetFolder EWS operations to try and fetch the PR_STORE_ENTRYID property.
  Despite specifying the PropertyTag for PR_STORE_ENTRYID (0x0FFB), the retrieved ID does not match the one from the old add-in.

### Expected Result
We are hoping to retrieve the same StoreID or find an appropriate ID mapping that matches the StoreID used in our old add-in.

### Request
Could someone with expertise in EWS, Office JS, or Outlook add-ins provide guidance on how to correctly fetch the StoreID in the new add-in? Any insights or alternative approaches would be greatly appreciated.

Thank you in advance!

**Comment by Swathy-Mothilal** [comment]
@kvnsairaamreddy Thank you for your question. We're currently looking into it and will keep you posted

**Comment by Swathy-Mothilal** [comment]
Hi @kvnsairaamreddy, unfortunately we don't have any equivalent of StoreID in Office JS Add-in. Preferably you store the immutable ID instead of the StoreId.

**Comment by kvnsairaamreddy** [comment]
@Swathy-Mothilal thanks for the confirmation, actually in our old implementation, for our use case, I believe we were making use of this StoreID for meetings to identify the original calendar from where the data was contributed so that it can only be updated/deleted from the same calendar, is there any available id which can be used to fulfill this use case

**Comment by Swathy-Mothilal** [comment]
Hi @kvnsairaamreddy  For your use case, please verify if the itemId mentioned [Refer - https://learn.microsoft.com/en-us/javascript/api/outlook/office.appointmentread?view=outlook-js-1.11&preserve-view=true#outlook-office-appointmentread-itemid-member] meets your needs. The itemId uniquely identifies the meeting, allowing you to update or delete it from the calendar.

**Comment by kvnsairaamreddy** [comment]
Hi @Swathy-Mothilal actually in our existing implementation, we are using combination of StoreId+EntryId as a way to identify the meeting and confirm the source calendar from where the data was initially contributed and we were planning to do the same in our new implementation as well, currently to fetch the EntryId in office js, we are extracting it from the itemId by removing few characters at the start and end.
Can you please confirm if this whole itemId will be different for different users/calendar so that we can use it identify the item while confirming the source as well.

**Comment by Swathy-Mothilal** [comment]
@kvnsairaamreddy The identifier returned by the itemId property is the same as the Exchange Web Services item identifier. Kindly refer to https://learn.microsoft.com/en-us/exchange/client-developer/exchange-web-services/ews-identifiers-in-exchange#working-with-identifiers and make sure your business use case fits in it.

**Comment by kvnsairaamreddy** [comment]
Hi @Swathy-Mothilal sorry for the delay in replying here. we have made some changes to our approach such that even using only itemId works for us, but we are having an issue with the itemId as well, when we are trying to create a new appointment, when the user saves/sends appointment invite, we need to store this itemId, Unique id along with a few details from the addin in our database for future use, but since itemId is generated after an item is saved, we are unable to store this id.

We also tried saving the appointment in OnAppointmentSend event trigger, but when we are doing that it is throwing an error like "The send or update operation could not be performed because the change key passed in the request does not match the current change key for the item" can you please suggest what to do here. 

Thanks in advance

**Comment by neprasad-microsoft** [comment]
Hi @kvnsairaamreddy 
Which API is returning this error? Please share a sample add-in and logs with us for faster debugging - [Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues](https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues) . 
You can share both on a private Github repo. 

Also, did you try a saveAsync API call (https://learn.microsoft.com/en-us/javascript/api/outlook/office.appointmentcompose?view=outlook-js-1.4&preserve-view=true#outlook-office-appointmentcompose-saveasync-member(2)) before calling the getItemIdAsync API?

**Comment by kvnsairaamreddy** [comment]
Hi, earlier this issue was consistently replicated, almost 50% of the time, but for some reason it seems to be fixed now and everything is working as expected so closing this thread. Thanks for all the help
