### ISSUE TITLE
Unable to view installed add-ins on desktop version of Outlook

### ISSUE THREAD

**Issue by truchonh** [OfficeDev/office-js#4911]
# Provide required information needed to triage your issue
Add-in was installed for multiple users through the web version of Outlook. The add-in is visible and is working correctly from the web.
Some users are unable to see the add-in from the desktop Outlook app, which they normally work with.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Outlook 365 MSO (version 2407 Build 16.0.17830.20210)
* Operating System: Windows 11
* Browser (if using Office on the web): N/A
 
## Expected behavior
Outlook add-in should be visible from the ribbon when viewing an existing email or when composing a new email.

## Current behavior
No add-in are visible from the desktop app. 

## Steps to reproduce
1. Install any side-loaded add-in from the web interface
2. Open an email from the mail mailbox
3. Add-ins are not visible in the ribbon
note: We are aware that add-ins can take several hours to sync-up and be available on the desktop app. This issue is open since a few weeks, therefore waiting is not the solution.

## Link to live example(s)
Not applicable. It seems to be a compatibility issue since the add-in is working well for 99% of users on a variety of exchange/365 accounts and Outlook versions. Furthermore, the add-in is working for the affected user on the web app. The iossue is isolated to this build of Outlook.

# Provide additional details
The session id can be provided in private.

## Context
We would like to know if there is an open issue with this specific Outlook build. 

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by millerds** [comment]
Can you clarify what is meant specifically by "Add-in was installed for multiple users through the web version of Outlook"

**Comment by millerds** [comment]
@truchonh can you elaborate on what you mean by "Add-in was installed for multiple users through the web version of Outlook" and also on "note: We are aware that add-ins can take several hours to sync-up and be available on the desktop app. This issue is open since a few weeks, therefore waiting is not the solution."

**Comment by truchonh** [comment]
@millerds Hi, thanks for looking into this.
"Add-in was installed for multiple users through the web version of Outlook" -> The add-in was installed individually by each users through the side-loading url (https://aka.ms/olksideload), as opposed to having it installed through the admin center by IT.

"note: We are aware that add-ins can take several hours to sync-up and be available on the desktop app. This issue is open since a few weeks, therefore waiting is not the solution."
I was given the blanket answer "just wait longer" in the past when add-ins do not show up in Outlook. I was pointing out that the add-in was installed a long time ago and is still not visible on the desktop Outlook app for windows.

**Comment by millerds** [comment]
Thanks for the clarification.

There isn't any known issue with a particular build with regard to getting add-ins.  Can you have those users clear their add-in caches to see if that corrects things?  see: https://learn.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache#manually-clear-the-cache-in-outlook (skip the part that says to un-install the sideloaded add-in).

**Comment by millerds** [comment]
@truchonh have you been able to try clearing the cache?
