### ISSUE TITLE
Are document variable methods/properties available in Office.js?

### ISSUE THREAD

**Issue by Piyush-IT** [OfficeDev/office-js#4914]
We are currently migrating from VSTO to Office.js and need to use document variable properties in Office.js. Expected behavior is that we should be able to access these document variable properties.

Is getting and setting **document variables available** in Office.js? If not, can you suggest an alternative approach?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: _____All_
* Host [Excel, Word, PowerPoint, etc.]: .....Word______
* Office version number: ______Microsoft® Word for Microsoft 365 MSO (Version 2408 Build 16.0.17928.20114) 64-bit 
* Operating System: ______window 11
* Browser (if using Office on the web): ______chrome

**Comment by shanshanzheng-dev** [comment]
Hi @Piyush-IT Document variables aren't supported in Office.js add-ins. But you could try to follow the ways that might work for their scenario:
1. custom doc properties. there is a good sample [within Script Lab](http://aka.ms/scriptlab) that (check custom properties section). These are regular document properties and can be accessed by any Add-in activated on this document.
2. [Settings](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings). think about this as a property bag specifically for add-ins, will hold settings for each add-in instance within the document.

**Comment by pinverso** [comment]
Work around provided.

**Comment by Piyush-IT** [comment]
Thank you so much for providing work around.,

Appreciated your Work.
