### ISSUE TITLE
Loading custom functions on macOS fails consistently every 2nd time

### ISSUE THREAD

**Issue by fzumstein** [OfficeDev/office-js#4918]
## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number:  16.89.1 (24091630)
* Operating System: macOS

 
## Expected behavior
Sideloading the manifest.xml doesn't fail with `Error installing functions` in the taskbar. 

## Current behavior
Every 2nd time that I load the manifest.xml via sideloading, it fails with `Error installing functions` in the taskbar and custom functions return a `#NAME?` error.

## Steps to reproduce
1. Download manifest from https://xlwings-server.onrender.com/manifest and sideload it. You probably get the error.
2. Quit Excel completely and restart
3. sideload the manifest again, you won't get the issue and you can click on "Insert custom functions" in the taskpane and everything will work.
4. Repeat the steps again and you'll see it'll fail every 2nd time.

## Useful logs
These are the debug logs. They differ slightly when it works vs when it fails:
[fails.log](https://github.com/user-attachments/files/17099136/fails.log)
[works.log](https://github.com/user-attachments/files/17099137/works.log)

**Comment by shanshanzheng-dev** [comment]
Hi @fzumstein Thanks for reporting this issue, I'm trying to repro but not. It always load successfully.
![image](https://github.com/user-attachments/assets/f4726d99-e3f5-451b-a2a6-8b30f65c5b00)
could you share us the repro video? Thanks

**Comment by fzumstein** [comment]
Sorry about the delay, I didn't get a notification for whatever reason. You're right, I can't repro the issue anymore with the hosted URL/manifest. However, it still repros on localhost. See video: https://www.loom.com/share/63be407bbdd840cc909ddfc31903dc81?sid=a2b05f6d-53bd-40de-b9c4-618825e276ee

If you want to repro this locally, you can follow the docs here (various options, like docker compose or GH codespaces): https://server.xlwings.org/en/latest/quickstart/ You can use `noncommercial` as license key.

**Comment by fzumstein** [comment]
I currently can't repro this anymore locally. I did a few things in the meantime, so possible candidate for fixing this are:

- Deleting the cache with this additional dir, which seems to be missing in the docs `~/Library/Containers/com.microsoft.Excel/Data/Library/Application\ Support/Microsoft/Office/16.0/Wef/`
- Putting a `<Version>` tag of format `x.x.x.x` instead of `x.x.x` into the manifest
- Removed an additional manifest from the sideloading dir, which was setup in a similar way (although it had an own Id and different custom function namespace).

My bet is on the first one.
