### ISSUE TITLE
OnMessageSend event handler always opens a browser popup window

### ISSUE THREAD

**Issue by phreniq** [OfficeDev/office-js#4919]
Microsoft Outlook for Mac: Version 16.89.1 (24091630)
Mailbox DefaultMinVersion = 1.13

I have created an add-in for Outlook that attaches an event handler for the OnMessageSend LaunchEvent (Smart Alerts) via the manifest XML config below:

```
<ExtensionPoint xsi:type="LaunchEvent">
  <LaunchEvents>
    <LaunchEvent Type="OnMessageSend" FunctionName="onMessageSendHandler" SendMode="PromptUser" />
  </LaunchEvents>
  <SourceLocation resid="JSRuntime.Url"/>
</ExtensionPoint>
```

My JSRuntime.Url resourceId points to an html resource that loads the javascript event handler that services the event.  All of this works great.  The user interacts with the compose surface of my add-in, which sets some behind-the-scenes metadata about the composed email, including whether the user wants my add-in to do something upon send.  The user clicks send on their email and a little browser popup shows whatever html that exists in the JSRuntime.Url html resource for a brief moment, then it closes once the event.completed function is called.  

However, if the user never engages the compose surface of my add-in, or chooses not to allow my add-in to do something upon message send, the little browser popup shows regardless.  This is disconcerting to my test users as they think that something has happened without their knowledge.  It also just as annoying as any popup that occurs while web browsing.  

How can I prevent the web browser popup window from showing every time the user clicks Send, even when my add-in hasn't been engaged?

**Comment by exextoc** [comment]
@phreniq Could you please confirm if the issue is occurring only in Outlook for Mac? Please host the add-in in a private repository and share a video recording of the issue. Grant access to @exextoc so we can replicate the scenario for better debugging. Thank you!

**Comment by Swathy-Mothilal** [comment]
@phreniq Could you please confirm if the issue is occurring only in Outlook for Mac? Please host the add-in in a private repository and share a video recording of the issue. Grant access to @exextoc  so we can replicate the scenario for better debugging. Thank you!

**Comment by phreniq** [comment]
Thanks @exextoc @Swathy-Mothilal.  I have created a private repo and invited @exextoc as a collaborator here: https://github.com/phreniq/outlook-smart-alert.  In that repo you will find a short screen recording that details the issue I'm seeing.  Please keep this screen recording private as it does show my email address.

I am only able to test on my Mac at this time.  I have reached out to some Windows testers for info on their experience but have not heard back yet.  I will update when I get more info from them.

What I need is the ability to NOT show the web popup on every email Send.  My add-in allows the user to choose whether to track info about the email during compose mode.  Then, on Send, I look at that setting to determine if my add-in should do something.  When my add-in isn't actually doing something, I would like the ability to say "don't show the popup window because I'm not actually handling this email."  Maybe something in the OnMessageSend event handler where I can skip processing/ignore/etc.

As I mentioned in my first post, the feedback from testers has been concerning as they see the popup window even without engaging my add-in.  This leads them to believe that my add-in has actually done something with their email, even though it hasn't.  I fully understand that the office.js API in its current form doesn't make a connection between read/compose/event modes, but this all-or-nothing approach seems very heavy-handed and limits the perceived usability of add-ins, like mine, that try to encapsulate the entire read/compose/send cycle.

Your attention and response is very much appreciated!

**Comment by exextoc** [comment]
Hi @phreniq, thank you for the detailed explanation! From the video, it looks like the popup window you mentioned is the "Developer Window."

Could you please confirm if debugging is enabled on your machine? Kindly refer this doc: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/debug-autolaunch?tabs=mac.

**Comment by Swathy-Mothilal** [comment]
Hi @phreniq, thank you for the detailed explanation! From the video, it looks like the popup window you mentioned is the "Developer Window."

Could you please confirm if debugging is enabled on your machine? Kindly refer this doc at https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/debug-autolaunch?tabs=mac.

**Comment by phreniq** [comment]
Thanks, @Swathy-Mothilal.  I can confirm I got the popup window to stop showing up for my test users on Mac by having them open a Terminal and running: `defaults write com.microsoft.Outlook OfficeWebAddinDeveloperExtras -bool false`

I think its worth noting that I wouldn't expect a new user to have to do this.  Can you confirm that this setting should be disabled by default?  I'm unsure if my test users enabled it on their Macs before we started testing my add-in.

Regardless, I think it is safe to mark this issue closed.  Thanks again!

**Comment by Swathy-Mothilal** [comment]
@phreniq Thanks for confirmation. And yes, the default value of "OfficeWebAddinDeveloperExtras" is false.
