### ISSUE TITLE
Office.js has not fully loaded when network is fast and cache is clean.

### ISSUE THREAD

**Issue by neso613** [OfficeDev/office-js#492]
I am developing Outlook web add-in. I am using Office.js. I have developed custom UI to save some settings for scheduling meeting. I have designed add-in command say "Settings".When I clicked on it shows me this statement while debugging on Vorlon-->
Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.

## Expected Behavior
Outlook web add-in should open Setting UI.

## Current Behavior
It shows loading icon and in vorlon debugging ,it shows 

Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Outlook client for MAC,windows and OWA
* Host [Excel, Word, PowerPoint, etc.]: Outlook

Please suggest solution.

**Comment by exextoc** [comment]
@nehasoni3 Can you please tell us if this issue is resolved and how did you fix it?
