### ISSUE TITLE
deprecation date for getUserIdentityTokenAsync and getCallbackTokenAsync in outlook add-in

### ISSUE THREAD

**Issue by e-vidyaraghavi** [OfficeDev/office-js#4924]
Can you provide the exact date for the deprecation of these methods, we are using this in our production add-ins?
 getUserIdentityTokenAsync
 getCallbackTokenAsync

**Comment by Swathy-Mothilal** [comment]
Hi @e-vidyaraghavi, Kindly refer to this page https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/faq-nested-app-auth-outlook-legacy-tokens for updates regarding the deprecation.
