### ISSUE TITLE
Integrated Spam Reporting Icon is Off-Center in New Outlook

### ISSUE THREAD

**Issue by alamansky** [OfficeDev/office-js#4931]
When an add-in is using the `ReportPhishingCommandSurface` extension point in New Outlook, and the add-in button text wraps to a new line, the icon image specified in the manifest is slightly off-center. See the bellow screenshot, where the icon image is a 64x64 solid red square:

![integrated_spam_reporting_icon](https://github.com/user-attachments/assets/77585f0c-2ecd-4ac2-8939-9226684a4109)

Note that the icon is slightly to the left of center. Closeup:

![integrated_spam_reporting_icon_closeup](https://github.com/user-attachments/assets/e0617724-5a77-4657-9341-0670f6ba8d26)

## Your Environment

* Platform: PC desktop
* Host: Outlook
* Office version number:
  * Microsoft Outlook Version 1.2024.911.200 (Production).
  * Client Version is 20240913004.12.
  * WebView2 Version is 129.0.2792.52.
* Operating System: Windows 10
* Browser: N/A
 
## Expected behavior
The icon image specified in the manifest for an integrated spam reporting add-in should be horizontally centered in the `Report` ribbon tab when the label text wraps to a new line.

## Current behavior
The icon image specified in the manifest for an integrated spam reporting add-in is _not_ horizontally centered in the `Report` ribbon tab when the label text wraps to a new line.

## Steps to reproduce

1. Create a manifest for an integrated spam reporting add-in. No functionality is required beyond getting the reporting button icon and a multi-line reporting button label to appear in the ribbon.
2. Install the manifest in New Outlook.
3. Observe the layout in the ribbon.

**Comment by Swathy-Mothilal** [comment]
@alamansky We are unable to repro this bug. Could you please share your add-in manifest and host the add-in in a private repository? Kindly grant access to [@exextoc](https://github.com/exextoc)
