### ISSUE TITLE
Sharing the copy of a document from an office application to outlook classic does not initialize composeType

### ISSUE THREAD

**Issue by Discolai** [OfficeDev/office-js#4933]
# Provide required information needed to triage your issue
Outlook classic addins are unable to get the compose type of messages when sharing a copy of an office document to outlook.

## Your Environment

* Platform: PC
* Host: Outlook Classic
* Office version number: 16.0.17928.20156
* Operating System: Windows 11
 
## Expected behavior
`Office.context.mailbox.item.getComposeTypeAsync` should return `Office.MailboxEnums.ComposeType.NewMail`

## Current behavior
`Office.context.mailbox.item.getComposeTypeAsync` returns an AsyncResult with the following error
````json
{"name":"InternalError","message":"The operation failed.","code":5001}
````

## Steps to reproduce
 1. Open a new word document and save it to disk (do not save it to onedrive or sharepoint)
 2. Share it as a copy to outlook (File -> Share -> Attach a copy instead)
 3. Any calls to `Office.context.mailbox.item.getComposeTypeAsync` will fail in this context. Both for add ins running as a launch event and in task panes

## Context
We are currently working around this issue by logging the error and returning `Office.MailboxEnums.ComposeType.NewMail` when `Office.context.mailbox.item.getComposeTypeAsync` fails. However, this leads to a lot of noise, since this is a common use case for our users.

**Comment by millerds** [comment]
This was reported in https://github.com/OfficeDev/office-js/issues/4028 and baring any issue should be fixed in 16.0.18227.20000
