### ISSUE TITLE
NAA - Question about the October 2024 legacy exchange tokens being defaulted to "off"

### ISSUE THREAD

**Issue by cf-joshnabbott** [OfficeDev/office-js#4934]
Regarding the updates to legacy Exchange Online tokens for Outlook add-ins - 

>  Exchange online tokens are turned off by default for new tenants and existing tenants known not to be using Exchange tokens.

How is it being determined whether an existing tenant is known to be using Exchange tokens for add-ins installed via a URL. We're hoping we don't fall into the category that gets legacy tokens turned off in October 2024, as we're not quite ready for that.

<img width="1055" alt="image" src="https://github.com/user-attachments/assets/0c69f0fe-0842-4b66-b722-30612928ad26">

We will be prepared for the January 2025 cut-off.

**Comment by pinverso** [comment]
Hello!
We have telemetry that can see if an add-in is calling exchange tokens.   If we see in the telemetry that there have been calls, we will not turn off the exchange tokens within that tenant.   As there can edge cases in which our telemetry doesn't catch this call, there is the cmdlet switch that is rolling out this October that will get the tenant admin the ability to turn back on legacy tokens.

Also, please look at our FAQ for answers to our common questions:  https://aka.ms/NAAFAQ
