### ISSUE TITLE
Issue with sideloading on Wopi hosted document served via on premise Office Online Server

### ISSUE THREAD

**Issue by vickeybird** [OfficeDev/office-js#494]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins#

## Issue
I'm trying to test my add in on a word document hosted on custom WOPI hosted application which is served by an On Premise Office Online Server.
When I click on Insert/Office Add-in, I get an error:  

> Please add or enable add-in catalogs from the Trust Centre.
![Annotation 2019-04-26 110314](https://user-images.githubusercontent.com/800534/56785951-d5603f00-6814-11e9-9270-e79d9b59c843.png)

Also when I do not get any options to Trust Centre via Files
![OptionsNotAvailableInMenu](https://user-images.githubusercontent.com/800534/56785940-c8435000-6814-11e9-8eaf-49db365f3dc3.png)

Is my OOS not configured properly or  add ins are not supported on WOPI hosted documents?

**Comment by Rick-Kirkham** [comment]
This issue might have the answer: https://stackoverflow.com/questions/44665073/how-to-deploy-officejs-addin-on-office-online-on-premise-server

**Comment by Rick-Kirkham** [comment]
Closing. If you are still having problems, please add a comment here.

**Comment by AmirNorouzpour** [comment]
@Rick-Kirkham Hi Rick I'm still having trouble! 
How to register paths for office online server, 
![1](https://user-images.githubusercontent.com/24652732/66257554-aaa4ea00-e7a7-11e9-81f3-033bdb35ee9a.PNG)
on-premise server?!

**Comment by geo-stanciu** [comment]
Hello,
I am having the exact same issue. Can you please post how was this solved ?
Basically, how to register trusted paths in Office Online Server ?

**Comment by nithinshiriya** [comment]
Have you tried setting the "AllowExternalMarketplace" as true?
