### ISSUE TITLE
How to insert chart in word document using insertOoxml

### ISSUE THREAD

**Issue by iam-alpesh** [OfficeDev/office-js#4945]
Hi team,

I have created the XML for a chart, but when I try to insert it using the insertOoxml function, I'm encountering an exception. While some charts are inserted successfully, others fail.

To troubleshoot, I retrieved the chart XML from a Word document using the getOoxml() method. The retrieved XML contained extra parts, so I modified it by removing the unnecessary sections. However, even after these modifications, I'm still unable to insert the chart into another Word document.

Could you please guide me on which parts of the XML are necessary for chart insertion and which can be excluded? Any advice or guidelines would be greatly appreciated.

**Snippet for Get XML :**

```
async function GetOoxml() {  

    await Word.run(async (context) => {
        // Create a proxy object for the document body.
        var body = context.document.getSelection();
        // Queue a commmand to get the OOXML contents of the body.
        var bodyOOXML = body.getOoxml();
        //context.load(bodyOOXML, "value");
        await context.sync();
        // Stashing the OOXML in case
        var currentOOXML = bodyOOXML.value;
        await context.sync();
        console.log("done");
    }).catch(function (error) {
        console.log("Error: " + JSON.stringify(error));
        if (error instanceof OfficeExtension.Error) {
            console.log("Debug info: " + JSON.stringify(error.debugInfo));
        }
    });
}
```

**Snippet for Insert XML:**

```
async function InserChartWithOpenXML() {
    await Word.run(async (context) => {
        debugger;
        const myOOXMLRequest = new XMLHttpRequest();
        let myXML;
        myOOXMLRequest.open('GET', "../Xml/Test3.xml", false);
        myOOXMLRequest.send();
        if (myOOXMLRequest.status === 200) {
            myXML = myOOXMLRequest.responseText;
        }
        //console.log(myXML);
        //Office.context.document.setSelectedDataAsync(myXML, { coercionType: 'ooxml' });
        const body = context.document.body;
        body.insertOoxml(myXML, Word.InsertLocation.end);
        console.log("Your code goes here");
        await context.sync();
    }).catch(function (error) {
        console.log("Error: " + JSON.stringify(error));
        if (error instanceof OfficeExtension.Error) {
            console.log("Debug info: " + JSON.stringify(error.debugInfo));
        }
    });
}
```

**XML Files :** 
https://filetransfer.io/data-package/D1SN8WBo#link

**Word Document :** 
[ChartDocument.docx](https://github.com/user-attachments/files/17273263/ChartDocument.docx)

Note: My primary task is to insert a chart from Excel into Word using a Word Add-in. If you have any alternative approaches that could help me avoid this issue, please let me know.

MS Word Version :
Microsoft® Word for Microsoft 365 MSO (Version 2409 Build 16.0.18025.20030) 64-bit 

Office js :
https://appsforoffice.microsoft.com/lib/1/hosted/office.js

**Comment by qinliuMSFT** [comment]
Hi @iam-alpesh , we have one public doc for your reference: [Understand when and how to use Office Open XML in your Word add-in](https://learn.microsoft.com/en-us/office/dev/add-ins/word/create-better-add-ins-for-word-with-office-open-xml).

For charts specific, in this document, we recommend: "Either add your rich content to an otherwise blank Word document and then save the file in Word XML Document format or use a test add-in with the `getSelectedDataAsync` method to grab the markup. "

I hope it helps.
