### ISSUE TITLE
Incorrect generation of a formula in an Office table with the French locale

### ISSUE THREAD

**Issue by LegoupilAlexandre** [OfficeDev/office-js#4947]
# Provide required information needed to triage your issue
I'm adding a formula in my office table that performs an operation on the cells of my table.
Example: I create a column that adds two columns of my table

## Your Environment

* Platform : Office on the web 
* Host : Excel
* Office version number: Build 16.0.18122.42305
* Operating System: Windows
* Browser : Any browser
 
## Expected behavior
Excel is supposed to create the formula correctly.

## Current behavior
The formula is not properly generated : an useless";" is inserted into the formula after each "@".

I am forced to manually remove the useless ";"  to make my formula works.

## Steps to reproduce

Set your locale to "French" in File/ Options/ Locale.

Create a Office table with two columns with numeric values.
Add a third column which adds the two cells of the two columns of the table like this : 
 - Type the column header and create the new column
 - Type "="
 - Click on  the first cell of the first column
 - Type "+"
 - Click on the first cell of the second column

You will see that Excel generates an incorrect formula with extra ";" after @ which doesn't work.
Example : =Tableau1[@;Column1]+Tableau1[@;Column2].

## Useful logs

[Adding a formula in Office Table with French locale issue.xlsx](https://github.com/user-attachments/files/17276267/Adding.a.formula.in.Office.Table.with.French.locale.issue.xlsx)

![image](https://github.com/user-attachments/assets/9125ac94-6bfe-4e9e-b1d4-9c22633fd6dd)

**Comment by qinliuMSFT** [comment]
Hello! This platform is dedicated to discussing and reporting issues related to the Office JS API. Could you please confirm if your issue pertains to the Office JS API? If not, I may need to close this issue.

**Comment by LegoupilAlexandre** [comment]
Hello, you'are right it's not about Office JS API, it's a Excel issue. Sorry !

Can you tell me where i'm supposed to do this kind of issue for Excel ?

**Comment by qinliuMSFT** [comment]
We have created an internal backlog item and transferred it to the Excel Online team for further investigation. Since we are unable to track its progress through this GitHub channel, we will be closing this issue here.

We appreciate your understanding and patience.
