### ISSUE TITLE
NAA Dialog fallback does not work

### ISSUE THREAD

**Issue by j-jodczyk** [OfficeDev/office-js#4949]
# Provide required information needed to triage your issue
I was trying to adopt NAA in my Outlook add-in according to this example: https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-NAA 
In the fallback scenario, when `getTokenWithDialogApi` is used to retrieve the token, the dialog opens to an empty screen and is stuck there. After changing PCA to `StandardPublicClientApplication` (using `createStandardPublicClientApplication` instead of `createNestablePublicClientApplication` [here](https://github.com/OfficeDev/Office-Add-in-samples/blob/7ef685066130e6bbe9a9cb9c9f45bf20cc9c3e8d/Samples/auth/Outlook-Add-in-SSO-NAA/src/taskpane/fallback/fallbackauthdialog.ts#L35)) the login page is displayed.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook on the Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: MacOs 14.6.1
* Browser (if using Office on the web): Chrome Version 129.0.6668.90
 
## Expected behavior
The login page is displayed when using NestablePublicClientApplication

## Current behavior
The dialog is stuck with blank page. No console logs displayed. When debugging, I can see that the code from fallbackauthdialog.ts is not executed beyond retrieving pca client.

## Steps to reproduce
Just try to execute the example https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-NAA with `getTokenWithDialogApi` being the path for getting the token.

## Context

Trying to migrate to NAA with all paths working - using the example mentioned as reference.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by neprasad-microsoft** [comment]
Hi @j-jodczyk 
This issue was fixed with this PR - https://github.com/OfficeDev/Office-Add-in-samples/pull/866 . You can pull in the latest sample code and try again. Please let us know if the issue still persists.
