### ISSUE TITLE
Word.LocationRelation value of insideEnd when comparing with selection on a new line

### ISSUE THREAD

**Issue by dannycurrie** [OfficeDev/office-js#495]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I have noticed that `range.compareLocationWith(anotherRange)` returns a `LocationRelation` value of `insideEnd` when comparing a range on a new line, with a range on the line above.

## Expected Behavior
`LocationRelation` value of `after`

## Current Behavior
`LocationRelation` value of `insideEnd`

## Steps to Reproduce, or Live Example
In Word Desktop
Load following gist in ScriptLab https://gist.github.com/dannycurrie/b8e462fa1c4cbbf5faddfba89855a0b4
Click `Insert` to insert a content control
Hit `Enter` to put caret on the next line
Hit `Compare` to `console.log` Location Comparison between the current selection and the content control on the above line
`LocationRelation` value shows `insideEnd`

## Context
We need to be able to identify the nearest previous content control to the current selection.
Note that this issue does not happen if there is more than one line between the current selection and the content control, or if there is text added between the selection and the control.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.22
* Operating System: Mojave

## Useful logs
See output from script lab gist.

**Comment by Rick-Kirkham** [comment]
I can reproduce. 
1. If the cursor is just outside the end of the CC, should get "After" but get "InsideEnd".
2. If there is 1 carriage return between the end of the CC and cursor, should get "After" but get "InsideEnd".
3. If the cursor is just inside the end of the CC, should get "InsideEnd", but get "Inside".
4. If the cursor is just outside the start of the CC, should get "Before" but get "InsideStart".
5. If the cursor is just inside the start of the CC, should get "InsideStart", but get "Inside".

**Comment by dannycurrie** [comment]
Thanks Rick!

**Comment by kbrandl** [comment]
@dannycurrie apologies for the lack of engagement on this issue. Are you still having this problem?

**Comment by dannycurrie** [comment]
Thanks for getting back to me @kbrandl - we're working around the problem at the moment, so it isn't a live issue for us, but it would be helpful to us if fixed.

**Comment by kbrandl** [comment]
@dannycurrie thanks for the update. @weshi can you please investigate? Thanks!
