### ISSUE TITLE
Outlook: How to detect Appointment/even save and have callback function

### ISSUE THREAD

**Issue by bhaskarchalla** [OfficeDev/office-js#4950]
I’m developing an Outlook Add-in that includes a taskpane with a form. When a user opens an appointment or event and launches our app, the form loads. We need to validate the form when the user clicks Save or Send. If the validation fails, we should prevent the save/send action and display an error message.

I found the `OnAppointmentSend` event in the documentation, which seems to work for the Send action but not for saving an appointment. Is there a way to implement this for both actions? Please let me know if you need any additional details.

**Comment by neprasad-microsoft** [comment]
Hi @bhaskarchalla 
We do not have an event for Appointment Save. This will be considered as a new feature request. 
We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.

**Comment by bhaskarchalla** [comment]
As suggested raised feature request in Tech Community Page
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/outlook-how-to-detect-appointment-even-save-and-have-callback/idi-p/4267658
