### ISSUE TITLE
Error when starting an office-js Excel taskpane project using the VSCode Office development kit add-in

### ISSUE THREAD

**Issue by jkpieterse** [OfficeDev/office-js#4951]
I am trying to get started developing a new Office-js taskpane project for Excel, using the instructions found here:

https://learn.microsoft.com/en-us/office/dev/add-ins/develop/development-kit-overview?tabs=vscode
(note that the link to VSCode is wrong, it points to Visual Studio)

After having installed both VSCode and Node.js, I launch VS code, click on the automatically added icon for "Microsoft Office Add-ins Development Kit" and click "Create a new add-in". I choose Excel taskpane add-in and after selecting the target folder and naming the project, I get this:

Error: Command failed: npm run convert-to-single-host --if-present -- excel
npm ERR! code ENOENT
npm ERR! syscall spawn C:/Program Files/Git/usr/bin/bash
npm ERR! path c:\Users\piete\Documents\officeAddins\SomeTestAddIn
npm ERR! errno -4058
npm ERR! enoent spawn C:/Program Files/Git/usr/bin/bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\piete\AppData\Local\npm-cache\_logs\2024-10-07T15_02_40_665Z-debug-0.log

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at ChildProcess.exithandler (node:child_process:423:12)
	at ChildProcess.emit (node:events:519:28)
	at maybeClose (node:internal/child_process:1105:16)
	at ChildProcess._handle.onexit (node:internal/child_process:305:5)
	at Process.callbackTrampoline (node:internal/async_hooks:130:17)

Now what???

**Comment by qinliuMSFT** [comment]
Hi @jkpieterse , thanks for reporting this issue. Product team will investigate and reply to you as soon as there is progress.

**Comment by hermanwenhe** [comment]
@jkpieterse Hi, can you provide the node version installed?

**Comment by hermanwenhe** [comment]
According to the error log you shared: `npm ERR! enoent spawn C:/Program Files/Git/usr/bin/bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.` 
This seems like the npm cannot find the bash on your local environment. Can you try install `Git Bash` and then create a new add-in project?

**Comment by jkpieterse** [comment]
Node version 20.18.0.

I tried (in a cmd window): npm install git bash

After that I tried anew to generate an Excel project, resulting in 👍 Error: Command failed: npm run convert-to-single-host --if-present -- excel
npm ERR! code ENOENT
npm ERR! syscall spawn C:/Program Files/Git/usr/bin/bash
npm ERR! path c:\Users\piete\Documents\officeAddins\JKP_Test_2
npm ERR! errno -4058
npm ERR! enoent spawn C:/Program Files/Git/usr/bin/bash ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\piete\AppData\Local\npm-cache\_logs\2024-10-11T13_47_29_401Z-debug-0.log

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at ChildProcess.exithandler (node:child_process:423:12)
	at ChildProcess.emit (node:events:519:28)
	at maybeClose (node:internal/child_process:1105:16)
	at ChildProcess._handle.onexit (node:internal/child_process:305:5)
	at Process.callbackTrampoline (node:internal/async_hooks:130:17)

**Comment by jkpieterse** [comment]
I suspect I didn't install git bash properly?

**Comment by hermanwenhe** [comment]
> I suspect I didn't install git bash properly?

No. You should not install git bash by running npm commands. Try this link to download and install: https://gitforwindows.org/

**Comment by jkpieterse** [comment]
I did install git bash from that source. I get the same error. Here is the output from my Powershell terminal in VS Code:

Executing task: npm run start:desktop -- --app excel 


> office-addin-taskpane@0.0.1 start:desktop
> office-addin-debugging start manifest.xml desktop --app excel

/c/Users/piete/Documents/officeAddins/excelTaskpaneAddin/node_modules/.bin/office-addin-debugging: line 2: sed: command not found
/c/Users/piete/Documents/officeAddins/excelTaskpaneAddin/node_modules/.bin/office-addin-debugging: line 2: dirname: command not found
/c/Users/piete/Documents/officeAddins/excelTaskpaneAddin/node_modules/.bin/office-addin-debugging: line 4: uname: command not found
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module 'C:\office-addin-debugging\cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.18.0

 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run start:desktop -- --app excel" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it.

**Comment by jkpieterse** [comment]
During installation of Git, I want with all the preselected choices. Should I have made changes?

**Comment by hermanwenhe** [comment]
> I did install git bash from that source. I get the same error. Here is the output from my Powershell terminal in VS Code:
> 
> Executing task: npm run start:desktop -- --app excel
> 
> > office-addin-taskpane@0.0.1 start:desktop
> > office-addin-debugging start manifest.xml desktop --app excel
> 
> /c/Users/piete/Documents/officeAddins/excelTaskpaneAddin/node_modules/.bin/office-addin-debugging: line 2: sed: command not found /c/Users/piete/Documents/officeAddins/excelTaskpaneAddin/node_modules/.bin/office-addin-debugging: line 2: dirname: command not found /c/Users/piete/Documents/officeAddins/excelTaskpaneAddin/node_modules/.bin/office-addin-debugging: line 4: uname: command not found node:internal/modules/cjs/loader:1228 throw err; ^
> 
> Error: Cannot find module 'C:\office-addin-debugging\cli.js' at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15) at Module._load (node:internal/modules/cjs/loader:1051:27) at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12) at node:internal/main/run_main_module:28:49 { code: 'MODULE_NOT_FOUND', requireStack: [] }
> 
> Node.js v20.18.0
> 
> * The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run start:desktop -- --app excel" terminated with exit code: 1.
> * Terminal will be reused by tasks, press any key to close it.

Try run `npm install -g office-addin-debugging` and `npm i` before perviewing. I suggest creating a new project and do so in the new one.

**Comment by jkpieterse** [comment]
Did this, no luck.
Looks like the Excel task pane project the add-in generates has a problem in its manifest file. If I run the manifest checker this is the output I get:

Validating manifest...
npx --yes office-addin-manifest validate manifest.xml
/c/Users/piete/AppData/Local/npm-cache/_npx/4692618cb69c9be3/node_modules/.bin/office-addin-manifest: line 2: sed: command not found
/c/Users/piete/AppData/Local/npm-cache/_npx/4692618cb69c9be3/node_modules/.bin/office-addin-manifest: line 2: dirname: command not found
/c/Users/piete/AppData/Local/npm-cache/_npx/4692618cb69c9be3/node_modules/.bin/office-addin-manifest: line 4: uname: command not found
node:internal/modules/cjs/loader:1228
  throw err;
  ^

Error: Cannot find module 'c:\office-addin-manifest\cli.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Module._load (node:internal/modules/cjs/loader:1051:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at node:internal/main/run_main_module:28:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v20.18.0
* Terminal will be reused by tasks, press any key to close it.

**Comment by hermanwenhe** [comment]
![image](https://github.com/user-attachments/assets/b369c82e-b8ce-4df0-a8d6-bac5867f063a)
I try to get answer from Copilot. Looks like this is virtual machine specific problem. Can you try open Git Bash from the start menu and navigate to the project directory, then run the manifest validation command `npx --yes office-addin-manifest validate manifest.xml`. If this works, then you can run the `npm install` and other commands in `package.json`.

**Comment by jkpieterse** [comment]
Thanks for replying. 
When I do that I do get "The manifest is valid.".
But I do not know what you mean exactly with ", then you can run the npm install and other commands in package.json"? I'm sorry, I'm a beginner in this respect and have very little experience with all these (mystic to me) tools. I have no idea what the various command-line tools needed to get this all working are for.

**Comment by jkpieterse** [comment]
I did execute npm install, to no avail. Debugging is still not possible, with the same error messages.

**Comment by hermanwenhe** [comment]
@jkpieterse Since you've run manifest validation successfully. You can try create a new add-in project and follow the instructions to start debugging.

**Comment by hermanwenhe** [comment]
Since you've run manifest validation successfully, it means your npm environment is fine. You can try creating a new add-in project and follow the instructions to start debugging.

The virtual machine usually behave strangely when developing. You should try figuring out how to `npm install` correctly and then use a new project to do further development. Since this issue is not a Dev Kit issue, completing this issue.

**Comment by jkpieterse** [comment]
This is not very helpful. I have probably by now redone the entire process of uninstalling everything related to VSCode and office-js development and meticulously following the steps described here: https://learn.microsoft.com/en-us/office/dev/add-ins/develop/development-kit-overview?tabs=vscode more than three times. No sigar. You say NPM is correctly installed as it is able to validate the manifest, but why does running the project then fail with these errors?

**Comment by hermanwenhe** [comment]
Can you paste the error log when click the "Preview your Office add-in" button?

**Comment by jkpieterse** [comment]
I've just reinstalled Windows on the machine with the intention to start over. I will revert as soon as that is done.

**Comment by jkpieterse** [comment]
After reinstalling Windows I did the following:

- Installed node.js. I checked the box to install all of its dependencies, I'm not sure if this was needed?
- Installed VS Code
- Installed the Office dev kit in Code
- Started a new project using that dev kit
- Got some errors when I tried to run
- Then in a cmd pane I ran npm install against the new add-in folder I just created
- Now I can debug after running npm start!

Remains one question: Was checking that box for dependencies in node.js installation necessary?

**Comment by hermanwenhe** [comment]
> After reinstalling Windows I did the following:
> 
> * Installed node.js. I checked the box to install all of its dependencies, I'm not sure if this was needed?
> * Installed VS Code
> * Installed the Office dev kit in Code
> * Started a new project using that dev kit
> * Got some errors when I tried to run
> * Then in a cmd pane I ran npm install against the new add-in folder I just created
> * Now I can debug after running npm start!
> 
> Remains one question: Was checking that box for dependencies in node.js installation necessary?

It's great to hear the issue is gone! Actually the node.js checkbox is just for checking if you have installed it. If not, developers should install it manually, it's more a prerequisite checker than an installing tool.

**Comment by jkpieterse** [comment]
Thanks for your support @hermanwenhe
