### ISSUE TITLE
[Word] Annotations don't work for add-ins when the license is single time purchase (non-subscription)

### ISSUE THREAD

**Issue by siddharth-jaidka** [OfficeDev/office-js#4953]
The **Annotations** [Word API Requirement set 1.7] feature does not function properly with a single-time purchase license (non-subscription based).

It would be beneficial to implement a method in office.js to detect this scenario and manage it more effectively. Currently, `.requirements.isSetSupported('WordApi', '1.7')` always returns true, which makes it difficult to identify the issue.

**Comment by qinliuMSFT** [comment]
Hi @siddharth-jaidka , thanks for reporting this issue. 

According to this [Requirement set availability](https://learn.microsoft.com/en-us/javascript/api/requirement-sets/word/word-api-requirement-sets?view=common-js-preview#requirement-set-availability), `Word API 1.7` is supported on Retail perpetual licenses after version 2311 and is not supported at all on Volume-Licensed perpetual licenses.

Could you please share more details about the non-subscription license? Is it retail perpetual or volume-licensed perpetual? The Office version number will help us differentiate between them and investigate further.

**Comment by siddharth-jaidka** [comment]
Facing this issue in following word versions on Windows under retail perpetual licenses:

- Office home and student 2021 - **Version 2407 (Build 17830.20166)** 
- Office home and student 2019 - **Version 2409 (Build 18025.20104)**

**isSetSupported** is returning true for WordApi  and **insertAnnotations** call succeeds without drawing any annotations on screen. The same is reproducible via Scriptlab as well.

**Comment by qinliuMSFT** [comment]
Thank you @siddharth-jaidka  for providing the additional information. We've added one item in our backlog #9432714, the product team will investigate and we will reply to you soon as there is progress.

**Comment by cbouzmsft** [comment]
This behavior is by design since the annotation service this API is based upon requires a subscription.

**Comment by siddharth-jaidka** [comment]
Hey @cbouzmsft, is there any way to properly identify this, since the **isSetSupported** returns true on these licenses lacking a subscription?

**Comment by cbouzmsft** [comment]
Our product team is aware of this limitation. There is currently no such way.

**Comment by gion-andri** [comment]
How are add-in authors supposed to check, if a user has a subscription, if `.requirements.isSetSupported('WordApi', '1.7')` always returns true? How can we detect, if we can use that API?
