### ISSUE TITLE
How to Implement NAA for Outlook addin created by Visual studio Scaffolding instead of node.js and yoeman

### ISSUE THREAD

**Issue by avisheknand** [OfficeDev/office-js#4955]
I'm encountering an error when trying to use createNestablePublicClientApplication from MSAL.js V3 in an Outlook add-in project created with Visual Studio 2022. The add-in was initially scaffolded with .NET Framework 4.8. As MSAL V3 is no longer available via CDN, I installed the following packages using the Client-Side Library Manager in Visual Studio:

@azure/msal-browser@3.25.0
@azure/msal-common@14.15.0

Error: Upon calling createNestablePublicClientApplication(msalConfig), I receive the following error: createNestablePublicClientApplication is not a function.

Further investigation revealed that IPublicClientApplication.ts could not be loaded due to the error in the file

![image](https://github.com/user-attachments/assets/7e5d0b07-ccf7-4e95-923f-6df4b2bee35f)

This same error is inside other files of the msal browser package/library

Has anyone encountered this and have any suggestion on how i can implement NAA if Addin was created via Visual Studio

**Comment by pkkj** [comment]
Hi @avisheknand,

I feel your code doesn't import the needed function to create the public client.

Usually I would do:
```TypeScript
import * as msal from "@azure/msal-browser";
msal.createNestablePublicClientApplication(msalConfig);
```

Thanks.
