### ISSUE TITLE
Require control over Don't Send button in prompt

### ISSUE THREAD

**Issue by riddhi-p-28** [OfficeDev/office-js#4957]
We are developing an outlook web addin using office js Smart alert template.

We are validating entered recipient . Sometimes when clicked on Outlook "Send" after successful validation, a popup appears stating "Validation is taking longer than expected" and then after few seconds another popup displays a green tick with the message "Validation tool finished processing," along with two buttons: "Send" and "Don't Send." Refer below:

![image](https://github.com/user-attachments/assets/ab415f92-6d2f-4a5e-9a52-721eaa938aa1)

![image](https://github.com/user-attachments/assets/c125d467-4340-4e02-b893-c31fc21e26d7)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior
We currently do not have control over the "Send" and "Don't Send" buttons in the green tick validation popup. Need to have some control on Don’t Send button for further action.

## Current behavior

On Mail Sent action, we are creating one text file. Due to this intermittent popup if user click on following button:
a) Clicked on "Send":
The email is sent and file created which is expected.
b) Clicked on "Don't Send":
The email is not sent but file get created which is not expected.

## Steps to reproduce

1. Compose a new email and popout
2. Add recipients, subject, body and attachments.
3. Click on the send button.

**Comment by neprasad-microsoft** [comment]
Hi @riddhi-p-28, 
Unfortunaltely this feature is not present currently and will be considered as a new feature request. 
We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.
