### ISSUE TITLE
Why is there no 'remove' button in the plugin management interface?

### ISSUE THREAD

**Issue by YoungChestnut** [OfficeDev/office-js#4959]
env:
 node: 18.16.0
 system： window 11
 outlook platform:  web,
 browser:  google (129 version)

Question 1:
Why is there no 'remove' button in the plugin management interface?
![1728654923315](https://github.com/user-attachments/assets/f5eaeccb-1dca-4e34-a7a5-db47d0432346)

Question 2:
When I modified the local port number in the manifest.xml file, the plugin window still displayed the previous port number. I tried changing the manifest's Id or version , but it didn't update the port number in the plugin window. What might be the reason for this, and is there a good solution?
![image](https://github.com/user-attachments/assets/68f78ba9-d914-4c71-b38d-9b970758f1cc)

**Comment by neprasad-microsoft** [comment]
Hi @YoungChestnut 
Thanks for reaching out. To answer your questions:

1. We do not support side loading from the new store experience. To remove sideloaded add-ins follow the steps here - https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing#remove-a-sideloaded-add-in
2. After changing the manifest, you need to reinstall the manifest for the changes in the manifest to reflect in your add-in.
