### ISSUE TITLE
`Office.context.mailbox` `ItemChanged` not triggering if taskpane is *not* pinned on Outlook for Mac

### ISSUE THREAD

**Issue by maoueh** [OfficeDev/office-js#4960]
## Your Environment
* Platform: Mac
* Host: Outlook native app, installed through download from Microsoft
* Office version number: Version 16.89.3 (24092813)
* Operating System: macOS 14.5 
 
## Expected behavior
```javascript
  Office.onReady(() => {
    console.log('Office Ready', Office.context.mailbox.diagnostics.hostName)
    Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, () => {
      console.log('[Outlook] item changed fired')
    })
  })
```

With an Outlook Add-In that has a taskpane.

If the taskpane is pinned, the code above correctly fires `ItemChanged` events when the user change from one email to the other.

If the taskpane is not pinned, the code above does not receives `ItemChanged` events anymore.

## Current behavior

Taskpane doesn't not receive any `ItemChanged` if the extension is not pinned.

Now, maybe it's the correct behavior and only pinned extension receives `ItemChanged`. The odd part is that `SelectedItemsChanged` are correctly fired in both cases, e.g. when the taskpane is pinned or not.

Current workaround is to use the `SelectedItemsChanged` (and request the permission) and retrieved the first selection `itemId`. Problems with this approach, at least for us, is that `SelectedItemsChanged` doesn't populate `conversationId` properly, which we used. And the `ItemId` is the non-immutable-ID, so we need to call `TranslateExchangeIds` to find the corresponding message on our backend. 

## Steps to reproduce
1. Install an Outlook Add-In that uses a taskpane and has the code above
1. Pin the taskpane and observed that `ItemChanged` are fired when navigating through email(s)
1. Unpin the taskpane and observed that `ItemChanged` are fired when navigating through email(s)

**Comment by neprasad-microsoft** [comment]
Hi @maoueh 
You are correct, ItemChanged event is only fired if the taskpane is pinned. This is the expected behaviour and is captured in the doc here - https://learn.microsoft.com/en-us/javascript/api/office/office.eventtype?view=common-js-preview . 

Is your add-in a multi-select add-in? You can go through this article for the behaviour of multi-select add-ins in conversation - https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/item-multi-select?tabs=jsonmanifest#multi-select-in-conversations. 

In case of mult-select add-ins you can use getSelectedItemsAsync to get the conversationID of the selected items. This link has an example of how it is used - https://learn.microsoft.com/en-us/javascript/api/outlook/office.selecteditemdetails?view=outlook-js-preview .

**Comment by maoueh** [comment]
> This is the expected behaviour and is captured in the doc here

Yeah I see now indeed. The thing that thrown me off as a constructive feedback was that the taskpane I'm implementing does stay visible when changing message even though the blue pin icon was not active. I think a better condition when the `ItemChanged` should or should not be fired should be: `ItemChanged is fired if your taskpane is visible to the user`.

That would ensure that the taskpane is always contextualy linked to the user's viewed message. Would probably be considered a breaking change now I imagine though.

> Is your add-in a multi-select add-in?

It was not, but it will now although I'll use the selection changed as a way to emulate ItemChanged, by using the first selected message.

> In case of mult-select add-ins you can use getSelectedItemsAsync

That's exactly what I did now to overcome the problem:

```js
    Office.context.mailbox.addHandlerAsync(Office.EventType.SelectedItemsChanged, () => {
      Office.context.mailbox.getSelectedItemsAsync(result => {
        if (result.error) {
          console.error('Error getting selected items', result.error)
          return
        }

        console.debug('[Outlook] SelectedItemsChanged changed', result)

        // From my testing, when multiple message are selected, the UI is not displaying anything
        // so we use the same logic below. If there is a single selection, we display it, if there
        // are multiple selections, we display nothing.
        if (result.value.length === 1) {
          // It appears that the SelectedItemsChanged does *not* contain the conversationId as
          // we get with the ItemChanged event. So we can't use the conversationId here. However,
          // take note the ID here is a mutable REST ID and not the immutable ID that we use in the
          // backend.
          //
          // The backend converts this mutable ID to the immutable ID before using it so this method
          // is a bit slower.
          setMessageId(convertItemIdToRestId(result.value[0].itemId))
        } else {
          setMessageId(undefined)
        }
      })
    })
 ```
 
From my current test, the `conversationId` was not present in the `result` array. I'll perform more tests to assert what I just said and I'll open a different issue for the `conversationId` not being present.

Thanks for your answer(s)!

**Comment by maoueh** [comment]
@neprasad-microsoft https://github.com/OfficeDev/office-js/issues/4974
