### ISSUE TITLE
Excel.createWorkbook(fileData) breaks relative (in-file) links in pivot tables.

### ISSUE THREAD

**Issue by iarailopoulos** [OfficeDev/office-js#4966]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Mac (but reproducible to PC desktop as well)
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.89.1
* Operating System: macOS Sequoia (v15.0)
* Browser (if using Office on the web): n/a
 
## Expected behavior

Given I have an excel file with pivot tables and links in the same sheet (without any references to other files)
Given I've read the file into memory as a base64 encoded string (`fileData`).
When I use the `Excel.createWork(fileData)` 
Then the file opens in a new excel window and the links of the pivot tables still work and they are relative without file references.

## Current behavior

Given I have an excel file with pivot tables and links in the same sheet (without any references to other files)
Given I've read the file into memory as a base64 encoded string (`fileData`).
When I use the `Excel.createWork(fileData)` 
Then the file opens in a new excel window and the links of the pivot tables **do not work as they have links to an absolute file path that doesn't exist**.
For example when I am trying to click on `Refresh Data` from a pivot chart I get an error `Can't open PivotTable source file '$PATH_TO_FILE/[blah.tmp]$SHEET_NAME'`

## Steps to reproduce

1. Create a file that uses pivot tables (for example add a pivot chart)
2. Try to use the `Excel.createWorkbook(fileAsBase64String)` to open it to a new file
3. When the new file opens right click on the pivot chart, click on `Refresh Data`
4. An error pops up `Can't open PivotTable source file '$PATH_TO_FILE/[blah.tmp]$SHEET_NAME'`

## Link to live example(s)

1. clone `https://github.com/iarailopoulos/excel_pivot_create_workbook_bug` (*Relevant file is `src/taskpane/components/CreatePivotWorkbook.tsx`*)
2. `npm install`
3. `npm run dev-server`
4. `npm start`
5. Click `Load Data` to load the excel file into memory
![image](https://github.com/user-attachments/assets/46afa210-04ef-4e26-aacd-f874d7cd4eba)
7. Click `Create Pivot Workbook` to create a new workbook
![image](https://github.com/user-attachments/assets/ee3096ce-dc6f-4cdc-bd34-54293eeb1fa0)
9. Open new workbook on the `PIVOT` tab
![image](https://github.com/user-attachments/assets/923c8a76-54fa-4cdf-bce7-9b4c8792b43f)
11. Right click on the chart and click `Refresh Data`
![image](https://github.com/user-attachments/assets/5a5a9bdd-5dff-4f5b-8680-3dbb42a286d7)
13. See error `Can’t open PivotTable source file ’/path/to/temp/file/[fname.tmp]RAW DATA’`
![image](https://github.com/user-attachments/assets/04063904-6e5f-4f95-8922-28c6619a1d54)

# Provide additional details

1. ______
2. ______
3. ______

## Context

I am trying to allow users to download a file with pivot tables but the pivot table links don't work.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by qinliuMSFT** [comment]
Hi @iarailopoulos , thank you for reporting this issue. I can reproduce on win32 application. We have filed an item #9443767 and put on our backlog, the team will investigate and reply to you as soon as there is any progress. Thank you for your patience.

**Comment by XuanZhouMSFT** [comment]
Hi @iarailopoulos, thanks for the waiting. Currently this is the limitation of using this API. We'd like to suggest you to link the file within the same worksheet.
After careful consideration, our team has decided to not fix this issue in the short term. We recommend you to upvote or submit a new Tech Community New Ideas item, this will give us visibility of the commonality of it and will help with our prioritization. If we end up working on this issue, we will re-activate as needed.

**Comment by iarailopoulos** [comment]
thanks @XuanZhouMSFT, the trouble is that this won't for for Excel for the web, as per the official [docs](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-workbooks):

The insertWorksheetsFromBase64 method is supported for Excel on the web, on Windows, and on Mac. It's not supported for iOS. **Additionally, in Excel on the web, this method doesn't support source worksheets with PivotTable, Chart, Comment, or Slicer elements. If those objects are present, the insertWorksheetsFromBase64 method returns the UnsupportedFeature error in Excel on the web.**
