### ISSUE TITLE
 Assistance Required for Running Office Add-ins in Embedded Excel

### ISSUE THREAD

**Issue by kumarabhi6385** [OfficeDev/office-js#4969]
**Description:**

I have developed an Office JavaScript add-in hosted in Azure, which works seamlessly with Excel files stored in SharePoint. Currently, I have a web application where I need to embed an Excel file and utilize this add-in directly within the embedded form of Office 365 Excel.

**Issue:**

I am facing difficulties in running the add-in directly in the embedded version of Office 365 Excel. I need guidance on how to achieve this functionality.

**Request:**

Could you please provide any sample code or documentation that can help me run the Office add-in in the embedded form of Excel? Any insights or solutions to this issue would be greatly appreciated.

**Comment by qinliuMSFT** [comment]
Hi @kumarabhi6385 , when you say Office 365 Excel forms embedded in a web application, are you referring to CSPP? If so, you may want to reference this doc: [Enable Office Add-ins provided by a WOPI host](https://learn.microsoft.com/en-us/microsoft-365/cloud-storage-partner-program/online/add-ins)
