### ISSUE TITLE
Track changes in Word and Excel

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#4970]
Can you please tell me API by which we can understand if context document has any tracked changes present or review comments?

**Comment by qinliuMSFT** [comment]
Hi @ishanig11 , there is no track change mode in Excel.

For Word, you can get all track changes information via getTrackedChanges(): Word.TrackedChangeCollection method.

Reference Link : [Word.TrackedChangeCollection class - Office Add-ins | Microsoft Learn](https://learn.microsoft.com/en-us/javascript/api/word/word.trackedchangecollection?view=word-js-preview)
