### ISSUE TITLE
Outlook `getSelectedItemsAsync` does not populate `conversationId` in results

### ISSUE THREAD

**Issue by maoueh** [OfficeDev/office-js#4974]
In issue https://github.com/OfficeDev/office-js/issues/4960#issuecomment-2411535959, it was suggested to use `Office.context.mailbox.addHandlerAsync(Office.EventType.SelectedItemsChanged, () => { ... })` and `getSelectedItemsAsync` to overcome the fact that `ItemChanged` is fired only for a pinned taskpane.

However, the `getSelectedItemsAsync` seems to be bogus by not populating the `conversationId` field of the selected items. 

## Your Environment
* Platform: Mac
* Host: Outlook
* Office version number: 16.89.3 (24092813)
* Operating System: macOS
 
## Expected behavior

With an Outlook extension that defines a taskpane which has multi-select APIs enabled, use the following code:

```js
  Office.onReady(() => {
    console.log('Init after Office Ready', Office.context.mailbox.diagnostics.hostName)

    Office.context.mailbox.addHandlerAsync(Office.EventType.SelectedItemsChanged, () => {
      console.log('[Outlook] SelectedItemsChanged event')
      Office.context.mailbox.getSelectedItemsAsync(result => {
        if (result.error) {
          console.error('Error getting selected items', result.error)
          return
        }

        console.log('[Outlook] SelectedItemsChanged result count', result.value.length)
        result.value.forEach(item => {
          console.log(`[Outlook] - Item ${item.itemId} - Conversation ID ${item.conversationId}`)
        })
      })
    })
  })
```

When the selection changed, you will see the following logs:

```
[Log] Init after Office Ready – "Outlook" (index.tsx, line 22)
[Log] [Outlook] SelectedItemsChanged event (index.tsx, line 24)
[Log] [Outlook] SelectedItemsChanged result count – 1 (index.tsx, line 30)
[Log] [Outlook] - Item AAMkA...QQKOAAA= - Conversation ID undefined (index.tsx, line 32)
[Log] [Outlook] SelectedItemsChanged event (index.tsx, line 24)
[Log] [Outlook] SelectedItemsChanged result count – 1 (index.tsx, line 30)
[Log] [Outlook] - Item AAMkA...QS4FAAA= - Conversation ID undefined (index.tsx, line 32)
[Log] [Outlook] SelectedItemsChanged result count – 2 (index.tsx, line 30)
[Log] [Outlook] - Item AAMkA...QQKNAAA= - Conversation ID undefined (index.tsx, line 32)
[Log] [Outlook] - Item AAMkA...QS4EAAA= - Conversation ID undefined (index.tsx, line 32)
```

## Current behavior
The `conversationId` is undefined always when receiving the results back from the `getSelectedItemsAsync`.

It should be populated.

## Steps to reproduce
1. Implement an Outlook Add-In with a taskpane and multi-select permissions.
1. Use the code provided above
1. Select messages in the inbox
1. Inspect the printed logs and observe that `conversationId` is `undefined`.

# Provide additional details

It appears this could be a bug with the Outlook native client only (maybe just on OSX too). Indeed, I've performed the same test using `Outlook for Web` and there, the `conversationId` field is properly populated.

## Context

Trying to overcome the limitation that `ItemChanged` which is emitted only for pinned taskpane even though our taskpane even when not **pinned** is still visible and as such, doesn't react to user changing messages.

We worked around the current issue by using `itemId` and retrieving the message in question and finding its `conversationId`. This is incurring extra calls in the backend as the `itemId` here is a mutable ID so we need in the backend to first convert to immutable ID (which we store internally for messages) via a Graph API call to `TranslateExchangeIds` to make the mutable `itemId` immutable and perform the lookup correctly.

## Useful logs

See logs above, see following screenshots which is my test session.

![image](https://github.com/user-attachments/assets/5e9f7a25-2db9-4d90-b534-8b2b0855df0a)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by neprasad-microsoft** [comment]
@maoueh 
Just to confirm, are you saying that it works as expected on Outlook Web, but not on Mac?

**Comment by maoueh** [comment]
@neprasad-microsoft Correct.

**Comment by maoueh** [comment]
When I say Mac, just to be clear I'm talking about the native Outlook Mac app

**Comment by maoueh** [comment]
I hadn't the chance to test native Outlook Windows app yet.

**Comment by neprasad-microsoft** [comment]
Hi @maoueh 
My apologies for the confusion. 'conversationId' is a part of API set 1.14 which is not yet supported on Mac. This is in our Feature backlog, but unfortunately, we do not have any timeline for this. Thanks for your patience.

**Comment by maoueh** [comment]
Great! What is the usual rollout time for those having automatic update set?

**Comment by neprasad-microsoft** [comment]
Hi @maoueh 
Unfortunately we do not have concrete timelines for this feature on Mac yet. But we will update our public docs as soon as we have 1.14 support on Mac. Thanks for your patience and understanding
