### ISSUE TITLE
Enabling browser extensions in Office Add-in WebView2 control 

### ISSUE THREAD

**Issue by rbilaney** [OfficeDev/office-js#4979]
The Edge Webview2 control now supports enabling browser extensions. However, Office Add-ins are hosted in a control which doesn't have the extensions enabled. 
Can someone help me in pointing to sample/documentation on enabling this? My use case is that I am developing an add-in that is to be used by enterprise users. The entrprise requires security extensions running in the browser that certifies that the user and device are both authorized/safe to allow access to internal web sites. Without this, the target users will only be able to use the add-in via Office Web and not desktop app like Excel (which is the primary use case).

Thanks,
Rakesh

**Comment by emmasab** [comment]
Thank you bringing this to our attention! This feature is in our backlog (tracking number: 9342979). Currently, however, we do not have a timeline to share. Thanks, Microsoft 365 Developer Platform team

**Comment by rbilaney** [comment]
Thanks Emma for the update. Is the link to backlog item public? If so, can you share so that I can +1 on it and monitor it.

**Comment by peterdTopaz** [comment]
My company is interested in this feature as well. Does this feature have any status update at this time?
