### ISSUE TITLE
[MAC] Office.context.mailbox.displayNewAppointmentForm method opens up a new appointment window but always shows "Reminder" as "None"

### ISSUE THREAD

**Issue by kanaksony** [OfficeDev/office-js#498]
**Expected Behavior**
I have set the Reminder on Outlook 2016 for Mac Preferences -> Calendar -> Default Reminder (say 15 minutes). In my add-in when I click on a button to open new appointment window using Office.context.mailbox.displayNewAppointmentForm method, the reminder should be shown as 15 minutes. This is working as expected for Outlook for Windows and OWA. Its should also work the same in Mac Outlook for Office 365.

**Current Behavior**
In Mac Outlook for Office 365, on clicking the button which calls Office.context.mailbox.displayNewAppointmentForm method opens an appointment window which always shows "Reminder" as "None".

**Steps to Reproduce, or Live Example**
Link to live example:
Please add the add-in into your Outlook for Mac by side loading - Get AddIns - My AddIn - Add from URL
https://mop.infocus.net:5000/infocus-conx-outlook-addin.xml

**Additional details:**
Go to Outlook Preferences->Calendar->Default Reminder->Set some value(say 15 min).
Click on second option "Schedule ConX Meeting" in the add-in's dropdown menu.
A new appointment window will open with some values in Subject, Location and Body.
Opened appointment, now showing Reminder to "None" whereas reminder set to 15 min.
Context

There is an inconsistent behaviour between all the Outlook platforms for our add-in. On Windows and OWA, Office.context.mailbox.displayNewAppointmentForm method opens an appointment with Default set "Reminder" but for Mac, it always displays "None" even if it is set to some value.

**Your Environment**
Platform: Mac
Host: Outlook
**Outlook for Mac version number: 16.22 (190211)**

**Comment by exextoc** [comment]
@Mac Outlook Extensibility Oncall<mailto:macolkextoncall@microsoft.com>

Bug 1095791<https://o365exchange.visualstudio.com/959adb23-f323-4d52-8203-ff34e5cbeefa/_workitems/edit/1095791>: [OfficeDev/office-js] Office.context.mailbox.displayNewAppointmentForm method opens up a new appointment window but always shows "Reminder" as "None" (#498)


________________________________

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding default reminder settings in Outlook for Mac. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by kanaksony** [comment]
Hi, Can I have any update on this?

**Comment by exextoc** [comment]
@kanaksony  Are you still facing this issue? We do not have a repro on our side.
We weren't able to find the Add-in "ConX Scheduler for Outlook" in store. Can you confirm if the Add-in is still available in store for installation? Please do share a screenshot of the Add-in in store if possible.
We were not able to repo this issue from our side when we tested Office.context.mailbox.displayNewAppointmentForm API independently. The reminder value is being picked from Outlook settings. If you are still facing this issue, Could you please provide the Mac Outlook Version number as well?

**Comment by exextoc** [comment]
@kanaksony Are you still facing this issue? We do not have a repro on our side.
We weren't able to find the Add-in "ConX Scheduler for Outlook" in store. Can you confirm if the Add-in is still available in store for installation? Please do share a screenshot of the Add-in in store if possible.
We were not able to repo this issue from our side when we tested Office.context.mailbox.displayNewAppointmentForm API independently. The reminder value is being picked from Outlook settings. If you are still facing this issue, Could you please provide the Mac Outlook Version number as well?
