### ISSUE TITLE
The dialog popup remains open for 5 minutes, after which an error message appears stating, "The UI-less add-in command times out.

### ISSUE THREAD

**Issue by Piyush-IT** [OfficeDev/office-js#4983]
We are developing an Office Add-in product that uses the displayDialogAsync function from Office.js to open a popup, but after 5 minutes, I consistently receive an error.
![AddinError](https://github.com/user-attachments/assets/07e2dd6e-89a4-4d58-a465-f2b53a06d225)
......................................code............
        Office.context.ui.displayDialogAsync('URL', { height: 50, width: 50, displayInIframe: true },
            function (asyncResult) {
                // Handle errors if the dialog fails to open
                if (asyncResult.status === Office.AsyncResultStatus.Failed) {
                    console.error('Failed to open dialog:', asyncResult.error.message);
                    return;
                }
                const dialog = asyncResult.value;
                // Add event handler for receiving messages from the dialog
                dialog.addEventHandler(Office.EventType.DialogMessageReceived, (arg) => {
                    console.log('Message received from dialog:', arg.message);

                });

                setTimeout(() => {

                    dialog.close();
					event.completed();
                }, 5000);
            }
        );
    }
}, 2000);
 dialog.close();
					event.completed();
					
					
..............................................................................................................................
Platform: Office for the Web
Host: Word
Office Version Number: Office 365
Operating System: Windows 10 (for testing purposes)

**Here are my questions:**
**1. Is it possible to set a custom timeout, such as 10 minutes or more?
2. I added event.completed, but it's not always reliable. Could you provide a sample code if available?**

Thank you in Advance..!!

**Comment by Piyush-IT** [comment]
Any update?

**Comment by Piyush-IT** [comment]
i request you to please update your view on this?

**Comment by qinliuMSFT** [comment]
Hi @Piyush-IT , sorry for the late response.  It has been put on our backlog # 9455404, the team will investigate and we will reply to you as soon as there is any progress. Thank you for your patience.

**Comment by m-hellesen** [comment]
Hey there, the timeout is set at 5 mins, our suggestion is to use dialogs for transient content or interactions that will complete within 5 mins. https://learn.microsoft.com/en-us/office/dev/add-ins/design/add-in-commands for more information

**Comment by Piyush-IT** [comment]
Can we extend the time limit from 5 minutes?

**Comment by EsterBergen** [comment]
Hi @Piyush-IT - Thanks for raising this. We'd need you to submit a feature request for this extension. We track Office Add-in feature requests on our [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. Thanks again!
