### ISSUE TITLE
Read formula error information by JavaScript API

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#4984]
Hello,

I would like to know if it's possible to read formula error information by JavaScript API. Here is an example of formula error:

![error-excel](https://github.com/user-attachments/assets/74e755d7-e602-48b5-9090-d26c29520a00)

Thank you

**Comment by qinliuMSFT** [comment]
Hello @chengtie , are you using Custom Function? If so, hope this article [Handle and return errors from your custom function](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-errors) can help you.

**Comment by chengtie** [comment]
> Hello @chengtie , are you using Custom Function? If so, hope this article [Handle and return errors from your custom function](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-errors) can help you.

Hello, I'm not using Custom Function.

Given a cell (e.g., E4), is there a JavaScript API to check if its formula raises an alarm and return the alarm type (e.g., "Inconsistent Formula")?

**Comment by qinliuMSFT** [comment]
Hi @chengtie , the Excel JavaScript API provides methods to check if a cell contains a formula and if there is an error. 
You can use the `Range` object to access the cell and its properties. Specifically, you can use the [formulas](https://learn.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#excel-excel-range-formulas-member) and [values](https://learn.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#excel-excel-range-values-member) properties to determine if a cell contains a formula and if there is an error.

Please refer to the following code snippet:

```
  await Excel.run(async (context) => {
    // Get the active cell
    const range = context.workbook.getActiveCell();

    // Load the necessary properties
    range.load(["formulas", "values"]);
    await context.sync();

    console.log(`Cell formulas:  ${range.formulas[0][0]}`);
    console.log(`Cell value: ${range.values[0][0]}`);
  });
```

For example, you will get output like this:
![{C914E7E0-3A9A-4F9D-B76A-0FB0B2322B9F}](https://github.com/user-attachments/assets/df12aa0e-0ab9-4858-a217-2a309f7a5a68)

Hope it's helpful.

**Comment by chengtie** [comment]
> Hi @chengtie , the Excel JavaScript API provides methods to check if a cell contains a formula and if there is an error. You can use the `Range` object to access the cell and its properties. Specifically, you can use the [formulas](https://learn.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#excel-excel-range-formulas-member) and [values](https://learn.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#excel-excel-range-values-member) properties to determine if a cell contains a formula and if there is an error.
> 
> Please refer to the following code snippet:
> 
> ```
>   await Excel.run(async (context) => {
>     // Get the active cell
>     const range = context.workbook.getActiveCell();
> 
>     // Load the necessary properties
>     range.load(["formulas", "values"]);
>     await context.sync();
> 
>     console.log(`Cell formulas:  ${range.formulas[0][0]}`);
>     console.log(`Cell value: ${range.values[0][0]}`);
>   });
> ```
> 
> For example, you will get output like this: ![{C914E7E0-3A9A-4F9D-B76A-0FB0B2322B9F}](https://private-user-images.githubusercontent.com/73509856/377692214-df12aa0e-0ab9-4858-a217-2a309f7a5a68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMjQ0NzMsIm5iZiI6MTcyOTIyNDE3MywicGF0aCI6Ii83MzUwOTg1Ni8zNzc2OTIyMTQtZGYxMmFhMGUtMGFiOS00ODU4LWEyMTctMmEzMDlmN2E1YTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE4VDA0MDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5NzJjYjhhNTZhYWFmYzg4MzkyMzM3OWFkM2Q1ZjJmOTllMjUxYmFkZDk2NzQxYmY5ZWZlOWU1NjRkZWIzNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J9pAEUNzy_AGcyuxzC0jT0XxRs_NrYou4mS9j0MTHNw)
> 
> Hope it's helpful.

Hello, I know these APIs you mentioned. But they don't return information like "Inconsistent Formula" shown in the screenshot of my initial question. My question is whether there is any API to return that information.

**Comment by qinliuMSFT** [comment]
@chengtie , thanks for the clarification, I understand your request now. I've put this case in our backlog #9455408 , and PG team will reply to you soon.

**Comment by adrianwu8516** [comment]
Hi @chengtie, We do not currently support this feature in Excel, and it would be helpful if you could also help us raise this in our [Tech Community](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) so that more people with similar requests can join and vote for this idea. Thank you very much for you suggestion!!
