### ISSUE TITLE
PowerPoint for Mac 16.90 is missing the `MicrosoftBuildNumber` information

### ISSUE THREAD

**Issue by jozefizso** [OfficeDev/office-js#4986]
# Provide required information needed to triage your issue

## Your Environment

* Platform: Mac
* Host: PowerPoint app
* Office version number: 16.90 (24101387)
* Operating System: macOS 14, macOS 15
* Browser: n/a
 
## Expected behavior
The `MicrosoftBuildNumber` information is in the `Info.plist` file in the `Microsoft PowerPoint.app` bundle.

## Current behavior

Our native (not office-js based) addin to PowerPoint is reading the `Info.plist` (the main bundle information) to check the version number of the Microsoft PowerPoint to determine if the bugfix for the event `PresentationCloseFinal` is applied.
The PowerPoint on macOS had a bug and the `PresentationCloseFinal` event was never called. This was fixed in the build `240422`. (See bug report here: https://github.com/jozefizso/powerpoint-vba-presentationclosefinal-event)

Our native Swift code must read this so our app can work with the correct events to clean up resources correctly.

The PowerPoint 16.90 (24101387) did remove the `MicrosoftBuildNumber` from the `Info.plist` file. This is a breaking change for out product.

Any administrative tool which reports the software information on macOS and is reading the `MicrosoftBuildNumber` value from the `Info.plist` file will have this issue too.

## Steps to reproduce
1. Write VBA macro which loads native `.dylib` app
2. The app in Swift code reads the `Bundle.main.infoDictionary?["MicrosoftBuildNumber"]` value
3. The app will use either `PresentationClose` or `PresentationCloseFinal` event based on the PowerPoint release.

## Link to live example(s)

This is a proprietary code so we cannot show it.

## Context

To correctly clean up native resources when customer closes a presentation file, we must know if the `PresentationCloseFinal` event is correctly implemented in the PowerPoint for Mac. To do so we must compare PowerPoint build number.

**Comment by qinliuMSFT** [comment]
Hello! This platform is dedicated to discussing and reporting issues related to the Office JS API. We have transferred the case to the PowerPoint team for further investigation and it has been put in backlog #9469028. Since we are unable to track its progress through this GitHub channel, we will be closing this issue here.

We appreciate your understanding and patience.
