### ISSUE TITLE
set the "link to previous" of a header as deactivate using office js

### ISSUE THREAD

**Issue by zeratul1215** [OfficeDev/office-js#4989]
Hi, I want to set the content of header and footer of each section of a file using office.js, but I noticed that if I want to set different content for header and footer of different sections, I need to tick off the "link to previous button" in the header setting, as shown in the screenshot
![image](https://github.com/user-attachments/assets/622f4910-1153-4d81-90cd-6577cbf62323)
is there any way I can deactivate this for each section using api?

**Comment by zeratul1215** [comment]
by the way, is there any way I can change the page margin for every section of the document

**Comment by qinliuMSFT** [comment]
Hi @zeratul1215 , the APIs to set `LinkToPrevious` and  `margin` for each section is not available in Word JS API right now. 

We recommend you to upvote or submit a new Tech Community New Ideas Item, we prioritize features based on community interest, as reflected by votes in our technical forums. Please consider voting for the link below to help us assess its importance relative to other requests.

[Office.js Add-in] Add functionality to set LinkToPrevious to Word Header/Footer sections](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/office-js-add-in-add-functionality-to-set-linktoprevious-to-word/idi-p/3033549)

[Allow changing page size and margin of each section of the document]
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/allow-changing-page-size-and-margin-of-each-section-of-the/idi-p/3049330
