### ISSUE TITLE
Compatibility addin office 2019

### ISSUE THREAD

**Issue by sebisebo** [OfficeDev/office-js#499]
Hi,
I developed an Excel addin using office.js and it work fine on excel 2013, 2016, 365 but on 2019 it just show a blank page on excel side panel. Any idea of this problem ?
I can put html code of the first page in case.
Thanks

**Comment by Rick-Kirkham** [comment]
Please provide some more information. Are you developing on Windows or a Mac?

**Comment by grangeryy** [comment]
Can you help to put more information on this issue? For example:

- Steps to Reproduce, or Live Example

- Context

- Your Environment & Platform:
Platform [PC desktop, Mac, iOS, Office Online]
Host [Excel, Word, PowerPoint, etc.]: 
Office version number: 
Operating System: 
Browser (if using Office Online): 

- Useful logs

- Console errors

- Screenshots

- Test file (if only happens on a particular file)

**Comment by grangeryy** [comment]
No more updated details for this issue. I'll close it for temp. If it reproduces with more details, we can reopen it.
