### ISSUE TITLE
how to on bookmark click event by word js api

### ISSUE THREAD

**Issue by anybody-1** [OfficeDev/office-js#4993]
i want to listen the bookmark click event by word js api, but i not found the relation api

**Comment by wangyun-microsoft** [comment]
Hi @anybody-1, can you explain your scenario and why you want this event? Thanks.

**Comment by anybody-1** [comment]
> Hi @anybody-1, can you explain your scenario and why you want this event? Thanks.

Hi, my scenario is that: 
i will check the document where has risk, then i'll show the risk list in add-ins taskpanel, i hope when  user click the text where has risk ,i can find the right risk in taskpanel

the method i used is that, i will insert bookmark on the risk text, when user click the bookmark ,i hope know the bookmark id to find the right risk card
i try to use comment or control to accomplish the goal, but it'll be perceived by users, because the comment event api is preview and it's will have a color or comment box, and the control will be has a box . bookmark is the solution that minimizes user perception.
or  can you give me some suggestion ?

**Comment by wangyun-microsoft** [comment]
Hi, 

There are multiple ways to do this:
1. Use Content Control. You could set content control as invisible so that end users don't see it ([appearance](https://learn.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview#word-word-contentcontrol-appearance-member)). Entering / Exiting content controls can be captured via events. 
2.  Annotation related APIs. The risky text can be annotated and highlighted. It shows Card UI to the end users for add-in suggestions. You can also capture the event when annotated text is hovered. https://learn.microsoft.com/en-us/javascript/api/requirement-sets/word/word-api-1-7-requirement-set?view=common-js-preview

**Comment by anybody-1** [comment]
> Hi,
> 
> There are multiple ways to do this:
> 
> 1. Use Content Control. You could set content control as invisible so that end users don't see it ([appearance](https://learn.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview#word-word-contentcontrol-appearance-member)). Entering / Exiting content controls can be captured via events.
> 2. Annotation related APIs. The risky text can be annotated and highlighted. It shows Card UI to the end users for add-in suggestions. You can also capture the event when annotated text is hovered. https://learn.microsoft.com/en-us/javascript/api/requirement-sets/word/word-api-1-7-requirement-set?view=common-js-preview

Thanks for your suggestion,  It seems that the first solution can solve my problem, i will try to it. the annotation is represents an annotation attached to a paragraph, it's can not insert by range. so, it's not meeting my needs, because i want to add a sign in  partial text in a paragraph. and I still hope to be able to monitor the click events of bookmarks, just like the comment events in preview api, do you have such a plan ?

**Comment by wangyun-microsoft** [comment]
Currently, we don't have plan for bookmark event. You could submit your requirement here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Office%20Add-ins%20deployment

Thanks.

**Comment by anybody-1** [comment]
> Currently, we don't have plan for bookmark event. You could submit your requirement here: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Office%20Add-ins%20deployment
> 
> Thanks.

Ok, thanks for your suguggestion

**Comment by RuizhiSunMS** [comment]
hi, @anybody-1 , did the first suggestion shared by wangyun resolve your problem? Please feel free to ask questions if there still be.

**Comment by anybody-1** [comment]
> hi, @anybody-1 , did the first suggestion shared by wangyun resolve your problem? Please feel free to ask questions if there still be.

i tried the first suggestion, and find  it's not perfect. because when i delete the text , the content control will prevent me from continuing to delete. i hope it  not affect user operations.

**Comment by wangyun-microsoft** [comment]
We don't have a recent plan to support Bookmark event. Please raise your request via this link: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Office%20Add-ins%20deployment

**Comment by anybody-1** [comment]
> We don't have a recent plan to support Bookmark event. Please raise your request via this link: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Office%20Add-ins%20deployment

Ok, I have already made my request by this link: 
https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/word-js-api-add-monitor-bookmark-events-just-like-comments/idi-p/4279327

**Comment by RuizhiSunMS** [comment]
Close this case since this is a feature request and the customer has submitted the request on our developer forum.
