### ISSUE TITLE
The Office.context.officeTheme.controlForegroundColor has a typo (in typings)

### ISSUE THREAD

**Issue by eblancperso** [OfficeDev/office-js#50]
The office-js typings file has a typo in the interface's property

## Expected Behavior
In the interface OfficeTheme, the property should be spelled "controlForegroundColor"

## Current Behavior
The property is spelled "controlForgroundColor"

## Steps to Reproduce, or Live Example
Open the index.d.ts file and go to line 247. The property is spelled "controlForgroundColor" instead of "controlForegroundColor"

## Your Environment
PC
Windows 10
"dependencies": {
    "@microsoft/office-js": "^1.1.2"
  }
"devDependencies": {
    "@types/office-js": "0.0.50",
}

**Comment by Zlatkovsky** [comment]
Thanks for reporting.  Just submitted it as a fix on DefinitelyTyped.  Closing here.
