### ISSUE TITLE
Spam Addins are not shown in Semi-annual channels.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#5010]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 2402 Build 17328 20612
* Operating System: Windows 10
* Browser (if using Office on the web): NA
 
## Expected behavior

Spam addins should be shown in all outlook client versions.

## Current behavior

The spam addins are not shown in semi-annual channels.

## Steps to reproduce

1. Setup a semi-annual channel outlook.
2. Install a spam addin.
3. Spam addin does not show in the outlook client.

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by timwan10** [comment]
Spam Add-ins are only available for in the SAC channel on builds 16.0.17928.XXXXX and later. 

It is available on Monthly Channels on build: 16.0.17530.15000 and later. 

See documentation here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/spam-reporting?tabs=jsonmanifest#supported-clients

There is no plan to backport this feature to 2402 build.

**Comment by glr0221** [comment]
@timwan10 

thank you for these additional details. I am currently basing my version numbers using this reference semi[-annual channel update list](https://learn.microsoft.com/en-us/officeupdates/semi-annual-enterprise-channel#version-2402-october-08).  And in that list the latest seems to be **Version 2402 (Build 17328.20612)**.

It seems that semi-annual-enterprise (SAE) preview is the one that has a build 2408. Will the non-preview SAE eventually get the Build 2408 update?

This [reference on update history ](https://learn.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date) also shows the same information.

Thank you again.

**Comment by timwan10** [comment]
The Semi-Annual Channel updates on a 6 month cadence. 

according to this link: https://learn.microsoft.com/en-us/microsoft-365-apps/updates/overview-update-channels

It should update the second Tuesday in Jan and July.

**Comment by glr0221** [comment]
thank you @timwan10 . Would you know if the next update for semi-annual will include the new runtime engine? Thank you.

**Comment by timwan10** [comment]
I don't think we can officially comment on when the V8 engine will make it into SAC. If the engine is NOT on in the current SAC Preview build, I would assume it will light up in the NEXT Sac **Preview** build, but as always this isn't confirmed until closer to when those builds come out, as things can always happen.
