### ISSUE TITLE
It is not possible to open the default mail software via the Excel Addin

### ISSUE THREAD

**Issue by fabiorich-ico** [OfficeDev/office-js#5011]
I am trying to open a blank e-mail (with the OS default programme) with the recipient set.

## Your Environment
- Platform [PC desktop]: PC desktop
- Host : Excel
- Office version number: (Version 2409 Build 16.0.18025.20030) 64 bit
- Operating System: Windows 11 pro
 
## Expected behavior
I am trying to open a blank e-mail (with the OS default programme) with the recipient set via `mailto:` pattern

## Current behavior
I have tried different ways to open an empty mail but none of them work:
- html tag `a` with href set to `mailto:user@mail.com`
- use `Office.context.ui.openBrowserWindow` with url `mailto:user@mail.com` (with the working browser)
- use `Office.context.ui.displayDialogAsync` with url `mailto:user@mail.com`

## Steps to reproduce
I used scriptlab to reproduce the bug:

``` ts
$("#opendia").on("click", () => tryCatch(openDialog));
$("#openwin").on("click", () => tryCatch(openWindows));

async function openDialog() {
  await Excel.run(async (context) => {
    const url = "mailto:user@mail.com";
    Office.context.ui.displayDialogAsync(url, { height: 75, width: 80 });
    await context.sync();
  });
}

async function openWindows() {
  await Excel.run(async (context) => {
    const url = "mailto:user@mail.com";
    Office.context.ui.openBrowserWindow(url);
    await context.sync();
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}

```

``` html
<a id="hrefto" class="ms-Button" href="mailto:user@mail.com" target="_blank" >Href to</a>
<button id="opendia" class="ms-Button">
    <span class="ms-Button-label">Open Dialog</span>
</button>
<button id="openwin" class="ms-Button">
    <span class="ms-Button-label">Open Windows</span>
</button>
```

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuizhiSunMS** [comment]
hi @fabiorich-ico , thx for the submit.
I did a quick try. 
For the 'ahref', the console showed an alert like below. It looks this action is banned.
![image](https://github.com/user-attachments/assets/bb8d926b-c6c1-466f-825a-5e6e1e726191)
For using 'Office.context.ui.displayDialogAsync', as the doc https://learn.microsoft.com/en-us/office/dev/add-ins/develop/dialog-best-practices saying, the url passed to displayDialogAsync must be 'https'.
For using openBrowser, looks 'mailto' doesn't work while 'https' and 'http' are ok. I will reach out to experts to confirm.

**Comment by RuizhiSunMS** [comment]
Hi, @fabiorich-ico. Experts in APIs like openBrowser confirmed that, only http and https are available in openBrowser.
