### ISSUE TITLE
Sideloading rejected by Exchange

### ISSUE THREAD

**Issue by vgpastor** [OfficeDev/office-js#5012]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): Chrome
 
## Expected behavior

Install the add-on and works

## Current behavior

When upload the manifest manually https://reports.zepo.ai/btn-outlook/manifest.xml whe received an error `{"error":{"code":"BadRequest","message":"Sideloading rejected by Exchange"}}``

## Steps to reproduce

1. Download manifest https://reports.zepo.ai/btn-outlook/manifest.xml
2. Open Outlook and try to add add-in manually.
3. Upload the manifest downloaded and the error happends

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. In the previous versions this error doen't appear, only start to appear when we enable Mobile Add-On

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by DivyaPatidar** [comment]
@vgpastor We could successfully install the shared manifest on our end. Additionally, I do not see MobileFormFactor in this manifest. Could you please share both versions of the manifest: the working one and the non-working one?"

**Comment by strtob** [comment]
That's really a shame! Microsoft has decided not to include this function in Outlook. Especially when it comes to appointments, Office.js doesn't make sense without this feature for Outlook. It would be better to invest your development time in other platforms, like Android or iOS.
