### ISSUE TITLE
Identify the encryption status of an Outlook email programmatically using the Office API or alternative methods

### ISSUE THREAD

**Issue by AacharanJain** [OfficeDev/office-js#5013]
Hello,

We are developing an Outlook add-in using React and need to determine if the currently opened email is encrypted. We want to identify the following encryption types:
- Encrypt Only
- Confidential
- Highly Confidential
- Do Not Forward

Our use case requires certain functionalities in our add-in to be restricted based on whether the email is marked as "Confidential" or "Do Not Forward."
Adding a screenshot to show where the encryption type can be viewed when sending an email via Outlook:

![image](https://github.com/user-attachments/assets/b9ecfcd6-f354-4ba3-b1c5-0e8847e81524)

We have attempted to use both the Office.js API and Graph API to retrieve any attributes that would help us identify the email's encryption status. However, we haven't been able to find a way to access this information.

We attempted the following approach, but it doesn’t meet our requirements:

**Office.context.mailbox.item.sensitivity**: This property associates the sensitivity level of an email, such as Normal, Personal, Private, or Confidential. A screenshot is attached for reference, showing where these options appear in Outlook:

![image](https://github.com/user-attachments/assets/156e6b30-1d6b-47c6-a9e1-4e6d348574cc)

Could anyone provide guidance or suggestions on how to fetch the encryption status ("Encrypt Only", "Confidential", "Highly Confidential", "Do Not Forward") of an email using the Office.js API or Graph API? Any insights would be greatly appreciated!

Thank you in advance for your help!

**Comment by DivyaPatidar** [comment]
@AacharanJain At present, the feature to retrieve the email's encryption status is not available as part of Office.js API set. This is will considered as a new feature request. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

For checking availability of such API on MS API Graph, please explore options available at [Microsoft Graph Dev Center | APIs and app development](https://developer.microsoft.com/en-us/graph)
