### ISSUE TITLE
The new Outlook will only launch the add-in for primary accounts.

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#5018]
## Your Environment

* Platform : PC desktop
* Host : New Outlook
* Microsoft Outlook version1.2024.1009.100 (Production).
* Operating System: Windows OS
 
## Issue
There has been an official release about the new Outlook, but the add-in issue has not been resolved.
Currently, Despite the [documentation](https://support.microsoft.com/ja-jp/office/outlook-%E3%81%A7%E3%82%A2%E3%83%89%E3%82%A4%E3%83%B3%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%99%E3%82%8B-1ee261f9-49bf-4ba6-b3e2-2ba7bcab64c8) describing how to use the add-in, the add-in is only activated on the primary account and does not work on the secondary account.
Typically, add-ins must be activated in all profiles.
I also asked about this issue on https://github.com/OfficeDev/office-js/issues/3996. When will this be available for add-ins for secondary accounts?
Also, where do you plan to announce when they are available?
As it stands, we are unable to recommend the use of the new Outlook to our customers.

**Comment by DivyaPatidar** [comment]
@mailchecktool-admin This issue is anticipated to be resolved by the end of this calendar year. You can check roadmap [here](https://www.microsoft.com/en-us/microsoft-365/roadmap?filters=&searchterms=412936) for updates on multi-account support for Add-ins.
