### ISSUE TITLE
Outlook add-in token verification method

### ISSUE THREAD

**Issue by e-vidyaraghavi** [OfficeDev/office-js#5019]
# Outlook add-in token verification method

Hi,

I have adopted the OfficeRuntime.auth.getAccessToken() method for getting the token. For validating the token, used server side code as suggested in this [document](https://learn.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins?tabs=jsonmanifest#pass-the-access-token-to-server-side-code)

The document says that the **aud in the token will be the client-id** of the app registered in Azure portal, but however I'm getting the Resource URI as given for the app in azure. Can you please confirm which one should we use to validate? the client-id or the resource URI 

**Note**: Sometimes we get client-id, sometimes resource URI

Looking forward to your answer!

Thanks

**Comment by mmanjaree-msft** [comment]
The difference could be depending on whether its v1 or v2 token https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens#validate-tokens. It could be both App id or uri as mebtioned here- https://learn.microsoft.com/en-us/entra/identity-platform/access-token-claims-reference#payload-claims.
please let us know if this helps in validation

**Comment by e-vidyaraghavi** [comment]
Hi,

Thank you for your reply. I'm only calling
the OfficeRuntime.auth.getAccessToken() JS method for getting the tokens,
how to differentiate whether it's v1 or v2?

Regards,
Vidya raghavi

**Comment by mmanjaree-msft** [comment]
Along with aud there should be a ver value as well in the token itself

**Comment by e-vidyaraghavi** [comment]
How the version is determined? Like how the version is v1 or v2? Also what are the possible versions?

This is important to me as for validating the token from this JS method OfficeRuntime.auth.getAccessToken()

**Comment by e-vidyaraghavi** [comment]
Also please let me know how to change the version that we get in OfficeRuntime.auth.getAccessToken({ allowSignInPrompt:true, allowConsentPrompt:true})??

Should we do changes in app registration , this would greatly help

**Comment by anjalitp** [comment]
@e-vidyaraghavi Please refer to the doc here https://learn.microsoft.com/en-us/entra/identity-platform/access-tokens#token-formats which mentions
"Set the version for applications by providing the appropriate value to the accessTokenAcceptedVersion setting in the [app manifest](https://learn.microsoft.com/en-us/entra/identity-platform/reference-app-manifest#manifest-reference). The values of null and 1 result in v1.0 tokens, and the value of 2 results in v2.0 tokens."
