### ISSUE TITLE
Outlook NAA throws invalid_client if add-in URL has a route path

### ISSUE THREAD

**Issue by dariussantaras** [OfficeDev/office-js#5020]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows
* Browser (if using Office on the web): Edge
 
## Current behavior

When an add-in is hosted under a path of a domain instead of the root, request to get an NAA token fails with:
```
ServerError: invalid_client: AADSTS700046: Invalid Reply Address. Reply Address must have scheme brk-9199bf20-a13f-4107-85dc-02114787ef48:// and be of Single Page Application type. Trace ID: ceab5b13-a000-465f-8251-7c5adcd31800 Correlation ID: 0192d8b4-701b-72cc-ba3a-7fec9cf9806c Timestamp: 2024-10-29 14:35:42Z
```

I would expect it to work the same regardless of where the static files are.

Is there any other config that needs to be set up differently?

## Steps to reproduce

1. Configure addin manifest to point the taskpane to a domain with a route (like `https://example.com/my/path/taskpane.html`)
2. Have the app registration in Entra set up with a SPA redirect to `brk-multihub://example.com` (I tried adding the full path too with no effect `brk-multihub://example.com/my/path`)
3. Launch the addin to try to get an NAA token and it will throw the error
4. Change the URLs to be at the root of the domain
5. NAA works

**Comment by codexeon** [comment]
I am not able to repro this issue, path should not be used in NAA. If you could provide more details on what SPA redirect URI you have registered in your AAD application it may help to diagnose. I can see that you mention `brk-multihub://example.com/my/path` which is an invalid redirect URI for NAA, it should be `brk-multihub://example.com` assuming your page is `https://example.com/my/path/taskpane.html`. I would recommend removing the invalid redirect URI from your registration, in case it is causing an issue. Other than that, if there is a repro or code sample you could provide it would help.

I tried https://github.com/OfficeDev/Office-Add-in-samples/tree/main/Samples/auth/Outlook-Add-in-SSO-NAA sample with changing the output path to include a sub directory. From https://localhost:3000/test/taskpane.html page with just `brk-multihub://localhost:3000` registered in AAD the sample was working in Outlook Web.

**Comment by dariussantaras** [comment]
I can't reproduce it anymore myself, I must have done something different and have some sort of configuration issue.
I'll close this because it seems like my issue is somewhere else
