### ISSUE TITLE
Issues with Adding New Row with colSpan in Tables Using Office.js Word API

### ISSUE THREAD

**Issue by badi4net** [OfficeDev/office-js#5024]
Hi Team,

We are developing a Word add-in using the Office.js (Word API), and we are facing some challenges.

My Environment:
Platform: PC Desktop
Host: Word
Office Version: Microsoft® Word for Microsoft 365 (Version 2304 Build 16.0.16327.20200) 64-bit
Operating System: Windows 10 Pro

Issue Description:
I’m having trouble adding a new row with `colSpan` in tables. I’m using the following code:

```javascript
// Set colspan if there is a next cell to compare with (for merged cells)
const newCell = table.rows[rowIndex].insertCell(colIndex);
newCell.colSpan = 2;
await context.sync();
```
This doesn’t work as expected in non-uniform tables, even though it works fine in uniform tables. This limitation is affecting our ability to manipulate tables effectively.

I would appreciate any guidance or solutions you could provide to help us with this issue.

Thank you in advance for your help!

**Comment by jonahkarpman** [comment]
Thank you for reporting and providing detailed information about this issue! I've assigned this issue to our SME for further investigation.

**Comment by jonahkarpman** [comment]
A bug (9494731) has been created to investigate this issue.

**Comment by RuizhiSunMS** [comment]
Hi @jonahkarpman, thx for the submit. 
May I confirm with you that, you want to use js api to make operations on a Word.Table? If yes, as far as I know, Word.Table is different from html table. One can't use an API which is not in the Word js API list to operate Word.Table. For example, insertCell is a js api while Word doesn't support it.

**Comment by jipyua** [comment]
@jonahkarpman thanks for the information. As mentioned, so far there is no insertCell js API on TableRow object. For the non-uniform tables you mentioned. I have one non-uniform one as below, and using no matter TableRow.insertRows("Before", 1) or TableRow.insertRows("After", 1) is working correctly. Would you please clarify more what you mean for not working in non-uniform table? thanks.
![image](https://github.com/user-attachments/assets/dc8300de-7821-4015-a31b-3f0074c33823)

**Comment by badi4net** [comment]
@jipyua  Thank you for your response. I want to add or update an existing row with rowspan and colspan values in a non-uniform table structure. The insertRow method (Office API) is not working for this functionality, so I am using the insertCell method (JS API). However, it's not rendering properly in Word. Could you please help me with the correct solution for handling colspan and rowspan values in a non-uniform table structure?

**Comment by RuizhiSunMS** [comment]
@jonahkarpman, would you please share some examples about what is the expected table you want to have and what is the current table you got after running some code.
