### ISSUE TITLE
AutoShowTaskpaneWithDocument for DocumentCreated on Word JS API

### ISSUE THREAD

**Issue by shinji-morimitsu** [OfficeDev/office-js#5030]
Are there anyway to set 'Office.AutoShowTaskpaneWithDocument' for Word.DocumentCreated object?

We are planning to implement to open a Word file on the our server. And we expect it would be opened with AddIn opened.

So, that means, I want to set 'Office.AutoShowTaskpaneWithDocument' for Word.DocumentCreated object.
Is it possible?

**Comment by RuizhiSunMS** [comment]
Hi @shinji-morimitsu , thx for the submit. Is this doc talking about what you are interested in https://learn.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document?
And btw, please add some information like which platform you aim to and the impact of your addin and others. These would be helpful for us to triage quickly.

**Comment by shinji-morimitsu** [comment]
@RuizhiSunMS 
Thanks for your reply.

>Is this doc talking about what you are interested in https://learn.microsoft.com/en-us/office/dev/add-ins/develop/automatically-open-a-task-pane-with-a-document?

Yes, right. That way on the page works for the current Word document. My expectation is that Word.DocumentCreated.open() works with addin started state.

Target platform is Word on both PC and Mac.

**Comment by RuizhiSunMS** [comment]
hi @shinji-morimitsu , that doc says autoopen feature is available to both word, excel and ppt for all platforms, including web, win32 client and mac. Looks your target platforms are all included.

**Comment by shinji-morimitsu** [comment]
Thanks. @RuizhiSunMS 
The doc is for the current document, and it is for on re-opening the document.

For example, there is 2 documents. document A and B. Both document do not have a setting to auto-open yet.
Now, my addin is working with document A, and trying to open document B from the Addin by using Word.DocumentCreated.open().
My question is if there would be the way to auto-open my addin at Word.DocumentCreated.open().

**Comment by RuizhiSunMS** [comment]
Hi @shinji-morimitsu , thx for the sharing. Create #9501870 to track this case (or QA I shall say). The team will investigate and we will reply to you as soon as there is any progress. Thank you for your patience.

**Comment by jipyua** [comment]
hi @shinji-morimitsu in order for the auto-open to work, you need to insert the addin in the document and call set setting API. So you can in document A make the auto open work and save the document. Then get the base64 of document A as the CreateDocument() parameter to see whether the newly created document with base64 supports auto-open. If document B is created as a blank document then auto-open will not work as the addin and setting hasn't been set on Document B yet.

**Comment by shinji-morimitsu** [comment]
Hi @jipyua 
Thanks for your reply. I understood, currently it is hard to make addin auto open via CreateDocument.
My addin is a sort of front-end of SaaS software, and the SaaS software stores user's word documents.
Now I'm adding 'file open' functionality from our server in our addin.
Therefore, it would be useful that our addin starts automatically with the opened document from our addin.
(Because we can not ensure the documents on our server have 'addin auto start' configuration.)

I expect addin-auto-open via CreateDocument would be implemented future.

**Comment by RuizhiSunMS** [comment]
Close this bug since the answer is provided.
