### ISSUE TITLE
Calling `item.body.getAsync` returns different results and possibly incomplete data

### ISSUE THREAD

**Issue by GirtsJermacans** [OfficeDev/office-js#5036]
# Provide required information needed to triage your issue
We've been processing body of `coerciontype 'html'` returned from `item.body.getAsync` when sending new mail item. If inline images are included, then up until now, the method call would always return a body with `img tag` that contains `src attribute` in it. The `src attribute` as well as `img tag `would differ slightly, depending on the platform and how the inline image is added to the message, however attribute itself would always be present.

Just recently, without a specific reason, for Environment B and Environment C (see below), and potentially other environments, `item.body.getAsync` started to return `img tag` without `src attribute` in it, therefore without some of the data usually associated with it.

This is causing issue to process the body correctly.

I have seen this [issue](https://github.com/OfficeDev/office-js/issues/4894) for mac, but it seems that it does not relate to the issue described above.

## Your Environment
3 different environments
### Environment A:
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 20241018004.22
* Operating System: Windows 11 enterprise
* Browser (if using Office on the web): Chrome

### Environment B:
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 20241025003.17
* Operating System: Windows 11 enterprise
* Browser (if using Office on the web): Chrome

### Environment C:
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 20241018004.21
* Operating System: macOS Sonoma Version 14.7
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Calling `item.body.getAsync` returns html body with image tag, that has `src` and `originalsrc` attribute in it. See below example for Environment A:
<img width="853" alt="image" src="https://github.com/user-attachments/assets/4634eceb-7d3c-431d-a73f-741c52fff6d1">

## Current behavior
For Platform B and C, calling `item.body.getAsync` returns html body with image tag, that has only 'originalsrc' attribute in it. See below example for Environment B and C:
<img width="848" alt="image" src="https://github.com/user-attachments/assets/24fc0b93-0630-4f14-a470-1d5ec4481568">

With this behavior, it is not possible to identify, for example, which attachment it is when getting attachments using `item.getAttachmentsAsync` method call. `Src attribute` contains `id`, which has 1 to 1 relation with `id` property on  `Office.AttachmentDetailsCompose` type. In some cases, it also has attachment content itself, which is a workaround for this [issue].(https://github.com/OfficeDev/office-js/issues/5031). Additionally, consistency is helpful, when processing data.

## Steps to reproduce
1. By using Environment B or C, start composing new mail.
2. Copy-paste an png or jpg into the message body as inline image (additionally, you can add it as message attachment, then right click and move it into message body as inline image - result will be the same).
3. Click send.
At this point check the value that is returned by `item.body.getAsync` of coerciontype 'html'. You will get html body with `img tag` that has no `src attribute` in it.

## Context

Our Addin processes information provided by the html body, including the inline attachments, performs some checks on it, and then creates a modified html body based on that information.#
It is important to match up the inline image on the html body, with what is returned from `item.getAttachmentsAsync`. Getting back just `cid` in `originalsrc` has no relation to any of the ids that are available on `Office.AttachmentDetailsCompose` interface, essentially making that inline attachment unknown to the rest of the app.
Up until now, src attribute always returned just enough to be able to work with it, however now for Environment B and C, it simply started to give back this different body. It could be that this is happening in other environments, and is not related just these specific ones.

## Useful logs
We use `@types/office-js version 1.0.401`.
Here is example code how to get html body:
```
function getMailbox() : Office.Mailbox {
	const result = getContext().mailbox;
	if (result) {
		return Office.context.mailbox;
	}
	throw new Error();
}

function getMailboxItem() : MailboxItem {
	const result = getMailbox().item;
	if (result) {
		return result;
	}
	throw new Error();
}

getItemBodyAsync(): Promise<string> {
      return new Promise((resolve, reject) => {
	      this.getMailboxItem().body.getAsync('html', (asyncResult) => {
		      if (asyncResult.status === Office.AsyncResultStatus.Failed) {
			      reject(asyncResult.error);
		      } else {
			      resolve(asyncResult.value);
		      }
	      });
      });
}
```

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by mmanjaree-msft** [comment]
Could you please confirm if you get the same response for every image copied from different sources? As per a repro we had, sometimes we do get src attribute as well.

**Comment by gauravsoni119** [comment]
We are also facing similar issues from past couple of days. Our add-in is also relying on `getAsync` to get body. But now for inline attachments it has `originalsrc` only which is causing issues for our add-in as well.

**Comment by geoffreyreemer** [comment]
Confirming the same issue for us. Since `originalsrc` only returns the `cid` (which we can't support in our add-in), it means that inline images aren't processed well anymore, leading to potential data loss. Could this please be looked into as soon as possible?

**Comment by mmanjaree-msft** [comment]
@geoffreyreemer @gauravsoni119 @GirtsJermacans Could you please share how are these images or attachments added to body in your cases. I was able to repro the issue but only sometimes. Looking for any recent change that might have broken this but meanwhile knowing the source of attachments in your cases would help

**Comment by GirtsJermacans** [comment]
@mmanjaree-msft  Just checked on Environment B following ways to add inline images.
**For the following scenarios, the body is missing src attribute:**
- Add as attachment, then move into message body.
- Open file directory, single click on image, copy it and paste it into the body.
- Use some snipping tool - create a snip, paste it into the body.
- Select following - 'Insert - Pictures' and select the image (it should add it to the body)

**For the following scenarios, the body has src attribute**
- Create a signature, compose new mail, insert signature to the body, click send.
- Create a signature, select it to appear automatically on compose new mail, compose new mail, click send.

Img tag example for the above 2 scenarios:
`<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAdUAAAEHCAYAAAD4T9zTAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFxEAABcRAcom8z8AAP+lSURBVHhebL0FlF/V9b89E5+4ezLRmehk4u7uIY7T4FacIsUpxQqUIi1OoVAoxVqgeKGlFEpxd5dAAjFCsP0+z87crPT3/r9r3XXv994j+9j+nL3PPvuUlJTsEyW19o2SntybcpXw3JV725rntjX/....... and so on...." id="image_0" style="max-width: 424px;">`

I think this covers all the possible scenarios, how to add inline image. Will confirm a bit later today if the Environment C, has the same outcomes.

**Comment by gauravsoni119** [comment]
> @geoffreyreemer @gauravsoni119 @GirtsJermacans Could you please share how are these images or attachments added to body in your cases. I was able to repro the issue but only sometimes. Looking for any recent change that might have broken this but meanwhile knowing the source of attachments in your cases would help

@mmanjaree-msft we have similar steps mentioned by @GirtsJermacans. While composing, use  'Insert - Pictures' and select the image.

**Comment by GirtsJermacans** [comment]
> @mmanjaree-msft Just checked on Environment B following ways to add inline images. **For the following scenarios, the body is missing src attribute:**
> 
> * Add as attachment, then move into message body.
> * Open file directory, single click on image, copy it and paste it into the body.
> * Use some snipping tool - create a snip, paste it into the body.
> * Select following - 'Insert - Pictures' and select the image (it should add it to the body)
> 
> **For the following scenarios, the body has src attribute**
> 
> * Create a signature, compose new mail, insert signature to the body, click send.
> * Create a signature, select it to appear automatically on compose new mail, compose new mail, click send.
> 
> Img tag example for the above 2 scenarios: `<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAdUAAAEHCAYAAAD4T9zTAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAAFxEAABcRAcom8z8AAP+lSURBVHhebL0FlF/V9b89E5+4ezLRmehk4u7uIY7T4FacIsUpxQqUIi1OoVAoxVqgeKGlFEpxd5dAAjFCsP0+z87crPT3/r9r3XXv994j+9j+nL3PPvuUlJTsEyW19o2SntybcpXw3JV725rntjX/....... and so on...." id="image_0" style="max-width: 424px;">`
> 
> I think this covers all the possible scenarios, how to add inline image. Will confirm a bit later today if the Environment C, has the same outcomes.

Checked - Environment C has the same results.

**Comment by mmanjaree-msft** [comment]
We have the bug in our backlog. We haven't root cause or any eta to share at this point.
Internal tracking id: 5054071

**Comment by arpitsangwanmsft** [comment]
Hey @GirtsJermacans !
Fix for this issue has reached 100% world-wide, so this should be resolved now. Please re-validate the scenario and let us know.
Thanks!

cc: @gauravsoni119 / @geoffreyreemer

**Comment by geoffreyreemer** [comment]
@arpitsangwanmsft Thanks! It seems to be fully solved for us now. Have a great final days of the year, and Happy 2025! 👍

**Comment by gauravsoni119** [comment]
@arpitsangwanmsft Thank you for fixing it. It's working as expected in our Add-in now. Have a great 2025!
