### ISSUE TITLE
Office.context.mailbox.item.body.setSignatureAsync throws error when File Block settings is set to "Open in protected view"

### ISSUE THREAD

**Issue by MrDaleQ** [OfficeDev/office-js#5038]
When calling Office.context.mailbox.item.body.setSignatureAsync this throws an error when the GPO setting "File Block settings" is set to "Open in protected view"

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2410
* Operating System: Windows 11
 
## Expected behavior
Expected behaviour is for Outlook to insert the signature as when the GPO setting is not enabled.

## Current behavior

Calling this API with the GPO set results in the following response:

{"name":"InternalError","message":"The operation failed.","code":5001}

## Steps to reproduce
As above - this error occurs when the following Office ADMX template GPO setting is used:

Admin Templates > Microsoft Word 2016 > Word Options > Security > Trust Center > File Block Settings > Web Pages.

Enabled. Set to "open files in protected view"

## Context
This prevents setsigasync from inserting a signature

**Comment by mmanjaree-msft** [comment]
Does the signature contain any inline images?

**Comment by MrDaleQ** [comment]
Hi @mmanjaree-msft 

Yes, this is seen when an inline image is inserted as part of the HTML source using an inline IMG tag

**Comment by anjalitp** [comment]
@MrDaleQ   Are you experiencing this problem on Classic Outlook or the New Outlook on Windows?
