### ISSUE TITLE
Get Permissions from Outlook Add-in from Javascript

### ISSUE THREAD

**Issue by garrit-schroeder** [OfficeDev/office-js#504]
Get Permissions from Outlook Add-in from Javascript.

I would like to enable / disable features based on the permissions the add-in has.
Is it possible to detect the Permissions set in the manifest.xml file installed in outlook?

The idea is to distribute multiple Manifest with different Permissions and enable / disable features based on the permissions set.

Greetings and thanks for your help.

**Comment by exextoc** [comment]
Bug 1100593<https://o365exchange.visualstudio.com/959adb23-f323-4d52-8203-ff34e5cbeefa/_workitems/edit/1100593>: [OfficeDev/office-js] Get Permissions from Outlook Add-in from Javascript (#504)


Created using VSTS Outlook add-in<https://www.owiki.ms/wiki/VSTS_Add-In_for_Outlook>

**Comment by exextoc** [comment]
If you are distributing multiple manifests, then an easy way to accomplish this is to change the URL that each manifests redirects to. (and have each separate file behave differently on your end). You could also just tag a query parameter to the end of each. i.e. http://contoso.com/index.php?permissionLevel=restricted

**Comment by garrit-schroeder** [comment]
Thanks, great idea.
