### ISSUE TITLE
Add-in passes validation, but cannot be installed after adding WebApplicationInfo.

### ISSUE THREAD

**Issue by J4Wx** [OfficeDev/office-js#5045]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: All?
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Microsoft Outlook Version 1.2024.1023.300 (Production).
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

When installing Office Add-In that passes all validation, that addin should install.

## Current behavior

The addin installs fine, until I add WebApplicationInfo.
The addin always passes validation.

## Steps to reproduce

1. Attempt to install manifest (either via Sideloading, or Integrated Apps)
2. Get Error

## Link to live example(s)

1. Sanitized example manifest will be provided in a comment. I will happily provide the actual manifest via direct message.

# Provide additional details

1. ______
2. ______
3. ______

## Context

I want to install an add-in for the purposes of development.
I cannot.
Not being able to do a thing that you want to do is generally perceived as being bad.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
None. Exchange provides no feedback when it fails to install an addin.

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by J4Wx** [comment]
[wlm-addin-cleansed.xml.txt](https://github.com/user-attachments/files/17634430/wlm-addin-cleansed.xml.txt)

**Comment by J4Wx** [comment]
Might be relevant:

The EAC Integrated Apps install process detects scopes, correctly asks for permissions, etc. So it doesn't appear to be a case of the WebApplicationInfo being malformed.

**Comment by anjalitp** [comment]
@J4Wx Would it be possible to share the actual manifest? You can host it on a private repo and share the access with 
@exextoc

**Comment by J4Wx** [comment]
@anjalitp https://github.com/J4Wx/wlm-manifest/invitations

**Comment by anjalitp** [comment]
@J4Wx  The reason for installation failure is "The domain part of this URI must match the domain, including any subdomains, used in the URLs in the <Resources> section of the add-in's manifest" . The url defined for id="FunctionFile.Url" is violating this condition. Could you please update and try?
We have documented this here https://learn.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins?tabs=xmlmanifest#configure-the-add-in
