### ISSUE TITLE
Addition or deletion of the comment triggers paragraph events in Word.

### ISSUE THREAD

**Issue by neer3** [OfficeDev/office-js#5049]
#### Note: The issue is happening in standalone Word application.

So I am utilizing `onParagraphDeleted` and `onParagraphAdded` on the document to check on the paragraphs but apparently, these events are also getting triggered when we add or delete a comment for any paragraph.

## Your Environment

* Platform: [PC desktop, Mac, Office on the web]
* Host: Word
* Office.js version number: 1.1
* Word application version: 2410
* Operating System: Windows 10
 
## Current behavior

When we are trying to add a new comment to a paragraph the `onParagraphAdded` is getting triggered and on deletion of the comment the `onParagraphDeleted` event is getting triggered.
(Comment is for the whole paragraph)

I can only reproduce this issue on the Word standalone application on both Windows and Mac, but on the browser I am not able to reproduce this issue.

## Steps to reproduce

1. Add a comment to an already existing paragraph.
2. Delete the comment from the paragraph.

## Expectation
I want some conditions to differentiate the comment from a paragraph event.
I am aware that a comment would be considered a paragraph with the styling of `Comment Text` (in case of addition).
What would be the case of the comment deletions?

**Comment by RuizhiSunMS** [comment]
hi @neer3, thx for your submit. 
Would you please confirm that how you trigger the event? By my test, only adding comment with multiple lines will trigger what you mentioned. Like the below screenshot, only 1 and 3 triggered. 
![image](https://github.com/user-attachments/assets/7e428621-5a9d-4193-a791-c159e67e7c1e)
And would you please also share the platform you are using?

**Comment by neer3** [comment]
Hi @RuizhiSunMS, I am using Word on Windows (shared the version details in the initial post).

I am adding comments with both multi-lines and single lines with more than 300 characters (no new line in single line comment). Both of'em are triggering the paragraph events.

Also, please check for deletions also whenever we delete the comments the events are also triggered.

**Comment by RuizhiSunMS** [comment]
@neer3, just want to make sure the target platform. Web works well at my side. What about your side?
And allow for deletion, deletion can always trigger the event while only adding multi lines comment can trigger it. If just one line added, the event won't be trigger whatever the string is long or not.
Anyway, it looks confusing indeed. Create #9513600 into our backlog to track it. The team will investigate and we will reply to you as soon as there is any progress. Thank you for your patience.

**Comment by neer3** [comment]
@RuizhiSunMS, on my side I am also not able to produce this issue on the web.
You are correct; only one line is not triggering the event. Apparently, the longer sentence I was using had a new line inside of it.

But in case of deletion the deletion event is getting triggered for any type of comment multi or single line.

**Comment by RuizhiSunMS** [comment]
@neer3 Thx for your confirmation. Our team folks would investigate it.

**Comment by cbouzmsft** [comment]
Hi. Since paragraph inside comments are not supported, the corresponding paragraph events will be disabled as a fix. Regarding the question about filtering, I would leverage parentBody.type (MainDoc, Header, Footer, ...).

**Comment by neer3** [comment]
hi @cbouzmsft, we can load the properties when we are adding any new comment or paragraph but what should we do in case of deletion as when we try to load those deleted content properties I am getting errors (as the property is deleted).

**Comment by cbouzmsft** [comment]
That is correct, you cannot retrieve information from a deleted object.

**Comment by neer3** [comment]
Alright, it seems like we need to address the deleted content separately.

And for added I can rely on their styling to figure out between paragraph and comment as comment would have `comment text` as style.
