### ISSUE TITLE
Outlook Add-in (All Addins) automatically enabled pinning functionality 

### ISSUE THREAD

**Issue by rohanbharadwaj1994** [OfficeDev/office-js#5054]
# Provide required information needed to triage your issue
It appears that all store add-ins, including ours, now have the pinning functionality enabled by default. Despite not specifying the SupportsPinning property in our manifest, the pinning feature is active for our add-in which we don't want.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: MacOS
* Browser (if using Office on the web): Chrome
 
## Expected behavior

The pinning functionality should only be enabled for add-ins where SupportsPinning is explicitly defined in the manifest.

## Current behavior

Currently, Pinning feature is enabled by default for all store add-ins, including ours, despite the absence of this property in our manifest file

## Steps to reproduce

1. Login to Outlook.com
2. Open any add-in
3. You will see pinning icon which is coming by default even if SupportsPinning is not explicitly defined in manifest

## Link to live example(s)

<img width="258" alt="Screenshot 2024-11-07 at 12 10 24 PM" src="https://github.com/user-attachments/assets/0dfb284f-078f-40bf-b6bd-f25c28222854">

**Comment by mmanjaree-msft** [comment]
Is your addin a multiselect addin?

**Comment by rohanbharadwaj1994** [comment]
@mmanjaree-msft No, our add-in doesnt support multiselect yet.
We haven't done any changes in the manifest as well regarding pinning or multiselect.
This is happening for all add-ins it seems including ours

**Comment by mmanjaree-msft** [comment]
@rohanbharadwaj1994 Is this app a MetaOS app or na XML addin?

**Comment by rohanbharadwaj1994** [comment]
@mmanjaree-msft This is happening for both MetaOS (unified) and XML add-in as we have both flavours available.

**Comment by JuaneloJuanelo** [comment]
@mmanjaree-msft  i cannot repro this in windows. @mmanjaree-msft  it seems that this is in Mac OS and Chrome, did you tried that configuration?

**Comment by exextoc** [comment]
@JuaneloJuanelo  There is a repro with this configuration on OWA in some sessions, but not all.

**Comment by anjalitp** [comment]
@JuaneloJuanelo  There is a repro with this configuration in some sessions, but not all.

**Comment by anjalitp** [comment]
@JuaneloJuanelo @rohanbharadwaj1994  This issue has already been fixed and the fix is being rolled out. We will update this thread once fix is 100% in Production.

**Comment by anjalitp** [comment]
This issue has been fixed, and fix is available in Production.
