### ISSUE TITLE
Lack of information in public article for creating Outlook profiles pogramatically

### ISSUE THREAD

**Issue by MgarcV** [OfficeDev/office-js#5056]
I was reviewing this article with a customer: https://learn.microsoft.com/en-us/office/client-developer/outlook/mapi/how-to-programmatically-create-a-profile-in-outlook

This customer was using this process to automatically create Outlook profiles in Outlook 2013 with mailboxes stored in Exchange 2013 (and also in the past stored in Exchange 2010).

Now they are removing old Office versions and installing M365 Apps, but the mailbox is still in Exchange 2013. Apparently, the article mentions how to configure the profile in different scenarios but is mixing Client and Server, and there is no any specific scenario that matches with customer’s scenario (Creating profile with Outlook M365 Apps and mailbox stored in Exchange 2013) 

Do you know if this is supported and if we have documentation about it?

Thanks!

**Comment by mmanjaree-msft** [comment]
Thsi is for outlook extensibility specific issues. This does not look like an extensibility related issue. Please open a new issue

**Comment by MgarcV** [comment]
@mmanjaree-msft Could you guide me for opening the issue in the correct place?
