### ISSUE TITLE
Add-in manifests fail to validate when they contain AppDomains tag

### ISSUE THREAD

**Issue by nivgoldsteiniron** [OfficeDev/office-js#5057]
# Provide required information needed to triage your issue

Manifest XML fails validation after adding AppDomains.

This is a continuation of https://github.com/OfficeDev/office-js/issues/4858

I have added AppDomains as @neprasad-microsoft recommended, and it fixed the issue with the popups (in https://github.com/OfficeDev/office-js/issues/4858)

However, adding AppDomains caused the add-in verification to fail.

I did some trial and error and found that removing the tags `IconUrl` and `HighResolutionIconUrl` made it work, and I was able to install the add-in via the sideload menu https://aka.ms/olksideload

Since this workaround worked, that's why I closed the previous issue (This is a continuation of https://github.com/OfficeDev/office-js/issues/4858
)

However, this workaround failed validation when I tried uploading via Admin portal:
https://admin.microsoft.com/Adminportal/Home#/Settings/IntegratedApps -> Upload Custom Apps -> App Type: Office Add-in -> Upload manifest file (.xml) from device.

[addin.xml](https://github.com/user-attachments/files/17661872/addin.xml.txt)
[addin_without_icons.xml](https://github.com/user-attachments/files/17661875/addin_without_icons.xml.txt)
[addin_without_appdomains.xml](https://github.com/user-attachments/files/17661881/addin_without_appdomains.xml.txt)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Web
* Operating System: Windows 11
* Browser (if using Office on the web): Edge
 
## Expected behavior

I expect addin.xml to not fail validation when uploading via Admin portal

## Current behavior

When uploading via Admin portal, addin.xml and addin_without_icons.xml fails to validate but addin_without_appdomains.xml validates successfully.
When uploading via sideload, addin.xml fails to validate but addin_without_icons.xml and addin_without_appdomains.xml validates successfully.

## Steps to reproduce

Go to https://admin.microsoft.com/Adminportal/Home#/Settings/IntegratedApps as an admin account
Then click: Upload Custom Apps -> App Type: Office Add-in -> Upload manifest file (.xml) from device.

To try out the sideload:
open sideload https://aka.ms/olksideload
On the left sidebar My add-ins->Custom addins->Add a custom add-in->Add from File...

**Comment by anjalitp** [comment]
It seems the elements are not following the expected order which is causing Add-in manifest validation to fail. 
Please update the manifest to have the AppDomain element after the icon urls. Attaching the updated manifest here which seems to be working.
[addin.xml.txt](https://github.com/user-attachments/files/17702842/addin.xml.txt)

To learn more about the ordering of elements please refer this doc https://learn.microsoft.com/en-us/office/dev/add-ins/develop/manifest-element-ordering

**Comment by nivgoldsteiniron** [comment]
It works, Thanks so much @anjalitp !
