### ISSUE TITLE
Inserting HTML into Content Control on Web does not work properly anymore

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#5058]
# Provide required information needed to triage your issue
Inserting an HTML into a Content Control in Word Online was working before. Since recently it is not working properly anymore. In other Word Hosts it is still working.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

Inserting HTML into a Word Content Control should work again.

## Current behavior
Inserting HTML into a Word Content Control depends on how the html is structured. I could not find a logic behind. If the HTML has a body element with a line break it does not work. Sometimes it inserts the first part and not the last. 

# Provide additional details

In the following example I am inserting HTML in different versions which should result in the same result. But they all behave different sometimes not inserting the HTML.

```
$("#run").on("click", () => tryCatch(run));

async function run() {
  await Word.run(async (context) => {
    const p1 = context.document.body.insertParagraph('First Paragraph', "End");
    const p2 = context.document.body.insertParagraph('Second Paragraph', "End");
    const p3 = context.document.body.insertParagraph('Third Paragraph', "End");
    const p4 = context.document.body.insertParagraph('Fourth Paragraph', "End");
    const p5 = context.document.body.insertParagraph('Fourth Paragraph', "End");
    await context.sync()  

    const firstContentControl = p1.insertContentControl();
    firstContentControl.insertHtml(htmlWithoutLineBreaks, 'Replace');   

    const secondContentControl = p2.insertContentControl();
    secondContentControl.insertHtml(htmlWithoutLineBreakAfterBodyElement, 'Replace'); 

    const thirdContentControl = p3.insertContentControl();
    thirdContentControl.insertHtml(htmlWithLineBreakAfterBodyElement, 'Replace'); 

    const fourthContentControl = p4.insertContentControl();
    fourthContentControl.insertHtml(htmlWithoutBodyElement, 'Replace'); 

    const fifthContentControl = p5.insertContentControl();
    fifthContentControl.insertHtml(htmlWithHtmllement, 'Replace'); 
    await context.sync()         
  });
}

// Default helper for invoking an action and handling errors.
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}

const htmlWithoutLineBreaks =`<body><h1>1. My Header</h1><p>My paragraph.</p><br/></body>`;

const htmlWithoutLineBreakAfterBodyElement = `<body><h1>2. My Header</h1>
<p>My paragraph.</p>
<br/><body>`;

const htmlWithLineBreakAfterBodyElement = `<body>
<h1>3. My Header</h1>
<p>My paragraph.</p>
<br/><body>`;

const htmlWithoutBodyElement = `<h1>4. My Header</h1>
<p>My paragraph.</p>
<br/>`;

const htmlWithHtmllement = `<html><body><h1>5. My Header</h1><p>My paragraph.</p><br/></body></html>`;
```
<img width="407" alt="image" src="https://github.com/user-attachments/assets/f8ce15a0-efc3-485f-956b-75d58505e3c8">

## Context
We are proving a first app which uploads a part of a Word Document as HTML by using the range.getHtml() API. Inserting this HTML into an other Content Control does not work anymore in Word Online. This breaks our second app which is used to insert HTML into Word.

**Comment by RuizhiSunMS** [comment]
Thank you for reporting this issue, I can repro it. It has been put on our backlog #9516931, the team will investigate and we will reply to you as soon as there is any progress. Thank you for your patience.

**Comment by noahw3** [comment]
I'm also seeing this behavior. As a result, our entire add-in is currently broken in Word online, while it works fine inside the local application.

Here's a snippet that does not work:

```
const expr = "{{ <span style="background-color: yellow">text</span> }}";
await Word.run(async (context) => {
      // insert a paragraph at the end of the document.
      console.debug("inserting html into document....");
      let range = context.document.getSelection();
      range.load("font");

      await context.sync();
      let fontName = range.font.name;
      let fontSize = range.font.size;

      range.insertHtml(expr, Word.InsertLocation.replace);

      range.font.name = fontName;
      range.font.size = fontSize;

      console.debug("syncing....");
      await context.sync();

      console.debug("done.");
    })
```

**Comment by thelsevier** [comment]
We have had this issue as well, but it seems to be fixed now, try again 👍

**Comment by barisbikmaz** [comment]
Thanks for the info @thelsevier. Yeah seems to be working again. I am closing the issue.
