### ISSUE TITLE
"getAttachmentContentAsync" Suppresses Errors and Fails to Invoke Callback in OWA

### ISSUE THREAD

**Issue by ykonda** [OfficeDev/office-js#5060]
When calling the function "getAttachmentContentAsync" function, an error in the ows javascript seems to occur and the office.js-function never returns. 
(The callback is never called?)

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: macOS Sonoma 14.5
* Browser (if using Office on the web): Google Chrome Version 130.0.6723.92 (Official Build) (arm64)
 
## Expected behavior
The callback is called with the Failure-State of the asyncResult.

## Current behavior
The code of the callback function is never executed.

## Steps to reproduce

1. Open Outlook
2. Open a add-in that calls "getAttachmentContentAsync" or implement one

## Link to live example(s)
```
export const demoAttachmentContentFailure = (attachmentId: string): void => {
  console.log("call demo");
  const email = Office.context.mailbox.item;
  if (!email) {
    throw new MissingMailboxItemError();
  }
  email.getAttachmentContentAsync(attachmentId, (asyncResult) => {
    console.log("asyncResult", asyncResult);
    if (asyncResult.status === Office.AsyncResultStatus.Failed) {
      console.error("failed status", asyncResult);
      throw asyncResult.error;
    }
    console.log("Attachment content received.");
    return asyncResult.value;
  });
};
```

# Provide additional details
I know this is also an issue with the Outlook Web client.
It suddenly started throwing this Error:
```
owa.2259.m.c69caa30.js:1  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__type')
    at r (owa.2259.m.c69caa30.js:1:21770)
    at tm (owa.32413.m.e40e7766.js:1:23618)
    at n5 (owa.32413.m.e40e7766.js:1:70528)
    at owa.32413.m.e40e7766.js:1:76006
    at e.invoke (owa.88760.m.abe8f8d7.js:1:50370)
    at u (owa.88760.m.abe8f8d7.js:1:34390)
    at v (owa.88760.m.abe8f8d7.js:1:37956)
```

However, the callback should be called anyway.

## Context
We have implemented a outlook add-in that reads mails and attachment from Outlook.

**Comment by mmanjaree-msft** [comment]
@ykonda  Please provide details about what kind of attachment is being added here?

**Comment by ykonda** [comment]
Hello @mmanjaree-msft, thanks for the response.
The issue with the callback not being called seems to be fixed now.
I immediately get an "InvalidAttachmentId"-Error now.
Even though, this is still a problem that appeared all of a sudden, we can close this issue and I can open a new one.

**Comment by anjalitp** [comment]
@ykonda  Closing the issue as this has been fixed.
