### ISSUE TITLE
rangeAreas.calculate() does not automatically calculate all dependent cells

### ISSUE THREAD

**Issue by miguellandrito** [OfficeDev/office-js#5063]
# Provide required information needed to triage your issue
`rangeAreas.calculate` function is not calculating all the dependent cells, it is only calculating cells that directly reference the rangeArea but not the cells that are dependent to the referenced cell. Calculation mode is also set to Automatic.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Excel Web, Mac, and PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Excel Web - latest
* Operating System: Windows/MacOS
* Browser (if using Office on the web): Chrome
 
## Expected behavior

`rangeAreas.calculate` should calculate the rangeArea and all the dependent cells, since it should be mimicking the behavior of a newly inserted formula

## Current behavior

`rangeAreas.calculate` would only calculate the rangeArea and cells that directly reference the rangeArea compared to when re-inserting the formula in formula bar
![rangeArea calculate vs inserting](https://github.com/user-attachments/assets/c8210901-6e5f-494a-aa7f-bd28924cc2a1)

## Steps to reproduce

1. In Script Lab, use two scripts:
- for registering random number generator custom function: 
```
/**
 * Returns a random number.
 * @customfunction
 * @returns a random number.
 */
function randomg() {
  return Math.floor(Math.random() * (100 - 1 + 1)) + 1;
}
```
- for calculating rangeArea:
```
$("#run").on("click", () => tryCatch(run));

async function run() {
  await Excel.run(async (context) => {
    const selectedTargetRanges = context.workbook.getSelectedRanges();

    selectedTargetRanges.calculate();
    await context.sync();
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}
```
2. in `A1` cell, use the scriptlab formula
3. in `B1` cell, reference A1 and do an equation (ex. =A1+1)
4. in `C1` cell, reference B1 and do (ex. =B1*2)
5. Select A1 as active cell, and click on the run button
6. only A1 and B1 would refresh but not C1

## Link to live example(s)

1. ______
7. ______
8. ______

# Provide additional details

1. ______
4. ______
5. ______

## Context

In our COM/PC addin, users can calculate the cell and the dependent cells would automatically refresh, and this causes a disparity in the Office.js' add-ins behavior. They are expecting that when a rangeArea is calculated all the dependent cells would also be calculated.

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuizhiSunMS** [comment]
Thank you for reporting this issue, I can repro it. It has been put on our backlog #9521625, the team will investigate and we will reply to you as soon as there is any progress. Thank you for your patience.

**Comment by qinliuMSFT** [comment]
Hi @miguellandrito , thanks for reporting this issue. The issue should only repro on Excel online and work as expected on Excel win32 and Excel Mac.

This is a known issue due to a known difference in how the dependency code works between Excel Online and Excel Desktop. There is a plan for Calc team to overhaul the dependency system but that overhaul is not yet scheduled and will take months of work. So in the short term, we cannot provide any fix at the API level.

We have two workaround that can make online behavior meet your expectations:
1. Do a larger re-calc, such as [sheet.calculate(markAllDirly)](https://learn.microsoft.com/en-us/javascript/api/excel/excel.worksheet?view=excel-js-preview#excel-excel-worksheet-calculate-member(1)). It can guarantee the calculate of dependencies on the same sheet.
2. Get the dependencies of a range first by calling API [range.getDependents()](https://learn.microsoft.com/en-us/javascript/api/excel/excel.worksheet?view=excel-js-preview#excel-excel-worksheet-calculate-member(1)), and then loop through all dependents of the active cell and trigger calculate().

Please let me know if you have any other questions.

**Comment by Jacob-Co** [comment]
Hello,

@miguellandrito, is currently OOO and will be back by tomorrow. We are still currently testing the workarounds to check if they fit our use-case. We will update here once we have the findings. Thank you!

**Comment by miguellandrito** [comment]
Hey @qinliuMSFT,

We've tested the workarounds and here are the results: 
- the first one isn't feasible for our use-case since there might be other custom formulas that are not from our add-in that can be affected by using sheet.calculate(markAllDirty)
  - this would calculate all cells even third-party custom formulas
- the second one is quite slow upon testing, since `range.getDependents` returns a WorkBookRangeAreas class and it does not have a calculate method
  - upon getting the WorkBookRangeAreas object, we use `workbookRangeAreas.areas` to get the RangeAreasCollection
  - then we would get the RangeAreas array using `RangeAreasCollection.items`
  - this results in alot of API calls that is making it slow

Do you have any other suggestions in mind that could be much faster than the second workaround?

**Comment by qinliuMSFT** [comment]
Hi @miguellandrito , have you considered changing the function to `volatile` type? Then the function and the cells depend on this function will be recalculated every time the workbook is recalculated. 

For the second workaround, to resolve the performance issue, you can minimize the number of API calls by batching them together. Instead of making multiple individual API calls, you can use the `context.sync()` method to batch the operations. 
- Get the dependents of the range.
- Loop through the dependents and collect them. Do not use `await context.sync()` in a loop.
- Trigger the calculation in a single batch operation.

**Comment by miguellandrito** [comment]
Hey @qinliuMSFT, I've tried implementing what you mentioned for the second workaround however I am quite stuck in this scenario:

```
const workBookRangeAreasArray: Excel.WorkbookRangeAreas[] = [];
   for (const range of flattenedExcelRangeArray) {
      try {
        const workBookRangeAreas = range.getDependents();
        workBookRangeAreasArray.push(workBookRangeAreas);
      } catch (e) {
        console.log(e);
      }
    }

await context.sync();
console.log(workBookRangeAreasArray);
```

`range.getDependents()` would not throw an error if there are no dependents. Instead when I check the `workBookRangeAreasArray`, `range.getDependents()` returned a WorkBookRangeAreas class despite there being no dependents.

**Comment by qinliuMSFT** [comment]
Hi @miguellandrito , please try my code snippet in Script Lab. the range.getDependents should throw ItemNotFound error if there is no dependents. 
- `Run1` button is your original function calling `calculate()` on selected range.
- `Run2` button is the second workaround, call `getDependents()`, then call `calculate()` on selected cell and all dependents ranges.

```
name: Blank snippet
description: Create a new snippet from a blank template.
host: EXCEL
api_set: {}
script:
  content: |
    $("#run1").on("click", () => tryCatch(run1));
    $("#run2").on("click", () => tryCatch(run2));

    async function run1() {
      await Excel.run(async (context) => {
        const selectedTargetRanges = context.workbook.getSelectedRanges();
        selectedTargetRanges.load("areas");
        await context.sync();
        selectedTargetRanges.calculate();
        await context.sync();
      });
    }

    async function run2() {
      await Excel.run(async (context) => {
        const selectedCell = context.workbook.getActiveCell();
        await context.sync();

        const dependents = selectedCell.getDependents();
        dependents.load("areas");
        await context.sync();
        selectedCell.calculate();
        for (let i = 0; i < dependents.areas.items.length; i++) {
          const dependentRange = dependents.areas.items[i];
          console.log(dependentRange);
          dependentRange.calculate();
        }

        await context.sync();
      });
    }

    /** Default helper for invoking an action and handling errors. */
    async function tryCatch(callback) {
      try {
        await callback();
      } catch (error) {
        // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
        console.error(error);
      }
    }
  language: typescript
template:
  content: |-
    <button id="run1" class="ms-Button">
        <span class="ms-Button-label">Run1</span>
    </button>

    <button id="run2" class="ms-Button">
        <span class="ms-Button-label">Run2</span>
    </button>
  language: html
style:
  content: |-
    section.samples {
        margin-top: 20px;
    }

    section.samples .ms-Button, section.setup .ms-Button {
        display: block;
        margin-bottom: 5px;
        margin-left: 20px;
        min-width: 80px;
    }
  language: css
libraries: |
  https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
  @types/office-js

  office-ui-fabric-core@11.1.0/dist/css/fabric.min.css
  office-ui-fabric-js@1.5.0/dist/css/fabric.components.min.css

  core-js@2.4.1/client/core.min.js
  @types/core-js

  jquery@3.1.1
  @types/jquery@3.3.1
```

**Comment by miguellandrito** [comment]
Hi @qinliuMSFT, I am trying to find a way to optimize the performance since there are multiple ranges that I need to get dependents for. The `range.getDependents` is inside a for loop which is causing it to have slow performance, and I tried placing the context.sync outside the for loop but it does not behave as expected.

**Comment by miguellandrito** [comment]
Hey @qinliuMSFT, I found another workaround but would just like to confirm if this solution would have any repercussions. Instead of calculating, I am programatically re-inserting the formula.

```
$("#run").on("click", () => tryCatch(run));

async function run() {
  await Excel.run(async (context) => {
    const selectedTargetRange = context.workbook.getSelectedRange();

    selectedTargetRange.load("formulas");
    await context.sync();

    const rangeAreas = context.workbook.getSelectedRanges();
    rangeAreas.areas.load("items");
    await context.sync();

    rangeAreas.areas.items.forEach(function (range) {
      range.formulas = [[selectedTargetRange.formulas[0][0]]];
    });
    await context.sync();
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}
```

Finally, just a question for `range.getDependents()`, is there a property similar to the `isNullObject` property from RangeAreas, that can be included in the object being returned by `getDependents()`?

**Comment by qinliuMSFT** [comment]
Hi @miguellandrito , the workaround looks good to me.

For your questions about `range.getDependents()`, unfortunately there is no property similar to the `isNullObject`, though, it will throw `ItemNotFound` error so you could catch this error and add additional check there. More details please see: https://learn.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview#excel-excel-range-getdependents-member(1)

**Comment by SiruiSun-MSFT** [comment]
Hi @miguellandrito, I noticed my colleague have provided another workaround for you [above](https://github.com/OfficeDev/office-js/issues/5063#issuecomment-2534126619) . Have you ever tried to change the function type to **volatile** type? From our test, the volatile type could also help mitigate this problem. Looking forward for your reply here! Thanks!
