### ISSUE TITLE
autofitColumns combined with special number format extends column width occasionally

### ISSUE THREAD

**Issue by wolfgang-sap** [OfficeDev/office-js#5066]
# autofitColumns combined with special number format extends column width occasionally

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Desktop PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: tested with Office 365 Version 2409 and 2402
* Operating System: Windows 11
* Browser (if using Office on the web): ______
 
## Expected behavior
autoFitColumns should always work correctly

## Current behavior
When I call autofitColumns on a range with special number format, sometimes the column will get very wide though it's not necessary. The number format contains special characters and blanks (e.g. "▸ @  "). See the attached workbook and scriptlab where it happens around 50% of the times on my machine.

## Steps to reproduce

1. open the attached workbook
2. run the attached scriptlab script (which does nothing more than call sheet.getUsedRange().format.autofitColumns())
3. maybe try several times

## Context

Excel online seems not to be affected but our customers use mostly Excel Desktop for Performance reasons.
[AutofitIssue.xlsx](https://github.com/user-attachments/files/17699766/AutofitIssue.xlsx)
[autofitIssueScriptlab.txt](https://github.com/user-attachments/files/17699785/autofitIssueScriptlab.txt)

**Comment by RuizhiSunMS** [comment]
Hi @wolfgang-sap, thx for your submit. 
I did some quick tests on both web and win32 client with your attachments following your steps, but everything looks good here. May I confirm that your steps can always trigger the problem? If not, would you please have another more stably triggering it?
```
$("#run").on("click", () => tryCatch(run));
$("#change").on("click", () => tryCatch(change));

async function run() {
  await Excel.run(async (context) => {
    console.log("run");
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    const range = sheet.getUsedRange().format.autofitColumns();
    await context.sync();
  });
}

async function change() {
  await Excel.run(async (context) => {
    console.log("change");
    const sheet = context.workbook.worksheets.getItem("Sheet1");
    const range = sheet.getRange("B1:C800");
    range.format.columnWidth = 1000;
    await context.sync();
    range.load("format");
    await context.sync();
    console.log(range.format);
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}
```

**Comment by wolfgang-sap** [comment]
I just tried again and in 8 out of 10 runs I had wrong sized column widths.
If I duplicate the content of A1:B1544 downwards to get longer columns it fails more often and I get the same failure when I use Ribbon -> Home -> Cells -> Format -> AutoFit Column Width.

**Comment by RuizhiSunMS** [comment]
> A1:B1544

I tried more than 20 times using `getRange("A1:B1544")`, none of them failed. My version is 2411. Have you ever tried update your Office?

**Comment by wolfgang-sap** [comment]
Thanks. I installed Current Preview Channel (2411) and I cannot reproduce the issue anymore. 2410 is still affected.
Is it possible to downport the fix as many of our customers use other Office Channels (Monthly Enterprise / SemiAnnual)?

**Comment by RuizhiSunMS** [comment]
> Thanks. I installed Current Preview Channel (2411) and I cannot reproduce the issue anymore. 2410 is still affected. Is it possible to downport the fix as many of our customers use other Office Channels (Monthly Enterprise / SemiAnnual)?

This question needs to get Excel folks involved. I'll reach out to them and let them discuss. Put #9524294 as the item id here. Will reply here if any update. 
Btw, can I regard your issue is resolved?

**Comment by wolfgang-sap** [comment]
Yes thanks. I guess it is resolved as far as it concerns you. Our customers then have to wait for an update or downport...
