### ISSUE TITLE
getAttachmentContentAsync fails

### ISSUE THREAD

**Issue by ykonda** [OfficeDev/office-js#5068]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: maxOS Sonoma 14.5
* Browser (if using Office on the web): Version 130.0.6723.117 (Official Build) (arm64)
 
## Expected behavior
`Office.context.mailbox.item.email.getAttachmentContentAsync` returns OfficeAttachmentContent.

## Current behavior
Even though a correct attachmentId was provided, the function returns a `InvalidAttachmentId`-Error. 

## Steps to reproduce
Open an add-in in read-modus in the context of a email with attachments.

```
const email = Office.context.mailbox.item;
if (!email) {
  throw new Error();
}
const id = email.attachments[0].id;
console.log("id", id);
email.getAttachmentContentAsync(id, (asyncResult) => {
  console.log(asyncResult);
});
```
![image](https://github.com/user-attachments/assets/b0077f65-6deb-4e2a-9f3b-a750a695f138)

Attachment:
![image](https://github.com/user-attachments/assets/f8030558-72bc-40a1-82ae-72b147f1f88b)

## Link to live example(s)

# Provide additional details

## Context
We have implemented a outlook add-in that reads mails and attachment from Outlook.

## Useful logs

- [x] Console errors
```
{
    "name": "InvalidAttachmentId",
    "message": "Die Anlage-ID war ungültig.",
    "code": 9003
}
```
- [] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by anjalitp** [comment]
@ykonda  Is this same as issue https://github.com/OfficeDev/office-js/issues/5060 ?

**Comment by anjalitp** [comment]
@ykonda  Thanks for reporting this issue regarding getAttachmentContentAsyncAPI. It has been added to our backlog. Unfortunately, we do not have a timeline to share at this point.

Internal tracking Id: 5076507

**Comment by dipika-mandhare-ambit** [comment]
I have created outlook add-in to get email attachment content but getAttachmentContentAsync functions returns result value as undefined previously it was working suddenly stopped to work.
![Capture](https://github.com/user-attachments/assets/e5fc688f-fbac-484f-b610-beb164da607e)

**Comment by btietze** [comment]
Is there any workaround for this problem?
We have problems with several customers and our internal environment due to this bug.
How can the priority be increased here?

**Comment by dipika-mandhare-ambit** [comment]
@btietze I also searching for workaround on high priority

**Comment by jacobtread** [comment]
Also started seeing this same "InvalidAttachmentId" issue about 1-2 weeks back with a user, on from what I can tell looks like a valid attachment ID same as above. Cannot replicate this issue on my personal account but a client is seeing this on their account consistently while trying to read attachments.

**Comment by dipika-mandhare-ambit** [comment]
> Also started seeing this same "InvalidAttachmentId" issue about 1-2 weeks back with a user, on from what I can tell looks like a valid attachment ID same as above. Cannot replicate this issue on my personal account but a client is seeing this on their account consistently while trying to read attachments.

For me it's working on desktop outlook app but facing issue for web also attachment id is valid still showing invalid attachment id issue

**Comment by ykonda** [comment]
> Also started seeing this same "InvalidAttachmentId" issue about 1-2 weeks back with a user, on from what I can tell looks like a valid attachment ID same as above. Cannot replicate this issue on my personal account but a client is seeing this on their account consistently while trying to read attachments.

A wild guess but does one of you have an external microsoft account of another tenant?

**Comment by jacobtread** [comment]
> > Also started seeing this same "InvalidAttachmentId" issue about 1-2 weeks back with a user, on from what I can tell looks like a valid attachment ID same as above. Cannot replicate this issue on my personal account but a client is seeing this on their account consistently while trying to read attachments.
> 
> A wild guess but does one of you have an external microsoft account of another tenant?

Not sure, how would I go about checking that for them?

**Comment by tobiasviehweger** [comment]
This def. stopped working. It was working a few weeks back for us but in our B2B account it's also broken now, with all attachments in OWA / new Outlook. @anjalitp @exextoc this is not just a bug but a production incident - we have been migrating away from using EWS callback tokens due to the pending deprecation but now one of the most important fallback things is broken. This needs do be fixed ASAP before all EWS stuff will stop working in Outlook add-ins.

To add to this: It does not even seem to do any call to Exchange to come to this conclusion (via Network tab), it seems to do a local validation and think this is not a valid id - seems like a broken client side check??
![image](https://github.com/user-attachments/assets/3ed85735-7659-47bf-9ee0-34a3062c886c)

**Comment by tobiasviehweger** [comment]
So after investigating this a bit longer, it seems that OWA internally uses immutableRestEntryIds while providing the add-in with a restEntryId and fails to find the attachment if provided with the id from attachment.id.

attchment.id => `AAMkADQ2<snip>Ni05MTRlLTE0ZjkzYjhiZmIxYgBGAAAAAAAiCmOBDIX4TojSJs8PRerdBwCiXa8K4T4FToTXRfNegy16AAAAAAENAACiXa8K4T4FToTXRfNegy16AAqRztfWAAABEgAQAK59sg/XdoNNkSsjstT6RIo=`
internal Outlook id => `AAkALgAAA<snip>Wg0Aol2vCuE+BU6E10XzXoMtegAKkdBsHgAAARIAEACufbIP13aDTZErI7LU+kSK`

**Comment by akarl-bricks** [comment]
I'm fairly certain that this is causing attachments to fail within the Salesforce Outlook addon. I see this same behavior happening for my users and I can easily replicate the behavior. That behavior began with similar timing to this thread. Given the relatively high user count from the Salesforce addon, I'd hope to see some prioritization occur.

**Comment by arpitsangwanmsft** [comment]
Hey Everyone!
@akarl-equips / @tobiasviehweger / @ykonda / @dipikamandhare 
We are actively investigating this on priority, Will keep the thread updated.
Thanks for all the inputs.

**Comment by alicegalasso** [comment]
Hi! Do we have some updates on the release date of the issue?
thanks

**Comment by arpitsangwanmsft** [comment]
Hey @alicegalasso!
The Fix has reached 100% world-wide and this should be resolved now. Please re-validate the scenario and let us know.
Thanks!

cc: @tobiasviehweger / @ykonda / @dipikamandhare / @akarl-equips / @jacobtread.

**Comment by akarl-bricks** [comment]
> Hey @alicegalasso! The Fix has reached 100% world-wide and this should be resolved now. Please re-validate the scenario and let us know. Thanks!
> 
> cc: @tobiasviehweger / @ykonda / @dipikamandhare / @akarl-equips / @jacobtread.

Working for me, thanks!

**Comment by dipika-mandhare-ambit** [comment]
> Hey @alicegalasso! The Fix has reached 100% world-wide and this should be resolved now. Please re-validate the scenario and let us know. Thanks!
> 
> cc: @tobiasviehweger / @ykonda / @dipikamandhare / @akarl-equips / @jacobtread.

it's working now. Thanks!!

**Comment by jacobtread** [comment]
Confirmed its working, awesome thank you

**Comment by arpitsangwanmsft** [comment]
Closing this. Thanks for the inputs!
