### ISSUE TITLE
Sideloaded add-ins on mac have to be re-added after each restart

### ISSUE THREAD

**Issue by misaunde** [OfficeDev/office-js#507]
Going through this tutorial for sideloading on mac:
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac 

For  a manifest that already works as expected on pc (Windows 10), I notice that every time I close and re-open Excel, my add-ins disappear. I have to go to the Insert ribbon, click on the my add-ins drop down menu, and re-select my developer add-in. Is this expected behavior?

On pc, if I add my custom ribbon manifest, it stays there for good, across restarts. Can this be achieved on a mac?

## Expected Behavior

I expect the add-ins to remain after restarting Excel similar to how they behave on Windows.

## Current Behavior

Every time I close and re-open Excel, my add-ins disappear.

## Steps to Reproduce, or Live Example

Restart Excel

## Context

On windows, I only have to sideload my add-in once, then it stays. I'd like not to have to add it every time I restart Excel.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ____Mac__
* Host [Excel, Word, PowerPoint, etc.]: _____Excel_
* Office version number: ___Excel 16.24 Office 365___
* Operating System: __Mac OS 10.14.4____
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by grangeryy** [comment]
This is expected behavior for Mac. You may find the important notice in [https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-an-office-add-in-on-ipad-and-mac]
![image](https://user-images.githubusercontent.com/50093161/59748386-934ff880-92ad-11e9-8b42-13ccb3529a65.png)

**Comment by ElivonRadecki** [comment]
Hi, I have a client who sideloaded an add to his mac (for word, ppt and excel) and is experiencing the same issue described by misaunde above. While I get it that this is expected behavior for the sideloaded add in to only show within the drop-down menu in the my add ins section, I was wondering if there is a way to instead have the add in to persist in the ribbon. Grateful for any insights.
