### ISSUE TITLE
Outlook: Register the online-meeting template for Rumi.ai

### ISSUE THREAD

**Issue by mjgaylord** [OfficeDev/office-js#5071]
Can you please register the online meeting template for our meeting service Rumi.ai

Asset ID: eeb734c9-c025-4f51-980d-02233fa8cdd0

```html
<br /><br />
You're invited to join a call on Rumi.ai
<br/>
To join the meeting: <a href="https://rumi.ai/sessions/107963471433307334" target="_blank">Click here</a>
<br />
Learn more at <a href="https://rumi.ai" target="_blank">Rumi.ai</a>
<br /><br />
```

Thank you.

**Comment by samantharamon** [comment]
Hi @mjgaylord. Thanks for your request. We'll notify the appropriate team to assist you with this.

**Comment by rajjha-msft** [comment]
Hey @mjgaylord 

Can you please share the asset ID as per the doc : https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/online-meeting?tabs=jsonmanifest#register-your-online-meeting-template

![image](https://github.com/user-attachments/assets/e3e024c3-a022-4eb0-847e-02be517b37d8)

Only online-meeting add-ins published to AppSource can be registered. Line-of-business add-ins aren't supported.

**Comment by mjgaylord** [comment]
Apologies @rajjha-msft 

Here is the asset ID: eeb734c9-c025-4f51-980d-02233fa8cdd0

**Comment by rajjha-msft** [comment]
Hey @mjgaylord 

The ID you have mentioned looks more to be add-in ID. 
You need to publish your app to AppSource to get an asset ID : https://learn.microsoft.com/en-us/power-platform/developer/appsource/publish-app

Is your app already published ? (Can you see it in add-in store ?)
