### ISSUE TITLE
Saving powerpoint document using PowerpointApi

### ISSUE THREAD

**Issue by rahul-chanana** [OfficeDev/office-js#5073]
Hello,

We are developing an Office Add-In (Taskpane) using the Angular framework and need to save the document on behalf of the user. For Word documents, we can use the `save` method from the Word API, and for Excel documents, we can use the `save` method from the Excel API. However, we couldn't find an equivalent method for PowerPoint documents.

Which method can we use to save a PowerPoint document on behalf of the user?

Thank you in advance for your help!

## Expected Behavior
There should be a method available to save the PowerPoint document on behalf of the user.

## Current Behavior
There doesn't appear to be an available method in the PowerPoint API to perform this action.

## Context
In certain cases we need to save the PowerPoint document on behalf of the user within our Add-In.

## Your Environment
* Platform: Desktop, Office Online
* Host: Powerpoint
* Office version number: 2402
* Operating System: Windows 11
* Browser: Chrome, Edge

**Comment by EsterBergen** [comment]
HI @rahul-chanana - You're correct that this functionality is not available. This would be a new feature for PowerPoint. Please make a feature request here [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions).  Feature requests on are considered when we go through our planning process. Thanks for highlighting this!
