### ISSUE TITLE
Checking for unsaved changes in powerpoint using Office JavaScript API

### ISSUE THREAD

**Issue by rahul-chanana** [OfficeDev/office-js#5075]
Hello,

We are developing an Office Add-In (Taskpane) using the Angular framework, and we need a way to determine whether the user has unsaved changes in the document. We’ve successfully implemented this check in Word and Excel using the following approaches:

For Word:

```
override isDocumentDirty(): Promise<boolean> {
  return Word.run(async (context) => {
    const document = context.document;
    context.load(document, 'saved');
    await context.sync();
    
    // If the document is not saved, it is considered "dirty"
    return !document.saved;
  });
}
```

For Excel:

```
override isDocumentDirty(): Promise<boolean> {
  return Excel.run(async (context) => {
    const workbook = context.workbook;
    context.load(workbook, 'isDirty');
    await context.sync();
    
    return workbook.isDirty;
  });
}
```

## Expected Behavior
We would like to detect unsaved changes in PowerPoint, similar to how we can in Word and Excel, to determine when a document is "dirty."

## Current Behavior
There doesn't seem to be a method available in the PowerPoint API to detect unsaved changes.

## Context
This functionality is needed to help detect unsaved changes within our add-in.

## Your Environment
* Platform: Desktop, Office Online
* Host: Powerpoint
* Office version number: 2402
* Operating System: Windows 11
* Browser: Chrome, Edge

**Comment by RuizhiSunMS** [comment]
hi @rahul-chanana, thx for the submit. I'm reaching out to PPT experts and will reply here if any update.

**Comment by EsterBergen** [comment]
Hi @rahul-chanana - I just asked Microsoft Copilot and here is the guidance.

Yes, you can check for unsaved changes in PowerPoint using the Office JavaScript API. Specifically, you can use the `Office.context.document` object to interact with the PowerPoint document. Here's a basic example of how you might check for unsaved changes:

```javascript
Office.onReady((info) => {
  if (info.host === Office.HostType.PowerPoint) {
    // Check if the document has unsaved changes
    const hasUnsavedChanges = Office.context.document.saved === Office.DocumentSavedStatus.notSaved;
    if (hasUnsavedChanges) {
      console.log("There are unsaved changes in the document.");
    } else {
      console.log("All changes are saved.");
    }
  }
});
```

In this example, `Office.context.document.saved` returns the saved status of the document. If it equals `Office.DocumentSavedStatus.notSaved`, it means there are unsaved changes.


Please try this. Thanks!

**Comment by rahul-chanana** [comment]
> Hi @rahul-chanana - I just asked Microsoft Copilot and here is the guidance.
> 
> Yes, you can check for unsaved changes in PowerPoint using the Office JavaScript API. Specifically, you can use the `Office.context.document` object to interact with the PowerPoint document. Here's a basic example of how you might check for unsaved changes:

Hi @EsterBergen,

Microsoft CoPilot has provided incorrect guidance. The `Office.context.document` object does not include a `saved` property. I recommend reaching out to the development team for further assistance on this matter.

**Comment by EsterBergen** [comment]
Hi @rahul-chanana  - Thank you highlighting this! This would be a new feature. Please make a feature request here [Microsoft 365 Developer Platform Ideas Forum](https://aka.ms/m365dev-suggestions). Please add your request there. Feature requests on are considered when we go through our planning process. Thanks for highlighting this!
