### ISSUE TITLE
Button and text UI in Smart alert is not consistent

### ISSUE THREAD

**Issue by riddhi-p-28** [OfficeDev/office-js#5076]
We are developing an outlook web addin using office js Smart alert template.
We are using Office JS Office.SmartAlertsEventCompletedOptions to display popup to the user. What we have observed is that the button placement on UI  and font size for Smart alert is not consistent. When drafting mail thru group menu in outlook, the button placement changes. As per the [docs here](https://learn.microsoft.com/en-us/javascript/api/outlook/office.smartalertseventcompletedoptions?view=outlook-js-preview), we can handle the button click event and label text shown on this popup. However, i see there is no option to alter the styling/positioning of the text or button. Hence, we do not have control over the UI of the Smart alert.
**NOTE: this issue occurs intermittently**

![UI misplace](https://github.com/user-attachments/assets/c14b5c45-69fd-4ee5-a275-6f16f1b8f6b8)

![bugUIMisplace](https://github.com/user-attachments/assets/a5a8bbdb-7601-4d62-8e43-dd4493270e7f)

<img width="625" alt="button placement" src="https://github.com/user-attachments/assets/dd1f7026-49e4-47dd-a3d4-fa5635b9ca12">

![image](https://github.com/user-attachments/assets/9be70015-5cf8-45f2-9727-ed1bd4cadebf)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

The UI should be consistent across all email smart alerts.

## Current behavior

Verify button present in Smart Alert from Addin popup is mislocated.

## Steps to reproduce

1. Click on group menu in outlook chrome.
2. Hover on any group present in group home page.
3. Click on send email present in that popup and popout the window.
4. Add subject, body and attachments.
5. Click on send.
6. Observe the UI

**Comment by anjalitp** [comment]
@riddhi-p-28  we are not able to repro this where button appears on the left. For us, the button appears to the right.
![image](https://github.com/user-attachments/assets/c86b766e-b16f-42ce-a5b8-e0a7d4c07be4)

Did u make any changes in layout settings? 
The difference in the button color is due to the theme applied in Outlook and this is expected behaviour. It would be helpful if you can share a repro video.
