### ISSUE TITLE
Error in requesting InternetMessageHeaders

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#5079]
# Provide required information needed to triage your issue
One of our customers is creating new profiles and adding new users to their environment. The REST APIs have worked well for their existing users but for the new profiles and users, an error stating 'REST API is in preview' happens. Because of this 'in preview' issue, our addin could not query the internet Message headers.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Any
* Operating System: Windows 10
* Browser (if using Office on the web): Any
 
## Expected behavior

Since REST is enabled for other users, it should be enabled (and not preview) for new users or new profiles as well.

## Current behavior

Instead of getting the message headers successfully, we are getting the following error : 

_Could not find a property named ‘InternetMessageHeaders’ on type ‘Microsoft.OutlookServices.Message’. REST APIs for this mailbox are currently in preview. You can find more information about the preview REST APIs at https://dev.outlook.com/.“_

Or is the above expected because of the deprecation of REST?

## Steps to reproduce

1. ______
2. ______
3. ______

## Link to live example(s)

1. ______
2. ______
3. ______

# Provide additional details

1. ______
2. ______
3. ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by anjalitp** [comment]
@glr0221  This forum is limited to Office js related issues. However, I would suggest you explore InternetHeaders API to check if works for your use case.  Please find the documentation here https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/internet-headers#get-internet-headers-while-reading-a-message
