### ISSUE TITLE
When sharing a file that was created using an Excel js addin it try to install it 

### ISSUE THREAD

**Issue by Nikodem98** [OfficeDev/office-js#5081]
Hello, every time I share a file that was created using an excel custom add-in if a person doesn't have access to that addin it still try to instal it in their machine. is there any way to prevent that? because users get the new Office addin error.

![Zrzut ekranu 2024-11-13 o 08 15 27](https://github.com/user-attachments/assets/c614f9d8-e230-45f0-80cf-328e6db7b74e)

**Comment by RuizhiSunMS** [comment]
Thx for your reporting the issue. I think it's related with addin installation. I will reach out to experts and reply here if any update.
Anyway, would you please share your addin with us?

**Comment by Nikodem98** [comment]
Hello, we use admin center to deploy manifest files to specific groups of people. But when other people without the access open the file this happens

**Comment by Nikodem98** [comment]
Also we use different addins for different env we have. So when users has access to one addin and shares a file with another user that has access to different addin and lines that file it shows for this user two addins one that he has access to and can be used and the other addin with which this shared file was created. Those addin have exactly the same names, custom functions etc. And we want to avoid that.

**Comment by RuizhiSunMS** [comment]
hi @Nikodem98, our experts need some more information about your case. Would you please share necessary ones? 
For example:
1. steps of what you did
2. what's the platform you are using and whose version number
3. (if possible) your addin, file, manifest and others
4. how did you share the file
These would be helpful to the investigationl.
