### ISSUE TITLE
Outlook OWA: getAttachmentContentAsync doesn't return value 

### ISSUE THREAD

**Issue by m-escher** [OfficeDev/office-js#5083]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Outlook (outlook.office.com)
* Office version number: -
* Operating System: MacOS 15.1
* Browser (if using Office on the web): Chrome / Safari
 
## Expected behavior

When calling `getAttachmentContentAsync` the `result.value` object shouldn't be undefined and provide the attachment content when called in OWA (Outlook web access / outlook.office.com)

## Current behavior

`result.value` is undefined when `getAttachmentContentAsync` gets called from OWA.
Everything is working as expected when `getAttachmentContentAsync` is called from **Outlook for Mac Version 16.90.3** 

## Steps to reproduce

```
let item = Office.context.mailbox.item;
let attachmentId = attachments[i].id;

item.getAttachmentContentAsync(attachmentId, (result) => {
    console.log(result.value.content);
}
```

![image](https://github.com/user-attachments/assets/5bc4e909-6fcf-4f42-8723-f5fd08418544)

## Context

Im trying to get all attachments and their content from an Email item for further processing.
This is working in Outlook for Mac but not in OWA (anymore.. i think it was working before).

## Useful logs

- [x] Console errors
```
importMail.js:99 Uncaught TypeError: Cannot read properties of undefined (reading 'content')
    at importMail.js:99:83
    at outlook-web-16.01.js:20:267585
    at Object.a [as callback] (outlook-web-16.01.js:20:268189)
    at M (outlook-web-16.01.js:20:118286)
```
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by anjalitp** [comment]
@m-escher Looks like the issue is similar to  https://github.com/OfficeDev/office-js/issues/5068. Could you please check the error being returned by the API and confirm?

**Comment by m-escher** [comment]
@anjalitp yes i think you're correct! Im getting the same error when using the code from #5068

![image](https://github.com/user-attachments/assets/d5542a99-25bf-4d2d-b357-f9ce0ca0328c)

**Comment by anjalitp** [comment]
@m-escher  Thanks for the confirmation. Please follow https://github.com/OfficeDev/office-js/issues/5068 for updates on this issue.
