### ISSUE TITLE
Excel Online unable to load any addins through the store under personal account

### ISSUE THREAD

**Issue by ITCons** [OfficeDev/office-js#5085]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Office Online
* Operating System: MacOS
* Browser (if using Office on the web): Chrome, Firefox
 
## Expected behavior
Office add-in should work on both excel online and desktop.

## Current behavior
500 error in console on https://euc-excel.officeapps.live.com/x/_layouts/AddinServiceHandler.ashx?action=getEntitlements&app=excel
![Screen Shot 2024-11-13 at 23 32 57](https://github.com/user-attachments/assets/4ed3493a-12c0-404a-8a0a-b5f62ae1fdf1)
All office add-in stops working on excel online on all of our tenants. The add-in still shows up on Excel Online and Excel desktop under business account as designed to be.

## Steps to reproduce
1. Sign into a free office account
2. Load Bing Maps online addin through addin store (Or any addin, i.e. Maps for Excell)
3. Error pops up, addin ribbon is visible in nav, error happens again if clicked, no sidebar shown.

## Link to live example(s)
N/A

# Provide additional details
Works when the account has a 365 subscription.

## Context
Unable to load the addin

## Useful logs
500 error in console on https://euc-excel.officeapps.live.com/x/_layouts/AddinServiceHandler.ashx?action=getEntitlements&app=excel
[chrome-onedrive.live.com-1731536036426.log](https://github.com/user-attachments/files/17740071/chrome-onedrive.live.com-1731536036426.log)
[firefox-console-export-2024-11-13_23-9-53.txt](https://github.com/user-attachments/files/17740076/firefox-console-export-2024-11-13_23-9-53.txt)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuizhiSunMS** [comment]
Thx @ITCons , we acknowledged that and are working on it.

**Comment by RuizhiSunMS** [comment]
@ITCons, would you please have a try? Our colleagues did a fix and it should be not able to repro now.

**Comment by ITCons** [comment]
At the moment I don't see any changes, the above issue is still there: see attached screenshots.
Bing Maps add-in
![Screen Shot 2024-11-14 at 10 37 04](https://github.com/user-attachments/assets/eaa34819-0ed3-4abb-9021-eec34cd3324e)

Maps for Excel add-in
![Screen Shot 2024-11-14 at 10 35 58](https://github.com/user-attachments/assets/6d340e29-a84a-4e48-b5f4-b1f7bbe4f787)

**Comment by RuizhiSunMS** [comment]
Does this repro still? If yes, would you please share the region you are?

**Comment by ITCons** [comment]
It seems to be fixed now. Thanks.

**Comment by RuizhiSunMS** [comment]
> It seems to be fixed now. Thanks.

Nice to hear that. Have a nice day!
