### ISSUE TITLE
Outlook Add-in Pane always has overflow (y-axis) scroll (height of content pane is 100% + title bar height)

### ISSUE THREAD

**Issue by cody-lettau** [OfficeDev/office-js#5087]
# Issue Description
Recently, the add-in pane height is messed up and always has a y-axis scroll bar. It seems to be taking the Add-in title into account and then making the element that the add-in content is actually rendered into 100% of the height, leading to 100% + height of title bar.

![image](https://github.com/user-attachments/assets/a6e24945-b453-4a1f-9c16-d02ed562c6e2)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Windows (OWA - Chrome)
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: ______
* Browser (if using Office on the web): Chrome
 
## Expected behavior
Fix this to have the height that it use to and not always show a scroll bar.

## Current behavior
See the description and screenshot provided

## Steps to reproduce

1. Open any add-in in Outlook (OWA for sure -- I have not tested on desktop)
2. See that the height of the pane is always greater than the screen size and showing a y-axis scrollbar.

## Context
For Toggles for Outlook, we have a button that previously rendered in the bottom right corner of the add-in pane. Now it's pushed further down and requires the user to scroll to see it. Obviously I can fix this with styling, but it still results in empty space at the bottom of the rendered content, which is not ideal.

**Comment by anjalitp** [comment]
@cody-lettau  This looks like a duplicate of https://github.com/OfficeDev/office-js/issues/5051 . Please follow  the same for updates.

**Comment by cody-lettau** [comment]
Agree - let's close this out as a duplicate.
