### ISSUE TITLE
PowerPoint API beta capabilities implemented in official release v1?

### ISSUE THREAD

**Issue by mscc-sascha** [OfficeDev/office-js#5094]
In our PowerPoint add-in, which was developed with OfficeJS, we need to differentiate between the available shapes in PowerPoint. To do this, we query the type of shape by accessing the `shape.type` property. 

Unfortunately, the type of shapes has changed in recent weeks. A text box used to be of type `PowerPoint.ShapeType.geometricShape`, in the latest version we get either `PowerPoint.ShapeType.geometricShape`, `Placeholder` or `TextBox`. According to the [documentation](https://learn.microsoft.com/en-us/javascript/api/powerpoint/powerpoint.shapetype) this should only be available in the beta version. We refer to https://appsforoffice.microsoft.com/lib/1/hosted/Office.js.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Browser (if using Office on the web): Chrome
 
## Context

This unexpected change affected the functionality of the add-ins

**Comment by RuizhiSunMS** [comment]
Hi @mscc-sascha, thx for reporting here. I've reached out to PPT experts. Please be patient and we will reply here if any update.

**Comment by ElizabethSamuel-MSFT** [comment]
@mscc-sascha We're updating the documentation to show these as being in release. Will advise after the updates are published.

**Comment by ElizabethSamuel-MSFT** [comment]
@mscc-sascha The documentation has been updated so closing this issue.

Thanks.
