### ISSUE TITLE
How can I expand and collapse Heading Style paragraphs using Key board in MSWord

### ISSUE THREAD

**Issue by ManoharRTTR** [OfficeDev/office-js#5096]
## Post how-to questions about your code on Microsoft Q&A

How can I expand and collapse Heading Style paragraphs using Key board in word?

![image](https://github.com/user-attachments/assets/d420f520-6be9-4732-8dcf-82df047f4a0c)

**Comment by RuizhiSunMS** [comment]
Hi @ManoharRTTR, thx for reporting here.
May I confirm with you that you are using Word Win32 client? If yes, you may can try `shift`+`alt`+`+` and `shift`+`alt`+`-`.

**Comment by ManoharRTTR** [comment]
@RuizhiSunMS I am using 64 bit office. Thanks 

above keys are not working

**Comment by RuizhiSunMS** [comment]
Hi @ManoharRTTR,
I did some tests on 2 versions:
1. on v2303, both mentioned shortcuts worked.
2. on v2311, `shift` `alt` `+` (to expand heading) worked while `shift` `alt` `-`(to collapse) didn't. 

Please try and check how they are at your side and provide the version you are using.

**Comment by ManoharRTTR** [comment]
@RuizhiSunMS  I use Version 2409. you are right,  shift alt +  to expand worked while shift alt -(to collapse) didn't.

is this a bug?

**Comment by RuizhiSunMS** [comment]
> @RuizhiSunMS I use Version 2409. you are right, shift alt + to expand worked while shift alt -(to collapse) didn't.
> 
> is this a bug?

Not sure. I'll involve word experts to go on investigation. Create an ado #9543187 to track this. Will reply here if any update.

**Comment by RuizhiSunMS** [comment]
Hi @anjalitp, word experts shared another shortcut, would you please have a try on 'alt' 'shift' 'numsub' to see if it works in collapse headings?
