### ISSUE TITLE
How to create the Table of Content (TOC) using office.js Word API

### ISSUE THREAD

**Issue by harsh-borad** [OfficeDev/office-js#5097]
## How to create the Table of Content (TOC) using office.js Word API

Platform : PC desktop
Host: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2404 Build 16.0.17531.20140) 64-bit
Operating System: Microsoft Windows 11 pro

Hello Team ,
I want to create the TOC using office.js API but found nothing to create it directly,so I tried this below code snippet in ScriptLab with default configuration of ScriptLab HTML,CSS,Libraries.
That give me some result but i want to use Word's Built-in Table of Contents Table styles (eg. Automatic Table 1 , etc).

```
$("#run").on("click", () => tryCatch(run));

async function run() {
  await Word.run(async (context) => {
    const body = context.document.body;

    // Sample TOC data (replace this with your actual data source)
    const tocData = [
      { TOCid: "toc1", title: "Introduction", customPageNumber: 1 },
      { TOCid: "toc2", title: "Methodology", customPageNumber: 2 },
      { TOCid: "toc3", title: "Results", customPageNumber: 5 },
      { TOCid: "toc4", title: "Conclusion", customPageNumber: 8 }
    ];

    // Clear any existing TOC entries
    const tocContentRange = body.search("Custom TOC Start:", { matchCase: true });
    tocContentRange.load("items");
    await context.sync();

    if (tocContentRange.items.length > 0) {
      tocContentRange.items[0]
        .getRange()
        .expandTo(body.getRange("End"))
        .clear();
    }

    // Insert a header for the TOC
    body.insertParagraph("Custom TOC Start:", Word.InsertLocation.end);

    // Loop through TOC data and insert each entry as a new paragraph
    tocData.forEach((entry) => {
      // Insert title with custom page number
      const tocEntryParagraph = body.insertParagraph(
        `${entry.title} ........................... ${entry.customPageNumber}`,
        Word.InsertLocation.end
      );

      // Load the range for hyperlink creation
      const range = tocEntryParagraph.getRange("Whole");
      range.hyperlink = `#${entry.TOCid}`; // This sets the range as a hyperlink to the bookmark
      range.font.color = "Blue"; // Optionally, set font color to indicate hyperlink style

      tocEntryParagraph.style = "TOC 1"; // Apply TOC style or custom formatting as needed
    });
    body.insertParagraph("Custom TOC End", Word.InsertLocation.end);
    await context.sync();
  });
}
// Default helper for invoking an action and handling errors.
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    console.error(error);
  }
}
```
This is result below:
![image](https://github.com/user-attachments/assets/559f9203-e743-426e-abf4-9371242b13ba)

**Comment by RuizhiSunMS** [comment]
Hi @harsh-borad, thx for reporting here. 
May I confirm that the below is what you want? If yes, range.insertField() may could help you with word.fieldtype.toc
![image](https://github.com/user-attachments/assets/85b9821b-7500-43bd-b83e-55ebb0dcfb85)

**Comment by harsh-borad** [comment]
@RuizhiSunMS thank you for looking into it.

- Your given solution seems helpful but what I exactly want is bit different. _**,I don't want to make TOC from selection but from my stored data and also with styles.**_. I have some data stored at some place,I took dummy data instead of it in provided code. I have custom bookmark Id which created using Guid in my stored data, based on which my current logic is working.

-Current Logic code snippet:
```
function AddTocData() {

    var TocTitle = $('#TocTitle').val().trim();
    var TocPageno = $('#TocPageno').val();
    var TOCId = "TOC_" + createGuid();
    var Id = TOCId.replaceAll("-", "");

    //var allowedCharsRegex = /^[a-zA-Z0-9\s\-_]+$/;

    if (TocTitle == "" && TocPageno == "") {
        showNotification("E", translate("Addin_J_755"), 5000);
    } else if (TocTitle == "") {
        showNotification("E", translate("Addin_J_756"), 5000);
    } else if (!ValidName(TocTitle)) {
        showNotification("E", translate("Addin_J_1706"), 5000);
    } else if (TocPageno == "") {
        showNotification("E", translate("Addin_J_757"), 5000);
    } else {
        TOC = {
            TOCId: Id,
            ProjectId: MetaInfo.ProjectId,
            SectionId: MetaInfo.SectionId,
            TOCTitle: TocTitle,
            PageNo: TocPageno,
            ModifyBy: MetaInfo.UserName,
        }
        var url = baseCoreUrl + "DMAPI/TOCdetails";
        DoAjaxCall(url, "POST", JSON.stringify(TOC), Addtocsucces, Addtocfaild);
    }
}

async function AddTOCtoDoc(res) {
    await Word.run(async function (context) {
        var selection = context.document.getSelection();
        selection.load("text,hyperlink,font/size");
        await context.sync();
        if (selection.text != "") {
            var fontsize = selection.font.size;
            if (Object.keys(TOC).length == 0) {
                var bookmarkName = res;
                var isbookmarkfound = false;
                var body = context.document.body;
                var bodyRange = body.getRange();
                bodyRange.load();
                var bookmarks = bodyRange.getBookmarks();
                await context.sync();
                for (var i = 0; i < bookmarks.value.length; i++) {
                    if ("TOC_TableofContent" == bookmarks.value[i]) {
                        isbookmarkfound = true;
                    }
                }

                MappedTOC(bookmarkName);
                var hyperlinkHtml = '<a href="#' + bookmarkName + '" ><span style="font-size: 12pt;">' + selection.text + '</span></a>';
                selection.insertHtml(hyperlinkHtml, Word.InsertLocation.replace);
                selection.font.size = fontsize;
                await context.sync();
                if (!isbookmarkfound) {
                    selection.insertBookmark("TOC_TableofContent", { coercionType: "start" });
                    await context.sync();
                }
                showNotification("S", translate("Addin_J_758"), 5000);
                createAndPostLogData({
                    projectId: MetaInfo.ProjectId,
                    documentId: "",
                    sectionId: MetaInfo.SectionId,
                    event: 323,
                    parentEvent: 92,
                    logLevel: 6,  // 6: Info
                    methodName: "AddTOCtoDoc",
                    message: "",
                    eventDescription: "Mapped successfully",
                    exception: "",
                    companyId: "",
                    createdBy: MetaInfo.OfficeUserId,
                    additionalData: {
                        username: MetaInfo.OfficeUserId
                    }
                });
                $($('.Toclist').find("#Link_" + bookmarkName)[0]).show();
                $($('.Toclist').find("#Link_" + bookmarkName)[0]).addClass("LinkToc");
            }
            else {
                let bookmarkName = TOC.TOCId;
                selection.insertBookmark(bookmarkName);

                //var contentControl = selection.insertContentControl();
                //contentControl.tag = bookmarkName;

                await context.sync();
                showNotification("S", translate("Addin_J_803"), 5000);
                TOC = {};
                $('#TocTitle').val('');
                $('#TocPageno').val('');
                if ($("#TOCpane").css("display") == "block") {
                    LoadTOC();
                }
            }
            autoSaveWord();
            $('#TOC, .overlay').hide();
        }
        else {
            showNotification("E", translate("Addin_J_760"), 5000);
        }
    });
}

```
- I want some styles so I used the **Word.Paragraph.styleBuiltIn** for style of paragraph in previously provided code but it gives me General Exception error in ScriptLab but I can avoid it coz you gave some solution which will be more helpful for me if its give me some liberty to change the style of TOC too.

- So here by I'm attaching the code and video evidence what I m trying to say :
[ScriptLab-TOC.zip](https://github.com/user-attachments/files/17773308/ScriptLab-TOC.zip)

**Comment by RuizhiSunMS** [comment]
@harsh-borad, sorry but I think I don't get your point very well. 
Looks like:
1. you have some bookmarks
2. You added some paragraphs
3. each paragraph is a hyperlink linked to one bookmark
4. each paragraph's format is like one item of TOC (but they are not TOC actually and you don't mind whether they are TOC or not)
5. what you want to resolve most is that setting paragraphs' style to be like TOC is not as you expected

Please correct me if wrong.

**Comment by harsh-borad** [comment]
Hey @RuizhiSunMS so sorry for messing things up !! just ignore above things.

**Just clear out one thing that based on your below solution ,how can I create the TOC using some stored data instead of selection and range?**


> Hi @harsh-borad, thx for reporting here. May I confirm that the below is what you want? If yes, range.insertField() may could help you with word.fieldtype.toc ![image](https://private-user-images.githubusercontent.com/97079392/386530102-85b9821b-7500-43bd-b83e-55ebb0dcfb85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MDM0MDEsIm5iZiI6MTczMTkwMzEwMSwicGF0aCI6Ii85NzA3OTM5Mi8zODY1MzAxMDItODViOTgyMWItNzUwMC00M2JkLWI4M2UtNTVlYmIwZGNmYjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE4VDA0MTE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjZWYxYjQzYjc5YmQ1NzRlOTZhNjhlMTU3ZDE0NjhhM2I1MmE2NWExODhhMjk3MDE1YzE1YTg0MDcyMmExMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HIfJuRHNWSDWKx0AeEVSSLT9LTKdgodJUStvfxVHLrk)

**Comment by RuizhiSunMS** [comment]
Hi @harsh-borad, may I regard this `how can I create the TOC using some stored data instead of selection and range?` as your main question? 
If so, I think using range is necessary for insertField is a method of `range`. You can get a `range` by many ways not limited to 'selection'.

**Comment by harsh-borad** [comment]
> Hi @harsh-borad, may I regard this `how can I create the TOC using some stored data instead of selection and range?` as your main question?

Yes ,you can.

> If so, I think using range is necessary for insertField is a method of `range`. You can get a `range` by many ways not limited to 'selection'.

could you please help me on it by giving some example? It will be very helpful !!

**Comment by RuizhiSunMS** [comment]
> > Hi @harsh-borad, may I regard this `how can I create the TOC using some stored data instead of selection and range?` as your main question?
> 
> Yes ,you can.
> 
> > If so, I think using range is necessary for insertField is a method of `range`. You can get a `range` by many ways not limited to 'selection'.
> 
> could you please help me on it by giving some example? It will be very helpful !!

As you can search in MS doc like https://learn.microsoft.com/en-us/search/?scope=Office%20Add-ins&terms=getrange, there are many objects like comments, paragraphs containing `getRange`. You can also create it as `new Range()`. I'm not sure about your specific usage but believe you can find the resolution there.

**Comment by harsh-borad** [comment]
@RuizhiSunMS Thank you for help.
