### ISSUE TITLE
`Office.context.mailbox.item.internetHeaders.setAsync` fails on Classic UI when replying/forwarding .eml file

### ISSUE THREAD

**Issue by AtharvaDevSeclore** [OfficeDev/office-js#5099]
# `Office.context.mailbox.item.internetHeaders.setAsync` fails on Classic UI when replying/forwarding .eml file

## Your Environment

* Platform: Mac
* Host: Outlook 16.91
 
## Expected behavior

`Office.context.mailbox.item.internetHeaders.setAsync`  should be successful

## Steps to reproduce
1. compose a mail
2. click on file -> save as and save the mail on the device as savedMail.eml
3. open the folder containing savedMail.eml
4. ctrl+click on savedMail.eml and open in outlook
5. reply/forward mail
6. open inspect element window
7. try to set internet headers
```
Office.context.mailbox.item.internetHeaders.setAsync(
  { "preferred-fruit": "orange", "preferred-vegetable": "broccoli", "best-vegetable": "spinach" },
  function (asyncResult) {
    if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
      console.log("Successfully set headers");
    } else {
      console.log("Error setting headers: " + JSON.stringify(asyncResult.error));
    }
  }
```

## Current behavior
`Office.context.mailbox.item.internetHeaders.setAsync`  fails on classic UI with error code 5001

# Provide additional details
I observed this issue only in classic UI. modern UI is working as expected

**Comment by mobisw-msft** [comment]
Hey @AtharvaDevSeclore , 

We are investigating this issue and will get back to you shortly.

**Comment by mobisw-msft** [comment]
Hey @AtharvaDevSeclore ,

Unfortunately, we are not able to reproduce this issue in Legacy outlook for Mac, or in the Modern Outlook for Mac. If this is an issue only with legacy Outlook for Mac, we are not prioritizing this fix on the Classic Mac UI. Users can switch to New Outlook for Mac experience- which works as expected. Please reopen the issue in case you experience this in the new Outlook for Mac.
