### ISSUE TITLE
Using Excel/Word/PowerPoint file programmatically

### ISSUE THREAD

**Issue by alippai** [OfficeDev/office-js#51]
Is it possible, to write a plugin for PowerPoint, where I can select an Excel file and read the range values given the base64/blob? 

I'd like to generate PowerPoint slides based on Excel (without external tools or VBA macros)

**Comment by Zlatkovsky** [comment]
@alippai , this sounds more like a question, not an "issue" per se.  Do you mind asking it on https://stackoverflow.com/tags/office-js, and posting a link back here for reference?

**Comment by alippai** [comment]
Well, this was more like a feature request. AFAIK I can't construct an Excel contect/object/document and use the API on it.

I'm not sure this is something matching your architecture and designs or this is "won't fix", so that's the question part.

**Comment by Zlatkovsky** [comment]
I don't want to be pedantic about it, so I hope I'm not scaring you off from asking questions, or raising issues and feature-requests, in the future.  But for this particular one, there actually *is* an answer (or at least, a possible workaround) -- and if there are elements of it that are not addressed by the workaround (which will probably also be the case), though might turn into a *series* of feature requests, not just one.

So if it's a question -- even if it's a question masquerading as a feature request -- I'd rather start with StackOverflow, and then break it apart into concrete work items as needed.  Sound fair?
