### ISSUE TITLE
SSL certificate required for Outlook add-in development not working for Chrome and Firefox

### ISSUE THREAD

**Issue by neso613** [OfficeDev/office-js#510]
HI
I am developing Outlook Web add-in using Office.js
As required, I have generated SSL certificate for my developing stage.But that SSL certificate is not working for Chome and Firefox.

## Expected Behavior
SSL also working for Chrome and Firefox

## Current Behavior
SSL only working for Edge, IE, not for Chome and Firefox

## Steps to Reproduce, or Live Example
Please sideload Microsoft add-in using following link-
https://mop.infocus.net:5000/infocus-conx-outlook-addin.xml

As this is server URL. Inspite that, its not working.

Please suggest some solution.

**Comment by exextoc** [comment]
The issue does'nt seem related to add-ins. The following is the warning firefox throws when we try to load the manifest.
"Websites prove their identity via certificates, which are issued by certificate authorities. Most browsers no longer trust certificates issued by GeoTrust, RapidSSL, Symantec, Thawte, and VeriSign. mop.infocus.net uses a certificate from one of these authorities and so the website’s identity cannot be proven.
You may notify the website’s administrator about this problem."

**Comment by neso613** [comment]
> The issue does'nt seem related to add-ins. The following is the warning firefox throws when we try to load the manifest.
> "Websites prove their identity via certificates, which are issued by certificate authorities. Most browsers no longer trust certificates issued by GeoTrust, RapidSSL, Symantec, Thawte, and VeriSign. mop.infocus.net uses a certificate from one of these authorities and so the website’s identity cannot be proven.
> You may notify the website’s administrator about this problem."
Ok. Thanks for support.
