### ISSUE TITLE
[PowerPoint] <DisplayName> tag bug when open taskpane with Office.addin.showAsTaskpane()

### ISSUE THREAD

**Issue by keienla** [OfficeDev/office-js#5103]
## Environment

* Platform: Office on the web
* Host: PowerPoint
* Operating System: Windows 11
* Browser: Firefox/Chrome
 
## Expected behavior
When opening a taskpane, the value inside the tag `DisplayName` should be used to set the title of the taskpane. 

## Current behavior
There is two case. One work well, the other doesn't work.

### <Action xsi:type="ShowTaskpane">

In this case, the value of DisplayName is used and everything work well.

![image](https://github.com/user-attachments/assets/faf9c2f2-40f4-4971-a599-b4989cb52d5e)

### <Action xsi:type="ExecuteFunction">

In this case, when the action is `ExecuteFunction`, and the function associated open the taskpane with `Office.addin.showAsTaskpane()`, in this case the value of `DisplayName` is not showed and the `<div class="PaneLabel" ...>` is empty.

![image](https://github.com/user-attachments/assets/f5db5f87-1bf8-4478-94d6-09e2a1118300)

## Steps to reproduce

Create an Addin with shared runtime used. Be sure that `DisplayName` tag value is not empty. Create a Control with Action as
``` xml
<Action xsi:type="ExecuteFunction">
    <FunctionName>openTaskpaneWithCode</FunctionName>
</Action>
```
And the function
``` typescript
function openTaskpaneWithCode(event: Office.AddinCommands.Event) {
  Office.addin.showAsTaskpane()
}

// Register the function
Office.actions.associate("openTaskpaneWithCode", openTaskpaneWithCode);
```

When you will click of the button to execute the function, the taskpane will have an empty name.

## Link to live example
I've created a small github repo that show the bug: https://github.com/keienla/test-ppt-name

I've created two button, one open taskpane with `<Action xsi:type="ShowTaskpane">` and the other with `<Action xsi:type="ExecuteFunction">` to show the difference. If you open the taskpane with one of the two button, you'll have to reload the page to see the result of the other button (it look like the state of the name is keeped).

## Context
I'm working on a small addin for PowerPoint and, as this bug is not blocking, having a name for my taskpane will be better. As in my app, the body have a background and so the body override the close button (and it's a little ugly). 

Thank's in advance for taking time to watch this issue!

**Comment by RuizhiSunMS** [comment]
Hi @keienla, sorry for the late response. I've reached out to PPT experts. Please be patient and we will reply here if any update.

**Comment by EsterBergen** [comment]
Hi @keienla - thanks for bringing this to our attention. We've filed the bug (9555953) and will provide updates to this thread when it's addressed. As you mentioned it's not blocking and will be prioritized according to other items in our backlog. Thanks!
