### ISSUE TITLE
Missing Line Between Two Mails in Mail Body Returned by `Office.context.mailbox.item.body.getAsync` on Reply/Forward

### ISSUE THREAD

**Issue by AtharvaDevSeclore** [OfficeDev/office-js#5104]
# Provide required information needed to triage your issue
When using the `Office.context.mailbox.item.body.getAsync` function to retrieve the mail body, I observed that the line separating the original message and the reply/forward is not present in value returned. I noticed this issue in Legacy Outlook

## Your Environment

* Platform: Mac
* Host: Outlook, Version 16.85, Legacy
 
## Expected behavior

Line separating original message and the reply/forward should be present in body returned by `Office.context.mailbox.item.body.getAsync` 

## Current behavior

Line separating original message and the reply/forward is missing in body returned by `Office.context.mailbox.item.body.getAsync`

**Comment by mobisw-msft** [comment]
Hey  @AtharvaDevSeclore ,

Thank you for sharing this issue. As a workaround, users can switch to the [New Outlook for Mac](https://support.microsoft.com/en-gb/office/the-new-outlook-for-mac-6283be54-e74d-434e-babb-b70cefc77439?ui=en-us&rs=en-gb&ad=gb) experience which works as expected. We are not prioritizing this fix on classic Mac UI; please reopen the issue in case the workaround does not solve your scenario.
