### ISSUE TITLE
The addin is timing out and unable to send emails.

### ISSUE THREAD

**Issue by FaseelUlla** [OfficeDev/office-js#5105]
We are developing an outlook web addin using office js Smart alert template.
When Forward/Reply an email which popped out after previewing the attachment which is received from a user adding is showing time out. oncompose ,onsend Events are not triggered. 
we are previewing the received attachment and popping it out and then Forward/Reply that Email after popping out.
After adding recipient click on send button 

Your Environment
Platform [PC desktop, Mac, iOS, Office on the web]: Office on the web
Host [Excel, Word, PowerPoint, etc.]: Outlook
Operating System: Windows
Browser (if using Office on the web): Chrome , Edge

Expected behavior
addin should not time out and task pane should be open

Current behavior
addin is getting timed out

Steps to reproduce
1-Go to a mail containing attachments in inbox.
2- Preview any attachment and pop out the mail.
3-Forwad/Reply to the mail. 
4-Add recipient and click on send

# Provide additional details
Console log inside the Event handlers are not printed when popped out through attachment triggered.

**Comment by mobisw-msft** [comment]
Hey @FaseelUlla ,

We are unable to reproduce the issue. Can you share a screen recording of your experience where you're facing this issue- perhaps one where your add-in is working for regular scenario and where it's broken for the popout scenario of attachment preview? Are you seeing the relevant notifications to suggest your add-in is running in the pop out context?

**Comment by rkpathak** [comment]
@FaseelUlla Please share the basic onsend handler function including event.completed, using which we can repro the timeout for this scenario. This will help us repro and debug this issue.

**Comment by arpitsangwanmsft** [comment]
Hey @FaseelUlla!
This issue was fixed and should not be a repro anymore. Please re-validate the scenario and let us know in-case you face any problems.
Thanks!
