### ISSUE TITLE
Extension point used by the Polls feature

### ISSUE THREAD

**Issue by jozefizso** [OfficeDev/office-js#5106]
Hi, Outlook clients have the Polls app (by Microsoft Corporation) available.

When composing new email and adding a poll to it using the Polls app command, an editable live content will be added to the email.

I am struggling to find which extension point is used by the Polls app to implement this functionality.

<img width="1182" alt="image" src="https://github.com/user-attachments/assets/54cb9408-d2ea-47c1-9a80-9590a626a3cb">

**Comment by mobisw-msft** [comment]
Hey @jozefizso , 

Unfortunately the Polls feature does not use OfficeJS or our Extensions Framework, and is a feature of Outlook. If you have any issues regarding the feature you can reach out to [our send feedback option.](https://support.microsoft.com/en-us/office/contact-support-and-provide-feedback-in-new-outlook-for-windows-4a4bcc80-c71e-4e44-97c1-d0e62452ef4a)

**Comment by jozefizso** [comment]
How can system integrators create compelling solutions when Microsoft is using private APIs not available to ISVs?

**Comment by mobisw-msft** [comment]
@jozefizso ,

You can have a look at [Adaptive Cards](https://learn.microsoft.com/en-us/adaptive-cards/getting-started/outlook) to see if they fit your scenario. If you're looking for this functionality within Outlook add-ins, this will be considered as a new feature request. 

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.

**Comment by jozefizso** [comment]
If this was able to be done in Adaptive Cards, Microsoft would not create a private API for this.

I think this is a violation of the Digital Markets Act as Microsoft as a gatekeeper of Outlook is preventing the same access to the product for each partner.

**Comment by rkpathak** [comment]
Currently the feature you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
