### ISSUE TITLE
The web add-in is not triggered and app is bypassed - New Outlook

### ISSUE THREAD

**Issue by riddhi-p-28** [OfficeDev/office-js#5108]
We are developing an outlook web addin using office js Smart alert template.
We are using LocalStorage to store some of our appdata. However, what we observed is that sometimes our app url does not show up in the LocalStorage. When this scenario occurs, the mails get sent directly bypassing the web add-in app and the Javascript files are not loaded.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: New Outlook Windows App
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Operating System: Windows
 
## Expected behavior
The app url should show up in the LocalStorage data and the app files should be loaded when new compose is triggered and validations should not be bypassed.

## Current behavior

- The app url doesn not show up in LocalStorage due to which our web add-in is getting bypassed without validations.
- NO network calls related to the web add-in was present
- NO errors were present in the console related to web add-in app.

## Steps to reproduce

1. Launch New outlook 
2. Compose a new email
3. Add recipient subject and body
4. Click on send
5. Go to devtools -> Application tab-> LocalStorage -> observe.

## Useful logs

[new outlook issue.zip](https://github.com/user-attachments/files/17810857/new.outlook.issue.zip)

**Comment by mobisw-msft** [comment]
Hey @riddhi-p-28 ,

Can you share your add-in manifest with a hosted endpoint (perhaps one where the code isn't minified) so that we can debug this further?

Do you see this issue on Outlook for Web?
