### ISSUE TITLE
ios dialog title area is included into the viewport height

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#511]
## Expected Behavior
The dialog title should not be included in the viewport height.
When writing css with height: 100%, this should only contain the area under the dialog title.
![image](https://user-images.githubusercontent.com/6338132/57538517-df238f80-7348-11e9-9ee6-7ec7c064c92a.png)

## Current Behavior
height: 100% included the title area
![image](https://user-images.githubusercontent.com/6338132/57538438-b26f7800-7348-11e9-986e-3e0b1ba61e94.png)

## Steps to Reproduce, or Live Example

Display the simple page with flexbox layout within a dialog in ios.
You'll notice that the blue area is not visible. When you increase the height of the blue area to 40px then you'll see slowly the blue area.

```
<html>
<style>
body{ display: flex; flex-direction: column; height:100%; color: white}
.red { backround-color: red; flex: 1 }
.blue{ backround-color: blue; height: 20px }
</style>
<body>
  <div class="red"> I am red<div>
  <div class="blue">I am blue<div>
</body>
</html>
```

## Context
The ui fabric dialog content area uses flexbox for designing flexible areas. We are using the 
same styles to display this within a office dialog. The buttons from the ui fabric dialog content are always cutted, because the 30px of the dialog title is always added to the full height.

## Your Environment

* Platform: iOs
* Host: Word, PowerPoint, Excel

**Comment by Rick-Kirkham** [comment]
This looks like a Fabric issue, not an issue with the Office JavaScript library. Are you using Fabric React or the non-React Fabric?

**Comment by barisbikmaz** [comment]
Just look my steps to reproduce. This is pure html with css with no third party included. I'm using the officejs dialog.

**Comment by barisbikmaz** [comment]
Just to note that we're still having this issue.

**Comment by lliu113** [comment]
@barisbikmaz  - so sorry for the very belated response to this. Are you still seeing this issue? Completely agree with you that the header should not included in the height of the dialog. If you're still seeing this, I can open up a bug to investigate.

**Comment by lliu113** [comment]
@barisbikmaz - I'm going to go ahead and close this issue for now. Please reactivate if you're seeing this and we can investigate. Thanks!
