### ISSUE TITLE
Certain files do not work in Excel Online due to WEF reference ID attribute's case-sensitivity

### ISSUE THREAD

**Issue by wh1t3cAt1k** [OfficeDev/office-js#5110]
## Summary

Upon opening of the following file, `await Office.addin.setStartupBehavior(Office.StartupBehavior.load);` or any `Excel.run(...)` calls hang indefinitely during our add-in's start-up sequence so it cannot initialise.

[Sage Intacct Demo GM Fixed.xlsx](https://github.com/user-attachments/files/17813283/Sage.Intacct.Demo.GM.Fixed.xlsx)

Session ID: 035bc6eb-68f2-2001-b9d2-b2f9d9092f3a

There are no suspicious errors in the console so it's impossible to understand what went wrong.

**The issue replicates only on a subset of files, so it might be because of an internal metadata issue.**

**UPD**: this is confirmed, see below

<img width="777" alt="image" src="https://github.com/user-attachments/assets/1b618f3c-cd23-4a54-ba03-1bd2bcfa6e41">

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on the Web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.18317.42305
* Operating System: Windows 11
* Browser (if using Office on the web): Chrome
 
## Expected behavior

The file to open and the add-in to start without any problems.

## Current behavior

The add-in cannot interact with the Excel API because it simply hangs.

## Steps to reproduce

1. Install the Velixo NX add-in from the AppSource.
2. Try to open the attached file and click the ribbon button.

[Velixo internal tracking item](https://velixo.atlassian.net/browse/RD-656)

**Comment by wh1t3cAt1k** [comment]
<img width="659" alt="image" src="https://github.com/user-attachments/assets/17d57e8d-ed2f-4828-b04f-9366ed877ed5">

Note that there are two reference IDs in `webextension1.xml` inside the file structure. They differ only by case and by store value.

Does anything here looks unexpected and suspicious? I can guarantee that this file **has not been manually tampered with** but it was opened on both Excel Online and Excel for Mac.

Also, this file works just fine on Excel for Mac so it is an Excel Online-specific issue.

**Comment by wh1t3cAt1k** [comment]
Once I manually convert the reference ID to uppercase (I suspect I didn't even have to remove the alternate references):

<img width="843" alt="image" src="https://github.com/user-attachments/assets/41970953-17a6-46de-a4be-a6a32d0abe28">

The file opens without any problems.

Guys, this seems like an easy fix to handle on the Excel's side? You could either

1. Auto-correct the reference ID in the file? OR
2. Not touch the file but do a `.toUpper()` on any reference ID encountered when processing web extension references?

I think that manually fixing the files is not a good option here and I'd rather have an in-product fix.

**Comment by wh1t3cAt1k** [comment]
In conclusion, I think this is the same as #3993, just a new instance of the same issue... Maybe a fix could be expedited?

**Comment by wh1t3cAt1k** [comment]
Duplicate of #3993

**Comment by guoms1** [comment]
Hi, wh1t3cAt1k

Thank you very much for reporting this issue. 

Since it is the same as issue [3993](https://github.com/OfficeDev/office-js/issues/3993), and 3993 contains more detailed information, I will continue to follow up on this matter there.
