### ISSUE TITLE
NAA behaves differently in event-based activation

### ISSUE THREAD

**Issue by barclayadam** [OfficeDev/office-js#5113]
# Provide required information needed to triage your issue

NAA in PC Desktop Outlook event-based activation gives a different error to other platforms:

`
untrusted_origin: The origin is not valid for Nested App Auth.
`

## Your Environment

* Platform: PC Desktop
* Host: Outlook
* Office version number: 16.0.18129.20116
* Operating System: Windows 11
 
## Expected behavior

NAA to work consistently given the same setup across platforms

## Current behavior

Currently, I have NAA working successfully in OWA (event-based and task pane) and the task pane in PC desktop, but the event-based activation in PC desktop gives me an error, as above. Using verbose logging of msal-browser library I see:

````
[Tue, 19 Nov 2024 12:08:30 GMT] : [] : @azure/msal-browser@3.26.0 : Info - Nested App Auth Bridge available: true
[Tue, 19 Nov 2024 12:08:30 GMT] : [] : @azure/msal-browser@3.26.0 : Error - Cached tokens are not found for the account, proceeding with silent token request.
````

Followed by the error above (`untrusted_origin: The origin is not valid for Nested App Auth.`).

I have added the `brk-multihub` redirect URI to our Entra App Registration, which I would have expected to need to be correct to work anywhere else:

![image](https://github.com/user-attachments/assets/e26bc47e-af48-43d3-a793-d488cf129996)

Our setup and use ofthe PCA is as below:

````typescript
 const pca = await createNestablePublicClientApplication({
        auth: {
            clientId: 'our-client-id-of-above-app',
            authority: 'https://login.microsoftonline.com/organizations',
        },
});

const tokenRequest = {
    scopes: ['openid', 'profile'],
};

// This fails with the errors above
const userAccount = await pca.acquireTokenSilent(tokenRequest);
````

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by codexeon** [comment]
I believe the problem is that you are missing `.well-known/microsoft-officeaddins-allowed.json` hosted on your domain. Documentation for this file is here: https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/use-sso-in-event-based-activation although it needs to be updated to mention it is also required for Nested App Auth. https://github.com/OfficeDev/Office-Add-in-samples/blob/main/Samples/auth/Outlook-Event-SSO-NAA/src/well-known/microsoft-officeaddins-allowed.json is a sample that does implement this file properly.

**Comment by RobertoBorges** [comment]
Same issue, but when running on HTTP instead of HTTPS

**Comment by barclayadam** [comment]
@codexeon thank you for the heads up. I've finally got around to testing this and you are correct, I was missing that file.

Frustratingly, I accidentally removed it in my dev environment after a different piece of work. If I had tested it elsewhere it would have worked fine :)

**Comment by davidchesnut** [comment]
Hi @barclayadam,

Glad this is working now! One more note is to be sure you have at least on Microsoft Graph scope or the request can fail in some scenarios. There's more information about the tokens you request and required scopes in the [FAQ](https://learn.microsoft.com/office/dev/add-ins/outlook/faq-nested-app-auth-outlook-legacy-tokens?#how-do-i-validate-the-id-token-or-authenticate-the-user).

Cheers,
David

**Comment by davidchesnut** [comment]
> Same issue, but when running on HTTP instead of HTTPS

Hi @RobertoBorges, You should always use HTTPS with Entra ID tokens and API calls to keep things secure.
