### ISSUE TITLE
Unpredictable behavior of Office.context.mailbox.item.getAttachmentsAsync

### ISSUE THREAD

**Issue by hmuris** [OfficeDev/office-js#5114]
When the method Office.context.mailbox.item.getAttachmentsAsync is executed, attachments are sometimes returned sometimes not.
It differs for inline attachments.

## Expected behavior
Always return attachments correctly.

## Current behavior
If the new email is written, and inline attachments are added, mentioned method is not returning attachments. When normal attachments are added and removed, then it does.

## Steps to reproduce

1. Compose new email
2. Turn on taskpane addin
3. Add inline attachment (WinKey + S, part of the screen and paste it in the email)
4. Click the Run in tha addin
5. **Error**: no attahments are returned.

If a normal attachment (not inline) is added (sometimes and removed, and sometimes another added again), the method returns all attachments inline and regular ones.

Here is the demo project, just `npm install` and then `npm start` to run the project.
[TaskpaneDemo.zip](https://github.com/user-attachments/files/17817837/TaskpaneDemo.zip)

Demo project is generated with Yeoman generator for Office Add-ins and then slightly modified. Modified are manifest.xml and taskpane.js.

**Comment by hmuris** [comment]
Any news here? We need this to work asap as there are many customers using our Add-in.

**Comment by MarcMei80** [comment]
@hmuris There is already an issue classified as a product bug. https://github.com/OfficeDev/office-js/issues/5068 Feel free to add comments there to hopefully get a higher priority. Unfortunately, many of our customers have been affected.

**Comment by sirrganggi** [comment]
There are multiple reports like this one (e.g. #5068, #5031), so any news or feedback regarding a prompt solution would be important and helpful. Many people are affected of this issue.

**Comment by hmuris** [comment]
While you are fixing this issue, it would be most meaningful to add the content id for inline attachments to the data this action returns. This would give office.js the complete picture of the current item (email or appointment)

**Comment by samantharamon** [comment]
Hi @hmuris,

Thank you for reporting this issue. Based on the update in #5068, the team is currently investigating this issue.

**Comment by rajjha-msft** [comment]
Hey @hmuris 

Is this issue still a repro ?

**Comment by kumarshrey-msft** [comment]
I believe this is same issue as #5031, please follow the same for updates. Closing this as duplicate
