### ISSUE TITLE
 Document Fails to Open if It Contains External Links

### ISSUE THREAD

**Issue by GajananVadekar** [OfficeDev/office-js#5117]
Platform : PC desktop
Host: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2404 Build 16.0.17531.20140) 64-bit
Operating System: Microsoft Windows 11 pro.

Hi team,
I am encountering an issue where Word documents fail to open when they contain certain external links. Attempting to open such a document results in a "General Exception Error".

Used below provided code
```
await Word.run(async function (context) {
    if (!loadEmpty) {
        if (abc) {
            context.document.insertFileFromBase64(mybase64, "Replace", {
            importTheme: true,
            importStyles: true,
            importParagraphSpacing: true,
            importPageColor: true,
            importChangeTrackingMode: true
            });
			await context.sync();
		}
	}
}).catch(async function (error) {
	if (error instanceof OfficeExtension.Error) {
        console.log('Debug info: ' + JSON.stringify(error.debugInfo));
    }
});
```

Error:- 
"code":"GeneralException","message":"GeneralException","errorLocation":"Document.insertFileFromBase64"

Please look into this issue and provide a resolution. Specifically:
1.Investigate why documents with external links are failing to open.
2.Suggest any workarounds or fixes to ensure that documents with external links can be accessed without errors.

Am provided an document for reference 
[TestExternalLinks.docx](https://github.com/user-attachments/files/17826719/TestExternalLinks.docx)

Thanks.

**Comment by RuizhiSunMS** [comment]
Hi @GajananVadekar, thx for reporting here. May I confirm with you that, converting the attached doc into a base64 string and insert it into another doc like what you did in code snippet, would encounter the exception, is it?

**Comment by GajananVadekar** [comment]
@RuizhiSunMS , We have a document in a blob, but attempting to load the document using a Base64 string results in an exception. I hope this clarifies your concern.

Feel free to reach out if you have any questions or need further clarification.

**Comment by RuizhiSunMS** [comment]
Reproed. Create #9563217 to track this and involve experts to take a look. Will reply here if any update.
Thx for your patience in advance.

**Comment by jipyua** [comment]
hi @GajananVadekar Thanks for reporting this issue, this is because the OLE object has potential security threats and from API side it has been disabled. Please try to remove it or replace with other features based on your request. Thanks.

**Comment by GajananVadekar** [comment]
@jipyua , What needs to be replaced, and how should it be done? I didn’t fully understand your point.

**Comment by jipyua** [comment]
hi @GajananVadekar I mean for the external file link in your document, such as the following one, can you change it to other features? Such as if you are referencing a table in the excel worksheet, can you instead use a Word table in the document. Sorry that the OLE object is not supported so far in the InsertFileFromBase64 scenario.
![image](https://github.com/user-attachments/assets/897a3a8f-98fd-4f8c-b5b9-2eb74a6bcee0)
