### ISSUE TITLE
Sorting Issue on Selected Range in Office.js: First Item Stuck on Z-A Sort After A-Z

### ISSUE THREAD

**Issue by libjosep** [OfficeDev/office-js#5119]
When sorting a selected range of cells in a worksheet using Office.js, the first item in the range remains fixed during a descending (Z-A) sort, after an ascending (A-Z) sort has been performed. This issue occurs when sorting is applied without expanding the selection

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Office on web
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows 11
* Browser (if using Office on the web): Edge
 
## Expected behavior
When sorting the range A3:A20 in descending order (Z-A) without expanding the selection, all items in the range should rearrange correctly according to the sort order, regardless of any prior sort actions.

## Current behavior
After performing an ascending sort (A-Z) on the range A3:A20, a subsequent descending sort (Z-A) on the same range causes the first item in the range (A3) to remain static and not participate in the sort operation.

## Steps to reproduce

1. Run the attached .yml in scriptlab
2. Click on "Set Up Sheet" button to create the contents.
3. In Excel, manually select the range A3:A20 (do not expand the selection to other columns).
4. Perform an ascending sort (A-Z) on the selected range.
5. Next, perform a descending sort (Z-A) on the same selected range.
6. Observe the behavior: The first item in the range (A3) remains static and does not participate in the descending sort.

## Link to live example(s)

1. Scriptlab yml
[test.yml.txt](https://github.com/user-attachments/files/17833546/test.yml.txt)

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by RuizhiSunMS** [comment]
Hi @libjosep, thx for reporting here. I can repro it. 
Mark this with one ADO #9564200 into our backlog. Will involve our experts to investigate. Please be patient and we will reply here if any update.

**Comment by RuizhiSunMS** [comment]
Hi @libjosep , would you please have a try on this code snippet if just using api worked as expected?
Note that please don't forget to map these functions to html elements.
```
async function run1() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    const range = sheet.getRange("A3:A20");

    // Find the row header that provides the sort criteria.
    // const header = range.find("a3", {});
    // header.load("rowIndex");
    await context.sync();

    range.sort.apply(
      [
        {
          // key: header.rowIndex,
          key: 0,
          ascending: true,
          sortOn: Excel.SortOn.value
        }
      ],
      false /*matchCase*/,
      // true /*hasHeaders*/,
      false,
      Excel.SortOrientation.rows
    );
    await context.sync();
  });
}
async function run1() {
  await Excel.run(async (context) => {
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    const range = sheet.getRange("A3:A20");

    // Find the row header that provides the sort criteria.
    // const header = range.find("a3", {});
    // header.load("rowIndex");
    await context.sync();

    range.sort.apply(
      [
        {
          // key: header.rowIndex,
          key: 0,
          ascending: false,
          sortOn: Excel.SortOn.value
        }
      ],
      false /*matchCase*/,
      // true /*hasHeaders*/,
      false,
      Excel.SortOrientation.rows
    );
    await context.sync();
  });
}
```

**Comment by libjosep** [comment]
Thanks for the update @RuizhiSunMS. I tried the code provided here. The first sort is working fine, but the subsequent sort operations didn't work. Please see the attached scriptlab sample
[SortScriptlab.yaml.txt](https://github.com/user-attachments/files/17981543/SortScriptlab.yaml.txt)

**Comment by RuizhiSunMS** [comment]
@libjosep, then it's different. API snippet works well at my side not matter calling ascending or descending or no matter calling how many times. 
The 'Sort' button on Excel Web does work unexpectedly (your and mine are the same here), I've reached out to Excel Web experts for further investigation.
