### ISSUE TITLE
[Excel] Sheet name tick inconsistency

### ISSUE THREAD

**Issue by misaunde** [OfficeDev/office-js#512]
There is a sheet name tick inconsistency between workbook.getSelectedRange() and worksheets.getItem().

For example, I would expect the code below to work in all scenarios (however it only works for sheet names that are a single word and have no apostrophe's in them - which is confusing and inconsistent in my opinion):
```
  await Excel.run(async (context) => {
    const input = context.workbook.getSelectedRange();
    input.load("address");
    await context.sync();
    
    const sheet = context.workbook.worksheets.getItem(input.address.split("!")[0])
    const range = sheet.getRange("B2:E6");
    range.select();
    await context.sync();
  });
```

However, getSelectedRange returns the following for these scenarios:

Actual Sheet Name| Address returned from getSelectedRange()
------------ | -------------
Sheet1 | "Sheet1!A1:A1"
Two Names | "'Two Names'!A1:A1"
Sheet's With Apostrophe | "'Sheet''s With Apostrophe'!A1:A1"

Now, if that's how excel does sheet names (according to this: https://superuser.com/questions/1156952/reference-excel-sheet-with-apostrophe-in-name) I can get over that. What I don't understand however, is why I can't directly pass the sheet name office.js gives me, into worksheets.getItem(). That feels like a bug to me and has tripped me up a few times. Is there a good reason for this? Can getItem() be fixed to handle the sheet name ticks we get as output from office.js?

## Expected Behavior

getItems() would work with the output from getSelectedRange() -- that it could deal in terms of Excel sheet names.

## Current Behavior

.getItems() works if a sheet name is just a single word and has no apostrophes, but breaks if the sheet name is more than one word or if it contains an apostrophe.

## Steps to Reproduce, or Live Example

Code above

## Context

A common pattern in our add-ins is to have a setup screen where users select the input columns to be used by our tool, along with some other options. Then, when our tool runs, we use those addresses provided by the user for various tasks and often output results/edits/etc to the same sheet of columns they selected. We use getItems() to get a handle to those sheets later in the process and we often trim the first and last ticks ourselves, but the curve ball was when we found out an "'s" (apostrophe s) was breaking things, so I thought I'd submit this case.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: __PC____
* Host [Excel, Word, PowerPoint, etc.]: ____Excel O365__
* Office version number: ___Version 1808___
* Operating System: ____Windows__
* Browser (if using Office Online): ______

**Comment by catchingyu** [comment]
Thanks a lot for reaching us @misaunde . We knew it is not the best experience,  I guess here you probably plan to do some more " file name strings handling stuff" as your previous workaround "trim first and last ticks".

**Comment by Zlatkovsky** [comment]
@catchingyu , I have to agree with @misaunde , it seems like we should be able to handle this case in the API implementation directly.  I'm happy to discuss more offline.

**Comment by catchingyu** [comment]
@Zlatkovsky. Yeah, you are right. It is a good experience for the developers that can use directly the return value from one function and use as an input as another one during their code/logic. It will make the code looks cleaner and more easier to understand. 

One concern from me changing the current output of the existing functions would bring some trouble to the existing logic which is already built on in the market, anyway we can discuss it more offline.

**Comment by catchingyu** [comment]
Bug 3392964 is created to track this issue.

**Comment by lindalu-MSFT** [comment]
According to bug, this has been fixed. Closing issue.
