### ISSUE TITLE
How can I prevent an Outlook add-in from opening in the message reading popup?

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js#5120]
Problem Description
I am developing an Add-In for Microsoft Outlook. I would like the Add-In not to be automatically opened in the message reading popup (when the user opens an email). The goal is to limit the loading of the Add-In to only the main window or specific contexts.

Current Behavior
Currently, the Add-In also automatically loads in the email reading popup, which is not necessary for our use case.

Desired Behavior
The Add-In should not automatically open in the reading popup, but only in the required main contexts (for example, the main Outlook window).

Steps to Reproduce

Open Outlook.
Enable the Add-In.
Double-click an email to open it in the reading popup.
Observe that the Add-In is also loaded in the popup.
Possible Solutions

Use the Add-In manifest settings to specify the contexts in which it should be loaded.
Please properly configure your Add-In commands or components to avoid loading in the popup.

**Comment by mobisw-msft** [comment]
Hey @CodeCube0 , Unfortunately, this capability does not exist on Outlook add-ins today. If you want this behaviour on Outlook, you have to raise a new Feature request.

We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered when we go through our planning process.
