### ISSUE TITLE
NAA Outlook legacy tokens deprecation when will the tooling be available

### ISSUE THREAD

**Issue by JustAnotherEXOAdmin** [OfficeDev/office-js#5121]
When will the tooling be available from Microsoft to allow admins to identify which Add-Ins will be affected by this change.

Microsoft originally said it would be available in October 2024 and then mid-November 2024 as per 

https://learn.microsoft.com/en-ie/office/dev/add-ins/outlook/faq-nested-app-auth-outlook-legacy-tokens#can-i-turn-legacy-tokens-back-on

But this document has not been updated and our organisation needs to know if any of our business critical add-ins will be affected ASAP,

**Comment by ashu66867** [comment]
I am also waiting for the same.

**Comment by Python-venkat** [comment]
Not sure how Microsoft deprecating a feature with out releasing the tool. Even I dont find the poweshell command which will reenable the NAA or which can block the disablement of this feature.

**Comment by Rohitkumarsir** [comment]
This tool supposed to be available in mid of Nov but yet there are no updates at Microsoft FAQ. Waiting for site to be updated.

**Comment by SenMS-CSA** [comment]
> When will the tooling be available from Microsoft to allow admins to identify which Add-Ins will be affected by this change.
> 
> Microsoft originally said it would be available in October 2024 and then mid-November 2024 as per
> 
> https://learn.microsoft.com/en-ie/office/dev/add-ins/outlook/faq-nested-app-auth-outlook-legacy-tokens#can-i-turn-legacy-tokens-back-on
> 
> But this document has not been updated and our organisation needs to know if any of our business critical add-ins will be affected ASAP,

Are you looking for this? It is available now.
Please refer below link
https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/turn-exchange-tokens-on-off

**Comment by davidchesnut** [comment]
Hi @JustAnotherEXOAdmin, we published a blog update earlier this week with updated information about the tooling. See https://devblogs.microsoft.com/microsoft365dev/naa-and-deprecation-of-legacy-tokens/. Unfortunately the tooling to report add-ins that use legacy tokens is still not complete. We published a list of all known Microsoft AppSource add-ins that were using Exchange tokens as of October 2024. You can find more information and instructions on how to use the list to find add-ins on your tenant here: https://github.com/OfficeDev/office-js/tree/release/add-in-ids

Thanks,
David
