### ISSUE TITLE
Outlook: Replies are duplicated / Smart Alerts runtime terminated on Reply send (Web, New Windows) 

### ISSUE THREAD

**Issue by dmitriikashin-outreach** [OfficeDev/office-js#5123]
# Provide required information needed to triage your issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: Outlook Web, Outlook for Windows (New)
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 365
* Operating System: Mac OS, Windows
* Browser (if using Office on the web): Chrome
 
## Expected behavior

**Prerequisite**: user has Outlook Add-in installed which leverages Smart Alerts functionality, and `OnMessageSend` handler in particular.

When user replies to an email using Outlook Web or Outlook for Windows (New) **in the main window**:
- Reply email  **is not sent** until Add-in finished the processing and indicated either success or failure
- In case if processing takes longer than 5 seconds, and user sees the "Add-in is taking longer than expected" popup and decides to click on the "Send anyway" button **only one email is sent**
- Smart Alerts runtime is not cancelled / terminated when native "send button" is clicked => has ability to indicate the result of processing back to Outlook

## Current behavior

**Prerequisite**: user has Outlook Add-in installed which leverages Smart Alerts functionality, and `OnMessageSend` handler in particular.

**Prerequisite**: be part of certain rollout happening on the Web platform, **as not every mailbox has this behavior.**

When user replies to an email using Outlook Web or Outlook for Windows (New) **in the main window**:
- As soon as user hits native "send" button Outlook initiates Add-in processing, but doesn't wait for it to finish
- After few seconds (~3), **"new" email is being sent by Outlook instead of reply**
- After few more seconds (~5 from beginning), the  "Add-in is taking longer than expected" popup appears
- Smart Alerts runtime is **terminated**, so Add-in can't indicate result of processing anymore
- "Add-in is taking longer than expected" popup is visible till use performs any action: either "Send anyway" or "Don't send"; meanwhile popup can change the state to "Add-in timed out" after several minutes
- User click on "Send anyway" (most often scenario)
- **"Reply" type of email is sent**
- Recipient gets **two emails instead of one**

## Steps to reproduce
- Pick mailbox that is part of most recent rollout (~since Nov 5 according to our reports)
- Install any Add-in that leverages Smart Alerts and `OnMessageSend`  in particular
- Go to Outlook Web, or New Outlook for Windows
- Send an email to any recipient which you can use later on for confirmation
- Go to send items, click on "reply" icon (make sure you don't compose in a new dedicated window, as this is a workaround we currently suggest to avoid the issue)
- Compose a reply, hit send button
- Note that in a few seconds **"new" email is sent**
- Note that Add-in you installed is hanging and  "Add-in is taking longer than expected" popup is shown
- Note that Add-in will eventually timeout as in reality there is no processing happening on the background
- Click "Send anyway" button
- **Note that "Reply" type of email was sent**
- Request (or verify yourself) on recipients end that **two emails were sent**

## Link to live example(s)
- [Repro video](https://drive.google.com/file/d/1CGbcHe73soMT62v6RXhTeGt4Aa_gCJoH/view?usp=sharing)
- Recipients end:
![image](https://github.com/user-attachments/assets/3ba0e0a6-201a-4d3f-8bba-730453b883c8)

- [No repro with same scenario](https://drive.google.com/file/d/1tp507LyZB5yCzO7FMssXRyIAQYSrPefZ/view?usp=sharing), but different mailbox used as a sender

# Provide additional details

The issue is reproducible, but not on every mailbox. In our case, our dev tenant (***@4qx0t4.onmicrosoft.com**) doesn't have an issue, while   ***@spectacle.outreach-demo.com** has. 

**Workaround** we suggest to the customers is to compose reply messages in the New Window: in this case Add-in is not hanging and there are no duplicated emails. 

## Context

The issue is reported by 11+ orgs which use [Outreach Add-in.](https://appsource.microsoft.com/en-us/product/office/WA200007033?flightCodes=OutreachAddinBeta)
The issue amount of affected orgs is growing.
The issue has started on ~ Nov 4 (first report). 

The issue has a big impact on productivity. If possible, we'd like to request the rollback of recent changes / stop the rollout that brings the issue. 

## Useful logs

Same reply scenario:

**Comment by rkpathak** [comment]
@dmitriikashin-outreach Please share log files via a private repo and give access to @exextoc. You may revoke access once your issue is answered. Your logs have been deleted for privacy reasons.

**Comment by dmitriikashin-outreach** [comment]
@rkpathak thanks for the notice, we will replicate it via private channel. 

Though the issue is very prominent and it has clear [repro](https://drive.google.com/file/d/1CGbcHe73soMT62v6RXhTeGt4Aa_gCJoH/view?usp=sharing)

It affects more and more customers, and it has incident level urgency.

The background "send" processing introduced recently into Web platform 
does not seem to work well with the Inline replies and Smart Alerts:

- Smart Alerts runtime is cancelled once "Send button" is clicked
- "New" email is sent (which should never happen **as user is replying**) after ~5 seconds of idle
- Duplicate "reply" email is sent when user clicks on "Send anyway"  - and obviously this processing can't be finished as runtime that's supposed indicate processing result back to Outlook is not running.

We also don't see the "background" send processing introduced on certain mailboxes, such as our dev tenant, where add-in keeps working fine. 

On a side note, Outlook Web doesn't seem to be in operational state since this morning (CET) time with 503/500 on every second API call:

![image](https://github.com/user-attachments/assets/1fb59444-82f3-4146-ad62-e23ebd4ae2ff)

**Comment by dmitriikashin-outreach** [comment]
Our latest observations related to the issue is that Outlook tries to process Email / Send it **multiple times** on "Send" button click:

- First time it Invokes the Add-in, finishes the processing, sends the email
- Second time it does **not invoke the Add-in,** but opens "Add-in is working on your request" popup. "Send anyway" click will lead to a duplicated email sent, while "Don't send"  click will leave user with somewhat expected outcome: only one **processed** email is sent. 

This double invocation is visible on the video below.

https://github.com/user-attachments/assets/f8251e04-cba5-406f-9020-4d9d26de24fb

**Comment by ruwi-next** [comment]
I am also able to reproduce this issue with our outlook add-in. It doesn't happen every time but replying to an email sends the email and then shows the spinner message "Add-in is working on your request". It is also affecting customers and we would like to see a fix please.

**Comment by rkpathak** [comment]
Thanks for reporting this issue. We are able to reproduce this issue. We could root cause this issue because of a recent flight. We have reverted the flight. This should fix the issue.

**Comment by dmitriikashin-outreach** [comment]
@rkpathak 

We are seeing recovery on several mailboxes internally. Confirming with the customers. 

Thank you

**Comment by rkpathak** [comment]
@dmitriikashin-outreach Thanks for the update. Keep us posted when you hear from your customers.

**Comment by JuaneloJuanelo** [comment]
Closing this issue as we see positive confirmation of the fix.

**Comment by pavelstudeny** [comment]
@rkpathak the same issue happened temporarily to some users on Monday December 2 again. It is not happening right now to those users, but it brings uncertainty to what degree this is resolved.
