### ISSUE TITLE
Manifest Validation Allows Missing Resource ID, Causing Deployment Failure in Microsoft 365 Admin Center

### ISSUE THREAD

**Issue by gerrillero** [OfficeDev/office-js#5125]
When uploading the application to the Microsoft 365 Admin Center, the step that validates the manifest (as well as the "office-addin-manifest validate" command) considers it correct if you have a resid but have not defined the ID in the resources tag. However, when deploying, an error message appears stating "Failed" in the Microsoft 365 Admin Center.

The error message should provide more information, and the manifest validation should catch this error before installation.

**Comment by Rick-Kirkham** [comment]
This is an issue with the platform, not the documentation, so I'm going to try to move it to the office-js repo.

**Comment by RuizhiSunMS** [comment]
Hi @gerrillero, thx for reporting here. I will reach out to experts in that area and reply here if any update.
In addition, would you please add some more about your question? For example, a list of detailed steps, some screenshots of steps you think are confusing or inappropriate, what kind of error information you want and others you want to discuss. These would be helpful for us.
Btw, may I know what application your addin is for?
