### ISSUE TITLE
DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.

### ISSUE THREAD

**Issue by jozefizso** [OfficeDev/office-js#5126]
## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: -
* Operating System: macOS 15
* Browser (if using Office on the web): Safari
 
## Expected behavior

The template for Office addin should work without deprecation warnings on dependencies.

## Current behavior

Running new Office addin created by `yo office` wizard will result in this error:

```
(node:59732) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

## Steps to reproduce

1. Follow the guide at https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/outlook-quickstart-yo
2. Run project `npm start`
3. Observe deprecation warnings  in the console.

## Useful logs

```
npm ls punycode
office-addin-taskpane-sso@0.0.0 /Users/izso/Developer/tmp/outlook-react-sentry
├─┬ eslint-plugin-office-addins@3.0.3
│ └─┬ @typescript-eslint/rule-tester@7.18.0
│   └─┬ ajv@6.12.6
│     └─┬ uri-js@4.4.1
│       └── punycode@2.3.1
├─┬ office-addin-debugging@5.1.6
│ └─┬ office-addin-dev-settings@2.3.6
│   └─┬ whatwg-url@14.0.0
│     └─┬ tr46@5.0.0
│       └── punycode@2.3.1 deduped
└─┬ url@0.11.4
  └── punycode@1.4.1
```

**Comment by rkpathak** [comment]
@jozefizso This repo is for handling office-js issues only. For yo generator, can you post the question in https://github.com/OfficeDev/generator-office/issues
