### ISSUE TITLE
After New Outlook recent updates, Outlook Add-ins behaves unexpectedly showing broken UI and Confusing Dialog

### ISSUE THREAD

**Issue by allfii** [OfficeDev/office-js#5127]
# Provide required information needed to triage your issue
After New Outlook recent updates, Outlook Add-ins behaves unexpectedly showing broken UI and Confusing Dialog.

## Your Environment
* Platform Windows
* Host New Outlook
* Office version number: Microsoft Outlook Version 1.2024.903.200 (Production). Client Version is 20241115003.23.
* Operating System: Windows
* Browser (if using Office on the web): WebView2 Version is 131.0.2903.63.
 
## Expected behavior
* UI is not broken
* There is no dialog prompting to choose between "Wait" and "Save as draft"
* If clicking "Wait", it will show a new pop up window

## Current behavior
* UI is broken
* There is dialog prompting to choose between "Wait" and "Save as draft"
* It should not show a new pop up window

## Steps to reproduce
1. Compose new email in Reading Pane
2. Fill up subject, to, and body
3. Open Add-ins
4. Click Send

# Provide additional details
I have developed Outlook Add-ins and released it in production. Everything is working fine as expected. However in the past few days, there are unexpected behaviors, after clicking Send button, Add-ins start processing, then Outlook UI is broken as shown below.
![Screenshot 1](https://github.com/user-attachments/assets/71fca406-c9a5-4912-86a3-fe21bdcc8c06)

Additionally, when Add-ins is taking longer time than expected, it will show warning dialog with the broken UI as shown below.
![Screenshot 2](https://github.com/user-attachments/assets/76bdbacd-a4d3-488f-bc39-bff9d53809b4)

Moreover, if Add-ins is trying to close the email, it will show unexpected prompt dialog as shown below.
![Screenshot 4](https://github.com/user-attachments/assets/db830167-146d-4782-b7df-b927eaee40dd)

I found in the documentation that this behavior can happen in Classic Outlook Desktop when mail is closed during on-send process. However, in the current testing I am using New Outlook application (not Classic Outlook Desktop). Does anyone know how to address this issue?

**Comment by rkpathak** [comment]
There were some changes around this area. Could you please refresh your OWA session and repro. In case the problem persists, collect and share logs by following instruction [Collecting log files for Outlook Add‐ins issues](https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues)

**Comment by allfii** [comment]
> There were some changes around this area. Could you please refresh your OWA session and repro. In case the problem persists, collect and share logs by following instruction [Collecting log files for Outlook Add‐ins issues](https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues)

@rkpathak could you please elaborate more on "There were some changes around this area", so it can be more transparent? Thank you

**Comment by rkpathak** [comment]
We have reverted a flight that was affecting item switch during send operation. Check in a new session if the problem is still seen, collect and share network traces following the instructions https://github.com/OfficeDev/office-js/wiki/Collecting-log-files-for-Outlook-Add%E2%80%90ins-issues
