### ISSUE TITLE
Send email Pop-up will close and go to Drafts while if user composes new email while Add-in is running

### ISSUE THREAD

**Issue by nivgoldsteiniron** [OfficeDev/office-js#5128]
We have OnSendAddinsEnabled being true and an Add-in that runs on the onSend hook which shows a dialog. Sometimes if internet connection is slow, the user will only see the sending email window while the dialog page loads.

This sometimes causes the user to go back to the main window, missing the dialog entirely.

Is it possible to maximize the window so the customer will be less likely to go back to the main window and miss the dialog when it shows up?

**Comment by rkpathak** [comment]
Few questions:
Which platform are you seeing this behaviour? 
Are you using ItemSend? If yes, can you try using smart alerts for your use case, with smart alerts you will get item switch behaviour that will notify using if they are moving away from the message.
