### ISSUE TITLE
Some APIs do not return the correct headers, respond with 404 or 503, and are inaccessible due to CORS restrictions

### ISSUE THREAD

**Issue by CodeCube0** [OfficeDev/office-js#5129]
While using the Microsoft Office 365 APIs to retrieve events, we encountered issues where certain requests do not return the correct headers and respond with unexpected HTTP status errors, such as 404 or 503. Additionally, some requests are blocked by CORS policies, as the Access-Control-Allow-Origin header is not present in the response.

Details:

Endpoint called: https://outlook.office365.com/api/v2.0/me/events?filter=singleValueExtendedProperties...
HTTP Method: GET
Response received:
Status Code: 503 Service Unavailable
Content-Type: text/plain
Content-Length: 0
Proxy message: The connection with the server was terminated abnormally
CORS Error:
"No 'Access-Control-Allow-Origin' header is present on the requested resource"
Request Origin: https://collaudo.micrappg.lan
Observed Issues:

Some requests receive a 503 status code without any useful information in the headers.
Some endpoints respond with a 404 status code, although the endpoint should exist and return data.
The absence of the Access-Control-Allow-Origin header prevents access to resources from different origins, causing requests to be blocked for security reasons.
Steps to Reproduce:

Send a GET request to the specified endpoint to retrieve events.
Check the received response, response status, and the presence of the Access-Control-Allow-Origin header.
Expected Result: The APIs should return a consistent response with appropriate headers and provide data or a descriptive error if the endpoint is unavailable. Additionally, they should include the Access-Control-Allow-Origin header to allow legitimate cross-origin requests.

Actual Result: Requests respond with 503 or 404 status codes without sufficient explanation, and they are blocked due to the missing CORS header.

This updated issue description should cover the CORS blocking issue along with the other errors.

**Comment by rkpathak** [comment]
Are you using Office js API? If yes, please share the API detail, platform and error details that you are getting.
