### ISSUE TITLE
Office JS API for checking if email is encrypted or not

### ISSUE THREAD

**Issue by pza-dev-brcm** [OfficeDev/office-js#5133]
We are using ItemSend event in outlook add-in;  In which we monitor email contents like  - subject, body, recipients, attachments and based on policies defined we decide whether to allow or block the email.

As per our requirement, we want to know if the email is encrypted. 
Also it will be helpful if we get more information like if the email is encrypted then with which flag it is encrypted like (Encrypt Only / Do Not Forward / SMIME) ?

Is there any API currently available for this in Office JS?

Note:
Currently add-in get's invoked if email is encrypted with (Encrypt Only / Do Not Forward).
We want to somehow know in the add-in that email is encrypted.

Environment
Platform [PC desktop, Mac, iOS, Office on the web]: PC desktop, On the web
Host [Excel, Word, PowerPoint, etc.]: New outlook
Office version number: You have Microsoft Outlook Version 1.2024.708.100 (Production). Client Version is 20240712002.10
webview2 version is 126.0.2592.113
Operating System: win 11
Browser (if using Office on the web): Chrome

**Comment by rkpathak** [comment]
At present, the feature to retrieve the email's encryption status is not available as part of Office.js API set. You can find all the supported APIs using link https://learn.microsoft.com/en-us/javascript/api/overview?view=outlook-js-1.14
We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process

**Comment by ricardoleonhart** [comment]
Alternatively, you can [get the mail headers](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/internet-headers) and check the `content-type` header for values relating to s/mime or encryption. You may refer to this link

https://learn.microsoft.com/en-us/openspecs/exchange_server_protocols/ms-oxosmime/e6f63b02-c679-4752-9302-9c4641749e95
