### ISSUE TITLE
createDocument from a base64 string doesnt work

### ISSUE THREAD

**Issue by azoulaynoam** [OfficeDev/office-js#5150]
Browser: Edge
Office API on React JS
Office 2024
Im trying to open a base64 file as a new document like so:
```
const newDoc = context.application.createDocument(wordDocumentBase64);
context.load(newDoc);
await context.sync();
newDoc.open();
```
but it doesnt work, I get a general error from the office api
but with the same base64 I can do that:
```
const body = context.document.body;
body.clear();
body.insertFileFromBase64(
  wordDocumentBase64,
  Word.InsertLocation.start
);
await context.sync();
```
and it works,
Anyone knows?

**Comment by guoms1** [comment]
Thank you for sharing your code and feedback. Based on the code you provided, I added functionality for Base64 encoding, and after testing, I found that the code works as expected. I’ll provide the updated example for your reference. Below are the steps to use the test code:

1. Run the provided test code: Execute the code in the appropriate environment where the add-in is set up.
2. File selection dialog: A file selection dialog will appear. Use it to select a valid .docx file from your system.
3. Base64 encoding: The example code will use the readFileAsBase64 function to convert the selected .docx file into a Base64-encoded string.
4. Opening the document: The code will then use the Base64-encoded string with your provided implementation to open the document in a new Word window.
5. Validation: You should see the selected document successfully opened in the new window, demonstrating that the API works as expected.

Please let me know if you encounter any issues or need further assistance!

#### Sample Code
```typescript
// this method could load a normal .docx.
export async function createNewDocument() {
  try {
    // Create file selection dialog
    const input = document.createElement("input");
    input.type = "file";
    input.accept = ".docx"; // Restrict file type to .docx

    input.onchange = async (event: Event) => {
      const file = (event.target as HTMLInputElement).files?.[0];
      if (!file) {
        console.log("No file selected!");
        return;
      }

      try {
        // Read file as Base64
        const base64File = await readFileAsBase64(file);

        // Initialize new Word document using Base64
        await Word.run(async (context) => {
          const newDoc = context.application.createDocument(base64File);
          context.load(newDoc);
          await context.sync();
          newDoc.open(); // Open new document
          console.log("New document created successfully!");
        });
      } catch (error) {
        console.error("Error processing file:", error);
      }
    };

    // Simulate file selection dialog click
    input.click();
  } catch (error) {
    console.log("Error:", error);
  }
}

// helper function: read file as Base64
function readFileAsBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve((reader.result as string).split(",")[1]); // remove base64 data header
    reader.onerror = (error) => reject(error);
    reader.readAsDataURL(file); // read file as Data URL so the .docx will be encoded as a base64 string
  });
}
