### ISSUE TITLE
New Outlook: Shared mailbox does not reflect update when messages are moved from one folder to another.

### ISSUE THREAD

**Issue by ArjunSureshKumar92** [OfficeDev/office-js#5153]
We have an outlook addin developed using office js. While testing out the "New Outlook" we realized, the shared mailboxes are all "web cached". 

Our application depends on outlook folders correctly updating the UI when messages are moved in and out. I have confirmed with the Outlook team that there is no way to turn off this caching. Due to this, our application is not working correctly anymore.

So my feature request is for office js to only load a message info if that message actually exists in the folder. In other words, the current folder info of the message has to be available through office js.

Additional, i did notice there is a sync option. Under the outlook ribbon -> View -> Sync. Now clicking on this, does update all the folders correctly. So if there any way office js apis' can access this option that will work as well for us.

Hoping for a resolution or workaround. Thanks in advance.

**Comment by galiling** [comment]
My team is having the same issue.

**Comment by huaji914** [comment]
I just got the same problem

**Comment by SamLpt** [comment]
My team is also having trouble to find a workaround to this issue as well for a little bit now. @exextoc let us know any updates to this.

**Comment by rajjha-msft** [comment]
Currently the feature of getting current folder info of the message through office js, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by ArjunSureshKumar92** [comment]
> Currently the feature of getting current folder info of the message through office js, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

@rajjha-msft 
I will make a case in the community page. Thanks.

_Additional, i did notice there is a sync option. Under the outlook ribbon -> View -> Sync. Now clicking on this, does update all the folders correctly. So if there any way office js apis' can access this option that will work as well for us._

I assume the above option is also unavailable through office-js. Can you please confirm this is the case?.

**Comment by rajjha-msft** [comment]
Hey @ArjunSureshKumar92 

Right now we do not support this feature via office-js
