### ISSUE TITLE
custom tab not working with outlook manifest

### ISSUE THREAD

**Issue by ishanig11** [OfficeDev/office-js#5157]
[manifest.zip](https://github.com/user-attachments/files/18009886/manifest.zip)
Please refer attached manifest file. Its not working after replacing default tab with customtab.

With npm validate, manifest file is valid.
Can you tell me what is missing?

**Comment by ishanig11** [comment]
@exextoc : did you get chance to check what is wrong with manifest file?

**Comment by JamesDerrickHH** [comment]
Hi @ishanig11  just in an attempt to help, and comparing to my own manifest which uses a custom tab, you don't seem to have a shortstring resource with an id of customTabLabel1. So the label doesn't have a value currently.
So something like this in your resources, inside `<bt:ShortStrings>`
`<bt:String id="customTabLabel1" DefaultValue="My Custom Tab" />`
Just a guess that that'd cause it not to show

**Comment by ishanig11** [comment]
I added string. SO manifest got imported. But I dont see custom tab on Ribbon.
![image](https://github.com/user-attachments/assets/636e7858-b6e6-45ca-aa1c-33d70fc562ed)

**Comment by samantharamon** [comment]
Hi @ishanig11. Thanks for reaching out. I see that you're experiencing issues when running the add-in in Outlook on the web. To help us troubleshoot this further, does the custom tab appear if you run the add-in in classic Outlook on Windows?

**Comment by rajjha-msft** [comment]
Can you please specify which is the impacted client (OWA / New Outlook for Windows / Classic Outlook for Windows) ?

**Comment by ishanig11** [comment]
I am checking this on online office 365.

I dont see option to upload add-in on Desktop app
![image](https://github.com/user-attachments/assets/f55956ee-88bb-42f7-8559-6690d912f0af)

**Comment by Swathy-Mothilal** [comment]
@ishanig11 We are still unable to repro the issue at our end. Could you please host the add-in to a private repo and give access to @exextoc?

And kindly validate the manifest before uploading it. For reference, https://learn.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest. For sideloading the add-ins on Outlook Desktop, kindly refer to https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/sideload-outlook-add-ins-for-testing.

**Comment by ishanig11** [comment]
@Swathy-Mothilal : I am facing issue with manifest file only. No further things from addin. I can't see custom tab loaded.

can you please share manifest which you are using along with screenshot of loaded custom tab?

**Comment by JamesDerrickHH** [comment]
I wasn't aware that custom tabs were a thing in the web version or new versions of Outlook, I have only had the custom tab show up in the older desktop version, but I thought that was expected behaviour.

**Comment by ishanig11** [comment]
does this mean custom tab not supported in web version?

**Comment by Swathy-Mothilal** [comment]
@ishanig11 Currently, the custom tab feature is not supported in Outlook on the Web or the New Outlook for Windows. We acknowledge there's a gap in the documentation, and we're working to address it. Could you share the use case you're trying to achieve?

**Comment by ishanig11** [comment]
We want to add one custom tab related to our app functionality.
