### ISSUE TITLE
How to test compatibility issues with older builds

### ISSUE THREAD

**Issue by lsmith77** [OfficeDev/office-js#5158]
## Post how-to questions about your code on Microsoft Q&A

I have a customer that has issues with our Add-in that is using an older build 2308. How can I best run such an old build locally for debugging?

**Comment by RuizhiSunMS** [comment]
may I ask that why your customer is unwilling to update?

**Comment by lsmith77** [comment]
They are on the semi-annual enterprise plan
https://learn.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date

**Comment by RuizhiSunMS** [comment]
https://support.microsoft.com/en-us/topic/how-to-revert-to-an-earlier-version-of-office-2bd5c457-a917-d57e-35a1-f709e3dda841
I got such guide doc, would it be helpful for your case?

**Comment by lsmith77** [comment]
Wow, quite complicated and requires Windows.
Allright, will dig out a windows laptop for this I guess.

**Comment by RuizhiSunMS** [comment]
@lsmith77 looking forward to your feedback.

**Comment by lsmith77** [comment]
I followed the instructions, however at Step 2.7 (ie. updating) I am getting an error. here is a screenshot of the error and the config.xml file I am using.

Note I am getting the same error if I use a more recent version. Only if I revert back to the most recent version, I am able to complete the update though it then just says that the latest version is already installed.

![Capture](https://github.com/user-attachments/assets/7f363884-a348-44c2-93f6-1978b88a5792)

**Comment by RuizhiSunMS** [comment]
Hi @lsmith77, sorry that I didn't notice you are using o365, which is not included in the previous article.
How about these two:
https://answers.microsoft.com/en-us/msoffice/forum/all/revert-to-a-previous-version-of-office-365/79138c95-80b4-48fb-bef7-08619af3593e
https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-downgrade-ms-office-365/eab319fb-1b6e-4007-a223-8f1881db265d

**Comment by lsmith77** [comment]
OK thank you. I managed to downgrade using https://answers.microsoft.com/en-us/msoffice/forum/all/revert-to-a-previous-version-of-office-365/79138c95-80b4-48fb-bef7-08619af3593e

This is really painful and time consuming. Would be great for developers to improve this.
