### ISSUE TITLE
[Document.addStyle]: add a List style does not return Word.ListLevelCollection items in Word.ListTemplate (style.listTemplate.listLevels)

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#5159]
* Platform [PC desktop, Mac, iOS, Office on the web]: PC
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2410 ( Build 18129.20158) Current Channel
* Operating System: Windows
 
## Expected behavior
It should return default `listLevels` items.

## Current behavior
- Returns an empty object when creating a new List style.
- Can return `listLevels` items for existing style.
## Steps to reproduce

1. Create a new list style using the API `Document.addStyle('New List Style', 'List')`  
   (https://learn.microsoft.com/en-us/javascript/api/word/word.document?view=word-js-preview#word-word-document-addstyle-member(1)).
2. Log the `listLevels` items (Script Lab: https://learn.microsoft.com/en-us/javascript/api/word/word.listlevel?view=word-js-preview).

## Useful logs
In Current Channel (Preview) 2411, I can see the `listLevels` items:
![image](https://github.com/user-attachments/assets/cce14132-ef48-4053-9b62-054f366ab526)

In Current Channel 2410, it returns an empty object:
![image](https://github.com/user-attachments/assets/d8394453-6e03-49c5-bc9f-d0f342e83fff)

## Context:
We need to retrieve the `listLevels` items to update the style. Currently, the listLevels are read-only properties. Is there any way to set the default items for the `listTemplate`?
Eg: style.

```
 style.listTemplate.set({
     listLevels: updatedListLevels,
 })

 interface ListTemplateUpdateData {
    // can only set this property
     outlineNumbered?: boolean;
 }
```

**Comment by RuizhiSunMS** [comment]
Hi @jasonhieu1905, thx for reaching out here.
May I ask that, you want a behavior on 2410 to be like what it is on 2411? I tried with my 2411 cc, the behaviour is just like what you expects.

**Comment by jasonhieu1905** [comment]
@RuizhiSunMS : Yes, I want it to return at least the default listLevels items when creating a new style.
The idea is that I have a pre-designed List style selected, and now I want to copy all its styles to a newly created List style. However, I am unable to do so because the listLevels are empty.

**Comment by RuizhiSunMS** [comment]
@jasonhieu1905, then may I know what blocks you from using 2411 if you confirmed it works on 2411?

**Comment by jasonhieu1905** [comment]
@RuizhiSunMS : It does not block me on version 2411. Most of our customers are using older builds. Hope this helps.

**Comment by RuizhiSunMS** [comment]
Thx @jasonhieu1905, I got it. I consulted our experts. Backporting to 2410 has been done some time ago. If everything goes well, users using 2410 would get this in next update. Please also share with your customers pay attention to the update.
