### ISSUE TITLE
Word addin multiple page

### ISSUE THREAD

**Issue by Hydro8** [OfficeDev/office-js#5165]
Hi

I searched on documentation, ask on Q&A or stackoverflow but I did'nt find a answer so I try here.

Basically, I want to have multiple page on my extension. So I created a test.html on taskpane folder and on taskpane.html I added : 

`<a href="test.html">Link</a>`

When I debug the extension and click on the link, I have this message : 

![63341](https://github.com/user-attachments/assets/c9c7ac49-66a9-49f6-a99c-6519c3e1b597)

The only way I have found to have a working link is to move test.html to "assets" folder and use : 

`<a href="../../assets/test.html">Link</a>`

From there, I can link to another html file that is in assets folder but not elsewhere or in subfolder.

Is this normal ? All pages we want to create must be in "assets" folder directly ?

Thanks for your help.

**Comment by guoms1** [comment]
This behavior is not specific to Office Add-ins; it’s a general aspect of how web applications handle static resources. In many templates and setups, a specific folder (e.g. "assets") is configured as the default location for static files. When your add-in or web application is loaded, the browser context and project configuration may restrict or interpret relative paths in a way that only works smoothly if resources are placed in the designated folder.

To address this, you can:  
1. Place additional pages in the "assets" folder so they’re directly accessible.  
2. Reconfigure your build or deployment setup—just as you would with any web project—to include other directories as valid static resource paths.  
3. Host the files externally and reference them using absolute URLs.

**Comment by Hydro8** [comment]
Thank a lot. 

Indeed I misunderstood how it works. 
Now I upload my site to a server and indicate it on the manifest. It works great. 

Thanks again.
