### ISSUE TITLE
An error occurs with the `internetHeaders` API.

### ISSUE THREAD

**Issue by mailchecktool-admin** [OfficeDev/office-js#5168]
I am developing an add-in using the `ItemSend` event.  
This add-in displays a dialog via the `displayDialogAsync` API, where users can perform a self-check of their email.  

Now, I am tasked with adding new functionality to this add-in.  
In line with this, I would like to ask about the specifications of the `internetHeaders` API.  

### **What I want to achieve**
Since this add-in does not function on smartphones or tablets, I am considering building an email-checking mechanism using an SMTP server instead of the add-in.  
By utilizing the Exchange Admin Center's send connectors and transport rules, I plan to modify the mail flow, temporarily hold emails at the SMTP server, and perform the self-check there.  

However, if all emails are routed through this SMTP server, users will end up performing self-checks twice, which would be too burdensome.  
To address this, I want to add a flag to the header information of emails that have already been self-checked by the add-in.  
Using a transport rule in the Exchange Admin Center, emails with this flag would be directly delivered to the recipient's email server.  
(If the flag is absent, the email would be routed to the SMTP server specified by the send connector.)  

The `internetHeaders` API provided by Office Add-ins allows the addition of header information, and I would like to incorporate this functionality.  

### **What I need advice on**
When I execute `internetHeaders.getAsync()`, an error occurs.  

The console error suggests that the type of argument passed to the API is incorrect, but I have confirmed that the arguments are set correctly.  
It seems there is another issue, but I have not been able to determine the cause through my investigation.  

Could you help identify what is wrong with this program?  
I can provide a sample add-in for your reference.  

■Steps to reproduce
1. Access the following URL.
https://drive.google.com/file/d/1N_xCpTipKQMOeRIMAJyVzk4Sqt1h4rKI/view?usp=sharing
2. Download "sample.zip" and place it in your desired location.
3. Launch the command prompt and navigate to the corresponding directory.
4. Run "npm install".
5. Run "npm run dev-server".
6. Upload "manifest.xml" in Outlook on the web to install the add-in. (The XML file is stored in sample.zip)
7. Compose an email.
8. Click the "Send" button.

**Comment by mailchecktool-admin** [comment]
@samantharamon 
Are you looking into this ticket?  
Could you please update me on the investigation status?

**Comment by samantharamon** [comment]
Hi @mailchecktool-admin,

I've assigned this issue to @exextoc for further investigation.

**Comment by mailchecktool-admin** [comment]
@exextoc @samantharamon 
It has been over a week since I inquired. Could you please update me on the status?

**Comment by Oleg-O** [comment]
But it appears that in `IndexComponent.vue`, you're passing a string in the 1st parameter, whereas [the API expects an array](https://learn.microsoft.com/en-us/javascript/api/outlook/office.internetheaders?view=outlook-js-preview#outlook-office-internetheaders-getasync-member(2)) - and the error you are getting seems appropriate?

`Office.context.mailbox.item.internetHeaders.getAsync(headerName, function(getResult) {`

Let me know if passing an array type instead helps address this issue for you? If it doesn't, can you please share the Outlook version that's failing?

**Comment by mailchecktool-admin** [comment]
@Oleg-O 
As per your advice, I was able to get it working correctly by passing an array-type parameter as the first argument to the getAsync method. Thank you so much! I’ll go ahead and close this ticket!
