### ISSUE TITLE
PKCE + Authorization Code Challenge should be prefered over implicit

### ISSUE THREAD

**Issue by schmitch** [OfficeDev/office-js#517]
currently the docs at https://docs.microsoft.com/en-us/office/dev/add-ins/develop/auth-external-add-ins encourages to use implicit flow.
however as of today it's probably better to use PKCE+authorization code, however office-js does not support PKCE (neither plain nor S256).

office-js should implement PKCE and probably encourage people to use it over implicit flows.
also the token exchange is probably broken: https://github.com/OfficeDev/office-js-helpers/blob/master/src/authentication/authenticator.ts#L180
normally a Content-Type header of type json is incorrect for some oauth servers.

**Comment by lindalu-MSFT** [comment]
If you're still interested in adding this feature, please go to our new [Ideas forum](https://aka.ms/m365dev-suggestions) and click **Submit an Idea**. If there's enough interest (votes), we will follow up with you there and add it to our feature request backlog. Thanks, lindalu
