### ISSUE TITLE
Outlook Add-In Dark Mode Icons

### ISSUE THREAD

**Issue by JamesDerrickHH** [OfficeDev/office-js#5170]
Is there a way of defining dark mode icons in the manifest?
I currently have 4 button controls in a custom tab, and the icons look decent in light mode
But they are not very visible when outlook is running in dark mode
Currently
Light mode
![image](https://github.com/user-attachments/assets/f42ae6d7-3df1-44bd-83ce-eeeff39d1766)
Dark mode
![image](https://github.com/user-attachments/assets/5f1ff8e3-d976-4626-855f-42e3c5191cb9)

**Comment by rajjha-msft** [comment]
Hey @JamesDerrickHH 

Currently the feature of defining dark mode icons in the manifest, you requested, is not a part of the product. We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.

**Comment by JamesDerrickHH** [comment]
@rajjha-msft thanks for the speedy reply
I have gone ahead an upvoted this pre-existing request, which is basically asking for the same thing
https://techcommunity.microsoft.com/idea/microsoft365developerplatform/office-add-in-manifest-overrides-for-dark-mode/2884091

**Comment by rajjha-msft** [comment]
I'll go ahead and close the issue.
