### ISSUE TITLE
Outlook Add In usage version web in a shared mailbox

### ISSUE THREAD

**Issue by Mabelinaa** [OfficeDev/office-js#5171]
I,ve developed a custom addin and published as a static website in Azure.

The addin has a button to move the email wich is read through a Http request to Power Automate.

The addin works perfectly in a shared mailbox. The point is that when I use the custom addin in Outlook web, the email keeps in the view until I refresh the window. Its like, since I have the addin opened over the mail wich I want to move, does not let the web to show the inbox updated. 

The issue is no happening in desktop version, if I move an email with the addin the mail dissapear automatically. 

Is there any way to show the changes in real time in Outlook web?

Thanks in advance

**Comment by samantharamon** [comment]
Hi @Mabelinaa. Thanks for submitting this issue. Please note that this repo is for issues and requests relating to Office Add-ins documentation. I'll go ahead and move this to the office-js repo so that the appropriate team can assist you.

**Comment by rajjha-msft** [comment]
Hey @Mabelinaa 

- Can you share a sample add-in which we can use to repro the issue ?

**Comment by Mabelinaa** [comment]
Good morning, @rajjha-msft

Thank you for your response.

The gif bellow shows the issue with the add-in.

![2024-12-1210-01-43-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/bace077e-1f21-4994-8ae8-98ceb7051f1f)

When using the "Move" action in the add-in, the email remains visible in the inbox, but only in the web view. The email is, in fact, successfully moved to the destination folder. However, the inbox view does not update automatically. If the window is refreshed, the email no longer appears in the inbox view as expected.

What we need is for the view to refresh automatically once the email is successfully moved.

Thanks in advance for your help.

Best regards,

Mabel

**Comment by Swathy-Mothilal** [comment]
@Mabelinaa We are unable to reproduce the issue on our end. Could you kindly provide a code snippet showing how you are moving the email from one folder to another?
