### ISSUE TITLE
 paragraph.insertAnnotations     word

### ISSUE THREAD

**Issue by TylerHuo** [OfficeDev/office-js#5179]
windows11    Office   home   2021

error when using Script Lab to execute paragraph.insertAnnotations

error:
n {name: "RichApi.Error", code: "GeneralException", traceMessages: Array[0], innerError: null, debugInfo: Object…}
name: "RichApi.Error"
code: "GeneralException"
traceMessages: Array[0]
innerError: null
debugInfo: Object
code: "GeneralException"
message: "GeneralException"
toString: function toString()
errorLocation: "Paragraph.insertAnnotations"
statement: "first.insertAnnotations(...);"
surroundingStatements: Array[9]
0: "..."
1: "// Instantiate {selection}"
2: "var paragraphs = selection.paragraphs;"
3: "// Instantiate {paragraphs}"
4: "var first = paragraphs.getFirst();"
5: "// Instantiate {first}"
6: "// >>>>>"
7: "first.insertAnnotations(...);"
8: "// <<<<<"
fullStatements: Array[1]
httpStatusCode: 500
data: undefined

**Comment by RuizhiSunMS** [comment]
Hi @TylerHuo, thx for reaching out here.
Would you please share more information about this? These would be helpful for us to investigate. For example:
1. your office version number
2. full code snippet and document file

**Comment by TylerHuo** [comment]
@RuizhiSunMS  

### thanks

### version : ® Microsoft Word 2021MSO (version 2410 Build 16.0.18129.20158) 64-bit
```javascript
await Word.run(async (context) => {
    const paragraph: Word.Paragraph = context.document.getSelection().paragraphs.getFirst();
    const options: Word.CritiquePopupOptions = {
      brandingTextResourceId: "PG.TabLabel",
      subtitleResourceId: "PG.HelpCommand.TipTitle",
      titleResourceId: "PG.HelpCommand.Label",
      suggestions: ["suggestion 1", "suggestion 2", "suggestion 3"]
    };
    const critique1: Word.Critique = {
      colorScheme: Word.CritiqueColorScheme.red,
      start: 1,
      length: 3,
      popupOptions: options
    };
    const critique2: Word.Critique = {
      colorScheme: Word.CritiqueColorScheme.green,
      start: 6,
      length: 1,
      popupOptions: options
    };
    const critique3: Word.Critique = {
      colorScheme: Word.CritiqueColorScheme.blue,
      start: 10,
      length: 3,
      popupOptions: options
    };
    const critique4: Word.Critique = {
      colorScheme: Word.CritiqueColorScheme.lavender,
      start: 14,
      length: 3,
      popupOptions: options
    };
    const critique5: Word.Critique = {
      colorScheme: Word.CritiqueColorScheme.berry,
      start: 18,
      length: 10,
      popupOptions: options
    };
    const annotationSet: Word.AnnotationSet = {
      critiques: [critique1, critique2, critique3, critique4, critique5]
    };

    const annotationIds = paragraph.insertAnnotations(annotationSet);

    await context.sync();

    console.log("Annotations inserted:", annotationIds.value);
  });
```

**Comment by TylerHuo** [comment]
### The content of the document is just a few simple words, which is an example of Script Lab

**Comment by RuizhiSunMS** [comment]
Sorry that I just recognized you are using our example code. I tried on two device, one is 2303 which can repro while the other is 2412 which doesn't repro. Suppose there could be some delay in backporting. I will confirm with our experts.
Here are two thing I want to make sure with you:
1. I think you are using o365 rather than 2021. 2021 usually appears like LTSC2021. Your version number looks like cc channel of O365.
2. have you ever tried with word web?

**Comment by TylerHuo** [comment]
### Hi @RuizhiSunMS :
   I updated Office Word and the current version is 2411. The problem remains! My office is home and student edition.
 Haven't tried Word Web

**Comment by RuizhiSunMS** [comment]
Hi @TylerHuo, thx for the update. I'm reaching out to the expert. It would cost some time.

**Comment by RuizhiSunMS** [comment]
Hi @TylerHuo, our experts completed the investigation and gave me the explanation, here I shall share it with you.
For now, this case is by-design. This api is part of one functionality which requires subscription as necessary. This is a known issue.    
#4953 is the last one talking about this. Some teams are discussing it but nothing made now. Here I suggest you to submit request on https://techcommunity.microsoft.com/category/microsoft365/ideas/microsoft365developerplatform. I suppose they would accelerate if your request got high votes.
