### ISSUE TITLE
Calling window.focus() causes Excel and the taskpane to lose focus

### ISSUE THREAD

**Issue by slowkoala** [OfficeDev/office-js#518]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

In Office 365 Excel, if you call `window.focus()` from the taskpane, both Excel and the taskpane will lose focus.  The Excel title bar dims and the current cell highlight goes away.  I'm using a library that calls `window.focus()` when you click into a box for user input, but since focus is lost, you can't type.

## Expected Behavior
Excel and the taskpane should maintain focus so you can type.

## Current Behavior
Excel and the taskpane lose focus.  Keystrokes are not recognized when this happens.

## Steps to Reproduce, or Live Example
Here's a Script Lab gist - https://gist.github.com/slowkoala/f8ee12e35e3dfd3837c50a55e73b8d8c

It's simple to reproduce by having this in your html and then trying to click into it and type:
`<input onfocus="window.focus()"></input>`

If you put this in a html document and load it in a regular browser, you can click on it and type as expected.

## Context
We're using the CodeMirror library which calls this at times internally.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Office 365 version 1906
* Operating System: Windows 10
* Browser (if using Office Online): ______

## Useful logs

**Comment by catchingyu** [comment]
Thanks slowkoala for reaching us. 

Can you share with me the screenshot of you Office 365 Excel Version? I am seeking the build version if possible.

**Comment by fds-ssg** [comment]
I can repro this on the following version of Excel for Windows:
Version 1906 (Build 11702.20000 Click-to-Run) 
Office Insider

**Comment by catchingyu** [comment]
Is it possible for you to try it on the build version later than Version 1906 (Build 11713.20000 Click-to-Run) sometime later?
I cannot repro it with that build. (And I can repro it with an old Version 1904).

Please do not hesitate to contact with us if you still encounter problems.

**Comment by fds-ssg** [comment]
@catchingyu My Excel version has been updated to Version 1906 (Build 11708.20006 Click-to-Run).  When I choose Update Now, it tells me I'm on the latest version, so I'm unable to update to a newer one.  The problem still occurs for me on this version.

**Comment by catchingyu** [comment]
Thanks a lot. @slowkoala. I am in the internal release version which is ahead of you. New version will come out to the public soon. Let's see whether you can still reproduce it when you get the version (later than 1906 (Build 11713.20000) some time later.

**Comment by catchingyu** [comment]
will reopen it when customer repro it on the latest version

**Comment by fds-ssg** [comment]
Still occurs in Version 1906 (Build 11715.20002)

**Comment by kbrandl** [comment]
@catchingyu FYI, reopening this issue since the customer's been able to repo on a sufficiently recent version.

**Comment by slowkoala** [comment]
@catchingyu sorry, I was out on vacation last week.  I just upgraded to the latest version (Version 1906 (Build 11715.20002)) and I still see the problem.  However, I'm not on the latest versions of Windows 10, so the taskpane is using IE11.  Are you testing with a taskpane using IE11 or Edge?

**Comment by catchingyu** [comment]
I am on the windows 10 enterprise version. Do you have a chance to test on the latest version of windows 10?

**Comment by catchingyu** [comment]
Also create a Bug 3392711 to track this issue

**Comment by catchingyu** [comment]
More information for you related to the windows version:

Beginning with Office 365 version 16.0.11629 and Windows 10 version 1903 [Windows May 2019 Update announcement], Office Add-ins running on Office 365 for Windows will use a Microsoft Edge WebView as the runtime.

**Comment by slowkoala** [comment]
@catchingyu Thanks for the extra information.  Our Windows updates are locked down so I haven't been able to test it with the latest update.  Even if it doesn't happen with Edge, we will want to release our add-in to users who don't have the requirements for the Edge WebView and use IE11 as their taskpane browser.

**Comment by MandytMSFT** [comment]
@slowkoala is this a blocking issue for your add-in release ?

**Comment by slowkoala** [comment]
@MandytMSFT I ended up writing a custom webpack plugin to remove the words `window.focus()` from all of our build output.  It's not ideal, but this is no longer blocking our add-in release.

**Comment by MandytMSFT** [comment]
@slowkoala  thanks for the info. We are looking at this bug actively, currently it's proved to be a original bug of IE. We will keep this bug on track.
