### ISSUE TITLE
Deprecation of exchange online tokens removes important functionality to report messsages

### ISSUE THREAD

**Issue by tomaskukk** [OfficeDev/office-js#5180]
## Exchange online token deprecation removes important functionality for reporting messages

Reporting messages to Microsoft has been an important functionality provided by soon to be deprecated API's. With exchange online token deprecation, there doesn't seem to be a way to do this anymore.

### Current situation
Both the Office REST API (beta version) and EWS API provides an endpoint to submit email reports to Microsoft.

REST: `/me/messages/<id>/reportMessage`
EWS: `<m:ReportMessage></m:ReportMessage>`

### Graph situation
Graph API doesn't provide this functionality, not in v1, nor beta. There is no way to submit reports to Microsoft using the Graph API to best of my knowledge. 

### Expected behavior
Reports to Microsoft can be done over an API after exchange online tokens have been deprecated.

### Question
Is there a way to do this after exchange online tokens have been deprecated? Is there some other way this could be achieved? The integration to report messages to MS for a 3rd party reporting add-in's has been an important piece of functionality.

**Comment by RuizhiSunMS** [comment]
Hi @tomaskukk, thx for reaching out here. 
Maybe some more information could be helpful for us to triage your case.
1. is your scenario a part of sending email (in other words, related with Outlook)?
2. any Microsoft doc for these 2 apis? if yes, please share the links.

**Comment by tomaskukk** [comment]
It's not really part of sending an email. It's part of reporting process of suspicious emails. This is useful for 3rd party add-ons that handle potential phishing reports.

To be fair, I can't find any documentation fast. I have seen the EWS documentation for this API endpoint before, but now I wasn't able to find it.

**Comment by samantharamon** [comment]
Hi @tomaskukk. Microsoft Graph provides the [threat assessment API](https://learn.microsoft.com/graph/api/resources/threatassessment-api-overview?view=graph-rest-1.0). Is this what you're after by any chance?

**Comment by tomaskukk** [comment]
Hmm, I'll have to check that, haven't bumped to it before. I'll report once I test it out.

Thanks!

**Comment by tomaskukk** [comment]
@samantharamon I tried out the API but it seems to not be intended for the usage I've described. There are quite a few issues with it.

1. To me, it looked like the API only works for users with enough privileges, even when the access token has `ThreatAssessment.ReadWrite.All` scope included. When making a request with a normal user, I encountered a 401 with message `Required authentication information is either missing or not valid for the resource`
2. Even making a request with an admin user didn't work, as then I encountered the following: `"The application '00000007-0000-0ff1-ce00-000000000000' is missing a HPA policy for target resource 'https://outlook.office.com/api/v2.0/users/tomas@nht8.onmicrosoft.com/messages/AAMkADY0Yzc2ZDYyLWZmMjYtNGFjZS1hMGUzLTVlMWQ3Nzg2ODQ3ZQBGAAAAAADyQWQbcRzjSqVx2QVCXZ6jBwBl-VXN1jZAQ7l-gm_l_LvvAAAAAAEMAABl-VXN1jZAQ7l-gm_l_LvvAADvqMtCAAA=?$select=id,sender,toRecipients,receivedDateTime,internetMessageId,subject,internetMessageHeaders'`
3. The API only has one scope `ThreatAssessment.ReadWrite.All` that would need to be granted for all users, giving them read access when the thing wanted is just an ability to push reports to the MS security center - submissions, similar as the native report functionality.

Hope these makes sense!

**Comment by samantharamon** [comment]
Thanks for detailing the issues you encountered, @tomaskukk. Upon looking into this further with the team, unfortunately, there doesn't appear to be a Graph API to report emails to Microsoft. As a workaround, we recommend configuring your add-in to report emails to a designated reporting mailbox. Once this is configured, users of your add-in will need to set user reported settings in Microsoft Defender. I'm including some resources for more information and guidance to get this set up.

- [Microsoft Defender for Office 365 roadmap](https://www.microsoft.com/microsoft-365/roadmap?filters=Microsoft%20Defender%20for%20Office%20365%2CIn%20development&searchterms=406167)
- [How your submissions to Defender for Office 365 are processed behind-the-scenes](https://techcommunity.microsoft.com/blog/microsoftdefenderforoffice365blog/how-your-submissions-to-defender-for-office-365-are-processed-behind-the-scenes/4231551)
- [Report suspicious email messages to Microsoft](https://learn.microsoft.com/defender-office-365/submissions-report-messages-files-to-microsoft#report-suspicious-email-messages-to-microsoft)
- [Submission result definitions in Exchange Online Protection and Defender for Office 365](https://learn.microsoft.com/defender-office-365/submissions-result-definitions)
- [User reported settings](https://learn.microsoft.com/defender-office-365/submissions-user-reported-messages-custom-mailbox)

If you haven't already, we recommend [submitting a feature request to Microsoft Graph](https://developer.microsoft.com/graph/support) for your scenario.
