### ISSUE TITLE
office word

### ISSUE THREAD

**Issue by TylerHuo** [OfficeDev/office-js#5181]
## Office word

I'm doing a text error correction, call the backend service by getting the text content, and the backend returns the subscript of the error text, how can I locate the wrong content in the document and highlight it based on the subscript? I checked the Range Api and didn't find it. How do I go about it?

_e.g. range(startIndex, endIndex)?_

**Comment by RuizhiSunMS** [comment]
Hi @TylerHuo, thx for reaching out here.
I wonder if this api would help you https://learn.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#word-word-body-search-member(1)
You must have origin string to judge error. With subscript and origin string, it should be ok to be found.
ps: I think it would be very helpful if you could paste your code and returned subscript here.

**Comment by TylerHuo** [comment]
### Hi @RuizhiSunMS 
   Here's a sample
```javascript
export async function getText() {
  return Word.run(async (context) => {
    try {
      const body = context.document.body;
      body.load("text");
      await context.sync();

      /**
       * Text examples
       *  今天我和朋友们一同去公园游玩，天氣晴朗，阳光明媚。我们在草地上踢足球，享受着愉快的时光。
       *  突然，一只小狗跑了过来，大家都觉得很可爱，并纷纷去抚摸它。之后，我们去湖边散步，
       *  看到了许多美丽的花朵和飞翔的小鸟。今天真是一个愉快的日子！
       */

      // Assume backend returned the following errors
      let errors = [
        { startIndex: 15, endIndex: 17, correction: "天氣 -> 天气" },
        { startIndex: 22, endIndex: 25, correction: "fixedText" },
        // ...
      ];

      //todo 

      // eslint-disable-next-line no-undef
      console.log(body.text);
    } catch (e) {
      // eslint-disable-next-line no-undef
      console.error("详细错误信息:", JSON.stringify(e.debugInfo, null, 2));
    }
  });
}
``` 

How do I locate content in a word document based on startIndex and endIndex?

Thank U

**Comment by TylerHuo** [comment]
### When I use WpsJs, I can use startIndex and endIndex to locate according to the Range API. The Range API in Word doesn't seem to work

**Comment by RuizhiSunMS** [comment]
Hi @TylerHuo,
May I ask that what you want is be like this?
![image](https://github.com/user-attachments/assets/56a0633a-59bf-479a-838b-07d4303622cf)

If yes, I did a quick try and this code snippet worked for me.
```
async function run() {
  await Word.run(async (context) => {
    const body = context.document.body;

    console.log("Your code goes here");
    const rangelist = body.search("天氣");
    rangelist.load("items");
    await context.sync();
    for (var i = 0;i<rangelist.items.length;i++){
      rangelist.items[i].font.highlightColor = "yellow";
    }
    await context.sync();
    rangelist.getFirst().insertText("天气","Replace");
    await context.sync();
  });
}```
