### ISSUE TITLE
Excel Becomes Unresponsive When Opening File from Base64 String

### ISSUE THREAD

**Issue by GajananVadekar** [OfficeDev/office-js#5189]
Platform : PC desktop
Host: Word
Office version number: Microsoft® Word for Microsoft 365 MSO (Version 2404 Build 16.0.17531.20140) 64-bit
Operating System: Microsoft Windows 11 pro.

Excel: Microsoft® Excel® for Microsoft 365 MSO (Version 2410 Build 16.0.18129.20158) 64-bit 

Hi team,
I am encountering an issue where Microsoft Excel becomes unresponsive (hangs) when opening a file that has been encoded in Base64 format. This problem arises when attempting to open the file programmatically using a Base64 string, which results in Excel freezing and failing to respond.

here is my code snippets for opening excel using base64.
[Code.txt](https://github.com/user-attachments/files/18123152/Code.txt)

Could you please assist me with this issue and provide a proper resolution.
Thanks.

**Comment by RuizhiSunMS** [comment]
Hi @GajananVadekar, thx for reaching out here.
I also failed to execute your code but I'm able to insert some simple ones. Then I'm interested in what content you are going to insert? And would you please confirm whether you can insert some simple excel files?

**Comment by GajananVadekar** [comment]
Hi, @RuizhiSunMS, thx for looking into the issue.
I am able to insert other Excel files without any problems, but I'm encountering delays with this particular file. It seems that something is causing it to take much longer to load. This file contains charts and images.

**Comment by GajananVadekar** [comment]
> Hi, @RuizhiSunMS, thx for looking into the issue. I am able to insert other Excel files without any problems, but I'm encountering delays with this particular file. It seems that something is causing it to take much longer to load. This file contains charts and images.

Hey, we were checking the issue and have found the root cause of issue, you can close out this ticket, Thanks.

**Comment by RuizhiSunMS** [comment]
> > Hi, @RuizhiSunMS, thx for looking into the issue. I am able to insert other Excel files without any problems, but I'm encountering delays with this particular file. It seems that something is causing it to take much longer to load. This file contains charts and images.
> 
> Hey, we were checking the issue and have found the root cause of issue, you can close out this ticket, Thanks.

Glad to here that. Welcome to reach out here if any other problems.
