### ISSUE TITLE
New Outlook - The task pane browser options are not available

### ISSUE THREAD

**Issue by ArjunSureshKumar92** [OfficeDev/office-js#5201]
In regular Outlook or OWA, when my office js addin is opened, the task pane can be mouse right-clicked to open the context menu and the "inspect" option can be selected. This allows me to check multiple information about the browser and also access the local and session storage info.

However, when i tried "New Outlook", there is no context-menu opened when i right click on the task pane. 

So, is this going to be fixed?

**Comment by kumarshrey-msft** [comment]
You can do the same via `olk.exe --devtools`. Following this [documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/one-outlook#debug-your-add-in) for more details regarding how to debug your add-in on the new Outlook on Windows.
