### ISSUE TITLE
Addins with SupportsPinning no longer work in  for outlook.com (outlook.live.com) web

### ISSUE THREAD

**Issue by lunarwtr** [OfficeDev/office-js#5202]
Using the SupportsPinning tag to turn on pinning ability, no longer is reflected on outlook.live.com  web.  If I use the desktop client it will show, but ability to pin is not shown in browser.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office on the web]: web
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Browser (if using Office on the web): Chrome
 
## Expected behavior
I expect a Pin icon in the titlebar of my taskpane

## Current behavior
no pin icon

**Comment by kumarshrey-msft** [comment]
Hi @lunarwtr, as outlined in our [public documentation](https://learn.microsoft.com/en-us/office/dev/add-ins/outlook/pinnable-taskpane?tabs=jsonmanifest), pinnable task panes aren't available for the following: 
1. Appointments/Meetings 
2. Outlook.com

You can refer to the documentation for more details

**Comment by lunarwtr** [comment]
I'm assuming outlook.com is referring to outlook.live.com ?

It was working a couple months ago in web before it suddenly stopped.   Pinning is still working when I open my account in the windows desktop client. (please dont break it if you weren't aware :D)

**Comment by kumarshrey-msft** [comment]
Yes, they refer to the same. 

Rest assured, any changes to the functionality of any feature will be communicated through our public documentation well in advance.
