### ISSUE TITLE
 Does Office Add-ins support .NET Core?

### ISSUE THREAD

**Issue by Piyush-IT** [OfficeDev/office-js#5204]
Hello Team,

I’m planning to migrate an application from .NET Framework 4.8 to .NET 7.0, as I need to deploy it without using IIS and instead utilize Kestrel as the web server. Could you please confirm if this is possible?

This is a bit urgent, so I would greatly appreciate your guidance and suggestions on the best approach.

**Comment by RuizhiSunMS** [comment]
Hi @Piyush-IT, I fully understand your feelings. But this channel is for Office-js rather than .net. Maybe you can reach out to https://techcommunity.microsoft.com/category/dotnet?WT.mc_id=dotnet-35129-website. (or another section in Tech Community)
