### ISSUE TITLE
Unable to use NAA in event-based activation in Windows Classic

### ISSUE THREAD

**Issue by barclayadam** [OfficeDev/office-js#5208]
Trying to use NAA in event-based activation fails with an error when trying to create the public client application in event-based activation. The same code works in other platforms and in the task pane of Classic Windows

````
TypeError: Cannot read properties of undefined (reading 'href')
    at getCurrentUri (~src\bundle.js:15222:28)
    at buildConfiguration (~src\bundle.js:7465:124)
    at new BaseOperatingContext (~src\bundle.js:14485:100)
    at new NestedAppOperatingContext (~src\bundle.js:14561:9)
    at createNestablePublicClientApplication (~src\bundle.js:4867:27)
    ...
````

Note the `bundle.js` is our bundled add-in, with msal-browser embedded (using `rspack`). It appears to believe it is being hosted in a browser environment, but `window.location` is undefined, as that method, `getCurrentUri` looks like:

````javascript
/**
 * Returns current window URL as redirect uri
 */
function getCurrentUri() {
    return window.location.href.split("?")[0].split("#")[0];
}
````

## Your Environment

* Platform: PC Desktop
* Host: Outlook Classic
* Office version number: 16.0.18227.20162
* Operating System: Windows 11
 
## Expected behavior
Nestable Public Client Applications can be created in event-based activation on Windows Classic

## Current behavior
Exception, as above.

## Steps to reproduce
In events.js try to create a Nestable PCA (note `logger` is our utility over console methods):

````javascript
async function tryCreatePublicClientApplication() {
    try {
        return await createNestablePublicClientApplication({
            auth: {
                clientId: process.env.PUBLIC_ENTRA_APP_ID!,
                authority: 'https://login.microsoftonline.com/organizations',
            },

            system: {
                loggerOptions: {
                    logLevel: LogLevel.Verbose,

                    piiLoggingEnabled: process.env.NODE_ENV === 'development',

                    loggerCallback: (logLevel, message) => {
                        switch (logLevel) {
                            case LogLevel.Error:
                                logger.error(message);
                                break;

                            case LogLevel.Warning:
                                logger.warn(message);
                                break;

                            case LogLevel.Info:
                                logger.info(message);
                                break;

                            case LogLevel.Verbose:
                                logger.debug(message);
                                break;
                        }
                    },
                },
            },
        });
    } catch (err) {
        logger.error('Unable to create NAA application: %e', err);

        return undefined;
    }
}
````

Thank you for taking the time to report an issue. Our triage team will respond to you in less than 72 hours. Normally, response time is <10 hours Monday through Friday. We do not triage on weekends.

**Comment by davidchesnut** [comment]
Hi @barclayadam,

When you run your build to pull in msal-browser you need to be sure the process isn't transpiling or applying polyfills or anything like that. The msal-browser code should be usable as is. I've seen issues when other build processes attempt to modify the code. Can you let us know if that works?

Thanks,
David

**Comment by davidchesnut** [comment]
Hi @barclayadam, sorry I didn't realize but there is a regression bug in msal-browser that causes this issue. It will be fixed but in the meantime, if you use version 3.26.1 you won't see the href issue.

Cheers,
David

**Comment by davidchesnut** [comment]
I'll go ahead and close this issue, but please reopen if you still have issues with NAA in event-based activation. Thanks!
