### ISSUE TITLE
Read data of another opened workbook

### ISSUE THREAD

**Issue by chengtie** [OfficeDev/office-js#5218]
We build several Excel add-ins. I know we can use [these APIs](https://learn.microsoft.com/en-us/javascript/api/excel/excel.range?view=excel-js-preview) to read data of the currently opened workbook.

Now, assume that the user has opened 2 workbooks: `a.xlsx` and `b.xlsx`. The add-in is opened in `a.xlsx`, how could we code the add-in so that it can read data of `b.xlsx`?

**Comment by RuizhiSunMS** [comment]
Hi @chengtie, thx for reaching out here. 
Here we have two suggestions:
1. [insertWorksheetsFromBase64(base64File, options)](https://learn.microsoft.com/zh-cn/javascript/api/excel/excel.workbook?view=excel-js-preview#excel-excel-workbook-insertworksheetsfrombase64-member(1))
2. there is an example code snippet called 'create workbook' in our scriptlab
