### ISSUE TITLE
[Excel] OfficeRuntime.AsyncStorage or OfficeRuntime.storage does not work in TaskPane

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js#522]
We have used .AsyncStorage and it worked fine. After updating typings to 1.0.8: https://www.npmjs.com/package/@types/office-runtime and using .storage we found out with latest Office updates that in the taskpane we are not able to set the value (and it turned out that it does not work no matter if we use .AsyncStorage or .Storage), however when we use it in Custom Functions it works fine. The issue was reproducible also with CFSample - in the UI it does not work, Custom Functions work fine.

## Expected Behavior
Both .AsyncStorage and .storage work as expected in both TaskPane and Custom Functions runtime.

## Current Behavior
It is not possible to store values in .AsyncStorage nor .Storage inside TaskPane app.

## Steps to Reproduce, or Live Example
Use CFSample where it is easily reproducible - simply try to retrieve or set value using UI.

## Context
Blocking issue as this functionality is crucial for passing validation/authentication tokens between TaskPane and Custom Functions Runtime.

## Your Environment
Windows 10, Excel version 1904(Build 11601.20204).

**Comment by madhavagrawal17** [comment]
Thank you @4tti for bringing this to our attention. We applied the fix for this issue. Please try your add-in now and let us know if you face any issue.

**Comment by 4tti** [comment]
Hello @madhavagrawal17 
Yep, it works now!
**Thanks for such a quick fix.**
