### ISSUE TITLE
Attachment IDs fetched using Office.context.mailbox.item.getAttachmentsAsync() change after some time for the same attachment

### ISSUE THREAD

**Issue by cluB-Watermelon** [OfficeDev/office-js#5226]
In Outlook on Mac (Classic UI), it was observed that if an inline attachment is present in the email body, and regular attachments are also present, the attachment ID of both, the regular and inline attachments changes after some time, when fetched using Office.context.mailbox.item.getAttachemntsAsync(). 

## Your Environment
* Platform [PC desktop, Mac, iOS, Office on the web]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook (Classic UI)
* Office version number: 16.91
* Operating System: MacOS Sonoma 14.5
 
## Expected behavior
Ideally, the ID of an attachment should stay consistent when fetched using Office.context.mailbox.item.getAttachmentsAsync().

## Current behavior
Currently, when attachment details are fetched using Office.context.mailbox.item.getAttachmentsAsync(), the value of the ID of that attachment changes after some time when fetched again using Office.context.mailbox.item.getAttachmentsAsync().

## Steps to reproduce

1. Create new email in Outlook.
2. Add inline attachment.
3. Add a regular attachment.
4. Fetch the attachment details using getAttachmentsAsync() API call multiple times.
5. Check the ID's of the attachments fetched.

## Context
We have an addin that works around handling attachments, and removing them when necessary. 
As the ID of an attachment keeps changing, there is no reliable way to keep track of an attachment, or to remove it (as the remove call requires the ID of that attachment).

**Comment by Swathy-Mothilal** [comment]
Hi @cluB-Watermelon , we’re unable to reproduce the issue on our side. Could you help clarify the following questions?

1. Since when did you start experiencing this issue? 
2. Does the issue occur in the New Outlook for Mac?

Additionally, could you please share a repro video to help us investigate further.
