### ISSUE TITLE
[Excel]Copy pasting a content addin should throw an event

### ISSUE THREAD

**Issue by arpit974** [OfficeDev/office-js#524]
## Expected Behavior
should be able to differentiate whether the addin is copy pasted or a new addin is added.

## Current Behavior
when copy pasting an addin we get Office.InitializationReason as document opened and same on reloading the addin, we need to able to differentiate between both the scenarios.

## Context
every time i reload addin i want to read the metadata and load addin accordingly, and when i copy paste i want to treat it like a new addin.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]:  desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Build Number 10730.20334

**Comment by catchingyu** [comment]
@arpit974 Thanks a lot for reaching us. May I understand more context on your scenario of the differentiation of the 1st time Addin Load and the CCP of Addin later? What are the differences there?

Here are some documents might help you : 
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/understanding-the-javascript-api-for-office
https://docs.microsoft.com/en-us/javascript/api/office/office.initializationreason?view=office-js

**Comment by arpit974** [comment]
On some user action the state of addin gets changed, I want the state to be preserved in case of addin reload.
In case of copy-paste scenario, copied addin should behave similar to inserting a new addin and should not know anything about the state of addin it is copied from.

for eg: addin state corresponds to the data in excel, i don't want two addins pointing to the same data.

Also, why copy - pasting a content addin only supported in excel desktop and not online.

**Comment by catchingyu** [comment]
As for the persist of state, pls refer to: 
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/persisting-add-in-state-and-settings


Web Online Excel is catching up the feature gaps with desktop version, it is our current on-going and heavily investment items.

**Comment by kbrandl** [comment]
Closing this issue, as it seems like @catchingyu has provided feedback to effectively address it. @arpit974 if that's not the case (and you'd like this issue to be re-opened) please comment here to let us know what additional information you need, and we'll re-open the issue. Thanks!
