### ISSUE TITLE
How to read/write custom properties in Excel Online & PowerPoint online using Office.js ?

### ISSUE THREAD

**Issue by ukalhapu** [OfficeDev/office-js#525]
We are developing Office Add-in for online office apps. 
Looking for API to read/write custom properties in Excel and PowerPoint online.

For Word online it can be achieved using following:

function setProperties() { 
           console.log("Adding custom properties ...");
		   Word.run(function (context) {
             context.document.properties.customProperties.add("TestOBID", "WTDoc:1234");
              return context.sync()
               .catch(function (e) {
                 console.log(e.message); 
              })
           })
        }
		
function getProperties() { 
            console.log("Reading custom properties ...");
		Word.run(function (context) {
                var customDocProps = context.document.properties.customProperties;
                 context.load(customDocProps);
               return context.sync()
                   .then(function () {
                  console.log("No. of custom properties:: " + customDocProps.items.length);
              })
         })
        }

What are APIs for Excel  and PowerPoint online ?
It would be helpful if you provide some examples.

**Comment by catchingyu** [comment]
@ukalhapu thanks a lot for reaching us. I assume the document can help you. There are some examples in the Excel customer properties.

https://docs.microsoft.com/en-us/javascript/api/excel/excel.customproperty?view=office-js
https://docs.microsoft.com/en-us/javascript/api/excel_release/excel.customproperty?view=office-js

**Comment by JuaneloJuanelo** [comment]
In  addition to @catchingyu  answered, please note that custom (and built-in) document properties are supported in Word and Excel only at this point. Powerpoint does not have an API yet to do this, please feel free to vote, upvote a user voice request here: https://officespdev.uservoice.com

**Comment by ukalhapu** [comment]
Thanks,
I am able to read/write custom properties in Excel.
