### ISSUE TITLE
Can't call context.sync() inside Dialog opened via FunctionFile

### ISSUE THREAD

**Issue by levitatejay** [OfficeDev/office-js#526]
I have an Angular OfficeJS Add-In with a view that contains a single button.
On button click I am trying to update the value in a cell with the following code:

```
testClick() {
    Excel.run(context => {
      const sheet = context.workbook.worksheets.getActiveWorksheet();
      const topLeft = sheet.getCell(1, 1);
      topLeft.values = [['test']];
      return context.sync();
    });
  }
```

When I open the view in a task pane and click the button it runs without issue.
When I open the view in a Dialog using a function file and click the button the code fails at `return context.sync();` with the error:
```
GeneralException: An internal error has occurred.
   at Anonymous function (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:24:273811)
   at T (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:24:212677)
   at x (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:24:212763)
   at t (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:24:212571)
   at l (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:24:211078)
```

Function file appears to work fine, it opens a dialog and updates a cell
Function file:
```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge" />

    <base href="/" />

    <script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>

    <script type="text/javascript">
      (function() {
        Office.initialize = function(reason) {};
      })();

      function openCalculateDialog(event) {
        Office.context.ui.displayDialogAsync('https://localhost:4222/#/home', {
          height: 30,
          width: 30
        });

        event.completed();
      }
    </script>
  </head>

  <body>
    <!-- NOTE: The body is empty on purpose. Since function in function-file.js are
       invoked via a button, there is no UI to render. -->
  </body>
</html>
```

Office.initialize() is running; there are no errors and the placeholder div (from index html body) is being removed from the dialog after its bootstrapped.

## Context
I'm trying to open a dialog directly from the ribbon that will make an API request and write the results into the workbook

## Your Environment
* Platform: PC desktop
* Host: Excel
* Office version number: 2016 - 16.0.11601.20184
* Operating System: Windows 10

**Comment by Rick-Kirkham** [comment]
This is expected behavior. The only APIs that can be called inside the dialog are `isSetSupported` and `messageParent`. See [Send information from the dialog box to the the host page](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#send-information-from-the-dialog-box-to-the-host-page).

If you want interaction between the dialog and the workbook, the button on the dialog sends a message with `messageParent` back to the parent page indicating what should be done. A handler on the parent page for `DialogEventReceived` then carries out the requested task. See the section in the link for details.

**Comment by sjgarland** [comment]
How can I make information flow in the other direction between a dialog (which I am willing to open either in a `FunctionFile` or in a taskpane) and the workbook?  For example, suppose I want a dialog to display the value in a cell chosen by the user.  This would be possible if the dialog could call `context.sync()` or if it could get a response back from the parent page after sending a message with `messageParent`.  But neither of these seems to be possible.  Is there another way?
