### ISSUE TITLE
Can displayDialogAsync API read response from server side page displayed in dialog box ?

### ISSUE THREAD

**Issue by ukalhapu** [OfficeDev/office-js#527]
Basically we want to display wizard in dialog box on click of custom ribbon button.
     Office.context.ui.displayDialogAsync('https://myDomain/wizard.jsp', {height: 30, width: 20});
Then user supply information asked on wizard and click Finish button of the wizard. 
The wizard get processed on the server and returns some information back. 
We would like to consume this information in add-in JavaScript function which launched the wizard using displayDialogAsync.
Can displayDialog API consume response from such wizard ?

How to consume it ? any example ?

Is there alternative to displayDialogAsync API to show server side wizards ?

Any help is appreciated.
Thanks

**Comment by Rick-Kirkham** [comment]
This can be done. The JavaScript in the dialog page puts the information it gets from the server into a stringified structure (could be JSON or XML or any structure you want), and then it passes the string to the parent page (such as the FunctionFile.html) with the `messageParent` API. On the parent page, you created a handler for the `DialogMessageReceived` event that processes the message. For details, see [send-information-from-the-dialog-box-to-the-host-pag](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#send-information-from-the-dialog-box-to-the-host-page).

As for alternatives, you could have a wizard in the task pane or in an iFrame in the task pane.
