### ISSUE TITLE
Edge WebView: Dialog API triggers an error

### ISSUE THREAD

**Issue by htryggva** [OfficeDev/office-js#530]
Whenever I use the office-js Dialog API, an error occurs on the page loaded in the dialog. I've seen this in our own apps and in ScriptLab.

## Expected Behavior
No error should occur on the page opened in the dialog.

## Current Behavior
A few errors occur on the page. Please see screenshot.

## Steps to Reproduce, or Live Example
1. Execute this in ScriptLab:
`Office.context.ui.displayDialogAsync(location.href, () => {});`
2. Open Edge Dev Tools Preview and attach to the Dialog
3. Observe errors (screenshot included)

## Your Environment

* Platform: PC desktop - Edge WebView
* Host: Word, Outlook
* Office version number: 16.0.11708
* Operating System: Windows 1903 - 18885.1001

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

![image](https://user-images.githubusercontent.com/6515360/58282649-99ce7b80-7da6-11e9-85b4-c4e85dcdc809.png)

**Comment by kbrandl** [comment]
@htryggva sorry to hear that you're having trouble, but thanks for reporting this issue. @jargil is this something that you can investigate (since it's related to Edge WebView)?

**Comment by jargil** [comment]
@htryggva - thanks for reporting and providing screenshots. I'll look into this.
Beyond seeing errors in the console log, are you having problems using the dialog API?

**Comment by htryggva** [comment]
@jargil Thanks for looking into this. We noticed the exception occurring for some of our users in our telemetry. So far, we've not noticed any problems in using the Dialog API and therefore don't think that our end users are affected by this issue.

**Comment by jargil** [comment]
@htryggva - just letting you know I've fixed this one, will update here once I have a build with the fix to see if you can help validate that you don't see those errors anymore on your end. Thanks again for reporting this issue and for the very clear repro steps.

**Comment by htryggva** [comment]
@jargil That sounds great! Happy to help and looking forward to trying it out :)

**Comment by jargil** [comment]
@htryggva - quick update on the build number with this fix. It should be included in any Office build 16.0.11810+.

**Comment by htryggva** [comment]
@jargil Just tested this on Word 16.0.11819 (Office Insider). Seems like it's fixed. Thanks a lot :)

**Comment by jargil** [comment]
@htryggva - thank you!
