### ISSUE TITLE
can add-in load the FunctionFile.html from URL of different domain than the domain from which add-in manifest xml loaded ?

### ISSUE THREAD

**Issue by ukalhapu** [OfficeDev/office-js#531]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I am testing the add-in with Word Online. 
I insert add-in using "Upload Add-in" feature and selects the local manifest file for e.g. C:\addin\test.xml.
The Add-in defined custom ribbon button and FunctionFile element whose URL points to HTML file served by the tomcat running on the localhost. Add-in commands are working fine and functions defined in the FunctionFile.html get executed. 

<FunctionFile resid="FunctionFile.Url" />
<bt:Url id="FunctionFile.Url" DefaultValue="https://<localhost.com>/WebApp/FunctionFile.html" /> 

If I modify the FunctionFile URL to HTML file served by tomcat running on the different host and reload the add-in then  add-in commands does not work as expected.
<bt:Url id="FunctionFile.Url" DefaultValue="https://<host.com>/WebApp/FunctionFile.html" /> 

Could you please help to resolve the issue ?

**Comment by ukalhapu** [comment]
### Working case:
<FunctionFile resid="FunctionFile.Url" />....
.......
<bt:Url id="FunctionFile.Url" DefaultValue="https://<localhost.com>/WebApp/FunctionFile.html" />

### Non-working case:
<FunctionFile resid="FunctionFile.Url" />...
......
<bt:Url id="FunctionFile.Url" DefaultValue="https://<remotehost.com>/WebApp/FunctionFile.html" />

**Comment by ukalhapu** [comment]
can someone provide any help on the issue ?

**Comment by dmahugh** [comment]
@weshi can you take a look at this? Thanks!

**Comment by ukalhapu** [comment]
@weshi could you please help ?

**Comment by weshi** [comment]
@lumine2008 this seems the same issue you worked on before.

**Comment by lumine2008** [comment]
as this issue is not in Excel SJ API scope, so unassigning myself
