### ISSUE TITLE
Office add ins SSO return 502 on web word add ins

### ISSUE THREAD

**Issue by seng1** [OfficeDev/office-js#532]
I have implemented office add ins SSO with asp.net. I have deploy our the application to our office 365. It was working fine the first week and after a few week later it return 502.

We expect we can request to our api with the access token but it was not.
When we deploy to our office 365, first week it works perfectly for both Office desktop and Office Web. but after a few later our it got error, i try to debug with Word Web app and i can see that the API return 502 bad request. I was wondering that is 

* Platform Office Online
* Browser :CHROM, Firefox, Edge,IE

![58485718-c0b5f480-818e-11e9-94f7-66d125763be3](https://user-images.githubusercontent.com/3612176/58527197-f6dd8d80-81fb-11e9-9bcf-daf99d263433.PNG)
![58485785-e3e0a400-818e-11e9-81dd-89a511858258](https://user-images.githubusercontent.com/3612176/58527212-0361e600-81fc-11e9-9e3b-0da95b87ce1a.PNG)

**Comment by Rick-Kirkham** [comment]
@seng1  What is your Office version/build number? SSO is turned off on builds that have reached the semi-annual channel.

**Comment by seng1** [comment]
My office build number is 1903. It work fine for both office desktop and office web app after I restart the app. That's issue is happening when sending request to my web API because I am also use firebug debugging and I can see that office js return a valid token. What I was wondering is, is it possible this issue cause from JWT middle as I send you on above message.

**Comment by seng1** [comment]
When restart the application, it works arround one week and after that I need to restart the application again.

**Comment by niteshgolchha85** [comment]
Is it only the SSO API that is returning the 502 error or are all office APIs returning this error?

**Comment by niteshgolchha85** [comment]
Closing since there was no response for >30 days. Please feel free to reopen if the issue still persists.
