### ISSUE TITLE
Office add ins SSO return 502

### ISSUE THREAD

**Issue by seng1** [OfficeDev/office-js#536]
I have implemented office add ins SSO with asp.net. I have deploy our the application to our office 365. It was working fine the first week and after a few week later it return 502.
 
![Capture](https://user-images.githubusercontent.com/3612176/58485718-c0b5f480-818e-11e9-94f7-66d125763be3.PNG)
![Capture](https://user-images.githubusercontent.com/3612176/58485785-e3e0a400-818e-11e9-81dd-89a511858258.PNG)

**Comment by Rick-Kirkham** [comment]
The Transfer issue feature is working today so I have transferred this and reopened it.

**Comment by Rick-Kirkham** [comment]
@seng1 
What is the Office build number?

**Comment by Rick-Kirkham** [comment]
It looks like the OP already recreated this issue in the office-js repo, so I'll close this.
