### ISSUE TITLE
Outlook OfficeOnline 16.0.10205.1000 can't get location string

### ISSUE THREAD

**Issue by rodrigoguariento** [OfficeDev/office-js#538]
After set the Office.context.mailbox.item.location programatically for the first time, its not possible to get other values set later in Office.context.mailbox.item.location at Outlook OfficeOnline 16.0.**10205**.1000 .

## Expected Behavior
After set some value into location, it should return the same value after.

## Current Behavior
After set some value at location field for the first time, this same value will be gotten even if you try to set other value.

## Steps to Reproduce, or Live Example
Office.context.mailbox.item.location.setAsync('room1');
Office.context.mailbox.item.location.getAsync(function(asyncResult: Office.AsyncResult<string>) {
   console.log( asyncResult.value ); // returns "room1", ok!
});
Office.context.mailbox.item.location.setAsync('room2');
Office.context.mailbox.item.location.getAsync(function(asyncResult: Office.AsyncResult<string>) {
   console.log( asyncResult.value ); // returns "room1", wrong. Should be "room2"!
});

## Context
This problem occurs only in Outlook OfficeOnline 16.0.10205.1000, the version Outlook OfficeOnline 16.0.10908.1000 works fine. Outlook on-premise works fine too.

## Your Environment
Google Chrome.

## Useful logs
No logs.

**Comment by exextoc** [comment]
@rodrigoguariento I am not able to reproduce this problem in latest OWA (Outlook Online: new OWA).

Couple of questions:

1. Are you using old OWA or new OWA?
2. When you say "Outlook on-premise works fine too." - do you mean Outlook Desktop client running on Windows System?
3. From where are you capturing these version numbers: 16.0.10205.1000 and 16.0.10908.1000 for Outlook OfficeOnline? Can you please share screenshot of this?
4. Are you using O365 Online or you have On-Premise setup?

**Comment by rodrigoguariento** [comment]
1. The problem occurs in old OWA, the new OWA is normal, Outlook Desktop version is normal too.

2. Yes, Outlook Desktop client running on Windows 10.

3. From this: 
```
Console.log(Office.context.diagnostics.host); // Outlook
Console.log(Office.context.diagnostics.platform); // OfficeOnline
Console.log(Office.context.diagnostics.version); // 16.0.10205.1000 from old OWA, and 16.0.10908.1000 from new OWA
```

4. I'm using O365 Online.

**Comment by exextoc** [comment]
@rodrigoguariento Thanks for your response.

Can I know the reason for using the older version (16.0.10205.1000) instead of newer version of OWA (16.0.10908.1000)? Looks like issue is not reproducible in 16.0.10908.1000 version. You can continue using new one then?

By the way, office.context.diagnostics.version tells Office version. To get OWA or Exchange versions, we can use office.context.mailbox.diagnostics APIs.

**Comment by rodrigoguariento** [comment]
> @rodrigoguariento Thanks for your response.
> 
> Can I know the reason for using the older version (16.0.10205.1000) instead of newer version of OWA (16.0.10908.1000)? Looks like issue is not reproducible in 16.0.10908.1000 version. You can continue using new one then?
> 
> By the way, office.context.diagnostics.version tells Office version. To get OWA or Exchange versions, we can use office.context.mailbox.diagnostics APIs.

Yes, of course, we can. The main reason it's because I tried for some times publish my add-in at Microsoft Seller Panel (Dashboard), and we were denied the publishing because the validation are being made in old OWA, where this problems occurs.

**Comment by rodrigoguariento** [comment]
Dears, problem solved, our add-in was accepted and published after I change the code to ignore this behaviour when old OWA is detected. We are considering that old OWA will be deprecated soon. Thank you!
