### ISSUE TITLE
Automatic OneDrive saving breaks online Word if a ContentControl exists

### ISSUE THREAD

**Issue by dinkom** [OfficeDev/office-js#54]
Automatic OneDrive saving breaks online Word if a ContentControl is inserted through Office.js. Until circa Jan 18 2018, the same code worked fine both online and on desktop. 

## Expected Behavior
Expected behavior is not to break online Word when inserting content through Office.js.

## Current Behavior
After inserting a ContentControl through Office.js code, online Word breaks: error message pops up, document cannot be handled any more until refreshed, last changes are not saved.

## Steps to Reproduce, or Live Example
Code for Script Lab: https://stackoverflow.com/questions/48380951/online-word-breaks-when-inserting-a-content-control

[kbrandl]:  I created this Script Lab snippet that can be used to repro the issue using Script Lab and Word Online:  https://gist.github.com/kbrandl/49b251a62bc56251c359b4b073e89e6d.

- after running the code snippet, wait a few moments until it breaks (without doing anything else to the document), usually 10-20 seconds, sometimes less, sometimes more

## Context
This issue blocks the users of our add in to use it in the online version of Word, which they were able to do so far. Ideally, both the desktop versions and online version should display the same behavior when using Office.js.

## Your Environment
* Platform: Online Word
* Host: Word
* Operating System: macOS
* Browser (if using Office Online): latest Chrome and Firefox Quantum

**Comment by kbrandl** [comment]
@dinkom  -- thanks for logging this issue here for the product team.  FYI, I've edited the **Steps to Reproduce...** section to add a link to a Script Lab gist that anyone can use to repro the issue using Script Lab and Word Online.

**Comment by JuaneloJuanelo** [comment]
Thanks for reporting this, we are investigating.

**Comment by alx-andru** [comment]
Are you seeing this message?
I'm encountering the same issue and was first wondering if it was my own addin causing it or not.

I was running Chrome (Version 63.0.3239.132 (Official Build) (64-bit)) and Windows 10

![scriptlab](https://user-images.githubusercontent.com/19511694/35882438-314d2ea2-0b52-11e8-915d-6e97abd25426.png)

**Comment by dinkom** [comment]
@alx-andru yes, that is the same message I am getting.

**Comment by weshi** [comment]
Could you try it again? This should be fixed now.

**Comment by dinkom** [comment]
@weshi I just tried it and it works fine :)

**Comment by JuaneloJuanelo** [comment]
Awesome! closing this issue. @dinkom  thanks for testing it!
