### ISSUE TITLE
[Excel] when create textbox in different computer,display at different position

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#540]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
Thank you for your understanding and continued feedback.

hi

when i create a textbox ,set left=100,top=100. and set textbox width=500 and height=50 . in 1920*1080. it's ok, but in 2048×1024 。it's display wrong。  i don't know what's wrong

**Comment by RuoyingLiang** [comment]
Thanks for reporting. Creating a bug to track first.

**Comment by MandytMSFT** [comment]
@dinglicoding could you help provide more details to help us better identify the issue?

Description :

Expected Behavior

Current Behavior

Steps to Reproduce, or Live Example

Context

Your Environment
Platform [PC desktop, Mac, iOS, Office Online]:
Host [Excel, Word, PowerPoint, etc.]:
Office version number:
Operating System:
Browser (if using Office Online):

**Comment by MandytMSFT** [comment]
@dinglicoding  could you help provide more details for investigation purpose, thanks !

**Comment by dinglicoding** [comment]
@tfjy2008 

Description :
In HD screen textbox will display wrong first time, if i  second run it, it's ok

Expected Behavior
textbox display in HD Screen it's also fine.

Current Behavior
In HD screen textbox will display wrong first time, if i  second run it, it's ok

Your Environment
Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
Host [Excel, Word, PowerPoint, etc.]: Excel
Office version number:1907
Operating System:windows
Browser (if using Office Online):

**Comment by kbrandl** [comment]
@tfjy2008 looks like @dinglicoding has provided the details you requested -- are you able to resume investigation now? Thanks!
