### ISSUE TITLE
Office excel add-in is getting cropped when loaded in excel online and in excel Desktop

### ISSUE THREAD

**Issue by shyambhiogade** [OfficeDev/office-js#542]
I have an Excel office Addin developed using office.js, when that addin is loaded in excel online or excel desktop on some machine its getting cropped. Please find the image below, notice that scroll head box at the bottom is not visible.Because of this the pop up message, i show is cropped.

![image](https://user-images.githubusercontent.com/10468130/58821023-f9b7f400-85e8-11e9-96ba-54d1841ed347.png)

## Expected Behavior
When its all good, bottom scroll head box is visible
![image](https://user-images.githubusercontent.com/10468130/58821059-0fc5b480-85e9-11e9-99ac-c487989fca1e.png)

I belive its an issue from office framework nothing to do with the way office add-in is developed. Let me know if anybody knows the solution for it.

**Comment by lumine2008** [comment]
Thanks @shyambhiogade for sharing the information. 
Looks like there is an error about date format, would you please check your code? or share your code at here? we need more information to locate the issue.

**Comment by shyambhiogade** [comment]
@lumine2008 please ignore the error message, what i wanted to show you is that bottom scroll head is not available when add-in loaded with a manifest file. The error message i am showing is the part of my addin functionality

**Comment by lumine2008** [comment]
Thanks, @shyambhiogade , i notice the bottom scroll head is not available, i would like to learn if this happen when you got the error message? if the error is fixed, will that bottom scroll head be able to show?

**Comment by shyambhiogade** [comment]
@lumine2008, it happens without error message also,  please give me your email id, i can send you the manifest file to use to reproduce. or you can create a sample application and use the manifest file to load the addin

**Comment by lumine2008** [comment]
@shyambhiogade, Please send the manifest to raymonlu@microsoft.com, thanks.

**Comment by shyambhiogade** [comment]
@lumine2008 I have sent you an email with the required details.

**Comment by lumine2008** [comment]
Thanks, @shyambhiogade, 
I found we have a internal bug 3333346 tracking this issue. I have invite PM to share some update to you.

**Comment by shyambhiogade** [comment]
Thanks @lumine2008, I will be waiting for the update.

**Comment by lliu113** [comment]
@shyambhiogade - Hello! I'm Lillian, I work on the Office Extensibility team with Raymond (@lumine2008). Thanks for reporting the issue. We are currently in the process of upgrading our taskpane infrastructure. We are planning on addressing this issue as part of the upgrade, scheduled July - Dec 19.

**Comment by lindalu-MSFT** [comment]
According to bug, this is Won't Fix since it should be fixed by React upgrade. Please let us know if you're still experiencing the issue. Otherwise, closing bug.
