### ISSUE TITLE
Create Invite Programmatically with base64 encrypted string fils to SEND

### ISSUE THREAD

**Issue by kanaksony** [OfficeDev/office-js#543]
I am developing an Outlook addin. This addin helps in pre-populating pre-defined invitation template wth some meeting URL, now we changed tis URL to base64 encrypted string like -

http://www.myurl.com/NTA1MDo4OTg5QGNvbnhtZS5uZXQ=/Kanak

## Expected Behavior
I should be able to SEND the invite with this invitation text from OWA and Windows and Mac clients both.

## Current Behavior
MAC Client - Sends the invite fine.
Windows client - Sends the invite well.
OWA - After clicking SEND button - Spinner starts showing and mail is never sent. When I INSPECT the OWA, there are lots of errors in console.

## Steps to Reproduce, or Live Example
1. Side load the app via https://urlzs.com/iJmtA
2. Go to Plugin Icon - Open and fill Settings - some dummy info.
3. When Save - it encrypts the URL.
4. Now, Schedule Meeting from Plugin will Open Meeting with pre-populated URL from #3.
5. Click on Send. Observe mail not being sent and errors in Console.

* Additional details: Screenshot

![Screen Shot 2019-06-04 at 12 26 47 AM](https://user-images.githubusercontent.com/6097596/58827065-c2d0f500-865f-11e9-9eee-270b56f5111d.png)

## Context
Mail-Select any EMail-Click on AddIn-Schedule Meeting

## Your Environment

* Platform  : OWA
* Host : Outlook
* Office version number: 16.22 (190211)
* Operating System: Windows and Mac both
* Browser (if using Office Online): Chrome

## Useful logs: Console logs
Failed to load resource: the server responded with a status of 404 ()
browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=AWT-Web-JS-1.8.1&x-apikey=a387cfcf60114a43a7699f9fbb49289e-9bceb9fe-1c06-460f-96c5-6a0b247358bc-7238&client-time-epoch-millis=1559581795668&time-delta-to-apply-millis=142:1 Failed to load resource: the server responded with a status of 403 (All records were throttled.)
lpcres.delve.office.com/lpc/versionless/livepersonacard_with-react_2b4871b5d9817cc223c6.js:16 Some icons were re-registered. Applications should only call registerIcons for any given icon once. Redefining what an icon is may have unintended consequences. Duplicates include: 
GlobalNavButton, ChevronDown, ChevronUp, Edit, Add, Cancel, More, Settings, Mail, Filter (+ 297 more)
r @ lpcres.delve.office.com/lpc/versionless/livepersonacard_with-react_2b4871b5d9817cc223c6.js:16
/owa/service.svc?action=CreateCalendarEvent&n=47&app=Calendar:1 Failed to load resource: the server responded with a status of 500 ()
2ow2.res.office365.com/owamail/2019052703.04/scripts/owa.calendardeeplink.js:87 Uncaught (in promise) Error: CreateCalendarEvent failed: Microsoft.Exchange.Clients.Owa2.Server.Core.OwaSerializationException
    at a (ow2.res.office365.com/owamail/2019052703.04/scripts/owa.calendardeeplink.js:87)
    at ow2.res.office365.com/owamail/2019052703.04/scripts/owa.calendardeeplink.js:87
    at Object.t.default (ow2.res.office365.com/owamail/2019052703.04/scripts/owa.calendardeeplink.js:87)
    at ow2.res.office365.com/owamail/2019052703.04/scripts/owa.calendardeeplink.js:72
    at ow2.res.office365.com/owamail/2019052703.04/scripts/owa.calendardeeplink.js:104
    at ow2.res.office365.com/owamail/2019052703.04/scripts/owa.calendardeeplink.js:72
    at i (ow2.res.office365.com/owamail/2019052703.04/scripts/owa.calendardeeplink.js:72)
    at t.promiseMiddleware (ow2.res.office365.com/owamail/2019052703.04/scripts/owa.calendardeeplink.js:72)
    at ow2.res.office365.com/owamail/2019052703.04/scripts/owa.calendardeeplink.js:72
    at t.stitch (ow2.res.office365.com/owamail/2019052703.04/scripts/owa.calendardeeplink.js:104)
/ows/v1.0/FloodGateSurvey/SurveyActivationStats?n=50&cv=AxC42WxqBT47WgaQKD24KN.50:1 Failed to load resource: the server responded with a status of 404 ()
browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=AWT-Web-JS-1.8.0&x-apikey=a387cfcf60114a43a7699f9fbb49289e-9bceb9fe-1c06-460f-96c5-6a0b247358bc-7238&client-time-epoch-millis=1559581898835&time-delta-to-apply-millis=17:1 Failed to load resource: the server responded with a status of 403 (All records were throttled.)
browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=AWT-Web-JS-1.8.0&x-apikey=a387cfcf60114a43a7699f9fbb49289e-9bceb9fe-1c06-460f-96c5-6a0b247358bc-7238&client-time-epoch-millis=1559581898736&time-delta-to-apply-millis=12:1 Failed to load resource: the server responded with a status of 403 (All records were throttled.)
browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application%2Fbond-compact-binary&client-id=NO_AUTH&sdk-version=AWT-Web-JS-1.8.1&x-apikey=a387cfcf60114a43a7699f9fbb49289e-9bceb9fe-1c06-460f-96c5-6a0b247358bc-7238&client-time-epoch-millis=1559582035670&time-delta-to-apply-millis=142:1 Failed to load resource: the server responded with a status of 403 (All records were throttled.)

**Comment by exextoc** [comment]
@kanaksony Are you using old OWA or new OWA?

**Comment by exextoc** [comment]
We are able to reproduce this issue when we try action "Schedule a Meeting" from any mail item. Thanks for reporting this issue regarding saving/sending calendar invite with your ConX addin. It has been put on our backlog. We unfortunately have no timelines to share at this point.

Note: We tried using the addin by freshly creating new calendar invite and this works fine. Steps for this:
1. Create new calendar invite.
2. Click on ConX addin from menu. UI-less addin runs and adds meeting detais.
3. Send meeting invite. This works.

**Comment by kanaksony** [comment]
Hi @exextoc thanks for the confirmation. We are developing this plugin for Foxconn. 

This is one of main functionality in our Addin. And this is something broken that must be fixed.

This is so unfortunate we have couple of issues reported during development recently and we get --  no timelines to share at this point :(.

Can you suggest me any workaround? We need to deliver this to my client.

**Comment by exextoc** [comment]
@kanaksony I understand the situation and really apologize for this. I am working with engineering if we can resolve this issue asap. Also, we are checking if we can provide any workaround for this.

You mentioned "couple of issues reported during development recently".  I found one issue: https://github.com/OfficeDev/office-js/issues/498 . Can you please help me with listing them here? I wanted to check if I can help you with prioritizing those as well.

**Comment by kanaksony** [comment]
Please Please do the needful. 

I am listing the important issues here, that we really want and request you to fix to deliver my project to client successfully:

1. https://github.com/OfficeDev/office-js/issues/543
2. https://github.com/OfficeDev/office-js/issues/430
3. https://github.com/OfficeDev/office-js/issues/498

**Comment by exextoc** [comment]
Thanks @kanaksony. I am looking into their status.

**Comment by exextoc** [comment]
Hi @kanaksony we are actively working on a solution. We see that your add-in in not available any more, could you please host it again? It will speed up our testing process. Thanks.

**Comment by kanaksony** [comment]
Hey @exextoc Thanks for the update. Please try https://mop.infocus.net:3000/infocus-conx-outlook-addin.xml

**Comment by exextoc** [comment]
Hi @kanaksony, we have fixed the bug and the fix should be available within 2-3 weeks.

**Comment by kanaksony** [comment]
Thanks for the update, please let me know when its out.

**Comment by exextoc** [comment]
Hi @kanaksony it should be available in production, apologies for the delayed response.
