### ISSUE TITLE
AppDomain can use First-level domain name

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#544]
hi

in office add-in xml. i use 
` <AppDomains>
    <AppDomain>mydomain.com</AppDomain>
 </AppDomains>
`
i can not open  https://api.mydomain.com

but i use 
`<AppDomains>
     <AppDomain>https://api.mydomain.com</AppDomain>
   <AppDomain>https://www.mydomain.com</AppDomain>
</AppDomains>`

it's ok.

if i want a xxx.mydomain.com, i need to add in appdomains?

**Comment by Rick-Kirkham** [comment]
The subdomain is part of a domain, so `xxx.mydomain.com` is a different domain from both `yyy.mydomain.com` and `mydomain.com`.

**Comment by lumine2008** [comment]
Hello, @dinglicoding, 

Could you please share more information about your scenarios? 

If you would like to jump from main domain to sub domain, you have 2 solutions:
1) if you know each subdomains, you could add each of your subdomain in to the manifest <AppDomains> session
2) another solution is server redirection. you can use when the sub domain is dynamically changing. so you could use the href="https://xxx.mydomain.com" to jump.  it enable you to jump from mydomain.com to xxx.mydomain.com. 


Thanks, 
Raymond

**Comment by dinglicoding** [comment]
hello @lumine2008 

the subdomain is part of a domain. so if one day i need a subdomain, so i need to add it to 

`<AppDomains>` and republish my excel add-in xml to office store. so it's Wasting time。 

subdomain is a different domain,but they all under the domain of mine.

**Comment by lumine2008** [comment]
Hello @dinglicoding, so you would like to dynamically changing the subdomain. if in this case, then you could use server redirection solution, by changing the sourcelocation to the maindomain, and use  href="https://xxx.mydomain.com" to jump.
