### ISSUE TITLE
Heavy usage of suspendScreenUpdatingUntilNextSync() causes Add-in Panel to blink

### ISSUE THREAD

**Issue by misaunde** [OfficeDev/office-js#545]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Product
Excel

## Feedback
I was really excited to try out `suspendScreenUpdatingUntilNextSync()` and so I went to one of my add-ins that does quite a bit of writing (writes out 10-15 sheets of 1k to 15k rows each), and initially I just sprinkled in `(<any> ctx.application).suspendScreenUpdatingUntilNextSync()` all over the place. I mostly put it everywhere I already had `ctx.application.suspendApiCalculationUntilNextSync();`, but the first thing I noticed is that when I ran the tool, the entire add-in website/panel was blinking the whole time. 

I'm used to excel itself blinking quite a bit while it's writing data, but I've never seen the add panel blink before, and it didn't seem like expected behavior to me, so I thought I'd report it.

Here's a gif of the bottom right corner demonstrating the entire panel blinking. At first I thought the add-in was just shutting down, but it kept coming back:
![excelblinking](https://user-images.githubusercontent.com/10051350/51874054-a40eca80-231c-11e9-8f39-958bfc94d1fe.gif)

Next, I hit undo to remove all those lines of code, ran it again, and it ran as expected without blinking.

After that, I added it back, but just to where I write the biggest chunk of data, and I turned off batching so it would write everything out at once (how I would assume this method was intended to be used) and called `suspendScreenUpdatingUntilNextSync()` just a single time.
When it ran this time, you almost couldn't notice any blinking at all, but I noticed very small blinks on a few of the sheets even still. Some of them were so small/quick you'd probably miss them if you weren't looking for them.

Anyways, just a heads up.

**Comment by kbrandl** [comment]
@misaunde apologies for the slow response, looked like this issue has been overlooked in OfficeDev/office-js until now. @tutieu is this something that you or someone on your team can investigate? Thanks!

**Comment by chanhohang** [comment]
@kbrandl can we get an update of this issue? my add-in encounters the same problem for the screen flickering in the taskpane as well.

**Comment by kbrandl** [comment]
@tutieu can you please follow up on this issue (or assign to someone else on your team to follow up)? Thanks!

**Comment by lumine2008** [comment]
Thanks @chanhohang, for your post, and apologize for the delay,
it seems that we are not able to repro this issue in our side. could you please share with us the gist or code sample for us to repro this issue? therefore we can locate the root cause.

**Comment by chanhohang** [comment]
@lumine2008 thanks for looking after this issue.

So the environment to reproduce it is Excel Application Office 365 pro plus and run on windows 10.

The Excel API will be 1.10 for this combination. and the underlying browser should be Edge running inside the Excel Process.

Our Code is similar to below. 
it's called inside Excel.run( { delayForCellEdit: true }, async context =>{ // Method below})
```
   if (Office.context.requirements.isSetSupported('ExcelApi', '1.9')) {
       context.application.suspendScreenUpdatingUntilNextSync()
    }
    for (let i = 0; i < updateStream.rowUpdates.length; i++) {
      let rowUpdate = updateStream.rowUpdates[i]
      let actionType = rowUpdate.actionType
      let rowIndex = this.findRowIndex(rowUpdate, rowIdColumn)
      // New Row in Table
      if (actionType === 'CREATE') {
        let values = this.getRowValues(
          this.columns,
          rowUpdate.cells,
          rowUpdate.rowId
        )
        newRows.push(values)
      } else if (rowUpdate.actionType === 'UPDATE') {
        let tableRow = tableRows.items[rowIndex]
        let range = tableRow.getRange()
        if (range !== null) {
          // Handle Update
        } else {
          throw new Error(
            `${rowIndex} is not availalbe for ${rowIdColumn.values}`
          )
        }
      } else if (rowUpdate.actionType === 'DELETE') {
        let tableRow = tableRows.items[rowIndex]
        tableRow.delete()
      }
    }
    if (newRows.length > 0) {
      this.lastValues = newRows
      tableRows.add(null, this.lastValues)
    }

    let excelSort = table.sort
    if (excelSort !== null) {
      excelSort.reapply()
    }
    table.reapplyFilters()
    await context.sync()
```

I am sorry I am not providing the full source code for your references. but i am open for further discussion if needed.

**Comment by lumine2008** [comment]
Thanks @chanhohang , the sample code is useful, our team has repro this issue, a bug3943969 is created to track this issue. Thanks again for your support

**Comment by lumine2008** [comment]
Thanks @chanhohang, our team has done the investigation on this issue. we found that this is by design, 
because our code will redraw all (include Ribbon, Grid, Addin panel) when writing data.
 
This API is designed to improve performance. If this API is called, then it won’t redraw all during writing data, only updated related Addin panel. After writing finished, we will redraw all once.

So our suggestion would be not to use this API in a loop.

**Comment by erharvey** [comment]
Hi, is there any plan to consider letting better controls on "when" the redraw is done the same way we can control if events are enabled on not? (ctx.runtime.enableEvents = false / true;)

The experience would not look as bad if we had only a single flicker during the rendering process. The API does indeed improve the performance a great deal for us and it would be great if it could be improved.

**Comment by ElizabethSamuel-MSFT** [comment]
@JinghuiMS Can you take a look and reassign as appropriate? Thanks.

**Comment by JinghuiMS** [comment]
The similar issue with https://github.com/OfficeDev/office-js/issues/2734

**Comment by wh1t3cAt1k** [comment]
We just had a complaint about the screen flicker in a piece of a long-operation logic that necessarily needs to do a lot of `sync()` calls.

There is no way we could disable `screenUpdating` until the end of `Excel.run`, not the next sync(), which would completely solve our situation.

Is it super technically difficult to expose a new method in the API since you already have `suspendScreenUpdatingUntilNextSync()`, like `suspendScreenUpdatingUntilEndOfRun()` or simply a setter like `application.screenUpdating` that would automatically reset at the end of the `run()`? 

I would imagine it would reuse the same infrastructure. It would make a big difference to customers' perception of our product.

**Comment by wh1t3cAt1k** [comment]
@gergzk @JinghuiMS I regret to see this has been closed without any comment.

This is a real UX problem, moreover and the underlying host application infrastructure is already implemented.

`context.runtime.enableEvents` is already exposed, I really urge you to implement the same for `screenUpdating`, which is easily available for VBA.
