### ISSUE TITLE
API 1.4: Document.open function

### ISSUE THREAD

**Issue by makzr** [OfficeDev/office-js#546]
I 'm playing around with the new api version 1.4 (beta).
I'm wondering how I can use the new open function (https://github.com/OfficeDev/office-js-docs/blob/WordJs_1.4_OpenSpec/reference/word/document.md#open)?

I tried this but it doesn't work:
```
    function openDocument(fileBase64) {
        Word.run(function (context) {
            return context.sync().then(function () {
                var wordDocument = context.application.createDocument(fileBase64);
                if (wordDocument) {
                    //context.load(wordDocument, 'open');
                    wordDocument.open();
                }
            }).then(context.sync);
        }).catch(errorHandler);
    }
```

Actually the createDocument function returns a Document object! However I cannot open it :(
I get an error "Invalid Argument".

How is it intended to work?

**Comment by JuaneloJuanelo** [comment]
@makzr  hello and thanks for the question, I noticed you opened this issue long time ago, this is supposed to be working on the latest Office updates, hopefully you can try it and let us know? if hyou can repro please add the office build you are using.

btw the documentation was moved to here https://docs.microsoft.com/en-us/javascript/api/word_release/word.application?view=office-js#createdocument-base64file-

and you can also restore this sample in Script Lab to try it.
https://gist.github.com/JuaneloJuanelo/0d8c5fbad8ca2147c88843daad891a4e

**Comment by JuaneloJuanelo** [comment]
We'll close this item as sample was provided and the behavior described cannot be reproduced any  more.
