### ISSUE TITLE
[excel] when set Requirements  my Ribbon Button can not display

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#547]
hello

my excel add-in use textbox. it's required  ExcelApi 1.9 ,so i add a Requirement in xml.

![image](https://user-images.githubusercontent.com/3963826/59003686-8d87fb00-8849-11e9-9526-c048ee1ce290.png)

so in office add-ins=> admin managed , i add my add-in . it's can not display my ribbon button , but it can show TaskPane. 

i removed the Requirements,it's display ok.

my excel version is 
![image](https://user-images.githubusercontent.com/3963826/59003897-5108cf00-884a-11e9-9784-d18299859ba9.png)

it's any wrong with my code of xml?

**Comment by lumine2008** [comment]
Thanks @dinglicoding, 

Out current design for the requirement set is not apply to textbox, therefore.please specify “ExcelApi” requirement set, instead of the “TextBox”. 

Thanks,
Raymond

**Comment by dinglicoding** [comment]
Thanks @lumine2008 

i replace TextBox to TableBindings, it's can not dislpay my ribbon button too.

**Comment by kbrandl** [comment]
Closing this issue, as it seems that @lumine2008 provided info that answers the question.
