### ISSUE TITLE
[excel] my add-in not support by my internet explorer

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#548]
hello

my add-in in TaskPane show error . how to check my add-in support the version of internet explorer?

![image](https://user-images.githubusercontent.com/3963826/59004356-f1132800-884b-11e9-91da-037593c8e457.png)

![image](https://user-images.githubusercontent.com/3963826/59005379-d8a50c80-884f-11e9-9aab-8d022c3cfa3a.png)

![image](https://user-images.githubusercontent.com/3963826/59005386-de025700-884f-11e9-953c-bc1ee65fd3b6.png)

**Comment by lumine2008** [comment]
Hello, @dinglicoding 
here is the information about which browser is used for the various platforms and operating systems.
https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

**Comment by dinglicoding** [comment]
Thanks @lumine2008   

it seems my browser is  fulfil requirements.

**Comment by kbrandl** [comment]
@dinglicoding did the information that @lumine2008 provided unblock you, or do you still need help with this issue?
