### ISSUE TITLE
[excel] Table onChanged, cell font color can not changed

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#549]
hello

table onChanged can not changed when i changed a cell value , it's can not changed , but mouse move to TaskPane ,it's changed.

see video,thanks

[Excel 2019-06-06 18-05-03.zip](https://github.com/OfficeDev/office-js/files/3261072/Excel.2019-06-06.18-05-03.zip)

**Comment by lumine2008** [comment]
Thanks @dinglicoding , could you please try to change the cell and don't move the mouse? onChange should not be related to mouse action. I guess the performance is slow. then feels like it changed when mouse move

**Comment by kbrandl** [comment]
@dinglicoding does @lumine2008's feedback effectively resolve this issue?
