### ISSUE TITLE
chart.getImage() on Mac issue - image is offset or blank

### ISSUE THREAD

**Issue by Andrew-AnalysisPlace** [OfficeDev/office-js#55]
I use chartObject.getImage() to get images of Excel charts so they can be displayed in Word and PowerPoint. I have been doing this for months and it works great on Office for Windows. I recently discovered (via customer complaints) that there are issues when getImage is done on Excel for Mac.
getImage() in Excel for Mac always seems to offset the chart image. Often the chart is not visible at all (image is all white).
I've tried changing the height, width, and fittingMode (Fit, FitAndCenter, Fill) parameters and nothing seems to fix the issue.
The further the chart is from the top-left of the sheet, the more offset the image is. So, if you put the image around f20, then you'll only see the bottom-right corner of the chart.  If the chart is further down or right, the image does not appear at all (all white).

## Expected Behavior
Works same on Mac as it does on Windows.

## Current Behavior
Image is offset.  Only partially appears depending on chart placement on sheet.

## Steps to Reproduce, or Live Example
Code and steps to repro are here: https://stackoverflow.com/questions/48412900/excel-office-js-chart-getimage-on-mac-issue

## Context
Customers use my Store add-in to transfer charts from Excel to Word or PowerPoint.  This issues interferes with their ability to do so on Macs 

## Your Environment

I think the issue has been occurring for months, but I just thought it was user error.  So, I don't think it is just recent versions of Office for Mac.
I currently have Office for Mac version 1609 (180109)
Host : Excel
I have never had the issue on Windows.

**Comment by codexeon** [comment]
This will be fixed in the 16.10 February release of Mac Excel.

**Comment by Andrew-AnalysisPlace** [comment]
I tested and It has been fixed in 16.10.
