### ISSUE TITLE
[excel] show dialog take too long time-

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#550]
hello

use ExecuteFunction and use Office.context.ui.displayDialogAsync to show a dialog. it take a long time to show.

use TaskPane and use Office.context.ui.displayDialogAsync to show a dialog , it's not too slowly.

why?

thanks

**Comment by lumine2008** [comment]
Hi @dinglicoding 
Thanks for your message,  we would like to know more about it. could you please share us your sample code? therefore I can verify it in my side.

**Comment by dmahugh** [comment]
Closing due to one month of inactivity and no repro.
