### ISSUE TITLE
Duplicate Table Name Issues

### ISSUE THREAD

**Issue by misaunde** [OfficeDev/office-js#551]
Trying to create a 2nd table using the same name as a previously created table yields a very vague and confusing error message:
`"The argument is invalid or missing or has an incorrect format."`

You can reproduce this in Script Lab, in the "Table collection events" script, by changing both table names to be the same in the `createSalesTable` and `createReturnsTable` functions:
![image](https://user-images.githubusercontent.com/10051350/59052055-764a0d00-884b-11e9-809a-57f24c2dec0b.png)

**First Request:**
I can understand why you would want table names to be unique within a sheet, but I wonder if that error message could be improved as it took me a while to identify I was having a problem related to duplicate table names.

**Second Request:**
Since tables are tied to a specific sheet, I didn't anticipate running into the issue of having the same table name on 2 different sheets being a problem and failing with the same error message. I found this confusing as the tables appear to be nested under a specific sheet object, so why should there be collisions outside of that sheet? Any chance they could be isolated to each sheet?

You can recreate this in the same file, by adding this code in the setup() function:
![image](https://user-images.githubusercontent.com/10051350/59052428-52d39200-884c-11e9-8643-be238b454dec.png)

**Workaround:**
Since I only create one table per sheet (even though it happens to be the same table in function at least to the user) I can mostly solve this by creating tables names that are made unique by appending the current sheetname ( `mytable.name = 'mytable_' + <current sheet name>`).

However, this still isn't bullet proof as sheet names can be long and unwieldy and also crash this name assignment with the same exact error...

## Expected Behavior

I would expect there to be naming collisions on the same sheet, but I wouldn't expect there to be naming collisions across sheets in the same workbook. I would expect sheet names to be isolated to each sheet. This is what I originally inferred based on the semantics of the code `sheet.tables.add("A1:E1", true)` and what made it harder to realize this was actually my issue.

## Current Behavior

Currently, it looks like all table names must be unique across an entire workbook.

## Steps to Reproduce, or Live Example

* Link to live example: ______

## Context

Use Case:
Our users of this particular tool have a sheet of data that they are preparing to submit into another system. After some initial work, a phase of this tool validates the data on their current sheet. These are often large datasets with wide ranges of validation issues and to make things easier for the user we output a validation table column at the very end of their dataset which we write errors inside of. Then, in the UI, they can click a button on a specific error and (since we're using a table as our last column) we can filter down to only the offending rows enabling them to find and fix things quicker.

Until I realized this issue, our challenge was we were creating the same validation table column (same name) on multiple sheets and it would fail due to this issue providing only the error message above.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: __pc____
* Host [Excel, Word, PowerPoint, etc.]: ____Excel O365__
* Office version number: ___1808___
* Operating System: ___Windows 10___
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lumine2008** [comment]
Thanks @misaunde for reporting to us the information. I just repro the issue in my side. 
1# Agree with you, we need to think about to improve the error message to let developer know what's happen. 
2# yes, all table names are unique across an entire workbook is our current design. agree this is a bit confusing, we should need to think about how to improve the error message for this as well. 

Thanks for bringing this issue to our attention.
