### ISSUE TITLE
Custom functions that return dynamic arrays return #VALUE if 2 or more are evaluated at the same time

### ISSUE THREAD

**Issue by slowkoala** [OfficeDev/office-js#553]
We have a custom function that returns an array.  With PC Office, if you have more than 1 in your workbook and you trigger a refresh by setting the cell's formula property to itself, it will return `#VALUE`.  This works fine with Office Online.  This also works with PC Office if you use the formula in an array formula (with control-shift-enter) or use `=@` instead of just `=`

## Expected Behavior
All custom formulas would refresh and show the correct value.

## Current Behavior
Custom formulas that use dynamic arrays return #VALUE if more than 1 are evaluated at the same time.

## Steps to Reproduce, or Live Example
  1.  Use this gist to create a custom formula that outputs an array - https://gist.github.com/slowkoala/fe12994040ca0824d7950d9714deef19
  2.  Enter the formula `=SCRIPTLAB.CUSTOMARRAYFORMULA.ADD10(1)` and `=SCRIPTLAB.CUSTOMARRAYFORMULA.ADD10(2)` in your workbook.  See that they evaluate correctly.
  3.  Run this gist to trigger a recalculation of the formulas - https://gist.github.com/slowkoala/752fbe197cab6132fc5f274212a0d6e9
  4.  See that they both show `#VALUE`

* Additional details:
  1. This only happens in PC Office, not Office Online
  2. If you manually enter the formula as an array formula, or prefix it with `=@` then it works fine

## Context
  1. We want to create a way to force custom formulas to get re-evaluated, and this approach works with Office Online but not PC Office.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.11722.20008
* Operating System: Windows 10

## Useful logs

- [X] Screenshots
![image](https://user-images.githubusercontent.com/48524800/59222978-d1a43400-8b98-11e9-8b73-65256f17ddef.png)
![image](https://user-images.githubusercontent.com/48524800/59223058-0617f000-8b99-11e9-90cf-b380f202594b.png)

**Comment by keyur32** [comment]
Hey there! Yes this is an active bug we have on *insiders* channel that has Excel Dynamic Arrays enabled. Team is currently investigating a fix, which will be made before Dynamic Arrays gets enabled.  End users on the Monthly channel will not hit this issue as they correctly evaluate there.

**Comment by hjkim-MSFT** [comment]
To work around this problem, you can use Range.calculate method instead of assigning array of formulas to recalc.

    async function run() {
      await Excel.run(async (context) => {
        const sheet = context.workbook.worksheets.getActiveWorksheet();

        const used = sheet.getUsedRange();
        used.calculate();
        await context.sync();
      });
    }

You can try this by importing this snippet https://gist.github.com/hjkim71/9bf56bd94566755a105896a64c9273eb into Script Lab (http://aka.ms/getscriptlab).

**Comment by slowkoala** [comment]
@hjkim71 thanks, that works!

**Comment by dmahugh** [comment]
Closing issue because there is a workaround and the fix is being handled so won't hit the monthly channel as Keyur noted above.

**Comment by keyur32** [comment]
Hi,  this has now been fixed.  It is available on Insiders channel, and will roll out to production as part of the "August Update"

**Comment by Tolli** [comment]
Hi, I am seeing this error, has this bug resurfaced perhaps?
