### ISSUE TITLE
getBase64ImageSrc() returns undefined on Word IPad

### ISSUE THREAD

**Issue by saferoombiz** [OfficeDev/office-js#56]
## Steps to Reproduce, or Live Example
```
Word.run(function (context) {
        // Getting the selected range
        var range = context.document.getSelection();

        // Getting the image from the selected range
        var picture = range.inlinePictures.getFirstOrNullObject();
        context.load(picture);

        // Loading the image properties so we can access it later
        return context.sync().then(function () {                
            var picbase64 = picture.getBase64ImageSrc();
            return context.sync().then(function () {                    
                console.log("Base64 string is " + picbase64.value);                    
            }); 

        });
})
```

* Additional details:
  1. https://stackoverflow.com/questions/48423914/how-to-get-a-base64-representation-of-a-selected-image-in-word-for-ipad
  
## Context
I am having a problem with getting the selected image on Word iPad within the Addin I am developing. This code above works perfectly in Word for Windows, Word Online and Word for Mac, but it doesn't work with Word for iPad. I get the following error:

> Base64 string is undefined

Having investigating further, I've found out that apparently Word for iPad interprets the selected image in a different way (not as InlinePicture). So, the question is how can I get a base64 representation of a selected image in Word for iPad?

One note - the image I am trying to access is inserted by Word. When I insert image (**InlinePicture**) programmatically, I can access it without any problems.

## Your Environment
* Platform: **iOS IPad**
* Host: **Word**
* Office version number: **2.5 (170904)**
* Operating System: **iOS**

**Comment by kbrandl** [comment]
@saferoombiz -- thank you for reporting this issue.  (@JuaneloJuanelo -- can you please look into this potential issue with the API and respond to the customer?)

**Comment by JuaneloJuanelo** [comment]
hello we are investigating this issue. thanks!

**Comment by saferoombiz** [comment]
Hi, any updates? :)
We're working on the Encryption AddIn for Microsoft Word and this bug is a stopper for us because we cannot put the Addin into Office store without having it operational on all platforms. 

Thanks in advance

**Comment by mlafleur** [comment]
While not a solution to the underlying problem, you _can_ publish an Add-in to the Store without supporting iPad by unchecking the `Make this add-in available in the Office add-in catalog on iOS` option in the [Seller Dashboard](https://sellerdashboard.microsoft.com/ ).

**Comment by JuaneloJuanelo** [comment]
The original hypothesis from @saferoombiz is correct. When you insert an image in Word for iPad by default is a floating image, not an inlinePicture.  So the description here is by design.  Floating images is a known gap on the API and recognized in the backlog, although a clear date is unknown at the moment.  Please create or upvote https://officespdev.uservoice.com
