### ISSUE TITLE
sheet.unprotect API not working in online office365

### ISSUE THREAD

**Issue by px-wmeng** [OfficeDev/office-js#560]
We are using the api sheet.unprotect(password) function to unprotect a workheet, it has been working fine, but now it throws error with the latest office-js library. The issue only happens in the browser for the online excel(office365), my installed office365 works fine. This issue can be reproduce in Script Lab as well.

## Expected Behavior

worksheet unprotect

## Current Behavior

there is an error throws when sheet.unprotect(pwd) get called

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: _____
* Operating System: Windows
* Browser (if using Office Online): Issue reproducible in any browser(Chrome, IE, Edge, Fireox)

## Useful logs

- [ ] Console errors
- [ 
![UproctectWorksheet](https://user-images.githubusercontent.com/41589574/59542269-f9fe9c00-8ed2-11e9-994a-090103544dbb.PNG)
] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by grangeryy** [comment]
Thanks for reporting the issue, @wei6100 . We also found the problem and we're under investigation. bug 3431640 is created to track it.

**Comment by grangeryy** [comment]
This bug is fixed.
