### ISSUE TITLE
Calling getSelectedRange (querying further Range properties) inside onSelectionChanged event handler leads to General Exception

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js#562]
## Expected Behavior

We should be able to getSelectedRange and query for its properties without any restriction inside onSelectionChanged event and moreover, the event should be fired immediately after changing the cell selection.
## Current Behavior

We see "GeneralException: An Internal error has occured" from time to time which causes that our onSelectionChanged handler stops working.
Also the event handler is having big delay quite frequently (2-3 seconds), see https://github.com/OfficeDev/office-js/issues/533 
## Steps to Reproduce, or Live Example
Attached is zip file with index.html and the script (with console window) you can add to any of your existing addin. It should be easily reproducible if you start quickly changing selections in the excel. We tried various onSelectionChanged events but the behavior is same no matter if we try workbook.onSelectionChanged,  context.workbook.worksheets.onSelectionChanged or context.workbook.worksheets.getActiveWorksheet().onSelectionChanged
Also note that in Script Lab it works fine as I've never seen issues with the events there (I guess there are some internal tweaks?).
If this is not sufficient, just let me know.

## Context

We want to render UI based on the content in cell (value/formula) but this blocks us.

## Your Environment

Desktop Excel on Windows 10, monthly channel, Version 1905 (build 11629.20246)

## Useful logs

Call stack of the exception:
` Cannot get Formula from cell - {"description":"An internal error has occurred.","name":"RichApi.Error","code":"GeneralException","traceMessages":[],"innerError":null,"debugInfo":{"code":"GeneralException","message":"An internal error has occurred."},"stack":"GeneralException: An internal error has occurred.\n at Anonymous function (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:24:274160)\n at T (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:24:212677)\n at x (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:24:212763)\n at t (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:24:212571)\n at l (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-win32-16.01.js:24:211078)"}`

Sample:
[sample.ZIP](https://github.com/OfficeDev/office-js/files/3297662/sample.ZIP)

**Comment by 4tti** [comment]
[sample.ZIP](https://github.com/OfficeDev/office-js/files/3297654/sample.ZIP)

**Comment by RuoyingLiang** [comment]
Thanks for reporting the issue. We are looking at it. Will reply after our investigation.

**Comment by RuoyingLiang** [comment]
Close this issue. Please reopen if you can still repro.
