### ISSUE TITLE
Office.context.auth.getAccessTokenAsync reply url issue with 57fb890c-0dab-4253-a5e0-7188c88b2bb4

### ISSUE THREAD

**Issue by plamenxpenchev** [OfficeDev/office-js#563]
## Expected Behavior
The `Office.context.auth.getAccessTokenAsync` method of the Office Javascript API invoked in Word Online to return an SSO token, that is to be exchanged for a graph one via the OBO flow.

## Current Behavior
Hitting the following issue with the (_Azure Enterprise_) Application with ID `57fb890c-0dab-4253-a5e0-7188c88b2bb4` (which as documented is **Office Online**, or more specifically **SharePoint Online Client** as named in the Azure portal):

![office-online-reply-url-err](https://user-images.githubusercontent.com/36263058/59657365-294e2b00-91a9-11e9-86e4-6a868c39d848.png)

Obviously, this application is outside of my control to add reply urls.

## Steps to Reproduce, or Live Example
  1. All the steps detailed in https://docs.microsoft.com/en-us/office/dev/add-ins/develop/register-sso-add-in-aad-v2 were thoroughly followed.
  2. The preview (_beta_) version of the Office API was used (vain attempts were also made against the latest versions of the `@microsoft/office-js package`).
  3. All the suggestions, stemming from a similar issue OfficeDev/Office-Add-in-ASPNET-SSO#23 were also thoroughly followed, namely:
      - Making an exact match between **add-in manifest scopes** & **Azure app permissions**.
      - All requested permissions have been **consented to**.
      - **Sideloading** the addin manifest, instead of uploading it via Sharepoint's Apps for Office (_the same issue is encountered_).

## Context
The issue is a major blocker for the add-in, as no interaction with OneDrive is possible in Word Online. Do note that this issue is **not reproducible** in the **desktop version** of Word.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Office (Word) Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: Windows 10 and Ubuntu 16.04
* Browser (if using Office Online): Irrespective of browser

## Useful logs

- [x] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by niteshgolchha85** [comment]
@plamenxpenchev Sorry that you are facing this issue but let me clarify first that the SSO API is in-preview so nothing should be blocked. You should use Dialog API instead in production
Coming to the issue that you are seeing - can you attach fiddler traces and share the domain on which you are seeing this issue (SharePoint probably)?

**Comment by niteshgolchha85** [comment]
Also, can you confirm that you used ForceConsent = true?

**Comment by plamenxpenchev** [comment]
@niteshgolchha85 Thank you for the response. Yes, forceConsent was attempted. And thank you for the suggestion. The code-grant flow worked as expected with `Office.context.ui.displayDialogAsync`.

**Comment by niteshgolchha85** [comment]
@plamenxpenchev Can you share your fiddler traces? I'd still like to get to the bottom of this issue.

**Comment by niteshgolchha85** [comment]
Closing as there is no response for a month. Please re-open if you face this issue again.
