### ISSUE TITLE
Excel API stopped working when DOM storage is disabled.

### ISSUE THREAD

**Issue by ndreisg** [OfficeDev/office-js#564]
When using Office 2016 installed via MSI and DOM storage is disabled in Internet Explorer, Excel Add-Ins are not working anymore because office.js can't be initialized.

## Expected Behavior
office-js should also work when DOM storage is disabled.

## Current Behavior
When using Office 2016 installed via MSI and DOM storage is disabled in Internet Explorer, Excel Add-Ins are not working anymore because office.js can't be initialized.
This problem appeared recently, a few months ago it was still working without DOM storage.

Following error occurs:

```
Unable to get property 'getItem' of undefined or null reference
excel-win32-16.01.debug.js (15526,3)
```

The same Add-In is working in Word.

I'm not sure if it is actually possible to disable the DOM storage in the Edge Browser, but if it is possible this error may occur in newer Office versions as well.

## Steps to Reproduce, or Live Example
  1. Use Office 2016 installed via MSI (or any Office installation that still uses Internet Explorer to display the Add-Ins)
  2. Disable DOM storage in Internet Explorer
  3. Insert any Add-In

## Your Environment
* Platform: PC desktop
* Host: Excel
* Office version number: 16.0.4849.1000
* Operating System: Windows

## Useful logs
```
Unable to get property 'getItem' of undefined or null reference
excel-win32-16.01.debug.js (15526,3)
```

**Comment by ndreisg** [comment]
A question btw: will the new Edge WebView control also come to Office 2016?

**Comment by kbrandl** [comment]
@ndreisg apologies for the slow response, looks like this issue has been overlooked until now. Are you still having this issue (with newer builds of Office)? 

Adding @tutieu to investigate the issue you've reported with Excel, and @jargil to respond to your question about whether or not Edge WebView control will also come to Office 2016.

**Comment by ndreisg** [comment]
@kbrandl Yes I'm still facing this issue. But my version number is still 16.0.4849.1000.  I didn't get a newer version after installing Windows updates.

**Comment by kbrandl** [comment]
@ndreisg thanks for confirming. @tutieu are you able to assist with this issue? Thanks!

**Comment by lumine2008** [comment]
Hello @ndreisg, can you repro now, i just have a try in my side, looks not repro it anymore. please let me know if you still be able to repro, and kindly share me your gist/snippet?

**Comment by kbrandl** [comment]
@lumine2008 FYI, looks like the end of your previous comment is missing something at the end of it. Can you please edit that comment to indicate what info you'd like@ndreisg to provide?

**Comment by ndreisg** [comment]
@lumine2008 I'm getting another error now. The `Excel` object is undefined:

    if (Office.context.requirements.isSetSupported("ExcelApi", "1.1")) {
      Excel.run(function(context) {  // --> Unable to get property 'run' of undefined or null reference
        // ...
      });
    }

**Comment by lumine2008** [comment]
Hi @ndreisg , i am revisiting the issues, may i know if this issue still active? if yes, would you please share with me the gist/snippet? therefore we can do further investigation.

**Comment by ndreisg** [comment]
Not reproducible any longer
