### ISSUE TITLE
Custom Icon isn't shown with informational messages

### ISSUE THREAD

**Issue by markb-trustifi** [OfficeDev/office-js#565]
`Office.context.mailbox.item.notificationMessages.addAsync` doesn't show custom icon.
- The informational message is created with custom icon in Windows Outlook client only. 
- In Mac and in Outlook Online (Chrome) they are created with default icon.
- When passing between emails with opened add-on panel in Windows Outlook Client the icon is changed from custom to default.

## Expected Behavior
See custom icon

## Current Behavior
Custom icon is not seen, only default outlook informational icon.

## Steps to Reproduce, or Live Example
```js
Office.context.mailbox.item.notificationMessages.addAsync("info", {
   type: Office.MailboxEnums.ItemNotificationMessageType.InformationalMessage,
   message: "message",
   icon: "icon16",
   persistent: true
});
```

Relevant manifest sections:
```
<VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
    <Resources>
        <bt:Images>
            <bt:Image id="icon16" DefaultValue="https://oaddin.trustifi.com/images/logo_v2/Trustifi_LogoEnvelope_v2-16x16.png"/>
        </bt:Images>
    </Resources>
    <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
        <Resources>
            <bt:Images>
                <bt:Image id="icon16" DefaultValue="https://oaddin.trustifi.com/images/logo_v2/Trustifi_LogoEnvelope_v2-16x16.png"/>
            </bt:Images>
        </Resources>
    </VersionOverrides>
</VersionOverrides>
```

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac, Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: {mac:"16.00",web:"16.01",win32:"16.02"}
* Operating System: Windows, Mac
* Browser (if using Office Online): Chrome 74

**Comment by exextoc** [comment]
Thanks for reporting this issue. We have been able to reproduce this successfully and placed it on our backlog of work items. We don't have an ETA to communicate yet regarding the resolution of this issue.
