### ISSUE TITLE
Callback of goToByIdAsync is never fired

### ISSUE THREAD

**Issue by va1729** [OfficeDev/office-js#567]
## Steps to Reproduce, or Live Example
Script lap scripts -
* Example 1 - https://gist.github.com/Vivekananda-Athukuri/4193af29eb19871b8cd724dab205d38f
* Example 2 - https://gist.github.com/Vivekananda-Athukuri/3f3a5abcc20389907aeabc8c17a402b3

## Context
I am trying to make the cursor go to a particular binding. The function `goToByIdAsync` takes me to the binding but the callback is never fired in Office Online. It works in Mac Word app though.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: macOS Mojave
* Browser (if using Office Online): Firefox version - 67.0.4

**Comment by kbrandl** [comment]
@Vivekananda-Athukuri apologies for the slow response, looks like this issue was overlooked until now. @weshi can you please investigate? Thanks!

**Comment by AbidRahman-MSFT** [comment]
Hey @va1729,

I apologize for the delay. It looks like in your sample, you're missing the .bindings property. I've changed the second function in your sample to the following:

```
function run2() {
  Office.context.document.bindings.getByIdAsync("myBinding", function(asyncResult) {
    if (asyncResult.status == Office.AsyncResultStatus.Failed) {
      console.log("Action failed. Error: " + asyncResult.error.message);
    } else {
      console.log("Go to binding with type: " + asyncResult.value.type + " and id: " + asyncResult.value.id);
    }
  });
}
```

The above snippet will now search for the binding with the "myBinding" id and can successfully log the type and id to the console: 
![image](https://user-images.githubusercontent.com/53581099/121078288-fa666080-c795-11eb-962e-9633b9f4ec86.png)

Closing the issue for now, please feel free to re-open if you have any further questions.
