### ISSUE TITLE
Excel.PivotLayout.getPivotItems(axisString, Excel.Range) crashing

### ISSUE THREAD

**Issue by rjankovic** [OfficeDev/office-js#569]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When I use Excel.PivotLayout.getPivotItems(axisString, Excel.Range), it only works when there are no pivot items on the corresponding axis. Otherwise, it throws a "The argument is invalid or missing or has an incorrect format." error.

## Expected Behavior
The function returns an array of PivotItems

## Current Behavior
If there are no pivot items on the axis (rows / columns), it correnctly returns an empty array. Otherwise, it crashes.

## Steps to Reproduce, or Live Example

* Additional details:
  1. Create a pivot table connected to an OLAP cube.
  2. Add a dimension to the columns axis and a measure to the table values
  3. Select a cell in the table body
  4. Have a selectionChanged event handler (```context.workbook.worksheets.onSelectionChanged.add(handleSelectionChange)```)

that contains
```
...
ws = context.workbook.worksheets.getItem(event.worksheetId);
selectedRange = ws.getRange(event.address);
...
selectedPivotItems = selectedPivotTable.layout.getPivotItems("column", selectedRange); // this throws the error
...
```

## Context
I want to find out which dimension members the selected value in the table belongs to.

## Your Environment

* Platform: Office 365
* Host: Excel
* Operating System: Windows 10

## Useful logs
Stack trace:

InvalidArgument: The argument is invalid or missing or has an incorrect format.
   at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:24:274160)
   at T (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:24:212677)
   at x (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:24:212763)
   at t (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:24:212571)
   at l (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:24:211078)

**Comment by lumine2008** [comment]
Thank you @rjankovic for reporting this issue , we created a bug to track this issue, bug ID: 3452657

**Comment by lumine2008** [comment]
This bug has been converted to a feature requirement. OLAP PivotTables in general are just not supported currently, ower team will need to plan accordingly.
