### ISSUE TITLE
Excel For Mac - Manifest parsing doesn't properly handle urls with # style routing

### ISSUE THREAD

**Issue by LanceEa** [OfficeDev/office-js#57]
## Expected Behavior
I have Angular 5 application that uses # (hash urls) for routing. I would expect that I could have two command bar buttons in the ribbon that open up two different side panels. The first command button would use the root for my web application. The second command button points to a deep-linked route for the same web application (same angular application).

Command Button 1 --> https://localhost:4200/
Command Button 2 --> https://localhost:4200/#/home/table/active

Sample of the manifest: 

```xml
<bt:Url id="HomeUrl" DefaultValue="https://localhost:4200/"></bt:Url>
<bt:Url id="ActiveTablesUrl" DefaultValue="https://localhost:4200/#/home/table/active">
```

## Current Behaviour

This works perfectly on Excel Online but the issue seems to be isolated to the most recent Mac for Excel (fast insider). It will not honor the (#) hash route on the url and instead just routes to the root url.

## Steps to Reproduce, or Live Example

Steps to Reproduce: 
- Setup a manifest that has two command buttons and one points to a url that uses (hash) style routing.
- Click the first command button to open up a side-panel to the root url
- Click the second button to open up a second side-panel that opens to the deep-linked route
- Both side-panels will open to the root url https://localhost:4200/ and the second panel should have gone directly to the hashed route but instead opens the root url route.

Checking the `location.href` for the second side-panel yields the following:

`https://localhost:4200/?_host_Info=Excel$Mac$16.01$en-US%23/home/table/active#/`

If I can successfully navigate to the deep-link route manually. I end up with the following url:

`https://localhost:4200/?_host_Info=Excel$Mac$16.01$en-US#/home/table/active`.

So, it appears to me that the url from the manifest is being urlEncoded causing the `#` to `%23` so when the side-panel navigates to the url Angular will not see a (__#__) thus thinking it is routing to the root url. This is why we end up seeing a `#/` at the end of the url because Angular just navigated to the default route.

## Your Environment
macOS High Sierra (10.13.3)
Excel for Mac (insider fast) - version 16.11 build(180130)

**Comment by LanceEa** [comment]
@Zlatkovsky @sumurthy - Can  either of comment on this? Is this a known issue? 

Let me know if there is a better place to report this type of error!

**Comment by sumurthy** [comment]
This [thread](https://stackoverflow.com/questions/47683237/unable-to-post-form-from-excel-2016-for-mac-or-excel-for-ipad/48101382#48101382) may be relevant for this issue. 
I'll check with Mac experts and get back.

**Comment by brasten** [comment]
Are there any updates on this? We're seeing the same issue here. Thanks!

**Comment by JuaneloJuanelo** [comment]
We are still investigating.. thanks for your patience,..

**Comment by LanceEa** [comment]
Looks like this was resolved in today's insiders release...Version 16.11 (180220). I didn't make any changes and it seems like it is working correctly now.

@JuaneloJuanelo @sumurthy  - can you confirm? If so I can close this issue.

Thanks,
Lance
