### ISSUE TITLE
Caching Issue

### ISSUE THREAD

**Issue by AlRosenthal** [OfficeDev/office-js#579]
I am creating an Office add-in app for Word. It has mostly been built, but this morning I noticed that none of my changes were taking affect. I've tried clearing the cache from
[Clear office cache](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#clear-the-office-cache)
I've also tried clearing my Internet Explorer cache, adding query params to the JS includes, cleaning and rebuilding the app and so far nothing has reflected changes in the app.

## Expected Behavior
Make a change to a JS file and reload the app

## Current Behavior
Make a change, reload the office add 

## Steps to Reproduce, or Live Example
1. Make a change to a JS file
2. Reload the app
3. No changes reflected

## Your Environment

* Platform: PC desktop
* Host: Word
* Office version number: Word for Office 365 version 1906
* Operating System: Windows 10

**Comment by sumurthy** [comment]
Thanks for reporting. Have you tried with a new document to see if the issues repros?

**Comment by AlRosenthal** [comment]
Every time the server in visual studio is stopped and started it creates a opens a new instance of word.

**Comment by AlRosenthal** [comment]
went to load up visual studio today and the caching issue seems to have resolved itself. I didn't do anything differently, just loaded up my project and ran it.
