### ISSUE TITLE
array formulas as parameter for custom function not working as expected in Excel Online

### ISSUE THREAD

**Issue by ddanehl** [OfficeDev/office-js#580]
we have a custom formula that returns an matrix. this formula is then used in another custom formula as parameter. when using Excel 2016 on windows this works as excepted. when using excel online, the behavior is different.

## Expected Behavior
that all clients works the same

## Current Behavior
excel online not works as expected. it only passes the first value of the matrix, not the whole matrix.

## Steps to Reproduce, or Live Example
- import this GIST: https://gist.github.com/ddanehl/cdd0b9d87489f7da269cfa4e657847d0
- use this formula: =SCRIPTLAB.PALO.DATA("localhost/Demo";"Sales";SCRIPTLAB.PALO.EL("Products";"All Products");SCRIPTLAB.PALO.EL("Regions";"Europe");SCRIPTLAB.PALO.EL("Months";"Year");SCRIPTLAB.PALO.EL("Years";"All Years");SCRIPTLAB.PALO.EL("Versions";"All Versions");SCRIPTLAB.PALO.EL("Measures";"Units"))

- check the console output in ScriptLab:

Excel 2016
![correct](https://user-images.githubusercontent.com/7172621/60246913-f3ebc080-98bf-11e9-8338-ac18a681332c.png)

Excel Online (Chrome) 
![wrong](https://user-images.githubusercontent.com/7172621/60246989-18e03380-98c0-11e9-9e97-6ec4c062ff30.png)

## Context
DATA is an formula that fetchs a value from an OLAP database. EL is an helper function that converts excel arrays to an csv string. for this issue report we stript down the functions to an minimum.

## Your Environment
* Platform: PC Desktop, Online
* Host: Excel
* Office : 16.0.11819.20002 32 bit
* Operating System: Windows 10
* Browser: Chrome, Edge

**Comment by lumine2008** [comment]
@RuoyingLiang , would you please have a look? thanks.

**Comment by keyur32** [comment]
Hey @ddanehl  - this is due to Dynamic Arrays not being available yet on Excel for the web (aka Excel online). This feature is only available on Insiders versions for Mac and Windows (Unfortunately our browser-based Office versions do not yet have a preview environment). 

For now, to work-around it, the formula can be ctrl+shift+entered on a desktop client (traditional way of array entry), and then open on Excel in the browser.

**Comment by keyur32** [comment]
@RuoyingLiang  - suggest you leave this open to track the product change until Excel Dynamic Arrays GA' s later this year...

**Comment by ddanehl** [comment]
Hi @keyur32 - thanks for the explanation. i tried it out but unfortunately this workaround will not work for us. the suggested workaround only works if you enter the formula in at least two cells via ctrl+shift+enter but we need solution for a single cell as our PALO.DATA function is no array formula and only returns one single value

**Comment by keyur32** [comment]
Apologies for delay. removed fix pending label.  Internal Bug #3494915

**Comment by keyur32** [comment]
Hi @ddanehl, in reviewing it internally, the reason why only the top left cell is returned when you return a matrix on Excel online is currently a limitation as that feature is not supported on Excel Online, as to have multiple values returned, you would need to have it be array-entered, which Excel online does not yet support. On the desktop, you may see this working as you may be on the Insiders or Monthly (Targeted) channels that have Dynamic Arrays enabled.  So, this will be fixed as soon as we can launch Dynamic Arrays to GA. No eta on that yet as it depends on user feedback.

**Comment by ddanehl** [comment]
@keyur32 @RuoyingLiang 
we noticed that the Dynamic Array feature is now live for Excel Online. but sadly it is still not working for us. please check out this GIST sample for ScriptLab: https://gist.github.com/ddanehl/bb7978b09552f39518459eb398d7146e

and use this function:
=SCRIPTLAB.PALO.DATA("localhost/Demo","Sales",SCRIPTLAB.PALO.EL("Products","All Products"),SCRIPTLAB.PALO.EL("Regions","Europe"),SCRIPTLAB.PALO.EL("Months","Year"),SCRIPTLAB.PALO.EL("Years","All Years"),SCRIPTLAB.PALO.EL("Versions","All Versions"),SCRIPTLAB.PALO.EL("Measures","Units"))

this is one of our use cases for array formulas as parameters. but the function SCRIPTLAB.PALO.DATA gets never executed, instead it returns #CALC! error and says "Nicht heraufstufbares Array" ( i only have the german error message).

is this usecase still not supported or do we something wrong?

**Comment by RuoyingLiang** [comment]
@ddanehl  The parameters in the DATA function are returns dynamic array. So the parameter in DATA  function should be defined as matrix. I updated the function definition to :
function data(connection: string, cube: string, el0: **any[][]**, el1: **any[][]**, el2: **any[][]**, el3: **any[]**[], el4: **any[][]**, el5: **any[][]**)

And the function will work well:
![image](https://user-images.githubusercontent.com/50130769/68455763-1eb72f80-0237-11ea-9be4-c59c18375e48.png)

Please let me know if you still encounter problem.

**Comment by ddanehl** [comment]
@RuoyingLiang many thanks it works now!
