### ISSUE TITLE
Toggle calculation mode in Excel with Add-In

### ISSUE THREAD

**Issue by jjtfsalgado** [OfficeDev/office-js#581]
Loading data to a range with the Formulas>Calculation Options>Automatic it slows down drastically the performance, is there any way we could toggle this option using the api?

I've found [this post](https://stackoverflow.com/questions/42932472/toggle-calculation-mode-in-excel-with-add-in)  saying that was in backlog at the time, is there any progress on this feature?

Thanks

**Comment by lumine2008** [comment]
Hi @jjtfsalgado, 

You could try this API. 
context.application.calculationMode = "Automatic";
for more information, please refers to this document. 
https://docs.microsoft.com/en-us/javascript/api/excel/excel.calculationmode?view=office-js

**Comment by jjtfsalgado** [comment]
@lumine2008 Yes it worked, thanks
