### ISSUE TITLE
Outlook Mac v16.26 broken Office.context.mailbox.item.requiredAttendees.setAsync/addAsync

### ISSUE THREAD

**Issue by touficmouk** [OfficeDev/office-js#582]
After updating to Outlook Mac 16.26 whenever a user is creating a new appointment with the `to` line not visible, adding a room through an add-in that uses either api `Office.context.mailbox.item.requiredAttendees.setAsync/addAsync`
fails to add the room email to the `to` line.

## Expected Behavior
Expect `to` line to become visible (like in previous versions) and be filled in the room email address after calling `Office.context.mailbox.item.requiredAttendees.setAsync/addAsync`

*Past versions*
![](http://recordit.co/U7vWZZEQWf.gif)

## Current Behavior
`to` line doesn't open nor filled in.

*Current version 16.26*
![](http://recordit.co/tGbYzHAEgA.gif)

**Comment by macOutlookExtensibility** [comment]
Hey @touficmouk,

Thank you for reporting this issue. The issue has been fixed and will be available from build 16.27 (19062615) onwards.

**Comment by kbrandl** [comment]
Thanks for the update @macOutlookExtensibility; I'm closing this issue (and labeling as **resolved: awaiting prod deployment**).  @touficmouk thanks again for reporting this issue.

**Comment by touficmouk** [comment]
@kbrandl @macOutlookExtensibility 	Thanks for the quick fix - Confirmed that 16.27 behaves correctly.
