### ISSUE TITLE
“{0} wants to display a new window” when using displayDialogAsync

### ISSUE THREAD

**Issue by Warsame-Egal** [OfficeDev/office-js#583]
Platform: PC desktop
Host: Outlook Online
Office version number: 
Operating System: Windows
Browser: Chrome

I'm using Office.context.ui.displayDialogAsync and when I launch our app in Outlook task pane I get a dialog with the message "Test wants to display a new window". The word Test is a ShortString that comes from our Manifest file.

https://imgur.com/a/UBYhVDR

But when I click the Outlook On Send feature I get the same dialog but with the text "{0} wants to display a new window". The string doesnt seem to be pulled from the Manifest file that we use.

https://imgur.com/a/aA02gjD

I tried adding a label string to the send hook but it doesnt follow the add-in schema. Why does {0} appear and how can I replace that with a string?

    <ExtensionPoint xsi:type="Events">
        <Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="sendTest" />
    </ExtensionPoint>

This is the string that I use and is shown on the dialog when I dont click send

    <bt:ShortStrings>
        <bt:String id="buttonLabel" DefaultValue="Test"/>
    </bt:ShortStrings>

Complete Manifest file

    <?xml version="1.0" encoding="UTF-8"?>
    <OfficeApp
          xmlns="http://schemas.microsoft.com/office/appforoffice/1.1"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:bt="http://schemas.microsoft.com/office/officeappbasictypes/1.0"
          xmlns:mailappor="http://schemas.microsoft.com/office/mailappversionoverrides/1.0"
          xsi:type="MailApp">
      <Id>1111111</Id>
      <Version>1.0.0.0</Version>
      <ProviderName>Sample</ProviderName>
      <DefaultLocale>en-US</DefaultLocale>
      
      <DisplayName DefaultValue="myApp" />
      <Description DefaultValue="some text"/>
      <IconUrl DefaultValue="img" />
      <HighResolutionIconUrl DefaultValue="img" />
      <SupportUrl DefaultValue="url" />
      <AppDomains>
        <AppDomain>url</AppDomain>
        <AppDomain>url</AppDomain>
      </AppDomains>
      <Hosts>
        <Host Name="Mailbox" />
      </Hosts>
      <Requirements>
        <Sets>
          <Set Name="Mailbox" MinVersion="1.1" />
        </Sets>
      </Requirements>
      <FormSettings>
        <Form xsi:type="ItemRead">
          <DesktopSettings>
            <SourceLocation DefaultValue="img"/>
            <RequestedHeight>60</RequestedHeight>
          </DesktopSettings>
          <TabletSettings>
            <SourceLocation DefaultValue="img" />
            <RequestedHeight>60</RequestedHeight>
          </TabletSettings>
        </Form>
        <Form xsi:type="ItemEdit">
          <DesktopSettings>
            <SourceLocation DefaultValue="img" />
          </DesktopSettings>
          <TabletSettings>
            <SourceLocation DefaultValue="img" />
          </TabletSettings>
        </Form>
      </FormSettings>
      <Permissions>ReadWriteMailbox</Permissions>
      <Rule xsi:type="RuleCollection" Mode="And">
        <Rule xsi:type="ItemIs" ItemType="Message" FormType="ReadOrEdit"  />
        <Rule xsi:type="ItemHasAttachment" />
      </Rule>
      <DisableEntityHighlighting>false</DisableEntityHighlighting>

      <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides" xsi:type="VersionOverridesV1_0">
        <VersionOverrides xmlns="http://schemas.microsoft.com/office/mailappversionoverrides/1.1" xsi:type="VersionOverridesV1_1">
          <Description resid="green" />
          <Requirements>
            <bt:Sets DefaultMinVersion="1.3">
              <bt:Set Name="Mailbox" />
            </bt:Sets>
          </Requirements>
          <Hosts>
            <Host xsi:type="MailHost">

              <DesktopFormFactor>
                <FunctionFile resid="residUILessFunctionFileUrl" />
          	    <ExtensionPoint xsi:type="Events">
							    <Event Type="ItemSend" FunctionExecution="synchronous" FunctionName="initOnSend" />
						    </ExtensionPoint>
                
                <ExtensionPoint xsi:type="MessageReadCommandSurface">
                  <OfficeTab id="TabDefault">
                    <Group id="msgReadGroup">
                      <Label resid="black" />
                      <Control xsi:type="Button" id="msgReadOpenPaneButton">
                        <Label resid="blue" />
                        <Supertip>
                          <Title resid="yellow" />
                          <Description resid="red" />
                        </Supertip>
                        <Icon>
                          <bt:Image size="16" resid="icon-16" />
                          <bt:Image size="32" resid="icon-32" />
                          <bt:Image size="80" resid="icon-80" />
                        </Icon>
                        <Action xsi:type="ShowTaskpane">
                          <SourceLocation resid="readTaskPaneUrl" />
                          <SupportsPinning>true</SupportsPinning>
                        </Action>
                      </Control>
                    </Group>
                  </OfficeTab>
                </ExtensionPoint>
                <ExtensionPoint xsi:type="MessageComposeCommandSurface">
                  <OfficeTab id="TabDefault">
                
                    <Group id="msgComposeGroup">
                      <Label resid="black" />
                      <Control xsi:type="Button" id="msgComposeOpenPaneButton">
                        <Label resid="blue" />
                        <Supertip>
                          <Title resid="yellow" />
                          <Description resid="red" />
                        </Supertip>
                        <Icon>
                          <bt:Image size="16" resid="icon-16" />
                          <bt:Image size="32" resid="icon-32" />
                          <bt:Image size="80" resid="icon-80" />
                        </Icon>
                        <Action xsi:type="ShowTaskpane">
                          <SourceLocation resid="composeTaskPaneUrl" />
                          <SupportsPinning>true</SupportsPinning>
                        </Action>
                      </Control>
                    </Group>
                
                  </OfficeTab>
                </ExtensionPoint>
              </DesktopFormFactor>
            </Host>
          </Hosts>

          <Resources>
            <bt:Images>
              <bt:Image id="icon-16" DefaultValue="img"/>
              <bt:Image id="icon-32" DefaultValue="img"/>
              <bt:Image id="icon-80" DefaultValue="img"/>
            </bt:Images>
            <bt:Urls>
              <bt:Url id="composeTaskPaneUrl" DefaultValue="img"/>
              <bt:Url id="readTaskPaneUrl" DefaultValue="img"/>
              <bt:Url id="residUILessFunctionFileUrl" DefaultValue="img" />
            </bt:Urls>
            <bt:ShortStrings>
              <bt:String id="black" DefaultValue="sample"/>
              <bt:String id="blue" DefaultValue="Test"/>
              <bt:String id="yellow" DefaultValue="sample"/>
            </bt:ShortStrings>
            <bt:LongStrings>
              <bt:String id="red" DefaultValue="some text"/>
              <bt:String id="green" DefaultValue="some text"/>
            </bt:LongStrings>
          </Resources>
        </VersionOverrides>
      </VersionOverrides>
    </OfficeApp>

**Comment by kbrandl** [comment]
@Warsame-Egal sorry to hear that you've run into this issue. Can you please update your original post to include the following information?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

@exextoc assigning to you for investigation, since this issue seems related to onSend in Outlook.

**Comment by exextoc** [comment]
@Warsame-Egal Can you please share your implementation for function "sendTest" so that I can try to repro the issue?

**Comment by Warsame-Egal** [comment]
Implementation for sendTest:


**index.html:**

    <script>
        Office.initialize = window.appSend.onInit;

        function sendTest(event) {
            window.appSend.onSend(event);
        }
    </script>
 
**AppSend.ts:**


    import { IEvent } from '../XXX/XXX';

    export class AppSend {

        public onSend = async (event: IEvent) => {

            Office.context.ui.displayDialogAsync("https://www.google.com/", { height: 50, width: 50 });      

        }
    }



**AppSendBootstrap.ts:**

    import { AppSend } from './AppSend';

    declare global {
      interface Window { appSend: any; }
    }

    const appSend = new AppSend();
    window.appSend = appSend;

**Comment by exextoc** [comment]
The dialog shared by you, is it a custom dialog? Where is the code set up for the dialog? The value which you want to read is coming from manifest, but where are you reading that value. The string from the manifest needs to be read in you code.

**Comment by Warsame-Egal** [comment]
The dialog shared is not a custom dialog, we are using Office JS dialog displayDialogAsync

**Comment by Warsame-Egal** [comment]
The value from the manifest is read in this dialog: https://imgur.com/a/UBYhVDR

But its not read here when clicking the On Send feature : https://imgur.com/a/aA02gjD

Both dialogs are the same and are created using  Office.context.ui.displayDialogAsync

**Comment by exextoc** [comment]
This dialog https://imgur.com/a/UBYhVDRhas has an internal implementation of reading the value from manifest, and also it reads a particular string value which is identified by string id. Since the manifest has multiple string values, the way we read the value from manifest matters. You need to check your string which you have added in manifest and the way you are trying to read it in the dialog.

**Comment by Warsame-Egal** [comment]
One is launched with onsend and the other with compose. In our code we dont read any values from the manifest.

**Comment by Warsame-Egal** [comment]
Our understanding is that Office.js should read the value from the manifest automatically. Thats why showDialog in compose mode displays the string but for some reason showDialog in OnSend mode does not. We are trying to figure out why compose reads the string from the manifest and on send does not. Our manifest is also provided above.

**Comment by exextoc** [comment]
This appears to be a bug in OWA. Does this reproduce when "Try the new Outlook" is toggled on or off? Could you share a version number of Outlook on the Web?

**Comment by kbrandl** [comment]
Please ignore the previous message from **msftbot**. The **Needs: author feedback** label was incorrectly applied to this issue; I've removed that label and this issue is no longer marked as stale. 

@Warsame-Egal if you're able to answer @exextoc's most recent question in this thread, that might help with troubleshooting. Thanks!

**Comment by exextoc** [comment]
@Warsame-Egal  Could you share a version number of Outlook on the Web? We are not able to repro this. Can you share stripped down version of your add-in code in github repository, where issue is reproducible?

**Comment by ghost** [comment]
This issue has been closed due to inactivity. Please comment if you still need assistance and we'll re-open the issue.
