### ISSUE TITLE
How to add Newline in return result?

### ISSUE THREAD

**Issue by BlazorDashboard** [OfficeDev/office-js#585]
Any idea how I can add a newline character in the return result of a custom function? The below does not work for me.

return "a\nb"; 
return "a"+String.fromcharcode(10)+"b"
return "a"+String.fromcharcode(10)+String.fromcharcode(13)+"b"

**Comment by kbrandl** [comment]
@keyur32 are you able to provide input on this issue (or suggest someone who can)? Thanks!

**Comment by keyur32** [comment]
@RuoyingLiang  to consider on the backlog. Currently we do not support this.

**Comment by lindalu-MSFT** [comment]
Is this actually in the backlog? If so, is there an internal number to track? Thanks, llc

**Comment by grangeryy** [comment]
Created a new feature for this: 4959644

**Comment by jordandev** [comment]
We need this as well

basically want multiline data table header descriptions

**Comment by grangeryy** [comment]
@jordandev and @BlazorDashboard, do you still have the requirement for this capability? To better manage the new feature requirement, please consider posting the feature ask in [Ideas Forum](https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform) which is the new place for "UserVoice".
