### ISSUE TITLE
Word.run apply weird inline styles during post process

### ISSUE THREAD

**Issue by jasonqsong** [OfficeDev/office-js#586]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When a inline range is loaded, we can apply a inline style. However, the post processing in Word.run will change the range of the style.

## Expected Behavior

Only selected range will be affected.

## Current Behavior

The text followed by the targeted range will be affected during Word.run post processing. This bug only happens on web. Desktop Word will render correctly.  

## Steps to Reproduce, or Live Example

* Link to live example: https://gist.github.com/jasonqsong/abe8ba3145d368870dca5a655fc4f97b

## Context

Heavily affected. No wordaround found.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 06/28/2019
* Operating System: Win10
* Browser (if using Office Online): Chrome

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

Code:
```typescript
async function bug() {
  // Set inline style for one word, get style for entire line
  await Word.run(async (context) => {
    const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
    const inlineRanges = context.document.body.getRange().search("doing");
    inlineRanges.load();
    await inlineRanges.context.sync();
    const inlineRange = inlineRanges.getFirst();
    inlineRange.font.color = "red";
    await inlineRange.context.sync();
    await context.sync();
    console.warn('Style looks correct before finish... Only "doing" is red');
    await sleep(3000);
  });
  console.warn('Style suddenly get wrong... "doing weird thing" become red');
}
```

Expected:
![image](https://user-images.githubusercontent.com/6178947/60313220-cf134e00-9990-11e9-99dc-1c5c0aa0ffe6.png)

Current:
![image](https://user-images.githubusercontent.com/6178947/60313294-20bbd880-9991-11e9-8d9e-9d2690d8e5be.png)

**Comment by kbrandl** [comment]
@jasonqsong sorry to hear that you've run into this issue, and thanks for providing this detailed write-up.

@weshi FYI, assigning to you for investigation.
