### ISSUE TITLE
Get-Addins not working on OWA for MAC (Safari)

### ISSUE THREAD

**Issue by kanaksony** [OfficeDev/office-js#588]
## Expected Behavior

1. Open Outlook on safari. Login to account.
2. New Message, Click on GetAddins button.
3. Must show "Add-ins for Outlook Window"

## Current Behavior
No window opens - results in blocker for development and testing

## Steps to Reproduce, or Live Example
1. Open Outlook on safari. Login to account.
2. New Message, Click on GetAddins button.
3. Must show "Add-ins for Outlook Window"

## Context
I need to test my plugin to submit it on store

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online (System OS is MAC)
* Host [Excel, Word, PowerPoint, etc.]: OWA Outlook 
* Operating System: MAC
* Browser (if using Office Online): Safari - Version 12.1.1 (14607.2.6.1.1)

## Useful logs
[Error] Unhandled Promise Rejection: Error: Key and Value parameters should not be null
	(anonymous function) (owa.Addins.js:1:418652)
	promiseReactionJob

**Here is the screenshot attached.**
![image](https://user-images.githubusercontent.com/6097596/60380670-ee7caa80-9a66-11e9-9829-7cfa6444c80f.png)

**Comment by kbrandl** [comment]
@kanaksony sorry to hear that you've run into this issue; we'll look into it. 

@macOutlookExtensibility FYI I've assigned this issue to you for investigation.

**Comment by kbrandl** [comment]
@kanaksony I notice you've also opened issue #591 -- which seems to indicate that you've been able to sideload your add-in (albeit now the add-in is producing errors). Is it true that you're able to sideload your add-in, and if yes, then can this issue (#588) be closed?

(unassigning @macOutlookExtensibility for now, until it's determined whether investigation is needed)

**Comment by ShannonLCapper** [comment]
I can still reproduce this issue, but only in the "new experience" in OWA (accessed by toggling on `Try the new Outlook` from the inbox). Add-ins can still be side loaded in the "old" OWA experience, as well as from Mac and Windows desktop

**Comment by kanaksony** [comment]
@kbrandl I confirm that I still can see this issue with one account and not with another account. @ShannonLCapper yes, it might be an issue with new and old experience but I was unable to find that toggle switch.

**Comment by kbrandl** [comment]
@kanaksony and @ShannonLCapper thanks for the additional information. 

@macOutlookExtensibility FYI, assigning this issue to you for investigation.

**Comment by exextoc** [comment]
@kanaksony We have fixed this issue. Can you please check again?

**Comment by ShannonLCapper** [comment]
After clearing my browser cache to pull down the updated OWA code, it looks like this issue is fixed for me! Thanks folks!

**Comment by kbrandl** [comment]
@ShannonLCapper thanks for confirming! I'll mark this issue as `Fixed` and close it.

**Comment by kanaksony** [comment]
@exextoc it works now. Thanks!
