### ISSUE TITLE
numberFormat changed by pc environment

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#590]
hi

i set a numberFormat for range like "$#,##0.00".  my excel language is CN, it's display ￥。if excel 

language is en it's ok. can i set $ for all environment? thanks

**Comment by kbrandl** [comment]
@dinglicoding thanks for your interest in Office Add-ins development. Before we can respond to this issue, we'll need some more information from you.  Can you please edit your original post to provide the code that results in the behavior you've described, and also provide the following information about platform, etc. where you're seeing this issue (and optionally, screenshots of the two outcomes you've described).  Thanks!

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

**Comment by catchingyu** [comment]
Is it possible for you to provide us more information on this issue? Thanks a lot for the support.

Description :

Expected Behavior

Current Behavior

Steps to Reproduce, or Live Example

Context

Your Environment
Platform [PC desktop, Mac, iOS, Office Online]:
Host [Excel, Word, PowerPoint, etc.]:
Office version number:
Operating System:
Browser (if using Office Online):

**Comment by dinglicoding** [comment]
@kbrandl  @catchingyu  thanks for your reply.

Description :
i set a numberFormat for range like "$#,##0.00". my excel language is CN, it's display ￥。

Expected Behavior
it's display $4.00

Current Behavior
it's display ￥4.00 , 

Steps to Reproduce, or Live Example
![image](https://user-images.githubusercontent.com/3963826/60490396-08bdbf00-9cd9-11e9-9d47-5aeebb65a069.png)

Context
Platform [PC desktop, Mac, iOS, Office Online]:  PC Desktop

Host [Excel, Word, PowerPoint, etc.]:  Excel

Office version number: version 1906(build 11727.20210)

Operating System:  Windows 家庭学生版。（中文）

**Comment by catchingyu** [comment]
@dinglicoding  could you share with us your code piece also? It would be great that you could share with us gists.

**Comment by dinglicoding** [comment]
@catchingyu 

piece of code:

    await Excel.run(async (context) => {
        const sheet = context.workbook.worksheets.getItem("Sample");
        const formats = [["$#,##0.00", "$#,##0.00"], ["$#,##0.00", "$#,##0.00"], ["$#,##0.00", "$#,##0.00"]];
        const range = sheet.getRange("D3:E5");
        range.numberFormat = formats;
        await context.sync();
    });

**Comment by catchingyu** [comment]
@dinglicoding thanks for that. Team will take a look at it and return to you later.

**Comment by catchingyu** [comment]
@dinglicoding  will you try to use   

const formats = [["$￥#,##0.00", "$￥#,##0.00"], ["$￥#,##0.00", "$￥#,##0.00"], ["$￥#,##0.00", "$￥#,##0.00"]]; on a clean range.
and check whether the showing is correct or not.

**Comment by dinglicoding** [comment]
@catchingyu 
I use Script Lab
![image](https://user-images.githubusercontent.com/3963826/60641361-0e90dd00-9e5e-11e9-806f-0a9f794c6f51.png)
![image](https://user-images.githubusercontent.com/3963826/60641387-2a947e80-9e5e-11e9-8165-ad5e501382e9.png)
![image](https://user-images.githubusercontent.com/3963826/60641390-2f593280-9e5e-11e9-9105-4ddf7730643e.png)

**Comment by catchingyu** [comment]
It seems to be highly related to your excel environment. Can you just input '$' in the cell from the UI?

**Comment by dinglicoding** [comment]
@catchingyu  thanks

 my excel language is chinese. and i input '$' in cell, it's display '$'

if excel language is english ,it's fine.

**Comment by catchingyu** [comment]
bug 3483278 is created for tracking the issue. The team is actively working on it now. Thanks a lot for reporting.

**Comment by MandytMSFT** [comment]
@dinglicoding could you use numberFormatLocal to see if it resolve your issue ?

**Comment by dinglicoding** [comment]
@tfjy2008  thanks.  i use  numberFormatLocal  , it resolved my issue.
