### ISSUE TITLE
Passing null to setCellProperties crashes Excel

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/office-js#593]
Passing an array with null values to `Range.setCellProperties` crashes Excel. Here's the code in question:

```
const range = sheet.getRange("A1:B2");
range.setCellProperties([
  [null,null],
  [null, null]
]);
```

## Expected Behavior
An error will be thrown and displayed through Script Lab's console

## Current Behavior
Excel reports an issue and closes.

## Steps to Reproduce, or Live Example
https://gist.github.com/AlexJerabek/1b3c36e6503e90b7583869ecfc9da459

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]:  PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1907 (Build 11814.20000)
* Operating System: Windows 10
* Browser (if using Office Online): ______

**Comment by kbrandl** [comment]
@AlexJerabek thanks for reporting this issue. @tutieu and @lumine2008 FYI, assigning to you for investigation (please feel free to change assignment if someone else on your team should investigate).

**Comment by catchingyu** [comment]
Bug 3466223 is created, I can reproduce it.

**Comment by catchingyu** [comment]
@AlexJerabek  This bug is already fixed and rolling out in XLO. The WIn32/Mac are in the processing of released. Thanks Alex for reporting this issue to us.
