### ISSUE TITLE
displayDialogAsync callback receives 5001 error, preventing event listeners from being added

### ISSUE THREAD

**Issue by nathguen** [OfficeDev/office-js#595]
## Expected Behavior
The callback parameter `result` should contain a property of `value` that is a reference to the opened dialog object.

## Current Behavior

The `result` is an `OSF.DDA.Error` error with code # 5001, and a message that "An internal error has occurred." This is only occurring on the web outlook client. It works correctly on the desktop outlook client.

## Steps to Reproduce, or Live Example

OAuthNeededContainer.tsx
```TypeScript
...

public render(): JSX.Element {
    return (
        <OAuthNeeded
            ...
            onReconnect={this.handleReconnect}
        />
    );
}

private async handleReconnect(): Promise<void> {
    this.done('oAuthNeeded');
}

private done(status: string): void {
    Office.context.ui.messageParent(JSON.stringify({ status: status }));
}
...
```

displayDialog.ts
```TypeScript
const receiveMessage = async (event: any): Promise<void> => {
    if (JSON.parse(event.message).status === 'oAuthNeeded') {
        const oAuthResult = await startFlowAsync(); // returns a promise with the result of authenticating w/ Microsoft
        resolve(oAuthResult);
    } else {
        resolve('Canceled');
    }
};

const url = 'someURL';
const dialogOptions = { width: 25, height: 55, displayInIframe: true };
Office.context.ui.displayDialogAsync(url, dialogOptions, (result: Office.AsyncResult) => {
    dialog = result.value;
    dialog.addEventHandler(Office.EventType.DialogMessageReceived, receiveMessage);
});
```

## Context

The "Reconnect" button sends an event called "oAuthNeeded" that the event handler is listening for. However, because of the 5001 error, as described above, the event listener is never bound to the dialog object, since the dialog object never gets passed into the callback.

![oauth reconnect dialog_brushed](https://user-images.githubusercontent.com/6416887/60551519-bdaba800-9ce8-11e9-863a-829a7032a6e8.png)

I was doing dev work on this particular feature early last week, and it was working. When I went to work on it yesterday, however, the callback started producing a `5001` error, and events were no longer being received. No new dependencies have been added, and no existing dependencies have been updated since it was last working.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Web Browser
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Web
* Operating System: MacOS Mojave (10.14.4) and Windows 10
* Browser (if using Office Online): Chrome, Firefox, and Internet Explorer (haven't tested Safari yet)

## Useful logs

- [x] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by kbrandl** [comment]
@nathguen sorry to hear that you've run into this problem; we'll investigate. 

FYI @danielgwilson assigning this to you (since it's related to Dialog API) -- please reassign if it should go to someone else. Thanks!

**Comment by exextoc** [comment]
Thanks for reporting this issue. we have checked-in the fix for this, will be live soon.

**Comment by exextoc** [comment]
@nathguen Is this problem resolved for you now? Can you please check?

**Comment by exextoc** [comment]
@nathguen Thanks for reporting this issue. We have fixed this problem and deployed in production already. Let us know if you need any other help in this regard.
