### ISSUE TITLE
How can I use excel addin upload 1G file

### ISSUE THREAD

**Issue by mengxianwen** [OfficeDev/office-js#596]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

 I wanted to upload a 1G file via excel addin. but I've met some problems when I was using Office.context.document.getFileAsync().

 ### Expected Behavior
---
 Returns the entire document file in slices of up to 4194304 bytes (4 MB). I hope the file can be uploaded successfully.
 ### Current Behavior
---
 But when the file slices to No.256, the error happened.ErrorCode:12007.ErrorMessage:A dialog box is already opened from this host window, so the operation failed.
![image](https://user-images.githubusercontent.com/52442516/60559974-34987d80-9d89-11e9-8e82-7de1c2d0a52d.png)
### Steps to Reproduce, or Live Example
---
the error happened in the function getSlice
```javascript
function uploadRun() {
	if (isCheckout) {
		$("#msg").empty();
		$('#uploadRun').addClass('disabled');
		$('#uploadCancel').addClass('disabled');
		$('#saveTemp').addClass('disabled');
	} else {
		$("#msg").empty();
		$('#footer-div .btn-primary').attr('disabled', true);
	}

	Office.context.document.getFileAsync(
		Office.FileType.Compressed,
		{ },  
		function (result) {
			if (result.status == Office.AsyncResultStatus.Succeeded) {
            	var myFile = result.value;
            	var state = {
                	file: myFile,
                	counter: 0,
                	sliceCount: myFile.sliceCount,
                	fileName: "",
                 	result: true,
					code: "",
					msg: ""
             	};
             	getSlice(state);
         	} else {
         		showMessage(JSMsg["OfficeAddin.msg.00102"], false);
         	}
     });
}
function getSlice(state) {
    state.file.getSliceAsync(state.counter, function (result) {
        if (result.status == Office.AsyncResultStatus.Succeeded) {
            sendSlice(result.value, state);

        } else if (result.status == Office.AsyncResultStatus.Failed) {
            console.log(result);
            showMessage("sliceCounter: " + state.counter + ".ERROR happened. ErrorCode: " + result.error.code + ".ErrorMessage:" + result.error.message, false);
        }else {
            showMessage(JSMsg["OfficeAddin.msg.00102"], false);
        }
    });
}
```
### Context
---
### Your Environment
---
- Host [Excel, Word, PowerPoint, etc.]: Excel
- Office version number: Excel for Office 365 MSO (16.0.11727.20222)
### Useful logs
---
- [x] Console errors
- [x] Screenshots
- [x] Test file (if only happens on a particular file)

**Comment by kbrandl** [comment]
@mengxianwen sorry to hear that you've run into this problem; we'll investigate.

@catchingyu FYI, assigning this issue to you (since it's Excel-related); please reassign it if it should go to someone else on your team instead. Thanks!

**Comment by mengxianwen** [comment]
> @mengxianwen sorry to hear that you've run into this problem; we'll investigate.
> 
> @catchingyu FYI, assigning this issue to you (since it's Excel-related); please reassign it if it should go to someone else on your team instead. Thanks!

thank you so much. waiting for your reply.

**Comment by catchingyu** [comment]
@mengxianwen  do you encounter this problem only in Excel or other Hosts like Word and PowerPoint?

@kbrandl Thanks a lot, we will look into first.

**Comment by mengxianwen** [comment]
@catchingyu I have tested the two Hosts (Word and PowerPoint), and the problem still exist

**Comment by kbrandl** [comment]
I've reassigned this issue (to @sumurthy) for investigation.

**Comment by sumurthy** [comment]
Just to clarify: 
1. Your Excel file is over 1GB and you're trying to upload its content to some location by using getFile API? 
2. Can you clarify if there are any dialogs involved in the add-in? The error code 12007 points to DialogAlreadyOpened error, which could be due to opening a dialog when one is already open.
3. Could you please mention the platforms that you are testing this on (Windows OS, MacOS)?

**Comment by mengxianwen** [comment]
@sumurthy
> Your Excel file is over 1GB and you're trying to upload its content to some location by using getFile API?

If you are referring to the getFileAsync method, yes. As I wrote in the code I am prompted, the problem occurs in state.file.getSliceAsync.
> Can you clarify if there are any dialogs involved in the add-in? The error code 12007 points to DialogAlreadyOpened error, which could be due to opening a dialog when one is already open.

No, I didn't find any dialogs, at least it didn't pop up any dialogs. I wonder why this error was reported because there is no dialog involved in my code.
> Could you please mention the platforms that you are testing this on (Windows OS, MacOS)?

Windows OS

**Comment by mengxianwen** [comment]
@kbrandl @sumurthy
Hi how’s things going? Have you worked out the problem? 
Sorry to bother you again. Still waiting for your reply

**Comment by MandytMSFT** [comment]
@mengxianwen is that possible to provide your sendSlice() code to help us identify cause ?

**Comment by mengxianwen** [comment]
@tfjy2008 here is the code ,wish can help you
```javascript
function sendSlice(slice, state) {
	var data = slice.data;

	if (data) {

		var fileData = data;
		var request = new XMLHttpRequest();
		//request.responseType = 'json';

		request.onreadystatechange = function () {
			if (request.readyState == 4) {
				var rep = JSON.parse(request.response);
				state.counter++;
				state.fileName = rep["slice-file"];
				state.result = rep["result"];
				state.code = rep["code"];
				state.msg = rep["msg"];
                showMessage("sliceCount:" + state.counter, true);
				if (state.result && state.counter < state.sliceCount) {
					getSlice(state);
				} else {
					closeFile(state);
				}
			}
		}

		var reqUrl = _url.replace(/msopen([^\?]*)/, "LocalOfficeUpload");
		if (!isCheckout && $("#selectMoveoutId").val() != $("#movSpaceId").val()) {
			reqUrl += "&spaceId=" + $("#selectMoveoutId").val();
		}

		if (isCheckout) {
			reqUrl += "&checkin=" + committed + "&times=" + savedtimes;
		}

		request.open("POST", reqUrl);
		request.setRequestHeader("slice-index", state.counter+1);
		request.setRequestHeader("slice-count", state.sliceCount);
		request.setRequestHeader("slice-file", state.fileName);
		request.send(fileData);
	}
}

**Comment by MandytMSFT** [comment]
Internal BUG 3479363 is tracking this issue

**Comment by adammpolak** [comment]
> Internal BUG 3479363 is tracking this issue

Has this been solved?
