### ISSUE TITLE
[Outlook] ConversationId is 'undefined' instead of 'null' in new OWA

### ISSUE THREAD

**Issue by ShannonLCapper** [OfficeDev/office-js#598]
According to the [documentation](https://docs.microsoft.com/en-us/javascript/api/outlook/office.message?view=office-js#conversationid), `Office.context.mailbox.item.conversationId` will return `null` if the mail item lacks a conversation ID. However, in the "new experience" of OWA, it returns `undefined`.

## Expected Behavior

I'd expect that the "new experience" in OWA would have the same behavior as the old experience and other platforms: if a mail item lacks a conversation ID, `Office.context.mailbox.item.conversationId` returns `null`.

## Current Behavior

When a mail item lacks a conversation ID in the "new experience" in OWA, `Office.context.mailbox.item.conversationId` return `undefined`. This does not match the documentation or the behavior in other platforms.

## Steps to reproduce
1. Toggle on `Try the new Outloook` from the OWA inbox
2. Click `+New mail`
3. Open any add-in that runs in compose mode
4. Access `window.Office.mailbox.item.conversationId` from the plugin. See that the value is undefined (see screenshots below)

## Context
Our code has fallbacks that alert us if values we consume from OfficeJS are not the type we'd expect, and it throws in this case since the value of conversation ID is expected to be either a string or null. We have code that explicitly checks if `conversationId` is null as part of a check to determine if a compose mail is part of a thread, and it does not work correctly when the value is undefined. While we can work around this, it would be nice if the value was consistent across platforms and matched the documentation.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.10908.10000
* Operating System: macOS High Sierra 10.13.6
* Browser (if using Office Online): only tested in Chrome 75.0.3770.100

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

In the "old" OWA experience, version 16.0.10205.10000
<img width="311" alt="Screen Shot 2019-07-03 at 11 34 29 AM" src="https://user-images.githubusercontent.com/21230261/60616657-d66a9b00-9d86-11e9-8c3e-742fccff1647.png">

In the "new" OWA experience, version 16.0.10908.10000
<img width="310" alt="Screen Shot 2019-07-03 at 11 33 32 AM" src="https://user-images.githubusercontent.com/21230261/60616672-dcf91280-9d86-11e9-8919-3ebb73a8bf0b.png">

**Comment by kbrandl** [comment]
@ShannonLCapper thanks for reporting this inconsistency and for providing such detailed information.

@exextoc FYI, assigning this issue to you for investigation (since it's related to Outlook on the web).

**Comment by exextoc** [comment]
@ShannonLCapper Thanks for reporting this and proving such detailed information. We have added this to our backlog. Unfortunately we have no timelines to share at this point

**Comment by exextoc** [comment]
We have fixed this issue and it is in production now.
