### ISSUE TITLE
[Outlook] localStorage not syncing between add-in windows on same domain

### ISSUE THREAD

**Issue by david-davidson** [OfficeDev/office-js#600]
Hi there,

This isn't a clear-cut bug—that is, it's not clear that Office.js is involved. Instead, I'm hoping it might ring a bell with your team!

We have an add-in that opens a dialog from the taskpane; the dialog and taskpane are on the same domain. In general, we're observing that they share `localStorage` correctly, per https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#pass-information-to-the-dialog-box . However, in one customer's case, we're observing that `localStorage` is NOT shared. Not only do updates to the taskpane not propagate into the dialog—state saved in the taskpane _before_ the dialog opens isn't captured in the dialog's initial storage state. For all intents and purposes, the two storages are distinct!

So far, we've only observed this in OWA on IE11; see Your Environment.

## Expected Behavior
A dialog and a taskpane on the same domain should share `localStorage`.

## Current Behavior
The two `localStorages` are distinct; changes in one aren't reflected in the other.

## Steps to Reproduce, or Live Example
Unfortunately, we can't give a live/direct example (since this is in a customer's environment), but the repro is as simple and broad as:
* In taskpane's DevTools: `localStorage.setItem('testKey', 'testVal')`
* Open dialog
* Inspect dialog's `localStorage`; `'testKey'` is not present

## Context
Our app relies on shared `localStorage` to communicate between the taskpane and the dialog, particularly when setting up initial state and propagating parent->child messages.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: **Office Online**
* Host [Excel, Word, PowerPoint, etc.]: **Outlook**
* Office version number: **16.0.11601.20184**
* Operating System: **Windows 10 (1607)**
* Browser (if using Office Online): **IE 11 (11.2969.14393.0)**
* Exchange Online: **15.20.2032.8**

-----

I realize this is very little information to go on—does this behavior ring a bell with your team? Can you think of a reason a dialog and taskpane, on the same domain in IE11, might not share `localStorage`?

Thanks!

**Comment by Zlatkovsky** [comment]
This sounds like an IE issues -- and does ring a bell.  Fortunately, there is an easy workaround, which we use in Script Lab:

From https://github.com/OfficeDev/script-lab/blob/d9ac2a989cae99efb4e3fe8e96d99f35a183c699/packages/common/src/utilities/ensure.fresh.local.storage.ts:
```
const ensureFreshLocalStorage = (): void => {
  // Due to bug in IE (https://stackoverflow.com/a/40770399),
  // Local Storage may get out of sync across tabs.  To fix this,
  // set a value of some key, and this will ensure that localStorage is refreshed.
  window.localStorage.setItem('scriptlab_unused_key', '');
};

export default ensureFreshLocalStorage;
```

See the link in the comment of the code above for more info.

**Comment by kbrandl** [comment]
@Zlatkovsky thanks for the input here (assigning this issue to you, for tracking purposes). @david-davidson  can you please let us know if the feedback provided by @Zlatkovsky helps to unblock you?

**Comment by david-davidson** [comment]
@kbrandl @Zlatkovsky Thanks for the quick response and suggestion! I'll take a look at the beginning of next week and let you know.
