### ISSUE TITLE
ContentControl.insertOoxml fails with message "documentNotSupported" in Office Online

### ISSUE THREAD

**Issue by sergiubucur** [OfficeDev/office-js#601]
We have a functionality which allows the user to select a piece of content from the document, have a Word Add-in extract the XML content from the selection, and then the user can paste this XML content back into the document (or into a different document) at a later point.

When pasting content, we insert a content control and then use ContentControl.insertOoxml to insert the XML content.

## Expected Behavior
The ContentControl.insertOoxml method should insert the XML content into the content control.

## Current Behavior
The ContentControl.insertOoxml method fails with the error message "RichApi.Error: documentNotSupported".

## Steps to Reproduce, or Live Example
ScriptLab gist: https://gist.github.com/sergiubucur/822ee7b5230c0a172e3d3bc8bf387be5
Select a piece of content, click "Copy". You should see a confirmation in the console. Then click "Paste". 

## Context
This code works as expected on Word Desktop and Word Online. It only fails on Word Online in one case: if the document being edited is served from SharePoint Online from a document library with the "Require Check Out" setting turned on (in SharePoint Online go to document library settings > Versioning settings > Require Check Out > Set to "Yes").

Other ContentControl insertion methods (insertText, insertParagraph, insertHtml) do work in this case. The issue is only with insertOoxml, in the "Require Check Out" set to "Yes" scenario.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: N/A (Office Online)
* Operating System: Windows 10
* Browser (if using Office Online): Google Chrome 75

## Useful logs
![image](https://user-images.githubusercontent.com/7591380/60655675-dafe8480-9e56-11e9-9065-b1a01b86e8d1.png)

**Comment by kbrandl** [comment]
@sergiubucur sorry to hear that you've run into this problem; thanks for reporting it.

@weshi FYI, I've assigned this issue to you for investigation.

**Comment by MandytMSFT** [comment]
i tried below code with scriptLab on word online, it works fine. BTW,  the first arg of insertOoxml is string which need .value to get from object.

_$("#setup").click(() => tryCatch(retrieveXML));

let xmlContent = "";

async function retrieveXML() {
await Word.run(async (context) => {
const range = context.document.getSelection();
context.load(range, "text, inlinePictures/hyperlink");
await context.sync();

xmlContent = range.getOoxml();
await context.sync();

const ctrl = range.insertContentControl();
ctrl.appearance = "boundingBox";
ctrl.insertOoxml(xmlContent.value, "Replace");

});
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
try {
await callback();
} catch (error) {
// Note: In a production add-in, you'd want to notify the user through your add-in's UI.
console.error(error);
}
}_

**Comment by sergiubucur** [comment]
@tfjy2008 Thanks for the reply. I updated the code sample (used .value instead of accessing xmlContent directly) and tested it in ScriptLab.

Unfortunately I still get the same result. With ScriptLab, it works in Word Desktop but gives the "documentNotSupported" error in Word Online.

I created a ScriptLab gist (https://gist.github.com/sergiubucur/822ee7b5230c0a172e3d3bc8bf387be5) and updated the original issue description to reflect this.

**Comment by sergiubucur** [comment]
@tfjy2008 After further investigation I can also confirm the functionality works as expected on Word Online, except for one case: if the document being edited is served from SharePoint Online from a document library with the "Require Check Out" setting turned on (in SharePoint Online go to document library settings > Versioning settings > Require Check Out > Set to "Yes").

That's the case where I receive the "documentNotSupported" error.

**Comment by MandytMSFT** [comment]
@sergiubucur then that make sense. We don't support set OOXML on non-coauthorable documents due to the bad merge story

**Comment by sergiubucur** [comment]
@tfjy2008 Thank you very much for the clarification. One last question, are there any plans to support it in the future or is this not on the roadmap at all currently?

**Comment by kbrandl** [comment]
Closing and marking as 'not actionable', per @tfjy2008's most recent comment.
