### ISSUE TITLE
[Word] Bullet list style is not preserved for get/setSelectedDataAsync

### ISSUE THREAD

**Issue by bplowry** [OfficeDev/office-js#604]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
Thank you for your understanding and continued feedback.

In Word I created a document with content like
```
A bulleted list:
• One
• Two
• Three
That is all.
```

Calling `getSelectedDataAsync`, storing the result, and inserting it using `setSelectedDataAsync` with a coercion type of `Office.CoercionType.Ooxml` inserts a snippet with a numbered list.

## Expected Behavior
Inserted snippet retains original bullet list formatting, e.g.
```
A bulleted list:
• One
• Two
• Three
That is all.
```

## Current Behavior
List is changed to a numbered list, e.g.
```
A bulleted list:
1. One
2. Two
3. Three
That is all.
```

## Steps to Reproduce, or Live Example

* Link to live example: ScriptLab https://gist.github.com/bplowry/0f84ed7a0547dcac3f6dfcb4f969408a

* Additional details:
  1. Create a Word document with a bullet list
  2. Select text
  3. Click "Get selection"
  4. Click "Insert selection"

## Context
We want to store a library of snippets for people to use in documents. These should have any relevant formatting, e.g. bold text, headings, lists, tables.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 1906
* Operating System: Windows 10, 1903, build 18362
* Browser (if using Office Online): N/A

## Useful logs
- Parsed ooxml from get (and used in insert): https://pastebin.com/zaQFrEdr

**Comment by kbrandl** [comment]
@bplowry sorry to hear you've run into this issue; thanks for reporting it. 

@weshi FYI, assigning this one to you for investigation (since it's related to Word).
