### ISSUE TITLE
Getting "Unable to get property '_permissionLevel$p$0' of undefined or null reference"

### ISSUE THREAD

**Issue by modestfake** [OfficeDev/office-js#607]
## Expected Behavior
Expected these methods work as documented:
```javascript
window.Office.context.mailbox.item.body.getAsync()
window.Office.context.mailbox.userProfile
window.Office.context.mailbox.getUserIdentityTokenAsync()
```

## Current Behavior
These methods throw TypeError sometimes:
```
Unable to get property '_permissionLevel$p$0' of undefined or null reference
```

## Steps to Reproduce, or Live Example
Unfortunately, I can't reproduce this. I see a lot of them in Sentry logs 9we send all of client-side errors to sentry.io). We run all of those methods after `await window.Office.onReady()`

## Your Environment
* Platform: PC
* Host: Outlook
* Office version number: between `16.0.10727` and `16.0.10730`
* Operating System: Windows
* Browser: IE11 (but probably you use it for Outlook Desktop to render an iframe)

## Useful logs
I see this in our Sentry client-side logs:
![image](https://user-images.githubusercontent.com/16977959/60881328-209fc080-a24e-11e9-89fa-f0bf33d0b185.png)

Stack trace is:
```
TypeError: Unable to get property '_permissionLevel$p$0' of undefined or null reference
  at u.DDA.OutlookAppOm.prototype._throwOnMethodCallForInsufficientPermission$i$0(/lib/1/hosted/outlook-win32-16.02.js:15:172357)
  at u.DDA.OutlookAppOm.prototype.getUserIdentityTokenAsync(/lib/1/hosted/outlook-win32-16.02.js:15:192625)
  at executor(./lib/services/Outlook.js:17:5) // I run one of the methods here
  ...
```

**Comment by ShannonLCapper** [comment]
We were getting these same problems and know one cause, in versions of Windows Outlook that allow pinning. The repro is:
1. From the drafts folder of the Outlook inbox, open the taskpane
2. Pin the taskpane open
3. Click the `Pop Out` button in Outlook's UI (in the upper righthand corner of the mail, to the left of the taskpane)

The draft pops out into a new window and a new taskpane opens there. The old taskpane gets changed to a view that says `Add-in tip: You've popped out your message to see it full screen, use the add-in there`, but the add-in code is still running underneath. When you're in this state, the `window.Office` object becomes unusable. `window.Office.context.mailbox.item` becomes `undefined`, and many other values throw a `Permission Denied` error if you try to read them.

If you go back to the drafts folder underneath (leaving the popped out window open), you can switch to other drafts and the pane will recover. If you go back to the popped-out mail item though, everything blows up again.

You can also pop out multiple mails, and the taskpane in the drafts folder will work correctly on non-popped mails but throws errors when popped ones are selected.

**Comment by ShannonLCapper** [comment]
We have worked around this by setting up an `ItemChanged` event listener on the mailbox, as the event handler will get triggered when the user clicks `Pop Out`. In our event handler, we check to see if `Office.context.mailbox.item` is undefined, and if so, we just programmatically close the taskpane via `Office.context.ui.closeContainer()`.

This isn't super ideal from a UX perspective because it unpins the add-in, but it at least prevents a ton of alert spam and code breakage.

**Comment by kbrandl** [comment]
@modestfake thanks for reporting this issue, and @ShannonLCapper thanks for providing the additional info as well. 

@exextoc FYI, assigning this to you for investigation.

**Comment by exextoc** [comment]
@modestfake can you try what @ShannonLCapper suggested? If that doesn't work, let us know to further assist you.

**Comment by modestfake** [comment]
@exextoc I've tried what @ShannonLCapper suggested. It kind of work, now we have a way fewer errors than before. But still, we have some. I've noticed that it happens not only when you open Draft folder and then back to the inbox. Sometimes it happens when I switching between any other folders like Deleted or Sent.

So, it's better now, but still an issue for us because it's not an ideal UX solution. Thank you @ShannonLCapper though 🙂

**Comment by exextoc** [comment]
Sorry to clarify, when you have a pinned add-in, you should be listening to the ItemChanged event.  Office.context.mailbox.item will have a value IF there is a valid item in the reading pane. IF there is no valid item in the reading pane, then Office.context.mailbox.item will be set to NULL. This can happen if an unsupported item is clicked on, or you click on something that doesn't display an item. (like a header). 

You should Handle the NULL item event as you see fit. Calling any APIs while the Item is null will result in errors.

**Comment by ShannonLCapper** [comment]
Would it be possible to update the documentation so that others know that this is a case they need to handle? Right now the [documentation](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=office-js#item) makes it sound like Office.context.mailbox.item will always be defined

**Comment by exextoc** [comment]
The documentation for pinnable taskpane [here](https://docs.microsoft.com/en-us/outlook/add-ins/pinnable-taskpane#handling-ui-updates-based-on-currently-selected-message) mentions the null check.
