### ISSUE TITLE
How to create an installer to Sideload Web Add-ins for external (beta) users

### ISSUE THREAD

**Issue by david-ps** [OfficeDev/office-js#608]
It is unclear to me how to facilitate a beta program with typical external users (to the organization) if the only way to deploy the Web Add-in for testing is have them Sideload it (via a Network Share) through the complex series of steps described in this article. 

It would be valuable to us to have instructions about if/how to create a Windows Installer that automates these steps could be distributed to external users. Specifically, how to update the Registry to add a Trusted Web Add-in Catalog entry with these settings:
 - Trusted Catalog Address (Catalog URL): \\[Device Name]\[Shared Manifest Folder]
 - Catalog Type = Network share
 - Show in Menu = Yes

Or, are there other options for the use case that could be documented?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ddce0bd-5c66-c2cb-0640-ee4d5bd401c5
* Version Independent ID: b5d4bc26-a43e-4a85-e7d5-fe4fc4ec3d0d
* Content: [Sideload Office Add-ins for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins)
* Content Source: [docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Rick-Kirkham** [comment]
Internal item: 3479342

**Comment by david-ps** [comment]
@Rick-Kirkham @JuaneloJuanelo thanks for moving this forward. We are seeking to build an installer rather than a powershell script if possible, so documenting the key step of using code to CRUD an entry to the Office Trusted Web Add-in Catalog is also important because it is nowhere to be found in my searches. FYI @lliu113

**Comment by david-ps** [comment]
@dmahugh FYI

**Comment by david-ps** [comment]
@Rick-Kirkham @dmahugh Any update or ETA on this? Just some documentation about using code to CRUD an entry to the Office Trusted Web Add-in Catalog would be great.

**Comment by JuaneloJuanelo** [comment]
@david-ps  one thing that you can try to avoid this, is that you can deploy your add-in to the store as hidden. this means people will be able to use a key to find the add-in on the store.. i think this is the simplest way to expose your add-in to beta-testers. 

is this an option for you?

**Comment by JuaneloJuanelo** [comment]
this seems to be more of a documentation of issue of the registry entries we need to enable a file share catalog.. something i think we can deliver promptly.

**Comment by david-ps** [comment]
@JuaneloJuanelo Thanks, I read the [Choose Visibility](https://docs.microsoft.com/en-us/windows/uwp/publish/choose-visibility-options) documentation and also the user comment/complaint tickets about it as a vehicle for engaging Testers (not good). 

I also assume that the product has to get Appsource approval to get it in there? We are seeking feedback and private testers with an early version that is not ready for that level (we assume) of acceptance scrutiny. So, developing a Sideload installer seems to be the better option if all of the above is true? 

@Rick-Kirkham can the documentation we requested be available promptly?

**Comment by Rick-Kirkham** [comment]
@david-ps 
This is a sample reg file that Juan sent me offline. You can send it to each of the beta testers and have them run it on their computers. Be sure to replace the `share` and `folder` placeholders.

I'll create a work item to put this in the documentation, but we've never had any other requests for this, so it's not going to be a high priority. 

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\WEF\TrustedCatalogs\{3B114B16-665F-4CF2-9794-81430FAC24A6}]
"Id"="{3B114B16-665F-4CF2-9794-81430FAC24A6}"
"Url"="\\\\share\\folder"
"Flags"=dword:00000001
```

**Comment by david-ps** [comment]
@Rick-Kirkham Thanks for the registry entry format, we have used it successfully. 
We note that the Key Name and "Id" are arbitrary and can be substituted without an issue. 
We will develop a Sideload Shared Folder Web Add-in Installer. 
At this stage we do not require further documentation or support but others may find the idea of an installer of interest. Thanks again for your help.

**Comment by Rick-Kirkham** [comment]
This is now documented and you should see the change in the next few days in this article: https://docs.microsoft.com/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins
