### ISSUE TITLE
ChartFill

### ISSUE THREAD

**Issue by jamestm27** [OfficeDev/office-js#609]
When will transparency be available for ChartFill (https://docs.microsoft.com/en-us/javascript/api/excel/excel.chartfill?view=office-js)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3b58c05c-4e49-dbad-70a5-3060e52a96ed
* Version Independent ID: 413ee37a-a6db-0f8f-265c-94af0469f0bf
* Content: [Excel.ShapeFill class - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/excel/excel.shapefill?view=office-js#feedback)
* Content Source: [docs/docs-ref-autogen/excel/excel.shapefill.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/excel/excel.shapefill.yml)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by grangeryy** [comment]
Transparency is not supported yet and we are using feature 3480572 to track the request.

**Comment by lumine2008** [comment]
Let's use voice user to track the feature-related ask. 
Could you please create a UserVoice, https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?category_id=163563 
So I am closing this bug for now. thanks.

**Comment by jamestm27** [comment]
Thanks for letting me know, we were using the bug below to track:

https://office.visualstudio.com/OC/_workitems/edit/3480572/?triage=true
