### ISSUE TITLE
Data collection from office-js

### ISSUE THREAD

**Issue by roebuk** [OfficeDev/office-js#61]
Hi,

I've noticed that when I include the script for the office integration a POST request is sent to the following address https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-type=application/bond-compact-binary&client-id=NO_AUTH&sdk-version=AWT-Web-JS-1.1.1&x-apikey=db334b301e7b474db5e0f02f07c51a47-a1b5bc36-1bbe-482f-a64a-c2d9cb606706-7439&client-time-epoch-millis=1518000010111&time-delta-to-apply-millis=use-collector-delta

This happens for both the debug version (https://appsforoffice.microsoft.com/lib/1.1/hosted/office.debug.js) and the production version (
https://unpkg.com/@microsoft/office-js/dist/office.js) 

This  request appears to be collecting a fair amount of data.

1. Can you please be transparent about what data you're collecting and why you're collecting it. 
2. Is this data collection 'feature' documented any where?
3. Can I turn this 'feature' off?
3. What impact, if any, does this have on my users when GDPR compliance comes into force in May?

Thank you.

**Comment by Zlatkovsky** [comment]
Adding @trmini.  And also @kbrandl and @Rick-Kirkham to make sure this is documented (if it's not already)

**Comment by Rick-Kirkham** [comment]
I'll created a VSO item for this work. For MS internal folks only: https://office.visualstudio.com/OC/_workitems/edit/2141899

**Comment by thinksysprem** [comment]
I would really like the answer to the question 

> Can I turn this 'feature' off?

Our application is making a request to 'https://telemetryservice.firstpartyapps.oaspapps.com/telemetryservice/telemetryproxy.html' due to the inclusion of 
`<script` `src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js"></script>`

1. It is interfering with our requests and causing some trouble while loading it. 
2. Even if we get around it, we would really like to give the control to the user, whether they want the telemetry to happen. So, at the user's discretion we can turn this feature on/off.

**Comment by roebuk** [comment]
Seen as GDPR is now in force and data is being collected without the users explicit, I see this as a clear violation of GDPR. An update on this would be greatly appreciated.

**Comment by PhilSmail** [comment]
**1.	Can you please be transparent about what data you're collecting and why you're collecting it.**

[Phil] The data we are collecting is to ensure that our infrastructure is healthy and that there aren’t specific add-ins causing customers issues. The data we are sending and collecting is in compliance with GDPR per our privacy policy

**2.	Is this data collection 'feature' documented any where?**

[Phil] Not in detail other than what is covered by our privacy policy

**3.	Can I turn this 'feature' off?**

[Phil] We are working on a feature to allow a customer to turn off the feature within the Office Client. It won’t be exposed as a developer option to turn on/off per add-in. This does not impact the current level of GDPR compliance of the feature

**4.	What impact, if any, does this have on my users when GDPR compliance comes into force in May?**

[Phil] The relationship for this data is between Microsoft and the customer. As for any other data collected by Microsoft the customer can request a Data Subject Request (DSR) to request an Export/Delete of the data

**Comment by JuaneloJuanelo** [comment]
at this point all questions are answered.

**Comment by smndtrl** [comment]
Any update on office client feature to turn off the telemetry?

**Comment by Tyler-H** [comment]
Just found that this is running every 10 seconds or more frequently on Microsoft Planner (https://tasks.office.com/ - which, can we talk about the inconsistent URL scheme for that and Stream vs other Office URLs?), which over a three day period amounted to over **28,000** requests for an idle website on an inactive computer. This is the kind of thing that ought to happen *once*: on page load.

**Comment by slgray** [comment]
> I would really like the answer to the question
> 
> > Can I turn this 'feature' off?
> 
> Our application is making a request to 'https://telemetryservice.firstpartyapps.oaspapps.com/telemetryservice/telemetryproxy.html' due to the inclusion of
> `<script` `src="https://appsforoffice.microsoft.com/lib/1/hosted/Office.js"></script>`
> 
> 1. It is interfering with our requests and causing some trouble while loading it.
> 2. Even if we get around it, we would really like to give the control to the user, whether they want the telemetry to happen. So, at the user's discretion we can turn this feature on/off.

Hi @thinksysprem , can you tell me how do you work around it.

**Comment by wandyezj** [comment]
Hello @slgray  

Thank you for bringing this issue to our attention,

Could you please share:

* the office application you are developing your Add-In for {Outlook, Excel, PowerPoint, etc...} ? 
* the client you are seeing this issue on {web, Windows, Mac etc..} ?
* the version of the client you are seeing the issue on?

This will help us investigate further,

Have a Terrific Thursday!

**Comment by slgray** [comment]
Hi  @wandyezj 

Thank for your help.

Here are the information you need:

* Our add-in is for Outlook
* Windows client
* We have issue on Office 2013, Office 2016 and Office 365

**Comment by wandyezj** [comment]
Hello @slgray 

Thank you for your patience,

I believe the [previous answer by @PhilSmail](https://github.com/OfficeDev/office-js/issues/61#issuecomment-393228592) covers your telemetry question. On newer builds of Office, users have full/basic control of telemetry events.

We are trying to understand how the request to 'https://telemetryservice.firstpartyapps.oaspapps.com/telemetryservice/telemetryproxy.html' interferes with an application. Could you provide further details?

**Comment by glr0221** [comment]
I know this ticket is closed but a really quick question, how do i disable my addin from dialing into to this url : 'https://telemetryservice.firstpartyapps.oaspapps.com/telemetryservice/telemetryproxy.html' ??

That yields a 404 now if i check the captured data packets.

**Comment by samfrach** [comment]
We are in november 2020, you are working on it since 2018... is it so hard ?

**Comment by Marientus** [comment]
Hello @wandyezj,

could you direct me to a documentation on how to disable telemetry events for a add-in on outlook? The company i work for really does not want these requests to be made at all and looking for a way to disable them fully.

Thanks!
