### ISSUE TITLE
Does the chart in office.js  contain the dataTable attribute?

### ISSUE THREAD

**Issue by zhangchuang1314** [OfficeDev/office-js#610]
Does the chart in office.js Excel contain the dataTable attribute?

**Comment by grangeryy** [comment]
You may find all exsiting supported Chart related js API in [https://docs.microsoft.com/en-us/javascript/api/excel_release/excel.chart?view=office-js](url) 
Could you explain more about your scenarios on dataTable? For example, what's your problem/what you want to achieve by using dataTable?

**Comment by zhangchuang1314** [comment]
> You may find all exsiting supported Chart related js API in [https://docs.microsoft.com/en-us/javascript/api/excel_release/excel.chart?view=office-js](url)
> Could you explain more about your scenarios on dataTable? For example, what's your problem/what you want to achieve by using dataTable?

I add Chart Element menu in Excel to add data table function to the chart. Now I want to use office. JS to implement it. Do you have the corresponding API implementation?

**Comment by zhangchuang1314** [comment]
![image](https://user-images.githubusercontent.com/35564276/60959111-35598280-a33a-11e9-9782-6d7663d81872.png)Functions in similar graphs

**Comment by grangeryy** [comment]
@zhangchuang1314 thanks for providing the snapshot so we can understand the problem. I checked with  js supported Chart type, but unfortunately, Data Table is not supported in current js API yet.
