### ISSUE TITLE
Calling Content addin's from taskpane or custom fuctions

### ISSUE THREAD

**Issue by BeachAlmanack** [OfficeDev/office-js#611]
I cant seem to start the content addin component along with task-panes. Custom function's, dialog box's and task-pane's can all start from the same addin. But adding content to the xml file seems to break it.

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by keyur32** [comment]
Hi, currently content add-ins cannot be hosted within the same add-in that contains a taskpane or a custom function. This feature is on the backlog but no eta yet. I'd propose logging this request on the officespdev.uservoice.com, as we will be able to track it there.

thanks!
