### ISSUE TITLE
getAccessTokenAsync on safari retuns 13001

### ISSUE THREAD

**Issue by fboterov** [OfficeDev/office-js#613]
I'm using OWA in safari and when I call getAccessTokenAsync it return 13001, but it works fine on chrome.

Windows (ie, edge, chrome) works fine.
Windows (Outlook client) works fine.
MAC (chrome) works fine.
MAC (safari) return 13001 I have try to pass { forceAddAccount:true }

## Expected Behavior
Expected result: status:'succeeded' 

## Current Behavior
Actual result: 13001 the user is not signed in Office

## Steps
1. login on outlook in OWA using safari. (I'm using 'The new Outlook')
2. load the add-in

```
<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/beta/hosted/office.debug.js"></script>

Office.onReady().then(function (value) {
   Office.context.auth.getAccessTokenAsync({ forceConsent: false }, function (result) {
      console.log('Checking token: ' + result.status);
   });
});
```

## Context
I'm trying to load the an add-in that works fine in other browsers as I mentioned before.

## Your Environment
* Platform [Mac, Office Online]
* Host [Outlook]
* Office version number: 16.0.10908.10000
* Operating System: OS: 5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15
* Browser (if using Office Online): Safari

## Useful logs
13001 the user is not signed in Office

Thanks, I really appreciate any help

**Comment by niteshgolchha85** [comment]
Can you check if you have 3rd party cookies enabled or disabled on Safari? If disabled, can you follow the instructions given here to enable to repro the issue:
https://www.clubrunnersupport.com/article/710-enable-third-party-cookies-for-safari

**Comment by fboterov** [comment]
Hi,

Thanks for the response,

I have unchecked this and now is working

![mac](https://user-images.githubusercontent.com/11320560/61257196-16d50a80-a7c4-11e9-9a50-b47480292b10.png)

I really appreciate the answer.
