### ISSUE TITLE
[Outlook] Edge IndexedDB API doesn't call back or error out

### ISSUE THREAD

**Issue by yanli0303** [OfficeDev/office-js#615]
Starting from [`Windows 10 ver. >= 1903 / Office 365 ver >= 16.0.11629`](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins), Outlook on Windows use Edge as web control for add-ins. However, sometimes the IndexedDB API doesn't call back or error out.

## Expected Behavior
IndexedDB API should always call back or error out.

## Current Behavior
When IndexedDB writing operations were interrupted by closing Outlook add-in task pane, IndexedDB API doesn't call back or error out next time open the task pane and access IndexedDB.

## Steps to Reproduce, or Live Example

I can't consistently reproduce this problem, but there is 20% chance for Outlook on Windows to behave like below:

- Call out Outlook add-in task pane, in the add-in, perform a lot of IndexedDB writing operations (write at least 2KB data at a time).
- Close the task pane while writing to IndexedDB.
- Call out same Outlook add-in task pane, now:
  - All IndexedDB API requests don't receive a response.
  - If inspect `Storage` with [`Microsoft Edge DevTools Perview`](https://www.microsoft.com/en-us/p/microsoft-edge-devtools-preview/9mzbfrmz0mnj?activetab=pivot:overviewtab), in the `IndexedDB` section, there isn't any database listed.
  - In the `console` of [`Microsoft Edge DevTools Perview`](https://www.microsoft.com/en-us/p/microsoft-edge-devtools-preview/9mzbfrmz0mnj?activetab=pivot:overviewtab), execute code for opening IndexedDB connection never receive response (no callback or error).

**[Please watch this screen recording](https://www.youtube.com/watch?v=43K65pbeDBQ&feature=youtu.be)**

## Context

I'm working on an Outlook add-in which makes use of IndexedDB as client cache storage.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]:  PC.
* Host [Excel, Word, PowerPoint, etc.]: Outlook.
* Office version number: Outlook (Office 364 ProPlus monthly channel) x64 ver. 1906 (Build 11727.20244 Click-to-Run)
* Operating System: Windows 10 Pro x64 ver. 1903.
* Browser (if using Office Online): N/A.

![office-version](https://user-images.githubusercontent.com/3038713/61222633-1582df80-a6e9-11e9-8f50-4191d9cebeea.png)
![windows-version](https://user-images.githubusercontent.com/3038713/61222639-17e53980-a6e9-11e9-9d66-c7d9f12f82d4.png)

**Comment by exextoc** [comment]
I wasn't able to repro this on our end, but it looks like the repro is intermittent. Do you have any idea about anything that you are doing differently to cause it to get into this state? You mentioned that it often repros if you "interrupt" writing to Indexed DB...how are you doing that? Can you repro this in just Edge (not inside outlook) ? (this may help us re-direct this to the right team).

**Comment by yanli0303** [comment]
@exextoc Thanks for looking into this issue. I'm sorry for didn't provide enough details.
I have written sample code for reproducing the issue, see below:

https://codesandbox.io/s/static-z04u2

## Outlook Add-in manifest file pointing to sample code

[outlook-add-in-manifest.xml.zip](https://github.com/OfficeDev/office-js/files/3438823/outlook-add-in-manifest.xml.zip)

## Reproduce Steps

- Install `Windows 10 Pro x64 ver. 1903`.
- In above OS, install `Outlook (Office 364 ProPlus monthly channel) x64 ver. 1906 (Build 11727.20244 Click-to-Run)`.
- Install `Microsoft Edge DevTools preview` from Microsoft Store.
- In above OS, download [outlook-add-in-manifest.xml.zip](https://github.com/OfficeDev/office-js/files/3438823/outlook-add-in-manifest.xml.zip), unzip it.
- In Outlook Desktop app, add custom add-in with unzipped file.
- Call out the add-in main page by clicking `IndexedDB` button in ribbon, DO NOT pin the add-in.
- Click the `Write to IndexedDB`, you should see a message on top of the button appears, like `1 is written`, and keeps changing.
- Close the task pane by clicking on `X` or selecting a different email message.
- Call out the add-in main page again, click the `Write to IndexedDB` button. While it is writing, close the task pane, repeat for a few times.
- When you click the `Write to IndexedDB`, but you don't see the message above it changes, you have reproduced the issue. Now, don't close the task pane but run `Microsoft Edge DevTools preview`, attach to the add-in page.
- In the `Storage` tab, you wouldn't see any database is listed under `IndexedDB`.
- In the `Console` tab, run following code, you probably won't see a number or an error message is printed:

  ```js
  var open = indexedDB.open("issue-615");
  open.onsuccess = (e) => {
      console.log(e.target.result.version);
  };

  open.onerror = (e) => {
    console.log(e.target.error.message);
  };
  ```

**Comment by yanli0303** [comment]
@exextoc BTW, it doesn't seem to be reproducible in Edge browser.

**Comment by yanli0303** [comment]
Hello @exextoc Any updates on this issue?

**Comment by yanli0303** [comment]
Hello, any updates?

**Comment by exextoc** [comment]
Unfortunately there are no real updates. The Edge team found this to be an issue and the bug was added to their backlog. There are no ETAs to share at this time :(

**Comment by exextoc** [comment]
This issue remains in the Edge backlog. Closing since there are no updates at this time.
