### ISSUE TITLE
Excel on Windows - Save 100MB in settings causes out of memory error

### ISSUE THREAD

**Issue by GeorgeHung** [OfficeDev/office-js#621]
Excel on Windows - Save 100MB in settings causes out of memory error

## Expected Behavior
On Excel for Mac and Excel online, save 100MB in setting does not causes the same error.

## Current Behavior
An out of memory error was thrown.

## Steps to Reproduce, or Live Example
* Link to live example: https://gist.github.com/GeorgeHung/97bdb2cddc9ec422ffd26fccc691f14f

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1906 build 11727.20244
* Operating System: Window 7
* Browser (if using Office Online): ______

## Useful logs

▶Error {description: "Out of memory", number: -2146828281, stack: "Error: Out of memory at step (https://script-lab-runner.azureedge.net/:86:24) at Anonymous function (https://script-lab-runner.azureedge.net/:65:46) at Anonymous function (https://script-lab-runner.azureedge.net/:59:9) at Promise (https://unpkg.com/core-js@2.4.1/client/core.min.js:8:11235) at Anonymous function (https://script-lab-runner.azureedge.net/:55:5) at Anonymous function (https://script-lab-runner.azureedge.net/:95:77) at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:24:280300) at o (https://script-lab-runner.azureedge.net/static/js/1.8ccdd024.chunk.js:1:2779061) at Anonymous function (https://script-lab-runner.azureedge.net/static/js/1.8ccdd024.chunk.js:1:2779208) at u (https://script-lab-runner.azureedge.net/static/js/1.8ccdd024.chunk.js:1:298182)"}

 description: "Out of memory"

 message: "Out of memory"

 number: -2146828281

 stack: "Error: Out of memory at step (https://script-lab-runner.azureedge.net/:86:24) at Anonymous function (https://script-lab-runner.azureedge.net/:65:46) at Anonymous function (https://script-lab-runner.azureedge.net/:59:9) at Promise (https://unpkg.com/core-js@2.4.1/client/core.min.js:8:11235) at Anonymous function (https://script-lab-runner.azureedge.net/:55:5) at Anonymous function (https://script-lab-runner.azureedge.net/:95:77) at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js:24:280300) at o (https://script-lab-runner.azureedge.net/static/js/1.8ccdd024.chunk.js:1:2779061) at Anonymous function (https://script-lab-runner.azureedge.net/static/js/1.8ccdd024.chunk.js:1:2779208) at u (https://script-lab-runner.azureedge.net/static/js/1.8ccdd024.chunk.js:1:298182)"

**Comment by RuoyingLiang** [comment]
We tried on several machine with same Office build, but didn't repro. Could you restart your machine to confirm if this is the env problem? If it still repro, could you provide the excel file you used for us to investigate? 
![image](https://user-images.githubusercontent.com/50130769/61365968-3bf87480-a8bb-11e9-8f93-ecc6a553e7d9.png)

**Comment by GeorgeHung** [comment]
Can you try clicking the button more than once?  Sometimes it didn’t happen the first time.

Regards,
George

**Comment by RuoyingLiang** [comment]
We still cannot repro it in our machine? Could you share with us what's the memory size of your machine and the memory changing info when you execute the operation?

**Comment by GeorgeHung** [comment]
Raymond

Is it possible to invite Ruoying to our Weekly meeting next week so he 
can take a look of my environment?

Regards,
George

**Comment by GeorgeHung** [comment]
+Ruoying,

OK, I will forward the invite to Ruoying for next sync meeting.


Thanks,
Raymond

**Comment by MandytMSFT** [comment]
@GeorgeHung I got below words from our official site: https://docs.microsoft.com/en-us/javascript/api/office/office.settings?view=office-js#set-name--value- 

![image](https://user-images.githubusercontent.com/52641972/61604201-27c5c600-ac73-11e9-8ed3-746a039e11a6.png)

We only support 2MB maximum for settings, Could you try settings under 2MB and let me know if the issue still exists

**Comment by RuoyingLiang** [comment]
Hi George, the setting does not support big data set. Please feel free to let Raymond and us know your scenario and discuss what should be the best solution.

**Comment by GeorgeHung** [comment]
Raymond

The meeting was rescheduled one hour early.  I assume you guys won’t make it.  I think it is better check if my use case is supported like Ruoying mentioned.

Regards,
George

**Comment by keyur32** [comment]
Hi some details: 
- Office 2013 has a limit of 2mb, this was removed in 2016 versions and higher. I don't think we did max testing then to see what the new limitations of that would be, but just that it would be constrained just like any other part of the document.

That said what @RuoyingLiang mentioned was accurate that the settings wasn't designed for large sets of data as in your case. Instead the pattern I'd suggest here if you need more than what can be allowed is to persist this data on a customxml part/hidden sheet/or backend (as large files won't load on Excel Online)

**Comment by kbrandl** [comment]
Closing this issue, as it seems like it's been addressed via the comment thread.
