### ISSUE TITLE
SupportSharedFolders stopped working

### ISSUE THREAD

**Issue by vamsii6116** [OfficeDev/office-js#622]
I have 1904 outlook version. We updated for testing `SupportSharedFolders`. We created a web add-in for Outlook meetings. By using 1904 version delegated calendars are able to see Add-in for delegated calendars too. This feature worked in May and part of June month. Since 3 weeks ago, suddenly this stopped working. Not sure if preview feature is changed or stopped working.

## Expected Behavior
Delegated calendar should see Add-in as we are using 1904 outlook version on testing machines

## Current Behavior
Add-in is disabled for disabled calendars

## Steps to Reproduce, or Live Example
```
   <Hosts>
      <Host xsi:type="MailHost">
        <DesktopFormFactor>
          <SupportsSharedFolders>true</SupportsSharedFolders>
          <!-- Location of the Functions that UI-less buttons can trigger (ExecuteFunction Actions). -->
          <FunctionFile resid="functionFile" />
          <!-- Message Compose -->
          <ExtensionPoint xsi:type="AppointmentOrganizerCommandSurface">        
            <OfficeTab id="TabDefault">
              <Group id="msgComposeGroup">
                <Label resid="groupLabel" />
                <Control xsi:type="Button" id="msgComposeOpenPaneButton">
                  <Label resid="paneComposeButtonLabel" />
                  <Supertip>
                    <Title resid="paneComposeSuperTipTitle" />
                    <Description resid="paneComposeSuperTipDescription" />
                  </Supertip>
                  <Icon>
                    <bt:Image size="16" resid="icon16" />
                    <bt:Image size="32" resid="icon32" />
                    <bt:Image size="80" resid="icon80" />
                  </Icon>
                  <Action xsi:type="ExecuteFunction">
                    <FunctionName>InsertTemplate</FunctionName>
                  </Action>
                  <!--<Action xsi:type="ShowTaskpane">
                    <SourceLocation resid="messageComposeTaskPaneUrl" />
                  </Action>-->
                </Control>
              </Group>
            </OfficeTab>
          </ExtensionPoint>

          <!-- Go to http://aka.ms/ExtensionPointsCommands to learn how to add more Extension Points: MessageRead, AppointmentOrganizer, AppointmentAttendee -->
        </DesktopFormFactor>
      </Host>
    </Hosts>
```

## Context
This issue is affecting our production deployment of web add in for global testing

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Outlook 365
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 1904 build 11601.20204
* Operating System: Windows 10

**Comment by kbrandl** [comment]
@vamsii6116 sorry to hear that you've run into this issue; thanks for reporting it.

@exextoc FYI, assigning this one to you for investigation (since it's related to Outlook).

**Comment by exextoc** [comment]
The SupportsSharedFolder feature has not shipped yet. It has been flighted to certain audiences and rolled back from certain audiences due to issues that we found, and may continue to do so until we announce release to production. (I do not have a date to share yet). It currently is only at the Insiders level of release, and may change going forward.
