### ISSUE TITLE
Height of outlook add-ins is 150px in Safari

### ISSUE THREAD

**Issue by kingcpro** [OfficeDev/office-js#623]
Platform: Mac OSX Mojave (latest)
Product: Outlook Web
Version: Safari 12.1.1

In Safari, the height of add-ins panel is 150px, while in other browsers(chrome, IE) is 100% . So html elements will be overlapped when the maximal height is only 150px.

BTW, after I switched back to old Outlook in Safari, it worked well.

Snapshots:
[1] https://pasteboard.co/IokN8aM.jpg
[2] https://pasteboard.co/IokNKI2.jpg

**Comment by ghost** [comment]
Can replicate in High Siera running Safari 12.1
All add-ins take up a fraction of the side panel.

**Comment by exextoc** [comment]
Thanks for reporting the issue. We are looking into it. We will get back on this.

**Comment by Bartlebyy** [comment]
Yes, our Calendly application is experiencing this too. Any update on this?

**Comment by Bartlebyy** [comment]
@exextoc Yes, our Calendly application is experiencing this too. Any update on this?

**Comment by Bartlebyy** [comment]
@exextoc @lliu113 Yes, our Calendly add-in is experiencing this too. Any update on this?

**Comment by JefCurtis** [comment]
@exextoc The Clio add-in is having the same issues. In fact, it was one of the reasons our lest review submission was rejected!

**Comment by wilcotroost** [comment]
We experience the same problem with our TimWeb AddIn. Beside the fixed height of 150px we also see a visual correction of the width after opening the addin. It start slightly wider and corrects automatically to the normal width. I hope this get's some attention soon...

**Comment by nathandpeterson** [comment]
@exextoc Hi, we are also experiencing this bug in Safari. The height of the iFrame is only 150px. We would appreciate an update on this serious issue. Thanks so much.

**Comment by exextoc** [comment]
@nathandpeterson the fix has been made and should be available in production within the next 2 weeks.
