### ISSUE TITLE
Error : InvalidOperationInCellEditMode: Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again.

### ISSUE THREAD

**Issue by soorajhealthplotter** [OfficeDev/office-js#625]
I open up the excel workbook and opens sheet January and load my Excel Add in.

I have to execute code to load bulk data(nearly 3000 data) into my January sheet(by using a button click in my add-in)

Now i click on the button to populate data

Before the data is populated to Jauary sheet, i go to February sheet and add data to columns.At this tima a Error came and my data loading to January sheet got stuck.The error came when context.sync is called

Details of Error is 

InvalidOperationInCellEditMode: Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again. 

My code

Excel.run((context) ->
  sheet = context.workbook.worksheets.getItem("January")
  angular.forEach obj, (key, value) ->
    range = sheet.getRange(value)
    range.values = [[ key ]]
  context.sync().then ->
    # close loading icon
    return
).catch (error) ->
  console.log 'Error: ' + error

**Comment by RuoyingLiang** [comment]
If you are in cell edit mode, JS API cannot execute in the Excel. You can check if you are in a cell edit mode, most actions in ribbon are disabled. So does Office Add-in APIs.

**Comment by RuoyingLiang** [comment]
Will log an item for this request. Thanks
