### ISSUE TITLE
Same session across different workbooks

### ISSUE THREAD

**Issue by soorajhealthplotter** [OfficeDev/office-js#628]
Threre are two workbooks(Workbook 1 and Workbook 2). 

I open up Workbook1. Using the add in i log-in to my application in Task pane.There is a button that i fetch the data from database and populate into the sheet.(takes around 2 min to fetch data)

At the same time I open up Workbook2.Loading the add-in will log-in to my application.When i click on the button to fetch data 

Now the the data is not getting populated in both sheets and stucks

## Expected Behavior
For Workbook1 and Workbook2 the data should be populated simutaneously

## Current Behavior
I open up Workbook1. Using the add in i log-in to my application in Task pane.There is a button that i fetch the data from database and populate into the sheet.(takes around 2 min to fetch data)

At the same time I open up Workbook2.Loading the add-in will log-in to my application.When i click on the button to fetch data 

Now the the data is not getting populated in both sheets and stucks

## Your Environment
* Platform [PC desktop, Mac]
* Host [Excel]
* Operating System: OSX,Windows

**Comment by RuoyingLiang** [comment]
Is that possible you could share your add-in/code with us to help us investigating? What API are you using? Is that repro in both PC and MAC?
