### ISSUE TITLE
F12 in windows can not work

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#629]
## Expected Behavior

F12 in windows 10 1803 it's fine.but in windows 10 1903 not work.

## Current Behavior

my windows update to windows 10 1903 (18362.239)
when i open my excel add-ins and open F12 tool. it's nothing.
![image](https://user-images.githubusercontent.com/3963826/61447195-0f0f9480-a983-11e9-948f-b73f87077006.png)
![image](https://user-images.githubusercontent.com/3963826/61447292-3e260600-a983-11e9-9db7-290a9fcdc0b6.png)

**Comment by ragavanrajan** [comment]
May be you need to check your **office version** and the below official link 
https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

**Comment by dinglicoding** [comment]
@ragavanrajan  thank you  

i found,the new windows version use edge browser.
