### ISSUE TITLE
IE11: SVGElement doesn't support property or method focus.

### ISSUE THREAD

**Issue by zelliott** [OfficeDev/office-js#63]
Method `focusToNextTabbable` in `excel-web-16.00.js` needs to check if method `focus` is defined before calling `focus()`.  In IE11, calling `focus()` on an `SVGElement` throws: _Object doesn't support property or method “focus"_.  This exception prevents the user from tabbing through the DOM.

## Expected Behavior

Attempting to tab through SVG elements should not throw exceptions

## Current Behavior

See the general summary above.

## Steps to Reproduce, or Live Example

Working on adding easy repro steps.

## Context

This issue effects the accessibility of our add-in.  Users rely upon proper tab order to tab through web apps.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: N/A
* Operating System: Windows 10
* Browser (if using Office Online): IE11

## Useful logs

![image](https://user-images.githubusercontent.com/4220717/36109726-21dbd662-0fd5-11e8-96e9-6f444974fa09.png)

**Comment by Zlatkovsky** [comment]
@zelliott , to clarify:  your issue seems to describe IE11, but the very first sentence mentions `excel-mac-16.00.js`.
Did you mean https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.js (and its correponding https://appsforoffice.microsoft.com/lib/1/hosted/excel-win32-16.01.debug.js as the nonminified version) instead?

**Comment by zelliott** [comment]
@Zlatkovsky Whoops- I edited the post above.  I meant `excel-web-16.00.js`.

**Comment by Zlatkovsky** [comment]
@zelliott , it sounds like you have an example app that exhibits that behavior?  could you give a link to it (or to a minimal repro thereof)?

Also, can you describe the exact sequence of how you are hitting this exception?  Is it that you're tabbing through elements on your add-in, and when you hit an SVG element it throws the error?
Does it look like the error is just a "side effect", or does it end up aborting a particular operation?  I.e., if we did have a check before `focus()` and didn't call it -- would that actually help?  Have you tried it manually using F12 developer tools, skipping over that bit of logic?

Thanks!
