### ISSUE TITLE
What is the alternative of Office Dialog ?

### ISSUE THREAD

**Issue by GopalZadafiya** [OfficeDev/office-js#630]
**What is the alternative of Office Dialog ?** 

- I am trying to implement web add-in support for Exchange 2013 accounts in Outlook web app(Outlook web Access).
- Our add-in is working completely fine with Office 365, Outlook Desktop and Mobile as well.
- Dialog API is not supported for my requirement currently. As per the documentation It is supported for Mailbox > 1.3. But as I am using exchange 2013 accounts in Outlook web App(Outlook web Access) for that Mailbox version is 1.1. So I have to go for some classic popup mechanism.
  Ref: https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=office-js
- Even I tried running Office.context.requirements.isSetSupported("DialogApi",1.1) to check If It is supported or not. It returned false.
- We have Angular 6 SPA that redirects to Identity Server for authentication.
- So I am trying to implement the same for my case But after clicking on Signin, popup is opened but redirection to identity server is being blocked.

**Comment by danielgwilson** [comment]
Hi there,

It's possible you could use `window.open()` or `window.openDialog()` directly—otherwise, unfortunately, Dialogs in Exchange 2013 / Mailbox 1.1 aren't something we plan to support.

**Comment by GopalZadafiya** [comment]
For my angular SPA, `window.open()` is not accepting the routing specified as a url, It redirects to index.html again and then application is broken.

**Update:**
I succeeded to implement authentication with classic pop by using below article.

**Ref:** https://benoitpatra.com/2015/05/28/implementing-the-oauth-2-0-flow-in-app-for-office-sandboxed-environment/

Make sure you are not loading Office.js into app.component.ts (If you are using angular SPA) otherwise It will block the redirection.

**Comment by danielgwilson** [comment]
Great! Glad to hear you got it working.
