### ISSUE TITLE
Roamsettings SaveAsync returns error in outlook 2013 windows - Outlook addin

### ISSUE THREAD

**Issue by kathirvalavan** [OfficeDev/office-js#634]
When I have stored necessary settings and perform 

Office.context.roamingSettings.saveAsync(function (asyncResult) {
                  if (asyncResult.status === Office.AsyncResultStatus.Failed) {
                    // eslint-disable-next-line
                    throw JSON.stringify(asyncResult)

                  }
                  callback();
                  dialog.close();
                });

## Expected Behavior
It should return success status

## Current Behavior
It returns {"value":null,"status":"failed","error":{"name":"GenericSettingsError","message":"Permission denied","code":9019}}

This error happens only in 2013 client windows
This is working in web , mac office 365

**Comment by exextoc** [comment]
This is the same issue as: https://github.com/OfficeDev/office-js/issues/626

A fix is coming out, but it is a client fix so you will need to wait for an update.
