### ISSUE TITLE
Office.context.mailbox.item.dateTimeCreated setted today date in Gmail Linked mailbox

### ISSUE THREAD

**Issue by eSpPulsaqui** [OfficeDev/office-js#638]
## Expected Behavior
In a gmail mailbox linked, getting the Office.context.mailbox.item object I need to get the original message reception date. But I only have dateTimeCreated and dateTimeModified.
## Current behavior
When I get the Office.context.mailbox.item object, it returns the dateTimeCreated and dateTimeModified date set to today, so I cannot know when the mail was received. There are any way to get the original received date?
## Steps to play, or live example
In https://outlook.live.com we must synchronize a gmail email account. We select an email from this mailbox and we get it with the Addin, if we get the data through Office.context.mailbox.item, we will see that it always returns the date of today.

## Your environment
* Platform: Web Browser
* Host: Outlook Live
* Operating system: Windows 10
* Browser: Google Chrome, Internet Explorer, Firefox ...

**Comment by exextoc** [comment]
Mail receive time is not a property that we expose as part of office.Js and there is no plan to expose that in the near future.

**Comment by exextoc** [comment]
Mail receive time is not a property that we expose as part of office.Js and there is no plan to expose that in the near future. We track Outlook add-in feature requests on our user-voice page. Please add your request there. Feature requests on [user-voice](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins) are considered when we go through our planning process.
