### ISSUE TITLE
Office.context.mailbox.item.getAttachmentContentAsync fails with inline attachments

### ISSUE THREAD

**Issue by eneoli** [OfficeDev/office-js#639]
## Expected Behavior
getAttachmentContentAsync should pass an object with the content of the requested attachment to callback.

## Current Behavior
Promise fails with error "Uncaught (in promise) {errorCode: 9020}"

## Steps to Reproduce, or Live Example
 ```
Office.context.mailbox.item.getAttachmentContentAsync(Office.context.mailbox.item.attachments[0].id, (r) => {
            console.log(r);
        });
```
If the attachment is not inline, everything works perfectly.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ? (Outlook online)
* Operating System: linux
* Browser (if using Office Online): Chrome

## Useful logs

  | s | @ | tslib.es6.js:69
-- | -- | -- | --
  | Promise.then (async) |   |  
  | c | @ | tslib.es6.js:70
  | (anonymous) | @ | tslib.es6.js:71
  | l | @ | tslib.es6.js:67
  | dn.<computed> | @ | getAttachmentContentAsyncApiMethod.ts:26
  | mn | @ | executeApiMethod.ts:192
  | (anonymous) | @ | EndpointRegistrator.ts:169
  | invoke | @ | osfruntime.js:2003
  | I | @ | osfruntime.js:1565
  | O | @ | osfruntime.js:1556
  | setInterval (async) |   |  
  | M | @ | osfruntime.js:1693

**Comment by exextoc** [comment]
Do you have some more details on the repro environment? Are you on Outlook Web Access or on Desktop Outlook? Are you doing this on a read or a compose mail? Can you get version numbers? For what it's worth I tried to repro this on Desktop Outlook, and it seems to be working in both Read and Compose mode.

**Comment by eneoli** [comment]
Yes, Iam on Outlook Web Access, doing it on a read mail.
Mailbox MinVersion 1.1
Using latest Office API from CDN

**Comment by exextoc** [comment]
@EneOli  Office.context.mailbox.item.attachments is only available in Read Mode. Docs here- https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/preview-requirement-set/office.context.mailbox.item#attachments-arrayattachmentdetails

So In Read Mode this code will work-
```
Office.context.mailbox.item.getAttachmentContentAsync(Office.context.mailbox.item.attachments[0].id, (r) => {
           console.log(r);
       });
```

In Compose Mode, you can get attachment content using below code -
```
Office.context.mailbox.item.getAttachmentsAsync(callback);
function callback(result) {
  if (result.value.length > 0) {
      Office.context.mailbox.item.getAttachmentContentAsync(result.value[0].id, (r)=>{
           console.log(r);
       });
  }
}
```

**Comment by exextoc** [comment]
Thanks for reporting this issue. We are able to repro this in OWA Read mail. We are working on a fix as quickly as we can.

**Comment by exextoc** [comment]
We have fixed this issue and it is live now.
