### ISSUE TITLE
getFileAsync() returns different document.xml with Word online vs Word desktop

### ISSUE THREAD

**Issue by harry-levick** [OfficeDev/office-js#640]
I am using the getFileAsync() method to get the document that is open in the current instance of Word. However, in testing this method, the document returned from the method when called in Word desktop is different to the document returned from the method when called in Word online. With Word online returning the exact same document.xml as that of the original document.

## Expected Behavior

The implementation of the method works fine when invoked in Word online, since the document returned (document.xml) is the same as that of the document which I originally opened in Word online.
I expect the same to be the case when calling the same method but from inside Word desktop.

## Current Behavior

However this returns a drastically different document.xml

Here is the [Original Document.zip](https://github.com/OfficeDev/office-js/files/3432010/Lorem_Ipsum_Original.-.Copy.zip), which I opened in Word (before opening the current document via code).
Here is the [Document Via Word Online.zip](https://github.com/OfficeDev/office-js/files/3432021/Lorem_Ipsum_Online.-.Copy.zip), which was returned from the getFileAsync() method when called in Word online.
And Here is the [Document Via Word Desktop.zip](https://github.com/OfficeDev/office-js/files/3432030/Lorem_Ipsum_Local.2.-.Copy.zip), which was returned from the getFileAsync() method when called in Word desktop.

```
function uploadDocument() {
    Office.context.document.getFileAsync(Office.FileType.Compressed,
        function (result) {

            if (result.status == Office.AsyncResultStatus.Succeeded) {

                // Get the File object from the result.
                var myFile = result.value;
                var state = {
                    file: myFile,
                    counter: 0,
                    sliceCount: myFile.sliceCount
                };

                state.file.getSliceAsync(state.counter, function (result) {
                    sendSlice(result.value, state);
                });
            }
        });
}

function sendSlice(slice, state) {
    var documentBase64 = base64ArrayBuffer(slice.data);
    // Continue to take base64 string and upload...
}
```

## Context

I wish to upload the .docx document to an online server, which can then be retrieved in the future. However, on re-download, the changes in the document caused by the getFileAsync() in Word desktop cause the document to be corrupted (by fault of the code which is returning the document from the server). However the same is not the case for the document uploaded from Word online. 

This appears to be a bug to me, and has already been raised before (but was dismissed).

I am not able to alter the code which retrieves the document, however, I shouldn't need to do so, because it works fine for the original document. It is just the alterations made by Word desktop which causes this to happen.

**Comment by JuaneloJuanelo** [comment]
yeah there is no guarantee that the OOXML payload will be exactly the same across platforms, even cross sessions you can also find differences, for many reasons revision among others, coauth revision ids and dozens of different compare/merge code paths.

but the OOXML should open, I tried your documents and they look 100% exactly the same (yeah with a few not needed OOXML  elements) .

how you are retrieving the document is important, not sure how that service delivers you the document, but it will be interesting to compare the OOXML you sent before and the one you retrieve from your service, i would assume is different cause i was able to retrieve an insert your OOXML by picking it from the file system.

**Comment by JuaneloJuanelo** [comment]
closing as this is a by-design issue and non-repro.
