### ISSUE TITLE
Fetching token using `getCallbackTokenAsync` requires mailbox item to be saved 

### ISSUE THREAD

**Issue by JefCurtis** [OfficeDev/office-js#641]
My Outlook add-in can fetch a token just fine using when in a `MessageReadCommandSurface` ExtensionPoint but returns an error when in `MessageComposeCommandSurface`. 
This seems to be the expected behavior when the add-on _doesn't_ have full `ReadWriteMailbox` permission but I _do_ have full permissions and I'm still seeing this error.

## Expected Behavior
While the add-in is running in `MessageComposeCommandSurface` and full `ReadWriteMailbox` permissions are granted, requesting a token should be successful.

## Current Behavior
Instead, the results is an error:
```
{
  "name": "CanOnlyGetTokenForSavedItem",
  "message": "The token can't be retrieved until the item is saved.",
  "code": 9029
}
```

## Steps to Reproduce, or Live Example
1. Run an add-in in Outlook when in the compose view
1. The add-in is given full permissions (`ReadWriteMailbox`)
1. The current mailbox item has not been saved
1. Request a REST API token using `getCallbackTokenAsync`
1. Expect a response with a token and not an error

## Context
The add-in has functionality that allows a user to scan their inbox and select emails from a list to be archived to a third party service. This functionality works fine with-in `MessageReadCommandSurface` but does not work in the compose mode. 

## Your Environment

* Platform: Desktop Windows, Mac, browser, every environment I've tried
* Host: Outlook
* Office version number: Outlook 1902 (Build 11328.20368)
* Operating System: Win10, MacOS Mojave
* Browser (if using Office Online): Chrome, Safari

## Useful logs
This issue can also be shown [here](https://stackoverflow.com/questions/51004240/can-i-fetch-a-rest-token-while-in-messagecomposecommandsurface-in-outlook-javasc/51009892?noredirect=1#comment100937444_51009892) on Stackoverflow

**Comment by exextoc** [comment]
@JefCurtis To get accessToken in compose mode use below code. The item must be saved in order to get a token. Once a save call has been successfully made, you should be able to get a token. Please let us know if you still see the error after saving-

```
Office.context.mailbox.item.saveAsync
(
	function(asyncResult1)
	{
		console.log(JSON.stringify(asyncResult1));
		Office.context.mailbox.getCallbackTokenAsync(
			function (asyncResult2)
			{
				console.log(JSON.stringify(asyncResult2));
			}
		);
	}
);
```
