### ISSUE TITLE
Excel Desktop - Office.context.document.settings.saveAsync() didn't persist settings 

### ISSUE THREAD

**Issue by ravikmrsingh8** [OfficeDev/office-js#642]
Shared office API for saving settings didn't work for excel desktop version 1908 (build 11903.20002 C2R). When excel file is reopened then it did not persist the saved settings. 
I am able to do Office.context.document.settings.set('key', value) and the call Office.context.document.settings.saveAsync(callback) also succeeded, but with excel these settings never seem to persist.
## Expected Behavior
the state should be saved and the next time when we open the document we should retrieve the saved values

## Current Behavior

When excel file is reopened then saved values from API settings.saveAsync() couldn't retrieve.
 
## Steps to Reproduce, or Live Example
save settings using function
function createSetting() {
    Office.context.document.settings.set("Foo", "bar");
    Office.context.document.settings.saveAsync();
}

to retrive use function
function readSetting() {
    console.log(Office.context.document.settings.get("Foo"));
}
readSetting prints null 

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

Any content add-in using office API won' t be able to persist settings 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ____PC desktop__
* Host [Excel, Word, PowerPoint, etc.]: ___Excel___
* Office version number: ____1908__ (build 11903.20002 C2R)
* Operating System: _____Windows_
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by JuaneloJuanelo** [comment]
known issue the team is working on a fix. (btw released today on insiders fast, please give it a try!)

**Comment by ravikmrsingh8** [comment]
![image](https://user-images.githubusercontent.com/22787917/62188228-65200700-b389-11e9-94a2-de4673cbe6cc.png)
Verified  with this build, I could not repro the issue there.

Thank you Juanelo : )

**Comment by ravikmrsingh8** [comment]
Hi @JuaneloJuanelo ,

Could you please let us know the office versions where we have the save issues for office settings. Also from which version this issue was fixed.
We have an Excel Addin which is near GA and we don't want users to encounter this.

Thanks,
Ravi

**Comment by JuaneloJuanelo** [comment]
16.0.11727.20286 +
