### ISSUE TITLE
getAttachmentContentAsync does not invoke callback on android app

### ISSUE THREAD

**Issue by eneoli** [OfficeDev/office-js#645]
## Expected Behavior
The passed callback should be called, like on other platforms like OWA or Outlook Desktop

## Current Behavior
The callback doesn't get called using the Add in with the Outlook android app. Using the exactly same code on OWA or Desktop works perfectly.

## Steps to Reproduce, or Live Example

> Office.context.mailbox.item.getAttachmentContentAsync(id, () => {
>         console.log('callback called');
> });

Tested on two android phones with Android 9

## Context
Passing attachments from mail to our web app (Read mail)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Android App
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: latest app version from Play Store
* Operating System: Android 9
* Browser (if using Office Online): X

## Useful logs
No errors, no warnings, nothing. Seems like the callback just not gets called.

Is it possible, that the callback is not called because of Office.context.mailbox.ewsUrl  not available on Android?

**Comment by kapgupt** [comment]
@EneOli right now, Outlook mobile only support API level requirement set 1.5. So this API is not supported as of now in Outlook Mobile(Android or iOS).

**Comment by JuaneloJuanelo** [comment]
@EneOli  we recommend you to check for this requirement at runtime and when supported on such platform your code will just work.

**Comment by GarryLowther** [comment]
It is not just an Android problem. Our getAttachmentContentAsync code to read attachments works perfectly in Outlook Web, but the installed Outlook throws an error: "the operation is not supported"
