### ISSUE TITLE
Table co-authoring

### ISSUE THREAD

**Issue by CreaQuora** [OfficeDev/office-js#646]
I think there is an error when entering data into the Excel table at the same time (co-authoring). When I add a row to the table on one computer, it appears outside the table on the other. It is likely that the table scope definition will not change when you update the workbook. Sheet is protected … this may be the reason too.
The macro makes those changes. With manual changes, worksheet is locked and unlocked on both computers, so it works correctly without a macro.
This is probably the wrong place to describe my issue, but I got here from https://docs.microsoft.com/en-us/office/dev/add-ins/excel/co-authoring-in-excel-add-ins

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by JuaneloJuanelo** [comment]
@kbrandl  this sound like an issue in Excel coauth team. I think its not related whatsoever with JS APIs or Web Add-ins.
