### ISSUE TITLE
Taskpane is not opening with specified width after adding RequestedWidth in manifest.xml

### ISSUE THREAD

**Issue by rake93** [OfficeDev/office-js#647]
I'm facing Drop down items wrapper issue in Office Word-addin. Dropdown values are not properly aligning when the Taskpane has been loaded. So I added the  RequestedWidth in manifest.xml to open the panel with specified width. But the below code is not working. Could you please suggest me to open the Task Pane with specified width.
```
<DefaultSettings>
    <SourceLocation DefaultValue="https://localhost:3000/index.html" />
	<RequestedWidth>500</RequestedWidth>
  </DefaultSettings>
```

## Expected Behavior

![image](https://user-images.githubusercontent.com/823725/62450617-aa05be00-b73a-11e9-9a6c-ec4013e8369b.png)

## Current Behavior
![image](https://user-images.githubusercontent.com/823725/62450701-ce619a80-b73a-11e9-932f-c3491fd81524.png)

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2016
* Operating System: Windows
* Browser (if using Office Online): NA

## Useful logs

- [ ] Console errors
- [1] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by JuaneloJuanelo** [comment]
@rake93 Today is not possible to start an **task pane** add-in with a specific width. The requestedWidth and requestedHeight elements are only applied on **Content** Add-ins.

**Comment by ralphtheninja** [comment]
> The requestedWidth and requestedHeight elements are only applied on Content Add-ins.

@JuaneloJuanelo Why is this the case? Is there any way we can provide feedback for this?

**Comment by buzzo123** [comment]
any news about this?

**Comment by festina-lente-z** [comment]
any news about this?

**Comment by MohamedMoussaTTW** [comment]
@JuaneloJuanelo Why did you close this? We need resizable task panes.

**Comment by al-scion** [comment]
Checking on this. Any updates?

**Comment by muralimadduTR** [comment]
Any updates on this pls?
