### ISSUE TITLE
Imagecoercion in Excel Online is missing

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#648]
## Expected Behavior
Office.context.requirements.isSetSupported("imagecoercion", "1.2") should be true in Excel Online
see [documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-in-availability)

## Current Behavior
Office.context.requirements.isSetSupported("imagecoercion", "1.1") == false
Office.context.requirements.isSetSupported("imagecoercion", "1.2") == false

## Context
We're checking in our app if the host supports inserting images. Currently we can't insert images on Excel Online anymore as Excel returns that it doesn't support images.

## Your Environment
* Platform: Office Online
* Host: Excel
* Browser : Chrome

## Useful logs
![image](https://user-images.githubusercontent.com/6338132/62460951-b82bfc80-b783-11e9-84b2-52be261b0e6a.png)

**Comment by lumine2008** [comment]
Thanks @barisbikmaz , i just verified, this issue can repro in my side. i created a bug (3537516), team is looking into this issue.

**Comment by lumine2008** [comment]
Hi @barisbikmaz, based on our engineering team investigation, we found we do no support imagecoercion for Excel online, therefore the documentation has an issue, we will fix the document issue. thanks for your understanding.

**Comment by barisbikmaz** [comment]
Thanks for the info.

**Comment by AlexJerabek** [comment]
For closure, the documentation will be fixed with this PR: https://github.com/OfficeDev/office-js-docs-pr/pull/1244

**Comment by MandytMSFT** [comment]
@barisbikmaz  @lumine2008  To clarify ,there are 2 issue in the thread and they are not related.

1. Excel online didn't support imagecoercion 1.1 and 1.2. 
2. can't insert images on Excel Online by shape.AddImage.

For 1, as mentioned above, Excel Online didn't support imagecoercion 1.1 and 1.2, we will update the documention. 
For 2, the fixing has checked in today, ideally it will be deployed to production in 1 week. @barisbikmaz I will let you know once it's in Prod, then you can have a try. If i forgot, feel free to ping me.
