### ISSUE TITLE
Status on Preview

### ISSUE THREAD

**Issue by Ballzer0** [OfficeDev/office-js#651]
There are videos on youtube from back in summer of 2017 where you guys first showed off the SSO API.
https://www.youtube.com/watch?v=w0VBrpVXPvk

How come the feature is still in preview? and can we expect it to go live soon?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb06c24b-9d11-9cc5-2e98-561601452638
* Version Independent ID: abda21d9-6e80-8319-c56f-004658014e3c
* Content: [Enable single sign-on for Office Add-ins - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins)
* Content Source: [docs/develop/sso-in-office-add-ins.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/sso-in-office-add-ins.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by niteshgolchha85** [comment]
@Ballzer0 Thanks for your patience. We are actively working to GA SSO API but I don't have a specific date yet. May I know how do you plan to use the SSO API? Do you need it to access Graph? Also, how do your users expect to get your add-in - via store or centralized deployment?

**Comment by niteshgolchha85** [comment]
Closing as there is no response from the the issue author since couple of weeks. @Ballzer0 Please feel free to reopen the issue.
