### ISSUE TITLE
Roaming settings are not synced to iOS devices

### ISSUE THREAD

**Issue by THPubs** [OfficeDev/office-js#652]
## Expected Behavior

- Add some data to the roaming settings.
- Save roaming settings.
- Open the iOS client.

The iOS client should be able to read the saved data from roaming settings.

## Current Behavior

The iOS client don't have the data in it's roaming settings. Tried after several minutes and even after several hours. Also tried closing the iOS client (Clearing the app not just minimizing) and re-opening. Still nothing.

## Steps to Reproduce, or Live Example
I just created a sample plugin and hosted it. The source code can be found here: https://github.com/THPubs/outlook-office-roaming-test

The manifest file of that code points to a real live version of this app. Now,

1) Try to open it in your web client, set a value to roaming settings.
2) Now open the plugin in a mobile client and see. For me, the settings are not transferred to the iOS.

## Your Environment

* Platform: Mac, iOS
* Host: Outlook
* Operating System: OSX 10.14.6, iOS 12.4

**Comment by exextoc** [comment]
Thanks for reporting this issue. This is a recently introduced regression. We are working on a fix.

**Comment by THPubs** [comment]
Thanks

**Comment by ntranvinh** [comment]
Yeah, experient the same issue.
I played around with the Roaming stuff and also found one issue that when I try to set some roamming setting on iOS client, and expect to see the roamming settings appears on Andoird client but it not.

**Comment by exextoc** [comment]
Thanks again for reporting this issue. A fix for this issue was made shortly after this issue was opened and was released soon after that.
