### ISSUE TITLE
displayDialogAsync Doesn't display Web Application in Windows Outlook Client

### ISSUE THREAD

**Issue by jaymaskell** [OfficeDev/office-js#655]
Authentication application does not display properly from displayDialogAsync in Windows 7 Outlook client but does display properly when using OWA with IE 11.  It does display properly on MAC using the Outlook client.  See the MP4 attachments.

The same problem occurs in Windows 10 versions 1803 and 1903.

Authentication application should display the login screen 

## Current Behavior

The authentication application does not display the login form.

## Steps to Reproduce, or Live Example

* Link to live example: ____

You can install the add-in using the following URL:  https://staasf-staging4.shoretelsky.com/outlook-addins/calendar/meeting.manifest.xml .
The add-in appears on new appointments and existing appointment which you previously created.  The button is named "Mitel Meet".

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

Main use case for the add-in is the Windows Outlook client.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______
See attachments and MAC mp4 for version information.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by jaymaskell** [comment]
The URL for the displayDialogAsync is https://staasf-staging4.shoretelsky.com/outlook-addins/calendar/authRedirect.htm which redirects (via window.location.replace) to https://auth.dev.mitel.io/authorize?app_name=Mitel Meet Outlook Add-In&scope=gauth abc&ui_locales=en&client_id=5f7965dc7b0cfadeb09e8ee304209baa&response_type=code&redirect_uri=https://staasf-staging4.shoretelsky.com/outlook-addins/calendar/authRedirect.htm

**Comment by exextoc** [comment]
Could you provide the build numbers for the Outlook desktop clients in which you are seeing this issue?
Also, could you add the lines of code where you call displayDialogAsync?

**Comment by jaymaskell** [comment]
Here is the product information.


[cid:image002.jpg@01D55C28.99738670]


Code calling displayDialogAsync:

                var clHost =auth.dev.mitel.io;

function openDialog() {

    loggingInStatus();

    authCode = null;
    dialog = null;

  var redirectURL = 'https://staasf-staging4.shoretelsky.com/outlook-addins/calendar/authRedirect.htm';
  var authUrl = '#https://' + clHost + '/authorize?app_name=Mitel Meet Outlook Add-In&scope=gauth abc&ui_locales=en&client_id=' + clientId + '&response_type=code&redirect_uri=' + redirectURL;

  console.log('displaydialogAsync: ' + redirectURL + authUrl + '&time=' + Date.now());

  Office.context.ui.displayDialogAsync(redirectURL + authUrl + '&time=' + Date.now(), {
        height: 49,
        width:  25,
   }, dialogCallback);
      }


function dialogCallback(asyncResult) {
    if (asyncResult.status == "failed") {

        // In addition to general system errors, there are 3 specific errors for
        // displayDialogAsync that you can handle individually.
        switch (asyncResult.error.code) {
            case 12004:
                loginError('Failed to open login window', 'Domain is not trusted');
                //app.showNotification("Domain is not trusted");
                break;
            case 12005:
                loginError('Failed to open login window', 'HTTPS is required');
                //app.showNotification("HTTPS is required");
                break;
            case 12007:
                loginError('Failed to open login window', 'A dialog is already opened.');
                //app.showNotification("A dialog is already opened.");
                break;
            default:
                loginError('Failed to open login window', asyncResult.error.message);
                //app.showNotification(asyncResult.error.message);
                break;
        }
    }
    else {
        dialog = asyncResult.value;

        /*Events are sent by the platform in response to user actions or errors. For example, the dialog is closed via the 'x' button*/
        dialog.addEventHandler(Office.EventType.DialogEventReceived, eventHandler);
        dialog.addEventHandler(Office.EventType.DialogMessageReceived, processMessage);
    }
}





Jay Maskell
Software Engineer
Advanced Applications

Email:  Jay.Maskell@mitel.com
Phone: +1 (408) 962-2690

[cid:image003.jpg@01D55C27.143E6110]<http://mitel.com/>

960 Stewart Drive
Sunnyvale, CA, 94085, United States

mitel.com

**Comment by lliu113** [comment]
@jaymaskell  - thanks for providing the code snippet! It looks like you are correctly using the API - we are debugging and will respond once we know more.

**Comment by exextoc** [comment]
The display dialog is correctly redirecting to the URL "https://auth.dev.mitel.io/authorize...". The page is not loading correctly, but there are no errors in the console for the dialog. Are you handling exceptions (such as script errors) that might be occurring?

**Comment by jaymaskell** [comment]
Not sure since this is not my application.  The application is a webpacked Angular application.
It does not explain why the application works properly with IE 11 (OWA) as the client yet fails in the Outlook IE 11 environment.  I did verify the IE build numbers are the same in the two environment.  Are there other IE restrictions when running in the Outlook client which could cause this failure?

**Comment by exextoc** [comment]
There should not be any restrictions on IE when running in the Outlook desktop client.

We debugged your add-in from the platform side, and we did not see any issues with our platform. We did find an error: "Error: Unspecified error" when calling replaceState. The internal Outlook desktop IE browser has does not support the History API. The history.replaceState function is visible but will just throw an “unspecified error” when used. This might be the error that is causing this issue, so we would suggest debugging the add-in to see if this is breaking your navigation.

**Comment by jaymaskell** [comment]
Thanks.

Can you tell me what other JavaScript API's are not supported in the Outlook desktop IE browser? 
These differences should be documented in the displayDialogAsync browser environment since may web applications expect these APIs to exist.

How did you debug this issue?  Is there something more we could have done to find these types of issues?

**Comment by exextoc** [comment]
If you would like to see what JavaScript APIs are supported for your version of Outlook, you can look at what requirement sets are supported [here](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#clients), and then view the supported APIs for those requirement sets. 

The History APIs are not one of the JavaScript APIs for Office. The history APIs are from the DOM Window object. You can read more about the history APIs [here](https://developer.mozilla.org/en-US/docs/Web/API/History_API).

There are instructions [here](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/test-debug-office-add-ins) for debugging your add-in.

**Comment by jaymaskell** [comment]
The history API is part of the Javascript 1.3 engine in IE 11 and has nothing to do with the JavaScript APIs for Office. It's part of the DOM window object.

Our application is an Angular 8 application and does not directly use the history API.  However, Angular components such as the Angular Router do use this API. There could be many other package dependencies using the history object (or other missing DOM APIs)  that  our application requires.

This is a fatal flaw in the displayDialogAsync Windows Outlook implementation because it breaks existing Web Applications.

Can you please provide all of the JavaScript DOM APIs (objects) which have been removed?
This information should be documented in the displayDialogAsync documentation.

**Comment by exextoc** [comment]
Thank you for pointing out this issue. We will pass along this information to our documentation team.
