### ISSUE TITLE
Scroll bar of ScrollablePane(from Fabric) is missing on Excel task-pane

### ISSUE THREAD

**Issue by mm90849491** [OfficeDev/office-js#656]
## Expected Behavior
Vertical scroll bar shall present.

## Current Behavior
Vertical scroll bar is missing in Excel with Edge.

## Steps to Reproduce, or Live Example
I put the Fabric documentation page (https://developer.microsoft.com/en-us/fabric#/controls/web/scrollablepane) in Excel, and the following screen-shot is the result:
![2019-08-06 13_09_26-](https://user-images.githubusercontent.com/10732375/62584550-fe5b8b80-b869-11e9-91b8-5a796bc7f5a2.png)

It does not behave exactly like my problem, but sufficient enough to show there are some problems when the component is rendered inside Excel, such as: missing horizontal scroll bar, Sticky component is covering the vertical scroll bar.
The only different is my ScrollablePane is inside of a Modal, with

```
        styles={{
          root: {
            boxSizing: 'border-box',
            padding: '12px'
          },
          main: {
            width: '100%',
            height: '100%'
          },
        }}
```

## Context
The component can still scroll with scrolling wheel (or swipe on touch screen), but looks broken, and hard to use.

## Your Environment
* Platform: PC desktop
* Host: Excel
* Office version number: 1907
* Operating System: Windows 10 (1903)

This problem only presents inside of Excel with Edge, the component works perfectly fine even inside Excel with IE and all browsers (including Edge) outside of Excel shown in following screen-shot:
![2019-08-06 11_36_33-Win10_Office2016 on WRK-IT-156 - Virtual Machine Connection](https://user-images.githubusercontent.com/10732375/62584581-14694c00-b86a-11e9-8965-880c2ed27f6a.png)

I reported this to Fabric team earlier and they said they cannot help with Office add-ins.

**Comment by lumine2008** [comment]
Thanks @mm90849491 for your post. 
i have tried to load the https://developer.microsoft.com/en-us/fabric#/controls/web/scrollablepane to my taskpane, but looks the scrollbar is here. could you please share more information for me to repro in my side. thanks. 
![image](https://user-images.githubusercontent.com/26398035/62671824-dd5e7c00-b9ca-11e9-9093-bdc109f93c82.png)

**Comment by mm90849491** [comment]
Hi @lumine2008 , thank you for your attention to this ticket.
This is a screen-shot of the area rendered properly on Edge (or any other browser including IE inside Excel): 
![Snap1](https://user-images.githubusercontent.com/10732375/62675728-06e0be80-b95d-11e9-8c91-0b913d1e2bec.png)
The horizontal scroll bar is present and vertical bar is not covered by the Sticky header nor footer area.
I think my issue is just a minor variation of this inconsistent behaviour. If a reproduction of my specific situation is still needed, I will try to make a CodePen tomorrow.

**Comment by mm90849491** [comment]
The following Pen contains codes to reproduce both horizontal and vertical bars are missing on a task-pane:
https://codepen.io/mm90849492/pen/aeGZVp

**Comment by lumine2008** [comment]
@lliu113 , is seems related to UX areas, would you please take care of it, thanks.

**Comment by lliu113** [comment]
@mm90849491 - thanks for providing the Pen! Unfortunately I'm having some issues running it (it doesn't show anything when I run). 

Just to clarify, are the scrollbars inside the add-in page or part of the taskpane? If you're able to upload a video showing the scrollbars (or where the scrollbars are missing), that will be very helpful. Thanks!

**Comment by mm90849491** [comment]
@lliu113 , thank you for your attention to this ticket.

The scrollbars are not the taskpane component, they belong to several <div />s generated by React-Fabric.

**Comment by lliu113** [comment]
@mm90849491 - is your add-in using WebView2? To check, you can go to the personality menu and select security info. The runtime should be listed as Microsoft Edge. 

If not, can you try and see if upgrading to WebView2 fixes the issue? Here are two links for more info: 
[- Understanding the Office Add-in Runtime](https://developer.microsoft.com/en-us/microsoft-365/blogs/understanding-office-add-ins-runtime/#:~:text=Office%20Add-ins%20require%20a,webview%20control%20on%20desktop%20clients.)
[- Browser used by office add-in](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)

**Comment by mm90849491** [comment]
@lliu113 
The problem used to persist on WebView2 only, as the old Excel using IE 11 was fine.
It seems had been fixed. We used to add `msOverflowStyle: 'scrollbar',` on root `<div />`, I just removed this line and scrollbars work fine in Task-pane.

**Comment by lliu113** [comment]
@mm90849491 - really glad you were able to fix this! Closing this issue, feel free to reactivate if you have any additional comments. Thanks!
