### ISSUE TITLE
Missing AddIn In Android Outlook

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#658]
Some registered addin(s) in the MS O365 Admin Center are not shown on android devices. The missing android addin however is present when viewing email via IOS outlook and Chrome browser (OWA) outlook.

## Expected Behavior

All platforms of outlook should show the same set of registered addins.

## Current Behavior

Current behavior is that 1 fixed addin deployed to everyone in the domain is missing. And this happens not only on the addin shown in the images but in other addins as well. The missing addin in this case is the Message Header Analyzer. Some of our company clients report that in their case, our addin the Phish Alert V2 is missing.

## Steps to Reproduce, or Live Example

* Link to live example: ______
1. Register an addin or several addins via the Microsoft O365 Admin Center.
2. Some addins should be registered as fixed, and some as available.
3. Wait for 12 hours or so.
4. Open an outlook account under the domain and check if all the addins are showing in (1) Android (2) IOS (3) web browsers (4) Windows outlook

* Additional details:
  1. ______
  2. ______
  3. ______

## Context

As I've said, some of our clients have reported that our Phish Alert Button V2 are not showing in their android devices. After testing once, I was able to reproduce the issue NOT on our addin but in the "Message Header Analyzer" addin. I am leaning towards the idea that this issue is not on the addins but on the Admin Center. It seems that those configured via the Exchange admin center (the old ui) gets registered correctly in android devices as well. The addins added in the new Microsoft O365 Admin Center sometimes do not make it through the admin center.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______
IOS outlook, Android Outlook and Chrome OWA.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

IOS Outlook Addin Icons :
![IPhoneOutlookWithAddin](https://user-images.githubusercontent.com/3444844/62591565-93aa5e80-b902-11e9-875c-b696efd7398e.PNG)

Chrome Outlook Addin Icons : 
![ChromeBrowserWithMessageHeaderAnalyzer](https://user-images.githubusercontent.com/3444844/62591582-a6249800-b902-11e9-86e6-04667ce6e727.PNG)

Android Outlook AddIn Icons : 
![AndroidOutlookMissingAddin](https://user-images.githubusercontent.com/3444844/62591592-b2a8f080-b902-11e9-9b78-23a602fca461.JPG)

Exchange Admin Center Registered addins : 
![OldEACAccessForAddinConfiguration](https://user-images.githubusercontent.com/3444844/62591629-ceac9200-b902-11e9-91a5-dca967284074.PNG)

New MS O365 Admin Center Registered addins : 
![NewMSO365CenterForAddInConfiguration](https://user-images.githubusercontent.com/3444844/62591649-db30ea80-b902-11e9-81eb-3e61653ce047.PNG)

**Comment by glr0221** [comment]
@kbrandl it's been a while, i hope you are doing really well. The issue i submitted above is probably not for the office-js team. But I wrote it here anyway because I find you and your team highly responsive and reliable. If this issue needs to be moved somewhere else, please feel free to do so. Thank you very much for your support and understanding.

**Comment by glr0221** [comment]
@kbrandl it's been a while, i hope you are doing really well. The issue i submitted above is probably not for the office-js team. But I wrote it here anyway because I find you and your team highly responsive and reliable. If this issue needs to be moved somewhere else, please feel free to do so. Thank you very much for your support and understanding.

**Comment by glr0221** [comment]
@kbrandl Sorry I accidentally clicked the "Close and comment" button. Thank you again.

**Comment by glr0221** [comment]
@wamaina @exextoc any update on this item for today? Thank you very much.

**Comment by kbrandl** [comment]
@exextoc FYI, see related issue here:  https://github.com/OfficeDev/outlook-dev-docs/issues/673. Are you able to provide any update for the customer about this problem?

**Comment by kbrandl** [comment]
@glr0221 FYI, per an update posted on related issue #676 just now -- "This is a known issue and the team has been actively working on a fix. The internal incident tracking this issue is 139217145." Just wanted to make sure you were aware of this status.

**Comment by glr0221** [comment]
Thank you always @kbrandl for the assist. Thank you @JuaneloJuanelo for updating the #676 ticket. I will update my clients about this too.

**Comment by glr0221** [comment]
@kbrandl @wamaina any update on this issue? This is still not fixed as of today even if #676 is already resolved. It seems that the addins i registered using the new Exchange Admin Center portal does not reflect in my android phone's outlook. Thank you.

**Comment by exextoc** [comment]
@glr0221 can you please provide any test account with which issue is reproducible ?

**Comment by glr0221** [comment]
Hello @exextoc,

Thank you for your quick response. Unfortunately, I cannot share my admin account with you as of this time. To reproduce this bug, you need an outlook/office365 suite domain admin. The bug here is the "divergence" in the new Microsoft365 Admin Center and old Exchange Admin Center, and how these addins are shown/activated in the Outlook client for IOS and Android. Please see images below :

1. Exchange Admin Center for our account : 
<img width="1680" alt="OldEACUI" src="https://user-images.githubusercontent.com/3444844/68216286-85b5b980-ff95-11e9-9889-2a1d25b6591c.png">

2. Microsoft365 Admin Center for the same account: 
<img width="1680" alt="NewEACUI" src="https://user-images.githubusercontent.com/3444844/68216333-96fec600-ff95-11e9-8285-0edc02b6811e.png">

3. IPhone / IOS Outlook client showing addins installed : 
![IPhoneOutlook](https://user-images.githubusercontent.com/3444844/68216383-aaaa2c80-ff95-11e9-9dd9-fbade71091aa.PNG)


4.Android Outlook client showing addins installed: 
![AndroidOutlook](https://user-images.githubusercontent.com/3444844/68216422-b85fb200-ff95-11e9-8966-1d76e4d84ec7.png)

@exextoc with the images above we can see that MHA (Header analyzer) is not shown/enabled in the Android outlook client. But is clearly seen in the IOS version of outlook. Moreover my IPhone shows three instances of PhishAlert and android shows only two instances. 

Are the images enough to guide you in resolving the issue?  Thank you very much.

**Comment by exextoc** [comment]
@glr0221, we need any test account with which add-in is not coming on android not the admin account. If possible provide manifest of add-in.

**Comment by glr0221** [comment]
@exextoc the problem does not happen on any one specific addin. I don't know how to explain this but here are the steps to generate the issue :

1. Open your MicrosoftO365 Admin Center
2. From there, install any number of addins for all domain users
   - In my case I added, MessageHeader Analyzer (set this up as fixed/everyone)
   - PhishAlert Button by KnowBe4
3. Allow installed addin to propagate to all users.
4. Open outlook for IOS and you can see messageheader analyzer.
5. Open outlook for android, messageheaderanalyzer addin is missing.

I hope the above steps make sense. I apologize for the lengthy back and forth.
Thanks for understanding!!

**Comment by sagarpilkhwal** [comment]
I'm facing same issue for Exchange2019 on Android Outlook client.

**Comment by glr0221** [comment]
Hello Microsoft team,

Any news on this item? Or should this be addressed by the Exchange Server / Office 365 team? 

Thanks.

**Comment by exextoc** [comment]
Thanks for your patience and sorry for the slow response. We are able to reproduce this issue on Android for the Message Header Analyzer add-in. We are working on a fix. Unfortunately, we don't have any timelines to share at this point.

If there are any other add-ins from Store that are not showing up on Android, please let us know so it's easier for us to fix and test.

**Comment by wondarkid** [comment]
An outlook account can be regarded as a Microsoft account and it gives you access to so many things. Apart from the email service provider, there are also several other things you stand to gain from a Microsoft account. For instance, you can use only one Microsoft account for everything Microsoft. What do I mean by this? What I mean is that with just signing u for a Microsoft account once, you can do everything Microsoft that is free all the way from your mail inbox to Microsoft apps......................................................................................................................................................................................................................................Read More Here < a href="https://www.techshure.com/outlook-account/"><b>Outlook Account</b></a>
https://www.techshure.com/outlook-account/

**Comment by exextoc** [comment]
A fix for this issue was made in the Android Outlook client and should now be resolved. Thanks.

**Comment by glr0221** [comment]
Thank you as always @exextoc @kbrandl.
