### ISSUE TITLE
[Excel] open Taskpane is still Loading

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#663]
## Expected Behavior

open pane quick if i  click ribbon button to show Taskpane

## Current Behavior

![image](https://user-images.githubusercontent.com/3963826/62748406-13633500-ba8b-11e9-993b-d120383b6c83.png)

show Taskpane is still loading  and nothing show,  our United States User can not open it sometimes.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______PC desktop
* Host [Excel, Word, PowerPoint, etc.]: ______Excel
* Office version number: ______1907
* Operating System: ______windows
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by wamaina** [comment]
Hi @dinglicoding,

Thank you for reaching out! Could you provide a bit more detail on this issue? 

- Is this an add-in taskpane?
- If so, does the taskpane not load for all add-ins?
-Does this only happen in the Excel Desktop application or does it also happen in Excel Online?

**Comment by dinglicoding** [comment]
@wamaina  
Is this an add-in taskpane?
Yes
If so, does the taskpane not load for all add-ins?
this is happened at our customer computer. so i can not know.

-Does this only happen in the Excel Desktop application or does it also happen in Excel Online?
we try it only in the excel desktop application

in our computer sometime like this, we have add Office.onReady()
![image](https://user-images.githubusercontent.com/3963826/62918451-3c106500-bdd2-11e9-86ef-76dbdcaf5063.png)

**Comment by lliu113** [comment]
@dinglicoding are you able to provide the office version your customer is on? For extra diagnostic logs, you can ask them to "Send a Frown". You can do this by going to File > Feedback > I Don't Like Something. 

Make sure they tick "Attach my logs to help troubleshoot", and include the keywords "office add-in" somewhere in the description. 

![SendDiagnosticLogs](https://user-images.githubusercontent.com/6591834/62983046-eabca180-bde2-11e9-8cd3-02d6530991b1.JPG)

**Comment by dinglicoding** [comment]
@lliu113  thanks ,
my customer office version is 1907.

today i open my taskpane. it's display nothing too . my office version is 1907.
![image](https://user-images.githubusercontent.com/3963826/62989587-36bb2500-be7b-11e9-83da-ede65ca38e99.png)
and F12 log display
![image](https://user-images.githubusercontent.com/3963826/62989534-ff4c7880-be7a-11e9-9618-112bdd46bb54.png)

**Comment by lliu113** [comment]
@dinglicoding are you opening the taskpane from an app command button? Is this the same behaviour for other add-ins, or does this only happen for your own add-in?

**Comment by dinglicoding** [comment]
@lliu113 
are you opening the taskpane from an app command button? 
yes
my excel also add Script Lab ,but it often can't open in china.
next time i try other add-ins.

does this only happen for your own add-in?
no, other people has same problem. but it not often happen.

one day my customer can not open.but my computer can open. the only different is location and network.

**Comment by lliu113** [comment]
@dinglicoding - sorry for the very late response to this, are you still seeing this issue?

**Comment by lliu113** [comment]
@dinglicoding - I'm going to go ahead and close this issue for now. Please reactivate if you're still hitting this and we can investigate. If you're able to provide a video, or manifest that will help us debug. Thanks!
