### ISSUE TITLE
Resuming work on funcioning Excel add-in now throws AccessDenied error

### ISSUE THREAD

**Issue by marianatuma** [OfficeDev/office-js#664]
Hi all. I have asked a [question ](https://stackoverflow.com/questions/57362064/worksheets-loaditems-fails-leading-to-an-access-denied-error)about this on SO, but haven't had any luck so I thought I'd bring it over here. 

I'm working on an Excel add-in that makes some changes to files. This project had to be put on hold for a while, but it was working at that point. I resumed work on it this week, and I'm now getting the following error:

`AccessDenied: You don't have sufficient permissions for this action.`

The console doesn't really provide more information. Reading information from the worksheet seems to be ok, as I can get sheet names, cell content, etc. I believe the problem is when trying to write.

## Expected Behavior
The add-in should be able to run as it was before, without errors.

## Current Behavior
When trying to write to the file, the add-in throws an AccessDenied error.

## Steps to Reproduce, or Live Example
The project was created using the yeoman generator. With this in mind, here is `App.tsx`:

```
/* global Office, Excel */

import * as React from 'react';
import { Body } from './Body';

import * as OfficeHelpers from '@microsoft/office-js-helpers';

export default class App extends React.Component<AppProps, AppState> {
  debug = async () => {
      try {
        await Excel.run( async context => {
          const sheets = context.workbook.worksheets
          sheets.load('items'); await context.sync()
          let range = sheets.items[0].getUsedRange()

          let A1 = range.getCell(0,0)
          A1.values = [["TESTING"]]
        })
        } catch (error) {
          //OfficeHelpers.UI.notify(error);
          OfficeHelpers.Utilities.log(error);
          await this.append_message("Something went wrong: "+ error)
          console.log("Debug info: " + JSON.stringify(error.debugInfo));
      }
    }

    render() {
        const {
            isOfficeInitialized,
        } = this.props;

        if (!isOfficeInitialized) {
            return (
              <div>
                If you're seeing this, something went wrong!
              </div>
            );
        }

        return (
            <div className='ms-welcome'>
                <Body buttonLabel='Format' click={ this.debug } />
            </div>
        );
    }
}
```

And `Body.tsx` is:

```
import * as React from 'react';
import { Button, ButtonType } from 'office-ui-fabric-react';

export interface ContentProps {
    buttonLabel: string;
    click: any;
    console: any[];
}

export class Body extends React.Component<ContentProps, any> {
    constructor(props, context) {
      super(props, context);
    }

    componentDidUpdate() {
      const console = document.getElementById("html_console")
      console.scrollTop = console.scrollHeight
    }

    render() {
        return (
            <div id='content-main'>
                <div className='padding text-center'>
                    <br/>
                    <div className="d-flex">
                      <button type="button" className='btn btn-outline-info mx-auto' onClick={this.props.click}>{this.props.buttonLabel}</button>
                    </div>
                    <div id="html_console" className="console m-1 mt-3 text-left border border-info ">
                      {this.props.console.map( (message, index) => {
                        return (<p className="mb-0 ml-1" key={index}>{message}</p>)
                      } )}
                    </div>
                </div>
            </div>
        );
    }
}
```

**NOTE:** I have been told a couple of times that I don't need to load a worksheet collection's `items`, but when I try to access it without loading, I invariably get this message: 

`PropertyNotLoaded: The property 'items' is not available. Before reading the property's value, call the load method on the containing object and call "context.sync()" on the associated request context.`

I posted a snippet of the actual code I'm using, as well as a part of `manifest.xml` and `package.json` to the SO question linked above, if that is relevant.

## Context
I'm trying to edit the worksheets by deleting rows, adding background colors, changing the text on cells, etc.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft Office 365 Business, Version 1907 (Build 11901.20176 Click-to-Run)
* Operating System: Microsoft Windows 10 Pro, 10.0.17134 Build 17134

I was using a local version of `office-js`, but changed to the CDN hoping it would fix the issue, but to no avail.

## Useful logs
![errorlog](https://user-images.githubusercontent.com/6773647/62785194-6f947c00-bac0-11e9-9aa9-4868381736cf.png)

**Comment by lumine2008** [comment]
Hello @marianatuma , i cannot repro the issue, by copied some your code and try it in my side. 
do you think you could upload your gist to the github. therefore we can have a repro in our side? thanks

**Comment by marianatuma** [comment]
I generated another project using `yo office`, moved all files in `src/components` from the broken project to the new one, and things work fine now... I don't know what the problem was. Previously I was using a local version of the library, maybe something about it became deprecated when the project was on hold, and now that I'm using a new version of the library, things work again?

Either way, the problem is solved. Thanks for the response though @lumine2008
