### ISSUE TITLE
addFileAttachmentAsync() produces attachment that I cannot view/open

### ISSUE THREAD

**Issue by harry-levick** [OfficeDev/office-js#665]
## Expected Behavior

addFileAttachmentAsync attaches document to composing email that can be opened.

## Current Behavior

The result of the method call is successful, I am able to get the attachment id of the result. However, i'm not able to open the attached document.
For example, when trying to open a docx document that I have attached to an email, I get the error `Word found unreadable content in _____`.
Similarly, in outlook in chrome, I get the error `Sorry, we ran into a problem while opening this document.`

I don't get any console errors when making the function call, but when attempting to open the file I get the console error:

`Access to XMLHttpRequest at https://browser.pipe.aria.microsoft.com/ping from origin https://euc-word-view.officeapps.live.com has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

`GET https://browser.pipe.aria.microsoft.com/ping net::ERR_FAILED`

## Steps to Reproduce, or Live Example

* Link to live example: ______

```
var url = "";

var docName = "Image-23-08-2017-13-10-19.jpg";

Office.context.mailbox.item.addFileAttachmentAsync(
    url,
    docName,
    function (asyncResult) {
        if (asyncResult.status == Office.AsyncResultStatus.Succeeded) {
            // Get the ID of the attached file.
            var attachmentID = asyncResult.value;
        }
    });
```

* Additional details:
The url passed to this method is valid

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.3216.1.2706983
* Operating System: Windows
* Browser (if using Office Online): Chrome

## Useful logs

- [ ] Screenshots
- [ ] Console errors
- [ ] Test file (if only happens on a particular file)

`Access to XMLHttpRequest at https://browser.pipe.aria.microsoft.com/ping from origin https://euc-word-view.officeapps.live.com has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

`GET https://browser.pipe.aria.microsoft.com/ping net::ERR_FAILED`

**Comment by exextoc** [comment]
Could you provide a version number to help us understand the environment to reproduce this? You can get the version number by calling the api `Office.context.mailbox.diagnostics.hostVersion`. When the callback for the API is invoked, what is the result that is returned?

**Comment by harry-levick** [comment]
I have updated the issue with the correct version number

**Comment by exextoc** [comment]
In the solution you provided, the first url (https://demo.myeqms.com/Administrator/LoadDocADM.Asp?ID=2179&Ext=True&CCID=1) uses client side script to redirect a browser to fetch the actual image.
The addFileAttachmentAsync API only fetches what's provided the direct url, that's why it only attaches the content from LoadDocADM.Asp.  Please try updating your url to the direct url instead. (In this example, that would be https://demo.myeqms.com/dbase_EQMSSSOBE/13574342/2179v.jpg)
