### ISSUE TITLE
Excel Add-in - setDataAsync not working after Windows and Office upgrade and now running with Edge

### ISSUE THREAD

**Issue by bferreira** [OfficeDev/office-js#667]
Our Excel Add-In stopped working after an office upgrade for monthly target users. They got an update together with the new version of Windows 10. The Excel Add-in in now running on Edge and not IE11.

## Expected Behavior
Data is transfer from the add-in to excel document. The table on the excel sheet should received the data.

## Current Behavior
The table is created, but we received the error code 12007
{name: “Display Dialog Error”, message: “The operation failed because this add-in already has an active dialog.“, code: 12007}
Note: There is no Dialog box

## Steps to Reproduce, or Live Example
  1.Create a table in the excel sheet
  2.Create data 
  3.Create data 
  4.Use setDataAsysnc to add data to the table

## Context
Add data to an existing table on excel sheet with setDataAsync:
binding.setDataAsync(
            tableData,
            { coercionType: Office.CoercionType.Table,
              startRow: 0,
              tableOptions: options },
            asyncResult => {
                if (asyncResult.status !== Office.AsyncResultStatus.Succeeded) {
                    curveDefinitionProcessor.reportError('Error in data transfer from plugin to Excel document',asyncResult.error.message);                                 
                } else {
                    if (callback) {
                        callback();
                    }
                }
            });

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1907
* Operating System: Window 10 (1903)
* Browser (if using Office Online): ______

## Useful logs
{name: “Display Dialog Error”, message: “The operation failed because this add-in already has an active dialog.“, code: 12007}
![image](https://user-images.githubusercontent.com/1233578/62872765-71f41180-bd1e-11e9-921a-835d3152ac13.png)

I also get an error when loading the add-in. 
![image](https://user-images.githubusercontent.com/1233578/62872749-6a346d00-bd1e-11e9-813e-d11cb46077dc.png)

**Comment by lliu113** [comment]
Hey @bferreira, thanks for reporting the issue! Are you able to provide a copy of your manifest for us to side-load, so we can try and repro? 

Looping in @jargil for Edge

**Comment by jargil** [comment]
@bferreira - you said Office version is 1907, are you on build 16.0.11901.20176?

Alternatively to your manifest to side-load, if you could you try to repro using Script Lab in Excel and send us the script that would also be very useful.

**Comment by bferreira** [comment]
Yes, it is that version
![image](https://user-images.githubusercontent.com/1233578/63000100-9eb83e00-be70-11e9-9568-83671e2afa6a.png)

And the manifest: 
[WAPIExcelPlugin.xml.zip](https://github.com/OfficeDev/office-js/files/3500154/WAPIExcelPlugin.xml.zip)
Is there a secure way to send you credentials to our service?

I will try to create a script using Script Lab.

**Comment by jargil** [comment]
@bferreira - could you try updating to 16.0.11901.20218 and post back if you see any difference?

**Comment by bferreira** [comment]
@jargil I have updated but it is still not working.
I create the https://gist.github.com/bferreira/1777edb4a7ab3127f458c7bd59047572 , but this works. I have no html or react component, of course.

It needs to be something not working well with the react app itself.
What could cause this error? I don't have any dialog window or am I creating any in the whole code.
Also when using the same version of office but without the windows upgrade, I don't have any errors, that tells me I am doing something that Edge does not like. 

Any points you could give me here? Thank you!

**Comment by jargil** [comment]
@bferreira - thanks for the follow up. Your gist sample works fine in Script Lab. Were you able to also make it work with your add-in?

If you're still having issues, I can help take a quick look, you said you needed to share credentials to your service, feel free to e-mail details here: dxipfb@microsoft.com
Personnel monitoring that e-mail address will forward me the information.

**Comment by bferreira** [comment]
No @jargil it does not work on the add-in. Probably something there that I cannot reproduce.
I have just sent you the credentials and the steps to test it.
Let me know if you need more information or if something is not clear.

Thank you!

**Comment by jargil** [comment]
@bferreira - I've received the info. Will update you here soon. Thanks!

**Comment by jargil** [comment]
@bferreira - thanks for sending your repro steps and information! After debugging with your add-in, we found a bug in our side that we'll be fixing. Will keep you posted with regards to which build to use for testing. It'll be made available first in Office Insider for you to test.

**Comment by bferreira** [comment]
Thank you @jargil ! That will be great

**Comment by jargil** [comment]
@bferreira - the fix will be available starting with Office build 16.0.12106, this build or a newer one should begin deploying to Office Insiders sometime next week. Please let me know once you're able to validate. I'll keep this issue open until then. Thanks!

**Comment by bferreira** [comment]
Great! Since I have Office 365. I have asked the admin to allow my account to get Office insider builds. Hopefully that will be sorted soon.

**Comment by jargil** [comment]
@bferreira - Office build 16.0.12112 is already deploying to Office Insiders and should contain this fix. Were you able to test that this works for you?

**Comment by bferreira** [comment]
Hi @jargil, yes, I can confirm. All works now. Thank you!

**Comment by jargil** [comment]
@bferreira - thanks for taking the time to test this new build!

**Comment by bferreira** [comment]
hi @jargil, do you know when we could expect this fix to out on different Office update channels or if you know the correct place to ask this? 
I would like to inform our customers when this would be fix. 
There are more reporting the problem now when getting Windows version 1903.

**Comment by jimbarrett33** [comment]
FYI. This is still broken on the Mac Client. Version 16.57 (22011101). Setting any table option other than headerRow causes `Office.context.document.setSelectedDataAsync()` to fail with error "One or more of the tableOptions parameters have values that aren't allowed. Double-check the values and try again."

This [comment ](https://github.com/OfficeDev/office-js/issues/78#issuecomment-505619312) suggests using the Excel API which isn't really a resolution because this truly is a bug and any existing code on Mac's will just break. If there is a chance this bug WILL be fixed I will open another issue.

I really need to know if you are giving up on the common API's in favor of Excel API's because I need to change a good amount of code if that is the direction of the office-js team.
