### ISSUE TITLE
[Excel] Worksheet onChanged insert column index 0 causes DataChangeType.rowInserted

### ISSUE THREAD

**Issue by shis91** [OfficeDev/office-js#669]
When a user insert first column (index = 0) the worksheet's onChanged event handler changeType is Excel.DataChangeType.rowInserted instead of Excel.DataChangeType.columnInserted. 

## Expected Behavior
Inserting first column event trigger should contain changeType === Excel.DataChangeType.columnInserted.

## Current Behavior
Inserting first column event trigger contains changeType === Excel.DataChangeType.rowInserted.

## Steps to Reproduce, or Live Example
In angular application add a simple onChanged function that just prints the handler.changeType to the console.

```
 private async addWorksheetOnChangedEvent(context: Excel.RequestContext): Promise<void> {
    try {
       const worksheets = context.workbook.worksheets;
       worksheets.onChanged.add(this.worksheetOnChanged);
       await context.sync();
       console.log('A handler has been registered for the onChanged event.');
    } catch (error) {
      OfficeHelpers.Utilities.log(error);
    }
  }
 private worksheetOnChanged = async (handler: Excel.WorksheetChangedEventArgs): Promise<void> => {
  console.log(handler.changeType.toString());
 }

```
## Context
User remove or add rows/columns application needs to recalculate the ranges of stored custom functions so reload function works just fine. At the moment when that happens the reload function load data to the old saved ranges.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1907 build 11901.20176
* Operating System: Windows 10 v 1903
* Browser (if using Office Online): N/A

**Comment by lliu113** [comment]
Thanks for reporting the issue @shis91! 

Looping in @lumine2008 to follow up

**Comment by lumine2008** [comment]
Thanks @shis91 , this is a known issue BUG 3559511, it has been fixed. thanks for your support
