### ISSUE TITLE
Character differs offline vs. online

### ISSUE THREAD

**Issue by TinoDidriksen** [OfficeDev/office-js#67]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Given the [same document](https://1drv.ms/w/s!AjHfvjn5PP1Qikb_qhEcEQv_jAWX), the text retrieved via `context.load(par, 'text')` differs subtly when comparing Word 2016 offline vs. online. So far I've noticed double spaces being different.

E.g., `"og\u0020\u00a0blomkål"` is returned as `"og\u0020\u0020blomkål"` in desktop Word - the NBSP is turned into a space, but is returned as `"og\u0020\u202fblomkål"` in Word Online - the NBSP is turned into U+202F (Narrow No-Break Space).

I can normalize this easily enough, but I would really prefer such differences did not exist. If spaces are mangled, what else might be? Are such differences documented anywhere?

**Comment by JuaneloJuanelo** [comment]
Thanks for sharing this.  Its our goal that all platforms return the same string, but probably there are localization issues.  This is potentially a bug, let us investigate. I am assuming you are getting the entire paragraph?

**Comment by TinoDidriksen** [comment]
Yes, I load the whole paragraph.

Some more information, because I couldn't immediately reproduce just by adding another space:

The actual text does contain U+00A0 (No-Break Space ; NBSP), meaning it is `"og\u0020\u00a0blomkål"` - I've confirmed this by hexdumping the raw XML document. Word Desktop gives me 2 normal spaces, Word Online gives me U+202F. So both are wrong, though normalizing to actual space is ok for me.

The text I get from the API is at least consistent with what I get by manually selecting the words and Ctrl-C Ctrl-V it. Neither gives me the actual NBSP - copy-paste also give spaces and Narrow NBSP.

**Comment by JuaneloJuanelo** [comment]
Yes that's what I noticed, the document actually contains UTF(32) + UTF(160) in Win32, who is translated to UTF(32) + UTF(8239) in Online. 
I wonder if this is a common practice in Danish? or how the UTF(160) ended up in the document. Sounds like an edge case, at least in English and other latin languages. (that we still need to fix, but presumably with lower priority)

**Comment by JuaneloJuanelo** [comment]
btw i created a small script lab snippet to get the UTFs of the selection, so you can see the unicodes without needing to hexdump the OOXML :) https://gist.github.com/JuaneloJuanelo/89b452c45918c9e7a4ddd2df5588df73
just select some text and click the getUnicodeFromSelection button

**Comment by JuaneloJuanelo** [comment]
we are tracking this internally with TFS2162025

**Comment by TinoDidriksen** [comment]
It wound up in the document because I am testing our cross-platform grammar checker add-in, and I want it to handle multiple spaces. So I copy-pasted text from Google Docs with a double space in it, and apparently GDocs represents them with NBSP. But only sometimes, because it doesn't always end up as NBSP in Word.

So I agree this is very unlikely to happen in the real world. I am testing edge cases, and this seems to be an edge case of an edge case. I was just worried that if this difference exists, what else could happen.

**Comment by JuaneloJuanelo** [comment]
Agree. Probably we need to report that issue to Google as well :) 
This is the first time I learn about a disparity like this, I am confident that we should have extremely low probability of having additional cases, but it make sense to add a note in our documentation about this. Thanks for the suggestion. I will also tag a documentation bug as part if this issue.

**Comment by JuaneloJuanelo** [comment]
Update: @weshi  is tracking this issue.
