### ISSUE TITLE
Content add-ins’ focus behavior

### ISSUE THREAD

**Issue by dulange** [OfficeDev/office-js#670]
This bug report is connected to the StackOverflow thread [“Excel’s cursor/selection focus after inserting content add-ins”](https://stackoverflow.com/questions/57481847/excel-s-cursor-selection-focus-after-inserting-content-add-ins).

## Expected Behavior
In Excel on the desktop, right after inserting a content add-in, the container of the add-in gets the focus (the resize handles appear and Excel reveals the Drawing Tools menu) and the workbook/sheet is being de-focused. Thus, interactions with the workbook (like `getSelectedRange()`) are not directly possible.

## Recent Behavior
Until recently, you had to make a click into the add-in at least once to change the focus back to the web control and the workbook.

## Current Behavior
After a recent Office update (using 16.0.11328.20362 now), this click to re-focus the workbook and focus the web control isn’t working anymore. The focus remains on the container. Now, only a click onto the workbook releases the focus.

## Steps to Reproduce
To reproduce this behavior, you just need to create a simple content add-in that runs `getSelectedRange()` right away inside `Office.initialize`.

```html
<button id="getSelection">Get selected</button>
<pre id="output"></pre>
```

```js
// Just a function to print something into the content add-in
const output = document.getElementById('output');
function print(text) {
  output.innerHTML += text + "\n";
}

Office.initialize = (reason) => {
  $(document).ready(() => {
    // Attach our getSelection function to the button
    document.getElementById('getSelection').onclick = () => { getSelection(); }
    // …and execute it right away too:
    getSelection();
  });
};

function getSelection() {
  try {
    Excel.run(async ctx => {
      const range = ctx.workbook.getSelectedRange();
      range.load('address');
      await ctx.sync();
      print(range.address);
    });
  } catch (err) {
    OfficeHelpers.UI.notify(err);
    OfficeHelpers.Utilities.log(err);
  };
}
```

## Context
The actual goal is being able to work with the data that has been selected on the sheet **prior** to inserting the add-in to mimic the behavior of native Excel charts. So we are talking about a shortcoming here that affects a workaround of an already existing more fundamental shortcoming (not being able to use `getSelectedRange()` right after add-in insertion because the focus is being set to the add-in’s container).

## Your Environment
* Platform: PC desktop
* Host: Excel
* Office version number: 16.0.11328.20362
* Operating System: Windows 10.0.17134

## Screenshots
![add-in-focus](https://user-images.githubusercontent.com/24853115/63017058-89093f80-be95-11e9-800e-0316c6b23ca4.png)

**Comment by lliu113** [comment]
@dulange thanks for reporting this! 

I tried this out with the People Graph add-in with the following repro steps: 
1) Highlighted table
2) Insert > People Graph
3) Data > Select Data 
4) Clicked "Create"

Although there is no UI cue that the focus has moved to the workbook (which is most likely a bug), it seems to have picked up the pre-selected range and was successfully able to create a table with it. Is that what you're seeing too, or is the issue that getSelectedRange() is also not working?
