### ISSUE TITLE
#CALC! error appears when referencing Dynamic Array Custom Function in volatile function and using batching

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js#671]
## Expected Behavior
Formulas are calculated in proper order and no error is shown.

## Current Behavior

When using P&P batching sample with Custom Functions that return Matrix result (dynamic array) and while referencing part of that result it will end up with #CALC! error.

## Steps to Reproduce
Here is gist: https://gist.github.com/4tti/0dba18309a03a32e28b967fc289fe488
Set up report like this: 
![image](https://user-images.githubusercontent.com/19533927/63021598-39c90c00-bea1-11e9-9ae8-14b30592671f.png)

When you recalculate it will work.
Go to C2, press F2 to edit formula and accept with ENTER key. In E3 will appear error #CALC!

## Context
I believe the issue is in the combination of batching (emulated network requests) and volatile function referencing dynamic array. The steps above are not the only cases when I see #CALC! It can be randomly encountered even when using CTRL+ALT+SHIFT+F9 in certain cases (in complex report which uses referenced data validation, etc.) but I was not able to replicate it regularly.
Note that in the logs we saw that the correct values were retrieved (in case of our addin and complex report).

## Your Environment
Windows 10. Office Version 1909 (build 12001.20000)

**Comment by keyur32** [comment]
Internal bug: #3555586

**Comment by RuoyingLiang** [comment]
@4tti Thanks for reporting this issue. We fixed this  in version 1908 (Build 11929.20254). Please let me know if this issue still there in build newer than that version.

**Comment by 4tti** [comment]
@RuoyingLiang : yep, I can confirm it seems to work. Good job!
