### ISSUE TITLE
Volatile Custom Functions are being recalculated unnecessarily when formatting/structuring sheet

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js#672]
## Expected Behavior
Volatile custom functions should be recalculated only when required.

## Current Behavior
Volatile custom functions are sometimes calculated in cases when it is not required, e.g. when changing column width, hiding empty row, etc.
In huge reports it might be real issue.

## Steps to Reproduce, or Live Example
Use this GIST: https://gist.github.com/4tti/0dba18309a03a32e28b967fc289fe488
 Add to A1:A20 roll6sided formulas , in B1:B20 add rollnsided referencing A1, A2, ... and then play with row height and column widths. Try also double-clicking on the column to resize it.

**Important note - automatic calculation must be enabled.**

## Your Environment
Windows 10. Office Version 1909 (build 12001.20000)

**Comment by RuoyingLiang** [comment]
WHen the column width changed, the column may hide. Some formula may changed according to visibility. So those actions will trigger the calculation.

**Comment by 4tti** [comment]
@RuoyingLiang and could you explain why e.g. NOW() native and volatile function does not have this issue?
I don't consider this as sufficient answer. Imagine situation when you have thousands or hundreds of thousands of volatile formulas and you will just resize column...

@keyur32  FYI

Edit: and I am not mentioning web requests :)

**Comment by 4tti** [comment]
@RuoyingLiang, @keyur32 : please reconsider this. It happens even when applying cell format, etc.

**Comment by RuoyingLiang** [comment]
@4tti The trigger point should same as build-in fomular. If not, it should be an issue. As NOW() may doesn't change value when you do the action( it the same minute so you cannot see the value refreshed), suggest to use RAND() to compare. We tried in our machine and didn't see inconsistency. Please let me know if still see difference. A video will be a great help for us to do further investigation.

**Comment by 4tti** [comment]
@RuoyingLiang: you are correct, my mistake. I either had manual calc in one case or I accidentally used Format Painter tool (which triggers recalculation for some reason). Yes, I tried even RAND() previously... 
Sorry for confusion!
