### ISSUE TITLE
Excel header/footer not showing immediately

### ISSUE THREAD

**Issue by RoelVB** [OfficeDev/office-js#674]
## Expected Behavior
The inserted/changed Excel header/footer should show up immediately after changing it.

## Current Behavior
After changing a header/footer it doesn't show the change. On mouse over (the header/footer) the change becomes visible. Scrolling also seems to help.
Looks like something has to trigger a (re)render of the header/footer.

## Steps to Reproduce, or Live Example
A small example code:
```typescript
Excel.run(async (context)=>{
  const sheets = context.workbook.worksheets;
  sheets.load({$all: true}); // Load all sheets

  const headerFooter = sheets.getActiveWorksheet().pageLayout.headersFooters.defaultForAllPages;
  headerFooter.load({$all: true}); // Load header/footer

  await context.sync();

  headerFooter.set({leftHeader: 'something'});
});
```

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Windows PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1907 (build 11901.20176)
* Operating System: Windows 10 (1803)

**Comment by lliu113** [comment]
@RoelVB - thanks for reporting this! Looping in @lumine2008 to help

**Comment by lumine2008** [comment]
Thanks @RoelVB for your post.  when i use your code, i can set the page setting. 
![image](https://user-images.githubusercontent.com/26398035/63695997-650e0c80-c84c-11e9-9fb5-d4d50593d161.png)

so I am not quite sure if i understand your scenario correctly, it would be helpful if you could share a screen shot for your current behavior. Thanks.

**Comment by RoelVB** [comment]
@lumine2008 I've made a short video:
![Header_text](https://user-images.githubusercontent.com/10999128/63848467-271a0100-c990-11e9-80a5-a39b61058c6e.gif)

As you can see something else triggers the change.
I'm using the developer tools for this demo, but I'm seeing the exact same thing when doing this from an add-on.

**Comment by MandytMSFT** [comment]
@RoelVB  thanks for reporting this issue. I can repro under page layout view, but the main purpose for this API is for print preview/page layout dialog/printing. Is this blocking your critical scenario ? or is it possible to use other action to trigger render as workaround ?

**Comment by MandytMSFT** [comment]
@RoelVB  politely ping

**Comment by RoelVB** [comment]
@MandytMSFT any ideas on how I could programmatically trigger a render?

**Comment by xuxife** [comment]
@RoelVB , do you still block on this problem?

**Comment by RoelVB** [comment]
@xuxife Customer learned to live with it
Not 100% certain the issue still exists.

**Comment by lumine2008** [comment]
I am going to close this issue, please reopen this issue if you still have further comments, thanks.
