### ISSUE TITLE
for getTypeAsync api

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#675]
why we can get html or text, not both of them or which i want to get. and can i change it? if can, maybe you can provide an api, maybe just like setTypeAsync.
thanks a lot.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 0498adf2-3f86-3520-82c2-df88e6ea4b95
* Version Independent ID: 347c34b6-0586-9ce5-2c84-ae010c27b276
* Content: [Office.Body interface - Office Add-ins](https://docs.microsoft.com/zh-cn/javascript/api/outlook/office.Body?view=outlook-js-preview#feedback)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.body.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.body.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
@hello-chenchen, getTypeAsync is intended to reflect what the user has chosen for the message body. The user can change this on a per message basis.  (Outlook may also decide on html or plain text based on the message the user is replying to.)  There is no 'setTypeAsync' API currently. As @ElizabethSamuel-MSFT noted, you can add or upvote on UserVoice.

As for body.setAsync, as documented, "InvalidFormatError: The options.coercionType parameter is set to Office.CoercionType.Html and the message body is in plain text.".  The intention here is that the addin would insert a body that matches the current message format (html or plain text).  Your addin can provide a plain text body to setAsync if getTypeAsync return 'text'.

Do you have a scenario where you want to force the body to be 'HTML' when the user / Outlook decides that the message format should be plaintext?

**Comment by hello-chenchen** [comment]
@exextoc , thank you for your comments.

And i will add 'setTypeAsync' on UserVoice. But i think maybe, it is a little big feature for mac outlook client. And i notice in windows 10 outlook client, there is a menu bar called "Format Text", and user can select paste 'As Html' , 'As plain Text' or 'As Rich Text'. I think maybe, it is only windows outlook client feature without mac.

And the reason why i want to force the body to be 'Html' is because our PM think, html will have a better user experience for our customer. For example, Our customers can clearly see some hyperlinks, phone numbers, etc. what we want to show them. And can use their mouse to easily access our services without the need to copy plain text hyperlinks or phone numbers.

thanks.

**Comment by hello-chenchen** [comment]
[if can add a new api for outlook add-ins Office.Body interface to change body type, maybe called setTypeAsync](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/38387839-if-can-add-a-new-api-for-outlook-add-ins-office-bo)

UserVoice track.

**Comment by hello-chenchen** [comment]
@exextoc , yes, i tested the 'getTypeAsync' api in windows 10 outlook client, By switch to 'Format Text' menu bar, and select paste 'As Html' , 'As plain Text' and 'As Rich Text'. And called 'getTypeSync' separately, the result are 'html', 'text', 'html'.

**Comment by exextoc** [comment]
Thanks for adding the UserVoice request and including the scenario and observations there.  Since this is a new API / feature request, we would be tracking in UserVoice, and I am closing this.
