### ISSUE TITLE
Add-ins not showing up on Outlook android app

### ISSUE THREAD

**Issue by sagarpilkhwal** [OfficeDev/office-js#676]
Is there any recent change in the manifest syntax for _MobileFormFactor_ ? None of the Outlook add-ins are showing up on Android Outlook application.

**Comment by JuaneloJuanelo** [comment]
THanks. This is a known issue and the team has been actively working on a fix.

**Comment by JuaneloJuanelo** [comment]
btw the internal incident tracking this issue is 139217145

**Comment by glr0221** [comment]
Hello Microsoft, @kbrandl @JuaneloJuanelo  any updates on this? Thank you very much. :D

**Comment by ntranvinh** [comment]
Hi, any new updates please :) ?

**Comment by kbrandl** [comment]
@JuaneloJuanelo are you able to provide a status update on this issue? (I don't seem to have access to the internal work item that you've noted above - 139217145.)

**Comment by glr0221** [comment]
Any updates on this issue? thanks.

**Comment by glr0221** [comment]
Sorry for the trouble guys but is there any update on this? @kbrandl  @JuaneloJuanelo Any update would be very much appreciated. Thank you in advance!

**Comment by glr0221** [comment]
Hi microsoft team. Hope you are all doing well. Is this issue fixed already? thanks

**Comment by sagarpilkhwal** [comment]
@glr0221 This is working as expected for me, don't know when the update was pushed by it somehow started working without any application update on my device.

**Comment by glr0221** [comment]
Thanks @sagarpilkhwal I will check on my end again today too.

**Comment by vinay-thallam** [comment]
I am still facing this issue. 
@JuaneloJuanelo  Any update on this issue from microsoft ?
