### ISSUE TITLE
Office Api's not working

### ISSUE THREAD

**Issue by kakusharma** [OfficeDev/office-js#678]
I am creating a contextual Outlook Add-In with "ItemHasRegularExpressionMatch" rule. Below are the issues that I am facing:
1. Office.context.mailbox.item.(getRegExMatchesByName |  getRegExMatches) are retrning null in Outlook 2016 desktop client, though its working on web client.
2. Office.context.mailbox.item.body.getAsync as HTML is not returning the mail body.  Instead its just returning me this: "**ÿþ<**".
## Expected Behavior

1. Office.context.mailbox.item.(getRegExMatchesByName |  getRegExMatches): these should return the Regex matches instead of returning null
2. Office.context.mailbox.item.body.getAsync: this should return complete the email body
## Current Behavior

1. Office.context.mailbox.item.(getRegExMatchesByName |  getRegExMatches): Instead of returning me the array of regex matched texts, its retuning me null
2. Office.context.mailbox.item.body.getAsync: Instead of mail body its returning me this: "**ÿþ<**".
## Steps to Reproduce, or Live Example

* Link to live example: You can sideload the test add-in from "https://tmdev01.tm00.com/testapp/manifest.xml". The rule is applied for "ItemHasRegularExpressionMatch" rule as regexvalue = view online

* Additional details:

  1. Send an email with "view online" text in it
  2. Sideload the Add-In from above mentioned address
  3. Try opening the add-in on Outlook 2016. 
  4. It should bind the mail body to the add-in. But it doesn't. Also, if you debug it you will find that getRegExMatchesByName and getRegExMatches bith returns null.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2016 (16.0.4266.1001) 64 bit
* Operating System: Windows
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
'getSelectedRegExMatches' is part of requirement set 1.6 (https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.6/office.context.mailbox.item) and only available on click-to-run versions of Outlook.

For your other issues, could you please try getting updates for Outlook?

**Comment by exextoc** [comment]
Does the body.getAsync issue reproduce on multiple emails?

**Comment by kakusharma** [comment]
Everything worked since I updated the Outlook 2016. Thanks for the help.
