### ISSUE TITLE
PowerPointApi set does not pass the validation

### ISSUE THREAD

**Issue by Niko0pl** [OfficeDev/office-js#680]
The PowerPoint Api requirement set (`<Set Name="PowerPointApi" MinVersion="1.1"/>`) does not pass the validation of `office-addin-validator`. The response message is: 

> Error OfficeDev/office-js-docs-pr#1:
> No supported Office products detected: There are no platforms which fulfil the requirements specified in the manifest. The most common reasons for this failure are issues in the Requirements section. Please review the manifest and try again. (link: undefined)

However, when debugging using Visual Studio, this requirement set works and allows to sideload the add-in.
Is it a known issue? How can i make it pass the validation?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ecc3552a-8793-509a-0340-576dd095c39b
* Version Independent ID: 6daf7dbd-4a2a-66a9-a0ea-2adb4e1a9a4a
* Content: [PowerPoint JavaScript API requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/powerpoint-api-requirement-sets)
* Content Source: [docs/reference/requirement-sets/powerpoint-api-requirement-sets.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/requirement-sets/powerpoint-api-requirement-sets.md)
* Product: **powerpoint**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by Niko0pl** [comment]
@sumurthy , any news here? I can't submit my add-in cause validator on Seller dashboard throws the same message.

**Comment by sbludlow** [comment]
@sumurthy , we see the same error and can't submit our add-in.  Any progress to share?

**Comment by Niko0pl** [comment]
My add-in keeps being rejected by Office validation team. They don't give a damn that this bug still exists on 2013 and that it can't be excluded from the manifest.

**Comment by Niko0pl** [comment]
My add-in keeps being rejected by Office validation team. It would be great to get some update here.

**Comment by sumurthy** [comment]
I fixed part of the [issue](https://github.com/OfficeDev/Office-Js-Requirement-Sets/pull/47). I'm not sure why this is not working still. (Could you re-try again?) I will follow-up with the team that handles this.

**Comment by sumurthy** [comment]
Can you also confirm which OS? Windows or MacOs?
