### ISSUE TITLE
OnSend event appears to not fire on Outlook for Mac

### ISSUE THREAD

**Issue by vijaypemmaraju** [OfficeDev/office-js#682]
The [OnSend docs](https://docs.microsoft.com/en-us/outlook/add-ins/outlook-on-send-addins?tabs=windows) appear to suggest that the OnSend event is supported on Outlook for Mac on an Office 365 Subscription. I am developing an addin that adds some html and, I followed the steps in the above link to add the extension point for the `ItemSend` event. The functionality works well in Outlook 365 Web, but the event doesn't even appear to fire in Outlook for Mac. I have exactly the same code running in both environments.

## Expected Behavior
The `ItemSend` event is triggered and my function is invoked

## Current Behavior
Nothing appears to happen when sending an email.

## Steps to Reproduce, or Live Example
I haven't tried the example app yet, but mine is quite similar, so it should be reproducible with the following:

1. Set up https://github.com/OfficeDev/Outlook-Add-in-On-Send
1. Install it onto Outlook for Mac
1. Try sending an email.

## Context
We need the same functionality across web and desktop to build our add-in successfully.

## Your Environment
Platform: Mac
Host: Outlook
Subscription: Office 365
Outlook for Mac Version: 16.28
Operating System: 10.14.6

**Comment by AnjanaValsan** [comment]
Are you on insiders Fast channel? onSend for Outlook Mac is currently in preview (limited to Insiders fast channel)

https://insider.office.com/en-us/join/mac

**Comment by vijaypemmaraju** [comment]
That's good to know, thanks @AnjanaValsan! FYI, the docs say: `This feature is also available in preview on Windows and Mac connected to an Office 365 subscription`, so it's not clear that this feature is limited to the insiders fast build. I'll close the issue.

**Comment by vijaypemmaraju** [comment]
@AnjanaValsan just out of curiosity: do you know when the OnSend feature will be generally available?
