### ISSUE TITLE
Folders area does not refresh after the addin (using EWS) creates new folder(s)

### ISSUE THREAD

**Issue by syedaliahsan** [OfficeDev/office-js#683]
## Expected Behavior
Newly created folders are visible in the Folders area.

## Current Behavior
Folders area does not refresh so newly created folders are not visible until the OWA web-page is reloaded in the browser.

## Steps to Reproduce, or Live Example
1. Install the demo add-in from https://newdev.timesolv.com/Integrations/addin/SimpleVersion.xml
2. Open OWA.
3. Select an email message.
4. Open the add-in.
5. Fill in the input fields (all are required).
6. Click on the button
7. See that the folders (corresponding to the input fields) are not visible in the Folders area (left navigation bar)

Note that the same add-in works in Outlook Windows as expected.

## Context
I want to allow my customers file (i.e. associate) their emails corresponding to a business entity (which is in my application) right from within the Outlook. To do this, I want to create a folder (if not already exists) in the Outlook corresponding to the selected record of that entity. The folders are created in a hierarchy as follows:
Top-Level Folder
&nbsp;&nbsp;&nbsp;&nbsp;Folder of the Parent of the selected record
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Folder of the selected record
After making sure that the folder has been created (or was already there), I move the selected email to that folder.

## Your Environment

* Platform: PC desktop, Windows 7, Outlook Web App
* Host: Outlook Web App
* Browser: Google Chrome 64-bit (76.0.3809.100) and Mozilla Firefox 64-bit (68.0.1). Not tested in other browsers.

## Useful logs
As far as the add-in functionality is concerned, there are no javascript errors. Please check the browser console for the log when you click on the button.

**Comment by davidchesnut** [comment]
Hi @syedaliahsan, thanks for letting us know about this issue. We'll take a look and get back to you.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding Folders area not refreshing. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by syedaliahsan** [comment]
Hi,

Any updates on the ETA? We are unable to release our add-in to our customers because of this.

**Comment by exextoc** [comment]
This feature is in our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
@syedaliahsan This issue is fixed now. Please check with your add-in that you no longer face this issue.

**Comment by syedaliahsan** [comment]
I had already checked a few months back and it was fixed.

Thanks

Kind regards,

Ali Ahsan
