### ISSUE TITLE
Unexpected Behavior of Context.sync().then() after update of Excel build (16.0.11901.20218)

### ISSUE THREAD

**Issue by VamsiKrishnaNori** [OfficeDev/office-js#684]
**Problem:**
Excel web Add-in not executing functions in context.sync().then()

**Context:**
We have built an Excel web add-in using office.js which loads data into the Excel sheet. The ‘then’ statement which has to execute after context.sync() call is not executing after recent update of Excel build (16.0.11901.20218). It is working fine when we reverted to earlier build (16.0.11901.20176) of Excel.

**Environment:**
* Platform: PC desktop, Mac, iOS, Office Online
* Host : Excel
* Office version number: 16.0.11901.20218
* Operating System: Windows 10

**Expected Behaviour - When the following code runs, the SampleCall() function is called.**
```
Excel.run(context){
	// Loading data into excel
	return context.sync().then(function(){
	    //Next function to be called
	    SampleCall();
        });
}
```

**Current Behaviour - When the above code runs, the SampleCall() function is not getting called.**

**Steps to repro:**
The Dataresponse is coming from an Ajax call

Dataresponse is 
Column: Which Column in Excel
Row: Which row in Excel  
Values: 2D array in RowxColumn

```
Excel.run(function (context) {
    var sheetName = "Sheet1";
    var worksheet = context.workbook.worksheets.getItem(sheetName);
    for (var responseIterator = 0; responseIterator < Dataresponse.length; responseIterator++) {
        column = Dataresponse[responseIterator].StartColumn - 1
        row = Dataresponse[responseIterator].Row - 1
        for (var valueIterator = 0; valueIterator < OTBDataresponse[responseIterator].Value.length; valueIterator++) {
            rangeColumn = column + valueIterator
            range = worksheet.getCell(row, rangeColumn)
            range.values = OTBDataresponse[responseIterator].Value[valueIterator];
        }
    }

    return context.sync().then(function () {
        consol.log('Success');
    })
}
```

**Comment by catchingyu** [comment]
Can you share with us the Windows Excel Version for reproduce this issue ? It will be great you could also provide us a screen shot on the Version.
Meanwhile, Is it possible you can share with us a gist for the example reproducing the above issue?

I tried with the very basic function of context.sync().then on the Windows Excel Version 1909 (Build 12005.20004), it works well.

async function setup() {
  await Excel.run(async (context) => {
    return context.sync().then(function () {
      console.log('Success');
    })
  });
}

**Comment by VamsiKrishnaNori** [comment]
![image](https://user-images.githubusercontent.com/29355955/63509348-9360b480-c4f9-11e9-8f34-9baf43afead3.png)


Please find the Microsoft Excel Version as seen in the snapshot above, for whcih we are facing the issue. Could you please try the same function on this version?

FYI, This version was available few days ago. And the newer version 1909 is not available yet to update.

**Comment by VamsiKrishnaNori** [comment]
To add more details. We have seen the issue affect if you are having more than 20 cells updated.

**Comment by VamsiKrishnaNori** [comment]
The gist of the function which we are using is We paint data values in rows and columns from data response object(This is received from the database). 

We are using two loops one for rows and other for columns to populate the data. Office.JS worksheet.getCell is used to get excel object reference and populate data. 

The below code snippet is one example case where it is failing. Instead of data from database we tried to replicate functionality with random function for you to execute. The console.log statement in then clause is not getting executed. This is happening only in 1908 build.

                Excel.run(function (ctx) {

                    var sheetName = "Sheet1";
                    var worksheet = ctx.workbook.worksheets.getItem(sheetName);

                    var StartColumn = 7;
                    var StartingRow = 15;

                    for (var responseIterator = 0; responseIterator < 19; responseIterator++) {
                        column = StartColumn + responseIterator;
                        row = StartingRow + responseIterator;

                        for (var valueIterator = 0; valueIterator < 19; valueIterator++) {
                            rangeColumn = column + valueIterator
                            range = worksheet.getCell(row, rangeColumn)
                            range.formulas = '=RAND()';
                        }
                    }
                    
                    return ctx.sync().then(function () {
                        console.log('Success');
                    });
                })

**Comment by VamsiKrishnaNori** [comment]
Hello Team, any update on this?

**Comment by MandytMSFT** [comment]
@star1ord Does this issue still repro for you? We have bug fixed in each release, both @catchingyu and I can not repro the issue you reported in version later than yours. Could you try to update your excel version ?

**Comment by VamsiKrishnaNori** [comment]
@MandytMSFT and @catchingyu Thanks for resolving the issue. It is fixed in the latest version of Office updates

**Comment by MandytMSFT** [comment]
thanks @star1ord  for confirmation!
