### ISSUE TITLE
After updating to Microsoft.Office.js 1.1.0.15 getting an error loading scripts

### ISSUE THREAD

**Issue by dankurtzGR** [OfficeDev/office-js#686]
After updating our nugget package to Microsoft.Office.JS 1.1.0.15 -  Office.JS reports a console error and it no longer fully loads

## Current Behavior
Console error :  MicrosoftAjax.js is not loaded successfully.

This appears because in the most reference version of this file the method to load in additional scripts - the code now adds this attribute to the <scripts> element calls -    f.setAttribute("crossOrigin", "anonymous");

## Your Environment
* Sharepoint - provider hosted app that is loading office.js on an MVC page
 *  Office App that is being brought into word

**Comment by davidchesnut** [comment]
Thanks @dankurtzGR! looks like this is related to #687 we'll take a look and get back to you

**Comment by keyur32** [comment]
Previous issue was closed. Closing this one.
