### ISSUE TITLE
After upgrading the Microsoft.Office.Js Nuget package from version 1.1.0.12 to 1.1.0.15, there were multiple compiler errors

### ISSUE THREAD

**Issue by dankurtzGR** [OfficeDev/office-js#687]
After upgrading the Microsoft.Office.Js Nuget package from version 1.1.0.12 to 1.1.0.15, there were multiple compiler errors.  We resolved the compiler errors by removing a file that was installed by the package, office-with-first-party.d.ts 

## Expected Behavior
Adding the package to a site, should compile by default

## Current Behavior
There are .TS files that compile and create the same code and cause duplicate issues

## Steps to Reproduce, or Live Example
Add Microsoft.Office.JS nugget package to a site
Build

## Your Environment
Visual Studio 2019
MVC / Web API

**Comment by davidchesnut** [comment]
Hi @dankurtzGR thanks for bringing this to our attention! We'll take a look and get back to you.

**Comment by wandyezj** [comment]
Hello @dankurtzGR  

Thank you for your patience, 

I have deployed a new version of the package.

Could you please check that the latest version resolves the build errors?

**Comment by dankurtzGR** [comment]
I see in the new version the file we removed manually to workaround the issue is no longer present in the the latest.  I also see that MicrosoftAjax.js is removed.  
We will test and check the results.  I assume this issue would be resolved, but I am not sure about #686 since the error in the debug console was with the loading of other scripts due to the crossOrigin attribute

**Comment by wandyezj** [comment]
Thank you @dankurtzGR for the quick followup,

Please let us know if you continue to see these issues after the update.

**Comment by dankurtzGR** [comment]
I am no longer seeing the compile errors in the new version
