### ISSUE TITLE
Office.context.ui.messageParent does not work on Internet Explorer

### ISSUE THREAD

**Issue by Sheikz** [OfficeDev/office-js#692]
It works fine on Chrome, but it does not work on Internet Explorer.
The dialog opener does not receive any message upon invocation of the method in the dialog box.

It is also not working in Outlook Desktop application, which is based on IE

**Comment by Rick-Kirkham** [comment]
We use the office-js-docs-pr repo to track issues with the documentation. Since this is about the framework, not the documentation, I have transferred it to the office-js repo.

**Comment by exextoc** [comment]
We were not able to repro this issue in Desktop or IE. What is the build number for your Outlook desktop client? Do you see any errors in the console for IE? 

Also, you can try clearing your cache to get the most recent version of office.js from the CDN.

**Comment by AlonEkelund** [comment]
We have recently got this problem in all our Outlook Add-ins on the desktop. It works in all browsers. After authenticating the authentication window will not close. We did check try clearing the cache and we do have the most recent version of office.js from the CDN. 

This is the Outlook version
![picturemessage_svqjhrqw lcb](https://user-images.githubusercontent.com/31590641/64523101-d5f8fe00-d2fb-11e9-92a7-46b77199ddd5.png)

**Comment by exextoc** [comment]
@AlonEkelund : May we request to open a separate issue regarding what you are facing. This way we can respond to posts individually and have a faster turn around time.

**Comment by AlonEkelund** [comment]
We solved the issue.

**Comment by GopalZadafiya** [comment]
@AlonEkelund, Can you please guide how did you solve this issue ?

**Comment by AlonEkelund** [comment]
We solved the issue when a dialog pop up is not closing in IE, Edge using the following.

 Office.initialize = function (reason) {
            $(document).ready(function () {
                isAuthenticated = true;
                Office.context.ui.messageParent(true);                
                setTimeout(TryInoldway, 5000);
                
            });
        };
    }
    function TryInoldway() {
        if (window.opener != null) {
            try {
                window.opener.ReloadPage();
                window.close();
            }
            catch (ex) {
                console.log(ex);
            }
        }
        else {
            try {
                window.parent.ReloadPage();
                window.close();
            }
            catch (ex) {
                console.log(ex);
            }
        }
    }
