### ISSUE TITLE
Excel: Custom Functions installation error message contains a 404 link

### ISSUE THREAD

**Issue by dzwillia** [OfficeDev/office-js#694]
## Expected Behavior

Expected the link in the error message to point to a valid docs page.

## Current Behavior

The link in the error message (https://aka.ms/customfunctions-troubleshooting) points to a 404.

![excel-online-add-in-error](https://user-images.githubusercontent.com/1385356/63825111-6ceeaf00-c927-11e9-8f96-701ca5f0719e.png)

## Steps to Reproduce, or Live Example
Follow the steps in issue #693 to get the custom functions error message to show.

## Context

Trying to install my add-in in Excel Online for testing purposes, however with an invalid manifest.xml file (simply by having a version with only 3 (e.g. `1.0.01) numbers instead of r (e.g. `1.0.0.0`), this error message shows.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Office Online
* Operating System: Windows 10
* Browser (if using Office Online):
    > Google Chrome | 76.0.3809.100 (Official Build) (64-bit) (cohort: Stable)
    > Revision: ed9d447d30203dc5069e540f05079e493fc1c132-refs/branch-heads/3809@{#990}
    > OS: Windows 10 OS Version 1903 (Build 18362.295)

## Useful logs

- [ ] Console errors
- [X] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by keyur32** [comment]
Fixed! Sorry we had issues with the link.

**Comment by dzwillia** [comment]
Thanks! I saw you had updated the README to include the new link so figured it was just lost in the mix. :-)
