### ISSUE TITLE
Return type matrix for Excel custom functions

### ISSUE THREAD

**Issue by georgechr** [OfficeDev/office-js#695]
Return type matrix for custom functions still requires the user to select the area where the data will be returned and enter the formula using the Ctrl+Shift+Enter combvination. 

In a comment by one of MS people on stackoverflow it was mentioned that this might not be required in the Excel JS custom functions release: https://stackoverflow.com/questions/47396809/excel-js-custom-function-does-not-return-a-matrix#comment81836171_47419653

This is a pivotal feature for us, otherwise we will have less incentives to move to the new API.

## Expected Behavior
When the return type of a custom function is of type 'matrix' then we expect that Excel will fill up the cells with the appropriate values without the user having to 'guess' how many results there will be.

## Current Behavior
User has to use the Ctrl+Shift+Enter combo after selecting the area for returning the formula results

**Comment by RuoyingLiang** [comment]
Thanks for reaching out. Custom function support to return array as result in Excel desktop. for example: 
function testFunc(): number[][] {
  return [
    [Math.floor(Math.random() * 5) + 1, Math.floor(Math.random() * 5) + 1],
    [Math.floor(Math.random() * 6) + 1, Math.floor(Math.random() * 6) + 1]
  ];
}
Could you try on Excel in desktop? If it's not working, could you share your build version with us? For Excel online, it's not supported yet, will update once it's supported.

**Comment by georgechr** [comment]
Hello,

Sorry I was away and did not respond. Is this happening because I am not part of the Insider program and dynamic arrays are only available for those in the Insider program?

@RuoyingLiang  That's pretty much what I've tried and it doesn't work, i think because the dynamic arrays feature has not been released yet

**Comment by keyur32** [comment]
Hi @georgechr , likely that is the case. You can join the insiders program on insiders.office.com. If you need a development account, you can get one through our developer program: https://aka.ms/o365devprogram.

Closing this one for now.
