### ISSUE TITLE
[Outlook] Error while making EWS request to find mailing item

### ISSUE THREAD

**Issue by IhorHalanDevPro** [OfficeDev/office-js#698]
We use `Office.context.mailbox.makeEwsRequestAsync` to manage mailbox items from our Outlook add-in and it randomly throws error for our customers. Unfortunately, we were not able to reproduce the error, but we have it in our production logs (see below). The description of the error is blank, but it's code is `-2147417843`.

## Expected Behavior
EWS requests should be executed successfully.

## Current Behavior
EWS requests randomly throw error.

## Steps to Reproduce, or Live Example
- Call `Office.context.mailbox.makeEwsRequestAsync` with the body for one of the following operations: `FindItem`, `UpdateItem`.
- Get an error (not guaranteed).

Example request payload:
```
<?xml version="1.0" encoding="utf-8"?>
  <soap:Envelope
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
    xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
  >
    <soap:Header>
      <t:RequestServerVersion Version="Exchange2013" />
    </soap:Header>
    <soap:Body>
      <m:FindItem Traversal="Shallow">
        <m:ItemShape>
          <t:BaseShape>IdOnly</t:BaseShape>
        </m:ItemShape>
        <m:Restriction>
          <t:Contains ContainmentMode="Substring" ContainmentComparison="IgnoreCase">
            <t:FieldURI FieldURI="message:InternetMessageId"/>
            <t:Constant Value="Message ID"/>
          </t:Contains>
        </m:Restriction>
        <m:ParentFolderIds>
          <t:DistinguishedFolderId Id="inbox" />
          <t:DistinguishedFolderId Id="outbox" />
          <t:DistinguishedFolderId Id="sentitems" />
          <t:DistinguishedFolderId Id="msgfolderroot" />
        </m:ParentFolderIds>
      </m:FindItem>
    </soap:Body>
</soap:Envelope>
```

## Context
Error prevents us from updating and sending emails successfully through our add-in. 

## Your Environment
* Platform: PC desktop
* Host: Outlook
* Office version number: 16.0.11901.20176
* Operating System: Windows 10.0

## Useful logs
Error object parsed by Bugsnag breadcrumbs
```
description:
number: -2147417843
stack: Error
   at n.prototype.execute (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:15:88948)
   at u.DDA.OutlookAppOm.prototype.callOutlookDispatcher (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:15:175997)
   at u.DDA.OutlookAppOm.prototype.invokeHostMethod (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:15:175866)
   at r.RequestBase.prototype._sendRequest$i$0 (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:15:317180)
   at r.EwsRequest.prototype.send (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:15:308709)
   at u.DDA.OutlookAppOm.prototype.makeEwsRequestAsync (https://appsforoffice.microsoft.com/lib/1/hosted/outlook-win32-16.02.js:15:190810)
```

**Comment by sumurthy** [comment]
@exextoc could you please comment?

**Comment by exextoc** [comment]
Does it happen randomly on many persons, or only one person? Could you provide fiddler trace for more investigation?

**Comment by IhorHalanDevPro** [comment]
It happens randomly to different people. The cases are not frequent and affect <1% of users. I'll try to get some network logs, but it might take a day or two.

**Comment by dmitry-semenov** [comment]
We're getting similar stacktrace when fetching recipient:
```
Error
at n.prototype.execute
at u.DDA.OutlookAppOm.prototype.callOutlookDispatcher 
at u.DDA.OutlookAppOm.prototype.invokeHostMethod
at u.DDA.OutlookAppOm.prototype._standardInvokeHostMethod$i$0 
at r.ComposeRecipient.prototype.getAsync 
at Anonymous function
```
hostName: Outlook
hostVersion: 16.0.11929.20254

**Comment by exextoc** [comment]
@dmitry-semenov : May we request opening a separate issue for what you are facing. This way we can keep issues independent and have a faster turn around time with responding individually.

@IhorHalanDevPro : For the makeEWS call, we recently added a diagnostics object to the asyncResult object. In cases of failures that you are seeing, could you share what the diagnostics object contains, if it exists?

**Comment by IhorHalanDevPro** [comment]
@exextoc Sure, I'll share the diagnostics object if we get one.

As for the logs you requested, the user who contacted us initially about the issue is not willing to provide them. We'll try to figure out the other way to get the logs if the approach with diagnostics object fails.
