### ISSUE TITLE
[Word] getTextRanges strips tabs

### ISSUE THREAD

**Issue by tonyroberts** [OfficeDev/office-js#699]
When calling Range.getTextRanges with trimSpaces=false on text containing tabs, the tabs are not included in the returned text.

**NOTE** This only applies to the online version of Word, tested in Edge, IE and Chrome. In the desktop version this works as expected.

## Expected Behavior
The full text, including the tab characters, should be returned.

## Current Behavior
Any tabs included in the text are removed.

## Steps to Reproduce, or Live Example
Create a document with the following text, noting the tab character between `hello` and `,`, and between `,` and `there` (it may not show up in rendered markdown, but be sure to include it when putting this text in to word):

`hello	,	there `    <==   *hello{TAB},{TAB}there*

The run the following code with that text selected:

```js
function run() {
  return Word.run(function (context) {
    const range = context.document.getSelection();
    const paragraphs = range.paragraphs;
    paragraphs.load();
    return context.sync()
      .then(() => {
        let ranges = paragraphs.items[0].getTextRanges([','], false);
        ranges.load();
        return context.sync()
          .then(() => {
            ranges.items.forEach((range) => {
              console.log(range.text);
            });
          });

      });
  });
}
```

I would expect the two strings to be (where {TAB} is either '\t' or '\u0009'):

- *hello{TAB},*
- *{TAB}there*

Indeed, this is what you get if you run it on the desktop verision. However, on the web version you'll see the tabs are missing and you get:

- *hello,*
- *there*

**Note** If you use javascript to write "hello\t,\rthere" then those tabs are not the same as if you press tab when entering the text by hand.

## Context

This is a problem when working with code snippets in Word documents that use tabs for indentation.

## Your Environment

* Platform : Office Online
* Host : Word
* Office version number: 16.0.12029.33701
* Operating System: Tested on Windows 10 and Mac
* Browser (if using Office Online): Tested in Edge, Chrome and IE

## Useful logs
![image](https://user-images.githubusercontent.com/3200395/64189746-cfd2cf80-ce6c-11e9-99e2-afb521e965c2.png)

**Comment by sumurthy** [comment]
@weshi can you comment on this?

**Comment by weshi** [comment]
This is actually expected behavior for this API in Word on the Web. The tab is not supported in Word on the Web. If you try to enter tab in between any text, it does not insert any space there. Only in the beginning of a paragraph, it will increase the indent the paragraph, but it is not a tab character. 

Since the tab character is not included in the text, when you call the API to get the text, it is not included either. If you open a Word document that already has texts with tabs, the Word on the Web breaks them into text runs without adding the tab characters in the rendered content.

**Comment by tonyroberts** [comment]
@weshi If you look at the screenshot provided (or try it yourself) you will see that pressing the ‘tab’ key results in some blank space inserted between words in the middle of a paragraph. This may not be a ‘tab’ character on the web version of Word, but it is textual content. How can this white space be retrieved using the API?

I would suggest that using a tab character would be a reasonable solution, and would be consistent with other versions of Word. However, if as you say the tab char isn’t supported, even though the tab key press clearly is, I am of course interested in whatever other solutions you may suggest that works across all versions of Word.

@sumurthy and @kbrandl, please can you review and reopen and/or comment as you see fit? Thank you :)
