### ISSUE TITLE
MessageComposeCommandSurface does not add add-in to reply email

### ISSUE THREAD

**Issue by wonderplayer** [OfficeDev/office-js#700]
In Outlook Web, I can see my add-in whether I'm replying to email or creating a new one. But in Outlook Desktop App, I can only see my add-in when creating a new email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06e092f1-aa6a-45b5-50ce-a1afca772776
* Version Independent ID: fa9c31b7-b63a-9867-f298-4d579b899c30
* Content: [ExtensionPoint element in the manifest file - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/extensionpoint#messagecomposecommandsurface)
* Content Source: [docs/reference/manifest/extensionpoint.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/manifest/extensionpoint.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by sumurthy** [comment]
@exextoc is this by design?

**Comment by exextoc** [comment]
It is not by design.
For windows desktop, does the addin show up in popup reply window?
What is your outlook desktop build? Could you share manifest and screenshot for us to do more investigation?

**Comment by wonderplayer** [comment]
Sure.

> For windows desktop, does the addin show up in popup reply window?

No

> What is your outlook desktop build?

11929.20254 Click-to-Run

> Could you share manifest and screenshot for us to do more investigation?

Added manifest and screenshots.
[Archive.zip](https://github.com/OfficeDev/office-js/files/3582495/Archive.zip)

BTW, add-in is from tutorial: https://docs.microsoft.com/en-us/outlook/add-ins/addin-tutorial, only changed default tab to custom tab.

**Comment by exextoc** [comment]
Sorry, after taking a look at your manifest it looks like you are using a "Custom Tab". CustomTabs do not show up in In Line Reply, for Compose Mail Items. They do show up in the "popped out" inspector window of compose mails. This is currently a gap in our Add-in Command feature. If you need this feature you can request it on our UserVoice: https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins 

Custom Tabs do work for Read Mails in the Explorer. The workaround for Compose Mails is to currently use the Default Tab which will put your Add-in Buttons onto the "message" tab of the inline reply AND the popped out inspector.

**Comment by wonderplayer** [comment]
Nope, I've moved to CustomTab after DefaultTab was not showing them either. With CustomTab I prooved to myself that Add-In isn't loading and it's not just me who can't find buttons in DefaultTab.
So, same problem persists in DefaultTab for me.

**Comment by exextoc** [comment]
Could you please share the manifest that uses the default tab? I'm seeing compose add-ins in In-Line Reply just fine.

**Comment by wonderplayer** [comment]
I've checked it myself before sending to you and tried custom and default tabs and they really are working!
Seems that something was wrong with the mail I was testing on as for that mail Add-In still doesn't show up, but for all others it is fine...
The mail item might be broken as there are custom configurations on it.

Anyway, thank you very much for your assistance! Hope I didn't bother you too much.
