### ISSUE TITLE
Certificate issues with Edge

### ISSUE THREAD

**Issue by AlexJerabek** [OfficeDev/office-js#701]
I setup an Office Add-in using a manifest created by yo office (with the rest through the Vue setup and manual edits described in the [quick start](https://review.docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-vue?branch=master)). I opened a browser pointing to the add-in, running on localhost:3000, and trusted the certificate. When attempting to sideload the add-in, the service could not be reached from an Edge browser or the win32 client. Sideloading through Chrome (in Excel on the web) worked fine.

## Current Behavior
![image](https://user-images.githubusercontent.com/38896772/64214735-6f409400-ce66-11e9-91a5-448bafc84b95.png)

## Steps to Reproduce, or Live Example
Follow the steps outlined in the updated Vue quick start: https://review.docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-vue?branch=master

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop/ Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1910
* Operating System: Windows 10
* Browser (if using Office Online): Edge

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by sumurthy** [comment]
@nokafor Could you please look into this?

**Comment by sumurthy** [comment]
@kbrandl we are missing an area for this - it should be part of 'developer experience'

**Comment by kbrandl** [comment]
@sumurthy I've added a new label for **Area: DevX** and also added assignees (Sylvia and Julian). @jargil this issue also seems related to Edge WebView, as the add-in runs fine in Office Online using Chrome, but will not load in Office Online using Edge or in Office on Windows (which also uses Edge).

**Comment by jargil** [comment]
This is not related to certificates.

The yellow error bar has a "See Details" button that when clicked opens a browser to:
https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/cannot-open-add-in-from-localhost

That explains what's happening, and what to do.

**Comment by kbrandl** [comment]
@AlexJerabek when you have a chance, can you please try adding a local loopback exception (as described in the article that @jargil links to above), to see if that fixes the problem you're having with the add-in not running in Edge? Thanks!

**Comment by Rick-Kirkham** [comment]
@jargil Actually, I've been getting that same error with the same link frequently for a few days now on computers where I've already done the loopback enable for Edge. I've solved what was going wrong, but it was a wide variety of causes. So, that error is popping up in response to almost anything that goes wrong with the loading of the add-in. This is a bug. It should only appear (at least with that link in it) when loopback is  not enabled on the computer.

**Comment by jargil** [comment]
@Rick-Kirkham - improvements for our documentation? The error that Office is showing is simply saying that we could not access localhost. The link to our documentation is the one that just mentions the exemption loopback. Perhaps you should modify the document/link to mention other possible causes for localhost not being available and thus this error showing up.

**Comment by Rick-Kirkham** [comment]
@jargil The documentation team doesn't control that error message. The wording of the message that precedes the button implies that whatever the user sees when he clicks the button is the one and only thing that can cause the error. Perhaps the text just before the button could say something like "Click the button for information on one of several things that could be causing this error:" 

But that error message is in the source code of Office. We on the docs team cannot change it.

**Comment by AlexJerabek** [comment]
@jargil
The loopback exception did fix the problem. Thanks!
