### ISSUE TITLE
Updating a sideloaded add-in

### ISSUE THREAD

**Issue by ltanase77** [OfficeDev/office-js#704]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing

## Issue
There is no explication about how to make the Office application to show updates for a side-loaded add-in. In practice the Office 365 or IE 11 caching mechanism makes extremely difficult to see the changes made in add-in code. For some reasons the application is stuck in showing the old code, even if a renamed the files on the server and change the manifest.

**Comment by kbrandl** [comment]
@sumurthy can you please assign this issue to someone on the product team who can can provide clarification about the add-in caching issue that @ltanase77 has described? Thanks!

**Comment by sumurthy** [comment]
@croicu could you look into this?

**Comment by sumurthy** [comment]
Adding @jeremy-msft  as well

**Comment by ifflanb** [comment]
Any updates on this. We are having the same issue ... what is the recommended approach for refreshing an office web add-in following a deployment of updated add-in files?

**Comment by dakshika** [comment]
Any update on this?

**Comment by jeremy-msft** [comment]
Hi @dakshika, please see https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache for guidance on clearing the add-ins cache.  If you are still seeing issues, please also try clearing the browser cache in the corresponding browser (https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins).

**Comment by swapnilwk** [comment]
In Microsoft Edge Devtools Preview, 
Go to Network Tab then click on "Always refresh from server" and then press Ctrl + R or F5 to reload. This should reflect code changes in Debugger tab.

**Comment by namnn96** [comment]
Hi all,

Using Edge Devtools works for development, but we cannot expect the clients who consume the add-ins to do the same thing everytime there is a new release pushed.

Asking users to perform some cache management is not an ideal thing to do, is there a way we could control this cache from our app? We added the meta tags for Cache-Control, Pragma and Expires but they don't seem to be sufficient, the issue would randomly come back where it loads a staled html.

**Comment by Iso5786** [comment]
As we are also planning to release a public version of our add-in for testing purposes, I also would like to know what the best way is on updating a sideloaded add-in as I do not want that users need to manually re-add the add-in or clear cache, or ...

Edit: I just figured that a hard reload, which clears the cache, via CTRL + F5 works within a browser, and within the mobile Outlook app it automatically refreshes :)

**Comment by awhowart** [comment]
The simplest solution I've found is to append a URL parameter to the SourceLocation element in the Add-in Manifest, which gets incremented with every release. The updated URL forces the client to resolve the URL on the server instead of the local cache.

```
<Version>1.0.0.0</Version>
...
<DefaultSettings>
  <SourceLocation default="https://www.github.com/index.html?version=1.0.0.0" />
</DefaultSettings>
```

Another option, if you are on a regular release cycle, may be to adjust the cache expiry in the HTTP Headers.

**Comment by YossiCohen** [comment]
@awhowart 
Do I need to add the parameter to all the links in the manifest?
Or does it works also if we change only the Default serrings?

**Comment by awhowart** [comment]
Updating the Version tag alone should work for bypassing the local cache, but it doesn’t always. Not in my experience anyway. That’s why I also update the SourceLocation as well.

I should clarify that I use WebPack to build my application, which automatically changes any JavaScript / CSS filenames, so they wouldn’t exist in the cache yet. I just need to force the updated HTML file down from the server. 

I don’t need to change any other links in the manifest file.
