### ISSUE TITLE
"Upload My Addin" button doesn't exist

### ISSUE THREAD

**Issue by Dmytrooo** [OfficeDev/office-js#705]
in "Office Add-ins" dialog on "MY ADD-INS" tab I see neither "Manage My Add-ins" or "Upload My Add-in" buttons. please describe why they may not be visible and how to make them so

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0ab35128-1e97-c6ad-babc-f696f2e7b0fe
* Version Independent ID: cd1bacb1-14d7-a38d-321c-ebc2a526e03b
* Content: [Sideload Office Add-ins in Office on the web for testing - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/sideload-office-add-ins-for-testing#feedback)
* Content Source: [docs/testing/sideload-office-add-ins-for-testing.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/testing/sideload-office-add-ins-for-testing.md)
* Product: **non-product-specific**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by kbrandl** [comment]
@sumurthy can you please assign this issue to someone on the product team who can can provide clarification about the missing "Manage My Add-ins" link that @Dmytrooo has described? Thanks!

**Comment by lindalu-MSFT** [comment]
FYI, the "Upload My Add-in" link does appear in the online version of Excel:
![image](https://user-images.githubusercontent.com/30682803/64455604-f11d0100-d0a2-11e9-8f76-6f59545342ba.png)

**Comment by lindalu-MSFT** [comment]
Weird, I definitely experienced this exact issue several days ago, and so I would use the Online version. But NOW when I go to the desktop version of Excel, I see it. I'm using Build 16.0.12105.35900. Is there a more recent version @Dmytrooo should try to update to?

**Comment by sumurthy** [comment]
@jeremy-msft is this something you can look into?

**Comment by keyur32** [comment]
Hi @Dmytrooo, this is because the "Upload my add-in" only is available on Excel for the web. In your screenshot you are trying  it on desktop and you'll need to use a different sideload option:

https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins

**Comment by keyur32** [comment]
Closing this for now. Let me know if this doesn't work for you. thanks.

**Comment by Dmytrooo** [comment]
thanks for the response, it is pity that shared folder is the only option but we have what we have...

**Comment by bison--** [comment]
Sorry for writing in such an old issue, but I have the exact same issue but i am on the Word desktop app and trying to test my very small add-in.
This is what the dialog looks like.
Exactly the same issue @Dmytrooo had.
![image](https://github.com/OfficeDev/office-js/assets/901400/e05d0f4a-407e-4f01-ae8f-a2230bd2438d)

**Comment by lindalu-MSFT** [comment]
@bison-- did you try the steps outlined here? https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins 

According to an answer previously posted on this thread, how you sideload add-ins is different in Online vs Desktop.
