### ISSUE TITLE
How return date from custom function?

### ISSUE THREAD

**Issue by Biktop** [OfficeDev/office-js#706]
I implemented custom function which return value with different types (e.g. string, number, date). If I return value as number (e.g. **10**, **10.101**) then Excel detects type correctly.

But I don't understand what I should return in case of date? I've tried different variants such as:

1. **new Date()**

1. **"2020-10-12"** (it works if insert data via office.js API).

1. **"2019-09-04T23:42:24.919Z"** (ISO)

In all above cases Excel treats value as string.

**Comment by RuoyingLiang** [comment]
@Biktop, Thanks for reaching out. Currently Custom Function support string and number, but not support other data types.  We are working on improving that. Will let you know once we have solution. Could you let me know more about your scenario and add-in?

**Comment by Biktop** [comment]
@RuoyingLiangm, my scenario is next:
User can configure my custom function for cell which retrieves values from external source. It could be strings, numbers and dates. 

In case of numbers and strings function returns JS types and Excel autodetects values (aligns values to right side). But in case of date (or date with time) Excel treats it as simple text (e.g. user cannot app date/time formats).

But in my sideload addin I insert data via Office.js SDK and Excel recognizes dates if I use format YYYY-MM-DD.

**Comment by erharvey** [comment]
I got the same issue on my side. Any updates on this feature?

**Comment by RuoyingLiang** [comment]
The support is on the way :)

**Comment by grangeryy** [comment]
Feature：4664778

**Comment by suresh-anumolu** [comment]
I am facing similar issues with date format.. Can you let me know when this feature will be released?

**Comment by grangeryy** [comment]
@suresh-anumolu , hey we are under development on this new feature to support Custom Functions to return formatted number values. It will be soon in Beta version.

**Comment by jordandev** [comment]
Great really need this

**Comment by suresh-anumolu** [comment]
> @suresh-anumolu , hey we are under development on this new feature to support Custom Functions to return formatted number values. It will be soon in Beta version.

Grangeryy - any update on when this feature will be available ?

**Comment by grangeryy** [comment]
@suresh-anumolu, thanks for checking! We are almost there. Currently we still need some time to do the validation tests and fix bugs. Pls stay tuned!

**Comment by grangeryy** [comment]
@suresh-anumolu we finally make this into preview recently. Pls have a try: [HERE](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-data-types-concepts#output-a-formatted-number-value)

**Comment by danielpdev** [comment]
@grangeryy do you happen to have a code snippet for returning a date type ?
I need to return a value that should be formatted as a date by excel, but could not found a snippet of code doing that.

**Comment by grangeryy** [comment]
@danielpdev, you may find more info here:[customizing a number format]( https://support.microsoft.com/en-us/office/review-guidelines-for-customizing-a-number-format-c0a1d1fa-d3f4-4018-96b7-9c9354dd99f5)

**Comment by kgeorgiou1234** [comment]
Any update on this feature? It is in preview for some time now.

**Comment by kalypsod** [comment]
@adrianwu8516 do you have any update on this? Do you have a timeline on when this will be available?
In addition, a code snippet for returning a date value would be very helpful.

**Comment by grangeryy** [comment]
@kalypsod, the feature is already available. The support is released with [CustomFunctionRuntime1.4 ](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-data-types-concepts#output-a-formatted-number-value) and you need to set [allowCustomDataForDataTypeAny JSON manifest property] (https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-json#allowcustomdatafordatatypeany) first and then use the feature called [Formatted Number CellValue](https://learn.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-data-types-concepts#output-a-formatted-number-value). 

For the code snipped, you can check [this](https://github.com/OfficeDev/office-js-snippets/blob/prod/samples/excel/16-custom-functions/data-types-custom-functions.yaml), search the word "Add Unit Price as a formatted number".
For the parameter of numberFormat: you can define a string using [excel date format](https://support.microsoft.com/en-us/office/review-guidelines-for-customizing-a-number-format-c0a1d1fa-d3f4-4018-96b7-9c9354dd99f5).
Hope it helps:)
