### ISSUE TITLE
Excel Desktop is throwing OLE Error 

### ISSUE THREAD

**Issue by ravikmrsingh8** [OfficeDev/office-js#708]
We are trying to create diagram from the excel  table data. The table get inserted and then Excel throws the  error "Microsoft Excel is waiting for another application to complete an OLE action" .
Could you please let us know when this error could happen.

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]:PC desktop ______
* Host [Excel, Word, PowerPoint, etc.]: ______Excel
* Office version number: ______
* Operating System: ______Windows
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
![OLE](https://user-images.githubusercontent.com/22787917/64317628-ee080f00-cfd5-11e9-8c08-ee298f712bad.png)

**Comment by sumurthy** [comment]
Sorry, this doesn't sound like Office.js related issue. Can you confirm if you are referring to add-in related issue or Excel product related? If Excel product related then logging a stanckoverflow issue and tagging with excel would be more productive.
