### ISSUE TITLE
Excel add-in is missing on the office store (Mac)

### ISSUE THREAD

**Issue by jjtfsalgado** [OfficeDev/office-js#709]
We've deployed an excel add-in to the office store using the office js api but recently we noticed some users couldn't find it on the store using excel desktop in the mac (works fine in excel online and in windows, both online and desktop). According the [documentation](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/requirements-for-running-office-add-ins#client-requirements-os-x-desktop), both version and subscription seem to match the minimum required. 

## Expected Behavior
Being able to search and load the "Iplicit" excel add-in on the mac

## Current Behavior
Nothing shows up, the add-in seems to not exist

## Steps to Reproduce, or Live Example
[Demo ](https://jose-iplicit.tinytake.com/tt/Mzc0NjUxNl8xMTQxMDQ0Ng)

## Your Environment
* Platform [Mac]
* Host [Excel]
* Office version number
![image](https://user-images.githubusercontent.com/14180997/64329676-8a76e500-cfc7-11e9-8672-d36abb5e06b4.png)

* Operating System: macOs High Sierra - Version 10.13.6

**Comment by sumurthy** [comment]
Can you please provide the requirement sets that you may have in your manifest?

**Comment by jjtfsalgado** [comment]
> Can you please provide the requirement sets that you may have in your manifest?

Sure @sumurthy :

```
<Requirements>
	<Sets DefaultMinVersion="1.1">
	     <Set Name="ExcelApi" MinVersion="1.1"/>
             <Set Name="CustomFunctionsRuntime" MinVersion="1.1" />
	</Sets>
</Requirements>
```

**Comment by AlexJerabek** [comment]
@sumurthy, Can you please follow up based on the provided information or reassign as necessary. Thanks!

**Comment by keyur32** [comment]
Hi @jjtfsalgado, there is a currently an issue that is preventing store add-ins from appearing in the Mac client store. We will revert back when it is addressed.

**Comment by sumurthy** [comment]
This is still unresolved due to a version# mismatch between what's being sent from the client and our backend system. We're looking into this issue. Sorry it's taking a long time to fix this.

**Comment by sumurthy** [comment]
We addressed this issue with this PR: https://github.com/OfficeDev/Office-Js-Requirement-Sets/pull/45/files
ExcelApi 1.1 and CustomFunctionsRuntime 1.1 now has the correct build# 

Could you please verify that is the case on your end?
