### ISSUE TITLE
Word Paragraph.insertHtml does not insert the last item in a list properly

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js#71]
When inserting a list structure with Paragraph.insertHtml(), the last \<li\> item is inserted as a non-list paragraph after the list. 

## Expected Behavior
Every \<li\> in an \<ol\> or \<ul\> should be included as an item in the list. 

## Current Behavior
When inserting a list structure with Paragraph.insertHtml(), the last \<li\> item is inserted as a non-list paragraph after the list. 

## Steps to Reproduce, or Live Example
This snippet shows the problem. The last paragraph in the list "a third item" is formatted as a non-list item and appears after the list. 

```
await Word.run(async (context) => {
        context.document.body.paragraphs.getLast()
            .insertParagraph("", "after")
            .insertHtml('<ul><li>a list item</li><li>another list item</li><li>a third item</li></ul>', "end");

        await context.sync();
    });
```

## Context
Creating Word snippets for Script Lab. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 1803 9123.1000 C2R
* Operating System: Win 10
* Browser (if using Office Online): ______

**Comment by JuaneloJuanelo** [comment]
this is a known issue we have 1158080 tracking.

**Comment by Rick-Kirkham** [comment]
Reopening because a customer is experiencing a variation of this: [inconsistent-host-behavior-with-office-js-inserthtml-and-paragraph-formatting](https://stackoverflow.com/questions/49558548/inconsistent-host-behavior-with-office-js-inserthtml-and-paragraph-formatting/49565600#49565600)
Is there any way that I can get the priority of https://office.visualstudio.com/OC/_workitems/edit/1158080 raised?

**Comment by JuaneloJuanelo** [comment]
have the customer open another issue. please do not re-open.
