### ISSUE TITLE
Dialog crashes after being idle for ~5-6 mins.

### ISSUE THREAD

**Issue by hmistry-lz** [OfficeDev/office-js#711]
I have an outlook add-in which opens up Dialog using `displayDialogAsync`. It crashes after keeping it open for ~5-6 mins. After that I am unable to open unless I refresh the tab in which it was open.

## Expected Behavior
It should not close itself after being idle.

## Current Behavior
Dialog crashes and closes the modal as a result and I am unable to use it thereafter.

## Steps to Reproduce, or Live Example
Install this plugin 
https://appsource.microsoft.com/en-us/product/office/WA200000175

Try to Schedule Meeting and leave it open for ~5-6 mins

## Context
This plugin helps our customer schedule meeting from outlook. It creates less than desirable experience for them if they have to reload the page and start setting up the meeting from start.

## Your Environment
* Platform : Mac & Windows
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: MacOs and Windows 7
* Browser (if using Office Online): Chrome

## Useful logs

![image](https://user-images.githubusercontent.com/53185673/64359549-260b5400-cfce-11e9-8f03-baf62acfc62a.png)

![image](https://user-images.githubusercontent.com/53185673/64359567-328fac80-cfce-11e9-82d2-b1ac5aad7bc8.png)

**Comment by exextoc** [comment]
Does the issue happens in browser only, or also in windows outlook desktop?

**Comment by hmistry-lz** [comment]
It only happens in browser

**Comment by sumurthy** [comment]
@lliu113 would that be you to review this and get back?

**Comment by exextoc** [comment]
Thanks for reporting the issue. The time-out of 330s for UI less add-in is an intended behavior. We will update the documentation to reflect the same. We have created a workitem in our backlog for the crash issue.

**Comment by hmistry-lz** [comment]
@exextoc Is there any way we can prevent the crashing before the team ships out fix for this issue?

**Comment by as-aaron** [comment]
What is the purpose of the time out? Is there a way to extend the duration? We have a potentially long running task in a dialog that would need to be reconsidered if this is the case.

**Comment by exextoc** [comment]
Since there is no UI for the UI less Add-ins, the time-out is there to prevent the Add-ins from running indefinitely without user being aware of it. Furthermore, since some of the Outlook functionalities such as mail encryption are blocked while the UI less Add-in runs, timeout avoids bad user experience.

There are no plans yet to increase the time out. Please raise a user voice request for it:
https://outlook.uservoice.com/forums/907141-the-new-outlook-on-the-web-office-365

**Comment by Saarnaki** [comment]
Has anybody figured out a way to prevent this?

In our case the user fills out a form in the dialog which in some cases can take longer than the said 330 seconds. And this itself causes bad UX, since they have to open it up again and enter the same details - again.

**Comment by tobiasviehweger** [comment]
We do save a copy of the current UI state and restore it if the dialog was forcefully closed. Not great, but better than losing everything...

**Comment by illing2005** [comment]
We're using the dialog in `ExecuteFunction`. 
Is there a way to get notified when `ExecuteFunction` times out?
