### ISSUE TITLE
Excel sidebar add-in opens links in a weird window rather than browser. 

### ISSUE THREAD

**Issue by leandrolares** [OfficeDev/office-js#712]
Previous to Edge WebView in Windows 10, links inside an Excel add-in opened in the default browser. Now they open in a weird window inside Excel. This happens with both <a> tags (<a target="_blank">) and JavaScript window.open("https://...").

This weird browser-like window inside Excel lacks the print functionally, which is required in my use case. Further more, PDFs inside iframes are not displayed.

**Comment by sumurthy** [comment]
@jargil is there a guidance we can provide here?

**Comment by jargil** [comment]
@leandrolares - For tags you'll have to use a script to popup the browser. From JavaScript could you please try something like this with your own urls:

```
if (window.navigator.userAgent.indexOf("WebView") > -1 && window.navigator.userAgent.indexOf("Edge") > -1) {
      Office.context.ui.openBrowserWindow(self.location.href);
    }
```

**Comment by leandrolares** [comment]
@jargil - Simply executing this
```
if (window.navigator.userAgent.indexOf("WebView") > -1 && window.navigator.userAgent.indexOf("Edge") > -1) {
  Office.context.ui.openBrowserWindow(self.location.href);
}
```
opens the sidebar of the add-in itself in the default browser.

This code
```
if (window.navigator.userAgent.indexOf("WebView") > -1 && window.navigator.userAgent.indexOf("Edge") > -1) {
  myButton.addEventListener('click', () => {
    Office.context.ui.openBrowserWindow('myUrl');
  });
}
```
doesn't do anything when I click myButton.

**Comment by leandrolares** [comment]
@jargil - I'm having the same issue in Excel for Mac now, therefore it's specific to Edge View.

**Comment by jargil** [comment]
@leandrolares - Sorry I don't understand your last comment. We don't use Edge View in Mac, that would be WebKit instead.

For the problem where your "myButton" does not do anything on click, you'd need to debug your add-in to make sure that the proper event is being attached to the button on the right time with regards to its DOM lifecycle. The fact that executing the script by itself does what is expected should be enough from our platform side of things. Makes sense?

**Comment by jargil** [comment]
@sumurthy - sending it back to you to follow up.

**Comment by sumurthy** [comment]
@lliu113 is this something you could follow-up on?

**Comment by jargil** [comment]
I think the main question was answered. Please comment again if you are still having problems and we'll reactivate!

**Comment by amiqat** [comment]
if (window.navigator.userAgent.indexOf("WebView")) {
not work on mac how on mac can make it work

**Comment by sergioalcalaweb** [comment]
> if (window.navigator.userAgent.indexOf("WebView")) {
> not work on mac how on mac can make it work

you can try with this validation 

if (Office.context.platform == 'OfficeOnline') {
 // code that work only in browser office apps
}
