### ISSUE TITLE
The Value of Office.context.OfficeTheme is not Changed When Changing the Excel's Theme with Edge Engine 

### ISSUE THREAD

**Issue by Lijing29** [OfficeDev/office-js#713]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
The value of Office.context.OfficeTheme should be changed when the Excel's theme is changed

## Current Behavior
The value of Office.context.OfficeTheme is not changed when the Excel's theme is changed

## Steps to Reproduce, or Live Example

* Repro Steps:
1. Use Edge Engine
2. Open Ideas
3. Change the theme
4. Observe the issue

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.12026.20060
* Operating System: Windows 10 Enterprise Version: 1903  OS build: 18362.295

## Useful logs

Below are snapshots based on the repro steps:
The initial theme is black:
![image](https://user-images.githubusercontent.com/50400285/64395952-9a0d3100-d08e-11e9-89dd-4774bda4fa0a.png)
Change the theme to Dark Gray:
![image](https://user-images.githubusercontent.com/50400285/64395962-a1ccd580-d08e-11e9-9a26-cf72e72b2cc9.png)

**Comment by MandytMSFT** [comment]
I can repro on version 1909(build 12026.2000 click to run). One simple way to repro is :

1. Run console.log(Office.context.officeTheme);  from script lab to get current officetheme with Edge webview
2. Change officeTheme from UI to a different one  (see screenshot) then run step1 again
3. You can see the officeTheme from scriptlab didn't change 

But if i switch to IE webView, it works fine

async function run() {
  await Excel.run(async (context) => {

    console.log(Office.context.officeTheme);

  });
}
![OfficeTheme](https://user-images.githubusercontent.com/52641972/64406817-5b3ea180-d0b5-11e9-9b94-6862a50682f4.png)

**Comment by MandytMSFT** [comment]
@jargil is this a known issue for edge webview ?

**Comment by MandytMSFT** [comment]
Filed BUG 3620704 to track internally.
