### ISSUE TITLE
Addin doesn't respond when trying to read 1000 rows of data

### ISSUE THREAD

**Issue by jag-cloudextend** [OfficeDev/office-js#715]
When we try loading values for 1000 rows 6 columns, Excel API sync doesn't respond with either success or failure.

## Expected Behavior
Excel API should return values for the cells

## Current Behavior
API never responds making addin wait forever

## Steps to Reproduce, or Live Example
1. Read 1000 rows of data from a sheet
#### Sample Data
https://celigo3-my.sharepoint.com/:x:/g/personal/jagapathi_celigo3_onmicrosoft_com/EfrSnfBaktRGjZreDWYlMbEBUwbmVlukC03NN423Lbc8OQ?e=HCvNrv
#### Code gist
https://gist.github.com/Jagapathi126/130370b2d02c324c6e0e830760a0e13c

## Context
Our taskpane app reads data from Excel make webservice request to create records in ERP system. So if a user has 1000 records and try to use addin, it goes into a loading state

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Office Home and Business 2016 (Build 11929.20254)
* Operating System: Windows 10
* Browser (if using Office Online): N/A

**Comment by sumurthy** [comment]
@weshi

**Comment by jargil** [comment]
Please refer to #697 

The estimate for this fix to begin deploying is this coming week.
