### ISSUE TITLE
Excel Desktop: Warning: Office.js is loaded outside of Office client on Addin reload

### ISSUE THREAD

**Issue by ravikmrsingh8** [OfficeDev/office-js#716]
When we reload the addin in excel desktop, it displays the blank page and we see the warning: 
Office.js is loaded outside of Office client.

## Expected Behavior

Addin should reload properly and should not display the above warning as the host is excel desktop 
## Current Behavior
When we reload the addin in excel desktop, it displays the blank page and we see the warning: 
Office.js is loaded outside of Office client.
In any browser if i upload the manifest and try reload it works it fails only in case of excel desktop.

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Context
Once we face this issue the addin corrupts and becomes unusable. It can not be opened in browser too.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: _PC Desktop_____
* Host [Excel, Word, PowerPoint, etc.]: ___Excel
![Officever](https://user-images.githubusercontent.com/22787917/64491463-63017000-d286-11e9-8c7c-56c78c5a2a84.PNG)
___
* Office version number: ___1910(Build 12030.20004 C2R)___
* Operating System: __Windows 1903 _OS Build 18362.295___
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by RuoyingLiang** [comment]
Desktop's sideload process is different than online. During debuging and testing,  please see [https://docs.microsoft.com/en-us/office/dev/add-ins/testing/create-a-network-shared-folder-catalog-for-task-pane-and-content-add-ins] for how to side load add-in in desktop. After the add-in is published to store, the add-in would be loaded successfully cross platforms.

**Comment by ravikmrsingh8** [comment]
Addin is published to the store (Private preview). I see the same issue. in online it works fine but fails in desktop.
In desktop it loaded fine when addin is created but shows a blank page when reloaded, I see the warning  "Office.js is loaded outside of Office client"

**Comment by AlexJerabek** [comment]
@nokafor, Could you please investigate?

**Comment by ravikmrsingh8** [comment]
Tried Office.initilize and Office.onReady but got no luck. intialization handlers are not getting called on Addin Reload

**Comment by ElizabethSamuel-MSFT** [comment]
@millerds Can you take a look? Thanks.

**Comment by millerds** [comment]
I don't see any dev tooling questions here.  It sounds like and add-in that already being hosted for store access.  Someone on the platform might know more, but I'm not sure who to talk to.

**Comment by ElizabethSamuel-MSFT** [comment]
@slabereemsft Is this something you can take a look at? Thanks.

**Comment by ElizabethSamuel-MSFT** [comment]
@ravikmrsingh8 Sorry for the late response but are you still facing this issue? Thanks.

**Comment by slabereemsft** [comment]
I tried using the Wikipedia add-in in Excel and clicking the reload button on the menu from the upper right of the task pane.  It reloaded fine.  Given the age of the bug this has either resolved itself or we need more information about the repro to investigate.  Waiting for author feedback.
