### ISSUE TITLE
Dialog API is not loading URL in frame in Outlook 16

### ISSUE THREAD

**Issue by hmistry-lz** [OfficeDev/office-js#717]
I am using `displayDialogAsync` API to load our application in iFrame. When I click on `Schedule` UI-less component in Outlook 16 for Mac, It only displays a blank white screen. 

## Expected Behavior
It should render the application correctly as it does in OWA
## Current Behavior
Plugin fails to render the URL and it displays a blank screen.

## Steps to Reproduce, or Live Example
Install this plugin in Outlook 16 for Mac. It only happens in **_macOs 10.12 Sierra_**.
https://appsource.microsoft.com/en-us/product/office/WA200000175
I am unable to debug it on that specific macOS 10.12 version as it is not supported.

## Context
It is not creating a consistence experience for our user when they switch between OWA and Desktop outlook

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook 16
* Office version number: ______
* Operating System: macOS Sierra (10.12.6)
* Browser (if using Office Online): ______

## Useful logs
![image](https://user-images.githubusercontent.com/53185673/64562704-23cd3080-d313-11e9-85f8-9b2c93c8b620.png)

**Comment by AlexJerabek** [comment]
@exextoc, Can you please take a look at this?

**Comment by exextoc** [comment]
We are not able to open https://appsource.microsoft.com/en-us/product/office/WA200000175. Could you verify if that is the add-in link you wanted to share?

Can you also verify that the API works in the latest OS versions, and the issue _only_ happens in Mac OS Sierra 10.12?

EDIT: We are able to access the link now.
