### ISSUE TITLE
context.sync() hangs if character length exceeds threshold

### ISSUE THREAD

**Issue by CGann** [OfficeDev/office-js#719]
Attempts to get all the text from the body of the document using the code below are failing if the document exceeds a character length threshold. The the first 'return context.sync()' operation hangs indefinitely. 

The threshold value appears to be affected by document formatting. 

## Expected Behavior
I'm expecting to be able to get the full text of the document. But, if I can't for some reason, I'd like to be able to report that the document exceeds maximum length.

## Current Behavior
In one case, a document with many cutsom tab stops, colored text, bulleted lists, etc, the first 'return context.sync()' operation hung if the length of the text exceeded 62,303 characters. In another case, a document with only moderate formatting applied, it hung if the length exceeded 64,052 characters. In another case, with no custom formatting applied, the character threshold was 64,139 characters

See question on StackOverflow:
https://stackoverflow.com/questions/57858436/context-sync-promise-not-resolving?noredirect=1#comment102153551_57858436

## Steps to Reproduce, or Live Example
Script Lab snippet: https://gist.github.com/CGann/bcfba9516ef3372e7c9281949423dc51
Follow these steps to reproduce the issue
1. Open the attached test document* in MS Word 2016 or Online
2. Open the Script Lab Add-in
3. Import the snippet YAML from the gist url
4. Run the snippet and check the output in the console.log window.

	If successful, the output should read-
		await context.sync() 
		DONE: await context.sync() 
		lenText: 64140
		
	If unsuccessful, the output should read-
		await context.sync() 
	The snippet will stay in context.sync() indefinitely.
	
5. You can then add or remove characters until your result changes.

* If you can't use the attached test document then copy the Lorem Ipsum text (below) and paste repeatedly into the body of the document until you have 18 pages worth of text. You do not have to save the document to test.

--== copy text from below this line==--
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent mattis orci vitae mi tempor blandit. In ut purus lorem. Vivamus id sagittis arcu. Cras ipsum magna, porttitor in orci at, euismod tristique est. In fringilla dolor quis arcu dapibus, sed tristique arcu ultricies. Duis id tortor ut libero dictum aliquet sed in tortor. Aliquam hendrerit nisi ut nisl sagittis facilisis. Fusce lacinia sed nulla et laoreet. Cras porta metus at laoreet gravida. Vestibulum sollicitudin augue eget lacus congue fermentum. Ut fringilla id enim ac vestibulum.
Praesent sed ex sit amet massa porta vestibulum eu a dui. Nullam aliquam arcu et efficitur mollis. Vivamus efficitur rutrum risus et hendrerit. Donec non gravida massa, sed bibendum felis. Vivamus sodales sapien odio, vitae convallis mauris facilisis in. Nam felis nisl, pharetra nec justo non, dignissim auctor neque. Fusce quis bibendum quam. Nullam interdum, ex ut efficitur ultricies, massa orci venenatis justo, in viverra risus lorem ac erat. Suspendisse potenti. Maecenas eu finibus lectus. Fusce et suscipit mi.
Suspendisse potenti. Mauris sed diam semper, euismod ligula et, sodales turpis. Sed sed sodales nisl. Nulla id accumsan elit, vel laoreet felis. Proin dignissim maximus convallis. Fusce hendrerit tortor velit, nec euismod nunc volutpat hendrerit. Maecenas vitae ultricies nibh.
Praesent id molestie elit, eget sodales diam. Duis finibus, velit non pharetra suscipit, lacus nibh egestas purus, ac porttitor mauris sem ut odio. Vestibulum vulputate at orci eu mollis. Nunc nec ligula semper, vehicula lacus ac, sagittis quam. Donec ac turpis at nulla finibus mattis. Sed aliquet pulvinar molestie. Curabitur sollicitudin, turpis luctus vehicula aliquet, odio dui viverra nunc, at cursus nunc augue quis mauris. Aenean vulputate augue ex, non mollis tellus malesuada at.
In ut bibendum justo, a vulputate erat. Vivamus imperdiet finibus eros, at mollis enim ornare fringilla. Morbi lacinia, odio ut vehicula pretium, est velit condimentum nisi, lacinia ornare arcu augue vel erat. Proin efficitur metus mi. Fusce non tempus leo, eget venenatis arcu. Pellentesque luctus venenatis est ac cursus. Etiam neque nunc, porttitor vitae vestibulum non, convallis id mi. Etiam vulputate nisl ipsum. Etiam interdum eros vitae tellus rhoncus semper vel non augue.
Nullam rutrum elit metus, id tempus justo vestibulum quis. Nam ante risus, aliquet vitae ultrices sit amet, scelerisque a est. Ut euismod ligula a libero eleifend bibendum. Vivamus tincidunt erat at ante scelerisque porta. Etiam enim tellus, tincidunt sit amet libero in, iaculis auctor eros. Quisque id scelerisque mauris. Proin ullamcorper tristique pulvinar. Morbi accumsan augue odio, non pretium urna rhoncus at. Suspendisse venenatis est id augue posuere scelerisque. Donec eros elit, tincidunt vitae sodales ac, consectetur tempus ex. Nullam eu maximus metus, eget suscipit lacus. Nulla placerat vitae eros nec lobortis. Suspendisse maximus eros nec dolor iaculis, quis imperdiet libero gravida. Aliquam viverra quam non lacus sagittis efficitur.
Vestibulum mi lectus, pretium ac cursus in, ornare sed nulla. Vivamus condimentum purus ac dolor iaculis, ac ornare sem convallis. Sed arcu lacus, imperdiet id augue hendrerit, feugiat pharetra lectus. Ut ut libero id ligula laoreet eleifend. Suspendisse ultricies eros vitae convallis ullamcorper. Proin egestas dolor eget pellentesque bibendum. Mauris non purus eget dolor ultrices feugiat at nec nunc. Etiam lacinia, magna auctor pulvinar tempor, tellus erat finibus nulla, eget fringilla quam diam in erat. Vestibulum dignissim sapien quis nibh scelerisque, quis facilisis ligula blandit.
Vestibulum dignissim sapien quis nibh scelerisque, quis facilisis ligula blandit.
--== copy text from above this line==--

## Context
My add-in needs to retrieve all the text from the body of a document in order to pass along to my api for processing. If there is a limit to the length of the characters that can be retrieved in a single call then users need to be made aware of it or a method needs to be produced in order to work around the limitation.

## Your Environment
* Platform: PC desktop, Office Online
* Host: Word
* Office version number: 1908 build 11929.20254
* Operating System: Windows 10
* Browser: MS Edge

## Useful logs
- [X ] Test file (if only happens on a particular file)
[Unformatted Test Doc.docx](https://github.com/OfficeDev/office-js/files/3596764/Unformatted.Test.Doc.docx)

**Comment by AlexJerabek** [comment]
Thanks for reporting this @CGann. @sumurthy, can you please investigate?

**Comment by CGann** [comment]
My pleasure. Thanks for looking into it so quickly! If there's anything else I can do to help please let me know.

**Comment by ghm9836** [comment]
@sumurthy @AlexJerabek This issue is deep impact for our startup launch and sumurthy appears to be away for Sept.  May we please have an active person assigned in his place? I'm new to github so please excuse my ignorance if the request is impolite.

**Comment by m-mains** [comment]
@CGann @ghm9836 I think this is the same issue as has already been reported here. The good news is there are indications it has been fixed as of latest builds (although they might not be distributing quite yet) See #702 where the 64kb threshold was the issue. That issue refers to #697 for the fix. This was an Excel issue but the same underlying problem, an IE11/Edge inconsistency in which the Edge engine the sidebar runs on had a bug.

Definitely try updating. Per comments in 697 the version that fixed it was released on the 10th so it should be available for us.

**Comment by sumurthy** [comment]
Refer to related issues.
