### ISSUE TITLE
Inconsistent styling when HTML inserted with Word Paragraph.insertHtml

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-js#72]
When inserting paragraphs with Paragraph.insertHtml(), the first paragraph is formatted with an HTML default. For example, the font is Times Roman. All other paragraphs get the current Word paragraph style at the insertion point.

## Expected Behavior
Every paragraph inserted should get the current Word paragraph style of the insertion point.. 

## Current Behavior
When inserting paragraphs with Paragraph.insertHtml(), the first paragraph is formatted with an HTML default. For example, the font is Times Roman. All other paragraphs get the current Word paragraph style at the insertion point.

## Steps to Reproduce, or Live Example
This snippet shows the problem. The fist paragraph is formatted with Times Roman, which seems to be a browser default formatting. The second paragraph gets the paragraph formatting that is in force at the point of the insertion.  

```
await Word.run(async (context) => {
        context.document.body.paragraphs.getLast()
            .insertParagraph("", "after")
            .insertHtml('<p>Inserted HTML.</p><p>Another paragraph</p>', "end");

        await context.sync();
    });
```

## Context
Creating Word snippets for Script Lab. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 1803 9123.1000 C2R
* Operating System: Win 10
* Browser (if using Office Online): ______

**Comment by JuaneloJuanelo** [comment]
This issue is by design. HTML supports formatting and we never override it with the document style. if the developer needs to keep the document style she/he needs to use the paragraph or insertText APIs.

**Comment by GeneZharov** [comment]
You can achieve that for web clients by adding these styles to your inserted HTML (but it won't work for desktop clients):

```
<html>
  <head>
    <style>
      * {
        line-height: inherit;
        font: inherit;
        text-decoration: inherit;
        color: inherit;
      }
    </style>
  </head>
  <body>...</body>
</html>
```
