### ISSUE TITLE
Missing restUrl in window.Office.context.mailbox.restUrl (Outlook)

### ISSUE THREAD

**Issue by modestfake** [OfficeDev/office-js#721]
Sometimes `restUrl` is missing when accessing it from `window.Office.context.mailbox.restUrl`. It's really hard to reproduce it, it only happens to me once. But I see this happens quite often for our customers.

## Expected Behavior
`restUrl` is in `window.Office.context.mailbox.restUrl`, so we can use it to send requests.

## Current Behavior
`restUrl` is an empty string `''` sometimes.

## Steps to Reproduce, or Live Example
Open add-in sidebar and check `window.Office.context.mailbox.restUrl` value. Sometimes it's `''`.

## Context
When a user doesn't have `restUrl`, we can't send a request to get user's attachments (`GET /v1.0/me/messages/{message-id}/attachments`.

## Your Environment
* Platform: `PC desktop`, `Mac`
* Host: `Outlook`
* Office version number: `16.0.11328.20392` (55%), `16.0.11929.20254` (24%), `16.0.11231.20130` (10%), `16.21 (190117)` (5%), `16.27 (190715)` (4%), `16.0.11328.20368` (2%).
* Operating System: `Windows 7/10`, `Mac OS X`

**Comment by AlexJerabek** [comment]
Thanks @modestfake for writing this up as a separate issue. Assigning to @exextoc to investigate and track.

**Comment by exextoc** [comment]
@modestfake When the restURL is empty, is it empty throughout that session of outlook? Also, can you make sure you are calling this withing after office.initialize is called? If you're addin is pinned, you should be calling this after listening to the itemChangedEvent. Also, what exchange are you connecting against, exchange online/on-prem?

**Comment by modestfake** [comment]
Hi @exextoc. Sorry, I was on vacation, so couldn't respond.
We log `accountType` for every error. This happens 98% for Office365 account types. So, it's probably not Exchange.
This happens after `Office.onReady()`. I will check if it also happens after `itemChangedEvent` and let you know if I can confirm this. Thanks for the suggestion.

> When the restURL is empty, is it empty throughout that session of outlook?

We run that code after the user performs some actions, so yes, it's not empty on the start (it might be though), but it's empty after some time user spends in the add-in.

I'll try to reproduce this and provide more details if I can. Thanks for your attention.

**Comment by exextoc** [comment]
@modestfake could you send us a repro of the issue you're facing?

**Comment by modestfake** [comment]
We've figured out that `restUrl` is an empty string `""` on items from shared folders. Not sure if there are more cases. It would be great to mention this in the documentation.

**Comment by exextoc** [comment]
For shared folders, you should use [SharedProperties](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-preview#getsharedpropertiesasync-options--callback-) to get the [targetRestUrl](https://docs.microsoft.com/en-us/javascript/api/outlook/office.sharedproperties?view=outlook-js-1.8#targetresturl).
