### ISSUE TITLE
OWA on Safari : Office.context.mailbox.displayNewAppointmentForm does not invoke

### ISSUE THREAD

**Issue by kanaksony** [OfficeDev/office-js#722]
Bug : OWA Schedule Meeting does not opens a new appointment form in Safari browser.

## Expected Behavior
Must open a new Appointment pre-populated with details filled  in #2.

## Current Behavior
It does not open the appointment window. No error is seen in console.

## Steps to Reproduce, or Live Example
1) Install Plugin, Fill information under Settings.
2) Click on Schedule Meeting from ConX Plugin
* Link to live example: https://mop.infocus.net:3000/infocus-conx-outlook-addin.xml

* Additional details:
```
function openScheduleMeeting(event, settings) {
  var meetingInviteText = populateMeetingInviteText(settings);
  var meetingInviteHTML = populateMeetingInviteHtml(settings);
  var SUBJECT = setSubjectLocale();

  var start = new Date();
  var end = new Date();
  end.setHours(start.getHours() + 1);
  console.log(start);
  console.log(end);
  console.log(SUBJECT);
  console.log(meetingInviteText);
  console.log(meetingInviteHTML);
  console.log(Office.context.mailbox.diagnostics.hostName);
  // If the Outlook is Outlook Web App
  if (Office.context.mailbox.diagnostics.hostName == "OutlookWebApp") {
    Office.context.mailbox.displayNewAppointmentForm(
      {
        start: start,
        end: end,
        location: settings.fullUrl,
        subject: SUBJECT,
        body: meetingInviteHTML,
        requiredAttendees: [emailId],
      });
  }
  else {
    Office.context.mailbox.displayNewAppointmentForm(
      {
        start: start,
        end: end,
        location: settings.fullUrl,
        subject: SUBJECT,
        body: meetingInviteText,
        requiredAttendees: [emailId],
      });
  }
  event.completed();
}

```
## Context
This is a blocker in context to get the addin published on store, because once your team verifies addin on Safari - will reject by saying its not functioning on safari.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: OWA
* Host [Excel, Word, PowerPoint, etc.]:Outlook
* Office version number: 16.22
* Operating System: MAC
* Browser (if using Office Online): Safari

## Useful logs
nothing

**Comment by AlexJerabek** [comment]
Thanks for reporting this @kanaksony. @JuaneloJuanelo, can you please investigate?

**Comment by exextoc** [comment]
Are you facing this issue when trying to launch the add-in from MessageReadCommandSurface or AppointmentComposeCommandSurface. Is the add-in working fine in other browsers and not working specifically in Safari or is it reproducable accross all the browsers.

**Comment by kanaksony** [comment]
Getting this issue when trying to launch it from MessageReadCommandSurface.
Yes - this is working fine in Google Chrome and Mozilla Firefox and not working specifically in Safari.

**Comment by exextoc** [comment]
I've tried to launch the add-in in Safari browser and was able to see the appointment window. Can you check if pop-up was disabled in your browser.

**Comment by kanaksony** [comment]
Okay, so after changing the popup window drop-down settings to "allow" it opens up the window but with error! Between - I have refreshed the browser window multiple times but no luck. But, Firefox and Chrome still working fine.

**I see an error in console.**

`
[Error] Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 't.id')
	(anonymous function) (compose:310:2555)
	u (compose:310:1417)
	(anonymous function) (owa.CalendarDeepBoot.js:53:40461)
	(anonymous function) (compose:315:6652)
	promiseMiddleware (owa.CalendarDeepBoot.js:37:257380)
	(anonymous function)
	stitch (owa.CalendarDeepBoot.js:53:40787)
	(anonymous function)
	bound 
	x (owa.CalendarDeepBoot.js:1:35591)
	S
	A
	dispatchWithMiddleware (compose:315:10407)
	(anonymous function)
	w (compose:345:2527)
	default (compose:330:7945)
	i (compose:315:6624)
	(anonymous function) (owa.CalendarDeepBoot.js:53:40471)
	promiseReactionJob
`

**Attaching the screenshots.**

![Screen Shot 2019-09-13 at 4 13 12 PM](https://user-images.githubusercontent.com/6097596/64857327-d964f000-d641-11e9-940e-6471aad3c3a2.png)

![Screen Shot 2019-09-13 at 4 17 45 PM](https://user-images.githubusercontent.com/6097596/64857407-103b0600-d642-11e9-9648-874141852a53.png)

**Comment by kanaksony** [comment]
@exectoc, can you please check if you are getting same issue?

**Comment by exextoc** [comment]
Hi @kanaksony we are currently investigating the scenario, will get back to you with our observations.

**Comment by exextoc** [comment]
@kanaksony we have made the fix from our end and the solution should be available in production within 2 weeks.
