### ISSUE TITLE
Cannot create content controls other than richtext content type

### ISSUE THREAD

**Issue by rina-andria** [OfficeDev/office-js#727]
hello, we won't to have the same functionalities as with VSTO Word add-in: add content control with the types dropdownlist, combobox, picture, checkbox and mostly datepicker.
can you please advise on how to do this? so far we only have the insertContentControl() method which inserts a Rich text one. Is there any parameter we can pass or any property we can specify to get  the other content control types?
Thank you!

**Comment by catchingyu** [comment]
Currently we only support the Rich Text. Other types are not supported now. Can you also share with us more context of this need in our UserVoice site, which is the center place tracking the feature request. And we would keep it on our radar for our future backlog planning, also, other developers can review and potentially comment or up vote on it.

**Comment by kbrandl** [comment]
@rina-andria here's the URL to the UserVoice site: https://officespdev.uservoice.com/. If you can please log this feature request there, the product team can consider it for the future. Thanks!

**Comment by rina-andria** [comment]
thanks for the updates. i ll add this feature request.
