### ISSUE TITLE
Excel Table Row Inserted Event Address Issue

### ISSUE THREAD

**Issue by david-ps** [OfficeDev/office-js#728]
In the Excel JS API the table event called "onChanged" fires whenever a change happens  and exposes the parameter "Excel.TableChangedEventArgs". 

This class has a property called "[address](https://docs.microsoft.com/en-au/javascript/api/excel/excel.tablechangedeventargs?view=excel-js-preview#address)" which should return the Range Address of the change that has occurred.  There is a use case when this address property does not return the correct range.

## Expected Behavior
Creating new rows below a table by dragging a cell value below the last row should create new rows and the OnChanged Event should return the range that has been added.

## Current Behavior
Drag a cell value below the last row in a table creates new rows but the OnChanged Event does not return the range of the new rows that have been added.

## Steps to Reproduce
1. Create and populate a table "A1:J8"
2. Select cell D8 
3. Drag the bottom right corner of D8 to copy contents down to D9, D10 and D11 
4. The onChanged Event occurrs with change type = "RowInserted" 
5. The address returned is A6:J8 (not the 3 new rows inserted > A9:J11)

## Context
By not returning the correct RowInserted range, dependent actions cannot be executed correctly and the application fails.

## Your Environment
* Platform: PC desktop
* Host : Excel Desktop
* Office version number: 1908 (Build 16.0.11929.20288)
* Operating System: Windows 10

## Images
![image](https://user-images.githubusercontent.com/47418828/64954784-f1e73b80-d8c9-11e9-9dad-f2fb4f233776.png)

![image](https://user-images.githubusercontent.com/47418828/64954891-2bb84200-d8ca-11e9-871c-4308bd8d237d.png)

**Comment by keyur32** [comment]
@lumine2008  - can you take a look please?

**Comment by catchingyu** [comment]
team is investing it now.

**Comment by david-ps** [comment]
FYI we also raised this API documentation/unexpected change [issue](https://github.com/OfficeDev/office-js-docs-pr/issues/1303)

**Comment by lumine2008** [comment]
I just check the issue, it was close, so i am going to close, please open a new issue, if you still meet this issue
> FYI we also raised this API documentation/unexpected change [issue](https://github.com/OfficeDev/office-js-docs-pr/issues/1303)
