### ISSUE TITLE
displayDialogAsync opens tab instead of pop-up

### ISSUE THREAD

**Issue by ayushsood** [OfficeDev/office-js#73]
I'm currently building an Excel v16.10 add-in on a Mac using office-js-helpers's authentication. Upon initiating the authentication request, a new tab on Chrome is created instead of pop-up. This prevents authentication from finishing.

Might be related to: https://github.com/firebase/firebase-js-sdk/issues/63

See the following sister-issue: https://github.com/OfficeDev/office-js-helpers/issues/66

## Expected Behavior
displayDialogAsync opens a pop-up

## Current Behavior
Upon initiating a displayDialogAsync, a new tab on Chrome is created instead of pop-up.

## Steps to Reproduce, or Live Example
```
Office.context.ui.displayDialogAsync("https://google.com/",
         { height: 50, width: 50, displayInIframe: true }, null);
```
I put that inside the app created via: https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/excel-quickstart-jquery?tabs=visual-studio-code ```yo office```

## Context
All of a sudden my add-in doesn't work - no user can log in. The login request doesn't redirect back to Excel. If this isn't fixed quickly, I will have to move off of the Excel platform.

## Your Environment
* Mac
* Excel
* Office version number: 16.10
* Chrome: 64

**Comment by sumurthy** [comment]
- Have you tried without the displayInFrame: true option? According to [this](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#take-advantage-of-a-performance-option-in-office-online) page, "You should not use displayInIframe: true if the dialog will at any point redirect to a page that cannot be opened in an iframe. For example, the sign in pages of many popular web services, such as Google and Microsoft Account, cannot be opened in an iframe."

- Have you tried sample add-ins that uses auth as described in the same page? example: `https://github.com/OfficeDev/PowerPoint-Add-in-Microsoft-Graph-ASPNET-InsertChart`

**Comment by Rick-Kirkham** [comment]
Also, please note the following from the same article that @sumurthy linked to: 
"The domain is the same as the domain of the host page, which can be the page in a task pane or the function file of an add-in command. This is required: the page, controller method, or other resource that is passed to the displayDialogAsync method must be in the same domain as the host page."

**Comment by ayushsood** [comment]
@sumurthy and @Rick-Kirkham thank you for the quick response. Just went through your suggested steps - the Auth0 example worked on my computer.

I think the issue might have to do with the domain issue that Rick mentioned - I have my Excel addin files being served from excel.myapp.com and the OAuth service running on myapp.com. Would that be an issue? This setup was working fine a couple months ago - was there a recent breaking change?

**Comment by Rick-Kirkham** [comment]
@ayushsood 
I don't believe there's  been a breaking change with `displayDialogAsync`, but I think there are (or were) some situations in which you can get away with passing a domain to it that is not the same as the parent page. But this does not work reliably across all hosts/platforms, so our policy is to require that the URL passed to `displayDialogAsync` be on the same domain as the parent page. This isn't really much of a handicap because you can have a UI-less page hosted in the same domain as the host page that has script which immediately redirects to any https URL you want. Please try this.

**Comment by ayushsood** [comment]
@Rick-Kirkham does that mean that authentication [here](https://github.com/OfficeDev/office-js-helpers/blob/a4e46bf3bc5e79b58da51c8d20749170a4d2d1d1/src/authentication/endpoint.manager.ts) would fail?

It triggers external URLs for Dropbox/FB/Google authentication. Trying to change my URL - will report back on if it fixes my issue. Thanks!

**Comment by ayushsood** [comment]
@Rick-Kirkham that seemed to have done the trick. Going to let you close the issue in case office-js-helpers needs to be updated based on my previous comment.

Also it would be great if the documentation stated explicitly that subdomains area considered *not* to be part of a domain for the purposes of `displayDialogAsync`

Thank you for the quick responses - I owe you a drink next time I'm Seattle (assuming that's where you guys' are based out of).

**Comment by jrop** [comment]
I am getting the same error/behavior when serving the add-in from localhost on Mac.  Is there special handling for the localhost domain?

I even tried tricking it by setting /etc/hosts to point a domain at 127.0.0.1.  If I use ngrok, then everything works as expected.  Is it handling non-standard ports by opening the URL with the default browser?
