### ISSUE TITLE
context.sync() afterparagraph.search method on string longer than 255 chars fails silently on word desktop

### ISSUE THREAD

**Issue by JensMadsen** [OfficeDev/office-js#731]
i found #168. same goes for paragraphs

Works on web version but not on windows dekstop. 

Before fixing the issue you could at least throw an error (i wasted a lot of time on this)

**Comment by keyur32** [comment]
@JensMadsen  - sorry for the issue. It is on the backlog but we can make it more visible.

@kbrandl , @davidchesnut  - can we transfer to teh docs repo and add a note for this issue?

**Comment by JuaneloJuanelo** [comment]
@JensMadsen  this is a known issue on Word Programmability. (same issue happens in VBA etc.)
fortunately, there is a workaround described by Cindy Meister here: https://stackoverflow.com/questions/50911606/body-search-issue-in-word-desktop/51159442#51159442

btw this is already documented here: https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#search-searchtext--searchoptions-

**Comment by JensMadsen** [comment]
@JuaneloJuanelo thank you for pointing me to the workaround :-) 

I simply suggest that instead of failing silently when the search string is longer than 255 please throw an error whenever the search string is longer than 255 chars. Could be two lines of code which would save others a lot of time.

**Comment by JuaneloJuanelo** [comment]
@JensMadsen thanks for the suggestion. We are tracking internally with 3649518.
