### ISSUE TITLE
Query regarding accessing local resources from Office JS

### ISSUE THREAD

**Issue by topkoong** [OfficeDev/office-js#732]
Hi there!

I'm trying to access local resources via Excel JavaScript API, Excel task pane add-in or Excel custom function. Would it be possible to do so? I know that Office add-ins are web applications that are displayed using iFrames, and they are using embedded browser controls in Office for desktop and mobile clients.

Could we, developers, change embedded browser controls in Office for desktop?

I was wondering if you guys could let me know about this.

Thank you for your time!

**Comment by JuaneloJuanelo** [comment]
@topkoong  hello!  No you cannot change the embedded browser control.

Can you be more specific on what local resources you are referring to or want access to? in general the answer to this will no. (for security and other reasons like  is there a multiplatform equivalent?  this is supposed to be a platform neutral technology)

**Comment by topkoong** [comment]
@JuaneloJuanelo I would like to get data from a text file on my local machine or any location in which Excel task pane add-in or Excel custom function could access. Would it be possible to do so?

**Comment by JuaneloJuanelo** [comment]
@topkoong  thanks for the clarification. In web programming you cannot open the file directly for security you need to ask the user what file to process. In other words, the user needs to pick the file.  You can enable that by using the file input type in your html, something like: 


```
	<form>
		Select a text file  To be inserted <input type="file" id="FileToInsert"> 
	</form>
```

And then you need a handler to process the file the user selected. 

something like: 

```
$("#FileToInsert").change(insertContent);  // event handler subscription

// the insertContent method  gets the file and then up to you how to process it....

function insertContent() {
  var myFile = document.getElementById("FileToInsert");
  var reader = new FileReader();
  var time1 = null;

  reader.onload = (function(theFile) {
    return function(e) {
      Excel.run(function(context) {
        var text = e.target.result;  // to get the file content you will get a string in result.
      
        return context.sync();
      });
  
    };
  })(myFile.files[0]);

  // Read in the image file as a data URL.
  reader.readAsDataURL(myFile.files[0]);
}


```

I hope this sets you up in the right direction.
