### ISSUE TITLE
Unhandled Rejection: worksheets.addFromBase64 is not a function

### ISSUE THREAD

**Issue by collinstowell** [OfficeDev/office-js#735]
So with the release of 1.1.32, it was expected that the beta functionality allowing worksheets.addFromBase64 would start working on the regular (non-beta) distribution of OfficeJS. However, I seem to still get this issue with the production CDN build of OfficeJS even though 1.1.32 has officially been released and tagged with the latest tag.

## Expected Behavior
I expected the functionality to become active on the non-beta build of OfficeJS.

Any idea why this isn't supported on the official https://appsforoffice.microsoft.com/lib/1/hosted/office.js build yet?

**Comment by catchingyu** [comment]
what do you mean by the release of 1.1.32, is it some release version of your add-In? The WorksheetCollection.addFromBase64  API is still in the Beta Preview State , so the production do not have this API now.

**Comment by collinstowell** [comment]
I appreciate the quick response. I had figured when the 1.1.32-beta (from NPM) version moved to @latest / 1.1.32 that the feature would have been promoted to production. Any idea when this feature is expected to be available on production?

**Comment by lumine2008** [comment]
Hi, @collinstowell , Do you expect to use this API in excel online?

**Comment by lumine2008** [comment]
we have just release preview version insertWorksheetFromBase64 for Excel Online, would you please try it? https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/excel-preview-apis?view=excel-js-preview
