### ISSUE TITLE
Contextual Add-In closing by itself if there is an advertisement

### ISSUE THREAD

**Issue by kakusharma** [OfficeDev/office-js#736]
When I am trying to open the contextual Add-In, it is getting closed as sson as it opens when there is a advertisement on the right panel. What's happening is whenever I click the text to open the contextual add-in, the advertisement frame refreshes and then the add-in window also closes. Its opening fine when there is no advertisement though

## Expected Behavior

The Add-In window should not close, even if there is some advertisement panel showing up.

## Current Behavior

Contextual Add-In window is closing when there is advertisement frame showing on the right panel

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: Windows
* Browser (if using Office Online): Chrome/Edge

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
We are not able to reproduce this issue. Can you please send us a video of when this is happening and console logs from browser DevTools if possible?

**Comment by kakusharma** [comment]
Seems like its not happening anymore. Last time I tried on my account, the Add-In window was getting closed as soon as it was opening up.
