### ISSUE TITLE
[Excel] Can use offline office.js?

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#739]
i use online office.js.

https://appsforoffice.microsoft.com/lib/1/hosted/office.js 

but some time can not connect ,the error 

The connection to 'appsforoffice.microsoft.com' failed. <br />Error: TimedOut (0x274c). <br />System.Net.Sockets.SocketException 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 23.65.187.233:443   

i found the IP   23.65.187.233   is Japan , The network in china   can't connect. so it's any offline office.js.

thanks

**Comment by lumine2008** [comment]
Thanks @dinglicoding, I am sorry, we currently don't support offline access, because our add-in is a web add-in, the code is not in local machine, so we need network to access. How often does this connection failure in your side?

**Comment by dinglicoding** [comment]
Thanks @lumine2008  sametime connection failure in my side, but offen slowly , the  appsforoffice.microsoft.com for cdn has china?

**Comment by sumurthy** [comment]
We do have edge server coverage across globe - but coverage in China may be lacking. One other option is to use the [offline copy](https://www.npmjs.com/package/@microsoft/office-js) and keep up with the versions. We'll follow-up on the CDN coverage as well.
