### ISSUE TITLE
Cannot add named item that refers to "=MyTable[[#Headers],[MyColumn]]"

### ISSUE THREAD

**Issue by harri-rajala-koivu-solutions** [OfficeDev/office-js#740]
You cannot add named item that refersh to "=MyTable[[#Headers],[MyColumn]]".

Code example:
```typescript
namedItemCollection.add("MyNamedItem", "=MyTable[[#Headers],[MyColumn]]");
await context.sync();
const namedItem = namedItemCollection.getItem("MyNamedItem").load("formula");
await context.sync();
console.log(namedItem.formula);
```

## Expected Behavior
Previous code example should print **"=MyTable[[#Headers],[MyColumn]]"**.

## Current Behavior
For some reason it prints **"=Sheet1!$A$1"**.

If you change previous example to use **"addFormulaLocal"** method (instead of "add") then it returns correct value. But the problem with "addFormulaLocal" method is that it requires that word "#Headers" is localized. Meaning that if Excel display language is English then "#Headers" is correct word but if Excel display language is Finnish then your code must use "#Ylätunnisteet" and so on. 

It doesn't make sense to write localized code.

## Steps to Reproduce, or Live Example
Here is full example:

```typescript
await Excel.run(async (context: Excel.RequestContext) => {
const sheet = context.workbook.worksheets.getActiveWorksheet();

const tableName = "MyTable";
// Delete existing test table and named items
let table = sheet.tables.getItemOrNullObject(tableName);
const namedItemCollection = sheet.names.load("items");
await context.sync();
if (table && !table.isNullObject) {
    table.delete();
}
for (const namedItem of namedItemCollection.items) {
    namedItem.delete();
}
sheet.getRange("E1:H1").clear();
sheet.getRange("E2:H2").clear();

// Create test table
table = sheet.tables.add("A1:C1", true);
table.name = tableName;
table.getHeaderRowRange().values = [["MyColumn1", "MyColumn2", "MyColumn3"]];
table.rows.add(undefined, [
    ["a1", "b1", "c1"],
    ["a2", "b2", "c2"],
    ["a3", "b3", "c3"]
]);
await context.sync();

const listSeparator = ",";
const columnLabel1 = "MyColumn1";
const columnLabel2 = "MyColumn2";

// We want to add named item that refers to table column header.
// You can do that manually:
// 1. Select column header for example MyColumn3 (C1).
// 2. Formulas => Define Name
// 3. Refers to is "=MyTable[[#Headers],[MyColumn3]]"

// There are two methods "add" and "addFormulaLocal" in NamedItemCollection.
// Both methods requires that "Headers" is localized and also separator 
// should be ";" or "," depending on you settings.
// If you use wrong "Headers" word then Excel throws exception.
// This means that if Excel language is English then headers should be "Headers" 
// but if language is Finnish then headers should be "Ylätunnisteet" and so on.
// So you need to do something like this:
let headers;
if (Office.context.displayLanguage === "fi-FI") {
    headers = "Ylätunnisteet";
} else {
    headers = "Headers";
}

// Add named item using "add" method.
// This does not work in any Excel language. It does not give any errors
// but later when you ask formula you can see that value is wrong.
// It should be:
// "MyTable[[#Headers],[MyColumn1]]"
// But it is:
// "Sheet1!$A$1"
namedItemCollection.add("HeaderUsing_add", 
      "=" + tableName + "[[#" + headers + "]" + listSeparator + "[" + columnLabel1 + "]]");

// Add named item using "addFormulaLocal" method.
// This method works but the problem is that we need to use localized "Headers".
namedItemCollection.addFormulaLocal("HeaderUsing_addFormulaLocal", 
      "=" + tableName + "[[#" + headers + "]" + listSeparator + "[" + columnLabel2 + "]]");

// How can we add named item which refers to "=MyTable[[#Headers],[MyColumn3]]" 
// without checking Excel language?
// I think that "add" method should be changed to accept 
// "English" word "Headers" and fixed list separator for example ",".

await context.sync();

const namedItem1 = namedItemCollection.getItemOrNullObject("HeaderUsing_add").
      load("formula,value");
const namedItem2 = namedItemCollection.getItemOrNullObject("HeaderUsing_addFormulaLocal").
      load("formula,value");
await context.sync();

sheet.getRange("E1:H1").values = [["'" + namedItem1.formula, namedItem1.value,
      "Should be:", "MyTable[[#Headers],[MyColumn1]]"]];
sheet.getRange("E2:H2").values = [["'" + namedItem2.formula, namedItem2.value,
      "Should be:", "MyTable[[#Headers],[MyColumn2]]"]];


sheet.getRange("A1:H4").format.autofitColumns();
}
```

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 1908 (Build 11929.20300 Click-to-Run)
* Operating System: Windows 10 Home version 1903 (OS Build 18362.356)
* Browser (if using Office Online): ______

**Comment by kbrandl** [comment]
@lumine2008 can you please assist with this issue, or assign to someone else on your team?

**Comment by harri-rajala-koivu-solutions** [comment]
@kbrandl @lumine2008 Do you have any updates on this issue?

**Comment by lumine2008** [comment]
Hi @harri-rajala-koivu-solutions , Thanks for your post, 
we have created Bug3674409 for tracking this issue, team is working on it.

**Comment by harri-rajala-koivu-solutions** [comment]
@lumine2008 Thanks.
Any estimate when that will be fixed?

**Comment by lumine2008** [comment]
@harri-rajala-koivu-solutions, we are evaluating this fix, as if we fix, this would be a breaking change, because some users has already wrote the code to get the "=Sheet1!$A$1" if we change, it may break their add-in. so may i know your scenario? i would like to know the scenario for returnning "=MyTable[[#Headers],[MyColumn]]".

**Comment by harri-rajala-koivu-solutions** [comment]
@lumine2008 
**Actually you have already made one breaking change related to this method!!!!**

Originally our Excel Add-in used NamedItemCollection.**add** method to add "=MyTable[[#Headers],[MyColumn]]". And it worked fine. It returned "=MyTable[[#Headers],[MyColumn]]".

But then in 05/2019 we noticed that our add-in does not work anymore with Excel version 1904. And the reason was this NamedItemCollection.add method. With version 1904 it started to return "=Sheet1!$A$1".

So please check version 1903 and you will notice that it returned "=MyTable[[#Headers],[MyColumn]]". And then starting from 1904 it returns "=Sheet1!$A$1". That was breaking change!!!

So in 05/2019 we changed our code to use **addFormulaLocal** because it was only way to get our add-in to work. But that should only be temporary workaround until you fix **add** method to work as it should work.

**Why do we need this?**

In our Excel add-in solution Named Items are used to define what kind of data should be put to Excel sheets.

If Named Item refers to single cell "=Sheet1!$A$1" then we know that user wants put single value (or first value) to that one cell.

If Named Item refers to table header "=MyTable[[#Headers],[MyColumn]]" then we know that user wants put multi values to that table column. Each multi value is in its own row in the column.

Note that it can be either end user or add-in code that adds these Named Items. And we need consistent way to add and find out whether the Named Item refers to single cell or table header.

**Comment by harri-rajala-koivu-solutions** [comment]
@lumine2008 Any update on this issue?

**Comment by harri-rajala-koivu-solutions** [comment]
Any update?

**Comment by lumine2008** [comment]
This issue was fixed, would you please validate? thanks

**Comment by harri-rajala-koivu-solutions** [comment]
@lumine2008 What is the first Excel version that fixes this issue?

**Comment by lumine2008** [comment]
this issue was checked in Dec 2019, so SAC should have this fix. please re-open it if you still observe the issue. thanks
