### ISSUE TITLE
Inconsistent behavior when the website redirects during ribbon command execution

### ISSUE THREAD

**Issue by slowkoala** [OfficeDev/office-js#741]
When executing a ribbon command, we want to redirect our website to a different url if we know the user is authenticated.  When we do this, we're seeing inconsistent results with different setups.

Testing with PC Excel, you need to call `event.completed()` before you redirect.  After you redirect, your command isn't called automatically, so you need to communicate the command you need to execute to the new url, and then run it manually there.

Testing with Excel Online, if you redirect right away, the event will be executed for you again on the new website.

Testing with the shared runtime with Excel Online and PC Excel, I'm seeing behavior similar to regular PC Excel where you need to manually execute the function yourself after redirecting.

What is the expected behavior here?  It would be nice for the event to be triggered again after the redirect if we didn't call `event.completed()` before the redirect.

**Comment by lumine2008** [comment]
Thanks @slowkoala for your post, could you please us more information on this issue? 
it would be awesome,that you could share us your gist, therefore we could better understand this issue. 

Thanks a lot for the support.

Description :

Expected Behavior

Current Behavior

Steps to Reproduce, or Live Example

Context

Your Environment
Platform [PC desktop, Mac, iOS, Office Online]:
Host [Excel, Word, PowerPoint, etc.]:
Office version number:
Operating System:
Browser (if using Office Online):

**Comment by slowkoala** [comment]
@lumine2008 I created a gist and filled out the information below:

Description : Redirecting the website while executing a command is inconsistent between Excel Online and PC Excel.

Expected Behavior : If you don't mark the event as complete, PC Excel should call the event again on the redirected website.

Current Behavior : If you don't mark the event as complete, PC Excel doesn't do anything after the redirect.  It will also show an error dialog if you try to run another command, since it never thinks the first one completed.

Steps to Reproduce, or Live Example
Here's a reproducer gist: https://gist.github.com/slowkoala/f85ae4c9252b0ec24acf79943bff307f
Install the dependencies, and then run `node serve.js` and sideload PC Excel or Excel Online

Context

Your Environment
Platform: PC and Online
Host: Excel
Office version number: 16.0.12119.20000
Operating System: Windows 7
Browser (if using Office Online): Chrome 77

**Comment by lumine2008** [comment]
Hi slowkoala , please let us know if you still repro this issue. thanks

**Comment by lumine2008** [comment]
I'm going to close this issue for now, please reactivate if you're still seeing this. IThanks!
