### ISSUE TITLE
Problems on inserting SVG images on Excel

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-js#744]
## Expected Behavior
Inserting an SVG image should work always.

## Current Behavior
Inserting an SVG image works sometimes, depending on the SVG content.
The error code is: 5001, internal error.

## Steps to Reproduce, or Live Example
* Link to live example: [Gist Example](https://gist.github.com/barisbikmaz/c99ec337d470439e348ea9fd526fd73a)

When you try to insert the svg in this gist repo you'll face an internal error.
If you remove the last "path" tag of the svg the insertion works.

## Context
We have an addin from which our users can insert SVG images into Excel. Now we have complains about that SVG insertion does not work properly. 

## Tested Environment

The insertion works on these environments:
- Excel Semi-annual Channel - 1902 (Build 11328.20420 Click-to-Run)
- ios Excel latest

The insertion does *NOT* work on these environments:
- Excel O365 ProPlus latest
- Excel macOS

## Your Environment

* Platform : PC & Mac
* Host: Excel
* Office version number: 1909
* Operating System: Windows & Mac

**Comment by lumine2008** [comment]
Thanks @barisbikmaz , i can repro this issue with your gist, i have created a bug (3674387) to track this issue. team is investigating on this issue. thanks

**Comment by lumine2008** [comment]
This issue was fixed, would you please verify it?

**Comment by barisbikmaz** [comment]
Yeah looks good.
