### ISSUE TITLE
getFileAsync return file not correct when not closeAsync on Word online.

### ISSUE THREAD

**Issue by hungvnguyen-kms** [OfficeDev/office-js#750]
When I getFileAsync, then close the taskpane before executing function file.closeAsync(), then open the taskpane and getFileAsync again, the file slice becomes different and cannot be opened when I download it.

To be specific, I'm writing a function to upload the document to server. Firstly, I getFileAsync, and getSliceAsync then hash it, it returns thing like *hashcode1*. When all the slices are uploaded to server. I can open the docx file normally. The closeAsync function is called after that. However, if user closes the taskpane before this progress is finished, and then reopens the taskpane to getFileAsync again, the file still has the same size and slice count, but when I getSliceAsync and hash, the result now is *hashcode2*. (Notice that the file is not changed at all, and if I reload the browser, the hash result will be back to *hashcode1*), this leads that the downloaded docx file now cannot be opened.

So it turns out that if the file is not closed async, the getFileAsync or getSliceAsync will have different behavior from origin until you reload the webpage.

## Expected Behavior
When getFileAsync for the second time, it should return error or it should getSliceAsync correctly

## Current Behavior
It getFileAsync success but getSliceAsync return wrong value.

## Your Environment
* Platform: Office Online
* Host: Word
* Office version number: Office365 via office.com
* Operating System: Windows 10
* Browser (if using Office Online): Chrome

**Comment by JuaneloJuanelo** [comment]
The API is not designed to work across different sessions. Also the hash is expected to be different since the getFileAsync first creates a copy of the file, which is the one who get paginated, so the slices can be different. 
You will need to start paging the file again on the new session and always call closeAsync otherwise you will get an exception, we do not allow more than 2 copies of the file open at the same time. 

hope this helps.

**Comment by hungvnguyen-kms** [comment]
I understand that we need to closeAsync the file. But if user closes the taskpane immediately, how can I handle it? I have tried to put the function in componentWillUnmount (I'm using React) or subcribe event 'beforeunmount' of window, the function doesn't run.

**Comment by hungvnguyen-kms** [comment]
@JuaneloJuanelo Can you share me a solution to closeAsync the file for this case? (when user closes the taskpane while the code is processing the file)
