### ISSUE TITLE
Wanted to enable right-click menu on sideload addin

### ISSUE THREAD

**Issue by hilarudeens** [OfficeDev/office-js#751]
Im developing outlook office addin,
I need to allow user to right click and choose past option from context menu.
Everything was working till, I update windows10 and outlook.
Now it is not working.
Please any help would be appreciated

It is not working only in outlook desktop client, which is using edge webview

<img width="172" alt="right-click-menu" src="https://user-images.githubusercontent.com/1651646/65983953-4f6bb280-e49c-11e9-930c-d31d239eb35a.png">

**Comment by hilarudeens** [comment]
Thanks @kbrandl

**Comment by peronald** [comment]
Can you elaborate on what the intended behavior is as well as explain more in detail what the issue is (which APIs you are using and what is failing, etc)? Can you submit a screenshot of the intended behavior as well?

**Comment by hilarudeens** [comment]
@peronald 
It is about outlook addin.

My addin have few forms which is having fields like text, textarea, radio button and so on.

As a user, i wanted to fill the form. I wanted to copy the text and paste in textarea by right click and chose paste option.

I'm not using anything crazy. Simple HTML form with text area as follows,
```
<!doctype html>
<html>
    <head>
        <meta http-equiv="Access-Control-Allow-Origin" content="*">
        <header name = "Access-Control-Allow-Origin" value = "*" />
        <title>Outlook Addi</title>
    </head>
    <body>
        <form>
            <textarea rows="10" cols="50"></textarea>
        </form>
        <script src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js" type="text/javascript"></script>
    </body>
</html>
```
and i enabled addin by pickig xml file from my local machine. 

This was working fine till upgrade outlook-desktop-client and windows 10. later it stops working.
I can see after upgrade outlook-desktop-client using Edge browser instance, earlier it was ie11 browser instance.

**Comment by exextoc** [comment]
This is a known issue with the Edge WebView and we are working with the Edge team to address it. In the meantime, you can use JavaScript to create custom menus for your add-in, as a workaround.
