### ISSUE TITLE
Importing large image (> 5MB) fails on PowerPoint Online

### ISSUE THREAD

**Issue by hxltinh** [OfficeDev/office-js#752]
## Expected Behavior

- it should import large images (> 5MB) successfully
## Current Behavior
- importing large images will throw error: `The specified data object is too large.`

## Steps to Reproduce, or Live Example

* Link to gist example: https://gist.github.com/hxltinh/e508ba1d096983c4e14c61672a8aec79
### steps:
1. Select more than 5MB image from file input
2. Click `Insert image from input file` button
3. Observe the logs to see the error

* Additional details:
  1. happens only on PowerPoint Online

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: PowerPoint
* Browser (if using Office Online): Chrome

## Useful logs

- [x] Console errors

**Comment by weshi** [comment]
There is a size limit in Online. This is by design behavior.
