### ISSUE TITLE
[Outlook] Attendee is not removed after calling Office.context.mailbox.item.saveAsync()

### ISSUE THREAD

**Issue by sergez** [OfficeDev/office-js#753]
## Expected Behavior
The attendee should be removed or "discard/not discard changes" dialog should be shown.

## Current Behavior
Attendee is not removed

## Steps to Reproduce
1/ Open existing meeting/appointment and open web Add-In panel. I use the following sample:

import * as React from 'react';
import * as ReactDOM from 'react-dom';
ReactDOM.render(
    <button onClick={() => Office.context.mailbox.item.saveAsync()}>SAVE ASYNC</button>,
    document.getElementById('app'),
);

2/ Add attendee by using 'People' dropdown on a meeting form;
3/ Call `Office.context.mailbox.item.saveAsync()`. In my case I call `Office.context.mailbox.item.saveAsync()` by clicking on the button;
4/ Remove just added attendee from the list;
5/ Close the meeting and open it again;

## Your Environment
* Platform: Office Online
* Host: Outlook Calendar
* Office version number: 2016
* Operating System: Windows Server 2012 R2,  Windows 10, Exchange 2016 (15.1.1779.2)
* Browser: Any

The interesting thing is that this issue reproduced only if I manipulate Attendees. It works as expected when change body, title, etc... And after changed body/title/... "discard/not discard dialog" is shown.

**Comment by exextoc** [comment]
We are not able to repro this. Can you share repro video?

**Comment by sergez** [comment]
![OfficeWebAddIn-Context-saveAsync-Attendees](https://user-images.githubusercontent.com/164393/66554205-38d8f180-eb55-11e9-8a3f-e1c6799e9846.gif)

**Comment by exextoc** [comment]
We are able to repro the issue. Thank you for reporting this issue and sharing clear repro step. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by sergez** [comment]
Hi,
I'm wondering is the issue fixed?

**Comment by exextoc** [comment]
Hey @sergez,
We have rolled out the new version of Outlook for Web across all Exchange Online mailboxes. In the new experience, this scenario should not exist. Are you still able to reproduce this issue?
