### ISSUE TITLE
makeEWSRequestAsync does not work on outlook on mac

### ISSUE THREAD

**Issue by chopraniitn** [OfficeDev/office-js#754]
## Expected Behavior
makeEWSRequestAsync should return valid data when its been called and all the required data is provided to the method. like item id with a valid soap request.

## Current Behavior
I am trying a outlook 365 addin where we call makeEWSRequestASync() Method to do some operations. but it seems like its not working and returns an error, even if i pass the valid item id  

## Steps to Reproduce, or Live Example
var mailbox = office.context.mailbox;
`mailbox.makeEwsRequestAsync(getItemRequest(id), function(asyncResult) {
			var parser = new X2JS();
			var json = parser.xml_str2json(asyncResult.value);
			getItemJson = json.Envelope.Body.GetItemResponse.ResponseMessages;
			logMessage("getItem request - call number " + asyncCount);
			//
			if (getItemJson.GetItemResponseMessage._ResponseClass !== "Error") {
				logMessage("getItem request success");
				changeKey = getItemJson.GetItemResponseMessage.Items.CalendarItem.ItemId._ChangeKey;
				logMessage("getItem request ChangeKey: " + changeKey, true);
				checkRecurrencePattern(getItemJson.GetItemResponseMessage.Items.CalendarItem);
			} else {
				logMessage("getItem request error");
				asyncCount++;
				setTimeout(function() {
					callGetItem(id);
				}, 5000);
			}
		});`

`var getItemRequest = function(id) {
		var request =
			'<?xml version="1.0" encoding="utf-8"?>' +
			'<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"' +
			'               xmlns:xsd="http://www.w3.org/2001/XMLSchema"' +
			'               xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"' +
			'               xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">' +
			'  <soap:Header>' +
			'    <RequestServerVersion Version="Exchange2016" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" soap:mustUnderstand="0" />' +
			'  </soap:Header>' +
			'  <soap:Body>' +
			'    <GetItem xmlns="http://schemas.microsoft.com/exchange/services/2006/messages">' +
			'      <ItemShape>' +
			'        <t:BaseShape>IdOnly</t:BaseShape>' +
			'        <t:AdditionalProperties>' +
			'            <t:FieldURI FieldURI="item:Subject"/>' +
			'            <t:FieldURI FieldURI="item:Body"/>' +
			'            <t:FieldURI FieldURI="calendar:IsRecurring"/>' +
			'            <t:FieldURI FieldURI="calendar:Recurrence"/>' +
			'            <t:FieldURI FieldURI="calendar:FirstOccurrence"/>' +
			'            <t:FieldURI FieldURI="calendar:LastOccurrence"/>' +
			'        </t:AdditionalProperties>' +
			'      </ItemShape>' +
			'      <ItemIds><t:ItemId Id="' + id + '"/></ItemIds>' +
			'    </GetItem>' +
			'  </soap:Body>' +
			'</soap:Envelope>';
		return request;
	};`

## Your Environment

* Platform **MAC**
* Host **outlook**

## Other detail
it works fine on outlook web and other outlook client on windows operating system. To be noted i am just trying this in user calendar not in delegate

**Comment by Shepherd-rocks** [comment]
Hi @chopraniitn which Mac Outlook Build version are you using? I think it should have been fixed with 16.24. Related conversation is [here](https://github.com/OfficeDev/office-js/issues/433)

**Comment by chopraniitn** [comment]
HI, we are using 16.29. i went through the link. but i could not locate the cache folder for outlook as mentioned in the discussion.
Not sure where to look into. i tried removing and re-add my account. but same result.

**Comment by macOutlookExtensibility** [comment]
Hey @chopraniitn,

Could you please share a formatted version of your code? The "//" is making it hard to debug what exactly is commented out in your code. We are curious to know how you are getting the item ID. Also could you share us the details of the error that you're getting? It should be a part of the asyncResult.error object in your callback.

**Comment by chopraniitn** [comment]
HI,

I am getting ID format error. here is xml i get back.

`<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="15" MinorVersion="20" MajorBuildNumber="2305" MinorBuildNumber="24" Version="V2018_01_08" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/></s:Header><s:Body><m:GetItemResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:GetItemResponseMessage ResponseClass="Error"><m:MessageText>Id is malformed.</m:MessageText><m:ResponseCode>ErrorInvalidIdMalformed</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:Items/></m:GetItemResponseMessage></m:ResponseMessages></m:GetItemResponse></s:Body></s:Envelope>`

i am not sure if outlook on mac is expecting a different format of id here. but it works everwhere else. so not sure what i am missing here


i have attcahed full script,as i am not sure what i am missing to format the code . i used insert code function, but it still display like that . 

Please note, i am doing this operation on already existing appointment which will have itemID set anyway.

As far as i know saveAsync does not work for new appointment created on outllok on mac , so basically you do not get itemID. Thats why i created item first and then  reopen it and then load my addin which is calling used saveASync to get item id.


Thanks
[script.zip](https://github.com/OfficeDev/office-js/files/3688067/script.zip)

**Comment by macOutlookExtensibility** [comment]
Hey @chopraniitn, Can you with share me the format of the Item ID being used in your request? It would be great if you could share the item ID itself. This will help us look into this further.

**Comment by chopraniitn** [comment]
HI, 
Here is the example if id i am passing . AQMkAGMwMAFhM2E2LWFiMGUtNDhkNC1iNWE0LTE4MzgwMWU2MzFlNwBGAAAD0tjtDdOkAkC_T7FP3oOb2gcA4QdUjomZfkS5W8iS_P3T8wAAAgENAAAA4QdUjomZfkS5W8iS_P3T8wABDDaZwgAAAA==

but as i said earlier this id we are getting from after calling  saveAync().

Thanks

**Comment by exextoc** [comment]
Thank you for reporting this bug. We have added this to our backlog. Unfortunately we cannot share timeline at this point. As a workaround you can replace _ with + and - with / in itemId which you are getting. That should work.

Internal tracking id:3698327

**Comment by chopraniitn** [comment]
Is there any way i can get notification whenever you will fix the bug? or it will be updated here in this ticket?

**Comment by rjpruitt16** [comment]
@chopraniitn do you find a workaround. It seems like no one is fixed this.

**Comment by exextoc** [comment]
Hi, this issue has been fixed. You should see the fix on the latest builds.
