### ISSUE TITLE
While deleting content control (with text) from table cell in Word document, error occurs: "A table in this document has become corrupted"

### ISSUE THREAD

**Issue by Kashishmsft** [OfficeDev/office-js#755]
## Title

Developing an Office JS Word add-in and trying to add and delete the content controls (and text in it) in the table inserted in Word document in enviroment Office 2016 MSI only, error is produced: "A table in this document has become corrupted".

## Expected Behavior

Error as above is not expected, it should delete the content control and text in Word 2016 MSI without issue.

## Current Behavior

While executing the below code in client machine having Office 365 (monthly channel and latest build) however, in Office 2016 MSI when the same code is executed creates an error (Error Source: Microsoft Word) 
when trying to delete the content control in the table. 
I am able to repro the issue in-house independent of any custom/moving parts.

## Steps to Reproduce, or Live Example

 1. Add one table in new Word document (one cell is enough) in environment having Word 2016 MSI version.
 2. Place the cursor in the inserted table and click on the button "insertcontentcontrol" in Word scriptlab add-in having imported gist (link provided above) from github.
 3. Now, click on the button "deletecontentcontrol" in the same snippet in Word scriptLab Add-in.
 4. Now, after deletion of the content control and text in it, you would observe that the Error "A table in this document has become corrupted".

Refernce: https://docs.microsoft.com/en-us/javascript/api/word/word.contentcontrol?view=word-js-preview#delete-keepcontent-

Import the code in the script lab and test from - https://gist.github.com/Kashishmsft/d10fd78b9a831551bb8d3d387e4e31a6

* Additional details:

 1. Once issue is reproduced, it would not be reproduced again until we re-start Word Application and follow the above repro steps again.

## Context

Because of this issue it disables us to delete the content control in the inserted table in cell programtically.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]:  PC Desktop 
* Host [Excel, Word, PowerPoint, etc.]: Word client application
* Office version number: 16.0.4849.1000
* Operating System: Windows 10
* Browser (if using Office Online): NA

## Useful logs

- [ ] Console errors - NA
- [ ] Screenshots - Attached the screenshot of the error.
- [ ] Test file (if only happens on a particular file) - NA
![Error](https://user-images.githubusercontent.com/35471218/66100653-62c86c00-e5c9-11e9-8631-f777a3de4703.png)

**Comment by weshi** [comment]
@shaofengzhu @kbrandl  This is for Word Rich API for desktop clients. Please reassign it.

**Comment by yihuax-zz** [comment]
This bug has been fixed and ported to O16 a month ago. the C2R branch has no such issue.

**Comment by yihuax-zz** [comment]
It's Bug:3714707.
