### ISSUE TITLE
addFromPromptAsync does not work on excel online in chrome

### ISSUE THREAD

**Issue by shyambhiogade** [OfficeDev/office-js#756]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
Thank you for your understanding and continued feedback.

I am using following api to select the range from excel online in chrome, but it does not allow me to select background range, it works as expected in desktop excel, I have not tested it in Internet explore. its only showing model dialog with previous selected range as its value.
 
addFromPromptAsync 

## Expected Behavior
it should allow me to select the background range, 

## Steps to Reproduce, or Live Example
Open office addin which uses addFromPromptAsync  function to in excel chrome, and exercise the scenario to select range, it doesnt work

## Your Environment
Excel online in chrome on windows 10 machine, I am using my corporate excel application. 

## Useful logs
There are no console error, please find the gif file
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10468130/66170349-c7e78600-e5f8-11e9-919c-921d7b5337df.gif)

**Comment by shyambhiogade** [comment]
https://stackoverflow.com/questions/45151481/addfrompromptasync-does-not-work-correctly-in-excel-online

**Comment by peronald** [comment]
Are you saying the issue is that the dialog doesn't allow the user to select the range with the cursor? If so, that is by design in the Excel Online client. The user can still enter the range in the text box though.

**Comment by shyambhiogade** [comment]
@peronald thanks for your reply, you understood it right, i am not able to select the range with cursor., why is there different experince for desktop and online version. at-least it should show the range selection in the backround when user manually enters the range, its not very intuitive, I would rather not show the prompt selection dialog in excel online. is there any way to detect if officeaddin is opened from excel online or excel desktop. any suggestion you would like to me give on how to make it more intuitive.
