### ISSUE TITLE
[Content Addin] Excel online crashes and corrupts the file on saving settings

### ISSUE THREAD

**Issue by 3dot1four** [OfficeDev/office-js#758]
## Expected Behavior

Excel online should not crash while saving settings
## Current Behavior

Excel online crashes with below error
![image](https://user-images.githubusercontent.com/4102247/66243899-d8484f80-e723-11e9-8a46-33b1c0b49956.png)
## Steps to Reproduce, or Live Example

Just run below line of code from a content Addin
`Office.context.document.settings.set("data", new Uint8Array(200000));
Office.context.document.settings.saveAsync(function (asyncResult) {
            console.log(asyncResult);
});`

We are actually trying to save Uint8Arrays in content addins which is leading to failure in excel online. It works perfectly in excel desktop.

## Your Environment

* Platform: Excel Online
* Host: Excel
* Office version number: (x-officeversion: 16.0.12204.31875)

**Comment by grangeryy** [comment]
Bug 3698271 created to track.

**Comment by MandytMSFT** [comment]
@rohitrewa i can't repro this issue on 16.0.12206.31877 which is the newer version. Could you help try again? If it's still repro, could you provide below info to us ? 

- Sample code which can reproduce this issue. We suggest to create a snippet by ScriptLab and share it to us.
- Session ID. Please reproduce this issue in Excel Online and provide the Session ID to us. You can find the Session ID from File -> About -> Session ID

**Comment by 3dot1four** [comment]
This still repros for me for the latest version: 16.0.12207.35901
session id: e6d40507-ea33-445a-8cd7-52b677bf7584
The issue does not repro for side pane addins so script lab snippet will not work.

I have added a Video in the bug, you guys can have a look.

https://office.visualstudio.com/e853b87d-318c-4879-bedc-5855f3483b54/_apis/wit/attachments/ae43c0ed-dd0b-41d6-b6ab-f3e04e5b6450?fileName=Media1.mp4&download=false&api-version=5.0-preview.2

**Comment by 3dot1four** [comment]
@MandytMSFT Any luck in getting the repro now?
@grangeryy Can you please help here in getting the bug triaged and assigned to a developer.

Team this is a very important bug for us and our first release is blocked on this.

**Comment by MandytMSFT** [comment]
@rohitrewa  yes, i can repro it now. And our team is working on that.

**Comment by MandytMSFT** [comment]
Chat with rohitrewa offline, this issue has been resolved by alternative way.
