### ISSUE TITLE
Show/hide elements depending on whether an Outlook web Add-In is installed or not

### ISSUE THREAD

**Issue by kakusharma** [OfficeDev/office-js#759]
I need to show an element in the email body if a specific Outlook web Add-In is not installed. Is there any way we can do that?

**Comment by exextoc** [comment]
There is currently no way to do something like this, in Read Mode. Can you help us understand the scenario that you are trying to achieve?

**Comment by kakusharma** [comment]
I want to show install Add-In message only if the Add-In is not installed already. Otherwise, hide that text.

**Comment by exextoc** [comment]
Currently the feature you are requesting, is not a part of the product. We track Outlook add-in feature requests on our [user-voice](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins) page. Please add your request there. Feature requests on user-voice are considered when we go through our planning process
