### ISSUE TITLE
Visual Studio displays a warning when including the office-js's dist folder in a project

### ISSUE THREAD

**Issue by eblancperso** [OfficeDev/office-js#76]
When including the npm package's dist folder in a Visual Studio 2017 project, a warning is displayed showing "The JavaScript language service has been disabled for the following project(s)"

## Expected Behavior
No warning should be displayed

## Current Behavior
A yellow banner is displayed in Visual Studio 2017 displaying a warning message.

## Steps to Reproduce, or Live Example
1. Create a new ASP.NET Web Application 4.6.2 project (MVC Template)
2. Run "npm init" to create a package.json file
3. Run "npm i @microsoft/office-js" to install dependencies.
4. In Visual Studio, select the "Show all files" button in Solution Explorer
5. Right click on the "dist" folder under "node_modules/@microsoft/office-js" and select "Include in project"

A warning banner indicating that the JavaScript language service has been disabled is shown.

## Context
It won't compile some custom typescript/javascript files for some reasons.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: n/a
* Office-JS version: 1.1.4
* Operating System: Windows 10
* Browser (if using Office Online): n/a

**Comment by wertyphil** [comment]
I am also facing this issue, any update on this @JuaneloJuanelo ?

**Comment by ElizabethSamuel-MSFT** [comment]
@eblancperso @wertyphil Are you still able to repro this? If so, let us know and we'll see if we can provide a workaround. Closing for now.
