### ISSUE TITLE
Is there a way to debug ExecuteFunction-Action in Outlook/Office Desktop?

### ISSUE THREAD

**Issue by eneoli** [OfficeDev/office-js#763]
Debugging Add-Ins that use a TaskPane is easily possible using F12 Tools or VisualStudio Debugger, but ExecuteFunction-Actions don't have this possibility what get's really frustrating if your code works in owa and you don't have any information to work with.
## Steps to Reproduce, or Live Example

Just try to debug an ExecuteFunction-Action

## Context

We had a Button in a taskpane executing a function. We desided to make an extra button in the ribbon for that. While still working in owa, the exactly same code that worked in Desktop before (Button in TaskPane) stopped working.
## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook Desktop
* Office version number: 1909
* Operating System: Windows 10

**Comment by exextoc** [comment]
If you are still on a version of Windows 10 or Office that does NOT support the new Edge WebView, you can attach a debugger (like Visual Studio) in Script mode to the iexplorer.exe process running in script mode to debug.

**Comment by eneoli** [comment]
Using Internet Explorer for owa works also as a workaround. Closing issue
