### ISSUE TITLE
Doesn't work in outlook app

### ISSUE THREAD

**Issue by iuri1994** [OfficeDev/office-js#765]
I am using the makeEwsRequestAsync to get user information like phone number and email. The problem is i can obtain all the parameters in the web-app (outlook in chrome) and when i use it in the windows app i can't. For example, when i use it to get the phone numbers, i can obtain how many numbers that contact have, but the phone numbers returned are undefined.
On the web-app, i don't have any problem.

**Comment by exextoc** [comment]
What is your xml for the get request, and the response you get in each case? What Exchange Server version are you connecting to? What is the version of the desktop client that you are using?

**Comment by iuri1994** [comment]
https://github.com/OfficeDev/office-js/issues/765

The xml code in a string `'<?xml version="1.0" encoding="utf-8"?>'+
'<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"'+
'               xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"'+
'               xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"'+
'               xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">'+
'  <soap:Header>'+
'    <t:RequestServerVersion Version="Exchange2013_SP1" />'+
'  </soap:Header>'+
'  <soap:Body>'+
'    <m:FindItem Traversal="Shallow">'+
'      <m:ItemShape>'+
'        <t:BaseShape>Default</t:BaseShape>'+
'      </m:ItemShape>'+
'      <m:IndexedPageItemView MaxEntriesReturned="50" Offset="0" BasePoint="Beginning" />'+
'      <m:ParentFolderIds>'+
'        <t:DistinguishedFolderId Id="contacts" />'+
'     </m:ParentFolderIds>'+
'     <m:QueryString>'+ email +'</m:QueryString>'+
'   </m:FindItem>'+
'  </soap:Body>'+
'</soap:Envelope>';
`

in the web browser, with the console log got this response 

![image](https://user-images.githubusercontent.com/51403191/66464262-8f233300-ea76-11e9-81bc-402c90506116.png)

where i can get the numbers

![image](https://user-images.githubusercontent.com/51403191/66464635-44ee8180-ea77-11e9-84b3-baaa101c5126.png)

in the windows app this is what i get:

![image](https://user-images.githubusercontent.com/51403191/66464717-63ed1380-ea77-11e9-8d06-0af12108aada.png)

but i can obtain how many numbers exist in the contact info.

The exchange version is 
![image](https://user-images.githubusercontent.com/51403191/66465800-79fbd380-ea79-11e9-8ccc-5f075cd17ca3.png)

The desktop client version is 
![image](https://user-images.githubusercontent.com/51403191/66465446-c561b200-ea78-11e9-9d79-19a5608448e1.png)

Best regards,

**Comment by exextoc** [comment]
We already have a bug tracking this.  I updated the bug that OP responded.
Bug 1252808<https://o365exchange.visualstudio.com/DefaultCollection/O365%20Core/_workitems/edit/1252808>: New GitHub Issue [OfficeDev/office-js]: Doesn't work in outlook app

**Comment by exextoc** [comment]
Do you have the find response request from the Desktop Client? Is it empty? or is it giving you errors? Do other MakeEwsRequests from desktop client also fail? Using fiddler may also help figure out why the ewsrequest from desktop is failing.

**Comment by iuri1994** [comment]
Hi
Today i tried to transform the response of the makeEwsRequestAsync into a string using the XMLSerializer(), with that i could confirm that the outlook is making the request and it's getting a response from the server,  because i am getting the same response in both, web app and windows app, and with that i can now find the parameters i want, this was the solution i found.
![image](https://user-images.githubusercontent.com/51403191/66654293-d570c180-ec31-11e9-9d2f-c66e5e428dda.png)


but in the other way i was doing still doesn't work, i know now that the outlook is making and getting the response but still gives me the parameters undefined,
to get the the phone numbers i use (this is the function in the ews request)


`function values(asyncResult){`
`  var result = asyncResult.value;`
`  var context = asyncResult.context;`
` if (asyncResult.status == "succeeded") {//get numbers from contact info`
`    var xmlDoc = $.parseXML(result.toString());
   xmlDoc.getElementsByTagName("t:PhoneNumbers")[0].getElementsByTagName("t:Entry"));`
`if (xmlDoc.getElementsByTagName("t:Items")[0].innerHTML!=""){`
      `var aux = xmlDoc.getElementsByTagName("t:PhoneNumbers")[0].getElementsByTagName("t:Entry");      `
`      var p = xmlDoc.getElementsByTagName("t:DisplayName")[0].innerHTML;      `
     ` for(let i = 0; i < aux.length; i++ ){`
        `PhoneNumber.push(aux[i].innerHTML);`
`      }
    }
  }`

and the variable PhoneNumber gives all the numbers as undefined.

best regards

**Comment by exextoc** [comment]
I'm sorry your last post was kind of unclear. You ARE getting a response back from the desktop client version? If you do a JSON.stringify(asyncResult). What is the value in the web client? What is the value in the desktop client? (are they the same?)

**Comment by iuri1994** [comment]
I am sorry for my last post been unclear,
1. I am getting a response from the desktop client version.

2.I receive the same response in both of them, I discovered this using the makeewsrequestasyn as a string and not transforming it in JSON.

3. Using the response as a string I can obtain the info I need, if I use it like JSON I get the undefined values.
 

In my last post I posted the code I use to get the info using JSON. That code works on the web app, but doesn't work on the desktop.

Hope this post were more clear.

Best regards,

**Comment by exextoc** [comment]
If the response is the same, then the function is working as intended. There is likely something wrong with your code that is parsing the information that we can't assist with. It is likely that since desktop will use IE, that different libraries / functions do not work in the IE environment.
