### ISSUE TITLE
Excel: Office.SetSelectedDataOptions.tableOptions fails when setting table options

### ISSUE THREAD

**Issue by ndeeH** [OfficeDev/office-js#767]
We have a TaskPane add in in the office store which adds content into excel and word.
Since a few weeks we get errors when we add formatted tables into excel via the Common API.

## Expected Behavior
We are using `setSelectedDataAsync(data: TableData, options: [SetSelectedDataOptions]) ` since a long time and have set the table style and options via the **[options.tableOptions parameter](https://docs.microsoft.com/en-us/javascript/api/office/office.setselecteddataoptions?view=word-js-preview)**.
#### Example 
```
options = {
            coercionType: Office.CoercionType.Table
            , tableOptions: {
                style: "TableStyleMedium2"
                 , headerRow: false        // these settings will cause the error - begin
                , firstColumn: false
                , filterButton: false
                , totalRow: false
                , lastColumn: false
                , bandedRows: false
                , bandedColumns: false  // end
            }
            , cellFormat: ...
        };
```
### These table settings worked for years- now we get those errors and our add-in is worthless. All our customers are using this feature and we have no work around.
Switching to Excel Javascript API is not option because we have to support older office versions!

## Current Behavior
We get this Error:
```
code	8011	Number
message	"One or more of the tableOptions parameters have values that aren't allowed. Double-check the values and try again."	String
name	"Invalid Value"	String
```
## Steps to Reproduce, or Live Example
You will be able to use our store office add in to check it out.
But only one day - end of this week we have to remove the table formatting because our customers can not use the add in anymore!
![tableOptions_parameters_failure](https://user-images.githubusercontent.com/11518242/66506882-73e41200-eace-11e9-8f4e-d5827b2397ac.gif)

### complete call
Here the parameter to reproduce (used JSON.stringify to export):
**options =** 
`{"coercionType":"table","tableOptions":{"style":"TableStyleMedium2","headerRow":false,"firstColumn":false,"filterButton":false,"totalRow":false,"lastColumn":false,"bandedRows":false,"bandedColumns":false},"cellFormat":[{"cells":{"row":0,"column":0},"format":{"fontStyle":"bold","width":"auto fit"}},{"cells":{"row":1,"column":0},"format":{"fontStyle":"italic","width":"auto fit"}},{"cells":{"row":1,"column":1},"format":{"width":"auto fit"}},{"cells":{"row":2,"column":0},"format":{"fontStyle":"italic","width":"auto fit"}},{"cells":{"row":2,"column":1},"format":{"width":"auto fit"}},{"cells":{"row":3,"column":0},"format":{"fontStyle":"italic","width":"auto fit"}},{"cells":{"row":3,"column":1},"format":{"width":"auto fit"}},{"cells":{"row":4,"column":0},"format":{"fontStyle":"bold","width":"auto fit"}},{"cells":{"row":4,"column":1},"format":{"width":"auto fit"}},{"cells":{"row":5,"column":0},"format":{"fontStyle":"italic","width":"auto fit"}},{"cells":{"row":5,"column":1},"format":{"width":"auto fit"}},{"cells":{"row":6,"column":0},"format":{"fontStyle":"italic","width":"auto fit"}},{"cells":{"row":6,"column":1},"format":{"width":"auto fit"}}]}`

**data =**
`{"headers":null,"rows":[["Filter",""],["Country","All Geographies"],["Date.Fiscal Year","FY 2007"],["Category","Bikes"],["Cube","Adventure Works"],["Data status","21.12.2017  15:11:10"],["Last Schema Update","12.2.2019  19:21:36"]]}`

#### Remarks
Removing these options will solve the failure (but we need these options!)
`,"headerRow":false,"firstColumn":false,"filterButton":false,"totalRow":false,"lastColumn":false,"bandedRows":false,"bandedColumns":false`

## Your Environment
Office 2016 latest updates
![2019-10-09 19 52 46](https://user-images.githubusercontent.com/11518242/66506963-9b3adf00-eace-11e9-83e1-166cde224897.jpg)

**Comment by donlvMSFT** [comment]
Thanks for reporting it to us.

I tried to reproduce it but failed, but  This seems works well on Excel latest version. Both using your add-in or use [snippet](https://gist.github.com/J-January/587f677a57aca25b6a71cba892edac3a) create in ScriptLab couldn't reproduce this issue.

Could you update the Office version and give it a try?

**Comment by ndeeH** [comment]
@J-January 
OK - I updated my Office version and now with this version:
![image](https://user-images.githubusercontent.com/11518242/66543203-0ae3b500-eb35-11e9-8b76-4d3320a94a4d.png)
**It works - again!** 🎉

**_So between those build versions (*.20288 - *.20384) this error definitely existed. 
Don't you have test cases to validate that each release of the API is fully functional?_** 🤔

Should we add a detail hint to all API related errors?
ℹ _Please update your office version and try again._

**Comment by donlvMSFT** [comment]
Glad it work!

API do have many test cases, but test cases couldn't cover all of the scenarios.
We will follow up to add test cases base on this issue to avoid further regression, thank you!
