### ISSUE TITLE
[Outlook add-in]Office.context.mailbox.item.body.getAsync can not get right content, which will cause error

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#768]
I am a developer on office365 add ins.
In outlook 2013, when I try to get a body with an attachment using 'body. getAsync', a picture with a hyperlink is returned. So that after I put this Body back use 'Body.setAsync', this attachment can not be open directly by double click.

## Expected Behavior
In HTML mode body.getAsync can identify the attachment with a special tag.
Or there is a js API to get attachments in body.(now outlook MSO version and outlook 2013 not support these  api)

## Current Behavior
 In outlook 2013, when I try to get a body with an attachment using 'body. getAsync', a picture with a hyperlink is returned. 

## Context
Now our user who use outlook 2013 can not use add-in to handle email with attachment in body.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2013 (15.0.5172.1000) MSO (15.0.5172.1000) 64bit.
* Operating System: Windows 10
* Browser (if using Office Online): ______

**Comment by exextoc** [comment]
Can you give an example of the response that you are getting, and what you are expecting? 

More than likely though, the version of Outlook 2013 is out of date, and needs to be upgraded. There were some changes made GetBody after SP1. Please make sure that Outlook 2013 is upgraded to the latest version, as well as the rest of the Office client. (notably, MSO.dll, osf.dll, and Word all need to be upgraded).

**Comment by SWei1234** [comment]
Thanks for your reply.
I insert a file (testfile.xml) to my email body
My code like:
`Office.context.mailbox.item.body.getAsync("html", {coercionType: Office.CoercionType.Html}, function (result) {
                    resolve(result.value);
                });`
Then I get response is:
`<p class=MsoNormal><img width=96 height=81 src="~WRS%7b6....D06-82C5-82AD48888B93%7d.files/image001.png"></p>`
I expect it to return other tags instead of < img > so that I can distinguish the attachments inserted into the body from the images. 
or is there any way I can try on outlook 2013 cause lots of our user still use outlook 2013.

**Comment by exextoc** [comment]
Those strange img src tag was a bug that was fixed in Outlook 2013. If your users upgraded Outlook 2013 they should see a fix. Do you know the specific build version of Outlook 2013 that they are on? (something like 15.0.XXXX.1000) (the XXXX is the stuff that is important). More importantly Outlook 2013 allows people to update binaries individually, so it is often not enough Outlook is just updated, but the whole of office. If they have Automatic Updates turned on they should be getting them, but some organizations stop automatic updates by policy.

**Comment by SWei1234** [comment]
> Those strange img src tag was a bug that was fixed in Outlook 2013. If your users upgraded Outlook 2013 they should see a fix. Do you know the specific build version of Outlook 2013 that they are on? (something like 15.0.XXXX.1000) (the XXXX is the stuff that is important). More importantly Outlook 2013 allows people to update binaries individually, so it is often not enough Outlook is just updated, but the whole of office. If they have Automatic Updates turned on they should be getting them, but some organizations stop automatic updates by policy.

Thanks for your reply, I didn't get the customer's version yet. But I can reproduce this problem on my computer. My outlook 2013 version is 2013 (15.0.5172.1000) MSO (15.0.5172.1000) 64bit. 
So, what patches should I install to fix this problem? May I have a patch number? Or patch link is better.

**Comment by exextoc** [comment]
That build should have the fixes it it. So perhaps I misunderstood your original problem. Are you using RTF e-mails to insert attachments?

**Comment by SWei1234** [comment]
Let me take an example to describe this problem:
I wanna schedule a meeting with a doc attachment in email body. I can double-click and open the file after I drag it in. But After I use Body.getAsync and Body.setAsync to insert my html invitation page. I can't open the doc in email body by double click. 
So is there anything I can do to let this doc can be open by double click? or at least let it work like outlook 2016:
In outlook 2016, use Body.getAsync and Body.setAsync the attachments in body will be archived in the attachment bar. 
By the way, I have tried set email format to HTML and RTF, the result is the same.

**Comment by exextoc** [comment]
In Outlook 2013, the only format for meeting request is RTF and there's no way to change to HTML for meeting requests. Unfortunately, what you are seeing is a limitation of the API with RTF editor.  There are no plans to change Outlook 2013 editor.

**Comment by SWei1234** [comment]
> In Outlook 2013, the only format for meeting request is RTF and there's no way to change to HTML for meeting requests. Unfortunately, what you are seeing is a limitation of the API with RTF editor. There are no plans to change Outlook 2013 editor.

Yes,I see. That's doesn't matter.  But I really want to know is:
Is there anything I can do to let this doc can be open by double click after I use Body.getAsync get whole body and then use  Body.setAsync set them back? 
Thanks

**Comment by SWei1234** [comment]
@exextoc Hi ,Is my description not very clear? any information I can provide？

**Comment by SWei1234** [comment]
@exextoc Our customer's Version is 2013 (15.0.5163.1000) MSO (15.0.5172.1000) 32-bit part of microsoft Office Professional Plus 2013

**Comment by exextoc** [comment]
It's not possible in Outlook 2013 because the API only supports this scenario for HTML messages, and in Outlook 2013 all meeting requests are in RTF.

**Comment by SWei1234** [comment]
> It's not possible in Outlook 2013 because the API only supports this scenario for HTML messages, and in Outlook 2013 all meeting requests are in RTF.

Okay, Thanks for your reply. last question:
So in Outlook 2013 there is no api for add-in to get the body with attachment and set them back right? At least so far.

**Comment by exextoc** [comment]
This is correct. This isn't possible via any Office.js API in Outlook 2013.

Closing the issue, but let us know if you have more questions.

**Comment by SWei1234** [comment]
> This is correct. This isn't possible via any Office.js API in Outlook 2013.
> 
> Closing the issue, but let us know if you have more questions.

Okay, Thanks. I got it. 

So ... if I develop an add-in on Outlook 2013, there is no way to insert the attachment into body and use the office.js' s api to update the body's content. And at the end, the inserted attachment can still be opened by double-click.

Right?

**Comment by exextoc** [comment]
Yes, this functionality is currently not supported in Outlook 2013.

**Comment by SWei1234** [comment]
> Yes, this functionality is currently not supported in Outlook 2013.

Okay, Thanks for your support. I have no question about this now.
