### ISSUE TITLE
Office Common API is not available in Custom Functions Runtime on Desktop

### ISSUE THREAD

**Issue by zakhan4** [OfficeDev/office-js#769]
## Expected Behavior

I expect to have [Office.Context](https://docs.microsoft.com/en-us/javascript/api/office/office.context) Common API available for Custom Function Runtime as well. As it has very important information inside it for example: information regarding display/content language, host, platform, requirements etc. of the system where add-in is running

## Current Behavior

Although I can access Office.Context property values inside Custom Function Runtime in Office Online. These are not available in Excel Desktop and "Office" object is always "undefined" inside Custom Function Runtime.

## Context

Right now, I'm trying to access the [Office.Context.displayLanguage](https://docs.microsoft.com/en-us/javascript/api/office/office.context?view=word-js-preview#displaylanguage) information inside custom functions, which in turn sends this information to the server, to get the localized response from the server.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 1910 (Build 12130.20112)
* Operating System: Microsoft Windows 10 Enterprise (10.0.18362)

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by keyur32** [comment]
Hi this is feature is actively being worked on. Workaround if you have a taskpane visible is to fetch it from the taskpane and pass it to the Custom Function via OfficeRuntime.storage API.

**Comment by zakhan4** [comment]
Hi,

Thanks for the response @keyur32. I'm glad that this feature is being actively worked on, but just the fact that it is already working in Office Online right now makes it a bit confusing, was my point.

Also about the workaround you suggested, I have already tried it. But I don't think that it is a reliable way to solve this problem. Because to fetch the values from the Task Pane and then send it to Custom Functions would mean that the user has to open the task pane first, while there could be scenarios when Custom Functions are executed even before there was a need for the user to open the task. pane.

**Comment by caolgood** [comment]
My 2 cents:
For our use case we want to get Office.context.document.url since that contains some necessary context used to build the path to one of our service endpoints. 
Not having that in the custom functions runtime makes it very difficult to use the OfficeRuntime.storage to hold authentication info since we need it to be scoped by document, not just domain. We want to support multiple excel documents with our add-in opened at once, which are making requests to different endpoints on the same domain.

**Comment by caolgood** [comment]
It looks like v1.2 of the custom functions runtime will fix this: https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial

I haven't gotten access to an insider build yet to test this, does it mean we will be able to use the full Office.context api in custom functions?

**Comment by RuoyingLiang** [comment]
This scenario is covered with Shared Runtime [https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime](url)
