### ISSUE TITLE
[Excel][Mac] Can't format by column in setFormatsAsync in Excel for Mac

### ISSUE THREAD

**Issue by igillis** [OfficeDev/office-js#77]
## Expected Behavior

I would expect this API to be consistent across environments.

## Current Behavior

I'm receiving an error 5001 Unknown error occurred. There's also something about extraArgs

## Steps to Reproduce, or Live Example

Run the following on Excel for Mac
`Office.select("bindings#myBinding).setFormatsAsync(
    [{cells: {column: 0}, format: {fontColor: "yellow"}}], 
    function (asyncResult){});`

## Context

I am trying to mark the background of an entire column red to let the user know the header is incorrect. Ideally I could mark just the one header cell red, but that doesn't seem possible.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.11
* Operating System: High Sierra

**Comment by JuaneloJuanelo** [comment]
is there any reason why you are not using the new Excel APIs for this?

**Comment by igillis** [comment]
Thanks for getting back to us! This is some fairly old code that we haven't touched in a while, but we are now attempting to add Mac support. 

Which new API did you have in mind for a use case like this? I looked through the updates [here](https://dev.office.com/reference/add-ins/requirement-sets/excel-api-requirement-sets) and nothing really jumped out.

**Comment by sumurthy** [comment]
[This](https://dev.office.com/reference/add-ins/excel/rangeformat) is a good starting point. Script Lab also has many examples dealing with formatting.

**Comment by igillis** [comment]
Thanks for pointing me to Script Lab, that has some useful examples. We are way behind, it seems all of the callback based interactions are no longer preferred and we should update everything to use context-based APIs. That's going to be somewhat of a lift for us.

I would argue that this is still a bug since the callback-based APIs are not actually deprecated and should behave consistently across environments. Feel free to correct that thinking.

**Comment by igillis** [comment]
Also, it seems that the `Excel` object is not defined in `Excel 2013` and supporting that is a requirement on our side. Was trying to avoid branching implementations of the same features.

**Comment by JuaneloJuanelo** [comment]
issue is mitigated with formatting APIs.
