### ISSUE TITLE
mailbox.item.body.getAsync with Text Coercion type returns incorrect text.

### ISSUE THREAD

**Issue by mpetro-t** [OfficeDev/office-js#773]
mailbox.item.body.getAsync with CoerctionType.Text does not separate text lines/paragraphs in Outlook Online when message type is Html. In Outlook for desktop it returns paragraphs/lines separated by spaces (which is the expected behavior).

## Expected Behavior
To have email message paragraphs separated.

## Current Behavior
All paragraphs are "glued" together in Outlook Online. They are separated properly in Outlook for Desktop.

## Steps to Reproduce, or Live Example

* Additional details:
  1. Open Outlook Online
  2. Compose a message (make sure that message is of Html type)
  3. Type in word "Hello" press Enter and type in "World"
  4.  You should have Hello and in new line World
  5.  Try to retrieve item body with Office.context.mailbox.item.body.getAsync(Office.CoercionType.Text, yourCallback);
  6.  Text "HelloWorld" is retrieved (without space or separator)

If repeating same scenario in Outlook for Desktop "Hello World" is retrieved by same function.

![image](https://user-images.githubusercontent.com/53277298/66674804-dd306600-ec31-11e9-8163-cfccc720a40f.png)

![image](https://user-images.githubusercontent.com/53277298/66674834-f0433600-ec31-11e9-8c16-4ce472e2c8be.png)

![image](https://user-images.githubusercontent.com/53277298/66674850-fd602500-ec31-11e9-893a-afc721fddf75.png)

![image](https://user-images.githubusercontent.com/53277298/66674867-06e98d00-ec32-11e9-9992-dd37d52f188b.png)

## Context
We need to retrieve email body as text (without any styling) in order to further process it.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Windows 10
* Browser (if using Office Online): Chrome

## Useful logs

- [ ] Console errors
- [ x ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
It is a bug from our end. we have added this to our backlog.

**Comment by kumaro** [comment]
is this fixed? we are experiencing the same issue since yesterday.

**Comment by msm2020** [comment]
Do you manage to fix this bug ?

**Comment by exextoc** [comment]
We have this in out backlog and we are planning to take this up soon and will keep you posted on the progress

**Comment by wxin627** [comment]
Any updates?

**Comment by gagliu** [comment]
Experiencing the same issue

**Comment by geniuslionel** [comment]
Hi @exextoc. I'm guessing this issue came back since you "closed this as completed on Jan 5, 2020". Any ETC would be nice so we can let our customers know.

**Comment by exextoc** [comment]
We have this in our backlog and we are planning to take this up soon and will keep you posted on the progress.
Internal Tracking ID: 58210

**Comment by prasad-cm** [comment]
Appreciate if there is any update on this issue? We are processing the body contents by line separators which is breaking on online outlook
