### ISSUE TITLE
Office.context.ui.displayDialogAsync is failing with error code -2147208651

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#774]
We are using adal for AAD authentication in our Addin
For opening a Sign In dialog we are using Office.context.ui.displayDialogAsync() function

## Expected Behavior
The dialog should be successfully opened or it should throw error code from 
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins

## Current Behavior
Dialog is failing to open and it is returning error code -2147208651

## Context
We have an Addin where we are using adal for AAD authentication.
For opening a Sign In dialog we are using Office.context.ui.displayDialogAsync() function

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Version 1902 (Build 11328.20438 Click-toRun)
* Operating System: Windows

**Comment by abtrip** [comment]
Hi Team -is there  any update on this issue?

**Comment by lliu113** [comment]
@shyampatroms - I'm closing this issue as it's stale. Please reopen if you are still experiencing problems. Thanks!
