### ISSUE TITLE
How to add an attachment to a new outlook email using a SOAP request in an Outlook Addin?

### ISSUE THREAD

**Issue by THPubs** [OfficeDev/office-js#776]
Right now I use the `Office.context.mailbox.item.addFileAttachmentAsync` method to attach new files to the currently composing email. I want to use a SOAP request to do this instead to better support self-hosted exchange servers.

I found the following doc: https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-add-attachments-by-using-ews-in-exchange#add-an-attachment-to-an-existing-email-by-using-ews but the problem is in there, I need to provide the item ID. For new emails `Office.context.mailbox.item.itemId` is undefined. Even after I use `Office.context.mailbox.item.saveAsync` to save the item it's still undefined. Any idea how to fix this?

**Comment by exextoc** [comment]
Office.context.mailbox.item.saveAsync returns item id in the async result.  However there are additional issues with this approach.  The soap(EWS) request only works on items that exist on the Exchange server.  In Desktop Outlook, for example, saveAsync only saves the item locally and sync-ing to Exchange can take additional time.

Additionally, you will need to have access to EWS to call the method.  Only a subset of EWS methods are exposed directly from addin, and CreateAttachment is not one of them.  https://docs.microsoft.com/en-us/outlook/add-ins/web-services,

Have you looked at the new Outlook preview method to add file content directly to the item?
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/preview-requirement-set/office.context.mailbox.item#addfileattachmentfrombase64asyncbase64file-attachmentname-options-callback

**Comment by THPubs** [comment]
@exextoc Actually I'm sending the ewsURL to our API and from there I call the exchange server using the callbackToken to in the header like this:

    request.post(
      {
        url: ewsUrl,
        headers: {
          Authorization: `Bearer ${callbackToken}`,
          'Content-Type': 'text/xml'
        },
        body: setAttachmentSOAP
      },
      async (error, response) => {
        console.log(error);
        console.log(response);
      }
    );

**Comment by THPubs** [comment]
@exextoc The problem with the direct method is that for older exchange servers and for some self hosted exchange servers it does not work.

**Comment by THPubs** [comment]
@exextoc I just tried with the item id returned by the `Office.context.mailbox.item.saveAsync` method but the response gave me the following errors:

> 2000008;reason="The web method in the request is not allowed with this token.";error_category="invalid_grant"
> The requested web method is unavailable to this caller or application.

**Comment by exextoc** [comment]
With the callbackToken (from getCallbackTokenAsync) Only GetItem and GetAttachment are supported.  See https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/preview-requirement-set/office.context.mailbox#getcallbacktokenasyncoptions-callback

I am curious about the issues you are seeing with addFileAttachmentAsync.
What versions of Exchange are you targeting?  For Outlook, are you targeting web (OWA), windows or Mac, and what versions? 
The reason I ask, addFileAttachmentAsync does not depend on Exchange for Desktop Outlook for Windows, for example.

**Comment by THPubs** [comment]
I'm trying to give support to all mobile, desktop (Both Mac and Windows) and web. Any idea how to authenticate without the callback token for `addFileAttachmentAsync`?

**Comment by exextoc** [comment]
Ok, there's currently no support for compose addin on mobile, so I will focus on desktop and web.
For desktop and web, addFileAttachmentAsync was the first available API on the platform for adding attachment, so it has the best coverage for older versions.

You don't need a token to call Office.context.mailbox.item.addFileAttachmentAsync.  
If you mean getting a token to add attachment, you can consider the rest token, but that would not have the same coverage for older versions (both Exchange and Outlook clients).

Could you go into a bit more on the issues you see with addFileAttachmentAsync?

**Comment by THPubs** [comment]
Thanks. Yes, surely I'll dive deeper into the issue and see. The problem was one of our main users had issues with it and they had a self-hosted exchange server version 2016. I just installed it my own machine and let's see how that goes. Any known issue with that version of the exchange server?

**Comment by exextoc** [comment]
For Outlook desktop in Windows, the Exchange server should not matter for addFileAttachmentAsync.  Client side firewall may block the download but that would be the same with any Exchange version.

For OWA, the attachment is retrieved from the Exchange server.  So the self-hosted Exchange needs to reach the url of addFileAttachmentAsync.  Again, the exact version of Exchange should not matter, but firewall may be an issue here, but it would be the restriction on the server instead of the client.

Exchange server 2016 is updated quarterly, so if the issue is not one of the above, it would be great to know which CU (update) is being used.

**Comment by THPubs** [comment]
@exextoc Just setup the latest 2016 exchange server (CU12). I tried to use the `addFileAttachmentAsync` to attach a file and it returned the following error:

```javascript
error: {…}
code: 9007
message: "The attachment cannot be added to the item."
name: "AttachmentUploadGeneralFailure"
```

To make sure it's not only my attachment. I tried to upload some other image files I can find in the web. But nothing works. And when I log into the server and open a browser, I can access these files without issue. This method workd in outlook.com but not in my Exchange server. Any idea why?

**Comment by exextoc** [comment]
To confirm, are you getting the error with OWA?
If you are getting the error for Windows or Mac Outlook, could you provide those client versions also?

**Comment by THPubs** [comment]
Right now only tested in OWA.

**Comment by THPubs** [comment]
Just tested with Outlook Desktop for Mac and in there `Office.context.mailbox.item.addFileAttachmentAsync` works! But still fails in the web addin.

**Comment by exextoc** [comment]
1. Thanks for reproducing this in OWA. Can you also please share your code-snippet for adding the attachment?

2. "_And when I log into the server and open a browser, I can access these files without issue_". I wanted to understand this more. Do you mean you login to Exchange Server machine and trying to access the Outlook from Browser? What files you are able to access?

**Comment by THPubs** [comment]
1) The code snippet:

```javascript
    Office.context.mailbox.item.addFileAttachmentAsync(
      fileURL,
      selectedAttachment.name,
      {},
      result => {
        if (result.status.toString() === 'succeeded') {
          // Notify the user
          notificationSystem.addNotification({
            message: `${i18n.t('file')} ${selectedAttachment.name} ${i18n.t(
              'successfullyAttached',
            )}`,
            level: 'success',
            position: 'bc',
          });

          // Call redux saga emitter
          emitter({
            status: 'success',
            selectedAttachment,
          });

          // If there are more files in the list, call attach again
          if ((selectedAttachments.length - 1 !== 0)) {
            const newListOfAttachments = [...selectedAttachments];
            newListOfAttachments.shift();

            officeAttachFiles(
              newListOfAttachments,
              notificationSystem,
              emitter,
              history
            );
          } else {
            emitter(END);
          }
        } else {
          notificationSystem.addNotification({
            message: i18n.t('someError'),
            level: 'error',
            position: 'bc',
          });

          emitter({
            status: 'error',
            selectedAttachment,
          });

          emitter(END);
        }
      },
    );
```

2) Yes you are correct. Login to the exchange server machine and try to access the `fileURL` im passing to the `addFileAttachmentAsync` function.

**Comment by THPubs** [comment]
@exextoc Any updates on this?

**Comment by exextoc** [comment]
@THPubs Does it work if you give fileURL as any publicly accessible URL? Example: http://i.imgur.com/WJXklif.png

**Comment by THPubs** [comment]
Nope. Tried that also.

**Comment by THPubs** [comment]
@exextoc I take it back. That URL worked. But earlier also I tested with a general image like this and it worked. But still out own images are failing.

**Comment by exextoc** [comment]
I see. So, it looks like HTTP/HTTPS server (hosted on Exchange Server) has something special which makes addin/OWA not able to fetch file from there and attach it. Right? Can you try capture networking trace when this API is running and see what you see when downloading file from HTTP/S server (Exchange Server)?

**Comment by THPubs** [comment]
@exextoc You mean check the network trace from the Exchange Server's side? May I please know how to do it?

**Comment by exextoc** [comment]
You can use https://www.telerik.com/fiddler to capture network trace and see what is happening when downloading file from exchange server. Can you try accessing the fileURL in incognito mode on public machine and see if fileURL requires any special access permissions?

**Comment by THPubs** [comment]
@exextoc Sure will try it out and let you know.

**Comment by THPubs** [comment]
@exextoc Sorry I did not get to check the trace. However, I'm proxying the request through another server to hide the host url. But still pass all the headers as it is and I can access the file using the proxied url from the browser. Might this be an issue?

**Comment by exextoc** [comment]
@THPubs We are not sure if this would be an issue. The network trace when making the request would clarify this. That should help us root cause this issue on OWA as well.

**Comment by illiach** [comment]
Method name: Office.context.mailbox.item.addFileAttachmentAsync()
URL and file name are provided and correct, file is correctly downloaded from browser.
AsyncResult error:

{code: 5001, message: "An internal error has occured.", name: "Internal Error"}

The issue occurs in Outlook for Mac only.

Please, advise what can be causing this and how to fix?

**Comment by exextoc** [comment]
Bug 1340469<https://o365exchange.visualstudio.com/959adb23-f323-4d52-8203-ff34e5cbeefa/_workitems/edit/1340469>: [OfficeDev/office-js] How to add an attachment to a new outlook email using a SOAP request in an Outlook Addin? (#776)

This is an Outlook For Mac  issue. But this poster is reviving an old thread. We should have them open this as another issue with more details.


Created using VSTS Outlook add-in<https://www.owiki.ms/wiki/VSTS_Add-In_for_Outlook>

**Comment by nchakravarthi** [comment]
Outllook for Mac.

Facing issue with the **Office.context.mailbox.item.addFileAttachmentAsync()**, 

AsyncResult error:

{code: 5001, message: "An internal error has occured.", name: "Internal Error"}

Can somebody help?

**Comment by nchakravarthi** [comment]
> Method name: Office.context.mailbox.item.addFileAttachmentAsync()
> URL and file name are provided and correct, file is correctly downloaded from browser.
> AsyncResult error:
> 
> {code: 5001, message: "An internal error has occured.", name: "Internal Error"}
> 
> The issue occurs in Outlook for Mac only.
> 
> Please, advise what can be causing this and how to fix?

Any solution for this?

**Comment by nchakravarthi** [comment]
The issue was with the file being under VPN protected access and it was not able to add it. We have sorted out the issue. 

It is working fine.
