### ISSUE TITLE
[Excel Online] getActiveCell() throws "PropertyNotLoaded" after load/sync

### ISSUE THREAD

**Issue by DLehenbauer** [OfficeDev/office-js#777]
## Expected Behavior
Snippet should log the active cell coordinates to the console.

## Current Behavior
Despite calling 'load()' and 'sync()', throws RichApi error with "PropertyNotLoaded", 

## Steps to Reproduce, or Live Example
```ts
const book = context.workbook.load();
book.onSelectionChanged.add(onSelectionChange);

const onSelectionChange = async (e: Excel.SelectionChangedEventArgs) => {
    await Excel.run({ delayForCellEdit: true }, async (context) => {
        const activeCell = e.workbook.getActiveCell();
        activeCell.load(["rowIndex", "columnIndex"]);
        await context.sync();
        console.log(`${activeCell.rowIndex}, ${col: activeCell.columnIndex}`);
    });
```

Some other variations I tried:
* getSelectedRange() instead of getActiveCell()
* Not awaiting Excel.run(..) -- i.e., letting the onSelectionChange promise resolve and performing the Excel.run(..) batch in a future turn.
* Passing no args to ```.load()```

## Your Environment
MacOS in latest Chrome

## Log
excel-web-16.00.js:24 Uncaught (in promise) RichApi.Error: The property 'rowIndex' is not available. Before reading the property's value, call the load method on the containing object and call "context.sync()" on the associated request context.
    at new c (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:24:286433)
    at Function.b.createPropertyNotLoadedException (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:24:384531)
    at b.throwIfNotLoaded (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:24:384435)
    at i.get [as rowIndex] (https://appsforoffice.microsoft.com/lib/1.1/hosted/excel-web-16.00.js:24:562802)
    at https://localhost:3000/taskpane.js:71044:35
    at step (https://localhost:3000/taskpane.js:70819:17)
    at Object.next (https://localhost:3000/taskpane.js:70750:14)
    at fulfilled (https://localhost:3000/taskpane.js:70704:24)

**Comment by Zlatkovsky** [comment]
@DLehenbauer , the issue is that you are creating an `Excel.run` with a new "anonymous" context, but you are using an existing object (in this case, the workbook that comes from the event).

If you did `await Excel.run(e.workbook, async context => ...)`, it should work.

If you want the `delayForCellEdit` as well, I believe the following syntax should work:

```
await Excel.run(
  { delayForCellEdit: true, previousObjects: e.workbook },
  async (context) => {
    // ...
  }
);
```

**Comment by DLehenbauer** [comment]
Thanks!  I had no idea that contexts need to be created for specific objects.  That solves my problem.
