### ISSUE TITLE
GetSharedPropertiesAsync is not a function in not shared folder

### ISSUE THREAD

**Issue by sarea** [OfficeDev/office-js#778]
I'm developing add-in OWA and trying to use `getSharedPropertiesAsync` for the shared folder from delegated account which is in preview,
it worked fine, but when I use it in a not shared folder I got the following.

`core.js:7376 ERROR Error: Uncaught (in promise): TypeError: Office.context.mailbox.item.getSharedPropertiesAsync is not a function
TypeError: Office.context.mailbox.item.getSharedPropertiesAsync is not a function`

not sure if this is by design but I expect to get `status error` from the result  Office.AsyncResult<Office.SharedProperties> explaining that this is not a shared folder for example.

**Comment by exextoc** [comment]
GetSharedPropertiesAsync is supposed to work only for shared mailbox, calendar and folder. Please check the documentation: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/preview-requirement-set/office.context.mailbox.item#getsharedpropertiesasyncoptions-callback. We agree the error can be more descriptive.
