### ISSUE TITLE
[Excel][Mac] Can't set tableStyle in setSelectedDataAsync

### ISSUE THREAD

**Issue by igillis** [OfficeDev/office-js#78]
On Windows/Online, you can specify a formatting style when setting table data by using a named style like `TableStyleLight18`.

## Expected Behavior
You can do the same thing in Mac Excel.

## Current Behavior
Right now, I receive a 5001 error with no detail if my payload contains a style.

## Steps to Reproduce, or Live Example
```
    var myTable = new Office.TableData();
    myTable.headers = [["Cities"]];
    myTable.rows = [['Berlin'], ['Roma'], ['Tokyo'], ['Seattle']];
    Office.context.document.setSelectedDataAsync(myTable, {coercionType: Office.CoercionType.Table, tableOptions: {style: 'TableStyleLight18'}},
        function (result) {
            var error = result.error
            if (result.status === Office.AsyncResultStatus.Failed) {
                write(error.name + ": " + error.message);
            }
    });
```

## Context
I just want to make sure that the tables I am creating programmatically are themed in a consistent way.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.10
* Operating System: High Sierra

**Comment by JuaneloJuanelo** [comment]
Hello.. is there a reason why you are not using our new APIs for Excel to do this?

**Comment by JuaneloJuanelo** [comment]
i will strongly recommend you to try the Table API for this. its way more powerful that setSelectedDataAsync https://docs.microsoft.com/en-us/javascript/api/excel/excel.table?view=office-js
