### ISSUE TITLE
The api Office.context.application.createDocumentAsync fails on iOS platform.

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#780]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
The api should work fine on Powerpoint iOS.

## Current Behavior
Insert an pptx file it's always throw an error : {"name":"Internal Error","message":"An internal error has occurred.","code":3001}

## Live Example
Gist: https://gist.github.com/jasonhieu1905/d81ca5b4a1998a2c776c21a112b846ef 

![ezgif-5-e6c963c3d5a8](https://user-images.githubusercontent.com/13063615/66997023-e6bb4180-f0fb-11e9-8064-7e7487f46b66.gif)

## Steps
    1. Sideload add-ins into powerpoint iOS device.
    2. Click button "Insert an existing sample file"
    3. Observe the result.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ___iOS___
* Host [Excel, Word, PowerPoint, etc.]: ___Powerpoint___

## Useful logs

{"name":"Internal Error","message":"An internal error has occurred.","code":3001}

**Comment by Rick-Kirkham** [comment]
@keyur32 The code works fine in Windows. Seems to be an iOS issue.

**Comment by catchingyu** [comment]
team start investigation on it.

**Comment by catchingyu** [comment]
bug 3723611 is used to track it.

**Comment by acblacktea** [comment]
@jasonhieu1905 Hi we are in investigation for this issue. We can repro this issue now. Could you share some your code example to us? manifest is not very useful to help us find the real problem :)

**Comment by jasonhieu1905** [comment]
@acblacktea : Basically, I've followed these step to create the project 
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/powerpoint-quickstart?tabs=yeomangenerator

My example code : https://github.com/jasonhieu1905/PowerpointUploader .
Feel free to drop here any question :)

**Comment by 2020Mar** [comment]
@jasonhieu1905 Hi, I am working on the issue you reported, as far as I know, the public document only introduce API
PowerPoint.createPresentation(base64File) for creating a PPT document, and actually it is a wrapper of createDocumentAsync. Could you help tell where do you find the API createDocumentAsync introduction?

**Comment by jasonhieu1905** [comment]
Hi @2020Mar : We know how to use **createDocumentAsync** API because  it during the preview phase for the feature. Now, we've tried with the latest code using  **createPresentation** api and it seems the issue still there.  ( https://github.com/jasonhieu1905/PowerpointUploader/blob/master/src/taskpane/taskpane.js). Note that the new **createPresentation** works fine on other environments.

![ezgif-3-adea93f268cd](https://user-images.githubusercontent.com/13063615/94550986-d2c20e80-027e-11eb-9b39-93e49a346fb2.gif)

**Comment by MartinSSeifert** [comment]
@catchingyu do you have any update on this - has this issue been fixed?
