### ISSUE TITLE
Excel.WorksheetCollection.addFromBase64  API(PreviewAPI) not working in excel online

### ISSUE THREAD

**Issue by px-wmeng** [OfficeDev/office-js#781]
I am using one preview API 'addFromBase64'  in Excel.WorksheetCollection class, it works fine in my installed Excel on PC, but not workING in excel online. it throws "NotImplemented" error. 
Do you know is this API not supported in Excel online, or it is a bug?
And also I would like to know when this preview API will be released?

Thanks,
Wei

**Comment by JuaneloJuanelo** [comment]
Known issue:  that's an API in preview and not yet available in Online. There is no clear ETA for this.
