### ISSUE TITLE
ContentControl.placeholderText isn't supported by Word in a browser.

### ISSUE THREAD

**Issue by jasonhieu1905** [OfficeDev/office-js#785]
## Expected Behavior
ContentControl.placeholderText should work fine in Word online, just like other hosts.

## Current Behavior
Exception : { code : "NotAllowed", message: "The action isn’t supported by Word in a browser. Check the OfficeExtension.Error.debugInfo for more information."}

## Steps to Reproduce, or Live Example
Script Lab : https://gist.github.com/jasonhieu1905/7f2af652e09800795ee2104dd14afbd3

Steps: following the Gists.
1. Insert a paragraph
2. Insert a content-control
3. Modify placeholderText.

Result : 
![2](https://user-images.githubusercontent.com/13063615/67073731-ed0bf500-f1b1-11e9-80b2-c3508c9e2c01.PNG)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ___Office Online___
* Host [Excel, Word, PowerPoint, etc.]: ___Word___

**Comment by weshi** [comment]
This is a known limitation for Word on the web. The content control placeholder cannot be changed from JS APIs.
