### ISSUE TITLE
Add-in disappears from Outlook when switching out-and-back-in to account

### ISSUE THREAD

**Issue by esegcy** [OfficeDev/office-js#786]
On Windows 10, Outlook 2016 Version 16.0.4849, setting up two email accounts: one with an add-in that is Centralized Deployed and the other is without this add-in, then switching between the two accounts causes the add-in to disappear.

## Expected Behavior
Expected that _always_ when switching to the account with the add-in, that add-in will appear. 
Of course I am testing the add-in according to its activation rules (meaning I expect it to appear when reading an email). I also tested when reading different emails and when opening an email in a new window

## Current Behavior
When switching to an account without the add-in, and then back to the account with the add-in, the add-in disappears. Only way to get it back is restart Outlook.

## Steps to Reproduce, or Live Example
1. Setup two different accounts on Outlook 2016 Version 16.0.4849 (Windows 10). Reproduced to me with one Office 365 (and no Exchange Server) and the other of Gmail.
2. Use Centralized Deployment to deploy an add-in from manifest file to the Office 365 account.
3. Restart Outlook to get the add-in to appear in the Outlook ribbon.
4. Switch to second account (without add-in). Add-in button in the Outlook ribbon does not appear, as expected.
5. Switch back to first account (with add-in). Add-in button in the Outlook ribbon doesn't re-appear (Bug).

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2016 Version 16.0.4849
* Operating System: Windows 10
* Browser (if using Office Online): -

**Comment by exextoc** [comment]
We have not been able to repro this so far. Could you include a screen shot or video to make sure we are using the same steps?

**Comment by esegcy** [comment]
Hi @exextoc - I am working on creating this. Sorry for the delay.

**Comment by esegcy** [comment]
Hi @exextoc - As such a recording with our add-in might be considered confidential to our company in matters of competition, can I email them privately to you somehow?

**Comment by AnjanaValsan** [comment]
Hello @esegcy ,
thank you for reporting this issue and also for your patience. 
This issue was fixed end of last week, Can you check and confirm?

**Comment by esegcy** [comment]
Hi @AnjanaValsan ,
Anything I should do in order to see this fixed? Update Outlook or something? If so, to which version/build-number?

Thanks.

**Comment by macOutlookExtensibility** [comment]
Hi, this was caused by a server side caching issue. So nothing much needed on the client side. Maybe you could just restart outlook. Can you check and confirm?

**Comment by esegcy** [comment]
Testing. Will update here.

**Comment by esegcy** [comment]
Looks ok on newer versions of Windows Outlook. Thanks.
