### ISSUE TITLE
Is there a way to get all recipients in `to` or `cc` fields?

### ISSUE THREAD

**Issue by yanli0303** [OfficeDev/office-js#788]
It is mentioned in documentation of `Office.MessageRead.to` that:

> The to property returns an array that contains an EmailAddressDetails object for each recipient listed on the To line of the message. The collection is limited to a maximum of 100 members.

This limitation is working correctly, if I have an message which was sent to more than 100 recipients, I can only get 100 of email addresses with `Office.context.mailbox.item.to`.

No similar limitation is mentioned in documentation of `Office.AppointmentRead.requiredAttendees`, but I can only get 100 of email addresses with `Office.context.mailbox.item.requiredAttendees`.

**Question**

I've tried to get recipients with both `Office.context.mailbox.item.to` and [REST API](https://docs.microsoft.com/en-us/outlook/add-ins/use-rest-api), I can only get 100 email addresses. **Is there a way to get a complete list of recipients?**

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac1d918e-05d2-cc06-1e2e-c2eda7dfb3ea
* Version Independent ID: d70d8e32-d63a-3e77-2fce-9cdf57633160
* Content: [Office.MessageRead interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-preview#feedback)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.messageread.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.messageread.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by yanli0303** [comment]
> Sorry, I'm digging into this a bit more. It looks like this may vary by client. For Desktop Outlook in Win32 (Outlook 2013, 2016 if updated all the way), the limit should be 500 recipients.
> 
> In what client are you seeing only 100 recipients come back? (I will try to follow up on my end as well, so we can get our documentation updated accordingly)

I was working with Microsoft Outlook for Mac Version 16.31 (19101400) (Office Insider Fast).
macOS Mojave 10.14.6

**Comment by ajays-msft** [comment]
closing old issue
