### ISSUE TITLE
Click spamming in protected excel sheet breaks JS flow

### ISSUE THREAD

**Issue by sethachoi** [OfficeDev/office-js#791]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
Thank you for your understanding and continued feedback.

Given a protected excel worksheet (in our case, recently protected via API), spamming clicks on the sheet itself breaks the flow of JS for the addin.

## Expected Behavior
JS should be executing uninterrupted, alternatively spamming click on a protected document shouldn't trigger edit mode error (see current behavior)

## Current Behavior
JS functionality stops executing from error. In script lab, the following error is thrown:
![image](https://user-images.githubusercontent.com/5778980/67155085-fe8df380-f2bc-11e9-929c-2352a64a8ee9.png)

## Steps to Reproduce, or Live Example
- Take existing or new sheet created, and protect it
- Sync
- In a timeout, unprotect the protected sheet
- When executing, spam click an excel cell or several cells while the sheet is still protected
- Sometimes (not always) the sheet never unlocks and throws the above error
- [Relevant scriptlab gist](https://gist.github.com/sethachoi/aba1552d50ddfbb3d1235c8832bb1144)

## Context
Our real world use case of this is to preload a sheet with data and attach event listeners to specific cells (IE if A1 emits a data changed event, do something) before allowing a user to interact with the sheet due to potential race conditions where the users are adjusting cells before our listeners are ready. We can't just do it from the start because our sheets + cell listeners are dynamically generated :/

I did consider the attaching listeners while protected might play a factor, but I've managed to reproduce the issue while completely removing that portion as well, as evidenced in the gist.

Also have reproduced it with protect({ selectionMode: 'none' }) in hopes that would negate it but it also borked.

Btw probably a far-ish edge case I know, but still who knows what end users will do ¯\_(ツ)_/¯

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Win Desktop with Office Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Operating System: Windows 10
* Browser (if using Office Online): Chrome 77.0.3865.120

## Useful logs
Copy paste of the console error:
```
Uncaught (in promise) RichApi.Error: Excel is in cell-editing mode. Please exit the edit mode by pressing ENTER or TAB or selecting another cell, and then try again.
    at new c (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:286433)
    at a.e.processRequestExecutorResponseMessage (https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:346713)
    at https://appsforoffice.microsoft.com/lib/1/hosted/excel-web-16.00.js:24:345089
c @ excel-web-16.00.js:24
e.processRequestExecutorResponseMessage @ excel-web-16.00.js:24
(anonymous) @ excel-web-16.00.js:24
Promise.then (async)
step @ (index):6
(anonymous) @ (index):7
__awaiter @ (index):3
(anonymous) @ (index):70
setTimeout (async)
(anonymous) @ (index):70
step @ (index):32
(anonymous) @ (index):13
fulfilled @ (index):4
Promise.then (async)
step @ (index):6
(anonymous) @ (index):7
__awaiter @ (index):3
(anonymous) @ (index):59
(anonymous) @ excel-web-16.00.js:24
Promise.then (async)
e._runCommon @ excel-web-16.00.js:24
e._runBatchCommon @ excel-web-16.00.js:24
e._runBatch @ excel-web-16.00.js:24
Vi @ excel-web-16.00.js:24
(anonymous) @ (index):59
```

**Comment by catchingyu** [comment]
I tried it with the below piece of code, and it does not reproduce on my machine. How often do you reproduce it?

$("#run").click(() => tryCatch(setup));

async function setup() {
  await Excel.run(async (context) => {
    let sheet = context.workbook.worksheets.getItem("Sheet1");
    console.log("run");
    sheet.protection.protect();
    await context.sync();
    await setTimeout(async () => {
      sheet.protection.unprotect();
      await context.sync();
    }, 5000);
  });
}

/** Default helper for invoking an action and handling errors. */
async function tryCatch(callback) {
  try {
    await callback();
  } catch (error) {
    // Note: In a production add-in, you'd want to notify the user through your add-in's UI.
    console.error(error);
  }
}

**Comment by sethachoi** [comment]
hi @catchingyu thanks for the response

It should break but it's hard to get it at first. Honestly with the minimum viable case (IE your/my test code) it's kind of hard to break and I have to click as fast as humanely possible with a mouse to get it, but once you figure it out you can reproduce somewhere between 1/2 the time to almost every time.

With code that has more complexity (and therefore more context.syncs()) it becomes far easier to reproduce, us being able to trigger it on accident instead of intentionally

**Comment by catchingyu** [comment]
team will try to reproduce it. It would be relatively hard if we can not consistently reproduce it.

**Comment by catchingyu** [comment]
track it with 3747321.

**Comment by topkoong** [comment]
Any update on this? @catchingyu
