### ISSUE TITLE
[Outlook add-in]we got "executeEntryPoint.tsx:39 Uncaught (in promise) TypeError: Cannot read property 'mode' of undefined" error

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#793]
we got "executeEntryPoint.tsx:39 Uncaught (in promise) TypeError: Cannot read property 'mode' of undefined" error since 2019/10/18 afternoon. This will cause we can't open add-in (even My Templates not work too) in a new meeting page without a page refresh.

## Expected Behavior
we could open add-in without page  refresh.

## Current Behavior
1. open a meeting page, then open a add-in and this time is work.
2. close this meeting and open a new meeting then open add-in will got an error.("executeEntryPoint.tsx:39 Uncaught (in promise) TypeError: Cannot read property 'mode' of undefined" )

Is there any update in 2019/10/18?? we can use add-in normal until 2019/10/18.

## Steps to Reproduce, or Live Example
1. open a meeting page, then open a add-in and this time is work.
2. close this meeting and open a new meeting then open add-in will got an error.

## Context
Now if we want to use add-in normal. We need refresh all the time.

If microsoft really make a update and can not find what the problem is please Version rollback. If it possible.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]:  Outlook
* Office version number: ______
* Operating System: win 10 and mac
* Browser (if using Office Online): Chrome

## Useful logs
executeEntryPoint.tsx:39 Uncaught (in promise) TypeError: Cannot read property 'mode' of undefined
    at executeEntryPoint.tsx:39
    at month:355
    at Object.next (month:355)
    at month:355
    at new Promise (<anonymous>)
    at f (month:355)
    at le (executeEntryPoint.tsx:24)
    at e.onClick (createOverflowContextMenuData.ts:10)
    at t.n._executeItemClick (ContextualMenu.base.tsx:1082)
    at n._onItemClickBase (ContextualMenu.base.tsx:1066)

**Comment by exextoc** [comment]
We are able to reproduced this issue. We are looking at this with high priority. Thanks for reporting this.

**Comment by SWei1234** [comment]
Now browser works fine. Thanks for your support.
