### ISSUE TITLE
[Excel - Custom Functions - Performance] Calculation of dependent custom function is too slow.

### ISSUE THREAD

**Issue by JRuncikInfor** [OfficeDev/office-js#794]
We use custom fictions heavily. When some of them depends on others custom function the performance is bad with long delay. 

## Expected Behavior
Ideally it should be fast as standard excel function = without significant delay.

## Steps to Reproduce
1) In script lab create simple function:
/**
 * Increments value.
 * @customfunction
 * @param {number} value
 * @returns The value + 1.
 */
function inc(value) {
  return (value + 1);
}

2) Register it.

3) On Excel sheet in cells put:
Cell coordinate 'A2'  "=SCRIPTLAB.BASICCUSTOMFUNCTION.INC(A1)"
Cell coordinate 'A3'  "=SCRIPTLAB.BASICCUSTOMFUNCTION.INC(A2)"
Cell coordinate 'A4'  "=SCRIPTLAB.BASICCUSTOMFUNCTION.INC(A3)"
Cell coordinate 'A5'  "=SCRIPTLAB.BASICCUSTOMFUNCTION.INC(A4)"
Cell coordinate 'A6'  "=SCRIPTLAB.BASICCUSTOMFUNCTION.INC(A5)"
Cell coordinate 'A7'  "=SCRIPTLAB.BASICCUSTOMFUNCTION.INC(A6)"

Type in cell A1 any number. E.g. 1... and you can see how slowly Excel recalculates it.
(Captured video how it behaves now: www.egtracing.cz/Work/Excel_CF_Performance.mp4)

## Context
This is common usage issue which restrict using custom function only for simple usage not as real custom functions.

## Your Environment
* Platform: Any [PC desktop, Mac, iOS, Office Online]
* Host: [Excel]:
* Office version number: 1910 (Build 12126.20000)
* Operating System: Win 10 1709 (Build 16299.1451)

**Comment by RuoyingLiang** [comment]
Thanks for reaching out. Yes, the perf is not good for dependent call in custom function(customer function’s parameter is another custom function). We will have further actions to improve this. Will back to this thread once we have update.

**Comment by JRuncikInfor** [comment]
I am looking forward.
Thanks Jarda

**Comment by JRuncikInfor** [comment]
Please, in which version will be the fix available?
Thanks Jarda

**Comment by 4tti** [comment]
@RuoyingLiang  can we get information in which version it was fixed cause I checked the behavior recently and it seems to be same (at least in separated runtime).
