### ISSUE TITLE
Any plans to bring custom functions to perpetual licenses?

### ISSUE THREAD

**Issue by gappyp** [OfficeDev/office-js#795]
Subject says it all :)

(Re content in:  [Custom Functions requirement sets - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-requirement-sets#feedback))

**Comment by kbrandl** [comment]
I've transferred this issue to the **OfficeDev/office-js** repo, so that someone from the product team can respond to this question. @RuoyingLiang can you please provide feedback? Thanks!

**Comment by keyur32** [comment]
Ack! Thanks Kim and sorry I missed this. Currently we don't have any plans to backport this to previous versions of Excel. It is currently only available through accounts connected to Office 365 subscriptions. Will let @RuoyingLiang follow up if this is something we can address in the future

**Comment by kbrandl** [comment]
@keyur32 thanks for the input on this one! I'm going to go ahead and close this issue (since you've provided a response), but @RuoyingLiang please feel free to comment here if you have anything else to add. Thanks!

**Comment by jjtfsalgado** [comment]
May I ask whats the reason to target just Office 365 subscriptions? Most of our customers are complaining about that fact. The majority of them don't use Office 365 and put us in this limbo where we have an add-in but nobody can use it. It's a big constrain for us.

**Comment by 4tti** [comment]
@jjtfsalgado : FYI there's closed user voice with 150 votes https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/36915445-provide-update-for-retail-version-of-office-2019

**Comment by jjtfsalgado** [comment]
@4tti thanks for letting me know
