### ISSUE TITLE
Outlook Office.context.ui.closeContainer() does nothing in Read mode

### ISSUE THREAD

**Issue by bchenhs** [OfficeDev/office-js#796]
From the taskpane, calling `Office.context.ui.closeContainer()` in read mode does not close the taskpane and does not return any error.

The same method works when called from compose mode.

## Expected Behavior
Office.context.ui.closeContainer() closes the taskpane.

## Current Behavior
Office.context.ui.closeContainer() does not close the taskpane, and does not yield any errors.

## Context
We are adopting the pinnable taskpane feature, and would like to temporarily close the taskpane when there are no mail item selected. The mechanism through `closeContainer()` only works for compose mode at the moment and we expect it to work consistently on both read and compose modes.

## Platform
Online, Office365
Chrome latest version on macOS Mojave

**Comment by exextoc** [comment]
Thank you for the issue report and scenario description.

On which platform and Outlook version do you see the read mode `closeContainer()` issue?

I believe closeContainer() won't work for your scenario because the add-in task pane is unpinned when it's closed, including when it's closed with `closeContainer()`. From the [closeContainer documentation](https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=word-js-preview#closecontainer--):

> Called from a task pane: The task pane will close. Any dialog opened by displayDialogAsync will also close. If the task pane supports pinning and was pinned by the user, it will be un-pinned.

**Comment by bchenhs** [comment]
Hi @exextoc, I've updated the issue with platform data. It is observed on Office 365 online (outlook.office.com) running in Chrome, macOs Mojave.
This issue happens with the taskpane pinned. It works (successfully closes the taskpane) when `Office.context.mailbox.item` is a compose item, but not when it is a read item.

**Comment by Tolik7** [comment]
Yes, I confirms this issue too! 
Do you have any progress, guys?

**Comment by exextoc** [comment]
1. Can you check if you are getting any console errors when calling closeContainer? If yes, can you share the error.
2. We tried to repro the issue on platform and outlook version mentioned. We are unable to repro it at out end. Is it possible to share the stripped down version of the add-in or some sample add-in to repro the issue.

**Comment by Tolik7** [comment]
I noticed, it seems Office.context.ui.closeContainer() works fine via corporate email (https://outlook.office.com/mail/). In this case I see my window to the right of the body of email letter!
BUT
it seems this issue relates to own OutLook Web Server (customer uses own ip in local network, for ex https://10.10.10.99/owa/#path=/mail). 
In such case I see a window below the body of the letter and got this issue! 
See my attached pics please. 
![action1](https://user-images.githubusercontent.com/4079690/67934768-918e2e00-fbd9-11e9-9c88-a34f0c9652a7.png)
![action2](https://user-images.githubusercontent.com/4079690/67934769-918e2e00-fbd9-11e9-86a7-ca554875fe54.png)

Note,
In first case to add new addin Im doing: open any email -> more action-> get apps/addin->my apps/addin-> from file.  and
in second case  to add new addin Im doing: Account->Options->apps->add from file

**Comment by Tolik7** [comment]
I used the latest Chrome browser in both cases.

**Comment by exextoc** [comment]
It seems like you are using grey Bar add-in, so as per below documentation these has been deprecated (scroll to bottom):
https://developer.microsoft.com/en-us/outlook/blogs/make-your-add-ins-available-in-the-office-ribbon/

If possible please convert your add-in to a taskpane add-in and start using it.

**Comment by bchenhs** [comment]
@exextoc I am using a taskpane add-in. There are no console error observed when the issue happens. Here is a code snippet:

Office.onReady().then(() => {
  Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged, () => {
    if (!Office.context.mailbox.item) {
      Office.context.ui.closeContainer()
    }
  })
});

To repro:
- Open a message in inbox to read
- navigate to a different folder (e.g. draft)
- closeContainer should be called, with no effect.

**Comment by exextoc** [comment]
The image attached above in which add-in is coming on bottom of page is greybar add-in only. is it the same you are using ?

**Comment by bchenhs** [comment]
No, our add-in is a taskpane that appears on the right.

**Comment by exextoc** [comment]
@bchenhs Why are you trying to close the add-in task pane, when there is no item in view?
Office APIs are expected to work with the item in preview.
In this case, you are trying to execute `Office.context.ui.closeContainer()`, when there is no item in preview. 
Can you try executing this outside of `if (!Office.context.mailbox.item)` and see if the API works?

**Comment by bchenhs** [comment]
@exextoc We would like to make our add-in to not take up space (i.e. close the taskpane) when there is no mail item in view. This mechanism in the code snippet above works when the last viewed item is a "compose". Is there a specific reason why it doesn't work for "read"?

**Comment by exextoc** [comment]
Wanted to let you know that if you call closeContainer, as per the [documentation](https://docs.microsoft.com/en-us/javascript/api/office/office.ui?view=outlook-js-preview#closecontainer--) your add-in will be un-pinned. 
It is Outlook's UI guidance to display a warning saying that "You need to select a message before you can use the add-in." and it is not recommended to hide this pane.

> Called from a task pane: The task pane will close. Any dialog opened by displayDialogAsync will also close. If the task pane supports pinning and was pinned by the user, it will be un-pinned.

**Comment by bchenhs** [comment]
It doesn't un-pin the taskpane right now, even when it works from a compose. Looks like there is a bug either way.

**Comment by exextoc** [comment]
Add-in not getting unpinned in Outlook Online has been put on our backlog. We unfortunately have no timelines to share at this point. 
But It is recommended to not call closeContainer() because once the fix for that is out, your add-in will get unpinned unnecessarily.
