### ISSUE TITLE
Outlook web add-in load error "This add-in could not be started ..."

### ISSUE THREAD

**Issue by jesyxue** [OfficeDev/office-js#797]
It shows one error message when the user click my outlook web add-in.

ADDIN-ERROR :

This add-in could not be started. Close this dialog to ignore the problem or click "Restart" to try again.

It is not responding even if I click the "Restart" button.

This issue is only happening on Outlook 2016 for Windows.
Outlook 2016 1908

Note:
It works on browser IE, Chrome and Edge. So it was not blocked by firewall.
And not only my add-in doesn't work, but also the standard add-in "My Template" cannot work too. The same error was reported. Clear outlook client cache, it still cannot work.
Any feedback for this issue?

**Comment by jesyxue** [comment]
> Hi @jesyxue,
> Thanks for reporting this. It appears to be a product issue, not a documentation issue. I'm going to transfer this to the product GitHub repo (https://github.com/OfficeDev/office-js). There, members of the product team can diagnose the underlying issue.

Thanks for your support.

**Comment by exextoc** [comment]
Thanks for providing details about the issue. Since other add-ins (i.e. My Templates) are not working as well, try these steps to resolve the issue:
https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/apps-for-office-not-start

> Re-enable protected mode for Restricted Sites: 
> 
> - In Internet Explorer, click the Tools button, and then click Internet Options.
> - Click the Security tab, and then select the Restricted SitesZone.
> - Select the Enable Protected Mode check box, and then click OK.
> - Restart Internet Explorer.

**Comment by jesyxue** [comment]
@exextoc This is an issue that reported from our customer. They have already do the above steps but it still cannot work now. Any other suggestion? It was just happened on outlook 2016 1908 client, and it works on browser IE, edge and chrome. Thanks.

**Comment by exextoc** [comment]
@jesyxue Can your customer try an add-in in another client such as Microsoft Word or Excel? Here are instructions for [installing and running an add-in in Excel](https://support.office.com/en-us/article/get-an-office-add-in-for-excel-d3df5854-0a4e-4169-9cc3-25177a288d3d#ID0EAABAAA=Newer_versions). This will help us determine whether this is specific to Outlook or common across all Office clients.

**Comment by jesyxue** [comment]
@exextoc Click Microsoft outlook sample add-in "My Template", the same error was popped up. Thanks.

**Comment by exextoc** [comment]
@jesyxue Did you try this add-in in Word or Excel? I'm asking you to specifically try an add-in Word/Excel to see if this issue also occurrs for those clients.

**Comment by exextoc** [comment]
One additional option to try is to enable Protected Mode for `Internet` as well. This shouldn't be required, though I've heard a report of it helping in one case.

**Comment by jesyxue** [comment]
@exextoc Sorry, we just have outlook add-in so cannot verify it in Word or Excel. What's other reason that can block add-in load in windows outlook client?

**Comment by SWei1234** [comment]
@exextoc Has the problem been positioned yet? Or still need more information? Or already in processing?  Any update?

**Comment by exextoc** [comment]
Usually when you see this error, it means that the Outlook client was unable to reach your web server. Can you verify that your web-page is reachable?

**Comment by SWei1234** [comment]
> Usually when you see this error, it means that the Outlook client was unable to reach your web server. Can you verify that your web-page is reachable?

sorry for reply late.
Yes.  It's works well on OnlineOffice on browser.  So I think the web-page is reachable. But on outlook client that didn't work.  It's a strange problem.

**Comment by exextoc** [comment]
Since it works Online, but not windows desktop. We have a few suggestions to identify the problem.
1. Please check [add-in debugging page](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/debug-add-ins-using-f12-developer-tools-on-windows-10) to see if there is some error message showing up.
2. Please provide fiddler trace log to us for further investigation.
3. As suggested before, it will help if you can follow [the instructions](https://support.office.com/en-us/article/get-an-office-add-in-for-excel-d3df5854-0a4e-4169-9cc3-25177a288d3d#ID0EAABAAA=Newer_versions) to verify whether add-ins can run on your Excel.  You don't need have your own Excel add-ins, they can be installed from office store.

**Comment by SWei1234** [comment]
@exextoc yes, we have had a meeting with our customer recently. And we found that some setting in IE will cause Outlook localStorage access denied. Then we tried close protect mode and set default security level but it doesn't work.(The machine that has the problem will still have a problem, and the machine that does not have the problem will not make a mistake. )
So I have a question : How do I need to set up to appear localstorage access denied? Can microsoft give us some suggestion or wiki?

**Comment by SWei1234** [comment]
@exextoc yes, we have had a meeting with our customer recently. And we found that some setting in IE will cause Outlook localStorage access denied. Then we tried close protect mode and set default security level but it doesn't work.(The machine that has the problem will still have a problem, and the machine that does not have the problem will not make a mistake. )
So I have a question : How do I need to set up to appear localstorage access denied? Can microsoft give us some suggestion or wiki?

**Comment by exextoc** [comment]
Can you confirm that your customer is using IE instead of Edge WebView by checking their Windows versions here https://developer.microsoft.com/en-us/office/blogs/microsoft-edge-webview-for-office-add-ins/

**Comment by SWei1234** [comment]
> Can you confirm that your customer is using IE instead of Edge WebView by checking their Windows versions here https://developer.microsoft.com/en-us/office/blogs/microsoft-edge-webview-for-office-add-ins/

Our users haven't used the latest version of the Outlook. So the IE setting still have affect on Outlook. So I still need to know the question above?

**Comment by exextoc** [comment]
We are not sure how to reproduce the Access Denied error for `localStorage`, however you can try disabling DOM Storage in IE by clicking on the **Settings** icon, then **Internet Options**, switch to the **Advanced** tab, then under the **Settings** section, scroll down to the **Security** subsection and uncheck **Enable DOM Storage**.

**Comment by SWei1234** [comment]
@exextoc 
Can you help me confirm will this problem happening on 
Windows： 1909 18363.1082
Outlook: 2002 12527.21104 
We met this problem on this environment.
And I tried reset IE security configuration, and restart IE and outlook.
Confirmed that localStorage can read and write. And cleaned the cache every time.
Any idea?
Thanks

**Comment by exextoc** [comment]
We would like to determine whether this is specific to Outlook or common across all Office clients. Can your customer try installing any add-in from the store such as Scriptlab in another client such as Microsoft Word or Excel?
