### ISSUE TITLE
getSelectedDataAsync returns string null when no text is selected on Outlook on the web

### ISSUE THREAD

**Issue by wandyezj** [OfficeDev/office-js#800]
on Outlook on the web when no text is selected getSelectedDataAsync result.value.data value is string null.

I was surprised!

It might be reasonable to make a note of the unexpected behavior in the documentation or if possible fix the issue.

Actual:
"null"

Expected:
""

Code to reproduce and work around the issue:
```typescript
async function getSelectedTextOutlook() {
    return new Promise&lt;string&gt;((resolve) =&gt; {
        Office.context.mailbox.item.getSelectedDataAsync(Office.CoercionType.Text, (result: Office.AsyncResult&lt;any&gt;)=&gt; {
            const value = result.value;
            
            // outlook returns string "null" if no text is selected.
            const isEmpty = value.endPosition === value.startPosition;

            const selectedText = isEmpty ? "" : value.data;
 
            resolve(selectedText);
        });
    });
}
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbb2ef5c-e278-6aba-6fe8-7a4cc0e357d5
* Version Independent ID: ebc95637-b567-86b8-4f6d-ee9c6afee19e
* Content: [Office.context.mailbox.item - requirement set 1.5 - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item#feedback)
* Content Source: [docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/reference/objectmodel/requirement-set-1.5/office.context.mailbox.item.md)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding getSelectedDataAsync API issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by ElizabethSamuel-MSFT** [comment]
The documentation portion of this issue has been addressed. When the product bug is fixed, we can update the docs to remove the note about the OWA bug and the associated sample code on handling the bug.

**Comment by ElizabethSamuel-MSFT** [comment]
The OWA bug has been fixed.

@wandyezj Thanks again for raising this issue.
