### ISSUE TITLE
CDN for office js in China

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#801]
The office js CDN is global

## Current Behavior

In China,we noticed that ips from japan are blocked on our network which prevents we from accessing office.js .

## Context

some time is fine, but some time is block. if the ip from jp,it's block.
i think the cdn of office.js has not in china. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: _PC desktop_____
* Host [Excel, Word, PowerPoint, etc.]: ___Excel___
* Office version number: __version 1909 (build 12026.20334)____
* Operating System: __windows 10____
* Browser (if using Office Online): ______

## Useful logs

The connection to 'appsforoffice.microsoft.com' failed.
Error: TimedOut (0x274c).
System.Net.Sockets.SocketException 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 23.65.187.233:443

**Comment by sumurthy** [comment]
We do have edge server coverage across globe - but coverage in China may be lacking. One other option is to use the [offline copy](https://www.npmjs.com/package/@microsoft/office-js) and keep up with the versions. We'll follow-up on the CDN coverage as well.

**Comment by sumurthy** [comment]
We are still in the process of inquiring. We have also added this to our backlog. @kbrandl how do we deal with such issues (ones in the backlog?) Do we keep them open and update it at a later time?

**Comment by lindalu-MSFT** [comment]
@sumurthy Please leave issue open and if we are tracking it internally with an ADO bug, please log the number here for cross-reference. Thanks!

**Comment by sumurthy** [comment]
At this point, the CDN inside of China or other protected region is not in-scope. We have this in the backlog - but we don't intend to add local CDN support. The best option would be to periodically get the latest NPM version of Office.js.
