### ISSUE TITLE
Word: closeContainer method not working for word

### ISSUE THREAD

**Issue by biswanathc** [OfficeDev/office-js#805]
I am working on word addin. On click of button I want to unload the sideloaded window. For this I am using below method.

function closeWindow() 
{
 Word.run(function (context) 
{ 
Office.context.ui.closeContainer(); 

 return context.sync(); 
}) 
.catch(errorHandler); }

Problem is I am getting null reference exception on calling closeContainer method. Also, in debug mode I see the closeContainer method is not showing under UI class. Could you let me know what is the issue here?

**Comment by biswanathc** [comment]
Any update on this please?

**Comment by biswanathc** [comment]
Any update please?

**Comment by biswanathc** [comment]
@weshi  Could you help please

**Comment by lliu113** [comment]
@biswanathc - this is by design. closeContainer() will only close the taskpane if it is called from within the taskpane. We currently don't support closing a taskpane from a ribbon button.

**Comment by lindalu-MSFT** [comment]
Closing issue **resolution: by design**. Please feel free to reopen if you have questions.

**Comment by junaid042** [comment]
> @biswanathc - this is by design. closeContainer() will only close the taskpane if it is called from within the taskpane. We currently don't support closing a taskpane from a ribbon button.

I am trying to close my taskpane from taskpane code but I am getting this error in word add-in
![image](https://github.com/user-attachments/assets/da19f489-c550-4b4c-a0b9-f4a3e02ec08d)
