### ISSUE TITLE
Excel stuck in cell editing mode even when the user clicks the task pane

### ISSUE THREAD

**Issue by edwardcawley** [OfficeDev/office-js#806]
The user clicks a cell then changes its value. They then immediately click a button in the task pane e.g. to save or update or load a new report. The code hangs as it waits on a context.sync() which uses delayForCellEdit true.

It will then continue if the user clicks on another cell in the sheet. This is awkward behavior - when the user clicks in the task pane the cursor stops flashing in the cell. I would assume at this point the cell is no longer being edited but it seems that that event isn't triggered until another cell is clicked. It currently seems the only way around this is a message to the user asking them to click another cell.

I have attached an example - if you click test the message "Code run." should show.

Refresh the pane to get the button back then type into a cell. Don't push return or change cells, instead click test and you should see the problem.
[test.zip](https://github.com/OfficeDev/office-js/files/3779358/test.zip)

Windows 10, Excel Office Insider version 1991 Build 12209.20010

**Comment by RuoyingLiang** [comment]
@lumine2008 could you help to triage if this is an issue and still existing?

**Comment by lumine2008** [comment]
Yes, this bug still exist, we have a bug 4216350 for this issue.

**Comment by donlvMSFT** [comment]
This issue already been fixed based on bug status, and released with Office with 16.0.14702.37375, please help verify. 
I'd like to close this thread, thank you!
