### ISSUE TITLE
Office.context.mailbox.item.getEntitiesByType(Office.MailboxEnums.EntityType.Contact) returns empty array

### ISSUE THREAD

**Issue by hectorAmaral** [OfficeDev/office-js#807]
## Expected Behavior
Calling `Office.context.mailbox.item.getEntitiesByType(Office.MailboxEnums.EntityType.Contact)` on Outlook Add-in taskpane should return the selected email item contacts array
## Current Behavior
Both `Office.context.mailbox.item.getEntitiesByType(Office.MailboxEnums.EntityType.Contact)` 
and `Office.context.mailbox.item.getEntities().contacts` are returning empty array.

## Steps to Reproduce, or Live Example
I'm using an Office 365 account.
* Additional details:
  1. Create a new contact with full name, email, job title, phone and company on Outlook for Desktop or Office Online
  2. Send a new email to the newly created contact.
  3. Go to the "sent" folder and select the sent email.
  4. Open your Outlook Add-in taskpane with the following code implemented:`Office.context.mailbox.item.getEntitiesByType(Office.MailboxEnums.EntityType.Contact)` 
  5. Log to the console the result of the getEntitiesByType method.
  6. Notice it logs an empty array.

## Context
I'm developing an Outlook task pane Add-in using React.
I'm calling the `Office.context.mailbox.item.getEntitiesByType(Office.MailboxEnums.EntityType.Contact)` on the `componentDidMount` event.
I have the ReadWriteMailbox permissions level on the Manifest file.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Outlook for Desktop and Office Online.
* Office version number:  Outlook for Office 365 MSO (16.0.12026.20344) 64-bit
* Operating System: Windows 10 Enterprise Version 1903 OS build 18362.418
* Browser (if using Office Online): Google Chrome Version 78.0.3904.70 (Official Build) (64-bit)

**Comment by johnkreagan** [comment]
I've seen this issue as well

**Comment by EdTech101** [comment]
I'm experiencing the same issue.

**Comment by exextoc** [comment]
That is the expected behavior. If you want to retrieve the `sender` or `recipients`, we have separate APIs for that. The `Contact Entity` type represents any contacts that were found in the body of the message. See documentation for [Office.contact interface](https://docs.microsoft.com/en-us/javascript/api/outlook/office.contact?view=outlook-js-preview).

**Comment by hectorAmaral** [comment]
Hi @exextoc , thanks for the response. 
Well, the Office.contact interface documentation reads as follows:

> Represents a contact stored on the server. Read mode only.
> 
> The list of contacts associated with an email message or appointment is returned in the contacts property of the Office.Entities object that is returned by the getEntities or getEntitiesByType method of the active item.

it doesn't mention anything about contacts in the body of the message.

What do you mean by _any contacts that were found in the body of the message_ exactly? 
Do you mean contact files (vcf) attached to the document?

What we're trying to achieve is to get the email recipients' contact information such as Full Name, Company Name (Business Name), Phone Number(s), Address(es). 
I
f there a way to achieve what a just mention above? 
We thought the `Office.context.mailbox.item.getEntitiesByType(Office.MailboxEnums.EntityType.Contact)`  method was the way to go.

Thank you.

**Comment by exextoc** [comment]
The documentation is confusing. We will get it fixed. In the documentation for Office.contact, there's a comment in the code sample that reads `// Get an array of strings that represent contacts in the current item's body.` That is what the API is meant for.

We don't have any API to provide you with what you are trying to obtain. However, we have an API to obtain the list of [recipients](https://docs.microsoft.com/en-us/javascript/api/outlook/office.recipients?view=outlook-js-preview). You can then use the [Microsoft Graph API](https://docs.microsoft.com/en-us/graph/api/contact-get?view=graph-rest-1.0&tabs=http) to retrieve the details of each contact.

**Comment by hectorAmaral** [comment]
@exextoc Could you please give me an example of a _contact in the current item's body_. That is still confusing for me. 
Does it mean embedded contact files (vcf)?
How can I include a contact in the body of the email?

Thank you.

**Comment by exextoc** [comment]
This doesn't refer to embedded contact files. A simple example will be an e-mail containing a signature of the sender, or basically the information you usually see on a physical contact card. An example of such an e-mail is below. **This functionality is non-existent at the moment**. However, to answer your question, here's an example of an e-mail containing a Contact entity. The signature portion contains all the necessary information for a Contact entity. I don't think this is the scenario you are trying to achieve.

_Hi there, I have received the package._

_Thanks._
_John Smith_
_Contoso Corporation_
_1 Contoso Way, Redmond, WA 98052_
_john.smith@contoso.com_
_206-111-1111_
_https://github.com/contoso/john.smith_

**Comment by ElizabethSamuel-MSFT** [comment]
@hectorAmaral Apologies for the confusion around this. We've refined the Contact description and included the sample email in our code example in the [Contact interface reference documentation](https://docs.microsoft.com/javascript/api/outlook/office.contact?view=outlook-js-preview). Let us know if you have any further questions.

I'll go ahead and close this issue now.

Thanks.
