### ISSUE TITLE
Excel Add-in. ADD-IN ERROR. This add-in could not be started. 

### ISSUE THREAD

**Issue by vitalcode** [OfficeDev/office-js#808]
I released an Excel adding around a year ago. 

Recently, users start reporting the issue. They cannot load adding. Instead following message is shown:

ADD-IN ERROR. This add-in could not be started. Close this dialog to ignore the problem or click "Restart" to try again.  

Users did not have this issue before, the issue started when they install Windows or Excel updates. All users have similar environment. See below example, but all users have almost identical Windows and Excel build versions. 

Windows 10 Pro
Version: 1903
Build: 18362.418

Excel 365 MSO (16.0.12026.20334) 32-bit
Version: 1909
Build: 12026.20320

I did install exactly the same environment on my VM, but cannot reproduce this issue. 

Thank you.

![VitalTax](https://user-images.githubusercontent.com/1747219/67718152-11907a00-f9c7-11e9-95e7-05063e526912.JPG)

**Comment by lumine2008** [comment]
Thanks @vitalcode for reporting this issue, is your add-in released in store? could you please share us the name of the add-in? if not, could you please share the manifest of the add-in? thanks

**Comment by vitalcode** [comment]
Thank you @lumine2008.
The Add-in is published in store. Here is a link: https://appsource.microsoft.com/en-us/product/office/WA104381859?src=office&corrid=6c2508da-dfaa-4628-a4fe-a53800c79cb9&omexanonuid=7ac04092-5aee-4941-95d0-638244f0e20a&referralurl=

**Comment by glenboy617** [comment]
Hiya I have same problem is there a fix

**Comment by lumine2008** [comment]
@vitalcode may i know whether this issue still repro for now?

**Comment by lumine2008** [comment]
I'm going to close this issue for now, please reactivate if you're still seeing this. If you can provide snippet/gist to help us test that would be extremely helpful. Thanks
