### ISSUE TITLE
Error resetting font highlight color via WordApi 1.1

### ISSUE THREAD

**Issue by morgan-tr** [OfficeDev/office-js#809]
## Expected Behavior
Using WordApi 1.1, I expect the font highlight color to be reset when a `null` value is used as per the [documentation](https://docs.microsoft.com/en-us/javascript/api/word/word.font?view=word-js-preview#highlightcolor).

## Current Behavior
Instead of the font highlight color being reset, an InvalidArgument error is thrown (errorLocation: Font.highlightColor). 

## Live Example
ScriptLab example:
https://gist.github.com/morgan-tr/cee3978a5b977dbac8792b1e2e6a0aaa

## Context
Our add-in highlights certain paragraphs in the document to emphasize certain information. We also need to be able to reset the highlighting.

Our clients use a volume license version of Word 2016 (Build 16.0.4849.1000), which is supposed to have full support for WordApi 1.1.

## Your Environment

* Platform: PC desktop
* Host: Word
* Office version number: Word 2016 - Build 16.0.4849.1000
* Operating System: Windows 10

## Useful logs
```
{description: "InvalidArgument", name: "RichApi.Error", code: "InvalidArgument", traceMessages: Array[0], innerError: null…}
 description: "InvalidArgument"
 name: "RichApi.Error"
 code: "InvalidArgument"
 traceMessages: Array[0]
 innerError: null
▶debugInfo: Object
 code: "InvalidArgument"
 message: "InvalidArgument"
 toString: function ()
 errorLocation: "Font.highlightColor"
 stack: "InvalidArgument: InvalidArgumentat Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:24:286471)at o (https://script-lab-runner.azureedge.net/static/js/1.30a5fcfe.chunk.js:1:2779072)at Anonymous function (https://script-lab-runner.azureedge.net/static/js/1.30a5fcfe.chunk.js:1:2779219)at u (https://script-lab-runner.azureedge.net/static/js/1.30a5fcfe.chunk.js:1:314565)}"
```

[StackOverflow issue](https://stackoverflow.com/questions/58606190/resetting-font-highlight-color-via-wordapi-1-1-throws-an-invalid-argument-except)

**Comment by weshi** [comment]
I tried with your sample on both Word on the Web and Windows, they both can work correctly to clear the highlight color. Could you try it with latest version of Word on desktop and see whether you can reproduce it? This will help us narrow down the scope of the issue and see if it is related to a specific version, or it's related to other cause. Thanks.

**Comment by morgan-tr** [comment]
@weshi The problem will not be reproducible in the latest version of Word on desktop nor in the online version. As specified in the environment section, the problem happens specifically in the volume license version of Word 2016 on Windows (Build 16.0.4849.1000). Please try to reproduce it in that version.

Our clients use this version, which is only compatible with WordApi 1.1, and so we must support it.

**Comment by morgan-tr** [comment]
@weshi Is there any update on this? Were you able to reproduce the issue in a volume license version of Word?

**Comment by weshi** [comment]
I found out that there was a related bug which has already been fixed about two years ago, and it should be included in build version later than 16.0.7526.1000. However since this is not a hot fix bug (which requires to meet specific criteria), if you use older version build, you will not get the fix. You will have to update to later version of Office if this is blocking your scenario.

**Comment by morgan-tr** [comment]
@weshi The volume license version of Office 2016 that our clients use is build 16.0.4849.1000, which is the **latest available version for the volume license**. Clients using the volume license of MS Word **cannot update** to 16.0.7526.1000 (if there is a way to do so, please let me know how). 

Otherwise, are you suggesting we tell our clients to buy hundreds of Office 2019 volume licenses because of an unfixed bug? 

If there is no way to update the volume license to 16.0.7526.1000, and you already have a solution to the bug, why not release a fix for the volume license too?

Can you provide a link to download build 16.0.7526.1000? I can't find it online except on websites in Arabic, and it's not available on the [MS Update catalog](https://www.catalog.update.microsoft.com/) either.

**Comment by weshi** [comment]
@morgan-tr: Is there any possibility to call other APIs to work around this bug, and still achieve the goal of your scenario? Waiting for a new patch update might take a longer time even the bug meets the criteria for a monthly update. 
BTW, are you using Office365? Or you are under on-prem environment? Office365 users can always get free update to latest version of desktop clients.

**Comment by morgan-tr** [comment]
@weshi Our add-in is limited to using WordApi 1.1 because we must support the volume license version of Office 2016 (build 16.0.4849.1000 - the latest available).

The ability to reset the highlight on paragraphs is crucial. Our clients typically work with "Track Changes" on. This means that when a paragraph is highlighted, it will be registered as a change to the document. Therefore, when the highlight is removed, the change will also be removed.

At the moment, we're forced to set the highlight colour to white instead of resetting it because the bug in WordApi 1.1 does not accept "null" as a value.

This means that when tracking changes, the highlight will be changed to "Yellow" and then to "White" (instead of to "Yellow" and then back to no highlight).

Our clients do not use Office 365 - they have purchased one-time volume licenses, as many enterprise corporations do.

This is clearly a bug with WordApi 1.1, since the [documentation](https://docs.microsoft.com/en-us/javascript/api/word/word.font?view=word-js-preview#highlightcolor) states: "To remove highlight color, set it to null."

May I ask what is the criteria for a monthly update, because this should be a straightforward fix and is quite crucial?

**Comment by weshi** [comment]
@morgan-tr I'll follow up with our internal team on this and will get back. Thanks.

**Comment by morgan-tr** [comment]
@weshi Could you please provide an update on this issue?

**Comment by weshi** [comment]
@morgan-tr After internal discussion, this bug does not meet the bar for backporting to the older version build.

**Comment by morgan-tr** [comment]
@weshi Thank you for looking into this.

@kbrandl Hi Kim - I see you're listed as a participant on this thread. I was hoping to get your input on this as I believe you're in charge of the developer experience.

We've had to add support to our add-in for WordApi 1.1 because many enterprise clients use a volume license version of Word 2016 and MS won't release a build for it that upgrades the support to WordApi 1.3. This means out clients are stuck with 1.1 unless they purchase Office 2019 licenses.

This bug with WordApi 1.1 renders a primary feature - highlighting paragraphs - unusable since the highlighting cannot be reset. Could you please explain why a bug like this won't be fixed or at least why support for WordApi 1.3 not added to the volume license of Word?

Thanks,

Morgan

**Comment by kbrandl** [comment]
@morgan-tr thanks for sharing your perspective on this; I can certainly understand your concerns. That said, I'm actually not the right person to provide the type of feedback you're seeking. (Although I care deeply about developer experience, I primarily own responsibility for creating Office Add-ins developer documentation, and am not involved in deciding which fixes get backported.) @sumurthy are you perhaps able to provide input here, or if not, redirect to someone else who can?

**Comment by sumurthy** [comment]
Porting fixes to prior versions is a fairly large undertaking. It is mainly due to the concerns around making changes to a stable build and the threshold that the bugs need to meet in order for us to recommend the fixes on older/stable builds of Office. 
In addition, some of the fixes may use features not yet present in older builds and hence makes it harder technically to port all dependencies. Due to that reason, we don't fix non security/privacy related bugs on older builds.

**Comment by morgan-tr** [comment]
@kbrandl Thank you for your response and for involving the right person.

@sumurthy Thank you for the explanation.
