### ISSUE TITLE
Outlook web add-in disappeared from Admin deployment list

### ISSUE THREAD

**Issue by jesyxue** [OfficeDev/office-js#810]
@exextoc 
At beginning of Oct,22 my Add-in disappeared from Admin deployment list. Then when I re-add, I got an error stating "This add-in has previously been uploaded. Please edit the existing add-in.(23f8b179-25cc-4236-b9f2-07e23bbdaf58)". I know that it means the add-in has been deployed. But I cannot find it in new Admin center deploy list and Exchange admin-> Organizer -> Add-ins list. Any suggestion for this issue? Many customers report this issue at beginning of last week.

## Expected Behavior
The add-in show in admin deploy list. And can be remove, add again.

## Current Behavior
I cannot find it in new Admin center deploy list and Exchange admin-> Organizer -> Add-ins list. But when I add the add-in again, it failed and got the error "This add-in has previously been uploaded. Please edit the existing add-in.(23f8b179-25cc-4236-b9f2-07e23bbdaf58)".

**Comment by ElizabethSamuel-MSFT** [comment]
@jesyxue Thanks for raising this issue.

@exextoc Can you take a look?

Thanks.

**Comment by EnoXirtaMinu** [comment]
I have the same issue. An Outlook add in that had been previously deployed cannot be found in the list anymore. When trying to add again it says it is already there and to edit the existing, which is not possible...

EDIT: the add in is visible when accessing through the Exchange admin center 'add-in's. It seems that those have not been migrated to the new central add-ins admin center.  After removing it there, I can add it the new way.

**Comment by exextoc** [comment]
We have fixed this issue.

**Comment by jp8899** [comment]
@EnoXirtaMinu Solution worked, wasn't showing in the 365 admin centre add-ins, but was showing in exchange admin centre.  Odd.  Thanks for the help all these years later!
