### ISSUE TITLE
Dialog API sometimes opens two dialogs on Android

### ISSUE THREAD

**Issue by TheSamsterZA** [OfficeDev/office-js#811]
## Expected Behavior

I expect one dialog to open on Android.

## Current Behavior

If I open a dialog then close it (by tapping the close button) enough times, I see a second, blank dialog that looks to be stuck at a loading stage.

This does not seem to affect messages from the dialog I intended to open; that is, I open a dialog to my auth provider which redirects back with an auth token, and after I close the blank dialog I can see that my add-in has logged in in the background.

## Steps to Reproduce, or Live Example

* Link to live example: https://github.com/TheSamsterZA/office-js-dialog-api-bug

* Additional details:
  1. Sideload the provided manifest
  2. On Outlook for Android, open the add-in
  3. Tap `Open dialog`. A dialog opens pointing to the auth provider.
  4. Close the dialog by tapping the close button (the 'X' on the left).
  5. Repeat steps 3 and 4, eventually you should see the second blank dialog.

## Context

 In my actual add-in that is currently live on AppSource, I am opening a dialog to a third-party authentication provider. After a successful login on the provider, I am redirected back to my add-in within the dialog. I receive the auth token then programmatically close the dialog from the main taskpane.

After the dialog is closed, seeing a second, blank dialog is unexpected. It will cause much confusion in my clients.

This problem does not occur on Outlook for iOS, Outlook for Windows, Outlook Online, nor Outlook for Mac.

## Your Environment

* Platform: Android
* Host: Outlook
* Office version number: 4.0.51 (365)
* Operating System: Android 9
* Browser (if using Office Online): N/A

## Useful logs

- [x] Screenshots

![outlook-android-blank-dialog](https://user-images.githubusercontent.com/4981594/67835963-68b95a80-fb3f-11e9-8b61-d99f345c67de.png)

**Comment by ElizabethSamuel-MSFT** [comment]
@TheSamsterZA Thanks for reporting this issue.

@exextoc Can you investigate?

Thanks.

**Comment by exextoc** [comment]
@TheSamsterZA , I tried reproducing the problem, if problem reproduces only after successful login, can you please provide test login info to repro this ?

**Comment by TheSamsterZA** [comment]
@exextoc A login is not required. Simply open the dialog and then close it enough times and you should see what I have come to name the shadow dialog behind the original one.

**Comment by exextoc** [comment]
@TheSamsterZA i tried multiple times but i could not reproduce the problem. do you know any specific condition with which issue is frequently reproducible ?

**Comment by SharonIron** [comment]
@exextoc I have a problem that occurs for Android users only as well, i am not sure it is the same problem though.
The issue i am experiencing is that our add-in suppose to make POST requests to my servers and it doesn't do them - instead it just hangs forever.
This issue doesn't occur with: iPhone, Outlook, OWA.

I am using webpack to pack the add-in and axios library (https://github.com/axios/axios) to make the POST request.
The add-in worked over Android devices (and no change has been made since before it stopped working)

**Comment by TheSamsterZA** [comment]
Hello @exextoc, please try to replicate now. I can replicate the issue fairly consistently on my Nokia 8 on Android 9 with Outlook for Android 4.0.63 (369).

**Comment by loovadia** [comment]
@exextoc  also happens to me.
Android 9 on LG v20 with Outlook version 4.0.57

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding blank dialog. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
Internal tracking id: Office:3773278
