### ISSUE TITLE
Outlook add in doesn't work on edge and firefox (node js - yeoman generator)

### ISSUE THREAD

**Issue by iuri1994** [OfficeDev/office-js#812]
Hi
I am doing an outlook add-in with the yeoman generator, when I use it on chrome or IE the add-in works
![image](https://user-images.githubusercontent.com/51403191/67846207-b52d7780-faf8-11e9-8bff-42e459ad364d.png)

but when I use it on edge or firefox doesn't work.
first, the icon doesn't appear, this is what shows
![image](https://user-images.githubusercontent.com/51403191/67846389-12292d80-faf9-11e9-87a9-978aa115ac7f.png)

when I press in the icon to open the task pane, it never loads.

![image](https://user-images.githubusercontent.com/51403191/67846617-6c29f300-faf9-11e9-9731-24671a599853.png)

this was on firefox, on edge I get the same thing but in the end, show me this: 
![image](https://user-images.githubusercontent.com/51403191/67851833-2bcf7280-fb03-11e9-98d3-dd95857f1867.png)

Best regards

**Comment by exextoc** [comment]
1. Is this issue started recently? Was this working correctly some days/week ago?
2. Can you check if you are getting any console errors in case of edge and firefox? If yes, can you share the error.
3. Is it possible to share the stripped down version of the add-in or some sample add-in to repro the issue on our side.

**Comment by iuri1994** [comment]
Hi

1. I always had this problem.
2. No console errors
3. I have created several new projects and the response is always the same, I even used the Edge browser to get the manifest and the response is always the same.

The edge version I am using is: Microsoft Edge 44.17763.771.0

I tried the chromium version of edge (beta) and it works there, I don't know if that will help.

Best regards

**Comment by exextoc** [comment]
@iuri1994,
We need manifest xml of your add-in to reproduce the problem at our side and debug it. 

Thanks

**Comment by iuri1994** [comment]
Hello

[manifest.zip](https://github.com/OfficeDev/office-js/files/3803241/manifest.zip)

the manifest is in a zip folder because I can't upload an XML file.

Best regards

**Comment by exextoc** [comment]
@iuri1994 i tried reproducing the problem, but your add-in is hosted at localhost, so it was not working in chrome as well as edge. So can you please host it some where and provide a manifest which can help to access add-in publicly ?

**Comment by shahshyam** [comment]
I have same issue and it is not loading in chrome and not getting any error in console. I have attached my manifesto.xml 
[Portlr.zip](https://github.com/OfficeDev/office-js/files/4396555/Portlr.zip)

**Comment by exextoc** [comment]
This issue was already closed and they commented on this one. They also ended up opening a new issue on GitHub so not doing anything with this notification and ignoring it.
A bug has been opened for the other incoming issue by them and tagged with IDC + OWA.

Best,
Ankush
________________________________

**Comment by joshuayuen99** [comment]
For anyone else having this issue, I found that Firefox was more critical of add-ins being sideloaded through localhost, and didn't trust the self-signed certificate used to serve it, while Chrome was happy enough to trust it without issue. I managed to get around this issue by visiting https://localhost:3000 directly in Firefox and going through the prompts to add it as an exception. I suspect you may be able to do something similar for Edge/other browsers.
