### ISSUE TITLE
Excel Add-in: Loading Add-in very slow after installing self assigned certificate in IE

### ISSUE THREAD

**Issue by lukchen** [OfficeDev/office-js#813]
I'm using https:localhost with self assigned SSL working with my Excel Add-ins, there was annoying security warning in IE when opening TaskPane or dialog so I installed the ssl certificate into IE to let it trust my local server
I tested the taskpane web page in independent IE, it loads well. But when open the TaskPane in Excel, It just keep displaying 'loading' spinner until 3-4 minutes after

## Expected Behavior

The TaskPane and dialog should be loaded quickly

## Current Behavior

The TaskPane and dialog needs few minutes to be loaded

## Steps to Reproduce, or Live Example

* Link to live example: ______
1. Manifest uses https:localhost with self assigned SSL
2. Install self assigned SSL certificate into IE
3. Open TaskPane or dialog in Excel

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: __PC desktop___
* Host [Excel, Word, PowerPoint, etc.]: __Excel___
* Office version number: __Office 365___
* Operating System: ___WIn10___
* Browser (if using Office Online): ___IE11___

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lukchen** [comment]
![image](https://user-images.githubusercontent.com/26646767/67948267-c4c1c480-fbbb-11e9-93ec-2d4732291b79.png)

**Comment by lukchen** [comment]
I'm testing a very simple page: only a <p>hello</p> without any scripts, so it cant be polyfill or js performance issue

**Comment by ElizabethSamuel-MSFT** [comment]
@lukchen Thanks for raising this issue. We'll start investigating as soon as possible.

Thanks.

**Comment by lumine2008** [comment]
@lukchen would you please share us the test gist for us to do the investigation? thanks a lot

**Comment by lukchen** [comment]
> @lukchen would you please share us the test gist for us to do the investigation? thanks a lot

1. Run a localhost web server with self signed certificate(you can generate cert using openssl)
2. When you have it running for example, https://localhost:8080/simple.html, put this url into the Excel Manifest file, specifically the TaskPane's source location
3. Open excel, load the TaskPane you can see there is security warning due to the self signed certificate, you can continue to load the TaskPane by clicking continue to this site, this is fine
4. But I want to fix that annoying warning, so open IE(my excel is use IE as browser), navigating to https://localhost:8080/simple.html, install the certificate from browser, the installation guide is here: https://medium.com/@ali.dev/how-to-trust-any-self-signed-ssl-certificate-in-ie11-and-edge-fa7b416cac68, after the install, open page again, there is no warning
5. But now if you load the TaskPane, it loads very slow, needs 3-4 minutes. In other word, after installing the self signed certficate from the localhost server into IE, the same page can be opened in standalone IE well, but not as TaskPane in Excel

**Comment by lukchen** [comment]
I want to close this issue since it haven't got any progress here. Also installing the self signed certificate into user's trust store is security violation in general

**Comment by NightGreyMoon** [comment]
@lukchen have you got this problem resolved? I'm facing similar issue on Mac Excel, taking too long on loading and ending up with message "Please sideload your add-in to see app body"
