### ISSUE TITLE
Bindings.addFromPromptAsync should return correct cell address in Excel

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js#815]
## Expected Behavior

When Bindings.addFromPromptAsync and user defines some address in the excel native dialog (either picking by mouse or typing) the binding created should provide address as part of the result (i.e. the binding object returned in the callback should have such property).
See https://docs.microsoft.com/en-us/javascript/api/office/office.bindings?view=word-js-preview#addfrompromptasync-bindingtype--options--callback-

## Current Behavior

Currently there is no way how to find out defined address in the picker dialog invoked by Bindings.addFromPromptAsync call - user can define vairous formats of the address either manually or just by using F4 key (e.g. not only Sheet1!$A$1 but also Sheet1!A$1 or Sheet1!$A1 or Sheet1!A1). The only possibility right now is to find the binding object based on the id and then use getRange() method but in that case querying for Address does not return it in the format specified by the user.
## Steps to Reproduce, or Live Example

Use simple sample for adding Binding from native picker and use e.g. Sheet1!$A1 and then try to find the appropriate range address... you'll find out that there is no such possibility to get it in the original format (i.e. Sheet1!$A1)

## Context

We wanted to use this native picker (calling addFromPromptAsync) for defining cell-references in our customized formula wizard and currently there is no way how to get the address in correct format which is MUST HAVE for the users as the usage of correct format allows then copy/paste of the formulas.

See also https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/32852590-improved-native-reference-control-while-using-bind

**Comment by ElizabethSamuel-MSFT** [comment]
@4tti Thanks for asking about this and linking to the UserVoice item (I hope you upvoted!). Maybe there can be a workaround or mitigation - someone will take a look and respond to your issue.

Thanks.

**Comment by lumine2008** [comment]
Thanks @4tti for your report, the bug (3761411) was created and team is in investigation on this issue.

**Comment by 4tti** [comment]
@lumine2008 Thanks a lot ;)

**Comment by lumine2008** [comment]
@4tti , our team is doing the investigation on this issue, 
The typical usage of this API is to let customers hook up handlers to listen to the events of a range. Users can get the content of the range and the address. as the address is a normalized form that used internally. And it is not always the same with the address users provide in the dialog. this is by design. 
my understanding of your scenario is to show a picker dialog to allow users to select or type the range (with or without the $), you want to get exactly what user input/select. 

Do you need to use the binding object in your scenario?

**Comment by 4tti** [comment]
@lumine2008 no, we only need the picker and get the address defined by using that picker (either using mouse or typing there).

**Comment by lumine2008** [comment]
converted to a feature ask 3811311
