### ISSUE TITLE
Excel-Addin: Dialog navigation been canceled using self signed SSL localhost server

### ISSUE THREAD

**Issue by lukchen** [OfficeDev/office-js#816]
When opening a TaskPane using a self signed SSL localhost server, there is security wanring in browser which is fine, user can just click continue to the site.
But when opening dialog, the navigation to hidden host page would just be canceld(there is no option to choose to proceed this site since it is hidden), so the dialog won't be opened further.

I'm not sure if it should be a bug because a host page is required by add-in design.
But Is there a way to work this around? 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ___PC desktop___
* Host [Excel, Word, PowerPoint, etc.]: __Excel____
* Office version number: __Office365____
* Operating System: __Win10____
* Browser (if using Office Online): ___IE11___

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lukchen** [comment]
The way to open dialog is my case is using the ribbon button(addin command)

**Comment by ElizabethSamuel-MSFT** [comment]
@lukchen Thank you for asking about this. Someone should investigate soon and respond with the outcome.

Thanks.

**Comment by lumine2008** [comment]
Hello, @lukchen, Could you please share a bit more information about the repro steps?

**Comment by lukchen** [comment]
> Hello, @lukchen, Could you please share a bit more information about the repro steps?

1. Run a localhost web server with self signed certificate(you can generate cert using openssl), 
create 3 htmls with the server, one is for TaskPane https://localhost:8080/TaskPane.html, other two for Dialog https://localhost:8080/index.html & https://localhost:8080/dialog.html. The index.html is the host page(hidden), in this page you call Office.context.ui.displayDialogAsync('https://localhost:8080/dialog.html'); to open the dialog
 
2. Open excel, load the TaskPane you can see the navigation been canceled at first time and there is security warning due to the self signed certificate, you can ignore the warning then click the option to continue to this site, the navigation would be resumed so you can load the TaskPane finally.

3. But if you open the dialog, nothing shows up because the navigation to index.html is canceld due to the self signed certificate warning, and since the index.html(host page) is hidden by design, there is no way to resume the navigation just like how in TaskPane, so the dialog cant be opened

Note: Both taskpane and dialog are opened via ribbon button(<Control>)

**Comment by lukchen** [comment]
maybe the office.js could give an option to decide the middle page to be hidden or visible? so I can open the dialog with clicking on the 'proceed to this page'

**Comment by lukchen** [comment]
I want to close this this for rasing another issue
