### ISSUE TITLE
class stripped from <div /> when doing a setAsync

### ISSUE THREAD

**Issue by thoffmann-fms** [OfficeDev/office-js#817]
If doing a setAsync with HTML, the "class" attribute of any &lt;div /&gt; seems to be stripped when the body is viewed on the saved event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0498adf2-3f86-3520-82c2-df88e6ea4b95
* Version Independent ID: 347c34b6-0586-9ce5-2c84-ae010c27b276
* Content: [Office.Body interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-preview)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.body.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.body.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
@AlexJerabek We are unable to reproduce this issue in-house on the rich native desktop client for Windows. Are you observing this issue in the desktop client or the web client?

**Comment by thoffmann-fms** [comment]
Web.  Chrome. Can send a code snippet on Monday if you’d like.-Tim




On Friday, November 1, 2019, 7:39 PM, Outlook Add-ins Team - MSFT <notifications@github.com> wrote:


@AlexJerabek We are unable to reproduce this issue in-house on the rich native desktop client for Windows. Are you observing this issue in the desktop client or the web client?

**Comment by exextoc** [comment]
@timothyhoffmann, can you please provide code snippet, if it is still not working ?

**Comment by thoffmann-fms** [comment]
Here is the HTML in the event viewed in the browser debugger:
![image](https://user-images.githubusercontent.com/28546239/68493142-e35a3800-0219-11ea-872b-d97279e0e40f.png)



Here is the HTML returned by the API:
![image](https://user-images.githubusercontent.com/28546239/68493066-befe5b80-0219-11ea-9d65-91cbd6323cd7.png)

Note the div class is missing and the \<label\> tags are also missing from the API response.

Code doing the save:

```
const newBody : string = thisState.body 
                        + '<br><br><div class="testClass" ' + constants.RSDivClassNew  + '><hr><label>[RS:' + resId + ']</label>'
                        + '<br>'
                        + '<a title="' + this.props.intl.formatMessage({ id:'NewEvent.ATitle'})
                          + '" href="http://localhost/ResourceScheduler/SchedDtl.asp?ID=' + resId + '">'
                          + this.props.intl.formatMessage({ id: 'NewEvent.AText'}) + ' Resource Scheduler</a>'
                        + '</div>';
                      OfficeItem.body.setAsync(newBody, {coercionType: Office.CoercionType.Html}, (asyncResult : Office.AsyncResult<void>) => {
                        if (asyncResult.status === Office.AsyncResultStatus.Failed) {
                          this.setState({ isError : true, errorMessage : asyncResult.error.message})
                        } else {
                          // Success
                        }
                        this.setState({ isBusy : false });
                        // Close the addin window
                        Office.context.ui.closeContainer();
                      })  
```


Code retrieving the body:
```
      itm.body.getAsync(Office.CoercionType.Html, (asyncResult : Office.AsyncResult<string>) => {
        if (asyncResult.status === Office.AsyncResultStatus.Failed) {
          this.setState({ isError : true, errorMessage : asyncResult.error.message})
        } else {
          let resId : string = this.parseBodyForId(asyncResult.value);
```

**Comment by exextoc** [comment]
Sorry for the delay in response. We added this to our list and we will investigate this issue. Thanks for reporting the issue.

**Comment by exextoc** [comment]
@timothyhoffmann Do you use the class for specific styling in UI? and it is not reflecting as expected?

**Comment by thoffmann-fms** [comment]
I am parsing the body was was using the class name as kludgy part of a unique ID but after playing with it it seemed more reasonable to use the ID field for that purpose since it stays (mainly) untouched.  Having the <label> tags missing just makes the parsing a bit more tedious but not a big problem.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Any update on this issue? Thx.

**Comment by exextoc** [comment]
Hey, sorry about the wait, but we are unable to see this issue, do confirm if you still see this issue.
We are using the following code (which is a stripped down version of your code:

```javascript
var resId = "Something";
var newText = '<br><br><div class="testClass" ><hr><label>[RS:' + resId + ']</label>'
                        + '<br>'
                        + '<a title="An appropriate title" href="http://localhost/ResourceScheduler/SchedDtl.asp?ID=' + resId + '">'
                          + 'Randomtext</a>'
                        + '</div>';
Office.context.mailbox.item.body.setAsync(newText, {coercionType: Office.CoercionType.Html}, function(asyncResult) {
                        if (asyncResult.status === Office.AsyncResultStatus.Failed) {
                        } else {
                          // Success
                        }
});
```
And we are using this code to fetch it:

```javascript
/* Get the HTML body of the email body */

Office.context.mailbox.item.body.getAsync
(
	Office.CoercionType.Html,
	{
		asyncContext : "Passed back to the callback."
	},
	function (asyncResult)
	{
		console.log(asyncResult.value)
    }
);
```

And we are seeing the following output:
<img width="696" alt="Screenshot 2020-01-31 at 7 59 58 PM" src="https://user-images.githubusercontent.com/28549921/73547105-51eb1280-4464-11ea-91c6-b462b7a1b72f.png">


While I agree the appending of "x_" to classes and ids might be confusing and need to be documented, I am not seeing the behaviour you're describing. Can you check if this issue still exists from your end?

**Comment by thoffmann-fms** [comment]
Partially fixed if you save the event and then Edit it.

If you Save the event (which closes the window) and then open it again in Read mode the HTML is different.

_Using OWA (Edge Chromium Canary)_

Here's the body just after being written but the Event is not yet saved. My Add-In code was closed and then re-opened:
```
<span>
<div></div>
<br>
<br>
<div class="x_test" id="x_RSPrivateData">
<hr>
<label id="x_testId">[RS:-1999998332]</label><br>
<a target="_blank" href="http://localhost:2000/ResourceScheduler/SchedDtl.asp?ID=-1999998332">Resource Scheduler</a></div>
</span>
```

Save then event and then open it and run the Add-In while the event is *not* in Edit mode:
```
<div>
<div><span>
<div></div>
<br>
<br>
<div id="x_RSPrivateData">
<hr>
[RS:-1999998332]<br>
<a href="http://localhost:2000/ResourceScheduler/SchedDtl.asp?ID=-1999998332" target="_blank">Resource Scheduler</a></div>
</span></div>
</div>
```

Note the label tag is missing plus the class attribute is gone.

Re-open the event in Edit mode:
```
<div>
<span>
</span></div><span><div></div>
<br>
<br>
<div class="x_test" id="x_RSPrivateData">
<hr>
<label id="x_testId">[RS:-1999998332]</label><br>
<a target="_blank" href="http://localhost:2000/ResourceScheduler/SchedDtl.asp?ID=-1999998332">Resource Scheduler</a></div>
</span>
```
Now the label tag is back and the class attribute is present.  I don't care about the class myself, but others might.  Also losing the label tag with its ID isn't handy for parsing the HTML but since its at least on the DIV it is workable.

On MacOS it's worse:
_Mac Outlook 16.33 Client (Office 365 subscription):_
```
<body lang=EN-US link=blue vlink=purple>
<div class=WordSection1>
<p class=MsoNormal style='margin-bottom:12.0pt'>&nbsp;</p>
<div class=MsoNormal align=center style='text-align:center'>
<hr size=0 width="100%" align=center>
</div>
<p class=MsoNormal>
<label id="x_testId">
[RS:-1999998332]
</label>
<br>
<a href="http://localhost:2000/ResourceScheduler/SchedDtl.asp?ID=-1999998332"
target="_blank">Resource Scheduler</a></p>
<p class=MsoNormal>&nbsp;</p>
</div>
</body>
</html>

```
Label tag is there but no attributes on anything and the DIV tag and extra BRs are gone, too.

**Comment by exextoc** [comment]
@timothyhoffmann We are able to reproduce this issue on both Mac and OWA, like you described. Could you help us with your scenario here? Are you trying to parse the HTML in an email that is already sent, on which the add-in has set some div and label tags? Are you looking for these same tags in the email that was received?

**Comment by thoffmann-fms** [comment]
This is not an e-mail but an Outlook calendar event.  I push this DIV into the Calendar event via the AddOn and then at some future point the AddIn will look to find this DIV to extract the data for use.  I can look for the text only but since user's can alter the text it seems safer to use a hidden attribute rather than assume the text is un-altered.   ,E.G. possibly similar to what other addins like WebEx or Teams will do with their private data inserted into the body.

**Comment by exextoc** [comment]
@timothyhoffmann Thanks. Please note that the body API does not guarantee the retention of these HTML tags when the email is sent. [The documentation](https://docs.microsoft.com/en-us/javascript/api/outlook/office.body?view=outlook-js-preview) says:

> When working with HTML-formatted bodies, it is important to note that the Body.getAsync and Body.setAsync methods are not idempotent. The value returned from the getAsync method will not necessarily be exactly the same as the value that was passed in the setAsync method previously. The client may modify the value passed to setAsync in order to make it render efficiently with its rendering engine.

This is probably why the extra div IDs and classes are removed after the email (or meeting invite) is sent. It is not recommended to use HTML tags for identifying data that is set by the add-in.

Marking this as closed since this is expected behaviour for this scenario.

**Comment by gibbitz** [comment]
This is disappointing when an unstyled tag (p/span) is substituted for a styled one (li/h2 etc) or when it strips my style attributes. Would be nice to have a reliable method of styling my add-on generated messages.
