### ISSUE TITLE
Add-In doesn't reload when I click on download images on Outlook for Mac

### ISSUE THREAD

**Issue by kakusharma** [OfficeDev/office-js#818]
When i open an email in Outlook for Mac the Add-In loads up fine. The entity gets highlighted. But when I click on download images to download the images in the email content, the whole content refreshes and the Add-In doesn't load up this time. I have to select some other mail and then come back to it again for the entity to get highlighted. This is happening on Outlook for Mac only. Works fine on windows clients.
## Expected Behavior

When I click to download the images, the email content refreshes and the Add-In should get triggered, just like it does when I came back to the mail after selecting some other mail.
## Current Behavior

The Add-In entity doesn't get highlighted when I download the content images.

The Add-In entity should get highlighted again when I download the content images, just like it does when I open the mail the Add-In entity is highlighted.
## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. See the video [here](https://www.screencast.com/t/8KINsbrgXjRm) to get a better idea of the issue 
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office 2019
* Operating System: Mac
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
@kakusharma  it seems that the link(with which add-in was running) is gone after video/images download thats why add-in is not running. For further investigation can you please forward the video to email: **meganb@androidaddins.onmicrosoft.com** ?

**Comment by kakusharma** [comment]
I have forwarded the video link on the email address you mentioned. Let me know if you need anything further.

**Comment by exextoc** [comment]
i saw you forwarded the link of bug video.. which you have already added here.. we need video in which add-in was running.. can you provide that ?

Or Can you forward the mail which you used for testing the issue?
