### ISSUE TITLE
isSetSupported('Mailbox', '1.8') returns false in add-in running in OWA with Office365

### ISSUE THREAD

**Issue by wadabottle** [OfficeDev/office-js#822]
In a [supported environment listed here](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets). Office.context.requirements.isSetSupported('Mailbox', '1.8') is returning false in OWA (Chrome) with Office365. When can we expect isSetSupported to return true for v1.8?

## Expected Behavior
Expect isSetSupported('Mailbox', '1.8') to return true for supported environments.

## Current Behavior
isSetSupported('Mailbox', '1.8') returns false in OWA with Office365.

## Steps to Reproduce, or Live Example
executed Office.context.requirements.isSetSupported('Mailbox', '1.8')

## Context
I'm trying to determine if Office.context.mailbox.item.getAttachmentContentAsync() is supported on the client/server configuration running the add-in. Should we be checking the Exchange server version + client build version against known functioning permutations or will Office.context.requirements.isSetSupported('Mailbox', '1.8') encapsulate these checks for us?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Office.context.diagnostics.version=16.0.10908.10000
Office.context.mailbox.diagnostics.hostVersion=2019102702.12
* Operating System: Mac
* Browser (if using Office Online): Chrome

## Useful logs
Office.context.requirements.isSetSupported('Mailbox', '1.8') returns true as expected in Outlook for Mac with Office365.

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by htryggva** [comment]
@JuaneloJuanelo We have implemented this in our Content Chooser product and have also run into this issue. Works fine on Windows and Mac but not on Online. Can you please look into this? Thanks!

**Comment by JuaneloJuanelo** [comment]
known issue, fix coming soon.

**Comment by exextoc** [comment]
A fix for this issue was deployed at the end of November last year.
