### ISSUE TITLE
"code":"Request_ResourceNotFound","message":"Resource {guid} does not exist or one of its queried reference-property objects are not present."

### ISSUE THREAD

**Issue by Harshagracy** [OfficeDev/office-js#823]
Issue: I am trying to **connect with graph API** from my **outlook add-in**. I am getting the access token.

 ![token](https://user-images.githubusercontent.com/14230498/67379416-823e2d80-f5a6-11e9-8d5d-b1e20bfe2fe6.png)
I have given my consent to use the graph API. But I am getting the below error: 
![graph-error](https://user-images.githubusercontent.com/14230498/67379360-69357c80-f5a6-11e9-9e27-0c05ba5069d5.png)
```
code: "Request_ResourceNotFound"
innerError:
date: "2019-10-23T09:28:27"
request-id: "5f20c0fe-279c-4c59-bdd2-1ea5a9613d81"
__proto__: Object
message: "Resource '8c14a998-3c8d-4c52-ad09-c9032671ea31' does not exist or one of its queried reference-property objects are not present."
__proto__: Object
```
Below is my code snippet: 

![code snippet](https://user-images.githubusercontent.com/14230498/67379363-69357c80-f5a6-11e9-81eb-68b252e90f9c.png)
It is a simple and straightforward code. i am not sure, what is the issue. 

Please help me If I have missed any.

**Comment by exextoc** [comment]
@Harshagracy, which API you are using to acquire the access token? There are two APIs that return access tokens, and those tokens are used differently.

If you wish to make a call from Javascript, and you are calling a Mail/Calendar Graph API, you may be able to use the Exchange REST URL in place of the Graph URL along with [getCallbackTokenAsync](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.5/office.context.mailbox#getcallbacktokenasyncoptions-callback).

More info on both token types:
- [Example for calling Exchange REST APIs using the callback token](https://docs.microsoft.com/en-us/outlook/add-ins/use-rest-api)
- [The first of many pages describing single sign-on (in preview)](https://docs.microsoft.com/en-us/outlook/add-ins/authentication), which can call any Graph API

**Comment by Harshagracy** [comment]
Hi, 

This is the method I am using: 

```
$.ajax({
      "async": true,
      "crossDomain": true,
      "url": "https://cors-anywhere.herokuapp.com/https://login.microsoftonline.com/mydomain.onmicrosoft.com/oauth2/v2.0/token",// I passed my domain in place of mydomain
      "method": "POST",
      "headers": {
        "content-type": "application/x-www-form-urlencoded"
      },
      "data": {
        "grant_type": "client_credentials",
        "client_id ": "77************f6", //my app guid id which is in azure portal
        "client_secret": "****************", //my secret  
        "scope ": "https://graph.microsoft.com/.default"
      },
      success: (response: any) => {
        console.log(response);
        var token = response.access_token;
        this.setState({ token: token });
        $.ajax({
          url: 'https://graph.microsoft.com/v1.0/me',
          type: 'GET',
          dataType: 'json',
          beforeSend: function (xhr) { xhr.setRequestHeader('Authorization', 'Bearer ' + token); }, //set
          headers: {
            'Authorization': 'Bearer ' + token,
            'Content-Type': 'application/json',
            'Access-Control-Allow-Origin': '*'
          },
          success: (results) => {
            console.log(results);
            this.setState({ msg: JSON.stringify(results) });
          },
          error: (error) => {
            console.log("Error in getting data: " + JSON.stringify(error.responseJSON.error));
            this.setState({ msg: JSON.stringify(error.responseJSON.error) });
          }
        });
```

**Comment by Harshagracy** [comment]
In regards to getCallbackTokenAsync, I am always getting the error. 
```
code: 5001
message: "Er is een interne fout opgetreden."
name: "Interne fout"
```
![image](https://user-images.githubusercontent.com/14230498/68273167-b4ae5700-008b-11ea-94ed-4497e3ea1ba9.png)

**Comment by exextoc** [comment]
I'm not sure my last reply helped, so let me check my understanding.

Which Graph API are you intending to call, once you have a token? This will help me recommend which token to use.

In the original screenshot, you had an access token, and in the latest screenshot, you got a 5001 error instead. What changed between the two? Thanks.
