### ISSUE TITLE
code: 5001, message: "An internal error has occurred.", name: "Internal Error"

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#826]
## Expected Behavior
The following methods should work without the "Internal Error" error:

Office.context.mailbox.item.body.getTypeAsync
Office.context.mailbox.item.getSelectedDataAsync
Office.context.mailbox.item.setSelectedDataAsync
Office.context.mailbox.item.subject.getAsync
Office.context.mailbox.item.subject.setAsync
Office.context.mailbox.item.to.getAsync
Office.context.mailbox.item.to.setAsync
Office.context.mailbox.item.cc.getAsync
Office.context.mailbox.item.cc.setAsync
Office.context.mailbox.item.bcc.getAsync
Office.context.mailbox.item.bcc.setAsync
Office.context.mailbox.item.addFileAttachmentAsync

## Current Behavior
Error:
{ code: 5001, message: "An internal error has occurred.", name: "Internal Error" }

## Steps to Reproduce, or Live Example
1. Windows 10 (1903)
2. Outlook 365 desktop (Version 1910)
3. Add-in for compose mode
4. Create 2 or more new emails and save them to Drafts.
5. Go to Drafts, select an email that you created, start the add-in and **pin** it.
6. Test any of the above methods, they work so far.
7. Select the other email in Drafts.
8. Test any of the above methods, they all **fail** now.

## Your Environment
* Platform: PC desktop
* Host: Outlook desktop (Version 1910)
* Office version number: 16.0.12130.20232 32bit
* Operating System: Windows 10 (1903)
* Browser: ______

**Comment by mscharlock** [comment]
@JuaneloJuanelo and/or @exextoc Hi folks! Would one of you be able to have a look at this? Thanks! @DmitryKostochko Microsoft had a major conference this week, so replies might be delayed a bit.

**Comment by exextoc** [comment]
It sounds like you might have an issue with the ItemChanged event. Does your add-in [support pinning](https://docs.microsoft.com/en-us/outlook/add-ins/pinnable-taskpane#support-task-pane-pinning)?

**Comment by DmitryKostochko** [comment]
Yes, the add-in supports pinning. But I don't handle the ItemChanged event. Please have a look at my test code below:

    // body
    Office.context.mailbox.item.body.getTypeAsync({},
      function (result: Office.AsyncResult<Office.CoercionType>) {
        if (result.status === Office.AsyncResultStatus.Failed) {
          console.error('item.body.getTypeAsync ERROR', result.error);
        } else {
          console.log('item.body.getTypeAsync OK', result.value);
        }
      }
    );
    // selected data
    Office.context.mailbox.item.getSelectedDataAsync(Office.CoercionType.Text,
      function (result: Office.AsyncResult<any>) {
        if (result.status === Office.AsyncResultStatus.Failed) {
          console.error('item.getSelectedDataAsync ERROR', result.error);
        } else {
          console.log('item.getSelectedDataAsync OK', result.value);
        }
      }
    );
    Office.context.mailbox.item.setSelectedDataAsync('test', { coercionType: Office.CoercionType.Text },
      function (result: Office.AsyncResult<void>) {
        if (result.status === Office.AsyncResultStatus.Failed) {
          console.error('item.setSelectedDataAsync ERROR', result.error);
        } else {
          console.log('item.setSelectedDataAsync OK');
        }
      }
    );

**Comment by exextoc** [comment]
You will need to register the event handler for the ItemChanged event when you call Office.initialize, so the add-in is notified when the item is changed. A sample for doing this can be found [here](https://docs.microsoft.com/en-us/outlook/add-ins/pinnable-taskpane#register-the-event-handler).

**Comment by DmitryKostochko** [comment]
Thank you for the explanation, adding the ItemChanged event handler solves the issue!
