### ISSUE TITLE
body.getAsync returns original HTML body not updated body

### ISSUE THREAD

**Issue by thoffmann-fms** [OfficeDev/office-js#828]
The addin is running in the context of an existing event.  The event was created then I updated the body, closed the event and then re-opened and re-launched the add-in.

Code:
```
      var itm = Office.context.mailbox.item;
      itm.body.getAsync(Office.CoercionType.Html, (asyncResult : Office.AsyncResult<string>) => {
        if (asyncResult.status === Office.AsyncResultStatus.Failed) {
          this.setState({ isError : true, errorMessage : asyncResult.error.message})
        } else {
          console.log(asyncResult.value);
          debugger;
```
Console output:
```
<div>
<div><span><br>

<br>

<div id="x_RSPrivateData">
<hr>
[RS:-1999823968]<br>

<a href="http://localhost/ResourceScheduler/SchedDtl.asp?ID=-1999823968" title="Afficher les détails de la réservation">Voir la réservation en Resource Scheduler</a></div>
</span></div>
</div>
```

What OWA shows on the screen:
![image](https://user-images.githubusercontent.com/28546239/68335041-c1da3e80-00a9-11ea-8c91-4910fd875a18.png)

What the Graph API returns:
```
            "bodyPreview": "Additional text @tim here\r\n\r\n________________________________\r\n[RS:-1999997498]\r\nVoir la réservation en Resource Scheduler",
            "body": {
                "contentType": "html",
                "content": "<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n<meta content=\"text/html; charset=iso-8859-1\">\r\n</head>\r\n<body>\r\n<div></div>\r\n<div>Additional <b>text @tim</b> here</div>\r\n<span><br>\r\n<div id=\"x_RSPrivateData\">\r\n<hr>\r\n[RS:-1999997498]<br>\r\n<a target=\"_blank\" title=\"Afficher les détails de la réservation\" href=\"http://localhost/ResourceScheduler/SchedDtl.asp?ID=-1999823968\">Voir la réservation en Resource Scheduler</a></div>\r\n</span>\r\n</body>\r\n</html>\r\n"
            },
```

**Comment by thoffmann-fms** [comment]
NOTE: Using OWA for this (Edge Chromium beta or Chrome or IE 11)

It appears to be a cache issue.  If I Edit the event, Send it, then re-open it and call the API I get the old data.  If I Edit the event, Send it, then click the browser Refresh button, then Double-click to open it and call the API I get the updated event.  Ditto if I exit the browser and then go back in I get the updated data.

**Comment by mscharlock** [comment]
Hi @exextoc - do you mind having a look at this? @timothyhoffmann sorry for the delay, Microsoft had a major conference this week so folks have been fairly busy. Thanks for your patience!

**Comment by exextoc** [comment]
Sorry for delay, we are investigating the issue and we will get back to you soon.

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
We have already fixed this issue.
