### ISSUE TITLE
Checkbox control from OOXML format getting converted into “?” while rendering in Word(O365)

### ISSUE THREAD

**Issue by biswanathc** [OfficeDev/office-js#830]
I am working on Word Addin/Office JS Project which deals with Word templates. My requirement is to load the static table into template when the user clicks on the Addin.

Step 1: Converting Static Table Data into OOXML and Storing it into Database.
![Initial_View](https://user-images.githubusercontent.com/43954679/68449707-4219b480-020e-11ea-97d9-e223446cd45d.png)

This Table has Check box controls and Content Control inside it. I am generating OOXML for this loading it into database.

Code

var body = context.document.body;

var bodyOOXML = body.getOoxml();
Step 2: Retrieving the table data from Database and loading it in the document when the user click on the addin.

Code

 var body = context.document.body;

 body.insertOoxml(currentOOXML, Word.InsertLocation.replace);
but when I retrieving the table data, the check box control in the table are displayed as "?"

Please find the output  below
![Loaded_View](https://user-images.githubusercontent.com/43954679/68449708-4219b480-020e-11ea-8bd5-f8ffa0d8c803.png)

Can some one help me with this I don’t understand why checkbox controls are getting converted as "?" If I click on "?" its converting back into Checkbox

Note: I am using api version 1.3 and word o365 desktop version for this work.

**Comment by mscharlock** [comment]
Hi @weshi - Another Word question for you when you get a chance to look at it. Thanks! @biswanathc Again, just an FYI that Microsoft had a major conference this week, so responses are a little delayed.

**Comment by weshi** [comment]
Just to confirm, can you provide the environment detail information? Is this for Word on Windows or Word for the Web? What's the version of the Word, etc.

BTW, check box control is not supported in Word for the Web.

**Comment by biswanathc** [comment]
@weshi  We are trying out in **Office 365 windows desktop version(Pro plus)**. Below is the ooxml for the checkbox which we are rendering in word and getting "?" symbol

<w14:checkbox><w14:checked w14:val="0"/><w14:checkedState w14:val="2612" w14:font="MS Gothic"/><w14:uncheckedState w14:val="2610" w14:font="MS Gothic"/></w14:checkbox>

**Comment by weshi** [comment]
@biswanathc I tried to reproduce the issue with insertOoxml API. I can successfully insert check box content control without problem. 

 I suspect that when you save the OOXML to your database and retrive it from it again, your database encoding might caused some characters converted to "?". Usually this can be caused if your database is using an encoding that does not support the characters in the XML contents. For example, if you database is not using unicode or UTF-8 encoding, then when you save XML contents which contains special characters not supported by your database encoding, they will be converted to ?. But this is just my assumption.

Can you check the XML contents you get from your database and see if that's the case? 

Or you can try the body.insertOoxml directly with the OOXML contents immediately after you get from body.getOoxml and see if the issuse still exists. 
Thanks.

**Comment by biswanathc** [comment]
@weshi  Thank you! This was issue with DB. We were saving OOXML in DB as Nvarchar. After changing to datatype to xml it worked fine.
