### ISSUE TITLE
Office.context.document.url method not working as expected for Word API

### ISSUE THREAD

**Issue by biswanathc** [OfficeDev/office-js#831]
I am working on Word Addin/Office JS. My word document is loaded at office online and the url generated is like below

https://mydomain.xyz/:w:/r/personal/personal_com/_layouts/15/Doc.aspx?sourcedoc=%7B6FEF6215-DD54-4BFF-B12C-2D762C0932AC%7D&file=AddinTest.docx&action=default&mobileredirect=true

My requirement is to read this url and fetch querystring value.

As per remedy given in below link 

https://stackoverflow.com/questions/58709035/how-to-retrieve-the-query-string-value-from-web-word-instance

I tried using Office.context.document.url method. But this gives me url as below and not showing the path as seen in browser

https://mydomain.xyz/personal/personal_com/Documents/AddinTest.docx

I want the actual url along with all querystring values. Please suggest how can I achieve this.

Just to give a background, I want to pass parameter from the source application to wordaddin by querystring. If the full url cannot be read by wordaddin then it defeats my idea.

**Comment by mscharlock** [comment]
Hi @weshi, do you mind having a look at this issue? @biswanathc Just so you know, Microsoft had a major conference this week so replies have been a little delayed.

**Comment by weshi** [comment]
This API currently is designed to return the file location URL. It's not same as the URL you see in the browser address bar. But with file location URL, you can still open the doc. There is no API to return the URL in you see in the address bar directly.

**Comment by dgrayling** [comment]
@weshi For the file location URL, this behaves as an automatic download link. Do you mean that we can open the document given that we've downloaded it or can this url some how be opened as the file avaliable on web?
