### ISSUE TITLE
Inconsistent result status for setSelectedDataAsync in Outlook Online

### ISSUE THREAD

**Issue by TobiasWolters** [OfficeDev/office-js#832]
We are developing an add-in for both Outlook, PowerPoint, Excel, and Word. Currently, we are looking at inserting images in Outlook. 
For this purpose we call `Office.context.mailbox.item.body.setSelectedDataAsync()`. In the desktop version of Outlook, we either get a successful response, and the image is inserted in the body, or we get a response indicating an unsuccessful insertion.
In Outlook Online, however, we sometimes get a successful response even though the image isn't actually inserted in the body.

## Expected Behavior
The response should only indicate success if the image is actually inserted.

## Current Behavior
The response sometimes indicates success even though the image isn't inserted.

## Steps to Reproduce
1. Open Outlook Online
2. Compose a message.
3. Try inserting an image with: `Office.context.mailbox.item.body.setSelectedDataAsync(imageHtml, { coercionType: Office.CoercionType.Html, callback}`. Replace `imageHtml` with the contents of: [imageHtml.txt](https://github.com/OfficeDev/office-js/files/3823976/imageHtml.txt). Note that the file contains less than 1,000,000 characters.
4. A successful insertion is indicated in the callback, but the image isn't inserted.

## Context
If users try inserting images where the resulting imageHtml contains more than 1,000,000 characters, we provide them with an appropriate error message. However, we can't provide appropriate user feedback, when the callback indicates that the image is inserted successfully, even though it isn't actually inserted.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Windows 10 Pro
* Browser (if using Office Online): Chrome.

**Comment by mscharlock** [comment]
Hi @exextoc, do you mind having a look at this issue? Thanks! @TobiasNissen Just an FYI, Microsoft had a major conference this week so replies may be delayed.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding < img > tag with data. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by TobiasWolters** [comment]
Thanks. Please let me know when you have an estimate on the timeline.

**Comment by exextoc** [comment]
It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
@TobiasNissen Have you tried our preview API to add attachment to mail item? https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/preview-requirement-set/office.context.mailbox.item#addfileattachmentfrombase64asyncbase64file-attachmentname-options-callback

**Comment by TobiasWolters** [comment]
@exextoc Yes, thank you. Seems like a much better way to do this - especially with the inline option.
