### ISSUE TITLE
Office.context.mailbox.item.attachments objects have no id field in Outlook Desktop

### ISSUE THREAD

**Issue by eneoli** [OfficeDev/office-js#833]
## Expected Behavior
Office.context.mailbox.item.attachments[x].id should exist.

## Current Behavior
Calling api on one mail that is signed returns attachment objects, but without id field, while acting like it should on OWA.

## Steps to Reproduce, or Live Example
console.log(Office.context.mailbox.item.attachments)

## Context
Developing a plugin for transffering mail content into ticket system.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 1910
* Operating System: Windows

**Comment by mscharlock** [comment]
Hi @exextoc - do you mind having a look at this issue? Thank you!

**Comment by exextoc** [comment]
What is your Outlook build number?

Office.context.mailbox.item.attachments is a read-only API. Are you using this API on a read item?

**Comment by eneoli** [comment]
Version: 1910
Build nummer: 12130.20272

I use it on a read item

**Comment by exextoc** [comment]
Thanks for the response. If the mail you are using is encrypted, add-ins should not be accessible. Could you explain more about how the mail was signed?

**Comment by eneoli** [comment]
Message format: S/MIME
Signed from: *censored*
Time: 09:52:24 04.11.2019
Digest algorithm; SHA256
Signing algorithm: RSA (2048 Bits)
Certificate from: COMODO RSA Client Authentication

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
I also want to add a note that you can use get-item EWS method to get the attachment IDs.
