### ISSUE TITLE
[Excel] Client is getting an Add-In Error message

### ISSUE THREAD

**Issue by dinglicoding** [OfficeDev/office-js#836]
our customer on her computer will show Add-in error message. 
but in our computer can't happen ,the only different is the computer version.
i take her's excel version and windows version in blew.
thanks

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ___pc desktop___
* Host [Excel, Word, PowerPoint, etc.]: ____excel__
* Office version number: _____1910_
* Operating System: __windows____

## Useful logs

![image](https://user-images.githubusercontent.com/3963826/68521049-0ea35c80-02d8-11ea-980e-4d696bf1b390.png)
![image](https://user-images.githubusercontent.com/3963826/68521060-1fec6900-02d8-11ea-9641-69a8d3c998bf.png)

**Comment by AbidRahman-MSFT** [comment]
Hello @dinglicoding, thank you for your question.

Can you provide more context on when your customer runs into this issue? Does it only happen when attempting certain actions? Does the error message correspond to an actual issue in the add-in or is the add-in functional while the message is displayed?

Please also let us know if you are able to reproduce the same bug on a different computer. You can also find common add-in errors and help with troubleshooting in the documentation:

https://docs.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting

Thanks!

**Comment by dinglicoding** [comment]
@AbidRahman-MSFT  we have reinstalling the add-in on our customer computer, the issue is still. 

we have no such environment，in our dev computer.

thanks.

**Comment by lumine2008** [comment]
@dinglicoding can you repro in your machine?

**Comment by dinglicoding** [comment]
@lumine2008   no. my machine is fine.

**Comment by lumine2008** [comment]
Please reactivate this issue or open a new one if you still repro this issue
