### ISSUE TITLE
PowerPoint Online Content Add In in presentation mode shows error "We couldn't connect the catalog server for this add in"

### ISSUE THREAD

**Issue by ndeeH** [OfficeDev/office-js#837]
Our PowerPoint Content Add In is already available in PPT Online.
Here we see a display errors which we can not solve, because they com from PPT Online itself.

PPT Online displays Add In content **AND** a obscur image of the add in, which is not completely in sync and looks like this:
![image](https://user-images.githubusercontent.com/11518242/68584767-ca9f8b80-0480-11ea-8b7b-3468f7356d24.png)
It seems that somebody at Microsoft added this image rendering to solve a problem with the thumbnail view that is caused by Add Ins that use an iFrame to display its content.
Our Add In uses a iFrame to display its content after pasting a report uri (but not on the initial screen!).

## Steps to Reproduce / Current Behavior
Insert Add In "IDL.PRESENTATION" from Store to see the behavior.
Just change the size of the add in and you even see more differences between:
live content of our add in **AND** a obscur image that PPT Online renders 
(this image does NOT come from our add in)

The DOM contains this image as jpg;base64
![image](https://user-images.githubusercontent.com/11518242/68585154-abedc480-0481-11ea-8dbc-7d9945540a0a.png)

Also the thumbnail view on the left does not render add ins properly:
![image](https://user-images.githubusercontent.com/11518242/68590141-1efd3800-048e-11ea-8050-d0ae18b58450.png)
Here you see an Content Add In which contains an iFrame that holds the content. 
Nothing on the thumbnail side.
On other thumbnail you see our add in and here "content add in image placeholder" is rendered.

## Your Environment
PPT Online - here latest Chrome.

**Comment by AbidRahman-MSFT** [comment]
Hey @weird-dreams, thanks for bringing up this issue. We are currently looking into this. This issue was only reproducible on the "IDL.PRESENTATION" add-in. Are you able to reproduce this issue on any other add-in that also uses an iFrame?

**Comment by ndeeH** [comment]
Hi @AbidRahman-MSFT, 
first I found a **WorkAround** - simple setting a **background color** 🙈 in our add in hides the rendered image below. _May be this was the difference to other add ins?_

**_Is it a requirement for an add in to set a **background color** and not use default (transparent)?_**
(When no background color is set you see the effect described in the issue)

Now we continued testing with PowerPoint Online and still have two issues:

1. After inserting content in our add in (displayed in an iFrame) - the **thumbnail view on the left** displays an empty box instead of the content
![image](https://user-images.githubusercontent.com/11518242/69140597-15458700-0ac3-11ea-8c4a-a1b4b0114887.png)

1. In **Presentation mode** we see this error instead of our content add in:
![image](https://user-images.githubusercontent.com/11518242/69140640-29898400-0ac3-11ea-8200-643579aa915a.png)

**Comment by AbidRahman-MSFT** [comment]
Thanks for the added information. The issue of having the rendered image being overlaid on top of your add-in is unique, I'm glad you were able to find a workaround! Adding @donlvMSFT to help with your background color requirement/workaround question.

For the thumbnail view: The snapshot feature of the add-in that assists in rendering the thumbnail of the add-in is implemented using html2canvas which has the following limitations:
- Cannot render video.
- Cannot render iFrame.

Unfortunately at this time, we do not have any plans to fix these limitations. 

Can you please provide more information regarding the 'Presentation Mode' bug? Does this only occur after you added a background color? Were there any other changes you made? (@donlvMSFT)

**Comment by ndeeH** [comment]
Hi @AbidRahman-MSFT,
I am not sure if presentation mode ever worked in PPT Online - the add in was not visible inside PowerPoint Online before some weeks. In the desktop version it works without any problems.

Here is the console output while getting this error - but this could be "normal":
```
powerpointframe.html:34 Refused to get unsafe header "WaitForSessionTimeoutMs"
powerpointframe.html:34 Refused to get unsafe header "ClientCorrelationID"
ariasdk.js:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-typ…fe-1c06-460f-96c5-6a0b247358bc-7238&client-time-epoch-millis=1574269197386 net::ERR_BLOCKED_BY_CLIENT
aria-web-telemetry.js:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-typ…fe-1c06-460f-96c5-6a0b247358bc-7238&client-time-epoch-millis=1574269204387 net::ERR_BLOCKED_BY_CLIENT
aria-web-telemetry.js:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-typ…fe-1c06-460f-96c5-6a0b247358bc-7238&client-time-epoch-millis=1574269207394 net::ERR_BLOCKED_BY_CLIENT
ariasdk.js:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-typ…2e-bacf-4067-bb5d-fe87f33fa915-7384&client-time-epoch-millis=1574269210387 net::ERR_BLOCKED_BY_CLIENT
ariasdk.js:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-typ…2e-bacf-4067-bb5d-fe87f33fa915-7384&client-time-epoch-millis=1574269213388 net::ERR_BLOCKED_BY_CLIENT
aria-web-telemetry.js:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-typ…36-1bbe-482f-a64a-c2d9cb606706-7439&client-time-epoch-millis=1574269221388 net::ERR_BLOCKED_BY_CLIENT
powerpointframe.html:34 Refused to get unsafe header "X-IsCacheable"
powerpointframe.html:34 Refused to get unsafe header "X-WacCluster"
powerpointframe.html:34 Refused to get unsafe header "sw"
powerpointframe.html:34 Refused to get unsafe header "sh"
powerpointframe.html:34 Refused to get unsafe header "WaitForSessionTimeoutMs"
powerpointframe.html:34 Refused to get unsafe header "ClientCorrelationID"
aria-web-telemetry.js:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-typ…36-1bbe-482f-a64a-c2d9cb606706-7439&client-time-epoch-millis=1574269225388 net::ERR_BLOCKED_BY_CLIENT
ariasdk.js:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-typ…fe-1c06-460f-96c5-6a0b247358bc-7238&client-time-epoch-millis=1574269230387 net::ERR_BLOCKED_BY_CLIENT
ariasdk.js:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-typ…fe-1c06-460f-96c5-6a0b247358bc-7238&client-time-epoch-millis=1574269234389 net::ERR_BLOCKED_BY_CLIENT
aria-web-telemetry.js:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-typ…fe-1c06-460f-96c5-6a0b247358bc-7238&client-time-epoch-millis=1574269241408 net::ERR_BLOCKED_BY_CLIENT
aria-web-telemetry.js:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-typ…fe-1c06-460f-96c5-6a0b247358bc-7238&client-time-epoch-millis=1574269244388 net::ERR_BLOCKED_BY_CLIENT
ariasdk.js:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-typ…2e-bacf-4067-bb5d-fe87f33fa915-7384&client-time-epoch-millis=1574269247387 net::ERR_BLOCKED_BY_CLIENT
ariasdk.js:1 POST https://browser.pipe.aria.microsoft.com/Collector/3.0/?qsp=true&content-typ…2e-bacf-4067-bb5d-fe87f33fa915-7384&client-time-epoch-millis=1574269251389 net::ERR_BLOCKED_BY_CLIENT

```

_Any ideas? 
The error message `"We couldn't connect the catalog server for this add in"` seems strange but could be a "red hering"._
TIA, Andi

**Comment by ndeeH** [comment]
#198 was the same issue I had reported long time ago. The issue was closed but is not fixed -
I am renaming the title face this prob.

**Comment by donlvMSFT** [comment]
@weird-dreams , yes, the background color of add-in is transparent, since it couldn't render iFrame in thumbnail, if your add-in is base on an iFrame page, it will be transparent in thumbnail.
I think setting a background color could be a workaround to mark your add-in.

**Comment by ndeeH** [comment]
@donlvMSFT  Good point. We will try this...  
Users only want to see content - so the "marker backgrounds" have **not** be "visible".
For example we hide app bar buttons and all around when users are not interacting with the add in.

**Comment by donlvMSFT** [comment]
@weird-dreams , if I'm not misunderstanding, you want to highlight content in the thumbnail.
Because of the limitation of iframe, maybe you could try to do a simple HTML but not fill all contents in the iframe.

**Comment by ndeeH** [comment]
@donlvMSFT  No - we only have the inserted chart content in an iFrame - the app itself is simple HTML and we using now background-colors where it is possible.

@AbidRahman-MSFT  Please could you follow up the issue in presentation mode - because this is a show stopper for a power point content add in.

**Comment by AbidRahman-MSFT** [comment]
@weird-dreams I was unable to reproduce the error when installing the "IDL.PRESENTATION" add-in from the store and using presentation mode on PPT on Web.

Can you confirm that this issue only occurs during development (when sideloading the add-in)?

**Comment by ndeeH** [comment]
@AbidRahman-MSFT Tried it again - and seems to work now. 
I deactivated PrivacyBadger in Chrome - maybe this blocked some cookies that were needed.
