### ISSUE TITLE
PowerPoint Content Add in Presentation Mode blury display

### ISSUE THREAD

**Issue by ndeeH** [OfficeDev/office-js#838]
Our PowerPoint Content Add In is already in the store.
When using Chrome and switch to presentation mode the add in content is displayed blury:
![image](https://user-images.githubusercontent.com/11518242/68585408-71385c00-0482-11ea-8295-b75f5012b620.png)
The Add In uses an iframe to display the report contents.

## Expected Behavior
Add In content should not look blury in presentation mode

## Steps to Reproduce, or Live Example
Use add in "IDL.PRESENTATION" from store and add a report from our site preview.idl.eu.
(I will send you the guest login via private message)

## Your Environment
Latest PPT Online with Chrome. (In Edge we do not see this effect)

**Comment by AbidRahman-MSFT** [comment]
Hello @weird-dreams,

Thank you for bringing up this issue - I am able to reproduce it and we have created a work item to improve the experience for content add-ins in PPT on web and fix the blurry issue on Chrome. 

Unfortunately this is not an easy fix nor is it highly prioritized at this moment,  but we will keep you updated on any improvements.

Thanks for the patience,
Abid

**Comment by lindalu-MSFT** [comment]
@AbidRahman-MSFT Is there an internal bug tracking this?

**Comment by AbidRahman-MSFT** [comment]
We are internally tracking this request with #3810520. There is no ETA for this at the moment.

**Comment by AbidRahman-MSFT** [comment]
@ndeeH , are you still having this issue?

**Comment by ndeeH** [comment]
Hi @AbidRahman-MSFT ,
I wanted to re-check this issue. At the moment the authentication flow does not work anymore - we get a message "Too many redirects" in Chrome and Edge. It seems that MS or Google has changed the behavior of redirects in a window.
This completely breaks our authentication! Do you know anything about this? 
Normal authentification flows only work by several redirects!
In Firefox all worked as expected - but the issue was in Chrome.
Trying to find, why we get the "too many redirects" message.
Bye, Andi

**Comment by AbidRahman-MSFT** [comment]
Hey @ndeeH,

Can you provide more information on the auth flow you are using? Are you using the Dialog API for your auth flow? When are you seeing the "Too many redirects" message in your add-in?

**Comment by ndeeH** [comment]
Hey @AbidRahman-MSFT ,
yes - we are using the dialog API and excatly the login flow described. (We are using ThinkTecture-IDP behind the scenes).
The flow does only work in firefox - all chromium based browsers now block the login flow 🤔
In the desktop version the login flow works as expected.

You may try it - here you have a document with our official store add in and an embedded content:
https://whiteduck-my.sharepoint.com/:p:/g/personal/andreas_hartmann_whiteduck_de/ERXR2xnfIQRDtnFt3njbZPMBs_kmMzKbOVcrm1C_HE0cvg?e=jqeo84
When you open the document - the login flow starts...


All our customers face the problem in the online versions of office 😫
_Hope you can help us..._

TIA, Andi

**Comment by lliu113** [comment]
@ndeeH - sorry to hear about the auth issue! If this is still a problem, can you open a separate github issue for it? This will better help us track. If you could include some repro steps for the login flow, that would be very helpful. Thanks!

**Comment by ndeeH** [comment]
@lliu113 @AbidRahman-MSFT 
Hi there,
I posted another issue and solved it already 😀 details [here](https://github.com/MicrosoftEdge/WebView2Feedback/issues/1194)
(was a Cookie-Problem coming up with Chrome... SameSite-Mode)

**Today I tested the "blury" issue and it has gone with the actual version of office and chrome.**

Thank you, Andi
