### ISSUE TITLE
Office.js custom function release date

### ISSUE THREAD

**Issue by pawsong** [OfficeDev/office-js#84]
*Moved from StackOverflow with @mlafleur's advice*

What would be the release date of Office.js Excel custom formula feature?

https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview

This feature has been under Developer Preview for months but I couldn't find any sign of updates.

There are some official channels to contact Microsoft like

- https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-overview
- https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/6936956-add-user-defined-function-support-to-the-apps-for

but the comments have received no reply so I posted this question here :)

**Comment by saunders77** [comment]
We try not to publish our planned future schedules because it's common for releases to be delayed by lots of factors.

We've done lots of exciting work on custom functions since the last release, and we'll give you an update at the time of Microsoft Build (May 7-9, 2018).

**Comment by pawsong** [comment]
Thank you. Looking forward to the next Microsoft Build :)
