### ISSUE TITLE
Settings Object could not be loaded when it is saved with difference manifests - from Store vs manually upload

### ISSUE THREAD

**Issue by cpornputthasri** [OfficeDev/office-js#840]
We are using Office.context.documents.settings.set() / .get() to manage settings on a file but when the same file is opened on different manifests, one via Add-in on store and one via manually upload. Each Add-in could not load settings data which was saved from each add-in version.

We also try with Excel.SettingCollection.add() / . getItemOrNullObject() and it gave the same result.

## Expected Behavior
When add-in saves settings data to a file and it should be readable from the same add-in even if it is opened from different environments or even with different manifest version.

## Current Behavior
Settings data which is saved from an add-in which is available on store, could not be read from the same add-in which is manually uploaded.

**Comment by lliu113** [comment]
Thanks for logging this! Looping in Mandy to help investigate

**Comment by JuaneloJuanelo** [comment]
this is by design. Settings are stored per instance per document. The ID of your add-in is not the same when you sideload that when it comes from the store.

**Comment by cpornputthasri** [comment]
@JuaneloJuanelo  Thank you for your response.

In this case, the manifest  from the store is updated, the same file with stored data from the previous version should be readable in the new version, right?

We still do not have any new version of manifest on the store yet. So that, I would like to confirm for this behavior?

**Comment by RuoyingLiang** [comment]
As long as the ID is not changed, the setting should be readable from the new add-in.  Please let us know if you encounter issue after update.
