### ISSUE TITLE
Ability to programmatic update the Excel Add-in cache or other automation way

### ISSUE THREAD

**Issue by lukchen** [OfficeDev/office-js#843]
Hi,

I've posted this feedback on user voice but no response over 2 weeks. It's an important feature to our project so I try to put it here to see if it can be helped or there is exisitng workaround can solve this

The server address in our Excel Addin manifest file often changes, so we are updating the manifest. 
Currently we not only update the manifest but also update the manifest cache so the addin can always get latest manifest.

But even updating the cache(programmatic) is not adequate: only restart excel or click the addin refresh button can apply the manifest cache update.

Is there a programmatic way to do the refresh operation?
![Capture](https://user-images.githubusercontent.com/26646767/68802790-936ddd80-062c-11ea-8f42-1efce3ef1e57.PNG)

thank you!

**Comment by lumine2008** [comment]
Thank you @lukchen for your report, yes, right now we don't have a programmatic way to clean the catch. and I have created a workitem 3783784 to track this issue.

**Comment by lukchen** [comment]
Hi lumine, just curious to know if the workitem is only internally visible or its status can be seen by public?

**Comment by lukchen** [comment]
@lumine2008 Hi, any chance there would be a resolution timeline for this?

**Comment by lukchen** [comment]
Hello @lumine2008  How is it going with this feature?

**Comment by lumine2008** [comment]
Team is still investigating, i will update to this thread once we have made progress. thanks for your understanding.

**Comment by lumine2008** [comment]
Would you please create a uservoice at https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback?category_id=163563 and let's track the feature request at uservoice.
