### ISSUE TITLE
Auto Launch functionality of Word Web Addin is not working as expected

### ISSUE THREAD

**Issue by biswanathc** [OfficeDev/office-js#845]
Hi Team,

We have developed one word web addin which will populate some content after fetching it from DB. We want as soon as user opens the doc the contents are fetched that means addin starts working without user being required to click on addin option in menu.

We have gone through the below link 
https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/develop/automatically-open-a-task-pane-with-a-document.md

This is not working for us. As per the description in the link there are 2 approaches suggested one is making change in manifest xml and other is adding 2 lines of code in office js. Our understanding is both the cases will be executed when addin actually loads. Our requirement is to load the addin on opening document. 

Please suggest if we are missing out anything or this is at all feasible and what is the solution in that case?
@weshi

**Comment by biswanathc** [comment]
@weshi  , @mscharlock Could you please help?

**Comment by AbidRahman-MSFT** [comment]
Hello @biswanathc, thank you for your question.

I understand that you are trying to auto open the add-in when the document is opened. This case is only possible while using the Open XML method. As mentioned in the documentation that you linked, there are two specific code snippets that you need to add to the document, the latter 'taskpane' portion includes a 'visibility' attribute that must be set to '1' if you wish to open the task pane automatically the **first** time a document is opened.

Can you please provide more information regarding your specific failure case, which methods have you tried, as well as the two Open XML code snippets that you have added to your document?

You can also try out the auto-open sample at: https://github.com/OfficeDev/Office-OOXML-EmbedAddin

**Comment by biswanathc** [comment]
Thanks. This has worked for us
