### ISSUE TITLE
Excel CustomFunctionsRuntime initialized twice

### ISSUE THREAD

**Issue by ddanehl** [OfficeDev/office-js#847]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

for our add-in we use the new runtime feature that is documented here:
https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial

when using it in combination with a CustomTab in the ribbon, the runtime will initialize twice but only if a custom function is present on the worksheet.

## Expected Behavior
that the runtime is only initialized once

## Current Behavior
when a custom function is present on the worksheet, the runtime is inizilized.
when user then clicks on the ribbon and opens the taskpane, the runtime gets initialized again.

## Steps to Reproduce
see attached gif that shows the issue. i used the add-in from the tutorial that i linked above.
only thing i did, was adding an CustomTab to the manifest and to the taskpane the Office.onReady function which writes to console 

## Context
we use the Office.onReady event to register some events like onChanged, onSelectionChanged, onSingleClick. due to the current behavior of the runtime, all events are registered twice.
the custom function / browser runtime feature is needed to share session data between taskpane and custom functions as our custom function connect to a database server and in the taskpane is our connection manager.

## Your Environment
* Platform: Online
* Host : Excel
* Office version number: Online 16.0.12313.35057
* Operating System: Win 10
* Browser (if using Office Online): Edge/Chrome/Firefox/Safari/IE11
![browser_runtime_bug](https://user-images.githubusercontent.com/7172621/68879442-b3270380-0709-11ea-9085-59bb062452ee.gif)

**Comment by Katli95** [comment]
Any updates on this? I'm running into an issue which might be related. 
My case is that I am not getting the onReady() event to fire until I open the taskpane :/
