### ISSUE TITLE
Dialog widens itself with Edge control, to fit url in titlebar

### ISSUE THREAD

**Issue by EdwinStraver** [OfficeDev/office-js#848]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When you display a dialog with a given width, and the dialog is too narrow to fit the title, the dialog widens itself to fit the title. This behavior was introduced with the switch from IE to Edge.
This behavior is very undesirable.

**Comment by smaremanda** [comment]
@EdwinStraver - I have an internal bug opened on this one. We will follow up with you if we need more info and will keep you updated on the progress.
Curious does this repro for you on the new Edge Webview2 as well?

**Comment by EdwinStraver** [comment]
I think so, but can you tell me how I can tell for sure if I am using the new Edge Webview 2 ?

**Comment by EdwinStraver** [comment]
For example, here is one of our dialogs we pop up, where Edge is ignoring the specified width:

[Graphical user interface, application  Description automatically generated]

**Comment by smaremanda** [comment]
I cant see the image you uploaded. can you try again? Also, to confirm you are running WebView 2, right click within your taskpane and you should see an option to "Inspect". this will launch the new Edge WebView 2 developer tools.

**Comment by EdwinStraver** [comment]
Yes, we see "inspect", and so we are using Edge.

Here is a screenshot of a dialog that has been widened by the control:

![image](https://user-images.githubusercontent.com/27964706/98989902-9a009080-24de-11eb-8f58-5a689d9e8a69.png)

**Comment by EdwinStraver** [comment]
Note that this only happens if the url is "too long". If Edge wouldn't display the url (which frankly is really what we would like), this problem would not happen.

**Comment by smaremanda** [comment]
Ok got it. we display the URL for security purposes, so the user is aware what is being loaded into the dialog. Let me check to see if there are ways around it - but just to set the expectation, this is likely by design.

**Comment by 4tti** [comment]
I agree with @EdwinStraver that actually it would be nice to have option to not show the URL although I understand the reason why it is being displayed.

**Comment by EdwinStraver** [comment]
Yes, and if it is by design, you probably want to update the documentation for the DisplayDialogAsync, and note that setting the width as described, simply doesn't work.

**Comment by tj-aew** [comment]
How is this different to [the previous version of this issue](https://github.com/OfficeDev/office-js/issues/2242) raised four days earlier? Shouldn't they be combined?
