### ISSUE TITLE
Getting error when add in launched on windows desktop outlook client

### ISSUE THREAD

**Issue by anilreddyr7** [OfficeDev/office-js#849]
When add in is launched on windows 10  - outlook client, we get below error message in side pane.
"Sorry, we couldn't load the app because your browser version is not supported. Click here for a list of supported browser versions". 

This is documented in below office addin documentation.
https://docs.microsoft.com/en-us/office/dev/add-ins/testing/testing-and-troubleshooting#common-errors-and-troubleshooting-steps

We followed those steps, still issue occurs.
 
What can be the reason for this?

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook Client
* Office version number: Office 365 subscription
* Operating System: Windows
* IE11 is installed on PC

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)
![f01a9f2c-75db-416a-b0f0-6b86302b3142](https://user-images.githubusercontent.com/25030206/68932187-11aabb00-07b8-11ea-8621-8197f3e4b917.png)

**Comment by anilreddyr7** [comment]
@exextoc  Hi Team, any clue on this?

**Comment by exextoc** [comment]
What is your Outlook version number?

**Comment by anilreddyr7** [comment]
> What is your Outlook version number?

Outlook Version is 1902 (build 11328.20438). Can you let me know why it occurs?

**Comment by anilreddyr7** [comment]
> > What is your Outlook version number?
> 
> Outlook Version is 1902 (build 11328.20438). Can you let me know why it occurs?

@exextoc Do you see any issue with this build 1902?

**Comment by exextoc** [comment]
What is your IE version? Please check [requirements for running office add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/requirements-for-running-office-add-ins).

**Comment by anilreddyr7** [comment]
> What is your IE version? Please check [requirements for running office add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/requirements-for-running-office-add-ins).

IE version is 11.864.17763.0 . We checked above link and every thing seems good. But not sure why we get the issue?

**Comment by anilreddyr7** [comment]
> What is your IE version? Please check [requirements for running office add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/requirements-for-running-office-add-ins).

We observed on one system. It was working till yesterday. All of sudden, we are facing this issue. 
"Sorry, we couldn't load the app because your browser version is not supported. Click here for a list of supported browser versions."
We observed that outlook is not updated and IE 11 is on the system. Nothing get updated. It sounds strange to us. I suspect that it is happening due to some windows updates. Do you help us here?

**Comment by exextoc** [comment]
Could you try to reset your IE settings to default and see if the issue is still there? If yes, please try to find if add-in can load in IE and other browsers.

**Comment by anilreddyr7** [comment]
> Could you try to reset your IE settings to default and see if the issue is still there? If yes, please try to find if add-in can load in IE and other browsers.

Resetting IE settings didn't help. Add in is working in all browsers. It is not working only in Outlook client. Even in IE browser, it is working fine.

**Comment by exextoc** [comment]
Could you share your windows build number as well. It might also be worth trying if you can use add-ins on other office apps, like say word/excel. Do you see the same error for those clients?

**Comment by anilreddyr7** [comment]
We have observed that task pane add ins are not working in other office apps like word, excel. Just checked MS Word and it is not working as it is in outlook. Kindly suggest what might be issue? Windows 10 details are windows 10 enterprise, Version 1803, OS build: 17134.1069. This is installed very long back.

**Comment by exextoc** [comment]
@anilreddyr7 A couple of options to try out:
- Can you try disabling and re-enabling IE and see if that fixes the issue?
- If that doesn't, try upgrading to Windows Version 1903 to see if this fixes it.
- If none of the above options fix it/are viable, a system repair might help.
Basically it seems like some registry keys for the OS got corrupted which is what the infrastructure is dependent on.

**Comment by anilreddyr7** [comment]
Upgrading outlook to latest build worked for us. Thanks for your help.
