### ISSUE TITLE
Word error when deleting a w:sdt containing a w:tbl

### ISSUE THREAD

**Issue by macote** [OfficeDev/office-js#85]
Word generates an error when deleting a content control that contains a table without a trailing paragraph. The delete method used is [this one](https://dev.office.com/reference/add-ins/word/contentcontrol#deletekeepcontent-bool).

## Expected Behavior
The content control gets deleted.

## Current Behavior
Word displays an error and the current document state seems unstable.

## Steps to Reproduce, or Live Example
[Script Lab](https://gist.github.com/macote/39e341fec8b39a864c72edc9aee24ea1)

## Context
I'm developing a tool that replaces content control content. When I call [insertOoxml()](https://dev.office.com/reference/add-ins/word/contentcontrol#insertooxmlooxml-string-insertlocation-string), I get the same behavior.

## Environment
* Platform: PC desktop
* Host: Word
* Office version number: Office Click-to-Run Version 1803 (9126.2116)
* Operating System: Windows 10

## Useful logs
![Screenshot](https://gist.github.com/macote/39e341fec8b39a864c72edc9aee24ea1/raw/b6e685a36943ce99f73e1306c25e7c16c884e427/Word%2520corrupted%2520table%2520error.png)

**Comment by JuaneloJuanelo** [comment]
Thanks for sending and documenting in detail this issue, I was able to repro. In an ideal world, the order in which you are sending the operations, in a blank doc, should work but in this case is corrupting the document.  This is potentially a bug that we need to fix.

That been said, I  have an alternative you can try. please find a script lab [here](https://gist.github.com/JuaneloJuanelo/234cda159349c6f2bc45a4575107ed3a).

The snippet that I am sharing with you has 2 slight changes from yours:

1. A minor issue which you can delete the first content control without loading the collection.
`    
await Word.run(async (context) => {
        context.document.contentControls.getFirst().delete();
        await context.sync();
    });`

2. The approach that I recommend you to follow in blank documents its not to to insert a paragraph but to replace the existing paragraph in the document. (in every word doc there is at least one paragraph :)). Then insert your content control and table. Then you will be able to delete the content control safely. (and not need to delete the last paragraph, which is what i think is corrupting the doc) 


PLease give it a try and let me know the outcomes.

**Comment by JuaneloJuanelo** [comment]
btw this is tracked internally with 2264713

**Comment by macote** [comment]
Thank you for your suggestions.

Unfortunately, I'm not dealing with blank documents and I have little or no control on the source where the documents come from. I found that if I delete all the tables in the content control first, I'm also able to workaround the issue. But you can understand that this is not ideal.

Is it possible to have more information or an ETA on the internal ticket?

**Comment by JuaneloJuanelo** [comment]
still working on it, given the workaround prioritization was impacted.

**Comment by JuaneloJuanelo** [comment]
This issue is fixed starting on build (Since August, actually sorry for the late update) starting on builds  16.0.12015.10000 +
