### ISSUE TITLE
Is information about installed Office-Add-Ins unintentionally stored redundant?

### ISSUE THREAD

**Issue by SWDevB** [OfficeDev/office-js#852]
I tried to find out how Office (in my case Excel) stores which Office-Add-Ins are installed for a user (for manual installation from store and for centralized deployed store or custom add ins - including versions for Windows, MAC and online) and how this affects the local machine the user is working on. [stackoverflow request here](https://stackoverflow.com/questions/58708719/what-exact-changes-are-made-on-the-installing-computer-while-installing-an-offic)

## Current Behavior
I learned that the registry key `[HKEY_CURRENT_USER\Software\Microsoft\office\16.0\WEF\` and the folder `%LOCALAPPDATA%\Microsoft\Office\16.0\Wef\` are involved. The folder keeps cached data about the add-ins and the registry is at least used to manage this data. 

After deleting the folder and starting Excel the add-ins appeared after some time when they were reinstalled.

After deleting folder and registry key, the add-ins weren't automatically installed, but when I opened the My add-ins area, they still were listed there and after pressing refresh, they were installed again and key and folder were created and populated again.

## Expected Behavior
Since @Rick-Kirkham suggested this might be a bug and asked me to open an issue here, it seems expected behavior would be the add-ins to be gone completely. If instead the expected behavior is the described one, please tell me where the information about the installed add-ins is stored.

## Steps to Reproduce, or Live Example

1. Install a commands containing Excel-Add-In from the office store
2. close Excel
3. open **%LOCALAPPDATA%\Microsoft\Office\16.0\\** and delete the folder **WEF**
4. open regedit
5. navigate to **[HKEY_CURRENT_USER\Software\Microsoft\office\16.0]** and delete Key **WEF**
6. open Excel
7. navigate Insert -> My add-ins -> Tab my MY ADD-INS -> Refresh
8. the formerly installed apps reappear

## Context
I want to ensure my Office-add-in is running properly in various environments. This includes complex environments like terminal server and Citrix solutions or systems with heavily limited user rights.
From former add-ins based on COM and VBA I know that of course the more changes are made on a users system (program folders, system folders, user profile, registry etc.) the more problems can occur while deploying to such environments. Therefore I would like to know the exact changes made while installing an Office-add-in on the client machine. This way it is much easier to find and solve deployment problems when they occur.
In this case for it feels like here is some important documentation missing.

## My Environment
Platform: PC
Host: Excel
Office version number: 365 ProPlus, 1906 (Build 11727.20210 Click-to-Run) 
Operating System: Windows 10 Enterprise 10.0.18362

**Comment by keyur32** [comment]
Hi,

So the locations listed above are correct in that is where we manage the cache of your installed add-ins on windows. The register is also where we register any sideloaded add-ins.

The other way add-ins are acquired is by your identity. Depending on the signed in user, Office will know what add-ins you are entitled to, whether they come from the store or centrally deployed. Once Office knows you have an add-in acquired, it will add the addins and then cache them in the WEF folder/registry.


 @niteshgolchha85 - can comment  if that is inaccurate :)

**Comment by SWDevB** [comment]
Okay, this would mean without identity (Office on premise and not signed in in Office), deleting folder and registry key will remove the add-ins permanently. This then matches my experience from testing that case.

**Comment by SWDevB** [comment]
What about Mac? It probably behaves the same in general, but is there anything involved beside the file system WEF folders?

**Comment by keyur32** [comment]
Sorry for super late response, this has information on the mac: https://docs.microsoft.com/en-us/office/dev/add-ins/testing/clear-cache

Closing for now, feel free to update if you have additional questions
