### ISSUE TITLE
Addin with version 1.8 did not uploaded

### ISSUE THREAD

**Issue by sarea** [OfficeDev/office-js#853]
I'm developing OWA add-in, as the [version 1.8](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.8/outlook-requirement-set-1.8) released I have change the manifest in:
```
  <Requirements>
    <Sets>
      <Set Name="Mailbox" MinVersion="1.8" />
    </Sets>
  </Requirements>
```
and in:
```
      <Requirements>
        <bt:Sets DefaultMinVersion="1.8">
          <bt:Set Name="Mailbox" />
        </bt:Sets>
      </Requirements>
```
when I upload the new manifest from `Get Addins -> my add-ins -> upload new addin`, it did not show any error message, but when I close that dialog I dont see the add-in at all, going back to `Get Add-ins` and I dont see the addin anymore!

Knowing that it work fine when I change the version to `1.7`

## Environment
* Platform: Office Online
* Host: OWA
* Office version number: 
* Operating System: mac
* Browser (if using Office Online): Chrome

**Comment by exextoc** [comment]
Thank you for your feedback. We apologise for any inconvenience or concern that we caused with 1.8 requirement support. We are working on fixing this issue.

**Comment by rickgoud** [comment]
I have the same issue. Any update on this?

**Comment by exextoc** [comment]
@rickgoud we are actively working on this issue. We will update you once we have details.

**Comment by exextoc** [comment]
We have fixed this issue and it will be 100% live in ~1 week.

**Comment by sarea** [comment]
Hi again, posting this here because I think it's related:
The issue above is fixed but when I try to deploy the add-in (v1.8) from the admin portal as file or URL, I got  this error:
```
No Supported Office Products. There are no platforms which fulfil the requirements specified in the manifest. The most common reasons for this failure are issues in the Requirements section. Please review the manifest and try again.
Correlation ID: cf770ed5-41a6-418a-8043-a92b22f69845
``` 
That error did not occur when deploying the same manifest with v1.7 or less
<br />
This issue is occurring only when deploying the add-in through the **admin portal**,  not when adding a new add-in as user.
Thanks

**Comment by exextoc** [comment]
Thank you for reporting this issue. I'm able to reproduce it as well.

I'm checking on the status of this issue in the admin portal.

If you open a new issue, we can close it when the issue is resolved, or we can update this thread at that time. Thanks again!

**Comment by sarea** [comment]
Hi @exextoc
Here is the [new issue](https://github.com/OfficeDev/office-js/issues/1099) 
Thanks
