### ISSUE TITLE
Unexpected Insert Footnotes/Endnotes & Split Window View behavior when using createDocument method

### ISSUE THREAD

**Issue by saraalfadil** [OfficeDev/office-js#854]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

When a document is created and opened using the createDocument method, it causes strange side effects to the Insert Footnotes, Insert Endnotes & Split Window View functionality. 

## Expected Behavior
1. After a new document is created with the createDocument method, using the "Insert footnotes and endnotes" feature should allow the notes to be inserted within the same document.
2. After a new document is created, the Split Window View option should be available.

## Current Behavior
1. After a new document is created using createDocument, using the "Insert footnotes and endnotes" feature causes a new application window to be opened unexpectedly.
2. After a new document is created, the Split Window View is disabled.

## Steps to Reproduce
1. Create a new Word document using createDocument().
2. In the new document, select "References->Insert Footnote" (or "Insert Endnote").
3. A new document window pops up unexpectedly. 

## Steps to Reproduce
1. Create a new Word document using createDocument().
2. Navigate to the "View" tab.
3. The "Split Window" option is disabled.

## Context
We are using the createDocument to programatically open documents store in a database. This issue prevents end users from using the Insert Footnotes, Insert  Endnotes, and Split View features in the newly opened document. 

## Your Environment
* Platform: PC desktop
* Host: Word
* Office version number: Office 365 Version 1910 (Build 12130.20272)
* Operating System: Window 10

**Comment by JuaneloJuanelo** [comment]
Wao thanks for finding this issue . Good catch!  
I was able to repro.

we are tracking internally with 4141351
