### ISSUE TITLE
Missing callback for addFileAttachmentFromBase64Async

### ISSUE THREAD

**Issue by TobiasWolters** [OfficeDev/office-js#857]
When calling `Office.context.mailbox.item.addFileAttachmentFromBase64Async` two or more times successively, the callback isn't consistently triggered for all function calls in Outlook Online.

## Expected Behavior
The provided callback should be triggered once for each call to `addFileAttachmentFromBase64Async`

## Current Behavior
The provided callbacks are sometimes triggered, but sometimes some of the callbacks aren't triggered.

## Steps to Reproduce, or Live Example
- Open Outlook Online
- Start composing an email.
- Open an add-in.
- Call the following code (using [image1.txt](https://github.com/OfficeDev/office-js/files/3857324/image1.txt) and [image2.txt](https://github.com/OfficeDev/office-js/files/3857326/image2.txt)):
```
Office.context.mailbox.item.addFileAttachmentFromBase64Async(<contents of image1.txt>, 'image1.jpeg', callback);
Office.context.mailbox.item.addFileAttachmentFromBase64Async(<contents of image2.txt>, 'image2.jpeg', callback);
```

## Context
The inconsistent triggering of the callbacks makes it impossible for us to provide proper user feedback, when users try attaching images to their emails.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Windows 10 Pro.
* Browser (if using Office Online): Chrome.

**Comment by exextoc** [comment]
Thank you for reporting this issue. We are able to repro this and it has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
This bug has been fixed, closing the issue.
