### ISSUE TITLE
[Outlook add-in]notificationMessages didn's disapear after this.close() (Only happened on Mac)

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#858]
On Mac Outlook 2016(16.32 19111100 ps: lower version might get the same problem too), after 'ExecuteFunction' Notification(xxx is working on your xxx) might not disappear. 

## Expected Behavior
After 'ExecuteFunction' Notification(xxx is working on your xxx) disappeared. Or can be removed.

## Current Behavior

We develop an add-in app. And use some asynchronous function inside it. At last I use event.complete(true) to close it. But we met some problem sometimes on mac Notification(xxx is working on your xxx) might not disappear until timeout. 

I see office.js provide getAllAsync and removeAsync to remove notification. But when I try to get notification ID by getAllAsync I only get {68ACED7-AFB6-4F87-.....}[<0X>]. And this can not use as a ID for removeAsync.

So is this a bug?  Or microsoft already fix it by another api? 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook 2016
* Office version number: 16.32 19111100
* Operating System: Mac

**Comment by exextoc** [comment]
Thanks for reporting this issue. We are aware of this issue and working on it. We unfortunately have no timelines to share at this point.

**Comment by SWei1234** [comment]
> Thanks for reporting this issue. We are aware of this issue and working on it. We unfortunately have no timelines to share at this point.

Okay, if any progress please let me know.

**Comment by exextoc** [comment]
@SWei1234 This issue has been fixed. Please update to the latest Insiders Fast build to get the fix, or wait for the Insiders Slow build to roll out.
