### ISSUE TITLE
isSetSupported method for 1.8 returns false for exchange online

### ISSUE THREAD

**Issue by chopranitin** [OfficeDev/office-js#859]
i am trying to use isSetSupported method to check if it supports latest api or not (1.8 in this case) on different versions of outlook. it gives correct result when used with in outlook client, but when using outllok on web it returns false result even my subscription is office 365

## Expected Behavior

when i am running addin on outlook on web with office 365 subscription Office.context.requirements.isSetSupported("Mailbox", "1.8") should return true

## Current Behavior
the result it returns as false which does not make nay sense

## Steps to Reproduce, or Live Example
just use above specified method

## Context
we need to use enhanced loaction method conditionally on the basis if particular environment support 1.8 api or not. if it does not then disable some features. outlook client seems ok, but outlook on web not. however if you use enhanced location method it works fine on outlook on web , 
## Your Environment

* Platform Office Online: ______
* Host outlook______
* Office version number: ______
* Operating System: windows 10
* Browser (if using Office Online): chrome/ie

**Comment by JuaneloJuanelo** [comment]
Hello ! this is a known issue and we are working on a fix!

**Comment by exextoc** [comment]
We have fixed this issue and it will be 100% live in ~1 week.

**Comment by JuaneloJuanelo** [comment]
Thanks so much for reporting this issue, this is now live! please try and if you find any issues we will re-open this case.
