### ISSUE TITLE
coding suggestion

### ISSUE THREAD

**Issue by lukchen** [OfficeDev/office-js#860]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
Thank you for your understanding and continued feedback.

So It's not a bug but a tiny suggestion that may help the office.js code can be integrated into 2nd party more smoothly. 
I found there are some "delete object" usage in the code, considering js tests may require strict mode so sometimes it would fail to pass build. Using "object = null" can be fine

**Comment by sumurthy** [comment]
@jayrathi is this something we could do? Not sure where this code is.. probably in the loader?

**Comment by lukchen** [comment]
> @jayrathi is this something we could do? Not sure where this code is.. probably in the loader?

What I found were in access-web-16.00.js and debug, and some excel-web js
