### ISSUE TITLE
How to insert custom HTML form into Message's Body in Outlook App in windows using Office-js

### ISSUE THREAD

**Issue by neso613** [OfficeDev/office-js#861]
Hi geeks
I have developing an Outlook add-in using office-js API.
My task is to insert custom HTML form into Message's body of composing mail.

It is working fine with OWA, custom HTML form renders as HTML .But with, Windows Outlook App, it renders as Text.

Can it is possible to insert HTML form into message's body as HTML, not as Text.
Thanks!!
Looking for response.

**Comment by kanaksony** [comment]
Hi, Is there any update? Is this a known bug or broken? 
Thank you for the response.

**Comment by exextoc** [comment]
There are some difference between desktop message body and a browser for Html input. 
Could you please let us know what is the scenario?

**Comment by neso613** [comment]
Hi @exextoc 

Scene is that, there is add-in commands on the ribbon of composing mail. On click of add-in command, a Taskpane is opens. TaskPane have some UI including table with some data.There is Download label and on click of it, I have to create HTML form with some static data having Textbox, checkbox and button.

Now, this HTML form should be rendered as HTML form.


Thing is this, OWA renders HTML form because its `Office.MailboxEnums.BodyType` is HTML.
![OWA1](https://user-images.githubusercontent.com/31642462/69483059-cee88300-0e48-11ea-9ea8-adc8f686b603.png)

But, Outlook Desktop App on windows have  `Office.MailboxEnums.BodyType` is HTML.
But it do not renders HTML form, it gives error, see in image..It renders HTML mark-up tags only like paragraph tag, bold tag, underline tag, breakline tag etc.
![OUTLOOK1](https://user-images.githubusercontent.com/31642462/69483106-3dc5dc00-0e49-11ea-9e87-27f44aff5ca0.png)


Waiting for response.

**Comment by kanaksony** [comment]
Appreciate any update on above. Really want to know if its a limitation that would not behave same on all platforms or a bug?

**Comment by JuaneloJuanelo** [comment]
Can you please attach 
1. the HTML that you are inserting.
2. is your email set to rich text?

**Comment by exextoc** [comment]
This is a limitation that would not behave the same across all platforms.
Outlook uses Word to render HTML.
Word converts any input HTML to Word's native format/elements/objects.
Due to this, not all HTML elements appear as they would in a browser.

**Comment by kanaksony** [comment]
> This is a limitation that would not behave the same across all platforms.
> Outlook uses Word to render HTML.
> Word converts any input HTML to Word's native format/elements/objects.
> Due to this, not all HTML elements appear as they would in a browser.

@exextoc this is disappointing for me and my client. 

Can you please suggest if there is any other way we can achieve this functionality using available APIs, may be I am not aware of one that can do the needful?

My client has a survey product, so this add-in will help the sales people to populate forms inside mail body which they created on backend before.

**Comment by exextoc** [comment]
This sounds like an ideal candidate for [actionable Messages](https://docs.microsoft.com/en-us/outlook/actionable-messages/send-via-email) instead.

**Comment by neso613** [comment]
@exextoc Thanks for making it clear.
