### ISSUE TITLE
Office Word Add-In Chinese garbled when get html from document body

### ISSUE THREAD

**Issue by ZhouHansen** [OfficeDev/office-js#862]
I am going to display the content of the current word document on Add-in Taskpane, I can achieve this simple task by calling [context.document.body.getHtml()](https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#gethtml--) from which gets an HTML representation of the body object. 

But the chinese characters in this html is garbled which means they represent nothing. 

Hope someone can help. Thanks

## Expected Behavior

Calling [context.document.body.getHtml()](https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#gethtml--) get html contains correct Chinese characters.
## Current Behavior

Calling [context.document.body.getHtml()](https://docs.microsoft.com/en-us/javascript/api/word/word.body?view=word-js-preview#gethtml--) get html contains garbled Chinese characters.

For example： 

我爱我的家(I love my family) becomes 辨瀹都(Nobody knows what is this)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]:  Mac 
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 16.31
* Operating System: macOS 10.15.1

**Comment by weshi** [comment]
Thanks for reporting this. I can reproduce this issue on Word for MAC. It works correctly on Word for Windows and Word for Web. We will do further investigation on the MAC.

**Comment by yihuax-zz** [comment]
Hansen, Could you try getOoxml instead of getHtml and see? Thanks!

**Comment by ZhouHansen** [comment]
getOoxml works fine.

**Comment by hjkim-MSFT** [comment]
Thanks for reporting this issue. Microsoft identified the problem. We're working on the fix.

**Comment by hjkim-MSFT** [comment]
This problem has been fixed. Word for Mac 16.34 (20010700) or higher builds should contain the fix.
