### ISSUE TITLE
Is it possible Excel Addin provide an option makes the internal browser client to trust localhost webserver with self signed certificate?

### ISSUE THREAD

**Issue by lukchen** [OfficeDev/office-js#864]
Due to security concerns, I have closed some previous issues that relates to making excel work with localhost webserver with self signed certificate. I think a standard way might be the solution if possible.

Is it possible for Excel Addin to configure the browser to trust https localhost webserver without explicitly instlalling certificate into system browser? So there wont be annoying security warnings.
I know the main use case is to use Excel Addin with valid domain&certificate. My case is exposing our desktop software's web based visulization tool in Excel, and I believe there are many same needs in the market.

**Comment by lukchen** [comment]
@lumine2008 Hello, is it possible to be in backlog or any interesting update?

**Comment by lukchen** [comment]
Hello @lumine2008 @slabereemsft , just want to check what's your team's decision on this: is it doable and can be developed?

**Comment by lindalu-MSFT** [comment]
If you're still interested in adding this feature, please go to our new [Ideas forum](https://aka.ms/m365dev-suggestions) and click **Submit an Idea**. If there's enough interest (votes), we will follow up with you there and add it to our feature request backlog. Please add link to the suggestion in the comments for tracking. Thanks, lindalu
