### ISSUE TITLE
Office.context.mailbox.item.addHandlerAsync api  not work after the iframe redirect or reload on MacOS chrome browser Office365 Outlook

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#865]
For example:
Open "My Templates" add-on which every office365 outlook have this add-on. And open the developer tools in chrome. then select the "My templates" execute context. like the screen shot.
![image](https://user-images.githubusercontent.com/1878089/69331027-06133480-0c8f-11ea-9a04-41479015a114.png)
![image](https://user-images.githubusercontent.com/1878089/69331050-12978d00-0c8f-11ea-909c-ef7c74c26f39.png)
For the first time, when i execute Office.context.mailbox.item.addHandlerAsync, it  works when i change the meeting time in the appointment:
```
function handleAppointmentTimeChange() {
    console.log('111');
}

Office.context.mailbox.item.addHandlerAsync(Office.EventType.AppointmentTimeChanged, 
handleAppointmentTimeChange);
```

But when i redirect the page like execute the below code:
```
location.href = location.href
```

then re-execute the addHandlerAsync code like:
```
function handleAppointmentTimeChange() {
    console.log('111');
}

Office.context.mailbox.item.addHandlerAsync(Office.EventType.AppointmentTimeChanged, 
handleAppointmentTimeChange);
```
it doesn't work when i change the meeting time in the appointment.
This api works well on the outlook mac client.

Please track the issue, thanks~

**Comment by exextoc** [comment]
Thank you for reporting this issue. We are able to repro this and it has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by hello-chenchen** [comment]
hi @exextoc , thank you for your reply. Have got it.
Another high level question for the redirect:
When my manifast.xml for example like below:
```
.............
  <AppDomains>
    <AppDomain>google.com</AppDomain> 
    <AppDomain>google.com.hk</AppDomain>
  </AppDomains>
......
  <FormSettings>
    <Form xsi:type="ItemRead">
      <DesktopSettings>
        <SourceLocation DefaultValue="https://google.com/application-xxx"/>
        <RequestedHeight>250</RequestedHeight>
      </DesktopSettings>
    </Form>
  </FormSettings>
........
<bt:Urls>
        <bt:Url id="messageReadTaskPaneUrl" DefaultValue="https://google.com/application-xxx"/>
 </bt:Urls>
.........
```
So, when my add-on first request must be **https://google.com/application-xxx**, but the backend response set **307 Temporary Redirect** status code and set the Location header to "https://google.com.hk/application-xxx". And the whole add-on will be crashed like below:
￼￼
![image](https://user-images.githubusercontent.com/1878089/69616571-cfb02d80-1071-11ea-9280-4dd6c7157de9.png)

And the Error Message in console is:

```
outlook-web-16.01.js:16 Uncaught Function ContextActivationManager_getAppContextAsync call failed. ErrorCode is -2, exception: Failed origin check
u @ outlook-web-16.01.js:16
ot @ outlook-web-16.01.js:16
```

I don't know if it is a bug for the office365, or just the architecture design.
Please confirm if it is a bug. If not, could you please share a prefect solution to solve my problem?
Any info you can pass would be appreciated~

**Comment by exextoc** [comment]
We are unable to repro this. Can you share repro steps? Also share code snippet which you are using for redirect. Is it same code which you shared earlier?

**Comment by hello-chenchen** [comment]
Actually, it is not the frontend code behavior.
I just designated the entrance url to my web server application in the mainfast.xml, for example "https://google.com/application-xxxx". But my web server(nginx) set response code to **307 Redirect ** status code and Location header to "https://google.com.hk/application-xxx". For example:
![image](https://user-images.githubusercontent.com/1878089/69794511-5ea17f00-1205-11ea-8eb8-c117f7abc7df.png)

![image](https://user-images.githubusercontent.com/1878089/69794532-682ae700-1205-11ea-990e-057ee8d89163.png)

you can image that the  redirect url is "google.com.hk" and then it will cause the add-on service unreachable. like below:
![image](https://user-images.githubusercontent.com/1878089/69794881-0c149280-1206-11ea-91a9-4fa9df979b0f.png)

**Comment by hello-chenchen** [comment]
happy Thanksgiving

**Comment by exextoc** [comment]
@hello-chenchen This seems like a different issue to the one originally mentioned in your post. Could you please start a new issue for this so we have more clarity?

As for your initial addHandlerAsync issue, we unfortunately don't have timelines for the fix yet - but one workaround you could do is call removeHandlerAsync and addHandlerAsync again after the redirect.

**Comment by hello-chenchen** [comment]
@exextoc okay, i will log a new issue for this one, and sorry for not describe the problem not clearly.
I will try to give you some demo code to simulate the backend server behavior and manifest.xml for how to repro this problem in the next few days.

**Comment by hello-chenchen** [comment]
hi @exextoc , for the  initial addHandlerAsync issue, i try to use your workaround solution, but it seams not work for me.

what the demo code when after the redirect:
```
function handleAppointmentTimeChange() {
    console.log('111');
}

Office.context.mailbox.item.removeHandlerAsync(Office.EventType.AppointmentTimeChanged, 
handleAppointmentTimeChange);

Office.context.mailbox.item.addHandlerAsync(Office.EventType.AppointmentTimeChanged, 
handleAppointmentTimeChange);
```

**Comment by exextoc** [comment]
@hello-chenchen Could you make sure you call addHandlerAsync in the callback for removeHandlerAsync? We want to make sure we don't do an addHandler before the previous one is removed.

Like so:

```
Office.context.mailbox.item.removeHandlerAsync(Office.EventType.AppointmentTimeChanged, 
function(result) { 
if (result.status === Office.AsyncResultStatus.Failed) {
        console.log("failed with " + JSON.stringify(result));
      }
      else {
        Office.context.mailbox.item.addHandlerAsync(Office.EventType.AppointmentTimeChanged, handleAppointmentTimeChange);
      }
});

```

**Comment by hello-chenchen** [comment]
@exextoc , please see the screen shot below. Is this the sequence of execution you want? which from the console on the right side. Or could you share your demo code and the sequence of execution to make this work?
![image](https://user-images.githubusercontent.com/1878089/70126122-4e7d1a00-16b3-11ea-8f16-53508c0ce4f8.png)
there is no any change or console log when i change the end Time

In fact, this problem is not a big deal for my production feature, i can wait for your final solution to fix this bug.

It seams too late for the american time, you can reply me tomorrow. Good night~

**Comment by exextoc** [comment]
Sorry, looks like the workaround also has the same issue. This has been put in our backlog.

**Comment by hello-chenchen** [comment]
all right, got it. thanks~
