### ISSUE TITLE
dynamic resize displaydialogAsync based on the container input

### ISSUE THREAD

**Issue by sourabhkrishna** [OfficeDev/office-js#868]
Is it possible to have a dynamic height and width for the displaydialogAsync ? If so , how ?
I would need to edit the Dialog header to a custom html for an Outlook Add in - OnSend

My OnSend Add-in opens a dialog and I want to have custom CSS applied to the dialog style parameters.

**Comment by exextoc** [comment]
Thanks for the questions. Can you provide following details?
Which office application are you working on?
Which variant of application are you using Windows App, MAC App or Web App? What is the version?

Also, have you tried following as per documentation at https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins

By default, the dialog box will occupy 80% of the height and width of the device screen, but you can set different percentages by passing a configuration object to the method, as shown in the following example:
Office.context.ui.displayDialogAsync('https://myDomain/myDialog.html', {height: 30, width: 20});

**Comment by sourabhkrishna** [comment]
I'm working on the OnSend Outlook Add In Web App.
The Dialog will be hosting my React OWA Addin. I'm looking to have dynamic height/width set based on the components I navigate in my react app.

Having this config object as suggested by you Office.context.ui.displayDialogAsync('https://myDomain/myDialog.html', {height: 30, width: 20}); means , the dialog is set to 30vh and 20vh. It wouldnt adjust basis my react app that is loading on this dialog.

I was exploring ways where in we can set custom values to the Dialog Header and edit/set the css for all Dialog properties.

**Comment by exextoc** [comment]
Currently the feature to adjust display dialog height and width depending on page which is being loaded in dialog is not supported. We track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered, when we go through our planning process.
