### ISSUE TITLE
Office (Excel) online doesn't validate manifest

### ISSUE THREAD

**Issue by SWDevB** [OfficeDev/office-js#869]
When uploading a manifest file in Office online, via "Upload My Add-in", it seems the manifest isn't validated, because I was able to run a invalid manifest file.

## Expected Behavior
I expect Office to reject the uploaded file. I wouldn't expect a detailed message but something like "The uploaded file isn't a valid manifest" would be appropriate 

## Current Behavior
I would like to support custom functions from different namespaces in one add-in. So the recommendation to achieve that was not to use namespaces at all, instead the namespace and the dot can used within the function's name. The fist try to do so was just removing the text from the respective sting configuration in the manifest 

`<bt:String id="Functions.Namespace" DefaultValue=""/>`

Uploaded into Office online, and a function with namespace and one without were working perfectly fine. But Excel desktop wasn't even able to load the add-in while trying to debug. 

After some time I figured out that removing the complete tag for Functions.Namespace worked for both Excel versions, after then validating both versions I knew the problem. I additionally remove the namespace tag `<Namespace resid="Functions.Namespace"/>` and wondered why it even worked with a reference to a non existent string definition...

## Steps to Reproduce, or Live Example

1. create custom functions project using yo office
2.  remove content of default value Functions.Namespace string
3.  run server
4.  upload manifest to Office online -> works
5.  debug in Excel desktop -> broken

## Context
Functions with different or non namespaces needed

## Your Environment
Platform: PC
Host: Excel
Office version number: 365 ProPlus, 1906 (Build 11727.20210 Click-to-Run)
Operating System: Windows 10 Enterprise 10.0.18362
Browser: Chrome

**Comment by keyur32** [comment]
Closing this out as this has been fixed now. Excel for web should have consistent behavior with Desktop now.
