### ISSUE TITLE
When network is disconnected, Office.context.mailbox.makeEwsRequestAsync will block

### ISSUE THREAD

**Issue by zhoukq** [OfficeDev/office-js#870]
Follow https://github.com/OfficeDev/office-js/issues/788, we use `Office.context.mailbox.makeEwsRequestAsync` to get all recipients info.
But when the network is disconnected, this API call will hang and never return.

This issue can reproduce in Mac desktop application 

## Expected Behavior
Make the API return timeout error in a reasonable time when the network is disconnected
Or
Make us can set the timeout value for this API

## Steps to Reproduce, or Live Example
Follow the code example in https://stackoverflow.com/questions/58289577/is-there-a-way-to-get-all-recipients-in-to-or-cc-fields 
When the network is down, 
the callback in 
` mailbox.makeEwsRequestAsync(request, (result) => {
    if (result.error) {
      reject(result.error);
    } else {
      const value = parseGetItemSoapResponse(result.value);
      resolve(value);
    }
  });`
will never triggered.

## Your Environment

* Platform [Mac]
* Host [Outlook]
* Office version number: Outlook 16.31(19111002)
* Operating System: 10.15.1

**Comment by slabereemsft** [comment]
Anjana, this is reported against Mac so sending your way first.

**Comment by exextoc** [comment]
Thank you for reporting this issue. We are able to repro this and it has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: Office:3806579

**Comment by neprasad-microsoft** [comment]
This issue is not reproducible anymore.
