### ISSUE TITLE
[Outlook] Office.UserProfile.displayName returns e-mail address instead of display name

### ISSUE THREAD

**Issue by ambachtelijk** [OfficeDev/office-js#872]
When the display name in Outlook is requested from the user profile by calling `Office.context.mailbox.userProfile.displayName`, their e-mail address is returned instead. Similarly, the `emailAddress` and `timeZone` properties appear to represent the wrong properties in [the documentation](https://docs.microsoft.com/en-us/javascript/api/outlook/office.userprofile?view=outlook-js-1.8).

## Expected Behavior
When `Office.context.mailbox.userProfile.displayName` is called, the display name of the user is returned, which should be equal to the name that is shown as sender in e-mails.

## Current Behavior
When `Office.context.mailbox.userProfile.displayName` is called, the e-mail address of the user is returned.

## Steps to Reproduce, or Live Example
Run the following code in a side-loaded plugin in Outlook and verify that the not the display name, but e-mail address is printed to the console. 
```JavaScript
console.log(Office.context.mailbox.userProfile.displayName);
```

## Context
I'm trying to compose a new e-mail message with `Office.context.mailbox.displayNewMessageForm` that includes a signature with the user's display name.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: Version 1911 Build 12228.2250
* Operating System: Windows 10
* Browser (if using Office Online): -

**Comment by exextoc** [comment]
We cannot reproduce this issue on recent builds of outlook. Can you try recreating a profile on Outlook and trying to see if that fixes it? Does it happen on all emails, read as well as compose? What happens after you restart outlook or is it always reproducible? Can you also maybe try on a different machine with the same account?

**Comment by gitcnd** [comment]
I am having the same problem.  It is easily reproduced.
Load the ScriptLab sample "Get from (message compose)" and click the "Who is this from?" button - the answer wrongly returns the email address in place of he name.
The same problem exists for both Office.context.mailbox.item.from.getAsync as well as Office.context.mailbox.userProfile.displayName

**Comment by exextoc** [comment]
@gitcnd could you please provide more info about the platform where you are facing this issue. As mentioned in the description, this bug is for Outlook for Windows. However, it is not reproducible there.
