### ISSUE TITLE
PowerPoint web: goToById doesn't work when presenting

### ISSUE THREAD

**Issue by gordonmleigh** [OfficeDev/office-js#875]
When the slideshow has started, `goToById` doesn't change the current slide.

Possibly related: #35 

## Expected Behavior
During presenting mode `goToById` should change the currently visible slide.

## Current Behavior
Nothing happens

## Steps to Reproduce, or Live Example
1. Open a slideshow on PowerPoint web and start the slideshow
2. Run `Office.context.document.goToByIdAsync(Office.Index.Next,Office.GoToType.Index, () => {})` from an add-in or DevTools console.
3. Nothing happens.

## Context
I'm trying to control the slideshow from the add-in, which works on desktop.

## Your Environment
* Platform: Office Online
* Host: PowerPoint
* Office version number: web
* Operating System: MacOS
* Browser (if using Office Online): Chrome 78

**Comment by donlvMSFT** [comment]
Hi @gordonmleigh , Thank you for reaching us!
I try `goToByIdAsync` API with my simple test add-in but it works well in PowerPoint Online. So we need more information to reproduce the issue.

- If your add-in is in the store, could you let us know the name? 
- If not, could you kindly share the testing snippet with us?

That will be really helpful to us! Thanks!

**Comment by gordonmleigh** [comment]
@donlvMSFT see my repro repository here: https://github.com/gordonmleigh/repro-officejs-875

Click "Run" to start changing the slide every second. Click "Stop" to stop it.

When in edit mode, the slide changes (though it seems to select the slides in the sidepane which doesn't happen on other platforms).

After clicking "Play from beginning" to start the slideshow, the slide doesn't change. This works fine on Mac and Windows.

**Comment by gordonmleigh** [comment]
The repro code is in taskpane.js:

https://github.com/gordonmleigh/repro-officejs-875/blob/1fdc8eaa232d461f9f456c0b23ca4e5c4e40b1e5/src/taskpane/taskpane.js#L21-L35

**Comment by donlvMSFT** [comment]
Thanks @gordonmleigh , I could repro this issue using your add-in.

I have open an internal bug 3809617 to track, will come back when there's any update.

I notice you use setInterval() to run the API, and the API `goToById` runs well separately, So do other APIs work well using setInterval(), like insert some text? 

What you provide for us is helpful to resolve the issue.

**Comment by gordonmleigh** [comment]
I also reproduced this by just running the `goToById` call from the console. I doubt `setInterval()` has anything to do with it. Can you share with me the code you say works?

**Comment by donlvMSFT** [comment]
This is a content add-in I used, which jump to next page when click `Go To Next Page` button, it works well in presenting mode. Can you take a try?

https://github.com/donlvMSFT/officejs-goToById/blob/master/GoToById.xml

The code is like:

```javascript
    function goToSlideByIndex() {
        var goToFirst = Office.Index.First;
        var goToLast = Office.Index.Last;
        var goToPrevious = Office.Index.Previous;
        var goToNext = Office.Index.Next;

        Office.context.document.goToByIdAsync(goToNext, Office.GoToType.Index, function (asyncResult) {
            if (asyncResult.status === "failed") {
                showNotification('Action failed with error: ', asyncResult.error.message);
            }
            else {
                showNotification("Navigation successful");
            }
        });
    }
```

**Comment by gordonmleigh** [comment]
@donlvMSFT This really doesn't need my feedback for you to look at it, I've clearly identified a problem and you have confirmed a repro. I'll try your code anyway and get back to you shortly.

**Comment by jipinshi** [comment]
Sorry to let you know until now this is by design, and the work is not on the recent plate.

**Comment by jipinshi** [comment]
If you still think this is high demanded, please go to https://officedev.uservoice.com to submit the feature request.
