### ISSUE TITLE
FQDN name in the manifest file is not working.

### ISSUE THREAD

**Issue by rakeshgorak** [OfficeDev/office-js#876]
Hello,
We are working on the Excel Addin using Office-js, and used a manifest file to load our Excel Addin. 
In the Manifest file, if the URL is used with localhost the addin is loaded properly, but when it is used with FQDN name Addin is not loaded and the page is empty. 
<DefaultSettings>
    <SourceLocation DefaultValue="http://machinename.domainname.com:portNum/ExcelAddIn/index.html" />
  </DefaultSettings>
Any help will greatly be appreciated.

**Comment by slabereemsft** [comment]
Hi Rakeshgorak,

If I understand correctly, your add-in manifest is still loading correctly in that an icon appears on the ribbon and you can click it but it fails to render the page.

If so, the best way to diagnose is to run Fiddler to intercept the traffic from the edge process associated with Excel to see what url it is trying to load and the response code.

**Comment by rakeshgorak** [comment]
There was a compatibility issue when added the below tag in the html file header. it worked.

meta http-equiv="X-UA-Compatible" content="IE=edge"

**Comment by slabereemsft** [comment]
Thanks for replying back and letting us know that you solved it.

**Comment by lakeman** [comment]
I can't find any mention in the online documentation that this tag is required, eg [1](https://docs.microsoft.com/en-us/office/dev/add-ins/overview/office-add-ins-fundamentals#accessing-the-office-javascript-api-library) [2](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/referencing-the-javascript-api-for-office-library-from-its-cdn). Nor is any error or warning displayed to the user / developer if this tag is missing. Making the experience of building an addin, without using one of the pre-defined templates, potentially very frustrating.
