### ISSUE TITLE
Office.context.mailbox.item.enhancedLocation.addAsync not working OWA - Exchange 2019

### ISSUE THREAD

**Issue by t-soares** [OfficeDev/office-js#878]
When calling the Office.context.mailbox.item.enhancedLocation.addAsync from a add-in inside the web outlook connected to a Exchange 2019 on-premise, it returns an error: 

```
OSF.DDA.Error {name: "Host Error", message: "The operation is not supported.", code: 5000}
code: 5000
message: "The operation is not supported."
name: "Host Error"
```
The test team claims that this was working before.

## Expected Behavior
It should add the location to the meeting

## Current Behavior
An error is being thrown.

## Steps to Reproduce, or Live Example
Call the Office.context.mailbox.item.enhancedLocation.addAsync  from a add-in inside the web outlook connected to a Exchange 2019 on-premise.

## Your Environment
* Platform: OWA
* Host: OWA Web Outlook
* Office version number: Exchange 2019 - 15.2.464.5
* Operating System: Windows
* Browser (if using Office Online): Chrome

**Comment by JuaneloJuanelo** [comment]
Yes, its working as expected. The enhanced location APIs are included in the 1.8 requirement set which is supported in Exchange Online. This functionality is not backported. 

please check [this page](https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets) for more info:
