### ISSUE TITLE
Office App - Word Task Pane - Cross window communication stopped working

### ISSUE THREAD

**Issue by dankurtzGR** [OfficeDev/office-js#879]
We have a office app for Word - a task pane
The task pane is a web page that has links to pop open other pages

## Expected Behavior

Open another page in javascript : 

javscript code:
var myChildWindow = window.open ("https://samedomain.com/popuppage.aspx","_blank","")

 myChildWindow   should be accessible since its in the same origin as our task pane app page

## Current Behavior
Until about two weeks ago, the myChildWindow variable was accessible.
We have been unable to identify what patches / updates may have been installed that has started to cause this code to no longer work.

Also, we tested the same task page - web page code in IE directly and it works fine

## Context
We're trying to have a dialog window and need to know when its closed so we can refresh our task pane page 

## Your Environment
This is Office 365 - word build 10730.20280
We tried downloading the latest office.js - same result
App manifest contains the domains involved 

Our apps manifest - with our company's info obfuscated

<OfficeApp xmlns="http://schemas.microsoft.com/office/appforoffice/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="TaskPaneApp">
  <Id>0030c0c4-8265-4745-bf69-0d992cd94de1</Id>
  <Version>1.0.0.0</Version>
  <ProviderName>Our company</ProviderName>
  <DefaultLocale>en-US</DefaultLocale>
  <DisplayName DefaultValue="Name" />
  <Description DefaultValue="Build Date: 11/25/2019"/>
  <IconUrl DefaultValue="https://ourdomain.com/SiteAssets/logo.png" />
  <SupportUrl DefaultValue="https://url" />
  <AppDomains>
    <AppDomain>https://subdomain.ourdomain.com</AppDomain>
  </AppDomains>
  <Hosts>
    <Host Name="Document" />
    <Host Name="Workbook" />
  </Hosts>
  <DefaultSettings>
    <SourceLocation DefaultValue="https://subdomain.Ourdomain.com/" />
  </DefaultSettings>
  <Permissions>ReadWriteDocument</Permissions>
</OfficeApp>

**Comment by slabereemsft** [comment]
@jeremy-msft @shaofengzhu - This sounds like a regression though this is an older build of Office for Desktop so perhaps its a known regression?

**Comment by dankurtzGR** [comment]
We determined that Word needed to be running with elevated rights for this behavior to work.  On our side those rights were recently removed, which triggered the issue to start happening
