### ISSUE TITLE
displayDialogAsync problem on 16.0.12130.20390

### ISSUE THREAD

**Issue by Barax67** [OfficeDev/office-js#880]
I developed an Outlook addin to integrate some reservation functionalities from our system (access control). The addin work as expected with Office version 16.0.11328.20468.
## Expected Behavior

CallingdisplayDialogAsync with a valid url, the addin execute the navigation
## Current Behavior

Calling displayDialogAsync with a valid url, the addin do not execute the navigation so the content is never loaded and the dialog is never displayed.
No error is catched; no callback is fired;

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
This is the precise line of code that suffer the problem

Office.context.ui.displayDialogAsync('valid_url',
                        function (asyncResult) {
                            dialog = asyncResult.value;
                            dialog.addEventHandler(Office.EventType.DialogMessageReceived, processMessage);
                            dialog.addEventHandler(Office.EventType.DialogEventReceived, processEvent);
                        }
                    );
## Context

We provide an extension of informations while the customere arrange a metting letting him chose a meeting room whit given characteristics. The addin show a view of custom data provided by the access control system.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop / Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.0.12130.20390
* Operating System: Windows 10 Pro
* Browser (if using Office Online): Edge

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
Could you give us the following information to clarify?

1. Is it happening in Desktop Outlook and Edge both?
2. You mention that it was working in Desktop version 16.0.11328.20468. Was it working on Edge at the time?
2. Could you post the _exact_ code snippet that reproduces the error (without the URL)? (we are not able to repro using the code you provided)
3. Could you try a different URL and tell us if it works? eg. 'https://github.com'

**Comment by Barax67** [comment]
1) Yes
2) No, the first try of this addin was tested only against Outlook Desktop version
3) See at the end of this message; tested passing GitHub.com as URL
4) I tried now, same result

-----------------------------------
FunctionFile.js source code

`
var passedCid = "";
var dialog;

Office.initialize = function () {
    passedCid = getParameterByName("cid");
    console.log(" *** cid: " + passedCid);
};

function getParameterByName(name, url) {
    if (!url) url = window.location.href;
    name = name.replace(/[\[\]]/g, '\\$&');
    var regex = new RegExp('[?&]' + name + '(=([^&#]*)|&|#|$)'),
        results = regex.exec(url);
    if (!results) return null;
    if (!results[2]) return '';
    return decodeURIComponent(results[2].replace(/\+/g, ' '));
}

function launchApp(event) {

    var item = Office.context.mailbox.item;

    var start = undefined;
    var end = undefined;

    var iExecute = 2;

    localStorage.setItem("emailAddress", Office.context.mailbox.userProfile.emailAddress);
    localStorage.setItem("displayName", Office.context.mailbox.userProfile.displayName);

    item.start.getAsync(function (asyncResult) {
        if (asyncResult.status !== "failed") {
            console.log(" *** G.1");
            start = asyncResult.value;
            localStorage.setItem("start", start);
            console.log(" *** G.2");
            iExecute--;
            if (iExecute === 0) {
                getContent(event);
            }
        }
        else {
            console.log(" *** asyncResult start failed");
        }
    });

    item.end.getAsync(function (asyncResult) {
        if (asyncResult.status !== "failed") {
            console.log(" *** F.1");
            end = asyncResult.value;
            localStorage.setItem("end", end);
            console.log(" *** F.2");
            iExecute--;
            if (iExecute === 0) {
                getContent(event);
            }
        }
        else {
            console.log(" *** asyncResult end failed");
        }
    });

}

function getContent(event) {
    var asyncResult = null;
    console.log(" *** BEFORE H");
    try {
        Office.context.ui.displayDialogAsync('https://gtihub.com', 
            function (asyncResult) {
                console.log(" *** H");
                dialog = asyncResult.value;
                dialog.addEventHandler(Office.EventType.DialogMessageReceived, processMessage);
                dialog.addEventHandler(Office.EventType.DialogEventReceived, processEvent);
            }
        );
    } catch (e) {
        console.log(e);
    }
    console.log(" *** AFTER H");

    event.completed();
}

function processMessage(arg) {
    var item = Office.context.mailbox.item;
    item.requiredAttendees.addAsync([arg.message]);
    dialog.close();
}

function processEvent(arg) {
    if (arg.error === "12006")
        dialog.close();
}

// Helper function to add a status message to the info bar.
function statusUpdate(icon, text) {
    Office.context.mailbox.item.notificationMessages.replaceAsync("status", {
        type: "informationalMessage",
        icon: icon,
        message: text,
        persistent: false
    });
}

function defaultStatus(event) {
    statusUpdate("icon16", "Hello World!");
}
`

The browser console shows the following log messages
*** cid: 9808A69F-11E6-45FF-9DF7-C8CD7E5EA111
Agave.HostCall.IssueCall
Agave.HostCall.ReceiveResponse
 *** G.1
 *** G.2
 *** F.1
 *** F.2
 *** BEFORE H
 *** AFTER H

**Comment by exextoc** [comment]
We are able to run your code and it works for us. We get the following log messages:

 *** G.1
 *** G.2
 *** F.1
 *** F.2
 *** BEFORE H
 *** AFTER H
Agave.HostCall.ReceiveResponse
 *** H

Can you try running the same code in a task pane add-in instead of UILess? Does it still not work? We are trying to get to the root of the problem.

**Comment by Barax67** [comment]
Do you mean using this kind of section in the addin manifest

```
 <Action xsi:type="ShowTaskpane">
    <SourceLocation resid="messageReadTaskPaneUrl" />
 </Action>
```

instead of this one

```
 <Action xsi:type="ExecuteFunction">
    <FunctionName>launchApp</FunctionName>
 </Action>
```

**Comment by exextoc** [comment]
Yes, it needs to also have an HTML page that includes the JS file. You can call the launchApp function in Office.initialize (cannot have a FunctionName element in type="ShowTaskpane").

**Comment by Barax67** [comment]
Ok thanks. I'll try tomorrow morning.

**Comment by Barax67** [comment]
I tried the taskpane way but do not know how to pass the "event" parameter to the launApp function. In any case, despite a couple of exceptions, the taskpane asks me to open a new window and I see the expected content.

**Comment by Barax67** [comment]
I have to apologize but I made a mistake in reporting the error; the Office version with which I am developing and testing the addin is the 18.1910.1283.0. Sorry

**Comment by Barax67** [comment]
Is there anything new on this issue?

**Comment by exextoc** [comment]
Hey @Barax67,

Sorry for the late response. I do see the issue here, and i believe the problem is here:

```
console.log(" *** AFTER H");
event.completed();
}
```

`event.completed()` should only be called after your UIless add-in execution is done. Since this is being synchronously called, it is killing the dialog as soon as it's launched. Remove it, and and add the line only after the entire lifecycle of your add-in is over. See if this helps.

**Comment by Barax67** [comment]
Yes! I tried and now the addin works properly. Thank you so much for your support.

Ax
