### ISSUE TITLE
Rich Api error at context.sync() when trying to insert html input fields into a content control using InsertHtml method

### ISSUE THREAD

**Issue by biswanathc** [OfficeDev/office-js#881]
I am trying to insert the below html into a content control using word api i am getting Richapi error at content.sync()

html Code with checkbox:

<html>
<head>
</head>
<body>
<input type='checkbox'/>
<p>Click the checkbox</p>
</body>
</html>

code used to insert html into Content Control:

function InsertHtml() {
        Word.run(function (context) {

            var Html = "<html><head></head><body><input type='checkbox' />click on check box</body></html>";
            var DynamicControl = context.document.contentControls.getByTag("Test").getFirstOrNullObject();

            DynamicControl.insertHtml(Html, Word.InsertLocation.replace);     

            return context.sync().then(function () {
                {
                   write('Inserted HTML in the first content control.');
                }

            });
        })
            .catch(errorHandler);
    }

with this code i am getting below error at context.sync()

GeneralException: GeneralException

   at Anonymous function (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.01.js:24:287994)
   at T (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.01.js:24:220903)
   at x (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.01.js:24:220989)
   at t (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.01.js:24:220797)
   at l (https://appsforoffice.microsoft.com/lib/1.1/hosted/word-win32-16.01.js:24:219304)

Same code is working as expected with html which doesnt have any input field control like Checkbox,Textbox ,text area. Example like below

html code without checkbox:

<html>
<head>
</head>
<body>
<p>Test Html</p>
</body>
</html>

Version of Word: Office 365 Desktop Pro Plus
Api version: 1.3

Please help on this issue as this is critical to our business.

**Comment by biswanathc** [comment]
@weshi

**Comment by weshi** [comment]
You cannot use insertHTML API to insert check box, etc. These are special controls in Word that are not supported to be added by this API.

**Comment by biswanathc** [comment]
Thanks
