### ISSUE TITLE
Not able to pass parameter from html to word using query string/any alternative 

### ISSUE THREAD

**Issue by biswanathc** [OfficeDev/office-js#882]
Hi team,

I am working on word addin project. Target environment is Office 365 Pro plus desktop and api version is 1.3.

My word document opens from one html based application. On click of a hyperlink, I am using uri scheme to auto open the document. My requirement is to track which user is opening the document. For this I wanted to pass user ID value through querystring like below

https://mydomain.xyz/:w:/r/personal/personal_com/_layouts/15/Doc.aspx?sourcedoc=%7B6FEF6215-DD54-4BFF-B12C-2D762C0932AC%7D&file=AddinTest.docx&action=default&mobileredirect=true

As per api documentation, I used Office.context.document.url method to read the url that has opened word. But this gives me below output withour any query string

https://mydomain.xyz/personal/personal_com/Documents/AddinTest.docx

Please suggest how can I pass parameter from my source application(angular/asp.net/java/html) that opens the word using hyperlink/uri scheme and capture the value in office js?

**Comment by biswanathc** [comment]
@weshi  Can you help?

**Comment by nrueckmann** [comment]
@AbidRahman-MSFT since you assigned yourself to this ticket, do you see any option how to pass arbitrary data to the add-in?

**Comment by AbidRahman-MSFT** [comment]
Hey @nrueckmann, apologies for the delay here. Thanks for posting the question. 

If i understand correctly, you're trying to fetch metadata from within your add-in when a link is clicked to open the Word document, is that correct?

Are you using the following method to open the document: https://docs.microsoft.com/en-us/office/dev/add-ins/excel/pnp-open-in-excel?

and when opening the document, does the add-in automatically load and the task pane is displayed?

Thanks,
Abid

**Comment by nrueckmann** [comment]
Hi @AbidRahman-MSFT, thanks for you fast reply. I've read the document you've sent. As far as i understand this solution would always include the need to write to the file before opening it. Unfortunately, this is not possible for our current project. We are at the very beginning of our planing, but for now all we need is to hand over some kind of context identifier while opening the document. The add-in will already be installed but needs to know the context in which the file has been opened.

The naive idea was to just add a query parameter to the the document URL and read it by the add-in.

**Comment by AbidRahman-MSFT** [comment]
I see, thanks for the info @nrueckmann. How do you currently guarantee that the add-in will already be installed for the user opening the document? 

If I understand correctly, the user would click a link to the document in your web app, the document opens in that user's desktop environment, presumably Windows, at which point you're looking for some kind of identifier from within the add-in runtime that will be able to tell you some information regarding **which user** clicked on the link in your web app. Is that correct?

There is currently no way to include some kind of context identifier that you're looking for without writing to the document, you could have alternative solutions where you're keeping track of the user clicking on the document in your web app. For eg. maybe a database that logs document clicks and the corresponding user in real-time. Then, when the document opens and the add-in starts, you can check that same database through your add-in to fetch the metadata on the user that opened the document. You can also utilize something like [SSO for Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins) to determine the current user in the document.

Let me know if that helps.

**Comment by nrueckmann** [comment]
Hi @AbidRahman-MSFT, thanks again. I guess we will try a workaround by calling an external service like you suggested. The idea behind using query parameters was that we already know that all clients will only use the web version of office.

**Comment by biswanathc** [comment]
@nrueckmann @AbidRahman-MSFT 

Nice to see the same question still stands for other projects. Well, to share my experience on this when I created this query..
We were doing a modernization project where the idea was to shift completely from desktop office to O365 including content migration from sharepoint to onedrive and VSTO to officeJS.

During that time office js was not working for online word so we migrated content to onedrive and still continued with desktop O365.

Our app was used by insurance brokers who deal with multiple templates(word doc).

We were maintaining a template DB and based on template we were pulling out the OOXML from sql DB and loading the word doc at the time it opens. 
Our requirement was to identify which template we are opening. Our base application was an ASP.net MVC app and from there we wanted to pass context to addin so it loads the correct content for the template it has been asked for. We wanted to physically store only one blank word doc as template and load content dynamically based on template ID.

Since there was no solution to it(passing application context to office addin), we created multiple copies of template(blank word doc) and appended unique ID(templateID as in DB) with file name.

Next step was to create a mapping between user and template ID in table so the user only sees the link for the templates he can open in application based on RBAC. At addin side we could read the filename, took the template ID and passed to api to fetch corresponding OOXML.

This way we solved our problem.

However, if user specific data is required to be loaded in document on load then there should be some straightforward mechanism to pass context from host app to addin.

**Comment by AbidRahman-MSFT** [comment]
Hey @biswanathc, 

Thank you for sharing the workaround your team took to overcome this limitation. The approach you took makes sense to me and is similar to some of the approaches we've heard other ISVs take in this scenario.

If your userbase is integrated into M365, I'm hopeful that the new SSO feature for Office Add-ins would make this scenario much easier to handle in the future. When utilizing SSO, the add-in will have the user information it needs to fetch only the templates/information that is relevant to the user logged in to the application.

Please let us know how else we can help,
Abid
