### ISSUE TITLE
Run time logs are not available on Excel Desktop Windows 

### ISSUE THREAD

**Issue by yurii-zhuk-mstr** [OfficeDev/office-js#883]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

According to the [Documents](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#use-runtime-logging-to-debug-your-add-in) on official web site runtime logging in Excel can be enabled in one of two ways: 
- Modifying register
- NPX

On MacOS it works as expected, but on Windows it's only creating an empty log file. 
## Expected Behavior
Log files on Windows Desktop should contain console.log outputs

## Current Behavior
Most of the times nothing is logged on Windows Desktop.
On initial run after registry is changed, or npx command is entered, log file may contain manifest issues. 
https://imgur.com/a/5HvZbbm

## Steps to Reproduce, or Live Example
refer to the [Documents](https://docs.microsoft.com/en-us/office/dev/add-ins/testing/troubleshoot-manifest#use-runtime-logging-to-debug-your-add-in)

Open excel desktop, on windows
Add an add-in which has console.log in source code
open command-line
enter npx office-addin-dev-settings runtime-log --enable
you should see a message with a path to log file
make some actions in add-in which should produce console.log output
Check created log file, it will be empty

## Context

We are trying to store the logs from our add-in. It works on mac but doesn't seem to log anything on windows desktop.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]:Excel 
* Office version number: 11.1.0000.0123 [64-bit]
* Operating System: Windows 10
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by kacper-kowalski-mstr** [comment]
Hi, any news on this one?

**Comment by Domen122** [comment]
I have the same issue, tried on multiple devices and no logs from console.log are visible

**Comment by 4tti** [comment]
Confirmed, have the same issue with latest insider build on window 10.
Excel version 1912(Build 12325.20012)

**Comment by MandytMSFT** [comment]
I can repro on my desktop. BUG 3834042 has filed for internal track. Will return back to you once we have any update

**Comment by LouMM** [comment]
Thank you, everyone! Anyone who is reproducing the issue, can you let us know the template or type of add-in. Is this an Excel Custom Function or a Web add-in?

**Comment by yurii-zhuk-mstr** [comment]
@LouMM Hello Lou, we are using Web add-in template.

**Comment by Anavaer** [comment]
Hi @LouMM, is there any new information on this that you could share with us?

**Comment by lindalu-MSFT** [comment]
@MandytMSFT Can you confirm if this has been fixed or is it still in the backlog?

**Comment by yunho-microsoft** [comment]
On Windows for manifest logging, we don't show success logging message. If you don't see any error message then your manifest is good to go. We can take a deeper look if anyone can share some example logs from Mac. Thanks.
