### ISSUE TITLE
Microsoft Office Professional Plus 2016 Office.context.requirements.isSetSupported("CustomFunctionsRuntime", "1.1") return true

### ISSUE THREAD

**Issue by zakhan4** [OfficeDev/office-js#884]
https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-requirement-sets states that "Excel custom functions are not supported on Office 2019 or earlier (one-time purchase)." But when I tested for the requirement set in Office 2016 for custom functions it states that it supports.

## Expected Behavior
I expect Office.context.requirements.isSetSupported("CustomFunctionsRuntime", "1.1") on Office 2016 to return 'false'

## Current Behavior
Office.context.requirements.isSetSupported("CustomFunctionsRuntime", "1.1") on Office 2016 returns 'true'

## Steps to Reproduce, or Live Example
1. Import the given below gist in Script Lab and run it
2. Click on 'Check Custom Functions Support' button
3. It will check for "CustomFunctionsRuntime", "1.1" support and will return the response under the console logs tab
* Link to live example: https://gist.github.com/zakhan4/1453cb57871c2c18bf06bcf457c09955

## Context
I'm using this check to notify users that Custom Functions are not supported in the older versions of Office.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft Office Professional Plus 2016 32-bit (Version 1910, Build 12130.20410)
* Operating System: Windows 7 Enterprise Service Pack 1

## Useful logs

![image](https://user-images.githubusercontent.com/41992420/69813681-fd70b000-11f2-11ea-9031-3b8a52fad4ba.png)

**Comment by xiaochunms** [comment]
May  you please test further to confirm custom function does work with your version Microsoft Office Professional Plus 2016 32-bit (Version 1910, Build 12130.20410)? You may can use function feature of scriptlab or install add-in **WA104381720** from the store. Click on the '**Show Taskpane**' button. Execute function **CONST_ASYNC()**

**Comment by zakhan4** [comment]
I can confirm that custom functions are not working in Microsoft Office Professional Plus 2016 32-bit (Version 1910, Build 12130.20410). When I tried to register "Basic custom function" sample from the Script Lab I got this error: 

> An unexpected error has occurred.
Error:
{
    "description": "There was an internal error while processing the request.",
    "message": "There was an internal error while processing the request.",
    "name": "RichApi.Error",
    "code": "GeneralException",
    "traceMessages": [],
    "innerError": null,
    "debugInfo": {
        "code": "GeneralException",
        "message": "There was an internal error while processing the request.",
        "errorLocation": "CustomFunctionManager.register",
        "statement": "v.register(...);",
        "surroundingStatements": [
            "var workbook=context.workbook;",
            "var v=Microsoft.ExcelServices.CustomFunctionManager.newObject();",
            "// >>>>>",
            "v.register(...);",
            "// <<<<<"
        ],
        "fullStatements": [
            "Please enable config.extendedErrorLogging to see full statements."
        ]
    },
    "stack": "GeneralException: There was an internal error while processing the request.\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/beta/hosted/excel-win32-16.01.js:24:283839)\n   at o (https://script-lab.azureedge.net/static/js/2.87213c66.chunk.js:1:3080913)\n   at Anonymous function (https://script-lab.azureedge.net/static/js/2.87213c66.chunk.js:1:3081060)\n   at c (https://script-lab.azureedge.net/static/js/2.87213c66.chunk.js:1:2415424)"
}

When I tried to install add-in **WA104381720** from the store, it is installed but I get this message in the status bar: "This add-in is only supported with an Office 365 subscription license and is not supported with your Office license. Please contact your administrator for more information." After that even though the add-in is working in the task pane, but custom functions are not registered, hence I could not find **CONST_ASYNC()** to execute. Hope this information helps.

**Comment by RuoyingLiang** [comment]
Thanks @zakhan4 ! This is very helpful. you are using an O365 account to update Office to version 1910 right?

**Comment by zakhan4** [comment]
Dear @RuoyingLiang ,

Yes that is correct. I'm signed in with my Office 365 account in Office 2016

**Comment by jamesdlow** [comment]
> Dear @RuoyingLiang ,
> 
> Yes that is correct. I'm signed in with my Office 365 account in Office 2016

@zakhan4, I think just because you're signed in using an Office 365 account, does not mean that your Office 2016 is activated as Office 365. It sound like you may still have your Office 2016 one time purchase as the activation license?

I've found this very frustrating though. I can't see why Microsoft wouldn't support JavaScript custom functions on Office 2016 / 2019 one time purchase licenses.
