### ISSUE TITLE
Chart is sometimes not updated when source is a volatile custom function

### ISSUE THREAD

**Issue by ddanehl** [OfficeDev/office-js#885]
when you have a chart which source is a range with volatile custom functions, it can happen that it is sometimes not updated. you then have to move/resize it that it is updated.

## Expected Behavior
that the chart updates always correctly

## Current Behavior
chart is sometimes not updated and is displayed as empty

## Steps to Reproduce, or Live Example
use ScriptLab volatile sample (ROLL6SIDED) and create chart on it as shown in the attached gif.
then press F9 a few times and the issue will happen.

## Context
show a chart on data that is returned by custom functions

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Excel Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.12325.35900
* Operating System: Win10 64bit
* Browser (if using Office Online): Chrome, Edge, Firefox, Safari

![chart_cf_colatile_bug](https://user-images.githubusercontent.com/7172621/69872291-4c7f1980-12b5-11ea-94c0-23b8afa472d8.gif)

**Comment by RuoyingLiang** [comment]
Thanks for reporting. This is a known issue. We are working on fixing. Sorry for the inconvenient.
