### ISSUE TITLE
Office Online should inform users about missing cookies/permissions/environment

### ISSUE THREAD

**Issue by sureshjoshi** [OfficeDev/office-js#886]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

I have a functional Word Add-in on Word 2016/2019 on Mac and Windows - but when I try to load it in Word Online, I get the `Uncaught (in promise) TypeError: Cannot read property 'run' of undefined` errors on `await Word.run(`. As a result, my add-in would not run in Office Online.

After about 20 minutes of debugging, I saw it was a result of one of the 20ish cookies from Office/Microsoft that my Chrome no-cookie policy was blocking which caused this.

## Expected Behavior

If there are fundamental environmental problems, the user should be notified visibly (somehow) that they might need to check permissions, to check cookies, to try in an incognito browser, etc. 

Something as simple as "Cookies from office.com are being blocked, and as a result, add-ins may not function" would be a good start.

## Current Behavior

On the first attempt at calling `Word.run`, I get `Uncaught (in promise) TypeError: Cannot read property 'run' of undefined` - only visible in the Chrome dev tools console.

Script-Lab threw an exception - only visible in the Chrome dev tools console.

Had I not been a developer, I wouldn't have any clue why these add-ins failed to load/run.

## Steps to Reproduce, or Live Example

My plugin is a private project at the moment, so I cannot produce a live example - but I used Script-Lab in Word Online as a sanity test - but Script-Lab failed to load with an Exception related to localStorage.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Word
* Operating System: MacOS 10.15.1
* Browser (if using Office Online): Chrome (78.0.3904.108)

I allow sites to set cookies, they get wiped when I close Chrome, but Chrome is setup to block 3rd party cookies.

**Comment by lindalu-MSFT** [comment]
@sureshjoshi Is this still causing issues with your add-in?

**Comment by sureshjoshi** [comment]
Hi @lindalu-MSFT 

I'll take a look on my next deployment and test it out again. I've just been avoiding Office Online for a while. Was there any code implemented to this end?

**Comment by lindalu-MSFT** [comment]
@sureshjoshi Hi SJ, yes there have been updates to Word for Mac. Also, you can consider joining [Office Insiders](https://insider.office.com/en-us/) to get the latest builds, if you haven't already! Sorry to hear you're avoiding Office Online, please give us a shot again! Thanks, linda

**Comment by lindalu-MSFT** [comment]
Also, if you run into issues, please provide us with steps to repro, and any logs or scripts so we can traige again. Thanks, linda
