### ISSUE TITLE
Office.context.host, Office.context.platform, Office.context.ui etc is undefined, even if Office.initialize callback was invoked

### ISSUE THREAD

**Issue by ravikmrsingh8** [OfficeDev/office-js#887]
Properties of Office.context e.g Office.context.host, Office.context.platform, Office.context.ui etc are undefined. We verfied that the Office initialize callback was invoked. 
 
## Expected Behavior

If office environment is initialized then Office.context properties should be present in the object.

## Current Behavior
In few of our customer logs we see that the office.initialize call succeeded but the properties of Office.context were undefined.

## Steps to Reproduce, or Live Example
We got the logs from customer usage. we don't have any repro, we are looking for some input that what could be possible cuases for this?

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by ravikmrsingh8** [comment]
@shreedhart Any pointer on this?

**Comment by sureshjoshi** [comment]
I'm not sure how much support you'll get without filling out the Context of the template.

**Comment by lindalu-MSFT** [comment]
@ravikmrsingh8 Closing due to the issue is stale. If you still further assistance, please click the New Issue button and create a new issue. Please fill out all areas including steps to repro, environment, logs, etc. so we can triage. Thanks, linda
