### ISSUE TITLE
Dark mode is not support the add-ons, on Outlook 365 Browser

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#888]
right display ui in light mode:
![image](https://user-images.githubusercontent.com/1878089/69937665-50f63d00-1516-11ea-820f-9fc884b82558.png)
wrong display ui in dark mode:
![image](https://user-images.githubusercontent.com/1878089/69937757-8c910700-1516-11ea-8774-136f5b951b54.png)

**prefect solution:**
provide the Office.context.officeTheme api on the browser(it only provide for windows client right now).Let the developer auto change the add-on theme.

**Comment by exextoc** [comment]
@hello-chenchen Could you provide more info on how we can reproduce this (the second image)? Could you share part of the HTML / CSS?

**Comment by hello-chenchen** [comment]
I think maybe tag this as a feature request will be better.


For the second image:
@exextoc there is no need any other html/css, you just need to open the outlook setting, and switch to dark mode.
![image](https://user-images.githubusercontent.com/1878089/70037944-68a2f380-15f2-11ea-8f6a-81a815b44ec4.png)
And "My Templates" is Microsoft provide the templates example for office 365 add-on users maybe.
![image](https://user-images.githubusercontent.com/1878089/70038080-a6a01780-15f2-11ea-8c64-a65a75fc2cd9.png)


And i will use "background-color: #fff" as a work around solution which is like the oneNote add-on does:
![image](https://user-images.githubusercontent.com/1878089/70038820-df8cbc00-15f3-11ea-8a8f-01d67efba5f0.png)


But i still think provide the Office.context.officeTheme api on the browser is a better solution.

**Comment by hello-chenchen** [comment]
If my body css no background-color set, the default color is transparent, and it will show like below:
![image](https://user-images.githubusercontent.com/1878089/70039461-fa136500-15f4-11ea-8e48-f0a2b062a370.png)

**Comment by exextoc** [comment]
Thanks, we are able to reproduce this issue. We will investigate if this is the expected behavior in this scenario and keep you informed. In the meantime, you could create a feature request to provide the Office.context.officeTheme API for OWA.

**Comment by exextoc** [comment]
The behavior shown here is expected, please submit a feature request to provide the Office.context.officeTheme API for OWA.

**Comment by chenxizhang** [comment]
After more than 1 year, Do we have the plan to provide this feature on OWA?  Do we have the workaround to support this requirement?

**Comment by exextoc** [comment]
Hi @chenxizhang , thanks for your query. We already have this feature in our backlog, but it is not prioritized yet. Unfortunately, we do not have any timelines to share at the moment.

**Comment by Sayan751** [comment]
Is there at least any workaround for this?

**Comment by toannguyenspce** [comment]
It'd been another year, Just want to check if it'd been implemented ?

**Comment by terajoellang** [comment]
It's been ANOTHER year. Has it been implemented now? If yes, where can I find it? It's been 4 years in total now....

**Comment by hielkehoeve** [comment]
An another 2+ years....
