### ISSUE TITLE
addHandlerAsync doesn't work with AttachmentsChanged and RecipientsChanged

### ISSUE THREAD

**Issue by markb-trustifi** [OfficeDev/office-js#889]
## Current Behaviour
The 1.8 features don't work in any client - Win/Mac/OWA.
Executing `Office.context.requirements.isSetSupported('MailBox', '1.8')` returns true.

This event works OK:
`Office.context.mailbox.addHandlerAsync(Office.EventType.ItemChanged,...)`

These events don't work:
`Office.context.mailbox.addHandlerAsync(Office.EventType.AttachmentsChanged,...)
Office.context.mailbox.addHandlerAsync(Office.EventType.RecipientsChanged,...)`

I receive a javascript error:
`Function addHandlerAsync has invalid parameters.`

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: PC, Mac, Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 365 subscription (Outlook Mac 16.31, Outlook Win 16.0.12130.202 32bit)
* Operating System: Win 10.0.18362, Mac 10.14.6
* Browser (if using Office Online): Chrome 78.0.3904.108

**Comment by exextoc** [comment]
Since AttachmentsChanged/RecipientsChanged events occur in the item scoped, the call is Office.context.mailbox.item.addHandlerAsync.  See https://docs.microsoft.com/en-us/office/dev/add-ins/reference/objectmodel/requirement-set-1.8/office.context.mailbox.item#addhandlerasynceventtype-handler-options-callback

**Comment by markb-trustifi** [comment]
@exextoc Thank you for update. I checked `RecipientsChanged` and it works well on all types of clients. There is a problem with `AttachmentsChanged` - it constantly sends add/remove notifications in infinite loop without stopping.

**Comment by exextoc** [comment]
Glad that it worked.  I cannot repro the AttachmentsChanged issue in PC desktop Outlook.  Could you confirm which clients you are seeing the infinite loop?  Could you also post the snippet you are using?

**Comment by markb-trustifi** [comment]
The infinite events start when I add attachment (manually) in compose window. It happens in all clients.
```js
Office.context.mailbox.item.addHandlerAsync(Office.EventType.AttachmentsChanged, args => console.log('AttachmentsChanged', args))
```
The events arrive in pairs - add,remove,add,remove,...
When I remove the attachment (manually) I receive 3-5 identical "remove" events.

**Comment by exextoc** [comment]
I cannot repro this in OWA or Desktop. Can you give us more details on what type of attachments you're adding and also how you are attaching them.

**Comment by markb-trustifi** [comment]
I cannot reproduce it too now. 
It can be related with `Office.context.mailbox.item.removeHandlerAsync`. 
Maybe sometimes the controller destructor isn't called by angular.

**Comment by exextoc** [comment]
Why do you think it is related to `removeHandlerAsync`? Are you calling `Office.context.mailbox.item.removeHandlerAsync` in your code?

**Comment by markb-trustifi** [comment]
Yes, I do. But before it reproduced, I opened and closed add-in (compose view) multiple times because some Angular error. Now, when I open it first time it works well.

**Comment by exextoc** [comment]
Glad it's working now. Please let us know if there's anything else we can help you with.

**Comment by markb-trustifi** [comment]
I succeeded to reproduce the issue on the Windows Outlook desktop client only.
I update all 3 fields by the script:
```js
Office.context.mailbox.item.to.setAsync(recipients.filter(itm => itm.source === 'to'), res_to => {
	Office.context.mailbox.item.cc.setAsync(recipients.filter(itm => itm.source === 'cc'), res_cc => {
		Office.context.mailbox.item.bcc.setAsync(recipients.filter(itm => itm.source === 'bcc'), res_bcc => {
			callback({res_to,res_cc,res_bcc});
		});
	});
});
```

When I'm sending recipients array as [1 TO recipient, 1 CC recipient, no BCC], I receive 3 events with changedRecipientFields: 
`{bcc:false, cc:true, to:true}`

When I'm sending recipients array as [1 TO recipient, no CC, no BCC], I receive 3 events with changedRecipientFields: 
`{bcc:false, cc:false, to:true}`

**Comment by markb-trustifi** [comment]
@exextoc please reopen the issue. I reproduced it in Outlook desktop client.

**Comment by exextoc** [comment]
There is a known issue with setting recipients via the API and the event returned is not entirely accurate. (as you observed). However, it should be too noisy when the bug happens. i.e. it may return true when nothing has changed, but it should never return "false" when something HAS changed. 

The work around is that you could compare recipients before/after between events to find out what has actually changed. 

There is not a timetable to when or if this issue will be fixed at this time.
