### ISSUE TITLE
Translated custom functions cannot be added through Excel API

### ISSUE THREAD

**Issue by caolgood** [OfficeDev/office-js#891]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

My add-in task pane is using this code to insert a function into the selected cell:
`range.formulas = [['=SUM(1,2) & CONTOSO.ADD(1,2)']];`
 By default this has the expected result, but after changing Excel's display language, there is a `#NAME?` error.

## Expected Behavior
With a german display language, the formula displayed for the cell should be:
`=SUMME(1,2) & CONTOSO.DE.ADD(1,2)`

## Current Behavior
The actual result is:
`=SUMME(1,2) & CONTOSO.ADD(1,2)`
The built in function was correctly inserted, but the custom function is still English. I should be able to insert custom functions by referencing their Id and not worry about the display name, same as how the built in functions are working. 

## Steps to Reproduce
https://github.com/caolgood/excel-translated-custom-functions
This repo was generated by 'yo office' with some changes to add a translated functions-de.json.

1. Clone the repo and `npm install`
2. Install the german language pack for office 365, or change the 'de-de' locale in the manifest.xml to a language already installed
3. Change Excel's display language and close excel
4. run `npm run build:dev` and `npm run start` from the repo's root folder
5. Open the add-in task pane and click the Run button

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1908
* Operating System: Windows 10
* Browser (if using Office Online): n/a

**Comment by xiaochunms** [comment]
The [link ](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-localize) explains how to localize custom functions. In the case of localized file Yoeman generated, such as functions-de.json, you may notice "ADD" in English is translated to "DE.ADD", which is not a real translation, instead it is more like a sample to figure out the part needs to be localized. You may can change it to a valid function name in German that should work.

**Comment by caolgood** [comment]
'DE.ADD' is a valid name according to the guideline [here](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-naming), and I can reproduce this with any other normally translated name. In fact this also occurs in an English locale if you have a function where the name and id are different.
When setting a value on `range.formulas` I'm expecting to be able to use the ids of my custom functions because that's how the built in functions work

**Comment by xiaochunms** [comment]
You are right, "DE.ADD" is a valid name. Sorry for my mistake in my last response. I noticed you mentioned that "In fact this also occurs in an English locale if you have a function where the name and id are different." Does custom function work in an English locale if the function name and id are same? Actually custom function supports the case that function name and id are different. #NAME? error indicates the failure of locating the function, which is defined in functions.ts in your case.

**Comment by caolgood** [comment]
If the English locale's functions use the same name and Id I don't see any issues. 
Should also note that typing out my custom functions in the worksheet always works fine, its just programmatically setting them that seems inconsistent

**Comment by RuoyingLiang** [comment]
@xiaochunms could you help to check if this issue still existing? if not, please close this item. Otherwise please open a bug. Thanks!
