### ISSUE TITLE
Created Office Word App with Yarn / Not able to sideloading office web Word

### ISSUE THREAD

**Issue by jrpally** [OfficeDev/office-js#892]
I can run my app on Office Desktop, but when I upload my manifest in Office Web Word I cannot see my app reflected in the word web app ribbon.

Any idea why?  I am using this initializer.

Office.initialize = () => {
	isOfficeInitialized = true;
	render(App);
};

**Comment by sureshjoshi** [comment]
Hey @jrpally, when you upload your manifest, whether or not it shows up in the ribbon, I believe is entirely controlled by the Manifest and your organization's support for allowing addins.

Out of curiosity, have you tried in Incognito mode? I had a slightly different issue happen, after the plugin had shown in the ribbon - I couldn't actually launch it. I bug reported it here (#886)... But... You never know.

Are you able to load other add-ins (e.g. Script Lab)?

**Comment by jrpally** [comment]
I did sideload using word and shared folder in word, and it works, it adds in the ribbon, but for Office word online I cant see in the ribbon, I load the manifest and nothing happens. Any idea?

**Comment by sureshjoshi** [comment]
So, were you able to try Office Online in incognito mode? 

Also, I was referring to adding other add-ins or anything in Office Online, not using desktop Word. Are you able to load Script Lab in Office Online?

Also, does your manifest validate correctly using the office-validator?

**Comment by jrpally** [comment]
I can add other addins in office online, I can run my addin/manifest in Word Desktop, but when I load my manifest using office online do not works.

**Comment by AbidRahman-MSFT** [comment]
Hey @jrpally, as this issue has been stale for quite some time, I am going to go ahead and close the issue. If you are still experiencing this issue, please feel free to re-open or add a new issue. Thanks! :)
