### ISSUE TITLE
Jira add-in stopped loading on insiders fast (works fine in monthly)

### ISSUE THREAD

**Issue by tcrusson** [OfficeDev/office-js#893]
We're the vendor for https://appsource.microsoft.com/en-us/product/office/WA200000556
The add-in doesn't load on the insiders fast distribution of excel
It loads fine in the monthly release of Excel

We tried uninstalling it to install it again, but no luck:
- we can't find it in the Office add-in store in Excel
- If we try to install it from appSource and select "open in Excel", it opens Excel but fails to load the add-in. The Jira command doesn't get added to the ribbon.

## Expected Behavior
User can install and use the add-in

## Current Behavior
- if the user has the add-in installed, the add-in doesn't load anymore
- if the user doesn't have the add-in installed, there's no way to install it.

<img width="1440" alt="Screen Shot 2019-12-09 at 5 24 07 PM" src="https://user-images.githubusercontent.com/7296890/70454679-245c9b00-1aab-11ea-9cc0-621fddb157a5.png">
<img width="1440" alt="Screen Shot 2019-12-09 at 5 20 49 PM" src="https://user-images.githubusercontent.com/7296890/70454697-2aeb1280-1aab-11ea-9c20-6d1a8e9dbc41.png">
<img width="1440" alt="Screen Shot 2019-12-09 at 5 19 01 PM" src="https://user-images.githubusercontent.com/7296890/70454711-2fafc680-1aab-11ea-895d-1a1f608fb829.png">

**Comment by keyur32** [comment]
Hey, there is a bug on insiders: internal bug 3812481, will be fixed on next update to Insiders/very soon.
