### ISSUE TITLE
Indent and alignment not working in office-js-in-word WordApi 1.1 & WordApi 1.2

### ISSUE THREAD

**Issue by ankushsolao** [OfficeDev/office-js#894]
I am trying to add indent & alignment in paragraphs of the document. It is working for me when I have used office.js "WordApi 1.3" but I need to implement in the office.js "WordApi 1.1 or WordApi 1.2".

Below the code i have tryied using WordApi 1.2:-

context.document.body.paragraphs.getFirst().leftIndent = 75; 
context.document.body.paragraphs.getFirst().alignment = "Centered";
 
below image code not working in WordApi1.1(Build number:- Word 2016 MSO(16.0.4738.1000)32-bit)
![image](https://user-images.githubusercontent.com/54404769/70500710-33425c80-1b42-11ea-9afa-85b5a5eaa25b.png)

Getting below error:- 
{"description":"InvalidArgument","name":"RichApi.Error","code":"InvalidArgument","traceMessages":[],"innerError":null,"debugInfo":{"code":"InvalidArgument","message":"InvalidArgument","errorLocation":""},"stack":"InvalidArgument: InvalidArgument\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:24:288131)\n   at T (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:24:221040)\n   at x (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:24:221126)\n   at t (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:24:220934)\n   at l (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:24:219441)"}

Any example to achieve this?

Many thanks..!!!

**Comment by ankushsolao** [comment]
I was trying to add indent in paragraphs of the document. 
I have word 2016 MSO(16.0.4738.1000)32-bit).
I need to access this on WordApi 1.1 0r 1.2 not in WordApi 1.3(Its working fine for me)
below code i tried:-
context.document.body.paragraphs.getFirst().leftIndent = 75;

Please find the error detail:-
{"description":"InvalidArgument","name":"RichApi.Error","code":"InvalidArgument","traceMessages":[],"innerError":null,"debugInfo":{"code":"InvalidArgument","message":"InvalidArgument","errorLocation":""},"stack":"InvalidArgument: InvalidArgument\n   at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:24:288131)\n   at T (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:24:221040)\n   at x (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:24:221126)\n   at t (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:24:220934)\n   at l (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:24:219441)"}

**Comment by AbidRahman-MSFT** [comment]
Hey @ankushsolao - this issue was resolved in the following thread: https://github.com/OfficeDev/office-js/issues/898

I'm going to go ahead and close this as a duplicate. Please feel free to re-open if you have more info or questions. Thanks!
