### ISSUE TITLE
Tutorial: Share data and events between Excel custom functions and the task pane does not work

### ISSUE THREAD

**Issue by zakhan4** [OfficeDev/office-js#895]
I followed the tutorial here: https://docs.microsoft.com/en-us/office/dev/add-ins/tutorials/share-data-and-events-between-custom-functions-and-the-task-pane-tutorial and expected for it to work.

## Current Behavior

After add-in is sideloaded, I get this error: 
![image](https://user-images.githubusercontent.com/41992420/70552478-b632d980-1b79-11ea-96ab-7dd1684e49c3.png)

## Steps to Reproduce, or Live Example

* Link to live example: https://github.com/zakhan4/CFSharedRuntime

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: Microsoft Office 365 ProPlus, Version 1912 (Build 12325.20012) Office Insider
* Operating System: Windows 10 Enterprise
* Yo office-generator version: 1.4.0

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by weshi** [comment]
Could you manually add the function.js reference in your taskpane.html? This is because now you use taskpane.html to share state with your custom functions. The tutorial or the yo office generator didn't do that for you. Please hava a try and let us know if this can solve your issue.

**Comment by zakhan4** [comment]
Hi @weshi ,

So I tried your suggestion, but I still have the same issue. I also updated my github repo with the changes. Can you please try to run it at your end and check. Thanks!

**Comment by weshi** [comment]
I noticed that you have put the below node under the wrong place:

    <Runtimes>      
        <Runtime resid="Taskpane.Url" lifetime="long" />    
    </Runtimes>

It should be put under VersionOverrides/Hosts/Host, just before the AllFormFactors. 




![manifest](https://user-images.githubusercontent.com/11494417/71396697-20f21380-2656-11ea-882b-a8da8ef1c63d.png)

**Comment by zakhan4** [comment]
Dear @weshi,

Thanks for your response. This made it work for me!
