### ISSUE TITLE
_host_info query parameters and pipe

### ISSUE THREAD

**Issue by bx-anil** [OfficeDev/office-js#896]
## Expected Behavior
Opening an url via displayDialogAsync even when redirecting to servers that do not honor "|" in query in parameters

## Current Behavior
Opening an URL via displayDialogAsync fails when opening AWS API Gateway URLs or similar such servers where "|" is not honored/configured to be used. Though it may be for the server to accept "|" the best practice may be to encode the URLs

* Additional details:
  1. Set up an AWS API Gateway + Lambda  
  2. Use Office API Office.context.ui.displayDialogAsync to open this URL.
  3. The Office API adds a query parameter "_host_info" with values similar to - outlook|web|16.01|en-us|6ed38bbe-e610-cf6a-b413-9491cdcef28a|isDialog|
  4. The page fails to open with a 400 error.

## Context

showDialog (line 8975) from https://appsforoffice.microsoft.com/lib/1.1/hosted/outlook-web-16.01.debug.js seems to include "|" in the constructing the query parameters. Can we please encode the query parameter component before calling window.open

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16
* Operating System: Windows 10
* Browser (if using Office Online): Chrome/Edge

**Comment by exextoc** [comment]
This is as per current design. if you want to request it, We track Outlook add-in feature requests on our user-voice page.

**Comment by massonj** [comment]
Thanks for reaching out.

Per @exextoc, this is a feature request which is best logged on our user voice page here https://officespdev.uservoice.com/
