### ISSUE TITLE
Please send us feedback on Outlook Auto Run and enabling Signature Scenarios.

### ISSUE THREAD

**Issue by JuaneloJuanelo** [OfficeDev/office-js#897]
Please reply with feedback on our Signature and Auto-run designs for Outlook.

## What
During the December 2019 community call (find it [here](https://developer.microsoft.com/en-us/office/blogs/)) we shared the design draft for Auto-run Add-ins in Outlook as well as enabling signature scenarios. 
This issue is to track your feedback, thanks in advance for your help making our platform better!

## Items we are interested
Please comment on this issue any feedback associated with the design. We are particularly interested in the following: 

## Steps to Reproduce, or Live Example

* Autorun Capabilities
  1. What events you would like to see enabled? Please add scenario.
  2.  What do you think about the required manifest annotations?

* Enabling Signature scenarios
  1. Does the proposed workflow make sense?
  2. API Feedback
  3.  is Offline relevant to you?

## THANK YOU

**Comment by sarea** [comment]
For the autorun: having an event for **read** mode would be very helpful!

**Comment by JuaneloJuanelo** [comment]
@sarea  can you share more details on how you will use the event on read items?

**Comment by sarea** [comment]
@JuaneloJuanelo we were waiting for this feature for a long long time as it helps us to change/replace the message body for the messages that have been send through our add-in instead of reading it in the task-pane, having this feature with the ability to replace the message body will be a very big step for better user experience!

**Comment by JuaneloJuanelo** [comment]
i will close this issue it was used to track more feedback and I think we got some. thanks everyone!
