### ISSUE TITLE
InvalidArgument error when apply Indent in Word 2016 MSO(16.0.4738.1000)32-bit)

### ISSUE THREAD

**Issue by ankushsolao** [OfficeDev/office-js#898]
I was trying to achieve the indent functionality in word add-in but getting an exception.
Below the details of issue:-

## Expected Behavior
The indent should be applied to the selected text/paragraph.

## Current Behavior
I am trying to use office.js API on Word 2016 MSO(16.0.4738.1000)32-bit) and facing an issue when I apply indent to selected text.
below the code:-
 Word.run(function (context) {
context.document.body.paragraphs.items[0].leftIndent = 75;
 return context.sync() })

## Steps to Reproduce, or Live Example

* Additional details:

I have checked the office word API version is supported or not. Below find result:-

1. Office.context.requirements.isSetSupported('WordApi', '1.1') = true.
2. Office.context.requirements.isSetSupported('WordApi', '1.2') = true.
3. Office.context.requirements.isSetSupported('WordApi', '1.3') = false.  

## Context
 Facing this issue on a test environment. 

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: word add-in
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: 2016 MSO(16.0.4738.1000)32-bit)
* Operating System: Windows 10
* Browser (if using Office Online):  Word Add-Ins/IE 11.3321.14393.0 (Update Version 11.0.160)

## Useful logs
{
"description": "InvalidArgument",
"message": "InvalidArgument",
"name": "RichApi.Error",
"code": "InvalidArgument",
"traceMessages": [],
"innerError": null,
"debugInfo": {
"code": "InvalidArgument",
"message": "InvalidArgument",
"errorLocation": ""
},
"stack": "InvalidArgument: InvalidArgument\n at Anonymous function (https://appsforoffice.microsoft.com/lib/1/hosted/word-win32-16.01.js:24:288131)\n at o (https://script-lab-runner.azureedge.net/static/js/1.30a5fcfe.chunk.js:1:2779072)\n at Anonymous function (https://script-lab-runner.azureedge.net/static/js/1.30a5fcfe.chunk.js:1:2779219)\n at u (https://script-lab-runner.azureedge.net/static/js/1.30a5fcfe.chunk.js:1:314565)"
}

**Please help me to resolve this issue.**

**Comment by gbalatckii** [comment]
No response for more than 1 year ....

Same by me Word 2016 (16.0.5110.1000) MSO (16.0.5134.1000) 32-Bit, Windows 10
![Bildschirmfoto 2021-03-11 um 12 45 15](https://user-images.githubusercontent.com/57895385/110782682-c1d2eb80-8267-11eb-9a99-8bf9659f93fc.png)

This is what I get if nothing is selected
![Bildschirmfoto 2021-03-11 um 12 50 24](https://user-images.githubusercontent.com/57895385/110783211-6e14d200-8268-11eb-8636-24f818ba3ead.png)

This is what I get if some text is selected
![Bildschirmfoto 2021-03-11 um 12 50 42](https://user-images.githubusercontent.com/57895385/110783224-72d98600-8268-11eb-8822-dd3154182ad7.png)

it works fine, if I take _context.document.contentControls_ and not _getSelection()_

**Comment by AbidRahman-MSFT** [comment]
Hey @ankushsolao, 

I can't repro the issue you mentioned, please try the following code to set the left indent of a paragraph in the document:
Note that this is only using APIs that are available in Word API 1.1 and 1.2:

```
async function run() {
  await Word.run(async (context) => {

    // Create a proxy object for the paragraphs collection.
    var paragraphs = context.document.body.paragraphs;

    // Queue a command to load the leftIndent property.
    // It is best practice to always specify the property set. Otherwise, all properties are
    // returned in on the object.
    context.load(paragraphs, 'leftIndent');
    await context.sync();

    paragraphs.items[0].leftIndent = 10;
    await context.sync();
  })
    .catch(function (error) {
      console.log('Error: ' + JSON.stringify(error));
      if (error instanceof OfficeExtension.Error) {
        console.log('Debug info: ' + JSON.stringify(error.debugInfo));
      }
    });
}
```

You need to make sure to load the properties before accessing them. The property in this case is the items property of a Paragraph Collection. Once you load the items, you can access them and change their properties. I don't see the same issue that you mention around InvalidArgument. Let me know if I missed anything.

Hey @GeorgeBalat, I also cannot repro the issue that you are seeing here, which .js library are you using for Office JS? Try using this: https://appsforoffice.microsoft.com/lib/1/hosted/office.js and let me know if the problem still exists.

**Comment by gbalatckii** [comment]
Hi @AbidRahman-MSFT,

I used this example as a template for my project, but just with react:
https://docs.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart?view=word-js-preview&tabs=yeomangenerator

So I am using React 16 with this office versions:
    "office-addin-cli": "^1.0.10",
    "office-addin-debugging": "^3.0.31",
    "office-addin-dev-certs": "^1.5.2",
    "office-addin-lint": "^1.0.23",
    "office-addin-manifest": "1.5.0",
    "office-addin-prettier-config": "^1.0.12"

Can you please test, if you can repro my issue with this environment?
Or do you need more information?

**Comment by AbidRahman-MSFT** [comment]
Hey @GeorgeBalat - I am still unable to repro the issue you are mentioning. As this is unrelated from the original problem this issue was created for, can you please post a new issue with details around how to reproduce the problem you are facing? Thanks!
