### ISSUE TITLE
getAttachmentsAsync method returns an id that has no data

### ISSUE THREAD

**Issue by clavx** [OfficeDev/office-js#900]
We obtain the id by using the `getAttachmentsAsync` method, and execute the `getAttachmentContentAsync` method, then its return value content is empty.

## Expected Behavior

After conversion to text mode, the length of the array of attachments in the `getAttachmentsAsync` method is zero.

## Current Behavior

The `getAttachmentsAsync` method shows that the attachment array length is 1 and retrieves the id.
If you use that id to call the `getAttachmentContentAsync` method, it returns an empty content.

## Steps to Reproduce, or Live Example

1. Open Outlook on the web (OWA).
2. Composes a "New message" in HTML mode.
3. Click "Insert pictures inline" button, insert an image into the body.
4. Click "Switch to plain text" to change the mode. At that time, you will be warned that the attachment will be removed, then select "OK".
5. Call the `getAttachmentsAsync` method.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: N/A
* Operating System: Windows 10 Pro, version 1903
* Browser (if using Office Online): Microsoft Edge 44.18362.449.0

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding Attachment API. It has been put on our backlog. We unfortunately have no timelines to share at this point

**Comment by exextoc** [comment]
Internal tracking ids: Office:3858085 and OutlookWeb:62585

**Comment by clavx** [comment]
I checked the current status and found that it works fine.
I think this issue has been resolved.

Any updates?

**Comment by exextoc** [comment]
This issue has been fixed on OWA. Closing the bug
