### ISSUE TITLE
Significant performance decrease of Custom Functions when using Shared App Model

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js#901]
The performance of custom functions is significantly decreased while using Shared App Model on insiders build.

## Expected Behavior

Custom Functions are fast as in separated Runtime or the performance differs just slightly and the calculation does not affect UI in any way.

## Current Behavior

The performance decrease issue is especially visible with larger amount of formulas (thousands).
With even greater number of formulas (40.000) the calculation fails (showing #BUSY! message) and even after couple of minutes (without any result) the task pane UI was "killed". See picture below.
![image](https://user-images.githubusercontent.com/19533927/70908459-7c475480-200b-11ea-9f5b-956a08f93f5d.png)

## Steps to Reproduce, or Live Example

1. Create sheet with thousands of custom functions (ideally volatile that retrieve some data from database and are using batching from PnP sample)
2. Calculate and compare the times on Shared App Model and dedicated Runtime
3. Create similar sheet but now with e.g. 40.000 custom functions and compare the results.

## Context

This is blocker for using Shared App Model for us. And as it introduces many required things - like cookie based authentication, possibility of direct communication, ... - it is basically must have for any advanced addin development.
## Your Environment

Win10 [Version 10.0.17134.1130]
Excel version 1912 (12325.20012)

**Comment by keyur32** [comment]
Just to touch on this, team is following up on a repro offline.

**Comment by 4tti** [comment]
Looks the behavior got significantly improved with new versions of Excel. Retested again on Version 2003 (build 12607.20000) and now the formulas are successfully calculated.

There is still small performance difference, having  around 47k formulas the calculation times are:
26s for Shared App Model
22s for separated Custom Functions Runtime.

Just note it was rough benchmark and we are going to do more precise testing later on.
However, we still see the 'Addin error' toast message - it would be nice to have it somehow under control, especially when the addin works only the calculation in the "background" is running for long time - but that will be discussed offline.
Closing for now (but maybe will get back with more feedback after thorough checking)
