### ISSUE TITLE
After updating Office, Excel can't start add-in any more

### ISSUE THREAD

**Issue by SWDevB** [OfficeDev/office-js#902]
After updating from Microsoft Office 365 ProPlus 1906 to 1911 (12228.20364) I cannot run my Excel-Add-In any more.

## Expected Behavior
Current version of Office still runs the add-in

## Current Behavior
After starting the desktop debugging, Excel starts, loads ribbon integration and opens task pane showing an empty window with just the following error

> ADD-IN ERROR
> This add-in could not be started. Close this dialog to ignore the problem or click "Restart" to try again.

Clicking restart doesn't change anything.

When clicking the task pane button which opens the add-ins task pane content, an additional task pane is opened showing the expected content. If the click on the ribbon button is repeated, the site is refreshed showing still the expected content but after some seconds the error mentioned above is also shown in this window.

The custom functions are available in auto completion, but stay on #BUSY when used. 

All this also happens when if a completely new add-in created by "yo office" is used.

Loading the add-in hosted on a public server by with proper certificate by network share sideloading works, loading the locally or within the network hosted add-in this way doesn't. So the issue might be about security/certificate issues, which somehow only affects specific versions of Office

- A collegue also on monthly channel using Microsoft Office 365 ProPlus 1911 (Build 12228.20332) also has the problem
- Another collegue on insider channel using Microsoft Office 365 ProPlus 1912 (Build 12325.20012) doesn't 
- In Office online (tested Chrome, Edge and IE) the problem doesn't occur. The add-in works there

## Steps to Reproduce, or Live Example
Create new Add-In and run it in default configuration locally

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Desktop Microsoft Office 365 ProPlus (32-bit)
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 1911 (Build 12228.20364)
* Operating System:  Windows 10 Version 10.0.18363 Build 18363
* Browser (if using Office Online): Chrome & Edge (both working)

## Useful logs
**Screenshot**

![error](https://user-images.githubusercontent.com/44261862/70908914-a51c1980-200c-11ea-8041-3ab70dcffb40.PNG)

**Windows' event log shows the following entry**

```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" /> 
    <EventID Qualifiers="0">1000</EventID> 
    <Level>2</Level> 
    <Task>100</Task> 
    <Keywords>0x80000000000000</Keywords> 
    <TimeCreated SystemTime="2019-12-16T11:04:04.870003700Z" /> 
    <EventRecordID>76454</EventRecordID> 
    <Channel>Application</Channel> 
    <Computer>PC.DOMAIN.local</Computer> 
    <Security /> 
  </System>
  <EventData>
    <Data>msoadfsb.exe</Data> 
    <Data>16.0.12228.20102</Data> 
    <Data>5dc1a162</Data> 
    <Data>KERNELBASE.dll</Data> 
    <Data>10.0.18362.476</Data> 
    <Data>540698cd</Data> 
    <Data>c06d007e</Data> 
    <Data>001135d2</Data> 
    <Data>493c</Data> 
    <Data>01d5b4006ebbe1e9</Data> 
    <Data>C:\Program Files (x86)\Microsoft Office\root\Office16\msoadfsb.exe</Data> 
    <Data>C:\WINDOWS\System32\KERNELBASE.dll</Data> 
    <Data>c111ce07-14f9-446d-b465-9f83ddab1ee4</Data> 
    <Data /> 
    <Data /> 
  </EventData>
</Event>
```

**Comment by RuoyingLiang** [comment]
Thanks for reporting. We are looking at it.

**Comment by SWDevB** [comment]
Thanks, as a workaround I installed fast insider, got version 2001 and there the issue doesn't occur. So it seems it was fixed in 1912, but the current monthly channel version contains the bug

**Comment by kotanda** [comment]
> Thanks for reporting. We are looking at it.
Hi, 
Do you have any news?
maybe some predictions?

**Comment by glr0221** [comment]
this is also happening in outlook? 
please check this out : https://github.com/OfficeDev/office-js/issues/928

**Comment by RuoyingLiang** [comment]
#928 should not be the same issue as this one is because the VS launched add-in had issue at some build.

**Comment by 4tti** [comment]
Hello @RuoyingLiang not sure why was this closed. Is it fixed? 
After recent windows update (forced by IT) on some of our Dev environments we experience exactly same issue. The excel started to use Edge webview and the addin is not possible to load. We are currently investigating.
Windows version: 1909, OS build 18363.836
Excel version: 16.0.12730.20342

I'll update here if Yeoman generated addin works once tested. But so far I think there is still bug in Edge based webview (unless it was fixed in the meantime).

@SWDevB: is it reproducible on your side?

Update: even **Yeoman generated addin does not work.**

To make it clear what is the issue - we cannot start our addin anymore, we see 'Addin Error' page:
![image](https://user-images.githubusercontent.com/19533927/82682369-75bea800-9c4f-11ea-9ae8-89f01f376c58.png).
And after restart nothing happens.
Also please note that we enabled loopback exemption on that machine so that is not an issue.

Edit: ScriptLab does not work as well.

**Comment by 4tti** [comment]
@keyur32 This is becoming very critical as it appeared on another environment. There we tried the insider build workaround but it did not help.
It is not possible to use any addin, even ScriptLab from store (i.e. it cannot be related to the Loopback Exemption if I am not mistaken) - all of the addins show same error.

**Comment by 4tti** [comment]
So we had this issue with 3 environments.
First environment was reinstalled using same windows version -> works now. 
Second was updated to newest windows build and it works as well.
So I guess it is fine now.
