### ISSUE TITLE
It is not possible to copy/paste cells with custom function between Excel instances

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js#903]
## Expected Behavior

Copy pasting of cells with Custom Functions work normally between excel instances.
## Current Behavior

IT is not possible to paste cells with Custom functions, it shows this message dialog:
![image](https://user-images.githubusercontent.com/19533927/70911187-9edc6c00-2011-11ea-9efb-cf63843593d3.png)

## Steps to Reproduce, or Live Example

Open workbook with Custom functions. Start second instance of excel and try to copy cells from the workbook from first instance and paste them into the second instance.

## Context

This is quite natural and expected behavior. It should work.

## Your Environment

Win10 [Version 10.0.17134.1130]
Excel version 1912 (12325.20012)

**Comment by massonj** [comment]
Hi @4tti 

Currently the feature(Copy/Paste of custom functions between Excel instances) which you requested is not a part of the product. We track Office Add-in feature requests on our UserVoice page - https://officespdev.uservoice.com. Please add your request there. Feature requests on user-voice are considered when we go through our planning process. 

Thanks, Office Platform team

**Comment by 4tti** [comment]
@massonj Are you serious? Copy/Paste is in excel just normal feature and it should be part of Custom Functions. I understand it is not yet implemented and might not have such high priority (though it is surprising) but definitely should not be simply closed as 'by design' and raise user voice request. **I doubt this is by design.** 
In worst case I would expect at least some 'internal tracking item' not simply just closing like this....

@keyur32  FYI

**Comment by 4tti** [comment]
Oh forget it. My mistake. It does not work even with UDFs. Sorry ;)
