### ISSUE TITLE
Outlook 16.32 crashed in Mac OS 10.15.2

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-js#904]
I got my new Macbook and synchronized my outlook account yesterday. Because some emails were not synchronized well, I deleted the account and tried to add it again. Then when I tried to open the outlook again, it does not work and crashes before the application is opened. 

<img width="472" alt="image" src="https://user-images.githubusercontent.com/43507527/70911417-37481000-2055-11ea-9f9c-52e235f570e5.png">

I've tried to reinstall the Outlook(MS Office suite) again, but it still does not work. On the other hand, other MS applications such as Excel, Word, they're working well.

My environment and MS version are as below.
**OS Version: Mac OS 10.15.2
Outlook Version: 16.32.0.19120802**

The log is attached.
[outlook_log.txt](https://github.com/OfficeDev/office-js/files/3968285/outlook_log.txt)

**Comment by massonj** [comment]
Thanks for reporting the issue. Unfortunately, this repo is only for tracking issues related to Office Add-ins, not general Office issues. The best way to report crashes like the one above to Microsoft is using the pictured dialog, along with any information on what you were doing at the time.

Thanks
