### ISSUE TITLE
yo office generated manifest not working for Office Online

### ISSUE THREAD

**Issue by jrpally** [OfficeDev/office-js#905]
I created an officeapp using yo office, for word, but I can;t open the app or at least nothing happens when I load this in office word online.
## Expected Behavior

Expected Behavior: Brand new apps created with yo office / word / react should be opened in office online
## Current Behavior

The current behavior: I created using yo office word app, but cant be opened in Word, but it can be opened in excel and powerpoint!!! 
## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______Online
* Host [Excel, Word, PowerPoint, etc.]: ______Word
* Office version number: ______OFfice 2019
* Operating System: ______Windows 10
* Browser (if using Office Online): ______Online with chrome.

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by Reezaali** [comment]
Hi @jrpally sorry to hear about this issue. Can you include your repro steps please? Thanks.
