### ISSUE TITLE
Windows Outlook Client add-on Error log in a higher probability: Office.js has not fully loaded. Your app must call "Office.onReady()" as part of it's loading sequence (or set the "Office.initialize" function). If your app has this functionality, try reloading this page.

### ISSUE THREAD

**Issue by hello-chenchen** [OfficeDev/office-js#906]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

when i load my add-on on the right side task pane. This log will display on my F12Choose.exe console, in a higher probability.  and it will cause my web site display ui not execute the javascript code what i write on the Office.initialize = () {...}.(ps: not only for **lib/1.1/hosted/office.js**, but also for **/lib/preview/hosted/Office.js**)
For example the load html:
```
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8" />
<meta http-equiv="x-ua-compatible" content="IE=Edge" />
<title>MS add-in</title>
<link rel="stylesheet" href="https://appsforoffice.microsoft.com/fabric/2.1.0/fabric.min.css">
<link rel="stylesheet" href="https://appsforoffice.microsoft.com/fabric/2.1.0/fabric.components.min.css">
<script src="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/js/fabric.min.js"></script>
<script type="text/javascript" src="https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js"></script>
</head>
<body>
<div id='app'></div>
<div class="ms-Spinner ms-Spinner--large loading" id=is-loading></div>
<script>
window.domainFromServer = '';
var SpinnerElements = document.querySelectorAll(".ms-Spinner");
for (var i = 0; i < SpinnerElements.length; i++) {
new fabric['Spinner'](SpinnerElements[i]);
}
</script>
<script src="https://unpkg.com/vue@2.5.17/dist/vue.js"></script>
<script>
window.domainFromServer="https://hostxxxx.net/fe-static/";
</script>
<script src="https://hostxxxx.net/fe-static/office365/js/chunk-common.9981c945.js"></script>
<script src="https://hostxxxx.net/fe-static/office365/js/login.e3e25ac0.js"></script>
...
</body>
</html>
```

The login.js file:
```
import Login from '../pages/Login.vue'

const Vue = window.Vue
Vue.config.productionTip = false

const Office = window.Office;

Office.initialize = () => {
    ....
    initVueFun();
}

const initVueFun = function() {
    new Vue({
        render: h => h(Login)
    }).$mount('#app')
};
```

![image](https://user-images.githubusercontent.com/1878089/70977891-c43ca900-20e9-11ea-8496-1f945519ee85.png)

**Comment by hello-chenchen** [comment]
Another question the same behavior is, it is not load the MicrosoftAjax.js. Error:
![image](https://user-images.githubusercontent.com/1878089/70978035-00700980-20ea-11ea-9ea2-430fa1d49e13.png)
I think it is also a problem, because it happened to offen.

please take a look, thanks

**Comment by exextoc** [comment]
Hey @hello-chenchen ,

Just a few things to follow up with you.

1. Are you seeing this issue across browsers, or any specific browser?
2. Can you check that window.Office and Office.initialize exists, before you use or assign values to them?
3. Can you ensure that Office.initialize is indeed getting overridden? You can try to put a breakpoint inside of Office.initialize and ensure it's getting hit, before any code that uses the Office library is called.

If 2 and 3 happen correctly, then ideally, you should not be facing this error.

**Comment by hello-chenchen** [comment]
Sorry, i have been to busy in the last few days.
Yes Actually, this is all platform(both windows outlook client, IE browser and chrome) both have this problem. But in relatively, the windows outlook client is more often.
In fact, not only my add-in, But also OneNote add-in can repro this problem.
![image](https://user-images.githubusercontent.com/1878089/71236795-cc3f5780-233a-11ea-89e0-ce6f6a2398e5.png)

As, you can see that, i use **Edge DevTools** to catch the error log for this problem. But actually, not only Edge DevTools, but also F12 debug tools(which is preview debug tools before Edge Devtools, and also ms official debug tools). You can find this debug tools from **C:\Windows\SysWOW64\F12\IEChooser.exe**.

**Comment by hello-chenchen** [comment]
just now, it happens on mac chrome browser too.
![image](https://user-images.githubusercontent.com/1878089/71237295-1d9c1680-233c-11ea-8aba-50f14dade58b.png)

**Comment by exextoc** [comment]
@hello-chenchen,
- The mac snapshot also has ERR_NETWORK_CHANGED and ERR_CONNECTION_RESET errors. Can you check if your network connection is stable?
- It looks like you are using Vue Js library for the add-in, can you test without any Vue code in the add-in and see if issue exists?
- We are unable to repro the issue at our end. Can you share stripped down version of your manifest to repro this issue?

**Comment by hello-chenchen** [comment]
Thanks for your reply, @exextoc ,

I think it is not vue js library cause this problem. Because i repro this problem in your onenote add-on. And i notice that onenote seams use react library.

Maybe my network connection is not stable. It happens in a higher probability last week. But this week, It seams worked well. So, can you give user some network error notification when you throw this error?

**Comment by hello-chenchen** [comment]
this error is throw from there:
![image](https://user-images.githubusercontent.com/1878089/71512384-e942d000-28d0-11ea-83cb-448847eb6e3c.png)

(Your debug code is Office.debug.js)
![image](https://user-images.githubusercontent.com/1878089/71512374-d4663c80-28d0-11ea-96bf-e189047e68ff.png)

**Comment by exextoc** [comment]
We agree with you on improving the logging part, have added it to our backlog.

Internal tracking id: OutlookWeb:62726

**Comment by adam-harwood** [comment]
I want to +1 this, but also call out a larger impact it can have: If the add-in has an OnSend event handler, and a poor network connection, then the following can happen:
- The user clicks to Send an email.
- The request is sent to load the function-file for the add-in, but this takes a long time because of the poor network connection.
- After some period of time, Outlook times out the fetch, and prints the error already highlighted above to the console.
- But most importantly, nothing happens on the UI. It sits there with a spinner say "{add-in} is working on your request". The user needs to close Outlook or navigate to another email before they can do anything again.

This seems really undesirable. We've had customers sitting there waiting for minutes for it to stop spinning, but it never does. Some error message that is show to the user would be much more desirable, ideally indicating that they should check their network connection.

**Comment by bx-anil** [comment]
We see this issue too and it's random.

**Comment by Syedtajudheenj** [comment]
Facing this same issue now and found out the reproducible scenario.
I'm using word online in chrome, Just switch network speed to slow 3g in the network tab

**Comment by justdevelopment** [comment]
We see the same issue, also think it might be related to internet speed. Users with slower internet report it more often and when throttling my connection I can reproduce the issue consistently.

**Comment by Enotsoul** [comment]
Can confirm that I've detected this issue when debugging other officejs/outlook plugin related issues, it seems to occur on a random fashion without any logic whatsoever.
