### ISSUE TITLE
Application.Run and Application.Evaluate does not work with Custom Functions in VBA

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js#907]
## Expected Behavior

I can run VBA code with Application.Run and Application.Evaluate to execute Custom Functions.

## Current Behavior

Currently it does now work, errors are shown.

## Steps to Reproduce, or Live Example

Open workbook and insert addin with custom functions in it.
Open VBA and try to execute e.g. Application.Evaluate function with the custom function.

## Context
This will allow users to automate things using VBA and custom functions.

## Your Environment

Win10 [Version 10.0.17134.1130]
Excel version 1912 (12325.20012)

**Comment by lumine2008** [comment]
VBA is running in Sync mode, but CF is running a Async mode, so i think VBA API cannot evaluate CF which is by design
