### ISSUE TITLE
Excel: Binding's onDataChanged event does not work correctly when added to Range

### ISSUE THREAD

**Issue by 4tti** [OfficeDev/office-js#919]
## Expected Behavior

The onDataChanged event should be fired **only** when the corresponding cell is changed. Then the binding can be used for just monitoring changes of specific cell.

## Current Behavior

When you use binding for cell, e.g. A1 it fires onDataChanged event randomly even for changing completely different cells.

## Steps to Reproduce, or Live Example

Check this gist (see the description in the taskpane):
https://gist.github.com/jhernaez/f03886f80a70ee077fc50fd77102fe71

## Your Environment

Win10 [Version 10.0.17134.1130]
Excel version 1912 (12325.20012)

**Comment by 4tti** [comment]
We wanted to use this event for customizing behavior when user types certain special 'command' over some of the cells/formulas, however with this strange event firing we cannot use it and it means for us quite critical issue.
It would be extremely helpful to get at least estimate when the fix will be ready (once confirmed it is bug).
Thanks in advance!

**Comment by lumine2008** [comment]
Thanks @4tti , I can repro this issue, a bug 3868915 is created to track this bug. team is investigating this issue now.

**Comment by lumine2008** [comment]
This issue was fixed, please verify. thanks
