### ISSUE TITLE
Adding a brand new setting after modifying an existing setting causes an ItemNotFound error

### ISSUE THREAD

**Issue by aldaliu** [OfficeDev/office-js#920]
Trying to add a brand new setting after modifying an existing setting causes an ItemNotFound error on Excel Online but works in Desktop Excel (Office 365 mac)

i.e. 
settings.add("thisExists", true)
settings.add("thisDoesntExist", true)
fails 

This might be related to adding two brand new settings in a row 

## Expected Behavior
It should work, both settings should be added

## Current Behavior
Works on desktop Excel but doesn't work on Excel Online

## Steps to Reproduce, or Live Example
This is the exact example provided by ScriptLab only that I added another `setSetting` call after the first one to show the bug

https://gist.github.com/aldaliu/23c7183fb6187343bfde7a9ea9bd44b2

## Context
I'm trying to set multiple settings but this error is occurring on Excel Online but not Desktop Excel

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.32
* Operating System: Mac
* Browser (if using Office Online): Firefox

## Useful logs
![Screen Shot 2020-01-02 at 3 37 24 PM](https://user-images.githubusercontent.com/12956632/71691588-cc494980-2d75-11ea-8afa-949be00bb714.png)
![Screen Shot 2020-01-02 at 3 22 22 PM](https://user-images.githubusercontent.com/12956632/71691596-d4a18480-2d75-11ea-82ec-54c92e3c56ec.png)

**Comment by lumine2008** [comment]
Thanks @aldaliu , I can repro this issue, a bug 3869316 is created to track this bug. team is investigating this issue now.

**Comment by aldaliu** [comment]
Thanks @lumine2008! This seems to be a regression as this has worked for us in the past. Is there a timeline that we can expect for the fix? It's currently affecting us on production :/

**Comment by MandytMSFT** [comment]
@aldaliu the culprit change has been turned off. I have verified your scenario works now from my side. Let me know if you still have this issue. Thanks for your reporting !

**Comment by aldaliu** [comment]
@MandytMSFT @lumine2008 Thank you both for the quick responses and turnaround! Really appreciate it :)
