### ISSUE TITLE
Word Online: FunctionFile.html does not load if X-Frame-Options SAMEORIGIN header is set

### ISSUE THREAD

**Issue by ukalhapu** [OfficeDev/office-js#925]
We are developing Office add-in for Word online. It has defined add-in commands to render custom ribbon.
The server has security setting which set header X-Frame-Options SAMEORIGIN for each resource. 
Word online is unable to load the FunctionFile.html. 
Browser shows message: 
Refused to display '<server:port>/webapp/html/officeapp/app/FunctionFile.html?et=' in a frame because it set 'X-Frame-Options' to 'sameorigin'
We enabled CORS in web server which is Apache :
     Header set Access-Control-Allow-Origin "*"
But still the issue. 
We can not disable security setting  X-Frame-Options SAMEORIGIN. 
Does office online loads the FunctionFile.html in IFRAME ?
How to resolve the issue ?

## Expected Behavior
Word online should be able to load FunctionFile.html as CORS is enabled in Apache 

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: ______
* Host [Excel, Word, PowerPoint, etc.]: ______
* Office version number: ______
* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by ukalhapu** [comment]
could you please re-open it ?

**Comment by ukalhapu** [comment]
pls some take look ?

**Comment by iyunbo** [comment]
Same issue here, please re-open.
