### ISSUE TITLE
Outlook for Mac: Office.context.mailbox.item.addFileAttachmentAsync() fails with "Internal Error"

### ISSUE THREAD

**Issue by illiach** [OfficeDev/office-js#927]
Attempt to add an attachment to an Outlook message in compose mode using method Office.context.mailbox.item.addFileAttachmentAsync() fails with an error.

## Expected Behavior

Attachment should be added into Outlook message without any errors.
--
## Current Behavior

An error occurs:
{code: 5001, message: "An internal error has occured.", name: "Internal Error"}

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. URL and file name are provided and correct, 
  2. The file can be properly added from browser an in Outlook on Windows.

## Context

The file is being downloaded from external system and has to be inserted into new mail message in Outlook in compose mode.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]:Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: v16.31
* Operating System: Mac OS Mojave 10.14.4
* Browser (if using Office Online): ______

## Useful logs

{code: 5001, message: "An internal error has occured.", name: "Internal Error"}

**Comment by exextoc** [comment]
Just to confirm: This issue only happens on Outlook For Mac? And not Outlook for Win32? 

Is it possible for you to provide the URL (or similar URL hosted on the same site), for us to test? It would also be interesting to note if ALL files aren't being attached...i.e. if you try to add a file from another domain)

**Comment by illiach** [comment]
@exextoc , yes this issue only happens on Outlook For Mac. Outlook for Win32 is not affected.
All files aren't being attached.
I will check if we can provide the URL to test.

**Comment by exextoc** [comment]
We are not able to reproduce the issue mentioned, it will be helpful if you can share the url used.

**Comment by illiach** [comment]
@exextoc , please use the following URL:
https://mm-litify-addin.smartcloudconnect.io/ExternalFiles/DownloadDocument/eb42da3d-d106-ea11-9c2b-3ca82a1e3f41/0612edf4-01ea-45d5-82d1-d2b99d5a0b8c/su25-2.jpg

**Comment by exextoc** [comment]
Hi, we're able to reproduce this bug with the URL you've provided. It only seems to happen for this particular URL. We are working on fixing this issue, but unfortunately we don't have any timelines to share at this point.

**Comment by vputsenko** [comment]
@exextoc  why is this ticket closed if you confirm that bug present? closed ticket means fix and release date (at least appoximate)

**Comment by exextoc** [comment]
Internal tracking ids: Office:3899937 and OutlookWeb:63811

**Comment by exextoc** [comment]
This issue has been fixed and you should see it on the latest build.
