### ISSUE TITLE
Previously Working AddIn Is Not Starting Up.

### ISSUE THREAD

**Issue by glr0221** [OfficeDev/office-js#928]
We have developed an addin which had been working really well with your standalone outlook clients. It is a script based taskpane-type addin. Recently,  some of our end users have started experiencing problems during the loading of the addin. I cannot reproduce the same issue on my machine (Windows 10 B1909 and  Office MSO 16.0.12325.20280). I was thinking that this was an issue related to Outlook-moving-to-EDGE-dropping-IE. (https://docs.microsoft.com/en-au/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins)

Note also that our addin is still working fine with the browsers (OWA). The issue we are having is right now with standalone clients.

Do you have anything in your documentation or knowledge-base that can potentially cause the following? 

![image-edited](https://user-images.githubusercontent.com/3444844/72140894-abfc3900-33cc-11ea-830c-f32da191ca85.png)

Thanks.

**Comment by exextoc** [comment]
Usually bugs like this mean that your add-in hasn't even been loaded yet.

- On customer machines that are failing, do ALL add-ins fail to load or just yours

- What versions of Outlook/Windows are the failing machines on?

If they are failing on IE, then it could be they have IE settings that are preventing the add-in from being reached/loaded. (see https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/apps-for-office-not-start)

**Comment by glr0221** [comment]
@exextoc @AlexJerabek 

Thank you for your quick replies. There are currently at least 2 client-companies affected by the issue. I am collating all the data so please give me some time. Thanks again.

**Comment by exextoc** [comment]
Thanks. We will wait to hear back from you.

**Comment by glr0221** [comment]
@exextoc @AlexJerabek 

Sorry for the delay. This is the best set of data we have gathered so far :

1 Company with over 60 clients are affected
=================
1. It looks like it is not happening on a domain-wide basis.
2. It does not seem to be an issue of Windows 10 version. As it has been reported to happen on Windows 10 builds 1803, 1809, 1903 and/or 1909.
3. It is not just our addin, but happens on two other installed addins as well. 
4. Our client-respondents have said that this does not occur in Office version 1902 and 1903. But started happening when they updated to versions 1904 and 1905. 
5. The "bitness" of the Office installation does not seem to matter either. (32bit and 64bit are affected too
6. This does not happen when they are accessing OWA or Outlook via Web Browser, just on Outlook-Office installed clients.

1 Company with admin testing on 1 client
==================
In one other report one of our end users started experiencing it recently in his test machine before he rolls it out to everyone. So in his tests he found the following : 
1. 16.0.12228.20322 64bit - AddIn is not loaded, addin not working
2. OWA via firefox (same account) - Addin working properly 
3. 16.0.12.12325.20280 64-bit (same account) - Addin Working Properly

Final NOTE : Is it possible that this is connected to the update you guys had on "office.js" released last December 12, 2019? 

Unfortunately, I cannot reproduce the issue on any of my test machines, and in any test machine in our test network. Or else I would have shared whatever notes I had on this issue. So any help / feedback would really be appreciated. Our addin is currently used by a LOT of end users but only a few have come back to us with more details on the issue.

Thank you always. Your prompt assistance is sincerely appreciated.

**Comment by glr0221** [comment]
@exextoc 
Probably linked to this : https://github.com/OfficeDev/office-js/issues/902

Just a quick update, it turns out this is not related to the above ticket.

**Comment by exextoc** [comment]
Were you able to determine whether [IE configuration](https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/apps-for-office-not-start) was causing an issue for some of the users?

Note that starting in Office version 16.0.11629, [Edge WebView replaces IE](https://developer.microsoft.com/en-us/office/blogs/microsoft-edge-webview-for-office-add-ins/) within Outlook for users running Windows version 1903 or later. So if it the issue is caused by IE configuration, updating Office may be an alternative option to resolve the issue for those users.

We aren't aware of any specific issue introduced in Office version 1904 that would cause this error. But given that 12325 seems to have helped in one case, could the first customer try updating to that version if it's an option?

If not, could one of the impacted users use the "Send a Frown" button (under File > Feedback) to report the issue? This will send diagnostics information to the Office team.

**Comment by glr0221** [comment]
@exextoc 

> Were you able to determine whether IE configuration was causing an issue for some of the users?

Yes, our clients did the workaround.
Thank you very much. I will send your instructions to our client. I will ask them to send a feedback to send some diagnostics your way. And include the url for this ticket if that helps. Thank you very much.

**Comment by exextoc** [comment]
> Yes, our clients did the workaround.

@glr0221 Thanks for the update. Do you mean that the suggested fix resolved the issue, or that the issue persisted after the workaround was implemented?

**Comment by glr0221** [comment]
@exextoc Yes, the issue persists even after the [IE Configuration](https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/apps-for-office-not-start)  workaround. I talked with our Customer support team and they told me that this is their first step [IE Configuration](https://docs.microsoft.com/en-us/office/troubleshoot/error-messages/apps-for-office-not-start) when troubleshooting this problem. For the mean time, I told our clients to update their versions as this may be a "version-specific" bug or submit a feedback to you guys if they still can reproduce the issue. I will also update this ticket with anything we find along the way. Thank you again, we really appreciate it.

**Comment by exextoc** [comment]
You're welcome. Please let us know if there is anything else needed, and we are happy to help if there are any more questions.
