### ISSUE TITLE
Pattern match in outlook attachments

### ISSUE THREAD

**Issue by sourabhkrishna** [OfficeDev/office-js#929]
how to perform pattern matching in Outlook attachments (Docx , pptx etc) while sending an email using office js

the getAttachmentContentAsync does get the file contents , but in base64 . how can I perform a simple search and modify content (highlight) before the mail is being sent.

**Comment by exextoc** [comment]
It may be helpful if you describe your scenario to better understand what solutions there are. 

getAttachmentContentAsync does return to you results in base64. Could you convert it and search for the information that you want? 

There is no way to highlight text in a compose body. You cannot modify an attachment, but you could remove and replace it.

**Comment by sourabhkrishna** [comment]
Use Case: Search the email attachments for some sensitive words and highlight them. 
I tried using below snippet code in my outlook addin

Word.run(function (context) {
		var myNewDoc = context.application.createDocument(content);
		context.load(myNewDoc);
}

But got an error saying Word is not defined. 
How can I convert base64 and perform a search using browser context ?

**Comment by exextoc** [comment]
Unfortunately, Word Office JS functionality is not supported within Outlook JS.

Can you use atob() to convert the attachment to something you can decipher/change? Then use bota() to convert it back to base64 and use addFileAttachmentFromBase64Async() to add it back? This would work for simpler types of attachments (like text files). I am not sure it will work for Word / PPT Attachments. You may need to use other libraries or tools to use the data from getAttachmentContentAsync() to something that you can change.

**Comment by exextoc** [comment]
We track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered, when we go through our planning process.
