### ISSUE TITLE
Excel: add comments do not work as expected

### ISSUE THREAD

**Issue by ruei-yu-yang** [OfficeDev/office-js#932]
My local execution environment: excel pro plus 2019.
I try to using this page add comments sample in my local machine, 
no error occurred during execution, but no show comments.

var comments = context.workbook.comments;
comments.add("Sheet1!A1", "comments...");
return context.sync();

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 992f7232-6aa0-b170-ff3b-009a273e7586
* Version Independent ID: 0fd9c00f-91d6-5036-48c9-e0e2e0690e78
* Content: [Work with comments using the Excel JavaScript API - Office Add-ins](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/excel-add-ins-comments)
* Content Source: [docs/excel/excel-add-ins-comments.md](https://github.com/OfficeDev/office-js-docs-pr/blob/master/docs/excel/excel-add-ins-comments.md)
* Product: **excel**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by AlexJerabek** [comment]
Assigning @catchingyu for further investigation.

**Comment by xiaochunms** [comment]
@ruei-yu-yang Sorry for the inconvenience. May you please provide more information that can help us for debugging the issue?
1. Code snippet to repro the issue,
2. It would be great to have some screen snapshots that can help us to understand the issue,
3. Add try... catch block to catch errors if there is any

**Comment by lumine2008** [comment]
@ruei-yu-yang, we could not locate the issue you described in your post, so it would be great if you could share the gist and then we can do some investigation in our side. thanks
