### ISSUE TITLE
[outlook]: How can I access to microphone in office add-in ?

### ISSUE THREAD

**Issue by MicleMing** [OfficeDev/office-js#933]
There is a pop-up to ask for microphone permission on web, but Nothing happened on desktop app , so I can't access to microphone on desktop. It seems that there isn't any useful informations on docs.  how can I access to microphone on desktop ? 
Platform: MacOS 
Thanks

**Comment by kbrandl** [comment]
I've transferred this issue to the **OfficeDev/office-js** repo.

**Comment by exextoc** [comment]
Hey,
We officially do not have support for microphone in a web add-in, but yes, we do realise that there is an inconsistency across platforms. We thank you for bringing up this issue, it has been put in our backlog and we will look into it. However, if you need Microphone support as a feature for add-ins I recommend adding a request on our [uservoice ](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins) page. We look through the uservoice page during our planning process.

**Comment by MicleMing** [comment]
hi, @exextoc 
 I have add a [request](https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/39616504-allow-user-to-access-to-microphone-in-office-add-i) on uservoice, and when can your support this feature and would you share the planning for me ?
  Thx

**Comment by JuaneloJuanelo** [comment]
Thanks for adding the uservoice request! we will update what features will go into our backlog soon.

**Comment by phihochzwei** [comment]
Is there a certain amoint of voices needed for to get active? We are also in need of this, rather basic feature. In May this year it was actually possible and now it isnr anymore :(
