### ISSUE TITLE
Excel Custom Functions: API Calls Timing Out After 60 Seconds

### ISSUE THREAD

**Issue by cidev5** [OfficeDev/office-js#934]
Our API needs longer than 60 seconds to complete some requests for custom functions, but there seems to be a limit of 60 seconds for completing API requests, after which requests fail. There is nothing specified on our end to cause requests to fail after 60 seconds, and setting timeouts on XMLHttpRequest does not fix this behavior. Is this a known limitation on custom functions, and is it possible to override this behavior?

**Comment by xiaochunms** [comment]
@dawid84 sorry for the inconvenience. May you please provide more information that can help us to debug? The information includes:
1. The platform runs when your API calls Custom Functions, is it Desktop or Excel Online?
2. May you please share some code snippets that we can know more about your scenario?

**Comment by cidev5** [comment]
Answers:

1. Desktop has the issue we are describing. Excel Online works correctly.

2. We are using `fetch`

```
async function makeApiRequest(...) {

  const configJson = await OfficeRuntime.storage.getItem('access');

  try {
    const requestUrl = `${config.apiUrl}/${entry.url}?${queryString}`;
    const response = await fetch(requestUrl);

    ...
 }
 ...
```

**Comment by xiaochunms** [comment]
Thanks for the information. Good to know Excel Online works correctly. From your code snippet, is the "**makeApiRequest**" the custom functions who fails in Desktop due to the execution time longer than 60 seconds? Could you please explain a little bit more about your scenario, such as how the return result of **makeApiRequest** used? Screenshots are also helpful too.

**Comment by cidev5** [comment]
`makeApiRequest` is used in each custom function to make the API request.

Here is an example custom function that has all the relevant parts of this method.

Please note the line `const response = await fetch(requestUrl);`

```
/**
 * Gets Some Data.
 * @customfunction EXAMPLE.FUNCTION
 * @param code Code
 * @returns Example
 */
async function getSomeData(code: string): Promise<any[][]> {
    const invocationEntry: BatchEntry = {
        url: 'data/example/example',
        params: { code },
        isSingleCell: false,
        address: undefined
    }

    const promise = new Promise<any>((resolve, reject) => {
        invocationEntry.resolve = resolve;
        invocationEntry.reject = reject;
      });

    const configJson = await OfficeRuntime.storage.getItem('access');

    if (configJson == null) {
        invocationEntry.resolve(handleError(401, invocationEntry.isSingleCell));
        completeRequest();
        return;
    }

    try {

    const config: {
        accessToken: string;
        apiUrl: string;
        expiration: number;
    } = JSON.parse(configJson);

    var time = new Date().getTime();

    if (config.expiration == null || time > config.expiration) {
        invocationEntry.resolve(handleError(401, invocationEntry.isSingleCell));
        completeRequest();
        return;
    }


    const requestUrl = `${config.apiUrl}/${invocationEntry.url}?${...}`;

    const response = await fetch(requestUrl);

    const text = await response.text(); // Parse it as text

    if (!response.ok || text == '') {
        invocationEntry.resolve(handleError(response.status, invocationEntry.isSingleCell));
    }

    const json = JSON.parse(text);
    if (invocationEntry.address && json.format) {
        await OfficeRuntime.storage.setItem(`${dataFormatPrefix}${invocationEntry.address}`, JSON.stringify(json.format));
    }

    if(json.data === null || json.data === undefined){
        invocationEntry.resolve( invocationEntry.isSingleCell ? NA : [[NA]]);
    } else {
        invocationEntry.resolve(json.data);
    }


    } catch (error) {
        let message = 'error: ' + error.message;
        invocationEntry.resolve(invocationEntry.isSingleCell ? message : [[message]]);
    } finally {
        completeRequest();
    }

    return promise;
}
CustomFunctions.associate("EXAMPLE.FUNCTION", getSomeData);

```

Result:

The cell will display `#BUSY!`
Until it errors out
Then it displays `error: Network request failed`

This is contingent on the call taking longer than 60 seconds.

**Comment by cidev5** [comment]
We are still experiencing this issue in our production application. When should we expect this to be resolved?

**Comment by xiaochunms** [comment]
Sorry to hear that you still hit the issue. As I know there is no 60-second limit in Custom Functions. May you please help to clarify that can the API call success in case of "fetch" call returns within 60 seconds?

**Comment by cidev5** [comment]
Yes, we have success for API calls using "fetch" within 60 seconds.

**Comment by csreddyennam** [comment]
I have a similar issue, i am using javascript. my call never success.
Please find the below code:
function getrandom(x) {
  
  let url = "http://xxx:345/abc/V2/tag";

  let xhttp = new XMLHttpRequest();
  xhttp.timeout = 10000000000;
  xhttp.withCredentials = true;

  return new Promise(function(resolve, reject) {
 
    xhttp.onreadystatechange = function(){

      if (xhttp.readyState !== 4) return; 

      if (xhttp.status == 200)
      {
        resolve("response status 200 " + xhttp.status);
      }else{
        resolve("reject (custom) status;  " + xhttp.status + " xhttp.statusText: " + xhttp.statusText + " xhttp.readyState: " + xhttp.readyState  + " xhttp.responseText: " + xhttp.responseText);
      }

    }
    
    xhttp.open("GET", url,  true, "wwuser", "wonderware");
    xhttp.send(null);

  });
}
CustomFunctions.associate("RANDOM", getrandom);

Response in excel: 
reject (custom) status;  0 xhttp.statusText: undefined xhttp.readyState: 4 xhttp.onerror: null				

reject (custom)   status;  0 xhttp.statusText: undefined   xhttp.readyState: 4 xhttp.responseText: Error code = 15
--




reject (custom)   status;  0 xhttp.statusText: undefined   xhttp.readyState: 4 xhttp.responseText: Error code = 15
--

**Comment by dho-caissa** [comment]
To demonstrate the 60 seconds timeout behavior, we created a demo project with two custom functions. One function calls a data service that takes 70 seconds to complete. The other function calls a data service that takes 5 seconds to complete. The first function failed with "Network Request Failed" error. The code for demo project can be found here. The readm.md has instructions how to run it.
https://github.com/dho-caissa/ExcelAddinDemo.
The excel custom function seems have a timeout limit on fetch() call. Is there way to change it?

**Comment by dho-caissa** [comment]
@xiaochunms We are still experiencing this 60 seconds request time limit in our current production Excel Add-In application. Is there setting in Excel or configuration that allows us to change this behavior? Thanks

**Comment by xiaochunms** [comment]
Sorry for the late response. Thanks for the efforts to nail down the issue to fetch api. Is it possible to have another test to know where the timeout limit is from, is it from the fetch api call itself or from custom function fetch api call?

**Comment by dho-caissa** [comment]
@xiaochunms we tested the fetch call for API that takes more than 60 seconds in other browsers and in side loader. They worked. It is definitely some setting in Excel / Excel custom functions that limit the time allowed for API calls

**Comment by xiaochunms** [comment]
@dho-caissa you may can try [Run your add-in code in a shared JavaScript runtimes](https://docs.microsoft.com/en-us/office/dev/add-ins/excel/custom-functions-shared-overview)

**Comment by zlatko-michailov** [comment]
I responded in issue #1184. Let's continue there.
