### ISSUE TITLE
My Add-ins menu on Insert Ribbon Tab is disabled when opening xls file

### ISSUE THREAD

**Issue by lapnd** [OfficeDev/office-js#935]
**My Add-ins** menu on Insert Ribbon Tab is disabled when opening xls file
## Expected Behavior

My Add-ins menu on Insert Ribbon Tab is enabled to select and activate add-ins to work with xls files

## Current Behavior

- Opening xlsx file: My Add-ins menu on Insert Ribbon Tab is enabled, everything work fine
- Opening xls file: My Add-ins menu on Insert Ribbon Tab is disabled, the add-ins can not be selected and activated

## Context

We have a lot of xls files from different projects and teams.
Our development team want to develop Excel add-ins that support all teams/projects with older file format.

## Your Environment

- Platform: Mac
- Host: Excel
- Office version number: 16.30 (19101301)
Operating System: MacOS catalina

## Useful logs

![image (1)](https://user-images.githubusercontent.com/17825933/72307424-d25ff400-36ac-11ea-8d61-ae886b003400.png)

**Comment by erayc-msft** [comment]
Hello -- thank you for your feedback.  Currently the feature: My Add-ins support for XLS files, is not part of the product.  We track Office Add-in feature requests on our [UserVoice page](https://officespdev.uservoice.com/).  Please add your request there.  Feature requests on user-voice are considered when we go through our planning process. 
Thanks, Office Platform team
