### ISSUE TITLE
EWS ExpandDL operation always fails saying it is unavailable.

### ISSUE THREAD

**Issue by duncan-smith-bj** [OfficeDev/office-js#937]
I am using a Mail Add-in hosted in OWA. 

During the OnSend event, I need to expand any distribution lists on the message to get the members they contain. When I try to do this through EWS using the ExpandDL operation it always fails with the error:

**_The requested web method is unavailable to this caller or application._**

I have tried hosting the Mail Add-in in Exchange 2016, Exchange 2019 and Office 365. All fail with the same error when calling the ExpandDL EWS operation.

The documentation for Add-ins states that this EWS operation is supported but it always fails.

Is the documentation wrong or is there some magic I am missing on how to get this to work?

Cheers
Duncan

**Comment by exextoc** [comment]
Hi, we are able to reproduce this on Outlook Web. Thanks for reporting this issue. We're working towards fixing it, but unfortunately don't have timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: OutlookWeb:63772
