### ISSUE TITLE
Security Popup in Outlook For Mac latest build every time I open a Contextual Add-In

### ISSUE THREAD

**Issue by kakusharma** [OfficeDev/office-js#939]
Everytime I click on the highlighted text to open the contextual Add-In, I get a popup with heading "Microsoft Office Potential Security Concern", asking me to allow the action. This same behavior is happening for in-built Add-Ins as well (Bing Maps for example). Once I click on "Yes", the Add-In window opens up and works fine. Now if I click on the highlighted text again, the same popup comes, again. This is happening with this latest build only. I have tried the Add-In on previous builds and it was working just fine.
## Expected Behavior

The "Microsoft Office Potential Security Concern" popup shouldn't come everytime. Once I gave the permission, the Add-In window should open up without any security popup.
## Current Behavior

In the latest Outlook build, Version 16.33 (20011301), a security popup with heading "Microsoft Office Potential Security Concern" comes up everytime I click the highlighted text to open the Addin window, even though I gave the permission the first time.

Once I gave the permission for the Add-In to work, I shouldn't be seeing that popup again while opening the Add-In anymore.
## Steps to Reproduce, or Live Example

Update you Outlook for Mac to the latest version. Then try using the Bing Maps Add-In. You should see that security popup when you click the highlighted text.

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.33 (20011301)
* Operating System: Mac
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
Thank you for reporting this issue. This has been brought about by a recent security change, and is expected behaviour. However, we are aware of the pain point this poses for contextual add-ins. We are looking at a possible workaround for this, and will update this thread if we have one.

**Comment by exextoc** [comment]
We are currently working on a fix and it will be available in Production soon.

**Comment by kakusharma** [comment]
Great, thanks. Please do update me as soon as it's in production. Thanks again. :)

**Comment by kakusharma** [comment]
Is there any update on this security popup thing?

**Comment by exextoc** [comment]
@kakusharma We have fixed the bug and the fix should be available in next monthly build. Depending on the release channel a customer is on, getting an updated build can take anywhere from 4-8 weeks.

**Comment by kakusharma** [comment]
Thanks guys. Can't wait to see this update in the upcoming build. :)
