### ISSUE TITLE
Excel on the web: Error trying to copy cell with custom function

### ISSUE THREAD

**Issue by fds-ssg** [OfficeDev/office-js#941]
## Expected Behavior
Copy operation succeeds

## Current Behavior
Error dialog appears.  Message: 
```
Sorry, something went wrong.
Could you please try that again?

Give Feedback

Error Id: 2122fcaf-08d5-4471-b0ec-9632951e4359, 2020-01-17 20:04:05Z
```

## Steps to Reproduce, or Live Example
* Additional details:
The affected cell contains a formula with a custom function.  **Note that the issue occurs whether our add-in containing the custom function is loaded or not.**

* To repro:
  1. Open attached file
[Book 47.xlsx](https://github.com/OfficeDev/office-js/files/4078823/Book.47.xlsx)
  2. Select cell B2
  2. Perform a Copy operation (either click ribbon button or press Ctrl+C
  3. Error dialog appears
  4. Page reloads

## Context
I'm developing an Excel add-in with custom functions.

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]: Excel Online
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: 16.0.12513.35902
* Operating System: Win 10
* Browser (if using Office Online): Chrome

**Comment by RuoyingLiang** [comment]
Thanks for the reporting. We can repro it and start to investigate. Will update here once we have result.

**Comment by RuoyingLiang** [comment]
The fix is ready. Will update here once it's hit production. Bug 3896521 is tracking it.
