### ISSUE TITLE
[Outlook add-in] After update windows , dev tool not work any more, any recommend?

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#942]
After update windows to 1903 , dev tool(IEChooser) can't debug outlook client add-in any more.
Can microsoft recommend a debug tool?

## Expected Behavior

Have a tool can debug add-in in Outlook Client windows.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: ______
* Operating System: windows 10 1903
* Browser (if using Office Online): ______

I know this problem is because browser core changed to chromium. But for most user (include me) they don't want to install visual studio 2015+, just for add-in debug. 
Any recommend dev tool ?Or any setting that we can use IEChooser.

**Comment by exextoc** [comment]
We have some documentation here:
https://developer.microsoft.com/en-us/outlook/blogs/microsoft-edge-webview-for-office-add-ins/
https://docs.microsoft.com/en-us/office/dev/add-ins/concepts/browsers-used-by-office-web-add-ins

These talk about using the [Microsoft Edge DevTools](https://www.microsoft.com/p/microsoft-edge-devtools-preview/9mzbfrmz0mnj?rtc=1&activetab=pivot%3Aoverviewtab) for debugging add-ins running with Edge. Can you try this out to see if you are able to debug your add-in now?
