### ISSUE TITLE
Excel: On recent office upgrade we are unable to see the sharedfolder

### ISSUE THREAD

**Issue by csreddyennam** [OfficeDev/office-js#945]
Issue details: 
Open Excel: 
In Menu, Go to Insert (Menu) -> Get Add-ins -> Office Add-ins (Under shared Folder) we are unable to see the shared path.
-	We could see the shared path before update excel.

Excel details: (After upgrade)
Microsoft Office Professional Plus 2019
Version 1912 (Build 12325.20288)
Microsoft Excel 2019 MSO (16.0.12325.20280) 32-bit

OS Details:
Windows 10:
OS: Version 1903
The windows 10 Pro operating system

**Comment by lindalu-MSFT** [comment]
@lumine2008 @keyur32 @Reezaali Hi, can you please address this issue? The customer reports that he cannot see the shared path after upgrading. Is this anything that is known or can be repo'd?  Please assign accordingly if necessary! Thanks, linda

**Comment by Lilyliu123** [comment]
Same issue, cannot see the addins Insert (Menu) -> Get Add-ins -> Office Add-ins (Under shared Folder). User who have already had addin added before got the error that cannot reach to the server of shared folder （Sorry cannot remember the exact message).

Excel version: office 365 MSO(16.0.12430.20172) 64-bit

**Comment by csreddyennam** [comment]
After recent update of office, its working fine.
