### ISSUE TITLE
Outlook: Office.context.mailbox.item.cc and Office.context.mailbox.item.to returns only 20 email addresses in OWA

### ISSUE THREAD

**Issue by Sankledar** [OfficeDev/office-js#948]
Office.context.mailbox.item.to and Office.context.mailbox.item.cc returns only 20 email addresses for each field if add-in was opened in Email with more than 20 emails in each of these fields.

## Expected Behavior
https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-1.1#to
https://docs.microsoft.com/en-us/javascript/api/outlook/office.messageread?view=outlook-js-1.1#cc

>By default, the collection is limited to a maximum of 100 members. However, on Windows and Mac, you can get 500 members maximum.

It means  that these fields should return 100 items maximum in OWA.

## Current Behavior
If email contains more than 20 email addresses in **TO** or **CC** field then Office Javascript API methods
`Office.context.mailbox.item.to` or 
`Office.context.mailbox.item.cc` respectively returns only first 20 email addresses untill collapsed fields are expanded
![image](https://user-images.githubusercontent.com/15731794/72903544-721d2200-3d3e-11ea-90c3-ba08a7a1daa3.png)

Once I click on these down arrows the rest of addresses is loaded and after that 
`Office.context.mailbox.item.to` 
`Office.context.mailbox.item.cc` returns actual list of email addresses

## Steps to Reproduce, or Live Example
* Link to live example: https://codepen.io/sankledar/project/editor/DPmPNm 
Just replace <SERVER_NAME> in manifest and deploy solution.
* Prepare email with more than 20 email addresses in **TO** or **CC** field
* Run installed add-in in OWA in Read Form of prepared email
* Add-in will show that field with more than 20 addresses contains only 20 addresses
* Expand list of collapsed email addresses and re-run add-in
* Add-in will show actual count of email addresses (even not limited neither by 100 nor by 500 items) 

## Environment

* Platform: Office Online
* Host : Outlook
* Office version number: 16.0.10908.10000
* Operating System: Windows 10 version 1803 (OS Build 17134.1246) (64-bit)
* Browser (if using Office Online): Google Chrome  Version 79.0.3945.117 (Official Build) (64-bit)

Also the same issue was posted on User Voice 
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/37142968-fix-issue-in-the-new-outlook-that-limits-the-dis

**Comment by exextoc** [comment]
Hi, we were able to repro this issue. Thanks for reporting. We, however have no timelines to share at this point. It has been put on our backlog.

**Comment by lindalu-MSFT** [comment]
Hi @exextoc Thanks for updating the customer about this issue. Question for you: until this is fixed, should I make an update to the documentation?

**Comment by Sankledar** [comment]
Hi, any updates on this?

Thank you.

**Comment by lindalu-MSFT** [comment]
Pinging @exextoc  customer inquiring about status update!

**Comment by exextoc** [comment]
@lindalu-MSFT Yes, we need a documentation update.
@Sankledar This is a platform behavior and involves a non-trivial fix. We request you to share your ask on [User Voice](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins).

**Comment by ElizabethSamuel-MSFT** [comment]
@Sankledar The documentation has been updated to indicate this limit for Outlook on the web.

Thanks again for letting us know about this.
