### ISSUE TITLE
Comment of "timeZone" is obviously wrong

### ISSUE THREAD

**Issue by BrendanJiang** [OfficeDev/office-js#951]
It's an obvious copy error by commenting "timeZone" as "Gets the user's SMTP email address.".

In fact I'd like to know what time zone ID this property shows, Windows, Rails, or Iana. Could you please specify this as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 32ddf3ef-2ff6-0046-19a4-191578b09135
* Version Independent ID: 39937c7a-37f8-32a3-6db5-bf7c6d5c0c00
* Content: [Office.UserProfile interface - Office Add-ins](https://docs.microsoft.com/en-us/javascript/api/outlook/office.userprofile?view=outlook-js-preview#feedback)
* Content Source: [docs/docs-ref-autogen/outlook/outlook/office.userprofile.yml](https://github.com/OfficeDev/office-js-docs-reference/blob/live/docs/docs-ref-autogen/outlook/outlook/office.userprofile.yml)
* Product: **outlook**
* Technology: **add-ins**
* GitHub Login: @o365devx
* Microsoft Alias: **o365devx**

**Comment by exextoc** [comment]
Office.context.mailbox.userProfile.timeZone will return the timeZone in the Windows format.

**Comment by ElizabethSamuel-MSFT** [comment]
@exextoc Thanks for the update. We're adding this info to the docs.

Thanks.
