### ISSUE TITLE
Win10. Word Desktop. Not able to Login in Add-in after Word update

### ISSUE THREAD

**Issue by aburtsev1** [OfficeDev/office-js#954]
**Description**: 
We have Office 365 ProPlus with Channel = Semi-Annual. We got a new update in January. And We are not able to login to our Add-In after the update. 

**Word Version**: Version 1908 (16.0.11929.20562)
**Win Version**:   1909  Build 18363.657

**Steps**: 
1. Install 'Model N Author' from  Add-in store 
![Step1](https://user-images.githubusercontent.com/20722542/73273249-5907eb80-41ec-11ea-8839-0439db7bcc6b.png)

2. Open "Model N Author" add-in in Word Desktop and Click the 'Production' button
![Step2](https://user-images.githubusercontent.com/20722542/73273294-691fcb00-41ec-11ea-8c4e-a106af5c7277.png)

**Expected Results**: 
Dialog for log in to SFDC is opened, user able to enter credentials
![Expected results](https://user-images.githubusercontent.com/20722542/73274265-f879ae00-41ed-11ea-96ae-8d9728bb936a.png)

**Actual Results**: 
1. Popup opened and closed
![Error1](https://user-images.githubusercontent.com/20722542/73273364-8785c680-41ec-11ea-85f2-2218cf2879d8.png)
2. If user will click again on Production btn The user sees an error: "The operation failed because this add-in already has an active dialog. "
![Error2](https://user-images.githubusercontent.com/20722542/73273385-8d7ba780-41ec-11ea-9917-e8e0bef15e3e.png)

**Video**
[Screencast 2020-01-28.zip](https://github.com/OfficeDev/office-js/files/4122912/Screencast.2020-01-28.zip)

**Additional info**: 
**!!** Issue is not reproducible on early access versions 16.0.12410.xxx (Office Insider Program) and on older than Version 1908 (16.0.11929.20562)

**!!** F12 chooser is not able to see our processes in debug
![Additional info](https://user-images.githubusercontent.com/20722542/73273410-97050f80-41ec-11ea-873d-60e3499cac47.png)

**!!** We were able to reproduce it on Version 1908 (16.0.11929.20562)  and 16.0.12228.xxxx versions of Word. 

Please assist, thanks

**Comment by aburtsev1** [comment]
Hello @weshi @JuaneloJuanelo 
Do you have any updates on this item about eta and etc?

**Comment by dmashchenko** [comment]
Hi @lliu113 , @weshi  could you please speed up the process of reviewing this issue? Looks like it's becoming a real problem for our customers. Thanks.

**Comment by aburtsev1** [comment]
Issue fixed with new Word update 
![Version](https://user-images.githubusercontent.com/20722542/76965777-8d1aa580-692d-11ea-94a8-bffd3af19ce1.png)
