### ISSUE TITLE
onCalculated event returns address as "null" (PREVIEW ONLY) in Beta version

### ISSUE THREAD

**Issue by topkoong** [OfficeDev/office-js#955]
**I have used a freshly installed custom function from yeoman using "yo office".**
In Excel online and installed Excel with Office Insider program, the onCalculated event (written in taskpane.ts) returns the address of the ranges that completed calculation as "null". 

I have also referenced the beta library on the CDN (https://appsforoffice.microsoft.com/lib/beta/hosted/office.js) and installed  type definition file for TypeScript compilation and IntelliSense, which is found at the CDN and DefinitelyTyped by using npm install --save-dev @types/office-js-preview.
## Expected Behavior

When I output an event from onCalculated to the web console (using console.log in this case), it should return the value of address, type, and worksheetId.
## Current Behavior

When I output an event from onCalculated to the web console (using console.log in this case), I got the value of address, type, and worksheetId. However, the address is null.
## Steps to Reproduce, or Live Example

**In taskpane.ts, I have the following code:**

```
Office.initialize = () => {
  document.getElementById("sideload-msg").style.display = "none";
  document.getElementById("app-body").style.display = "flex";
  document.getElementById("run").onclick = run;
};

async function run() {
  try {
    await Excel.run(async context => {
      const sheet = context.workbook.worksheets.getItem('Sheet1');
      sheet.onCalculated.add(event => Excel.run(async context => {
         console.log("The worksheet has recalculated.");
         console.log('event: ', event);
         await context.sync();
      }));
      await context.sync();
    });
  } catch (error) {
    console.error(error);
  }
}
```

**In function.ts, I have the code like so:**

```
/**
 * Adds two numbers.
 * @customfunction
 * @param first First number
 * @param second Second number
 * @returns The sum of the two numbers.
 */
/* global clearInterval, console, setInterval */

export function add(first: number, second: number): number {
  return first + second;
}
```

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online, Office Online, Office Desktop
* Host [Excel, Word, PowerPoint, etc.]: Excel
* Office version number: ______
* Operating System: macOS Mojave
* Browser (if using Office Online): Chrome, New Microsoft Edge, Safari

## Useful logs

- [x] Console errors
- [x] Screenshots
![Screen Shot 2563-01-30 at 17 02 22](https://user-images.githubusercontent.com/18175994/73439777-bf267700-4382-11ea-8331-d4292d50cfaf.png)

- [ ] Test file (if only happens on a particular file)

**Comment by xiaochunms** [comment]
Hi @topkoong thanks for you to try the new feature of onCalculated event. You may notice that it is in Beta version. The feature is still in rolling out. Regarding to the feature rolling out, I am sorry I don't have ETA yet, but it should be available soon.
