### ISSUE TITLE
office (Word) how to set the first pageheader header (or footer) different with others? 

### ISSUE THREAD

**Issue by waveheart** [OfficeDev/office-js#956]
if users didnot manually check the checkbox 'first page diffrent with others', 
i get the first page header, the i set it , it not works
so i need mannualy checked the checkbox in the word to set the first page header diffrent with others

---
expect:
Is there an api that could set the setting 'first page different with others" ?

**Comment by waveheart** [comment]
![image](https://user-images.githubusercontent.com/25602259/73456574-14777e00-43ad-11ea-9070-2eac720a03a7.png)

**Comment by weshi** [comment]
Unfortunately, there isn't such an API to set it for the time being.

**Comment by lindalu-MSFT** [comment]
If you're still interested in adding this feature, please go to our new [Ideas forum](https://aka.ms/m365dev-suggestions) and click **Submit an Idea**. If there's enough interest (votes), we will follow up with you there and add it to our feature request backlog. Thanks, lindalu
