### ISSUE TITLE
Share state between custom function and task pane code through sharedState variable.

### ISSUE THREAD

**Issue by topkoong** [OfficeDev/office-js#957]
I am able to share state between custom function and task pane through sharedState variable if custom function and task pane share the same domain.

However, I was wondering if I could share state between custom function and task pane having different subdomains or ports through sharedState variable. If so, it would be greatly appreciated if you could clarify this on the documentation like the OfficeRuntime.storage object documentation.

Thank you for your time and consideration.

**Comment by RuoyingLiang** [comment]
Shared Runtime should support this scenario  [https://docs.microsoft.com/en-us/office/dev/add-ins/develop/configure-your-add-in-to-use-a-shared-runtime](url)
