### ISSUE TITLE
Would it be possible to change/disable the ribbon (Add-in commands icon/image for the button) after invoking any functions?

### ISSUE THREAD

**Issue by topkoong** [OfficeDev/office-js#958]
I would like to change/disable the icon/image for the button after a successful login. So, I was wondering if you could let me know if it is possible to do so.

Thank you for your time and consideration.

**Comment by JuaneloJuanelo** [comment]
Hello! thanks for your question. Short answer:  No, this is not possible today, 
Larger answer: but we are planning on adding relatively soon the capability of enable/disable ribbon buttons!! stay tuned!


I recommend you to get to our uservoice channel and upvote this is an existing request. https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/19026019-programmatically-disable-hide-the-ribbon-menu

**Comment by topkoong** [comment]
@JuaneloJuanelo  Thank you for the information! Greatly appreciated!

**Comment by bdentino** [comment]
@JuaneloJuanelo The link provided has been in the 'Started' state without updates for over 2 years. Is there a GitHub issue I could subscribe to to be notified of progress on this feature?
