### ISSUE TITLE
Office Dialog API on Desktop PC not posting messages to parent

### ISSUE THREAD

**Issue by david-on-github** [OfficeDev/office-js#959]
Having an issue in Excel, Word on Desktop for PC, where opening a dialog to an external allowed domain, and redirecting back to the domain of the task pane, the ability to post messages to parent doesn't work. 

If the dialog is first opened to the same origin as the task pane, and then redirected to an external domain, then back to same origin domain, posting messages works.

## Expected Behavior
I expect dialog api to recieve a DialogMessageReceived event after a redirect from external domain.
## Current Behavior
No event fired inside the DialogMessageReceived event.

## Steps to Reproduce, or Live Example
Here are links to relevant code:
https://gist.github.com/david-on-github/94a744b51bae36a2750d7a483d032047
Also deployed to:
https://office-js-dialog.netlify.com
https://office-js-dialog-alternate.netlify.com

## Context
Unable to perform external authentication.

## Your Environment
* Platform: PC desktop
* Host: Word
* Office version number: 16.0.12325.20280
* Operating System: Windows 10 Pro N | Version: 1903 | OS Build: 18362.592

**Comment by JuaneloJuanelo** [comment]
@david-on-github thanks so much for the detailed description, code, samples, etc. I was able to repro this issue, its seems to be a bug. We'll investigate further with bug 3928090.
Can you please clarify what version of Windows you are using?

**Comment by JuaneloJuanelo** [comment]
we need the windows version please, hence the needs author flag

**Comment by david-on-github** [comment]
> we need the windows version please, hence the needs author flag

@JuaneloJuanelo Thanks for looking, 
Updated OS.

**Comment by JuaneloJuanelo** [comment]
@david-on-github : i think the behavior you are experiencing is by design, that's a security restriction we added to the dialog. please check the remarks on the documentation https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins#send-information-from-the-dialog-box-to-the-host-page

is this a regression that you are experiencing?

**Comment by david-on-github** [comment]
@JuaneloJuanelo 
Oh okay thanks, I didn't realize this was changed. 

I primarily work with Office for Mac and Office Online, and those platforms still receive the messages even if the dialog is not first opened to a task pane domain.

**Comment by lliu113** [comment]
@david-on-github  - thanks for reporting this! We are following up internally, the behaviour should be as described in the documentation. For auth scenarios, we recommend the latter code pattern you described in your original post - first opening to the same domain as the taskpane, redirecting to your external domain, then redirecting back to message the parent taskpane. 

Does this pattern work for your user scenario?

**Comment by david-on-github** [comment]
@lliu113 
Yup I can make that work. Thanks
