### ISSUE TITLE
Edge DevTools debugger hanging on Reload and it is not loading 

### ISSUE THREAD

**Issue by ragavanrajan** [OfficeDev/office-js#960]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
When you reload the taskpane add-in, Add-in should reload and appear. 

## Current Behavior

When I reload the Project TaskPane Add-in, It doesnt reload, instead it just hang and do nothing. 

## Steps to Reproduce, or Live Example

* Link to live example: 

![EdgeHanging](https://user-images.githubusercontent.com/6369107/73490683-e24c3780-4411-11ea-9d28-d0a5c6286709.gif)

## Additional: Also getting error in console  which is cryptic 

![image](https://user-images.githubusercontent.com/6369107/73490903-5ab2f880-4412-11ea-82fa-3ea7ab8d7193.png)

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: _PC/ Laptop (Windows 10)
* Host [Excel, Word, PowerPoint, etc.]: Project
* Office version number:Version 192 ( Build 12325.20344- Monthly channel) 
* Operating System: Windows 10 ( Build 18363.628, Version 1909) 
* Browser (if using Office Online):Edge 
![image](https://user-images.githubusercontent.com/6369107/73490475-808bcd80-4411-11ea-8f1f-097e891ab263.png)

## Useful logs

- [x ] Screenshots

Kindly fix this bug.

**Comment by ragavanrajan** [comment]
Dear Microsoft, Any update on this please.

**Comment by nnyegaard** [comment]
@ragavanrajan How did you get the Edge console to appear? I have been appending to a div to see logs
