### ISSUE TITLE
Would it be possible to dynamically/programmatically close/hide the task pane from Ribbon/custom functions/ other stuff (in PREVIEW version)?

### ISSUE THREAD

**Issue by topkoong** [OfficeDev/office-js#961]
I have configured my manifest to be able to share data and events between Excel custom functions and the taskpane utlizing window.shareState (available only in Preview). 

Also, I have used the autoopen feature to specify the task pane to open automatically, and it works perfectly fine. Then, I have called onCalculated to actively listen to an event to identify which cells in the worksheet are calculated. After that, I would like to find a way to programatically/dynamically close the task pane, and the custom functions can still work. 

I was wondering if you guys could let me know if it is possible to programmatically close/hide the task pane from Ribbon/custom functions/ other stuff. If so, could you please provide me the information?

Right now, I have to close the task pane on my own, and the custom functions can still work.

Thank you for your time and consideration!

**Comment by lliu113** [comment]
@topkoong - thanks for your question! We are currently working on an API which allows you to dynamically open/close the taskpane associated with your shared runtime. This should be ready to preview over the next few months, will update this thread once it becomes available. 

Thanks!

**Comment by corytheboyd** [comment]
@lliu113 We're very interested in programmatic control over the Taskpane, is there a ticket I can subscribe to somewhere to stay up to date on progress?

**Comment by lliu113** [comment]
@corytheboyd - sorry for the very belated response to this. If you're still interested in the close/hide taskpane feature this is now in GA. You can find more information about it here - https://docs.microsoft.com/en-us/office/dev/add-ins/develop/show-hide-add-in.

I'm going to go ahead and close this issue, please free feel to reactivate if you have any additional question. Thanks!
