### ISSUE TITLE
How to open angular component as confirmation dialog box while user moving to another cell in excel .

### ISSUE THREAD

**Issue by ravitejagGitHub** [OfficeDev/office-js#962]
I would like to open angular component as Confirmation dialogue box (Yes/No options) in center of excel sheet while user moving to new cell. 

Is there any example in dialogue box api to achieve this functionality? and is it recommended?
https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins

**Comment by lliu113** [comment]
@ravitejagGitHub - thanks for your question! You can include angular components as part of the webpage in the dialog box, but the frame itself cannot be an angular component.

**Comment by ravitejagGitHub** [comment]
Thanks you.
