### ISSUE TITLE
All entities are null

### ISSUE THREAD

**Issue by surjyams** [OfficeDev/office-js#963]
Hello,
I followed the sample code that is shared at: https://docs.microsoft.com/en-us/outlook/add-ins/extract-entity-strings-from-an-item#extracting-task-suggestions. I have an email, that has a valid address (1234 Main Street, Redmond, WA 07722). But all the entities on the email are null, including the 'Addresses' entity. 

> Return value for Office.context.mailbox.item.getEntities():  

`{ "_data$p$0": { "Addresses": null, "Contacts": null, "EmailAddresses": null, "MeetingSuggestions": null, "PhoneNumbers": null, "TaskSuggestions": null, "Urls": null }, "_filteredData$p$0": {}, "_dateTimeSent$p$0": "2019-11-15T12:01:19.000Z", "_permissionLevel$p$0": 2, "_addresses$p$0": [] }`

Any help to get it to work will be greatly appreciated.

Regards
~Surjya.

**Comment by exextoc** [comment]
Internal tracking id: OutlookWeb:64166
