### ISSUE TITLE
Outlook for Mac, setSelectedDataAsync, font-size problem

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#965]
In an Outlook add-in for compose mode, we are using the setSelectedDataAsync method to insert HTML text into the email body. In Outlook for Mac, the default font size is set to 11pt (please see the screenshot attached). The setSelectedDataAsync method does not allow inserting HTML text with the default font size.

## Expected Behavior
The setSelectedDataAsync method shall insert HTML text with the specified font size or the default font size (if the font-size property is not specified).

## Current Behavior
The setSelectedDataAsync method inserts HTML text with font size === 12pt. 

## Steps to Reproduce, or Live Example
Please see the test code below:
`Office.context.mailbox.item.body.setSelectedDataAsync(‘We appreciate the time you have spent on this issue’, { coercionType: Office.CoercionType.Html }, (asyncResult) => {
});`

`Office.context.mailbox.item.body.setSelectedDataAsync(‘<p>We appreciate the time you have spent on this issue</p>’, { coercionType: Office.CoercionType.Html }, (asyncResult) => {
});`

`Office.context.mailbox.item.body.setSelectedDataAsync(‘<span style=”font-size:11pt”>We appreciate the time you have spent on this issue</span>’, { coercionType: Office.CoercionType.Html }, (asyncResult) => {
});`

`Office.context.mailbox.item.body.setSelectedDataAsync(‘<p><span style=”font-size:11pt”>We appreciate the time you have spent on this issue</span></p>’, { coercionType: Office.CoercionType.Html }, (asyncResult) => {
});`

The four code samples above do the same thing, the difference is in HTML tags and styles. All the code samples insert paragraphs with font size = 12pt, please see the screenshot attached.

* Additional details:
  1. Only Outlook for Mac is affected. Everything works fine in Outlook Online and Outlook 2016 & 2019.

## Your Environment
* Platform: Mac
* Host: Outlook for Mac
* Office version number: 16.33 (20011301)

* Operating System: ______
* Browser (if using Office Online): ______

## Useful logs
- [ ] Screenshots
<img width="586" alt="OutlookForMac-Settings" src="https://user-images.githubusercontent.com/28924916/73670014-8b688b80-46b9-11ea-8956-e2215e01239a.png">
<img width="469" alt="OutlookForMac-Inspector" src="https://user-images.githubusercontent.com/28924916/73670042-96bbb700-46b9-11ea-8557-91c097eaa136.png">

**Comment by exextoc** [comment]
Hi, thank you for reporting this bug regarding the default font size on Outlook Mac. We are able to reproduce this issue, and it has been put in our backlog. Unfortunately, we do not have any timelines to share at this point.
