### ISSUE TITLE
"supportSharedFolders" doesn't work on Outlook 2016 one-time purchase

### ISSUE THREAD

**Issue by jesyxue** [OfficeDev/office-js#967]
I am working on outlook web add-in. And I have added "supportSharedFolders" element to my manifest.xml. But on some Outlook client version, open the delegated calendar still cannot see my add-in button. My outlook version is Outlook 2016 one-time purchase, 16.0.4266.1001 (64 bit), open the delegated calendar by other person, cannot see my add-in button.

As the document's description, to use "supportSharedFolders" Outlook need support 1.8. 
My question is how to support this feature for Office 365 subscription users. Do you prepare to support Outlook 2016, 2019 one-time purchase users? 
Many customers report this issue, they said that cannot use outlook web add-in on other's calendar who give delegated privilege.

The related document
https://docs.microsoft.com/en-us/office/dev/add-ins/reference/manifest/supportssharedfolders

https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/outlook-api-requirement-sets#requirement-sets-supported-by-exchange-servers-and-outlook-clients

**Comment by JuaneloJuanelo** [comment]
Thanks for your question. Yes, that's as expected. We did not backported the 1.8 functionality to MSI builds you referred. You will need builds 16.0.12130.20272+ to support 1.8, including shared folders. We are updating the referred pages to reflect the builds where the requirement set is supported.
