### ISSUE TITLE
Outlook Add-in is not working on Android 9 and Android 10

### ISSUE THREAD

**Issue by ntranvinh** [OfficeDev/office-js#968]
I am developing Outlook add-in using add-in command to execute a function.
The test version of the add-in will open dialog then user can choose to click OK or cancel then another dialog will appear and user can click OK to complete the action.
The add-in works well on iOS and web, but not on Android

## Expected Behavior
I expected the add-in can work on web, iOS, Android

1. The add-in will show notification " is working on your request"
2. The add-in then show notification "step 1"
3. The add-in then open a dialog allow user to click button to send message back to parent and the dialog is closed
4. The notification show "step 2"
5. The dialog will appear and allow user to click button to send message back to parent and the dialog is closed
6. Action complete

## Current Behavior
The add-in works very well on web and iOS. But when it comes to Android, the problem appears:

- Sometimes the add-in stops working, the only notification message appears is " is working on your request" and it spinning forever.
- Sometimes the add-in successfully opens the dialog but I click many times to the button on the dialog and nothing happened, no error showing up, it just stays there. Need to press X to close the dialog.
- Sometimes the add-in can stop at any step.
- Sometimes the add-in does successfully the expected steps.

## Steps to Reproduce, or Live Example

* Link to live example: ______
https://github.com/ntranvinh/AndroidOutlookAddinSample

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Android
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: the latest version of Outlook for Android on 2020-04-02
* Operating System: Android version 9 and Android version 10
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
Thanks for reporting this bug. We are able to reproduce this issue on Android. We have added it to our backlog. However, we don't have any timelines to share at this point.
