### ISSUE TITLE
[outlook add-in]Can we get more info about recurring meeting

### ISSUE THREAD

**Issue by SWei1234** [OfficeDev/office-js#969]
I consult the microsoft add-in Doc. Only get this recurring meeting info. But when I edit this event or all events in this series I can't see any different. 
As a result, A user can different what they are editing but as an add-in can't.

## Expected Behavior
I wonder is there a api for add-in to different what they are editing an event or entire series.
I see outlook have notification to let me know what I am editing so I think add-in should get these info.

## Current Behavior
call Office.context.mailbox.item.recurrence.getAsync

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: All
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 2016&2019&Online
* Operating System: windows 10
* Browser (if using Office Online): chrome

**Comment by exextoc** [comment]
Hi, just to clarify, are you looking for a way for the add-in to differentiate if the current event is part of a series or a single occurrence?

**Comment by SWei1234** [comment]
@exextoc yes.

**Comment by exextoc** [comment]
As described [here](https://docs.microsoft.com/en-us/javascript/api/outlook/office.recurrenceproperties?view=outlook-js-preview), you can use the recurrence API to check if the current meeting is a one-time event or part of a series:

```
Office.context.mailbox.item.recurrence.getAsync(callback);

function callback(asyncResult) {
    var context = asyncResult.context;
    var recurrence = asyncResult.value;
    if (!recurrence) {
        console.log("One-time appointment or meeting");
    } else {
        console.log("Recurrence");
    }
}
```

Can you confirm that this is what you needed?

**Comment by SWei1234** [comment]
@exextoc No, I am not mean different the one-time appointment and recurrence.
I mean how to different the type of recurrence. like 'this event' or 'all events in this series'
For example:
![image](https://user-images.githubusercontent.com/15980696/73996655-2356c580-4997-11ea-8be6-71552439c5a0.png)
Do add-in have api to different this three option?

**Comment by exextoc** [comment]
@SWei1234 Currently this feature is not available via office JS APIs. Add-in can edit the view which is opened by the user. If user has opened series view it will update series else it will update the event. We track Outlook add-in feature requests on our [user-voice page](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins). Please add your request there. Feature requests on user-voice are considered, when we go through our planning process.

**Comment by SWei1234** [comment]
Okay, I know. Thanks for your support.
