### ISSUE TITLE
Outlook for Mac, addFileAttachmentFromBase64Async, An internal error has occurred.

### ISSUE THREAD

**Issue by DmitryKostochko** [OfficeDev/office-js#970]
In an Outlook add-in for compose mode, we are using the addFileAttachmentFromBase64Async method to add attachments. In Outlook for Mac, the "Internal Error" occurs if attachmentName contains space characters.

## Expected Behavior
The Internal Error should not occur.

## Current Behavior
The following error occurs:
OSF.DDA.Error
name: "Internal Error"
message: "An internal error has occurred."
code: undefined

## Steps to Reproduce, or Live Example
Please use the following code to reproduce the issue:
`const options2: Office.AsyncContextOptions & { isInline: boolean } = {
    isInline: false
};
Office.context.mailbox.item.addFileAttachmentFromBase64Async('MQ==', 'test 1.txt', options2, (result: Office.AsyncResult<string>) => {});`

## Your Environment
* Platform: Mac
* Host: Outlook for Mac
* Office version number: 16.33 (20011301)
* Operating System: ______
* Browser (if using Office Online): ______

**Comment by exextoc** [comment]
Thank you for reporting this bug. We are able to reproduce this issue on Mac, and have added it to our backlog. However, we do not have any timelines to share at this point.
