### ISSUE TITLE
How to give custom title for dialog box with option displayInIframe: true

### ISSUE THREAD

**Issue by ravitejagGitHub** [OfficeDev/office-js#971]
I'm opening dialog box with displayInIframe option true.

Is it possible to give custom title to dialog window instead of default title (Message from Add-in: )?

<img width="415" alt="Annotation 2020-02-06 184206" src="https://user-images.githubusercontent.com/20149862/73940355-522a5880-4911-11ea-927c-6860550c1f75.png">

**Comment by lliu113** [comment]
@ravitejagGitHub - thanks for your question. For security reasons, we do not currently allow customizable dialog titles. 

If this is a key customer scenario for you, you can vote for the feature on UserVoice here - https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/33035422-allow-to-customize-the-pop-up-dialogue-title-when

Thanks!
Lillian
