### ISSUE TITLE
ItemChanged event is not triggered on system emails

### ISSUE THREAD

**Issue by modestfake** [OfficeDev/office-js#974]
By _system email_ I mean the email which I get when email delivery has failed:
![image](https://user-images.githubusercontent.com/16977959/74167631-3389d180-4c31-11ea-85fb-841ce36654c6.png)

## Expected Behavior
ItemChanged should be triggered when I navigate to system email

## Current Behavior
When I open a system email with pinned taskpane, I don't get ItemChanged event

## Steps to Reproduce, or Live Example
1. Try to send email to some invalid email and get system email ("Delivery has failed to these recipients or groups...").
2. Subscribe to `ItemChanged` and add some `console.log('Item changed!')` statement to see when this event gets triggered.
3. Open another email you've received, open taskpane and pin it.
4. Navigate to any other email and you'll see that event gets triggered.
5. Navigate to system email and you'll see that there's nothing in the console.

## Context
Any of Outlook API (getting user identity token or retrieving email body) doesn't work on system emails. We don't know that the item has changed and at some point try to retrieve email body or user's identity token and it fails. To prevent this we at least need to know when the item changed, so we can detect if this is a valid item or not.

## Your Environment

* Platform: Office Online
* Host: Outlook
* Office version number: 16.0.10908.10000
* Operating System: Mac OS
* Browser: Chrome

**Comment by exextoc** [comment]
We are able to repro this issue on our end for Outlook web client. Thanks for reporting this issue. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: OutlookWeb:77951

**Comment by exextoc** [comment]
Currently there is no support for addins from system generated emails We track Outlook add-in feature requests on our [Tech Community Page](http://aka.ms/M365dev-suggestions). Please submit your request there and choose the appropriate label(s). Feature requests on Tech Community are considered, when we go through our planning process.
