### ISSUE TITLE
Custom Property not set

### ISSUE THREAD

**Issue by soorajhealthplotter** [OfficeDev/office-js#975]
## Expected Behavior
I have got Excel Add-in. Here for adding a workbook id i use to create a custom property and add it to workbook. For Office Online, Excel 2019 and for Excel on all of my clients system works fine except one client.
The Office version client using is  **Windows 10  MSFT Office Professional Plus 2016 64 bit**

## Current Behavior

When the add-in loads in i check for a custom property. If the custom property is not there it throws a error and in catch block i make call to create custom property function. But the custom property always seems not be set for this particular client.
 
When i am trying to add or read the custom property i believe an error is occuring.

## Code to create a Custom Property
Excel.run((context) ->
customDocProperties = context.workbook.properties.custom
work_book = context.workbook
d = $scope.generateUUID()
customDocProperties.add("workbook_identifier", d)
customProperty = customDocProperties.getItem('workbook_identifier')
customProperty.load 'key, value'
work_book.load 'name'
work_sheet = context.workbook.worksheets.getActiveWorksheet()
work_sheet.load 'id'
work_sheet.load 'name'
context.sync().then ->
$scope.workbook = customProperty.value
$scope.worksheet_id = work_sheet.id
$scope.workbook_name = work_book.name
$scope.worksheet_name = work_sheet.name
return
).catch (error) ->
console.log 'Error: ' + error

## Code to read a custom property
Excel.run((context) ->
work_book = context.workbook
customDocProperties = context.workbook.properties.custom
customProperty = customDocProperties.getItem('workbook_identifier')
customProperty.load 'key, value'
work_sheet = context.workbook.worksheets.getActiveWorksheet()
work_sheet.load 'id'
work_sheet.load 'name'
work_book.load 'name'
context.sync().then ->
$scope.workbook = customProperty.value
$scope.worksheet_id = work_sheet.id
$scope.workbook_name = work_book.name
$scope.worksheet_name = work_sheet.name
return
).catch (error) ->
console.log("------------error- call function for creating custom property------")
call the function for creating a custom property

## Your Environment
Windows 10 64 bit
MSFT Office Professional Plus 2016 64 bit(Microsoft@Excel@2016(16.0.4954.1000) MSO (16.0.4939.1000) 64-bit)
IE 11 (Version 11.3442.14393.0, although IE hasn’t had any issues).

**Comment by lumine2008** [comment]
Hi @soorajhealthplotter 
I notice that the code you share is as same as https://github.com/OfficeDev/office-js/issues/973?
have you saved the workbook?

**Comment by soorajhealthplotter** [comment]
Now saving the document is not the issue.that is done manually.but creating the custom properties only in this particular version is problem

**Comment by lumine2008** [comment]
seems i am not be able to repro this issue, could you please share me the gist and repro steps?

**Comment by soorajhealthplotter** [comment]
Hi i have noticed my system has some internal issue.i installed on another system and checked.now working fine

Thank you
