### ISSUE TITLE
Adding table to worksheet

### ISSUE THREAD

**Issue by iksinski** [OfficeDev/office-js#976]
I want to build a function to download data from an external service and insert it as a table to the worksheet. I started using some example found in the docs, but after a few changes it started working very inconsistent. From time to time, inserting headers values throws an "InvalidArgument" error.

```js
Excel.run(async context => {
    const sheet = context.workbook.worksheets.getActiveWorksheet();
    const range = context.workbook.getSelectedRange();
    console.log(1);
    const header = ['Date', 'Merchant', 'Category', 'Amount'];
    const tableHeaderRange = range.getColumnsBefore(-header.length);
    console.log(2);
    const expensesTable = sheet.tables.add(tableHeaderRange, true);
    expensesTable.name = generateString();
    console.log(3);
    expensesTable.getHeaderRowRange().values = [header];

    await context.sync();
    console.log(4);
    expensesTable.rows.add(null, [
      ['1/1/2017', 'The Phone Company', 'Communications', '$120'],
      ['1/2/2017', 'Northwind Electric Cars', 'Transportation', '$142'],
      ['1/5/2017', 'Best For You Organics Company', 'Groceries', '$27'],
      ['1/10/2017', 'Coho Vineyard', 'Restaurant', '$33'],
      ['1/11/2017', 'Bellows College', 'Education', '$350'],
      ['1/15/2017', 'Trey Research', 'Other', '$135'],
      ['1/15/2017', 'Best For You Organics Company', 'Groceries', '$97'],
    ]);
    console.log(5);

    if (Office.context.requirements.isSetSupported('ExcelApi', '1.2')) {
      sheet.getUsedRange().format.autofitColumns();
      sheet.getUsedRange().format.autofitRows();
    }
    console.log(6);

    sheet.activate();
    console.log(7);

    return context.sync();
  }).catch(errorHandlerFunction);
```

So for some reason it stops after `console.log(3)` from time to time. What I'm planning to achieve here is replace fixed header and rows data with data fetched from the service - that's only an example function.

`tableHeaderRange` is a hacky way to insert the table starting from the selected cell. I've tried to change that and no matter if it's arrays' length or a constant integer - error is still happening.

I'm using Excel 16.27 for Mac, but it also happens on Windows - Excel 2016 MSO(16.0.12430.20172) 64bit.

**Comment by lumine2008** [comment]
Hello, could you please share what's the definition for generateString()?
`    expensesTable.name = generateString();`
I made a change to this line, it works for me.
`  expensesTable.name = "test" + Math.random();`

Here is the gist I created for you based on your sample code
https://gist.github.com/lumine2008/a7cddead512bb35f1f73f54343b8dc35

**Comment by iksinski** [comment]
Hi @lumine2008, thanks for your answer!

It's pretty similar to what you did:

```js
const generateString = () => {
  return Math.random()
    .toString(36)
    .substring(7);
};
```

I've checked and this fails even when strings are unique.

**Comment by lumine2008** [comment]
have you tried my gist that I created for you based on your sample code, it works in my side
https://gist.github.com/lumine2008/a7cddead512bb35f1f73f54343b8dc35

**Comment by lucetius** [comment]
Hi, @lumine2008 
I'm working on this issue with @iksinski and attached gist file is not working.
In you're example you're only changing background of the cell but not inserting a new table.
Try to change `run` function content to proper one and try again.
You can start testing by adding function on cells: F20 and G11

**Comment by lumine2008** [comment]
Thanks @lucetius for your reply, I am not sure if I get it. For my gist, it could run successfully. would you mind to change my gist and share the updated gist back to me, therefore I can repro the issue.
![image](https://user-images.githubusercontent.com/26398035/74943896-1a9ece80-5430-11ea-9b7c-bda3e9e44792.png)
