### ISSUE TITLE
Unable to save draft from context of pinned taskpane after switching to a different draft

### ISSUE THREAD

**Issue by corytheboyd** [OfficeDev/office-js#979]
## Expected Behavior
The Outlook.js API call to save the draft should not fail when I try to call it from a pinned compose taskpane.

## Current Behavior

If you have already pinned the compose taskpane from a previous message compose, when you click reply on a message from your inbox again, the call to `Office.context.mailbox.item.saveAsync` will yield the following error:

| Code | Name | Message|
| --- | --- | --- |
| 9021 | SaveError | Connection error occurred while trying to save the item on the server. |

If you close the pinned taskpane and open it again, the API call will succeed as expected.

## Steps to Reproduce, or Live Example

1. Ensure that you have Cached Exchange Mode enabled for your Outlook client
1. Go to your inbox
1. Click Reply on a message (inline, not pop-out)
1. Open the add-in Taskpane and pin it
1. Click Delete on this Draft to close it
1, Click reply on 
1. Attach an Edge debugger to the taskpane context
1. Directly invoke `Office.context.mailbox.item.saveAsync`
1. See the error

## Context

This affects the email send functionality of our product. We rely on `Office.context.mailbox.item.saveAsync` to yield the draft ID, which is sent to our server and later used to invoke the [`send` Graph API function](https://docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&tabs=http).

We would like our add-in's send functionality to reliably work using the pinned compose taskpane and inline reply (instead of a pop-out), as that will be one of the most widely used contexts for our email send functionality.

We would prefer not to hack around this issue ourselves if the root cause can be identified and fixed.

### Note

This is with Cached Exchange Mode enabled. We have to support this feature of the PC Desktop client as our customers depend on it.

## Your Environment

* Platform: **PC desktop**
* Host: **Outlook**
* Outlook version number: **Microsoft Outlook for Office 365 MSO (16.0.12430.20112) 32-bit**
* Operating System: **Windows 10 Home**
* Browser (if using Office Online): **N/A**

## Useful logs

Screenshot with error:

![9021_error_message](https://user-images.githubusercontent.com/692632/74288492-5e336300-4ce1-11ea-927f-a5dd395f6522.PNG)

Recording:

![2020-02-11 15 22 46](https://user-images.githubusercontent.com/692632/74288911-94251700-4ce2-11ea-8511-735cf14d7165.gif)

Manifest source URL: https://addin.grooveapp.com/manifest.xml

**Comment by exextoc** [comment]
@corytheboyd One reason why this can happen is if your add-in does not register for the [ItemChanged event](https://docs.microsoft.com/en-us/outlook/add-ins/pinnable-taskpane). Can you add support for that to your add-in (if you haven't already) and see if that resolves this issue? If your add-in doesn't support this event, the `Office.context.mailbox.item` object in the add-in becomes stale, resulting in the error you are experiencing.

**Comment by corytheboyd** [comment]
Thanks for the quick response! We should have an `itemChanged` listener already registered, but I will inspect that configuration now to look for any issues.

**Comment by exextoc** [comment]
Thanks @corytheboyd. Let us know what you find.

**Comment by corytheboyd** [comment]
@exextoc After peeling back 100% of our application code and just exercising `itemChanged` event handling logic I am confirming that I no longer see this behavior, so yay there is no issue here! Thanks for checking in to help quickly resolve this.

**Comment by exextoc** [comment]
Thanks for the update @corytheboyd Closing this issue.
