### ISSUE TITLE
Office.context.document.getFileAsync  fails when renaming in Excel Online

### ISSUE THREAD

**Issue by nanan14** [OfficeDev/office-js#98]
when I rename the workbook in Excel Online, Office.context.document.getFileAsync fails. this does not happen in Word and Powerpoint Online

## Expected Behavior
getFileAsync should return successful and able to retrieve the content

## Current Behavior
returns an error "A network problem has prevented retrieval of the file"

## Steps to Reproduce, or Live Example
1.  open new workbook in Excel online
2. rename the workbook by clicking its title ex. booktest
3.  call getFileAsync 

## Context
Currently I'm implementing a plugin that gets the content of the document  by using  Office.context.document.getFileAsync so far there was no Issue on Word and PowerPoint but I encounter and Issue on Excel Online. Once I have renamed the document(workbook)  and call the Office.context.document.getFileAsync it returns an error "A network problem has prevented retrieval of the file" and I failed to get the content. I've tried refreshing the page and the Issue was gone but this always happens when you rename in Excel Online.   

And I have also done more investigation in seems there was an error in Excel Online when you rename the workbook

## Your Environment
* Platform [PC desktop, Mac, iOS, Office Online]:  Office Online
* Host [Excel, Word, PowerPoint, etc.]:  Excel
* Operating System: Windows
* Browser (if using Office Online):  Firefox, chrome

**Comment by XiangGaoMSFT** [comment]
Thanks for reporting this issue.
I can repro it with code below. We're looking into it.

```js
Office.context.document.getFileAsync(Office.FileType.Compressed, { sliceSize: 65536 /*64 KB*/ }, 
        function (result) {
        console.log("callback start");

        if (result.status == "succeeded") {
            var myFile = result.value;
            var sliceCount = myFile.sliceCount;
            console.log("File size:" + myFile.size + " #Slices: " + sliceCount);
            myFile.closeAsync();
        }
        else {
            console.log("Error:", result.error.message);
        }

        console.log("callback end");
});
```

**Comment by nanan14** [comment]
Thank you. do you know if there are any work around for this issue?

**Comment by XiangGaoMSFT** [comment]
A work around is appending file extension when you rename the workbook.
For example, when you want to rename a file to `filename`, rename it to `filename.xlsx` instead. But the problem is, the final filename will be `filename.xlsx.xlsx`

The bad news is currently this work around can't be achieved without involving user's manual operation. So from code side, maybe you can just detect this issue and show a warning message.

**Comment by JuaneloJuanelo** [comment]
@nanan14  this issue is now fix, thanks so much for helping make our platform better. 
thanks!

**Comment by nanan14** [comment]
Hi @JuaneloJuanelo , thank you I verified it and its fixed now. thank you for your quick response.
