### ISSUE TITLE
Compatibility between Toggling 'Up/Down' arrows in Inspector View and Pinnable Taskpane

### ISSUE THREAD

**Issue by Byron-Mo** [OfficeDev/office-js#981]
The Outlook Addin has inconsistent behavior when it is pinned in Inspector View while the user interacts the 'up' and 'down' arrows to toggle through emails in Read Mode. Additionally, as the user toggle through emails in the Inspector View, the Explorer View also updates with the respective email. Because the addin is pinned, it also loads up in Explorer View and we observed a delay in the getItem call. 

## Expected Behavior
In the Outlook Addin, both the Inspector and Explorer views should load getItem context without error

## Current Behavior
1. In the Outlook Addin, the Explorer View often times has a delay when attempting to getItem
2. The pinned Addin in the Inspector View sometimes sometimes does not remain pinned on email toggle

## Steps to Reproduce, or Live Example
1. Open Outlook Addin and pin it to Explorer View
2. Double click on any email in the Inbox Folder to open up Inspector View
3. Observe the Addin open in the Inspector View
4. Use the 'Up/Down" arrows to switch to another email and observe Addin behavior in both Explorer and Inspector Views.

Inspector View up/down arrows
![updownarrows](https://user-images.githubusercontent.com/14811552/74385549-a8334c00-4da8-11ea-884b-c097172a61d7.jpeg)

Failed getItem call in Explorer View
![explorerview](https://user-images.githubusercontent.com/14811552/74385557-abc6d300-4da8-11ea-8a45-aed5052bda4d.jpeg)

## Context
- Arose from a customer investigation

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Outlook Desktop on Windows

**Comment by exextoc** [comment]
Thanks for reporting this issue. It has been placed on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: Office:3954414

**Comment by exextoc** [comment]
This should be fixed in builds 16.0.13110.10000 and later.
