### ISSUE TITLE
Edge WebView: Outlook crashes when starting any add-in

### ISSUE THREAD

**Issue by tobiasviehweger** [OfficeDev/office-js#982]
We have a customer, where ~25% of their users are seeing Outlook crashes when starting ANY office add-in. Edge WebView seems to be crashing on startup.

## Expected Behavior
Do not crash.

## Current Behavior
Clicking on any action of an Office add-in crashes Outlook for the customer, this is happening with our add-in, as well as every other one (e.g. OneNote). The sidebar still opens and a spinner is coming up, afterwards Outlook restarts.

## Steps to Reproduce, or Live Example
Cannot reproduce on our machines

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC 
* Host [Excel, Word, PowerPoint, etc.]: Outlook 
* Office version number: 1809 11929.20606
* Operating System: Windows 10 1903 18362.592
* Edge: 44.18362449.0

## Logs

> Lokinimi:      Application
> Lähde:         Application Error
> Päivä:         13.2.2020 15.33.41
> Tapahtumatunnus:1000
> Tehtäväluokka: (100)
> Taso:          Virhe
> Avainsanat:    Perinteinen
> Käyttäjä:       - 
> Kuvaus:
> Viallisen sovelluksen nimi: wwahost.exe, versio: 10.0.18362.1, aikaleima: 0xd44a1ada
> Viallisen moduulin nimi: EdgeManager.dll, versio: 11.0.18362.418, aikaleima: 0x5bbfcaef
> Poikkeuskoodi: 0xc0000409
> Virhepoikkeama: 0x0000000000047e98
> Viallisen prosessin tunnus: 0x1bec
> Viallisen sovelluksen käynnistysaika: 0x01d5e27234ae3a19
> Viallisen sovelluksen polku: C:\Windows\System32\wwahost.exe
> Viallisen moduulin polku: C:\Windows\System32\EdgeManager.dll
> Raportin tunnus: f5fd790e-2132-482f-9821-d4da3afa8e52
> Viallisen paketin koko nimi: Microsoft.Win32WebViewHost_10.0.18362.449_neutral_neutral_cw5n1h2txyewy
> Viallisen paketin suhteellinen sovellustunnus: DPI.PerMonitorAware
> Tapahtuman Xml:
> <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
>   <System>
>     <Provider Name="Application Error" />
>     <EventID Qualifiers="0">1000</EventID>
>     <Level>2</Level>
>     <Task>100</Task>
>     <Keywords>0x80000000000000</Keywords>
>     <TimeCreated SystemTime="2020-02-13T13:33:41.787358100Z" />
>     <EventRecordID>50364</EventRecordID>
>     <Channel>Application</Channel>
>     <Security />
>   </System>
>   <EventData>
>     <Data>wwahost.exe</Data>
>     <Data>10.0.18362.1</Data>
>     <Data>d44a1ada</Data>
>     <Data>EdgeManager.dll</Data>
>     <Data>11.0.18362.418</Data>
>     <Data>5bbfcaef</Data>
>     <Data>c0000409</Data>
>     <Data>0000000000047e98</Data>
>     <Data>1bec</Data>
>     <Data>01d5e27234ae3a19</Data>
>     <Data>C:\Windows\System32\wwahost.exe</Data>
>     <Data>C:\Windows\System32\EdgeManager.dll</Data>
>     <Data>f5fd790e-2132-482f-9821-d4da3afa8e52</Data>
>     <Data>Microsoft.Win32WebViewHost_10.0.18362.449_neutral_neutral_cw5n1h2txyewy</Data>
>     <Data>DPI.PerMonitorAware</Data>
>   </EventData>
> </Event>

A similar problem (same error location & code) seems to be described here:
https://social.technet.microsoft.com/Forums/en-US/8ec56aee-3c72-4a18-9fab-05a4776e7838/outlook-crashes-when-accessing-365-addins?forum=outlook

> Description:
> Faulting application name: wwahost.exe, version: 10.0.18362.1, time stamp: 0xd44a1ada
> Faulting module name: EdgeManager.dll, version: 11.0.18362.418, time stamp: 0x5bbfcaef
> Exception code: 0xc0000409
> Fault offset: 0x0000000000047e98
> Faulting process id: 0x2e5c
> Faulting application start time: 0x01d5dbbb536c01d8
> Faulting application path: C:\Windows\System32\wwahost.exe
> Faulting module path: C:\Windows\System32\EdgeManager.dll
>

**Comment by KravetsArtem** [comment]
Hi,
We have exactly the same issue in Excel Add-In. It sometimes randomly appears during just starting of Add-In, but if we managed to open add-in we get it whenever iFrame or popup window gets closed.
We are able to reproduce it on our machines so we can provide any logs that can be helpful.

We use: 
Office Professional Plus 2016(Version 2001, Build 12430.20288 Click-to-Run)
Edge 44.18362.449.0
EdgeHTML 18.18363

**Comment by exextoc** [comment]
Is it possible that either of you has captured a dump of the crashing process?

**Comment by tobiasviehweger** [comment]
We have not, but the customer was pretty responsive so we might be able to get one. Would you need a short or a full dump?

**Comment by croicu** [comment]
Thank you,
Alex

**Comment by KravetsArtem** [comment]
Hi,
Here is a link for a dump of a process that creates problems: https://1drv.ms/u/s!ArV6qzJz7_sHamE9HFCdCm3NiZY?e=EcMzAK
If you need anything else I can provide some additional logs that will help you

**Comment by croicu** [comment]
Adding @Ling<mailto:lingz@microsoft.com> and @Liang<mailto:Liang.Zhao@microsoft.com>

Thanks,
Alex

**Comment by croicu** [comment]
The dump shows multiple thread in WWAHost waiting on WaitForPendingGitRegistrations while CoUninitialize. I remember Dave investigated something similar before. Don't know whether he knows more about how this might cause Outlook to crash.

Are there any failure/Watson events in event viewer(eventvwr.exe)?

Liang

From: Alexandru Croicu <alexcro@microsoft.com>
Sent: Thursday, March 5, 2020 10:14 AM
To: OfficeDev/office-js <reply@reply.github.com>; OfficeDev/office-js <office-js@noreply.github.com>; Ling Zhong <lingz@microsoft.com>; Liang Zhao (REDMOND) <Liang.Zhao@microsoft.com>
Cc: Assign <assign@noreply.github.com>
Subject: RE: [OfficeDev/office-js] Edge WebView: Outlook crashes when starting any add-in (#982)

Adding @Ling<mailto:lingz@microsoft.com> and @Liang<mailto:Liang.Zhao@microsoft.com>

Thanks,
Alex

**Comment by ghost** [comment]
This is reproducible on my workstation with the Add-ins for Zoom, KnowBe4, and the Microsoft Spam/Phishing reporting add-in.  Happy to provide dumps, etc. if you give me some basic instructions on how create them.

**Comment by Borgquite** [comment]
Same issue here w/ Windows 10 1909, latest Office 365 build, and the Microsoft FindTime or Asana plugins:

Log Name:      Application
Source:        Application Error
Date:          27/05/2020 11:05:09
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      <redacted>
Description:
Faulting application name: wwahost.exe, version: 10.0.18362.1, time stamp: 0xd44a1ada
Faulting module name: EdgeManager.dll, version: 11.0.18362.693, time stamp: 0xb50be940
Exception code: 0xc0000409
Fault offset: 0x0000000000047e98
Faulting process ID: 0x27d0
Faulting application start time: 0x01d6340e4d8c9b80
Faulting application path: C:\Windows\System32\wwahost.exe
Faulting module path: C:\Windows\System32\EdgeManager.dll
Report ID: 13ebc296-4fe2-4f8d-8746-125740e201fd
Faulting package full name: Microsoft.Win32WebViewHost_10.0.18362.449_neutral_neutral_cw5n1h2txyewy
Faulting package-relative application ID: DPI.PerMonitorAware
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-05-27T10:05:09.148171400Z" />
    <EventRecordID>77917</EventRecordID>
    <Channel>Application</Channel>
    <Computer><redacted></Computer>
    <Security />
  </System>
  <EventData>
    <Data>wwahost.exe</Data>
    <Data>10.0.18362.1</Data>
    <Data>d44a1ada</Data>
    <Data>EdgeManager.dll</Data>
    <Data>11.0.18362.693</Data>
    <Data>b50be940</Data>
    <Data>c0000409</Data>
    <Data>0000000000047e98</Data>
    <Data>27d0</Data>
    <Data>01d6340e4d8c9b80</Data>
    <Data>C:\Windows\System32\wwahost.exe</Data>
    <Data>C:\Windows\System32\EdgeManager.dll</Data>
    <Data>13ebc296-4fe2-4f8d-8746-125740e201fd</Data>
    <Data>Microsoft.Win32WebViewHost_10.0.18362.449_neutral_neutral_cw5n1h2txyewy</Data>
    <Data>DPI.PerMonitorAware</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        Application Error
Date:          27/05/2020 11:05:10
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      <redacted>
Description:
Faulting application name: OUTLOOK.EXE, version: 16.0.12730.20352, time stamp: 0x5ec59603
Faulting module name: EdgeManager.dll, version: 11.0.18362.693, time stamp: 0xb50be940
Exception code: 0xc0000409
Fault offset: 0x0000000000058b41
Faulting process ID: 0x27f4
Faulting application start time: 0x01d6340e3197fb86
Faulting application path: C:\Program Files\Microsoft Office\root\Office16\OUTLOOK.EXE
Faulting module path: C:\Windows\System32\EdgeManager.dll
Report ID: 365986c9-19f8-4809-8e96-936511b79507
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2020-05-27T10:05:10.179345800Z" />
    <EventRecordID>77918</EventRecordID>
    <Channel>Application</Channel>
    <Computer><redacted></Computer>
    <Security />
  </System>
  <EventData>
    <Data>OUTLOOK.EXE</Data>
    <Data>16.0.12730.20352</Data>
    <Data>5ec59603</Data>
    <Data>EdgeManager.dll</Data>
    <Data>11.0.18362.693</Data>
    <Data>b50be940</Data>
    <Data>c0000409</Data>
    <Data>0000000000058b41</Data>
    <Data>27f4</Data>
    <Data>01d6340e3197fb86</Data>
    <Data>C:\Program Files\Microsoft Office\root\Office16\OUTLOOK.EXE</Data>
    <Data>C:\Windows\System32\EdgeManager.dll</Data>
    <Data>365986c9-19f8-4809-8e96-936511b79507</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by Borgquite** [comment]
Have just tried the following to resolve, no luck though:
1) Clearing IE and Edge browser cache, history, cookies etc
2) Recreating Outlook profile
3) Running dism /online /Cleanup-Image /restorehealth
4) Running sfc /scannow

**Comment by Borgquite** [comment]
Fixed for me in the latest Current Channel release (2006 Build 13001.20384)

https://docs.microsoft.com/en-us/officeupdates/current-channel#version-2006-july-14

'Addressed a crash issue with the office host in windows, when an add-in is activated while the registry TabProcGrowth value is REG_SZ type.'

**Comment by smaremanda** [comment]
Thanks for the update.
