### ISSUE TITLE
Office.context.mailbox.item.enhancedLocation.getAsync does not work correctly in OWA 

### ISSUE THREAD

**Issue by mrbfrank** [OfficeDev/office-js#983]
When editing an appointment in OWA if you change the locations in the appointment editor then call `Office.context.mailbox.item.enhancedLocation.getAsync` it returns old locations, & not any new locations added by the user.

## Expected Behavior

`Office.context.mailbox.item.enhancedLocation.getAsync` should return all locations that the user has entered into the appointment editor, not old locations from the previous appointment edit/save. The desktop Outlook clients work like this but OWA does not.

## Current Behavior

Old locations are returned. For instance, if the original saved appointment has no location then you add locations & call `Office.context.mailbox.item.enhancedLocation.getAsync` the returned array is empty. If the original saved appointment has a location named "Contoso" then you delete it, add new locations, & call `Office.context.mailbox.item.enhancedLocation.getAsync` the returned array has still has a single element with the "Contoso" location.

## Steps to Reproduce, or Live Example

* Additional details:
  1. Create a new appointment
  2. Add a location
  3. Save the appointment
  4. Edit the appointment location
  5. Log `Office.context.mailbox.item.enhancedLocation.getAsync` to console
  6. Observe the returned array still contains the old location, not the new edited location

## Context

I need to validate room email addresses as they are edited, & at any time. I know I can subscribe to the `Office.EventType.EnhancedLocationsChanged` event & get location updates (it works properly). However I also need to call `Office.context.mailbox.item.enhancedLocation.getAsync` at various other times & that is not working as expected.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: OWA
* Operating System: MacOS High Sierra
* Browser (if using Office Online): Chrome

## Useful logs

![image](https://user-images.githubusercontent.com/2744313/74488447-d9367e00-4e87-11ea-8662-5e1d9c5472fa.png)

**Comment by exextoc** [comment]
We are able to repro the issue at our end. Thanks for reporting this issue regarding the enhanced location not returned correctly. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: OutlookWeb:59151

**Comment by exextoc** [comment]
We have fixed this bug and the fix should be available in the latest versions.
