### ISSUE TITLE
CoercionType doesn't support Image for Excel web add-in

### ISSUE THREAD

**Issue by ZhengAudrey** [OfficeDev/office-js#984]
For office js API, based on this [link](https://docs.microsoft.com/en-us/javascript/api/office/office.coerciontype), Office.CoercionType.Image should be supported in Excel. But I find Office.CoercionType.Image is undefined in Excel Online. Only Text, Matrix, and Table have values.
[Screenshot](https://i.stack.imgur.com/em6Kp.png)

BTW, it seems that OneNote also supports Office.CoercionType.Image which is not listed in the document.

## Expected Behavior
Office.CoercionType.Image is supported in Excel Online.

## Current Behavior
 Office.CoercionType.Image is undefined in Excel Online.

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Online
* Host [Excel, Word, PowerPoint, etc.]: Excel, OneNote
* Office version number: ______
* Operating System: Windows
* Browser (if using Office Online): Chrome

## Useful logs

- [ ] Console errors
- [x] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by lumine2008** [comment]
Thanks @ZhengAudrey for your post, according to this document: https://docs.microsoft.com/en-us/office/dev/add-ins/reference/requirement-sets/image-coercion-requirement-sets, 
Office.CoercionType.Image is not supported for Excel Online, 

what's your scneario? can you use shape.AddImage?

**Comment by davidchesnut** [comment]
I'm checking to see if our docs need to be updated...

**Comment by lindalu-MSFT** [comment]
@davidchesnut Any update?

**Comment by davidchesnut** [comment]
Looks like the documentation is correct, so I'll close this issue for now.
