### ISSUE TITLE
Office Add-in actions of type ExecuteFunction malfunction with more instances of Office Desktop Apps

### ISSUE THREAD

**Issue by mrqzzz** [OfficeDev/office-js#986]
In an Office Add-in for Word or Excel, where a ribbon button calls an action of type "ExecuteFunction", if you open more that one instance of Word (or of Excel) , the function is always called for the first instance of the app that uses it, regardless which instance calls it after the first time.
Note: the Add-in Host is Mircosoft Edge. Edge Version 80.0.361.51

## Expected Behavior

If i sideload my Add-in in two or more instances of Word (or Excel), in each instance, when i click the ribbon button of my Add-in that calls an "ExecuteFunction", the function is executed in each instance, in its own context.

## Current Behavior

If i sideload my Add-in in two or more instances of Word (or Excel), in each instance, when i click the ribbon button of my Add-in that calls an "ExecuteFunction", the function is always executed in the instance where i clicked the ribbon button the first time.
Instead, it works as expected in the Word and Excel for the web.

## Steps to Reproduce, or Live Example

1) Create a simple React App for an Excel or Word Taskpane Add-in using Yeoman generator for Office.
2) In the _manifest.xml_ file , add a new button, or simply change the existing one, setting the _Action_ like this:
```
<Action xsi:type="ExecuteFunction">
    <FunctionName>myFunction</FunctionName>
    <Label resid="InsertTableButton.Label"/>
</Action>
```

3) In the _commands.html_ file, add this script part:
```
<script>
        (function () {
            Office.initialize = function (reason) {};
        })();

        function myFunction(event) {
            // SET THE CURRENT SELECTION TO A RANDOM NUMBER:
            Office.context.document.setSelectedDataAsync(Math.random(), function () { });         
            event.completed();
        }
</script>
```
4) Start the app (as usual, with _npm install_ and then _npm start_ )
5) Open two (or more) instances of Word
6) Click the Add-in button in the ribbon from Instance1 of Word, you should see a random number in the document body of Word Instance1.
7) Click the Add-in button in the ribbon from Instance2 of Word, you will see the another random number, but in the document body of Instance1 of Word.

Note: in Excel the behaviour is similar but not equal (The selected cell of Instance1 is not updated with a random number, but in Instance2 the cell is not set).

## Context

This is preventing several Add-in functionalities.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]:  **Pc**
* Host [Excel, Word, PowerPoint, etc.]: **Excel App, Word App**
* Office version number:  **Excel for Office 365 MSO (16.0.12325.20280),  Word for Office 365 MSO (16.0.12325.20280)**
* Operating System: **Windows 10 Enterprise v. 1903 build 18362.628**
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by JuaneloJuanelo** [comment]
this is not an issue in Word, adjusting area of ownership.

**Comment by JuaneloJuanelo** [comment]
Actually the team fixed these issue a few months ago, no longer repro, as per team confirmation. 
thanks for reporting.
