### ISSUE TITLE
Office.context.mailbox.displayNewMessageForm doesn't work in outlook 16.35

### ISSUE THREAD

**Issue by zhoukq** [OfficeDev/office-js#987]
Office.context.mailbox.displayNewMessageForm doesn't work in outlook 16.35

## Expected Behavior
run `Office.context.mailbox.displayNewMessageForm({htmlBody: "Platform: Mac<br/>Outlook Version: 16.35<br/> Add-in Version: 11.2.1.9999",subject: "Outlook Add-in Feedback",toRecipients: ["info@xxx.com"]})` with Office.js context should pop up a new email with the corresponding content.

## Current Behavior
this method will return undefine
<img width="1364" alt="Screen Shot 2020-02-14 at 2 20 56 PM" src="https://user-images.githubusercontent.com/5601033/74560787-4eac5800-4f35-11ea-9fd6-f0099bef6082.png">

## Steps to Reproduce, or Live Example
1. open outlook
2. open add-in
3. inspect element
4. run `Office.context.mailbox.displayNewMessageForm({htmlBody: "Platform: Mac<br/>Outlook Version: 16.35<br/> Add-in Version: 11.2.1.9999",subject: "Outlook Add-in Feedback",toRecipients: ["info@xxx.com"]})`

## Context
We just want to use this API to open a new email window and fill in some content automatically, so user can send us some feedback when they use our outlook add-in

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Mac
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 16.35(20021300)
* Operating System: can be reproduced in catalina and mojave
* Browser (if using Office Online): N/A

## Useful logs
N/A

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding Office.context.mailbox.displayNewMessageForm API. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
We have fixed this issue. Thank you for your patience.
