### ISSUE TITLE
Content control in docx document show up as plain text when opening on Word for iPad

### ISSUE THREAD

**Issue by tpasi** [OfficeDev/office-js#988]
When opening on Word for iPad a document that was created using Word for Desktop that contains content controls, these control show up as just text.

In our case the controls are not deleteable, but on the iPad version, the user can just simply delete it

## Expected Behavior

Content control should show up like least like they do on Word for Web 

## Steps to Reproduce, or Live Example

Insert a content control into a word document on the desktop, mark is as "Content Control cannot be deleted" (Developer Tab)

Save and open the same document on Word for iPad.

## Context

Trying to edit a template that has content control that we control from a taskpane add-in.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: iPad
* Host [Excel, Word, PowerPoint, etc.]: Word
* Office version number: ______
* Operating System: iOS

**Comment by JuaneloJuanelo** [comment]
This is actually not an issue with web add-ins but Word for iOS team.
