### ISSUE TITLE
Telemetry service causes 404 error when loading add-in page outside of Office host

### ISSUE THREAD

**Issue by jakobpn** [OfficeDev/office-js#99]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

## Expected Behavior
That the page would load without giving a 404 error 

## Current Behavior
A 404 error is thrown when the add-in page is loaded outside of an Office host:
![image](https://user-images.githubusercontent.com/13109307/39026191-7e22fe0a-4400-11e8-829a-c6607bf79152.png)

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. ______
  2. ______
  3. ______

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outside of Office host
* Office version number: N/A
* Operating System: Windows 10
* Browser (if using Office Online): Chrome

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by ElizabethSamuel-MSFT** [comment]
@mattgeim Is this something you can help direct to an appropriate person to investigate? Thanks.
