### ISSUE TITLE
Attempting to attach large file in Outlook for Windows using Office.context.mailbox.item.addFileAttachmentAsync() fails, but reports the result as successful

### ISSUE THREAD

**Issue by LiamWarnes** [OfficeDev/office-js#992]
I am using Office.context.mailbox.item.addFileAttachmentAsync() to attempt to attach a large .mp4 file (44.6 MB) to an email in compose mode in Outlook for Desktop, and it is reporting that the operation was successful in the result
![image](https://user-images.githubusercontent.com/61216957/74798953-55ffa700-5323-11ea-9dcc-b8368dc397db.png)

but it is then attaching the file with the addition "Download failed" (i.e. it was a failure):
![image](https://user-images.githubusercontent.com/61216957/74798813-f0abb600-5322-11ea-9d34-bbfd3ff54b74.png)

## Expected Behavior
The result received in the callback for the function has a status of "Failed", and an error message something along the lines of:
![image](https://user-images.githubusercontent.com/61216957/74800640-34ed8500-5328-11ea-915a-d65815475f1a.png)

(this is the message that is displayed when attempting to attach the file using the regular attach operation in Outlook)

## Current Behavior
The result received in the callback for the function returns as succeeded. (screenshot above)

## Steps to Reproduce, or Live Example
I cant really provide steps to reproduce because it is happening inside a newly developed feature of an Outlook add-in, but simply calling the function using the same file type and a uri for that file as provided in the details below should yield similar results. It occurs on 100% for similar files for me (tested multiple files)

* Additional details:
  1. This only happens in Outlook for Windows (Desktop Client). In other versions of Outlook e.g. OWA on Chromium Edge, the result status comes back correctly as failed, although the corresponding error message is incorrect (i will report this in a separate issue).
  2. The mp4 file is in a SharePoint library. The URI provided to the addFileAttachmentAsync function is obtained via Microsoft Graph driveItem. See this page for reference https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0. The uri on that resource in particular is the downloadUrl (under Instance Attributes)
  3. Outlook desktop is using Edge for the add-in that this is supposed to be working with
 

## Context
We are developing a feature to insert files into emails from SharePoint. In this case, if the result is being returned as a success when it is in fact a failure, then i cannot implement custom handling to deal with that failure.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook [Edge]
* Office version number: Version 2002 (Build 12527.20138)
* Operating System: Windows 10
* Browser (if using Office Online): N/A

Eagerly awaiting your reply

Many thanks.

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding addFileAttachmentAsync(). It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: Office:3965795

**Comment by Oleg-O** [comment]
The bug appears to have been fixed a while ago (~September 2020) and integrated in build 16.0.13310.10000.
