### ISSUE TITLE
Error in result from Office.context.mailbox.item.addFileAttachmentAsync() is only being returned as "Internal Error"

### ISSUE THREAD

**Issue by LiamWarnes** [OfficeDev/office-js#993]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

Attaching a large mp4 file (44.6 MB) to an email in compose mode using the regular attach file option in outlook will display the failure and an error saying the attachment was too large:
![image](https://user-images.githubusercontent.com/61216957/74802790-fad3b180-532e-11ea-829d-2b57c28b978c.png)

I believe this is in line with the documentation on the addFileAttachmentAsync function and should correspond to the AttachmentSizeExceeded error:
![image](https://user-images.githubusercontent.com/61216957/74802947-6fa6eb80-532f-11ea-9212-64b450489cb3.png)

Yet when calling the Office.context.mailbox.item.addFileAttachmentAsync() function, in the event of failure, the only error message being received in the callback is "Internal Error":
![image](https://user-images.githubusercontent.com/61216957/74802455-0a9ec600-532e-11ea-9781-7067fded4564.png)

In fact, the only error I ever receive in the callback to this function is Internal Error. We are trying to develop a feature that uses this function and it is completely inconsistent with what it will or will not attach (variety of files; small and large, different types), the example provided is only used because i know it is an instance where i can expect an error 100% of the time, but i suspect this is happening across the board. 

As a developer, trying to narrow down what is the cause of these errors is extremely hard when the only information i have is "An internal error occurred". An additional consideration is that if the error is legitimate (as in the case with this large file), i want present the user with a meaningful message as to why - "An internal error occurred" is not meaningful.

I suspect that errors are not being sent properly in the result for the callback for this function.

## Expected Behavior
When attaching a large file, the error message comes back as something along the lines of "Attachment size exceeded"

## Current Behavior
When attaching a large file, the error message comes back as "Internal Error"

## Steps to Reproduce, or Live Example
Use the function to attach a large file. The file used in the example above is in a SharePoint library. It is accessed using the Microsoft Graph driveItem. See https://docs.microsoft.com/en-us/graph/api/resources/driveitem?view=graph-rest-1.0 for reference. The particular uri that is passed to the addFileAttachmentAsync function is the downloadUrl on this resource (under Instance Attributes).

## Context
In custom handling of any failures I would like to report to the user a meaningful message as to why the attachment operation is failing. "An internal error occurred" is not meaningful.

Additionally, in developing the feature where i am using the function, having errors only reported as Internal Error means that i cant investigate further the cause of the error.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: Office Online
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: 
* Operating System:
* Browser (if using Office Online): Chromium Edge

## Useful logs

- [ ] Console errors
- [ ] Screenshots
- [ ] Test file (if only happens on a particular file)

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding addFileAttachmentAsync() in Office Online. It has been put on our backlog. We unfortunately have no timelines to share at this point.

**Comment by exextoc** [comment]
Internal tracking id: OutlookWeb:78725

**Comment by LiamWarnes** [comment]
Hi,

I have reviewed the changes that have been implemented to address this issue. Using the same process outlined in the original issue on various platforms, here are my findings:

Outlook Desktop Client for Windows  - Requirement set 1.9
![image](https://user-images.githubusercontent.com/61216957/132786755-4d71e8eb-0a3b-4b4f-8edd-cacf80d0d0a1.png)

An error is returned with expected reason as cause✔, although I believe the message can be refined*. Suggestion for message: "_The attachment cannot be added because it exceeds the maximum size allowed by Outlook_" 

-------
*note for error messages - I have noticed that error responses are returned with codes/names that may be able to mapped for custom handling of the response:
![image](https://user-images.githubusercontent.com/61216957/132787307-7a5c1247-0aa1-46b1-b555-87bca54b309b.png)

however, I can find limited documentation regarding what the expected response code/names might be, I have seen codes/names returned that are not in the existing documentation. Is documentation up to date? Without knowing what codes to expect, custom handling cannot be added, and that leaves only the possibility to trust the message returned with the error, which may, from my perspective at least, require refinement.

-------

OWA in Edge - Requirement set 1.9
![image](https://user-images.githubusercontent.com/61216957/132792097-6f86b5a6-c6ce-4a14-8d8b-4a2aa0d60a4b.png)

An error is returned with general error as the cause ⚠. My main concern here is; why has OWA returned a different error message to the desktop client for the same operation?

Can the general error be improved? Again; the issue highlighted the need to provide a meaningful message to the user, it seems "internal error" could just have been replaced with this "general error" - it looks nicer, but beyond that, it doesn't serve much more of a purpose.

I found the above to be consistent with OWA in other browsers; IE, Chrome, Firefox, Safari

**Comment by exextoc** [comment]
Thanks for reporting this issue regarding the error message in Office.context.mailbox.item.addFileAttachmentAsync() . It has been put on our backlog. We, unfortunately, have no timelines to share at this point.

Internal tracking id: Outlook Web: 78725

**Comment by rkpathak** [comment]
This issue has been fixed and rolled out.
