### ISSUE TITLE
Table Row delete() is not working when there is a filter apply to the table.

### ISSUE THREAD

**Issue by chanhohang** [OfficeDev/office-js#994]
Sample code to reproduce the problem

```  
Excel.run(async context => {
 let table = await getTable(context, 'abc')
await clearAllRows(context, table)

})

static async getTable(context, tableName) {
    let workbook = context.workbook
    workbook.load('tables')
    await context.sync()
    let tables = workbook.tables
    tables.load('items/name')
    await context.sync()
    let table = tables.getItem(tableName)
    await context.sync()
    table.load('worksheet')
    await context.sync()
    return table
  }
  static async getTableRows(context, table) {
    table.load('rows, rows/count')
    // await context.sync()
    let tableRows = table.rows
    // tableRows.load('count')
    await context.sync()
    return tableRows
  }

static async clearAllRows(context, table) {
    let tableRows = await ExcelContextUtil.getTableRows(context, table)
    for (let i = tableRows.items.length - 1; i >= 0; i--) {
      let tableRow = tableRows.items[i]
      tableRow.getRange().delete(Excel.DeleteShiftDirection.up)
    }
    await context.sync()
  }
```

the code above is working to remove all the records of a table when there is no filter.

When a table is having a filter, the rows are not deleted at all.

Can you kindly check if you can reproduce the problem?

**Comment by lumine2008** [comment]
Thanks @chanhohang, it seems the code you provide cannot run successfully, would you mind to share the gist? you could use script lab and upload your gist.
![image](https://user-images.githubusercontent.com/26398035/74941805-a57ec980-542e-11ea-8700-50d9ac5a84c3.png)

**Comment by chanhohang** [comment]
Hi @lumine2008 ,
Please find the gist by following this link
https://gist.github.com/chanhohang/ee6e1cd608e06a51346a3eb13ea42736

To reproduce the problem, you have to create an Excel Table, and then apply column filter (e.g. exclude all blank values for this column), and then click the button.

**Comment by lumine2008** [comment]
Thanks @chanhohang , i can repro it. we have done some investigation, and based on our investigation, The API behavior is aligned with UI, as in UI it does not allow ins/del of table cells in the presence of Table filters. 

 ![image](https://user-images.githubusercontent.com/26398035/75026636-49707f80-54d8-11ea-8a7a-b623e5b1ba27.png)
In UI, when there is no filter you can delete Table Rows, But if there is filter, you can only delete entire row. It is not allowed to delete table row when filter is on.
![image](https://user-images.githubusercontent.com/26398035/75026740-6c9b2f00-54d8-11ea-8fa2-ad4efa7f4ead.png)

So this API is by design

**Comment by Zlatkovsky** [comment]
@lumine2008 , that's a great find.  Is something that can be added to the documentation for the `table.delete()` API?

**Comment by chanhohang** [comment]
@lumine2008 thanks for explaining.
I can understand this is the same behavior from the UI.

what will be your suggestion if we need to remove row/ clear tables when there is filter applied to the table?

**Comment by lumine2008** [comment]
Maybe you could delete the entire sheet row?

**Comment by chanhohang** [comment]
@lumine2008 we are now using a workaround, instead of delete row, we set all rows cells into empty string and can perserve the sorting. i am closing this issue now.
