### ISSUE TITLE
Edge Webview - Can't authenticate with Azure SSO when conditional access requires domain joined

### ISSUE THREAD

**Issue by mmatu-fmb** [OfficeDev/office-js#995]
## Expected Behavior
Edge WebView should pass conditional access checks like IE was able to prior to 1903 in Outlook Plugins.

## Current Behavior
Opening a plugin thru Outlook launches the SSO authentication process and fails because it appears that the device is not domain joined.  All other O365 applications work as intended and pass these checks normally.

## Steps to Reproduce, or Live Example

* Link to live example: ______

* Additional details:
  1. Enable Salesforce Plugin
  2. Configure SSO authentication in Azure for Salesforce
  3. Configure conditional access requiring domain joined in Intune.
  4. Attempt to authenticate thru the plugin which uses the Edge WebView

## Context
Users would like to continue to use the integration that was working prior to the 1903 build of Windows 10 when the Edge Webview was introduced to replace the IE shell for web access from the Office apps.  This is something we have been using for a little while now and unless we revert back to a previous version of Windows, we can not continue to use it without changing our security posture in InTune.

## Your Environment

* Platform [PC desktop, Mac, iOS, Office Online]: PC Desktop
* Host [Excel, Word, PowerPoint, etc.]: Outlook
* Office version number: O365 Pro Plus Version 2001 (Build 12430.20264)
* Operating System: Windows 10

## Useful logs

You can't get there from here
This application contains sensitive information and can only be accessed from:
 domain joined devices. Access from personal devices is not allowed.
Sign out and sign in with a different account 
More details 
Request Id: a618cd49-9c93-4ddd-a482-7ee3ec872e00 
Correlation Id: 8fe234e7-0ca8-48bb-a624-cdc6b1b73f41 
Timestamp: 2020-02-20T13:59:27.777Z 
App name: Salesforce Production
App id: 8a3b8d84-1dd2-4606-bce7-0e145ba9c355
IP address: 
Device identifier: Not available
Device platform: Windows 10
Device state: Unregistered
Advanced diagnostics: Disable 
If you plan on getting support for an issue, turn this on and try to reproduce the error. This will collect additional information that will help troubleshoot the issue.

**Comment by exextoc** [comment]
To make sure we are looking at the same thing, are you referring to the Salesforce addin from the office store https://appsource.microsoft.com/en-us/product/office/WA104379334?src=office&tab=Overview ?

**Comment by mmatu-fmb** [comment]
Yes that is correct.

**Comment by Sayyed-Abbas** [comment]
Hi,
I am experiencing same behavior on the app SAML with AWS. 

Then webview is currently showing on iOS that the device is not managed 

You Can’t get from here 
You cannot access the resource from this browser on your device. You need to use Safari or Edge.

Request Id: 6a313ace-7525-410e-8f4c-fc5df6330500
Correlation Id: bad1f61a-780f-46a6-8f46-2ae53c5c2398
Timestamp: 2020-03-05T06:10:51.040Z
App name: my-aws - saml-app
App id: ******************
IP address: 98.201.129.196
Device identifier: Not available
Device platform: iOS
Device state: Unregistered
Advanced diagnostics: Disable
If you plan on getting support for an issue, turn this on and try to reproduce the error. This will collect additional information that will help troubleshoot the issue.

**Comment by exextoc** [comment]
This issue with Edge WebView is known, but there is no additional information to provide at this time. @Sayyed-Abbas you should open a separate issue for iOS.

**Comment by LaurentV9** [comment]
Hi, I have the same issue. Is there a solution to this?

Laurent

**Comment by Sayyed-Abbas** [comment]
You need to use broker service via Authenticator.

Update your info.plist with MS-Authenticator SDK , repackage and deployed to Intune.

The app compliance will be accessible only via Authenticator App.

**Comment by LaurentV9** [comment]
Hi, thanks for your response but my error in for Windows 10 and not for IOS. As explained in first post by mmatu-fmb 

Laurent

**Comment by jargil** [comment]
@LaurentV9 - This problem should be resolved by applying the latest Windows updates. Please let me know if after updating to the latest you still have problems.

**Comment by mmatu-fmb** [comment]
@jargil This issue self resolved for us a month or two ago after Microsoft 365 and Windows updates.  Was this officially addressed in a specific update?  Do you know if it was on the 365 side or Windows side?  Just trying to get some clarification for our management because we never received any notification and want to be 100% sure that there wasn't some other random change that fixed it.

**Comment by jargil** [comment]
@mmatu-fmb - Good to hear. Yeah it was specifically addressed with a Windows update. It was released as multiple patches, depending on which OS version you have installed. Releases happened on or around 7/21 and 7/31.
This is one example, you can scroll down and you'll see a mention to Conditional Access and Office.:
https://support.microsoft.com/en-us/help/4568831

**Comment by LaurentV9** [comment]
> @mmatu-fmb - Good to hear. Yeah it was specifically addressed with a Windows update. It was released as multiple patches, depending on which OS version you have installed. Releases happened on or around 7/21 and 7/31.
> This is one example, you can scroll down and you'll see a mention to Conditional Access and Office.:
> https://support.microsoft.com/en-us/help/4568831

Hi,

Many thanks for your help but We are in Windows10 1909. Do you know if there is an update for this version? the link you provided is for 2004 version.

Regards,

Laurent

**Comment by jargil** [comment]
@LaurentV9 - updating from within Windows to apply the latest patches should work. If you want to manually just apply this patch, then this one should work for 1909:
https://support.microsoft.com/en-us/help/4559004

**Comment by LaurentV9** [comment]
Many thanks. I tried with last CU from September and it works.

Best regards,

Laurent
