### ISSUE TITLE
displayMessageForm failures without an indicator

### ISSUE THREAD

**Issue by jlevenssfdc** [OfficeDev/office-js#996]
There appears to be some race conditions around the outcome of this feature that cause a failure when a newly created item.itemId is specified.  The caller/consumer has no indication that the request failed.

## Expected Behavior
The ability to display a message form should permit a callback to be passed that expects an indicator of success/failure for the request.

## Current Behavior
When displayMessage form fails the caller is never made aware.
Allowing a callback to be passed would permit the request to handle the failure.

## Steps to Reproduce, or Live Example
(psuedo)

```
const request = // create new draft xml
Office.context.mailbox.makeEwsRequestAsync(request, (asyncResult) => {
    const draftId = parseXmlAndGetItemIdFromResponse(asyncResult.value)
    Office.context.mailbox.displayMessageForm(draftId);
})
```

## Context
Attempting to create an email draft with an EWS request then displaying the new draft in a message form.  

## Your Environment

This bug can be reproduced in all versions, platforms, hosts.  The nature of the race condition may mean that multiple attempts are required to reproduce.

* Platform [PC desktop, Mac, iOS, Office Online]: ALL
* Host [Excel, Word, PowerPoint, etc.]: Outlook Client / Browser
* Office version number: ALL
* Operating System: ALL
* Browser (if using Office Online): ALL

## Useful logs
n/a

**Comment by exextoc** [comment]
API "displayMessageForm" does not provide a callback method. So, we do not pass information on API response as mentioned in the documentation here in the [document ](https://docs.microsoft.com/en-us/javascript/api/outlook/office.mailbox?view=outlook-js-1.5#displaymessageform-itemid-)

**Comment by jlevenssfdc** [comment]
@exextoc Should this be a feature request?

**Comment by exextoc** [comment]
yes please add to the[ user voice](https://officespdev.uservoice.com/forums/224641-general/category/131778-outlook-add-ins)

**Comment by lindalu-MSFT** [comment]
@jlevenssfdc Please provide the link to the UserVoice feature request! Thanks, linda

**Comment by jlevenssfdc** [comment]
@lindalu-MSFT https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/39800023-add-displaymessageformasync-to-office-js-so-that-i

**Comment by lindalu-MSFT** [comment]
@jlevenssfdc THANKS! Closing this issue for now.

**Comment by JuaneloJuanelo** [comment]
@jlevenssfdc this feature is in preview now. if you install the latest insider fast you will see that all the display methods now have an Async flavor you can use to see if the item exists or not. (with a callback) i.e. Office.context.mailbox.displayAppointmentFormAsync(ewsID, function(result) .....
