### ISSUE TITLE
Word: context.sync() fails when context.document.body.getOoxml() runs on document with layered images

### ISSUE THREAD

**Issue by fdjones** [OfficeDev/office-js#998]
> Message from office-js bot:
We’re closing this issue because it has been inactive for a long time. We’re doing this to keep the issues list manageable and useful for everyone. If this issue is still relevant for you, please create a new issue.
> Thank you for your understanding and continued feedback.

We are getting an issue that with some documents that include (lots of) layered images, context.sync() is failing and throwing an error in the console. We think it may be to do with the size of the xml that `getOoxml` returns..?

## Expected Behavior
For context.sync() to work as usual

## Current Behavior
See above

## Steps to Reproduce, or Live Example
Create a document and add in a layered image which has multiple large images in in (>500kb). Try to use `getOoxml()` and then do `context.sync()` and you will see it fails. This is happening when we reproduce it in script lab so it's not our own implementation.

## Context
We are trying to parse the document to get relevant metadata and determine what to display to users based on this. Unfortunately converting to HTML doesn't work as this metadata is not preserved.

## Your Environment
* Platform: Macbook Pro 2019, macOS Mojave v10.14.6
* Host: Microsoft Word for Mac
* Office version number: 16.33
* Operating System: Mojave v10.14.6
* Browser (if using Office Online): ______

## Useful logs

- [ ] Console errors:

```
Oops! Something went wrong!
Message: RichApi.Error: GeneralException,
FileName: https://our-file
Line Number: 17,
Column Number: 18487
Stack trace:
 (1)
RuntimeError — word-mac-16.00.debug.js:10660
processRequestExecutorResponseMessage — word-mac-16.00.debug.js:13741
(anonymous function) — word-mac-16.00.debug.js:13648
nrWrapper — word:17:18445
promiseReactionJob
```

**Comment by JuaneloJuanelo** [comment]
Hello thanks for reporting this issue. I was not able to repro it. We'll need more details to try to repro in our end.[ This is the snippet](https://gist.github.com/JuaneloJuanelo/1fc0bad0770c39ab6ce23f3520c641cb) i am using to test (you can restore in script lab): 

1. By Any chance you can provide a sample document so we can try?
2. Can you please confirm this only happens on the Mac?

**Comment by DannyHinshaw** [comment]
@JuaneloJuanelo may we please reopen this? I'm having this same issue except there's no need to add "layered images", this is occurring on just plain blank documents. The way we are using it is to check for chart xml to detect if the cursor is on a chart title.

I've tested on both Windows & Mac and can confirm they are both affected. It seems as though this bug/issue was introduced with a version update as when I initially tested it on Windows it worked, then I ran updates and it is now screwed like its Mac counterpart. 

Here are the current versions, I apologize that I didn't have the foresight to get the working Windows Word version number before updating :(

**Versions**
Word for Mac: 
16.35 (20030802)

MS Word for Office 365 MSO (Windows 10):
16.0.12624.20348 (64-bit)

**Reproduce**
Here's a repo for reproducing the error. It's just the Yeoman Word React TypeScript generated app with the `range.getOoxml` codes snippet from the documentation inserted to the button click handler.
https://github.com/DannyHinshaw/test-word-context

To reproduce:
1. Sideload the addon
2. Add a simple bar chart and move cursor to the chart title text.
3. Click the button in the Add-On and see in console the errors.

**Comment by JuaneloJuanelo** [comment]
re-opening, sample document was provided offline.

**Comment by JuaneloJuanelo** [comment]
I am diagnosing the issue now, with the file provided, its a huge image and it takes time, but i am able to get the OOXML and then insert it in Windows. Now we will test on the Mac.

@DannyHinshaw  your issue is a different one, we are correctly investigating your issue in a separate issue here https://github.com/OfficeDev/office-js/issues/1097

**Comment by JuaneloJuanelo** [comment]
we are tracking this investigation, and potential bug with 4158702

**Comment by RBILLC** [comment]
@JuaneloJuanelo, I believe I am experiencing the same error when calling body.getOoxml() in a Word document that contains a Shape grouped with a Picture. If I ungroup the 2 features than the API function runs successfully. **Is there any update on bug 4158702?**

**Version:**
Microsoft® Word for Microsoft 365 MSO (Version 2203 Build 16.0.15028.20152) 32-bit 

Using the following code:

            // Create a proxy object for the document body.
            var body = context.document.body;

            // Queue a command to get the OOXML contents of the body.
            var bodyOOXML = body.getOoxml();

            // Synchronize the document state
            await context.sync();

Returns this error message:
```
{
    "error": {
        "name": "RichApi.Error",
        "code": "GeneralException",
        "traceMessages": [],
        "innerError": null,
        "debugInfo": {
            "code": "GeneralException",
            "message": "GeneralException",
            "errorLocation": "Body.getOoxml",
            "statement": "body.getOoxml();",
            "surroundingStatements": [
                "...",
                "var body = root.body;",
                "// Instantiate {body}",
                "var paragraphs = body.paragraphs;",
                "// Instantiate {paragraphs}",
                "paragraphs.load([\"text\",\"style\"]);",
                "// >>>>>",
                "body.getOoxml();",
                "// <<<<<"
            ],
            "fullStatements": [
                "var root = context.root;",
                "var body = root.body;",
                "// Instantiate {body}",
                "var paragraphs = body.paragraphs;",
                "// Instantiate {paragraphs}",
                "paragraphs.load([\"text\",\"style\"]);",
                "body.getOoxml();"
            ]
        },
        "httpStatusCode": 500
    }
}
```

**Comment by marcotonani** [comment]
We are having the same issue mentioned by @RBILLC just above.
When calling the getOoxml method from word desktop we are getting a RichApi.Error GeneralException.
Using word online instead we are able to get the ooxml for the same document.
As @RBILLC said if we ungroup the image present in the document everything works correctly.
I'm attaching the word document that cause the issue.

Version:
Microsoft® Word for Microsoft 365 MSO (Version 2211 Build 16.0.15813.20000) 64-bit 

[Weird add-in bug for sharing.docx](https://github.com/OfficeDev/office-js/files/9860055/Weird.add-in.bug.for.sharing.docx)
