### ISSUE TITLE
Deployment. Self hosting the source (?)

### ISSUE THREAD

**Issue by ybrodsky** [OfficeDev/office-js#999]
## Article URL
https://docs.microsoft.com/en-us/office/dev/add-ins/publish/publish

Greetings.
I have built a add-in for Outlook following the tutorials. When the time came to deploy, I made a build and uploaded the dist files to a personal server. Its accessible through the web without restricting, the files are all being served correctly.
Then I edited my manifest.xml file changing the file source from `localhost:3000` to my online url.

When I tried to install the add-in in Outlook, desktop application, it installs and displays correctly. However, when clicking on the button to see the taskpane, outlooks reports a network error and tells me to make sure I am connected to the internet.

I tried installing the add-in in the web client at `outlook.office.com` and it installed and loads correctly. No network error whatsoever.

So my question is, is it possible that Outlook deskptop is blocking the requests to my custom server?
Is my method of deployment valid at all, or am I forced to go through AppSource?

Thanks, I googled this but could not find anything related to my particular problem / question.

**Comment by lindalu-MSFT** [comment]
@ybrodsky Have you been able to resolve this issue? Our team needed more info from  you to investigate. Please provide the info requested by exextoc.

**Comment by ybrodsky** [comment]
Hi, sorry for the lack of response, I have been away.
I was going to check the AppSource deployment method when I opened outlook and it started working. Outlook showed a prompt asking me permission to access the internet and after that it was working.

So kinda fixed itself (?).

If you know there are no restrictions in the desktop app to access foreign urls like I did, then I guess you can close this.

**Comment by lindalu-MSFT** [comment]
Thanks for the update!!
